### ISSUE TITLE
showDatePicker throws null exception on web

### ISSUE THREAD

**Issue by gxsham** [flutter/flutter#79129] opened 2021-03-26 08:21 UTC
## Steps to Reproduce

```
DateTime currentDate = DateTime.now();

Future<void> _selectDate(BuildContext context) async {
    final DateTime? pickedDate = await showDatePicker(
        context: context, initialDate: currentDate, firstDate: DateTime(2015), lastDate: DateTime(2050));
    if (pickedDate != null && pickedDate != currentDate)
      setState(() {
        currentDate = pickedDate;
      });
  }
  
 @override
 Widget build(BuildContext context) {
    return Center(
        child: TextButton(
      onPressed: () => _selectDate(context),
      child: Text('Select date'),
    ));
  }
``` 

To reproduce the problem I'll use this code. A simple example of a date picker.

1. Run `flutter run -d chrome`.
2. Click on the 'Select date; button.
3. Click on any day or try to select any year.

**Note:** Worked fine on android.

**Expected results:** Expect the 'currentDate' to be set. 

**Actual results:** Throws the exception shown below.

<details>
  <summary>Logs</summary>

```
[+2003 ms] Error: Expected a value of type 'String', but got one of type 'Null'
                        at Object.throw_ [as throw] (http://localhost:62014/dart_sdk.js:5032:11)
                        at Object.castError (http://localhost:62014/dart_sdk.js:5005:15)
                        at Object.cast [as as] (http://localhost:62014/dart_sdk.js:5314:17)
                        at Function.as (http://localhost:62014/dart_sdk.js:42400:19)
                        at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:62014/dart_sdk.js:155298:38)
                        at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:62014/dart_sdk.js:155214:33)
                        at _DefaultBinaryMessenger.[_sendPlatformMessage]
(http://localhost:62014/packages/flutter/src/services/system_channels.dart.lib.js:2180:38)
                        at _DefaultBinaryMessenger.send (http://localhost:62014/packages/flutter/src/services/system_channels.dart.lib.js:2224:40)
                        at OptionalMethodChannel._invokeMethod (http://localhost:62014/packages/flutter/src/services/system_channels.dart.lib.js:948:50)
                        at _invokeMethod.next (<anonymous>)
                        at runBody (http://localhost:62014/dart_sdk.js:37229:34)
                        at Object._async [as async] (http://localhost:62014/dart_sdk.js:37260:7)
                        at OptionalMethodChannel.[_invokeMethod] (http://localhost:62014/packages/flutter/src/services/system_channels.dart.lib.js:946:20)        
                        at OptionalMethodChannel.[_invokeMethod] (http://localhost:62014/packages/flutter/src/services/system_channels.dart.lib.js:1078:34)       
                        at OptionalMethodChannel.invokeMethod (http://localhost:62014/packages/flutter/src/services/system_channels.dart.lib.js:1056:36)
                        at invokeMethod.next (<anonymous>)
                        at runBody (http://localhost:62014/dart_sdk.js:37229:34)
                        at Object._async [as async] (http://localhost:62014/dart_sdk.js:37260:7)
                        at OptionalMethodChannel.invokeMethod (http://localhost:62014/packages/flutter/src/services/system_channels.dart.lib.js:1055:20)
                        at vibrate (http://localhost:62014/packages/flutter/src/services/haptic_feedback.dart.lib.js:30:55)
                        at vibrate.next (<anonymous>)
                        at runBody (http://localhost:62014/dart_sdk.js:37229:34)
                        at Object._async [as async] (http://localhost:62014/dart_sdk.js:37260:7)
                        at Function.vibrate (http://localhost:62014/packages/flutter/src/services/haptic_feedback.dart.lib.js:29:20)
                        at calendar_date_picker._CalendarDatePickerState.new.[_vibrate]
                        (http://localhost:62014/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2654:42)
                        at calendar_date_picker._CalendarDatePickerState.new.[_handleDayChanged]
                        (http://localhost:62014/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2702:21)
                        at calendar_date_picker._MonthPickerState.new.[_handleDateSelected]
                        (http://localhost:62014/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3130:11)
                        at http://localhost:62014/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3539:28
                        at ink_well._InkResponseState.new.[_handleTap] (http://localhost:62014/packages/flutter/src/material/icon_button.dart.lib.js:50084:42)    
                        at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:62014/packages/flutter/src/gestures/recognizer.dart.lib.js:201:18)       
                        at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:62014/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
                        at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:62014/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
                        at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:62014/packages/flutter/src/gestures/tap.dart.lib.js:199:23)
                        at arena.GestureArenaManager.new.sweep (http://localhost:62014/packages/flutter/src/gestures/arena.dart.lib.js:221:31)
                        at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:62014/packages/flutter/src/gestures/binding.dart.lib.js:334:27)      
                        at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:62014/packages/flutter/src/gestures/binding.dart.lib.js:313:24)    
                        at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:62014/packages/flutter/src/rendering/layer.dart.lib.js:6071:13)    
                        at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately]
(http://localhost:62014/packages/flutter/src/gestures/binding.dart.lib.js:284:14)
                        at binding$5.WidgetsFlutterBinding.new.handlePointerEvent
(http://localhost:62014/packages/flutter/src/gestures/binding.dart.lib.js:257:43)
                        at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue]
(http://localhost:62014/packages/flutter/src/gestures/binding.dart.lib.js:246:14)
                        at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket]
(http://localhost:62014/packages/flutter/src/gestures/binding.dart.lib.js:236:65)
                        at Object.invoke1 (http://localhost:62014/dart_sdk.js:173249:7)
                        at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:62014/dart_sdk.js:155201:15)
                        at _engine.PointerBinding.__.[_onPointerData] (http://localhost:62014/dart_sdk.js:155815:49)
                        at http://localhost:62014/dart_sdk.js:156224:26
                        at http://localhost:62014/dart_sdk.js:156183:16
                        at http://localhost:62014/dart_sdk.js:155908:11
```

```
```

[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web  
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)      
[√] Connected device (2 available)

• No issues found!
</details>

**Comment by pedromassangocode** [comment] 2021-03-26 10:17
Hi @gxsham 
I cannot reproduce the issue with the complete code sample listed bellow.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: MyApp(),
    )
  ));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  DateTime currentDate = DateTime.now();

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? pickedDate = await showDatePicker(
        context: context, initialDate: currentDate, firstDate: DateTime(2015), lastDate: DateTime(2050));
    if (pickedDate != null && pickedDate != currentDate)
      setState(() {
        currentDate = pickedDate;
      });
  }

  @override
  Widget build(BuildContext context) {
    return Center(
        child: TextButton(
          onPressed: () => _selectDate(context),
          child: Text('Select date'),
        ));
  }
}
```
</details>

**Comment by gxsham** [comment] 2021-03-26 11:17
Hi @pedromassangocode, 

Did you run it on web? The issue is only on the web platform. It used to work fine before migrating to null safety.

**Comment by gxsham** [comment] 2021-03-26 11:23
A small update, if I run it with ```flutter run --no-sound-null-safety``` then it works fine. 

But as all the packages I'm using in my app are migrated already I am building **with** sound null-safety. Would be a shame to build without it only because of this issue.

**Comment by pedromassangocode** [comment] 2021-03-26 13:04
> Did you run it on web?

Yes I did.

![gif](https://user-images.githubusercontent.com/67424416/112635465-25e6d980-8e3c-11eb-916a-0508ffaf137e.gif)

**Comment by gxsham** [comment] 2021-03-26 14:18
Then we can close the issue. I have no clue what's the problem yet, should be something on my side. 
One of my friends tried on his machine and got the same exception as I did.

**Comment by alnah005** [comment] 2021-03-27 22:28
I was getting this issue on web then I ran it with --no-sound-null-safety and the error went away.

**Comment by gxsham** [comment] 2021-03-27 22:54
> I was getting this issue on web then I ran it with --no-sound-null-safety and the error went away.

I said the same a few comments back. I know it's a null safety issue. But I want the flutter team to know it too so they can fix it. But it seems they cannot reproduce it

> A small update, if I run it with `flutter run --no-sound-null-safety` then it works fine.
> 
> But as all the packages I'm using in my app are migrated already I am building **with** sound null-safety. Would be a shame to build without it only because of this issue.
> 
> Thank you for your time and help!

**Comment by pedromassangocode** [comment] 2021-03-29 07:29
> Then we can close the issue. I have no clue what's the problem yet, should be something on my side.
> One of my friends tried on his machine and got the same exception as I did.

Closing this for now. Please write in the comments bellow if you have a reproducible sample/steps so that I can verify it again.
Thank you

**Closed by pedromassangocode** 2021-03-29 07:29 UTC
Labels: in triage

**Comment by Levi-Lesches** [comment] 2021-04-27 17:30
For what it's worth, I got a response over at #79834 that this was fixed in master, probably why it couldn't be reproduced.
