### ISSUE TITLE
timeout waiting for the application to start 

### ISSUE THREAD

**Issue by jayantakumar** [flutter/flutter#23947] opened 2018-11-05 19:22 UTC
**Log:**
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
#timeout waiting for the application to start
#23861 
Syncing files to device GT I9300...
I/Process (27308): Sending signal. PID: 27308 SIG: 9
Lost connection to device.

**PLEASE HELP ME!!**

**Comment by DanTup** [comment] 2018-11-06 20:55
This appears to be a duplicate of #23861 which is mentioned in your comment (and maybe #22338). If you think this is a different problem and needs its own issue, please add some additional info why.

**Closed by DanTup** 2018-11-06 20:55 UTC
