### ISSUE TITLE
Flutter run --release app crashes on start

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#17470] opened 2018-05-10 13:15 UTC
## Steps to Reproduce
When I run the command "Flutter run --release", after building and installing on my device, the app crashes on start with this :
## Logs
F/flutter (26289): [FATAL:flutter/runtime/dart_vm.cc(413)] Error while initializing the Dart VM: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-type_checks no-asserts no-error_on_bad_type no-error_on_bad_override arm-eabi hardfp' but the VM has 'product no-type_checks no-asserts no-error_on_bad_type no-error_on_bad_override arm-eabi softfp'
Application finished.

**NB:-**, worked fine on my dev channel v0.4.0., then crash started after upgrade v0.4.2
Also works fine on current beta

the device am working with is:
Samsung Tab A SM T555 • 7779e875 • android-arm • Android 7.1.1 (API 25)

This crash currently happens on 
**dev**
[√] Flutter (Channel dev, v0.4.2, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
    • Flutter version 0.4.2 at M:\flutter
    • Framework revision de332ec782 (3 days ago), 2018-05-07 14:13:53 -0700
    • Engine revision e976be13c5
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.23.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.12.1

[√] Connected devices (1 available)
    • SM T555 • 7779e875 • android-arm • Android 7.1.1 (API 25)

• No issues found!

crash also happen current master channel:
[√] Flutter (Channel master, v0.4.3-pre.71, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
    • Flutter version 0.4.3-pre.71 at M:\flutter
    • Framework revision ca94bfdfc6 (7 hours ago), 2018-05-09 22:42:38 -0700
    • Engine revision 11d6da3cd9
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.23.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.12.1

[√] Connected devices (1 available)
    • SM T555 • 7779e875 • android-arm • Android 7.1.1 (API 25)

• No issues found!

**Comment by NMateu** [comment] 2018-05-10 13:36
same as https://github.com/flutter/flutter/issues/17387

**Comment by MichaelSowah** [comment] 2018-05-10 14:09
likely but error logs dont look the same

**Comment by cbracken** [comment] 2018-05-10 18:15
Closing as dupe of #17387. Fix should be landing shortly in #17453.

**Closed by cbracken** 2018-05-10 18:15 UTC
