### ISSUE TITLE
MissingPluginException start project from Vscode but in AS works fine

### ISSUE THREAD

**Issue by Alexufo** [flutter/flutter#68422] opened 2020-10-18 04:02 UTC
I have android application with flutter as module integrated as[ option B.](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-b---depend-on-the-modules-source-code)

If I run project from Android studio all works fine. But if I run project  from VScode, my button inside project return exception.

![2020-10-18_06-59-04](https://user-images.githubusercontent.com/1562329/96358402-76c90800-110f-11eb-80ea-41ac35536006.jpg)

I cant call any native code  throught platform channels. But flutter application starts and works good.

![2020-10-19_03-55-20](https://user-images.githubusercontent.com/1562329/96390840-1b565300-11bf-11eb-90c5-491ba559f037.jpg)

<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.92, on Microsoft Windows [Version 10.0.19041.572], locale ru-RU)
    • Flutter version 1.23.0-8.0.pre.92 at C:\flutter
    • Framework revision 79400b2462 (2 weeks ago), 2020-10-01 09:06:46 -0400
    • Engine revision 612acf349e
    • Dart version 2.11.0 (build 2.11.0-180.0.dev)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Salo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\Salo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0
```

</details>

**Comment by briankariuki** [comment] 2020-10-18 06:08
try running `flutter clean`

**Comment by mohitjadav** [comment] 2020-10-18 10:59
in my case, I was trying to run the app with hot reload after just adding dependencies,
after  uninstalling an app it works for me

**Comment by Alexufo** [comment] 2020-10-18 22:31
@briankariuki @mohitjadav it does not help (

**Comment by TahaTesser** [comment] 2020-10-19 11:31
Hi @Alexufo 
Can you please provide a complete reproducible minimal code sample including module and android app 
Thank you

**Comment by Alexufo** [comment] 2020-10-19 18:39
https://github.com/Alexufo/test_r

**Comment by TahaTesser** [comment] 2020-10-20 11:05
Hi @Alexufo 
This is working as expected, you need to launch flutter activity from native to call platform channel methods from a native app

If you want to use the platform channel without a native app, you can add your platform channel code inside the flutter module's android folder, in this case, it is trying to look for that code in the android folder of your module not native app
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-20 11:05 UTC
Labels: in triage
