### ISSUE TITLE
Android Studio (not installed)

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#82354] opened 2021-05-12 15:32 UTC
## Steps to Reproduce

1. Install Android Studio
2. Install Flutter
3. Add flutter\bin to path
4. Run `flutter doctor`

## Logs

<details>
<summary>flutter doctor --verbose</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale pt-BR)
    • Flutter version 2.0.6 at C:\flutter
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\jckod\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Progra~1\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.56.1)
    • VS Code at C:\Users\jckod\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```
</details>

<details>
<summary>java --version</summary>

```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
```
</details>

<details>
<summary>set | grep JAVA</summary>

```
JAVA_HOME=C:\Progra~1\Android\Android Studio\jre
```
</details>

Notice: first, it complained about not accepted Android licenses, I run with ` --android-licenses`, all licenses were accepted.

Android Command Line Tools is installed.

**Comment by TahaTesser** [comment] 2021-05-13 07:58
Hi @JCKodel 
Closing as duplicate of https://github.com/flutter/flutter/issues/82345

**Closed by TahaTesser** 2021-05-13 07:58 UTC
Labels: in triage
