### ISSUE TITLE
[camera][android] `availableCameras()` cannot get the correct camera if the camera is not plugged in when device is powered on

### ISSUE THREAD

**Issue by wenxiangjiang** [flutter/flutter#113730] opened 2022-10-20 01:11 UTC
## Steps to Reproduce

1. Turn on the Android device and keep the camera unplugged.
2. Insert the camera into the device after the device is powered on.
3. Execute `flutter run` on the newest code sample of [camera](https://github.com/flutter/plugins/tree/main/packages/camera/camera)
4. The `availableCameras()` method cannot obtain the correct camera information. (Camera not recognized)
5. Kill the demo application.
6. Turn on the system camera (or other application's camera), and the camera can be recognized correctly.
7. Reopen our application, the `availableCameras()` method works correctly.

**Expected results:** 
The `availableCameras()` method works correctly when first time open the  application.

**Actual results:** 
The `availableCameras()` method works correctly when the system camera (or other application's camera) has opened once.

**Other:**
I try to use `Camera1` to develop android native applications. The scenario described above can be executed correctly. I'm not sure whether it is related to the implementation of `Camera1` and `Camera2`.

**Comment by huycozy** [comment] 2022-10-20 07:43
Hi @wenxiangjiang Do you use an external USB camera? 

May be related/similar: #42413

**Comment by wenxiangjiang** [comment] 2022-10-20 08:15
@huycozy It is an external USB camera. But my device doesn't have any cameras,  the external camera will be recognized as a back camera, not external camera.

**Comment by huycozy** [comment] 2022-10-20 08:36
@wenxiangjiang 
Does the issue happen when you plug the camera into the phone before powering it on? (I mean whether turning on/off the power is an important step in reproducing the issue)
Also, please provide `camera` plugin version you are using as well. Thanks!

**Comment by wenxiangjiang** [comment] 2022-10-20 09:48
@huycozy YES, whether plug the camera into the phone before turn on the power is an important step.

- **Do** plug the camera into the phone, turn on the power, the `availableCameras()` method works **correctly**.
- **Do not** plug the camera into the phone, turn on the power.
  1. launch my application, the `availableCameras()` method works **incorrectly**.
  2. back to desktop, launch system's camera.
  3. back to my application, the `availableCameras()` method works **incorrectly**.
  4. kill my application.
  5. launch my application, the `availableCameras()` method works **correctly**.
- **Do not** plug the camera into the phone, turn on the power.
  1. launch system's camera.
  2. launch my application, the `availableCameras()` method works **correctly**.

I have tried `0.8.1+3` and `0.10.0+3` of `camera` package.

**Comment by stuartmorgan** [comment] 2022-10-20 20:06
I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/42413; it sounds like when you have it already plugged in on power on, the device itself treats the camera as if it weren't external, which means https://github.com/flutter/flutter/issues/42413 isn't triggered. But that's a device-level behavior, not a plugin-level behavior. The core problem when it happens is still https://github.com/flutter/flutter/issues/42413.

**Closed by stuartmorgan** 2022-10-20 20:06 UTC
Labels: e: device-specific, platform-android, plugin, p: first party, p: camera
