### ISSUE TITLE
TextFormField onChanged not called when editing text through TextEditingController in 2.5.0

### ISSUE THREAD

**Issue by mitgolden76** [flutter/flutter#89925] opened 2021-09-11 19:34 UTC
## Steps to Reproduce
Create a TextFormField. Pass in a TextEditingController instance, and store a reference in the containing widget's state class. Specify a onChanged function.

Call `clear()` on the TextEditingController instance. Alternatively, set text manually through `controller.value = TextEditingValue(text: 'some text');`

The onChanged function will not be called on the programmatic editing of the text.

This worked properly in 2.1, but upon the update to 2.5.0, widget tests in my app began failing, and this is the cause.

Here's a simple sample app demonstrating the problem

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(controller: controller, onChanged: (s) => print('I changed...')),
            TextButton(child: const Text('Clear'), onPressed: () => controller.clear(),),
          ],
        ),
      ),
    );
  }
}
```

**Expected results:** 
onChanged function called when the TextButton was pressed ("I changed..." printed to the console)

**Actual results:**
onChanged function is called when text is changed from keyboard, but not from the TextEditingController.

<details>
  <summary>Logs</summary>

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 20.04.3 LTS 5.11.0-34-generic, locale en_US.UTF-8)
    • Flutter version 2.5.0 at /home/mitch/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (4 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/mitch/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/114/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/114/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2021-09-13 09:37
Hi @mitgolden76, I just downgraded to the previous stable (2.2.3) and tried out your code sample, and the `onChanged` wasn't triggered when I clicked the `TextButton`.

Is there something I might be missing?

**Comment by mitgolden76** [comment] 2021-09-13 18:48
> Hi @mitgolden76, I just downgraded to the previous stable (2.2.3) and tried out your code sample, and the `onChanged` wasn't triggered when I clicked the `TextButton`.
> 
> Is there something I might be missing?

I skipped over 2.2 in my project. Last version I was running was 2.1, and it worked back then. I can't seem to restore that version to investigate the difference in the framework now.

**Comment by LongCatIsLooong** [comment] 2021-09-13 19:25
This is intended behavior. The `onChanged` callback will not only be invoked on programmatic text changes: https://master-api.flutter.dev/flutter/material/TextField/onChanged.html

**Comment by danagbemava-nc** [comment] 2021-09-14 08:33
Closing based on [this comment](https://github.com/flutter/flutter/issues/89925#issuecomment-918505959).

**Closed by danagbemava-nc** 2021-09-14 08:33 UTC
Labels: in triage
