### ISSUE TITLE
When using [inputFormatters:], the cursor loops indefinitely

### ISSUE THREAD

**Issue by zhoutengshen** [flutter/flutter#54929] opened 2020-04-16 04:30 UTC
the input cursor kept looping indefinitely, and the keyboard could not be operated and put away. The worst thing was that my phone crashed.

My operation is as follows:
I continuously delete the numbers in [TextField].

Here is a demonstration of the error:
![bug](https://user-images.githubusercontent.com/26021548/79413860-ab7eca00-7fdb-11ea-9aca-abd0ee2f8dd2.gif)

code show as below:
```
      .....
      body: TextField(
        inputFormatters: [CreditCardFormatter()],
      )
     .....
````
```
class CreditCardFormatter extends TextInputFormatter {
  static final RegExp _digitOnlyRegex = RegExp(r'\d+');
  static final WhitelistingTextInputFormatter _digitOnlyFormatter =
  WhitelistingTextInputFormatter(_digitOnlyRegex);
  TextEditingValue _lastNewValue;

  final String separator;

  CreditCardFormatter({this.separator = ' '});

  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {
    /// nothing changes, nothing to do
    if (newValue.text == _lastNewValue?.text) {
      return newValue;
    }
    _lastNewValue = newValue;

    /// Remove all illegal characters
    newValue = _digitOnlyFormatter.formatEditUpdate(oldValue, newValue);

    /// format
    final newText = _formatPattern(newValue.text);

    return newValue.copyWith(
        text: newText,
        selection: TextSelection.collapsed(offset: newText.length),
        composing: TextRange.empty);
  }

  String _formatPattern(String digits) {
    StringBuffer buffer = StringBuffer();
    int offset = 0;
    int count = min(4, digits.length);
    final length = digits.length;
    for (; count <= length; count += min(4, max(1, length - count))) {
      buffer.write(digits.substring(offset, count));
      if (count < length) {
        buffer.write(separator);
      }
      offset = count;
    }
    return buffer.toString();
  }

}
```

**Comment by VladyslavBondarenko** [comment] 2020-04-16 08:37
Hi @zhoutengshen 
could you provide your `flutter doctor -v`?
with what device can you reproduce it?
I tried with `dev  v1.18.0-dev.5.0` on iPhone 7 (iOS 13.4) and iOS 13.4 simulator, couldn't

**Comment by zhoutengshen** [comment] 2020-04-17 03:06
> Hi @zhoutengshen
> could you provide your `flutter doctor -v`?
> with what device can you reproduce it?
> I tried with `dev v1.18.0-dev.5.0` on iPhone 7 (iOS 13.4) and iOS 13.4 simulator, couldn't


this is my info:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\as
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • HRY AL00a • 79URX18B23009927 • android-arm64 • Android 10 (API 29)

• No issues found!

```

and my device:

![1](https://user-images.githubusercontent.com/26021548/79527846-2c50cb00-809b-11ea-8961-d6a24fd7332d.png)


and my solution is to add a throttle function in the [inputFormatters] function

**Comment by VladyslavBondarenko** [comment] 2020-04-17 12:15
@zhoutengshen 
can you reproduce it with the latest stable `v1.12.13+hotfix.9`?
I tried with it on Android 10 emulator and couldn't reproduce as well

**Comment by zhoutengshen** [comment] 2020-04-20 09:02
> the latest stable `v1.12.13+hotfix.9`

the latest stable v1.12.13+hotfix.9 is ok。
but why？ what did version 'hotfix.5' do.

**Comment by VladyslavBondarenko** [comment] 2020-04-20 12:42
@zhoutengshen 
Then it seems to be fixed.
Closing, since there is no need to track the issue.
if you disagree and you can experience this with a version newer than latest stable, please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-04-20 12:42 UTC
Labels: in triage
