### ISSUE TITLE
video_player plugin can cause a crash on iPhone X running iOS 12 when disposing the video controller

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#41125] opened 2019-09-23 17:53 UTC
When popping a page that contains a video on it, and disposing of the video controller in the dispose method could very often cause a crash on an iPhoneX running iOS 12. This happens because the DisplayLink has notified the flutter Texture registry that a frame is ready, and the flutter GPU thread then tries to get the pixel buffer after the FLTVideoPlayer object has been destructed.

The following code leads to the problem:

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class VideoCrashPlayerPage extends StatefulWidget {
  @override
  _VideoCrashPlayerPageState createState() => _VideoCrashPlayerPageState();
}

class _VideoCrashPlayerPageState extends State<VideoCrashPlayerPage> {
  
  VideoPlayerController _videoPlayerController;

  @override
  void initState() {
    super.initState();

    _videoPlayerController = VideoPlayerController.asset("videos/video.mp4");
    _videoPlayerController.addListener(() {
      if (!_videoPlayerController.value.isPlaying) {
        Navigator.pop(context);
      }
    });
    _videoPlayerController.play();
    _videoPlayerController.initialize();
  }

  @override
  void dispose() {
    _videoPlayerController.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return Material(
        elevation: 0,
        child: Column(
          children: <Widget>[
            Expanded(
                child: FittedBox(
                  fit: BoxFit.cover,
                  child: Container(
                      width: 818.0,
                      height: 864.0,
                      child: VideoPlayer(_videoPlayerController)
                  ),
                )
            )
          ],
        )
    );
  }
}
```

**Comment by dannyvalentesonos** [comment] 2019-09-23 18:06
We cannot repro this on any other iPhone, nor an iPhone X running anything under iOS 12.

**Comment by kf6gpe** [comment] 2019-09-23 21:41
3P triage upgrading to critical given the nature of the report.

**Comment by Hixie** [comment] 2019-09-24 23:35
cc @cyanglaz @collinjackson @bparrishMines

**Comment by cyanglaz** [comment] 2019-09-25 03:47
@dannyvalentesonos I have tried running your code on an iPhone X with iOS 12.4 and couldn't reproduce the crash. Could you post your flutter doctor -v with the device connected?

**Comment by dannyvalentesonos** [comment] 2019-09-25 03:54
@cyanglaz I do not have a physical device that I can get this info for you. I'll have to have someone else get that (whom doesn't have the flutter tools installed, so it may take some time).
I can reproduce this very reliably with the iPhone X 12.1 simulator.

**Comment by recastrodiaz** [comment] 2019-09-27 10:06
@dannyvalentesonos shouldn't the super.dispose() method be called before disposing of the video player? Does this fix your crash issue?

``` DART
@override
  void dispose() {
    super.dispose();
    _videoPlayerController.dispose();
  }

**Comment by dannyvalentesonos** [comment] 2019-09-27 15:18
It doesn't fix the crash. The crash is in the GPU thread. The dispose call on the video player causes a platform channel call, which has to cross over to the main thread of the app. Therefore, the order of calls in this callstack doesn't make a difference.

**Comment by cyanglaz** [comment] 2019-09-30 14:57
One way I can think of is to add an 'onUnregistered' callback in the FlutterTexture. Then the video player plugin can dispose the player object inside the callback. This way we guarantee the player object is disposed after the texture is unregistered. @dannyvalentesonos I can wire up a quick prototype for you to try out?

**Comment by dannyvalentesonos** [comment] 2019-09-30 15:03
yes, that is a good solution and something I was hoping could be added. I'd be happy to test.

**Comment by cyanglaz** [comment] 2019-09-30 15:10
https://github.com/flutter/engine/pull/12695
https://github.com/flutter/plugins/pull/2124

@dannyvalentesonos I tested with simulator and it doesn't crash anymore. I also made sure the player is disposed as well.
Do you want to apply these 2 patches and try the same with your app on your real devices?

**Comment by dannyvalentesonos** [comment] 2019-09-30 16:19
@cyanglaz I just realized that we don't build the engine, and have never had the time to try and get an environment up and running that can do so. If you can confirm you no longer get the crash on the simulator, then I'd say that is good, as our temporary fix has been confirmed on the simulator too.

**Comment by cyanglaz** [comment] 2019-10-16 00:04
@dannyvalentesonos I landed the engine change and started working on the plugin side. Now for some reason I couldn't reproduce the crash anymore. Do you mind send me a full example app (with the navigation code as well) and let me try if I can reproduce it again?

**Comment by dannyvalentesonos** [comment] 2019-10-16 01:28
@cyanglaz I got a notification of a question from you, but don't see it here. I've got a zipped up file of the sample app if you need it. Let me know.

**Comment by cyanglaz** [comment] 2019-10-16 19:00
@dannyvalentesonos The fix is ready in https://github.com/flutter/plugins/pull/2124. I am planning to get some reviews and land it by EOW.

**Comment by cyanglaz** [comment] 2019-10-18 04:36
@dannyvalentesonos I am still fighting ci to make the test pass. It might take a while, meanwhile if you need a hotfix, I suggest to patch the changes in https://github.com/flutter/plugins/pull/2124

**Comment by Hixie** [comment] 2019-10-29 23:13
Update: @cyanglaz had some higher-priority issues to deal with but is now back on this bug. Thanks for your patience.

**Comment by cyanglaz** [comment] 2019-11-20 22:01
This is fixed with https://github.com/flutter/plugins/pull/2124. With video_player version 0.10.3+1
I am going to close the issue for now. If any related issue is found, please feel free open another issue with details. If the same issue still occurs, please comment on this issue and I'm happy to reopen it right away!

**Closed by cyanglaz** 2019-11-20 22:01 UTC
Labels: customer: amplify, e: device-specific, p: video_player, plugin, severe: crash, severe: customer critical, waiting for PR to land (fixed), ⌺‬ platform-ios
