### ISSUE TITLE
How to set maxlines in MardownBody ?

### ISSUE THREAD

**Issue by DazzlingCVa** [flutter/flutter#107291] opened 2022-07-08 10:32 UTC
Anyone help Me how to set maxlines in MardownBody

**Comment by darshankawar** [comment] 2022-07-08 12:17
@DazzlingCVa 
Your question is better suited for support channels like Stackoverflow so please ask the same there.
Closing, as this is not a bug or feature request.

**Closed by darshankawar** 2022-07-08 12:17 UTC
Labels: in triage
