### ISSUE TITLE
drm solution not available

### ISSUE THREAD

**Issue by mohankr123** [flutter/flutter#80177] opened 2021-04-10 05:43 UTC
Please add drm solution in video player.

**Comment by iapicca** [comment] 2021-04-10 13:30
possible duplicate of https://github.com/flutter/flutter/issues/24923

**Comment by darshankawar** [comment] 2021-04-12 08:15
Please follow-up in original issue for updates, https://github.com/flutter/flutter/issues/24923
Closing this as duplicate.

**Closed by darshankawar** 2021-04-12 08:15 UTC
Labels: in triage
