### ISSUE TITLE
Optimizing imports in a Kotlin class removes android imports

### ISSUE THREAD

**Issue by MichaelM97** [flutter/flutter#37585] opened 2019-08-04 16:13 UTC
Not sure if this is the correct place to create this issue, feel free to ask me to move it if needed.

When optimixing imports in an android kotlin class, any android specific libraries are removed as if they are unused. A simple way to test this is to:
- Open a Flutter project
- Go to MainActivity.kt
- Optimize imports
- See that the import for `android.os.Bundle` is removed, even though it is being used

This can be done accidentily by making a change to MainActivity.kt, and then commiting via the Android Studio commit dialog with the 'Optimize imports' option checked.

I've checked this on Android Studio 3.4.1, using Flutter version
`[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E2035,
    locale en-GB)`

P.S. This may also affect java classes, though I haven't tested it

**Comment by blasten** [comment] 2019-08-06 17:58
Does the app crashes when you run it?

**Comment by MichaelM97** [comment] 2019-08-06 18:07
Yes, if you attempt to build the APK without this import it will fail.
I presume this would be the same for any android class that is missing a required import

**Comment by markusaksli-nc** [comment] 2020-08-12 13:40
Closing since this is no longer reproducible with the latest version of Android Studio `4.0.1`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-8.0.pre.176, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-8.0.pre.176 at C:\Development\flutter_master
    • Framework revision d9637ed784 (3 hours ago), 2020-08-11 23:51:03 -0400
    • Engine revision 6381b1511b
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

**Closed by markusaksli-nc** 2020-08-12 13:40 UTC
Labels: dependency: android, framework, platform-android
