### ISSUE TITLE
[tool_crash] StackOverflowError: (null)

### ISSUE THREAD

**Issue by cfddb** [flutter/flutter#160747] opened 2024-12-23 03:19 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StackOverflowError: (null)
```
#0      _StringBase.createFromCharCodes (dart:core-patch/string_patch.dart:127:3)
#1      new String.fromCharCodes (dart:core-patch/string_patch.dart:22:24)
#2      _Utf8Decoder.decodeGeneral (dart:convert/utf.dart:668:31)
#3      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1765:14)
#4      _readFQDN (package:multicast_dns/src/packet.dart:165:24)
#5      _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#6      _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#7      _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#8      _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#9      _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#10     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#11     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#12     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#13     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#14     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#15     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#16     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#17     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#18     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#19     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#20     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#21     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#22     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#23     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#24     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.22.1 on channel stable at /Users/daibo/Documents/Develope/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision a14f74ff3a (7 months ago), 2024-05-22 11:08:21 -0500
    [32m•[39m Engine revision 55eae6864b
    [32m•[39m Dart version 3.4.1
    [32m•[39m DevTools version 2.34.3
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/daibo/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
    [32m•[39m Xcode at /Applicat

**Comment by yajatkaul** [comment] 2024-12-23 06:09
I assume you need to run it for apk so you have to configure a few things before

- `path/to/sdkmanager --install "cmdline-tools;latest"`
- `flutter doctor --android-licenses` Accept all the terms

**Comment by danagbemava-nc** [comment] 2024-12-23 09:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/155433

**Closed by danagbemava-nc** 2024-12-23 09:41 UTC
Labels: in triage
