### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "/usr/bin/java/bin/java" in the search path. Command: /usr/bin/java/bin/java, OS error code: 0

### ISSUE THREAD

**Issue by mahmoudhamdyae** [flutter/flutter#139554] opened 2023-12-05 10:09 UTC
## Command
```
flutter create .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "/usr/bin/java/bin/java" in the search path. Command: /usr/bin/java/bin/java, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:714:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:377:51)
#5      Java.version.<anonymous closure> (package:flutter_tools/src/android/java.dart:139:44)
#6      Java.version (package:flutter_tools/src/android/java.dart:179:5)
#7      Java.version (package:flutter_tools/src/android/java.dart)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:510:41)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterComman

**Comment by darshankawar** [comment] 2023-12-05 11:38
@mahmoudhamdyae 
Can you provide `flutter doctor -v` ? Do you get this error everytime consistently while running the said command ?

**Comment by mahmoudhamdyae** [comment] 2023-12-05 11:40
2023/12/05 13:39:53.687559 cmd_run.go:1046: WARNING: cannot create user data directory: cannot read symlink: readlink /home/mahmoudhamdyae/snap/flutter/current: invalid argument
[✓] Flutter (Channel stable, 3.16.2, on Ubuntu 23.10 6.5.0-13-generic, locale en_US.UTF-8)
    • Flutter version 3.16.2 on channel stable at /home/mahmoudhamdyae/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (5 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /media/mahmoudhamdyae/48984A99984A8602/Android/Sdk/
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /usr/bin/java/bin/java
    ✗ Cannot execute /usr/bin/java/bin/java to determine the version

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/mahmoudhamdyae/android-studio2
    • Flutter plugin version 72.1.1
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/mahmoudhamdyae/android-studio/
    • Flutter plugin version 76.3.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/mahmoudhamdyae/android-studio/
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[!] Android Studio (version unknown)
    • Android Studio at /home/mahmoudhamdyae/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /home/mahmoudhamdyae/idea-IC-221.5080.210
    • Flutter plugin version 76.1.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.78.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10 6.5.0-13-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment] 2023-12-06 05:29
> Cannot execute /usr/bin/java/bin/java to determine the version

Could it be due to this that you are getting the error reported. Can you switch to latest master and run your scenario again to check if you still get the same output or not ?

`flutter channel master`
`flutter upgrade`

**Comment by mahmoudhamdyae** [comment] 2023-12-06 06:24
@darshankawar I switched to master and run again and still the same errors

**Comment by darshankawar** [comment] 2023-12-07 05:41
Thanks for the update. I am unable to replicate the reported behavior, but based on the report and occuring on both stable and master, keeping the issue open and labeling for team's attention, as there isn't a similar open issue already.

/cc @christopherfujino

**Comment by christopherfujino** [comment] 2023-12-08 00:13
I think this is a duplicate of https://github.com/flutter/flutter/issues/139180, which was already just fixed in https://github.com/flutter/flutter/pull/139614

**Closed by christopherfujino** 2023-12-08 00:13 UTC
Labels: c: crash, tool, team-tool

**Comment by christopherfujino** [comment] 2023-12-08 00:14
it is has been nominated for cherrypicking into stable at https://github.com/flutter/flutter/issues/139699. Actually, @andrewkolos I'm thinking we should probably cherry pick this into beta also, since it would be bad for users from 3.16 who had the cherry pick to upgrade to beta and then find it regressed.

**Comment by andrewkolos** [comment] 2023-12-08 00:22
> ...we should probably cherry pick this into beta also, since it would be bad for users from 3.16 who had the cherry pick to upgrade to beta and then find it regressed.

Good catch. Will do.
