### ISSUE TITLE
Feature request: Add support for editing rich text

### ISSUE THREAD

**Issue by amardeep** [flutter/flutter#12023] opened 2017-09-09 04:13 UTC
My current use case is a twitter post like edit box which highlights certain words with a different color. eg:

![image](https://user-images.githubusercontent.com/86928/30236910-46c5dcf0-9543-11e7-98ee-75ea04be8f56.png)

**Comment by zoechi** [comment] 2018-12-28 10:48
Duplicate of #12675

**Closed by zoechi** 2018-12-28 10:48 UTC
Labels: a: text input, f: material design, framework
