### ISSUE TITLE
Flutter render issue on app enter to foreground

### ISSUE THREAD

**Issue by LongXiangGuo** [flutter/flutter#68761] opened 2020-10-22 05:22 UTC
## Single Event

1. It is a single event, currently could not reproduce it.
2. While launch the app from background, the app screen show Black and white

 
**Actual results:** 

1 
<img width="450" alt="1" src="https://user-images.githubusercontent.com/16632821/96828065-7dd27c00-1469-11eb-9604-4ee4073dcabc.png">
2
<img width="435" alt="2" src="https://user-images.githubusercontent.com/16632821/96828074-81fe9980-1469-11eb-8572-e8dbb26ee416.png">
3
<img width="452" alt="3" src="https://user-images.githubusercontent.com/16632821/96828076-82973000-1469-11eb-9b24-b19c5c30e2e6.png">
4
<img width="451" alt="4" src="https://user-images.githubusercontent.com/16632821/96828077-83c85d00-1469-11eb-8ee0-9dd505cac537.png">
5
<img width="446" alt="5" src="https://user-images.githubusercontent.com/16632821/96828078-8460f380-1469-11eb-8bb2-0092d3bb5277.png">

<details>
  <summary>Logs</summary>
 

```
[✓] Flutter (Channel unknown, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)


```

</details>

**Comment by pedromassangocode** [comment] 2020-10-22 08:14
Hi @LongXiangGuo 
Looks like you are not using a valid Flutter channel.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists, then please provide your `flutter doctor -v` a minimal complete reproducible code sample?
Thank you

**Comment by LongXiangGuo** [comment] 2020-10-23 02:12
> Hi @LongXiangGuo
> Looks like you are not using a valid Flutter channel.
> Can you please upgrade to the latest `stable` and try again
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the issue persists, then please provide your `flutter doctor -v` a minimal complete reproducible code sample?
> Thank you

We could not reproduce it, It happens only once in one weak.

From the code I guess it may be related to `SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);`, but I'am can't find a stable double line step.


```dart
void main(){
   .... 
    runStartupConfiguration(configuration)
}
void runStartupConfiguration( .....) {
    ...
    run(Shell())
}

class Shell extends StatefulWidget {
  final StartupConfiguration _startupConfiguration;
  final List<Module> _modules;
  final List<LocalizationsDelegate> _localizationDelegates;
  final List<Locale> _supportedLocales;
  final bool _forceDarkMode;

  /// {@macro shell}
  const Shell({ ...

  @override
  State<Shell> createState() => _ShellState();
}

class _ShellState extends State<Shell> with WidgetsBindingObserver {
  
  ....

  @override
  void initState() {
    super.initState();
    SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);  //fix ios status bar disappear when from horizontal to vertical
    ...
  }

  @override
  Widget build(BuildContext context) { ...
    SystemChrome.setPreferredOrientations(<DeviceOrientation>[
      DeviceOrientation.portraitUp,
    ]);
  
```

**Comment by pedromassangocode** [comment] 2020-10-23 08:33
Hi @LongXiangGuo 
I'm going to close this issue for now. 
If the issue reproduces on any of the latest Flutter channel please comment on this issue by providing your `flutter doctor -v` with a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I will reopen it.

Thank you

**Closed by pedromassangocode** 2020-10-23 08:33 UTC
Labels: in triage

**Comment by LongXiangGuo** [comment] 2020-10-24 03:16
> Hi @LongXiangGuo
> I'm going to close this issue for now.
> If the issue reproduces on any of the latest Flutter channel please comment on this issue by providing your `flutter doctor -v` with a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I will reopen it.
> 
> Thank you

OK
