### ISSUE TITLE
[flutter web]  Use ui.platformViewRegistry.registerViewFactory . ios low system failed to load the second time

### ISSUE THREAD

**Issue by iamzhibo** [flutter/flutter#128306] opened 2023-06-06 03:32 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.iOS version is 11.0-13.0.Failed to load the second time
2.iOS version is 13.0 and above are correct

### Expected results

1.iOS version is 11.0-13.0.Failed to load the second time
2.iOS version is 13.0 and above are correct

### Actual results

loaded correctly

### Code sample

String _localVideoPlayerId = 'pkkkkkk${DateTime.now().millisecondsSinceEpoch}';
  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ui.platformViewRegistry.registerViewFactory(
        _localVideoPlayerId,
        (int viewId) => IFrameElement()
          ..allowFullscreen = true
          ..height = '360'
          ..src = 'https://www.baidu.com'
          ..style.border = 'none');
    return Scaffold(
        appBar: AppBar(
          title: const Text('WebViewX Page'),
        ),
        body: Center(
          child: Container(
            color: Colors.red,
            // padding: const EdgeInsets.only(left: 16, right: 16),
            height: 500,
            child: HtmlElementView(viewType: _localVideoPlayerId),
          ),
        ));
  }

### Screenshots or Video

https://github.com/flutter/flutter/assets/118972991/76f7edd9-6e82-49f2-a37f-7ad9149b2408

### Logs

Flutter version 3.7.12,The latest version also tried

### Flutter Doctor output

Flutter (Channel stable, 3.7.12, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-US)
    • Flutter version 3.7.12 on channel stable at /zb/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (7 周前), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

**Comment by darshankawar** [comment] 2023-06-06 08:40
Closing as duplicate of https://github.com/flutter/flutter/issues/128015.

Please don't file duplicate issues for same reason.

**Closed by darshankawar** 2023-06-06 08:40 UTC
Labels: in triage
