### ISSUE TITLE
Autofill is unable to associate credentials and is always asking if they should be stored

### ISSUE THREAD

**Issue by jsc57x** [flutter/flutter#135948] opened 2023-10-04 05:34 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We created an application with a login form and want to save the credentials in the system password safe (e.g. the Google Password Manger on Android). We hust the AutfillHints on the Username/E-Mail and password text field and everything works fine on Android.
In Xcode we created an associated domain, something like: `webcredentials:<subdomain>.<domain>?mode=developer` and created an apple-app-site-association file which is available at <subdomain>.<domain>/.well-known/apple-app-site-assocation:
```html
{
   "webcredentials":{
      "apps":[
         "<TeamID>.<AppID>"
      ]
   },
   "applinks":{
      "apps":[ ],
      "details":[
         {
            "appID":"<TeamID>.<AppID>",
            "paths":[ "*", "/" ]
         }
      ]
   }
}
```

### Expected results

Android and iOS will ask for confirmation to store the credentials after login and provide the possibility to choose the login credentials on the login page.

### Actual results

On Android everything works as expected but iOS (we are only able to try it on iOS 15.7.7 which is not ideal but in the expected range of customer devices) behaves weird:
1. The keyboard overlay does not show the saved credentials but the possibility to open the password manager and you have to manually select the credentials. They are then entered correctly in the email and password field.
2. After every login a system overlay shows up and ask for confirmation to save the credentials even if they are already stored. The following is a minimal code snippet for the login form
We know that the apple-app-site-association file is accessed by the application but something seems to be off.

### Code sample

<details><summary>Code sample</summary>

```dart
 Container _buildLoginForm(BuildContext context) {
    return Container(
        padding: const EdgeInsets.all(20.0),
        child: AutofillGroup(
            onDisposeAction: AutofillContextAction.commit,
            child: Wrap(runSpacing: 10, children: [
              TextField(
                autofillHints: const <String>[AutofillHints.username], 
                decoration: getTextFieldDecoration("E-Mail"), 
                controller: _emailController),
              TextField(
                  obscureText: true,
                  autofillHints: const <String>[AutofillHints.password],
                  decoration: getTextFieldDecoration("Password"),
                  controller: _passwordController,
                  onEditingComplete: () => _handleLogin()),
              ElevatedButton(
                onPressed: () => _handleLogin(),
                child: const Text("Login"),
              )
            ])));
  }```
</details>


### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.2 22G91 darwin-arm64, locale de-DE)
    • Flutter version 3.10.6 on channel stable at /Users/builduser/Desktop/dev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/builduser/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPad von Build User (mobile) • f108aef935b763dbfe1e4fa7e029eed1b07a439e • ios            • iOS 15.7.7 19H357
    • macOS (desktop)              • macos                                    • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)                 • chrome                                   • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-10-04 09:08
Hi @jsc57x . Thanks for filing this. I see there is an already open issue describing this exact case https://github.com/flutter/flutter/issues/116889. Kindly upvote, comment and follow up on the issue for updates.
Closing this as a duplicate of the existing issue, if you disagree, please comment and I'd reopen this.
Thank you!

**Closed by dam-ease** 2023-10-04 09:08 UTC
Labels: in triage

**Comment by jsc57x** [comment] 2023-10-04 09:19
Thanks for the answer, yes I see that the bug with the focus lost might be problem 2. But I don't see that the other problem is mentioned (in fact the behaviour is shown in the demo video). Should I comment the other ticket or alter this one?

**Comment by dam-ease** [comment] 2023-10-04 10:02
Hi @jsc57x. Please comment on the existing issue.
