### ISSUE TITLE
TextFiled set 'obscureText' is true  in iPhone 11pro max collapse

### ISSUE THREAD

**Issue by lp7799** [flutter/flutter#62637] opened 2020-07-31 02:03 UTC
```
     TextField(
          obscureText: true,
        )
```
Textfield sets obscureText to true to crash in iOS

_[✓] Flutter (Channel master, 1.21.0-6.0.pre.126, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.21.0-6.0.pre.126 at /Users/mac/Documents/sdk/flutter
    • Framework revision fbd29b8880 (5 hours ago), 2020-07-30 13:41:02 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • A34A0CDA-4785-4D6A-A0CF-8B75F23DBBF9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 category.
Process finished with exit code 0_

**Comment by LongCatIsLooong** [comment] 2020-07-31 03:35
likely a duplicate of #62501. Closing.

**Closed by LongCatIsLooong** 2020-07-31 03:35 UTC
