### ISSUE TITLE
Failed assertion: line 4731 pos 12: '_state._element == null': is not true.

### ISSUE THREAD

**Issue by SediqeZangane** [flutter/flutter#71223] opened 2020-11-25 12:16 UTC
hello....
thanks for answer my error as soon as possible 
i wrote  strings of number in TextFormField and select "Enter" then a red screen came with this error

 "The following assertion was thrown building DefaultTextStyle(debugLabel: (englishLike body1 2014).merge(blackMountainView bodyText2), inherit: false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4731 pos 12: '_state._element == null': is not true."
what should i do???? help me as soon as possible please

**Comment by iapicca** [comment] 2020-11-25 12:53
@SediqeZangane 
please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment] 2020-11-25 13:08
@SediqeZangane 
It seems to be an issue with your code implementation and not the error with Flutter framework. Your question is better suited for StackOver flow, as suggested above.
Closing from here. If you disagree or think the issue is coming from the framework, write in comments and I'll reopen it.

**Closed by darshankawar** 2020-11-25 13:08 UTC
