### ISSUE TITLE
path_provider usage of dart:ffi prevents web compilation

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#66143] opened 2020-09-18 21:33 UTC
Due to the inconsistent set of dart libraries supported by Web and Desktop/Mobile SDKs, certain dart libraries cannot be used safely. dart:ffi is one of those - if it is reachable in a web app, the compilation will fail.

See:  https://github.com/flutter/flutter/pull/66136#issuecomment-695090577

```
[web_benchmarks_html] [STDOUT] Executing: /b/s/w/ir/k/flutter/bin/flutter build web --dart-define=FLUTTER_WEB_ENABLE_PROFILING=true --profile -t lib/web_benchmarks.dart in /b/s/w/ir/k/flutter/dev/benchmarks/macrobenchmarks
[web_benchmarks_html] [STDOUT] stdout: Downloading Web SDK...                                              1.0s
[web_benchmarks_html] [STDOUT] stdout: Compiling lib/web_benchmarks.dart for the Web...                
[web_benchmarks_html] [STDOUT] stderr: Target dart2js failed: Exception: ../../../../../cache/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.2/lib/path_provider_windows.dart:7:8:
[web_benchmarks_html] [STDOUT] stderr: Error: Not found: 'dart:ffi'
[web_benchmarks_html] [STDOUT] stderr: import 'dart:ffi';
[web_benchmarks_html] [STDOUT] stderr:        ^
[web_benchmarks_html] [STDOUT] stderr: ../../../../../cache/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart:6:8:
[web_benchmarks_html] [STDOUT] stderr: Error: Not found: 'dart:ffi'
[web_benchmarks_html] [STDOUT] stderr: import 'dart:ffi';
[web_benchmarks_html] [STDOUT] stderr:        ^
[web_benchmarks_html] [STDOUT] stderr: ../../../../../cache/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf16.dart:6:8:
[web_benchmarks_html] [STDOUT] stderr: Error: Not found: 'dart:ffi'
[web_benchmarks_html] [STDOUT] stderr: import 'dart:ffi';
[web_benchmarks_html] [STDOUT] stderr:        ^
[web_benchmarks_html] [STDOUT] stderr: ../../../../../cache/.pub-cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:5:8:
[web_benchmarks_html] [STDOUT] stderr: Error: Not found: 'dart:ffi'
[web_benchmarks_html] [STDOUT] stderr: import 'dart:ffi';
[web_benchmarks_html] [STDOUT] stderr:        ^
[web_benchmarks_html] [STDOUT] stderr: ../../../../../cache/.pub-cache/hosted/pub.dartlang.org/win32-1.7.1/lib/src/callbacks.dart:7:8:
```

**Comment by csells** [comment] 2020-09-18 21:35
@amirh fyi

**Comment by stuartmorgan** [comment] 2020-09-18 21:54
Why didn't this fail flutter/plugins CI?

**Comment by dsokolov-pfpt** [comment] 2020-09-19 00:10
Having a similar issue. Logs show the issue is caused with new update to path_provider released today. 
The **pub get** command is picking all repos:
```
[  +16 ms] Found plugin onboard_plugin at /home/ubuntu/workspace/Meta-Project-Build-Internal-Android-32bit/onboard_plugin/
[   +4 ms] Found plugin path_provider at /home/ubuntu/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.16/
[        ] Found plugin path_provider_linux at /home/ubuntu/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /home/ubuntu/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+4/
[   +1 ms] Found plugin path_provider_windows at /home/ubuntu/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.2/
```

**Comment by dsokolov-pfpt** [comment] 2020-09-19 00:11
Temporary fix: roll to previous version **path_provider: 1.16.14**

**Comment by stuartmorgan** [comment] 2020-09-19 01:51
I guess we'll need to conditional-include path_provider_windows, with a dummy version of PathProviderWindows that's just an empty class for web?

**Comment by stuartmorgan** [comment] 2020-09-19 23:26
> Why didn't this fail flutter/plugins CI?

I wonder if we don't have anything in flutter/plugins that both supports web and depends on path_provider.

**Comment by juzimmer** [comment] 2020-09-20 23:38
Just to clarify I ran into this same problem and the path provider version that fixes this is path_provider: 1.6.14, **not 1.16.14**

**Comment by mavtar-software** [comment] 2020-09-21 05:13
I am Facing Same Problem, 
even   path_provider: 1.6.14 not working.

i am using dev channel, flutter web

Flutter 1.22.0-12.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision a27c242b0e (9 days ago) • 2020-09-11 17:46:57 -0400
Engine • revision fee6f9e533
Tools • Dart 2.10.0 (build 2.10.0-110.0.dev)

can anybody help me? [ i am new to flutter, but i have 12 years of c#.net experience in desktop coding.]

**Comment by juzimmer** [comment] 2020-09-21 12:55
@mavtar-software the issue should be fixed for now. If you are still having issues, switch over to beta channel using “flutter channel beta” and running “flutter upgrade” and “pug get” If you are still having issues I would create another ticket as your issue could be unrelated.

**Comment by stuartmorgan** [comment] 2020-09-21 13:18
> @mavtar-software the issue should be fixed for now.

It is not fixed yet.

**Comment by barriehadfield** [comment] 2020-09-21 15:14
Same issue

**Comment by stuartmorgan** [comment] 2020-09-21 15:45
Everyone with a project that has a dependency (transitive or otherwise) on `path_provider` will have this problem building for web if they have 1.6.16. Please just subscribe to the issue if you want to get an update when the fix is landed and published; there's no need to comment about the existence of the problem.

**Closed** 2020-09-21 20:48 UTC
Labels: p: path_provider, plugin, severe: regression

**Comment by faisalramdan17** [comment] 2020-09-22 06:04
I didn't use the path_provider package in my case 
then I just added  path_provider_windows: ^0.0.4+1 in my pubspec.yaml file.
So, working fine!
You can try this one.

**Comment by mavtar-software** [comment] 2020-09-22 11:59
thanks a lot Mr. faisalramdan17.
its working now.

**Comment by stuartmorgan** [comment] 2020-09-22 13:19
It shouldn't be necessary to manually pin a version of `path_provider_windows` if the dependency is transitive; you just need to re-pull the latest versions of packages so that you get the latest path_provider and path_provider_windows.

**Comment by faisalramdan17** [comment] 2020-09-22 13:25
> thanks a lot Mr. faisalramdan17.
> its working now.

It's okay brother

**Comment by slabo** [comment] 2021-01-12 13:20
This should still be open. It's not fixed yet. Fixed for windows builds, not web. I confirm I still have the same problem with   path_provider: ^1.6.27

**Comment by stuartmorgan** [comment] 2021-01-12 13:40
> Fixed for windows builds, not web.

This was only ever an issue for web, so I'm not sure what you mean by "fixed for Windows build".

> I confirm I still have the same problem with path_provider: ^1.6.27

Please file a new issue with the exact error message. Either your packages have not updated correctly, or you're getting an FFI inclusion some other way.

**Comment by pratikpwr** [comment] 2021-01-20 09:53
for those the above solution didn't work, try removing ffi.dart if it is imported in your project in lib section. I had the same issue, when I remove the import all was working fine

**Comment by stuartmorgan** [comment] 2021-01-20 14:11
It seems like there's some confusion about what this issue was about. Any inclusion of `ffi` in a web project will fail to compile, which is expected behavior. **This** issue was about the fact that `path_provider` created a transitive dependency on `ffi`, and that has long since been fixed.

Unless your output contains:
```
 Target dart2js failed: Exception: [...]/path_provider_windows.dart:7:8:
 Error: Not found: 'dart:ffi'
```
—**note the `path_provider_windows` as the place where the `dart:ffi` include is coming from**—your issue is unrelated to this one, and you should look at what file is listed there instead of `path_provider_windows` to find out what is including `ffi` in your project.
