### ISSUE TITLE
Image_picker external images failed - Android Q

### ISSUE THREAD

**Issue by kleinpetr** [flutter/flutter#34873] opened 2019-06-21 19:13 UTC
Hey when I use image_picker and select some image from Recent images or from Camera folder I have got this message
 FileSystemException: Cannot retrieve length of file, path = '/mnt/content/media/external/images/media/151259' (OS Error: No such file or directory, errno = 2)
And image not showing..

When I select image from Google photos the path of image is /data/user/0/com.example.app/cache/image_picker7358001208011697539.jpg
and this works fine.

When I select image from Folder Downloads the path of image is
/data/user/0/com.example.app/cache/image_picker8396370077072731644.jpg
and this working fine too

**Comment by BondarenkoStas** [comment] 2019-10-03 23:30
Duplicate of #31845

**Closed by BondarenkoStas** 2019-10-03 23:30 UTC
