### ISSUE TITLE
[TextField] backspace key removes two characters at a time in Chinese, which is not a problem in the English letters

### ISSUE THREAD

**Issue by 1291431532** [flutter/flutter#70581] opened 2020-11-16 03:23 UTC
flutter doctor -v

[✓] Flutter (Channel master, 1.24.0-8.0.pre.252, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
    • Flutter version 1.24.0-8.0.pre.252 at D:\App\flutter
    • Framework revision bf2c9dfc05 (24 hours ago), 2020-11-14 22:38:02 -0500
    • Engine revision 3e77d854a7
    • Dart version 2.12.0 (build 2.12.0-45.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by pedromassangocode** [comment] 2020-11-16 07:42
Hi @1291431532 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by 1291431532** [comment] 2020-11-16 07:51
```
void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(body: Center(child: TextField()),),
    );
  }
}
```
![be](https://user-images.githubusercontent.com/30567427/99225640-56ca5880-2823-11eb-8a95-ed60e255e370.png)
![af](https://user-images.githubusercontent.com/30567427/99225644-57fb8580-2823-11eb-89c7-793db22cdef6.png)

**Comment by pedromassangocode** [comment] 2020-11-17 08:04
Reproducible on latest `master` channel.

I can confirm that the issue does not reproduce with Latin characters.

| Master channel | Stable/Beta channel |
| ----- | ----- |
|![gif](https://user-images.githubusercontent.com/67424416/99360921-99d30d00-28b1-11eb-95c8-6c4a54fc40c0.gif) |![gif2](https://user-images.githubusercontent.com/67424416/99362347-aa848280-28b3-11eb-8f2f-3730b92f866e.gif)|

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.267, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.267 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 22e576fa26 (8 hours ago), 2020-11-16 18:48:03 -0500
    • Engine revision f0e80100f7
    • Dart version 2.12.0 (build 2.12.0-49.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X
      10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 86.0.4240.198

• No issues found!
```
</details>

**Comment by 1291431532** [comment] 2020-11-17 09:41
The problem still exists, and it has nothing to do with the locale.
It will appear in the following situations:
1.  The Android emulator uses the BackSpack button of the real keyboard (the virtual machine keyboard is normal)

2.  Android real machine running (IOS real machine is normal)

I only have a Windows system and I have not tested MAC
<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.267, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
    • Flutter version 1.24.0-8.0.pre.267 at D:\App\flutter
    • Framework revision 22e576fa26 (10 hours ago), 2020-11-16 18:48:03 -0500
    • Engine revision f0e80100f7
    • Dart version 2.12.0 (build 2.12.0-49.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\App\AndroidSdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\App\JetBrainsApps\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at D:\App\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at D:\App\JetBrainsApps\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at D:\App\JetBrainsApps\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (5 available)
    • Redmi K30 Pro (mobile) • d86a82d3   • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows    • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Web Server (web)       • web-server • web-javascript • Flutter Tools
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)             • edge       • web-javascript • Microsoft Edge 86.0.622.69

• No issues found!
```

</details>

**Comment by pamir72** [comment] 2020-11-18 06:53
Not only China and not only emulator.
After last upgrade I have this problem on the emulator and physical device with English, Russian and number symbols. But only Android!

Flutter 1.24.0-10.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 405c85fe7e (4 days ago) • 2020-11-13 21:22:10 -0800
Engine • revision bd390c0310
Tools • Dart 2.12.0 (build 2.12.0-29.7.beta)

**Comment by gspencergoog** [comment] 2020-11-20 18:47
This is a duplicate of #70744. Closing.

**Closed by gspencergoog** 2020-11-20 18:47 UTC
Labels: a: text input, customer: crowd, f: material design, found in release: 1.24, framework, has reproducible steps, severe: regression
