### ISSUE TITLE
http request crashes on iOS 10 with Flutter 2

### ISSUE THREAD

**Issue by ChristianPauly** [flutter/flutter#77808] opened 2021-03-10 14:07 UTC
## Steps to Reproduce

1. Create a new application and import the http package (minimal example provided here)
2. Run the app on an iOS 10 device (I have no other device to test...)
3. Make the app start an http call

**Expected results:** 
App performs the http call.

**Actual results:** 
App crashes/exits without any flutter logs and the phone returns to the homescreen.
It works fine on all other platforms including the iOS emulator on my Macbook.

<details>
  <summary>Logs</summary>

```
[  +27 ms] Connected to _flutterView/0x170d3210.
[   +4 ms] Flutter run key commands.
[   +7 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone von Christian is available at: http://127.0.0.1:54503/l-TzpR6tXOQ=/
[   +1 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on iPhone von Christian is available at:
           http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A54503%2Fl-TzpR6tXOQ%3D%2F
[   +1 ms] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+6903 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +6 ms] DevFS: Deleting filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/FF41895F-1BBA-4D8A-9EEA-7ADF6BF72622/tmp/ioscrashtestwnxLfa/ioscrashtest/)
[ +260 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +4 ms] "flutter run" took 52.105ms.
[ +121 ms] ensureAnalyticsSent: 114ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

```
Analyzing ioscrashtest...                                               
No issues found! (ran in 3.6s)
```

```
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.1 20C69 darwin-x64, locale de)
    • Flutter version 2.0.1 at /Users/christianpauly/development/flutter
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices
    • Android SDK at /Users/christianpauly/Library/Android/sdk
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone von Christian (mobile) • cb2bdac00d26df7dbd2572badabf239969c3753d • ios            • iOS 10.3.4
    • macOS (desktop)               • macos                                    • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                  • chrome                                   • web-javascript • Google Chrome 88.0.4324.192
    ! Error: iPhone von Christian is busy: Copying cache files from device. Xcode will continue when iPhone von Christian is finished. (code -10)

! Doctor found issues in 2 categories.
```

</details>

### Minimal example:
```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _onTap() {
    http
        .get(Uri.parse('https://janian.de/_matrix/client/versions'))
        .then((e) => print(e.body));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _onTap,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

### pubspec.yaml
```yaml
name: ioscrashtest
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
```

**Comment by darshankawar** [comment] 2021-03-11 10:31
@ChristianPauly 
Tried your code sample on 2 iOS devices (iOS 14.2 and 12.4.9) but didn't see app crash. Tapping on FAB shows bunch of below logs on both devices respectively and a white screen all the time. Verified this on latest master.

![37007](https://user-images.githubusercontent.com/67046386/110773315-9c9fa680-8282-11eb-8469-52c3daafba04.jpg)


<details>
<summary>iOS 14.2 log</summary>

```
Running pod install...
Running Xcode build...
Xcode build done.                                           24.3s
Installing and launching...
Debug service listening on ws://127.0.0.1:58037/c8VMyEZsASM=/ws
Syncing files to device Darshan's iphone...
[VERBOSE-2:FlutterObservatoryPublisher.mm(138)] Could not register as server for FlutterObservatoryPublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
[VERBOSE-2:FlutterObservatoryPublisher.mm(138)] Could not register as server for FlutterObservatoryPublisher, permission denied. Check your 'Local Network' permissions for this app in the Privacy section of the system Settings.
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:24:18: warning: unused variable 'outputCoverage_Stage0'
    const float4 outputCoverage_Stage0 = float4(1.0);
                 ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:25:18: warning: unused variable 'outputCoverage_Stage0'
    const float4 outputCoverage_Stage0 = float4(1.0);
                 ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:35:12: warning: unused variable '_tmp_1_inPosition'
    float2 _tmp_1_inPosition = (_globals._anonInterface0->ulocalMatrix_Stage0 * float3(_in.inPosition, 1.0)).xy;
           ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:39:12: warning: unused variable '_tmp_0_inPosition'
    float2 _tmp_0_inPosition = _in.inPosition;
           ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:30:18: warning: unused variable 'outputCoverage_Stage0'
    const float4 outputCoverage_Stage0 = float4(1.0);
                 ^
program_source:32:16: warning: unused variable '_5_highPrecision'
    const bool _5_highPrecision = false;
               ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:24:18: warning: unused variable 'outputCoverage_Stage0'
    const float4 outputCoverage_Stage0 = float4(1.0);
                 ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:26:18: warning: unused variable 'outputCoverage_Stage0'
    const float4 outputCoverage_Stage0 = float4(1.0);
                 ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:24:18: warning: unused variable 'outputCoverage_Stage0'
    const float4 outputCoverage_Stage0 = float4(1.0);
                 ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:36:12: warning: unused variable '_tmp_1_inPosition'
    float2 _tmp_1_inPosition = (_globals._anonInterface0->ulocalMatrix_Stage0 * float3(_in.inPosition, 1.0)).xy;
           ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:31:18: warning: unused variable 'outputCoverage_Stage0'
    const float4 outputCoverage_Stage0 = float4(1.0);
                 ^
program_source:33:16: warning: unused variable '_5_highPrecision'
    const bool _5_highPrecision = false;
               ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:24:18: warning: unused variable 'outputCoverage_Stage0'
    const float4 outputCoverage_Stage0 = float4(1.0);
                 ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:39:12: warning: unused variable '_tmp_0_inPosition'
    float2 _tmp_0_inPosition = _in.inPosition;
           ^
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:29:18: warning: unused variable 'outputCoverage_Stage0'
    const float4 outputCoverage_Stage0 = float4(1.0);
                 ^
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
[Metal Compiler Warning] Warning: Compilation succeeded with: 


program_source:36:12: warning: unused variable '_tmp_1_inPosition'
    float2 _tmp_1_inPosition = (_globals._anonInterface0->ulocalMatrix_Stage0 * float3(_in.inPosition, 1.0)).xy;
           ^
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}

```

</details>


<details>
<summary>iOS 12.4.9 log</summary>

```
Installing and launching...
Debug service listening on ws://127.0.0.1:58211/UQCtkfXEmbE=/ws
Syncing files to device Deepti 's iPhone...
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
flutter: {"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}



```

</details>


<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.205, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.205 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 267f66a7dc (6 hours ago), 2021-03-10 23:15:03 -0500
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Deepti 's iPhone (mobile) • 0554e90e563e81fd41bfd2ff9a2c6960595b9825 • ios
      • iOS 12.4.9
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.82
    ! Error: Deepti 's iPhone is busy: Copying cache files from device. Xcode
      will continue when Deepti 's iPhone is finished. (code -10)

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment] 2021-03-11 10:31
Tagging @TahaTesser to verify this on iOS 10.

**Comment by ChristianPauly** [comment] 2021-03-11 11:06
One of my colleges can confirm that this is not a problem on his iOS 14.x device. Seems to affect only my combination. The test URL just gives some data back, but it doesn't matter which url you send a request too.

**Comment by TahaTesser** [comment] 2021-03-11 14:51
Hi @ChristianPauly 
Thanks for filing the issue, I can reproduce the crash on iOS 10.3.3 on an iPhone 5s on the `stable` and `master` channels

App crash when clicking FAB, however, this seems to be fixed on the `dev` and `master` channels and the logs are printed instead of a crash.


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _onTap() {
    http
        .get(Uri.parse('https://janian.de/_matrix/client/versions'))
        .then((e) => print(e.body));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _onTap,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

``` 

</details>

```bash
[  +18 ms] Connected to _flutterView/0x10382c220.
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[        ] An Observatory debugger and profiler on Taha’s iPhone is available at: http://127.0.0.1:57746/U2oRQ82eiyI=/
[ +917 ms] The Flutter DevTools debugger and profiler on Taha’s iPhone is available at:
                    http://127.0.0.1:9109?uri=http%3A%2F%2F127.0.0.1%3A57746%2FU2oRQ82eiyI%3D%2F
[+13725 ms] flutter:
{"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filt
ering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.
public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
[ +118 ms] flutter:
{"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filt
ering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.
public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • e534bcc711c9a011aa892eb51cdb60f40b3acddb • ios
      • iOS 10.3.3
    • macOS (desktop)        • macos                                    •
      darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

```bash
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_beta
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • e534bcc711c9a011aa892eb51cdb60f40b3acddb • ios
      • iOS 10.3.3
    • macOS (desktop)        • macos                                    •
      darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

</details>

Thank you

**Comment by ChristianPauly** [comment] 2021-03-12 09:25
I can confirm that it is fixed in the dev channel. Thank you very much! :-) You guys are awesome

**Comment by chinmaygarde** [comment] 2021-03-15 18:04
@TahaTesser Do you have the crash report for [your reproduction](https://github.com/flutter/flutter/issues/77808#issuecomment-796792183)? We are wondering if this is related to SSL but without a stacktrace, it is hard to cross reference any fixes with this issue.

**Comment by chinmaygarde** [comment] 2021-03-15 18:06
For reference, we think the fix is https://github.com/dart-lang/sdk/issues/45214

**Comment by ChristianPauly** [comment] 2021-03-16 12:12
Unfortenetly we cant build our app with dev or master channel at the moment because of a dependency hell which is intruded there starting with FFI 1.0.0 needed. So we are totally blocked at the moment. Is it possible to backport the fix to the stable channel of flutter?

**Comment by chinmaygarde** [comment] 2021-03-16 16:30
The patch I linked is already being cherry picked.

**Comment by xster** [comment] 2021-03-18 19:11
@kf6gpe sounds like we're cherry picking it. Can you track its release state (or dupe into another tracking bug)?

**Comment by chinmaygarde** [comment] 2021-03-22 17:44
Seems hotfixed in 2.12.1. Per Ray, closing this here.

**Closed by chinmaygarde** 2021-03-22 17:44 UTC
Labels: P2, e: OS Version specific, engine, found in release: 2.0, has reproducible steps, platform-ios, severe: fatal crash, severe: regression

**Comment by TahaTesser** [comment] 2021-03-23 09:54
@chinmaygarde 
I was on vacation since this is closed, I take no more information is needed, thanks.

**Comment by jlubeck** [comment] 2021-03-24 20:57
> I can confirm that it is fixed in the dev channel. Thank you very much! :-) You guys are awesome

I'm running into this same issue, I'm currently on the latest dev channel and doesn't seem to be fixed. Like the original issue, there are no logs other than a `Lost connection to device.`

Not sure how can I help...

**Comment by jlubeck** [comment] 2021-03-25 01:28
@TahaTesser @chinmaygarde 👆 🙏

**Comment by jlubeck** [comment] 2021-03-25 14:39
BTW, I tried beta (which is actually newer Framework revision for some reason) and still having the issue...

**Comment by TahaTesser** [comment] 2021-03-25 15:51
@jlubeck 
I just tried on all the latest channels, none of them crash on iPhone 5s running iOS 10.3.3 when using the code sample  https://github.com/flutter/flutter/issues/77808#issuecomment-796792183

**Comment by jlubeck** [comment] 2021-03-25 16:22
> @jlubeck
> I just tried on all the latest channels, none of them crash on iPhone 5s running iOS 10.3.3 when using the code sample [#77808 (comment)](https://github.com/flutter/flutter/issues/77808#issuecomment-796792183)

Yes, I understand it got fixed for everyone else here, that's why I was seeing I don't know how I can help? I can't replicate it with the code sample, but it's 100% reproducible on my app (which is huge I can't seem to be able to strip a reproducible crashing sample)

But it's definitely crashing as soon as it calls the `post` method of the `Client` object in the `http` package.

But I have no logs, no nothing. The app just closes and then I see nothing else in the logs...
