### ISSUE TITLE
ld: framework not found Pods_Runner when running flutter build ios with flavor

### ISSUE THREAD

**Issue by brizaldi** [flutter/flutter#60277] opened 2020-06-25 11:56 UTC
We got this error whenever we try to build ios using flavor command: `flutter build ios --flavor prod -t lib/main_prod.dart`

```
    ld: framework not found Pods_Runner
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ld: framework not found Pods_Runner
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: the following command failed with exit code 1 but produced no further output
    Ld
    /Users/MyComp/Library/Developer/Xcode/DerivedData/Runner-czftomtlafkkuacwhumiisrjmtsb/Build/Intermediates.noindex/Runner.build/Release-prod-iphoneos/Runner.build/Objects-normal/arm64/Bina
    ry/Runner normal arm64
```

**Comment by TahaTesser** [comment] 2020-06-25 14:59
Hi @brizaldi 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by brizaldi** [comment] 2020-06-25 23:50
<details>
  <summary>flutter doctor -v</summary>
  
  ```
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.0-1.0.pre at /Applications/development/mobile/flutterSDK/flutter
    • Framework revision f73f498da1 (7 days ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/MyComp/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)            
    • iPhone SE (2nd generation) • 06E8357F-5349-42F4-AFC4-1F653AC74FDB • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
  ```
</details>

<details>
  <summary>flutter run --flavor prod -t lib/main_prod.dart --verbose</summary>

  [verbose_log.txt](https://github.com/flutter/flutter/files/4834353/verbose_log.txt)
</details>

the app is launch perfectly when we try to run it using `flutter run` command, but the problem occurred when we try to build using `flutter build ios` command

**Comment by brizaldi** [comment] 2020-06-26 00:00
@TahaTesser the build process seems stopped at 'Link Binary with Libraries'

<img width="1182" alt="Screen Shot 2020-06-26 at 06 58 48" src="https://user-images.githubusercontent.com/41714881/85806939-a2983a80-b77a-11ea-9517-f4034e6aa1f9.png">

**Comment by TahaTesser** [comment] 2020-06-26 07:48
Hi @brizaldi 
Could you provide complete `flutter build ios --flavor prod -t lib/main_prod.dart --verbose`?
Thank you

**Comment by brizaldi** [comment] 2020-06-26 08:17
@TahaTesser 

<details>
  <summary>flutter build ios --flavor prod -t lib/main_prod.dart --verbose</summary>
  
[build_ios_verbose_log.txt](https://github.com/flutter/flutter/files/4835815/build_ios_verbose_log.txt)
</details>

**Comment by mathatan** [comment] 2020-06-29 08:47
Is there any workaround for this issue? I'm also running into this and I would need to start making profile/release builds soon.

**Comment by jmagman** [comment] 2020-07-14 23:36
```
                    xcodebuild: error: The project named "Runner" does not
                    contain a scheme named "Prod". The "-list" option can be
                    used to find the names of the schemes in the project.
```
This looks like a form of https://github.com/flutter/flutter/issues/59029, and the fix is in the master channel.  Workaround is to rename your scheme from "prod" to "Prod".

**Closed by jmagman** 2020-07-14 23:36 UTC
Labels: P4, a: build, platform-ios, t: xcode, tool

**Comment by mathatan** [comment] 2020-07-15 10:42
Yeah, for me it ended up being an issue with Deployment target iOS version being too low bc of Apple Sign-in.

**Comment by aTeamSolace** [comment] 2020-07-27 07:04
@brizaldi @TahaTesser  have you solved this issue I also suffered from this issue any update on this?  https://github.com/flutter/flutter/issues/61938

**Comment by brizaldi** [comment] 2020-07-27 07:11
nope, we end up with creating a new project and then manually copy the code, it might happen because cache from pod being stuck in the xcode

**Comment by aTeamSolace** [comment] 2020-07-27 07:27
@brizaldi thanks for helping

**Comment by jmagman** [comment] 2020-07-27 17:48
@brizaldi I closed this because it looked like a duplicate of #59029, however if renaming your scheme didn't work on master, this should have been reopened.
@aTeamSolace if your verbose run logs show something like `xcodebuild: error: The project named "Runner" does not contain a scheme named "YourFlavor".` on the master channel, please open a new issue and completely fill out the template.  We would like to track this down for all developers, not require them to make a new project and copy files around.
