### ISSUE TITLE
ProcessException: ProcessException: %1 不是有效的 Win32 应用程序。    Command: D:\Android\Android Studio\jre\bin\java.EXE -version

### ISSUE THREAD

**Issue by wangsanpiao** [flutter/flutter#38174] opened 2019-08-11 12:28 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: %1 不是有效的 Win32 应用程序。

  Command: D:\Android\Android Studio\jre\bin\java.EXE -version

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:298:51)
#5      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#6      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:100:14)
#7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:242:54)
#8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:175:40)
#9      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:21:55)
#10     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:88:51)
#11     Doctor.validators (package:flutter_tools/src/doctor.dart:144:46)
#12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:39)
#13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
<asynchronous suspension>
#14     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#23     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#24     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#32     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#33     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CommandRunner.run (package:args/command_runner.dart:112:14)
#36     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#37     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1500:12)
#42     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#43     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _runZoned (dart:async/zone.dart:1516:10)
#47     runZoned (dart:async/zone.dart:1463:12)
#48     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#49     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#50     run (package:flutter_tools/runner.dart:51:10)
#51     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#52     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#53     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
encountered exception: ProcessException: %1 不是有效的 Win32 应用程序。

  Command: D:\Android\Android Studio\jre\bin\java.EXE -version

#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:298:51)
#5      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#6      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:100:14)
#7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:242:54)
#8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:175:40)
#9      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:165:41)
#10     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#12     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:113:23)
#15     androidStudio (package:flutter_tools/src/android/android_studio.dart:16:44)
#16     javaPath (package:flutter_tools/src/android/android_studio.dart:30:24)
#17     AndroidSdk.findJavaBinary (package:flutter_tools/src/android/android_sdk.dart:530:24)
#18     AndroidValidator.validate (package:flutter_tools/src/android/android_workflow.dart:157:42)
<asynchronous suspension>
#19     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:354:52)
<asynchronous suspension>
#20     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
#21     Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
#22     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#23     Doctor.diagnose (package:flutter_tools/src/doctor.dart:213:24)
#24     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:193:26)
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
#26     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:7)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
#33     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#35     _doctorText (package:flutter_tools/runner.dart:192:19)
#36     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#37     _doctorText (package:flutter_tools/runner.dart:188:27)
#38     _createLocalCrashReport (package:flutter_tools/runner.dart:170:32)
#39     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#40     _createLocalCrashReport (package:flutter_tools/runner.dart:155:37)
#41     _handleToolError (package:flutter_tools/runner.dart:125:33)
#42     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#43     _rootRunUnary (dart:async/zone.dart:1132:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#45     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#47     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#48     Future._complete (dart:async/future_impl.dart:473:7)
#49     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#52     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#53     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:84:45)
#54     _rootRunBinary (dart:async/zone.dart:1144:38)
#55     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#56     _FutureListener.handleError (dart:async/future_impl.dart:140:20)
#57     Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#58     Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#59     Future._completeError (dart:async/future_impl.dart:491:5)
#60     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#61     _Completer.completeError (dart:async/future_impl.dart:27:5)
#62     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:18)
#63     IOClient.send (package:http/src/io_client.dart)
#64     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:84:45)
#65     _rootRunBinary (dart:async/zone.dart:1144:38)
#66     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#67     _FutureListener.handleError (dart:async/future_impl.dart:140:20)
#68     Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#69     Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#70     Future._completeError (dart:async/future_impl.dart:491:5)
#71     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:539:7)
#72     _rootRun (dart:async/zone.dart:1124:13)
#73     _CustomZone.run (dart:async/zone.dart:1021:19)
#74     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#75     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#76     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#77     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#78     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

```

```
```

**Comment by jonahwilliams** [comment] 2019-08-12 02:57
Duplicate of https://github.com/flutter/flutter/issues/37223

**Closed by jonahwilliams** 2019-08-12 02:57 UTC
