### ISSUE TITLE
iOS Universal Links for Navigator2.0/Router with FlutterDeepLinkingEnabled

### ISSUE THREAD

**Issue by abegehr** [flutter/flutter#82550] opened 2021-05-14 16:55 UTC
## Steps to Reproduce

1. Create a new flutter app.
2. Setup the iOS config as outlined here: https://flutter.dev/docs/development/ui/navigation/deep-linking. Including setting FlutterDeepLinkingEnabled to true in the Info.plist
3. Create a simple `MaterialApp.router()` with a routeInformationParser that simply prints to the console (the app uses the beamer package for the routerDelegate, whereas the point here is that the routeInformationParser does not get called on deep link open) :
```
class App extends StatelessWidget {
  final routerDelegate = BeamerRouterDelegate(
    locationBuilder: BeamerLocationBuilder(
      beamLocations: [
        WelcomeLocation(),
      ],
    ),
    initialPath: WelcomeLocation.name,
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
        routeInformationParser: SimpleParser(),
        routerDelegate: routerDelegate,
    );
  }
}

class SimpleParser extends RouteInformationParser<Object> {
  @override
  Future<Object> parseRouteInformation(
      RouteInformation routeInformation) async {
    print('Deep Link – routeInformation: $routeInformation');
    return Future.value(Object());
  }
}
```
4. Run the app and open a deep link.

**Expected results:** 

`SimpleParser.parseRouteInformation()` gets called and a console log is printed for each deep link open when the app is running as is specified in the behavior section of the docs: https://flutter.dev/docs/development/ui/navigation/deep-linking#behavior

**Actual results:** 

`SimpleParser.parseRouteInformation()` gets called once on initial open and then does not got called when opening a deep link.
The deep link is registered somehow, since Analytics does notice the deep link open (see screenshot):
![Screenshot 2021-05-14 at 18 43 14](https://user-images.githubusercontent.com/23075874/118303406-b3ae7f00-b4e5-11eb-90b0-ceb07d171073.png)

<details>
  <summary>Logs</summary>

[log.txt](https://github.com/flutter/flutter/files/6480146/log.txt)

```
Analyzing smallgroups...                                                
No issues found! (ran in 5.3s)
```

```
[✓] Flutter (Channel dev, 2.3.0-1.0.pre, on macOS 11.3.1 20E241 darwin-x64, locale en-DE)
    • Flutter version 2.3.0-1.0.pre at /Users/anton/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d97f41caed (2 weeks ago), 2021-04-30 12:35:21 -0700
    • Engine revision e7939e091e
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/anton/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212
    ! Error: Anton’s iPhone is not connected. Xcode will continue when Anton’s iPhone is connected. (code -13)

• No issues found!
```
- I have just disconnected the iOS device but was testing on it before.

</details>

**Comment by abegehr** [comment] 2021-05-14 20:51
Using `getInitialLink()` and `linkStream` from [uni_links](https://pub.dev/packages/uni_links) and navigating on a deep link works. After reading https://flutter.dev/docs/development/ui/navigation/deep-linking#migrating-from-plugin-based-deep-linking, I was under the impression that the FlutterDeepLinkingEnabled flag would mean there is no need to handle incoming deep links manually. Is this not correct? What does FlutterDeepLinkingEnabled do in that case?

**Comment by slovnicki** [comment] 2021-05-15 12:37
Hi @abarth 

I followed the instructions at https://flutter.dev/docs/development/ui/navigation/deep-linking by adding
```xml
<!-- Deep linking -->
<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="http" android:host="flutterbooksample.com" />
    <data android:scheme="https" />
</intent-filter>
```
to the `AndroidManifest.xml` of beamer's [example app](https://github.com/slovnicki/beamer/tree/master/package/example) and it worked with **no changes** to the app's `lib/` folder.

Then I went on to define a `SimpleParser` similar to yours that also prints the incoming link;
```dart
class SimpleParser extends RouteInformationParser<BeamState> {
  @override
  SynchronousFuture<BeamState> parseRouteInformation(
      RouteInformation routeInformation) {
    print('incoming link: ${routeInformation.location}');
    final uri = Uri.parse(routeInformation.location ?? '/');
    return SynchronousFuture(BeamState.fromUri(uri));
  }

  @override
  RouteInformation restoreRouteInformation(BeamState beamState) {
    return RouteInformation(location: beamState.uri.toString());
  }
}
```
This also works as shown in the below gif.

![Peek 2021-05-15 14-25](https://user-images.githubusercontent.com/29288059/118361268-ea8aa080-b58a-11eb-8b85-1b4e8a346464.gif)

It's important that parser and delegate operate on same type of object, in this case  - `BeamState`.
**NOTE:** I used beamer from `master` on GitHub. Versions `<=0.12.4` would operate on `Uri` instead so `SimpleParser` should be tweaked accordingly.

**Comment by abegehr** [comment] 2021-05-16 22:29
Hey @slovnicki, thanks for checking this out! I have confirmed that this does work with a custom URL schema on iOS as well. It does however not work with [iOS universal links](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html).

I have built a minimal example with `MaterialApp.router()` and [beamer](https://pub.dev/packages/beamer) here: https://github.com/abegehr/flutter_beamer_deep_linking/tree/6261f9fb4d0f1cf1197684d7abdebe90ac64049b
To get the universal links to open the app, I had to publish the app to iOS App Store Connect and install a version via TestFlight. The apple-app-site-association file is hosted on Firebase hosting: http://flutterbeamerdeeplinking.web.app/apple-app-site-association (also deployed through the minimal repo example above).
While universal links do open the app, they do not navigate. Custom schema links do trigger a navigation. I have tried both custom url schema and universal links with and without `/#`. You can see in this screen recording that only option 3 (custom schema, no `/#` navigates to book 13: 

https://user-images.githubusercontent.com/23075874/118414769-c6bc7d00-b6a6-11eb-8e96-8495b6bdddf8.mov

**Comment by slovnicki** [comment] 2021-05-16 22:35
This is a very valuable investigation @abegehr :+1: 
I'm wondering what will other people comment on this as I don't have any experience in iOS universal links.

**Comment by abegehr** [comment] 2021-05-16 22:44
BeamerParser.onParse() does not get called for iOS universal links: https://github.com/abegehr/flutter_beamer_deep_linking/tree/3f1b72901655472f6b7e1441d72cfb84cae81ebd
I will now try an implementation without beamer.

**Comment by abegehr** [comment] 2021-05-16 23:13
I validated that the issue that Flutter does not navigate on iOS universal links is not a beamer issue. Here is a minimal example based on the [medium article's](https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade) books example (that does not use the beamer package: https://github.com/abegehr/flutter_beamer_deep_linking/tree/0c3a5a0c2760f08ebaa63ab1831e4b8bd73f5705
On [line 12 of main.dart](https://github.com/abegehr/flutter_beamer_deep_linking/blob/0c3a5a0c2760f08ebaa63ab1831e4b8bd73f5705/lib/main.dart#L12), I'm logging `routeInformation.location` in `BookRouteInformationParser.parseRouteInformation(routeInformation)`. Flutter does log `routeInformation.location` as /books/13 when I click the custom schema link `flutterbeamerdeeplinking://flutterbeamerdeeplinking.web.app/books/13`, but not if I click the universal link `https://flutterbeamerdeeplinking.web.app/books/13` (both links open the app). Therefore, I assume [Flutter deep linking](https://flutter.dev/docs/development/ui/navigation/deep-linking) currently does not support iOS universal links but only custom schema links.

**Comment by abegehr** [comment] 2021-05-16 23:16
One work around to get deep linking to work with iOS universal links currently is to use a package like [uri_links](https://pub.dev/packages/uni_links) and navigate manually on getInitialLink() and new entries to linkStream.

**Comment by abegehr** [comment] 2021-05-16 23:22
I've also tried setting the URL Scheme to `https`: 
![Screenshot 2021-05-17 at 01 19 04](https://user-images.githubusercontent.com/23075874/118416019-df7c6100-b6ad-11eb-9a13-2c3f7d68c860.png)
This does not seep to work for https://flutterbeamerdeeplinking.web.app/books/13 either.

**Comment by TahaTesser** [comment] 2021-05-17 11:31
Hi @abegehr 
I'm not familiar with deep linking on iOS, since you've provided all the details needed, I feel safe to label issue 
Thanks for filiing the issue!

**Comment by sullenel** [comment] 2021-05-18 20:12
This is likely a duplicate of https://github.com/flutter/flutter/issues/80580. Universal links don't work when using `onGenerateInitialRoutes`/`onGenerateRoute` either.

**Comment by goderbauer** [comment] 2021-05-20 22:16
Thanks for the report!

Looks like we're missing engine support to handle universal links on iOS. There was an attempt to add support for it in https://github.com/flutter/engine/pull/25705, but it got abandoned. Maybe someone here is interested in picking that back up again?

/cc @chunhtai @gaaclarke FYI since you implemented the original deep link support.

**Comment by AlBlanc** [comment] 2021-05-20 23:47
@goderbauer I made a pull request. It works (I use it in my project)

I must fix the test. I'll fix the test before the end of the week.

**Comment by chinmaygarde** [comment] 2021-05-24 18:13
@jmagman: The linked PR was stale but it looks like we have enough information to make progress on this. Can we followup on a fix for this please?

**Comment by jmagman** [comment] 2021-05-24 21:21
> @jmagman: The linked PR was stale but it looks like we have enough information to make progress on this. Can we followup on a fix for this please?

I'll wait for @AlBlanc to follow up:
 
> I must fix the test. I'll fix the test before the end of the week.

**Comment by michaelmairegger** [comment] 2021-06-10 14:24
Any news on that issue?

**Comment by janjoosse** [comment] 2021-07-11 10:50
Is there any progress on the PR?

**Comment by gaaclarke** [comment] 2021-07-19 17:23
@AlBlanc's PR was closed when it became stale.  There was some feedback from @jmagman that wasn't addressed.  The PR doesn't seem to be that big, it would probably be easy to pick up again.

**Comment by Justice4Joffrey** [comment] 2021-07-29 09:21
Would be great if someone could pick this up.

**Comment by janjoosse** [comment] 2021-07-29 11:48
I want to help but have zero experience with Swift/ iOS development, so the PR changes are kind of abracadabra to me. Is there anyone with iOS experience who can assist?

**Comment by AlBlanc** [comment] 2021-07-29 12:00
I am deeply sorry guys. I can just tell you the fix works (as I am using it in few apps) but I don't have time to fix the test (and also I am running out of space on my laptop hard drive to download/compile flutter)

**Closed** 2021-08-09 21:35 UTC
Labels: platform-ios, engine, f: routes, passed first triage, P3

**Comment by tahitiangabriel** [comment] 2021-08-12 02:36
It works with the master channel. Thank you for the PR.
