### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by nevilpurpp** [flutter/flutter#76487] opened 2021-02-21 15:03 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Access is denied.
, errno = 5
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 1.22.6 at C:\Users\USER\Desktop\winner\anim\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment] 2021-02-21 17:21
duplicate of https://github.com/flutter/flutter/issues/69116

@nevilpurpp 
please try this possible [solution](https://github.com/flutter/flutter/issues/69116#issuecomment-775765289)

**Comment by pedromassangocode** [comment] 2021-02-22 09:16
Closing as duplicate of https://github.com/flutter/flutter/issues/69116.

**Closed by pedromassangocode** 2021-02-22 09:16 UTC
Labels: in triage
