### ISSUE TITLE
Textfield obscureText interaction exception

### ISSUE THREAD

**Issue by tarcyys** [flutter/flutter#152292] opened 2024-07-25 03:24 UTC
### Steps to reproduce

First click on a textfield whose obscureText is false(true)
Click again on a textfield whose obscureText is true (false)

### Expected results

The keyboard should not disappear and reappear. It should directly determine the keyboard type and focus on the new textfield.

### Actual results

The keyboard animation pops up and disappears abnormally. The cursor disappears and needs to be clicked again to focus.

Upgrading from 3.10.0 to 3.16.0 appears, in HarmonyOS 4,

### Code sample

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('Demo'),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
                key: Key('a'),
                keyboardType: TextInputType.numberWithOptions(signed: true),
                decoration: InputDecoration(hintText: ' a obscureText false')),
            TextField(
                key: Key('c'),
                keyboardType: TextInputType.text,
                obscureText: true,
                decoration: InputDecoration(hintText: ' c obscureText true')),
          ],
        ),
      ),
    );
  }
}

### Screenshots or Video

https://private-user-images.githubusercontent.com/122137647/323926514-7d18f9cf-65f3-458c-bd30-496ca76c8729.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzgxMjQsIm5iZiI6MTcyMTg3NzgyNCwicGF0aCI6Ii8xMjIxMzc2NDcvMzIzOTI2NTE0LTdkMThmOWNmLTY1ZjMtNDU4Yy1iZDMwLTQ5NmNhNzZjODcyOS5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwMzIzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGRhYWEwMDg4NzVmOGI3OWNhNzVhMzYzNWQ5YzA2ZjQyOGE5MDA3OTQ5OGViNjM2MjExNDA3YmJlYjViNTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sUxZhqS-qpBha49Y7q7SVoLXbmo3QjMYNJtUzUn28RE

https://private-user-images.githubusercontent.com/122137647/323825758-f3f163b3-5e4c-4f93-a1fd-ab18eaafa1f1.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzgxMjQsIm5iZiI6MTcyMTg3NzgyNCwicGF0aCI6Ii8xMjIxMzc2NDcvMzIzODI1NzU4LWYzZjE2M2IzLTVlNGMtNGY5My1hMWZkLWFiMThlYWFmYTFmMS5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwMzIzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTEwNTI3ZmNjOGMxNjQ2YTAxODU3M2Y2ZWU2MjdjNWJjMGNkMDY2MWRlZThmZjFlZjY2MGUxNTdjMzQ3ZmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mAVT3ox844dJM6DgpLbIZVrT-bvJ5q7JT0NpWE4P6JA

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-25 08:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/140369

**Closed by danagbemava-nc** 2024-07-25 08:59 UTC
Labels: in triage
