### ISSUE TITLE
Pasting into a textbox not doing anything on android

### ISSUE THREAD

**Issue by MichaelRFairhurst** [flutter/flutter#13091] opened 2017-11-19 22:28 UTC
## Steps to Reproduce

Haven't tested on iOS

```dart
    return new Scaffold(                                                         
        appBar: new AppBar(                                                      
          title: new Text('Enter text to read'),                                 
        ),                                                                       
        body: new Center(                                                        
            child: new Column(children: [                                        
          new Expanded(                                                          
              child: new Container(                                              
            margin: new EdgeInsets.all(4.0),                                     
            padding: new EdgeInsets.all(4.0),                                    
            decoration: const BoxDecoration(                                     
                border: const Border(                                            
              top: const BorderSide(width: 2.0, color: Colors.grey),             
              left: const BorderSide(width: 2.0, color: Colors.grey),            
              right: const BorderSide(width: 2.0, color: Colors.grey),           
              bottom: const BorderSide(width: 2.0, color: Colors.grey),          
            )),                                                                  
            child: new TextField(                                                
                maxLines: 10000, // null has a bug                               
                controller: _controller,                                         
                decoration: new InputDecoration(                                 
                  hintText: 'Enter some text for paced reading',                 
                ),                                                               
                onChanged: _action,                                              
                onSubmitted: (String str) {                                      
                  Navigator.of(context).push(new MaterialPageRoute<Null>(        
                      builder: (_) => new MyReadPage(text: str)));               
                }),                                                              
          ))                                                                     
        ])));   
```

If I copy some text (and verify I can paste it in other apps), and paste it, it does nothing

## Logs

Nothing in the logs/analyze

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/mfairhurst/dart/flutter
    • Framework revision e8aa40eddd (5 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/mfairhurst
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /home/mfairhurst
    • Java binary at: /usr/local/buildtools/java/jdk8-google-v7-64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-google-v7-169763474-169682997)

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[-] IntelliJ IDEA Ultimate Edition (version 2016.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 162.2485
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[-] IntelliJ IDEA Ultimate Edition (version 2017.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 172.2791
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[-] IntelliJ IDEA Ultimate Edition (version 2016.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 163.8651
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected devices
    • ONEPLUS A5000 • d6843768 • android-arm • Android 7.1.1 (API 25)
```

**Comment by eseidelGoogle** [comment] 2017-11-20 17:07
Eek.  We had a bug like this before (maybe that was on iOS?) and fixed it.

**Comment by Hixie** [comment] 2017-11-20 18:45
Weird. We've also received reports that pasting doesn't work into dialogs, maybe it's related: https://github.com/flutter/flutter/issues/13021

**Comment by HansMuller** [comment] 2018-11-20 19:29
I'm closing this because it doesn't appear to be a bug anymore. Copying and pasting within an app based on the code in the description and between the app and other Android apps, all appear to work. 

Checked with this test case: https://gist.github.com/HansMuller/c6fd7fe13afd34d95c7c06a6a7e19b50 using a `Nexus 5 • 05f0097ed007ad8c • android-arm • Android 5.1.1 (API 22)`.

This does appear to be a duplicate of #13201 (closed as well).

If the test case still fails on a particular device, or if a different version of the test case fails, please reopen this bug.

**Closed by HansMuller** 2018-11-20 19:29 UTC
Labels: a: text input, ▣ platform-android
