### ISSUE TITLE
LayoutBuilder and on-screen keyboard interfering with TextField focus

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#63919] opened 2020-08-16 22:58 UTC
## Steps to Reproduce

1. Run `flutter create chat_msg_bug`.
2. Update the `main.dart` file with:
  * add:  `import 'chat.dart'`
  * replace the `floatingActionButton` with:
```dart
      floatingActionButton: FloatingActionButton(
        //onPressed: _incrementCounter,
        onPressed: () => Navigator.push(
          context,
          MaterialPageRoute(
            builder: (BuildContext context) => OrderChatScreen(),
            settings: const RouteSettings(name: 'OrderChatScreen'),
            fullscreenDialog: true,
          ),
        ),
        tooltip: 'Chat', // 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
```
3. Add the `chat.dart` file:
```dart
import 'dart:async';
import 'package:flutter/material.dart';

class OrderChatScreen extends StatelessWidget {
  OrderChatScreen({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Chat Message Bug')),
      body: OrderChat(),
    );
  }
}

class OrderChat extends StatefulWidget {
  OrderChat({
    Key key,
  }) : super(key: key);

  @override
  _OrderChatState createState() => _OrderChatState();
}

class _OrderChatState extends State<OrderChat> {
  final _conversationController = ScrollController();
  final _chatMessageController = TextEditingController();
  final _chatMessageFocusNode = FocusNode();

  final List<String> messages = [];

  @override
  void dispose() {
    _chatMessageController.dispose();
    super.dispose();
  }

  Widget _buildChatMessage() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10.0),
      child: TextField(
        controller: _chatMessageController,
        focusNode: _chatMessageFocusNode,
        decoration: InputDecoration(
          icon: const Icon(Icons.message),
          hintText: 'Message',
          suffixIcon: IconButton(
            icon: const Icon(Icons.close),
            onPressed: () => _chatMessageController.clear(),
          ),
        ),
        textInputAction: TextInputAction.send,
        maxLines: null,
        maxLength: 1000,
        onSubmitted: (message) async {
          await _submitChatMessage(message);
          _chatMessageController.clear();
          _chatMessageFocusNode.requestFocus();
        },
      ),
    );
  }

  Future<void> _submitChatMessage(String message) async {
    if (true == message?.isNotEmpty) {
      setState(() {
        messages.add(message);
      });

      // Scroll the chat to the end (0 is the end because the ListView is reversed)
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (_conversationController.hasClients) {
          _conversationController.jumpTo(0.0);
        }
      });
    }
  }

  Widget _buildContextCard() {
    return Card(
      child: Column(
        children: [
          Placeholder(),
          Placeholder(),
          Placeholder(),
        ],
      ),
    );
  }

  Widget _buildConversation() {
    return ListView.builder(
      controller: _conversationController,
      reverse: true,
      shrinkWrap: true,
      itemBuilder: (BuildContext context, int index) {
        // Double reverse to order and scroll correctly
        final message = messages[messages.length - index - 1];
        return ListTile(
          key: ObjectKey(message),
          title: SelectableText(message),
        );
      },
      itemCount: messages.length,
    );
  }

  Widget _buildPortraitLayout(BoxConstraints constraints) {
    return Column(
      children: <Widget>[
        Expanded(
          child: ListView(
            shrinkWrap: true,
            children: [
              _buildContextCard(),
              const Divider(
                color: Colors.green,
                thickness: 2,
              ),
            ],
          ),
        ),
        LimitedBox(
          maxHeight: constraints.maxHeight / 3,
          child: _buildConversation(),
        ),
        SafeArea(
          child: _buildChatMessage(),
        ),
      ],
    );
  }

  Widget _buildLandscapeLayout() {
    return Row(
      children: <Widget>[
        Expanded(
          child: Column(
            children: [
              Expanded(
                child: ListView(
                  shrinkWrap: true,
                  children: [
                    _buildContextCard(),
                    const Divider(
                      color: Colors.green,
                      thickness: 2,
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        Expanded(
          child: Container(
            padding: const EdgeInsets.all(10.0),
            child: Column(
              children: <Widget>[
                Expanded(
                  child: _buildConversation(),
                ),
                SafeArea(
                  child: _buildChatMessage(),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (context, constraints) =>
            constraints.maxWidth < constraints.maxHeight
                ? _buildPortraitLayout(constraints)
                : _buildLandscapeLayout());
  }
}
```

4. `flutter run` on an Android device or emulator.  I replicated this using a **Lenovo Tab E7** (Android 8.1.0).
 * While in _Portrait_ mode, click/tap on the bottom Message field.

**Expected results:** 

This is extracted from a Chat screen.  I should be able to click on the message field, then enter a message to send.

**Actual results:** 

Unfortunately, with Android, the keyboard pops up and triggers a layout and my focus is being lost on the message field.

It is difficult to explain, so it is easier if you watch the attached video:
![chat_msg_bug](https://user-images.githubusercontent.com/123887/90345757-3991ae00-dfd8-11ea-9296-accb38dfd97d.gif)

You can witness the correct behavior (for Portrait) when your simplify the build:
```dart
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (context, constraints) => _buildPortraitLayout(constraints));
  }
```
However, the screen is intentionally using LayoutBuilder to provide a responsive layout depending on if the screen is in Landscape or Portrait.  When in Portrait, the components are stacked vertically, and when in Landscape, the components are split into two columns.

Note that the layout works fine on the Apple Simulator and iPhone.  This issue seems limited to Android.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.2 at /Users/anthony/flutter
    • Framework revision bbfbf1770c (3 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/anthony/Library/Android/sdk
    • Platform android-R, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2020-08-17 10:16
Hi @awhitford 
I was able to reproduce this on both, Android and iOS(13.6) devices.

As a workaround I suggest you to check the device's orientation state and use it in place of LayoutBuilder:

```dart
  @override
  Widget build(BuildContext context) {
    final orientation = MediaQuery.of(context).orientation;
    
    if (orientation == Orientation.portrait)
      return _buildPortraitLayout();
    return _buildLandscapeLayout();
  }
```

<details>
<summary> complete sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Tab Orientation Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> with SingleTickerProviderStateMixin {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        //onPressed: _incrementCounter,
        onPressed: () => Navigator.push(
          context,
          MaterialPageRoute(
            builder: (BuildContext context) => OrderChatScreen(),
            settings: const RouteSettings(name: 'OrderChatScreen'),
            fullscreenDialog: true,
          ),
        ),
        tooltip: 'Chat', // 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class OrderChatScreen extends StatelessWidget {
  OrderChatScreen({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Chat Message Bug')),
      body: OrderChat(),
    );
  }
}

class OrderChat extends StatefulWidget {
  OrderChat({
    Key key,
  }) : super(key: key);

  @override
  _OrderChatState createState() => _OrderChatState();
}

class _OrderChatState extends State<OrderChat> {
  final _conversationController = ScrollController();
  final _chatMessageController = TextEditingController();
  final _chatMessageFocusNode = FocusNode();

  final List<String> messages = [];

  @override
  void dispose() {
    _chatMessageController.dispose();
    super.dispose();
  }

  Widget _buildChatMessage() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10.0),
      child: TextField(
        controller: _chatMessageController,
        focusNode: _chatMessageFocusNode,
        decoration: InputDecoration(
          icon: const Icon(Icons.message),
          hintText: 'Message',
          suffixIcon: IconButton(
            icon: const Icon(Icons.close),
            onPressed: () => _chatMessageController.clear(),
          ),
        ),
        textInputAction: TextInputAction.send,
        maxLines: null,
        maxLength: 1000,
        onSubmitted: (message) async {
          await _submitChatMessage(message);
          _chatMessageController.clear();
          _chatMessageFocusNode.requestFocus();
        },
      ),
    );
  }

  Future<void> _submitChatMessage(String message) async {
    if (true == message?.isNotEmpty) {
      setState(() {
        messages.add(message);
      });

      // Scroll the chat to the end (0 is the end because the ListView is reversed)
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (_conversationController.hasClients) {
          _conversationController.jumpTo(0.0);
        }
      });
    }
  }

  Widget _buildContextCard() {
    return Card(
      child: Column(
        children: [
          Placeholder(),
          Placeholder(),
          Placeholder(),
        ],
      ),
    );
  }

  Widget _buildConversation() {
    return ListView.builder(
      controller: _conversationController,
      reverse: true,
      shrinkWrap: true,
      itemBuilder: (BuildContext context, int index) {
        // Double reverse to order and scroll correctly
        final message = messages[messages.length - index - 1];
        return ListTile(
          key: ObjectKey(message),
          title: SelectableText(message),
        );
      },
      itemCount: messages.length,
    );
  }

  Widget _buildPortraitLayout(BoxConstraints constraints) {
    return Column(
      children: <Widget>[
        Expanded(
          child: ListView(
            shrinkWrap: true,
            children: [
              _buildContextCard(),
              const Divider(
                color: Colors.green,
                thickness: 2,
              ),
            ],
          ),
        ),
        LimitedBox(
          maxHeight: constraints.maxHeight / 3,
          child: _buildConversation(),
        ),
        SafeArea(
          child: _buildChatMessage(),
        ),
      ],
    );
  }

  Widget _buildLandscapeLayout() {
    return Row(
      children: <Widget>[
        Expanded(
          child: Column(
            children: [
              Expanded(
                child: ListView(
                  shrinkWrap: true,
                  children: [
                    _buildContextCard(),
                    const Divider(
                      color: Colors.green,
                      thickness: 2,
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        Expanded(
          child: Container(
            padding: const EdgeInsets.all(10.0),
            child: Column(
              children: <Widget>[
                Expanded(
                  child: _buildConversation(),
                ),
                SafeArea(
                  child: _buildChatMessage(),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (context, constraints) =>
        constraints.maxWidth < constraints.maxHeight
            ? _buildPortraitLayout(constraints)
            : _buildLandscapeLayout());
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.2 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision bbfbf1770c (4 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 1119074E-0493-4533-9212-6758A33EB40C
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 3 categories.
```
</details>

**Comment by awhitford** [comment] 2020-08-17 14:17
@pedromassangocode Thank you for the update and recommendation.  Note that I did try swapping `LayoutBuilder` with `OrientationBuilder`, but that did not resolve the issue -- I see know that `OrientationBuilder` is a thin wrapper for `LayoutBuilder`.  However, your advice to use `MediaQuery` works fine.

**Comment by Hamza5** [comment] 2020-11-24 20:18
I am suffering from the same issue when trying to design login/register pages that should fill the entire body (so I need `LayoutBuilder`) while being scrollable as well using `SingleChildScrollView` when the virtual keyboard pops out.

**Comment by simon-the-shark** [comment] 2021-01-13 14:55
@Hamza5 I had a similar problem and ended up adding the keyboard height to `maxHeight` from `LayoutBuilder`, calculated this way:
`EdgeInsets.fromWindowPadding(WidgetsBinding.instance.window.viewInsets,                       WidgetsBinding.instance.window.devicePixelRatio).bottom` 
It holds keyboard height when visible and is equal to 0 when there's none on the screen.

**Comment by maheshmnj** [comment] 2022-12-07 14:45
Hi @awhitford, I verified the issue on stable and the master channel and I am unable to reproduce it.


https://user-images.githubusercontent.com/31410839/206209472-ce8ac874-d22f-4298-89da-95c141874826.mov



<details>
<summary>code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
          appBar: AppBar(
            title: Text('Material App Bar'),
          ),
          body: NewPage()),
    );
  }
}

class NewPage extends StatefulWidget {
  const NewPage({Key? key}) : super(key: key);

  @override
  State<NewPage> createState() => _NewPageState();
}

class _NewPageState extends State<NewPage> {
  @override
  Widget build(BuildContext context) {
    return Center(
        child: ElevatedButton(
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => OrderChatScreen()),
              );
            },
            child: Text('tap me')));
  }
}

class OrderChatScreen extends StatelessWidget {
  OrderChatScreen({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Chat Message Bug')),
      body: OrderChat(),
    );
  }
}

class OrderChat extends StatefulWidget {
  OrderChat({
    Key? key,
  }) : super(key: key);

  @override
  _OrderChatState createState() => _OrderChatState();
}

class _OrderChatState extends State<OrderChat> {
  final _conversationController = ScrollController();
  final _chatMessageController = TextEditingController();
  final _chatMessageFocusNode = FocusNode();

  final List<String> messages = [];

  @override
  void dispose() {
    _chatMessageController.dispose();
    super.dispose();
  }

  Widget _buildChatMessage() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10.0),
      child: TextField(
        controller: _chatMessageController,
        focusNode: _chatMessageFocusNode,
        decoration: InputDecoration(
          icon: const Icon(Icons.message),
          hintText: 'Message',
          suffixIcon: IconButton(
            icon: const Icon(Icons.close),
            onPressed: () => _chatMessageController.clear(),
          ),
        ),
        textInputAction: TextInputAction.send,
        maxLines: null,
        maxLength: 1000,
        onSubmitted: (message) async {
          await _submitChatMessage(message);
          _chatMessageController.clear();
          _chatMessageFocusNode.requestFocus();
        },
      ),
    );
  }

  Future<void> _submitChatMessage(String message) async {
    if (true == message?.isNotEmpty) {
      setState(() {
        messages.add(message);
      });

      // Scroll the chat to the end (0 is the end because the ListView is reversed)
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (_conversationController.hasClients) {
          _conversationController.jumpTo(0.0);
        }
      });
    }
  }

  Widget _buildContextCard() {
    return Card(
      child: Column(
        children: [
          Placeholder(),
          Placeholder(),
          Placeholder(),
        ],
      ),
    );
  }

  Widget _buildConversation() {
    return ListView.builder(
      controller: _conversationController,
      reverse: true,
      shrinkWrap: true,
      itemBuilder: (BuildContext context, int index) {
        // Double reverse to order and scroll correctly
        final message = messages[messages.length - index - 1];
        return ListTile(
          key: ObjectKey(message),
          title: SelectableText(message),
        );
      },
      itemCount: messages.length,
    );
  }

  Widget _buildPortraitLayout(BoxConstraints constraints) {
    return Column(
      children: <Widget>[
        Expanded(
          child: ListView(
            shrinkWrap: true,
            children: [
              _buildContextCard(),
              const Divider(
                color: Colors.green,
                thickness: 2,
              ),
            ],
          ),
        ),
        LimitedBox(
          maxHeight: constraints.maxHeight / 3,
          child: _buildConversation(),
        ),
        SafeArea(
          child: _buildChatMessage(),
        ),
      ],
    );
  }

  Widget _buildLandscapeLayout() {
    return Row(
      children: <Widget>[
        Expanded(
          child: Column(
            children: [
              Expanded(
                child: ListView(
                  shrinkWrap: true,
                  children: [
                    _buildContextCard(),
                    const Divider(
                      color: Colors.green,
                      thickness: 2,
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        Expanded(
          child: Container(
            padding: const EdgeInsets.all(10.0),
            child: Column(
              children: <Widget>[
                Expanded(
                  child: _buildConversation(),
                ),
                SafeArea(
                  child: _buildChatMessage(),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (context, constraints) =>
            constraints.maxWidth < constraints.maxHeight
                ? _buildPortraitLayout(constraints)
                : _buildLandscapeLayout());
  }
}
```
</details>  

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as fixed, incase anyone still encounters the problem feel free to leave a comment on this issue with more details and we will reopen it.

**Closed by maheshmnj** 2022-12-07 14:45 UTC
Labels: a: text input, framework, f: material design, f: focus, has reproducible steps, found in release: 1.20
