### ISSUE TITLE
TabController doesn't change TabBarView

### ISSUE THREAD

**Issue by MagTuxGit** [flutter/flutter#92175] opened 2021-10-20 14:26 UTC
I need to change tabs programmatically and stay on the current tab.
Doing animateTo() I'm able to change tab but TabBarView doesn't change.

## Steps to Reproduce

Run the sample, tap + button.

**Expected results:** Current Tab and TabBarView don't change

**Actual results:** Current Tab doesn't change but current TabBarView does

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      debugShowCheckedModeBanner: false,
      home: TestPage(),
    ));

class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  late List<TabWidget> _tabs;
  int currentTabValue = 0;

  @override
  void initState() {
    super.initState();
    _tabs = List.generate(5, (index) => TabWidget(index));
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: _tabs.length,
      child: Builder(builder: builder),
    );
  }

  Widget builder(BuildContext context) {
    final tabController = DefaultTabController.of(context)!;
    tabController.addListener(() {
      currentTabValue = _tabs[tabController.index].value;
    });

    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          IconButton(
            icon: const Icon(Icons.add),
            onPressed: () async {
              setState(() => _tabs.insert(0, TabWidget(_tabs.length)));
              final int currentTabIndex =
                  _tabs.indexWhere((tab) => tab.value == currentTabValue);
              tabController.animateTo(currentTabIndex, duration: Duration.zero);
            },
          ),
        ],
        centerTitle: false,
        title: TabBar(
          isScrollable: true,
          tabs: _tabs.map((var tab) {
            return Tab(
              child: GestureDetector(
                onLongPress: () => setState(() => _tabs.remove(tab)),
                child: tab,
              ),
            );
          }).toList(),
        ),
      ),
      body: TabBarView(
        children: _tabs.toList(),
      ),
    );
  }
}

class TabWidget extends StatelessWidget {
  final int value;

  const TabWidget(this.value, {Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Text('Tab $value');
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-UA)
    • Flutter version 2.5.2 at /Users/trand/DEV/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/trand/Library/Android/sdk
    • Platform android-S, build-tools 30.0.2
    • ANDROID_HOME = /Users/trand/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

</details>

**Comment by danagbemava-nc** [comment] 2021-10-21 09:59
Hi @MagTuxGit, there's a similar issue filed https://github.com/flutter/flutter/issues/89367. Although the issue states deleting a tab, since it's the same `TabController` that handles the operation, i believe the same can said of adding. 

PS: I tested the sample the author of #89367 posted and modified it to attempt adding and the same behaviour could be reproduced. 

As such I'll be closing this issue as a duplicate of #89367 so that the issue with `TabController` and `TabBarView` can be tracked in one place. 

Thank you

**Closed by danagbemava-nc** 2021-10-21 09:59 UTC
Labels: in triage
