### ISSUE TITLE
google adsense support for flutter web

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#80240] opened 2021-04-11 23:44 UTC
add google adsense  support for flutter web so that    we  monetization our  flutter web app

**Comment by iapicca** [comment] 2021-04-12 00:35
@samithe7 
unlikely to happen until this is fixed https://github.com/flutter/flutter/issues/46789

**Comment by pedromassangocode** [comment] 2021-04-12 09:52
Closing as duplicate of https://github.com/flutter/flutter/issues/40376.

**Closed by pedromassangocode** 2021-04-12 09:52 UTC
Labels: in triage
