### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAvailableBiometrics on channel plugins.flutter.io/local_auth)

### ISSUE THREAD

**Issue by mhabashy** [flutter/flutter#64005] opened 2020-08-17 23:23 UTC
Hello,

Have two projects in android that have an issue with local_auth not reaching implementation. local_auth 0.6.2+3

```
An Observatory debugger and profiler on Pixel 2 XL is available at: http://127.0.0.1:63640/9wh-VfviJOw=/
W/Gralloc3( 1922): mapper 3.x is not supported
E/flutter ( 1922): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAvailableBiometrics on channel plugins.flutter.io/local_auth)
E/flutter ( 1922): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter ( 1922): <asynchronous suspension>
E/flutter ( 1922): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter ( 1922): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:347:40)
E/flutter ( 1922): #3      LocalAuthentication.canCheckBiometrics (package:local_auth/local_auth.dart:115:23)=
```

`authenticateWithBiometrics` does the same.

### Flutter docker

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.48.0)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
------------

MainActivity
package <PACKAGE_NAME>

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
   
}

**Comment by TahaTesser** [comment] 2020-08-18 10:40
Hi @mhabashy 
Could please try with following  on `local_auth: ^0.6.2+3` and execute `flutter pub get`, no issues 
```
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
```

<details> 
<summary>code sample</summary> 

```dart
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final LocalAuthentication auth = LocalAuthentication();
  bool _canCheckBiometrics;
  List<BiometricType> _availableBiometrics;
  String _authorized = 'Not Authorized';
  bool _isAuthenticating = false;

  Future<void> _checkBiometrics() async {
    bool canCheckBiometrics;
    try {
      canCheckBiometrics = await auth.canCheckBiometrics;
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _canCheckBiometrics = canCheckBiometrics;
    });
  }

  Future<void> _getAvailableBiometrics() async {
    List<BiometricType> availableBiometrics;
    try {
      availableBiometrics = await auth.getAvailableBiometrics();
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _availableBiometrics = availableBiometrics;
    });
  }

  Future<void> _authenticate() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticateWithBiometrics(
          localizedReason: 'Scan your fingerprint to authenticate',
          useErrorDialogs: true,
          stickyAuth: true);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Authenticating';
      });
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    final String message = authenticated ? 'Authorized' : 'Not Authorized';
    setState(() {
      _authorized = message;
    });
  }

  void _cancelAuthentication() {
    auth.stopAuthentication();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: <Widget>[
                Text('Can check biometrics: $_canCheckBiometrics\n'),
                RaisedButton(
                  child: const Text('Check biometrics'),
                  onPressed: _checkBiometrics,
                ),
                Text('Available biometrics: $_availableBiometrics\n'),
                RaisedButton(
                  child: const Text('Get available biometrics'),
                  onPressed: _getAvailableBiometrics,
                ),
                Text('Current State: $_authorized\n'),
                RaisedButton(
                  child: Text(_isAuthenticating ? 'Cancel' : 'Authenticate'),
                  onPressed:
                      _isAuthenticating ? _cancelAuthentication : _authenticate,
                )
              ])),
    ));
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (5 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (1 available)            
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

**Comment by mhabashy** [comment] 2020-08-18 12:42
@TahaTesser  thanks for responding. 

When adding that snippet to the MainActivity, it breaks one other flutter package but I can always replace that package. However, also get the following error.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fastlending.app, PID: 17443
    java.lang.ClassCastException: <package>.MainActivity cannot be cast to androidx.appcompat.app.AppCompatActivity
        at io.flutter.plugins.localauth.LocalAuthPlugin.onAttachedToActivity(LocalAuthPlugin.java:183)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java:143)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
        at com.fastlending.app.MainActivity.configureFlutterEngine(MainActivity.kt:10)
```

**Comment by TahaTesser** [comment] 2020-08-19 08:26
Hi @mhabashy 
Your error is related to AndroidX incompatibility, you need to [migrate to AndroidX](https://flutter.dev/docs/development/androidx-migration) in your existing project. or try a new project with AndroidX 
`MainActivity cannot be cast to androidx.appcompat.app.AppCompatActivityat io.flutter.plugins.localauth.LocalAuthPlugin.onAttachedToActivity(LocalAuthPlugin.java:183)` 

Please create new project with AndroidX, add the code sample, MainActivity (including imports) package from https://github.com/flutter/flutter/issues/64005#issuecomment-675403583

<img width="376" alt="Screenshot 2020-08-19 at 1 50 05 PM" src="https://user-images.githubusercontent.com/48603081/90610813-96cd6f80-e223-11ea-82aa-f4dbd8fe32db.png">


 also add  `<uses-permission android:name="android.permission.USE_FINGERPRINT"/>` in your `AndroidManifest.xml`

**Comment by mhabashy** [comment] 2020-08-19 14:31
@TahaTesser ran androidX it finished with `No Usages Found in the project` - I installed a different version of an android studio and ran the same somehow it worked. was using android 4.0.1 - moved to 4.1 RC beta. Thanks for the help

**Comment by TahaTesser** [comment] 2020-08-21 06:42
Hi @mhabashy 
This doesn't reproduce with androidx, your project might not have proper configured android. Just only android in Android Studio, not entire project and migrate 

Since the issue isn't and given your last message I feel safe to close this issue,if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-08-21 06:42 UTC
Labels: in triage
