### ISSUE TITLE
Cannot use any GestureRecognizer on a TextSpan in RichText if a WidgetSpan is present

### ISSUE THREAD

**Issue by Luk3s** [flutter/flutter#51936] opened 2020-03-04 15:06 UTC
## Steps to Reproduce

If the following app does not run on the first try, first remove the recognizer and then add it again using hot reload 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() => runApp(MaterialApp(
  home: BuzzingText()
));

class BuzzingText extends StatefulWidget {
  @override
  _BuzzingTextState createState() => _BuzzingTextState();
}

class _BuzzingTextState extends State<BuzzingText> {
  TapGestureRecognizer _tapRecognizer;

  @override
  void initState() {
    super.initState();
    _tapRecognizer = TapGestureRecognizer()
      ..onTap = () => print('tapped');
  }

  @override
  void dispose() {
    _tapRecognizer.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Text.rich(
      TextSpan(
        text: 'Can you ',
        style: TextStyle(color: Colors.black),
        children: <InlineSpan>[
          TextSpan(
            text: 'find the',
            style: TextStyle(
              color: Colors.green,
              decoration: TextDecoration.underline,
              decorationStyle: TextDecorationStyle.wavy,
            ),
            recognizer: _tapRecognizer,
          ),
          TextSpan(
            text: ' secret?',
          ),
          WidgetSpan(
            child: Icon(Icons.search)
          )
        ],
      ),
    )
    );
  }
}
```

<details>
  <summary>Logs</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following RangeError was thrown during a scheduler callback:
flutter: RangeError (index): Invalid value: Valid value range is empty: 0
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.[] (dart:core-patch/growable_array.dart:146:60)
flutter: #1      List.elementAt (dart:core-patch/growable_array.dart:355:16)
flutter: #2      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:878:50)
flutter: #3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3659:13)
flutter: #4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #5      ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
flutter: #6      new List.from (dart:core-patch/array_patch.dart:47:19)
flutter: #7      Iterable.toList (dart:core/iterable.dart:400:5)
flutter: #8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3656:8)
flutter: #9      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #10     ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
flutter: #11     new List.from (dart:core-patch/array_patch.dart:47:19)
flutter: #12     Iterable.toList (dart:core/iterable.dart:400:5)
flutter: #13     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3656:8)
flutter: #14     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #15     ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
flutter: #16     new List.from (dart:core-patch/array_patch.dart:47:19)
flutter: #17     Iterable.toList (dart:core/iterable.dart:400:5)
flutter: #18     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3656:8)
flutter: #19     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #20     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:139:32)
flutter: #21     ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
flutter: #22     new List.from (dart:core-patch/array_patch.dart:47:19)
flutter: #23     Iterable.toList (dart:core/iterable.dart:400:5)
flutter: #24     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3656:8)
flutter: #25     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #26     ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
flutter: #27     new List.from (dart:core-patch/array_patch.dart:47:19)
flutter: #28     Iterable.toList (dart:core/iterable.dart:400:5)
flutter: #29     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3537:8)
flutter: #30     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #31     Iterable.single (dart:core/iterable.dart:554:13)
flutter: #32     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2582:7)
flutter: #33     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1084:16)
flutter: #34     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:406:21)
flutter: #35     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:797:13)
flutter: #36     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #37     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1109:15)
flutter: #38     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1048:9)
flutter: #39     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:857:7)
flutter: #48     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
flutter: #49     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
flutter: #50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
flutter: (elided 8 frames from package dart:async and package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RangeError (index): Invalid value: Valid value range is empty: 0
flutter: Another exception was thrown: Bad state: Future already completed

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 776 pos 14: '!_firstFrameCompleter.isCompleted': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:776:14)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1109:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1048:9)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:857:7)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by scheduler library ═════════════════════════════════════════════════
'package:flutter/src/widgets/binding.dart': Failed assertion: line 768 pos 12: '!debugBuildingDirtyElements': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```                                            
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.14.6 at /Users/username/flutter
    • Framework revision fabeb2a16f (5 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[!] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • F0581480-1342-43FC-BB21-1CBFEF320617 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.106
    • Web Server        • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-03-04 15:24
Works as intended with Android, I can see the exception only with iOS

**Comment by goderbauer** [comment] 2020-03-04 23:27
From the stack trace it looks like it is crashing when generating the semantics tree for this.

**Comment by wdjwxh** [comment] 2020-03-10 12:11
same error...

**Comment by tomoya55** [comment] 2020-05-13 13:08
I got the same error. Nesting WidgetSpan with another TextSpan nor extracting WidgetSpan out of its parent to put directly under the top RichText did neither work...

**Comment by hienlh** [comment] 2020-06-22 08:13
Same, please fix it.

**Comment by zhengbomo** [comment] 2020-07-08 07:23
════════ Exception caught by scheduler library ═════════════════════════════════
The following RangeError was thrown during a scheduler callback:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack
#0      List.[]  (dart:core-patch/growable_array.dart:146:60)
#1      List.elementAt  (dart:core-patch/growable_array.dart:355:16)
#2      RenderParagraph.assembleSemanticsNode 
package:flutter/…/rendering/paragraph.dart:909
#3      _SwitchableSemanticsFragment.compileChildren 
package:flutter/…/rendering/object.dart:3684
#4      _SyncIterator.moveNext  (dart:core-patch/core_patch.dart:146:23)
...
════════════════════════════════════════════════════════════════════════════════

**Comment by pedromassangoncode** [comment] 2020-07-15 09:37
I was able to reproduce on `1.20.0-7.1.pre`.

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101,
    locale en-AO)
    • Flutter version 1.20.0-7.1.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision 7736f3bc90 (4 days ago), 2020-07-10 16:33:05
      -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)
 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Andr
      oid Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google
      Chrome.app/Contents/MacOS/google-chrome-unsafe

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Andr
      oid Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    •
      Android 9 (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     •
      Mac OS X 10.15.5 19F101
    • Web Server (web)             • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                 • chrome        • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```
</details>

**Comment by zhengbomo** [comment] 2020-08-12 01:52
proplem still on 1.20.1

```
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (6 days ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0
```

@pedromassangocode

**Comment by EaglesChen** [comment] 2020-08-15 09:53
same with me

```
                  TextSpan(
                    children: [
                      TextSpan(text: state.desc),
                      WidgetSpan(
                          child: SizedBox(
                        width: Adapt.dp(4),
                      )),
                      TextSpan(
                          text: '点击查看奖品详情',
                          recognizer: TapGestureRecognizer()
                            ..onTap = () => dispatch(
                                ChatGroupLotteryActionCreator.onViewInfo()),
                          style: TextStyle(color: XSXColors.dark_blue)),
                      WidgetSpan(
                          child: Icon(
                        Icons.arrow_forward_ios,
                        color: XSXColors.dark_blue,
                        size: Adapt.dp(13),
                      ))
                    ],
                    style: TextStyle(
                      fontSize: Adapt.dp(12),
                      color: XSXColors.text_content,
                    ),
```

**Comment by zzterrozz** [comment] 2020-09-02 14:56
Still facing the same issue. Anyone found a solution or alternative please ?

**Comment by IoanaAlexandru** [comment] 2020-09-03 21:05
This works for me on Android but fails with the same error when trying to run a test, and on iOS.

**Comment by bayun2** [comment] 2020-10-15 09:53
`
RichText(
                    overflow: TextOverflow.ellipsis,
                    maxLines: 1,
                    text: TextSpan(
                      style: TextStyle(
                        fontSize: 16.0,
                        height: 22.0 / 16.0,
                      ),
                      children: [
                        TextSpan(
                          text:
                              '12334512334512334512334512334511233451233451233451233451233451123345123345123345123345123345112334512334512334512334512334511233451233451233451233451233451',
                          style: TextStyle(color: Colors.red),
                        ),
                        WidgetSpan(
                          alignment: PlaceholderAlignment.middle,
                          child: GestureDetector(
                              behavior: HitTestBehavior.translucent,
                              onTap: () {
                                LBChannel.getNativePage(
                                    'lb://page/stock/detail?id=123');
                              },
                              child: Padding(
                                padding: EdgeInsets.only(right: 2),
                                child: Icon(
                                  Iconfont.stock,
                                  size: 16,
                                ),
                              )),
                        ),
                        TextSpan(
                          text: '123345',
                          style: TextStyle(color: Colors.red),
                        )
                      ],
                    ),
                  )
`
If WidgetSpan overflow will cause the error

**Comment by stuz5000** [comment] 2020-11-10 06:37
> This works for me on Android but fails with the same error when trying to run a test, and on iOS.

Similar issue on web: https://github.com/flutter/flutter/issues/70159

**Comment by guopeng1994** [comment] 2020-11-28 03:52
same error on **Stable version - 1.22.4**

**Comment by andrea689** [comment] 2021-01-18 11:31
a workaround is to wrap `RichText` in `ExcludeSemantics`:

```dart
ExcludeSemantics(
  excluding: true,
  child: RichText( ... ),
),
```

**Comment by jason-simmons** [comment] 2021-02-17 23:41
Duplicate of https://github.com/flutter/flutter/issues/69787

**Closed by jason-simmons** 2021-02-17 23:41 UTC
Labels: a: accessibility, f: gestures, found in release: 1.20, framework, has reproducible steps, platform-ios, severe: crash
