### ISSUE TITLE
Setting .exe version from pubspec.yaml version value

### ISSUE THREAD

**Issue by PiN73** [flutter/flutter#79838] opened 2021-04-06 04:00 UTC
## Use case

I'm compiling my app for Windows and want to set its version (view: Right-click on .exe file -> Properties -> Details tab).

Currently it can be changed manually in windows/runner/Runner.rc:
```
#define VERSION_AS_NUMBER 1,0,0
...
#define VERSION_AS_STRING "1.0.0"
```

## Proposal

It would be great if `version` from `pubspec.yaml` used by default. For example, part before `+` can go to _File version_, and the whole value can go to _Product version_.

Also it would be useful to be able to explicitly set this values when compiling, maybe through command line flags

**Comment by TahaTesser** [comment] 2021-04-06 13:34
Hi @PiN73 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/73652
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-06 13:34 UTC
Labels: in triage
