### ISSUE TITLE
Error running pod install; Error launching application on iPhone 11; Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies

### ISSUE THREAD

**Issue by Alvaro-99** [flutter/flutter#65210] opened 2020-09-03 23:36 UTC
## Steps to Reproduce

Hello, I just started coding and I am very new to this. I am using flutter on Visual Studio Code. Every time I "start debugging" I get the following message: "Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies. To update the CocoaPods specs, run: pod repo update; Error running pod install; Error launching application on iPhone 11. Exited (sigterm)". I have run "pod repo update" on my terminal and I get "Updating spec repo `trunk`", and it still doesn't work. I have also run "flutter doctor -v" and everything looks in place. I have also run "flutter clean" but it still doesn't work (I get the same errors as explained above). Attached you may see pictures of the debugging process as well as of the terminal when I run these commands. I would really appreciate your help on this.

<img width="1552" alt="Screen Shot 2020-09-03 at 10 33 53 AM" src="https://user-images.githubusercontent.com/70729292/92183525-b1efd000-ee1c-11ea-9d8e-ca60bdb3a51b.png">
<img width="1552" alt="Screen Shot 2020-09-03 at 10 34 04 AM" src="https://user-images.githubusercontent.com/70729292/92183527-b320fd00-ee1c-11ea-9056-10dbb80e4e32.png">
<img width="1552" alt="Screen Shot 2020-09-03 at 10 34 06 AM" src="https://user-images.githubusercontent.com/70729292/92183531-b3b99380-ee1c-11ea-8aea-b61b1707200b.png">
<img width="1552" alt="Screen Shot 2020-09-03 at 10 34 49 AM" src="https://user-images.githubusercontent.com/70729292/92183533-b6b48400-ee1c-11ea-8c9e-56db8aa94904.png">
<img width="1552" alt="Screen Shot 2020-09-03 at 10 34 57 AM" src="https://user-images.githubusercontent.com/70729292/92183536-b7e5b100-ee1c-11ea-937e-bf229ec2b624.png">
<img width="1552" alt="Screen Shot 2020-09-03 at 10 35 19 AM" src="https://user-images.githubusercontent.com/70729292/92183538-b87e4780-ee1c-11ea-85ee-da25de354406.png">

## Logs

```
```

```
```

**Comment by TahaTesser** [comment] 2020-09-04 07:46
Hi @Alvaro-99 
Please execute `pod repo update` then execute `pod update` from` ios` folder of your project and then run your app using `flutter run --verbose`

If the problem perists after this,  Can you please provide your `flutter doctor -v` your `flutter run --verbose`, your `pod --version` and a complete reproducible minimal code sample

Thank you

**Comment by TahaTesser** [comment] 2020-10-14 14:23
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 14:23 UTC
Labels: in triage

**Comment by pierre-gancel** [comment] 2020-11-03 08:15
Hi,
I also have the same issue on macos running desktop app,
@TahaTesser I followed your commands but the problem is still here : 
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
           To update the CocoaPods specs, run:
             pod repo update

`[        ] "flutter run" took 41,349ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:608:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1072:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)`

**Comment by TahaTesser** [comment] 2020-11-03 09:24
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by pierre-gancel** [comment] 2020-11-03 10:56
just before I file another one,
I can still run on mac desktop on other projects, so I wonder if wouldn't the yaml be more useful ?

**Comment by anilthedeveoper** [comment] 2021-01-28 11:58
<img width="841" alt="Screenshot 2021-01-28 at 17 18 54" src="https://user-images.githubusercontent.com/64885578/106134839-1bd29280-618d-11eb-8ed8-8909dbd333cc.png">

To fix this open **Runner.xcworkspace** from ios directory and change Deployment Target to something that is latest e.g. `iOS 14.0`. This is happening because some of the dependencies are not compatible with outdated iOS version (which Flutter generates, usually `iOS 8.0` or `iOS 9.0`)

After that run `pod repo update` and then run your project
