### ISSUE TITLE
TextField’s border is cut if placed inside a SingleChildScrollView

### ISSUE THREAD

**Issue by denis-evteev** [flutter/flutter#61434] opened 2020-07-14 09:23 UTC
When a `TextField` is the bottommost widget in a `SingleChildScrollView`, its bottom border appears to be thinner than usual. Probably a rendering issue.

An unwrapped `TextField` looks like this:

<img width="347" alt="Screenshot 2020-07-14 at 12 11 11" src="https://user-images.githubusercontent.com/3929460/87407740-3bc4af00-c5cb-11ea-9e02-47a445f73930.png">

A `TextField` inside a `SingleChildScrollView` looks like this:

<img width="347" alt="Screenshot 2020-07-14 at 12 11 20" src="https://user-images.githubusercontent.com/3929460/87407786-4d0dbb80-c5cb-11ea-9955-f47e6210dfdc.png">

If the border width is less than `1.0`, then it becomes almost invisible inside the scroll view.

Here’s a sample code to reproduce the issue:
```
import 'package:flutter/material.dart';

void main() {
  runApp(SampleWidget());
}

class SampleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: (_, __) => Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(25.0),
            child: SingleChildScrollView(
              child: TextField(),
            ),
          ),
        ),
      ),
    );
  }
}
```

<details><summary><code>flutter doctor -v</code></summary>
<pre>
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/denis/Projects/vendor/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/denis/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • 6FCA75B1-A34C-45EC-BF25-BA36CC5DA55D • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 1 category.
</pre>
</details>

**Comment by TahaTesser** [comment] 2020-07-14 11:21
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (3 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • SM M305F (mobile)      • 32003c30dc19668f                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.5.1
    • iPhone 11 (mobile)     • C56E212F-BE8E-4766-8610-12CFADC797F0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.5 19F101
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```

</details>

@denis-evteev 
Thanks for catching this

**Comment by xu-baolin** [comment] 2020-07-23 04:00
@denis-evteev This is an anti-aliasing effect. If you don’t want it, please configure SingleChildScrollView(child: TextField(), clipBehavior: Clip.none,), Hope it helps you^_^

**Comment by denis-evteev** [comment] 2020-07-23 07:45
@xu-baolin The `SingleChildScrollView` widget does not have a `clipBehavior` property.

**Comment by xu-baolin** [comment] 2020-07-23 08:05
![image](https://user-images.githubusercontent.com/61075224/88264339-2c95dd80-ccfe-11ea-9e11-a9a5268fd062.png)
(Channel master, 1.21.0-2.0.pre.83

**Comment by denis-evteev** [comment] 2020-07-23 09:14
Well, you’re referring to a property that doesn’t yet exist in the `stable` channel, so unfortunately your suggestion won’t work there. Nonetheless, it’s great to know that the issue has been addressed and resolved in more recent flutter releases.

**Comment by xu-baolin** [comment] 2020-07-23 09:41
> Well, you’re referring to a property that doesn’t yet exist in the `stable` channel, so unfortunately your suggestion won’t work there. Nonetheless, it’s great to know that the issue has been addressed and resolved in more recent flutter releases.

As a workaround, you can hack your source code, it is easy.

**Comment by denis-evteev** [comment] 2020-07-23 09:58
I’m not sure what you mean by hacking my source code, but I don’t think that implementing a hack-like solution is a good idea anyway.

A simple workaround that I already implemented was to wrap the `TextField` in a `Padding` widget and specify some bottom padding. Once the `clipBehavior` property that you pointed to becomes available in the `stable` channel, I’ll switch to using that instead.

**Comment by Piinks** [comment] 2020-07-24 17:13
It sounds like this is fixed on master, so I am going to close this issue. If you feel that we have not addressed the issue, let us know and we will re-open it! 

#14288 is a long-standing issue around anti-aliasing, there is a lot of discussion and work arounds for various cases there as well! :)

**Comment by xu-baolin** [comment] 2020-08-06 03:12
After further investigation, I think this may be a bug related to ClipRect. Here, the size of _RenderSingleChildViewport is the same as the size of the child. According to the code-logic(flutter/packages/flutter/lib/src/widgets/single_child_scroll_view.dart:575) will go to `pushClipRect`, after clip, the TextField's underline will be cut no matter the clip behaver is antiAlias or hard-edge.

```
  bool _shouldClipAtPaintOffset(Offset paintOffset) {
    assert(child != null);
    return paintOffset < Offset.zero || !(Offset.zero & size).contains((paintOffset & child.size).bottomRight);
  }
```
Also, ask a question, If the size of the parent is the same as the size of the child. Why should it be cut? 
(Rect.contains's comment: `Rectangles include their top and left edges but exclude their bottom and right edges`)
@liyuqian Looking forward to your answer，thanks.

**Comment by xu-baolin** [comment] 2020-08-06 03:55
> After further investigation, I think this may be a bug related to ClipRect. Here, the size of _RenderSingleChildViewport is the same as the size of the child. According to the code-logic(flutter/packages/flutter/lib/src/widgets/single_child_scroll_view.dart:575) will go to `pushClipRect`, after clip, the TextField's underline will be cut no matter the clip behaver is antiAlias or hard-edge.
> 
> ```
>   bool _shouldClipAtPaintOffset(Offset paintOffset) {
>     assert(child != null);
>     return paintOffset < Offset.zero || !(Offset.zero & size).contains((paintOffset & child.size).bottomRight);
>   }
> ```
> 
> Also, ask a question, If the size of the parent is the same as the size of the child. Why should it be cut?
> (Rect.contains's comment: `Rectangles include their top and left edges but exclude their bottom and right edges`)
> @liyuqian Looking forward to your answer，thanks.

The second question I think it is a bug that has been around for a long time, I will fix it.

**Comment by Piinks** [comment] 2020-08-06 22:34
Thanks for investigating @xu-baolin and opening a pull request! I'll re-open this issue.

**Comment by xu-baolin** [comment] 2020-08-07 00:12
> Thanks for investigating @xu-baolin and opening a pull request! I'll re-open this issue.

Hi, thank you for reopening this issue.
Although #63054 will cause unnecessary clipRect, I think this is not the root cause of this problem, because the clipRect is equaled to the child's size not overflow, so the child's underline should not be cut. This is why I did not link #63054 to the issue.
In summary, here are some things that need to be figured out. ^-^

**Comment by xu-baolin** [comment] 2020-08-07 04:00
![image](https://user-images.githubusercontent.com/61075224/89607431-22024900-d8a5-11ea-88cf-95101ea10bbc.png)
I found the line be cut 1.5px here, @liyuqian who will affect this parameter?

**Comment by liyuqian** [comment] 2020-08-07 04:27
#63054 is definitely something we need to fix. Thank you @xu-baolin for finding it!

The 0.5 pixel comes from Skia's [hairline logic]. Flutter [sets 0 stroke width in the border paint][0-border] used by the underline to make that underline a hairline. The hairline always has 1-device-pixel regardless of the transformation and it's impossible for Flutter to figure out exactly which pixel it may touch on the Dart level. Due to anti-aliasing, such 1-device-pixel line may actually touch 2 pixels (e.g., drawing 0.4, 0.6 in two pixels to approximate a solid pixel at a fractional 0.4 offset).

As hairline's actual boundary depends on transformations and a `Transform` can be added on top of a widget at any time, it seems impossible for a widget to calculate its paint boundary correctly if there are hairlines. Therefore correctly clipping a widget with hairlines seems to be mission impossible. CC @Hixie @reed-at-google for thoughts. 

[hairline logic]: https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/include/core/SkPaint.h;l=325?q=hairline%20file:SkPaint.h&ss=chromium%2Fchromium%2Fsrc:third_party%2Fskia%2F
[0-border]: https://github.com/flutter/flutter/blob/77b4505c8014330fba2f2706c658a64bc5d1891b/packages/flutter/lib/src/painting/borders.dart#L186

**Comment by mikerreed** [comment] 2020-08-07 13:44
Agreed -- can't clip to a hairline

**Closed** 2020-08-10 17:46 UTC
Labels: a: quality, a: text input, f: material design, found in release: 1.17, found in release: 1.20, framework, has reproducible steps

**Comment by xu-baolin** [comment] 2020-08-11 09:06
@liyuqian Hi, I want to ask a question, how can I capture a special frame SkPicture by flutter screenshot --type=skia --observatory-uri, I found it only captures the 1st frame of the APP.

**Comment by liyuqian** [comment] 2020-08-11 21:19
@xu-baolin It should capture the current frame of the app instead of the 1st frame of
the app. In what version of Flutter did you find this problem? I'm
currently having difficulty in visualizing the skp due to
https://bugs.chromium.org/p/skia/issues/detail?id=10588

**Comment by xu-baolin** [comment] 2020-08-12 01:15
> @xu-baolin It should capture the current frame of the app instead of the 1st frame of
> the app. In what version of Flutter did you find this problem? I'm
> currently having difficulty in visualizing the skp due to
> https://bugs.chromium.org/p/skia/issues/detail?id=10588

I made a mistake, it did capture the current frame. My version is Channel unknown, 1.21.0-8.0.pre.84, I don't know why is channel unknown, I think it should be channel master. I meet the seam issue last week #62845, but it was repaired quickly.

Now I have an issue in my project, When I swipe the screen, the screen is a little bit blurry transitory, so is there any way to capture the frames during a period for debug?

**Comment by xu-baolin** [comment] 2020-08-12 02:00
@liyuqian  I switch to up-to-date master-branch, it works well.
```
PS F:\flutter_dev\src_new\flutter> flutter screenshot --type=skia --observatory-uri=http://127.0.0.1:49512/h8BUvMyqB7g=/#/vm-connect
No supported devices connected.
The following devices were found, but are not supported by this project:
PDCM00 (mobile)   • 9LL7VO8XUOIN75ZH • android-arm64 • Android 10 (API 29)
Windows (desktop) • windows          • windows-x64   • Microsoft Windows [Version 10.0.17763.615]
If you would like your app to run on android or windows, consider running `flutter create .` to generate projects for
these platforms.

Screenshot written to flutter_08.skp (300kB).
PS F:\flutter_dev\src_new\flutter> flutter doctor -v
[√] Flutter (Channel master, 1.21.0-8.0.pre.172, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.21.0-8.0.pre.172 at F:\flutter_dev\src_new\flutter
    • Framework revision 8dcb4c338a (2 hours ago), 2020-08-11 17:29:35 -0700
    • Engine revision 06458d2f6c
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30330.147
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (2 available)
    • PDCM00 (mobile)   • 9LL7VO8XUOIN75ZH • android-arm64 • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64   • Microsoft Windows [Version 10.0.17763.615]

• No issues found!
PS F:\flutter_dev\src_new\flutter>
```

**Comment by liyuqian** [comment] 2020-08-12 02:16
Thanks for bringing https://github.com/flutter/flutter/issues/62845 to my attention! It indeed seems to be the root cause and I've closed the Skia bug accordingly.

https://api.flutter.dev/flutter/scheduler/timeDilation.html might help you capture a frame in the middle of an animation,
