### ISSUE TITLE
ListTile onTap handler swapped with other list (ListTile) onTap handler

### ISSUE THREAD

**Issue by jazarja** [flutter/flutter#27603] opened 2019-02-06 16:59 UTC
![Demo](https://i.stack.imgur.com/jt0ay.gif)
## Steps to Reproduce

1. Create two list, wire them with BottomNavigationBar 
2. Define ontap handler for each list.
3. Open the first list, observe the ontap handler that being served.
4. Open the second list, observe the ontap handler that being served.

Sample source code: https://github.com/jazarja/flutter_app

**Comment by zoechi** [comment] 2019-02-07 13:38
Sounds like you need to add unique keys to the ListTiles
https://www.youtube.com/watch?v=kn0EOS-ZiIc

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by jazarja** [comment] 2019-02-12 15:47
I add keys with GlobalKey() function, but the issue still intact. Any other idea?

Here is my changes:
```
         if (snapshot.hasData) {
              return ListView.builder(
                key: GlobalKey(),
                itemCount: snapshot.data.length,
                itemBuilder: (context, index) {
                  return ListTile(
                      key: GlobalKey(),
                      title: Text('${snapshot.data[index].name}'),`
```

**Comment by zoechi** [comment] 2019-02-12 16:12
```
 key: GlobalKey(),
```
does not really do anything. It just creates a new key every time build is run for every `ListTile()`

I'd suggest you ask on StackOverflow and if it actually turns out to be a Flutter bug, create an issue.

**Comment by jazarja** [comment] 2019-02-12 16:47
I have another variation that using plain BottomNavigationBar (no animation, etc) which works perfectly without using key.

**Comment by zoechi** [comment] 2019-02-13 10:23
Yes it's specific to the animation. 
It's not that the `onTap` handler of the wrong `ListTile` is called 
but that the taps are handled only by the `PersonList` no matter which tab is selected.

**Comment by iapicca** [comment] 2020-07-29 08:51
Hi @jazarja 
From what I can see, the issue is related to the 3rd party plugin [fluttertoast](https://pub.dev/packages/fluttertoast) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/PonnamKarthik/FlutterToast/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-29 08:51 UTC
Labels: P4, framework
