### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by pampsdeep** [flutter/flutter#72048] opened 2020-12-10 04:23 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=AYIFMNDABIS859S4 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#4      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:36:51)
#5      FlutterProject._readManifest (package:flutter_tools/src/project.dart:218:34)
#6      FlutterProjectFactory.fromDirectory.<anonymous closure> (package:flutter_tools/src/project.dart:48:55)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#8      FlutterProjectFactory.fromDirectory (package:flutter_tools/src/project.dart:47:21)
#9      FlutterProject.current (package:flutter_tools/src/project.dart:87:61)
#10     FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1001:81)
#11     RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:351:21)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:933:11)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _runZoned (dart:async/zone.dart:1630:10)
#19     runZoned (dart:async/zone.dart:1550:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
```
```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-AU)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\pamps\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\pamps\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] VS Code, 64-bit edition (version 1.46.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Lenovo A7010a48 (mobile) • AYIFMNDABIS859S4 • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'E:\Work_Precise\Mobile\precise_wms\pubspec.yaml'

**Comment by pedromassangocode** [comment] 2020-12-10 08:08
Closing as a duplicate of https://github.com/flutter/flutter/issues/65021.

See https://github.com/flutter/flutter/issues/65021#issuecomment-685095919 for a workaround for this issue.
Thank you

**Closed by pedromassangocode** 2020-12-10 08:08 UTC
