### ISSUE TITLE
CupertinoTabScaffold TextField not focusable after iOS Back Swipe

### ISSUE THREAD

**Issue by b3nni97** [flutter/flutter#92053] opened 2021-10-19 00:53 UTC
Example: https://gist.github.com/b3nni97/445b6be519188a84c3ac12fbce67bb24

1. Click on Textfield - Works
2. Click on "here"
3. Click on Textfield - Works
4. Swipe back (only way to reproduce with Back Button it would work)
5. Click on Textfield - NOT WORKING

[✓] Flutter (Channel master, 2.6.0-12.0.pre.380, on macOS 11.5.2 20G95 darwin-arm, locale de-DE)
    • Flutter version 2.6.0-12.0.pre.380 at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 686a1c27b5 (5 hours ago), 2021-10-19 04:41:33 +0900
    • Engine revision faa45f497f
    • Dart version 2.15.0 (build 2.15.0-226.0.dev)

**Comment by caseycrogers** [comment] 2021-10-21 21:17
@b3nni97 I checked and this doesn't appear to be related to https://github.com/flutter/flutter/pull/90097.

1. `git checkout 76b3c6758cb323727c26aad9382eca9fa53386e9` <----- sha hash of #90097 
2. Follow repro steps you posted above
3. Note that bug is not present

**Comment by caseycrogers** [comment] 2021-10-21 22:26
> @caseycrogers Just to clarify the bug is without PR #90097 also still present or is the bug no longer there? If the bug does not appear there anymore would mean it could be because of that.
> 
> Because you wrote "is not present".
> 
> I had suspected this PR because I develop on the master branch and I made an pull there 2-3 weeks ago and since then the bug has arisen. In a quick search I found only this PR in the time frame which could be releated.

To clarify: I performed your repro with the latest from master and was able to reproduce the broken behavior. I then checked out the commit where I first merged https://github.com/flutter/flutter/pull/90097 and re-ran the repro steps. I could not recreate the bug. This should mean that the bug was introduced some time after https://github.com/flutter/flutter/pull/90097.

**Comment by LongCatIsLooong** [comment] 2021-11-04 17:38
This seems to have the same root cause as https://github.com/flutter/flutter/issues/92693. Closing as a duplicate of #92693.

**Closed by LongCatIsLooong** 2021-11-04 17:38 UTC
Labels: severe: regression, framework, f: cupertino, f: routes, has reproducible steps, found in release: 2.6
