### ISSUE TITLE
[Desktop] PointerScrollEvent; Not possible to distinguish between Mouse and Trackpad

### ISSUE THREAD

**Issue by ltOgt** [flutter/flutter#88175] opened 2021-08-13 15:16 UTC
`PointerScrollEvent.kind` (`PointerDeviceKind`) can not distinguish between `mouse` and `trackpad`.

The expected scroll behavior of trackpad and mouse might differ though.
The following behavior might be a matter of taste, but does not seem to be implementable with flutter in any case:

Scrolling a mouse wheel downwards should scroll content up / viewport down.
Scrolling a trackpad downwards should scroll content down / viewport up.

![2021081317:07:33_screenshot_sel](https://user-images.githubusercontent.com/24209580/129378229-583250d8-488e-466e-a31e-7796285e75bc.png)

Since the device kind can not be differentiated, the `scrollOffset` can only be applied in the same direction for both input types.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Trackpad Scroll Events on each Frame',
      theme: ThemeData.dark(),
      home: Scaffold(
        body: Example(),
      ),
    ),
  );
}

class Example extends StatelessWidget {
  const Example({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return NotificationListener<ScrollNotification>(
      onNotification: (scrollNotification) {
        if (event is PointerScrollEvent) {
           // Will print "flutter: PointerDeviceKind.mouse" for both mouse and trackpad
           // event.scrollOffset can only be applied in the same direction
           print(event.kind);
        }
      },
      child: SingleChildScrollView(
        child: Column(
          children: [
            for (int i = 0; i < 100; i++)
              Container(
                // width: 100,
                height: 100,
                color: (i % 2 == 0) ? Colors.blue : Colors.black,
                child: Center(
                  child: Text(
                    "$i",
                  ),
                ),
              ),
          ],
        ),
      ),
    );
  }
}
```

It might well be that this is not possible because the system does not omit different events for mouse and trackpad

**Comment by stuartmorgan** [comment] 2021-08-13 15:20
Duplicate of https://github.com/flutter/flutter/issues/23604

**Closed by stuartmorgan** 2021-08-13 15:20 UTC
