### ISSUE TITLE
Base Vertex Instance Drawing is only supported on MTLGPUFamilyApple3 and later when FLTEnableImpeller is set to True

### ISSUE THREAD

**Issue by ingmferrer** [flutter/flutter#110617] opened 2022-08-30 21:12 UTC
## Steps to Reproduce

1. Enable FLTEnableImpeller flag on Info.plist. [See instructions](https://github.com/flutter/flutter/wiki/Impeller)
2. Execute `flutter run`

**Expected results:**
Be able to run the app

**Actual results:**
App crashed

<details>
  <summary>Logs</summary>

```
MTLValidateFeatureSupport:4854: failed assertion `Base Vertex Instance Drawing is only supported on MTLGPUFamilyApple3 and later.'
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/mac/Library/Developer/Xcode/DerivedData/Runner-babvbpjxjlxgspapaadcebujfanp/Build/Products/Debug-development-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMTLCapture.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/mac/Library/Developer/Xcode/DerivedData/Runner-babvbpjxjlxgspapaadcebujfanp/Build/Products/Debug-development-iphonesimulator
MTLValidateFeatureSupport:4854: failed assertion `Base Vertex Instance Drawing is only supported on MTLGPUFamilyApple3 and later.'
CoreSimulator 802.6 - Device: iPhone 13 Pro Max (BD27B34D-95E5-4BA1-B0B4-CD375F0F63DE) - Runtime: iOS 15.4 (19E240) - DeviceType: iPhone 13 Pro Max
```

```
libsystem_kernel.dylib`__pthread_kill:
    0x7fff6fab1004 <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x7fff6fab1009 <+5>:  movq   %rcx, %r10
    0x7fff6fab100c <+8>:  syscall 
->  0x7fff6fab100e <+10>: jae    0x7fff6fab1018            ; <+20>
    0x7fff6fab1010 <+12>: movq   %rax, %rdi
    0x7fff6fab1013 <+15>: jmp    0x7fff6faab1c5            ; cerror_nocancel
    0x7fff6fab1018 <+20>: retq   
    0x7fff6fab1019 <+21>: nop    
    0x7fff6fab101a <+22>: nop    
    0x7fff6fab101b <+23>: nop    
```

```
Analyzing flutter_app...                                           
No issues found! (ran in 4.1s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.3.1 21E258 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2022-08-31 09:44
Hi @ingmferrer, I tried running a new Flutter project with enabled `FLTEnableImpeller`, it doesn't crash.
My device info: `Iphone 7 (iOS 15.5, Chipset Apple A10)`. 
I also run on `iPhone 13 Pro Max` simulator. It doesn't crash but the application is only displaying pure color on `stable` channel but it displays normally when running on `master` channel (see in demo)

<details>
<summary>Demo (stable)</summary>

| Iphone 7 | iPhone 13 Pro Max (simulator) |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/187645857-7f19d267-1a01-4a92-878d-21f30049e859.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/187647753-c394f75b-6dc8-4b74-bd6b-e43d5f5894c2.png">

</details>

<details>
<summary>Demo (master)</summary>

<img width="600" src="https://user-images.githubusercontent.com/104349824/187649462-d95cf7f4-f14c-47c7-a98a-4e91eb233f69.png">


</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-x64, locale en-EE)
    • Flutter version 3.3.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (28 hours ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2592, on macOS 12.5 21G72 darwin-x64, locale en-EE)
    • Flutter version 3.1.0-0.0.pre.2592 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 069f504297 (3 hours ago), 2022-08-30 18:20:09 -0700
    • Engine revision 0ef08a8525
    • Dart version 2.19.0 (build 2.19.0-152.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

It looks like you're running the app on a simulator, right? I see there was an issue that has merged recently #104743 about supporting iOS simulator (Impeller). Could you try reproducing this issue on the latest Flutter master channel?

**Comment by ingmferrer** [comment] 2022-08-31 10:27
Hello @huycozy, this is interesting because I switched to the master channel and the app works on the simulator!

However, on the stable channel, xcode outputs the same logs (see above) and running the app from Android Studio gives me a full black screen without any console errors.

<details>
<summary>master channel</summary>

```
Flutter is already up to date on channel master
Flutter 3.1.0-0.0.pre.2592 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 069f504297 (9 hours ago) • 2022-08-30 18:20:09 -0700
Engine • revision 0ef08a8525
Tools • Dart 2.19.0 (build 2.19.0-152.0.dev) • DevTools 2.16.0
```

</details>

<details>
<summary>stable channel</summary>

```
Flutter is already up to date on channel stable
Flutter 3.3.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffccd96b62 (34 hours ago) • 2022-08-29 17:28:57 -0700
Engine • revision 5e9e0e0aa8
Tools • Dart 2.18.0 • DevTools 2.15.0
```

</details>

Let me know if I can do anything else to help.

**Comment by huycozy** [comment] 2022-08-31 15:23
@ingmferrer 
Looks like the issue comes from XCode than Flutter itself.  
Could you try switching to the master channel and running application with XCode to see if there are the same logs there?

**Comment by ingmferrer** [comment] 2022-08-31 15:50
No errors running the app with XCode and the master channel. Whatever the problem is, it is related to stable channel.

I understand that Impeller is a preview for iOS, so I don't expect this to be resolved anytime soon, but since the [wiki](https://github.com/flutter/flutter/wiki/Impeller) mentions the stable channel to try this feature then I think this is worth looking at.

**Comment by huycozy** [comment] 2022-08-31 16:34
@ingmferrer
Yes, it's just a preview on iOS currently. Given what you've tested, I feel safe ending the issue from here. 
Closing as fixed on the master channel. The fix should land on the stable channel in future releases. Thanks for your contribution.

**Closed by huycozy** 2022-08-31 16:34 UTC
Labels: in triage
