### ISSUE TITLE
App crashing at startup on Android 5.1

### ISSUE THREAD

**Issue by kssujithcj** [flutter/flutter#52385] opened 2020-03-11 05:56 UTC
## Description:
This issue is happening in our production app as well which has more than 1 million users.
In this process of debugging the production app, we created a sample project which is also crashing on the Emulator. We were able to reproduce this issue on Android 5.1, the following are the details regarding the issue. 

## Steps to Reproduce

1. Run `flutter create crashcheck`.
2. `cd crashcheck`
3. `flutter run`

**Expected results:** App launches

**Actual results:** Crashing at the startup

<details>
  <summary>Logcat</summary>

```
W/linker  ( 4971): libflutter.so: unused DT entry: type 0x6ffffef5 arg 0x39830
W/linker  ( 4971): libflutter.so: unused DT entry: type 0x6ffffffe arg 0x397d0
W/linker  ( 4971): libflutter.so: unused DT entry: type 0x6fffffff arg 0x3
F/libc    ( 4971): Fatal signal 4 (SIGILL), code 1, fault addr 0xa4c9379a in tid 4971 (mple.crashcheck)
I/ResourceExtractor( 4971): Resource version mismatch res_timestamp-1-1583904940533
I/DEBUG   (  647): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  647): Build fingerprint: 'Android/sdk_google_phone_armv7/generic:5.1.1/LMY48X/5525941:userdebug/test-keys'
I/DEBUG   (  647): Revision: '0'
I/DEBUG   (  647): ABI: 'arm'
I/DEBUG   (  647): pid: 4971, tid: 4971, name: mple.crashcheck  >>> com.example.crashcheck <<<
I/DEBUG   (  647): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xa4c9379a
I/DEBUG   (  647):     r0 a51d644c  r1 00000002  r2 00000000  r3 a3cb70c4
I/DEBUG   (  647):     r4 a51d6448  r5 a51d6370  r6 b6e533ac  r7 b6f7c03a
I/DEBUG   (  647):     r8 000000a9  r9 b6f80714  sl 00000001  fp a51d25a8
I/DEBUG   (  647):     ip a51d4194  sp beecacf0  lr a4c9c65d  pc a4c9379a  cpsr 60000170
I/DEBUG   (  647): 
I/DEBUG   (  647): backtrace:
I/DEBUG   (  647):     #00 pc 000dd79a  /data/app/com.example.crashcheck-2/lib/arm/libflutter.so
I/DEBUG   (  647):     #01 pc 000de36d  /data/app/com.example.crashcheck-2/lib/arm/libflutter.so
I/DEBUG   (  647):     #02 pc 000de20b  /data/app/com.example.crashcheck-2/lib/arm/libflutter.so
I/DEBUG   (  647):     #03 pc 000dea85  /data/app/com.example.crashcheck-2/lib/arm/libflutter.so
I/DEBUG   (  647):     #04 pc 000015bd  /system/bin/linker (__dl__ZN6soinfo12CallFunctionEPKcPFvvE+44)
I/DEBUG   (  647):     #05 pc 00001691  /system/bin/linker (__dl__ZN6soinfo9CallArrayEPKcPPFvvEjb+140)
I/DEBUG   (  647):     #06 pc 00001867  /system/bin/linker (__dl__ZN6soinfo16CallConstructorsEv+142)
I/DEBUG   (  647):     #07 pc 00003237  /system/bin/linker (__dl__Z9do_dlopenPKciPK17android_dlextinfo+194)
I/DEBUG   (  647):     #08 pc 00000f1d  /system/bin/linker (__dl__ZL10dlopen_extPKciPK17android_dlextinfo+24)
I/DEBUG   (  647):     #09 pc 001d274f  /system/lib/libart.so (art::JavaVMExt::LoadNativeLibrary(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, art::Handle<art::mirror::ClassLoader>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+506)
I/DEBUG   (  647):     #10 pc 001f77a1  /system/lib/libart.so (art::Runtime_nativeLoad(_JNIEnv*, _jclass*, _jstring*, _jobject*, _jstring*)+528)
I/DEBUG   (  647):     #11 pc 0007980d  /data/dalvik-cache/arm/system@framework@boot.oat
W/ActivityManager(  988):   Force finishing activity 1 com.example.crashcheck/.MainActivity
I/DEBUG   (  647): 
I/DEBUG   (  647): Tombstone written to: /data/tombstones/tombstone_06
I/Zygote  (  653): Process 4971 exited due to signal (4)
```
</details>

<details>
 <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN.utf8)
    • Flutter version 1.12.13+hotfix.8 at /home/ajinasokan/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/ajinasokan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/ajinasokan/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at /home/ajinasokan/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
</details>

**Comment by jason-simmons** [comment] 2020-03-19 23:27
A crash due to a SIGILL in an ARM emulator is probably happening because some ARM emulators claim to support integer division but do not actually support it (see https://github.com/flutter/flutter/issues/37193)

**Comment by chinmaygarde** [comment] 2020-06-13 00:19
Duplicate of https://github.com/flutter/flutter/issues/37193 which has been fixed.

**Closed by chinmaygarde** 2020-06-13 00:19 UTC
Labels: a: production, engine, severe: crash
