### ISSUE TITLE
[Web][url_launcher][WebGL] Flashing items with Links

### ISSUE THREAD

**Issue by zltnDC** [flutter/flutter#87686] opened 2021-08-04 20:18 UTC
**Description:**

Flutter Web has problems displaying list items that contain the Link widget from url_launcher. I noticed items flashing randomly when scrolling.

url_launcher: ^6.0.9

Related to: https://github.com/flutter/flutter/issues/75914

<details>
  <summary>Flutter doctor</summary>

```

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale pl-PL)
    • Flutter version 2.2.3 at /Users/name/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

...

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 

```
</details>

<details>
  <summary>Console log</summary>

```
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:62997/AOPo4Fxyugs%3D/ws
Debug service listening on ws://127.0.0.1:62997/AOPo4Fxyugs=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:62997/AOPo4Fxyugs=/ws
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
... and more
```
</details>

**Minimal example:**

<details>
  <summary>Source code</summary>

```
import 'package:flutter/material.dart';
import 'package:url_launcher/link.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Demo'),
      ),
      body: ListView.builder(
        itemCount: 111,
        itemBuilder: (BuildContext context, int index) {
          return Card(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Link(
                target: LinkTarget.blank,
                uri: Uri.parse('https://flutter.dev/'),
                builder: (context, _) => Text(index.toString()),
              ),
            ),
          );
        },
      ),
    );
  }
}
```
</details>

**Comment by TahaTesser** [comment] 2021-08-05 14:50
Hi @zltnDC 
I can reproduce the issue on the latest `stable` channel, however, this seems to be on `beta` channel

Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

Closing, as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-05 14:50 UTC
Labels: in triage

**Comment by zltnDC** [comment] 2021-08-08 11:52
I checked your suggestion and the result is the same.

<details>
  <summary>Screenshots</summary>
  <img width="1392" alt="img" src="https://user-images.githubusercontent.com/56175965/128630615-451bacbc-32d8-4aaa-b326-878e5a1d7d40.png">
<img width="1392" alt="img2" src="https://user-images.githubusercontent.com/56175965/128630748-961f138d-6da6-43cc-a8af-cd8801572a6c.png">
</details>
<details>
  <summary>Flutter doctor</summary>

```
flutter doctor -v
[✓] Flutter (Channel beta, 2.4.0-4.2.pre, on macOS 11.4 20F71 darwin-x64, locale pl-PL)
    • Flutter version 2.4.0-4.2.pre at /Users/name/fvm/versions/beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f18b9281c2 (2 weeks ago), 2021-07-22 14:08:30 -0700
    • Engine revision 844c29f42a
    • Dart version 2.14.0 (build 2.14.0-301.2.beta)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome
```
</details>

**Comment by zambetpentru** [comment] 2021-08-13 06:42
@TahaTesser I just ran this against the latest master and I see a platform view error and can then make it error on scrolling.

![image](https://user-images.githubusercontent.com/81489824/129315404-f13ea913-d166-4d42-97ed-d3e0b91d4228.png)

<details>
  <summary>Error detail</summary>

Error: setState() called after dispose(): _PlatformViewLinkState#9bc98(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree
(e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState()
from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another
solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in
the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to
this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to
this object during dispose().
    at Object.throw_ [as throw] (http://localhost:49648/dart_sdk.js:5087:11)
    at http://localhost:49648/packages/flutter/src/widgets/widget_inspector.dart.lib.js:10730:23
    at platform_view$._PlatformViewLinkState.new.setState
    (http://localhost:49648/packages/flutter/src/widgets/widget_inspector.dart.lib.js:10736:28)
    at platform_view$._PlatformViewLinkState.new.[_onPlatformViewCreated]
    (http://localhost:49648/packages/flutter/src/widgets/platform_view.dart.lib.js:993:12)
    at http://localhost:49648/packages/url_launcher_web/src/link.dart.lib.js:257:12
    at _RootZone.runUnary (http://localhost:49648/dart_sdk.js:38527:59)
    at _FutureListener.then.handleValue (http://localhost:49648/dart_sdk.js:33727:29)
    at handleValueCallback (http://localhost:49648/dart_sdk.js:34279:49)
    at Function._propagateToListeners (http://localhost:49648/dart_sdk.js:34317:17)
    at _Future.new.[_completeWithValue] (http://localhost:49648/dart_sdk.js:34165:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49648/dart_sdk.js:34186:35)
    at Object._microtaskLoop (http://localhost:49648/dart_sdk.js:38794:13)
    at _startMicrotaskLoop (http://localhost:49648/dart_sdk.js:38800:13)
    at http://localhost:49648/dart_sdk.js:34533:9
</details>

<details>
  <summary>Flutter doctor</summary>

  [√] Flutter (Channel master, 2.5.0-7.0.pre.53, on Microsoft Windows [Version 10.0.17763.2114], locale en-IE)
    • Flutter version 2.5.0-7.0.pre.53 at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9764d861ca (12 hours ago), 2021-08-12 11:42:04 -0700
    • Engine revision 06da8b0c07
    • Dart version 2.15.0 (build 2.15.0-5.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.70

• No issues found!
</details>
