### ISSUE TITLE
App crashes when importing camerakit-android

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#14425] opened 2018-02-01 23:36 UTC
When I try to add this library to my project: https://github.com/CameraKit/camerakit-android
It will crash immediately on running with the following error
```
02-01 18:12:09.973 22076-22076/com.yourcompany.blank E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.yourcompany.blank, PID: 22076
  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yourcompany.blank-2/base.apk"],nativeLibraryDirectories=[/data/app/com.yourcompany.blank-2/lib/arm64, /data/app/com.yourcompany.blank-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
    at java.lang.Runtime.loadLibrary0(Runtime.java:984)
    at java.lang.System.loadLibrary(System.java:1562)
    at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:157)
    at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:142)
    at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:20)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5405)
    at android.app.ActivityThread.-wrap2(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6121)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

## Steps to Reproduce
- `flutter create testapp`
- open `android/app/build.gradle` and add `compile 'com.wonderkiln:camerakit:0.13.1'` to it
- `flutter run`
- should crash

I see this on a Nexus 5, and it will happen consistently

## Logs
Nothing of note, app crashes immediately

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G1114, locale en-US, channel master)
    • Flutter version 0.0.12-pre.284 at /Users/KG/Developer/Flutter/flutter
    • Framework revision f49d16dd2f (6 days ago), 2018-01-26 09:06:41 -0500
    • Engine revision 4c82c566ed
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0RC2.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25
```

**Comment by xster** [comment] 2018-02-01 23:58
@mravn-google can you help re-route this issue?

**Comment by jason-simmons** [comment] 2018-02-02 18:41
The library search path implies that the target is 64-bit Android.  We just landed support for Flutter on android-arm64 a few days ago.

Try building the APK with `flutter build apk --target-platform=android-arm64`

**Comment by KevinTheGray** [comment] 2018-02-05 16:40
@jason-simmons I'm hitting an error when trying to run that flutter build command

```
Cannot locate the genSnapshot executable

FAILURE: Build failed with an exception.

* Where:
Script '/Users/KG/Developer/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 388

* What went wrong:
Execution failed for task ':app:flutterDependenciesFb_debugRelease'.
> Process 'command '/Users/KG/Developer/Flutter/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Gradle build failed: 1
```

**Comment by jason-simmons** [comment] 2018-02-05 17:51
Ah, I see you're running on a Mac.  Right now we're only uploading the android-arm64 tools for Linux.  Mac and Windows support will come soon.

**Comment by alvarlagerlof** [comment] 2018-02-08 20:28
I need Mac support too.

**Comment by xster** [comment] 2018-04-03 22:47
I think this is solved now. Please reopen if the issue is still occurring for anyone.

**Closed by xster** 2018-04-03 22:47 UTC
Labels: customer: posse (eap), plugin: framework, ▣ platform-android
