### ISSUE TITLE
TextPainter line metrics test flaked on Linux

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#43763] opened 2019-10-29 22:34 UTC
From https://cirrus-ci.com/task/6466421722185728

```
00:16 +16 ~1 -1: /tmp/flutter sdk/packages/flutter/test/painting/text_painter_test.dart: TextPainter line metrics [E]                                                                                  
  Expected: <false>
    Actual: <true>
  
  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 231:3  expect
  test/painting/text_painter_test.dart 749:5         main.<fn>
  
```

It passed on the next PR afterwards

**Comment by jonahwilliams** [comment] 2019-10-30 04:52
This happened again in https://api.cirrus-ci.com/v1/task/4795481758105600/logs/main.log

**Comment by jonahwilliams** [comment] 2019-10-30 04:52
cc @GaryQian

**Comment by GaryQian** [comment] 2019-10-30 18:27
Hmm, this test should not be flaky, it is not dependent on anything but the engine LibTxt code, which is performed synchronously and deterministically.

Do you know how frequently the test is flaking?

**Comment by jonahwilliams** [comment] 2019-10-30 19:26
I've seen it fail twice in a single day

**Comment by GaryQian** [comment] 2019-10-31 20:04
I am unable to repro flakiness locally, Ran over 100 times with zero flakes. I'll continue to keep an eye out for it and will revisit if it becomes a problem.

**Comment by goderbauer** [comment] 2019-11-06 23:00
@jonahwilliams are you still seeing these flakes?

**Comment by jonahwilliams** [comment] 2019-11-06 23:04
Negative

**Comment by GaryQian** [comment] 2019-11-06 23:43
I have not done anything, but I haven't seen them either. Seems to have gone away by itself.

**Comment by GaryQian** [comment] 2019-11-06 23:46
Going to add the waiting for customer response flag, reply if this is still relevant in near future.

**Comment by jonahwilliams** [comment] 2019-11-12 23:55
Happened again: https://api.cirrus-ci.com/v1/task/6486989225852928/logs/main.log

**Comment by jonahwilliams** [comment] 2019-11-13 16:31
And again: https://api.cirrus-ci.com/v1/task/6040160726155264/logs/main.log

**Comment by GaryQian** [comment] 2019-11-13 22:51
Ok, this must be real then, will look when i get a chance

**Comment by tvolkert** [comment] 2019-11-19 20:32
Just ran into this again -- https://api.cirrus-ci.com/v1/task/6244159039471616/logs/test_framework.log

**Comment by jonahwilliams** [comment] 2019-11-20 03:27
Happened again on LUCI: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8896305037073337408/+/steps/run_test.dart_for_framework_tests_shard/0/stdout

**Comment by jonahwilliams** [comment] 2019-11-20 18:13
Happened again: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8896249721706362304/+/steps/run_test.dart_for_framework_tests_shard/0/stdout

**Comment by GaryQian** [comment] 2019-11-20 20:47
Yeah this flake is definitely real. Still unable to repro locally.

**Comment by goderbauer** [comment] 2019-11-20 22:50
Looks like it does reproduce on cirrus? Maybe push a PR with a bunch of extra logging up and see if you can reproduce it there and figure out why it's happening?

**Comment by GaryQian** [comment] 2019-11-22 00:38
Experiment PR: https://github.com/flutter/engine/pull/13966

**Comment by Piinks** [comment] 2019-12-04 23:30
Happened twice in a row on Cirrus here: https://cirrus-ci.com/task/4548185002868736

**Comment by Piinks** [comment] 2019-12-05 17:25
Here in a pre-submit check: https://cirrus-ci.com/task/4616674262646784

**Comment by GaryQian** [comment] 2019-12-06 02:38
So it looks like it doesn't happen on Engine presubmit runs of framework tests. I'll see if I can come up with a way to repro it in the Framework presubmit or locally.

**Comment by GaryQian** [comment] 2019-12-06 04:51
Attempting a similar process but on the framework side: https://github.com/flutter/flutter/pull/46213

**Comment by jonahwilliams** [comment] 2019-12-09 23:51
Happened again: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8894507654043620080/+/steps/run_test.dart_for_framework_tests_shard/0/stdout

**Comment by jonahwilliams** [comment] 2019-12-10 02:34
Happened again on cirrus: https://cirrus-ci.com/task/5038874639728640

**Comment by GaryQian** [comment] 2019-12-10 02:36
Is there a way to mark a flutter test as flaky? I don't want this to block/slow people but reproing reliably it is very difficult. I'm currently rerunning a PR with logging on Cirrus.

**Comment by jonahwilliams** [comment] 2019-12-10 02:47
Negatory. Would it be possible to amend the test to dump all of the info you need to debug on a failure? It would still block people but you might get your feedback more quickly

**Comment by jonahwilliams** [comment] 2019-12-10 02:48
Or, as a last resort you could skip on linux

**Comment by tvolkert** [comment] 2019-12-10 02:51
Let's not skip, as this could be indicative of a real bug affecting users.

**Comment by goderbauer** [comment] 2019-12-18 22:58
@GaryQian Where you able to figure anything out here by any chance?

**Comment by GaryQian** [comment] 2019-12-18 23:03
not yet. I'll go ahead an "prescreen" the test for the failing result, and dump data as Jonah suggested. The flake still seems too rare to just keep hitting rerun on my flake-detection PR.

**Comment by GaryQian** [comment] 2019-12-18 23:18
https://github.com/flutter/flutter/pull/46213 should now be landed, and any flakes that happen in the wild will log the metrics reported. Not sure what other information is useful at this point as it is unclear what is causing.

Looking for review :)

**Comment by dnfield** [comment] 2020-01-02 18:02
From a recent failure:

```
LineMetrics called: 4
0: true
23605080: true
23605080: true
23605080: true

04:03 +2237 ~3 -1: /tmp/flutter sdk/packages/flutter/test/painting/text_painter_test.dart: TextPainter line metrics [E]                                                                                
  Expected: <false>
    Actual: <true>
  
  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 348:3  expect
  test/painting/text_painter_test.dart 758:5         main.<fn>
```

**Comment by dnfield** [comment] 2020-01-02 18:04
What's with those line numbers?

**Comment by dnfield** [comment] 2020-01-02 18:17
@GaryQian could this be a race between `layout` and `computeLineMetrics`?  Are we using the new Skia text shaping stuff, and if so is it doing anything multi-threaded?

**Comment by GaryQian** [comment] 2020-01-02 20:34
Thanks for finding that.

Values look too small to be overflow, maybe something with the way we encode it? It's a good place to start looking at least.

This is still totally from LibTxt and is done on the same thread.

**Comment by dnfield** [comment] 2020-01-08 15:17
again: https://cirrus-ci.com/task/5931335038533632?command=main#L1094

**Comment by christopherfujino** [comment] 2020-01-08 18:22
seeing it here: https://cirrus-ci.com/task/6339835417853952?command=main#L1286

**Comment by goderbauer** [comment] 2020-01-08 22:56
Here's another one: https://cirrus-ci.com/task/5831446229155840

**Comment by Piinks** [comment] 2020-01-10 20:56
Once more with feeling: https://cirrus-ci.com/task/6677267694747648

**Comment by GaryQian** [comment] 2020-01-14 20:59
Going to add FML checks to ensure we aren't accidentally calling the linemetrics getter before layout is done, which can cause this strange behavior.

**Comment by jonahwilliams** [comment] 2020-01-21 18:49
This happened 3-4 times this morning

**Comment by GaryQian** [comment] 2020-01-22 00:39
Adding a few additional expectations between layout and computeLineMetrics to check if there is a race going on: https://github.com/flutter/flutter/pull/49261

**Comment by jonahwilliams** [comment] 2020-01-22 19:15
Another failure:
```
03:53 +2269 ~3: /tmp/flutter sdk/packages/flutter/test/painting/text_painter_test.dart: TextPainter line metrics                                                                                       
LineMetrics called: 4
0: true
23659696: true
23659696: true
23659696: true
03:53 +2269 ~3 -1: /tmp/flutter sdk/packages/flutter/test/painting/text_painter_test.dart: TextPainter line metrics [E]                                                                                
  Expected: <false>
    Actual: <true>
  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 348:3  expect
  test/painting/text_painter_test.dart 758:5         main.<fn>
```

**Comment by dnfield** [comment] 2020-01-22 20:01
related patch is still open.

**Comment by dnfield** [comment] 2020-01-23 04:34
Still happening with reland patch apparently.

The value doesn't seem to be stable either - It's consistently around 235xxxxx to 236xxxxx, but each failure seems to have it slightly different.

@aam @rmacnak-google - any chance this could be some kind of background compiler issue?

**Comment by dnfield** [comment] 2020-01-23 04:34
I've run it ... a whole lot locally and don't get a failure.

**Comment by GaryQian** [comment] 2020-01-23 18:54
I will disable it for now, the values in this test are still covered in paragraph_unittests.cc in the engine, so we won't loose too much coverage from disabling this.

I have also run it hundreds of times locally, in various configurations with no repro.

**Comment by GaryQian** [comment] 2020-01-23 19:11
https://github.com/flutter/flutter/pull/49364 Disables the test.

**Comment by goderbauer** [comment] 2020-03-18 21:54
Closing this since the test is disabled now.

**Closed by goderbauer** 2020-03-18 21:54 UTC
Labels: a: typography, engine, framework, team: flakes, 🐧 platform-linux
