### ISSUE TITLE
libtxt: Text objects with empty-string data should take vertical layout space

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#3345] opened 2016-04-15 01:00 UTC
When a Text object is set to the empty string, it takes no space in the layout - neither horizontal nor vertical.  This leads to situations where the layout changes in unexpected ways when the Text's contents change.

In the following example, the button position jumps as it is tapped:

```dart
import 'package:flutter/material.dart';

class TextSpaceWidget extends StatefulWidget {
  @override
  State createState() => new TextSpaceState();
}

class TextSpaceState extends State<TextSpaceWidget> {
  String _text = '';
  void _handleButtonPressed() {
    setState(() {
      _text = _text == '' ? 'Hello world' : '';
    });
  }
  @override
  Widget build(BuildContext context) {
    return new Material(
      child: new Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          new Text(_text),
          new RaisedButton(
            child: new Text('Tap me'),
            onPressed: _handleButtonPressed
          )
        ]
      )
    );
  }
}

void main() {
  runApp(
    new MaterialApp(
      routes: <String, WidgetBuilder>{
        '/': (BuildContext context) => new TextSpaceWidget()
      }
    )
  );
}
```

**Comment by krisgiesing** [comment] 2016-04-15 01:01
@Hixie

**Comment by abarth** [comment] 2016-04-15 04:33
This is by-design.  We might need to revisit the design.  Maybe the `Text` widget should substitute a zero-width space for empty strings like the `Input` widget does...

**Comment by Hixie** [comment] 2016-04-15 06:00
It's by design for CSS, but I think a solid argument can be made that the paragraph line-height should be honoured even for empty paragraphs.

**Comment by abarth** [comment] 2016-04-15 06:06
I can't think of any bad things that would cause.  There might be some interaction with how we eventually do replaced spans, but we can alway use null strings instead of empty strings for 0x0 spans if we get into trouble.

**Comment by krisgiesing** [comment] 2016-04-15 16:37
FWIW, Android honors line-height for empty content TextViews (even if using wrap_content). I'm not sure what other frameworks do.

**Comment by Hixie** [comment] 2017-12-18 19:54
cc @jason-simmons Might be easy for you to fix this one while you're in that code -- it probably just requires removing some special case code for empty strings.

**Comment by darshankawar** [comment] 2020-09-04 08:25
Hi @krisgiesing,
I verified this on latest stable (1.20.3) and the button doesn't jump upon tap.

[3345.mp4.zip](https://github.com/flutter/flutter/files/5173558/3345.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (2 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

</details>

Can you please confirm if this is still valid or can be closed ?
Thanks.

**Comment by prik-k** [comment] 2020-09-22 15:50
Hi @darshankawar 
The author of this issue @krisgiesing is inactive upon this issue for years now. Moreover the issue seems to be fixed in recent flutter versions. 

So i guess it can be closed now owing to huge number of unnecessary open issues here.

Please go ahead and close this issue.
Thanks.

**Comment by krisgiesing** [comment] 2020-09-22 18:10
If the problem doesn't repro then this issue can be closed.

I am a little annoyed at the "inactive upon this issue for years" comment. I somehow missed the request for confirmation 18 days ago, but before that, this issue was not waiting on me for anything.

**Comment by darshankawar** [comment] 2020-09-23 05:18
Closing this as fixed.

**Closed by darshankawar** 2020-09-23 05:18 UTC
Labels: P4, a: typography, engine, framework
