### ISSUE TITLE
Support text selections

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#225] opened 2015-11-09 21:49 UTC
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 01:37 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1778_

----

Text selections in read-only text areas, text selections in input fields, etc.

**Comment by sethladd** [comment] 2016-01-07 23:14
See also https://www.google.com/design/spec/patterns/selection.html#selection-item-selection

**Comment by abarth** [comment] 2016-01-22 00:30
Dupe of #107

**Closed by abarth** 2016-01-22 00:30 UTC
Labels: affects: framework, affects: material design, affects: text input, ⚠ brand new feature
