### ISSUE TITLE
Facing Unusual Error While try to Debug Flutter Application in Some Device Like ( Vivo Z1 Pro )

### ISSUE THREAD

**Issue by sanz777** [flutter/flutter#110237] opened 2022-08-25 04:11 UTC
Hello , 
Facing Unusual Error While try to Debug Flutter Application in Some Device Like ( Vivo Z1 Pro )

Error : 
Launching lib/main.dart on vivo 1951 in debug mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
I/flutter ( 3014): The Dart VM service is listening on ************************************
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on vivo 1951.
Exited

Flutter Doctor -v 
sanjaysalve@Sanjays-MacBook-Pro task_manager % flutter doctor -v                     
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.6 20G624 darwin-x64, locale en-IN)
    • Flutter version 3.0.5 at /Users/sanjaysalve/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/sanjaysalve/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • vivo 1951 (mobile) • bf5d0a7a • android-arm64 • Android 11 (API 30)
    • macOS (desktop)    • macos    • darwin-x64    • macOS 11.6.6 20G624 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

Anyone Know how to Fix This Error 
@flutter-github-sync @flutter-intellij-kokoro @fluttercerberus @fluttergalleryreleasebot

**Comment by danagbemava-nc** [comment] 2022-08-25 10:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/106086. 

Please refrain from filing multiple issues for the same bug.

**Closed by danagbemava-nc** 2022-08-25 10:40 UTC
Labels: in triage
