### ISSUE TITLE
[camera]  start recording a video the app freezes - Skipped 31 frames! The application may be doing too much work on its main thread 

### ISSUE THREAD

**Issue by MoaathJO** [flutter/flutter#54766] opened 2020-04-14 18:17 UTC
Everything is working find, Except a small issue while start recording a video the app freezes (Janks) a little then goes fine until again stop the recording. 

everything is done in async and await, but seems the starting of writing operation by the camera is making this issue.

anyone has the same issue?

**Comment by TahaTesser** [comment] 2020-04-15 08:03
Hi @MoaathJO 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem, to better understand cause of the app freezes 
Thank you

**Comment by MoaathJO** [comment] 2020-04-15 12:12
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';
import 'package:path_provider/path_provider.dart';
import 'package:gallery_saver/gallery_saver.dart';

class MyCamera extends StatefulWidget {
  @override
  _MyCameraState createState() => _MyCameraState();
}

class _MyCameraState extends State<MyCamera> {
  CameraController controller;
  List<CameraDescription> cameras = [];
  int camIndex = 0;
  var path;

  void initCameras(int cameraIndex) async {

    cameras = await availableCameras();
    
    controller = CameraController(cameras[cameraIndex], ResolutionPreset.high, enableAudio: true);
    
    controller.initialize().then((_) {
      setState(() {});
    });
  }

  void capturePhoto() async {
    try {
      path = (await getApplicationDocumentsDirectory()).path +'${DateTime.now()}.png'; //Temporary path
      await controller.takePicture(path); //take photo
      await GallerySaver.saveImage(path, albumName: 'Flutter');
    } catch (e) {
      print(e);
    }
  }

// Start recording a video
  void startRecording() async {
    try {
      path = (await getApplicationDocumentsDirectory()).path +'${DateTime.now()}.mp4'; //path to store the video
      await controller.prepareForVideoRecording();
      **_await controller.startVideoRecording(path);_** // start recording <<<<<<<<<<<< problem here when start recording
    } catch (e) {
      print(e);
    }
  }

  void stopRecording() async {
    **_await controller.stopVideoRecording();_**  <<<<<<<<<<<< problem here when start recording
    await GallerySaver.saveVideo(path, albumName: 'Flutter');
  }

  @override
  void initState() {
    super.initState();
    initCameras(0); // defaults to first cam
  }

  @override
  void dispose() {
    controller?.dispose(); // release camera
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (controller == null) {
      return Center(
        child: CircularProgressIndicator(),
      );
    }

    return Stack(children: [
      GestureDetector(
        onVerticalDragEnd: (drag) {
          if ((drag.velocity.pixelsPerSecond.dy).abs() >= 2) {
            camIndex++;
            initCameras(camIndex % 3); // change camera on swipe
          }
        },
        child: Align(
          alignment: Alignment.center,
          child: AspectRatio(
            aspectRatio: controller.value.aspectRatio,
            child: CameraPreview(controller),
          ),
        ),
      ),
      Container(
        alignment: AlignmentDirectional.bottomEnd,
        padding: EdgeInsets.symmetric(vertical: 30),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            SizedBox(
                width: 50,
                child: RaisedButton(
                    child: Text("B/Nor"), onPressed: () => {initCameras(0)})),
            SizedBox(
                width: 50,
                child: RaisedButton(
                    child: Text("B/Wide"), onPressed: () => {initCameras(2)})),

            SizedBox(
                width: 50,
                child: RaisedButton(
                    child: Text("F/Clo"), onPressed: () => {initCameras(1)})),
            SizedBox(
                width: 50,
                child: RaisedButton(
                    child: Text("F/Wide"), onPressed: () => {initCameras(3)})),

            //zoom camera not working!! Galaxy note 10+
            SizedBox(
                width: 50,
                child: RaisedButton(
                    child: Text("4"), onPressed: () => {initCameras(4)})),

            SizedBox(
              width: 50,
              child: RaisedButton(
                child: Icon(Icons.camera),
                onPressed: () => {capturePhoto()}, // Take photo
              ),
            ),

            SizedBox(
              width: 50,
              child: GestureDetector(
                child: Icon(
                  Icons.videocam,
                  color: Colors.red,
                ),
                onLongPress: () => {startRecording()}, // start recording video
                onLongPressEnd: (longDetalis) =>
                    {stopRecording()}, // stop recording video
              ),
            ),
          ],
        ),
      ),
    ]);
  }
}

**Comment by MoaathJO** [comment] 2020-04-15 12:14
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.778], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at c:\src\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at c:\Users\moaath\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = c:\Users\moaath\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.1)
    • VS Code at C:\Users\Moaath\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • SM N975F • 192.168.100.18:5555 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

**Comment by MoaathJO** [comment] 2020-04-15 12:22
[   +2 ms] �🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +2 ms] An Observatory debugger and profiler on SM N975F is available at: http://127.0.0.1:57599/hNa3nvCB6oM=/
[  +30 ms] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+3907 ms] D/ViewRootImpl@b0eb978[MainActivity](29285): ViewPostIme pointer 0
[ +817 ms] I/CameraManagerGlobal(29285): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.example.flutter_hello API Level 2
[ +133 ms] W/e.flutter_hell(29285): Long monitor contention with owner main (29285) at void
android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(android.hardware.camera2.params.InputConfiguration, java.util.List,
android.hardware.camera2.CameraCaptureSession$StateCallback, java.util.concurrent.Executor, int, android.hardware.camera2.CaptureRequest)(CameraDeviceImpl.java:643)        
waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 391ms  
[   +4 ms] I/Choreographer(29285): Skipped 31 frames!  The application may be doing too much work on its main thread.
[ +202 ms] I/CameraManagerGlobal(29285): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.example.flutter_hello API Level 2
[+2389 ms] D/ViewRootImpl@b0eb978[MainActivity](29285): ViewPostIme pointer 1
[ +440 ms] I/CameraManagerGlobal(29285): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.example.flutter_hello API Level 2
[ +160 ms] W/e.flutter_hell(29285): Long monitor contention with owner main (29285) at void
android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(android.hardware.camera2.params.InputConfiguration, java.util.List,
android.hardware.camera2.CameraCaptureSession$StateCallback, java.util.concurrent.Executor, int, android.hardware.camera2.CaptureRequest)(CameraDeviceImpl.java:643)        
waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 427ms  
[ +288 ms] I/CameraManagerGlobal(29285): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.example.flutter_hello API Level 2

**Comment by TahaTesser** [comment] 2020-04-15 12:45
Hi @MoaathJO 
This could be because of `gallery_saver`

Can you please try with official [sample](https://pub.dev/packages/camera#-example-tab-)
Thanks

**Comment by MoaathJO** [comment] 2020-04-15 13:04
Hi @TahaTesser 
It is not.
as the issue happens on start recording as well, 
and Gallery_saver is only on Stop

**Comment by MoaathJO** [comment] 2020-04-15 13:16
Same isuue:

[ +164 ms] W/e.flutter_hell( 3482): Long monitor contention with owner main (3482) at void
android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(android.hardware.camera2.params.InputConfiguration, java.util.List,
android.hardware.camera2.CameraCaptureSession$StateCallback, java.util.concurrent.Executor, int, android.hardware.camera2.CaptureRequest)(CameraDeviceImpl.java:643)        
waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative,
android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 395ms
[  +33 ms] I/Choreographer( 3482): Skipped 30 frames!  The application may be doing too much work on its main thread.
[  +33 ms] W/e.flutter_hell( 3482): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
[   +1 ms] I/ExoPlayerImpl( 3482): Init 40d5a8f [ExoPlayerLib/2.9.6] [d2s, SM-N975F, samsung, 29]

**Comment by MoaathJO** [comment] 2020-04-15 18:14
@TahaTesser it might be the plugin issue, as i tried some PoC through implementing heavy job and regardless having its execution synchronously running, it freezes the UI and drops frames.

This leads to suspect that the code implements the native camera plugin (Java in our case) at some point has an operation that locks the execution a little... which in other words needs a separate thread to handle its execution.

Hope I find a solution to this or for the plugin team to release  a new version fixing this issue if so.

**Comment by chamarts** [comment] 2020-04-19 08:46
may be the the plugin need to create a native thread and get a callback when its done ?

**Comment by TahaTesser** [comment] 2020-05-20 07:43
Closing in favor of https://github.com/flutter/flutter/issues/57451 
Since it happens when starting recording and end recoding

**Closed by TahaTesser** 2020-05-20 07:43 UTC
Labels: has reproducible steps, p: camera, p: first party, plugin, severe: performance
