### ISSUE TITLE
url_launcher plugging missing method?

### ISSUE THREAD

**Issue by dvaldivia** [flutter/flutter#25193] opened 2018-12-11 07:28 UTC
Hi, I'm trying to use the `url_launcher 0.4.1` plugging but Im getting the following exception when tryin to launch an URL, I just upgraded to flutter 1.0 via `flutter upgrade`

any ideas what could be causing this? 

```
MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
<asynchronous suspension>
#1      canLaunch (package:url_launcher/url_launcher.dart:88:25)
<asynchronous suspension>
#2      PostWidget.build._launchURL (package:app/post.dart:66:17)
<asynchronous suspension>
#3      PostWidget.build.<anonymous closure> (package:app/post.dart:107:44)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
```

**Comment by zoechi** [comment] 2018-12-11 09:04
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2018-12-11 09:05
Try `flutter clean` and 
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

**Comment by zoechi** [comment] 2018-12-12 20:50
Duplicate of #23832

**Closed by zoechi** 2018-12-12 20:50 UTC
Labels: p: first party, plugin, severe: crash, waiting for customer response
