### ISSUE TITLE
'package:cloud_firestore/src/firestore.dart': Failed assertion: line 49 pos 12: 'app != null': is not true.

### ISSUE THREAD

**Issue by pranjalchaplot** [flutter/flutter#69294] opened 2020-10-29 11:45 UTC
Hi,
I have a compile error every time that I run my app. I have 3 views, Home Page, Hack Page, and Hack Screen. Hack Page: contains the card where I want to show my life hack of the particular category. Hacks Screen is the file where I control the firestore stuff (the hacks of each category). Home Page is the home of the app and it contains the list of categories in the form of cards.

My main goal is for the user to click on a particular category and then take the chosen category as **_collectionPath_** and put it in **_firestore.collection(collectionPath).snapshots()_**

**_For example:_** 

In the Home Page the user clicks on the Travel Category --> it Navigates to Hack Screen with parameters of collectionPath as "travel" which is the collection name I have on firestore which contains all the travel categories hacks. --> it again Navigates to Hack Page where  I have created a card and other option which then shows the Life Hacks of Travel one by one (controllable by button)

**_Problem:_** 
It's dropping this error and also when I remove the Hacks Screen from the process and directly navigate to Hack Page with random text it works fine so I think the problem is in the Hack Screen

**_The error is:_**

```
D/ColorViewRootUtil(20907): nav bar mode ignore false downX 513 downY 380 mScreenHeight 1520 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=513.0, y[0]=380.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=42425289, downTime=42425289, deviceId=3, source=0x1002, displayId=0 }
D/ColorViewRootUtil(20907): nav bar mode ignore false downX 499 downY 621 mScreenHeight 1520 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=499.0, y[0]=621.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=42426777, downTime=42426777, deviceId=3, source=0x1002, displayId=0 }
I/flutter (20907): Another exception was thrown: 'package:cloud_firestore/src/firestore.dart': Failed assertion: line 49 pos 12: 'app != null': is not true.

Performing hot reload...
Reloaded 2 of 792 libraries in 662ms.
D/ColorViewRootUtil(20907): nav bar mode ignore false downX 427 downY 633 mScreenHeight 1520 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=427.0, y[0]=633.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=42507154, downTime=42507154, deviceId=3, source=0x1002, displayId=0 }
I/flutter (20907): Another exception was thrown: 'package:cloud_firestore/src/firestore.dart': Failed assertion: line 49 pos 12: 'app != null': is not true.

Performing hot reload...                                               -I/flutter (20907): ══╡ EXCEPTION CAUGHT BY WIDGETS 
LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20907): The following assertion was thrown building Builder(dirty):
I/flutter (20907): 'package:cloud_firestore/src/firestore.dart': Failed assertion: line 49 pos 12: 'app != null': is       
I/flutter (20907): not true.
I/flutter (20907):
I/flutter (20907): The relevant error-causing widget was:
I/flutter (20907):   MaterialApp file:///D:/Work/Learning/Learning%20Flutter/LifeHacks_app/main/lib/main.dart:11:12        
I/flutter (20907):
I/flutter (20907): When the exception was thrown, this was the stack:
I/flutter (20907): #2      FirebaseFirestore.instanceFor (package:cloud_firestore/src/firestore.dart:49:12)
I/flutter (20907): #3      new HackScreen (package:main/views/hack_screen.dart:6:58)
I/flutter (20907): #4      _MyHacksState.build.<anonymous closure>.<anonymous closure> (package:main/views/home_page.dart:85:41)
I/flutter (20907): #5      CupertinoPageRoute.buildContent (package:flutter/src/cupertino/route.dart:360:55)
I/flutter (20907): #6      CupertinoRouteTransitionMixin.buildPage (package:flutter/src/cupertino/route.dart:228:26)       
I/flutter (20907): #7      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:818:45)     
I/flutter (20907): #8      Builder.build (package:flutter/src/widgets/basic.dart:7196:48)
I/flutter (20907): #9      StatelessElement.build (package:flutter/src/widgets/framework.dart:4730:28)
I/flutter (20907): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4656:15)
I/flutter (20907): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #12     StatelessElement.update (package:flutter/src/widgets/framework.dart:4737:5)
I/flutter (20907): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6152:14)      
I/flutter (20907): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6152:14)
I/flutter (20907): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4828:11)
I/flutter (20907): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:4860:5)
I/flutter (20907): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #23     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5674:32)
I/flutter (20907): #24     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6274:17)
I/flutter (20907): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #27     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4828:11)
I/flutter (20907): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:4860:5)
I/flutter (20907): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
       \I/flutter (20907): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6152:14)
I/flutter (20907): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4828:11)
I/flutter (20907): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:4860:5)
I/flutter (20907): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6152:14)
I/flutter (20907): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4828:11)
I/flutter (20907): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #43     StatefulElement.update (package:flutter/src/widgets/framework.dart:4860:5)
I/flutter (20907): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6152:14)      
I/flutter (20907): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #48     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4828:11)
I/flutter (20907): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #50     StatefulElement.update (package:flutter/src/widgets/framework.dart:4860:5)
I/flutter (20907): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #54     StatelessElement.update (package:flutter/src/widgets/framework.dart:4737:5)
I/flutter (20907): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4828:11)
I/flutter (20907): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #59     StatefulElement.update (package:flutter/src/widgets/framework.dart:4860:5)
I/flutter (20907): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6152:14)
I/flutter (20907): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
        
Reloaded 2 of 792 libraries in 1,199ms.
I/flutter (20907): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #65     ProxyElement.update (package:flutter/src/widgets/framework.dart:5014:5)
I/flutter (20907): #66     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)   
I/flutter (20907): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6152:14)      
I/flutter (20907): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4828:11)
I/flutter (20907): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:4860:5)
I/flutter (20907): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #77     ProxyElement.update (package:flutter/src/widgets/framework.dart:5014:5)
I/flutter (20907): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #80     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4828:11)
I/flutter (20907): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #82     StatefulElement.update (package:flutter/src/widgets/framework.dart:4860:5)
I/flutter (20907): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4737:5)
I/flutter (20907): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6152:14)      
I/flutter (20907): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #92     ProxyElement.update (package:flutter/src/widgets/framework.dart:5014:5)
I/flutter (20907): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:3348:15)
I/flutter (20907): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:16)
I/flutter (20907): #95     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4828:11)
I/flutter (20907): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
I/flutter (20907): #97     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2758:33)
I/flutter (20907): #98     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:906:21)
I/flutter (20907): #99     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:310:5)
I/flutter (20907): #100    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (20907): #101    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (20907): #102    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (20907): (elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
I/flutter (20907):
I/flutter (20907): ════════════════════════════════════════════════════════════════════════════════════════════════════    
D/ColorViewRootUtil(20907): nav bar mode ignore false downX 490 downY 374 mScreenHeight 1520 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=490.0, y[0]=374.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=42783276, downTime=42783276, deviceId=3, source=0x1002, displayId=0 }

Performing hot reload...
Reloaded 3 of 792 libraries in 531ms.
D/ColorViewRootUtil(20907): nav bar mode ignore false downX 414 downY 590 mScreenHeight 1520 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=414.0, y[0]=590.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=42837758, downTime=42837758, deviceId=3, source=0x1002, displayId=0 }
I/flutter (20907): Another exception was thrown: 'package:cloud_firestore/src/firestore.dart': Failed assertion: line 49 pos 12: 'app != null': is not true.`
```
**_The Hack_Page.dart:_**

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:main/themes/style.dart';
import 'package:main/themes/theme_text.dart';

class HackPage extends StatelessWidget {
  final Color backgroundColor;
  final String hackText;

  const HackPage({
    Key key,
    @required this.backgroundColor,
    @required this.hackText,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Container(
          alignment: Alignment.center,
          child: Text(
            "Hacks For Life",
            style: GoogleFonts.oxygen(
              textStyle: TextStyle(
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ),
        actions: [
          GestureDetector(
            onTap: () {},
            child: Container(
              padding: EdgeInsets.symmetric(horizontal: 16),
              child: Icon(Icons.share_outlined),
            ),
          )
        ],
      ),
      body: Container(
        child: Column(
          children: [
            Container(
              margin: EdgeInsets.only(top: 35),
              child: Card(
                color: backgroundColor,
                margin: EdgeInsets.only(left: 20, right: 20),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.end,
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Stack(
                      children: [
                        Container(
                          height: 400,
                          width: 360,
                          alignment: Alignment.center,
                          child: ListTile(
                            title: Text(
                              hackText,
                              style: ThemeText.headline,
                              textAlign: TextAlign.center,
                            ),
                            tileColor: Colors.transparent,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10.0),
                ),
              ),
            ),
            SizedBox(
              height: 45,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                GestureDetector(
                  onTap: () {},
                  child: Column(
                    children: [
                      Container(
                          padding: EdgeInsets.symmetric(horizontal: 26),
                          child: Icon(
                            Icons.chevron_left_rounded,
                            color: Colors.white,
                            size: 50,
                          )),
                      Container(
                        margin: EdgeInsets.only(top: 5),
                        child: Text(
                          "Previous",
                          style: simpleText(),
                        ),
                      ),
                    ],
                  ),
                ),
                GestureDetector(
                  onTap: () {},
                  child: Column(
                    children: [
                      Container(
                          padding: EdgeInsets.symmetric(horizontal: 26),
                          child: Icon(
                            Icons.chevron_right_rounded,
                            color: Colors.white,
                            size: 50,
                          )),
                      Container(
                        margin: EdgeInsets.only(top: 5),
                        child: Text("Next", style: simpleText()),
                      )
                    ],
                  ),
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}

```
**_The Hack_Screen.dart:_**

```
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:main/views/hack_page.dart';
import 'package:random_color/random_color.dart';

class HackScreen extends StatelessWidget {
  final FirebaseFirestore _firestore = FirebaseFirestore.instanceFor();
  final RandomColor _randomColor = RandomColor();

  final String collectionPath;

  HackScreen({
    Key key,
    @required this.collectionPath,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamBuilder(
        stream: _firestore.collection(collectionPath).snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) return _LoadingIndicator();
          return PageView.builder(
            itemCount: snapshot.data.docs.length,
            itemBuilder: (context, index) {
              final document = snapshot.data.docs[index];
              return HackPage(
                backgroundColor: _randomColor.randomColor(
                  colorBrightness: ColorBrightness.dark,
                ),
                hackText: document['hack'],
              );
            },
          );
        },
      ),
    );
  }
}

class _LoadingIndicator extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: CircularProgressIndicator(),
    );
  }
}
```

**Comment by darshankawar** [comment] 2020-10-29 12:11
@pranjalchaplot 
This issue is better suited on StackOverflow. Please consider asking support questions there.
If you think the issue is related to the `cloud_firestore` plugin and not with your implementation, open the issue in Firebase dedicated repo : https://github.com/FirebaseExtended/flutterfire/issues
Closing this from here.

**Closed by darshankawar** 2020-10-29 12:11 UTC
