### ISSUE TITLE
Anti-aliasing apparent in Stretched FlexibleSpace.title 

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#53823] opened 2020-04-02 12:20 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update `main.dart` file as follows:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          controller: ScrollController(),
          physics: const BouncingScrollPhysics(),
          slivers: <Widget>[
            SliverAppBar(
              elevation: 0.0,
              expandedHeight: 200.0,
              pinned: false,
              stretch: true,
              leading: const CloseButton(color: Colors.white),
              flexibleSpace: FlexibleSpaceBar(
                background: Image.network(
                  'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Panor%C3%A1mica_Elche.JPG/1920px-Panor%C3%A1mica_Elche.JPG',
                  fit: BoxFit.cover,
                ),
                collapseMode: CollapseMode.none,
                title: Container(
                  height: 8.0,
                  decoration: const BoxDecoration(
                    borderRadius: BorderRadius.vertical(
                      top: Radius.circular(20.0),
                    ),
                    color: Colors.white,
                  ),
                ),
                centerTitle: true,
                titlePadding: const EdgeInsets.all(0),
              ),
            ),
            SliverList(
              delegate: SliverChildListDelegate(
                <Widget>[
                  ColoredBox(
                    color: Colors.white,
                    child: Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: const <Widget>[
                          SizedBox(height: 16.0),
                          Placeholder(),
                          SizedBox(height: 16.0),
                          Placeholder(),
                          SizedBox(height: 16.0),
                          Placeholder(),
                          SizedBox(height: 16.0),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    ),
  );
}
```
3. Scroll in any direction.

- If you scroll from top to bottom, while overscrolling thanks to `stretch: true`, you can notice a weird line appears above the `Placeholder`s (between `SliverAppBar` and `SliverList`). 
- If you scroll from bottom to top, a _smaller_ line appears. If you stop scrolling, the line will remain rendered.

**Expected results:** No gap between between `SliverAppBar` and `SliverList`.

**Actual results:** A weird line appears between `SliverAppBar` and `SliverList`.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, v1.16.4-pre.69, on Microsoft Windows [VersiÃ³n 10.0.18363.752], locale es-ES)
    • Flutter version 1.16.4-pre.69 at C:\flutter
    • Framework revision 19e7db585d (18 hours ago), 2020-04-01 11:16:01 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\crist\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.2-dev.5
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Connected device (3 available)
    • Pixel 3 XL • 192.168.1.33:5555 • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome            • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server        • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by Piinks** [comment] 2020-04-03 21:06
This looks like it may be a floating point error with the alignment of the `FlexibleSpace`'s `title`. 

The little line is the bottom of the image (the `background`), and the white `Container` used for the `title` (`Stack`ed on top) is supposed to be aligned to the bottom of it. 

It looks like it is slightly off as it stretches.

**Comment by ozburo** [comment] 2020-04-05 13:48
I just noticed this too and thought I was losing my mind :sweat_smile:

**Comment by Piinks** [comment] 2020-04-06 16:43
I think I may have a workaround, I'll put it here once I verify. :)

**Comment by Piinks** [comment] 2020-04-06 18:47
Better yet, I have a fix. Just need to write a test. I'll link the PR once i's ready. :)

**Comment by Piinks** [comment] 2020-04-06 20:55
This PR has the fix: https://github.com/flutter/flutter/pull/54137

**Comment by Piinks** [comment] 2020-04-07 23:04
Update: The fix appears to be device dependent in its current state. Still continuing to investigate, though on the PR @HansMuller provided some resources for this:

> This does look like the kind of antialiasing issue that's introduced by trying to stack containers in one color on a background with a strongly contrasting color. The problem occurs because of the mapping from logical pixels to device pixels. There's an open issue for a documentation fix: #14288
> 
> More info about the problem can be found here:
> #14288 (comment)
> #17084 (comment)
> #15035 (comment)

**Comment by Piinks** [comment] 2020-04-14 23:08
So this fix I thought I had was not actually a fix. : \ 
This appears to actually be an anti-aliasing bug. The issues listed above are similar instances of this bug (and #54370).
Workarounds have been discussed in #25009

**Comment by VladyslavBondarenko** [comment] 2020-07-31 08:58
Reproduces with current master `1.21.0-6.0.pre.129`

<img width=400 src="https://user-images.githubusercontent.com/17024977/89018776-03400780-d325-11ea-960e-078be9751dd5.png" />

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.129, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.129 at /Users/nevercode/dev/flutter
    • Framework revision 30aef0a3b9 (12 hours ago), 2020-07-30 14:20:21 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

Duplicate of https://github.com/flutter/flutter/issues/37578

**Comment by Piinks** [comment] 2020-08-03 18:09
Since this is a duplicate, I am going to close it. The other issue has several upvotes, which will do better to increase the priority of this issue. #14288 is the larger, comprehensive issue for AA.

**Closed by Piinks** 2020-08-03 18:09 UTC
Labels: P4, a: quality, f: material design, f: scrolling, found in release: 1.21, framework, has reproducible steps
