### ISSUE TITLE
Horizontal scrollbar becomes invalid and does not disappear after increasing the width of the screen.

### ISSUE THREAD

**Issue by KristofHorvath** [flutter/flutter#78009] opened 2021-03-12 08:59 UTC
## Steps to Reproduce
Use this snippet to reproduce the malfunction:
```
class TestScreen extends StatefulWidget {
  TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  final scrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'.tr),
      ),
      body: RawScrollbar(
        isAlwaysShown: true,
        controller: scrollController,
        child: SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          controller:scrollController,
          child: Row(
            children: Iterable.generate(15, (i) => Text('Test$i ')).toList(),
          ),
        )
      ),
    );
  }
}
```

**Expected results:** If you resize the screen smaller (on web) or rotate it from horizontal to vertical (on mobile) then the scrollbar appears. If you resize it back, then the scrollbar disappears.

**Actual results:** If the scrollbar appeared once and you increase the width of the screen, the scrollbar remains visible in an invalid state.

Note: I'm using sound null safety now; however, the issue had already existed before flutter 2.0.

<details>
  <summary>Logs</summary>

`flutter run --verbose` does not produce any relevant information, nothing is displayed during the resizing process.

`flutter analyze` couldn't find any problem.

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.804], locale hu-HU)
    • Flutter version 2.0.1 at C:\Code\flutter
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Asus\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.54.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```

</details>

**Comment by xu-baolin** [comment] 2021-03-12 09:24
This may be the same issue as #75613
The Scrollbar can only update right now when it receives a scroll notification, so if scrolling has not occurred, it does not have new scroll metrics to update with.

**Comment by KristofHorvath** [comment] 2021-03-12 09:44
You are probably right. I've found your PR - have you checked my code with your patch?

**Comment by xu-baolin** [comment] 2021-03-12 09:55
The PR is in progress, I will check if the patch works on your issue.

**Comment by pedromassangocode** [comment] 2021-03-12 10:12
Closing as duplicate of https://github.com/flutter/flutter/issues/75613. Please follow up on that issue and subscribe for updates.
Thank you

**Closed by pedromassangocode** 2021-03-12 10:12 UTC
Labels: in triage
