### ISSUE TITLE
textpainter.layout will block ui,can not use isolate.have any plugin to resolver it

### ISSUE THREAD

**Issue by leetomlee123** [flutter/flutter#62109] opened 2020-07-23 08:34 UTC

**Comment by TahaTesser** [comment] 2020-07-23 10:37
This might help https://github.com/flutter/flutter/issues/30604#issuecomment-526013977  
Closing as duplicate of https://github.com/flutter/flutter/issues/30604

**Closed by TahaTesser** 2020-07-23 10:37 UTC
