### ISSUE TITLE
Support "Return" key in multiline text fields

### ISSUE THREAD

**Issue by sclee15** [flutter/flutter#11460] opened 2017-08-01 06:06 UTC
## Steps to Reproduce

- Make a text field and run the app
- Tap the field and type
- There's no way to press enter to input multi line message

But i do see maxlines. but even if i set it, the keyboard is not allowing to enter multi line messages.

**Comment by gspencergoog** [comment] 2017-09-13 16:03
Duplicate of #8028

**Closed by gspencergoog** 2017-09-13 16:03 UTC
Labels: prod: engine, prod: text input
