### ISSUE TITLE
URGENT: - After upgrading flutter to 3.22.0, not able to build android project

### ISSUE THREAD

**Issue by ritesh-121** [flutter/flutter#153292] opened 2024-08-12 16:25 UTC
### Steps to reproduce

Trying to run project and got this error.

### Actual results

```
android\app\src\debug\AndroidManifest.xml Error:
	Attribute application@allowBackup value=(false) from (unknown)
	is also present at [com.appsflyer:af-android-sdk:6.14.0] AndroidManifest.xml:32:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:41:5-94:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processSit2DebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 56s
Error: Gradle task assembleSit2Debug failed with exit code 1
```

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

```
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] Connected device (4 available)
[√] Network resources
```

**Comment by danagbemava-nc** [comment] 2024-08-13 07:31
You are specifying conflicting values in your manifest file. This is likely due to a conflict in some of your dependencies. You should open your `android` directory in android studio and open the `AndroidManifest.xml` file and look for the `merged manifest` to see which values are conflicting. 

You can also try the suggestion in the error 

```
Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:41:5-94:19 to override.
```

Given that this is caused by a conflict in the manifest values from your dependencies, you will need to resolve this yourself.

Closing from here as this is not a flutter issue.

Thank you

**Closed by danagbemava-nc** 2024-08-13 07:31 UTC
Labels: in triage
