### ISSUE TITLE
Failing integration test due to system dialogs

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#140987] opened 2024-01-04 22:30 UTC
### Type of Request

bug

### Infrastructure Environment

Github, LUCI, flutter/packages

### What is happening?

The `file_selector_android` integration test was failing often and was seemingly fixed by closing any system dialogs before running a test: https://github.com/flutter/packages/pull/5805. 

The flakiness seems to have started some time after moving the Android Emulator to API 34: https://github.com/flutter/packages/pull/5218. However it recently started failing more consistently. 

Other Android plugin integration tests may also be flaking due to this. I'm also not entirely sure if this is an issue with infra, Android 34, or Flutter integration tests.

Related link: https://stackoverflow.com/questions/39457305/android-testing-waited-for-the-root-of-the-view-hierarchy-to-have-window-focus

### Steps to reproduce

Running the integration tests in `file_selector_android` on CI without the changes made in https://github.com/flutter/packages/pull/5805. The test seems to always pass when ran locally.

To run it locally after downloading the `flutter/packages` repo
```
cd packages/file_selector/file_selector_android/example
flutter build apk
cd android
./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=io.flutter.plugins.DartIntegrationTest
```

### Expected results

The tests should pass, but it ends with error: 

```
dev.flutter.packages.file_selector_android_example.FileSelectorAndroidTest > openImageFile[android_34_google_apis_x64(AVD) - 14] [31mFAILED [0m
    androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
    Root{application-window-token=android.view.ViewRootImpl$W@c8cc8b3, window-token=android.view.ViewRootImpl$W@c8cc8b3, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030001
```

It seems unnecessary that we would have to clear system dialogs before each test.

**Comment by bparrishMines** [comment] 2024-01-04 22:32
cc @stuartmorgan @camsim99 fyi

**Comment by stuartmorgan** [comment] 2024-01-05 00:16
> I'm also not entirely sure if this is an issue with infra, Android 34, or Flutter integration tests.

The fact that this became extremely bad sometime in the last few weeks without any apparently related change on our side suggests something likely changed on the infra side that caused dialogs to appear in emulators in CI.

**Comment by stuartmorgan** [comment] 2024-01-05 11:47
TBD whether this is also causing the really bad `quick_actions` flake that started at about the same time.

**Comment by camsim99** [comment] 2024-01-05 18:52
> TBD whether this is also causing the really bad `quick_actions` flake that started at about the same time ([example](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8759754005542471617/+/u/Run_package_tests/native_integration_tests/stdout)).

I wonder about this too but do want to note that it was flaking before starting to run in on API 34 emulators as well, just to a significantly lesser extent.

**Comment by gmackall** [comment] 2024-01-11 19:12
assigning to @reidbaker for investigation as to why the system dialogues started appearing in the first place

**Comment by stuartmorgan** [comment] 2024-01-12 17:29
Does that mean the emulators are not reset (even just a cold reboot) at all? https://github.com/flutter/flutter/issues/137555#issuecomment-1811442582 indicated that emulators shouldn't have persistent state like that.

**Comment by reidbaker** [comment] 2024-01-12 17:53
In this case I am imagining a system dialog that says "do you want to update" or even "new update for google play available" then when you dismiss it hides the notification for some period of time. That could be server persisted state. It is also possible that the emulators are launched from a "cold" state but not from a fresh reboot. That is pretty common for emulators that are used when developing. Meaning the dialog would have been dismissed and the device is not turned off. 

Still trying to reproduce but no luck so far.

**Comment by reidbaker** [comment] 2024-01-12 18:32
https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_shard_1%20master/4350/overview

**Comment by reidbaker** [comment] 2024-01-12 18:33
https://g3doc.corp.google.com/company/teams/flutter/infrastructure/playbook.md?cl=head#ssh-to-a-mac-machine-hosted-by-chromium

**Comment by reidbaker** [comment] 2024-01-12 19:22
6+ pushes with the fixed cls reverted and cannot get this to reproduce. Additionally I am running into undocument access controls to even ssh into the chromium machines. 

Closing as fixed since we cant reproduce.

**Closed by reidbaker** 2024-01-12 19:22 UTC
Labels: team-infra, P1, p: file_selector, p: espresso

**Comment by stuartmorgan** [comment] 2024-01-12 21:02
Do we want to revert the workarounds so we see it if this happens again, or leave them in to minimize the chances of this happening again?

**Comment by reidbaker** [comment] 2024-01-16 16:04
I think leave them in to minimize this impacting us if it happens again. Dismissing dialogs should not cause issues in those tests since we do not intentionally pop dialogs.
