### ISSUE TITLE
Should pass the Locale from Localizations to Text/RichText/etc to painting.TextStyle to ui.TextStyle

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16408] opened 2018-04-10 05:33 UTC

**Comment by Hixie** [comment] 2018-04-10 05:34
cc @HansMuller who worked on i18n
cc @gspencergoog who may enjoy this one

**Comment by najeira** [comment] 2018-05-11 08:08
Font selection is a very important thing for Japan and China. I sincerely hope that the font selection by language works fine.

I think that this issue is related to font selection. I expect that this issue will be fixed.

**Comment by eseidelGoogle** [comment] 2018-05-23 16:18
My understanding from @najeira's article:
https://medium.com/@najeira/flutter-and-cjk-font-selection-5dbc6a6164ba
is that this is a regression as part of moving to libtxt from blink?

@jason-simmons

**Comment by Hixie** [comment] 2018-05-23 22:49
This has never worked correctly in Flutter.

**Comment by eseidelGoogle** [comment] 2018-05-23 23:16
OK.  Is the correct understanding of https://medium.com/@najeira/flutter-and-cjk-font-selection-5dbc6a6164ba that the workaround for this bug(?) which worked with blink no longer works with libtxt?  Looks like @najeira is currently building a custom engine to enable blink. :)

**Comment by Hixie** [comment] 2018-05-23 23:29
I'm sure some equivalent workaround could be made to work, but that kind of workaround (pretty much anything involving building one's own engine) is definitely not supported use of the API.

The correct fix is to propagate the locale and the text direction together from the framework to the engine. I believe @HansMuller is looking at this as we speak.

**Comment by HansMuller** [comment] 2018-05-23 23:37
I am indeed.

**Comment by najeira** [comment] 2018-05-24 01:34
Thank you for reading my article!

It is not regression. My patch just does not work on the new libtxt.

**Closed** 2018-05-31 18:01 UTC
Labels: a: internationalization, a: typography, framework, severe: new feature
