### ISSUE TITLE
Flutter [Web] [iOS] [CanvasKit] Issue with Video player not displaying when widget tree parent has a ClipRRect

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#90270] opened 2021-09-17 14:24 UTC
Hi,

A bit of a strange one - on Web iPadOS and iOS when using CanvasKit (HTML renderer is fine) and the plugin Feedback any HTMLVideoElements are shown as a blank square, and you can start the video with touch and hear the sound. There doesn't appear to be any errors that I can see or trap with Sentry.

I am aware the trigger is related to an external plugin but since the plugin itself appears to be working correctly and the issue only occurs with iPadOS and iOS and is fine with Android and Desktop including Mac, it looks like it maybe related to something in the Flutter Canvaskit itself?

Expected as seen on Desktop Web and Android Web: 
![image](https://user-images.githubusercontent.com/81489824/133797819-7da0b0c4-9877-436d-b3c9-73380135f4db.png)

iPadOS:
![image](https://user-images.githubusercontent.com/81489824/133798402-dc0e1d9f-6be9-4e72-9317-8d00c47ed50b.png)

I couldn't find a version of the Flutter framework including from 2.2.3 onwards that would work.

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:convert';
import 'dart:ui' as ui;

import 'dart:html';
import 'package:feedback/feedback.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print('in build');
    return BetterFeedback(
      child: MaterialApp(
        home: Scaffold(
          backgroundColor: Colors.grey,
          body: Center(
            child: Container(color: Colors.blue, height: 300, width: 300, child: WebVideoElement('1')),
          ),
        ),
      ),
    );
  }
}

class WebVideoElement extends StatefulWidget {
  const WebVideoElement(this.src);

  final String src;
  final double startAt = 0;
  final bool autoplay = false;
  final bool controls = true;

  @override
  _WebVideoElementState createState() => _WebVideoElementState();
}

class _WebVideoElementState extends State<WebVideoElement> {
  @override
  String? URL;

  void initState() {
    URL = 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4#t=${widget.startAt}';
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // Do not remove the below comment - Fix for missing ui.platformViewRegistry in dart.ui
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(widget.src, (int viewId) {
      //https: //api.flutter.dev/flutter/dart-html/VideoElement-class.html
      final video = VideoElement()
        ..src = URL!
        ..autoplay = widget.autoplay
        ..controls = widget.controls
        ..style.border = 'none'
        ..style.borderColor = 'red'
        ..style.height = '100%'
        ..style.width = '100%';

      // Allows Safari iOS to play the video inline
      video.setAttribute('playsinline', 'true');
      return video;
    });
    return HtmlElementView(
      viewType: widget.src,
    );
  }
}
```

</details>

<details> 
<summary>flutter doctor</summary> 

```console
[√] Flutter (Channel master, 2.6.0-6.0.pre.130, on Microsoft Windows [Version 10.0.17763.2183], locale en-IE)
    • Flutter version 2.6.0-6.0.pre.130 at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a11f858e80 (5 hours ago), 2021-09-17 05:32:02 -0400
    • Engine revision 9788fb4b13
    • Dart version 2.15.0 (build 2.15.0-118.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-09-17 15:15
Hi @zambetpentru 
I just tried code sample using `flutter build web --web-renderer canvaskit` on iPad.  Using both `stable` & `master`.


![IMG_2909D02676AC-1](https://user-images.githubusercontent.com/48603081/133806658-216d8416-3831-4f17-8e3c-d290941303c6.jpeg)


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (9 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile)   • 00008020-000255113EE8402E            • ios            • iOS 15.0 19A344
    • iPhone 11 Pro (mobile) • A9530DDA-3DB6-4737-BD67-26506428926F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.82
    ! Error: Taha’s iPad is busy: Fetching debug symbols for Taha’s iPad. Xcode will continue when Taha’s iPad is finished. (code -10)

! Doctor found issues in 1 category.

```
	
</details>

**Comment by zambetpentru** [comment] 2021-09-17 15:42
Well that is interesting! I dug into it further and found the widget that is causing it so now I have a repo without any plugins:

I am on ios 14.7.1 and I was using the same build command as you.

<details> 
<summary>minimal code sample</summary> 


import 'dart:ui' as ui;
import 'dart:html';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 300),
  );

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print('in build');

    final scaleAnimation = Tween<double>(begin: 1, end: 0.65).chain(CurveTween(curve: Curves.easeInSine)).animate(_controller);
    final animation = Tween<double>(begin: 0, end: 1).chain(CurveTween(curve: Curves.easeInSine)).animate(_controller);

    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.grey,
        body: Center(
          child: Transform.scale(
            alignment: Alignment(
              -0.3 * animation.value,
              -0.65 * animation.value,
            ),
            scale: scaleAnimation.value,
            child: ClipRRect(
              borderRadius: BorderRadius.all(
                Radius.circular(
                  20 * animation.value,
                ),
              ),
              child: Container(
                color: Colors.lightBlue,
                height: 300,
                width: 300,
                child: WebVideoElement('1'),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

///Working well in Windows, Linux, MacOS, iOS and Android Mobile Web / PWA
class WebVideoElement extends StatefulWidget {
  const WebVideoElement(this.src);

  final String src;
  final double startAt = 0;
  final bool autoplay = false;
  final bool controls = true;

  @override
  _WebVideoElementState createState() => _WebVideoElementState();
}

class _WebVideoElementState extends State<WebVideoElement> {
  @override
  String? URL;

  void initState() {
    URL = 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4#t=${widget.startAt}';
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // Do not remove the below comment - Fix for missing ui.platformViewRegistry in dart.ui
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(widget.src, (int viewId) {
      //https: //api.flutter.dev/flutter/dart-html/VideoElement-class.html
      final video = VideoElement()
        ..src = URL!
        ..autoplay = widget.autoplay
        ..controls = widget.controls
        ..style.border = 'none'
        ..style.borderColor = 'red'
        ..style.height = '100%'
        ..style.width = '100%';

      // Allows Safari iOS to play the video inline
      video.setAttribute('playsinline', 'true');
      return video;
    });
    return HtmlElementView(
      viewType: widget.src,
    );
  }
}

</details>

**Comment by TahaTesser** [comment] 2021-09-20 08:19
Hi @zambetpentru 
Thanks for the reproducible code sample.  I can reproduce the issue with `ClipRRect` code sample on iOS Safari and macOS Safari (doesn't reproduce on chrome on Apple devices or on non-apple devices). Only audio is played, while  `HtmlElementView` view is blank. 

Looks like this is the same as https://github.com/flutter/flutter/issues/79550, where ClipRRect is probably using clip path in Safari

Indeed the issue is only on cavaskit

Reproduced on the `web` using the following `--web-renderer`s
|  `chrome`  |  canvaskit  | html | 
| :---: | :---: | :---: |
debug | ✅ | ❗️ |



### Reproducible code sample

<details> 
<summary>complete minimal runnable code sample</summary>

```dart
import 'dart:ui' as ui;
import 'dart:html';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 300),
  );

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final animation = Tween<double>(begin: 0, end: 1).chain(CurveTween(curve: Curves.easeInSine)).animate(_controller);

    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.grey,
        body: Center(
          child: ClipRRect(
            child: Container(
              color: Colors.lightBlue,
              height: 300,
              width: 300,
              child: WebVideoElement('1'),
              //  ),
            ),
          ),
        ),
      ),
    );
  }
}

///Working well in Windows, Linux, MacOS, iOS and Android Mobile Web / PWA
class WebVideoElement extends StatefulWidget {
  const WebVideoElement(this.src);

  final String src;
  final double startAt = 0;
  final bool autoplay = false;
  final bool controls = true;

  @override
  _WebVideoElementState createState() => _WebVideoElementState();
}

class _WebVideoElementState extends State<WebVideoElement> {
  @override
  String? URL;

  void initState() {
    URL = 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4#t=${widget.startAt}';
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // Do not remove the below comment - Fix for missing ui.platformViewRegistry in dart.ui
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(widget.src, (int viewId) {
      //https: //api.flutter.dev/flutter/dart-html/VideoElement-class.html
      final video = VideoElement()
        ..src = URL!
        ..autoplay = widget.autoplay
        ..controls = widget.controls
        ..style.border = 'none'
        ..style.borderColor = 'red'
        ..style.height = '100%'
        ..style.width = '100%';

      // Allows Safari iOS to play the video inline
      video.setAttribute('playsinline', 'true');
      return video;
    });
    return HtmlElementView(
      viewType: widget.src,
    );
  }
}
``` 

</details>

### Preview

| iOS Safari | macOS Safari |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/133973655-f6f8d5e3-2e39-4ebb-8c0f-66d879e5012e.png" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/133973664-2c3b7428-2396-406a-9d4e-265fe994923c.PNG" height="450" /> |



### Logs

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (3 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 15.0 19A344
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.147, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.147 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83dfb2237a (2 days ago), 2021-09-17 23:48:04 -0400
    • Engine revision 31792e0340
    • Dart version 2.15.0 (build 2.15.0-120.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 15.0 19A344
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 1 category.
```
		
</details>

✅: No Issue ❗️: Issue reproduced

Thanks for filing the issue

Closing as duplicate of https://github.com/flutter/flutter/issues/79550

**Closed by TahaTesser** 2021-09-20 08:19 UTC
Labels: in triage
