### ISSUE TITLE
Keyboard resets to alphabetic mode upon changing text using TextEditingController in TextField in Android

### ISSUE THREAD

**Issue by viplavrawal** [flutter/flutter#53734] opened 2020-04-01 07:47 UTC
The keyboard in android resets to alphabet mode when text is changed using TextEditingController. Please find the below minimal code to reproduce this issue.

## Steps to Reproduce

1. Run the app with the below code in android.
2. Change the keyboard type to digit mode.
3. Enter any character from the digit mode.

**Expected results:** The keyboard type should remain in digit mode

**Actual results:** The keyboard type changes to alphabetic mode

```
import 'package:flutter/material.dart';

class AppLoginPage extends StatefulWidget {
  AppLoginPage({Key key}) : super(key: key);

  @override
  _AppLoginPageState createState() => _AppLoginPageState();
}

class _AppLoginPageState extends State<AppLoginPage> {
  final _controller = TextEditingController();

  _onTextChanged(String text) {
    _controller.value = _controller.value.copyWith(
        text: text + "0",
        selection:
            TextSelection.fromPosition(TextPosition(offset: text.length + 1)),
        composing: TextRange.empty);
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Scaffold(
        body: Center(
          child: Padding(
            padding: EdgeInsets.all(20),
            child: TextField(
              controller: _controller,
              onChanged: (text) {
                _onTextChanged(text);
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

![ezgif-6-e1d266a34479](https://user-images.githubusercontent.com/13478203/78113763-d84cb200-741d-11ea-86d3-cfbf5923d101.gif)

One possible solution would be to change the keyboardType to `TextInputType.number` but that's not possible in our case as we need both integers and characters in this field.

## Flutter doctor
`[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87,`
`    locale en-IN)`
`[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)`
`[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)`
`[✓] Android Studio (version 3.5)`
`[✓] VS Code (version 1.42.1)`
`[✓] Connected device (2 available)`

**Comment by TahaTesser** [comment] 2020-04-01 08:37
Hi @viplavrawal 
I have tried to reproduce this issue on stable, it does exist, gboard's keyboard resets but testings on dev channel doesn't reproduce the issue. It seems to be  fixed in dev channel

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.16.4-pre.33, on Mac OS X 10.15.4 19E266, locale
    en-GB)
    • Flutter version 1.16.4-pre.33 at /Users/taha/Code/flutter_dev
    • Framework revision aee9e94c21 (33 hours ago), 2020-03-30 16:12:40 -0700
    • Engine revision c779894d08
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E266
    • Chrome        • chrome                    • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server    • web-server                • web-javascript • Flutter Tools

• No issues found!
```

There is no need of keeping the issue open if it's already fixed
if you're still experiencing latest dev channel, comment  below and  I will reopen it
Thank you

**Closed by TahaTesser** 2020-04-01 08:37 UTC
