### ISSUE TITLE
"Getting started..." app crashes on Android 5.0.1

### ISSUE THREAD

**Issue by kicune** [flutter/flutter#85410] opened 2021-06-27 14:04 UTC
Hello,

I encountered a problem with my Flutter app I need to run on an older Android device w/ Android 5.0.1 (API lvl 21). Then the same problem manifested even with a brand new “Getting started with Flutter” application: the app stops and ​the “Unforutnately, [app name] has stopped.” dialog is shown. It crashes both on physical device and on emulator, although no error or exception (AFAIK) can be seen in the logs.

On the emulator with API lvl 22 (Android 5.1) the same app runs without any problems.
​It also runs normally on the physical device with Android 9 on it.
I was able to replicate the behavior on both stable and beta channel.

## Steps to Reproduce
1. Android Studio: Create new Flutter App
2. Run the app on the Android API v21 device or emulator 
3. "Unfortunately, [app name] has stopped." dialog is displayed.

**Expected results:**
Basic "Getting started with Flutter" app

**Actual results:**
The app stops and the dialog is displayed.

<details>
  <summary>Logs</summary>

```
$ flutter run --verbose
[  +88 ms] executing: sysctl hw.optional.arm64
[  +17 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +7 ms] executing: [/Users/lisak/Projects/tools/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] executing: [/Users/lisak/Projects/tools/flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[  +20 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] 2.2.2
[   +6 ms] executing: [/Users/lisak/Projects/tools/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/lisak/Projects/tools/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +123 ms] executing: [/Users/lisak/Projects/tools/flutter/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +5 ms] executing: sw_vers -productName
[  +12 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.4
[        ] executing: sw_vers -buildVersion
[  +14 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20F71
[  +60 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb devices -l
[  +11 ms] executing: sysctl hw.optional.arm64
[   +4 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[   +8 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[        ] Xcode not found. Run 'flutter doctor' for more information.
[   +1 ms] executing: xcrun xcodebuild -version
[   +7 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[  +36 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:14
[   +7 ms] /Users/lisak/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +27 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] executing: xcrun xcodebuild -version
[   +8 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[  +60 ms] Skipping pub get: version match.
[ +105 ms] Generating /Users/lisak/Projects/test/test4/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +49 ms] ro.hardware = ranchu
[  +12 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +25 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +4 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[   +5 ms] /Users/lisak/Projects/tools/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/lisak/Projects/tools/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/lisak/Projects/tools/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /var/folders/wg/g12lq2ld4yj1hcgbh9nmdj680000gn/T/flutter_tools.xUA9L9/flutter_tool.12PMWp/app.dill --packages
/Users/lisak/Projects/test/test4/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +12 ms] executing: /Users/lisak/Library/Android/sdk/build-tools/30.0.2/aapt dump xmltree /Users/lisak/Projects/test/test4/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +8 ms] Exit code 0 from: /Users/lisak/Library/Android/sdk/build-tools/30.0.2/aapt dump xmltree /Users/lisak/Projects/test/test4/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.test4" (Raw: "com.example.test4")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="test4" (Raw: "test4")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.test4.MainActivity" (Raw: "com.example.test4.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +8 ms] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +16 ms] <- compile package:test4/main.dart
[  +23 ms] --------- beginning of system
           06-27 15:55:27.874 D/TaskPersister( 1528): removeObsoleteFile: deleting file=12_task_thumbnail.png
[  +17 ms] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb version
[  +17 ms] Android Debug Bridge version 1.0.41
           Version 31.0.2-7242960
           Installed as /Users/lisak/Library/Android/sdk/platform-tools/adb
[   +2 ms] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb start-server
[  +45 ms] Building APK
[  +21 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from /Users/lisak/Projects/test/test4/android/gradlew.
[  +98 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[   +9 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/li
b\/jna.jar","JVMVersion":"1.8*,1.8+","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio4.2","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.vendor.name":"Google","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An
application in Android Studio requests access to the user's Desktop folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-202.7660.26.42.7351085","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in Android Studio requests access to the device's
camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"4.2","NSMi
crophoneUsageDescription":"An application in Android Studio requests access to the device's microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","L
SMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android Studio requests access to the user's Documents folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio requests access to the user's Downloads
folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a network volume.","CFBundleGetInfoString":"Android Studio 4.2, build AI-202.7660.26.42.7351085. Copyright JetBrains s.r.o., (c) 2000-2021","NSRemovableVolumesUsageDescription":"An application in
Android Studio requests access to files on a removable volume."}
[   +6 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +95 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6916264, mixed mode)
[   +1 ms] executing: [/Users/lisak/Projects/test/test4/android/] /Users/lisak/Projects/test/test4/android/gradlew -Pverbose=true -Ptarget-platform=android-x86 -Ptarget=/Users/lisak/Projects/test/test4/lib/main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1024 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +81 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +297 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +94 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[        ] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[  +20 ms] BUILD SUCCESSFUL in 1s
[        ] 32 actionable tasks: 4 executed, 28 up-to-date
[ +364 ms] Running Gradle task 'assembleDebug'... (completed in 2,098ms)
[  +35 ms] calculateSha: LocalDirectory: '/Users/lisak/Projects/test/test4/build/app/outputs/flutter-apk'/app.apk
[ +472 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +4 ms] executing: /Users/lisak/Library/Android/sdk/build-tools/30.0.2/aapt dump xmltree /Users/lisak/Projects/test/test4/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[  +14 ms] Exit code 0 from: /Users/lisak/Library/Android/sdk/build-tools/30.0.2/aapt dump xmltree /Users/lisak/Projects/test/test4/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.test4" (Raw: "com.example.test4")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="test4" (Raw: "test4")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.test4.MainActivity" (Raw: "com.example.test4.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +5 ms] Stopping app 'app.apk' on Android SDK built for x86.
[   +1 ms] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.example.test4
[ +342 ms] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.example.test4
[ +318 ms] package:com.example.test4
[   +2 ms] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.test4.sha1
[  +15 ms] e143f9bc4bd26f76aaf6a929bf128a4e17b6562b
[        ] Latest build already installed.
[        ] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +15 ms] --------- beginning of main
           06-27 15:55:56.847 D/AndroidRuntime( 5234): Shutting down VM
[  +13 ms] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.test4/com.example.test4.MainActivity
[ +332 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.test4/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +253 ms] Observatory URL on device: http://127.0.0.1:33763/v5KdtKh5Ycc=/
[   +1 ms] executing: /Users/lisak/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:33763
[  +10 ms] 53875
[        ] Forwarded host port 53875 to device port 33763 for Observatory
[+2917 ms] Caching compiled dill
[  +31 ms] Connecting to service protocol: http://127.0.0.1:53875/v5KdtKh5Ycc=/
[ +239 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:53875/v5KdtKh5Ycc=/.
[  +68 ms] DDS is listening at http://127.0.0.1:53883/r6IeOlowmB0=/.
[  +52 ms] Successfully connected to service protocol: http://127.0.0.1:53875/v5KdtKh5Ycc=/
[+2975 ms] Caching compiled dill
[  +30 ms] Connecting to service protocol: http://127.0.0.1:54108/OwAFEG_WVtA=/

[ +214 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:54108/OwAFEG_WVtA=/.
[  +78 ms] DDS is listening at http://127.0.0.1:54116/ZvuDaL-vcuk=/.
[  +54 ms] Successfully connected to service protocol: http://127.0.0.1:54108/OwAFEG_WVtA=/
```
Dialog "Unfortunately, test4 has stopped" is displayed. After clicking on "OK", the process in the terminal runs on without any further output.

```
$ flutter analyze
Analyzing test4...                                                      
No issues found! (ran in 8.4s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.2 at /Users/lisak/Projects/tools/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/lisak/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS 
(...) _- I don't develop the iOS apps atm._

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 5.0.2 (API 21) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 91.0.4472.114

```

</details>

Best Regards,
Jan

**Comment by janithcooray** [comment] 2021-06-27 16:06
Please state more info about the device you are testing on. (Physical or Virtual, CPU Arch, Ram, Manufacture). And Flutter version.

**Comment by kicune** [comment] 2021-06-27 17:47
I've tested it both on virtual device (emulator) and physical one:
Virtual device (emulator): 7" WSVGA Tablet, Android 5.0 x86, 600x1024mdpi, 512MB RAM, 48MB VM Heap, internal storage 800MB
Physical device: Lenovo IdeaTab S8-50F, Tablet 8" 1920x1200, Intel Atom Z3745 1.86 GHz, 2GB DDR3, 16GB eMMC, Android 5.0.1

On both occasion the app behaved as described above (the app stopped immediately after installation).

**Comment by TahaTesser** [comment] 2021-06-28 13:58
HI @kicune
This is a known issue, https://github.com/flutter/flutter/issues/73118 probably fixed it
Can you please upgrade to the latest  `master` and try again or wait for the fix the reach stable channel as this is quite an old version of Android with a very low userbase

Execute the following commands to upgrade
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Closing as duplicate of https://github.com/flutter/flutter/issues/73118

**Closed by TahaTesser** 2021-06-28 13:58 UTC
Labels: in triage
