### ISSUE TITLE
Put Row widget on trailing attributes in ListTile widget but got exception

### ISSUE THREAD

**Issue by kurakurakuda** [flutter/flutter#101636] opened 2022-04-09 13:44 UTC
I put this Row widget on ListTile such below and got exception and widget is not described on screen
Sample Code
```
ListTile(
                    title: Text(ingredient.name!),
                    trailing: Row(
                        children: <Widget>[
                          Icon(Icons.flight),
                          Icon(Icons.flight_land)
                        ])
                  )
```

Exception I got
```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderCustomPaint#4ec2d relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1982 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Card Card:file:///C:/Users/kris3/StudioProjects/shopping_with_checkmark/lib/view/card/meal_planning_card.dart:27:12
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1982:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117:21)
#4      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#6      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#10     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#11     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#12     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#14     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#15     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#16     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#23     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#26     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#28     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#36     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:213:28)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#38     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#39     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#40     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#57     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#61     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#62     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
#63     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#64     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#69     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#72     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731:7)
#73     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#74     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#75     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#76     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#77     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#78     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#79     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#83     _invoke (dart:ui/hooks.dart:151:10)
#84     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#85     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderPhysicalShape#e7c11 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=387.4, 0.0<=h<=Infinity)
...  size: MISSING
...  elevation: 6.0
...  color: Color(0xfff5f5f5)
...  shadowColor: Color(0xfff5f5f5)
...  clipper: ShapeBorderClipper
RenderObject: RenderPhysicalShape#e7c11 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=387.4, 0.0<=h<=Infinity)
  size: MISSING
  elevation: 6.0
  color: Color(0xfff5f5f5)
  shadowColor: Color(0xfff5f5f5)
  clipper: ShapeBorderClipper
...  child: RenderCustomPaint#4ec2d relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=387.4, 0.0<=h<=Infinity)
...    size: MISSING
...    painter: null
...    foregroundPainter: _ShapeBorderPainter#397e8()
...    child: _RenderInkFeatures#6429f relayoutBoundary=up16 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=387.4, 0.0<=h<=Infinity)
...      size: MISSING
...      child: RenderSemanticsAnnotations#9a0c9 relayoutBoundary=up17 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=387.4, 0.0<=h<=Infinity)
...        size: MISSING
...        child: RenderDecoratedBox#11094 relayoutBoundary=up18 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=387.4, 0.0<=h<=Infinity)
...          size: MISSING
...          decoration: BoxDecoration
...            color: Color(0x00000000)
...            border: Border(top: BorderSide(Color(0x00000000), 1.0, BorderStyle.solid), bottom: BorderSide(Color(0x00000000), 1.0, BorderStyle.solid))
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#e3407(), devicePixelRatio: 2.6, locale: en, textDirection: TextDirection.ltr, platform: android)
====================================================================================================
```

Flutter doctor in my local
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19043.1586], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.66.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by danagbemava-nc** [comment] 2022-04-11 09:21
Hi @kurakurakuda, this is working as intended. The `Row` you have put there is trying to take up as much size as it can, which is making the calculation of the size for the trailing widget fail. 

You should be able to fix this by either setting the mainAxisSize of the row to `MainAxisSize.min` or wrapping the `Row` with a `SizedBox` and specifying a width for the sized box. 

Closing as this is working as intended. 

See https://api.flutter.dev/flutter/rendering/MainAxisSize.html#max and https://api.flutter.dev/flutter/rendering/MainAxisSize.html#min for more info. 

`code for mainAxisSize`

```dart
ListTile(
                  title: const Text('Test'),
                  trailing: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: const [
                      Icon(Icons.flight),
                      Icon(Icons.flight_land)
                    ],
                  ),
                ),
```

`code for SizedBox`

```dart
ListTile(
                  title: const Text('Test'),
                  trailing: SizedBox(
                    width: 60,
                    child: Row(
                      children: const [
                        Icon(Icons.flight),
                        Icon(Icons.flight_land)
                      ],
                    ),
                  ),
                ),
```

**Closed by danagbemava-nc** 2022-04-11 09:21 UTC
Labels: in triage
