### ISSUE TITLE
url_lauchner Provide  function to check if Launched URL is Running

### ISSUE THREAD

**Issue by boyi01** [flutter/flutter#58368] opened 2020-05-31 13:01 UTC
I use the url_lauchner to Open a Login  Page (in a Webbrowser)

Everything is easy when the user is doin'g the procedure succesful, i can find this out and use closeWebView() but i have no chance to check if it's still running, so if the user goes Back by itself...
just using the back button...

So it possible it would be awesome to have a function like checkWebView thgat return true as long a the the webview is open... is this possible?

**Comment by stuartmorgan** [comment] 2023-05-26 21:12
Closing as a duplicate of https://github.com/flutter/flutter/issues/20034, which is a better way of addressing the same use case (as it doesn't involve polling).

**Closed by stuartmorgan** 2023-05-26 21:12 UTC
Labels: new feature, plugin, p: url_launcher, proposal, passed first triage, P5
