### ISSUE TITLE
iOS: Issues with multiple flavors. command-line builds

### ISSUE THREAD

**Issue by eikebartels** [flutter/flutter#18342] opened 2018-06-10 14:40 UTC
Hello, 

Im having a couple of problems with flavors. Manly on iOS but also on Android. 

I have one code base for 2 different apps. Each app has a live and staging configuration. Each of this configuration has one for release and one for debug. 

My configuration in Xcode looks like: 
 
![screen shot 2018-06-10 at 16 10 46](https://user-images.githubusercontent.com/767979/41202398-e5e23380-6cc8-11e8-89bd-ceea994d8421.png)

![screen shot 2018-06-10 at 16 10 50](https://user-images.githubusercontent.com/767979/41202399-e89fd73a-6cc8-11e8-8a5d-4cc41a9ae188.png)

And my configuration in Android Studio looks like

![screen shot 2018-06-10 at 16 11 53](https://user-images.githubusercontent.com/767979/41202406-0d1b095e-6cc9-11e8-8353-251865627cf8.png)

# Things going wrong. 

1. I run app a from Android Studio. Then I wanna run app b. App b installs on simulator but app a starts. 
2. flutter does not take Xcode schema environment variables.
3. If I run `flutter build ios --release --flavor instructor_live --target lib/main_instructor_live.dart` Im getting errors like 

```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    In file included from /Users/eikebartels/Documents/driveddy/mobile/ios/Pods/Protobuf/objectivec/GPBWellKnownTypes.m:35:
    /Users/eikebartels/Documents/driveddy/mobile/ios/Pods/Protobuf/objectivec/GPBWellKnownTypes.h:40:10: fatal error: 'Protobuf/Any.pbobjc.h' file not found
     #import <Protobuf/Any.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Encountered error while building for device.
make: *** [build_instructor_live] Error 1

```

But archiving via Xcode works 

## Doctor output 
```
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-DE)
    • Flutter version 0.4.4 at /Users/eikebartels/Applications/flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/eikebartels/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
```

(Im still using cocoa pods v 4.0 because otherwise nothing works anymore.

**Comment by eikebartels** [comment] 2018-06-13 09:50
I found one issue related to point 1. 
When you run an app with a specific flavor you have to set `Use ... for command line builds`
![screen shot 2018-06-13 at 11 38 31](https://user-images.githubusercontent.com/767979/41343235-5263b894-6efe-11e8-8f58-9f1d6fe63b5e.png)

I think what needs to be changed somehow. Because this causes issue if you are working with different flavors and im not sure how it gonna behave on CI

**Comment by Caioflandau** [comment] 2018-07-02 21:34
+1 here. I'm having the same issue on iOS builds - especially point 1. Case is:

1. An app that can have two different versions (most common case being a staging and a production flavor)
1. Install one flavor and then the other
1. No matter which flavor I installed, Flutter will launch the one set in the "Use <configuration> for command-line builds"

It does build and install the right app, but when launching it on the iOS emulator it launches the wrong one.

**Comment by acudworth** [comment] 2018-07-06 21:46
Having this issue too - this is a very common workflow setup and needs to be addressed asap. Flutter should launch the app with bundle identifier that has just been built

**Comment by eikebartels** [comment] 2018-08-17 14:59
Regarding the `Use ... for command line builds` issue. You can make use of the ruby library https://github.com/CocoaPods/Xcodeproj to set the value via CI. 

Im using fastlane 

```
lane :build_beta do
    sh("./modify_pbxproj.sh Flavor1")
end 
```

My `modify_pbxproj.sh` file looks like: 
```
#!/bin/sh
P_PATH="../ios/Runner.xcodeproj"
ruby modify_pbxproj.rb $1 $P_PATH
```

And my `modify_pbxproj.rb` looks like 
```
require 'xcodeproj'

config = ARGV[0]
project_path = ARGV[1]
project = Xcodeproj::Project.open(project_path)
objectGroup = project.objects_by_uuid["97C147051CF9000F007C117D"]
puts "Old Config: #{objectGroup.default_configuration_name}"
objectGroup.default_configuration_name = config
puts "New Config: #{objectGroup.default_configuration_name}"
project.save(project_path)
```

Which this kind of dirty solution Im able to switch between different flavour configurations and build on CI

**Comment by Abgaryan** [comment] 2018-08-17 15:04
@eikebartels  good job.

**Comment by nashfive** [comment] 2018-09-30 10:14
Any update on this issue ? I also have this problem, the command line is trying to launch the wrong app in the simulator...

**Comment by leorachit** [comment] 2018-10-04 13:37
Please help on this.

**Comment by zoechi** [comment] 2019-02-13 08:29
Please check if #27691 fixes this as well

**Comment by martin-fink** [comment] 2019-03-20 08:32
Hi! I've run into the same problem on Flutter 1.2.1, channel stable.

`flutter run --flavor $flavor` builds and installs the correct version, but runs the one specified under "Use ... for command-line builds".

**Comment by mayurdhurpate** [comment] 2019-07-05 15:03
I tried setting up Flutter Flavor for iOS apps following this blog: https://www.tengio.com/blog/multiple-firebase-environments-with-flutter/ but even though the `Debug-dev` scheme seems to be running during `flutter run --flavor dev`, the resulting App always seem to run on my Production server. 

(Have added my Flutter verbose output for reference: http://pasted.co/7b85a2f9)
Option for `Use ... for command line builds` doesn't seem to work for me too.

Would be great if we can have an official way of setting up flavor on iOS and Android. Hoping that https://github.com/flutter/flutter/pull/32761 pull request might solve a few issues.

**Comment by maqoo** [comment] 2019-07-14 10:59
I am having the same issue here. We have multiple flavors which are represented with schemes in iOS project. Using command line `flutter build ios --flavor $flavor_name -t $target` does not produce the correct app version. The flavors work using `flutter run` though 🤔

**Comment by evelyne24** [comment] 2019-07-22 14:31
Confirmed. Same problem with `flutter run` running the wrong iOS build scheme.

**Comment by eseidelGoogle** [comment] 2019-07-22 18:59
I believe @jonahwilliams is looking at our underlying build infrastructure as we speak, which likely will affect our support of flavors: https://github.com/flutter/flutter/projects/35

**Comment by acudworth** [comment] 2019-07-22 21:16
Great to see this is being worked on - it's sorely needed for a lot of build setups!

**Comment by nickpnmrv** [comment] 2019-07-27 10:39
Is there a workaround?? My app uses flavors to separate prod and dev config for Firebase... Currently I can not start my app in with dev Firebase... blocks further development

**Comment by v7lin** [comment] 2019-08-02 08:07
How to add ios flavors appname for multiple languages

**Comment by aniket08485786** [comment] 2019-08-03 10:25
Any updates?
I am facing the same problem here.
Android Flavors are working properly but for iOS, it doesn't seem to work... 
I cant give different app name to each scheme/flavor in XCode

Also Please add proper documentation on flutter [Website](
https://flutter.dev/docs/deployment/flavors)... just dont link other people's blog in it..
it's rather confusing for people like me who are coming from the android background and who have no knowledge of XCode / iOS.

**Comment by mayurdhurpate** [comment] 2019-08-03 10:41
Hi @aniket08485786, I know that getting stuck with Flutter flavors might seem like a bottleneck, and lack of proper resources might add to the frustration, but I believe the team is super loaded with flooded traffic of devs like us finding bugs everywhere from small plugins to core foundation. 

With 'always helping' @zoechi and Flutter co-Founder & Lead @eseidel already monitoring this one with 10x devs like @jonahwilliams 😎 working on the underlying build infrastructure (can be tracked [here](https://github.com/flutter/flutter/projects/35)) I believe it's got quite an attention and is just a matter of time for it to be resolved. 

PS: Thanks to the Flutter team for such a wonderful project! ❤️

**Comment by mayurdhurpate** [comment] 2019-09-30 18:14
Any updates on this one? It's difficult to manage multiple environments (especially when using multiple Firebase projects for staging and production) to configure without using flavors.

**Comment by 0x6a6f74726f** [comment] 2019-10-01 07:50
As @eseidelGoogle already mentioned you can track progress at this project https://github.com/flutter/flutter/projects/35

**Comment by tasaquino** [comment] 2019-10-18 06:01
@eikebartels I have flavors/schemes configured in my project and could set the configuration using command line while building/archiving. Just pass the `-configuration`:

`xcodebuild -workspace ./Runner.xcworkspace -configuration Release-beta -scheme beta -destination 'generic/platform=iOS' -archivePath build/ios/iphoneos/Runner.xcarchive archive -allowProvisioningUpdates`

`xcodebuild -exportArchive -archivePath build/ios/iphoneos/Runner.xcarchive -exportPath build/ios/iphoneos -exportOptionsPlist exportOptions-prod.plist`

I am using Circle CI, here is a [gist with example for the config.yml ](https://gist.github.com/tasaquino/1b9c28aaad352a22b2bd6908f7ac8a50)

**Comment by jpcarreira** [comment] 2019-11-14 19:16
Any further development on this one? I'm currently manually changing `Use ... for command-line builds` whenever I want to switch between dev and prod environments.

**Comment by kuhnroyal** [comment] 2019-11-15 09:29
@jpcarreira I have patched my local stable channel with the changes from https://github.com/flutter/flutter/commit/ccfdf95c4a8e5a1117baf89748c0c22304570aaf - this seems to work

**Comment by jpcarreira** [comment] 2019-11-17 23:15
> @jpcarreira I have patched my local stable channel with the changes from [ccfdf95](https://github.com/flutter/flutter/commit/ccfdf95c4a8e5a1117baf89748c0c22304570aaf) - this seems to work

Thanks for your tip, I did something similar: branched-out of the current **stable** branch and cherry-picked that commit. And it has been working so far, hopefully soon this commit will be part of the stable channel.

**Comment by kuhnroyal** [comment] 2019-12-05 15:33
This is now working on the `beta` channel.

**Comment by jmagman** [comment] 2020-01-22 02:09
Closing as fixed by https://github.com/flutter/flutter/pull/42964.  Please reopen if you think there's still an issue.
Thanks!

**Closed by jmagman** 2020-01-22 02:09 UTC
Labels: t: xcode, tool, ⌺‬ platform-ios

**Comment by PritishSawant** [comment] 2020-02-03 07:17
My issue is not getting resolved even after changing command-line builds option. I am using different scheme in iOS for multiple firebase project. It seems to work on Android. If I add release version of Google service info plist file after dev version then it uses release version irrespective of flavor and vice versa. For more details, check this https://stackoverflow.com/questions/59944278/configuring-multiple-scheme-in-ios-causes-mismatch-in-flavors

**Comment by bobanminic96** [comment] 2020-04-06 12:08
I experiencing that if i'am building dev flavor, or any other, bundle id is always same, for production. Building from terminal/cmd line.
