### ISSUE TITLE
FlutterView on iOS should only presentWithTransaction when there's an embedded UIView

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#24133] opened 2018-11-09 00:04 UTC
Right now if the embedded views flag is no we always set the FlutterView's layer to `presentsWithTransaction` to true.
This is less efficient, and we should only do it if there's an embedded view (or even expose that as a knob for the app developer, as we don't really need this for all use cases).

**Comment by dnfield** [comment] 2019-08-18 06:27
I think, more generally, it would be helpful to have the embedded views controller tell you whether or not you should be using transactions. This is important for Metal, since there using transactions will require blocking the thread to present the frame within the transaction, if in fact transactions are expected to be used.

**Comment by dnfield** [comment] 2019-08-18 06:34
As an semi-related aside, I think this might be the cause of our freezeups on OpenGL - OpenGL may be sometimes trying to present the frame after the transaction commits, which leads to a mismatch between the CPU and GPU and thread starvation.

**Comment by craigomac** [comment] 2020-11-24 08:37
> As an semi-related aside, I think this might be the cause of our freezeups on OpenGL - OpenGL may be sometimes trying to present the frame after the transaction commits, which leads to a mismatch between the CPU and GPU and thread starvation. I was able to fix this in the metal implementation.

@dnfield Was this ever fixed in the OpenGL implementation? I'm currently having to use a [Flutter OpenGL build](https://github.com/acoutts/flutter-engines-no-metal) so I can take advantage of shader warmups. Everything works great except for these seemingly random freezes:
![image](https://user-images.githubusercontent.com/6972172/100069041-905d1e00-2e38-11eb-80ab-2221078872dc.png)

Further down the graph I don't see any issues with long rebuilds or paint operations—it's just this block that seems to stop the app for a few stuttering seconds until it picks up and continues smoothly.

Could it be the issue you describe here?

**Comment by dnfield** [comment] 2020-11-24 13:51
I don't believe this was ever fixed.  @flar may know

**Comment by cyanglaz** [comment] 2023-01-11 22:23
Closing this issue as we are doing it on both impeller and skia now: 
https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/ios_surface_metal_skia.mm#L69
https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/ios_surface_metal_impeller.mm#L55

**Closed by cyanglaz** 2023-01-11 22:23 UTC
Labels: platform-ios, engine, a: platform-views, passed first triage, P4
