### ISSUE TITLE
Consider mipmapping `ui.Image`'s generated by the engine.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#26443] opened 2019-01-11 23:39 UTC
Currently, the engine does not enable mipmapping on any images generated for the framework. Skia does support building mipmaps. Using mipmaps will lead to better quality in rendering of scaled images and better per frame performance because of fewer texel fetches from texture memory at non-base mipmap levels. This is at the cost of ~1.3x per texture memory usage.

We should consider either enabling mipmapping for all images or provide a flag to the framework for images it intends to render at a scaled size.

Mipmapping should always be disabled for images in the raster cache because rendering at resolution is the entire point for images generated by the cache.

**Comment by dnfield** [comment] 2020-05-18 22:36
We do use mipmapping on cross context images. Closing this on the assumption that that's all that was intended here. 

Specifically, https://github.com/flutter/engine/blob/17e07c537e136d92f1f3f6957531c81b8b4374af/lib/ui/painting/image_decoder.cc#L289

**Closed by dnfield** 2020-05-18 22:36 UTC
Labels: engine
