### ISSUE TITLE
Flutter APK file crashes when started on mobile device

### ISSUE THREAD

**Issue by Vlxdi** [flutter/flutter#129369] opened 2023-06-22 18:57 UTC
Hi, Flutter team!
I wanted to bring an issue to your attention that I've been experiencing lately. My build APK isn't opening on my phone properly. Whenever I tap the app icon, it opens for a moment and then crashes immediately. Additionally, when I run the command "`flutter build apk --release`" in the console, I receive several errors indicating a problem with the Kotlin version.

The error:
```
 C:/Users/�����/.gradle/caches/transforms-3/99c39af4f8a8c6bb15f38e76173c7613/transformed/jetified-firebase-analytics-ktx-21.3.0-api.jar!/META-INF/java.com.google.android.libraries.firebase.firebase_analytics_ktx_granule.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseKotlin'.
```

As you can see I am also using firebase. 
I have attached the content of my gradle files.

Please write me back if there is anything I can provide you with.
[build.gradle.txt](https://github.com/flutter/flutter/files/11838221/build.gradle.txt)
[app_build.gradle.txt](https://github.com/flutter/flutter/files/11838228/app_build.gradle.txt)

**Comment by huycozy** [comment] 2023-06-23 05:57
Hi @Vlxdi 
It looks like an issue with Gradle. Does the issue persist when running in `release` mode? If so, can you share the complete output of `flutter run --release -v`?

**Comment by Vlxdi** [comment] 2023-06-23 16:56
> Hi @Vlxdi It looks like an issue with Gradle. Does the issue persist when running in `release` mode? If so, can you share the complete output of `flutter run --release -v`?

I can run the program in a web browser (Edge) without issues, I could also run it on a windows application but not anymore since firebase does not support it. However here is the output you asked for:
```
[   +2 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +50 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 796c8ef79279f9c774545b3771238c3098dbefab
[        ] executing: [C:\src\flutter/] git tag --points-at 796c8ef79279f9c774545b3771238c3098dbefab
[  +76 ms] Exit code 0 from: git tag --points-at 796c8ef79279f9c774545b3771238c3098dbefab
[        ] 3.10.5
[   +2 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +29 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +87 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +59 ms] executing: c:\android\sdk\platform-tools\adb.exe devices -l
[  +48 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
```

**Comment by darshankawar** [comment] 2023-06-26 06:07
@Vlxdi 
It looks like an issue / version compatibility between analytics version as the log shows:

`firebase_analytics_ktx_granule.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.`

Please follow along the message and try to change the `firebase_analytics_ktx_granule.kotlin_module` version. You can search for same on support channels like StackOverflow to get some ideas.

**Comment by Vlxdi** [comment] 2023-06-26 14:15
> 

Whenever I search, everybody says that I should change "ext. kotlin_version" but my version is already set to `1.8.0`, I tried changing it to `1.6.0` but then i get an error saying that my project requires newer version of kotlin. I don't know what to do at this point. I also tried adding `implementation group: 'com.google.firebase', name: 'firebase-analytics', version: '21.3.0'` instead of `implementation 'com.google.firebase:firebase-analytics-ktx` and at first I got no issues but then i installed the app and it still didn't opened.

**Comment by darshankawar** [comment] 2023-06-27 06:23
@Vlxdi 
In order to properly address / pinpoint the cause of the issue, I suggest you to segregate firebase implementation from your project and try again to build the apk and check if the reported error still occurs or not. This is to confirm / isolate the issue from firebase. That way we can try to narrow down to the cause of the issue.

**Comment by Vlxdi** [comment] 2023-06-27 11:50
I segregated firebase from the project and now when I run `flutter build apk --relase`. The terminal returns:
`e: C:/Users/�����/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation-jvm/1.6.0/a7257339a052df0f91433cf9651231bbb802b502/annotation-jvm-1.6.0.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/�����/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/�����/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/�����/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/�����/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.22/1a8e3601703ae14bb58757ea6b2d8e8e5935a586/kotlin-stdlib-common-1.8.22.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.`

**Comment by darshankawar** [comment] 2023-06-28 05:59
@Vlxdi 
Check [this](https://github.com/flutter/flutter/issues/115477#issuecomment-1346678524) and see if it helps in your case or not.

**Comment by darshankawar** [comment] 2023-06-29 05:24
Please provide us a sample repo with minimal code including only relevant details that are enough to trigger the error you are getting, so that we can clone it and verify at our end and to properly address this issue.

**Comment by Vlxdi** [comment] 2023-06-29 18:34
> Please provide us a sample repo with minimal code including only relevant details that are enough to trigger the error you are getting, so that we can clone it and verify at our end and to properly address this issue.

I have invited you as a collaborator in my repo, I hope it contains the needed information

**Comment by darshankawar** [comment] 2023-06-30 06:08
I cloned the repo but it seems it isn't in proper structure, as while trying to run, it looks for `lib/main.dart` but there's directly `main.dart`. I could try to copy all in a sample app and move files to it but it'll be a bit time consuming.

Also, meantime, please check if [this](https://stackoverflow.com/questions/75256812/the-binary-version-of-its-metadata-is-1-8-0-expected-version-is-1-6-0-module-w) is useful or not.

**Comment by Vlxdi** [comment] 2023-07-02 17:24
I tried adding those dependencies and the compose version as well. I tried with the copy paste version then i change it to 1.4.0, 1.6.0, and 1.8.0 . But it seems like it didn't change anything.

**Comment by huycozy** [comment] 2023-07-03 06:03
@Vlxdi It's possible that you changed the Kotlin versions when using some plugin (just an assumption).

I recommend you migrate your code to the new project one by one and observe if the issue still persists. If it's not a Flutter issue, feel free to close this issue and search for it on StackOverflow to have more ideas.

**Comment by Vlxdi** [comment] 2023-07-03 16:15
> @Vlxdi It's possible that you changed the Kotlin versions when using some plugin (just an assumption).
> 
> I recommend you migrate your code to the new project one by one and observe if the issue still persists. If it's not a Flutter issue, feel free to close this issue and search for it on StackOverflow to have more ideas.

i already tried migrating to a new proeject and I'm sure it is something just with the gradle files. As for the kotlin version is still the newest one I checked.

**Comment by Vlxdi** [comment] 2023-07-04 09:01
I migrated the project again and removed the firebase, still got the issue though, that means is probably something in the code

**Comment by huycozy** [comment] 2023-07-05 03:24
Could you share these file contents? Or could you invite me to your current minimal sample project that is having the issue?

- `/android/build.gradle`
- `/android/app/build.gradle`
- `/android/gradle/wrapper/gradle-wrapper.properties`

**Comment by Vlxdi** [comment] 2023-07-05 11:51
> huycozy

I have invited you. The repository provides everything you said.

**Comment by huycozy** [comment] 2023-07-06 04:34
Thanks but it's not a proper project structure. You are also using some 3rd party packages so it doesn't make sure the issue can be caused by one of them. 

I would suggest you create a new Flutter project, then add package/widget/settings(gradle/kotlin) one by one until you can reproduce the crash consistently. And then share that project so I can investigate it on my end.

**Comment by Vlxdi** [comment] 2023-07-06 08:58
The problem comes with firebase. I tried making new project and adding all of my previous code and i had no problems installing it and opening it on my phone.

**Comment by huycozy** [comment] 2023-07-07 04:09
@Vlxdi I tried creating a new Flutter project and importing the same Firebase plugin as yours but can't reproduce this issue. It could be an issue with your local Gradle cache as well. You can try to clear and download again (see this [SO answer](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache) for steps to do)

Since this is not a Flutter issue, I will close this issue from here. Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

**Closed by huycozy** 2023-07-07 04:09 UTC
Labels: in triage

**Comment by Vlxdi** [comment] 2023-07-07 16:36
> @Vlxdi I tried creating a new Flutter project and importing the same Firebase plugin as yours but can't reproduce this issue. It could be an issue with your local Gradle cache as well. You can try to clear and download again (see this [SO answer](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache) for steps to do)
> 
> Since this is not a Flutter issue, I will close this issue from here. Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

I had deleted my cache multiple times but at least it worked for you
