### ISSUE TITLE
"flutter upgrade" prompts for ... "flutter upgrade"

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#13289] opened 2017-12-01 03:46 UTC
Just a silly little nit.

<img width="597" alt="screen shot 2017-11-30 at 7 45 13 pm" src="https://user-images.githubusercontent.com/168174/33467124-111b3c08-d607-11e7-8e7c-586b8e72a952.png">

**Comment by mit-mit** [comment] 2017-12-01 09:42
Dupe of https://github.com/flutter/flutter/issues/12991

**Closed by mit-mit** 2017-12-01 09:42 UTC
Labels: dev: tool
