### ISSUE TITLE
more optional constructor variables cause flutter crashed

### ISSUE THREAD

**Issue by ideologist** [flutter/flutter#45904] opened 2019-12-02 14:40 UTC
I have a constructor has many optional variables, if the optional variables is greater than 34, it cause the app crashed.

Here is the crash dump stack trace

```
 E/Dart    (13814): ../../third_party/dart/runtime/vm/compiler/assembler/assembler_arm64.h: 162: error: unreachable code
E/DartVM  (13814): version=2.7.0 (Fri Nov 8 17:16:37 2019 +0000) on "android_arm64"
E/DartVM  (13814): thread=13859, isolate=main(0x6feadad800)
E/DartVM  (13814):   pc 0x0000006fef052f4c fp 0x0000006fed9c4e50 /data/app/xxxxxxxxxxxxxx==/lib/arm64/libflutter.so+0x1689f4c
E/DartVM  (13814): -- End of DumpStackTrace
```

**Comment by iapicca** [comment] 2019-12-02 15:35
Hi @ideologist 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by ideologist** [comment] 2019-12-06 03:45
Hi, here is my output
flutter doctor -v
[✓] Flutter (Channel beta, v1.11.0, on Mac OS X 10.14.5 18F132, locale en-CN)
    • Flutter version 1.11.0 at /Users/ideologist/flutter
    • Framework revision 856a90e67c (4 weeks ago), 2019-11-08 18:00:01 -0800
    • Engine revision af04338413
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ideologist/Library/Android/sdk
    • Android NDK at /Users/ideologist/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Nexus 6P • 84B5T15A29019259 • android-arm64 • Android 8.1.0 (API 27)

**Comment by ideologist** [comment] 2019-12-06 03:52
hello,

Here is my demo code

`class A {
  String a;
  String b;
  String c;
  String d;
  String e;
  String f;
  String g;
  String h;
  String i;
  String j;
  String k;
  String l;
  String m;
  String n;
  String o;
  String p;
  String q;
  String r;
  String s;
  String t;
  String u;
  String v;
  String w;
  String x;
  String y;
  String z;
  String a1;
  String a2;
  String a3;
  String a4;
  String a5;
  String a6;
  String a7;
  String a8;
  String a9;
  String a10;
  String a11;

  A([this.a, this.b, this.c, this.d, this.e, this.f, this.g, this.h, this.i,
      this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, this.r,
      this.s, this.t, this.u, this.v, this.w, this.x, this.y, this.z, this.a1,
      this.a2, this.a3, this.a4, this.a5, this.a6, this.a7, this.a8, this.a9,
      this.a10, this.a11]);
}

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    A a = A();
    
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
`

**Comment by iapicca** [comment] 2019-12-19 15:45
Hi @ideologist 

does this solution fix the issue?

<details>
  <summary>code sample</summary>

```dart 
import 'package:flutter/material.dart';

class Alphabet {
  final String a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,bb,cc,dd,ee,ff,gg,hh,ii,jj,kk;
 
  Alphabet({this.a, this.b, this.c, this.d, this.e, this.f, this.g, this.h, this.i,
      this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, this.r,
      this.s, this.t, this.u, this.v, this.w, this.x, this.y, this.z, this.aa,
      this.bb, this.cc, this.dd, this.ee, this.ff, this.gg, this.hh, this.ii,
      this.jj, this.kk});
}

class AlphabetPositional {
  String a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,bb,cc,dd,ee,ff,gg,hh,ii,jj,kk;
 
  AlphabetPositional(this.a, this.b, this.c, this.d, this.e, this.f, this.g, this.h, this.i,
      this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, this.r,
      this.s, this.t, this.u, this.v, this.w, this.x, this.y, this.z, this.aa,
      this.bb, this.cc, this.dd, this.ee, this.ff, this.gg, this.hh, this.ii,
      this.jj, this.kk);
}

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static final Alphabet _alphabet = Alphabet(a:'a');
  static final AlphabetPositional _positional = 
  AlphabetPositional('a','b','c','d','e','f','g','h','i','j','k',
  'l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',
  'aa','bb','cc','dd','ee','ff','gg','hh','ii','jj','kk');

  @override
  Widget build(BuildContext context) => MaterialApp(
    home: Scaffold(
      body: Center(
        child: Text('${_alphabet.a} ${_positional.a}'),
      ),
    ),
  );
}
```

</details>

thank you

**Comment by VladyslavBondarenko** [comment] 2020-01-10 09:05
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by VladyslavBondarenko** 2020-01-10 09:05 UTC
Labels: dependency: dart, engine, severe: crash, waiting for customer response

**Comment by mraleph** [comment] 2020-08-25 08:50
Duplicate of #64526
