### ISSUE TITLE
Flutter tabbar tab scroll start changes contents in current widget

### ISSUE THREAD

**Issue by newDroidGuy** [flutter/flutter#90278] opened 2021-09-17 17:13 UTC
I have a tab bar with 4 tabs, each tab has listview, which is populated with data from API, i'm calling the api in initState of each widget for the tab, when i just start the scroll and do not complete the scroll for moving to next tab, the api of next tab is getting called and when the i stop or donot proceed with the scroll, the tab doesn't change but the contents are changed. Please find the gif below
![tab_issue](https://user-images.githubusercontent.com/16486350/133827661-6b74d2ec-4a89-4428-9040-fa0f546277e8.gif)

```
Class with tabbar 
`class HomeScreen extends StatefulWidget {
  const HomeScreen({Key key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with TickerProviderStateMixin {
  AssignmentRepository assignmentRepository;
  TabController _controller;
  // ignore: unused_field
  int _selectedIndex = 0;
  HomeBloc homeBloc;

  @override
  void initState() {
    super.initState();
    assignmentRepository = AssignmentRepository();
    _controller = TabController(length: 4, vsync: this);
    _controller.addListener(() {
      setState(() {
        _selectedIndex = _controller.index;
      });
      print("Selected Index: " + _controller.index.toString());
    });
    homeBloc = HomeBloc(aRepository: assignmentRepository);
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 4,
      child: Scaffold(
        appBar: DecoratedTabBar(
          decoration: BoxDecoration(
            border: Border(
              bottom: BorderSide(
                color: Theme.of(context).dividerTheme.color,
                width: 1.0,
              ),
            ),
          ),
          tabBar: TabBar(
            indicatorColor: Theme.of(context).accentColor,
            indicatorSize: TabBarIndicatorSize.tab,
            indicatorWeight: 2,
            //controller: _controller,
            isScrollable: true,
            labelColor: Theme.of(context).tabBarTheme.labelColor,
            labelStyle: Theme.of(context).tabBarTheme.labelStyle,
            unselectedLabelColor:
                Theme.of(context).tabBarTheme.unselectedLabelColor,
            unselectedLabelStyle:
                Theme.of(context).tabBarTheme.unselectedLabelStyle,
            tabs: [
              Tab(
                text: 'NEW',
              ),
              Tab(
                text: 'WORKING ON',
              ),
              Tab(
                text: 'SUBMITTED',
              ),
              Tab(
                text: 'DONE',
              ),
            ],
          ),
        ),
        body: TabBarView(children: [
          NewAssignmentWidget(
            homeBloc: homeBloc,
          ),
          WorkingOnWidget(
            homeBloc: homeBloc,
          ),
          SubmittedWidget(
            homeBloc: homeBloc,
          ),
          DoneWidget(
            homeBloc: homeBloc,
          ),
        ]),
      ),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}`
```

**Comment by andre799** [comment] 2021-09-17 20:19
Are TabBarView items a StatefulWidget? If so, try using the AutomaticKeepAliveClientMixin mixin and setting wantKeepAlive to true

Example:

```dart
class Page extends StatefulWidget {
  const Page({Key? key}) : super(key: key);

  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<AboutYouPage> with AutomaticKeepAliveClientMixin{
  @override
  Widget build(BuildContext context) {
    super.build(context); // <-----
    return Scaffold(
      appBar: AppBar(
        title: const Text(''),
      ),
      body: Container(),
    );
  }

  @override
  bool get wantKeepAlive => true; // <-----
}
```

[Here](https://api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html) is an explanation of how AutomaticKeepAliveClientMixin works

**Comment by newDroidGuy** [comment] 2021-09-18 00:41
Hi, thanks for the reply, but unfortunately this didn't solve the issue.

**Comment by darshankawar** [comment] 2021-09-20 07:02
@newDroidGuy 
This issue sounds like can be asked in support channels like StackOverflow. Also since you are using `bloc` which is 3rd party, we can't really tell if the issue is with it or in core framework. I suggest you to ask this question on StackOverflow.
If you disagree and think this is a genuine bug in the framework, please provide us a complete minimal reproducible code sample without any 3rd party plugins, that we can directly run to verify.
Closing for now.

**Closed by darshankawar** 2021-09-20 07:02 UTC
Labels: in triage
