### ISSUE TITLE
Flutter 3.7.0: Missing whatsapp icon

### ISSUE THREAD

**Issue by FabioPaganoAPSystem** [flutter/flutter#119202] opened 2023-01-25 23:52 UTC
In Flutter 3.7.0 is no more present the whatsapp icon.

The following instruction:
Icon(Icons.whatsapp)
now gives error "The getter 'whatsapp' isn't defined for the type 'Icons'".

In previous version the whatsapp icon was present.

Thank you.

**Comment by stuartmorgan** [comment] 2023-01-26 00:30
Duplicate of https://github.com/flutter/flutter/issues/111667

**Closed by stuartmorgan** 2023-01-26 00:30 UTC
