### ISSUE TITLE
The arrow keys to place the cursor in a certain position in the TextField widget do not work correctly many times (Flutter 2.0.1 Desktop Windows - Beta Channel)

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#77538] opened 2021-03-07 22:11 UTC
Hi,
The arrow keys to position the cursor in the TextField widget often do not work correctly.
For example, you start typing in a TextField widget, at a certain point you want to use the arrow keys to go to the left of the text, and instead of just moving the cursor, what they do is select the text when moving to the left.
As you can see with this bug and with others that I have communicated, the text input has many problems, so for the moment it is not possible to develop any type of moderately serious application for desktop windows. 
Neither Flutter version of either channel solves this problem.
Regards,
Jose.

**Comment by stuartmorgan** [comment] 2021-03-07 22:43
This sounds like a side effect of the stuck modifier key issue. /cc @dkwingsmt

**Comment by TahaTesser** [comment] 2021-03-08 09:21
Hi @Josua2012 
Here I created a minimal runnable code sample (has a big font size for easy recording), unable to replicate the issue. Can you please try the code sample below,  if it reproduces the issue, please provide reproducible steps? 

When typing some words and tapping arrows to the left, the text wasn't selected

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: TextField(
            maxLines: 6,
            style: TextStyle(fontSize: 64),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
PS C:\Users\Taha\AndroidStudioProjects> flutterb doctor -v
[✓] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.0.1 at C:\Users\Taha\Code\flutter_beta
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
PS C:\Users\Taha\AndroidStudioProjects>
```

</details>

Thank you

**Comment by Josua2012** [comment] 2021-03-08 09:55
Hi @TahaTesser,

It is very easy to reproduce it. :)
In this video you can see 2 problems.

1. I place the mouse cursor to start writing the text.
2. I click SHIFT + E so that the letter E is displayed in uppercase.
3. I release the SHIFT key, however it continues to be capitalized. **This is wrong.**
4. I write a few more letters.
5. Then with the arrow left key I move the cursor to the left, the text is selected. **This is wrong.** Only the cursor should move to the left, it should not select the text. With the arrow keys only it must select the text if the SHIFT key is simultaneously pressed. It is the standard operation of the windows edit fields. 

Video: https://recordit.co/bNztNiqy2P

Thank you.

Regards,
Jose

**Comment by stuartmorgan** [comment] 2021-03-08 12:42
Definitely the same as the stuck shift key given those steps. Closing as a duplicate of https://github.com/flutter/flutter/issues/75675

**Closed by stuartmorgan** 2021-03-08 12:42 UTC
Labels: in triage
