### ISSUE TITLE
The plugin `shared_preferences` doesn't have a main class defined

### ISSUE THREAD

**Issue by SahajRana** [flutter/flutter#60322] opened 2020-06-25 23:08 UTC
I just downloaded the flutter package and ran it.
& this is what I'm receiving. I tired with the example folder included with flutter package and flutter clean.
How to resolve this? 
```
The plugin `shared_preferences` doesn't have a main class defined in F:\my_app\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java or
F:\my_app\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\android\src\main\kotlin\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.kt. This is likely to due to an
incorrect `androidPackage: io.flutter.plugins.sharedpreferences` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different
plugin in the meanwhile.
```

flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.836], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Android Studio (version 3.1)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.37.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by VladyslavBondarenko** [comment] 2020-06-26 11:39
Hi @SahajRana 
I just tried the example project https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences/example with stable v1.17.4 on and it's working as intended. 
Have you used it?

**Comment by VladyslavBondarenko** [comment] 2020-07-22 12:52
@SahajRana 
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with filling out template

**Closed by VladyslavBondarenko** 2020-07-22 12:52 UTC
Labels: in triage, waiting for customer response

**Comment by zhongyiqwer** [comment] 2020-10-12 11:37
![image](https://user-images.githubusercontent.com/20125641/95742131-1cb8e480-0cc2-11eb-8d53-25c613bfea30.png)
just comment out these lines
