### ISSUE TITLE
[iOS 17] Textfield last char selected

### ISSUE THREAD

**Issue by Kiruel** [flutter/flutter#130796] opened 2023-07-18 14:16 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Use any TextField in iOS on iOS 17.

### Expected results

Should be the same as preview iOS version.

### Actual results

The TestField add a selected for the last char. See video on iOS 17 below.

### Code sample

<details><summary>Code sample</summary>

```dart
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const TextField(),
    );
  }
}

```
[dartpad](https://dartpad.dev/?id=74ace43c34fd6a9b1c6f448467f2ebfa)
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

iOS 16.4:

https://github.com/flutter/flutter/assets/8250175/8ec9e09b-2551-4f3e-a408-c2576a238c82

iOS 17.0:

https://github.com/flutter/flutter/assets/8250175/35d9ab70-a1d0-46e1-abdf-c6cb811aa6a0

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.80.1)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-07-18 14:41
Hi @Kiruel, Thanks for filing this issue. There is a currently open issue that describes this case. Kindly upvote, comment and follow up on the issue for updates. Closing this as a duplicate of https://github.com/flutter/flutter/issues/128406. 
If you disagree, please write in the comments and I will reopen it.
Thank you!

**Closed by dam-ease** 2023-07-18 14:41 UTC
Labels: in triage
