### ISSUE TITLE
Production crash report "couldn't find libflutter.so" from Android devices 

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#68484] opened 2020-10-19 15:11 UTC
Here is the list of devices where found the error:

1. Nexus 5X
2. POCO X3 NFC
3. Mi Note 10 Lite
4. Redmi Note 5 Pro
5. Galaxy J7(2016)
6. Galaxy J2 Core
7. Galaxy A3(2017)
8. Galaxy A21s
9. Redmi Note 9 Pro
10. Huawei y5

Surprisingly most of these devices have a 64-bit processor architecture and app bundle doesn't solve this problem. I sure this problem should be investigated carefully because it is popular devices and we want our customers to be able to use our apps.

Last 3 devices: Flutter stable 1.22.2

Issue catches by firebase crashlytics

**Comment by TahaTesser** [comment] 2020-10-19 15:35
Hi @Renesanse 
Can you please provide your `flutter doctor -v`, your `crash logs` from `firebase crashlytics`, your `pubspec.yaml`, the list of affected devices, and if possible your `flutter run --release --verbose` running on the same OS version as the affected device or devices 
Thank you

**Comment by Renesanse** [comment] 2020-10-19 15:52
**flutter doctor**
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G73, locale en-RU)
    • Flutter version 1.22.2 at /Users/renesanse/flutter
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/renesanse/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/renesanse/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.beta.2

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.


**crash logs**
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{ru.ozon.ozon_pvz/ru.ozon.ozon_pvz.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/base.apk"],nativeLibraryDirectories=[/data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/lib/arm64, /data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libflutter.so"
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3623)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3775)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2261)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8107)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by java.lang.RuntimeException
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/base.apk"],nativeLibraryDirectories=[/data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/lib/arm64, /data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libflutter.so"
io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java:243)
io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:289)
io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:192)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine (FlutterActivityAndFragmentDelegate.java:234)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:154)
io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:410)
android.app.Activity.performCreate (Activity.java:7957)
android.app.Activity.performCreate (Activity.java:7946)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3598)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3775)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2261)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8107)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by java.util.concurrent.ExecutionException
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/base.apk"],nativeLibraryDirectories=[/data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/lib/arm64, /data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libflutter.so"
java.util.concurrent.FutureTask.report (FutureTask.java:123)
java.util.concurrent.FutureTask.get (FutureTask.java:193)
io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java:178)
io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:289)
io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:192)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine (FlutterActivityAndFragmentDelegate.java:234)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:154)
io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:410)
android.app.Activity.performCreate (Activity.java:7957)
android.app.Activity.performCreate (Activity.java:7946)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3598)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3775)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2261)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8107)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/base.apk"],nativeLibraryDirectories=[/data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/lib/arm64, /data/app/ru.ozon.ozon_pvz-aBpxi8JafA_boYse3dYdhQ==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libflutter.so"
java.lang.Runtime.loadLibrary0 (Runtime.java:1067)
java.lang.Runtime.loadLibrary0 (Runtime.java:1007)
java.lang.System.loadLibrary (System.java:1667)
io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java:129)
io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java:123)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)
FinalizerWatchdogDaemon
java.lang.Object.wait (Object.java)
java.lang.Object.wait (Object.java:442)
java.lang.Object.wait (Object.java:568)
java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded (Daemons.java:339)
java.lang.Daemons$FinalizerWatchdogDaemon.runInternal (Daemons.java:319)
java.lang.Daemons$Daemon.run (Daemons.java:137)
java.lang.Thread.run (Thread.java:919)
pool-6-thread-1
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2067)
java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:442)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1092)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)
ScionFrontendApi
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2109)
java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:467)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1091)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)
ReferenceQueueDaemon
java.lang.Object.wait (Object.java)
java.lang.Object.wait (Object.java:442)
java.lang.Object.wait (Object.java:568)
java.lang.Daemons$ReferenceQueueDaemon.runInternal (Daemons.java:215)
java.lang.Daemons$Daemon.run (Daemons.java:137)
java.lang.Thread.run (Thread.java:919)
firebase-iid-executor
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt (AbstractQueuedSynchronizer.java:868)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1023)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1334)
java.util.concurrent.CountDownLatch.await (CountDownLatch.java:232)
com.google.android.gms.tasks.Tasks$zza.await (Источник неизвестен:9)
com.google.android.gms.tasks.Tasks.await (Источник неизвестен:22)
com.google.firebase.iid.zzau.zza (com.google.firebase:firebase-iid@@20.1.5:82)
com.google.firebase.iid.zzt.zza (com.google.firebase:firebase-iid@@20.1.5:73)
com.google.firebase.iid.zzs.run (Источник неизвестен:12)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.android.gms.common.util.concurrent.zza.run (Источник неизвестен:6)
java.lang.Thread.run (Thread.java:919)
MessengerIpcClient
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2109)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:1132)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:849)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1092)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.android.gms.common.util.concurrent.zza.run (Источник неизвестен:6)
java.lang.Thread.run (Thread.java:919)
FirebaseInstanceId
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos (AbstractQueuedSynchronizer.java:1063)
java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos (AbstractQueuedSynchronizer.java:1358)
java.util.concurrent.CountDownLatch.await (CountDownLatch.java:278)
com.google.android.gms.tasks.Tasks$zza.await (Источник неизвестен:11)
com.google.android.gms.tasks.Tasks.await (Источник неизвестен:31)
com.google.firebase.iid.FirebaseInstanceId.zza (com.google.firebase:firebase-iid@@20.1.5:98)
com.google.firebase.iid.FirebaseInstanceId.getToken (com.google.firebase:firebase-iid@@20.1.5:94)
com.google.firebase.iid.FirebaseInstanceId.zzc (com.google.firebase:firebase-iid@@20.1.5:97)
com.google.firebase.iid.zzbb.zzc (com.google.firebase:firebase-iid@@20.1.5:42)
com.google.firebase.iid.zzbb.run (com.google.firebase:firebase-iid@@20.1.5:23)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:462)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.android.gms.common.util.concurrent.zza.run (Источник неизвестен:6)
java.lang.Thread.run (Thread.java:919)
Crashlytics Exception Handler1
dalvik.system.VMStack.getThreadStackTrace (VMStack.java)
java.lang.Thread.getStackTrace (Thread.java:1720)
java.lang.Thread.getAllStackTraces (Thread.java:1796)
com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateThreadsList (com.google.firebase:firebase-crashlytics@@17.0.0:260)
com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateExecutionData (com.google.firebase:firebase-crashlytics@@17.0.0:240)
com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateEventApplicationData (com.google.firebase:firebase-crashlytics@@17.0.0:202)
com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.captureEventData (com.google.firebase:firebase-crashlytics@@17.0.0:106)
com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistEvent (com.google.firebase:firebase-crashlytics@@17.0.0:214)
com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistFatalEvent (com.google.firebase:firebase-crashlytics@@17.0.0:121)
com.google.firebase.crashlytics.internal.common.CrashlyticsController$6.call (com.google.firebase:firebase-crashlytics@@17.0.0:400)
com.google.firebase.crashlytics.internal.common.CrashlyticsController$6.call (com.google.firebase:firebase-crashlytics@@17.0.0:393)
com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then (com.google.firebase:firebase-crashlytics@@17.0.0:106)
com.google.android.gms.tasks.zzf.run (Источник неизвестен:2)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun (com.google.firebase:firebase-crashlytics@@17.0.0:60)
com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run (com.google.firebase:firebase-crashlytics@@17.0.0:27)
java.lang.Thread.run (Thread.java:919)
Measurement Worker
com.google.android.gms.internal.measurement.zzop.zza (com.google.android.gms:play-services-measurement-impl@@17.5.0:8)
com.google.android.gms.internal.measurement.zzop.zzb (com.google.android.gms:play-services-measurement-impl@@17.5.0:1)
com.google.android.gms.measurement.internal.zzat.zzax (com.google.android.gms:play-services-measurement-impl@@17.5.0:58)
com.google.android.gms.measurement.internal.zzcg.zza
com.google.android.gms.measurement.internal.zzem.zza (com.google.android.gms:play-services-measurement-impl@@17.5.0:26)
com.google.android.gms.measurement.internal.zzy.zzd (com.google.android.gms:play-services-measurement-impl@@17.5.0:98)
com.google.android.gms.measurement.internal.zzy.zza (com.google.android.gms:play-services-measurement-impl@@17.5.0:109)
com.google.android.gms.measurement.internal.zzgb.zzab (com.google.android.gms:play-services-measurement-impl@@17.5.0:363)
com.google.android.gms.measurement.internal.zzgb.zzaa (com.google.android.gms:play-services-measurement-impl@@17.5.0:328)
com.google.android.gms.measurement.internal.zzeq.zza (com.google.android.gms:play-services-measurement-impl@@17.5.0:168)
com.google.android.gms.measurement.internal.zziv.zzb (com.google.android.gms:play-services-measurement-impl@@17.5.0:287)
com.google.android.gms.measurement.internal.zziv.zza (com.google.android.gms:play-services-measurement-impl@@17.5.0:120)
com.google.android.gms.measurement.internal.zzgb.zza (com.google.android.gms:play-services-measurement-impl@@17.5.0:241)
com.google.android.gms.measurement.internal.zzgd.run (com.google.android.gms:play-services-measurement-impl@@17.5.0:3)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:462)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
com.google.android.gms.measurement.internal.zzfy.run (com.google.android.gms:play-services-measurement-impl@@17.5.0:21)
com.google.firebase.crashlytics.startup1
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2067)
java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:442)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1092)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun (com.google.firebase:firebase-crashlytics@@17.0.0:60)
com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run (com.google.firebase:firebase-crashlytics@@17.0.0:27)
java.lang.Thread.run (Thread.java:919)
awaitEvenIfOnMainThread task continuation executor1
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2067)
java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:442)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1092)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun (com.google.firebase:firebase-crashlytics@@17.0.0:60)
com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run (com.google.firebase:firebase-crashlytics@@17.0.0:27)
java.lang.Thread.run (Thread.java:919)
pool-12-thread-1
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos (AbstractQueuedSynchronizer.java:1063)
java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos (AbstractQueuedSynchronizer.java:1358)
java.util.concurrent.CountDownLatch.await (CountDownLatch.java:278)
com.google.firebase.crashlytics.internal.common.CrashlyticsController$BlockingCrashEventListener.awaitEvent (com.google.firebase:firebase-crashlytics@@17.0.0:1743)
com.google.firebase.crashlytics.internal.common.CrashlyticsController$23.call (com.google.firebase:firebase-crashlytics@@17.0.0:1793)
com.google.firebase.crashlytics.internal.common.CrashlyticsController$23.call (com.google.firebase:firebase-crashlytics@@17.0.0:1769)
com.google.android.gms.tasks.zzv.run (Источник неизвестен:2)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:462)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)
firebase-iid-executor
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2109)
java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:467)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1091)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.android.gms.common.util.concurrent.zza.run (Источник неизвестен:6)
java.lang.Thread.run (Thread.java:919)
queued-work-looper
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:336)
android.os.Looper.loop (Looper.java:197)
android.os.HandlerThread.run (HandlerThread.java:67)
firebase-installations-executor-2
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2109)
java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:467)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1091)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)
pool-11-thread-1
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2067)
java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:442)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1092)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)
firebase-installations-executor-1
sun.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2109)
java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:467)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1091)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)
FinalizerDaemon
java.lang.Object.wait (Object.java)
java.lang.Object.wait (Object.java:442)
java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:190)
java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:211)
java.lang.Daemons$FinalizerDaemon.runInternal (Daemons.java:271)
java.lang.Daemons$Daemon.run (Daemons.java:137)
java.lang.Thread.run (Thread.java:919)

**pubspec.yaml**

name: ***
description: ***
version: 1.0.4+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stream_transform: ^1.2.0
  package_info: ^0.4.3
  launch_review: ^2.0.0
  after_layout: ^1.0.7+2
  google_fonts: ^1.1.1
  bolter_flutter: ^1.1.7
  osam_http_client: ^0.1.0
  worker_manager: ^3.0.3
  sticky_headers: ^0.1.8+1
  syncfusion_flutter_barcodes: ^18.3.40
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  meta: ^1.2.3
  build_runner: ^1.10.2
  hive_generator:
    git:
      url: https://github.com/Renesanse/hive.git
      path: hive_generator
  json_annotation: ^3.1.0
  json_serializable: ^3.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

All issues found came from Google play versions of builds (means release mode)

**Comment by Renesanse** [comment] 2020-10-19 15:55
@TahaTesser  unfortunately, I am not able to run flutter run release -v on affected devices

**Comment by TahaTesser** [comment] 2020-10-20 08:00
I’m unable to reproduce the issue to pinpoint the cause, but there are reports from several users. The issue needs further investigation.

**Comment by chinmaygarde** [comment] 2020-10-26 18:49
Closing this seems to be a duplicate of [a previous issue that we investigated](https://github.com/flutter/flutter/issues/64697#issuecomment-683007555). If Crashlytics suggest a crash rate greater than 0.01% as reported by other users, it may be a different issue. In that case, we can reopen and investigate further.

**Closed by chinmaygarde** 2020-10-26 18:49 UTC
Labels: a: production, customer: crowd, engine, platform-android, severe: crash
