### ISSUE TITLE
Flutter 2.5: Scrolling in Web not working

### ISSUE THREAD

**Issue by drmilde** [flutter/flutter#89985] opened 2021-09-13 16:04 UTC
Hi Flutter Team,

after upgrading to 2.5, scrolling (see simple testcode below) in Web ist no longer working. On Android, everything is ok. Downgrading back to 2.2.3 restores the functionality. 

Testet it with a number of apps. No scrolling of ListViews in any of the apps. 

Thank you and best wishes

Jan-Torsten

============ TESTCODE =====================
```dart
import 'package:flutter/material.dart';

class ListTestScreen extends StatelessWidget {
  const ListTestScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: 100,
        itemBuilder: (context, index) {
          return Padding(
            padding: const EdgeInsets.all(8.0),
            child: Container(
              color: (index % 2) == 0 ? Colors.pink : Colors.lime,
              width: 300,
              height: 100,
            ),
     );},),);}}
```
============ TESTCODE =====================

**Comment by dotupNET** [comment] 2021-09-13 17:49
Maybe this helps:
[https://github.com/flutter/flutter/issues/89975#issuecomment-918209098](https://github.com/flutter/flutter/issues/89975#issuecomment-918209098)

**Comment by HansMuller** [comment] 2021-09-13 18:32
@dotupNET - that's correct.

Drag to scroll is disabled by default on desktop #81569 (thsi change isn't present in stable or beta)and read #83359 for more details

See migration guide https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag

**Comment by darshankawar** [comment] 2021-09-14 08:48
@drmilde 
Per above comment, this is working as intended, as the change isn't yet present in stable and beta. You can take a look at migration guide for further reference.
Closing this based on above comment.

**Closed by darshankawar** 2021-09-14 08:48 UTC
Labels: in triage
