### ISSUE TITLE
[camera] repeating anrs stopBackgroundThread

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#106493] opened 2022-06-23 13:39 UTC
We are getting a lot of these errors in firebase from various devices.

```
main (waiting)
tid=1 systid=29889

main (waiting): tid=1 systid=29889 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Thread.join(Thread.java:1438)
       at java.lang.Thread.join(Thread.java:1519)
       at io.flutter.plugins.camera.Camera.stopBackgroundThread(Camera.java:675)
       at io.flutter.plugins.camera.Camera.close(Camera.java:1196)
       at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:70)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
       at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8056)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

flutter doctor:
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3.1 21E258 darwin-arm, locale en-GR)
• Flutter version 3.0.2 at /Users/nikostsesmelis/Tools/flutter/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/cd41fdd495f6944ecd3506c21e94c6567b073278 (2 weeks ago), 2022-06-08 09:52:13 -0700
• Engine revision f15f824b57
• Dart version 2.17.3
• DevTools version 2.12.2

camera plugin version: 0.9.7+1 (not able to upgrade due to ios issue https://github.com/flutter/flutter/issues/106492)

**Comment by camsim99** [comment] 2022-06-23 23:06
I'm not sure if the context is the same of the error that prompted that change, but I'd suggest seeing if that change fixes it since it was a similar error.

**Comment by huycozy** [comment] 2022-06-24 10:20
Hi @NikosTsesmelis 
Could you provide the full log from Firebase Crashlytics here? 
And which platforms (Android/iOS)/specific devices does the issue occur on?

It seems this issue and issue #106490 you created has the same cause from `MethodChannelCamera`. I'm not sure should them merge into one (keep only one issue open) but please provide as much as information possible.

**Comment by NikosTsesmelis** [comment] 2022-06-24 11:03
I have only encountered it on android.
These are the most common devices so it seems pretty common.

Galaxy A22, Galaxy A12, Galaxy Note20, Galaxy A51, Galaxy S21+ 5G, POCO X3 Pro, Redmi Note 11 Pro 5G, Redmi Note 8 Pro, TCL 205, realme 8i.

I have not encountered it during development on my pixel 4a but i get it from our customers on firebase.

Is there a way to export the full stacktrace from firebase because it is fragmented in 100 different parts. Or do you need something else?

<img width="1323" alt="Screenshot 2022-06-24 at 2 02 52 PM" src="https://user-images.githubusercontent.com/100851392/175522208-d5fae3d8-9746-476d-b40a-b26c4c6dea4f.png">

**Comment by huycozy** [comment] 2022-06-27 04:30
@NikosTsesmelis 
Thank you! Labeling this issue for further investigation from the team.

**Comment by Chetan-3110** [comment] 2022-07-05 14:25
Hey there, I am also facing this issue. It is only happening in Android 11 and Android 12.

<img width="452" alt="Screenshot 2022-07-05 at 7 55 24 PM" src="https://user-images.githubusercontent.com/91893165/177351047-93b202d7-c24e-49d4-8dc2-78d483758b43.png">

**Comment by tijanirf** [comment] 2022-07-19 08:01
Any update regarding this issue? 👀

Here's more info for my project, 130 events for the last 90 days is just too much

<img width="1096" alt="Screen Shot 2022-07-19 at 3 00 00 PM" src="https://user-images.githubusercontent.com/35812470/179698616-21e11fef-2733-4c21-9b0f-76d02ce85797.png">

<img width="432" alt="Screen Shot 2022-07-19 at 2 58 18 PM" src="https://user-images.githubusercontent.com/35812470/179698259-e0d94b9b-6968-46ea-9bee-3b239810d80e.png">

**Comment by agrvaibhav** [comment] 2022-07-29 07:28
This ANR is happening for my app too. This is possibly happening when camera is opened several times in quick succession:

<img width="1295" alt="Screenshot 2022-07-29 at 12 49 05 PM" src="https://user-images.githubusercontent.com/2479919/181704895-31a34141-c887-4829-885d-01915b35325c.png">

**Comment by tijanirf** [comment] 2022-08-04 03:29
This is taken from [Camera.java](https://github.com/flutter/plugins/blob/main/packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/Camera.java)
<img width="680" alt="Screen Shot 2022-08-04 at 10 24 08 AM" src="https://user-images.githubusercontent.com/35812470/182756332-d8366a96-080c-47a0-ad9b-9f09964736db.png">

Anyway do we really need `backgroundHandlerThread.join()` after `backgroundHandlerThread.quitSafely()`? I think it does block the thread. CMIIW

**Comment by rifkyputra** [comment] 2022-08-10 14:04
This issue could be caused by unhandled catch error when calling `initialize`.

In my case i simply add `.catchError` and the problem is gone.

![image](https://user-images.githubusercontent.com/11476083/183919800-d6089f6b-5c95-478c-955d-00eea1b117b7.png)

maybe you're just following example code from previous version :

https://pub.dev/packages/camera/versions/0.9.4+24

catchError is not there yet. but in recent version, there's a catchError in `initialize`.

**Comment by camsim99** [comment] 2022-08-10 18:37
> Anyway do we really need `backgroundHandlerThread.join()` after `backgroundHandlerThread.quitSafely()`? I think it does block the thread. CMIIW

@tijanirf I think you're right. I don't think we do since we do not rely on the tasks on this thread finishing before doing any work on another. I'll make a PR to remove it.

**Comment by tijanirf** [comment] 2022-09-12 06:17
Hi @camsim99,

I saw the [PR](https://github.com/flutter/plugins/pull/6224) is already merged, but the latest camera package is still `0.10.0+1`

Do you know when it will be released on pub.dev? Sorry, I don't quite understand the release process of the flutter plugin. If the release time is unknown I am considering to fork and apply your PR changes because the ANR number is really concerning.

Thanks

**Comment by camsim99** [comment] 2022-09-12 18:41
@tijanirf Right now, the `camera` plugin depends on the `camera_android` version `^0.1.10`([source](https://github.com/flutter/plugins/blob/main/packages/camera/camera/pubspec.yaml#L24)), but my changes may not be included since a new version of the `camera` plugin hasn't been published since. My changes are in version `0.10.0+2`, so I would try forking it and specifying that version for `camera_android` to ensure the changes are applied!

**Comment by stuartmorgan** [comment] 2022-09-12 19:52
> @tijanirf Right now, the `camera` plugin depends on the `camera_android` version `^0.1.10`([source](https://github.com/flutter/plugins/blob/main/packages/camera/camera/pubspec.yaml#L24)), but my changes may not be included since a new version of the `camera` plugin hasn't been published since.

To clarify since the typo is important here: it relies on `^0.10.1`, which is a range that includes any `0.10.*` version.

We don't generally publish updates to the app-facing packages just to require the latest version of the implementation packages. Developers should be updating all of their transitive includes, not just their direct dependencies.

> My changes are in version `0.10.0+2`, so I would try forking it and specifying that version for `camera_android` to ensure the changes are applied!

There is no need to fork anything. All someone has to do is `flutter pub upgrade` to update their transitive dependencies (which is something that should be done regularly regardless, to pick up bug fixes in transitive dependencies).

Closing as the fix has been published, and this isn't something we would update `camera` for.

**Closed by stuartmorgan** 2022-09-12 19:52 UTC
Labels: platform-android, engine, plugin, p: camera, a: release, a: production, P4, severe: fatal crash

**Comment by tijanirf** [comment] 2022-09-13 01:34
@camsim99 @stuartmorgan Thank you for the detailed answer, well noted
