### ISSUE TITLE
Maps Support

### ISSUE THREAD

**Issue by charlieforward9** [flutter/flutter#119068] opened 2023-01-24 15:17 UTC
## Use case

Our company is a map-based SaaS that is looking to rebuild our application using Flutter for Web, iOS, and Andriod support. I noticed that the google_maps_flutter package for mobile is separate from the package for the Web. I am curious why they are not merged and would like to know the timeline for that if that is under discussion. 

Furthermore, I notice that there are a handful of features that are not currently supported on the web version, apart from an update on their status, I'd like to get about the teams' opinion on developing this map-based application using Flutter as the primary UI framework vs sticking to a JS-based framework where maps seem to have more robust support. (I know the team is busy solving framework issues so a brief, simple explanation suffices)

## Proposal

Combine the two Google Maps packages into one. Please refer me to the relevant issue if it is already open.

Thank you

**Comment by stuartmorgan** [comment] 2023-01-24 15:33
> I noticed that the google_maps_flutter package for mobile is separate from the package for the Web.

This is not unique to web; every platform's implementation is separate in our fully-federated plugin structure. `google_maps_flutter_web` is a peer of `google_maps_flutter_ios` and `google_maps_flutter_android`, and uses the same structure. The only difference is that `google_maps_flutter_web` is not endorsed yet, so you have to explicitly opt in to adding that implementation. Once you do you still just use `google_maps_flutter`'s API on all platforms, including web.

> I notice that there are a handful of features that are not currently supported on the web version, apart from an update on their status

You can follow the relevant issues for updates on their status (or file issues for any features that you would like to see supported that currently aren't). [This query](https://github.com/flutter/flutter/issues?q=is%3Aopen+label%3A%22p%3A+maps%22+label%3Aplatform-web) should be helpful in locating existing issues.

> I'd like to get about the teams' opinion on developing this map-based application using Flutter as the primary UI framework

The Flutter team generally can't provide guidance on individual projects; you could consider getting community feedback from one of the resources at https://flutter.dev/community#community-grid.

> Combine the two Google Maps packages into one. Please refer me to the relevant issue if it is already open.

Closing as a duplicate of https://github.com/flutter/flutter/issues/80688.

**Closed by stuartmorgan** 2023-01-24 15:33 UTC
