### ISSUE TITLE
Custom Info Window Of Marker In Google Maps

### ISSUE THREAD

**Issue by MOhsain** [flutter/flutter#53633] opened 2020-03-31 07:22 UTC
Please tell me how to make custom info window of marker in google marker, i done lot of search but cant find any solution. so please guide me

**Comment by TahaTesser** [comment] 2020-03-31 07:37
Duplicate of [#24213](https://github.com/flutter/flutter/issues/24213)

**Closed by TahaTesser** 2020-03-31 07:37 UTC

**Comment by MOhsain** [comment] 2020-03-31 12:27
Not closed. Read my statement, i want to change marker info window(When you click on marker then its show a text at the top of marker, its an info window) not marker. 
Your link is about to change the marker, please suggest main another solution related to info window

**Comment by MOhsain** [comment] 2020-03-31 12:27
Not closed. Read my statement, i want to change marker info window(When you
click on marker then its show a text at the top of marker, its an info
window) not marker.
Your link is about to change the marker, please suggest main another
solution related to info window

**Comment by TahaTesser** [comment] 2020-03-31 12:31
Updated the comment

**Comment by MOhsain** [comment] 2020-03-31 13:16
Thanks But Your provided solution is not workable. Please check its Issue here is the link --> https://github.com/Menelphor/GoogleMapsCustomInfoWidget/issues/1.
Please talk to Flutter Library Devs to change the infoWindow into Widget, everyone will change this  into desired views.
The thing i want, i want to change its Info Window as per i need, like i'll add User Profile, name etc, but this solution is only for change the info window text style.
So now i'm waiting again :(

**Comment by MOhsain** [comment] 2020-03-31 13:33
Thanks But Your provided solution is not workable. Please check its Issue
here is the link --> Menelphor/GoogleMapsCustomInfoWidget#1
<https://github.com/Menelphor/GoogleMapsCustomInfoWidget/issues/1>.
Please talk to Flutter Library Devs to change the infoWindow into Widget,
everyone will change this into desired views.
The thing i want, i want to change its Info Window as per i need, like i'll
add User Profile, name etc, but this solution is only for change the info
window text style.
So now i'm waiting again :(

**Comment by TahaTesser** [comment] 2020-03-31 14:07
Hi @MOhsain 
Custom infoWindow is not supported yet in the package
Thank you
