### ISSUE TITLE
Playing DRM Video content in Flutter 

### ISSUE THREAD

**Issue by harsh5400** [flutter/flutter#50554] opened 2020-02-11 10:54 UTC
Hello Everyone,

I am creating a VOD Mobile Application for TATASKY in India.

The main issue which I am facing is Playing of DRM (.m3u8 format with a License URL) content in Flutter using a video_player widget.

Has anybody tried playing Protected DRM content in Flutter?

**Comment by TahaTesser** [comment] 2020-02-11 10:58
Hi @harsh5400 
Closing as this duplicate of [#24923](https://github.com/flutter/flutter/issues/24923) 
Thank you

**Closed by TahaTesser** 2020-02-11 10:58 UTC
