### ISSUE TITLE
flutter drive -d chrome fails with SocketException

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#50605] opened 2020-02-11 22:01 UTC
We should either make it work or produce a much better error message.

## command

```
flutter drive -d chrome -t lib/stack_trace.dart
```

## exception

```
SocketException: SocketException: Connection failed (OS Error: Connection refused, errno = 111), address = localhost, port = 4444

#0      _NativeSynchronousSocket.connectSync.connectNext (dart:io-patch/sync_socket_patch.dart:91:9)
#1      _NativeSynchronousSocket.connectSync.connectNext (dart:io-patch/sync_socket_patch.dart:102:27)
#2      _NativeSynchronousSocket.connectSync.connectNext (dart:io-patch/sync_socket_patch.dart:102:27)
#3      _NativeSynchronousSocket.connectSync (dart:io-patch/sync_socket_patch.dart:118:23)
#4      _RawSynchronousSocket.connectSync (dart:io-patch/sync_socket_patch.dart:25:34)
#5      RawSynchronousSocket.connectSync (dart:io-patch/sync_socket_patch.dart:13:34)
#6      new SyncHttpClientRequest._ (package:sync_http/src/sync_http.dart:67:45)
#7      SyncHttpClient.postUrl (package:sync_http/src/sync_http.dart:20:11)
#8      SyncHttpRequestClient.sendRaw (package:webdriver/src/request/sync_http_request_client.dart:20:38)
#9      SyncRequestClient.send (package:webdriver/src/common/request_client.dart:46:26)
#10     createDriver (package:webdriver/sync_core.dart:63:26)
#11     createDriver (package:webdriver/sync_io.dart:35:5)
#12     _createDriver (package:flutter_tools/src/commands/drive.dart:441:10)
#13     DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:182:16)
<asynchronous suspension>
```

/cc @angjieli @nturgut

**Comment by jonahwilliams** [comment] 2020-02-11 22:06
Duplicate of https://github.com/flutter/flutter/issues/50146

**Closed by jonahwilliams** 2020-02-11 22:06 UTC
Labels: t: flutter driver, ☸ platform-web
