### ISSUE TITLE
iframe is not working for Desktop platforms.

### ISSUE THREAD

**Issue by unoravi** [flutter/flutter#76105] opened 2021-02-16 11:09 UTC
iframe HTML contents and URL are displaying properly on Android device using "webview_flutter" dev_dependencies. Same thing is not working on Desktop platforms Windows/Linux. I have also tried by creating local class by implementing WebViewPlatform class.

flutter doctor -v

````
[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.27.0-1.0.pre at /home/ravi/flutter
    • Framework revision 68c96f100e (7 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.146

! Doctor found issues in 2 categories.
````
Please let me know if anyway I can have it running.

Thanks

**Comment by TahaTesser** [comment] 2021-02-16 11:42
Hi @unoravi 
Desktop doesn't support platformview  supported yet https://github.com/flutter/flutter/issues/41724  https://github.com/flutter/flutter/issues/31713  so you can't use iFrame, webview
Closing as duplicate of https://github.com/flutter/flutter/issues/41724

**Closed by TahaTesser** 2021-02-16 11:42 UTC
Labels: in triage

**Comment by unoravi** [comment] 2021-03-17 09:39
@TahaTesser 
Please let me know whenever it starts supporting iFrame, webview for Desktops..

Thanks
