### ISSUE TITLE
[path_provider] path_provider_android 2.0.10 throws MissingPluginException on older versions of Flutter

### ISSUE THREAD

**Issue by JamesKarl** [flutter/flutter#95706] opened 2021-12-23 02:34 UTC
The following code works well with path_provider 2.0.1. After upgrading to 2.0.8, it throws "MissingPluginException(No implementation found for method getApplicationDocumentsDirectory.
```dart
final doc = await getApplicationDocumentsDirectory();
```

**Comment by sara010** [comment] 2021-12-23 03:46
same problem

**Comment by 6a209** [comment] 2021-12-23 05:37
the same problem

**Comment by maheshmnj** [comment] 2021-12-23 08:13
Hi @JamesKarl, Thanks for filing the issue. I ran the [official sample code ](https://pub.dev/packages/path_provider/example) using `path_provider: ^2.0.8` and I could not reproduce the issue.

<img src="https://user-images.githubusercontent.com/31410839/147209368-62cc9cb9-428d-409e-b8f7-95cd25f2ac0f.png" width ="300">
 
Please share the output of `flutter doctor -v` and a minimal and complete reproducible code sample.


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.7:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by medyas** [comment] 2021-12-23 13:17
@maheshmnj Having the same issue:
```bash
E/flutter (32229): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (32229): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter (32229): <asynchronous suspension>
E/flutter (32229): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115)
E/flutter (32229): <asynchronous suspension>
E/flutter (32229): #2      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12)
E/flutter (32229): <asynchronous suspension>
E/flutter (32229): #3      main (package:flutterbaytemployer/main.dart:28)
E/flutter (32229): <asynchronous suspension>
```

It was building using the lastest `path_provider_android-2.0.10`
Quick fix for this is to override the version and have 2.0.9
```yaml
dependency_overrides:
  path_provider_android: 2.0.9
```

The plugin was trying to connect through `plugins.flutter.io/path_provider`  as per the [`path_provider_platform`](https://github.com/flutter/plugins/blob/0619c3a9b81be1e20480c1ba82eddd41b49ea2c2/packages/path_provider/path_provider_platform_interface/lib/src/method_channel_path_provider.dart#L16) but the latest [`path_provider_android:2.0.10`](https://github.com/flutter/plugins/blob/0619c3a9b81be1e20480c1ba82eddd41b49ea2c2/packages/path_provider/path_provider_android/lib/path_provider_android.dart#L13) update changed the channel to `plugins.flutter.io/path_provider_android`

**Comment by stuartmorgan** [comment] 2021-12-23 15:47
What version of Flutter is everyone who is seeing this using? If it's 2.5 or earlier, that's a known bug in the update to the Android implementation. If it's 2.8, that's unexpected.

**Comment by medyas** [comment] 2021-12-23 16:47
@stuartmorgan only failing in version 2.5.3, this did not occur in the latest 2.8.1

**Comment by gabrielchavestoro** [comment] 2021-12-23 17:22
Same problem here. The dependencie override suggested by @medyas worked but I wouldn't like to deploy a version with it. Will we be able to revert the change until today?

**Closed** 2021-12-23 18:29 UTC
Labels: severe: regression, platform-android, plugin, p: first party, p: path_provider, in triage, P3

**Comment by stuartmorgan** [comment] 2021-12-23 19:26
`path_provider_android` 2.0.11 has been published to fix this.
