### ISSUE TITLE
Could not ensure the target project location exists and is accessible:

### ISSUE THREAD

**Issue by tz182736** [flutter/flutter#46917] opened 2019-12-12 23:27 UTC
2 encounter same issues.

1 - I am trying to use ramdisk as build location for my flutter project and encounter symbolic link error .
2 - So as another attempt create new flutter project on ramdisk and following error encounter.
 - Could not ensure the target project location exists and is accessible

Steps to reproduce:
Create RAM Disk (using Imdisk or ROG same result)
Create new flutter project on Ram Disk ( R:\ )

## Logs

The log below is from another project , but same machine and same issues.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --verbose assemble --depfile R:\build\app\intermediates\flutter\debug/flutter_build.d --output R:\build\app\intermediates\flutter\debug -dTargetFile=C:\_dev\easytech\ET LOTTERY\et_lottery_app_flutter\lib\main.dart -dTargetPlatform=android -dBuildMode=debug debug_android_application

## exception

FileSystemException: FileSystemException: Cannot resolve symbolic links, path = 'R:\build\app\intermediates\flutter\debug' (OS Error: Incorrect function.
, errno = 1)

```
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:833:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:397:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:58:49)
#3      SourceVisitor.visitPattern (package:flutter_tools/src/build_system/source.dart:121:49)
#4      _PatternSource.accept (package:flutter_tools/src/build_system/source.dart:213:49)
#5      Target._resolveConfiguration (package:flutter_tools/src/build_system/build_system.dart:234:14)
#6      Target.resolveOutputs (package:flutter_tools/src/build_system/build_system.dart:192:12)
#7      Target._toNode (package:flutter_tools/src/build_system/build_system.dart:136:39)
#8      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:420:30)
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:170:50)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1465:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1465:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:112:14)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#32     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _runZoned (dart:async/zone.dart:1518:10)
#36     runZoned (dart:async/zone.dart:1502:12)
#37     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#39     _rootRun (dart:async/zone.dart:1126:13)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _runZoned (dart:async/zone.dart:1518:10)
#42     runZoned (dart:async/zone.dart:1465:12)
#43     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#44     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#45     run (package:flutter_tools/runner.dart:50:10)
#46     main (package:flutter_tools/executable.dart:65:9)
#47     main (file:///C:/_packages/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#48     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\_packages\flutter
    • Framework revision 27321ebbad (33 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\_packages\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\_packages\android-sdk
    • Java binary at: C:\_applications\android-studio-3.5.3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\_applications\android-studio-3.5.3
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by tz182736** [comment] 2019-12-12 23:29
![flutter error](https://user-images.githubusercontent.com/46246407/70757358-a845aa00-1d6d-11ea-8981-d8316086120d.png)

**Comment by christopherfujino** [comment] 2020-01-17 19:50
Thanks for filling this, but I am closing this as a duplicate of https://github.com/flutter/flutter/issues/26113. Please thumbs up that issue and follow for updates!

**Closed by christopherfujino** 2020-01-17 19:50 UTC
Labels: severe: crash, tool
