### ISSUE TITLE
Please add macOS support to package_info

### ISSUE THREAD

**Issue by sma** [flutter/flutter#56241] opened 2020-05-03 15:04 UTC
The `package_info` plugin only works on iOS and Android. Please make it work on macOS, too.

I think the iOS specific Objective-C code should work on macOS, too, so only the project configuration needs to be extended.

**Comment by stuartmorgan** [comment] 2020-05-03 22:14
Duplicate of https://github.com/flutter/flutter/issues/41727

**Closed by stuartmorgan** 2020-05-03 22:14 UTC
