### ISSUE TITLE
Exception:  'toDouble' was called on null' on IOS

### ISSUE THREAD

**Issue by JuliusNM** [flutter/flutter#31195] opened 2019-04-17 13:16 UTC
## Steps to Reproduce

1. `flutter run -t lib/main_prod.dart`
2. Exception appears and disappears as soon as the app loads/builds properly
3. This only happens on iOS device.
4. Project available here >> https://github.com/JuliusNM/Frecipe

## Logs
```
[ +201 ms] flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] flutter: The following NoSuchMethodError was thrown building Builder(dirty, dependencies: [MediaQuery]):
[        ] flutter: The method 'toDouble' was called on null.
[        ] flutter: Receiver: null
[        ] flutter: Tried calling: toDouble()
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[  +49 ms] flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
[        ] flutter: #1      double.> (dart:core-patch/double.dart:87:31)
[        ] flutter: #2      _NestedScrollCoordinator.hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:501:27)
[   +7 ms] flutter: #3      _NestedScrollViewState.build.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:344:47)
[   +1 ms] flutter: #4      Builder.build (package:flutter/src/widgets/basic.dart:6233:41)
[        ] flutter: #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
[        ] flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
[        ] flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[   +6 ms] flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #26     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
[        ] flutter: #27     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
[        ] flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #45     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #51     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #55     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #59     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #63     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #67     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #71     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #81     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #85     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[   +1 ms] flutter: #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #87     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
[        ] flutter: #88     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
[        ] flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #94     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[   +3 ms] flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #98     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #100    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #104    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #106    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[   +1 ms] flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[   +5 ms] flutter: #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[   +1 ms] flutter: #110    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[   +1 ms] flutter: #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #114    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #118    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[   +1 ms] flutter: #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[   +2 ms] flutter: #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[   +1 ms] flutter: #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[   +1 ms] flutter: #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[   +1 ms] flutter: #124    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[   +1 ms] flutter: #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[  +52 ms] flutter: #126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #130    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #134    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #136    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #140    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[+1260 ms] flutter: #144    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
[   +4 ms] flutter: #145
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:700:20)
[        ] flutter: #146
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:286:5)
[        ] flutter: #147    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1012:15)
[   +4 ms] flutter: #148    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:952:9)
[        ] flutter: #149    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:773:7)
[        ] flutter: #158    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
[        ] flutter: #159    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
[   +4 ms] flutter: #160    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
[        ] flutter: (elided 8 frames from package dart:async and package dart:async-patch)
[   +3 ms] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
[ +471 ms] Scanned through 0 files in 0ms
[   +1 ms] Syncing files to device Julius Mburu’s iPhone...
[   +1 ms] Scanning asset files
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +9 ms] /Users/julius/development/flutter/bin/cache/dart-sdk/bin/dart
/Users/julius/development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/julius/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build/app.dill --packages
/Users/julius/AndroidStudioProjects/frecipe/.packages --filesystem-scheme org-dartlang-root
[  +10 ms] <- compile package:Frecipe/main_prod.dart
```
```
```

`flutter analyze`
No issues found! (ran in 65.3s)

```
```

`flutter doctor -v`

[✓] Flutter (Channel master, v1.5.2-pre.3, on Mac OS X 10.13.6 17G6030, locale en-KE)
    • Flutter version 1.5.2-pre.3 at /Users/julius/development/flutter
    • Framework revision ca46fc03de (11 hours ago), 2019-04-16 22:27:18 -0400
    • Engine revision 388124f948
    • Dart version 2.3.0 (build 2.3.0-dev.0.0 8e73b3c006)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/julius/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Julius Mburu’s iPhone • 00032057848b762b448d1a0b36cf672226e6ecf9 • ios • iOS 12.1.3

• No issues found!

```
```

**Comment by Hixie** [comment] 2019-07-03 22:02
https://github.com/flutter/flutter/issues/28351 may be related.

**Comment by chunhtai** [comment] 2019-07-03 22:17
The issue is during runapp, widgetbinding will first build the root by running attachRootWidget, after that it schedule an asynchronized task to draw the first warm up frame.

The widget first built in attachRootWidget, and then built again in the drawframe. In the middle of this two built, a the runtimecontroller in engine will get initialized and fire a usersettingupdate which change the text styling or some other user setting. This will dirty widgetapp which will cause drawframe to rebuild the dirty element. The Nestedscrollview crash if you build it twice without laying it out.

**Comment by dnfield** [comment] 2019-07-03 22:25
I know we've been looking at the more comprehensive solution of solving the first part of the problem @chunhtai  mentioned, but perhaps for now we could just make NestedScrollView resillient to getting build called without a layout?  

Would it be enough to set `_lastHasScrolledBody` only in layout instead of in build?

**Comment by chunhtai** [comment] 2019-07-03 22:55
I am trying to see if I can defer the first build and merge that into schedule warm up frame. If we are building something that is not immediately required and might be dirty later anyway. we might as well just build it at the warm up frame. I am not sure if this is even possible, and if it will have performance impact.

but it does seem that Nestedscrollview should be able to build twice without layout, and it is more like a bug that i can't.

**Comment by CocoaZX** [comment] 2019-07-15 03:42
so how to fix that for now?

**Comment by chunhtai** [comment] 2019-07-15 16:13
@CocoaZX for now, you can apply this patch https://github.com/flutter/flutter/pull/36097 to fix it. We are still not certain what the right fix is.

**Comment by chunhtai** [comment] 2019-07-17 16:31
The fixed is merged now, you should not see the exception with the fix.

We will still need to figure out the double build issue, I will keep this issue open

**Comment by robin7331** [comment] 2019-08-14 08:58
How can I actually apply this fix to my project?
You said you merged it. Into the main branch according to the PR.
But if I run `flutter upgrade` I won't have this issue fixed.
Even if I choose the latest version by running `flutter version v1.8.3`

Sorry. I'm just not familiar with the terminology :)

**Comment by chunhtai** [comment] 2019-08-14 16:17
1.8.3 should include the fix.

Can you post the full error message and a reproducible code?

**Comment by robin7331** [comment] 2019-08-14 16:23
Actually I just tried 1.8.4 and this release has you changes. And it works!

**Comment by chunhtai** [comment] 2019-08-21 00:00
simplify repro
```

import 'package:flutter/material.dart';

class App extends StatefulWidget {
  @override
  AppState createState() {
    return AppState();
  }
}

class AppState extends State<App> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'test',
      home: Home(),
      initialRoute: '/home',
      routes: <String, WidgetBuilder>{
        '/home': (BuildContext context) => Home(),
      },
    );
  }
}

class Home extends StatelessWidget {
  Home(): super();
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder:
          (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              title: Text('text'),)
          ];
        },
        body: ListView(
          children: <Widget>[
            SizedBox(height: 40.0),
          ],
        )
      ),

    );
  }
}

void main() {
  runApp(App());
}
```

**Closed** 2019-09-06 16:46 UTC
Labels: f: scrolling, framework, severe: crash
