### ISSUE TITLE
App crashes while using VoiceOver

### ISSUE THREAD

**Issue by kennethj** [flutter/flutter#58600] opened 2020-06-03 15:01 UTC
When closing a scaffold drawer with a `FlatButton` while using VoiceOver, the app crashes.

## Reproduce
1. Open drawer in app
2. Turn on VoiceOver
3. Tap `FlatButton` to close drawer

## Code
```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey();
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'VO drawer bug',
        home: Material(
          child: Scaffold(
            key: _scaffoldKey,
            drawer: Drawer(
              child: Builder(
                builder: (context) => Center(
                  child: FlatButton(
                    child: Text("close"),
                    onPressed: () => Navigator.pop(context),
                  ),
                ),
              ),
            ),
            body: Center(
              child: FlatButton(
                child: Text("open"),
                onPressed: () => _scaffoldKey.currentState.openDrawer(),
              ),
            ),
          ),
        ),
      );
}
```

**Comment by VladyslavBondarenko** [comment] 2020-07-30 08:28
Hi @kennethj 
does the issue persist? could you provide your `flutter doctor -v`? I can't reproduce it with current master `1.21.0-6.0.pre.117` running on iPhone 7 iOS 13.6

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.117 at /Users/nevercode/dev/flutter
    • Framework revision 7ec2d360bc (2 hours ago), 2020-07-29 23:25:38 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by markusaksli-nc** [comment] 2020-08-28 12:01
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

Thanks for your contribution.

**Closed by markusaksli-nc** 2020-08-28 12:01 UTC
Labels: a: accessibility, f: material design, framework, has reproducible steps, platform-ios, waiting for customer response
