### ISSUE TITLE
google_sign_in: readme "register your application" link under android section goes to unhelpful page

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#78063] opened 2021-03-12 19:44 UTC
https://developers.google.com/mobile/add?platform=android redirects to https://firebase.google.com/?platform=android

...which isn't helpful.

Should fix this!

**Comment by 2002Bishwajeet** [comment] 2021-03-14 08:36
Hey, I Would Like to work on this issue, Could you provide me some tips on how to Proceed???

**Comment by TahaTesser** [comment] 2021-03-24 12:19
Looks like a duplicate of https://github.com/flutter/flutter/issues/68039

**Closed by TahaTesser** 2021-03-24 12:19 UTC
Labels: documentation, easy fix, p: first party, p: google_sign_in, passed first triage, plugin

**Comment by TahaTesser** [comment] 2021-03-24 12:21
@2002Bishwajeet 
Please read through the [Contributors guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md)
