### ISSUE TITLE
unclear how to use flutter build.

### ISSUE THREAD

**Issue by gregsimon** [flutter/flutter#3146] opened 2016-04-06 20:21 UTC
$ flutter build
Missing subcommand for "flutter build".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

--> what are the subcommands? flutter -h is no help:
...
Available commands:
  analyze      Analyze the project's Dart code.
  build        Flutter build commands.
...

**Comment by abarth** [comment] 2016-04-06 20:26
@devoncarew

**Comment by abarth** [comment] 2016-04-06 20:26
`flutter build -h` shows the subcommands.  Probably `flutter build` should print its own help by default.

**Comment by sethladd** [comment] 2016-04-06 20:28
Dupe of https://github.com/flutter/flutter/issues/3145

**Closed** 2016-04-06 21:29 UTC
Labels: affects: dev experience, affects: tools, ⚠ bug
