### ISSUE TITLE
Make generated code null safe intl

### ISSUE THREAD

**Issue by nimr77** [flutter/flutter#77291] opened 2021-03-04 21:44 UTC
This Error is after going to dart 2.12, with null safety, I had this error in my generated code, for intl, which can be fixed by adding the @dart = 2.9, yet it keeps changing to an error every time I do update my language code.

this is blocking and slowing the development of my apps, please if there is a way around this without disabling the null safety.

**Comment by TahaTesser** [comment] 2021-03-05 09:06
Hi @nimr77 
Can you please provide your `flutter doctor -v` and  `pubspec.yaml` and `flutter pub get` output?
Thank you

**Comment by nimr77** [comment] 2021-03-05 12:21
[✓] Flutter (Channel stable, 2.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.0 at /home/nimr/snap/flutter/common/flutter
    • Framework revision 60bd88df91 (2 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/nimr/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /var/lib/snapd/snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /var/lib/snapd/snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /var/lib/snapd/snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.146

• No issues found!

**Comment by TahaTesser** [comment] 2021-03-08 07:21
Hi @nimr77 
It seems you're using third-party packages to achieve intl code generation,  

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repository.
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-08 07:21 UTC
Labels: in triage
