### ISSUE TITLE
flutter.gradle : flutter.sdk must point to the Flutter SDK directory

### ISSUE THREAD

**Issue by narcdev** [flutter/flutter#95491] opened 2021-12-18 07:29 UTC
## Steps to Reproduce

I'm trying to run my app on Flutter channel Beta : Flutter 2.9.0-0.1.pre with Android Studio.

I have to use the Beta channel cause my app need this fix : https://github.com/flutter/flutter/commit/f802e639b2d4615287b80b1c2d186be27c1b15e6

What I'm doing :
1.  flutter clean
2. flutter pub get
3. flutter run

## Logs

<details>
<summary>Logs</summary>

```
1: Task failed with an exception.
-----------
* Where:
Script '/opt/homebrew/Caskroom/flutter/2.8.0/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 214

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin class 'FlutterPlugin'.
   > flutter.sdk must point to the Flutter SDK directory
```

```
[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 12.0.1 21A559 darwin-arm, locale fr-FR)
    • Flutter version 2.9.0-0.1.pre at /opt/homebrew/Caskroom/flutter/2.8.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (3 days ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/builder/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 12 (API 31) (emulator)
```

</details>

**Comment by mamuseferha** [comment] 2021-12-20 07:38
Hi @narcdev Looks like flutter.sdk is pointing to the wrong directory.
Can you please paste the content of your local.properties file. Thank you

**Comment by narcdev** [comment] 2021-12-20 08:16
> Hi @narcdev Looks like flutter.sdk is pointing to the wrong directory. Can you please paste the content of your local.properties file. Thank you

Of course, please find here the content of my local.properties file

```
sdk.dir=/Users/builder/Library/Android/sdk
flutter.sdk=/opt/homebrew/Caskroom/flutter/2.8.0/flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
```

And `/opt/homebrew/Caskroom/flutter/2.8.0/flutter `seems OK, I've installed Flutter with Homebrew.

**Comment by mamuseferha** [comment] 2021-12-21 08:06
Hi @narcdev, you are on the latest beta `2.9.0-0.1.pre` but your flutter version seems to be pointing to `2.8.0`. Can you please provide the version of homebrew you are currently using so I can reproduce on my end?

**Comment by mamuseferha** [comment] 2021-12-21 08:12
@narcdev, please also provide your flutter root path in your bashrc / zshrc file using this command `echo $PATH`.

**Comment by narcdev** [comment] 2021-12-21 08:12
> Hi @narcdev, you are on the latest beta `2.9.0-0.1.pre` but your flutter version seems to be pointing to `2.8.0`. Can you please provide the version of homebrew you are currently using so I can reproduce on my end?

Yes, here it is 

```
brew --version
Homebrew 3.3.7
Homebrew/homebrew-core (git revision e160df1adbf; last commit 2021-12-12)
Homebrew/homebrew-cask (git revision 2cb2f004e9; last commit 2021-12-12)
```

The directory is `/opt/homebrew/Caskroom/flutter/2.8.0/flutter`, but inside it's the latest beta branch

```
builder@MacBook-Pro flutter % pwd
/opt/homebrew/Caskroom/flutter/2.8.0/flutter
builder@MacBook-Proflutter % git status
On branch beta
Your branch is up to date with 'origin/beta'.

nothing to commit, working tree clean
```

**Comment by narcdev** [comment] 2021-12-21 08:13
> @narcdev, please also provide your flutter root path in your bashrc / zshrc file using this command `echo $PATH`.

And the result of `echo $PATH` 

```
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
```

**Comment by mamuseferha** [comment] 2021-12-22 07:42
Hi @narcdev, add `/opt/homebrew/Caskroom/flutter/2.8.0/flutter/bin` to your path and see if it works.
https://docs.flutter.dev/get-started/install/macos#update-your-path

**Comment by narcdev** [comment] 2021-12-22 09:35
> Hi @narcdev, add `/opt/homebrew/Caskroom/flutter/2.8.0/flutter/bin` to your path and see if it works. https://docs.flutter.dev/get-started/install/macos#update-your-path

Yes now it works ! Thanks a lot

**Comment by mamuseferha** [comment] 2021-12-22 09:53
Hi @narcdev 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by mamuseferha** 2021-12-22 09:53 UTC
Labels: in triage
