### ISSUE TITLE
[Impeller] ImageFilter.blur is not shown the correct Intensity.

### ISSUE THREAD

**Issue by kuemme01** [flutter/flutter#127923] opened 2023-05-31 07:34 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Build an UI example in Figma or other design program with blurring background for example with an intensity of 120.
2. Rebuild the UI in Flutter by using ImageFiltered widget and use a sigmaX/Y of 120.
3. Recognize the blur effect is way to high.
4. Play with sigmaX/Y and find a match to your Figma template by ~60 (maybe higher).

### Expected results

The intensity of sigmaX/Y should have around the same result as in common graphic programs, like it was before the fix for:
https://github.com/flutter/flutter/issues/126487

### Actual results

After updating to the newest version including the fix for https://github.com/flutter/flutter/issues/126487 I was happy for the fixed bug about a maximum sigmaX/Y of 85, but recognized the value I pass no longer match my template.

The intensity of sigmaX/Y is around double the intensity of the result in common graphic programs.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int? textFieldValue = 0;
  int? sliderValue = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Card(
          clipBehavior: Clip.hardEdge,
          child: Container(
            height: 200,
            width: double.infinity,
            color: Colors.cyan,
            child: ImageFiltered(
              imageFilter: ImageFilter.blur(
                sigmaX: 60.0,
                sigmaY: 60.0,
              ),
              child: Container(
                width: 80,
                height: 80,
                decoration: const BoxDecoration(
                  color: Colors.cyanAccent,
                  shape: BoxShape.circle,
                ),
              ),
            ),
          ),
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Example screenshots from my project, optical different from code example but same implementation.

Flutter ImageFiltered with sigmaX/Y 60.0:
<img width="369" alt="sigma60" src="https://github.com/flutter/flutter/assets/26045175/5516c31d-0d58-4b1a-8aff-0c2b0640831d">

Flutter ImageFiltered with sigmaX/Y 120.0:
<img width="372" alt="sigma120" src="https://github.com/flutter/flutter/assets/26045175/13f7fbef-c73a-4c93-ab60-dff4c0823c4a">

Figma BackgroundBlur with value of 60.0:
<img width="1284" alt="Bildschirmfoto 2023-05-31 um 09 21 05" src="https://github.com/flutter/flutter/assets/26045175/56c21a82-1b61-4e1f-8546-d855d8671a9a">

Figma BackgroundBlur with value of 120.0:
<img width="1293" alt="Bildschirmfoto 2023-05-31 um 09 20 47" src="https://github.com/flutter/flutter/assets/26045175/4cca9a91-5402-48dc-a241-cb457c1478bf">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E772610a darwin-arm64, locale de-DE)
    • Flutter version 3.10.2 on channel stable at /Users/.../Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (7 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/.../Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by huycozy** [comment] 2023-05-31 12:43
Thanks for filing the issue. Since you use `cyan` color instead, It's not easy to compare. Even though, I see it displays correctly when sigma is 60, it doesn't seem to be correct with sigma 120.

Also, I see there are different results between stable and master channels as below demo. Labeling the issue for further insights.

<details>
<summary>Demo stable</summary>

| sigma 60 | sigma 120 |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/90a9e34f-dbf1-4639-b3f4-98f44283f2eb"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/148058ef-0caf-4ae4-97e8-a4b7893f4bd8">

</details>

<details>
<summary>Demo master channel</summary>

| sigma 60 | sigma 120 |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/205700e9-becf-4d31-a271-b16f0410052a"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/beb628f3-d6ab-42e2-9dfc-61ebba254b0f">

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (22 hours ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-16.0.pre.21, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-16.0.pre.21 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f4662beeb6 (20 minutes ago), 2023-05-30 23:09:32 -0400
    • Engine revision 7a4a267d8a
    • Dart version 3.1.0 (build 3.1.0-155.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by kuemme01** [comment] 2023-05-31 13:26
Yeah, I also recognized it while writing the issue. In direct compare its not really doubled but different as expected and definitely different as before https://github.com/flutter/flutter/issues/126487 was fixed.

**Comment by bdero** [comment] 2023-07-14 22:53
Ah, I believe this is a duplicate of https://github.com/flutter/flutter/issues/130411, which happened to get filed a couple of days before this one. Either way, it's nice to have this example reproduction to reference, thanks!

**Closed by bdero** 2023-07-14 22:53 UTC
Labels: platform-ios, engine, has reproducible steps, P2, e: impeller, found in release: 3.10, found in release: 3.11, team-ios, triaged-ios, multiteam-retriage-candidate

**Comment by bdero** [comment] 2023-07-14 22:56
(Although the reproduction in https://github.com/flutter/flutter/issues/127770 uses a mask filter, both reproductions are using the same Gaussian blur path internally in Impeller)
