### ISSUE TITLE
Different environment path when build with Android Studio, Xcode and build a release app

### ISSUE THREAD

**Issue by LeXuanKhanh** [flutter/flutter#75911] opened 2021-02-12 14:53 UTC
I try to run some command using Process on Mac OS like `brew --version`, it run fine when i run on Android Studio but when i try to run on Xcode or build the release app it can't the command and always tell the executable is not found

After print the environment variables, i found out that these variables are different between building with Android Studio, Xcode and release, especially the PATH variable

Android Studio:
`  "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/macbook/Developer/flutter/bin:/Users/macbook/Library/Android/sdk/emulator:/Users/macbook/Library/Android/sdk/tools:/Users/macbook/Library/Android/sdk/tools/bin:/Users/macbook/Library/Android/sdk/platform-tools:/Users/macbook/Library/Python/3.8/bin"`

XCode:
`"PATH": "/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"`

Release app:
`"PATH": "/usr/bin:/bin:/usr/sbin:/sbin"`

It seem missing the /usr/local/bin, which contain brew and many important executables 
I expected that the environment is the same at-least  on debug mode, despite run on different IDEs
Is this a bug or because i need more config ? How can I make environment variables the same between IDEs, or maybe in different environment mode ?

**Comment by TahaTesser** [comment] 2021-02-15 07:25
Hi @LeXuanKhanh 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by LeXuanKhanh** [comment] 2021-02-16 03:46
Flutter doctor -v:

```
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-US)
    • Flutter version 1.26.0-12.0.pre at /Users/macbook/Developer/flutter
    • Framework revision a706cd2112 (5 weeks ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/macbook/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.7 19H2 darwin-x64

• No issues found!
```

Example: press the floating button to print the environment variables to screen

```
import 'package:flutter/material.dart';
import 'dart:io';

import 'package:pretty_json/pretty_json.dart';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var text = '';

  void _incrementCounter() async {
    var env = Platform.environment;
    print(prettyJson(env));

    setState(() {
      text = prettyJson(env);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              SelectableText(text),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2021-02-16 05:44
Hi @LeXuanKhanh 
Thanks for reproducible, I can reproduce the different results.


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 68c96f100e (7 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150
! Doctor found issues in 2 categories.
```
```bash
[✓] Flutter (Channel master, 1.27.0-2.0.pre.102, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-2.0.pre.102 at /Users/tahatesser/Code/flutter_master
    • Framework revision b2e05062b6 (21 hours ago), 2021-02-15 03:56:03 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150
! Doctor found issues in 2 categories.
```

</details>

**Comment by LeXuanKhanh** [comment] 2021-02-16 14:45
@TahaTesser I'm going to report that crash too which involve to `Message from debugger: Terminated due to signal 13` since I'm working with Process on my project on my Github ( https://github.com/LeXuanKhanh/flutter_youtube_downloader ) 

By ignoring the signal using `signal(SIGPIPE, SIG_IGN)` in `applicationDidBecomeActive` and `applicationWillUnhide` in `AppDelegate`, you can temporary fix the crash when the `Process.run` produce the error, by won't fix when building a release app

In your example, I think because the `Process` can't found the `npm` executable, it will produce the error which leading to a crash, can you try to add the `signal(SIGPIPE, SIG_IGN)` ?

```
import Cocoa
import FlutterMacOS

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
    override func applicationDidBecomeActive(_ notification: Notification) {
        signal(SIGPIPE, SIG_IGN);//Ignore signal
    }
    
    override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        return true
    }
    
    override func applicationWillUnhide(_ notification: Notification) {
        signal(SIGPIPE, SIG_IGN);
    }
    
    override func applicationWillBecomeActive(_ notification: Notification) {
        signal(SIGPIPE, SIG_IGN);
    }
}
```

**Comment by TahaTesser** [comment] 2021-02-18 10:39
Hi @LeXuanKhanh 
When making this changes I get 
```bash
[+115717 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: ProcessException: Operation not permitted
[        ]   Command: npm -v
```

**Comment by LeXuanKhanh** [comment] 2021-02-18 15:02
@TahaTesser Can you try `pwd` first to find out which location your process are on when you execute `npm -v` ? , I guess you are on some system directory so you can't run some command. 

The location which create the Process is different too between Android Studio, Xcode and build a release app

Android Studio: `(Project Folder)`
Xcode: `(Xcode DerivedData Folder)/(Project Build Temp Folder)/Build/Product/Debug`
Release: `/` (root directory)

Try to change to some different directory then try again

**Comment by TahaTesser** [comment] 2021-02-19 13:20
@LeXuanKhanh 
True, that makes sense, this could use a new issue tho

**Comment by LeXuanKhanh** [comment] 2021-02-23 02:37
@TahaTesser do i need to create a new issue reference to this crash ?

**Comment by TahaTesser** [comment] 2021-02-23 10:22
@LeXuanKhanh 
Yes

**Comment by stuartmorgan** [comment] 2021-03-01 19:38
This is not a bug; environment is inherited from the parent process, so depending on where you launch from, you will have a different environment. In particular, your "Release app" environment is controlled entirely by macOS itself. You can add things to the environment of normally-launched GUI apps on your own OS using a user-level plist, but that wouldn't apply on anyone else's machine.

In general, unless you control the launch environment for an application (e.g., it will only ever be launched from a script you control), you should not make assumptions about the contents of the environment in a desktop application.

**Comment by stuartmorgan** [comment] 2021-03-03 14:27
> so I didn't think the location is the reason making environment is different

When I said "where you launch from" I don't mean the location of the application, I mean the method you are using. E.g., if you launch an application from Terminal, you'll have a different environment than if you launch from Finder.

> You said the Release environment is controlled entirely by macOS itself. How about the Debug, is it the same ?

What optimization mode the application is compiled with is irrelevant here; what matters is how you launch it. I was assuming that what you labelled "Release app" was launched from Finder.

> How can I control the launch environment for an application ? , for example: modify the PATH or some environment variables

I recommend a general programming resource like StackOverflow if you have questions about how to launch macOS applications with a modified environment (but I would also recommend explaining when you post there what your actual goal is, because changing the inherited environment is a poor solution if what you want to do is affect sub-launched processes as described in the original report).

I meant to close this when I commented before (since this is not a bug and not related to Flutter itself); closing now.

**Closed by stuartmorgan** 2021-03-03 14:27 UTC
Labels: P4, a: desktop, a: release, engine, found in release: 1.27, has reproducible steps, platform-mac, t: xcode
