### ISSUE TITLE
Application not working after adding apptics_flutter package to the project.

### ISSUE THREAD

**Issue by khan-raptee** [flutter/flutter#151525] opened 2024-07-10 07:36 UTC
### Steps to reproduce

1. I am using the zoho apptics sdk for my android app
2. i have configured the plugin and it is working fine.
3. But when add [apptics_package](https://pub.dev/packages/apptics_flutter) i am getting error. 
4. The application is crashing immediately while i run >> flutter run

### Expected results

The package should work according to the instructions provided in documentation of flutter [apptic_flutter](https://pub.dev/packages/apptics_flutter) package

### Actual results

The application is not running after adding the [apptics_flutter](https://pub.dev/packages/apptics_flutter) package to the project.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![apptics 1](https://github.com/flutter/flutter/assets/171899797/74f58715-c6e0-4de5-8034-9f7352684124)

![apptics 2](https://github.com/flutter/flutter/assets/171899797/56c57a1d-51a1-4026-8afe-96a0da8deecd)

</details>

### Logs

<details open><summary>Logs</summary>

```console
C:\Users\Kashaf\Desktop\zoho_apptics_temp>flutter run
Launching lib\main.dart on 22081283G in debug mode...
ERROR:C:\Users\Kashaf\.gradle\caches\transforms-3\dfa7740a2ab2c60abf24b5c077001144\transformed\jetified-apptics-core-0.2.5-runtime.jar: D8: com.android.tools.r8.internal.Hc: Sealed classes are not supported as program classes

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform apptics-core-0.2.5.aar (com.zoho.apptics:apptics-core:0.2.5) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\Kashaf\.gradle\caches\transforms-3\dfa7740a2ab2c60abf24b5c077001144\transformed\jetified-apptics-core-0.2.5-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Running Gradle task 'assembleDebug'...                              9.6s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────┐
│ [!] The shrinker may have failed to optimize the Java bytecode.            │
│ To disable the shrinker, pass the `--no-shrink` flag to this command.      │
│ To learn more, see: https://developer.android.com/studio/build/shrink-code │
└────────────────────────────────────────────────────────────────────────────┘
Error: Gradle task assembleDebug failed with exit code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
C:\Users\Kashaf>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.5)
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.91.0)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-10 09:17
This is a gradle issue, and might be related to something in the plugin you're using. Kindly check  https://stackoverflow.com/questions/73453524/what-is-causing-this-error-com-android-tools-r8-internal-nc-sealed-classes-are to see if it helps. 

If it does not, you will need to reach out to the zoho support team for assistance as there isn't much we can about third-party issues without the source. 

Closing from here as this is caused by a third-party plugin. 

Thank you

**Closed by danagbemava-nc** 2024-07-10 09:17 UTC
Labels: in triage
