### ISSUE TITLE
flutter test keeps running in a loop and sometimes throws Timeout exception

### ISSUE THREAD

**Issue by dna2github** [flutter/flutter#142443] opened 2024-01-29 14:04 UTC
### Steps to reproduce

```
import 'dart:async';
import 'dart:io';
import 'package:crypto/crypto.dart';

  Future<String> calculateHash(String targetFilename) async {
    final f = File(targetFilename);
    if (!f.existsSync()) return "";
    final digest = await sha256.bind(f.openRead()).first;
    return digest.toString();
  }
```

```
void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    final baseDir = path.dirname(Platform.script.toFilePath());
    // create a file at the project root: /path/to/project/root/asset/image/logo.png
    final testfile = path.join(baseDir, 'asset', 'image', 'logo.png');
    final result = await calculateHash(testfile);
    expect(result, "xxxxxxx");
  });
}
```

`flutter test` hangs at ` final digest = await sha256.bind(f.openRead()).first;`; once comment it out and set `final digest = "xxxxxxx"`, got passed.

however, the `calculateHash` function works correctly in the app in runtime; so the library works fine.

### Expected results

`flutter test` should stop whatever the test result.

### Actual results

hang in die loop, timer ticks forever ...

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [version 10.0.22621.3007], locale ...)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.19)
[√] Android Studio (version 2023.1)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by darshankawar** [comment] 2024-01-30 06:20
@dna2github 
In your code, where is `path` coming from ?
Can you also provide the console log that shows the unending loop ?

**Comment by dna2github** [comment] 2024-01-31 04:32
@darshankawar 
```
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as path;
```

```
pubspec.yml
...
  path: ^1.8.3
  crypto: ^3.0.3
...
```

```
PS (path to project folder)> flutter test
08:12 +1: (path to project folder)/test/some_test.dart: Counter increments smoke test

+1 means that the default `widget_test` test case passed ...
```

**Comment by dna2github** [comment] 2024-01-31 04:51
oh, great, after 10min, i got:
```
  TimeoutException after 0:10:00.000000: Test timed out after 10 minutes.
  dart:isolate  _RawReceivePort._handleMessage
```

**Comment by darshankawar** [comment] 2024-01-31 06:23
Thanks for the update. Below is runnable code sample.

<details>
<summary> runnable code </summary>

```

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as path;

Future<String> calculateHash(String targetFilename) async {
  final f = File(targetFilename);
  if (!f.existsSync()) return "";
  final digest = await sha256.bind(f.openRead()).first;
  return digest.toString();
}

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    final baseDir = path.dirname(Platform.script.toFilePath());
    // create a file at the project root: /path/to/project/root/asset/image/logo.png
    final testfile = path.join(baseDir, 'assets','logo.png');
    final result = await calculateHash(testfile);
    expect(result, "xxxxxxx");
  });
}

```

</details>

I observed test not be completed and keeps on running but didn't see timeout exception.
Since `crypto` and `path` both are dart packages, maybe this probably need to be reported in dart-lang repo, but I'll keep the issue here open for team's input.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.16.8, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.16.8 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (2 days ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.19.0-14.0.pre.25, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.19.0-14.0.pre.25 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4af2051f8e (61 minutes ago), 2024-01-30 23:13:30 -0500
    • Engine revision 2d2d88068a
    • Dart version 3.4.0 (build 3.4.0-92.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by mraleph** [comment] 2024-01-31 08:14
This is working as expected, due to `FakeAsync` used by flutter test suite. You need to use [`runAsync`](https://api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html) if you are doing real asynchronous operations.

**Comment by dna2github** [comment] 2024-01-31 09:37
@mraleph i guess `runAsync` is deprecated: `This is no longer supported and has no effect. `

thanks all the same, will keep an eye on this and may report to dart-lang repo.

**Comment by mraleph** [comment] 2024-01-31 09:49
> @mraleph i guess `runAsync` is deprecated

You are misreading the documentation. It is the specific named parameter that is deprecated, `runAsync` is not deprecated (though it is discouraged for obvious reasons). Alternatively, don't use `testWidgets` if you are not testing UI stuff.  

> thanks all the same, will keep an eye on this and may report to dart-lang repo.

There is nothing to report. This is an expected behavior due to how UI testing is implemented in Flutter. It wants to simulate the passing of time so it uses `FakeAsync`. 

There is related issue in `FakeAsync` to make this more user friendly: https://github.com/dart-lang/fake_async/issues/24

**Comment by dna2github** [comment] 2024-01-31 09:50
@mraleph thanks for more info.

however, as mentioned in the description:

> flutter test hangs at `final digest = await sha256.bind(f.openRead()).first;`;
>
>once comment it out and set `final digest = "xxxxxxx"`, test got passed.

**Comment by mraleph** [comment] 2024-01-31 10:02
`FakeAsync` is complicated. `await Future.value("")` will still not stall even in `FakeAsync` zone. But any real asynchronous activity will stall. Compare:

```dart
  testWidgets('Test that passes', (WidgetTester tester) async {
    await Future.value("");
  });
  testWidgets('Test that times out', (WidgetTester tester) async {
    await Future.delayed(const Duration(milliseconds: 100), () => "");
  });
```

When you do `final digest = ""` you effectively make the code produce `Future.value("")`. 

> but yes, i guess your direction is right, maybe it is a bug in FakeAsync

It's not a bug in FakeAsync. It's intended behavior - though arguably rather unfriendly. It's extremely puzzling when you encounter it for the first time because Flutter does not provide any diagnostics to make obvious what is going wrong. 

There is a bunch of bugs in the Flutter repo with developers being confused about it (e.g. https://github.com/flutter/flutter/issues/5728)

**Comment by goderbauer** [comment] 2024-02-06 23:26
Closing this as working as expected.

**Closed by goderbauer** 2024-02-06 23:26 UTC
Labels: a: tests, framework, dependency: dart, has reproducible steps, team-framework, found in release: 3.16, found in release: 3.19
