### ISSUE TITLE
one plus5 image picker from camera is not working 

### ISSUE THREAD

**Issue by vartikaantino** [flutter/flutter#98899] opened 2022-02-22 04:20 UTC
I have made application in that image picker from camera is not working. it is working fine for other devices.

**Comment by darshankawar** [comment] 2022-02-22 07:42
@vartikaantino 
Can you provide `flutter doctor -v`, plugin version you are using, a minimal complete reproducible code sample that shows the behavior you are reporting ?

Also, what do you mean by `camera not working` ? Does it throw any error while doing so ? If yes, can you provide the complete error log ?

Can you also try the image_picker plugin [example](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker/example) on same device and see if you still get the same behavior of `not working` with it too ?

**Comment by vartikaantino** [comment] 2022-02-28 12:13
Hey ,

I am mentioning console log in case we capture image from camera in one plus 5.

Console log:

D/vndksupport(19827): Loading /vendor/lib64/hw/gralloc.msm8996.so from current namespace instead of sphal namespace.
The Flutter DevTools debugger and profiler on ONEPLUS A3003 is available at: [http://127.0.0.1:9101?uri=http://127.0.0.1:57396/LSyOlnS5lnM=/](http://127.0.0.1:9101/?uri=http://127.0.0.1:57396/LSyOlnS5lnM=/)
E/BpSurfaceComposerClient(19827): Failed to transact (-1)
E/BpSurfaceComposerClient(19827): Failed to transact (-1)
W/Binder (19827): Caught a RuntimeException from the binder stub implementation.
W/Binder (19827): java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=19827, uid=10148 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
W/Binder (19827): at android.os.Parcel.createException(Parcel.java:1950)
W/Binder (19827): at android.os.Parcel.readException(Parcel.java:1918)
W/Binder (19827): at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
W/Binder (19827): at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
W/Binder (19827): at android.content.ContentProviderProxy.delete(ContentProviderNative.java:561)
W/Binder (19827): at android.content.ContentResolver.delete(ContentResolver.java:1813)
W/Binder (19827): at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:83)
W/Binder (19827): at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:61)
W/Binder (19827): at android.os.Binder.execTransact(Binder.java:752)

**Comment by vartikaantino** [comment] 2022-02-28 12:14
@darshankawar  please see this. this is error log when we pick image from camera and it will not come when we pick image from gallery

**Comment by darshankawar** [comment] 2022-03-01 05:34
Closing this as duplicate of https://github.com/flutter/flutter/issues/87896

**Closed by darshankawar** 2022-03-01 05:34 UTC
Labels: in triage
