### ISSUE TITLE
[macOS] TextField is not captured in composing range

### ISSUE THREAD

**Issue by YeungKC** [flutter/flutter#73684] opened 2021-01-11 04:08 UTC
mini code: 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

Steps:
1. Switch to the input method that has composing.
2. Click on the TextField and press any letter.

Actual results:

![image](https://user-images.githubusercontent.com/11473691/104146263-15aa8b00-5405-11eb-9ee4-b5ab9f3e688f.png)

Expected results:

![image](https://user-images.githubusercontent.com/11473691/104146434-a84b2a00-5405-11eb-98f5-c899d9392aa1.png)

**Comment by YeungKC** [comment] 2021-01-11 04:09
cc @stuartmorgan @justinmc

**Comment by YeungKC** [comment] 2021-01-11 04:20
I am not sure, but suspect that this behavior can also be reproduced in window or Linux. But I only have macOS.

@TahaTesser

**Comment by stonega** [comment] 2021-01-11 05:37
I tested it on Linux,  can confirm this is not a issue on Linux platform. But another wired issue is the cursor always jump to beginning after typeseveral words.

**Comment by stuartmorgan** [comment] 2021-01-11 12:15
Duplicate of https://github.com/flutter/flutter/issues/30660

**Closed by stuartmorgan** 2021-01-11 12:15 UTC
Labels: a: text input, framework, platform-mac
