### ISSUE TITLE
Material routes have delay on push and pop

### ISSUE THREAD

**Issue by tomgilder** [flutter/flutter#88221] opened 2021-08-14 15:38 UTC
When using `MaterialRoute` or `MaterialPage` on web or desktop, there's a 300ms delay when navigating back from any page. This makes Flutter apps on web and desktop very laggy:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/756862/129447467-7175eab9-a8eb-4fe4-a3d3-8f0589ddeda4.gif)

PR #82596 removed the default animations from web and desktop, but didn't remove the animation transition delay, which is [hard coded in MaterialRouteTransitionMixin](https://github.com/flutter/flutter/blob/1422bfa7237be3efdcde2ba206db4ae962898f4c/packages/flutter/lib/src/material/page.dart#L85). The navigator waits for the 300ms `transitionDuration` before popping the page. This change is in the current beta branch 2.5.0-5.1.pre.

I feel this change should be reverted until there's a solution for the delay: it's better to have an animation rather than a pause that will make developers feel something is broken. It especially feels laggy on web when using the browser's back button.

The hard-coding of the 300ms duration is really problematic; it also means the transition animation is incorrect on iOS (issue #80929). Ideally the transition duration would be provided in the [transition themes](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/page_transitions_theme.dart).

Related issue that users are likely to run into when trying to remove this delay:
* #86604

<details>
  <summary>Example app code</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: PageOne()));
}

class PageOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Page one'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(builder: (_) => PageTwo()),
            );
          },
          child: const Text('Push page two'),
        ),
      ),
    );
  }
}

class PageTwo extends StatefulWidget {
  @override
  _PageTwoState createState() => _PageTwoState();
}

class _PageTwoState extends State<PageTwo> {
  final _timer = NotifyingTimer();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: BackButton(
          onPressed: () {
            _timer.go();
            Navigator.pop(context);
          },
        ),
        title: AnimatedBuilder(
          animation: _timer,
          builder: (_, __) => Text('${_timer.stopwatch.elapsedMilliseconds}ms'),
        ),
      ),
    );
  }
}

class NotifyingTimer extends ChangeNotifier {
  final stopwatch = Stopwatch();

  void go() {
    stopwatch.start();
    Timer.periodic(
      const Duration(milliseconds: 1),
      (_) => notifyListeners(),
    );
  }
}
```
</details>

cc @yjbanov @goderbauer @chunhtai @darrenaustin

**Comment by TahaTesser** [comment] 2021-08-16 14:04
Hi @tomgilder
Thanks for filing the issue, I can confirm it is from beta to master 



|  `stable`  |  `beta`  | `dev` | `master` |
| :---: | :---: | :---: |:---: |
|  ✅  |   ❌  |  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0
    • iPhone 12 (mobile)     • 7CC8A747-CD39-4C42-871C-2D1CCEAE2AE2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel beta, 2.5.0-5.1.pre, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.5.0-5.1.pre at /Users/tahatesser/Code/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 65cf7de5f4 (5 days ago), 2021-08-11 15:48:01 -0700
    • Engine revision fbeb7e22bd
    • Dart version 2.14.0 (build 2.14.0-377.4.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0 19A5318f
    • iPhone 12 (mobile)     • 7CC8A747-CD39-4C42-871C-2D1CCEAE2AE2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel dev, 2.5.0-6.0.pre, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.5.0-6.0.pre at /Users/tahatesser/Code/flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 225a43d941 (11 days ago), 2021-08-05 11:32:48 -0700
    • Engine revision 07ec4b82c7
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0 19A5318f
    • iPhone 12 (mobile)     • 7CC8A747-CD39-4C42-871C-2D1CCEAE2AE2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.83, on macOS 12.0 21A5304g darwin-x64, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.83 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 06be7e5392 (19 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0 19A5318f
    • iPhone 12 (mobile)     • 7CC8A747-CD39-4C42-871C-2D1CCEAE2AE2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5304g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.131

• No issues found!

```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by tomgilder** [comment] 2021-08-16 17:58
I'd say this is pretty clearly a bug - I don't believe keeping the delay was intentional

**Comment by Goncharo** [comment] 2021-09-09 22:13
+1 one for this, however it is worth noting that I'm seeing this on `MaterialPage` pushes as well (using Nav 2.0), and definitely looks like a bug.

Upgraded to 2.5.0 this morning, and spent some time diagnosing why the `MaterialPage` transitions were now seemingly different between mobile and desktop/web. As mentioned above, it seems like PR [#82596](https://github.com/flutter/flutter/pull/82596) removed the default transitions, however the animation delay is still there for both pops and pushes.

Agreed with @tomgilder that this PR should probably be reverted, otherwise need to have a fix in place. As of now, the default `MaterialPage` behavior look fairly broken on web/desktop.

**Comment by rydmike** [comment] 2021-09-10 11:38
Yes indeed @Goncharo the issue has sadly now regressed into release 2.5.0 stable release. since it was never addressed in the 2.5 pre-release versions earlier.

**Comment by rydmike** [comment] 2021-09-10 13:29
@TahaTesser since this issue has now regressed into stable 2.5.0 the affected channels should be updated, and it now needs some attention and high prio too. 

Imo this issue now needs a 2.5.1 hotfix release where it is reverted if the actual fix to implement it correctly takes too long implement and deliver. Better to have an animation that starts at once, than to wait the animation time before anything happens - I'm with @tomgilder on that.

**Comment by csells** [comment] 2021-09-11 22:41
cc @chunhtai

**Comment by darrenaustin** [comment] 2021-09-13 18:33
Apologies for not catching this before it went into stable. I am investigating removing the delay when there is no transition. If I can't do that quickly and safely, I will revert it. 

However, if you need a work around for right now, you can put back the original behaviour by adding the previous default transitions to your app's theme:

```dart
MaterialApp(
  theme: ThemeData(
      pageTransitionsTheme: const PageTransitionsTheme(
        builders: <TargetPlatform, PageTransitionsBuilder>{
          TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
          TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.linux: FadeUpwardsPageTransitionsBuilder(),
          TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.windows: FadeUpwardsPageTransitionsBuilder(),
        },
      )
  )
)
```

**Comment by tomgilder** [comment] 2021-09-13 21:06
@darrenaustin thank you!

If you'd like a suggestion as to how to fix this longer term, I came up with a [TransitionPage](https://github.com/tomgilder/routemaster/blob/main/lib/src/pages/transition_page.dart) for my package that I think works quite well for users.

It defines a `PageTransition` object with `duration` and `transitionsBuilder` properties, I think something similar in Flutter would work well.

**Comment by chunhtai** [comment] 2021-09-13 21:17
One idea is add transition duration to the PageTransitionsTheme, and grab that duration in https://github.com/flutter/flutter/blob/fad5e4cf892bcf65ad3f1cde092cfb9671c3de99/packages/flutter/lib/src/material/page.dart#L85
One problem with the approach is that it doesn't have context at that point, but the Route has access to navigator state, we can probably grab the context from it

**Comment by HansMuller** [comment] 2021-09-13 23:07
Reverting  #82596 until we can resolve this issue to everyone's satisfaction is the right thing to do in the short-term. The "cp: 2.5" label LGTM.

**Comment by maheshmnj** [comment] 2021-09-24 05:21
Adding the Desktop and web labels, since this issue is only on those platforms.

**Comment by darrenaustin** [comment] 2022-02-24 07:11
As the change that caused this delay has been reverted, I am going to close this issue. I will open another one to track changing the default transition for desktop and web to be a zero delay transition.

**Closed by darrenaustin** 2022-02-24 07:11 UTC
Labels: severe: regression, framework, f: material design, f: routes, customer: crowd, platform-web, a: desktop, has reproducible steps, P3, cp: 2.5 completed, cp: 2.5, found in release: 2.5
