### ISSUE TITLE
[webview_flutter ] Running Webview in hybrid composition will not show when in CupertinoTabScaffold

### ISSUE THREAD

**Issue by liqping** [flutter/flutter#74626] opened 2021-01-25 10:41 UTC
## Steps to Reproduce

1.my test code:

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:webview_flutter/webview_flutter.dart';

void main() {
  // runApp(MyApp());
  runApp(
          CupertinoApp(
            title: 'test',
            theme: CupertinoThemeData(
              barBackgroundColor: Colors.red.withAlpha(250),
              brightness: Brightness.light,
              primaryColor: Colors.white,
            ),
            home:  TestWidget(),
            // navigatorObservers: [
            //   routeObserver
            // ],
          )
      );
}

class TestWidget extends StatefulWidget {
  const TestWidget();
  @override
  State createState() => _TestState();
}

class _TestState extends State<TestWidget>{
  int _selectedIndex = 0;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {

    return
      CupertinoTabScaffold(
        tabBar: CupertinoTabBar( // 底部导航
          activeColor: Colors.red,
          backgroundColor: Color(0xD8FFFFFF),
          inactiveColor: Colors.grey,
          border: Border(
            top: BorderSide(
              color: Colors.grey,
              width: 1.0, // One physical pixel.
              style: BorderStyle.solid,
            ),
          ),
          items: <BottomNavigationBarItem>[
            BottomNavigationBarItem(
                icon: Icon(Icons.image),
                activeIcon: Icon(Icons.image,color: Colors.red,),
                title: Text('web1', style: TextStyle(fontSize: 11.5))),
            BottomNavigationBarItem(
                icon: Icon(Icons.margin),
                activeIcon: Icon(Icons.margin,color: Colors.red,),
                title: Text('blank', style: TextStyle(fontSize: 11.5))),
            BottomNavigationBarItem(
                icon: Icon(Icons.gradient),
                activeIcon: Icon(Icons.gradient,color: Colors.red,),
                title: Text('web2', style: TextStyle(fontSize: 11.5))),
          ],
          currentIndex: _selectedIndex,
//        fixedColor: Colors.blue,
          onTap: _onItemTapped,
        ),
        tabBuilder: (BuildContext context, int index) {

          return CupertinoTabView(
            builder: (BuildContext context) {
              Widget scaffold;
              switch (index) {
                case 0:
                  scaffold =
                      CupertinoPageScaffold(
                          navigationBar: CupertinoNavigationBar(
                            middle: Text('web 1'),
                          ),
                          child: WebView(
                            initialUrl: 'https://github.com',
                          )
                      );
                  break;
                case 1:
                  scaffold =
                      CupertinoPageScaffold(child: Center(
                        child: Text('page blank'),
                      ));
                  break;
                case 2:
                  scaffold = CupertinoPageScaffold(
                      navigationBar: CupertinoNavigationBar(
                        middle: Text('web 2'),
                      ),
                      child: WebView(
                        initialUrl: 'https://pub.dev',
                      )
                  );
                  break;
              }
              return scaffold;
            },
          );
        },
//      )
      );
  }
  void _onItemTapped(int index) {
    if(_selectedIndex != index) {
      setState(() {
        _selectedIndex = index;
      });

    }
  }
}
```
</details>

2. description
   1). first page (web 1)  did show, next press third tab, the third page (web 2) will not show, then press first tab(web1 page), web1 page will not show yet.
   2) but if press middle tab(page blank page)  rather than press third tab ,then press third tab, the third page (web 2) and the first page(web 1)  did show.
 
 3) detail see gif

| Preview | Preview |
| --------------- | --------------- |
![db5pz-m7abc](https://user-images.githubusercontent.com/62126718/105695198-c738d880-5f3c-11eb-8aa2-ed7e67a518f3.gif)	| ![mu9mw-lmerh](https://user-images.githubusercontent.com/62126718/105695281-e20b4d00-5f3c-11eb-8f18-ffcc5dc06749.gif)

 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.25.0-8.1.pre at /Users/liping/flutter/flutter
    • Framework revision 8f89f6505b (6 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/liping/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/liping/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • MI 6X (mobile)             • 2b58c837                             • android-arm64  • Android 9 (API
      28)
    • iPhone 11 Pro Max (mobile) • B70D8471-97CF-4EC7-9D79-AE8E5A836B74 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      88.0.4324.96
```
</details>

**Comment by TahaTesser** [comment] 2021-01-25 14:17
Hi @liqping 
Thanks for filing the issue, I can reproduce it in CupertinoTabScaffold but no issues in material TabBar.
It works fine in non-hybrid mode. 

<details> 
<summary>CupertinoTabScaffold code sample</summary> 

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:webview_flutter/webview_flutter.dart';

void main() {
  // runApp(MyApp());
  runApp(CupertinoApp(
    title: 'test',
    theme: CupertinoThemeData(
      barBackgroundColor: Colors.red.withAlpha(250),
      brightness: Brightness.light,
      primaryColor: Colors.white,
    ),
    home: TestWidget(),
    // navigatorObservers: [
    //   routeObserver
    // ],
  ));
}

class TestWidget extends StatefulWidget {
  const TestWidget();
  @override
  State createState() => _TestState();
}

class _TestState extends State<TestWidget> {
  int _selectedIndex = 0;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        // 底部导航
        activeColor: Colors.red,
        backgroundColor: Color(0xD8FFFFFF),
        inactiveColor: Colors.grey,
        border: Border(
          top: BorderSide(
            color: Colors.grey,
            width: 1.0, // One physical pixel.
            style: BorderStyle.solid,
          ),
        ),
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
              icon: Icon(Icons.image),
              activeIcon: Icon(
                Icons.image,
                color: Colors.red,
              ),
              title: Text('web1', style: TextStyle(fontSize: 11.5))),
          BottomNavigationBarItem(
              icon: Icon(Icons.margin),
              activeIcon: Icon(
                Icons.margin,
                color: Colors.red,
              ),
              title: Text('blank', style: TextStyle(fontSize: 11.5))),
          BottomNavigationBarItem(
              icon: Icon(Icons.gradient),
              activeIcon: Icon(
                Icons.gradient,
                color: Colors.red,
              ),
              title: Text('web2', style: TextStyle(fontSize: 11.5))),
        ],
        currentIndex: _selectedIndex,
//        fixedColor: Colors.blue,
        onTap: _onItemTapped,
      ),
      tabBuilder: (BuildContext context, int index) {
        return CupertinoTabView(
          builder: (BuildContext context) {
            Widget scaffold;
            switch (index) {
              case 0:
                scaffold = CupertinoPageScaffold(
                    navigationBar: CupertinoNavigationBar(
                      middle: Text('web 1'),
                    ),
                    child: WebView(
                      initialUrl: 'https://github.com',
                    ));
                break;
              case 1:
                scaffold = CupertinoPageScaffold(
                    child: Center(
                  child: Text('page blank'),
                ));
                break;
              case 2:
                scaffold = CupertinoPageScaffold(
                    navigationBar: CupertinoNavigationBar(
                      middle: Text('web 2'),
                    ),
                    child: WebView(
                      initialUrl: 'https://pub.dev',
                    ));
                break;
            }
            return scaffold;
          },
        );
      },
//      )
    );
  }

  void _onItemTapped(int index) {
    if (_selectedIndex != index) {
      setState(() {
        _selectedIndex = index;
      });
    }
  }
}

``` 

</details>

<details> 
<summary>TabBarcode sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              WebView(
                initialUrl: 'https://github.com',
              ),
              Center(child: Text('page blank')),
              WebView(
                initialUrl: 'https://pub.dev',
              )
            ],
          ),
        ),
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.22.5 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.25.0-8.3.pre at C:\Users\Taha\Code\flutter_beta
    • Framework revision 5d36f2e7f5 (11 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!
```

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.144, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-13.0.pre.144 at C:\Users\Taha\Code\flutter_master
    • Framework revision 2007186d2e (17 hours ago), 2021-01-24 12:54:00 -0800
    • Engine revision fdddf87080
    • Dart version 2.12.0 (build 2.12.0-253.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!
```

</details>

Thank you

**Comment by liqping** [comment] 2021-01-26 10:05
@TahaTesser 
It works fine to delay load webview by  add "WidgetsBinding.instance.addPostFrameCallback". 
```
int isLoaded = fasle;
initState() {
WidgetsBinding.instance.addPostFrameCallback((callback) {
        setState(() {
          isLoaded = true;
        });
      }
);
...
}

Widget build(BuildContext context) {
 return isLoaded ? WebView():Container();
}

```

**Comment by haohongwei** [comment] 2021-02-20 11:10
I have the same problem. And I change the code as what  @liqping  said, the problem solved.

**Comment by danagbemava-nc** [comment] 2021-08-16 07:21
I cannot reproduce the issue on `stable 2.2.3` or `master 2.5.0-7.0.pre.83` with `webview_flutter: ^2.0.12`. 

Labelling as fixed and closing the issue. See attached video.

If anyone disagrees or still experiences this issue, kindly provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

[hybrid composition cupertino tab.mp4.zip](https://github.com/flutter/flutter/files/6990422/hybrid.composition.cupertino.tab.mp4.zip)

<details>
<summary> code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(
    CupertinoApp(
      title: 'test',
      theme: CupertinoThemeData(
        barBackgroundColor: Colors.red.withAlpha(250),
        brightness: Brightness.light,
        primaryColor: Colors.white,
      ),
      home: TestWidget(),
    ),
  );
}

class TestWidget extends StatefulWidget {
  const TestWidget();
  @override
  State createState() => _TestState();
}

class _TestState extends State<TestWidget> {
  int _selectedIndex = 0;

  @override
  void initState() {
    super.initState();
    WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        // 底部导航
        activeColor: Colors.red,
        backgroundColor: Color(0xD8FFFFFF),
        inactiveColor: Colors.grey,
        border: Border(
          top: BorderSide(
            color: Colors.grey,
            width: 1.0, // One physical pixel.
            style: BorderStyle.solid,
          ),
        ),
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
              icon: Icon(Icons.image),
              activeIcon: Icon(
                Icons.image,
                color: Colors.red,
              ),
              title: Text('web1', style: TextStyle(fontSize: 11.5))),
          BottomNavigationBarItem(
              icon: Icon(Icons.margin),
              activeIcon: Icon(
                Icons.margin,
                color: Colors.red,
              ),
              title: Text('blank', style: TextStyle(fontSize: 11.5))),
          BottomNavigationBarItem(
              icon: Icon(Icons.gradient),
              activeIcon: Icon(
                Icons.gradient,
                color: Colors.red,
              ),
              title: Text('web2', style: TextStyle(fontSize: 11.5))),
        ],
        currentIndex: _selectedIndex,
        onTap: _onItemTapped,
      ),
      tabBuilder: (BuildContext context, int index) {
        return CupertinoTabView(
          builder: (BuildContext context) {
            late Widget scaffold;
            switch (index) {
              case 0:
                scaffold = CupertinoPageScaffold(
                  navigationBar: CupertinoNavigationBar(
                    middle: Text('web 1'),
                  ),
                  child: WebView(initialUrl: 'https://github.com'),
                );
                break;
              case 1:
                scaffold = CupertinoPageScaffold(
                    child: Center(
                  child: Text('page blank'),
                ));
                break;
              case 2:
                scaffold = CupertinoPageScaffold(
                  navigationBar: CupertinoNavigationBar(
                    middle: Text('web 2'),
                  ),
                  child: WebView(initialUrl: 'https://pub.dev'),
                );
                break;
            }
            return scaffold;
          },
        );
      },
    );
  }

  void _onItemTapped(int index) {
    if (_selectedIndex != index) {
      setState(() {
        _selectedIndex = index;
      });
    }
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.83, on macOS 11.5.1 20G80 darwin-arm,
    locale en-GH)
    • Flutter version 2.5.0-7.0.pre.83 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 06be7e5392 (11 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
</details>

**Closed by danagbemava-nc** 2021-08-16 07:21 UTC
Labels: platform-android, plugin, p: first party, a: platform-views, p: webview, has reproducible steps, P4, found in release: 1.22, found in release: 1.25, found in release: 1.26
