### ISSUE TITLE
RuntimeError: /usr/local/opt/autoconf not present or broken

### ISSUE THREAD

**Issue by XXonline** [flutter/flutter#22728] opened 2018-10-05 12:22 UTC
Error: An exception occured within a child process:
  RuntimeError: /usr/local/opt/autoconf not present or broken
Please reinstall autoconf. Sorry :(

**Comment by zoechi** [comment] 2018-10-05 16:03
How is this related to Flutter?
Can you please provide more information how to reproduce?

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2018-11-30 14:23
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-11-30 14:23 UTC
Labels: waiting for customer response

**Comment by Alan201601** [comment] 2019-01-05 06:35
i have same question,some one can help me?

Error: An exception occurred within a child process:
  RuntimeError: /usr/local/opt/libtool not present or broken
Please reinstall libtool. Sorry :(

**Comment by amirzucker** [comment] 2019-01-06 08:20
@Alan201601 Have you tried `brew install libtool` and `brew link libtool`?

**Comment by craigomac** [comment] 2019-04-18 09:25
I fixed this by `brew reinstall autoconf`, then a couple of other `brew reinstall` commands for subsequent error messages of the same nature.

**Comment by gerritjvv** [comment] 2019-06-21 10:03
I needed to run:

brew reinstall autoconf \
&& brew reinstall libtool \
&& brew reinstall libusb

**Comment by lucifer717** [comment] 2019-08-13 08:20
> I needed to run:
> 
> brew reinstall autoconf 
> && brew reinstall libtool 
> && brew reinstall libusb 
> && brew unlink xz && brew reinstall xz

it works for me, thx
