### ISSUE TITLE
Dynamic magnifier border in CupertinoPicker

### ISSUE THREAD

**Issue by JSBmanD** [flutter/flutter#57737] opened 2020-05-21 14:13 UTC
## Use case
I put custom background for picker and now default colors on borders of magnifier look like they are not from the whole design. I needed to put less transparent color to borders but it's hardcoded and private now and it will be great to make them overridable.
https://github.com/flutter/flutter/blob/1ba4f1f509202f3d2ec16f053edcbe2df6b7107e/packages/flutter/lib/src/cupertino/picker.dart#L14

## Proposal

I want custom border color parameter in the constructor of CupertinoPicker for flexibility so I could make dark and light design for picker (as it now not showing correctly on my gradient).

**Comment by iapicca** [comment] 2020-05-22 07:54
Hi @JSBmanD 
given this [answer](https://github.com/flutter/flutter/issues/21049#issuecomment-431155645)
since this cupertino is meant to reproduce the original ios experience;
the feature you are describing is obtainable creating a custom widget.

I'm closing this issue 
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2020-05-22 07:54 UTC
