### ISSUE TITLE
[google_maps_flutter] Application crashes after move from screen with map on earlier versions of IOS

### ISSUE THREAD

**Issue by varpa89** [flutter/flutter#58409] opened 2020-06-01 12:51 UTC
- IOS 9.3.5
- Flutter Channel stable, v1.17.1
After this commit https://github.com/flutter/plugins/commit/531ff2bc80afb3181218a1ff46e195303348ae0c
my application started crashes after moving from screen with google maps on devices with IOS 9

google_maps_flutter: 0.5.26+3

> 2020-06-01 15:47:35.358 Runner[495:131068] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x16d17150 of class GMSMapView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x16decf20> (
<NSKeyValueObservance 0x1a13f430: Observer: 0x16d19190, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dc0bf0>
<NSKeyValueObservance 0x1a13f430: Observer: 0x16d19190, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dc0bf0>
<NSKeyValueObservance 0x1a13f430: Observer: 0x16d19190, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dc0bf0>
<NSKeyValueObservance 0x1a13f430: Observer: 0x16d19190, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dc0bf0>
<NSKeyValueObservance 0x1a13f430: Observer: 0x16d19190, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dc0bf0>
<NSKeyValueObservance 0x1a13f430: Observer: 0x16d19190, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dc0bf0>
<NSKeyValueObservance 0x1a13f430: Observer: 0x16d19190, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dc0bf0>
<NSKeyValueObservance 0x1a13f430: Observer: 0x16d19190, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dc0bf0>
<NSKeyValueObservance 0x1a13f430: Observer: 0x16d19190, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x16dc0bf0>
)'
*** First throw call stack:
(0x2245f91b 0x21bfae17 0x2245f861 0x22c167a9 0x21c153a9 0x2242258f 0x224221c1 0x2242000d 0x2236f229 0x2236f015 0x2395fac9 0x26a43189 0x73401 0x22017873)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by TahaTesser** [comment] 2020-06-01 14:41
Hi @varpa89 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by varpa89** [comment] 2020-06-01 18:52
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F96, locale en-RU)
    • Flutter version 1.17.1 at /Users/pavel.varchenko/Work/Dev/env/flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

> flutter run --verbose

The output is too long. Do we really need it?

App sample (please use your maps token)
Go to Maps Screen and then push back. On IOS 9 crash will appear

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GitHub Issue 58409 Sample',
      home: _MainScreen(),
    );
  }
}

class _MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: RaisedButton(
        onPressed: () {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => _MapScreen()),
          );
        },
        child: Text(
          "Go To Map Screen",
        ),
      )),
    );
  }
}

class _MapScreen extends StatelessWidget {
  Completer<GoogleMapController> _controller = Completer();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Map'),
      ),
      body: GoogleMap(
          mapType: MapType.normal,
          onMapCreated: (GoogleMapController controller) {
            _controller.complete(controller);
          },
          initialCameraPosition: CameraPosition(
            target: LatLng(61.52401, 105.31875600000001),
            zoom: 1,
          )),
    );
  }
}

```

**Comment by ryanhoo95** [comment] 2020-07-06 07:47
I have encountered this issue as well on iPad (4th Gen, iOS 10.3.3)

**Comment by jaetmar** [comment] 2020-07-15 00:01
Any updates on this? I'm facing the same issue

**Comment by sdemisse** [comment] 2020-09-03 00:59
I have the same issue with iPhone 7 simulator.

**Comment by ozz-rjq** [comment] 2020-09-16 14:50
Having the same issue with flutter v1.20.3 and ios 10.3 simulator

**Comment by ziasultan2** [comment] 2020-09-30 04:27
app killed same error on flutter v1.20.2

it's occuring in real devices but working on simulator

**Comment by TahaTesser** [comment] 2020-10-01 11:08
Hi @varpa89  @ziasultan2  @ozz-rjq
I cannot reproduce any crash running `google_maps_flutter` on iOS 14 on the latest staable
<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GitHub Issue 58409 Sample',
      home: _MainScreen(),
    );
  }
}

class _MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: RaisedButton(
        onPressed: () {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => _MapScreen()),
          );
        },
        child: Text(
          "Go To Map Screen",
        ),
      )),
    );
  }
}

class _MapScreen extends StatelessWidget {
  Completer<GoogleMapController> _controller = Completer();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Map'),
      ),
      body: GoogleMap(
          mapType: MapType.normal,
          onMapCreated: (GoogleMapController controller) {
            _controller.complete(controller);
          },
          initialCameraPosition: CameraPosition(
            target: LatLng(61.52401, 105.31875600000001),
            zoom: 1,
          )),
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.20.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.0.1

• No issues found!

```

</details> 


Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by varpa89** [comment] 2020-10-01 11:32
@TahaTesser I provided it before. As you can see, the issue reproduces on earlier versions of iOS (9,10).

**Comment by halloga** [comment] 2020-10-02 07:09
Same issue on iOS 10 using _google_maps_flutter: 0.5.29+1_. Here's my Crashlytics log:

> Crashed: com.google.firebase.crashlytics.ios.exception
> 0  Runner                         0x100056a00 FIRCLSProcessRecordAllThreads + 392 (FIRCLSProcess.c:392)
> 1  Runner                         0x100056de4 FIRCLSProcessRecordAllThreads + 423 (FIRCLSProcess.c:423)
> 2  Runner                         0x10004d50c FIRCLSHandler + 34 (FIRCLSHandler.m:34)
> 3  Runner                         0x100049168 __FIRCLSExceptionRecord_block_invoke + 218 (FIRCLSException.mm:218)
> 4  libdispatch.dylib              0x18976a9a0 _dispatch_client_callout + 16
> 5  libdispatch.dylib              0x189777ee0 _dispatch_barrier_sync_f_invoke + 84
> 6  Runner                         0x100048900 FIRCLSExceptionRecord + 225 (FIRCLSException.mm:225)
> 7  Runner                         0x100048bf8 FIRCLSExceptionRecordNSException + 111 (FIRCLSException.mm:111)
> 8  Runner                         0x1000484e0 FIRCLSTerminateHandler() + 279 (FIRCLSException.mm:279)
> 9  libc++abi.dylib                0x1893035d4 std::__terminate(void (*)()) + 16
> 10 libc++abi.dylib                0x1893031a8 __cxa_rethrow + 144
> 11 libobjc.A.dylib                0x1893146f8 objc_exception_rethrow + 44
> 12 CoreFoundation                 0x18a78ee10 CFRunLoopRunSpecific + 532
> 13 GraphicsServices               0x18c1f9074 GSEventRunModal + 100
> 14 UIKit                          0x190a49c9c UIApplicationMain + 208
> 15 Runner                         0x10002a2e8 main + 7 (main.m:7)
> 16 libdyld.dylib                  0x18979d59c start + 4

**Flutter Doctor:**
>  Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale en-TR)
>     • Flutter version 1.20.4 at /Users/halloga/dev/flutter
>     • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
>     • Engine revision d1bc06f032
>     • Dart version 2.9.2
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
>     • Android SDK at /Users/halloga/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.0-rc1
>     • ANDROID_HOME = /Users/halloga/Library/Android/sdk
>     • ANDROID_SDK_ROOT = /Users/halloga/Library/Android/sdk
>     • Java binary at: /Users/halloga/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.3.1, Build version 11C505
>     • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Users/halloga/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
>     • Flutter plugin version 49.0.2
>     • Dart plugin version 193.7547
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by EffyCoder** [comment] 2020-10-12 17:11
I am facing same issue. App crashes when with uncaught NSException.
Following is my crash log:
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fcf0c2f2200 of class GMSMapView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x61800023ed60> (
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	<NSKeyValueObservance 0x610000441aa0: Observer: 0x6180000bdbe0, Key path: frame, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000258d20>
	)'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x000000010f440b0b __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x000000010eea5141 objc_exception_throw + 48
		2   CoreFoundation                      0x000000010f4a9625 +[NSException raise:format:] + 197
		3   Foundation                          0x000000010bbb2b53 NSKVODeallocate + 294
		4   libobjc.A.dylib                     0x000000010eeba2fa _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 866
		5   UIKit                               0x000000010cdea2f7 -[UIView dealloc] + 1841
		6   libobjc.A.dylib                     0x000000010eeba2fa _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 866
		7   UIKit                               0x000000010cdea2f7 -[UIView dealloc] + 1841
		8   libobjc.A.dylib                     0x000000010eeba2fa _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 866
		9   CoreFoundation                      0x000000010f3d4454 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
		10  CoreFoundation                      0x000000010f3d40e3 __CFRunLoopDoTimer + 1011
		11  CoreFoundation                      0x000000010f3d3caa __CFRunLoopDoTimers + 266
		12  CoreFoundation                      0x000000010f3cb9ec __CFRunLoopRun + 1916
		13  CoreFoundation                      0x000000010f3cb016 CFRunLoopRunSpecific + 406
		14  GraphicsServices                    0x00000001145a0a24 GSEventRunModal + 62
		15  UIKit                               0x000000010cd55134 UIApplicationMain + 159
		16  Runner                              0x000000010755fbeb main + 75
		17  libdyld.dylib                       0x000000011046b65d start + 1
		18  ???                                 0x0000000000000005 0x0 + 5
	)`


Flutter doctor output:
`[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E266, locale en-CA)
    • Flutter version 1.22.1 at /Users/xcodeclub/Desktop/shantanoo/flutter
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xcodeclub/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone 6s (mobile) • A1051007-9557-48C5-BB2F-22ACD26D91E5 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)

• No issues found!`

**Comment by amorenew** [comment] 2020-10-15 04:12
Same Flutter 1.22, google map 1.0.2, iOS 10 Ipad 4

**Comment by EffyCoder** [comment] 2020-10-23 13:26
@TahaTesser any update on this issue? We are not able to deliver our application to large chunk of user group. and it

**Comment by ziasultan2** [comment] 2020-10-23 16:54
> @TahaTesser any update on this issue? We are not able to deliver our application to large chunk of user group. and it is inhibiting them to use our app.

it's a bug. It'll not fix in shortly. so I suggest you to relase your app with minimum ios version 11

**Comment by Omrankabalan** [comment] 2020-11-11 13:01
Any updates on this issue ?

**Comment by jraulc** [comment] 2020-11-26 02:39
> Any updates on this issue ?

The same exception with iOS 10.3 then I tried with iOS 11.3 and working like a charm, thank you all...

**Comment by singun-lxd** [comment] 2020-12-02 10:22
same problem

**Comment by haonv206** [comment] 2021-02-24 08:22
Reading this article: 
https://medium.com/@johnjwchen/fix-the-an-instance-0xxxx-of-class-xxx-was-deallocated-while-key-value-observers-were-still-707dc13e2004
It is a bug on iOS prio to 11.

I swizzled the GMSMapView class, and problem gone away.
Thanks John Chen (https://medium.com/@johnjwchen)

**Comment by stuartmorgan** [comment] 2023-08-15 02:32
Closing as obsolete; iOS 9 and 10 are no longer supported by the plugin.

**Closed by stuartmorgan** 2023-08-15 02:32 UTC
Labels: platform-ios, p: maps, package, e: OS-version specific, P2, team-ios, triaged-ios, multiteam-retriage-candidate
