### ISSUE TITLE
Build Failure: AndroidX issue

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#28294] opened 2019-02-22 00:42 UTC
I went through all of [this](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility), [this](https://github.com/flutter/flutter/issues/27747) and a few other options, e.g. creating a new Flutter project, but I am still encountering the following issue:

```
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
```

I am using exactly three plugins and the `cupertino_icons` *package*:

```
shared_preferences: 0.5.1+1
firebase_remote_config: 0.1.0+2
cloud_firestore: 0.9.5+1
```

According to [this table](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx), all those plugins should have long been updated to use AndroidX, however, `flutter build apk` etc. still fails with that message.

```
[√] Flutter (Channel master, v1.2.2-pre.46, locale en-US)
    • Flutter version 1.2.2-pre.46 at flutterRoot
    • Framework revision 04b7a5b366 (2 hours ago), 2019-02-21 14:46:24 -0800
    • Engine revision 6d7eb52185
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)
```

Going back to the versions listed in that table really is no option since they are vastly outdated by now.

**Comment by mklim** [comment] 2019-02-22 01:04
Could you upload the full error output that you're seeing from `flutter build apk`? You're right, those 3 dependencies should all be updated. I just tried reproducing the problem on my end but wasn't able to.

**Comment by EliasDeuss** [comment] 2019-02-22 05:29
I am getting the same error I was just about to create an issue!

**Comment by EliasDeuss** [comment] 2019-02-22 05:31
This is what is happening to me.

`Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:10: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:645: error: cannot find symbol
  private void reportException(Result result, @Nullable Exception exception) {
                                               ^
  symbol:   class Nullable
  location: class FirebaseAuthPlugin
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:557: error: cannot find symbol
    public void onComplete(@NonNull Task<AuthResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.SignInCompleteListener
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:576: error: cannot find symbol
    public void onComplete(@NonNull Task<Void> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.TaskVoidCompleteListener
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:594: error: cannot find symbol
    public void onComplete(@NonNull Task<SignInMethodQueryResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.GetSignInMethodsCompleteListener
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:186: error: cannot find symbol
                      public void onComplete(@NonNull Task<AuthResult> task) {
                                              ^
  symbol: class NonNull
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:452: error: cannot find symbol
              public void onComplete(@NonNull Task<GetTokenResult> task) {
                                      ^
  symbol: class NonNull
/Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:506: error: cannot find symbol
          public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                          ^
  symbol: class NonNull
Note: /Users/elias/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_auth:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
         *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1
`

**Comment by zoechi** [comment] 2019-02-22 06:48
@EliasDeuss probably better to ask on StackOverflow.

**Comment by EliasDeuss** [comment] 2019-02-22 06:56
@zoechi I know but i'm talking about the cloud firestore warning

**Comment by zoechi** [comment] 2019-02-22 07:02
@EliasDeuss sorry, but still the same advice. This is a support request and we don't have the resources to support everyone individually.

**Comment by creativecreatorormaybenot** [comment] 2019-02-22 20:28
@mklim Using `flutter build apk -v`, I only get the following error message:

```
[        ] > Task :app:validateSigningRelease FAILED
[  +83 ms]          *********************************************************
[        ] WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't
compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be
unrelated.
[        ]          *********************************************************
[        ] 79 actionable tasks: 11 executed, 68 up-to-date
[ +495 ms] Running Gradle task 'assembleRelease'... (completed in 28.4s)
[   +2 ms] "flutter apk" took 44,356ms.
[        ] "flutter apk" took 44,356ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:462:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:330:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:45:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

That is it. Everything else lgtm.

After `flutter clean`:

```
[   +2 ms] > Task :app:validateSigningRelease FAILED
[  +59 ms]          *********************************************************
[   +1 ms] WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] 79 actionable tasks: 69 executed, 10 up-to-date
[ +500 ms] Running Gradle task 'assembleRelease'... (completed in 23.9s)
[   +3 ms] "flutter apk" took 26,756ms.
[        ] "flutter apk" took 26,756ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:462:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:330:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:45:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

Same exception after removing `Pub/Cache` and running `packages get` again.

**Comment by creativecreatorormaybenot** [comment] 2019-02-22 20:58
@mklim The only additional relevant line was the following:

```
[        ] > Task :app:validateSigningRelease FAILED
```

Because of this, I ran `gradle validateSigningRelease --debug` in the `android` module and got the following error:

```
* What went wrong:
20:54:21.764 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred evaluating project ':app'.
20:54:21.764 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to apply plugin [id 'com.android.application']
20:54:21.764 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Minimum supported Gradle version is 5.1.1. Current version is 4.10.3. If using the gradle wrapper, try editing the distributionUrl in android\gradle\wrapper\gradle-wrapper.properties to gradle-5.1.1-all.zip
```

The `distributionUrl` in my project is already set to `gradle-5.1.1-all.zip`. I also tried deleting Pub and Gradle caches, but that did not resolve anything.

**Closed** 2019-02-23 04:51 UTC
Labels: p: first party, plugin, t: gradle, ▣ platform-android

**Comment by just-peteking** [comment] 2019-02-25 16:37
I get this error also, I created a brand new project, ensured it worked, migrated to AndroidX via Android Studio, ensured it worked again, added firebase_core: ^0.3.1+1, again ensured it work; it all did to this point.

I then added the latest firebase auth package: firebase_auth: ^0.8.1+3, run again -> compile issues.

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
C:\flutter\flutter_windows_v0.3.2-beta\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+3\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\flutter\flutter_windows_v0.3.2-beta\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+3\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:10: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
C:\flutter\flutter_windows_v0.3.2-beta\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+3\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:706: error: cannot find symbol
  private void reportException(Result result, @Nullable Exception exception) {
                                               ^
  symbol:   class Nullable
  location: class FirebaseAuthPlugin
C:\flutter\flutter_windows_v0.3.2-beta\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+3\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:610: error: cannot find symbol
    public void onComplete(@NonNull Task<AuthResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.SignInCompleteListener
C:\flutter\flutter_windows_v0.3.2-beta\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+3\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:629: error: cannot find symbol
    public void onComplete(@NonNull Task<Void> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.TaskVoidCompleteListener
C:\flutter\flutter_windows_v0.3.2-beta\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+3\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:647: error: cannot find symbol
    public void onComplete(@NonNull Task<SignInMethodQueryResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.GetSignInMethodsCompleteListener
C:\flutter\flutter_windows_v0.3.2-beta\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+3\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:187: error: cannot find symbol
                      public void onComplete(@NonNull Task<AuthResult> task) {
                                              ^
  symbol: class NonNull
C:\flutter\flutter_windows_v0.3.2-beta\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+3\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:492: error: cannot find symbol
              public void onComplete(@NonNull Task<GetTokenResult> task) {
                                      ^
  symbol: class NonNull
C:\flutter\flutter_windows_v0.3.2-beta\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+3\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:559: error: cannot find symbol
          public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                          ^
  symbol: class NonNull
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_auth:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
         *********************************************************
WARNING: This version of firebase_auth will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1`

**Comment by zoechi** [comment] 2019-02-25 17:00
Looks like the migration did not work.

Did you add
```
android.useAndroidX=true
android.enableJetifier=true
``` 
to `gradle.properties`?

**Comment by just-peteking** [comment] 2019-02-25 17:04
Yep, just added they, right before you mentioned it, this does indeed make it work.

However, there aren’t many plugins around for anything really that support AndroidX; very little amount out there.

So I may have to go backwards until basic plugins like GPS and Permissions are supported ☹

Thank you! 😊

**Comment by zoechi** [comment] 2019-02-25 18:10
@just-peteking https://github.com/flutter/flutter/issues/28207#issuecomment-465600796 might help

**Comment by just-peteking** [comment] 2019-02-26 08:57
> @just-peteking [#28207 (comment)](https://github.com/flutter/flutter/issues/28207#issuecomment-465600796) might help

Thanks mate, I kind of agree with the last comment in that thread; I would add that until the most popular/most used plugins are upgraded and verified to actually work (as some have been upgraded, but don't work), it isn't worth upgrading yet.

**Comment by zoechi** [comment] 2019-02-26 09:03
Ensure the issue is reported for each affected plugin in their plugin repo
