### ISSUE TITLE
[GUL_AppDelegate onCancelWithArguments:] unrecognized selector on app hot restart

### ISSUE THREAD

**Issue by emostar** [flutter/flutter#66190] opened 2020-09-19 18:35 UTC
## Steps to Reproduce

0. Using our codebase that is not open sourced, iOS version with physical device
1. Run `flutter run -t lib/main_prod.dart` in a terminal window
2. Press 'R' to hot restart it

**Expected results:** The app should hot restart and run without crashing

**Actual results:** The app hot restarts, loads the UI, and then crashes with this in the Console:

```-[GUL_AppDelegate-0C560823-DA58-418C-B58D-2D4FC7E2B6F7 onCancelWithArguments:]: unrecognized selector sent to instance 0x2803cda00```

I'm unable to determine what is causing this crash and have no idea on where to look.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.4 at /Users/emostar/dev/flutter
    • Framework revision fba99f6cf9 (5 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/emostar/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/emostar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • emostar’s iPhone (mobile) • XXXXXXXXXXXXXX • ios • iOS 13.6.1

• No issues found!
```

</details>

**Comment by iapicca** [comment] 2020-09-20 12:51
> 1. Using our codebase that is not open sourced, iOS version with physical device

@emostar  There's no need to share you production code, 
but without a **minimal reproducible code sample** the issue will be hardly workable

Also it would be useful to have the full `flutter run --release -v` that includes the crash

**Comment by emostar** [comment] 2020-09-20 18:33
@iapicca Thanks for the response. I have no problem creating a minimal reproducible case, but part of the issue is that I have no indication of what is causing the crash. I ran `flutter run --release -v -t lib/main_prod.dart`, but there is no output for the crash.

Below is a snippet of the output of `flutter run -v -t lib/main_prod.dart`. I opted to not include `--release`, as doing a hot restart causes the crash, and release mode does not support support hot restarts.

<details>
<summary>flutter run -v output</summary>
[   +2 ms] Connected to _flutterView/0x14804a020.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Dev iPhone’s iPhone is available at: http://localhost:50346
[+11267 ms] Starting incremental build...
[   +2 ms] Skipping target: gen_localizations
[        ] complete
[   +1 ms] Performing hot restart...
[   +9 ms] Scanned through 588 files in 7ms
[        ] Syncing files to device Dev’s iPhone...
[        ] Scanning asset files
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:rs/main_prod.dart 67cca47a-90bf-4c89-b890-a062ee3cf21d
[        ] <- 67cca47a-90bf-4c89-b890-a062ee3cf21d
[  +62 ms] Updating files
[ +760 ms] DevFS: Sync finished
[        ] Syncing files to device Dev iPhone’s iPhone... (completed in 824ms)
[        ] Synced 30.6MB.
[        ] <- accept
[ +282 ms] Hot restart performed in 1,116ms.
[   +3 ms] Performing hot restart... (completed in 1,121ms)
[        ] Restarted application in 1,126ms.
[+2126 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/0ECF48B6-8799-4C13-A993-8C93B6B338E0/tmp/rs-flutterkO93Jy/rs-flutter/)
[ +254 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] "flutter run" took 109,398ms.
[  +85 ms] ensureAnalyticsSent: 80ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 0
</summary>

I only see this crash on iOS, and the only way I got the unrecognized selector error was looking in the Console program to pull it out. There is no log or output anywhere with a stack trace.

**Comment by pedromassangocode** [comment] 2020-09-21 08:09
Hi @emostar 
Please provide your `flutter run --verbose` and a minimal complete reproducible code sample if possible?

I did a quick search and this may be related to iOS code, you can try this solution if it is related to your code: https://stackoverflow.com/a/23375270.

Thank you

**Comment by emostar** [comment] 2020-10-01 20:56
@pedromassango My application is quite large, and I do not know what is triggering this. How can I debug this, to find the trigger, so I can make a reproducible code sample?

**Comment by pedromassangocode** [comment] 2020-10-02 06:32
Hi @emostar 
You may want to start by creating a sample project and try to replicate the content of your original application that you suspect is the cause of the problem.

You can also try hot-restart the sample project without modifications first.

**Comment by pedromassangocode** [comment] 2020-10-23 11:02
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-23 11:02 UTC
Labels: in triage
