### ISSUE TITLE
webview_flutter doesn't open storage/gallery while pressing on "choose file" input tags

### ISSUE THREAD

**Issue by Sarthaktydy** [flutter/flutter#33961] opened 2019-06-06 06:43 UTC

**Comment by SupaFan** [comment] 2019-08-27 02:27
I have the same problem~~

**Comment by Sarthaktydy** [comment] 2019-09-23 05:27
> I have the same problem~~

found any solution

**Comment by BondarenkoStas** [comment] 2019-10-08 11:53
Duplicate of #27924

**Closed by BondarenkoStas** 2019-10-08 11:53 UTC
