### ISSUE TITLE
Unhandled Exception: TimeoutException after 0:00:03.000000: Future not completed

### ISSUE THREAD

**Issue by Virakyuth-PK** [flutter/flutter#61438] opened 2020-07-14 10:15 UTC
This is the code I wanted to run.

Position position =
        await Geolocator().getCurrentPosition().timeout(Duration(seconds: 3));

**Comment by TahaTesser** [comment] 2020-07-14 11:26
Hi @Virakyuth-PK 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Baseflow/flutter-geolocator/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-14 11:26 UTC
