### ISSUE TITLE
Implement Cupertino large title refresh control 

### ISSUE THREAD

**Issue by KagurazakaHanabi** [flutter/flutter#44238] opened 2019-11-06 03:32 UTC
## Use case

![2466F8F0-A772-4463-A676-B1A2CE33DCDF](https://user-images.githubusercontent.com/23377765/68266088-f38edd80-0088-11ea-9044-a07f3bfe33e0.jpeg)

**Comment by iapicca** [comment] 2019-11-06 10:10
Hi @KagurazakaHanabi 
can you please describe the issue in detail
and provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by KagurazakaHanabi** [comment] 2019-11-06 10:24
This is iOS 13.2 Email app

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.15-pre.405, on Microsoft Windows [Version 10.0.19013.1000], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.39.2)
[√] Connected device (3 available)
```

**Comment by iapicca** [comment] 2019-11-06 11:22
Hi again @KagurazakaHanabi
can you please describe the issue in detail,
also would be useful if you could explain 
how to reproduce the issue
Thank you

**Comment by KagurazakaHanabi** [comment] 2019-11-06 11:37
It's a feature request not a issue. The picture is screenshot of iOS 13 Email app
We can't place `CupertinoSliverRefreshControl` in `CupertinoSliverNavigationBar`

**Comment by iapicca** [comment] 2019-11-06 13:38
https://github.com/flutter/flutter/issues/44078

**Comment by LongCatIsLooong** [comment] 2019-11-07 03:21
FYI making a `CupertinoSearchBar` is being tracked here: https://github.com/flutter/flutter/issues/9784. It's also listed in https://github.com/flutter/flutter/issues/43041. I remember the large title refresh control being brought up but couldn't find an issue for it. Do you mind if we re-purpose this issue to "create a Cupertino large title refresh control"?

**Comment by KagurazakaHanabi** [comment] 2019-11-07 04:49
No, do as you please
BTW, I can’t find a issue for [this](https://github.com/flutter/flutter/blob/e3742b6e410aa5e9ea34b60dfbdd9a923c5a1fe8/packages/flutter/lib/src/cupertino/nav_bar.dart#L292)

**Comment by LongCatIsLooong** [comment] 2019-11-07 21:57
@KagurazakaHanabi that comment is referring to https://github.com/flutter/flutter/issues/10469. Also it turns out the large title refresh control issue exists: https://github.com/flutter/flutter/issues/16069, so I'm going to close this issue as a duplicate.

**Closed by LongCatIsLooong** 2019-11-07 21:57 UTC
Labels: a: fidelity, a: quality, f: cupertino, proposal, severe: new feature
