### ISSUE TITLE
url_launcher: WebViewActivity.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by Mister-Hope** [flutter/flutter#61819] opened 2020-07-19 14:45 UTC
## Steps to Reproduce

See https://github.com/Hope-Studio/inNENU-flutter/runs/886996626?check_suite_focus=true

Gradle reports that url_launcher is using a deprecated API in WebViewActivity.java

**Expected results:** 

**Actual results:** 

```
Run flutter build apk --target-platform=android-arm64
  flutter build apk --target-platform=android-arm64
  shell: /bin/bash -e {0}
  env:
    FLUTTER_HOME: /opt/hostedtoolcache/flutter/1.17.5-stable/x64
Running Gradle task 'assembleRelease'...                        
Note: /opt/hostedtoolcache/flutter/1.17.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.



FAILURE: Build failed with an exception.
```

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by shameemreza** [comment] 2020-07-19 22:16
Duplicate of #37616

Its just a warning. You can generate the production app and run it without any issue.

**Comment by darshankawar** [comment] 2020-07-20 07:57
Closing this as duplicate of [37616](https://github.com/flutter/flutter/issues/37616)

**Closed by darshankawar** 2020-07-20 07:57 UTC
