### ISSUE TITLE
iOS: TextField on invisible page captures input from keyboard

### ISSUE THREAD

**Issue by arnirichard** [flutter/flutter#123007] opened 2023-03-20 13:09 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample  on iOS
2. Type into TextField on Page1
3. View Page2 and keep typing (the letters will go into the invisible TextField.

**Expected results:** 

Letters should appear on the currently visible TextField

**Actual results:** 

Letters appear in TextField on previous screen.
See video.
I can only replicate on iPhone (iOS 16.3, iPhone Xs)

<details>
<summary>Code sample</summary>

```import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class Page extends StatefulWidget {
  const Page({Key? key}) : super(key: key);

  @override
  State<Page> createState() => _PageState();
}

class _PageState extends State<Page> with AutomaticKeepAliveClientMixin {

  @override
  Widget build(BuildContext context) {
    super.build(context);

    return const Center(child: SizedBox(
      width: 200,
      height: 50,
      child: TextField(autofocus: true),));
  }

  @override
  bool get wantKeepAlive => true;
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  late final PageController _pageController = PageController(keepPage: true);
  final List<Widget> _pages = const [Page(), Page()];

    @override
  Widget build(BuildContext context) {

    return Scaffold(body: Column(children: [
        Expanded(child: PageView(
          controller: _pageController,
          physics: const NeverScrollableScrollPhysics(),
          children: _pages
        )),
        BottomAppBar(child: Row(children: [
          _buildTabItem('Page1', 0),
          _buildTabItem('Page2', 1),
        ],)
      )
    ]));
  }

  Widget _buildTabItem(String title , int index) {

    List<Widget> children = [];

    children.add(Text(
      title,
      style: const TextStyle(color: Colors.black),
    ));

    return Container(
        margin: const EdgeInsets.symmetric(horizontal: 2, vertical: 2),
        constraints: const BoxConstraints(maxWidth: 100),
        child: MaterialButton(
          onPressed: () => {
            _pageController.animateToPage(index,
                duration: const Duration(milliseconds: 300), curve: Curves.ease)
          },
          color: Colors.lightBlue,
          materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
          padding: EdgeInsets.zero,
          highlightColor: Colors.white.withOpacity(.5),
          splashColor: Colors.white.withOpacity(.5),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          child:  Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            children: children,
          ),
        ));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.7.7 on channel stable at /Users/arniarnason/Development/flutter
    • Upstream repository [https://github.com/flutter/flutter.git](https://l.messenger.com/l.php?u=https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git&h=AT0o1htE0BGKlc__kc9rQE0fZayQNlD-qtWxjbxOXpHqKC7Ur2WCs24qj_shSrZHmmsipvibfTgkf__a0ulpksQlZx2HIqFnZPdBKc20Hlm4MwG2KAfPAPF0KC7v9uZUVioqDiU1k28hgbsPvdw)
    • Framework revision 2ad6cd72c0 (12 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
```

</details>

https://user-images.githubusercontent.com/95013472/226347138-b6de2d88-65e7-4b13-b28e-a9bc61e084f0.mp4

**Comment by huycozy** [comment] 2023-03-21 06:07
As far as I can see, this issue is caused by TextField's focus being kept on the previous Page. When focusing on the next page's TextField, the text is displayed normally. You should control it with your implementation code.

https://user-images.githubusercontent.com/104349824/226528013-a9e56712-3bac-494f-875c-6ccd261af65a.MP4

For your case, I would recommend you try [this](https://github.com/flutter/flutter/issues/17098#issuecomment-414610135) to see if it's applicable.

**Comment by arnirichard** [comment] 2023-03-21 06:43
@huycozy Yes, this solves the problem. Thank you for your help.

**Comment by huycozy** [comment] 2023-03-21 07:02
Glad it's helpful. Closing the issue as solved.

**Closed by huycozy** 2023-03-21 07:02 UTC
Labels: in triage
