### ISSUE TITLE
The cells in the dashboard's top row redirect to the builder page not the build run

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#145849] opened 2024-03-27 18:24 UTC
### Type of Request

bug

### Infrastructure Environment

Dashboard

### What is happening?

The cells in the top row of the build dashboard redirect to the builder page that shows the history of the builds for said build and not the particular build itself.

### Steps to reproduce

1. Navigate to the dashboard.
2. Click a yellow cell in the top row of the dashboard.
3. It should redirect to the builder page with a historical list of the previous builds.

### Expected results

I expect to not be redirected and that to see the queue time and run time in a bubble when clicked as shown here:
![image](https://github.com/flutter/flutter/assets/32242716/72b9cc21-e796-45c0-98b9-c59ca26be368)

**Comment by ditman** [comment] 2024-03-28 22:25
@keyonghan no idea, *maybe*. I've also noticed this behavior recently!

**Comment by ditman** [comment] 2024-03-29 02:48
I've checked this a little bit and the problem seems to be that the semantics system is picking up clicks on that first row (in my mac it's 2 rows, it seems).

One potential solution is to comment this out:

* https://github.com/flutter/cocoon/blob/7a67a76fd71d13fe9356e70b5501006371c514d7/dashboard/lib/main.dart#L71

But I think @yjbanov is going to be interested in this issue!

**Comment by keyonghan** [comment] 2024-04-08 17:20
This seems blocking team manaully rerun a failed task from the first row to green the tree. /cc @stuartmorgan 

> One potential workaround is to comment this out:

> https://github.com/flutter/cocoon/blob/7a67a76fd71d13fe9356e70b5501006371c514d7/dashboard/lib/main.dart#L71

@ditman Can I simply remove the line to unblock as suggested? Will this cause any other unexpected behavior? /cc @goderbauer who made changes on this row before.

**Comment by goderbauer** [comment] 2024-04-08 17:44
> @goderbauer who made changes on this row before.

Do you mean the change in https://github.com/flutter/cocoon/commit/354995f6fd4500009d989531cabb3d4a4e7bbcba? That one is replacing an error-prone (private) API call with a public API without changing the behavior. The behavior was originally introduced in https://github.com/flutter/cocoon/pull/1729 - apparently to allow tools like vimium to navigate the dashboard. Presumably, that functionality will break if we'd remove the line to turn on semantics.

**Comment by keyonghan** [comment] 2024-04-08 17:56
By visiting https://chromewebstore.google.com/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb, seems it's blocked internally.

If there is no other quick solutions, we may give it a try to unblock the high demanding usage of dashboard retry (or build executions review from the first row), assuming not much use of that functionality.

**Comment by ricardoamador** [comment] 2024-04-10 03:30
Okay here is something interesting which I think has to do with a different bug that may still be open. If you click the lower righthand corner of the cell it will take you to the build page. This works for the top row. Casey made a change a while back that had an adverse affect on the cells where you had to click different areas of it.

**Comment by gaaclarke** [comment] 2024-05-06 17:20
## workaround
I found that resizing the web browser window will sometimes allow you to get the popup behavior if you are getting the "navigate to builders" behavior.

**Comment by stuartmorgan** [comment] 2024-05-06 17:24
I think it's the tooltip for the header, as I can frequently (although not reliably; I'm not sure what the exact trigger is) get different behavior depending on whether I have hovered over a header before clicking a square that's where the tooltip shows. And in particular I can get it to open the builder for a different column than I'm in if I open a tooltip for that builder first.

**Comment by matanlurey** [comment] 2024-05-06 18:20
I'm proposing the easiest possible fix for this, https://github.com/flutter/cocoon/pull/3706.

**Closed** 2024-05-06 18:28 UTC
Labels: platform-web, team-infra, P2, fyi-web
