### ISSUE TITLE
StreamBuilder once doesn't update when Navigator.push()

### ISSUE THREAD

**Issue by Fogan1703** [flutter/flutter#75971] opened 2021-02-13 15:24 UTC
[Code sample](https://dartpad.dev/96011849d48c1dca311d6c47777a518b) of bug representation. It is just situation where my bug also appears. You can understand what is going on wrong there.

To sign in you have to write one of the right names, which are in the final array in the User class (auth.dart) (now they're Bob, Elizabeth, Tom and Lara)

`flutter doctor` 

```
[√] Flutter (Channel beta, 1.26.0-17.5.pre, on Microsoft Windows [Version 10.0.18363.1379], locale en-CA)
    • Flutter version 1.26.0-17.5.pre at C:\tools\flutter
    • Framework revision 1fe38dcb5f (3 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Zdristi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

```

**Comment by iapicca** [comment] 2021-02-13 22:39
@Fogan1703 
the code sample in your stackoverflow question
```dart
Stream<AppUser> get user => _streamController.stream;

StreamController<AppUser> _streamController = StreamController<AppUser>.broadcast();

//...

//in constructor
FirebaseAuth.instance.userChanges().listen(
      (newUser) {
        if (newUser != null) {
          FirebaseFirestore.instance
              .collection('users')
              .doc(newUser.uid)
              .get()
              .then((DocumentSnapshot documentSnapshot) {
            if (documentSnapshot.exists) {
              _streamController.add(AppUser.fromMap(documentSnapshot.data()));
              return;
            }

            AppUser newCreatedUser = AppUser(
              newUser.uid,
              newUser.displayName,
              newUser.photoURL,
            );
            FirebaseFirestore.instance
                .collection('users')
                .doc(newCreatedUser.uid)
                .set(newCreatedUser.toMap());
            _streamController.add(newCreatedUser);
          });
        } else {
          _streamController.add(null);
        }
      },
    );
```
uses [firebase](https://firebase.flutter.dev/) which is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by Fogan1703** [comment] 2021-02-14 07:21
@iapicca
Ok, I'll do it

**Comment by Fogan1703** [comment] 2021-02-14 09:51
I updated my question. I made this bug in empty project and added repository for it.

**Comment by darshankawar** [comment] 2021-02-15 08:55
@Fogan1703 
I cloned your repo and ran it. Can you elaborate what's the issue here ie, what's the expected vs actual behavior ?

**Comment by Fogan1703** [comment] 2021-02-15 12:54
@darshankawar
When I go to the HomePage I see only CirculatProgressIndicator instead of user's name because last user is null for some reason. And when I do hot reload it goes to the SignInPage.

**Comment by darshankawar** [comment] 2021-02-16 05:57
@Fogan1703 
When I enter a name `(ex: test test)` and tap `Sign in`, I get `wrong name` snackbar. What's the expected behavior here ?
How do I go to HomePage ?

**Comment by Fogan1703** [comment] 2021-02-16 06:46
@darshankawar 
Updated

**Comment by darshankawar** [comment] 2021-02-16 07:54
@Fogan1703 
Tried with `Bob` and `Tom` after which I do see loading indicator. But `hot reloading` still keeps on same screen.
Also, have you tried to debug `because last user is null for some reason.` ?

**Comment by Fogan1703** [comment] 2021-02-16 08:12
@darshankawar 
I tries but no result. Last user is **not** nut in the SignInPage 'cause it **does** go to the HomePage. But it **is** null in the HomePage for some reason. Maybe it is because it notificates about user changing **before** it goes to the HomePage. But if so, HomePage has to have last user, so something goes really wrong I think.

And do `hor restart` instead of `hot reload`. It has weighty difference.

**Comment by darshankawar** [comment] 2021-02-16 08:30
@Fogan1703 
I looked at your code again and noticed `provider` being used, which is 3rd party. Can you try by removing that plugin code and use only core code and check if you still get similar behavior ?

**Comment by Fogan1703** [comment] 2021-02-16 09:09
Ok, I'll do it, but a little later

**Comment by Fogan1703** [comment] 2021-02-16 13:33
@darshankawar
Ok, I removed provider and did it with static fields and methods, but problem's still there

**Comment by iapicca** [comment] 2021-02-16 14:46
@Fogan1703 
I have very strong doubts that changing `initialRoute`  with a `StreamBuilder`
is the indented way to use the [Navigation](https://flutter.dev/docs/development/ui/navigation) api

```dart
 return StreamBuilder<User>(
      stream: Auth.user,
      builder: (context, snapshot) => MaterialApp(
        title: 'Flutter Bug',
        initialRoute: snapshot.hasData ? '/home' : '/sign_in',
        routes: {
          '/sign_in': (context) => SignInPage(),
          '/home': (context) => HomePage(),
        },
      ),
    );

```

everyone is obviously free to code however he or she wants,
but this a problem with your implementation and **_not a bug with flutter_**, 

if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by Fogan1703** [comment] 2021-02-16 15:20
@iapicca
Ok, but even if I remove StreamBuilder (I also updated my repo), problem's still there. And it does not apply to my problem

**Comment by iapicca** [comment] 2021-02-16 17:46
@Fogan1703 
try this https://gist.github.com/iapicca/2f5105b41a1136f225d1b8d077e00b3b

**Comment by Fogan1703** [comment] 2021-02-16 17:58
@iapicca
I got `welcom` title

**Comment by darshankawar** [comment] 2021-02-17 06:13
@Fogan1703 
Cloned your updated repo, but app is crashing with below error:

```
E/AndroidRuntime(29169): FATAL EXCEPTION: main
E/AndroidRuntime(29169): Process: com.example.bug, PID: 29169
E/AndroidRuntime(29169): java.lang.NoSuchMethodError: No virtual method getLongVersionCode()J in class Landroid/content/pm/PackageInfo; or its super classes (declaration of 'android.content.pm.PackageInfo' appears in /system/framework/framework.jar)
```

**Comment by Fogan1703** [comment] 2021-02-17 08:14
@darshankawar
I don't know, it works normally for me

**Comment by darshankawar** [comment] 2021-02-17 11:00
@Fogan1703 
Sorry it was my bad. The idea behind @iapicca sharing his code sample, is to try and include it in your code sample per your need and see if the updated implementation works for you.

**Comment by devk320** [comment] 2021-02-17 11:04
@darshankawar
Ok, I removed provider and did it with static fields and methods, but problem's still there

**Comment by iapicca** [comment] 2021-02-17 12:28
@Fogan1703  
with my following statement I do not mean any disrespect,
I actually do respect tinkering and experimenting, but
since I see that other developers (@devk320 ) are looking into this code sample
and might get misguided by your "_unconventional_"  implementation

I feel compelled to point out what I believe is **_WRONG_** in the [code sample you provided](https://github.com/Fogan1703/flutter-stream-builder-bug)
- it's **_very_** inefficient as you literally rebuild your whole `MaterialApp` each time you navigate
- ignores most of the [Navigation](https://flutter.dev/docs/development/ui/navigation) api and its core concepts
- dangerously ignores best practices
   - example `  static StreamController<User> _controller = StreamController<User>.broadcast();` never closes

if you don't like the [my code sample](https://dartpad.dartlang.org/2f5105b41a1136f225d1b8d077e00b3b)
and you are married to the idea of using a [StreamBuilder](https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html) you can just do this

<details>
<summary>code sample w/o navigation</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';

const validUser = [
  'bob',
  'elizabeth',
  'tom',
  'lara',
];

abstract class LoginStatus {
  const LoginStatus();
  const factory LoginStatus.loggedIn() = LoggedIn;
  const factory LoginStatus.loggedOut() = LoggedOut;
}

class LoggedIn implements LoginStatus {
  const LoggedIn();
}

class LoggedOut implements LoginStatus {
  const LoggedOut();
}

class AuthAPI extends InheritedWidget {
  AuthAPI({
    @required Widget child,
  })  : _controller = StreamController<LoginStatus>.broadcast(),
        assert(child != null),
        super(
          key: const ValueKey('AuthAPI'),
          child: child,
        );

  Stream<LoginStatus> get status => _controller.stream;

  final StreamController<LoginStatus> _controller;

  void login(String name) {
    if (validUser.contains(name)) {
      _controller.sink.add(const LoginStatus.loggedIn());
    }
  }

  void logout() {
    _controller.sink.add(const LoginStatus.loggedOut());
  }

  void dispose() {
    _controller?.close();
  }

  static AuthAPI of(BuildContext context) =>
      context.dependOnInheritedWidgetOfExactType<AuthAPI>();

  @override
  bool updateShouldNotify(_) => false;
}

void main() => runApp(AuthAPI(child: const MyApp()));

class MyApp extends StatefulWidget {
  const MyApp() : super(key: const ValueKey('MyApp'));

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void dispose() {
    AuthAPI.of(context).dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: StreamBuilder<LoginStatus>(
          stream: AuthAPI.of(context).status,
          initialData: const LoginStatus.loggedOut(),
          builder: (context, snapshot) => snapshot.data is LoggedIn
              ? const MyWelcomePage()
              : snapshot.data is LoggedOut
                  ? const MyHomePage()
                  : const Material(child: Center(child: Icon(Icons.error))),
        ),
      );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage() : super(key: const ValueKey('MyHomePage'));

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  @override
  void dispose() {
    print('dispose');
    _controller?.dispose();
    super.dispose();
  }

  static const _focused = OutlineInputBorder(
    borderSide: BorderSide(color: Colors.blue, width: 3),
  );

  static const _enabled = OutlineInputBorder(
    borderSide: BorderSide(color: Colors.blue, width: 1),
  );

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: Padding(
            padding: EdgeInsets.symmetric(
              horizontal: MediaQuery.of(context).size.width * .2,
            ),
            child: TextField(
              controller: _controller,
              decoration: const InputDecoration(
                focusedBorder: _focused,
                enabledBorder: _enabled,
                hintText: 'just type `bob`',
              ),
            ),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.login),
          onPressed: () => AuthAPI.of(context).login(
            _controller.text.toLowerCase(),
          ),
        ),
      );
}

class MyWelcomePage extends StatelessWidget {
  const MyWelcomePage() : super(key: const ValueKey('MyWelcomePage'));

  @override
  Widget build(BuildContext context) => Scaffold(
        body: const Center(child: Text('welcome')),
        floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.logout),
          onPressed: AuthAPI.of(context).logout,
        ),
      );
}

```

</details>

once again, I'm convinced this is NOT a bug with flutter
and I recommend you to follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by Fogan1703** [comment] 2021-02-17 15:37
@iapicca
I think you understood me wrong. My problem is not with my navigation. My problem is when I go to HomePage I see progress indicators insted of user's name. 
I know my realization of navigation was not correct. I'm working on it and it will be nice later, so that's not care. And I already wrote that I removed StreamBuilder that was above my App class.

Don't take it offensive if it is

**Comment by Fogan1703** [comment] 2021-02-17 16:10
@iapicca
Oops, I missed something in your code sample. I will try it a little later, I don't have possibility now.

Can I add `waiting for custemer response` by myself? If no, please, somebody do it

**Comment by iapicca** [comment] 2021-02-17 16:22
@Fogan1703 
wait... I understand: it's the `ConnectionState.waiting` problem
you are trying to listen the **old ** value from the stream **after** the `StreamBuilder` was even built

> stream emits value => welocome page built => streambuilder awaits new value... 

this isn't supposed to work;  try replacing [this ](https://gist.github.com/Fogan1703/96011849d48c1dca311d6c47777a518b#file-main-dart-L16) with the code below
(the code below is purely demonstrative, not a solution or even a workaround **don't use it in production**)

```dart
  static void signIn(User user) async {
    final _user =
        User.users.any((existingUser) => user.name == existingUser.name)
            ? user
            : null;
    if (_user != null) {
      await Future.delayed(Duration(seconds: 2));
      _controller.add(_user);
    }
    await Future.delayed(Duration(seconds: 2));
    _controller.add(_user);
  }

```

if you really want to follow this approach you may want to use [bloc](https://bloclibrary.dev/)
I'm 99% sure it has a workaround built in

regarding your [initial code](https://github.com/flutter/flutter/issues/75971#issuecomment-778688238), this might not even the case, take a look at this [answer](https://stackoverflow.com/questions/55919816/streambuilder-snapshot-is-always-connectionstate-waiting)

**Comment by Fogan1703** [comment] 2021-02-17 17:00
@iapicca

> this isn't supposed to work;
> just for purely demonstrative purpose, (this is not a solution or even a workaround **don't use it in production**)
> try replacing [this ](https://gist.github.com/Fogan1703/96011849d48c1dca311d6c47777a518b#file-main-dart-L16) with the code below
> 
> ```dart
>   static void signIn(User user) async {
>     final _user =
>         User.users.any((existingUser) => user.name == existingUser.name)
>             ? user
>             : null;
>     if (_user != null) {
>       await Future.delayed(Duration(seconds: 2));
>       _controller.add(_user);
>     }
>     await Future.delayed(Duration(seconds: 2));
>     _controller.add(_user);
>   }
> ```

Nothing


> regarding your [initial code](https://github.com/flutter/flutter/issues/75971#issuecomment-778688238), this might not even be the case, take a look at this [answer](https://stackoverflow.com/questions/55919816/streambuilder-snapshot-is-always-connectionstate-waiting)

You wrote link that passes just to the question, not answer, so I can't see what you wanted me to look at


> if you really want to follow this approach you may want to use [bloc](https://bloclibrary.dev/) I'm 99% sure it has a workaround built in

Ok, so I'm closing the issue and trying to do it using bloc

**Comment by darshankawar** [comment] 2021-02-18 06:26
@Fogan1703 
The SO link @iapicca shared has related answers as why you may be getting a loading indicator. So you may need to go through them and see if any of those help you to resolve the issue.
I am now thinking, this issue / question is best suited for support channels and StackOverflow. 

> if you really want to follow this approach you may want to use [bloc](https://bloclibrary.dev/) I'm 99% sure it has a workaround built in

You may also explore possibility of using above suggested library. 
I am going ahead and closing this. Please see https://flutter.dev/community for resources and if you need help with your code, please see https://www.reddit.com/r/flutterhelp/

If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by darshankawar** 2021-02-18 06:26 UTC
Labels: in triage
