### ISSUE TITLE
[cloud_firestore] Plugin adds about 150M to IPA size

### ISSUE THREAD

**Issue by tapizquent** [flutter/flutter#47795] opened 2019-12-25 22:27 UTC
My project was reading a huge size for the IPA (170M) in comparison to the APK (20M) so I went ahead and created a new project and started adding plugins one by one and measuring the size right after to identify where the huge size was coming from.

Right as I added `cloud_firestore`, the size for the IPA jumped from:

**New project:** `-rw-r--r--  1 tapizquent  staff    21M Dec 25 17:00 build/app.ipa`

to:

**After adding cloud_firestore**: `-rw-r--r--  1 tapizquent  staff   172M Dec 25 17:16 build/app.ipa`

As can be clearly seen, that is a **150M** increase in IPA size for just 1 plugin, which is definitely not okay. 

## Steps to Reproduce

1. Generate a new flutter project
2. Measure its IPA size using steps recommended here: https://flutter.dev/docs/perf/app-size or simply run:
`flutter build ios && tar -zcf build/app.ipa build/ios/iphoneos/Runner.app && ls -lh build/app.ipa`
and observe the output. For me it was about 21M (Which is still huge for new project but ok)
3. Add `could_firestore` to `pubspec.yaml` and save (call `flutter pub get`).
4. Re-run `flutter build ios && tar -zcf build/app.ipa build/ios/iphoneos/Runner.app && ls -lh build/app.ipa`

**Target Platform:**
iOS

## Logs

```
Analyzing firestore_size_test...                                        
No issues found! (ran in 3.9s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/tapizquent/Projects/tools/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/tapizquent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone • ios • iOS 13.3

• No issues found!
```

**Comment by cbenhagen** [comment] 2019-12-26 14:37
Did you see https://github.com/flutter/flutter/issues/47101#issuecomment-567522077?

**Comment by tapizquent** [comment] 2019-12-26 21:48
I did but how come it increases the size dramatically after adding cloud_firestore plugin and before it was way smaller?

**Comment by iapicca** [comment] 2019-12-27 09:23
Hi @tapizquent 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-27 09:23 UTC
