### ISSUE TITLE
Hard-crash on flutter run

### ISSUE THREAD

**Issue by kentcb** [flutter/flutter#14546] opened 2018-02-08 05:19 UTC
## Steps to Reproduce

Seemingly out of nowhere, my app started crashing on startup. Initially I thought it might be due to recent changes, so I backed out to a prior build that I knew to be working. That also failed. So I tried with a brand new project:

1. `flutter create repro`
2. `cd repro`
3. `flutter run`

_That also fails_.

Note that the same app built via `flutter build apk` does work when I deploy it to my device.

I've tried:
* `flutter clean`
* restarting my machine
* plugging/unplugging my device

None of these things worked, but switching channels to alpha did. So I assume this has to do with the fact that I upgraded flutter earlier this morning and master is currently broken? Super weird that it didn't trigger any problem for _hours_ after the upgrade.

## Logs

Output from `flutter run`:
```
flutter run
Launching lib/main.dart on Pixel in debug mode...
Initializing gradle...                                0.8s
Resolving dependencies...                             1.3s
Running 'gradlew assembleDebug'...                    2.2s
Built build\app\outputs\apk\debug\app-debug.apk (25.3MB).
```

Output from `flutter analyze`:
```
flutter analyze
Analyzing C:\Users\kent\Repository\repro...
No issues found!
Ran in 5.3s
```

Output in logcat:
```
02-08 15:13:48.967: A/libc(23708): Fatal signal 4 (SIGILL), code 1, fault addr 0x7ad3fc0400 in tid 23746 (ui_thread), pid 23708 (m.example.repro)
02-08 15:13:48.990: I/Icing(20243): App usage reports: 1
02-08 15:13:48.990: I/Icing(20243): Usage reports ok 1, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
02-08 15:13:49.001: I/crash_dump64(23752): obtaining output fd from tombstoned, type: kDebuggerdTombstone
02-08 15:13:49.002: I//system/bin/tombstoned(743): received crash request for pid 23708
02-08 15:13:49.005: I/crash_dump64(23752): performing dump of process 23708 (target tid = 23746)
02-08 15:13:49.006: A/DEBUG(23752): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-08 15:13:49.006: A/DEBUG(23752): Build fingerprint: 'google/sailfish/sailfish:8.1.0/OPM1.171019.012/4470837:user/release-keys'
02-08 15:13:49.006: A/DEBUG(23752): Revision: '0'
02-08 15:13:49.006: A/DEBUG(23752): ABI: 'arm64'
02-08 15:13:49.006: A/DEBUG(23752): pid: 23708, tid: 23746, name: ui_thread  >>> com.example.repro <<<
02-08 15:13:49.006: A/DEBUG(23752): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7ad3fc0400
02-08 15:13:49.006: A/DEBUG(23752):     x0   0000007ad3480821  x1   0000007ad3480821  x2   0000007ad3400c20  x3   0000007ad3480820
02-08 15:13:49.006: A/DEBUG(23752):     x4   0000007ad4042e01  x5   0000007ad34a9d31  x6   0000007ad34808e1  x7   0000000000000001
02-08 15:13:49.006: A/DEBUG(23752):     x8   0000007ae4e5ca00  x9   0000000000000000  x10  0000000000000001  x11  000000000000000d
02-08 15:13:49.006: A/DEBUG(23752):     x12  ffffffffffffe000  x13  0000007ad34aa050  x14  000f714b96000000  x15  0000007ad3dbec70
02-08 15:13:49.006: A/DEBUG(23752):     x16  00000000000c0600  x17  0000007ad34a9da1  x18  0000007ad6771000  x19  0000007ae4e5ca00
02-08 15:13:49.006: A/DEBUG(23752):     x20  0000000000000000  x21  0000007ae4eba338  x22  0000007ae4eba348  x23  0000007ae4eba368
02-08 15:13:49.006: A/DEBUG(23752):     x24  0000007ad4043961  x25  0000007ad3dbdc80  x26  0000007ae4e5ca00  x27  0000007ad34aa050
02-08 15:13:49.006: A/DEBUG(23752):     x28  0000007ad6f262a8  x29  0000007ad3dbecb0  x30  0000007ad3400ce4
02-08 15:13:49.006: A/DEBUG(23752):     sp   0000007ad3dbdcc0  pc   0000007ad3fc0400  pstate 0000000040000000
02-08 15:13:49.007: A/DEBUG(23752): backtrace:
02-08 15:13:49.007: A/DEBUG(23752):     #00 pc 0000000000000400  <anonymous:0000007ad3fc0000>
02-08 15:13:49.007: A/DEBUG(23752):     #01 pc 0000000000000ce0  <anonymous:0000007ad3400000>
02-08 15:13:49.013: I/Icing(20243): Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0, imm upload false
02-08 15:13:49.507: E//system/bin/tombstoned(743): Tombstone written to: /data/tombstones/tombstone_07
```
## Flutter Doctor

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale en-AU, channel master)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] VS Code (version 1.19.3)
[√] Connected devices

• No issues found!
```

**Comment by xster** [comment] 2018-02-09 01:28
cc @jason-simmons 
Maybe a 64-bit dupe?

**Comment by jason-simmons** [comment] 2018-02-09 01:52
Duplicate of https://github.com/flutter/flutter/issues/14454

I just landed a patch that will deploy 32-bit APKs on all devices (unless you explicitly specify --target-platform=android-arm64)

**Closed by jason-simmons** 2018-02-09 01:52 UTC
