### ISSUE TITLE
[web]: Decoration not working on TextField and Container if I set image in background.

### ISSUE THREAD

**Issue by GaneshShiroleScorg** [flutter/flutter#49142] opened 2020-01-19 18:39 UTC
Decoration not working on TextField and Container if I set image in background., flutter_web 1.12, Chrome 79.0.3945.130

```
Container(
          decoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage("assets/tree.webp"),
              fit: BoxFit.cover,
            ),
          ),
          child: Column(
            children: <Widget>[
              Container(
                decoration: BoxDecoration(
                  border: Border.all(
                    color: Colors.red, //                   <--- border color
                    width: 5.0,
                  ),
                ),
                child: Text(
                  "Test",
                  style: TextStyle(color: Colors.white),
                ),
              ),
              TextField(
                style: TextStyle(color: Colors.white),
                decoration: InputDecoration(
                    border: OutlineInputBorder(
                      borderSide: BorderSide(
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(10.0),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderSide: BorderSide(
                        color: Colors.blue,
                      ),
                      borderRadius: BorderRadius.circular(10.0),
                    ),
                    hintText: "Focus decoration text ...",
                    hintStyle: TextStyle(color: Colors.white)),
              ),
            ],
          ),
        )
```

**Comment by GaneshShiroleScorg** [comment] 2020-01-19 18:40
Please resolve this issue as soon as possible I want to publish my website.

**Comment by VladyslavBondarenko** [comment] 2020-01-20 08:15
Hi @GaneshShiroleScorg ,
This [was already fixed](https://github.com/flutter/flutter/issues/40728#issuecomment-534297853) in master channel, but these changes are not yet in stable.
I run your code with master and I can see the red border for title, while I couldn't with dev channel.
You may consider to switch to master.
Closing the issue as duplicate of https://github.com/flutter/flutter/issues/40728
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-01-20 08:15 UTC
