### ISSUE TITLE
SelectableText.rich Widget can not select a whole line text with textAlign is justify

### ISSUE THREAD

**Issue by BayMikyou** [flutter/flutter#43893] opened 2019-10-31 08:54 UTC
## Steps to Reproduce

1. when textAlign is **default or TextAlign.start** is OK

![image](https://user-images.githubusercontent.com/31265255/67932324-a4ffc000-fbfe-11e9-96ef-e6c113db1933.png)

2. when textAlign is **TextAlign.justify** is unexpected

![image](https://user-images.githubusercontent.com/31265255/67932410-d1b3d780-fbfe-11e9-9d37-d25f61c892ad.png)

**Comment by HansMuller** [comment] 2019-10-31 15:58
CC @chunhtai

**Comment by chunhtai** [comment] 2019-12-27 05:10
@BayMikyou 
I cannot reproduce this issue. Here is my code
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(title: 'test',));
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SelectableText.rich(
              TextSpan(
          text: 'This class is the configurationforthestate.Itholdsthevalues(inthiscasethetitle)providedbytheparent(inthis case the App widget) and used by the build method of the State. Fields in a Widget subclass arealways marked "final".',
              ),
              textAlign: TextAlign.justify,
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

<img width="357" alt="Screen Shot 2019-12-26 at 9 07 58 PM" src="https://user-images.githubusercontent.com/47866232/71502252-02da0e00-2824-11ea-8b9f-83ec141ca589.png">
Can you share a minimum reproducible example?

**Comment by TahaTesser** [comment] 2020-04-16 14:47
Hi @BayMikyou 
Are you still experiencing this issue with latest stable?
if yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment] 2020-06-05 13:06
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-06-05 13:06 UTC
Labels: a: text input, f: material design, framework, waiting for customer response
