### ISSUE TITLE
Using Image.asset in a package throws `Unable to load asset`

### ISSUE THREAD

**Issue by nicholasspencer** [flutter/flutter#110686] opened 2022-08-31 16:56 UTC
## Steps to Reproduce

My company has several packages that include assets and we have widget tests
in those packages that test trees that include assets. While upgrading to 3.3.0, if 
we include the `package:` parameter in `Image.asset` the tests will throw. If we 
exclude the package name, the image will not load in an app (expected) but the
tests pass. This is new behavior with 3.3.0. Tests pass and our apps run as 
expected under 3.0.5.

1. Run an app and execute tests on the code sample

**Expected results:** 

Assets load in app code and under widget tests

**Actual results:** 

Assets load in one or the other... not both

<details>
<summary>Code sample</summary>

 ([full example project](https://github.com/nicholasspencer/png_test_flutter))

```dart
/// example widget tree in package
class PngTest extends StatelessWidget {
  const PngTest({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      /// Works when running the app
      /// Doesn't work under test
      Image.asset(
        'assets/pngs/ethernet_connected.png',
        package: 'png_test',
      ),

      /// Doesn't work when running in an app
      /// Work under test
      Image.asset(
        'assets/pngs/ethernet_disconnected.png',
        // package: 'png_test',
      ),
    ]);
  }
}
```

```dart
/// example widget test in package
void main() {
  testWidgets('Image.asset', (tester) async {
    TestWidgetsFlutterBinding.ensureInitialized();

    tester.pumpWidget(
      const MaterialApp(home: PngTest()),
    );
  });
}
```

```dart
/// example app usage
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const [PngTest()],
        ),
      ),
    );
  }
}
```

```yaml
# pubspec.yaml of package
name: png_test
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/pngs/
```

</details>

<details>
  <summary>Logs</summary>

```bash
# flutter test in package

00:00 +0: loading /Users/nicholasspencer/Development/png_test/test/png_test_test.dart                                                                                                                  
00:01 +0: loading /Users/nicholasspencer/Development/png_test/test/png_test_test.dart                                                                                                                  
00:02 +0: loading /Users/nicholasspencer/Development/png_test/test/png_test_test.dart                                                                                                                  
00:02 +0: Image.asset                                                                                                                                                                                  
00:02 +0: Image.asset                                                                                                                                                                                  
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/png_test/assets/pngs/ethernet_connected.png.

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:272:7)
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:731:35)
#2      AssetBundleImageProvider.loadBuffer (package:flutter/src/painting/image_provider.dart:695:14)
#3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:513:13)
#4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:384:22)
#5      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:511:81)
#6      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:358:9)
#8      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:473:24)
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

Image provider: AssetImage(bundle: null, name:
  "packages/png_test/assets/pngs/ethernet_connected.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#013b2(), name:
  "packages/png_test/assets/pngs/ethernet_connected.png", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

00:02 +0 -1: Image.asset [E]                                                                                                                                                                           
  Test failed. See exception logs above.
  The test description was: Image.asset
  

To run this test again: /Users/nicholasspencer/fvm/versions/stable/bin/cache/dart-sdk/bin/dart test /Users/nicholasspencer/Development/png_test/test/png_test_test.dart -p vm --plain-name 'Image.asset'

00:02 +0 -1: Some tests failed.                                                                                                                                                                        
```

```bash
# flutter run -v in app
[   +1 ms] Syncing files to device iPhone 13 Pro Max... (completed in 98ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x7ff5b6014620.
[   +4 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on iPhone 13 Pro Max is available at: http://127.0.0.1:49882/dT0CepEf17w=/
[ +104 ms] 
           ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
           The following assertion was thrown resolving an image codec:
           Unable to load asset: assets/pngs/ethernet_disconnected.png.

           When the exception was thrown, this was the stack:
           #0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:272:7)
           #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:731:35)
           #2      AssetBundleImageProvider.loadBuffer (package:flutter/src/painting/image_provider.dart:695:14)
           #3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:513:13)
           #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:384:22)
           #5      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:511:81)
           #6      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
           #7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:358:9)
           #8      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:473:24)
           <asynchronous suspension>

           Image provider: AssetImage(bundle: null, name: "assets/pngs/ethernet_disconnected.png")
           Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#fd9c7(), name:
             "assets/pngs/ethernet_disconnected.png", scale: 1.0)
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +246 ms] The Flutter DevTools debugger and profiler on iPhone 13 Pro Max is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:49882/dT0CepEf17w=/
[+134838 ms] Application finished.

```

```bash
Analyzing example...                                            
No issues found! (ran in 2.9s)
```

```bash
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-x64, locale en-US)
    • Flutter version 3.3.0 on channel stable at /Users/nicholasspencer/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (2 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/nicholasspencer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_SDK_ROOT = /Users/nicholasspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 7C156174-5C99-408B-8899-FD1F8C627ABC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by DeToxer** [comment] 2022-08-31 20:23
I'm also encountering this issue in my UI tests. 
Flutter 3.3.0 -> UI tests fails (unable to load asset).
Downgrade to 3.0.5 -> Everything runs fine.

**Comment by exaby73** [comment] 2022-09-01 10:13
Hello @nicholasspencer. This is occurring because you are running the app from an example app (therefore you need the `package` param) and the test from the package (therefore you don't need it). If you move the test from `test/png_test_test.dart` to `example/test/png_test_test.dart` and run `flutter test` from the example folder, you will see the same result as running the app.

I am closing this issue as everything is working as expected. Thank you.

**Comment by remcoanker** [comment] 2022-09-01 10:33
What's the reason for this change in 3.3.0? Tests for a package should be in the package repository, not the app using it. This breaks tests that are in the package itself.

**Comment by nicholasspencer** [comment] 2022-09-01 14:35
> Hello @nicholasspencer. This is occurring because you are running the app from an example app (therefore you need the `package` param) and the test from the package (therefore you don't need it). If you move the test from `test/png_test_test.dart` to `example/test/png_test_test.dart` and run `flutter test` from the example folder, you will see the same result as running the app.
> 
> I am closing this issue as everything is working as expected. Thank you.

@exaby73 Thanks for the reply. Unfortunately I think there is a misunderstanding...

The tests are supposed to be in the package. We are testing widgets that are exposed from the package. My company has several apps that depend on core packages that reuse widgets and assets. These widgets in these core packages are tested. Hence, this is a bug.

**Comment by bleroux** [comment] 2022-09-01 14:57
@nicholasspencer
@exaby73 will probably reopen this, add the regression label and ask for team insights when he will be online. Thank you for your patience.

**Comment by Jordan-Nelson** [comment] 2022-09-01 18:39
Hi @exaby73 - Multiple customers (myself included) are reporting this as a regression as it was working 3.0.5, and is not working in 3.3.

This is either an unintentional regression in 3.3, or an intentional breaking change. It seems to me that this is an unintentional regression. If this was an intentional breaking change, can you explain why support for loading assets within widgets tests from a package was dropped in 3.3?

**Comment by exaby73** [comment] 2022-09-01 18:44
@Jordan-Nelson @nicholasspencer @remcoanker I'll reopen this issue as I misunderstood it. Tested on previous versions, and I see the regression you are describing. Labelling for more insights from the team

**Comment by christopherfujino** [comment] 2022-09-06 20:19
cc @eliasyishak & @andrewkolos

**Comment by andrewkolos** [comment] 2022-09-06 20:43
cc @jonahwilliams

**Comment by jonahwilliams** [comment] 2022-09-06 21:10
So this was likely cause by a change I made that replaced the bespoke unit test asset loader with the same asset loader used by the framework. As a result, this broke the behavior that `package/<current-package>/<asset-name>` would load assets and instead the same strategy used by the code under lib would need to be used instead.

Its unclear to me if this is actually desirable behavior, or if instead `package/<current-package>/<asset-name>` should work regardless of whether or not you are running the app or running the unit test. The divergence of behavior seems like it has the potential to be confusing.

@nicholasspencer what is the fix you'd like to see here. Do you actually want the old behavior / are you able to update to the new behavior?

**Comment by nicholasspencer** [comment] 2022-09-06 22:32
> Do you actually want the old behavior / are you able to update to the new behavior?

@jonahwilliams What would updating to the new behavior look like? I want to say that the old behavior made sense based on [API documentation](https://api.flutter.dev/flutter/painting/AssetImage-class.html) and the [Assets and images documentation](https://docs.flutter.dev/development/ui/assets-and-images#from-packages).

With the current API for `AssetImage` and `Image.asset`, I would assume that if the `package` parameter is not null, any kind of "`<current-package>`" logic would be disregarded and the package name would be explicitly used. I should note that this appears to not be affecting the loading other types of assets.

If we were to try and use this new behavior, would we have to introduce a `DefaultAssetBundle` in our package's tests that resolve differently? I guess I'm kind of stumped on this. Or maybe it's as easy as fully realizing the asset path in the key parameter instead of using the `package` parameter (🤔 I should try that.) My specific situation, and I assume others, is that we have shared image assets in packages. Some of these assets as loaded by trees internally, some are just `Image.asset` wrappers so that we can constantly defined the images and avoid strings all over the place. These widgets explicitly set the package name in `Image.asset` because, although the assets and code exist in the package together, the widget is expected to be used (and the asset loaded) in code that depends on the package. I would expect package tests to test packages as if they're being used by something that depends on it.

**Comment by DeToxer** [comment] 2022-09-10 12:02
Any ETA on this? This issue keeps me on 3.0.5.
If a fix is not in the near future, what are some work arounds I can do? I've tried quite a few things to be able to load image assets during UI tests, but it still fails

**Comment by dustin-genter** [comment] 2022-09-12 12:23
@jonahwilliams What is a workaround for this bug? When will it be fixed or documentated?

**Comment by maik-kluwe** [comment] 2022-09-12 12:24
> The tests are supposed to be in the package. We are testing widgets that are exposed from the package. My company has several apps that depend on core packages that reuse widgets and assets. These widgets in these core packages are tested. Hence, this is a bug.

We experience the same problem here. We have a core package to reuse widgets in multiple projects. 

> I'm also encountering this issue in my UI tests. Flutter 3.3.0 -> UI tests fails (unable to load asset). Downgrade to 3.0.5 -> Everything runs fine.

As mentioned here, we have the same problem keeping us in Version 3.0.5.

> @nicholasspencer what is the fix you'd like to see here. Do you actually want the old behavior / are you able to update to the new behavior?

I would definitely expect that the framework should find the given asset as it worked before. Especially if the package is given while loading the asset.

**Comment by desmond206x** [comment] 2022-09-12 12:34
@jonahwilliams What is the workaround for this?

**Comment by jonahwilliams** [comment] 2022-09-12 15:07
Deduplicating into https://github.com/flutter/flutter/issues/111285

In general the workaround would be to load assets in tests the same way you load them in the applicaiton. This seems too breaking for now so I'll put together a cherry pick

**Closed by jonahwilliams** 2022-09-12 15:07 UTC
Labels: a: tests, severe: regression, tool, has reproducible steps, P4, r: duplicate, found in release: 3.1, found in release: 3.3

**Comment by Jordan-Nelson** [comment] 2022-09-12 15:14
@jonahwilliams - is this being tracked in #111285 now? I wasn't sure from the previous comment if that is what you meant.

I might suggest keeping this one open over #111285 as it has been open longer and has more people following it.

**Comment by rydmike** [comment] 2022-09-12 18:46
Pretty sure this is the issue I had one of my packages as well. Saw it in beta 3.3.x before 3.3.0 stable release. It worked OK in 3.0.5, but failed on beta 3.3, did not have time to figure out why so I temporarily disabled the test until I could get back to it. Have not done so yet, but seems like now is a good idea to do so and see if this fixes it.

**Comment by nicholasspencer** [comment] 2022-09-13 05:43
> @jonahwilliams - is this being tracked in #111285 now? I wasn't sure from the previous comment if that is what you meant.
> 
> I might suggest keeping this one open over #111285 as it has been open longer and has more people following it.

right, wouldn't the other one be a duplicate? :suspect:

**Comment by maik-kluwe** [comment] 2022-09-13 06:35
@jonahwilliams Thans for the information and the work!

Is my assumption correct that the cherry pick will be available in the next hotfix / fix version?

**Comment by DeToxer** [comment] 2022-09-16 12:45
Works now in v3.3.2
