### ISSUE TITLE
Render page bursted when wakeup from background

### ISSUE THREAD

**Issue by ipconfiger** [flutter/flutter#59303] opened 2020-06-12 04:19 UTC
## Steps to Reproduce

step1. put the app in background
step2. wakeup the app

And the screen not fully rendered, it shows like below

![3746EB59-9950-4558-A3A5-79217548A74C](https://user-images.githubusercontent.com/950968/84464803-0f560400-aca8-11ea-8831-214906b9f397.png)

**Comment by TahaTesser** [comment] 2020-06-12 10:53
Hi @ipconfiger 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment] 2020-07-03 11:24
Closing as duplicate of https://github.com/flutter/flutter/issues/59754

**Closed by TahaTesser** 2020-07-03 11:24 UTC
Labels: in triage, waiting for customer response
