### ISSUE TITLE
[tool_crash] ProcessException: The requested operation requires elevation. Command: "C:\Program Files\Google\Chrome\Application\chrome.exe", OS error code: 740

### ISSUE THREAD

**Issue by Agus9090** [flutter/flutter#80599] opened 2021-04-16 22:03 UTC
## Command
```
flutter run -d chrome --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The requested operation requires elevation.
 Command: "C:\Program Files\Google\Chrome\Application\chrome.exe", OS error code: 740
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:664:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:663:12)
#6      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:243:53)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:221:36)
<asynchronous suspension>
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:136:17)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:541:9)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 2.2.0-10.1.pre, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 2.2.0-10.1.pre at D:\flutter\flutter
    • Framework revision 0941968447 (27 hours ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Devs\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Devs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.72

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b1395592de68cc8ac4522094ae59956dd21a91db
### Plugins
connectivity-3.0.3
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_messaging-7.0.3
flutter_local_notifications-3.0.3
flutter_plugin_android_lifecycle-1.0.11
flutter_webview_plugin-0.3.11
geolocator-5.3.2+2
google_api_availability-2.0.4
google_maps_flutter-0.5.33
image_picker-0.6.7+22
location_permissions-3.0.0+1
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.5
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
webview_flutter-0.3.24
wifi_info_flutter-2.0.0

**Comment by darshankawar** [comment] 2021-04-19 07:19
Closing this as duplicate of https://github.com/flutter/flutter/issues/78240

**Closed by darshankawar** 2021-04-19 07:19 UTC
Labels: in triage
