### ISSUE TITLE
[Linux/GTK] Many emojis don't work and show as rectangles, others show in hard to read s/w outline only

### ISSUE THREAD

**Issue by ell1e** [flutter/flutter#74124] opened 2021-01-16 17:54 UTC
On Linux using the GTK+ Flutter app "Fluffychat," many emojis don't work and show as rectangles, others show in hard to read s/w outline only. It seems like basically no proper complete and colored emoji font is used, resulting in very poor and many completely missing emoji renderings. The app developer [suggested this might be a flutter upstream issue.](https://gitlab.com/famedly/fluffychat/-/issues/229)

## Steps to Reproduce

1. Install fluffychat from flathub.org on Linux: https://flathub.org/apps/details/im.fluffychat.Fluffychat (which uses flutter GTK)
2. Run it and have somebody else send an emoji to you (since due to #24153 there appears to be no way to enter them yourself on desktop)
3. Look at the result

**Expected results:** A proper colored emoji rendering, like the ones on GitHub: :smile: :heavy_check_mark: 

**Actual results:** s/w outlined hard to visually read emojis that are also small, or even just plain rectangles: ![](https://gitlab.com/famedly/fluffychat/uploads/f1ea5e7a74156fa4c42e9c9c29bafb45/Screenshot_from_2020-12-18_19-32-37.png)

*(logs omitted since I never used flutter as a developer, so i don't have any tooling installed)*

**Comment by stuartmorgan** [comment] 2021-01-17 11:52
Duplicate of https://github.com/flutter/flutter/issues/30700

**Closed by stuartmorgan** 2021-01-17 11:52 UTC

**Comment by stuartmorgan** [comment] 2021-01-17 11:57
> 2\. since due to #24153 there appears to be no way to enter them yourself on desktop

That's an Android bug. Entering emoji using whatever input system you would normally use to enter emoji on your system should work.

**Comment by ell1e** [comment] 2021-01-17 13:08
@stuartmorgan ... I'm on Linux??

**Comment by stuartmorgan** [comment] 2021-01-17 13:52
> So how do you enter emojis normally on your desktop PC?

I primarily use macOS and Windows; both have system UI elements for controlling input methods, as well as dedicated keyboard shortcuts that bring up an emoji panel. Since you're on Linux how that works would depend on your desktop environment but unless you're using something extremely minimal i would be surprised if there's nothing available.

> Nevertheless, there is #24153 after all. But it is pretty vital for desktop, which is why I left that small note in the text to point that out,

That issue is about controlling the presence of the emoji button on the Android (or iOS) virtual keyboard. Since you presumably don't have a virtual keyboard on your Linux system in not sure how you believe that issue is relevant to your use case.

**Comment by ell1e** [comment] 2021-01-17 14:02
Ohhh, I see, my bad! I did indeed misunderstand the issue then, I thought it was about an emoji button placed in the actual input bar of flutter. I think this would be the best solution.

> Since you're on Linux how that works would depend on your desktop environment

This question suggests by default there isn't really one without custom extensions:


https://askubuntu.com/questions/1045915/how-to-insert-an-emoji-into-a-text-in-ubuntu-18-04-and-later

So this is a bit of a problem. Also, do on Windows people commonly know the emoji panel shortcut? All chat applications I have ever seen or used on Desktop usually have an emoji button in the input bar with an integrated emoji picker inside the app, so requiring OS special shortcuts to do this task seems quite uncommon to me. But such an integrated picker would likely require such a selector popup to be added to flutter. Should I possibly file a separate issue for that?

**Comment by stuartmorgan** [comment] 2021-01-17 15:33
> Also, do on Windows people commonly know the emoji panel shortcut?

I have no idea what fraction of users know about it.

> All chat applications I have ever seen or used on Desktop usually have an emoji button in the input bar with an integrated emoji picker inside the app, so requiring OS special shortcuts to do this task seems quite uncommon to me.

It sounds like you are arguing what the UI of the specific application you referenced should be. As neither a user nor developer of that application I have no opinion on that; I was simply pointing out that there are in fact ways to enter emoji on desktops.

> But such an integrated picker would likely require such a selector popup to be added to flutter.

An application developer could create an emoji selector, or a developer could make one as a reusable package (in fact, such packages may already exist). There's no reason it would need to be part of the framework. If you want an emoji UI element in a specific application, you should file a feature request with that application's developer.
