### ISSUE TITLE
CupertinoSliverNavigationBar  & CupertinoNavigationBar should support differing style||widget for `largeTitle` and `middle`

### ISSUE THREAD

**Issue by shamilovtim** [flutter/flutter#53788] opened 2020-04-01 22:22 UTC
Once you scroll down on CupertinoSliverNavigationBar the middle widget automatically appears -- this widget cannot be customized while simultaneously having a customized largeTitle. If you try to use a custom middle widget it will appear even while the largeTitle is active in its regular state. There's really no option to customize the middle state of the largeTitle.

Can't customize:
![image](https://user-images.githubusercontent.com/3495974/78192446-2e355000-7446-11ea-8b80-e20b351ffbe1.png)

Can customize:
![image](https://user-images.githubusercontent.com/3495974/78192476-3d1c0280-7446-11ea-8316-ec7f783c2084.png)

Right now both have to change together. Ideally you could set a different font weight, or even a different widget when the large title is gone.

**Comment by jackie099** [comment] 2020-05-21 17:58
That will be nice to have. Also, CupertinoSliverNavigationBar needs a slight visual update to match what it looks on iOS13.

**Comment by shamilovtim** [comment] 2020-10-30 18:32
> Can't you supply a middle and a largeTitle widget separately with whatever customization you need?

No you cant if you use the 'middle' widget it unceremoniously appears while the largeTitle is active (which according to the docs isn't a bug, but I don't understand why that's not a bug). 

> I imagine this is the main ask? Add a shouldTheMiddleWidgetYouSuppliedFadeAwayWhenTheLargeTitleAppears type flag?

Yes that would be one way of solving this issue

> I think that's true. Maybe so by design since the font are different. Perhaps you're asking for a way to force some subset of the styling (excluding font size, letter spacing etc) to be the same via a single inherited widget? Unless this is a big impediment, I'd consider this a low-prio ask since the fonts are indeed different by design.

No I'm specifically asking that there be an option for them to be considered separate widgets. Consider this: for whatever reason a dev wants them to be two different colors, typefaces, weighs, etc. in the middle state or the large state. It's not about stopping/enforcing inheritance, it's about allowing two separate styles.

**Comment by hacnguyen1412** [comment] 2020-11-10 14:07
i have same isssue :v

**Comment by GabRoyer** [comment] 2021-03-15 23:16
> No you cant if you use the 'middle' widget it unceremoniously appears while the largeTitle is active (which according to the docs isn't a bug, but I don't understand why that's not a bug).

I'm surprised that this isn't a bug. From the docs: 

> For advanced uses, an optional middle widget can be supplied to show a different widget in the middle of the navigation bar when the sliver is collapsed.

This to me implies that the middle widget _wouldn't_ show up when the sliver is _not_ collapsed.

**Comment by kstam** [comment] 2021-06-19 05:56
The bug seems to be here btw. I wonder if this is a parameter that should be passed into the Cupertino header instead of the current logic. Changing this line to `false` makes the header behave as per the description. 
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/nav_bar.dart#L716

**Comment by subzero911** [comment] 2022-01-27 08:37
I have the similar issue.
If I supply just Text widget as a largeTitle, everything works okay: large title and small middle text on scroll.
But if I style it, both largeTitle and middle share the same style. And large middle text looks ugly.

**Comment by SimonHausdorf** [comment] 2022-03-12 10:29
Is someone willing to make a PR for this?

**Comment by victorsanni** [comment] 2024-09-27 22:56
Hi @shamilovtim @SimonVillage is this still an issue? I'm able to customize the `largeTitle` and `middle` properties separately in CupertinoSliverNavigationBar with the flag `alwaysShowMiddle` set to false.

![ezgif com-video-to-gif-converter (9)](https://github.com/user-attachments/assets/a4bdfbeb-2555-4ff6-b6f8-d13cdc2d226a)

**Comment by victorsanni** [comment] 2024-10-12 16:04
Closing as duplicate of https://github.com/flutter/flutter/issues/113542.

**Closed by victorsanni** 2024-10-12 16:04 UTC
Labels: framework, f: cupertino, c: proposal, P3, workaround available, team-design, triaged-design
