### ISSUE TITLE
Permission denied when creating Xcode directory

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#137342] opened 2023-10-26 16:15 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

Devicelab

### What is happening?

Some (if not all) of mac devicelab bots have permission denied when trying to create a directory in `/opt/flutter`.

For example, when installing Xcode, we download the Xcode app into `/opt/flutter/xcode`, however, if the `xcode` directory does not exist yet, it is created with `mkdir`. However, this fails due to file permissions.
```
mkdir /opt/flutter/xcode: permission denied
```
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/471486/overview

Either we need to update permission allowance or the `xcode` directory needs to be created manually when bots are set up.

Note: the `xcode` directory has the owner of `swarming` currently, which allows directories to be created inside of it

### Steps to reproduce

ssh into a bot and do

```
mkdir /opt/flutter/xcode
```

### Expected results

Directory gets created or is already there

**Comment by keyonghan** [comment] 2023-10-26 16:22
@kentnguyen99 Could you help run below command to unblock?
```
sudo mkdir -p /opt/flutter/xcode && sudo chown -R swarming /opt/flutter/xcode
```

@yusuf-goog Does this sound a good fit to add to salt for make sure the folder exists with correct permission?

**Comment by vashworth** [comment] 2023-10-26 16:34
I already did it manually for mac-1

**Comment by yusuf-goog** [comment] 2023-10-26 16:48
@keyonghan we should probably chown at /opt/flutter:

`sudo mkdir -p /opt/flutter/xcode && sudo chown -R swarming /opt/flutter`

**Comment by yusuf-goog** [comment] 2023-10-26 17:00
https://dash-internal-review.git.corp.google.com/c/salt/+/1920 is potential fix in salt to setup the directories.

**Comment by yusuf-goog** [comment] 2023-10-26 19:47
Ran potential fix on mac-45. @vashworth can you confirm if the issue is resolved on that machine?

**Comment by vashworth** [comment] 2023-11-07 21:34
Looks like https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-11 needs to have it's permissions updated, as well

**Comment by yusuf-goog** [comment] 2023-11-07 21:43
fixed permissions on mac-11

**Comment by keyonghan** [comment] 2023-12-13 22:29
This should have been resolved.

**Comment by vashworth** [comment] 2023-12-13 22:55
@keyonghan & @yusuf-goog  Looks like https://dash-internal-review.git.corp.google.com/c/salt/+/1920 never got merged in?

**Comment by keyonghan** [comment] 2023-12-14 17:12
Confirmed with @yusuf-goog all bots have been with correct permission now. We may still need to make sure these configs auto handled by salt for potential future cases like OS upgrade, etc? Just in case, reopening, but lowing priority to P2.

**Comment by vashworth** [comment] 2023-12-14 17:35
> We may still need to make sure these configs auto handled by salt for potential future cases like OS upgrade, etc?

Yeah we handled it manually for the upgrade so far, but I think it's important to have it automated as it could get forgotten next upgrade or if we get new bots

**Comment by yusuf-goog** [comment] 2023-12-14 19:22
https://dash-internal-review.git.corp.google.com/c/salt/+/1920  is submitted. This should run on new mac setups, and is available for us to run manually if ever the case arise. 

@vashworth let me know if theres anything else, if not , you can go ahead and close this

**Closed** 2023-12-14 19:26 UTC
Labels: team-infra, P2, infra: device lab, triaged-infra
