### ISSUE TITLE
autofocus on TextFormField widgets causes keyboard to show and hide rapidly

### ISSUE THREAD

**Issue by vladaman** [flutter/flutter#18846] opened 2018-06-26 19:20 UTC
Following widget causes keyboard to be rapidly shown and hidden. Notice autofocus: true - when set to false the issue is gone. No other widget has autofocus set.

```dart
return TextFormField(
      keyboardType: TextInputType.emailAddress,
      autofocus: true,
      // inputFormatters: <TextInputFormatter>[new UpperCaseTextFormatter()],
      maxLength: 40,
      validator: (value) {
        if (value.isEmpty) {
          return "Missing data";
        }
      },
      decoration: InputDecoration(
        hintText: 'me@aaa.com',
        labelText: 'Email',
        contentPadding: EdgeInsets.fromLTRB(16.0, 10.0, 2.0, 20.0),
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(0.0)),
      ),
    );
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.23.1)
[✓] Connected devices (1 available)
```

![ezgif-3-1c25884eb5](https://user-images.githubusercontent.com/907206/41934157-41b9c8b6-7986-11e8-81f9-3758c4adfc58.gif)

**Comment by vladaman** [comment] 2018-07-12 19:32
Is there at least some workaround this issue until fixed?

**Comment by BondarenkoStas** [comment] 2019-10-24 14:33
@vladaman I just tried it with v1.9.1+hotfix.5 on both android and ios, couldn't reproduce. I think the issue is gone, closing it. Please correct me if I'm wrong.

**Closed by BondarenkoStas** 2019-10-24 14:33 UTC
Labels: a: text input, framework
