### ISSUE TITLE
AppBarTheme iconTheme color is not working when useMaterial3

### ISSUE THREAD

**Issue by rddewan** [flutter/flutter#112379] opened 2022-09-26 11:46 UTC
when useMaterial3 is enabled `iconTheme: const IconThemeData( color: Colors.white, ),   ` do not take effect

```
theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.green,
        appBarTheme:  AppBarTheme(
          color: Colors.green,
          iconTheme: const IconThemeData(
            color: Colors.white,
          ),          
          titleTextStyle: Theme.of(context).textTheme.headline6?.copyWith(
            color: Colors.white,
          ),
          systemOverlayStyle: const SystemUiOverlayStyle(
            systemNavigationBarColor: Colors.greenAccent,
            systemNavigationBarIconBrightness: Brightness.dark,
            statusBarIconBrightness: Brightness.light, // For Android
            statusBarBrightness: Brightness.dark,        
          ),
        ),
        bottomNavigationBarTheme: BottomNavigationBarThemeData(
          backgroundColor: Colors.grey[200],
          type: BottomNavigationBarType.shifting,
        ),
      ),
```
Flutter Doctor
```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2022-09-26 12:49
Hi @rddewan, I believe this is a duplicate of https://github.com/flutter/flutter/issues/110878.

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-09-26 12:49 UTC
Labels: in triage
