### ISSUE TITLE
Divide main.dart.js into main.dart.mini.js + project.js

### ISSUE THREAD

**Issue by UsherBaby** [flutter/flutter#99692] opened 2022-03-07 16:26 UTC
Flutter web first loading is too slow for the big size of main.dart.js. Why not divide main.dart.js into main.dart.mini.js + project.js. Main.dart.mini.js only contains the flutter framework basic code, NOT changed at build time. And the project.js comains the app codes. Please consider the cocos-js solution!

**Comment by maheshmnj** [comment] 2022-03-08 08:09
Hi @UsherBaby, Thanks for filing the issue. There is already a feature request being tracked to make the Web app's first load faster https://github.com/flutter/flutter/issues/76009, Regarding your proposal which is more of a question, I would suggest you please continue the discussion on that thread.

Closing as the duplicate of the linked issue. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-03-08 08:09 UTC
Labels: in triage
