### ISSUE TITLE
error flutter firestore 0.12.9

### ISSUE THREAD

**Issue by orgio** [flutter/flutter#37657] opened 2019-08-06 02:56 UTC
![error](https://user-images.githubusercontent.com/27058809/62508017-c1c36c00-b838-11e9-86d3-ea8a5ba1e7c5.PNG)

**Comment by atos93** [comment] 2019-08-06 09:27
Just switch to AndroidX -> https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by orgio** [comment] 2019-08-06 09:45
Thank you so much for sending email to me And i used androidx but does not help maybe i missed something

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 6, 2019 at 5:29 PM, Emanuele Deriu<notifications@github.com> wrote:   
Just switch to AndroidX -> https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by iapicca** [comment] 2020-01-16 11:21
Hi @orgio 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-16 11:21 UTC
Labels: ▣ platform-android
