### ISSUE TITLE
There is a strange dividing line between two containers

### ISSUE THREAD

**Issue by 1663049254** [flutter/flutter#95725] opened 2021-12-23 10:33 UTC
This problem only occurs on Android
However, it is strange that the results will be different when the container is set to different heights

Here is the code

<summary>
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: MyPage()));
}

class MyPage extends StatefulWidget {
  MyPage({Key? key}) : super(key: key);

  @override
  _MyPageState createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            body: Center(
      child: TextButton(
          onPressed: () {
            showDialog(
                context: context,
                builder: (context) {
                  return _renderDialog();
                });
          },
          child: Text('test')),
    )));
  }

  _renderDialog() {
    return Container(
      alignment: Alignment.center,
      child: Container(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 300,
              height: 300,
              color: Colors.white,
            ),
            Container(
              width: 300,
              height: 99, //If you write 99 here, there will be a dividing line, but 100 doesn't?
              color: Colors.white,
            ),
          ],
        ),
      ),
    );
  }
}
</summary>

**Comment by nt4f04uNd** [comment] 2021-12-23 12:02
Sounds like a duplicate of https://github.com/flutter/flutter/issues/14288

**Closed by nt4f04uNd** 2021-12-23 12:02 UTC
