### ISSUE TITLE
Keyboard Issue with webview_flutter 1.0.1

### ISSUE THREAD

**Issue by rampal** [flutter/flutter#68018] opened 2020-10-13 12:19 UTC
Earlier we were using 0.3.22 version and everything was working fine on IOS and ANDROID.
After upgrading to flutter 1.22.0 seeing the keyboard issue. With flutter 1.22.0 we updated webview_flutter 1.0.1

Issue: on focussing text field when keyboard appears the whole page gets refresh and this causes a lot of issue for us.
Its happening in both IOS and NAdroid.

Appreciate if you could look it urgent basis and provide some guidance.

Thanks,
Rampal

**Comment by rampal** [comment] 2020-10-14 03:52
@pedromassangocode  any update on this?

**Comment by pedromassangocode** [comment] 2020-10-14 09:15
Able to reproduce on `master` channel.

<img width="240" height="500" src="https://user-images.githubusercontent.com/67424416/95964060-5263e780-0e00-11eb-9e36-fd439ed72143.gif">

<details><summary>Complete code sample</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:webview_flutter/platform_interface.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: WebViewExample()));

class WebViewExample extends StatefulWidget {
  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
      ),
      body: CustomWebView(),
    );
  }

}

class CustomWebView extends StatelessWidget {
  final Completer<WebViewController> _controllerCompleter =
      Completer<WebViewController>();
  WebViewController _webViewController;

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Builder(builder: (BuildContext context) {
        _controllerCompleter.future
            .then((WebViewController webViewController) async {
          //Get headers
          _webViewController = webViewController;
          _webViewController
              .loadUrl('https://github.com/flutter/flutter/issues');
        });
        return WebView(
            key: GlobalKey(),
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (WebViewController webViewController) async {
              _controllerCompleter.complete(webViewController);
              webViewController.clearCache();
              final CookieManager cookieManager = CookieManager();
              await cookieManager.clearCookies();
            },
            javascriptChannels: <JavascriptChannel>[
              JavascriptChannel(
                name: 'flutter',
                onMessageReceived: (JavascriptMessage message) {
                  //TODO
                },
              )
            ].toSet(),
            navigationDelegate: (NavigationRequest request) async {
              NavigationDecision decision = NavigationDecision.prevent;
              decision = await Future<NavigationDecision>.delayed(
                  const Duration(milliseconds: 10),
                  () => NavigationDecision.navigate);
              return decision;
            },
            onPageStarted: (String paramVal) {
              //Page Started
            },
            onPageFinished: (String paramVal) async {
              //Page Finished
            },
            onWebResourceError: (WebResourceError error) async {
              //Map<String, String> cookies = await _getCookiesFromWebView();
              //Log error
            });
      }),
    );
  }
}

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en)
    • Flutter version 1.23.0-18.0.pre at /Users/pedromassango/dev/SDKs/flutter_dev
    • Framework revision 37ebe3d82a (15 hours ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.80

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by sachindeorah** [comment] 2020-10-14 14:03
We are also facing the same issue. @pedromassangocode Did we find any solution for this?

**Comment by hifron** [comment] 2020-10-15 15:38
According [WebView doc](https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebView-class.html) method onPageStarted is invoked when page STARTS LOADING. Method onWebViewCreated is invoked once the web view IS CREATED. When keyboard shows, then view is probably recreated and with clearing its repainted altough is already completed rendering...

**Comment by pedromassangocode** [comment] 2020-10-16 06:52
Hi @sachindeorah 
Not yet, you can subscribe into this issue to get notified once this get fixed!

**Comment by blasten** [comment] 2020-10-19 22:45
I was able to reproduce this issue if I use the Android emulator. I was unable to reproduce it on a physical device running the same OS version (Android 10/ API level 29).

This issue can be fixed by using hybrid composition: ` WebView.platform = SurfaceAndroidWebView();`

https://github.com/flutter/plugins/blob/master/packages/webview_flutter/README.md#using-hybrid-composition

**Closed by blasten** 2020-10-19 22:45 UTC
Labels: found in release: 1.23, has reproducible steps, p: first party, p: webview, p: webview-keyboard, platform-android, plugin

**Comment by 94wogus** [comment] 2021-08-06 11:24
same problem
Did we have any solution for this issue?
