### ISSUE TITLE
Error thrown when disposing page with enddrawer opened

### ISSUE THREAD

**Issue by Xgamefactory** [flutter/flutter#38849] opened 2019-08-19 22:01 UTC
We have second page with endDrawer while drawer is opened switching back to main page throws this error on console.
has 
` final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();`
in Statefullwidget state

here is the build method with scaffold and enddrawer
 ```
@override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: _willPopCallback,
      child: Scaffold(
        key: _scaffoldKey,
        backgroundColor: AppConfig.backgroundColor,
        endDrawer: _buildFilterDrawer(context),
```

```
setState() or markNeedsBuild() called during build.
I/flutter ( 6041): This Scaffold widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
I/flutter ( 6041): The widget on which setState() or markNeedsBuild() was called was:
I/flutter ( 6041):   Scaffold-[LabeledGlobalKey<ScaffoldState>#0a5bd]
I/flutter ( 6041): The widget which was currently being built when the offending call was made was:
I/flutter ( 6041):   WillPopScope
I/flutter ( 6041): #0      Element.markNeedsBuild.<anonymous closure> 
package:flutter/…/widgets/framework.dart:3670
I/flutter ( 6041): #1      Element.markNeedsBuild 
package:flutter/…/widgets/framework.dart:3685
I/flutter ( 6041): #2      State.setState 
package:flutter/…/widgets/framework.dart:1161
I/flutter ( 6041): #3      ScaffoldSt
I/flutter ( 6041): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
I/flutter ( 6041): The following assertion was thrown building
I/flutter ( 6041): WillPopScope(dependencies: [_ModalScopeStatus], state:
I/flutter ( 6041): _WillPopScopeState#06d91):
I/flutter ( 6041): setState() or markNeedsBuild() called during build.
I/flutter ( 6041): This Scaffold widget cannot be marked as needing to build because
I/flutter ( 6041): the framework is already in the process of building widgets.  A
I/flutter ( 6041): widget can be marked as needing to be built during the build
I/flutter ( 6041): phase only if one of its ancestors is currently building. This
I/flutter ( 6041): exception is allowed because the framework builds parent widgets
I/flutter ( 6041): before children, which means a dirty descendant will always be
I/flutter ( 6041): built. Otherwise, the framework might not visit this widget
I/flutter ( 6041): during this build phase.
I/flutter ( 6041): The widget on which setState() or markNeedsBuild() was called
I/flutter ( 6041): was:
I/flutter ( 6041):   Scaffold-[LabeledGlobalKey<ScaffoldState>#0a5bd]
I/flutter ( 6041): The widget which was currently being built when the offending
I/flutter ( 6041): call was made was:
I/flutter ( 6041):   WillPopScope
```

**Comment by Victory886** [comment] 2019-08-21 01:04
final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();
 Scaffold --- key: _scaffoldKey 
只要添加了这个，右侧抽屉是可以正常显示和消失，但是使用文本框的时候键盘显示一下就下去，无法正常输入内容。

**Comment by Xgamefactory** [comment] 2019-09-11 23:18
scaffoldkey without ScaffoldState i will try thanks.

**Comment by Xgamefactory** [comment] 2019-09-12 07:25
without ScaffoldState its impossible to dismiss drawer when page is dismissed

```
@override
  void dispose() {
    // Navigator.of(context).pop();
    _scrollController?.dispose();
    if (_scaffoldKey.currentState.isEndDrawerOpen) {
    Navigator.of(context).pop();
    }
    // bloc?.dispose();
    super.dispose();
  }
```

**Comment by Xgamefactory** [comment] 2019-09-12 07:45
same error
```

════════ Exception Caught By animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3641 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      Element.markNeedsBuild 
package:flutter/…/widgets/framework.dart:3641
#3      State.setState 
package:flutter/…/widgets/framework.dart:1161
#4      DrawerControllerState._animationChanged 
package:flutter/…/material/drawer.dart:263
#5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners 
package:flutter/…/animation/listener_helpers.dart:124
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3641 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      Element.markNeedsBuild 
package:flutter/…/widgets/framework.dart:3641
#3      State.setState 
package:flutter/…/widgets/framework.dart:1161
#4      DrawerControllerState._animationChanged 
package:flutter/…/material/drawer.dart:263
#5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners 
package:flutter/…/animation/listener_helpers.dart:124
#6      AnimationController._tick 
package:flutter/…/animation/animation_controller.dart:768
...
The AnimationController notifying listeners was: AnimationController#79e72(⏮ 0.000; paused)
```

**Comment by Xgamefactory** [comment] 2020-04-11 15:53
still no fix or response from dev team :)

**Comment by TahaTesser** [comment] 2020-07-01 13:57
Hi @Xgamefactory 
<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          Navigator.push(context, MaterialPageRoute(builder: (_) => Second()));
        },
      ),
    );
  }
}

class Second extends StatelessWidget {
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        return Future.value(true);
      },
      child: Scaffold(
        endDrawer: Drawer(
          child: Center(
            child: RaisedButton(
                child: Text('Close'),
                onPressed: () {
                  Navigator.pop(context);
                }),
          ),
        ),
        key: _scaffoldKey,
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.add),
          onPressed: () {},
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (8 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F      • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos            • darwin-x64     • Mac OS X 10.15.5
      19F101
    • Web Server    • web-server       • web-javascript • Flutter Tools
    • Chrome        • chrome           • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
``` 

</details> 

Not able to reproduce this issue, if you're still experiencing this issue with latest stable
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-07-29 11:31
Closing as fixed,
@Xgamefactory comment if you disagree and I'll reopen

**Closed by VladyslavBondarenko** 2020-07-29 11:31 UTC
Labels: f: material design, framework, waiting for customer response
