### ISSUE TITLE
[Web] Combine Positioned with Draggable (with button as child) throws when dragging

### ISSUE THREAD

**Issue by tcd93** [flutter/flutter#72256] opened 2020-12-14 05:18 UTC
## Description
When on web, a Draggable or LongPressDraggable with a child containing an onTap() method will throw an exception and fail to update when starting to drag. 

Similar to #69774, the only difference is that the **Draggable is under a Positioned widget**

## Steps to Reproduce

Example code on [DartPad](https://dartpad.dev/4038412fce163ac9eb59a269cbf95faf)
```
  Widget build(BuildContext context) {
    final fab = FloatingActionButton(
        onPressed: () {}); // works if switch to a widget without onTap/onPress...

    return MaterialApp(
      home: Stack(
        children: [
          Container(key: overlayCtnKey),
          DraggableWidget(containerKey: overlayCtnKey, child: fab),
        ],
      ),
    );
  }
```
To reproduce the bug when on Web, drag & drop the FloatingActionButton to a new position on screen

**Expected results:** The Draggable's new position should be updated

**Actual results:** The Draggable crashes. In the console, exceptions are thrown:

<details>
  <summary>Logs</summary>

```
Error: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
                    Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
```

```
Error: Assertion failed: file:///C:/Users/jaden.tang/sdk/flutter/packages/flutter/lib/src/rendering/mouse_tracking.dart:301:12
           !_debugDuringDeviceUpdate is not true
```

```
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.52.0)
[√] Connected device (3 available)
```

</details>

*When on Android emulator, the dragging behaves as expected.*

**Comment by TahaTesser** [comment] 2020-12-14 13:37
Hi @tcd93 
Thanks for filing the issue, I can reproduce the issue on `beta`, However, it seems to be fixed in the `dev` and `master` channel 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final overlayCtnKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    final fab = FloatingActionButton(
        onPressed:
            () {}); // works if switch to a widget without onTap/onPress...

    return MaterialApp(
      home: Stack(
        children: [
          Container(key: overlayCtnKey),
          DraggableWidget(containerKey: overlayCtnKey, child: fab),
        ],
      ),
    );
  }
}

class DraggableWidget extends StatefulWidget {
  final Widget child;

  final GlobalKey containerKey;

  DraggableWidget({@required this.child, @required this.containerKey});

  @override
  DraggableWidgetState createState() => DraggableWidgetState();
}

class DraggableWidgetState extends State<DraggableWidget> {
  double top, left;

  @override
  void initState() {
    top = 50;
    left = 50;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final RenderBox backgroundRenderBox =
        widget.containerKey.currentContext.findRenderObject();
    return Positioned(
      top: top,
      left: left,
      child: Draggable(
        dragAnchor: DragAnchor.child,
        feedback: widget.child,
        child: widget.child,
        childWhenDragging: const SizedBox(),
        onDragEnd: (drag) {
          final localOffset = backgroundRenderBox.globalToLocal(drag.offset);
          setState(() {
            top = localOffset.dy;
            left = localOffset.dx;
          });
        },
      ),
    );
  }
}

``` 

### Issue exist
</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64,
    locale en-GB)
    • Flutter version 1.24.0-10.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.2
    • iPhone 12 (mobile)   • 2188C52E-1D22-45B2-98B8-48401D2B6716 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Web Server (web)     • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

### No issue on version below

<details> 
<summary>multiple flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on macOS 11.0.1 20B29 darwin-x64,
    locale en-GB)
    • Flutter version 1.25.0-8.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision a12e2a473a (5 days ago), 2020-12-08 23:13:04 -0500
    • Engine revision df39e5c515
    • Dart version 2.12.0 (build 2.12.0-133.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.2
    • iPhone 12 (mobile)   • 2188C52E-1D22-45B2-98B8-48401D2B6716 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64
      • macOS 11.0.1 20B29 darwin-x64
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 1.25.0-9.0.pre.43, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.25.0-9.0.pre.43 at /Users/tahatesser/Code/flutter_master
    • Framework revision 63062a6443 (22 hours ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.2
    • iPhone 12 (mobile)   • 2188C52E-1D22-45B2-98B8-48401D2B6716 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64
      • macOS 11.0.1 20B29 darwin-x64
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

Labelling the issue to track the fix for beta channel 

CC @pcsosinski

**Comment by ferhatb** [comment] 2020-12-17 21:40
Please see https://github.com/flutter/flutter/issues/67044 . closing this one as duplicate.

**Closed by ferhatb** 2020-12-17 21:40 UTC
Labels: found in release: 1.24, framework, has reproducible steps, platform-web
