### ISSUE TITLE
Video_player: Bad state: Future already completed

### ISSUE THREAD

**Issue by manhnt79** [flutter/flutter#29591] opened 2019-03-19 08:17 UTC
I player a video with same Url. it can play in android but I get error in iPhone with below stack trace.
Please help me resolve it.
thanks 
Bad state: Future already completed

 ------- STACK TRACE -------
      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
     VideoPlayerController.initialize.eventListener (package:video_player/video_player.dart:239:33)
      _rootRunUnary (dart:async/zone.dart:1132:38)
     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
      _rootRun (dart:async/zone.dart:1120:38)
     _CustomZone.run (dart:async/zone.dart:1021:19)
   _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    _rootRun (dart:async/zone.dart:1124:13)
   _CustomZone.run (dart:async/zone.dart:1021:19)
     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by jonahwilliams** [comment] 2019-03-19 17:10
Hi @manhnt79 , we don't really have enough information here to help you. Please include the output of `flutter doctor -v`, the version of the video player plugin you are using, and if possible a small sample that reproduces the issue.

**Comment by jonasbark** [comment] 2019-03-22 12:12
https://github.com/flutter/plugins/pull/1174 contains a fix for this

**Comment by manhnt79** [comment] 2019-03-28 09:12
Here are more information for my issue.
macs-MacBook-Air:addins mac$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.2.1 at /Users/mac/Downloads/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0.beta.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • Android SDK built for x86 64 • emulator-5554                            • android-x64 •
      Android 9 (API 28) (emulator)
    • iPhone của Tomo              • 074eed5de8d693db88b1bd34ab795a970c322df5 • ios         • iOS
      12.1.2

**Comment by palbert75** [comment] 2019-03-29 19:36
I have the same problem, it looks like the video controller gets the initialized event 2 times, and tries to complete the initializingCompleter a second time

**Comment by anasiqbal** [comment] 2019-04-15 09:57
I have the same problem. I am trying to show multiple videos in a list view. I am only getting this error on iOS.

**Comment by cbenhagen** [comment] 2019-04-27 16:22
Duplicate of https://github.com/flutter/flutter/issues/19197

**Comment by iskakaushik** [comment] 2019-04-29 23:30
This should be addressed in version: `0.10.0+8` by this PR: https://github.com/flutter/plugins/pull/1552/ please re-open this if it's still an issue. Thanks!

**Closed by iskakaushik** 2019-04-29 23:30 UTC
Labels: p: video_player
