### ISSUE TITLE
Stack is changing the layout

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#27040] opened 2019-01-24 18:32 UTC
I created a loading Widget with this build method:

```dart
Widget build(BuildContext context) {
    return StreamBuilder(
      stream: loadingStream,
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          if (snapshot.data) {
            return Stack(
              children: <Widget>[child, new Center(child: busyWidget)],
            );
          } else {
            return Stack(children: <Widget>[child]);
          }
        }
        return child;
      },
    );
```
If I exchange the line:
```dart
return Stack(children: <Widget>[child]);
```
to 
```dart
return child;
```

the layout is flickers means the stack is adding margins or something else.
I think both ways it should work.

```
C:\Projects\obdchk\obdchk>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.1.6-pre.34, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] VS Code, 32-bit edition (version 1.30.1)
[√] Connected device (2 available)
```

**Comment by zoechi** [comment] 2019-01-24 18:35
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment] 2019-01-24 18:36
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment] 2019-02-18 08:11
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by ride4sun** [comment] 2019-02-18 16:59
I think the original post has enough code information to investigate.

**Comment by zoechi** [comment] 2019-02-18 17:05
We don't want to depend on assumptions how to pick together a running app to from snippets and therefore ask for minimal **runnable** reproduction.

I think this is working as intended and should be ask on support channels instead.

**Comment by ride4sun** [comment] 2019-02-18 20:11
@zoechi any change of mind?

**Closed** 2019-05-14 22:28 UTC
Labels: waiting for customer response
