### ISSUE TITLE
`ColorFiltered` widget leaves traces in PageView (only on iOS device)

### ISSUE THREAD

**Issue by DimaKutko** [flutter/flutter#105516] opened 2022-06-07 11:51 UTC
## Steps to Reproduce

1. Execute flutter run on the code sample on iOS device.
2. Open page with page viewer.
3. Scroll through the page viewer. 

**Expected results:** The page viewer leaves a trail

**Actual results:** The page viewer not leaves a trail

<details>
<summary>Code sample</summary>

[Full project](https://github.com/DimaKutko/color_stripes_in_page_viewer)

```dart 
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Color stripes in page viewer',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  PageController? pageController;
  static const links = [
    'https://image.emojisky.com/676/9577676-middle.png',
    'https://koenig-media.raywenderlich.com/uploads/2021/10/Teaching_Dash_.png',
    'https://avatars.githubusercontent.com/u/38634459?v=4',
  ];

  @override
  void initState() {
    super.initState();

    pageController = PageController(viewportFraction: 0.6);
  }

  @override
  void dispose() {
    pageController?.dispose();

    super.dispose();
  }

  Widget _buildItem(String link) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 8),
      child: ColorFiltered(
        colorFilter: ColorFilter.mode(
          Colors.black.withOpacity(0.8),
          BlendMode.darken,
        ),
        child: SizedBox(
          height: 150,
          child: Image.network(link),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Color stripes in page viewer')),
      backgroundColor: Colors.teal,
      body: Center(
        child: PageView.builder(
          itemCount: links.length,
          controller: pageController,
          itemBuilder: (_, i) => _buildItem(links[i]),
        ),
      ),
    );
  }
}

```
</details>

<details>
  <summary>Logs</summary>

```
MacBook-DimaKutko:color_stripes_in_page_viewer dimakutko$ flutter analyze
Analyzing color_stripes_in_page_viewer...                               
No issues found! (ran in 1.3s)
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-UA)
    • Flutter version 3.0.1 at /Users/DimaKutko/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/dimakutko/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone (Dima Kut’ko) (mobile) • ********************* • ios            • iOS 15.5 19F77
    • macOS (desktop)               • macos                     • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                  • chrome                    • web-javascript • Google Chrome 102.0.5005.61
    ! Error: iPhone (Dima Kut’ko) is busy: Preparing the watch for development via iPhone (Dima Kut’ko). Xcode will continue when iPhone (Dima Kut’ko) is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Screencast:

https://user-images.githubusercontent.com/56451967/172370764-70524296-0fa0-4ad2-abff-2d3fc9f86c70.MP4

**Comment by danagbemava-nc** [comment] 2022-06-07 13:36
Issue is reproducible on `stable` and `master` only on `iOS`.

<details>
<summary>videos</summary>

| android | ios | ios- no ColorFiltered | cycling through blend modes| 
| -- | -- | -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/172393558-b9852f47-810b-438f-8177-2a39a864ab1f.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/172393624-f3011305-7895-4301-a494-d0e03326a72e.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/172393705-b33c6972-d4cf-49ed-aa7b-f0706810a6d8.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/172393796-0f0ab90a-f873-41a6-a6bc-fe1fa30f3e3f.mp4" /> |


</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Color stripes in page viewer',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  PageController? pageController;
  static const links = [
    'https://image.emojisky.com/676/9577676-middle.png',
    'https://koenig-media.raywenderlich.com/uploads/2021/10/Teaching_Dash_.png',
    'https://avatars.githubusercontent.com/u/38634459?v=4',
  ];

  BlendMode _mode = BlendMode.clear;

  @override
  void initState() {
    super.initState();

    pageController = PageController(viewportFraction: 0.6);
  }

  @override
  void dispose() {
    pageController?.dispose();

    super.dispose();
  }

  void _changeBlendMode() {
    const mode = BlendMode.values;

    setState(() {
      _mode = mode[(_mode.index + 1) % mode.length];
    });
  }

  Widget _buildItem(String link) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 8),
      child: ColorFiltered(
        colorFilter: ColorFilter.mode(
          Colors.black.withOpacity(0.8),
          _mode,
        ),
        child: SizedBox(
          height: 150,
          child: Image.network(link),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Color stripes in page viewer')),
      backgroundColor: Colors.teal,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('mode: $_mode'),
            Expanded(
              child: PageView.builder(
                itemCount: links.length,
                controller: pageController,
                itemBuilder: (_, i) => _buildItem(links[i]),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _changeBlendMode,
        child: const Icon(Icons.swap_calls),
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.0.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 15.5 19F77
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 102.0.5005.61

[!] HTTP Host Availability
    ✗ HTTP host "https://cloud.google.com/" is not reachable. Reason: Failed to connect to host in 10 seconds

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1139, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1139 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ab56de808 (65 minutes ago), 2022-06-07 02:18:05 -0400
    • Engine revision 5797ecf2fb
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 15.5 19F77
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by chinmaygarde** [comment] 2022-06-13 17:58
Closing as duplicate of https://github.com/flutter/flutter/issues/105674

**Closed by chinmaygarde** 2022-06-13 17:58 UTC
Labels: platform-ios, engine, severe: rendering, has reproducible steps, found in release: 3.0, found in release: 3.1
