### ISSUE TITLE
simple_animation_perf is acting strange on iPhone XS

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#43452] opened 2019-10-24 21:43 UTC
simple_animation_perf_iphonexs is showing weird behavior, where it sometimes uses 3ms, sometimes 17ms, and sometimes 33ms. This suggests there's something wrong with either the benchmark or something in our code.

cc @liyuqian 

![DeepinScreenshot_select-area_20191024144121](https://user-images.githubusercontent.com/551196/67527664-6309d380-f66c-11e9-9c46-c92a56bc6eae.png)

For example, consider the 90th percentile rasterizer time specifically:

![DeepinScreenshot_select-area_20191024144232](https://user-images.githubusercontent.com/551196/67527724-8af93700-f66c-11e9-9da5-f7475bff523c.png)

Understanding the behaviour here could be key to some performance improvements.

**Comment by Hixie** [comment] 2019-10-24 22:23
(Note: I've rebaselined the graphs so that they appear green, but this does not mean that this issue was in any way resolved. It just makes it easier to catch additional problems.)

**Comment by liyuqian** [comment] 2019-10-24 22:27
@flar has done some research on why Flutter can sometimes take 16ms to rasterize a simple frame during his study on https://github.com/flutter/flutter/issues/31865 . IIRC, the iOS scheduling is the issue. Jim: can you share more insights of this specific issue?

@digiter @godofredoc  : the regression seems to start after the device lab is migrated. Have you upgraded the iOS version of that iPhone Xs during the migration? I believe @chinmaygarde was suggesting to do that to avoid future system update notifications. However, the upgraded iOS may change the behavior of that test.

BTW, [similar effects](https://medium.com/flutter/performance-testing-of-flutter-apps-df7669bb7df7) where frame time increases when the complexity actually decreases are also found on Android by @filiph . I'm going to ask how our sister device labs lock the CPU/GPU scaling on iOS.

**Comment by digiter** [comment] 2019-10-24 23:05
IIRC, the iPhone Xs was not working with Xcode 10.3, then we changed the phone to iPhone 6.

**Comment by flar** [comment] 2019-10-24 23:11
We still don't know why iOS occasionally locks us in an OpenGL call until the next Vsync, but it does happen. The main drawback is that we lose a little bit of self-determination. It doesn't seem to affect our energy usage but we can't do anything else while we are stuck there. Since we can't dispatch a new frame until we are done with the old frame, we'd have to wait anyway, but the difference would be that we could potentially do "other things" while we wait unlike if we're stuck in a kernel wait. Currently we have no "other things" identified that we could do, though, so this is a theoretical limitation.

There are a couple of compounding factors, though...

If we ever run into this wait condition, then our current setting for the frame queue depth of 2 means we will immediately try to render the next frame as soon as we come out of the wait state and finish the old frame - and then we end up back in the wait condition on that next frame as well nearly 100% of the time. This means we "lock in" the wait condition when it happens. If we lower the queue depth to 1, then we will not "render ahead" any more and we don't end up "locking it in" any more. The side effect of lowering the queue depth is that we would no longer "render ahead" when we miss one frame time by a slim margin. So, we could potentially reduce this to "occasionally we miss a frame, but recover" at the expense of "render ahead". Also, we do eventually recover from the "locked in" state - at some point the system will have something else happen to it that interrupts our flow (some sort of system-wide task wakes up or something?) and then we have a good chance of coming out of that "lock-in" state - only to eventually re-enter it at another random time.

If we don't use the off-screen layer on iOS then we end up triggering the wait a lot less often, but it still happens, and we still get "locked in" if the queue depth is 2. So, this is not a real solution for this particular problem, it would just hide it more often.

So far this has just been an anomaly in our Observatory traces in trying to diagnose energy usage, but if this is showing up in making the benchmarks less reliable then that would be a good reason to follow up with Apple on why this happens. Note that this is a commonly asked question on the net about apps getting stuck in wait conditions in GL calls and there are no public answers from Apple. When we asked Skia about it, they pointed us at some of those threads as in "this is a common issue".

**Comment by liyuqian** [comment] 2019-10-26 20:52
Thank you Jim for the very detailed explanation! Loop in our iOS experts @gaaclarke @gw280 @chinmaygarde

**Comment by liyuqian** [comment] 2020-10-09 22:14
We've migrated to Metal and removed iPhone XS from the device lab. Hence I'm closing this issue.

**Closed by liyuqian** 2020-10-09 22:14 UTC
Labels: P4, e: device-specific, engine, platform-ios, severe: performance
