### ISSUE TITLE
Flutter run - is not work

### ISSUE THREAD

**Issue by OfficialSameer** [flutter/flutter#23522] opened 2018-10-25 17:50 UTC
![error](https://user-images.githubusercontent.com/41697881/47519901-52354f00-d8ac-11e8-9bc6-9d7620d2cae4.PNG)

**Comment by her0satr** [comment] 2018-10-26 01:58
This issue exist for fresh install flutter

**Comment by her0satr** [comment] 2018-10-26 02:03
I am already update my build.gradle repository like this : 

    repositories {
        maven { url 'https://maven.fabric.io/public' }
        mavenCentral()
        jcenter()
        google()
    }

**Comment by hariprasadiit** [comment] 2018-10-26 22:49
duplicate of #23404

**Comment by zoechi** [comment] 2018-10-27 07:50
Thanks @hariprasadiit 
Merging with #23404

**Closed by zoechi** 2018-10-27 07:50 UTC
