### ISSUE TITLE
[regression] TextFormField has a white (invisible) text color on latest master

### ISSUE THREAD

**Issue by pedromassangocode** [flutter/flutter#73314] opened 2021-01-05 10:55 UTC
Found a regression in the text form field's default text color, on latest master the default text color is white (aka invisible) while on latest stable it is black. Found while creating https://github.com/flutter/flutter/issues/73309.

## Steps to reproduce

1. Run the code bellow

```dart
import 'package:flutter/material.dart';

void main() => runApp(
    MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: TextFormField(
            initialValue: "Hello",
          ),
        ),
      ),
    ),
  );
```

**Expected Results:** a text field with black text color
**Actual Results:** a text field with a invisible text (the text is there but has a white color)

Note: if you type any text in the field the color of the text will turn black.

|master channel|stable channel
|-|-|
|![Screen Shot 2021-01-05 at 11 48 23](https://user-images.githubusercontent.com/67424416/103638004-9a506180-4f4c-11eb-974d-0b9a92cf914b.png)|![Screen Shot 2021-01-05 at 11 45 22](https://user-images.githubusercontent.com/67424416/103638024-a0464280-4f4c-11eb-87bb-17835e2546b5.png)|

# Critical
This issue seems to be happening with all theme properties and is affecting all widgets that uses display any text in the app. Seems to be an inheritance theme issue which was introduced by https://github.com/flutter/flutter/pull/69050 that may be causing this.

<details><summary>flutter doctor -v</summary>

```
/Users/pedromassango/dev/SDKs/flutter_master/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 1.26.0-2.0.pre.177, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.177 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 7c26c8fbb1 (4 hours ago), 2021-01-05 01:19:03 -0500
    • Engine revision b9dc0cf1d8
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by pedromassangocode** [comment] 2021-01-05 12:28
Another code sample that showcase the bug in other widgets. Running the code bellow (don't hot-reload/restart) all texts will be invisible, if you type anything in the text fields they all will appear.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Testing',
        home: Scaffold(
          body: Padding(
            padding: const EdgeInsets.all(32),
            child: Column(
              children: [
                Text('Helllo'),
                RaisedButton(child: Text('Button'), onPressed: () {},),
                FlatButton(child: Text('Button'), onPressed: () {},),
                TextField(controller: TextEditingController(text: 'Text Field'),),
                TextFormField(initialValue: 'Text Form Field',)
              ],
            ),
          ),
        ),
    );
  }
}


```

**Comment by darshankawar** [comment] 2021-01-05 13:14
Verified and issue replicable on latest master. The text is being rendered in white font color initially when app launches which makes it looks like it isn't there, but then shows up in black color font after tapping on corresponding widget (ex : TextField, Button).


https://user-images.githubusercontent.com/67046386/103650140-942aa700-4f85-11eb-9209-57dd7eb0523e.mov


<img width="321" alt="Screenshot 2021-01-05 at 6 40 30 PM" src="https://user-images.githubusercontent.com/67046386/103650187-a86ea400-4f85-11eb-861a-a1596270388d.png">

<details>
<summary>master flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.26.0-2.0.pre.179, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.179 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a293c82251 (4 hours ago), 2021-01-05 04:04:03 -0500
    • Engine revision b7352132cd
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5556 • android-x64    •
      Android 11 (API 30) (emulator)
    • macOS (desktop)                  • macos         • darwin-x64     • Mac OS
      X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                     • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

</details>

The same behavior works as expected on latest dev and beta.

<img width="333" alt="Screenshot 2021-01-05 at 6 35 10 PM" src="https://user-images.githubusercontent.com/67046386/103650267-c3d9af00-4f85-11eb-9a50-9ea56a9f8e4f.png">
<img width="327" alt="Screenshot 2021-01-05 at 6 36 30 PM" src="https://user-images.githubusercontent.com/67046386/103650272-c5a37280-4f85-11eb-8fbd-d31693fa9319.png">


<details>
<summary>dev and beta flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-1.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 63062a6443 (3 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5556 • android-x64    •
      Android 11 (API 30) (emulator)
    • macOS (desktop)                  • macos         • darwin-x64     • Mac OS
      X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                     • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!

[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5556 • android-x64    •
      Android 11 (API 30) (emulator)
    • Chrome (web)                     • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!



```

</details>

**Comment by LongCatIsLooong** [comment] 2021-01-06 20:43
first introduced in a7030ad977d5ccd177e9f9bea6e34fa01321bd1c  /cc @chinmaygarde

**Comment by LongCatIsLooong** [comment] 2021-01-07 02:04
@pedromassango @darshankawar  it no longer seems reproducible for me on the latest master branch. Could you confirm it's been fixed?

**Comment by dnfield** [comment] 2021-01-07 04:25
How did this not get caught by golden tests involving text?

**Comment by dnfield** [comment] 2021-01-07 04:25
Marking this as P0 until we're sure it's resolved.

**Comment by darshankawar** [comment] 2021-01-07 04:59
@LongCatIsLooong Yes, verified on latest master. I don't see the issue anymore.

<img width="329" alt="Screenshot 2021-01-07 at 10 27 09 AM" src="https://user-images.githubusercontent.com/67046386/103852979-14125780-50d3-11eb-8427-38bc5d07d7e9.png">
<img width="331" alt="Screenshot 2021-01-07 at 10 27 37 AM" src="https://user-images.githubusercontent.com/67046386/103852989-1674b180-50d3-11eb-80dd-4e2d15ebdf76.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.220, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.220 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 01babcac16 (85 minutes ago), 2021-01-06 22:34:03 -0500
    • Engine revision 1758eaa4ed
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    •
      Android 11 (API 30) (emulator)
    • macOS (desktop)                  • macos         • darwin-x64     • Mac OS
      X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                     • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

</details>

**Comment by dnfield** [comment] 2021-01-07 05:56
Can someone figure out where this got fixed? We should update https://github.com/flutter/flutter/wiki/Bad-Builds and mark any builds affected by this as bad.

**Comment by LongCatIsLooong** [comment] 2021-01-07 06:12
https://github.com/flutter/flutter/pull/73380. None of the commits has been tagged it seems.

**Comment by dnfield** [comment] 2021-01-07 06:27
Thanks.  @pcsosinski - is there some way we track these? I imagine google testing would catch this regression, but if not then we should still make sure this doesn't somehow make it to a tagged build.

**Comment by dnfield** [comment] 2021-01-07 06:28
I'm also still a bit unsure about how this didn't get caught in golden tests in our own repo :(

**Closed by dnfield** 2021-01-07 06:27 UTC
Labels: P0, a: text input, a: typography, customer: crowd, f: material design, found in release: 1.26, framework, has reproducible steps, passed first triage, severe: regression

**Comment by pcsosinski** [comment] 2021-01-07 18:21
@dnfield do you have a range of hashes that are affected?

**Comment by pcsosinski** [comment] 2021-01-07 18:38
cc @kf6gpe
