### ISSUE TITLE
The Android app cannot load the Flutter control when launching the Release APK. Integration with existing Android app

### ISSUE THREAD

**Issue by tianzhiguo123** [flutter/flutter#54946] opened 2020-04-16 10:02 UTC
Androidアプリは、Release APKの再生時にFlutterコントロールを読み込めません。これは、Flutterの既存のAndroidアプリを追加するためです。

![WeChat 圖片_20200416162827](https://user-images.githubusercontent.com/44284679/79443260-324b9b00-800c-11ea-937c-d50e9dd738e9.jpg)
The flutter control is not displayed in the Android Studio release version APK

**Comment by VladyslavBondarenko** [comment] 2020-04-16 10:10
Hi @tianzhiguo123 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a minimal project to reproduce it

**Comment by tianzhiguo123** [comment] 2020-04-17 10:52
This is a project of our company. Demo can't be reproduced

**Comment by tianzhiguo123** [comment] 2020-04-17 10:52
> Hi @tianzhiguo123
> can you please provide your `flutter doctor -v`?
> Also, to better address the issue, would be helpful
> if you could post a minimal project to reproduce it

This is a project of our company. Demo can't be reproduced

**Comment by VladyslavBondarenko** [comment] 2020-04-17 12:00
@tianzhiguo123 
does it work in debug mode?

**Comment by VladyslavBondarenko** [comment] 2020-04-17 14:57
Duplicate of https://github.com/flutter/flutter/issues/54938

**Closed by VladyslavBondarenko** 2020-04-17 14:57 UTC
Labels: a: existing-apps, platform-android, waiting for customer response
