### ISSUE TITLE
GestureDetector defers onTap to next screen tap

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#41233] opened 2019-09-24 22:53 UTC
So basically if you tap GestureDetector, it will defer its events until the next event is fired. This is a very serious regression unless I'm misunderstanding something.

Here's a little rx style marble diagram:

```
input:    1-2-3-4-5-6
expected: 1-2-3-4-5-6
actual:   --1-2-3-4-5
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.5, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!
```

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(_MyApp());
}

class _MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Row(
          children: [1, 2, 3].map(
            (value) {
              /// 1. Tap once on any of these
              /// 2. Observe that no print statement occurs
              /// 3. Tap anywhere on the screen
              /// 4. Observe that the previously expected print statement occurs
              ///
              /// TLDR: print statements are delayed one tap, even if the
              ///       last tap is not on any of these GestureDetectors
              return GestureDetector(
                onTap: () => print(value),
                child: Container(
                  color: Colors.red.shade100,
                  margin: EdgeInsets.all(8),
                  alignment: Alignment.center,
                  child: Text(value.toString()),
                  width: 60,
                ),
              );
            },
          ).toList(),
        ),
      ),
    );
  }
}
```

**Comment by goderbauer** [comment] 2019-09-24 23:13
Does this happen on iOS or Android or both?

**Comment by lukepighetti** [comment] 2019-09-24 23:13
I only have iOS available for testing.

**Comment by lukepighetti** [comment] 2019-09-24 23:17
@goderbauer just to be clear this would be a show stopping regression if it's widespread

**Comment by goderbauer** [comment] 2019-09-24 23:22
Yeah.

I was unable to reproduce this on master, though. Can you try if you see the problem there as well?

**Comment by athornz** [comment] 2019-09-24 23:26
I noticed issues around this on dev as well but it's fixed on master.

**Comment by goderbauer** [comment] 2019-09-24 23:27
It does reproduce on v1.10.5, though. 

/cc @liyuqian Is this related to https://github.com/flutter/flutter/issues/31086? Was that the reason why your change got reverted?

**Comment by logemann** [comment] 2019-09-24 23:29
Funny, i have exact the same problem here. First found out by using the flutter_slidable plugin. Debugged into the plugin but couldnt see any specific things besides using plain GestureDetector. I then started digging deeper. My findings were:

- only on iOS emulator (not android, not iOS physical device)
- tried it with iOS 13 and iOS 12 on Emu. Problems on both.
- tested with "master" and "dev" channel

But my problems go further like not being able to close a Drawer on tapping the main screen.

**Comment by liyuqian** [comment] 2019-09-24 23:38
@goderbauer is correct: this is a known issue that has been fixed on master: https://github.com/flutter/flutter/issues/40863

The fix should be rolled in to the dev branch soon.

**Closed by liyuqian** 2019-09-24 23:38 UTC
Labels: f: gestures, framework

**Comment by lukepighetti** [comment] 2019-09-24 23:41
Did a fresh install of Flutter and did some testing

`Channel stable, v1.9.1+hotfix.2` working
`Channel dev, v1.10.5` failed
`Channel master, v1.10.6-pre.53` working

**Comment by liyuqian** [comment] 2019-09-24 23:43
@lukepighetti : right, I'm sorry for the breakages. We recorded such issues in https://github.com/flutter/flutter/wiki/Bad-Builds and you can see that this specific issue is introduced in 1.10.4 and we're still waiting for the fix to be rolled into the dev branch. Hopefully that it will be in 1.10.6 soon.

**Comment by logemann** [comment] 2019-09-24 23:45
ok, will retry master then. I was quite sure that this happens there too. Perhaps its just too late now ;)
