### ISSUE TITLE
DataTransferItemList.getAsEntry() is not returning correct type

### ISSUE THREAD

**Issue by crizant** [flutter/flutter#143509] opened 2024-02-15 05:45 UTC
### Steps to reproduce

1. Run the sample code on chrome by `flutter run -d chrome`
2. Drag a local file into the chrome window
3. Observe console output

### Expected results

`true` should be observed.

### Actual results

`false` is observed.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:html' as html;
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  }) : super();

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    html.window.onDragEnter.listen((event) {
      event.preventDefault();
    });
    html.window.onDragOver.listen((event) {
      event.preventDefault();
    });
    html.window.onDragLeave.listen((event) {
      event.preventDefault();
    });
    html.window.onDrop.listen((event) {
      event.preventDefault();
      final items = event.dataTransfer.items;
      for (int i = 0; i < (items?.length ?? 0); i++) {
        final entry = items![i].getAsEntry();
        print(entry is html.Entry);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'Drop files here.',
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Attempting to install properties from non-Object type
'FileEntry' onto the native JS Object.
Attempting to install properties from non-Object type
'FileEntry' onto the native JS Object.
Attempting to install properties from non-Object type
'FileEntry' onto the native JS Object.
false
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor
-v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3.1
    23D60 darwin-arm64, locale zh-HK)
[✓] Android toolchain - develop for Android devices
    (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by crizant** [comment] 2024-02-15 06:21
In release mode `entry is html.Entry` returns `true`, but `entry is html.FileEntry` is not.

**Comment by huycozy** [comment] 2024-02-15 11:36
Reproduced this issue on master channel as well.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.9 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (14 hours ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-7.0.pre.58, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-7.0.pre.58 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0fac13b443 (5 hours ago), 2024-02-14 22:43:18 +0000
    • Engine revision 3af336bfb2
    • Dart version 3.4.0 (build 3.4.0-140.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • iPad (mobile)   • 00008103-000A1464346A201E • ios            • iOS 17.2 21C62
    • macOS (desktop) • macos                     • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by yjbanov** [comment] 2024-02-15 19:05
This seems to be a Dart SDK issue. However, consider switching to `package:web`, which replaces `dart:html`.

**Comment by a-siva** [comment] 2024-02-20 18:43
//cc @sigmundch this is marked as a dart dependency issue, please feel free to close if issues `dart:html` are not intended to be fixed.

**Comment by srujzs** [comment] 2024-02-23 00:51
This issue is likely not fixable (explained below) so the above code works as intended, and considering our shift to encourage users to use `package:web`, I'd recommend using that instead. Try casting the entry you get back from `getAsEntry` to [`FileSystemEntry`](https://github.com/dart-lang/web/blob/975e55cbe4ac683c33d5256a91f4133fa97b4c34/lib/src/dom/entries_api.dart#L16), and using JS interop to interact with it. Since the constructor for `FileSystemFileEntry` can't be accessed, you can't use `instanceof` to type-check, but it looks like the correct way to determine if it's a `FileSystemFileEntry` is to use [`isFile`](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry/isFile).

Closing as I believe the fix is not feasible.

Some background mostly for posterity:

It looks like at some point `FileSystemFileEntry` (the native type that `FileEntry` corresponds to) had its constructor replaced with JS `Object`: https://github.com/dart-lang/sdk/blob/bd38fbada435677e65d8fa76444244b163e5b72c/sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart#L420.

Previously, the type was not visible in the global scope, so we added code in DDC to defer the registration of this type until we actually got such an object: https://github.com/dart-lang/sdk/commit/01642c21229cfa97612a974bf93c22930c00e4f4. When we did get such an object in `getAsEntry`, we'd then try to register/map the type to the Dart `@Native` class using the object's constructor. However, it looks like that constructor no longer exists either. Dart2js does something slightly different by checking doing an `Object.prototype.toString` call, which I suppose if the constructor no longer exists, probably also doesn't work, and hence `entry is html.FileEntry` is false.

The only real alternative here is to polyfill the type so `is` checks like the above still work: https://github.com/dart-lang/sdk/blob/bd38fbada435677e65d8fa76444244b163e5b72c/sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/runtime.dart#L95, but I think this only works for DDC and not Dart2js.

**Closed by srujzs** 2024-02-23 00:51 UTC
Labels: engine, dependency: dart, platform-web, has reproducible steps, team-web, found in release: 3.16, found in release: 3.20, dependency:dart-triaged
