### ISSUE TITLE
Show extensions function in suggestions ide

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#59516] opened 2020-06-16 00:51 UTC
Current. All extensions don't show if not import them yet. I think it should be smarter by pre suggest :D

**Comment by TahaTesser** [comment] 2020-06-16 09:52
Hi @tbm98 
I would think suggestions in IDE are related to Flutter plugins

For VSC 
 [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).

For Android Studio
[jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-16 09:52 UTC
