### ISSUE TITLE
Failed assertion node.isRepaintBoundary is not true when combining LayoutBuilder, AnimatedSwitcher and ProgressIndicator

### ISSUE THREAD

**Issue by snipd-mikel** [flutter/flutter#120874] opened 2023-02-16 11:29 UTC
I have found an issue where a `Failed assertion node.isRepaintBoundary is not true` is thrown when having a tree consisting of `LayoutBuilder`, `AnimatedSwitcher` and `CircularProgressIndicator`.

The issue happens when the `AnimatedSwitcher`'s animation duration (`kAnimationDuration` on the example) is bigger than the duration of the change rate of the variable controlling the `AnimatedSwitcher`'s child (`kTimerDuration` on the example). The assertion fails when the `AnimatedSwitcher`'s child changes for the second time (in the example I run the timer switching the child twice).

Removing the `LayoutBuilder` from the tree prevents the assertion to fail. Wrapping the `CircularProgressIndicator` with a `RepaintBoundary` widget.

## Steps to Reproduce

1. Execute `flutter run` (debug mode) on the code sample.
2. Check the Console. You will see the following assertion exception `'package:flutter/src/rendering/object.dart': Failed assertion: line 1135 pos 20: 'node.isRepaintBoundary': is not true.` (Complete logs on Logs section)

**Expected results:** Don't throw assert exception

**Actual results:** Assert ` 'node.isRepaintBoundary': is not true.` thrown

<details>
<summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

const kAnimationDuration = Duration(milliseconds: 1000);
const kTimerDuration = Duration(milliseconds: 900);
void main() {
  runApp(const IssueApp());
}

class IssueApp extends StatelessWidget {
  const IssueApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: IssueScreen(),
    );
  }
}

class IssueScreen extends StatefulWidget {
  const IssueScreen({Key? key}) : super(key: key);

  @override
  State<IssueScreen> createState() => _IssueScreenState();
}

class _IssueScreenState extends State<IssueScreen> {
  bool _showLoading = true;
  Timer? _timer;
  @override
  void initState() {
    int times = 0;
    _timer = Timer.periodic(kTimerDuration, (timer) {
      setState(() {
        _showLoading = !_showLoading;
      });
      times++;
      if (times > 2) {
        timer.cancel();
      }
    });
    super.initState();
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Issue screen'),
      ),
      body: LayoutBuilder(builder: (context, constraints) {
        return AnimatedSwitcher(
          duration: kAnimationDuration,
          child: _showLoading
              ? const CircularProgressIndicator()
              : const SizedBox(),
        );
      }),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1135 pos 20: 'node.isRepaintBoundary': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1135:20)
#3      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:518:19)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#9      _invoke (dart:ui/hooks.dart:145:13)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#11     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
```

```
flutter analyze                                           
Analyzing issue.dart...
No issues found! (ran in 0.5s)
```

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2 22D49 darwin-arm64, locale en-CH)
    • Flutter version 3.7.3 on channel stable at /Users/mcorcuera/development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mcorcuera/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • Mikel’s iPhone (mobile) • 00008110-000609D40C38401E • ios            • iOS 16.2 20C65
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-02-16 12:50
Thanks for the report. I am seeing same behavior using latest master and stable versions.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.3 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.8.0-13.0.pre.52, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.8.0-13.0.pre.52 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc473e4f19 (73 minutes ago), 2023-02-15 22:51:19 -0500
    • Engine revision 3fc40ca5be
    • Dart version 3.0.0 (build 3.0.0-241.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by tim-isonsolutions** [comment] 2023-02-17 21:05
Yes, I'm see the exact same as well.

Flutter 3.7.3 • channel stable

Thanks for the very useful report of it.

**Comment by Jonas-Sander** [comment] 2023-02-18 18:09
In my case we have a permanent `Drawer` with a list of a custom `DrawerTile` widgets, with each an `AnimatedSwitcher` inside it. The `AnimatedSwitcher` is used to animate the tile becoming active.  When using the `Drawer` to navigate between pages `Failed assertion node.isRepaintBoundary is not true` would show up, since changing the page would make another tile active and trigger the `AnimatedSwitcher`.   
Removing the `AnimatedSwitcher` inside the `DrawerTile` fixed it (but now the UI looks worse😭)

I don't know if it is the interplay between `Drawer` and `AnimatedSwitcher` or another widget inside the widget tree either outside of the drawer or inside the drawer. Right now I can't investigate further. We don't use a `LayoutBuilder` but `Row`, `Column`, `SizedBox`, `Expanded`, `SingleChildScrollView`.

This error started occurred when I tried to upgrade our Flutter app from `2.10.5` to `3.7.3`, it didn't occur before upgrading.

**Comment by bleroux** [comment] 2023-02-20 07:03
FYI, I bisected this regression to the following commit: https://github.com/flutter/flutter/pull/106962

**Comment by HansMuller** [comment] 2023-02-23 16:48
CC @gspencergoog 
https://github.com/flutter/flutter/pull/106962 was landed by @youssef-attia, looks like your LGTM.

**Comment by LongCatIsLooong** [comment] 2023-03-02 18:23
Looks like this has already been fixed by https://github.com/flutter/flutter/pull/121408.

**Comment by gnprice** [comment] 2023-03-04 04:39
#121408 has since been reverted, in #121835, so reopening.

See also #121336, which was fixed by the same PR that fixed this one.

**Comment by Paul-cbt** [comment] 2023-03-06 17:21
Same issue here, seems to happen when I press a button which is currently being animated to by an AnimatedSwitcher.
For example:
AnimatedSwitcher(
  duration: const Duration(milliseconds: 400),
child: isLoading? Container(): Button(...)
);
if I press the button just after isLoading has been set to false the issue happens

**Comment by DieGlueckswurst** [comment] 2023-04-05 11:05
same issue here, using a `AnimatedSwitcher`. Is there a fix coming or a workaround? For now, all I could do is lower the `duration`, which is not ideal.

**Comment by tim-isonsolutions** [comment] 2023-04-06 16:06
Just wrapping the animation in a RepaintBoundary was the workaround for my case.

**Comment by nero-angela** [comment] 2023-06-29 03:32
> Just wrapping the animation in a RepaintBoundary was the workaround for my case.

When I wrapped the child of the `AnimatedSwitcher` with `RepaintBoundary`, the error did not occur, but the `AnimatedSwitcher` did not work.

**Comment by trapeye** [comment] 2023-08-24 12:16
is there any alternative solution other than RepaintBoundary?

**Comment by ahmed-alqazzaz** [comment] 2024-02-08 07:40
Wrapping the child with a SizedBox fixed the issue for

```
AnimatedSwitcher(
              child: SizedBox(
                child: child,
                width: getScreenSize().width * 0.75,
              ),
              duration: const Duration(milliseconds: 500),
 )
```

**Comment by Hyla96** [comment] 2024-02-27 14:43
> Wrapping the child with a SizedBox fixed the issue for me
> 
> ```
> AnimatedSwitcher(
>   child: SizedBox(
>    key: UniqueKey(),
>     child: child,
>     width: getScreenSize().width * 0.75,
>   ),
>   duration: const Duration(milliseconds: 500),
> );
> ```

This workaround works for me too. In my case I have an AnimatedAlign wrapped by a LayoutBuilder and with an animated shimmer as child.

**Comment by Muffin8175** [comment] 2024-04-12 09:55
Adding `key: UniqueKey()` to AnimatedSwitcher was the 'key' :)

**Comment by mpsal** [comment] 2024-06-15 12:22
> > Just wrapping the animation in a RepaintBoundary was the workaround for my case.
> 
> When I wrapped the child of the `AnimatedSwitcher` with `RepaintBoundary`, the error did not occur, but the `AnimatedSwitcher` did not work.

This problem seems to be related to the animated switcher not detecting that the child changed, because it is the same widget (RepaintBoundary). Providing a key that changes depending on the child or only wrapping the problematic child (CircularProgressIndicator) with the RepaintBoundary solved the issue for me.

**Comment by mrRedSun** [comment] 2024-06-26 11:18
Workarounds with unique or value key are problematic as they reset state which causes unexpected behavior when the value key changes, proceed with workarounds with caution, this may lead to an unexpected behavior

**Comment by AlexDochioiu** [comment] 2024-07-15 19:42
Also encountering this issue on Flutter version 3.23.0-0.1.pre
Cause is: Layout Builder -> Animated Switcher -> Some (Custom) Animated Widget

**Comment by ToniTornado** [comment] 2024-07-17 02:04
I have a rather complicated `StatefulWidget`: `VisibilityDetector` > `ValueListenableBuilder` > `LayoutBuilder` > [QR code scanner widget]
Wrapping the whole thing with a ColoredBox kills it.

Flutter stable / 3.22.2

**Comment by LongCatIsLooong** [comment] 2024-07-23 03:30
I can no longer reproduce the issue on master (but I was able to repro this using `3.23.0-0.1.pre`) using the provided sample. It looks like 8ce3bfb6ca4c2339b6eaed3a954547fc6498e8db fixed it.

**Closed by LongCatIsLooong** 2024-07-23 03:30 UTC
Labels: c: regression, c: crash, framework, f: material design, a: error message, has reproducible steps, P2, found in release: 3.7, found in release: 3.8, team-framework, triaged-framework
