### ISSUE TITLE
BoxConstraints Invalid argument(s): 0.0

### ISSUE THREAD

**Issue by Midicon** [flutter/flutter#58216] opened 2020-05-29 02:24 UTC
My project has too many pages and widgets, so I can't ensure which one cause this problem.
#5259 may not be the answer for this problem.
Flutter version is 1.12.13.
```
***[Invalid argument(s): 0.0
#0 _Double.clamp (dart:core-patch/double.dart:184)
#1 BoxConstraints.constrainWidth (package:flutter/src/rendering/box.dart:257)
#2 BoxConstraints.constrain (package:flutter/src/rendering/box.dart:284)
#3 RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209)
#4 RenderObject.layout (package:flutter/src/rendering/object.dart:1767)
#5 RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744)
#6 RenderObject.layout (package:flutter/src/rendering/object.dart:1767)
#7 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110)
#8 RenderObject.layout (package:flutter/src/rendering/object.dart:1767)
#9 RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:264)
...
```

**Comment by iapicca** [comment] 2020-05-29 12:21
Hi @Midicon 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, your `flutter run --verbose` and a minimal reproducible code sample.
Thank you

**Comment by TahaTesser** [comment] 2020-06-19 15:23
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-19 15:23 UTC
Labels: in triage, waiting for customer response

**Comment by meritozh** [comment] 2020-08-14 06:31
@Midicon Hi, can you share your complete stacktrace?

**Comment by Midicon** [comment] 2020-08-14 07:10
> @Midicon Hi, can you share your complete stacktrace?

Thanks for following this problem. I have found the cause for this problem and I am sorry for that I haven't updating information of this problem in time. The reason that cause this problem is using an illegal method to hide a widget. Now I use offstage to avoid this problem and it works.

**Comment by meritozh** [comment] 2020-08-14 08:48
@Midicon Can you share more information? I face similar issue, but cannot found the root cause. Such as, what is illegal method? `Visibility`, do you try to hide a sliver or box widget in a `SliverList`? I try to make a reproducible code sample.

**Comment by Midicon** [comment] 2020-08-14 09:38
I used to move the widget out of the screen to hide it instead of using visibility or offstage.  It has been a long time so is hard to find the history code. I think you may put your widget out of boundary.
