### ISSUE TITLE
Wrong hour/minute order in timePicker in RTL mode

### ISSUE THREAD

**Issue by mehrdad-shokri** [flutter/flutter#63427] opened 2020-08-10 21:26 UTC
Hour and Minute order are wrong in RTL mode. It is just reversed from left -> right to right -> left.
Hour view is same in both RTL and LTR meaning hour comes on the left and minute comes on the right.  
To reproduce the problem set ``locale`` in ``MaterialApp`` to an rtl locale (like ``Locale('fa')``); and call ``showTimePicker(context:context, initialTime: TimeOfDay.now());``
![screenshot-2020-08-11_01 50 05 949](https://user-images.githubusercontent.com/13661520/89832987-7fccb480-db75-11ea-99be-8ea1b638aa98.png)

**Comment by mehrdad-shokri** [comment] 2020-08-10 21:44
For now I solved it by:  
```
                    builder: (BuildContext context, Widget child) {
                      return Directionality(
                        textDirection: TextDirection.ltr,
                        child: child,
                      );
                    }
```

**Comment by liyuqian** [comment] 2020-08-10 21:46
This does not seem to be a performance issue. @HansMuller : do you know if someone in the design language team can take a look at this?

**Comment by mehrdad-shokri** [comment] 2020-08-10 21:56
@liyuqian yes it's not. my previous workaround also didn't work because it took action bottoms to the right which is wrong direction.

**Comment by TahaTesser** [comment] 2020-08-11 11:26
@mehrdad-shokri 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by mehrdad-shokri** [comment] 2020-08-11 12:36
@TahaTesser sure
```
▶ flutter doctor -v
[✓] Flutter (Channel master, 1.20.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0 at /home/mehrdad/flutter
    • Framework revision c68758fab1 (7 weeks ago), 2020-06-24 21:23:02 -0700
    • Engine revision 0c14126211
    • Dart version 2.9.0 (build 2.9.0-18.0.dev d8eb844e5d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/mehrdad/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/mehrdad/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Samsung Galaxy S10 • 192.168.59.102:5555 • android-x86 • Android 10 (API
      29)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-08-11 14:26
Hi @mehrdad-shokri 
That looks to be quite a old `master` channel 

Can you upgrade to latest `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by mehrdad-shokri** [comment] 2020-08-12 04:11
@TahaTesser  After upgrading flutter it's now fixed on dial mode, but it's still reverse on the input mode.  
![screenshot-2020-08-12_08 34 58 851](https://user-images.githubusercontent.com/13661520/89974164-87748200-dc77-11ea-8b6d-80545dddaf53.png)
![screenshot-2020-08-12_08 35 09 001](https://user-images.githubusercontent.com/13661520/89974170-89d6dc00-dc77-11ea-9c2a-f2870083b6f5.png)
```

▶ flutter doctor -v
[✓] Flutter (Channel master, 1.21.0-8.0.pre.175, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-8.0.pre.175 at /home/mehrdad/flutter
    • Framework revision 4a1a0c1e22 (73 minutes ago), 2020-08-11 22:46:02 -0400
    • Engine revision 9893a29366
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/mehrdad/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/mehrdad/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Samsung Galaxy S10 (mobile) • 192.168.59.102:5555 • android-x86 • Android 10 (API 29)

• No issues found!

```

**Comment by mehrdad-shokri** [comment] 2020-08-12 07:34
It doesn't also accept a valid hour/minute on the input mode.
![screenshot-2020-08-12_12 02 48 084](https://user-images.githubusercontent.com/13661520/89987825-e5af5e00-dc93-11ea-89a7-f139e436124d.png)

**Comment by HansMuller** [comment] 2020-08-12 15:39
CC @rami-a @darrenaustin

**Comment by rami-a** [comment] 2020-08-12 15:46
This is a duplicate of https://github.com/flutter/flutter/issues/62775 and is fixed on `master`. We've also requested that the [fix](https://github.com/flutter/flutter/pull/62803) be cherry-picked into stable.

**Comment by mehrdad-shokri** [comment] 2020-08-12 17:35
@rami-a I'm on master channel and updated ~10 hours ago and still have the problem

**Comment by mehrdad-shokri** [comment] 2020-08-12 17:38
@rami-a to be more clear it is fixed on dial mode but still this is the problem on input mode

**Comment by rami-a** [comment] 2020-08-12 17:39
ah sorry you're right, I must have missed the input mode. I'll create a fix for this

**Comment by mehrdad-shokri** [comment] 2020-08-12 17:41
@rami-a very thanks.

**Comment by mehrdad-shokri** [comment] 2020-08-14 09:41
thank you very much @rami-a is this update available on master channel now?

**Comment by mehrdad-shokri** [comment] 2020-08-14 11:36
Updated flutter and confirm it is fixed, but there are 2 issues. Fist padding-bottom of action buttons in input mode is less than dial mode padding. Also why inserting English digits is not a valid time? I think it's a bug too

![screenshot-2020-08-14_16 03 54 542](https://user-images.githubusercontent.com/13661520/90245472-fe607500-de47-11ea-9ba8-8a56e1b6292c.png)
![screenshot-2020-08-14_16 03 32 392](https://user-images.githubusercontent.com/13661520/90245478-00c2cf00-de48-11ea-8176-e5a0682f5962.png)

**Comment by rami-a** [comment] 2020-08-14 13:34
Oh that's very interesting, I'll have to take a look. Could you please file this is a separate issue @mehrdad-shokri? Since this one is closed and is specific to RTL order. Thanks!

**Comment by rami-a** [comment] 2020-08-18 21:34
My fix had to be reverted since it caused the ":" to not be aligned properly. Creating a new fix now

**Comment by rami-a** [comment] 2020-08-19 13:31
New fix has landed and should be the one that is cherry-picked if possible

**Closed** 2020-08-19 13:30 UTC
Labels: a: internationalization, a: quality, cp: 1.20, f: date/time picker, f: material design, framework
