### ISSUE TITLE
Could not determine the dependencies of task ':firebase_admob:generateDebugRFile'.

### ISSUE THREAD

**Issue by Irewoleo** [flutter/flutter#58051] opened 2020-05-27 00:10 UTC
I get an error when trying to run my flutter app.

    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-sdk-api-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-impl-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] play-services-measurement-base-17.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    [Fatal Error] firebase-iid-19.0.0.pom:2:1: Content is not allowed in prolog.
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Could not determine the dependencies of task ':firebase_admob:generateDebugRFile'.
    > Could not resolve all task dependencies for configuration ':firebase_admob:debugCompileClasspath'.
       > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
         Required by:
             project :firebase_admob > com.google.android.gms:play-services-ads-lite:18.1.1
             project :firebase_admob > com.google.android.gms:play-services-measurement-api:17.0.0
             project :firebase_admob > com.google.android.gms:play-services-measurement-sdk:17.0.0
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-sdk-api/17.0.0/play-services-measurement-sdk-api-17.0.0.pom
                > Content is not allowed in prolog.
       > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
         Required by:
             project :firebase_admob > com.google.android.gms:play-services-measurement:17.0.0
             project :firebase_admob > com.google.android.gms:play-services-measurement-api:17.0.0
             project :firebase_admob > com.google.android.gms:play-services-measurement-sdk:17.0.0
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-base:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-base/17.0.0/play-services-measurement-base-17.0.0.pom
                > Content is not allowed in prolog.
       > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
         Required by:
             project :firebase_admob > com.google.android.gms:play-services-measurement:17.0.0
             project :firebase_admob > com.google.android.gms:play-services-measurement-api:17.0.0
             project :firebase_admob > com.google.android.gms:play-services-measurement-sdk:17.0.0
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.android.gms:play-services-measurement-impl:17.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-measurement-impl/17.0.0/play-services-measurement-impl-17.0.0.pom
                > Content is not allowed in prolog.
       > Could not resolve com.google.firebase:firebase-iid:19.0.0.
         Required by:
             project :firebase_admob > com.google.android.gms:play-services-measurement-api:17.0.0
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
          > Could not resolve com.google.firebase:firebase-iid:19.0.0.
             > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/19.0.0/firebase-iid-19.0.0.pom
                > Content is not allowed in prolog.
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    BUILD FAILED in 41s
    Exception: Gradle task assembleDebug failed with exit code 1
    Exited (sigterm)
Can anyone help me out on this. I have been on it for days now, with not a single progress. I need y'all help.
Just assist me in working this out and I will be forever grateful. I need all the help I can get.

Can anyone help me out on this. I have been on it for days now, with not a single progress. I need y'all help.
Just assist me in working this out and I will be forever grateful. I need all the help I can get.

Can anyone help me out on this. I have been on it for days now, with not a single progress. I need y'all help.
Just assist me in working this out and I will be forever grateful. I need all the help I can get.

**Comment by TahaTesser** [comment] 2020-05-27 09:27
Hi @Irewoleo 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank yoU

**Closed by TahaTesser** 2020-05-27 09:27 UTC
