### ISSUE TITLE
Unable to download from Google Drive or OneDrive

### ISSUE THREAD

**Issue by dashanan13** [flutter/flutter#70066] opened 2020-11-08 22:40 UTC
## Steps to Reproduce

Flutter can not download files from Google Drive or OneDrive, zip or otherwise. 
The files just get partially downloaded where as files from most other links from websites etc are downloaded completely.
Example code shows both links and result.
**Expected results:** Files from Google Drive or Microsoft One drive are downloaded completely

**Actual results:** The files are not completely downloaded rather only 10 % or so and the program finishes.

```
import 'package:archive/archive.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'dart:io';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Flutter Demo', theme: ThemeData(primarySwatch: Colors.blue,visualDensity: VisualDensity.adaptivePlatformDensity,), home: MyHomePage(),);
  }
}

class MyHomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Downloading Files'),),
      body: Center(child: Text('Press the floating button to download files',),),
      floatingActionButton: FloatingActionButton(
        onPressed: () { _downloadFile();},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  Future<File> _downloadFile() async {

    String myUrl = 'https://drive.google.com/file/d/1xnhT8mzMeU-wRemt1sNFR0DJt2MNmSC8/view?usp=sharing';
    String my7ZIPUrl = 'https://www.gutenberg.org/files/1342/1342-h.zip';
    String myDownloadDirectory = ((await getApplicationDocumentsDirectory()).path);
    String myDownloadedGoogleFile1 = 'myColorsDIO.zip';
    String myDownloadedGoogleFile2 = 'myColorsHTTP.zip';
    String myDownloadedfromgutenberg1 = '1342DIO.zip';
    String myDownloadedfromgutenberg2 = '1342HTTP.zip';

    print('Download Directory: $myDownloadDirectory');
    //Downloading Google Drive zip file via DIO
    Dio dio = Dio();
    await dio.download(
        myUrl,
        '$myDownloadDirectory/$myDownloadedGoogleFile1',
        onReceiveProgress: (rcv, total) {print('received: ${rcv.toStringAsFixed(0)} out of total: ${total.toStringAsFixed(0)}');}
    );

    await dio.download(
        my7ZIPUrl,
        '$myDownloadDirectory/$myDownloadedfromgutenberg1',
        onReceiveProgress: (rcv, total) {print('received: ${rcv.toStringAsFixed(0)} out of total: ${total.toStringAsFixed(0)}');}
    );

    //Downloading Google Drive zip file via HTTP
    var req = await http.Client().get(Uri.parse(myUrl));
    var file = File('$myDownloadDirectory/$myDownloadedGoogleFile2',);
    file.writeAsBytes(req.bodyBytes);

    //Downloading Google Drive zip file via HTTP
    var req1 = await http.Client().get(Uri.parse(my7ZIPUrl));
    var file1 = File('$myDownloadDirectory/$myDownloadedfromgutenberg2',);
    file1.writeAsBytes(req1.bodyBytes);

print('Expected size: myColorsDIO.zip: 594,545 , myColorsHTTP.zip: 594,545 , 1342DIO.zip: 778512,  1342HTTP.zip: 778512');
    print('myColorsDIO.zip: ${await File('$myDownloadDirectory/$myDownloadedGoogleFile1',).length()}, myColorsHTTP.zip: ${await File('$myDownloadDirectory/$myDownloadedGoogleFile2',).length()}, 1342DIO.zip: ${await File('$myDownloadDirectory/$myDownloadedfromgutenberg1',).length()},  1342HTTP.zip: ${await File('$myDownloadDirectory/$myDownloadedfromgutenberg2',).length()}');
    return null;
  }

}
```

<details>
Output:
Expected size: myColorsDIO.zip: 594,545 , myColorsHTTP.zip: 594,545 , 1342DIO.zip: 778512,  1342HTTP.zip: 778512
Obtained size: myColorsDIO.zip: 63411, myColorsHTTP.zip: 70677, 1342DIO.zip: 778512,  1342HTTP.zip: 778512

Packages used: DIO and HTTP

</details>

**Comment by pedromassangocode** [comment] 2020-11-09 10:34
Hi @dashanan13 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins/package?
Thank you

**Comment by dashanan13** [comment] 2020-11-09 10:46
@pedromassangocode I am not sure how to achieve downloading functionality without a package.
Packages used: DIO and HTTP
 Pubspec.yaml:

name: flutter_downloading
description: Flutter application to download stuff

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  dio: ^3.0.10
  archive: ^2.0.13
  path_provider: ^1.6.24


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by pedromassangocode** [comment] 2020-11-09 12:33
Hi @dashanan13 
If you are using the [http](https://pub.dev/packages/http) package I suggest you to file this issue [here](https://github.com/dart-lang/http). And if you are using [Dio](https://pub.dev/packages/dio) you can file the issue [here](https://github.com/flutterchina/dio).

I'm closing this since Downloading capability is not something related to Flutter itself but with the packages you are using.
Thank you

**Closed by pedromassangocode** 2020-11-09 12:33 UTC
Labels: in triage

**Comment by dashanan13** [comment] 2020-11-09 20:43
@pedromassangocode Is there no native alternative in flutter or dart to download files?

**Comment by pedromassangocode** [comment] 2020-11-10 07:12
In http://pub.dev/ you can find some similar packages for file downloads.
