### ISSUE TITLE
Assertion "RenderBox was not laid out: RenderEditable#c3d81 NEEDS-LAYOUT NEEDS-PAINT" indicates an error

### ISSUE THREAD

**Issue by qualitrium-peter** [flutter/flutter#79183] opened 2021-03-27 04:38 UTC
<details> 
<summary>code sample</summary> 

```dart
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  Persist _query = Persist();

  final myLove = Secret(
    id: 0,
    secretBase64: "Je veux connaître Karine très bien! Et je veux la soutenir.",
    description: 'My heartfelt secret',
    key: "my 32 length key................",
  );

  List<Secret> _secrets = [];

  final _searchFormKey = GlobalKey<FormState>();
  final controller = TextEditingController();
  String _searchText;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<KeyHolder>(
      builder: (context, holder, child) => Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              _search_add(),
              _list(),
            ],
          ),
        ),
      ),
    );
  }

  _search_add() => Container(
    color: Colors.white,
    padding: EdgeInsets.symmetric(vertical: 10, horizontal: 10),
    child: Form(
      key: _searchFormKey,
      child: Row(
        children: <Widget>[
          Flexible(
            child: TextFormField(
              decoration: InputDecoration(hintText: 'Search for description of Secret'),
              controller: controller,
              autofocus: true,
              onChanged: (text) {
                _searchText = text;
                _onFilter();
              },
            ),
          ),
          OutlinedButton(
            onPressed: () {
              debugPrint("I am a material button and the secret is ${controller.text}");
              _onCreate();
            },
            child: Text("Search"),
          ),
        ],
      ),
    ),
  );

  _list() => Expanded(
    child: Card(
      margin: EdgeInsets.fromLTRB(10, 10, 10, 0),
      child: ListView.builder(
        padding: EdgeInsets.all(8),
        itemCount: _secrets.length,
        itemBuilder: (context, index) {
          return Column(
            children: <Widget>[
              ListTile(
                title: Text(_secrets[index].description),
              ),
              Divider(
                height: 4.0,
              )
            ],
          );
        },
      ),
    ),
  );

  _onCreate() {}

  _onFilter() {
    _secrets.add(myLove);
    print("Now searching for ... $_searchText ...");
  }

  Widget _makeRoute(
      {@required BuildContext context,
       @required String routeName,
       Object arguments}) {
    final Widget child = _buildRoute(
      context: context,
      routeName: routeName,
      arguments: arguments,
    );
    return child;
  }

  Widget _buildRoute({
    @required BuildContext context,
    @required String routeName,
    Object arguments,
  }) {
    switch (routeName) {
      case '/add':
        return AddSecretPage();
/*        return MultiProvider(
          providers: [
            ChangeNotifierProvider.value(
              value: provider,
            )
          ],
          child: AddSecretPage(),
        ); */
      default:
        return Container();
    }
  }
}
``` 

</details>

When rendering the above Class, this error was detected:

<details> 
<summary>logs</summary> 

```bash
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for FocusNode:
RenderBox was not laid out: RenderEditable#c3d81 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1785 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md


> When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1785:12)
#3      EditableTextState._updateSizeAndTransform (package:flutter/src/widgets/editable_text.dart:2289:40)
#4      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:1922:7)
#5      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:1955:7)
#6      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:2266:5)
...
The FocusNode sending notification was: FocusNode#0c1ea([PRIMARY FOCUS])
  context: EditableText-[LabeledGlobalKey<EditableTextState>#7f337]
  PRIMARY FOCUS
====================================================================================================\
```

</details>

**Comment by TahaTesser** [comment] 2021-03-29 15:26
Hi @qualitrium-peter 
Thanks for filing the issue, I stripped out all the unnecessary code from your code sample, made a runnable code sample and tried to reproduce it, I'm not able to reproduce the issue

Can you please edit the code sample if needed and provide reproducible steps along with your `flutter doctor -v`

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  // Persist _query = Persist();

  // final myLove = Secret(
  //   id: 0,
  //   secretBase64: "Je veux connaître Karine très bien! Et je veux la soutenir.",
  //   description: 'My heartfelt secret',
  //   key: "my 32 length key................",
  // );

  List<String> _secrets = [];

  final _searchFormKey = GlobalKey<FormState>();
  final controller = TextEditingController();
  String _searchText;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            _search_add(),
            _list(),
          ],
        ),
      ),
    );
  }

  _search_add() => Container(
        color: Colors.white,
        padding: EdgeInsets.symmetric(vertical: 10, horizontal: 10),
        child: Form(
          key: _searchFormKey,
          child: Row(
            children: <Widget>[
              Flexible(
                child: TextFormField(
                  decoration: InputDecoration(
                      hintText: 'Search for description of Secret'),
                  controller: controller,
                  autofocus: true,
                  onChanged: (text) {
                    _searchText = text;
                    _onFilter();
                  },
                ),
              ),
              OutlinedButton(
                onPressed: () {
                  debugPrint(
                      "I am a material button and the secret is ${controller.text}");
                  _onCreate();
                },
                child: Text("Search"),
              ),
            ],
          ),
        ),
      );

  _list() => Expanded(
        child: Card(
          margin: EdgeInsets.fromLTRB(10, 10, 10, 0),
          child: ListView.builder(
            padding: EdgeInsets.all(8),
            itemCount: _secrets.length,
            itemBuilder: (context, index) {
              return Column(
                children: <Widget>[
                  ListTile(
                    title: Text(_secrets[index]),
                  ),
                  Divider(
                    height: 4.0,
                  )
                ],
              );
            },
          ),
        ),
      );

  _onCreate() {}

  _onFilter() {
    // _secrets.add(myLove);
    print("Now searching for ... $_searchText ...");
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.294, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.294 at /Users/tahatesser/Code/flutter_master
    • Framework revision a603714610 (29 hours ago), 2021-03-28 03:54:02 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```
	
</details>


Thank you

**Comment by pedromassangocode** [comment] 2021-04-21 09:11
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:11 UTC
Labels: a: text input, in triage, waiting for customer response
