### ISSUE TITLE
TimePicker needs some semantics for integration testing

### ISSUE THREAD

**Issue by ilyasRikI** [flutter/flutter#151758] opened 2024-07-15 14:43 UTC
### Use case

I would highly suggest to have semantics built in within the TimePicker DatePicker so to make it easier for integration tests, 
now I have some difficulties with automation tests for the widget and I prefer not to deal with it by using the offsets. 

Maybe I am missing something, if so please let me know 🙏 

### Proposal

<img width="368" alt="Screenshot 2024-07-15 at 4 42 52 pm" src="https://github.com/user-attachments/assets/1e18c7ba-a88f-41ba-a88d-9b1f5acc376c">

![Uploading Screenshot 2024-07-15 at 4.43.16 pm.png…]()

<img width="337" alt="Screenshot 2024-07-15 at 4 43 41 pm" src="https://github.com/user-attachments/assets/4696cf8d-b9ca-4f98-94ff-b3e2e100e255">

**Comment by darshankawar** [comment] 2024-07-16 06:32
Closing this as duplicate of https://github.com/flutter/flutter/issues/51331

**Closed by darshankawar** 2024-07-16 06:32 UTC
Labels: in triage
