### ISSUE TITLE
after i upgrade to Flutter 1.7.8+hotfix.4 • channel stable, after clicking on TextField the keyboard can't load

### ISSUE THREAD

**Issue by ReounKompheareak** [flutter/flutter#36918] opened 2019-07-25 04:56 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by vagrantrobbie** [comment] 2019-07-25 13:03
Which device OS?

**Comment by ReounKompheareak** [comment] 2019-07-25 13:49
I tested it on android Pie

**Comment by HansMuller** [comment] 2019-07-25 15:19
We're not seeing this issue. Please provide the output of `flutter doctor` and a small self-contained app that demonstrates the problem and we'll look into it. Note also: https://gist.github.com/ is a useful way to share the code.

**Comment by ReounKompheareak** [comment] 2019-07-26 01:50
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code, 64-bit edition (version 1.36.1)
[√] Connected device (1 available)

• No issues found!

**Comment by ReounKompheareak** [comment] 2019-07-26 01:51
This is when i clicked on Textfield


W/InputMethodManager(10092): startInputReason = 3
I/InputMethodManager(10092): showSoftInput
I/InputMethodManager(10092): mServedView =com.optistech.meetingv2flutteradmin;view =com.optistech.meetingv2flutteradmin;flags =0
I/HwSecImmHelper(10092): mSecurityInputMethodService is null
E/SpannableStringBuilder(10092): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(10092): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(10092): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(10092): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/HwSecImmHelper(10092): mSecurityInputMethodService is null
D/HwAppInnerBoostImpl(10092): asyncReportData com.optistech.meetingv2flutteradmin,2,1,1,0 interval=236

**Comment by HansMuller** [comment] 2019-07-29 15:56
Thanks for the console log messages! Unfortunately to address this issue we'll really need a test case (we haven't seen the problem in internal testing): https://github.com/flutter/flutter/issues/36918#issuecomment-515087656

**Comment by suesitran** [comment] 2019-07-31 10:54
I have the same issue, and in my case, the problem happens if the TextField is inside nested navigator widget.

**Comment by VictorCamargo** [comment] 2019-08-05 10:45
I'm getting the same error only on fields that are inside a page that was presented by **Navigator**.

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.13.6 17G7024, locale en-PT)
    • Flutter version 1.7.8+hotfix.4 at /Users/victor/development/flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/victor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • VOG L29 • 22X7N19315033169 • android-arm64 • Android 9 (API 28)

• No issues found!

```

**Comment by mlamp** [comment] 2019-08-06 20:12
@HansMuller @vagrantrobbie tested flutter master and dev versions and cloned / ran project: https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example

Console doesn't have anything interesting, posting flutter doctor  -v output:
```22:55 $ ~/_DEV/flutter/bin/flutter doctor -v
[✓] Flutter (Channel master, v1.8.4-pre.116, on Mac OS X 10.14.6 18G84, locale en-EE)
    • Flutter version 1.8.4-pre.116 at /Users/mlamp/_DEV/flutter
    • Framework revision 0564f0a812 (2 hours ago), 2019-08-06 20:08:09 +0200
    • Engine revision 7f67b9f0dc
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 8cd01287b4)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/mlamp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```
Also little demo: ![flutter_webview](https://user-images.githubusercontent.com/2169037/62573785-83ad6300-b89f-11e9-945c-a5406716c0c9.gif)

**Comment by amirh** [comment] 2019-08-06 22:29
Duplicate of https://github.com/flutter/flutter/issues/19718 
The keyboard support landed just recently and is not yet on stable, you can try switching to the master channel.
Note that the keyboard support is still experimental and there are a few known bugs (see the [README for the webview plugin](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/README.md#developers-preview-status)).
(and is still experimental with known bugs),

**Closed by amirh** 2019-08-06 22:29 UTC
Labels: f: material design, framework, p: webview
