### ISSUE TITLE
Print Navigator stack/history

### ISSUE THREAD

**Issue by moneer-muntazah** [flutter/flutter#70756] opened 2020-11-18 11:23 UTC
Hi everyone,

Is there a way to easily print the Navigator stack to check how many, and what routes you have on top of each other? If this is not built-in already it would be great for debugging.

Here is a similar request on stackoverflow

https://stackoverflow.com/questions/59401354/how-to-know-if-a-page-is-open-added-to-navigator-stack 

Thank you

**Comment by sidrao2006** [comment] 2020-11-18 13:52
Duplicate of #29317
Hey @moneer-muntazah , I found an open issue addressing this problem. Please post the output of `flutter doctor -v` and follow up there.

Thanks.

**Comment by moneer-muntazah** [comment] 2020-11-18 14:06
@sidrao2006 thank you so much I'll defiantly follow up. Here is my `flutter doctor -v` 

```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (5 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Moneer\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Moneer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\Moneer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Closed** 2020-11-18 14:07 UTC
