### ISSUE TITLE
ButtonTextTheme isn't coming through properly

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#29556] opened 2019-03-18 15:37 UTC
I believe this should render with a Yellow text color, but it renders with a blue one.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sandbox',
      theme: ThemeData(
        buttonTheme: ButtonThemeData(
          textTheme: ButtonTextTheme.primary,
        ),
        textTheme: TextTheme(
          button: TextStyle(color: Colors.red),
        ),
        primaryTextTheme: TextTheme(
          button: TextStyle(color: Colors.yellow),
        ),
        accentTextTheme: TextTheme(
          button: TextStyle(color: Colors.green),
        ),
      ),
      home: Scaffold(
        body: SafeArea(
          child: _Home(),
        ),
      ),
    );
  }
}

class _Home extends StatefulWidget {
  @override
  __HomeState createState() => __HomeState();
}

class __HomeState extends State<_Home> {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(28.0),
      child: Center(
        child: FlatButton(
          child: Text("weeee"),
          onPressed: () => null,
        ),
      ),
    );
  }
}
```

![IMG_7DE4847B50DA-1](https://user-images.githubusercontent.com/666539/54542458-3113ee80-4972-11e9-8bdb-571f363ddaff.jpeg)

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.10, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-02-26 14:44
Duplicate of [#29556](https://github.com/flutter/flutter/issues/29556)

**Closed by TahaTesser** 2020-02-26 14:44 UTC
Labels: f: material design, framework
