### ISSUE TITLE
problems with Decimal Calculation

### ISSUE THREAD

**Issue by SachinR90** [flutter/flutter#73021] opened 2020-12-28 07:39 UTC
I was doing some basic calculation in my app was getting wrong values. So, I tried the same in dartpad and and I think that there seems to be some issue in the dart itself. 

Example 1
```
void main() {
  var data = 5.1 * 100;
  print(data);
}
```

Expected : 510;
current: 509.99999999999994

<img width="1439" alt="Screenshot 2020-12-28 at 12 56 02 PM" src="https://user-images.githubusercontent.com/22074472/103197450-0ce98d80-490c-11eb-8f43-49f70f4b703b.png">

Example 2
```
void main() {
  var data = 5.2* 100;
  print(data);
}
```
Expected: 520
current: 520

<img width="1437" alt="Screenshot 2020-12-28 at 1 01 21 PM" src="https://user-images.githubusercontent.com/22074472/103197832-cb0d1700-490c-11eb-8966-9be6056d800f.png">

Note: Yes, I could round the result to get expected output in example 1,  but example 2 is not using any rounding method, and it still giving expected output.

Can anyone explain what is going wrong in 1st example?

**Comment by cmedamine** [comment] 2020-12-28 08:36
i think you could use .toStringasFixed to get the exact value, that's how I would solve that problem.

**Comment by pedromassangocode** [comment] 2020-12-28 10:31
Hi @SachinR90 
From what I can see, the issue is related to Dart language rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-28 10:31 UTC
