### ISSUE TITLE
flutter `windows.locales` always return extra `en_CN` as first item

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#38323] opened 2019-08-12 17:01 UTC
To find out current `Local`, I create a simple app to print current all `Local list`, but couldn't get it as expect.

## Steps to Reproduce

1. Create new flutter project.
2. Update `main.dart` file as bellow.(Just include `dart:ui`, and print `windows.locales`)
3. Print `window.locale` in `build()`.

```dart
import 'dart:ui';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var localList = window.locales;
    var local = window.locale;
    print(localList);  //<-- this
    print(local);      //<-- this

    return MaterialApp(
      title: 'Flutter Demo',
      home: Center(
        child: Text('Flutter Demo Home Page'),
      ),
    );
  }
}
```

Expected result would be show just same as `setting list`(only `2 items` in setting), but get extra `en_CN` at the beginning.

> flutter: [en_CN, `fr_CN, en_CN`]

> flutter: en_CN

> flutter: [en_CN, `en_CN, fr_CN`]

> flutter: en_CN

![Simulator Screen Shot - iPhone 7 - 2019-08-12 at 23 37 02](https://user-images.githubusercontent.com/6405390/63019607-6f381e80-bece-11e9-9034-80745acdea2c.png)![Simulator Screen Shot - iPhone 7 - 2019-08-12 at 23 49 06](https://user-images.githubusercontent.com/6405390/63019619-76f7c300-bece-11e9-8a4a-6baf3204652e.png)

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/jerryzhou/Documents/code/flutter/sdk/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jerryzhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (2 available)
    • iPhone   • 1daca728d75535c21ced151fc7829191064d0e00 • ios • iOS 12.4
    • iPhone 7 • C2F35BB6-9852-4D01-AFA4-DD1201A28154     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)
```

**Comment by jerryzhoujw** [comment] 2019-08-12 17:09
May related to https://github.com/flutter/flutter/issues/37404

**Comment by jerryzhoujw** [comment] 2019-08-12 17:12
If anyone can prove that the actual current `local` is aways the second one, I can use the second one as a solution...

**Comment by HansMuller** [comment] 2019-08-13 15:52
CC @GaryQian

**Comment by jerryzhoujw** [comment] 2019-08-13 19:07
May related to https://github.com/flutter/flutter/issues/38469 ?

**Comment by markusaksli-nc** [comment] 2020-08-13 12:15
Closing this for now since I can't reproduce it on Android and iOS on the latest master `1.21.0-8.0.pre.176`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.70, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.70 at C:\Development\flutter_master
    • Framework revision 0629030a05 (5 hours ago), 2020-08-13 00:01:03 -0400
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>
<details>
 <summary>Output</summary>

```
Performing hot restart...
Syncing files to device SM G950F...
Restarted application in 1,230ms.
I/flutter (12254): [en_GB, et_EE, en_CA, fr_CA]
I/flutter (12254): en_GB
I/flutter (12254): [en_GB, et_EE, en_CA, fr_CA]
I/flutter (12254): en_GB
```
</details>

Let me know if you still face this issue and I'll reopen.

**Closed by markusaksli-nc** 2020-08-13 12:15 UTC
Labels: a: internationalization, framework

**Comment by jerryzhoujw** [comment] 2020-10-20 07:15
Hi @markusaksli-nc 
After upgrade flutter from `stable 1.17.5` to  `stable 1.22.2`, this issue gone.
