### ISSUE TITLE
Make an autoroller update the Fuchsia toolchain.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#63581] opened 2020-08-12 16:29 UTC
From a Google internal thread, we've been asked to update the Fuchsia builds to use clang 12 and specific build flags discussed there.

May need help from the Dart team, too. 

cc @zanderso, @petrhosek who's on the Fuchsia thread.

**Comment by zanderso** [comment] 2020-08-12 16:54
The `dependency: dart` here is to indicate that flutter/engine and dart-lang/sdk will probably need to sync to the same, or at least nearby, toolchain versions.

**Comment by zanderso** [comment] 2020-08-12 19:34
I'm going to bump this to P2 because size will eventually block a release.

@chinmaygarde might be a bit swamped, so tentatively assigning @iskakaushik.

**Comment by zanderso** [comment] 2020-08-12 19:43
It looks like we have autorollers for these already:
https://autoroll.skia.org/r/fuchsia-linux-toolchain-flutter-engine
https://autoroll.skia.org/r/fuchsia-mac-toolchain-flutter-engine

Why were they stopped and not restarted?

**Comment by chinmaygarde** [comment] 2020-08-12 20:48
I believe the autoroller is running but it looks for updates at a spot that is no longer being updated. For example: https://chrome-infra-packages.appspot.com/p/fuchsia/clang/mac-amd64/+/ on Mac which has an update 9 months ago.

I believe the guidance of where to get these toolchains has changed since when these autorollers were first setup. I am not sure if we want to have a setup where the toolchains are updated constantly by an autoroller or just pick a blessed version of the toolchain.

Is there guidance on where to get this Clang 12? If so, we can trivially update the toolchain (and fix any new issues should they arise) and retires these rollers.

**Comment by chinmaygarde** [comment] 2020-08-12 20:49
> From a Google internal thread, we've been asked to update the Fuchsia builds to use clang 12

May I be CC-ed on this thread please? So we can figure out where these rollers live today.

**Comment by petrhosek** [comment] 2020-08-12 20:59
We have moved the toolchain to a new location: https://chrome-infra-packages.appspot.com/p/fuchsia/third_party/clang. @frobtech has already sent out a change to update the autoroller: https://skia-review.googlesource.com/c/buildbot/+/306357

**Comment by zanderso** [comment] 2020-08-12 21:16
@petrhosek @frobtech Ah, okay. It looks like that change landed, and the comments on that change indicate that a manual roll is needed for that change to work, but no one on the Flutter team was notified. So it looks like we should do that to get the autoroller started again, and we can use this issue to track.

**Comment by chinmaygarde** [comment] 2020-08-12 22:19
I am attempting a manual roll but there are a few breakages to address before it can land.

**Comment by chinmaygarde** [comment] 2020-08-17 17:46
The patch is out but there is [an ICU blocker](https://dart-review.googlesource.com/c/sdk/+/151505) that needs the be addressed before it can land.

**Comment by chinmaygarde** [comment] 2020-08-18 19:05
I am going to consult Martin about how to resolve the ICU issue when he is back later this week. If this is urgent, can patch ICU but not sure what impact this will have in the Dart buildroot.

**Comment by kf6gpe** [comment] 2020-09-14 22:32
It looks like the ICU blocker's landed. @chinmaygarde Do we want to try to land our PR, or am I missing something? Not urgent, but worth finishing. Thanks!

**Comment by Hixie** [comment] 2020-09-15 23:33
Clashing vacations made this drop through the cracks, but we expect to get back to it momentarily.

**Comment by kf6gpe** [comment] 2020-09-22 16:49
For Tuesday triage --- @chinmaygarde any update on landing the relevant PR yet?

**Comment by Hixie** [comment] 2020-09-29 23:32
(This will land after https://github.com/flutter/flutter/issues/59879.)

**Comment by chinmaygarde** [comment] 2020-10-05 17:47
Jason is going to attempt the ICU update that'll unblock the patch. Thanks!

**Comment by kf6gpe** [comment] 2020-10-06 18:35
Jason is actively debugging this roll now.

**Comment by jason-simmons** [comment] 2020-10-08 23:40
The ICU roll has landed.

**Comment by chinmaygarde** [comment] 2020-10-12 17:36
I will attempt to land the patch this week now that the ICU roll has been completed.

**Comment by chinmaygarde** [comment] 2020-10-19 18:02
I was busy with null-safety work last week. Depending on the work items remaining in that effort (the primary patch has landed already), I will get to this issue this week.

**Comment by chinmaygarde** [comment] 2020-11-02 19:04
Update: I attempted a roll but the flags changed in the meantime which require another buildroot update. We are going to keep running into this issue till we use a consistent compiler frontend for all platforms. I will attempt another buildroot update and attempt landing this again.

**Comment by kf6gpe** [comment] 2020-11-10 20:44
(for triage) @chinmaygarde --- did you get a chance to try the buildroot update yet? I am wondering if because the Fuchsia team hasn't come knocking if we should keep the milestone and drop this to a P3. WDYT?

**Comment by zanderso** [comment] 2020-11-10 21:46
They will eventually be blocked on this, so technically it should stay P2. The milestone we can probably shift out to the end of the quarter, though.

**Comment by chinmaygarde** [comment] 2020-11-10 23:21
Yes, this should stay P2. I am finding that the toolchain updates often (too often to be unattended in the versions I tried) need updates in various warning flags. Since these flags are in the buildroot, the updates are harder still. I am working to figure out how to unblock us on this.

**Comment by a-siva** [comment] 2020-12-02 20:37
Can we remove the dart-dependency label from this issue? not sure what is expected on the Dart side for this.

**Comment by zanderso** [comment] 2020-12-02 21:21
Reading the thread, it looks like the the dart-dependency label was intended to be a reminder to update the toolchain pulled by Dart as well. But to keep the engine toolchain and the Dart toolchain relatively similar, we'd probably want to avoid rolling the Dart toolchain until this issue is resolved.

**Comment by zanderso** [comment] 2020-12-11 15:51
This will be a blocker sooner than was expected, so bumping back up to P2.

**Comment by zanderso** [comment] 2021-01-11 18:14
@chaselatta I saw the toolchain roll was reverted. Will you be picking this back up?

**Comment by chaselatta** [comment] 2021-01-11 18:18
Yes, I have a fix which will land later today which will allow me to reapply the toolchain bump.

**Comment by chaselatta** [comment] 2021-01-13 22:37
The manual roll has landed. We still need to get the auto roller working again.

**Comment by chaselatta** [comment] 2021-01-25 18:53
Once https://github.com/flutter/engine/pull/23842 lands we will be using the fuchsia toolchain that is rolled into //buildtools instead of the one that is rolled into //src/fuchsia/toolchain. These two toolchains were coming from the same cipd bucket and using the same tag so there was no reason to keep them both.

**Comment by dnfield** [comment] 2021-01-25 22:41
https://skbug.com/11197 is going to repurpose the rollers to update the //buildtools, and everything should be happy.

**Closed** 2021-01-25 22:51 UTC
Labels: P4, customer: fuchsia, dependency: dart, engine, passed first triage, severe: new feature
