### ISSUE TITLE
webview_flutter_android flakily timed out when running integration tests in Firebase Test Lab

### ISSUE THREAD

**Issue by mvanbeusekom** [flutter/flutter#91012] opened 2021-09-30 07:31 UTC
- Approximate timestamp: 2021-09-30 02:35:33 (retrieved from logs)
- GitHub Action log: https://github.com/flutter/plugins/runs/3751079335
- Cirrus CI log: https://cirrus-ci.com/task/5020598427451392

```
BUILD SUCCESSFUL in 31s
81 actionable tasks: 15 executed, 66 up-to-date
Running command: "gcloud firebase test android run --type instrumentation --app build/app/outputs/apk/debug/app-debug.apk --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk --timeout 7m --results-bucket=gs://flutter_firebase_testlab --results-dir=plugins_android_test/webview_flutter_android/4707128108646400/22b275b8-4ecb-40e3-aeb9-2f4114e2f815/0/ --device model=flame,version=29 --device model=starqlteue,version=26" in /tmp/cirrus-ci-build/packages/webview_flutter/webview_flutter_android/example
┌─────────┬───────────────────────────┬──────────────────────┐
│ OUTCOME │      TEST_AXIS_VALUE      │     TEST_DETAILS     │
├─────────┼───────────────────────────┼──────────────────────┤
│ Failed  │ starqlteue-26-en-portrait │ Test timed out       │
│ Passed  │ flame-29-en-portrait      │ 16 test cases passed │
└─────────┴───────────────────────────┴──────────────────────┘
```

/cc @stuartmorgan, are you able to add relevant logs from FTL as I have no access?

**Comment by stuartmorgan** [comment] 2021-09-30 15:18
It's `The test timed out. The test ran longer than its maximum allowed duration, and was stopped.` so this is a duplicate of the recent comments in https://github.com/flutter/flutter/issues/86757

**Closed by stuartmorgan** 2021-09-30 15:18 UTC
Labels: platform-android, plugin, team: flakes, P3
