### ISSUE TITLE
payment webview not working with ios 

### ISSUE THREAD

**Issue by AzzamSuliman** [flutter/flutter#95831] opened 2021-12-26 21:01 UTC
Hello, 

I have a store application and I have integrated a payment gateway and everything works fine in Android, but when I ran the version on the iPhone, it does not work
There is a video explaining the problem

[video](https://ufile.io/sv8si9k5)

**Comment by darshankawar** [comment] 2021-12-27 09:48
Closing this as a duplicate of https://github.com/flutter/flutter/issues/93425

**Closed by darshankawar** 2021-12-27 09:48 UTC
Labels: in triage
