### ISSUE TITLE
Problems with using RichText in the Web

### ISSUE THREAD

**Issue by SongHuaixu** [flutter/flutter#62749] opened 2020-08-02 14:35 UTC
`
 Column(
      children: <Widget>[
        RichText(
          text: WidgetSpan(
            child: Container(
              child: Text("text"),
            ),
          ),
        ),
      ],
    );
`

```
flutter  --version
Flutter 1.21.0-6.0.pre.141 • channel master •
https://github.com/flutter/flutter.git
Framework • revision c748f1a7aa (2 days ago) • 2020-07-31 17:45:18 -0700
Engine • revision 280bbfc763
Tools • Dart 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)
```

<details>
<summary> Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following LateInitializationErrorImpl was thrown during performLayout():
LateInitializationError: Field '_placeholderCount' has not been initialized.

The relevant error-causing widget was: 
  RichText file:///Users/User/{MyAPP}/lib/mine_exam/mine_exam.dart:89:43
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49  throw_
lib/_engine/engine/text/paragraph.dart 1047:12                                get [_placeholderCount]
lib/_engine/engine/text/paragraph.dart 1046:31                                get placeholderCount
packages/flutter/src/widgets/widget_span.dart 110:19                          build
packages/flutter/src/painting/text_painter.dart 560:13                        layout
...
The following RenderObject was being processed when the exception was fired: RenderParagraph#f79ab relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=506.0, h=100.0)
...  size: MISSING
...  textAlign: start
...  textDirection: ltr
...  softWrap: wrapping at box width
...  overflow: clip
...  locale: en_US
...  maxLines: unlimited
  text: WidgetSpan#4ddce
    alignment: bottom
RenderObject: RenderParagraph#f79ab relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=506.0, h=100.0)
  size: MISSING
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
  text: WidgetSpan#4ddce
    alignment: bottom
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Assertion failed: file:///Users/User/flutter/packages/flutter/lib/src/rendering/box.dart:1713:12
hasSize
"RenderBox was not laid out: RenderParagraph#f79ab relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE"
The relevant error-causing widget was: 
  Container file:///Users/User/Documents/{MyAPP}/lib/mine_exam/mine_exam.dart:89:13
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Assertion failed: file:///Users/User/flutter/packages/flutter/lib/src/rendering/box.dart:1713:12
hasSize
"RenderBox was not laid out: RenderConstrainedBox#128f1 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE"
The relevant error-causing widget was: 
  Column file:///Users/User/{MyAPP}/lib/mine_exam/mine_exam.dart:64:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Assertion failed: file:///Users/User/flutter/packages/flutter/lib/src/rendering/box.dart:1713:12
hasSize
"RenderBox was not laid out: RenderFlex#983ac relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE"
The relevant error-causing widget was: 
  Scaffold file:///Users/User/{MyAPP}/lib/mine_exam/mine_exam.dart:61:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
'<Unexpected Null Value>'
method not found
Receiver: null
Arguments: []
The relevant error-causing widget was: 
  Column file:///Users/User/{MyAPP}/lib/mine_exam/mine_exam.dart:64:15
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
Assertion failed: file:///Users/User/flutter/packages/flutter/lib/src/rendering/box.dart:1713:12
hasSize
"RenderBox was not laid out: RenderPointerListener#6763f NEEDS-LAYOUT NEEDS-PAINT"
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
Assertion failed: file:///Users/User/flutter/packages/flutter/lib/src/rendering/mouse_tracking.dart:354:12
!_debugDuringDeviceUpdate
is not true
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by pedromassangocode** [comment] 2020-08-03 08:15
Hi @SongHuaixu 
Can you please provide  your `pubspec.yaml`.
Thank you

**Comment by SongHuaixu** [comment] 2020-08-03 10:32
> Hi @SongHuaixu
> Can you please provide your `pubspec.yaml`.
> Thank you



`
name: {MyAPPName}
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # see https://pub.flutter-io.cn/packages/convex_bottom_bar
  convex_bottom_bar: ^2.3.0
  flutter_snake_navigationbar: ^0.4.0+1
  flutter_icons: ^1.1.0
  flutter_mobx: ^1.1.0+1
  get_it: ^4.0.4
  flutter_keyboard_visibility: ^3.2.1
  keyboard_avoider: ^0.1.2
  intl: any
  shared_preferences: '>=0.5.8 <2.0.0'
  hive_flutter: ^0.3.1
  device_info: '>=0.4.2+4 <2.0.0'
  connectivity: '>=0.4.9 <2.0.0'
  package_info: '>=0.4.1 <2.0.0'
  provider: ^4.3.1
  path_provider: ^1.6.11
  location: ^3.0.2
  permission_handler: ^5.0.1+1
  share: '>=0.6.4+3 <2.0.0'
  webview_flutter: ^0.3.22+1
  flutter_html:
    git:
      url: https://github.com/zhaolinlins/flutter_html
  flutter_widget_from_html: ^0.4.2
  dio: ^3.0.9
  flutter_screenutil: ^2.3.1
  auto_size_text: ^2.1.0
  tree_view: ^0.0.5
  fluttertoast: ^7.0.2
  pull_to_refresh: ^1.6.1
  flutter_staggered_grid_view: ^0.3.2
  cached_network_image: ^2.2.0+1
  azlistview: ^0.1.2
  lpinyin: ^1.0.9
  flutter_easyloading: ^1.1.4
  photo_view: ^0.9.2
  flutter_picker: ^1.1.5
  image_picker: ^0.6.7+4
  image_picker_for_web: ^0.1.0+1
  multi_image_picker: ^4.7.10
  flutter_cupertino_date_picker:
    git:
      url: https://github.com/zhaolinlins/flutter-cupertino-date-picker
  flutter_bugly: ^0.2.8
  timer_builder: ^1.3.0
  flutter_custom_calendar:
    git:
      url: https://github.com/SongHuaixu/flutter_custom_calendar.git
  fijkplayer: ^0.8.7

  nested: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/data/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by mdebbar** [comment] 2020-08-03 19:55
Duplicate of https://github.com/flutter/flutter/issues/42086

**Closed by mdebbar** 2020-08-03 19:55 UTC
Labels: P3, a: null-safety, a: typography, found in release: 1.21, framework, has reproducible steps, platform-web, severe: crash
