### ISSUE TITLE
App is not loading in the browser with --machine argument

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#96548] opened 2022-01-12 20:27 UTC
Adding --machine argument to 'flutter run -d chrome --web-allow-expose-url' causes the hello world app not to load in the browser.

flutter doctor -v: 

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.322, on macOS 12.1 21C52
    darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.322 at
      /Users/annagrin/source/flutter/flutter
    • Upstream repository git@github.com:annagrin/flutter.git
    • Framework revision 9490917408 (25 hours ago), 2022-01-11 13:00:12
      -0600
    • Engine revision a79a3bac0c
    • Dart version 2.16.0 (build 2.16.0-154.0.dev)
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    • Android SDK at /Users/annagrin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more
      details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup
      for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.1 21C52
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome
      97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment] 2022-01-13 07:45
@annagrin Hi,

Although I didn't try `hello world` app, but tried another sample below (code below) and ran it using `flutter run -d chrome --machine` that compiled and loaded properly:

```
dhs@Dhss-MacBook-Pro ios_bug % flutter run -d chrome --machine
[{"event":"daemon.connected","params":{"version":"0.6.1","pid":11065}}]
[{"event":"app.start","params":{"appId":"304da99a-f3d8-4a62-8d4b-22011f34d835","deviceId":"chrome","directory":"/Users/dhs/Documents/NCFlutter/ios_bug","supportsRestart":true,"launchMode":"run"}}]
Launching lib/main.dart on Chrome in debug mode...
[{"event":"app.progress","params":{"appId":"304da99a-f3d8-4a62-8d4b-22011f34d835","id":"0","progressId":null,"message":"Waiting for connection from debug service on Chrome...","finished":false}}]
[{"event":"app.progress","params":{"appId":"304da99a-f3d8-4a62-8d4b-22011f34d835","id":"0","progressId":null,"finished":true}}]
[{"event":"app.webLaunchUrl","params":{"url":"http://localhost:50836","launched":true}}]
This app is linked to the debug service: ws://127.0.0.1:50860/1RA6SQuvi1s=/ws
Debug service listening on ws://127.0.0.1:50860/1RA6SQuvi1s=/ws

💪 Running with sound null safety 💪
[{"event":"app.started","params":{"appId":"304da99a-f3d8-4a62-8d4b-22011f34d835"}}]
[{"event":"app.debugPort","params":{"appId":"304da99a-f3d8-4a62-8d4b-22011f34d835","port":50860,"wsUri":"ws://127.0.0.1:50860/1RA6SQuvi1s=/ws"}}]

```

<img width="740" alt="Screenshot 2022-01-13 at 1 12 39 PM" src="https://user-images.githubusercontent.com/67046386/149287062-41177109-84df-402b-9b33-e7867bc3d922.png">


```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.333, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] VS Code (version 1.62.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

<details>

<summary> code sample </summary>

```

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      appBar: AppBar(
        title: Text(title),
      ),
      body: Column(
        children: [
          const CheckboxWithLabel(onChanged: null),
        ],
      ),
    );

  }
}

class CheckboxWithLabel extends StatelessWidget {
  const CheckboxWithLabel({Key? key, required this.onChanged})
      : super(key: key);
  final ValueChanged<bool?>? onChanged;

  bool get enabled => onChanged != null;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      checked: true,
      button: true,
      enabled: enabled,
      label: "Test",
      excludeSemantics: true,
      child: Row(
        children: [
          Checkbox(
            value: true,
            onChanged: onChanged,
          ),
          const Text("Test"),
        ],
      ),
    );
  }
}

```

</details>

**Comment by annagrin** [comment] 2022-01-13 20:08
Handing off my investigation to @christopherfujino:

- This is only called with both arguments present and never finishes: https://github.com/flutter/flutter/blob/df384c4809c5fe21773b6d9d5c8ac4b3b382df5f/packages/flutter_tools/lib/src/commands/daemon.dart#L371
- Which causes the following to hang:
https://github.com/dart-lang/webdev/blob/a0c010d0a80542e881e93ac4862552f95d872c6b/dwds/lib/dwds.dart#L156

Looks like the problem resides in the flutter daemon.

**Comment by darshankawar** [comment] 2022-01-14 05:31
Thanks for the update. I do see the same behavior using additional flags as mentioned.

<img width="802" alt="Screenshot 2022-01-14 at 11 00 09 AM" src="https://user-images.githubusercontent.com/67046386/149456842-de10fe2c-4fe5-42f7-af9d-452139bf3cbd.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.9.0-1.0.pre.363, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.363 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e9a728667 (4 hours ago), 2022-01-14 09:40:11 +0800
    • Engine revision f121c1fe68
    • Dart version 2.17.0 (build 2.17.0-11.0.dev)
    • DevTools version 2.9.2
    
[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!


```

</details>

**Comment by annagrin** [comment] 2022-01-21 21:56
Assigning priority to match the original issue: https://github.com/flutter/flutter/issues/95916

**Comment by zanderso** [comment] 2022-01-25 17:23
Routing to @DanTup who added the `--web-allow-expose-url` functionality in https://github.com/flutter/flutter/commit/4944622b5d8e7a8ee5dbf658b0d0e8ab94b8efd3

**Comment by DanTup** [comment] 2022-01-25 17:28
@annagrin how/where are you running this? `--web-allow-expose-url` is an indication to the daemon that the client (eg. VS Code) can handle reverse-requests from the daemon to the client that can expose URLs (eg. in the case of using VS Code remoting or some cloud IDE, where the Flutter tool has a URL like http://localhost:1234/ but needs to know that it should be exposed to the user as `https://some-cloud-service.foo/`).

The only place it generally makes sense to pass `--web-allow-expose-url` is in the VS Code debug adapter (or any other editor that handles this - although I don't know any).

**Comment by christopherfujino** [comment] 2022-01-25 17:53
> @annagrin how/where are you running this? `--web-allow-expose-url` is an indication to the daemon that the client (eg. VS Code) can handle reverse-requests from the daemon to the client that can expose URLs (eg. in the case of using VS Code remoting or some cloud IDE, where the Flutter tool has a URL like http://localhost:1234/ but needs to know that it should be exposed to the user as `https://some-cloud-service.foo/`).
> 
> The only place it generally makes sense to pass `--web-allow-expose-url` is in the VS Code debug adapter (or any other editor that handles this - although I don't know any).

So this was broken out from https://github.com/flutter/flutter/issues/95916, where we are seeing in crash logging the invocation: `flutter run --machine --start-paused -d chrome --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib\main.dart`

**Comment by DanTup** [comment] 2022-01-25 17:57
Ah, I see. I suspect that flag is not related to the crash and probably safe to just ignore. VS Code pretty much always passes it (although if it's confusing to have it always show up, I could change it to only pass it when running in a remote environment which might make it clearer if/when the issue is unrelated to that).

**Comment by christopherfujino** [comment] 2022-04-12 21:49
> Ah, I see. I suspect that flag is not related to the crash and probably safe to just ignore. VS Code pretty much always passes it (although if it's confusing to have it always show up, I could change it to only pass it when running in a remote environment which might make it clearer if/when the issue is unrelated to that).

@DanTup can you reproduce Anna's finding from https://github.com/flutter/flutter/issues/96548#issuecomment-1012342739 ?

**Comment by DanTup** [comment] 2022-04-21 14:52
Sorry for the delay. I'm not sure I understand the problem. It is expected that running `--machine --web-allow-expose-url` won't work correctly from the command line, as these flags enable some functionality that allows flutter_tools to ask the IDE to expose ports through a firewall/proxy. When you run like this, you'll see something like this in the output:

```
[{"id":"1","method":"app.exposeUrl","params":{"url":"ws://127.0.0.1:54707/$debug"}}]
```

This is flutter_tools asking the IDE to expose `ws://127.0.0.1:54707/$debug` and return the the public exposed URL. The IDE would call an API in its host/infrastructure (for example a VS Code/GitPod/CloudShell API) and respond by providing a public URL that has been tunnelled to that port, something like `wss://970-1cbe2e3a-ae67-40e1-340e-2253854745c5.europe-west1.cloudshell.dev/$debug`).

So whether there's an issue in this functionality depends on where the original report came from. If it's someone running in VS Code, something may be broken. If it was just running from a terminal trying to reproduce something by using a command from a log (or such), then it might be a red herring.

**Comment by annagrin** [comment] 2022-04-25 19:27
I believe the original issue comes from user data - @christopherfujino I think you mentioned that it is the top failure? I am not familiar with how this command is run, just tried to investigate it in case something is wrong with dwds. @dantup who would be the best person to take this on?

**Comment by DanTup** [comment] 2022-04-25 19:47
> @DanTup who would be the best person to take this on?

I'm not sure without understanding what the original report is. If this has come from crash reports or something, is there some error/stack trace? If the error came from a user reporting something not working, are there any more details? (if they're running this command from a terminal, it's expected not to work if they don't respond as an IDE would, but if they're running it from VS Code and it's not working, [some logs](https://dartcode.org/docs/logging/#capture-debugging-logs) would help).

**Comment by annagrin** [comment] 2022-04-25 20:21
@christopherfujino could you please help getting this information? I believe the reports are from running in the IDE but that's all I know.

**Comment by christopherfujino** [comment] 2022-04-25 20:56
> Sorry for the delay. I'm not sure I understand the problem. It is expected that running `--machine --web-allow-expose-url` won't work correctly from the command line, as these flags enable some functionality that allows flutter_tools to ask the IDE to expose ports through a firewall/proxy. When you run like this, you'll see something like this in the output:
> 
> ```
> [{"id":"1","method":"app.exposeUrl","params":{"url":"ws://127.0.0.1:54707/$debug"}}]
> ```
> 
> This is flutter_tools asking the IDE to expose `ws://127.0.0.1:54707/$debug` and return the the public exposed URL. The IDE would call an API in its host/infrastructure (for example a VS Code/GitPod/CloudShell API) and respond by providing a public URL that has been tunnelled to that port, something like `wss://970-1cbe2e3a-ae67-40e1-340e-2253854745c5.europe-west1.cloudshell.dev/$debug`).
> 
> So whether there's an issue in this functionality depends on where the original report came from. If it's someone running in VS Code, something may be broken. If it was just running from a terminal trying to reproduce something by using a command from a log (or such), then it might be a red herring.

Ahh thanks, that makes sense. Given this, I will close this issue, and I still have https://github.com/flutter/flutter/issues/95916 assigned to me. Thanks @annagrin and @DanTup

**Closed by christopherfujino** 2022-04-25 20:56 UTC
Labels: tool, platform-web, has reproducible steps, P3, found in release: 2.8, found in release: 2.9
