### ISSUE TITLE
[tool_crash] OSError: OS Error: Can't assign requested address, errno = 49

### ISSUE THREAD

**Issue by zhaoyangyang123** [flutter/flutter#137021] opened 2023-10-21 16:01 UTC
## Command
```
flutter --no-color attach --machine --device-id=00008030-00092D542684802E lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OSError: OS Error: Can't assign requested address, errno = 49
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1699:74)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1595:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2527:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:145:16)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:63:7)
<asynchronous suspension>
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:52)
<asynchronous suspension>
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:277:11)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:224:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 14.0 23A344 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/zhaoyangyang68/Desktop/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (1 year, 3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/zhaoyangyang68/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • 赵扬扬测试机iPhone (mobile) • 00008030-00092D542684802E • ios            • iOS 17.0.3 21A360
    • macOS (desktop)       • macos                     • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 118.0.5993.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.my_flutter
**iOS bundle identifier**: com.example.myFlutter
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1

**Comment by darshankawar** [comment] 2023-10-23 07:39
Closing as duplicate of https://github.com/flutter/flutter/issues/97489

**Closed by darshankawar** 2023-10-23 07:39 UTC
Labels: in triage
