### ISSUE TITLE
Adding a flutter_test_config.dart triggers an error in a flutter generated test file (Method not found: 'testExecutable')

### ISSUE THREAD

**Issue by llucax** [flutter/flutter#72801] opened 2020-12-22 13:48 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. `echo 'import "dart:async"; Future<void> main(FutureOr<void> Function() testMain) async => testMain();' > test/flutter_test_config.dart`
3. `flutter test`

**Expected results:** Tests pass

**Actual results:** Exception is thrown at a ` flutter test` generated file: `../../flutter_tools.LYDATW/flutter_test_listener.TGHCDI/listener.dart:45:18: Error: Method not found: 'testExecutable'.`

This method was introduced in https://github.com/flutter/flutter/pull/67425/commits/982be1510db609dc7b69d3365a56ba370a13d1ba by @jonahwilliams so I guess it might be related to that commit or #67425 in general.

<details>
  <summary>Logs</summary>

```console
$ flutter test --verbose
[  +57 ms] executing: [/home/luca/software/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8f89f6505b941329a864fef1527243a72800bf4d
[        ] executing: [/home/luca/software/flutter/] git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[  +13 ms] Exit code 0 from: git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[        ] 1.25.0-8.1.pre
[  +31 ms] executing: [/home/luca/software/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/luca/software/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +38 ms] executing: [/home/luca/software/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +46 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +40 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +54 ms] Skipping pub get: version match.
[  +78 ms] Found plugin integration_test at /home/luca/software/flutter/packages/integration_test/
[ +113 ms] Found plugin integration_test at /home/luca/software/flutter/packages/integration_test/
[   +5 ms] Generating /home/luca/devel/flutter/bug9/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +33 ms] switching to directory LocalDirectory: 'test' to run tests
[        ] running test package with arguments: [-r, compact, --timeout, 30s, --concurrency=6, --, /home/luca/devel/flutter/bug9/test/widget_test.dart]
00:00 +0: loading /home/luca/devel/flutter/bug9/test/widget_test.dart                                                                                    [ +153 ms] test 0: starting test /home/luca/devel/flutter/bug9/test/widget_test.dart
[  +18 ms] test 0: starting shell process
[   +4 ms] Discovered flutter_test_config.dart in /home/luca/devel/flutter/bug9/test
[   +2 ms] Compiler will use the following file as its incremental dill file: /tmp/flutter_tools.BKKFMR/flutter_test_compiler.AECKON/output.dill
[        ] Listening to compiler controller...
[   +1 ms] Compiling file:///tmp/flutter_tools.BKKFMR/flutter_test_listener.IQFVPX/listener.dart
[   +6 ms] /home/luca/software/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/luca/software/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/luca/software/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --no-print-incremental-dependencies --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.BKKFMR/flutter_test_compiler.AECKON/output.dill --packages
/home/luca/devel/flutter/bug9/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--initialize-from-dill /home/luca/devel/flutter/bug9/build/test_cache/build/cache.dill.track.dill
[  +13 ms] <- compile file:///tmp/flutter_tools.BKKFMR/flutter_test_listener.IQFVPX/listener.dart
00:01 +0: loading /home/luca/devel/flutter/bug9/test/widget_test.dart                                                                                    [+1764 ms] /tmp/flutter_tools.BKKFMR/flutter_test_listener.IQFVPX/listener.dart:45:18: Error: Method not found: 'testExecutable'.
[   +2 ms]     return () => test_config.testExecutable(test.main);
[        ]                  ^^^^^^^^^^^^^^
00:06 +0: loading /home/luca/devel/flutter/bug9/test/widget_test.dart                                                                                    [+4491 ms] killing pid 378584
[   +2 ms] test 0: cleaning up...
[        ] test 0: deleting temporary directory
[   +6 ms] test 0: shutting down test harness socket server
00:06 +0 -1: loading /home/luca/devel/flutter/bug9/test/widget_test.dart [E]                                                                             
  Failed to load "/home/luca/devel/flutter/bug9/test/widget_test.dart":
  Compilation failed
  Test: /home/luca/devel/flutter/bug9/test/widget_test.dart
  Shell: /home/luca/software/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester
  
  
00:06 +0 -1: Some tests failed.                                                                                                                          
[  +24 ms] Deleting /tmp/flutter_tools.BKKFMR/flutter_test_compiler.AECKON...
[   +5 ms] killing pid 378584
[        ] test 0: waiting for controller sink to close
[  +29 ms] Compiling /tmp/flutter_tools.BKKFMR/flutter_test_listener.IQFVPX/listener.dart took 6347ms
[   +3 ms] test package returned with exit code 1
[   +7 ms] "flutter test" took 6,883ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:306:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>
           
           
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

```console
$ flutter analyze 
Analyzing bug9...                                                       
No issues found! (ran in 1.4s)
```

```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Linux, locale en_IE.UTF-8)
    • Flutter version 1.25.0-8.1.pre at /home/luca/software/flutter
    • Framework revision 8f89f6505b (7 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/luca/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/luca/software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Android Studio
    • Android Studio at /home/luca/software/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/luca/software/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • LG H870 (mobile) • LGH8701d9f7a4 • android-arm64  • Android 9 (API 28)
    • Chrome (web)     • chrome        • web-javascript • Chromium 83.0.4103.116 built on Debian bullseye/sid, running on Debian bullseye/sid

• No issues found!
```

</details>

**Comment by llucax** [comment] 2020-12-22 13:54
In case it helps, here is the test case with a GH Action configured to test it in stable, beta and dev channels:

**Comment by llucax** [comment] 2020-12-22 14:11
It fails in dev too, to make it work in stable I had to [remove `inteagration_test` from the `dev_dependencies`](https://github.com/llucax/flutter-bug-72801/commit/8a2fb1f1fc9380f5160f783b1a1ea4514ecdb087) because is not part of the SDK in stable (I created the project in beta) and [remove `cupertino_icons` from the `dependencies`](https://github.com/llucax/flutter-bug-72801/commit/31e986fc22df09089c104dc56902edf4e73cf964) because is not really needed and cupertino_icons >=1.0.1 requires SDK version >=2.12.0-0 <3.0.0, and this doesn't work in stable.

Here is the latest action run: https://github.com/llucax/flutter-bug-72801/actions/runs/438188527

**Comment by darshankawar** [comment] 2020-12-23 06:26
Issue replicable on latest master.

```
dhs@Dhss-MacBook-Pro ncflutter % cd bug
dhs@Dhss-MacBook-Pro bug % echo 'import "dart:async"; Future<void> main(FutureOr<void> Function() testMain) async => testMain();' > test/flutter_test_config.dart
dhs@Dhss-MacBook-Pro bug % flutter test
00:02 +0: ... /Users/dhs/Documents/NCFlutter/bug/test/widget_test.dart         /var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/flutter_tools.oC6C2I/flutter_te
st_listener.SvQiGU/listener.dart:45:18: Error: Method not found:
'testExecutable'.
    return () => test_config.testExecutable(test.main);
                 ^^^^^^^^^^^^^^
00:06 +0 -1: loading /Users/dhs/Documents/NCFlutter/bug/test/widget_test.dart [E]
  Failed to load "/Users/dhs/Documents/NCFlutter/bug/test/widget_test.dart":
  Compilation failed
  Test: /Users/dhs/Documents/NCFlutter/bug/test/widget_test.dart
  Shell: /Users/dhs/documents/Fluttersdk/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester
  
  
00:06 +0 -1: Some tests failed.                                                
dhs@Dhss-MacBook-Pro bug % 

```

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.26.0-2.0.pre.117, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.117 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 15c009b805 (5 hours ago), 2020-12-22 20:09:03 -0500
    • Engine revision b7cd3f8e70
    • Dart version 2.12.0 (build 2.12.0-173.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

</details>

**Comment by nwparker** [comment] 2020-12-24 04:50
I'm also experiencing this issue for any arbitrary test

We might want to rename this issue to indicate as such. It doesn't seem to be related to the test being `flutter_test_config.dart` or anything config related.

**Comment by DeividWillyan** [comment] 2021-01-14 13:28
I have the same problem in a project containing tests, it worked normally in channel stable, now in channel beta (I need to run integration test via browser), I face the same problem.

` /var/folders/jf/j1m5rfgs4vgdrw_0h_lk6w8r0000gp/T/flutter_tools.AcnEjs/flutter_test_listener.Soai0m/listener.dart:45:18: Error: Method not
found: 'testExecutable'.
    return () => test_config.testExecutable(test.main);
                 ^^^^^^^^^^^^^^`
                 
                 
 <details>
 <summary>
 flutter doctor -v
  </summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.4 19E287 darwin-x64, locale pt-BR)
    • Flutter version 1.25.0-8.2.pre at /Users/deivid.fabiano/Development/Flutter/flutter
    • Framework revision b0a2299859 (9 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/deivid.fabiano/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/deivid.fabiano/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deivid.fabiano/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

  </details>

**Comment by jonahwilliams** [comment] 2021-01-14 17:54
The example you've provided is not valid dart code. A function named main cannot accept an arbitrary function as its first parameter. Instead you need to something like 

```dart

Future<void> testExecutable(FutureOr<void> Function() cb) async {  cb() }
```

If you're experiencing this other please share the contents of flutter_test_config.dart

**Comment by DeividWillyan** [comment] 2021-01-14 18:19
> The example you've provided is not valid dart code. A function named main cannot accept an arbitrary function as its first parameter. Instead you need to something like
> 
> ```dart
> Future<void> testExecutable(FutureOr<void> Function() cb) async {  cb() }
> ```
> 
> If you're experiencing this other please share the contents of flutter_test_config.dart

@jonahwilliams 
Its functional solution very well for channel beta, however it stopped working so it will be using stable, but in my context (I need web flutter) I will continue with the channel beta.
So all my tests are back up and running. Thank you very much.

Obs:
Channel stable 
```dart
Future<void> main(FutureOr<void> Function() testMain) async {  testMain() }

**Comment by llucax** [comment] 2021-01-18 17:41
@jonahwilliams Thanks for the clarification, but the example I provided works in stable and is actually in the [official Flutter documentation](https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html). It is also used in some other widely used packages (like [goldens](https://pub.dev/packages/golden_toolkit#loading-fonts)). Also there is almost no way to know what went wrong from the error message or how to fix the issue, so no clear upgrade path.

So I guess this is a (yet undocumented) breaking change introduced in recent versions of Dart (used in beta and above), right?

I'm not familiar with Flutter/Dart development process, so maybe this is coming and just not available yet, but It would be good to get better error reporting (with a clear suggestion on how to fix the code) if possible, and updated documentation and migration instructions for users using the old broken `main`.

**Comment by matthew-carroll** [comment] 2021-02-07 21:33
The following comes from the `flutter_test` API documentation:

> Before a test file is executed, the Flutter test framework will scan up the directory hierarchy, starting from the directory in which the test file resides, looking for a file named flutter_test_config.dart. If it finds such a configuration file, the file will be assumed to have a main method with the following signature:
> Future<void>` main(FutureOr<void> testMain());
> The test framework will execute that method and pass it the main() method of the test. It is then the responsibility of the configuration file's main() method to invoke the test's main() method.

https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html

A few months ago, in a previous project, I had a `flutter_test_config.dart` that worked as described in the docs. I just tried to setup the exactly same kind of behavior in my current project and I'm getting the failure documented in this issue.

**Comment by matthew-carroll** [comment] 2021-02-07 21:39
Ok, after a little bit of playing around I see what this error is trying to say.

The docs say that the method should be called:
`Future<void> main(FutureOr<void> testMain()) {...}`

Apparently a change was made and it should actually be called:
`Future<void> testExecutable(FutureOr<void> testMain()) {...}`

Maybe this was clear to others on this thread, but it wasn't clear to me at all. Changing this name fixed my current project. My guess is that any existing project that was using the approach in the API docs will require a change to work again.

**Action Items**

- Someone should update the API docs accordingly
- @goderbauer did this constitute a breaking change? If so, did it sneak under the radar?

**Comment by goderbauer** [comment] 2021-02-09 18:33
> Someone should update the API docs accordingly

Looks like this is already fixed on master (https://master-api.flutter.dev/flutter/flutter_test/flutter_test-library.html).

> @goderbauer did this constitute a breaking change? If so, did it sneak under the radar?

@jonahwilliams You indicated in https://github.com/flutter/flutter/pull/67425#issuecomment-704518560 that this was breaking google3, which would constitute a breaking change. Did you follow https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes? Can you link to the migration guide?

**Comment by alberto-sf** [comment] 2021-02-26 10:06
We have encountered this issue as well yesterday when we migrated to `beta` in order to start working on null-safety. Our `flutter_test_config.dart` file looked like this:

```dart
Future<void> main(FutureOr<void> Function() testMain) async {
  setUpAll(() async {
    await loadAppFonts();
  });

  return testMain();
}
```

As @matthew-carroll said, I tried to change the name of the method to `testExecutable` but it still doesn't work. If it could be helpful, on the (currently) stable channel we don't have this issue but it pops out as soon as we move to `beta`. This is the error:

> /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/flutter_tools.R3teXi/flutter_test_listener.0GpykM/listener.dart:45:18: Error: Method not found: 'testExecutable'.
>     return () => test_config.testExecutable(test.main);
>                  ^^^^^^^^^^^^^^

**Comment by MiguelSOliveira** [comment] 2021-03-05 20:42
Having this error when migrating to flutter 2.

Replacing the "main" method for "testExecutable", appears to have worked for me.

**Comment by alberto-sf** [comment] 2021-03-09 14:18
I can confirm that in Flutter 2.x using `testExecutable` instead of `main` works! It's just a matter of updating the official doc and maybe pointing this out in a migration doc

**Comment by darshankawar** [comment] 2023-05-09 10:49
Verified this issue and confirmed that using below code snippet, it works as expected as also documented here: https://master-api.flutter.dev/flutter/flutter_test/flutter_test-library.html

`echo 'import "dart: async"; Future<void> testExecutable(FutureOr<void> Function() testMain) async { testMain(); }`

```
dhs@Dhss-MacBook-Pro issue_bug % flutter test
No tests ran.                                                                   
No tests were found.
dhs@Dhss-MacBook-Pro issue_bug % 
```

I'll optimistically close this issue as fixed. If anybody disagrees, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-05-09 10:49 UTC
Labels: a: tests, tool, passed first triage, has reproducible steps, P4, found in release: 1.26
