### ISSUE TITLE
build flutter web error

### ISSUE THREAD

**Issue by a97077088** [flutter/flutter#40679] opened 2019-09-17 15:00 UTC
Launching lib\main.dart on Chrome in debug mode...
Building application for the web...
Skipping compiling nongyue|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

image_picker|lib/image_picker.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings

**Comment by BondarenkoStas** [comment] 2019-09-17 17:49
Duplicate of #39998.
As image_picker imports dart:io from Dart SDK which is not supported in flutter web. Please try #40341 (comment) and report if that will help.

**Closed by BondarenkoStas** 2019-09-17 17:49 UTC
