### ISSUE TITLE
Crash of card_collection example by checking "Make card labels editable"

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#833] opened 2015-12-09 10:23 UTC
(flutter version: 4472d06e022cd5fb604c83a850ff20d54073906b)

STEPS TO REPRODUCE:
1. Run `examples/widgets/card_collection.dart`
2. Open the drawer
3. Check _Make card labels editable_

```
android: F/flutter : [FATAL:jni_android.cc(249)] Check failed: false. Please include Java exception stack in crash report
android: --------- beginning of crash
android: F/libc    : Fatal signal 6 (SIGABRT), code -6 in tid 12990 (mokit.sky.shell)
android: W/ActivityManager:   Force finishing activity 1 org.domokit.sky.shell/.SkyActivity
android: W/ActivityManager: Exception thrown during pause
android: W/ActivityManager: android.os.DeadObjectException
android: W/ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
android: W/ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:496)
android: W/ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
android: W/ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
android: W/ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2726)
android: W/ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2583)
android: W/ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2497)
android: W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11505)
android: W/ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11402)
android: W/ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12086)
android: W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11597)
android: W/ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

**Comment by Hixie** [comment] 2015-12-28 22:22
Dupe of #964.

**Closed by Hixie** 2015-12-28 22:22 UTC
Labels: affects: engine, affects: framework, affects: text input, customer: demos, ⚠ crash
