### ISSUE TITLE
Flutter child props is changing parent variable.

### ISSUE THREAD

**Issue by dooboolab** [flutter/flutter#21358] opened 2018-09-03 11:09 UTC
I am having trouble with data syncing in flutter with parent Widget and child Widget.

----------------
1. In parent StatefulWidget, I have lists like below image.
<img width="357" alt="screen shot 2018-09-03 at 8 04 05 pm" src="https://user-images.githubusercontent.com/27461460/44983615-bde9f280-afb4-11e8-9684-9f0ee1c79a15.png">

code:
```
Navigator.of(context).push(
  MaterialPageRoute(builder:
    (context) =>TripUpdate(
      key: Key('trip_update'),
      trip: _trip, /// trip data
    ),
  )
);
```

----------------
2. In child StatefulWidget, I am handling data to update.
<img width="362" alt="screen shot 2018-09-03 at 8 04 19 pm" src="https://user-images.githubusercontent.com/27461460/44983618-c0e4e300-afb4-11e8-955f-08c72c0e53a7.png">

code: 
```
/// just set variable in TextField
onChanged: (String str) {
  _trip.name = str;
},
```

----------------
3. If I don't click the `save` button in child widget, I don't want to update the variable but it updates whenever I change a variable from child widget. Is this normal?
<img width="357" alt="screen shot 2018-09-03 at 8 04 25 pm" src="https://user-images.githubusercontent.com/27461460/44983620-c2161000-afb4-11e8-928f-1fa59d9a6347.png">

----------------
flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.26.1)
[✓] Connected devices (3 available)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-09-03 11:57
Can you please post a runnable minimal reproduction? (main.dart)

**Comment by dooboolab** [comment] 2018-09-03 12:42
@zoechi 
I've just created full code here.

```
import 'package:flutter/material.dart';

import '../utils/theme.dart' as Theme;
import '../utils/general.dart';

class Trip {
  String id;
  String name;
  Trip(this.id, this.name);
}

class ExListViewChildView extends StatefulWidget {
  ExListViewChildView({Key key}) : super(key: key);

  @override
  ExListViewChildViewState createState() => new ExListViewChildViewState();
}

class ExListViewChildViewState extends State<ExListViewChildView> {
  List<Trip> list = new List();
  @override
  void initState() {
    super.initState();
    list.add(Trip('', 'TRIP 1'));
    list.add(Trip('', 'TRIP 2'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverFixedExtentList(
            itemExtent: 100.0,
            delegate: SliverChildBuilderDelegate(
                  (BuildContext context, int index) {
                return Container(
                  margin: EdgeInsets.only(top: 8.0),
                  child: Column(
                    children: <Widget>[
                      Container(
                        child: Column(
                          children: <Widget>[
                            Text(this.list[index].name),
                            Container(
                              child: FlatButton(
                                child: Text('press'),
                                onPressed: () {
                                  Navigator.of(context).push(
                                      MaterialPageRoute(builder:
                                          (context) => TripUpdate(
                                        trip: list[index],
                                      ),
                                      )
                                  );
                                },
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                );
              },
              childCount: list.length,
            ),
          ),
        ],
      ),
    );
  }
}

/// child view
class TripUpdate extends StatefulWidget {
  final Trip trip;
  TripUpdate({Key key, @required this.trip}) : super(key: key);

  @override
  TripUpdateState createState() => new TripUpdateState(trip);
}

class TripUpdateState extends State<TripUpdate> {
  final Trip trip;
  TripUpdateState(this.trip);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('TripUpdate'),
      ),
      body: Container(
        child: Column(
          children: <Widget>[
            Text('textfield'),
            TextField(
              onChanged: (String str) {
                this.trip.name = str;
              },
            )
          ],
        ),
      ),
    );
  }
}
```

Output is below.
![lwcm2ud2bk](https://user-images.githubusercontent.com/27461460/44987449-37d4a880-afc2-11e8-849c-de6dbd8ce9e8.gif)

**Comment by zoechi** [comment] 2018-09-03 12:49
I don't really understand the question.
There is no save button in the code.
If you don't want to update, don't do `this.trip.name = str;`

**Comment by dooboolab** [comment] 2018-09-03 12:50
@zoechi Yes. But somehow the ui represents things based on the variables. In `react-native` passed props won't update parent variable.

**Comment by zoechi** [comment] 2018-09-03 12:55
If you pass primitives (String, int, double, bool), they are copied per value and changes to such a variable are not reflected to other variables that held the value before.
If you pass a value of any other type, they are passed as reference and changes to properties of them change it everywhere else with a reference to the same instance.

I don't know react-native, but Darts behavior is quite common among object-oriented languages and Flutter doesn't do anything to prevent that. 

Closing as working as intended. 
Feel free to add follow-up questions.

**Closed by zoechi** 2018-09-03 12:55 UTC

**Comment by dooboolab** [comment] 2018-09-03 15:26
Could someone discuss this with me? I feel this is critical. dart doesnt even support deep clone for object. We need to fetch extra dummy data to handle this kind of senario..

**Comment by zoechi** [comment] 2018-09-03 15:40
Not sure what to suggest or discuss.
There is no good standard way for cloning objects, this is why Dart doesn't provide one.
Either you implement `clone` yourself in the classes where you need it or
you can for example use https://pub.dartlang.org/packages/built_value which generates immutable classes where modifications lead to new instances.

**Comment by srikanthgoud138** [comment] 2019-06-28 07:19
Same issue, **when we change the child class variable value, it is also changing the parent class variable value.**
Badly need some help,
Thank u

**Comment by deepakrajv** [comment] 2020-04-29 10:34
Same issue. When we change the child StatefulWidget variable passed from parent, it is also changing the parent StatefulWidget variable value.

**Comment by thilva** [comment] 2020-07-20 19:29
same issue. When changing the child class variable value, it also changes parent class variable value. i need help very badly, please help

**Comment by SmiffyKMc** [comment] 2021-01-25 11:08
I'm have the same issue, it doesn't really make sense to change the values of the list item. What if the user went in to make a change but decided against it, goes back and still sees the change? 

What do you propose so as Android as a technology doesn't do this?

**Comment by hyochan** [comment] 2021-01-25 16:10
Happy that people are coming and now having a discussion. Very long time waiting!
Looks like we need an alternative to [Parcelable in android](https://developer.android.com/reference/android/os/Parcelable) in a flutter to copy without having to refer them.

**Comment by davemg3** [comment] 2021-03-06 13:20
@hyochan , i feel the Flutter team didnt try to understand your programmer as customer issue...I am expecting Flutter language to be focused on programmers need...

the thing that "If you pass a value of any other type, they are passed as reference and changes to properties of them change it everywhere else with a reference to the same instance." is quite disturbing when applied to List and list item in case you dont want changed in child to be reflected to parents...

Hopefully they will consider our voices and re-open the discussion

**Comment by troncomputers** [comment] 2021-04-21 08:20
Same for me. That is wird. Basic example is when user try to edit object, open an edit screen, type a new value, and than "cancel", "go back", because decided to not changing anything but it's already changed... 

My example is:
New order -> selecting product from list of products (name, quantity, price) -> selecting customer (with discount, for example 48%) -> products are recalculated with customer discount -> remove product from order -> selecting it again and the price is with discount...

**NEW ORDER SCREEN**
![new_order](https://user-images.githubusercontent.com/29543667/115520775-cccb6380-a28a-11eb-92f5-feb1f8847b56.png)

**PRODUCT SELECTION** - price is `9.70` (first element)
![product_selection](https://user-images.githubusercontent.com/29543667/115520817-d5239e80-a28a-11eb-8c88-28e78ef76b2b.png)
**DISCOUNT RECALCULATION** - `48%` of discount. Now price is `6.55`
![discount_calculation](https://user-images.githubusercontent.com/29543667/115520939-f1bfd680-a28a-11eb-901b-3c670f313de5.png)
**PRODUCT SELECTION (AGAIN)** - price is changed
![product_selection_2](https://user-images.githubusercontent.com/29543667/115521084-1451ef80-a28b-11eb-8cdc-75cbe1651998.png)


Two different widgets, two differents screens and how is that normal behavior?
