### ISSUE TITLE
In [google_maps_flutter] package add Customization of InfoWindow

### ISSUE THREAD

**Issue by umerbutt03** [flutter/flutter#121853] opened 2023-03-03 05:17 UTC
## Use case

I want to use my custom widget on infoWindow property of Google Maps Package, but, I am not able to add on it. infoWindow property doesn't allow me to customize it.

Sample shown in below link, which I want to do.

https://developers.google.com/static/maps/documentation/images/marker-infowindows_2x.png

## Proposal

Please add the customize option in Google Maps infoWindow property.

**Comment by darshankawar** [comment] 2023-03-03 08:43
Closing as a duplicate of https://github.com/flutter/flutter/issues/52878 and https://github.com/flutter/flutter/issues/24213.

**Closed by darshankawar** 2023-03-03 08:43 UTC
Labels: in triage
