### ISSUE TITLE
PaginatedDataTable Last Page Error

### ISSUE THREAD

**Issue by melihgundogan** [flutter/flutter#123093] opened 2023-03-21 08:25 UTC
Hello,
When I go to the last page using the showFirstLastButton feature after pulling data in PaginatedDataTable, I get the error "RangeError (index): Index out of range: no indices are valid: 0". I was also able to find DataTable for the solution of this error. But I can't find any solution in PaginatedDataTable. It's urgent, I'd appreciate it if you could help.

**Comment by huycozy** [comment] 2023-03-21 10:23
Hi @melihgundogan 
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Also, please provide the output of `flutter doctor -v` and `flutter run -v` (if the log is too long, please save it into a file and attach it here.) as well. Thanks!

**Comment by melihgundogan** [comment] 2023-03-21 15:07
`import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:http/http.dart' as http;
import 'cubit/example_cubit.dart';

class Passenger {
  final String id;
  final String name;
  final String trips;
  final String airline;

  Passenger(
      {required this.airline,
      required this.id,
      required this.name,
      required this.trips});

  factory Passenger.fromJson(Map<String, dynamic> json) {
    return Passenger(
      id: json['_id'].toString(),
      name: json['name'].toString(),
      trips: json['trips'].toString(),
      airline: json['airline'].toString(),
    );
  }
}

class _PassengerDataSe extends DataTableSource {
  _PassengerDataSe(this._passengers, this._totalItemCount);

  List<dynamic> _passengers;
  final int _totalItemCount;
  int counter = -1;

  List<dynamic> isVisible = List.generate(100000, (index) => false);

  @override
  DataRow getRow(int index) {
    counter == 10 ? counter = 0 : counter++;
    final passenger = _passengers[counter];
    return DataRow.byIndex(index: index, cells: [
      DataCell(BlocProvider(
        create: (context) => ExampleCubit(),
        child: Row(
          children: [Text(passenger['_id'].toString())],
        ),
      )),
      DataCell(Text(passenger['name'].toString())),
      DataCell(Text(passenger['trips'].toString())),
      DataCell(Text(passenger['airline'][0]['name'].toString())),
    ]);
  }

  @override
  bool get isRowCountApproximate => false;

  @override
  int get rowCount => _totalItemCount;

  @override
  int get selectedRowCount => 0;
}

class PaginatedDataTableExample extends StatefulWidget {
  @override
  _PaginatedDataTableExampleState createState() =>
      _PaginatedDataTableExampleState();
}

class _PaginatedDataTableExampleState extends State<PaginatedDataTableExample> {
  int _rowsPerPage = 10;
  int _currentPage = 0;
  int _totalPages = 0;
  List<dynamic> _passengers = [];
  bool _isLoading = true;
  int _totalItemCount = 0;

  Future<void> _fetchPassengers() async {
    setState(() {
      _isLoading = true;
    });

    final response = await http.get(Uri.parse(
        'https://api.instantwebtools.net/v1/passenger?page=$_currentPage&size=$_rowsPerPage'));
    if (response.statusCode == 200) {
      final jsonData = jsonDecode(response.body);
      setState(() {
        _totalPages = jsonData['totalPages'];
        _totalItemCount = jsonData['totalPassengers'];
        _passengers = jsonData['data'];
        _isLoading = false;
      });
    } else {
      setState(() {
        _isLoading = false;
      });
      throw Exception('Failed to fetch passengers');
    }
  }

  @override
  void initState() {
    super.initState();
    _fetchPassengers();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Passengers')),
      body: SingleChildScrollView(
        child: PaginatedDataTable(
            showFirstLastButtons: true,
            header: const Text('Passengers'),
            columns: const [
              DataColumn(label: Text('ID')),
              DataColumn(label: Text('Name')),
              DataColumn(label: Text('Trips')),
              DataColumn(label: Text('Airline')),
            ],
            source: _PassengerDataSe(_passengers, _totalItemCount),
            rowsPerPage: _rowsPerPage,
            columnSpacing: 250,
            onPageChanged: (value) {
              setState(() {
                _currentPage = value;
              });
              _fetchPassengers();
            }),
      ),
    );
  }
}
`
Error message when go to last screen : RangeError (index): Index out of range: no indices are valid: 0

**Comment by huycozy** [comment] 2023-03-22 04:40
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. 

Also, please provide information indicated at https://github.com/flutter/flutter/issues/123093#issuecomment-1477588805 so that we can verify the issue properly. Thanks!

**Comment by melihgundogan** [comment] 2023-03-22 07:21
I'm pulling data from the internet. How can I do this without using third party apps. If I generate a list using list.generate, paginateddatatable does not give such an error. The problem part starts after the data is taken. How can I make the code less in this case?

**Comment by melihgundogan** [comment] 2023-03-22 15:07
`import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

//MODEL
class Passenger {
  final String id;
  final String name;
  final String trips;
  final String airline;

  Passenger(
      {required this.airline,
      required this.id,
      required this.name,
      required this.trips});

  factory Passenger.fromJson(Map<String, dynamic> json) {
    return Passenger(
      id: json['_id'].toString(),
      name: json['name'].toString(),
      trips: json['trips'].toString(),
      airline: json['airline'].toString(),
    );
  }
}

//--------------------------------------------------------------------------------
//SOURCE
class _PassengerDataSe extends DataTableSource {
  _PassengerDataSe(this._passengers, this._totalItemCount);

  final List<dynamic> _passengers;
  final int _totalItemCount;
  int counter = -1;

  @override
  DataRow getRow(int index) {
    counter++;
    final passenger = _passengers[counter];
    return DataRow(cells: [
      DataCell(Text(passenger['_id'].toString())),
      DataCell(Text(passenger['name'].toString())),
      DataCell(Text(passenger['trips'].toString())),
      DataCell(Text(passenger['airline'][0]['name'].toString())),
    ]);
  }

  @override
  bool get isRowCountApproximate => false;

  @override
  int get rowCount => _totalItemCount;

  @override
  int get selectedRowCount => 0;
}

//---------------------------------------------------------------------------------
//VİEW
class PaginatedDataTableExample extends StatefulWidget {
  @override
  _PaginatedDataTableExampleState createState() =>
      _PaginatedDataTableExampleState();
}

class _PaginatedDataTableExampleState extends State<PaginatedDataTableExample> {
  int _rowsPerPage = 10;
  int _currentPage = 1;
  int _totalPages = 0;
  List<dynamic> _passengers = [];
  bool _isLoading = true;
  int _totalItemCount = 0;

  Future<void> _fetchPassengers(int currentPage) async {
    setState(() {
      _isLoading = true;
    });

    final response = await http.get(Uri.parse(
        'https://api.instantwebtools.net/v1/passenger?page=$currentPage&size=10'));
    if (response.statusCode == 200) {
      final jsonData = jsonDecode(response.body);
      print("response:" + response.body.toString());
      setState(() {
        _totalPages = jsonData['totalPages'];
        _totalItemCount = jsonData['totalPassengers'];
        _passengers = jsonData['data'];
        _isLoading = false;
      });
    } else {
      setState(() {
        _isLoading = false;
      });
      throw Exception('Failed to fetch passengers');
    }
  }

  Future<void> _fetchPassengersDene(int currentPage) async {
    setState(() {
      _isLoading = true;
    });

    final response = await http
        .get(Uri.parse('https://api.instantwebtools.net/v1/passenger'));
    if (response.statusCode == 200) {
      final jsonData = jsonDecode(response.body);
      print("response:" + response.body.toString());
      setState(() {
        _totalPages = jsonData['totalPages'];
        _totalItemCount = jsonData['totalPassengers'];
        _passengers = jsonData['data'];
        _isLoading = false;
      });
    } else {
      setState(() {
        _isLoading = false;
      });
      throw Exception('Failed to fetch passengers');
    }
  }

  @override
  void initState() {
    super.initState();
    _fetchPassengers(_currentPage);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Passengers')),
      body: SingleChildScrollView(
        child: Column(
          children: [
            PaginatedDataTable(
                showFirstLastButtons: true,
                header: const Text('Passengers'),
                columns: const [
                  DataColumn(label: Text('ID')),
                  DataColumn(label: Text('Name')),
                  DataColumn(label: Text('Trips')),
                  DataColumn(label: Text('Airline')),
                ],
                source: _PassengerDataSe(_passengers, _totalItemCount),
                rowsPerPage: _rowsPerPage,
                onPageChanged: (value) {
                  setState(() {
                    dynamic example = _fetchPassengers(value);
                  });
                }),
          ],
        ),
      ),
    );
  }
}
`

**Comment by huycozy** [comment] 2023-03-23 04:32
Thanks. As I can see, the issue is caused by your implementation code. Your data on the last page is empty, so `_passengers` list is empty, this makes the exception when you try to access the list `_passengers[counter]`. 
The given simple solution is to check the list before building the UI:

```
  @override
  DataRow getRow(int index) {
    if(_passengers.isEmpty) {
      return const DataRow(cells: [
        DataCell(SizedBox.shrink()),
        DataCell(SizedBox.shrink()),
        DataCell(SizedBox.shrink()),
        DataCell(SizedBox.shrink()),
      ]);
    }
    counter++;
    final passenger = _passengers[counter];
    return DataRow(cells: [
      DataCell(Text(passenger['_id'].toString())),
      DataCell(Text(passenger['name'].toString())),
      DataCell(Text(passenger['trips'].toString())),
      DataCell(Text(passenger['airline'][0]['name'].toString())),
    ]);
  }
```

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/227103605-51704418-dede-41ee-bf24-3631fcb23879.mov


</details>

Your question is best suited for support channels like StackOverflow, so please ask the same there for other solutions if any.

Closing for now since it's not a Flutter framework issue.

**Closed by huycozy** 2023-03-23 04:32 UTC
Labels: in triage
