### ISSUE TITLE
W/Gralloc3( 8677): mapper 3.x is not supported

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#50405] opened 2020-02-08 11:51 UTC
I am testing a Flutter app with Google Maps Flutter, and the app often hangs after this message:

> Running Gradle task 'assembleDebug'...
> √ Built build\app\outputs\apk\debug\app-debug.apk.
> Installing build\app\outputs\apk\app.apk...
> Syncing files to device Pixel 2...
> W/Gralloc3( 8677): mapper 3.x is not supported
> 
Sometimes it loads without an issue (same codebase). Any tips?
## Details

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

**Comment by jonahwilliams** [comment] 2020-02-08 18:20
Do you have the full device logs when this happens? From `adb logcat` - that would contain more information on whether something is crashing

**Comment by jonahwilliams** [comment] 2020-02-08 18:21
Though it might also be a tool sync issue, in which case we'd also need logs from a verbose run `flutter run -v` and your flutter version `flutter doctor -v`

**Comment by VladyslavBondarenko** [comment] 2020-03-05 16:06
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.

**Comment by VladyslavBondarenko** [comment] 2020-04-16 11:34
@kirankumbhar 
could you provide steps to reproduce it?

**Comment by kirankumbhar** [comment] 2020-04-17 08:24
@VladyslavBondarenko 

I was working on demo app and everything was working fine and after following incident is started showing this error

1. I inserted Text() widget without passing string in it.
2. I got error which was obvious.
3. I entered string and now error is gone
4. but now my app is crashed I checked debug console. It is showing above logs with mapper not supported.
I switched to real device from emulator. Still the error popping.
I did `flutter clean`. Sill the error is popping

I'm not sure that step 1 to 3 are actual reasons behind this error.

After bit of googling, I got app working with `flutter run --verbose` command. Even at the time of running --verbose command Flutter  `No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.` was still there. But somehow the app started working again.

Right now the app is working but sometimes I still get these errors. not sure the reason behind this.

Tools and Versions details:

- Windows 10 build 1903
- Flutter 1.12.13+hotfix.8
- Emulator Pixel 3 running API 29
- Physical device Nokia 8.1 running Andriod 10
- VS code

**Comment by xfengs1366** [comment] 2020-05-06 20:07
11

**Comment by fatherchill** [comment] 2020-05-16 11:59
It seems that this error is occurring on all (? or at least many) devices running Android 10. At least sometimes it is a breaking error (once I publish my app on Play store it will hang immediately).

To reproduce:
Create new flutter app in Android Studio or VS code.
Run the new app on a Pixel 3 emulator API 29 (error doesn't show on API 28). View logcat.

I have tested 5+ flutter apps, new and old. Tested with Flutter versions from the dev, beta and stable branch of 1.17.x down to v1.5.4 and the error still appears. Installed Flutter and Android studio on a new windows machine, error still appeared when running fresh app on physical Pixel 3.

Devices tested with Gralloc3 mapper 3.x error:
Physical Pixel 3 - API 29
Physical Nokia 8.1 - API 29
Emulator Pixel 3 - API 29
Emulator Nexus 6 - API 29

Emulator Pixel 3 - API 30 fails with Gralloc4 ... mapper 4.x error

**Comment by vulterey** [comment] 2020-05-26 18:29
Same happens to my widget tested on Samsung S10 Plus: W/Gralloc3: mapper 3.x is not supported

**Comment by mobilego** [comment] 2020-06-16 02:05
Any updates on this issue ? I am also facing the same issue with Flutter 1.17.3 and Android 10

**Comment by dnfield** [comment] 2020-09-28 22:01
This can happen if a call to [`AndroidBitmap_lockPixels`](https://developer.android.com/ndk/reference/group/bitmap#androidbitmap_lockpixels) is made on a hardware buffer backed bitmap.

We don't call that API directly - but maybe the maps SDK does. @amirh do you know?

**Comment by AlaaMarawi** [comment] 2020-11-28 14:37
Same issue with samsung galaxy s10 (x86) android10 , Flutter 1.22.3  
(not all android 10 and all x86 devices !)

**Comment by pedromassangocode** [comment] 2020-12-02 10:27
Hi @giorgio79 
I cannot reproduce this issue on the latest stable version of Flutter using the code bellow and the latest version of Google Maps plugin.

Not sure if the code bellow reproduces this issue so please confirm and provide your steps to reproduce the issue if it still happening.

<details><summary>Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(0, 0),
        ),
      ),
    );
  }
}

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-10.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 022b333a08 (2 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>

**Comment by redimongo** [comment] 2020-12-03 12:10
I am having the same issue here is my full app code if it helps:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.radiomedia.drn1">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="drn1"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```

**Comment by pedromassangocode** [comment] 2020-12-03 14:07
@redimongo please make sure you provide code that is runnable and that does not uses third-party plugins/packages.

**Comment by pedromassangocode** [comment] 2020-12-30 10:43
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 10:43 UTC
Labels: P4, dependency: android, engine, in triage, platform-android, severe: crash, tool, waiting for customer response

**Comment by kashh-crypto** [comment] 2021-02-09 09:26
02/09 10:19:47: Launching 'app' on Pixel 4 API 29.
Install successfully finished in 14 s 103 ms.
$ adb shell am start -n "com.example.audiorecorder/com.example.audiorecorder.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 8645 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/e.audiorecorde: Waiting for a blocking GC ClassLinker
I/e.audiorecorde: WaitForGcToComplete blocked ClassLinker on HeapTrim for 376.637ms
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
W/e.audiorecorde: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/e.audiorecorde: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/HostConnection: HostConnection::get() New Host Connection established 0xd444c190, tid 8701
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0xd4403360: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xd4403360: ver 2 0 (tinfo 0xd4400240)
W/Gralloc3: mapper 3.x is not supported
D/HostConnection: createUnique: call
    HostConnection::get() New Host Connection established 0xd444c460, tid 8701
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2 
D/eglCodecCommon: allocate: Ask for block of size 0x1000
D/eglCodecCommon: allocate: ioctl allocate returned offset 0x3ffffa000 size 0x2000
D/EGL_emulation: eglMakeCurrent: 0xd4403360: ver 2 0 (tinfo 0xd4400240)
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 0
W/RenderThread: type=1400 audit(0.0:54): avc: denied { write } for name="property_service" dev="tmpfs" ino=6755 scontext=u:r:untrusted_app:s0:c134,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0
I/e.audiorecorde: NativeAlloc concurrent copying GC freed 3973(576KB) AllocSpace objects, 0(0B) LOS objects, 51% free, 1460KB/2996KB, paused 27.196ms total 1.148s

**Comment by kashh-crypto** [comment] 2021-02-09 09:27
how can i fix problem

**Comment by SonicCodes** [comment] 2021-03-11 16:51
![Uploading Screen Shot 2021-03-11 at 7.45.40 PM.png…]()


[Gralloc3.cpp](https://android.googlesource.com/platform/frameworks/native/+/master/libs/ui/Gralloc3.cpp)
I don't think this is a problem with flutter, I got it while working on my a native app & I wasn't able to display the map. 

I am testing on Android 10 GO
com.google.android.gms:play-services-maps:17.0.0

**Comment by SonicCodes** [comment] 2021-03-11 16:53
![Screen Shot 2021-03-11 at 7 53 24 PM](https://user-images.githubusercontent.com/48802163/110823786-7c341400-82a3-11eb-952b-0de773f4f418.png)

Here's a screen shot

**Comment by SonicCodes** [comment] 2021-03-11 17:58
Update, This is not the issue, you must have something wrong with your code, this is supposedly a warning and not an indication of a serious thing.
 if you're on an emulator enable useHostGpu & add 
```<uses-feature android:glEsVersion="0x00020000" android:required="true" />```
In your Manifest File
```
0x00020000 = OpenGles 2.0 (API >=8)
0x00020000 = OpenGles 3.0 (API >=18)
```
This will force android studio to use a specific OpenGles Library.
