### ISSUE TITLE
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#47343] opened 2019-12-18 15:33 UTC
This error seems to be related to some problem with TextFiled and TextFormField, after I put TextFiled in a 38 height containner.

```
Syncing files to device SM J120H...
Reloaded 20 of 1030 libraries in 2.433ms.
I/flutter ( 3344): obteve  do cache

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField file:///D:/MyDartProjects/appsescverao/lib/widgets/appbar_search.dart:47:14
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
#4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
#5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#63e9d relayoutBoundary=up32
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=191.0, 0.0<=h<=14.0)
...  size: Size(191.0, 14.0)
...  cursorColor: Color(0x004285f4)
...  showCursor: ValueNotifier<bool>#05e19(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: pt_BR
...  selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#01cd6(offset: 0.0, range: 0.0..0.0, viewport: 191.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#b88bc, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge((blackMountainView subhead).apply)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Roboto
    size: 15.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
RenderObject: RenderEditable#63e9d relayoutBoundary=up32
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=191.0, 0.0<=h<=14.0)
  size: Size(191.0, 14.0)
  cursorColor: Color(0x004285f4)
  showCursor: ValueNotifier<bool>#05e19(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: pt_BR
  selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#01cd6(offset: 0.0, range: 0.0..0.0, viewport: 191.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#b88bc, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge((blackMountainView subhead).apply)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Roboto
    size: 15.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```dart
import 'package:flutter/material.dart';

class SearchAppBar extends StatefulWidget with PreferredSizeWidget {
  //"Big Noodle Titling"
  static const textStyle = TextStyle(color: Colors.white, fontFamily: "Roboto");
  static const backColor = Color.fromRGBO(239, 237, 222, 0.0);
  String title = "";
  TextStyle styleTitle = textStyle;
  Color colorIcon = Colors.white;
  Color backgroundColor = backColor;
  double elevation = 0;
  bool centerTitle = true;
  Function searchOpening;
  Function onKeypress;
  bool showSearch = true;
  Size preferredSize = AppBar().preferredSize;
  final List<Widget> actions;

  SearchAppBar({Key key, this.title = "", this.colorIcon = Colors.white, this.backgroundColor = backColor, this.styleTitle = textStyle, this.showSearch = true, this.searchOpening, @required this.onKeypress, this.elevation = 0, this.centerTitle = true, this.actions}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return new SearchAppBarState();
  }
}

class SearchAppBarState extends State<SearchAppBar> {
  final TextEditingController _filter = TextEditingController();
  Icon _searchIcon = Icon(Icons.search);
  bool _isSearching = false;

  _buildTitle() {
    return Text(
      widget.title,
      style: widget.styleTitle,
    );
  }

  _buildSearchField() {
    return Container(
      padding: EdgeInsets.fromLTRB(15, 0, 10, 0),
      height: 38,
      decoration: BoxDecoration(color: Color.fromRGBO(255, 255, 255, 1), borderRadius: BorderRadius.all(Radius.circular(25))),
      child: TextField(
        style: TextStyle(fontSize: 15),
        autofocus: true,
        controller: _filter,
        decoration: InputDecoration(
          border: InputBorder.none,
          /*OutlineInputBorder(
          borderRadius: BorderRadius.circular(25.0),
          borderSide: BorderSide(),
        ),*/
          //prefixIcon: Icon(Icons.search),
          hintText: 'Buscar...',
          hintStyle: TextStyle(fontFamily: "Roboto"),
        ),
      ),
    );
  }

  Widget _buildBar(BuildContext context) {
    var appBar = AppBar(
        iconTheme: IconThemeData(
          color: widget.colorIcon, //change your color here
        ),
        centerTitle: widget.centerTitle,
        titleSpacing: 0.0,
        title: _isSearching ? _buildSearchField() : _buildTitle(),
        backgroundColor: widget.backgroundColor,
        elevation: widget.elevation,
        actions: widget.showSearch
            ? <Widget>[
                IconButton(
                    icon: _searchIcon,
                    onPressed: () {
                      _searchPressed();
                    }),
              ]
            : widget.actions);

    widget.preferredSize = appBar.preferredSize;
    return appBar;
  }

  void _searchPressed() async {
    setState(() {
      if (this._searchIcon.icon == Icons.search) {
        this._searchIcon = Icon(Icons.close);
        _isSearching = true;
      } else {
        this._searchIcon = Icon(Icons.search);
        _filter.clear();
        _isSearching = false;
      }

      if (widget.searchOpening != null) {
        widget.searchOpening();
      }
    });
  }

  @override
  void initState() {
    super.initState();
    initWidgetState();
  }

  initWidgetState() async {
    //ouvinte de vento onkeypress do searchbox
    _filter.addListener(() {
      if (widget.onKeypress != null) {
        widget.onKeypress(_filter.text);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    var screenSize = MediaQuery.of(context).size;
    return _buildBar(context);
  }
}

```

```yaml
name: appsescverao
description: Aplicativo do Sesc Verão Rio das Ostras

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+2
  path_provider: ^1.5.1
  flutter_advanced_networkimage: ^0.6.2
  sqflite: ^1.2.0
  connectivity: ^0.4.6+1
  url_launcher: ^5.4.1
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.2
  google_sign_in: ^4.1.0
  firebase_database: ^3.1.1
  rxdart: ^0.23.1
  webview_flutter: ^0.3.18+1
  auto_size_text: ^2.1.0
  flutter_map: ^0.8.0
  latlong: ^0.6.1
  queries: ^0.1.12
  firebase_analytics: ^5.0.9
  shared_preferences: ^0.5.6
  #audioplayers: ^0.13.5
  #audio_streams: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.7

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background.png
    - assets/background2.png
    - assets/background3.png
    - assets/user-avatar.png
    - assets/logo-pmro-cinza.png
    - assets/logo-pmro-branco.png
    - assets/wave-bottom.png
    - assets/wave-top.png
    - assets/logo2.png
    - assets/logo-branca.png

  fonts:
    - family: Big Noodle Titling
      fonts:
        - asset: fonts/big_noodle_titling.ttf
    - family: GlosaDisplayW01-Bold
      fonts:
        - asset: fonts/glosa_display_w01_bold.ttf
    - family: BakerieSmoothCondensedMedium
      fonts:
        - asset: fonts/BakerieSmoothCondensed-Medium.otf
    - family: BakerieSmoothBold
      fonts:
        - asset: fonts/BakerieSmooth-Bold.otf
    - family: iconsmind
      fonts:
        - asset: fonts/iconsmind.ttf
```

**Comment by BuddyShen** [comment] 2019-12-20 08:50
I faced a same issue too.
It looks like something wrong during painting FocusNode on the textFeild.
Did you fix that?

**Comment by ayush221b** [comment] 2019-12-21 13:51
I am facing the same issue. Have you found any solution ?

**Comment by insinfo** [comment] 2019-12-21 14:37
This error is flashing, time appears time does not appear. I saw that the problem seems to be related to the size of TextFiled's parent widget, I saw that on iphone the error does not appear

**Comment by ayush221b** [comment] 2019-12-21 14:47
I can see the error on the simulator, haven't tested on a physical device.

**Comment by mzimbres** [comment] 2019-12-22 08:47
Same problem here.

**Comment by ayush221b** [comment] 2019-12-22 12:28
@Hixie can you help us?

**Comment by premy** [comment] 2019-12-22 18:51
Same problem here.

**Comment by BuddyShen** [comment] 2019-12-23 04:00
fixed it by upgrade to master version.

**Comment by Hixie** [comment] 2019-12-23 05:58
The test case in the first comment seems to be missing a `void main` so I'm not sure how to start it.

The assertion that's firing is `assert(affinity != null)`.

Sure enough, the exception above says:
```
...  selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: null, isDirectional: false)
```

I don't see any obvious way that that could become null...

**Comment by Hixie** [comment] 2019-12-23 05:58
@insinfo can you confirm if it's fixed on master for you also?

**Comment by Anyoks** [comment] 2019-12-23 15:57
I'm on master. still same issue.

**Comment by dariotrombello** [comment] 2019-12-23 17:05
```
Restarted application in 1.760ms.

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during paint():[39;49m
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mTextFormField[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      new TextPosition  (dart:ui/text.dart:1372:15)[39;49m
[38;5;244m#3      RenderEditable._updateSelectionExtentsVisibility[39;49m
[38;5;244m#4      RenderEditable._paintContents[39;49m
[38;5;244m#5      RenderEditable.paint[39;49m
[38;5;244m#6      RenderObject._paintWithContext[39;49m
[38;5;244m...[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: RenderEditable#3c901 relayoutBoundary=up31[39;49m
[38;5;244mRenderObject: RenderEditable#3c901 relayoutBoundary=up31[39;49m
    [38;5;244mparentData: <none> (can use size)[39;49m
    [38;5;244mconstraints: BoxConstraints(w=232.0, 0.0<=h<=Infinity)[39;49m
    [38;5;244msize: Size(232.0, 19.0)[39;49m
    [38;5;244mcursorColor: Color(0x004285f4)[39;49m
    [38;5;244mshowCursor: ValueNotifier<bool>#d836a(true)[39;49m
    [38;5;244mmaxLines: 1[39;49m
    [38;5;244mminLines: null[39;49m
    [38;5;244mselectionColor: Color(0xff64ffda)[39;49m
    [38;5;244mtextScaleFactor: 1.0[39;49m
    [38;5;244mlocale: en_US[39;49m
    [38;5;244mselection: TextSelection(baseOffset: 10, extentOffset: 10, affinity: null, isDirectional: false)[39;49m
    [38;5;244moffset: ScrollPositionWithSingleContext#a2c29(offset: 0.0, range: 0.0..0.0, viewport: 232.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#37902, ScrollDirection.idle)[39;49m
    [38;5;244mtext: TextSpan[39;49m
        [38;5;244mdebugLabel: (englishLike subhead 2018).merge(whiteMountainView subhead)[39;49m
        [38;5;244minherit: true[39;49m
        [38;5;244mcolor: Color(0xffffffff)[39;49m
        [38;5;244mfamily: Roboto[39;49m
        [38;5;244msize: 16.0[39;49m
        [38;5;244mweight: 400[39;49m
        [38;5;244mletterSpacing: 0.1[39;49m
        [38;5;244mbaseline: alphabetic[39;49m
        [38;5;244mdecoration: TextDecoration.none[39;49m
        [38;5;244m"••••••••••"[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mTextFormField[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: RenderEditable#cc19e relayoutBoundary=up31[39;49m
[38;5;244mRenderObject: RenderEditable#cc19e relayoutBoundary=up31[39;49m
    [38;5;244mparentData: <none> (can use size)[39;49m
    [38;5;244mconstraints: BoxConstraints(w=232.0, 0.0<=h<=Infinity)[39;49m
    [38;5;244msize: Size(232.0, 19.0)[39;49m
    [38;5;244mcursorColor: Color(0x004285f4)[39;49m
    [38;5;244mshowCursor: ValueNotifier<bool>#7b833(true)[39;49m
    [38;5;244mmaxLines: 1[39;49m
    [38;5;244mminLines: null[39;49m
    [38;5;244mselectionColor: Color(0xff64ffda)[39;49m
    [38;5;244mtextScaleFactor: 1.0[39;49m
    [38;5;244mlocale: en_US[39;49m
    [38;5;244mselection: TextSelection(baseOffset: 10, extentOffset: 10, affinity: null, isDirectional: false)[39;49m
    [38;5;244moffset: ScrollPositionWithSingleContext#dab3f(offset: 0.0, range: 0.0..0.0, viewport: 232.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#fc84e, ScrollDirection.idle)[39;49m
    [38;5;244mtext: TextSpan[39;49m
        [38;5;244mdebugLabel: (englishLike subhead 2018).merge(whiteMountainView subhead)[39;49m
        [38;5;244minherit: true[39;49m
        [38;5;244mcolor: Color(0xffffffff)[39;49m
        [38;5;244mfamily: Roboto[39;49m
        [38;5;244msize: 16.0[39;49m
        [38;5;244mweight: 400[39;49m
        [38;5;244mletterSpacing: 0.1[39;49m
        [38;5;244mbaseline: alphabetic[39;49m
        [38;5;244mdecoration: TextDecoration.none[39;49m
        [38;5;244m"••••••••••"[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
```
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!
```
Can confirm on latest stable release with an S9 as testing device.

**Comment by Hixie** [comment] 2019-12-23 20:05
Please post the exact test case that reproduces this. Thanks!

**Comment by insinfo** [comment] 2019-12-23 20:26
This error is occurring with the latest stable version of the flutter, to make the error simply place a TextField inside a container with a defined size less than 32 in height in the AppBar title.

**Comment by Anyoks** [comment] 2019-12-24 08:09
```
final topAppBar = AppBar(
      leading: Container(),
      elevation: 0.1,
      backgroundColor: Colors.deepPurple[300], //fromRGBO(211, 47, 47, 1),
      title: Padding(
          padding: EdgeInsets.only(left: 80),
          child: Text("Distro")), 
      bottom: PreferredSize(
        preferredSize: Size(50, 50),
        child: Container(
          padding: EdgeInsets.all(10.0),
          child: TextField(
            controller: searchController,
            
            decoration: InputDecoration(
                labelText: "Search",
                hintText: "Search",
                prefixIcon: Icon(Icons.search),
                border: OutlineInputBorder(
                    borderRadius: BorderRadius.all(Radius.circular(25.0)))),
          ),
        ),
      ),
    );

```

Here are the Logs.

```

I/flutter (10734): #128    SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1041
I/flutter (10734): #129    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:850
I/flutter (10734): #131    _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (10734): #132    _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (10734): #133    _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (10734): (elided 3 frames from class _AssertionError and package dart:async-patch)
Reloaded 11 of 831 libraries in 2,311ms.
I/flutter (10734): The following RenderObject was being processed when the exception was fired: RenderEditable#ff527 relayoutBoundary=up26:
I/flutter (10734):   creator: _Editable-[GlobalKey#6da04] ← Semantics ← CompositedTransformTarget ←
I/flutter (10734):     IgnorePointer-[GlobalKey#b42c5] ← Semantics ← _PointerListener ← Listener ←
I/flutter (10734):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#429b3] ← _PointerListener ← Listener
I/flutter (10734):     ← _ScrollableScope ← RepaintBoundary ← ⋯
I/flutter (10734):   parentData: <none> (can use size)
I/flutter (10734):   constraints: BoxConstraints(w=268.0, 0.0<=h<=Infinity)
I/flutter (10734):   size: Size(268.0, 13.0)
I/flutter (10734):   cursorColor: Color(0x004285f4)
I/flutter (10734):   showCursor: ValueNotifier<bool>#fbb73(true)
I/flutter (10734):   maxLines: 1
I/flutter (10734):   minLines: null
I/flutter (10734):   selectionColor: Color(0xff90caf9)
I/flutter (10734):   textScaleFactor: 0.7
I/flutter (10734):   locale: en_US
I/flutter (10734):   selection: TextSelection(baseOffset: 1, extentOffset: 1, affinity: null, isDirectional: false)
I/flutter (10734):   offset: ScrollPositionWithSingleContext#f41e1(offset: 0.0, range: 0.0..0.0, viewport: 268.0,
I/flutter (10734):     ScrollableState, ClampingScrollPhysics, IdleScrollActivity#b90b5, ScrollDirection.idle)
I/flutter (10734): This RenderObject had the following child:
I/flutter (10734):     text: TextSpan
I/flutter (10734): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by zzlhr** [comment] 2019-12-25 09:58
The same problem exists. If there is no Done keypad after typing TextField on ios, click the white area to close the Drawer and open the Drawer again to get this error.

**Comment by thanhhai08sk** [comment] 2019-12-25 10:31
Same issue.
Tap the edit text to show keyboard -> remove it from the widgets tree -> add it again to the widgets tree, this time, edit text content is blank, tapping the blank space will make the text reappear.

If not showing keyboard, only remove and add to the widgets tree then no problem.

**Comment by defint** [comment] 2019-12-26 15:24
Widget that reproduces the problem: https://gist.github.com/defint/7c42ff3c4149d3345c84c32bbe6abd05

Steps:
1) input "aa"
2) lost focus from the input
3) validation message "xxx" should be shown
4) tap on the textfield
5) have a message: 'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

**Comment by iLeafSolutionsPvtLtd** [comment] 2019-12-27 09:38
I was able to stop this exception by adding this line
FocusScope.of(context).requestFocus(new FocusNode());
when switch TextField to Text ...
But it failed to carry back the focus when it turned back to TextField.

**Comment by iLeafSolutionsPvtLtd** [comment] 2019-12-27 09:41
> Same issue.
> Tap the edit text to show keyboard -> remove it from the widgets tree -> add it again to the widgets tree, this time, edit text content is blank, tapping the blank space will make the text reappear.
> 
> If not showing keyboard, only remove and add to the widgets tree then no problem.

I was able to stop this exception by adding this line
FocusScope.of(context).requestFocus(new FocusNode());
when switch TextField to Text ...
But it failed to carry back the focus when it turned back to TextField.

**Comment by thanhhai08sk** [comment] 2019-12-27 17:18
Looks like it only happens on the simulator/debug mode for me

**Comment by defint** [comment] 2019-12-27 17:33
> Looks like it only happens on the simulator/debug mode for me

Yep, assertion util doesn't affect on release mode.
But this bug must be fixed anyway.

**Comment by TheTrainor** [comment] 2019-12-30 12:43
+1 on this issue.

**Comment by brianwawok** [comment] 2019-12-31 17:07
This is 100% hitting release mode for me.

**Comment by premy** [comment] 2020-01-01 20:24
In my case the exception occurs whenever I try to hide a dirty form:
```
if (model.isLoading) return  Center(
          child: CircularProgressIndicator(),
        );
    return ListView(
                padding: EdgeInsets.all(16.0),
                children: [
                  Container(
                    child:  buildClassificado(context, model)
                  ),
                ]
            );
```
The form lives inside buildClassificado. After the user completes the form he gets to tap a submit button which sets isLoading to true. If I take out the isLoading check and submit the form, no problem.
Now I've got quite a few forms in the app, all showing a loader while savinhg data to the backend, which seems to be a rather common requirement, yes?
The exception started with the current stable version; with the former stable version it did not happen.
And it doesn't matter if it's debug/release or emulator/device.

**Comment by premy** [comment] 2020-01-03 01:46
Ok, was able to solve it by adding the following at the start of the button's onpressed:
```
 FocusScopeNode currentFocus = FocusScope.of(context);
        if (!currentFocus.hasPrimaryFocus) {
          currentFocus.unfocus();
        }
```
This removes focus from the last TextFormField being edited and dismisses the keyboard. Would expect this to happen automatically when tapping a button, but apparently...

**Comment by Hixie** [comment] 2020-01-03 03:39
cc @gspencergoog since that implicates focus

**Comment by gspencergoog** [comment] 2020-01-06 18:26
This is working as intended: non-Flutter apps don't set the focus to the button (or remove focus from another widget) based on a click/tap either, they only trigger the button action.

**Comment by nadchif** [comment] 2020-01-07 16:04
@premy your solution solved my problem. I was using a CupertinoTextField inside a Stepper and after using your solution, the issue is gone 👍

**Comment by rhhub** [comment] 2020-01-08 23:29
I've tried @premy solution but I need to maintain TextField focus while pressing a button. If I go to refocus after the frame using the following code, the keyboard flickers: 
```
WidgetsBinding.instance.addPostFrameCallback((_) {
      _focusNode.unfocus();
      FocusScope.of(context).requestFocus(_focusNode);
});
```

**Comment by marciombm** [comment] 2020-01-17 01:01
I started studying Flutter last year with an previous version and since I upgraded to the latest version I am getting this error, but now the issue is solved with the @premy solution. Thanks from Brazil!

**Comment by marciombm** [comment] 2020-01-17 01:05
I started studying Flutter last year with a previous version and since I upgraded to the latest version I am getting this error, but now the issue is solved with the @premy solution. Thanks from Brazil!

**Comment by navaronbracke** [comment] 2020-02-01 13:01
I'm no longer getting the issue on v1.12.13+hotfix.7 So I guess this issue can be closed if everyone agrees?

**Comment by LongCatIsLooong** [comment] 2020-04-17 21:38
Seems to have been fixed in https://github.com/flutter/flutter/pull/44622

**Closed by LongCatIsLooong** 2020-04-17 21:38 UTC
Labels: a: typography, customer: crowd, f: material design, framework, severe: crash, severe: regression
