### ISSUE TITLE
microbenchmark_sstock_animation_open_first_frame_average regressed.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#41918] opened 2019-10-03 16:36 UTC
Looks like this engine roll: https://github.com/flutter/flutter/commit/5975e86f00a39f23635feed7d051b0d647ed2ede

Could be as late as https://github.com/flutter/flutter/commit/0af2a84cbbb69c8a3ea33a389b9e893e6de8ef4d.

**Comment by Hixie** [comment] 2019-10-03 19:21
I suspect this is the same cause as https://github.com/flutter/flutter/issues/41919. I'm going to close it as as dupe of that one for now.

**Closed by Hixie** 2019-10-03 19:21 UTC
Labels: severe: performance, severe: regression, ⚠ TODAY
