### ISSUE TITLE
I am not able to use camera in Flutter.

### ISSUE THREAD

**Issue by aakashtyagiwmp** [flutter/flutter#95901] opened 2021-12-28 12:25 UTC
Launching lib/main.dart on Infinix X690 in debug mode...
Running Gradle task 'assembleDebug'...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/Camera.java:23: error: cannot find symbol
import android.media.EncoderProfiles;
                    ^
  symbol:   class EncoderProfiles
  location: package android.media
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/Camera.java:951: error: cannot find symbol
  EncoderProfiles getRecordingProfile() {
  ^
  symbol:   class EncoderProfiles
  location: class Camera
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:10: error: cannot find symbol
import android.media.EncoderProfiles;
                    ^
  symbol:   class EncoderProfiles
  location: package android.media
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:29: error: cannot find symbol
  private EncoderProfiles recordingProfile;
          ^
  symbol:   class EncoderProfiles
  location: class ResolutionFeature
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:63: error: cannot find symbol
  public EncoderProfiles getRecordingProfile() {
         ^
  symbol:   class EncoderProfiles
  location: class ResolutionFeature
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:187: error: cannot find symbol
  public static EncoderProfiles getBestAvailableCamcorderProfileForResolutionPreset(
                ^
  symbol:   class EncoderProfiles
  location: class ResolutionFeature
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/media/MediaRecorderBuilder.java:8: error: cannot find symbol
import android.media.EncoderProfiles;
                    ^
  symbol:   class EncoderProfiles
  location: package android.media
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/media/MediaRecorderBuilder.java:24: error: cannot find symbol
  private final EncoderProfiles encoderProfiles;
                ^
  symbol:   class EncoderProfiles
  location: class MediaRecorderBuilder
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/media/MediaRecorderBuilder.java:36: error: cannot find symbol
      @NonNull EncoderProfiles encoderProfiles, @NonNull String outputFilePath) {
               ^
  symbol:   class EncoderProfiles
  location: class MediaRecorderBuilder
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/media/MediaRecorderBuilder.java:51: error: cannot find symbol
      @NonNull EncoderProfiles encoderProfiles,
               ^
  symbol:   class EncoderProfiles
  location: class MediaRecorderBuilder
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:186: error: cannot find symbol
  @TargetApi(Build.VERSION_CODES.S)
                                ^
  symbol:   variable S
  location: class VERSION_CODES
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/Camera.java:208: error: reference to MediaRecorderBuilder is ambiguous
      mediaRecorderBuilder = new MediaRecorderBuilder(getRecordingProfileLegacy(), outputFilePath);
                             ^
  both constructor MediaRecorderBuilder(CamcorderProfile,String) in MediaRecorderBuilder and constructor MediaRecorderBuilder(EncoderProfiles,String) in MediaRecorderBuilder match
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:118: error: cannot find symbol
      EncoderProfiles profile =
      ^
  symbol:   class EncoderProfiles
  location: class ResolutionFeature
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:120: error: package EncoderProfiles does not exist
      List<EncoderProfiles.VideoProfile> videoProfiles = profile.getVideoProfiles();
                          ^
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:121: error: package EncoderProfiles does not exist
      EncoderProfiles.VideoProfile defaultVideoProfile = videoProfiles.get(0);
                     ^
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:200: error: cannot find symbol
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_HIGH);
                                 ^
  symbol:   method getAll(String,int)
  location: class CamcorderProfile
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:204: error: cannot find symbol
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_2160P);
                                 ^
  symbol:   method getAll(String,int)
  location: class CamcorderProfile
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:208: error: cannot find symbol
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_1080P);
                                 ^
  symbol:   method getAll(String,int)
  location: class CamcorderProfile
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:212: error: cannot find symbol
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_720P);
                                 ^
  symbol:   method getAll(String,int)
  location: class CamcorderProfile
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:216: error: cannot find symbol
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_480P);
                                 ^
  symbol:   method getAll(String,int)
  location: class CamcorderProfile
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:220: error: cannot find symbol
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_QVGA);
                                 ^
  symbol:   method getAll(String,int)
  location: class CamcorderProfile
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:224: error: cannot find symbol
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_LOW);
                                 ^
  symbol:   method getAll(String,int)
  location: class CamcorderProfile
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:241: error: package EncoderProfiles does not exist
      List<EncoderProfiles.VideoProfile> videoProfiles = recordingProfile.getVideoProfiles();
                          ^
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java:243: error: package EncoderProfiles does not exist
      EncoderProfiles.VideoProfile defaultVideoProfile = videoProfiles.get(0);
                     ^
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/media/MediaRecorderBuilder.java:32: error: reference to MediaRecorderBuilder is ambiguous
    this(camcorderProfile, outputFilePath, new MediaRecorderFactory());
    ^
  both constructor MediaRecorderBuilder(CamcorderProfile,String,MediaRecorderFactory) in MediaRecorderBuilder and constructor MediaRecorderBuilder(EncoderProfiles,String,MediaRecorderFactory) in MediaRecorderBuilder match
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/media/MediaRecorderBuilder.java:79: error: package EncoderProfiles does not exist
      EncoderProfiles.VideoProfile videoProfile = encoderProfiles.getVideoProfiles().get(0);
                     ^
/home/aakash/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.9.4+5/android/src/main/java/io/flutter/plugins/camera/media/MediaRecorderBuilder.java:80: error: package EncoderProfiles does not exist
      EncoderProfiles.AudioProfile audioProfile = encoderProfiles.getAudioProfiles().get(0);
                     ^
27 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':camera:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by manoharanpncity** [comment] 2021-12-28 12:45
May i know the minSdk version of the project?

**Comment by maheshmnj** [comment] 2021-12-28 12:50
Hi @aakashtyagiwmp, Thanks for filing the issue. This is a duplicate of https://github.com/flutter/flutter/issues/93714 (closed). 
Please set the `target SDK` version to 31 as mentioned here https://github.com/flutter/flutter/issues/93714#issuecomment-970390516 and that should resolved the build failure.

Closing as this is already resolved. Feel free to write back if you still encounter the issue.

**Closed by maheshmnj** 2021-12-28 12:50 UTC
Labels: in triage

**Comment by aakashtyagiwmp** [comment] 2021-12-28 12:53
issue is resolved

**Comment by aakashtyagiwmp** [comment] 2021-12-28 12:53
Thanks sir.
