### ISSUE TITLE
Analyze and build flutter/gallery during presubmit

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#100980] opened 2022-03-29 17:05 UTC
To avoid post-submit tree breakages like https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_samsung_s10%20new_gallery__transition_perf/279/overview

**Comment by christopherfujino** [comment] 2022-08-04 22:53
I'm guessing you mean analyzer benchmark: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20analyzer_benchmark/3965/overview. A few things:

1. This is a devicelab test because it is a benchmark, and thus (currently) requires being run with the devicelab framework
2. We could add gallery analysis to the existing dev/bots/analyze.dart test; however, I don't think that would have helped, it wasn't the new gallery code that failed analysis, but the flutter_tools, which is already run from dev/bots/analyze.dart, but passed (the analysis in the devicelab test is invoked differently, which perhaps caused hitting hte flake differently)
3. IMO the true failure here is that the analysis result is not deterministic given the same source code inputs, which is being investigated upstream in https://github.com/dart-lang/sdk/issues/49596

**Comment by godofredoc** [comment] 2023-06-13 23:46
Closing as working as intended.

**Closed by godofredoc** 2023-06-13 23:46 UTC
Labels: gallery, team: infra, passed secondary triage
