### ISSUE TITLE
Impeller on iOS fails to draw point correctly

### ISSUE THREAD

**Issue by flodaniel** [flutter/flutter#137412] opened 2023-10-27 13:01 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Using a CustomPainter to draw inside an InteractiveViewer does not display the drawn shape. This only affects iOS and does work on skia. I tested this with the `FLTEnableImpeller` Info.plist flag. 

### Expected results

See a drawn shape inside the interactive viewer.

### Actual results

No shape is visible

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Draggable & Zoomable Circle'),
        ),
        body: Center(
          child: DraggableZoomableCircle(),
        ),
      ),
    );
  }
}

class DraggableZoomableCircle extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return InteractiveViewer(
      boundaryMargin: const EdgeInsets.all(5.0),
      minScale: 0.1,
      maxScale: 1.6,
      child: Center(
        child: SizedBox(
          height: 20,
          width: 20,
          child: CustomPaint(
            painter: CirclePainter(),
            child: Container(
              height: 200,
              width: 200,
            ),
          ),
        ),
      ),
    );
  }
}

@immutable
class CirclePainter extends CustomPainter {
  const CirclePainter();

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = Colors.red
      ..strokeCap = StrokeCap.round
      ..strokeWidth = 20.0;

    final point = size.center(Offset.zero);
    canvas.drawPoints(PointMode.points, [point], paint);
  }

  @override
  bool shouldRepaint(CirclePainter oldDelegate) => false;
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Impeller enabled:
![image](https://github.com/flutter/flutter/assets/6661557/073b9b0a-18ca-4cfe-a8da-f87b7f6f25be)

Impeller disabled: 
![image](https://github.com/flutter/flutter/assets/6661557/c35cd135-8b3a-4fa5-b665-2ec5ef86db73)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.13.9, on macOS 13.5.2 22G91 darwin-arm64, locale en-AT)
    • Flutter version 3.13.9 on channel stable at /Users/floriandaniel/Documents/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/floriandaniel/Documents/flutter. Consider adding /Users/floriandaniel/Documents/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/floriandaniel/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/floriandaniel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • F8803C99-9215-4F77-87CD-FE21F9E620E7 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64 • macOS 13.5.2 22G91 darwin-arm64
    ! Error: Browsing on the local area network for Arthur’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Gernot’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
    ! Error: Browsing on the local area network for Gernot Panholzer’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by dam-ease** [comment] 2023-10-27 15:00
Hi @flodaniel. Thanks for filing this. I can reproduce this on the `stable` channel but this seems to have been fixed in later versions as I can't reproduce on the latest `master`. If you are able to switch to the `master` channel, you can confirm this as well.

![Simulator Screenshot - iPhone 8 - 2023-10-27 at 15 54 16](https://github.com/flutter/flutter/assets/53122008/a5e835d1-9e09-4294-be9b-a12b2a3b3cb4)

Closing this as it has been fixed in the latest versions of Flutter, if you disagree please comment and I'll reopen this.
Thank you!

**Closed** 2023-10-27 15:01 UTC
Labels: in triage

**Comment by flodaniel** [comment] 2023-10-27 20:42
Hi @dam-ease!
Thanks for checking.
Is there a way to know when this will land in stable?

**Comment by dam-ease** [comment] 2023-10-30 09:53
You can read about it here: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release (and whole that page for more info)
