### ISSUE TITLE
Unsupported Android Studio version: Canary versions of Android Studio are not supported by the Flutter plugin.Hi @akshbswas98

### ISSUE THREAD

**Issue by ben700** [flutter/flutter#98597] opened 2022-02-16 18:10 UTC
I see from the last guy opening issue TahaTesser just going to close and no attempt to 
resolve 

```
☠] Android Studio (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      AndroidStudioValidator.validate (package:flutter_tools/src/android/android_studio_validator.dart:65:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>







✓] Flutter (Channel stable, 2.10.1, on Debian GNU/Linux 10 (buster) 5.4.163-17383-gbc0d0d65633b, locale en_US.UTF-8)
    • Flutter version 2.10.1 at /flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (7 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2
```

Hi @akshbswas98 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

_Originally posted by @TahaTesser in https://github.com/flutter/flutter/issues/64861#issuecomment-683780272_

**Comment by darshankawar** [comment] 2022-02-17 08:22
> ☠] Android Studio (the doctor check crashed)
>     ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
>       https://github.com/flutter/flutter/issues.
>     ✗ FormatException: Unexpected extension byte (at offset 5)

@ben700 If you reporting this error, then please note that This was a known issue that has since been fixed. The initial report was in #94060.

The fix is available on the latest master and beta channels and soon will be available on stable. Check this issue comment for your reference: #94060 (comment)

Closing this, since it is already fixed and a duplicate of original linked issue.

**Closed by darshankawar** 2022-02-17 08:22 UTC
Labels: in triage

**Comment by ben700** [comment] 2022-02-17 16:20
> #94060
I fixed by removing the beta and just installing the stable version. 

I just find people raising, you closing and them leaving 1 star reviews. Just because you correct doesn't mean the customer goes away happy!
