### ISSUE TITLE
Help text within `flutter run` is hard to scan

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#44387] opened 2019-11-07 23:17 UTC
When I do `flutter run` and want to see what keyboard shortcuts are available, pressing `h` gives me:

```
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:38605/ParKHSqj8IY=/
You can dump the widget hierarchy of the app (debugDumpApp) by pressing "w".
To dump the rendering tree of the app (debugDumpRenderTree), press "t".
For layers (debugDumpLayerTree), use "L"; for accessibility (debugDumpSemantics), use "S" (for traversal order) or "U" (for inverse hit test order).
To toggle the widget inspector (WidgetsApp.showWidgetInspectorOverride), press "i".
To toggle the display of construction lines (debugPaintSizeEnabled), press "p".
To simulate different operating systems, (defaultTargetPlatform), press "o".
To toggle the elevation checker, press "z".
To display the performance overlay (WidgetsApp.showPerformanceOverlay), press "P".
To enable timeline events for all widget build methods, (debugProfileWidgetBuilds), press "a"
To save a screenshot to flutter.png, press "s".
To repeat this help message, press "h". To detach, press "d"; to quit, press "q".
```

While this block of text reads well from the standpoint of using proper English, I find it hard to scan when I'm looking for something.  The relevant keys are at the end of each sentence, and in some cases multiple items (and keys) are mentioned on the same line with semicolons.  Furthermore, because it uses full sentences, it repeats "press" all the time, which ends up being noise. (It's also not consistent; sometimes it says "by pressing" or "use".)

I think that it would be easier to read:

```
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:38605/ParKHSqj8IY=/
The following keys are available to press:
r: 🔥 Hot reload changes while running.
R: Hot restart (and rebuild state).
w: Print widget hierarchy (debugDumpApp).
t: Print the rendering tree (debugDumpRenderTree).
L: Print the layer tree (debugDumpLayerTree)
S: Print the accessibility tree (debugDumpSemantics) in traversal order.
U: Print the accessibility tree in inverse hit test order.
i: Toggle the widget inspector (WidgetsApp.showWidgetInspectorOverride).
p: Toggle the display of construction lines (debugPaintSizeEnabled).
o: Simulate different operating systems (defaultTargetPlatform).
z: Toggle the elevation checker.
P: Display the performance overlay (WidgetsApp.showPerformanceOverlay).
a: Enable timeline events for all widget build methods (debugProfileWidgetBuilds).
s: Save a screenshot to flutter.png.
h: Repeat this help message, press "h".
d: Detach.
q: Quit.
```
This also would reduce the number of lines that would need to be wrapped on an 80-column terminal.

(As an aside, I also think that the observatory message is too long and too jargony.  Why not just "A debugger and profiler is available at: "?)

CC @InMatrix

**Comment by christopherfujino** [comment] 2019-11-08 00:25
I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/44090. The good news is that there is a PR open for this https://github.com/flutter/flutter/pull/44106.

**Closed by christopherfujino** 2019-11-08 00:25 UTC
Labels: tool
