### ISSUE TITLE
[SelectionArea] Selection Text lost when new item inserted to ListView 

### ISSUE THREAD

**Issue by dath7** [flutter/flutter#152428] opened 2024-07-27 07:57 UTC
### Steps to reproduce

Run the code below in desktop. 

### Expected results

Selection of item remains.

### Actual results

Selection of item lost when new item insert to list at 0. 
I've tried add to the list instead of inserting so the selection of item remains. 
Is there any way to fix this problem ?

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  List<String> data = ['Hello world'];

  void _incrementCounter() {
    setState(() {
      _counter++;
      data.insert(0, 'Hello world $_counter');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            SizedBox(height: 100),
            TextButton(
                onPressed: () {
                  _incrementCounter();
                },
                child: Text('add')),
            Expanded(
              child: SelectionArea(
                child: ListView.builder(
                    itemCount: data.length,
                    itemBuilder: (context, index) {
                      return Text(data[index]);
                    }),
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/user-attachments/assets/0c54983a-ab95-4e68-ad1b-88998aca20c3

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-29 07:39
This is caused by the listview rebuilding it's contents to insert the new item. An issue with the same root cause is being tracked in https://github.com/flutter/flutter/issues/124787. 

Kindly follow up in the original issue for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2024-07-29 07:39 UTC
Labels: in triage
