### ISSUE TITLE
Support 32-bit Windows as a target

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#37777] opened 2019-08-07 14:51 UTC
**For doing _development_ with Flutter _on_ 32-bit Windows, see #33862**

At this time we have no plans to add support for 32-bit Windows as a target. I'm filing this bug as a cleaner place to track this request (e.g. upvote if you want this) as well as the blocking issues were someone to want to add support in the future.

The known blockers at this point are very similar to 33862:
- 32-bit Windows build rules for the engine.
- Either [`gen_snapshot` support for generating x86 snapshots from x64](https://github.com/dart-lang/sdk/issues/31709) or tool logic to manage two copies of `gen_snapshot` on Windows.

**Comment by zhileichen** [comment] 2019-09-06 10:37
Hello, 
We have a big request for the 32-bit  windows flutter.  
We are migrating our app from mobile to desktop, however almost 30% percent of our customers runs 32-bit windows, which are mostly Windows XP SP3. Lots of old computers still run windows xp in China.
Please raise the priority to the support the 32-bit windows.

**Comment by stuartmorgan** [comment] 2019-09-06 12:37
> which are mostly Windows XP SP3

Note that separately from 32-bit, we do not plan to support XP as a target.

**Comment by zhileichen** [comment] 2019-11-05 11:57
Hello @stuartmorgan 
Is there any updates on this issue?

**Comment by stuartmorgan** [comment] 2019-11-05 16:06
As explained above, this issue exists to track votes and information, not because we expect to implement it, so there is no reason to expect updates here absent substantial new information.

The one vote for this so far has not changed our plans, especially since per your comment 32-bit support without XP support would not actually have much value.

**Comment by jkurtw** [comment] 2019-11-13 17:57
Does the fact that x86 support has been added in JIT mode address the original second point? 
https://github.com/flutter/flutter/issues/9253

**Comment by stuartmorgan** [comment] 2019-11-13 19:17
I'm not familiar with that work; it depends on how easily the approach could be applied to Windows. It sounds promising though.

**Comment by jonahwilliams** [comment] 2019-11-13 19:27
It would probably work better than it does for android to be honest, but we would need to do some work on the packaging.

**Comment by csells** [comment] 2020-01-10 16:17
@stuartmorgan given that Microsoft stops support Windows 7 in 5 days, are we thinking hypothetical 32-bit support would be limited to Windows 8 and Windows 10?

**Comment by stuartmorgan** [comment] 2020-01-13 17:43
Well, we support iOS 8 which I believe hasn't had a security update in over 4 years, so I'm not sure if the fact that Windows 7 support will end necessarily disqualifies it from being a Flutter target. But I presume we'll make the final decision about OS version separately from the question of 32-bit.

**Comment by Sunbreak** [comment] 2020-06-12 04:26
> Hello,
> We have a big request for the 32-bit windows flutter.
> We are migrating our app from mobile to desktop, however almost 30% percent of our customers runs 32-bit windows, which are mostly Windows XP SP3. Lots of old computers still run windows xp in China.
> Please raise the priority to the support the 32-bit windows.

https://gs.statcounter.com/windows-version-market-share/desktop suggusts Win10 72.9%, Win7 19.95% and WinXP 0.87% in worldwide

https://gs.statcounter.com/windows-version-market-share/desktop/china suggusts Win10 47.14%, Win7 46.79% and 3.29% in China

@zhileichen It is suggusted to deprecate WinXP support

**Comment by Sunbreak** [comment] 2020-06-30 01:31
There are some pioneers: https://github.com/flutter/flutter/issues/57793

**Comment by stuartmorgan** [comment] 2020-06-30 01:49
@Sunbreak That issue has nothing to do with this one.

**Comment by Sunbreak** [comment] 2020-06-30 02:00
> @Sunbreak That issue has nothing to do with this one.

I keep in touch with those guys on Wechat. AFAIK, the crashes happen on Win7 and somehow they make it possible to run Flutter for Windows on some Win7 32bit marchine.

The crashes are caused by absence of graphic drivers which is a surprise for them. Because they've tested on Win7 32bit/64bit before release.

**Comment by neylsongularte** [comment] 2021-05-15 00:39
+1

**Comment by phongmh307** [comment] 2021-08-17 10:05
+1

**Comment by letungcntt** [comment] 2021-08-17 10:25
+1

**Comment by linhmanh92** [comment] 2021-08-17 10:26
+1

**Comment by letungcntt** [comment] 2021-08-17 10:31
@stuartmorgan Has this problem been solved ?

**Comment by seikosantana** [comment] 2021-11-17 08:17
I also need targeting x86 support in flutter production. I don't need to be able to develop on 32 bit machine, I often develop for industrial and offices and all of them runs 32 bit version of Windows, Windows 7 SP1 and Windows 10. I really wish I can use flutter to work on those projects.

**Comment by phr34k** [comment] 2021-11-17 08:41
I second this. I also require targetting x86 support for flutter application for production. In my case I have already developed the application. I was planning for closed testing until I discovered my oversight that flutter didn't support x86 (yet?). A significant portion of hardware in industrial and offices might still run on x86.

What would actually be required to have x86 support for flutter?

- I assume some parts of the dart-vm would need to have support for it, but I'm not sure how big of a deal this is considering flutter already targets different abi's and architechtures in the first place.

**Comment by Sunbreak** [comment] 2021-11-17 09:05
https://microsoft.github.io/react-native-windows/ is maintained by Microsoft.

A lot of Office and Xbox APPs are using it. Try it for x86 please

**Comment by phr34k** [comment] 2021-11-27 17:45
> https://microsoft.github.io/react-native-windows/ is maintained by Microsoft.
> 
> A lot of Office and Xbox APPs are using it. Try it for x86 please

Unfortunately in my case that's not an option. I have already invested time for developing a workable product. Personally, I don't really mind being forced to run x64. Where it's possible I have simply converted the machines to x64 to continue a closed beta. However almost immediately the first sets of problems came to light. 

Thirdparty software dependencies. The devices/software I interact with only provide installation files with x86 compiled modules. Under a x64 host proces those LoadLibrary calls throw an badimage error. The installation package of the IHV claims to offer x64 bit support, but the reality is that it leans on the built-in x86 emulation layer. 

Outside of hardware imposed restrictions the disttribution of software dependencies can also be a driving factor of which arch to target. I'm doing my best to work around these restrictions with surogate processes and contacting the IHV for support but honestly it would be really great if flutter could also be simply be cross-compiled.

@stuartmorgan presently are there some easy wins if I wanted to have x86 support? I think I read somewhere `gen_snapshot` already makes arm32 and arm64 at the same time- I'm wondering how far off x86 support potentionally is.

**Comment by stuartmorgan** [comment] 2021-11-28 01:06
> @stuartmorgan presently are there some easy wins if I wanted to have x86 support?

I'm not sure what you are asking here. Building an x86 Flutter application would require end-to-end support, from Dart and its tooling all the way through the `flutter` tool and the Windows build template. Maybe some individual pieces of that would be easy, but I don't know what the point of implementing one miscellaneous piece of that would be without the rest.

If you're asking if the Dart parts of this work would be easy, I have no idea.

**Comment by phr34k** [comment] 2021-11-28 08:50
@stuartmorgan I'm asking for a present state for outstanding issues/scope of this topic. I mean, this was raised in 2019 but I there's also been more incremental improvents to make new platform adoptions easier. So if we could have a more present perspective on any major or minor blockers that'd be great.

For example I believe I read somewhere that `gen_shapshot ` outlined as one of the major blockers on arm has a structure where it dual target arm32 and arm64 iirc. I would imagine that these sort of improvements on other platforms can have an positive effect, making this easier now.

**Comment by stuartmorgan** [comment] 2021-11-28 11:34
I'm not aware of any changes to the known blocker list in the original description of this issue.

**Comment by fzyzcjy** [comment] 2022-03-05 14:44
Hi, IMHO many people are still using 32bit windows computers, so it is critical to support 32bit windows - otherwise they cannot use it. Is there any updates, or any workarounds supporting 32bit computers? Thanks!

**Comment by Sunbreak** [comment] 2022-03-05 15:12
You could build the engine with above PRs and Docs

- https://github.com/flutter/engine/pull/30417
- https://github.com/flutter/flutter/pull/95559
- https://github.com/flutter/website/pull/6597

**Comment by fzyzcjy** [comment] 2022-03-06 00:33
@Sunbreak Thank you! But IMHO those are "WIP", and for app in production I guess a stable build is needed.

**Comment by Letal1s** [comment] 2022-03-12 21:33
@Sunbreak are those PRs actually able to generate a x86 jit build in debug though, or are they not in a usable state yet? Trying to build a clone of that engine results in gn warning that 'angle_skip_dxgi_1_2_check' in '--args' isn't declared and '_BitScanReverse64' isn't declared, after fixing those errors I then get another error about having no 'windows-x86' snapshot in artifacts when attempting to use "flutter build" in a project with the built engine. Is this meant to work yet or is my build environment likely messed up?

**Comment by Sunbreak** [comment] 2022-03-13 00:00
cc @eggfly

**Comment by eggfly** [comment] 2022-03-13 00:13
> @Sunbreak are those PRs actually able to generate a x86 jit build in debug though, or are they not in a usable state yet? Trying to build a clone of that engine results in gn warning that 'angle_skip_dxgi_1_2_check' in '--args' isn't declared and '_BitScanReverse64' isn't declared, after fixing those errors I then get another error about having no 'windows-x86' snapshot in artifacts when attempting to use "flutter build" in a project with the built engine. Is this meant to work yet or is my build environment likely messed up?

Fixing is in progress

**Comment by cbracken** [comment] 2022-03-15 19:49
Just to copy my comments over from https://github.com/flutter/engine/pull/30417:

First off, thanks to @eggfly and others who've expressed interest, and especially thanks for small, clean patches to make supporting 32-bit Windows easier.

We've historically said we wouldn't do anything to stand in the way of fixes that make life better for those who'd like to get Flutter working on 32-bit Windows so long as those fixes don't complicate support for 64-bit Windows, which is what we officially target. 

While there are a few dedicated contributors who want to see 32-bit Windows support, there aren't currently enough contributors focusing on maintaining/improving our 32-bit Windows for it to successful "officially supported" target (nor do we have 32-bit Windows test infra, for that matter).

**Comment by eggfly** [comment] 2022-03-16 03:24
Thank you @cbracken and @timsneath and discussed in this thread.
I see, the various tiers may cost various overhead, I wonders we can let Flutter Infra do a minimum support like `win_debug_x86` compilation, and it only ensure the compilation regressions are quickly caught, can we do an evaluation and do that?

Or let me try to use the Github Actions to do the external CI jobs for windows_x86 engine, I'm not sure if I can get it done. 😄

**Comment by GithubSiXun** [comment] 2022-12-05 07:33
github.com

**Comment by GithubSiXun** [comment] 2022-12-05 07:33
Hello,
We have a big request for the 32-bit windows flutter.
We are migrating our app from mobile to desktop,About 1 million users in our company are using 32-bit windows 7. Lots of old computers still run 32-bit Windows  in China.
Please raise the priority to the support the 32-bit windows.

**Comment by GithubSiXun** [comment] 2022-12-06 02:38
@stuartmorgan Excuse me, does Flutter team plan to add support for Windows 7 32-bit operating system?

**Comment by stuartmorgan** [comment] 2022-12-06 02:46
@GithubSiXun Please see the comments above.

**Comment by yefl2064** [comment] 2022-12-23 09:31
> > @Sunbreak That issue has nothing to do with this one.
> 
> I keep in touch with those guys on Wechat. AFAIK, the crashes happen on Win7 and somehow they make it possible to run Flutter for Windows on some Win7 32bit marchine.
> 
> The crashes are caused by absence of graphic drivers which is a surprise for them. Because they've tested on Win7 32bit/64bit before release.

@Sunbreak Do you have a way to build a flutter program to run on win 32bit？ how to do that？

**Comment by Sunbreak** [comment] 2022-12-23 10:10
https://github.com/flutter/flutter/issues/37777#issuecomment-1059781046

**Comment by dasaintgray** [comment] 2023-03-06 02:57
Yes, I want these features, I have a big problem-consuming window 32bit dll in FFI, it always returns error code 193, and I found out the error is from my 32bit dll, I download dart ia32 the problem gone, but when i attach the dart code into flutter, the same error code 193.

**Comment by cbracken** [comment] 2024-06-07 21:02
I'm going to close this as not intended. We'd be more than happy to take patches that would make the code more portable between 32 and 64 bits where those issues exist, but a full solution to this would add significantly complexity to the build, tool, so I don't think we'd accept patches that fully resolve this.

As noted though, we'd be more than happy to take patches that make maintaining a 32-bit fork easier.

**Closed by cbracken** 2024-06-07 21:02 UTC
Labels: c: new feature, engine, platform-windows, customer: crowd, a: desktop, P3, team-windows, triaged-windows
