### ISSUE TITLE
The "waiting for green" bot doesn't work on the plugins repo (doesn't recognise "submit-queue" check)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#77401] opened 2021-03-05 19:08 UTC
See e.g. https://github.com/flutter/plugins/pull/3665#issuecomment-791614547.

**Comment by godofredoc** [comment] 2021-03-05 23:28
The "waiting for green" won't submit a PR that have failing checks and in this case "submit-queue" is failing.

According to the submit-queue button the tree is closed because https://github.com/flutter/plugins/runs/2036525291 is failing "analyze:stable" test.

Is this working as intended?

**Comment by Hixie** [comment] 2021-03-05 23:31
"submit-queue" on the plugins repo is like "flutter-build" on the framework repo.

**Comment by godofredoc** [comment] 2021-03-06 00:07
I'm not sure I fully understand what the problem is.  "waiting for green" didn't submit the PR because submit-queue is failing which seems the correct behavior.

Is this bug about the submit-queue not being updated or maybe the githubbot removing the label?

**Comment by Hixie** [comment] 2021-03-06 00:24
When I do this in flutter/flutter, if the tree is red (as shown by flutter-build) the bot just waits until it's green, and then lands it. That's more or less the only reason to have the label in the first place as far as I can tell. :-)
On flutter/plugins, the bot doesn't seem to wait until the tree is green (as shown by submit-queue), it just says "the tree wasn't green" and then gives up. But if I have to wait until the tree is green to set the label, I might as well just merge it myself. :-)

**Comment by godofredoc** [comment] 2021-03-06 00:52
Thanks for the explanation, now I get it.

The following list is missing the "submit-queue" check:
 https://cs.opensource.google/flutter/cocoon/+/master:app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart;l=253?q=waiting&ss=flutter%2Fcocoon

**Comment by godofredoc** [comment] 2021-03-06 01:19
PR ready for review: https://github.com/flutter/cocoon/pull/1104

If you are not in a rush to land your PR I'd like to use it to test the fix. What do you think?

**Comment by Hixie** [comment] 2021-03-06 01:28
SGTM

**Comment by Hixie** [comment] 2021-03-06 01:41
https://github.com/flutter/plugins/pull/3665 is the PR where i saw this, FWIW.

**Comment by godofredoc** [comment] 2021-03-06 01:58
The PR was merged correctly but the submit-queue check was already green. I'll close the bug for now but please reopen if you find the problem again.

**Closed** 2021-03-06 01:58 UTC
Labels: P2, team: infra
