### ISSUE TITLE
Two flutter engines are not sharing plugin data immediately

### ISSUE THREAD

**Issue by kishansr1** [flutter/flutter#114385] opened 2022-11-01 01:25 UTC
Hello
We have a flutter application with foreground android service. This service is showing a flutter view on window manager.
But problem is, if we do some processing on app (like saving to shared pref or login with firebase) it will directly not reflect on flutter view until and unless we restart the service.

## Steps to Reproduce

1. Create a basic flutter application with pressing a button save to shared pref
2. Add a method channel to create a new flutter engine from flutter engine group
3. Create a flutter widget that show the saved shared pref and make flutter engine entry point to that callback
4. Attach flutter engine to flutter view
5. Now press the button on app and then open flutter view it will reflect null, until you restart your app

**Expected results:** All native plugins data should be shared immediately

**Actual results:** We need to restart the app before it is shard

<details>
<summary>Code sample</summary>

Creating flutter engine
```kotlin
override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        setupEngine(flutterEngine, false)

        // Create new engine for flutter-view and cache
        val flutterEngineGroup = FlutterEngineGroup(context)
        val entryPoint = DartExecutor.DartEntrypoint(
            FlutterInjector.instance().flutterLoader().findAppBundlePath(),
            "viewEntryPoint"
        )
        val flutterViewEngine = flutterEngineGroup.createAndRunEngine(context, entryPoint)
        FlutterEngineCache.getInstance().put("ViewCachedEngine", flutterViewEngine)
        setupEngine(flutterViewEngine, true)
    }
```

Attaching to flutter view

```kotlin
val flutterEngine = FlutterEngineCache.getInstance().get("ViewCachedEngine")
val flutterSurfaceView = FlutterSurfaceView(serviceContext, true)
flutterView = FlutterView(serviceContext, flutterSurfaceView)
flutterView!!.attachToFlutterEngine(flutterEngine!!)
flutterEngine!!.lifecycleChannel.appIsResumed()
windowManager.addView(flutterView!!, flutterViewLayoutParams)
```

viewEntryPoint Callback

```dart
@pragma('vm:entry-point')
void viewEntryPoint() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const FlutterViewApp());
}
```

</details>

**Comment by stuartmorgan** [comment] 2022-11-01 02:26
This is a duplicate of https://github.com/flutter/flutter/issues/101691

**Closed by stuartmorgan** 2022-11-01 02:26 UTC

**Comment by kishansr1** [comment] 2022-11-01 02:36
@stuartmorgan it's not just releated to SharedPref rather I as told it's also happening with Firebase curr user also.
