### ISSUE TITLE
Support for Web Integration Testing in Flutter

### ISSUE THREAD

**Issue by ssuojae** [flutter/flutter#153422] opened 2024-08-14 09:30 UTC
### Use case

<img width="400" alt="image" src="https://github.com/user-attachments/assets/bfacd5a3-c522-4478-a8dd-bb170b3f4d0a">

<br/>
<br/>

Currently, Flutter's integration testing package does not fully support web platform testing.
I ran an integrated test to import and map the data from Firebase, but there was a problem

How about modifying the official document? The official document guides on the web integration test.
https://docs.flutter.dev/testing/integration-tests

### Proposal

I would like to request that the Flutter team provides full support for integration testing on the web platform. 

Specifically, the integration tests should be able to:
- Run seamlessly in different web browsers such as Chrome, Firefox, and Edge.
- Provide detailed feedback and logs when running tests in a web environment.
- Support common web-specific scenarios, such as handling of different screen sizes and input types.

```
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.1.1 23B81 darwin-arm64, locale en-KR)
    • Flutter version 3.22.3 on channel stable at /Users/i/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (4 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/i/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.87.2)
    • VS Code at /Users/i/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.120
    ! Error: Browsing on the local area network for Jonghyuck’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

**Comment by danagbemava-nc** [comment] 2024-08-14 10:34
Closing this as a duplicate of https://github.com/flutter/flutter/issues/117955

**Closed by danagbemava-nc** 2024-08-14 10:34 UTC
Labels: in triage
