### ISSUE TITLE
TextInputAction.next isn't working

### ISSUE THREAD

**Issue by HasanElHefnawy** [flutter/flutter#113668] opened 2022-10-19 03:30 UTC
Consider the sample below. If I remove the `style` from `ElevatedButton`, `TextInputAction.next` is working normally.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                children: <Widget>[
                  const SizedBox(height: 1000),
                  TextFormField(
                    textInputAction: TextInputAction.next,
                  ),
                  const SizedBox(height: 20),
                  TextFormField(),
                  const SizedBox(height: 20),
                ],
              ),
            ),
          ),
          ElevatedButton(
            child: const Text('Bottom Button'),
            onPressed: () {},
            style: ElevatedButton.styleFrom(
              minimumSize: const Size(double.infinity, 50),
            ),
          ),
          const SizedBox(height: 20),
        ],
      ),
    );
  }
}
```

**Comment by exaby73** [comment] 2022-10-19 08:38
Hello @HasanElHefnawy. I'm not sure what you mean by `TextInputAction.next` not working. When the keyboard is shown, the second `TextField` is hidden, and therefore Flutter isn't able to find it in the current `FocusScope`. If you scroll to make sure the second `TextField` is visible, it will focus it when you press `next`. You can ensure this behavior by manually adding a `FocusNode`. See the updated code sample.

<details>
<summary>Updated Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final focusNode = FocusNode();

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                children: <Widget>[
                  const SizedBox(height: 1000),
                  TextFormField(
                    textInputAction: TextInputAction.next,
                    onEditingComplete: () => focusNode.requestFocus(),
                  ),
                  const SizedBox(height: 20),
                  TextFormField(focusNode: focusNode),
                  const SizedBox(height: 20),
                ],
              ),
            ),
          ),
          ElevatedButton(
            child: const Text('Bottom Button'),
            onPressed: () {},
            style: ElevatedButton.styleFrom(
              minimumSize: const Size(double.infinity, 50),
            ),
          ),
          const SizedBox(height: 20),
        ],
      ),
    );
  }
}
```

</details>

This is working as intended. Closing this issue due to these reasons. Thank you.

**Closed by exaby73** 2022-10-19 08:38 UTC
Labels: in triage
