### ISSUE TITLE
What is the Rationale behind Null Safety Since Dart already has Optionals

### ISSUE THREAD

**Issue by hashweather** [flutter/flutter#78784] opened 2021-03-22 12:22 UTC
Dart already has this thing called Optionals. For example

```
void screenNavigator(BuildContext context, Screen screen,
      [StreamedResponse extraData]) {


}

```
From the above function, extraData is an Optional Argument.

Why then is the need of including nulls into the language?

**Comment by pedromassangocode** [comment] 2021-03-22 13:20
Hi @hashweather 
From what I can see, the issue is related to Dart than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-22 13:20 UTC
Labels: in triage
