### ISSUE TITLE
'constraints.hasBoundedHeight': is not true.

### ISSUE THREAD

**Issue by AbhinaiVatsal** [flutter/flutter#83555] opened 2021-05-28 11:58 UTC
>  ListView.builder(
              itemCount: 10,
              itemBuilder: (context, snapshot) {
                return ListView.builder(
                    shrinkWrap: true,
                    itemCount: 50,
                    scrollDirection: Axis.horizontal,
                    itemBuilder: (_, i) {
                      return Text('text$i');
                    });
              })),

Getting `'constraints.hasBoundedHeight': is not true.` at the inside ListView.

**Comment by TahaTesser** [comment] 2021-05-28 13:03
Hi @AbhinaiVatsal 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/78796
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-28 13:03 UTC
Labels: in triage
