### ISSUE TITLE
firebase_messaging not working if include flutter_local_notifications package on iOS

### ISSUE THREAD

**Issue by ishakdas** [flutter/flutter#46469] opened 2019-12-08 09:06 UTC
Hello to everyone
I was able to send data notification in the background via android but I think there is a problem for ios.
Is this Problem a solved issue or is it still going on?

**Comment by iapicca** [comment] 2019-12-09 11:46
Hi @ishakdas 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-09 11:46 UTC
