### ISSUE TITLE
refactor->Extract->Flutter Widget

### ISSUE THREAD

**Issue by burakylmz50** [flutter/flutter#26603] opened 2019-01-15 20:40 UTC
I get this error : reference to an enclosing class method cannot be extracted

Help me

**Comment by kangwang1988** [comment] 2019-01-16 05:42
@burakylmz50 
Paste result for `flutter doctor -v`.
Provide a minimal demo project(main.dart) to help reproduce it.

**Comment by burakylmz50** [comment] 2019-01-16 09:39
flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.253], locale tr-TR)
    • Flutter version 1.0.0 at C:\Program Files\flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Burak YILMAZ\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by zoechi** [comment] 2019-01-16 09:42
The issue is related to your code, without your code and what part of the code you had selected when you invoked the refactoring there is no way to diagnose if this is an issue or working as intended.

**Comment by zoechi** [comment] 2019-01-25 09:42
Duplicate of #27050

**Closed by zoechi** 2019-01-25 09:42 UTC
Labels: waiting for customer response

**Comment by Flutey** [comment] 2019-04-12 06:58
You can create a class called RadialSeekBar and then reference it in Extended.

**Comment by Flutey** [comment] 2019-04-12 06:59
You can create a class called something and then reference it in Extended.
