### ISSUE TITLE
Packages are not supported when using the legacy build system, but it is enabled in xcode preferance

### ISSUE THREAD

**Issue by SupriyaKamat** [flutter/flutter#102207] opened 2022-04-20 10:27 UTC
Packages are not supported when using the legacy build system, but it is enabled in xcode preferance
Facing issue when trying to integrate Firebase iOS SDK in xcode

**Comment by darshankawar** [comment] 2022-04-20 12:55
Closing this as duplicate of https://github.com/flutter/flutter/issues/76868

**Closed by darshankawar** 2022-04-20 12:55 UTC
Labels: in triage
