### ISSUE TITLE
[Web]: Difference in asset rendering using canvasKit and html on Windows

### ISSUE THREAD

**Issue by ferraridamiano** [flutter/flutter#76187] opened 2021-02-17 08:45 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: add any image.png  under res/image.png and add it on pubspec.yaml, paste the following code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Image.asset('res/image.png', width: 40,)
      ),
    );
  }
}
```

3. Run: ```flutter run -d chrome --web-renderer canvaskit```

**Actual results:**
The border of the image is really pixelated, it looks like a low resolution image (which is not)
![canvas](https://user-images.githubusercontent.com/34270884/108177244-4320dd80-7103-11eb-8106-4ab8d6369f14.jpg)

**Expected results:**
The result I am expecting is the result that I get with: ```flutter run -d chrome --web-renderer html```
![html](https://user-images.githubusercontent.com/34270884/108177697-d528e600-7103-11eb-86de-267edc10e4bb.jpg)

You can spot this behaviour just with image asset. With icons everything is good.

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel beta, 1.26.0-17.6.pre, on Microsoft Windows [Versione 10.0.19042.804], locale it-IT)
    • Flutter version 1.26.0-17.6.pre at C:\flutter
    • Framework revision a29104a69b (15 hours ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Damia\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Damia\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0
[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.68
• No issues found!
```

</details>

This happens also on [my web app](https://ferraridamiano.github.io/ConverterNOW/#/), if you open it and open the drawer you will see that the icons looks like low resolution (just on desktop).

**Comment by darshankawar** [comment] 2021-02-17 09:58
@ferraridamiano 
I verified this issue on latest master with a sample asset and rendered using canvaskit. I didn't see any difference in rendering.

<img width="1300" alt="Screenshot 2021-02-17 at 3 25 10 PM" src="https://user-images.githubusercontent.com/67046386/108187504-89dafb80-7134-11eb-9ce5-ab6c91d7c73b.png">

Left is canvaskit, right is html.

Can you switch to latest master and try again with the image you have and see if issue persists or no ?  There were few canvaskit issues fixed recently and merged in master and may not have landed in beta yet.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.126, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
    • Flutter version 1.27.0-2.0.pre.126 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 50897c98fc (5 hours ago), 2021-02-16 20:13:53 -0800
    • Engine revision 9bcb3bfb0e
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM A260G (mobile)                  • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5556    • android-x86    • Android 8.1.0 (API 27)
      (emulator)
    • macOS (desktop)                    • macos            • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome
      88.0.4324.150

! Doctor found issues in 1 category.

```

</details>

**Comment by ferraridamiano** [comment] 2021-02-17 10:44
Hi @darshankawar, the issue exists also on master branch. It happens when you resize the image to be smaller, try with flutter logo and set `width: 200`
![html](https://user-images.githubusercontent.com/34270884/108192906-1ecdfc80-7115-11eb-9c96-393d0e455136.jpg) ![canvaskit](https://user-images.githubusercontent.com/34270884/108193113-62c10180-7115-11eb-8d09-7f8db58ef0bc.jpg)

Left is html, right is canvaskit. Can you spot the difference?

**Comment by darshankawar** [comment] 2021-02-17 11:32
@ferraridamiano 
Thanks. I can clearly spot the difference between the images you shared above.

I tried with a flutter logo png on latest beta as well as on master and by resizing it to 150 and 200, but still unable to see any difference.  Maybe I need to wear glasses :-))

<img width="229" alt="ck_mst" src="https://user-images.githubusercontent.com/67046386/108198332-81d58880-7141-11eb-92ad-ea81d1cf99c5.png">
<img width="226" alt="ht_mst1" src="https://user-images.githubusercontent.com/67046386/108198335-839f4c00-7141-11eb-9af8-4af3deb469ee.png">

First is canvaskit, below is html.  

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.126, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
    • Flutter version 1.27.0-2.0.pre.126 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 50897c98fc (7 hours ago), 2021-02-16 20:13:53 -0800
    • Engine revision 9bcb3bfb0e
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.

```

</details>

Can you share the images you are using, so that I can try with those and see if I succeed ?

**Comment by ferraridamiano** [comment] 2021-02-17 12:47
It is very strange! Everything is the same of you, except for the OS. 
[Here you can download the 2 images I used](https://github.com/flutter/flutter/files/5995615/res.zip)
I set termometer to `width: 40` and flutter logo to `width: 200`

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.27.0-2.0.pre.126, on Microsoft Windows [Versione 10.0.19042.804], locale it-IT)
    • Flutter version 1.27.0-2.0.pre.126 at C:\flutter
    • Framework revision 50897c98fc (8 hours ago), 2021-02-16 20:13:53 -0800
    • Engine revision 9bcb3bfb0e
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Damia\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Damia\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2021-02-17 13:51
Thanks for providing images @ferraridamiano. Tried both images with width as you mentioned, but still rendered properly. Top is canvaskit and below it is html respectively.

<img width="188" alt="Screenshot 2021-02-17 at 7 11 19 PM" src="https://user-images.githubusercontent.com/67046386/108213355-eea64e00-7154-11eb-981d-2399585702a8.png">
<img width="348" alt="Screenshot 2021-02-17 at 7 17 43 PM" src="https://user-images.githubusercontent.com/67046386/108213362-f0701180-7154-11eb-80b8-0938c3616c4b.png">

Since you are on Windows, it may be the factor. Since I don't have Windows machine to verify, I am keeping this issue open for further investigation.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-17.6.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a29104a69b (19 hours ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM G975F (mobile)           • RZ8M802WY0X   • android-arm64  • Android 10
      (API 29)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 88.0.4324.150

! Doctor found issues in 1 category.

```

</details>

**Comment by ferraridamiano** [comment] 2021-02-17 14:02
Thank you!
Here I published a repo with the above issue:
https://github.com/ferraridamiano/demoBugCanvasKit

**Comment by yjbanov** [comment] 2021-02-17 17:16
I recently landed a fix for a similar issue (https://github.com/flutter/flutter/issues/73714), so I expected this to be fully fixed, although I haven't tried a Windows computer. I'll take a look.

**Comment by yjbanov** [comment] 2021-02-22 23:25
I can reproduce _an_ issue on Windows (I think it depends more on the monitor than on the OS), although I'm not sure it manifests as described here. What I'm seeing is that `FilterQuality.medium` looks _higher_ quality than `FilterQuality.high`. For example, look at the downscaled thermometer icon below. Notice that the second last (medium quality) looks better than the last one (high quality):

![flutter-filter-quality](https://user-images.githubusercontent.com/211513/108783213-ea49ae80-7521-11eb-9679-9b6626a805c3.PNG)

Deployed build: https://yjbanov.web.app/issues/76187/#/

Code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: [
          Column(
            children: [
              Image.asset('res/logo.jpg', width: 200, filterQuality: FilterQuality.none),
              Image.asset('res/logo.jpg', width: 200, filterQuality: FilterQuality.low),
              Image.asset('res/logo.jpg', width: 200, filterQuality: FilterQuality.medium),
              Image.asset('res/logo.jpg', width: 200, filterQuality: FilterQuality.high),
            ],
          ),
          Column(
            children: [
              Image.asset('res/temperatura.png', width: 200, filterQuality: FilterQuality.none),
              Image.asset('res/temperatura.png', width: 200, filterQuality: FilterQuality.low),
              Image.asset('res/temperatura.png', width: 200, filterQuality: FilterQuality.medium),
              Image.asset('res/temperatura.png', width: 200, filterQuality: FilterQuality.high),
            ],
          ),
          Column(
            children: [
              SizedBox(width: 30, height: 30, child: Image.asset('res/temperatura.png', width: 200, filterQuality: FilterQuality.none)),
              SizedBox(width: 30, height: 30, child: Image.asset('res/temperatura.png', width: 200, filterQuality: FilterQuality.low)),
              SizedBox(width: 30, height: 30, child: Image.asset('res/temperatura.png', width: 200, filterQuality: FilterQuality.medium)),
              SizedBox(width: 30, height: 30, child: Image.asset('res/temperatura.png', width: 200, filterQuality: FilterQuality.high)),
            ],
          ),
        ],
      ),
    );
  }
}
```

@ferraridamiano as a workaround, try using `FilterQuality.medium` on the image. In the meantime, I'll ping the Skia team.

**Comment by yjbanov** [comment] 2021-02-24 00:15
So, it looks like this works as intended. Our "medium" and "high" may be misleading. What's happening is that the scaling algorithm used for "high" is better than "medium" when scaling up. However, when scaling _down_, frequently "medium" is better than "high". I'm going to document this better in our API docs.

Long-term the Skia team is recommending that we expose sampling API directly, giving more precise control than what the current `FilterQuality` enum provides. I'm going to file a separate issue for that.

**Closed** 2021-03-10 23:25 UTC
Labels: P4, a: assets, a: images, e: web_canvaskit, engine, passed first triage, platform-web, platform-windows
