### ISSUE TITLE
[web]: I would like to constrain the size of my app in a browser using CSS

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#35194] opened 2019-06-27 16:39 UTC
I would like set the min and max widths of my app, and have it center but using CSS in index.html. While I can do it with Flutter widgets, they're unnecessary (and potentially incorrect) for running the app on Android or iOS.

Ideally, it'd be great if something like the following worked:

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>hauz</title>
  <style>
    body {
      width: 300px;
      max-width: 500px;
      margin: auto;
    }
  </style>
</head>

<body>
  <script src="main.dart.js" type="application/javascript"></script>
</body>

</html>

**Comment by ferhatb** [comment] 2019-07-11 22:31
this will be handled through a separate runApp entrypoint that allows add-to-app feature. For now the only workaround is to use iframe to host.

**Comment by rostopira** [comment] 2019-07-13 10:43
Looks like a duplicate of #32329

**Comment by ferhatb** [comment] 2020-04-01 18:27
Duplicate of #32329

**Closed by ferhatb** 2020-04-01 18:27 UTC
Labels: platform-web, severe: new feature
