### ISSUE TITLE
iOS build failed on 1.17.5 - Invalid `Podfile` file: cannot load such file

### ISSUE THREAD

**Issue by linusyoung** [flutter/flutter#61130] opened 2020-07-08 22:13 UTC
iOS build failed under flutter version 1.17.5 - stable channel. Once it's switch to dev channel, build is successful.

[Codemagic build link](https://codemagic.io/app/5f05a0fb37f3550011d48223/build/5f05a2c529657a000d829420)

output:
```
== Building for iOS ==

> /usr/local/bin/flutter build ios --release --no-codesign
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building club.swimmingbeaver.fivehundreds for device (ios-release)...
Running pod install...                                              2.2s
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: cannot load such file -- /Users/builder/programs/flutter/packages/flutter_tools/bin/podhelper.
```

**Comment by darshankawar** [comment] 2020-07-09 07:19
@linusyoung, see [this](https://github.com/flutter/flutter/issues/59522#issuecomment-651271208) comment.
Closing this as duplicate of [59522](https://github.com/flutter/flutter/issues/59522)

If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by darshankawar** 2020-07-09 07:19 UTC
