### ISSUE TITLE
TextField on desktop - trying to select text just scrolls the content

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#71105] opened 2020-11-23 20:56 UTC
### Steps to reproduce

Render a `TextField` on desktop. I used the following properties:

```dart
class MyTextField extends StatelessWidget {
  const MyTextField({
    Key? key,
    this.focusNode,
    this.controller,
    this.obscureText = false,
  }) : super(key: key);

  final FocusNode? focusNode;
  final TextEditingController? controller;
  final bool obscureText;

  static const InputBorder _inputBorder = OutlineInputBorder(
    borderSide: BorderSide(color: Color(0xff999999)),
    borderRadius: BorderRadius.zero,
  );

  @override
  Widget build(BuildContext context) {
   return TextField(
      controller: controller,
      focusNode: focusNode,
      cursorWidth: 1,
      obscureText: obscureText,
      cursorColor: Colors.black,
      style: const TextStyle(fontFamily: 'Verdana', fontSize: 11),
      decoration: InputDecoration(
        fillColor: Colors.white,
        hoverColor: Colors.white,
        filled: true,
        contentPadding: const EdgeInsets.fromLTRB(3, 13, 0, 4),
        isDense: true,
        enabledBorder: _inputBorder,
        focusedBorder: _inputBorder,
        disabledBorder: _inputBorder,
      ),
    );
}
```

Then put the text field in a limited-width container:

```dart
SizedBox(
  width: 100,
  child: MyTextField(),
)
```

Now type more text in the field that will fit, then try to use the mouse cursor to select text.

### Expected results

You expect to be able to select the text

### Actual results:

When you drag the mouse cursor, it scrolls the text rather that selecting it:

![ezgif-7-2e3348e91933](https://user-images.githubusercontent.com/15253456/100013588-efb02500-2d89-11eb-9545-b3ef0154907e.gif)

### Version info

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.328, on Mac OS X 10.15.3 19D76 darwin-x64, locale en-US)
    • Flutter version 1.24.0-8.0.pre.328 at /Users/tvolkert/project/flutter/flutter
    • Framework revision a5519dc75e (3 days ago), 2020-11-20 11:18:07 -0800
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)
```

FYI @justinmc @stuartmorgan

**Comment by stuartmorgan** [comment] 2020-11-23 21:09
Duplicate of https://github.com/flutter/flutter/issues/59141

**Closed by stuartmorgan** 2020-11-23 21:09 UTC
Labels: P3, a: desktop, a: mouse, a: text input
