### ISSUE TITLE
Execution failed for task ':app:processReleaseResources'. with minSdkVersion as 21

### ISSUE THREAD

**Issue by jarriaza-102** [flutter/flutter#27551] opened 2019-02-05 17:44 UTC
I am getting an issue using minSdkVersion as 21, I saw that the majority of examples use the 16 API, but I couldn't use that cuz I am using some dependencies that require that API version.
The issue that I am getting is this:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Android resource linking failed
  Output:  C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\incremental\mergeReleaseResources\merged.dir\values\values.xml:137: error: resource android:attr/fontVariationSettings not found.
  C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\incremental\mergeReleaseResources\merged.dir\values\values.xml:137: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: C:\Users\joseph.arriaza\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\42d72a25de05c0a46e75cddecb240d5d\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\joseph.arriaza\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\merged_manifests\release\processReleaseManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\processed_res\release\processReleaseResources\out\resources-release.ap_\
          -R\
          @C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\incremental\processReleaseResources\resources-list-for-resources-release.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\generated\not_namespaced_r_class_sources\release\processReleaseResources\r\
          --custom-package\
          com.archangelsystems.tagueo\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\symbols\release\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\joseph.arriaza\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\4889927745807dec05ed4fe733f46abb\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\joseph.arriaza\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\4889927745807dec05ed4fe733f46abb\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: C:\Users\joseph.arriaza\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\42d72a25de05c0a46e75cddecb240d5d\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\joseph.arriaza\AppData\Local\Android\sdk\platforms\android-27\android.jar\
          --manifest\
          C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\merged_manifests\release\processReleaseManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\processed_res\release\processReleaseResources\out\resources-release.ap_\
          -R\
          @C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\incremental\processReleaseResources\resources-list-for-resources-release.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\generated\not_namespaced_r_class_sources\release\processReleaseResources\r\
          --custom-package\
          com.archangelsystems.tagueo\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\joseph.arriaza\Desktop\proyects\tagueoflutter\build\app\intermediates\symbols\release\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      15.5s
Gradle task assembleRelease failed with exit code 1

And this is my build.graddle

apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.archangelsystems.tagueo"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

**Comment by mklim** [comment] 2019-02-06 02:30
This is a duplicate of #27106.

[This comment](https://github.com/flutter/flutter/issues/27106#issuecomment-458366675) has more details and info on how to fix the compile problem.

**Closed by mklim** 2019-02-06 02:30 UTC
