### ISSUE TITLE
Could not determine the dependencies of task ':permission_handler:compileDebugAidl'.

### ISSUE THREAD

**Issue by pakindessama** [flutter/flutter#63666] opened 2020-08-13 14:29 UTC
```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':permission_handler:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-29           
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 1s                                                   
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        62.0s
Exception: Gradle task assembleDebug failed with exit code 1
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Linux, locale en_CA.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

```

## pubspec.yaml

```javascript
...
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.7+3
  dio: ^3.0.9
  json_model: ^0.0.2
  json_annotation: ^2.2.0
  json_serializable: ^2.0.0
  provider: ^4.1.3
  intl: ^0.16.1
  fluttertoast: ^4.0.1
  webview_flutter: ^0.3.22+1
  device_info: ^0.4.2+4
  logger: ^0.9.1
  loading: ^1.0.2
  loading_overlay: ^0.2.1
  flutter_statusbarcolor: ^0.2.3
  image_picker: ^0.6.7+4
  simple_image_crop: ^0.1.3
  uuid: ^2.2.0
  crypto: ^2.1.4
  xml2json: ^4.2.0
  cached_network_image: ^2.2.0+1
  flutter_cache_manager: ^1.4.1
  video_player: ^0.10.11+2
  chewie: ^0.9.10
  wakelock: ^0.1.4+2
  file_picker: ^1.13.0+1
  flutter_staggered_grid_view: ^0.3.1
  material_design_icons_flutter: ^4.0.5345
  city_pickers: ^0.1.30
  qr_flutter: ^3.2.0
  permission_handler: 5.0.1+1
...
```

## I already tried 
> flutter pub cache repair
> flutter clean

**Comment by TahaTesser** [comment] 2020-08-13 14:59
Hi @pakindessama 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Baseflow/flutter-permission-handler/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-13 14:59 UTC

**Comment by pakindessama** [comment] 2020-08-15 07:17
> Hi @pakindessama
> From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Baseflow/flutter-permission-handler/issues).
> Closing, as this isn't an issue with Flutter itself.
> If you disagree, please write in the comments,
> providing your `flutter doctor -v`, your `flutter run -v`, your `pubspec.yaml`
> a minimal reproducible code sample that does not use 3rd party plugins,
> and I will reopen it.
> Thank you

You are right. I tested the same code on another laptop and it is working. Thanks
