### ISSUE TITLE
Flutter SDK Tools is marked as obsolete in android studio.

### ISSUE THREAD

**Issue by JanKaifer** [flutter/flutter#51793] opened 2020-03-02 20:06 UTC
## Steps to Reproduce

1. Install Android Studio
2. run `flutter doctor`

## Logs

```
$ flutter doctor            
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.


$ flutter doctor --android-licenses
Android sdkmanager tool not found (/home/pearman/Android/Sdk/tools/bin/sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.
```

The reason for this is that Flutter SDK tools are not installed by default and they are not even shown in the SDK install manager in Android studio (It hides obsolete packages by default.)

**Comment by yogeshck** [comment] 2020-03-03 08:24
I encountered the same issue while installing flutter. I'm still looking for a solution

**Comment by TahaTesser** [comment] 2020-03-03 08:30
Duplicate of [#51712](https://github.com/flutter/flutter/issues/51712)

**Closed by TahaTesser** 2020-03-03 08:30 UTC

**Comment by siberiawolf** [comment] 2020-03-05 11:50
Thanks a lot. I checked my Android Studio, and installed Android SDK Tools. The issues fixed.

<img width="776" alt="WX20200305-193913@2x" src="https://user-images.githubusercontent.com/3274949/75978973-8eee6d00-5f1a-11ea-8fbb-11b2ff6ef9a9.png">

**Comment by Zizico2** [comment] 2020-03-08 23:54
I've done this and flutter still complains about sdkmanager being outdated, if I try to update it, I get this:
`Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more`

I can't seem to solve this (all I did was reinstalling flutter and the Android sdk as I can't find anyone else wit this problem).

**Comment by blacksu** [comment] 2020-03-21 06:38
> Thanks a lot. I checked my Android Studio, and installed Android SDK Tools. The issues fixed.
> 
> <img alt="WX20200305-193913@2x" width="776" src="https://user-images.githubusercontent.com/3274949/75978973-8eee6d00-5f1a-11ea-8fbb-11b2ff6ef9a9.png">

but I can‘t find **Android SDK Tools** now,what's your Android studio Version？mine is 3.6.1
![image](https://user-images.githubusercontent.com/12581632/77221105-897f5c80-6b81-11ea-833e-ad4db39e59a9.png)

**Comment by blacksu** [comment] 2020-03-21 06:49
> > Thanks a lot. I checked my Android Studio, and installed Android SDK Tools. The issues fixed.
> > <img alt="WX20200305-193913@2x" width="776" src="https://user-images.githubusercontent.com/3274949/75978973-8eee6d00-5f1a-11ea-8fbb-11b2ff6ef9a9.png">
> 
> but I can‘t find **Android SDK Tools** now,what's your Android studio Version？mine is 3.6.1
> ![image](https://user-images.githubusercontent.com/12581632/77221105-897f5c80-6b81-11ea-833e-ad4db39e59a9.png)

I download a zip from https://androidsdkmanager.azurewebsites.net/SDKTools,and unzip it.now I resolve this Problem.

**Comment by siberiawolf** [comment] 2020-03-23 08:45
> > Thanks a lot. I checked my Android Studio, and installed Android SDK Tools. The issues fixed.
> > <img alt="WX20200305-193913@2x" width="776" src="https://user-images.githubusercontent.com/3274949/75978973-8eee6d00-5f1a-11ea-8fbb-11b2ff6ef9a9.png">
> 
> but I can‘t find **Android SDK Tools** now,what's your Android studio Version？mine is 3.6.1
> ![image](https://user-images.githubusercontent.com/12581632/77221105-897f5c80-6b81-11ea-833e-ad4db39e59a9.png)

Mine is 3.6.1,too. Try check **Hide Obsolete Packages** button.

**Comment by vchar00** [comment] 2020-04-22 04:33
https://robbinespu.gitlab.io/blog/2020/03/03/flutter-issue-fixed-android-license-status-unknown-on-windows/

**Comment by MojtabaTavakkoli** [comment] 2020-04-25 04:11
It's not there for me. 
![image](https://user-images.githubusercontent.com/18093612/80270735-e6fe5000-86cf-11ea-9f54-1763dc49c804.png)


and this is the `flutter-doctor`:
```
`[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at D:\FlutterSDK\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\mojta\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.`
```

**Comment by vchar00** [comment] 2020-04-25 22:38
hey, try this:

### First
1. **Go to Android SDK Folder *(in ur case: C:\Users\mojta\AppData\Local\Android\sdk)***
1. **Delete `tools` folder**
1. **Re-open Android Studio and navigate to `SDK Tools` tab**
1. **check `Hide Obsolete Packages` button**
1. **Install Android SDK Tools (Obsolete)**
1. **Install Android SDK Command-line Tools (latest)**

### Second
1. **Go to Android SDK Folder (again)**
2. **Open the `bin` folder inside `tools` in shell**
3. **Type: `sdkmanager.bat --licenses` and accept all**
4. **Try now: `flutter doctor` or `flutter doctor --android-licenses`**

**Comment by 49paunilay** [comment] 2020-05-28 20:59
![IMG_20200529_004000](https://user-images.githubusercontent.com/52963703/83193104-1f240300-a154-11ea-90d4-cdcdd90e0e68.jpg)
Same with me android tools obselete not found

**Comment by iam-navneeth-k** [comment] 2020-06-26 12:27
> hey, try this:
> 
> ### First
> 1. **Go to Android SDK Folder _(in ur case: C:\Users\mojta\AppData\Local\Android\sdk)_**
> 2. **Delete `tools` folder**
> 3. **Re-open Android Studio and navigate to `SDK Tools` tab**
> 4. **check `Hide Obsolete Packages` button**
> 5. **Install Android SDK Tools (Obsolete)**
> 6. **Install Android SDK Command-line Tools (latest)**
> 
> ### Second
> 1. **Go to Android SDK Folder (again)**
> 2. **Open the `bin` folder inside `tools` in shell**
> 3. **Type: `sdkmanager.bat --licenses` and accept all**
> 4. **Try now: `flutter doctor` or `flutter doctor --android-licenses`**

this worked man tysm

**Comment by Sowndharya1143** [comment] 2020-07-17 12:41
> hey, try this:
> 
> ### First
> 1. **Go to Android SDK Folder _(in ur case: C:\Users\mojta\AppData\Local\Android\sdk)_**
> 2. **Delete `tools` folder**
> 3. **Re-open Android Studio and navigate to `SDK Tools` tab**
> 4. **check `Hide Obsolete Packages` button**
> 5. **Install Android SDK Tools (Obsolete)**
> 6. **Install Android SDK Command-line Tools (latest)**
> 
> ### Second
> 1. **Go to Android SDK Folder (again)**
> 2. **Open the `bin` folder inside `tools` in shell**
> 3. **Type: `sdkmanager.bat --licenses` and accept all**
> 4. **Try now: `flutter doctor` or `flutter doctor --android-licenses`**

It worked Thanks

**Comment by 49paunilay** [comment] 2020-07-28 16:45
Finally got time to try this.
Thanks man it worked

**Comment by ahmedaniss25** [comment] 2020-12-08 12:45
problem fix here : https://youtu.be/LEvZUI95Zv4
