### ISSUE TITLE
[go_router] BUG - Jumping to the next navigation, or returning to the navigation, will eventually lead to a page rebuild already on the stack

### ISSUE THREAD

**Issue by medz** [flutter/flutter#101967] opened 2022-04-15 05:27 UTC
## Steps to Reproduce

defined routes:
```dart
final routes = [
  GoRoute(
    path: '/',
    builder:(context, state) => HomePage(),
  ),
  GoRoute(
    path: '/page-1',
    builder:(context, state) => Page1(),
  ),
  GoRoute(
    path: '/page-2',
    builder:(context, state) => Page2(),
  ),
];
```

Jump from `/` to `/page-1` then `HomePage` will be rebuilt once, if jump from `/page-1` to `/page-2` then both `HomePage` and `Page1` will be rebuilt Rebuilt!

So does pop!

**Expected results:** 

Routing page jumps should not relocate pages already in the stack!

**Actual results:** 

Every time a push or pop route is made, the pages already in the stack are incorrectly recreated!

**Comment by bernaferrari** [comment] 2022-04-16 19:21
Oh yeah, this is known and the reason I don't use go_router. It is surprising how it can't handle such as simple scenario.

Duplicate of https://github.com/flutter/flutter/issues/99577 https://github.com/flutter/flutter/issues/99124

You should probably check beamer or other router methods, they can handle this.

**Comment by danagbemava-nc** [comment] 2022-04-18 07:17
Closing as a duplicate based on the above comment. 

Thank you

**Closed by danagbemava-nc** 2022-04-18 07:17 UTC
Labels: in triage
