### ISSUE TITLE
Release PRs do not run all the targets in presubmit

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#131279] opened 2023-07-25 18:07 UTC
https://github.com/flutter/engine/pull/43982 needed to regenerate several goldens. However, the test Linux mac_unopt isn't marked as a release build.

The expectation is all tests run, regardless if they produce artifacts.

**Comment by drewroengoogle** [comment] 2023-07-25 18:34
Thanks for the heads up, taking a look to understand why these presubmit tests aren't running. From a quick check in cocoon it seems that we only are supposed to be filtering postsubmit targets based on the `release_build` property.

**Comment by drewroengoogle** [comment] 2023-07-25 18:53
@CaseyHillers I'm still investigating, but so far it doesn't seem like it is related to whether it is marked as a `release_build` or not, as targets like `Linux Fuchsia` and `Linux Fuchsia FEMU` were run without being release builds ([code](https://github.com/flutter/engine/blob/main/.ci.yaml#L192-L212)).

**Comment by drewroengoogle** [comment] 2023-07-25 20:56
Looking at how the ci.yaml is pulled, I think the lack of these targets is related to the fact that .ci.yaml is very out of sync. The candidate branch does not have the `unopt` targets, so when it validates the ci.yaml, it isn't in the list of targets to trigger.

**Comment by godofredoc** [comment] 2023-08-18 22:45
release_build = true is used to identify which builds are going to be running on dart-internal (only builds that generate artifacts) everything else should still be scheduled by the cocoon scheduler. Also this configuration only impacts presubmit.

Also I see the Linux_mac_unopt in the list of presubmit tests:

![image](https://github.com/flutter/flutter/assets/54371434/4df0b20f-a398-4083-a059-e63b610a88f7)

@CaseyHillers is this working as intended?

**Comment by drewroengoogle** [comment] 2023-08-21 15:06
@godofredoc This issue can probably be closed.

The actual issue was related to the fact that ci.yaml in candidate branches compares targets to what is in the main ci.yaml, and if they don't match up, then they don't run. With some of the engine_v2 changes, some obsolete targets got removed from main, and new targets were added, but these changes weren't applied to the candidate branch. The resolution was to cherrypick the new targets into the candidate branch (https://github.com/flutter/flutter/issues/131351).

**Closed** 2023-08-21 15:06 UTC
Labels: team-infra
