### ISSUE TITLE
TextField not receiving input on mobile keyboard

### ISSUE THREAD

**Issue by master-pojo** [flutter/flutter#88833] opened 2021-08-25 00:10 UTC
<details>
<summary>Code Sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: LayoutBuilder(
          builder: (context, constraints) {
            if(MediaQuery.of(context).size.width < 1000) {
              return TextField(
                keyboardType: TextInputType.number,
                inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                controller: TextEditingController(text: ''),
              );
            }
            return Container();
          },
        ),
      ),
    );
  }
}
```
</details>

## Steps to Reproduce

1. Run the provided code sample on mobile
2. Click on the text field
3. Click any numeric button on the mobile keyboard.

**Expected results:** The text field receives the input.

**Actual results:** The text field does not receive the input.

**Additional Observations:** 

1. If you click on the text field twice, then using the mobile keyboard works.
2. If you click on any of the non-numeric keys (dash, space, comma, period), then click on a numeric key the text field will accept the input.
3. If you remove the if statement in the LayoutBuilder in the provided code sample, the mobile keyboard works.
4. If you remove the keyboardType of the TextField in the provided code sample, the mobile keyboard works.
5. If you remove the controller of the TextField in the provided code sample, the mobile keyboard works.

<details>
  <summary>Logs</summary>

```
flutter analyze
Analyzing testing...
No issues found! (ran in 1.7s)
```

```
flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.2.3 at D:\Flutter\flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\KyleRoth\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at D:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\AndroidStudio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!

```
[log.txt](https://github.com/flutter/flutter/files/7042721/log.txt)

</details>

**Comment by akhlaqshah** [comment] 2021-08-25 07:25
hello @master-pojo , please initialize the controller outsize of the build method, and make it final as your class is StatelessWidget,

like this one

`final textController = TextEditingController();`

and pass textController to TextField's controller parameter

like this
`if (MediaQuery.of(context).size.width < 1000) {
                return TextField(
                  keyboardType: TextInputType.number,
                  inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                  controller: textController,
                );
              }`

**Comment by maheshmnj** [comment] 2021-08-25 10:17
@master-pojo Thanks for filing the issue I am able to reproduce the issue and the observations looks valid, reproduced on the latest `stable 2.2.3` and the `master 2.5.0-7.0.pre.188` channel on an Android emulator (api 30), The same code sample works fine on IOS, macOS, and the web

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-7.0.pre.188, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.188 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea5dacebc2 (28 hours ago), 2021-08-24 11:49:07 +0530
    • Engine revision 710af46d53
    • Dart version 2.15.0 (build 2.15.0-42.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 11 (mobile)        • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 11 (mobile)        • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```
</details>

**Comment by bleroux** [comment] 2024-02-14 14:09
As pointed out in some comments, for the first and fourth text fields the issue is related to recreating a new TextEditingController instance on each build using the `TextEditingController(String text)` constructor.

For the fifth text field the issue is no longer reproducible. It was fixed in https://github.com/flutter/flutter/pull/123777, which takes care of setting a proper selection when a text field is focused and its controller selection is not initialized.
As mentioned in some comments, a workaround was to use `TextEditingController.fromValue` instead. This is no longer required since https://github.com/flutter/flutter/pull/123777.

Closing this issue because the main issue was fixed in https://github.com/flutter/flutter/pull/123777.

TextEditingController(String text) needs more documentation. This is tracked in https://github.com/flutter/flutter/issues/95978.

**Closed by bleroux** 2024-02-14 14:09 UTC
Labels: a: text input, platform-android, framework, has reproducible steps, P2, found in release: 2.2, found in release: 2.5, team-android, triaged-android, multiteam-retriage-candidate
