### ISSUE TITLE
Adding borderRadius to a container removes all of its content

### ISSUE THREAD

**Issue by johhansantana** [flutter/flutter#29267] opened 2019-03-13 02:43 UTC
Hello

I am trying to have a container that has a left border in a card widget that has a border radius on the left, so that the borderRadius is the same as the Card widget

This is my code:
https://gist.github.com/johhansantana/2c646723624d816412dc0ad4a8c4f16a#file-main-dart-L36

Notice that on line `36` I have commented it in order to make it work since uncommenting these lines will result in the following:
![Screenshot_20190312-222701](https://user-images.githubusercontent.com/9933887/54249402-78375500-4516-11e9-8f5a-bd2ef9509eeb.jpg)

Instead of what I want (without the border radius on the left):
![53439664_1998331043609733_7479725068273057792_n](https://user-images.githubusercontent.com/9933887/54249624-3c50bf80-4517-11e9-8598-f979d9e79717.jpg)

## Steps to Reproduce

1. Just copy the `main.dart` file from [here](https://gist.github.com/johhansantana/2c646723624d816412dc0ad4a8c4f16a)
2. Uncomment and comment the lines to reproduce
3. Check the console for errors

## Logs

```
[ +535 ms] I/flutter (15489): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[  +19 ms] I/flutter (15489): The following assertion was thrown during paint():
[        ] I/flutter (15489): A borderRadius can only be given for uniform borders.
[        ] I/flutter (15489): 'package:flutter/src/painting/box_border.dart': Failed assertion: line 496 pos 12: 'borderRadius ==
[        ] I/flutter (15489): null'
[   +3 ms] I/flutter (15489):
[   +1 ms] I/flutter (15489): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (15489): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (15489): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (15489):   https://github.com/flutter/flutter/issues/new?template=BUG.md
```

```
```

```
```

**Comment by fellow7000** [comment] 2019-05-29 21:39
Same stuff I have in my project - Radius property removes everything from the list

**Comment by jeidison** [comment] 2019-06-06 15:01
try 

decoration: BoxDecoration(
                                  gradient: new LinearGradient(
                                    stops: [0.02, 0.02],
                                    colors: [Colors.red, Colors.white],
                                  ),
                                  borderRadius: BorderRadius.all(Radius.circular(10)),
                                  color: Colors.white,
                                  boxShadow: [
                                    BoxShadow(color: Colors.grey, blurRadius: 5.0),
                                  ],
                                ),

**Comment by cytryn** [comment] 2020-01-05 10:33
> try
> 
> ```
> decoration: BoxDecoration(
>                                   gradient: new LinearGradient(
>                                     stops: [0.02, 0.02],
>                                     colors: [Colors.red, Colors.white],
>                                   ),
>                                   borderRadius: BorderRadius.all(Radius.circular(10)),
>                                   color: Colors.white,
>                                   boxShadow: [
>                                     BoxShadow(color: Colors.grey, blurRadius: 5.0),
>                                   ],
>                                 ),
> ```

Tried on a web project, still get the error

**Comment by cytryn** [comment] 2020-01-05 10:38
Just realized I also had a `border` property on my `BoxDecoration` which was causing the issue because Flutter was trying to apply the BorderRadius to all but I only defined bottom as a BorderSide.

**Comment by TahaTesser** [comment] 2020-05-06 15:08
Just tried to reproduce the issue, we cannot use both `border` and `borderRadius` together in `BoxDecoration`

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: EventsList(),
    );
  }
}

class EventsList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Events'),
      ),
      body: Event(),
    );
  }
}

class Event extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Card(
      child: Container(
        decoration: BoxDecoration(
          border: Border(bottom: BorderSide(color: Colors.green, width: 50)),
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(5),
            bottomLeft: Radius.circular(5),
          ),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Row(
              children: <Widget>[
                Column(
                  children: <Widget>[
                    Text('hey'),
                    Text('hey'),
                  ],
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.18.0-10.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-10.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 9b7b9d795e (18 hours ago), 2020-05-05 12:09:51 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details>

**Comment by taufn** [comment] 2020-07-28 02:51
@TahaTesser do you have a workaround if we still want to add border to the container?

**Comment by fluttercorner** [comment] 2020-10-07 03:44
[How to add Border Radius to Container in Flutter ?](https://fluttercorner.com/how-to-add-border-radius-to-container-in-flutter/)

**Comment by emlil** [comment] 2020-10-23 08:39
wrap container in card with properties
 ```
semanticContainer: true,
                      clipBehavior: Clip.antiAliasWithSaveLayer,
```

**Comment by darshankawar** [comment] 2021-01-19 10:59
Issue replicable on latest stable and master using the code sample provided in original [comment](https://github.com/flutter/flutter/issues/29267#issue-420291377). 

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
A borderRadius can only be given for a uniform Border.

The following is not uniform:
BorderSide.color
BorderSide.width
BorderSide.style
The relevant error-causing widget was: 
  Container file:///Users/dhs/Documents/NCFlutter/webtest/lib/main.dart:33:14

```

<details>
<summary>master and stable flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.402, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.402 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 2a188eeca3 (31 hours ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • SM A260G (mobile)            • 5200763ebcfa861f                     •
      android-arm    • Android 8.1.0 (API 27)
    • AOSP on IA Emulator (mobile) • emulator-5554                        •
      android-x86    • Android 9 (API 28) (emulator)
    • iPhone 12 Pro Max (mobile)   • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)              • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                 • chrome                               •
      web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM A260G (mobile)            • 5200763ebcfa861f                     •
      android-arm • Android 8.1.0 (API 27)
    • AOSP on IA Emulator (mobile) • emulator-5554                        •
      android-x86 • Android 9 (API 28) (emulator)
    • iPhone 12 Pro Max (mobile)   • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by rydmike** [comment] 2021-08-29 22:52
@darshankawar @johhansantana 

This is as it should be, well at least in the sense that there is a dedicated assert in the SDK to prevent this type of border. I don't know why it is like that though.

This is quite an annoying limitation in Flutter SDK imo at least. Also for example ToggleButtons paints its own widget with borders to avoid this limitation.

I just asked people on Twitter to try draw this in Flutter 
![image](https://user-images.githubusercontent.com/39990307/131267671-e711336d-8149-4330-a0e6-2fd76608c0fd.png)

to see what they come up, see here https://twitter.com/RydMike/status/1431999590547476483

The initial reaction is usually, I can just do this with `BoxDecoration` easily, until they hit above assertion and start scratching their heads for workarounds and hack together some really wonderful options in the thread. If you dig around in it, there are maybe 5 different creative solutions in DartPad demos with different variations.

I did not know about this old issue post about it when I made the above Tweet today. I found this issue when I was searching for a mentioned PR in the thread that is supposed to include a fix for this issue. I did not find any such PR yet, but maybe there is one.

**Comment by nt4f04uNd** [comment] 2021-08-30 01:51
I believe this issue is a duplicate of https://github.com/flutter/flutter/issues/12583

**Comment by rydmike** [comment] 2021-08-30 02:36
It definitely is the same issue. So this old issue from Mar 13, 2019  can be closed with reference to the even older same issue from Oct 17, 2017 https://github.com/flutter/flutter/issues/12583 !!

This really needs a solution in the SDK, a package is discussed elsewhere, but this kind of drawing capability is just expected out of the box by most Flutter devs. Sure you can do many workarounds for it, but still... 🤷🏻‍♂️ 😄

**Comment by TahaTesser** [comment] 2021-08-31 07:08
Closing as duplicate of https://github.com/flutter/flutter/issues/12583

**Closed by TahaTesser** 2021-08-31 07:08 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 1.22, found in release: 1.26
