### ISSUE TITLE
hot_reload_web_test is causing Linux web_tool_tests (3.09%) and Windows web_tool_tests flaky

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#86884] opened 2021-07-22 17:07 UTC
Example: 
Windows web_tool_tests: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/2876/overview
Linux web_tool_tests:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2947/overview
```

03:47 +5 ~1 -2: test/web.shard/hot_reload_web_test.dart: newly added code executes during hot restart - canvaskit [E]                                                                                  
  TimeoutException after 0:00:15.000000: Future not completed
  

03:47 +5 ~1 -2: loading test/web.shard/hot_reload_web_test.dart                                                                                                                                        
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
```

<img width="76" alt="Screen Shot 2021-07-22 at 10 03 18 AM" src="https://user-images.githubusercontent.com/54558023/126679360-734cc39d-a905-4a7e-9fa7-733a6a5ad158.png">

**Comment by zanderso** [comment] 2021-07-22 17:11
This is a duplicate of https://github.com/flutter/flutter/issues/85043

**Closed by zanderso** 2021-07-22 17:11 UTC
Labels: P1, severe: flake, team: flakes, tool
