### ISSUE TITLE
Does print() work like this?

### ISSUE THREAD

**Issue by jba-tm** [flutter/flutter#69303] opened 2020-10-29 15:09 UTC
Hi. Does the print() function print to debug console from another realesed app? Steps to perform it:
1. App A have a print function somewhere?
2. Run app;
3. Stop app A;
4. Run app B;
5. Minimize app B;
6. Open app A;
7. and then watch debug console;

like that you can print text (everything if it printed with print() function) from app A;

I/flutter (26986): B: print from app B
D/ViewRootImpl@4a62851[MainActivity](26986): ViewPostImeInputStage processPointer 0
W/System  (26986): ClassLoader referenced unknown path: /system/framework/QPerformance.jar
E/BoostFramework(26986): BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
V/BoostFramework(26986): BoostFramework() : mPerf = null
D/ViewRootImpl@4a62851[MainActivity](26986): ViewPostImeInputStage processPointer 1
D/ViewRootImpl@4a62851[MainActivity](26986): MSG_WINDOW_FOCUS_CHANGED 0
D/SurfaceView(26986): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={Surface(name=null)/@0x58559b7 isValid=false 0}
D/ViewRootImpl@4a62851[MainActivity](26986): mHardwareRenderer.destroy()#1
D/ViewRootImpl@4a62851[MainActivity](26986): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
D/InputTransport(26986): Input channel destroyed: fd=89
I/flutter (28360): A: print from app A
I/flutter (28360): A: print from app A

**Comment by jba-tm** [comment] 2020-10-29 15:28
Question two - why console debug from another application?

**Comment by pedromassangocode** [comment] 2020-10-30 11:21
Hi @jba-tm 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?

Possibly related to https://github.com/flutter/flutter/issues/46815.

Thank you

**Comment by jba-tm** [comment] 2020-10-30 12:43
flutter doctor -v:

[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale tk-TM)
    • Flutter version 1.22.2 at C:\flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\MainUser\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.48.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

**Comment by jba-tm** [comment] 2020-10-30 13:10
It's not about my code. There is some released application in the play market, I install it to my phone device. Then connect my device to pc and test own apps. When build is running I minimize my develop app and open realesed app.  Data (in json format), developer use print function during development, is being printed at this time.

**Comment by jba-tm** [comment] 2020-10-30 13:20
Does it secure? If print function work from realesed app, in theory can I it with every function?

**Comment by pedromassangocode** [comment] 2020-10-30 14:26
Hi @jba-tm 
I can't tell without reproducing the issue.

@blasten @jonahwilliams this seems to be related to https://github.com/flutter/flutter/issues/46815.

**Comment by jba-tm** [comment] 2020-11-01 06:24
Problem is samely with that issue and reproducing too. But I said about print() function, which print to console even now.

**Comment by danagbemava-nc** [comment] 2022-07-29 10:26
Closing this as a duplicate of https://github.com/flutter/flutter/issues/58611. 

See https://github.com/flutter/flutter/issues/58611#issuecomment-645505527 for more context.

**Closed by danagbemava-nc** 2022-07-29 10:26 UTC
Labels: platform-android, tool
