### ISSUE TITLE
Expose package:flutter/foundation as package that can be used without importing Flutter

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#32844] opened 2019-05-16 22:47 UTC
Goal is that dart command line applications can import the package and reuse useful functionality from flutter/foundation instead of duplicating it.
https://github.com/flutter/flutter/pull/32464 is a step towards making this possible by enabling the foundation code to run on the web. This CL may be sufficient or we may need a follow on CL that enables flutter/foundation to work when both dart:ui is and dart:html are not present (server).

Suggested implementation:
* Write a script which we can put in the dev/bots directory, that takes the foundation directory, massages it into the shape of a package that imports flutter/foundation if it's available.
* Creates a pubspec.yaml with a version matching the current flutter version (from the /version file probably)
* Publishes it
* Call that from the LUCI infrastructure.

**Comment by dnfield** [comment] 2019-05-16 22:50
This may be a duplicate of https://github.com/flutter/flutter/issues/29230

**Closed** 2019-05-16 22:53 UTC
