### ISSUE TITLE
[google_maps_flutter]Certain map updates don't take effect

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#103686] opened 2022-05-13 08:55 UTC
I have a complex screen that includes a PageView that shows search results on the bottom, on top of a google map that has custom markers showing the price of every item.

 As i swipe and change the page of the pager the markers are updated so that the selected item is focused.

This is working fine with flutter 2.10.5 but not with 3.0.0. I have the same version of google map plugin in both so this is not responsible for the bug.

Now with flutter 3.0.0 the screen doesn't seem to be refreshing correctly when the markers change. It is an irregular behaviour that sometimes they refresh correctly sometimes not.

When the bug kicks in and the markers are not updated if i scroll the map even a little then the screen is repainted correctly.

It seems to me that somehow the flutter framework decides that not enough has changed in the screen to repaint it which leads to the ui refreshing when the whole map is moved.

Also it be only an Android related problem as in IOS it seems to be working fine to me. 

Could this be related to the partial rebuilds that were introduced?

Can I somehow disable the partial rebuilds to test if this is indeed at fault?

It is really difficult to provide a working example as this is a pretty complex code that i am using.

This bug is making it impossible for me to upgrade to flutter 3.0.0

[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-GR)
    • Flutter version 3.0.0 at /Users/nikostsesmelis/Tools/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

**Comment by darshankawar** [comment] 2022-05-13 10:06
@NikosTsesmelis 
Without a working reproducible code, it would be hard to analyze anything, so if possible please provide one code sample that shows the behavior you are reporting, without it, we probably can't make this issue actionable.

Thanks.

**Comment by NikosTsesmelis** [comment] 2022-05-13 10:26
I will try to create some small project to showcase this. In the meantime is there a way to disable the partial repaints on android?

**Comment by darshankawar** [comment] 2022-05-13 11:59
> disable the partial repaints on android?

sorry I am not aware of it. Will try to provide details on it.

**Comment by NikosTsesmelis** [comment] 2022-05-16 07:50
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  Set<Marker> _markers = {};

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      _setRedMarkers();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: GoogleMap(
              initialCameraPosition: const CameraPosition(
                target: LatLng(37.3861, -122.0839),
                zoom: 14,
              ),
              markers: _markers,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(32),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                _button('RED', Colors.red, _setRedMarkers),
                _button('GREEN', Colors.green, _setGreenMarkers),
                _button('BLUE', Colors.blue, _setBlueMarkers),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _button(String text, Color color, VoidCallback onTap) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        color: color,
        padding: const EdgeInsets.all(16),
        child: Text(text),
      ),
    );
  }

  void _setRedMarkers() async {
    _setMarkers('assets/images/red.png');
  }

  void _setGreenMarkers() async {
    _setMarkers('assets/images/green.png');
  }

  void _setBlueMarkers() async {
    _setMarkers('assets/images/blue.png');
  }

  void _setMarkers(String assetPath) async {
    Uint8List? byteData = await _getBytesFromAsset(assetPath, 30);
    if (byteData == null) return;

    BitmapDescriptor icon = BitmapDescriptor.fromBytes(byteData);

    setState(() {
      _markers = {
        Marker(
          markerId: const MarkerId('1'),
          position: const LatLng(37.3861, -122.0839),
          icon: icon,
        ),
        Marker(
          markerId: const MarkerId('2'),
          position: const LatLng(37.3761, -122.0839),
          icon: icon,
        ),
        Marker(
          markerId: const MarkerId('3'),
          position: const LatLng(37.3961, -122.0839),
          icon: icon,
        ),
      };
    });
  }

  Future<Uint8List?> _getBytesFromAsset(String path, int width) async {
    ByteData data = await rootBundle.load(path);
    Codec codec = await instantiateImageCodec(
      data.buffer.asUint8List(),
      targetWidth: width,
    );
    FrameInfo fi = await codec.getNextFrame();
    return (await fi.image.toByteData(format: ImageByteFormat.png))?.buffer.asUint8List();
  }
}

[Archive.zip](https://github.com/flutter/flutter/files/8698128/Archive.zip)

If you type some times on the buttons you will see that the markers are not updated but if you move the map a little then they do. 

Test on Android because IOS seems to be working fine

**Comment by felix-ht** [comment] 2022-05-16 16:18
might be related to https://github.com/flutter/flutter/issues/103907

**Comment by darshankawar** [comment] 2022-05-17 05:25
@NikosTsesmelis 
Can you check [this](https://github.com/flutter/flutter/issues/103630) issue and see if it is similar to your case ?

**Comment by darshankawar** [comment] 2022-05-17 05:26
> might be related to #103907

@felix-ht Same for you. Looks similar to the one I linked above.

**Comment by NikosTsesmelis** [comment] 2022-05-17 07:04
It is not similar with to my case. In my case maps are rendered in the correct position.

**Comment by maheshmnj** [comment] 2022-05-17 13:17
> I will try to create some small project to showcase this. In the meantime is there a way to disable the partial repaints on android?

@NikosTsesmelis [ClipPath](https://api.flutter.dev/flutter/widgets/ClipPath-class.html) might be what you are looking for, it allows you to paint only a specific portion of the widget.

**Comment by maheshmnj** [comment] 2022-05-17 13:26
Hi @NikosTsesmelis, Thanks for filing the issue. I am able to reproduce the issue on stable and the master channel on Android, verified on Xiaomi k20 pro Android 11. Markers do not update with SetState unless the maps is interacted with a gesture.

stable 2.10.3 | stable/master 3.0
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/168820398-b84a7c9c-daf1-4392-9dd5-a9e028235961.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/168820371-1c4dc540-4a91-4021-9989-dedf01021190.mov' width=180/> 

marker assets used in below code sample can be found here [assets](https://github.com/flutter/flutter/files/8708588/marker_assets.zip)

<details>
<summary>code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:permission_handler/permission_handler.dart';
import 'dart:typed_data';
import 'dart:ui';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: TestScreen(),
    );
  }
}

class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  Set<Marker> _markers = {};

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
      _setRedMarkers();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: GoogleMap(
              initialCameraPosition: const CameraPosition(
                target: LatLng(37.3861, -122.0839),
                zoom: 14,
              ),
              markers: _markers,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(32),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                _button('RED', Colors.red, _setRedMarkers),
                _button('GREEN', Colors.green, _setGreenMarkers),
                _button('BLUE', Colors.blue, _setBlueMarkers),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _button(String text, Color color, VoidCallback onTap) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        color: color,
        padding: const EdgeInsets.all(16),
        child: Text(text),
      ),
    );
  }

  void _setRedMarkers() async {
    _setMarkers('assets/red.png');
  }

  void _setGreenMarkers() async {
    _setMarkers('assets/green.png');
  }

  void _setBlueMarkers() async {
    _setMarkers('assets/blue.png');
  }

  void _setMarkers(String assetPath) async {
    Uint8List? byteData = await _getBytesFromAsset(assetPath, 30);
    if (byteData == null) return;

    BitmapDescriptor icon = BitmapDescriptor.fromBytes(byteData);

    setState(() {
      _markers = {
        Marker(
          markerId: const MarkerId('1'),
          position: const LatLng(37.3861, -122.0839),
          icon: icon,
        ),
        Marker(
          markerId: const MarkerId('2'),
          position: const LatLng(37.3761, -122.0839),
          icon: icon,
        ),
        Marker(
          markerId: const MarkerId('3'),
          position: const LatLng(37.3961, -122.0839),
          icon: icon,
        ),
      };
    });
  }

  Future<Uint8List?> _getBytesFromAsset(String path, int width) async {
    ByteData data = await rootBundle.load(path);
    Codec codec = await instantiateImageCodec(
      data.buffer.asUint8List(),
      targetWidth: width,
    );
    FrameInfo fi = await codec.getNextFrame();
    return (await fi.image.toByteData(format: ImageByteFormat.png))
        ?.buffer
        .asUint8List();
  }
}

```
</details> 

Labeling this issue as a regression since this works fine on `stable 2.10.3`.

<details>
<summary>flutter doctor -v (3.0)</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
    • Flutter version 3.1.0-0.0.pre.419 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2eed8cbf93 (2 weeks ago), 2022-04-28 22:29:06 -0400
    • Engine revision dfdfe0b3b0
    • Dart version 2.18.0 (build 2.18.0-66.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

<details>
<summary>flutter doctor -v (2.10.3)</summary>

```
[✓] Flutter (Channel unknown, 2.10.3, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter_dev
    • Upstream repository unknown
    • Framework revision 7e9793dee1 (3 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 33B73E43-8CF4-4A78-851F-87FD477C288D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64
    ! Device 192.168.1.7:5555 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by blasten** [comment] 2022-05-17 17:11
Seems related to the recent changes. I will take a look.

**Comment by Cryward** [comment] 2022-05-18 21:07
As there is still no solution regarding this issue, I made a small code that does not solve the problem, but it could help to continue working while it is solved

```Ruby
GoogleMap(
  onCameraMove: (CameraPosition position) {
            setState(() {
              currentZom = position.zoom;
            });
          },
),

mapController?.animateCamera(
  CameraUpdate.newCameraPosition(
     CameraPosition(target: getCentralLatlng(listPointMarkers), zoom: currentZom)  //17 is new zoom level
  )
);
```

**Comment by CoMatu** [comment] 2022-05-20 11:27
Same issue today

**Comment by NikosTsesmelis** [comment] 2022-05-25 09:51
Thanks for the fix. It is behaving much better now but unfortunately it is not completely fixed. In a new fast phone it probably happens like 1% of the time but in an old laggy phone it is noticeable.

**Comment by stuartmorgan** [comment] 2022-05-25 13:11
I don't think it's a different issue; the workaround that landed in the maps plugin could definitely have the behavior described there.

**Comment by NikosTsesmelis** [comment] 2022-05-30 06:57
Is there any progress with this?

**Comment by NikosTsesmelis** [comment] 2022-05-31 07:27
Well actually what I said before about working on newer phones is not true. It is not working at all in my case. 

This is recorded in my pixel 4a in release mode. 

I tested with flutter 2.10.5 and it works fine as well as on an iphone.

Please can you work on it? I need to upload and this is keeping me from doing so.

[screen-20220531-100130~2.mp4.zip](https://github.com/flutter/flutter/files/8802995/screen-20220531-100130.2.mp4.zip)

**Comment by al-sadi** [comment] 2022-05-31 07:42
> Well actually what I said before about working on newer phones is not true. It is not working at all in my case.
> 
> This is recorded in my pixel 4a in release mode.
> 
> I tested with flutter 2.10.5 and it works fine as well as on an iphone.
> 
> Please can you work on it? I need to upload and this is keeping me from doing so.
> 
> [screen-20220531-100130~2.mp4.zip](https://github.com/flutter/flutter/files/8802995/screen-20220531-100130.2.mp4.zip)

I am facing the same issue as well. As a temp fix, I downgraded Flutter to 2.10.4.

**Comment by blasten** [comment] 2022-05-31 16:40
The fix for this issue is coming in https://github.com/flutter/engine/pull/33599

**Comment by NikosTsesmelis** [comment] 2022-06-14 06:52
Any update on this? We are waiting for this fix to upload.

**Comment by GaryQian** [comment] 2022-06-28 19:49
The medium term action to take here is to further the strategy used in https://github.com/flutter/plugins/pull/5787 to cover behavior on slower devices that seem to exhibit race behavior where the single frame skip invalidation is not sufficient to produce updates.

We can work around this by adding in additional delayed invalidation calls as well as a catch-all extremely delayed invalidation to ensure almost the updates will eventually be caught even if it is noticeably delayed.

**Comment by stuartmorgan** [comment] 2022-07-20 19:54
Based on further discussion, I think we'll update maps so that its Hybrid Composition switch works again post-3.0, and then default it to Hybrid Composition, and then explore options for improving behavior with TLHC after that.

**Comment by JarvanMo** [comment] 2022-07-21 01:41
Any updates for this issues? It not only affects google map but also other plugin. For me , there's no other better way to resolve this . I have to change viewpoint to current viewpoint to force update PlatformView, which against performance.

**Comment by stuartmorgan** [comment] 2022-07-21 14:17
> It not only affects google map but also other plugin.

Please file other issues for other plugins; we'll need to follow up on each one separately to find out what options are viable for them.

**Comment by stuartmorgan** [comment] 2022-09-01 15:37
Re-opening; defaulting to HC avoids this in the default case, but we want to fix this for TLHC so that we can switch back.

**Comment by XuanTung95** [comment] 2023-01-04 09:33
@stuartmorgan how about method `invalidateMapIfNeeded()` keep calling `mapView.invalidate()` for the next 20 frames, this way the `Surface` will be drawn continuously for the next n frames but the marker will be updated with minimum delay. This will affect the performance but I think redrawing a few frames is not so bad, it already draws many frames when user moves the map. The performance of Hybrid Composition mode is pretty bad all the time so I think this is worth a try.

**Comment by stuartmorgan** [comment] 2023-01-04 12:54
Yes, that's essentially https://github.com/flutter/flutter/issues/103686#issuecomment-1169163526

**Comment by XuanTung95** [comment] 2023-01-04 13:17
@stuartmorgan, So will you adapt this workaround and release a new version using TLHC? 
The current workaround is calling invalidate() after some delay frame but my workaround is calling invalidate() n frames continuously.
FYI, I tried to reproduce the bug in native android project. with PlatformViewWrapper and a TextureView as embedded view, it seems like the PlatformViewWrapper always draws the previous image of the TextureView.

**Comment by stuartmorgan** [comment] 2023-01-04 15:18
> So will you adapt this workaround and release a new version using TLHC?

There hasn't been a decision yet about continuing to try to work around the problem, vs. just putting that effort into investigating why we are missing updates in the first place to see if the core problem is fixable.

Anyone interested in moving the workaround approach forward is welcome to submit a PR.

**Comment by XuanTung95** [comment] 2023-01-05 03:42
@stuartmorgan For some reason, I can reproduce this bug using flutter 3.0.5 but not with flutter 3.3.10, using google_maps_flutter 2.1.5 (before the workaround). If we cannot reproduce this bug anymore, let's consider it fixed.

**Comment by XuanTung95** [comment] 2023-01-06 05:58
I dug in more about `TextureView` and found out that after calling `TextureView.unlockCanvasAndPost()`, `onSurfaceTextureUpdated()` will be called to notify that the most recent image from the image stream is available. If `View.invalidate()` is called after `onSurfaceTextureUpdated()`, it will draw() the latest image.

So there are some ideas:
- After `onMapReady()` is called, walkthrough each child of `MapView` to find the `TextureView` and overwrite the `SurfaceTextureListener.onSurfaceTextureUpdated()`. I tested and it works.
- Maybe we can get the `SurfaceTexture` of `TextureView` and pass it directly into Flutter engine to render.

**Closed** 2023-11-29 17:35 UTC
Labels: c: regression, platform-android, a: platform-views, p: maps, package, has reproducible steps, P2, found in release: 3.0, found in release: 3.1, platform-views: tlhc, team-android, triaged-android, multiteam-retriage-candidate
