### ISSUE TITLE
Unable to open telegram , whatsapp , facebook,twitter links in a flutter webview?

### ISSUE THREAD

**Issue by prakash6491** [flutter/flutter#93317] opened 2021-11-09 11:28 UTC
I created a Flutter web view application...i have share option in my applicaiton ... when i click WhatsApp share its not navigate to externel whats app.. it's going page Not Found. I want to open an external application . How to handle this task in a flutter to support in  Android? I used the **flutter webview plugin** to launch a url.

**Comment by danagbemava-nc** [comment] 2021-11-09 13:32
Hi @prakash6491 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Also, specify which version of `webview_flutter` you're using. 

Thank you

**Comment by prakash6491** [comment] 2021-11-10 06:34
flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
    • Flutter version 2.2.3 at D:\Prakash\flutter_stable_version\flutter
    • Framework revision f4abaa0735 (4 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\media\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\media\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • POCO X2 (mobile) • caf8ca9c • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 95.0.1020.30

• No issues found!

**Comment by prakash6491** [comment] 2021-11-10 06:36
am using webview_flutter: ^0.3.3

**Comment by danagbemava-nc** [comment] 2021-11-10 06:59
Please provide a complete minimal reproducible code sample and if possible a screenshot of what you see when you try to open said links. 

Side note: You also appear to be on older versions of `stable` and `webview_flutter`, I would advise you upgrade to the latest versions if possible.

**Comment by prakash6491** [comment] 2021-11-10 07:17
yeah now updated webview flutter version... my URL is https://tamilnadunow.com/wow-facts/. I attached a code screenshot https://prnt.sc/1yzq0tg.

**Comment by prakash6491** [comment] 2021-11-10 07:23
if I open in the mobile browser it perfectly navigates to external applications(what's app,Facebook,Twitter)

**Comment by danagbemava-nc** [comment] 2021-11-10 08:52
Kindly paste the code sample here. 

> if I open the same URL in the mobile browser it perfectly navigates to external applications(what's app, Facebook, Twitter)

Webviews work differently from browsers, so do not expect the same behaviour from them

**Comment by prakash6491** [comment] 2021-11-10 09:14
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:webview_flutter/webview_flutter.dart';

class HomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _HomeState();
  }
}

class _HomeState extends State<HomePage> {
  final _key = UniqueKey();
  bool _isLoadingPage;
  int _selectedIndex = 0;
  WebView _webView;
  WebViewController _controller;
  final Completer<WebViewController> _controllerCompleter =
      Completer<WebViewController>();

  List<String> arr_links = [
    'https://tamilnadunow.com/wow-facts',
    'https://tamilnadunow.com/wow-facts/entertainment-wow-facts',
    'https://tamilnadunow.com/wow-facts/sports-wow-facts-2',
    'https://tamilnadunow.com/wow-facts/viral-wow-facts',
    'https://tamilnadunow.com/wow-facts/entertainment-wow-facts-2',
  ];

  String currentUrl = "https://tamilnadunow.com/wow-facts";

  @override
  void initState() {
    super.initState();
    _isLoadingPage = true;
  }

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text('WowFacts')),
        automaticallyImplyLeading: false,
      ),
      body: SafeArea(
        child: WillPopScope(
          onWillPop: () => _goBack(context),
          child: Stack(
            children: <Widget>[
              WebView(
                key: _key,
                initialUrl: currentUrl,
                javascriptMode: JavascriptMode.unrestricted,
                gestureNavigationEnabled: true,
                userAgent: Platform.isIOS
                    ? 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15' +
                        ' (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1'
                    : 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) ' +
                        'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Mobile Safari/537.36',
                onPageStarted: (url) {
                  print('start load');
                },
                onWebViewCreated: (WebViewController webViewController) {
                  _controller = webViewController;
                },
                onPageFinished: (finish) {
                  setState(() {
                    _isLoadingPage = false;
                    _controller.evaluateJavascript(
                        'setCookie("in_app=true; path=/");');
                  });
                },
              ),
              _isLoadingPage
                  ? Scaffold(
                      body: Center(
                        child: CircularProgressIndicator(
                          valueColor:
                              new AlwaysStoppedAnimation<Color>(Colors.pink),
                        ),
                      ),
                      backgroundColor: Colors.black.withOpacity(
                          0.70), // this is the main reason of transparency at next screen. I am ignoring rest implementation but what i have achieved is you can see.
                    )
                  : Stack()
            ],
          ),
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home, color: Colors.white54),
            label: 'Home',
            backgroundColor: Colors.red,
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.movie, color: Colors.white54),
            label: 'Entertainment',
            backgroundColor: Colors.green,
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.sports_basketball, color: Colors.white54),
            label: 'Sports',
            backgroundColor: Colors.purple,
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.flash_on, color: Colors.white54),
            label: 'Viral',
            backgroundColor: Colors.pink,
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.emoji_people, color: Colors.white54),
            label: 'History',
            backgroundColor: Colors.red,
          ),
        ],
        currentIndex: _selectedIndex,
        selectedItemColor: Colors.white,
        onTap: _onItemTapped,
      ),
    );
  }

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
      _isLoadingPage = true;
      currentUrl = arr_links[_selectedIndex];
      _controller.loadUrl(currentUrl);
    });
  }

  Future<bool> _goBack(BuildContext context) async {
    if (await _controller.canGoBack()) {
      _controller.goBack();
      return Future.value(false);
    } else {
      showDialog(
          context: context,
          builder: (context) => AlertDialog(
                title: Text('Do you want to exit'),
                actions: <Widget>[
                  FlatButton(
                    onPressed: () {
                      Navigator.of(context).pop();
                    },
                    child: Text('No'),
                  ),
                  FlatButton(
                    onPressed: () {
                      SystemNavigator.pop();
                    },
                    child: Text('Yes'),
                  ),
                ],
              ));
      return Future.value(true);
    }
  }
}

**Comment by prakash6491** [comment] 2021-11-10 09:15
I attached the full code. please look at anything I missed.

**Comment by danagbemava-nc** [comment] 2021-11-10 10:56
From this SO link https://stackoverflow.com/a/32714613/10630669, it looks like this is a limitation of the android `Webview`. 

What you can try is implement a custom `navigationDelegate` and capture the links to the social media sites then use the `url_launcher` to open a browser which might open the app for the user. See this SO answer for a sample implementation. 

https://stackoverflow.com/questions/51833766/how-to-open-app-links-in-flutter-webview

**Comment by prakash6491** [comment] 2021-11-15 10:09
nope .Not working.any other solution is there?

**Comment by danagbemava-nc** [comment] 2021-11-15 12:08
Unfortunately, as this is a limitation of the android `Webview` itself, that is beyond the scope of the plugin. 

As such, I'll reluctantly have to close this issue. 

If you do have any more issues, kindly file them. 

Thank you

**Closed by danagbemava-nc** 2021-11-15 12:08 UTC
Labels: in triage
