### ISSUE TITLE
App crash for firebase messaging

### ISSUE THREAD

**Issue by Niccolohui** [flutter/flutter#56463] opened 2020-05-06 17:55 UTC
Hi, the app crash in android when it got a notification from firebase. here is the log from Android studio. thank you!

I/flutter (12646): 360.0
I/dalvikvm(12646): Could not find method android.content.pm.PackageManager.isInstantApp, referenced from method com.google.android.gms.common.wrappers.PackageManagerWrapper.isCallerInstantApp
W/dalvikvm(12646): VFY: unable to resolve virtual method 702: Landroid/content/pm/PackageManager;.isInstantApp (Ljava/lang/String;)Z
D/dalvikvm(12646): VFY: replacing opcode 0x6e at 0x002e
D/AndroidRuntime(12646): Shutting down VM
W/dalvikvm(12646): threadid=1: thread exiting with uncaught exception (group=0x41756d58)
E/AndroidRuntime(12646): FATAL EXCEPTION: main
E/AndroidRuntime(12646): Process: com.sbchk.app, PID: 12646
E/AndroidRuntime(12646): java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.RuntimeException: PluginRegistrantCallback is not set.
E/AndroidRuntime(12646): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2585)
E/AndroidRuntime(12646): 	at android.app.ActivityThread.access$1900(ActivityThread.java:141)
E/AndroidRuntime(12646): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1295)
E/AndroidRuntime(12646): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12646): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(12646): 	at android.app.ActivityThread.main(ActivityThread.java:5072)
E/AndroidRuntime(12646): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12646): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12646): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(12646): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
E/AndroidRuntime(12646): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(12646): Caused by: java.lang.RuntimeException: PluginRegistrantCallback is not set.
E/AndroidRuntime(12646): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:157)
E/AndroidRuntime(12646): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate(FlutterFirebaseMessagingService.java:77)
E/AndroidRuntime(12646): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2575)
E/AndroidRuntime(12646): 	... 10 more
I/Process (12646): Sending signal. PID: 12646 SIG: 9
Lost connection to device.

**Comment by dvird** [comment] 2020-05-06 21:27
Send me your manifest & mainactivity in your android folder

**Comment by Niccolohui** [comment] 2020-05-07 00:42
Hi Dvird,

MainActivity

package com.domain.app

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}



manifest

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.domain.app">
    
    <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="app"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>


        </activity>

        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by TahaTesser** [comment] 2020-05-07 14:07
Hi @Niccolohui 
for what I can see the issue is related to a FlutterFire plugin, please open the issue in the dedicated [GitHub](https://github.com/FirebaseExtended/flutterfire/issues). 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by TahaTesser** 2020-05-07 14:07 UTC
