### ISSUE TITLE
[web] Debug mode is paused when launched from IntelliJ/Android Studio

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#76680] opened 2021-02-24 08:57 UTC
Hi,
I am developing a flutter web application using Android Studio.
I use the Chrome browser as my device.

If I press play, the website is launched and displayed by chrome.
But if I press debug, chrome displays only a white page. Even if I wait several minutes.
A workaround is to press the reload button once. After that my website is dislayed.

I don't know what code to include hence I can't include the whole project.

Anyone else facing this problems?

```
[√] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale de-DE)
    • Flutter version 1.26.0-17.3.pre at C:\Users\akilian\Flutter SDK\flutter
    • Framework revision 4b50ca7f7f (3 weeks ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.56

! Doctor found issues in 1 category.

```

</details>

**Comment by TahaTesser** [comment] 2021-02-24 11:14
Hi @Wissperwind 
I can only see a white blank screen in Android Studio when running in debug mode on macOS and Windows, doesn't reproduce in VS Code or Terminal

Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by pedromassango** [comment] 2021-02-24 13:56
As I mentioned in , this is probably due to a crash. Sharing my logs here as my issue was close. I got those logs once you resume the debugger (that blue button above the webpage).

```console
Running "flutter pub get" in app...
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:56126/1tWXqmQvm-Q=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:56126/1tWXqmQvm-Q=/ws
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:56000/dart_sdk.js:5347:11)
    at Object.nullCheck (http://localhost:56000/dart_sdk.js:5680:30)
    at _engine._PointerAdapter.new.[_getSanitizer] (http://localhost:56000/dart_sdk.js:166679:28)
    at http://localhost:56000/dart_sdk.js:166739:42
    at http://localhost:56000/dart_sdk.js:166697:16
    at http://localhost:56000/dart_sdk.js:166391:11
    at <anonymous>
    at http://localhost:56000/dart_sdk.js:50601:13
    at Generator.next (<anonymous>)
    at runBody (http://localhost:56000/dart_sdk.js:39187:34)
    at Object._async [as async] (http://localhost:56000/dart_sdk.js:39218:7)
    at http://localhost:56000/dart_sdk.js:50592:20
    at new Promise (<anonymous>)
    at Object._invokeExtension [as invokeExtension] (http://localhost:56000/dart_sdk.js:50589:12)
    at <anonymous>:1:31
```

**Comment by Wissperwind** [comment] 2021-02-24 14:24
I can confirm that chrome does not display my website in debug mode, because somehow the program is paused - I can press resume and my website appears perfextly debuggable, but in my case, no weeoe is printed after I press resume.

**Comment by yjbanov** [comment] 2021-02-24 18:28
Confirmed that this is happening in IntelliJ only. The app is launched in paused state and requires unpausing either by using the "play" icon in IntelliJ (I had to click it twice) or in Chrome DevTools.

`flutter run -d chrome` and VSCode work fine.

/cc @jacob314

**Comment by jacob314** [comment] 2021-02-24 18:47
@grouma 
The expected behavior for VSCode and IntelliJ is that the app should start paused and then the IDE should resume it immediately. That enables setting breakpoints on startup, etc.
Most likely something is going wrong with DWDS indicating that the app is paused on startup so IntelliJ doesn't know it should resume. @DanTup did you do something to VSCode to not pause web apps on startup?

**Comment by DanTup** [comment] 2021-02-24 18:55
Nope, nothing special - it all seems to work in VS Code. Looking at the log, it looks like the isolate is already be paused at the start, and we trigger the resume based on its `pauseEvent` being a `PauseStart`.

As far as I can tell, there's no special handling for web here, it's all the same as for CLI.

**Comment by grouma** [comment] 2021-02-24 19:04
@DanTup is correct. `package:dwds` doesn't handle this directly but instead exposes the necessary APIs to support pause on start. We expose an `AppConnection` which you can call `runMain` on.

It looks like Flutter Tools [automatically](https://github.com/flutter/flutter/blob/ac4d5099d846a1a80e91d7758d94b684a3ee105f/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L816) calls `runMain`.

@jonahwilliams any thoughts here?

**Comment by grouma** [comment] 2021-02-24 19:29
@jacob314 mentioned it may be due to the fact that Intellij expects a `kPauseStart` event. This is properly set when an Isolate is created in `package:dwds` [here](https://github.com/dart-lang/webdev/blob/148a55a651c6bdc664ef48feaffe74e9495409f5/dwds/lib/src/debugging/inspector.dart#L122). 

However, we don't emit this event. I'm not sure what the expected behavior is here but this likely could be the cause of the issue.

**Comment by DanTup** [comment] 2021-02-24 19:29
I think the comment there may be misleading, it only calls that if not starting paused:

https://github.com/flutter/flutter/blob/ac4d5099d846a1a80e91d7758d94b684a3ee105f/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L815-L817

In VS Code, when we connect to the VM service, we:

- subscribe to the debug streams to get pause events
- fetch all existing isolates
- process the `pauseEvent` on each isolate as if it arrived as a pause event

When we process a `PauseStart` event (whether it arrives in the stream, or was picked up on an existing isolate) we send breakpoints then call resume.

**Closed** 2021-02-25 02:26 UTC
Labels: a: debugging, d: intellij, found in release: 1.26, found in release: 1.27, has reproducible steps, platform-web, severe: regression, tool

**Comment by yjbanov** [comment] 2021-02-25 17:17
Retroactively categorizing as P2, just so we can make sure that the fix for this bug reaches users faster.

**Comment by Wissperwind** [comment] 2021-03-05 16:12
Is the fix already available? Or was it in the last released version?
I at the moment I have the problem again using flutter 2.0.

**Comment by helin24** [comment] 2021-03-05 16:38
@Wissperwind this change was included in v54 of the Flutter plugin. If that's the version you're using, maybe the issue we reproduced wasn't the same as yours despite having similar behavior. In that case, could you check if there's an error if you open up the Chrome inspector while it's on a blank screen?

**Comment by Wissperwind** [comment] 2021-03-08 08:40
No, it was my fault. You fixed the right bug. I didn't realize that a flutter update is not enough and I had to update the IDE Plugins.
