### ISSUE TITLE
[web]: Build doesn't recognize diferent imports for the same file

### ISSUE THREAD

**Issue by AndresVaron** [flutter/flutter#45423] opened 2019-11-22 21:36 UTC
Hi, Trying to build the app for deployment using the flutter build web command on version 1.12.5 generates the following error:

![imports](https://user-images.githubusercontent.com/35813015/69461763-564cce00-0d45-11ea-86ad-57a9da82af51.jpeg)

Entire StackTrace:
#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:156:7)
<asynchronous suspension> 
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure>
(package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync (dart:async/future.dart:224:31)
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:419:36)
#7      buildWeb (package:flutter_tools/src/web/compile.dart:41:50)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:57:11)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:607:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
Exception: lib/main.dart:46:31:
Error: The argument type 'List<Tema/*1*/>' can't be assigned to the parameter type 'List<Tema/*2*/>'.
  'List' is from 'dart:core'.
  'Tema/*1*/' is from 'lib/main.dart'.
  'Tema/*2*/' is from 'package:appreport/main.dart' ('lib/main.dart').
      ConnectivityBloc(temas: temas, navigatorKey: _navigatorKey);
                              ^
Error: Compilation failed. 

I believe this is because in one file i have "package:appreport/main.dart" as an import. Importing the file with its relative path("../main.dart") fixes the problem. It seams dart2js can't identify the different imports methods are referencing the same file. 

P.S. The code i'm running works perfectly on **flutter run -d chrome**

**Comment by jonahwilliams** [comment] 2019-11-23 19:25
Duplicate of https://github.com/flutter/flutter/issues/43846

**Closed by jonahwilliams** 2019-11-23 19:25 UTC
