### ISSUE TITLE
Windows win+v key cannot paste to textfield

### ISSUE THREAD

**Issue by janino** [flutter/flutter#146056] opened 2024-04-01 02:55 UTC
### Steps to reproduce

1.Windows win+v key cannot paste to textfield
![AC2028BE-3130-40bd-9183-BF37B7B517FC](https://github.com/flutter/flutter/assets/13724193/20c8dc29-d18d-42f8-8b11-038c5482b60d)

When I use the shortcut key win+v in Windows to select the contents of the pasteboard, I cannot paste it into the textfield.

### Expected results

Hope the paste can be successful

### Actual results

When I use the shortcut key win+v in Windows to select the contents of the pasteboard, I cannot paste it into the textfield.

### Code sample

```dart
import 'package:desktop_multi_window/desktop_multi_window.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class EventWidget extends StatefulWidget {
  const EventWidget({Key? key, required this.controller}) : super(key: key);

  final WindowController controller;

  @override
  State<EventWidget> createState() => _EventWidgetState();
}

class MessageItem {
  const MessageItem({this.content, required this.from, required this.method});

  final int from;
  final dynamic content;
  final String method;

  @override
  String toString() {
    return '$method($from): $content';
  }

  @override
  int get hashCode => Object.hash(from, content, method);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    if (other.runtimeType != runtimeType) {
      return false;
    }
    final MessageItem typedOther = other as MessageItem;
    return typedOther.from == from && typedOther.content == content;
  }
}

class _EventWidgetState extends State<EventWidget> {
  final messages = <MessageItem>[];

  final textInputController = TextEditingController();

  final windowInputController = TextEditingController();

  @override
  void initState() {
    super.initState();
    DesktopMultiWindow.setMethodHandler(_handleMethodCallback);
    textInputController.addListener(() {
      debugPrint("textInputController->${textInputController.text}");
    });
  }

  @override
  dispose() {
    DesktopMultiWindow.setMethodHandler(null);
    super.dispose();
  }

  Future<dynamic> _handleMethodCallback(
      MethodCall call, int fromWindowId) async {
    if (call.arguments.toString() == "ping") {
      return "pong";
    }
    setState(() {
      messages.insert(
        0,
        MessageItem(
          from: fromWindowId,
          method: call.method,
          content: call.arguments,
        ),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    void submit() async {
      final text = textInputController.text;
      if (text.isEmpty) {
        return;
      }
      final windowId = int.tryParse(windowInputController.text);
      textInputController.clear();
      final result =
          await DesktopMultiWindow.invokeMethod(windowId!, "onSend", text);
      debugPrint("onSend result: $result");
    }

    return Column(
      children: [
        Expanded(
          child: ListView.builder(
            itemCount: messages.length,
            reverse: true,
            itemBuilder: (context, index) =>
                _MessageItemWidget(item: messages[index]),
          ),
        ),
        Row(
          children: [
            SizedBox(
              width: 100,
              child: TextField(
                controller: windowInputController,
                decoration: const InputDecoration(
                  labelText: 'Window ID',
                ),
                inputFormatters: [FilteringTextInputFormatter.digitsOnly],
              ),
            ),
            Expanded(
              child: TextField(
                onChanged: (value) {
                  debugPrint("textInputController->${value}");
                },
                maxLines: 10,
                controller: textInputController,
                decoration: const InputDecoration(
                  hintText: 'Enter message',
                ),
                onSubmitted: (text) => submit(),
              ),
            ),
            IconButton(
              icon: const Icon(Icons.send),
              onPressed: submit,
            ),
          ],
        ),
      ],
    );
  }
}

class _MessageItemWidget extends StatelessWidget {
  const _MessageItemWidget({Key? key, required this.item}) : super(key: key);

  final MessageItem item;

  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Text("${item.method}(${item.from})"),
      subtitle: Text(item.content.toString()),
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-04-01 11:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143997

**Closed by danagbemava-nc** 2024-04-01 11:25 UTC
Labels: in triage
