### ISSUE TITLE
[image_picker] Add support for web

### ISSUE THREAD

**Issue by OlfatMostafa** [flutter/flutter#36281] opened 2019-07-16 17:41 UTC
I know flutter web is still fresh but i'm trying to do image uploading in my flutter web project, so image_picker is still not supported but i'm looking for suggestions for any replacements or approaches for that.

I'm using firebase, and the part that i can't figure out is how to pick an image from my computer to upload it.

Thanks!

**Comment by aabounegm** [comment] 2019-07-24 12:21
You can try this code as a workaround until plugins are supported by Flutter Web. It worked with me.
```dart
import 'dart:html';

void main() {
  final InputElement input = document.createElement('input');
  input
      ..type = 'file'
      ..multiple = true
      ..accept = 'image/*';
  input.onChange.listen((e) {
    final List<File> files = input.files;
    for (final file in files) {
      final reader = new FileReader();
      reader.onLoad.listen((e2) {
        String fileContent = reader.result;
        print(fileContent);
      });
      reader.readAsText(file); // or '.readAsDataUrl' for using as img src, for example
    }
  });
  input.click();
}
```
Of course you can further improve on it by wrapping it in a function that would return a `Future` that resolves with the actual `fileContent`.

**Comment by mohamed6996** [comment] 2019-07-26 14:59
@aabounegm 

Where should i add this element in htlm? 
`  document.createElement('input');
`

I could not find any reference to `document`

Can you please provide a complete example?

**Comment by moulikcipherX** [comment] 2019-09-11 18:04
I really love to work on the plugin.. Does anyone working on it?
Please tell me how to start creating plugin.

**Comment by hterkelsen** [comment] 2019-09-11 18:10
@ditman has been working on a prototype for image_picker

**Comment by ditman** [comment] 2019-09-13 19:41
I have a prototype of the image_picker plugin for web that seems to work, at least in the happiest cases. It requires some overrides to `dart:io` (through the IOOverrides class), but I am not 100% sure it covers all possible use cases. You can take a look at it [here](https://github.com/ditman/plugins/pull/12). 

It uses an in-memory, **not persistent** filesystem (from package:file) to temporarily store images/videos as they're selected/taken so they can be passed around the program and plugins, but the file will NOT be saved permanently anywhere, unless you do it yourself (like pushing the image to firebase as the OP mentioned!).

_**Again, Big Disclaimer:** The pull request above will not end up merged as is, because it's a starting point for us on what to do with `dart:io` and other packages that need some special code to run on web._ 

Please, handle with care! However, if you test the proto I posted above and have any feedback, please do share!

**Comment by Thathy916** [comment] 2019-10-18 05:35
Have you implemented the function of uploading the flitter web image? The image upload function I made can't be used on the mobile browser, except for chrome. What's the matter?

**Comment by ykaito21** [comment] 2019-12-18 12:43
> Have you implemented the function of uploading the flutter web image? The image upload function I made can't be used on the mobile browser, except for chrome. What's the matter?

I am facing the same issue. @Thathy916  Did you find any solution?

**Comment by ykaito21** [comment] 2019-12-19 06:35
I finally found the solution which probably works on mobile safari too. I leave it here. Hope it will help someone like me.

```
  Future<void> _setImage() async {
    final completer = Completer<List<String>>();
    InputElement uploadInput = FileUploadInputElement();
    uploadInput.multiple = true;
    uploadInput.accept = 'image/*';
    uploadInput.click();
    //* onChange doesn't work on mobile safari
    uploadInput.addEventListener('change', (e) async {
      // read file content as dataURL
      final files = uploadInput.files;
      Iterable<Future<String>> resultsFutures = files.map((file) {
        final reader = FileReader();
        reader.readAsDataUrl(file);
        reader.onError.listen((error) => completer.completeError(error));
        return reader.onLoad.first.then((_) => reader.result as String);
      });

      final results = await Future.wait(resultsFutures);
      completer.complete(results);
    });
    //* need to append on mobile safari
    document.body.append(uploadInput);
    final List<String> images = await completer.future;
    setState(() {
      _uploadedImages = images;
    });
    uploadInput.remove();

    //* this also works
    // final completer = Completer<List<String>>();
    // final InputElement input = document.createElement('input');
    // input
    //   ..type = 'file'
    //   ..multiple = true
    //   ..accept = 'image/*';
    // input.click();
    //* onChange doesn't work in mobile safari
    // input.addEventListener('change', (e) async {
    //   final List<File> files = input.files;
    //   Iterable<Future<String>> resultsFutures = files.map((file) {
    //     final reader = FileReader();
    //     reader.readAsDataUrl(file);
    //     reader.onError.listen((error) => completer.completeError(error));
    //     return reader.onLoad.first.then((_) => reader.result as String);
    //   });
    //   final results = await Future.wait(resultsFutures);
    //   completer.complete(results);
    // });
    // document.body.append(input);
    // // input.click(); can be here
    // final List<String> images = await completer.future;
    // setState(() {
    //   _uploadedImages = images;
    // });
    // input.remove();
  }

**Comment by MoacirSchmidt** [comment] 2020-01-30 23:44
@ditman I tried your PR (in flutter WEB) but when I click in "PICK" button nothing happens. I checked the source and the methodChannel seems not to work on WEB version. Do you have any idea to help me?

**Comment by ditman** [comment] 2020-01-31 19:35
Sorry @MoacirSchmidt, I wrote that one months ago, and hasn't been maintained since. Many things may have changed since then. I'd start by checking the Javascript console to see if there are any errors there. That might give you some clues?

**Comment by Mostafa-SA-developer** [comment] 2020-03-20 17:49
this support web image_picker_web: ^0.1.6

**Comment by ditman** [comment] 2020-03-20 18:32
`image_picker_web` does not conform to any Platform Interface, so if used in conjunction with the official `image_picker`, it might break at any time.

**Comment by Mostafa-SA-developer** [comment] 2020-03-20 18:36
im build 2 version one for ios&android i using image_picker
and for flutter build web just replace image_picker with image_picker_web

**Comment by Ahmadre** [comment] 2020-03-20 20:56
I can confirm what @ditman says. Today I release version 1.0.3 of `image_picker_web` (https://pub.dev/packages/image_picker_web) but I will have to work on a PR with platform_interface and web implementation like url_launcher for example

**Comment by ditman** [comment] 2020-03-20 22:36
@Ahmadre the problem is that the current version is using strings to paths that rely on dart:io (and don't work on web). @rodydavis did a `FileX` class that might be used as a common return value, but no matter what we do, the change will be backwards incompatible with what currently exists.

**Comment by motorahul** [comment] 2020-03-21 07:06
> I know flutter web is still fresh but i'm trying to do image uploading in my flutter web project, so image_picker is still not supported but i'm looking for suggestions for any replacements or approaches for that.
> 
> I'm using firebase, and the part that i can't figure out is how to pick an image from my computer to upload it.
> 
> Thanks!

hi @OlfatMostafa  
have you tried  flutter web authentication for mobile number using firebase
thanks

**Comment by SwissCheese5** [comment] 2020-04-21 21:10
Any updates?

**Comment by ditman** [comment] 2020-04-21 21:12
@SwissCheese5 we're working on this, but as you know we've been pretty busy with other plugins :P

**Comment by SwissCheese5** [comment] 2020-04-21 22:00
> @SwissCheese5 we're working on this, but as you know we've been pretty busy with other plugins :P

haha, fair enough!

**Comment by ditman** [comment] 2020-04-27 18:46
So the plan for this plugin is as follows:

1. Migrate the current version of the plugin to the new platform-interface + delegated implementations so work can progress further (I'll start on this **right away**)
2. Come up with a new return type that is not dependent on `dart:io` directly, following @rodydavis' FileX example. @cyanglaz, Rody and I will work on this.
3. Introduce new versions of the `pick*` methods that return the new type, instead of `String`, and mark the old methods as `@deprecated`.
   * Now we can implement a web version. Most of the code has already been written by @rodydavis and I, so this should be quick.
4. Eventually bump the major version of the core plugin, and remove the methods marked as `@deprecated` from it, so everybody must use the new `FileX` ones.

**Comment by rodydavis** [comment] 2020-04-27 19:35
Sounds great to me 💪🏻

**Comment by ditman** [comment] 2020-05-21 01:48
In case anybody else is interested in taking this for a spin, There's a PR + demo of the plugin here:

https://github.com/flutter/plugins/pull/2767

Please give it a shot and report whatever you find!

**Comment by DhiaEddineNabli** [comment] 2020-06-01 04:38
image_picker_web is now out there
https://pub.dev/packages/image_picker_web

**Comment by ditman** [comment] 2020-06-01 16:51
@DhiaEddineNabli sorry I hid your comment, that's not the package we're working on. The official package is going to be:

**image_picker_for_web**

**Comment by ditman** [comment] 2020-06-04 05:06
Published `image_picker_for_web` to pub.dev:

https://pub.dev/packages/image_picker_for_web (^0.1.0)

For now, it is not *endorsed*, so you'll have to depend both on image_picker and image_picker_for_web. Please, see the instructions in the README.

**Closed** 2020-06-04 05:06 UTC
Labels: P3, p: first party, p: image_picker, platform-web, plugin, severe: new feature

**Comment by iscojin** [comment] 2020-06-05 14:31
Hello, I am not sure how to upload image from my PC to firebase storage using image_picker_web.

**Comment by shinriyo** [comment] 2020-09-05 04:09
```
Because image_picker_platform_interface >=1.1.0 depends on http ^0.12.1 and andu depends on http 0.12.0+4, image_picker_platform_interface >=1.1.0 is forbidden.
```

**Comment by shinriyo** [comment] 2020-09-05 04:10
```
flutter clean
flutter pub cache repair
```

need?

**Comment by chaitanya-teja** [comment] 2020-09-24 19:18
> You can try this code as a workaround until plugins are supported by Flutter Web. It worked with me.
> 
> ```dart
> import 'dart:html';
> 
> void main() {
>   final InputElement input = document.createElement('input');
>   input
>       ..type = 'file'
>       ..multiple = true
>       ..accept = 'image/*';
>   input.onChange.listen((e) {
>     final List<File> files = input.files;
>     for (final file in files) {
>       final reader = new FileReader();
>       reader.onLoad.listen((e2) {
>         String fileContent = reader.result;
>         print(fileContent);
>       });
>       reader.readAsText(file); // or '.readAsDataUrl' for using as img src, for example
>     }
>   });
>   input.click();
> }
> ```
> 
> **Edit: here is a sample function that wraps it in a Future:**
> 
> ```dart
> import 'dart:html';
> import 'dart:async';
> 
> Future<List<String>> getFiles() {
>   final completer = new Completer<List<String>>();
>   final InputElement input = document.createElement('input');
>   input
>       ..type = 'file'
>       ..multiple = true
>       ..accept = 'image/*';
>   input.onChange.listen((e) async {
>     final List<File> files = input.files;
>     Iterable<Future<String>> resultsFutures = files.map((file) {
>       final reader = new FileReader();
>       reader.readAsDataUrl(file);
>       reader.onError.listen((error) => completer.completeError(error));
>       return reader.onLoad.first.then((_) => reader.result as String);
>     });
>     final results = await Future.wait(resultsFutures);
>     completer.complete(results);
>   });
>   input.click();
>   return completer.future;
> }
> ```
> 
> or in case you want only one file:
> 
> ```dart
> import 'dart:html';
> import 'dart:async';
> 
> Future<String> getFile() {
>   final completer = new Completer<String>();
>   final InputElement input = document.createElement('input');
>   input
>       ..type = 'file'
>       ..accept = 'image/*';
>   input.onChange.listen((e) async {
>     final List<File> files = input.files;
>     final reader = new FileReader();
>     reader.readAsDataUrl(files[0]);
>     reader.onError.listen((error) => completer.completeError(error));
>     await reader.onLoad.first;
>     completer.complete(reader.result as String);
>   });
>   input.click();
>   return completer.future;
> }
> ```
> 
> Of course, you can tweak this according to your needs by changing the returned object (ex: `File` itself instead of reading it) and using a different `reader.readAs*` function.
> Seeing that almost all Firebase plugins for Flutter depend on the Flutter package, I don't think you can use the Flutter package. Try to see if you can use the [Web](https://pub.dev/packages/firebase) one instead

This solution works if we have to select a file. But when the file picker opens, and we cancel the dialog. This code won't run again. It keeps waiting for the file to be picked which was cancelled long back.

**Comment by cedvdb** [comment] 2021-03-18 15:17
why not include it directly in the image picker package ?

**Comment by ditman** [comment] 2021-03-18 18:19
image_picker default web support has been published recently. 

https://pub.dev/packages/image_picker/changelog#073

**Comment by pumuckelo** [comment] 2021-03-24 21:39
I got it working this way:

// file is PickedFile received by ImagePicker

```
var data = await file.readAsBytes();
var uploadTask = FirebaseStorage.instance.ref().child("path").ref.putData(data);
```

**Comment by pumuckelo** [comment] 2021-03-24 21:42
Full working example function to use PickedFile with firebase storage

```
Future<TaskSnapshot> uploadProfilePicture(
      String userId, PickedFile file) async {
   
    Reference ref = _storage
        .ref()
        .child("/users/$userId/images/profilePicture/profilePicture");

    if (isWeb()) {
      var data = await file.readAsBytes();
      return ref.putData(data);
    }

    return ref.putFile(File(file.path));
  }
```
