### ISSUE TITLE
devicelab flutter_view__start_up test timed out

### ISSUE THREAD

**Issue by aam** [flutter/flutter#13233] opened 2017-11-28 22:45 UTC
devicelab test `flutter_view__start_up` timed out

```
...
stdout:            native-code: 'armeabi-v7a'
stdout: [   +2 ms] Stopping app 'app.apk' on Moto G 4.
stdout: [        ] /Users/fortuna/Library/Android/sdk/platform-tools/adb -s ZY223TDZ45 shell am force-stop io.flutter.examples.flutter_view
stdout: [ +974 ms] /Users/fortuna/Library/Android/sdk/platform-tools/adb -s ZY223TDZ45 shell pm list packages io.flutter.examples.flutter_view
stdout: [ +963 ms] package:io.flutter.examples.flutter_view
stdout: [   +2 ms] /Users/fortuna/Library/Android/sdk/platform-tools/adb -s ZY223TDZ45 shell cat /data/local/tmp/sky.io.flutter.examples.flutter_view.sha1
stdout: [  +46 ms] dd0654a63e4325197f9ba952d7c5297e5985a0a3
stdout: [        ] Installing APK.
stdout: [   +2 ms] /Users/fortuna/Library/Android/sdk/platform-tools/adb version
stdout: [  +10 ms] Android Debug Bridge version 1.0.36
stdout:            Revision 0e9850346394-android
stdout: [        ] /Users/fortuna/Library/Android/sdk/platform-tools/adb start-server
stdout: [   +9 ms] Installing build/app/outputs/apk/app.apk...
stdout: [        ] /Users/fortuna/Library/Android/sdk/platform-tools/adb -s ZY223TDZ45 install -r build/app/outputs/apk/app.apk
stdout: [+5180 ms] Success
stdout: [   +2 ms] /Users/fortuna/Library/Android/sdk/platform-tools/adb -s ZY223TDZ45 shell echo -n 50b607b8232ee621d60b10a5bcd6e1f25337771a > /data/local/tmp/sky.io.flutter.examples.flutter_view.sha1
stdout: [  +59 ms] Moto G 4 startApp
stdout: [   +2 ms] /Users/fortuna/Library/Android/sdk/platform-tools/adb -s ZY223TDZ45 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez trace-startup true io.flutter.examples.flutter_view/com.example.view.MainActivity
stdout: [+1005 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=io.flutter.examples.flutter_view/com.example.view.MainActivity (has extras) }
stdout: [        ] Waiting for observatory port to be available...
stdout: [ +505 ms] Observatory URL on device: http://127.0.0.1:39311/
stdout: [   +8 ms] /Users/fortuna/Library/Android/sdk/platform-tools/adb -s ZY223TDZ45 forward tcp:8100 tcp:39311
stdout: [  +11 ms] Forwarded host port 8100 to device port 39311 for Observatory
stdout: [   +2 ms] Connecting to service protocol: http://127.0.0.1:8100/
stdout: [ +116 ms] Successfully connected to service protocol: http://127.0.0.1:8100/
stdout: [   +3 ms] getVM: {}
stdout: [  +12 ms] _flutter.listViews: {}
stdout: [ +189 ms] I/FlutterActivityDelegate(28264): onResume setting current activity to this
stdout: [+59823 ms] Request to Dart VM Service timed out: _flutter.listViews({})
stdout: [  +16 ms] "flutter run" took 102,759ms.
stderr: 
stderr: TimeoutException: Request to Dart VM Service timed out: _flutter.listViews({})
stderr: #0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:740)
stderr: 
stderr: #1      VM.invokeRpc (package:flutter_tools/src/vmservice.dart:757)
stderr: 
stderr: #2      VM.refreshViews (package:flutter_tools/src/vmservice.dart:853)
stderr: 
stderr: #3      VMService.waitForViews (package:flutter_tools/src/vmservice.dart:251)
stderr: 
stderr: #4      FlutterDevice.waitForViews (package:flutter_tools/src/resident_runner.dart:95)
stderr: 
stderr: #5      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:609)
stderr: 
stderr: #6      ColdRunner.run (package:flutter_tools/src/run_cold.dart:67)
stderr: 
stderr: #7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:335)
stderr: 
stderr: #8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
stderr: 
stderr: #9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
stderr: 
stderr: #10     CommandRunner.runCommand (package:args/command_runner.dart:194)
stderr: 
stderr: #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
stderr: 
stderr: #12     CommandRunner.run. (package:args/command_runner.dart:109)
stderr: #13     new Future.sync (dart:async/future.dart:222)
stderr: #14     CommandRunner.run (package:args/command_runner.dart:109)
stderr: #15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
stderr: #16     run. (package:flutter_tools/runner.dart:89)
stderr: 
stderr: #17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
stderr: 
stderr: #18     AppContext.runInZone. (package:flutter_tools/src/base/context.dart:66)
stderr: #19     _rootRun (dart:async/zone.dart:1120)
stderr: #20     _CustomZone.run (dart:async/zone.dart:1001)
stderr: #21     runZoned (dart:async/zone.dart:1467)
stderr: #22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
stderr: #23     run (package:flutter_tools/runner.dart:60)
stderr: 
stderr: #24     main (package:flutter_tools/executable.dart:43)
stderr: 
stderr: #25     main (file:///Users/fortuna/.cocoon/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
stderr: #26     _startIsolate. (dart:isolate-patch/isolate_patch.dart:263)
stderr: #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
stderr: 
stdout: [   +4 ms] exiting with code 1
exitcode: 1
Task failed: Executable failed with exit code 1.

Stack trace:
package:flutter_devicelab/framework/utils.dart 75:3        fail
package:flutter_devicelab/framework/utils.dart 255:5       exec
===== asynchronous gap ===========================
dart:async                                                 _Completer.completeError
package:flutter_devicelab/framework/utils.dart 258:1       exec
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_devicelab/framework/utils.dart 233:10      exec
package:flutter_devicelab/framework/utils.dart 303:10      flutter
package:flutter_devicelab/tasks/perf_tests.dart 100:13     StartupTest.call.
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_devicelab/tasks/perf_tests.dart 93:54      StartupTest.call.
package:flutter_devicelab/framework/utils.dart 327:24      inDirectory
===== asynchronous gap ===========================
dart:async                                                 new Future.microtask
package:flutter_devicelab/framework/utils.dart 323:80      inDirectory
package:flutter_devicelab/tasks/perf_tests.dart 93:18      StartupTest.call
===== asynchronous gap ===========================
dart:async                                                 new Future.microtask
package:flutter_devicelab/tasks/perf_tests.dart 92:35      StartupTest.call
package:flutter_devicelab/framework/framework.dart 125:36  _TaskRunner._performTask.
===== asynchronous gap ===========================
dart:async                                                 new Future.microtask
package:flutter_devicelab/framework/framework.dart 124:28  _TaskRunner._performTask.
package:stack_trace                                        Chain.capture
package:flutter_devicelab/framework/framework.dart 124:11  _TaskRunner._performTask
package:flutter_devicelab/framework/framework.dart 84:39   _TaskRunner.run

Task execution finished
```

**Comment by Hixie** [comment] 2018-05-21 22:43
I'm going to close this one because we have various bugs of this nature but this specific one isn't very actionable (not clear how to reproduce, and the logs aren't actionable).

**Closed by Hixie** 2018-05-21 22:43 UTC
