### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by JackSinner** [flutter/flutter#155485] opened 2024-09-21 08:09 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008110-000224DC0E46401E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.3 on channel stable at /Users/yuanziqiang/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (9 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yuanziqiang/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • 袁子强的iPhone (mobile)             • 00008110-000224DC0E46401E • ios            • iOS 18.0 22A3354
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.139

[!] Network resources
    ✗ A network error occurred while checking "https://maven.google.com/": Operation timed out
    ✗ A network error occurred while checking "https://cocoapods.org/": Failed host lookup: 'cocoapods.org'

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2e9cb0aa71a386a91f73f7088d115c0d96654829
### Plugins
device_info_plus-10.1.2
emoji_picker_flutter-3.0.0
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_plugin_android_lifecycle-2.0.22
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
quill_native_bridge-10.6.5
screen_brightness-1.0.1
screen_brightness_android-1.0.1
screen_brightness_ios-1.0.1
screen_brightness_macos-1.0.1
screen_brightness_windows-1.0.1
share_plus-10.0.2
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
webview_flutter-4.9.0
webview_flutter_android-3.16.7
webview_flutter_wkwebview-3.15.0

**Comment by danagbemava-nc** [comment] 2024-09-23 06:49
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-09-23 06:49 UTC
Labels: in triage
