### ISSUE TITLE
AtlasTextOp taking 1.8s to compile shader on iOS Metal (total time ~4s for one frame), causes page flip animation to jank significantly

### ISSUE THREAD

**Issue by bizz84** [flutter/flutter#76517] opened 2021-02-22 11:05 UTC
### Example 1

This is an example showing a full-screen page flip animation:

https://gist.github.com/bizz84/93a2777b33fea75f06ded660ca7ecfc2

Running this program on iOS causes severe jank on first launch:

https://user-images.githubusercontent.com/153167/108698131-ae035780-74fb-11eb-8e3e-ad946d3b8b3b.mov

On second launch things are considerably better:

https://user-images.githubusercontent.com/153167/108698163-ba87b000-74fb-11eb-909c-c76201787dd5.mov

On third launch and beyond no jank was observed.

I tried capturing some traces but I'm not sure if I've done it the right way (by the way the Medium article should be updated as it no longer matches the observatory UX):

[dart_devtools_2021_2_22-1613989729175000.log](https://github.com/flutter/flutter/files/6021436/dart_devtools_2021_2_22-1613989729175000.log)
[dart_devtools_2021_2_22-1613989058132000.log](https://github.com/flutter/flutter/files/6021438/dart_devtools_2021_2_22-1613989058132000.log)

### Example 2

Here's another example that includes some SVG assets. This was running in release mode. 

First launch:

https://user-images.githubusercontent.com/153167/108699497-39311d00-74fd-11eb-884e-0efad8aa9f30.mov

Second launch:

https://user-images.githubusercontent.com/153167/108699522-42ba8500-74fd-11eb-903f-fb5f46bd1809.mov

The jank is very noticeable on first launch. The source code for this example is here:

https://github.com/bizz84/page_flip_builder/tree/main/example

**Target Platform:** iOS
**Target OS version/browser:** 14.4
**Devices:** iPhone XR

**Related: iOS Metal jank example #76180**

## Logs

<details>
<summary>Logs</summary>

```
Analyzing page_flip_ios_jank_flutter...                                 
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel master, 1.27.0-5.0.pre.94, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-5.0.pre.94 at /Users/andrea/work/flutter/flutter_master
    • Framework revision 5642bed237 (8 hours ago), 2021-02-21 21:41:03 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andrea/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Andrea iPhone XR (mobile) • 00008020-001231380AE1002E            • ios            • iOS 14.4
    • iPhone 12 (mobile)        • BC5DD310-A3B9-495B-959E-1FEB9AA6C767 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
```

</details>

**Comment by bizz84** [comment] 2021-02-22 11:33
I'm not sure if this was discussed elsewhere, but me (and probably many others) could live with waiting on the launch screen until all shaders are loaded.

In practice, this could be an acceptable temporary fix (especially if the _right_ fix is still months away):

```dart
void main() {
  runApp(MyApp(), waitForShaders: true);
}
```

Is this something that could be done?

**Comment by renefloor** [comment] 2021-02-22 11:54
@bizz84 I like this answer from @eseidelGoogle: https://www.reddit.com/r/FlutterDev/comments/llmkd4/ios_jank_reproducible_example/gnun2au/
Especially this part:

> We will have more about that soon, but in short, current ideas include making shader compilation explicit inside the Flutter Engine to make it possible for developers to program around this necessity 

So what you propose is being worked on, but you'd probably warm each shader that you need and it won't be 1 magic boolean.

**Comment by Hixie** [comment] 2021-02-22 20:00
Thanks for a great bug!

If I'm reading the traces correctly, this looks like a problem with text-related shaders specifically.

> I'm not sure if this was discussed elsewhere, but me (and probably many others) could live with waiting on the launch screen until all shaders are loaded.

The problem with waiting for all shaders is we don't know which shaders we need until it's too late (i.e. until we're trying to render a scene with them). There's a near-infinite number of possible shaders because of the way that Skia works (e.g. it would use a different shader for a gradient with 2 stops vs a gradient with 3 stops). You can use shader warm-up to get the effect you describe, though; that's implemented and works today (you can even see it in the trace here).

**Comment by Hixie** [comment] 2021-10-15 21:55
For the record this issue was turned into an SKP test case for Skia: https://github.com/flutter/tests/blob/master/skp_generator/lib/tests/page_flip.dart

**Comment by MitchellGoodwin** [comment] 2023-12-04 20:19
CC Engine team. Is this still relevant with Impeller?

**Comment by jonahwilliams** [comment] 2023-12-11 19:07
No, we no longer think this is relevant. Closing as fixed via Impeller.

**Closed by jonahwilliams** 2023-12-11 19:07 UTC
Labels: platform-ios, engine, c: performance, dependency: skia, customer: crowd, c: rendering, perf: speed, P1, team-engine, multiteam-retriage-candidate
