### ISSUE TITLE
[web][html] Text rendered using <canvas> is blurry on Chromium based browsers

### ISSUE THREAD

**Issue by azbuky** [flutter/flutter#74986] opened 2021-01-29 15:36 UTC
## Steps to Reproduce

1. Run `flutter create bug`
2. Replace the content of `main.dart` with the code sample below
3. Add `google_fonts` package to `pubspec.yaml` 
(It is not mandatory to use the google_fonts package, but the selected font makes the blurry effect more visible)
4. Run `flutter run -d chrome --web-renderer html`

On my machine with the latest flutter master the Text in the ElevatedButton is rendered in a `<canvas>` element and it is quite blurry.

![canvas](https://user-images.githubusercontent.com/567277/106290859-9e258a00-6253-11eb-89e5-c0b0127aea37.png)

If you hover over the button the Text rendering is switched to a DOM `<p>` element and becomes much sharper.

![dom_p](https://user-images.githubusercontent.com/567277/106290879-a41b6b00-6253-11eb-8bb0-29952c176eb1.png)

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            width: 300,
            child: ElevatedButton(
              style: ElevatedButton.styleFrom(
                primary: const Color(0xffdaa525),
                textStyle: GoogleFonts.amaticSc(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                  color: Colors.white,
                ),
              ),
              onPressed: () {},
              child: Padding(
                padding: const EdgeInsets.all(20),
                child: Text("New Game"),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```
</details

**Expected results:** 
![Screenshot from 2021-01-29 15-27-45](https://user-images.githubusercontent.com/567277/106289066-7af9db00-6251-11eb-9ce5-720615b895d7.png)

**Actual results:** 

![Screenshot from 2021-01-29 15-26-22](https://user-images.githubusercontent.com/567277/106289096-80efbc00-6251-11eb-8a4d-7058a8466cc1.png)

A screenshot from one of my projects where the use of `<canvas>` and `<p>` elements is alternated and the difference is clearly visible

![Screenshot from 2021-01-29 15-14-47](https://user-images.githubusercontent.com/567277/106289353-de840880-6251-11eb-8d5c-1417b638e707.png)

Only seems to happen in Chromium based browsers.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.73, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-18.0.pre.73 at /home/azbuky/fvm/versions/master
    • Framework revision 791edc230d (9 hours ago), 2021-01-28 21:54:03 -0800
    • Engine revision 4ba79a34a0
    • Dart version 2.12.0 (build 2.12.0-272.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/azbuky/Devel/Sdks/Android/Sdk/
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/azbuky/Devel/Sdks/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /home/azbuky/Devel/Sdks/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/azbuky/Devel/Sdks/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Nexus 5X (mobile) • 026128a95bb02d50 • android-arm64  • Android 8.1.0 (API 27)
    • Linux (desktop)   • linux            • linux-x64      • Linux
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-02-01 07:55
Hi @azbuky 
Thanks for filing the issue, I can verify it.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```
```bash
[✓] Flutter (Channel dev, 1.26.0-17.1.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-17.1.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision c40e5294dd (3 days ago), 2021-01-29 08:44:18 -0800
    • Engine revision 5d3477eab4
    • Dart version 2.12.0 (build 2.12.0-259.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.90, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.90 at /Users/tahatesser/Code/flutter_master
    • Framework revision 25134a16d1 (2 days ago), 2021-01-29 23:52:30 -0800
    • Engine revision ce14c8a841
    • Dart version 2.12.0 (build 2.12.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thank you

**Comment by ferhatb** [comment] 2021-02-01 21:42
@azbuky are you only seeing this on linux or other platforms too? , i don't see a difference on macbook

**Comment by azbuky** [comment] 2021-02-01 22:36
@ferhatb 
I haven't checked recently, but I have seen the same issue at least on Windows on the same machine, in the past. I can check tomorrow.
Might be the same root cause of #58159

A few other things to note:

I am using a font scaling factor of 1.1 on Ubuntu. If I set the font scaling factor to 1, the issue goes away and the text is decent. It is not as good as when rendered using the `<p>` element but I guess this might be due to the unavailability of sub pixel antialiasing in `<canvas>`

I can replicate the blur at scaling factor of 1 when zooming the page to 110%

The following screenshot is from Gnome Tweaks - Fonts section
![Screenshot from 2021-02-01 23-50-44](https://user-images.githubusercontent.com/567277/106523638-14dbb500-64ea-11eb-8580-7341602b21f9.png)

This translates to a device pixel ratio of 1.0999 in Chrome

![Screenshot from 2021-02-01 23-57-41](https://user-images.githubusercontent.com/567277/106523710-2f159300-64ea-11eb-94dc-01429df20ec8.png)

I am not sure if it is visible in the first screenshots but I noticed the `<canvas>` element has a different width and height attribute value than the width and height in the style attribute, probably due to the scaling factor

![Screenshot from 2021-02-01 23-56-45](https://user-images.githubusercontent.com/567277/106524096-c2e75f00-64ea-11eb-8b50-ae24eb6589df.png)

I have manually added [image-rendering: pixelated](https://developers.google.com/web/updates/2015/01/pixelated) to one of the canvases, in DevTools and it seems to help to some degree, as the text looks almost as good as when using the scaling factor of 1, but still looks slightly worse. Might also be a pixel boundary misalignment when rendering text in `<canvas>`

Let me know if I can help with any more details or screenshots.

**Comment by TahaTesser** [comment] 2021-02-02 10:14
Hi @ferhatb 
We can see the difference on macOS Big Sur as well 
<img width="1108" alt="Screenshot 2021-02-02 at 3 44 17 PM" src="https://user-images.githubusercontent.com/48603081/106585625-87da3f80-656d-11eb-9908-b59d16a97836.png">

**Comment by azbuky** [comment] 2021-02-02 13:02
@ferhatb 
I have checked on more systems and got the following:

On Linux and Windows whenever the devicePixelRatio is not a whole number (whether it is from setting the system wide font scaling factor or by zooming the page in the browser) I get the blur effect on Chrome (Chromium and MS Edge also). Firefox is OK.

If you zoom in on the following screenshot from Chrome it is clearly visible the difference. The first one is the default `<canvas>` that has the blur. For the second one, I have manually added `image-rendering: pixelated` to the `<canvas>`. The third one is using the `<p>` element.

![Screenshot from 2021-02-02 14-33-30](https://user-images.githubusercontent.com/567277/106602537-d1269100-6565-11eb-83cd-536e7a771b37.png)

It seems to me that Chrome is applying an extra smoothing effect over the canvas and the text is already anti-aliased when drawn in the canvas which results in a double anti-alias effect.

**Comment by eseidelGoogle** [comment] 2021-02-03 16:44
I think I'm seeing this on gallery.flutter.dev from my ChromeBook on a second monitor as well.  
![image](https://user-images.githubusercontent.com/11857803/106779628-07aeeb00-65fc-11eb-9142-69198cad7496.png)

**Comment by hillelcoren** [comment] 2021-08-25 13:31
These links provide a comparison of the HTML and CanvasKit renderers:

- HTML: https://demo.invoiceninja.com
- CanvasKit: https://demo.invoiceninja.com/?build=wasm

Testing on Chrome/Windows the fonts appear much clearer using the CanvasKit renderer.

From https://github.com/flutter/flutter/issues/32274#issuecomment-572767237 it looks like this Chromium bug may be related.

https://bugs.chromium.org/p/chromium/issues/detail?id=1040222

**Comment by slavap** [comment] 2021-12-09 00:45
For me this workaround solves the blurry problem: https://github.com/flutter/flutter/issues/81215#issuecomment-988755443

**Comment by danagbemava-nc** [comment] 2024-04-19 11:42
I can't seem to reproduce this issue on the latest version of flutter. 

It seems like the DOM has also changed since this issue was reported. Given that we haven't had any reports in quite some time and it doesn't seeem to reproduce anymore, I'll be closing this as fixed. If anyone still experiences this issue on the latest versions of flutter, kindly file a new issue and provide the relevant information required to reproduce the issue. 

Thank you

<img width="1680" alt="Screenshot 2024-04-19 at 11 39 25" src="https://github.com/flutter/flutter/assets/88313112/c4a174e3-1f01-42b4-a600-7c6b05949f15">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.19.6 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (2 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.4.1 21E236
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 124.0.6367.60

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.22.0-14.0.pre.35, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.22.0-14.0.pre.35 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9feccd5f3b (3 hours ago), 2024-04-19 05:08:40 -0400
    • Engine revision 4ed7a2d6ae
    • Dart version 3.5.0 (build 3.5.0-77.0.dev)
    • DevTools version 2.35.0-dev.8
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (5 available)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.4.1 21E236
    • Dean’s iPad (mobile)            • 00008103-000825C811E3401E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 124.0.6367.60

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Closed by danagbemava-nc** 2024-04-19 11:42 UTC
Labels: engine, a: typography, platform-web, e: web_html, has reproducible steps, P2, found in release: 1.25, found in release: 1.26, customer: arias, team-web, triaged-web
