### ISSUE TITLE
"std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::Rasterizer... 1031 (atomic:1031)" crashes in iOS Flutter 3.16

### ISSUE THREAD

**Issue by SShayashi** [flutter/flutter#147461] opened 2024-04-27 10:42 UTC
## Overview
The following crashes have been detected in Firebase Crashlytics in production apps since Flutter 3.16. The frequency is 0.03% of all users.

```
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x7200 __pthread_kill + 8
1  libsystem_pthread.dylib        0x71ac pthread_kill + 268
2  libsystem_c.dylib              0x20c8c abort + 180
3  Flutter                        0x2e4534 fml::LogMessage::~LogMessage() + 100 (logging.cc:100)
4  Flutter                        0x2e4700 fml::FileMapping::CreateReadOnly(std::_LIBCPP_ABI_NAMESPACE::basic_string<char, std::_LIBCPP_ABI_NAMESPACE::char_traits<char>, std::_LIBCPP_ABI_NAMESPACE::allocator<char>> const&) + 21 (mapping.cc:21)
5  Flutter                        0x3ed274 std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::Rasterizer::Draw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>> const&)::$_0, std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::Rasterizer::Draw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>> const&)::$_0>, void (std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::LayerTreeItem, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::LayerTreeItem>>)>::operator()(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::LayerTreeItem, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::LayerTreeItem>>&&) + 1031 (atomic:1031)
6  Flutter                        0x3ec4c4 flutter::Rasterizer::Draw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>> const&) + 302 (unique_ptr.h:302)
7  Flutter                        0x404800 std::_LIBCPP_ABI_NAMESPACE::__function::__func<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDraw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>>)::$_0>, std::_LIBCPP_ABI_NAMESPACE::allocator<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDraw(std::_LIBCPP_ABI_NAMESPACE::shared_ptr<flutter::Pipeline<flutter::LayerTreeItem>>)::$_0>>, void ()>::operator()() + 1237 (shell.cc:1237)
8  Flutter                        0x2e5a48 fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 128 (message_loop_impl.cc:128)
9  Flutter                        0x2e91dc fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 86 (message_loop_darwin.mm:86)
10 CoreFoundation                 0xce35c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
11 CoreFoundation                 0x8a9d8 __CFRunLoopDoTimer + 940
12 CoreFoundation                 0x2e598 __CFRunLoopDoTimers + 288
13 CoreFoundation                 0x7bfcc __CFRunLoopRun + 1896
14 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
15 GraphicsServices               0x1368 GSEventRunModal + 164
16 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888
17 UIKitCore                      0x3a2034 UIApplicationMain + 340
```

I don't have the code to reproduce the issue at this time, but I created this issue because there didn't seem to be a related issue created.

<details>
<summary>  flutter doctor -v </summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.4 22F66 darwin-arm64, locale ja-JP)
    • Flutter version 3.16.0 on channel stable at /Users/01036096/fvm/versions/3.16.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (4 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/01036096/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/01036096/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode14.1.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-04-29 09:33
Hi @SShayashi 
I think this is similar to https://github.com/flutter/flutter/issues/136628. I will mark this as a duplicate of that one since there is a full crash stack. Please follow up on that for updates. Thanks!

**Closed by huycozy** 2024-04-29 09:33 UTC
Labels: in triage
