### ISSUE TITLE
Firestore runTransaction transaction.get does not work

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#18870] opened 2018-06-27 10:44 UTC
I am using the scenario for running a transaction [from the example](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/README.md#usage):

```dart
final DocumentReference postRef = Firestore.instance.document('posts/123');
Firestore.instance.runTransaction((Transaction tx) async {
  DocumentSnapshot postSnapshot = await tx.get(postRef);
  if (postSnapshot.exists) {
    await tx.update(postRef, <String, dynamic>{'likesCount': postSnapshot.data['likesCount'] + 1});
  }
});
```

It worked for me before, but [not now, apparently](https://stackoverflow.com/questions/51051730/flutter-firestore-transaction-timed-out-waiting-for-task):

```dart
DocumentSnapshot postSnapshot = await tx.get(postRef);
```

This instantly fails with a `PlatformException` , its message: `Timed out waiting for task`.

  - Flutter version: 0.5.4
  - cloud_firestore:  0.7.3

**Comment by creativecreatorormaybenot** [comment] 2018-06-28 10:14
Stacktrace from *Logcat* on *Android*:

```
E/MethodChannel#plugins.flutter.io/cloud_firestore: Failed to handle method call result
    java.lang.IllegalStateException: Task is already complete
        at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source:9)
        at com.google.android.gms.tasks.zzu.zzdr(Unknown Source:6)
        at com.google.android.gms.tasks.zzu.setResult(Unknown Source:3)
        at com.google.android.gms.tasks.TaskCompletionSource.setResult(Unknown Source:2)
        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$3$1.success(CloudFirestorePlugin.java:283)
        at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:169)
        at io.flutter.view.FlutterNativeView.handlePlatformMessageResponse(FlutterNativeView.java:187)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by creativecreatorormaybenot** [comment] 2018-08-18 11:45
I just noticed that there are actually *two different* exceptions occuring. One is `Timed out waiting for task` and the other one is `Task is already complete`. I already mentioned both of them, but also found [another question on StackOverflow having this problem](https://stackoverflow.com/q/51831864/6509751).

**Comment by rlee1990** [comment] 2018-09-18 18:00
I have a similar issue with it showing `Failed to handle method call result` and `java.lang.IllegalStateException: Task is already complete`. It also prints out the snapshot twice.

**Comment by iamjavademon** [comment] 2018-09-27 09:51
I am having same issue and i am about to run mad especially since it was working before i added a composite index to my collection.

**Comment by JotaFerreira** [comment] 2018-10-08 23:31
same issue

**Comment by Syphonjr** [comment] 2018-10-16 09:59
Did you get it fixed? I had this issue one time but somehow it fixed itself without me doing anything.

**Comment by magicleon94** [comment] 2018-10-17 21:01
Same issue here

**Comment by iamjavademon** [comment] 2018-10-18 12:02
I have decided to move the transaction activity to a firebase cloud function. Guess thats the only way for now.

**Comment by iamjavademon** [comment] 2018-10-18 12:15
Just finished writing it, tested with postman and its fine. Guess i will just start using firebase cloud functions instead of getting headaches from the flutter firestore plugin.

**Comment by RishitKedia** [comment] 2018-11-15 09:45
Hey! 👋 For the **'Task is already complete'** exception, see my other comment: [#17663 (comment)](https://github.com/flutter/flutter/issues/17663#issuecomment-438977007).

Again, as I noted there, this may not be the case for you, so YMMV, but it may help others in a similar situation. 😅

**Comment by collinjackson** [comment] 2019-02-13 15:14
This looks to be Android specific.

It seems likely that the "Task is already complete" error and printing the snapshot twice might be fixed by flutter/plugins#1202

Is the "`Timed out waiting for task`" happening always, or only under certain circumstances? Based on @iamjavademon's comment about composite indices, it seems like there might be errors that are causing the timeout.

**Comment by larssn** [comment] 2019-02-28 15:31
```
...
RaisedButton(
                    onPressed: () async {
                      _formKey.currentState.save();

                      await Firestore.instance
                          .runTransaction((Transaction trans) async {
                        final docRef = Firestore.instance
                            .document('products/' + widget.product.key);
                        await trans.get(docRef);

                        print('Saving ' + widget.product.key + ' Name: ' + name);
                        // Artificial slowness
                        await Future.delayed(Duration(seconds: 2));
                        
                        return trans.update(docRef, {'name': name});
                      });
                    },
```

**Comment by larssn** [comment] 2019-02-28 15:35
I should add that the above freeze happens in `0.9.5+2`

**Comment by nuvoPoint** [comment] 2019-02-28 17:01
> This looks to be Android specific.
> 
> It seems likely that the "Task is already complete" error and printing the snapshot twice might be fixed by [flutter/plugins#1202](https://github.com/flutter/plugins/pull/1202)
> 
> Is the "`Timed out waiting for task`" happening always, or only under certain circumstances? Based on @iamjavademon's comment about composite indices, it seems like there might be errors that are causing the timeout.

The "`Timed out waiting for task`" error happens when a document is open on two different devices after which the first one saves his update. Then after the other device tries to save his updates, he will get this error: "Error performing transaction, Timed out waiting for Task".

**Comment by larssn** [comment] 2019-02-28 19:53
So we've tested transactions using various approaches. One was basically just hooking a button up to incrementing a counter, like in the official Flutter youtube video about Firestore support (www.youtube.com/watch?v=DqJ_KjFzL9I), and it's not looking good.

Here's the transaction we're running when you click a button. The idea here is to click the button multiple times, rapidly, in order to simulate race conditions:

```
final docRef = Firestore.instance.document('somewhere/' + widget.doc.key);
Firestore.instance.runTransaction((Transaction tx) async {
  DocumentSnapshot postSnapshot = await tx.get(docRef);
  final newVal = 1 + postSnapshot['counter'];
  print('NEWVAL ' + newVal.toString());
  await tx.update(postSnapshot.reference, {
     'counter': newVal,
   });
});
```

Clicking the button 5 times, rapidly, and then checking the affected document in Firestore we'd expect the counter to show 5, but it generally showed **2** or **3**.

We've worked with transactions before, both in Cloud Functions and in the WebSDK, so I'm pretty confident we're doing it correctly. We can only conclude that transactions **ARE NOT** production ready, unlike what the youtube video seemed to indicate.

It's really a shame, because the rest seem to work really well, and Flutter in general is basically a godsend.

Ps. I can't help but notice there's a lot of open issues tied to transactions, some of which are getting old. Is anything being done about them?

**Comment by ened** [comment] 2019-03-12 06:21
Hi, Can you reproduce the issue using the latest cloud_firestore (0.9.5+2) plugin?

**Comment by HengJunXi** [comment] 2019-03-17 03:35
I think I found a workaround for this (which worked for me)
For **every document reference read** in the transaction, you must also perform update to that specific document reference (even though no change to the data)

Following code works successfully using cloud_firestore 0.8.2+3
```
db.runTransaction((Transaction tx) async {
    var courseDoc = await tx.get(courseRef);       // read courseRef
    await tx.update(courseRef, courseDoc.data);    // extra update to courseRef
    await tx.set(chatRef, chat);                   // actual intended operation
}
```

**Comment by RussellZornes** [comment] 2019-05-30 00:04
My transaction code has been running fine for months and suddenly the transactions are simply not running. No exceptions no logcat output no nothing. Just never returns or invokes the callback. Seems like its stuck waiting. There are no other firestore operations occurring at the same time so its not blocked as far as I can tell.

This was working fine for months then it suddenly stopped.

```
      Future<void> transactionUpdate(String path, Map<String, dynamic> json) async {
        DocumentReference doc = firestore.document(path);
        firestore.runTransaction((Transaction tx) async {
          DocumentSnapshot snapshot = await tx.get(doc);
          if (snapshot.exists) {
            await tx.update(doc, json);
          } else {
            await tx.set(doc, json);
          }
        });
      }

```

I am using cloud_firestore: 0.12.0


```
    [√] Flutter (Channel master, v1.6.6-pre.15, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
        • Flutter version 1.6.6-pre.15 at C:\dev\libraries\flutter2\flutter
        • Framework revision 8139a368ea (7 hours ago), 2019-05-29 10:08:58 -0700
        • Engine revision 8dc3a4cde2
        • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)
    
    [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
        • Android SDK at C:\dev\libraries\android-sdk
        • Android NDK location not configured (optional; useful for native profiling support)
        • Platform android-28, build-tools 28.0.3
        • ANDROID_HOME = C:\dev\libraries\android-sdk
        • Java binary at: C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio\jre\bin\java
        • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
        • All Android licenses accepted.
    
    [√] Android Studio (version 3.4)
        • Android Studio at C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio
        • Flutter plugin version 35.3.1
        • Dart plugin version 183.6270
        • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

```

**Comment by samvidmistry** [comment] 2019-05-30 07:13
I'm having the same problem as @RussellZornes. I'm on using cloud_firestore: 0.12.1. The code in a transaction is not being executed. It works fine if you put it outside a transaction. The app is not stuck and works fine. Just the transaction is not working. There are no other operations going on because only I have the app. I am working with Intellij, not Android Studio.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.6.4-pre.5, on Linux, locale en_IN.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.2)
[✓] Android Studio (version 3.2)
[!] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] IntelliJ IDEA Community Edition (version 2019.1)
[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by jasonkaruza** [comment] 2019-06-01 16:46
Same here with cloud_firestore 0.10.1. A transaction that consistently worked suddenly won't go into the runTransaction handler:

> [√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.503], locale en-US)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     X Android license status unknown.
>       Try re-installing or updating your Android SDK Manager.
>       See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-> setup for detailed instructions.
> [√] Android Studio (version 3.3)
> [√] VS Code (version 1.34.0)
> [√] Connected device (1 available)
> 
> ! Doctor found issues in 1 category.

```
// Perform the atomic update
    await _store.runTransaction((transaction) async {
      DocumentSnapshot latest = await transaction.get(countSnapshot.reference);
      try {
        print(
            "Updating count to " + (latest[keyCount] + amount).toString());
        await transaction.update(latest.reference, {
          keyCount: val = (latest[keyCount] + amount),
        });
      } catch (error) {
        print("Failed to update $collection count: $error");
      }
      print("New count for $collection is $val");
    }).catchError((error) {
      print("Failed to change the count for $collection: $error");
      return null;
    });
````

**Comment by ukuleleplayer** [comment] 2019-06-06 09:24
Joining the choir of people - my transactions no longer work. cloud_firestore 0.12.1

**Comment by vshashi01** [comment] 2019-06-11 23:45
Same in my app as well, the transaction never gets through.. even a simplified get operation seems to be not running when put inside a transaction. Any other solutions for atomic operations?

**Comment by collinjackson** [comment] 2019-06-13 17:46
Transactions were fixed in 0.12.2, see #1701.

Please let me know if upgrading doesn't help and I'm happy to reopen this issue.

**Closed by collinjackson** 2019-06-13 17:46 UTC
Labels: p: cloud_firestore, p: firebase, p: first party, plugin, severe: crash, ▣ platform-android

**Comment by ride4sun** [comment] 2019-07-18 16:46
I just run into the same problem. My Transaction are not executing and I have no idea where to go from here. This is with the latest version of cloud_firestore 0.12.7 and the latest stable flutter release 1.7. 
And line many others indicated there are no exceptions. 

This is super important to us be because all depends on these calls being reliable. 
I really hopes this get attention.

**Comment by collinjackson** [comment] 2019-07-18 21:18
@ride4sun Does it work if you call `transaction.set` instead of calling `setData()` on the reference?

**Comment by ride4sun** [comment] 2019-07-18 21:30
> @ride4sun Does it work if you call `transaction.set` instead of calling `setData()` on the reference?

Like this?
```
    _fireStore.runTransaction(
      (Transaction transaction) async {
        transaction.set(_fireStore.collection("users").document(email),
            {'email': email, 'displayName': displayName});
      },
    );

```

**Comment by collinjackson** [comment] 2019-07-18 21:41
Yeah

**Comment by ride4sun** [comment] 2019-07-18 21:55
Tried it , does not execute...

_fireStore.runTransaction(
      (Transaction transaction) async {

------- anything inside here is not executed ----------

      },
    );

**Comment by ride4sun** [comment] 2019-07-22 05:42
Is this fixed in the devopment branch or why  do we not reopen this Issue?

**Comment by collinjackson** [comment] 2019-07-22 15:58
> Is this fixed in the devopment branch or why do we not reopen this Issue?

The fix was to the plugin (0.12.2) rather than to Flutter. The integration tests for cloud_firestore transactions are passing on both iOS and Android. So something must be different about your setup.

```
    test('runTransaction', () async {
      final DocumentReference ref = firestore.collection('messages').document();
      await ref.setData(<String, dynamic>{
        'message': 'testing',
        'created_at': FieldValue.serverTimestamp(),
      });
      final DocumentSnapshot initialSnapshot = await ref.get();
      expect(initialSnapshot.data['message'], 'testing');
      final dynamic result = await firestore.runTransaction(
        (Transaction tx) async {
          final DocumentSnapshot snapshot = await tx.get(ref);
          final Map<String, dynamic> updatedData =
              Map<String, dynamic>.from(snapshot.data);
          updatedData['message'] = 'testing2';
          tx.update(ref, updatedData); // calling await here is optional
          return updatedData;
        },
      );
      expect(result['message'], 'testing2');

      await ref.delete();
      final DocumentSnapshot nonexistentSnapshot = await ref.get();
      expect(nonexistentSnapshot.data, null);
      expect(nonexistentSnapshot.exists, false);
    });
```

```
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         2.5s
I/flutter ( 5218): Observatory listening on http://127.0.0.1:42166/nDUUkDzgUng=/
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:52973/nDUUkDzgUng=/
[trace] FlutterDriver: Isolate found with number: 3627700187582027
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
I/flutter ( 5218): 00:00 +0: Firestore getDocumentsWithFirestoreSettings
[info ] FlutterDriver: Connected to Flutter application.
I/flutter ( 5218): 00:00 +1: Firestore getDocumentsFromCollection
I/flutter ( 5218): 00:01 +2: Firestore getDocumentsFromCollectionGroup
I/flutter ( 5218): 00:01 +3: Firestore increment
I/flutter ( 5218): 00:03 +4: Firestore runTransaction
I/flutter ( 5218): 00:04 +5: Firestore pagination
I/flutter ( 5218): 00:06 +6: Firestore pagination with map
I/flutter ( 5218): 00:07 +7: (tearDownAll)
I/flutter ( 5218): 00:07 +8: All tests passed!
Stopping application instance.
```

Since the original issue was fix and is covered by tests, I'm leaving this issue closed, but you can file a new issue with steps to reproduce if you aren't able to solve this by updating to cloud_firestore 0.12.2.

**Comment by thevzurd** [comment] 2019-08-19 03:20
I had the same problem. Try this. Hope it Helps 
[FIrestore Transaction Handler](https://github.com/thevzurd/Firestore-Transaction-Handler)

**Comment by kroikie** [comment] 2019-10-13 19:04
@creativecreatorormaybenot

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/778. Any further collaboration will be done there.
