### ISSUE TITLE
Issue with launching another app.

### ISSUE THREAD

**Issue by VickySalunkhe** [flutter/flutter#41019] opened 2019-09-21 09:02 UTC
I have tried using **android_intent** and **url_launcher** package for launching another app

but both are failing and returning different error
so posting both errors and code I am using for both respectively 

Facing issues with all apps which I have tried to launch

` What I am actually trying to achieve is to use upi transaction through flutter app`

I know there is library **flutter_upi** for that 
but that library is creating issues with **image_picker** and **google_sign_in** plugin so cant use that library so `looking forward to find / build a alternative for it.`

refer error facing with **image_picker** and **google_sign_in** while using **flutter_upi** library [here](https://github.com/flutter/flutter/issues/40339) and [here](https://github.com/flutter/flutter/issues/40337) respectively

I have raised the issue about **flutter_upi** to author but it seems that he is inactive for sometime
you can check it [here](https://github.com/samarthagarwal/flutter_upi/issues/4)

**android_intent**

**CODE**
have tried using only appID too throws same error
found to launch the app need to use infront of app id
```
here appID -> com.whatsapp      (example)
AndroidIntent intent = AndroidIntent(action: 'action_view', data: "package:"+appID);
await intent.launch();

```
**LOG**
```
> I/io.flutter.plugins.androidintent.AndroidIntentPlugin(16939): Sending intent Intent { act=android.intent.action.VIEW dat=package:com.google.android.apps.walletnfcrel }
> I/Timeline(16939): Timeline: Activity_launch_request time:667142748 intent:Intent { act=android.intent.action.VIEW dat=package:com.google.android.apps.walletnfcrel }
> E/MethodChannel#plugins.flutter.io/android_intent(16939): Failed to handle method call
> E/MethodChannel#plugins.flutter.io/android_intent(16939): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=package:com.google.android.apps.walletnfcrel }
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1816)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.app.Activity.startActivityForResult(Activity.java:4396)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.app.Activity.startActivityForResult(Activity.java:4355)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.app.Activity.startActivity(Activity.java:4679)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.app.Activity.startActivity(Activity.java:4647)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at io.flutter.plugins.androidintent.AndroidIntentPlugin.onMethodCall(AndroidIntentPlugin.java:157)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.os.MessageQueue.next(MessageQueue.java:329)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.os.Looper.loop(Looper.java:142)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
> E/MethodChannel#plugins.flutter.io/android_intent(16939): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
> E/flutter (16939): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=android.intent.action.VIEW dat=package:com.google.android.apps.walletnfcrel }, null)
> [38;5;244mE/flutter (16939): #0      StandardMethodCodec.decodeEnvelope[39;49m
> [38;5;244mE/flutter (16939): #1      MethodChannel.invokeMethod[39;49m
> E/flutter (16939): <asynchronous suspension>
> [38;5;248mE/flutter (16939): #2      AndroidIntent.launch[39;49m
> E/flutter (16939): <asynchronous suspension>
> [38;5;248mE/flutter (16939): #3      _DonateScreenTwoState._launchApp[39;49m
> E/flutter (16939): <asynchronous suspension>
> [38;5;248mE/flutter (16939): #4      _DonateScreenTwoState.build.<anonymous closure>[39;49m
> [38;5;244mE/flutter (16939): #5      _InkResponseState._handleTap[39;49m
> [38;5;244mE/flutter (16939): #6      _InkResponseState.build.<anonymous closure>[39;49m
> [38;5;244mE/flutter (16939): #7      GestureRecognizer.invokeCallback[39;49m
> [38;5;244mE/flutter (16939): #8      TapGestureRecognizer._checkUp[39;49m
> [38;5;244mE/flutter (16939): #9      TapGestureRecognizer.acceptGesture[39;49m
> [38;5;244mE/flutter (16939): #10     GestureArenaManager.sweep[39;49m
> [38;5;244mE/flutter (16939): #11     GestureBinding.handleEvent[39;49m
> [38;5;244mE/flutter (16939): #12     GestureBinding.dispatchEvent[39;49m
> [38;5;244mE/flutter (16939): #13     GestureBinding._handlePointerEvent[39;49m
> [38;5;244mE/flutter (16939): #14     GestureBinding._flushPointerEventQueue[39;49m
> [38;5;244mE/flutter (16939): #15     GestureBinding._handlePointerDataPacket[39;49m
> [38;5;244mE/flutter (16939): #16     _rootRunUnary  (dart:async/zone.dart:1136:13)[39;49m
> [38;5;244mE/flutter (16939): #17     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)[39;49m
> [38;5;244mE/flutter (16939): #18     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)[39;49m
> [38;5;244mE/flutter (16939): #19     _invoke1  (dart:ui/hooks.dart:263:10)[39;49m
> [38;5;244mE/flutter (16939): #20     _dispatchPointerDataPacket  (dart:ui/hooks.dart:172:5)[39;49m
> E/flutter (16939):
> 
```

**url_launcher**

**CODE**

```
// here appID -> com.whatsapp      (example)
if (await canLaunch(appID))
      await launch(appID);
else
      throw 'Could not launch $appID';
```

**LOG**
```
> E/flutter (18367): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Could not launch com.whatsapp
> [38;5;248mE/flutter (18367): #0      _DonateScreenTwoState._launchApp[39;49m
> E/flutter (18367): <asynchronous suspension>
> [38;5;248mE/flutter (18367): #1      _DonateScreenTwoState.build.<anonymous closure>[39;49m
> [38;5;244mE/flutter (18367): #2      _InkResponseState._handleTap[39;49m
> [38;5;244mE/flutter (18367): #3      _InkResponseState.build.<anonymous closure>[39;49m
> [38;5;244mE/flutter (18367): #4      GestureRecognizer.invokeCallback[39;49m
> [38;5;244mE/flutter (18367): #5      TapGestureRecognizer._checkUp[39;49m
> [38;5;244mE/flutter (18367): #6      TapGestureRecognizer.acceptGesture[39;49m
> [38;5;244mE/flutter (18367): #7      GestureArenaManager.sweep[39;49m
> [38;5;244mE/flutter (18367): #8      GestureBinding.handleEvent[39;49m
> [38;5;244mE/flutter (18367): #9      GestureBinding.dispatchEvent[39;49m
> [38;5;244mE/flutter (18367): #10     GestureBinding._handlePointerEvent[39;49m
> [38;5;244mE/flutter (18367): #11     GestureBinding._flushPointerEventQueue[39;49m
> [38;5;244mE/flutter (18367): #12     GestureBinding._handlePointerDataPacket[39;49m
> [38;5;244mE/flutter (18367): #13     _rootRunUnary  (dart:async/zone.dart:1136:13)[39;49m
> [38;5;244mE/flutter (18367): #14     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)[39;49m
> [38;5;244mE/flutter (18367): #15     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)[39;49m
> [38;5;244mE/flutter (18367): #16     _invoke1  (dart:ui/hooks.dart:263:10)[39;49m
> [38;5;244mE/flutter (18367): #17     _dispatchPointerDataPacket  (dart:ui/hooks.dart:172:5)[39;49m
> E/flutter (18367):
> 
```

**Comment by stuartmorgan** [comment] 2021-06-29 18:49
> // here appID -> com.whatsapp      (example)
> if (await canLaunch(appID))
>       await launch(appID);
> else
>       throw 'Could not launch $appID';

`url_launcher` launches URLs; an app ID is not a URL. Closing as this is expected behavior, not a bug in `url_launcher`.

**Closed by stuartmorgan** 2021-06-29 18:49 UTC
Labels: p: first party, p: url_launcher, plugin, severe: crash
