### ISSUE TITLE
[et] Startup time is about 10s

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#147985] opened 2024-05-08 16:18 UTC
## details
os: macos
network: google wifi

## seen results
There is about 10 seconds between invoking `./flutter/bin/et build -c host_debug_unopt_arm64 //flutter/impeller:impeller_unittests` and seeing `[2024-05-08T09:16:10.317][macos/host_debug_unopt_arm64: GN]: OK` printed out.

## expected results
I'd expect to have faster startup time (sub 1s).  Or better transparency about what it is doing for 10s.

**Comment by matanlurey** [comment] 2024-05-10 18:52
I _think_ this is a duplicate of https://github.com/flutter/flutter/issues/147666.

**Closed by matanlurey** 2024-05-10 18:52 UTC
Labels: team-engine, e: engine-tool
