### ISSUE TITLE
C++ crash when java throws exception in plugin callback

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10771] opened 2017-06-16 16:16 UTC
@lukef just ran into a crash.  I've seen it before.  I'm pretty sure this happens when dart calls into java and java throws an uncaught exception.

The bug here is that we crash in an obtuse manner.  Fine to crash, just need to explain why.

```
06-16 09:06:51.510 12181-12181/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-16 09:06:51.511 12181-12181/? A/DEBUG: Build fingerprint: 'google/bullhead/bullhead:7.1.2/NPG47I/3795619:user/release-keys'
06-16 09:06:51.511 12181-12181/? A/DEBUG: Revision: 'rev_1.0'
06-16 09:06:51.511 12181-12181/? A/DEBUG: ABI: 'arm'
06-16 09:06:51.511 12181-12181/? A/DEBUG: pid: 12027, tid: 12027, name: om.example.app  >>> com.example.app <<<
06-16 09:06:51.511 12181-12181/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-16 09:06:51.515 12181-12181/? A/DEBUG: Abort message: '[FATAL:../../flutter/shell/platform/android/platform_view_android_jni.cc(30)] Check failed: env->ExceptionCheck() == JNI_FALSE. 
                                          '
06-16 09:06:51.515 12181-12181/? A/DEBUG:     r0 00000000  r1 00002efb  r2 00000006  r3 00000008
06-16 09:06:51.515 12181-12181/? A/DEBUG:     r4 ed9e658c  r5 00000006  r6 ed9e6534  r7 0000010c
06-16 09:06:51.515 12181-12181/? A/DEBUG:     r8 ffcd848c  r9 e0fc2a80  sl ffcd84f8  fp dfaf2f98
06-16 09:06:51.515 12181-12181/? A/DEBUG:     ip 0000000b  sp ffcd8330  lr ec22c5e7  pc ec22ee44  cpsr 200f0010
```

**Comment by mit-mit** [comment] 2017-06-16 16:16
cc @mravn-google

**Comment by mravn-google** [comment] 2017-06-16 16:46
The site where we invoke the plugin callback in Java is already guarded by a try-catch construct which will catch and log any `java.lang.Exception` thrown by the plugin.

@lukef Did you discover what type of Java `Throwable` was involved?

**Comment by lukef** [comment] 2017-06-16 17:21
It was actually due to a library version mismatch between our app and the Firebase plugins and not an actual java code error.

**Comment by PixelToast** [comment] 2017-07-14 08:38
I can reproduce this by using an outdated google_sign_in:
```
dependencies:
  google_sign_in: "^0.2.1"
  firebase_analytics: "^0.0.4"
  firebase_auth: "^0.1.1"
  firebase_database: "^0.0.12"
  firebase_storage: "^0.0.5"
```
Using latest flutter `Framework revision 547708b327 (7 hours ago), 2017-07-13 18:08:14 -0700`
adb log: https://hastebin.com/raw/keyuzeroyi

Fixed by upgrading google_sign_in

I can make a repo to reproduce this if you are still looking into the issue

**Comment by kirbyfan64** [comment] 2017-08-15 14:26
Aaaah I just encountered this in https://github.com/kirbyfan64/zdata/issues/2. It makes the logcats kinda useless...

**Comment by iapicca** [comment] 2019-11-01 13:08
Hi @eseidelGoogle  is this issue still meant to be open?

**Closed** 2019-11-06 14:37 UTC
Labels: customer: posse (eap), engine, p: framework, waiting for customer response, ▣ platform-android

**Comment by omerrciftcii** [comment] 2020-04-03 20:20
Hello I am getting this error from different android emulator. One of the emulator is working fine, emulator which occurs the problem is: 



```
Name: Pixel

CPU/ABI: Google APIs Intel Atom (x86)

Path: C:\Users\omercftc\.android\avd\Pixel.avd

Target: google_apis [Google APIs] (API level 28)

Skin: pixel_xl_silver

SD Card: 512 MB

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_xl

hw.lcd.width: 1440

hw.initialOrientation: Portrait

image.androidVersion.api: 28

tag.id: google_apis

hw.mainKeys: no

hw.camera.front: webcam0

avd.ini.displayname: Pixel

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 2560

vm.heapSize: 384

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images\android-28\google_apis\x86\

showDeviceFrame: yes

hw.camera.back: emulated

AvdId: Pixel

hw.lcd.density: 560

hw.arc: false

hw.device.hash2: MD5:f78477654d5471c3d7f705251d14e72f

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

disk.dataPartition.size: 2G

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes 
```


and there is no problem this emulator:



```
Name: Pixel3

CPU/ABI: Google APIs Intel Atom (x86)

Path: C:\Users\omercftc\.android\avd\Pixel3_1.avd

Target: google_apis [Google APIs] (API level 28)

Skin: pixel_2_xl

SD Card: 512 MB

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_2_xl

hw.lcd.width: 1440

hw.initialOrientation: Portrait

image.androidVersion.api: 28

tag.id: google_apis

hw.mainKeys: no

hw.camera.front: webcam0

avd.ini.displayname: Pixel3

hw.gpu.mode: auto

hw.ramSize: 2048

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 2880

vm.heapSize: 216

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images\android-28\google_apis\x86\

showDeviceFrame: yes

hw.camera.back: emulated

AvdId: Pixel3

hw.lcd.density: 560

hw.arc: false

hw.device.hash2: MD5:ce72d6c2506218ad8c9cc1cfa7e13357

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

disk.dataPartition.size: 12000M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```



here is my error:

```
 [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: No implementation found for int 
io.agora.rtc.internal.RtcEngineImpl.nativeLog(int, java.lang.String) (tried Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog and Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog__ILjava_lang_String_2)
E/flutter (27417):      at io.agora.rtc.internal.RtcEngineImpl.nativeLog(Native Method)
E/flutter (27417):      at io.agora.rtc.internal.Logging.log(Logging.java:25)
E/flutter (27417):      at io.agora.rtc.internal.Logging.i(Logging.java:49)
E/flutter (27417):      at io.agora.rtc.internal.RtcEngineImpl.checkIfInUIThread(RtcEngineImpl.java:155)
E/flutter (27417):      at io.agora.rtc.RtcEngine.CreateRendererView(RtcEngine.java:881)
E/flutter (27417):      at io.agora.agorartcengine.AgoraRenderViewFactory.create(AgoraRenderViewFactory.java:22)
E/flutter (27417):      at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:176)
E/flutter (27417):      at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
E/flutter (27417):      at android.app.Dialog.show(Dialog.java:302)
E/flutter (27417):      at android.app.Presentation.show(Presentation.java:249)
E/flutter (27417):      at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
E/flutter (27417):      at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:46)
E/flutter (27417):      at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:112)
E/flutter (27417):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:95)
E/flutter (27417):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (27417):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/flutter (27417):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (27417):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/flutter (27417):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (27417):      at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (27417):      at android.os.Looper.loop(Looper.java:160)
E/flutter (27417):      at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter (27417):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (27417):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (27417):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (27417):
F/flutter (27417): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
F/libc    (27417): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27417 (.provider_login), pid 27417 (.provider_login)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:9/PSR1.180720.117/5875966:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
pid: 27417, tid: 27417, name: .provider_login  >>> com.example.provider_login <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
'
    eax 00000000  ebx 00006b19  ecx 00006b19  edx 00000006
    edi 00006b19  esi 00000070
    ebp fffb0558  esp fffb04f8  eip e985bb39
backtrace:
    #00 pc 00000b39  [vdso:e985b000] (__kernel_vsyscall+9)
    #01 pc 0001fdf8  /system/lib/libc.so (syscall+40)
    #02 pc 00022ed3  /system/lib/libc.so (abort+115)
    #03 pc 011b4a97  /data/app/com.example.provider_login-Pg_5Meq6KRjCZM4HtxLkIA==/lib/x86/libflutter.so (offset 0x1198000)
    #04 pc 011a16e7  /data/app/com.example.provider_login-Pg_5Meq6KRjCZM4HtxLkIA==/lib/x86/libflutter.so (offset 0x1198000)
    #05 pc 0119f480  /data/app/com.example.provider_login-Pg_5Meq6KRjCZM4HtxLkIA==/lib/x86/libflutter.so (offset 0x1198000)
    #06 pc 01207435  /data/app/com.example.provider_login-Pg_5Meq6KRjCZM4HtxLkIA==/lib/x86/libflutter.so (offset 0x1198000)
    #07 pc 011b2d2f  /data/app/com.example.provider_login-Pg_5Meq6KRjCZM4HtxLkIA==/lib/x86/libflutter.so (offset 0x1198000)
    #08 pc 011b57e9  /data/app/com.example.provider_login-Pg_5Meq6KRjCZM4HtxLkIA==/lib/x86/libflutter.so (offset 0x1198000)
    #09 pc 011b572e  /data/app/com.example.provider_login-Pg_5Meq6KRjCZM4HtxLkIA==/lib/x86/libflutter.so (offset 0x1198000)
    #10 pc 011bb600  /data/app/com.example.provider_login-Pg_5Meq6KRjCZM4HtxLkIA==/lib/x86/libflutter.so (offset 0x1198000)
    #11 pc 011bb62e  /data/app/com.example.provider_login-Pg_5Meq6KRjCZM4HtxLkIA==/lib/x86/libflutter.so (offset 0x1198000)
    #12 pc 00012a77  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39)
    #13 pc 00013896  /system/lib/libutils.so (android::Looper::pollInner(int)+998)
    #14 pc 0001340b  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+43)
    #15 pc 000e415b  /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+59)
    #16 pc 003ddb28  /system/framework/x86/boot-framework.oat (offset 0x3ca000) (android.media.MediaExtractor.seekTo [DEDUPED]+136)
    #17 pc 0000cec6  /dev/ashmem/dalvik-jit-code-cache (deleted) (android.os.MessageQueue.next+230)
    #18 pc 005f0a02  /system/lib/libart.so (art_quick_invoke_stub+338)
    #19 pc 000a2f4e  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+222)
    #20 pc 0029bb22  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+338)
    #21 pc 00293cc8  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction 
const*, unsigned short, art::JValue*)+1048)
    #22 pc 005bc353  /system/lib/libart.so (MterpInvokeVirtual+691)
    #23 pc 005e2ba1  /system/lib/libart.so (ExecuteMterpImpl+14241)
    #24 pc 00aea9fc  /system/framework/boot-framework.vdex (android.os.Looper.loop+128)
    #25 pc 00266096  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3007865774+598)
    #26 pc 0026c61c  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+220)
    #27 pc 00293cab  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction 
const*, unsigned short, art::JValue*)+1019)
    #28 pc 005bdb1f  /system/lib/libart.so (MterpInvokeStatic+207)
    #29 pc 005e2d21  /system/lib/libart.so (ExecuteMterpImpl+14625)
    #30 pc 00384cd2  /system/framework/boot-framework.vdex (android.app.ActivityThread.main+214)
    #31 pc 00266096  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3007865774+598)
    #32 pc 0026c50e  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+126)
    #33 pc 005a93fd  /system/lib/libart.so (artQuickToInterpreterBridge+1277)
    #34 pc 005f6aed  /system/lib/libart.so (art_quick_to_interpreter_bridge+77)
    #35 pc 005f0bd2  /system/lib/libart.so (art_quick_invoke_static_stub+418)
    #36 pc 000a2f5f  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+239)
    #37 pc 004d3209  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, 
art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+89)
    #38 pc 004d4eee  /system/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+1422)
    #39 pc 00449643  /system/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+83)
    #40 pc 0011d778  /system/framework/x86/boot.oat (offset 0x114000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+168)
    #41 pc 005f0a02  /system/lib/libart.so (art_quick_invoke_stub+338)
    #42 pc 000a2f4e  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+222)
    #43 pc 0029bb22  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+338)
    #44 pc 00293cc8  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction 
const*, unsigned short, art::JValue*)+1048)
    #45 pc 005bc353  /system/lib/libart.so (MterpInvokeVirtual+691)
    #46 pc 005e2ba1  /system/lib/libart.so (ExecuteMterpImpl+14241)
    #47 pc 00c0b966  /system/framework/boot-framework.vdex (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
    #48 pc 00266096  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3007865774+598)
    #49 pc 0026c50e  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+126)
    #51 pc 005f6aed  /system/lib/libart.so (art_quick_to_interpreter_bridge+77)
    #52 pc 00badc2c  /system/framework/x86/boot-framework.oat (offset 0x3ca000) (com.android.internal.os.ZygoteInit.main+3100)
    #53 pc 005f0bd2  /system/lib/libart.so (art_quick_invoke_static_stub+418)
    #54 pc 000a2f5f  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+239)
    #55 pc 004d3209  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, 
art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+89)
    #56 pc 004d2e8d  /system/lib/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, char*)+429)      
    #57 pc 003a770d  /system/lib/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+925)
    #58 pc 000d90f3  /system/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, char*, art::Primitive::Type, art::InvokeType)+2867)
    #59 pc 000c6ba9  /system/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+73)        
    #60 pc 0007098e  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+62)
    #61 pc 00073e88  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+744)   
    #62 pc 00001bb2  /system/bin/app_process32 (main+1506)
    #63 pc 000c0f54  /system/lib/libc.so (__libc_init+100)
Lost connection to device.
PS C:\Users\omercftc\Documents\Projects\provider_login> flutter doctor -v
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18363.720], locale en-GB)
    • Flutter version 1.15.17 at C:\src\flutter
    • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\omercftc\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\omercftc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (4 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • AOSP on IA Emulator • emulator-5556 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome              • chrome        • web-javascript • Google Chrome 80.0.3987.163
    • Web Server          • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```


is anyone know why this error occurs? I am trying to use agora rtc engine

**Comment by iapicca** [comment] 2020-04-06 13:32
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
