### ISSUE TITLE
[mac andriod release test] poosible flaky target fails many times during re-run

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#110053] opened 2022-08-23 00:59 UTC
the target mac andriod release test fails on post submit, an example would be https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20run_release_test. for the two commits I am testing at https://flutter-dashboard.appspot.com/#/build?taskFilter&authorFilter&messageFilter&hashFilter&showMac=true&showWindows=true&showiOS=true&showLinux=true&showAndroid=true&showStaging=false&repo=flutter&branch=flutter-3.2-candidate.5, one of them succeeded on the 2nd try, the other one is still failing on the 4 th try. Can we double check if there is a flake in the test target? Thank you!

**Comment by jmagman** [comment] 2022-08-23 01:02
> [run_release_test] [STDOUT] run:stderr: Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>


https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8805082649715414481/+/u/run_run_release_test/test_stdout

Looks like a duplicate of https://github.com/flutter/flutter/issues/105715

**Comment by jmagman** [comment] 2022-08-23 01:03
Was marked flaky in https://github.com/flutter/flutter/pull/109890.

**Closed by jmagman** 2022-08-23 01:02 UTC
