### ISSUE TITLE
[flake] flutter doctor timed out after three hours

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#100731] opened 2022-03-25 00:54 UTC
Mac tool_integration_tests_4_4 and Mac tool_tests_general  timed out at the step device doctor. The problem is observed in recent stable release, at https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_tests_4_4/17946/overview, And during presubmit checks at https://github.com/flutter/flutter/pull/100716. Not sure if it is a release related problem, would be great if @christopherfujino could take a look. cc @godofredoc

**Comment by godofredoc** [comment] 2022-03-25 00:56
Chris did something change recently on how flutter doctor is running? we have had a few timeouts.

**Comment by christopherfujino** [comment] 2022-03-25 18:26
I think it's either the `androidValidator` or `androidLicenseValidator`, continuing to investigate

**Comment by godofredoc** [comment] 2022-03-25 19:33
I believe the open question is if `flutter doctor` never completed until it was killed or if `flutter doctor` finished with an error and luci step hung of the leaked processes to complete.

**Comment by christopherfujino** [comment] 2022-03-25 19:51
I'm pretty sure that it never completed. I would expect some kind of log output if it failed.

**Comment by goderbauer** [comment] 2022-03-28 21:00
I've been running in this problem as well, both `Mac tool_tests_commands` and `Mac tool_tests_general` are getting stuck on my PRs. Examples: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20tool_tests_general/10474/overview, https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20tool_tests_general/10478/overview

**Comment by goderbauer** [comment] 2022-03-28 21:26
This is now also the root cause for the tree redness.

**Comment by christopherfujino** [comment] 2022-03-28 22:24
it doesn't look like my PR to add debug worked: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20build_tests_2_4/3993/overview

**Comment by christopherfujino** [comment] 2022-03-29 23:03
Haven't seen this since landing https://github.com/flutter/flutter/pull/100936, optimistically closing

**Closed by christopherfujino** 2022-03-29 23:03 UTC
Labels: t: flutter doctor, team: flakes, team: infra, P0
