### ISSUE TITLE
The desktop application could not fetch the VPN connection

### ISSUE THREAD

**Issue by Chesterguan** [flutter/flutter#47680] opened 2019-12-23 15:59 UTC
### The problem about the VPN connection on Flutter Desktop Application 

Hi there, I and my team wrote a small application with flutter. It works very well and quickly in mobile platforms. Recently, we would like to convert the mobile application into the `Desktop` version. By following the [documents](https://github.com/google/flutter-desktop-embedding) and resources [here](https://medium.com/flutter-community/flutter-for-desktop-create-and-run-a-desktop-application-ebeb1604f1e0 ). The codes could run successfully. However, before using the application, we should check the VPN connection since the database is private and secured. The mobile application works well while the desktop platform will raise the exception  

>  ***flutter: SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = my.irb.ufl.edu, port = 443***

And also, if we bypassed the checking process and try to connect with the server directly, it will also raise the **SocketException**. 

The codes are shown below:
![Screen Shot 2019-12-23 at 10 49 19 AM](https://user-images.githubusercontent.com/31426497/71367072-e747dc80-2571-11ea-85b1-ec2e884e2d18.png)
We just easily check the connection with the [`Http Package`](https://pub.dev/packages/http).

**Other Information:**
1. OS platform :  macOS
2. version : flutter upgraded and all of the packages are updated.
3. We only replaced the `lib` folder and `pubspec.yaml` to make sure the configuration is correct.
4. We used the `Cisco Anyconnect` Software to build the VPN connection.

We thought it might be the problem of the package that could not well-working in desktop application or there should be a bridge between the VPN connection and flutter desktop application. 
Thanks for your time and if you have any suggestions please share with us.

**Comment by stuartmorgan** [comment] 2019-12-23 16:31
Duplicate of https://github.com/flutter/flutter/issues/47606

**Closed by stuartmorgan** 2019-12-23 16:31 UTC

**Comment by Chesterguan** [comment] 2019-12-23 16:42
@stuartmorgan  Hi, thanks for your information and it works now!
For others' information :100:  
**Add**
`<key>com.apple.security.network.client</key>`
`<true/>`
to file `DebugProfile.entitlements` under directory `macos/Runner/`

**Comment by stuartmorgan** [comment] 2019-12-23 16:52
If you only added it to that file, your release builds will have the same problem. Prior should follow the instructions linked from the other issue, which provide more complete information.

**Comment by Chesterguan** [comment] 2019-12-23 16:55
Yep I also add it to the release file. Thanks for your information and have a nice day! I will change my answer as well

Ziyuan Guan
Data Analyst From PrismaP Team
College of Medicine, University of Florida
________________________________
发件人: stuartmorgan <notifications@github.com>
发送时间: Monday, December 23, 2019 11:52:56 AM
收件人: flutter/flutter <flutter@noreply.github.com>
抄送: Guan,Ziyuan <ziyuan.guan@ufl.edu>; Author <author@noreply.github.com>
主题: Re: [flutter/flutter] The desktop application could not fetch the VPN connection (#47680)

[External Email]

If you only added it to that file, your release builds will have the same problem. Prior should follow the instructions linked from the other issue, which provide more complete information.

―
