### ISSUE TITLE
Input is voiced on a textfield with obscureText set to true when using VoiceOver

### ISSUE THREAD

**Issue by natalieeeflores** [flutter/flutter#97034] opened 2022-01-21 22:40 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Start typing in textfield 

**Expected results:** Input is not voiced

**Actual results:** VoiceOver voices the input

https://user-images.githubusercontent.com/19349394/150610304-af691867-dfe7-4f86-88d9-9ec002734ef5.MP4

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Padding(
          padding: EdgeInsets.all(20),
          child: TextField(
            obscureText: true,
            decoration: InputDecoration(
              hintText: 'Type password here',
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2022-01-24 06:44
@natalieeeflores 
I believe this particular use case doesn't seem to be implemented yet. Please see [this](https://github.com/flutter/flutter/issues/14543) open issue for tracking under `What remains to be done:` section.
So I am going ahead and closing this as a duplicate of above linked issue. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-01-24 06:44 UTC
Labels: in triage
