### ISSUE TITLE
The Flutter project works normally, but many places in the Android directory are marked red

### ISSUE THREAD

**Issue by gionchat** [flutter/flutter#89964] opened 2021-09-13 05:58 UTC
The Flutter project works normally, but many places in the Android directory are marked red
![image](https://user-images.githubusercontent.com/58280808/133031071-c16a67fe-7449-4fec-99b1-3fd1b4f1b5e4.png)

**Comment by Anirban-Chand** [comment] 2021-09-13 06:46
This is a normal issue in Android Studio for years. Don't know why they just don't fix it. Actually, these small errors are caused by deprecations. For example - in some places, if you add **'new'** keyword it'll show an error, while the implementation is not wrong.

**Comment by darshankawar** [comment] 2021-09-13 11:42
@gionchat 
Android Studio works best when you open the Android module as a top-level project. You can easily do so by selecting the Android module then using the menu Tools > Flutter > Open Android module in Android Studio. After the new window opens a Gradle sync will be performed and those symbols will be resolved.

Also, this doesn't seem to be a framework issue, but an issue in intellij's flutter plugin. You may track this issue here for your reference: flutter/flutter-intellij#2243

Closing from here.

**Closed by darshankawar** 2021-09-13 11:42 UTC
Labels: in triage
