### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by zcoderr** [flutter/flutter#126643] opened 2023-05-12 08:05 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1.flutter upgrade
2. flutter doctor

## Logs
FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:129:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:428:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:427:12)
#5      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:916:19)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1518:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-arm64, locale
    en-CN)
    [32m•[39m Flutter version 3.10.0 on channel stable at /Users/zachary/dev/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 84a1e904f4 (3 days ago), 2023-05-09 07:41:44 -0700
    [32m•[39m Engine revision d44b5a94c9
    [32m•[39m Dart version 3.0.0
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
    [32m•[39m Android SDK at /Users/zachary/Library/Android/Sdk
    [32m•[39m Platform android-33, build-tools 33.0.0-rc1
    [32m•[39m ANDROID_HOME = /Users/zachary/Library/Android/Sdk
    [32m•[39m ANDROID_SDK_ROOT = /Users/Zachary/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.1)
    [32m•[39m Xcode a

**Comment by danagbemava-nc** [comment] 2023-05-12 09:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65242

**Closed by danagbemava-nc** 2023-05-12 09:58 UTC
Labels: in triage
