### ISSUE TITLE
dependent dylib '@rpath/Flutter.framework/Flutter' not found

### ISSUE THREAD

**Issue by athornz** [flutter/flutter#45306] opened 2019-11-21 00:52 UTC
I've been running into this error daily when launching my application on an iPad.

## Steps to Reproduce

1. Launch application on iPad
2. App crashes on startup

Running some combination of flutter clean, deleting frameworks, pub get, pod install will sometimes fix the issue.

When running the app from xcode directly, it just works.

**Target Platform:** iOS 13.1.3 / xcode 11.2.1
**Target OS version/browser:** iOS 13.1.3 / xcode 11.2.1
**Devices:** iPad

## Logs

```
Hardware Model:      iPad7,6
Process:             Runner [869]
Path:                /private/var/containers/Bundle/Application//Runner.app/Runner
Identifier:           - 
Version:             1 (0.0.1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:            - 


Date/Time:           2019-11-21 13:46:58.2497 +1300
Launch Time:         2019-11-21 13:46:58.0663 +1300
OS Version:          iPhone OS 13.1.3 (17A878)
Release Type:        User
Baseband Version:    7.00.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib '@rpath/Flutter.framework/Flutter' not found for '/private/var/containers/Bundle/Application/./Runner.app/Runner'. vm_copy() failure
Highlighted by Thread:  0

Backtrace not available
```

```
```

```
[✓] Flutter (Channel master, v1.12.5-pre.56, on Mac OS X 10.15.1 19B88, locale en-AU)
    • Flutter version 1.12.5-pre.56 at /Users/athor/dev/flutter
    • Framework revision 106b8eb9c0 (2 hours ago), 2019-11-20 14:45:32 -0800
    • Engine revision 176f563296
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/athor/dev/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/athor/dev/android-sdk
    • Java binary at: /Users/athor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/191.5977832/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio 3.2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/athor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/191.5977832/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Users/athor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.5994180/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio
    • Android Studio at /Users/athor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6008643/Android Studio 4.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Users/athor/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (4 available)
    • Josh’s iPad • 700def2f65bd06c02d157f0ae59689a32695da10 • ios            • iOS 13.1.3
    • macOS       • macOS                                    • darwin-x64     • Mac OS X 10.15.1 19B88
    • Chrome      • chrome                                   • web-javascript • Google Chrome 78.0.3904.97
    • Web Server  • web-server                               • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

**Comment by iapicca** [comment] 2019-11-21 08:37
Hi @athornz 
could you please provide your `flutter run --verbose` (reproducing the crash)?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jmagman** [comment] 2019-11-21 23:44
Can you paste your Podfile?

**Comment by athornz** [comment] 2019-11-22 00:32
@jmagman 

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

```

**Comment by peasfarmer** [comment] 2019-12-27 16:11
i have the same problem:

Steps to Reproduce:
1. uninstall the app
2. click "Debug" in android studio,app run ok
3. click "Stop"  in android studio
4. click "Debug" in android studio again, the app run to Launch screen, then crash
5. run "flutter run --release",app run ok
6. run "flutter run --debug",app crash again
7. i try run "flutter clean", but it  not work

i guess only debug version have this problem.


```
Incident Identifier: E704AFD3-BDAE-4D13-9EE0-5A20F0981C05
CrashReporter Key:   a56e37e303dd560682eda4f52ff5524c4d8e5f5a
Hardware Model:      iPhone9,1
Process:             Runner [370]
Path:                /private/var/containers/Bundle/Application/E16D8B25-06C7-4B50-A3B3-321CC2043BA2/Runner.app/Runner
Identifier:          com.xxxx
Version:             1 (2.2.2)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.xxxx [598]


Date/Time:           2019-12-27 23:30:42.6486 +0800
Launch Time:         2019-12-27 23:30:42.4649 +0800
OS Version:          iPhone OS 13.1.2 (17A860)
Release Type:        User
Baseband Version:    7.00.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib '@rpath/Flutter.framework/Flutter' not found for '/private/var/containers/Bundle/Application/E16D8B25-06C7-4B50-A3B3-321CC2043BA2/Runner.app/Runner'. vm_copy() failure
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016d349fe0   x3: 0x0000000000000097
    x4: 0x000000016d349be0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x72656e6e75522f32  x11: 0x6e75522f7070612e
   x12: 0x6e75522f7070612e  x13: 0x6d76202e2772656e  x14: 0x20292879706f635f  x15: 0x006572756c696166
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016d349be0  x21: 0x0000000000000097  x22: 0x000000016d349fe0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x0000000102fa8000  x26: 0x0000000000000001  x27: 0x0000000102fa8000
   x28: 0x0000000000000000   fp: 0x000000016d349bb0   lr: 0x0000000102f9230c
    sp: 0x000000016d349b70   pc: 0x0000000102f8b4f0 cpsr: 0x00000000
   esr: 0x00000000  Address size fault

Binary images description not available
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)
```

run "flutter run --verbose" log in run.log file
[run.log](https://github.com/flutter/flutter/files/4005734/run.log)

**Comment by santervo** [comment] 2020-01-22 07:44
Experiencing the same. Running via xcode works, but `flutter run` crashes the app with similar crash report as in original comment. I've rebuilt the podfile also. It works sometimes if I delete app first.

**Comment by santervo** [comment] 2020-01-22 07:49
`flutter run --verbose` output ends with:

> [  +27 ms] (lldb)     run
[ +196 ms] success
[        ] (lldb)     safequit
[ +109 ms] Process 94973 detached
[  +48 ms] Application launched on the device. Waiting for observatory port.
[   +3 ms] Checking for advertised Dart observatories...
[+5017 ms] No pointer records found.
[   +2 ms] mDNS lookup failed, attempting fallback to reading device log.
[        ] Waiting for observatory port.

**Comment by Lorkios** [comment] 2020-01-24 13:21
Actually experiencing exactly the same issue. A friend told me to change flutter version from the master to a dev branch. Going to try out.

**Comment by tolsac** [comment] 2020-01-24 15:37
Same problem, anyone found a solution ?

**Comment by jmagman** [comment] 2020-02-11 22:12
@louislefebvre You are hitting https://github.com/flutter/flutter/issues/49504.

**Comment by jmagman** [comment] 2020-02-11 22:13
@tolsac You may also be hitting https://github.com/flutter/flutter/issues/49504 but I can't tell without more information.  Please file a new issue or check that one out to see if it matches your OS and provisioning profile characteristics.

**Comment by DanialNikbin** [comment] 2020-02-23 17:55
I'm facing the same Issue. It's been a long time since I'm unable to run my flutter apps on a real iOS device. Any update or solution?

This is my xcode output.

`dyld: Library not loaded: @rpath/Flutter.framework/Flutter
  Referenced from: /private/var/containers/Bundle/Application/8FC96742-55CE-440A-848F-EE28EF4BEE1D/Runner.app/Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/8FC96742-55CE-440A-848F-EE28EF4BEE1D/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/8FC96742-55CE-440A-848F-EE28EF4BEE1D/Runner.app/Frameworks/Flutter.framework/Flutter'
`

**Comment by jmagman** [comment] 2020-02-23 18:55
@DanialNikbin same to you:
> You may also be hitting #49504 but I can't tell without more information. Please file a new issue or check that one out to see if it matches your OS and provisioning profile characteristics.

**Comment by jmagman** [comment] 2020-03-06 21:56
Actually @athornz maybe you are also hitting https://github.com/flutter/flutter/issues/49504#issuecomment-592767041.  For some reason I just assumed you wouldn't be using a Personal Team provisioning profile based on other issues you've filed, but that may not be true.

Are you seeing this on your iPad on iOS 13.4 beta 3 or later?  If so, you have have the unfortunate distinction of being the first one to have created an issue for it.

**Comment by jmagman** [comment] 2020-03-27 20:01
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-03-27 20:01 UTC
Labels: e: device-specific, severe: crash, tool, waiting for customer response, ⌺‬ platform-ios
