### ISSUE TITLE
release_full_compile_millis flutter_gallery_win__compile regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#67533] opened 2020-10-07 16:19 UTC
https://flutter-flutter-perf.skia.org/e/?begin=1601950322&end=1602017523&keys=X7ebbd68d9692047b75b46186abf9b94a&num_commits=50&request_type=1&xbaroffset=21815

First seen at https://github.com/flutter/flutter/pull/67029, although I don't see why that would be the case.

/cc @stuartmorgan

**Comment by stuartmorgan** [comment] 2020-10-07 16:45
flutter_gallery_win__compile is compiling for Android; my PR only changes code used in compiling for Windows and Linux.

Given how noisy that graph is, it could have started earlier (e.g., the spike at the last engine roll) or later.

**Comment by kf6gpe** [comment] 2020-10-07 16:46
Thanks, Stuart, that makes sense and matches what I thought.

@liyuqian any thoughts here? Dropping `tool`, adding `engine` in case it's the engine roll.

**Comment by liyuqian** [comment] 2020-10-07 18:43
Yes, it could also be caused by the NNBD commit https://github.com/flutter/flutter/commit/e826442ef4215d6d32ec668ce798c6b3f1d72936 (one commit after #67209). CC @jonahwilliams 

Considering the noise, we need someone to run this test multiple times locally to bisect and identify exactly which framework commit caused this regression.

**Comment by chinmaygarde** [comment] 2020-10-12 17:35
This looks bimodal and noisy. A run after the "regression" shows a value that is back to the original value. I am reducing the priority of this issue.

**Comment by zanderso** [comment] 2020-10-12 17:39
@jonahwilliams reverted his change here https://github.com/flutter/flutter/pull/67433 and the previous perf behavior was not restored.

**Comment by liyuqian** [comment] 2020-10-12 18:49
I think we can close this issue now as [the metric][1] has dropped significantly to the normal level after these 3 commits:
- https://github.com/flutter/flutter/commit/f1c1d944e3173cf2bcd43f27904b8dd137957249
- https://github.com/flutter/flutter/commit/ab9373bf48e7eddaa1701b2bb56b259a1cc25a43
- https://github.com/flutter/flutter/commit/13bf341584aa191ca940259a817cbddfa5a44e4d

[1]: https://flutter-flutter-perf.skia.org/e/?begin=1601598722&end=1602494738&keys=X7ebbd68d9692047b75b46186abf9b94a&requestType=0&xbaroffset=21815

**Closed by liyuqian** 2020-10-12 18:49 UTC
Labels: P4, engine, passed first triage, perf: speed, severe: performance, severe: regression, team, team: benchmark
