### ISSUE TITLE
Clarify the names animation and forwardAnimation

### ISSUE THREAD

**Issue by xster** [flutter/flutter#9132] opened 2017-03-31 19:58 UTC
Motion to rename the parameter names 'animation' and 'forwardAnimation' to 
- 'incomingAnimation' and 'outgoingAnimation' or
- 'entranceAnimation' and 'exitAnimation' or
something that points out their analogous nature.

And rename the various underlaying field variables and properties. 

cc @Hixie

**Comment by Hixie** [comment] 2017-03-31 20:06
The problem is that the animations are used like this:

 * `Route A <--animation1--> Route B <--animation2--> Route C`

...which means that `animation1` can be both "incoming" or "entrance" (when going from A to B) and "outgoing" or "exit" (when going from B to A), as can `animation2` (when going from B to C and C to B respectively).

Further complicating matters, the "animation" for B is the "forwardAnimation" for A, and the "forwardAnimation" for B is the "animation" for C.

**Comment by Hixie** [comment] 2017-03-31 20:07
(moving to M2 since if we don't change it in the coming week or so we probably can't change it ever)

**Comment by HansMuller** [comment] 2017-03-31 20:11
I think renaming these parameters would make the API a little easier to understand. 

I also think we could improve the doc for `ModalRoute.buildTransitions()` a little. Currently it begins with: `Override this method to wrap the route in a number of transition widgets.` It might be a little clearer to say that the method enables defining how the route transitions in and out. 

If the example for the buildTransitions() method demo'd transitions that were linked to both the incoming and outgoing animations, that would help too.

**Comment by HansMuller** [comment] 2017-03-31 20:13
@hixie I see that I was more confused than I thought. I still hope that we can clarify that docs/names somehow.

**Comment by Hixie** [comment] 2017-03-31 20:16
Yeah I totally agree that the current names suck. I tried for a while to come up with better names and failed. :-( I'm open to suggestions, but they have to be at least as accurate as today's dubious names. :-)

**Comment by xster** [comment] 2017-03-31 20:16
- There's actually 2 independent instances of things that can be at where you drew the 'animation1' right? The 'forwardAnimation' for route A and the 'animation' for route B are 2 separate orthogonal things that are happening simultaneously right? 
- The situation you described is indeed confusing but mainly because you changed perspective right? I think the clearer way to visualize it is when going from C to B for instance, we're reversing the entranceAnimation of C and reversing the exitAnimation of B. But we're still calling them entranceAnimation and exitAnimation from the perspective of the advancing animation.

**Comment by xster** [comment] 2017-03-31 20:19
In other words, when taking the absolute numerical values of those animations into account, the words entrance/incoming/exit/outgoing can make a bit more sense. If we go from C to B, the fact that we're still running the 'entranceAnimation' of C is a bit easier to understand when we also think about the fact that that animation is running from 1.0 to 0.0.

**Comment by Hixie** [comment] 2017-03-31 20:19
IIRC, the `animation` for B and the `forwardAnimation` for A are driven by the same underlying `AnimationController`. (They might overlay different curves on that underlying animation.) They are fundamentally the "same" animation.

**Comment by Hixie** [comment] 2017-03-31 20:21
I don't really see why the animation from B to C is any more of an "exit" animation for B than the animation from A to B. Both animations are used when B "exits", it just depends if it exits "forward" or "backward". In fact strictly speaking, it doesn't exit at all when going from B to C; it's still there in the background and you can typically return to it by reversing the animation from B to C.

**Comment by xster** [comment] 2017-03-31 20:27
re https://github.com/flutter/flutter/issues/9132#issuecomment-290819486
I think that's ok though. Having the same instance of a thing under the hood being called 2 different things from 2 different perspectives is ok. Having that same input produce 2 different outputs is ok too. 

> I don't really see why the animation from B to C is any more of an "exit" animation for B than the animation from A to B.

You meant 'for B than the animation from B to A' right?

So from B to C, you're running B's exitAnimation from 0->1. That's easier to visualize.
From B to A, you're running B's entranceAnimation from 1->0. Thus, you're reversing B's entranceAnimation. Backing out of an entrance is easy to visualize too I think and describes what it's doing.

**Comment by Hixie** [comment] 2017-03-31 20:32
In fact that's why we just call the A->B animation "animation" from B's perspective, because it's usually the only one you deal with. It's very rare in practice to actually use "forwardAnimation".

**Comment by xster** [comment] 2017-03-31 20:37
What about using some name that denoted the you're-going-above-someone-else and the you're-going-below-someone-else nature of it? That doesn't change depending on the directionality of the perspective.

**Comment by xster** [comment] 2017-03-31 20:43
Say above/belowAnimation or covering/becomingCoveredAnimation?

**Comment by Hixie** [comment] 2017-03-31 21:58
Seems reasonable if we can find good words... It's hard though, e.g. is "aboveAnimation" the animation for when you are above someone, or when someone is coming above you?

There's a huge asymmetry in how much these are used. For example, we literally only use forwardAnimation once in our repo, and it's in a test. We use the other animation a lot more. This argues for the current asymmetry in the names, where the commonly used argument is just "animation" and the rarely used one has a longer name.

**Comment by xster** [comment] 2017-04-01 02:10
I think we shouldn't use how frequently we used this to implement material to inform assumptions on how our users would use it or to guide how easy to make each part of the API understandable. 

All these terms from properties and parameters are coming from superclasses of self. It would be a leap to derive that 'above' is referring to a non-self entity being above.

Trying to think of transferable skeuomorphic terms from relatable industries. foreground/backgroundAnimations could work. It's kinda like we're shooting a movie.

**Comment by Hixie** [comment] 2017-04-01 03:14
> I think we shouldn't use how frequently we used this to implement material to inform assumptions on how our users would use it or to guide how easy to make each part of the API understandable.

I think it's probably a reasonable proxy for how common the feature is in general (at least, it's the only real proxy we have today). We should definitely make common things shorter and easier and rarer things longer. (The short names are a scarce namespace, the common things should be short for convenience.)

> It would be a leap to derive that 'above' is referring to a non-self entity being above.

I think it would be eminently reasonable to assume that the "aboveAnimation" is above the "belowAnimation", but if I understand what you're describing, it would be the other way around.

> foreground/backgroundAnimations could work. It's kinda like we're shooting a movie.

I like the idea of using terms from film-making. I'm not sure about those specific terms... when you're going back from the "forward" animation, you're in the foreground, in that if the user taps the screen that's what gets tapped.

**Comment by abarth** [comment] 2017-04-02 06:44
Word clouds:

 * primary, enter, exit, intro, outro
 * nextRoute, pause, resume, backgrounded, foregrounded

Name suggestions:

 * animation / nextRouteAnimation
 * entranceAnimation / suspendAnimation

API suggestion:

Should we have more methods instead of one all-sing, all-dance method?

```dart
Widget buildEntranceTransition(Animation<double> animation, Widget child);
Widget buildExitTransition(Animation<double> animation, Widget child);
Widget buildSuspendTransition(Animation <double> animation, Widget child);
Widget buildResumeTransition(Animation <double> animation, Widget child);
```

or

```dart
Widget buildTransition(Animation<double> animation, Widget child);
Widget buildSuspendResumeTransition(Animation <double> animation, Widget child);
```

**Comment by Hixie** [comment] 2017-04-02 06:53
Having all four won't work because you can reverse the animation mid-course, otherwise that would bevery attractive. Even having two is dubious because you can actually have both animations simultaneously going on and it's not clear which one you want to build inside the other. I can imagine wanting it both ways. That's why it's one builder today.

animation / nextRouteAnimation is what I was going for with animation / forwardAnimation. I'm fine with that one if y'all prefer it to forwardAnimation.

animation / suspendResumeAnimation could work, I guess, though it seems weird to have those names versus something like entranceExitAnimation / suspendResumeAnimation or previousRouteAnimation / nextRouteAnimation, both of which seem excessively verbose.

**Comment by abarth** [comment] 2017-04-02 07:13
> Having all four won't work because you can reverse the animation mid-course, otherwise that would very attractive.

The way we handle this for CurvedAnimation is that we only flip over to the reverse curve if you actually make it to the end of the forward curve.  In this scenario, that would mean that if you when back in the middle of the entrance animation, we'd just play the entrance animation backwards but if you got the end of the entrance animation before going back, then we'd play the exit animation.

**Comment by abarth** [comment] 2017-04-02 07:14
(Obviously we could supply a default implementation of buildExitTransition that just called through to buildEntranceTransition with the animation reversed or whatever.)

**Comment by Hixie** [comment] 2017-04-02 07:19
People get really jumpy when the "out" animation isn't exactly the same as the "in" animation in reverse, that's what started this whole thing. I think we'd be better off not making that easier. :-)

**Comment by abarth** [comment] 2017-04-02 07:23
Ah, ok.  I guess that makes sense.  I got too wrapped up in the filmmaking analogy.  :)

**Comment by HansMuller** [comment] 2017-04-03 15:37
Could we remove forwardTransition? If it's "very rare in practice to use the forwardAnimation" and see https://github.com/flutter/flutter/issues/9132#issuecomment-290841280, could we live without it? I have to admit that I'm still confused about what it's for...

**Comment by xster** [comment] 2017-04-03 18:09
I'm using it for the cupertino page animation :S

Let's talk in person.

**Comment by abarth** [comment] 2017-04-03 18:26
You need it for some effects.  For example, if you want to slide the old route over to the side a bit as the new route comes in.

**Comment by HansMuller** [comment] 2017-04-03 18:46
So you use the "forwardAnimation" if you want to change how your route exits or leaves or disappears or vanishes when it's being replaced or dimsissed or removed or ... :-)

I suppose we need to beef up https://docs.flutter.io/flutter/widgets/ModalRoute/buildTransitions.html so that this use case can be understood.

**Comment by xster** [comment] 2017-04-03 19:04
Yes, we'll violently add more explanations to the dartdoc either way. It's only used when the route is being replaced by another route and and in reverse when it's un-replaced. The 'primary' animation is used when it was already the top of the stack and being dismissed.

**Closed** 2017-04-05 00:18 UTC
Labels: dev: docs - api, prod: animation, prod: API stability
