### ISSUE TITLE
flutter pub get  - fails with HandshakeException CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jci-cfoxr** [flutter/flutter#109886] opened 2022-08-19 22:02 UTC
I'm getting this error with this setup:

MacOS 11.6.8

flutter --version
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (5 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

Flutter doctor won't run due to this error as well.

I was originally trying to use flutter 2.10.5 and had the same error.

`[+30002 ms] IO  : Retry #4 for GET https://pub.dartlang.org/api/packages/js...
[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/js
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: macos
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: 9479F63B-94E7-46F2-B6FA-00FFAE0A9350
[        ]     | X-Pub-Environment: flutter_cli:get
[        ]     | user-agent: Dart pub 2.17.6
[ +114 ms] IO  : HTTP error:
[        ]     | HandshakeException: Handshake error in client (OS Error: 
[        ]     | 	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))
[        ]     | 
[        ]     | dart:_http                                             _HttpClient.openUrl
[        ]     | package:http/src/io_client.dart 35:38                  IOClient.send
[        ]     | package:pub/src/http.dart 68:43                        _PubHttpClient.send
[        ]     | package:http/retry.dart 109:33                         RetryClient.send
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                             _asyncThenWrapperHelper
[        ]     | package:pub/src/http.dart 175:39                       _ThrowingClient.send
[        ]     | package:pub/src/http.dart 379:31                       _ThrottleClient.send
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                             _asyncThenWrapperHelper
[        ]     | package:pub/src/authentication/client.dart 52:37       _AuthenticatedClient.send
[        ]     | package:http/src/base_client.dart 93:38                BaseClient._sendUnstreamed
[        ]     | package:http/src/base_client.dart 27:7                 BaseClient.get
[        ]     | package:http/src/base_client.dart 51:28                BaseClient.read
[        ]     | package:pub/src/source/hosted.dart 358:28              HostedSource._fetchVersionsNoPrefetching.<fn>
[        ]     | package:pub/src/authentication/client.dart 133:20      withAuthenticatedClient
[        ]     | package:pub/src/source/hosted.dart 355:24              HostedSource._fetchVersionsNoPrefetching
[        ]     | package:pub/src/source/hosted.dart 417:26              HostedSource._fetchVersions
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                             _CustomZone.runUnary
[        ]     | package:pub/src/rate_limited_scheduler.dart 85:27      RateLimitedScheduler._processNextTask.runJob
[        ]     | package:pub/src/rate_limited_scheduler.dart 83:21      RateLimitedScheduler._processNextTask.runJob
[        ]     | package:pub/src/rate_limited_scheduler.dart 88:24      RateLimitedScheduler._processNextTask
[        ]     | package:pool/pool.dart 127:28                          Pool.withResource
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                             _asyncThenWrapperHelper
[        ]     | package:pub/src/rate_limited_scheduler.dart 134:37     RateLimitedScheduler.schedule.<fn>
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                             scheduleMicrotask
[        ]     | package:pub/src/rate_limited_scheduler.dart 134:7      RateLimitedScheduler.schedule
[        ]     | package:pub/src/source/hosted.dart 629:41              HostedSource.doGetVersions
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                             _asyncThenWrapperHelper
[        ]     | package:pub/src/system_cache.dart 186:37               SystemCache.getVersions
[        ]     | package:pub/src/solver/version_solver.dart 449:34      VersionSolver._getAvailableVersions
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                             _asyncErrorWrapperHelper
[        ]     | package:pub/src/solver/version_solver.dart 423:13      VersionSolver._result
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                             _asyncThenWrapperHelper
[        ]     | package:pub/src/solver/version_solver.dart 100:22      VersionSolver.solve.<fn>
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                             _asyncThenWrapperHelper
[        ]     | package:pub/src/solver/version_solver.dart             VersionSolver.solve.<fn>
[        ]     | dart:async                                             runZoned
[        ]     | package:pub/src/source/hosted.dart 954:20              HostedSource.withPrefetching.<fn>
[        ]     | package:pub/src/source/hosted.dart 953:47              HostedSource.withPrefetching.<fn>
[        ]     | package:pub/src/rate_limited_scheduler.dart 110:28     RateLimitedScheduler.withPrescheduling
[        ]     | package:pub/src/source/hosted.dart 953:29              HostedSource.withPrefetching
[        ]     | package:pub/src/solver/version_solver.dart 93:40       VersionSolver.solve
[        ]     | package:pub/src/solver.dart 44:5                       resolveVersions
[        ]     | package:pub/src/entrypoint.dart 282:16                 Entrypoint.acquireDependencies.<fn>
[        ]     | package:pub/src/entrypoint.dart 280:68                 Entrypoint.acquireDependencies.<fn>
[        ]     | package:pub/src/log.dart 428:18                        progress
[        ]     | package:pub/src/entrypoint.dart 280:26                 Entrypoint.acquireDependencies
[        ]     | package:pub/src/command/get.dart 52:22                 GetCommand.runProtected
[        ]     | package:pub/src/command.dart 183:45                    PubCommand.run.<fn>
[        ]     | package:pub/src/command.dart 183:33                    PubCommand.run.<fn>
[        ]     | dart:async                                             new Future.sync
[        ]     | package:pub/src/utils.dart 109:12                      captureErrors.wrappedCallback
[        ]     | package:stack_trace                                    Chain.capture
[        ]     | package:pub/src/utils.dart 122:11                      captureErrors
[        ]     | package:pub/src/command.dart 183:13                    PubCommand.run
[        ]     | package:args/command_runner.dart 209:27                CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 174:24             PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 159:20             PubCommandRunner.run
[        ]     | package:dartdev/dartdev.dart 45:56                     runDartdev
[        ]     | /opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
`

**Comment by exaby73** [comment] 2022-08-22 07:26
Duplicate of https://github.com/flutter/flutter/issues/100762. This is fixed in master and will be included in a future stable release.

**Closed by exaby73** 2022-08-22 07:26 UTC
Labels: in triage
