### ISSUE TITLE
Flutter Flame: The GameRenderBox class does not implement "computeDryLayout".

### ISSUE THREAD

**Issue by zmunk** [flutter/flutter#74036] opened 2021-01-15 12:04 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:  

*pubspec.yaml*
```yaml
dependencies:
  ...
  flame: ^0.28.0
```
*main.dart*
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flame/util.dart';
import 'package:flame/game.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  Util flameUtil = Util();
  await flameUtil.fullScreen();
  await flameUtil.setOrientation(DeviceOrientation.portraitUp);
  BoxGame boxGame = BoxGame();
  runApp(MaterialApp(
    home: Scaffold(
      body: boxGame.widget,
    )
  ));
}

class BoxGame extends Game {
  void render(Canvas canvas) {}
  void update(double t) {}
}

```
3. run `flutter clean` and `flutter pub get` 
make sure you're on the master channel (run `flutter channel master`)
if not enabled, enable linux desktop with `flutter config --enable-linux-desktop`
run app `flutter run -d linux`
**Results:** 
I was following [this tutorial](https://jap.alekhin.io/create-mobile-game-flutter-flame-beginner-tutorial)
The app should run without a problem.
But I get the following error:
```
The following assertion was thrown during performResize():
The GameRenderBox class does not implement "computeDryLayout".
```

<details>
  <summary>Logs</summary>

```
[  +99 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +47 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[   +1 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git tag --points-at d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[  +18 ms] Exit code 0 from: git tag --points-at d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[   +3 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[  +39 ms] Exit code 0 from: git describe --match *.*.* --long --tags d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[        ] 1.26.0-1.0.pre-275-gd9044a8a61
[  +57 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/ibrahim/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] executing: /home/ibrahim/Android/Sdk/platform-tools/adb devices -l
[  +30 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +90 ms] executing: /home/ibrahim/Android/Sdk/platform-tools/adb devices -l
[  +28 ms] Skipping pub get: version match.
[  +34 ms] Found plugin audioplayers at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.15.1/
[  +51 ms] Found plugin path_provider at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[   +3 ms] Found plugin path_provider_linux at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +3 ms] Found plugin path_provider_macos at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[   +5 ms] Found plugin path_provider_windows at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +70 ms] Found plugin integration_test at /home/ibrahim/snap/flutter/common/flutter/packages/integration_test/
[ +131 ms] Found plugin audioplayers at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.15.1/
[  +33 ms] Found plugin path_provider at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[   +4 ms] Found plugin path_provider_linux at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +2 ms] Found plugin path_provider_macos at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[   +3 ms] Found plugin path_provider_windows at /home/ibrahim/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +52 ms] Found plugin integration_test at /home/ibrahim/snap/flutter/common/flutter/packages/integration_test/
[   +7 ms] Generating /home/ibrahim/Documents/Flutter/Flame/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +126 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[   +7 ms] complete
[   +9 ms] Launching lib/main.dart on Linux in debug mode...
[   +8 ms] /home/ibrahim/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/ibrahim/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/ibrahim/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.HKJZRL/flutter_tool.VSYNMQ/app.dill --packages /home/ibrahim/Documents/Flutter/Flame/bug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[  +30 ms] Building Linux application...
[  +48 ms] <- compile package:bug/main.dart
[   +4 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/ibrahim/Documents/Flutter/Flame/bug/linux
[  +21 ms] List of devices attached
[   +4 ms] List of devices attached
[  +94 ms] -- Configuring done
[  +13 ms] -- Generating done
[   +1 ms] -- Build files have been written to: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug
[   +6 ms] executing: ninja -C build/linux/debug install
[  +14 ms] ninja: Entering directory `build/linux/debug'
[+7896 ms] [1/5] Generating /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/ibrahim/Documents/Flutter/Flame/bug/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +20 ms] [ +163 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] [  +72 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] [        ] d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[   +9 ms] [   +1 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git tag --points-at d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[   +2 ms] [  +27 ms] Exit code 0 from: git tag --points-at d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[   +9 ms] [   +3 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[        ] [  +58 ms] Exit code 0 from: git describe --match *.*.* --long --tags d9044a8a61e4d7d0afbd4fe8bad6d40762c289dd
[        ] [        ] 1.26.0-1.0.pre-275-gd9044a8a61
[   +1 ms] [ +125 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/ibrahim/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +92 ms] executing: [/home/ibrahim/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [ +216 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] [   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +174 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [ +142 ms] Initializing file store
[        ] [  +18 ms] Done initializing file store
[        ] [  +79 ms] Skipping target: gen_localizations
[        ] [+3755 ms] Skipping target: unpack_linux
[        ] [ +762 ms] Skipping target: kernel_snapshot
[        ] [ +679 ms] Skipping target: debug_bundle_linux_assets
[        ] [   +1 ms] Persisting file store
[        ] [  +19 ms] Done persisting file store
[        ] [  +13 ms] build succeeded.
[        ] [  +14 ms] "flutter assemble" took 5,755ms.
[        ] [ +261 ms] ensureAnalyticsSent: 255ms
[        ] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +851 ms] [2/5] Building CXX object CMakeFiles/bug.dir/flutter/generated_plugin_registrant.cc.o
[ +100 ms] [3/5] Building CXX object CMakeFiles/bug.dir/my_application.cc.o
[ +365 ms] [4/5] Linking CXX executable intermediates_do_not_run/bug
[        ] [4/5] Install the project...
[  +31 ms] -- Install configuration: "Debug"
[  +62 ms] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/bug
[   +1 ms] -- Set runtime path of "/home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/bug" to "$ORIGIN/lib"
[   +1 ms] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/icudtl.dat
[   +2 ms] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[ +308 ms] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets
[   +1 ms] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[ +106 ms] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[   +1 ms] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/NOTICES
[   +2 ms] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/ibrahim/Documents/Flutter/Flame/bug/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[  +34 ms] Building Linux application... (completed in 10.1s)
[ +377 ms] Observatory URL on device: http://127.0.0.1:33815/cWeJZqnb3eY=/
[+6694 ms] Caching compiled dill
[ +285 ms] Connecting to service protocol: http://127.0.0.1:33815/cWeJZqnb3eY=/
[   +4 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:33815/cWeJZqnb3eY=/.
[ +241 ms] DDS is listening at http://127.0.0.1:36229/WDvwE_VCSh4=/.
[ +107 ms] Successfully connected to service protocol: http://127.0.0.1:33815/cWeJZqnb3eY=/
[  +22 ms] DevFS: Creating new filesystem on the device (null)
[  +21 ms] DevFS: Created new filesystem on the device (file:///tmp/bugNOAEQU/bug/)
[   +3 ms] Updating assets
[ +171 ms] Syncing files to device Linux...
[   +4 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +6 ms] <- recompile package:bug/main.dart 2b2f8eec-3f8e-489e-a476-2a3c98e5f74e
[        ] <- 2b2f8eec-3f8e-489e-a476-2a3c98e5f74e
[ +486 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Linux... (completed in 498ms)
[   +1 ms] Synced 0.0MB.
[   +1 ms] <- accept
[   +9 ms] Connected to _flutterView/0x14215c0.
[   +2 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:36229/WDvwE_VCSh4=/
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+33769 ms] Application finished.

```

*Output of flutter analyze*
```
Analyzing bug...

   info • Unused import: 'package:bug/main.dart' • test/widget_test.dart:11:8 • unused_import
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function

2 issues found. (ran in 18.1s)
```

*Output of flutter doctor*
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.275 at /home/ibrahim/snap/flutter/common/flutter
    • Framework revision d9044a8a61 (6 days ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/ibrahim/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 86.0.4240.183

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2021-01-15 12:20
Hi @zmunk 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/flame-engine/flame/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-15 12:20 UTC

**Comment by zmunk** [comment] 2021-01-15 12:23
Submitted in the flame repo: https://github.com/flame-engine/flame/issues/629
