### ISSUE TITLE
[web] Weird ScrollBar indicator behavior

### ISSUE THREAD

**Issue by harlanx** [flutter/flutter#86548] opened 2021-07-16 12:19 UTC
## Steps to Reproduce

1. Create flutter app for web
2. Create a ListView.separated() with vertical scrollDirection
3. Return a small height widget in separatorBuilder and return large height widget in the itemBuilder

**Expected results:** 
Smooth scrollbar indicator behavior.
**Actual results:** 
Glitchy scrollbar indicator behavior. (Same with profile and release mode)

## Bug Preview

https://user-images.githubusercontent.com/78299538/125945367-dbc291eb-0604-4204-9db8-67271e53a428.mp4

<details><summary>Reproducible Example</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Scrollbar Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.separated(
        shrinkWrap: true,
        scrollDirection: Axis.vertical,
        separatorBuilder: (_, __) => Container(
          height: 20,
          color: Colors.blue,
        ),
        itemCount: 10,
        itemBuilder: (_, index) {
          return Container(
            height: 250,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text('Horizontal Group # $index'),
                Flexible(
                  child: ListView(
                    shrinkWrap: true,
                    scrollDirection: Axis.horizontal,
                    children: List.generate(
                      10,
                      (horizIndex) => Placeholder(
                        fallbackWidth: 200,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
```

</p>
</details>

<details>
  <summary>Logs</summary>

PS D:\Documents\Projects\Dart\scrollbar_behavior_test> flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-PH)
    • Flutter version 2.2.3 at C:\SDKs\flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\SDKs\Android
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\harit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 1 category.

</details>

**Comment by TahaTesser** [comment] 2021-07-16 13:23
Hi @harlanx 
This has been filed before https://github.com/flutter/flutter/issues/25652 https://github.com/flutter/flutter/issues/51470
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/25652
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-16 13:23 UTC
Labels: in triage
