### ISSUE TITLE
App freezes on device when using localizationsDelegates and supportedLocales

### ISSUE THREAD

**Issue by ben55j** [flutter/flutter#84184] opened 2021-06-08 10:44 UTC
Hello,

I am trying to use the datePicker confirgued with the Locale("fr", "FR"). Bellow how this feature has been implemented:

**Here is my call to action:** 

```dart
onTap: () {
                showDatePicker(
                  locale: const Locale("fr", "FR"),
                  context: context,
                  initialDate: DateTime.now(),
                  firstDate: DateTime.now(),
                  lastDate: DateTime.now().add(Duration(days: 365)),
                ).then((value) {
                  if (value != null) {
                    showTimePicker(
                      context: context,
                      initialTime: TimeOfDay.now(),
                    );
                  }
                });
              },
```

**on pubspec.yaml:** 
```yaml
dependencies:
  flutter:
    sdk: flutter
  **flutter_localizations:
          sdk: flutter`**
```
**on main** 
```dart
MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate
      ],
      supportedLocales: [
        const Locale('en'),
        const Locale('fr')
      ],
```

This run s well on simulator, but it freezes my App on a real device.

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on macOS 11.4 20F71 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)

• No issues found!

</details>

**Comment by TahaTesser** [comment] 2021-06-08 12:13
Hi @ben55j 
I cannot reproduce any app freeze running code sample on `2.2.1` or `2.3.0-17.0.pre.259` 

Try the code sample

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      localizationsDelegates: [GlobalMaterialLocalizations.delegate],
      supportedLocales: [const Locale('en'), const Locale('fr')],
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          showDatePicker(
            locale: const Locale("fr", "FR"),
            context: context,
            initialDate: DateTime.now(),
            firstDate: DateTime.now(),
            lastDate: DateTime.now().add(Duration(days: 365)),
          ).then((value) {
            if (value != null) {
              showTimePicker(
                context: context,
                initialTime: TimeOfDay.now(),
              );
            }
          });
        },
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.259, on macOS 11.4 20F71 darwin-x64,
    locale en-GB)
    • Flutter version 2.3.0-17.0.pre.259 at
      /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba5208122a (9 hours ago), 2021-06-07 23:29:04 -0400
    • Engine revision b5dca5d4b4
    • Dart version 2.14.0 (build 2.14.0-188.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5154h
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      15.0
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.4 20F71 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 91.0.4472.77

• No issues found!
```

</details>

**Comment by ben55j** [comment] 2021-06-08 12:34
Hello Taha,

Yes, this sample works good. I will investigate more on my side to clarify the issue. Maybe a problem of interactions of packages...
I will let you know asap.

Many thanks.
Benjami

**Comment by ben55j** [comment] 2021-06-08 21:36
Hello @TahaTesser, 

I have succeeded to isolate the bug. I can't figure out why, but it seems to be linked to the use of both **CupertinoTabScaffold** and **localizationsDelegates & supportedLocales**

Here a minimal sample code to experiment the freeze (to test on real device):

`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      localizationsDelegates: [GlobalMaterialLocalizations.delegate],
      supportedLocales: [const Locale('en'), const Locale('fr')],
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    //return sca1();
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        iconSize: 25,
        currentIndex: 0,
        items: [
          BottomNavigationBarItem(icon: Icon(Icons.message), label: "Page 1"),
          BottomNavigationBarItem(
              icon: Icon(Icons.house_rounded), label: "Page 2"),
          BottomNavigationBarItem(
              icon: Icon(Icons.camera_enhance), label: "Page 3"),
        ],
      ),
      tabBuilder: (BuildContext ctx, int index) {
        Widget controllerSelected = bodies()[index];

        return Scaffold(
          body: controllerSelected,
        );
      },
    );
  }

  Widget pageTab(String title) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Page $title'),
              ElevatedButton(
                  onPressed: () {
                    showDatePicker(
                      locale: const Locale("fr", "FR"),
                      context: context,
                      initialDate: DateTime.now(),
                      firstDate: DateTime.now(),
                      lastDate: DateTime.now().add(const Duration(days: 365)),
                    ).then((value) {
                      if (value != null) {
                        showTimePicker(
                          context: context,
                          initialTime: TimeOfDay.now(),
                        );
                      }
                    });
                  },
                  child: Icon(Icons.add_circle))
            ],
          ),
        ),
      ),
    );
  }

  List<Widget> bodies() {
    return [
      pageTab("1"),
      pageTab("2"),
      pageTab("3"),
    ];
  }
}
`

**Comment by TahaTesser** [comment] 2021-06-09 09:58
Hi @ben55j 
I just tried code sample on the `stable` and `dev` (Channel dev, 2.3.0-16.0.pre), in both debug and release mode, the app doesn't get freeze. 

### Preview


https://user-images.githubusercontent.com/48603081/121334388-49410100-c922-11eb-9bd4-3ed9fc314440.mov



### Logs

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel dev, 2.3.0-16.0.pre, on macOS 11.4 20F71 darwin-x64, locale
    en-GB)
    • Flutter version 2.3.0-16.0.pre at /Users/tahatesser/Code/flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fa5883b78e (3 weeks ago), 2021-05-21 13:04:03 -0700
    • Engine revision 2f067fc4c5
    • Dart version 2.14.0 (build 2.14.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5154h
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554             • android-x86    •
      Android 11 (API 30) (emulator)
    • Taha’s iPhone (mobile)  • 00008020-001059882212002E • ios            • iOS
      15.0
    • macOS (desktop)         • macos                     • darwin-x64     •
      macOS 11.4 20F71 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript •
      Google Chrome 91.0.4472.77

• No issues found!
```

</details>

My device is using on IOS 15, which iOS version you're testing on?
Also please try again with latest `dev` channel 

Can you please upgrade to the latest  `dev` and try again
Execute the following commands to upgrade
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by darshankawar** [comment] 2021-07-09 12:33
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-07-09 12:33 UTC
Labels: in triage, waiting for customer response
