### ISSUE TITLE
Font manifest does not exist 

### ISSUE THREAD

**Issue by pouledodue** [flutter/flutter#33681] opened 2019-05-31 22:21 UTC
Please bundle a default FontManifest for Flutter Web

## Steps to Reproduce

1. open Vscode
2. Flutter: New Web Project
3. Start without Debugging
4. when page is loaded in Chrome, go to console

## Logs

```
dart_sdk.js:100734 Font manifest does not exist at `assets/FontManifest.json` – ignoring
```

```

✓] Flutter (Channel master, v1.6.4-pre.27, on Mac OS X 10.14.4 18E226, locale fr-FR)
    • Flutter version 1.6.4-pre.27 at /Users/xxx/dev/flutter-test/flutter
    • Framework revision 2d9b158faf (3 days ago), 2019-05-28 11:35:03 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.5.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by yjbanov** [comment] 2019-06-13 17:38
Closing as duplicate of https://github.com/flutter/flutter/issues/32245

**Closed by yjbanov** 2019-06-13 17:38 UTC
Labels: ☸ platform-web
