### ISSUE TITLE
There is only one FlutterSharedPreferences.xml file, which is fixed and cannot be changed. You cannot customize and create SharedPreferences files like Android

### ISSUE THREAD

**Issue by tolzlz** [flutter/flutter#120539] opened 2023-02-12 00:15 UTC
There is only one FlutterSharedPreferences.xml file, which is fixed and cannot be changed. You cannot customize and create SharedPreferences files like Android

**Comment by danagbemava-nc** [comment] 2023-02-13 07:49
Closing this as a duplicate of https://github.com/flutter/flutter/issues/82554. 

Kindly subscribe to the main issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-02-13 07:49 UTC
Labels: in triage
