### ISSUE TITLE
[quick_action][android] Not working with "LauncherActivity"

### ISSUE THREAD

**Issue by peixinli** [flutter/flutter#152883] opened 2024-08-05 19:29 UTC
Copied from internal bug b/357028168

### Steps to reproduce

Launched from shortcut

### Expected results

Expected: Launching from quick action shortcut should always trigger the callback in `quickActions.initialize`.

### Actual results

Actual: When the app has an "LauncherActivity" which forwards intents to the "MainActivity". (See attached recording)

1. If the app is launched normally from launch icon, the following shortcut works fine.

1. if the app is launched from shortcut, only the first shortcut works, the following shortcut is not working.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:quick_actions/quick_actions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: false),
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

// Copied from https://pub.dev/packages/quick_actions/example.
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String shortcut = 'no action set';

  @override
  void initState() {
    super.initState();

    const QuickActions quickActions = QuickActions();
    quickActions.initialize((String shortcutType) {
      setState(() {
        shortcut = shortcutType;
      });
    });

    quickActions.setShortcutItems(<ShortcutItem>[
      // NOTE: This first action icon will only work on iOS.
      // In a real world project keep the same file name for both platforms.
      const ShortcutItem(
        type: 'action_one',
        localizedTitle: 'Action one',
        icon: 'AppIcon',
      ),
      // NOTE: This second action icon will only work on Android.
      // In a real world project keep the same file name for both platforms.
      const ShortcutItem(
          type: 'action_two',
          localizedTitle: 'Action two',
          icon: 'ic_launcher'),
    ]).then((void _) {
      setState(() {
        if (shortcut == 'no action set') {
          shortcut = 'actions ready';
        }
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(shortcut),
      ),
      body: const Center(
        child: Text('On home screen, long press the app icon to '
            'get Action one or Action two options. Tapping on that action should  '
            'set the toolbar title.'),
      ),
    );
  }
}
```
AndroidManifest.xml
```
<activity
        android:name=".LauncherActivity"
        android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
        android:exported="true"
        android:hardwareAccelerated="true"
        android:launchMode="singleTop"
        android:theme="@style/LaunchTheme"
        android:windowSoftInputMode="adjustResize">
```

LauncherActivity.java
```
public final class LauncherActivity extends Activity {

  private static final String QUICK_ACTIONS_EXTRA = "some unique action key";

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    Intent mainActivityIntent = new Intent(this, MainActivity.class);
    mainActivityIntent.putExtras(getIntent());
    startActivity(mainActivityIntent);
    finish();
  }

  @Override
  public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
  }
}
```

</details>

https://github.com/user-attachments/assets/5cdd118a-70f6-4644-819d-30ac03eab86c

**Comment by danagbemava-nc** [comment] 2024-08-06 07:03
Hi @peixinli, it appears that you forgot to include the recording. Can you please add that? Please also include your `flutter doctor -v` output. 

Also, do we need to create a `LauncherActivity`? If so, kindly provide the code sample for that as well. 

Thank you

**Comment by peixinli** [comment] 2024-08-06 17:21
> Hi @peixinli, it appears that you forgot to include the recording. Can you please add that? Please also include your `flutter doctor -v` output.
> 
> Also, do we need to create a `LauncherActivity`? If so, kindly provide the code sample for that as well.
> 
> Thank you

Updated with recording and the code sample to create `LauncherActivity`.  This tracker of internal issue so I don't have `flutter doctor -v` output.

**Comment by danagbemava-nc** [comment] 2024-08-07 06:57
Hi @peixinli, does the screenshot below capture the issue? It appears your screen recording didn't make it this time round as well 😅 

![Screenshot_20240807-065609](https://github.com/user-attachments/assets/d605460c-3b61-41eb-a61d-6afc3ecc2cda)

**Comment by peixinli** [comment] 2024-08-07 17:51
Ah! Sorry I didn't realize it wasn't successfully uploaded. I uploaded the recording again. 

The issue starts at 0:42 and the title is not set to `action_two`.

I believe the issue is caused by changing an intent flag from `FLAG_ACTIVITY_CLEAR_TASK` to `FLAG_ACTIVITY_SINGLE_TOP` in [pull request](https://github.com/flutter/plugins/pull/5048/files#diff-102ba87893812ded222f3ddde9023b6b568dee9a142d575d0bff832fdf7325fdL166). The "LauncherActivity" pattern and the intent flags quick action plugin uses make case 2 fall into the below scenario mentioned in [Android doc](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_NEW_TASK:~:text=if%20a%20task%20is%20already%20running%20for%20the%20activity%20you%20are%20now%20starting%2C%20then%20a%20new%20activity%20will%20not%20be%20started%3B%20instead%2C%20the%20current%20task%20will%20simply%20be%20brought%20to%20the%20front%20of%20the%20screen%20with%20the%20state%20it%20was%20last%20in):

> if a task is already running for the activity you are now starting, then a new activity will not be started; instead, the current task will simply be brought to the front of the screen with the state it was last in.

**Comment by darshankawar** [comment] 2024-08-08 06:18
Thanks for the update. I was able to replicate the reported behavior using code sample provided.

```
Stable : 3.24.0
Master: 3.24.0-1.0.pre.509
```

**Comment by camsim99** [comment] 2024-08-15 20:48
> I believe the issue is caused by changing an intent flag from `FLAG_ACTIVITY_CLEAR_TASK` to `FLAG_ACTIVITY_SINGLE_TOP` in [pull request](https://github.com/flutter/plugins/pull/5048/files#diff-102ba87893812ded222f3ddde9023b6b568dee9a142d575d0bff832fdf7325fdL166). The "LauncherActivity" pattern and the intent flags quick action plugin uses make case 2 fall into the below scenario mentioned in [Android doc](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_NEW_TASK:~:text=if%20a%20task%20is%20already%20running%20for%20the%20activity%20you%20are%20now%20starting%2C%20then%20a%20new%20activity%20will%20not%20be%20started%3B%20instead%2C%20the%20current%20task%20will%20simply%20be%20brought%20to%20the%20front%20of%20the%20screen%20with%20the%20state%20it%20was%20last%20in):
> 
> > if a task is already running for the activity you are now starting, then a new activity will not be started; instead, the current task will simply be brought to the front of the screen with the state it was last in.

This makes sense. The docs mention using [`FLAG_ACTIVITIY_MULTIPLE_TASK`](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_MULTIPLE_TASK) to disable that behavior when you are implementing a top-level application launcher. I'm not 100% sure what that refers to but I think I will try this out and see if it works. I'm also going to read up on the modes and leave my notes here to sort out what flags we actually need (without undoing the work of that PR for non-launcher activity use cases).

**Comment by camsim99** [comment] 2024-08-15 21:02
Just checked and `FLAG_ACTIVITIY_MULTIPLE_TASK` does not work and neither does changing `FLAG_ACTIVITY_SINGLE_TOP` back to `FLAG_ACTIVITY_CLEAR_TASK`. Need to now dig into the different modes and how the single top launch mode of the launcher/main activity may play into this.

**Comment by camsim99** [comment] 2024-08-16 22:30
I've played around with this a bit and have found some interesting things:

1. According to https://developer.android.com/guide/components/activities/tasks-and-back-stack#:~:text=This%20second%20ability,a%20CATEGORY_LAUNCHER%20filter, we should not be defining singleTop mode for launcher activities. That may be part of the issue here but not sure. I tried changing it to single task mode and it did work but it did completely relaunch (maybe in a new task?) the option_2 activity when option_1 was already open.
2. I think that the flags we specify in `quick_actions` in this scenario apply to the intent starting the launcher activity not option_1/option_2. option_1/option_2 are from the main activity that use singleTop mode according to the manifest. I think for them to act as we'd expect, the launcher activirt may have to add additional intent flags. Since main activity is single top, I would expect for it's `onNewIntent` to get called and it does not, so I need to investigate that too.

I was able to get it working in a weird way (the activities were opening in new tasks) by adding flags to the launcher activity, so I'm going to keep digging there.

**Comment by camsim99** [comment] 2024-08-19 23:25
I've played around a more and now know what's happening.

Essentially, the `LauncherActivity` has mode `singleTop` meaning that **only if** an existing activity is at the top of the back stack of Activities in the current task, then it is re-opened with its `onNewIntent` called to potentially update the state. This means that if we launch action_one via quick action then we launch action_two via quick_action, the `onNewIntent` to the action_one/action_two activity is never called because the `LauncherActivity` used to launch action_two is  actually on the top of the back stack. This means that there's nothing actually launching action_two hence this issue.

**Comment by camsim99** [comment] 2024-08-19 23:54
As mentioned before, having the `LauncherActivity` use launcher mode `singleTask` does work. It behaves differently from apps without a launcher activity, though, because it causes the launcher activity to be opened in the same task both times it is launched via quick action. I think this because action_two > back press > action_one.

In an app with no launcher activity (main activity has mode `singleTop`), action_two > back press> home screen + no accessible action_two activity. action_one > back press >home screen + accessible action_one activity.

I now wonder if it's possibly to recreate the same back press behavior with the launcher activity.

**Comment by camsim99** [comment] 2024-08-20 23:52
Reading https://stackoverflow.com/questions/46096589/android-dynamic-shortcuts-not-opening-proper-activity-second-time made me realize I don't think I understand the issue here well, but also gave me great insight.

I now think that what's currently happening is that when the main activity is being back then brought back into the foreground, the task containing the launch activity (and main activity from before) is brought into view and Android does nothing as it has mode singleTop.

**Comment by camsim99** [comment] 2024-08-21 00:04
I just tried setting https://developer.android.com/guide/topics/manifest/activity-element#finish:~:text=Whether%20an%20existing,FLAG_ACTIVITY_RESET_TASK_IF_NEEDED%20isn%27t%20set. on launcher activity + adding flag clear_top and it worked as expected for this case and for the non-launcher activity case. The back behavior still does not match the same as [before](https://github.com/flutter/flutter/issues/152883#issuecomment-2297712362).

Hoping to figure out the differences there and that should hopefully bring me to the configuration needed here.

**Comment by camsim99** [comment] 2024-08-22 20:57
I just tried using `singleInstance` for the launcher activity because I had an inkling, and it worked. I will be back to try to explain this.

**Comment by camsim99** [comment] 2024-08-22 23:22
Ok I can confirm now that to fix this issue, the launcher activity needs to have mode `singleInstance`.

In the repro, the launcher activity uses mode `singleTop` as described [here](https://developer.android.com/guide/components/activities/tasks-and-back-stack#ManifestForTasks) in the Android docs. So...

1. When the action_one shortcut is launched, the launcher activity gets created (did not exist before) and then creates/launches the main activity that shows `action_one`.
2. When the action_two shortcut is launched, the launcher activity is brought back from the background to the foreground (as I believed is described [here](https://developer.android.com/guide/components/activities/tasks-and-back-stack#:~:text=The%20device%20Home,in%20the%20stack.) in the docs because a new task for the launcher activity is not started), and this re-launches the same main activity that shows `action_one`. `onNewIntent` is not called in the main activity.

However, when the launcher activity uses mode `singleInstance`,

1. When the action_one shortcut is launched, the launcher activity gets created (did not exist before) and then creates/launches the main activity that shows `action_one`.
2. When the action_two shortcut is launched, the launcher activity is launched into a new task and then re-launches the main activity that shows `action_one` originally, but `onNewIntent` is called, so that the launched main activity shows `action_two`.

Both launch modes have the same back press behavior as described by:  

> action_two > back press > home screen + no accessible action_two activity. action_one > back press >home screen + accessible action_one activity.

As I hinted to in my description of the differences in behavior, I believe this is happening because `singleInstance` (like `singleTask` which worked without maintaining the same back press behavior) both ensure a new task is started for the launcher activity, ensuring that an old state isn't just brought to the foreground.

Closing this as completed and will update b/357028168 but this can be reopened if this does not suit those bug's needs.

**Comment by camsim99** [comment] 2024-08-23 02:56
Decided a good action item here is to add documentation on how to handle launcher activities to the quick_action README. Re-opening to track that work.

**Comment by camsim99** [comment] 2024-09-10 17:43
**To update this issue:** my findings here seem to not have resolved  b/357028168 but I have confirmed that having a launcher activity like the one in the repro (no additional logic besides launching the main activity) with launch mode `singleInstance` maintains the same behavior as not having a launcher activity. I would still like to document this fact and plan to do so after I resolve the internal issue.

**Comment by camsim99** [comment] 2024-09-23 16:20
Turns out that the internal bug had other factors impacting the behavior of the quick_actions plugin with a launcher activity.

To close this issue, I will add documentation on maintaining the same behavior with/without a launcher activity so that folks that wish to use a launcher activity and this plugin have some guidance.

**Comment by camsim99** [comment] 2024-09-25 13:06
Re-opening to track improvements to https://github.com/flutter/packages/pull/7686 that includes further breadcrumbs on the work I did for this issue and what Flutter users may be able to do to figure out the right launch modes for their own launcher activities.

**Closed** 2024-10-02 16:33 UTC
Labels: platform-android, p: quick_actions, package, has reproducible steps, P1, team-android, triaged-android, found in release: 3.24
