### ISSUE TITLE
Firefox is slow at rendering a ListView of images

### ISSUE THREAD

**Issue by ilyoungkim** [flutter/flutter#50274] opened 2020-02-06 14:06 UTC
My Flutter web show images with ListBuilder. 
![671746f8d770a](https://user-images.githubusercontent.com/18169077/73943846-d9d58e80-4934-11ea-9900-b69f901deb5d.jpg)

The screen is not slow in the Chrome browser. However, the screen moves slowly in other browsers, such as Samsung Internet, Firefox, and Naver Whale.

Please make sure that the website address has been made public(http://grrrrtube.com) , and hope to fix the slow screen in the next patch.

**Comment by jonahwilliams** [comment] 2020-02-06 18:13
Hi @ilyoungkim what version of flutter are you using? (flutter doctor -v) I know that @ferhatb has recently landed some performance improvements for images

**Comment by ferhatb** [comment] 2020-02-06 21:19
@ilyoungkim , What version of Firefox? , do you have specs of phone you are testing on ?

**Comment by ilyoungkim** [comment] 2020-02-10 05:23
> Hi @ilyoungkim what version of flutter are you using? (flutter doctor -v) I know that @ferhatb has recently landed some performance improvements for images

summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.15.2, on Microsoft Windows [Version 10.0.18362.592], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] Connected device (2 available)

**Comment by ilyoungkim** [comment] 2020-02-10 05:32
> @ilyoungkim , What version of Firefox? , do you have specs of phone you are testing on ? Are you on master channel?

68.4.2
Firefox for Android Release
January 20, 2020

Testing Phone Spec.
Samsung Galaxy S8 and Galaxy Note5

Flutter channels:
  master
* dev
  beta
  stable

**Comment by yjbanov** [comment] 2020-04-28 19:01
I'm unassigning this for now as I won't be able to come back to it soon. My initial thought was that this can be fixed with paint ops pruning, but it looks like this is something very Firefox-specific.

**Comment by TahaTesser** [comment] 2020-11-11 11:59
Hi @ilyoungkim
Just tried to reproduce on the latest `master`, images load fast on firefox on mobile r desktop

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final List<String> images = [
    "https://i.imgur.com/WX4pLLN.jpg",
    "https://i.imgur.com/Mg7PAUo.jpg",
    "https://i.imgur.com/8ZNzBIS.jpg",
    "https://i.imgur.com/v7cShqs.jpg",
    "https://i.imgur.com/Xc3P64F.jpg",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: ListView.builder(
          itemCount: images.length,
          itemBuilder: (BuildContext context, int index) {
            return Image.network(images[index]);
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.194, on Mac OS X 10.15.7 19H15
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.194 at /Users/tahatesser/Code/flutter_master
    • Framework revision 018467cdb1 (4 hours ago), 2020-11-11 02:04:03 -0500
    • Engine revision 81f219c59c
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/SanDisk/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.2
    • macOS (desktop)      • macos                     • darwin-x64     • Mac OS X
      10.15.7 19H15 darwin-x64
    • Web Server (web)     • web-server                • web-javascript • Flutter
      Tools
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 86.0.4240.193

• No issues found!
```

</details>

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment] 2020-12-02 09:00
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-02 09:00 UTC
Labels: P4, browser: firefox, e: web_html, engine, perf: speed, platform-web, severe: performance, severe: rendering, waiting for customer response

**Comment by coditori** [comment] 2021-07-24 15:52
@pedromassangocode I'm having the same issue with the latest version of Firefox Mobile and Flutter

**Comment by TahaTesser** [comment] 2021-07-27 11:46
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
