### ISSUE TITLE
libtxt: Ellpsising code doesn't handle Arabic

### ISSUE THREAD

**Issue by Khalid-Nowaf** [flutter/flutter#10719] opened 2017-06-15 11:26 UTC
## Steps to Reproduce
create new flutter app `flutter create app`
change the title to Arabic text for example `تطبيق فلاتر`
run the app. try to compare the text `تطبيق فلاتر` with the AppBar title. You will see the missing character "one and half character cropped ! *RTL". Also some extra three dots `...`.
I tried couple languages including Hebrew with no issues. I'm not really sure is this related to AppBar or Scaffold.

sample code 
`````dart
....
 Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('تطبيق فلاتر'),
      ),
.....
``````
![](https://media.giphy.com/media/3og0IPXUHAu0aqyfa8/giphy.gif)

## Doctor 
`````
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-CA, channel master)
    • Flutter at /Users/Khalid/Library/flutter
    • Framework revision db75aa768c (2 days ago), 2017-06-12 19:46:38 -0700
    • Engine revision ffe8181ffe
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/Khalid/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[-] IntelliJ IDEA Ultimate Edition (version 2016.3.1)
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 14.0.0
    • Dart plugin version 163.13137
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[-] WebStorm (version 2016.3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected devices
    • iPhone SE • 71C81361-B8E3-4343-AD61-4D4BB4BF581E • ios • iOS 10.3 (simulator)

``````

**Comment by Hixie** [comment] 2017-06-16 07:05
This is probably specifically related to Arabic and text ellipsising.
cc @jason-simmons who was last in this code.
cc @GaryQian who may be solving this with libtxt.

**Comment by Khalid-Nowaf** [comment] 2017-06-16 07:23
BTW, I try to use Arabia text in many use cases, and all works with no issue. Except this one in the AppBar.

**Comment by Hixie** [comment] 2017-06-16 07:30
Have you tried it elsewhere with TextOverflow.ellipsis?

**Comment by Khalid-Nowaf** [comment] 2017-06-16 07:35
No I have not. I will try it now.

**Comment by Khalid-Nowaf** [comment] 2017-06-16 07:42
I have test 
````dart
new Text('تطبيق فلاتر', overflow: TextOverflow.ellipsis)
`````
and I still get the same problem.

**Comment by Hixie** [comment] 2017-06-16 22:12
Cool, thanks for the update.

**Comment by Hixie** [comment] 2017-10-20 00:34
cc @yjbanov this was the elipsising bug you ran into.

**Comment by Hixie** [comment] 2017-10-26 00:58
I was unable to reproduce this with the Ahem font:
```dart
  test('TextPainter - Arabic ellipsizing', () {
    final TextPainter painter = new TextPainter()
      ..textDirection = TextDirection.rtl
      ..ellipsis = '\u2026';

    painter.text = const TextSpan(
      text: '\u062A\u0637\u0628\u064A\u0642\u0020\u0641\u0644\u0627\u062A\u0631',
    );

    painter.layout();
    expect(painter.width, 154.0); // 11 * 14                                                                                                                                                                                                    
    expect(painter.height, 14);

    painter.layout(maxWidth: 155.0);
    expect(painter.width, 154.0); // 11 * 14                                                                                                                                                                                                    
    expect(painter.height, 14);
  });
```
Will have to try reproducing this on a device.

**Comment by yjbanov** [comment] 2017-10-26 19:38
The specific symptom that I've seen is text being broken up into multiple lines in buttons (https://github.com/flutter/flutter/issues/12288). It might be the same issue as this one.

**Comment by Hixie** [comment] 2017-11-01 00:30
I've been able to reproduce the problem without ellipses, but not with. The test above (from June 16) doesn't reproduce it any more.

**Comment by Hixie** [comment] 2017-11-01 00:30
If you can reproduce this reliably please do let me know. We very much care about this issue and intend to solve it if we can reproduce it.

**Comment by Khalid-Nowaf** [comment] 2017-11-01 01:59
I have updated my flutter 

## Doctor 
`````
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-CA, channel master)
    • Flutter at /Users/Khalid/projects/flutter
    • Framework revision e43eab656d (3 hours ago), 2017-10-31 15:51:32 -0700
    • Engine revision 277bfe66f0
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/Khalid/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • iPhone X • 4F4D54B0-6AAE-4B7F-B4AA-93342092CD51 • ios • iOS 11.0 (simulator)
`````

## steps to preduce 

1.  `flutter create arabic_flutter`
2. change the Home page title in main.dart to
`````dart
home: new MyHomePage(title: 'تطبيق فلاتر')
`````
3. hot reload
4. you will get an error "I have file an issue regarding this error"
`````
Unhandled exception:
FormatException: Source contains non-ASCII bytes.
#0      _SimpleAsciiDecoderSink.add (dart:convert/ascii.dart:293)
#1      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#2      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#3      _rootRunUnary (dart:async/zone.dart:1128)
#4      _CustomZone.runUnary (dart:async/zone.dart:1012)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#8      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#9      _StreamController._add (dart:async/stream_controller.dart:667)
#10     _StreamController.add (dart:async/stream_controller.dart:613)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#12     _rootRunUnary (dart:async/zone.dart:1132)
#13     _CustomZone.runUnary (dart:async/zone.dart:1012)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#17     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#18     _StreamController._add (dart:async/stream_controller.dart:667)
#19     _StreamController.add (dart:async/stream_controller.dart:613)
#20     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#21     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
``````` 
5. since the app crashed, try to run it again `flutter run`
6. you will see the Title "تطبيق فلاتر" not randerd currectly in semulator. 

## GIFS
### Change the Title 
![](https://media.giphy.com/media/l1JLHO5qVGtL2XnoI/giphy.gif)
### Run after Cersh
![](https://media.giphy.com/media/3o6obONLWmAaVPBnWM/giphy.gif)

**Comment by Hixie** [comment] 2017-11-02 20:36
Excellent, thanks.

**Comment by Hixie** [comment] 2017-12-20 01:48
cc @jason-simmons 

Leaving in current milestone as this is a high priority for us in the coming months.

**Comment by dahabit** [comment] 2018-01-18 04:45
Waiting to Fix this issue and other RTL issues

**Comment by dahabit** [comment] 2018-02-27 23:15
That issue still available on Flutter Beta :)

![screen shot 2018-02-28 at 1 12 24 am](https://user-images.githubusercontent.com/284535/36760743-c4c03796-1c24-11e8-9ddb-c7b1dd648688.png)

Version info
`
Flutter 0.1.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f914e701c5 (8 days ago) • 2018-02-19 21:12:17 +0000
Engine • revision 13cf22c284
Tools • Dart 2.0.0-dev.27.0-flutter-0d5cf900b0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (on Mac OS X 10.13.3 17D102, locale en-EG, channel beta)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[✓] VS Code (version 1.20.1)
[✓] Connected devices
`

**Comment by dahabit** [comment] 2018-02-27 23:37
I Switched to Master branch and still the same
![screen shot 2018-02-28 at 1 35 18 am](https://user-images.githubusercontent.com/284535/36761463-d540e2b6-1c27-11e8-9787-1f75cde60c35.png)

`
Flutter 0.1.8-pre.3 • channel master • https://github.com/flutter/flutter.git
Framework • revision 66e3f9d8aa (44 minutes ago) • 2018-02-28 01:19:32 +0200
Engine • revision e133da723c
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.1.8-pre.5, on Mac OS X 10.13.3 17D102, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[✓] VS Code (version 1.20.1)
[✓] Connected devices (1 available)
`

**Comment by xsoh** [comment] 2018-03-01 17:03
Hello everyone,
Thanks for this great project.
Just want to note that when you Add any ASCII character at the end it will print the whole words.
Here is an example of writing `أهلا و سهلا`:
<img width="393" alt="screen shot 2018-03-01 at 7 59 41 pm" src="https://user-images.githubusercontent.com/871079/36858115-5373277a-1d8b-11e8-8821-f41f23532204.png">

and here is  `أهلا و سهلا!` (Added: `!`):
<img width="345" alt="screen shot 2018-03-01 at 8 00 03 pm" src="https://user-images.githubusercontent.com/871079/36858129-627d2f68-1d8b-11e8-8fa9-d91dad1bdcc9.png">

**Comment by Khalid-Nowaf** [comment] 2018-03-03 00:06
@xsoh so the end if the line must not be a space then ...

**Comment by Hixie** [comment] 2018-03-03 00:32
This is on our list for the next few weeks. Patience folks. :-)

**Comment by Hixie** [comment] 2018-03-20 23:26
We are curious to hear if anyone who is using master is still running into this. We recently landed a major change to how text is rendered and it's possible (though certainly not guaranteed) that this was resolved at the same time. (We will look into it ourselves soon if nobody says that it is in fact fixed.)

**Comment by Rmaan** [comment] 2018-03-21 09:33
My case that was pretty similar to #12288 is fixed now. Thanks!

**Comment by xsoh** [comment] 2018-03-22 06:36
@Hixie I tried the master and it did work! Thanks!!
<img width="390" alt="screen shot 2018-03-22 at 9 34 55 am" src="https://user-images.githubusercontent.com/871079/37754905-7f6ba486-2db4-11e8-8593-5095888dd280.png">

**Comment by yjbanov** [comment] 2018-03-22 17:15
This looks beautiful! I'll check https://github.com/flutter/flutter/issues/12288 and close these two issues if they look fixed.

**Comment by dahabit** [comment] 2018-03-24 17:37
Arabic now working perfect Thanks 👍 
![screen shot 2018-03-24 at 2 49 16 pm](https://user-images.githubusercontent.com/284535/37866971-b50f0302-2f9a-11e8-81a0-ac98d93bee63.png)

**Comment by Hixie** [comment] 2018-03-27 23:27
Great! We will close this bug then! If you run into any issues, please don't hesitate to file a new bug.

**Closed by Hixie** 2018-03-27 23:27 UTC
Labels: prod: engine, prod: i18n
