### ISSUE TITLE
Execution failed for task ':thumbnails:verifyReleaseResources'. on apk build

### ISSUE THREAD

**Issue by rishabhdeepsingh** [flutter/flutter#69684] opened 2020-11-03 16:57 UTC
Steps: 
- `flutter build apk`

gives the following error

➜ `flutter build apk`
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to
reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:
        https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Removed unused resources: Binary resource data reduced from 462KB to 440KB: Removed 4%

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':thumbnails:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/whiteknife/.gradle/caches/transforms-2/files-2.1/c82bf40584b9a53c31dba07a8a48f301/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     /Users/whiteknife/.gradle/caches/transforms-2/files-2.1/c82bf40584b9a53c31dba07a8a48f301/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 1m 20s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      80.8s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using
Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...                            ⡿%

**Comment by pedromassangocode** [comment] 2020-11-05 08:39
Hi @rishabhdeepsingh 
Can you please provide your `flutter doctor -v`, your `flutter build appbundle --verbose` and your `pubspec.yaml`. 
Thank you

**Comment by rishabhdeepsingh** [comment] 2020-11-05 08:51
> $ flutter doctor -v


[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-IN)
    • Flutter version 1.22.3 at /Users/whiteknife/softwares/flutter
    • Framework revision 8874f21e79 (7 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/whiteknife/softwares/androidsdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/whiteknife/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Users/whiteknife/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Users/whiteknife/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 2 categories.



------

[appbundle.log](https://github.com/flutter/flutter/files/5493047/appbundle.log)

[pubspec.yaml.txt](https://github.com/flutter/flutter/files/5493051/pubspec.yaml.txt)

**Comment by pedromassangocode** [comment] 2020-11-05 09:13
Hi @rishabhdeepsingh 
Looks like the issue is gone, based on the logs your build succeeded.

```
[        ] > Task :app:configureReleaseDependencies
[+4699 ms] > Task :app:packageReleaseBundle
[+1185 ms] > Task :app:signReleaseBundle
[        ] > Task :app:bundleRelease
[        ] BUILD SUCCESSFUL in 15s
[        ] 224 actionable tasks: 10 executed, 214 up-to-date
[ +391 ms] Running Gradle task 'bundleRelease'... (completed in 16.5s)
[  +10 ms] ✓ Built build/app/outputs/bundle/release/app-release.aab (20.5MB).
[   +4 ms] "flutter appbundle" took 18,503ms.
[ +262 ms] ensureAnalyticsSent: 257ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

Are you still facing this issue?

**Comment by rishabhdeepsingh** [comment] 2020-11-05 09:25
Yes, I am still facing the issue.
> flutter build apk

You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to
reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:
        https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':thumbnails:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/whiteknife/.gradle/caches/transforms-2/files-2.1/c82bf40584b9a53c31dba07a8a48f301/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     /Users/whiteknife/.gradle/caches/transforms-2/files-2.1/c82bf40584b9a53c31dba07a8a48f301/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      11.9s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using
Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...                            ⡿%

**Comment by pedromassangocode** [comment] 2020-11-05 13:12
Based on the logs looks like the issue is related to an plugin.

```
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using
Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'... ⡿%
```

From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-05 13:12 UTC
Labels: in triage

**Comment by rishabhdeepsingh** [comment] 2020-11-05 15:45
Thanks a lot @pedromassango

**Comment by Nandan-Wewhare** [comment] 2020-12-01 06:36
```
`FAILURE: Build failed with an exception.                                                                                    
Execution failed for task ':thumbnails:verifyReleaseResources'.         
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /home/user/.gradle/caches/transforms-2/files-2.1/6b399c2363bb098ebde1725d903cbda0/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
`
```

Error while building the project

**Comment by Nandan-Wewhare** [comment] 2020-12-01 06:38
**Flutter Doctor output**

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_IN)
    • Flutter version 1.23.0-18.1.pre at /home/user/Documents/flutter
    • Framework revision 198df796aa (7 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/user/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/user/Documents/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.66

• No issues found!

```
