### ISSUE TITLE
[camera] starting image stream freezes camera (android)

### ISSUE THREAD

**Issue by felixriehm** [flutter/flutter#125623] opened 2023-04-27 12:14 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Just execute the minimal reproducible sample i have provided

=> camera freezes

Smartphone: Galaxy A04s
Model name: SM-A047F/DSN
One UI Core Version 5.1
Android Verion: 13

camera: camera: 0.10.4
camera_android: 0.10.6+1

It works with the android emulator.

### Expected results

camera should not freeze

### Actual results

camera freezes

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

late List<CameraDescription> _cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  _cameras = await availableCameras();
  runApp(const CameraApp());
}

/// CameraApp is the Main Application.
class CameraApp extends StatefulWidget {
  /// Default Constructor
  const CameraApp({super.key});

  @override
  State<CameraApp> createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  late CameraController controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(_cameras[0], ResolutionPreset.high);
    controller.initialize().then((_) {
      if (!mounted) {
        return;
      }
      controller.startImageStream((image) => null);
      setState(() {});
    }).catchError((Object e) {
      if (e is CameraException) {
        switch (e.code) {
          case 'CameraAccessDenied':
          // Handle access errors here.
            break;
          default:
          // Handle other errors here.
            break;
        }
      }
    });
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!controller.value.isInitialized) {
      return Container();
    }
    return MaterialApp(
      home: CameraPreview(controller),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://user-images.githubusercontent.com/13718034/234858271-a34f8eb6-b8b0-49a1-ba27-e67b69724380.mp4

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on SM A047F in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Debug service listening on ws://127.0.0.1:58036/vRVO7DY1JbQ=/ws
Syncing files to device SM A047F...
I/CameraManagerGlobal(24641): Connecting to camera service
D/VendorTagDescriptor(24641): addVendorDescriptor: vendor tag id 14172875900359437128 added
I/CameraManagerGlobal(24641): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.example.camera_image_stream_bug API Level 2
I/CameraManagerGlobal(24641): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client android.system API Level 2
I/CameraManagerGlobal(24641): Camera 2 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client android.system API Level 2
I/CameraManagerGlobal(24641): Camera 23 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2
I/CameraManagerGlobal(24641): Camera 3 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client android.system API Level 2
I/CameraManagerGlobal(24641): Camera 52 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2
I/CameraManagerGlobal(24641): Camera 54 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2
D/CompatibilityChangeReporter(24641): Compat change id reported: 206033068; UID 10171; state: ENABLED
I/BLASTBufferQueue(24641): [SurfaceView[com.example.camera_image_stream_bug/com.example.camera_image_stream_bug.MainActivity]@0#1](f:0,a:0) onFrameAvailable the first frame is available
D/SurfaceView@2b191f1(24641):  setAlpha: mUseAlpha = false alpha=1.0
D/SurfaceView@2b191f1(24641):  updateSurfaceAlpha: setUseAlpha() is not called, ignored.
I/ViewRootImpl@409e3e5[MainActivity](24641): Setup new sync id=0
I/ViewRootImpl@409e3e5[MainActivity](24641): Setting syncFrameCallback
E/SurfaceSyncer(24641): Failed to find sync for id=0
I/ViewRootImpl@409e3e5[MainActivity](24641): registerCallbacksForSync syncBuffer=false
D/SurfaceView@2b191f1(24641): updateSurfacePosition RenderWorker, frameNr = 1, position = [0, 0, 720, 1510] surfaceSize = 720x1510
I/SurfaceView@2b191f1(24641): uSP: rtp = Rect(0, 0 - 720, 1510) rtsw = 720 rtsh = 1510
I/SurfaceView@2b191f1(24641): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@2b191f1(24641): aOrMT: ViewRootImpl@409e3e5[MainActivity] t = android.view.SurfaceControl$Transaction@f06b33b fN = 1 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1537 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:373 
I/ViewRootImpl@409e3e5[MainActivity](24641): mWNT: t=0xb400006fc0648600 mBlastBufferQueue=0xb400006fc0567500 fn= 1 caller= android.view.SurfaceView.applyOrMergeTransaction:1455 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1537 
I/ViewRootImpl@409e3e5[MainActivity](24641): mWNT: t=0xb400006fc0648f00 mBlastBufferQueue=0xb400006fc0567500 fn= 1 caller= android.view.ViewRootImpl.lambda$applyTransactionOnDraw$11$android-view-ViewRootImpl:12865 android.view.ViewRootImpl$$ExternalSyntheticLambda1.onFrameDraw:4 android.graphics.HardwareRenderer$FrameDrawingCallback.onFrameDraw:924 
I/ViewRootImpl@409e3e5[MainActivity](24641): Received frameDrawingCallback syncResult=0 frameNum=1.
I/ViewRootImpl@409e3e5[MainActivity](24641): Setting up sync and frameCommitCallback
I/BLASTBufferQueue(24641): [ViewRootImpl@409e3e5[MainActivity]#0](f:0,a:0) onFrameAvailable the first frame is available
I/ViewRootImpl@409e3e5[MainActivity](24641): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
D/OpenGLRenderer(24641): CFMS:: SetUp Pid : 24641    Tid : 24684
I/ViewRootImpl@409e3e5[MainActivity](24641): onSyncComplete
I/ViewRootImpl@409e3e5[MainActivity](24641): setupSync seqId=0 mSyncId=0 fn=1 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503 
I/ViewRootImpl@409e3e5[MainActivity](24641): reportDrawFinished seqId=0 mSyncId=-1 fn=1 mSurfaceChangedTransaction=0xb400006fc0648d00
I/ViewRootImpl@409e3e5[MainActivity](24641): MSG_WINDOW_FOCUS_CHANGED 1 0
I/ViewRootImpl@409e3e5[MainActivity](24641): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400006f3fab6000}
D/InputMethodManager(24641): startInputInner - Id : 0
I/InputMethodManager(24641): startInputInner - mService.startInputOrWindowGainedFocus
W/Camera  (24641): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
I/CameraManagerGlobal(24641): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.example.camera_image_stream_bug API Level 2
D/InputMethodManager(24641): startInputInner - Id : 0
D/InsetsController(24641): onStateChanged: InsetsState: {mDisplayFrame=Rect(0, 0 - 720, 1600), mDisplayCutout=DisplayCutout{insets=Rect(0, 45 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(272, 0 - 448, 45), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=720 displayHeight=1600 physicalDisplayWidth=720 physicalDisplayHeight=1600 density={1.875} cutoutSpec={M 0,0 H -46.93333333333333 V 24 H 46.93333333333333 V 0 H 0 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=60, center=Point(60, 60)}, RoundedCorner{position=TopRight, radius=60, center=Point(660, 60)}, RoundedCorner{position=BottomRight, radius=60, center=Point(660, 1540)}, RoundedCorner{position=BottomLeft, radius=60, center=Point(60, 1540)}]}  mRoundedCornerFrame=Rect(0, 0 - 720, 1600), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(637, 0 - 720, 48) rotation=0}, mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][720,48], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,1510][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][0,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[720,0][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_MANDATORY_GESTURES, mFrame=[0,0][720,68], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_MANDATORY_GESTURES, mFrame=[0,1510][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-100000,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][720,45], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[100000,0][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,100000][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][720,48], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_TAPPABLE_ELEMENT, mFrame=[0,1510][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_IME, mFrame=[0,0][0,0], mVisible=false, mInsetsRoundedCornerFrame=false} } host=com.example.camera_image_stream_bug/com.example.camera_image_stream_bug.MainActivity from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6740
I/Camera  (24641): startPreview
I/Camera  (24641): CameraCaptureSession onConfigured
I/Camera  (24641): Updating builder settings
D/Camera  (24641): Updating builder with feature: ExposureLockFeature
D/Camera  (24641): Updating builder with feature: ExposurePointFeature
D/Camera  (24641): Updating builder with feature: ZoomLevelFeature
D/Camera  (24641): Updating builder with feature: AutoFocusFeature
D/Camera  (24641): Updating builder with feature: NoiseReductionFeature
I/Camera  (24641): updateNoiseReduction | currentSetting: fast
D/Camera  (24641): Updating builder with feature: FocusPointFeature
D/Camera  (24641): Updating builder with feature: ResolutionFeature
D/Camera  (24641): Updating builder with feature: SensorOrientationFeature
D/Camera  (24641): Updating builder with feature: FlashFeature
D/Camera  (24641): Updating builder with feature: ExposureOffsetFeature
D/Camera  (24641): Updating builder with feature: FpsRangeFeature
I/Camera  (24641): refreshPreviewCaptureSession
I/CameraManagerGlobal(24641): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.example.camera_image_stream_bug API Level 2
I/CameraManagerGlobal(24641): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.example.camera_image_stream_bug API Level 2
I/Camera  (24641): startPreviewWithImageStream
I/Camera  (24641): CameraCaptureSession onConfigured
I/Camera  (24641): Updating builder settings
D/Camera  (24641): Updating builder with feature: ExposureLockFeature
D/Camera  (24641): Updating builder with feature: ExposurePointFeature
W/mage_stream_bug(24641): Long monitor contention with owner main (24641) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1402) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 548ms
D/Camera  (24641): Updating builder with feature: ZoomLevelFeature
D/Camera  (24641): Updating builder with feature: AutoFocusFeature
W/mage_stream_bug(24641): Long monitor contention with owner main (24641) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1402) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 461ms
D/Camera  (24641): Updating builder with feature: NoiseReductionFeature
I/Camera  (24641): updateNoiseReduction | currentSetting: fast
D/Camera  (24641): Updating builder with feature: FocusPointFeature
D/Camera  (24641): Updating builder with feature: ResolutionFeature
D/Camera  (24641): Updating builder with feature: SensorOrientationFeature
D/Camera  (24641): Updating builder with feature: FlashFeature
D/Camera  (24641): Updating builder with feature: ExposureOffsetFeature
D/Camera  (24641): Updating builder with feature: FpsRangeFeature
I/Camera  (24641): refreshPreviewCaptureSession
I/CameraManagerGlobal(24641): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.example.camera_image_stream_bug API Level 2
I/Camera  (24641): CameraCaptureSession onClosed
E/mali_winsys(24641): Unrecognised Android chroma siting range: [2, 2]. Applying default
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
W/System  (24641): A resource failed to call Surface.release. 
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
E/BufferQueueProducer(24641): [ImageReader-1280x720f23m1-24641-1](id:604100000004,api:4,p:742,c:24641) waitForFreeSlotThenRelock: timeout [mDequeueTimeout=1000ms
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-DE)
    • Flutter version 3.7.7 on channel stable at /Users/felix/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (7 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/felix/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/felix/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/felix/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 72.1.3
    • Dart plugin version 222.4560

[✓] VS Code (version 1.77.3)
    • VS Code at /Users/felix/Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM A047F (mobile)           • R58TB15K7TF   • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2023-04-27 13:15
I believe this is a duplicate of https://github.com/flutter/flutter/issues/114862. 

Kindly subscribe to the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2023-04-27 13:15 UTC
Labels: in triage
