### ISSUE TITLE
Pigeon: unable to spawn isolate

### ISSUE THREAD

**Issue by xster** [flutter/flutter#71766] opened 2020-12-05 04:00 UTC
```
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Error: Could not resolve the package 'pigeon' in 'package:pigeon/pigeon_lib.dart'.
/var/folders/xt/mwq_g0y15x5dqzsdc3zym1_r0000gn/T/27uiPu/_pigeon_temp_.dart:4:8: Error: Not found: 'package:pigeon/pigeon_lib.dart'
import 'package:pigeon/pigeon_lib.dart';
       ^
/var/folders/xt/mwq_g0y15x5dqzsdc3zym1_r0000gn/T/27uiPu/_pigeon_temp_.dart:7:23: Error: Getter not found: 'Pigeon'.
  sendPort.send(await Pigeon.run(args));
```

when flutter pub run pigeon on 1.17

From GDS China video comment https://www.bilibili.com/video/BV11z4y1y7ph

**Comment by gaaclarke** [comment] 2021-06-21 23:46
I'm unable to reproduce this problem, I'd need to have some reproduction steps.  Is the user potentially running from global activate instead of using pigeon as a dev_dependency?

However they produced it, I suspect it will be eliminated with the migration to the Dart analyzer here: https://github.com/flutter/packages/pull/381

**Comment by stuartmorgan** [comment] 2021-08-24 20:03
Since we don't have repro steps, and the migration to analyzer landed, I'm going to close this as there doesn't seem to be anything else actionable at this point.

**Closed by stuartmorgan** 2021-08-24 20:03 UTC
Labels: severe: crash, p: first party, package, passed first triage, pigeon
