### ISSUE TITLE
scrollUntilVisible can't be used with a ListView in flutter_test

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#90298] opened 2021-09-17 23:28 UTC
When I try to call `scrollUntilVisible` I get an error:

```dart
    // Scroll until the item to be found appears.
    await tester.scrollUntilVisible(
      itemFinder,
      500.0,
      scrollable: listFinder,
    );
```

```
The following _CastError was thrown running a test:
type 'ListView' is not a subtype of type 'Scrollable' in type cast
```

I can work around the issue by changing the Finder from `find.byKey(const ValueKey('long_list'))` to `find.byType(Scrollable)`, but I'm not sure why ListView isn't able to be cast as a Scrollable

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

main.dart:

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(10000, (i) => "Item $i"),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;

  const MyApp({Key? key, required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: const Text(title),
        ),
        body: ListView.builder(
          // Add a key to the ListView. This makes it possible to
          // find the list and scroll through it in the tests.
          key: const Key('long_list'),
          itemCount: items.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text(
                items[index],
                // Add a key to the Text widget for each item. This makes
                // it possible to look for a particular item in the list
                // and verify that the text is correct
                key: Key('item_${index}_text'),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

test/widget_test.dart:

```dart
// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility that Flutter provides. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:bug/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(MyApp(
      items: List<String>.generate(10000, (i) => "Item $i"),
    ));

    final listFinder = find.byKey(const ValueKey('long_list'));
    final itemFinder = find.byKey(const ValueKey('item_50_text'));

    // Scroll until the item to be found appears.
    await tester.scrollUntilVisible(
      itemFinder,
      500.0,
      scrollable: listFinder,
    );

    // Verify that the item contains the correct text.
    expect(itemFinder, findsOneWidget);
  });
}
```

3. Run `flutter test`

**Expected results:** Test passes

**Actual results:** Exception: "The following _CastError was thrown running a test:
type 'ListView' is not a subtype of type 'Scrollable' in type cast"

<details>
  <summary>Logs</summary>

```
/Users/ryjohn/code/sdks/flutter/bin/flutter --no-color test --machine --start-paused test/widget_test.dart
Testing started at 4:23 PM ...

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _CastError was thrown running a test:
type 'ListView' is not a subtype of type 'Scrollable' in type cast

When the exception was thrown, this was the stack:
#0      WidgetController.widget (package:flutter_test/src/controller.dart:69:44)
#1      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1192:15)
#2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1190:39)
#5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1190:27)
#7      main.<anonymous closure> (file:///Users/ryjohn/code/github/johnpryan/integration_test_experiments/test/widget_test.dart:24:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The test description was:
  Counter increments smoke test
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Counter increments smoke test
```

```
Analyzing bug...                       
No issues found! (ran in 1.5s)
```

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.6 20G165 darwin-x64, locale en)
    • Flutter version 2.5.0 at /Users/ryjohn/code/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (10 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ryjohn/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 13181FDD400226 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos          • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 1 category.

```

</details>

**Comment by TahaTesser** [comment] 2021-09-21 09:06
Hi @johnpryan 
I can reproduce this, duplicate of https://github.com/flutter/flutter/issues/85046

**Closed by TahaTesser** 2021-09-21 09:06 UTC
Labels: a: tests, P5
