### ISSUE TITLE
there's a typo

### ISSUE THREAD

**Issue by aasiflm10** [flutter/flutter#99988] opened 2022-03-11 17:17 UTC
there is a typo in the last second word of the following paragraph 

It can go anywhere in the file outside of MyApp, but the solution places it at the bottom of the file. In lib/main.dart, position your cursor after all of the code, enter Return a couple times to start on a fresh line. In your IDE, start typing stful. The editor asks if you want to create a Stateful widget. Press Return to accept. The boilerplate code for two classes appears, and the cursor is positioned for you to enter the name of your stateless widget.

/* It needs to be stateful not stateless */

**Comment by danagbemava-nc** [comment] 2022-03-14 07:35
Hi @aasiflm10, can you share a link to the document that contains this typo so it may be properly addressed?

**Comment by amanv8060** [comment] 2022-03-16 21:29
looks like a duplicate of #69504

**Closed** 2022-04-04 08:15 UTC
Labels: waiting for customer response, in triage
