### ISSUE TITLE
CustomScrollView bug when SliverGrid and SliverList are children

### ISSUE THREAD

**Issue by JohannesKaufmann** [flutter/flutter#11548] opened 2017-08-08 11:04 UTC
## Steps to Reproduce

Running the Sample Code from [widgets/CustomScrollView](https://docs.flutter.io/flutter/widgets/CustomScrollView-class.html) produces a bug while scrolling. See [Video](https://youtu.be/C-7Dt3ZkaN0) and [Github Repo](https://github.com/JohannesKaufmann/sliverbug/blob/master/lib/main.dart#L41-L82).

(The issue only seems to happen if a `SliverGrid` and a `SliverFixedExtentList`/`SliverList` are mixed together in a `CustomScrollView`?) It was recorded on the iPhone Simulator but the same happens on an actual Android Device.

```dart
/* Sample Code from widgets/CustomScrollView */
new CustomScrollView(
  slivers: <Widget>[
    const SliverAppBar(
      pinned: true,
      expandedHeight: 250.0,
      flexibleSpace: const FlexibleSpaceBar(
        title: const Text('Demo'),
      ),
    ),
    new SliverGrid(
      gridDelegate: new SliverGridDelegateWithMaxCrossAxisExtent(
        maxCrossAxisExtent: 200.0,
        mainAxisSpacing: 10.0,
        crossAxisSpacing: 10.0,
        childAspectRatio: 4.0,
      ),
      delegate: new SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          return new Container(
            alignment: FractionalOffset.center,
            color: Colors.teal[100 * (index % 9)],
            child: new Text('grid item $index'),
          );
        },
        childCount: 20,
      ),
    ),
    new SliverFixedExtentList(
      itemExtent: 50.0,
      delegate: new SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          return new Container(
            alignment: FractionalOffset.center,
            color: Colors.lightBlue[100 * (index % 9)],
            child: new Text('list item $index'),
          );
        },
      ),
    ),
  ],
)
```

```dart
/* similar code in my own app */
List slivers = <Widget>[
  new SliverAppBar(
    pinned: true,
    primary: true,
    expandedHeight: topSize['height'],
    flexibleSpace: new FlexibleSpaceBar(
      background: topContent(context, widget.id),
    ),
    actions: <Widget>[
      new IconButton(
        icon: new Icon(Icons.share),
        onPressed: () {

        },
        tooltip: 'Share',
      )
    ],
  ),
  new SliverList(
    delegate: new SliverChildListDelegate(
      topChildren.where(notNull).toList(),
    )
  ),
  new Images( // is a SliverGrid
    images: screenshots,
    id: widget.id,
    onClickImage: openImage
  ),
  new SliverList(
    delegate: new SliverChildListDelegate(
    bottomChildren.where(notNull).toList(),
  )
 ), 
];

return new CustomScrollView(
  slivers: slivers
)
```

### `flutter logs`

Since there is not crash happening there are no indications in the logs.

```
DTServiceHub: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
diagnosticd: dispatch_io_write error: 32 (Broken pipe)
diagnosticd: reflect channel created for fd 6
DTServiceHub: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
DTServiceHub: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
DTServiceHub: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
```

### `flutter analyze`
only one issues regarding not using the value `_counter`

## `flutter doctor`

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-DE, channel alpha)
    • Flutter at /Users/johannes/Documents/dev/github/flutter-sdk
    • Framework revision bbcfb8d51a (7 days ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/johannes/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/johannes/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[-] IntelliJ IDEA Community Edition (version 2016.3.2)
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 14.0.0
    • Dart plugin version 163.13137
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected devices
    • iPhone SE • A5527156-9756-425D-B9F0-CB741DB4FB42 • ios • iOS 10.3 (simulator)
```

-----

Because there is a lack of documentation regarding slivers I wanted to ask another question:

If I understand correctly this

```
CustomScrollView
  - SliverAppBar
  - SliverList
      - Item
      - Item
  - SliverGrid
  - SliverList
```
is now preferred over
```
$controller

ListView (with controller)
  - Item
  - Item
  - GridView (with controller & shrinkWrap: true)
  - Item
```

Is this correct?

**Comment by Hixie** [comment] 2017-08-08 18:31
> is this correct?

Definitely, yes.

There should be some documentation for slivers now by the way. The only thing lacking any documentation at all currently is NestedScrollView. Please don't hesitate to file bugs if you have specific questions that the documentation doesn't answer.

**Comment by Hixie** [comment] 2017-08-08 20:56
Looks like the bug here is that when the SliverGrid is off the screen, it reports the wrong metrics.

**Comment by eturk1** [comment] 2017-08-09 21:19
Another related bug? 

I'm learning flutter and was driving me nuts thinking I was missing code, until I tried a simple test.

BUG: cannot have more than one SliverGrid in CustomScrollView. 
Recreate by taking the same sample code above, copy a create 3 total SliverGrids, change color for each grid. 
When you scroll on Nexus 5 emulator, you'll get first two and then bounce up to top. 3rd never paints.

**Comment by Hixie** [comment] 2017-08-09 21:33
Probably the same thing, yeah.

**Comment by eturk1** [comment] 2017-08-11 18:58
Any suggested workaround to show multiple grids in a single view?
I want to show grids of Cards with headings, as in Google Now view on Android.

---
Here's the code to recreate multi-grid bug:
[main.dart.txt](https://github.com/flutter/flutter/files/1218828/main.dart.txt)

**Comment by Hixie** [comment] 2017-08-12 05:02
I can't think of a work-around. This is definitely a bug we should fix though. It's probably a simple math bug in the RenderSliverGrid class if you're interested in trying to pin down the cause yourself.

**Comment by eturk1** [comment] 2017-08-16 06:22
Actually, important to note not even the sample Flutter code actually works.
https://docs.flutter.io/flutter/widgets/CustomScrollView-class.html

once it hits the list index of [12] screen paints starting at [12] at the top, rather than continuing to scroll below [11]. Sample main.dart attached with flutter doc sample used for home:

[main.dart.txt](https://github.com/flutter/flutter/files/1227200/main.dart.txt)

I'm digging into RenderSliverGrid.performLayout() but it's over my head pretty quickly. :(

**Comment by Hixie** [comment] 2017-08-16 16:48
Yup, we definitely need to fix this.

**Comment by eturk1** [comment] 2017-08-23 23:07
seems a low priority that the sample code doesn't even work. 
any way to include an expert in this thread on SliverGrid so this can get on their radar?

**Comment by Hixie** [comment] 2017-08-23 23:41
I'm the expert. It's a high priority, it's just competing with all the other high priorities.

**Comment by eturk1** [comment] 2017-08-24 21:29
oh cool Hixie thanks
flutter is very promising and thanks for your dedication to make it great!

**Comment by eturk1** [comment] 2017-08-28 08:21
seems bug is also in SliverFixedExtentList as well as SliverGrid

sample using 3 SliverFixedExtentList of length 20. It also bounces to start paint at top when 3 list is starting to display. Sample code:
[main.dart.txt](https://github.com/flutter/flutter/files/1255501/main.dart.txt)

**Comment by Hixie** [comment] 2018-02-03 02:14
I have a fix for this. Just need to write a test.

**Closed** 2018-02-05 21:56 UTC
Labels: prod: framework, prod: scrolling, waiting for PR to land (fixed)
