### ISSUE TITLE
Flutter docs on Google Code Labs part 2 uses `new` keyword which is not required since Dart 2.1

### ISSUE THREAD

**Issue by deadcoder0904** [flutter/flutter#25146] opened 2018-12-10 06:13 UTC
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#0 has lots of `new` keyword. It can be removed since newer Dart versions don't require it :)

**Comment by zoechi** [comment] 2018-12-10 07:55
Duplicate of flutter/website#1936

**Closed by zoechi** 2018-12-10 07:55 UTC
