### ISSUE TITLE
[animations] OpenContainer exceptions

### ISSUE THREAD

**Issue by iamarnas** [flutter/flutter#51397] opened 2020-02-25 08:55 UTC
I have long list by Items and some of them crash when I close container otherwise most of them work well. I can say 3% of list items throw error exception on closing. I use latest animations: ^1.0.0+5 package. More info below...

<details>
  <summary>Logs</summary>

```
════════ Exception caught by widgets library  ═══════════
The following NoSuchMethodError was thrown building AnimatedBuilder(animation: AnimationController#064eb(◀ 1.000; for _OpenContainerRoute)➩ProxyAnimation, dirty, state: _AnimatedState#75c14):

The getter 'isInTree' was called on null.
Receiver: null
Tried calling: isInTree

When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      _OpenContainerRoute.buildPage.<anonymous closure> 
package:animations/src/open_container.dart:738
#2      AnimatedBuilder.build 
package:flutter/…/widgets/transitions.dart:1012
#3      _AnimatedState.build 
package:flutter/…/widgets/transitions.dart:178
#4      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4334
...
═══════════════════════════════════════════════════════════════

════════ Exception caught by animation library  ══════════════
The setter 'placeholderSize=' was called on null.
Receiver: null
Tried calling: placeholderSize=null
═══════════════════════════════════════════════════════════════
```
```
Analyzing demo_app_x...                                                 
No issues found! (ran in 77.5s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale sv-SE)
    • Flutter version 1.12.13+hotfix.8 at /Users/arnas/Documents/Development/Tools/flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/arnas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Nexus 5X • 013c535795c613eb • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-02-25 09:29
Hi @iamarnas 
could you provide a code sample to reproduce it?

**Comment by iamarnas** [comment] 2020-02-25 10:42
> Hi @iamarnas
> could you provide a code sample to reproduce it?

**Comment by iamarnas** [comment] 2020-02-25 10:53
Hi @VladyslavBondarenko 

The look of the list looks like this.

`
//...
children: _fixtures
                    .map((fixture) {
                      // Add fixtures by same id to list
                      if (fixture.league.id == leagueId)
                        return _buildEventTile(fixture);
                      else
                        return null;
                    })
                    .where((widget) => widget != null)
                    .toList(),
//...
`

Here is my OpenContainer..

`
Widget _buildEventTile(Response fixtures) {
    // Open Container with animated transition
    return OpenContainer(
      closedShape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.all(
          Radius.circular(0),
        ),
      ),
      closedElevation: 0,
      openElevation: 0,
      closedColor: Theme.of(context).scaffoldBackgroundColor,
      openColor: Theme.of(context).scaffoldBackgroundColor,
      transitionType: _transitionType,
      openBuilder: (BuildContext _, VoidCallback openContainer) {
        return FixturesPage(fixture: fixtures);
      },
      closedBuilder: (BuildContext _, VoidCallback openContainer) {
        return Material(
          type: MaterialType.transparency,
          child: InkWell(
            onTap: openContainer,
            child: Container(
              height: kToolbarHeight,
              margin: EdgeInsets.only(left: _padding, right: _padding),
              child: Row(
                mainAxisSize: MainAxisSize.max,
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
                  StatusContainer(
                    status: fixtures.fixture.status.short,
                    elapsed: fixtures.fixture.status.elapsed,
                  ),
                  TeamNameContainer(
                    crossAxisAlignment: CrossAxisAlignment.end,
                    textAlign: TextAlign.end,
                    text: fixtures.teams.home.name,
                  ),
                  TeamLogo(imageUrl: fixtures.teams.home.logo),
                  Scores(
                    date: fixtures.fixture.date.toLocal(),
                    homeScore: fixtures.goals.home,
                    awayScore: fixtures.goals.away,
                  ),
                  TeamLogo(imageUrl: fixtures.teams.away.logo),
                  TeamNameContainer(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    textAlign: TextAlign.start,
                    text: fixtures.teams.away.name,
                  ),
                  Opacity(
                    opacity: 0.0,
                    child: StatusContainer(
                      status: 'hidden',
                    ),
                  )
                ],
              ),
            ),
          ),
        );
      },
    );
  }
`
and sorry for wrong button :) reopening again.

**Comment by kuhnroyal** [comment] 2020-02-28 15:11
I am running into this as well. Somehow the `hideableKey.currentState` is null.

```
════════ (7) Exception caught by widgets library ═══════════════════════════════════════════════════
The getter 'isInTree' was called on null.
Receiver: null
Tried calling: isInTree
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (8) Exception caught by animation library ═════════════════════════════════════════════════
The setter 'placeholderSize=' was called on null.
Receiver: null
Tried calling: placeholderSize=null
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by suztomo** [comment] 2020-02-28 15:18
This error happened to me when I delete the widget that called OpenContainer before closing OpenContainer. To be more exact, I observed this when the deleted widget was the last item in ListView.

**Comment by kuhnroyal** [comment] 2020-02-28 15:36
I kind of figured out the problem for my case but unsure what to do about it.
I have a list that is built with a `StreamBuilder` from the sqlite database. I use `OpenContainer` around the `ListTile` to open a detail view. If I just close the detail view again, everything is fine but if I edit the detail entity and save it to the database, and then go back, this error happens.

The cause is that the `StreamBuilder` of my list is rebuilding due to the database save and all the `OpenContainer`s in the list get rebuild as well.

**Comment by RohanKapurDEV** [comment] 2020-03-12 04:21
I'm having a similar problem. My closed state builder returns a simple FAB while the open builder returns a new page defined elsewhere. 

Every time tab the FAB, the transition animates to the next page just fine but when I go back I get the error message below in the terminal, a red error screen in the app (for about 1 second) and then it transitions to the page i was previously at but without the animation.

Code below:

```dart
Scaffold buildMainView(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      floatingActionButton: OpenContainer(
        transitionType: _transitionType,
        openBuilder: (BuildContext context, VoidCallback _) {
          return ActionsView();
        },
        closedElevation: 6.0,
        closedShape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.all(
            Radius.circular(100),
          ),
        ),
        closedBuilder: (BuildContext context, VoidCallback _) {
          return FloatingActionButton(
            child: Icon(Icons.add),
          );
        },
      ),
      body: NestedScrollView(
        controller: _scrollController,
        headerSliverBuilder: (BuildContext _, bool boxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              backgroundColor: Colors.black,
              leading: IconButton(
                icon: Icon(Icons.notifications),
                onPressed: () {},
              ),
              actions: <Widget>[
                IconButton(
                  icon: Icon(Icons.insert_chart),
                  onPressed: () {},
                )
              ],
              pinned: true,
              forceElevated: boxIsScrolled,
              expandedHeight: MediaQuery.of(context).size.width / 1.75,
              flexibleSpace: FlexibleSpaceBar(
                title: Text(
                  "-----",
                  style: GoogleFonts.rubik(),
                ),
                centerTitle: true,
                titlePadding: EdgeInsets.fromLTRB(0, 0, 0, 60),
                collapseMode: CollapseMode.pin,
                background: Padding(
                  padding: EdgeInsets.only(bottom: 30),
                  child: Center(
                    child: Text(
                      '------',
                      style: GoogleFonts.rubik(
                        textStyle: TextStyle(color: Colors.white, fontSize: 20),
                      ),
                    ),
                  ),
                ),
              ),
              bottom: TabBar(
                controller: _tabController,
                labelStyle: GoogleFonts.rubik(),
                indicator: UnderlineTabIndicator(
                  insets: EdgeInsets.fromLTRB(60, 0, 60, 0),
                  borderSide: const BorderSide(width: 3.0, color: Colors.blue),
                ),
                tabs: <Widget>[
                  Tab(
                    text: 'Activity',
                  ),
                  Tab(
                    text: 'Security',
                  ),
                ],
              ),
            )
          ];
        },
        body: ClipRRect(
          borderRadius: BorderRadius.only(
              topLeft: Radius.circular(20), topRight: Radius.circular(20)),
          child: TabBarView(
            controller: _tabController,
            .....
          ),
        ),
      ),
    );
```


The error I get:

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building AnimatedBuilder(animation: AnimationController#fc37a(◀ 1.000; for _OpenContainerRoute)➩ProxyAnimation, dirty, state: _AnimatedState#d6004):
The getter 'isInTree' was called on null.
Receiver: null
Tried calling: isInTree

The relevant error-causing widget was: 
  MaterialApp file:///E:/Flutter%20Projects/paymint/lib/main.dart:49:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _OpenContainerRoute.buildPage.<anonymous closure> (package:animations/src/open_container.dart:738:63)
#2      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1012:12)
#3      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:178:48)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
The getter 'isInTree' was called on null.
Receiver: null
Tried calling: isInTree
The relevant error-causing widget was: 
  MaterialApp file:///E:/Flutter%20Projects/paymint/lib/main.dart:49:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by animation library ═════════════════════════════════════════════════
The setter 'placeholderSize=' was called on null.
Receiver: null
Tried calling: placeholderSize=null
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Does anyone know why this is happening? The ActionsView animates in just fine. But when I go back, i get a red error screen for a second (maybe less), the above message in the terminal, but then my app does close the openContainer, but with no animation. Just an abrupt change back to the original.

Help would be much appreciated!!

**Comment by RohanKapurDEV** [comment] 2020-03-12 06:56
Ok guys i think I found the fix. The problem was that the widget that had the FAB in it was not originally pushed by the Navigator as a route. Once I added that widget as a named route and pushed to it instead of just returning it, the OpenContainer stopped giving me those errors.

So to conclude, when you have a widget that uses OpenContainer, make sure that the overall widget that uses the OpenContainer is pushed through a Navigator instead of a simple return statement.

Hope that helped!!!

**Comment by suztomo** [comment] 2020-03-12 23:56
@RohanKapurDEV Thank you for sharing the solution. To confirm my understanding, would you be willing to share the code diff in your example?

**Comment by mcgowan** [comment] 2020-03-13 22:20
I started receiving this exception after I switched out the ListView for the ReorderableListView. Also, it only occurs when running my app on iOS, not Android. Yes, please do share your code, thanks Rohan.

**Comment by RohanKapurDEV** [comment] 2020-03-13 22:39
Right, so the key insight for my fix came from this great medium article someone wrote specifically about this package: https://medium.com/flutter-nyc/a-deep-dive-into-the-flutter-animations-package-3e26b10c43c1

So the explanation for the container transform in the article section states the following:

"It is important to note that the OpenContainer widget must be used in a context with a Navigator. When it transitions from the closed widget to the open widget, it pushes a new PageRoute onto its closest ancestor Navigator. It then grows the open widget to fill the entire size of this Navigator. Most Navigators are full-screen, but don’t have to be."

So what was my mistake? Well, I was pushing the widget the contained the code snippet I posted above as a return statement instead of pushing the entire thing using a Navigator. I didn't have to change the snippet I posted above at all.

The snippet I posted was a function that returned a widget. All I had to do was make sure the Stateless widget whose build function used the code above was pushed into the main view of the app using a Navigator like so:

```dart
Navigator.of(context).pushNamed(context, '\routeNameOfTheWidgetThatHasAnOpenContainerInsideIt')
```

I know this is unclear but I'm not posting my code because once again, ALL i had to do was NOT update the portion of my code with the openContainer inside it and INSTEAD, I just pushed the top level Scaffold that contained the snippet I posted via the Navigator. Before this, that widget was pushed onto the main screen via a simple return MyWidget() statement. Now it's pushed via the Navigator.

**Comment by suztomo** [comment] 2020-03-13 23:50
@RohanKapurDEV Thank you for explanation. As I use Navigator already, my problem seems different than yours. Thanks anyway.

**Comment by mcgowan** [comment] 2020-03-14 00:04
Thanks @RohanKapurDEV, my problem also proved to be something different. I too was already using the Navigator, however I was using the flutter beta channel on my mac and the dev channel on windows. I no longer receive this exception on my mac since upgrading to v1.15.21 on the dev channel.

**Comment by britannio** [comment] 2020-03-22 14:32
> I kind of figured out the problem for my case but unsure what to do about it.
> I have a list that is built with a `StreamBuilder` from the sqlite database. I use `OpenContainer` around the `ListTile` to open a detail view. If I just close the detail view again, everything is fine but if I edit the detail entity and save it to the database, and then go back, this error happens.
> 
> The cause is that the `StreamBuilder` of my list is rebuilding due to the database save and all the `OpenContainer`s in the list get rebuild as well.
> 
> Edit:
> Somehow this does not happen with the first list item. I tried to give the list items keys but that didn't help.

Did you find a fix?

**Comment by kuhnroyal** [comment] 2020-03-22 17:09
I copied most of the code and made it a NamedRoute, just added null check at the offending places and it seems to work so far.

**Comment by goderbauer** [comment] 2020-03-30 17:24
Looks like there are a couple of different issues discussed in this bug. Can you please open separate issues for each bug and post a minimal, but fully runnable code sample with it that reproduces the problem? That would help us in fixing these problems. 

I am going to close this issue for now since it is not vary actionable right now for us.

**Closed by goderbauer** 2020-03-30 17:24 UTC
Labels: customer: crowd, framework, p: animations, package
