### ISSUE TITLE
`SelectionArea` multiline copy-paste pastes all text in one line (web only)

### ISSUE THREAD

**Issue by elliette** [flutter/flutter#131077] opened 2023-07-21 17:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Note: This is reproducible when running in the browser and using the browser's native context menus. This is not reproducible on non-web devices. 

This is reproducible using the example in the `SelectionArea` documentation: https://api.flutter.dev/flutter/material/SelectionArea-class.html

![Screenshot 2023-07-21 at 10 45 40 AM](https://github.com/flutter/flutter/assets/21270878/76979271-514f-415f-a88e-576621a4752b)

1. Select the multiline text
2. Copy the text
3. Paste it somewhere

### Expected results

I would expect the multiline text to be pasted with line breaks, e.g.:

```
Row 1
Row 2
Row 3
```

### Actual results

The text is pasted with no line breaks and no spaces where the line breaks should be:

```
Row 1Row 2Row 3
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [SelectionArea].

void main() => runApp(const SelectionAreaExampleApp());

class SelectionAreaExampleApp extends StatelessWidget {
  const SelectionAreaExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SelectionArea(
        child: Scaffold(
          appBar: AppBar(title: const Text('SelectionArea Sample')),
          body: const Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text('Row 1'),
                Text('Row 2'),
                Text('Row 3'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

N/A this is reproducible on demo page

**Comment by afriddev** [comment] 2023-07-22 01:29
Use column-edit instead of the multi-line edit mode:

Click the end of the source text.
Shift Alt, click the beginning.
Copy.
Click the end of the destination text.
Shift Alt, click the beginning.
Paste.

**Comment by Renzo-Olivares** [comment] 2023-07-26 19:45
This looks like a duplicate of https://github.com/flutter/flutter/issues/104548. Closing this, but feel free to re-open if this issue is different.

**Closed by Renzo-Olivares** 2023-07-26 19:45 UTC
Labels: framework, f: material design, platform-web, f: selection, team-web
