### ISSUE TITLE
Click events not registering in clipped region of Stack widget

### ISSUE THREAD

**Issue by MaundoMoru** [flutter/flutter#141549] opened 2024-01-15 06:32 UTC
### Use case

Expected Behavior:
Click events should be registered in the entire area of the GestureDetector, including the clipped region, allowing for interaction with the container.

Actual Behavior:
Click events are not detected in the clipped region. Taps outside the clipped area work as expected.

### Proposal

Expected Behavior:
Click events should be registered in the entire area of the GestureDetector, including the clipped region, allowing for interaction with the container.

Actual Behavior:
Click events are not detected in the clipped region. Taps outside the clipped area work as expected.

**Comment by MaundoMoru** [comment] 2024-01-15 06:32
Expected Behavior:
Click events should be registered in the entire area of the GestureDetector, including the clipped region, allowing for interaction with the container.

Actual Behavior:
Click events are not detected in the clipped region. Taps outside the clipped area work as expected.

**Comment by MaundoMoru** [comment] 2024-01-15 06:32
N/A

**Comment by dam-ease** [comment] 2024-01-15 11:25
Thanks for filing this @MaundoMoru 
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you

**Comment by MaundoMoru** [comment] 2024-01-18 09:05
Stack(
              clipBehavior: Clip.none,
              children: [
                Container(
                  decoration: const BoxDecoration(color: Color(0xFF008080)),
                  height: 150,
                  width: MediaQuery.of(context).size.width,
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          'My accounts',
                          style: GoogleFonts.lexend(
                            textStyle: const TextStyle(
                                color: Colors.white70, fontSize: 17),
                          ),
                        ),
                        Row(
                          children: [
                            const Icon(
                              Icons.toggle_off,
                              color: Colors.white,
                              size: 30,
                            ),
                            const SizedBox(
                              width: 12,
                            ),
                            const SizedBox(
                              width: 8,
                            )
                          ],
                        )
                      ],
                    ),
                  ),
                ),
                Positioned(
                  top: 100,
                  left: 0,
                  right: 0,
                  child: Align(
                    alignment: Alignment.bottomCenter,
                    child: Container(
                      width: MediaQuery.of(context).size.width * 0.9,
                      decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(10),
                          color: Colors.transparent),
                      height: 100,
                      child: ListView.separated(
                        physics: const AlwaysScrollableScrollPhysics(),
                        padding: EdgeInsets.zero,
                        shrinkWrap: true,
                        scrollDirection: Axis.horizontal,
                        itemCount: menus.length,
                        separatorBuilder: (context, index) {
                          return Container(
                            height: 8,
                          );
                        },
                        itemBuilder: (context, index) {
                          var menu = menus[index];
                          return GestureDetector(
                            onTap: () {
                              print('Hello');
                            },
                            child: Container(
                              height: 100,
                              width: MediaQuery.of(context).size.width * 0.9,
                              decoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(10),
                                  color: Colors.white,
                                  border:
                                      Border.all(color: Colors.grey.shade300)),
                              child: Padding(
                                padding: const EdgeInsets.all(8.0),
                                child: Row(
                                  mainAxisAlignment:
                                      MainAxisAlignment.spaceBetween,
                                  children: [
                                    Column(
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      mainAxisAlignment:
                                          MainAxisAlignment.center,
                                      children: [
                                        Text('data');
                                      ],
                                    ),
                                    Icon(
                                      Icons.arrow_forward_ios,
                                      color: Colors.grey.shade300,
                                    )
                                  ],
                                ),
                              ),
                            ),
                          );
                        },
                      ),
                    ),
                  ),
                ),
              ],
            ),

**Comment by MaundoMoru** [comment] 2024-01-18 09:06
```
  Stack(
              clipBehavior: Clip.none,
              children: [
                Container(
                  decoration: const BoxDecoration(color: Color(0xFF008080)),
                  height: 150,
                  width: MediaQuery.of(context).size.width,
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          'My accounts',
                          style: GoogleFonts.lexend(
                            textStyle: const TextStyle(
                                color: Colors.white70, fontSize: 17),
                          ),
                        ),
                        Row(
                          children: [
                            const Icon(
                              Icons.toggle_off,
                              color: Colors.white,
                              size: 30,
                            ),
                            const SizedBox(
                              width: 12,
                            ),
                            const SizedBox(
                              width: 8,
                            )
                          ],
                        )
                      ],
                    ),
                  ),
                ),
                Positioned(
                  top: 100,
                  left: 0,
                  right: 0,
                  child: Align(
                    alignment: Alignment.bottomCenter,
                    child: Container(
                      width: MediaQuery.of(context).size.width * 0.9,
                      decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(10),
                          color: Colors.transparent),
                      height: 100,
                      child: ListView.separated(
                        physics: const AlwaysScrollableScrollPhysics(),
                        padding: EdgeInsets.zero,
                        shrinkWrap: true,
                        scrollDirection: Axis.horizontal,
                        itemCount: menus.length,
                        separatorBuilder: (context, index) {
                          return Container(
                            height: 8,
                          );
                        },
                        itemBuilder: (context, index) {
                          var menu = menus[index];
                          return GestureDetector(
                            onTap: () {
                              print('Hello');
                            },
                            child: Container(
                              height: 100,
                              width: MediaQuery.of(context).size.width * 0.9,
                              decoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(10),
                                  color: Colors.white,
                                  border:
                                      Border.all(color: Colors.grey.shade300)),
                              child: Padding(
                                padding: const EdgeInsets.all(8.0),
                                child: Row(
                                  mainAxisAlignment:
                                      MainAxisAlignment.spaceBetween,
                                  children: [
                                    Column(
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      mainAxisAlignment:
                                          MainAxisAlignment.center,
                                      children: [
                                        Text('data');
                                      ],
                                    ),
                                    Icon(
                                      Icons.arrow_forward_ios,
                                      color: Colors.grey.shade300,
                                    )
                                  ],
                                ),
                              ),
                            ),
                          );
                        },
                      ),
                    ),
                  ),
                ),
              ],
            ),
```

**Comment by dam-ease** [comment] 2024-01-18 14:00
Thanks for your response @MaundoMoru.
I can reproduce this on my end as well but I see this is similar/related to https://github.com/flutter/flutter/issues/104519 which is a duplicate of https://github.com/flutter/flutter/issues/75747. Can you check these out as well to see if they are similar to yours?

**Closed** 2024-02-08 14:08 UTC
Labels: waiting for customer response, in triage
