### ISSUE TITLE
availableCameras

### ISSUE THREAD

**Issue by geannib** [flutter/flutter#149135] opened 2024-05-27 14:44 UTC
### Steps to reproduce

1. create a demo app base on the exampe from dev flutter
2. call availableCameras and display the result
3.

### Expected results

All the available cameras ( in my exemple samsung galaxy ultra 24 has many cameras)

### Actual results

I got only 4, looks like generic 2 front and 2 back cameras
I tried on few other phones and I get the same result

### Code sample

<details open><summary>Code sample</summary>

```dart
 availableCameras().then((cameras) => allCameras = cameras)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2024-05-28 07:39
Closing as duplicate of https://github.com/flutter/flutter/issues/91247

**Closed by darshankawar** 2024-05-28 07:39 UTC
Labels: in triage
