### ISSUE TITLE
Listview scrolling with mouse wheel on windows is not smooth

### ISSUE THREAD

**Issue by imchivaa** [flutter/flutter#78634] opened 2021-03-19 18:27 UTC
Hi Flutter Team,

I found an issue with listview scrolling on windows build. The scrolling using mouse wheel isn't smooth.

## Steps to Reproduce
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.separated(
        itemCount: 1000,
        itemBuilder: (context, index) {
          return ListTile(
            title: Text('row $index'),
          );
        },
        separatorBuilder: (context, index) {
          return Divider();
        },
      ),
    );
  }
```

**Expected results:**  Scrolling with mouse wheel should be the same way as scrolling using the mousepad, the fluid smooth scrolling animation isn't there

**Actual results:**  It doesn't scroll the list smoothly. The scroll stops immediately instead of gradually stop.

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.18363.1440], locale en-MY)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (8 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\HP\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\New folder\IntelliJ IDEA Community Edition 2020.2.3
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1440]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!

```

</details>

**Comment by xkeyC** [comment] 2021-03-20 08:05
Yes, I think this problem needs improvement.

**Comment by imchivaa** [comment] 2021-03-20 16:02
I would like to know if my implementation have issues or just a missing feature from flutter for windows itself. From the implementation, it works just fine on mobile and touchpad when scrolling, but not with mouse wheel. Hope to get some advice and explaination on this issue.

Possible duplication of any existing reported issues?

**Comment by nt4f04uNd** [comment] 2021-03-21 03:04
duplicate of https://github.com/flutter/flutter/issues/32120

**Closed** 2021-03-22 03:05 UTC
