### ISSUE TITLE
TextField with lots of characters hangs the app

### ISSUE THREAD

**Issue by Maruf-Elsa** [flutter/flutter#159661] opened 2024-12-02 10:52 UTC
### Steps to reproduce

When I try to add more than 35 characters as email in TextField or TextFormField, the app freezes for a few seconds. This happens only in real devices of Android & iOS. 
Without the inputFormatters the app just freezes permanently. 
With inputFormatters
```dart
inputFormatters: [
 LengthLimitingTextInputFormatter(100),
  ],
```
the app freezes for a few seconds and then types the rest of the text.

```dart
                              TextField(
                              controller: emailController,
                              inputFormatters: [
                                LengthLimitingTextInputFormatter(100),
                              ],
                              style: DsTextStyles.body.copyWith(
                                color: DsColors.white,
                              ),
                              decoration: InputDecoration(
                                hintText: S.of(context).enter_your_email_nova,
                                hintStyle: DsTextStyles.body.copyWith(
                                  color: DsColors.white.withOpacity(0.6),
                                ),
                                border: OutlineInputBorder(
                                  borderRadius:
                                      BorderRadius.circular(DsRadii.x3),
                                  borderSide: BorderSide.none,
                                ),
                              ),
                              onChanged: (email) =>
                                  bloc.onEmailChanged.add(email),
                            ),
```

### Expected results

TextField/TextFormField should take as many characters as required without getting the app frozen and not require inputFormatters to get it unstuck after a delay.

Email used - 24097760@student.hoangmaistarschool.com

### Actual results

App gets stuck after long characters are added for email.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Screen(),
    );
  }
}

class Screen extends StatelessWidget {
  final TextEditingController emailController = TextEditingController();
  Screen({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Screen'),
      ),
      body: Center(
        child: TextField(
          controller: emailController,
          inputFormatters: [
            LengthLimitingTextInputFormatter(100),
          ],
          decoration: InputDecoration(
            hintText: 'Enter your email',
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide.none,
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/1c00fdf3-27ac-45a4-a8e0-3902174291c8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.1.2 23B92 darwin-arm64, locale en-IN)
    • Flutter version 3.24.0 on channel stable at /Users/marufhassan/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (4 months ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/marufhassan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/marufhassan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.95.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-12-02 13:05
Hi @Maruf-Elsa, please provide a complete minimal reproducible code sample without any third-party packages so that we can properly investigate this.

Please also upgrade to the latest version of flutter stable (3.24.5) to see if you still experience this. 

Thank you

**Comment by Maruf-Elsa** [comment] 2024-12-04 06:35
@danagbemava-nc I have edited and updated the minimum the issue with the minimum reproducable code. The issue only happens in real devices. I have tested it in iPhone 14 & Xiaomi 11i 5G.

**Comment by danagbemava-nc** [comment] 2024-12-05 06:24
Hi @Maruf-Elsa, I can't seem to reproduce the issue with the code sample you provided above. I tested on my iPhone XS running iOS 18.1.1 and my Pixel 7 running android 15. See the recordings below. Is there any additional information you can provide? 

| iPhone XS | Pixel 7 | 
| -- | -- |
| <video src="https://github.com/user-attachments/assets/2fc0ef1e-da2d-4397-ba31-7ba8ab86a273" /> | <video src="https://github.com/user-attachments/assets/466283cc-a9fa-4cad-a54c-334cb59bebe3" /> |

**Comment by sugith10** [comment] 2024-12-10 12:58
The issue faced by @Maruf-Elsa was caused by the computationally intensive regex validations performed in the onChanged method:

`onChanged: (email) => bloc.onEmailChanged.add(email)`

As the email length increased, handling the complex regex validation literally caused the app to halt. I hope @Maruf-Elsa can close this issue.

**Comment by Maruf-Elsa** [comment] 2024-12-12 06:17
Thank you @sugith10. It was the reason for the issue and by reducing the regex validation, it helped solve the issue for now. 

@danagbemava-nc Flutter should be able to handle complex regex without hanging the app, can the Flutter team look into this. 

Complex regex hanging the app - `r'^[_A-Za-z0-9-+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$'`
Simple working regex for email- `r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'`

**Comment by danagbemava-nc** [comment] 2024-12-12 06:49
There's an issue tracking allowing the textfield to handle lots of text in https://github.com/flutter/flutter/issues/90063. 

Kindly follow up there for updates. While that issue deals with thousands of text and yours has a few, I believe because of the complexity of the regex, they produce the same effect. 

Closing this in favor of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-12-12 06:49 UTC
Labels: in triage
