### ISSUE TITLE
Add axis to ToggleButtons

### ISSUE THREAD

**Issue by LefebvreIlyas** [flutter/flutter#70569] opened 2020-11-15 14:48 UTC
It would be interesting to add an axis parameter to the ToggleButtons widget, which would allow the buttons to be displayed in row (as is currently the case) or in column if necessary.

**Comment by MrBirb** [comment] 2020-11-15 22:25
Looks like a duplicate of [#63871](https://github.com/flutter/flutter/issues/63871)

**Comment by pedromassangocode** [comment] 2020-11-16 08:08
Closing as duplicate of https://github.com/flutter/flutter/issues/63871. Please follow up on that issue for updates.

**Closed by pedromassangocode** 2020-11-16 08:08 UTC

**Comment by LefebvreIlyas** [comment] 2020-11-16 11:35
Hello @MrBirb, @pedromassangocode

This is not really a duplicate, because #63871 suggests using Wrap instead of Row. But this PR #63880 (which has been closed) is a perfect answer to this issue.

**Comment by xu-baolin** [comment] 2020-11-17 02:30
@LefebvreIlyas #70670 This PR may be able to meet your needs ：）

**Comment by LefebvreIlyas** [comment] 2020-11-17 09:30
@xu-baolin Exactly! Thank you very much for all your work! 🚀
