### ISSUE TITLE
Android Integration tests on firebase test lab are timing out

### ISSUE THREAD

**Issue by prolificcoder** [flutter/flutter#85728] opened 2021-07-01 21:08 UTC
## Steps to Reproduce

_Sorry, I didn't follow the template because it a specific issue with my application on running tests_

1. Run the test locally with `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/goals_test.dart` and see it pass multiple times
2. Create the android binaries as described in [here](https://flutter.dev/docs/testing/integration-tests#uploading-an-android-apk) for running tests in firebase test lab
3. Upload the binaries to FTL and do run test. 

**Expected results:** 

Either a success or fail from the test 
Or some useful error

**Actual results:** 

The app doesn't boot after 5 minutes and times out
See this error several times in the logs
`Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?`
starting with 
```
06-30 23:56:39.113: W/ClassPathPackageInfoSource(11196): Cannot load class. Make sure it is in your apk. Class name: 'androidx.room.paging.LimitOffsetDataSource'. Message: androidx.room.paging.LimitOffsetDataSource
06-30 23:56:39.113: W/ClassPathPackageInfoSource(11196): java.lang.ClassNotFoundException: androidx.room.paging.LimitOffsetDataSource
```
But not sure if this is the cause of the error. 

Also I am able to run tests on FTL from example applciation with no problems

**Additional details** 

I spoke with developer on the FTL dev team and they suggested to open an issue here. 
Our app is not null safe and it has mparticle library as a dependency 

<details>
  <summary>Logs</summary>
  
Full logs from FTL: 
[timeout_logcat.txt](https://github.com/flutter/flutter/files/6750773/timeout_logcat.txt)

Flutter doctor results
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.1.4)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)
```

</details>

**Comment by TahaTesser** [comment] 2021-07-02 14:52
Hi @prolificcoder 
Thanks for filing the issue

When I tried to reproduce the issue and upload the test,  it simply runs forever, never stops (not if it is firebase or test build)
In your testing, to see the test stopping? what is the behaviour after uploading the test.

**Comment by prolificcoder** [comment] 2021-07-02 16:58
@TahaTesser how were you able to reproduce? Is it locally or on fire base test lab? 
I did not run the test locally through android but only through 
`flutter drive`

Do you think i can run those tests with something like`./gradlew connectedTest` ?

**Comment by TahaTesser** [comment] 2021-07-05 08:04
@prolificcoder 

> Run the test locally with flutter drive --driver=test_driver/integration_test.dart --target=integration_test/goals_test.dart and see it pass multiple times


I have followed your steps, ran the test locally then [submitted ](https://flutter.dev/docs/testing/integration-tests#uploading-an-android-apk)it to the test lab, it runs forever on the Test lab 


Please explain the steps from scratch and let me know what behavior you see in the test lab?

**Comment by eseidelGoogle** [comment] 2021-07-07 17:26
It's hard to tell what the actual error is.  There is a ton of class loading stuff, suggesting that possible that AAR/APK isn't being generated correctly from gradel?

06-30 23:56:39.113: W/ClassPathPackageInfoSource(11196): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.paging.PositionalDataSource" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~gDoST-AO6odAhgVSc8X8gg==/com.sofi.sofi_x_flutter.test-rlCH0EXkyClsvZcPmpQcGg==/base.apk", zip file "/data/app/~~hnC8rhU9v6SHTkO4uHUk3Q==/com.sofi.sofi_x_flutter-CELlI2lDfKAqcop-7jr0XQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~gDoST-AO6odAhgVSc8X8gg==/com.sofi.sofi_x_flutter.test-rlCH0EXkyClsvZcPmpQcGg==/lib/x86, /data/app/~~hnC8rhU9v6SHTkO4uHUk3Q==/com.sofi.sofi_x_flutter-CELlI2lDfKAqcop-7jr0XQ==/lib/x86, /data/app/~~gDoST-AO6odAhgVSc8X8gg==/com.sofi.sofi_x_flutter.test-rlCH0EXkyClsvZcPmpQcGg==/base.apk!/lib/x86, /data/app/~~hnC8rhU9v6SHTkO4uHUk3Q==/com.sofi.sofi_x_flutter-CELlI2lDfKAqcop-7jr0XQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]

If the AAR is "thin" and doesn't contain whatever architecture of Android the FTL uses, that could explain some of this?

**Comment by csells** [comment] 2021-07-07 17:31
cc @dnfield

**Comment by eseidelGoogle** [comment] 2021-07-07 18:02
I suggest diffing the log with a log which works.  That log is quite large and it's hard to tell what might be the parts which are wrong. :)

**Comment by prolificcoder** [comment] 2021-07-07 18:05
Thank you for looking more into this issue. 


I want to summarize the things I have tried so far with no difference in behaviour
1. Physical device or virtual 
2. API 30 or API 29
3. Change minsdk to 29 from 16
4. Remove datadog library (it was giving problems in a different context)

Note that this is not null safe but we are in flutter 2.2, also we are going with Add-To-App strategy but I think this test should be independent of that because it can locally just fine on the standalone app.

**Comment by eseidelGoogle** [comment] 2021-07-07 18:48
I might try reducing the app until something works. :). Or trying a test app on the same account.  There is some indication in the logs that it might be having trouble loading classes (e.g. that the apk might be compiled for the wrong architecture or missing a piece or something), there are also various other Errors ("E/") and warnings.  None of which are obviously the answer to me w/o more context (e.g. trying other examples, seeing them work and comparing the logs).  Hope that helps!

**Comment by dnfield** [comment] 2021-07-07 19:38
@blasten might know more about this - it looks like you're submitting an app to FTL that's trying to load `androidx.room.paging.LimitOffsetDataSource`, but it's not present in the APK. It's possible there's some (proguard? R8?) rule misconfigured/missing or some annotation on that class missing which is causing it to get stripped from your application.

You may want to try running this locally and see if you're getting the same error - I suspect you will find that you are and that this is not really a firebase testlab issue.

**Comment by TahaTesser** [comment] 2021-07-08 14:20
Hi @dnfield 
I have spent time this figuring out, I can reproduce an issue with `integration_test` (not sure if it is same) running on Firebase test lab using a regular Flutter app.  Following the steps as  https://github.com/flutter/flutter/issues/85728#issue-935215659 

Steps to reproduce 
1. Create a regular project on the latest `stable, 2.2.3` 
2. Add `integration_test`  dependency, add a very simple test to find app title 
```dart
  testWidgets('Find App Title', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());

    expect(find.text('Material App Bar'), findsOneWidget);
  });
```
3. Run the test locally with `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart`
4. Follow [instructions](https://flutter.dev/docs/testing/integration-tests#uploading-an-android-apk) to upload an APK to Firebase Test Lab
5. Upload the  APK, test passes. check out test screenshots and video, logs

Firebase test lab says tests ha passed, video is only around a minute, screenshots shows the test started and app was running (can see home screen)

Now the make the little bit more complex, for which I simply added another screen to the with `google_maps_flutter` example. 
6. Add another to navigate to this maps page, click a button and navigate back to home screen
```dart
  testWidgets('Test Minimal Googel Maps Sample', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());

    final mapsSample = find.text('Maps Minimimal');
    expect(mapsSample, findsOneWidget);
    await tester.tap(mapsSample);
    await tester.pumpAndSettle();
    await tester.pump(new Duration(seconds: 5));

    final fab = find.byKey(Key('fabKey'));
    expect(fab, findsOneWidget);
    await tester.tap(fab);
    await tester.pumpAndSettle();
    await tester.pump(new Duration(seconds: 3));

    final back = find.byTooltip('Back');
    expect(back, findsOneWidget);
    await tester.tap(back);
    await tester.pumpAndSettle();

    expect(mapsSample, findsOneWidget);
  });
```
7. Repeat step 3, notice locally test passes, navigates maps screen and navigates back every time
8. Repeat step 4. After test finishes, Firebase Test lab shows tests passed
Check out test results  

- Screenshots shows the app was stuck at "Test starting..." for entire time 

<details> 
<summary>preview</summary> 
<img width="1424" alt="Screenshot 2021-07-08 at 4 23 22 PM" src="https://user-images.githubusercontent.com/48603081/124937291-ea99a080-e00f-11eb-8a76-68f5ff6eabcd.png">



</details>

- Video results shows same thing, video length is 5 min (which is default timeout for FTL), it's just 5 min of `monkey test taps` 
- No actual `integration_test` done for entire duration of the test. 

<details> 
<summary>preview</summary>


https://user-images.githubusercontent.com/48603081/124937405-0ac95f80-e010-11eb-8caf-750ab54a5770.mp4

 


</details>

- When checking logcat from this test, there are somany error messages
[logcat.zip](https://github.com/flutter/flutter/files/6785158/logcat.zip)






@prolificcoder 
Is this similar to your issue? 

>  we are going with Add-To-App strategy

As mentioned in https://github.com/flutter/flutter/issues/85728#issuecomment-875878714, this could be something in your app  and if you can isolate it to be related, regular flutter app or add to app. please provide. a complete reproducible code sample (if add to app, please provide a sample repository with example module and example native)  and steps to reproduce the issue 

Thank you

**Comment by dnfield** [comment] 2021-07-08 15:45
@TahaTesser - I think you're describing a different bug than the OP, though it's hard to tell because the OP has not provided a complete reproduction.

The errors in your logs are different, and many of them are ignorable artifacts from FTL. However, your test actually threw failures - if you grep that log for `EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK` you can see them. @jiahaog, do you know what's going on there? Specifically:

```
07-08 06:15:07.666: I/flutter(17981): (The following exception is now available via WidgetTester.takeException:)
07-08 06:15:07.726: I/flutter(17981): â•â•â•¡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK â•žâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.726: I/flutter(17981): The following assertion was thrown running a test:
07-08 06:15:07.726: I/flutter(17981): 'package:flutter_test/src/binding.dart': Failed assertion: line 1551 pos 16: 'hitTestResult !=
07-08 06:15:07.726: I/flutter(17981): null': is not true.
07-08 06:15:07.726: I/flutter(17981): When the exception was thrown, this was the stack:
07-08 06:15:07.726: I/flutter(17981): #2      LiveTestWidgetsFlutterBinding.dispatchEvent (package:flutter_test/src/binding.dart:1551:16)
07-08 06:15:07.726: I/flutter(17981): #3      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
07-08 06:15:07.726: I/flutter(17981): #4      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
07-08 06:15:07.726: I/flutter(17981): #5      TestWidgetsFlutterBinding.handlePointerEvent (package:flutter_test/src/binding.dart:507:13)
07-08 06:15:07.726: I/flutter(17981): #6      LiveTestWidgetsFlutterBinding.handlePointerEvent (package:flutter_test/src/binding.dart:1539:17)
07-08 06:15:07.726: I/flutter(17981): #7      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
07-08 06:15:07.726: I/flutter(17981): #8      GestureBinding.unlocked (package:flutter/src/gestures/binding.dart:265:5)
07-08 06:15:07.726: I/flutter(17981): #9      BindingBase.lockEvents.<anonymous closure> (package:flutter/src/foundation/binding.dart:304:9)
07-08 06:15:07.726: I/flutter(17981): #19     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart)
07-08 06:15:07.726: I/flutter(17981): <asynchronous suspension>
07-08 06:15:07.726: I/flutter(17981): (elided 11 frames from class _AssertionError, dart:async, dart:async-patch, and package:stack_trace)
07-08 06:15:07.726: I/flutter(17981): The test description was:
07-08 06:15:07.726: I/flutter(17981):   Find App Title
07-08 06:15:07.726: I/flutter(17981): â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.726: I/flutter(17981): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
07-08 06:15:07.743: I/flutter(17981): â•â•â•¡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK â•žâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.743: I/flutter(17981): The following assertion was thrown running a test:
07-08 06:15:07.743: I/flutter(17981): 'package:flutter_test/src/binding.dart': Failed assertion: line 1551 pos 16: 'hitTestResult !=
07-08 06:15:07.743: I/flutter(17981): null': is not true.
07-08 06:15:07.743: I/flutter(17981): When the exception was thrown, this was the stack:
07-08 06:15:07.744: I/flutter(17981): #2      LiveTestWidgetsFlutterBinding.dispatchEvent (package:flutter_test/src/binding.dart:1551:16)
07-08 06:15:07.744: I/flutter(17981): #3      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
07-08 06:15:07.744: I/flutter(17981): #4      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
07-08 06:15:07.744: I/flutter(17981): #5      TestWidgetsFlutterBinding.handlePointerEvent (package:flutter_test/src/binding.dart:507:13)
07-08 06:15:07.744: I/flutter(17981): #6      LiveTestWidgetsFlutterBinding.handlePointerEvent (package:flutter_test/src/binding.dart:1539:17)
07-08 06:15:07.744: I/flutter(17981): #7      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
07-08 06:15:07.744: I/flutter(17981): #8      GestureBinding.unlocked (package:flutter/src/gestures/binding.dart:265:5)
07-08 06:15:07.744: I/flutter(17981): #9      BindingBase.lockEvents.<anonymous closure> (package:flutter/src/foundation/binding.dart:304:9)
07-08 06:15:07.744: I/flutter(17981): #19     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart)
07-08 06:15:07.744: I/flutter(17981): <asynchronous suspension>
07-08 06:15:07.744: I/flutter(17981): (elided 11 frames from class _AssertionError, dart:async, dart:async-patch, and package:stack_trace)
07-08 06:15:07.744: I/flutter(17981): The test description was:
07-08 06:15:07.744: I/flutter(17981):   Find App Title
07-08 06:15:07.744: I/flutter(17981): â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.748: I/flutter(17981): 00:01 +0: Find App Title [E]
07-08 06:15:07.749: I/flutter(17981):   Test failed. See exception logs above.
07-08 06:15:07.749: I/flutter(17981):   The test description was: Find App Title
07-08 06:15:07.750: I/flutter(17981):   
07-08 06:15:07.766: I/flutter(17981): â•â•â•¡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK â•žâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.766: I/flutter(17981): The following assertion was thrown running a test (but after the test had completed):
07-08 06:15:07.766: I/flutter(17981): 'package:flutter_test/src/binding.dart': Failed assertion: line 809 pos 12: 'inTest': is not true.
07-08 06:15:07.766: I/flutter(17981): When the exception was thrown, this was the stack:
07-08 06:15:07.766: I/flutter(17981): #2      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:809:12)
07-08 06:15:07.766: I/flutter(17981): <asynchronous suspension>
07-08 06:15:07.766: I/flutter(17981): (elided 2 frames from class _AssertionError)
07-08 06:15:07.766: I/flutter(17981): ...
07-08 06:15:07.766: I/flutter(17981): â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.767: I/flutter(17981): 00:01 +0 -1: Test Minimal Googel Maps Sample
07-08 06:15:07.787: W/surfaceflinger(642): type=1400 audit(0.0:327): avc: denied { read } for name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=17686 scontext=u:r:surfaceflinger:s0 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0
07-08 06:15:07.789: E/libc(642): Access denied finding property "vendor.debug.egl.swapinterval"
07-08 06:15:07.792: I/flutter(17981): (The following exception is now available via WidgetTester.takeException:)
07-08 06:15:07.791: W/surfaceflinger(642): type=1400 audit(0.0:328): avc: denied { read } for name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=17686 scontext=u:r:surfaceflinger:s0 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0
07-08 06:15:07.792: E/libc(642): Access denied finding property "vendor.debug.egl.swapinterval"
07-08 06:15:07.797: I/flutter(17981): â•â•â•¡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK â•žâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.797: I/flutter(17981): The following _CastError was thrown running a test:
07-08 06:15:07.797: I/flutter(17981): type 'Null' is not a subtype of type 'Element' in type cast
07-08 06:15:07.797: I/flutter(17981): When the exception was thrown, this was the stack:
07-08 06:15:07.797: I/flutter(17981): #0      _CastIterableBase.lastWhere.<anonymous closure> (dart:_internal/cast.dart:53:60)
07-08 06:15:07.797: I/flutter(17981): #1      Iterable.lastWhere (dart:core/iterable.dart:541:38)
07-08 06:15:07.797: I/flutter(17981): #2      _CastIterableBase.lastWhere (dart:_internal/cast.dart:52:15)
07-08 06:15:07.797: I/flutter(17981): #3      WidgetTester.dispatchEvent (package:flutter_test/src/widget_tester.dart:807:26)
07-08 06:15:07.797: I/flutter(17981): #4      LiveTestWidgetsFlutterBinding.dispatchEvent (package:flutter_test/src/binding.dart:1553:32)
07-08 06:15:07.797: I/flutter(17981): #5      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
07-08 06:15:07.797: I/flutter(17981): #6      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
07-08 06:15:07.797: I/flutter(17981): #7      TestWidgetsFlutterBinding.handlePointerEvent (package:flutter_test/src/binding.dart:507:13)
07-08 06:15:07.797: I/flutter(17981): #8      LiveTestWidgetsFlutterBinding.handlePointerEvent (package:flutter_test/src/binding.dart:1539:17)
07-08 06:15:07.797: I/flutter(17981): #9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
07-08 06:15:07.797: I/flutter(17981): #10     GestureBinding.unlocked (package:flutter/src/gestures/binding.dart:265:5)
07-08 06:15:07.797: I/flutter(17981): #11     BindingBase.lockEvents.<anonymous closure> (package:flutter/src/foundation/binding.dart:304:9)
07-08 06:15:07.797: I/flutter(17981): #21     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart)
07-08 06:15:07.797: I/flutter(17981): <asynchronous suspension>
07-08 06:15:07.797: I/flutter(17981): (elided 9 frames from dart:async, dart:async-patch, and package:stack_trace)
07-08 06:15:07.797: I/flutter(17981): The test description was:
07-08 06:15:07.797: I/flutter(17981):   Test Minimal Googel Maps Sample
07-08 06:15:07.797: I/flutter(17981): â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.797: I/flutter(17981): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
07-08 06:15:07.805: I/flutter(17981): â•â•â•¡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK â•žâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.806: I/flutter(17981): The following _CastError was thrown running a test:
07-08 06:15:07.806: I/flutter(17981): type 'Null' is not a subtype of type 'Element' in type cast
07-08 06:15:07.806: I/flutter(17981): When the exception was thrown, this was the stack:
07-08 06:15:07.806: I/flutter(17981): #0      _CastIterableBase.lastWhere.<anonymous closure> (dart:_internal/cast.dart:53:60)
07-08 06:15:07.806: I/flutter(17981): #1      Iterable.lastWhere (dart:core/iterable.dart:541:38)
07-08 06:15:07.806: I/flutter(17981): #2      _CastIterableBase.lastWhere (dart:_internal/cast.dart:52:15)
07-08 06:15:07.806: I/flutter(17981): #3      WidgetTester.dispatchEvent (package:flutter_test/src/widget_tester.dart:807:26)
07-08 06:15:07.806: I/flutter(17981): #4      LiveTestWidgetsFlutterBinding.dispatchEvent (package:flutter_test/src/binding.dart:1553:32)
07-08 06:15:07.806: I/flutter(17981): #5      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
07-08 06:15:07.806: I/flutter(17981): #6      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
07-08 06:15:07.806: I/flutter(17981): #7      TestWidgetsFlutterBinding.handlePointerEvent (package:flutter_test/src/binding.dart:507:13)
07-08 06:15:07.806: I/flutter(17981): #8      LiveTestWidgetsFlutterBinding.handlePointerEvent (package:flutter_test/src/binding.dart:1539:17)
07-08 06:15:07.806: I/flutter(17981): #9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
07-08 06:15:07.806: I/flutter(17981): #10     GestureBinding.unlocked (package:flutter/src/gestures/binding.dart:265:5)
07-08 06:15:07.806: I/flutter(17981): #11     BindingBase.lockEvents.<anonymous closure> (package:flutter/src/foundation/binding.dart:304:9)
07-08 06:15:07.806: I/flutter(17981): #21     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart)
07-08 06:15:07.806: I/flutter(17981): <asynchronous suspension>
07-08 06:15:07.806: I/flutter(17981): (elided 9 frames from dart:async, dart:async-patch, and package:stack_trace)
07-08 06:15:07.806: I/flutter(17981): The test description was:
07-08 06:15:07.806: I/flutter(17981):   Test Minimal Googel Maps Sample
07-08 06:15:07.806: I/flutter(17981): â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.806: I/flutter(17981): 00:01 +0 -1: Test Minimal Googel Maps Sample [E]
07-08 06:15:07.806: I/flutter(17981):   Test failed. See exception logs above.
07-08 06:15:07.806: I/flutter(17981):   The test description was: Test Minimal Googel Maps Sample
07-08 06:15:07.806: I/flutter(17981):   
07-08 06:15:07.816: I/flutter(17981): â•â•â•¡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK â•žâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.816: I/flutter(17981): The following assertion was thrown running a test (but after the test had completed):
07-08 06:15:07.816: I/flutter(17981): 'package:flutter_test/src/binding.dart': Failed assertion: line 1561 pos 12: 'inTest': is not true.
07-08 06:15:07.816: I/flutter(17981): When the exception was thrown, this was the stack:
07-08 06:15:07.816: I/flutter(17981): #2      LiveTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1561:12)
07-08 06:15:07.816: I/flutter(17981): #3      WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:534:22)
07-08 06:15:07.816: I/flutter(17981): #6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
07-08 06:15:07.816: I/flutter(17981): #7      WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:531:27)
07-08 06:15:07.816: I/flutter(17981): #8      main.<anonymous closure> (file:///Users/tahatesser/StudioProjects/triage/integration_test/app_test.dart:16:18)
07-08 06:15:07.816: I/flutter(17981): #9      main.<anonymous closure> (file:///Users/tahatesser/StudioProjects/triage/integration_test/app_test.dart:15:50)
07-08 06:15:07.816: I/flutter(17981): #10     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:156:29)
07-08 06:15:07.816: I/flutter(17981): <asynchronous suspension>
07-08 06:15:07.816: I/flutter(17981): <asynchronous suspension>
07-08 06:15:07.816: I/flutter(17981): (elided 5 frames from class _AssertionError, dart:async, and package:stack_trace)
07-08 06:15:07.816: I/flutter(17981): â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-08 06:15:07.816: I/flutter(17981): 00:01 +0 -2: (tearDownAll)
07-08 06:15:07.830: I/flutter(17981): 00:01 +1 -2: Some tests failed.
```

Seems not to have failed the test on Firebase for some reason.

**Comment by jiahaog** [comment] 2021-07-09 11:36
The errors (such as `hitTestResult != null`) usually indicates that the test is trying to tap on something that isn't there, and 

> Screenshots shows the app was stuck at "Test starting..." for entire time

sounds like Flutter had some trouble showing the widgets on screen. 

After the `I/flutter(17981): 00:01 +1 -2: Some tests failed.` line is printed the integration tests are "done", but it seems like FTL  (Espresso?) continues to tapping on the screen for some reason, which is unexpected:

```
07-08 06:15:09.181: I/Robo(17981): Received request from the controller: # androidx.test.tools.crawler.proto.RemotePlatformRequest@ae8018b0
07-08 06:15:09.181: I/Robo(17981): perform_action {
07-08 06:15:09.181: I/Robo(17981):   action {
07-08 06:15:09.181: I/Robo(17981):     vision_action {
07-08 06:15:09.181: I/Robo(17981):       x_coord: 293
07-08 06:15:09.181: I/Robo(17981):       y_coord: 1013
07-08 06:15:09.181: I/Robo(17981):     }
07-08 06:15:09.181: I/Robo(17981):   }
07-08 06:15:09.181: I/Robo(17981): }
07-08 06:15:09.183: D/InteractionController(17981): clickNoSync (293, 1013)
07-08 06:15:09.195: I/flutter(17981): Some possible finders for the widgets at Offset(106.5, 368.4):
07-08 06:15:09.196: I/flutter(17981):   find.text('Test starting...')
07-08 06:15:09.197: I/flutter(17981):   find.byType(Center)
07-08 06:15:09.197: I/flutter(17981):   find.byType(Container)
07-08 06:15:09.197: I/flutter(17981):   find.byType(RepaintBoundary)
```

and flutter responds with the widgets that are at the position - note the finder that matches `Text('Test starting...')` . We can also see these taps in the video as well.

I'm not sure what is going on here. @TahaTesser can you please share a bit more about how you added the `google_maps_flutter` example in between step 5 and step 6? Is this the same Flutter project that is used for step 2, or is it another project altogether with similar code used in `integration_test/app_test.dart`?

**Comment by TahaTesser** [comment] 2021-07-09 13:54
@jiahaog 
Thank you for looking into this, yes, it's the same project created from scratch from step 1 to the last step. 
To not pollute this issue, I have filed an issue with full code repo and local test video to demo.

**Comment by darshankawar** [comment] 2021-07-30 12:33
Going ahead and closing this as OP doesn't seem to have provided a reproducible code sample to properly address this issue and to make it actionable. So without additional information, we are unfortunately not sure how to resolve this issue. 

Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-07-30 12:33 UTC
Labels: in triage, waiting for customer response
