### ISSUE TITLE
Any plan to support 32-bits windows platform as a lot of users use 32-bits windows in china

### ISSUE THREAD

**Issue by yinzhou2018** [flutter/flutter#79944] opened 2021-04-07 12:44 UTC

**Comment by TahaTesser** [comment] 2021-04-07 12:48
Closing as duplicate of https://github.com/flutter/flutter/issues/14925#
Check this [comment](https://github.com/flutter/flutter/issues/14925#issuecomment-369077739)

**Closed by TahaTesser** 2021-04-07 12:48 UTC
Labels: in triage
