### ISSUE TITLE
Copy and Paste controls for text fields overflow if the localization has longer texts for 'copy', 'paste' etc.

### ISSUE THREAD

**Issue by Dancovich** [flutter/flutter#36547] opened 2019-07-19 16:20 UTC
If you localize your app to a language with long words for the phrases COPY, PASTE, SELECT ALL and others from the clipboard controls, the text will overflow when selecting anything that causes the controls to appear.

That's how the controls appear on Android in pt_BR: 
![Screenshot_1563552009](https://user-images.githubusercontent.com/1204296/61550218-4be19700-aa28-11e9-979f-953f3ec07c83.png)

## Steps to Reproduce

* Create a new sample project with flutter create
* Declare dependencies for flutter_localizations and flutter_cupertino_localizations
* On main.dart, change the `MyApp.build` method to:
```dart
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      locale: Locale('pt', 'BR'),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en'),
        const Locale('pt'),
      ],
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
```

* Also change the `_MyHomePageState.build` method to:

```dart
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: TextField(),
            ),
            Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
```

* Run the app on Android. Tested device was an emulator with the Nexus 5X frame
* Write some text on the field
* Select part of the text but not all the characters, so that the `SELECT ALL` option appears
* `SELECT ALL` option will overflow

## Logs

```
I/flutter (22610): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═══════
I/flutter (22610): The following assertion was thrown during layout:
I/flutter (22610): A RenderFlex overflowed by 22 pixels on the right.
I/flutter (22610):
I/flutter (22610): The overflowing RenderFlex has an orientation of Axis.horizontal.
I/flutter (22610): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter (22610): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter (22610): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter (22610): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter (22610): This is considered an error condition because it indicates that there is content that cannot be
I/flutter (22610): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter (22610): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter (22610): like a ListView.
I/flutter (22610): The specific RenderFlex in question is: RenderFlex#ab4c7 relayoutBoundary=up4 OVERFLOWING:
I/flutter (22610):   creator: Row ← ConstrainedBox ← Container ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (22610):     _InkFeatures-[GlobalKey#2902e ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (22610):     PhysicalModel ← AnimatedPhysicalModel ← Material ← _TextSelectionToolbar ← CustomSingleChildLayout
I/flutter (22610):     ← ⋯
I/flutter (22610):   parentData: <none> (can use size)
I/flutter (22610):   constraints: BoxConstraints(0.0<=w<=411.4, h=44.0)
I/flutter (22610):   size: Size(411.4, 44.0)
I/flutter (22610):   direction: horizontal
I/flutter (22610):   mainAxisAlignment: start
I/flutter (22610):   mainAxisSize: min
I/flutter (22610):   crossAxisAlignment: center
I/flutter (22610):   textDirection: ltr
I/flutter (22610):   verticalDirection: down
I/flutter (22610): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter (22610): ═════════════════════════
```

**Comment by joshua-liubojie** [comment] 2019-07-21 02:45
Looks like issue [#35826](https://github.com/flutter/flutter/issues/35826)

**Comment by justinmc** [comment] 2019-08-02 17:40
Yeah I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/35826 to focus the discussion over there.

**Closed by justinmc** 2019-08-02 17:40 UTC
Labels: a: text input, f: cupertino, f: material design

**Comment by gongxh13** [comment] 2019-11-10 06:32
It is the bug in Flutter itself. They going to fix it in future releases. For now you should change

child: Row(mainAxisSize: MainAxisSize.min, children: items), 
in flutter/packages/flutter/lib/src/material/text_selection.dart on line 61 with

child: ListView(
          scrollDirection: Axis.horizontal,
          children: items,
        ),
More details you can find on Flutter github
