### ISSUE TITLE
"mp4" files generated by `camera` are not valid mp4 files

### ISSUE THREAD

**Issue by SebastianKG** [flutter/flutter#86249] opened 2021-07-11 13:36 UTC
# The Problem

I am using the `camera` plugin to record video, play that video back using `video_player`, and upload that video to an Amazon S3 link. I can't test this on an emulator (due to the problems with the `camera` plugin there), so I test it out using my iPhone 8. The video plays correctly in `video_player` after being recorded by `camera` and successfully uploads a file to S3, but the file I get in S3 is not a valid mp4 -- when I try to play this file in VLC or in other desktop video players, it fails. And when I test it using the `ffprobe` utility, I get:

```
$ ffprobe ~/Downloads/new_upload.mp4
ffprobe version 3.4.8-0ubuntu0.2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561989d46080] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561989d46080] moov atom not found
/home/sebastian/Downloads/new_upload.mp4: Invalid data found when processing input
```

**Is the recorded video file format a standard .mp4 as several tutorials suggest?** Or is the actual format different in any way?

# Details

### How I handle the video recording being stopped
```
void onStopButtonPressed() async {
  var file = await stopVideoRecording();
  if (mounted) setState(() {});
  if (file != null) {
    _uploadFile(file);
    print('Video recorded to ${file.path}');
    setState(() {
      _performance = file;
    });
  }
}
```

### How I upload the file
```
void _uploadFile(XFile file) async {
  var signedLinkUri = Uri.parse('${Configuration.domain}/signed-upload-link');

  var signedLinkResponse = await http.post(signedLinkUri);
  if (signedLinkResponse.statusCode == 200) {
    var signedLinkMap = jsonDecode(signedLinkResponse.body);
    var wrappedSignedLink = SignedLink.fromJson(signedLinkMap);
    print(wrappedSignedLink.link);

    var request =
        http.MultipartRequest('PUT', Uri.parse(wrappedSignedLink.link));

    request.files.add(await http.MultipartFile.fromPath("file", file.path));

    var response = await request.send();

    if (response.statusCode == 200) print('Uploaded!');
  }
}
```

## Pubspec.yaml

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  json_annotation: ^4.0.1
  video_player: ^2.1.5
  cupertino_icons: ^1.0.2
  camera: ^0.8.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
```

## Flutter Doctor Output

(this is mostly irrelevant as I am running this code on my iOS device)

```
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_CA.UTF-8)
    • Flutter version 2.2.1 at /home/sebastian/snap/flutter/common/flutter
    • Framework revision 02c026b03c (6 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/sebastian/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/sebastian/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/sebastian/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /home/sebastian/Documents/idea-IU-201.7223.91
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
```

**Comment by stuartmorgan** [comment] 2021-07-12 02:21
> The video plays correctly in `video_player` after being recorded by `camera` and successfully uploads a file to S3, but the file I get in S3 is not a valid mp4

If it works locally, and only fails after being uploaded, can you describe the debugging you've done to determine that the issue is with the camera plugin, rather than your upload or your server?

**Comment by TahaTesser** [comment] 2021-07-12 13:07
Hi @SebastianKG 
Please provide the details asked above 

If you think this is an issue with the `camera`  plugin, Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by JonasJW** [comment] 2021-07-22 16:29
I have (probably) the same issue.

As I understand, the plugin records in `.mov` format, which is incompatible with browsers.

Oddly the recorded video name ends with `.mp4`. When renaming it to `[name].mov` and uploading the video, I can download it and play it with QuickTime Player.

When my understanding is correct, we need to convert the recorded video to mp4, which I have not yet found a way to do so.

**Comment by TahaTesser** [comment] 2021-08-12 07:33
This is a duplicate of https://github.com/flutter/flutter/issues/86881 and there is a proposal for choosing video encoder  https://github.com/flutter/flutter/issues/83074

**Closed by TahaTesser** 2021-08-12 07:33 UTC
Labels: waiting for customer response, in triage
