### ISSUE TITLE
[cocoon] Uncaught error in request handler: Unsupported operation: Cannot extract a file path from a URI with a query component

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#65395] opened 2020-09-08 16:15 UTC
The PR https://github.com/flutter/cocoon/pull/937 is causing the following error:

```
2020-09-08 09:04:37.650 PDT
Uncaught error in request handler: Unsupported operation: Cannot extract a file path from a URI with a query component
#0      _SimpleUri.toFilePath (dart:core/uri.dart:4616:9)
#1      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:129:45)
#2      runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#3      runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#4      _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#5      _rootRun (dart:async/zone.dart:1190:13)
#6      _CustomZone.run (dart:async/zone.dart:1093:19)
#7      _runZoned (dart:async/zone.dart:1630:10)
#8      runZonedGuarded (dart:async/zone.dart:1618:12)
#9      runZoned (dart:async/zone.dart:1547:12)
#10     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#11     fork (package:gcloud/service_scope.dart:104:30)
#12     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#13     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#20     _StreamController._add (dart:async/stream_controller.dart:682:7)
#21     _StreamController.add (dart:async/stream_controller.dart:624:5)
#22     _HttpServer._handleRequest (dart:_http/http_impl.dart:2874:19)
#23     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2629:19)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#29     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#30     _StreamController._add (dart:async/stream_controller.dart:682:7)
#31     _StreamController.add (dart:async/stream_controller.dart:624:5)
#32     _HttpParser._headersEnd (dart:_http/http_parser.dart:393:19)
#33     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
#34     _HttpParser._parse (dart:_http/http_parser.dart:323:7)
#35     _HttpParser._onData (dart:_http/http_parser.dart:852:5)
#36     _rootRunUnary (dart:async/zone.dart:1198:47)
#37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#41     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#42     _StreamController._add (dart:async/stream_controller.dart:682:7)
#43     _StreamController.add (dart:async/stream_controller.dart:624:5)
#44     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#45     _rootRunUnary (dart:async/zone.dart:1206:13)
#46     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#50     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#51     _StreamController._add (dart:async/stream_controller.dart:682:7)
#52     _StreamController.add (dart:async/stream_controller.dart:624:5)
#53     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#54     _Closure.call (dart:core-patch/function.dart)
#55     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

I have rolled the server back to previous version to mitigate the incident (https://github.com/flutter/flutter/issues/65393).

**Comment by keyonghan** [comment] 2020-09-08 18:20
This seems to be related to latest changes in `flutter` or `dart`.
By using an earlier flutter docker image (Flutter Channel master, 1.22.0-10.0.pre.14, on Linux, locale en_US) to deploy cocoon, it works.
But it hits the error when using the latest flutter docker image (Channel master, 1.22.0-10.0.pre.87, on Linux, locale en_US).

**Comment by digiter** [comment] 2020-09-08 18:25
Do you have a link to the docker images? Is it possible to use `dev` or `beta` version of the flutter docker image? /cc @godofredoc

**Comment by keyonghan** [comment] 2020-09-08 19:12
Here are the [docker images](https://pantheon.corp.google.com/gcr/images/flutter-dashboard/GLOBAL/flutter?project=flutter-dashboard&gcrImageListsize=30). Cocoon build  is based on the one with `latest` tag.

I guess we can switch to `dev` or `beta` channel. Let me do a test trial.

**Comment by keyonghan** [comment] 2020-09-08 20:44
Did a successful build based on dev channel. I will verify it works to build cocoon later, before closing.

**Comment by keyonghan** [comment] 2020-09-08 22:23
Latest cocoon build is based on the `dev` flutter docker image, and is working well. 
This is a workaround to make cocoon deployment/dashboard work.
The root cause to this error from flutter master side may need further triage.

**Closed** 2020-09-08 22:59 UTC
Labels: P1, team: infra
