### ISSUE TITLE
--licenses is no longer a valid flag to Android's sdkmanager

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14190] opened 2018-01-19 23:03 UTC
https://github.com/flutter/flutter/blob/7ffcce84a2037376afe2614d6789c30a57bdb0a8/packages/flutter_tools/lib/src/android/android_workflow.dart#L194

```
$ ~/Android/Sdk/tools/bin/sdkmanager --licenses
Error: Unknown argument --licenses

$ echo $?
1
```

**Comment by tvolkert** [comment] 2018-01-19 23:09
This blocks me from running any apps on Android:

```
$ flutter run --debug
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                1.0s
Resolving dependencies...                                /

* Error running Gradle:
Unable to download needed Android SDK components, as the following licenses have not been accepted:
Android SDK Build-Tools 26.0.2

To resolve this, please run the following command in a Terminal:
flutter doctor --android-licenses

$ flutter doctor --android-licenses
Error: Unknown argument --licenses
Usage: 
  sdkmanager [--uninstall] [<common args>] \
    [--package_file <package-file>] [<packages>...]
  sdkmanager --update [<common args>]
  sdkmanager --list [<common args>]

In its first form, installs, or uninstalls, or updates packages.
    <package> is a sdk-style path (e.g. "build-tools;23.0.0" or 
             "platforms;android-23").
    <package-file> is a text file where each line is a sdk-style path
                   of a package to install or uninstall.
    Multiple --package_file arguments may be specified in combination
     with explicit paths.
In its second form (with --update), currently installed packages are
    updated to the latest version.
In its third form, all installed and available packages are printed out.

Common Arguments:
    --sdk_root=<sdkRootPath>: Use the specified SDK root instead of the SDK containing this tool
    --channel=<channelId>: Include packages in channels up to <channelId>.
                           Common channels are:
                           0 (Stable), 1 (Beta), 2 (Dev), and 3 (Canary).

    --include_obsolete: With --list, show obsolete packages in the
                        package listing. With --update, update obsolete
                        packages as well as non-obsolete.
    --no_https: Force all connections to use http rather than https.
    --proxy=<http | socks>: Connect via a proxy of the given type.
    --proxy_host=<IP or DNS address>: IP or DNS address of the proxy to use.
    --proxy_port=<port #>: Proxy port to connect to.

* If the env var REPO_OS_OVERRIDE is set to "windows",
  "macosx", or "linux", packages will be downloaded for that OS.

```

**Comment by tvolkert** [comment] 2018-01-19 23:23
I just opened the Android SDK Manager GUI and started installing whatever SDKs and tools the tool was complaining about (which in turn prompted me to accept various licenses) until the tool stopped complaining... but it wasn't at all intuitive whether I was doing the right thing or why I even needed to install SDK platforms that I didn't yet have (e.g. I had SDK platform 27, but it was complaining that I hadn't accepted the license for platform 26).

In any case, I was able to get unblocked by checking as many boxes as I could in the SDK Manager GUI 😄

**Comment by cbracken** [comment] 2018-01-23 19:11
Closing as dupe of #13353, which appears to be a dupe of #9959.

**Closed by cbracken** 2018-01-23 19:11 UTC
Labels: dev: first hour, dev: tool, ▣ platform-android

**Comment by gnanamganesan** [comment] 2018-05-14 14:10
Error running Gradle:
Unable to download needed Android SDK components, as the following licenses have not been accepted:
Android SDK Build-Tools 26.0.2, Android SDK Platform 27

**Comment by gnanamganesan** [comment] 2018-05-14 14:11
At the time of build. I am getting this error.

**Comment by lucasmicheleto** [comment] 2018-05-15 20:27
Ensure your file 'local.properties' has correct location of sdk.dir

**Comment by gnanamganesan** [comment] 2018-05-17 09:26
Thanks for the reply.

But, I am trying to build apk file through bitbucket pipeline. I am facing below errors,
Error running Gradle: Unable to download needed Android SDK components, as the following licenses have not been accepted: Android SDK Build-Tools 26.0.2, Android SDK Platform 27               

Needed with solution
==============

In local build  i used below code
-------------------------------
flutter.buildMode=release
flutter.sdk=C:\\Flutter\\flutter\\flutter_git_repo\\flutter
sdk.dir=C\:\\Users\\admin\\AppData\\Local\\Android\\Sdk
----------------------------------------------------------

BitBucket ... what will write ?


https://gist.github.com/gnanamganesan/69d870557c57d70da1817fc08ea3ecc1

**Comment by MudassirRaza12345** [comment] 2021-06-10 09:06
Error: Could not find or load main class solution.pk\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\..
Caused by: java.lang.ClassNotFoundException: solution/pk\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\\//

facing this error
