### ISSUE TITLE
flutter run does not always pick up changes to plugin dependencies

### ISSUE THREAD

**Issue by smrtsmrf** [flutter/flutter#10772] opened 2017-06-16 16:26 UTC
## Steps to Reproduce

Working with the [Firebase for Flutter code lab step 10](https://codelabs.developers.google.com/codelabs/flutter-firebase/#9) to get images working in the chat app. Android works fine, but iOS throws this error:

## Logs

<img width="1512" alt="screen shot 2017-06-16 at 9 39 46 am" src="https://user-images.githubusercontent.com/17756776/27234812-9307ff18-527b-11e7-9082-469114b56d14.png">

## Solution

Running a ```flutter build ios``` before trying to run on a device allows it to work properly, but there is no mention of needing to do this.

Can we either add this instruction to the code lab or make it so this command isn't needed?

**Comment by eseidelGoogle** [comment] 2017-06-16 16:30
@collinjackson would know.

**Comment by mit-mit** [comment] 2017-06-16 16:31
@smrtsmrf did Run/Debug from IntelliJ or `flutter run` from the terminal work? Or you just tried running from Xcode? Trying to narrow down what might trigger this.

**Comment by mravn-google** [comment] 2017-06-16 17:10
(Sorry for closing, was trying to cancel a comment) It is a known issue that Xcode doesn't always refresh its view of the ios project, and that it may therefore complain about missing files or other inconsistencies following changes made by Flutter tooling/cocoapod. These problems usually resolve themselves during the Build face, if you just ignore them and hit Run.

In this case, that obviously wasn't sufficient.

@smrtsmrf Two questions:

1. Does the problem persist, if you restart Xcode?
1. Does running the app also fail on iOS, if you run it with `flutter run` or from IntelliJ?

**Comment by smrtsmrf** [comment] 2017-06-16 17:19
I tried running it first with flutter run. I saw it complaining about the image picker so I tried running in xcode to get more info. Running it in there created the problem in the screenshot above. I tried it in xcode yesterday as well as today, so restarting xcode didn't fix it.

**Comment by collinjackson** [comment] 2017-06-16 19:14
What was the original error about image_picker that caused you to open Xcode?

**Comment by smrtsmrf** [comment] 2017-06-16 19:50
Unfortunately, I can't remember the error exactly since it was a lot of output. I only saw that image_picker was the culprit. I couldn't really understand/make sense of the error, so that's why I opened Xcode, hoping for some clarification. I know this is not so helpful...

**Comment by smrtsmrf** [comment] 2017-06-16 19:51
I got back to a device, and it crashes on an iOS device when I try to access the photo library. Here's the output from ```flutter run```
[output.txt](https://github.com/flutter/flutter/files/1081799/output.txt)

**Comment by collinjackson** [comment] 2017-06-16 20:00
Looks like a dupe of #10752 which has been fixed. Does upgrading image_picker to 0.0.3 fix it?

**Comment by smrtsmrf** [comment] 2017-06-16 20:14
@collinjackson you are right. That specific issue was solved with the update. the initial problem of needed to explicitly call ```flutter build ios``` first is still an issue I believe?

**Comment by mravn-google** [comment] 2017-06-16 20:32
Calling `flutter build ios` should only be necessary between these two steps:

1. Change your plugin dependencies in `pubspec.yaml`.
1. Launch your app from Xcode.

(Something similar applies to Android).

Flutter tooling must be invoked in between, because the tools read your `pubspec.yaml` file and instruct cocoapods to inject the plugin dependencies into your Xcode project. If you launch your app using `flutter run` or from IntelliJ, `flutter build ios` happens under the hood. Following this, you can also launch from Xcode.

Reading the code lab steps, it is unclear to me how you'd arrive at a situation where all plugin dependencies except one have been so injected. Any context you may be able to provide here would be greatly appreciated.

**Comment by smrtsmrf** [comment] 2017-06-16 20:40
@mravn-google I ran into the image_picker issue earlier, so I took it out until I was actually doing the image stuff. So then I added the image_picker dependency, then upgraded and got packages. Then I tried doing ```flutter run```. I'm told that the build process happens inside the run, but in this case, I had to explicitly call ```flutter build ios``` and then ```flutter run``` would work

**Comment by mravn-google** [comment] 2017-06-16 20:43
@smrtsmrf Thanks!
@collinjackson I'm making this issue be about the need for calling `flutter build ios` after plugin changes, OK?

**Comment by smrtsmrf** [comment] 2017-06-16 20:46
@mravn-google yes, that was the initial intent. Thanks for clarifying things. and thanks @collinjackson for pointing me to the dupe and solved issue for the other part

**Comment by Hixie** [comment] 2017-12-18 19:57
This seems like plugin framework maintenance, which we have on our short-term priority list, so leaving in the current milestone.

**Comment by mravn-google** [comment] 2018-02-07 09:24
I am unable to reproduce the issue (the need for explicit `flutter build ios` before `flutter run`).

Tried a number of variations along: Run project with plugins, remove some plugins, run again, re-add the removed plugins, run again.

**Closed by mravn-google** 2018-02-07 09:24 UTC
Labels: plugin, plugin: tooling
