### ISSUE TITLE
iFrameElement captures input from dialog above it

### ISSUE THREAD

**Issue by sentanilesh** [flutter/flutter#94924] opened 2021-12-09 10:07 UTC
## Steps to reproduce
1. flutter create `bug`
2. Run the code sample on `web`
3. Click on the button in the `Appbar` to show the dialog
4. Click on the `ok` button in the dialog

## Expected results 

The app renders the `iFrame` and the dialog is closed when you click on `OK`

## Actual Results

The app renders the `iFrame` and the dialog is closed, however, the `OK` button is non-responsive. If you look closely, you'll see that the touch events are captured by the `iFrame`

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:html' as html;
import 'dart:ui' as ui;
 

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
 
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Appbar"),
        actions: [
           ElevatedButton(onPressed: () { 
              showDialog(
                context: context,
                builder: (ctx) => AlertDialog(
                  title: const Text("Alert Dialog Box"),
                  content: const Text("You have raised a Alert Dialog Box"),
                  actions: <Widget>[
                    TextButton(
                      onPressed: () {
                        Navigator.of(ctx).pop();
                      },
                      child: const  Text("okay"),
                    ),
                  ],
                ),
              );
            },
            child: const Text("SHOW DIALOG FOR ISSUE"),)
        ],
      ),
      body: IframeDemo(),
    );
  }
}

class IframeDemo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return MyWidget();
  }
}

class MyWidget extends State<IframeDemo> {
  String? _url;
  html.IFrameElement? _iframeElement;

  @override
  initState() {
    super.initState();
    _url = 'https://flutter.dev/';
    _iframeElement = html.IFrameElement()
      ..src = _url
      ..id = 'iframe'
      ..style.border = 'none';
    //ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => _iframeElement!,
    );
  }

  @override
  Widget build(BuildContext context) {
    print('url is $_url');

    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
        ),
        const SizedBox(
          height: 500,
          width: 600,
          child: HtmlElementView(
            viewType: 'iframeElement',
          ),
        ),
      ],
    );
  }
}
```
</details>

## Images

https://ibb.co/xsnbqjh

https://ibb.co/FD9hN6c

**Comment by danagbemava-nc** [comment] 2021-12-09 13:30
Hi @sentanilesh, this is a duplicate of https://github.com/flutter/flutter/issues/81081. 

You can try wrapping the dialog with a `PointerInterceptor` from the https://pub.dev/packages/pointer_interceptor package. 

Kindly try the sample below and let me know if you are able to interact with the dialog. 

<details>
<summary>code sample</summary>

```dart
// ignore_for_file: avoid_web_libraries_in_flutter

import 'package:flutter/material.dart';
import 'dart:html' as html;
import 'dart:ui' as ui;

import 'package:pointer_interceptor/pointer_interceptor.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Appbar"),
        actions: [
          ElevatedButton(
            onPressed: () {
              showDialog(
                context: context,
                builder: (ctx) => PointerInterceptor(
                  child: AlertDialog(
                    title: const Text("Alert Dialog Box"),
                    content: const Text("You have raised a Alert Dialog Box"),
                    actions: <Widget>[
                      TextButton(
                        onPressed: () {
                          Navigator.of(ctx).pop();
                        },
                        child: const Text("okay"),
                      ),
                    ],
                  ),
                ),
              );
            },
            child: const Text("SHOW DIALOG FOR ISSUE"),
          )
        ],
      ),
      body: PointerInterceptor(child: IframeDemo()),
    );
  }
}

class IframeDemo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return MyWidget();
  }
}

class MyWidget extends State<IframeDemo> {
  String? _url;
  html.IFrameElement? _iframeElement;

  @override
  initState() {
    super.initState();
    _url = 'https://flutter.dev/';
    _iframeElement = html.IFrameElement()
      ..src = _url
      ..id = 'iframe'
      ..style.border = 'none';
    //ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => _iframeElement!,
    );
  }

  @override
  Widget build(BuildContext context) {
    print('url is $_url');

    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
        ),
        const SizedBox(
          height: 500,
          width: 600,
          child: HtmlElementView(
            viewType: 'iframeElement',
          ),
        ),
      ],
    );
  }
}

```

</details>

**Comment by slavap** [comment] 2021-12-10 02:15
@sentanilesh 
Also you can try to add the following to the end of body in index.html:
```html
<script>
    const wait_until = setInterval(() => {
      var elt = document.querySelector('flt-glass-pane');
      if (elt) {
        clearInterval(wait_until);

        // pointer-events to resolve issue when widgets over the IFrame ignore clicks.
        // Read more https://github.com/rodydavis/easy_web_view/issues/7#issuecomment-752326934
        // Another possible solution https://pub.dev/packages/pointer_interceptor

        var css = 'flt-scene-host { pointer-events: auto !important; }';
        var style = document.createElement('style');
        style.innerHTML = css;
        elt.shadowRoot.appendChild(style);
      }
    }, 500);
  </script>
```

**Closed** 2021-12-30 14:09 UTC
Labels: waiting for customer response, in triage
