### ISSUE TITLE
Issue facing in flutter web application 

### ISSUE THREAD

**Issue by nil1613** [flutter/flutter#56035] opened 2020-04-30 11:19 UTC
I have gone through the linkhttps://flutter.dev/docs/get-started/web. and
I have removed build_web_compilers and build_runner dependencies
Now I am getting below errors

webdev could not run for this project.
You must have a dependency on build_runner in pubspec.yaml.

pubspec.yaml
dev_dependencies:
build_runner: >=1.6.2 <2.0.0
You must have a dependency on build_web_compilers in pubspec.yaml.

pubspec.yaml
dev_dependencies:
build_web_compilers: >=2.6.1 <3.0.0
You have a dependency on cupertino_icons which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on flutter which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on flutter_test which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
pub finished with exit code 78
_

Now what should i add or remove to run main.dart

**Comment by TahaTesser** [comment] 2020-04-30 11:33
duplicate of [#56025](https://github.com/flutter/flutter/issues/56025)

**Closed by TahaTesser** 2020-04-30 11:33 UTC
