### ISSUE TITLE
[☠] Visual Studio - develop for Windows (the doctor check crashed)

### ISSUE THREAD

**Issue by DogandCows** [flutter/flutter#105401] opened 2022-06-05 16:14 UTC
Hi Nice meet you

I'm going to build a flutter development environment in vcode. But this error is blocking it.

I installed the C++ desktop Blah blah  in the visual studio.
Of course I reinstalled it.
All the other items have been checked.
I'd really appreciate your help. I just started learning flutter!

By the way, how do you change the font size in GitHub writing? The font size is uneven.
Most translators and sentences can be awkward. Please understand me..^^
-------------------------------------------------------------------------------------------------------------
....flutter doctor -v

[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: [
 {
          "instanceId": "3a08cd68",
          "installDate": "2022-06-05T15:37:25Z",
          "installationName": "VisualStudio/17.2.3+32526.322",
          "installationPath": "D:\\Microsoft Visual Studio",
          "installationVersion": "17.2.32526.322",
          "productId": "Microsoft.VisualStudio.Product.Community",
          "productPath": "D:\\Microsoft Visual Studio\\Common7\\IDE\\devenv.exe",
          "state": 4294967295,
.
.
.
.
      #39     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #40     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>
-------------------------------------------------------------------------------------------------------------

**Comment by stuartmorgan** [comment] 2022-06-05 19:07
Duplicate of https://github.com/flutter/flutter/issues/102451

**Closed by stuartmorgan** 2022-06-05 19:07 UTC
