### ISSUE TITLE
GIF images are faster than the original

### ISSUE THREAD

**Issue by cv0cv0** [flutter/flutter#57469] opened 2020-05-18 08:32 UTC
## Steps to Reproduce

**Expected results:** 
Consistent with the speed at which GIF images were originally designed.

**Actual results:** 
All third-party image loading libraries are just as over-fast as Image.

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/hzlx/Library/Flutter
    • Framework revision f139b11009 (7 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hzlx/Library/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = /Users/hzlx/Library/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (2 available)
    • iPhone 11 Pro • F51DB1DF-8067-430F-98DC-EAADFBAC52E4 • ios        •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS         • macOS                                • darwin-x64 • Mac OS X 10.15.4 19E287
```

</details>

**Comment by iapicca** [comment] 2020-05-18 09:41
Hi @cv0cv0 
could you please run 
```conosle
flutter channel stable
flutter upgrade --force
```
if the issue persists 
please provide your updated `flutter doctor -v` , 
and a reproducible minimal code sample.
Thank you

**Comment by cv0cv0** [comment] 2020-05-18 10:08
> Hi @cv0cv0
> could you please run
> 
> ```
> flutter channel stable
> flutter upgrade --force
> ```
> 
> if the issue persists
> please provide your updated `flutter doctor -v` ,
> and a reproducible minimal code sample.
> Thank you

The library in use is not compatible with 1.17.0

**Comment by w4mxl** [comment] 2020-05-19 03:23
@cv0cv0 Hi, We encountered the same problem.

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-CN)
    • Flutter version 1.17.0 at /Users/wml-wufeng/Wufeng/development/flutter
    • Framework revision e6b34c2b5c (2 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wml-wufeng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • Android SDK built for x86  • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • Wml's XR                   • 00008020-0018292E0ED8003A            • ios         • iOS 13.5
    • iPhone SE (2nd generation) • 9D42102A-3CD5-4AD0-A4DA-F7280F93770C • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
```

Then this is a reproducible minimal code sample:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Image.network("https://image.xiniujiao.net/bf265029ea1183ba84a18f4b6da75bdd.gif"),
      ),
    );
  }
}
```
You can compare the difference in gif loading speed between browser and app.

**Comment by cv0cv0** [comment] 2020-05-19 04:52
@w4mxl The strange thing is that the sample speed in the Flutter Gallery is normal.
奇怪的是 Flutter Gallery 里的示例速度是正常的。

**Comment by TahaTesser** [comment] 2020-05-19 11:43
@w4mxl 
Thanks for code sample
I can reproduce the issue using latest `dev` channel  

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-1.0.pre at /home/tesser/Code/flutter_dev
    • Framework revision 456d80b9dd (8 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/tesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/tesser/Code/SDK
    • Java binary at: /home/tesser/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/tesser/Code/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API
      29) (emulator)

• No issues found!
``` 

</details> 

closing as duplicate of https://github.com/flutter/flutter/issues/29130

**Closed by TahaTesser** 2020-05-19 11:43 UTC
Labels: in triage

**Comment by w4mxl** [comment] 2020-05-20 04:42
> @w4mxl The strange thing is that the sample speed in the Flutter Gallery is normal.
> 奇怪的是 Flutter Gallery 里的示例速度是正常的。

hi 你说「Flutter Gallery 里的示例」我没找到位置，是在哪个部分？

**Comment by cv0cv0** [comment] 2020-05-20 05:01
![Simulator Screen Shot - iPhone 11 Pro - 2020-05-20 at 13 00 26](https://user-images.githubusercontent.com/18623780/82406706-e328d800-9a99-11ea-96c5-7a86f3010a84.png)
Media

**Comment by w4mxl** [comment] 2020-05-20 05:42
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-05-20 at 13 40 24](https://user-images.githubusercontent.com/3645496/82409067-803a3f80-9a9f-11ea-937a-9860efa66841.png)
之前是你截图那样。我上午是 clone 的最新的 Flutter Gallery ，好像改版了，难怪没找到了
