### ISSUE TITLE
Invalid argument(s): Cannot find executable for git.

### ISSUE THREAD

**Issue by Daibaku9999** [flutter/flutter#59241] opened 2020-06-11 07:08 UTC
I upgrade flutter(channel beta) an hour ago and after that I can't run any command.
PowerShell returns messages like so.
How can I fix this?

```
Unhandled exception:
Invalid argument(s): Cannot find executable for git.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#3      _runGit (package:flutter_tools/src/version.dart:665:23)
#4      new FlutterVersion (package:flutter_tools/src/version.dart:54:26)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:138:29)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     flutterVersion (package:flutter_tools/src/globals.dart:88:46)
#11     new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:192:51)
#12     new Usage (package:flutter_tools/src/reporting/usage.dart:79:9)
#13     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:195:20)
#14     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#16     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#18     flutterUsage (package:flutter_tools/src/globals.dart:51:35)
#19     _handleToolError (package:flutter_tools/runner.dart:122:13)
#20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:76:13)
#21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:70:17)
#22     _rootRunBinary (dart:async/zone.dart:1222:13)
#23     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#24     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1601:18)
#25     _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
#26     Future._propagateToListeners (dart:async/future_impl.dart:646:16)
#27     Future._completeError (dart:async/future_impl.dart:537:5)
#28     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
#30     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#31     _rootRunBinary (dart:async/zone.dart:1214:47)
#32     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#33     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#34     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#35     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#36     Future._completeError (dart:async/future_impl.dart:537:5)
#37     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
#38     _rootRun (dart:async/zone.dart:1190:13)
#39     _CustomZone.run (dart:async/zone.dart:1093:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by TahaTesser** [comment] 2020-06-11 12:08
Hi @Daibaku9999 
Can you please provide your `flutter doctor -v`?
Does it result to same logs too?

Looks like duplicate https://github.com/flutter/flutter/issues/57802#issuecomment-632769475
Thank you

**Comment by Daibaku9999** [comment] 2020-06-11 12:09
Hi, @TahaTesser 
Yeah, same logs.
Should I close then?

**Comment by TahaTesser** [comment] 2020-06-11 12:11
Closing as duplicate of  https://github.com/flutter/flutter/issues/57802

**Closed by TahaTesser** 2020-06-11 12:11 UTC
Labels: in triage
