### ISSUE TITLE
Flutter 2.0.3: Error connecting to the service protocol: failed to connect to http://127.0.0.1:62719/OJaWBfEtnmY=/

### ISSUE THREAD

**Issue by ldemyanenko** [flutter/flutter#79567] opened 2021-04-01 17:17 UTC
I'm experiencing an issue with the Flutter template app when launching it on Flutter 2.0.3.
I'm getting this output 
```
Launching lib/main.dart on SM J320H in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Error connecting to the service protocol: failed to connect to http://127.0.0.1:62719/OJaWBfEtnmY=/
```
I'm launching this app on a real Android device. 
When launching with Flutter 1.22.5 - everything works fine. 

Flutter doctor output: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-04-05 10:11
Hi @ldemyanenko 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/77347
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-05 10:11 UTC
Labels: in triage
