### ISSUE TITLE
Can't build for windows app

### ISSUE THREAD

**Issue by thesmartrenovation** [flutter/flutter#50774] opened 2020-02-14 03:16 UTC
I've clone this repo:

https://github.com/google/flutter-desktop-embedding

I was try to run this example but the process stuck.

Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:77:5)
<asynchronous suspension>
#2      WindowsDevice.buildForDevice (package:flutter_tools/src/windows/windows_device.dart:46:11)
#3      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:85:13)
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:434:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:333:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:556:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:668:18)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.15.4-pre.65, on Microsoft Windows [VersiÃ³n 10.0.18362.657], locale es-CO)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[√] Connected device (3 available)

• No issues found!

pubspec.yaml

name: example_flutter
description: An example project for flutter-desktop-embedding.

version: 0.1.0

environment:
  sdk: '>=2.0.0 <3.0.0'
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900

**Comment by stuartmorgan** [comment] 2020-02-14 03:34
Duplicate of https://github.com/google/flutter-desktop-embedding/issues/672

(In the future, please run with `-v` when reporting failures as it says in the output; the only reason I can tell what the problem is is that we have a known breakage at the moment.)

**Closed by stuartmorgan** 2020-02-14 03:34 UTC
