### ISSUE TITLE
Hover effect on TextButtons does not work with colored Containers in a List

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#78330] opened 2021-03-16 15:19 UTC
Hi,
I have a ListView with containers inside. Similiar like the Teams chat list.
Each container is child of a TextButton so that he is clickable.
The TextButton has a hover effect so that it gets gray if I hover with the mouse over it.

If I don't set a color to the conatiners, the hover effect does work:
![Bild2](https://user-images.githubusercontent.com/20759873/111333690-31cfe000-8673-11eb-932e-bbda968a4000.png)

But if I make the containers white, what is verry common, the hover effect does not work anymore.
It seems to me, like the hover color is displayed behind the container. If there are by accident small 1 px gap between the containers, I can see a glimps of the hover effect.

![Bild1](https://user-images.githubusercontent.com/20759873/111333915-680d5f80-8673-11eb-9d4c-4ce3aed29639.png)

I expect the hover effect to work in both cases. Is this intended? If I have only Text in a TextButton, it would be ok to have the hover effect in the background. But how to make a hover effect aboth the cards?

<details>
  <summary>flutter doctor -v</summary>
[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale de-DE)
    • Flutter version 2.0.1 at C:\Users\akilian\Flutter SDK\flutter
    • Framework revision c5a4b4029c (12 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 1 category.

</details>

**Comment by Wissperwind** [comment] 2021-03-16 15:32
Another strange thing is, that if I selected one container, in my case they get gray. And over the gery containers, the hover effect works. (If I hover their gray gets darker). But over the unselected containers, the hover effect does not work.

**Comment by Wissperwind** [comment] 2021-03-16 16:01
Widget buildJobCard(BuildContext context, int index) {
   [...]

    Color cardColor;

    if (jobDetailView.job != null && jobDetailView.job.jobId == job.jobId) {
      // borderColor = Theme.of(context).accentColor;
      cardColor = Colors.black12;
    } else {
      cardColor = Colors.white;
    }

    var container = Container(
      child: largeRow,
      padding: EdgeInsets.all(10),
      decoration: BoxDecoration(
        border: Border.all(color: Colors.black38, width: 0.2),
        color: cardColor,
        ),
    );



    var onCardClick = () {
      setState(() {
        jobDetailView = JobDetailView(job: job);
      });
    };
    
    ButtonStyleGenerator buttonStyleGenerator = ButtonStyleGenerator(hoverColor: Colors.red, onPressedColor: Theme.of(context).splashColor, textColor: Colors.black);
    TextButton clickableContainer = TextButton(child: container, onPressed: onCardClick, style: buttonStyleGenerator.generate());

    return clickableContainer;
  }

**Comment by Wissperwind** [comment] 2021-03-16 16:02
So if the card color is black12, the card is selected and the hovering works.
If the card color is white, the hovering does not work.

**Comment by Wissperwind** [comment] 2021-03-22 13:40
A workaround is to use:
Color cardColor = Colors.white70.withBlue(255).withGreen(255).withRed(255);
This way you can get white cards with a hover effekt.

I also noticed that the hover effect does not work with Color.from...
For example Color.fromARGB(255, 255, 255, 255);

**Comment by Wissperwind** [comment] 2021-03-22 13:45
Another, probably related issue is, that in white container which are insode of textbuttons like aboce, the hover effect of icon buttons does not work.
It does work if you set the color to "another white": Colors.white70.withBlue(255).withGreen(255).withRed(255);

**Comment by HansMuller** [comment] 2021-07-12 21:32
As far as I can tell, there's no bug here. If the background of a button's child is opaque, then the button's own background will be obscured by the child. The button's background is used to display the overlayColor, which - despite its name - is not a color that's overlaid on the button itself, just on top of the button's background. This doesn't have anything to do with the button being a ListView descendant.

I'm going to close this issue as "working as intended". If I've missed some aspect of the issue, please reopen it.

```dart
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Color? getColor(Set<MaterialState> states) {
      const Set<MaterialState> interactiveStates = <MaterialState>{
        MaterialState.hovered,
      };
      if (states.any(interactiveStates.contains))
        return Colors.blue.shade100;
      return null; // use the default
    }

    return Scaffold(
      body: Center(
        child: TextButton(
          style: ButtonStyle(
            overlayColor: MaterialStateProperty.resolveWith<Color?>(getColor),
          ),
          onPressed: () {},
          child: Text('Flutter'),
        ),
      ),
    );
  }
}

void main() {
  runApp(MaterialApp(home: Home()));
}
```

**Closed by HansMuller** 2021-07-12 21:32 UTC
Labels: f: material design, found in release: 2.0, found in release: 2.1, framework, has reproducible steps
