### ISSUE TITLE
Can not install app in ios simulator

### ISSUE THREAD

**Issue by testlast** [flutter/flutter#51462] opened 2020-02-26 10:15 UTC
Sending crash report to Google.
Crash report sent (report ID: 8bc462463acf4add)
Oops; flutter has exited unexpectedly.
Crash report written to /Users/GATISTAVAM-PC7/Documents/VAISHALI /LEARNING RESOURCE/abiamarket/flutter_01.log;
[flutter_01.log](https://github.com/flutter/flutter/files/4254909/flutter_01.log)

**Comment by TahaTesser** [comment] 2020-02-26 11:06
Duplicate of [#47633](https://github.com/flutter/flutter/issues/47633)

**Closed by TahaTesser** 2020-02-26 11:06 UTC
