### ISSUE TITLE
[go_router] Can not navigate to a child route when using a top-level redirect.

### ISSUE THREAD

**Issue by phamquoctrongnta** [flutter/flutter#144979] opened 2024-03-12 04:58 UTC
### Steps to reproduce

1. Open app within `redirect` config on `GoRouter`.
2. Click `push` to child page.

### Expected results

Able navigate from `HomePage` to `SecondPage` after use `redirect`.

### Actual results

I can not navigate from **HomePage** to **SecondPage**.

### Code sample

<details open><summary>Code sample</summary>

```
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  final isLogged = true;

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: MaterialApp.router(
        routerConfig: GoRouter(
          initialLocation: '/login',
          redirect: (_, state) {
            print('>>>>>> ${state.fullPath}');
            if (isLogged) {
              return '/home';
            }
            return null;
          },
          routes: [
            GoRoute(
                path: '/login',
                builder: (context, state) {
                  return const Login();
                }),
            GoRoute(
              path: '/home',
              pageBuilder: (context, state) =>
                  const NoTransitionPage(child: HomePage()),
            ),
            GoRoute(
              path: '/second',
              pageBuilder: (context, state) =>
                  const NoTransitionPage(child: SecondPage()),
            ),
          ],
        ),
      ),
    );
  }
}
```

`HomePage`:
```
class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: SizedBox(
            height: 50,
            child: ElevatedButton(
              onPressed: () {
                context.push('/second');
              },
              child: const Text('Push to Second Page'),
            ),
          ),
        ),
      ),
    );
  }
}
```
`SecondPage`:
```
class SecondPage extends StatefulWidget {
  const SecondPage({super.key});

  @override
  State<SecondPage> createState() => _Page1State();
}

class _Page1State extends State<SecondPage> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('This is Second Page'),
          ],
        ),
      ),
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
I/flutter (20452): >>>>>> /login
I/flutter (20452): >>>>>> /home
D/EGL_emulation(20452): app_time_stats: avg=323.09ms min=4.88ms max=8840.02ms count=28
I/flutter (20452): >>>>>> /login
I/flutter (20452): >>>>>> /home
D/EGL_emulation(20452): app_time_stats: avg=887.59ms min=179.67ms max=1595.51ms count=2
I/flutter (20452): >>>>>> /second
I/flutter (20452): >>>>>> /home
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.0 23A344 darwin-arm64, locale en-VN)
    • Flutter version 3.19.2 on channel stable at /Users/fvm/versions/3.19.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (13 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.0

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)      • emulator-5554             • android-arm64 • Android 14 (API 34) (emulator)
    
    
      
    
      

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-03-12 10:34
Closing this as a duplicate of https://github.com/flutter/flutter/issues/142393

**Closed by darshankawar** 2024-03-12 10:34 UTC
Labels: in triage
