### ISSUE TITLE
Flutter app failed to build or run on android

### ISSUE THREAD

**Issue by abulojoshua1** [flutter/flutter#28270] opened 2019-02-21 17:42 UTC
My flutter app runs well on an i.o.s simulator but does not run when I use an android emulator, also, when I try to create an android build, it runs into the same errors. When I ran `flutter build apk`, it initializes with no errors, resolves dependencies with no errors, but fails to run the task `Gradle task 'assembleRelease'` and ends with `Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0`. Below is a more detailed view of the error logs.

```
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
 
Gradle task 'assembleDebug'... Done                          6.6s
Gradle task assembleDebug failed with exit code 1
```

I tried changing the compileSdkVersion from 27 to 28 in `android/app/build.gradle` but it still throws the same error. What can I do?

**Comment by zoechi** [comment] 2019-02-21 17:56
Can you please post the complete log output from the `flutter -v run -v`

**Comment by zoechi** [comment] 2019-02-21 17:56
Probably a duplicate of #27106

**Comment by abulojoshua1** [comment] 2019-02-22 11:47
Thanks, @zoechi, I will post the Logs of `flutter -v run -v` on #27106.

**Closed** 2019-05-14 16:28 UTC
Labels: waiting for customer response
