### ISSUE TITLE
Nested StatefulWidget resets state when parent's Container parameter is nulled

### ISSUE THREAD

**Issue by doctor-kicks** [flutter/flutter#39633] opened 2019-09-01 04:44 UTC
## Steps to Reproduce

Example:
https://gist.github.com/doctor-kicks/1ed6e6832a96c24c3a5f0cbd2063dbae

1. A Stateful Parent widget has a Container widget, containing a Stateful Child widget.
2. Container color parameter is set dynamically, reacting to Parent state
3. If said color parameter is explicitly set to null, Child widget silently resets its state.

The issue also happens with Container(decoration: null) and possibly others.

Observation: parameters to Row() are asserted to not be null, maybe Container should similarly prevent null parameter values?

## Logs

[        ] Updating files
[ +140 ms] DevFS: Sync finished
[   +2 ms] Syncing files to device Android SDK built for x86... (completed in 2,074ms, longer than expected)
[   +1 ms] Synced 0.9MB.
[   +3 ms] Sending to VM service: _flutter.listViews({})
[   +7 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xe8bdee10, isolate: {type: @Isolate, fixedId: true, id:
isolates/1019754985, name: main.dart$main-1019754985, number: 1019754985}}]}
[   +1 ms] <- accept
[        ] Connected to _flutterView/0xe8bdee10.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +2 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:63423/HX-7O7PRqs4=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+24706 ms] I/flutter (19093): Creating a new child state
[ +337 ms] I/chatty  (19093): uid=10086(com.example.nested_stateful) 1.ui identical 1 line
[        ] I/flutter (19093): Creating a new child state
[ +452 ms] I/flutter (19093): Creating a new child state

```
```

$ flutter analyze
Analyzing nested_stateful...
No issues found! (ran in 1.8s)

```
```

$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/admin/Development/flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M337n
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • Noise Pad                 • e3d6d5600b423d808bc063605e25ca661bb7915c • ios         • iOS 12.4

• No issues found!

```
```

**Comment by GaspardMerten** [comment] 2019-09-01 18:11
The issue also happens with every other parameter of the Container!

**Comment by doctor-kicks** [comment] 2019-09-01 18:53
Doesn't have to be null either, changing the type of e.g. decoration param also exhibits the behavior:
`Container(decoration: _state ? BoxDecoration(...) : CustomDecoration(...))`

**Comment by csells** [comment] 2020-01-13 18:53
I can only get this to repo when I'm setting something in the parent Container to null, i.e. if I swap between two BoxDecorations, it doesn't reset the child's state. Further, this seems like "by design" behavior to me, as the debug output calls it out:

```flutter: Creating a new child state```

Still, I can't imagine why Flutter feels the need to do this. @HansMuller do you have any idea?

**Comment by markusaksli-nc** [comment] 2020-08-18 13:01
Reproducible on the latest master `1.21.0-10.0.pre.135`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.135, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.135 at C:\Development\flutter_master
    • Framework revision 654022aecb (6 hours ago), 2020-08-18 03:01:02 +0300
    • Engine revision b9243713a0
    • Dart version 2.10.0 (build 2.10.0-36.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

If this behavior is intended then this should be labeled a documentation issue because this is not documented in the explanation for when the framework can call [createState](https://master-api.flutter.dev/flutter/widgets/StatefulWidget/createState.html).

**Comment by goderbauer** [comment] 2020-10-14 22:01
This is working as intended, but could be documented better. The container only builds the widgets it needs based on the parameters given and when you change some parameters from null to non-null or vice versa, it will change the shape of the widget tree, which causes the behavior you're seeing. If you want to avoid this, you can give the child of the container a globalkey which will make sure that the child moves to the new position in the modified widget tree.

**Comment by maheshmnj** [comment] 2022-11-25 22:51
Hi @doctor-kicks, As mentioned https://github.com/flutter/flutter/issues/39633#issuecomment-708684047 this is working as intended, Also the stateful widget seems to mention it.

> A [StatefulWidget](https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html) keeps the same [State](https://api.flutter.dev/flutter/widgets/State-class.html) object when moving from one location in the tree to another if its creator used a [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html) for its [key](https://api.flutter.dev/flutter/widgets/Widget/key.html). Because a widget with a [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html) can be used in at most one location in the tree, a widget that uses a [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html) has at most one associated element. The framework takes advantage of this property when moving a widget with a global key from one location in the tree to another by grafting the (unique) subtree associated with that widget from the old location to the new location (instead of recreating the subtree at the new location). The [State](https://api.flutter.dev/flutter/widgets/State-class.html) objects associated with [StatefulWidget](https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html) are grafted along with the rest of the subtree, which means the [State](https://api.flutter.dev/flutter/widgets/State-class.html) object is reused (instead of being recreated) in the new location. However, in order to be eligible for grafting, the widget must be inserted into the new location in the same animation frame in which it was removed from the old location.


<details>
<summary>modified code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(Parent());
}

class Parent extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => ParentState();
}

class ParentState extends State<Parent> {
  int count = 0;
  final key = GlobalKey();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Sample"),
        ),
        body: Center(
          child: Container(
            /////////// PROBLEM LINE: color is dynamically set to null //////
            color: (count % 2 == 1) ? Colors.red : null,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                ElevatedButton(
                  onPressed: () {
                    setState(() {
                      count++;
                    });
                  },
                  child: Text('Parent count: $count'),
                ),
                Child(
                  key: key,
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class Child extends StatefulWidget {
  const Child({super.key});

  @override
  State<Child> createState() => _ChildState();
}

class _ChildState extends State<Child> {
 int count = 0;

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: () {
        setState(() {
          count++;
        });
      },
      child: Text('Child count: $count'),
    );
  }
}
```
</details> 

Provided that this is mentioned in the docs I am going to close this issue. Incase anyone disagrees feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-11-25 22:51 UTC
Labels: easy fix, framework, a: quality, documentation, has reproducible steps, found in release: 1.21
