### ISSUE TITLE
The type of ByteBuffer is incorrect type judgment in defferent  run mode 

### ISSUE THREAD

**Issue by shingohu** [flutter/flutter#28260] opened 2019-02-21 15:04 UTC
The following code print a different result

### run in debug mode, the print is false

```dart
ByteBuffer a = null;
var dataMap = Map<String, dynamic>();
dataMap['data'] = a;
if (dataMap['data'] is ByteBuffer) {
  print(true);
} else {
  print(false);
}
```

```
E:\flutter\socket.io-tester>flutter doctor -v
[√] Flutter (Channel dev, v1.2.1, on Microsoft Windows [Version 10.0.17134.523], locale zh-CN)
    • Flutter version 1.2.1 at D:\software\flutter\tools\flutter
    • Framework revision 8661d8aecd (7 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\software\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\software\AndroidSdk
    • Java binary at: D:\software\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.3)
    • Android Studio at D:\software\Android Studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • A0001 • d4751002 • android-arm • Android 7.1.2 (API 25)
```

**Comment by zoechi** [comment] 2019-02-21 15:06
@mraleph ?

**Comment by aartbik** [comment] 2019-02-21 17:47
This is as plain as bugs come :-)

JIT-run
false

AOT-run
true

**Comment by aartbik** [comment] 2019-02-21 18:38
Looks like the bug is introduced by AOT's TryReplaceInstanceOfWithRangeCheck() method, probably not properly accounting for the null value.

**Comment by aartbik** [comment] 2019-02-21 20:38
This particular transformation replaces the "is ByteBuffer"

v9 <- InstanceCall:20( _simpleInstanceOf@0150898<0>, v6, v8 IC[0: ])

with the cid range check [135,138]. However, the null cid (136) is inside this range.

**Comment by aartbik** [comment] 2019-02-21 21:41
Here is what happens in HierarchyInfo::BuildRangesFor(). At first glance it seems the continue should account for still open ranges, but I am not very familiar with this code yet (and it has been around for a bit now).

135 is the first cid that "succeeds"
136 continue on null cid
137 continue on dyn cid
138 continue on void cid
139 is the first cid that "fails", and thus closes the range as [135,138]

@mkustermann

**Comment by aartbik** [comment] 2019-02-21 23:04
Proposed fix out for review.

**Comment by mkustermann** [comment] 2019-02-22 08:28
@aartbik I believe the issue here is that this functionality was intended for `as X` checks only, which do allow `null`, but it was enabled in `is X` checks as well.

**Comment by aartbik** [comment] 2019-02-22 16:29
For sure. The "as" and "is" have different requirements related to include/exclude/dontcare when building the Cid ranges.

**Comment by aartbik** [comment] 2019-02-25 23:09
Fixed in Dart ToT, but this needs an engine/flutter roll before it hits the Flutter ToT.

**Comment by aartbik** [comment] 2019-03-04 23:26
Engine roll dart e94e797d7b..9450c6d829 (8 commits) brings in last part of fix.

**Closed by aartbik** 2019-03-04 23:26 UTC
Labels: dependency: dart, engine, waiting for PR to land (fixed)
