### ISSUE TITLE
Flutter build is returning with 0 despite compilation failed

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#86011] opened 2021-07-07 09:22 UTC
Hi,

If you build flutter, and an error occours, I would expect that the returncode is not zero. But it is.
It would be much easier to integrate a flutter build in another software if the returncode would depend on the result.

**Comment by TahaTesser** [comment] 2021-07-07 11:46
Hi @Wissperwind 
Can you please provide an example where it returns "0"? Also, explain your proposal in detail
Thank you

**Comment by jonahwilliams** [comment] 2021-07-07 15:38
duplicate of https://github.com/flutter/flutter/issues/85989

**Closed by jonahwilliams** 2021-07-07 15:38 UTC
Labels: in triage, waiting for customer response
