### ISSUE TITLE
The current Flutter SDK version is 0.0.0-unknown

### ISSUE THREAD

**Issue by xixixx** [flutter/flutter#64699] opened 2020-08-27 08:08 UTC
i have problem when i import new dart package
  The current Flutter SDK version is 0.0.0-unknown.

Because demo depends on fluro >=1.5.0 which requires Flutter SDK version >=1.2.0, version solving failed.
pub get failed (1; Because demo depends on fluro >=1.5.0 which requires Flutter SDK version >=1.2.0, version solving failed.)

I use the 
git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor
 
but it does not work   there new file version show :
 0.0.0-unknown

**Comment by hamdikahloun** [comment] 2020-08-27 08:23
Hi @xixixx 

Please can you provide your flutter doctor -v, flutter run -v, pubspec.yaml and a minimal reproducible code sample that does not use 3rd party plugins.

Thank you

**Comment by pedromassangocode** [comment] 2020-08-27 08:44
Hi @xixixx 
Looks like you are not using a valid Flutter channel, please run the following commands:
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

For the package version conflict, please see [Conflict resolution](https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution) section to see how to solve this version conflict.

Closing as this is not an issue with flutter itself. If you disagree please write in the comments bellow and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-27 08:44 UTC
