### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by fiskindal** [flutter/flutter#78953] opened 2021-03-24 09:03 UTC
## Command
```
flutter run
```

I tried running flutter web with rpi4 ubuntu 20.10 chromium browser.

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#5      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:775:57)
#6      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:734:54)
<asynchronous suspension>
#7      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:517:41)
<asynchronous suspension>
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.223, on Linux, locale tr_TR.UTF-8)
    • Flutter version 2.1.0-13.0.pre.223 at /home/fiskindal/snap/flutter/common/flutter
    • Framework revision 891511d58f (11 hours ago), 2021-03-23 14:57:01 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-arm64    • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 83.0.4103.116 built on Debian bullseye/sid, running on
      Debian bullseye/sid

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 198df796aa80073ef22bdf249e614e2ff33c6895

**Comment by pedromassangocode** [comment] 2021-03-24 09:05
Closing as duplicate of https://github.com/flutter/flutter/issues/68958.

**Closed by pedromassangocode** 2021-03-24 09:05 UTC
Labels: in triage
