### ISSUE TITLE
Gray weird layer after send and app to playstore

### ISSUE THREAD

**Issue by juniorsistemasufms** [flutter/flutter#58128] opened 2020-05-27 22:03 UTC
I was developing an app normally, the apk generated by android studio is everything ok. I started to have some problem when I sended my frist version to playstore google.  I did to upload correctly but when the google take me to do the download from playstore, it come the problem. The login page is ok but when I acess the main page of the app, there is a grey layter over the drawer widget  the contain the main menu of the of (I´ll send a print screen). Beside that, over the google map widget on the main page also there is the same grey shape like a layer.  I need some help to solve them because I didt find  any information on internet about this issue. This error have happend just after send the apk ou app bundle to playstore, in all test whit apk is everything ok.

I took in this message 4 images.  2 whit de issue and 2 correct.

![correto 2](https://user-images.githubusercontent.com/30843147/83076838-a423f500-a04c-11ea-892c-41069d6cf50f.jpeg)

![correto 1](https://user-images.githubusercontent.com/30843147/83076831-a1290480-a04c-11ea-9199-a40dd558bd36.jpeg)

![erro 1](https://user-images.githubusercontent.com/30843147/83069192-df6bf700-a03f-11ea-9d56-cd3740870c37.jpeg)
![erro 2](https://user-images.githubusercontent.com/30843147/83069195-e0048d80-a03f-11ea-8055-ab6a19616b51.jpeg)

**Comment by TahaTesser** [comment] 2020-05-28 10:28
Hi @juniorsistemasufms 
Can you please provide your `flutter doctor -v`, your `flutter run --release  --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by juniorsistemasufms** [comment] 2020-05-28 12:05
doctor --verbose
[✓] Flutter (Channel master, 1.19.0-2.0.pre.143, on Mac OS X 10.15.4 19E287, locale pt-BR)
    • Flutter version 1.19.0-2.0.pre.143 at /Users/lourivaljunior/Documents/flutter
    • Framework revision 9d58a87066 (5 days ago), 2020-05-22 22:37:01 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lourivaljunior/Documents/Android_sdk
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = /Users/lourivaljunior/Documents/Android_sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by juniorsistemasufms** [comment] 2020-05-28 13:13
`DefaultTabController( // Added
length: 4, // Added
initialIndex: 0, //Added
child: Scaffold(
key: _scaffoldKey,
floatingActionButton:
this.pilotoTemVooAssumido=='1' ?
this.tabIndex==0  ?
FloatingActionButton(
backgroundColor: Colors.redAccent,
onPressed: () async {
},
child: Icon(Icons.delete_forever,color: Colors.white,),
) : null :  null,
appBar: AppBar(
backgroundColor: Color.fromRGBO(37, 67, 154, 1),
//LARANJA  Color.fromRGBO(249, 138, 18, 1)  AZUL "Color.fromRGBO(37, 67, 154, 1)"
title: Text(
"Ata Brasil VA", style: TextStyle(color: Colors.white),),
iconTheme: new IconThemeData(color: Colors.white),
),
drawer: buildDrawer(),
body: buildBody(tabIndex),
bottomNavigationBar: BottomNavigationBar(

selectedItemColor: Color.fromRGBO(249, 138, 18, 1),
unselectedItemColor: Colors.white,
//backgroundColor: Color.fromRGBO(249, 138, 18, 1) ,
backgroundColor: Color.fromRGBO(37, 67, 154, 1),
currentIndex: tabIndex,
onTap: (int index) {
},
items: [
BottomNavigationBarItem(
icon: Icon(Icons.home),
title: Text('Home'),
),
BottomNavigationBarItem(
icon: Icon(Icons.airplanemode_active),
title: Text('Últimos Voos'),
),
BottomNavigationBarItem(
icon: Icon(Icons.map),
title: Text('Ao Vivo'),
),
]),
));`


`Widget buildDrawer() {
  return Drawer(
    child: Column(
      children: <Widget>[
        Container(
          color: Color.fromRGBO(37, 67, 154, 1),
          padding: const EdgeInsets.fromLTRB(0, 0, 0, 0),
          child: Expanded(
              flex: 2,     /*backgroundColor: Color.fromRGBO(249, 138, 18, 1),  //LARANJA Color.fromRGBO(37, 67, 154, 1)*/
              child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    UserAccountsDrawerHeader(
                      decoration: BoxDecoration(
                        color: Color.fromRGBO(37, 67, 154, 1),
                      ),
                      arrowColor: Colors.white,
                      accountName: Text(this.pilotoMatricula+" - "+this.pilotoNome,style: TextStyle(color: Colors.white),),
                      accountEmail: Text(this.pilotoEmail,style: TextStyle(color:Color.fromRGBO(249, 138, 18, 1))),
                      onDetailsPressed: () async {
                      },
                      currentAccountPicture:
                      GestureDetector(
                        onTap: () async {
                        },
                        child:  Container(
                          child:CircleAvatar(
                            radius: 50,
                            backgroundImage: NetworkImage(this.pilotoFoto),
                          ),
                        ),
                      ),
                    ),
                  ])
          ),
        ),
        Expanded(
            flex: 5,
            child: ListView(
              shrinkWrap: true,
              children: <Widget>[
                buildSeparators("Meu Cadastro"),
                buildTile(
                  "Perfil",
                  "/perfil",
                  'assets/img/perfil.jpg',
                )
              ],
            ))
      ],
    ),
  );
}`

**Comment by juniorsistemasufms** [comment] 2020-05-28 13:14
Widget buildDrawer() {
  return Drawer(
    child: Column(
      children: <Widget>[
        Container(
          color: Color.fromRGBO(37, 67, 154, 1),
          padding: const EdgeInsets.fromLTRB(0, 0, 0, 0),
          child: Expanded(
              flex: 2,     /*backgroundColor: Color.fromRGBO(249, 138, 18, 1),  //LARANJA Color.fromRGBO(37, 67, 154, 1)*/
              child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    UserAccountsDrawerHeader(
                      decoration: BoxDecoration(
                        color: Color.fromRGBO(37, 67, 154, 1),
                      ),
                      arrowColor: Colors.white,
                      accountName: Text(this.pilotoMatricula+" - "+this.pilotoNome,style: TextStyle(color: Colors.white),),
                      accountEmail: Text(this.pilotoEmail,style: TextStyle(color:Color.fromRGBO(249, 138, 18, 1))),
                      onDetailsPressed: () async {
                      },
                      currentAccountPicture:
                      GestureDetector(
                        onTap: () async {
                        },
                        child:  Container(
                          child:CircleAvatar(
                            radius: 50,
                            backgroundImage: NetworkImage(this.pilotoFoto),
                          ),
                        ),
                      ),
                    ),
                  ])
          ),
        ),
        Expanded(
            flex: 5,
            child: ListView(
              shrinkWrap: true,
              children: <Widget>[
                buildSeparators("Meu Cadastro"),
                buildTile(
                  "Perfil",
                  "/perfil",
                  'assets/img/perfil.jpg',
                )
              ],
            ))
      ],
    ),
  );
}

**Comment by jonahwilliams** [comment] 2020-05-30 18:07
This is not a rendering issue - in release mode the red crash screen is replaced with a grey screen.

**Comment by TahaTesser** [comment] 2020-06-01 09:05
Hi @juniorsistemasufms 
As Jonah mentioned,  this is a crash screen, probably caused by your code and code sample is not runnable and missing components
Can you please provide a runnable minimal complete reproducible code sample?
Thank you

**Comment by juniorsistemasufms** [comment] 2020-06-01 15:44
Thanks  @TahaTesser   and @jonahwilliams 

The stranger is that this grey screen just have been showing after I send do play store the signed app bundle being that during all test that I did everything looks like ok.

**Comment by TahaTesser** [comment] 2020-06-02 07:03
@juniorsistemasufms 
This grey screen is for release mode, you can try to reproduce by running your app in release mode `flutter run --release`. Also try to isolate the code for where the issue is happening and provide code sample for it
Thank you

**Comment by TahaTesser** [comment] 2020-07-01 10:23
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-01 10:23 UTC
Labels: in triage, waiting for customer response

**Comment by cybertheory** [comment] 2021-05-25 17:59
Hey! I am having the same issue. This is only in release mode. And I tried to run 
```
flutter run --release
```
This just resulted in the app running correctly. I also ran flutter dev tools and nothing seemed out of place.
This happened after we pushed to Testflight for beta deployment.
Can we get this issue re-opened? Thank You!

I am not sure what part of the code exactly is causing the error, and do not want to confuse anyone further with an entire dump of our Drawer widget.

**Comment by cybertheory** [comment] 2021-05-25 18:02
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version
    10.0.19042.985], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-05-26 12:50
@cybertheory

This is not related to this issue. For any production, app you need to some sort of crash reporting so you can get production crash reports and this would also contain device details . If you can provide any crash report related to Flutter or image_picker, please file a ne wissue

**Comment by TahaTesser** [comment] 2021-05-26 12:50
@cybertheory

This is not related to this issue. For any production, app you need to some sort of crash reporting so you can get production crash reports and this would also contain device details . If you can provide any crash report related to Flutter or image_picker, please file a ne wissue
