### ISSUE TITLE
IconButton's splash radius is too large on an AppBar

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#64702] opened 2020-08-27 09:14 UTC
The IconButton does follow the default material specs and has a splash radius of about 24px. This is definitely not suitable for auto generated icons like the back button and the scaffold drawer button.

Though the material design does specify a set splash radius, an overflow is definitely not intended. The icon button's splash always overflows in `AppBar`s.

Possible solutions - 

1.  Allow setting the default splash radius for all auto generated icon buttons in `AppBar`s.

2. Set the default splash radius so that it doesnt overflow atleast  - in the defaul `AppBar`

**Comment by sidrao2006** [comment] 2020-08-27 09:16
Possibly related to inactive issue - #31194

**Comment by darshankawar** [comment] 2020-08-27 12:23
Hi @sidrao2006,
Can you provide a screenshot of the splash effect that overflows the app bar ?
Also, provide `flutter doctor -v`.
Thanks.

**Comment by sidrao2006** [comment] 2020-08-27 12:54
It was easier to use a dartpad for this as there were very few changes needed.
[Link to dartpad](https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b)

> Changes made
> ```dart
> actions: [
>         IconButton(
>           icon: Icon(Icons.ac_unit),
>           onPressed: () => print('Click'),
>         ),
>       ],
> ```

**Comment by dnfield** [comment] 2020-08-27 14:55
Why not just set the splashSize property to your desired value?

**Comment by sidrao2006** [comment] 2020-08-27 15:29
> Why not just set the splashSize property to your desired value?

@dnfield it is not possible to the `splashRadius` in auto generated `IconButton`s like the back button and the open drawer button.

**Comment by dnfield** [comment] 2020-08-27 15:56
Ahh, ok. It sounds like `appBar` may need to have some extra property to pass through to `iconButton`s it creates. 

I did check on some other Android apps and it looks ike the splash does not typically overflow the bar.

That said, app bars can be different sizes, and some people may _want_ the overflow, so whatever is done here shouldn't be a change to defaults on `IconButton`.

/cc @willlarche  @rami-a who might know the right person on the Material team to look at this.

**Comment by dnfield** [comment] 2020-08-27 16:06
Also, based on a quick look at this code: https://github.com/flutter/flutter/blob/f2c2b02893fe8e099d03f43dc12fb777b00ab962/packages/flutter/lib/src/material/ink_highlight.dart#L122

Seems a little fishy to me - I wonder if there's some way we should be making sure that the highlight is drawn as a percentage of the constraints rather than as a fixed amount.

**Comment by rami-a** [comment] 2020-08-27 17:05
Thanks for bringing this up @sidrao2006. I think that there's definitely an improvement we can make here to allow for the out-of-the-box IconButtons inside app bars (Back button, menu button) to use a smaller splash radius. I've reached out to our designers to get some additional guidance on this and I'll report back once I have some.

**Comment by sidrao2006** [comment] 2020-08-27 17:32
I think I was able to fix it, taking @dnfield 's suggestion in mind. Now, I just need to run some tests

**Comment by Hixie** [comment] 2020-08-27 18:44
> The IconButton does follow the default material specs and has a splash radius of about 24px.

I thought we did follow the specs... they may have changed, though. Do you have a link to the spec we should follow?

**Comment by Hixie** [comment] 2020-08-27 18:46
As far as how to control the splash size, that seems like something that we should put in the theme. cc @HansMuller

**Comment by sidrao2006** [comment] 2020-08-28 02:25
@Hixie , thanks for replying, as I have mentioned, flutter **does** indeed follow the material spec.

Amazing, I look into the themes and open a pr. But I am still confused whether to apply that to all the `IconButton`s (which is a more predictable behaviour) or apply it only to the `IconButton`s generated by `autoImplyLeading`

**Comment by darshankawar** [comment] 2020-08-28 06:30
This is how it looks on latest stable (1.20.2) when we tap on iconButton in appbar:

![64702](https://user-images.githubusercontent.com/67046386/91528830-d6800f80-e925-11ea-95e7-cf696bfee7eb.png)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

**Comment by sidrao2006** [comment] 2020-08-28 06:47
@darshankawar , this problem existed even before `v1.20.0`

**Comment by sidrao2006** [comment] 2020-08-28 06:54
@HansMuller, @dnfield , @Hixie can you please review my solution plan

1. Create a property named `iconButtonSplashRadius` in `ThemeData` and then set the default value to overflow by following the material spec.

2. Add this property to `AppBarTheme` as well so that it can be customized only for the app bar too.

3. Set `IconButton.splashRadius` to `Theme.of(context).iconButtonSplashRadius` in icon_button.dart.

On approval, I will add these to my PR's TODO.

**Comment by willlarche** [comment] 2020-08-28 14:33
@rami-a is working with designers to confirm the spec. The specs change and what's published isn't always the latest guidance. We're proud that on Flutter we often get the latest guidance before it's even published so our clients can have the benefit of new features and improvements. 

Also, sometimes the spec does change without alerting us that we need to make a code change. This happens much less often these days but happened a lot in earlier years. 

Either way, we need to confirm what the designers want us to do here. And @rami-a is working on that. So, sit tight and we'll get back to you when this information request comes up in the queue!

**Comment by sidrao2006** [comment] 2020-08-28 14:38
Thanks a lot @willlarche

**Comment by sidrao2006** [comment] 2020-09-01 05:35
Waiting for #64789 to be merged

**Comment by ReniDelonzek** [comment] 2021-06-18 03:30
Any solution for this? The current size is definitely inadequate. I believe that allowing this property to be set by the application's theme would be enough.

**Comment by bcbcbcbcbcl** [comment] 2021-06-19 12:32
Any update on this?

**Comment by get6** [comment] 2021-07-08 11:32
IconButton's splashRadius variable is 35.0(Because default set is Material.defaultSplashRadius attribute).
So when I use IconButton in actions at AppBar. I use it like this.
```
actions: [
        IconButton(
          onPressed: () {},
          icon: const Icon(Icons.add),
          splashRadius: Material.defaultSplashRadius / 2,
        )
],
```

**Comment by meiraxx** [comment] 2021-07-10 21:05
When will we be able to control splashRadius from theme (including having the button themes for the appBar theme)?

**Comment by meiraxx** [comment] 2021-07-10 21:07
> Material.defaultSplashRadius / 2

Doing that doesn't help when we're using widgets that include IconButton inside of it. We need something to control splashRadius OUTSIDE of a given widget

**Comment by meiraxx** [comment] 2021-07-10 21:08
> IconButton's splashRadius variable is 35.0(Because default set is Material.defaultSplashRadius attribute).
So when I use IconButton in actions at AppBar. I use it like this.```actions: [
        IconButton(
          onPressed: () {},
          icon: const Icon(Icons.add),
          splashRadius: Material.defaultSplashRadius / 2,
        )
],```

Doing that doesn't help when we're using widgets that include IconButton inside of it. We need something to control splashRadius OUTSIDE of a given widget

**Comment by LarMaySee** [comment] 2021-08-22 08:42
Use splashRadius in IconButton

**Comment by TahaTesser** [comment] 2021-11-26 12:29
This will be fixed by https://github.com/flutter/flutter/pull/93478

**Comment by TahaTesser** [comment] 2021-12-01 18:27
https://github.com/flutter/flutter/issues/64702 landed

**Comment by TahaTesser** [comment] 2021-12-03 07:46
https://github.com/flutter/flutter/pull/93478 is reverted, I am working on reimplementation

**Comment by Enzodtz** [comment] 2022-02-15 00:34
What is the status of this? Thanks

**Comment by GayatriDunakhe** [comment] 2022-07-27 03:16
The icon splashRadius look this so 
![image](https://user-images.githubusercontent.com/74578232/181152918-8063c908-f854-4216-89f3-f7dc7659c124.png)

I try to do this -
splashRadius: Material.defaultSplashRadius / 2
then it dosen't show any click moment on that app bar

![image](https://user-images.githubusercontent.com/74578232/181153033-fc310840-6323-4345-a982-f52cac5dac1a.png)

How I deal with this?

**Comment by QuncCccccc** [comment] 2022-07-27 22:23
Hi! The IconButton component is recently updated to the Material Design 3 [spec](https://m3.material.io/components/icon-buttons/overview), so the splash radius issue will no longer exist. Here's the issue link which contains the related PRs: https://github.com/flutter/flutter/issues/103528

Please let me know if there are any questions:) Thanks!

**Comment by FeodorFitsner** [comment] 2022-08-02 19:42
Is it by design that `IconButton` in `AppBar` is not having a round splash now?

![image](https://user-images.githubusercontent.com/5041459/182459831-156690ef-a045-48f3-8b4e-a52600b679f2.png)

**Comment by QuncCccccc** [comment] 2022-08-25 16:37
The PR is reverted, so I re-opened this issue. Will add a reland soon.

**Closed** 2022-09-01 19:03 UTC
Labels: framework, f: material design, a: quality, passed first triage, has reproducible steps, found in release: 1.20
