### ISSUE TITLE
Flutter Hot reload/Hot restart gets stuck on reassemble in callbackDispatcher isolate

### ISSUE THREAD

**Issue by knaeckeKami** [flutter/flutter#84347] opened 2021-06-10 13:08 UTC
Edit:

If you're reading this because the issue was referenced and you can't get hot reload to work, here's a TL;DR:

This happens when using fvm < 2.2.0. To resolve the issues with hot reload, upgrade your fvm installation.

Original Post:

I have a problem with my Flutter project, which causes Hot Reload / Hot Restart to hang indefinitely sometimes.
It happens on Android and iOS devices, real and simulator/emulator.
It does not happen on every time I use hot reload/hot restart, but after a few times it usually gets triggered fairly reliably. 

Here a gist of the debug output of flutter attach --verbose:

https://gist.github.com/knaeckeKami/46970ac3073ff38d367f9ff49cc98322

Relevant lines:

```
[        ] Performing hot reload...
[  +38 ms] Scanned through 1349 files in 29ms
[        ] Syncing files to device iPhone 12 Pro Max...
[        ] Compiling dart to kernel with 1 updated files
[   +5 ms] <- recompile package:neocortex_mobile/main.staging.dart be2a7fa8-087d-4693-a996-2cd6d1b763f1
[        ] package:neocortex_mobile/matrix/chat.dart
[        ] <- be2a7fa8-087d-4693-a996-2cd6d1b763f1
[ +233 ms] Updating files.
[  +14 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device iPhone 12 Pro Max... (completed in 254ms)
[        ] Synced 0.1MB.
[ +275 ms] <- accept
[        ] reloaded 1 of 2938 libraries
[  +70 ms] Reassembling application
[+2006 ms] This is taking a long time; will now check for paused isolates.
[  +90 ms] Found 0 newly paused isolate(s).
```

After the line 

` Found 0 loadPausedIsolatesFound newly paused isolate(s).` 

the tools just hangs and does not react to any commands. 
After quitting the tool with STRG-C and re-attaching to the running flutter app, I can hot reload/ hot restart again.

After digging a bit, I found that the tool gets stuck on this line:

https://github.com/flutter/flutter/blob/07921b561d6f79a5cfe0401b1b081a5d581bd771/packages/flutter_tools/lib/src/run_hot.dart#L1265

The hot reload actually works i.e. I see the changes that I have made deployed on the device, it's just that the tool keeps hanging here.
I tried commenting out this line, which made hot reload and hot restart work again reliably without hanging (but I don't know about possible side effects that this causes).

I added more debug logging to this file to get an idea of what's going on. Here's a gist of the output of run_hot.dart with more logging added:

https://gist.github.com/knaeckeKami/566f920560a351197ff1d56b72add98b

The modified run_hot.dart with additional logging is here:
https://gist.github.com/knaeckeKami/af9cbd138ef55c1f2e8a3dd45ec821a0 

My interpretation of this (I don't really know what's going on here): 
- There is an isolate called main, for which the reassembleFuture completes.
See the lines
```
[  +49 ms] found isolate main isolates/1112832209456463 [Event kind: Resume, timestamp: 1623258672622]
```
and
```
[   +2 ms] finished reassemble for isolates/1112832209456463
```
- There is another isolate called callbackDispatcher, where the reassambleFuture never completes. (no lines "finished reassemble for... printed for this isolate)

## Steps to Reproduce

Unfortunately, I am not able to produce a minimal example of this. It only happens in a big-ish production app.

I don't know much about the internals of the hot reload/ hot restart system, so I would not know how to start trying to reproduce this. Obviously, this works with a newly created flutter app. But I'm happy to dig deeper when someone with more insight gives me a few pointers.

```
 fvm flutter doctor --verbose
Building flutter tool...
[✓] Flutter (Channel unknown, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/kami/fvm/versions/2.2.1
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/kami/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/kami/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 1C848851-B380-4185-B9D5-54C06C495E9D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.101

• No issues found!
```

</details>

Same results happen also on the current master channel.

**Comment by jonahwilliams** [comment] 2021-06-10 15:48
> Flutter (Channel unknown, 2.2.1,

You are not on a valid channel, as a result you're probably using an odd mix of hot reload experiments that aren't meant to be in stable. (This is good information for fixing those btw).

You should either use `fluttter upgrade/channel` to restore things or download a new Flutter SDK

**Comment by knaeckeKami** [comment] 2021-06-10 21:11
Oh yeah sorry. This probably happened due to me using fvm as flutter version manager and then adding some local commits to the run_hot.dart file to get more information.

But I have the same behavior when using the plain flutter 2.2.1 from stable without fvm.

```
 flutter doctor -v
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/kami/development/flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/kami/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/kami/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 1C848851-B380-4185-B9D5-54C06C495E9D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.101

• No issues found!
```

I can also reproduce it this behavior on the current master channel.

Output from flutter run on the current stable branch:

````
[  +49 ms] Checking for advertised Dart observatories...
[+5027 ms] Checking for available port on com.diagnosia.fachinformation.stage._dartobservatory._tcp.local
[   +2 ms] Checking for authentication code for com.diagnosia.fachinformation.stage._dartobservatory._tcp.local
[  +62 ms] Connecting to service protocol: http://127.0.0.1:58743/8W-PghaAbKY=/
[ +110 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:58743/8W-PghaAbKY=/.
[ +742 ms] Warning: Failed to start DDS: JSON-RPC error 100: Feature is disabled data: {details: A DDS instance is already connected at http://127.0.0.1:58743/8W-PghaAbKY=/., request: {jsonrpc: 2.0, method: _yieldControlToDDS, id: 12, params: {uri: http://127.0.0.1:64832/XaypXIXetoI=/}}}
[  +58 ms] Successfully connected to service protocol: http://127.0.0.1:58743/8W-PghaAbKY=/
[  +16 ms] DevFS: Creating new filesystem on the device (null)
[   +2 ms] DevFS: Creating failed. Destroying and trying again
[        ] DevFS: Deleting filesystem on the device (null)
[   +3 ms] DevFS: Deleted filesystem on the device (null)
[   +2 ms] DevFS: Created new filesystem on the device (file:///Users/kami/Library/Developer/CoreSimulator/Devices/1C848851-B380-4185-B9D5-54C06C495E9D/data/Containers/Data/Application/70C3E6B1-3162-43B0-A6A2-076E88F59C55/tmp/neocortex_mobile_fluttereKACNb/neocortex_mobile_flutter/)
[   +2 ms] Updating assets
[ +507 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +5 ms] Syncing files to device iPhone 12 Pro Max...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[  +11 ms] /Users/kami/fvm/versions/2.2.1/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/kami/fvm/versions/2.2.1/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/kami/fvm/versions/2.2.1/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill /var/folders/yy/9y9fhbgj6bv24d7gk_hdmt140000gn/T/flutter_tools.uMquUU/flutter_tool.Dfkoj4/app.dill --packages /Users/kami/diagnosia/neocortex-mobile/neocortex_mobile_flutter/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/e191c212e914ccf704fa28187f4e0e18.cache.dill.track.dill --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy --no-sound-null-safety
[  +22 ms] <- compile package:neocortex_mobile/main.staging.dart
[+32489 ms] Updating files.
[        ] DevFS: Sync finished
[  +29 ms] Syncing files to device iPhone 12 Pro Max... (completed in 32.5s)
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[  +10 ms] Connected to _flutterView/0x7fec4081cc20.
[        ] Connected to _flutterView/0x7fec40a1a820.
[   +6 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[        ] An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:58743/8W-PghaAbKY=/.,
[        ] The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:9103?uri=http%3A%2F%2F127.0.0.1%3A58743%2F8W-PghaAbKY%3D%2F.%2C
r
[+2223 ms] Initializing file store
[   +5 ms] Done initializing file store
[  +32 ms] gen_localizations: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/kami/fvm/versions/2.2.1/packages/flutter_tools/lib/src/build_system/targets/localizations.dart,/Users/kami/diagnosia/neocortex-mobile/neocortex_mobile_flutter/l10n.yaml,/Users/kami/diagnosia/neocortex-mobile/neocortex_mobile_flutter/lib/l10n/translations_de.arb,/Users/kami/diagnosia/neocortex-mobile/neocortex_mobile_flutter/.dart_tool/flutter_gen/gen_l10n/translations_de.dart,/Users/kami/diagnosia/neocortex-mobile/neocortex_mobile_flutter/.dart_tool/flutter_gen/gen_l10n/translations.dart}
[ +214 ms] gen_localizations: Complete
[   +9 ms] complete
[   +1 ms] Performing hot reload...
[  +35 ms] Scanned through 1349 files in 24ms
[        ] Syncing files to device iPhone 12 Pro Max...
[        ] Compiling dart to kernel with 2 updated files
[   +6 ms] <- recompile package:neocortex_mobile/main.staging.dart 9657a23e-d6d3-425e-b6c6-07ac98f66e42
[        ] package:flutter_gen/gen_l10n/translations.dart
[        ] package:flutter_gen/gen_l10n/translations_de.dart
[        ] <- 9657a23e-d6d3-425e-b6c6-07ac98f66e42
[ +189 ms] Updating files.
[  +36 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device iPhone 12 Pro Max... (completed in 234ms)
[        ] Synced 0.1MB.
[ +310 ms] <- accept
[   +2 ms] reloaded 2 of 2938 libraries
[ +130 ms] Reassembling application
[ +464 ms] Hot reload performed in 1,169ms.
[        ] Performing hot reload... (completed in 1,180ms)
[   +1 ms] Reloaded 2 of 2938 libraries in 1,455ms.
r
[+1305 ms] Skipping target: gen_localizations
[        ] complete
[        ] Performing hot reload...
[  +25 ms] Scanned through 1349 files in 20ms
[        ] Syncing files to device iPhone 12 Pro Max...
[        ] Compiling dart to kernel with 0 updated files
[   +5 ms] <- recompile package:neocortex_mobile/main.staging.dart ac41e043-a149-4ba5-9de1-5666fd96090e
[        ] <- ac41e043-a149-4ba5-9de1-5666fd96090e
[  +49 ms] Updating files.
[  +11 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 12 Pro Max... (completed in 67ms)
[        ] Synced 0.0MB.
[ +116 ms] Reassembling application
[ +125 ms] Hot reload performed in 334ms.
[        ] Performing hot reload... (completed in 336ms)
[        ] Reloaded 0 libraries in 339ms.
r
[+7814 ms] Skipping target: gen_localizations
[        ] complete
[        ] Performing hot reload...
[  +21 ms] Scanned through 1349 files in 16ms
[        ] Syncing files to device iPhone 12 Pro Max...
[        ] Compiling dart to kernel with 1 updated files
[   +4 ms] <- recompile package:neocortex_mobile/main.staging.dart a05049be-4898-430d-862a-cb0218e612a2
[        ] package:neocortex_mobile/matrix/chat.dart
[        ] <- a05049be-4898-430d-862a-cb0218e612a2
[ +168 ms] Updating files.
[   +9 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 12 Pro Max... (completed in 183ms)
[        ] Synced 0.1MB.
[ +341 ms] <- accept
[        ] reloaded 1 of 2938 libraries
[  +95 ms] Reassembling application
[+2005 ms] This is taking a long time; will now check for paused isolates.
[  +80 ms] Found 0 newly paused isolate(s).
r
[+4988 ms] Ignoring terminal input: "r" because we are busy.
r
[+2140 ms] Ignoring terminal input: "r" because we are busy.
r
[+93220 ms] Ignoring terminal input: "r" because we are busy.
r
[ +735 ms] Ignoring terminal input: "r" because we are busy.
```

**Comment by jonahwilliams** [comment] 2021-06-10 22:16
Are you using any background execution? callbackDispatcher sounds like a background API thingy

**Comment by jonahwilliams** [comment] 2021-06-10 22:22
Might be related to https://github.com/flutter/flutter/issues/54395 , but I've never seen it get stuck like this before

**Comment by jonahwilliams** [comment] 2021-06-11 17:19
Are you using any plugins that do background execution? It would help a lot to know what they are just so I have a chance to reproduce this.

**Comment by knaeckeKami** [comment] 2021-06-11 17:31
I don't use workmanager, but I do use firebase messaging with background push handling and I use an Isolate with for sqlite access (using moor https://moor.simonbinder.eu/docs/advanced-features/isolates/ ).

I will try to remove these background handling features and see if I can still reproduce it.


Is there a way to somehow get more information on the vmservice Isolate, e.q. the entry point of the code it is running?
Because I don't really know where it comes from, from what I have seen, neither moor nor firebase messaging spawn an isolate with this name.

**Comment by jonahwilliams** [comment] 2021-06-11 17:49
Thanks for the info, let me look into what moor/sqlite are doing with background execution

**Comment by jonahwilliams** [comment] 2021-06-11 17:54
Ahh, I see callbackDispatcher is frequently used as the background execution name. I wonder if that isolate is pegged or something, or perhaps is short lived. We shouldn't be trying to reassemble those isolates anyway

**Comment by jonahwilliams** [comment] 2021-06-11 17:57
@knaeckeKami if I post a diff/PR for a tool modification to work around this, would you be willing to try it out and see if you can still repro the issue?

**Comment by knaeckeKami** [comment] 2021-06-11 18:15
> @knaeckeKami if I post a diff/PR for a tool modification to work around this, would you be willing to try it out and see if you can still repro the issue?

Yeah, sure.

**Comment by jonahwilliams** [comment] 2021-06-11 18:53
I have a potential fix in https://github.com/flutter/flutter/pull/84457, the diff can't be applied to 2.2 because a lot of other stuff changed, but you could checkout the PR and see if it repros still

**Comment by knaeckeKami** [comment] 2021-06-11 20:09
Thanks!
Good news and bad news:

Bad news: your PR does not fix my issue.

Good news: I found a way to get hot reload working again, the culprit seems to be flutter_downloader. (https://pub.dev/packages/flutter_downloader )
This package also spawns a background isolate, I didn't think of this.

If I omit the call to  `FlutterDownloader.initialize()', then I can use hot reload/ hot restart as expected.
Maybe I can produce a minimal example project now.

**Comment by jonahwilliams** [comment] 2021-06-11 20:49
Ahh sweet, well I can look into flutter_downloader to see where it is getting stuck too

**Comment by jonahwilliams** [comment] 2021-06-11 20:50
Ahh I see, since it runs `WidgetsFlutterBinding.ensureInitialized();` it _will_ have a reassemble method registered so my fix didn't skip it

**Comment by knaeckeKami** [comment] 2021-06-11 21:08
I was able to reproduce this in the example/ app in the flutter_downloader package.
https://pub.dev/packages/flutter_downloader 

I used flutter from #84457, and an iOS simulator.
just run the app, add some minor changes (like changing the `title` of `MyHomePage`, run hot reload.
If it succeeds, repeat (it triggers reliably after 2-3 times for me)

```
[ +106 ms] DevTools activation throttled until 2021-06-12 01:15:19.616742.
[ +574 ms] The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:9104?uri=http%3A%2F%2F127.0.0.1%3A51016%2FIdVyMc02t6M%3D%2F
[+3539 ms] Skipping target: gen_localizations
[   +1 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[   +1 ms] Performing hot reload...
[  +37 ms] Scanned through 522 files in 30ms
[   +4 ms] Syncing files to device iPhone 12 Pro Max...
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:flutter_downloader_example/main.dart 9b2a5a1b-acc8-45e1-b9d5-7fa45d94fc37
[        ] <- 9b2a5a1b-acc8-45e1-b9d5-7fa45d94fc37
[  +16 ms] Updating files.
[   +4 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 12 Pro Max... (completed in 22ms)
[        ] Synced 0.0MB.
[  +47 ms] Reassembling application
[  +91 ms] Hot reload performed in 197ms.
[        ] Performing hot reload... (completed in 205ms)
[        ] Reloaded 0 libraries in 211ms.
[ +638 ms] Skipping target: gen_localizations
[        ] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Performing hot reload...
[   +8 ms] Scanned through 522 files in 6ms
[        ] Syncing files to device iPhone 12 Pro Max...
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:flutter_downloader_example/main.dart ed6ea4bb-73c1-4c31-8a5d-3469a2110785
[        ] <- ed6ea4bb-73c1-4c31-8a5d-3469a2110785
[   +8 ms] Updating files.
[   +1 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 12 Pro Max... (completed in 10ms)
[        ] Synced 0.0MB.
[  +28 ms] Reassembling application
[  +40 ms] Hot reload performed in 86ms.
[        ] Performing hot reload... (completed in 88ms)
[        ] Reloaded 0 libraries in 92ms.
[+12938 ms] Skipping target: gen_localizations
[   +1 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[        ] Performing hot reload...
[  +22 ms] Scanned through 522 files in 13ms
[        ] Syncing files to device iPhone 12 Pro Max...
[        ] Compiling dart to kernel with 1 updated files
[   +1 ms] <- recompile package:flutter_downloader_example/main.dart 9d160f2d-a4bc-4e2f-b7c7-71ebb6a509b1
[        ] package:flutter_downloader_example/main.dart
[        ] <- 9d160f2d-a4bc-4e2f-b7c7-71ebb6a509b1
[ +154 ms] Updating files.
[   +1 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 12 Pro Max... (completed in 158ms)
[        ] Synced 0.1MB.
[ +124 ms] <- accept
[   +1 ms] reloaded 1 of 757 libraries
[  +37 ms] Reassembling application
[+2006 ms] This is taking a long time; will now check for paused isolates.
[  +31 ms] Found 0 newly paused isolate(s).
[+236501 ms] Ignoring terminal input: "r" because we are busy.
```

**Comment by kuhnroyal** [comment] 2021-06-14 11:47
I migrate an app from Flutter 1.22.6 to 2.0.6 and this problem started right away. I finally managed to trace it to the `FlutterDownloader.initialize()` call and ended up here.
I can confirm this is happening, no matter which device/simulator.
As soon as I comment out `FlutterDownloader.initialize()` it is working again.

**Comment by jonahwilliams** [comment] 2021-06-15 21:25
Can you see where the reassemble is stuck using either dart devtools or the observatory? Frustratingly I have not been able to build that example app locally

**Comment by knaeckeKami** [comment] 2021-06-16 12:01
Yes. It gets stuck on here:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/binding.dart#L456

on the call

```json
{"jsonrpc":"2.0","id":"39","method":"ext.flutter.fastReassemble","params":{"isolateId":"isolates/4482822091642315","className":"MyApp"}}
```
where the isolate with that id is from  `package:flutter_downloader/src/callback_dispatcher.dart$callbackDispatcher-4482822091642315`.

On the hot reload, it also does a `fastReassembleClassName` for the main isolate that results in the call

```json
{"jsonrpc":"2.0","id":"37","method":"ext.flutter.fastReassemble","params":{"isolateId":"isolates/1494484542859819","className":"MyApp"}}
```
but this call finished in <100ms

**Comment by jonahwilliams** [comment] 2021-06-16 17:34
Can you include flutter doctor for that call? You should not be getting any `fastReassemble` calls unless you're on master or channel unknown

**Comment by jonahwilliams** [comment] 2021-06-16 18:01
you could also try https://github.com/flutter/flutter/pull/84363 to see if that resolves the issue

**Comment by knaeckeKami** [comment] 2021-06-16 18:42
Yes, I have been running these tests against the master branch.

```
flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-13.0.pre.509, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.509 at /Users/kami/development/flutter
    • Framework revision 655a836de1 (2 months ago), 2021-04-08 01:22:37 +0200
    • Engine revision 56b1355980
    • Dart version 2.13.0 (build 2.13.0-211.0.dev)
```

I will try against stable and see if there's another issue. I've definitely seen the hangs on stable too, but maybe there's another issue.

**Comment by knaeckeKami** [comment] 2021-06-16 19:39
You are right, I cannot reproduce the hang on hot reload of the flutter_downloader example app on stable.
Also, on #84363  it works fine. Only on master the hot reload of the flutter_downloader example app hangs.

So I guess there is actually another issue. 
I will try to find the source of the hangs on stable in my proprietary app, hopefully I can show a reproducible example this time.

**Comment by jonahwilliams** [comment] 2021-06-16 19:44
No other work is necessary - I'll work on getting #84363 landed.

**Comment by kuhnroyal** [comment] 2021-06-16 20:08
> You are right, I cannot reproduce the hang on hot reload of the flutter_downloader example app on stable.
> Also, on #84363 it works fine. Only on master the hot reload of the flutter_downloader example app hangs.
> 
> So I guess there is actually another issue.
> I will try to find the source of the hangs on stable in my proprietary app, hopefully I can show a reproducible example this time.

That's not correct, I get this problem with the flutter_downloader right away when migrating my app from 1.22.6 to 2.0.6

**Comment by jonahwilliams** [comment] 2021-06-16 20:17
> That's not correct, I get this problem with the flutter_downloader right away when migrating my app from 1.22.6 to 2.0.6

Are you on Stable, or on "Unknown" ?

**Comment by knaeckeKami** [comment] 2021-06-16 20:56
> > You are right, I cannot reproduce the hang on hot reload of the flutter_downloader example app on stable.
> > Also, on #84363 it works fine. Only on master the hot reload of the flutter_downloader example app hangs.
> > So I guess there is actually another issue.
> > I will try to find the source of the hangs on stable in my proprietary app, hopefully I can show a reproducible example this time.
> 
> That's not correct, I get this problem with the flutter_downloader right away when migrating my app from 1.22.6 to 2.0.6

Yes, I also have it on stable on my proprietary app. I am not 100% confident that  #84363 fixes that issue too, I will need to try it out.

It's just that I cannot reproduce the hang in the example app from flutter_downloader on stable. Can you?

**Comment by kuhnroyal** [comment] 2021-06-16 21:08
I'll try that tomorrow.

**Comment by kuhnroyal** [comment] 2021-06-16 21:10
> > That's not correct, I get this problem with the flutter_downloader right away when migrating my app from 1.22.6 to 2.0.6
> 
> Are you on Stable, or on "Unknown" ?

Probably unknown cause of `fvm`.

**Comment by jonahwilliams** [comment] 2021-06-16 21:20
FWIW we're not going to fix problem caused by the "unknown" channel. Please use the actual stable channel

**Comment by knaeckeKami** [comment] 2021-06-16 21:35
I think I now know what's going on here. 

This is an actual bug on the master channel, which should be fixed by #84363.
On stable, this normally does not occur, because the fastReassemble is behind a feature flag that is deactivated by default.
I did not know that there are feature flags depending on the current branch name. https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/features.dart#L367

Users of fvm will be on an "unknown" channel - so they will get all the experiments enabled, even if they are on a stable release like 2.2.2. This should be fixed by fvm.

Now I feel like I wasted your time. You brought up the issue with the "unknown" channel, but I just did not know that not only the commit that you are on matters but also the channel name - so I didn't even consider this.

**Comment by jonahwilliams** [comment] 2021-06-16 21:36
You definitely didn't waste my time, you helped me figure out that #84363 was necessary

**Comment by kuhnroyal** [comment] 2021-06-16 22:32
I see, I wouldn't have guessed that the channel name matters when I can also just checkout a git tag of Flutter and use it.

**Comment by jonahwilliams** [comment] 2021-06-16 22:38
Its not necessary to know that the channel name matters if you use official distributions

**Comment by leoafarias** [comment] 2021-06-17 03:23
@jonahwilliams found a workaround for fvm that follows a similar flow to `downgrade` but for any version. 

However, I believe there might be an issue worth taking a look still. It seems there is a fallback to master if it's any other branch. This means if the channel name matters, any branch of an official channel will default to master correct?

This will impact many workflows outside of fvm, especially flutter community contributors. Wouldn't make sense to raise a `warning` on Flutter doctor or making more obvious in some other way?

Sorry if noise has been added to this issue because of fvm, but I believe there might still be some side effects worth exploring.

**Closed** 2021-06-24 16:36 UTC
Labels: P4, t: hot reload, tool
