### ISSUE TITLE
[flake] [engine] [fuchsia] Fuchsia tests hung at MessageLoop.NonDelayedTasksAreRunInOrder

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#50156] opened 2020-02-05 00:35 UTC
Only seen this once so far: https://chromium-swarm.appspot.com/task?id=4a2b64a03e407a10

/cc @gw280 @iskakaushik @chinmaygarde

**Comment by chinmaygarde** [comment] 2020-02-05 02:20
This can't be happening on ToT because we disabled [these unit-tests](https://github.com/flutter/engine/pull/16340) on Fuchsia. The message loop interop has gremlins that caused us to [revert the migration](https://github.com/flutter/engine/commit/f5de1acf945ff79cb50b02a92dd2c4f47bd973e6) till we [figure out what is happening](https://github.com/flutter/flutter/issues/50032).

**Comment by chinmaygarde** [comment] 2020-02-05 02:22
Confirmed that this [has not been reverted](https://github.com/flutter/engine/blob/e3e6de2aee139f520efd6ba6e4e5aed90bae521c/fml/BUILD.gn#L243). I think we can close this as the flake has been addressed and the investigation is tracked in linked issues already.

**Closed by chinmaygarde** 2020-02-05 02:22 UTC
Labels: a: tests, engine, team: flakes, ○ platform-fuchsia
