### ISSUE TITLE
[webview_flutter] Can not invoke Javascript function on iOS

### ISSUE THREAD

**Issue by TarunRaxa** [flutter/flutter#128489] opened 2023-06-08 07:12 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This package work perfectly fine on android but for ios I am getting crash when I runJavaScript from webview. This happens only on iOS Side. For android I am able to send and receive data between js and flutter. 

I am using latest version of package. 

And the error at ios side is - 
```console
Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1050:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScript (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:385:7)
<asynchronous suspension>
#2      _WebViewExampleState.build.<anonymous closure> (package:my_rich_editor/web_view.dart:252:11)
<asynchronous suspension>
```
### Expected results

Expected result I should runJavaScript from ios side too.

### Actual results

Actually it is not sending data from js to flutter

### Code sample

<details><summary>Code sample</summary>

```dart
WebViewController controller = WebViewController();
controller
    ..setJavaScriptMode(JavaScriptMode.unrestricted)
    ..setBackgroundColor(const Color(0x00000000))
    ..addJavaScriptChannel(
      'GetAppCurrentLanguage',
      onMessageReceived: (JavaScriptMessage message) {
        print('GetAppCurrentLanguage');
        String languageCode = "en";
             },
    )
   ..loadFlutterAsset('assets/demo.html');
```

</details>

    
    

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1050:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScript (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:385:7)
<asynchronous suspension>
#2      _WebViewExampleState.build.<anonymous closure> (package:my_rich_editor/web_view.dart:252:11)
<asynchronous suspension>

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.10.3, on macOS 13.0.1 22A400 darwin-arm64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by huycozy** [comment] 2023-06-08 10:15
Can you please share the complete sample code (a runnable single `main.dart` file) so that we may verify the issue properly?

**Comment by TarunRaxa** [comment] 2023-06-08 10:36
//main.dart file

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const WebViewDemo(),
    );
  }
}

class WebViewDemo extends StatefulWidget {
  const WebViewDemo({super.key});

  @override
  State<WebViewDemo> createState() => _WebViewDemoState();
}

class _WebViewDemoState extends State<WebViewDemo> {
  WebViewController controller = WebViewController();

  @override
  void initState() {
    super.initState();
    // _methodChannel = const MethodChannel('myMethodChannel');

    // late final PlatformWebViewControllerCreationParams params;
    // if (WebViewPlatform.instance is WebKitWebViewPlatform) {
    //   params = WebKitWebViewControllerCreationParams(
    //     allowsInlineMediaPlayback: true,
    //     mediaTypesRequiringUserAction: const <PlaybackMediaTypes>{},
    //   );
    // } else {
    //   params = const PlatformWebViewControllerCreationParams();
    // }
    // _controller = WebViewController.fromPlatformCreationParams(params);

    controller
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..addJavaScriptChannel(
        'Toaster',
        onMessageReceived: (JavaScriptMessage message) {
          print(message.message);
          print('Toaster Flutter Mobile');
        },
      )
      ..setNavigationDelegate(NavigationDelegate(
        onProgress: (int progress) {
          debugPrint('WebView is loading (progress : $progress%)');
        },
        onPageStarted: (String url) {
          debugPrint('Page started loading: $url');
        },
        onPageFinished: (String url) async {
          debugPrint('Page finished loading: $url');
          var result = await controller
              .runJavaScriptReturningResult('yourJavascriptFunction()');
          print('JavaScript function result: $result');
        },
      ))
      ..loadFlutterAsset('assets/dummy.html');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
      ),
      // ignore: unnecessary_null_comparison
      body: WebViewWidget(controller: controller),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
           String sampleData = 'Hello from Flutter!';
           String jsCode = 'testFunction("$sampleData");';
           await controller.runJavaScript(jsCode);
           var result = await controller.runJavaScriptReturningResult('yourJavascriptFunction();');
           print('JavaScript function result: $result');
           controller.runJavaScript('testFunction();');
        },
        child: const Icon(Icons.send),
      ),
    );
  }


}

**Comment by TarunRaxa** [comment] 2023-06-08 10:38
//main.dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const WebViewDemo(),
    );
  }
}

class WebViewDemo extends StatefulWidget {
  const WebViewDemo({super.key});

  @override
  State<WebViewDemo> createState() => _WebViewDemoState();
}

class _WebViewDemoState extends State<WebViewDemo> {
  WebViewController controller = WebViewController();

  @override
  void initState() {
    super.initState();
    controller
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..addJavaScriptChannel(
        'Toaster',
        onMessageReceived: (JavaScriptMessage message) {
          print(message.message);
          print('Toaster Flutter Mobile');
        },
      )
      ..setNavigationDelegate(NavigationDelegate(
        onProgress: (int progress) {
          debugPrint('WebView is loading (progress : $progress%)');
        },
        onPageStarted: (String url) {
          debugPrint('Page started loading: $url');
        },
        onPageFinished: (String url) async {
          debugPrint('Page finished loading: $url');
          var result = await controller
              .runJavaScriptReturningResult('yourJavascriptFunction()');
          print('JavaScript function result: $result');
        },
      ))
      ..loadFlutterAsset('assets/dummy.html');
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
      ),
      // ignore: unnecessary_null_comparison
      body: WebViewWidget(controller: controller),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
           String sampleData = 'Hello from Flutter!';
           String jsCode = 'testFunction("$sampleData");';
           await controller.runJavaScript(jsCode);
           var result = await controller.runJavaScriptReturningResult('yourJavascriptFunction();');
           print('JavaScript function result: $result');
           controller.runJavaScript('testFunction();');
        },
        child: const Icon(Icons.send),
      ),
    );
  }


}

**Comment by TarunRaxa** [comment] 2023-06-08 10:38
Here is my html file code

<!DOCTYPE html>
<html>
<head>
  <title>Flutter to JavaScript Communication</title>
</head>
<body>
  <h1>JavaScript Communication</h1>
  <div id="wrap">
    <div id="editor" contentEditable="true" placeholder="" class="placeholder" style="overflow-y: scroll;">
    </div>
</div>

  <script>
    function yourJavascriptFunction() {
      console.log('JavaScript function called from Flutter');
      alert('This is an alert from JavaScript');
      // Perform any other operations here
      return document.getElementById('editor').innerHTML;
    }
    function testFunction(data) {
                console.log('Received data:', data);
                // Perform any other operations with the received data
    }
    // Receive data from Flutter
    window.addEventListener('message', function(event) {
      var receivedData = event.data;
      // Handle the received data in JavaScript
      console.log(receivedData);
      // Perform any other operations with the received data
    });
  </script>
</body>
</html>

**Comment by TarunRaxa** [comment] 2023-06-08 10:39
Also not able to call js function from flutter side

**Comment by huycozy** [comment] 2023-06-09 04:22
_Note: I merged two of your comments into one and format the sample code_

Thanks for providing sample code. I can see it works on Android but not on iOS. However, there is no crash on iOS, it just doesn't work when communicating with JS. 

I'm checking this on the latest plugin version `webview_flutter_wkwebview: ^3.4.4`. Which version are you working on? Can you please retry on latest version and confirm?

**Comment by TarunRaxa** [comment] 2023-06-09 04:42
I am using latest webview_flutter: ^4.2.2 version

**Comment by TarunRaxa** [comment] 2023-06-09 04:43
Yes it is working fine on android but not on ios side

**Comment by huycozy** [comment] 2023-06-09 05:31
Labeling the issue for further insights.

- Complete sample code: https://github.com/flutter/flutter/issues/128489#issuecomment-1582347219
- Reproducible plugin version: `webview_flutter_wkwebview: ^3.4.4`
- Platforms:
    - Android ✅
    - iOS ❌

✅: No Issue ❌: Issue reproduced 

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (2 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.12.0-2.0.pre.43, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.12.0-2.0.pre.43 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e25eabd263 (81 minutes ago), 2023-06-08 18:57:25 -0700
    • Engine revision a5f7d5d75f
    • Dart version 3.1.0 (build 3.1.0-171.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by cyanglaz** [comment] 2023-06-09 16:32
`Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null)` This error message is not that helpful.
At least we need to better surface the error message on the iOS side of the plugin. For example we should print the details of the NSError object.

**Comment by stuartmorgan** [comment] 2023-06-09 16:41
I'm confused about what the issue is here. The original report says that it throws an exception, the reproduction confirmation says "However, there is no crash on iOS, it just doesn't work when communicating with JS." which contradicts that. I don't see either when running locally; I see it correctly logging an empty return string every time the JS is run.

@huycozy What exactly did you reproduce when you say it "doesn't work"?

@TarunRaxa What are the reproduction steps for getting the platform exception?

**Comment by huycozy** [comment] 2023-06-09 18:17
@stuartmorgan I mean the function implemented in the JS code doesn't work (I should describe it more clearly).

- On Android, JS function is called (an alert dialog is displayed when clicking on FAB)
- On iOS, JS function is not called and there is no crash or specific log from the output console (you're right, it's so confusing if looking back to OP's result. I was thinking he got the same result as mine after retrying this)

| iOS ❌ | Android ✅ |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/c1dd025e-d4e5-4025-8d0e-b6d1e051fc10"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/bcb96ce8-d18a-40c0-b1d0-e86dc9e25743">

**Comment by stuartmorgan** [comment] 2023-06-09 18:47
> * On iOS, JS function is not called

Yes it is, it just doesn't do anything visible:
- It doesn't alert because `alert()` [isn't implemented for iOS](https://github.com/flutter/flutter/issues/30358)
- It doesn't log to the console because console logging doesn't do anything by default in WKWebView
- It returns an empty string because that's what the function is written to do in practice.

None of those are issues with invoking the function.

**Comment by stuartmorgan** [comment] 2023-06-09 18:48
Adjusting labels; without a repro case for the error in the original report we can't investigate this further.

**Comment by TarunRaxa** [comment] 2023-06-10 04:21
Hello, yes same happend at my end. It working fine on android but not on ios. Also is there any more information needed from my side.

**Comment by stuartmorgan** [comment] 2023-06-10 10:54
@TarunRaxa Yes, see my comment just above. We need a complete, reproducible test case for the `PlatformException` you reported. The code above runs without any exceptions in our testing.

**Comment by radoo11** [comment] 2023-06-12 08:58
Exactly the same issue invoking 
`await _controller.runJavaScript(
      'localStorage["access"] = "$token";',
    );`
    
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1050:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:401:28)
<asynchronous suspension>
#2      _WebViewState.initState.<anonymous closure> (package:xxx/features/feed/view/web_view_2.dart:69:26)
<asynchronous suspension>

- Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-x64, locale en-GB)
- webview_flutter: ^4.2.2

**Comment by radoo11** [comment] 2023-06-12 09:00
Exactly the same issue invoking
`await _controller.runJavaScript( 'localStorage["access"] = "$token";', );`

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null)
WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1050:7)
https://github.com/flutter/flutter/pull/1 WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:401:28)
https://github.com/flutter/flutter/pull/2 _WebViewState.initState. (package:xxx/features/feed/view/web_view.dart:69:26)


- Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-x64, locale en-GB)
- webview_flutter: ^4.2.2

**Comment by stuartmorgan** [comment] 2023-06-12 10:36
@radoo11 Per my comment above, we need a complete reproducible test case in order to investigate.

**Comment by radoo11** [comment] 2023-06-12 11:01
I created minimal REPO: https://github.com/radoo11/min_jsweb
with only main.dart with code from https://pub.dev/packages/webview_flutter/example and error below

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null)
WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1050:7)
<asynchronous suspension>
WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:401:28)
<asynchronous suspension>
_TestWebViewState.initState.<anonymous closure> (package:min_jsweb/main.dart:58:28)
<asynchronous suspension>

**Comment by stuartmorgan** [comment] 2023-06-12 13:01
@radoo11 WKWebView returns an error because that JS is invalid; `return` is not valid in a non-function context. The plugin is behaving correctly there.

**Comment by stuartmorgan** [comment] 2023-06-29 18:43
Closing due to lack of response, since without a reproducible test case we cannot investigate further; by far the most likely way to get the original error is a mistake in the JS itself, rather than a plugin bug.

If anyone has a reproducible case with correct JS, please file a new issue with all of the code necessary to reproduce it.

**Closed by stuartmorgan** 2023-06-29 18:43 UTC
Labels: platform-ios, p: webview, package, found in release: 3.10, found in release: 3.12
