### ISSUE TITLE
'flutter doctor' cannot locate the plugins of IntelliJ IDEA

### ISSUE THREAD

**Issue by laolarou726** [flutter/flutter#35440] opened 2019-07-02 02:20 UTC
I'm using the latest version of the Intellij (2019.1.3), and I install the flutter & dart plugin on it. When I using 'flutter doctor', it shows the program cannot found these two plugins. Is this a compatibility problem?

Environment:
OS: MACOS Mojave 10.14.5
Flutter Version: flutter_macos_v1.5.4-hotfix.2-stable
Intellij IDEA: 2019.1.3
Dart plugin: 191.7830
Flutter plugin: 36.2.1

This is the console screenshot:
![image](https://user-images.githubusercontent.com/25716486/60392214-e8530080-9b30-11e9-8508-0730a8598d81.png)

This is the image of the versions of my plugins:
![image](https://user-images.githubusercontent.com/25716486/60392205-a9bd4600-9b30-11e9-9db4-c3160173a2d9.png)

I didn't change the path of the configuration file. Also, I found this folder in this location "path.join(homeDirPath, 'Library', 'Application Support', '$id$major.$minor')":

![image](https://user-images.githubusercontent.com/25716486/60477782-dbf6b100-9cb2-11e9-9fc5-e0c9946cdb36.png)

**Comment by mikhail-tokarev** [comment] 2019-10-01 12:29
hi @laolarou726 ,
is  the issue is still present with the latest version of Flutter and IntelliJ IDEA?
if so please provide the updated output of "flutter doctor -v"

**Comment by iapicca** [comment] 2019-11-08 15:34
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 15:34 UTC
Labels: waiting for customer response
