### ISSUE TITLE
System (Android 7.1.2) / System-UI crash: ListView | NetworkImage

### ISSUE THREAD

**Issue by fablue** [flutter/flutter#10172] opened 2017-05-18 18:40 UTC
# Introduction
As I started developing a Flutter Version of my Project "Lime" (which is a very small social network displaying posts nearby) I noticed, that scrolling down the Feed can result in a whole System crash. This does not happen all the time, but nearly all the time at least the System-UI crashes / has to restart. 

I built a small example app  to demonstrate this behaviour as promised in gitter! 
This was tested with my Nexus 5X running Android 7.1.2. 

The example code contains more information about the issue and will be posted below. 
I think it is some kind of memory leak in my example, the ListView or in NetworkImage. 

Hope this helps :smiley: 

## Steps to Reproduce
Tested on Android 7.1.2 with Nexus 5x

### Source Code (Main.dart)
```dart
import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(new MyApp());
}

/// This example should demonstrate a flutter ListView Issue
/// which leads to a freezing Android-System-UI or complete
/// System crash. This was tested with a Nexus 5X running
/// Android 7.1.2
///
/// This Example App contains a simple ListView which displays
/// Images from a remote server. This Images are fetched and
/// managed by the ExampleList Widget which will load more
/// images if the user scrolls down and calls .setState after
/// a successful request. The request is provided by a Service
/// called Lime and can be replaced by any type of web-service which
/// delivers URL's to images.
///
/// Once the App runs you should be able to reproduce the following behaviour:
///  1) The App is starting
///  2) The App fetches the first set of 50 Image URL's from the Web-Service
///  3) The ListView is running like butter
///
/// Now start scrolling down (and maybe little up again) until you can
/// see the following
/// 1) The App fetches new URLS from the Web-Service and new displays can be displayed.
/// 2) The App's Frame-Rate drops significantly.
/// 3) Other Background-Apps get closed by the System
///    (tested while listening to Spotify which got closed)
///
/// After scrolling further (my nexus takes it to page 6 with 2GB of ram):
/// 1) No more frames are rendered
/// 2) Choreographer will print some messages to the terminal,
/// telling that the Main Thread is working to hard.
/// 3) If Fingertips are enabled in Dev Settings:
///   Touch-Events wont be handled correctly anymore (you can see a whole freezing Android UI)
///
/// If touching the App further:
/// 1) System-UI restarts
/// 2) OR Android Restarts completely
///
///
/// What could be wrong:
/// Based on the symptoms i think there is some kind of memory leak
/// in my Implementation, ListView or NetworkImage
///
/// I could NOT reproduce this issues by:
/// 1) using text-only list-items (maybe not taking enough memory?)
/// 2) Using the same image for every item (smooth like butter)
//
class MyApp extends StatelessWidget {
  @override

  /// Nothing interesting in the MyApp's build method
  /// I am just using the MaterialApp here because
  /// it was suggested by the Template.
  Widget build(BuildContext context) {
    return new MaterialApp(
        title: 'ISSUE EXAMPLE',
        theme: new ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: new ExampleList()
    );
  }
}


/// This is the Widget which controls the ListView
///
/// This widget contains just a simple ListView which uses
/// a ItemBuilder to build NetworkImage items from the URL'S
/// fetched from the Web-Service
///
/// This will fetch new URLS (and so display more images) once
/// the user scrolls down (pagination)
class ExampleList extends StatefulWidget {

  @override
  State<StatefulWidget> createState() {
    return new _ExampleListState();
  }
}

/// Most of the description was added
/// to the ExampleList (Widget).
/// This State is actually doing the work.
class _ExampleListState extends State<ExampleList> {

  /// Just an arbitrary number and irrelevant
  /// for this demo.
  ///
  /// The State starts fetching the next 50 URLS from the
  /// server once only the number of fetchingThreshold Items
  /// are left inside the ListView to display if scrolled down.
  static int fetchingThreshold = 15;

  /// Contains the URLS for the Images to display.
  ///
  /// The exact form of this depends on the Web-Service used.
  /// The only important thing is, that it contains some URLS to images
  /// which can be displayed inside the ListView
  List<Map> items = [];

  /// A http client used to talk with the Web-Service
  final Client client = createHttpClient();

  /// The current running request.
  /// This is null if no request is currently running.
  /// A null-check on this future ensures, that there
  /// is only one request triggered when new URLS should be
  /// requested.
  Future request;

  /// Builds the ListView using buildItem as ItemBuilder
  /// This should be ok, i guess :)
  @override
  Widget build(BuildContext context) {
    return new ListView.builder(
        itemBuilder: buildItem, itemCount: items.length);
  }


  /// This method is called to build a List Item.
  /// I know that the build(BuildContext) method and
  /// methods like this should be side-effect free,
  /// but i could not find another way to do some kind
  /// of pagination (load the more images when scrolled down.
  ///
  /// So one side-effect of this method is, that
  /// it can trigger a HTTP-Request to the Web-Server
  /// which will lead to more Image-Urls fetched.
  Widget buildItem(BuildContext context, int position) {

    /// If request != null then a Request is currently running,
    /// which means that no other request has to be triggered.
    ///
    /// The second condition is, that there are only fetchingThreshold items
    /// left "below" to display.
    if (request == null && (position + fetchingThreshold > items.length)) {
      /// Set the request to indicate, that something is running
      /// and no further request should be triggered
      request = fetchNextItems().then((x) {
        /// Indicate that the operation is finished
        request = null;
      });
    }


    /// This part actually builds the Widget from the item;

    /// The ImageUrl is inside the Map.
    /// As described before: This is absolutely dependend on the
    /// Web-Service used.
    Map item = items[position];

    /// This gets a specific string from the object.
    String url = item["mediaUrl"];

    /// Some objects from the Web-Service do not contain
    /// Images: This is absolutely irrelevant for this demo
    /// but i have to filter them. I will just display an empty
    /// container instead.
    if (url == null) return new Container();

    /// If the item contains an image: Create it
    /// by building the correct URL.
    ///
    /// getMediaUrl(url) is just a Web-Service dependend
    /// helper method which will create a fully working
    /// URL. As mentioned: This would work
    /// with any Image-Url as long as the Images
    /// are not all the same URl

    return
      new SizedBox(height: 300.0,
          child:
          new Image.network(
              Uri.encodeFull(
                  getMediaUrl(url)
              )
          )
      );
  }

  @override
  void initState() {
    super.initState();

    /// Fetch the first 50 items from the Web-Service
    /// and store the Future instance in request to
    /// indicate, that a request is currently running.
    request = fetchNextItems().then((x) {

      /// Indicate that the request finished.
      request = null;
    });
  }


  /// The will fetch the next 50 items
  /// from the Web-Service
  Future fetchNextItems() async {
    int page = (items.length / 50.0).floor();
    print("Fetching page $page");

    /// Fetch 50 items from the Web-Service
    /// The exact form of this is arbitrary and
    /// should work with any Web-Service
    List<Map> fetchedItems = await getFeed(
        client,
        paginationIndex: page
    );

    /// set the State after the Items are fetched
    this.setState(() {

      /// Add the new items to the list
      items.addAll(fetchedItems);
    });
  }


}


/// Just an arbitrary api call.
/// I am using one of my own services
/// to demonstrate this.
///
/// The token will be active
/// until the issue is closed
Future <List<Map<String, dynamic>>> getFeed(Client client,
    {
      int paginationIndex: 0,
      int paginationSize: 50,

    }) async {
  String server = "https://lime.fablue.org";
  double latitude = 50.0;
  double longitude = 12.0;
  double distance = 9.0;
  String url = "$server/message?latitude=$latitude"
      "&longitude=$longitude&distance=$distance"
      "&pagination_index=$paginationIndex"
      "&pagination_size=$paginationSize";

  url = Uri.encodeFull(url);
  print("Requesting more items:\n$url");
  Response response = await client.get(url,
      headers: {
        "token": "fluttertesttoken"
      }
  );

  print("API HTTP STATUS CODE (SHOUD BE 200): ${response.statusCode}");


  List<Map<String, dynamic>> objects = JSON.decode(response.body);
  return objects.reversed.toList();
}

/// Irrelevant for this issue.
/// Just the way the server wants image requests
String getMediaUrl(String url) {
  return Uri.encodeFull("https://lime.fablue.org/media/$url");
}



```

### IntelliJ project

[flutter_listview.zip](https://github.com/flutter/flutter/files/1011938/flutter_listview.zip)

### Last logs before the App crashed
```
I/flutter ( 9694): API HTTP STATUS CODE (SHOUD BE 200): 200
I/flutter ( 9694): Fetching page 6
I/flutter ( 9694): Requesting more items:
I/flutter ( 9694): https://lime.fablue.org/message?latitude=50.0&longitude=12.0&distance=9.0&pagination_index=6&pagination_size=50
I/flutter ( 9694): API HTTP STATUS CODE (SHOUD BE 200): 200
I/Choreographer( 9694): Skipped 3067 frames!  The application may be doing too much work on its main thread.
Lost connection to 
```

### Flutter analyze
```
Analyzing /home/sellmair/dev/flutter-listview/flutter_listview...
No issues found!
Ran in 29.3s
```

## Flutter Doctor
```
[✓] Flutter (on Linux, channel master)
    • Flutter at /opt/flutter
    • Framework revision bac2f0d01f (vor 79 Minuten), 2017-05-18 10:08:11 -0700
    • Engine revision 82815836eb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/sellmair/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] WebStorm (version 2017.1)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424.20
    • Flutter plugin version 13.1

[✓] Connected devices
    • Nexus 5X • 0214bed43bac24d0 • android-arm • Android 7.1.2 (API 25)
```

**Comment by eseidelGoogle** [comment] 2017-05-18 20:20
Is this an OOM?  FYI @Hixie @jason-simmons @a-siva

**Comment by rmacnak-google** [comment] 2017-05-18 21:14
The code above works fine for me on Nexus 4 / Android 5.1.1.

**Comment by fablue** [comment] 2017-05-18 21:16
Have you noticed any frame rate drop after loading a few pages of images?

**Comment by fablue** [comment] 2017-05-22 15:41
I made a video demonstrating of this issues and how long it takes to freeze the UI (about 2 minutes of scrolling) 
[https://youtu.be/9yXL6ljYSd8?t=1m41s](https://youtu.be/9yXL6ljYSd8?t=1m40s)

Please make sure to scroll "long enough" to reproduce  :smiley:

**Comment by bduyng** [comment] 2017-05-23 07:12
I hope we can have a feed demo like Instagram and if that works well with 60fps with 100 posts Flutter will be truly awesome!!!

**Comment by fablue** [comment] 2017-05-23 07:31
Here you go:
https://youtu.be/yAUOuh9Mgus

Built with flutter in one day of work including reading all the stuff at flutter.io

**Comment by bduyng** [comment] 2017-05-23 07:35
wow so impressed! Is the performance same on iOS? and the issue is fixed?

**Comment by fablue** [comment] 2017-05-23 07:44
Thank you very much :relaxed: 
I did not have the chance to try it on iOS yet (since I am not owning an Apple Computer). 
The issue is still open but I think starting Flutter development right now is worth it. 
For me its maybe  3-5x more time efficient than building a native Android App. Its just great! :smiley:

**Comment by bduyng** [comment] 2017-05-23 07:47
@fablue. You are welcome! Because of your video, I am playing it with Flutter right now haha. I saw you have a repo for Lime. Can't wait if you planned to open source the app.

**Comment by sethladd** [comment] 2017-05-23 15:34
@fablue thank you for sharing the video! Very cool. Would you be up for writing a blog post about how you built it?

**Comment by fablue** [comment] 2017-05-23 15:45
@sethladd Yeah of course! Can you provide more information about the post? 
How long should it be?
Where to publish? 

Thanks :relaxed:

**Comment by sethladd** [comment] 2017-05-23 17:46
> How long should it be?

No particular opinion, but only "as long as it needs to be: :)

You probably don't have to include content about installing Flutter, but instead focus on how you build this demo. What's unique about Flutter? How and why did it help you build this? What would another developer find interesting?

For a title, something like "I build an instagram feed clone in XX LOC for iOS and Android, here's what I learned" should work well :)

> How long should it be?

We find that Medium is a good place to publish articles.

Thank you!

**Comment by jason-simmons** [comment] 2017-05-24 17:47
Was able to reproduce this as an OOM on a Nexus 4.  Graphics memory consumption increases as you scroll, eventually resulting in this:

05-24 10:42:56.800 17167 17190 D skia    : sk_out_of_memory (asked for 4478976 bytes)
05-24 10:42:56.800 17167 17190 D skia    : ../../third_party/skia/src/ports/SkMemory_malloc.cpp:18: fatal error: "assert((SkDebugf("sk_out_of_memory (asked for " "%zu" " bytes)""\n", size), false))"

**Comment by fablue** [comment] 2017-05-24 17:54
@sethladd Working on it, but I cannot say for sure how long it will take  :persevere: 
I am just writing it as markdown inside a GitHub repository  :smirk: 

@jason-simmons Tell me if I can help in any way! :+1:

**Comment by sethladd** [comment] 2017-05-24 18:07
> I am just writing it as markdown inside a GitHub repository

Sounds great! Thanks again :)

**Comment by fablue** [comment] 2017-05-24 20:48
https://github.com/fablue/building-a-social-network-with-flutter
Fist chapter is written! Work in progress  :smile: 
Don't judge me too hard for the language! Since I am no native speaker I will make it better once the content is written! 

Feedback welcome :relaxed:

**Comment by sethladd** [comment] 2017-05-24 21:18
Nice! We'll continue the conversation over in your Github. Thank you :)

**Comment by turnidge** [comment] 2017-09-26 18:06
(I'm studying how flutter users diagnose and fix memory problems, so I'm following this bug - @turnidge)

**Comment by zoechi** [comment] 2018-12-18 14:21
Is this issue still relevant?

**Comment by zoechi** [comment] 2019-01-14 08:58
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-14 08:58 UTC
Labels: engine, severe: crash, waiting for customer response, ▣ platform-android
