### ISSUE TITLE
[video_player] green pixels and not full screen

### ISSUE THREAD

**Issue by diyargulli** [flutter/flutter#83599] opened 2021-05-29 12:57 UTC
i recently received a report from my users that video player has green pixels  also not full screen on some android boxes and android TVs

**Comment by davidgaspardev** [comment] 2021-05-30 21:56
Can you share more information about the problem ? ... screenshot and logs

**Comment by diyargulli** [comment] 2021-05-30 22:02
> Can you share more information about the problem ? ... screenshot and logs
See the bottom gree line 👇
![Screenshot_20210517-170214](https://user-images.githubusercontent.com/68226757/120121355-a531ba00-c1ab-11eb-8eae-be5f9a684599.jpg)

and see same video without green pixels app made with android studio (exoPlayer) 👇
![Screenshot_20210517-170226_INTV+](https://user-images.githubusercontent.com/68226757/120121381-ce524a80-c1ab-11eb-8927-2114ced99d6a.jpg)

**Comment by davidgaspardev** [comment] 2021-05-31 02:11
Is your background color green ? 

I think it's the style issue of the containers around the video widget, some widgets have standard dimensions for margin or padding.

Use [DevTools](https://flutter.dev/docs/development/tools/devtools/inspector) to see which widget that green line belongs to.

**Comment by diyargulli** [comment] 2021-05-31 08:35
> Is your background color green ?
> 
> I think it's the style issue of the containers around the video widget, some widgets have standard dimensions for margin or padding.
> 
> Use [DevTools](https://flutter.dev/docs/development/tools/devtools/inspector) to see which widget that green line belongs to.

No i didn't used green color i have multiple app with this problem it is VideoPlayer widget on some devices it show big part of screen as green color and video smaller than real size all other pixels are green, note: some videos doesn't have this problem i can give you a video link to test

**Comment by diyargulli** [comment] 2021-05-31 08:44
Please use this to test if problem not exists please test on other devices too
https://ikomg2.mmdlive.lldns.net/ikomg2/107b7df8f5444d778f349100739a09cd/manifest.m3u8

**Comment by TahaTesser** [comment] 2021-05-31 12:39
Hi @davidgaspardev 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/55090
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-31 12:39 UTC
Labels: in triage
