### ISSUE TITLE
Bug in DateTime

### ISSUE THREAD

**Issue by Poupygeek** [flutter/flutter#125699] opened 2023-04-28 18:00 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

See the example

### Expected results

the result of DateTime difference is false in summer period

### Actual results

difference of one day in summer period (27/3 ->29/10

### Code sample

example code: 
int DD = 0;
    int MM = 1;
    for (int i = 1; i < 366; i++) {
      DD++;
      if ((DD > 31 &&
          (MM == 1 || MM == 3 || MM == 5 || MM == 7 || MM == 8 || MM == 10))
          || (DD > 28 && MM == 2)
          ||
          (DD > 30 && (MM == 4 || MM == 6 || MM == 9 || MM == 11))) {
        MM++;
        DD = 1;
      }
      DateTime date = DateTime(2023, MM, DD);
      int doy = date.difference(new DateTime(2022, 12, 31, 0, 0)).inDays;
      if (doy != i) {
        Routines.debug("-------------------------------- $doy $i $DD/$MM/2023");
      }
    }

Result:
I/flutter ( 8366): -------------------------------- 85 86 27/3/2023
I/flutter ( 8366): -------------------------------- 86 87 28/3/2023
I/flutter ( 8366): -------------------------------- 87 88 29/3/2023
I/flutter ( 8366): -------------------------------- 88 89 30/3/2023
I/flutter ( 8366): -------------------------------- 89 90 31/3/2023
I/flutter ( 8366): -------------------------------- 90 91 1/4/2023
I/flutter ( 8366): -------------------------------- 91 92 2/4/2023
I/flutter ( 8366): -------------------------------- 92 93 3/4/2023
I/flutter ( 8366): -------------------------------- 93 94 4/4/2023
I/flutter ( 8366): -------------------------------- 94 95 5/4/2023
I/flutter ( 8366): -------------------------------- 95 96 6/4/2023
I/flutter ( 8366): -------------------------------- 96 97 7/4/2023
I/flutter ( 8366): -------------------------------- 97 98 8/4/2023
I/flutter ( 8366): -------------------------------- 98 99 9/4/2023
I/flutter ( 8366): -------------------------------- 99 100 10/4/2023
I/flutter ( 8366): -------------------------------- 100 101 11/4/2023
I/flutter ( 8366): -------------------------------- 101 102 12/4/2023
I/flutter ( 8366): -------------------------------- 102 103 13/4/2023
I/flutter ( 8366): -------------------------------- 103 104 14/4/2023
I/flutter ( 8366): -------------------------------- 104 105 15/4/2023
I/flutter ( 8366): -------------------------------- 105 106 16/4/2023
I/flutter ( 8366): -------------------------------- 106 107 17/4/2023
I/flutter ( 8366): -------------------------------- 107 108 18/4/2023
I/flutter ( 8366): -------------------------------- 108 109 19/4/2023
I/flutter ( 8366): -------------------------------- 109 110 20/4/2023
I/flutter ( 8366): -------------------------------- 110 111 21/4/2023
I/flutter ( 8366): -------------------------------- 111 112 22/4/2023
I/flutter ( 8366): -------------------------------- 112 113 23/4/2023
I/flutter ( 8366): -------------------------------- 113 114 24/4/2023
I/flutter ( 8366): -------------------------------- 114 115 25/4/2023
I/flutter ( 8366): -------------------------------- 115 116 26/4/2023
I/flutter ( 8366): -------------------------------- 116 117 27/4/2023
I/flutter ( 8366): -------------------------------- 117 118 28/4/2023
I/flutter ( 8366): -------------------------------- 118 119 29/4/2023
I/flutter ( 8366): -------------------------------- 119 120 30/4/2023
I/flutter ( 8366): -------------------------------- 120 121 1/5/2023
I/flutter ( 8366): -------------------------------- 121 122 2/5/2023
I/flutter ( 8366): -------------------------------- 122 123 3/5/2023
I/flutter ( 8366): -------------------------------- 123 124 4/5/2023
I/flutter ( 8366): -------------------------------- 124 125 5/5/2023
I/flutter ( 8366): -------------------------------- 125 126 6/5/2023
I/flutter ( 8366): -------------------------------- 126 127 7/5/2023
I/flutter ( 8366): -------------------------------- 127 128 8/5/2023
I/flutter ( 8366): -------------------------------- 128 129 9/5/2023
I/flutter ( 8366): -------------------------------- 129 130 10/5/2023
I/flutter ( 8366): -------------------------------- 130 131 11/5/2023
I/flutter ( 8366): -------------------------------- 131 132 12/5/2023
I/flutter ( 8366): -------------------------------- 132 133 13/5/2023
I/flutter ( 8366): -------------------------------- 133 134 14/5/2023
I/flutter ( 8366): -------------------------------- 134 135 15/5/2023
I/flutter ( 8366): -------------------------------- 135 136 16/5/2023
I/flutter ( 8366): -------------------------------- 136 137 17/5/2023
I/flutter ( 8366): -------------------------------- 137 138 18/5/2023
I/flutter ( 8366): -------------------------------- 138 139 19/5/2023
I/flutter ( 8366): -------------------------------- 139 140 20/5/2023
I/flutter ( 8366): -------------------------------- 140 141 21/5/2023
I/flutter ( 8366): -------------------------------- 141 142 22/5/2023
I/flutter ( 8366): -------------------------------- 142 143 23/5/2023
I/flutter ( 8366): -------------------------------- 143 144 24/5/2023
I/flutter ( 8366): -------------------------------- 144 145 25/5/2023
I/flutter ( 8366): -------------------------------- 145 146 26/5/2023
I/flutter ( 8366): -------------------------------- 146 147 27/5/2023
I/flutter ( 8366): -------------------------------- 147 148 28/5/2023
I/flutter ( 8366): -------------------------------- 148 149 29/5/2023
I/flutter ( 8366): -------------------------------- 149 150 30/5/2023
I/flutter ( 8366): -------------------------------- 150 151 31/5/2023
I/flutter ( 8366): -------------------------------- 151 152 1/6/2023
I/flutter ( 8366): -------------------------------- 152 153 2/6/2023
I/flutter ( 8366): -------------------------------- 153 154 3/6/2023
I/flutter ( 8366): -------------------------------- 154 155 4/6/2023
I/flutter ( 8366): -------------------------------- 155 156 5/6/2023
I/flutter ( 8366): -------------------------------- 156 157 6/6/2023
I/flutter ( 8366): -------------------------------- 157 158 7/6/2023
I/flutter ( 8366): -------------------------------- 158 159 8/6/2023
I/flutter ( 8366): -------------------------------- 159 160 9/6/2023
I/flutter ( 8366): -------------------------------- 160 161 10/6/2023
I/flutter ( 8366): -------------------------------- 161 162 11/6/2023
I/flutter ( 8366): -------------------------------- 162 163 12/6/2023
I/flutter ( 8366): -------------------------------- 163 164 13/6/2023
I/flutter ( 8366): -------------------------------- 164 165 14/6/2023
I/flutter ( 8366): -------------------------------- 165 166 15/6/2023
I/flutter ( 8366): -------------------------------- 166 167 16/6/2023
I/flutter ( 8366): -------------------------------- 167 168 17/6/2023
I/flutter ( 8366): -------------------------------- 168 169 18/6/2023
I/flutter ( 8366): -------------------------------- 169 170 19/6/2023
I/flutter ( 8366): -------------------------------- 170 171 20/6/2023
I/flutter ( 8366): -------------------------------- 171 172 21/6/2023
I/flutter ( 8366): -------------------------------- 172 173 22/6/2023
I/flutter ( 8366): -------------------------------- 173 174 23/6/2023
I/flutter ( 8366): -------------------------------- 174 175 24/6/2023
I/flutter ( 8366): -------------------------------- 175 176 25/6/2023
I/flutter ( 8366): -------------------------------- 176 177 26/6/2023
I/flutter ( 8366): -------------------------------- 177 178 27/6/2023
I/flutter ( 8366): -------------------------------- 178 179 28/6/2023
I/flutter ( 8366): -------------------------------- 179 180 29/6/2023
I/flutter ( 8366): -------------------------------- 180 181 30/6/2023
I/flutter ( 8366): -------------------------------- 181 182 1/7/2023
I/flutter ( 8366): -------------------------------- 182 183 2/7/2023
I/flutter ( 8366): -------------------------------- 183 184 3/7/2023
I/flutter ( 8366): -------------------------------- 184 185 4/7/2023
I/flutter ( 8366): -------------------------------- 185 186 5/7/2023
I/flutter ( 8366): -------------------------------- 186 187 6/7/2023
I/flutter ( 8366): -------------------------------- 187 188 7/7/2023
I/flutter ( 8366): -------------------------------- 188 189 8/7/2023
I/flutter ( 8366): -------------------------------- 189 190 9/7/2023
I/flutter ( 8366): -------------------------------- 190 191 10/7/2023
I/flutter ( 8366): -------------------------------- 191 192 11/7/2023
I/flutter ( 8366): -------------------------------- 192 193 12/7/2023
I/flutter ( 8366): -------------------------------- 193 194 13/7/2023
I/flutter ( 8366): -------------------------------- 194 195 14/7/2023
I/flutter ( 8366): -------------------------------- 195 196 15/7/2023
I/flutter ( 8366): -------------------------------- 196 197 16/7/2023
I/flutter ( 8366): -------------------------------- 197 198 17/7/2023
I/flutter ( 8366): -------------------------------- 198 199 18/7/2023
I/flutter ( 8366): -------------------------------- 199 200 19/7/2023
I/flutter ( 8366): -------------------------------- 200 201 20/7/2023
I/flutter ( 8366): -------------------------------- 201 202 21/7/2023
I/flutter ( 8366): -------------------------------- 202 203 22/7/2023
I/flutter ( 8366): -------------------------------- 203 204 23/7/2023
I/flutter ( 8366): -------------------------------- 204 205 24/7/2023
I/flutter ( 8366): -------------------------------- 205 206 25/7/2023
I/flutter ( 8366): -------------------------------- 206 207 26/7/2023
I/flutter ( 8366): -------------------------------- 207 208 27/7/2023
I/flutter ( 8366): -------------------------------- 208 209 28/7/2023
I/flutter ( 8366): -------------------------------- 209 210 29/7/2023
I/flutter ( 8366): -------------------------------- 210 211 30/7/2023
I/flutter ( 8366): -------------------------------- 211 212 31/7/2023
I/flutter ( 8366): -------------------------------- 212 213 1/8/2023
I/flutter ( 8366): -------------------------------- 213 214 2/8/2023
I/flutter ( 8366): -------------------------------- 214 215 3/8/2023
I/flutter ( 8366): -------------------------------- 215 216 4/8/2023
I/flutter ( 8366): -------------------------------- 216 217 5/8/2023
I/flutter ( 8366): -------------------------------- 217 218 6/8/2023
I/flutter ( 8366): -------------------------------- 218 219 7/8/2023
I/flutter ( 8366): -------------------------------- 219 220 8/8/2023
I/flutter ( 8366): -------------------------------- 220 221 9/8/2023
I/flutter ( 8366): -------------------------------- 221 222 10/8/2023
I/flutter ( 8366): -------------------------------- 222 223 11/8/2023
I/flutter ( 8366): -------------------------------- 223 224 12/8/2023
I/flutter ( 8366): -------------------------------- 224 225 13/8/2023
I/flutter ( 8366): -------------------------------- 225 226 14/8/2023
I/flutter ( 8366): -------------------------------- 226 227 15/8/2023
I/flutter ( 8366): -------------------------------- 227 228 16/8/2023
I/flutter ( 8366): -------------------------------- 228 229 17/8/2023
I/flutter ( 8366): -------------------------------- 229 230 18/8/2023
I/flutter ( 8366): -------------------------------- 230 231 19/8/2023
I/flutter ( 8366): -------------------------------- 231 232 20/8/2023
I/flutter ( 8366): -------------------------------- 232 233 21/8/2023
I/flutter ( 8366): -------------------------------- 233 234 22/8/2023
I/flutter ( 8366): -------------------------------- 234 235 23/8/2023
I/flutter ( 8366): -------------------------------- 235 236 24/8/2023
I/flutter ( 8366): -------------------------------- 236 237 25/8/2023
I/flutter ( 8366): -------------------------------- 237 238 26/8/2023
I/flutter ( 8366): -------------------------------- 238 239 27/8/2023
I/flutter ( 8366): -------------------------------- 239 240 28/8/2023
I/flutter ( 8366): -------------------------------- 240 241 29/8/2023
I/flutter ( 8366): -------------------------------- 241 242 30/8/2023
I/flutter ( 8366): -------------------------------- 242 243 31/8/2023
I/flutter ( 8366): -------------------------------- 243 244 1/9/2023
I/flutter ( 8366): -------------------------------- 244 245 2/9/2023
I/flutter ( 8366): -------------------------------- 245 246 3/9/2023
I/flutter ( 8366): -------------------------------- 246 247 4/9/2023
I/flutter ( 8366): -------------------------------- 247 248 5/9/2023
I/flutter ( 8366): -------------------------------- 248 249 6/9/2023
I/flutter ( 8366): -------------------------------- 249 250 7/9/2023
I/flutter ( 8366): -------------------------------- 250 251 8/9/2023
I/flutter ( 8366): -------------------------------- 251 252 9/9/2023
I/flutter ( 8366): -------------------------------- 252 253 10/9/2023
I/flutter ( 8366): -------------------------------- 253 254 11/9/2023
I/flutter ( 8366): -------------------------------- 254 255 12/9/2023
I/flutter ( 8366): -------------------------------- 255 256 13/9/2023
I/flutter ( 8366): -------------------------------- 256 257 14/9/2023
I/flutter ( 8366): -------------------------------- 257 258 15/9/2023
I/flutter ( 8366): -------------------------------- 258 259 16/9/2023
I/flutter ( 8366): -------------------------------- 259 260 17/9/2023
I/flutter ( 8366): -------------------------------- 260 261 18/9/2023
I/flutter ( 8366): -------------------------------- 261 262 19/9/2023
I/flutter ( 8366): -------------------------------- 262 263 20/9/2023
I/flutter ( 8366): -------------------------------- 263 264 21/9/2023
I/flutter ( 8366): -------------------------------- 264 265 22/9/2023
I/flutter ( 8366): -------------------------------- 265 266 23/9/2023
I/flutter ( 8366): -------------------------------- 266 267 24/9/2023
I/flutter ( 8366): -------------------------------- 267 268 25/9/2023
I/flutter ( 8366): -------------------------------- 268 269 26/9/2023
I/flutter ( 8366): -------------------------------- 269 270 27/9/2023
I/flutter ( 8366): -------------------------------- 270 271 28/9/2023
I/flutter ( 8366): -------------------------------- 271 272 29/9/2023
I/flutter ( 8366): -------------------------------- 272 273 30/9/2023
I/flutter ( 8366): -------------------------------- 273 274 1/10/2023
I/flutter ( 8366): -------------------------------- 274 275 2/10/2023
I/flutter ( 8366): -------------------------------- 275 276 3/10/2023
I/flutter ( 8366): -------------------------------- 276 277 4/10/2023
I/flutter ( 8366): -------------------------------- 277 278 5/10/2023
I/flutter ( 8366): -------------------------------- 278 279 6/10/2023
I/flutter ( 8366): -------------------------------- 279 280 7/10/2023
I/flutter ( 8366): -------------------------------- 280 281 8/10/2023
I/flutter ( 8366): -------------------------------- 281 282 9/10/2023
I/flutter ( 8366): -------------------------------- 282 283 10/10/2023
I/flutter ( 8366): -------------------------------- 283 284 11/10/2023
I/flutter ( 8366): -------------------------------- 284 285 12/10/2023
I/flutter ( 8366): -------------------------------- 285 286 13/10/2023
I/flutter ( 8366): -------------------------------- 286 287 14/10/2023
I/flutter ( 8366): -------------------------------- 287 288 15/10/2023
I/flutter ( 8366): -------------------------------- 288 289 16/10/2023
I/flutter ( 8366): -------------------------------- 289 290 17/10/2023
I/flutter ( 8366): -------------------------------- 290 291 18/10/2023
I/flutter ( 8366): -------------------------------- 291 292 19/10/2023
I/flutter ( 8366): -------------------------------- 292 293 20/10/2023
I/flutter ( 8366): -------------------------------- 293 294 21/10/2023
I/flutter ( 8366): -------------------------------- 294 295 22/10/2023
I/flutter ( 8366): -------------------------------- 295 296 23/10/2023
I/flutter ( 8366): -------------------------------- 296 297 24/10/2023
I/flutter ( 8366): -------------------------------- 297 298 25/10/2023
I/flutter ( 8366): -------------------------------- 298 299 26/10/2023
I/flutter ( 8366): -------------------------------- 299 300 27/10/2023
I/flutter ( 8366): -------------------------------- 300 301 28/10/2023
I/flutter ( 8366): -------------------------------- 301 302 29/10/2023

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.10.0-1.4.pre, on Ubuntu 23.04 6.2.0-20-generic, locale fr_FR.UTF-8)
    • Flutter version 3.10.0-1.4.pre on channel beta at /home/cg/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14a4eac61 (il y a 3 jours), 2023-04-26 12:54:31 +0700
    • Engine revision f7ac42e8a2
    • Dart version 3.0.0 (build 3.0.0-417.3.beta)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/cg/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/cg/programmes/ProgTelecharges/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/cg/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/cg/programmes/ProgTelecharges/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.3)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 23.04 6.2.0-20-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 112.0.5615.165

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by tomg2012** [comment] 2023-04-28 19:43
Hi, I was able to reproduce this issue with the following code and found it to be linked to Daylight Savings adjustments:
```
    DateTime startDate = DateTime(2022, 12, 31,0);
    int diff_1 = DateTime(2023, 3, 12, 0).difference(startDate).inDays;
    int diff_2 = DateTime(2023, 3, 13, 0).difference(startDate).inDays;

    int dst_diff_1 = DateTime(2023, 3, 12, 3).difference(startDate).inDays;
    int dst_diff_2 = DateTime(2023, 3, 13, 3).difference(startDate).inDays;

    print("If the hour is 0: $diff_1  :  $diff_2");
    print("if the hour is 3: $dst_diff_1  :  $dst_diff_2");

console:
If the hour is 0 : 71  :  71
if the hour is 3 : 71  :  72
```
The difference is that March 12 is when we lose an hour, making the difference between March 12 and March 13 less than 24 hours.  The time is then regained when we "fall back".

I'm not sure if it's a "bug" per-se as technically there's less than 24 hours difference between March 12 and 13, but _is_ an annoyance for anyone working with dates and times in their code. Fortunately there's a workaround involving converting to UTC before calculating time difference.

```
    DateTime startDate = DateTime.utc(2022, 12, 31,0);
    int diff_1 = DateTime.utc(2023, 3, 12, 0).difference(startDate).inDays;
    int diff_2 = DateTime.utc(2023, 3, 13, 0).difference(startDate).inDays;

console:
If the hour is 0: 71  :  72
if the hour is 3: 71  :  72
```

If it turns out to be a bug, it's probably a Dart language issue, but I'll let everyone else weigh-in. I hope this helps!

**Comment by stuartmorgan** [comment] 2023-04-28 20:36
This is documented behavior:

> The difference between two dates in different time zones is just the number of nanoseconds between the two points in time. It doesn't take calendar days into account. That means that the difference between two midnights in local time may be less than 24 hours times the number of days between them

Computing a `Duration` and then calling `inDays` on it (which [just divides by the time in a normal day](https://api.dart.dev/stable/2.19.6/dart-core/Duration/inDays.html)) will not give you calendar days, because `Duration` has no concept of calendars.

Closing as this is not a bug (and, as noted in the comment above, because if it were it would need to be filed against Dart, not Flutter).

**Closed by stuartmorgan** 2023-04-28 20:36 UTC
