### ISSUE TITLE
When pre-input Chinese, click the overlay above the content area to crash

### ISSUE THREAD

**Issue by Winstonokk** [flutter/flutter#153835] opened 2024-08-21 10:43 UTC
### Steps to reproduce

1、Pre-enter Chinese in the content area, do not confirm
2、Click the content area button to trigger the pop-up box
3、Click one of the controls on the pop-up box to refresh the UI

### Expected results

normal

### Actual results

```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(0x1c15d4cb4 0x1ba6f43d0 0x1c16e3bbc 0x10607a754 0x1c4002d34 0x1c36ef6b8 0x1c36eec4c 0x1c36ecb8c 0x1c3ff8f98 0x1c372e520 0x1c3732d94 0x1c3732054 0x1c3730340 0x1c3779018 0x1c3a7e5fc 0x1c169e128 0x1c16aa7b4 0x1c162f5e8 0x1c16450d4 0x1c164a3ec 0x1fc1df35c 0x1c39d76e8 0x1c39d734c 0x1029bc110 0x1e0b12dec)
libc++abi: terminating due to uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001ffc0f558 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1ffc0f558 <+8>:  b.lo   0x1ffc0f578               ; <+40>
    0x1ffc0f55c <+12>: pacibsp
    0x1ffc0f560 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1ffc0f564 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.

Exited.
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(0x1c15d4cb4 0x1ba6f43d0 0x1c16e3bbc 0x10607a754 0x1c4002d34 0x1c36ef6b8 0x1c36eec4c 0x1c36ecb8c 0x1c3ff8f98 0x1c372e520 0x1c3732d94 0x1c3732054 0x1c3730340 0x1c3779018 0x1c3a7e5fc 0x1c169e128 0x1c16aa7b4 0x1c162f5e8 0x1c16450d4 0x1c164a3ec 0x1fc1df35c 0x1c39d76e8 0x1c39d734c 0x1029bc110 0x1e0b12dec)
libc++abi: terminating due to uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001ffc0f558 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1ffc0f558 <+8>:  b.lo   0x1ffc0f578               ; <+40>
    0x1ffc0f55c <+12>: pacibsp
    0x1ffc0f560 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1ffc0f564 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.

Exited.
```

### Flutter Doctor output

![image](https://github.com/user-attachments/assets/56bc5a56-8fd6-4924-8dcf-d2b524ec7e3e)

**Comment by danagbemava-nc** [comment] 2024-08-21 13:14
Hi @Winstonokk, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.24.0 at the time of writing) to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v` along with a complete minimal reproducible code sample so that we can properly investigate this issue. 

Thank you

**Comment by Winstonokk** [comment] 2024-08-23 09:54
29/5000
I still had this problem when I upgraded to the latest version, using a third-party library called quill(https://github.com/singerdmx/flutter-quill),I have raised the issue with them, but there is no reply. quill's editor uses the RichText control to dynamically update text. When the text is pre-entered text, clicking on the blank space behind it will crash. Can you guys help parse this crash log? thanks very much.

Below is a screenshot of quill's code and crash video

![image](https://github.com/user-attachments/assets/671336ef-52ff-4740-8ed4-b8a6a3b46279)

https://github.com/user-attachments/assets/23d58f9e-d7c0-4a77-883e-9f00aeb40769

**Comment by danagbemava-nc** [comment] 2024-08-26 07:13
The actual reason for the crash is found in the first line `'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'`.  You might be able to get more information about the crash from going to `Settings > Privacy And Security > Analytics & Improvements > Analytics Data` and finding an entry to corresponds to the app and the time the crash happened. If this happened in debugging mode, you can view the call stack in Xcode. 

Unfortunately, a RichTextEditor is a complex application and considering this crash happens with a third-party package, your only option might be to switch to a new one or wait for the maintainers of the one you're using to respond. Given that this is caused by a third-party package, I'll be closing this issue. 

Thank you

**Closed by danagbemava-nc** 2024-08-26 07:13 UTC
Labels: in triage
