### ISSUE TITLE
TextField, when center aligned, shows caret in the middle when pasting text

### ISSUE THREAD

**Issue by pablote** [flutter/flutter#22496] opened 2018-09-30 19:05 UTC
## Steps to Reproduce

I have a TextField like this:

```dart
child: TextField(
        onChanged: handleInputChange,
        enabled: !disabled,
        textAlign: TextAlign.center,
        style: TextStyle(color: Colors.black, fontSize: 16.0),
        obscureText: obscureText,
        decoration: new InputDecoration(
          contentPadding: const EdgeInsets.all(7.0),
          hintText: hintText,
          border: new OutlineInputBorder(
              borderRadius: new BorderRadius.all(const Radius.circular(5.0))
          )
        ),
      )
```

As I type, the caret is correctly shown at the end, but if I paste text from my keyboard, like my email which it remembers, the caret is shown in the middle in a weird position, not really in between characters. BTW, this does not happen when left aligned, in which case the caret is correctly advanced to the end.

<img width="562" alt="caret_middle" src="https://user-images.githubusercontent.com/2463995/46261463-5f883500-c4ca-11e8-95a2-192a4d4a5a13.png">

## Logs

N/A

## Flutter doctor

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.8.2 at /Users/pablo/Documents/work/projects/forks/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/pablo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/pablo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

**Comment by JediBurrell** [comment] 2018-11-11 11:11
This also happens when writing text if there's a space at the end.

**Comment by yohom** [comment] 2018-11-16 09:37
I made a workaround to fix this problem, you can try it. @JediBurrell 
```dart
_controller.addListener(() {
  if (_controller.text.length != _controller.text.trim().length) {
    _controller.text = _controller.text.trim();
  }
  _controller.selection =
    TextSelection.collapsed(offset: _controller.text.length);
});
```

**Comment by pablote** [comment] 2018-11-16 12:32
This seems fixed for me starting with `v0.10.2`, can you guys verify it got fixed from 0.9.x to 0.10.x?

**Comment by yohom** [comment] 2018-11-16 13:21
My flutter version is `0.11.3`, and I met same problem with @JediBurrell 's situation(`text if there's a space at the end`), so I found a workaround. This is my `flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.28.2)
```

**Comment by justinmc** [comment] 2018-12-26 22:36
I'm unable to reproduce this on the iOS simulator.  I'll try on a real device soon if I can get set up.  There have been several improvements to the TextField cursor recently that hopefully have fixed this.

**Comment by goderbauer** [comment] 2019-01-03 21:41
With the example code given I cannot reproduce this anymore on neither a physical Android nor iOS device. I am tentatively closing this. If you still see this, please do not hesitate to reopen with additional details of how you reproduced it.

**Closed by goderbauer** 2019-01-03 21:41 UTC
Labels: a: text input, framework

**Comment by zoechi** [comment] 2019-01-04 11:01
Looks like a dup of #24456 that was fixed recently https://github.com/flutter/flutter/issues/24456#issuecomment-446707682

**Comment by JWong1105** [comment] 2019-08-06 02:35
> I made a workaround to fix this problem, you can try it. @JediBurrell
> 
> ```dart
> _controller.addListener(() {
>   if (_controller.text.length != _controller.text.trim().length) {
>     _controller.text = _controller.text.trim();
>   }
>   _controller.selection =
>     TextSelection.collapsed(offset: _controller.text.length);
> });
> ```

hello, but i wanna show the last white space, do you have any idea? your method will remove the last white space.
