### ISSUE TITLE
[Web]MyApp runs twice.

### ISSUE THREAD

**Issue by JDongKhan** [flutter/flutter#102127] opened 2022-04-19 06:01 UTC
https://user-images.githubusercontent.com/4929805/163935911-220b6504-1438-41ff-88ce-caa896d1f311.mov

When I refresh the page，MyApp runs twice.

Chrome version: 100.0.4896.88

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/jd/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by navaronbracke** [comment] 2022-04-19 06:08
This is working as intended.

The first time your app starts, it prints once.
When you refresh the page, it rebuilds and prints again.

Since your terminal was running all the time, the second print just shows up after the first one.

**Comment by maheshmnj** [comment] 2022-04-19 07:40
Hi @JDongKhan, Thanks for filing the issue. @navaronbracke is right, When you reload from the browser the console isn't cleared and hence you are seeing the logs twice. You may try hot restarting from Android Studio or from the terminal and you should see a single log in the console.

Closing as this is not really a bug and it is working as intended.

**Closed by maheshmnj** 2022-04-19 07:40 UTC
Labels: in triage

**Comment by JDongKhan** [comment] 2022-04-19 07:51
@maheshmnj 
Thanks for response,I'll try what you said.
