### ISSUE TITLE
Unable to load asset images after upgrade 1.17.3

### ISSUE THREAD

**Issue by saravananmnm** [flutter/flutter#59328] opened 2020-06-12 14:14 UTC
```bash
I/flutter (10549): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (10549): The following assertion was thrown resolving an image codec:
I/flutter (10549): Unable to load asset:
I/flutter (10549):
I/flutter (10549): When the exception was thrown, this was the stack:
I/flutter (10549): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter (10549): <asynchronous suspension>
I/flutter (10549): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:664:31)
I/flutter (10549): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:648:14)
I/flutter (10549): #3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:501:13)
I/flutter (10549): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:359:22)
I/flutter (10549): #5      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:499:80)
I/flutter (10549): #6      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
I/flutter (10549): #7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:330:9)
I/flutter (10549): #8      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:460:26)
I/flutter (10549): (elided 13 frames from dart:async)
I/flutter (10549):
I/flutter (10549): Image provider: AssetImage(bundle: null, name: "")
I/flutter (10549): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#1a142(), name: "", scale: 1.0)
I/flutter (10549): ════════════════════════════════════════════════════════════════════════════════════════════════════


```

**Comment by saravananmnm** [comment] 2020-06-12 14:17
C:\Saravanan\Flutter_Sdk\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)
    • Flutter version 1.17.3 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision b041144f83 (8 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Sony Xperia 10 • 192.168.215.103:5555 • android-x86 • Android 10 (API 29)

• No issues found!

**Comment by iapicca** [comment] 2020-06-12 14:26
Hi @saravananmnm 
the issue might be caused by your implementation
can you please provide a minimal complete reproducible code sample.
Thank you

**Comment by saravananmnm** [comment] 2020-06-12 14:30
` Row(
                              mainAxisAlignment: MainAxisAlignment.end,
                              children: <Widget>[
                                (item.mAuctionGuidePrice != null ||
                                        item.mCurrentBidPriced != null)
                                    ? Image.asset(
                                  mViewModel.getCurrencyValue(
                                      item.mCurrencyCode),
                                  height: 30.0,
                                  width: 30.0,
                                )
                                    : Container(),
                                SizedBox(
                                  width: 5.0,
                                ),
                                Text(
                                  item.mCurrentBidPriced == null
                                      ? item.mAuctionGuidePrice.toString()
                                      : item.mCurrentBidPriced.toString(),
                                  style: TextStyle(
                                      color: Colors.white, fontSize: 34.0),
                                ),
                              ],
                            ),`

`String getCurrencyValue(String aCurrencyCode) {
    switch (aCurrencyCode) {
      case StringConstant.CURRENCY_INDIA:
        return AssetConstant.RUPEE_SYMBOL;
        break;
      case StringConstant.CURRENCY_EURO:
        return AssetConstant.POUND_SYMBOL;
        break;
      default:
        return "";
    }
  }`

**Comment by saravananmnm** [comment] 2020-06-12 14:30
`cupertino_icons: ^0.1.2
  package_info: ^0.4.0+3
  http: ^0.12.0+1
  kiwi: ^0.1.0
  rxdart: ^0.23.1
  shared_preferences: ^0.5.1+1
  sembast: ^2.0.1+2
  fluttertoast: ^4.0.1
  font_awesome_flutter: ^8.5.0
  jaguar_serializer:
  device_info: ^0.4.0+2
  imei_plugin: ^1.1.6
  permission_handler: ^4.3.0
  jaguar_retrofit: ^2.8.8
  loadmore: ^1.0.3
  url_launcher: ^5.1.3
  intl:
  flutter_google_places:
  google_maps_webservice:
  geolocator: ^5.3.1
  google_maps_flutter: ^0.5.21+2
  flutter_local_notifications:
  firebase_messaging:
  signature: ^2.0.0
  path_provider: ^1.6.5
  image_picker: ^0.6.1+4
  flutter_map: ^0.9.0
  flutter_native_timezone: ^1.0.4
  image: ^2.1.12
  flutter_polyline_points: ^0.1.0
  path: ^1.6.4
  app_settings: ^3.0.1
  webview_flutter: ^0.3.21
  cached_network_image: ^2.2.0+1
  geocoder: ^0.2.1`

**Comment by TahaTesser** [comment] 2020-06-12 15:37
Hi @saravananmnm 
Your snippet isn't complete
Can you please provide and a minimal complete reproducible code sample without using any packages?
Thank you

**Comment by saravananmnm** [comment] 2020-06-12 17:57
`Widget getHeaderCard(BuildContext context, AuctionInfoModel item) {
    return Container(
      width: MediaQuery.of(context).size.width,
      margin: EdgeInsets.all(10.0),
      child: Card(
          elevation: 8.0,
          shape:
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.0)),
          color: mViewModel.getCardColour(item.mAuctionStatus),
          child: Padding(
            padding: EdgeInsets.fromLTRB(15.0, 10.0, 15.0, 10.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(
                      'Time Left',
                      style: TextStyle(color: Colors.white, fontSize: 9.0),
                    ),
                    Text(
                      Utils.getsecondsfromDate(
                          item.mAuctionClosesInSeconds ?? 0),
                      style: TextStyle(fontSize: 34.0, color: Colors.white),
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: <Widget>[
                        SizedBox(
                          width: 5.0,
                        ),
                        Text(
                          'Hours',
                          style: TextStyle(color: Colors.white, fontSize: 9.0),
                        ),
                        SizedBox(
                          width: 30.0,
                        ),
                        Text(
                          'Min',
                          style: TextStyle(color: Colors.white, fontSize: 9.0),
                        ),
                        SizedBox(
                          width: 30.0,
                        ),
                        Text(
                          'Sec',
                          style: TextStyle(color: Colors.white, fontSize: 9.0),
                        )
                      ],
                    )
                  ],
                ),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: <Widget>[
                    Container(
                      child: Row(
                        children: <Widget>[
                          Container(
                            padding: EdgeInsets.only(left: 5.0, right: 5.0),
                            height: 15.0,
                            decoration: BoxDecoration(
                              color: Colors.white30,
                              borderRadius: BorderRadius.circular(20.0),
                            ),
                            child: Row(
                              children: <Widget>[
                                Icon(
                                  Icons.local_shipping,
                                  color: Colors.white,
                                  size: 10.0,
                                ),
                                SizedBox(
                                  width: 5.0,
                                ),
                                Text(
                                  item.mVehicleType ?? '',
                                  style: TextStyle(
                                      color: Colors.white, fontSize: 9.0),
                                ),
                              ],
                            ),
                          ),
                          SizedBox(
                            width: 5.0,
                          ),
                          Container(
                            alignment: Alignment.centerRight,
                            padding: EdgeInsets.only(left: 5.0, right: 5.0),
                            height: 15.0,
                            decoration: BoxDecoration(
                              color: Colors.white30,
                              borderRadius: BorderRadius.circular(20.0),
                            ),
                            child: Text(
                              "Total Miles : ${item.mTotalDistance.round() ?? ''}",
                              style:
                                  TextStyle(color: Colors.white, fontSize: 9.0),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 10.0),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        children: <Widget>[
                          Image.asset(
                            AssetConstant.LAW,
                            height: 15.0,
                            width: 15.0,
                          ),
                          SizedBox(
                            width: 5.0,
                          ),
                          Text(
                            item.mCurrentBidPriced == null
                                ? "Guide Price"
                                : "Your Current Bid",
                            style:
                                TextStyle(color: Colors.white, fontSize: 12.0),
                          ),
                        ],
                      ),
                    ),
                    (item.mAuctionGuidePrice != null ||
                            item.mCurrentBidPriced != null)
                        ? Container(
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.end,
                              children: <Widget>[
                                (item.mAuctionGuidePrice != null ||
                                        item.mCurrentBidPriced != null)
                                    ? Image.asset(
                                  mViewModel.getCurrencyValue(
                                      item.mCurrencyCode),
                                  height: 30.0,
                                  width: 30.0,
                                )
                                    : Container(),
                                SizedBox(
                                  width: 5.0,
                                ),
                                Text(
                                  item.mCurrentBidPriced == null
                                      ? item.mAuctionGuidePrice.toString()
                                      : item.mCurrentBidPriced.toString(),
                                  style: TextStyle(
                                      color: Colors.white, fontSize: 34.0),
                                ),
                              ],
                            ),
                          )
                        : Container(
                            height: 40.0,
                            width: 34.0,
                          ),
                  ],
                ),
              ],
            ),
          )),
    );
  }`

**Comment by iapicca** [comment] 2020-06-15 06:45
Hi @saravananmnm 
please try the following steps:

<details>
  <summary>steps</summary>

1. save ´https://miro.medium.com/max/1020/1*37gf5xxgWr9KUOb-waZo7g.png´ as ´dash.png´

2. run consecutively these commands in your terminal 
```console
flutter upgrade -f
flutter create asset_image
cd asset_image
mkdir assets
```
3. move ´dash.png´ in the ´assets´ folder

4. paste
´´´yaml
  assets:
    - assets/dash.png
´´´
In your ´pubspec.yaml´ below 
´´´yaml
uses-material-design: true
´´´
5. replace the content of `main.dart` with the following
```dart
import 'package:flutter/material.dart';

void main() {
  const Widget _app = MyApp();
  runApp(_app);
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp(
    home: Material(
      child: Center(
        child: Image(
          image: AssetImage('assets/dash.png'),
        ),
      ),
    ),
  );
}
```

6. make sure you have a device attached and run `flutter run -v`


</details>

if the issue persist please create a public github repo with the app above 
and provide both the link to said repo and the output of `flutter run -v`
together with your `flutter doctor -v`
Thank you

**Comment by saravananmnm** [comment] 2020-06-22 09:57
thanks, its working fine.

**Comment by iapicca** [comment] 2020-06-24 13:28
Hi @saravananmnm 
I'm glad to hear that
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by iapicca** 2020-06-24 13:28 UTC
Labels: in triage
