### ISSUE TITLE
flutter doctor / help

### ISSUE THREAD

**Issue by HelloWordSurely** [flutter/flutter#103791] opened 2022-05-14 08:15 UTC
[☠]Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: [
        {

**Comment by wzslr321** [comment] 2022-05-14 08:36
Please, don't delete the PR template and share more information according to the instruction in the template.

**Comment by HelloWordSurely** [comment] 2022-05-14 11:02
> Lütfen PR şablonunu silmeyin ve şablondaki talimata göre daha fazla bilgi paylaşın.

Okey bro thanks

**Comment by stuartmorgan** [comment] 2022-05-14 12:02
Duplicate of https://github.com/flutter/flutter/issues/102451

**Closed by stuartmorgan** 2022-05-14 12:02 UTC
