### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument (URI scheme not allowed): "file:///E:/FILE%20NEW/flutter_project/haikal_ekel/haikal_ekel/lib/utilities/Constants.dart"

### ISSUE THREAD

**Issue by michaelhaikal31** [flutter/flutter#74103] opened 2021-01-16 04:51 UTC
## Command
```
flutter --no-color run --machine --verbose --track-widget-creation --device-id=chrome lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument (URI scheme not allowed): "file:///E:/FILE%20NEW/flutter_project/haikal_ekel/haikal_ekel/lib/utilities/Constants.dart"
```
#0      DartUri._recordAbsoluteUri (package:dwds/src/utilities/dart_uri.dart:86:7)
#1      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:60:9)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:88:19)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:171:37)
<asynchronous suspension>
#5      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:138:23)
#6      DebugService.start (package:dwds/src/services/debug_service.dart:142:55)
#7      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:184:25)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.23.0-18.0.pre at E:\FILE NEW\sdk\flutter
    • Framework revision 37ebe3d82a (3 months ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.52.0)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 87.0.664.75

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: e0c63cd35e15e407a80dc44281cc392535fcce25
### Plugins
flutter_full_pdf_viewer-1.0.6
flutter_webview_plugin-0.3.11
path_provider-1.6.9
path_provider_macos-0.0.4+3
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+9
shared_preferences_web-0.1.2+7
url_launcher-5.4.10
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6

**Comment by iapicca** [comment] 2021-01-16 09:36
@michaelhaikal31 
please take a look at this possible [solution](https://github.com/flutter/flutter/issues/59924#issuecomment-678287123)
possibel duplicate of https://github.com/flutter/flutter/issues/59924

**Comment by darshankawar** [comment] 2021-01-18 07:56
@michaelhaikal31 
Along with above referred possible solution, also try [this](https://github.com/flutter/flutter/issues/64492#issuecomment-680100884) and see if it helps.

**Comment by pedromassangocode** [comment] 2021-02-12 10:23
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-12 10:23 UTC
Labels: in triage, waiting for customer response
