### ISSUE TITLE
Process.start 在release模式中调用的程序无法隐藏被调用的程序的界面

### ISSUE THREAD

**Issue by shirne** [flutter/flutter#81609] opened 2021-05-01 11:19 UTC
## Details

**Target Platform:** Windows
**Target OS version/browser:** Win10 2004
**Devices:**

## Logs

<details>
<summary>Logs</summary>

```
Analyzing hosted...
No issues found! (ran in 0.5s)
```

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.928], locale zh-CN)
    • Flutter version 2.0.5 at D:\flutter
    • Framework revision adc687823a (2 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\shirn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.49

• No issues found!
```

</details>

我正在使用Flutter开发一个中国象棋的界面端，项目地址 [chinese chess](https://github.com/shirne/chinese_chess.git) .

项目需要后台调用ucci端来获取行棋的招法信息，调用是用的Process.start(路径, []) 在ide调试时被调用的ucci端都是隐藏的。

但是使用flutter build windows 生成出来的release ( 目录 build\windows\runner\Release )的程序中执行时，不管是不是在shell里执行都会显示出被调用端的界面

 flutter中的process可以正常写入和接收信息，显示出来那个程序端口是空白的，没有任何信息 

![aaaa](https://user-images.githubusercontent.com/2263157/116780918-13eafd00-aab2-11eb-9735-4a37546ebcfb.png)

**Comment by pedromassangocode** [comment] 2021-05-03 11:18
Hi @shirne 
Can you please elaborate? It is not clear what this issue is about.
Can you please provide a minimal complete reproducible code sample?

Also, please avoid posting comments in a language other than English as Flutter uses English to interact across its online community.
Thank you

[Google Translate]

嗨@shirne
你能详细说明一下吗？ 目前尚不清楚此问题是关于什么的。
您能否提供一个最小的完整的可复制代码示例？

另外，请避免以非英语的其他语言发布评论，因为Flutter使用英语在其在线社区中进行互动。
谢谢

**Comment by shirne** [comment] 2021-05-04 01:09
Demo : https://github.com/shirne/flutter-cmd

<details>
<summary>main.dart</summary>

```
import 'dart:io';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Process process;
  TextEditingController cmdController =
  TextEditingController();
  List<String> messages = [];

  @override
  void initState() {
    super.initState();
    Process.start('cmd.exe', []).then((value) {
      process = value;
      process.stdout.listen(onMessage);
      setState(() {
        messages.add('cmd ok');
      });
    });
  }

  @override
  dispose(){
    process.kill();
    process = null;
    super.dispose();
  }

  setCmd(String cmd){
    if(cmd == 'clear'){
      messages.clear();
    }
    if(process != null){
      process.stdin.writeln(cmd);
    }
  }

  onMessage(List<int> event){
    String lines = String.fromCharCodes(event).trim();
    setState(() {
      messages+= lines.split('\n');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: WillPopScope(
        onWillPop: (){
          if(process!=null)process.kill();
          return Future.value(true);
        },
        child: Padding(
          padding: EdgeInsets.all(20),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Row(
                children: [
                  Text(
                    'Cmd:',
                  ),
                  SizedBox(width: 150,
                    child:TextField(
                      controller: cmdController,
                    ),
                  ),

                  ElevatedButton(onPressed: (){
                    setCmd(cmdController.text);
                    cmdController.text = '';
                  }, child: Text('Send')),
                  SizedBox(width: 10,),
                  ElevatedButton(onPressed: (){
                    setCmd('clear');
                  }, child: Text('Clear')),
                ],
              ),
              Expanded(
                child: ListView(
                  children: messages.map<Widget>((item)=>Text(item)).toList(),
                ),
              ),

            ],
          ),
        ),
      ) ,
    );
  }
}

```
</details>
Here's the demo project  and code  . you can clone the project or create an empty project then copy the code to main.dart

1. open the project with androidstudio
2. select device windows  and click run main.dart
![ok](https://user-images.githubusercontent.com/2263157/116950593-15861200-acb8-11eb-8b90-691399742d06.png)
now it's OK . **the cmd process running in child mode and the cmd window is hidden**
3. run  "flutter buid windows" in this project
4. open directory build/windows/runner/Release  or Debug
5. double click to run  "process_test.exe"
![error](https://user-images.githubusercontent.com/2263157/116950607-1c148980-acb8-11eb-929a-53ac1e2c0232.png)
the cmd process is **not** running in child mode and the cmd window is **not** hidden

**Comment by pedromassangocode** [comment] 2021-05-04 06:38
Hi @shirne 
From what I can see, the issue is related to Dart rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).

Closing, as this isn't an issue with Flutter itself.  
Thank you

**Closed by pedromassangocode** 2021-05-04 06:38 UTC
Labels: in triage
