### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DotVixus** [flutter/flutter#25350] opened 2018-12-14 03:54 UTC
```
[myapp] flutter create myapp
Waiting for another flutter command to release the startup lock...
Creating project myapp...
  myapp\.gitignore (created)
  myapp\.idea\libraries\Dart_SDK.xml (created)
  myapp\.idea\libraries\Flutter_for_Android.xml (created)
  myapp\.idea\libraries\KotlinJavaRuntime.xml (created)
  myapp\.idea\modules.xml (created)
  myapp\.idea\runConfigurations\main_dart.xml (created)
  myapp\.idea\workspace.xml (created)
  myapp\.metadata (created)
  myapp\android\app\build.gradle (created)
  myapp\android\app\src\main\java\com\example\myapp\MainActivity.java (created)
  myapp\android\build.gradle (created)
  myapp\android\myapp_android.iml (created)
  myapp\android\app\src\main\AndroidManifest.xml (created)
  myapp\android\app\src\main\res\drawable\launch_background.xml (created)
  myapp\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  myapp\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  myapp\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  myapp\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  myapp\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  myapp\android\app\src\main\res\values\styles.xml (created)
  myapp\android\gradle\wrapper\gradle-wrapper.properties (created)
  myapp\android\gradle.properties (created)
  myapp\android\settings.gradle (created)
  myapp\ios\Runner\AppDelegate.h (created)
  myapp\ios\Runner\AppDelegate.m (created)
  myapp\ios\Runner\main.m (created)
  myapp\ios\Runner.xcodeproj\project.pbxproj (created)
  myapp\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  myapp\ios\Flutter\AppFrameworkInfo.plist (created)
  myapp\ios\Flutter\Debug.xcconfig (created)
  myapp\ios\Flutter\Release.xcconfig (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  myapp\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  myapp\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  myapp\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  myapp\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  myapp\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  myapp\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  myapp\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  myapp\ios\Runner\Base.lproj\Main.storyboard (created)
  myapp\ios\Runner\Info.plist (created)
  myapp\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  myapp\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  myapp\lib\main.dart (created)
  myapp\myapp.iml (created)
  myapp\pubspec.yaml (created)
  myapp\README.md (created)
  myapp\test\widget_test.dart (created)
Running "flutter packages get" in myapp...                      

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 527fef08135ab7df)
Crash report written to C:\Users\Dell\Documents\FlutterProjects\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
exit code 1
```
[flutter_01.log](https://github.com/flutter/flutter/files/2678594/flutter_01.log)

**Comment by zoechi** [comment] 2018-12-14 10:59
Duplicate of #15646

**Closed by zoechi** 2018-12-14 10:59 UTC
