### ISSUE TITLE
Web expression_evaluation_web_test failing on non-web HHH bot

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#69711] opened 2020-11-03 20:57 UTC
We're seeing these [sorts of failures](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8864642682270776256/+/steps/flutter_test_tool_tests/0/stdout) on the Flutter HHH bot:

```
23:47 +98 ~18 -13: test/integration.shard/expression_evaluation_web_test.dart: flutter test expression evaluation - can evaluate trivial expressions in a test [E]                                     
  Exception: Received app.stop event while waiting for app.started event
  
  the Dart compiler exited unexpectedly.
  
  #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
  #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:709:13)
  #2      _rootRun (dart:async/zone.dart:1182:47)
  #3      _CustomZone.run (dart:async/zone.dart:1093:19)
  #4      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
  #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
  #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
  #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
  #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
  #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
  #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
  #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
  #13     _rootRun (dart:async/zone.dart:1182:47)
  #14     _CustomZone.run (dart:async/zone.dart:1093:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
  #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
  #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
  #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
  #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
  #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
  #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
  #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
  #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
  #25     _rootRun (dart:async/zone.dart:1182:47)
  #26     _CustomZone.run (dart:async/zone.dart:1093:19)
  #27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
  #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
  #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
  #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
  #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
  #33     _StreamController.close (dart:async/stream_controller.dart:664:5)
  #34     _Socket._onData (dart:io-patch/socket_patch.dart:1976:21)
  #35     _rootRunUnary (dart:async/zone.dart:1206:13)
  #36     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
  #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
  #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
  #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
  #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
  #41     _StreamController._add (dart:async/stream_controller.dart:682:7)
  #42     _StreamController.add (dart:async/stream_controller.dart:624:5)
  #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1512:35)
  #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1010:18)
  #45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
  #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
  
  
  
  dart:async                                                         _Completer.completeError
  test/integration.shard/test_driver.dart 379:18                     FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart                            FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _StreamImpl.listen
  test/integration.shard/test_driver.dart 358:35                     FlutterTestDriver._waitFor
  test/integration.shard/test_driver.dart 555:54                     FlutterRunTestDriver._setupProcess.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart                            FlutterRunTestDriver._setupProcess.<fn>
  test/integration.shard/test_driver.dart 574:6                      FlutterRunTestDriver._setupProcess
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart 456:11                     FlutterRunTestDriver.run
  test/integration.shard/expression_evaluation_web_test.dart 140:22  batch2.startPaused
  test/integration.shard/expression_evaluation_web_test.dart 156:22  batch2.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/expression_evaluation_web_test.dart         batch2.<fn>
  dart:async                                                         runZoned
  test/src/common.dart 220:14                                        testWithoutContext.<fn>
  test/src/common.dart 190:18                                        test.<fn>
```

It's also surprising that we're seeing this failure on the non-web HHH bot. Is that a bug?

**Comment by sigmundch** [comment] 2020-11-03 21:02
I am guessing this is in the non-web bot because it is an integration test requiring a bit of setup to launch flutter tools and get things running end to end.

@jonahwilliams @annagrin - could you take a look?

**Comment by jonahwilliams** [comment] 2020-11-03 21:09
I do not have time to look at this currently. If you're unable to update the HHH bot to make these run I suggest skipping the web tests

**Comment by jonahwilliams** [comment] 2020-11-03 21:09
(FYI @zanderso )

**Comment by jonahwilliams** [comment] 2020-11-03 21:09
@ferhatb

**Comment by zanderso** [comment] 2020-11-03 21:40
`the Dart compiler exited unexpectedly.` indicates that some recent change to the Dart compiler is causing these tests to fail. I'd recommend bisecting on changes there to zero in on the commit where this starts. Reducing to P3 for now, but this may need to be escalated if it is blocking rolls.

**Comment by bkonyi** [comment] 2020-11-04 00:33
I believe this is blocking the SDK roll (@a-siva can you confirm?).

**Comment by sigmundch** [comment] 2020-11-04 00:38
Let's disable the test for now then, @a-siva @bkonyi or other folks, do you have some pointers for how to do so?

**Comment by annagrin** [comment] 2020-11-04 00:41
I will disable the tests for now - they should only run on the web bot.

**Comment by a-siva** [comment] 2020-11-04 00:48
The Dart rolls into Flutter are happening, see https://autoroll.skia.org/r/dart-sdk-flutter-engine?tab=status

Disabling the tests is fine so that the Flutter 3H bot turns green.

**Comment by annagrin** [comment] 2020-11-04 21:24
Update: the PR didn't fix all the tests that are failing. Initial investigation has shown that this might be not a bug on a bot (both bots are able to run web tests), but a potential issue with the SDK. Will update more when I manage to repro.

**Comment by annagrin** [comment] 2021-01-07 00:02
All web tools tests are now running on web HHH bots. Closing.

**Closed by annagrin** 2021-01-07 00:02 UTC
Labels: P3, dependency: dart, passed first triage, platform-web, severe: crash
