### ISSUE TITLE
Error trying to create flutter app in terminal

### ISSUE THREAD

**Issue by saurrutia** [flutter/flutter#53935] opened 2020-04-03 18:07 UTC
## Steps to Reproduce
1. Open terminal as Admin user.
2. Type flutter create c:\path\to\app\myapp
3. Error is shown.

## Logs
[flutter_02.log](https://github.com/flutter/flutter/files/4429126/flutter_02.log)

## command

flutter create C:\path\to\app\myapp

## exception

ProcessException: ProcessException: Access is denied.

  Command: cmd.exe /c ver

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _WindowsUtils.name (package:flutter_tools/src/base/os.dart:328:51)
#5      new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:203:81)
#6      new Usage (package:flutter_tools/src/reporting/usage.dart:79:9)
#7      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:117:20)
#8      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:100:41)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#10     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:88:20)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:117:32)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:115:23)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:115:23)
#14     Usage.instance (package:flutter_tools/src/reporting/usage.dart:85:40)
#15     flutterUsage (package:flutter_tools/src/reporting/usage.dart:69:33)
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:510:9)
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#23     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#24     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#27     _rootRun (dart:async/zone.dart:1126:13)
#28     _CustomZone.run (dart:async/zone.dart:1023:19)
#29     _runZoned (dart:async/zone.dart:1518:10)
#30     runZoned (dart:async/zone.dart:1465:12)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#32     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#33     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CommandRunner.run (package:args/command_runner.dart:112:14)
#36     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#37     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#38     _rootRun (dart:async/zone.dart:1126:13)
#39     _CustomZone.run (dart:async/zone.dart:1023:19)
#40     _runZoned (dart:async/zone.dart:1518:10)
#41     runZoned (dart:async/zone.dart:1502:12)
#42     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#43     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#44     _rootRun (dart:async/zone.dart:1126:13)
#45     _CustomZone.run (dart:async/zone.dart:1023:19)
#46     _runZoned (dart:async/zone.dart:1518:10)
#47     runZoned (dart:async/zone.dart:1465:12)
#48     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#49     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#50     run (package:flutter_tools/runner.dart:50:10)
#51     main (package:flutter_tools/executable.dart:65:9)
#52     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#53     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.719], locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    [32m•[39m Framework revision f139b11009 (4 days ago), 2020-03-30 13:57:30 -0700
    [32m•[39m Engine revision af51afceb8
    [32m•[39m Dart version 2.7.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.6)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 44.0.2
    [32m•[39m Dart plugin version 192.7761
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[32m[✓][39m Connected device (1 available)
    [32m•[39m sdk gphone x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

[32m•[39m No issues found!
```

I am able to run the command
![image](https://user-images.githubusercontent.com/47123347/78391677-11169380-75a4-11ea-832d-f43336af2f0f.png)

**Comment by jonahwilliams** [comment] 2020-04-03 18:15
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-04-03 18:15 UTC
