### ISSUE TITLE
Waiting for connection from Dart debug extension

### ISSUE THREAD

**Issue by fcioffi** [flutter/flutter#59240] opened 2020-06-11 06:57 UTC
Hi guys.
Launching example app from VSCode it not works.
Google Chrome with Dart Debug Extension installed shows blank page.
Thanks a lot for support.

```
Dart Code extension: 3.11.0
Flutter extension: 3.11.0 (not activated)

App: Visual Studio Code
Remote: wsl
Version: 1.46.0
Platform: linux

Workspace type: Flutter
Multi-root?: false

Dart SDK:
    Loc: /opt/flutter/bin/cache/dart-sdk
    Ver: 2.9.0-8.2.beta
Flutter SDK:
    Loc: /opt/flutter
    Ver: 1.18.0-11.1.pre

HTTP_PROXY: undefined
NO_PROXY: undefined

Thu Jun 11 2020 [08:43:57 GMT+0200 (Central European Summer Time)] Log file started
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] Termination requested!
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Requested to terminate with SIGINT...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Terminating processes...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Terminating related process 1076 with SIGINT...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Terminating main process with SIGINT...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Disabling break-on-exception and removing all breakpoints
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Unpausing all threads...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Removing all stored data...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Waiting for process to finish...
[8:44:10 AM] [FlutterRun] [Info] [Flutter (Web Server)] Process terminated! null, SIGINT
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] Process exited (sigint)
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Disconnecting...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] Disconnect requested!
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Requested to terminate with SIGINT...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Did not need to terminate processes
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Removing all stored data...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Waiting for process to finish...
[8:44:10 AM] [Observatory] [Info] [Flutter (Web Server)] TERM: Disconnecting...
[8:44:11 AM] [General] [Info] Debugger:SessionDuration timing: 182153ms (Flutter)
[8:44:12 AM] [General] [Info] Starting debug session...
[8:44:12 AM] [General] [Info]     workspace: /home/fcioffi/coding/myapp
[8:44:12 AM] [General] [Info] Using found common entry point: /home/fcioffi/coding/myapp/lib/main.dart
[8:44:12 AM] [General] [Info] Using workspace as cwd: /home/fcioffi/coding/myapp
[8:44:12 AM] [General] [Info] Detected launch project as Flutter
[8:44:12 AM] [General] [Info] Using Flutter debug adapter for this session
[8:44:12 AM] [FlutterDaemon] [Info] ==> [{"id":"6","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/home/fcioffi/coding/myapp"}}]
[8:44:12 AM] [FlutterDaemon] [Info] <== [{"id":"6","result":{"platforms":["ios","android","web"]}}]
[8:44:12 AM] [General] [Info] Checking for errors before launching
[8:44:12 AM] [General] [Info] Debug session starting...
    {
        "type": "dart",
        "request": "launch",
        "program": "/home/fcioffi/coding/myapp/lib/main.dart",
        "cwd": "/home/fcioffi/coding/myapp",
        "name": "Flutter (Web Server)",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "globalFlutterArgs": [],
        "args": [],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "/opt/flutter/bin/cache/dart-sdk/bin/dart",
        "maxLogLineLength": 2000,
        "pubPath": "/opt/flutter/bin/cache/dart-sdk/bin/pub",
        "pubSnapshotPath": "/opt/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "useFlutterStructuredErrors": true,
        "debuggerHandlesPathsEverywhereForBreakpoints": true,
        "supportsWsVmService": true,
        "supportsExposeUrl": true,
        "evaluateGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "useWriteServiceInfo": true,
        "supportsDebugInternalLibraries": false,
        "forceFlutterVerboseMode": true,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "/opt/flutter/bin/flutter",
        "deviceId": "web-server",
        "deviceName": "Web Server (web-javascript)",
        "showMemoryUsage": false,
        "debugServer": 51156,
        "debuggerType": 2
    }
[8:44:12 AM] [FlutterRun] [Info] [Flutter (Web Server)] Spawning /opt/flutter/bin/flutter with args ["run","--machine","--target","lib/main.dart","-d","web-server","--track-widget-creation","--start-paused","--web-server-debug-protocol","ws","--web-allow-expose-url","-v"]
[8:44:12 AM] [FlutterRun] [Info] [Flutter (Web Server)] ..  in /home/fcioffi/coding/myapp
[8:44:12 AM] [FlutterRun] [Info] [Flutter (Web Server)] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[8:44:12 AM] [FlutterRun] [Info] [Flutter (Web Server)]     PID: 647
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +11 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +53 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] 2738a1148ba6c9a6114df62358109407c3ef2553
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] executing: [/opt/flutter/] git tag --contains HEAD
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [ +184 ms] Exit code 0 from: git tag --contains HEAD
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +1 ms] 1.18.0-11.1.pre
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +9 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +1 ms] origin/beta
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +1 ms] https://github.com/flutter/flutter.git
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [ +114 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +1 ms] beta
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +46 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +16 ms] executing: /opt/Android/platform-tools/adb devices -l
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +81 ms] List of devices attached
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +7 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [ +234 ms] Generating /home/fcioffi/coding/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [{"event":"daemon.connected","params":{"version":"0.5.3","pid":1172}}]
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [{"event":"app.start","params":{"appId":"d2219151-917a-4597-9c1a-dd9632f18e0f","deviceId":"web-server","directory":"/home/fcioffi/coding/myapp","supportsRestart":true,"launchMode":"run"}}]
[8:44:13 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [ +101 ms] Launching lib/main.dart on Web Server in debug mode...
[8:44:14 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [{"method":"app.exposeUrl","params":{"url":"http://127.0.0.1:51855/$debug"},"id":"1"}]
[8:44:14 AM] [General] [Info] Exposing URL: http://127.0.0.1:51855/%24debug
[8:44:14 AM] [General] [Info] Mapping URL: http://127.0.0.1:51855/%24debug
[8:44:14 AM] [General] [Info] Mapped URL: http://127.0.0.1:51856/%24debug
[8:44:14 AM] [General] [Info] Final URI: http://127.0.0.1:51856/$debug
[8:44:14 AM] [General] [Info] Final URL: http://127.0.0.1:51856/$debug
[8:44:14 AM] [FlutterRun] [Info] [Flutter (Web Server)] ==> [{"id":"1","result":{"url":"http://127.0.0.1:51856/$debug"}}]
[8:44:14 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +77 ms] Updating assets
[8:44:14 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [{"event":"app.progress","params":{"appId":"d2219151-917a-4597-9c1a-dd9632f18e0f","id":"0","progressId":null,"message":"Syncing files to device Web Server..."}}]
[8:44:14 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [ +135 ms] Generating /home/fcioffi/coding/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[8:44:14 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +35 ms] <- reset
[8:44:14 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +6 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart /opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /opt/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.XOMDOZ/app.dill --libraries-spec file:///opt/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.ZSBGVO --filesystem-scheme org-dartlang-app --initialize-from-dill build/cache.dill --platform file:///opt/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[8:44:14 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [  +26 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[8:44:15 AM] [Analyzer] [Info] ==> {"id":"35","method":"analysis.getHover","params":{"file":"/home/fcioffi/coding/myapp/lib/main.dart","offset":1329},"clientRequestTime":1591857855878}
[8:44:15 AM] [Analyzer] [Info] <== {"id":"35","result":{"hovers":[{"offset":1329,"length":3,"dartdoc":"Initializes [key] for subclasses.","elementDescription":"{Key key}","elementKind":"parameter","isDeprecated":false,"staticType":"Key"}]}}
[8:44:27 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [{"event":"app.progress","params":{"appId":"d2219151-917a-4597-9c1a-dd9632f18e0f","id":"0","progressId":null,"finished":true}}]
[8:44:27 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [+13242 ms] Synced 22.0MB.
[8:44:27 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [        ] <- accept
[8:44:27 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [   +2 ms] Waiting for connection from Dart debug extension at http://localhost:51853
[8:44:27 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [{"event":"app.webLaunchUrl","params":{"url":"http://localhost:51853","launched":false}}]
[8:44:27 AM] [FlutterRun] [Info] [Flutter (Web Server)] <== [{"method":"app.exposeUrl","params":{"url":"http://127.0.0.1:51854"},"id":"2"}]
[8:44:27 AM] [General] [Info] Exposing URL: http://127.0.0.1:51854/
[8:44:27 AM] [General] [Info] Mapping URL: http://127.0.0.1:51854/
[8:44:27 AM] [General] [Info] Mapped URL: http://127.0.0.1:51876/
[8:44:27 AM] [General] [Info] Final URI: http://127.0.0.1:51876/
[8:44:27 AM] [General] [Info] Final URL: http://127.0.0.1:51876/
[8:44:27 AM] [FlutterRun] [Info] [Flutter (Web Server)] ==> [{"id":"2","result":{"url":"http://127.0.0.1:51876/"}}]
[8:46:16 AM] [Analyzer] [Info] ==> {"id":"36","method":"analysis.setPriorityFiles","params":{"files":[]},"clientRequestTime":1591857976433}
[8:46:16 AM] [Analyzer] [Info] <== {"id":"36"}
Thu Jun 11 2020 [08:46:42 GMT+0200 (Central European Summer Time)] Log file ended
```

**Comment by TahaTesser** [comment] 2020-06-11 12:20
Hi @fcioffi 
Looks like your flutter extension i vsc is disabled, please activate it and try again
```
Flutter extension: 3.11.0 (not activated)
```

If the problem persist, can you please provide your `flutter doctor -v`, your `flutter run --verbose`
Thank you

**Comment by fcioffi** [comment] 2020-06-11 13:01
Hi @TahaTesser,
thanks for the response. I don't know why the log show that plugin is not actevated, It is active and on mobile it runs correctly. I think that it is active, I launch from vscode -> Debug -> Dart & Flutter

This is the output of doctor:
```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-11.1.pre at /opt/flutter
    • Framework revision 2738a1148b (4 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/Android
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

And this is the output from flutter run (that runs correctly).
```
[   +9 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2738a1148ba6c9a6114df62358109407c3ef2553
[        ] executing: [/opt/flutter/] git tag --contains HEAD
[ +173 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] 1.18.0-11.1.pre
[  +10 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +111 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[  +44 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +37 ms] executing: /opt/Android/platform-tools/adb devices -l
[  +64 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +186 ms] Generating /home/fcioffi/coding/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +84 ms] Launching lib/main.dart on Web Server in debug mode...
[  +51 ms] Updating assets
[  +84 ms] Syncing files to device Web Server...
[  +36 ms] Generating /home/fcioffi/coding/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +31 ms] <- reset
[   +5 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart /opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /opt/flutter/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.NJILUK/app.dill --libraries-spec
file:///opt/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-root /tmp/flutter_tools.PFLFMW --filesystem-scheme org-dartlang-app --initialize-from-dill build/cache.dill --platform
file:///opt/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +29 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+14720 ms] Syncing files to device Web Server... (completed in 14,814ms, longer than expected)
[        ] Synced 22.0MB.
[        ] <- accept
[        ] lib/main.dart is being served at http://localhost:53679
[   +6 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+65624 ms] Application finished.
[   +3 ms] "flutter run" took 81,000ms.
```

I run on WSL in VSCODE the problem is only when I run from it.

Thanks a lot.

**Comment by TahaTesser** [comment] 2020-06-11 14:25
Hi @fcioffi 

<img width="607" alt="Screenshot 2020-06-11 at 7 54 49 PM" src="https://user-images.githubusercontent.com/48603081/84398323-6cf13e80-ac1d-11ea-98ec-8de3e99a5f32.png">

make sure it is activated here and sine the app runs from `flutter run --verbose` i believe this should be something between wsl and vs code


Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-11 14:25 UTC
Labels: in triage

**Comment by LemonSpike** [comment] 2021-04-24 10:19
I had to do `flutter clean` and then things magically started working.
