### ISSUE TITLE
MouseRegion does not call onHover when mouse button is pressed

### ISSUE THREAD

**Issue by rekire** [flutter/flutter#125763] opened 2023-04-30 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a widget with this build method:
  ```dart
  @override
  Widget build(BuildContext context) {
    const width = 240.0;
    return Center(
      child: SizedBox(
        width: width,
        height: width,
        child: MouseRegion(
          onEnter: (details) {
            print('onEnter $details ${details.buttons} ${details.down}');
          },
          onHover: (details) {
            print('onHover $details ${details.buttons} ${details.down}');
          },
          child: const ColoredBox(color: Colors.pink),
        ),
      ),
    );
  }
  ```
2. Click and keep pressed outside of the pink box and move the cursor above it

### Expected results

I can see the `onEnter` event and lots of `onHover` events where I can read out which mouse button is pressed

### Actual results

The `onEnter` event is fired the `onHover` event not.

### Code sample

<details><summary>Code sample</summary>

```dart
class MouseRegionBug extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const width = 240.0;
    return Center(
      child: SizedBox(
        width: width,
        height: width,
        child: MouseRegion(
          onEnter: (details) {
            print('onEnter $details ${details.buttons} ${details.down}');
          },
          onHover: (details) {
            print('onHover $details ${details.buttons} ${details.down}');
          },
          child: const ColoredBox(color: Colors.pink),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
flutter: onEnter _TransformedPointerEnterEvent#2ae49(position: Offset(328.3, 221.8)) 1 true
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.2.1 22D68 darwin-x64, locale de-DE)
    • Flutter version 3.7.11 on channel stable at /Users/rekire/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (vor 3 Wochen), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/rekire/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/rekire/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/rekire/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/rekire/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at /Users/rekire/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.7571.182/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /Users/rekire/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.8109.175/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by timmaffett** [comment] 2023-04-30 19:03
The docs for the `onHover` event handler within `MouseRegion` explicitly state that "Triggered when a pointer moves into a position within this widget *without buttons pressed*."

It looks like that behavior that you are seeing is correct and matches the documented intended behavior.

If you would like to get move events when the mouse buttons are pressed you can use a `Listener`'s `onPointerMove` event, which is "Called when a pointer that triggered an [onPointerDown] changes position."


excerpt from MouseRegion docs in `widgets/basic.dart`:
```dart
class MouseRegion extends SingleChildRenderObjectWidget {
...

  /// Triggered when a pointer moves into a position within this widget without
  /// buttons pressed.
  ///
  /// Usually this is only fired for pointers which report their location when
  /// not down (e.g. mouse pointers). Certain devices also fire this event on
  /// single taps in accessibility mode.
  ///
  /// This callback is not triggered by the movement of the widget.
  ///
  /// The time that this callback is triggered is during the callback of a
  /// pointer event, which is always between frames.
  ///
  /// See also:
  ///
  ///  * [Listener.onPointerHover], which does the same job. Prefer using
  ///    [Listener.onPointerHover], since hover events are similar to other regular
  ///    events.
  final PointerHoverEventListener? onHover;

...

```
and further documentation from `Listener` for `Listener.onPointerHover` - it clearly states that onPointerHover events are called "when a pointer that has *not triggered* an [OnPointerDown] changes position".

```dart
  /// Called when a pointer that has not triggered an [onPointerDown] changes
  /// position.
  ///
  /// This is only fired for pointers which report their location when not down
  /// (e.g. mouse pointers, but not most touch pointers).
  final PointerHoverEventListener? onPointerHover;
```

**Comment by rekire** [comment] 2023-04-30 19:43
Thank you for this hint. I missed that detail. When I modify my code to this:

```dart
  @override
  Widget build(BuildContext context) {
    const width = 240.0;
    return Center(
      child: Listener(
        onPointerDown: (details) {
          print('onPointerDown: ${details.localPosition}');
        },
        onPointerMove: (details) {
          print('onPointerMove: ${details.localPosition}');
        },
        onPointerHover: (details) {
          print('onPointerHover: ${details.localPosition}');
        },
        child: CircleAvatar(
          radius: width / 2,
          backgroundColor: Colors.black12,
          child: Container(),
        ),
      ),
    );
```

In that sample I use a gray circle, but the behavior is still the same. I get no calls when I pressed the mouse button outside of the gray circle. I read this time more careful the documentation, but I interpret it in that way that it should work with `Listener` but it doesn't.

**Comment by timmaffett** [comment] 2023-04-30 21:12
I believe that you will have to capture and track the `onPointerMove` events from the same widget/listener that captured the `onPointerDown` event.  Ie. whereever the mouse down even is happening is where you are going to need to track the mouse move as well.  When the mouse down even happens than *that* widget/listener becomes the 'owner' of the mouse move events.

Here is a dartpad which illustrates this:
https://dartpad.dev/?channel=old&id=8ced42a5d3d90fa549adb75bcfc4ef45

the dartpad has the code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: Colors.blueGrey,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Listener(
        onPointerDown: (details) {
          print('OUTER onPointerDown: ${details.localPosition}');
        },
        onPointerMove: (details) {
          print('OUTER onPointerMove: ${details.localPosition}');
        },
        // console too noisy with onPointHover on outer also..
        //onPointerHover: (details) {
        //  print('OUTER onPointerHover: ${details.localPosition}');
        //},
        child: Column( children: 
          [
            Expanded( child:
              Container( 
                color: Colors.blue,
                child:
                  Center(
                    child: MyWidget(),
                  ),
                ),
              ),
           ],
          ),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    const width = 240.0;
    return Center(
      child: Listener(
        onPointerDown: (details) {
          print('onPointerDown: ${details.localPosition}');
        },
        onPointerMove: (details) {
          print('onPointerMove: ${details.localPosition}');
        },
        onPointerHover: (details) {
          print('onPointerHover: ${details.localPosition}');
        },
        child: CircleAvatar(
          radius: width / 2,
          backgroundColor: Colors.black12,
          child: Container(),
        ),
      ),
    );
  }
}
```

**Comment by danagbemava-nc** [comment] 2023-05-02 08:53
Hi @rekire, does the code sample in https://github.com/flutter/flutter/issues/125763#issuecomment-1529140550 work for you?

**Comment by timmaffett** [comment] 2023-05-02 15:06
Strictly speaking the code sample does not 'work' for what @rekire originally reported because that is not how events work within the flutter widgets.  The code sample is meant to help illustrate how they do work, and give @rekire ideas how he might accomplish what he needs with event handlers in *both* the outside widget and the 'inner' widget.
  @rekire never described exactly what he was trying to accomplish in the first place, so it was not possible to provide an example of that.  (well other than synthesizing onHoverEvents while the mouse button is down, but the onMouseMove events  in the sample code will hopefully give him ideas on how to achieve what he needs.. that is what I was intending)

**Comment by rekire** [comment] 2023-05-02 18:38
Well yes I can observe the mouse events with `Listener`, but that was not really what I expected. Using the listener is very lowlevel out of my view.

My original intent was to implement an edge swipe for wear os, since there is no edge on desktop I wanted to simulate the edge swipe by crossing the widget bounds. With the `Listener` class I got the first steps managed.

Anyway even the fact that it is working as "intended" based on the documentation it feels strange that mouse events are filtered in such a way.

My actual problem is solved, but the current API feels wrong IMHO

**Comment by danagbemava-nc** [comment] 2023-05-03 06:28
@timmaffett thanks for the insight. 

@rekire please feel free to file proposals/issues on how you think the API can be improved. 

Given that the original issue has been resolved, I will be closing this issue. 

Thank you

**Closed by danagbemava-nc** 2023-05-03 06:28 UTC
Labels: in triage

**Comment by rekire** [comment] 2023-05-03 06:36
@danagbemava-nc to be honest I stick to this ticket. I still think that it should work as I expected it intially.

My issue was that it doesn't work when the mouse button is pressed. The documentation says something else, so my issue is not a bug instead it is a change request. The only change is that the current behavior is expected and not a bug
