### ISSUE TITLE
Getting "Unhandled Exception: type 'int' is not a subtype of type 'String?' in type cast" at runtime 

### ISSUE THREAD

**Issue by luvsingh1993** [flutter/flutter#90655] opened 2021-09-24 05:29 UTC
## Steps to Reproduce

1. install version 1.0.8
2. code
```
ProductDetailsResponse productDetailResponse =
await _inAppPurchase.queryProductDetails(_kProductIds.toSet());
  if (productDetailResponse.error != null) {
      setState(() {
        _queryProductError = productDetailResponse.error.message;
        _isAvailable = isAvailable;
        _products = productDetailResponse.productDetails;
        _purchases = [];
        _notFoundIds = productDetailResponse.notFoundIDs;
        _consumables = [];
        _purchasePending = false;
        _loading = false;
      });
      return;
    }
```

## Logs

```
Unhandled Exception: type 'int' is not a subtype of type 'String?' in type cast
E/flutter ( 3808): #0      _$SkuDetailsWrapperFromJson (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.g.dart:15:47)
E/flutter ( 3808): #1      new SkuDetailsWrapper.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.dart:56:7)
E/flutter ( 3808): #2      _$SkuDetailsResponseWrapperFromJson.<anonymous closure> (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.g.dart:59:35)
E/flutter ( 3808): #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter ( 3808): #4      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter ( 3808): #5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter ( 3808): #6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter ( 3808): #7      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter ( 3808): #8      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter ( 3808): #9      _$SkuDetailsResponseWrapperFromJson (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.g.dart:60:14)
E/flutter ( 3808): #10     new SkuDetailsResponseWrapper.fromJson (package:in_app_purchase_android/src/billing_client_wrappers/sku_details_wrapper.dart:182:7)
E/flutter ( 3808): #11     BillingClient.querySkuDetails (package:in_app_purchase_android/src/billing_client_wrappers/billing_client_wrapper.dart:146:38)
```

**Comment by danagbemava-nc** [comment] 2021-09-24 09:17
Hi @luvsingh1993 , this is a duplicate of #90509. 

Kindly see https://github.com/flutter/flutter/issues/90244#issuecomment-924678704 for a quick fix. 

Kindly follow up there for updates.

Closing from here.

**Closed by danagbemava-nc** 2021-09-24 09:17 UTC
Labels: in triage
