### ISSUE TITLE
"getTextBeforeCursor on inactive InputConnection" warning when clearing text field using TextEditingController.

### ISSUE THREAD

**Issue by anarchyrucks** [flutter/flutter#11321] opened 2017-07-20 16:21 UTC
## Steps to Reproduce
When input to the text field is submitted,  the warning is generated.
The problem seems to be is with `controller.clear()`.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Text> _list = [];
  TextEditingController controller = new TextEditingController();

  void _addToList(inputText) {
    setState(() {
      _list.add(inputText);
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        backgroundColor: Colors.redAccent,
        title: new Text("Home"),
      ),
      body: new Center(
        child: new Column(
          children: <Widget>[
            new TextField(
              controller: controller,
              onSubmitted: (String inputText) {
                _addToList(new Text(inputText));
                controller.clear();
              },
            ),
            new Column(
              children: _list,
            ),
          ],
        ),
      ),
    );
  }
}
```

## Logs

`W/IInputConnectionWrapper(12446): getTextBeforeCursor on inactive InputConnection`

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G16b, locale en-GB, channel alpha)
    • Flutter at /Users/anarchyrucks/flutter
    • Framework revision d36e2f6191 (4 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/anarchyrucks/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] Connected devices
    • A0001 • 96234dd • android-arm • Android 7.1.2 (API 25)
```

**Comment by Y0hy0h** [comment] 2017-12-04 14:38
I encountered this warning in my app as well and investigated it. It does not seem to be an issue with `controller.clear()`, but instead is correlated with the keyboard being open.

I've modified the sample by @anarchyrucks to also include a button that "submits" the text (code below). If I use either the keyboard's submit button, or the added UI button *while the keyboard is opened* to process the TextInput, then I get the mentioned error message twice:
```
W/IInputConnectionWrapper( 4264): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4264): getTextBeforeCursor on inactive InputConnection
```
If however I close the keyboard and then press the button, *no* warning appears.

In a [related StackOverflow discussion](https://stackoverflow.com/questions/8122625/getextractedtext-on-inactive-inputconnection-warning-on-android) on this problem in Android are some mentions of keyboard and focus issues which led me to the above discovery. Unfortunately, there does not seem to be an explanation of what is really going on.

*Code I used to test this, modified from @anarchyrucks's version:*
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Text> _list = [];
  TextEditingController controller = new TextEditingController();

  void _addToList(Text inputText) {
    setState(() {
      _list.add(inputText);
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        backgroundColor: Colors.redAccent,
        title: new Text("Home"),
      ),
      body: new Center(
        child: new Column(
          children: <Widget>[
            new TextField(
              controller: controller,
              onSubmitted: (String inputText) {
                _addToList(new Text(inputText));
                controller.clear();
              },
            ),
            new IconButton(icon: new Icon(Icons.add), onPressed: () {
              _addToList(new Text(this.controller.text));
              controller.clear();
            }),
            new Column(
              children: _list,
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by Y0hy0h** [comment] 2018-01-06 13:48
I have come across a [StackOverflow answer](https://stackoverflow.com/a/9643981/3287963) stating that `inactive InputConntection`s can occur when the connection wasn't closed using `connection.close()`.

As stated by @anarchyrucks, the errors only show if `controller.clear()` is called. If it is left out, no messages appear, regardless of whether you're using the button or the keyboard to submit.

**Comment by raffomania** [comment] 2018-08-11 12:38
I get this when using a `TextFormField` with `autofocus: true` and then setting `.text` to a value on my controller. When disabling `autofocus: true`, the warnings disappear.

**Comment by tkshnwesper** [comment] 2018-08-13 16:00
I get this even with `autofocus: false`. But with that, the warning appears after I move between different `TextFormField`s in my form 3 or 4 times whereas with autofocus enabled, it appears when I click on a `TextFormField` once.

**Comment by tkshnwesper** [comment] 2018-08-14 19:14
Oh my goodness, folks! I managed to resolve the issue while trying to fix something else.

Read the contents of this [link](https://flutter.io/cookbook/forms/validation/) carefully. It fixed everything for me. 🎉

**Comment by tkshnwesper** [comment] 2018-08-14 20:15
I never actually had to clear the text in the text field like in the example above within my application. In my application I had multiple text fields with different keyboard types and toggling between them caused the warning to come up. I was able to resolve that issue with the help of the link I posted above.

I was just looking into how to resolve @Y0hy0h 's example using something similar. But it seems like there might be a bug because no matter what I try, the warning pops up.

**Comment by tkshnwesper** [comment] 2018-08-15 05:31
So I decided to take one last shot at this. I added the text field clearing logic to my code and guess what! I got no warning! 🎉 

Here's my code, knock yourselves out 🍺 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:kanjuice_app/misc/screen_dimensions.dart';

class RegisterRoute extends MaterialPageRoute {
  RegisterRoute() : super(builder: (BuildContext context) => _RegisterWidget());
}

class _RegisterWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _RegisterWidgetState();
}

class _RegisterWidgetState extends State<_RegisterWidget> {
  final TextEditingController _employeeIdController = TextEditingController();
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _internalNumberController =
      TextEditingController();

  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    final dimensions = ScreenDimensions(context);
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      appBar: AppBar(title: Text("Register")),
      body: Container(
        margin: EdgeInsets.symmetric(
            horizontal: dimensions.width * 0.05,
            vertical: dimensions.height * 0.03),
        child: Column(
          children: <Widget>[
            Expanded(
                child: Form(
                    key: _formKey,
                    autovalidate: true,
                    child: Column(
                      children: <Widget>[
                        _FormFieldContainer(
                            "Employee ID",
                            [WhitelistingTextInputFormatter.digitsOnly],
                            "Can contain only digits",
                            _employeeIdController,
                            TextInputType.number),
                        _FormFieldContainer(
                            "Name",
                            [BlacklistingTextInputFormatter(RegExp("^[ ]*\$"))],
                            "Cannot be empty",
                            _nameController,
                            TextInputType.text),
                        Container(
                          padding:
                              EdgeInsets.only(top: dimensions.height * 0.05),
                          child: Column(
                            children: <Widget>[
                              Text(
                                  "Please swipe your ID card in order"
                                  " to fill in the below field",
                                  style: TextStyle(
                                      fontSize: dimensions.height * 0.03,
                                      fontWeight: FontWeight.bold)),
                              _FormFieldContainer(
                                  "Internal Number",
                                  [WhitelistingTextInputFormatter.digitsOnly],
                                  "Cannot be empty and may consist"
                                  " only of digits",
                                  _internalNumberController,
                                  TextInputType.number)
                            ],
                          ),
                        )
                      ],
                    ))),
            Container(
              height: dimensions.height * 0.15,
              child: SizedBox.expand(
                child: RaisedButton(
                    color: Colors.deepPurple,
                    onPressed: () {
                      if (_formKey.currentState.validate()) {}
                      _employeeIdController.text = '';
                      _nameController.text = '';
                      _internalNumberController.text = '';
                    },
                    padding: EdgeInsets.symmetric(
                        vertical: dimensions.height * 0.01,
                        horizontal: dimensions.width * 0.01),
                    child: Text(
                      "Complete Registration",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                          fontSize: dimensions.height * 0.04,
                          color: Colors.white),
                    )),
              ),
            )
          ],
        ),
      ),
    );
  }
}

class _FormFieldContainer extends StatelessWidget {
  final String _labelText;
  final Iterable<TextInputFormatter> _inputFormatters;
  final String _invalidInputMessage;
  final TextEditingController _controller;
  final bool _enabled;
  final TextInputType _inputType;

  @override
  Widget build(BuildContext context) {
    final dimensions = ScreenDimensions(context);
    return Container(
      child: Column(
        children: <Widget>[
          TextFormField(
              autofocus: true,
              enabled: _enabled,
              controller: _controller,
              style: TextStyle(
                  fontSize: dimensions.height * 0.05, color: Colors.black),
              autovalidate: false,
              inputFormatters: _inputFormatters,
              validator: (String value) =>
                  value.isEmpty ? _invalidInputMessage : null,
              keyboardType: _inputType,
              decoration: InputDecoration(labelText: _labelText))
        ],
      ),
    );
  }

  _FormFieldContainer(this._labelText, this._inputFormatters,
      this._invalidInputMessage, this._controller, this._inputType,
      [this._enabled = true]);
}
```

**Comment by AoraMD** [comment] 2019-03-06 02:04
Same problem here. I found that the problem has arisen only textfield is in a StatelessWidget. it never happens when in a stateful one.

**Comment by goderbauer** [comment] 2019-06-18 22:35
Dupe of https://github.com/flutter/flutter/issues/9471.

**Closed by goderbauer** 2019-06-18 22:35 UTC
Labels: a: text input, framework, ▣ platform-android

**Comment by amit-onappr** [comment] 2019-10-16 06:37
> bloc

In case if you are using bloc design pattern and setting text property of controller insight build method. 
`  if (state is LoginRecheckMobileState) {
        _mobileNumberController.text = state.mobile;
      }
`

Workaround to this problem is to use 
`@override
  void didChangeDependencies() {
    final _authBloc = BlocProvider.of<LoginBloc>(context);
    if (_authBloc.currentState is LoginRecheckMobileState) {
      _mobileNumberController.text = _authBloc.currentState.mobile;
    }`

**Comment by Shamim18** [comment] 2019-11-26 07:51
i have same problem, 
**My Task**
i want to clear my textfield on button click 

here is my code
```
String searchData = "";
 TextEditingController searchEditor = TextEditingController();

            Row(
                children: <Widget>[
                  Expanded(
                    child: TextField(  // My textbox
                      controller: searchEditor,
                      autofocus: false,
                      onChanged: (str){
                        searchData = (str == null)? "" : str;
                        setState(() {
                        });
                      },
                      decoration: InputDecoration(
                        prefixIcon: IconTheme(
                          child: Icon(Icons.search),
                          data: IconThemeData(color: Colors.blueAccent),
                        ),
                        labelText: 'Search',
                      ),
                    ),
                    flex: 8,
                  ),
                  Expanded(
                    child: RaisedButton(
                      color: Basic.hbColor,
                      textColor: Colors.white,
                      child: Icon(Icons.clear),
                      onPressed: (){      // On button click
                        FocusScope.of(context).unfocus();   // Close keyboard
                        setState(() {
                          searchData = "";
                        });
                        Future.delayed(Duration(microseconds: 500),(){   //call back after 500  microseconds
                          searchEditor.clear();  // clear textfield 
                        });
                      },
                      elevation: 10,
                    ),
                    flex: 2,
                  )
                ],
              )
```

i solved by **USING  'searchEditor.clear();'   inside Future.delayed**
Because when we call  **FocusScope.of(context).unfocus();** for closing keyboard it take some microseconds for close that's why it show this **WANRING** 
i.e. `getTextBeforeCursor on inactive InputConnection`
to overcome i called searchEditor.clear(); method after some microseconds 

**it's work for me.**
**By the way it is not a BUG**

**Comment by MartinBergerDX** [comment] 2019-12-05 12:15
I my case, in a project totally unrelated to yours, these warnings appears when keyboard obscures ListView whose rows contains EditText.

**Comment by rasulbc** [comment] 2020-02-16 14:21
> So I decided to take one last shot at this. I added the text field clearing logic to my code and guess what! I got no warning! 🎉
> 
> Here's my code, knock yourselves out 🍺
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> import 'package:kanjuice_app/misc/screen_dimensions.dart';
> 
> class RegisterRoute extends MaterialPageRoute {
>   RegisterRoute() : super(builder: (BuildContext context) => _RegisterWidget());
> }
> 
> class _RegisterWidget extends StatefulWidget {
>   @override
>   State<StatefulWidget> createState() => _RegisterWidgetState();
> }
> 
> class _RegisterWidgetState extends State<_RegisterWidget> {
>   final TextEditingController _employeeIdController = TextEditingController();
>   final TextEditingController _nameController = TextEditingController();
>   final TextEditingController _internalNumberController =
>       TextEditingController();
> 
>   final _formKey = GlobalKey<FormState>();
> 
>   @override
>   Widget build(BuildContext context) {
>     final dimensions = ScreenDimensions(context);
>     return Scaffold(
>       resizeToAvoidBottomPadding: false,
>       appBar: AppBar(title: Text("Register")),
>       body: Container(
>         margin: EdgeInsets.symmetric(
>             horizontal: dimensions.width * 0.05,
>             vertical: dimensions.height * 0.03),
>         child: Column(
>           children: <Widget>[
>             Expanded(
>                 child: Form(
>                     key: _formKey,
>                     autovalidate: true,
>                     child: Column(
>                       children: <Widget>[
>                         _FormFieldContainer(
>                             "Employee ID",
>                             [WhitelistingTextInputFormatter.digitsOnly],
>                             "Can contain only digits",
>                             _employeeIdController,
>                             TextInputType.number),
>                         _FormFieldContainer(
>                             "Name",
>                             [BlacklistingTextInputFormatter(RegExp("^[ ]*\$"))],
>                             "Cannot be empty",
>                             _nameController,
>                             TextInputType.text),
>                         Container(
>                           padding:
>                               EdgeInsets.only(top: dimensions.height * 0.05),
>                           child: Column(
>                             children: <Widget>[
>                               Text(
>                                   "Please swipe your ID card in order"
>                                   " to fill in the below field",
>                                   style: TextStyle(
>                                       fontSize: dimensions.height * 0.03,
>                                       fontWeight: FontWeight.bold)),
>                               _FormFieldContainer(
>                                   "Internal Number",
>                                   [WhitelistingTextInputFormatter.digitsOnly],
>                                   "Cannot be empty and may consist"
>                                   " only of digits",
>                                   _internalNumberController,
>                                   TextInputType.number)
>                             ],
>                           ),
>                         )
>                       ],
>                     ))),
>             Container(
>               height: dimensions.height * 0.15,
>               child: SizedBox.expand(
>                 child: RaisedButton(
>                     color: Colors.deepPurple,
>                     onPressed: () {
>                       if (_formKey.currentState.validate()) {}
>                       _employeeIdController.text = '';
>                       _nameController.text = '';
>                       _internalNumberController.text = '';
>                     },
>                     padding: EdgeInsets.symmetric(
>                         vertical: dimensions.height * 0.01,
>                         horizontal: dimensions.width * 0.01),
>                     child: Text(
>                       "Complete Registration",
>                       textAlign: TextAlign.center,
>                       style: TextStyle(
>                           fontSize: dimensions.height * 0.04,
>                           color: Colors.white),
>                     )),
>               ),
>             )
>           ],
>         ),
>       ),
>     );
>   }
> }
> 
> class _FormFieldContainer extends StatelessWidget {
>   final String _labelText;
>   final Iterable<TextInputFormatter> _inputFormatters;
>   final String _invalidInputMessage;
>   final TextEditingController _controller;
>   final bool _enabled;
>   final TextInputType _inputType;
> 
>   @override
>   Widget build(BuildContext context) {
>     final dimensions = ScreenDimensions(context);
>     return Container(
>       child: Column(
>         children: <Widget>[
>           TextFormField(
>               autofocus: true,
>               enabled: _enabled,
>               controller: _controller,
>               style: TextStyle(
>                   fontSize: dimensions.height * 0.05, color: Colors.black),
>               autovalidate: false,
>               inputFormatters: _inputFormatters,
>               validator: (String value) =>
>                   value.isEmpty ? _invalidInputMessage : null,
>               keyboardType: _inputType,
>               decoration: InputDecoration(labelText: _labelText))
>         ],
>       ),
>     );
>   }
> 
>   _FormFieldContainer(this._labelText, this._inputFormatters,
>       this._invalidInputMessage, this._controller, this._inputType,
>       [this._enabled = true]);
> }
> ```

I believe your problem occurs because your code calculates the dimensions every time when the widget rebuilds. When the TextFieldForm is tapped the keyboard pops up, the heigh

**Comment by BabkenM** [comment] 2020-03-27 10:45
> i have same problem,
> **My Task**
> i want to clear my textfield on button click
> 
> here is my code
> 
> ```
> String searchData = "";
>  TextEditingController searchEditor = TextEditingController();
> 
>             Row(
>                 children: <Widget>[
>                   Expanded(
>                     child: TextField(  // My textbox
>                       controller: searchEditor,
>                       autofocus: false,
>                       onChanged: (str){
>                         searchData = (str == null)? "" : str;
>                         setState(() {
>                         });
>                       },
>                       decoration: InputDecoration(
>                         prefixIcon: IconTheme(
>                           child: Icon(Icons.search),
>                           data: IconThemeData(color: Colors.blueAccent),
>                         ),
>                         labelText: 'Search',
>                       ),
>                     ),
>                     flex: 8,
>                   ),
>                   Expanded(
>                     child: RaisedButton(
>                       color: Basic.hbColor,
>                       textColor: Colors.white,
>                       child: Icon(Icons.clear),
>                       onPressed: (){      // On button click
>                         FocusScope.of(context).unfocus();   // Close keyboard
>                         setState(() {
>                           searchData = "";
>                         });
>                         Future.delayed(Duration(microseconds: 500),(){   //call back after 500  microseconds
>                           searchEditor.clear();  // clear textfield 
>                         });
>                       },
>                       elevation: 10,
>                     ),
>                     flex: 2,
>                   )
>                 ],
>               )
> ```
> 
> i solved by **USING 'searchEditor.clear();' inside Future.delayed**
> Because when we call **FocusScope.of(context).unfocus();** for closing keyboard it take some microseconds for close that's why it show this **WANRING**
> i.e. `getTextBeforeCursor on inactive InputConnection`
> to overcome i called searchEditor.clear(); method after some microseconds
> 
> **it's work for me.**
> **By the way it is not a BUG**

Thank you a lot. I spent a lot of weeks to resolve this issue. BTW this not happening on stable channel , for me it only happens on master.
clearing every time the TextField ( and no matter if this is a TextField or TextFormField) helped me.
I tried every thing with GlobalKeys , StatelesWidget , Statefulwidget but no result.
Solution for me was clearing TextField value with TextEditingController every time when I'm unfocusing the TextField and closing the keyboard, I used the clearing method in 
 GestureDetector's onTap callback.

**Comment by DipakShrestha-ADS** [comment] 2020-04-07 13:30
just change your flutter channel to stable.. .... just garbage the master channel, it took my whole day.
