### ISSUE TITLE
[DO NOT CLOSE][WEB] Text is not selectable by default on the web

### ISSUE THREAD

**Issue by AmethystLiang** [flutter/flutter#74881] opened 2021-01-28 08:01 UTC
Most website texts are selectable. Flutter should support web texts to be selectable **by default** too. 

This issue was supported by many developers (see #32246 and #74871) but always got closed by admins. 

Admins recommend using SelectableTextWidget instead. Do you expect us to wrap EVERY SINGLE TEXT on our application with SelectableTextWidget? 

Why is it not on your team's high priority list to support web selectable text BY DEFAULT given it bothers so many developers and the current behavior goes against web standard?

**Comment by iapicca** [comment] 2021-01-28 08:35
@AmethystLiang 

> Most website texts are selectable. Flutter should support web texts to be selectable **by default** too.

I believe consistency between platforms is paramount, a class behavior changing according to the platform
seems very **_disadvantageous_** to me

> . Do you expect us to wrap EVERY SINGLE TEXT on our application with SelectableTextWidget?

you don't wrap a `Text` in `SelectableText`, but rather you create a [SelectableText class](https://api.flutter.dev/flutter/material/SelectableText-class.html) using a `String`
in the same exact way you create a [Text class](https://api.flutter.dev/flutter/dart-html/Text-class.html)

what issues , annoyance or disadvantages are you experiencing using [SelectableText](https://api.flutter.dev/flutter/material/SelectableText-class.html) over [Text](https://api.flutter.dev/flutter/dart-html/Text-class.html)?

> [...] the current behavior goes against web standard? 

can you provide any reference to support such a claim

**Comment by pedromassangocode** [comment] 2021-01-28 09:19
This is a duplicate of https://github.com/flutter/flutter/issues/74871.

As mentioned in the comment above and in https://github.com/flutter/flutter/issues/32246#issuecomment-546485253, please use SelectableText widget if you want your text to be selectable.



> ```dart
> import 'package:flutter/foundation.dart' show kIsWeb;
> import 'package:flutter/material.dart';
> 
> class CustomText extends StatelessWidget {
>   const CustomText(this.data, {Key key}) : super(key: key);
>   final String data;
>   @override
>   Widget build(BuildContext context) =>
>       kIsWeb ? SelectableText(data) : Text(data);
> }
> ```

This is such a good example in how you can make a custom widget that will behave differently on Web and other platforms.

**Closed by pedromassangocode** 2021-01-28 09:19 UTC
