### ISSUE TITLE
 Error: Not found: 'dart:js'              import 'dart:js';

### ISSUE THREAD

**Issue by abdinur99** [flutter/flutter#70373] opened 2020-11-12 11:25 UTC
```
lib/models/task.dart:1:8: Error: Not found: 'dart:js'
import 'dart:js';
       ^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs; message=StandardFileSystem only supports file:* and data:* URIs)
#0      St
andardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:657:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:825:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:572:15)
<asynchronous suspension>
#4      _FlutterFrontendC
ompiler.compile (package:flutter_frontend_server/server.dart:43:22)
#5      starter (package:flutter_frontend_server/server.dart:182:2      
7)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:9:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart
:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)



FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
```

**Comment by hello-addweb** [comment] 2020-11-12 12:16
Please check [this](https://stackoverflow.com/questions/59479813/error-not-found-dartjs-import-dartjs).

Similar issue reported there.

**Comment by darshankawar** [comment] 2020-11-12 13:06
@abdinur99 
Can you provide `flutter doctor -v` and minimal reproducible code sample ?

**Comment by darshankawar** [comment] 2020-11-12 13:06
Related issues:

https://github.com/flutter/flutter/issues/52763
https://github.com/dart-lang/sdk/issues/36481

**Comment by pedromassangocode** [comment] 2020-12-04 09:23
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-04 09:23 UTC
Labels: in triage, waiting for customer response

**Comment by tomgilder** [comment] 2020-12-04 13:14
This happened for me when trying to use the `js` package from a Flutter project. I needed to use it for interop when compiling for Web, but I got this error when compiling for iOS and Android as the js package isn't supported.

In this case, the solution is to use conditional, see for example https://stackoverflow.com/a/61921960 

It would be nice if there was a more friendly error from the compiler.

**Comment by aqeelshamz** [comment] 2020-12-05 12:29
Go to your flutter installed directory/.pub-cache/hosted/pub.dartlang.org/js-0.6.3-nullsafety.1/lib/js.dart

Delete or comment this line:

`export 'dart:js' show allowInterop, allowInteropCaptureThis;`
Then try again

**Comment by mikeesouth** [comment] 2021-01-11 16:27
Does anyone have a more permanent solution for this? I'm building a web app and I'm using a library (printing) that imports `js: js-0.6.3-nullsafety.3`. My runs fine in web (both localhost and published) but my flutter widget tests fails due to the above error about dart:js missing, my error message is:
```
./../../../flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.3-nullsafety.3/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
```

This is a pure web application so I cant use conditionals to get flutter test working.

I can circumvent this by commenting/removing the line according to the post from @aqeelshamz but that is a highly temporary solution for me. I also have build agents that run into this problem and I dont want to add a script that removes this line in the automatic build pipeline.

**Comment by zouchengli** [comment] 2021-07-21 06:06
IDE Search 

"import import 'dart:js';"  

Delete or comment this line!

**Comment by cedvdb** [comment] 2021-08-07 17:41
I've this error while running tests too and the IDE does not find that line "import 'dart:js';" (nor export)

```
Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis; 
```
