### ISSUE TITLE
No LUCI tests triggered from some PRs

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#78466] opened 2021-03-17 21:16 UTC
See https://github.com/flutter/flutter/pull/78386/checks?sha=7f55aff74ba37f3d502a1ab920cbb424b6df6dd3
I was expecting to see a new build in https://ci.chromium.org/p/flutter/builders/try/Windows%20web_tool_tests?limit=50 since that PR enabled it, so maybe they aren't being triggered?

**Comment by keyonghan** [comment] 2021-03-17 21:27
This is a duplicate of https://github.com/flutter/flutter/issues/74611, and I will work on that issue with a higher priority.

@yusufm Do you mind re-trigger LUCI builds in that PR? Once triggered, we can close this one.

**Comment by keyonghan** [comment] 2021-03-17 21:33
builders have been triggered by rebasing. Closing this one and will keep track of https://github.com/flutter/flutter/issues/74611

**Closed by keyonghan** 2021-03-17 21:33 UTC
Labels: P2, team, team: infra
