### ISSUE TITLE
Android Studio complains of missing flutter.iml for Existing app projects

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#31806] opened 2019-04-29 21:09 UTC
When following the instructions here: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
Android studio complains about the .android/Flutter/flutter.iml file missing when opening the existing Android app project, however, the file is indeed there, and the flutter project does appear in the Projects pane and can be navigated. I don't know if this is an Android Studio bug or a Flutter bug. Maybe the fact that the file is in a path that contains a hidden directory (.android)?

![android_studio_flutter_error](https://user-images.githubusercontent.com/40898687/56927212-9b579d00-6aa1-11e9-9152-584f2d53d75b.png)

**Comment by matthew-carroll** [comment] 2019-05-01 20:49
@devoncarew do you have someone who could take a look at this?

**Comment by devoncarew** [comment] 2019-05-01 23:33
From the error, it looks like a `.iml` is likely referenced in the metadata generated by flutter create, but that iml file doesn't exist.

Matt, do you know what template this is? It likely needs to be updated or corrected.

**Comment by matthew-carroll** [comment] 2019-05-01 23:41
@dannyvalentesonos can you comment as to which Flutter template you started with? Was it the module template? And was the project created recently?

**Comment by dannyvalentesonos** [comment] 2019-05-02 01:28
@matthew-carroll We created the module using **flutter create -t module ...**. The module was created with a version of Flutter around 0.9.
However, that error in the screenshot is taken from opening our existing application's project, and its .idea/modules.xml file contains an entry for **.../flutter_module/.android/Flutter/flutter.iml** which does indeed exist.
That file is generated by running **flutter build bundle** from within the flutter_module directory.
The reason that entry is there is because of the dependency on the include_flutter.groovy file that we've added in our settings.gradle file as described in the Add2App documentation.

**Comment by dannyvalentesonos** [comment] 2019-05-02 01:34
I've just looked at the .idea/modules.xml file for our existing project, and I had 2 identical entries:
**<module fileurl="file://$PROJECT_DIR$/../../flutter_module/.android/Flutter/flutter.iml" filepath="$PROJECT_DIR$/../../flutter_module/.android/Flutter/flutter.iml" />
<module fileurl="file://$PROJECT_DIR$/../../flutter_module/.android/Flutter/flutter.iml" filepath="$PROJECT_DIR$/../../flutter_module/.android/Flutter/flutter.iml" />**

Interestingly enough, I removed both entries, and re-opened the project, and now everything seems good. I will see if I can find a way to get it back into this bad state.

**Comment by dannyvalentesonos** [comment] 2019-05-02 01:53
I found how to repro.
Simply delete the build directory in the flutter module, and then run **flutter build bundle** to get it generated again.
Next time you open the existing app's project, Android Studio adds a second identical entry in there and gives the error I pasted above. The alert doesn't pop up automatically by the way. It's an error in the Event Log that pops up at the bottom right of the window.

**Comment by dannyvalentesonos** [comment] 2019-05-02 01:54
I can also mention that selecting **Yes** on that alert sucessfully removes only one of those entries, and gets everything work well again.

**Comment by matthew-carroll** [comment] 2019-05-02 02:59
@devoncarew does @dannyvalentesonos's info help narrow down the possible causes? Do you think this is likely an IDE issue, or do you think it could be some kind of Gradle or Flutter tool issue?

**Comment by matthew-carroll** [comment] 2019-05-14 20:19
@devoncarew did you get a chance to look at the supplied info?

**Comment by dannyvalentesonos** [comment] 2019-05-29 18:20
Thank you @matthew-carroll for following up on this. Is there any new update?

**Comment by xster** [comment] 2019-07-19 01:54
@stevemessick I run into this frequently while testing too. I'm not 100 sure how to repro it but it might have something to do with running flutter packages get in the flutter module while the outer app is opened.

**Comment by stevemessick** [comment] 2019-07-22 20:46
@xster I added a fix for this problem to #36486. The issue is that the Flutter module embedded in the  Android support needs a `flutter.iml` file to exist at all times. If the `.android` directory was re-created by flutter_tools it did not regenerate that file.

**Closed** 2019-08-01 22:47 UTC
Labels: a: existing-apps, customer: amplify, ▣ platform-android
