### ISSUE TITLE
AppBar managing SystemUIOverlayStyle in build() can be confusing

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#11638] opened 2017-08-16 16:14 UTC
`AppBar` sets the system UI color in its [`build()` method](https://github.com/flutter/flutter/blob/94ed7dce41d61a898f9b0eb7e38104045777ffb2/packages/flutter/lib/src/material/app_bar.dart#L334). This is not great because `build()` methods can be called at unpredictable times and so once an `AppBar` is visible the behavior of `setSystemUIOverlayStyle` is unpredictable. It can pose a problem for devs who aren't using `AppBar` in every modal route of their app, because they have to manage the system UI state manually with a `NavigatorObserver` and fight with the `AppBar` also setting the brightness.

## Steps to Reproduce

- Build an app that has a main route that has no `AppBar`.
- Set the initial system UI brightness with `setSystemUIOverlayStyle`.
- Push modal routes onto the Navigator stack that do have an `AppBar`.
- `setSystemUIOverlayStyle` now behaves unpredictably and may be overwritten by the `AppBar`'s preferred value at unspecified times.
- Once the route with the `AppBar` is popped, the system UI brightness is not automatically restored to its previous value. The developer has to set it again.

Here are some possible solutions:

1. Instead of setting the brightness in the `build()` method of `AppBar`, the `Navigator` could manage the system UI brightness based on the brightness of visible routes in the navigator stack (which would default to using values from the `Theme` wrapping the `Navigator` is). The `Navigator` would be responsible for restoring it to the previous value.
1. We could provide a widget that knows how to set the system UI brightness when it is visible and restore the previous value when it is not. This widget could be used by `AppBar` as well as other widgets that want to set the system UI brightness.

/cc @xster @Hixie

**Comment by Hixie** [comment] 2017-08-16 16:40
Dupe of https://github.com/flutter/flutter/issues/4630.

**Closed by Hixie** 2017-08-16 16:40 UTC
Labels: new feature, prod: framework
