### ISSUE TITLE
Flutter: Could not find com.android.tools.build:gradle:7.5.1

### ISSUE THREAD

**Issue by theSonGoku1991** [flutter/flutter#118316] opened 2023-01-11 13:27 UTC
Hello guys,

I keep and keep and keep running into the same issue(s) since several days.

I came back to code to my app, as I noticed, it does not start/run anymore, because I had a Java missmatch error.

To solve it, I had to (did not even know there is a new one) install Android Studio Flamingo (I am out for a few month and Android just releases a brand new Android Studio haha) which comes/supports Java 19.

Dunno why but the Gradle versions in my project kept and kept complaining, so I later found stackoverflow thread recommending to downgrade to Java 17 (which is a huge move from 19). So I did that, downgraded Gradle as well, because the latest Gradle version(s) dont run with Java 17.

Then, I kept getting the message "Could not find com.android.tools.build:gradle:X.X.X" (X.X.X stands for all the different versions I tried out). Updated/Upgraded all my dependencies as well.

In my last session yesterday, I just checked out those links which the terminal send me:
- https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.5.1/gradle-7.5.1.pom
- https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.5.1/gradle-7.5.1.pom
- https://jcenter.bintray.com/com/android/tools/build/gradle/7.5.1/gradle-7.5.1.pom
and noticed that all of them show 404 errors.

I also tried to download gradle with a VPN but it did not help neither.

I really do not know what else I could try and since I do not get a reply on stackoverflow, I try me luck here.

In case you need any further information (which you most likely need) feel free to ask.

Regards
Thomas

**Comment by huycozy** [comment] 2023-01-12 05:15
@theSonGoku1991 Can you share the output of `flutter doctor -v`? Also, are you setting the `X.X.X` as `7.5.1`? If so, can you retry with `7.3.1`?

Please also check [Update Gradle](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle) for using a compatible Gradle version corresponding with your Android Studio.

**Comment by theSonGoku1991** [comment] 2023-01-12 21:29
Hi @huycozy, thank you for your reply!

Here is my flutter doctor -v output:

`PS C:\Coding\nutritious> flutter run
Running "flutter pub get" in nutritious...
Resolving dependencies...
  intl 0.17.0 (0.18.0 available)
Got dependencies!
Using hardware rendering with device sdk gphone64 x86 64. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...

FAILURE: Build failed with an exception.

PS C:\Coding\nutritious> flutter doctor -v
[√] Flutter (Channel master, 3.7.0-17.0.pre.15, on Microsoft Windows [Version 10.0.19044.2364], locale de-DE)
    • Flutter version 3.7.0-17.0.pre.15 on channel master at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a6f17e697c (2 days ago), 2023-01-11 05:31:17 +0800
    • Engine revision 687e3cb0fb
    • Dart version 3.0.0 (build 3.0.0-105.0.dev)
    • DevTools version 2.20.0

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Goku\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Users\Goku\Downloads\android-studio-2022.1.1.18-windows\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.4.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.4.33110.190
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Users\Goku\Downloads\android-studio-2022.1.1.18-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.2)
    • Android Studio at C:\Users\Goku\Downloads\android-studio-2022.2.1.10-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\Goku\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19044.2364]

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.`

I set the x.x.x with 7.6 recently but I pretty much tried EVERY gradle version in combination with Android Studio and Android Studio Flamingo (and meanwhile Android Studio Electric (I do not even know the difference)) out there so far (everytime with the same problems). 

I just tried out Android Gradle Plugin Version 7.3 and Gradle Version 7.4 (as from your link) and ran into the same issue again.

`Could not find com.android.tools.build:gradle:7.3.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3/gradle-7.3.pom
  - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.3/gradle-7.3.pom
  - https://jcenter.bintray.com/com/android/tools/build/gradle/7.3/gradle-7.3.pom
Required by:
    project :
Add google Maven repository and sync project
Open File`

Just to confirm:
As far as I understood so far, there are several ways to upgrade gradle.
I can either go to Android Studio > Project Structure and change the gradle version here (which also changes the gradle version in the gradle files of the project) AND/OR I can go to the gradle wrapper file and edit the distributionUrl as well as the gradle version in the project gradle file. But BOTH does not seem to work for me.

Also, just to confirm, are we speaking about the "Android Gradle Plugin Version" or the "Gradle Version"?

What confuses me is, that these links ALWAYS point to 404 pages. No wunder it does not work. But where to get it otherwise?

On this stackoverflow post https://stackoverflow.com/questions/75074542/java-gradle-versions, Makoto said, the most recent gradle version of my artifact (I dunno what he meant with that) is 2.3 (at that point, there still were several entries on that page which for some reason do not exist anymore). I was always refering to this list of gradle distributions: https://services.gradle.org/distributions/

I am really looking forward to your reply(s). Since this issue occours, I can not work on my project anymore :/

**Comment by huycozy** [comment] 2023-01-13 04:45
@theSonGoku1991 

>Required by:
    project :
Add google Maven repository and sync project
Open File

It might be missing a repository on your `android/build.gradle`. Could you share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by theSonGoku1991** [comment] 2023-01-13 12:51
Hi @huycozy, hope I got you right, this is my androud/build.gradle file.

```

buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.6'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


```

I recently (while debugging and searching for the issue) replaced jcenter() with mavenCentral() because I red somewhere, jcenter() is outdated.

I unfortunately do not know where the difference between the root build.gradle and the other build.gradle files (androud/build.gradle etc.) is.

Hope this helps, otherwise feel free to ask for additional information.

**Comment by theSonGoku1991** [comment] 2023-01-15 12:47
I extended my dependencies section meanwhile

```
    repositories {
        mavenCentral()
        maven { url 'https://dl.google.com/dl/android/maven2' }
        maven { url "https://repo.spring.io/release" }
        maven { url "https://repository.jboss.org/maven2" }
        maven { url 'https://maven.google.com' }
        maven { url 'https://maven.fabric.io/public' }
        jcenter()
        google()
        google { url 'https://maven.google.com/web/index.html' }
    }
```

But I keep getting the same error message

```
Could not find com.android.tools.build:gradle:7.6.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.6/gradle-7.6.pom
  - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.6/gradle-7.6.pom
  - https://repo.spring.io/release/com/android/tools/build/gradle/7.6/gradle-7.6.pom
  - https://repository.jboss.org/maven2/com/android/tools/build/gradle/7.6/gradle-7.6.pom
  - https://maven.google.com/com/android/tools/build/gradle/7.6/gradle-7.6.pom
  - https://maven.fabric.io/public/com/android/tools/build/gradle/7.6/gradle-7.6.pom
  - https://jcenter.bintray.com/com/android/tools/build/gradle/7.6/gradle-7.6.pom
  - https://maven.google.com/web/index.html/com/android/tools/build/gradle/7.6/gradle-7.6.pom
Required by:
    project :
Add google Maven repository and sync project
Open File
```

**Comment by huycozy** [comment] 2023-01-16 03:03
@theSonGoku1991 
Below is my `android/build.gradle` file content that is working normally on `Android Studio Dolphin | 2021.3.1`. 

<details>
<summary>My android/build.gradle</summary>

```gradle
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
</details>

I'm not sure whether this issue is caused by Android Studio or not, so can you retry on Visual Studio as well? 

Also, please check if the issue is also happening on a new Flutter default project (counter app) to make sure your change does not cause the issue.

**Comment by theSonGoku1991** [comment] 2023-01-16 15:54
@huycozy

I tried it out in Android Studio and Visual Studio Code simultaneously the entire time.

I just created a brand new Flutter project and was able to build/launch it in the emulator.

**Comment by huycozy** [comment] 2023-01-17 04:17
>I just created a brand new Flutter project and was able to build/launch it in the emulator.

@theSonGoku1991 As it's working normally on a new Flutter project, please double-check your modification on the old project. 

Closing this issue from here as it's not Flutter issue itself. If you disagree please write in the comments and I will reopen it. Thank you!

**Closed by huycozy** 2023-01-17 04:17 UTC
Labels: in triage
