### ISSUE TITLE
[WEB] Add build numbers to main.js to solve web cache issue

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#110649] opened 2022-08-31 07:31 UTC
It's a very simple issue.

When deploying web the cache gets stuck unless the user manually refreshes the browser or you tell them too, not so good.

Instead, add the version and build number to `main.js` in `web/index.html` when the app loads.

We do this manually at the moment with build numbers and it works.

`scriptTag.src = 'main.dart.js?version=44';`

**Comment by danagbemava-nc** [comment] 2022-08-31 11:28
Hi @ollydixon, I believe this is a duplicate of https://github.com/flutter/flutter/issues/63500. 

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. If you disagree, kindly leave a comment below and I will reopen this. 

Kindly upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2022-08-31 11:28 UTC
Labels: in triage
