### ISSUE TITLE
cloud firestorage doesnt work

### ISSUE THREAD

**Issue by grammystrano** [flutter/flutter#57335] opened 2020-05-15 19:51 UTC
### **this is my code for my the 1st TabBarview :
when i run it the app gets blocked**

`import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:flutterapp/FLS.dart';

class CjTemps extends StatefulWidget {
  @override
  _CjTempsState createState() => _CjTempsState();
}

class _CjTempsState extends State<CjTemps> {

  StreamSubscription<QuerySnapshot> subscription;
  List <DocumentSnapshot> tempsList;
  final CollectionReference collectionReference =
  Firestore.instance.collection("temps");

  @override
  void initState() {
    super.initState();
    subscription = collectionReference.snapshots().listen((datasnpashot){
      setState(() {
        tempsList = datasnpashot.documents;
      });
    });
  }

  @override
  void dispose() {
    subscription?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return  tempsList !=null?
      new StaggeredGridView.countBuilder(
          padding: EdgeInsets.all(6),
          crossAxisCount: 3,
          itemBuilder: (context, i){
            String imgPath = tempsList[i].data['url'];
            return Material(
              elevation: 8,
              borderRadius: BorderRadius.all(Radius.circular(8)),
              child: InkWell(
                onTap: ()=> Navigator.push(context, MaterialPageRoute(
                  builder: (context)=> Fls(imgPath)
                )),
               child: Hero(
                tag: imgPath,
                 child: FadeInImage(
                   image: NetworkImage(imgPath),
                   fit: BoxFit.cover,
                   placeholder: AssetImage("assets/not.gif"),
                 ) ,
              ),
              ),
            );
          },
          staggeredTileBuilder: (i) => StaggeredTile.count(2, i.isEven? 2 : 3),
          mainAxisSpacing: 5,
          crossAxisSpacing: 5,

      ) : Center(
       child: CircularProgressIndicator(backgroundColor: Colors.red),
      );
  }
}
`

**Comment by TahaTesser** [comment] 2020-05-18 08:54
Hi @grammystrano 
For what I can see the issue is related to a FlutterFire plugin, please open the issue in the dedicated [GitHub](https://github.com/FirebaseExtended/flutterfire/issues). 
Closing, as this isn't an issue with Flutter itself, if you disagree please write in the comments and I will reopen it
thank you

**Closed by TahaTesser** 2020-05-18 08:54 UTC
