### ISSUE TITLE
flutter_gallery's driver test doesn't show image resources

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#30641] opened 2019-04-07 16:17 UTC
To reproduce, run `flutter drive --profile -t test_driver/transitions_perf.dart` inside flutter_gallery on iPhone6S. Pay attention to Shrine and Contact inside Studies.

This issue makes our benchmark inaccurate as it doesn't capture the possibly slow image loading jank in https://github.com/flutter/flutter/issues/28113#issuecomment-476530608

Below is a screenshot of Contact when the flutter_gallery is opened by `flutter drive`:
![flutter_01](https://user-images.githubusercontent.com/22987568/55686407-96c21d80-5915-11e9-80ed-33b583f204d3.png)

For comparison, here's a screenshot if I open flutter_gallery normally without `flutter_drive`:
![flutter_03](https://user-images.githubusercontent.com/22987568/55686418-c5d88f00-5915-11e9-8461-49aee0a40516.png)

**Comment by liyuqian** [comment] 2019-04-07 16:34
Seems to be related with https://github.com/flutter/flutter/issues/21931. Here's my `flutter doctor -v`:

```
liyuqian-macbookpro2:flutter_gallery liyuqian$ flutter doctor -v
[✓] Flutter (Channel master, v1.2.1-pre.717, on Mac OS X 10.13.6 17G5019, locale en-US)
    • Flutter version 1.2.1-pre.717 at /Users/liyuqian/flutter/flutter
    • Framework revision d0f89c1190 (2 days ago), 2019-04-05 18:55:33 -0700
    • Engine revision 6bc33b5e14
    • Dart version 2.2.1 (build 2.2.1-dev.3.0 None)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/liyuqian/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4203.498

[✓] Connected device (1 available)
    • SixDegreesOfSeparation • 2b398993d86f42b05511b330a89ae65289832852 • ios • iOS 12.1.4

• No issues found!
```

**Comment by liyuqian** [comment] 2019-04-07 16:39
I just tested it with MotoG4 on Linux. The images are missing too. Here's my `flutter doctor -v`:
```
liyuqian@liyuqian:~/flutter/flutter/packages/flutter$ flutter doctor -v
[✓] Flutter (Channel revert_warm_up_check, v1.2.1-pre.678, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1-pre.678 at /usr/local/google/home/liyuqian/flutter/flutter
    • Framework revision 2b1cb9b607 (4 days ago), 2019-04-03 13:32:21 -0700
    • Engine revision cc115500b9
    • Dart version 2.2.1 (build 2.2.1-dev.3.0 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/google/home/liyuqian/android/Sdk/
    • Android NDK at /usr/local/google/home/liyuqian/android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/google/home/liyuqian/android/Sdk/
    • ANDROID_SDK_ROOT = /usr/local/google/home/liyuqian/android/Sdk/
    • Java binary at: /opt/android-studio-with-blaze-3.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio-with-blaze-3.3
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.backup)
    • IntelliJ at /opt/intellij-ce-2018.3
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5153.38

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /opt/intellij-ce-2018.2
    • Flutter plugin version 31.1.3
    • Dart plugin version 182.5124

[✓] VS Code (version 1.32.3)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Moto G 4 • ZY2245H6KS • android-arm • Android 7.0 (API 24)
```

**Comment by leishuai** [comment] 2019-07-17 06:34
@liyuqian  Has it worked now with latest flutter SDK version?

**Comment by liyuqian** [comment] 2019-07-17 17:51
Unfortunately no. I just confirmed that the issue is still there in 3b945da00d69698ab09f4375da16e13918508afc

@jonahwilliams : do you have any idea why `flutter run` has the images while `flutter drive` don't?

**Comment by jonahwilliams** [comment] 2019-07-17 17:54
No, I don't. This will need some time spent investigating. Possibly related to the reports that isolates don't work also.

**Comment by leishuai** [comment] 2019-07-18 03:36
I thought the reason is Isolated.spawn can NOT work in flutter drive. 
referring to: https://github.com/flutter/flutter/issues/35720

**Comment by liyuqian** [comment] 2019-07-18 17:23
Thank you @leishuai for your detailed explanation in https://github.com/flutter/flutter/issues/35720#issuecomment-512171082 !

**Comment by vishna** [comment] 2019-08-26 11:51
Apparently you can unpause the isolate in the observatory and then the image should show up:
https://github.com/flutter/flutter/issues/24703#issuecomment-505949053

That's not the fix though.

**Comment by The-Redhat** [comment] 2019-08-26 12:21
I think this whole issue is part of #24703 . The flutter team should look at this issue.

**Comment by vishna** [comment] 2019-08-26 13:49
Here's workaround that makes those images appear in the aforementioned tests: 

https://github.com/vishna/flutter/commit/2f858fc334fc2f43b92c318d02bdbf1ad0984033

Flutter team didn't have time to fix the issue #24703 since **Nov 2018** so unsure how critical working instrumentation tests are.

It is a really bad bug to have in my opinion and it seems to be only caused by an isolate being paused for whatever reasons 🤷‍♀️

**Comment by rockingdice** [comment] 2019-08-31 07:31
bump this. @vishna Thank you for the workaround! It's working now.

**Comment by amreniouinnovent** [comment] 2020-07-22 06:15
Solved my issue
https://github.com/flutter/flutter/issues/24703#issuecomment-531277291

**Comment by liyuqian** [comment] 2020-07-22 18:00
CC @CareF . If you're going to write a host-independent test for flutter_gallery, keep an eye on whether it shows the image and avoids this issue.

**Comment by CareF** [comment] 2020-07-22 20:55
I can confirm that the test app generated by e2e doesn't have this issue if directly run from the device, **but** if we are running e2e test using `flutter drive` we still go into this. @liyuqian

**Comment by liyuqian** [comment] 2020-07-22 22:03
@CareF in that case, I wonder if https://github.com/flutter/plugins/pull/2873 can only be used with `flutter drive`, or could it also be used with `flutter run`? In the worst case, I think we can just let the app print out the result, and parse it either through the stdout of `flutter run`, or from something like `adb logcat`. I believe all the test platforms (e.g., Firebase test lab) must persist the running log in some way?

**Comment by CareF** [comment] 2020-07-22 22:08
> @CareF in that case, I wonder if [flutter/plugins#2873](https://github.com/flutter/plugins/pull/2873) can only be used with `flutter drive`, or could it also be used with `flutter run`? In the worst case, I think we can just let the app print out the result, and parse it either through the stdout of `flutter run`, or from something like `adb logcat`. I believe all the test platforms (e.g., Firebase test lab) must persist the running log in some way?

Yes flutter/plugins#2873 is just an adaptor to `flutter drive`, and may be used in the future for Timeline collection on e2e. To just print the result we don't need flutter/plugins#2873.

**Comment by dnfield** [comment] 2020-07-23 18:48
https://github.com/flutter/flutter/pull/61841 Will fix this.

**Comment by speaking-in-code** [comment] 2020-07-27 05:14
My fix for this in #61841 was reverted with #62239. So this bug is still open.

If anyone has tips on how to run the devicelab tests, I'm happy to try to debug the issues so that this fix can land.

**Comment by jonahwilliams** [comment] 2020-07-27 16:16
There are some instructions in https://github.com/flutter/flutter/tree/master/dev/devicelab


two of the specific tests that failed were new_gallery_ios__transition_perf and new_gallery__transition_perf

**Comment by dnfield** [comment] 2022-08-17 18:08
Fix relanded in https://github.com/flutter/flutter/pull/65703

**Closed** 2022-08-17 18:07 UTC
Labels: team, framework, f: material design, severe: performance, team: gallery, passed first triage, P3
