### ISSUE TITLE
textfield on iOS  autofill  will twice for void _formatAndSetValue(TextEditingValue value) {}

### ISSUE THREAD

**Issue by Tonigt** [flutter/flutter#66797] opened 2020-09-28 02:25 UTC
textfield on iOS  autofill  will twice call the method void _formatAndSetValue(TextEditingValue value) {}
on second time the method be called，the value is error  
for example : the first time  value is '2223', the second time call  the value has been '22232223', its exception

**Comment by pedromassangocode** [comment] 2020-09-28 08:45
Hi @Tonigt 
Can you please provide your `flutter doctor -v` the actual vs expected results and a minimal complete reproducible code sample?
Thank you

**Comment by Tonigt** [comment] 2020-09-28 08:47
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.5 19F101, locale
 
&nbsp; &nbsp; zh-Hans-CN)
 
&nbsp; &nbsp; • Flutter version 1.20.4 at /Users/tonight/flutter_master/flutter
 
&nbsp; &nbsp; • Framework revision fba99f6cf9 (13 days ago), 2020-09-14 15:32:52 -0700
 
&nbsp; &nbsp; • Engine revision d1bc06f032
 
&nbsp; &nbsp; • Dart version 2.9.2
 
&nbsp; &nbsp; • Pub download mirror https://pub.flutter-io.cn
 
&nbsp; &nbsp; • Flutter download mirror https://storage.flutter-io.cn
 


 
&nbsp;
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
 
&nbsp; &nbsp; • Android SDK at /Users/tonight/Library/Android/sdk
 
&nbsp; &nbsp; • Platform android-29, build-tools 29.0.3
 
&nbsp; &nbsp; • ANDROID_HOME = /Users/tonight/Library/Android/sdk
 
&nbsp; &nbsp; • Java binary at: /Applications/Android
 
&nbsp; &nbsp; &nbsp; Studio.app/Contents/jre/jdk/Contents/Home/bin/java
 
&nbsp; &nbsp; • Java version OpenJDK Runtime Environment (build
 
&nbsp; &nbsp; &nbsp; 1.8.0_242-release-1644-b3-6222593)
 
&nbsp; &nbsp; • All Android licenses accepted.
 


 
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
 
&nbsp; &nbsp; • Xcode at /Applications/Xcode.app/Contents/Developer
 
&nbsp; &nbsp; • Xcode 12.0.1, Build version 12A7300
 
&nbsp; &nbsp; • CocoaPods version 1.10.0.beta.2
 


 
[✓] Android Studio (version 4.0)
 
&nbsp; &nbsp; • Android Studio at /Applications/Android Studio.app/Contents
 
&nbsp; &nbsp; • Flutter plugin version 46.0.2
 
&nbsp; &nbsp; • Dart plugin version 193.7361
 
&nbsp; &nbsp; • Java version OpenJDK Runtime Environment (build
 
&nbsp; &nbsp; &nbsp; 1.8.0_242-release-1644-b3-6222593)
 


 
[✓] VS Code (version 1.48.2)
 
&nbsp; &nbsp; • VS Code at /Applications/Visual Studio Code.app/Contents
 
&nbsp; &nbsp; • Flutter extension version 3.13.2
 


 
[✓] Connected device (1 available)
 
&nbsp; &nbsp; • iPhone (mobile) • 82701af5539171b5da4b6da05c38f53597c13703 • ios • iOS
 
&nbsp; &nbsp; &nbsp; 14.0
 


 
• No issues found!





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pedro Massango"<notifications@github.com&gt;; 
发送时间: 2020年9月28日(星期一) 下午4:45
收件人: "flutter/flutter"<flutter@noreply.github.com&gt;; 
抄送: "lonely"<1984701289@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [flutter/flutter] textfield on iOS  autofill  will twice for void _formatAndSetValue(TextEditingValue value) {} (#66797)





 
Hi @Tonigt
 Can you please provide your flutter doctor -v the actual vs expected results and a minimal complete reproducible code sample?
 Thank you

**Comment by pedromassangocode** [comment] 2020-09-28 14:12
Hi @Tonigt 
I also need the actual vs expected results and a minimal complete reproducible code sample.
Thank you

**Comment by Tonigt** [comment] 2020-09-29 03:18
just sample example  :  TextField(
            focusNode: FocusNode(),
               decoration: InputDecoration(
                contentPadding: EdgeInsets.zero,
                border: InputBorder.none,
                hintText: '请输入验证码',
                hintStyle: TextStyle(
                    color: Color.fromARGB(255, 153, 153, 153),
                    fontWeight: fontWeight500,
                    fontSize: fontSize15)),
            controller: TextEditingController());      

a network request ask servicer turn back a security code "2223", tap  iOS  autofill, then  textField's text value is "22232223"

**Comment by pedromassangocode** [comment] 2020-09-29 08:02
Hi @Tonigt 
I also need the a minimal complete reproducible code sample. the code you provided is not runnable since it is just a TextField. 
Thank you

**Comment by pedromassangocode** [comment] 2020-10-21 13:28
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-21 13:28 UTC

**Comment by BaroneX** [comment] 2021-05-19 03:18
@Tonigt I also have this problem, have you found a solution?
