### ISSUE TITLE
Delete by word does not work

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#77547] opened 2021-03-08 00:18 UTC
Control/Alt + Delete/Backspace should delete entire word, but it is currently not implemented.

**Comment by HansMuller** [comment] 2021-03-08 21:55
CC @justinmc

**Comment by justinmc** [comment] 2021-03-13 01:07
Closing as a duplicate of https://github.com/flutter/flutter/issues/57015.

**Comment by gspencergoog** [comment] 2021-04-02 22:08
Reopening, since this was reverted in https://github.com/flutter/flutter/pull/79674

**Comment by gspencergoog** [comment] 2021-04-02 22:09
Sorry, reopened wrong issue.  Closing again, still a duplicate.

**Closed by gspencergoog** 2021-04-02 22:09 UTC
Labels: a: text input, f: material design, found in release: 2.1, framework, has reproducible steps
