### ISSUE TITLE
pub get failed - Gradle failed No route to host: connect

### ISSUE THREAD

**Issue by gourav6m17** [flutter/flutter#55022] opened 2020-04-17 08:37 UTC
```
After updating flutter and android studio it give me an issue i.e.
C:\src\flutter\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in flut_new...                        
Because flutnew depends on flutter any from sdk which doesn't exist (unknown SDK "flutter."), version solving failed.

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

Because flutnew depends on flutter any from sdk which doesn't exist (unknown SDK "flutter."), version solving failed.

pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...

Because flutnew depends on flutter any from sdk which doesn't exist (unknown SDK "flutter."), version solving failed.

pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...

Because flutnew depends on flutter any from sdk which doesn't exist (unknown SDK "flutter."), version solving failed.
And its going on.........

D:\AndroidProjects\flut_new>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Android Studio (version 3.6)
[√] VS Code (version 1.41.0)
[!] Connected device

D:\AndroidProjects\flut_new>flutter upgrade
Upgrading Flutter from C:\src\flutter\flutter...
Already up to date.
Flutter is already up to date on channel beta
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (10 days ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

! Doctor found issues in 2 categories.

PLEASE HELP ME!

```

**Comment by iapicca** [comment] 2020-04-17 08:57
Hi @gourav6m17 
to fix
```console
Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
```
please follow up on this [issue](https://github.com/flutter/flutter/issues/51712).

About the error `pub get failed (server unavailable)`
if you are behind a proxy or a vpn you may want to check the solutions proposed this [issue](dart-lang/pub#2288).

Let me know if the issue persists
Thank you

**Comment by gourav6m17** [comment] 2020-04-18 07:42
Hi @iapicca thank for replying.
i'm not using any proxy and vpn but it dont stil work for me.
I have installed Android SDK Tools (Obsolete) 26.1.1
but still error. same`[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.`

**Comment by TahaTesser** [comment] 2020-04-20 08:39
Hi @gourav6m17 
After installing `Android SDK Tools (Obsolete) 26.1.1`
please execute `flutter doctor --android-licenses` and accept al licenses 
and try `flutter doctor -v` to confirm
Thank you

**Comment by gourav6m17** [comment] 2020-04-20 10:29
@TahaTesser Thank u sir for replying!
I have all these things and there is no issue shown by `flutter doctor -v`
But while I'm trying to run my app and it gives me following issue.
`Launching lib\main.dart on Redmi 4 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download kotlin-compiler-runner.jar (org.jetbrains.kotlin:kotlin-compiler-runner:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-runner/1.3.50/kotlin-compiler-runner-1.3.50.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-runner/1.3.50/kotlin-compiler-runner-1.3.50.jar'.
            > Read timed out
   > Could not download kotlin-scripting-jvm.jar (org.jetbrains.kotlin:kotlin-scripting-jvm:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-scripting-jvm/1.3.50/kotlin-scripting-jvm-1.3.50.jar'.
         > Read timed out
   > Could not download kotlin-scripting-common.jar (org.jetbrains.kotlin:kotlin-scripting-common:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-scripting-common/1.3.50/kotlin-scripting-common-1.3.50.jar'.
         > Read timed out
   > Could not download kotlin-gradle-plugin-api.jar (org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin-api/1.3.50/kotlin-gradle-plugin-api-1.3.50.jar'.
         > Read timed out
   > Could not download kotlin-native-utils.jar (org.jetbrains.kotlin:kotlin-native-utils:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-native-utils/1.3.50/kotlin-native-utils-1.3.50.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-native-utils/1.3.50/kotlin-native-utils-1.3.50.jar'.
            > Read timed out
   > Could not download kotlin-util-io.jar (org.jetbrains.kotlin:kotlin-util-io:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-util-io/1.3.50/kotlin-util-io-1.3.50.jar'.
         > Read timed out
   > Could not download gradle-download-task.jar (de.undercouch:gradle-download-task:3.4.3)
      > Could not get resource 'https://jcenter.bintray.com/de/undercouch/gradle-download-task/3.4.3/gradle-download-task-3.4.3.jar'.
         > Could not GET 'https://jcenter.bintray.com/de/undercouch/gradle-download-task/3.4.3/gradle-download-task-3.4.3.jar'.
            > No route to host: connect
   > Could not download kotlin-script-runtime.jar (org.jetbrains.kotlin:kotlin-script-runtime:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-script-runtime/1.3.50/kotlin-script-runtime-1.3.50.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-script-runtime/1.3.50/kotlin-script-runtime-1.3.50.jar'.
            > No route to host: connect
   > Could not download kotlin-daemon-embeddable.jar (org.jetbrains.kotlin:kotlin-daemon-embeddable:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-daemon-embeddable/1.3.50/kotlin-daemon-embeddable-1.3.50.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-daemon-embeddable/1.3.50/kotlin-daemon-embeddable-1.3.50.jar'.
            > No route to host: connect
   > Could not download trove4j.jar (org.jetbrains.intellij.deps:trove4j:1.0.20181211)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.jar'.
            > No route to host: connect
   > Could not download kotlin-build-common.jar (org.jetbrains.kotlin:kotlin-build-common:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.3.50/kotlin-build-common-1.3.50.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.3.50/kotlin-build-common-1.3.50.jar'.
            > No route to host: connect
   > Could not download kotlinx-coroutines-core.jar (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.jar'.
            > No route to host: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16m 56s
Exception: Gradle task assembleDebug failed with exit code 1`
This is fresh flutter App. 
Please help me!

**Comment by TahaTesser** [comment] 2020-04-22 07:52
Duplicate of [#54921](https://github.com/flutter/flutter/issues/54921)

**Closed by TahaTesser** 2020-04-22 07:52 UTC
Labels: in triage

**Comment by gourav6m17** [comment] 2020-04-23 11:53
Thank u so much @TahaTesser for solving this issue.
