### ISSUE TITLE
iOS device does not show up in Firebase Analytics DebugView

### ISSUE THREAD

**Issue by CyrilBos** [flutter/flutter#32626] opened 2019-05-13 14:47 UTC
Hi everyone,
I am trying to integrate Firebase Analytics in my Flutter app. It currently works fine on Android but it's hard to see if it really does on iOS. 

I have added the `-FIRDebugEnabled` flag in the arguments of the Runner scheme in Xcode but the device does not show up in the DebugView of my Firebase project. 

Any idea on how to troubleshoot this?

**Comment by CyrilBos** [comment] 2019-05-13 15:39
I have read here https://firebase.google.com/docs/analytics/ios/events that I should add `FIRAnalyticsDebugEnabled` as well, however this still does not work.
The device appears in StreamView by the way.

**Comment by SmallMouth** [comment] 2019-05-15 10:04
try add FIRDebugEnabled without "-"

**Comment by KingWu** [comment] 2019-10-02 08:56
Face the same issues. i added -FIRDebugEnabled into scheme. Using flutter run, the debug view did not work. But, i try to use XCode to run the flutter project. it works. 

I wonder that ```flutter run``` command does not pass the -FIRDebugEnabled argument to build iOS app.

**Comment by logemann** [comment] 2019-10-19 14:58
Same here. Firebase team says to modify command line argument for the RUN method in xcode but i am pretty sure "flutter run" doesnt use the command line argument defined in XCode. I have no issues at all on Android of course.

Please can somebody from the Flutter tooling team comment on that? We need a way to pass that FIRDebugEnabled to the Simulator.

**Comment by iapicca** [comment] 2020-01-15 12:55
Hi @CyrilBos 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-15 12:55 UTC
Labels: ⌺‬ platform-ios
