### ISSUE TITLE
flutter has exited unexpectedly

### ISSUE THREAD

**Issue by G-0-k-u** [flutter/flutter#35887] opened 2019-07-10 16:20 UTC
## Steps to Reproduce

Last login: Wed Jul 10 18:09:40 on ttys000
Gokus-MBP:~ goku$ flutter --version
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Oops; flutter has exited unexpectedly.
Crash report written to /Users/goku/flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
Gokus-MBP:~ goku$ 

## Logs

Last login: Wed Jul 10 18:09:40 on ttys000
Gokus-MBP:~ goku$ flutter --version
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Oops; flutter has exited unexpectedly.
Crash report written to /Users/goku/flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
Gokus-MBP:~ goku$ 

## command

flutter --version

## exception

VersionCheckError: VersionCheckError: Command exited with code 1: git log -n 1 --pretty=format:%ad --date=iso
Standard error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

```
#0      _runSync (package:flutter_tools/src/version.dart:522:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:142:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:110:99)
#4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:387:46)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 1: git log -n 1 --pretty=format:%ad --date=iso
Standard error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun


#0      _runSync (package:flutter_tools/src/version.dart:522:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:142:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:95:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:501:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:193:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:192:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:170:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:125:33)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:65:22)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1500:12)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#29     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#30     run (package:flutter_tools/runner.dart:51:10)
#31     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#32     main (file:///Users/wade/Developer/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
-->

```
```

```
```

**Comment by ketanm** [comment] 2019-07-10 16:29
@G-0-k-u 

As error tells you, install XCode command line tools. See #stackoverflow for it.
`Standard error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

**Comment by stuartmorgan** [comment] 2019-07-18 13:06
Duplicate of #29952

**Closed by stuartmorgan** 2019-07-18 13:06 UTC
