### ISSUE TITLE
app crashes when image picker opens

### ISSUE THREAD

**Issue by mahdiqdi** [flutter/flutter#131267] opened 2023-07-25 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

when gallery opens vm shutting down

### Expected results

picture should be selected

### Actual results

when gallery opens vm shutting down

### Code sample

<details><summary>Code sample</summary>

```dart
Future<bool> getImage() async {
    final pickedFile = await ImagePicker().pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      String imagePath = pickedFile.path;
      String imageType = imagePath.split('.').last;
      bool isValid = false;
      if (imageType == 'jpg' || imageType == 'jpeg' || imageType == 'png' || imageType == 'PNG' || imageType == 'JPEG' || imageType == 'JPG') {
        isValid = true;
      }

      if (((File(imagePath)).lengthSync() / 1024 / 1024) < 5 && isValid) {
        final bytes = await File(imagePath).readAsBytes();
        setState(() {
          image = base64Encode(bytes);
        });
      } else {
        return false;
      }
    }

    return true;
  }```

</details>


### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details><summary>Logs</summary>

```console
E/JavaBinder(27999): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 826136)
W/ActivityStopInfo(27999): Bundle stats:
W/ActivityStopInfo(27999):   androidx.lifecycle.BundlableSavedStateRegistry.key [size=824628]
W/ActivityStopInfo(27999):     android:support:activity-result [size=1396]
W/ActivityStopInfo(27999):     android:support:fragments [size=822908]
W/ActivityStopInfo(27999):       fragment_0918a42c-3f8e-4020-9367-424c1b1801f6 [size=822492]
W/ActivityStopInfo(27999):         savedInstanceState [size=820680]
W/ActivityStopInfo(27999):           framework [size=820612]
W/ActivityStopInfo(27999): PersistableBundle stats:
W/ActivityStopInfo(27999):   [null]
D/AndroidRuntime(27999): Shutting down VM
E/AndroidRuntime(27999): FATAL EXCEPTION: main
E/AndroidRuntime(27999): java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 826136 bytes
E/AndroidRuntime(27999): 	at android.app.ActivityClient.activityStopped(ActivityClient.java:87)
E/AndroidRuntime(27999): 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
E/AndroidRuntime(27999): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(27999): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(27999): 	at android.os.Looper.loopOnce(Looper.java:211)
E/AndroidRuntime(27999): 	at android.os.Looper.loop(Looper.java:300)
E/AndroidRuntime(27999): 	at android.app.ActivityThread.main(ActivityThread.java:8279)
E/AndroidRuntime(27999): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27999): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
E/AndroidRuntime(27999): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
E/AndroidRuntime(27999): Caused by: android.os.TransactionTooLargeException: data parcel size 826136 bytes
E/AndroidRuntime(27999): 	at android.os.BinderProxy.transactNative(Native Method)
E/AndroidRuntime(27999): 	at android.os.BinderProxy.transact(BinderProxy.java:629)
E/AndroidRuntime(27999): 	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1315)
E/AndroidRuntime(27999): 	at android.app.ActivityClient.activityStopped(ActivityClient.java:84)
E/AndroidRuntime(27999): 	... 9 more
W/e.android(27999): type=1400 audit(0.0:77806): avc: denied { search } for name="mqsas" dev="dm-11" ino=540 scontext=u:r:untrusted_app:s0:c16,c261,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=
W/OOMEventManagerFK(27999): Failed to mkdir /data/mqsas/hprof/
I/Process (27999): Sending signal. PID: 27999 SIG: 9
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 12.6.1 21G217 darwin-x64, locale en-TR)
    • Flutter version 3.10.0 on channel stable at /Users/mac/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 months ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.1)
    • VS Code at /Users/mac/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • 21061119AG (mobile) • 105f2bfe0506 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)     • macos        • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 115.0.5790.102

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-07-26 06:34
Hi @mahdiqdi 
Please share the complete sample code. I check below sample code but can't reproduce issue on my device (Realme 6, Android 11). 

<details>
<summary>Sample code</summary>

```dart
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const MyWidget(),
    ),
  );
}

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () async {
            await getImage();
          },
          child: const Text('Pick Image'),
        ),
      ),
    );
  }

  Future<bool> getImage() async {
    final pickedFile = await ImagePicker().pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      String imagePath = pickedFile.path;
      String imageType = imagePath.split('.').last;
      bool isValid = false;
      if (imageType == 'jpg' || imageType == 'jpeg' || imageType == 'png' || imageType == 'PNG' || imageType == 'JPEG' || imageType == 'JPG') {
        isValid = true;
      }

      if (((File(imagePath)).lengthSync() / 1024 / 1024) < 5 && isValid) {
        final bytes = await File(imagePath).readAsBytes();
        setState(() {
          final image = base64Encode(bytes);
        });
      } else {
        return false;
      }
    }

    return true;
  }
}

```
</details>

And which device are you seeing this crash? Please also provide detailed steps or recorded video that will help to verify the issue. A picked image can come from some kind of content uri (SD Card, Google Photos, etc), so verifying the source of image could be helpful.

**Comment by mahdiqdi** [comment] 2023-07-26 06:40
I will provide you more detail
But crash occurs in xiaomi redmi10.i tested it on nothing1 and its ok.
I should tell you that the problem occurs unexpectdly,before yesterday it was ok

**Comment by mahdiqdi** [comment] 2023-07-26 10:07
@huycozy 
i found something else
this issue is not related to image_picker 
this error happens even if i minimize my application
only in this page when i minimize my app or select image from gallery this error happens
other pages is ok
plz help me or if you need more detail about this issue tell me i can provide you
thanks for your help

**Comment by huycozy** [comment] 2023-07-27 03:18
Hi @mahdiqdi 
If the issue is not related to `image_picker` package, but other 3rd packages, please report it to package's developers/maintainers and feel free to close this issue.

Otherwise, if you think this is a Flutter framework bug, please provide:
- The detailed steps to reproduce the crash
- Output of `flutter run -v` that may include stack trace of crash
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code

**Closed** 2023-08-17 04:09 UTC
Labels: waiting for customer response, in triage
