### ISSUE TITLE
Keyboard is Locked when we press ALTgr + @ on virtual keyboard on Windows

### ISSUE THREAD

**Issue by Alexandre-Burger** [flutter/flutter#101811] opened 2022-04-13 07:50 UTC
Hello, i have some problem with virtual keyboard on windows. When i'm trying to tap ALTgr on virtual keyboard on windows, the entire keyboard is locked. It's impossible to tap on any other key. (I'm using french keyboard). If i press Ctrl left two times, the keyboard is now unlocked and i can type other key.
The [issue 78005](https://github.com/flutter/flutter/issues/78005) is about the same problem. A pull request has been done to fix this problem, but i think that fix only for real keyboard and not for a virtual keyboard.

## Steps to Reproduce

1. Execute `flutter run -d windows` on the code sample (on windows) 
2. Open virtual keyboard like on-screen keyboard.  
3.  Press @ with ALTgr in the Textfield and try after to press letters. 

**Expected results:** 
I can use keyboard normally.

**Actual results:** 
I can no longer use keyboard if i press ALTgr and @.

<details>
<summary>Code sample (it's the sample of TextField in flutter)</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  late TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(
          controller: _controller,
          onSubmitted: (String value) async {
            await showDialog<void>(
              context: context,
              builder: (BuildContext context) {
                return AlertDialog(
                  title: const Text('Thanks!'),
                  content: Text(
                      'You typed "$value", which has length ${value.characters.length}.'),
                  actions: <Widget>[
                    TextButton(
                      onPressed: () {
                        Navigator.pop(context);
                      },
                      child: const Text('OK'),
                    ),
                  ],
                );
              },
            );
          },
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
There are no exceptions with flutter run --verbose
```

```
Analyzing bug...                                                        
No issues found! (ran in 4.0s)
```

```[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19043.1586], locale en-US)
    • Flutter version 2.10.4 at C:\Users\Optyce\Documents\flutter_sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Optyce\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 16.0.1+9-24)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.66.1)
    • VS Code at C:\Users\Optyce\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.29

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by maheshmnj** [comment] 2022-04-13 09:36
Hi @Alexandre-Burger, thanks for filing the issue. I tried to verify this on a qwerty keyboard and I was not able to reproduce the issue. I believe this issue could be specific to french keyboards. Can you please check if this is reproducible on the master channel? You can switch to the master channel by running 
```
flutter channel master
 flutter upgrade
```

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586],
    locale en-US)
    • Flutter version 2.10.4 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.82      
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.30     

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Alexandre-Burger** [comment] 2022-04-13 10:03
Hi @maheshmnj. Thanks for your anwser. I try on master channel and it works. i can't reproduce the bug on master channel. So i have a question : can we use master channel for production? Is it safe?

**Comment by maheshmnj** [comment] 2022-04-13 10:46
Thanks for the update @Alexandre-Burger.
 > can we use the master channel for production? Is it safe?

Using master channel is not recommended for production apps as it is the tip of the tree all PR's from contributors are merged in the master channel every day, which includes accidental bugs too :)

To understand more about flutter channels and the release cycle please see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels.

> I try on master channel and it works.

Closing as fixed based on the above response.

**Closed by maheshmnj** 2022-04-13 10:46 UTC
Labels: in triage
