### ISSUE TITLE
[TextFormField] validator errorText how to change position?

### ISSUE THREAD

**Issue by peterweb2005** [flutter/flutter#88568] opened 2021-08-20 07:52 UTC
as title,

when field validate error, the "errorText" is place under the input field,
but my project want the errorText place above the input field, any most elegant solution?

**Comment by TahaTesser** [comment] 2021-08-23 10:52
Hi @peterweb2005 
There is no align property for this yet, duplicate of https://github.com/flutter/flutter/issues/11068

**Closed by TahaTesser** 2021-08-23 10:52 UTC
Labels: in triage
