### ISSUE TITLE
[web] Widget disappear with showSearch + delegate + Inkwell

### ISSUE THREAD

**Issue by ferraridamiano** [flutter/flutter#61792] opened 2020-07-18 12:28 UTC
I created a web app with flutter and I noticed that if you use showSearch() with a custom delegate and inside the search page you use a clickable widget such as InkWell or GestureDetector when we tap on one of this widgets all the widgets disappear. If you use the same codebase on android all works well.

Here's a self explanatory gif:
![InstantGif_2020 07 18-14 03](https://user-images.githubusercontent.com/34270884/87852347-739c6100-c901-11ea-895f-a327661d670c.gif)

<details>
  <summary>Example code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

    final SearchDelegate _searchDelegate=CustomSearchDelegate();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        actions: [IconButton(icon: Icon(Icons.search), onPressed: () {showSearch(context: context,delegate: _searchDelegate);})],
      ),
      body: Scrollbar(
        child: Container(
          child: GridView.count(
            crossAxisCount: 3,
            shrinkWrap: true,
            crossAxisSpacing: 15.0,
            children: getListGridTile(),
          ),
        ),
      ),
    );
  }
}

List getListGridTile() {
  List<SearchGridTile> gridTiles = new List();
  gridTiles.add(SearchGridTile(icon: Icon(Icons.ac_unit, size: 50.0,),onTap: () {}));
  gridTiles.add(SearchGridTile(icon: Icon(Icons.access_alarm, size: 50.0,),onTap: () {}));
  gridTiles.add(SearchGridTile(icon: Icon(Icons.access_time, size: 50.0,),onTap: () {},));
  return gridTiles;
}

class SearchGridTile extends StatelessWidget {
  final Widget icon;
  final onTap;
  SearchGridTile({this.icon, this.onTap});

  @override
  Widget build(BuildContext context) {
    return InkWell(
        onTap: onTap,
        child: Container(
            padding: EdgeInsets.all(5.0),
            child: Center(
                child: GridTile(
                    child: Align(
                        alignment: Alignment.center,
                        child: Container(
                            width: 55.0, height: 55.0, child: icon))))));
  }
}

class CustomSearchDelegate extends SearchDelegate {
  @override
  ThemeData appBarTheme(BuildContext context) => Theme.of(context);

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
      icon: AnimatedIcon(
        icon: AnimatedIcons.menu_arrow,
        progress: transitionAnimation,
      ),
      onPressed: () {
        close(context, null);
      },
    );
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    final List<SearchGridTile> allConversions = getListGridTile();
    return GridView(
            gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
                maxCrossAxisExtent: 200.0),
            children: allConversions,
          );
  }

  @override
  Widget buildResults(BuildContext context) {
    return Container();
  }

  @override
  List<Widget> buildActions(BuildContext context) {
    return <Widget>[
      if (query.isNotEmpty)
        IconButton(
          tooltip: 'Clear',
          icon: const Icon(Icons.clear),
          onPressed: () {
            query = '';
            showSuggestions(context);
          },
        ),
    ];
  }
}
```
</details>

<details>
  <summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Versione 10.0.19041.388], locale it-IT)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.2)
[√] Connected device (3 available)

• No issues found!
```

</details>

If you just want to try the app, here there is my flutter app affected by this bug, just open the link and click the search icon in the bottom right corner (in this case we have the bug when we long press the icons): https://ferraridamiano.github.io/ConverterNOW

**Comment by TahaTesser** [comment] 2020-07-20 08:49
Hi @ferraridamiano 
I can reproduce the issue on latest `beta ` but there is no issue on `dev` 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final SearchDelegate _searchDelegate = CustomSearchDelegate();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        actions: [
          IconButton(
              icon: Icon(Icons.search),
              onPressed: () {
                showSearch(context: context, delegate: _searchDelegate);
              })
        ],
      ),
      body: Scrollbar(
        child: Container(
          child: GridView.count(
            crossAxisCount: 3,
            shrinkWrap: true,
            crossAxisSpacing: 15.0,
            children: getListGridTile(),
          ),
        ),
      ),
    );
  }
}

List getListGridTile() {
  List<SearchGridTile> gridTiles = new List();
  gridTiles.add(SearchGridTile(
      icon: Icon(
        Icons.ac_unit,
        size: 50.0,
      ),
      onTap: () {}));
  gridTiles.add(SearchGridTile(
      icon: Icon(
        Icons.access_alarm,
        size: 50.0,
      ),
      onTap: () {}));
  gridTiles.add(SearchGridTile(
    icon: Icon(
      Icons.access_time,
      size: 50.0,
    ),
    onTap: () {},
  ));
  return gridTiles;
}

class SearchGridTile extends StatelessWidget {
  final Widget icon;
  final onTap;
  SearchGridTile({this.icon, this.onTap});

  @override
  Widget build(BuildContext context) {
    return InkWell(
        onTap: onTap,
        child: Container(
            padding: EdgeInsets.all(5.0),
            child: Center(
                child: GridTile(
                    child: Align(
                        alignment: Alignment.center,
                        child: Container(
                            width: 55.0, height: 55.0, child: icon))))));
  }
}

class CustomSearchDelegate extends SearchDelegate {
  @override
  ThemeData appBarTheme(BuildContext context) => Theme.of(context);

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
      icon: AnimatedIcon(
        icon: AnimatedIcons.menu_arrow,
        progress: transitionAnimation,
      ),
      onPressed: () {
        close(context, null);
      },
    );
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    final List<SearchGridTile> allConversions = getListGridTile();
    return GridView(
      gridDelegate:
          SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent: 200.0),
      children: allConversions,
    );
  }

  @override
  Widget buildResults(BuildContext context) {
    return Container();
  }

  @override
  List<Widget> buildActions(BuildContext context) {
    return <Widget>[
      if (query.isNotEmpty)
        IconButton(
          tooltip: 'Clear',
          icon: const Icon(Icons.clear),
          onPressed: () {
            query = '';
            showSuggestions(context);
          },
        ),
    ];
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (5 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
```

</details> 

I cannot reproduce this issue on latest dev channel.
Can you upgrade to `dev` channel  and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by ferraridamiano** [comment] 2020-07-20 09:18
Thanks @TahaTesser ! I confirm that with dev channel the issue has been fixed. I'm sorry, I did't checked before submitting the issue

**Comment by TahaTesser** [comment] 2020-07-21 07:02
Hi @ferraridamiano 
No worries, thanks for confirming 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-07-21 07:02 UTC
Labels: in triage
