### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Uri c:/Users/tinoc/pos_devices_app/fonts/Roboto-Regular.ttf must have scheme 'file:'.

### ISSUE THREAD

**Issue by tcourage-mush** [flutter/flutter#150110] opened 2024-06-12 13:39 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Uri c:/Users/tinoc/pos_devices_app/fonts/Roboto-Regular.ttf must have scheme 'file:'.
```
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:86:7)
#1      Context.fromUri (package:path/src/context.dart:1040:40)
#2      ManifestAssetBundle._resolveAsset (package:flutter_tools/src/asset.dart:1164:47)
#3      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:957:34)
#4      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:308:54)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:544:26)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:322:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22621.3593], locale en-ZW)
    [32m•[39m Flutter version 3.22.0 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 5dcb86f68f (5 weeks ago), 2024-05-09 07:39:20 -0500
    [32m•[39m Engine revision f6344b75dc
    [32m•[39m Dart version 3.4.0
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.7)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.9.34902.65
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.90.0)
    [32m•[39m VS Code at C:\Users\tinoc\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.90.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3593]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.142
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.92

[33m[!][39m Network resources
    [31m✗[39m A network error occurred while checking "https://pub.dev/": The semaphore timeout period has expired.

    [31m✗[39m A network error occurred while checking "https://storage.googleapis.com/": The semaphore timeout period has expired.

    [31m✗[39m A network error occurred while checking "https://maven.google.com/": The semaphore timeout period has expired.

    [31m✗[39m A network error occurred while checking "https://cocoapods.org/": The semaphore timeout period has expired.

    [31m✗[39m A network error occurred while checking "https://github.com/": The semaphore timeout period has expired.


[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: null
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
app_links-6.1.1
connectivity_plus-5.0.2
gtk-2.1.0
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sqflite-2.3.3+1
url_launcher-6.2.6
url_launcher_android-6.3.2
url_launcher_ios-6.3.0
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1

**Comment by danagbemava-nc** [comment] 2024-06-12 13:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/116737

**Closed by danagbemava-nc** 2024-06-12 13:41 UTC
Labels: in triage
