### ISSUE TITLE
Weird images rendering issues

### ISSUE THREAD

**Issue by PiercarloSlavazza** [flutter/flutter#22546] opened 2018-10-02 07:11 UTC
Today one of the testers of our Flutter app reported a weird issue abount images rendering and layout.

The app usually looks like this (with some labels "anonymized"):

![flutter_images_ok](https://user-images.githubusercontent.com/3389306/46333655-65dcf500-c621-11e8-9f72-76af397109c1.png)

But, on its phone, at some point in time (apparntly without any relation to any action on the dev/deploy side), it started to look like this:

![flutter_images_garbled_1_annotated](https://user-images.githubusercontent.com/3389306/46333729-b9e7d980-c621-11e8-97b1-d950734e8081.png)

The brand, model and Android version of the tester are:

> brand: huawei
> model: ALE-L21
> android version: 6

Among the testers, which are currently 10 or so, he is the only one affected by this weird issue (the app is not yet released) - even when we tried to replicate the very same data on each of the testers phone (which are all Android, of different brands/versions).

Does anyone have some clue about what might happening and/or can point me to a way to debugging this behaviour?

Images are loaded and displayed via `NetworkImage`, and layout is done via a `GridView.builder`.

Flutter doctor says:

```
C:\apps\programming\flutter\bin\flutter.bat --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.9.4-pre.31, on Microsoft Windows [Versione 10.0.17134.285], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
[√] Connected devices (1 available)
```

**Comment by zoechi** [comment] 2018-12-30 17:04
Sorry for not coming back to this earlier.
Are still seeing this problem?

**Comment by nullp01nt3r** [comment] 2019-01-02 15:31
Hi @zoechi ,

I asked the tester which was experiencing the problem and:

* he said he is still using the same phone, but that he has not seen this kind of issue for a long time
* on the other end, I haven't changed in the meatime the Flutter SDK version, and I did not changed the implementation of the related code in a significant way

So, given that the issue is no more observable, and I have no clue in understanding what actually solved it, I would just close the issue for the moment.

**Comment by zoechi** [comment] 2019-01-02 16:41
@nullp01nt3r thanks for the update.
Feel free to reopen if you encounter it again.

**Comment by nullp01nt3r** [comment] 2019-01-21 08:20
Hi @zoechi,

yesterday the tester reported the issue one more time.

Belowe the screenshot he sent me.

Flutter sdk and test phone are unchanged.

The issue however seems to occur randomly - so I cannot reporduce it.

I have no idea if and how we can collect useful data about the issue - apart these screenshots.

Let me know if you have any tip which might help in debugging.

Thank you.

![image](https://user-images.githubusercontent.com/3389306/51461199-c2455b00-1d5d-11e9-9a2c-77d9ed837c2d.png)

**Comment by nullp01nt3r** [comment] 2019-01-21 08:32
> The output of flutter doctor -v from the machine where you created the used build

It's in the beginning of the issue - unchanged from then.

**Comment by marcglasberg** [comment] 2019-03-02 17:43
A question: Do you use the `flutter_svg` package? 

Also, would you say these 3 following issues are the same problem? 
https://github.com/flutter/flutter/issues/28484 
https://github.com/flutter/flutter/issues/22546
https://github.com/flutter/flutter/issues/28786

**Comment by marcglasberg** [comment] 2019-03-02 17:53
Also these:
https://github.com/flutter/flutter/issues/28227
https://github.com/dnfield/flutter_svg/issues/115

**Comment by nullp01nt3r** [comment] 2019-03-02 19:51
@marcglasberg I do not use the `flutter_svg` package, and among the issues that you mentioned, only #28484 _might_ be similar - but in the end really unsure whether there is any connection at all.

**Comment by allandaleho** [comment] 2019-03-14 02:25
Hello @marcglasberg , I am also having this problem and I already moved from beta to master as I initially thought it would fix the problem. Now I'm encountering this even in debug mode.

> $ flutter doctor -v
[✓] Flutter (Channel master, v1.3.10-pre.36, on Mac OS X 10.14 18A391, locale
en-SG)
• Flutter version 1.3.10-pre.36 at
/Users/allandaleho/Documents/Flutter/flutter
• Framework revision eb294a9 (64 minutes ago), 2019-03-13 18:08:57 -0700
• Engine revision 8b1a299ed5
• Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/allandaleho/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling
support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1248-b01)
• All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.1, Build version 10B61
• ios-deploy 2.0.0
• CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 33.3.1
• Dart plugin version 182.5215
• Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 2.24.0

[✓] Connected device (1 available)
• Lena’s iPhone • XXXX • ios • iOS
11.1.2

• No issues found!

**Comment by TahaTesser** [comment] 2020-03-12 10:20
Hi @PiercarloSlavazza  @allandaleho 
Does this issue still exist for you?
Thank you

**Comment by PiercarloSlavazza** [comment] 2020-03-12 10:50
@TahaTesser no more reported since last report- so I would say, on my side, that we can close it.

**Comment by TahaTesser** [comment] 2020-03-12 10:56
Hi @PiercarloSlavazza 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-03-12 10:56 UTC
Labels: a: images, e: device-specific, engine, framework, ▣ platform-android
