### ISSUE TITLE
Windows Hot Restart reverts to older version of app (from the first Hot Restart)

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#60910] opened 2020-07-06 15:38 UTC
I haven't reproduced myself yet as I've not got VS set up for Windows Desktop work (I can't repro using the Android emulator on Windows) but I've seen @BootBlock reproduce it reliably on multiple video calls. He's using:

- Windows 10
- Latest Flutter master branch (`1.20.0-3.0.pre.130`)
- Windows Desktop device
- The default counter app created by `flutter create`

The problem looks like this:

- Run the app
- Make a change to the text (eg. replace with "one") and save (which triggers a hot reload)
- Manually click the Hot Restart action (this restarts the app, and correctly shows "one")
- Change the text again (eg. replace with "two") and save (which triggers a hot reload)
- Manually click the Hot Restart action (this restarts the app, but incorrectly reverts to showing "one")

This happens consistently. Any time you click Hot Restart from this point, it will revert to showing "one". Hot Reload works fine, reflecting the changes being made.

Here is both a full verbose log (including Flutter daemon output, and all VM service traffic) and also a version I've trimmed down to remove some of the stuff I think isn't relevant to this (setLibraryDebuggable spam, ServiceExtensionAdded, etc.).

- [hotRestartLog.txt](https://github.com/flutter/flutter/files/4879886/hotRestartLog.txt)
- [hotRestartLog.trimmed.txt](https://github.com/flutter/flutter/files/4879885/hotRestartLog.trimmed.txt)

This is from the hot restart the fails - I'm not sure if the 0 here is the cause (however this file was known to have been modified and was hot reloaded in successfully between the initial - working - hot restart, and this one):

```
[15:55:45] [FlutterRun] [Error] [        ] Scanning asset files
[15:55:45] [FlutterRun] [Error] [        ] <- reset
[15:55:45] [FlutterRun] [Error] [        ] Compiling dart to kernel with 0 updated files
[15:55:45] [FlutterRun] [Error] [        ] <- recompile package:bugtest/main.dart 26f89a78-d949-494f-845c-86bcaa413fa9
[15:55:45] [FlutterRun] [Error] [        ] <- 26f89a78-d949-494f-845c-86bcaa413fa9
```

(@jonahwilliams if there's anywhere we can add extra logging to temporarily to track this down, let me know - we can easily modify the source locally on @BootBlock's machine and redo)

**Comment by DanTup** [comment] 2020-07-06 15:38
> This is from the hot restart the fails - I'm not sure if the 0 here is the cause

Actually, the successful hot restart also had that, so maybe unrelated. It's only the hot reloads that have non-zero values there.

**Comment by jonahwilliams** [comment] 2020-07-06 16:17
The 0 is expected from hot restart, but I've definitely seen odd behavior from windows desktop on my own PC. Usually hot reload works until the first hot restart, and then subsequent hot reloads/restarts do nothing. I suspect the problem is not with compilation, but with the runFromSource VM service API (implemented by the flutter engine). Since this API accepts a file path and windows is the only runner we have without a posix file API.

**Comment by jonahwilliams** [comment] 2020-07-06 16:17
I'm tentatively marking this as tools and engine since the fix might involve both

**Comment by jonahwilliams** [comment] 2020-07-12 02:33
I looked into this some more and confirmed that the compilation artifacts are correctly up to date, so it seems to be a problem in either the engine or (less likely) dart_vm in loading once it is running from the devFS

**Comment by jonahwilliams** [comment] 2020-08-04 21:53
Removing tool designation since the artifacts look correct from the tool side.

**Comment by jonahwilliams** [comment] 2020-09-07 23:55
I still think this is ultimately an issue with the engine/vm service, but we can work around this at the tool level.

 it seems like the timing for the upload of the new application dill is done when the old dill is still open by the embedder, so that hits file lock behavior which Is unique to windows. I never got a stack trace to confirm this, but I observed that uploading the new application dill with a different name causes everything to work as normal.

This doesn't happen on the first hot restart, since that is when we switch from the bundled dill to the devfs.

A workaround would be to always upload the dill with a new name. On non-windows devices this risks polluting the devfs, which might have more limited space. There doesn't appear to be a devFS api to delete a single file, but adding that or having the embedder delete the old dill if it loads a newly named one in runFromSource might fix that.

**Comment by jonahwilliams** [comment] 2020-09-09 00:15
so its not a file read lock, its actually just protection for the memory mapping the engine sets up

**Closed** 2020-09-09 22:56 UTC
Labels: P4, engine, platform-windows, tool
