### ISSUE TITLE
Swiper Widget Gives Error When 'Loop' Property is Set to True and Amount of Pages in Swiper are Adjusted: '..\…\widgets\scroll_controller.dart:108 _positions.isNotEmpty "ScrollController not attached to any scroll views."'

### ISSUE THREAD

**Issue by jeffreywolberg** [flutter/flutter#83362] opened 2021-05-25 18:21 UTC
Hi,
I am trying to build an app that involves swiping pages. Depending on the circumstance in the app, there are either 3 or 4 pages in this swiper, and it can change pretty often. I want to be able to swipe through the pages (including wrapping around from the last to the first and vice versa), and I also want my app to be able to add/subtract a page in the swiper when needed. However, when running my app, I would be able to scroll left and right as much as I wanted (including having the pages wrap around once I reached the last/first), yet when the amount of pages in the swiper changed, my app threw an error.

I am using the flutter_swiper: ^1.1.6 package for this, as specified in my pubspec.yaml file. I am using flutter version 1.25.0-8.3.pre.

Here is a minimal runnable reproduction of my code that reproduces this error:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_swiper/flutter_swiper.dart';

void main() => runApp(SwiperTestApp());

class SwiperTestApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Test App', home: MainPage());
  }
}

class MainPage extends StatefulWidget {
  @override
  _MainPageState createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> {
  SwiperController swiperController = SwiperController();
  bool expand = false;
  int nOrigPages = 3;
  int nExpandedPages = 4;
  SwiperController swiperController = SwiperController();
  @override
  Widget build(BuildContext context) {
    MediaQueryData mediaQuery = MediaQuery.of(context);
    return Column(children: [
      Container(
        height: mediaQuery.size.height / 2,
        width: mediaQuery.size.width,
        child: Swiper(
          loop: false, // IF YOU UNCOMMENT THIS LINE IT WORKS
          itemBuilder: (BuildContext context, int index) {
            return Container(
                child: Center(
              child: Text("$index"),
            ));
          },
          itemCount: expand ? nExpandedPages : nOrigPages,
          pagination: SwiperPagination(),
          controller: swiperController,
        ),
      ),
      RaisedButton(
          color: Colors.white,
          child: Text("Toggle expand"),
          onPressed: () {
            setState(() {
              expand = !expand;
            });
          }),
    ]);
  }
}
```

You should get the error below when looping around and trying to change the amount of pages in the swiper. The error is:
'..\…\widgets\scroll_controller.dart:108
_positions.isNotEmpty
"ScrollController not attached to any scroll views."'

The full error, along with the stack, is this:
═══════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Swiper(dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#6a408]], state: _SwiperState#6fb34):
Assertion failed:
..\…\widgets\scroll_controller.dart:108
_positions.isNotEmpty
"ScrollController not attached to any scroll views."

The relevant error-causing widget was
Swiper
lib\widgets\swiper.dart:48
When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 231:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
packages/flutter/src/widgets/scroll_controller.dart 108:23                                                                 get position
packages/flutter/src/widgets/page_view.dart 200:41                                                                         animateToPage
packages/transformer_page_view/transformer_page_view.dart 527:25                                                           didUpdateWidget
...
════════════════════════════════════════════════════════════════════════════════
Exited (1)

I am not sure what this means, and I don't know where I would insert a ScrollController.

I figured out that by setting the 'loop' property in my Swiper widget to false (thus restricting the ability to loop around my swiper), this error wouldn't arise, and everything worked fine. Also note that when I switched from 4 pages to 3 pages while I was viewing the 4th page, it automatically went to the 3rd page, which is desired behavior. However, it is inconvenient to not be able to loop around. I attached two videos below demonstrating this issue.

Videos:
-With Looping:
    https://user-images.githubusercontent.com/54825193/119544603-dcddd380-bd5f-11eb-8037-920467f08cad.mp4
-Without Looping:
    https://user-images.githubusercontent.com/54825193/119544563-d2233e80-bd5f-11eb-8435-bb632369c503.mp4

The question is, how do I give my app the ability to loop around the swiper pages while being able to adjust the amount of pages in the swiper without flutter throwing an error?

Lastly, here is my flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (2 available)

• No issues found!

Any assistance is greatly appreciated.

Thanks,
Jeffrey

**Comment by TahaTesser** [comment] 2021-05-26 08:02
Hi @jeffreywolberg 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/best-flutter/flutter_swiper/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-26 08:02 UTC
Labels: in triage

**Comment by jeffreywolberg** [comment] 2021-05-30 18:41
Found out how to solve it: Within the Swiper Widget pass in a key as a property that is different between the two swipers. This way they won't overlap, and Flutter will create two distinct swiper widgets in memory.
