### ISSUE TITLE
Flutter looking for sdkmanager in the wrong directory

### ISSUE THREAD

**Issue by Yakimych** [flutter/flutter#52209] opened 2020-03-08 20:24 UTC
## Steps to Reproduce

1. Install flutter according to the steps in https://flutter.dev/docs/get-started/install/macos
2. Install Android Studio, SDK Manager, etc.
3. Run `flutter doctor`

```
Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
```
4. Run `flutter doctor --android-licenses`
```
Android sdkmanager tool not found
(/Users/yakimych/Library/Android/sdk/tools/bin/sdkmanager).
```

This is not surprising, since sdkmanager is in `/Users/yakimych/Library/Android/sdk/cmdline-tools/latest/bin`. Is there a way to set this directory instead of the one flutter is looking into?

## Logs

```
$ flutter doctor -v --android-licenses
Android sdkmanager tool not found (/Users/yakimych/Library/Android/sdk/tools/bin/sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      AndroidLicenseValidator.runLicenseManager
(package:flutter_tools/src/android/android_workflow.dart:311:7)
#2      Doctor.diagnose (package:flutter_tools/src/doctor.dart:243:38)
#3      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#4      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:615:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-SE)
    • Flutter version 1.12.13+hotfix.8 at /Users/yakimych/flutter/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/yakimych/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 96571891-AD8E-45BC-BE8E-3B6C3C72D43C • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment] 2020-03-08 20:40
Duplicate of https://github.com/flutter/flutter/issues/51712

**Closed by jonahwilliams** 2020-03-08 20:40 UTC
