### ISSUE TITLE
[google_maps_flutter][android] v2.0.10 unchecked cast build warning

### ISSUE THREAD

**Issue by lukaskurz** [flutter/flutter#90969] opened 2021-09-29 17:23 UTC
## Steps to Reproduce

1. Add `google_maps_flutter:^2.0.10` as dependency
2. Run `flutter build appbundle` or just run the app with the debugger in vscode
3. Be presented with warnings during first build or when clean has been called before

**Expected results:** 
No build warnings :sweat_smile: 

**Actual results:** 
With enabled "-Xlint:unchecked" for more verbose warning output.
First warning is related to #70923

```
/home/lukaskurz/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java:27: warning: [deprecation] FlutterMain in io.flutter.view has been deprecated
import io.flutter.view.FlutterMain;
                      ^
/home/lukaskurz/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/TileProviderController.java:78: warning: [unchecked] unchecked cast
      result = (Map<String, ?>) data;
                                ^
  required: Map<String,?>
  found:    Object
2 warnings
```

<details>

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.0, on Fedora 31 (Workstation Edition) 5.8.18-100.fc31.x86_64, locale en_US.UTF-8)
    • Flutter version 2.5.0 at /usr/share/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/lukaskurz/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/lukaskurz/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/lukaskurz/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /home/lukaskurz/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /home/lukaskurz/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

</details>

this is similar to #90811

**Comment by lukaskurz** [comment] 2021-09-29 17:25
I have already prepared a PR for #90811,  if you want, I can write one for this too, since this does not seem to complicated :sweat_smile:

**Comment by maheshmnj** [comment] 2021-09-30 08:17
Hi @lukaskurz, Thanks for filing the issue. I tried building the app bundle on the master and stable channel `2.5.1`  using the  `google maps plugin: 2.0.10` but did not see any such warning could you please try upgrading to latest `stable 2.5.1`

Could you please try switching to master and see if that reproduces for you by running 

```
flutter upgrade
cd <path to project> && flutter clean
```

<details>
<summary>logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 example % flutter build appbundle

💪 Building with sound null safety 💪

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Note: /Users/mahesh/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/mahesh/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/TileProviderController.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Removed unused resources: Binary resource data reduced from 122KB to 96KB: Removed 20%
Running Gradle task 'bundleRelease'...                             89.7s
✓ Built build/app/outputs/bundle/release/app-release.aab (16.8MB).
mahesh@Maheshs-MacBook-Air-M1 example % 
```
</details>


<details>
<summary>flutter doctor -v</summary>


```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.136, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.136 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aaa14b8004 (22 hours ago), 2021-09-29 06:03:04 -0400
    • Engine revision bccb3a57eb
    • Dart version 2.15.0 (build 2.15.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone X (mobile)         • B6C32C16-12A3-4613-9ADF-8C521ACD6302 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone X (mobile)         • B6C32C16-12A3-4613-9ADF-8C521ACD6302 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
</details>

**Comment by lukaskurz** [comment] 2021-09-30 12:10
Hi @maheshmnj, I wasn't aware 2.5.1 was already out :smile: 
I just upgraded to `2.5.1` using `flutter upgrade` and the build warnings still persist.

Note: I think you do have the same errors as me, your're just seeing them in a less verbose output, since you don't have the `"-Xlint:unchecked" ` compiler option on.

In your logs its this:
```
Note: /Users/mahesh/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/mahesh/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/TileProviderController.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

You can add them in your project level build.gradle file, so you get more info on the warnings

```
allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:deprecation"
            options.compilerArgs << "-Xlint:unchecked"
        }
    } 
    repositories {
        google()
        jcenter()
    }
}
```

Also here are my logs for 2.5.1, just for completeness' sake :sweat_smile: 

<details>
<summary>Logs</summary>

```
➜ flutter clean && flutter build appbundle
Deleting build...                                                  109ms
Deleting .dart_tool...                                               6ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in flutter...                            856ms

💪 Building with sound null safety 💪

/home/lukaskurz/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java:27: warning: [deprecation] FlutterMain in io.flutter.view has been deprecated
import io.flutter.view.FlutterMain;
                      ^
/home/lukaskurz/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/TileProviderController.java:78: warning: [unchecked] unchecked cast
      result = (Map<String, ?>) data;
                                ^
  required: Map<String,?>
  found:    Object
2 warnings
/home/lukaskurz/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+2/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java:220: warning: [unchecked] unchecked cast
    ArrayList<String> pathList = (ArrayList<String>) resultMap.get(cache.MAP_KEY_PATH_LIST);
                                                                  ^
  required: ArrayList<String>
  found:    Object
1 warning
/home/lukaskurz/.pub-cache/hosted/pub.dartlang.org/launch_review-3.0.1/android/src/main/java/com/iyaffle/launchreview/LaunchReviewPlugin.java:11: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
/home/lukaskurz/.pub-cache/hosted/pub.dartlang.org/launch_review-3.0.1/android/src/main/java/com/iyaffle/launchreview/LaunchReviewPlugin.java:41: warning: [deprecation] Registrar in PluginRegistry has been deprecated
    public static void registerWith(Registrar registrar) {
                                    ^
2 warnings
Removed unused resources: Binary resource data reduced from 902KB to 839KB: Removed 7%
Running Gradle task 'bundleRelease'...                             59.1s
✓ Built build/app/outputs/bundle/release/app-release.aab (27.8MB).
```

</details>

<details>
<summary>flutter doctor</summary>

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.1, on Fedora 31 (Workstation Edition) 5.8.18-100.fc31.x86_64, locale en_US.UTF-8)
    • Flutter version 2.5.1 at /usr/share/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/lukaskurz/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/lukaskurz/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/lukaskurz/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /home/lukaskurz/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /home/lukaskurz/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2021-09-30 13:12
@lukaskurz thanks for the clarification. I was able to reproduce it on the stable and the master channel with 
google_maps_flutter: ^2.0.10 

```console
mahesh@Maheshs-MacBook-Air-M1 sample % flutter build appbundle

💪 Building with sound null safety 💪

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
/Users/mahesh/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java:27: warning: [deprecation] FlutterMain in io.flutter.view has been deprecated
import io.flutter.view.FlutterMain;
                      ^
/Users/mahesh/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-2.0.10/android/src/main/java/io/flutter/plugins/googlemaps/TileProviderController.java:78: warning: [unchecked] unchecked cast
      result = (Map<String, ?>) data;
                                ^
  required: Map<String,?>
  found:    Object
2 warnings
Removed unused resources: Binary resource data reduced from 112KB to 87KB: Removed 21%
Running Gradle task 'bundleRelease'...                             43.5s
✓ Built build/app/outputs/bundle/release/app-release.aab (16.3MB).
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30)
      (emulator)
    • iPhone X (mobile)         • B6C32C16-12A3-4613-9ADF-8C521ACD6302 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.6 20G165
      darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome
      94.0.4606.61

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.136, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.136 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aaa14b8004 (22 hours ago), 2021-09-29 06:03:04 -0400
    • Engine revision bccb3a57eb
    • Dart version 2.15.0 (build 2.15.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30)
      (emulator)
    • iPhone X (mobile)         • B6C32C16-12A3-4613-9ADF-8C521ACD6302 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.6 20G165
      darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome
      94.0.4606.61

• No issues found!
```
</details>

Thanks

**Comment by maheshmnj** [comment] 2021-09-30 13:12
> I have already prepared a PR for #90811, if you want, I can write one for this too, since this does not seem to complicated 😅

That would be great :)

**Comment by maheshmnj** [comment] 2021-11-23 11:30
Since this has been https://github.com/flutter/plugins/pull/4409 merged I believe this is safe to close.
If anyone disagrees feel free to comment and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-11-23 11:30 UTC
Labels: platform-android, plugin, p: first party, p: maps, good first contribution, has reproducible steps, P4, found in release: 2.5, found in release: 2.6
