### ISSUE TITLE
Lost connection to device.   

### ISSUE THREAD

**Issue by believejava** [flutter/flutter#58015] opened 2020-05-26 15:59 UTC
**1. when I run "flutter doctor -v"**
```console
huangweipeng@huangweipengs-MacBook-Pro colorful_classroom_app % flutter doctor -v
[✓] Flutter (Channel master, 1.19.0-2.0.pre.143, on Mac OS X 10.15.4 19E287, locale en-HK)
    • Flutter version 1.19.0-2.0.pre.143 at /Users/huangweipeng/Documents/development/flutter
    • Framework revision 9d58a87066 (3 days ago), 2020-05-22 22:37:01 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/huangweipeng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (4 available)
    • iPhone 11  • 52DBB86C-B59B-408E-B946-D85A7238A8DF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

**2. when run "flutter run -d 52DBB86C-B59B-408E-B946-D85A7238A8DF"**
the log as below,
```bash
huangweipeng@huangweipengs-MacBook-Pro colorful_classroom_app % flutter run -d 52DBB86C-B59B-408E-B946-D85A7238A8DF
Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                         8.0s
Xcode build done.                                           18.3s
Waiting for iPhone 11 to report its views...                         3ms
Lost connection to device.                                              
Syncing files to device iPhone 11...      
```

**Comment by iapicca** [comment] 2020-05-27 08:50
Hi @believejava 
does the issue occur with other virtual or physical devices?
If so could you please provide you full `flutter run --verbose`
Thank you

**Comment by dev-aentgs** [comment] 2020-05-27 18:40
@iapicca  came across this [stackoverflow question](https://stackoverflow.com/questions/62045297/app-crease-after-use-flutter-1-17-1-in-android-in-reales-mode/62045714?noredirect=1#comment109744493_62045714) , **Lost connection to device** is in the logs.  
The user mentioned app worked on  **flutter 1.12.13+hotfix.9**  but started crashing on **flutter 1.17.1**

**Comment by AngusPei** [comment] 2020-05-28 11:13
same issue..
```
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-US)
    • Flutter version 1.19.0-1.0.pre at /Users/angus/flutter
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/angus/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • iPhone XR  • 9F07CB2E-9E7D-4D18-B78E-E980F0D3BFF8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-12-1 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.4 19E287
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 83.0.4103.61
```

**Comment by TheVinhLuong** [comment] 2020-05-29 15:28
I have exactly the same issue
```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by TheVinhLuong** [comment] 2020-05-30 02:20
Turns out the cause is because of `extension FlutterViewController` inside `AppDelegate.swift`. After removing it the crash is no more.

**Comment by TahaTesser** [comment] 2020-06-17 12:11
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-17 12:11 UTC
Labels: in triage, waiting for customer response
