### ISSUE TITLE
Rendering issue in Android emulator on macOS

### ISSUE THREAD

**Issue by aubykhan** [flutter/flutter#11795] opened 2017-08-27 11:22 UTC
## Issue
Getting strange rendering behavior for floating action button on Android emulator while it works fine on a physical device. The screens shows just fine on iOS emulator though. I get an error in console too:
```
E/flutter ( 2605): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(189)] WARNING: Could not create offscreen surface. This device or emulator does not support color correct rendering. Fallbacks are in effect. Colors on this device will differ from those displayed on most other devices. This warning will only be logged once.
```
![Android missing FAB icon](https://github.com/aubykhan/blogger/blob/master/Screenshot_1503831763.png)

## Code
```dart
class UICheckScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: const Text('UI Check'),
      ),
      body: const Center(
        child: const Text('This is UI check body'),
      ),
      floatingActionButton: new FloatingActionButton(
        child: const Icon(Icons.send),
        onPressed: () {},
      ),
    );
  }
}
```

## Possible cause
I remember I connected my mac to a projector for a presentation. It worked fine there but after that, Android emulator seems to catch up with some strange bug.

**Comment by Hixie** [comment] 2017-08-29 20:48
This might be fixed now if it was caused by the recent Skia bug with rendering text (#11475). Can you check if your app works on the master channel today?

**Comment by sclee15** [comment] 2017-08-30 04:12
I have same error log
and i tried latest master version of flutter and i found that this is still happening

Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision def0b4203a (23 minutes ago) • 2017-08-29 20:34:30 -0700
Engine • revision f9e00a7c72
Tools • Dart 1.25.0-dev.11.0

**Comment by rogchap** [comment] 2017-11-07 10:34
I have a similar issue that text does not show up on the RaisedButton widget.

**Comment by Hixie** [comment] 2018-05-24 19:20
We believe this is now fixed. If you still see this please file a new bug and include as much information as possible about your setup. Thanks.

**Closed by Hixie** 2018-05-24 19:20 UTC
Labels: waiting for customer response, ▣ platform-android
