### ISSUE TITLE
@mustCallSuper should work with inheritance hierarchies 

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#25097] opened 2018-12-07 19:58 UTC
We ran into an issue with keep alives not working. We were using the `AutomaticKeepAliveClientMixin` in an abstract `State` class. Because of the `@mustCallSuper` annotation, we knew to call `super.build` in the `build` method of the abstract class. However, there was no warning for the fact that we weren't calling `super.build` in the concrete implementations of our abstract `State` class.

I can't envision a case where you wouldn't want the annotation to extend to all transitive subclasses.

**Comment by zoechi** [comment] 2018-12-09 15:45
I think this should be reported in dart-lang/sdk or dart-lang/linter

**Comment by alanrussian** [comment] 2018-12-10 19:39
Thanks. Filed https://github.com/dart-lang/sdk/issues/35372

**Comment by zoechi** [comment] 2018-12-10 20:18
Duplicate of dart-lang/sdk#35372

**Closed by zoechi** 2018-12-10 20:18 UTC
Labels: customer: mulligan (g3), dependency: dart
