### ISSUE TITLE
[tool_crash] SessionNotCreatedException

### ISSUE THREAD

**Issue by btsuro** [flutter/flutter#148533] opened 2024-05-17 07:41 UTC
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/test.dart -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SessionNotCreatedException
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:81:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:155:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:323:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.2, on macOS 14.5 23F79 darwin-arm64, locale en-ZW)
    [32m•[39m Flutter version 3.19.2 on channel stable at /Users/benjamintsuro/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 7482962148 (3 months ago), 2024-02-27 16:51:22 -0500
    [32m•[39m Engine revision 04817c99c9
    [32m•[39m Dart version 3.3.0
    [32m•[39m DevTools version 2.31.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/benjamintsuro/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15F31d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[32m[✓][39m VS Code (version 1.89.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.60

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
integration_test
path_provider-2.0.14
path_provider_android-2.0.25
path_provider_foundation-2.2.2
path_provider_linux-2.1.11
path_provider_windows-2.1.7
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
sqflite-2.2.6
url_launcher-6.2.5
url_launcher_android-6.3.0
url_launcher_ios-6.2.5
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.3
url_launcher_windows-3.1.1

**Comment by danagbemava-nc** [comment] 2024-05-17 08:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/141010

**Closed by danagbemava-nc** 2024-05-17 08:40 UTC
Labels: in triage
