### ISSUE TITLE
test_driver/scroll_perf.dart is flaky

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6256] opened 2016-10-10 18:08 UTC
I ran it three times. One time it said it timed out waiting for the app. A second time it worked fine. A third time it said:

```
$ flutter drive --profile test_driver/scroll_perf.dart
Using device Nexus 6.
Starting application: lib/main.dart
Building APK in profile mode (android-arm-profile)...
Warning: signing the APK using the debug keystore.
Built build/app.apk (12.7MB).
Observatory listening on http://127.0.0.1:8183
00:00 +0: scrolling performance test (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://localhost:8183
[trace] FlutterDriver: Looking for the isolate
00:00 +0 -1: scrolling performance test (setUpAll)
  Bad state: No element
  dart:core                                               List.first
  package:flutter_driver/src/driver.dart 85:43            FlutterDriver.connect.<async>
  dart:async                                              _SyncCompleter.complete
  package:vm_service_client/vm_service_client.dart 207:7  VMServiceClient.getVM.<async>
  dart:async                                              _SyncCompleter.complete
  package:json_rpc_2/src/client.dart 175:25               Client._handleSingleResponse
  package:json_rpc_2/src/client.dart 165:7                Client._handleResponse
  dart:async                                              _StreamController.add
  package:json_rpc_2/src/peer.dart 92:36                  Peer.listen.<fn>
  ===== asynchronous gap ===========================
  dart:async                                              _Completer.completeError
  package:flutter_driver/src/driver.dart 188:3            FlutterDriver.connect.<async>
  dart:async                                              _SyncCompleter.complete
  package:vm_service_client/vm_service_client.dart 207:7  VMServiceClient.getVM.<async>
  dart:async                                              _SyncCompleter.complete
  package:json_rpc_2/src/client.dart 175:25               Client._handleSingleResponse
  package:json_rpc_2/src/client.dart 165:7                Client._handleResponse
  dart:async                                              _StreamController.add
  package:json_rpc_2/src/peer.dart 92:36                  Peer.listen.<fn>
  ===== asynchronous gap ===========================
  dart:async                                              _asyncThenWrapperHelper
  package:flutter_driver/src/driver.dart                  FlutterDriver.connect
  test_driver/scroll_perf_test.dart 14:36                 main.<fn>.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async                                              Future.Future.microtask
  test_driver/scroll_perf_test.dart                       main.<fn>.<fn>

00:00 +0 -1: scrolling performance test (tearDownAll)
00:00 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1138)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Stopping application instance.
```

cc @yjbanov

**Comment by eseidelGoogle** [comment] 2016-10-19 21:05
Should this be in "Today"?

**Comment by yjbanov** [comment] 2016-10-19 21:50
@Hixie which `scroll_perf.dart` is this referring to? We have a few ([1](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/test_driver/scroll_perf.dart), [2](https://github.com/flutter/flutter/blob/master/examples/stocks/test_driver/scroll_perf.dart), [3](https://github.com/flutter/flutter/blob/master/dev/benchmarks/complex_layout/test_driver/scroll_perf.dart)). We only run `complex_layout/test_driver/scroll_perf.dart` on the devicelab on a regular basis, and the build history [looks very stable](https://flutter-dashboard.appspot.com/build.html). If the flaky test is one we're not running regularly, we should probably remove it as it's probably bitrotten by now.

**Comment by Hixie** [comment] 2016-10-19 22:07
This was referring to "Scroll perf (complex_layout)" on our dashboard. It's in "Today" because it means the dashboard is broken and we are unable to notice when we regress performance.

**Comment by yjbanov** [comment] 2016-10-19 22:11
I see that we are failing to record the frames (or perhaps there really is only one frame). We should definitely fix that. However, I'm not seeing flakiness or the stacktrace that looks like the one in the original bug report.

How about we close this issue (unless anyone can still reproduce it) and open a new one to fix the missing frame data?

**Comment by Hixie** [comment] 2016-10-19 22:14
So long as the dashboard gets fixed, I don't mind what bug tracks it. :-)

We should probably also have a bug to track the flakiness of the benchmark when run locally, though.

**Comment by eseidelGoogle** [comment] 2016-11-04 18:05
This has made no movement in "Today" for 25 days, that doesn't seem right.  Removing the milestone.

**Comment by eseidelGoogle** [comment] 2017-02-08 22:47
@goderbauer fixed a bunch of flakes last month.  Unclear if that affected this?

**Comment by goderbauer** [comment] 2017-02-08 23:42
On the dashboard, this test is passing every single run.

**Comment by zanderso** [comment] 2019-07-23 16:38
This issue appears stale. Closing.

**Closed by zanderso** 2019-07-23 16:38 UTC
Labels: a: tests, severe: regression, team: flakes, tool
