### ISSUE TITLE
Integration test passes even though the displayed text is CROPPED

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#37189] opened 2019-07-29 19:16 UTC
If we use SerializableFinder find.text, the finder still gets the complete text even though the displayed text is cropped. Maybe because the text attribute in flutter inspector is still the entire string?

 Is there a workaround in order to FAIL the test if the displayed text is cropped?

**Comment by escamoteur** [comment] 2019-09-20 16:47
Is this still a problem?

**Comment by snickersv2** [comment] 2019-09-20 16:50
@escamoteur yes

**Comment by jonahwilliams** [comment] 2020-04-25 20:46
flutter_driver and flutter_test do not check if widgets are partially offscreen. If you want to verify exact matches, you could look at scuba/screenshot testing functionality, or perhaps look at comparing the element rects to see if they are offscreen.

Closing since this is not a bug.

**Closed by jonahwilliams** 2020-04-25 20:46 UTC
Labels: a: tests, d: stackoverflow, tool
