### ISSUE TITLE
ios selection control ui overflow if the user selects big text size

### ISSUE THREAD

**Issue by binSaed** [flutter/flutter#144514] opened 2024-03-03 11:37 UTC
### Steps to reproduce

1-run code sample
2- change ios display text size to a bigger one

### Expected results

should show perfectly

### Actual results

overflow

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Test')),
        body: const TextField(),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![IMG_7019](https://github.com/flutter/flutter/assets/33700292/20532455-659b-414f-bf73-8598428bc678)
![IMG_7020](https://github.com/flutter/flutter/assets/33700292/be320191-26b4-4782-afa3-ff83754b6419)

</details>

### Logs

.

### Flutter Doctor output

.

**Comment by danagbemava-nc** [comment] 2024-03-04 09:32
Hi @binSaed, what version of flutter are you using? If you're not using the latest version of flutter stable (3.19.2), I suggest you upgrade to that version. I just tested with the largest possible text size it could be on iOS and there is no overflow. I tested at various other large sizes too with no overflow. See the screenshot below 

<img src="https://github.com/flutter/flutter/assets/88313112/f27c5308-e2ce-4c45-9cdd-4f5b81f9581a" width="300"/>

**Comment by binSaed** [comment] 2024-03-04 14:50
Flutter version is 3.13.9
Is there any workaround instead of upgrading our flutter version?
Currently we haven't time to upgrade flutter and upgrade dependencies 

@danagbemava-nc

**Comment by danagbemava-nc** [comment] 2024-03-05 06:14
Unfortunately, you will have to upgrade to the latest version of the framework. There are no workarounds that I am aware of. 

Based on the fact that you're using an older version of the framework and I cannot reproduce this on the latest version, I will be closing this issue. 

If you do run into this issue on the latest version of flutter, kindly leave a comment below and I will reopen this.

Thank you

**Closed by danagbemava-nc** 2024-03-05 06:14 UTC
Labels: in triage
