### ISSUE TITLE
flutter_plugin_tools 'format' doesn't work on Windows

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#65773] opened 2020-09-14 17:58 UTC
I opened this issue on melos: https://github.com/invertase/melos/issues/11 but it appears to be a problem with `flutter_plugin_tools` instead.

Running the melos format command on IntelliJ IDEA on Windows 10, I get this output:

![image](https://user-images.githubusercontent.com/8120472/93121061-a8772b00-f69a-11ea-991b-39eafc3f75da.png)

Which isn't very meaningful.

**Comment by stuartmorgan** [comment] 2020-09-14 22:04
What about this do you find illegible/not meaningful? It's showing you the command it tried to run (`flutter format [...]`), and the OS error that resulted from trying to run that command (`CreateProcessW failed 2` being the error code, and `The system cannot find the file specified` being the corresponding error string).

It sounds like Flutter isn't installed, or at least isn't in the path.

**Comment by feinstein** [comment] 2020-09-14 22:14
`flutter` is installed and on the path.

I thought that output was a result, not the command itself, so I don't know what could be wrong then or which file it's complaining. 

Melos is developed in a Mac and I guess I am the only Windows user so far, so I guess this could be an incompatibility?

**Comment by stuartmorgan** [comment] 2020-09-14 22:25
> or which file it's complaining

If you're getting error 2 from `CreateProcessW` that means the thing it tried to run--`flutter`, here--wasn't found. Maybe something is going wrong with the PATH somewhere along the way, or maybe this is a `flutter`/`flutter.bat` mismatch issue (i.e., maybe `flutter_plugin_tools format` is currently written in such a way that it doesn't work on Windows).

**Comment by feinstein** [comment] 2020-09-14 22:29
interesting I will forward this to the melos team.

**Comment by PixelToast** [comment] 2020-09-14 22:55
This does seem to be a bug with the `flutter_plugin_tools` package, it calls `Process.start('flutter', [...])` which doesn't work on windows because `flutter` is not an executable, it's a batch file.

One way to handle this on windows is to do `Process.start('cmd', ['/c', 'flutter', ...])`.

**Comment by PixelToast** [comment] 2020-09-14 22:57
melos also doesn't seem to support windows properly either:

https://github.com/invertase/melos/blob/96ffffd515e182d9136fdee00bcd0d45b64e422a/lib/src/common/workspace.dart#L193

**Comment by stuartmorgan** [comment] 2020-09-14 23:57
> This does seem to be a bug with the `flutter_plugin_tools` package

Windows support for the `flutter_plugin_tools` `format` command is a reasonable feature request, but I would recommend that anyone interested in it submit a PR; if the repos that package are primarily intended to support aren't running `format` on Windows, it's not going to be a priority.

> One way to handle this on windows is to do `Process.start('cmd', ['/c', 'flutter', ...]`).

Usually Flutter tooling use a `Platform` switch to decide whether to use `foo` or `foo.bat` as a command to address this problem (which is what my comment about "`flutter`/`flutter.bat` was about).

**Comment by PixelToast** [comment] 2020-09-15 00:06
Ahhhh, I didn't realize you could Process.run a batch file

**Comment by stuartmorgan** [comment] 2021-07-08 18:03
Duplicate of https://github.com/flutter/flutter/issues/33964

**Closed** 2021-07-13 01:09 UTC
Labels: P4, p: tooling, passed first triage, platform-windows, plugin
