### ISSUE TITLE
All flutter commands fails with integrity error on Catalina

### ISSUE THREAD

**Issue by aboodman** [flutter/flutter#38606] opened 2019-08-15 05:59 UTC
I upgraded to Catalina, and all flutter commands started failing like so:

```
flutter doctor -v
```

Then I get this error dialog from OSX:

<img width="414" alt="Screen Shot 2019-08-14 at 7 58 15 PM" src="https://user-images.githubusercontent.com/80388/63075577-e8834180-becd-11e9-9e66-05ab470e8741.png">

Halp?

**Comment by dnfield** [comment] 2019-08-15 06:22
Duplicate of https://github.com/flutter/flutter/issues/36714

**Closed by dnfield** 2019-08-15 06:22 UTC

**Comment by aboodman** [comment] 2019-08-15 06:30
Sorry, I did search the issues for the text in the dialog, but it doesn't appear in that bug report.

**Comment by dnfield** [comment] 2019-08-15 06:34
No worries - it's hard to find things in here sometimes :)
