### ISSUE TITLE
run "flutter install", get error

### ISSUE THREAD

**Issue by carly1987** [flutter/flutter#25506] opened 2018-12-18 12:25 UTC
run `flutter install`, return
``` 
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries,
res=-113]
```
my build.gradle for android:
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new Exception("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.");
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutterdemo1"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        ndk { abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips64', 'mips64', 'mips' }
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

     splits {
         abi {
             enable true
             reset()
             include 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips64', 'mips64', 'mips'
             universalApk true
         }
     }

}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```

**Comment by zoechi** [comment] 2018-12-18 12:49
Duplicate of #8824

**Comment by zoechi** [comment] 2018-12-18 12:50
Also related #6864, #6136, #7539, #5592

**Comment by carly1987** [comment] 2018-12-19 03:43
> Also related #6864, #6136, #7539, #5592

I can run "flutter build apk --release", it is success,
my problem is "flutter install" is fail, i just want to install the apk in my deveice. and my device's cpu is arm64-v8a.  please help me to fix it ~

**Comment by carly1987** [comment] 2018-12-19 03:56
> Also related #6864, #6136, #7539, #5592

run "flutter build apk --release", I check the result build is right. 
app-arm64-v8a-release.apk
app-armeabi-release.apk
app-armeabi-v7a-release.apk
app-x86_64-release.apk
app-x86-release.apk
...

my problem just is "Installing a release APK on a device", i follow this document : https://flutter.io/docs/deployment/android

**Comment by zoechi** [comment] 2018-12-19 06:06
Please add the output of `flutter doctor -v` with the device in question connected.

**Comment by carly1987** [comment] 2018-12-19 06:18
> Please add the output of `flutter doctor -v` with the device in question connected.

![image](https://user-images.githubusercontent.com/4493524/50202402-f9a89c80-0398-11e9-89a4-8058f8a5aada.png)

**Comment by carly1987** [comment] 2019-01-09 09:35
When can I fix this problem or give a solution?

**Comment by zoechi** [comment] 2019-01-09 09:43
> with the device in question connected.

The flutter doctor output above has an emulator connected.

Above you mentioned

>  i just want to install the apk on my deveice. and my device's cpu is arm64-v8a

**Comment by carly1987** [comment] 2019-01-14 06:09
> > with the device in question connected.
> 
> The flutter doctor output above has an emulator connected.
> 
> Above you mentioned
> 
> > i just want to install the apk on my deveice. and my device's cpu is arm64-v8a

thx, I had installed.

**Comment by zoechi** [comment] 2019-01-14 07:17
It's unclear what the status of this issue is now?

Is there still an issue?
What exactly is the issue?
If there is still an issue, please connect the device you can reproduce the issue with and post the output of `flutter doctor -v` as text.

**Comment by zoechi** [comment] 2019-02-07 18:47
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-02-07 18:47 UTC
Labels: severe: crash, tool, waiting for customer response
