### ISSUE TITLE
FileSystemException: FileSystemException: Cannot create file, path = 'C:\Users\adil rehman\Documents\codecanyon-28508826-flutter-multi-city-directory-city-tour-guide-business-directory-travel-guide-booking-10\Flutter-Multi-City(v_1.0)\Mobile Source\Flutter-Multi-City\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: The system cannot find the path specified. , errno = 3)

### ISSUE THREAD

**Issue by adilwahla** [flutter/flutter#68440] opened 2020-10-18 13:40 UTC
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color pub upgrade

## exception

FileSystemException: FileSystemException: Cannot create file, path = 'C:\Users\adil rehman\Documents\codecanyon-28508826-flutter-multi-city-directory-city-tour-guide-business-directory-travel-guide-booking-10\Flutter-Multi-City(v_1.0)\Mobile Source\Flutter-Multi-City\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: The system cannot find the path specified.
, errno = 3)

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:26:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:660:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1147:11)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:263:11)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:127:23)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.20.4 at C:\Users\adil rehman\Documents\flutterSdk\flutter
    • Framework revision fba99f6cf9 (5 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\adil rehman\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.42.1)
    • VS Code at C:\Users\adil rehman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • CPH1809 (mobile) • 25cfa711 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by Abhishek01039** [comment] 2020-10-18 15:17
Maybe the duplication of https://github.com/flutter/flutter/issues/60272

**Comment by sidrao2006** [comment] 2020-10-19 04:10
Duplicate of #67196

**Comment by pedromassangocode** [comment] 2020-10-19 10:11
Hi @adilwahla 
I see there's an open issue (https://github.com/flutter/flutter/issues/68290) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-10-19 10:11 UTC

**Comment by adilwahla** [comment] 2020-10-19 10:38
hi still got no answer can you please tell me what is the solution?
note: there is no file created named "GeneratedPluginRegistrant.java"
waiting for response

thanks in advance !

**Comment by adilwahla** [comment] 2020-10-19 10:42
@Abhishek01039 @pedromassangocode @ianloic @sidrao2006  
can you please tell me the solution ?
Not yet resolved
thanks!

**Comment by pedromassangocode** [comment] 2020-10-19 13:21
Hi @adilwahla 
This might be caused by anything including the space in your directory names **C:\Users\adil rehman\**. You can try to make sure your directories names does not contains spaces.
