### ISSUE TITLE
DUT response to touch is very slow

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#52256] opened 2020-03-09 19:39 UTC
https://buganizer.corp.google.com/issues/150860723

cc @dkwingsmt and @iskakaushik. Conversation on the Google bug.

**Comment by goderbauer** [comment] 2020-03-10 23:08
@dkwingsmt The internal issue was assigned to you, so I also assigned this mirror issue to you.

**Comment by goderbauer** [comment] 2020-03-10 23:09
@dkwingsmt Can you please assign a conservative milestone to this bus? Thanks.

**Comment by dkwingsmt** [comment] 2020-03-11 01:07
@goderbauer I would like to, but I'm waiting for the response for the question I asked in the thread. For now I don't have any way to reproduce it.

**Comment by dkwingsmt** [comment] 2020-03-12 01:57
I did find a bug during investigation, which will be fixed by https://github.com/flutter/flutter/pull/52450. I'm unsure if it's the cause for this issue, and I'll update the internal ticket for confirmation once the fix is rolled in.

**Comment by Hixie** [comment] 2020-03-24 23:06
We believe this is closed.

**Closed by Hixie** 2020-03-24 23:06 UTC
Labels: customer: fuchsia, framework, severe: customer blocker, waiting for customer response
