### ISSUE TITLE
Circular-shaped decorations are not properly clipped

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#13675] opened 2017-12-19 17:57 UTC
## Steps to Reproduce

I'm getting visual glitches using this widget structure:
```dart
new Container(
      decoration: new BoxDecoration(
        color: color,
        shape: BoxShape.circle,
        border: new Border.all(
          color: Colors.white,
          width: 2.5,
        ),
      ),
      child: new Center(
        child: new Text(
          "$index",
          style: theme.textTheme.body1.apply(color: textColor),
        ),
      ),
    );
```
![image](https://user-images.githubusercontent.com/729934/34171211-72fbe908-e4e5-11e7-8b88-c793e19ef92f.png)

As you can notice, the background color of the decoration is slightly overflowing the circular border. I've tried in different ways (e.g. using ClipOval) but the result is always the same.

I think this behaviour, even if intended, is not what a developer/designer would expect.

Is there a way to properly achieve the expected result?

Thanks

**Comment by Hixie** [comment] 2017-12-19 20:38
Yeah that's not good.

**Comment by sroddy** [comment] 2017-12-19 22:46
Btw, this issue is happening almost in the same way using native iOS Sdk. The reason there is because of anti-aliasing, I don't know if in this case it's the same.

**Comment by Hixie** [comment] 2017-12-19 23:20
Oh it's definitely just antialiasing. But we should do better. (For example, maybe we can shrink the background color paint by half the border width or something.)

**Comment by Hixie** [comment] 2018-05-21 19:41
We can't really shrink by one pixel; we don't know what the transformation matrix is.

**Comment by marcglasberg** [comment] 2018-05-21 21:00
I see. We've been fixing antialias problems, usually gaps, in some places where there is no transformation, or where we know the transformation. That's not fixable then, since if you do what you said the shrinking of the background color will be visible when the border is semi-transparent. Or maybe you only do this if the border color is not transparent. Or you add a flag.

**Comment by Hixie** [comment] 2018-05-21 21:51
Yeah...

We might be able to improve this at a lower level maybe, too.

**Comment by Mahmoud2B** [comment] 2018-10-09 20:05
this issue still there, @Hixie  did you guys find a fix?

**Comment by fralways** [comment] 2019-04-03 13:54
Can't believe so much time has passed with no fix. Very annoying bug. I often want to do something like this in order to make circular button but cant do because of this problem with edges: 
```
return InkWell(
      onTap: callback,
      child: Container(
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: Colors.red,
          shape: BoxShape.circle,
        ),
        child: Image.asset(
          'assets/images/someimage.png',
          fit: BoxFit.cover,
        ),
      ),
    );
```
![photo_2019-04-03 15 49 12](https://user-images.githubusercontent.com/6430214/55484043-0ee3c700-5628-11e9-9b5c-ce357394e0de.jpeg)


Similar thing happens if using flutter's CircleAvatar - there are still image leftovers over Container's border 
```
CircleAvatar(
  backgroundImage: AssetImage(
      "assets/someimage.png"),
  child: Container(
    decoration: BoxDecoration(
      shape: BoxShape.circle,
      border: Border.all(
        color: Colors.white,
        width: 5.0,
      ),
    ),
  ),
)
```
![2019-04-03 15 54 06](https://user-images.githubusercontent.com/6430214/55484415-bc56da80-5628-11e9-9210-20eb3fea757a.jpg)

**Comment by amreniouinnovent** [comment] 2019-07-16 12:47
@Hixie I have some pixels in Android **Tablet** is it the same issue or I need to open a different issue? 
Check "**Continue button**"  and the **CustomClipper** for green arrow and red arrow

My button code:

```
RaisedButton(
            padding: EdgeInsets.symmetric(
                vertical: AppFonts.localePadding(context, 10),
                horizontal: AppFonts.localePadding(context, 100)),
            color: AppColors.primary,
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(30),
                side: BorderSide(color: AppColors.textBlack, width: 1,style: BorderStyle.solid)),
            child: Text(
              'Continue',
              style: TextStyle(
                  color: AppColors.textBlack,
                  fontSize: AppFonts.localeSize(context, 18),
                  fontFamily: AppFonts.localeFont(context)),
            ),
            onPressed: () {},
          )
```

![flutter_01](https://user-images.githubusercontent.com/52191652/61295338-e489d400-a7e8-11e9-8b74-fcf85e8d7935.png)

**Comment by Omi231** [comment] 2020-02-19 10:59
Wow! 2 years and still no fix

**Comment by amreniouinnovent** [comment] 2020-02-19 11:32
@Omi231 They are working hard on stabilizing the system and they provide Flutter totally free.
Try to investigate the issue and make a pull request you see how much the engine is complex.

**Comment by artyomdevyatov** [comment] 2020-05-31 22:14
I've just faced the same issue...

Easy workaround:
```dart
return Container(
  width: 28,
  height: 28,
  decoration: BoxDecoration(
    color: Colors.grey, // border color
    shape: BoxShape.circle,
  ),
  child: Padding(
    padding: EdgeInsets.all(2), // border width
    child: Container(
      decoration: BoxDecoration(
        shape: BoxShape.circle,
      ),
      child: Container(), // inner content
    ),
  ),
);
```

**Comment by natebot13** [comment] 2020-09-02 05:27
Glad to see there was a little activity here two weeks ago. I ran into this issue today while trying to make a simple color picker. Seeing the color outside the white border is kinda ugly. I know I could use the above workaround, but I would not have expected this to be an issue in the first place. I assume it's an anti-aliasing issue and I hope it gets some improvement soon!

**Comment by TahaTesser** [comment] 2020-09-07 13:04
![image](https://user-images.githubusercontent.com/48603081/92390510-99dbc180-f138-11ea-8836-591919742436.png)

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          height: 50,
          width: 100,
          decoration: new BoxDecoration(
            color: Colors.blue,
            shape: BoxShape.circle,
            border: new Border.all(
              color: Colors.white,
              width: 2.5,
            ),
          ),
          child: new Center(
            child: new Text(
              "2",
              style:
                  Theme.of(context).textTheme.body1.apply(color: Colors.white),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.87, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.87 at /home/taha/Code/flutter_master
    • Framework revision 4732a214a7 (3 days ago), 2020-09-04 21:05:02 -0400
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      •
      Linux
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 85.0.4183.83

• No issues found!

```

</details>

**Comment by Omi231** [comment] 2020-09-17 21:08
Guys please give this issue some priority 😰 It screws almost every design which require rounded corners.

**Comment by fluttercorner** [comment] 2020-10-08 18:03
[How to Create a rounded button / button with border-radius in Flutter](https://fluttercorner.com/how-to-create-rounded-button-button-with-border-radius-in-flutter/)

**Comment by bsbilal** [comment] 2021-01-13 11:50
is there any solution?
![image](https://user-images.githubusercontent.com/9121424/104448606-73c6a200-55ae-11eb-803a-424dd6ebf55d.png)

**Comment by wess** [comment] 2021-03-25 14:08
Hitting this now as well and our "major fintech" app uses a lot of circles, do we know the status?

**Comment by naamapps** [comment] 2021-05-22 14:38
Hey, the issue still exists in version 2.2
Is there progress on this?

**Comment by Mixpeal** [comment] 2021-08-28 22:57
@naamapps check this little hack


`Container(
  width: 63.0,
  height: 63.0,
  decoration: BoxDecoration(
      shape: BoxShape.circle,
      border: Border.all(
        color: Color(0xFFF1DEC1),
        width: 3,
      )),
  child: Container(
    width: 60.0,
    height: 60.0,
    decoration: BoxDecoration(
        image: DecorationImage(
            fit: BoxFit.fitWidth,
            image: Image.asset(
              "assets/images/sample.jpg",
            ).image),
        shape: BoxShape.circle),
  ),
),`

**Comment by Mixpeal** [comment] 2021-08-28 23:00
@naamapps  check this little hack 

```dart
Container(
  width: 63.0,
  height: 63.0,
  decoration: BoxDecoration(
      shape: BoxShape.circle,
      border: Border.all(
        color: Color(0xFFF1DEC1),
        width: 3,
      )),
  child: Container(
    width: 60.0,
    height: 60.0,
    decoration: BoxDecoration(
        image: DecorationImage(
            fit: BoxFit.fitWidth,
            image: Image.asset(
              "assets/images/sample.jpg",
            ).image),
        shape: BoxShape.circle),
  ),
),

```

**Comment by CodingAleCR** [comment] 2021-11-17 16:46
This issue also affects the `CircularProgressIndicator` widget. I had to go at it in a different way, I placed a Stack and clipped the widget using a `Container` to clip the inside shadow and another `CircularProgressIndicator` to clip the outside shadow. It is a bit hard to explain and definitely not a robust way to handle it, but due to urgency, I had to go at it this way. 

A couple of improvements that could be done would be to replace the `CircularProgressIndicator` used for the outer shadow and the `Container` used for the inner shadow with a `CustomPaint` or even create a custom clipper for it.

Anyways, you can [see a DartPad of the problem here](https://dartpad.dev/?null_safety=true&id=5c57b1ae3c78c22ecffdad65ac5b61d3) and you can [see the code in detail of how I solved it here](https://dartpad.dev/?null_safety=true&id=acf40e55e8ddd564bb0cca55376184e9).

**Comment by naamapps** [comment] 2021-11-17 21:16
Still exists in 2.5.3 😕 
Flutter team, this issue exists for 4 years now.
Please can someone take a look at this? 
Such a small thing but it degrades the UI and makes it unprofessional.

**Comment by Carl-CircuitWorx** [comment] 2021-11-21 12:15
Just had the same problem,
![image](https://user-images.githubusercontent.com/9988707/142761198-62198654-769a-4d3d-923c-e51622ad1aea.png)

Shall try a work around!

**Comment by alireza7991** [comment] 2021-12-02 08:18
4 Years, no fix! TY flutter.

**Comment by orangeswim** [comment] 2022-03-21 03:54
wanted to bump this issue.
![image](https://user-images.githubusercontent.com/1499212/159203247-67f8b480-1679-44af-82bf-02221fd8aaa3.png)

```
Container(
                            margin:
                                const EdgeInsets.symmetric(horizontal: 16.0),
                            width: 130,
                            height: 130,
                            decoration: BoxDecoration(
                              image: DecorationImage(
                                image: CachedNetworkImageProvider(
                                    content.imageUrl),
                                fit: BoxFit.cover,
                              ),
                              border: Border.all(width: 4.0),
                              shape: BoxShape.circle,
                            )),
```

**Comment by bernaferrari** [comment] 2022-07-30 23:00
I think I can solve this. As 95% of reported issues use no opacity, what if I made the background paint until 50% the width? Is this a good solution?

<img width="666" alt="image" src="https://user-images.githubusercontent.com/351125/182002867-03d55bbb-163d-48b9-ba3c-ed32dbef2680.png">

The new StrokeAlign property (the PR is open) would also help you, with a StrokeAlign value of -0.98.

**Comment by danagbemava-nc** [comment] 2023-03-10 10:25
Reproduces on the latest versions of flutter.

<img width="191" alt="Screenshot 2023-03-10 at 10 20 44" src="https://user-images.githubusercontent.com/88313112/224291012-2a000b00-34e1-4cef-a8cf-33ef741b5d64.png">

<details>
<summary>updated sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          height: 150,
          width: 150,
          decoration: BoxDecoration(
            color: Colors.blue,
            shape: BoxShape.circle,
            border: Border.all(
              color: Colors.white,
              width: 2.5,
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.7.7 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (2 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8836.5

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • adb-5dd3be00-17AYzd._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • Nexus (mobile)      • 00008020-001875E83A38002E                  • ios            • iOS 16.3.1 20D67
    • macOS (desktop)     • macos                                      • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)        • chrome                                     • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.9.0-1.0.pre.144, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.9.0-1.0.pre.144 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac550c6356 (7 hours ago), 2023-03-09 21:59:21 -0500
    • Engine revision e9ca7b2c45
    • Dart version 3.0.0 (build 3.0.0-313.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8836.5

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile) • adb-5dd3be00-17AYzd._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • Nexus (mobile)      • 00008020-001875E83A38002E                  • ios            • iOS 16.3.1 20D67
    • macOS (desktop)     • macos                                      • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)        • chrome                                     • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by sabatage3** [comment] 2024-04-05 01:29
Almost 7 years have passed, any updates on this? i really love Flutter, but that weird outline makes the UI look so cheap

**Comment by bernaferrari** [comment] 2024-04-05 02:01
I made a PR but it broke internal Google stuff that was hard to test and I never tried fixing that.

**Comment by erlangparasu** [comment] 2024-07-15 05:16
> 2017-2024

Any updates?

**Comment by bernaferrari** [comment] 2024-07-15 19:05
I gave up because I don't have access to Google internal testing

**Comment by erlangparasu** [comment] 2024-07-15 23:19
Mybe svg as alternative?

**Comment by bernaferrari** [comment] 2024-07-16 01:59
Well, 1) flutter doesn't support svg, 2) you don't want this to happen in basic shapes.

**Comment by gnprice** [comment] 2024-08-12 05:12
> Right now with customer testing it would be waaay harder to land this change :(

FWIW I doubt customer testing will add much to the difficulty of fixing this.
* It's a lot smaller than (my guess of the size of) Google testing.
* In particular, though there are a number of libraries, there's only one app; namely Zulip, and speaking for Zulip we don't currently use golden tests.
* Everything there is open source, so if something does break you can always fix it.

Failures in Google internal tests are a bummer, though.

---

OTOH I took a look just now at the previous PR, and it reads like it got pretty close to merge — in particular it seems like the Google internal changes were deemed to be OK:
https://github.com/flutter/flutter/pull/122317#issuecomment-1526027980
So for anyone who wants to try to further take this forward (whether @bernaferrari again or someone else), I think it may not be a lot of work to start from #122317, rebase it, handle the couple of nits starting at https://github.com/flutter/flutter/pull/122317#pullrequestreview-1489212518 , and get it merged.

**Comment by bernaferrari** [comment] 2024-08-12 08:44
The issue was that Google testing problem seemed bad (it was affecting some apparently unintended things) and I have no way to debug. I can submit again if you want to debug for me, or point me in the right direction.

The issue with customer testing is there the super apps and Cupertino macOS testing have a lot of bounding checks, so I think they might be affected and the only way to "solve" would be commenting the test, landing this, fixing the test. There is no partial migration.

For Google testing it is going to fail in 200 places, but as long as you are willing to update the hard coded values, it is not a problem.

**Comment by gnprice** [comment] 2024-08-12 20:48
My reading of the thread is that after spending a bit of time looking at the Google-internal changes, @gspencergoog concluded they were fine. [He wrote](https://github.com/flutter/flutter/pull/122317#issuecomment-1526027980):
> They're pretty trivial, so as long as we can say that they are more correct now than they were, I'm OK with approving them.

---

> The issue with customer testing is with super apps and Cupertino macOS testing that got a lot of bounding checks, so I think they might be affected and the only way to "solve" would be commenting the test, landing this, fixing the test. There is no partial migration.

Yeah, that sort of effect is possible. I think the usual solution is to temporarily disable the affected suite in `flutter/tests`: rename the file `registry/foo.test` to `registry/foo.test.disabled`, then land the framework change, then land the test update downstream, then rename the file back.

If by "Cupertino macOS testing" you're referring to the suite `registry/macos_ui.test`, you may be glad to hear that that one is disabled since last December: https://github.com/flutter/tests/pull/317 .

**Comment by bernaferrari** [comment] 2024-08-12 20:51
Greg said the changes were ok, but he manually checked some files and there were some small things that seemed "odd" and unintended, like Chips/Buttons were being affected somehow (Material State, weird things). They weren't supposed to be affected in the way he saw, but I was never able to reproduce locally, and I can't trigger the golden of what he saw, so it is hard.

**Comment by gnprice** [comment] 2024-08-12 21:00
Hmm, I see, dang. Did that discussion happen somewhere else, then (perhaps Discord)? It doesn't seem like any reference to it made it onto the PR thread.

**Comment by bernaferrari** [comment] 2024-08-12 21:02
Here: https://github.com/flutter/flutter/pull/122317#issuecomment-1526026433

**Comment by gnprice** [comment] 2024-08-12 21:23
I see. Well, that's the comment that was followed by this one:

> They're pretty trivial, so as long as we can say that they are more correct now than they were, I'm OK with approving them.

So I think those (as well as the other changes like them) are the changes that he was referring to in that later comment.

If the reply to those changes is, "I tried and couldn't reproduce a change like those locally; but they are visually trivial, and the new versions don't look any worse to me than the old versions, and I think in principle they should be more correct because the new logic in the PR is more correct", then my guess based on the thread is that @gspencergoog (and any other Googlers involved) would have been happy with that answer.

Looking at those screenshots myself, I'd definitely say they're visually trivial and that the new versions don't look any worse than the old. I haven't closely read the logic in the PR, but presumably you think it is indeed more correct. So if you tried to reproduce similar changes and couldn't, then I think that's probably all the debugging that is needed.

**Comment by bernaferrari** [comment] 2024-08-12 21:26
The main issue is not that they look odd or wrong, just "are you sure your change should happen here?" and I'm not sure. I wish I could debug to be sure, there is a 75% chance that's a bug, but I can't debug it.

**Comment by gnprice** [comment] 2024-08-12 21:37
OK, I guess it comes down to that estimate of whether it's a bug. If you think it probably really is a bug in the PR, then I agree it should be fixed before merging, and it's frustrating that the repro case for the bug isn't accessible.

FWIW my guess would be that it's not a bug. Those three gray "1", "2", "3" boxes don't visibly have borders… but they might still have a `_decoration.shape` that's an OutlinedBorder, say, just with a border that's the same color as the interior. Based on the code in the PR, it seems like something like that has to be the case in order for it to have an effect.

And then once the new logic gets involved, it's expected that it may cause small rounding differences that make visually imperceptible changes in the output.

**Comment by gspencergoog** [comment] 2024-08-12 21:55
We were actually pretty close, I was OK with just approving those diffs, I just wanted to make sure they were expected.  If you want help with the Google testing side, I can look at them and approve if they're still trivial.  I doubt many other customers do golden tests, but we can deal with them if they do (and if they do, you can reproduce it there).

**Comment by bernaferrari** [comment] 2024-08-12 22:01
Could be. If @gnprice thinks that's not a bug, I can resubmit the PR. My brain melted thinking "is that a bug or not?" and I couldn't find an answer, then I gave up.

**Comment by gnprice** [comment] 2024-08-13 02:18
Yeah, I can't claim to be sure of it, but my assessment is that it's probably not a bug. A resubmitted version of the PR sounds great!

If we want to get to a higher degree of certainty that those golden diffs aren't telling us about some way in which the code isn't behaving how it's intended to, then since you've already tried and been unable to reproduce the behavior locally, probably the most effective next step would be for @gspencergoog or another Googler to dig into one of those test cases that doesn't visually have a border and confirm that the widgets do express a border after all. (And the border is just very thin, or the same color as the interior or exterior, or for some other reason doesn't appear visually.) But personally I'd be comfortable skipping that step.

**Closed** 2024-08-15 19:02 UTC
Labels: framework, engine, dependency: skia, customer: crowd, has reproducible steps, P2, found in release: 3.7, found in release: 3.9, team-engine, triaged-engine
