### ISSUE TITLE
Flutter Desktop - Can't enter backticks (`) in TextField widget

### ISSUE THREAD

**Issue by Sorunome** [flutter/flutter#90441] opened 2021-09-21 08:57 UTC
It appears you are unable to enter backticks in a TextField widget on flutter desktop on linux. When trying to enter e.g. 
```
`u
```
 it'll convert that to "ù". Even more, when copypasting the string 
 ```
 `u
 ```
 externally into a TextField widget it'll mangle that down into "ù", making it impossible to send backticks by themself.

**Comment by TahaTesser** [comment] 2021-09-21 11:29
Hi @Sorunome 
I just tried copy and paste into linux desktop app, it looks the same on the latest `stable`.  If you're entering from keyboard, can you please provide which keyboard are you using? Also does it reproduce web on linux?



| Preview | 
| --------------- | 
| <img src="https://user-images.githubusercontent.com/48603081/134162843-c5fcb3f5-77f7-4ee6-b2cb-d385264fc59b.png" height="450" />	|


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Zorin OS 16 5.11.0-34-generic, locale
    en_US.UTF-8)
    • Flutter version 2.5.1 at /home/taha/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Zorin OS 16 5.11.0-34-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```
	
</details>

**Comment by Raatty** [comment] 2021-10-10 00:38
think i found the problem https://gitlab.com/famedly/fluffychat/-/blob/main/lib/config/themes.dart#L17 it turns out to be a rendering issue with these fallback font settings, disabling makes back ticks display as expected but then u don't get emojis.....

**Comment by danagbemava-nc** [comment] 2021-11-03 09:11
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-11-03 09:11 UTC
Labels: waiting for customer response, in triage
