### ISSUE TITLE
[text_field]: enableSuggestions:false is not honored on Android

### ISSUE THREAD

**Issue by NickalasB** [flutter/flutter#75462] opened 2021-02-05 00:29 UTC
## Use case

My specific use-case is that, on Android, I want to be able to present the user with a keyboard where suggestions are turned off, but the user can still enter text via voice-input by way of the built-in keyboard microphone button. 

The workaround we're currently using is setting the `keyboardType` on Android to `TextInputType.emailAddress`. That disables suggestions but also disables the keyboard's microphone so voice-input doesn't work.

**Scenario:**
Given I have set `enableSuggestions` to false.
When I open the device keyboard and start typing.
**Expected Behavior:**
Then I should not see any suggestions above the keyboard.
**Actual Behavior:**
I see suggestions above the keyboard

## Proposal

Update the backing code to properly set the native Android inputTypes.

As mentioned in https://github.com/flutter/flutter/issues/22828#issuecomment-731765021: 
> In Android native you can get this using :
android:inputType="textFilter|textMultiLine|textNoSuggestions"

https://github.com/flutter/flutter/pull/42550 is the PR where this behavior was originally implemented so it sounds like this is a regression?

Related issues:
https://github.com/flutter/flutter/issues/22828
https://github.com/flutter/flutter/issues/71679

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)
    ! Error: Nick’s iPhone is not connected. Xcode will continue when Nick’s iPhone is connected. (code -13)

! Doctor found issues in 1 category.
```

**Code Sample 1 (`enableSuggestions: false`):**

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 24.0),
        child: TextField(enableSuggestions: false),
      ),
    );
  }
}
```

**Image below is from a Pixel 3 running Android 11**

![image](https://user-images.githubusercontent.com/16969303/106972312-788dfa00-6705-11eb-9ee7-3da940988017.png)

**Code Sample 2 (`keyboardType: TextInputType.emailAddress`):**

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 24.0),
        child: TextField(keyboardType: TextInputType.emailAddress),
      ),
    );
  }
}
```

**Image below is from a Pixel 3 running Android 11**
![image](https://user-images.githubusercontent.com/16969303/106972473-c6a2fd80-6705-11eb-944b-a9073c38e22e.png)

**Comment by pedromassangocode** [comment] 2021-02-05 07:51
I'm able to reproduce this issue and this seems to be a duplicate of https://github.com/flutter/flutter/issues/71679. Since they are the same I'm going to close this one and have the discussion in https://github.com/flutter/flutter/issues/71679. I will also update the other one since this clearly seems to be a regression.

Thank you for filling this issue!

**Closed by pedromassangocode** 2021-02-05 07:51 UTC
