### ISSUE TITLE
failed to emit precompiled header '/Users/flutter-dev/Library/Developer/Xcode/DerivedData/Runner-dghhhijkztquumaijdrrzdcoklxr/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_3M45BMBR9VCN7-clang_3TF9NZCX310S2.pch' for bridging header '/Users/flutter-dev/AndroidStudioProjects/flutter_lt_3.0/ios/Runner/Runner-Bridging-Header.h'

### ISSUE THREAD

**Issue by ArpanaSwarnkar** [flutter/flutter#101277] opened 2022-04-04 08:25 UTC
Hi, not able to build iOS app due to this build issue:
failed to emit precompiled header '/Users/flutter-dev/Library/Developer/Xcode/DerivedData/Runner-dghhhijkztquumaijdrrzdcoklxr/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_3M45BMBR9VCN7-clang_3TF9NZCX310S2.pch' for bridging header '/Users/flutter-dev/AndroidStudioProjects/flutter_lt_3.0/ios/Runner/Runner-Bridging-Header.h'

Earlier it was working properly.

output of flutter doctor -v
✓] Flutter (Channel stable, 2.5.0, on macOS 11.2.1 20D75 darwin-x64, locale en-IN)
    • Flutter version 2.5.0 at /Volumes/Macintosh HD - Data/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/flutter-dev/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

podfile:
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
  end
end

**Comment by maheshmnj** [comment] 2022-04-04 11:37
Hi @ArpanaSwarnkar, Thanks for filing the issue.

There is a similar issue describing this case https://github.com/flutter/flutter/issues/99387, Please check [this comment on the issue](https://github.com/flutter/flutter/issues/99387#issuecomment-1081238267) for the cause of the solution 
Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-04-04 11:37 UTC
Labels: in triage
