### ISSUE TITLE
`Mac_ios hot_mode_dev_cycle_ios__benchmark` is flaky due to xcode build crash

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#130025] opened 2023-07-05 16:39 UTC
The test has been flaky 7 times in recent 100 runs:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_ios__benchmark/5743/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_ios__benchmark/5741/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_ios__benchmark/5719/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_ios__benchmark/5686/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_ios__benchmark/5685/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_ios__benchmark/5682/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_ios__benchmark/5681/overview

```
[2023-06-30 19:09:46.195219] [STDOUT] stdout: [   +7 ms] Failed to build iOS app
[2023-06-30 19:09:46.195239] [STDOUT] stderr: [   +1 ms] Could not build the precompiled application for the device.
[2023-06-30 19:09:46.195256] [STDOUT] stderr: [   +1 ms] Error (Xcode): unexpected service error: The Xcode build system has crashed. Build again to continue.
[2023-06-30 19:09:46.195273] [STDOUT] stderr: 
[2023-06-30 19:09:46.195772] [STDOUT] stderr: [        ] Uncategorized (Xcode): Command  failed with a nonzero exit code
[2023-06-30 19:09:46.195812] [STDOUT] stderr: 
[2023-06-30 19:09:46.196340] [STDOUT] stderr: [        ] Error launching application on swarming’s iPhone.
[2023-06-30 19:09:46.867025] [STDOUT] stdout: [ +670 ms] "flutter run" took 41,170ms.
```

**Comment by zanderso** [comment] 2023-07-05 16:57
This is a duplicate of the flake bot reporting the stats on https://github.com/flutter/flutter/issues/120808. I'm guessing this is related to the recent Xcode version upgrade cc @vashworth.

**Closed by zanderso** 2023-07-05 16:57 UTC
Labels: platform-ios, tool, P1, severe: flake
