### ISSUE TITLE
Back button is not working when TextField has focus

### ISSUE THREAD

**Issue by ShwetaJain** [flutter/flutter#66784] opened 2020-09-27 19:56 UTC
Hello,
I am creating Flutter application and using 'TextFormField' for text entry. If I don't edit that field or till the field is not in focus and we press Android Back Button of device ,  we are taking back to previous screen but if we take focus to text field and perform some operation then Android back button is not working .

We are using OnWillpop() function of 'WillPopScope' Class to handle the Android Device back button.

Please help me.

**Comment by pedromassangocode** [comment] 2020-09-28 09:25
Hi @ShwetaJain 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by ShwetaJain** [comment] 2020-09-28 09:59
Hey Pedro ,
Thanks for looking into the issue. Sharing the required details 
Please see attached png for the version 
Code Snippet.

//Main.Dart
@override
  Widget build(BuildContext context) {
    
    return WillPopScope(
      onWillPop: ()async {
        print('call on Willpopup');
        _onBackPressed();
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          /
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                TextFormField(
                  controller: controller,
                  style:
                  TextStyle(fontSize: 22.0, color: Color.fromRGBO(100, 100, 100, 1)),
                  decoration: InputDecoration(
                    
                      labelText: 'EMAIL *',
                      labelStyle: TextStyle(
                          fontFamily:'Montserrat',
                          fontSize: 22,
                          fontWeight: FontWeight.bold,
                          color: Color.fromRGBO(97, 97, 97, 1)
                      ),
                      focusedBorder: UnderlineInputBorder(

                          borderSide: BorderSide(color: Colors.blue)
                      )
                  ),
                  
             ),//TextFormField
                              ],//<Widget>[]
            ),//Column

        
    ),//Center
        
      ),//Scaffold
    );//WillpopScope
  }


Future<bool> _onBackPressed() {
    print(1);
    exit(0);
  }



![fluter](https://user-images.githubusercontent.com/1005913/94418624-4391f980-019f-11eb-9902-371f9cb57668.png)

**Comment by pedromassangocode** [comment] 2020-09-29 06:41
Hi @ShwetaJain 
I need a minimal complete reproducible code sample that I can just copy/paste into a main.dart file and run it. The code you provided is not runnable.

**Comment by ShwetaJain** [comment] 2020-09-29 13:24
Hello @pedromassangocode 
Adding full main.dart file code here , it is in runnable condition .Please do let me know if needs other details . Thank you 
//main.dart


import 'dart:io';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  Future<bool> _onBackPressed() {
    print(1);
    exit(0);
  }

  TextEditingController controller;

  @override
  void initState() {
    super.initState();
    controller = new TextEditingController();
    controller.text = 'Sample Email';
  }


  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: ()async {
        print('call on Willpopup');
        _onBackPressed();
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                TextFormField(
                  controller: controller,
                  style:
                  TextStyle(fontSize: 22.0, color: Color.fromRGBO(100, 100, 100, 1)),
                  decoration: InputDecoration(
                    //contentPadding: EdgeInsets.all(30),
                      labelText: 'EMAIL *',
                      labelStyle: TextStyle(
                          fontFamily:'Montserrat',
                          fontSize: 22,
                          fontWeight: FontWeight.bold,
                          color: Color.fromRGBO(97, 97, 97, 1)
                      ),
                      focusedBorder: UnderlineInputBorder(
                          borderSide: BorderSide(color: Colors.blue)
                      )
                  ),
             ),
             ],
            ),
    ),
      ),
    );
  }


}

**Comment by pedromassangocode** [comment] 2020-09-30 07:29
I was able to reproduce this on latest master channel. This is a regression since it does not reproduce on latest stable.

Removing the `WillPopscope` widget the issue is still reproducible so it is not related. I attached a minimal reproducible code bellow. Just tap the text field and try to click the back button of the device.

The issue is also reproducible in release builds. Tested with Android 10 and Android 9.

| Stable channel | Master channel |
| --------------- | --------------- |
![gif1](https://user-images.githubusercontent.com/67424416/94654429-f9229100-02f4-11eb-9636-2ad69d500d88.gif) | ![gif](https://user-images.githubusercontent.com/67424416/94654583-296a2f80-02f5-11eb-8b2d-82b90d37c5e1.gif)

<details><summary>minimal reproducible code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: TextFormField(),
        ),
      ),
    );
  }
}

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.428, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.428 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision a06f385145 (5 hours ago), 2020-09-29 21:37:04 -0400
    • Engine revision d18c3ea75c
    • Dart version 2.11.0 (build 2.11.0-178.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by TahaTesser** [comment] 2020-09-30 16:13
Hi @ShwetaJain  @pedromassangocode 
This is now fixed on the latest `master` channel 


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: TextFormField(),
        ),
      ),
    );
  }
}
```

</details> 

### Physical Device Test
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/48603081/94710348-615c8b80-0364-11eb-8255-41caddbefc37.gif)

### Emulator Test
![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/48603081/94710989-2575f600-0365-11eb-9627-ee17715bb502.gif)


<details> 
<summary>code sample</summary> 

```dart
import 'dart:io';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  Future<bool> _onBackPressed() {
    print(1);
    exit(0);
  }

  TextEditingController controller;

  @override
  void initState() {
    super.initState();
    controller = new TextEditingController();
    controller.text = 'Sample Email';
  }


  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: ()async {
        print('call on Willpopup');
        _onBackPressed();
        return true;
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                TextFormField(
                  controller: controller,
                  style:
                  TextStyle(fontSize: 22.0, color: Color.fromRGBO(100, 100, 100, 1)),
                  decoration: InputDecoration(
                    //contentPadding: EdgeInsets.all(30),
                      labelText: 'EMAIL *',
                      labelStyle: TextStyle(
                          fontFamily:'Montserrat',
                          fontSize: 22,
                          fontWeight: FontWeight.bold,
                          color: Color.fromRGBO(97, 97, 97, 1)
                      ),
                      focusedBorder: UnderlineInputBorder(
                          borderSide: BorderSide(color: Colors.blue)
                      )
                  ),
             ),
             ],
            ),
    ),
      ),
    );
  }
}
```

</details> 
### WillPopScope Sample Test

![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/48603081/94711405-b4830e00-0365-11eb-874d-d21c3c38e5ac.gif)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.430, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.430 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 94e836711e (75 minutes ago), 2020-09-30 07:29:25 -0700
    • Engine revision a6a6fd163b
    • Dart version 2.11.0 (build 2.11.0-177.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.7
      19H2 x86_64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!


```

</details> 


Can you please upgrade to the latest `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Closing, as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-30 16:13 UTC
Labels: a: text input, engine, found in release: 1.22, has reproducible steps, platform-android, severe: regression
