### ISSUE TITLE
Lower frame rate on route switch or listview scroll with finger

### ISSUE THREAD

**Issue by warfrogsdf** [flutter/flutter#29656] opened 2019-03-20 03:06 UTC
1. write a simple demo
2. use fultter built-in navigator
3. use flutter listview

when route switch （with finger） on iphone xs， frame rate so Lower， the same demo with rn better than flutter demo。

the same on listview scroll with finger。

so，i hope flutter team optimization performance on route switch wih fingre and listview scroll with finger。if this problem can be solve，flutter will perfect。

**Comment by warfrogsdf** [comment] 2019-03-20 03:09
I think we should first solve the problem of fluency, then solve the engineering and development efficiency of flutter development for Android and IOS platforms, and finally support the web, don't give up all the costs.

**Comment by warfrogsdf** [comment] 2019-03-20 03:11
In the xian fish app recommended by flutter, the frame rate of the page switching with finger is significantly lower than that of the app native page.

**Comment by warfrogsdf** [comment] 2019-03-20 03:15
@abarth

**Comment by x4080** [comment] 2019-04-23 07:43
@warfrogsdf , I agree with the non as performance as native especially in Android (list view), my iPhone SE works pretty good in list view, and there's issues about iPhone Xs as well

**Comment by escamoteur** [comment] 2019-09-24 15:53
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by warfrogsdf** [comment] 2019-09-26 09:59
this problem only in ios platform, iphone x and iphone xs, maybe skia problem

**Comment by escamoteur** [comment] 2019-09-26 10:52
Could you please add the output of flutter doctor here?

**Comment by warfrogsdf** [comment] 2019-09-30 10:55
is skia on ihone x xs problem, maybe flutter 1.10.x resovled this problem.

**Comment by escamoteur** [comment] 2019-09-30 19:44
Hi,
what do you mean by * flutter 1.10.x resovled this problem.* have you tried on latest master and the problem is gone?

**Comment by iapicca** [comment] 2019-11-07 13:44
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-07 13:44 UTC
Labels: waiting for customer response
