### ISSUE TITLE
UserAccountsDrawerHeader has white on white text by default

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#7194] opened 2016-12-08 05:38 UTC
decoration is essentially required, since the text is white on white by default.  Presumably we should include a better default background?

**Comment by orthros** [comment] 2017-06-09 20:50
I might take a crack at this 😺

**Comment by Hixie** [comment] 2017-12-13 00:10
This is not on our short-term priority list. Moving to next milestone.

**Comment by TahaTesser** [comment] 2020-03-24 14:54
Hi @Hixie 
Testing the code above, does reproduce default blue and white text. 
Is this issue still valid?
Thank you

**Comment by TahaTesser** [comment] 2020-07-29 12:48
Looks like this is fixed, default is blue, text is white 

![Simulator Screen Shot - iPhone 11 - 2020-07-29 at 18 17 26](https://user-images.githubusercontent.com/48603081/88801779-cf030480-d1c7-11ea-9112-3ec0baa39144.png)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f25bd9c55c (2 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (5 available)            
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details> 

Closing, as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-29 12:48 UTC
Labels: P4, easy fix, f: material design, framework, has reproducible steps
