### ISSUE TITLE
Flutter web can't start when url contains more than one route param

### ISSUE THREAD

**Issue by Oleh-Sv** [flutter/flutter#120692] opened 2023-02-14 14:58 UTC
I noticed that flutter app from version 3.7 can't start app if url contains more than on route param (and pathUrlStrategy enabled)

## Steps to Reproduce

1. Use  setPathUrlStrategy()
2. Launch flutter in web
3. Try to navigate to route like localhost:8000/test1/test2

**Expected results:**
Flutter app starts correct

**Actual results:**
Infinity loading of app

<img width="800" alt="Screenshot 2023-02-14 at 14 53 12" src="https://user-images.githubusercontent.com/17007214/218773512-8ec0aa64-57c9-47aa-b973-59cd8bdc66ca.png">

In console I noticed this messages. Looks like js code can't find path to flutter_service_worker

**Comment by mhbdev** [comment] 2023-02-15 00:18
I had the same issue on the latest flutter stable version (3.7.3).
It has been fixed in the latest version of flutter master channel with [this fix](https://github.com/flutter/flutter/pull/118684) and you can follow [this issue](https://github.com/flutter/flutter/issues/120310) for more details.

**Comment by huycozy** [comment] 2023-02-15 06:04
Hi @Oleh-Sv 
As @mhbdev mentioned above, I'm closing this issue as a duplicate of #116360 which has been fixed on the master channel. 
You may find the workaround at https://github.com/flutter/flutter/issues/116360#issuecomment-1364181861. And also follow up on https://github.com/flutter/flutter/issues/120197 (CP to stable) for updates. Thanks!

**Closed by huycozy** 2023-02-15 06:04 UTC
Labels: in triage
