### ISSUE TITLE
await Future.delayed(Duration.zero) takes more time after flutter update

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#90874] opened 2021-09-28 12:10 UTC
Hi, after switching flutter from stable 2.2.3 to stable 2.5.1 operation await Future.delayed(Duration.zero) started taking more time.

I have a while loop which has to work without any pauses in order to have time to change some data with WriteProcessMemory in another process, so i used await Future.delayed(Duration.zero) to avoid UI stuck, but now, after update, i see that it works differently(slower).

I even downgraded flutter version with 
```
flutter channel beta
flutter downgrade v2.2.3
```
to ensure that it happened because of update(It actually downgraded to 2.2.0-10.1.pre)

Platform: Windows application.

Maybe you can write some test to check how many times some operation in while loop can be performed for 10 seconds with Future.delayed(Duration.zero) on flutter 2.2.3 and flutter 2.2.5?

Or maybe there's some other way to avoid UI stuck on while loop? (Except another isolate)

**Comment by TahaTesser** [comment] 2021-09-28 13:41
Hi @kirill-21 
Not sure how you calculated the difference but I have attempted with `DateTime.now()`
Different is really really small, seems fine to me 
```console
[+2155 ms] flutter: Before - 2021-09-28 16:33:10.093155
[  +18 ms] flutter: After - 2021-09-28 16:33:10.111370
```


<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          print('Before - ${DateTime.now()}');
          await Future.delayed(Duration(seconds: 3));
          print('After - ${DateTime.now()}');

        },
      ),
    );
  }
}
``` 
	
</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
    • Flutter version 2.5.1 at C:\Users\Taha\Code\flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (11 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.194]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```
	 
</details>


Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by kirill-21** [comment] 2021-09-28 15:53
> Hi @kirill-21 Not sure how you calculated the difference but I have attempted with `DateTime.now()` Different is really really small, seems fine to me
> 
> ```
> [+2155 ms] flutter: Before - 2021-09-28 16:33:10.093155
> [  +18 ms] flutter: After - 2021-09-28 16:33:10.111370
> ```
> 
> minimal code sample
> flutter doctor -v
> Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample Thank you

Hi. I've been testing flutter sdk's from https://flutter.dev/docs/development/tools/sdk/releases, and found out after which update i started having this problem
![image](https://user-images.githubusercontent.com/63228361/135121996-70baa587-aba6-4488-86c4-85c440ef968d.png)

**Comment by TahaTesser** [comment] 2021-09-29 07:34
Hi @kirill-21 
Thanks for identifying the commit

**Comment by kirill-21** [comment] 2021-09-29 07:44
> Hi @kirill-21 Thanks for identifying the commit

So how can I manually change this in my project?

**Comment by TahaTesser** [comment] 2021-09-29 07:54
@kirill-21 
If you want to modify engine, you need it set it up locally then build app using local engine

**Comment by kirill-21** [comment] 2021-09-29 07:56
> @kirill-21 If you want to modify engine, you need it set it up locally then build app using local engine

Is there any guide how to do that?

**Comment by TahaTesser** [comment] 2021-09-29 08:07
@kirill-21 
Checkout [Setting up the Engine development environment](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) & [Compiling the engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine)

**Comment by mraleph** [comment] 2021-09-29 11:52
Removed `dependency: dart` given that this is caused by a pure engine change (and seems intentional?) /cc @iskakaushik

**Comment by iskakaushik** [comment] 2021-09-29 15:05
Hi @kirill-21 , we've identified an issue where on desktop platforms vsync behavior lead to pausing the microtasks longer than needed and it was fixed in https://github.com/flutter/engine/pull/28817, could you please let us know if that solves your issue? This is assuming you are able to get the engine to build.

**Comment by kirill-21** [comment] 2021-09-29 15:30
> Hi @kirill-21 , we've identified an issue where on desktop platforms vsync behavior lead to pausing the microtasks longer than needed and it was fixed in [flutter/engine#28817](https://github.com/flutter/engine/pull/28817), could you please let us know if that solves your issue? This is assuming you are able to get the engine to build.

When will it be available on master channel so that i can test it? I have some issues with building engine myself (gclient sync fails with message that flutter folder in src does not exist, but if i add this folder manually, it moves somewhere and fails again)

**Comment by iskakaushik** [comment] 2021-09-29 16:05
I'm expecting it to land in the engine today and hopefully roll into the framework soon after. I will add a note to this issue once it rolls into the framework (and available on master channel).

**Comment by iskakaushik** [comment] 2021-09-30 15:52
@kika It should be in master branch now as of https://github.com/flutter/flutter/pull/90980. Could you please try it out and let me know if it solved your problem?

**Comment by kirill-21** [comment] 2021-09-30 17:29
> @kirill-21 It should be in master branch now as of #90980. Could you please try it out and let me know if it solved your problem?

Hi. Upgraded to d0d8e348b6b4269c8483060d84f5fe135055a163 engine, now it works great and rapidly

**Closed** 2021-09-30 17:31 UTC
Labels: severe: regression, engine, severe: performance, passed first triage, perf: speed, regression identified
