### ISSUE TITLE
crash always in iOS 15 (19A346)

### ISSUE THREAD

**Issue by xioFei** [flutter/flutter#90743] opened 2021-09-26 06:15 UTC
```console
libsystem_kernel.dylib
__pthread_kill + 8

1 libsystem_pthread.dylib
pthread_kill + 268
2 libsystem_c.dylib
abort + 164
3 Metal
MTLGetWarningMode + 0
4 IOGPU
IOGPUResourceGetClientShared + 0
5 Metal
0x000000019b6bd000 + 83696
6 IOGPU
0x00000001ca352000 + 22564
7 AGXMetalA12
0x00000001f23b1000 + 927020
8 AGXMetalA12
0x00000001f23b1000 + 208948
9 Flutter
GrMtlCommandBuffer::getRenderCommandEncoder(MTLRenderPassDescriptor*, GrMtlPipelineState const*, GrMtlOpsRenderPass*) (GrMtlCommandBuffer.mm:0)
10 Flutter
GrMtlOpsRenderPass::precreateCmdEncoder() (GrMtlOpsRenderPass.mm:38)
11 Flutter
GrMtlOpsRenderPass::GrMtlOpsRenderPass(GrMtlGpu*, GrRenderTarget*, GrSurfaceOrigin, GrOpsRenderPass::LoadAndStoreInfo const&, GrOpsRenderPass::StencilLoadAndStoreInfo const&) (GrMtlOpsRenderPass.mm:240)
12 Flutter
GrMtlGpu::onGetOpsRenderPass(GrRenderTarget*, GrAttachment*, GrSurfaceOrigin, SkIRect const&, GrOpsRenderPass::LoadAndStoreInfo const&, GrOpsRenderPass::StencilLoadAndStoreInfo const&, SkTArray<GrSurfaceProxy*, true> const&, GrXferBarrierFlags) (GrMtlGpu.mm:198)
13 Flutter
GrOpsTask::onExecute(GrOpFlushState*) (GrOpsTask.cpp:634)
14 Flutter
GrDrawingManager::flush(SkSpan<GrSurfaceProxy*>, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrBackendSurfaceMutableState const*) (GrDrawingManager.cpp:358)
15 Flutter
GrDrawingManager::flushSurfaces(SkSpan<GrSurfaceProxy*>, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrBackendSurfaceMutableState const*) (GrDrawingManager.cpp:537)
16 Flutter
SkCanvas::onFlush() (GrDirectContext.cpp:375)
17 Flutter
_ZNSt3__110__function6__funcIZN7flutter15GPUSurfaceMetal28AcquireFrameFromCAMetalLayerERK7SkISizeE3$_0NS_9allocatorIS7_EEFbRKNS2_12SurfaceFrameEP8SkCanvasEEclESC_OSE_ (gpu_surface_metal.mm:93)
18 Flutter
flutter::SurfaceFrame::Submit() (surface_frame.cc:43)
19 Flutter
flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) (functional:1902)
20 Flutter
_ZNSt3__110__function6__funcIZN7flutter10Rasterizer4DrawEN3fml6RefPtrINS2_8PipelineINS2_9LayerTreeEEEEENS_8functionIFbRS7_EEEE3$_1NS_9allocatorISE_EEFvNS_10unique_ptrIS7_NS_14default_deleteIS7_EEEEEEclEOSK_ (rasterizer.cc:338)
21 Flutter
flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >, std::__1::function<bool (flutter::LayerTree&)>) (memory:2648)
22 Flutter
_ZNSt3__110__function6__funcIZN7flutter5Shell14OnAnimatorDrawEN3fml6RefPtrINS2_8PipelineINS2_9LayerTreeEEEEENS4_9TimePointEE4$_33NS_9allocatorISB_EEFvvEEclEv (functional:1818)
23 Flutter
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:121)
24 Flutter
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
25 CoreFoundation
0x00000001814a2000 + 713336
29 CoreFoundation
CFRunLoopRunSpecific + 600
30 Flutter
fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:47)
31 Flutter
_ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ (message_loop_impl.cc:0)
32 libsystem_pthread.dylib
_pthread_start + 148
```

**Comment by TahaTesser** [comment] 2021-09-27 10:12
Hi @xioFei 
Does the issuer reproduce locally?  Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without third-party packages

Can you also please provide your `flutter doctor -v`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by plx-tech** [comment] 2021-10-09 12:52
We can confirm that we observe the very same bug from our Crashlytics console only on users running iOS 15+ and only in our apps that use multiple flutter engines.

Sometimes (but not always) It happens while the main thread is performing some cleanup routine while receiving the applicationDidEnterBackground Notification.

When the main thread is "clean" (like in the last stack trace), we observed that sometimes other threads are processing callbacks related to the applicationWillResignActive Notification.

The app is currently running on Flutter 2.5.1 stable and like we said above we are not observing any crashes from iOS 14 or lower.

any raster thread:
```
Crashed: home.2.raster
0  libsystem_kernel.dylib         0x79c4 __pthread_kill + 8
1  libsystem_pthread.dylib        0x7434 pthread_kill + 268
2  libsystem_c.dylib              0x1ff64 abort + 164
3  Metal                          0xbe250 MTLGetWarningMode + 218
4  IOGPU                          0x3ba8 IOGPUResourceGetClientShared + 242
5  Metal                          0x146f0 -[_MTLCommandEncoder initWithCommandBuffer:] + 884
6  IOGPU                          0x5824 -[IOGPUMetalCommandEncoder initWithCommandBuffer:] + 56
7  AGXMetalA13                    0x108694 (Missing)
8  AGXMetalA13                    0x36f84 (Missing)
9  Flutter                        0x287de8 GrMtlCommandBuffer::getRenderCommandEncoder(MTLRenderPassDescriptor*, GrMtlPipelineState const*, GrMtlOpsRenderPass*) + 4370152936
10 Flutter                        0x28e4a8 GrMtlOpsRenderPass::GrMtlOpsRenderPass(GrMtlGpu*, GrRenderTarget*, sk_sp<GrMtlFramebuffer>, GrSurfaceOrigin, GrOpsRenderPass::LoadAndStoreInfo const&, GrOpsRenderPass::StencilLoadAndStoreInfo const&) + 4370179240
11 Flutter                        0x28b584 GrMtlGpu::onGetOpsRenderPass(GrRenderTarget*, bool, GrAttachment*, GrSurfaceOrigin, SkIRect const&, GrOpsRenderPass::LoadAndStoreInfo const&, GrOpsRenderPass::StencilLoadAndStoreInfo const&, SkTArray<GrSurfaceProxy*, true> const&, GrXferBarrierFlags) + 4370167172
12 Flutter                        0x19cfd0 GrOpsTask::onExecute(GrOpFlushState*) + 4369190864
13 Flutter                        0x1920c4 GrDrawingManager::flush(SkSpan<GrSurfaceProxy*>, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrBackendSurfaceMutableState const*) + 4369146052
14 Flutter                        0x1924b0 GrDrawingManager::flushSurfaces(SkSpan<GrSurfaceProxy*>, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrBackendSurfaceMutableState const*) + 4369147056
15 Flutter                        0x58c34 SkCanvas::onFlush() + 4367862836
16 Flutter                        0x4f63f0 std::__1::__function::__func<flutter::GPUSurfaceMetal::AcquireFrameFromCAMetalLayer(SkISize const&)::$_1, std::__1::allocator<flutter::GPUSurfaceMetal::AcquireFrameFromCAMetalLayer(SkISize const&)::$_1>, bool (flutter::SurfaceFrame const&, SkCanvas*)>::operator()(flutter::SurfaceFrame const&, SkCanvas*&&) + 4372702192
17 Flutter                        0x409fc4 flutter::SurfaceFrame::Submit() + 4371734468
18 Flutter                        0x341d3c flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&) + 4370914620
19 Flutter                        0x349bd4 std::__1::__function::__func<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDrawLastLayerTree(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)::$_15>, std::__1::allocator<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDrawLastLayerTree(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)::$_15> >, void ()>::operator()() + 4370947028
20 Flutter                        0x2ee068 fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 4370571368
21 Flutter                        0x2f1098 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 4370583704
22 CoreFoundation                 0xae278 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
23 CoreFoundation                 0x32c50 __CFRunLoopDoTimer + 1076
24 CoreFoundation                 0x2d44c __CFRunLoopDoTimers + 328
25 CoreFoundation                 0xbc68 __CFRunLoopRun + 1944
26 CoreFoundation                 0x1f3c8 CFRunLoopRunSpecific + 600
27 Flutter                        0x2f0f74 fml::MessageLoopDarwin::Run() + 4370583412
28 Flutter                        0x2f0788 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 4370581384
29 libsystem_pthread.dylib        0x1a60 _pthread_start + 148
30 libsystem_pthread.dylib        0xf5c thread_start + 8
```

main thread when crashing while performing applicationDidEnterBackground:
```
com.apple.main-thread
0  libsystem_kernel.dylib         0x1ff0 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8274 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2ef36c fml::AutoResetWaitableEvent::Wait() + 4366955372
4  Flutter                        0x3444c0 flutter::Shell::OnPlatformViewDestroyed() + 4367303872
5  Flutter                        0x2b724 -[FlutterViewController surfaceUpdated:] + 4364056356
6  Flutter                        0x2c448 -[FlutterViewController applicationDidEnterBackground:] + 4364059720
7  CoreFoundation                 0x2aee8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8  CoreFoundation                 0xc6b9c ___CFXRegistrationPost_block_invoke + 52
9  CoreFoundation                 0x99f54 _CFXRegistrationPost + 456
10 CoreFoundation                 0x40d54 _CFXNotificationPost + 716
11 Foundation                     0x1b028 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
12 UIKitCore                      0x266f0c __47-[UIApplication _applicationDidEnterBackground]_block_invoke + 316
13 UIKitCore                      0x1c6664 +[UIViewController _performWithoutDeferringTransitionsAllowingAnimation:actions:] + 164
14 UIKitCore                      0x400124 -[UIApplication _applicationDidEnterBackground] + 144
15 UIKitCore                      0x1f4efc __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke_2 + 840
16 UIKitCore                      0x1af29c _UIScenePerformActionsWithLifecycleActionMask + 104
17 UIKitCore                      0x2db9b4 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 224
18 UIKitCore                      0x3fc45c -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 248
19 UIKitCore                      0x63dacc -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 760
20 UIKitCore                      0x5c91f0 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 340
21 UIKitCore                      0x1b00a0 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 196
22 UIKitCore                      0x270688 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 892
23 UIKitCore                      0x1b1fb0 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 276
24 UIKitCore                      0x29d1e8 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 384
25 UIKitCore                      0x725b0c __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.610 + 776
26 UIKitCore                      0x1e0db8 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 256
27 UIKitCore                      0x2244f0 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 288
28 UIKitCore                      0x1adfe0 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 492
29 FrontBoardServices             0xd110 -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:] + 528
30 FrontBoardServices             0x25d5c __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2 + 152
31 FrontBoardServices             0xa6c4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
32 FrontBoardServices             0x10b20 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke + 396
33 libdispatch.dylib              0x3950 _dispatch_client_callout + 20
34 libdispatch.dylib              0x73e8 _dispatch_block_invoke_direct + 264
35 FrontBoardServices             0xbfa4 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
36 FrontBoardServices             0xb3e4 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
37 FrontBoardServices             0xf9f4 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
38 CoreFoundation                 0xbb030 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
39 CoreFoundation                 0xcbcf0 __CFRunLoopDoSource0 + 208
40 CoreFoundation                 0x5ff8 __CFRunLoopDoSources0 + 268
41 CoreFoundation                 0xb804 __CFRunLoopRun + 820
42 CoreFoundation                 0x1f3c8 CFRunLoopRunSpecific + 600
43 GraphicsServices               0x138c GSEventRunModal + 164
44 UIKitCore                      0x51b0bc -[UIApplication _run] + 1100
45 UIKitCore                      0x298be8 UIApplicationMain + 2124
46 libswiftUIKit.dylib            0x31184 UIApplicationMain(_:_:_:_:) + 104
47 App                       0x5f80 main + 4332003200 (Assets+App.swift:4332003200)
48 ???                            0x104b45a24 (Missing)
```

main thread in all other crashes:
```
com.apple.main-thread
0  libsystem_kernel.dylib         0x1564 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1bfc mach_msg + 76
2  CoreFoundation                 0x7698 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb98c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3c8 CFRunLoopRunSpecific + 600
5  GraphicsServices               0x138c GSEventRunModal + 164
6  UIKitCore                      0x51b0bc -[UIApplication _run] + 1100
7  UIKitCore                      0x298be8 UIApplicationMain + 2124
8  libswiftUIKit.dylib            0x31184 UIApplicationMain(_:_:_:_:) + 104
9  App                       0x5f80 main + 4341276544 (Assets+App.swift:4341276544)
10 ???                            0x104f2da24 (Missing)`
```

**Comment by gaaclarke** [comment] 2021-10-11 21:55
@sroddy  I suspect this has been fixed in https://github.com/flutter/engine/pull/28383  The reason why is that PR put a guard around submitting a surface that didn't exist previously, and that's exactly the backtrace you have.

That hasn't rolled to stable yet.  Here is the roll commit: https://github.com/flutter/flutter/commit/947034ed82a3e3cd99f2a5d8b5297d28ac13eb24

**Closed by gaaclarke** 2021-10-11 21:55 UTC
Labels: waiting for customer response, in triage
