### ISSUE TITLE
Build APK fails with unknown property 'runtimeConfiguration' error

### ISSUE THREAD

**Issue by MahdiPishguy** [flutter/flutter#45680] opened 2019-11-27 09:49 UTC
when i try to build apk from my current application i get this error:

> FAILURE: Build failed with an exception.
> 
> * Where: Initialization script 'C:\flutter\packages\flutter_tools\gradle\aar_init_script.gradle'
> line: 122
> 
> * What went wrong: Could not get unknown property 'runtimeConfiguration' for object of type
> com.android.build.gradle.internal.api.LibraryVariantImpl.

and i'm not sure whats that and how can i resolve

**gradle-wrapper.properties:**

    #Fri Jun 23 08:50:38 CEST 2017
    distributionBase=GRADLE_USER_HOME
    distributionPath=wrapper/dists
    zipStoreBase=GRADLE_USER_HOME
    zipStorePath=wrapper/dists
    distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

**build.gradle:**

    classpath 'com.android.tools.build:gradle:3.5.2'

doctor command output:

```
[√] Flutter (Channel beta, v1.11.0, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.11.0 at C:\flutter
    • Framework revision 856a90e67c (3 weeks ago), 2019-11-08 18:00:01 -0800
    • Engine revision af04338413
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at G:\software\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = G:\software\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.0)
    • VS Code at C:\Users\mahdi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • WAS LX1A • 2XJDU17C14006203 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

```

**Comment by iapicca** [comment] 2019-11-27 12:57
Hi @MahdiPishguy 
could you please provide your `flutter build --verbose` ?
Thank you

**Comment by MahdiPishguy** [comment] 2019-11-27 13:52
@iapicca yes sure,

```
G:\Projects\Flutter\unlimited_power_pro>flutter build --verbose
[  +70 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +74 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 856a90e67c9284124d44d2be6c785bacd3a1c772
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +100 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.11.0-0-g856a90e67c
[   +8 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +34 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
Missing subcommand for "flutter build".
```

**Comment by iapicca** [comment] 2019-11-27 14:48
Hi @MahdiPishguy 

the logs seems to point to a androidx incompatibility in the plugins

```
[   +2 ms] The built failed likely due to AndroidX incompatibilities in a plugin. 
The tool is about to try using Jetfier to solve the incompatibility.

```

do the proposed [solutions](https://stackoverflow.com/questions/56539737/how-to-fix-flutter-androidx-incompatibility) fix the issue?
thank you

**Comment by MahdiPishguy** [comment] 2019-11-27 20:17
@iapicca i tested your linked me solution before creating new issue here, unfortunately it doesn't any change :(

**gradle.properties :**

```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```

app **build.gradle:**

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "xx.xxxx.xxxxxxxxx"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

**Comment by gordianknot1981** [comment] 2019-12-10 02:31
@MahdiPishguy 

I got the same issue of  packaging audioplayer and the error message, **"build fail with unknown property 'runtimeConfiguration'"**,  also quite similar with you.  But all things  was ever going well before downgrading flutter to v1.11.0, so I upgrade flutter back to v1.12.13+hotfix.3, then I got an error message as below:


```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audioplayer:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\gordianknot\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontStyle not found.

     C:\Users\gordianknot\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/font not found.

     C:\Users\gordianknot\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontWeight not found.

     C:\Users\gordianknot\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\gordianknot\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      37.4s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin audioplayer...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    3.6s
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to D:\Users\gordianknot\AppData\Local\Android\android-sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.

BUILD FAILED

Total time: 3.336 secs


FAILURE: Build failed with an exception.

* Where:
Initialization script 'E:\flutter\packages\flutter_tools\gradle\aar_init_script.gradle' line: 122

* What went wrong:
Could not get unknown property 'runtimeConfiguration' for object of type com.android.build.gradle.internal.api.LibraryVariantImpl.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


The plugin audioplayer could not be built due to the issue above.
```

and I set compileSdkVersion of audioplayer to 28 to match the sdkversion used in my project.
```groovy
android {
    compileSdkVersion 28 // 25
//    buildToolsVersion '25.0.3'
    ...
}
```

then It works....
hope it works for you.

**Comment by Ricardokanitz** [comment] 2020-03-08 16:20
I had the same situation change "audioplayer" plugin for "audioplayers" and it worked.

**Comment by iapicca** [comment] 2020-03-09 12:44
Hi @MahdiPishguy 
are you experiencing the issue with the latest stable version of flutter?
Please note that both [audioplayers](https://pub.dev/packages/audioplayers) ([github](https://github.com/luanpotter/audioplayers/issues)) and [audioplayer](https://pub.dev/packages/audioplayer) ([github](https://github.com/rxlabz/audioplayer/issues)) are 3rd party plugin; 
if you believe the issue being caused by said plugins, 
please open an issue in the dedicated gitub
Thank you

**Comment by jmagman** [comment] 2020-03-30 20:08
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-03-30 20:08 UTC
Labels: severe: crash, t: gradle, tool, waiting for customer response, ▣ platform-android

**Comment by parsadoc** [comment] 2020-04-07 14:01
i had this issue too,
i solve the error by changing my library package  from audioplayer to another one.
you can use other library like 
audioplayers,
audiofileplayer or just_audio
