### ISSUE TITLE
Flutter web app not opening in android mobile browser though on apple mobile browsers, it works fine

### ISSUE THREAD

**Issue by koxxyPro** [flutter/flutter#129175] opened 2023-06-20 14:33 UTC

**Comment by dam-ease** [comment] 2023-06-20 14:52
Hi @koxxyPro
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps

Closing this issue, since little information has been provided. Thanks!

**Closed** 2023-06-20 14:52 UTC
Labels: in triage

**Comment by koxxyPro** [comment] 2023-06-20 15:03
This is what is seen when I inspect in chrome dev tools

Uncaught MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
    at Object.f (https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:4185:3)
    at https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:90120:15
    at bjE.a (https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:5488:62)
    at bjE.$2 (https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:50989:14)
    at bim.$1 (https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:50983:21)
    at bdw.aWo (https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:52182:34)
    at bdw.Dr (https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:52184:21)
    at b6B.$0 (https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:51457:11)
    at Object.Fx (https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:5628:40)
    at al.q2 (https://shop.kilimofresh.co.tz/main.dart.js?version=7.0:51381:3)
