### ISSUE TITLE
The application's Info.plist does not contain a valid CFBundleShortVersionString.

### ISSUE THREAD

**Issue by hellohejinyu** [flutter/flutter#113907] opened 2022-10-23 08:12 UTC
## Steps to Reproduce

1. Create a new project.
2. Run `flutter pub add tencent_im_sdk_plugin`.
3. Run `flutter run` to run it on iPhone simulator.
4. Flutter throw 'The application's Info.plist does not contain a valid CFBundleShortVersionString.'.

**Expected results:** 

Works fine.

**Actual results:** 

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/8766034/197381031-0537c8b7-8a6b-4a8b-a570-07872c128175.png">

<details>
<summary>Code sample</summary>

[https://github.com/hellohejinyu/flutter_ios_bundle_version_missed](https://github.com/hellohejinyu/flutter_ios_bundle_version_missed)

</details>

<details>
  <summary>Logs</summary>

[log.txt](https://github.com/flutter/flutter/files/9845986/log.txt)

```
Analyzing flutter_ios_bundler_version_missed...                         
No issues found! (ran in 1.4s)
```

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.4 on channel stable at /Users/Jinyu/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (3 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/Jinyu/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/Jinyu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[!] Connected device
    ! No devices available

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by nLoser** [comment] 2022-10-23 16:06
这样问题google一下就能查到原因，不用上来就提issue。
问题明显是xcode command line tools提示的问题，说明iOS工程中的version没有获取到。可以用xcode打开ios 项目，然后检查一下version、build、info.plist

**Comment by hellohejinyu** [comment] 2022-10-23 23:36
> 这样问题google一下就能查到原因，不用上来就提issue。
> 
> 问题明显是xcode command line tools提示的问题，说明iOS工程中的version没有获取到。可以用xcode打开ios 项目，然后检查一下version、build、info.plist

Why are you so confident that I didn't do these operations? I even found that tencent_im_sdk_plugin@4.1.3 version does not cause this bug. And I also pulled down the two versions of the code to compare. I didn't find anything suspicious, so I came to file an issue for Flutter.

**Comment by huycozy** [comment] 2022-10-24 09:04
Hi @hellohejinyu 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the [tencent_im_sdk_plugin repository](https://github.com/TencentCloud/TIMSDK/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2022-10-24 09:04 UTC
Labels: in triage
