### ISSUE TITLE
Syntax highlighting doesn't work in tests

### ISSUE THREAD

**Issue by RenatFakhrutdinov** [flutter/flutter#70426] opened 2020-11-13 01:42 UTC
## Steps to Reproduce

Working in AndroidStudio I found that syntax highlighting stopped working in test dart files today. Highlighting works well in regular dart files. Also test run buttons are gone. Tests from the console are run. But writing tests without syntax highlighting is very inconvenient. Flutter doctor shows that flutter plugin is not installed but it's actually installed.

## Logs

```
[✓] Flutter (Channel unknown, 1.20.4, on Mac OS X 10.15.7 19H15, locale ru-RU)
    • Flutter version 1.20.4 at /Users/macbookpro/flutter
    • Framework revision fba99f6cf9 (8 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.193
```

**Comment by TahaTesser** [comment] 2020-11-13 09:43
Hi @RenatFakhrutdinov 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-13 09:43 UTC
