### ISSUE TITLE
DefaultTextStyle doc includes many blank properties

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#9433] opened 2017-04-17 21:55 UTC
I'm referring to the first 6 `-> dynamic` unnamed properties in the screenshot below.

![screenshot](https://cloud.githubusercontent.com/assets/1377460/25106329/bae8bd88-237d-11e7-9147-83c38e16b31d.png)

**Comment by Hixie** [comment] 2017-04-17 22:00
dupe of https://github.com/dart-lang/dartdoc/issues/1367

**Closed by Hixie** 2017-04-17 22:00 UTC
Labels: dev: docs - api
