### ISSUE TITLE
TextField cursor's problem with emoji

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#28192] opened 2019-02-20 06:31 UTC
Since cursor's height has changed on IOS, it works good with Chinese. but now I found that there may some problem work with emoji.
<img width="397" alt="qq20190220-142309 2x" src="https://user-images.githubusercontent.com/23414420/53070979-be9f2280-351b-11e9-962c-cfb504b2c392.png">
<img width="397" alt="qq20190220-142247 2x" src="https://user-images.githubusercontent.com/23414420/53070981-bfd04f80-351b-11e9-87bd-faaa385d2a7d.png">

**Comment by hahafather007** [comment] 2019-02-20 06:33
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.2.1-pre.2, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```
Code:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        alignment: Alignment.topCenter,
        child: TextField(),
      ),
    );
  }
}

```

**Comment by zoechi** [comment] 2019-02-20 08:58
Looks similar to #19935

Not sure if #27612 is supposed to fix this 
@GaryQian ?

**Comment by GaryQian** [comment] 2019-02-20 09:49
It is likely caused by something we have dealt with before. #27612 does not fix this.

**Comment by FE-Mars** [comment] 2019-06-20 10:06
I've got the same problem

**Comment by GaryQian** [comment] 2019-06-20 17:25
Are you seeing this with both iOS and Android?

**Comment by littlered-zz** [comment] 2019-08-21 08:04
how is the issue going? we still met the problem in 1.7.8 HOT FIX4

**Comment by MHJcoder** [comment] 2019-09-12 07:15
I still met the problem in 1.9

**Comment by MHJcoder** [comment] 2019-09-12 07:21
> Are you seeing this with both iOS and Android?

As I can see ,both will

**Comment by GaryQian** [comment] 2020-03-23 20:09
We have recently landed using strut height for carets. Can you confirm this is fixed/still existing?

**Comment by justinmc** [comment] 2020-04-06 18:26
It looks like it's working to me, or am I reproducing it wrong?

![Screen Shot 2020-04-06 at 11 22 54 AM](https://user-images.githubusercontent.com/389558/78592073-57b0fb80-77f9-11ea-8d07-f46b1408cb11.png)
![Screen Shot 2020-04-06 at 11 26 14 AM](https://user-images.githubusercontent.com/389558/78592136-73b49d00-77f9-11ea-8d40-dfc30aa05181.png)

**Comment by jmagman** [comment] 2020-04-30 01:11
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-04-30 01:11 UTC
Labels: a: text input, a: typography, engine, waiting for customer response
