### ISSUE TITLE
Jank on first ListView.builder build

### ISSUE THREAD

**Issue by SBNTT** [flutter/flutter#68105] opened 2020-10-14 14:39 UTC
```dart
main() {
  runApp(MaterialApp(
    home: ListViewPage(),
  ));
}

class ListViewPage extends StatelessWidget {
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: 1000,
        itemBuilder: (context, index) {
          return ListTile(
            title: Text("Dummy title"),
            subtitle: Text("Index = $index"), 
            trailing: IconButton(
              icon: const Icon(Icons.arrow_forward_ios),
              onPressed: () { },
            ),
          );
        },
      ),
    );
  }
}
```

I ran this in profile mode in a real device (OnePlus 6).

It seems like Flutter take to much time to lay out all the visibles items during the first build

````
[✓] Flutter (Channel stable, 1.22.1, on macOS 11.0 20A5384c, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
[✓] VS Code (version 1.50.0)
[✓] Connected device (1 available)
```

**Comment by sidrao2006** [comment] 2020-10-14 15:59
Suggestion - As mentioned in the docs, providing the `itemExtent` parameter imroves performance. Could you please try that?

**Comment by PixelToast** [comment] 2020-10-14 20:57
Could you post the exact performance metrics you are observing?

I wouldn't expect the provided `ListView.builder` to take very long to build, are you including how long it takes to build MaterialApp initially too?

**Comment by SBNTT** [comment] 2020-10-15 07:24
MaterialApp is not included because i don't use exactly the code i provided in OP. Instead, i'm using a blank page with a button as a homePage. When this button is pressed, it push the `ListViewPage`.
Here is a capture of the timeline after the `ListViewPage` was pushed:

![Dart DevTools](https://user-images.githubusercontent.com/20710321/96089730-8b1ac400-0ec7-11eb-8407-39fd1d07a6bb.png)

It takes more than 40ms just to build the visible items.

Don't know about `itemExtend`, i'll try that

**Comment by TahaTesser** [comment] 2020-10-15 12:50
Hi @SBNTT 
Can you please provide details of the device or emulator you're experiencing this issue on?  your doctor -v doesn't  this data 
Is it iOS or Android?

**Comment by SBNTT** [comment] 2020-10-15 13:22
Hi, I said I was using a OnePlus 6 in OP :)
I do not have a real iOS device to try sorry

**Comment by TahaTesser** [comment] 2020-10-16 08:24
Hi @SBNTT 
The issue isn't reproducible on Android 10 device Realme 6, have you tried any other android device or emulator?
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.1 at C:\Code\flutter_stable
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at C:\Code\android-studio\
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\Code\android-studio\
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • RMX2001 (mobile)                   • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86   • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by pedromassangocode** [comment] 2020-11-06 10:29
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-06 10:29 UTC
