### ISSUE TITLE
#35000 GestureDetector problem

### ISSUE THREAD

**Issue by wasabia** [flutter/flutter#51635] opened 2020-02-28 14:58 UTC
the red Container GestureDetector can not catch tap event

```
import 'package:flutter/material.dart';



class DemoOnePage extends StatefulWidget {
  DemoOnePage({Key key}) : super(key: key);

  @override
  createState() => DemoOnePageState();
}

class DemoOnePageState extends State<DemoOnePage> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("demo"),),
      body: _build(context)
    );
  }

  _build(BuildContext context) {
    return Container(
      color: Colors.yellow,
      width: 300,
      height: 300,
      child: Center(
        child: GestureDetector(
          onTap: () {
            print(" green is tapped ");
          },
          child: Container(
            color: Colors.green,
            width: 50,
            height: 50,
            child: Stack(
              overflow: Overflow.visible,
              children: <Widget>[
                Positioned(
                  left: -50,
                  top: 0,
                  child: GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: () {
                      print("tap....");
                    },
                    onPanDown: (DragDownDetails details) {
                      print("onPanDown....");
                    },
                    child: Container(
                      width: 50,
                      height: 50,
                      color: Colors.red,
                    ),
                  ),
                )
              ],
            ),
          ),
        )
      ),
    );
  }

}

```

[✓] Flutter (Channel master, v1.15.3-pre.17, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.3)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)

**Comment by TahaTesser** [comment] 2020-02-28 15:15
Hi @wasabia 
Running your code

Definitely an issue, `GestureDetector` inside `Stack` doesn't get detected. 
![untitled](https://user-images.githubusercontent.com/48603081/75560453-2eb78100-5a6b-11ea-9aa9-2196ea609808.gif)

Thank you

**Comment by goderbauer** [comment] 2020-03-05 00:08
Duplicate of https://github.com/flutter/flutter/issues/19445.

**Closed by goderbauer** 2020-03-05 00:08 UTC
Labels: f: gestures, framework
