### ISSUE TITLE
Cannot open RawDatagramSocket with port less than 1024

### ISSUE THREAD

**Issue by Jack-Overflow** [flutter/flutter#51238] opened 2020-02-22 00:48 UTC
I'm attempting to use port 9 on the RawDatagramSocket to send a wake on LAN packet. When attempting to open a socket with a port that is less than 1024 it throws an error on android but not iOS.

## Steps to Reproduce

1. Attempt to open a RawDatagramSocket binding to a port that is less than 1024
```
RawDatagramSocket.bind(InternetAddress.anyIPv4, 9)
        .then((RawDatagramSocket udpSocket) {
      udpSocket.broadcastEnabled = true;

      List<int> packet = [1];
      udpSocket.send(packet, ipAddress, 9);
      udpSocket.close();
    });
```
2. Observe that on iOS the socket is opened and the packet is send successfuly however on android the following error is thrown:

```
E/flutter ( 6064): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Permission denied, errno = 13), address = 0.0.0.0, port = 9
E/flutter ( 6064): #0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:668:7)
E/flutter ( 6064): <asynchronous suspension>
E/flutter ( 6064): #1      _RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1986:26)
E/flutter ( 6064): #2      RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1944:31)
E/flutter ( 6064): #3      WakeOnLanService.wake (package:wolow/services/wake-on-lan.service.dart:7:30)
E/flutter ( 6064): #4      _HomePageState.wakeUpDevice (package:wolow/pages/home.dart:59:10)
E/flutter ( 6064): #5      _HomePageState.build.<anonymous closure> (package:wolow/pages/home.dart:83:31)
E/flutter ( 6064): #6      Header.build.<anonymous closure> (package:wolow/widgets/header.dart:58:15)
E/flutter ( 6064): #7      WakeUpButton.build.<anonymous closure> (package:wolow/widgets/wake-up-button.dart:29:11)
E/flutter ( 6064): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:705:14)
E/flutter ( 6064): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:788:36)
E/flutter ( 6064): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 6064): #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 6064): #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 6064): #13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 6064): #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
E/flutter ( 6064): #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 6064): #16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 6064): #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 6064): #18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 6064): #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 6064): #20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 6064): #21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 6064): #22     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 6064): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 6064): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 6064): #25     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 6064): #26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 6064): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 6064): #28     _invoke1 (dart:ui/hooks.dart:274:10)
E/flutter ( 6064): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:183:5)
E/flutter ( 6064): 
```

**Expected results:** 
I wanted the android version of the app to function the same as the iOS version and open the socket on port 9 and send the packet without throwing an error.

**Actual results:** 
The following error is thrown:
```
E/flutter ( 6064): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Permission denied, errno = 13), address = 0.0.0.0, port = 9
E/flutter ( 6064): #0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:668:7)
E/flutter ( 6064): <asynchronous suspension>
E/flutter ( 6064): #1      _RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1986:26)
E/flutter ( 6064): #2      RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1944:31)
E/flutter ( 6064): #3      WakeOnLanService.wake (package:wolow/services/wake-on-lan.service.dart:7:30)
E/flutter ( 6064): #4      _HomePageState.wakeUpDevice (package:wolow/pages/home.dart:59:10)
E/flutter ( 6064): #5      _HomePageState.build.<anonymous closure> (package:wolow/pages/home.dart:83:31)
E/flutter ( 6064): #6      Header.build.<anonymous closure> (package:wolow/widgets/header.dart:58:15)
E/flutter ( 6064): #7      WakeUpButton.build.<anonymous closure> (package:wolow/widgets/wake-up-button.dart:29:11)
E/flutter ( 6064): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:705:14)
E/flutter ( 6064): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:788:36)
E/flutter ( 6064): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 6064): #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 6064): #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 6064): #13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 6064): #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
E/flutter ( 6064): #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 6064): #16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 6064): #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 6064): #18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 6064): #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 6064): #20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 6064): #21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 6064): #22     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 6064): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 6064): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 6064): #25     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 6064): #26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 6064): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 6064): #28     _invoke1 (dart:ui/hooks.dart:274:10)
E/flutter ( 6064): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:183:5)
E/flutter ( 6064): 
```

<details>
  <summary>Logs</summary>

```
jack@Jacks-MacBook-Pro wolow % flutter analyze
Analyzing wolow...                                                      

   info • Unused import: 'dart:io' • lib/widgets/device-selection.dart:1:8 • unused_import
   info • Unused import: 'package:wolow/types/callback.dart' • lib/widgets/wake-up-button.dart:4:8 • unused_import

```

```
jack@Jacks-MacBook-Pro wolow % flutter doctor -v
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.14.6 at /Users/jack/Library/Google/flutter
    • Framework revision fabeb2a16f (3 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jack/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/jack/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6186006/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/jack/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6186006/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Users/jack/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 4 categories.

```

</details>

**Comment by TahaTesser** [comment] 2020-02-24 12:21
Hi @Jack-Overflow 
"On Unix you can't listen to ports less than 1024 unless you're root, so this is working as intended."  [Reference](https://github.com/flutter/flutter/issues/42499#issuecomment-545201906) in [#42499](https://github.com/flutter/flutter/issues/42499)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-02-24 12:21 UTC
