### ISSUE TITLE
http2 error in http2 connection  cause websocket receives no message

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#73953] opened 2021-01-14 16:01 UTC
reproduce step
1. set up web socket (in dart:io) and echo message;
```
socket = await WebSocket.connect(strUrl);
    recorder.ready();
    await for (String message in socket) {
     print("get $message");
...
}
````

```
another timer to send message to server using the socket;
```
every thing works well;

2. use http2 in flutter plugin to send http request, but the server doesn't support http protocal,so server just reset the connection
3. websocket will not get message from server again, but server will still receive message from client;

**Comment by TahaTesser** [comment] 2021-01-15 07:32
Hi @wanjm 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http2/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-15 07:32 UTC
