### ISSUE TITLE
flutter test hangs when you have a missing dependency

### ISSUE THREAD

**Issue by mikejurka** [flutter/flutter#3362] opened 2016-04-15 21:51 UTC
## Steps to Reproduce

Take a test suite. Remove "test" from the pubspec.yaml file and run ``pub get``. Then run ``flutter test``

Similarly, I took my test suite but commented out the dependency to ``import 'package:typed_mock/typed_mock.dart';`` . Then I ran ``flutter test``

Expected:
test fails immediately because of dependency issue

Actual result:
test hangs, and keeps waiting for a long time until a timeout. gives no information about the dependency issues

**Comment by eseidelGoogle** [comment] 2016-04-15 21:53
Looks like a dupe of https://github.com/flutter/flutter/issues/3305 ?

**Closed** 2016-04-15 21:57 UTC
