### ISSUE TITLE
Something wrong when using Multiple Flutter instances architecture

### ISSUE THREAD

**Issue by HaloWang** [flutter/flutter#119403] opened 2023-01-28 07:16 UTC
## Steps to Reproduce

1. open official tutorial of [Multiple Flutter instances](https://docs.flutter.dev/development/add-to-app/multiple-flutters)
2. Go to [sample section](https://docs.flutter.dev/development/add-to-app/multiple-flutters#samples) and download the [source code of demo](https://github.com/flutter/samples/tree/main/add_to_app/multiple_flutters)
3. Open Xcode, build and run the demo codes
4. Click "Next", Click "Next", Click "Next", You will now see a `DoubleFlutterViewController` in navigation stack, Click "Add" or whatever, everything work well.
5. Find the VM service url in the Xcode console panel, something like "http://127.0.0.1:64278/NhIZ5kDP4SU=/", open it in the chrome.
6. You will find three isolate in the `Isolate Group`, reasonable, three different entry point function.
7. select last isolate, debug it, `reload` it, the app running in iPhone simulator now have no response forever.

**Expected results:** 

Everything work well especially `reload`

**Actual results:** 

App has no response after invoking `reload` command. Both official demo and my own app.

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.2 22D49 darwin-arm64, locale en-CN)
    • Flutter version 3.7.0 on channel stable at /Users/wangce/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (4 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/wangce/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (4 available)
    • HaloWang’s iPad (mobile)                  • 00008103-001911122160801E            • ios            • iOS 16.2 20C65
    • iPhone SE (3rd generation) (mobile) • 71606565-105E-445D-BCF6-1B3F8CA19867 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.2 22D49
      darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome
      109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by HaloWang** [comment] 2023-01-28 08:58
Sync state througth multiple flutter instance by some codes (which I can see in official demo) looks over-complex.

I wonder is this approach still recommended when facing "A screen where multiple partial screen Flutter views might be integrated and visible at once", after flutter team introduce an early preview of [Multiple Windows on Desktop](https://youtu.be/vtB-teu57vw).

Will this document dropped in further flutter releases?

**Comment by darshankawar** [comment] 2023-01-30 08:08
Thanks for the detailed report. Using steps to replicate as mentioned, I was able to replicate the reported behavior. Selected the last isolate as mentioned and reloaded it, but the app seems to hang as shown below:

<img width="1381" alt="Screenshot 2023-01-30 at 1 33 30 PM" src="https://user-images.githubusercontent.com/67046386/215421701-eb2f18a5-6e57-4c9b-aafc-daa8852e5735.png">
<img width="840" alt="Screenshot 2023-01-30 at 1 36 43 PM" src="https://user-images.githubusercontent.com/67046386/215421708-6f7b8cd8-930d-4a5a-9676-5415f1ea5bd5.png">


https://user-images.githubusercontent.com/67046386/215421730-e2a9c33c-56a1-4a42-b502-2d80a639236d.mov

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (28 hours ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-29.0.pre.26, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.7.0-29.0.pre.26 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 15cd00f1ed (2 hours ago), 2023-01-29 21:58:05 -0500
    • Engine revision a7bb0e4108
    • Dart version 3.0.0 (build 3.0.0-179.0.dev)
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by chinmaygarde** [comment] 2023-01-30 19:01
cc @rmacnak-google @a-siva I am not sure what the behavior of `reload` when invoked from the Dart debugger. It can't be a hot-reload or restart because the engine isn't involved.

**Comment by a-siva** [comment] 2024-02-08 17:38
@HaloWang @darshankawar it is unclear why you were using the observatory to debug the app, can you try using 'dart devtools' which is what you should see when connecting to the URL by default with the latest flutter. Can you try and see if the problem still exists when you use 'dart devtools'.

**Comment by a-siva** [comment] 2024-02-08 18:28
@bkonyi I presume this should work when devtools is used for debugging ?

**Comment by bkonyi** [comment] 2024-02-12 21:09
> @bkonyi I presume this should work when devtools is used for debugging ?

I just tried to connect to this sample in DevTools and it turns out it fails to connect (probably due to some missing service extensions that are normally registered by flutter_tools). FYI @kenzieschmoll

**Comment by kenzieschmoll** [comment] 2024-02-14 23:45
> probably due to some missing service extensions that are normally registered by flutter_tools

@bkonyi what were you seeing that made you think this? Where is the hang or exception occurring?

**Comment by bkonyi** [comment] 2024-02-15 20:12
These are the errors I see in the console when I attempt to connect to the application:

```
flutter: Attempted to call extension 'ext.flutter.inspector.structuredErrors', but no service with that name exists
flutter: [ERROR]: [20]-wrapFuture(evaluate,...): Failed
flutter: Timed out trying to fetch flutter version from `ConnectedApp.initializeValues`.
flutter: [ERROR]: 'package:devtools_app/src/shared/diagnostics/inspector_service.dart': Failed assertion: line 41 pos 16: 'serviceConnection.serviceManager.connectedAppInitialized': is not true.
```

**Comment by bkonyi** [comment] 2024-02-15 20:21
Confirmed that removing the call to the `flutterVersion` service allows for a connection.

**Comment by bkonyi** [comment] 2024-02-15 22:34
I'm going to close this issue. The `reload` command in Observatory's debugger doesn't have the necessary awareness of the Flutter specific bits to perform a hot reload for a Flutter application, and now that Observatory is deprecated and no longer served by default for Dart / Flutter applications, we don't plan on adding Flutter hot reload support to the tool.

It's possible to work with this sample application using DevTools, but it's not obvious how to do this without prior knowledge (or reading [these docs](https://docs.flutter.dev/add-to-app/debugging) for debugging add-to-app applications). To get hot reload and hot restart support with this project, you need to follow these steps:

1. Navigate to `samples/add_to_app/multiple_flutters/multiple_flutters_module/`
2. Invoke `flutter attach`

This will start up a Flutter Tools instance which registers all the necessary services for various developer tools to interact with Flutter applications, including those needed for hot reload and hot restart. At this point, you can either open the DevTools URL that's printed to the console after running `flutter attach` or you can use `dart devtools <vm-service-uri>` to launch DevTools. I've filed an issue to have the sample projects for `add_to_app` include documentation for debugging: https://github.com/flutter/flutter/issues/143550. 

Attempting to connect to the VM Service URI directly from DevTools without first running `flutter attach` results in a failed connection, simply because there's some missing services registered by Flutter Tools that it expects to be there for any Flutter application it connects to. This probably shouldn't be a fatal error, and DevTools should simply provide a degraded experience without Flutter specific functionality in this case. This issue is tracked in https://github.com/flutter/devtools/issues/6848.

**Closed by bkonyi** 2024-02-15 22:34 UTC
Labels: platform-ios, waiting for customer response, engine, dependency: dart, a: existing-apps, has reproducible steps, P2, found in release: 3.7, team-ios, triaged-ios, dependency:dart-triaged
