### ISSUE TITLE
Text wrapping options

### ISSUE THREAD

**Issue by VadimOsovsky** [flutter/flutter#40152] opened 2019-09-10 13:45 UTC
## Use case
At the moment if a word doesn't fit on a line flutter moves it to the next line, for longer words especially without spaces (e.g. file path location) it looks ugly. Wrapping by letters would work much better in this case.

![Screenshot_2019-09-10-16-36-38-582_com PrivateRouter PrivateMailFiles](https://user-images.githubusercontent.com/39897981/64618867-bcce7b00-d3e9-11e9-9cf9-ab9bae363845.png)
![IMG_20190910_163752](https://user-images.githubusercontent.com/39897981/64618869-bcce7b00-d3e9-11e9-8121-801333e2b402.jpg)

## Proposal
Sometimes you want to choose how to wrap text, e.g. by words/ letters. You can wrap text anywhere, but you cannot choose where NOT to wrap it. Please add extra options for text wrapping.

**Comment by goderbauer** [comment] 2019-09-11 22:22
This looks like a duplicate of https://github.com/flutter/flutter/issues/18761.

**Closed by goderbauer** 2019-09-11 22:22 UTC
Labels: framework, severe: new feature
