### ISSUE TITLE
`dynamicSchemeVariant` is missing from **ColorScheme.fromSeed**

### ISSUE THREAD

**Issue by sarbagyastha** [flutter/flutter#148380] opened 2024-05-15 06:18 UTC
### Steps to reproduce

As per the [Flutter 3.22 announcement](https://medium.com/flutter/whats-new-in-flutter-3-22-fbde6c164fe3#2d81), the `ColorScheme.fromSeed` should have `dynamicSchemeVariant` property. But it's missing in both `beta` and `stable` branches.

### Expected results

```dart
final colorScheme  = ColorScheme.fromSeed(
        dynamicSchemeVariant: DynamicSchemeVariant.fidelity, // should be allowed
        seedColor: headerBackgroundColor,
        brightness: Brightness.dark,
        surface: Color(0xFF181818),
);
```

### Actual results

```dart
final colorScheme  = ColorScheme.fromSeed(
        dynamicSchemeVariant: DynamicSchemeVariant.fidelity, // The named parameter 'dynamicSchemeVariant' isn't defined.
        seedColor: headerBackgroundColor,
        brightness: Brightness.dark,
        surface: Color(0xFF181818),
);
```

### Code sample

<details open><summary>Code sample</summary>

```dart
final colorScheme  = ColorScheme.fromSeed(
        dynamicSchemeVariant: DynamicSchemeVariant.fidelity, // The named parameter 'dynamicSchemeVariant' isn't defined.
        seedColor: headerBackgroundColor,
        brightness: Brightness.dark,
        surface: Color(0xFF181818),
);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
The named parameter 'dynamicSchemeVariant' isn't defined.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F5074a darwin-arm64, locale
    en-NP)
    • Flutter version 3.22.0 on channel stable at ###
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = ssh://git@github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (6 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at ###
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = ###
    • Java binary at: ###
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = ###

[!] Android Studio (version unknown)
    • Android Studio at ###
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
    • IntelliJ at ###
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 241.15989.9

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • C7C36F3A-8C2A-430C-8A96-E9B4582E2985 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 14.5 23F5074a darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 14.5 23F5074a darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • unknown

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by Zudah228** [comment] 2024-05-15 06:44
I`m confused, too.
In [Breaking Change](https://docs.flutter.dev/release/breaking-changes/new-color-scheme-roles) page, it named `schemeVariant`.

```dart
ColorScheme.fromSeed(
    seedColor: Color(0xFF0000FF), // Bright blue
    schemeVariant: FromSeedVariant.fidelity,
)
```

**Comment by rydmike** [comment] 2024-05-15 09:26
This feature did not land at all in Flutter 3.22.
So yes the documentation is incorrect, and as noted it also talks about `schemeVariant`, in master where the feature exists the property name is `dynamicSchemeVariant`, like the enum `DynamicSchemeVariant` it is based on.

This issue is duplicate of earlier reported issue: https://github.com/flutter/flutter/issues/148359

**Comment by darshankawar** [comment] 2024-05-15 10:12
Closing this as duplicate of https://github.com/flutter/flutter/issues/148359

**Closed by darshankawar** 2024-05-15 10:12 UTC
Labels: in triage
