### ISSUE TITLE
TextField obscured characters jump while typing

### ISSUE THREAD

**Issue by optdxf** [flutter/flutter#155439] opened 2024-09-20 05:46 UTC
### Steps to reproduce

Have a TextField with `obscureText` set to true, and type a variety of characters (e.g. alphanumeric and special characters).

### Expected results

The height of the characters should stay the same.

### Actual results

The height of the characters fluctuates. Similar to: https://github.com/flutter/flutter/issues/59854

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: TextField(
          obscureText: true,
          style: GoogleFonts.inter(
            fontSize: 20,
          ),
        ),
      ),
    ),
  ));
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/68544011-0461-4ff7-a32a-b9db8bc74b8d

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.19045.4894], locale en-US)
    • Flutter version 3.24.1 on channel stable at C:\SDKs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (4 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
```

</details>

**Comment by darshankawar** [comment] 2024-09-20 10:17
Closing this as duplicate of https://github.com/flutter/flutter/issues/147279
@optdxf Please check [this](https://github.com/flutter/flutter/issues/147279#issuecomment-2076696472) solution mentioned in it.

**Closed by darshankawar** 2024-09-20 10:17 UTC
Labels: in triage

**Comment by optdxf** [comment] 2024-09-20 17:49
Tested both enabling and disabling the 'case' font feature as described in the solution. Unfortunately, the problem persists.

`fontFeatures: [const FontFeature.caseSensitiveForms()]`
`fontFeatures: [const FontFeature.enable('case')]`
`fontFeatures: [const FontFeature.disable('case')]`

**Comment by optdxf** [comment] 2024-09-20 17:54
Moving this to https://github.com/flutter/flutter/issues/155469 since this issue has been closed already.
