### ISSUE TITLE
ScrollableViewport overscrolls while height/width animates.

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5167] opened 2016-08-01 17:44 UTC
If you have a `ScrollableViewport` with a child `Widget` that animates it's width/height along the `mainAxis` and as long as the `ScrollableViewport` is scrollable (child doesn't fit), it is possible to overscroll during the animation. When the animation finishes, everything returns to normal.

Sample code to reproduce:

```dart
new ScrollableViewport(
  child: new AnimatedContainer(
    width: 200.0,
    height: 1000.0 * new Random().nextDouble() + 1000.0,
    margin: const EdgeInsets.all(40.0),
    duration: const Duration(seconds: 10),
    decoration: new BoxDecoration(
      backgroundColor: Colors.black
    )
  )
)
```

I've only tested on Android. No clue what this works like on iOS.

**Comment by Hixie** [comment] 2017-11-14 22:55
I should verify if this still happens with the new scrolling code.

**Comment by Hixie** [comment] 2017-12-02 02:53
This reproduces it. Change the height of the container to 10.0 and hot reload, then try to scroll as it shrinks.
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      home: new Material(
        child: new Container(
          color: Colors.blue,
          child: new StatefulBuilder(
            builder: test,
          ),
        ),
      ),
    ),
  );
}

Widget test(BuildContext context, StateSetter setState) {
  return new SingleChildScrollView(
    child: new AnimatedContainer(
      height: 1000.0,
      margin: const EdgeInsets.all(40.0),
      duration: const Duration(seconds: 40),
      decoration: new BoxDecoration(
        color: Colors.green
      ),
      child: const Placeholder(),
    ),
  );
}
```

**Comment by pedromassangocode** [comment] 2020-08-27 11:49
I was not able to reproduce this on latest `master` channel.

![gif](https://user-images.githubusercontent.com/67424416/91438501-5a24f800-e863-11ea-8e65-5192b643f197.gif)


<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.93, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-2.0.pre.93 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision f35a8b7470 (2 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

 
[✓] Connected device (4 available)            
    • iPhone 11 Pro Max (mobile) • B2A481C0-B2C1-495A-9ECA-0D3778F2FCD3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 84.0.4147.135

! Doctor found issues in 3 categories.
```
</details>

I'm closing this as probably fixed. If you disagree please write in the comment bellow providing your `flutter doctor -v` and I will reopen it.

**Closed by pedromassangocode** 2020-08-27 11:49 UTC
Labels: P5, a: animation, f: scrolling, framework, platform-android
