### ISSUE TITLE
Inconsistent Dart analyzer results with recent upgrade

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#7676] opened 2017-01-27 00:34 UTC
## Steps to Reproduce

I recently upgraded Flutter, and got my code working with the recent pubspec.yaml/flutter.yaml merge. However, I'm now seeing some very strange things coming out of the dart analyzer. From the "Dart Analysis" panel in IntelliJ, everything looks great and I'm not seeing any errors or warnings, including when I restart the Dart Analysis Server. However, re-analyzing my sources in Atom gives me a bunch of strange warnings. Also, if I run the dartanalyzer command in Terminal, I'm getting the same warnings as I am in Atom. Note that if I go back to an older version of Flutter from 2 weeks ago, I'm not getting any warnings from dartanalyzer.

I'm confused about why I'm seeing different results in IntelliJ from results using the other methods. I'm also not sure why I'm seeing these warnings.

## Logs

```
dartanalyzer [file names]
[warning] Element 'int' from SDK library 'core.dart' is implicitly hidden by 'popup_menu.dart (via material.dart)' ([filepath], line 63, col 18)
[warning] int is not a type ([filepath], line 63, col 18)
[warning] Element 'List' from SDK library 'core.dart' is implicitly hidden by 'popup_menu.dart (via material.dart)' ([filepath], line 78, col 3)
[warning] List is not a type ([filepath], line 78, col 3)
[warning] int is not a type ([filepath], line 79, col 3)
[warning] List is not a type ([filepath], line 90, col 5)
[warning] List is not a type ([filepath], line 91, col 5)
[warning] int is not a type ([filepath], line 109, col 21)
[warning] int is not a type ([filepath], line 159, col 18)
.
.
.
964 warnings found.
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/emshack/flutter
    • Framework revision 682c7992e5 (46 minutes ago), 2017-01-26 15:43:28
    • Engine revision fb69728f33
    • Tools Dart version 1.22.0-dev.9.1

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin version 163.9166.22
    • Flutter plugin version 0.1.8.1

[✓] Connected devices
    • None
```

**Comment by danrubel** [comment] 2017-01-27 15:02
Do you see these same warnings with `flutter analyze`?

There is a `.analysis_options_user` file in the flutter repo root that is not picked up by `dartanalyzer` and I'm wondering if this is the cause of what you are seeing.

**Comment by emshack** [comment] 2017-01-27 18:45
No, I'm not seeing the same warnings. Should something in my project be configured differently?

**Comment by danrubel** [comment] 2017-01-27 18:50
Nope. That's a bug on my plate to normalize the output between `flutter analyze`, `dartanalyzer`, and analysis server. I'm making progress but there are several changes I need to land before the work is complete. For now, rely on `flutter analyze`.

**Comment by emshack** [comment] 2017-01-27 18:59
Ok, thanks! Please let me know when the changes are in.

**Comment by eseidelGoogle** [comment] 2017-01-27 19:07
@emshack was this a regression?  @danrubel is there a bug @emshack can track?

**Comment by emshack** [comment] 2017-01-27 19:20
Not sure what you mean-- this bug occurred after I updated Flutter, I had never seen these errors before.

**Comment by emshack** [comment] 2017-02-17 00:01
FYI, I just upgraded Dart and this problem went away.

**Comment by eseidelGoogle** [comment] 2017-02-23 21:27
Thanks for the report!  Closing.

**Closed by eseidelGoogle** 2017-02-23 21:27 UTC
Labels: customer: pink

**Comment by mit-mit** [comment] 2017-02-24 10:33
Yes, this was resolved in a recent Dart SDK drop.
