### ISSUE TITLE
Stateful widgets are rebuilt from route stack

### ISSUE THREAD

**Issue by maheshkumar2150** [flutter/flutter#56444] opened 2020-05-06 13:48 UTC
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    print("MyApp");

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    print("MyHomePage");

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: RaisedButton(
          child: Text("Click Me"),
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) => PageOne()));
          },
        ),
      ),
    );
  }
}

class PageOne extends StatefulWidget {
  @override
  _PageOneState createState() => _PageOneState();
}

class _PageOneState extends State<PageOne> {
  @override
  Widget build(BuildContext context) {

    print("Page One");

    return Container(
      child: Center(
        child: RaisedButton(
          child: Text("Click Me"),
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) => PageTwo()));
          },
        ),
      ),
    );
  }
}


class PageTwo extends StatefulWidget {
  @override
  _PageTwoState createState() => _PageTwoState();
}

class _PageTwoState extends State<PageTwo> {
  @override
  Widget build(BuildContext context) {

    print("Page Two");

    return Container(
      child: Center(
        child: RaisedButton(
          child: Text("Click Me"),
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) => PageThree()));
          },
        ),
      ),
    );
  }
}

class PageThree extends StatefulWidget {
  @override
  _PageThreeState createState() => _PageThreeState();
}

class _PageThreeState extends State<PageThree> {
  @override
  Widget build(BuildContext context) {

    print("Page Three");

    return Container(
      child: Center(
        child: RaisedButton(
          child: Text("Click Me"),
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) => PageFour()));
          },
        ),
      ),
    );
  }
}

class PageFour extends StatefulWidget {
  @override
  _PageFourState createState() => _PageFourState();
}

class _PageFourState extends State<PageFour> {
  @override
  Widget build(BuildContext context) {

    print("Page Four");

    return Container(
      child: Center(
        child: RaisedButton(
          child: Text("Click Me"),
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) => PageOne()));
          },
        ),
      ),
    );
  }
}

```
I/flutter ( 6531): Page Four
I/flutter ( 6531): MyHomePage
I/flutter ( 6531): Page One
I/flutter ( 6531): Page Two
I/flutter ( 6531): Page Three

When i pressed the Click Me Buttom from Page Three,
The page Four Widget is loaded. But the widget which are behind the page four are rebuilt without any use.

Is this a bug or am i making any mistake?

**Comment by VladyslavBondarenko** [comment] 2020-05-07 08:36
Hi @maheshkumar2150 
I can't reproduce it with `dev 1.18.0-12.0.pre` and in https://dartpad.dev/ as well.
With what flutter version are you experiencing this?

**Comment by DrKoob** [comment] 2020-05-07 14:00
I would suggest to either push Scaffolds or use a stack in your homepage to display your containers. 
Btw here you don't need to have any  StatefulWidget since you are never setting state :))

**Comment by lenva** [comment] 2020-05-14 08:20
This bug exists in version 1.12 and has been fixed in version 1.17

**Comment by maheshkumar2150** [comment] 2020-05-14 09:45
After upgrading to 1.17, the problem is solved for me. Thanks.

**Comment by VladyslavBondarenko** [comment] 2020-05-14 10:00
Then closing as fixed

**Closed by VladyslavBondarenko** 2020-05-14 10:00 UTC
Labels: in triage
