### ISSUE TITLE
Emojis in ListView with BouncingScrollPhysics are not rendered as expected on iOS

### ISSUE THREAD

**Issue by Nico3652** [flutter/flutter#118154] opened 2023-01-08 11:18 UTC
While creating a social & chat-app I have found one more time an ugly render for Emojis in ```ListView``` while using ```BouncingScrollPhysics``` :

https://user-images.githubusercontent.com/50270977/211192573-d43f57ee-7c2e-43c0-9961-a233704d2c83.mp4

This is happening only when Emojis are the last item in List with a ```Text("")``` widget alone and only on iOS according my tests.
Same problem found on Textfield...
 
This issue is certainly link to the main and famous emoji problem mentioned here #28894 

**Workarounds :** 

- Not using ```BouncingScrollPhysics```
- Wrap ```Text``` widget with ```Container``` owning an empty ```BoxDecoration```

Despite the workarounds it would be great to found solutions in general way to improve the Emoji render and mainly on iOS because chat-app are not ready-to-prod in that way. 

----------------------------------------
FULL CODE 
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}


class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: EmojiBouncingPage()
    );
  }
}

class MessageObject {
  String content;
  bool sender;

  MessageObject({required this.content, required this.sender});
}

class EmojiBouncingPage extends StatefulWidget {
  const EmojiBouncingPage({Key? key}) : super(key: key);

  @override
  State<EmojiBouncingPage> createState() => _EmojiBouncingPageState();
}

class _EmojiBouncingPageState extends State<EmojiBouncingPage> {
  List<MessageObject> messageList = [];

  @override
  void initState() {
    final tempList = [
      MessageObject(content: "Hello friend !", sender: false),
      MessageObject(content: "Hey how are you doing today ?", sender: true),
      MessageObject(
          content:
              "Not very well actually i'm still facing issues with Emoji in my flutter app...",
          sender: false),
      MessageObject(
          content:
              "Hm there is nothing that you can do to workaround this or fix it ?",
          sender: true),
      MessageObject(content: "😵‍💫😵‍💫", sender: false),
    ];
    messageList.addAll(tempList.reversed);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        title: Text("Emoji Test Page"),
      ),
      body: SafeArea(
        top: false,
        child: Column(
          children: [
            Expanded(
              child: ListView.builder(
                  reverse: true,
                  scrollDirection: Axis.vertical,
                  itemCount: messageList.length,
                  physics: BouncingScrollPhysics(),
                  padding: EdgeInsets.only(left: 8.0, right: 8.0, top: 500),
                  itemBuilder: (ctx, index) {
                    final message = messageList[index];
                    final bool isEmoji = index == 0;
                    return Align(
                      alignment: message.sender
                          ? Alignment.centerRight
                          : Alignment.centerLeft,
                      child: Container(
                        decoration: isEmoji
                            ? null
                            : BoxDecoration(
                                border: Border.all(
                                    color: message.sender
                                        ? Colors.white.withOpacity(0.5)
                                        : Colors.blue.withOpacity(0.5)),
                                borderRadius: BorderRadius.circular(10)),
                        padding: EdgeInsets.all(10),
                        margin: EdgeInsets.only(
                            top: 15,
                            right: message.sender ? 0 : 100,
                            left: message.sender ? 100 : 0),
                        child: Text(
                          message.content,
                          style: TextStyle(
                              color: Colors.white,
                              fontSize: isEmoji ? 50 : null),
                        ),
                      ),
                    );
                  }),
            ),
            SizedBox(height: 10),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: CupertinoTextField(
                placeholder: "Write message",
                placeholderStyle: TextStyle(
                  color: Colors.white,
                ),
                padding: EdgeInsets.all(10),
                decoration: BoxDecoration(color: Colors.blue),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

----------------------------------------
FLUTTER DOCTOR 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2023-01-09 07:33
Hi @Nico3652, I can reproduce this on `stable` but not on `beta` or `master`. See the recordings below

Can you confirm if this is the case for you as well or there's another scenario where this reproduces on the master or beta channels?

<details>
<summary>recordings</summary>

| stable | beta & master | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/211258541-d427b824-7f0c-421d-b02c-e0919dac0c61.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/211258555-4139ce97-b676-4e5e-933c-b31cd7f59bb8.mp4" /> |

</details>

**Comment by jason-simmons** [comment] 2023-01-10 21:26
This looks like a duplicate of https://github.com/flutter/flutter/issues/108590, which has been fixed on the master branch.

**Comment by danagbemava-nc** [comment] 2023-01-11 05:51
Closing this as fixed based on https://github.com/flutter/flutter/issues/118154#issuecomment-1377891883 and https://github.com/flutter/flutter/issues/118154#issuecomment-1375208602

**Closed by danagbemava-nc** 2023-01-11 05:51 UTC
Labels: waiting for customer response, in triage
