### ISSUE TITLE
[androidx-migration] Require to migrate but nothing to migrate 

### ISSUE THREAD

**Issue by thanhbinh84** [flutter/flutter#118231] opened 2023-01-10 08:35 UTC
## Steps to Reproduce

1. Execute `flutter pub get` on the code sample 
2. Show error  `The plugin `wallet_connect_android` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.` 
3. Follow the instruction to migrate to androidx 
**Expected results:** 
Succed to migrate 
**Actual results:** 
![Screen Shot 2023-01-10 at 15 22 01](https://user-images.githubusercontent.com/366768/211498788-234e10f8-9de7-4da2-a0b3-4db5903e703e.png)
<details>
<summary>Code sample</summary>

https://github.com/tokoinofficial/wallet_connect/tree/integrate_wallet_connect_android_x

</details>

<details>
  <summary>Logs</summary>

[flutter_run_verbose_log.txt](https://github.com/flutter/flutter/files/10380613/flutter_run_verbose_log.txt)

```
ntbinh@Binhs-MacBook-Pro wallet_connect % flutter analyze
Analyzing wallet_connect...                                             
No issues found! (ran in 4.8s)
```

```
ntbinh@Binhs-MacBook-Pro wallet_connect % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6.2 21G320 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/ntbinh/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ntbinh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 12.6.2 21G320 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

![Screen Shot 2023-01-10 at 15 31 39](https://user-images.githubusercontent.com/366768/211500442-20759a95-dea1-478f-ac9d-0e8b31f12280.png)

**Comment by stuartmorgan** [comment] 2023-01-10 13:18
> I also see this issue on the latest master channel.

Are you sure you saw the same error message? The incorrect link was changed in https://github.com/flutter/flutter/pull/107456 (which isn't in 3.3, but is on master).

**Comment by huycozy** [comment] 2023-01-10 13:46
>Are you sure you saw the same error message? The incorrect link was changed in https://github.com/flutter/flutter/pull/107456 (which isn't in 3.3, but is on master).

No, the message is not the same exactly but it's about migration issue in general I mean. Below are output messages on stable and master channels: (sorry for missing this)

### Stable
```
Running "flutter pub get" in wallet_connect...                      3.3s
Running "flutter pub get" in example...                          2,777ms
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `wallet_connect_android` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and
re-run this command.
```

### Master
```
Running "flutter pub get" in wallet_connect...
Resolving dependencies... (1.6s)
Got dependencies!
Resolving dependencies in ./example... 
Got dependencies in ./example.
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `wallet_connect_android` requires your app to be migrated to the Android embedding v2. Follow the steps on the migration doc above and re-run this command.

```

**Comment by stuartmorgan** [comment] 2023-01-10 14:35
The bug is that the second link on `stable` is linking to the wrong migration. AndroidX migration and embedding v2 migration aren't the same thing, and the actual problem here is that the project needs a v2 migration.

Closing as fixed on master since the bad link doesn't exist in the `master` error message. The v2 embedding notification and wiki instructions link are expected behavior here.

**Closed by stuartmorgan** 2023-01-10 14:35 UTC
Labels: platform-android, tool, has reproducible steps, found in release: 3.3, found in release: 3.7
