### ISSUE TITLE
UiKitView Gesture Failure in Rolling Container & UiKitView Display problems

### ISSUE THREAD

**Issue by hetian9288** [flutter/flutter#25751] opened 2018-12-25 10:45 UTC
1. UiKitView Gesture Failure in Rolling Container
2. UiKitView displays errors in the scroll container and the outer layer of the container UiKitView as shown in the figure
![ezgif-1-a0bb8dbf595c](https://user-images.githubusercontent.com/5409513/50420941-30892180-0875-11e9-8e7d-eb89976e8717.gif)

## Steps to Reproduce
```dart
class _FlutterTTADFeedState extends State<FlutterTTADFeed> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return Text("dddd");
    } else if (defaultTargetPlatform == TargetPlatform.iOS) {
      return UiKitView(
        viewType: "plugins.hetian.me/ttview_feed",
        creationParams: {
          "index": widget.index,
        },
        creationParamsCodec: const StandardMessageCodec(),
        onPlatformViewCreated: _onPlatformViewCreated,
        gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
          new Factory<OneSequenceGestureRecognizer>(
                    () => new TapGestureRecognizer(),
          ),
        ].toSet(),
      );
    } else {
      return Text('$defaultTargetPlatform 平台暂不支持FlutterTTPlugin插件');
    }
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
  }

  void _onPlatformViewCreated(int id) {
    print("feedviewID$id");
//    widget.onCreate(FlutterGDTBannerController._(id));
  }

}


CustomScrollView(
              slivers: <Widget>[
                len > 0
                    ? SliverToBoxAdapter(
                        child: Container(
                          height: 320,
                          color: cs[1],
                          child: FlutterTTADFeed(index: 1),
                        ),
                      )
                    : SliverToBoxAdapter(
                        child: Container(
                          height: 320,
                          color: cs[0],
                        ),
                      ),
                SliverList(
                  delegate: SliverChildBuilderDelegate(
                    (context, index) {
                      return Container(
                        width: MediaQuery.of(context).size.width,
                        height: 320,
                        child: Text(
                          index.toString(),
                        ),
                      );
                    },
                    childCount: 10,
                  ),
                )
              ],
            )
```

UIView
```
UIButton *btn = [[UIButton alloc] initWithFrame:CGRectMake(12.0, 12.0, 120, 45)];
    [btn setTitle:@"测试测试测试测试" forState:UIControlStateNormal];
    [btn addTarget:self action:@selector(actions) forControlEvents:UIControlEventTouchDown];
    [self addSubview:btn];
```

`flutter doctor -v`
```
[✓] Flutter (Channel dev, v1.1.4, on Mac OS X 10.13.6 17G3025, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.1)
[✓] Connected device (2 available)
```

**Comment by darshankawar** [comment] 2020-10-20 10:06
@hetian9288 
Is this still a valid issue on latest Flutter version ? I tried your code sample but seems to be incomplete.
If issue persists, please provide a complete reproducible code sample that we can copy paste and run that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment] 2020-11-11 10:16
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-11 10:16 UTC
Labels: P4, a: existing-apps, engine
