### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by hupo376787** [flutter/flutter#29795] opened 2019-03-22 12:56 UTC
Hi, I used to be a Microsoft uwp developer, now turning to Flutter.
But If Flutter support uwp, that will be perfect.

[This issue will be closed in a few days, just let the flutter team hear the voice.]

**Comment by WesleyKhoiVo** [comment] 2019-05-25 14:44
#30726

**Comment by stuartmorgan** [comment] 2019-05-25 14:56
Closing as a duplicate of 30726 and #14967

**Closed by stuartmorgan** 2019-05-25 14:56 UTC
