### ISSUE TITLE
flutter doctor implies I need both iOS and Android toolchains installed to just try Flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#17781] opened 2018-05-21 20:35 UTC
Flutter doctor is amazing! But, for the first hour, it may be (incorrectly) suggesting that you need _both_ iOS and Android toolchains installed _just to try Flutter_.

See anecdote here: https://twitter.com/clarklab/status/998613583599669250

**Comment by AlexK22** [comment] 2018-05-21 21:10
A heading that tells which tools to install would be good. Something like this
For Android development install:
• ...

For iOS development install:
• ...

**Comment by timsneath** [comment] 2018-05-21 22:19
adding @mit-mit

**Comment by mit-mit** [comment] 2018-05-22 14:03
> A heading that tells which tools to install would be good

The current Android and iOS headings do (attempt) to explain this:

`Android toolchain - develop for Android devices` / `iOS toolchain - develop for iOS devices`

Is the core issue that this language isn't strong enough, or that it's easily missed among all the other text?

**Comment by timsneath** [comment] 2018-05-22 14:27
I think we've trained (and continue to train) developers that a successful installation is one where the output of `flutter doctor` is fully checked. 

In https://flutter.io/setup-windows/, for instance, we tell you:

> run the following command to see if there are any dependencies you need to install to complete the setup

There's no indication that one or the other is sufficient to start developing, either in the tool or the accompanying docs. Instead we give you an `[x]` which implies failure/incompletion. 

It might be viable to use the verbose mode for non-essential dependencies, or to add a line to the output of `flutter doctor` if the minimum dependencies are satisfied, along the lines of:

> SUCCESS: you have everything you need to start developing in Flutter. Check the verbose output to see

**Comment by mit-mit** [comment] 2018-05-22 14:33
But how do we determine what is 'essential' vs 'non-essential'. The category of deps we are checking here for is 'essential' to a developer that wants to develop for that platform, but 'non-essential' to the one that doesn't. So we would need some way of asking what platform they are interested in, which get's complicated.

Alternatively, and probably more straightforward we could do what we do for IDEs: omit the checks until "something" is installed for that particular platform (for example, if a developer doesn't have anything from the Android SDK installed, then assume they are not interested in Android, and don't check for anything).

cc @devoncarew ideas?

**Comment by zoechi** [comment] 2019-01-17 11:07
Duplicate of #12768

**Closed by zoechi** 2019-01-17 11:07 UTC
Labels: a: first hour, t: flutter doctor, tool
