### ISSUE TITLE
[go_router] Nested Navigation With ShellRoute

### ISSUE THREAD

**Issue by parsa10** [flutter/flutter#111976] opened 2022-09-20 15:24 UTC
I want to have a `BottomNavigation` inside Another `BottomNavigation` , When i use `ShellRoute` inside another `ShellRoute` , This error is given : 
**`'package:go_router/src/route.dart': Failed assertion: line 442 pos 14: 'route is GoRoute': is not true.`**
As i understood till now , the ShellRoute is not supporting nested navigation properly ! I had problem with implementing TabBar inside a BottomNavigation too.
`go_router v5.0.0`
<details><summary>GoRouterCodeToReproduce</summary>
<p>

```dart
    router = GoRouter(
      navigatorKey: _rootNavigatorKey,
      initialLocation: '/',
      routes: <RouteBase>[
        ShellRoute(
          navigatorKey: _shellNavigatorKey,
          pageBuilder: (context, state, child) => CustomTransitionPage(
            key: state.pageKey,
            transitionDuration: kThemeAnimationDuration,
            child: Material(
              child: Column(
                children: [
                  Expanded(child: ContainerPage(child: child)),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    children: [
                      Padding(
                        padding: const EdgeInsets.all(8),
                        child: Text(state.location),
                      ),
                      ElevatedButton(
                          onPressed: () => context
                              .read<AuthenticationBloc>()
                              .add(const AuthenticationLogoutRequested()),
                          child: const Text("LogOut"))
                    ],
                  ),
                ],
              ),
            ),
            transitionsBuilder: (context, animation, _, child) =>
                FadeTransition(opacity: animation, child: child),
          ),
          // builder: (context, state, child) => ContainerPage(child: child),
          routes: <RouteBase>[
            GoRoute(
              name: 'home',
              path: '/home',
              pageBuilder: (context, state) => CustomTransitionPage(
                key: state.pageKey,
                transitionDuration: kThemeAnimationDuration,
                child: BlocProvider(
                  create: (context) => HomeCubit(
                      itemsRepository: context.read<ItemsRepository>())
                    ..onGetTrendingModel(1),
                  child: const HomePage(),
                ),
                transitionsBuilder: (context, animation, _, child) =>
                    FadeTransition(opacity: animation, child: child),
              ),
              routes: <RouteBase>[
                GoRoute(
                  path: 'detail',
                  builder: (context, state) => const HomePage(),
                )
              ],
            ),
            GoRoute(
              name: 'search',
              path: '/search',
              pageBuilder: (context, state) => CustomTransitionPage(
                key: state.pageKey,
                transitionDuration: kThemeAnimationDuration,
                child: BlocProvider(
                  create: (context) => HomeCubit(
                      itemsRepository: context.read<ItemsRepository>())
                    ..onGetTrendingModel(1),
                  child: const HomePage(),
                ),
                transitionsBuilder: (context, animation, _, child) =>
                    FadeTransition(opacity: animation, child: child),
              ),
              routes: <RouteBase>[
                GoRoute(
                  path: 'detail',
                  builder: (context, state) => const HomePage(),
                )
              ],
            ),
            ShellRoute(
              navigatorKey: _tabBarShellNavigatorKey,
              pageBuilder: (context, state, child) => CustomTransitionPage(
                key: state.pageKey,
                transitionDuration: kThemeAnimationDuration,
                child: LibraryPage(child: child , pageId: state.subloc),
                transitionsBuilder: (context, animation, _, child) =>
                    FadeTransition(opacity: animation, child: child),
              ),
              routes: [
                GoRoute(
                  name: 'history',
                  path: '/history',
                  pageBuilder: (context, state) => CustomTransitionPage(
                    key: state.pageKey,
                    transitionDuration: kThemeAnimationDuration,
                    child: const HistoryPage(),
                    transitionsBuilder: (context, animation, _, child) =>
                        FadeTransition(opacity: animation, child: child),
                  ),
                ),
                GoRoute(
                  name: 'comments',
                  path: '/comments',
                  pageBuilder: (context, state) => CustomTransitionPage(
                    key: state.pageKey,
                    transitionDuration: kThemeAnimationDuration,
                    child: const CommentsPage(),
                    transitionsBuilder: (context, animation, _, child) =>
                        FadeTransition(opacity: animation, child: child),
                  ),
                ),
                GoRoute(
                  name: 'favorites',
                  path: '/favorites',
                  pageBuilder: (context, state) => CustomTransitionPage(
                    key: state.pageKey,
                    transitionDuration: kThemeAnimationDuration,
                    child: const FavoritesPage(),
                    transitionsBuilder: (context, animation, _, child) =>
                        FadeTransition(opacity: animation, child: child),
                  ),
                ),
              ],
            ),
            GoRoute(
              name: 'setting',
              path: '/setting',
              pageBuilder: (context, state) => CustomTransitionPage(
                key: state.pageKey,
                transitionDuration: kThemeAnimationDuration,
                child: const SettingPage(),
                transitionsBuilder: (context, animation, _, child) =>
                    FadeTransition(opacity: animation, child: child),
              ),
              routes: <RouteBase>[
                GoRoute(
                  path: 'detail',
                  builder: (context, state) => const SettingPage(),
                )
              ],
            ),
          ],
        ),
        GoRoute(
          name: 'login',
          path: '/login',
          pageBuilder: (context, state) => CustomTransitionPage(
            key: state.pageKey,
            transitionDuration: const Duration(milliseconds: 200),
            child: BlocProvider(
                create: (context) => AuthenticationCubit(
                    authenticationRepository:
                        context.read<AuthenticationRepository>(),
                    hiveDatabaseRepository:
                        context.read<HiveDatabaseRepository>()),
                child: LoginPage(key: state.pageKey)),
            transitionsBuilder:
                (context, animation, secondaryAnimation, child) =>
                    FadeTransition(
              opacity: animation,
              child: child,
            ),
          ),
        ),
        GoRoute(
          name: 'root',
          path: '/',
          redirect: (context, state) => '/home',
        ),
      ],
      errorBuilder: (context, state) {
        return const NotFound404Page();
      },
      redirect: (context, redirectState) {
        // if the user is not logged in, they need to login
        final authenticated = context.read<AuthenticationBloc>().state.status ==
            AuthenticationStatus.authenticated;
        final loggingIn = redirectState.subloc == '/login';
        // bundle the location the user is coming from into a query parameter
        final fromp =
            redirectState.subloc == '/' ? '' : '?from=${redirectState.subloc}';
        //TODO Add AuthenticationRequired status to get the event whenever we needed authenticating.
        // if (!authenticated) return loggingIn ? null : '/login$fromp';

        // if the user is logged in, send them where they were going before (or
        // home if they weren't going anywhere)
        if (loggingIn && authenticated) {
          return redirectState.queryParams['from'] ?? '/';
        }
        // no need to redirect at all
        return null;
      },
      // changes on the listenable will cause the router to refresh it's route
      refreshListenable:
          RefreshStream(context.read<AuthenticationBloc>().stream),
      debugLogDiagnostics: true,
    );

```

</p>
</details>

**Comment by johnpryan** [comment] 2022-09-20 16:16
Duplicate of https://github.com/flutter/flutter/issues/111981

**Closed by johnpryan** 2022-09-20 16:16 UTC
