### ISSUE TITLE
Flutter version constraints are not working for versions >=2.0.0

### ISSUE THREAD

**Issue by 0ttik** [flutter/flutter#80610] opened 2021-04-17 00:16 UTC
**Bug description**

I'm getting no error despite flutter version requirements are not satisfied.

**Expected behaviour**

To get error like I get when I'm on older flutter versions. For example with flutter `1.22.5` and environment restrinctions like:
```
environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.0.0 <1.2.0"
```
I get an error running `flutter pub get` saying:

```
The current Flutter SDK version is 1.22.5.

Because [app_name] requires Flutter SDK version >=1.0.0 <1.2.0, version solving failed.
pub get failed (1; Because [app_name] requires Flutter SDK version >=1.0.0 <1.2.0, version solving failed.)
```

**Reproduction**
1. Create new flutter project with last flutter version from stable channel (`>=2.0.0`)
2. Make environment section of `pubspec.yaml` file look like this: 
```
environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.4 <1.23.0"
```
3. Run `flutter pub get`
4. Get no error despite flutter version requirements are not satisfied.

**Comment by darshankawar** [comment] 2021-04-19 07:25
I am not sure if this is a bug or intended functionality. 
Keeping this open for further insights.

**Comment by 0ttik** [comment] 2021-04-22 21:51
I don't understand why this could be an indented functionality. Why would flutter stop showing errors if version constraints are not satisfied after 2.0 versions?

**Comment by christopherfujino** [comment] 2022-05-05 16:37
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/95472. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2022-05-05 16:37 UTC
Labels: tool, has reproducible steps, found in release: 2.0
