### ISSUE TITLE
Horizontal scrolling not working

### ISSUE THREAD

**Issue by Hardebayho** [flutter/flutter#87904] opened 2021-08-08 13:18 UTC
I don't know what's wrong, but I cannot scroll horizontally in flutter. This happens both on Web Desktop and Desktop (Linux). I thought it was something with my app so I created a new flutter project.

## Steps to Reproduce

* Create new flutter project
* Paste the following code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Scaffold(body: MyHomePage()),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView(
      scrollDirection: Axis.horizontal,
      children: List.generate(
          50,
          (index) => Container(
              color: Colors.blue,
              width: 80,
              margin: const EdgeInsets.all(8.0),
              child: Text('Index $index'))),
    );
  }
}
```

**Expected results:** 
ListView widget scrolls its children horizontally.

**Actual results:** 
Nothing. It does absolutely nothing. I tried with my mouse and touchpad and I was unable to scroll.

<details>

```
```

flutter doctor -v:
```
[✓] Flutter (Channel dev, 2.5.0-1.0.pre, on Solus 4.3 Fortitude
    5.11.21-179.current, locale en_US.UTF-8)
    • Flutter version 2.5.0-1.0.pre at /home/adebayo/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 184e5871be (13 days ago), 2021-07-26 04:38:02 -0400
    • Engine revision a877f6fed6
    • Dart version 2.14.0 (build 2.14.0-350.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/adebayo/Programs/AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/adebayo/Programs/AndroidSDK
    • Java binary at: /home/adebayo/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.20.2
    • ninja version 1.10.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/adebayo/Downloads/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Solus 4.3 Fortitude
      5.11.21-179.current
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2021-08-09 09:48
Hi @Hardebayho,  

Since flutter v2.3.0-12.0.pre and above scrolling is disabled by default on the web and Desktop, This behavior was changed in #81569 to fix the unexpected ability to scroll by dragging with a mouse. However, this can be completely restored using the [migration guide](https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag)

Closing this issue as this is intended if you still face the issue after using the migration Guide feel free to write back with more details and the updated reproducible code.

Thank you.

**Comment by Hardebayho** [comment] 2021-08-09 13:17
My intention is not to scroll by dragging a mouse. When I'm using a web app or a desktop app, Shift+Mouse wheel is supposed to scroll a scrollable horizontally. The point of this is that horizontal scrolling does not work by default on desktop.

Even when I try to use my touch pad, it still doesn't work. Scrolling a table for instance that can be scrolled both horizontally and vertically will only ever scroll vertically. Is this also intended behavior?

To make things worse, it doesn't even show any scrollbar that can possibly be used instead. Just right now, horizontal scrolling works not.

**Comment by Hardebayho** [comment] 2021-08-09 13:23
If it's not how it's supposed to work by default, please reopen the issue or enlighten me on how I'm supposed to map Shift+mouse wheel to enable horizontal scrolling.

**Comment by Hardebayho** [comment] 2021-08-09 13:44
And speaking of defaults, are users supposed to expect that their widget cannot scroll horizontally by default on web and desktop? I don't see how that's a good thing

**Comment by maheshmnj** [comment] 2021-08-10 11:36
> Even when I try to use my touchpad, it still doesn't work.

Thanks for the clarification, I ran your sample code on the latest dev and it works fine  for me I can scroll the list horizontally by using the touch pad.

>  how I'm supposed to map Shift+mouse wheel to enable horizontal scrolling.
Shift + scroll is currently not supported and is being tracked here https://github.com/flutter/flutter/issues/75180

I would suggest your to please either try the scroll migration guide [as mentioned here](https://github.com/flutter/flutter/issues/87904#issuecomment-895091075) or try switching to stable channel

**Comment by maheshmnj** [comment] 2021-08-11 07:20
@Hardebayho, The main goal of the migration guide is to enable/disable drag gestures to mimic the native behaviour.
Until #75180 is closed you may either prefer using a scrollbar or switch to stable channel.
Closing this issue as solved. Feel free to comment if you disagree and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-08-11 07:20 UTC
