### ISSUE TITLE
Frequent Exit Code 1 error on apk installation from Windows

### ISSUE THREAD

**Issue by Skylled** [flutter/flutter#9638] opened 2017-04-27 16:47 UTC
## Steps to Reproduce

I'm using Powershell from within VSCode, and about 30% of the time `flutter run` will crash at the `Installing build\app/outputs/apk/app.apk...` step.
If I immediately try `adb install -r build\app\outputs\apk\app.apk` the install succeeds with no issue, but obviously no debugging.
I've tried doing `adb kill-server` before each run. I've tried `flutter run --no-build`. Nothing works 100% of the time, and the logs all look identical.

I'm going to start regularly using -v so I can maybe give better logs next time it happens.
(Don't mind the host error, I was offline this last time.)

## Shell log

```
Launching lib/main.dart on LG H910 in debug mode...
Running 'gradle assembleDebug'...
Built build\app/outputs/apk/app-debug.apk (21.9MB).
Installing build\app/outputs/apk/app.apk...

Oops; flutter has exited unexpectedly: "Exit code 1 from: C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd install -r build\app
/outputs/apk/app.apk".
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Failed host lookup: 'clients2.google.com' (OS Error: No such
host is known.
, errno = 11001)
Crash report written to C:\Users\Kyle\Source\Flutter\Cybertronix\flutter_11.log;
please let us know at https://github.com/flutter/flutter/issues.
```

## flutter_11.log

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

String: Exit code 1 from: C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd install -r build\app/outputs/apk/app.apk

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:214)
<asynchronous suspension>
#1      AndroidDevice.installApp (package:flutter_tools/src/android/android_device.dart:241)
<asynchronous suspension>
#2      AndroidDevice._installLatestApp (package:flutter_tools/src/android/android_device.dart:281)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:335)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:203)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:291)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>
#7      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:205)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     Future.Future.sync (dart:async/future.dart:208)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#15     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1465)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#24     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 6.3.9600], channel master)
    • Flutter at C:\flutter
    • Framework revision e2cd78358f (19 hours ago), 2017-04-26 13:14:31 -0700
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at C:\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

[✓] Connected devices
    • LG H910 • LGH9107a67a5fd • android-arm • Android 7.0 (API 24)

```

**Comment by eseidelGoogle** [comment] 2017-04-27 17:21
@goderbauer would know. :)

**Comment by goderbauer** [comment] 2017-04-27 17:59
Looks like adb always returns 1 when something goes wrong :(. A failing run with `-v` might be more helpful in debugging this. Please post it here, if you're able to reproduce it with `-v`.

Also, can you please start Android Studio and use the SDK Manager there to update to the latest Android Platform Tools? The release notes mention that some crashes of adb on Windows were fixed in the most recent release (version 25.0.5).

**Comment by Skylled** [comment] 2017-04-27 18:15
I will make both of those changes.
If I don't get another crash by this evening, I'll call it fixed.

**Comment by Skylled** [comment] 2017-04-27 18:31
First try after upgrading the Platform-Tools, it failed in a much more informative way.

Key line, to my novice eyes anyway, is
`[+1362 ms] Failed to install build\app/outputs/apk/app.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl703449352.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]`

## flutter run -v
```
[  +32 ms] [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [C:\flutter\] git ls-remote --get-url origin
[  +41 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\flutter\] git log -n 1 --pretty=format:%H
[  +42 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 2891772846d661b5b30b8f69599667476ab49aca
[        ] [C:\flutter\] git log -n 1 --pretty=format:%ar
[  +33 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 hours ago
[ +400 ms] C:\Android\sdk\platform-tools\adb devices -l
[+4098 ms] Exit code 0 from: C:\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           * daemon not running. starting it now at tcp:5037 *
           * daemon started successfully *
           LGH9107a67a5fd         device product:elsa_att_us model:LG_H910 device:elsa
[  +45 ms] C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd shell getprop
[ +873 ms] Launching lib/main.dart on LG H910 in debug mode...
[ +151 ms] Using gradle from C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat.
[   +1 ms] [android\] C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat app:properties
[+2323 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat app:properties
[   +2 ms] C:\Android\sdk\build-tools\25.0.2\aapt dump badging build\app/outputs/apk/app.apk
[  +18 ms] Exit code 0 from: C:\Android\sdk\build-tools\25.0.2\aapt dump badging build\app/outputs/apk/app.apk
[        ] package: name='com.yourcompany.Cybertronix' versionCode='1' versionName='0.0.1' platformBuildVersionName='7.1.1'
           sdkVersion:'16'
           targetSdkVersion:'21'
           uses-permission: name='android.permission.INTERNET'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.yourcompany.Cybertronix.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales:
           densities: '160' '240' '320' '480' '640'
           native-code: 'armeabi-v7a' 'x86' 'x86_64'
[   +7 ms] C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd logcat -v time -t 1
[ +189 ms] Exit code 0 from: C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd logcat -v time -t 1
[        ] --------- beginning of main
           04-27 13:21:48.367 D/libc    (32654): getaddrinfo called from pid =32654
[   +6 ms] C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd logcat -v time
[ +458 ms] DependencyChecker: C:\Users\Kyle\Source\Flutter\Cybertronix\.packages is newer than 2017-04-27 10:38:29.000
[   +7 ms] C:\Android\sdk\platform-tools\adb version
[  +34 ms] Android Debug Bridge version 1.0.39
           Revision 3db08f2c6889-android
           Installed as C:\Android\sdk\platform-tools\adb.EXE
[   +4 ms] C:\Android\sdk\platform-tools\adb start-server
[  +14 ms] Building APK
[  +91 ms] Found plugin url_launcher at C:\Users\Kyle\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-0.2.0\
[  +30 ms] Using gradle from C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat.
[   +3 ms] Running 'gradle assembleDebug'...
[   +2 ms] [android\] C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat -Ptarget=C:\Users\Kyle\Source\Flutt
er\Cybertronix\lib/main.dart assembleDebug
[+2534 ms] Incremental java compilation is an incubating feature.
[  +16 ms] The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskI
nputs.file(Object).skipWhenEmpty() instead.
[  +35 ms]      at build_bhixzqu22wz2op93jnb3b0cud$_run_closure2.doCall(C:\Users\Kyle\Source\Flutter\Cybertronix\android\build.gra
dle:20)
[+4658 ms] :app:flutterBuildX86Jar
[   +2 ms] :app:preBuild UP-TO-DATE
[        ] :app:preDebugBuild UP-TO-DATE
[        ] :app:checkDebugManifest
[        ] :app:preProfileBuild UP-TO-DATE
[   +1 ms] :app:preReleaseBuild UP-TO-DATE
[        ] :url_launcher:preBuild UP-TO-DATE
[        ] :url_launcher:preReleaseBuild UP-TO-DATE
[   +1 ms] :url_launcher:checkReleaseManifest
[   +1 ms] :url_launcher:prepareReleaseDependencies
[   +4 ms] :url_launcher:compileReleaseAidl UP-TO-DATE
[   +2 ms] :url_launcher:compileReleaseNdk UP-TO-DATE
[   +1 ms] :url_launcher:compileLint UP-TO-DATE
[   +1 ms] :url_launcher:copyReleaseLint UP-TO-DATE
[   +2 ms] :url_launcher:mergeReleaseShaders UP-TO-DATE
[   +2 ms] :url_launcher:compileReleaseShaders UP-TO-DATE
[        ] :url_launcher:generateReleaseAssets UP-TO-DATE
[   +7 ms] :url_launcher:mergeReleaseAssets UP-TO-DATE
[   +1 ms] :url_launcher:mergeReleaseProguardFiles UP-TO-DATE
[   +2 ms] :url_launcher:packageReleaseRenderscript UP-TO-DATE
[   +7 ms] :url_launcher:compileReleaseRenderscript UP-TO-DATE
[   +3 ms] :url_launcher:generateReleaseResValues UP-TO-DATE
[        ] :url_launcher:generateReleaseResources UP-TO-DATE
[   +6 ms] :url_launcher:packageReleaseResources UP-TO-DATE
[   +5 ms] :url_launcher:processReleaseManifest UP-TO-DATE
[   +4 ms] :url_launcher:generateReleaseBuildConfig UP-TO-DATE
[   +5 ms] :url_launcher:processReleaseResources UP-TO-DATE
[        ] :url_launcher:generateReleaseSources UP-TO-DATE
[   +7 ms] :url_launcher:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
[ +636 ms] :url_launcher:compileReleaseJavaWithJavac
[        ] Full recompilation is required because 'flutter.jar' was changed. Analysis took 0.449 secs.
[+1011 ms] :url_launcher:processReleaseJavaRes UP-TO-DATE
[        ] :url_launcher:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
[   +4 ms] :url_launcher:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
[  +18 ms] :url_launcher:mergeReleaseJniLibFolders UP-TO-DATE
[   +1 ms] :url_launcher:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
[   +1 ms] :url_launcher:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
[        ] :url_launcher:bundleRelease UP-TO-DATE
[   +2 ms] :app:prepareIoFlutterPluginsUrl_launcherUrl_launcher10SNAPSHOTLibrary UP-TO-DATE
[   +1 ms] :app:prepareDebugDependencies
[   +6 ms] :app:compileDebugAidl UP-TO-DATE
[   +7 ms] :app:compileDebugRenderscript UP-TO-DATE
[   +3 ms] :app:generateDebugBuildConfig UP-TO-DATE
[+8673 ms] :app:flutterBuildDebug
[   +3 ms] :app:mergeDebugShaders UP-TO-DATE
[   +2 ms] :app:compileDebugShaders UP-TO-DATE
[        ] :app:generateDebugAssets UP-TO-DATE
[   +4 ms] :app:mergeDebugAssets UP-TO-DATE
[  +24 ms] :app:copyFlutterAssetsDebug
[   +2 ms] :app:generateDebugResValues UP-TO-DATE
[        ] :app:generateDebugResources UP-TO-DATE
[   +6 ms] :app:mergeDebugResources UP-TO-DATE
[   +6 ms] :app:processDebugManifest UP-TO-DATE
[   +6 ms] :app:processDebugResources UP-TO-DATE
[  +23 ms] :app:generateDebugSources UP-TO-DATE
[   +6 ms] :app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
[ +341 ms] :app:compileDebugJavaWithJavac
[   +3 ms] Full recompilation is required because 'flutter.jar' was changed. Analysis took 0.235 secs.
[ +301 ms] :app:compileDebugNdk UP-TO-DATE
[   +2 ms] :app:compileDebugSources
[+4456 ms] :app:transformClassesWithDexForDebug
[   +4 ms] :app:mergeDebugJniLibFolders UP-TO-DATE
[+4915 ms] :app:transformNative_libsWithMergeJniLibsForDebug
[   +4 ms] :app:processDebugJavaRes UP-TO-DATE
[ +799 ms] :app:transformResourcesWithMergeJavaResForDebug
[   +1 ms] :app:validateSigningDebug
[+6514 ms] :app:packageDebug
[        ] :app:assembleDebug
[   +1 ms] :url_launcher:preDebugBuild UP-TO-DATE
[   +2 ms] :url_launcher:checkDebugManifest
[   +1 ms] :url_launcher:prepareDebugDependencies
[   +7 ms] :url_launcher:compileDebugAidl UP-TO-DATE
[   +4 ms] :url_launcher:compileDebugNdk UP-TO-DATE
[   +2 ms] :url_launcher:copyDebugLint UP-TO-DATE
[   +3 ms] :url_launcher:mergeDebugShaders UP-TO-DATE
[   +3 ms] :url_launcher:compileDebugShaders UP-TO-DATE
[   +2 ms] :url_launcher:generateDebugAssets UP-TO-DATE
[   +3 ms] :url_launcher:mergeDebugAssets UP-TO-DATE
[   +1 ms] :url_launcher:mergeDebugProguardFiles UP-TO-DATE
[   +2 ms] :url_launcher:packageDebugRenderscript UP-TO-DATE
[   +6 ms] :url_launcher:compileDebugRenderscript UP-TO-DATE
[   +2 ms] :url_launcher:generateDebugResValues UP-TO-DATE
[   +1 ms] :url_launcher:generateDebugResources UP-TO-DATE
[   +6 ms] :url_launcher:packageDebugResources UP-TO-DATE
[  +44 ms] :url_launcher:processDebugManifest UP-TO-DATE
[   +1 ms] :url_launcher:generateDebugBuildConfig UP-TO-DATE
[        ] :url_launcher:processDebugResources UP-TO-DATE
[        ] :url_launcher:generateDebugSources UP-TO-DATE
[   +4 ms] :url_launcher:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
[  +97 ms] :url_launcher:compileDebugJavaWithJavac
[        ] Full recompilation is required because 'flutter.jar' was changed. Analysis took 0.044 secs.
[  +99 ms] :url_launcher:processDebugJavaRes UP-TO-DATE
[  +27 ms] :url_launcher:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[   +5 ms] :url_launcher:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
[        ] :url_launcher:mergeDebugJniLibFolders UP-TO-DATE
[        ] :url_launcher:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
[        ] :url_launcher:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
[   +4 ms] :url_launcher:bundleDebug UP-TO-DATE
[        ] :url_launcher:compileDebugSources
[        ] :url_launcher:assembleDebug
[   +1 ms] BUILD SUCCESSFUL
[  +14 ms] Total time: 35.348 secs
[ +996 ms] calculateSha: build\app/outputs/apk/app.apk
[ +462 ms] Built build\app/outputs/apk/app-debug.apk (21.9MB).
[   +1 ms] C:\Android\sdk\build-tools\25.0.2\aapt dump badging build\app/outputs/apk/app.apk
[   +9 ms] Exit code 0 from: C:\Android\sdk\build-tools\25.0.2\aapt dump badging build\app/outputs/apk/app.apk
[        ] package: name='com.yourcompany.Cybertronix' versionCode='1' versionName='0.0.1' platformBuildVersionName='7.1.1'
           sdkVersion:'16'
           targetSdkVersion:'21'
           uses-permission: name='android.permission.INTERNET'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.yourcompany.Cybertronix.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales:
           densities: '160' '240' '320' '480' '640'
           native-code: 'armeabi-v7a' 'x86' 'x86_64'
[        ] Stopping app 'app.apk' on LG H910.
[        ] C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd shell am force-stop com.yourcompany.Cybertronix
[+1080 ms] C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd shell pm list packages com.yourcompany.Cybertronix
[ +504 ms] package:com.yourcompany.Cybertronix
[   +2 ms] C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd shell cat /data/local/tmp/sky.com.yourcompany.Cybertronix.sha1
[  +45 ms] 51703fedab42ec515ca21c850e002577d2d35671
[   +1 ms] Installing APK.
[   +2 ms] C:\Android\sdk\platform-tools\adb version
[  +18 ms] Android Debug Bridge version 1.0.39
           Revision 3db08f2c6889-android
           Installed as C:\Android\sdk\platform-tools\adb.EXE
[   +1 ms] C:\Android\sdk\platform-tools\adb start-server
[  +14 ms] Installing build\app/outputs/apk/app.apk...
[        ] C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd install -r build\app/outputs/apk/app.apk
[+1362 ms] Failed to install build\app/outputs/apk/app.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certi
ficates from /data/app/vmdl703449352.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]
[   +1 ms] 'flutter run' took 48683ms.

Oops; flutter has exited unexpectedly: "Exit code 1 from: C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd install -r build\app
/outputs/apk/app.apk".
[  +20 ms] Sending crash report to Google.
[ +977 ms] Crash report sent (report ID: 56bf015d90000000)
Crash report written to C:\Users\Kyle\Source\Flutter\Cybertronix\flutter_12.log;
please let us know at https://github.com/flutter/flutter/issues.
[ +592 ms] ensureAnalyticsSent: 0ms
[   +1 ms] exiting with code 1
```

## flutter_12.log

## exception

String: Exit code 1 from: C:\Android\sdk\platform-tools\adb -s LGH9107a67a5fd install -r build\app/outputs/apk/app.apk

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:214)
<asynchronous suspension>
#1      AndroidDevice.installApp (package:flutter_tools/src/android/android_device.dart:241)
<asynchronous suspension>
#2      AndroidDevice._installLatestApp (package:flutter_tools/src/android/android_device.dart:281)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:335)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:223)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:183)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:306)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>
#8      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:210)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     Future.Future.sync (dart:async/future.dart:208)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#16     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1465)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#25     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 6.3.9600], channel master)
    • Flutter at C:\flutter
    • Framework revision 2891772846 (2 hours ago), 2017-04-27 09:39:12 -0700
    • Engine revision 3211d2fca2
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at C:\Android\sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.2

[✓] Connected devices
    • LG H910 • LGH9107a67a5fd • android-arm • Android 7.0 (API 24)

```

**Comment by goderbauer** [comment] 2017-04-27 18:59
Looks like there is some issue with certificates, maybe.
@jakobr-google Do you have any insights into this?

**Comment by goderbauer** [comment] 2017-04-27 19:03
This actually looks like a duplicate of https://github.com/flutter/flutter/issues/8605. Let's close this bug here and move the discussion over there.

**Closed by goderbauer** 2017-04-27 19:03 UTC
Labels: crash, dev: tool - gradle, ❖ platform-windows

**Comment by kararsaadkd** [comment] 2018-12-05 00:43
hellio > can you heelp me

Error: ADB exited with exit code 1
adb: failed to install C:\Users\karrar\untitled1\build\app\outputs\apk\app.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]
Error launching application on Android SDK built for x86.

**Comment by zoechi** [comment] 2018-12-05 08:03
@kararsaadkd looks like your device/emulator's storage is full.
Try deleting some apps or similar to free up storage.

**Comment by destangfb01** [comment] 2018-12-26 12:09
@zoechi You King I register with you say thank you :)

**Comment by bhanuka96** [comment] 2019-01-28 15:46
it's not adb or emulator error.. change your device or emulator and check again!!!

**Comment by Neo42** [comment] 2019-06-24 08:20
Hi everyone. I was trying to run the flutter demo app on the Android Studio emulator on Win10. But I got this complaint. Could you please help me?
```
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\Users\Jarvis\Desktop\code\first_app\build\app\outputs\apk\app.apk: Failure [INSTALL_FAILED_ABORTED: User rejected permissions]
Error launching application on COR AL00.
```

**Comment by dusdong** [comment] 2019-07-09 22:22
@Neo42 Using the AVD manager to "Wipe Data" seems to have cleared it.

**Comment by pashute** [comment] 2019-08-22 09:09
See here for ```read-only file system problem```: https://stackoverflow.com/questions/6066030/read-only-file-system-on-android

**Comment by pashute** [comment] 2019-08-22 10:39
In the end I made a new emulator deleted the old ones. And it worked.

**Comment by lucaszanella** [comment] 2019-10-24 06:43
Im not using an emulator and I have more than 2gb free and I cannot send the app to my Moto G6 but I can to Moto Z

**Comment by marianoarga** [comment] 2019-11-20 16:09
Same here, got space on my moto G7 but suddenly can't run the app on it anymore

**Comment by ramioooz** [comment] 2019-12-07 20:34
restart your android phone and build again. worked for me.
Thank you

**Comment by FranciscoDevPy** [comment] 2019-12-26 17:26
Open Android Studio: Configure ->AVD Manager->Edit AVD->Show Advanced Options->Memory and Storage-> increment Memory Storage and SD CARD

**Comment by ghazalKhaled** [comment] 2020-01-11 17:17
i tried Open Android Studio: Configure ->AVD Manager->Edit AVD->Show Advanced Options->Memory and Storage-> increment Memory Storage and SD CARD as FranciscoDevPy commented. it worked with me than you. i tried this with new emulater.

**Comment by omargxr** [comment] 2020-03-22 17:42
> 
> 
> @kararsaadkd looks like your device/emulator's storage is full.
> Try deleting some apps or similar to free up storage.

Thank's man

**Comment by aTItudeDeVeloper** [comment] 2020-03-30 22:15
@zoechi era isso mesmo falta de espaço no dispositivo, deu certo aqui obrigado!

**Comment by ashehata8888** [comment] 2020-04-11 23:10
for ADP issue you just need to double your emulator storage from the AVD Manager - advanced setting 
you can set the following values in the memory and storage section for instance : 

Ram : 3072
VM heap: 512
Internal Storage: 1024
SD Card : 1024 - optional 

and Allah willing every thing will be fine
