### ISSUE TITLE
App freezes with error: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.

### ISSUE THREAD

**Issue by duttk** [flutter/flutter#72176] opened 2020-12-12 02:26 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: [main.dart](https://gist.github.com/duttk/4a5b1dd26692b8accd2d084329bba200)
3. On the simulator, In the two lists that appear, scroll the two lists and scroll within the lists. The freeze is usually triggered when the top list is partially or fully out of the viewport.

**Expected results:** 
App does not freeze

**Actual results:** 
When both lists along with the app itself is being scrolled, the app freezes and  issues the following error:

```

════════ Exception caught by gesture library ═══════════════════════════════════
The following _CastError was thrown while dispatching a pointer event:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      DragGestureRecognizer.acceptGesture
package:flutter/…/gestures/monodrag.dart:321
#1      GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
#2      GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:362
#3      GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
#4      RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
...
Event: PointerUpEvent#26974(position: Offset(0.0, 896.0))
    position: Offset(0.0, 896.0)
Target: <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture library ═══════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════
```

<details>
  <summary>Logs</summary>

```
[+21176 ms] flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
[   +9 ms] flutter: The following _CastError was thrown while dispatching a pointer event:
[        ] flutter: Null check operator used on a null value
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #0      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:321:60)
[        ] flutter: #1      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
[        ] flutter: #2      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
[        ] flutter: #3      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[        ] flutter: #4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] flutter: #5      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[        ] flutter: #6      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] flutter: #7      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] flutter: #11     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] flutter: #12     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[   +5 ms] flutter: (elided 3 frames from dart:async)
[        ] flutter:
[        ] flutter: Event:
[        ] flutter:   PointerUpEvent#aa9e4(position: Offset(202.0, 443.5))
[        ] flutter: Target:
[        ] flutter:   <WidgetsFlutterBinding>
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +168 ms] flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[ +676 ms] flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
```

```
Analyzing minimal...                                                    
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/duttk/pg/flutter-dev/flutter
    • Framework revision 7891006299 (31 hours ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/duttk/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode_12.0.0.app/Contents/Developer
    • Xcode 12.0, Build version 12A7208
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • AE662838-489D-4B82-9CA0-7793A18D02FC • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2020-12-14 06:54
@duttk 
Tried replicating the issue with your code sample, but it didn't freeze for me, unless I missed any step to correctly replicate it.

[72176.mov.zip](https://github.com/flutter/flutter/files/5686963/72176.mov.zip)


<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (3 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details>

Can you provide vide of the issue and exact steps ?

**Comment by duttk** [comment] 2020-12-14 07:43
[flutter.zip](https://github.com/flutter/flutter/files/5687157/flutter.zip)

@darshankawar Thanks for taking a look.

The way I consistently reproduce this is by:
1. Dragging the top level lists up so that the first list is out of the viewport
2. Rapidly scroll inside the bottom list
3. Click outside the bottom list (Say above 'Text')

To aid with this, I increased the number of black containers in the inner lists and increased the size of 'Text'

**Comment by darshankawar** [comment] 2020-12-14 13:38
@duttk Still can't replicate the issue. Did you try on a device or this happens only on simulator ?

**Comment by duttk** [comment] 2020-12-14 17:52
That's strange. I haven't tried this on a device. If that doesn't work, I'll try to blow away my flutter installation and recreate it to see if fixes it 🤷 

Thanks for looking, you can close this issue as not reproducible.

**Comment by darshankawar** [comment] 2020-12-15 06:16
@duttk 
You don't need to re-install flutter. You may try it on a device and see if it replicates there too. Looking at the issue you are getting, it could be similar / duplicate of https://github.com/flutter/flutter/issues/71331

**Comment by duttk** [comment] 2020-12-17 20:21
I was finally able to get back to this. 
I did take a look at the issue you linked before I filed this, but that seems like a third party bug and since I was able to replicate this minimally, I didn't think they were the same.

Restarting my simulator fixed this, so it would appear that I wouldn't have been able to replicate this on a device.

**Comment by darshankawar** [comment] 2020-12-18 05:46
@duttk 
Thanks for getting back. I am going ahead and closing this as non-reproducible. If you think otherwise or see similar behavior again, feel free to comment and I'll reopen it.
Thanks.

**Closed by darshankawar** 2020-12-18 05:46 UTC
Labels: in triage

**Comment by KeenStratium** [comment] 2021-02-23 02:23
Can you share your pubspec.yml?

I have this issue affecting me almost every session since this past month, and likely caused by a 3rd party bug.
