### ISSUE TITLE
custom engines do not work with flutter start in ios simulator

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2633] opened 2016-03-12 00:07 UTC
flutter start --debug with the ios simulator.  The --debug is just ignore.

https://github.com/flutter/engine/wiki/Flutter-Apps-on-iOS is the official instructions instead.

At a minimum we should throw an error in this case and point people to the wiki.

This affects Dart VM engineers attempting to work on the Dart VM in flutter on Macs.  FYI @johnmccutchan

**Comment by chinmaygarde** [comment] 2016-03-24 23:38
Duplicate of https://github.com/flutter/flutter/issues/2061

**Closed by chinmaygarde** 2016-03-24 23:38 UTC
Labels: affects: tools, ⌺‬ platform-ios
