### ISSUE TITLE
Would like a way to ignore iOS message from `flutter doctor` on Mac

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#15461] opened 2018-03-12 21:59 UTC
We've seen this feedback in a few places, including this article:

https://proandroiddev.com/what-the-f-tter-understanding-flutter-as-an-android-java-developer-2158086a2bd9

> Note : You don’t actually need libimobiledevice , ideviceinstaller, ios-deploy and CocoaPods unless you want to build an iOS app, so ignore flutter doctor’s advice on installing them and you’ll save a hell lot of a time."

I thought there was a bug about adding a `--android-only` flag or similar to `flutter doctor`, but I didn't find it.

FYI @the-dagger (who wrote that article)

**Comment by xster** [comment] 2018-03-12 23:10
We should expand on #13200. 

We should also make sure these options show up on `flutter doctor -h`

**Comment by zoechi** [comment] 2019-01-17 11:05
Duplicate of #12768

**Closed by zoechi** 2019-01-17 11:05 UTC
Labels: t: flutter doctor, tool
