### ISSUE TITLE
[web]: Selectable text toolbaroption is not working and also shift + arrow key not working for selecting text

### ISSUE THREAD

**Issue by Jayrajghoniya** [flutter/flutter#55450] opened 2020-04-23 10:05 UTC
I have selectable text in flutter web and I can only select the text but after selecting text there is no pop-up toolbar action for copy,  select all, etc.
also there not an option for copying text in the right-click context menu.
I've also trying to select text by using keyboard shortcut (shift + arrow key) but it is also not working.
I am using Chrome for debugging the flutter web.
below are some screenshots of the problems which I am facing.

![Screen Shot 2020-04-23 at 15 30 09](https://user-images.githubusercontent.com/58690099/80086550-83610f00-8577-11ea-8267-aacf1911385a.png)
![Screen Shot 2020-04-23 at 15 30 21](https://user-images.githubusercontent.com/58690099/80086558-83f9a580-8577-11ea-938a-ecadffe89df9.png)

![code](https://user-images.githubusercontent.com/58690099/80086544-7f34f180-8577-11ea-890b-58f64d26fc04.png)

**Comment by TahaTesser** [comment] 2020-04-23 11:10
Duplicate of [#44176](https://github.com/flutter/flutter/issues/44176) 


Related to [#47234](https://github.com/flutter/flutter/issues/47234)

**Closed by TahaTesser** 2020-04-23 11:10 UTC
