### ISSUE TITLE
Flutter web rtl multi lines textfield content selection inverted

### ISSUE THREAD

**Issue by aymentoumi** [flutter/flutter#50098] opened 2020-02-04 08:41 UTC
As you can see in the picture the text direction is rtl but the selection zone is ltr.
![Capture du 2020-02-04 09-35-28](https://user-images.githubusercontent.com/4050791/73727411-b393d100-4731-11ea-9cd0-c5b78ade643f.png)
The chunk of used code is:
`TextFormField(
                        textDirection: TextDirection.rtl,
                        textAlign: TextAlign.right,
                        key: _contenuKey,
                        maxLines: null,
                      )`

**Comment by majdkz97** [comment] 2020-02-12 17:41
wait for solution

**Comment by majdkz97** [comment] 2020-02-18 21:58
need solution!!

**Comment by mohsenShakiba** [comment] 2020-05-15 08:02
please prioritize.
thank you

**Comment by d1saeed** [comment] 2020-05-15 11:52
this bug is blocking our development process

**Comment by pedromassangocode** [comment] 2020-09-21 10:57
Hi @aymentoumi 
I cannot reproduce this on latest master channel.

![gif](https://user-images.githubusercontent.com/67424416/93759069-72d5c300-fc01-11ea-8dff-78655ee2122e.gif)

<details><summary>code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Padding(
          padding: EdgeInsets.all(50),
          child: TextFormField(
            textDirection: TextDirection.rtl,
            maxLines: 2,
          ),
        ),
      ),
    ),
  );
}

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.269 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 51fa704642 (2 days ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

Closing this as fixed. If you disagree please feel free to write a comment below and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-21 10:57 UTC
Labels: P4, a: text input, framework, platform-web
