### ISSUE TITLE
flutter web: cursor stays in the beginning in textfield

### ISSUE THREAD

**Issue by cactoos13** [flutter/flutter#59948] opened 2020-06-21 14:35 UTC
just use a textfield in flutter web or check [flutter gallery samples](https://flutter.github.io/gallery/#/crane)
textfield has no problem in android output

`C:\Users\Mohammad Reza M\IdeaProjects\gamia_universal>flutter doctor --verbose
[√] Flutter (Channel master, 1.20.0-1.0.pre.132, on Microsoft Windows [Version 10.0.17763.1217], locale en-US)
    • Flutter version 1.20.0-1.0.pre.132 at C:\src\flutter
    • Framework revision 5995661777 (2 days ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1
    • Flutter plugin version 27.1.2
    • Dart plugin version 181.4203.498

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Users\Mohammad Reza M\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.7479.19
    • Flutter plugin version 35.2.2
    • Dart plugin version 191.6183.88

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\Mohammad Reza M\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

• No issues found!`

**Comment by thantez** [comment] 2020-06-22 08:55
This issue has been created for me as well.
![output2](https://user-images.githubusercontent.com/33148504/85268118-5653ae80-b48b-11ea-8cab-2473ea4dc4d2.gif)
As you see, it doesn't matter if the written language is `RTL` (Here, Persian) or `LTR`! Cursor will not behave properly. 
Another example:
![output3](https://user-images.githubusercontent.com/33148504/85268162-69667e80-b48b-11ea-922b-2c80f7eef25c.gif)

**Comment by VladyslavBondarenko** [comment] 2020-06-22 12:09
Hi @cactoos13 

I tried with

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: TextField(),
        )
      ),
    );
  }
}
```

and I can see the wrong cursor position only for `textDirection: TextDirection.rtl,`. I tried with `master 1.20.0-1.0.pre.132` on Mac. @TahaTesser tried with Windows and says that it's only about ltr too.

<details> 
<summary>flutter doctor -v</summary> 

``` 
[√] Flutter (Channel master, 1.20.0-1.0.pre.132, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.20.0-1.0.pre.132 at C:\Code\flutter_master
    • Framework revision 5995661777 (3 days ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0
[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106
• No issues found!
``` 

</details> 

Could you provide complete minimal reproducible code sample?

**Comment by cactoos13** [comment] 2020-06-22 15:07
Hi @VladyslavBondarenko 

Yes you're right it's only for rtl
I sat the locale to a rtl locale and used TextDirection.start or TextDirection.end which caused the problem and I just typed in different languages without changing the TextDirection

But I need RTL 🥺

**Comment by VladyslavBondarenko** [comment] 2020-06-22 15:17
@cactoos13 
please follow up on https://github.com/flutter/flutter/issues/32239, closing as duplicate of https://github.com/flutter/flutter/issues/54099

**Closed by VladyslavBondarenko** 2020-06-22 15:17 UTC
Labels: in triage
