### ISSUE TITLE
[webview_flutter] How to ignore ssl in latest version?

### ISSUE THREAD

**Issue by mdmota** [flutter/flutter#112098] opened 2022-09-21 17:19 UTC

**Comment by stuartmorgan** [comment] 2022-09-21 19:37
Please do not keep filing duplicates of this issue.

Closing as a duplicate of https://github.com/flutter/flutter/issues/36925 (and https://github.com/flutter/flutter/issues/98931, and https://github.com/flutter/flutter/issues/101354).

**Closed by stuartmorgan** 2022-09-21 19:37 UTC
