### ISSUE TITLE
Keyboard focus issue

### ISSUE THREAD

**Issue by the-best-is-best** [flutter/flutter#157085] opened 2024-10-17 09:34 UTC
### Steps to reproduce

1- click in any input field
2- click outside of input filed without click done in keyboard
3- click in avatar for showModalBottomSheet and click outside will keyboard open and focus last field why?

### Expected results

Keyboard display auto for click any inkwell or button if i don't click done in keyboard

### Actual results

keyboard not open if i don't back to click any field

### Code sample

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            InkWell(
              onTap: () {
                showSelectMediaBottomSheet(context);
              },
              child: const CircleAvatar(
                radius: 50.0,
                backgroundColor: Colors.grey,
              ),
            ),
            const SizedBox(
              height: 20.0,
            ),
            Form(
                child: Column(
              children: [
                TextField(
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    labelText: 'Email',
                  ),
                  onTapOutside: (event) => FocusScope.of(context).unfocus(),
                ),
                TextField(
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    labelText: 'Password',
                  ),
                  onTapOutside: (event) => FocusScope.of(context).unfocus(),
                ),
              ],
            ))
          ],
        ),
      ),
    );
  }
}

void showSelectMediaBottomSheet(BuildContext context) {
  showModalBottomSheet(
    context: context,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
    ),
    builder: (BuildContext context) {
      return SizedBox(
        height: 150, // Adjust the height as needed
        child: Column(
          children: <Widget>[
            ListTile(
              leading: const Icon(Icons.camera_alt),
              title: const Text('Camera'),
              onTap: () {
                // Handle camera selection
                Navigator.pop(context);
                // Call the function to open the camera
              },
            ),
            ListTile(
              leading: const Icon(Icons.photo),
              title: const Text('Gallery'),
              onTap: () {
                // Handle gallery selection
                Navigator.pop(context);
                // Call the function to open the gallery
              },
            ),
          ],
        ),
      );
    },
  );
}
```

### Screenshots or Video

https://github.com/user-attachments/assets/522527bf-b5b1-4c78-8b4a-55baac15f5cd

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.94.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by the-best-is-best** [comment] 2024-10-17 09:39
https://github.com/user-attachments/assets/e9fb3de6-1fd7-4d6c-9156-950502ec6139

video issue so uploaded new video if click done in keyboard all of things is correct if don't and click outside not work correctly

**Comment by huycozy** [comment] 2024-10-17 12:18
When you trigger `showModalBottomSheet`, it will open a new route. And it comes with isDismissible as true by default, which means the model is dismissed when tapping outside. This is actually calling Navigator.pop method. If you use `Navigator.push` to a new page instead when tapping on the avatar, you will also see the same issue.

This is a known issue at https://github.com/flutter/flutter/issues/145155 (or https://github.com/flutter/flutter/issues/48464). You can find a workaround at https://github.com/flutter/flutter/issues/145155#issuecomment-2203536461.

Closing this as a duplicate of these issue.

**Closed by huycozy** 2024-10-17 12:18 UTC
Labels: in triage
