### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by Samdosh** [flutter/flutter#159222] opened 2024-11-20 21:01 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=0987437354161357 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```console
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#4      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634:34)
<asynchronous suspension>
#5      ForwardingFile.writeAsString (package:file/src/forwarding/forwarding_file.dart:136:12)
<asynchronous suspension>
#6      ErrorHandlingFile.writeAsString.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:259:24)
<asynchronous suspension>
#7      _run (package:flutter_tools/src/base/error_handling_io.dart:569:12)
<asynchronous suspension>
#8      _renderTemplateToFile (package:flutter_tools/src/flutter_plugins.dart:40:3)
<asynchronous suspension>
#9      _writeCppPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:856:3)
<asynchronous suspension>
#10     writeWindowsPluginFiles (package:flutter_tools/src/flutter_plugins.dart:851:3)
<asynchronous suspension>
#11     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1099:5)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:398:5)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1750:7)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.19045.5131], locale en-US)
    • Flutter version 3.24.4 on channel stable at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (4 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34024.191
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.95.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • TECNO KI5k (mobile) • 0987437354161357 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.5131]
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 130.0.6723.117
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 130.0.2849.80

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2663184aa79047d0a33a14a3b607954f8fdd8730
### Plugins
cloud_firestore-5.4.4
cloud_firestore_web-4.3.2
firebase_core-3.6.0
firebase_core_web-2.18.1
flutter_stripe-11.3.0
path_provider-2.1.5
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
stripe_android-11.3.0
stripe_ios-11.3.0

**Comment by darshankawar** [comment] 2024-11-21 07:56
Closing as duplicate of https://github.com/flutter/flutter/issues/145028

**Closed by darshankawar** 2024-11-21 07:56 UTC
Labels: in triage
