### ISSUE TITLE
google_signin crash after idtoken expiration on Android

### ISSUE THREAD

**Issue by SBNTT** [flutter/flutter#44097] opened 2019-11-04 10:39 UTC
using:
```yaml
google_sign_in: ^4.0.11
```

and
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  final GoogleSignIn _googleSignIn = GoogleSignIn();

  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(
          title: Text("Google signin test"),
        ),
        body: Center(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Expanded(
                child: TimerWidget(),
              ),
              Padding(
                padding: const EdgeInsets.all(36),
                child: Column(
                  children: [
                    RaisedButton(
                      onPressed: _onSilentSigninButtonPressed,
                      child: Text("Sign in silently"),
                    ),
                    RaisedButton(
                      onPressed: _onSigninButtonPressed,
                      child: Text("Sign in"),
                    ),
                  ],
                ),
              )
            ],
          ),
        ),
      ),
    );
  }

  _onSigninSuccess(GoogleSignInAccount account) async {
    
    final auth = await account.authentication;

    final email = account.email;
    final idToken = auth.idToken;

    print(email);
    print(idToken);
  }

  _onSigninButtonPressed() async {
    try {
      final account = await _googleSignIn.signIn();
      _onSigninSuccess(account);
    } catch (error) {
      print(error);
    }
  }

  _onSilentSigninButtonPressed() async {
    try {
      final account = await _googleSignIn.signInSilently();
      _onSigninSuccess(account);
    } catch (error) {
      print(error);
    }
  }

}

class TimerWidget extends StatefulWidget {

  _TimerWidgetState createState() => _TimerWidgetState();

}

class _TimerWidgetState extends State<TimerWidget> {

  int _hours = 0;
  int _minutes = 0;
  int _seconds = 0;

  void initState() {
    super.initState();
    Timer.periodic(Duration(seconds: 1), (Timer timer) {
      setState(() {
        _hours = timer.tick ~/ 3600;
        _minutes = (timer.tick % 3600) ~/ 60;
        _seconds = timer.tick % 60;
      });
    });
  }

  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(24),
      child: Text(
        "${_hours}H ${_minutes}m ${_seconds}s",
        style: TextStyle(
          fontSize: 64
        ),
      ),
    );
  }

}

```

Steps to reproduce:

Signin once and see email / idtoken printed
Wait 1 hour (after the token expiration)
Try to signin/silent signin
App crashes on
```dart
final auth = await account.authentication;
```

with

```
Exception has occurred.
PlatformException (PlatformException(exception, Unknown, null))
```

flutter doctor:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A583, locale fr-FR)
    • Flutter version 1.9.1+hotfix.6 at /Users/sbntt/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sbntt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/sbntt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/sbntt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Users/sbntt/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • 22485716-ED5B-41F8-BFDB-A08C933D7305 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2019-11-04 11:31
Hi @SBNTT 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by iapicca** [comment] 2019-11-04 11:33
Hi @SBNTT 
Could you please provide your `flutter doctor -v`
and your your `flutter run --verbose`?
Thank you

**Comment by SBNTT** [comment] 2019-11-04 12:57
Hi,
flutter doctor is already included in the first post

```
[        ] Updating files
[  +87 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Android SDK built for x86... (completed in 1 873ms)
[        ] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +3 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x84b8d390, isolate: {type: @Isolate, fixedId: true, id: isolates/3041568165227011, name: main.dart$main-3041568165227011, number:
3041568165227011}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x84b8d390.
[   +3 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +2 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:49333/sUqHba4-ogY=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+17158 ms] W/ActivityThread( 6368): handleWindowVisibility: no activity for token android.os.BinderProxy@a2df1d7
[  +98 ms] D/EGL_emulation( 6368): eglMakeCurrent: 0x9bd1a0c0: ver 3 0 (tinfo 0x9bd0f790)
[+1005 ms] D/EGL_emulation( 6368): eglMakeCurrent: 0x9bd1a0c0: ver 3 0 (tinfo 0x9bd0f790)
[  +19 ms] W/oglesignin_tes( 6368): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
[        ] W/oglesignin_tes( 6368): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
[        ] W/oglesignin_tes( 6368): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[        ] W/oglesignin_tes( 6368): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[  +32 ms] W/oglesignin_tes( 6368): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[   +3 ms] I/flutter ( 6368): myemail@domain.fr
[        ] I/flutter ( 6368):XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[+3930249 ms] W/oglesignin_tes( 6368): Reducing the number of considered missed Gc histogram windows from 395 to 100
[+189727 ms] W/oglesignin_tes( 6368): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[   +9 ms] E/flutter ( 6368): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(exception, Unknown, null)
[        ] E/flutter ( 6368): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] E/flutter ( 6368): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
[        ] E/flutter ( 6368): <asynchronous suspension>
[        ] E/flutter ( 6368): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
[        ] E/flutter ( 6368): <asynchronous suspension>
[        ] E/flutter ( 6368): #3      GoogleSignInAccount.authentication (package:google_sign_in/google_sign_in.dart:82:36)
[        ] E/flutter ( 6368): <asynchronous suspension>
[        ] E/flutter ( 6368): #4      MyApp._onSigninSuccess (package:flutter_googlesignin_test/main.dart:50:32)
[        ] E/flutter ( 6368): <asynchronous suspension>
[  +34 ms] E/flutter ( 6368): #5      MyApp._onSilentSigninButtonPressed (package:flutter_googlesignin_test/main.dart:71:7)
[        ] E/flutter ( 6368): <asynchronous suspension>
[        ] E/flutter ( 6368): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
[        ] E/flutter ( 6368): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
[        ] E/flutter ( 6368): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] E/flutter ( 6368): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
[        ] E/flutter ( 6368): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
[        ] E/flutter ( 6368): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
[        ] E/flutter ( 6368): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
[        ] E/flutter ( 6368): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
[        ] E/flutter ( 6368): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
[        ] E/flutter ( 6368): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
[        ] E/flutter ( 6368): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
[        ] E/flutter ( 6368): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
[        ] E/flutter ( 6368): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
[        ] E/flutter ( 6368): #19     _rootRunUnary (dart:async/zone.dart:1136:13)
[        ] E/flutter ( 6368): #20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] E/flutter ( 6368): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[        ] E/flutter ( 6368): #22     _invoke1 (dart:ui/hooks.dart:263:10)
[        ] E/flutter ( 6368): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
[        ] E/flutter ( 6368): 
```

**Comment by iapicca** [comment] 2019-11-04 13:34
Thank you @SBNTT

**Comment by SBNTT** [comment] 2019-11-25 16:14
Any informations about when this issue will be fixed, or any idea to workaround it ?
it generates hundreds of reports in crashlytics..

**Comment by rebeccamcfadden** [comment] 2020-12-14 18:20
I am also having this issue. Any updates?

**Comment by stuartmorgan** [comment] 2021-04-07 20:19
Duplicate of https://github.com/flutter/flutter/issues/33981

**Closed by stuartmorgan** 2021-04-07 20:19 UTC
Labels: P4, p: first party, p: google_sign_in, platform-android, plugin
