### ISSUE TITLE
`Hero.flightShuttleBuilder` has an incorrect `animation` state after the second `push` of the same route

### ISSUE THREAD

**Issue by VladyslavBilomeria** [flutter/flutter#144890] opened 2024-03-09 23:36 UTC
### Steps to reproduce

1. Paste the code sample into the `main.dart` in an empty Flutter project.
2. Run it.
3. Tap on `Go to page 2` button.
4. Before the transition between pages is completed (transition time is 3 seconds), tap on the `Back to page 1` button.
5. Before the transition between pages is completed tap on `Go to page 2` button again.
6. (optional) Repeat steps 4 and 5 for a more visual result.

### Expected results

The `animation.value` value of `Hero.flightShuttleBuilder` should change in accordance with the animation of the `Hero` widget.

### Actual results

If we make the second `push()` of the `FirstPage` page before the animation of the previous `pop()` transition between `SecondPage` -> `FirstPage` pages is completed, then the animation value will reach the value `0.0` and at the end of the transition animation we will see an abrupt state transition of `Hero` widget

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

const double page1BoxSize = 64.0;
const double page2BoxSize = 128.0;

const Color page1BoxColor = Colors.green;
const Color page2BoxColor = Colors.red;

const Duration pageTransitionDuration = Duration(seconds: 3);

// Used just to visually demonstrate the value of `flightShuttleBuilder`'s [animation.value]
final ValueNotifier<double> flightShuttleAnimationValueNotifier =
    ValueNotifier(0.0);

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: const FirstPage(),
    );
  }
}

class FirstPage extends StatelessWidget {
  const FirstPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            AnimationValueTextWidget(),
            SizedBox(
              width: 172.0,
              height: 172.0,
              child: Center(
                child: Hero(
                  tag: 'colored_box',
                  child: BoxWidget(
                    size: page1BoxSize,
                    color: page1BoxColor,
                  ),
                ),
              ),
            ),
            Text('Page with GREEN box'),
            const SizedBox(height: 16.0),
            ElevatedButton(
              onPressed: () => Navigator.of(context).push(
                CustomPageRoute(builder: (_) => SecondPage()),
              ),
              child: Text('Go to page 2'),
            ),
          ],
        ),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            AnimationValueTextWidget(),
            SizedBox(
              width: 172.0,
              height: 172.0,
              child: Center(
                child: Hero(
                  tag: 'colored_box',
                  flightShuttleBuilder: (
                    BuildContext flightContext,
                    Animation<double> animation,
                    HeroFlightDirection flightDirection,
                    BuildContext fromHeroContext,
                    BuildContext toHeroContext,
                  ) {
                    return AnimatedBuilder(
                      animation: animation,
                      builder: (context, _) {
                        // Used just to visually demonstrate the value of [animation.value]
                        WidgetsBinding.instance.addPostFrameCallback((_) {
                          flightShuttleAnimationValueNotifier.value =
                              animation.value;
                        });

                        double size = lerpDouble(
                            page1BoxSize, page2BoxSize, animation.value)!;
                        Color color = Color.lerp(
                            Colors.green, Colors.red, animation.value)!;
                        return BoxWidget(
                          size: size,
                          color: color,
                        );
                      },
                    );
                  },
                  child: BoxWidget(
                    size: page2BoxSize,
                    color: page2BoxColor,
                  ),
                ),
              ),
            ),
            Text('Page with RED box'),
            const SizedBox(height: 16.0),
            ElevatedButton(
              onPressed: () => Navigator.of(context).pop(),
              child: Text('Back to page 1'),
            ),
          ],
        ),
      ),
    );
  }
}

class BoxWidget extends StatelessWidget {
  final double size;
  final Color color;

  const BoxWidget({required this.size, required this.color});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: size,
      height: size,
      color: color,
    );
  }
}

// Used just to visually demonstrate the value of `flightShuttleBuilder`'s [animation.value]
class AnimationValueTextWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: ValueListenableBuilder(
        valueListenable: flightShuttleAnimationValueNotifier,
        builder: (context, value, child) {
          return Text('animation.value: ${value.toStringAsFixed(6)}');
        },
      ),
    );
  }
}

class CustomPageRoute extends PageRouteBuilder {
  CustomPageRoute({
    required WidgetBuilder builder,
  }) : super(
          transitionDuration: pageTransitionDuration,
          reverseTransitionDuration: pageTransitionDuration,
          pageBuilder: (context, animation, secondaryAnimation) =>
              builder(context),
          transitionsBuilder: (context, animation, secondaryAnimation, child) {
            return FadeTransition(
              opacity: Tween<double>(
                begin: 0.0,
                end: 1.0,
              ).animate(
                CurvedAnimation(
                  parent: animation,
                  curve: Curves.fastOutSlowIn,
                  reverseCurve: Curves.fastOutSlowIn,
                ),
              ),
              child: child,
            );
          },
        );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/51199783/cb26761b-d79a-40f0-a013-30b7033d84c0

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-UA)
    • Flutter version 3.19.3 on channel stable at /Users/vladyslav/fvm/versions/stable
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision ba39319843 (2 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/vladyslav/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/vladyslav/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (1 available)
    • iPhone 15 Pro (mobile)      • D127FBD4-46C1-4EF3-AB2A-4F52E49A3B1A • ios • com.apple.CoreSimulator.SimRuntime.iOS-17-0
      (simulator)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-03-11 11:16
Thanks for filing a detailed issue, @VladyslavBilomeria. But I think this is similar to https://github.com/flutter/flutter/issues/53523 which pointed out the animation listener is not triggered. If you add this snippet code to `flightShuttleBuilder`, you can see it never hits `completed` status when the issue comes:

```dart
animation.addStatusListener((status) {
	if (status == AnimationStatus.completed) {
		print('completed');
	}
});
```

So I will close this as a duplicate of https://github.com/flutter/flutter/issues/53523. Please also share your case in comments there as well.

**Closed by huycozy** 2024-03-11 11:16 UTC
Labels: in triage
