### ISSUE TITLE
PlatformViewsController Trying to use platform views with API 19, required API level is:  20.Can you lower the api level?

### ISSUE THREAD

**Issue by hschenzhimin** [flutter/flutter#23728] opened 2018-10-30 09:41 UTC
I want to play video with surfaceview on Android 4.4.  
I found that PlatformView cannot be used on 4.4, and it is OK above 5.0. 

Can you lower this criterion?
```dart
public void onMethodCall(MethodCall call, Result result) {
        if (VERSION.SDK_INT < 20) {
            Log.e("PlatformViewsController", "Trying to use platform views with API " + VERSION.SDK_INT + ", required API level is: " + 20);
        } else {
        .....
        }
```

**Comment by zhaoya188** [comment] 2018-12-24 09:10
Does Platform View have plans to support Android API Level 19 or below?

**Comment by codedog76** [comment] 2019-01-18 13:03
Hi I have the same issue or rather more specifically mine's coming from trying to run google_maps_flutter library on a 4.4.2 tablet.

**Comment by ahmedmgh67** [comment] 2019-01-23 17:14
@hschenzhimin did you try to change it?

**Comment by sbd2015** [comment] 2019-04-11 11:14
I'm having the same issue while using google_maps_flutter , it shows a blank page on Android 4.4.2

**Comment by joaquinperaza** [comment] 2019-04-14 15:46
Same Issue

**Comment by p30arena** [comment] 2019-04-15 08:40
Same Issue Here
I need at least API 16

**Comment by eseidelGoogle** [comment] 2019-04-15 17:30
AndroidView unfortunately requires lvl 20 or higher:
https://docs.flutter.io/flutter/widgets/AndroidView-class.html
The way we implement AndroidView on Android requires APIs which aren't provided that far back unfortunately.

It is possible that we can potentially implement whatever use case you're using AndroidView for (e.g. Maps, WebView) in a different way on older Android's.  It would help to understand which use case individuals are looking for here.

FYI @amirh

**Comment by p30arena** [comment] 2019-04-16 18:41
@eseidel
For example, I need the camera plugin to work on API above 16,
The official plugin doesn't support API lower than 21, so I had to rewrite the plugin to support them.
But then I found out that PlatformView support API lvl > 20

So I had to write another class to use android Activity instead of PlatformView

Does TextureRegistry and FlutterView also need api lvl > 20 ?
https://docs.flutter.io/javadoc/io/flutter/view/TextureRegistry.html
https://docs.flutter.io/javadoc/io/flutter/view/FlutterView.html

**Comment by HulkZeng** [comment] 2019-04-19 07:08
Can you consider supporting API 16 ?

**Comment by amirh** [comment] 2019-04-29 23:03
@p30arena  the camera plugin's requirement for SDK 21 is because it depends on the camera2 API which was introduced in 21. You can write your own plugin that uses the [android.hardware.Camera](https://developer.android.com/reference/android/hardware/Camera) that is available prior to API 21, you shouldn't need platform view for that, you can direct the preview to a texture and display it with a Texture widget.

More generally, it is possible to bring the AndroidView requirement down to API 19(VirtualDisplay#setSurface is the only thing that requires API 20 and we can probably live without it, see comment [here](https://github.com/flutter/engine/blob/ab01d73960d677f3a035b56ccaa991c0eb892ffc/shell/platform/android/io/flutter/plugin/platform/VirtualDisplayController.java#L86)).

As Eric mentioned, it may be possible to implement AndroidView using a hybrid composition approach (somewhat similarly to how we implement it on iOS for UIKitView) this approach should work with any API level that Flutter supports but will have significant limitations (the platform view will not be synchronized with the Flutter frame, and most transforms won't work). I'm curious for the use cases you would need AndroidView to support on earlier SDK versions and whether the hybrid composition approach satisfies the requirements.

**Comment by yuridiniz** [comment] 2019-06-03 13:14
Is there any planning for this? This would really be very useful!

**Comment by Vanethos** [comment] 2019-06-06 07:14
Just wanted to say that we also have this problem, our company needs to have a PlatformView that supports API 19

**Comment by cremor** [comment] 2019-08-06 14:41
I would need the WebView plugin for API 16.

**Comment by ChessLuo** [comment] 2019-08-16 06:41
Webview_flutter loads the web page with error message:
E / PlatformViewsController: Try to use the platform view of API 19, the required API level is: 20
[Error: flutter / lib / ui / ui_dart_state.cc(148)] Unhandled Exception: PlatformException (Error, try to use platform view on Android version not supported by platform view., null)

Does the flutter android platform use webview_flutter requires an API level of 20 or higher?

**Comment by cremor** [comment] 2019-08-16 07:31
Yes, sadly it does right now. But there is an alternative WebView plugin that works on older API versions: https://pub.dev/packages/flutter_webview_plugin

**Comment by ChessLuo** [comment] 2019-08-20 03:44
I hope that PlatformView will also support API 19 at least, because there are many devices in API 19.

**Comment by fauzipadlaw** [comment] 2019-09-10 05:07
facing the same issue here, cannot display maps

**Comment by amirh** [comment] 2019-09-10 18:31
@fauzipadlaw I'd suggest you thumb up the first comment so the issue comes up the priority order.

**Comment by DanialV** [comment] 2019-09-22 08:29
Same issue here can't use google map on API level 19 please consider updating platform view for supporting  API level 19 and under.

**Comment by jagiro** [comment] 2019-10-03 10:51
This is a blocking point for me, I can't leave so many devices without maps.
I believe that being able to support GoogleMaps on a wide range of devices should be a priority.

**Comment by eseidelGoogle** [comment] 2019-10-03 18:25
I would strongly encourage you to upvote the main comment.  We use the upvotes for prioritization of issues.  Right now this issue only has 11 upvotes (suggesting it may affect fewer developers than other more-upvoted issues).

We may want to break out the question of Google Maps for v19 specifically.  It's possible there are workarounds we could do specific to maps but not general to PlatformViews.  @amirh might have thoughts.

**Comment by jagiro** [comment] 2019-10-24 10:02
We are migrating from Apps to native Flutter.
The App needs the map in order to work correctly. I would like to avoid publishing it only for IOS.
@eseidelGoogle  @amirh , do you have any progress or workaround?

**Comment by Gperez88** [comment] 2019-11-25 15:22
Same Issue api 19

**Comment by ramsestom** [comment] 2019-12-06 20:27
> AndroidView unfortunately requires lvl 20 or higher:
> https://docs.flutter.io/flutter/widgets/AndroidView-class.html
> The way we implement AndroidView on Android requires APIs which aren't provided that far back unfortunately.
> It is possible that we can potentially implement whatever use case you're using AndroidView for (e.g. Maps, WebView) in a different way on older Android's.  It would help to understand which use case individuals are looking for here.
> FYI @amirh

@eseidelGoogle 
Could you please tell us exactly what android native function available for API level >=20 only was used for AndroidView? I would really like to have AndroidView work for API 19 as kitkat devices still represent 7% of the android market (https://developer.android.com/about/dashboards). So it is not negligible (I can live with an app that won't work for <5% of my potential customers. So if it do not work for API level <19 it is OK. But cut me off more than 10% of these customers is just too much, so I really need to be able to focus API level 19).
I took a quick look at the java code of androidviews to see if it could be adapted to work with API level 19 but couldn't find any function call requiering API level >=20 (I only found code explicitly requiering at least ICE_CREAM_SANDWICH but it is API level 15...)

**Comment by eseidelGoogle** [comment] 2019-12-06 20:46
@amirh would know.  I do not know off the top of my head.

**Comment by eseidelGoogle** [comment] 2019-12-06 20:49
This is probably the answer:
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L40
https://developer.android.com/reference/android/hardware/display/VirtualDisplay#setSurface(android.view.Surface)

**Comment by ramsestom** [comment] 2019-12-06 20:52
yes the setSurface seems to be the problematic function to support API level 19. Thanks. I will investigate how to bypass this limitation in case of API level <20 .

**Comment by TheMisir** [comment] 2020-01-16 17:47
Does min api level affect the minimum supported android version?

**Comment by Mujas** [comment] 2020-03-04 08:21
Any update on this issue? I am migrating the native app to Flutter and webview is not supporting in Api level 19.

Trying to use platform views with API 19, required API level is: 20

**Comment by LPzoe** [comment] 2020-03-26 05:48
same issue....Does Platform View have plans to support Android API Level 19 or below?

**Comment by LPzoe** [comment] 2020-03-26 05:49
6.9% on Android API Level 19  https://developer.android.com/about/dashboards

**Comment by mulenatni** [comment] 2020-04-08 13:33
the same problem any one can help me please

**Comment by magax** [comment] 2020-04-12 02:50
No updates about this issue??

**Comment by magax** [comment] 2020-04-12 03:02
This is a huge problem, I don't know if the community realize that we are loosing more than 10% of the market if we consider all the devices running with SDK under version 20.

**Comment by mulenatni** [comment] 2020-04-13 05:20
thanks magax

**Comment by doonfrs** [comment] 2020-04-22 04:12
Any updates about this issue? any alternative solution?
We are receiving many complaints, those devices still common in many countries ...

**Comment by samuelg123** [comment] 2020-04-28 06:13
Sdk 16-19 still widely used in my country.
Or please provide support sdk 20 below for google_maps_flutter plugin

**Comment by egyleader** [comment] 2020-05-12 06:40
having the same problem with admob native ads running on android api lower than 20 witch means loses millions of potential customers ,, this must be a priority or have some workaround for it ..

**Comment by vrijmetse** [comment] 2020-05-27 14:06
Seems like this issue remains open for a few years now. Is there a workaround for this ? Can I access webview using platform channel specific ?

**Comment by eseidelGoogle** [comment] 2020-05-27 21:01
CC @zoeyfan

**Comment by jaumard** [comment] 2020-06-12 14:12
Main usage for me is web views (under a dialog so can't use another web view package except the official one). I'm getting a lot of `fatalPlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 18, required API level is: 20 at io.flutter.plugin.platform.PlatformViewsController` because of this

**Comment by eseidelGoogle** [comment] 2020-06-24 21:31
@blasten Can you drive a decision resolution to this bug?  I'd like us to have clear communication here as to if we plan to lower the API level for Video (and WebView?) or if this is just the best we can get out of Android APIs?  If not, seems like we can just explain that and close the bug?

**Comment by blasten** [comment] 2020-06-24 22:00
@eseidelGoogle Sgtm. I will assign this bug to myself, and will follow up once we have confirmed that these plugins can be migrated to hybrid (which requires API 19) without any major compromise.

**Comment by eseidelGoogle** [comment] 2020-06-24 22:50
Thanks.  My goal is to communicate the plan here, even if it's "we can't do this due to X".  The bug feels a bit in limbo atm, despite being a common source of comments. :)  Thanks!

**Comment by blasten** [comment] 2020-06-24 23:06
To summarize the current plan, our team has been working on a new implementation of platform views that requires API 19 instead of API 20.  As a result, we will be looking at migrating the webview plugin to this new mode.  The video player plugin seems doable as well provided performance is reasonable.

**Comment by blackbusters** [comment] 2020-10-10 08:57
Is there any solution to use google_maps_flutter with API 19 since flutter v1.22 ? 

I hope there is some way to use Platform View with hybrid composition automatically when it is detected on API 19.

**Comment by blasten** [comment] 2020-10-14 00:20
We released hybrid composition in Flutter 1.22, which just requires API level 19. 

To learn more, take a look at the new API: 
https://flutter.dev/docs/development/platform-integration/platform-views?tab=android-platform-views-kotlin-tab#hybrid-composition

As far as existing plugins are concerned, WebView already supports this new mode.  If you would like to contribute, feel free to send us a PR to extend support to other plugins such as Google Maps!

**Closed by blasten** 2020-10-14 00:20 UTC
Labels: P4, a: platform-views, customer: crowd, engine, platform-android

**Comment by 24KWYL** [comment] 2020-11-30 12:50
I want to play video with TextureView and GSYVideoPlayer.
But use 'hybrid composition' cannot play video

**Comment by ShejaEddy** [comment] 2021-03-26 10:42
Here in our country we're still using 16-18 Api level, now woth our company's release app 50% of the mobile's google map is not working. We really need support of at lease Api level 18. Your help will be much appreciated, Thanks
