### ISSUE TITLE
SelectableText content selection doesn't deselect on mobile

### ISSUE THREAD

**Issue by krisisav** [flutter/flutter#107840] opened 2022-07-18 14:17 UTC
## Description

The text content of the widget `SelectableText` remains selected after another selection has been made, which is a child of a different widget of the same type (run code below and see attached video).

**Expected results:** 
Any following selection should deselect the previous

**Actual results:** 
This happens only for text that belongs to the same widget

<details>
<summary>Code sample</summary>

```import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Selectable Text Sample',
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 32.0, vertical: 90),
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SelectableText(
                  "Lorem Ipsum",
                  style: Theme.of(context).textTheme.headline2,
                ),
                const SizedBox(height: 24.0),
                SelectableText(
                  "What is Lorem Ipsum?",
                  style: Theme.of(context).textTheme.headline5,
                ),
                const SizedBox(height: 16.0),
                SelectableText(
                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                  style: Theme.of(context).textTheme.headline6,
                ),
                const SizedBox(height: 24.0),
                SelectableText(
                  "Why do we use it?",
                  style: Theme.of(context).textTheme.headline5,
                ),
                const SizedBox(height: 16.0),
                SelectableText(
                  "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
                  style: Theme.of(context).textTheme.headline6,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.0.4 at /Users/kristinasavova/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kristinasavova/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 892A4078-A1AC-44AB-B3DF-2E9A7C311F0E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

https://user-images.githubusercontent.com/66869604/179530797-0f893018-5de5-4eeb-aa7c-b5116eda059c.mp4

**Comment by maheshmnj** [comment] 2022-07-19 08:11
Hi @krisisav, Thanks for filing the issue. this is working as intended since you are using multiple `SelectableText` and they are independent of each other. But there's an open issue for this request see https://github.com/flutter/flutter/issues/64854. On the contrary,  there are also plans to deprecate the SelectableText widget in favor of the new widget SelectionArea see https://github.com/flutter/flutter/issues/104547

Closing as a duplicate of #64854

**Closed by maheshmnj** 2022-07-19 08:11 UTC
Labels: in triage
