### ISSUE TITLE
How to implement a nested TabBarView cleanly/correctly?

### ISSUE THREAD

**Issue by HengJunXi** [flutter/flutter#19765] opened 2018-07-25 14:03 UTC
### Problem: ###

I am trying to implement nested TabBarView, and succeed in doing so. However, I am not quite sure is this the 'clean' way to write Flutter code. 

Everything works well if I just put all widget in one state class. To be more modular, I separate the inner TabBarView from the outer TabBarView. However, I discover that the innerTabController must reside in the outer TabBarView class, in order for the inner TabBarView to recover its previous index correctly. 

I consider this as bad code as my outer TabBarView will need to concern about the inner TabBarView details (length, initialIndex, ...) 

    class _TestAppState extends State<TestApp>
        with TickerProviderStateMixin {

      TabController _tabController;
      TabController _innerTabController;

      @override
      void initState() {
        super.initState();
        _tabController = TabController(
          length: 2,
          vsync: this
        );
        _tabController.addListener(handleTabChange);
        _innerTabController = TabController(
          length: 2,
          vsync: this
        );
      }

### Question: ###
How should I structure the code to make it more clean/maintainable/modular?
Or should I use other method to retain the index of the inner TabView?

### Code: ###
https://gist.github.com/HengJunXi/ae99777df6fc5f902805628b3e270ab4

**Comment by zoechi** [comment] 2018-07-25 15:35
Please consider asking how-to questions on StackOverflow.

**Comment by HengJunXi** [comment] 2018-07-25 16:14
Sorry about that.

I think I have found a better way to do this nested tab bar view thing by using the ValueKey and PageStorageBucket readState() and writeState() methods.

      final _tabKey = ValueKey('tab');

      TabController _innerTabController;

      void handleTabChange() {
        print('Inner tab, previous: ${_innerTabController.previousIndex}, current: ${_innerTabController.index}');
        PageStorage.of(context).writeState(context, _innerTabController.index, identifier: _tabKey);
      }

      @override
      void initState() {
        super.initState();
        print('init');
        int initialIndex = PageStorage.of(context).readState(context, identifier: _tabKey);
        _innerTabController = TabController(
          length: 2,
          vsync: this,
          initialIndex: initialIndex != null ? initialIndex : 0
        );
        _innerTabController.addListener(handleTabChange);
      }

All of these codes will stay in the inner tab view class, hence the outer tab view class will no longer need to concern about the inner one.

Again, sorry for the trouble.

**Full code here:** https://gist.github.com/HengJunXi/b23994fbcb22f0a832dc5c6a50434725

**Comment by goderbauer** [comment] 2019-01-02 23:01
Closing as it sounds like the issue is resolved.

**Closed by goderbauer** 2019-01-02 23:01 UTC
Labels: framework
