### ISSUE TITLE
Plugins default to Kotlin and Java

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#25412] opened 2018-12-15 15:59 UTC
# Context and Rationale

At the moment, `flutter create --template=plugin` ([ref](https://flutter.io/docs/development/packages-and-plugins/developing-packages#step-1-create-the-package-1)) defaults to Objective C and Java. It is my suggestion that the we switch the default to Swift and Kotlin respectively instead.

Kotlin is first-class language supported by Android, and officially preferred by Android rather than Java ([ref](https://developer.android.com/kotlin/)) even if Kotlin adds a little bit overhead ([ref](https://developer.android.com/kotlin/faq))

When it comes to Swift, the case is even stronger. While Kotlin is officially endorsed and preferred by Android team, it's still developed by another entity, JetBrain. Meanwhile, Swift is developed by Apple specifically for iOS, macOS and tvOS development. In the first quarter of 2018 Swift surpassed Objective-C in measured popularity ([ref](https://redmonk.com/sogrady/2018/03/07/language-rankings-1-18/)). The runtime overhead will no longer be an issue for Swift 5, according to wwdc 2018
> And we also have another release coming up for you in the language, Swift 5. The focus of Swift 5 is greater adoption by delivering Swift as part of the OS. Apps will no longer need to include the Swift runtime when delivering on our newer OS releases, resulting in smaller downloads and faster launches. We're very excited about this, too, and we have made great progress toward this goal. And you'll see it in a release coming early next year.

# Proposed actions
- Change https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart to switch the default language to Swift and Kotlin.
  - Change https://github.com/flutter/flutter-intellij accordingly <img width="665" alt="screen shot 2018-12-15 at 10 51 52 pm" src="https://user-images.githubusercontent.com/358585/50044829-24a2a000-00bc-11e9-9495-bfe80f3637e2.png">
- Convert all "first-party" plugins https://github.com/flutter/plugins to Swift and Kotlin.
  - Write platform unit test in Swift (https://github.com/flutter/flutter/issues/10141) and Kotlin (https://github.com/flutter/flutter/issues/10140)

**Comment by truongsinh** [comment] 2018-12-15 16:00
Maybe related https://github.com/flutter/flutter/issues/17999
CC @ened @Hixie @amirh @mravn-google goderbauer

**Comment by zoechi** [comment] 2018-12-16 15:00
Duplicate of #21190

**Comment by truongsinh** [comment] 2018-12-16 15:42
@zoechi btw, I also propose to convert all "first-party" plugins https://github.com/flutter/plugins to Swift and Kotlin.

**Comment by zoechi** [comment] 2018-12-16 15:50
I don't think a single issue for all that fulfills any purpose 
and when it's time the Flutter team will plan that work properly anyway.

Just saw 

> in general i recommend filing a bug and ccing @amirh to discuss what to do.

in Gitter flutter/contributors
So I'll reopen and leave it to @amirh how to proceed.

**Comment by amirh** [comment] 2018-12-17 18:53
The Flutter team is currently maintaining Dart, C++, Java, and ObjC code (and a few other languages in things like build scripts). Java and ObjC are used not only in the plugins repository but also in the engine. I think we should try to keep the set of languages that Flutter team members need to be familiar with as small as possible. I vote to only convert / add Kotlin code to the plugins repository if it's part of a broad migration plan to convert all Java code (in the plugins and engine repositories) to Kotlin. I wouldn't want to make a "first incremental step" in that direction without a plan to migrate all code within a reasonable amount of time.

Currently I don't think that the potential benefits of Kotlin justify starting a migration effort given our other priorities.
My thoughts are similar regarding Objc/Swift with the addition that we should probably only consider it when the Swift runtime doesn't have to be bundled with the app (as we are trying to minimize binary size).

**Comment by zanderso** [comment] 2019-08-23 21:15
The tool now defaults to kotlin and swift, so as titled I think this issue can be closed. If it is desired to rewrite the plugins that the Flutter team is maintaining in those languages, let's open (a) separate issue(s) for that.

**Closed by zanderso** 2019-08-23 21:15 UTC
Labels: plugin, severe: new feature, tool
