### ISSUE TITLE
[web] wrong image filter on web app built with HTML renderer

### ISSUE THREAD

**Issue by tanharpatel** [flutter/flutter#76966] opened 2021-03-01 06:12 UTC
I am trying to display image as background in container. It works well in debug mode but doesn't appear same when I host it

Here is code snippet which is not working well

![image](https://user-images.githubusercontent.com/47564751/109458018-026d8080-7a82-11eb-8112-47e908de6602.png)

**Comment by pedromassangocode** [comment] 2021-03-01 07:35
Hi @tanharpatel 
Can you please provide your `flutter doctor -v`, a minimal complete reproducible code sample and the actual vs expected results?
Thank you

**Comment by tanharpatel** [comment] 2021-03-01 08:03
> Hi @tanharpatel
> Can you please provide your `flutter doctor -v`, a minimal complete reproducible code sample and the actual vs expected results?
> Thank you

The expected output is:
![20210301_132540](https://user-images.githubusercontent.com/47564751/109467936-effb4300-7a91-11eb-8643-e3b24a45a1eb.jpg)

The output what I am getting is: (not working in mobile device chrome after hosting)
![20210301_132448](https://user-images.githubusercontent.com/47564751/109467950-f4bff700-7a91-11eb-8249-35a087899d89.jpg)



Output of flutter doctor -v:

[√] Flutter (Channel master, 1.27.0-2.0.pre.103, on Microsoft
    Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.27.0-2.0.pre.103 at C:\flutter
    • Framework revision f49956598b (13 days ago), 2021-02-16
      00:56:06 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK
    version 29.0.2)
    • Android SDK at C:\Users\Tanha
      Patel\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Tanha
      Patel\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Tanha
      Patel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome      
      88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge     
      88.0.705.56

• No issues found!



Sample Code:

import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  Image image;
  @override
  Widget build(BuildContext context) {
    return Container(
        width: MediaQuery.of(context).size.width*0.85,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage("assets/images/$image"), fit: BoxFit.cover,
            colorFilter: ColorFilter.mode(Colors.black.withOpacity(0.25), BlendMode.dstATop),
          ),
          border: Border.all(color: Color(0xFF00bcd5), width: 2),
          borderRadius: BorderRadius.circular(MediaQuery.of(context).size.height*0.05),
        ),
        child: Column(
          children: [
            Padding(
              padding: EdgeInsets.only(right: 20, left: 20),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  SizedBox(height: 20),
                  Align(
                    alignment: Alignment.topRight,
                    child: Text(
                      "hi",
                      textAlign: TextAlign.right,
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                        fontFamily: 'Segoe UI',
                        fontSize: MediaQuery.of(context).size.height*0.04,
                      ),
                    ),
                  ),
                  Align(
                    alignment: Alignment.topRight,
                    child: Text(
                      "helo",
                      textAlign: TextAlign.right,
                      softWrap: true,
                      style: TextStyle(
                        color: Colors.white,
                        fontFamily: 'Segoe UI',
                        fontSize: MediaQuery.of(context).size.height*0.025,
                      ),
                    ),
                  ),
                  SizedBox(height: 15),
                  Align(
                    alignment: Alignment.topRight,
                    child: Text(
                      "asdf aslhdk",
                      textAlign: TextAlign.right,
                      softWrap: true,
                      style: TextStyle(
                        color: Colors.white,
                        fontFamily: 'Segoe UI',
                        fontWeight: FontWeight.w500,
                        fontSize: MediaQuery.of(context).size.height*0.02,
                      ),
                    ),
                  ),
                  
                ],
              ),
            ),
            SizedBox(height: 20),
          ],
        ),
      );
  }
}

**Comment by pedromassangocode** [comment] 2021-03-01 12:00
Hi @tanharpatel 
Can you please provide the command used to build the release/debug builds? It would be great to have the image you have used as well.
Thank you

**Comment by tanharpatel** [comment] 2021-03-01 12:20
Hello @pedromassango 

Thanks for reply and your help.

I have tried using 
> flutter run -d chrome --release 
> flutter run -d chrome 

for both the command i got desired output but after hosting my website on github the output is different in mobile version of chrome, for reference you can check my website at [Tanha's Portfolio](https://tanharpatel.github.io/tanha/)

**Comment by pedromassangocode** [comment] 2021-03-01 12:45
This seems to be that in the release build, you (or Flutter) has chosen HTML as the renderer and this causes the Image color filter to become a little lighter. On CanvasKit the image has the expected dark opacity.

I was able to reproduce this on latest Master channel.

| CanvasKit Renderer | HTML Renderer |
|-|-|
|![Screen Shot 2021-03-01 at 13 36 17](https://user-images.githubusercontent.com/67424416/109498823-49647180-7a94-11eb-8209-daacca0ce28d.png)|![Screen Shot 2021-03-01 at 13 44 56](https://user-images.githubusercontent.com/67424416/109498838-51241600-7a94-11eb-8df3-abf9626d36d1.png)|

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.128, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-9.0.pre.128 at /Users/pedromassango/Code/flutter_master
    • Framework revision 199d5dc086 (8 hours ago), 2021-02-28 14:36:02 -0800
    • Engine revision 34236c9837
    • Dart version 2.13.0 (build 2.13.0-81.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

**Comment by tanharpatel** [comment] 2021-03-01 13:07
Thank you so much @pedromassangocode for helping me out.

I explicitly specified the web renderer this time and it worked.
> flutter build web --release --web-renderer canvaskit

**Comment by pedromassangocode** [comment] 2021-03-03 08:52
I'm pretty sure this is still a valid issue. 
Let's just have this opened for the team to review.

**Comment by ferhatb** [comment] 2021-04-06 16:54
landed in master

**Closed by ferhatb** 2021-04-06 16:54 UTC
Labels: P4, a: images, e: web_html, engine, found in release: 1.27, has reproducible steps, platform-web, severe: rendering, waiting for PR to land (fixed)
