### ISSUE TITLE
[web]: TextField and TextFormField Problem

### ISSUE THREAD

**Issue by Zewe1995** [flutter/flutter#69037] opened 2020-10-26 17:15 UTC
Hi dear flutter developent support... the TextField and TextFormField cursor is not currectly work in RTL locate, please solve this

**Comment by chinmoy12c** [comment] 2020-10-26 19:38
Hello @Zewe1995 
Please provide the output for `flutter doctor -v` and a minimum reproducible code for your issue. Also can you please describe your issue a bit more in detail?

**Comment by darshankawar** [comment] 2020-10-27 07:36
Closing this as duplicate of [32239](https://github.com/flutter/flutter/issues/32239)

**Closed by darshankawar** 2020-10-27 07:36 UTC
