### ISSUE TITLE
range error(index)

### ISSUE THREAD

**Issue by sriram613** [flutter/flutter#62002] opened 2020-07-22 05:13 UTC
someone help me wit this
it is showing like this
 Oops; flutter has exited unexpectedly: "RangeError (index): Index out of range: no indices are valid: 0". A crash report has been written to C:\Users\srira\flutter_02.log.

This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JeyYe

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JJWyM

**Comment by darshankawar** [comment] 2020-07-22 06:14
Hi @sriram613,
You seem to have opened multiple tickets for same issue.
Closing this as duplicate of [62004](https://github.com/flutter/flutter/issues/62004)

**Closed by darshankawar** 2020-07-22 06:14 UTC
