### ISSUE TITLE
Functions run with compute are ignored by flutter test coverage

### ISSUE THREAD

**Issue by The-Redhat** [flutter/flutter#35484] opened 2019-07-02 21:17 UTC
## Steps to Reproduce

1. create flutter project
2. add a compute function
3. test compute function with unit test
4. run `flutter test --coverage`

## Logs
```
Analyzing schoolsen-mobile...                                           
No issues found! (ran in 3.7s)
```

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.2 at /home/gregor/development/flutter
    • Framework revision 2e540931f7 (5 hours ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/gregor/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • Java binary at: /snap/android-studio/76/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/76/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by tvolkert** [comment] 2019-07-08 16:41
@The-Redhat can you give an example of such a function?

**Comment by The-Redhat** [comment] 2019-07-08 20:32
#

**Comment by The-Redhat** [comment] 2019-08-03 11:22
Here an example:
```dart
static RequestState _parseJson(String response) {
    // parse Something
  }

  @override
  Future<RequestState> parseData(String response) =>
      compute(_parseJson, response);
```

**Comment by tvolkert** [comment] 2019-08-03 15:10
@The-Redhat you need to use `runAsync()` whenever you perform real async work within a Flutter test.

https://api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html

```dart
void main() {
  testWidgets('compute', (WidgetTester tester) async {
    dynamic data = await tester.runAsync(() => parseData('[1]'));
    print(data);
  });
}

Future<dynamic> parseData(String str) => compute(parseJson, str);

dynamic parseJson(String str) {
  return json.decode(str);
}
```

**Comment by The-Redhat** [comment] 2019-08-03 15:14
Ok thanks. I test this function in a unit test. Is runAsync there also available?

**Comment by tvolkert** [comment] 2019-08-03 15:27
If I run this in a unit test, it works for me out of the box:

```dart
void main() {
  test('compute', () async {
    dynamic data = await parseData('[1]');
    print(data);
  });
}

Future<dynamic> parseData(String str) => compute(parseJson, str);

dynamic parseJson(String str) {
  return json.decode(str);
}
```

**Comment by The-Redhat** [comment] 2019-08-03 15:30
Yes sure I said it works. My problem is that the test coverage ignores _parseJson function and marks it as not tested.

**Comment by tvolkert** [comment] 2019-08-03 16:42
lol, sorry, I lost track of the original reported bug 😆

**Comment by mikhail-tokarev** [comment] 2019-10-01 11:43
I think it is safe to close the issue.
If you disagree please comment and I will reopen it.

**Comment by csells** [comment] 2020-01-13 20:30
@BondarenkoStas can you comment on why you re-opened this issue?

**Comment by BondarenkoStas** [comment] 2020-01-13 21:47
@csells I thought https://github.com/flutter/flutter/issues/35484#issuecomment-517933104 may require an attention, but it was on October and it seems that the issue is obsolete. Feel free to close it.

**Comment by The-Redhat** [comment] 2021-06-01 21:52
Unfortunately not

**Comment by maheshmnj** [comment] 2021-07-07 08:25
closing it as the issue is solved

**Closed by maheshmnj** 2021-07-07 08:25 UTC
Labels: a: tests
