### ISSUE TITLE
Card color issues when using Material 3 and a semi-transparent background color

### ISSUE THREAD

**Issue by PapyElGringo** [flutter/flutter#125406] opened 2023-04-24 09:21 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Make a card with semi-transparent background color, a full transparent tint color and an elevation

### Expected results

The background color should be the semi-transparent selected one

### Actual results

There is a darker tint color applied

### Code sample

<details><summary>Code sample</summary>

```dart
Card(
          color: Colors.red.withOpacity(0.5),
          surfaceTintColor: Colors.transparent,
          elevation: 4
)
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://user-images.githubusercontent.com/3754825/233954764-3748ce3c-a317-4caa-8b80-e3b2dc42efaf.png)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.9.0-18.0.pre.8, on Fedora Linux 38.20230424.0 (Silverblue) 6.2.11-300.fc38.x86_64, locale en_US.UTF-8)
    • Flutter version 3.9.0-18.0.pre.8 on channel master at /var/home/papyelgringo/workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4a1002e2e2 (4 weeks ago), 2023-03-26 22:55:12 +0200
    • Engine revision 685fbc6f4d
    • Dart version 3.0.0 (build 3.0.0-366.0.dev)
    • DevTools version 2.22.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /var/home/papyelgringo/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.0
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64   • Fedora Linux 38.20230424.0 (Silverblue) 6.2.11-300.fc38.x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.

```

</details>

**Comment by TahaTesser** [comment] 2023-04-24 09:49
Hi @PapyElGringo 
This is a duplicate of https://github.com/flutter/flutter/issues/122177

**Closed by TahaTesser** 2023-04-24 09:49 UTC

**Comment by PapyElGringo** [comment] 2023-04-24 10:16
@TahaTesser Thanks I missed #122177 and my issue it's indeed a bit different because there is no workaround available like you mentioned in the related issue. 
Let's continue the conversation there.
