### ISSUE TITLE
google_maps_flutter:0.5.21 polygons not refreshing on tap with setstate as it is on google_maps_flutter:0.5.20+6

### ISSUE THREAD

**Issue by CodeGlitch** [flutter/flutter#40589] opened 2019-09-16 14:10 UTC
Hello, I've used google_maps_flutter for polygons with success for over a month now. On the latest version I'm finding a problem with the polygon presentation.
On earlier versions the code is working fine, adding new corners to the polygon on each tap, but on the latest version it doesn't look to be refreshing the polygon design, just stays as a triangle while it has been update (ontap is triggered normally, and setstate, but looks like it has no effect).

google_maps_flutter:0.5.21:
![2019-09-16 13 52 37](https://user-images.githubusercontent.com/1039012/64963991-b298fa80-d889-11e9-8a96-83a8fa34b083.jpg)

google_maps_flutter:0.5.20+6:
![2019-09-16 13 57 00](https://user-images.githubusercontent.com/1039012/64964574-dc065600-d88a-11e9-884b-1f211f5f8d50.jpg)

My code looks something like this:

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class GooglePolyMap extends StatefulWidget {
  GooglePolyMap({Key key}) : super(key: key);

  @override
  _GooglePolyMapState createState() => _GooglePolyMapState();
}

class _GooglePolyMapState extends State<GooglePolyMap> {
  @override
  initState() {
    super.initState();
  }

  Widget getAppBar() {
    return AppBar(
      title: Row(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          Text("Defina o Poligono", style: new TextStyle(color: Colors.white)),
          Expanded(child: Container(), flex: 5),
          IconButton(
            onPressed: () {
              setState(() {
                coordsPoints = new List();
              });
            },
            icon: Icon(Icons.delete_forever, color: Colors.red, size: 30.0),
          ),
          Expanded(child: Container(), flex: 1),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: getAppBar(),
      body: new Container(child: googleMapPolylineBuilder()),
      floatingActionButton: FloatingActionButton(
        heroTag: 'save',
        onPressed: () {
          //...
          Navigator.pop(context);
        },
        child: Icon(Icons.save),
      ),
    );
  }

  List<LatLng> coordsPoints = new List();
  double zoom = 4;
  LatLng target = LatLng(39.1479748,-47.7275007);

  Widget googleMapPolylineBuilder() {
    CameraPosition _cposition = CameraPosition(
      target: LatLng(39.1479748,-47.7275007),
      zoom: 4.0,
    );

    Set<Polygon> _polygons = {};
    Set<Polyline> _lines = {};
    if (coordsPoints.length > 2) {
      _polygons.add(Polygon(
          strokeWidth: 4,
          polygonId: PolygonId("1"),
          fillColor: Colors.redAccent.withOpacity(0.50),
          visible: true,
          strokeColor: Colors.indigo,
          points: coordsPoints));
    } else if (coordsPoints.length == 2) {
      _lines.add(Polyline(
          width: 4,
          polylineId: PolylineId("1"),
          color: Colors.indigo,
          points: coordsPoints));
    } else {
      _polygons = {};
      _lines = {};
    }

    return Container(
        height: MediaQuery.of(context).size.height,
        width: MediaQuery.of(context).size.width,
        child: GoogleMap(
          compassEnabled: false,
          scrollGesturesEnabled: true,
          rotateGesturesEnabled: true,
          zoomGesturesEnabled: true,
          myLocationEnabled: false,
          myLocationButtonEnabled: false,
          tiltGesturesEnabled: false,
          initialCameraPosition: _cposition,
          mapType: MapType.hybrid,
          polylines: _lines != null ? _lines : null,
          polygons: _polygons != null ? _polygons : null,
          onCameraMove: (value) {
            zoom = value.zoom;
            target = value.target;
          },
          onTap: (value) {
            setState(() {
              coordsPoints.add(LatLng(value.latitude, value.longitude));
            });
          },
        ));
  }
}
```

**Comment by jmagman** [comment] 2019-09-16 17:41
@iskakaushik

**Comment by cantaspinar** [comment] 2019-09-17 12:28
I am having the same issue with polylines, markers work fine btw.

**Comment by iskakaushik** [comment] 2019-09-17 16:23
Duplicate of https://github.com/flutter/flutter/issues/39737

**Closed by iskakaushik** 2019-09-17 16:23 UTC
Labels: p: maps, plugin
