### ISSUE TITLE
App crash with implementing push notification in IOS on a physical device.

### ISSUE THREAD

**Issue by wadealanchan** [flutter/flutter#48561] opened 2020-01-10 10:04 UTC
https://pub.dev/packages/firebase_messaging
I followed this article to implement IOS integration with everything all set
APNs uploaded on Firebase, GoolgeService-info.plist,etc. 

It works when building with simulator and also i tested with my own cert(automatically manage signing). It also works(but this i had to disable push notifications in Xcode).

However, when i enable Push Notifications and used the cert generated from apple developer account(Distribution Ad Hoc).

I tried to run it by flutter. It always returned below error
```
Could not install build/ios/iphoneos/Runner.app on ....
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace.
```

When i opened the code to run it. It only returned below code
```
2020-01-10 17:28:57.227292+0800 Runner[1230:136551]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist

W0110 17:28:57.236075       1 commandlineflags.cc:1503] Ignoring RegisterValidateFunction() for flag pointer 0x100bcdfd0: no flag found at that address

2020-01-10 17:28:57.332811+0800 Runner[1230:136307] [VERBOSE-2:ptrace_ios.cc(66)] Could not call ptrace(PT_TRACE_ME): Operation not permitted

2020-01-10 17:28:57.345904+0800 Runner[1230:136307] Metal API Validation Enabled
```
I wondered if that's my cert problem, but it wasn't coz i tested it with a new project. It worked.

My problem: 
1) I could not run the app on my physical device . successfully built but app crashed once installed.
2) Flutter did not show any detailed log or error
3) i need to test push notification in IOS on a physical device. It did not work with the below setting.
![Screenshot 2020-01-10 at 5 49 26 PM](https://user-images.githubusercontent.com/32679452/72144566-96d6d880-33d3-11ea-984b-8ef05066260d.png)

Things that have been tested:
1) everything works in Android, including receive push notifications.
2) works with building in simulator and cert with (automatically manage signing)

**Comment by iapicca** [comment] 2020-01-10 10:25
Hi @wadealanchan 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-01-10 10:25 UTC
