### ISSUE TITLE
SliverPersistentHeader disappears when scrolls up in certain cases 

### ISSUE THREAD

**Issue by natalieeeflores** [flutter/flutter#43936] opened 2019-10-31 22:47 UTC
## Steps to Reproduce

1. Scroll down to the bottom of the screen quickly
2. Scroll back up to the top of the screen quickly
3. Observe the screen, the header will disappear briefly and come back 

![ezgif com-optimize](https://user-images.githubusercontent.com/19349394/67990742-08d0bb80-fbf4-11e9-9dde-24f1584b780c.gif)

``` dart
import 'package:flutter/material.dart';

class SliverPersistentHeaderExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: CustomScrollView(
        slivers: <Widget>[
          _SliverPersistentHeader(),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (_, i) => Text(
                i.toString(),
                style: TextStyle(fontSize: 40),
              ),
              childCount: 100,
            ),
          ),
        ],
      ),
    );
  }
}

class _SliverPersistentHeader extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SliverPersistentHeader(
      delegate: _HeaderDelegate(
        height: 80,
      ),
      pinned: true,
    );
  }
}

class _HeaderDelegate extends SliverPersistentHeaderDelegate {
  _HeaderDelegate({
    @required this.height,
    this.onTextFieldChanged,
  });

  final double height;
  final void Function(String) onTextFieldChanged;

  @override
  double get minExtent => height;

  @override
  double get maxExtent => height;

  @override
  Widget build(
    BuildContext context,
    double shrinkOffset,
    bool overlapsContent,
  ) {
    return Container(
      color: Colors.pink,
    );
  }

  @override
  bool shouldRebuild(_HeaderDelegate oldDelegate) {
    return height != oldDelegate.height;
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SliverPersistentHeaderExample(),
    );
  }
}

void main() {
  runApp(MyApp());
}
```

**Target Platform:** iOS

## Logs

```
```

```
Waiting for another flutter command to release the startup lock...
Analyzing login_issue...                                                
No issues found! (ran in 3.7s)
```

```
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15 19A603, locale en-US)
    • Flutter version 1.10.7 at /Users/natalieflores/flutter
    • Framework revision e70236e36c (4 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/natalieflores/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/natalieflores/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 11                 • 4DA77D37-5C0F-4A42-80B3-88A18693755F • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by iapicca** [comment] 2019-11-01 07:58
Hi @natalieeeflores 
I didn't manage to reproduce the behavior you are describing,
are you experiencing this on both iOS and Android?
Both on physical and virtual devices?
Thank you

**Comment by natalieeeflores** [comment] 2019-11-01 17:33
Hi @iapicca! I've only been experiencing this issue on iOS. I have seen it on both physical and virtual devices but it is much easier to reproduce on physical devices. It's very difficult to reproduce on virtual devices. I've had it happen on my iPhone 10R which is running software version 13.1.3.

**Comment by iapicca** [comment] 2019-11-04 07:29
Thank you @natalieeeflores for the details you  provided

**Comment by TahaTesser** [comment] 2020-10-27 13:41
Hi @natalieeeflores 
Not able to reproduce the issue on XR running iOS 14

### Preview

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/48603081/97309510-20369900-1888-11eb-8134-9f0c0d301282.gif)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

class SliverPersistentHeaderExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: CustomScrollView(
        slivers: <Widget>[
          _SliverPersistentHeader(),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (_, i) => Text(
                i.toString(),
                style: TextStyle(fontSize: 40),
              ),
              childCount: 100,
            ),
          ),
        ],
      ),
    );
  }
}

class _SliverPersistentHeader extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SliverPersistentHeader(
      delegate: _HeaderDelegate(
        height: 80,
      ),
      pinned: true,
    );
  }
}

class _HeaderDelegate extends SliverPersistentHeaderDelegate {
  _HeaderDelegate({
    @required this.height,
    this.onTextFieldChanged,
  });

  final double height;
  final void Function(String) onTextFieldChanged;

  @override
  double get minExtent => height;

  @override
  double get maxExtent => height;

  @override
  Widget build(
    BuildContext context,
    double shrinkOffset,
    bool overlapsContent,
  ) {
    return Container(
      color: Colors.pink,
    );
  }

  @override
  bool shouldRebuild(_HeaderDelegate oldDelegate) {
    return height != oldDelegate.height;
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SliverPersistentHeaderExample(),
    );
  }
}

void main() {
  runApp(MyApp());
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-4.0.pre.82, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-4.0.pre.82 at /Users/tahatesser/Code/flutter_master
    • Framework revision e5814756a2 (5 hours ago), 2020-10-27 01:47:03 -0700
    • Engine revision 1857470267
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 86.0.4240.111

• No issues found!

```

</details> 

Can you please try on the latest flutter version on XR 
Thank you

**Comment by pedromassangocode** [comment] 2020-11-20 13:22
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-20 13:22 UTC
Labels: a: quality, engine, platform-ios, waiting for customer response
