### ISSUE TITLE
[path_provider] 1.6.22

### ISSUE THREAD

**Issue by lizhuoyuan** [flutter/flutter#69007] opened 2020-10-26 06:22 UTC
```
Duplicate class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement found in modules animal-sniffer-annotations-1.18.jar (org.codehaus.mojo:animal-sniffer-annotations:1.18) and sig.jar (sig.jar)
```

1.6.21 is normal, after upgrading to 1.6.22, the build fails

**Comment by TahaTesser** [comment] 2020-10-26 09:48
Hi @lizhuoyuan 
Just tried to reproduce the issue on the latest `stable using `path_provider: ^1.6.22`, both flutter run and flutter build has no issues on Android  using official [example](https://pub.dev/packages/path_provider/example)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.2 at C:\Code\flutter_stable
    • Framework revision 84f3d28555 (10 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

</details> 

Can you please provide your `flutter doctor -v` your `flutter run --verbose` or `flutter build apk` and a complete reproducible minimal code sample
Thank you

**Comment by lizhuoyuan** [comment] 2020-10-26 11:33
```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.15.7 19H2,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/lizhuoyuan/Development/flutter
    • Framework revision f139b11009 (7 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/lizhuoyuan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/lizhuoyuan/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] Android Studio
    • Android Studio at /Application/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Application/Android Studio.app/Contents
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • ONEPLUS A5000 • f6f90654                                 • android-arm64 •
      Android 9 (API 28)
    • 李卓原的iPhone    • e0c0bdcaf20e6d3e26e5a752abd72fe0adc56982 • ios           •
      iOS 13.7

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment] 2020-10-27 08:17
Hi @lizhuoyuan 
Looks like you're running a very old version
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If you can't provide a code sample from https://github.com/flutter/flutter/issues/69007#issuecomment-716435301, please official example in a new project 
**With upgrade** Can you please provide your `flutter doctor -v` your `flutter run --verbose` or `flutter build apk` and a complete reproducible minimal code sample
Thank you

**Comment by lizhuoyuan** [comment] 2020-10-29 11:50
I upgraded flutter to 1.20.4
I will try path_provider 1.6.22 in the near future.
Thank you.

**Comment by pedromassangocode** [comment] 2020-11-24 10:07
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-24 10:07 UTC
Labels: in triage, waiting for customer response
