### ISSUE TITLE
RefreshIndicatorState._handleScrollNotification calls SetState during performLayout

### ISSUE THREAD

**Issue by coupestartup** [flutter/flutter#66328] opened 2020-09-22 08:20 UTC
RefreshIndicatorState._handleScrollNotification sometimes calls SetState during performLayout, which is not allowed.

One instance where this happens is when associated with a CustomScrollView with overflowing scrollOffset.

Repro:
```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyHomePage()));

class MyHomePage extends StatelessWidget {
  final controller = ScrollController(initialScrollOffset: -1000);
  @override
  Widget build(BuildContext context) => RefreshIndicator(
        child: CustomScrollView(controller: controller),
        onRefresh: () async {},
      );
}
```

The stack trace below says it all

Encountered on Flutter 1.20.4, channel stable

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Build scheduled during frame.
[...]

The relevant error-causing widget was:
  CustomScrollView
  file:///Users/yuanyuanxie/AndroidStudioProjects/refresh_indicator_repro/lib/main.dart:9:16

When the exception was thrown, this was the stack:
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:736:9)
#1      WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:759:6)
#2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2524:23)
#3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4230:11)
#4      State.setState (package:flutter/src/widgets/framework.dart:1260:14)
#5      RefreshIndicatorState._handleScrollNotification (package:flutter/src/material/refresh_indicator.dart:225:7)
#6      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:131:41)
#7      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:49:20)
#8      ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:33:18)
#9      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4033:39)
#10     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:65:13)
#11     ScrollActivity.dispatchScrollStartNotification (package:flutter/src/widgets/scroll_activity.dart:93:65)
#12     ScrollPosition.didStartScroll (package:flutter/src/widgets/scroll_position.dart:751:14)
#13     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:743:7)
#14     ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:118:11)
#15     ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:150:7)
#16     IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:163:14)
#17     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:559:14)
#18     ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:108:11)
#19     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:502:7)
#20     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1350:14)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#40     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#57     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3228:13)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#61     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#75     RenderView.performLayout (package:flutter/src/rendering/view.dart:170:13)
#76     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
#77     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
#78     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
#79     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#80     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#81     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#82     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#83     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
```

**Comment by darshankawar** [comment] 2020-09-22 09:26
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.20.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision fba99f6cf9 (7 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile)  • emulator-5554
      • android-x86 • Android 10 (API 29) (emulator)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

```

</details>

**Comment by maheshmnj** [comment] 2022-11-24 00:55
Hi @coupestartup, Thanks for filing the issue. I can no longer reproduce the issue on the latest master 3.6, Looks like this might have been fixed. I am going to close this issue as no longer reproduceible, in Incase you still encounter the issue. Feel free to write back in the comments with more details and we will reopen it.

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Thank you.

**Closed by maheshmnj** 2022-11-24 00:55 UTC
Labels: framework, f: material design, a: layout, has reproducible steps, found in release: 1.20
