### ISSUE TITLE
Regression in license script average runtime on CI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#117243] opened 2022-12-16 22:55 UTC
Since the license script change [here](https://github.com/flutter/engine/commit/fc71faad05a0c2492c4beaa9fd8f66a17aebb631), the average runtime on CI has increased from <10 minutes to >30 minutes [1]. Previously, it would run >30 minutes on a small number of commits, for example Dart rolls. But now it appears to run that long every commit.

[1] See https://ci.chromium.org/p/flutter/builders/prod/Linux%20License?limit=200. The fast runs today don't include the license script change since they are CPs to the 3.7 branch.

cc @Hixie

**Comment by Hixie** [comment] 2022-12-17 00:06
https://github.com/flutter/engine/pull/38363

**Comment by aam** [comment] 2022-12-19 19:26
It looks like some of the performance regression is due to more expensive regexps introduced in the recent script change.
For example, on third_party/freeeetype2/.../freetype.h it takes 2 seconds to apply [following regex](https://github.com/flutter/engine/blob/main/tools/licenses/lib/patterns.dart#L400 ) :
```
r"(?:This file is part of the Independent JPEG Group's software.)? "
      r'(?:It was modified by The libjpeg-turbo Project to include only code (?:and information)? relevant to libjpeg-turbo\.)? '
      r'For conditions of distribution and use, see the accompanying '
```

If you remove those non-capturing groups that drops execution time of that regex down to 0.1s

**Comment by a-siva** [comment] 2022-12-19 22:00
Is sharding the script using multiple isolates an option?

**Comment by Hixie** [comment] 2022-12-19 22:48
The next thing I want to do is change the pattern-matching approach entirely so as to not use RegExps, by first tokenizing the files and then doing word-by-word pattern matching for the licenses. That should improve performance by orders of magnitude. No idea when I'll get around to that though, probably in 5 years. Happy to help someone else do it first, or if anyone wants to micro-optimize the regexps, please go ahead; I'm very happy to review any patches -- I tried looking at some of the patterns, but other than figuring out that the _lineBreak thing is really expensive, I didn't know how to figure out that's expensive and what isn't. The code does have a RegExp introspection layer now so it's easy to find which pattern is the most expensive, just run the script with `--verbose`.

**Comment by chinmaygarde** [comment] 2023-01-09 18:37
From Triage: Marking this as resolved after https://github.com/flutter/engine/pull/38363 landed. I've added @Hixie comments for followup in https://github.com/flutter/flutter/issues/118193
<img width="534" alt="Screenshot 2023-01-09 at 10 35 31 AM" src="https://user-images.githubusercontent.com/44085/211382417-9c0380ac-9bbc-4c68-a4d9-2623f72d367d.png">

**Closed by chinmaygarde** 2023-01-09 18:37 UTC
Labels: severe: regression, team, engine, waiting for PR to land (fixed), P1
