### ISSUE TITLE
CupertinoTextField Cursor' navigation issue

### ISSUE THREAD

**Issue by abayomiAkanji** [flutter/flutter#82151] opened 2021-05-09 13:51 UTC
I can't use `CupertinoTextField` cursor to navigate through its text.

How would one enable the `CupertinoTextField` cursor to scroll/navigate through the text (when you pinch or hold it down)? I noticed that it isn't possible like it does for `TextFormField`.

Am I missing something or it's a missing feature for `CupertinoTextField`?

**Comment by darshankawar** [comment] 2021-05-10 11:41
@abayomiAkanji 
You mean, using the following code snippet, you are unable to move the text cursor among the text anywhere ?

```
body: Center(
          child: CupertinoTextField(
            maxLines: 5,
          ),
        ),
```

And it works with `TextFormField` ?

If this isn't correct interpretation of the issue, can you provide details around it ?

**Comment by darshankawar** [comment] 2021-05-11 07:21
@abayomiAkanji 
I tried the sample code on iphone6s using latest stable version and was able to navigate among the text by tapping wherever required which was followed by the cursor as expected.


https://user-images.githubusercontent.com/67046386/117774777-73d26800-b257-11eb-80c4-1efd56ed41c6.MP4

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by abayomiAkanji** [comment] 2021-05-11 13:27
Hi @darshankawar, did you notice that the first scroll through the character requires a longer press than the subsequent ones? 
Is it that the intended design?

**Comment by darshankawar** [comment] 2021-05-13 05:38
@abayomiAkanji I understand, but I think this isn't replicable at our end and based on our thread above, the navigation behavior seems to be consistent across all related widgets.

I am going ahead and closing this as working as intended. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-05-13 05:38 UTC
Labels: in triage
