### ISSUE TITLE
intent links not opening

### ISSUE THREAD

**Issue by MightyM17** [flutter/flutter#132119] opened 2023-08-08 10:35 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Get an Intent URL `intent://` ideally (https://developer.chrome.com/docs/multidevice/android/intents/)
Try to launch it in flutter with launchUrlString(intentURL)

### Expected results

It should open the app picker/app that the intent has in it, just like how browsers do it.

### Actual results

```
Unhandled Exception: PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { intent://scan/#Intent;scheme=zxing;package=com.google.zxing.client.android;S.browser_fallback_url=http%3A%2F%2Fzxing.org;end }, null, null)
The url opens fine on any browser
```
It fails to open the intent.
Other ways to open an app like `sms:`, `mailto:`, `tel:` work just fine.

### Code sample

<details><summary>Code sample</summary>

```dart
launchUrlString("intent://scan/#Intent;scheme=zxing;package=com.google.zxing.client.android;S.browser_fallback_url=http%3A%2F%2Fzxing.org;end");
```

</details>

### Logs

<details><summary>Logs</summary>

```console
E/flutter (18796): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { intent://scan/#Intent;scheme=zxing;package=com.google.zxing.client.android;S.browser_fallback_url=http%3A%2F%2Fzxing.org;end }, null, null)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.2070], locale en-IN)
    • Flutter version 3.10.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\bavis\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.80.2)
    • VS Code at C:\Users\bavis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • 22021211RI (mobile) • 838f68b4 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.2070]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 115.0.5790.170
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 115.0.1901.188

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by stuartmorgan** [comment] 2023-08-08 11:43
Per the `url_launcher` README:
> The provided URL is passed directly to the host platform for handling. The supported URL schemes therefore depend on the platform and installed apps.

Android doesn't have any handling of the `intent` scheme; that's a browser feature to convert specific URLs into intents. If you believe Android should handle `intent:` URIs, you would need to file an issue against Android. However, the intended way of using intents in a non-browser context on Android is to actually create an intent, not an `intent:` URI. See [`android_intent_plus`](https://pub.dev/packages/android_intent_plus) for example.

Closing as out of scope, since `url_launcher` does not—by design—do custom URL handling before handing off to the system.

**Closed by stuartmorgan** 2023-08-08 11:43 UTC

**Comment by MightyM17** [comment] 2023-08-08 11:58
> Per the `url_launcher` README:
> 
> > The provided URL is passed directly to the host platform for handling. The supported URL schemes therefore depend on the platform and installed apps.
> 
> Android doesn't have any handling of the `intent` scheme; that's a browser feature to convert specific URLs into intents. If you believe Android should handle `intent:` URIs, you would need to file an issue against Android. However, the intended way of using intents in a non-browser context on Android is to actually create an intent, not an `intent:` URI. See [`android_intent_plus`](https://pub.dev/packages/android_intent_plus) for example.
> 
> Closing as out of scope, since `url_launcher` does not—by design—do custom URL handling before handing off to the system.

I'm opening a webpage in a webview that has intents to open specific apps, changing those is not in my hands.
Is there any way in which I would be able to convert those URIs to Intents the way Android likes them? Or somehow one could be able to recreate how the browsers do the conversions in the flutter app.

**Comment by stuartmorgan** [comment] 2023-08-08 15:13
> Is there any way in which I would be able to convert those URIs to Intents the way Android likes them?

`url_launcher` doesn't do parsing or conversion, so any code you wrote do to custom handling of URIs would not involve `url_launcehr`.
