### ISSUE TITLE
`Shortcuts` interactive examples broken

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#81507] opened 2021-04-29 21:41 UTC
https://master-api.flutter.dev/flutter/widgets/Shortcuts-class.html

**Comment by Abhishek01039** [comment] 2021-04-30 03:30
Thanks @LongCatIsLooong for filing an issue.

**Comment by goderbauer** [comment] 2021-04-30 18:06
Looks like the problem is that dartpad is running with flutter stable (2.0.5), which does not yet include the recently added `ShortcutActivator` class. I don't think there's much we can do about it unless we can run dartpad with the latest master...

**Comment by LongCatIsLooong** [comment] 2021-04-30 18:15
I thought dartpad used to use the beta channel? If https://master-api.flutter.dev uses the stable version that will be sad.

**Comment by goderbauer** [comment] 2021-04-30 18:23
@johnpryan probably knows for sure what version of Flutter dartpad runs.

**Comment by dkwingsmt** [comment] 2021-04-30 19:37
Anyway, master-api should probably use master channel. Can we file an issue for this?

**Comment by goderbauer** [comment] 2021-04-30 19:43
> Can we file an issue for this?

--> https://github.com/dart-lang/dart-pad/issues/new/choose

**Comment by dkwingsmt** [comment] 2021-04-30 19:46
I think it's more like an issue for Flutter instead for Dartpad. But I'll file one anyway.

**Comment by goderbauer** [comment] 2021-05-05 21:56
I am going to close this issue since there's nothing we can do on our side for now.

**Closed by goderbauer** 2021-05-05 21:56 UTC
Labels: d: api docs, documentation, framework
