### ISSUE TITLE
Error: Flutter build apk 

### ISSUE THREAD

**Issue by duy1998** [flutter/flutter#78230] opened 2021-03-15 17:28 UTC
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not resolve all artifacts for configuration ':app:profileRuntimeClasspath'.
   > Could not resolve io.flutter:x86_64_profile:1.0.0-40441def692f444660a11e20fac37af9050245ab.
     Required by:                                                       
         project :app                                                   
      > Could not resolve io.flutter:x86_64_profile:1.0.0-40441def692f444660a11e20fac37af9050245ab.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_64_profile/1.0.0-40441def692f444660a11e20fac37af9050245ab/x86_64_profile-1.0.0-40441def692f444660a11e20fac37af9050245ab.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/io/flutter/x86_64_profile/1.0.0-40441def692f444660a11e20fac37af9050245ab/x86_64_profile-1.0.0-40441def692f444660a11e20fac37af9050245ab.pom'. Received status code 502 from server: Bad Gateway
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org

[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-VN)
    • Flutter version 2.0.1 at /Users/dinhcongduy1998yahoo.com.vn/Downloads/flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dinhcongduy1998yahoo.com.vn/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by kdelorey** [comment] 2021-03-16 02:48
According to [bintray status](https://status.bintray.com/) jcenter had an outage earlier that has since been resolved. I can easily reproduce this with:

```shell
> flutter create test-proj ; cd test-proj
> flutter build apk
```

Anyone have a work around?

**Comment by pedromassangocode** [comment] 2021-03-16 09:15
Hi @duy1998 @kdelorey 
I cannot reproduce this issue on latest stable channel.

Is this still happening for you?


<details>
<summary>logs</summary>

```bash
pedromassango@MacBook-Pro-de-MacBook Desktop % flutters create aab && cd aab && flutters build apk
Creating project aab...
  aab/windows/runner/flutter_window.cpp (created)
  aab/windows/runner/utils.h (created)
  aab/windows/runner/run_loop.h (created)
  aab/windows/runner/utils.cpp (created)
  aab/windows/runner/runner.exe.manifest (created)
  aab/windows/runner/CMakeLists.txt (created)
  aab/windows/runner/win32_window.h (created)
  aab/windows/runner/Runner.rc (created)
  aab/windows/runner/win32_window.cpp (created)
  aab/windows/runner/resources/app_icon.ico (created)
  aab/windows/runner/main.cpp (created)
  aab/windows/runner/resource.h (created)
  aab/windows/runner/run_loop.cpp (created)
  aab/windows/runner/flutter_window.h (created)
  aab/windows/flutter/CMakeLists.txt (created)
  aab/windows/.gitignore (created)
  aab/windows/CMakeLists.txt (created)
  aab/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  aab/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  aab/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  aab/ios/Runner/Info.plist (created)
  aab/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  (created)
  aab/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  (created)
  aab/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  aab/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  aab/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  (created)
  aab/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  (created)
  aab/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  aab/ios/Runner/Base.lproj/Main.storyboard (created)
  aab/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  (created)
  aab/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.p
  list (created)
  aab/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xc
  settings (created)
  aab/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  aab/ios/Flutter/Debug.xcconfig (created)
  aab/ios/Flutter/Release.xcconfig (created)
  aab/ios/Flutter/AppFrameworkInfo.plist (created)
  aab/ios/.gitignore (created)
  aab/test/widget_test.dart (created)
  aab/aab.iml (created)
  aab/.gitignore (created)
  aab/web/favicon.png (created)
  aab/web/index.html (created)
  aab/web/manifest.json (created)
  aab/web/icons/Icon-192.png (created)
  aab/web/icons/Icon-512.png (created)
  aab/.metadata (created)
  aab/macos/Runner.xcworkspace/contents.xcworkspacedata (created)
  aab/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  aab/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png (created)
  aab/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  (created)
  aab/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png (created)
  aab/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png (created)
  aab/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png (created)
  aab/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png (created)
  aab/macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  aab/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png (created)
  aab/macos/Runner/DebugProfile.entitlements (created)
  aab/macos/Runner/Base.lproj/MainMenu.xib (created)
  aab/macos/Runner/MainFlutterWindow.swift (created)
  aab/macos/Runner/Configs/Debug.xcconfig (created)
  aab/macos/Runner/Configs/Release.xcconfig (created)
  aab/macos/Runner/Configs/Warnings.xcconfig (created)
  aab/macos/Runner/Configs/AppInfo.xcconfig (created)
  aab/macos/Runner/AppDelegate.swift (created)
  aab/macos/Runner/Info.plist (created)
  aab/macos/Runner/Release.entitlements (created)
  aab/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks
  .plist (created)
  aab/macos/Runner.xcodeproj/project.pbxproj (created)
  aab/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  aab/macos/Flutter/Flutter-Debug.xcconfig (created)
  aab/macos/Flutter/Flutter-Release.xcconfig (created)
  aab/macos/.gitignore (created)
  aab/android/app/src/profile/AndroidManifest.xml (created)
  aab/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  aab/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  aab/android/app/src/main/res/drawable/launch_background.xml (created)
  aab/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  aab/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  aab/android/app/src/main/res/values-night/styles.xml (created)
  aab/android/app/src/main/res/values/styles.xml (created)
  aab/android/app/src/main/res/drawable-v21/launch_background.xml (created)
  aab/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  aab/android/app/src/main/AndroidManifest.xml (created)
  aab/android/app/src/debug/AndroidManifest.xml (created)
  aab/android/gradle/wrapper/gradle-wrapper.properties (created)
  aab/android/gradle.properties (created)
  aab/android/.gitignore (created)
  aab/android/settings.gradle (created)
  aab/android/app/build.gradle (created)
  aab/android/app/src/main/kotlin/com/example/aab/MainActivity.kt (created)
  aab/android/build.gradle (created)
  aab/android/aab_android.iml (created)
  aab/pubspec.yaml (created)
  aab/README.md (created)
  aab/ios/Runner/Runner-Bridging-Header.h (created)
  aab/ios/Runner/AppDelegate.swift (created)
  aab/ios/Runner.xcodeproj/project.pbxproj (created)
  aab/lib/main.dart (created)
  aab/.idea/runConfigurations/main_dart.xml (created)
  aab/.idea/libraries/Dart_SDK.xml (created)
  aab/.idea/libraries/KotlinJavaRuntime.xml (created)
  aab/.idea/modules.xml (created)
  aab/.idea/workspace.xml (created)
Running "flutter pub get" in aab...                                10.5s
Wrote 121 files.

All done!
In order to run your application, type:

  $ cd aab
  $ flutter run

To enable null safety, type:

  $ cd aab
  $ dart migrate --apply-changes

Your application code is in aab/lib/main.dart.


Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     308.9s
✓ Built build/app/outputs/flutter-apk/app-release.apk (15.4MB).
pedromassango@MacBook-Pro-de-MacBook aab % flutters build apk --verbose 
[ +102 ms] executing: [/Users/pedromassango/Code/flutter_stable/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +82 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +3 ms] 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] executing: [/Users/pedromassango/Code/flutter_stable/] git tag
--points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[ +108 ms] Exit code 0 from: git tag --points-at
8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] 2.0.2
[  +54 ms] executing: [/Users/pedromassango/Code/flutter_stable/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/pedromassango/Code/flutter_stable/] git ls-remote
--get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +70 ms] executing: [/Users/pedromassango/Code/flutter_stable/] git rev-parse
--abbrev-ref HEAD
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +8 ms] executing: sw_vers -productName
[  +26 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +20 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.2.2
[        ] executing: sw_vers -buildVersion
[  +21 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20D80
[  +13 ms] executing: sysctl hw.optional.arm64
[   +8 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +93 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +54 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping
update.
[  +60 ms] Skipping pub get: version match.
[ +183 ms] Generating
/Users/pedromassango/Desktop/aab/android/app/src/main/java/io/flutter/plugins/Ge
neratedPluginRegistrant.java
[  +93 ms] Building without sound null safety
[        ] For more information see
https://dart.dev/null-safety/unsound-null-safety
[  +21 ms] Running Gradle task 'assembleRelease'...
[   +5 ms] Using gradle from /Users/pedromassango/Desktop/aab/android/gradlew.
[   +1 ms] /Users/pedromassango/Desktop/aab/android/gradlew mode: 33261
rwxr-xr-x.
[  +15 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android
Studio.app/Contents/Info.plist
[  +16 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$A
PP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:
$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$AP
P_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVM
Version":"1.8*,1.8+","MainClass":"com.intellij.idea.Main","Properties":{"idea.pa
ths.selector":"AndroidStudio4.1","idea.executable":"studio","idea.platform.prefi
x":"AndroidStudio","idea.vendor.name":"Google","idea.home.path":"$APP_PACKAGE\/C
ontents"}},"NSDesktopFolderUsageDescription":"An application in Android Studio
requests access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-201.8743.12.4
1.6953283","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An
application in Android Studio requests access to the device's
camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleType
IconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBund
leTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitc
hing":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHigh
ResolutionCapable":true,"CFBundleShortVersionString":"4.1","NSMicrophoneUsageDes
cription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio"
,"NSLocationUsageDescription":"An application in Android Studio requests access
to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTy
peRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],
"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"pu
blic.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVe
rsion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android
Studio requests access to the user's Documents
folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio
requests access to the user's Downloads
folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio
requests access to files on a network volume.","CFBundleGetInfoString":"Android
Studio 4.1, build AI-201.8743.12.41.6953283. Copyright JetBrains s.r.o., (c)
2000-2020","NSRemovableVolumesUsageDescription":"An application in Android
Studio requests access to files on a removable volume."}
[  +11 ms] executing: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +176 ms] Exit code 0 from: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6915495, mixed mode)
[   +3 ms] executing: [/Users/pedromassango/Desktop/aab/android/]
/Users/pedromassango/Desktop/aab/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib/main.dart
-Ptrack-widget-creation=true -Ptree-shake-icons=true assembleRelease
[+4106 ms] > Task :app:compileFlutterBuildRelease
[        ] [  +95 ms] executing: [/Users/pedromassango/Code/flutter_stable/] git
-c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [        ] 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] [        ] executing: [/Users/pedromassango/Code/flutter_stable/] git
tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] [  +26 ms] Exit code 0 from: git tag --points-at
8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] [        ] 2.0.2
[        ] [  +55 ms] executing: [/Users/pedromassango/Code/flutter_stable/] git
rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic
@{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/Users/pedromassango/Code/flutter_stable/] git
ls-remote --get-url origin
[        ] [  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +76 ms] executing: [/Users/pedromassango/Code/flutter_stable/] git
rev-parse --abbrev-ref HEAD
[        ] [  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +94 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is
not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required,
skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not
required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[        ] [ +106 ms] Artifact Instance of 'MaterialFonts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is
not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not
required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required,
skipping update.
[        ] [  +68 ms] Initializing file store
[        ] [   +8 ms] Done initializing file store
[        ] [  +96 ms] Skipping target: gen_localizations
[        ] [ +364 ms] Skipping target: kernel_snapshot
[        ] [  +31 ms] Skipping target: android_aot_release_android-arm
[        ] [  +30 ms] Skipping target: aot_android_asset_bundle
[        ] [  +24 ms] Skipping target: android_aot_release_android-arm64
[        ] [  +26 ms] Skipping target: android_aot_release_android-x64
[        ] [  +28 ms] Skipping target: android_aot_bundle_release_android-arm
[        ] [  +26 ms] Skipping target: android_aot_bundle_release_android-arm64
[        ] [  +27 ms] Skipping target: android_aot_bundle_release_android-x64
[        ] [        ] Skipping target: _composite
[        ] [        ] Persisting file store
[  +52 ms] [  +10 ms] Done persisting file store
[        ] [  +10 ms] build succeeded.
[        ] [  +20 ms] "flutter assemble" took 926ms.
[        ] [   +8 ms] ensureAnalyticsSent: 0ms
[        ] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +7 ms] exiting with code 0
[  +94 ms] > Task :app:packLibsflutterBuildRelease UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:extractProguardFiles UP-TO-DATE
[        ] > Task :app:preReleaseBuild UP-TO-DATE
[        ] > Task :app:compileReleaseAidl NO-SOURCE
[        ] > Task :app:compileReleaseRenderscript NO-SOURCE
[        ] > Task :app:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :app:checkReleaseAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeReleaseAssets
[        ] > Task :app:mergeReleaseShaders UP-TO-DATE
[        ] > Task :app:compileReleaseShaders NO-SOURCE
[        ] > Task :app:generateReleaseAssets UP-TO-DATE
[        ] > Task :app:mergeReleaseAssets
[        ] > Task :app:copyFlutterAssetsRelease
[        ] > Task :app:generateReleaseResValues UP-TO-DATE
[        ] > Task :app:generateReleaseResources UP-TO-DATE
[  +96 ms] > Task :app:mergeReleaseResources UP-TO-DATE
[        ] > Task :app:createReleaseCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksRelease UP-TO-DATE
[        ] > Task :app:processReleaseMainManifest UP-TO-DATE
[        ] > Task :app:processReleaseManifest UP-TO-DATE
[        ] > Task :app:processReleaseManifestForPackage UP-TO-DATE
[        ] > Task :app:processReleaseResources UP-TO-DATE
[        ] > Task :app:compileReleaseKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileRelease UP-TO-DATE
[        ] > Task :app:compileReleaseJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileReleaseSources UP-TO-DATE
[+1201 ms] > Task :app:lintVitalRelease
[        ] > Task :app:mergeReleaseNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressReleaseAssets UP-TO-DATE
[  +97 ms] > Task :app:checkReleaseDuplicateClasses UP-TO-DATE
[        ] > Task :app:mergeReleaseGeneratedProguardFiles UP-TO-DATE
[        ] > Task :app:processReleaseJavaRes NO-SOURCE
[        ] > Task :app:mergeReleaseJavaResource UP-TO-DATE
[        ] > Task :app:minifyReleaseWithR8 UP-TO-DATE
[        ] > Task :app:collectReleaseDependencies UP-TO-DATE
[        ] > Task :app:sdkReleaseDependencyData UP-TO-DATE
[        ] > Task :app:shrinkReleaseRes UP-TO-DATE
[        ] > Task :app:mergeReleaseJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeReleaseNativeLibs UP-TO-DATE
[        ] > Task :app:stripReleaseDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningRelease UP-TO-DATE
[  +95 ms] > Task :app:packageRelease UP-TO-DATE
[        ] > Task :app:assembleRelease
[        ] Deprecated Gradle features were used in this build, making it
incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See
https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_li
ne_warnings
[        ] BUILD SUCCESSFUL in 5s
[        ] 35 actionable tasks: 6 executed, 29 up-to-date
[ +420 ms] Running Gradle task 'assembleRelease'... (completed in 6.4s)
[  +39 ms] calculateSha: LocalDirectory:
'/Users/pedromassango/Desktop/aab/build/app/outputs/flutter-apk'/app.apk
[   +9 ms] calculateSha: reading file took 8us
[ +230 ms] calculateSha: computing sha took 230us
[   +4 ms] ✓ Built build/app/outputs/flutter-apk/app-release.apk (15.4MB).
[   +3 ms] "flutter apk" took 7,208ms.
[ +263 ms] ensureAnalyticsSent: 259ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
pedromassango@MacBook-Pro-de-MacBook aab % 
```
</details>

**Comment by kdelorey** [comment] 2021-03-16 13:23
Looks like my CI pipeline is passing again. Is there an alternative repository that can be used/added? I believe bintray/jcenter is shutting down soon anyways.

**Comment by pedromassangocode** [comment] 2021-03-17 10:14
I going to close this as duplicate of https://github.com/flutter/flutter/issues/78338 as this was caused by JCenter being down. 

Flutter team is planning to move android repositories away from JCenter.
Thank you

**Closed by pedromassangocode** 2021-03-17 10:14 UTC
Labels: in triage, waiting for customer response
