### ISSUE TITLE
Flutter / SDK Manager issues.

### ISSUE THREAD

**Issue by esam22** [flutter/flutter#53625] opened 2020-03-31 03:16 UTC
flutter doctor -v: `C:\Users\busin>flutter doctor -v
`[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-AU)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\busin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed      instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.43.2)
    • VS Code at C:\Users\busin\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available`

`C:\Users\busin>flutter doctor --android-licenses
A newer version of the Android SDK is required. To update, run:
C:\Users\busin\AppData\Local\Android\sdk\tools\bin\sdkmanager --update`

When I try to upgrade sdk it gives me: `sdkmanager --update
'sdkmanager' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by ShardulNalegave** [comment] 2020-03-31 06:57
Hi, so I think the problem is because you run the `--update` command in a directory other than the one where the `sdkmanager` batch file is present and you don't have the directory in `PATH` variable.

Try to `cd` into the directory where `sdkmanager` file is present and then run the command.

**Comment by TahaTesser** [comment] 2020-03-31 08:21
Duplicate of [#51712](https://github.com/flutter/flutter/issues/51712)
Please check out this [solution](https://github.com/flutter/flutter/issues/51712#issuecomment-593721423)

**Closed by TahaTesser** 2020-03-31 08:21 UTC

**Comment by esam22** [comment] 2020-03-31 09:03
hi, when i try to do that it comes up with this: `C:\Users\busin\AppData\Local\Android\Sdk\tools\bin>sdkmanager --update
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more`

**Comment by TahaTesser** [comment] 2020-03-31 11:52
@esam22 
Manually install sdk tools from Android studio 
Please check out this [solution](https://github.com/flutter/flutter/issues/51712#issuecomment-593721423)
