### ISSUE TITLE
Shorter background color height when using  Chinese pingyin pingfang font in iOS devices

### ISSUE THREAD

**Issue by xiaoxiaowesley** [flutter/flutter#76770] opened 2021-02-25 08:02 UTC
It only happened in iOS. When enter pingyin you will find  the  rectangle height of space is different with other characters which is shorter than others.

Look the space between 'i' and 'h'.

And I found there is  an similar issue here
https://github.com/flutter/engine/pull/16709

<img height="720" src="https://user-images.githubusercontent.com/44207000/109120756-4fe7a600-7781-11eb-939e-71232122c6ab.PNG">

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
class FDTextEditingController extends TextEditingController {

  FDTextEditingController(
      {String text,
        this.editingTextStyle = const TextStyle(backgroundColor: Color(0xFFE9E9EA))})
      : super(text: text);

  FDTextEditingController.fromValue(TextEditingValue value,
      {this.editingTextStyle =
      const TextStyle(backgroundColor: Color(0xFFE9E9EA))})
      : super.fromValue(value);

  final TextStyle editingTextStyle;

  @override
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
    if (!value.composing.isValid || !withComposing) {
      return TextSpan(style: style, text: text);
    }
    final TextStyle composingStyle = style.merge(
        editingTextStyle
    );
    return TextSpan(
        style: style,
        children: <TextSpan>[
          TextSpan(text: value.composing.textBefore(value.text)),
          TextSpan(
            style: composingStyle,
            text: value.composing.textInside(value.text),
          ),
          TextSpan(text: value.composing.textAfter(value.text)),
        ]);
  }
}

class MyTextField extends StatelessWidget {
  TextEditingController inputController;
  MyTextField(){
    inputController = FDTextEditingController(
      editingTextStyle: const TextStyle(
        backgroundColor: Color(0xFFDDDEE0),
      ),
    );
  }
//  MediaQuery
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child:
          TextField(
            controller: inputController,
            style: const TextStyle(
              fontSize: 32.0,
              fontFamily: 'PingFang SC',
            ),
          )
      ),
    );
  }
}

void main() async {
  runApp(MaterialApp(
    home: MyTextField(),
  ));
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.4, on macOS 11.1 20C69, locale zh-Hans-CN)
    • Flutter version 1.17.4 at /Users/xx/Documents/software/flutter
    • Framework revision 1ad9baa8b9 (8 months ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/xx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max • 11F07AF2-A492-4476-A052-24AC71A433A5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 2 categories.
```
</details>

**Comment by pedromassangocode** [comment] 2021-02-25 09:43
Hi @xiaoxiaowesley 
Can you please provide your `flutter doctor -v` and the font you used in your app?
Thank you

**Comment by xiaoxiaowesley** [comment] 2021-02-25 12:47
> Hi @xiaoxiaowesley
> Can you please provide your `flutter doctor -v` and the font you used in your app?
> Thank you

OK.I has updated the issue content.

**Comment by pedromassangocode** [comment] 2021-02-25 13:16
I notice that you are using a custom font family, can you please point me where you get it? So that I can download it if it is public.
Thank you

**Comment by xiaoxiaowesley** [comment] 2021-02-26 01:38
> I notice that you are using a custom font family, can you please point me where you get it? So that I can download it if it is public.
> Thank you

No.'Pingfang SC' is not custom font. It's system font in iOS system

**Comment by pedromassangocode** [comment] 2021-02-26 08:17
Hi @xiaoxiaowesley 
I cannot reproduce the issue on latest stable channel.

I noticed that your Flutter version is eight months old (1.17.4). That is possible that this was already fixed.
Can you please upgrade and try again? If the issue persists. please provide your `flutter doctor -v`.
Thank you

**Comment by xiaoxiaowesley** [comment] 2021-03-01 02:44
> Hi @xiaoxiaowesley
> I cannot reproduce the issue on latest stable channel.
> 
> I noticed that your Flutter version is eight months old (1.17.4). That is possible that this was already fixed.
> Can you please upgrade and try again? If the issue persists. please provide your `flutter doctor -v`.
> Thank you

I upgraded to newest flutter version 1.22.6 and still don't work. Are you switch to chinese qwer pingying keyboard and make sure the iOS version is iOS14?

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.6 at /Users/xx/Documents/software/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Flutter download mirror http://flutter-storage.alibaba-inc.com/xianyu

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/xx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 201.9245

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • MI 6 (mobile)             • 8f405d61                                 • android-arm64 • Android 9 (API 28)
    • RoyChan 的 iPhone (mobile) • 9f4880651c05ea08146eeb2d66408def76cdceee • ios           • iOS 14.3
```

**Comment by pedromassangocode** [comment] 2021-03-01 06:52
Hi @xiaoxiaowesley 
I'm not sure if I have this `pingying` keyboard available on Simulator.

| | |
|-|-|
|![Screen Shot 2021-03-01 at 07 50 36](https://user-images.githubusercontent.com/67424416/109461684-d262b500-7a62-11eb-9fb1-0633d9b5ddd9.png)|![Screen Shot 2021-03-01 at 07 50 24](https://user-images.githubusercontent.com/67424416/109461723-df7fa400-7a62-11eb-9756-fb2f14c133ce.png)|

**Comment by xiaoxiaowesley** [comment] 2021-03-02 03:45
> Hi @xiaoxiaowesley
> I'm not sure if I have this `pingying` keyboard available on Simulator.
> 
> ![Screen Shot 2021-03-01 at 07 50 36](https://user-images.githubusercontent.com/67424416/109461684-d262b500-7a62-11eb-9fb1-0633d9b5ddd9.png)	![Screen Shot 2021-03-01 at 07 50 24](https://user-images.githubusercontent.com/67424416/109461723-df7fa400-7a62-11eb-9756-fb2f14c133ce.png)

I test simulator and it's same with devices. And my keyboard is chinese,simplified Pingyin QWERTY which is right side of your picture

**Comment by pedromassangocode** [comment] 2021-03-02 07:42
> I test simulator and it's same with devices. And my keyboard is chinese,simplified Pingyin QWERTY which is right side of your picture

Sorry, I though they are different.

I still cannot reproduce this issue.

![gif](https://user-images.githubusercontent.com/67424416/109614498-01e0f280-7b33-11eb-9d0c-15f501372bb0.gif)

Your code seems to be using a custom font, this font must be referenced in your `pubspec.yaml`.

```dart
          TextField(
            controller: inputController,
            style: const TextStyle(
              fontSize: 32.0,
              fontFamily: 'PingFang SC',
            ),
```

**Comment by xiaoxiaowesley** [comment] 2021-03-05 03:56
> > I test simulator and it's same with devices. And my keyboard is chinese,simplified Pingyin QWERTY which is right side of your picture
> 
> Sorry, I though they are different.
> 
> I still cannot reproduce this issue.
> 
> ![gif](https://user-images.githubusercontent.com/67424416/109614498-01e0f280-7b33-11eb-9d0c-15f501372bb0.gif)
> 
> Your code seems to be using a custom font, this font must be referenced in your `pubspec.yaml`.
> 
> ```dart
>           TextField(
>             controller: inputController,
>             style: const TextStyle(
>               fontSize: 32.0,
>               fontFamily: 'PingFang SC',
>             ),
> ```

And I don't add anything in pubspec.yaml. 
The font 'PingFang SC' is iOS preinstall font and I just declare and use it explicitly.  Here is the apple all preinstall  fonts https://developer.apple.com/fonts/system-fonts/

![1](https://user-images.githubusercontent.com/44207000/110064968-20502380-7da9-11eb-990d-688a2d517020.gif)

As I had said I found the key of problem and the similar flutter/engine#16709 .And I modify the engine to solove problem. But flutter developer said this is skia's problem instead of engine

**Comment by pedromassangocode** [comment] 2021-03-05 10:17
This seems to reproduce on iOS 14.2 and above.

<img width="371" alt="Screenshot 2021-03-05 at 1 22 06 PM" src="https://user-images.githubusercontent.com/67424416/110101699-31e2fc80-7da4-11eb-9f02-f2c170f2e912.png">


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
  locale en-GB)
  • Flutter version 2.0.1 at /Users/dhs/documents/Fluttersdk/flutter
  • Framework revision c5a4b4029c (14 hours ago), 2021-03-04 09:47:48 -0800
  • Engine revision 40441def69
  • Dart version 2.12.0
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
  • Android SDK at /Users/dhs/Library/Android/sdk
  • Platform android-30, build-tools 30.0.0
  • Java binary at: /Applications/Android
   Studio.app/Contents/jre/jdk/Contents/Home/bin/java
  • Java version OpenJDK Runtime Environment (build
   1.8.0_242-release-1644-b3-6915495)
  • All Android licenses accepted.
[!] Xcode - develop for iOS and macOS
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Xcode 12.3, Build version 12C33
  ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
    CocoaPods is used to retrieve the iOS and macOS platform side's plugin
    code that responds to your plugin usage on the Dart side.
    Without CocoaPods, plugins will not work on iOS or macOS.
    For more info, see https://flutter.dev/platform-plugins
   To upgrade see
   https://guides.cocoapods.org/using/getting-started.html#installation for
   instructions.
[✓] Chrome - develop for the web
  • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
  • Android Studio at /Applications/Android Studio.app/Contents
  • Flutter plugin can be installed from:
   🔨 https://plugins.jetbrains.com/plugin/9212-flutter
  • Dart plugin can be installed from:
   🔨 https://plugins.jetbrains.com/plugin/6351-dart
  • Java version OpenJDK Runtime Environment (build
   1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
  • VS Code at /Applications/Visual Studio Code.app/Contents
  • Flutter extension version 3.18.1
[✓] Connected device (4 available)
  • SM A260G (mobile)     • 5200763ebcfa861f           •
   android-arm  • Android 8.1.0 (API 27)
  • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
   • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
  • macOS (desktop)      • macos                •
   darwin-x64   • Mac OS X 10.15.4 19E2269 darwin-x64
  • Chrome (web)        • chrome                •
   web-javascript • Google Chrome 88.0.4324.192
! Doctor found issues in 1 category.
```
</details>

**Comment by xiaoxiaowesley** [comment] 2021-03-08 09:59
> This seems to reproduce on iOS 14.3 and above.
> 
> <img alt="Screenshot 2021-03-05 at 1 22 06 PM" width="371" src="https://user-images.githubusercontent.com/67424416/110101699-31e2fc80-7da4-11eb-9f02-f2c170f2e912.png">
> 
> flutter doctor -v

YES.Apple change the system font 'Pingfang SC'. And the charater above between 'n' and 'h' is a space  unicode '\u2006' and the metrics of '\u2006' is different between iOS 14 above and iOS below. As result the skia use the difference metrics to render show two different results. Please trust me , I solve it by myself, but It seem your team throw the issue to skia. Looooook this issue. it's same thing flutter/engine#16709

**Comment by xiaoxiaowesley** [comment] 2021-05-13 06:40
hi @xster  I am xiaxiang from xianyu alibaba team. This will be a common issue if users use iOS device. We have nodify flutter engine c++ code to fix it by ourself instead of skia code. Is flutter team has scedule to fix this problem ?

**Comment by xster** [comment] 2021-05-14 05:14
@jason-simmons did iOS move to SkParagraph already?

**Comment by jason-simmons** [comment] 2021-05-14 15:59
No - SkParagraph is not yet the default on any platform

**Comment by jason-simmons** [comment] 2021-05-15 00:45
Try setting a different `selectionHeightStyle` such as `BoxHeightStyle.max` on the `TextField`.

This will produce consistent selection rectangle heights even if some characters in the text are shorter than others.

**Comment by xster** [comment] 2021-05-19 06:44
@xiaoxiaowesley, does the above solution work for you?

**Comment by darshankawar** [comment] 2021-06-18 12:23
Since this issue is marked `P3` and has `customer: gold` label too, I am a bit reluctant to close this.
@xiaoxiaowesley Can you take a look at above comments and check if https://github.com/flutter/flutter/issues/76770#issuecomment-841573308 solution helps to resolve your issue ?

**Comment by xiaoxiaowesley** [comment] 2021-06-28 03:08
> @xiaoxiaowesley, does the above solution work for you?

Sorry for not getting back to you sooner.  

Changing the property of TextField `selectionHeightStyle` to `BoxHeightStyle.max` did't work for me.

```

import 'dart:ui';

import 'package:flutter/material.dart';
class FDTextEditingController extends TextEditingController {

  FDTextEditingController(
      {String text,
        this.editingTextStyle = const TextStyle(backgroundColor: Color(0xFFE9E9EA))})
      : super(text: text);

  FDTextEditingController.fromValue(TextEditingValue value,
      {this.editingTextStyle =
      const TextStyle(backgroundColor: Color(0xFFE9E9EA))})
      : super.fromValue(value);

  final TextStyle editingTextStyle;

  @override
  TextSpan buildTextSpan({TextStyle style, bool withComposing}) {
    if (!value.composing.isValid || !withComposing) {
      return TextSpan(style: style, text: text);
    }
    final TextStyle composingStyle = style.merge(
        editingTextStyle
    );
    return TextSpan(
        style: style,
        children: <TextSpan>[
          TextSpan(text: value.composing.textBefore(value.text)),
          TextSpan(
            style: composingStyle,
            text: value.composing.textInside(value.text),
          ),
          TextSpan(text: value.composing.textAfter(value.text)),
        ]);
  }
}

class MyTextField extends StatelessWidget {
  TextEditingController inputController;
  MyTextField(){
    inputController = FDTextEditingController(
      editingTextStyle: const TextStyle(
        backgroundColor: Color(0xFFDDDEE0),
      ),
    );
  }
//  MediaQuery
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child:
          TextField(
            controller: inputController,
            selectionHeightStyle: BoxHeightStyle.max,
            style: const TextStyle(
              fontSize: 32.0,
              fontFamily: 'PingFang SC',
            ),
          )
      ),
    );
  }
}

void main() async {
  runApp(MaterialApp(
    home: MyTextField(),
  ));
}
```

![IMG_E33271446A2D-1](https://user-images.githubusercontent.com/44207000/123573765-1b542b80-d801-11eb-9c78-a9e3a4a9a0d5.jpeg)

**Comment by fzyzcjy** [comment] 2022-03-31 05:24
Hi, is there any updates?

**Comment by dam-ease** [comment] 2023-05-11 10:46
I'm unable to reproduce this issue on the latest `stable` and `master` branches. I'd be closing this issue as it has been fixed.

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';
class FDTextEditingController extends TextEditingController {
 
  FDTextEditingController(
      {String? text,
        this.editingTextStyle = const TextStyle(backgroundColor:  Color(0xFFE9E9EA))})
      : super(text: text);

  FDTextEditingController.fromValue(TextEditingValue value,
      {this.editingTextStyle =
      const TextStyle(backgroundColor: Color(0xFFE9E9EA))})
      : super.fromValue(value);

  final TextStyle editingTextStyle;
  @override
  TextSpan buildTextSpan({required BuildContext context, TextStyle? style, required bool withComposing}) {
    if (!value.composing.isValid || !withComposing) {
      return TextSpan(style: style, text: text);
    }
    final TextStyle composingStyle = style!.merge(
        editingTextStyle
    );
    return TextSpan(
        style: style,
        children: <TextSpan>[
          TextSpan(text: value.composing.textBefore(value.text)),
          TextSpan(
            style: composingStyle,
            text: value.composing.textInside(value.text),
          ),
          TextSpan(text: value.composing.textAfter(value.text)),
        ]);}

}

class MyTextField extends StatelessWidget {
  TextEditingController? inputController;
  MyTextField(){
    inputController = FDTextEditingController(
      editingTextStyle: const TextStyle(
        backgroundColor: Color(0xFFDDDEE0),
      ),
    );
  }
//  MediaQuery
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child:
          TextField(
            controller: inputController,
            style: const TextStyle(
              fontSize: 32.0,
              fontFamily: 'PingFang SC',
            ),
          )
      ),
    );
  }
}

void main() async {
  runApp(MaterialApp(
    home: MyTextField(),
  ));
}
``` 

</p>
</details> 
<details><summary>Screenshot</summary>
<p>
<img width="371" alt="Screenshot 2021-03-05 at 1 22 06 PM" src="https://github.com/flutter/flutter/assets/53122008/633b89d9-e1c2-4aaa-966d-01ade620c69c">

</p>
</details> 
<details> <summary> flutter doctor -v </summary>

```bash
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (4 days ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

• No issues found!


```
```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.10.0 on channel stable at /Users/dammya/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Closed by dam-ease** 2023-05-11 10:46 UTC
Labels: a: text input, platform-ios, framework, f: material design, a: internationalization, customer: alibaba, has reproducible steps, P3, found in release: 2.0, found in release: 2.1
