### ISSUE TITLE
bug: MaterialPageRoute doesn't fade between routes anymore (regression)

### ISSUE THREAD

**Issue by albertodev01** [flutter/flutter#89972] opened 2021-09-13 09:52 UTC
## Steps to Reproduce

 0. Make sure you're on Flutter 2.5 and Dart 2.14
 1. Create a new Flutter project
 2. Use the code snippet below
 3. See that when moving from a page to another there isn't a fade transition anymore

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Page1(),
    ),
  );
}

class Page1 extends StatelessWidget {
  const Page1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (_) => const Page2(),
              ),
            );
          },
          child: const Text('Go!'),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  const Page2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const Center(
        child: Text('Page 2'),
      ),
    );
  }
}
```

**Expected results:** When moving from `Page1` to `Page2` a fade transition should run.

**Actual results:** When moving from `Page1` to `Page2` no transitions run.

**Note**: Before 2.5, `MaterialPageRoute` automatically added a fade transition when going from a page to another but after upgrading, it just doesn't animate anymore. I guess this is a regression bug since I haven't seen breaking change notes about this

**Comment by maheshmnj** [comment] 2021-09-13 14:28
Hi @albertodev01 Thanks for filing the issue, I don't see your code doing fade animation to get a fade effect and as a result, it is working as expected. 
Additionally You might want to take a look at how fade animation can be implemented in flutter in this [coobook](https://flutter.dev/docs/cookbook/animation/opacity-animation) 

<details>
<summary>Output</summary>

https://user-images.githubusercontent.com/31410839/133101230-d8f6794e-99c6-430a-9a00-aa5151d65dab.mov

</details>
 
 
 <details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
</details>


Thanks

**Comment by darrenaustin** [comment] 2021-09-13 18:42
@albertodev01 can you tell us what platform you were testing on? 

We removed the default transitions for desktop and web as they aren't a common feature found on typical desktop apps (see #82596). If this is on iOS or Android and you aren't seeing it, then we can take a further look.

**Comment by albertodev01** [comment] 2021-09-13 23:00
@darrenaustin I have tested it on the following devices:

 - Android: the default transition is still there
 - iOS: the default transition is still there
 - Web: the default transition is **NOT** there anymore

Thank you for pointing out #82596, which is the reason why I haven't seen the transition anymore. 

I filed this issue because I didn't see this pointed out anywhere but thank you for clearing! This is not a big deal though, to make this work anyway I just manually apply the transition by myself:

```dart
PageRouteBuilder<HomePage>(
  pageBuilder: (_, __, ___) => const HomePage(),
  transitionsBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
    final tween = Tween(
      begin: const Offset(1.0, 0.0),
      end: Offset.zero,
    );

    return SlideTransition(
      position: animation.drive(tween),
      child: child,
    );
  },
)
```

**Comment by maheshmnj** [comment] 2021-09-14 06:17
@albertodev01, I see you were talking about the default slide transitions and not Fade Transitions, and yes those transitions have been removed for web and Desktop, This is also mentioned in the [release notes ](https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-2.5.0) 

![image](https://user-images.githubusercontent.com/31410839/133204941-ce055f7f-227e-4c5f-b365-fd37d5378f9d.png)


Closing this issue as it is working as intended, if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-14 06:17 UTC
Labels: in triage

**Comment by maheshmnj** [comment] 2021-09-14 06:20
Changed title for letting others find this conversation if they stumble onto the same issue as a bug.
