### ISSUE TITLE
For Windows 10 OS. FileSystemException: FileSystemException: Cannot create file, path = 'F:\FlutterTest\sampleapps\android\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied. , errno = 5)

### ISSUE THREAD

**Issue by abusayedcse** [flutter/flutter#50539] opened 2020-02-11 04:40 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by dnfield** [comment] 2020-02-11 06:58
Does your user account have access to those files without requiring administrative priviledges?

**Comment by jonahwilliams** [comment] 2020-02-15 22:01
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-15 22:01 UTC
Labels: tool, waiting for customer response, ❖ platform-windows
