### ISSUE TITLE
Pan and Tap gesture is not working inside the flutter TabviewController

### ISSUE THREAD

**Issue by DeviArunaMurugan** [flutter/flutter#59555] opened 2020-06-16 12:53 UTC
I have used a GestureDetector which is placed inside TabViewController. In that, the Pan and Tap events of Gesture Detector are not working and instead of that the drag and tap event of TabViewController is working. How to make the events of gesture detector to work?

I have referred to this [post](stackoverflow.com/questions/61221798/gesturedetector-is-not-working-on-top-of-tabbarview). But in that, the solution for avoiding the overridden of tap gesture of the corresponding widget has provided

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: DefaultTabController(length: 3, child: MyHomePage()),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _value = 10;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        bottom: TabBar(
          tabs: [
            Tab(icon: Icon(Icons.directions_car)),
            Tab(icon: Icon(Icons.directions_transit)),
            Tab(icon: Icon(Icons.directions_bike)),
          ],
        ),
        title: Text('Tabs Demo'),
      ),
      body: TabBarView(
        children: <Widget>[
          SingleChildScrollView(
            child: Card(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: <Widget>[
                  ConstrainedBox(
                      constraints: BoxConstraints.loose(Size(200, 200)),
                      child: AspectRatio(
                          aspectRatio: 1,
                          child: GestureDetector(
                            onPanStart: (DragStartDetails details) =>
                                {print('pan start')},
                            onPanUpdate: (DragUpdateDetails details) =>
                            {print('pan update')},
                            onPanEnd: (DragEndDetails details) =>
                            {print('pan end')},
                            onTapUp: (TapUpDetails details) =>
                            {print('tap up')},
                            child: Container(
                              color: Colors.green,
                            ),
                          ))),
                  Padding(
                    padding: EdgeInsets.all(10),
                    child: Container(
                      height: 200,
                      width: 200,
                      color: Colors.lightBlue,
                    ),
                  ),
                  Container(
                    height: 200,
                    child: Slider(
                        value: _value.toDouble(),
                        min: 1.0,
                        max: 10.0,
                        divisions: 10,
                        activeColor: Colors.red,
                        inactiveColor: Colors.black,
                        label: 'Set a value',
                        onChanged: (double newValue) {
                          setState(() {
                            _value = newValue.round();
                          });
                        }),
                  ),
                  Padding(
                    padding: EdgeInsets.all(10),
                    child: Container(
                      height: 200,
                      width: 200,
                      color: Colors.lightBlue,
                    ),
                  ),
                  Container(
                    height: 200,
                    child: Slider(
                        value: _value.toDouble(),
                        min: 1.0,
                        max: 10.0,
                        divisions: 10,
                        activeColor: Colors.red,
                        inactiveColor: Colors.black,
                        label: 'Set a value',
                        onChanged: (double newValue) {
                          setState(() {
                            _value = newValue.round();
                          });
                        }),
                  )
                ],
              ),
            ),
          ),
          Container(
            color: Colors.yellow,
          ),
          Container(
            color: Colors.red,
          )
        ],
      ),
    );
  }
}
```

**Comment by VladyslavBondarenko** [comment] 2020-06-16 14:58
I see that the vertical pan isn't recognised, because the gesture scrolls column

<details>
 <summary>You can see that it's working when there is nothing to scroll</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(length: 3, child: MyHomePage()),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        bottom: TabBar(
          tabs: [
            Tab(icon: Icon(Icons.directions_car)),
            Tab(icon: Icon(Icons.directions_transit)),
            Tab(icon: Icon(Icons.directions_bike)),
          ],
        ),
        title: Text('Tabs Demo'),
      ),
      body: TabBarView(
        children: <Widget>[
          SingleChildScrollView(
            child: Card(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: <Widget>[
                  ConstrainedBox(
                      constraints: BoxConstraints.loose(Size(200, 200)),
                      child: AspectRatio(
                          aspectRatio: 1,
                          child: GestureDetector(
                            onPanStart: (DragStartDetails details) =>
                            {print('pan start')},
                            onPanUpdate: (DragUpdateDetails details) =>
                            {print('pan update')},
                            onPanEnd: (DragEndDetails details) =>
                            {print('pan end')},
                            onTapUp: (TapUpDetails details) =>
                            {print('tap up')},
                            child: Container(
                              color: Colors.green,
                            ),
                          ))),
                ],
              ),
            ),
          ),
          Container(
            color: Colors.yellow,
          ),
          Container(
            color: Colors.red,
          )
        ],
      ),
    );
  }
}
```

</details>

Horizontal pan isn't recognised because the gesture scrolls the TabView

<details>
 <summary>You can see that it's working when you have single tab</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(length: 1, child: MyHomePage()),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _value = 10;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        bottom: TabBar(
          tabs: [
            Tab(icon: Icon(Icons.directions_car)),
          ],
        ),
        title: Text('Tabs Demo'),
      ),
      body: TabBarView(
        children: <Widget>[
          SingleChildScrollView(
            child: Card(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: <Widget>[
                  ConstrainedBox(
                    constraints: BoxConstraints.loose(Size(200, 200)),
                    child: AspectRatio(
                      aspectRatio: 1,
                      child: GestureDetector(
                        onPanStart: (DragStartDetails details) =>
                            {print('pan start')},
                        onPanUpdate: (DragUpdateDetails details) =>
                            {print('pan update')},
                        onPanEnd: (DragEndDetails details) =>
                            {print('pan end')},
                        onTapUp: (TapUpDetails details) => {print('tap up')},
                        child: Container(
                          color: Colors.green,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

**Comment by DeviArunaMurugan** [comment] 2020-06-17 06:53
@VladyslavBondarenko : Thanks for your reply. I have multiple items in my TabBarView widget and more than one tab. While setting the physics: NeverScrollableScrollPhysics() in TabBarView, all the child widget of TabBarView receives gesture input but the gesture of TabBarView is working. My requirement is, the GestureDetector used as child inside the TabBarView receives all the gesture input while touching(Pan or Tap) on it, since I have done some business logic in the pan start, pan update and pan end event of gesture dectector. Like wise, I dont want restrict the TabBarView functionality(such as scrolling in the single tab or navigativating among the tabs).

Regards,
Devi

**Comment by VladyslavBondarenko** [comment] 2020-06-17 08:18
@DeviArunaMurugan 
what I see Tap gestures are detected. Do you want to have this GestureDetector with higher priority than parent TabBarView or/and SingleChildScrollView (override pan gesture for the widget but have possibility to switch tabs by pan gestures on other widgets), right? not simply detecting the pan gesture with still switching tabs with it?

**Comment by DeviArunaMurugan** [comment] 2020-06-17 13:31
@VladyslavBondarenko : Yes, I want the gesture detector with higher priority than the TabBarView. Like the drag event of the slider gets higher priority when comparing to its parent tab view and for navigating to the other tabs while using the slider, we can use other child widgets present inside the corresponding tab.  Likewise, I need the gesture detector to work and it would be good, the gesture detector gets priority if only its pan events get hooked. Otherwise, the parent TabView gets priority for the touch events. 

Regards,
Devi

**Comment by huycozy** [comment] 2022-10-20 10:25
Hi @DeviArunaMurugan, this issue seems to have been fixed on the latest stable and master channel as I cannot reproduce it there. Please see the demo below.

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/196921832-fa20f908-16b8-4209-8686-45c240e7d5d8.mov


</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (9 hours ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-9.0.pre.28, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-9.0.pre.28 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 49405135d7 (2 hours ago), 2022-10-19 20:23:12 -0700
    • Engine revision 563b8e830c
    • Dart version 2.19.0 (build 2.19.0-317.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

I'll be closing this issue as fixed. If you still experience this issue, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2022-10-20 10:25 UTC
Labels: framework, f: material design, f: scrolling, has reproducible steps, found in release: 1.20
