### ISSUE TITLE
Error Running Graddle after making changes to build.gradle upon importing firebase.

### ISSUE THREAD

**Issue by Nyarko** [flutter/flutter#46586] opened 2019-12-09 09:13 UTC
```bash
* Error running Gradle:
ProcessException: Process "C:\Users\nyark\AndroidStudioProjects\pharmassist_app\android\gradlew.bat" exited abnormally:

> Configure project :app
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
  Command: C:\Users\nyark\AndroidStudioProjects\pharmassist_app\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

```

**Comment by iapicca** [comment] 2019-12-09 13:32
Hi @Nyarko 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-09 13:32 UTC
