### ISSUE TITLE
NoSuchMethodError exception on windows desktop hot reload with 2.0.1

### ISSUE THREAD

**Issue by OranShuster** [flutter/flutter#77524] opened 2021-03-07 16:57 UTC
## Steps to Reproduce
1. Run `flutter create bug`.
2. Run the project in debug mode (i used latest intellij for this, 2020.3)
3. Change the primarySwatch color of the application  from blue to red (you can do any other change, it doesn't matter)

**Expected results:**
Hot reload working and the color changes

**Actual results:**
Exception window with the following message
```
No constructor 'StatefulWidget.' with matching arguments declared in class 'StatefulWidget'.
Receiver: StatefulWidget
Tried calling: new StatefulWidget.()
Found: new StatefulWidget.({Key? key}) => StatefulWidget
```

`flutter analyze`
```
No issues found! (ran in 3.9s)
```

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.844], locale en-US)
    • Flutter version 2.0.1 at C:\Users\orans\scoop\apps\flutter\current
    • Framework revision c5a4b4029c (3 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\orans\scoop\apps\android-sdk\current
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions.
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Users\orans\scoop\apps\jetbrains-toolbox\current\apps\IDEA-C\ch-0\203.7148.57
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.844]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45
```

**Comment by TahaTesser** [comment] 2021-03-08 13:07
Hi @OranShuster 
This has been in later channels (`dev` and `master`), a duplicate of https://github.com/flutter/flutter/issues/75419
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-08 13:07 UTC
Labels: in triage
