### ISSUE TITLE
Open URI not work in flutter web when its in mobile(Android & iOS)

### ISSUE THREAD

**Issue by ara-kurd-dev** [flutter/flutter#102280] opened 2022-04-21 07:01 UTC
## Steps to Reproduce

I created a project to generate a picture and download it via AnchorElement and when clicked on the download button nothing appear at all (it works properly on laptop this issue just comes with when it opened in mobile browser) so instead, I created an API to save the image in server and download it by a link which runs res.download in express node js all of these work on laptop browser but when it came to mobile browser like before nothing happening at all.

Flutter Doctor:
[✓] Flutter (Channel stable, 2.10.5, on macOS 11.6 20G165 darwin-x64, locale en-IQ)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.66.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability 

<details>
<summary>Code sample</summary>

```
  Future<void> downloadImage(Uint8List image) async {
    try {
      final base64data = base64Encode(image);
      final response =
          await http.post(Uri.parse(link + 'downloadImage'), body: {
        'data': jsonEncode({
          "data": base64data,
          "extension": '.jpeg',
          "name": "nawras_eid_card",
        })
      });
      final result = jsonDecode(response.body);
      html.window.open(link + result['path'], "_blnak");
     
    } catch (e) {
      print(e);
    }
  }

```

</details>

**Comment by danagbemava-nc** [comment] 2022-04-21 08:25
Hi @ara-kurd-dev, the sample you have provided is not complete. Please provide a  [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can investigate this. 

Thank you

**Comment by ara-kurd-dev** [comment] 2022-04-21 08:45
This is the example of using html.AnchorElement
```
import 'dart:convert';
import 'dart:html' as html;
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:screenshot/screenshot.dart';

class DownloadPage extends StatefulWidget {
  String image;
  DownloadPage({
    Key? key,
    required this.image,
  }) : super(key: key);

  @override
  State<DownloadPage> createState() => _DownloadPageState();
}

class _DownloadPageState extends State<DownloadPage> {

  ScreenshotController screenshotController = ScreenshotController();
  
  Future<void> downloadImage(Uint8List image) async {
    try {
      final base64data = base64Encode(image);
      final anchor = html.AnchorElement(
          href:
              "data:application/octet-stream;charset=utf-16le;base64,$base64data")
        ..setAttribute("download", "file.jpeg")
        ..click();
    } catch (e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 16),
        child: Center(
          child: Column(
            children: [
              Screenshot(
                controller: screenshotController,
                child: Stack(
                  alignment: Alignment.center,
                  children: <Widget>[
                    Image.asset(widget.image, height: 400),
                  ],
                ),
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                  child: Text('Download'),
                  onPressed: () async {
                    final result = await screenshotController.capture();
                    await downloadImage(result!);
                  }),
            ],
          ),
        ),
      ),
    );
  }
}

```

As I referred before this widget work properly on non mobile browser but when I want to test it on mobile browser nothing happening at all

**Comment by danagbemava-nc** [comment] 2022-04-21 12:35
Hi @ara-kurd-dev, can you test if this works without the `screenshot` package?

**Comment by ara-kurd-dev** [comment] 2022-04-22 07:46
Thanks, @danagbemava-nc the issue was the package, but not only the package but the function that Flutter uses to capture a widget is not available on the web I use an inspector on my mobile:
![2022-04-22 10 38 46 (1)](https://user-images.githubusercontent.com/78718160/164637334-ad3bfbc1-029b-4bab-82a9-6004d0517964.png)

so decided to use raw flutter code to do the same task:
```
RenderRepaintBoundary boundary =
        _globalKey.currentContext!.findRenderObject() as RenderRepaintBoundary;
    ui.Image image = await boundary.toImage(pixelRatio: 3.0);
    ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
```
but like before it throws the same exception.
have I to create another issue for this one or there is the same issue?

Again Thanks for your response.

**Comment by danagbemava-nc** [comment] 2022-04-22 08:15
Hi @ara-kurd-dev, the issue with the image capture not working on mobile web is known and is being tracked in #49857.

The reason it works on desktop is that desktop uses the `canvaskit` renderer by default whereas the mobile web uses the `html` renderer by default. I believe if you build with the `canvaskit` renderer you should be able to capture the screenshot on mobile, but I haven't tested that. 

Given that your initial report actually works, I'm going to close this issue. 

Thank you

**Closed by danagbemava-nc** 2022-04-22 08:15 UTC
Labels: in triage
