### ISSUE TITLE
Unable to lauch app on USB device

### ISSUE THREAD

**Issue by LorenzoPantano** [flutter/flutter#31117] opened 2019-04-16 08:29 UTC
## Steps to Reproduce

I connected my usb device to the computer (Redmi note 7), running flutter devices displays that there are no problems, the device is connected. When I try to lauch the demo app with flutter run the process fails after "Inizializing gradle...". 

## Logs
 C:\Users\Lorenzo Pantano\first>flutter run --verbose
[  +47 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +326 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms] origin/stable
[   +4 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[ +264 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +2 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[ +390 ms] Exit code 0 from: git ls-remote --get-url origin
[   +5 ms] https://github.com/flutter/flutter.git
[   +4 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%H
[ +624 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[   +2 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%ar
[ +223 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +2 ms] 9 weeks ago
[   +3 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +702 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] v1.2.1-0-g8661d8aec
[ +400 ms] executing: C:\Users\defaultuser0\Documents\Android\Sdk\platform-tools\adb devices -l
[ +376 ms] Exit code 0 from: C:\Users\defaultuser0\Documents\Android\Sdk\platform-tools\adb devices -l
[   +3 ms] List of devices attached
           6ed2ca41               device product:lavender_eea model:Redmi_Note_7 device:lavender transport_id:1
[ +611 ms] C:\Users\defaultuser0\Documents\Android\Sdk\platform-tools\adb -s 6ed2ca41 shell getprop
[ +153 ms] ro.hardware = qcom
[+8857 ms] Launching lib/main.dart on Redmi Note 7 in debug mode...
[  +78 ms] Initializing gradle...
[   +8 ms] Using gradle from C:\Users\Lorenzo Pantano\first\android\gradlew.bat.
[+1534 ms] executing: C:\Users\Lorenzo Pantano\first\android\gradlew.bat -v
CreateProcessW failed 193
[ +250 ms] "flutter run" took 11.992ms.
[   +1 ms] "flutter run" took 11.992ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: d346de0250a7a618)
Crash report written to C:\Users\Lorenzo Pantano\first\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.

#logfile

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --verbose

## exception

ProcessException: ProcessException: %1 non è un'applicazione di Win32 valida.

  Command: C:\Users\Lorenzo Pantano\first\android\gradlew.bat -v

#0      runAsync (package:flutter_tools/src/base/process.dart:228:33)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:243:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:210:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:191:37)
<asynchronous suspension>
#4      _readGradleProject (package:flutter_tools/src/android/gradle.dart:119:31)
<asynchronous suspension>
#5      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#6      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:137:23)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:37:32)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:288:56)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#19     Future._complete (dart:async/future_impl.dart:473:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#22     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#30     Future._complete (dart:async/future_impl.dart:473:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#33     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#34     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#35     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#41     Future._complete (dart:async/future_impl.dart:473:7)
#42     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#43     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

C:\Users\Lorenzo Pantano\first>flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Versione 10.0.17134.706], locale it-IT)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\defaultuser0\Documents\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\defaultuser0\Documents\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\Lorenzo Pantano\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • Redmi Note 7 • 6ed2ca41 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by csells** [comment] 2020-01-13 16:38
@LorenzoPantano we've made a number of fixes in our gradle support. Are you able to do the following things to check whether we've fixed this issue?

- ```flutter upgrade```
- remove the android sub-folder from your project
- re-create the android sub-folder with ```flutter create .``` in your project directory
- ```flutter run -d <deviceid>```

**Comment by jmagman** [comment] 2020-01-14 23:50
Duplicate of https://github.com/flutter/flutter/issues/30329.

**Closed by jmagman** 2020-01-14 23:50 UTC
Labels: severe: crash, t: gradle, tool, waiting for customer response, ▣ platform-android
