### ISSUE TITLE
E/SurfaceSyncer(20290): Failed to find sync for id=0   &&  W/Parcel  (20290): Expecting binder but got null! 

### ISSUE THREAD

**Issue by sajjad-njr** [flutter/flutter#119935] opened 2023-02-03 16:07 UTC
![image](https://user-images.githubusercontent.com/67529599/216649111-7e4b10f9-dbca-4e10-a924-c5574fe344d7.png)

 

 

## Steps to Reproduce

1. I am using  geolocator: ^9.0.2 for getting Latitude and Longitude . Why these error shows in the debug mood , these are 

<br>First one
` E/SurfaceSyncer(20290): Failed to find sync for id=0 `
<br>second one
`
     W/Parcel  (20290): Expecting binder but got null!
`

**Comment by huycozy** [comment] 2023-02-06 04:40
@sajjad-njr 
From what I can see, the issue is related to a 3rd party plugin (`geolocator`) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Baseflow/flutter-geolocator/issues).

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2023-02-06 04:40 UTC
Labels: in triage

**Comment by sajjad-njr** [comment] 2023-02-06 05:27
Oh. That's my mistake to put it here. I am sorry fir that. Thank you for information 🥰
