### ISSUE TITLE
Flutter web debug stops on breakpoints but in another source file on Visual Studio Code

### ISSUE THREAD

**Issue by dumabg** [flutter/flutter#101139] opened 2022-03-31 19:33 UTC
I'm using flutter web on Visual Studio Code for a long time without problems. I've updated to the last Flutter release (2.10.4) and all continues well during some days but, suddenly, the breakpoints stops in other parts of code.

I've created a new project and put a breakpoint on main.dart, on runApp(MyApp()):

```dart
void main() {
  runApp(MyApp());
}
``` 

When the program starts, on VSC the breakpoint is stopped on the file web_entrypoint.dart (not in main.dart), on the first line. On Chrome, is correct, the source shown is main.dart and stopped on the breakpoint.

I've downgraded Flutter, uninstalled Flutter and Visual Studio Code, but continues with the same problem. 

Flutter doctor indicates that everything is correct:

```
✓] Flutter (Channel stable, 2.10.4, on KDE neon User - 5.24 5.13.0-39-generic, locale es_ES.UTF-8)
    • Flutter version 2.10.4 at /home/indulgeme-dev/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (hace 7 días), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio-2021.1.1/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /opt/android-studio-2021.1.1/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Moto G 5 Plus (mobile) • ZY2247BMKF • android-arm    • Android 8.1.0 (API 27)
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by maheshmnj** [comment] 2022-04-01 07:31
Hi @dumabg, Thanks for filing the issue. I am able to reproduce the issue on stable and the master channel on macOS, While it works fine on Ubuntu and execution stops at the breakpoint.
  
### macOS

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31410839/161212250-ecad47f7-6a41-45f5-9339-0abf39647396.png">

### Ubuntu

![Screenshot from 2022-04-01 12-28-35](https://user-images.githubusercontent.com/31410839/161211961-af937c1f-0e08-4728-939d-32df13cc3c72.png)

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.277, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.277 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 13d2381109 (6 hours ago), 2022-03-27 21:00:08 -0400
    • Engine revision 559e259c54
    • Dart version 2.17.0 (build 2.17.0-246.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by sgehrman** [comment] 2022-04-04 10:19
I'm on Debian and having similar problems.

**Comment by Cory-FanDemand** [comment] 2022-04-04 15:29
Is it only on Chrome 100? earlier?  other browsers?

**Comment by corymalcolmtaylor** [comment] 2022-04-04 15:34
> 

I ask because I see this too but just after upgrading to chrome 100 and I may have seen post somewhere else in which  someone mentioned it specifically in Chrome 100.

**Comment by dumabg** [comment] 2022-04-04 21:53
I have Chrome 100.0.4896.60 (Build oficial) (64 bits)

**Comment by dsyrstad** [comment] 2022-04-05 00:13
I'm having the same problem on Ubuntu -  with IntelliJ 2021.3.3 Build #IU-213.7172.25, Dart plugin 213.7306, Flutter plugin 66.0.3, Chrome Version 100.0.4896.60 (Official Build) (64-bit)
```
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 21.10 5.13.0-39-generic, locale en_US.UTF-8)
    • Flutter version 2.10.4 at /home/dsyrstad/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/dsyrstad/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/dsyrstad/Android/Sdk
    • Java binary at: /home/dsyrstad/AndroidStudio/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 13.0.0-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)  <---- NOT CORRECT
    • IntelliJ at /home/dsyrstad/IntelliJ/idea-IU-202.6397.94 <---- NOT CORRECT
    • Flutter plugin version 66.0.3
    • Dart plugin version 213.7306

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 21.10 5.13.0-39-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by annagrin** [comment] 2022-04-05 01:26
Seems like several people encountered this issue with chrome update, investigating.

**Comment by dumabg** [comment] 2022-04-05 17:23
Confirmed. I've downgraded to the same version (v99.0.4844.51) and it works. It's a Chrome problem.

**Comment by christopherfujino** [comment] 2022-04-05 21:44
It sounds like this is a confluence of two issues, one of which is https://github.com/dart-lang/webdev/issues/1557

**Comment by elliette** [comment] 2022-04-05 22:18
Yes, I believe there are two issues here. Both affect Flutter Web users when they are debugging with breakpoints:

**1. https://github.com/dart-lang/webdev/issues/1557**
> DESCRIPTION: No stack trace / variable information is shown when a user hits a breakpoint. This is only affecting users on Chrome v. 100 or later, and is due to a change that Chrome introduced. @annagrin has a fix: https://github.com/dart-lang/webdev/pull/1559

**2. https://github.com/flutter/flutter/issues/101388**
> DESCRIPTION: A user can hit a breakpoint, and inspect the call stack, but the breakpoint is in the wrong location. This is affecting users on earlier versions of Chrome (I can reproduce on `v.99.0.4844.84`).

**Comment by annagrin** [comment] 2022-04-05 22:56
duplicate of https://github.com/flutter/flutter/issues/101224

**Comment by darshankawar** [comment] 2022-04-06 06:43
Closing this as duplicate of linked issue. Please follow-up in it for further updates.

**Closed by darshankawar** 2022-04-06 06:43 UTC
Labels: tool, platform-mac, a: debugging, platform-web, platform-linux, has reproducible steps, P2, found in release: 2.10, found in release: 2.13
