### ISSUE TITLE
Remove blur at transparent CupertinoNavigationBar

### ISSUE THREAD

**Issue by desmeit** [flutter/flutter#90134] opened 2021-09-15 16:43 UTC
I try to have a transparent CupertinoNavigationBar. If I use it with an showCupertinoModalBottomSheet there is a ugly blur when I open a bottom sheet with modal bottom sheet package:

https://github.com/jamesblasco/modal_bottom_sheet

I dont think this has to do with the package because with the normal Material Appbar it is working perfect.

How can I remove the blur or is that a bug? 

![IMG_7660](https://user-images.githubusercontent.com/9454529/133474014-33e39c23-9d49-43f4-8422-230fe49bc1f1.PNG)

```
 appBar: CupertinoNavigationBar(
        border: Border(bottom: BorderSide(color: Colors.transparent)),
        backgroundColor: Colors.transparent,
        brightness: Brightness.light,
        transitionBetweenRoutes: false,
        middle: const Text('test'),
      ),
```

Is there a solution for that issue?

flutter doctor -v

[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.7 19H1217 darwin-x64, locale de-DE)
    • Flutter version 2.5.0 at /Users/XXX/development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

**Comment by maheshmnj** [comment] 2021-09-16 10:15
Hi @desmeit, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the complete output of `flutter doctor -v` to better address the issue.

Thanks

**Comment by desmeit** [comment] 2021-09-20 07:23
I made a test project:

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:modal_bottom_sheet/modal_bottom_sheet.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      onGenerateRoute: RouteGenerator.generateRoute,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void openBottomSheet(context) {
    //showModalBottomSheet(
    Future<void> future = showCupertinoModalBottomSheet(
        //useRootNavigator: true,
        //expand: true,
        context: context,
        //isScrollControlled: true,
        backgroundColor: Colors.transparent,
        builder: (BuildContext context) {
          return StatefulBuilder(
              builder: (BuildContext context, StateSetter mystate) {
            return AnimatedPadding(
                padding: EdgeInsets.only(
                  bottom: MediaQuery.of(context).viewInsets.bottom,
                ),
                duration: const Duration(milliseconds: 250),
                child: const Material(child: Center(child: Text("testmodal"))));
          });
        });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const CupertinoNavigationBar(
        border: Border(bottom: BorderSide(color: Colors.transparent)),
        backgroundColor: Colors.transparent,
        brightness: Brightness.light,
        heroTag: 'titleTest',
        transitionBetweenRoutes: false,
        middle: Text('title'),
      ),

      body: Center(
          child: TextButton(onPressed: () {
            openBottomSheet(context);
          }, child: const Text("open Modal"))),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


class RouteGenerator {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    // Getting arguments passed in while calling Navigator.pushNamed
    final args = settings.arguments;

    switch (settings.name) {
      case '/':
        return MaterialWithModalsPageRoute(
            builder: (_) => const MyHomePage());
  

      default:
        // If there is no such named route in the switch statement, e.g. /third
        return _errorRoute();
    }
  }

  static Route<dynamic> _errorRoute() {
    return MaterialPageRoute(builder: (_) {
      return Scaffold(
        appBar: AppBar(
          title: const Text('Error'),
        ),
        body: const Center(
          child: Text('ERROR'),
        ),
      );
    });
  }
}
```

**Comment by maheshmnj** [comment] 2021-09-20 07:51
@desmeit Thanks for the code sample I see that it's working as intended,

>     backgroundColor: Colors.transparent,

 since you are adding a transparent color to the `CupertinoNavigationBar`

**Comment by desmeit** [comment] 2021-09-20 10:49
yes, thats the reason but I need a transparent CupertinoNavigationBar because I have a animated background. With the normal appbar it is working but not with CupertinoNavigationBar.

**Comment by maheshmnj** [comment] 2021-09-20 14:04
@desmeit, I can reproduce the issue on the stable as well as master channel, but it looks like it could be caused by a third-party package as when using built-in `showModalBottomSheet` the  `CupertinoNavigationBar` is correctly shown. Also, it's worth noting that by adding a backgroundColor to `CupertinoNavigationBar` the app bar is shown properly.
Keeping this issue open for further investigation.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:modal_bottom_sheet/modal_bottom_sheet.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      onGenerateRoute: RouteGenerator.generateRoute,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void openBottomSheet(context) {
    Future<void> future = showCupertinoModalBottomSheet(
        //useRootNavigator: true,
        //expand: true,
        context: context,
        //isScrollControlled: true,
        backgroundColor: Colors.transparent,
        builder: (BuildContext context) {
          return Container(
            height: 300,
            color: Colors.red,
            child: ElevatedButton(child: Text('testmodal'), onPressed: () {}),
          );
        });
  }

  void showBottomSheet(context) {
    showModalBottomSheet(
        context: context,
        builder: (context) {
          return Container(
            height: 300,
            color: Colors.red,
            child: ElevatedButton(child: Text('testmodal'), onPressed: () {}),
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const CupertinoNavigationBar(
        border: Border(bottom: BorderSide(color: Colors.transparent)),
        backgroundColor: Colors.transparent,
        brightness: Brightness.light,
        heroTag: 'titleTest',
        transitionBetweenRoutes: false,
        middle: Text('title'),
      ),

      body: Center(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          ElevatedButton(
              onPressed: () {
                showBottomSheet(context);
              },
              child: Text('show bottom sheet'))
        ],
      )),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class RouteGenerator {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    // Getting arguments passed in while calling Navigator.pushNamed
    final args = settings.arguments;

    switch (settings.name) {
      case '/':
        return MaterialWithModalsPageRoute(builder: (_) => const MyHomePage());

      default:
        // If there is no such named route in the switch statement, e.g. /third
        return _errorRoute();
    }
  }

  static Route<dynamic> _errorRoute() {
    return MaterialPageRoute(builder: (_) {
      return Scaffold(
        appBar: AppBar(
          title: const Text('Error'),
        ),
        body: const Center(
          child: Text('ERROR'),
        ),
      );
    });
  }
}
```

</details>




<details>
<summary>Output</summary>


modal_bottom_sheet package             |  showModalBottomSheet
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/31410839/134015175-fac19543-2518-4420-9f8b-04bf0fa388f7.png)  |  ![](https://user-images.githubusercontent.com/31410839/134015190-79bf29d9-f121-4b07-8fe6-4d1840d13651.png)


### Setting a background Color to CupertinoNavigationBar
```
  backgroundColor: Colors.blue,
```

<img src="https://user-images.githubusercontent.com/31410839/134015920-48877855-b008-4508-a56c-75c7cd29e83b.png" width ="300">

</details>



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPad Pro (11-inch) (3rd generation) (mobile) • 4367E72A-10EB-46BA-9E12-D89A8F0DA157 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)                              • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-6.0.pre.147, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.147 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83dfb2237a (2 days ago), 2021-09-17 23:48:04 -0400
    • Engine revision 31792e0340
    • Dart version 2.15.0 (build 2.15.0-120.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2021-11-03 09:34
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-11-03 09:34 UTC
Labels: waiting for customer response, p: third party, has reproducible steps, found in release: 2.5, found in release: 2.6
