### ISSUE TITLE
it's  so   tedious   to   press r  to  reload  ,  why can't   allow   autoReload  when   user  press save   

### ISSUE THREAD

**Issue by Super1Windcloud** [flutter/flutter#154785] opened 2024-09-08 06:40 UTC
### Use case

it's  so   tedious   to   press r  to  reload  ,  why can't   allow   autoReload  when   user  press save   

### Proposal

it's  so   tedious   to   press r  to  reload  ,  why can't   allow   autoReload  when   user  press save

**Comment by iapicca** [comment] 2024-09-08 10:41
@Super1Windcloud 
try these solutions:
- [vs code](https://stackoverflow.com/a/66949547/9836706)
- [android studio](https://stackoverflow.com/a/50026380/9836706)

**Comment by stuartmorgan** [comment] 2024-09-08 13:06
Duplicate of https://github.com/flutter/flutter/issues/91584

**Closed by stuartmorgan** 2024-09-08 13:06 UTC
