### ISSUE TITLE
How to solve the problem that android can not pop up the soft keyboard after accessing the physical keyboard.

### ISSUE THREAD

**Issue by lyqiai** [flutter/flutter#39978] opened 2019-09-06 14:26 UTC

**Comment by BondarenkoStas** [comment] 2019-09-10 16:27
@lyqiai Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

Please provide your ```flutter doctor -v``` output.

Also it may be a good question to StackOverflow, in case the issue is related to implementation.

**Comment by BondarenkoStas** [comment] 2019-09-13 09:31
Closing as asked

**Closed by BondarenkoStas** 2019-09-13 09:31 UTC
Labels: d: stackoverflow
