### ISSUE TITLE
☂️Merge flutter/buildroot into flutter/engine and retire the repository.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#67373] opened 2020-10-06 03:03 UTC
Remaining work is now tracked by this label: 

[![GitHub Issues or Pull Requests by label](https://img.shields.io/github/issues/flutter/flutter/e%3A%20buildmoot)](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22e%3A+buildmoot%22)

---

_**EDITED** by @matanlurey so it's more visible to others. Original post is below:_

<details>

<summary> Background on buildroot by @chinmaygarde</summary>

The Flutter Buildroot and the Engine used to live in a common repository. [In 2016](https://github.com/flutter/buildroot/commit/af5d72a1e41672bc07f6ebb9274f9f5b3f835687), in order to facilitate building the Flutter Engine in the Fuchsia as well Flutter buildroots, the buildroot used by Flutter was [separated into its own repository](https://github.com/flutter/buildroot) with the engine DEPS file referencing the version of the buildroot to use. The Flutter Engine GN rules had to be written such that they worked when the engine was present in either buildroot.

Flutter no longer builds in the Fuchsia buildroot. Instead, Fuchsia artifacts are built from the Flutter buildroot using the Fuchsia SDK (which was not present at the time the split occurred) and vended to Flutter application authors. So, the original use case of the split is no longer present.

Even though there is no use-case served by the split, there are numerous downsides to this approach:
* Patches to GN rules (especially in the secondary buildroot) need to be split across multiple commits to the buildroot and the engine.
* Any buildroot patch necessitates a DEPS update in the engine.
* If the DEPS update fails for any reason, the same patch must be backed out in the buildroot ASAP. If someone else patches the buildroot in the meantime, they must hold till the failed buildroot update has been reverted lest their DEPS roll fail too.
* The buildroot has no presubmits. Authors who want to test buildroot updates must first update the buildroot in their fork and then point the patch that rolls DEPS in the engine to point to their fork of the buildroot so that presubmits can run. Before landing, they must back out this redirection after landing the patch in the buildroot.
* The separate PR queue for buildroot patches means the patches there are often missed by reviewers.

Personally, I dread instances where I have to update the buildroot. Not because it is hard, but because it is incredibly tedious. And quite unnecessarily so. The buildroot itself is a [significant source of technical debt](https://github.com/flutter/flutter/issues/17780) and having build rules split across two repos also makes incrementally tackling this debt hard. Merging the repos would get rid of one source of unnecessary complexity in the build process.

The buildroot has no presubmit or its own issue tracker, so I don't expect any infra related issues with this switch.

The original split occurred by preserving no history. The team has grown significantly since then and the Git history may be valuable. So maybe we should consider a subtree import instead of just copying over the files. But, I don't have a strong opinion either way.
</details>

---

The first PR is WIP, https://github.com/flutter/engine/pull/46733, which moves `third_party/glfw`.

Roughly, the process is:

1. Update [`DEPS`](https://github.com/flutter/engine/blob/main/DEPS) for `src/third_party` dependencies:

    ```diff
    - 'src/third_party/glfw':
    + 'src/flutter/third_party/glfw':
    ```

2. Update source references, such as any `BUILD.gn` files (but other files are also possible):

    ```diff
    deps = [
      "//flutter/shell/platform/embedder:embedder",
    - "//third_party/glfw",
    + "//flutter/third_party/glfw",
      "//third_party/vulkan-deps/vulkan-headers/src:vulkan_headers",
    ]
    ```

3. Update the license checker (WIP, @cbracken is hacking on this now).

---

Here is a list of all dependencies that need to be migrated.

Some of these (i.e. `skia`) will be more difficult, and might require a few incremental PRs, or closer work with folks on the engine team. Others, like the Dart packages, or leaf-level C++ packages that aren't highly used (like `glfw`) are simpler, and can be done more simply (see https://github.com/flutter/engine/pull/46733).

To volunteer, edit this table and replace `None` with `<link-to-GH-issue>`, and assign yourself to the GH issue.

You can follow [this template](https://github.com/flutter/flutter/issues/136284):

> As part of eliminating the Flutter buildroot (#67373), we are moving all third-party dependencies from `//third_party` to `//flutter/third_party`.
> 
> Steps:
> * [x] Buildroot: Migrate `BUILD.gn` to `build/secondary/flutter/third_party/BUILD.gn` https://github.com/flutter/buildroot/pull/777
> * [ ] Engine: Update `DEPS` and references to use new location/targets https://github.com/flutter/engine/pull/46733
> 
> This is an abridged form of a longer, stepwise migration that we _may_ use for more complex future migrations:
> * [ ] Buildroot: Copy `BUILD.gn` to `build/secondary/flutter/third_party/BUILD.gn`
> * [ ] Engine: Update `DEPS` and references to use new location
> * [ ] Buildroot: Eliminate old `BUILD.gn` from `build/secondary/third_party/BUILD.gn`
> * [ ] Engine: Eliminate `DEPS` references to old location
>
> Part of #67373

## C++ or Utilities

Done | Source | Destination | Issue | 
---- | ------- | ----------- | ------ |
 :white_check_mark: | `src/third_party/abseil-cpp` | `src/flutter/third_party/abseil-cpp` | https://github.com/flutter/flutter/issues/144201
 :white_check_mark: | `src/third_party/angle` | `src/flutter/third_party/angle` | https://github.com/flutter/flutter/issues/144786
 :white_check_mark: | `src/third_party/benchmark` | `src/flutter/third_party/benchmark` | https://github.com/flutter/engine/pull/47652
 :white_check_mark: | `src/third_party/boringssl` | `src/flutter/third_party/boringssl` | https://github.com/flutter/engine/pull/50601
 :white_check_mark: | `src/third_party/expat` | `src/flutter/third_party/expat` | https://github.com/flutter/engine/pull/48193
 :white_check_mark: | `src/third_party/flatbuffers` | `src/flutter/third_party/flatbuffers` | https://github.com/flutter/engine/pull/47387
 :white_check_mark: | `src/third_party/freetype2` | `src/flutter/third_party/freetype2` | https://github.com/flutter/engine/pull/50830
 :white_check_mark: | `src/third_party/glfw` | `src/flutter/third_party/glfw` | https://github.com/flutter/flutter/issues/136284
 :white_check_mark: | `src/third_party/googletest` | `src/flutter/third_party/googletest` | https://github.com/flutter/engine/pull/50830
 :white_check_mark:  | `src/third_party/gtest-parallel` | `src/flutter/third_party/gtest-parallel` | https://github.com/flutter/engine/pull/47393
 :white_check_mark: | `src/third_party/harfbuzz` | `src/flutter/third_party/harfbuzz` | https://github.com/flutter/engine/pull/50830
 :white_check_mark: | `src/third_party/icu` | `src/flutter/third_party/icu` | https://github.com/flutter/engine/pull/50924
 :white_check_mark: | `src/third_party/imgui` | `src/flutter/third_party/imgui` | https://github.com/flutter/engine/pull/47031
 :white_check_mark: | `src/third_party/inja` | `src/flutter/third_party/inja` | https://github.com/flutter/engine/pull/47408
 :white_check_mark: | `src/third_party/json` | `src/flutter/third_party/json` | None
:white_check_mark: | `src/third_party/khronos` | `src/flutter/third_party/khronos` | https://github.com/flutter/engine/pull/47398
 :white_large_square: | `src/third_party/libcxx` | `src/flutter/third_party/libcxx` | None
 :white_large_square: | `src/third_party/libcxxabi` | `src/flutter/third_party/libcxxabi` | None
 :white_check_mark: | `src/third_party/libjpeg-turbo` | `src/flutter/third_party/libjpeg-turbo` | https://github.com/flutter/engine/pull/48193
 :white_check_mark: | `src/third_party/libpng` | `src/flutter/third_party/libpng` | https://github.com/flutter/engine/pull/50571
:white_check_mark: | `src/third_party/libtess2` | `src/flutter/third_party/libtess2` | https://github.com/flutter/engine/pull/47408
:white_check_mark:| `src/third_party/libwebp` | `src/flutter/third_party/libwebp` | https://github.com/flutter/engine/pull/48193
 :white_check_mark: | `src/third_party/libxml` | `src/flutter/third_party/libxml` |https://github.com/flutter/engine/pull/48906
 :white_check_mark: | `src/third_party/ocmock` | `src/flutter/third_party/ocmock` | https://github.com/flutter/engine/pull/48193
 :white_check_mark: | `src/third_party/perfetto` | `src/flutter/third_party/perfetto` | https://github.com/flutter/flutter/issues/144204
 :white_check_mark: | `src/third_party/protobuf` | `src/flutter/third_party/protobuf` | https://github.com/flutter/flutter/issues/144204
 :white_check_mark: | `src/third_party/pyyaml` | `src/flutter/third_party/pyyaml` | https://github.com/flutter/engine/pull/48193
 :white_check_mark: | `src/third_party/rapidjson` | `src/flutter/third_party/rapidjson` | https://github.com/flutter/engine/pull/47354
 :white_check_mark: | `src/third_party/shaderc` | `src/flutter/third_party/shaderc` | https://github.com/flutter/engine/pull/47383
 :white_check_mark: | `src/third_party/skia` | `src/flutter/third_party/skia` | https://github.com/flutter/engine/pull/47913
 :white_check_mark: | `src/third_party/stb` | `src/flutter/third_party/stb` | [None](https://github.com/flutter/engine/pull/48845)
 :white_check_mark: | `src/third_party/sqlite` | `src/flutter/third_party/sqlite` | https://github.com/flutter/engine/pull/47408
:white_check_mark: | `src/third_party/tinygltf` | `src/flutter/third_party/tinygltf` | https://github.com/flutter/engine/pull/48852
 :white_check_mark: | `src/third_party/swiftshader` | `src/flutter/third_party/swiftshader` | None
 :white_check_mark: | `src/third_party/vulkan-deps` | `src/flutter/third_party/vulkan-deps` | https://github.com/flutter/flutter/issues/144205
 :white_check_mark: | `src/third_party/vulkan_memory_allocator` |  `src/flutter/third_party/vulkan_memory_allocator` | https://github.com/flutter/flutter/issues/144812
 :white_check_mark: | `src/third_party/wuffs` | `src/flutter/third_party/wuffs` | https://github.com/flutter/engine/pull/48193
 :white_check_mark: | `src/third_party/yapf` | `src/flutter/third_party/yapf` |(https://github.com/flutter/engine/pull/48847

## Android and Java

TBD.

## Dart Packages

Done | Source | Destination | Issue | 
---- | ------- | ----------- | ------ |
 :white_check_mark: | `src/third_party/pkg/archive` | `src/flutter/third_party/pkg/archive` | https://github.com/flutter/engine/pull/47654
 :white_check_mark: | `src/third_party/pkg/equatable` | `src/flutter/third_party/pkg/equatable` | https://github.com/flutter/engine/pull/47654
 :white_check_mark: | `src/third_party/pkg/flutter_packages` | `src/flutter/third_party/pkg/flutter_packages` | https://github.com/flutter/engine/pull/47654
 :white_check_mark: | `src/third_party/pkg/gcloud` | `src/flutter/third_party/pkg/gcloud` | https://github.com/flutter/engine/pull/47654
 :white_check_mark: | `src/third_party/pkg/googleapis` | `src/flutter/third_party/pkg/googleapis` | https://github.com/flutter/engine/pull/47654
 :white_check_mark: | `src/third_party/pkg/platform` | `src/flutter/third_party/pkg/platform` | https://github.com/flutter/engine/pull/47654
 :white_check_mark: | `src/third_party/pkg/process` | `src/flutter/third_party/pkg/process` | https://github.com/flutter/engine/pull/47654
 :white_check_mark: | `src/third_party/pkg/process_runner` | `src/flutter/third_party/pkg/process_runner` | https://github.com/flutter/engine/pull/47654
 :white_check_mark: | `src/third_party/pkg/vector_math` | `src/flutter/third_party/pkg/vector_math` | https://github.com/flutter/engine/pull/47654

> Notably, `src/third_party/dart` is missing above. That is intentional, we plan to work on that in a second phase.

## General build infra
Done | Source | Destination | Issue | 
---- | ------- | ----------- | ------ |
 :white_check_mark: | `src/build_overrides` | `src/flutter/build_overrides` | https://github.com/flutter/flutter/issues/144790

**Comment by chinmaygarde** [comment] 2020-10-06 03:04
cc @jason-simmons @cbracken @zanderso

**Comment by cbracken** [comment] 2020-10-06 21:53
Definitely in favour of merging buildoot into the engine repo. When we do this, we'll need to update the engine build wiki to eliminate the relevant instructions.

One thing I run across relatively frequently are patches that have landed in the buildroot that were never rolled (or can't roll) to the engine repo. Whenever we hit this situation, it typically involves a minor archaeological expedition to figure out what the change was intended to fix and why it wasn't rolled as well as a decision on whether to revert those changes before applying my own or try to roll them through.

**Comment by stuartmorgan** [comment] 2020-10-06 21:57
The split is also super annoying when trying to maintain any relatively long-lived engine branch that involves buildroot changes (as a current example, the UWP development fork), because keeping up with current master involves maintaining two parallel branches, updating them both at the same time, and updating the DEPS in the fork.

**Comment by matanlurey** [comment] 2023-10-10 23:04
This is now, once again, work in progress. I'll update the original post (thanks @chinmaygarde) with details.

**Comment by cbracken** [comment] 2023-10-11 16:50
I am assigning myself since I'm actively working on a part of this, but this effort has room for a lot of parallelisation so I encourage others who want to actively work on this to self-assign as well.

**Comment by matanlurey** [comment] 2024-08-14 20:30
Re-assigning to @jtmcdole to babysit.

**Comment by jtmcdole** [comment] 2024-08-16 17:37
Some of this work is going on here: https://github.com/flutter/flutter/issues/153059

**Comment by jtmcdole** [comment] 2024-09-26 19:47
Presented as Dash Forum. Plan is for Q4.

**Comment by matanlurey** [comment] 2024-12-30 22:52
This is done!

**Closed by matanlurey** 2024-12-30 22:52 UTC
Labels: team, engine, c: proposal, P2, c: tech-debt, team-engine, triaged-engine, e: buildmoot
