### ISSUE TITLE
Bringup mode tests showed up in flutter/plugins and flutter/packages postsubmit

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#120331] opened 2023-02-09 02:10 UTC
In https://github.com/flutter/plugins/pull/7066 I've been in the process of completing a task architecture switch for a number of macOS host LUCI tests. I just landed that (runs have started at https://github.com/flutter/plugins/runs/11213216361) but prior to that all of the `Mac_arm64 ios_platform_test*` tests were in bringup mode.

However the prior commit, which landed 5 hours before, is showing all of the Intel *and* ARM versions, as if nothing were in bringup mode: https://github.com/flutter/plugins/runs/11207463320

The previous commit, which was a day earlier, has the expected postsubmit runs (only the Intel versions of those tests), so whatever happened was recent.

Hopefully with my PR landed things will be resolved for this specific case, but I wanted to file it since having tests that are in bringup mode in the commit source randomly showing up as if they weren't seems very strange, so I thought someone might want to try look into how it was possible, and if it could happen again.

**Comment by stuartmorgan** [comment] 2023-02-09 16:18
The same thing happened in flutter/packages:
https://github.com/flutter/packages/pull/3046

The tree was red because the tests being brought out of bringup mode in that PR we red in the commit *before* that PR landed.

**Comment by drewroengoogle** [comment] 2023-02-09 16:57
In regards to the packages PR, did you notice any previous PRs running tests in bringup mode, similar to the plugins PR?

**Comment by stuartmorgan** [comment] 2023-02-09 17:11
I was trying to think about what might have triggered this both of the PRs have been open various iterations for quite a while, and it occurs to me that I had both PRs in draft for a while, and then took them out of draft yesterday. It is possible that the draft->ready for review transition is incorrectly triggering a .ci.yaml sync?

**Comment by drewroengoogle** [comment] 2023-02-09 18:26
Looking at the plugins PR, something definitely seems off in regards to every test being run on the [commit](https://github.com/flutter/plugins/commit/84ad624e32417e9d34239e0df8408a42bd163757) you mentioned above. @CaseyHillers have you ever seen anything similar to this occur, where `bringup` is being ignored?

As far as the packages PR, it seems like this is intended behavior - when `bringup: true` is removed, I believe that test is supposed to be run during the PR it is being removed. Please let me know if I'm misunderstanding something.

**Comment by stuartmorgan** [comment] 2023-02-09 18:28
> As far as the packages PR, it seems like this is intended behavior - when `bringup: true` is removed, I believe that test is supposed to be run during the PR it is being removed. Please let me know if I'm misunderstanding something.

It supposed to be run in the PR where it is being removed, yes. It is not supposed to be run **in postsubmit runs on main** for PRs that are submitted to main **before** the PR that removes `bringup: true` is landed.

**Comment by stuartmorgan** [comment] 2023-02-10 16:28
This just happened again (https://github.com/flutter/packages/runs/11256786582, test was added yesterday and the PR to enabled it [hasn't landed](https://github.com/flutter/packages/pull/3190)). Is it expected that the PR linked above wouldn't have fixed this (e.g., it hasn't propagated to the necessary places yet)?

**Comment by CaseyHillers** [comment] 2023-02-10 18:18
Correct, Cocoon changes deploy at 8 AM PST on weekdays, so this is available now.

**Comment by stuartmorgan** [comment] 2023-02-10 18:19
Great, thanks! I couldn't remember what the schedule was.

**Comment by godofredoc** [comment] 2023-02-16 23:09
@CaseyHillers can we close this bug?

**Comment by CaseyHillers** [comment] 2023-02-16 23:38
Verified a commit in flutter/packages is no longer showing Mac_x64 ios_build_all_packages stable on postsubmit.

@stuartmorgan if you're still seeing this, please reopen.

**Closed by CaseyHillers** 2023-02-16 23:38 UTC
Labels: team: infra, P1
