### ISSUE TITLE
(elided 2 frames from class _AssertionError)

### ISSUE THREAD

**Issue by john-erik-moscoso** [flutter/flutter#127550] opened 2023-05-25 04:15 UTC
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/binding.dart': Failed assertion: line 364 pos 12:
'!_debugMouseTrackerUpdateScheduled': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RendererBinding._scheduleMouseTrackerUpdate (package:flutter/src/rendering/binding.dart:364:12)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:359:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#7      _invoke (dart:ui/hooks.dart:142:13)
#8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#9      _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
![2023-05-24_23h14_17](https://github.com/flutter/flutter/assets/130120260/189776b2-1ab7-483a-8c74-01dc590fad02)

**Comment by danagbemava-nc** [comment] 2023-05-25 07:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/84241.

Kindly subscribe to the original issue for updates.

Thank you.

**Closed by danagbemava-nc** 2023-05-25 07:16 UTC
Labels: in triage
