### ISSUE TITLE
[Plugin video_player] Can I play from a List<Uint8> or stream.

### ISSUE THREAD

**Issue by huhuang03** [flutter/flutter#71903] opened 2020-12-08 10:04 UTC
For now, I only see `video_player` can only play file、assert and net. Can it support raw data?

My situation is that I choice a file in flutter web. And the return value is `data:video/mp4;base64,the data balabala`, and I now want to play it.

**Comment by darshankawar** [comment] 2020-12-08 11:54
Closing this as duplicate of https://github.com/flutter/flutter/issues/59387

**Closed by darshankawar** 2020-12-08 11:54 UTC
