### ISSUE TITLE
default selectionControls of material TextField should be decided by its Material/Cupertino ancestor first

### ISSUE THREAD

**Issue by narumishi** [flutter/flutter#75752] opened 2021-02-10 00:44 UTC
## Steps to Reproduce
1. Create a `MaterialApp` with `TextField` leave `selectionControls` unset.
2. run on an iOS device
3. quick double tap the TextField to enter selection mode
4. error: `No CupertinoLocalizations found.`

For `CupertinoTextField`, controls can be `cupertinoTextSelectionControls` and `cupertinoDesktopTextSelectionControls`
https://github.com/flutter/flutter/blob/8df58eb6502b859a82e31af10a92b034ce3e71ec/packages/flutter/lib/src/cupertino/text_field.dart#L1071-L1083

For material `TextField`, it can be all type of `TextSelectionControls`. 
https://github.com/flutter/flutter/blob/8f3a6245f014f4983e48a5be46732808c9d525e2/packages/flutter/lib/src/material/text_field.dart#L1143-L1188

If the default platform doesn't match material/cupertino, like using cupertino app in android and material app in ios. It is better to check its ancestor first for `TextField` if everything is set default.

<details>
  <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building _CupertinoTextSelectionControlsToolbar(dirty,
dependencies: [_LocalizationsScope-[GlobalKey#2752a], MediaQuery], state:
_CupertinoTextSelectionControlsToolbarState#25c6f):
No CupertinoLocalizations found.
_CupertinoTextSelectionControlsToolbar widgets require CupertinoLocalizations to be provided by a
Localizations widget ancestor.
The cupertino library uses Localizations to generate messages, labels, and abbreviations.
To introduce a CupertinoLocalizations, either use a CupertinoApp at the root of your application to
include them automatically, or add a Localization widget with a CupertinoLocalizations delegate.
The specific widget that could not find a CupertinoLocalizations ancestor was:
  _CupertinoTextSelectionControlsToolbar
The ancestors of this widget were:
  ...
  Builder
  CompositedTransformFollower
  FadeTransition
  Directionality
  _EffectiveTickerMode
  ...

The relevant error-causing widget was:
  Overlay
  file:///Users/narumi/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-2.2.2/lib/src/widgets/loading.dart:62:14

When the exception was thrown, this was the stack:
#0      debugCheckHasCupertinoLocalizations.<anonymous closure> (package:flutter/src/cupertino/debug.dart:23:7)
#1      debugCheckHasCupertinoLocalizations (package:flutter/src/cupertino/debug.dart:43:4)
#2      CupertinoLocalizations.of (package:flutter/src/cupertino/localizations.dart:262:12)
#3      _CupertinoTextSelectionControlsToolbarState.build (package:flutter/src/cupertino/text_selection.dart:135:73)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4626:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4509:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4203:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4488:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4672:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4483:5)
...     Normal element mounting (39 frames)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3554:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3312:18)
#51     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5575:32)
#52     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6119:17)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3299:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4534:16)
#55     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4681:11)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4203:5)
#57     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2533:33)
#58     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:873:21)
#59     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#60     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#61     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#62     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#66     _invoke (dart:ui/hooks.dart:167:10)
#67     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#68     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.244, on Mac OS X 10.15.7 19H512 darwin-x64, locale en-CN)
    • Flutter version 1.26.0-18.0.pre.244 at /Users/narumi/Library/flutter-master
    • Framework revision 4d25d45c2b (2 hours ago), 2021-02-09 17:51:08 -0500
    • Engine revision 53a783bbf6
    • Dart version 2.13.0 (build 2.13.0-15.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/narumi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio
    • Android Studio at /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/202.7033425/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • PACM00 (mobile)         • TS4PGIAAIZCADUQK                         • android-arm64 • Android 10 (API 29)
    • iPhone (mobile)            • 58677d0fc8984330404af9009f82e7795fc678d1 • ios           • iOS 14.1
    • macOS (desktop)         • macos                                    • darwin-x64    • Mac OS X 10.15.7 19H512
      darwin-x64

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2021-02-10 07:36
Hi @narumishi 
I cannot reproduce the issue with the code bellow on latest Master channel. I got no errors and the app runs fine.

![Screen Shot 2021-02-10 at 08 36 18](https://user-images.githubusercontent.com/67424416/107479187-0db44700-6b7b-11eb-8d0f-84518f60e345.png)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```
</details>

**Comment by narumishi** [comment] 2021-02-10 11:51
@pedromassangocode I figure out the reason, sorry for that's my fault.

I implement my app with i18n support. But only add `GlobalMaterialLocalizations.delegate` and `GlobalWidgetsLocalizations.delegate` into `localizationsDelegates`, without `GlobalCupertinoLocalizations.delegate`.
I have never update this part actually since the project is used mostly for android the past years.

**Comment by pedromassangocode** [comment] 2021-02-10 14:41
Hi @narumishi 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by pedromassangocode** 2021-02-10 14:41 UTC
Labels: in triage
