### ISSUE TITLE
Docs haz 404s, will make Travis sad

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7480] opened 2017-01-13 17:15 UTC
We're about to turn on auto-link checking for the website, but we noticed there are a few links that 404:

```

- _site/animations/index.html
  *  External link https://docs.flutter.io/flutter/physics/ScrollSimulation-class.html failed: 404 No error
- _site/assets-and-images/index.html
  *  External link https://docs.flutter.io/flutter/services/ImageResource-class.html failed: 404 No error
  *  External link https://docs.flutter.io/flutter/widgets/AssetVendor-class.html failed: 404 No error
  *  External link https://github.com/flutter/flutter/tree/master/examples/widgets failed: 404 No error
- _site/debugging/index.html
  *  External link https://docs.flutter.io/flutter/material/InkFeatures-class.html failed: 404 No error
  *  External link https://docs.flutter.io/flutter/rendering/RenderObject/debugDescribeSettings.html failed: 404 No error
  *  External link https://docs.flutter.io/flutter/scheduler/Scheduler/addPersistentFrameCallback.html failed: 404 No error
- _site/platform-services/index.html
  *  External link https://docs.flutter.io/flutter/services/MojoShell-class.html failed: 404 No error
  *  External link https://github.com/flutter/engine/blob/master/sky/shell/platform/android/io/flutter/view/FlutterView.java failed: 404 No error
  *  External link https://github.com/flutter/engine/blob/master/sky/shell/platform/ios/framework/Headers/FlutterAsyncMessageListener.h failed: 404 No error
  *  External link https://github.com/flutter/engine/blob/master/sky/shell/platform/ios/framework/Headers/FlutterMessageListener.h failed: 404 No error
  *  External link https://github.com/flutter/engine/blob/master/sky/shell/platform/ios/framework/Headers/FlutterViewController.h failed: 404 No error
  *  External link https://github.com/flutter/flutter/blob/master/examples/hello_services/ios/HelloServices/AppDelegate.m failed: 404 No error
  *  External link https://github.com/flutter/flutter/blob/master/examples/hello_services/ios/HelloServices/LocationProvider.m failed: 404 No error
  *  External link https://github.com/flutter/flutter/tree/master/examples/hello_services/ios/HelloServices failed: 404 No error
- _site/rendering/index.html
  *  internally linking to ../../example/rendering/sector_layout.dart, which does not exist (line 577)
     <a href="../../example/rendering/sector_layout.dart">sector_layout.dart
example</a>
- _site/text-input/index.html
  *  External link https://docs.flutter.io/flutter/widgets/RawInputLine-class.html failed: 404 No error
- _site/widgets-intro/index.html
  *  External link https://docs.flutter.io/flutter/material/InputState-class.html failed: 404 No error
htmlproofer 3.4.0 | Error:  HTML-Proofer found 18 failures!
```

Once we fix these, we can turn on link checking and never have a broken link again [1]

[1] results may vary

**Comment by sethladd** [comment] 2017-01-13 17:17
cc @Sfshaza @LarkAscending can you help us resolve these broken links?

Our friendly framework team is standing by to help point you to the new names, if it's not immediately obvious.

Thank you!

**Comment by LarkAscending** [comment] 2017-01-19 01:49
These should be addressed now - will wait to see what Travis says before closing this issue!

**Comment by mit-mit** [comment] 2017-01-19 08:16
Still seeing the following failures:

```
Checking 386 external links...
Ran on 26 files!
- _site/animations/index.html
  *  External link https://docs.flutter.io/flutter/animation/Force-class.html failed: 404 No error
- _site/assets-and-images/index.html
  *  External link https://docs.flutter.io/flutter/material/AssetImage-class.html failed: 404 No error
  *  External link https://docs.flutter.io/flutter/widgets/AssetImage-class.html failed: 404 No error
- _site/custom-fonts/index.html
  *  External link https://docs.flutter.io/flutter/material/TextStyle/fontStyle.html failed: 404 No error
- _site/debugging/index.html
  *  External link https://docs.flutter.io/flutter/material/Widget/debugFillDescription.html failed: 404 No error
- _site/platform-services/index.html
  *  External link https://docs.flutter.io/flutter/material/State-class.html failed: 404 No error
- _site/widgets-intro/index.html
  *  External link https://docs.flutter.io/flutter/material/State/setState.html failed: 404 No error
  *  External link https://docs.flutter.io/flutter/widgets/BoxDecoration-class.html failed: 404 No error
- _site/widgets/index.html
  *  External link https://docs.flutter.io/flutter/material/CustomPainter-class.html failed: 404 No error
  *  External link https://docs.flutter.io/flutter/material/ScrollableGrid-class.html failed: 404 No error
htmlproofer 3.4.0 | Error:  HTML-Proofer found 10 failures!
```

**Comment by eseidelGoogle** [comment] 2017-01-19 14:25
Could those be new failures after https://github.com/flutter/flutter/commit/17bc18880376b27a36278a53601d006246bb8151
which included
https://github.com/dart-lang/dartdoc/commit/7478a4f3d90f6e2d4f63db28e5f3cbf9040626d1
(and some othe rchanges) which would have changed the urls of re-exported symbols?

For example CustomPainter is now:
https://docs.flutter.io/flutter/rendering/CustomPainter-class.html
and https://docs.flutter.io/flutter/material/CustomPainter-class.html is 404.

@abarth might know.

**Comment by LarkAscending** [comment] 2017-01-19 18:22
Half of these are new errors, and one is due to perhaps a merge that didn't
go down correctly (debugFillDescription). Could be a simple workflow issue
or my learning curve, or both.

Also, there were also a few broken links that I noticed in the first pass
that the link checker did not report. I believe they were in deeply nested
directories.

Will do another round to fix these, and we'll learn more about how
HTMLproofer works, and after a couple of iterations we should be in a good
place.

**Comment by abarth** [comment] 2017-01-19 18:43
These look like new errors from de-duplicating entries on the docs web site.  Previously, if a class was exported by more than one library, we'd get a separate page for it in each library.  Now we just get one copy in the original library.  I can fix these up if you like.  (It's just a matter of re-pointing the links to the "canonical" page.)

**Comment by LarkAscending** [comment] 2017-01-19 18:48
Good to know! That sounds right for root cause...

abarth, if you can do a pass, we'll see what remains and I'll clean up the
rest.

**Comment by LarkAscending** [comment] 2017-01-19 20:35
This set of errors should be fixed by:
https://github.com/flutter/website/pull/360

Give the link checker another whirl!

**Comment by mit-mit** [comment] 2017-01-20 08:38
Woot, it's passing!

```
Validating all links.
Running ["ImageCheck", "LinkCheck", "ScriptCheck"] on ["_site"] on *.html... 
Checking 381 external links...
Ran on 26 files!
HTML-Proofer finished successfully.
```

**Comment by sethladd** [comment] 2017-01-20 16:51
Go team!

**Closed** 2017-01-26 20:03 UTC
Labels: dev: docs, dev: docs - website

**Comment by sethladd** [comment] 2017-01-26 21:04
Yay! Nice work, everyone.
