### ISSUE TITLE
Doesn't Support Linux Kernel 5.5.9

### ISSUE THREAD

**Issue by KernelErr** [flutter/flutter#52589] opened 2020-03-14 04:03 UTC
## Description
Hi, when I use Ubuntu 18.04 with the latest kernel version 5.5.9 and try to run a Flutter app in Android Studio. It sometimes stuck at installing the app, or syncing files to the device, or waiting for observatory port to be available. These errors happen on both real devices and emulators.
But after switching to old kernel version 5.3, it works fine. So I thought that it must have something with the kernel update. So if there is a fix for it?
Thanks a lot.

## Logs

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/li/development/flutter
    • Framework revision 0b8abb4724 (4 周前), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/li/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/li/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/li/development/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • HLK AL00 • C7Y6R19725003580 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by KernelErr** [comment] 2020-03-14 07:31
By the way, when I was trying to build the Fuchsia system, I also get errors about Dart. Maybe Dart isn't compatible with the latest kernel.

**Comment by jonahwilliams** [comment] 2020-03-15 03:50
Duplicate of https://github.com/flutter/flutter/issues/49185

**Closed by jonahwilliams** 2020-03-15 03:50 UTC
