### ISSUE TITLE
While I can introduce web_socket_channel into dart, iOS won't be able to call this package

### ISSUE THREAD

**Issue by sliderss** [flutter/flutter#143737] opened 2024-02-20 08:22 UTC
### Steps to reproduce

I introduced separate packages into the yaml file:
fluttertoast: ^8.2.4
bot_toast: ^4.1.3
web_socket_channel: ^2.4.4

Then：
flutter pub get

cd ios

pod install

### Actual results

fluttertoast is normal.
While I can introduce web_socket_channel and bot_toast  into dart, iOS won't be able to call this package.
I checked and found that web_socket_channel is not imported into the iOS project by cocoapod.
But I can import some other packages into the iOS project.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```myself@MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64
    (Rosetta), locale zh-Hans-CN)
    ! The dart binary is not on your path. Consider adding
      /Users/myself/flutter/bin to your path.
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.86.2)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for 高钰的iPad. Ensure the device
      is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

! Doctor found issues in 3 categories.

<!-- Paste your output here -->

```

</details>

**Comment by dam-ease** [comment] 2024-02-20 10:04
Thanks for filing this @sliderss.
I can't reproduce the issue described. Can you share the logs you get on your end?
I added the three packages and ran the code sample https://pub.dev/packages/web_socket_channel/example on iOS, everything works fine on my end.

**Comment by sliderss** [comment] 2024-02-22 03:05
My local environment：

Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1

Xcode 15.2

myself@MacBook-Pro ~ % pod --version
1.15.2


I can successfully import the web_socket_channel package into dart. I checked the pubspec.lock file and it is there, but web_socket_channel is not mentioned in the.fly-plugins-dependencies file.

And when the pod intstall,
The web_socket_channel is also not added in the /ios/.symlinks/plugins directory.


I don't know what version of iOS flutter3.19.0 can support?
What version of iOS does web_socket_channel support?

I guess that's a possibility.

Some packages can be used, such as file_picker: ^6.1.1, fluttertoast: ^8.2.4
In addition to web_socket_channel: ^2.4.4, bot_toast: ^4.1.3 also has this problem.

**Comment by dam-ease** [comment] 2024-02-22 06:50
Thanks for your response. 
This seems to be an issue with the `web_socket_channel` package which isn't a flutter package, kindly file an issue in the appropriate repo: https://github.com/dart-lang/web_socket_channel/issues.
Closing this from here as this isn't an issue with flutter itself.
Thank you!

**Closed by dam-ease** 2024-02-22 06:50 UTC
Labels: in triage
