### ISSUE TITLE
[iPadOS] With `Scribble mode` on lines are drawn on every page when using the pencil

### ISSUE THREAD

**Issue by zhoushuangjian001** [flutter/flutter#119590] opened 2023-01-31 02:42 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by zhoushuangjian001** [comment] 2023-01-31 02:43
Flutter 3.7 version, I only want to trigger the "handwriting" function in the text, other pages do not trigger

**Comment by zhoushuangjian001** [comment] 2023-01-31 02:53
Flutter version 3.7, ipad device, apple pencil's handwriting function causes the drawing to not respond in time

**Comment by danagbemava-nc** [comment] 2023-01-31 09:36
Hi @zhoushuangjian001,

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). 

Please also show some screen recordings or screenshots of the expected vs actual behavior. 

Also, do you have `scribble mode` enabled on your iPad?

Thank you

**Comment by Hochul822** [comment] 2023-02-01 03:18
I have the same issuse. 

I use [scribble_plugin](https://pub.dev/packages/scribble) which supports Apple pencil kit.

This scribble plugin was ok until i upgraded to Flutter 3.7.

But it doesn't work after i upgraded to Flutter 3.7 when using Apple's stylus.

**Comment by danagbemava-nc** [comment] 2023-02-01 07:22
Hi @Hochul822, Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third-party packages/plugins so that we can investigate this?

Thank you

**Comment by zhoushuangjian001** [comment] 2023-02-01 08:11
@danagbemava-nc @Hochul822 
The video link of the problem display is as follows: https://github.com/zhoushuangjian001/pub_images/blob/master/apple_pencil.mp4

The test project code is as follows:
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: ListView(
          children: const [
            SizedBox(
              height: 100,
              child: Text('第一个'),
            ),
            SizedBox(
              height: 100,
              child: Text('第一个'),
            ),
            SizedBox(
              height: 100,
              child: Text('第一个'),
            ),
            SizedBox(
              height: 100,
              child: Text('第一个'),
            ),
            SizedBox(
              height: 100,
              child: Text('第一个'),
            ),
            SizedBox(
              height: 100,
              child: Text('第一个'),
            ),
          ],
        ),
      ),
    );
  }
}

```

The versions of flutter are as follows:
```
 admin@MrZhou  ~/Documents/Me/Pub.dev/pub_images   master  flutter --version
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (8 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
```

flutter  doctor  -v
```
 admin@MrZhou  ~/Documents/Me/Pub.dev/pub_images   master  flutter doctor -v
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.5 21G72 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.7.0 on channel stable at /Users/admin/fvm/versions/3.7.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (8 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/admin/android
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/admin/android
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPad001 (mobile) • 00008112-0019093A018B401E • ios            • iOS 16.2 20C65
    • macOS (desktop)  • macos                     • darwin-x64     • macOS 12.5
      21G72 darwin-x64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome
      109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by wva37254626** [comment] 2023-02-01 08:27
@zhoushuangjian001 @Hochul822 @danagbemava-nc @ianloic @anaisbetts I also encountered this problem during development, when upgrading to 3.7.0, I encountered a missing line in the artboard drawing

**Comment by HHQBOOK** [comment] 2023-02-01 08:29
YES, I have the same problem

**Comment by YiHang00** [comment] 2023-02-01 09:14
After upgrading Flutter version to 3.7.0, I also encountered this problem.

**Comment by anaisbetts** [comment] 2023-02-01 09:54
@wva37254626 I have no involvement with this repo, please stop CCing me and other random people.

**Comment by danagbemava-nc** [comment] 2023-02-01 12:15
Hi @zhoushuangjian001, thanks for the sample. I want to confirm something, do you have scribble mode turned on in your apple pencil settings? 

Can you also take a look at https://github.com/flutter/flutter/issues/119180 to see if it's similar to your case?

**Comment by zhoushuangjian001** [comment] 2023-02-02 02:40
@danagbemava-nc  Yes, scribble mode on apple pencil is on.  Our project needs the graffiti function of the text, but we don't want other pages to have the graffiti function.

**Comment by danagbemava-nc** [comment] 2023-02-02 06:41
Similar to https://github.com/flutter/flutter/issues/119180 but while #119180 is about the wonky scrolling/doodling, this is about the scribbles that are left whenever the pencil interacts with the app. 

Leaving this open just in case it might have to be treated differently from #119180

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/216250641-aaaa1cbd-9638-4ee5-ad2f-0c4b3222fafb.MP4


</details>

<details>
<summary>minimal sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
    • Flutter version 3.7.1 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (14 hours ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

```
[!] Flutter (Channel master, 3.8.0-1.0.pre.32, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
    • Flutter version 3.8.0-1.0.pre.32 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9daa9aac4 (3 hours ago), 2023-02-01 22:59:24 -0500
    • Engine revision 679c4b42e2
    • Dart version 3.0.0 (build 3.0.0-192.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```
</details>

**Comment by jascodes** [comment] 2023-02-04 07:32
+1

**Comment by jascodes** [comment] 2023-02-04 16:07
@danagbemava-nc Do you think it will be a high priority? Seems like big deal to me but at the same time feels like something small trigging this. Or it will be advisable to revert to 3.3.10?

**Comment by theniceboy** [comment] 2023-02-06 02:03
Unable to upgrade to Flutter 3.7.1 as this issue is breaking my app

**Comment by jascodes** [comment] 2023-02-06 05:21
@theniceboy I have to revert to 3.3.10 actually, this screws up the entire experience.

**Comment by theniceboy** [comment] 2023-02-06 06:33
@jascodes This issue is actually fixed already in one of the branches. I'm using Flutter 3.7.0 with a custom fix. Here's how to do it:

1. Clone the Flutter repository and checkout the `revert-115146-revert-114698-revert-114647-revert-104128-scribble-mixin` branch
2. Find the commit dc8bcba2262cdaec05d4a8c884324f6f5d2ef72e and use it to create a new branch `fix-scribble`.
3. Check out the `stable` branch, and use the commit b06b8b2710955028a6b562f5aa6fe62941d6febf to create a new branch`stable-3.7.0`
4. Merge `fix-scribble` into `stable-3.7.0`

Sounds like a lot but it's actually super quick to do with [lazygit](https://github.com/jesseduffield/lazygit)

**Comment by jascodes** [comment] 2023-02-08 11:55
@goderbauer Really P4? entire pencil feature is broken. This should be hotfix.

**Comment by lemomar** [comment] 2023-02-10 15:28
> @goderbauer Really P4? entire pencil feature is broken. This should be hotfix.

Agreed, this pretty much breaks any app using the Apple Pencil.

**Comment by jmagman** [comment] 2023-02-10 17:55
This will be fixed by https://github.com/flutter/engine/pull/39516, which is almost ready to land but needs an extra round of manual testing, adjusting priority to reflect that (see https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities if you want to learn more about how we choose priorities).  I will be requesting a hotfix for it once it merges.

**Closed** 2023-02-10 19:48 UTC
Labels: platform-ios, framework, a: tablet, has reproducible steps, P3, found in release: 3.7, found in release: 3.8

**Comment by lemomar** [comment] 2023-02-10 20:01
> This will be fixed by [flutter/engine#39516](https://github.com/flutter/engine/pull/39516), which is almost ready to land but needs an extra round of manual testing, adjusting priority to reflect that (see https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities if you want to learn more about how we choose priorities). I will be requesting a hotfix for it once it merges.

Amazing, thanks!

**Comment by jmagman** [comment] 2023-02-10 20:17
Hotfix request at https://github.com/flutter/flutter/issues/120478

**Comment by zhoushuangjian001** [comment] 2023-02-22 03:09
now, I upgrade to version 3.7.4 to view, but I failed to solve this problem

**Comment by jascodes** [comment] 2023-02-22 05:44
@zhoushuangjian001 Its not stable branch till https://github.com/flutter/flutter/issues/120478 is finished

**Comment by theniceboy** [comment] 2023-02-22 08:09
Is there a way for me to manually merge it by myself? @jascodes

**Comment by jmagman** [comment] 2023-02-22 21:29
> Is there a way for me to manually merge it by myself?

The fix is in flutter/engine, you're welcome to cherry-pick the change in, but then you're signing yourself up for compiling it on your machine https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release

The fix is available in 3.8.0-12.0.pre which will be available in the [beta channel](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos) soon.

**Comment by theniceboy** [comment] 2023-02-23 04:09
Thank you! Since https://github.com/flutter/flutter/issues/120478 is completed, can I just pull the `stable` branch and get this fix? @jmagman

**Comment by jmagman** [comment] 2023-02-23 19:35
It's in 3.5.7 https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#375-feb-22-2023

**Comment by jascodes** [comment] 2023-02-24 06:19
@jmagman  you meant 3.7.5 :) And thanks very much for pushing it.

**Comment by jmagman** [comment] 2023-02-24 20:55
I did mean 3.7.5, thanks!
