### ISSUE TITLE
Question :: Can we load fonts on demand from a network ttf file?

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#16353] opened 2018-04-08 18:54 UTC
Is it possible to not bundle the font files via pubsepc.yaml file and load them dynamically.
Can NetworkAssetBundle be used for this purpose? Is there an example implementation of such a scenario somewhere?

**Comment by zoechi** [comment] 2018-04-09 05:50
dup of #15386 ?

**Comment by manujbahl** [comment] 2018-04-09 06:34
Is there a list of the default fonts supported out of box?

**Comment by manujbahl** [comment] 2018-04-09 16:50
Is there a possible workaround ?

**Comment by manujbahl** [comment] 2018-04-09 20:54
@Hixie .. any ideas on a workaround and is there a list of out of box fonts included in the platform

**Comment by Hixie** [comment] 2018-04-09 21:52
You can ship whatever fonts you want with Flutter and use them. See https://flutter.io/cookbook/design/fonts/

**Comment by Hixie** [comment] 2018-04-09 21:56
The fonts available by default are whatever fonts ship with the operating system.

Closing as dupe of #15386.

**Closed by Hixie** 2018-04-09 21:56 UTC

**Comment by srix55** [comment] 2018-07-03 12:39
Progress at #17910
