### ISSUE TITLE
io.flutter.plugins.webviewflutter.y2.o 

### ISSUE THREAD

**Issue by imharsshhh** [flutter/flutter#123990] opened 2023-04-03 05:07 UTC
Getting this type of Crash in Firebase Crashlytics 

```
Fatal Exception: java.lang.NullPointerException:
       at java.util.Objects.requireNonNull(Objects.java:220)
       at io.flutter.plugins.webviewflutter.y2.o(:13)
       at io.flutter.plugins.webviewflutter.z2$c.onProgressChanged(:9)
       at Ea.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-541411734:278)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8333)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)`
```      
 
 This is on the specific device :- Vivo V2055 (Andriod 12)
 i got this crash only one time on this specific device

**Comment by danagbemava-nc** [comment] 2023-04-03 09:07
Closing this as a duplicate of https://github.com/flutter/flutter/issues/123004

Kindly upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2023-04-03 09:07 UTC
Labels: in triage
