### ISSUE TITLE
[web] Fonts: Material fonts/icons not rendering

### ISSUE THREAD

**Issue by martinrybak** [flutter/flutter#32245] opened 2019-04-09 20:35 UTC
**Describe the bug**
Material icons do not render on web.

**To Reproduce**
```
import 'package:flutter_web/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Container(
        color: Colors.white,
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.print),
            Icon(Icons.settings),
            Icon(Icons.undo),
            Icon(Icons.person),
            Icon(Icons.location_on),
          ],
        ),
      ),
    );
  }
}
```

**Expected behavior**
Material design icons should render as they do on mobile.

**Screenshots**
# Web
<img width="374" alt="web" src="https://user-images.githubusercontent.com/2292792/55833369-5b764900-5ae5-11e9-8533-53fc51c47b94.png">

# Mobile
![mobile](https://user-images.githubusercontent.com/2292792/55833375-603afd00-5ae5-11e9-8844-94858f84a763.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome 73.0.3683.86, safari 12.0.3
 - Dart Version 2.2.1
 - Flutter Web commit SHA f9288f36fed5f3fda825082ac80f46eec6e7f62f

**Comment by DanTup** [comment] 2019-05-08 10:14
The links above posted as workarounds don't appear to be accessible - can anyone re-post what needs to be done? I saw some questions on Gitter about getting material icon to work but couldn't find anywhere to link them.

**Comment by keithliam** [comment] 2019-05-08 10:20
I am also experiencing this issue. The workaround mentioned above seems to be gone.

- OS: MacOS
- Browser: Chrome 74.0.3729.131
- Dart Version: 3.0.0

<img width="499" alt="Screen Shot 2019-05-08 at 6 14 31 PM" src="https://user-images.githubusercontent.com/17793151/57368306-6a701a00-71bd-11e9-9018-4a54eaef78de.png">

**Comment by Kiruel** [comment] 2019-09-27 21:34
Nothing new here ? The bug still here in:

I just create the project and run to Chrome.

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.7-pre.64, on Mac OS X 10.14.6 18G95, locale en-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

• No issues found!
```

<img width="494" alt="Screenshot 2019-09-27 at 23 33 17" src="https://user-images.githubusercontent.com/8250175/65803586-410d5600-e17f-11e9-9d25-3887253d2292.png">

**Comment by AppleEducate** [comment] 2019-09-29 21:50
This is happening to me too. What’s weird is in debug mode it works, when I build for release it doesn’t show.

**Comment by AppleEducate** [comment] 2019-10-03 17:18
It works only in chrome. On safari for Mac, iPadOS or iOS it is broken.

**Comment by elibwhittle** [comment] 2019-10-08 23:35
My icons render using web on pc but not through web on mobile.

**Comment by mono0926** [comment] 2019-10-23 02:56
It seems to be fixed by https://github.com/flutter/engine/pull/12801.
It enrolled to Flutter master channel now.

**Comment by AppleEducate** [comment] 2019-10-23 14:06
Can confirm it works! 

https:rodydavis.com

**Comment by nturgut** [comment] 2019-10-28 18:02
closing the bug since it is confirmed to work now.

**Closed by nturgut** 2019-10-28 18:02 UTC
Labels: severe: new feature, ☸ platform-web

**Comment by TheMisir** [comment] 2019-12-27 07:30
Now it doesn't works for mobile app (not web). In debug mode it works but not on release mode. Did someone faced with that issue?

**Comment by nturgut** [comment] 2020-01-03 12:42
I field this today: https://github.com/flutter/flutter/issues/48113

Thanks
