### ISSUE TITLE
Creating a new flutter project after setup for the first time using VsCode

### ISSUE THREAD

**Issue by Tawanny** [flutter/flutter#71651] opened 2020-12-03 12:55 UTC
I am trying to create a new flutter project using Vs code but it keeps on crashing, showing this error message below. Can someone help me on how to resolve it please, I am new with flutter and Vs code.

```
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to 'C:\Users\Bryan\Documents\Java Source code,
practice\VsCodeprac\myproject\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path =
'C:\flutter_windows_1.22.4-stable\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS     
Error: Access is denied.
, errno = 5)".
 
A crash report has been written to C:\Users\Bryan\Documents\Java Source code, practice\VsCodeprac\flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+copy+file+to+%27C%3A%5CUsers%5CBryan%5CDocuments%5CJava+Source+code%2C+practice%5CVsCodeprac%5Cmyproject%5Candroid%5Capp%5Csrc%5Cmain%5Cres%5Cmipmap-hdpi%5Cic_launcher.png%27%2C+path+%3D+%27C%3A%5Cflutter_windows_1.22.4-stable%5Cflutter%5Cpackages%5Cflutter_tools%5Ctemplates%5Capp%5Candroid.tmpl%5Capp%5Csrc%5Cmain%5Cres%5Cmipmap-hdpi%5Cic_launcher.png%27+%28OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%29

```

**Comment by darshankawar** [comment] 2020-12-03 13:25
@Tawanny 
This issue has been [fixed](https://github.com/flutter/flutter/issues/50880) and [merged](https://github.com/flutter/flutter/pull/63540) already. Please upgrade to latest master branch and try again to see if it works.

**Comment by iapicca** [comment] 2020-12-13 16:09
possible duplicate of https://github.com/flutter/flutter/issues/69116

**Comment by pedromassangocode** [comment] 2021-01-06 12:21
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-06 12:21 UTC
Labels: in triage, waiting for customer response
