### ISSUE TITLE
ImagePicker plugin tip of tree no longer works with Android.

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#16164] opened 2018-04-02 21:46 UTC
## Steps to Reproduce

Create a new flutter project and copy in the example code specified in the [README](https://github.com/flutter/plugins/tree/master/packages/image_picker). Run on an Android device. Try to hit the "camera/image picker button". Either it crashes there (first log) or I get the two pop-ups requesting permission to access my camera and my photos, and then the whole thing crashes (second log)

## Logs
 onResume setting current activity to this
Syncing files to device Nexus 5X...
D/ImagePicker( 9673): Oops! Failed create IMG_20180402_144545 file
E/MethodChannel#plugins.flutter.io/image_picker( 9673): Failed to handle method call
E/MethodChannel#plugins.flutter.io/image_picker( 9673): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at android.app.Activity.startActivityForResult(Activity.java:4487)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at android.app.Activity.startActivityForResult(Activity.java:4445)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:105)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#plugins.flutter.io/image_picker( 9673): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter ( 9673): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 9673): PlatformException(error, Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference, null)
E/flutter ( 9673): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:544:7)
E/flutter ( 9673): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
E/flutter ( 9673): <asynchronous suspension>
E/flutter ( 9673): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:47:40)
E/flutter ( 9673): <asynchronous suspension>
E/flutter ( 9673): #3      _MyHomePageState.getImage (file:///usr/local/google/home/efortuna/IdeaProjects/image_picker_test/lib/main.dart:52:39)
E/flutter ( 9673): <asynchronous suspension>
E/flutter ( 9673): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
E/flutter ( 9673): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
E/flutter ( 9673): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 9673): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter ( 9673): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
E/flutter ( 9673): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 9673): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter ( 9673): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter ( 9673): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 9673): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter ( 9673): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter ( 9673): #15     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter ( 9673): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

D/ImagePicker( 4453): Oops! Failed create Camera
D/AndroidRuntime( 4453): Shutting down VM
E/AndroidRuntime( 4453): FATAL EXCEPTION: main
E/AndroidRuntime( 4453): Process: com.yourcompany.imagepickertest, PID: 4453
E/AndroidRuntime( 4453): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2345, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.yourcompany.imagepickertest/com.yourcompany.imagepickertest.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
E/AndroidRuntime( 4453): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4324)
E/AndroidRuntime( 4453): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
E/AndroidRuntime( 4453): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime( 4453): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
E/AndroidRuntime( 4453): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 4453): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 4453): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/AndroidRuntime( 4453): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4453): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime( 4453): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/AndroidRuntime( 4453): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
E/AndroidRuntime( 4453): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1608)
E/AndroidRuntime( 4453): 	at android.app.Activity.startActivityForResult(Activity.java:4472)
E/AndroidRuntime( 4453): 	at android.app.Activity.startActivityForResult(Activity.java:4430)
E/AndroidRuntime( 4453): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onRequestPermissionsResult(ImagePickerPlugin.java:193)
E/AndroidRuntime( 4453): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:175)
E/AndroidRuntime( 4453): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
E/AndroidRuntime( 4453): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:117)
E/AndroidRuntime( 4453): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7388)
E/AndroidRuntime( 4453): 	at android.app.Activity.dispatchActivityResult(Activity.java:7239)
E/AndroidRuntime( 4453): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
E/AndroidRuntime( 4453): 	... 9 more

## Flutter Doctor

[✓] Flutter (Channel dev, v0.2.6, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.6 at /usr/local/google/home/efortuna/googleio/flutter
    • Framework revision 1d067220da (4 days ago), 2018-03-29 22:14:04 -0700
    • Engine revision 9af82c5a1a
    • Dart version 2.0.0-dev.43.0.flutter-e305117519

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/google/home/efortuna/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-3.0
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700

[✓] Connected devices (2 available)
    • Nexus 5X                  • 00b316142e9555f5 • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 8.0.0 (API 26) (emulator)

• No issues found!

This is HIGH priority as it is for I/O.

**Comment by efortuna** [comment] 2018-04-02 22:55
Update -- this is only for the ImageSource.camera option. The ImageSource.gallery seems to work fine.

**Comment by jason-simmons** [comment] 2018-04-03 00:05
I can reproduce this on a Nexus 5X running Android 8.1.0

The image picker plugin is using a third party library to access the camera (https://github.com/esafirm/android-image-picker).  That library is trying to write to the `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)` path, failing, and then returning a null intent for the camera activity.  The plugin passes the null intent to `activity.startActivityForResult`, which then throws.

For a quick workaround, try setting the `targetSdkVersion` in your app's `build.gradle` to `22`.

The write to DIRECTORY_PICTURES is failing because the app isn't acquiring the necessary runtime permissions for accessing that path.  Reducing the `targetSdkVersion` signals that this is a legacy app that is unaware of the runtime permissions model.

We'll need to update the image picker plugin to use a different storage location or request the runtime permissions.  Upgrading the plugin to the latest release of https://github.com/esafirm/android-image-picker didn't solve this.

**Comment by goderbauer** [comment] 2018-04-03 00:39
There is a PR in progress to remove the 3rd party plugin and access the camera directly: https://github.com/flutter/plugins/pull/453

**Comment by goderbauer** [comment] 2018-04-03 00:40
Also @jonahwilliams who added the other permissions to the plugin.

**Comment by jonahwilliams** [comment] 2018-04-03 00:44
I can verify that this is either fixed by the current PR or make sure it gets added

**Comment by jonahwilliams** [comment] 2018-04-03 00:44
or if it needs to be fixed sooner than just this week, I can make a PR tomorrow morning to fix it

**Comment by roughike** [comment] 2018-04-03 01:01
If there's a real rush to land the PR, I can address the feedback maybe tomorrow. However I'm really busy; it's a release week and I need to publish an article too.

**Comment by goderbauer** [comment] 2018-04-03 20:16
@efortuna can you take the latest release (0.4.1) for a spin? It's fresh of the press and includes the changes from @roughike. They should fix the issue you were having.

**Comment by efortuna** [comment] 2018-04-03 21:12
Yes! It works! Thank you for the quick fix!!

**Closed** 2018-04-03 21:12 UTC
Labels: plugin

**Comment by zoechi** [comment] 2018-08-02 11:29
Dup of #13921
