### ISSUE TITLE
[web] shared_preferences error: check the following imports: generated_plugin_registrant.dart

### ISSUE THREAD

**Issue by stuz5000** [flutter/flutter#48361] opened 2020-01-07 23:45 UTC
If:

 * deploying to flutter web
 * project uses shared_preferences
 * project has more than one main function
 * the secondary main functions are in sub-directories of the project's lib (but not lib itself)

then flutter gives an obscure error that prevent the app from launching in Chrome, but works fine when deploying to an Android emulator.

Its important to gave multiple mains -- it allows is to work on and debug individual components independently of the rest of the app.

The error:
```
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'generated_plugin_registrant.dart';` from flutterapp|lib/util/text_util_web_entrypoint.dart at 5:1

Failed after 91ms
```

lib/util/textutil.dart
```
main() {
  print("Hello");
}
```

lib/main.dart
```
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: FutureBuilder<String>(
            future: Future<String>(() async{
              await Future.delayed(Duration(seconds:1));
              SharedPreferences prefs = await SharedPreferences.getInstance();
//               prefs.setString('counter', 'ABCDEF');
              final val = prefs.getString('counter');
              return ( val ?? "--not found--");
            }),
            builder: (context, snapshot){
              if (snapshot.hasData) {
                return Text(snapshot.data);
              }
              else if (snapshot.hasError) {
                return Text((snapshot.error as Exception).toString());
              }
              else{
                return Text("Loading");
              }
            },
          ),
        ),
      ),
    );
  }
}
```

pubspec.yaml:
```
name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

#environment:
#  sdk: ">=2.1.0 <3.0.0"
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.13.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.13.0 at /home/sir/development/flutter
    • Framework revision 09126abb22 (5 weeks ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/sir/Android/Sdk
    • Java binary at: /home/sir/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/sir/soft/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /snap/intellij-idea-ultimate/193
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome
      76.0.3809.132
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by yjbanov** [comment] 2020-01-09 23:27
Could be because the tool is confused by the second entrypoint in lib/util/textutil.dart

**Comment by stuz5000** [comment] 2020-01-09 23:33
Which tool? Whichever, multiple mains works fine without shared_preferences + web deploy.

**Comment by hterkelsen** [comment] 2020-01-10 00:15
The `flutter` tool generates an entrypoint which initializes the Flutter engine and then calls the `main()` in your actual entrypoint. It looks like the problem is that we are always generating `import 'generated_plugin_registrant.dart';` assuming that the entrypoint is in `lib/` where it is a sibling of `generated_plugin_registrant.dart`.

We should either account for the nesting of the entrypoint in the relative import and correctly generate `import '../generated_plugin_registrant.dart';` here, or we should do something like `import package:<your_package_name>/generated_plugin_registrant.dart';`

**Comment by stuz5000** [comment] 2020-01-10 00:18
Does that account for the difference in behavior between the Android emulator and web? (emulator works fine).

**Comment by hterkelsen** [comment] 2020-01-10 00:20
Yes, because the generated entrypoint is only for the web.

**Comment by aayanraja210** [comment] 2020-01-12 15:25
I get the same issue when trying to import firebase, I'm importing it as 

import 'package:firebase/firebase.dart' as fb;

**Comment by aayanraja210** [comment] 2020-01-12 15:26
`Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:firebase/firebase.dart';` from spi_dev_web|lib/main.dart at 3:1

`

**Comment by stuz5000** [comment] 2020-01-13 01:36
Do you also have addition mains in directories below /lib?

**Comment by aayanraja210** [comment] 2020-01-13 02:09
Sorry, im not quite sure what you mean, i switched to using firebase core for now, 8ts working fine, but i cant use plugins like fontawesoneIcons

**Comment by hterkelsen** [comment] 2020-01-25 01:01
I have a fix for the original issue where the path to the plugin registrant is incorrect for nested entrypoints. However, I have uncovered some more issues with nested entrypoints that should be addressed for a real fix.

**Comment by hterkelsen** [comment] 2020-01-30 19:16
This was fixed in https://github.com/flutter/flutter/pull/48979

Please re-open if you still see this issue on an updated master channel.

**Comment by stuz5000** [comment] 2020-01-31 06:28
Is this publicly available on master?

As of just now, I still see the issue:

```
$ flutter channel master
$ flutter upgrade

$ rm -rf ~/.dartServer/
$ flutter clean
$ flutter build web
```

Then launch debug in Android Studio:
```
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'generated_plugin_registrant.dart';` from flutterui|lib/scratch/demo_fractional_sizing_web_entrypoint.dart at 5:1
```

```
/home/sir/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, v1.14.7-pre.58, on Linux, locale en_US.UTF-8)
    • Flutter version 1.14.7-pre.58 at /home/sir/development/flutter
    • Framework revision 83d4d63a71 (4 hours ago), 2020-01-30 18:10:36 -0800
    • Engine revision e5209202fb
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 162d6c5634)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/sir/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/sir/soft/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /snap/intellij-idea-ultimate/198
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 76.0.3809.132
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
Process finished with exit code 0
```

**Comment by sotisoti** [comment] 2020-02-02 13:13
Same issue after switching to master channel

**Comment by doppio** [comment] 2020-02-05 03:40
@stuz5000, can you re-open this issue? It looks like several of us are still having the problem on master.

**Comment by stuz5000** [comment] 2020-02-05 14:37
@doppio Gitgub won’t let me.
@hterkelsen  several people are reporting this is not fixed in the master channel. Can you whether the fix merged? If so, the issue should probably be reopened.

**Comment by hterkelsen** [comment] 2020-02-05 19:04
Reopening as several people are still hitting the issue. I'll look into it again today

**Closed** 2020-02-07 01:08 UTC
Labels: plugin, tool, ☸ platform-web

**Comment by hterkelsen** [comment] 2020-02-07 19:03
This should be fixed in master now. Please try again and let me know if you still see the issue

**Comment by doppio** [comment] 2020-02-07 22:53
@hterkelsen It fixed the issue for me and web builds are now succeeding. Thank you!

**Comment by coeaimrm** [comment] 2020-08-03 15:44
"Error when reading 'lib/generated_plugin_registrant.dart" 
Happens when you run your flutter app in chrome device after master channel upgrade without giving web support .

Solution : Give web support to your flutter by hitting below command.

flutter create .

This will create necessary support files for web app. 
further instruction will come in screen.

Reference last statement of this article 

https://flutter.dev/docs/get-started/web
