### ISSUE TITLE
Flutter TextField FocusNode not gaining focus back [FocusNode “NOT FOCUSABLE”]

### ISSUE THREAD

**Issue by renannery** [flutter/flutter#50398] opened 2020-02-08 03:19 UTC
## Steps to Reproduce

https://i.imgur.com/Z6lRPEq.mp4

**Expected results:** TextField gain focus and display keyboard

**Actual results:** The keyboard isn't displayed even though the TextField has been tapped

<details>
  <summary>Logs</summary>
[log.txt](https://github.com/flutter/flutter/files/4173717/log.txt)
</details>
[bug.zip](https://github.com/flutter/flutter/files/4173720/bug.zip)

**Comment by dnfield** [comment] 2020-02-08 05:56
Could you please provide a minimal sample that reproduces this issue?

A zipped project can be helpful, but collaborators are much more likely to be able to help if there is a small but complete code sample to help with and comment on.

**Comment by renannery** [comment] 2020-02-08 18:46
@dnfield Tks for your quick response.

I've created a small project in which I was able to reproduce the same issue.

https://github.com/renannery/flutter_textfield_focus_issue

**Comment by atavci** [comment] 2020-03-04 07:59
I am on the **stable** branch and I have the exact problem. I also looked at the sample project @renannery provided. Looks like the error occurs when navigating with a navigator key though i' dont use a navigator key in my project. Only global keys that i use is for a form and the drawer.

I have also tried the other flutter channels, beta channel has the same issue but everything works as expected in master branch.

**Comment by renannery** [comment] 2020-03-04 14:36
@atavci Nice catch dude! I completely forgot to test over Master and it's actually working, I wonder what are the changes to make it work in Master.

**Comment by TahaTesser** [comment] 2020-07-09 11:09
Hi @renannery 
Not able to reproduce this issue your issue code sample on physical XR or simulator 



![ezgif com-resize](https://user-images.githubusercontent.com/48603081/87032731-ac05b600-c202-11ea-860e-cdf18776027e.gif)


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static final navKey = new GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      navigatorKey: navKey,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MainView(),
    );
  }
}

class MainView extends StatefulWidget {
  @override
  MainViewState createState() => MainViewState();
}

class MainViewState extends State<MainView> {
  static final GlobalKey mainViewKey = new GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: IndexedStack(
        children: <Widget>[
          Navigator(
            onGenerateRoute: (route) => MaterialPageRoute(
              settings: route,
              builder: (context) => MyHomePage(title: "Search"),
            ),
          ),
        ],
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            Padding(
                padding: EdgeInsets.all(16.0),
                child: TextField(
                  decoration: InputDecoration(
                    prefixIcon: Icon(Icons.search),
                    hintText: "Search",
                  ),
                )),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          MyApp.navKey.currentState
              .push(MaterialPageRoute(builder: (context) => SecondPage()));
        },
        child: Icon(Icons.add),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  SecondPage();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second Page'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Text(
          '• if you tap BackButton the issue does not happen\n\n\n• If you drag the page back (iOS behavior), the issue happens and the TextField will not get focus again',
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (5 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
``` 

</details> 

Are you still experiencing this issue on latest `dev` channel? 
If yes, please provide `flutter doctor -v` with latest `dev`
Thank you

**Comment by TahaTesser** [comment] 2020-08-05 14:45
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-05 14:45 UTC
Labels: P4, a: text input, f: focus, f: material design, framework
