### ISSUE TITLE
Inkwell does not have splash/hover/focus state on Web when Image.ink is used as a child

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#45705] opened 2019-11-27 16:13 UTC
## Steps to Reproduce
* Use an `Inkwell` widget with an `Ink.image` as a child
* Run on web
* Hover over Inkwell and observe no hover state
* Tab to Inkwell and observe no focus state
* Tap and hold and observe no splash state

**Target Platform:** Web
**Target OS version/browser:** Chrome
**Devices:** Chrome on macOS

## Logs

```
[✓] Flutter (Channel master, v1.12.14-pre.11, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.12.14-pre.11 at /Users/raboughanem/Development/flutter
    • Framework revision 92b0ceaaa6 (34 hours ago), 2019-11-26 01:19:51 -0500
    • Engine revision 05f8c8b24b
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/raboughanem/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-stable, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
```

**Comment by yjbanov** [comment] 2019-11-27 20:58
We have a bug in compositing images: https://github.com/flutter/flutter/issues/44845. This is likely caused by it. Closing as duplicate, but if that doesn't fix it, let's reopen.

**Closed by yjbanov** 2019-11-27 20:58 UTC
Labels: f: material design, framework, ☸ platform-web
