### ISSUE TITLE
[tool_crash] UnknownException

### ISSUE THREAD

**Issue by hasanm08** [flutter/flutter#101041] opened 2022-03-30 11:38 UTC
Command
```
flutter drive --dart-define=app.flavor=develop --driver=lib/integration_test/test_driver.dart --target=lib/integration_test/scenarios/user_actions_test.dart -d web-server --driver-port=9515
```

Steps to Reproduce
1. install chrom and chrome driver 99
2. start test

Logs
UnknownException
```
 parseJsonWireResponse (package:webdriver/src/handler/json_wire/utils.dart:82:9)
JsonWireSessionHandler.parseInfoResponse (package:webdriver/src/handler/json_wire/session.dart:27:21)
JsonWireSessionHandler.parseCreateResponse (package:webdriver/src/handler/json_wire/session.dart:18:7)
InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:100:39)
AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
createDriver (package:webdriver/async_core.dart:64:19)
<asynchronous suspension>
WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:141:19)
<asynchronous suspension>
DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:272:28)
<asynchronous suspension>
FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
 AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-US)
    • Flutter version 2.10.4 at E:\flutter_windows_2.5.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = E:\SDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10 0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10 0-b96-7249189)

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 100.0.4896.60
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 99.0.1150.55

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

%23%23 Flutter Application Metadata
**Type**: app
**Version**: 2.8.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
%23%23%23 Plugins
connectivity_plus-2.2.1
connectivity_plus_linux-1.3.0
connectivity_plus_macos-1.2.1
connectivity_plus_web-1.2.0
connectivity_plus_windows-1.2.0
device_info_plus-3.2.2
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.2
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
firebase_analytics-9.1.2
firebase_analytics_web-0.4.0 8
firebase_core-1.13.1
firebase_core_web-1.6.1
firebase_crashlytics-2.5.3
flutter_keyboard_visibility-5.2.0
flutter_keyboard_visibility_web-2.0.0
integration_test
native_device_orientation-1.0.0
path_provider-2.0.9
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
share_plus-4.0.3
share_plus_linux-3.0.0
share_plus_macos-3.0.0
share_plus_web-3.0.0
share_plus_windows-3.0.0
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2
text_to_speech-0.2.3
text_to_speech_macos-0.1.1
text_to_speech_web-0.1.2
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.9
url_launcher_windows-3.0.0
video_player-2.3.0
video_player_android-2.3.2
video_player_avfoundation-2.3.1
video_player_web-2.0.7
video_player_web_hls-0.1.11 4
volume_watcher-2.0.1
wakelock-0.6.1 2
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by yjbanov** [comment] 2022-03-31 18:10
This looks exactly like https://github.com/flutter/flutter/issues/97307. I'd deduplicate.

**Comment by christopherfujino** [comment] 2022-03-31 18:40
Thank you for filing this issue! However, I am going to close it as a duplicate of #97307. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2022-03-31 18:40 UTC
Labels: severe: crash, tool, platform-web
