### ISSUE TITLE
[file_selector] Noticeable, five second delay after opening file/directory picker dialog (desktop/Windows)

### ISSUE THREAD

**Issue by V3ntus** [flutter/flutter#129887] opened 2023-07-02 15:08 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Define a button widget that opens a file or directory picker dialog `onPressed`/`onTap`
2. Desktop/Windows dialog opens instantly, pick or cancel.
3. Dialog closes, but async call to library's function hangs for a few seconds.

### Expected results

After dialog closes, the future being awaited should be resolved and execution should continue immediately

### Actual results

Delay and hanging of application

### Code sample

<details><summary>Code sample</summary>

```dart
FilledButton(
  onPressed: () {
    void askForFile() async {
      showDialog(
          barrierDismissible: false,
          context: context,
          builder: (context) {
            return const AlertDialog(
              title: Text("Loading..."),
            );
          });
      final XFile? file = await openFile(acceptedTypeGroups: [
        const XTypeGroup(
          label: 'KMZ',
          extensions: ['kmz'],
        )
      ]);
      if (file != null && context.mounted) {
        context.pop();
        importKMZAction(context, file.path);
        setState(() {
          ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
            content: Text("Imported a KMZ"),
            elevation: 3,
            duration: Duration(seconds: 1),
          ));
        });
      } else {
        context.pop();
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
          content: Text("Cancelled KMZ import"),
          elevation: 3,
          duration: Duration(seconds: 1),
        ));
      }
    }

    askForFile();
  },
  child: const Text("Import KMZ"),
),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/29584664/c4beb522-ecf9-4aee-92d2-9242cd28db6f

</details>

### Logs

<details><summary>Logs</summary>

```console
None relevant
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\Users\clearview\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (8 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.5.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.20348.0

[✓] VS Code (version 1.76.0)
    • VS Code at C:\Users\clearview\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.78 (unsupported)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by V3ntus** [comment] 2023-07-02 17:00
Possibility of being outside Flutter, noticing it within other applications as well. Will test on other devices

**Comment by huycozy** [comment] 2023-07-03 09:04
Hi @V3ntus 
[file_picker](https://pub.dev/packages/file_picker) is a 3rd party plugin. Please open the issue in the dedicated [repository](https://github.com/miguelpruivo/flutter_file_picker/issues) for better support there. Closing, as this isn't an issue with Flutter framework/1st party plugins.

**Comment by V3ntus** [comment] 2023-07-03 11:11
Sorry, meant file_selector. Was in the middle of migrating and got mixed up

**Comment by huycozy** [comment] 2023-07-04 05:03
I re-open the issue for further discussion. 

I checked this with [plugin sample code](https://github.com/flutter/packages/tree/main/packages/file_selector/file_selector/example) but can't notice the delay. Please also try it and observe if you can see the delay on your machine. 

If you can't see the issue, it could be an issue with your implementation code. I would suggest you narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a single `main.dart` file that can be run independently. If the issue's still reproducible, please provide that `main.dart` file so that we can verify the issue properly. Thanks!

**Comment by V3ntus** [comment] 2023-07-04 14:22
With further testing, it seems like an issue with a single machine of mine. Although the issue seen in my app is consistent on this machine, it did not occur on other Windows PC's we've tested on. The same results appear for the sample code. Maybe an edge case that can't be reproducible?

**Comment by huycozy** [comment] 2023-07-05 03:59
It could be a device-specific issue. Can you please provide a recorded video when running [plugin sample code](https://github.com/flutter/packages/tree/main/packages/file_selector/file_selector/example)?

And please also try running the sample in `profile`/`release` mode and observe if the issue still persists or not.

**Comment by V3ntus** [comment] 2023-07-09 14:00
After further testing, the issue cannot be reproduced on the same device, with the example code and my application.

**Comment by huycozy** [comment] 2023-07-10 04:06
Thanks for your response. I will close this issue since it can not be reproducible. When you see the issue again and can reproduce it consistently, please write in the comments and I will reopen this for further investigation.

**Closed by huycozy** 2023-07-10 04:06 UTC
Labels: in triage
