### ISSUE TITLE
NavigationBar elevation has no effect with useMaterial3 flag

### ISSUE THREAD

**Issue by erabti** [flutter/flutter#105433] opened 2022-06-06 08:40 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample.
2. Change elevation property of NavigationBar to any value.

**Expected results:** Different coloring, or shadows.

**Actual results:** No effect whatsoever.

<details>
<summary>Code sample</summary>

[Dartpad Sample](https://dartpad.dev/?id=e9b18a2e25af7468187204780b7ef660)

</details>

Reference for @rydmike mentioning his concern on the original PR with this, it might be related to this issue:
https://github.com/flutter/flutter/pull/83047#issuecomment-846603530

Side Note/Suggestion:
I think having no shadow is intentional as per material 3 spec, but the surfaceTint color should get applied to the underlying Material widget based on set elevation, and it should not be fixed to "3", we should have an additional property called surfaceTintColor as in Card widget, and it should be themable too.

![Screen Shot 2022-06-06 at 10 39 54 AM](https://user-images.githubusercontent.com/18039922/172126767-8a0a23d4-1f2c-49af-8a51-7ab64a9f1eca.png)

**Comment by huycozy** [comment] 2022-06-06 11:45
Hi @erabti, thanks for filing the issue. 
But the elevation works as intended, see: https://m3.material.io/components/navigation-bar/overview. You can see the demo here: https://flutter.github.io/samples/web/material_3_demo

For `surfaceTint`, there was an issue #102627 that is inside #91605, so please follow up on it for further updates.

I'm closing this issue as above explanation.
If you disagree about this, please drop a comment and I will reopen it.

**Closed by huycozy** 2022-06-06 11:45 UTC
Labels: in triage
