### ISSUE TITLE
Support for Standard drawer in Flutter.

### ISSUE THREAD

**Issue by amadeu01** [flutter/flutter#57387] opened 2020-05-16 15:42 UTC
Support permanent drawer

The [Drawer class](https://api.flutter.dev/flutter/material/Drawer-class.html) has a link to material guidelines, where we can find about _permanently visible drawer_

> Permanently visible drawer: When users need to switch destinations frequently (and screen size allows), a permanently visible drawer can be used.

The standard drawer is used a lot on the web part, and since we have a flutter for web, it could be useful for the web, and also for the desktop targets.

## Use case

- Responsive web sites built with flutter
- Responsive desktop apps built with flutter

## Proposal

Add support for the permanent drawer. Or, making the Drawer handle its appearance regarding the size of the screen.

```
drawer: Drawer(
    child: ListView(
      padding: EdgeInsets.zero,
      children: const <Widget>[ ...],
    ),
    permanentFrom: 400, /// Size of the screen where the drawer become permanent instead of colapsed.
  ),
```

**Comment by TaimoorHassan** [comment] 2020-05-17 05:44
https://github.com/flutter/flutter/issues/50276

This looks similar

**Comment by TahaTesser** [comment] 2020-05-18 12:01
Hi @amadeu01 
Looks like what you proposing is what exactly what [this](https://github.com/flutter/flutter/issues/50276) would solve this

In the meantime, you can check out navigation rail with extended view to achieve something effect 
Closing as duplicate of https://github.com/flutter/flutter/issues/50276

**Closed by TahaTesser** 2020-05-18 12:01 UTC
