### ISSUE TITLE
Kernel Panic (and reboot) on Galaxy J3(2017), Android 8.0

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#24607] opened 2018-11-21 12:35 UTC
We got various reports by our customer using the Galaxy J3 (2017) claiming that their devices were showing random reboot while using our app. These reports (more than 10 reports at the moment) have started to appear after having updated our app to use the v0.10.1 (from the 0.9.6) version of Flutter, so there seems to be a connection.

Anyways we bought a J3 (SM J330F) and we tried (and managed) to reproduce the issue!
I've discovered that the reboot is actually caused by a kernel panic and I've managed to take a dump of the unhandled fault. The app id is `com.bendingspoons.live.quiz`, if you look for `live.quiz` inside the log you will find it in the stack traces.

## Steps to Reproduce
Open the app and wait for a bit, it usually crashes after some random time (between 30 seconds and 15 minutes). It doesn't seem to be related to something occurring inside the app, but to something occurring externally while the screen is turned on (but no particular interaction is in act) and the app is in foreground performing regular tasks.

## Logs
see the attached file
[panic.txt.zip](https://github.com/flutter/flutter/files/2604186/panic.txt.zip)

**Comment by sroddy** [comment] 2018-11-23 14:56
@timsneath I've actually discovered that this is not related to any Flutter update:
Looks like a very recent system update for this device is now causing this crash.
I've managed to reproduce it using heavy and even less heavy games that use OpenGL ES. For example the phone was consistently rebooting while performing the initial download/setup phase of the game Hearthstone.
The software update that is causing this is a minor 22,84MB patch (build J330FXXS3BRI2) that applies the September security updates of Oreo 8.0.0. The previous version (J330FXXU3BRG2) is based on Oreo 8.0.0 with June security updates and is perfectly working.
I'm wondering if this issue is Android-specific or Samsung related and/or if it's something that a patch on Skia could fix.

**Comment by dasebasto** [comment] 2019-01-11 10:07
I am having similar issues in my game (which does not use flutter or OpenGL) with this device (Samsung J3 2017).
There is nothing about the error leading to the reboots in logcat in my case (but some logs about a game optimizing service put me on the right track).

How do you collect kernel panic logs by the way?

I have found out that the random restarts are caused by some Samsung bloatware that unfortunately cannot be easily uninstalled by users...

I managed to fix the issue on my test device by running this command in an adb shell:

pm uninstall -k --user 0 com.enhance.gameservice

I did not find a way to report this to Samsung :/

**Comment by cbracken** [comment] 2019-02-04 19:37
@sroddy is this still an issue for you? I suspect there's not a ton we can do without a reliable repro. Are you able to provide crash reports or a stack trace that would help reproduce this?

**Comment by cbracken** [comment] 2019-04-29 18:09
Closing for now. Let us know if you're still experiencing this issue and we'll gladly re-open.

**Closed by cbracken** 2019-04-29 18:09 UTC
Labels: engine, severe: crash, severe: regression, waiting for customer response
