### ISSUE TITLE
Loop after 'flutter build apk --split-per-abi / msg 'Dart snapshot generator failed with exit code -1073741571' 

### ISSUE THREAD

**Issue by zalekbloom** [flutter/flutter#119654] opened 2023-01-31 21:42 UTC
I have an existing Flutter app which works OK – I develop it in VSCode. Recently I decided to add to the app a MarkupText widget.
Debugging the app worked OK, on the device and on the emulator.

 I tried build flutter app using: f**lutter build apk --split-per-abi** and i got an error: 
Dart snapshot generator failed with exit code -1073741571
Dart snapshot generator failed with exit code -1073741571
The message appears twice, then there is a message: 
Running Gradle task 'assembleRelease'...   
And it continue to run.
After 20 minutes I killed the job. Usually to create apk file takes me not more than 3 minutes.
I tried to repeat this procedure after ‘flutter clean’, rebooting PC – but always with the same results. 

flutter doctor –v display:

flutter doctor -v
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
    • Flutter version 3.3.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (3 months ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\hayor\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (4 available)
    • SM G988U (mobile) • R3CN50ERY9D • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version
      10.0.22621.1105]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 109.0.1518.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
PS D:\flutter_projects\spanish_rules>

Meantime I installed the debug version on my device (which is working fine), but how to solve this problem?

**Comment by huycozy** [comment] 2023-02-01 07:49
@zalekbloom Does the issue happen on a new Flutter project? If so, please provide the output of `flutter build apk --split-per-abi -v` so that we may verify it.

**Comment by zalekbloom** [comment] 2023-02-01 17:35
It is an old project I wrote few month ago and I used on the phone and on the Web.  recently  I decided to add to exiting app a MarkupText widget.
Debugging the app worked OK, on the device and on the emulator.
This problem happens when I try to compile project using the command: "flutter build apk --split-per-abi"
When I compile this project for the Web using command: "flutter build web "- I don't see any problems.
Here is this app on the web:
http://cobolmutant.com/Spanish_Rules

I issued commands:
flutter pub cache clean 
flutter pub get

and I got a little different errors:

flutter build apk --split-per-abi

 Building with sound null safety 
Dart snapshot generator failed with exit code -1073741571
Dart snapshot generator failed with exit code -1073741571
FAILURE: Build failed with an exception.
* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159
* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1     
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 21s
Running Gradle task 'assembleRelease'...                           22.2s
Gradle task assembleRelease failed with exit code 1
PS D:\flutter_projects\spanish_rules> 

I looked on the line 1159 of C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle
This is the code which starts on line 1159:
        project.exec {
            logging.captureStandardError LogLevel.ERROR
            executable flutterExecutable.absolutePath
            workingDir sourceDir
            if (localEngine != null) {
                args "--local-engine", localEngine
                args "--local-engine-src-path", localEngineSrcPath
            }
            if (verbose) {
                args "--verbose"
            } else {
                args "--quiet"
            }
            args "assemble"
            args "--no-version-check"
            args "--depfile", "${intermediateDir}/flutter_build.d"
            args "--output", "${intermediateDir}"
            if (performanceMeasurementFile != null) {
                args "--performance-measurement-file=${performanceMeasurementFile}"
            }
            if (!fastStart || buildMode != "debug") {
                args "-dTargetFile=${targetPath}"
            } else {
                args "-dTargetFile=${Paths.get(flutterRoot.absolutePath, "examples", "splash", "lib", "main.dart")}"
            }
            args "-dTargetPlatform=android"
            args "-dBuildMode=${buildMode}"
            if (trackWidgetCreation != null) {
                args "-dTrackWidgetCreation=${trackWidgetCreation}"
            }
            if (splitDebugInfo != null) {
                args "-dSplitDebugInfo=${splitDebugInfo}"
            }
            if (treeShakeIcons == true) {
                args "-dTreeShakeIcons=true"
            }
            if (dartObfuscation == true) {
                args "-dDartObfuscation=true"
            }
            if (dartDefines != null) {
                args "--DartDefines=${dartDefines}"
            }
            if (bundleSkSLPath != null) {
                args "-dBundleSkSLPath=${bundleSkSLPath}"
            }
            if (codeSizeDirectory != null) {
                args "-dCodeSizeDirectory=${codeSizeDirectory}"
            }
            if (extraGenSnapshotOptions != null) {
                args "--ExtraGenSnapshotOptions=${extraGenSnapshotOptions}"
            }
            if (extraFrontEndOptions != null) {
                args "--ExtraFrontEndOptions=${extraFrontEndOptions}"
            }
            args ruleNames
        }

Don't understand which command I need to run with these options:: 
"Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

**Comment by huycozy** [comment] 2023-02-02 03:52
@zalekbloom It's hard to verify the issue with this piece of error log. Please provide the output of `flutter build apk --split-per-abi -v` so that we may verify it. If the log is too long, please save it into a file and attach it here.

Also, if the issue is only happening when adding [markup_text](https://pub.dev/packages/markup_text), I recommend you file a new issue to its repository for better support.

**Comment by zalekbloom** [comment] 2023-02-02 13:59
Thanks!
Here is the output from the command: flutter build apk --split-per-abi -v 
I noticed in the terminal some first entries were not showed, maybe terminal has a limit how many entries to display, I am not aware how to increase the limit. I attached the log created.
 
Thanks for looking into my problem.
[Flutter_comp_log.txt](https://github.com/flutter/flutter/files/10569686/Flutter_comp_log.txt)

zb

**Comment by huycozy** [comment] 2023-02-03 04:37
@zalekbloom Thanks for providing the log. But currently I have not found any clue from it. 

Can you please try:
- Run `flutter build apk -v` (without `--split-per-abi` param) to see if the issue still persists?
- Switch to the latest Flutter master channel and retry?

```
flutter channel master
flutter upgrade
```

**Comment by zalekbloom** [comment] 2023-02-07 01:54
I run 'flutter build apk -v'    - the same results
I tried commands you suggested:
flutter channel master
flutter upgrade

After rebooting PC, ‘flutter clean’, and ‘flutter pub get’ I run ‘flutter build apk --split-per-abi’ and this time I got:

 Building with sound null safety 

/C:/Users/hayor/AppData/Local/Pub/Cache/hosted/pub.dev/markup_text-1.0.1/lib/src/markup_parser.dart:8592:37: Error: Member not found: 'whatsapp'.
      case "whatsapp": return Icons.whatsapp;
                                    ^^^^^^^^
/C:/Users/hayor/AppData/Local/Pub/Cache/hosted/pub.dev/markup_text-1.0.1/lib/src/markup_parser.dart:8593:43: Error: Member not found: 'whatsapp_sharp'.
      case "whatsapp_sharp": return Icons.whatsapp_sharp;
                                          ^^^^^^^^^^^^^^
/C:/Users/hayor/AppData/Local/Pub/Cache/hosted/pub.dev/markup_text-1.0.1/lib/src/markup_parser.dart:8594:45: Error: Member not found: 'whatsapp_rounded'.
      case "whatsapp_rounded": return Icons.whatsapp_rounded;
                                            ^^^^^^^^^^^^^^^^
/C:/Users/hayor/AppData/Local/Pub/Cache/hosted/pub.dev/markup_text-1.0.1/lib/src/markup_parser.dart:8595:46: Error: Member not found: 'whatsapp_outlined'.
      case "whatsapp_outlined": return Icons.whatsapp_outlined;
                                             ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1154

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Running Gradle task 'assembleRelease'...                           11.3s
Gradle task assembleRelease failed with exit code 1
PS D:\flutter_projects\spanish_rules>
-------------------------

I am not using Whatsup in my app, but I have Whatsup installed on my PC.
For me it looks that the problem is with the package markup_text-1.0.1.
I am using this package because it is much easier to display text with properties like bold or colors. Do you know any other package which can replace markup_text package?

Thanks!

zb

**Comment by zalekbloom** [comment] 2023-02-07 02:55
I checked the package markup_text-1.0.1:
https://github.com/poqueque/markup_text/blob/master/lib/src/markup_parser.dart

There is a code:

      case "whatsapp": return Icons.whatsapp;
      case "whatsapp_sharp": return Icons.whatsapp_sharp;
      case "whatsapp_rounded": return Icons.whatsapp_rounded;
      case "whatsapp_outlined": return Icons.whatsapp_outlined;

but Icons does not includes any whatsapp* members.
Few month ago these members existed - who I need to notify to add this memebers back?

Thanks,

zb

**Comment by huycozy** [comment] 2023-02-07 03:22
@zalekbloom Looking at your new logs, it seems the original issue has been gone. For the new issue with whatsapp icon, please see https://github.com/flutter/flutter/issues/111667#issuecomment-1249224509 which refers to Material Icons source for these icons no longer exists.

So please try using another source icon for it and build again to check if the original issue is fixed on the master channel. Thanks!

**Comment by huycozy** [comment] 2023-02-08 05:29
@zalekbloom So, it's a specific project issue I think. Please share the complete output of `flutter build apk --split-per-abi -v`.

**Closed** 2023-03-01 06:10 UTC
Labels: waiting for customer response, in triage
