### ISSUE TITLE
Default app template looks oddly stretched when iOS simulator is rotated

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#6555] opened 2016-10-27 12:19 UTC
## Steps to Reproduce

1. Create a new project with `flutter create`
1. `flutter run` it in the iOS simulator
1. Rotate the screen in the simulator (Hardware>Rotate Left)
 
Result: Screen looks oddly stretched:

![simulator screen shot 27 oct 2016 14 18 51](https://cloud.githubusercontent.com/assets/13644170/19766845/4fc90b20-9c50-11e6-82ec-f2e7022050ec.png)

**Comment by eseidelGoogle** [comment] 2016-10-27 12:55
Duplicate of https://github.com/flutter/flutter/issues/6374

**Closed by eseidelGoogle** 2016-10-27 12:55 UTC
