### ISSUE TITLE
License scrolling looks janky (but doesn't seem to drop frames?)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5623] opened 2016-08-26 20:22 UTC
flutter/flutter@f1d5fd8c0d7bd59e57dbecdf367048f4172718a7

This is on my iPhone 6s.

https://youtu.be/qGOByVh0hJI

FYI @Hixie

**Comment by eseidelGoogle** [comment] 2016-08-26 20:29
https://youtu.be/sF522byCs6k is a video of the iOS Settings license screen scrolling.  I think this may just be our scroll physics being wrong. https://github.com/flutter/flutter/pull/5340

**Comment by LouisCAD** [comment] 2017-09-29 18:43
@eseidelGoogle Flutter Gallery scrolling looks janky too on my Nexus 6P (Android Oreo, same behavior back on Nougat) on a fresh start. Is there a way to measure it? I mean, since it's not using the system rendering, GPU profile rendering doesn't show anything. Flutter needs something similar. Is it available?

**Comment by Hixie** [comment] 2017-12-20 00:15
Can't reproduce on a Pixel2 XL.

**Comment by LouisCAD** [comment] 2017-12-20 09:01
@Hixie Can you reproduce on a cheap, non high-end phone? Testing apps, and more importantly frameworks and libs on non performant devices is always a good idea.

**Comment by Hixie** [comment] 2017-12-21 21:01
@LouisCAD I haven't tried, but yes, the point of my comment was that this will probably require a lower-end phone to reproduce, hence why I left it open and marked it device-specific. :-)

**Comment by LouisCAD** [comment] 2017-12-21 21:14
@Hixie I found an easy reproduction that doesn't even need a lower-end phone (Nexus 6P was 700€, right):

1. Open the Flutter Gallery app
2. From the list, open the "Dialog" screen
3. Click on the "Confirmation" button: this will open a popup with a time picker
4. Rotate quickly repeatedly the clock hand like it was a fidget spinner…
You should notice a few lags every few seconds, probably indicating an issue in the garbage collector, or something else. In my cas, I rotate the clock hand at about 3rpm, and I notice a significant lag about every 2-3 seconds

These repro steps may work on your Pixel 2 XL, other Android devices, and maybe also iOS devices

**Comment by Hixie** [comment] 2017-12-21 21:41
This issue is related to the license screen, please file separate issues for other performance problems.

**Comment by Hixie** [comment] 2017-12-21 21:41
(In particular, the issue you describe sounds like a higher priority than jank on the license screen!)

**Comment by LouisCAD** [comment] 2017-12-21 21:45
@Hixie I'd think the root cause is common, but I'll file another issue as you suggest

**Comment by guidezpl** [comment] 2022-04-13 12:20
Closing as not reproducible. If you disagree, please file an issue at https://github.com/flutter/gallery.

**Closed by guidezpl** 2022-04-13 12:20 UTC
Labels: team, e: device-specific, framework, severe: performance, team: gallery, f: scrolling, passed first triage, P4
