### ISSUE TITLE
[web][feature_request] Scroll when middle mouse scroll key is clicked

### ISSUE THREAD

**Issue by ZiyadF296** [flutter/flutter#81671] opened 2021-05-03 09:20 UTC
## Use case
Activate scroll when the middle mouse scroll key is clicked on the web page.

## Proposal
Switch the cursor icon to the pointer icon. Scroll up or down depending on the position of the cursor from when it was clicked.

![pointer](https://user-images.githubusercontent.com/56755783/116859864-57a44a80-ac09-11eb-9dce-848b994d377a.png)

**Comment by yjbanov** [comment] 2021-05-06 22:09
This is a general Windows scrolling issue, which should be fixable purely on the framework side. So I'm removing the web label. However, if the framework needs some API from the engine, we can add the label back and discuss what API would be needed to implement this.

/cc @goderbauer

**Comment by Leffe108** [comment] 2022-04-03 21:58
This looks like it is a duplicate of https://github.com/flutter/flutter/issues/66537

**Comment by goderbauer** [comment] 2022-04-27 22:15
Duplicate of https://github.com/flutter/flutter/issues/66537.

**Closed by goderbauer** 2022-04-27 22:15 UTC
Labels: severe: new feature, framework, f: scrolling, proposal, passed first triage
