### ISSUE TITLE
 Warning: `aa` on your path resolves to bb, which is not inside your current Flutter SDK checkout at   "xx" Consider adding "yy" to the front of your path.

### ISSUE THREAD

**Issue by dong-lufei** [flutter/flutter#119995] opened 2023-02-04 11:47 UTC
```
$ flutter doctor -v
[!] Flutter (Channel stable, 3.7.1, on Microsoft Windows [版本 10.0.22000.1455], locale zh-CN)
    • Flutter version 3.7.1 on channel stable at D:\scoop_user_apps\apps\flutter\current
    ! Warning: `flutter` on your path resolves to D:\scoop_user_apps\shims\flutter, which is not inside your current Flutter SDK checkout at D:\scoop_user_apps\apps\flutter\current. Consider adding
      D:\scoop_user_apps\apps\flutter\current\bin to the front of your path.
    ! Warning: `dart` on your path resolves to D:\scoop_user_apps\apps\flutter\3.7.1\bin\cache\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at
      D:\scoop_user_apps\apps\flutter\current. Consider adding D:\scoop_user_apps\apps\flutter\current\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (3 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```

**Comment by darshankawar** [comment] 2023-02-06 07:12
Closing as duplicate of https://github.com/flutter/flutter/issues/115651. Please read [this](https://github.com/flutter/flutter/issues/115651#issuecomment-1409619007) comment for your reference.

**Closed by darshankawar** 2023-02-06 07:12 UTC
Labels: in triage
