### ISSUE TITLE
Can't run flutter app with firebase on IOS as it giving error

### ISSUE THREAD

**Issue by Haseeb717** [flutter/flutter#58407] opened 2020-06-01 12:32 UTC
Integrating Firebase in my flutter app. For Android it works fine but for IOS it gives an error

```
Running Xcode build...
Xcode build done.                                           22.9s
Configuring the default Firebase app...
*** First throw call stack:
  (
     0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
     1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
     2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
     3   Runner                              0x00000001063194ea +[FIRApp configure] + 138
     4   Runner                              0x00000001063eb446 -[FLTFirebaseAnalyticsPlugin init] + 214
     5   Runner                              0x00000001063eb27d +[FLTFirebaseAnalyticsPlugin registerWithRegistrar:] + 173
     6   Runner                              0x00000001063144e3 +[GeneratedPluginRegistrant registerWithRegistry:] + 115
     7   Runner                  <…>
```

I added `GoogleService-Info.plist` under Runner by right click on Runner and Add the files using XCode! and its showing inside Runner/Runner folder.

<img width="412" alt="Screenshot 2020-06-01 at 3 23 10 PM" src="https://user-images.githubusercontent.com/13509606/83409202-6a2c6780-a42d-11ea-92eb-fb6ade1bbd2d.png">

<img width="272" alt="Screenshot 2020-06-01 at 3 23 52 PM" src="https://user-images.githubusercontent.com/13509606/83409258-83351880-a42d-11ea-8531-76e7f35e6b7d.png">

But it still not working and crash as app start on emulator.

AppDelegate.swift code is:-

```
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
   override func application(
      _ application: UIApplication,
      didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
      ) -> Bool {
         FirebaseApp.configure()
         GeneratedPluginRegistrant.register(with: self)
         return super.application(application, didFinishLaunchingWithOptions: launchOptions)
   }
}
```

What I am missing due to still getting error?

I added `pod 'Firebase/Analytics' `in bottom of Podfile

**Comment by iapicca** [comment] 2020-06-01 13:06
Hi @Haseeb717 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-01 13:06 UTC

**Comment by Haseeb717** [comment] 2020-06-01 13:09
Ok let me post there. :)
But If you know its solution or have any idea about this issue please tell me :)
