### ISSUE TITLE
Android 5.0 crash

### ISSUE THREAD

**Issue by gooyaweb** [flutter/flutter#83417] opened 2021-05-26 15:18 UTC
I created a simple project with flutter 2.2.0 version, I run it on Android 5.0 and it crashed.
On other versions it runs without crash.
Even on Android 5.1 it doesn't crash.
It has not any packages.

```
`[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.0 at C:\flutter
    • Framework revision b22742018b (12 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\android\adt-bundle-windows-x86_64-20140321\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\android\adt-bundle-windows-x86_64-20140321\sdk
    • Java binary at: D:\android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at D:\android\android-studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\moloop\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 5.0.2 (API 21) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!`
```

**Comment by behzodfaiziev** [comment] 2021-05-27 09:00
Hi @gooyaweb.
This issue might be the same as [Android app fails to launch on API 21](https://github.com/flutter/flutter/issues/73118)
You can try this [#26083](https://github.com/flutter/engine/pull/26083#issuecomment-839976868)

**Comment by TahaTesser** [comment] 2021-05-27 10:14
Hi @gooyaweb 
Closing as duplicate of https://github.com/flutter/flutter/issues/73118
Adding https://github.com/flutter/flutter/issues/73118#issuecomment-822395456 still crashes the app for some reason

**Closed by TahaTesser** 2021-05-27 10:14 UTC
Labels: in triage
