### ISSUE TITLE
type 'List<dynamic> is not subtype of type 'List<widget>

### ISSUE THREAD

**Issue by OsamaAldawoody** [flutter/flutter#41596] opened 2019-09-30 07:25 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment] 2019-09-30 07:40
Hello @OsamaAldawoody !

Thank you for posting.
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-09-30 07:40 UTC
