### ISSUE TITLE
[webview_flutter] Need to monitor the scroll offset of scroll

### ISSUE THREAD

**Issue by OHeroJ** [flutter/flutter#72569] opened 2020-12-18 01:07 UTC
Sometimes we need to monitor the offset of the webview to do some animation. Now `flutter` can get `offsetY` and `offsetX`. If you need to get these values in real time, you need to start a timer. This is bad, it should be native `WebView` tells `flutter` that I have scrolled when scrolling, instead of `flutter` starting the timer.

**Comment by darshankawar** [comment] 2020-12-18 07:47
@OHeroJ 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
thanks.

**Comment by OHeroJ** [comment] 2020-12-21 12:22
```sh
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-CN)
    • Flutter version 1.22.5 at /Users/imac/fvm/versions/stable
    • Framework revision 7891006299 (11 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • I-X (mobile)         • f63ff6875a528942c5afb742e8be9b531fd04f1a • ios • iOS 14.0.1
    • Stan的iPhone (mobile) • 32a5e2f23ff9026fb4ab85a6d5c7a47d2f077fdb • ios • iOS 14.3

• No issues found!

```

**Comment by darshankawar** [comment] 2020-12-21 13:40
@OHeroJ 
Can you elaborate on `Now flutter can get offsetY and offsetX. If you need to get these values in real time, you need to start a timer.` along with your use-case and code sample which shows this issue ? What does `start a timer` mean ?

**Comment by OHeroJ** [comment] 2020-12-26 08:39
```js
window.addEventListener("scroll", function () {
        let scrollTop = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop;
        Flutter.postMessage(JSON.stringify({
          "method": "scrollOffsetYChanged",
          "params": { "y": scrollTop }
        }));
      }, { passive: false });
```

just want listen webview scroll offsetY.

**Comment by tsx1453** [comment] 2021-03-02 04:07
i have the same issues, and i found that android's webview return the real pixel size but iOS's webview return logical pixel size, so you can division the pixelReatio to get the value you want

**Comment by stuartmorgan** [comment] 2021-12-09 16:17
Duplicate of https://github.com/flutter/flutter/issues/31027

**Closed by stuartmorgan** 2021-12-09 16:17 UTC
Labels: plugin, p: first party, p: webview, proposal, passed first triage, P5
