### ISSUE TITLE
Nested InkWells cause extra ink splashing

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#33593] opened 2019-05-30 16:54 UTC
Here's the test case: https://gist.github.com/HansMuller/7c99dda97c62dc5c09faead5d386bb49

I would expect that tapping on the child InkWell would _only_ cause a splash within the child's InkWell.

The parent InkWell appears to be attempting to cancel the ink splash that's triggered by its tapDown handler. Unfortunately the parent's splash still appears.

**Comment by HansMuller** [comment] 2019-05-30 16:55
CC @Hixie

**Comment by Hixie** [comment] 2019-05-30 17:23
Duplicate of https://github.com/flutter/flutter/issues/14417, which has a workaround for now.

**Closed by Hixie** 2019-05-30 17:23 UTC
Labels: f: material design, framework

**Comment by bladeofgod** [comment] 2019-06-03 03:31
i got this problem too;
