### ISSUE TITLE
Flutter is stuck while launching the application on chrome

### ISSUE THREAD

**Issue by HawkarShwany** [flutter/flutter#51271] opened 2020-02-22 19:10 UTC
Hi, I just upgraded the Flutter SDK to support web and added web support to an existing application following the documentation guide. but when I run `flutter run -d chrome` to launch the app it got stuck on `attempting to connect to browser instance..`. it says this is taking unexpectedly long time. This happens on both existing apps on which I added web support and new apps. Is this problem related to the SDK or is it just my CPU is slow? It is `Intel(R) Core(TM) i5-5200U 2.20GHz`. 
Thanks for any help.

**Comment by JaviBonilla** [comment] 2020-02-22 21:14
Are you using Linux? This happened to me too, it seems to be related to issue with Kernels 5.5.x - https://github.com/flutter/flutter/issues/49185

**Comment by jonahwilliams** [comment] 2020-02-23 20:13
Duplicate of https://github.com/flutter/flutter/issues/49103

**Closed by jonahwilliams** 2020-02-23 20:13 UTC
