### ISSUE TITLE
Tree is closed on metrics upload failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#102825] opened 2022-04-29 15:06 UTC
For example https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20analyzer_benchmark/2544/overview

The failure looks different from the one from yesterday though:
```
Successfully uploaded metrics to skia perf
AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/update-task-status
  HTTP Status: 404
  Response body:
Not found: HTTP 404: https://flutter.googlesource.com/mirrors/cocoon/+/refs/heads/master/app_dart/dev/branches.txt?format=text
```

**Comment by keyonghan** [comment] 2022-04-29 16:35
Fix in https://github.com/flutter/cocoon/pull/1807

**Comment by CaseyHillers** [comment] 2022-04-29 16:40
https://github.com/flutter/flutter/issues/100071 for tracking a root cause to fix issues like this (move the upload to pubsub to defer processing)

**Comment by CaseyHillers** [comment] 2022-04-29 17:13
I merged https://github.com/flutter/flutter/pull/102824 to kick the tree with the cocoon fix

**Comment by godofredoc** [comment] 2022-04-29 17:22
Master branch was finally removed from cocoon. Seems like this was the last part where master was being used.

**Closed by godofredoc** 2022-04-29 17:22 UTC
Labels: team: infra, P0
