### ISSUE TITLE
Cloud_firestore: How reject a transaction?

### ISSUE THREAD

**Issue by manuraf** [flutter/flutter#48402] opened 2020-01-08 11:25 UTC
Hi,

I am writing a transaction using cloud_firestore plugin and I want to reject a transaction if a particular field of data does not match a condition

![image](https://user-images.githubusercontent.com/12083207/71974171-16687a00-3211-11ea-8875-71b4363b045b.png)

The problem is that when I throw an Exception I get an **PlatformException(Every document read in a transaction must also be written in that transaction., null)**.

I tried to use Future.error(..) instead throwing an exception, but using that the transaction is done without error.

What is the way to stop a transaction?

**Comment by iapicca** [comment] 2020-01-08 11:33
Hi @manuraf 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it

Please refrain from posting pictures if not necessary.
Thank you

**Closed by iapicca** 2020-01-08 11:33 UTC
Labels: created via support template
