### ISSUE TITLE
[tool_crash] UnknownException

### ISSUE THREAD

**Issue by VladimirCores** [flutter/flutter#102960] opened 2022-05-03 07:31 UTC
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/templates/template_create_test.dart -d chrome
```

## Steps to Reproduce
1. chromedriver --port=4444
2. flutter drive --driver=test_driver/integration_test.dart --target=integration_test/templates/template_create_test.dart -d chrome
3. Crash

![image](https://user-images.githubusercontent.com/442111/166417977-dcf12871-867f-488b-93c8-524b4bc5bed9.png)

## Logs
UnknownException
```
#0      parseJsonWireResponse (package:webdriver/src/handler/json_wire/utils.dart:82:9)
#1      JsonWireSessionHandler.parseInfoResponse (package:webdriver/src/handler/json_wire/session.dart:27:21)
#2      JsonWireSessionHandler.parseCreateResponse (package:webdriver/src/handler/json_wire/session.dart:18:7)
#3      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:100:39)
#4      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#5      createDriver (package:webdriver/async_core.dart:64:19)
<asynchronous suspension>
#6      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:141:19)
<asynchronous suspension>
#7      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:272:28)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<

**Comment by danagbemava-nc** [comment] 2022-05-03 08:08
Closing as duplicate of #97307

**Closed by danagbemava-nc** 2022-05-03 08:08 UTC
Labels: in triage
