### ISSUE TITLE
RTL language support in UserAccountsDrawerHeader

### ISSUE THREAD

**Issue by shadyaziza** [flutter/flutter#15059] opened 2018-03-02 09:57 UTC
Including RTL language (e.g, Arabic) in the `UserAccountsDrawerHeader` , it does not appear the way it is supposed to, see the following code, Arabic in `UserAccountsDrawerHeader` is not properly displayed while it is correctly displayed in the `ListTile`

```
endDrawer: Drawer(
          child: ListView(
            children: <Widget>[
              UserAccountsDrawerHeader(
                accountEmail: Text("عربي",textDirection: TextDirection.rtl),
                accountName:  Text("عربي", textDirection: TextDirection.rtl,),
                currentAccountPicture: CircleAvatar(),
              ),
              new ListTile(title: Text("عربي",textDirection: TextDirection.rtl,),)
            ],
          ),
        ),
```

![rtlsupport](https://user-images.githubusercontent.com/12971971/36893456-c7ca2b70-1e10-11e8-9a36-ec72cec1c8ff.PNG)

**Comment by Hixie** [comment] 2018-03-03 00:57
Dupe of https://github.com/flutter/flutter/issues/10719.

**Closed by Hixie** 2018-03-03 00:57 UTC

**Comment by shadyaziza** [comment] 2018-03-03 06:46
The two issue are not the same, actually the issue you mentioned is solved by now by including `TextDirection.rtl` , while my issue is specific to the `UserAccountsDrawerHeader` as you can see in my code even by including `TextDirection.rtl`, Flutter still display Arabic in the wrong way.

**Comment by Khalid-Nowaf** [comment] 2018-03-06 19:53
@shadyaziza I think it is the same problem internally :)

**Comment by Hixie** [comment] 2018-03-06 23:47
Yeah the underlying issue is the same. We don't quite measure Arabic text correctly. If it turns out that fixing #10719 doesn't fix this bug, we can reopen this one. :-)
