### ISSUE TITLE
Fall in analytics with 1.7.8 release

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#37017] opened 2019-07-26 16:25 UTC
We've noticed a sharp drop in analytics returned by the 1.7.8 release; need to root cause and fix or otherwise explain (i.e., previous analytics were incorrect?).

**Comment by zanderso** [comment] 2019-07-26 17:37
Dupe of https://github.com/flutter/flutter/issues/37019

**Closed by zanderso** 2019-07-26 17:37 UTC
Labels: severe: customer critical, tool
