### ISSUE TITLE
Is there any image button in flutter_quill toolbar in web?

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#111720] opened 2022-09-16 03:37 UTC
Is there any image button in [`flutter_quill`][1] toolbar in web?

When I read the [`flutter_quill`][1] package readme, I see that there is an image button in the [`flutter_quill`][1] toolbar in Android, as shown in the image below:

[![image][2]][2]

However, in the app I run via `web (Chrome)`, there is no image button in the [`flutter_quill`][1] toolbar, as shown in the image below:

[![image][3]][3]

Where is the image button? Is it because of the different versions, or do I need to add the image button myself, or something else.

Appreciate if someone can advise. Thank you in advance!

  [1]: https://pub.dev/packages/flutter_quill
  [2]: https://i.stack.imgur.com/C29LL.png
  [3]: https://i.stack.imgur.com/9Cb7d.png

**Comment by huycozy** [comment] 2022-09-16 09:22
Hi @mycar98765 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. And I also saw your filed issue https://github.com/singerdmx/flutter-quill/issues/952 in the `flutter-quill` repository. Please follow up on it for further updates.

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2022-09-16 09:22 UTC
Labels: in triage
