### ISSUE TITLE
Provide better support for UiAutomator

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#32062] opened 2019-05-03 21:28 UTC
Internal: b/131923608

cc @mehmetf 
cc @jonahwilliams 

Not sure how much is possible here, but it's a little bit difficult to use UiAutomator with Flutter. Of particular difficulty is the fact that there's no way to provide any sort of identifier for finding elements. With Android Framework development, you can use resource IDs, but there's no parallel with Flutter. Using UiAutomator is useful for testing inside Google because it's used by an internal testing framework that I expect most teams inside of Google will want to use.

Is it possible to create virtual resource IDs when turning the Flutter semantic tree into the Android view tree (my understanding of how things work)?

**Comment by dnfield** [comment] 2019-05-05 03:25
There is work ongoing right now to make Espresso work better with Flutter, both inside and outside of google3.  Would that suit your needs?

/cc @adazh @matthew-carroll

**Comment by alanrussian** [comment] 2019-05-05 06:27
Hmm not entirely sure, though would probably guess not. I believe
UiAutomator works by targeting elements using the accessibility layer and
Espresso works by [1] targeting elements in the view layer.

IIRC espresso has more direct access to the actual view hierarchy. I don't
believe the view hierarchy is the same as what's produced by the Flutter
accessibility bridge, which populates sort of a virtual view hierarchy
through the accessibility nodes.

[1] Take my espresso assumptions for a grain of salt since I'm not super
familiar with Espresso.

**Comment by dnfield** [comment] 2019-05-05 14:23
Part of the work for espresso is making sure we can make these things accessible to testing frameworks, including the semantics tree.  I think @goderbauer knows the bug tracking that bit he's out this week.  I'll try to dig it up

**Comment by alanrussian** [comment] 2019-05-05 17:22
Sounds good. Just to be clear, I'm seeing things visible in the testing framework. It's just hard to access specific elements.

BTW, I forgot to mention that I saw this line ([JavaDoc](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#setViewIdResourceName(java.lang.String))) which appears might be used to set the resource ID, but it's always set to an empty string: https://github.com/flutter/engine/blob/7ce2666e54cb137f35b62950b32b8db80d5027e6/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L516

**Comment by adazh** [comment] 2019-05-05 18:10
As Dan described, we are working on making Espresso work with Flutter UI as the way it does with Android UI (analogous to [Espresso-Web](https://developer.android.com/training/testing/espresso/web)).

@alanrussian Mind elaborating more on your testing scenarios?
Like how your test flows would look like; what Flutter UI widgets you are interested in interacting with, and how. A (hypothetical) example test case/scenario would be very helpful. Thanks!

**Comment by alanrussian** [comment] 2019-05-05 18:24
Here's something we're trying to do right now in one of our UiAutomator driven tests:

1) Scroll down on a page to find a `ListTile`. Tap on it.
2) Tap on an icon button in the app bar.
3) Type into a text field (this is broken: #32063 but we have a workaround which doesn't require us to enter text for now).
4) Repeat step 1.
5) Tap on some text.
6) Repeat step 1.
7) Tap on some text.

However, this is just what we need to do right now. Different customers will obviously need to do different things.

**Comment by adazh** [comment] 2019-05-05 19:40
Thanks! Let's chat more then. I'll set up something.

**Comment by samdup123** [comment] 2023-12-21 20:29
@dnfield @adazh I am interested in using UiAutomator to work with my flutter app and am having similar problems to what @alanrussian described 3.5 years ago. `Of particular difficulty is the fact that there's no way to provide any sort of identifier for finding elements.`

I am interested in what came of this discussion? I want to use Appium's UiAutomator to find elements on the screen and tap them. Can you help me?

**Comment by dnfield** [comment] 2023-12-21 20:45
It looks like https://github.com/flutter/engine/pull/48882 should have resolved that, although we may be missing widgets in the framework setting it appropriately....

**Comment by samdup123** [comment] 2023-12-21 20:59
What do you mean by `we may be missing widgets in the framework setting it appropriately` ? Are you referencing a bug ticket?

**Comment by dnfield** [comment] 2023-12-21 21:00
@bartekpacia - what's the status of the semantics identifier work? Is there more framework work left to do?

**Comment by bartekpacia** [comment] 2023-12-22 00:43
The work on semantics identifier is completed and is already available on master channel. It can be used like this:

```dart
Semantics(
  identifier: 'hello-world',
  child: Container(
    width: 100,
    height: 100,
    color: Colors.red,
  ),
)
```


PS#1 I think this issue is a duplicate (or a subset) of #17988.

PS#2 Actually @dnfield I have a question for you: how can I check whether these changes will be available in the next Flutter beta in Januray? Is this info publicly available?

**Comment by dnfield** [comment] 2023-12-22 02:48
> The work on semantics identifier is completed and is already available on master channel. It can be used like this:
> 
> ```dart
> Semantics(
>   identifier: 'hello-world',
>   child: Container(
>     width: 100,
>     height: 100,
>     color: Colors.red,
>   ),
> )
> ```
> 
> PS#1 I think this issue is a duplicate (or a subset) of #17988.

I agree. However, the part I'm still not clear on is whether we need to add some default identifiers to more framework widgets "out of the box". I suspect that we don't but it's not 100% clear to me.

@samdup123 I'm going to close this issue as a duplicate of #17988, and to be honest I think it's either resolved or mostly resolved (but you'll need to add the kind of code that @bartekpacia suggested above in places in your app where you want it to work). 

> PS#2 Actually @dnfield I have a question for you: how can I check whether these changes will be available in the next Flutter beta in Januray? Is this info publicly available?

Which commit is it? The first thing to check is whether that commit is part of 3.18, which is the beta that was cut in December. If not I'm pretty sure it'll be part of 3.19 in January :)

**Closed by dnfield** 2023-12-22 02:48 UTC
Labels: a: tests, platform-android, framework, customer: mulligan (g3), c: proposal, P3, team-android, triaged-android, multiteam-retriage-candidate

**Comment by bartekpacia** [comment] 2023-12-22 23:48
> However, the part I'm still not clear on is whether we need to add some default identifiers to more framework widgets "out of the box".

No, we don't want to do that. It makes sense to make all the built-in widgets in core framework have sensible accessibility, but `Semantics.identifier` is an exception since it's only for UI testing.

It would only interfere with identifiers given by developers.

**Comment by bartekpacia** [comment] 2023-12-22 23:57
> Which commit is it?

Mainly https://github.com/flutter/flutter/commit/948523b80c9cb9659153e13cd60a53a8cc254603 but [all the PRs listed here](https://github.com/flutter/engine/pull/47961) also have to be released for this feature to work.

I see it's not on beta yet. Let's hope for January 🤞🏻 

<img width="352" alt="Screenshot 2023-12-23 at 12 57 07 AM" src="https://github.com/flutter/flutter/assets/40357511/358f3c30-1586-4375-9242-4d983abcbb75">
