### ISSUE TITLE
Poor performance on Xiaomi Mi Mix 2, MIUI 10

### ISSUE THREAD

**Issue by donnysim** [flutter/flutter#22350] opened 2018-09-27 14:07 UTC
I have Xiaomi Mi Mix 2 with MIUI 10 and every flutter app is very laggy and stuter, expecially lists and animations.

For example: https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&hl=en_US

Every app works smooth for about 2 seconds and then starts lagging. Disabling MIUI optimizations through developer tools does not change anything.

When enabling performance overlay and continuously scrolling a list, it drop to 35 frames per second or so.

**Comment by zoechi** [comment] 2018-09-27 16:29
Please add the output of `flutter doctor -v`.

Have you tried with profile or release builds?
The performance characteristic of debug builds is not representative.

**Comment by donnysim** [comment] 2018-09-27 16:34
Yes, we tried release builds, debug builds, other flutter apps on google play - all of them have performance issues on this device. I'll try to get the output tomorrow.

**Comment by zoechi** [comment] 2018-09-27 16:45
Please add the output of `flutter doctor -v`.

**Comment by donnysim** [comment] 2018-09-28 05:32
```
[√] Flutter (Channel master, v0.9.3-pre.3, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.9.3-pre.3 at C:\flutter
    • Framework revision 8b5af14f24 (8 days ago), 2018-09-19 15:42:51 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
```

Note that we updated from flutter 0.8.2 to latest to see if the problem went away.

**Comment by BondarenkoStas** [comment] 2019-10-24 16:07
is the issue still relevant?

**Comment by donnysim** [comment] 2019-10-24 17:04
Can't really tell, I flashed different ROM and it works smoothly so the issue was definitely MIUI. We can close this issue if necessary.

**Comment by lawliet467** [comment] 2019-11-21 10:26
you are not alone.I try my Xiaomi 6, Xiaomi 8, they are all the same situation.and not any solution found so far

**Comment by 1030310877** [comment] 2020-04-02 06:50
same issue, MIX2 Android 9 MIUI 11 and XIAOMI PLAY Android 9. But the phone MIX2S Android 10 MIUI 11, works perfectly.

**Comment by TahaTesser** [comment] 2020-09-04 15:13
Hi @donnysim 
Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by donnysim** [comment] 2020-09-13 12:28
@TahaTesser I don't have MIUI anymore, I rooted the phone and installed a different ROM long time ago and it worked without a hitch so it was definitely the MIUI that caused the problem.

**Comment by TahaTesser** [comment] 2020-09-14 11:29
Hi @donnysim 
Since you no longer have the deice and are  unable to provide more details 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-14 11:29 UTC
Labels: P4, e: device-specific, engine, severe: performance
