### ISSUE TITLE
Transform.scale animation Weird problem

### ISSUE THREAD

**Issue by hetian9288** [flutter/flutter#29440] opened 2019-03-15 17:04 UTC
## Problem Description
The second animation, the text component cannot appear
![ezgif-4-3c5b0e62cc7e](https://user-images.githubusercontent.com/5409513/54448511-e97d3f00-4786-11e9-8bff-94deeb2cd0f9.gif)

### flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.10, on Mac OS X 10.13.6 17G5019, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.32.1)
[✓] Connected device (1 available)

• No issues found!
```

## Sample code
```
class TopicPage extends StatefulWidget {
  final String name;

  TopicPage({Key key, this.name}) : super(key: key);

  @override
  TopicPageState createState() => new TopicPageState();
}

class TopicPageState extends State<TopicPage> with TickerProviderStateMixin {
  AnimationController _container;
  Animation _animation;
  @override
  void initState() {
    super.initState();
    _container = AnimationController(vsync: this, duration: Duration(seconds: 1));
    _animation = Tween(begin: 0.0, end: 1.0).animate(_container)
    ..addListener((){
      setState(() {});
    })
    ..addStatusListener((status){
      if (status == AnimationStatus.completed) {
        _container.reverse(from: 1.0);
      }else if (status == AnimationStatus.dismissed) {
        _container.forward(from: 0.0);
      }
    });
    _container.forward(from: 0.0);
  }


  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.name),
      ),
      body: Center(
        child: Container(
          width: 50,
          height: 50,
          alignment: Alignment.center,
          child: Stack(
            children: <Widget>[
              Container(
                width: 50,
                height: 50,
              ),
              Transform.scale(
                scale: _animation.value,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Image.asset(
                      "assets/images/icon_min_jinbi.png",
                      width: 16,
                      height: 16,
                      fit: BoxFit.contain,
                    ),
                    SizedBox(
                      width: 2,
                    ),
                    Text(
                      "+32",
                      style: TextStyle(color: MyColors.tred, fontWeight: FontWeight.bold, fontSize: 13),
                    )
                  ],
                ),
              ),
              Positioned(
                child: Container(
                  width: 60,
                  height: 60,
                  alignment: Alignment.center,
                  child: Image.asset(
                    "assets/images/my_red.png",
                    width: 40,
                    height: 40,
                    fit: BoxFit.contain,
                  ),
                ),
                top: (1 - _animation.value) * 50,
              ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _container.dispose();
    super.dispose();
  }

}
```

**Comment by dnfield** [comment] 2019-04-06 15:53
Duplicate of #30522 

This was a bug in Skia that has been fixed.  If it's not on master yet it should be very soon.

**Closed by dnfield** 2019-04-06 15:53 UTC
Labels: a: typography, engine
