### ISSUE TITLE
Andriod  - url_launcher Plugin show blank screen on dismiss 

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#61843] opened 2020-07-20 07:34 UTC
getting black screen when opening whats app URL link when going back

url_launcher: ^5.5.0

C:\Tools\flutter\bin\flutter.bat doctor --verbose
    • Flutter version 1.17.5 at C:\Tools\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

to reproduce issue:
1 - url should be whatsapp contact url  **https://wa.me/qr/BFVWE2E7YHIWG1**
2 - press back to navigate to app and you will see black screen see below video.

```dart
Future<void> launchURL(String url) async {
  if (await canLaunch(url)) {
    await launch(url, enableJavaScript: true);
  }
}
```

<img src="https://user-images.githubusercontent.com/47334522/87911697-b92d6b00-ca74-11ea-9f0d-53a78ab80333.gif" width ="300">

**Comment by kw2019ltd** [comment] 2020-07-20 07:36
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/47334522/87911749-cd716800-ca74-11ea-8fe8-6369b3e5901e.gif)

**Comment by darshankawar** [comment] 2020-07-20 10:31
Hi @kw2019ltd,
I tried to replicate the issue on latest Flutter dev channel and with latest version of `url_launcher` plugin but I was unable to replicate and see the black screen.
I used the official plugin example and used the https whatsapp url you shared in your code. Although the link didn't work for me, but I was able to go back to the app properly without any issues. I also tried this url https://flutter.dev/ and didn't see the issue. Attached is the video for your reference.

[61843.mp4.zip](https://github.com/flutter/flutter/files/4947092/61843.mp4.zip)

**Comment by kw2019ltd** [comment] 2020-07-20 13:01
@darshankawar the issue only happened related to what'sup url,  

to reproduce the issue: 
1 - launch the url and add the contact to your contact list and save it - this is the first time
2 - launch it again and you will face the issue.

**Comment by darshankawar** [comment] 2020-07-20 13:32
Hi @kw2019ltd,
When you say launch what'sapp url, what do you mean ? How do I get one url that will work to replicate the issue ?

**Comment by kw2019ltd** [comment] 2020-07-20 14:54
Hi use this url

*https://wa.me/qr/BFVWE2E7YHIWG1 <https://wa.me/qr/BFVWE2E7YHIWG1>*

*Make sure what'sup installed in your phone, *

*Once you launched the url it will promote contact screen save it and go
back*

*Now launch it again and press back you will see black /white screen. *

**Comment by darshankawar** [comment] 2020-07-21 05:40
Hi @kw2019ltd,
I see there's a similar open issue describing your case, [61072](https://github.com/flutter/flutter/issues/61072).
I'd suggest to follow-up there for updates.
I am closing this as duplicate. If you disagree, write in comments and I'll reopen. Thanks.

**Comment by kw2019ltd** [comment] 2020-07-21 06:41
donse close it mine on android , 61843 on WEB.

pls provide a fix

**Comment by darshankawar** [comment] 2020-07-21 09:41
Thanks @kw2019ltd, reopened the issue.

**Comment by darshankawar** [comment] 2020-07-21 09:45
Issue is reproducible on latest Flutter dev channel and with latest version of `url_launcher` plugin.
Per @kw2019ltd, this seem to be happening only when we try to open a whatsapp contact in app browser and while trying to go back to the app, a black screen is shown. Attached is the video for reference. 

Tested on Android 8.1.0 device.


[61843.mp4.zip](https://github.com/flutter/flutter/files/4952605/61843.mp4.zip)

**Comment by kw2019ltd** [comment] 2020-12-09 17:30
any update? @darshankawar

**Comment by maheshmnj** [comment] 2023-01-10 04:47
hI @kw2019ltd, I verified the issue on stable 3.3 and master 3.7 and I am unable to reproduce the issue. I believe that the issue is fixed. Please try the updated code sample as per the latest version of the plugin

```dart
Future<void> _launchUrl() async {
  await launchUrl(_url, mode: LaunchMode.externalApplication);
}
```



https://user-images.githubusercontent.com/31410839/211463734-2d1b4fa4-09cd-46fd-a614-8c214c26e13b.mov




<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

final Uri _url = Uri.parse('https://wa.me/qr/BFVWE2E7YHIWG1');

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Center(
            child: ElevatedButton(
              onPressed: _launchUrl,
              child: Text('Show Flutter homepage'),
            ),
          ),
        ),
      ),
    );

Future<void> _launchUrl() async {
  await launchUrl(_url, mode: LaunchMode.externalApplication);
}

```
</details> 




<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as fixed. In case you disagree, then please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2023-01-10 04:47 UTC
Labels: platform-android, plugin, p: first party, p: url_launcher, has reproducible steps, P4, found in release: 1.20
