### ISSUE TITLE
Engine -> Framework roll failing on tool test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#84458] opened 2021-06-11 18:57 UTC
https://github.com/flutter/flutter/pull/84451

`test/commands.shard/permeable/analyze_once_test.dart` tests are failing.

I'm guessing it's due to the Dart roll here https://github.com/flutter/engine/pull/26703

Which contains analyzer changes here: https://dart.googlesource.com/sdk.git/+log/d622b98e77d7..c8a66f8e7ca1

P0 because this is blocking rolls.

/cc @scheglov @srawlins

**Comment by scheglov** [comment] 2021-06-11 19:12
How do I run these tests, and how to reproduce this failure with newer Dart SDK?

FWIW, I ran `flutter test` in `~/Source/flutter/packages/flutter_tools` after fetching the latest state, `flutter upgrade` and `flutter update-packages`. I see many `TimeoutException` and other failures. So, it seems that this is not what I need to run, but I don't know any better.

**Comment by zanderso** [comment] 2021-06-11 19:25
You probably need to specify the test to run `flutter test test/commands.shard/permeable/analyze_once_test.dart`. About how to test with a newer Dart SDK, maybe @jonahwilliams can give advice.

**Comment by jonahwilliams** [comment] 2021-06-11 19:31
I don't see an easy to patch a local engine usage. You could try checking out the failing roll and running it there.

**Comment by scheglov** [comment] 2021-06-11 19:47
I patched `AnalysisServer` in `packages/flutter_tools/lib/src/dart/analysis.dart` to point at `pkg/analysis_server/bin/server.dart` instead of the snapshot from the included Dart SDK. With this `flutter test test/commands.shard/permeable/analyze_once_test.dart` works without failures. So, either I cannot reproduce it, or there was a change in Dart SDK (`analyzer` or `analysis_server`) that fixed it.

**Comment by zanderso** [comment] 2021-06-11 19:52
@scheglov Maybe you can verify whether your change here fixed it? https://github.com/dart-lang/sdk/commit/4936904e9aae57102a63e5ae7d64c240c632cad4

**Comment by jason-simmons** [comment] 2021-06-11 19:55
I can reproduce this locally by running `flutter test test/commands.shard/permeable/analyze_once_test.dart` with engine build `f3c565a2f750e472b2f7152652576c83ea4edc10`

I attached a capture of the Flutter project generated by that test.  If I run `flutter analyze --no-pub` from that project then I don't see the expected errors when using the most recent engine builds.

[bug_84458.zip](https://github.com/flutter/flutter/files/6640718/bug_84458.zip)

**Comment by scheglov** [comment] 2021-06-11 20:06
I don't know what "with engine build XYZ" means.

I tried to checkout Dart SDK at `64e7cb9` and `4936904`, the test `flutter test test/commands.shard/permeable/analyze_once_test.dart` works for both. 

For the attached project, I have to run `flutter pub get` to update the `package_config.json` file, but then in both branches analysis gives some diagnostics.
```console
scheglov@scheglov-macbookpro2:~/tmp/888/flutter_project$ flutter analyze --no-pub
Analyzing flutter_project...

   info • Avoid empty else statements • lib/main.dart:8:48 • avoid_empty_else
   info • Avoid empty statements • lib/main.dart:8:48 • empty_statements
   info • The declaration '_incrementCounter' isn't referenced • lib/main.dart:30:8 • unused_element
warning • The parameter 'onPressed' is required • lib/main.dart:56:29 • missing_required_param

4 issues found. (ran in 18.5s)
```

I also made sure that `flutter_tools` actually runs `analysis_server` from sources by making it throw an exception.

**Comment by jason-simmons** [comment] 2021-06-11 20:14
I ran it using the Flutter engine binaries built from that engine commit (https://github.com/flutter/engine/commit/f3c565a2f750e472b2f7152652576c83ea4edc10).
The versions of Dart and other packages used in that engine build are declared in https://github.com/flutter/engine/blob/f3c565a2f750e472b2f7152652576c83ea4edc10/DEPS

I'm continuing to investigate, but I'm suspicious that this might be related to package resolution.  The project directory when this fails seems to be missing a `.packages` file, and the test environment is trying to avoid running `pub`.

**Comment by scheglov** [comment] 2021-06-11 20:17
`.packages` are not used anymore, `.dart_tool/package_config.json` are used instead. `Pub` generates both, but the analyzer uses only one.

**Comment by jason-simmons** [comment] 2021-06-11 21:24
Still looking at this, but here are some things that I've noticed so far:

* The test is writing a `.dart_tool/package_config.json` file instead of running `pub` (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart#L83).  This package config needs to be updated (e.g. using language version 2.12)
* One of the test cases is writing an `analysis_options.yaml` file that specifies the `only_throw_errors` linter rule (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart#L246).
When I run `flutter analyze` for that test case the analyzer does not report any of the expected issues.  If I remove the `linter` section then `flutter analyze` does produce warnings for the other issues in the project.

**Comment by zanderso** [comment] 2021-06-11 21:56
The Engine -> Framework roll succeeded after reverting the Dart roll: https://github.com/flutter/flutter/pull/84464

**Comment by jason-simmons** [comment] 2021-06-11 23:21
I was able to reproduce this reliably with this sequence:
* delete `~/.dartServer`
* roll the framework to engine `3984c21bd8b837b232ec767a14eefbde45a67aae`
* run `analyze_once_test`
* roll to engine `f3c565a2f750e472b2f7152652576c83ea4edc10`
* rerun `analyze_once_test`

At this point the contents of `~/.dartServer` appear to be corrupt and the analyzer produces incorrect results.

The test passes if I:
* build engine `f3c565a2f750e472b2f7152652576c83ea4edc10` and patch Dart's `pkg/analyzer/lib/src/dart/analysis/driver.dart` to increment `DATA_VERSION`
* symlink the resulting `host_debug_unopt/dart-sdk` into the framework's `bin/cache/dart-sdk`
* run `analyze_once_test`

So the change above that includes an update to `DATA_VERSION` should fix this (https://github.com/dart-lang/sdk/commit/4936904e9aae57102a63e5ae7d64c240c632cad4)

We should be able to resume the Dart->engine roller starting with `2.14.0-203.0.dev`

**Comment by aam** [comment] 2021-06-11 23:37
Just wanted to confirm that the test failures starts with https://dart.googlesource.com/sdk/+/cf4e55ba64d4ca0c57636e62d48a7149f5a9edaa(which seems to have updated DATA_VERSION).
Using engine with dart at previous commit (bd4a6291e5985423cbeeee4d34222e4136e75936) have the analyze_once_test passing.

**Comment by aam** [comment] 2021-06-14 16:05
The dart roll landed, engine to framework roll succeeded too.

**Closed by aam** 2021-06-14 16:05 UTC
Labels: P0, dependency: dart, engine, team
