### ISSUE TITLE
we also have this issue:  (flutter version v1.12.13-hotfix.9)

### ISSUE THREAD

**Issue by impeiwei** [flutter/flutter#58162] opened 2020-05-28 11:43 UTC
we also have this issue:  (flutter version v1.12.13-hotfix.9)

`Fatal Exception: java.lang.UnsatisfiedLinkError:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kkk.android-J_bUPlymM_2nsrvl5-hMRg==/base.apk"],nativeLibraryDirectories=[/data/app/com.kkk.android-J_bUPlymM_2nsrvl5-hMRg==/lib/arm, /data/app/com.kkk.android-J_bUPlymM_2nsrvl5-hMRg==/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libflutter.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
at java.lang.System.loadLibrary(System.java:1660)
at io.flutter.embedding.engine.loader.FlutterLoader.a(FlutterLoader.java:122)
at io.flutter.embedding.engine.loader.FlutterLoader.a(FlutterLoader.java:93)`

it may claused by android selinux permission, but how fix it? :
`05-23 23:11:28.468 W/omelink.android(30010): type=1400 audit(0.0:3610): avc: denied { read } for name="libflutter.so" dev="sdd60" ino=180057 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_tmp_file:s0 tclass=file permissive=0`

![image](https://user-images.githubusercontent.com/55788007/82778097-e699d600-9e82-11ea-8a6b-0a29209c6a23.png)

_Originally posted by @impeiwei in https://github.com/flutter/flutter/issues/37566#issuecomment-633369727_

**Comment by impeiwei** [comment] 2020-05-28 11:47
https://github.com/flutter/flutter/issues/37566#issuecomment-633402543

users are affected,  any suggestions to solve it ?

**Comment by TahaTesser** [comment] 2020-05-28 13:28
duplicate of https://github.com/flutter/flutter/issues/37566

**Closed by TahaTesser** 2020-05-28 13:28 UTC
