### ISSUE TITLE
flutter_localizations & intl dependencies issue during restoration

### ISSUE THREAD

**Issue by wcoder** [flutter/flutter#132308] opened 2023-08-10 15:26 UTC
I have a problem with flutter_localizations + intl during restoration packages for the same flutter environment on different machines:

`pub get` on dev1 machine:
```sh
> fvm flutter pub get

Resolving dependencies...
Because no versions of flutter_date_pickers match >0.4.2 <0.5.0 and flutter_date_pickers 0.4.2 depends on flutter_localizations from sdk, flutter_date_pickers ^0.4.2 requires flutter_localizations from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.18.1, flutter_date_pickers ^0.4.2 requires intl 0.18.1.
So, because my_test_app depends on both intl 0.18.0 and flutter_date_pickers ^0.4.2, version solving failed.
```

### App pubspec.yml
```yml
environment:
   sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ...
  intl: ^0.18.0
  collection: ^1.17.0
  flutter_date_pickers: ^0.4.2
  ...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
```

### Flutter doctor from dev1
```
> fvm flutter doctor -v

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-arm64, locale en)
    • Flutter version 3.10.5 on channel stable at /Users/dev/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/dev/Library/Developer/android-sdk-macosx
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 14 (mobile)          • CF79B28C-B1D8-4260-B422-6B7D053FCAE9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

## But it works for dev2 

But it works correctly on the second machine with the same app `pubspec.yml` and flutter version:

### Flutter doctor from dev2

```
> fvm flutter doctor -v

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-x64, locale en)
    • Flutter version 3.10.5 on channel stable at /Users/dev2/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dev2/Library/Developer/android-sdk-macosx
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/dev2/Library/Developer/android-sdk-macosx
    • Java binary at: /Users/dev2/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/dev2/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

After some investigation, I see that `pubspec.lock` regenerates for each machine to use `intl 0.18.0 or 0.18.1`.

Attached `fvm flutter pub deps -v` output from both machines:
[dev1_deps.txt](https://github.com/flutter/flutter/files/12313840/dev1_deps.txt)
[dev2_deps.txt](https://github.com/flutter/flutter/files/12313841/dev2_deps.txt)

-- 

Looks similar to #102637 but works depending on pubspec.lock generation.

**Comment by darshankawar** [comment] 2023-08-11 06:56
@wcoder 
Thanks for the report. I added the said dependencies but didn't get the reported error.

```
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter --no-color pub get
Resolving dependencies...
  material_color_utilities 0.5.0 (0.8.0 available)
Got dependencies!
Process finished with exit code 0
```

It also maybe due to the package `flutter_date_pickers` you are using which could be using lesser version of `intl`, as I see a similar issue in that repo to upgrade the dependency version: https://github.com/MariaMelnik/flutter_date_pickers/issues/109

**Comment by wcoder** [comment] 2023-08-14 15:45
@darshankawar 
> I added the said dependencies but didn't get the reported error.

It appears that the issue lies in the restoration of the `pubspec.lock`. You can review the pub dependency logs provided above for further information.

> It also maybe due to the package flutter_date_pickers you are using which could be using lesser version of intl

`flutter_date_pickers` package is using range:
https://github.com/MariaMelnik/flutter_date_pickers/blob/c69f1fb4b4dbebb03ef654515009c9c0fb86aa96/pubspec.yaml#L13
then dart deps resolve decides what to use, as I understand it.

**Comment by darshankawar** [comment] 2023-08-15 06:47
Thanks for the update. I am unable to replicate the reported behavior, but based on the report and findings related to `pubspec.lock`, keeping the issue open for team's attention.

**Comment by Hixie** [comment] 2023-08-15 22:56
@wcoder Looking at the logs it seems like one machine is arm64 and the other x86_64, is that right?

Can you include the two `/Users/.../.pub-cache/log/pub_log.txt` files for the two machines after running this on each one?

This is probably a `pub` issue (maybe the heuristic is sensitive to the architecture?), in which case we would probably recommend filing the issue on <https://github.com/dart-lang/pub/issues/new/choose>.

**Comment by Hixie** [comment] 2023-08-16 22:29
Looking at the diff:
[dev_pub_log.diff.txt](https://github.com/flutter/flutter/files/12363989/dev_pub_log.diff.txt)
...it seems that for some reason pub thinks dev1's flutter_test depends on test_api 0.6.0 while dev2's depends on test_api 0.5.1. There are other differences too.

I see from the `flutter doctor` output above that both checkouts think they're on the same version of Flutter, but it sure seems like maybe something has gone wrong here and one is on a slightly older version. Can you try running `git diff` and `git status` in both developers' `flutter` directories? Is one locally modified in some way?

**Comment by wcoder** [comment] 2023-08-17 18:32
You were absolutely right! Thanks!

The issue was solved by resetting changes in used `~/fvm/versions/3.10.5` the reason for the changes is unknown.

dev1:
```sh
> git status

On branch stable
Your branch and 'origin/stable' have diverged,
and have 31 and 1365 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   dev/automated_tests/pubspec.yaml
        modified:   dev/benchmarks/complex_layout/pubspec.yaml
        modified:   dev/benchmarks/macrobenchmarks/pubspec.yaml
        modified:   dev/benchmarks/microbenchmarks/pubspec.yaml
        modified:   dev/benchmarks/multiple_flutters/module/pubspec.yaml
        modified:   dev/benchmarks/platform_channels_benchmarks/pubspec.yaml
        modified:   dev/benchmarks/platform_views_layout/pubspec.yaml
        modified:   dev/benchmarks/platform_views_layout_hybrid_composition/pubspec.yaml
        modified:   dev/benchmarks/test_apps/stocks/pubspec.yaml
        modified:   dev/bots/pubspec.yaml
        modified:   dev/conductor/core/pubspec.yaml
        modified:   dev/customer_testing/pubspec.yaml
        modified:   dev/devicelab/pubspec.yaml
        modified:   dev/forbidden_from_release_tests/pubspec.yaml
        modified:   dev/integration_tests/abstract_method_smoke_test/pubspec.yaml
        modified:   dev/integration_tests/android_embedding_v2_smoke_test/pubspec.yaml
        modified:   dev/integration_tests/android_semantics_testing/pubspec.yaml
        modified:   dev/integration_tests/android_views/pubspec.yaml
        modified:   dev/integration_tests/channels/pubspec.yaml
        modified:   dev/integration_tests/deferred_components_test/pubspec.yaml
        modified:   dev/integration_tests/external_ui/pubspec.yaml
        modified:   dev/integration_tests/flavors/pubspec.yaml
        modified:   dev/integration_tests/flutter_gallery/pubspec.yaml
        modified:   dev/integration_tests/gradle_deprecated_settings/pubspec.yaml
        modified:   dev/integration_tests/hybrid_android_views/pubspec.yaml
        modified:   dev/integration_tests/ios_add2app_life_cycle/flutterapp/pubspec.yaml
        modified:   dev/integration_tests/ios_app_with_extensions/pubspec.yaml
        modified:   dev/integration_tests/ios_platform_view_tests/pubspec.yaml
        modified:   dev/integration_tests/non_nullable/pubspec.yaml
        modified:   dev/integration_tests/platform_interaction/pubspec.yaml
        modified:   dev/integration_tests/release_smoke_test/pubspec.yaml
        modified:   dev/integration_tests/spell_check/pubspec.yaml
        modified:   dev/integration_tests/ui/pubspec.yaml
        modified:   dev/integration_tests/web/pubspec.yaml
        modified:   dev/integration_tests/web_compile_tests/pubspec.yaml
        modified:   dev/integration_tests/web_e2e_tests/pubspec.yaml
        modified:   dev/integration_tests/wide_gamut_test/pubspec.yaml
        modified:   dev/integration_tests/windows_startup_test/pubspec.yaml
        modified:   dev/manual_tests/pubspec.yaml
        modified:   dev/tools/gen_defaults/pubspec.yaml
        modified:   dev/tools/gen_keycodes/pubspec.yaml
        modified:   dev/tools/pubspec.yaml
        modified:   dev/tools/vitool/pubspec.yaml
        modified:   dev/tracing_tests/pubspec.yaml
        modified:   examples/api/pubspec.yaml
        modified:   examples/flutter_view/pubspec.yaml
        modified:   examples/hello_world/pubspec.yaml
        modified:   examples/image_list/pubspec.yaml
        modified:   examples/layers/pubspec.yaml
        modified:   examples/platform_channel/pubspec.yaml
        modified:   examples/platform_channel_swift/pubspec.yaml
        modified:   examples/platform_view/pubspec.yaml
        modified:   examples/splash/pubspec.yaml
        modified:   packages/flutter/lib/src/widgets/framework.dart
        modified:   packages/flutter/pubspec.yaml
        modified:   packages/flutter/test_private/pubspec.yaml
        modified:   packages/flutter/test_private/test/pubspec.yaml
        modified:   packages/flutter_driver/pubspec.yaml
        modified:   packages/flutter_goldens/pubspec.yaml
        modified:   packages/flutter_goldens_client/pubspec.yaml
        modified:   packages/flutter_localizations/pubspec.yaml
        modified:   packages/flutter_test/pubspec.yaml
        modified:   packages/flutter_tools/pubspec.yaml
        modified:   packages/flutter_web_plugins/pubspec.yaml
        modified:   packages/fuchsia_remote_debug_protocol/pubspec.yaml
        modified:   packages/integration_test/example/pubspec.yaml
        modified:   packages/integration_test/integration_test_macos/pubspec.yaml
        modified:   packages/integration_test/pubspec.yaml
```

dev2:
```sh
> git status

On branch stable
Your branch is behind 'origin/stable' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

**Comment by Hixie** [comment] 2023-08-17 18:54
Oh weird, I wonder if maybe dev1 ran `flutter update-packages --force-upgrade'. That's a command we use during development to roll forward our dependencies but isn't something we expect people to run normally, which would cause all the `pubspec.yaml` files to get updated.

Maybe we should prevent that command from running on master/main/beta/stable ? cc @christopherfujino

**Comment by christopherfujino** [comment] 2023-08-17 20:53
> Oh weird, I wonder if maybe dev1 ran `flutter update-packages --force-upgrade'. That's a command we use during development to roll forward our dependencies but isn't something we expect people to run normally, which would cause all the `pubspec.yaml` files to get updated.
> 
> Maybe we should prevent that command from running on master/main/beta/stable ? cc @christopherfujino

My idea for this was, now that we have a bot running this on a CRON, detect from that command if the user has a terminal attached, and if so put a warning that you probably shouldn't be running this command

**Comment by christopherfujino** [comment] 2023-08-22 20:52
It looks like the root cause of this was developers mistakenly running the maintainer-only sub-command `flutter update-packages --force-upgrade`. I am going to close this issue as resolved, and will track making sure this doesn't happen again in https://github.com/flutter/flutter/issues/132800

**Closed by christopherfujino** 2023-08-22 20:52 UTC
Labels: team-tool
