### ISSUE TITLE
ImageIcon displays a colourful icon as black & white

### ISSUE THREAD

**Issue by kamalbanga** [flutter/flutter#81643] opened 2021-05-02 13:58 UTC
```
ElevatedButton.icon(icon: ImageIcon(AssetImage('assets/images/google.png')), label: Text('Sign in with Google'))
```
shows the color-ful icon as white. I tried setting `color: null`, but that didn't help. 
<img width="170" alt="Screenshot 2021-05-02 at 7 26 42 PM" src="https://user-images.githubusercontent.com/3932617/116815690-54af4880-ab7c-11eb-8290-6a6da85a9f3c.png">

One option is to use `Image.asset` instead of `ImageIcon` but that ridiculously enlarges the button.
<img width="330" alt="Screenshot 2021-05-02 at 7 06 00 PM" src="https://user-images.githubusercontent.com/3932617/116815063-70651f80-ab79-11eb-8589-c06ed030bc33.png">

There's a similar [StackOverflow question](https://stackoverflow.com/questions/49166899/flutter-imageicon-showing-image-white-or-black).

**Comment by kamalbanga** [comment] 2021-05-02 16:30
I just realized, `Image.asset` solution giving large button, could be because of dimensions of the image. I tried another one and it works fine.

**Comment by TahaTesser** [comment] 2021-05-03 10:25
Hi @kamalbanga 
This is not a bug,  ImageIcon paints whatever icon you provided with [ButtonStyle.foregroundColor](https://github.com/flutter/flutter/blob/1d9032c7e1d867f071f2277eb1673e8f9b0274e3/packages/flutter/lib/src/material/elevated_button.dart#L31)

You can test with code sample below

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
theme: ThemeData(
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ButtonStyle(
      foregroundColor: MaterialStateProperty.all(Colors.pink),
    ))
),
      
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: ElevatedButton.icon(icon: ImageIcon(NetworkImage('https://pics.freeicons.io/uploads/icons/png/2659939281579738432-512.png')), label: Text('Sign in with Google'), onPressed: () {  },),
      ),

    );
  }
}

``` 

</details>

You can use `Image.asset` with custom size, it depends on the asset image's size
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-03 10:25 UTC
Labels: in triage
