### ISSUE TITLE
Compiler produces a mess after each code change

### ISSUE THREAD

**Issue by sebastianbuechler** [flutter/flutter#94122] opened 2021-11-23 20:52 UTC
On both my development machines the Flutter compiler seems to get confused after I change even just small pieces of code:
![image](https://user-images.githubusercontent.com/42775578/143113141-c34a1c9c-0130-4f92-8411-f4f0546d1602.png)

Suggestions appear multiple times, variable and function names get completely messed up, error under-lining is totally wrong and in general, it finds dozens of errors where there is none. Often it helps to save the file, close and re-open it. Until the next change is done.

## Steps to Reproduce

1. Open an existing project in VS Code.
2. Make a change to the code.
3. Compiler gets confused

## Logs

<details>
<summary>Logs</summary>

```
```

$ flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19044.1348], locale de-CH)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.dev

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.52

! Doctor found issues in 1 category.

```
```

</details>

**Comment by mamuseferha** [comment] 2021-11-25 09:49
Hi @...  
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-11-25 09:49 UTC
Labels: in triage
