### ISSUE TITLE
Framework coverage is not uploaded anywhere

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#75183] opened 2021-02-02 02:11 UTC
https://github.com/flutter/flutter/pull/45235 removed the `framework_coverage` test, but was closed without merging because
> Closing this PR as I can't find a good way to make presubmits run within 15 minutes.

https://github.com/flutter/flutter/issues/31615 was closed because the shard was deleted in https://github.com/flutter/infra/pull/71.
> We no longer run a coverage shard.

The test code still exists, but it's not being run by any builder.
https://github.com/flutter/flutter/blob/8712f63dd8efd9a41fbbb04a4a99e0d37b46f140/dev/bots/test.dart#L118

Either
1. The test should be run
2. We should delete the test code.

**Comment by jmagman** [comment] 2021-02-02 02:12
@dnfield @jonahwilliams you both had context for this last year.  Should we run or delete the test?

**Comment by dnfield** [comment] 2021-02-02 04:07
I was under the impression that Jonah made coverage fast enough to run in the normal test shard.

I think we can safely delete the code related to it. If we need to add coverage back it wouldn't be in its own shard anymore.

**Comment by jonahwilliams** [comment] 2021-02-02 17:37
The coverage running is definitely fast enough that we don't need a new shard. But we do need to upload that coverage somewhere...

**Comment by dnfield** [comment] 2021-02-02 22:42
Yeah I think I remember now - we needed some way to coordinate the coverage upload across shards.

I still think it's fine to delete this code, since I don't think we really have any intention of running coverage for all framework tests in a single shard. If we really do need to do that it should probably be scheduled at some interval less than per commit (e.g. we do it once a day overnight or something) to avoid tying up resources for too long.

/cc @godofredoc @keyonghan who might have ideas or plans for that.

**Comment by godofredoc** [comment] 2021-02-02 22:49
The codecov service we were using is deprecated. Should we try to find a new service? the final solution will depend on how we are planning to use the coverage. e.g to provide feedback on PRs or to keep a historical database of the repos coverage for tracking.

**Comment by godofredoc** [comment] 2021-02-11 23:24
\cc @pcsosinski is this something we want to collect on prod builders?

**Comment by Hixie** [comment] 2022-01-19 20:47
Duplicate of https://github.com/flutter/flutter/issues/81803

**Closed by Hixie** 2022-01-19 20:47 UTC
Labels: a: tests, team, passed first triage, team: infra, passed secondary triage
