### ISSUE TITLE
Ninja error when compiling engine

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#114440] opened 2022-11-01 18:25 UTC
I'm getting an error when trying to compile the engine on an Apple M1 Pro Mac. 

I ran `gclient sync` and then ran `./flutter/tools/gn --no-goma --ios --simulator --unoptimized --simulator-cpu=arm64 --verbose && ninja -C out/ios_debug_sim_unopt_arm64`. The `gn` part is successful. The `ninja` part gives me some errors:

```
ninja: Entering directory `out/ios_debug_sim_unopt_arm64'
[1/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.date.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.date.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.date.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/date.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.date.o
[2/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.bool.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.bool.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.bool.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/bool.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.bool.o
[3/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.array.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.array.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.array.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/array.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.array.o
[4/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.async.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.async.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.async.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/async.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.async.o
[5/5482] CXX clang_arm64/obj/third_party/dart/runtime/vm/libdart_lib_precompiler.bootstrap.o
FAILED: clang_arm64/obj/third_party/dart/runtime/vm/libdart_lib_precompiler.bootstrap.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/vm/libdart_lib_precompiler.bootstrap.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/vm/bootstrap.cc -o clang_arm64/obj/third_party/dart/runtime/vm/libdart_lib_precompiler.bootstrap.o
[6/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.function.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.function.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.function.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/function.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.function.o
[7/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.stacktrace.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.stacktrace.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.stacktrace.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/stacktrace.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.stacktrace.o
[8/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.double.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.double.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.double.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/double.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.double.o
[9/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.errors.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.errors.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.errors.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/errors.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.errors.o
[10/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.object.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.object.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.object.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/object.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.object.o
[11/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.growable_array.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.growable_array.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.growable_array.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/growable_array.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.growable_array.o
[12/5482] CXX clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.integers.o
FAILED: clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.integers.o
../../buildtools/mac-arm64/clang/bin/clang++ -MD -MF clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.integers.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_ARM64 -DNDEBUG -DDART_TARGET_OS_MACOS -DDART_TARGET_OS_MACOS_IOS -DDART_PRECOMPILER -I../../third_party/dart/runtime -I../.. -Iclang_arm64/gen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -I../../third_party/dart/runtime/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.13.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fno-aligned-allocation -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -fno-strict-vtable-pointers -O3 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c ../../third_party/dart/runtime/lib/integers.cc -o clang_arm64/obj/third_party/dart/runtime/lib/libdart_lib_precompiler.integers.o
ninja: build stopped: subcommand failed.
```

If I run the `ninja` command again, I get different FAILED messages, but they look very similar.

**Comment by jmagman** [comment] 2022-11-01 18:57
Note @vashworth is on https://github.com/flutter/engine/commit/e013908440cde2cc6b0d1b53bc9ae56032346fc0 and has run `gclient sync`

**Comment by stuartmorgan** [comment] 2022-11-01 19:29
Capturing from discussion in a couple of chats:
- I saw the same thing building for host or Android ARM simulator on an ARM macOS machine.
- The underlying error is `Killed: 9` when running one of the failing commands directly, and that's also the message I get when I just try running `buildtools/mac-arm64/clang/bin/clang --version`
- Reverting `17f0103118d4ceafb2c94dadef89c849fb6754d0` (the last `clang_version` roll) fixed by builds.

So the issue is specific to that version of that part of the build tools.

**Comment by christopherfujino** [comment] 2022-11-01 20:02
hmm, @stuartmorgan and @vashworth, do you have gatekeeper on? I wonder if this is an unsigned clang binary.

**Comment by dnfield** [comment] 2022-11-01 21:13
@petrhosek says he's going to file a bug in the toolchain land to look at this. Unfortunately, Fuchsia toolchain doesn't currently have tests covering running their builds on an m1.

**Comment by dnfield** [comment] 2022-11-01 21:14
@christopherfujino - gatekeeper would print a different message, there's just something wrong with this particular build.

**Comment by jonahwilliams** [comment] 2022-11-04 17:45
I'm also hitting this problem. My machine is in minimally protected mode and I've rebooted recently, no dice

**Comment by chinmaygarde** [comment] 2022-11-07 19:27
This may be a combination of the binary and the environment. Multiple folks have tried to reproduce this issue at the same commit with different results.

If someone sees a failure, can they post the engine SHA as well as the shasum of clang++ that they are using to build the engine?

**Comment by zanderso** [comment] 2022-11-14 18:51
The toolchain roll has been reverted, so we should no longer be affected by this. The upstream bug is https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=113913.

**Closed by zanderso** 2022-11-14 18:51 UTC
Labels: engine, P2
