### ISSUE TITLE
io.flutter.view.VsyncWaiter$1.asyncWaitForVsync npe

### ISSUE THREAD

**Issue by qylshy** [flutter/flutter#51847] opened 2020-03-03 14:02 UTC
## Steps to Reproduce

I got a issue ：

java.lang.NullPointerException: Attempt to read from field 'float android.view.DisplayInfo.refreshRate' on a null object reference
	at android.view.Choreographer.getRefreshRate(Choreographer.java:197)
	at android.view.Choreographer.<init>(Choreographer.java:185)
	at android.view.Choreographer.<init>(Choreographer.java:83)
	at android.view.Choreographer$1.initialValue(Choreographer.java:112)
	at android.view.Choreographer$1.initialValue(Choreographer.java:105)
	at java.lang.ThreadLocal$Values.getAfterMiss(ThreadLocal.java:460)
	at java.lang.ThreadLocal.get(ThreadLocal.java:65)
	at android.view.Choreographer.getInstance(Choreographer.java:208)
	at io.flutter.view.VsyncWaiter$1.asyncWaitForVsync(SourceFile:32)
	at io.flutter.embedding.engine.FlutterJNI.asyncWaitForVsync(SourceFile:142)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5400)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

device：vivo X7
android os：	5.1.1

I see another issue is similar: https://github.com/google/ExoPlayer/issues/3144

flutter doctor：

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D76, locale
    zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[!] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2018.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by chinmaygarde** [comment] 2020-06-13 00:26
The fix in the related issue seems to indicate that `getDefaultDisplay` may sometimes return `nullptr` on Android. This seems like something easy to guard against.

**Comment by pedromassangocode** [comment] 2020-12-02 10:34
Hi @qylshy 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample if the issue is still happening?

Thank you

**Comment by pedromassangocode** [comment] 2020-12-23 09:24
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:24 UTC
Labels: P4, easy fix, engine, in triage, platform-android, severe: crash, waiting for customer response
