### ISSUE TITLE
fading_child_animation_perf__timeline_summary 99th_percentile_frame_build_time_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#58413] opened 2020-06-01 15:49 UTC
Looks like it went up at https://github.com/flutter/flutter/pull/58230.

![Screen Shot 2020-06-01 at 8 49 13 AM](https://user-images.githubusercontent.com/1435716/83426938-c919be80-a3e4-11ea-878b-dc3ff8ac77cd.png)

**Comment by zanderso** [comment] 2020-06-01 17:33
@flar Could this be related to https://github.com/flutter/engine/pull/17914?

**Comment by flar** [comment] 2020-06-01 18:00
We saw this in local testing, but went with the fix for several reasons:

- The red you see there is an anomaly in the first place. The benchmark has so much noise that the thresholds were a compromise. Really we need to understand why it varies by more than 2x on a run to run basis and then once we discover that we should rebaseline to match. The existing baselines were chosen to just keep it from being red even though what we really care about is the shorter bars which may have taken a hit as well, but it is hard to tell from this data. We could rebaseline again to just apply a bandaid to keep the graph from going red.

- The slight regression here is offset by a bigger gain in the average and 90% rasterizer times which was the point of the fix.

- The fix was entirely in the C++ code of the engine which shouldn't have affected the build times at all, but since the build occasionally makes native calls there could be side effects.

**Comment by zanderso** [comment] 2020-06-01 18:06
@flar since it sounds like this was intentional after evaluating the trade-offs, I'm going to remove the TODAY label, and drop the priority down, but leave the issue open to investigate the benchmark behavior. Could you rebaseline it to something reasonable in the meantime? Thanks!

**Comment by flar** [comment] 2020-06-01 21:22
@zanderso I rebased shortly after writing that comment and consulting with @liyuqian. The new baselines should be visible on the benchmark dashboard now.

**Comment by flar** [comment] 2020-06-01 21:26
Note these related improvements in the average and 90% frame rasterization times:
<img width="266" alt="Screen Shot 2020-06-01 at 2 25 23 PM" src="https://user-images.githubusercontent.com/50503328/83456032-c6828d80-a413-11ea-97a6-aa8b20b7273b.png">
<img width="266" alt="Screen Shot 2020-06-01 at 2 23 37 PM" src="https://user-images.githubusercontent.com/50503328/83456037-cb474180-a413-11ea-9480-d1486b187c4f.png">

**Comment by liyuqian** [comment] 2020-06-03 17:38
Thanks @flar for the rebaseline! Closing this issue now.

**Closed by liyuqian** 2020-06-03 17:38 UTC
Labels: P3, engine, perf: speed, severe: performance, severe: regression, team: benchmark
