### ISSUE TITLE
[Platform-Web] App crashes with  `Expected a value of type 'FontCollectionNamespace', but got one of type 'Null'`

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#123794] opened 2023-03-30 17:08 UTC
## Steps to Reproduce

1. Create a new web project with IntelliJ with `master` on https://github.com/flutter/flutter/commit/8c5d223bab704623e139bbcd117f70f437fe50a2
2. Run it with Chrome (web)

There is an error:

>Rejecting promise with error: Expected a value of type 'FontCollectionNamespace', but got one of type 'Null'
_js_helper.TypeErrorImpl.new

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel master, 3.9.0-19.0.pre.71, on Microsoft Windows [Version 10.0.19045.2728], locale de-DE) 
    • Flutter version 3.9.0-19.0.pre.71 on channel master at c:\use\flutter                                   
    ! Upstream repository https://github.com/asashour/flutter is not a standard remote.                       
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/asashour/flutter to dismiss this error.
    • Framework revision 8c5d223bab (47 minutes ago), 2023-03-30 09:19:14 -0700                               
    • Engine revision 7d190aa0e1                                                                              
    • Dart version 3.0.0 (build 3.0.0-384.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform
      update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = C:\Users\\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Users\\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\223.8836.41
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[√] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at C:\Users\\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\231.8109.175
    • Flutter plugin version 72.1.5
    • Dart plugin version 231.8109.91

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Users\\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\231.8109.175
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.44

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by AleksandrUkrainets** [comment] 2023-03-31 04:51
I have the same error today.

**Comment by danagbemava-nc** [comment] 2023-03-31 08:33
The issue is reproducible on the `master` but not on `beta` or `stable` only on `web` in `debug` mode. It worked fine for me in `release` and `profile` mode.

### Steps to reproduce
- Run `flutter create foo` and cd into foo
- Run `flutter run -d chrome`


<details>
<summary>flutter doctor -v(master)</summary>

```
[!] Flutter (Channel master, 3.9.0-20.0.pre.54, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.9.0-20.0.pre.54 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bd4c792ba4 (2 hours ago), 2023-03-31 02:37:09 -0400
    • Engine revision a6421ed6bb
    • Dart version 3.0.0 (build 3.0.0-387.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 72.1.5
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 16.4 20E247
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 111.0.5563.146
    ! Error: Nexus is busy: Waiting to connect and unlock the device. Xcode will continue when Nexus is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by Arun789788** [comment] 2023-03-31 09:10
274849945 Issue Tracker Content Removal Request
component:  [Public Trackers > Issue Tracker Support Requests](https://issuetracker.google.com/components/169992)
status:  Infeasible
reporter:  [karun250960@gmail.com](mailto:karun250960@gmail.com)
assignee:  [ju...@google.com](mailto:ju...@google.com)
cc:  [bu...@google.com](mailto:bu...@google.com), [karun250960@gmail.com](mailto:karun250960@gmail.com)
type:  Customer Issue
priority:  P1
severity:  S1
retention:  Component default

**Comment by kevmoo** [comment] 2023-03-31 15:57
Duplicate of https://github.com/flutter/flutter/issues/123737

Should be fixed at latest HEAD

**Closed by kevmoo** 2023-03-31 15:57 UTC
Labels: severe: regression, severe: crash, a: debugging, platform-web, has reproducible steps, found in release: 3.9

**Comment by asashour** [comment] 2023-03-31 22:07
I am afraid it is not fixed in `HEAD` (now https://github.com/flutter/flutter/commit/d5e25f220e89f4600dd69f9ec9d9f8c5d8ca15ba)

**Comment by RomanIvn** [comment] 2023-04-02 09:13
Just updated flutter and unable to debug web apps.  Any way to manually bypass the issue for now? (without downgrading flutter)

`[√] Flutter (Channel main, 3.9.0-20.0.pre.84, on Microsoft Windows [Version 10.0.19044.2728], locale he-IL)
    • Flutter version 3.9.0-20.0.pre.84 on channel main at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cb19c0d66f (80 minutes ago), 2023-04-02 03:52:34 -0400
    • Engine revision fc9c1504f9
    • Dart version 3.0.0 (build 3.0.0-397.0.dev)
    • DevTools version 2.22.2`

**Comment by kevmoo** [comment] 2023-04-02 15:29
I don't think there's a way to work-around. We have a PR pending w/ a fix.

**Comment by kevmoo** [comment] 2023-04-02 15:30
@RomanIvn – try deleting your `flutter/bin/cache/` directory

**Comment by Karthiks915** [comment] 2023-04-03 07:48
Same issue, is there no work around to debug web apps?

**Comment by asashour** [comment] 2023-04-03 09:19
As mentioned in https://github.com/flutter/flutter/issues/123794#issuecomment-1493372787, deleting `flutter/bin/cache/` works with me, till #123915 is merged.
