### ISSUE TITLE
[AssetBundle/Engine] Large bundle loading cause frames missing

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#94464] opened 2021-12-01 13:40 UTC
Large bundle (51M JSON file) loading still causes a couple of frames missing.

## Related issues/PRs
- https://github.com/flutter/engine/pull/22077
- https://github.com/flutter/engine/pull/29016

## Details

- Run the example: https://github.com/AlexV525/large_bundle_load_test.
- Click the FAB.

![195b6eba0e84e303bf89e30db5bd30a](https://user-images.githubusercontent.com/15884415/144244582-eee44204-e1ed-4bf2-aa13-c69c7a35f434.jpg)

**Comment by AlexV525** [comment] 2021-12-01 13:42
cc @zhongwuzw @dnfield

**Comment by AlexV525** [comment] 2021-12-01 15:07
> What's the example?

😢 Sorry, updated in the top comment.

**Comment by zhongwuzw** [comment] 2021-12-01 15:42
Assets are loaded on the UI thread (executes all Dart code for the root isolate). So if assets size is large, IO overhead can not be neglected. Seems we tried to move it to other threads. :)

**Comment by dnfield** [comment] 2021-12-01 15:44
Ahh sure this will definitely be slow. 

Is this a real thing though?  I agree an application can do this but it doesn't seem necessary - there are several other serious reasons to avoid this pattern.

Another question is how much time is spent on copying the data rather than loading it from disk.

**Comment by AlexV525** [comment] 2021-12-01 15:49
> Is this a real thing though? I agree an application can do this but it doesn't seem necessary - there are several other serious reasons to avoid this pattern.

This is the data from some random COVID sites, loading this costs hugely, and yes not only Flutter will be stuck at present.
I could imagine some scenarios when users use Flutter to develop games, which requires assets actively.

> Another question is how much time is spent on copying the data rather than loading it from disk.

Not sure if `File` would help, I'm not familiar with that case.

**Comment by AlexV525** [comment] 2021-12-01 15:51
Maybe we should be happy that this process only makes one frame is missing? 😕

**Comment by dnfield** [comment] 2021-12-01 22:33
If you include a file as an Asset on Android, I do not believe you can use the `File` API to open it. You could, however, use a plugin to open it.

I'm not recommending you do that, and I'm not entirely convinced that the asset IO should be synchronous, but I'm also not really swayed by this example - having a 50mb asset in your APK just seems like a really bad idea, and trying to load it all at once is going to really hurt on low end phones whether it's sync or async - forget even trying to parse the JSON into a usable data structure.

**Comment by maheshmnj** [comment] 2021-12-02 11:16
Hi @AlexV525, Thanks for filing the issue. Provided that loading large files will block the UI thread and will result in frame loss. I believe this is working as intended and it is safe to close the issue.
If anyone disagrees feel free to write in the comments and I will reopen it.

Thank you.

**Comment by dnfield** [comment] 2021-12-02 18:54
I think we can leav ethis open for further discussion.

**Comment by AlexV525** [comment] 2021-12-03 01:47
> trying to load it all at once is going to really hurt on low end phones whether it's sync or async - forget even trying to parse the JSON into a usable data structure.

Forget about the bundle, what's the best choice when loading such huge data? As I mentioned above, in this case, the data is from some COVID site, which includes plenty of statistics info. If any COVID app wants to use it, they'll try to load and parse it. The data might not be loaded every time, then when we are involved with the cache mechanism, we'll back to the start, using a plugin maybe.

**Comment by dnfield** [comment] 2021-12-03 01:55
That would be loaded from the network though right?

After downloading I guess you could chunk it out somehow instead of parsing the whole thing at once.

**Comment by AlexV525** [comment] 2021-12-03 03:28
> That would be loaded from the network though right?

Indeed.

> After downloading I guess you could chunk it out somehow instead of parsing the whole thing at once.

I'm not sure it'll work in most cases since it's a simple JSON?

**Comment by dnfield** [comment] 2021-12-03 03:40
Network IO will always be sync.  

You could manually find offsets of sublists.  Or you could preprocess the json in some server rather than on device

**Comment by jonahwilliams** [comment] 2024-09-08 23:57
Asset loading has since been moved off of the UI thread, see  https://github.com/flutter/engine/pull/40183 and https://github.com/flutter/engine/blob/main/lib/ui/painting/immutable_buffer.cc#L46-L120

**Closed by jonahwilliams** 2024-09-08 23:57 UTC
Labels: engine, perf: speed, P2, team-engine, triaged-engine
