### ISSUE TITLE
The GLContextPresent cost too much time on iOS

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#47940] opened 2019-12-29 10:27 UTC
@liyuqian  Hi，we found that ListView is very easy to drop frames on iOS, even for a very sample demo, like this:
```
import "package:flutter/material.dart";

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: Scaffold(
        body: ListPage(),
      ),
    );
  }
}

class ListPage extends StatelessWidget {

  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) {
        return Container(
          child: Column(
            children: <Widget>[
              Text(index.toString())
            ],
          ),
        );
      },
    );
  }
}
```
The GLContextPresent function cost more than 40 ms sometimes.

<img width="1186"  src="https://user-images.githubusercontent.com/4476512/71555531-6ce2f500-2a68-11ea-909c-88efe3d46ffa.png">

So what could be the reason? It really confused us !

devices: iPhone 5s, iOS 12.4.

flutter doctor -v:
```
[✓] Flutter (Channel unknown, v1.13.5, on Mac OS X 10.14.6 18G103, locale en-CN)
    • Flutter version 1.13.5 at /Users/wangying/Desktop/flutter/flutter
    • Framework revision 41a911099b (10 days ago), 2019-12-19 13:48:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/wangying/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/wangying/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • linxuebin’s iPhone • 480ff3125e7e1420a8fa4087677c5c3d14524678 • ios            • iOS 12.4
    • Chrome     • chrome           • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server       • web-javascript • Flutter Tools
```

**Comment by yuanhuihui** [comment] 2019-12-29 12:50
@liyuqian  hi, yuqian.  If you have time, help us analysis this issues?

cc @zoeyfan

**Comment by VladyslavBondarenko** [comment] 2019-12-30 08:55
Hi @wangying3426 
Please follow up on that [issue](https://github.com/flutter/flutter/issues/47946)
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2019-12-30 08:55 UTC

**Comment by wangying3426** [comment] 2019-12-31 08:36
> Hi @wangying3426
> Please follow up on that [issue](https://github.com/flutter/flutter/issues/47946)
> I'm closing the current one as duplicate.
> If you disagree please write in the comments
> and I will reopen it.
> Thank you

It's seems OK.
All of them belong to thread waiting.
By the way, this problem is more serious, especially on iOS，while #47946 is occurs on both Android and iOS, and less serious.

**Comment by liyuqian** [comment] 2020-01-05 05:01
Thank you @wangying3426 for bringing this to our attention! I did find some performance regressions on our 32-bit iOS tests which use devices similar to the iPhone 5s of this issue (https://flutter-dashboard.appspot.com/benchmarks.html):
- flutter_gallery_ios32__transition_perf worst_frame_rasterizer_time_millis, 90ms to 300ms
- flutter_gallery_ios32__transition_perf 99th_percentile_frame_rasterizer_time_millis, 30ms to 60ms

The regressions started from a seemingly unrelated commit: https://github.com/flutter/flutter/commit/261594e78578db4b37ea03006932f51095fdf229

Unfortunately, as those two benchmarks are archived, we didn't notice those regressions.

@flar : can you please take a look at this while I'm out-of-office?

**Comment by flar** [comment] 2020-01-06 20:20
This commit (https://github.com/flutter/flutter/commit/3c65463f890636ce687bbbaf5bcd19dee930cce6) results for which are still showing in the benchmark history on appspot is also suspicious. Before the commit the worst_frame benchmark was usually around 300ms, and after that commit it is now usually more than 1200ms.

But, that is a newer issue than the previous regression that @liyuqian reported going from 90->300ms. I'll continue to do some regression analysis.

**Comment by flar** [comment] 2020-01-06 23:23
I confirmed the regression in commit (https://github.com/flutter/flutter/commit/261594e78578db4b37ea03006932f51095fdf229). On my iPhone 6s the worst frame went from around 17ms to around 70ms and I tried 3 runs on each to make sure it wasn't a flake. I added a comment to PR https://github.com/flutter/flutter/pull/43677 to get some ideas on what might be the cause.

**Comment by craigomac** [comment] 2020-11-24 09:29
This looks a lot like the graph I'm seeing here: https://github.com/flutter/flutter/issues/24133#issuecomment-732743357. The `GLContextPresent` events seem to be delayed by a second or more! It seems to happen entirely at random in my "game loop", which consists of regular rebuilds. I'm using an OpenGL version of Flutter because of the jank problems Metal builds currently have.

Did you ever find a solution?
