### ISSUE TITLE
Image colors are now much darker on iOS (simulators and devices)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8630] opened 2017-03-07 23:28 UTC
This seems to be a recent change?

Android from 2/8:
![flutter_04](https://cloud.githubusercontent.com/assets/11857803/23682861/aeb0fe20-034a-11e7-9284-c8998e3d8c65.png)

iOS Simulator from 3/8:
![flutter_08](https://cloud.githubusercontent.com/assets/11857803/23682876/b8734530-034a-11e7-9b6a-e769a8e11f21.png)

**Comment by eseidelGoogle** [comment] 2017-03-07 23:29
Presumably https://github.com/flutter/flutter/issues/8152 is related?

**Comment by eseidelGoogle** [comment] 2017-03-07 23:37
Android (Nexus 5X) from 3/8:
![flutter_09](https://cloud.githubusercontent.com/assets/11857803/23683081/f2a0de2e-034b-11e7-888e-2bf826618fb6.png)

**Comment by chinmaygarde** [comment] 2017-03-13 19:53
cc @mattsarett. One of the issues we talked about. This one only has the 565 to 8888 changes. I'll gather more information about what is causing this. But we should definitely address this before the color correctness stuff is enabled.

**Comment by mattsarett** [comment] 2017-03-14 17:22
cc @brianosman

**Comment by brianosman** [comment] 2017-03-14 20:27
Do I need to do anything special to get this to happen? I just got latest, and tried the gallery on simulator (5s), and the colors look fine. (I also tested with a locally built copy of engine).

**Comment by chinmaygarde** [comment] 2017-03-14 20:41
We were trying to understand the difference between before and after the 565 to 8888 changes were made. I was able to reproduce the difference on the simulator (using an iPhone 6S simulator if that matters). I am not sure if there is a way in Skia to make the image use a 565 texture. But that was essentially what was happening earlier. If not, assuming https://github.com/flutter/engine/pull/3434 cleanly reverts, I was going to do a before-after comparison.

To be clear, I am still not sure the new stuff looks "wrong" (@eseidelGoogle, does it?) . But I just to be able to explain the difference.

**Comment by brianosman** [comment] 2017-03-14 20:46
Okay. I tried my simulator in a couple modes, and in all cases (currently 6s), the results on screen look almost identical to the Android screenshots from this thread. It never looks as dark as the simulator screen shot that was posted. I wouldn't expect any significant difference between 565 and 8888 (beyond precision loss in 565, but no absolute shift in color or luminance). Curious about the results of your before-after test.

**Comment by mattsarett** [comment] 2017-03-15 18:07
FWIW, I also cannot reproduce the difference reported here at ToT.

**Comment by chinmaygarde** [comment] 2017-03-15 18:43
Sorry folks. I checked out ToT and did not see the issue either. After questioning my sanity, I realized that we recently switched away from the OpenGL backend on the simulators to the software backend. The issue manifests itself clearly when using the OpenGL backend.

![screen shot 2017-03-15 at 11 39 53 am](https://cloud.githubusercontent.com/assets/44085/23965190/6ee0b4b8-0974-11e7-9456-265266fc6c91.png)
![screen shot 2017-03-15 at 11 38 54 am](https://cloud.githubusercontent.com/assets/44085/23965191/6ee09320-0974-11e7-9098-e6264eb9b630.png)

A patch you can apply locally to force the OpenGL backend on the simulators is [here](https://gist.github.com/chinmaygarde/1a357bc62e820b4974f831d9db0e14fc).

**Comment by chinmaygarde** [comment] 2017-03-15 19:55
Also, to be clear, this darkening happens on the devices too (where we only use OpenGL). Its just a whole lot easier to reproduce on the simulator.

Maybe I should keep the flag to switch backend of the simulator around for easier testing.

**Comment by brianosman** [comment] 2017-03-15 19:59
Okay. I was just trying to get things running on a device to verify that -
good to know...

**Comment by chinmaygarde** [comment] 2017-03-15 21:31
Fixed by https://github.com/flutter/engine/pull/3480

**Closed by chinmaygarde** 2017-03-15 21:31 UTC
Labels: dependency: skia, regression, ⌺‬ platform-ios
