### ISSUE TITLE
Infra flake on reset XCode/ Tool Integration shard

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69317] opened 2020-10-29 17:39 UTC
Happened once on https://ci.chromium.org/p/flutter/builders/prod/Mac%20SDK%20Drone/5288?

**Comment by keyonghan** [comment] 2020-10-29 18:09
This is a duplicate of https://github.com/flutter/flutter/issues/68322.

**Closed by keyonghan** 2020-10-29 18:09 UTC
Labels: P4, team: infra
