### ISSUE TITLE
Application headerbar is missing or gets disappeared 

### ISSUE THREAD

**Issue by 177shivam** [flutter/flutter#76377] opened 2021-02-19 11:29 UTC
## Issue
The flutter desktop application header bar get disappeared as soon as window get launched. The only close, minimize, maximize button can be seen but close button did not respond.

On clicking the close button  log says

> GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

**NOTE:**
On making application in full-screen close button works but still header bar is not visible.

## Flutter doctor -v
```
[✓] Flutter (Channel master, 1.27.0-5.0.pre.18, on Linux, locale en_IN)
    • Flutter version 1.27.0-5.0.pre.18 at /home/desktop/flut/flutter
    • Framework revision 50897c98fc (2 days ago), 2021-02-16 20:13:53 -0800
    • Engine revision 9bcb3bfb0e
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/lib/android-sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.47.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 83.0.4103.116

```
## Tested on
Ubuntu 16.04 LTS
Kernel 4.4.0-197-generic

**Comment by 177shivam** [comment] 2021-02-19 13:23
Hi @TahaTesser 
That application is built on Ubuntu 18.04 LTS and the build bundle was being tested on Ubuntu 16.04. The issue of headerbar getting disappeared comes when flutter is being executed  before that gtk code is working fine, i.e.,
```
#include "my_application.h"

#include <flutter_linux/flutter_linux.h>

#include "flutter/generated_plugin_registrant.h"

struct _MyApplication {
  GtkApplication parent_instance;
};

G_DEFINE_TYPE(MyApplication, my_application, GTK_TYPE_APPLICATION)

// Implements GApplication::activate.
static void my_application_activate(GApplication* application) {
  GtkWindow* window =
      GTK_WINDOW(gtk_application_window_new(GTK_APPLICATION(application)));
  GtkHeaderBar *header_bar = GTK_HEADER_BAR(gtk_header_bar_new());
  gtk_widget_show(GTK_WIDGET(header_bar));
  gtk_header_bar_set_title(header_bar, "Test");
  gtk_header_bar_set_show_close_button(header_bar, TRUE);
  gtk_window_set_titlebar(window, GTK_WIDGET(header_bar));
  gtk_window_set_default_size(window, 800, 600);

  gtk_window_set_default_icon_from_file("test.png",nullptr);
  gtk_window_set_icon_from_file(window,"../test.png",nullptr);
  gtk_widget_show(GTK_WIDGET(window));
  

//////////////////// **Till here headbar is visible after this the headbar gets disappeared**      ////////////////

  g_autoptr(FlDartProject) project = fl_dart_project_new();

  FlView* view = fl_view_new(project);
  gtk_widget_show(GTK_WIDGET(view));
  gtk_container_add(GTK_CONTAINER(window), GTK_WIDGET(view));

  fl_register_plugins(FL_PLUGIN_REGISTRY(view));

  gtk_widget_grab_focus(GTK_WIDGET(view));
}

static void my_application_class_init(MyApplicationClass* klass) {
  G_APPLICATION_CLASS(klass)->activate = my_application_activate;
}

static void my_application_init(MyApplication* self) {}

MyApplication* my_application_new() {
  return MY_APPLICATION(g_object_new(my_application_get_type(), nullptr));
}

```

Since it is build on Ubuntu 18.04 LTS and its bundled is run on Ubuntu 16.04, so I guess that will become a limitation of flutter.

With old 1.20.* flutter version it was working fine.

**Comment by TahaTesser** [comment] 2021-02-23 09:36
Hi @177shivam 
It doesn't matter where it's built, the issue is on 16.04, which is not supported for development or as a target

**Comment by 177shivam** [comment] 2021-02-23 12:35
@TahaTesser 
Actually, it is solved now the issue was the gtk part of  my_application.c file was compatible with old flutter version which I was using before the upgrade, and after upgrading flutter it was not handling new changes of the engine so making the changes in my_aplication.c file solved the issue.

new my_application.c file

```
#include "my_application.h"

#include <flutter_linux/flutter_linux.h>
#ifdef GDK_WINDOWING_X11
#include <gdk/gdkx.h>
#endif

#include "flutter/generated_plugin_registrant.h"

struct _MyApplication {
  GtkApplication parent_instance;
  char** dart_entrypoint_arguments;
};


G_DEFINE_TYPE(MyApplication, my_application, GTK_TYPE_APPLICATION)

// Implements GApplication::activate.
static void my_application_activate(GApplication* application) {
  MyApplication* self = MY_APPLICATION(application);
  GtkWindow* window =
      GTK_WINDOW(gtk_application_window_new(GTK_APPLICATION(application)));

  // Use a header bar when running in GNOME as this is the common style used
  // by applications and is the setup most users will be using (e.g. Ubuntu
  // desktop).
  // If running on X and not using GNOME then just use a traditional title bar
  // in case the window manager does more exotic layout, e.g. tiling.
  // If running on Wayland assume the header bar will work (may need changing
  // if future cases occur).
  gboolean use_header_bar = TRUE;
#ifdef GDK_WINDOWING_X11
  GdkScreen *screen = gtk_window_get_screen(window);
  if (GDK_IS_X11_SCREEN(screen)) {
     const gchar* wm_name = gdk_x11_screen_get_window_manager_name(screen);
    if (g_strcmp0(wm_name, "GNOME Shell") != 0 ) {
      use_header_bar = FALSE;
    }
  }
#endif
  if (use_header_bar) {
    GtkHeaderBar *header_bar = GTK_HEADER_BAR(gtk_header_bar_new());
    gtk_widget_show(GTK_WIDGET(header_bar));
    gtk_header_bar_set_title(header_bar, "test");
    gtk_header_bar_set_show_close_button(header_bar, TRUE);
    gtk_window_set_titlebar(window, GTK_WIDGET(header_bar));
    gtk_window_set_default_size(window, 800, 600);
    gtk_window_set_default_icon_from_file("test.png",nullptr);
  }
  else {
    gtk_window_set_title(window, "test");
    gtk_window_set_default_size(window, 800, 600);
  }

  
  gtk_widget_show(GTK_WIDGET(window));

  g_autoptr(FlDartProject) project = fl_dart_project_new();
  fl_dart_project_set_dart_entrypoint_arguments(project, self->dart_entrypoint_arguments);

  FlView* view = fl_view_new(project);
  gtk_widget_show(GTK_WIDGET(view));
  gtk_container_add(GTK_CONTAINER(window), GTK_WIDGET(view));

  fl_register_plugins(FL_PLUGIN_REGISTRY(view));

  gtk_widget_grab_focus(GTK_WIDGET(view));
}

// Implements GApplication::local_command_line.
static gboolean my_application_local_command_line(GApplication* application, gchar ***arguments, int *exit_status) {
  MyApplication* self = MY_APPLICATION(application);
  // Strip out the first argument as it is the binary name.
  self->dart_entrypoint_arguments = g_strdupv(*arguments + 1);

  g_autoptr(GError) error = nullptr;
  if (!g_application_register(application, nullptr, &error)) {
     g_warning("Failed to register: %s", error->message);
     *exit_status = 1;
     return TRUE;
  }

  g_application_activate(application);
  *exit_status = 0;

  return TRUE;
}

// Implements GObject::dispose.
static void my_application_dispose(GObject *object) {
  MyApplication* self = MY_APPLICATION(object);
  g_clear_pointer(&self->dart_entrypoint_arguments, g_strfreev);
  G_OBJECT_CLASS(my_application_parent_class)->dispose(object);
}

static void my_application_class_init(MyApplicationClass* klass) {
  G_APPLICATION_CLASS(klass)->activate = my_application_activate;
  G_APPLICATION_CLASS(klass)->local_command_line = my_application_local_command_line;
  G_OBJECT_CLASS(klass)->dispose = my_application_dispose;
}

static void my_application_init(MyApplication* self) {}

MyApplication* my_application_new() {
  return MY_APPLICATION(g_object_new(my_application_get_type(),
                                     "application-id", APPLICATION_ID,
                                     "flags", G_APPLICATION_NON_UNIQUE,
                                     nullptr));
  // return MY_APPLICATION(g_object_new(my_application_get_type(), nullptr));
}
```

**Comment by 177shivam** [comment] 2021-03-03 06:47
@TahaTesser 
The same issue is being observed in Ubuntu 18
VERSION="18.04.3 LTS (Bionic Beaver)"
Kernel version= 5.4.0-62-generic

**Comment by TahaTesser** [comment] 2021-03-03 09:15
Hi @177shivam 
Thanks, I will reproduce it soon on Ubuntu 18.04

**Comment by 177shivam** [comment] 2021-03-03 09:30
And 

> Hi @177shivam
> Thanks, I will reproduce it soon on Ubuntu 18.04

The interesting part is the issue is not reproducible on kernel 5.4.0-42-generic

**Comment by 177shivam** [comment] 2021-03-13 05:29
@TahaTesser 
I request you to open this bug.

**Comment by TahaTesser** [comment] 2021-03-23 10:17
Hi @177shivam 
This seems to be related to https://github.com/flutter/flutter/issues/75948, which has a similar kernel 
Please follow up on that issue, I'm closing the current one as a duplicate.
Thank you

**Closed by TahaTesser** 2021-03-23 10:17 UTC
