### ISSUE TITLE
Gestures should not pass through disabled controls

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10593] opened 2017-06-09 14:01 UTC
I’m using showModalBottomSheet to show a list of RadioListTiles as options. I still want to show unavailable options — so they show up as disabled (onchanged = null). However, when you tap those disabled options it seems like the tap passes through and dismisses the sheet. It seems unexpected.

As a workaround, @Hixie suggested wrapping the RadioListTile in an AbsorbPointer. I also wrapped that in a GestureDetector with an empty onTap. The below works for me.

```dart
  final tile = new GestureDetector(
    onTap: () {},
    child: new AbsorbPointer(
      absorbing: !merchandiseItemSize.isAvailable,
      child: new RadioListTile<String>(
        title: new Text(
          "$sizeTitle ($priceString)",
        ),
        value: sizeTitle,
        groupValue: _sizeValue,
        onChanged: merchandiseItemSize.isAvailable ? _updateSelectedSize : null,
      ),
    ),
  );
```

**Comment by Hixie** [comment] 2017-06-09 16:42
Forget the AbsorbPointer, I was barking up the wrong tree with that one. But wrapping the whole part of the sheet that you want to have not dismiss the sheet with a `new GestureDetector(onTap: () { }, ...)` should solve it.

**Comment by Hixie** [comment] 2017-06-09 16:51
The question is whether we want that behaviour by default for Radio, RadioListTile, or anything else, or if it's specifically a question for sheets, or if we should just document it somewhere...

**Comment by iapicca** [comment] 2019-11-01 13:05
Hi @alardizabal  is this issue still meant to be open?

**Comment by iapicca** [comment] 2020-03-25 14:04
Hi @alardizabal 
I tried to replicate the issue you described on [dartpad](https://dartpad.dev/fdf2fd2676add3b1c1bb78881a365759)
and doesn't seem to occur anymore

May I close this issue?
Thank you

**Comment by iapicca** [comment] 2020-07-08 12:33
I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

**Comment by Hixie** [comment] 2020-07-14 23:34
Given how long we have had this behaviour, maybe we should call it intentional and close this bug...

**Comment by HansMuller** [comment] 2020-07-15 01:32
I'm gong to close this issue because it no longer seems to be reproducible, https://github.com/flutter/flutter/issues/10593#issuecomment-655490988, and because - if it were reproducible - it's unlikely to be a welcome change anymore, https://github.com/flutter/flutter/issues/10593#issuecomment-658463583.

**Closed by HansMuller** 2020-07-15 01:32 UTC
Labels: f: gestures, framework, will need additional triage
