### ISSUE TITLE
google_sign_in: signInSilently does not send error to dart and I am not able to catch error

### ISSUE THREAD

**Issue by GiacomoK** [flutter/flutter#28534] opened 2019-02-26 22:24 UTC
Hi,  
when `signInSilently` function throws an error it does not send error to dart, and I am not able to catch error in flutter.

This is the code that throws the error:

    @override
      dynamic decodeEnvelope(ByteData envelope) {
        // First byte is zero in success case, and non-zero otherwise.
        if (envelope.lengthInBytes == 0)
          throw const FormatException('Expected envelope, got nothing');
        final ReadBuffer buffer = ReadBuffer(envelope);
        if (buffer.getUint8() == 0)
          return messageCodec.readValue(buffer);
        final dynamic errorCode = messageCodec.readValue(buffer);
        final dynamic errorMessage = messageCodec.readValue(buffer);
        final dynamic errorDetails = messageCodec.readValue(buffer);
        if (errorCode is String && (errorMessage == null || errorMessage is String) && !buffer.hasRemaining)
          throw PlatformException(code: errorCode, message: errorMessage, details: errorDetails); // <------ HERE IS THE ERROR
        else
          throw const FormatException('Invalid envelope');
      }

As you can see in this stackoverflow post:

https://stackoverflow.com/questions/54893560/catch-statement-does-not-catch-thrown-error-in-debug-mode-in-an-async-function/54894358#54894358

**Comment by zoechi** [comment] 2019-02-27 07:04
Possible duplicate of #28430

**Comment by cyanglaz** [comment] 2019-03-27 16:36
Thank you for opening the issue. Could you try `signInSilently(bool suppressErrors:false)` to catch the error?

**Closed** 2019-05-14 01:24 UTC
Labels: p: first party, p: google_sign_in, plugin, severe: crash, waiting for customer response
