### ISSUE TITLE
flutter has exited unexpectedly

### ISSUE THREAD

**Issue by HYAdonisCoding** [flutter/flutter#35111] opened 2019-06-26 09:02 UTC
## Steps to Reproduce

1. run flutter attach -d 5a8c6e9e0a8c28bb1b21f7ad93a14533b2a0a6f1
2. Checking for advertised Dart observatories...
3. Oops; flutter has exited unexpectedly.Sending crash report to Google.

## Logs

```
[  +42 ms] executing: [/Users/adonis/Developer/flutter/] git log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [/Users/adonis/Developer/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +20 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.5.4-hotfix.2-0-g7a4c33425
[  +24 ms] executing: [/Users/adonis/Developer/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [/Users/adonis/Developer/flutter/] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +82 ms] executing: [/Users/adonis/Developer/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +508 ms] executing: /Users/adonis/Library/Android/sdk/platform-tools/adb devices -l
[  +38 ms] Exit code 0 from: /Users/adonis/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           192.168.56.101:5555    device product:vbox86p model:Google_Pixel_3_XL device:vbox86p
[  +21 ms] executing: idevice_id -h
[ +312 ms] executing: which ideviceinstaller
[   +7 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[   +5 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[   +6 ms] /usr/bin/xcrun simctl list --json devices
[ +262 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on
all
                    devices.
[   +8 ms] /Users/adonis/Library/Android/sdk/platform-tools/adb -s 192.168.56.101:5555 shell getprop
[  +47 ms] ro.hardware = vbox86
[   +1 ms] ro.build.characteristics = nosdcard
[   +6 ms] Google Pixel 3 XL • 192.168.56.101:5555                      • android-x86 • Android 9 (API 28)
[   +2 ms] Adam 的 iPhone7    • 5a8c6e9e0a8c28bb1b21f7ad93a14533b2a0a6f1 • ios         • iOS 11.3
[   +1 ms] iPhone Xʀ         • C026FE00-6E8E-4CC8-8A8C-A398411C9878     • ios         •
com.apple.CoreSimulator.SimRuntime.iOS-12-2
           (simulator)
[   +2 ms] iPhone Xʀ         • 29029CF4-5935-4410-9265-AC964CA79B71     • ios         •
com.apple.CoreSimulator.SimRuntime.iOS-12-1
           (simulator)
[  +21 ms] "flutter run" took 1,258ms.
[        ] "flutter run" took 1,258ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:257:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:538:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#34     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

```
Analyzing flutter_library...
No issues found! (ran in 3.3s)
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/adonis/Developer/flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/adonis/Library/Android/sdk
    • Android NDK at /Users/adonis/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
```

**Comment by christopherfujino** [comment] 2019-06-26 20:21
Possible duplicate of #35102, can you try:

```
brew uninstall --ignore-dependencies usbmuxd libimobiledevice ideviceinstaller
brew tap flutter/flutter https://flutter-mirrors.googlesource.com/homebrew-flutter
brew install --HEAD usbmuxd-flutter libimobiledevice-flutter ideviceinstaller-flutter
```

**Closed** 2019-07-15 23:03 UTC
Labels: tool

**Comment by christopherfujino** [comment] 2019-07-15 23:05
This has been fixed upstream. To fix a broken usbmuxd homebrew install, issue: `brew upgrade --fetch-HEAD usbmuxd`
