### ISSUE TITLE
~40% regression in complex_layout_scroll_perf__memory

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#36079] opened 2019-07-12 17:39 UTC
https://github.com/flutter/flutter/pull/35952 caused a regression in the complex_layout_scroll_perf__memory diff-median benchmark.

![cNsWBbkYmiy](https://user-images.githubusercontent.com/15253456/61147487-4a94f500-a491-11e9-843b-0e966e3d1760.png)

**Comment by tvolkert** [comment] 2019-07-12 17:44
This commit caused a similar regression in the "flutter_gallery__image_cache_memory diff-median" and the "flutter_gallery__image_cache_memory diff-min" benchmarks

**Comment by jason-simmons** [comment] 2019-07-12 23:06
In the devicelab logs complex_layout_scroll_perf__memory shows a consistent pattern after the regression started.  The "Native Heap" metric from Android's `dumpsys meminfo` increases by about 3MB during each run of the scroll test.
Prior to the regression, that value would only increase by a couple hundred KB.

However, I've been unable to reproduce this when I run complex_layout_scroll_perf__memory on my desktop.

The difference in native heap usage might be related to the image decompression thread pool introduced in https://github.com/flutter/engine/commit/ad582b5089256e56727b2d7306fb097078a3dcdc

**Comment by jason-simmons** [comment] 2019-07-13 00:18
Apparently complex_layout_scroll_perf__memory is timing sensitive.  I can reproduce the difference in native heap usage by running the benchmark controller on an old MacBook or by inserting a delay in `MemoryTest.useMemory` before the call to `recordStart()`.  Maybe that gives the device time to do a GC before the scroll test starts?

Anyway, I can confirm that the difference in behavior started with https://github.com/flutter/engine/commit/ad582b5089256e56727b2d7306fb097078a3dcdc.  However, part of the difference seems to be caused by lower native heap consumption at the start of the test.  Possibly the new image decoding approach shifts some memory usage into the time interval measured by the test when previously the allocations happened before the measurement started?

@chinmaygarde would that make sense?

**Comment by jason-simmons** [comment] 2019-07-13 01:14
Another change introduced in https://github.com/flutter/engine/commit/ad582b5089256e56727b2d7306fb097078a3dcdc is that the `SingleFrameCodec` is holding on to the encoded image data buffer (`descriptor_.data`) after decoding the frame.

This is likely what accounts for most of the observed difference in native heap usage.

**Comment by chinmaygarde** [comment] 2019-07-13 03:28
This issue was caused by the removal of a previous hack in the way the compressed host allocation used to be discarded. This hack was getting preventing users from querying the image size from the codec without incurring the cost of a 1:1 decompression (before attempting texture decompression at a reduced size).

I have highlighted the following section from the [commit message](https://github.com/flutter/engine/commit/ad582b5089256e56727b2d7306fb097078a3dcdc) of the patch that caused this regression.

> ... creating a codec with a single image frame immediately kicks of
>   decompression and upload of that frame image (even if the frame was never
>   request from the codec). This hack was added because we wanted to get rid of
>   the compressed image allocation ASAP. The expectation was codecs would only be
>   created with the sole purpose of getting the decompressed image bytes.
>   However, for applications that only create codecs to get image sizes (but
>   never actually decompress the same), we would end up replacing the compressed
>   image allocation with a larger allocation (device resident no less) for no
>   obvious use...

In the benchmark, for reasons that are not fully apparent ATM, the codec was being kept around after the frame was requested. Now, just like the multi-frame codec, the single-frame codec will also hold onto the host allocation so that it will only decompress to the device allocation lazily when the next frame is requested (or not at all in the resizing case). The reasoning being that the compressed host allocation is many times smaller than the decompressed device allocation. So, when a device allocation is not necessary, a lot of work can be avoided.

After chatting with Jason, I think we can bring back the old behavior by discarding the image descriptors compressed image data in the callback that returns the device resident image from the image decompressor. This is still a slight pessimization because applications that release images (but not their codecs) due to memory concerns will still keep a fully decompressed image in memory. But I think this behavior is baked into the contract at this point. Jason & I were prototyping a patch for this regression which we can land on Monday.

We should also figure out where the codec are being referenced though. The pessimization and the fact that both the device and host allocations will be kept for multi-frame codecs makes this behavior particularly memory hungry.

**Comment by jason-simmons** [comment] 2019-07-16 18:46
Investigated this some more and noticed that native heap size was continuing to increase even after changing SingleFrameCodec to drop its reference to the compressed image data buffer.

I tried disabling the image cache in the framework, running the Shrine demo in Gallery, and repeatedly scrolling through the images.  Native heap size and private dirty pages continued to increase, and the rate of growth was correlated with the size of the image decoder thread pool.

It looks like this is due to implementation details of Android's malloc related to allocating buffers on one thread and freeing them on another thread.  In this case, the compressed image buffer is allocated on the UI thread but is freed on a decoder worker thread.

We could work around this by queueing deletion of the buffer to the UI thread or using another mechanism (e.g. anonymous mappings) to allocate the buffer.

**Comment by gspencergoog** [comment] 2019-07-18 23:17
So, what is the status of this bug?  Has it been mitigated, or is there still more work to be done?

**Comment by jason-simmons** [comment] 2019-07-19 00:47
https://github.com/flutter/engine/commit/b7b791b3fa05fe06d778c56d8ad53897f8ef05cc will help, but the memory usage behavior of the image decoder thread pool will differ from the previous implementation.  We can rebase the benchmarks after that PR rolls over to the framework.

**Comment by gspencergoog** [comment] 2019-07-19 16:17
@jason-simmons, Is it mitigated to the point that this is no longer a TODAY bug? (assuming I merge that change into the google3 roll)

**Comment by Hixie** [comment] 2019-07-22 22:26
(this started around https://github.com/flutter/flutter/pull/36238)

**Comment by chinmaygarde** [comment] 2019-07-22 23:01
The additions in the heap size have been confirmed to not be leaks. Using additional threads for image decompression seems to be causing the system malloc (`jemalloc`) to allocate additional heap space in thread specific caches. These thread specific caches are a feature used to optimize multi-threaded performance and reduce fragmentation. This memory is available to the application even if shows as being claimed in the heap allocation report. Also, we have added an Android specific mitigation where allocations for images also don't use `malloc`, instead, we now allocate an anonymous FD mapping for image data and unmap the same when done. The utility of this mitigation is suspect as we now incur syscalls on allocation & deallocation but reported heap allocation is lower. Further optimization for this benchmark will be counterproductive. This regression also does  not show up on iOS as it uses a different allocator.

The recommendation is to re-baseline the benchmark.

**Comment by franciscojma86** [comment] 2019-07-30 21:36
Regression has been re-introduced since 7/26 on [9b150f134b9b6ba103ec305f489645b5fee905d2](https://github.com/flutter/flutter/commit/9b150f134b9b6ba103ec305f489645b5fee905d2).

**Comment by Hixie** [comment] 2019-07-31 00:13
@liyuqian this one too. (see https://github.com/flutter/flutter/issues/37176)

**Comment by liyuqian** [comment] 2019-07-31 17:38
This should be an improvement instead of a regression: both the start memory and the end memory drops after that PR.  The start memory drops more significantly so the diff (end memory - start memory) increases. Presumably, less start memory leaves GC more room to retain more objects so the diff increases. But since the overall memory strictly decreases, this has no negative effect for any users.

I think we should:
1. Rebaseline the diff memory
2. Ensure that the GC is called right before measuring the start and end memory for diff computation (https://github.com/flutter/flutter/issues/37318).

**Comment by liyuqian** [comment] 2019-07-31 17:44
Rebaseline and close this issue as the original regression disappeared since 7/19/2019, and the new regression is actually an improvement (https://github.com/flutter/flutter/issues/36079#issuecomment-516948642).

**Closed by liyuqian** 2019-07-31 17:44 UTC
Labels: severe: performance, severe: regression, ⚠ TODAY
