### ISSUE TITLE
[showDatePicker]  RenderFlex overflow exception with orientation of Axis.vertical and setting the text size to smallest from device settings.

### ISSUE THREAD

**Issue by crtingram** [flutter/flutter#61334] opened 2020-07-13 01:19 UTC
## Steps to Reproduce

1. Open _DatePickerDialog (via showDatePicker method).
2. Click edit icon top Enter Date.
3. Enter an invalid date (1/1/1) in this case.

This is only occurring on my iPhone 7 right now. Also despite what the doctor says I do have both dart and flutter plugins installed and up to date (another issues I will have to look into).

**Expected results:** 

Expect to see error message "Out of Range", not overflow message in flutter.

**Actual results:** 

See attached image.

![image](https://user-images.githubusercontent.com/25697816/87261347-af9b7600-c46a-11ea-9cd6-159d9a5823dc.png)

<details>
  <summary>Logs</summary>

```
   +1 ms] flutter: The following assertion was thrown during layout:
[        ] flutter: A RenderFlex overflowed by 4.9 pixels on the bottom.
[        ] flutter:
[        ] flutter: The relevant error-causing widget was:
[        ] flutter:   Theme
[        ] flutter:   file:///Users/cory.ingram/Documents/Development/accuro-mobile/lib/widgets/acc_calendar/acc_calendar.dart:402:18
[        ] flutter:
[        ] flutter: The overflowing RenderFlex has an orientation of Axis.vertical.
[        ] flutter: The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
[        ] flutter: black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
[        ] flutter: Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
[        ] flutter: RenderFlex to fit within the available space instead of being sized to their natural size.
[        ] flutter: This is considered an error condition because it indicates that there is content that cannot be
[        ] flutter: seen. If the content is legitimately bigger than the available space, consider clipping it with a
[        ] flutter: ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
[        ] flutter: like a ListView.
[        ] flutter: The specific RenderFlex in question is: RenderFlex#d5884 OVERFLOWING:
[        ] flutter:   needs compositing
[        ] flutter:   creator: Column ← ConstrainedBox ← Container ← LayoutBuilder ← OrientationBuilder ←
[        ] flutter:     InputDatePickerFormField ← _FormScope ← WillPopScope ← Form-[LabeledGlobalKey<FormState>#748fa] ←
[        ] flutter:     Expanded ← Column ← Builder ← ⋯
[        ] flutter:   parentData: <none> (can use size)
[        ] flutter:   constraints: BoxConstraints(w=291.2, h=66.2)
[        ] flutter:   size: Size(291.2, 66.2)
[        ] flutter:   direction: vertical
[        ] flutter:   mainAxisAlignment: start
[        ] flutter:   mainAxisSize: max
[        ] flutter:   crossAxisAlignment: center
[        ] flutter:   verticalDirection: down
[        ] flutter: ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```

```

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G103, locale en-CA)
    • Flutter version 1.17.5 at /Users/cory.ingram/Documents/Development/SDK/flutter
    • Framework revision 8af6b2f038 (12 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cory.ingram/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • 9024O                        • de3d4e87                                 • android-arm • Android 7.1.1 (API 25)
    • Android SDK built for x86 64 • emulator-5554                            • android-x64 • Android 10 (API 29)
      (emulator)

```

</details>

**Comment by darshankawar** [comment] 2020-07-13 10:48
Hi @crtingram,
Please provide a minimal complete reproducible code sample that shows this issue. Can you also confirm if this happens on Android device ?

**Comment by crtingram** [comment] 2020-07-13 19:16
@darshankawar Here is the a minimal complete reproducible code sample. I can confirm that this issue does not occur on my Android tablet, or any of the emulators that I have tried. Only on my iPhone 7. 

<details>
  <summary>Code Sample</summary>

```

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  DateTime _fromDate = DateTime.now();

  Future<void> _showDatePicker() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _fromDate,
      firstDate: DateTime(2015, 1),
      lastDate: DateTime(2100),
    );
    if (picked != null && picked != _fromDate) {
      setState(() {
        _fromDate = picked;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showDatePicker,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
</codee>

**Comment by darshankawar** [comment] 2020-07-14 09:25
Related to [55535](https://github.com/flutter/flutter/issues/55535)

**Comment by darshankawar** [comment] 2020-07-14 09:43
Hi @crtingram,
Since I don't have iPhone 7, I can't replicate the issue. I tried on iPhone 11 and 8 and don't see the overflow. Also tried on Samsung devices but didn't see the issue. May be it has to do with smaller screen devices.

**Comment by crtingram** [comment] 2020-07-14 22:33
Thanks looking @darshankawar,

I do agree it looks to be a screen size issue. I looked at the source for showDatePicker and _DatePickerDialog class but was unable to find anything to tweak the size from my application.

**Comment by KhatibFX** [comment] 2020-09-22 13:18
I am facing this issue as well, on OnePlus 5T. The problem is this line:
```dart
const Size _inputPortraitDialogSize = Size(330.0, 270.0);
```
in date_picker_dialog.dart

I took the code in the class into a custom class, and set the size to Size(330.0, 300.0); (increased the height of the dialog), and it fixed the issue for me. I wish there was a more dynamic way of controlling the size of this dialog instead of constants.

**Comment by DhavalRKansara** [comment] 2020-10-29 14:25
I am also facing the same issue with a date validation error.

**Comment by pedromassangocode** [comment] 2020-12-30 13:37
I cannot reproduce the issue on latest master channel on iPhone 8, Android 9 emulator. For anyone who was able to reproduce this issue, please provide the device information where this issue happened.

<details><summary>flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.157, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.157 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 4b83be6c23 (6 hours ago), 2020-12-30 02:09:03 -0500
    • Engine revision 0e5a25d779
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)              • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by navy1991** [comment] 2021-02-16 07:39
My iPhone11 caused this when just only smallest text size(Settings > Display&Brightness > Text Size).
When I made text size more bigger, the error disappeared.
![IMG_7553](https://user-images.githubusercontent.com/29075851/108031276-e62a1680-7073-11eb-8348-22097186551d.PNG)
![IMG_7555](https://user-images.githubusercontent.com/29075851/108031278-e75b4380-7073-11eb-9973-8ec222825653.PNG)

And fixed by changing
`const Size _inputPortraitDialogSize = Size(330.0, 270.0);`
to
`const Size _inputPortraitDialogSize = Size(330.0, 290.0);`
in date_picker_dialog.dart. (but I don't know how to fix properly...)

**Comment by dotcom** [comment] 2023-07-26 04:44
How about this
in date_picker.dart
```dart
      child: AnimatedContainer(
        width: dialogSize.width,
        //height: dialogSize.height,
        duration: _dialogSizeAnimationDuration,
        curve: Curves.easeIn,
        child: MediaQuery(
          data: MediaQuery.of(context).copyWith(
            textScaleFactor: textScaleFactor,
          ),
          child: Builder(builder: (BuildContext context) {
            switch (orientation) {
              case Orientation.portrait:
                return Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: <Widget>[
                    header,
                    if (useMaterial3) const Divider(),
                    picker, //Expanded(child: picker),
                    actions,
                  ],
                );
```

**Comment by darshankawar** [comment] 2024-07-09 11:19
I verified this issue using latest stable version and running the given code in iOS simulator iphone 7 and also on iphone 13 pro max (OS 15.3.2) and observed that the overflow exception occurs if we change the text size settings to smallest from device settings, which leads to below:

<img width="307" alt="Screenshot 2024-07-09 at 4 42 35 PM" src="https://github.com/flutter/flutter/assets/67046386/eb4c14ae-9eb5-45e8-bcb3-587922127843">
<img width="354" alt="Screenshot 2024-07-09 at 4 44 10 PM" src="https://github.com/flutter/flutter/assets/67046386/fc9a9398-af2e-4a05-90b8-4426f207b35f">

Device settings to set smallest size:

<img width="358" alt="Screenshot 2024-07-09 at 4 48 13 PM" src="https://github.com/flutter/flutter/assets/67046386/de3b1873-9dca-4a5f-b238-e93ce73fdb1a">

So this issue is still relevant and doesn't seem to be specific to device or OS version. Keeping the issue open and updating labels as applicable.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.22.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.22.2 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (33 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.24.0-1.0.pre.54, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.24.0-1.0.pre.54 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9ab8b6e150 (33 minutes ago), 2024-07-09 09:41:35 +0200
    • Engine revision 69075e7e87
    • Dart version 3.5.0 (build 3.5.0-323.0.dev)
    • DevTools version 2.37.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Closed** 2024-07-31 19:56 UTC
Labels: platform-ios, framework, f: material design, f: date/time picker, has reproducible steps, P2, team-design, triaged-design, found in release: 3.22, found in release: 3.24
