### ISSUE TITLE
Not able to compile code, Compiler message: org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find '}' to match '{'. {

### ISSUE THREAD

**Issue by krsolutions** [flutter/flutter#29191] opened 2019-03-12 00:25 UTC
Compiler message:
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find '}' to match '{'.
{
^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find '}' to match '{'.
{
^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find '}' to match '{'.
{
^
Compiler failed on /FlutterProjects/leader/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/FlutterProjects/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 553

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command '/FlutterProjects/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by lahsrah** [comment] 2019-03-14 08:24
Run `flutter clean`

**Comment by mraleph** [comment] 2019-03-19 12:13
Duplicate of #29232 29232

**Closed by mraleph** 2019-03-19 12:13 UTC
