### ISSUE TITLE
"Unable to find bundled Java version" when using Android Studio Arctic Fox Beta

### ISSUE THREAD

**Issue by Mikilll94** [flutter/flutter#86238] opened 2021-07-10 20:09 UTC
## Steps to Reproduce

1. Download Android Studio Arctic Fox Beta.
2. Do the usual stuff to install Flutter on macOS
2. Run `flutter doctor`.
3. Eventually you will receive this error:

```
Android Studio
✗ Unable to find bundled Java version.
```

In Android Studio Arctic Fox Beta, the bundled Java version is installed at this path:
`/Applications/Android\ Studio\ Preview.app/Contents/jre/Contents/Home`

However `flutter doctor` searches at this path:
`/Applications/Android\ Studio\ Preview.app/Contents/jre/jdk/Contents/Home`

This code should be fixed:
https://github.com/flutter/flutter/blob/3c72ef374d748ef07bb2f6781161fa6bcb0b4289/packages/flutter_tools/lib/src/android/android_studio.dart#L465

## Logs

<details>
<summary>Logs</summary>

```
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale
    en-PL)
    • Flutter version 2.2.3 at /Users/user/development/flutter
    • Framework revision f4abaa0735 (9 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at:
      /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/jav
      a
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • F45B25FD-BA13-4048-AB4B-70DAFD4A7F9C • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```

</details>

**Comment by asashour** [comment] 2021-07-11 12:52
A duplicate of https://github.com/flutter/flutter/issues/85602

**Comment by TahaTesser** [comment] 2021-07-12 12:26
Hi @Mikilll94 
Thanks for filing the issue, Yes I can confirm, I've added it as part of https://github.com/flutter/flutter/issues/85602

**Closed by TahaTesser** 2021-07-12 12:26 UTC
Labels: in triage
