### ISSUE TITLE
Flutter web scroll is laggy (especially on mobile)

### ISSUE THREAD

**Issue by AryashDubey** [flutter/flutter#84592] opened 2021-06-14 20:05 UTC
Hey I am using flutter for web and I have observed that the website built by it has a laggy scroll as compared to other websites and I just wanted to know when can we experience smooth scrolling behaviour on flutter web

**Comment by bernaferrari** [comment] 2021-06-14 20:18
Duplicate of https://github.com/flutter/flutter/issues/56257

**Closed** 2021-06-15 05:12 UTC
