### ISSUE TITLE
Bad cursor position with multiline TextField on web platform

### ISSUE THREAD

**Issue by ffpresents** [flutter/flutter#150851] opened 2024-06-26 13:43 UTC
### Steps to reproduce

Create a simple app with TextField(maxLines:null) and deploy it on a web host.
Open it from **Chrome on Android.** 
Type some text.

You can reproduce it on DartPad.
https://dartpad.dev/?id=3aaf0f8b64baed6878ce5614a53595bd

note: I use a keyboard called "[ATOK](https://play.google.com/store/apps/details?id=com.justsystems.atokmobile.pv.service&hl=ja)" to input characters.

### Expected results

The cursor should appear on the right.

### Actual results

The cursor appears at the bottom.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    builder: (context, child) => const MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<StatefulWidget> createState() {
    return _MyAppState();
  }
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: TextField(
          maxLines: null,
          keyboardType: TextInputType.multiline,
          controller: TextEditingController(),
          cursorColor: Colors.black,
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/135512697/5b87cd1f-fdeb-4df4-902a-7c1c10319d50

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 flutter doctor -v
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale ja-JP)
    • Flutter version 3.22.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\fmdmk\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34018.315
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code (version 1.90.2)
    • VS Code at C:\Users\fmdmk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.126
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.68

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment] 2024-06-27 06:30
Hi @ffpresents 
Looks like this can be reproduced without using ATOK keyboard app (I can't download it as it's not available on my end). I switched to Japanese input source on Gboard and seem to see the issue:

<details open>
<summary>Demo (Flutter stable 3.22.2)</summary>

| Web (Android Chrome) | Android app |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/db97bbd5-6d69-4001-a66a-cdb8fa81850d"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/be745a3c-a778-4ae1-ab23-386b1a7988be">
</details>

But it seems to be fixed on master channel as I see the cursor is aligned on right as expected:

![Screenshot 2024-06-27 at 13 28 39](https://github.com/flutter/flutter/assets/104349824/6a61c771-ebf4-4278-a95b-5f559170873d)

Can you switch to master channel and confirm this with both cases (with Gboard - Japanese input source and with ATOK keyboard app)? 

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (31 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-13.0.pre.337, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-13.0.pre.337 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5030724698 (2 hours ago), 2024-06-25 21:49:37 -0400
    • Engine revision 25af762ffb
    • Dart version 3.5.0 (build 3.5.0-299.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by ffpresents** [comment] 2024-06-28 13:01
@huycozy , thank you for your confirmation!

I checked on the master channel and the cursor position was improved as you said. (on both G Board and ATOK.)

But I noticed other problems.

On G Board, the highlight of the characters indicating compose mode is incorrect.
I've attached my screenshot, but you can see the incorrect hilight position in your screenshot as well.
<img src="https://github.com/flutter/flutter/assets/135512697/baa8ccc2-bb92-440a-8216-efd81a49c725" width="300px">


On ATOK, the characters aren't highlighted when typing. I think it is by design.
But there's another problem.

When converting characters from hiragana to kanji, the display is distorted. 
You can see that the last character 亜 is doubled in the screenshot .
This damages the user experience.

<img src="https://github.com/flutter/flutter/assets/135512697/1ddc32ab-c86c-411a-9458-c74523404d68" width="300px">
 
The cursor position has certainly been improved.
I am truly grateful for that.

However, unless other display issues are addressed, many multibyte users will hesitate to use TextField in production environments.

**Comment by huycozy** [comment] 2024-07-01 03:42
>On G Board, the highlight of the characters indicating compose mode is incorrect.

Yes, I see this issue as well. Please help to file a separate issue for more effective tracking.

>When converting characters from hiragana to kanji, the display is distorted.
You can see that the last character 亜 is doubled in the screenshot .

Please also file another issue for this. On this new issue, please mention if this can be reproduced with ATOK or also with Gboard. 

Since the original issue is fixed on master channel, I will close this. Thank you for confirmation!

**Closed by huycozy** 2024-07-01 03:42 UTC
Labels: in triage
