### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists., errno = 183

### ISSUE THREAD

**Issue by cosmo-developer** [flutter/flutter#137592] opened 2023-10-31 05:32 UTC
## Command
```
flutter build windows
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists.
, errno = 183
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:992:5)
#6      buildWindows (package:flutter_tools/src/windows/build_windows.dart:66:3)
#7      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:56:11)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.8, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    [32m•[39m Flutter version 3.13.8 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 6c4930c4ac (13 days ago), 2023-10-18 10:57:55 -0500
    [32m•[39m Engine revision 767d8c75e8
    [32m•[39m Dart version 3.1.4
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at C:\Users\SONU\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    [32m•[39m Visual Studio at E:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.7.34031.279
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2023.1)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.2
    [32m•[39m Flutter plugin version 75.1.3
    [32m•[39m Dart plugin version 231.9392.3

[32m[✓][39m VS Code (version 1.83.1)
    [32m•[39m VS Code at C:\Users\SONU\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.74.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.118
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 118.0.2088.76
    [33m![39m Device Ucamera001 is offline.

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 6c4930c4ac86fb286f30e31d0ec8bffbcbb9953e
### Plugins
audioplayers-5.1.0
audioplayers_android-4.0.1
audioplayers_darwin-5.0.1
audioplayers_linux-3.0.0
audioplayers_web-4.0.0
audioplayers_windows-3.0.0
bitsdojo_window-0.1.5
bitsdojo_window_linux-0.1.3
bitsdojo_window_macos-0.1.3
bitsdojo_window_windows-0.1.5
emoji_picker_flutter-1.6.1
file_picker-5.2.10
flutter_plugin_android_lifecycle-2.0.16
path_provider-2.1.1
path_provider_android-2.2.0
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
record-4.4.4
record_linux-0.4.1
record_macos-0.2.2
record_web-0.5.0
record_windows-0.7.1
screen_capturer-0.1.7
screen_retriever-0.1.9
shared_preferences-2.2.1
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.1
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.1
url_launcher-6.1.14
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.6
url_launcher_macos-3.0.7
url_launcher_web-2.0.19
url_launcher_windows-3.0.8
window_manager-0.3.6

**Comment by danagbemava-nc** [comment] 2023-10-31 09:03
Closing this as a duplicate of https://github.com/flutter/flutter/issues/90028

**Closed by danagbemava-nc** 2023-10-31 09:03 UTC
Labels: in triage
