### ISSUE TITLE
SystemUiOverlayStyle class ,option statusBarIconBrightness and  systemNavigationBarIconBrightness  setting invalid

### ISSUE THREAD

**Issue by dev-zl** [flutter/flutter#41256] opened 2019-09-25 05:40 UTC
## CODE

```Dart  
if (Platform.isAndroid) {
    SystemUiOverlayStyle systemUiOverlayStyle = SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarBrightness: Brightness.dark,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.dark,
    );
    SystemChrome.setSystemUIOverlayStyle(systemUiOverlayStyle);
  }
````

## image

![image](https://user-images.githubusercontent.com/36152331/65572276-33e34200-df9a-11e9-9824-5f8d0e8e6b0a.png)

[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17134.112], locale zh-CN)
    • Flutter version 1.7.8+hotfix.3 at C:\
    • Framework revision b712a172f9 (3 months ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\
    • ANDROID_SDK_ROOT = D:\
    • Java binary at: C:\
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

**Comment by escamoteur** [comment] 2019-09-25 07:37
Hi,
could you please upgrade and try on  on latest stable ?
Also please try if this also happen on master, thanks.

**Comment by dev-zl** [comment] 2019-09-25 11:52
@escamoteur 
Upgrade has no effect

**Comment by escamoteur** [comment] 2019-09-25 12:04
Could you explain to me what you mean by *invalid* It's not clear to me just from the image.

**Comment by dev-zl** [comment] 2019-09-25 12:13
@escamoteur 
The brightness of the top status bar icons.

**Comment by dev-zl** [comment] 2019-09-25 12:17
@escamoteur 
option  statusBarIconBrightness ,  i setting Brightness.dark  But there was no change.

**Comment by escamoteur** [comment] 2019-09-25 12:18
Ah so the status bar should be dark. The Navigationbar is dark, that's ok or not?

DO you know if this was working in earlier versions?

**Comment by escamoteur** [comment] 2019-09-25 12:20
could this be the problem?
https://github.com/flutter/flutter/issues/40590

**Comment by dev-zl** [comment] 2019-09-25 12:29
So this is a problem.
I am looking forward to is, Status bar font, icon color for dark

**Comment by escamoteur** [comment] 2019-09-25 12:32
@dev-zl does #40590 fit?

**Comment by dev-zl** [comment] 2019-09-25 12:40
@escamoteur 
I think this question should be treated as a separate question，You can also merge

**Comment by TahaTesser** [comment] 2020-03-10 13:00
Issue still exist on 
```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

<details>
 <summary>Code Sample</summary>

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    if (Platform.isAndroid) {
      SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarBrightness: Brightness.dark,
        statusBarIconBrightness: Brightness.dark,
        systemNavigationBarColor: Colors.transparent,
        systemNavigationBarIconBrightness: Brightness.dark,
      ));
    }
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```
</details>


### Logs
<details>
 <summary>Logs/summary>

```
[  +27 ms] executing: [C:\Code\flutter_stable\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +78 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +1 ms] executing: [C:\Code\flutter_stable\] git describe --match v*.*.* --first-parent --long --tags
[  +58 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +20 ms] executing: [C:\Code\flutter_stable\] git rev-parse --abbrev-ref --symbolic @{u}
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Code\flutter_stable\] git ls-remote --get-url origin
[  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +123 ms] executing: [C:\Code\flutter_stable\] git rev-parse --abbrev-ref HEAD
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +136 ms] executing: C:\Code\SDK\platform-tools\adb.exe devices -l
[  +29 ms] Exit code 0 from: C:\Code\SDK\platform-tools\adb.exe devices -l
[        ] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:2
[  +21 ms] C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f shell getprop
[ +116 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +182 ms] Generating
C:\Users\Taha\AndroidStudioProjects\stable_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java    
[  +68 ms] ro.hardware = exynos7904
[   +1 ms] ro.build.characteristics = phone
[  +64 ms] Launching lib\main.dart on SM M305F in debug mode...
[  +14 ms] executing: C:\Code\SDK\build-tools\29.0.3\aapt dump xmltree
C:\Users\Taha\AndroidStudioProjects\stable_app\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +39 ms] Exit code 0 from: C:\Code\SDK\build-tools\29.0.3\aapt dump xmltree
C:\Users\Taha\AndroidStudioProjects\stable_app\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +3 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.stable_app" (Raw: "com.example.stable_app")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="stable_app" (Raw: "stable_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")   
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.stable_app.MainActivity" (Raw:
                   "com.example.stable_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +22 ms] executing: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f shell -x logcat -v time -t 1
[ +145 ms] Exit code 0 from: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f shell -x logcat -v time -t 1
[        ] --------- beginning of system
           03-10 18:29:02.058 I/SamsungAlarmManager( 6061): setLocked to kernel - T:3 / 20200310T182914, SetElapsed=26839538, 
           nowELAPSED=26826905
[  +24 ms] executing: C:\Code\SDK\platform-tools\adb.exe version
[   +2 ms] executing: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f logcat -v time -T 03-10 18:29:02.058
[  +58 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\Code\SDK\platform-tools\adb.exe
[   +4 ms] executing: C:\Code\SDK\platform-tools\adb.exe start-server
[  +30 ms] Building APK
[  +25 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from C:\Users\Taha\AndroidStudioProjects\stable_app\android\gradlew.bat.
[  +10 ms] executing: C:\Code\android-studio\jre\bin\java -version
[ +122 ms] Exit code 0 from: C:\Code\android-studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +5 ms] executing: [C:\Users\Taha\AndroidStudioProjects\stable_app\android\]
C:\Users\Taha\AndroidStudioProjects\stable_app\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\Taha\AndroidStudioProjects\stable_app\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+3476 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [  +59 ms] executing: [C:\Code\flutter_stable\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +85 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +32 ms] [        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +1 ms] [        ] executing: [C:\Code\flutter_stable\] git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] [  +45 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] [        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +24 ms] [  +12 ms] executing: [C:\Code\flutter_stable\] git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[   +1 ms] [        ] executing: [C:\Code\flutter_stable\] git ls-remote --get-url origin
[        ] [  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] [        ] https://github.com/flutter/flutter.git
[   +1 ms] [  +89 ms] executing: [C:\Code\flutter_stable\] git rev-parse --abbrev-ref HEAD
[  +16 ms] [  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[  +17 ms] [  +25 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +18 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +13 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +129 ms] Initializing file store
[  +12 ms] [  +21 ms] Done initializing file store
[+1017 ms] [+1439 ms] kernel_snapshot: Starting due to {InvalidatedReason.inputChanged}
[   +1 ms] [  +17 ms] C:\Code\flutter_stable\bin\cache\dart-sdk\bin\dart.exe
C:\Code\flutter_stable\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Code\flutter_stable\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter
-Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages
C:\Users\Taha\AndroidStudioProjects\stable_app\.packages --output-dill
C:\Users\Taha\AndroidStudioProjects\stable_app\.dart_tool\flutter_build\1f88f472f0ff8ff2af630c7287cd9634\app.dill --depfile   
C:\Users\Taha\AndroidStudioProjects\stable_app\.dart_tool\flutter_build\1f88f472f0ff8ff2af630c7287cd9634\kernel_snapshot.d    
package:stable_app/main.dart
[+6493 ms] [+6454 ms] kernel_snapshot: Complete
[ +299 ms] [ +354 ms] debug_android_application: Starting due to {InvalidatedReason.inputChanged,
InvalidatedReason.outputMissing}
[ +202 ms] [ +206 ms] debug_android_application: Complete
[  +95 ms] [  +32 ms] Persisting file store
[   +1 ms] [  +22 ms] Done persisting file store
[        ] [   +5 ms] build succeeded.
[  +20 ms] [  +28 ms] "flutter assemble" took 8,782ms.
[ +185 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[  +18 ms] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[  +66 ms] > Task :app:mergeDebugAssets
[ +304 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[  +15 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +74 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +1 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +21 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +2 ms] > Task :app:processDebugResources UP-TO-DATE
[  +43 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[  +94 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +8 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[  +98 ms] > Task :app:compileDebugSources UP-TO-DATE
[   +3 ms] > Task :app:processDebugJavaRes NO-SOURCE
[  +72 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[   +4 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +4 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[   +4 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[ +211 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[   +8 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +3 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +3 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[   +3 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[  +42 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +7 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +2 ms] Compatible side by side NDK version was not found.
[+1663 ms] > Task :app:packageDebug
[   +1 ms] > Task :app:assembleDebug
[   +1 ms] BUILD SUCCESSFUL in 14s
[  +11 ms] 30 actionable tasks: 5 executed, 25 up-to-date
[ +599 ms] Running Gradle task 'assembleDebug'... (completed in 15.5s)
[  +76 ms] calculateSha: LocalDirectory: 'C:\Users\Taha\AndroidStudioProjects\stable_app\build\app\outputs\apk'/app.apk
[  +78 ms] calculateSha: reading file took 76us
[ +821 ms] calculateSha: computing sha took 820us
[  +21 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[   +5 ms] executing: C:\Code\SDK\build-tools\29.0.3\aapt dump xmltree
C:\Users\Taha\AndroidStudioProjects\stable_app\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +21 ms] Exit code 0 from: C:\Code\SDK\build-tools\29.0.3\aapt dump xmltree
C:\Users\Taha\AndroidStudioProjects\stable_app\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +23 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.stable_app" (Raw: "com.example.stable_app")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="stable_app" (Raw: "stable_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")   
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.stable_app.MainActivity" (Raw:
                   "com.example.stable_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +38 ms] Stopping app 'app.apk' on SM M305F.
[  +11 ms] executing: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f shell am force-stop com.example.stable_app       
[ +156 ms] executing: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f shell pm list packages com.example.stable_app
[ +157 ms] package:com.example.stable_app
[   +4 ms] executing: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f shell cat
/data/local/tmp/sky.com.example.stable_app.sha1
[ +107 ms] b6d2f2444667038f4551fac8396190c92f9c2eaa
[   +1 ms] Installing APK.
[   +2 ms] executing: C:\Code\SDK\platform-tools\adb.exe version
[  +37 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\Code\SDK\platform-tools\adb.exe
[   +2 ms] executing: C:\Code\SDK\platform-tools\adb.exe start-server
[  +34 ms] Installing build\app\outputs\apk\app.apk...
[   +2 ms] executing: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f install -t -r
C:\Users\Taha\AndroidStudioProjects\stable_app\build\app\outputs\apk\app.apk
[+5643 ms] Performing Streamed Install
                    Success
[        ] Installing build\app\outputs\apk\app.apk... (completed in 5.6s)
[   +2 ms] executing: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f shell echo -n
8aed24a813f1e2db234633927c37c438914683dc > /data/local/tmp/sky.com.example.stable_app.sha1
[ +100 ms] SM M305F startApp
[   +3 ms] executing: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f shell am start -a android.intent.action.RUN -f
0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez
verify-entry-points true com.example.stable_app/com.example.stable_app.MainActivity
[ +170 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.stable_app/.MainActivity (has
extras) }
[   +1 ms] Waiting for observatory port to be available...
[+1000 ms] D/FlutterActivity(32292): Using the launch theme as normal theme.
[   +2 ms] D/FlutterActivityAndFragmentDelegate(32292): Setting up FlutterEngine.
[  +13 ms] D/FlutterActivityAndFragmentDelegate(32292): No preferred FlutterEngine was provided. Creating a new FlutterEngine 
for this FlutterFragment.
[ +425 ms] D/FlutterActivityAndFragmentDelegate(32292): Attaching FlutterEngine to the Activity that owns this Fragment.
[ +113 ms] D/FlutterView(32292): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@9ac55ca
[  +65 ms] D/FlutterActivityAndFragmentDelegate(32292): Executing Dart entrypoint: main, and sending initial route: /
[ +162 ms] Observatory URL on device: http://127.0.0.1:35704/GEroKOG1-N0=/
[   +2 ms] executing: C:\Code\SDK\platform-tools\adb.exe -s 32003c30dc19668f forward tcp:0 tcp:35704
[  +42 ms] 64309
[  +13 ms] Forwarded host port 64309 to device port 35704 for Observatory
[  +13 ms] Connecting to service protocol: http://127.0.0.1:64309/GEroKOG1-N0=/
[ +393 ms] Successfully connected to service protocol: http://127.0.0.1:64309/GEroKOG1-N0=/
[   +5 ms] Sending to VM service: getVM({})
[  +19 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Unknown, operatingSystem: android, targetCPU: arm64,
version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "android_arm64", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 32292,  
startTime: 158384...
[   +7 ms] Sending to VM service: getIsolate({isolateId: isolates/72054418052731})
[  +10 ms] Sending to VM service: _flutter.listViews({})
[  +47 ms] Result: {type: Isolate, id: isolates/72054418052731, name: main, number: 72054418052731, _originNumber:
72054418052731, startTime: 1583845167190, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0,       
avgCollectionPeriodMillis: 0.0,...
[  +15 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7c13218b20, isolate: {type:
@Isolate, fixedId: true, id: isolates/72054418052731, name: main.dart$main-72054418052731, number: 72054418052731}}]}
[   +8 ms] DevFS: Creating new filesystem on the device (null)
[  +12 ms] Sending to VM service: _createDevFS({fsName: stable_app})
[  +66 ms] Result: {type: FileSystem, name: stable_app, uri:
file:///data/user/0/com.example.stable_app/code_cache/stable_appJAPIEL/stable_app/}
[   +2 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.example.stable_app/code_cache/stable_appJAPIEL/stable_app/)
[   +3 ms] Updating assets
[  +91 ms] Syncing files to device SM M305F...
[   +3 ms] Scanning asset files
[   +3 ms] <- reset
[  +11 ms] Compiling dart to kernel with 0 updated files
[   +9 ms] C:\Code\flutter_stable\bin\cache\dart-sdk\bin\dart.exe
C:\Code\flutter_stable\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Code\flutter_stable\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Taha\AppData\Local\Temp\flutter_tool.e9d02204-62ce-11ea-9e4a-40b0760a8f62\app.dill --packages
C:\Users\Taha\AndroidStudioProjects\stable_app\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[  +19 ms] <- compile package:stable_app/main.dart
[ +780 ms] D/ViewRootImpl@66ce36c[MainActivity](32292): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340)
req=(1080,2340)0 dur=23 res=0x1 s={true 532537868288} ch=false
[ +262 ms] D/ViewRootImpl@66ce36c[MainActivity](32292): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340)
req=(1080,2340)0 dur=19 res=0x1 s={true 532537868288} ch=false
[ +172 ms] D/InputMethodManager(32292): prepareNavigationBarInfo() DecorView@2ddd340[MainActivity]
[   +1 ms] D/InputMethodManager(32292): getNavigationBarColor() 0
[   +1 ms] V/InputMethodManager(32292): Starting input: tba=com.example.stable_app ic=null mNaviBarColor 0
mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
[  +15 ms] D/InputMethodManager(32292): startInputInner - Id : 0
[   +1 ms] I/InputMethodManager(32292): startInputInner - mService.startInputOrWindowGainedFocus
[   +1 ms] D/InputTransport(32292): Input channel destroyed: 'ClientS', fd=86
[ +399 ms] D/ViewRootImpl@66ce36c[MainActivity](32292): stopped(true) old=false
[   +5 ms] D/SurfaceView(32292): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{5e5d817 V.E......
........ 0,0-1080,2214} of ViewRootImpl@66ce36c[MainActivity]
[  +13 ms] D/SurfaceView(32292): surfaceDestroyed callback.size 1 #1 io.flutter.embedding.android.FlutterSurfaceView{5e5d817
V.E...... ........ 0,0-1080,2214}
[  +18 ms] W/libEGL  (32292): EGLNativeWindowType 0x7bfdbb2010 disconnect failed
[        ] D/SurfaceView(32292): remove() io.flutter.embedding.android.FlutterSurfaceView{5e5d817 V.E...... ........
0,0-1080,2214} Surface(name=SurfaceView - com.example.stable_app/com.example.stable_app.MainActivity@5e5d817@0)/@0xafd106e    
[   +2 ms] D/FlutterView(32292): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@9ac55ca
[ +312 ms] D/ViewRootImpl@66ce36c[MainActivity](32292): MSG_WINDOW_FOCUS_CHANGED 0 1
[   +1 ms] D/InputMethodManager(32292): prepareNavigationBarInfo() DecorView@2ddd340[MainActivity]
[   +1 ms] D/InputMethodManager(32292): getNavigationBarColor() 0
[+44
```
</details>

**Comment by markusaksli-nc** [comment] 2020-07-30 14:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/41256 since the author and the repro code is using an AppBar. Otherwise the issue does not reproduce.

**Closed by markusaksli-nc** 2020-07-30 14:42 UTC
Labels: a: fidelity, a: layout, a: quality, engine, framework, platform-android
