### ISSUE TITLE
Crash while swiping between low-light and ambient screens on some devices

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#32779] opened 2019-05-15 21:47 UTC
Placeholder for triage for https://fuchsia.atlassian.net/browse/FL-258. Discussion of this issue should be handled there. When that issue closes, please close this one.

**Comment by liyuqian** [comment] 2019-06-26 21:14
According to our latest debugging with Ariana, the issue is more likely in Fuchsia FIDL or scenic, than in Flutter. Hence I'm closing this issue for now, and reassign FL-258 to Michael Jurka.

**Closed by liyuqian** 2019-06-26 21:14 UTC
Labels: customer: fuchsia, engine, severe: customer blocker
