### ISSUE TITLE
ExceptionHandler Widget

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#19993] opened 2018-07-30 17:17 UTC
@eseidelGoogle As discussed here is the issue:

Currently we don't have a possibility to handle Exceptions that happens inside a Widget somewhere down the widget tree. I would propose a Widget that allows that. Something like

```Dart
typedef ExceptionHandler = void Function( ex)
typedef AlternativeBuilder = void Function(BuildingContext context, ex)


ExceptionHandledBuilder(
   List<Object>  exceptionsToCatch,           // Exceptions that should behandled  (It's really a pity that Dart doesen't have a common Exception base class)
   HandlerFunction: onException,               // get's called to allow logging or what else
   AlternativeBuilder: alternativeBuilder,     // Builder that get's invoked while executing the normal builder method
   AsyncWidgetBuilder<T>: builder);          // the default builder that tryies to bild the child widget tree.
```

I'm not sure if something like this is possible.

What are your thoughts?

**Comment by eseidelGoogle** [comment] 2018-07-30 17:24
@Hixie and @leafpetersen are the right folks for thoughts probably.

**Comment by leafpetersen** [comment] 2018-07-30 21:06
I don't have a lot of thoughts from the language perspective (as opposed to the API perspective), other than to wonder whether support for implicitly lazy parameters would clean this up a bit?  cc @munificent

**Comment by Hixie** [comment] 2018-07-30 22:33
@escamoteur  What's the use case here?

**Comment by zoechi** [comment] 2018-07-31 06:54
I guess the first bullet of #19996

**Comment by escamoteur** [comment] 2018-07-31 07:47
@Hixie if I call a dcuntion to assign a value inside the widget tree that could throw an exception I have no chance to handle this. Sure I could do such calls at the beginning of the build method with a try-catch  and set some bool flags to display different contents but I think there should be a better way to achieve that

**Comment by munificent** [comment] 2018-08-02 22:14
Ah, so the issue is that in the middle of building a tree of widgets, an exception might occur. You want to be able to catch it and provide an alternate subtree instead of the failed one?

Something like:

```dart
Widget hopefullyMakeText() {
  if (sometimes) throw "Oh no!";

  return Text('Hello, world!');
}

Widget build() {
  return Center(child: hopefullyMakeText());
}
```

And you want to be able to handle that exception and swap out the widget without having to do:

```dart
Widget build() {
  // Hoist everything out of expression.
  Widget child;
  try {
    child = hopefullyMakeText();
  } catch (error) {
    child = Text('Fallback');
  }

  return Center(child: child);
}
```

Do I have that right? You can always solve this at the application level by writing a utility function:

```dart
Widget definitelyMakeText() {
  try {
    return hopefullyMakeText();
  } catch (error) {
    return Text('Fallback');
  }
}

Widget build() {
  return Center(child: definitelyMakeText());
}
```

If Dart were an expression-oriented language, I could imagine that it would allow something like:

```dart
Widget build() {
  return Center(
    child: try {
      hopefullyMakeText();
    } catch (error) {
      Text('Fallback');
    }
  );
}
```

I'm definitely not *proposing* that, but that is a way it could be solved in the language.

As far as your original question, yes, it's possible. Here's one way:

```dart
T handleException<T>(T Function() original, T Function() fallback) {
  try {
    return original();
  } catch (error) {
    return fallback();
  }
}
```

Then you'd use it like:

```dart
Widget build() {
  return Center(
    child: handleException(hopefullyMakeText, () => Text('Fallback'))
  );
}
```

It would be easy to extend `handleException()` to let you control which exceptions it catches.

**Comment by zoechi** [comment] 2018-09-03 08:19
@escamoteur what do you think about @munificent's suggestion?

**Comment by escamoteur** [comment] 2018-09-05 07:40
Yeah, that is a completely feasible solution. My suggestion from the beginning was if something like that shouldn't be part of the framework. @eseidel

**Comment by Hixie** [comment] 2018-09-12 19:27
I would recommend making your build methods not ever throw. Don't read data from a database within your build methods, for example; read the data in your model objects, asynchronously, and have the build methods read from your model in a way guaranteed not to throw.

But if that's not a thing you want to do, consider making a variant of Builder that catches exceptions, something like (untested):

```dart
class SafeBuilder extends StatelessWidget {
  SafeBuilder({
    Key key,
    this.builder,
  }) : super(key: key);
  final WidgetBuilder builder;
  @override
  Widget build(BuildContext context) {
    try {
      return builder(context);
    } catch (error) {
      return ErrorWidget(error);
    }
  }
}
```

If you want custom handling for the error, you can call a different builder instead of ErrorWidget.

Also you may wish to look at [ErrorWidget.builder](https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/ErrorWidget/builder.html), which is a more global way to catch errors.

**Comment by escamoteur** [comment] 2018-09-18 07:44
@Hixie that looks like an interesting idea. I agree with you that normally this should not happen. Anyway I still think such a widget should be part of the framework in case you need it e.g. if a Widget from a package throws exception under certain conditions.

**Comment by Hixie** [comment] 2018-10-06 00:17
We don't really want to encourage people to consider it to be ok to throw in a builder. We technically already wrap most builders in a try/catch, that's how `ErrorWidget.builder` gets called.

**Comment by goderbauer** [comment] 2019-01-03 20:17
Closing based on the comment above from @Hixie.

**Closed by goderbauer** 2019-01-03 20:17 UTC
Labels: framework, severe: new feature

**Comment by rrousselGit** [comment] 2019-07-02 10:57
https://github.com/flutter/flutter/issues/19993#issuecomment-420768814

This is not a solution. Error boundaries are not just about build methods. 

They are for any kind of exceptions that comes from the descendants. This also includes:
- click handlers
- uncaught futures
- other widgets lifecycles

The exception can also happens from a widget very deep down in the widget tree. 
The catcher is not necesseraly the widget that threw.

**Comment by eseidelGoogle** [comment] 2019-07-09 17:46
@rrousselGit I think to revive this discussion we're going to need to engage in something a bit more long-form.  Can you provide examples of what you're trying to achieve?  (e.g. I want to have a click-handler which might throw and when it does I want to do X.)

There is discussion of error reporting in https://flutter.dev/docs/cookbook/maintenance/error-reporting.  As Ian notes, there is already an ErrorWidget.  But it's not clear from your comment what your asking for.

In any case, this bug is long and it might be time to start a new one, clearly stating the *problem* and *desired outcome* and let folks hash out what the right solutions then should be?

**Comment by escamoteur** [comment] 2020-03-12 11:41
I'm currently faced with the situation that it can happen that a file a FileImage tries to load does not exists. Currently there is only a loadingBuilder but not an ErrorBuilder. This just as an example.

**Comment by escamoteur** [comment] 2020-03-12 11:46
The handleException og @munificent solved it for now. I still think we should have something like this in the framework

**Comment by escamoteur** [comment] 2020-03-12 11:59
I have to correct me. The exception that is thrown by the imagestream never reaches the Widgettree. it is swallowed somewhere.
