### ISSUE TITLE
google_maps_flutter Freeze/Crash on android

### ISSUE THREAD

**Issue by AliEasy** [flutter/flutter#73310] opened 2021-01-05 10:46 UTC
I created a single page Flutter android app and used [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) to show and pick location.

After launching application, map loads and every thing is fine but after using map like scroll or zoom, every thing on phone freezes and stop working and this situation continues until phone is restarted.

flutter doctor:
```
C:\Windows\System32>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.17763.1637], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)
```

logcat:

> 01-05 14:12:26.822 31451-31451/com.google.test_google_map D/DisplayManager: getDisplayInfo: displayId=14, info=DisplayInfo{"flutter-vd", uniqueId "virtual:com.google.test_google_map,10233,flutter-vd,0", app 1080 x 1776, real 1080 x 1776, largest app 1080 x 1776, smallest app 1080 x 1776, mode 15, defaultMode 15, modes [{id=15, width=1080, height=1776, fps=60.0}], rotation 0, density 480 (480.0 x 480.0) dpi, layerStack 14, appVsyncOff 0, presDeadline 16666666, type VIRTUAL, state ON, owner com.google.test_google_map (uid 10233), FLAG_PRIVATE}
> 01-05 14:12:26.834 31451-31451/com.google.test_google_map D/DisplayManager: getDisplayInfo: displayId=14, info=DisplayInfo{"flutter-vd", uniqueId "virtual:com.google.test_google_map,10233,flutter-vd,0", app 1080 x 1776, real 1080 x 1776, largest app 1080 x 1776, smallest app 1080 x 1776, mode 15, defaultMode 15, modes [{id=15, width=1080, height=1776, fps=60.0}], rotation 0, density 480 (480.0 x 480.0) dpi, layerStack 14, appVsyncOff 0, presDeadline 16666666, type VIRTUAL, state ON, owner com.google.test_google_map (uid 10233), FLAG_PRIVATE}
> 01-05 14:12:26.851 31451-31451/com.google.test_google_map D/DisplayManager: getDisplayInfo: displayId=14, info=DisplayInfo{"flutter-vd", uniqueId "virtual:com.google.test_google_map,10233,flutter-vd,0", app 1080 x 1776, real 1080 x 1776, largest app 1080 x 1776, smallest app 1080 x 1776, mode 15, defaultMode 15, modes [{id=15, width=1080, height=1776, fps=60.0}], rotation 0, density 480 (480.0 x 480.0) dpi, layerStack 14, appVsyncOff 0, presDeadline 16666666, type VIRTUAL, state ON, owner com.google.test_google_map (uid 10233), FLAG_PRIVATE}
> 01-05 14:12:26.854 31451-31451/com.google.test_google_map I/Google Maps Android API: Google Play services package version: 204713018
> 01-05 14:12:26.859 31451-31451/com.google.test_google_map I/System: exec(/system/bin/getprop debug.mapview.renderer.label @ com.google.maps.api.android.lib6.common.q.e:2)
> 01-05 14:12:26.924 31451-10427/com.google.test_google_map D/libc: [NET] android_getaddrinfofornetcontext+,hn 19(0x636c69656e7473),sn(),hints(known),family 0,flags 1024, proc=com.google.test_google_map
> 01-05 14:12:26.924 31451-10427/com.google.test_google_map D/libc: [NET] android_getaddrinfo_proxy get netid:0
> 01-05 14:12:26.925 31451-10427/com.google.test_google_map D/libc: [NET] android_getaddrinfo_proxy-, success
> 01-05 14:12:26.925 31451-31451/com.google.test_google_map D/DisplayManager: getDisplayInfo: displayId=14, info=DisplayInfo{"flutter-vd", uniqueId "virtual:com.google.test_google_map,10233,flutter-vd,0", app 1080 x 1776, real 1080 x 1776, largest app 1080 x 1776, smallest app 1080 x 1776, mode 15, defaultMode 15, modes [{id=15, width=1080, height=1776, fps=60.0}], rotation 0, density 480 (480.0 x 480.0) dpi, layerStack 14, appVsyncOff 0, presDeadline 16666666, type VIRTUAL, state ON, owner com.google.test_google_map (uid 10233), FLAG_PRIVATE}
> 01-05 14:12:26.925 31451-31451/com.google.test_google_map D/DisplayManager: getDisplayInfo: displayId=14, info=DisplayInfo{"flutter-vd", uniqueId "virtual:com.google.test_google_map,10233,flutter-vd,0", app 1080 x 1776, real 1080 x 1776, largest app 1080 x 1776, smallest app 1080 x 1776, mode 15, defaultMode 15, modes [{id=15, width=1080, height=1776, fps=60.0}], rotation 0, density 480 (480.0 x 480.0) dpi, layerStack 14, appVsyncOff 0, presDeadline 16666666, type VIRTUAL, state ON, owner com.google.test_google_map (uid 10233), FLAG_PRIVATE}
> 01-05 14:12:26.962 31451-31451/com.google.test_google_map D/DisplayManager: getDisplayInfo: displayId=14, info=DisplayInfo{"flutter-vd", uniqueId "virtual:com.google.test_google_map,10233,flutter-vd,0", app 1080 x 1776, real 1080 x 1776, largest app 1080 x 1776, smallest app 1080 x 1776, mode 15, defaultMode 15, modes [{id=15, width=1080, height=1776, fps=60.0}], rotation 0, density 480 (480.0 x 480.0) dpi, layerStack 14, appVsyncOff 0, presDeadline 16666666, type VIRTUAL, state ON, owner com.google.test_google_map (uid 10233), FLAG_PRIVATE}
> 01-05 14:12:33.132 31451-31463/com.google.test_google_map I/art: Background sticky concurrent mark sweep GC freed 181279(5MB) AllocSpace objects, 32(1836KB) LOS objects, 0% free, 40MB/40MB, paused 14.276ms total 83.887ms

The phone Im using: `HTC One_M8 dual sim Android 6.0` And

**Comment by darshankawar** [comment] 2021-01-05 11:35
@AliEasy 
Can you provide minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by AliEasy** [comment] 2021-01-05 11:48
@darshankawar 
This is the whole code

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}
```

which is The Code sample on [google_maps_flutter](https://pub.dev/packages/google_maps_flutter)
and the version is `1.0.6` also tested on  `0.5.33` but no progress

Also Flutter sdk version is `1.22.4` for Windows

**Comment by darshankawar** [comment] 2021-01-06 07:32
@AliEasy 
Although I don't have the device you mentioned, but I tried on Emulator 6.0 and didn't get the issue. I was able to zoom, scroll and move the map properly without any issues.

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.26.0-2.0.pre.179, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.179 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a293c82251 (22 hours ago), 2021-01-05 04:04:03 -0500
    • Engine revision b7352132cd
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)           • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86    • Android
      11 (API 30) (emulator)
    • macOS (desktop)             • macos            • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)                • chrome           • web-javascript • Google
      Chrome 87.0.4280.88

! Doctor found issues in 1 category.

```

</details>


Can you try on any other device or on an emulator to see if you still get the issue ?

**Comment by AliEasy** [comment] 2021-01-07 05:30
@darshankawar 
It works fine on my other device but the problem is I need to make sure it wont cause damage my customers device.
Also the Weird part is that I created a google map application by java and it works just fine on  the device so my guess is there sth wrong with the flutter app

**Comment by darshankawar** [comment] 2021-01-07 06:14
@AliEasy 
It indicates the issue could be device specific and may not be reproducible on all devices, so it's hard to diagnose what exactly could be causing the freeze / crash.  Does the freeze / crash happen consistently everytime ?

**Comment by AliEasy** [comment] 2021-01-07 06:45
@darshankawar 
Yes it happens every time

**Comment by darshankawar** [comment] 2021-01-07 11:58
@AliEasy 
Since it's device specific, there's similar open issue describing your case, https://github.com/flutter/flutter/issues/35809
Please follow-up there for updates.
Closing this as duplicate.

**Closed by darshankawar** 2021-01-07 11:58 UTC
Labels: in triage, waiting for customer response
