### ISSUE TITLE
Tooltip rebuild child widget on mouse reentering Flutter window

### ISSUE THREAD

**Issue by anlumo** [flutter/flutter#128516] opened 2023-06-08 16:40 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Clone the example project below.

Build on a desktop platform (confirmed on Linux and Windows), then move the mouse cursor in and out of that window.

This does not happen on the web platform.

### Expected results

Text always remaining the same after the initial delay of one second.

### Actual results

The FutureBuilder's connection state briefly flashes between waiting and done whenever the mouse enters the window. The Future is not run again, so this is purely within the builder function in the FutureBuilder.

This is apparently triggered by the Tooltip widget. The FutureBuilder is not responsible, it also happens with other widgets (the FutureBuilder just makes it easy to see). It seems like it's re-evaluating the child widget again when you leave/enter the window. I added a `print` statement to demonstrate this in the example project.

Step to reproduce on other widgets:

* open performance overlay
* leave and enter window
* the performance overlay will move by one frame

### Code sample

https://github.com/anlumo/future_flash/

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on Ubuntu 23.04 6.2.0-20-generic, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME
      set and the java binary in your PATH. You can download the JDK from
      https://www.oracle.com/technetwork/java/javase/downloads/.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by brainwo** [comment] 2023-06-08 16:55
Replicable on Linux using bspwm for window manager
Moving window focus using keyboard doesn't trigger this problem

**Comment by LongCatIsLooong** [comment] 2023-06-08 22:12
This looks like a duplicate of https://github.com/flutter/flutter/issues/117627. Feel free to reopen if that's not the case or if the issue isn't fixed on the master branch.

**Closed by LongCatIsLooong** 2023-06-08 22:12 UTC
