### ISSUE TITLE
TextField with maxLength needs multiple delete taps to delete text 

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#67828] opened 2020-10-10 16:37 UTC
b/170458334

This can be repro'ed using the sample at: https://flutter.dev/docs/cookbook/forms/retrieve-input

Add `maxLength: 5` to the `TextField` widget and try entering: "123456789" to the text field. You will need to press backspace 5 times to start deleting the text. My hunch is that we are not storing the inner "cursor position" correctly. The data seems to be correct (pressing the FAB always returns 12345).

I recall this used to work so marking as regression.

**Comment by ayRatul** [comment] 2020-10-10 16:57
The same happens when using FilteringTextInputFormatter, i use 
```
inputFormatters: [
                    FilteringTextInputFormatter.digitsOnly,
```
and i enter 123456abc , the text shows 123456 , but i need to delete 3 times (abc) before i'm able to delete the numbers. Is this the intended behaviour? even using a custom TextInputFormatter to never change the text it stills preserves a "history".

The issue seems to be fixed once i remove the focus of the textfield and focus it again. Then it seems that internally 123456abc becomes 123456

**Comment by lstimac** [comment] 2020-10-10 20:38
I noticed this issue today too, I'm using inputFormatters with digits only filter along with the max length of 6. It seems like there is a counter or something internally which means even if I limit my input to 6 characters, each additional character will not appear in the input field, but it will be counted and will disrupt backspace functionality (nothing gets deleted until you reach the "real" input text).

Let's hope this will be fixed ASAP as it is a pretty severe bug for such a widely used functionality.

### Flutter doctor
```
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.778],
    locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.49.3)
[√] Connected device (1 available)

• No issues found!

```

**Comment by pedromassango** [comment] 2020-10-11 11:22
Duplicate of https://github.com/flutter/flutter/issues/67236

**Comment by xu-baolin** [comment] 2020-10-12 04:43
I am posting the fix PR now.

**Closed** 2020-10-12 16:37 UTC
Labels: P1, a: text input, customer: money (g3), severe: regression
