### ISSUE TITLE
25% regression in `timeToFirstFrameMicros` `complex_layout_ios__start_up`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#108378] opened 2022-07-26 17:04 UTC
## Description
`timeToFirstFrameMicros` `complex_layout_ios__start_up` regressed 25%

## skiaperf 
https://flutter-flutter-perf.skia.org/e/?begin=1658785076&end=1658853605&keys=Xde9e0f83c32d64a5a26a36361411be1b&num_commits=50&request_type=1&xbaroffset=30074

## Apparent introduction
https://github.com/flutter/flutter/pull/108350

**Comment by gaaclarke** [comment] 2022-07-26 17:08
https://dart.googlesource.com/sdk.git/+/1ab217ac409ad77ce0db3b053831f33a8f551fec  may be the culprit since it would only effect iOS.

**Comment by zanderso** [comment] 2022-07-26 17:10
I'm also wondering about this patch to snapshots https://dart.googlesource.com/sdk.git/+/286326f834fcb4816c78472e36b4a69675694727. Either way cc @rmacnak-google

**Comment by jason-simmons** [comment] 2022-07-26 20:08
Reproduced this and confirmed that it started with the snapshot change (https://dart.googlesource.com/sdk.git/+/286326f834fcb4816c78472e36b4a69675694727)

**Comment by rmacnak-google** [comment] 2022-07-26 20:35
The unstripped library is now bigger. Is this benchmark using stripped or unstripped libraries?

**Comment by gaaclarke** [comment] 2022-07-26 20:48
Here is the test: https://github.com/flutter/flutter/blob/f1df76e963c3e00baff85a8020a1753f72f6b729/dev/devicelab/bin/tasks/complex_layout_ios__start_up.dart#L11

Here is what is ultimately called: https://github.com/flutter/flutter/blob/f1df76e963c3e00baff85a8020a1753f72f6b729/dev/devicelab/lib/tasks/perf_tests.dart#L691

It is using `flutter build ios -v --profile`.  I'd have to look at the tool but to know for sure but I suspect the libraries are unstripped since profile builds should have symbols for profiling.

**Comment by zanderso** [comment] 2022-07-27 02:20
There is also a ~100KB compressed size regression on the same engine roll. https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3Drelease_size_bytes%26test%3Dflutter_gallery_ios__compile

I'm guessing the cause is the same. But I'm pretty sure the size benchmark uses a release build: https://github.com/flutter/flutter/blob/b5a36f03c69ed86be85aecef48a8359e05c84482/dev/devicelab/lib/tasks/perf_tests.dart#L1379

**Comment by zanderso** [comment] 2022-07-27 02:21
Sending a revert here https://dart-review.googlesource.com/c/sdk/+/252801.

**Comment by sstrickl** [comment] 2022-07-27 09:16
The CL mentioned _really_ shouldn't have affected the size of stripped snapshots, since it only adds information in the static symbol table, which shouldn't get output to snapshots there.  I don't see any changes to snapshot size on the Golem benchmarks for that revision either outside of the usual very small fluctuations in gzip/brotli size, so I'm quite confused as to how it ended up affecting a release snapshot here. Is there an easy reproduction I can try locally?

**Comment by zanderso** [comment] 2022-07-27 13:48
The size and start-up regressions appears to be iOS-only. The size benchmark I linked above is running the command:
```
flutter build ios --release --tree-shake-icons --split-debug-info=infos/
```
Under `dev/integration_tests/flutter_gallery` in a `flutter/flutter` checkout. Then the benchmark looks at the built artifact [here](https://github.com/flutter/flutter/blob/b5a36f03c69ed86be85aecef48a8359e05c84482/dev/devicelab/lib/tasks/perf_tests.dart#L1403).

**Comment by gaaclarke** [comment] 2022-07-27 16:21
> The size and start-up regressions appears to be iOS-only.

That's a blind spot for Golem, right?

**Comment by zanderso** [comment] 2022-07-28 04:56
Both regressions have recovered following the revert rolling through, so closing this issue.

**Closed by zanderso** 2022-07-28 04:56 UTC
Labels: severe: regression, engine, dependency: dart, P1, perf: startup

**Comment by sstrickl** [comment] 2022-07-28 07:06
> > The size and start-up regressions appears to be iOS-only.
> 
> That's a blind spot for Golem, right?

Hmm, I suppose so. As I said, I'll look into it, because I am _very_ interested in seeing what's causing it. The only thing I could think of is that I somehow made a mistake in the `AssemblyImageWriter` that wasn't repeated in the `BlobImageWriter` (used for direct ELF output, which I assume the Android pipeline uses). I'll report back just to close the loop once I've found it.
