### ISSUE TITLE
Scrollable.ensureVisible does not work with nested SingleChildScrollViews on both axes

### ISSUE THREAD

**Issue by orischwartz** [flutter/flutter#65100] opened 2020-09-02 14:01 UTC
## Steps to Reproduce

1. Run the sample app below. It creates a grid of cells using a `Column` of `Row`s and two `SingleChildScrollView`s--one for `Axis.horizontal` and the other for `Axis.vertical`.

![image](https://user-images.githubusercontent.com/16327036/91993246-220a3300-ed03-11ea-8f2e-65ccbe369265.png)

**Expected results:** 
Tapping any cell should center that cell in the viewport via `ensureVisible`.

```dart
         Scrollable.ensureVisible(context,
            alignment: .5,
            duration: Duration(
              milliseconds: 500,
            ));
```

**Actual results:** 
Cells are not centered as expected. This works correctly when using just a single `SingleChildScrollView` but not with two.

`ensureVisible` does traverse all the `Scrollable`s in the context:

https://github.com/flutter/flutter/blob/a8281e31afa9dddfa0764f59128c3a2360c48f49/packages/flutter/lib/src/widgets/scrollable.dart#L312-L323

But something about nesting the scrollviews will yield different values here:

https://github.com/flutter/flutter/blob/a8281e31afa9dddfa0764f59128c3a2360c48f49/packages/flutter/lib/src/widgets/single_child_scroll_view.dart#L628

This behavior has been present since 2019 and is reproducible on the latest beta branch on both iOS and Android.

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Grid(),
      ),
    ),
  );
}

class Grid extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    List<Row> rows = List.generate(
      15,
      (y) => Row(
        children: List.generate(
          12,
          (x) => Cell(
            child: Text("$x,$y"),
          ),
        ),
      ),
    );

    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Column(
          children: rows,
        ),
      ),
    );
  }
}

class Cell extends StatelessWidget {
  final Widget child;

  const Cell({
    this.child,
  });

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () {
        Scrollable.ensureVisible(context,
            alignment: .5,
            duration: Duration(
              milliseconds: 500,
            ));
      },
      child: Container(
        width: 100,
        height: 100,
        color: Colors.grey.withOpacity(.2),
        margin: EdgeInsets.all(3),
        child: Center(
          child: child,
        ),
      ),
    );
  }
}
```

**Comment by pedromassangocode** [comment] 2020-09-02 15:18
Hi @orischwartz 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by orischwartz** [comment] 2020-09-02 15:37
```
$ flutter doctor                                                                                                                                                                    

Doctor summary (to see all details, run flutter doctor -v):  
[√] Flutter (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3) 
! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

But this is reproducible on all builds/platforms since at least August 2019 -- no special setup required.

**Comment by xu-baolin** [comment] 2020-09-03 06:17
I am currently investigating this issue.

**Comment by pedromassangocode** [comment] 2020-09-03 08:00
I was able to reproduce this on latest `master` channel. The scroll is not happening in both directions at the same time.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.65, on Mac OS X 10.15.6 19G2021, locale
    en)
    • Flutter version 1.22.0-10.0.pre.65 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 2032a448ed (81 minutes ago), 2020-09-02 23:36:19 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API
      30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome
      85.0.4183.83

! Doctor found issues in 2 categories.
```
</details>

**Comment by xu-baolin** [comment] 2020-09-03 09:08
@orischwartz 
I found the cause of the problem. 
The outer Scrollable is responsible for the horizontal adjust, When it calculates the adjustment displacement, it calculates all the cells as a whole, not the one clicked, so the whole is centered in the horizontal direction.

I modified the related algorithm, and now it works as expected
![20200903_165511](https://user-images.githubusercontent.com/61075224/92094756-5f57e900-ee07-11ea-8220-59a313c7f392.gif)
But I'm not sure the expectation is correct for this sample code.
@HansMuller @Piinks @Hixie Would you guys mind taking a look at the behavior?

**Comment by dnfield** [comment] 2020-09-29 17:39
Fix had to be reverted. Will try to come up with a new test case covering the breakage.

**Comment by dnfield** [comment] 2020-09-30 15:14
Quick update here: I'm starting to suspect the internal test this broke just needs to be updated. Trying to find the owners of that test to discuss further.

At a high level, the test is using `ensureVisible` and taking a screenshot. I think that it might not be waiting long enough now to take the screenshot, and that it might have been expecting the wrong element to be centered.

**Comment by dnfield** [comment] 2020-09-30 23:06
Ok! The basic problem here if you have a `TabView` or `PageView` that has `Row`s in its listview, and you try to scroll something on the righthand side of the screen in thef rist page/tab, it will actually now move you to the second tab. This is not desired behavior.

We might be able to somehow use the `hasImplicitScrolling` flag to work with this. I'll add a test case to clarify what needs to pass.

**Comment by xu-baolin** [comment] 2020-10-09 12:33
> Ok! The basic problem here if you have a `TabView` or `PageView` that has `Row`s in its listview, and you try to scroll something on the righthand side of the screen in thef rist page/tab, it will actually now move you to the second tab. This is not desired behavior.
> 
> We might be able to somehow use the `hasImplicitScrolling` flag to work with this. I'll add a test case to clarify what needs to pass.

Thank you very much for your investigation and additional test cases. ：）
I think we can't directly change its behavior, but through a parameter to control it so that developers can choose the scrolling behavior. I will fix it as soon as possible.

**Comment by dnfield** [comment] 2020-10-09 21:38
I believe I have a fix for this. Posting a PR.

**Comment by dnfield** [comment] 2020-10-09 21:45
My original instinct to try to use `allowImplicitScrolling` was wrong, but an easier solution was to just discard the targetRenderObject in _PagePosition's implementation of ScrollPosition.

**Closed** 2020-10-10 00:40 UTC
Labels: f: scrolling, found in release: 1.22, framework, has reproducible steps
