### ISSUE TITLE
flutter doctor --android licenses is not working

### ISSUE THREAD

**Issue by sandy9808** [flutter/flutter#53314] opened 2020-03-25 22:46 UTC
## Steps to Reproduce

1. ... I am just trying to remove the andrid license status unknown error and i got stuck in this command which is not working properly.
Just help me please.......

## command

flutter doctor --android-licenses

## exception

ProcessException: ProcessException: The system cannot find the file specified.

  Command: C:\Users\user\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --version

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:368:50)
#5      AndroidSdk.sdkManagerVersion (package:flutter_tools/src/android/android_sdk.dart:595:43)
#6      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:314:64)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:243:38)
#8      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at C:\realflutter\flutter
    [32m•[39m Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Users\user\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-R, build-tools 29.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    [31m✗[39m Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[32m[✓][39m Android Studio (version 3.6)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 44.0.2
    [32m•[39m Dart plugin version 192.7761
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[32m[✓][39m VS Code (version 1.43.1)
    [32m•[39m VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.8.1

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 2 categories.
```

```
```
## output of command
 'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\realflutter\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
CreateProcessW failed 2

Sending crash report to Google.
Crash report sent (report ID: 4b5413b5119d39c1)
Oops; flutter has exited unexpectedly.
\CreateProcessW failed 2
Crash report written to C:\Users\user\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues. -->

```
```

**Comment by sandy9808** [comment] 2020-03-25 23:39
please help someone.............

**Comment by ameyer117** [comment] 2020-03-26 02:10
You need to install the Android SDK Tools. 

You can install them from the SDK Manager in Android Studio.

Steps are as follows:
1. Open android studio.
2. Click configure on the bottom right.
3. Click SDK manager
4. Click SDK tools tab
5. Un-check the Hide Obselete Packages checkbox
6. Check Android SDK Tools (Obselete)
7. Click apply
8. Finish installation
9. Run the command -> ```flutter doctor --android-licenses```

**Comment by TahaTesser** [comment] 2020-03-26 08:49
Duplicate of [#51712](https://github.com/flutter/flutter/issues/51712)

**Closed by TahaTesser** 2020-03-26 08:49 UTC

**Comment by sandy9808** [comment] 2020-03-26 09:44
I have completed steps 1 to 8 as mentioned by @ameyer117 but i have problem in step 9 because the 
flutter doctor --android-licenses command is not working

**Comment by TahaTesser** [comment] 2020-03-26 10:08
Hi @sandy9808 
Please make sure the sdk tools is properly installed and then run the command

**Comment by TahaTesser** [comment] 2020-03-26 10:20
Please don't create duplicates 
Check out this [comment](https://github.com/flutter/flutter/issues/51712#issuecomment-593721423)

Please follow the issue [#51712](https://github.com/flutter/flutter/issues/51712)

**Comment by sandy9808** [comment] 2020-03-26 11:32
how do i make sure android sdk tools is properly installed..@TahaTesser

**Comment by sandy9808** [comment] 2020-03-26 19:17
@TahaTesser i have tried everything but this error is not going. HELP
