### ISSUE TITLE
Why do I use the TextField,the keyboard will disappear automatically??

### ISSUE THREAD

**Issue by QixianWu** [flutter/flutter#30777] opened 2019-04-09 08:16 UTC
![untitled](https://user-images.githubusercontent.com/28887269/55784194-9f1b8380-5ae2-11e9-90cf-114cf6860511.gif)

```Dart
bottomSheet: Container(
        child: Row(
          children: <Widget>[
            Expanded(child: TextField(
              autofocus: false,
            )),
            RaisedButton(
              child: Text('Send'),
              onPressed: () {},
            ),
          ],
        ),
      ),
```

**Comment by xqwzts** [comment] 2019-04-09 08:58
Could you share the full code of a minimum reproducible example?

This looks to me like the following:
- You have a StatefulWidget
- You have a parent widget that is inheriting from the MediaQuery InheritedWidget [via `MediaQuery.of(context)` in a build method]
- The keyboard opening triggers a change of dimensions, so a change in the MediaQueryData.
- The subscribed widget rebuilds, calling `dispose` on your StatefulWidget, closing the keyboard.

**Comment by QixianWu** [comment] 2019-04-09 09:07
> Could you share the full code of a minimum reproducible example?
> 
> This looks to me like the following:
> 
> * You have a StatefulWidget
> * You have a parent widget that is inheriting from the MediaQuery InheritedWidget [via `MediaQuery.of(context)` in a build method]
> * The keyboard opening triggers a change of dimensions, so a change in the MediaQueryData.
> * The subscribed widget rebuilds, calling `dispose` on your StatefulWidget, closing the keyboard.

```Dart
return Scaffold(
  appBar: AppBar(
    title: Text('bottom sheet'),
  ),
  body: ListView.builder(
    itemBuilder: (BuildContext context, int index) {
      return ListTile(
        title: Text(index.toString()),
        subtitle: Text("${index}"),
      );
    },
    itemCount: 100,
  ),
  bottomSheet: Container(
    child: Row(
      children: <Widget>[
        Expanded(child: TextField()),
        RaisedButton(
          child: Text('Send'),
          onPressed: () {},
        ),
      ],
    ),
  ),
);
```
This is a very simple code, I tried to build a new project, this problem will not happen. Simply in my project

**Comment by QixianWu** [comment] 2019-04-10 07:05
If this code  in main. dart, it can run, but this problem can occur if the page is routed to jump.

**Comment by wheel1992** [comment] 2019-04-10 07:14
```dart
...
TextField(
    autofocus: false,
),
...
```

Because you have set autofocus for every build iteration.

Remove `autofocus` will solve the issue.

**Comment by QixianWu** [comment] 2019-04-10 07:20
but i am not use the autofocus.

**Comment by QixianWu** [comment] 2019-04-10 07:25
But I didn't use autofocus.

**Comment by QixianWu** [comment] 2019-04-10 07:49
I solve this problem with other way.
I think it's because of the bottomSheet problem.
So I used `expand` of `column` to solve this problem.

**Closed** 2019-04-10 07:49 UTC
Labels: f: material design, framework

**Comment by Firzan97** [comment] 2020-12-05 20:57
You also can wrapped it with stack then using Positioned with bottom: 0..

**Comment by Spyingaround** [comment] 2021-04-15 14:39
> 
> 
> You also can wrapped it with stack then using Positioned with bottom: 0..

Can you provide some code?
I've seen your reply on issues related, but no code has been given.

**Comment by LOOS-A** [comment] 2021-06-02 09:22
@Spyingaround Here is some code:

`Expanded(child:
        Column(
             children: []
        ),
        flex: 5
)`
