### ISSUE TITLE
【BUG】When both vertical and horizontal scrolling are performed, and scrollbar is added to the scrollbar, two scrollbars will appear in horizontal scrolling.

### ISSUE THREAD

**Issue by zancheng** [flutter/flutter#60950] opened 2020-07-07 02:23 UTC
## Steps to Reproduce

1.The code runs on Android 5.1 and dartpad.
2. When both vertical and horizontal scrolling are performed, and ScrollBar widget is added to the scrollbar, two scrollbars will appear in horizontal scrolling.
https://test.unisiot.com/ad_img/pic_help/utCY7GgJEnA30RrVKm.png
```Flutter
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: CupertinoScrollbar(
        child: SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Column(
            children: [
              Container(
                color: Colors.blue,
                child: Text('1'),
                height: 500,
                alignment: Alignment.center,
              ),
              Container(
                alignment: Alignment.topLeft,
                height: 150,
                child: CupertinoScrollbar(
                  child: SingleChildScrollView(
                    physics: BouncingScrollPhysics(),
                    //设置水平方向排列
                    scrollDirection: Axis.horizontal,
                    //添加子元素
                    child: Row(
                      children: [
                        Container(
                          color: Colors.blue,
                          child: Text('1'),
                          width: 500,
                          alignment: Alignment.center,
                        ),
                        Container(
                          color: Colors.blue,
                          child: Text('1'),
                          width: 500,
                          alignment: Alignment.center,
                        ),
                        Container(
                          color: Colors.blue,
                          child: Text('1'),
                          width: 500,
                          alignment: Alignment.center,
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Container(
                color: Colors.blue,
                child: Text('1'),
                height: 500,
                alignment: Alignment.center,
              ),
              Container(
                color: Colors.blue,
                child: Text('1'),
                height: 500,
                alignment: Alignment.center,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```
**Expected results:** 
Horizontal scrolling displays only its own scroll bar.
**Actual results:** 
Horizontal scrolling also shows the scroll bar of the outer widget.

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] Connected device (3 available)

! Doctor found issues in 2 categories.

```

```
```

**Comment by darshankawar** [comment] 2020-07-07 05:46
I am able to replicate this issue on latest dev, but not sure if this is an expected behavior or not.

![60950](https://user-images.githubusercontent.com/67046386/86721072-43240f80-c043-11ea-9bb4-696280e254cb.png)

**Comment by coreysprague** [comment] 2020-07-08 17:17
this is a duplicate of: https://github.com/flutter/flutter/issues/36474

**Comment by goderbauer** [comment] 2020-07-08 22:15
Closing as dup of https://github.com/flutter/flutter/issues/36474.

**Closed by goderbauer** 2020-07-08 22:15 UTC
Labels: f: scrolling, found in release: 1.20, framework, has reproducible steps, platform-android
