### ISSUE TITLE
Using PageView and Curves.easeOutExpo produces Exception

### ISSUE THREAD

**Issue by nazrinharris** [flutter/flutter#84965] opened 2021-06-21 08:19 UTC
## Steps to Reproduce
Using PageView with NeverScrollablePhysics and controlled by a few buttons. The exception comes up when I use specific Curves.

I see the exception when I use Curves.easeOutExpo and Curves.easeOutQuad 

I do not see this exception when I use Curves.easeInExpo, Curves.easeOutCubic.

But, the exception also pops up randomly at times. Sometimes it doesn't appear and sometimes it does. I am confusion now.

```
class NewHomePage extends StatefulWidget {
  NewHomePage({Key? key}) : super(key: key);

  @override
  _NewHomePageState createState() => _NewHomePageState();
}

class _NewHomePageState extends State<NewHomePage> {
  final controller = PageController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            SizedBox(
              height: 600,
              width: 600,
              child: PageView(
                physics: NeverScrollableScrollPhysics()
                controller: controller,
                children: [
                  Container(
                    width: 50,
                    height: 50,
                    color: Colors.red,
                  ),
                  Container(
                    width: 50,
                    height: 50,
                    color: Colors.blue,
                  )
                ],
              ),
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                TextButton(
                    onPressed: () {
                      controller.previousPage(
                          duration: Duration(milliseconds: 500),
                          curve: Curves.easeOutExpo);
                    },
                    child: Text('Previous')),
                TextButton(
                    onPressed: () {
                      controller.nextPage(
                          duration: Duration(milliseconds: 500),
                          curve: Curves.easeOutExpo);
                    },
                    child: Text('Next'))
              ],
            )
          ],
        ),
      ),
    );
  }
}
```

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Actual results:** 
There does not seem to be any visible problems. Aside from the exception being thrown

<details>
  <summary>Logs</summary>

```
 ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
                    The following assertion was thrown during performLayout():
                    'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 270 pos 12:
                    'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is
                    not true.

                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md

                    The relevant error-causing widget was:
                      PageView file:///D:/DevelopmentProjects/FlutterProjects/firebasefirestore/lib/main.dart:67:22

                    When the exception was thrown, this was the stack:
                    #2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:270:12)
                    #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
                    #4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
                    #5      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
                    #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
                    #7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
                    #8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1574:12)
                    #9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1483:20)
                    #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636:7)
                    #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
                    #12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
                    #13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
                    #14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
                    #15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
                    #16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
                    #17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
                    #21     _invoke (dart:ui/hooks.dart:163:10)
                    #22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
                    #23     _drawFrame (dart:ui/hooks.dart:126:31)
                    (elided 5 frames from class _AssertionError and dart:async)

                    The following RenderObject was being processed when the exception was fired: RenderSliverFillViewport#36c4a relayoutBoundary=up2 NEEDS-LAYOUT     
                    NEEDS-COMPOSITING-BITS-UPDATE:
                      needs compositing
                      creator: _SliverFillViewportRenderObjectWidget ← _SliverFractionalPadding ← SliverFillViewport ←
                        Viewport ← IgnorePointer-[GlobalKey#2e23e] ← Semantics ← Listener ← _GestureSemantics ←
                        RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#5e5ac] ← Listener ← _ScrollableScope
                        ← _ScrollSemantics-[GlobalKey#a672e] ← ⋯
                      parentData: paintOffset=Offset(0.0, 0.0) (can use size)
                      constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle,
                        scrollOffset: 411.4, remainingPaintExtent: 411.4, crossAxisExtent: 600.0, crossAxisDirection:
                        AxisDirection.down, viewportMainAxisExtent: 411.4, remainingCacheExtent: 411.4, cacheOrigin: 0.0)
                      geometry: SliverGeometry(scrollExtent: 822.9, paintExtent: 411.4, maxPaintExtent: 822.9,
                        hasVisualOverflow: true, cacheExtent: 411.4)
                      currently live children: 1 to 1
                    This RenderObject had the following descendants (showing up to depth 5):
                        child with index 1: RenderIndexedSemantics#fab06
                          child: RenderRepaintBoundary#c2108
                            child: RenderConstrainedBox#f098f
                              child: _RenderColoredBox#2bae8
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-MY)
    • Flutter version 2.2.2 at C:\Users\unoff\fvm\default
    • Framework revision d79295af24 (10 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\unoff\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.54

• No issues found!
```

</details>

(This is my first time filing an issue so if there's any problems with this please don't hesitate to tell me.

**Comment by nazrinharris** [comment] 2021-06-21 08:25
Same issue as #47730 I believe

**Comment by darshankawar** [comment] 2021-06-21 14:13
I was able to replicate this only with `curve: Curves.easeOutExpo` and that too after compiling the app everytime, ie, didn't see the exception upon hot-restart:

```
Syncing files to device iPhone 12 Pro Max...
Restarted application in 413ms.

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 270 pos 12: 'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  PageView PageView:file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:31:22
When the exception was thrown, this was the stack: 
#2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:270:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1854:7)
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#5      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1854:7)
#7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1574:12)
#9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1483:20)
#10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1709:7)
#11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
#12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:464:19)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:879:13)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:330:5)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#21     _invoke (dart:ui/hooks.dart:163:10)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#23     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderSliverFillViewport#d2e65 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 428.0, remainingPaintExtent: 428.0, crossAxisExtent: 600.0, crossAxisDirection: AxisDirection.down, viewportMainAxisExtent: 428.0, remainingCacheExtent: 428.0, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 856.0, paintExtent: 428.0, maxPaintExtent: 856.0, hasVisualOverflow: true, cacheExtent: 428.0)
...    scrollExtent: 856.0
...    paintExtent: 428.0
...    maxPaintExtent: 856.0
...    hasVisualOverflow: true
...    cacheExtent: 428.0
...  currently live children: 1 to 1
RenderObject: RenderSliverFillViewport#d2e65 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 428.0, remainingPaintExtent: 428.0, crossAxisExtent: 600.0, crossAxisDirection: AxisDirection.down, viewportMainAxisExtent: 428.0, remainingCacheExtent: 428.0, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 856.0, paintExtent: 428.0, maxPaintExtent: 856.0, hasVisualOverflow: true, cacheExtent: 428.0)
    scrollExtent: 856.0
    paintExtent: 428.0
    maxPaintExtent: 856.0
    hasVisualOverflow: true
    cacheExtent: 428.0
  currently live children: 1 to 1
...  child with index 1: RenderIndexedSemantics#9ef0b
...    needs compositing
...    parentData: index=1; layoutOffset=428.0
...    constraints: BoxConstraints(w=428.0, h=600.0)
...    semantics node: SemanticsNode#9
...      Rect.fromLTRB(0.0, 0.0, 428.0, 600.0)
...      tags: RenderViewport.twoPane
...    semantic boundary
...    size: Size(428.0, 600.0)
...    index: 1
...    child: RenderRepaintBoundary#c4e97
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=428.0, h=600.0)
...      layer: OffsetLayer#e3f97
...        engine layer: OffsetEngineLayer#c487b
...        offset: Offset(0.0, 0.0)
...      size: Size(428.0, 600.0)
...      metrics: 96.6% useful (1 bad vs 28 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderConstrainedBox#9c56c
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=428.0, h=600.0)
...        size: Size(428.0, 600.0)
...        additionalConstraints: BoxConstraints(w=50.0, h=50.0)
...        child: _RenderColoredBox#1d015
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=428.0, h=600.0)
...          size: Size(428.0, 600.0)
...          behavior: opaque
====================================================================================================
```

<details>
<summary> flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ncflutter % flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-17.0.pre.414, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-17.0.pre.414 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 757c3add14 (7 hours ago), 2021-06-20 22:29:02 -0400
    • Engine revision 9520bb15b3
    • Dart version 2.14.0 (build 2.14.0-228.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.106

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2021-06-21 14:14
Similar issue, https://github.com/flutter/flutter/issues/47730 that was closed due to inactivity.

**Comment by xu-baolin** [comment] 2021-06-25 06:35
@darshankawar Hey, can not repro with the latest master branch code, am I miss something?
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: NewHomePage(),
    );
  }
}

class NewHomePage extends StatefulWidget {
  NewHomePage({Key? key}) : super(key: key);

  @override
  _NewHomePageState createState() => _NewHomePageState();
}

class _NewHomePageState extends State<NewHomePage> {
  final controller = PageController(keepPage: false);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            SizedBox(
              height: 600,
              width: 600,
              child: PageView(
                physics: NeverScrollableScrollPhysics(),
                controller: controller,
                children: [
                  Container(
                    width: 50,
                    height: 50,
                    color: Colors.red,
                  ),
                  Container(
                    width: 50,
                    height: 50,
                    color: Colors.blue,
                  ),
                  Container(
                    width: 50,
                    height: 50,
                    color: Colors.yellow,
                  ),
                ],
              ),
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                TextButton(
                    onPressed: () {
                      controller.previousPage(
                          duration: Duration(milliseconds: 500),
                          curve: Curves.easeOutExpo);
                    },
                    child: Text('Previous')),
                TextButton(
                    onPressed: () {
                      controller.nextPage(
                          duration: Duration(milliseconds: 500),
                          curve:  Curves.easeOutExpo);
                    },
                    child: Text('Next'))
              ],
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by nt4f04uNd** [comment] 2021-12-12 02:24
Can we close this in favour of https://github.com/flutter/flutter/issues/95101 which has a description of the problem and reproduction steps?

**Comment by Piinks** [comment] 2021-12-13 20:15
Closing per last comment, please follow up there. Thanks!

**Closed by Piinks** 2021-12-13 20:15 UTC
Labels: framework, f: scrolling, a: error message, has reproducible steps, found in release: 2.3
