### ISSUE TITLE
how to use methodchannel in a new isolate?

### ISSUE THREAD

**Issue by pickupsb** [flutter/flutter#101221] opened 2022-04-02 01:40 UTC

**Comment by Sunyandong-CS** [comment] 2022-04-02 03:21
https://pub.dev/packages/flutter_isolate
https://pub.dev/packages/isolate_handler

**Comment by stuartmorgan** [comment] 2022-04-02 13:13
Please use one of the community resources listed at https://flutter.dev/community#community-grid for questions.

Closing as this is not a bug or feature request.

**Closed by stuartmorgan** 2022-04-02 13:13 UTC
