### ISSUE TITLE
Text don't get ellipses when wrapped with in the Wrap widget 

### ISSUE THREAD

**Issue by Yuvaraj-Gajaraj** [flutter/flutter#123599] opened 2023-03-28 12:58 UTC
## Steps to Reproduce

Execute `flutter run` on the code sample 

I have wrapped a list of Text widget with large text with Wrap widget and set the overflow property in Textstyle to ellipsis but the text never get ellipse.

**Expected results:** 

<img width = 200 src='https://user-images.githubusercontent.com/61863686/228241631-1e9207ba-7b5c-427e-85cd-2a9d1cbd968b.png' />

**Actual results:** 

<img width = 200 src='https://user-images.githubusercontent.com/61863686/228242910-b6597dc9-eead-445c-8924-5e7a74aa0886.png'/>

<details>
<summary>Code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme:
          ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  _MyHomePageState();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
      padding: const EdgeInsets.all(8.0),
      child: SizedBox(
          height: 400,
          child: Wrap(
            direction: Axis.vertical,
            children: const [
              Text(
                overflow: TextOverflow.ellipsis,
                'A) Understanding Technical Stock Charts & their Types Understanding Technical Stock Charts & their Types',
                style: TextStyle(overflow: TextOverflow.ellipsis),
              ),
              Text(
                'B) Understanding Technical Stock Charts & their Types Understanding Technical Stock Charts & their Types',
                style: TextStyle(overflow: TextOverflow.ellipsis),
              ),
            ],
          )),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
syncfsuion@Syncfsuions-MacBook-Air i449418 % flutter doctor -v 
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.0 22A380 darwin-arm64, locale en-IN)
    • Flutter version 3.7.7 on channel stable at /Users/syncfsuion/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (3 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/syncfsuion/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 16208EF8-0E4F-4596-8431-868F0AD1F1B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2023-03-29 05:53
Hi @Yuvaraj-Gajaraj, this is caused by `direction: Axis.vertical`. Try removing it, the result is expected. Closing this issue as it's not a Flutter bug.

**Comment by Yuvaraj-Gajaraj** [comment] 2023-03-30 06:19
Hi @huycozy,

Please find a code snippet to reproduce the issue.

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  _MyHomePageState();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SizedBox(
              height: 400,
              child: Wrap(
                direction: Axis.vertical,
                children: [
                  Row(
                    children: const [
                      Icon(
                        Icons.circle,
                        color: Colors.red,
                        size: 10,
                      ),
                      Text(
                        'Understanding Technical Stock Charts & their Types Understanding Technical Stock Charts & their Types',
                        style: TextStyle(overflow: TextOverflow.ellipsis),
                      ),
                    ],
                  ),
                  Row(
                    children: const [
                      Icon(
                        Icons.circle,
                        color: Colors.blue,
                        size: 10,
                      ),
                      Text(
                        'Understanding Technical Stock Charts & their Types Understanding Technical Stock Charts & their Types',
                        style: TextStyle(overflow: TextOverflow.ellipsis),
                      ),
                    ],
                  ),
                ],
              )),
        ),
      ),
    );
  }
}

```

**Comment by huycozy** [comment] 2023-03-30 07:57
I reopen this issue for further discussion. As above sample code, I see you still use `direction: Axis.vertical`. Below is the result when removing it:

<img width="400" src="https://user-images.githubusercontent.com/104349824/228769027-8a940898-902a-4046-bc7a-57ceb162fc2b.png">

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (34 hours ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.9.0-18.0.pre.51, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.9.0-18.0.pre.51 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 659ba386f6 (3 hours ago), 2023-03-28 19:13:50 -0500
    • Engine revision 78f9c68971
    • Dart version 3.0.0 (build 3.0.0-376.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 8 Plus (mobile) • A6BF67EF-D048-430D-A097-324F146781DA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 111.0.5563.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by Yuvaraj-Gajaraj** [comment] 2023-03-30 08:49
Hi @huycozy,

I have removed the `direction: Axis.vertical` It show the pixel overflow issue. Please check the below image.

![image](https://user-images.githubusercontent.com/61863686/228782034-f5de9bd5-7792-4419-9962-44bfb1955ccc.png)

**Comment by huycozy** [comment] 2023-03-30 10:28
This is caused by you wrapping `Icon` and `Text` inside a `Row`. And you should fix the Text overflow issue with `Row` widget, and it's not `Wrap` widget's issue.

You can try below code:

<details>
<summary>Sample code</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  _MyHomePageState();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SizedBox(
              height: 400,
              child: Wrap(
                children: [
                  Row(
                    children: const [
                      Icon(
                        Icons.circle,
                        color: Colors.red,
                        size: 10,
                      ),
                      Expanded(
                        child: Text(
                          'Understanding Technical Stock Charts & their Types Understanding Technical Stock Charts & their Types',
                          style: TextStyle(overflow: TextOverflow.ellipsis),
                        ),
                      ),
                    ],
                  ),
                  Row(
                    children: const [
                      Icon(
                        Icons.circle,
                        color: Colors.blue,
                        size: 10,
                      ),
                      Expanded(
                        child: Text(
                          'Understanding Technical Stock Charts & their Types Understanding Technical Stock Charts & their Types',
                          style: TextStyle(overflow: TextOverflow.ellipsis),
                        ),
                      ),
                    ],
                  ),
                ],
              )),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>Demo</summary>

![Screenshot 2023-03-30 at 17 18 43](https://user-images.githubusercontent.com/104349824/228806110-424aec31-235e-45de-87d0-fbf0db697f13.png)

</details>

Since it is expected behavior, closing the issue from here. Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Thanks!

**Closed by huycozy** 2023-03-30 10:28 UTC
Labels: in triage

**Comment by LavanyaGowtham2021** [comment] 2023-04-10 13:21
Hi @huycozy ,

Facing same issue in wrap widget as per the below code snippet.

Sample Code:

`import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

List<String> textList = <String>[
  'Hi',
  'How are you',
  'I use fastLineSeries for real time data without setting interval/min/max on the primary Y-axis. It all works fine',
  'You can achieve your requirement with the help of the rangePadding property in the NumericAxis it will help you to eliminate the unwanted range in the axis and calculate the range based on the visible point. We have shared the related UG documentation below for your reference.',
  'Welcome to Flutter',
];

List<Icon> icons = const <Icon>[
  Icon(color: Colors.red, Icons.circle),
  Icon(color: Colors.blue, Icons.rectangle),
  Icon(color: Colors.green, Icons.access_alarm),
  Icon(color: Colors.yellow, Icons.star),
  Icon(color: Colors.brown, Icons.pentagon),
];

class _MyHomePageState extends State<MyHomePage> {
  _MyHomePageState();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SizedBox(
            height: 400,
            child: Wrap(
              children: List<Widget>.generate(
                textList.length,
                (int index) {
                  return _buildRowWidget(index);
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}

Widget _buildRowWidget(int index) {
  List<Widget> child = <Widget>[
    icons[index],
    const SizedBox(width: 5),
    Text(
      textList[index],
      style: const TextStyle(overflow: TextOverflow.ellipsis),
    ),
  ];
  return Row(children: child);
}

<img width="360" alt="image" src="https://user-images.githubusercontent.com/82077349/230908971-611fd536-7753-4654-8672-bd787024d333.png">

`
