### ISSUE TITLE
[webview_flutter]  for android  Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording

### ISSUE THREAD

**Issue by ningchanglong** [flutter/flutter#140624] opened 2023-12-26 19:49 UTC
### Steps to reproduce

<uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

Set the above permissions

Use the webview_flutter demo

### Code sample

<uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

Set the above permissions

Use the webview_flutter demo

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

<uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

Set the above permissions

Use the webview_flutter demo

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Logs

<uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

Set the above permissions

Use the webview_flutter demo

### Flutter Doctor output

<uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

Set the above permissions

Use the webview_flutter demo

**Comment by dam-ease** [comment] 2023-12-28 10:03
Hi @ningchanglong  
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:


- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps


I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-12-28 10:03 UTC
Labels: in triage
