### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by cjsmocjsmo** [flutter/flutter#115873] opened 2022-11-22 22:41 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:201:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:185:25)

**Comment by danagbemava-nc** [comment] 2022-11-24 05:57
Closing this as a duplicate of https://github.com/flutter/flutter/issues/115433. 

Kindly follow up in the issue linked above for updates. 

Please upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2022-11-24 05:57 UTC
Labels: in triage
