### ISSUE TITLE
Exit when create flutter project with OS Error: Access is denied. , errno = 5

### ISSUE THREAD

**Issue by DTharaka** [flutter/flutter#69978] opened 2020-11-06 20:11 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by hamdikahloun** [comment] 2020-11-06 20:42
Hi @DTharaka 

Can you please provide your `flutter create -v newapp` .

Thank you

**Comment by hamdikahloun** [comment] 2020-11-07 09:24
Hi @DTharaka 

Can you please provide the full log of your `flutter build -v apk --debug` and your ` flutter doctor -v` too .

Thank you

**Comment by iapicca** [comment] 2020-11-28 18:52
possible duplicate of https://github.com/flutter/flutter/issues/69116

**Closed** 2020-11-28 19:43 UTC
Labels: waiting for customer response
