### ISSUE TITLE
Camera Plugin Stream is rotated 90 degree on iPhone since 0.7.0

### ISSUE THREAD

**Issue by maxp89** [flutter/flutter#76210] opened 2021-02-17 14:17 UTC
After an upgrade of the Camera Plugin to version 0.7.0 and later, the `CameraImage` from `startImageStream` is 90 degrees CCW rotated.

This leads to unexpected and unfavorable behavior for further processing the CameraImage with MLKit/others.
For example, a user has to turn its smartphone or paper 90 degree ccw in order to get a good result with MLKit on iOS.

## Steps to Reproduce

Please have a look inside this StackOverflow ticket. This includes the source-code as well as the results (from version 0.7.0+2 and 0.6.4+5). Basically it is the Example source code but with `controller.buildPreview()`instead of the `CameraPreview`widget.
[https://stackoverflow.com/questions/66225051/flutter-camera-package-stream-picture-from-camera-is-90-rotated/66243581#66243581
](https://stackoverflow.com/questions/66225051/flutter-camera-package-stream-picture-from-camera-is-90-rotated/66243581#66243581
)

**Comment by pedromassangocode** [comment] 2021-02-17 14:30
Hi @maxp89 
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by maxp89** [comment] 2021-02-17 14:47
Sure.
```

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale de-DE)
    • Flutter version 1.22.6 at /Users/max/workspaces/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/max/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone von Max (mobile) • .... • ios • iOS 14.4
    ! Error: iPad von Max is not connected. Xcode will continue when iPad von Max is connected. (code -13)

! Doctor found issues in 1 category.

```

**Comment by pedromassangocode** [comment] 2021-02-18 13:54
The issue is reproducible with latest version of the camera plugin.

| camera: ^0.7.0+2 | camera: ^0.6.4+5 |
|-|-|
|![IMG-0637](https://user-images.githubusercontent.com/67424416/108366252-72fddd00-71f8-11eb-9769-edb79fc56296.PNG)|![IMG-0638](https://user-images.githubusercontent.com/67424416/108366249-72654680-71f8-11eb-9dd8-4653e216b826.PNG)|




<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.43, on Mac OS X 10.15.4 19E2269
  darwin-x64, locale en-IN)
  • Flutter version 1.27.0-5.0.pre.43 at
   /Users/dhs/documents/Fluttersdk/flutter
  • Framework revision 341984237e (5 hours ago), 2021-02-17 19:46:04 -0800
  • Engine revision 6993cb229b
  • Dart version 2.13.0 (build 2.13.0-30.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
  • Android SDK at /Users/dhs/Library/Android/sdk
  • Platform android-30, build-tools 30.0.0
  • Java binary at: /Applications/Android
   Studio.app/Contents/jre/jdk/Contents/Home/bin/java
  • Java version OpenJDK Runtime Environment (build
   1.8.0_242-release-1644-b3-6915495)
  • All Android licenses accepted.
[!] Xcode - develop for iOS and macOS
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Xcode 12.3, Build version 12C33
  ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
    CocoaPods is used to retrieve the iOS and macOS platform side's plugin
    code that responds to your plugin usage on the Dart side.
    Without CocoaPods, plugins will not work on iOS or macOS.
    For more info, see https://flutter.dev/platform-plugins
   To upgrade see
   https://guides.cocoapods.org/using/getting-started.html#installation for
   instructions.
[✓] Chrome - develop for the web
  • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
  • Android Studio at /Applications/Android Studio.app/Contents
  • Flutter plugin can be installed from:
   🔨 https://plugins.jetbrains.com/plugin/9212-flutter
  • Dart plugin can be installed from:
   🔨 https://plugins.jetbrains.com/plugin/6351-dart
  • Java version OpenJDK Runtime Environment (build
   1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
  • VS Code at /Applications/Visual Studio Code.app/Contents
  • Flutter extension version 3.18.1
[✓] Connected device (3 available)
  • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
   • iOS 14.2
  • macOS (desktop)      • macos                  •
   darwin-x64   • Mac OS X 10.15.4 19E2269 darwin-x64
  • Chrome (web)       • chrome                  •
   web-javascript • Google Chrome 88.0.4324.182
! Doctor found issues in 1 category.
```
</details>

**Comment by cyanglaz** [comment] 2021-02-18 19:08
cc @mvanbeusekom

**Comment by mvanbeusekom** [comment] 2021-02-19 14:08
I'll be looking into it. Thanks for reporting the bug and the heads up.

**Comment by gibahjoe** [comment] 2021-03-07 17:45
Hi, any workaround while the PR is waiting to be merged?

**Comment by maxp89** [comment] 2021-03-09 15:25
> Hi, any workaround while the PR is waiting to be merged?
> 
> I tried `await controller.lockCaptureOrientation(DeviceOrientation.portraitUp);` but no luck

So far, using an older Version helped as a workaround. However, you will find incompatibilities, if you use other libs that are "newer" than those from inside the camera package.

camera: ^0.6.4+5

**Closed** 2021-03-24 14:35 UTC
Labels: P4, found in release: 1.27, has reproducible steps, p: camera, p: first party, platform-ios, plugin, severe: regression
