### ISSUE TITLE
Flutter web intermittently only renders the very first frame of the app in profile/release builds

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#69313] opened 2020-10-29 16:41 UTC
I came across this in DevTools when embedded inside VS Code (https://github.com/Dart-Code/Dart-Code/issues/2852). Sometimes it would just render a tiny blue square where the app should be:

<img width="712" alt="Screenshot 2020-10-27 at 09 50 58" src="https://user-images.githubusercontent.com/1078012/97285313-f3f42b80-1839-11eb-9e17-f23a6166c6ad.png">

After much trial and error, I've managed to reproduce this in a simple Flutter app outside of VS Code:

![Screenshot 2020-10-29 at 16 29 47](https://user-images.githubusercontent.com/1078012/97603100-fdc98a80-1a03-11eb-85d7-a28b38c2f5f6.png)

This turns out to be only the first frame rendering, and then nothing more. The small square is the first frame of the `CircularProgressIndicator` rendered by the app. There are no errors or warnings listed in the Chrome developer tools/console.

It's pretty intermittent, but here's my steps:

- `flutter create foo`
- replace `lib/main.dart` with [this simple app](https://gist.github.com/DanTup/af9f33413c2179ec7b6230d0712fa94b#file-main-dart) which renders a `CircularProgressIndicator` and then changes to a `Text` widget after 500ms.
- build the app with `flutter build web --profile`
- run the app through a web server, for ex with `cd build/web && python3 -m http.server`
- open the app in your browser

If you're lucky, it will just happen first time. Otherwise, you can press refresh repeatedly until it happens.

It seems to occur more frequently when I do one or more of the following:

- Open Chrome developer tools, go to Application and click "Clear site data"
- Copy the URL, navigate to another website, then paste the URL back into the address bar and press <enter>

It seems like a race I wonder if it might be related to the service worker (only because it *seems* more common after clearing the data - though it could just be something else cached that alters timing).

I littered the Flutter code with some `prints` to see if anything different was happening, and noticed that when this *does* happen, the call to `scheduleBuildFor()` triggered by the `setState()` call skips over the call to `onBuildScheduled`, though I don't understand this code enough to know if that's relevant (or always the case):

<img width="652" alt="Screenshot 2020-10-29 at 14 12 35" src="https://user-images.githubusercontent.com/1078012/97585260-db7a4180-19f0-11eb-857a-1e40653a5566.png">

- Flutter version is master / Framework • revision 13896b3bd1 (14 hours ago)
- OS is macOS Catalina (10.15.7 19H2)
- Chrome is 86.0.4240.111 (Official Build) (x86_64) / Revision `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`

**Comment by DanTup** [comment] 2020-10-29 16:56
I tried removing the service worker JS from index.html, unregistered the service and then reproducing - and it did. So this seems unrelated to the service worker.

**Comment by DanTup** [comment] 2020-10-29 17:06
I published the build output here:

https://blog.dantup.com/flutter-repro-69313/#/

And with some refreshing, it occurs there too (it did take 20-30 refreshes though):

![Screenshot 2020-10-29 at 17 06 08](https://user-images.githubusercontent.com/1078012/97607634-24d68b00-1a09-11eb-908c-4fd41c42bf65.png)

**Comment by TahaTesser** [comment] 2020-10-30 11:04
I was able to reproduce after 15-20 refreshes


Deployed
https://optimistic-mclean-e229a1.netlify.app/#/

![image](https://user-images.githubusercontent.com/48603081/97697721-69c3f580-1acd-11eb-9dd5-fddd2582a9d0.png)
![image](https://user-images.githubusercontent.com/48603081/97697783-7fd1b600-1acd-11eb-90d5-e0253f16151a.png)

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() async {
  runApp(const MyApp());
}

final _theme = ThemeData.dark().copyWith(
  accentColor: Colors.green,
  backgroundColor: Colors.blue,
  scaffoldBackgroundColor: Colors.red,
);

@immutable
class MyApp extends StatefulWidget {
  const MyApp();

  @override
  State<MyApp> createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Builder(
      builder: (context) {
        return MaterialApp(
          title: 'Dart DevTools',
          theme: _theme,
          onGenerateRoute: (settings) => MaterialPageRoute(
              settings: settings, builder: (_) => MyInitializer()),
        );
      },
    );
  }
}

class MyInitializer extends StatefulWidget {
  @override
  _MyInitializerState createState() => _MyInitializerState();
}

class _MyInitializerState extends State<MyInitializer> {
  bool _isLoaded = false;

  @override
  Widget build(BuildContext context) => _isLoaded
      ? const Text('LOADED SCREEN')
      : const Scaffold(body: Center(child: CircularProgressIndicator()));

  @override
  void initState() {
    super.initState();

    Future.delayed(const Duration(milliseconds: 500)).then(
      (_) {
        _isLoaded = true;
        setState(() {});
      },
    );
  }
}

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-4.0.pre.165, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.24.0-4.0.pre.165 at C:\Code\flutter_master
    • Framework revision e444b1e3fa (6 hours ago), 2020-10-30 00:41:52 -0400
    • Engine revision 99cc50dfff
    • Dart version 2.11.0 (build 2.11.0-266.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.51

• No issues found!
```

</details>

**Comment by devoncarew** [comment] 2020-11-04 19:26
cc @yjbanov @mariamhas

**Comment by ferhatb** [comment] 2020-12-02 21:13
@devoncarew , any stack trace in console?

**Comment by DanTup** [comment] 2020-12-02 21:24
@ferhatb there are no errors in the dev console when this happens (I built this page with a lot of print statements, but it repros without):

<img width="1440" alt="Screenshot 2020-12-02 at 21 23 09" src="https://user-images.githubusercontent.com/1078012/100933007-9d3adb00-34e4-11eb-99de-6c9678ccfc59.png">

My sample is here: https://blog.dantup.com/flutter-repro-69313/#/ - you may need to refresh it 10-20 times for it to occur.

**Comment by yjbanov** [comment] 2020-12-04 02:58
Yep, I see it happening after a few refreshes.

**Comment by yjbanov** [comment] 2020-12-04 03:09
This is reproducible in a non-canvaskit build, so I'm removing the cavaskit label. Comparing the output from the print statements that @DanTup added, the framework does indeed sometimes decide to go through a different codepath. For example, when the bug happens the output contains:

```
...
main.dart.js:7628 because _scheduledFlushDirtyElements_MediaQueryFromWindowsState
...
main.dart.js:7628 inside flutter setState of _MediaQueryFromWindowsState
main.dart.js:7628 calling element.markNeedsBuild for _MediaQueryFromWindowsState
...
```

These lines are not printed when the app loads normally. A good place to start debugging this is to figure out what conditions cause it to ping `_MediaQueryFromWindowsState`.

Leaving it as P3, as this is a pretty severe bug. We should be able to write an integration test for this too, just reload the app 100 times and take the screenshot of the first frame, compare with the golden.

**Comment by DanTup** [comment] 2020-12-04 07:45
Not much more detail, but in the original issue I had [this comment about a difference](https://github.com/Dart-Code/Dart-Code/issues/2852#issuecomment-718783000) the difference in code paths:

---

I added some prints throughout Flutter, and found that whenever this happens, it's when this code in `scheduleBuildFor` skips over calling `onBuildScheduled`. I don't completely understand how this code works to know whether that's important though.

<img width="652" alt="Screenshot 2020-10-29 at 14 12 35" src="https://user-images.githubusercontent.com/1078012/97585260-db7a4180-19f0-11eb-857a-1e40653a5566.png">

**Comment by yjbanov** [comment] 2020-12-10 20:35
After some additional print debugging my current conclusion is that the issue is a race between the warm-up frame and the first real scheduled frame. The warm-up frame is implemented via a pair of timers, one for `handleBeginFrame`, and one for `handleAnimationFrame`. Currently, dart2js/DDC do not make the same guarantees as the VM, allowing the `Window.scheduleFrame()` to fire between the timers.

Here's a draft for a workaround: https://github.com/flutter/flutter/pull/72088/files. However, I don't like it due to the following reasons:

- It relies on zones, which are complex and error-prone. Zones can be easily bypassed via `Zone.root` or `Zone.parent`.
- It does not the solve the underlying issue with the discrepancy between the VM and dart2js, which means the Flutter users will have to deal with this quirk in their code.

I'm also bumping the priority of this issue to P2, because being able to launch an app only _sometimes_ is not an option.

**Comment by yjbanov** [comment] 2020-12-11 03:51
https://github.com/flutter/flutter/pull/72115 -- an alternative fix, one that doesn't use zones. It's still unclear to me though why the animation halts without a real engine frame (i.e. not the warm-up frame), but at least the fix guarantees that if the app requested an engine frame, it will get one, in addition to the warm-up frame. Previously you'd either get a warm-up frame + engine frame (common case), or just the warm-up frame and no engine frame (uncommon case). I can see how this randomness can lead to flakiness, which the PR should fix.

**Comment by goderbauer** [comment] 2020-12-15 19:33
To document what we found in the unhappy case:

* The warm-up frame's handleBeginFrame runs
* transient callbacks for that frame execute
* another frame is scheduled
* transient callbacks for that frame are scheduled
* the newly scheduled frame wants to run between the warm-up's frame handleBeginFrame and handleDrawFrame
* It is cancelled (without setting _hasScheduledFrame back to false), its transient callbacks therefore never run
* the warm-up frames handleDrawFrame executes

At this point, the app is stuck and we do not produce another frame, ever, because:
- when somebody tries to schedule a frame with scheduleFrame we ignore that request because we think another frame is already scheduled (_hasScheduledFrame is still true, but that frame was cancelled and will never be produced).
- even if we were to reset _hasScheduledFrame, we still may not produce another frame if it is triggered by the transient callbacks scheduled for the cancelled frame (since those callbacks never run).

@yjbanov Is that a good summary of what we chatted about yesterday?

**Comment by yjbanov** [comment] 2020-12-15 19:58
In a chat with @goderbauer we decided to go with the https://github.com/flutter/flutter/pull/72115.

**Comment by yjbanov** [comment] 2020-12-15 20:05
> @yjbanov Is that a good summary of what we chatted about yesterday?

:+1:

**Comment by yjbanov** [comment] 2020-12-16 00:55
Fixed by https://github.com/flutter/flutter/pull/72115

**Closed by yjbanov** 2020-12-16 00:55 UTC
Labels: P2, customer: ddt, customer: web10, engine, found in release: 1.24, has reproducible steps, platform-web, severe: rendering
