### ISSUE TITLE
text_field_focus_test is flaky

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16355] opened 2018-04-08 20:49 UTC
### Observed on AppVeyor (Windows)

Originally observed on https://github.com/flutter/flutter/pull/16343.  Resolved itself when the AppVeyor build was restarted.

```
02:16 +842 ~2: C:\projects\flutter sdk\packages\flutter\test\material\text_field_focus_test.dart: - Dialog interaction
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the RenderPadding class returned values that violate the
intrinsic protocol contract.
The following failures was detected:
 * getMinIntrinsicWidth(Infinity) returned a larger value (168.0) than
   getMaxIntrinsicWidth(Infinity) (120.0)
 * getMinIntrinsicWidth(280.0) returned a larger value (168.0) than getMaxIntrinsicWidth(280.0)
   (120.0)
If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1762:11)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1772:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1507:17)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1507:65)
#4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:202:5)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#6      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#8      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:257:13)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#10     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:625:13)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#17     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1141:11)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#19     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:257:13)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#21     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#23     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#25     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#38     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2716:13)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#40     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:509:15)
#41     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
#42     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
#43     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:613:23)
#44     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#45     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#46     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#47     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:578:9)
#50     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#51     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:566:27)
#52     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:215:47)
#55     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#56     WidgetTester.pump (package:flutter_test/src/widget_tester.dart:215:27)
#57     main.<anonymous closure> (file:///C:/projects/flutter%20sdk/packages/flutter/test/material/text_field_focus_test.dart:116:18)
#71     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:660:16)
#72     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:466:5)
#73     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:646:24)
#79     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:644:16)
#80     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:62:24)
#81     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
#93     Declarer._runSetUps (package:test/src/backend/declarer.dart)
(elided 51 frames from class _FakeAsync, package dart:async, and package stack_trace)

The following RenderObject was being processed when the exception was fired:
  RenderPadding#39c83 relayoutBoundary=up8 NEEDS-PAINT
  creator: Padding ← Column ← ConstrainedBox ← IntrinsicWidth ← DefaultTextStyle ←
  AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#68093 ink renderer] ←
  NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← PhysicalShape
  ← _MaterialInterior ← ⋯
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(w=280.0, 0.0<=h<=Infinity)
  size: Size(280.0, 44.0)
  padding: EdgeInsets(24.0, 24.0, 24.0, 0.0)
  textDirection: ltr
This RenderObject had the following child:
  RenderParagraph#0e9d5 relayoutBoundary=up9 NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Hixie** [comment] 2018-08-04 00:14
Dupe of https://github.com/flutter/flutter/issues/19696

**Closed by Hixie** 2018-08-04 00:14 UTC
Labels: team, team: flakes
