### ISSUE TITLE
hot reload and hot restart not working

### ISSUE THREAD

**Issue by rohitsainik** [flutter/flutter#58186] opened 2020-05-28 19:08 UTC
I really don't know what happened after I updated flutter, hot restart and hot reload are not working ln IntelliJ whenever i reload or restart the app after any edit not change is shown due to which i have to restart the application again like I am developing an android app

**Comment by aayanraja210** [comment] 2020-05-28 21:34
What Flutter channels have you tried?

**Comment by iapicca** [comment] 2020-05-29 08:12
Hi @rohitsainik 
If you are experiencing the issue only with Android Studio or IntelliJ and not with VS Code, then following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Otherwise, please provide your ´flutter doctor - v´ output.
Thank you

**Comment by rohitsainik** [comment] 2020-05-29 10:20
> What Flutter channels have you tried?

stable

**Comment by rohitsainik** [comment] 2020-05-30 08:36
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.17.2 at C:\flutter
    • Framework revision 5f21edf8b6 (2 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\MY PC\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected device (1 available)
    • MI MAX 2 • 192.168.43.1:5555 • android-arm64 • Android 7.1.1 (API 25)

**Comment by iapicca** [comment] 2020-06-01 06:33
Hi @rohitsainik 
I see there's an open [issue](https://github.com/flutter/flutter/issues/51853) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-01 06:34 UTC
Labels: in triage
