### ISSUE TITLE
Go_Router - Navigate to specific route or initial route when 404 page found.

### ISSUE THREAD

**Issue by MungaraJay** [flutter/flutter#108517] opened 2022-07-28 06:28 UTC
Hello There,

I was writing my flutter web app using navigator with [go_router](https://pub.dev/packages/go_router) 4.2.2,

Following is my **'errorPageBuilder'** for my GoRouter when a url path doesn't match,

```
errorPageBuilder: (context, state) => MaterialPage(
        key: state.pageKey,
        child: Scaffold(
            body: Center(
                child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Image.asset(AppImage.imgAppError,
                height: 250, width: 250, fit: BoxFit.cover),
            const SizedBox(height: 8),
            const Text('Page Not Found!',
                style: TextStyle(
                    color: AppColor.black,
                    fontSize: 32,
                    fontWeight: FontWeight.bold)),
            const SizedBox(height: 16),
            ElevatedButton(
                onPressed: () {
                  GoRouter.of(context).go('/');
                },
                style: ElevatedButton.styleFrom(
                    primary: AppColor.primary,
                    padding: const EdgeInsets.symmetric(
                        horizontal: 32, vertical: 16)),
                child: const Text('Go To Home',
                    style: TextStyle(
                        color: AppColor.white,
                        fontSize: 24,
                        fontWeight: FontWeight.w500))),
            // Text('ErrorPageBuilder ${state.error.toString()}'),
          ],
        ))))
```

So, what I want to achieve is, Let say I'm on web url path 'localhost/home' at the moment which is path specified in my GoRouter routes. Now, if I try to access the following url 'localhost/home/test' which is not found in my GoRouter routes. So, It will redirect my website to errorPageBuilder widget. But, when I try to redirect it to my initial location from **'Go To Home'** Button onTap, it gives me an error log like,

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
Assertion failed: file:///Users/jaym/Documents/JayM/flutter/.pub-cache/hosted/pub.dartlang.org/go_router-4.2.1/lib/src/router.dart:251:12
inherited != null
"No GoRouter found in context"

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/go_router/src/router.dart 251:21                                     of
packages/flutter_follow_up/main.dart 74:40                                    <fn>
packages/flutter/src/material/ink_well.dart 1005:21                           [_handleTap]
packages/flutter/src/gestures/recognizer.dart 198:24                          invokeCallback
packages/flutter/src/gestures/tap.dart 613:48                                 handleTapUp
packages/flutter/src/gestures/tap.dart 298:5                                  [_checkUp]
packages/flutter/src/gestures/tap.dart 232:7                                  handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 563:9                           handleEvent
packages/flutter/src/gestures/pointer_router.dart 94:12                       [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 139:9                       <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
packages/flutter/src/gestures/pointer_router.dart 137:17                      [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 123:7                       route
packages/flutter/src/gestures/binding.dart 445:19                             handleEvent
packages/flutter/src/gestures/binding.dart 425:14                             dispatchEvent
packages/flutter/src/rendering/binding.dart 329:11                            dispatchEvent
packages/flutter/src/gestures/binding.dart 380:7                              [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 344:5                              handlePointerEvent
packages/flutter/src/gestures/binding.dart 302:7                              [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 285:32                             [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1105:13                           invoke1
lib/_engine/engine/platform_dispatcher.dart 185:5                             invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 130:39                                [_onPointerData]
lib/_engine/engine/pointer_binding.dart 543:18                                <fn>
lib/_engine/engine/pointer_binding.dart 496:21                                <fn>
lib/_engine/engine/pointer_binding.dart 210:16                                loggedHandler
Handler: "onTap"
Recognizer: TapGestureRecognizer#38461
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(470.2, 478.9)
  finalLocalPosition: Offset(124.2, 18.4)
  button: 1
  sent tap down
====================================================================================================
```

So, how can I redirect it to initial path in flutter ?

Also, is it possible to pop all web pages and redirect to my initial page anyway in flutter web using go_router?

Any help would be appreciated.

**Comment by Skogsfrae** [comment] 2022-07-28 10:13
It's a duplicate of https://github.com/flutter/flutter/issues/108144

**Comment by maheshmnj** [comment] 2022-07-28 11:36
Hi @MungaraJay, Thanks for filing the issue. I believe you could handle that manually right now in error builder something like this

/// this condition may not be appropriate
```dart
 errorBuilder: (context, state) {
      if (condition) {
        return Home();
      }else{
         return YourCustomErrorWidget();
      }
``` 

Also, this issue  https://github.com/flutter/flutter/issues/108144 does seem to propose to handle error redirects.So I think we can close this issue as a duplicate.

**Comment by MungaraJay** [comment] 2022-07-28 12:28
@maheshmnj Can you please tell me in above case how can I remove my go_router stack clear and redirect my user to home page?

Will `context.go('/')` will work?

**Comment by Skogsfrae** [comment] 2022-07-28 15:00
@MungaraJay there are several reasons why it's not possible to navigate inside `errorBuilder`:
* `errorBuilder` must return a widget without performing any navigation
* `errorBuilder` is executed during the build frame so it's not possible to perform a navigation
* the context used inside `errorBuilder` is outside GoRouter inherited widget, so it's not possible to use `GoRouter.of(context)`

Waiting for https://github.com/flutter/flutter/issues/108144 a workaround is still possible though it's not the most elegant solution.

```dart
// you have to assign your GoRouter instance to a variable in order
// to make it accessible to errorBuilder body
final router = GoRouter(
  routes: $appRoutes,
  debugLogDiagnostics: true,
  errorBuilder: (context, state) {
    // use a post frame callback to perform your navigation after
    // the build frame has finished
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      router.go('/');
    });

    // you must return a widget anyway
    return const SizedBox.shrink();
  }
);
```

**Comment by maheshmnj** [comment] 2022-07-29 06:14
@MungaraJay  @Skogsfrae is right you cannot navigate while the build is in process, Perhaps you can add some delay or navigate post frame as stated above. But I think your use case can be solved by this issue  https://github.com/flutter/flutter/issues/108144.
 Closing in favor of the linked issue. If you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-07-29 06:14 UTC
Labels: in triage
