### ISSUE TITLE
Flutter doesn't clean memory after failing to compile for Android

### ISSUE THREAD

**Issue by Mattew05** [flutter/flutter#102730] opened 2022-04-28 08:08 UTC
This says it all
![Untitled2](https://user-images.githubusercontent.com/20031235/165706741-3d49f26e-084a-4939-abae-b9763393b1d0.png)

This is my code, everything else is created by default, didn't touch it
![Capture](https://user-images.githubusercontent.com/20031235/165707006-f219ae25-ce1f-43b9-b7b8-6334e63be773.PNG)

Flutter doctor in case you need it
![Capture](https://user-images.githubusercontent.com/20031235/165707126-95ed329d-4547-48d1-8e64-b9b6dd5b4b5a.PNG)

**Comment by maheshmnj** [comment] 2022-04-28 11:12
Hi @Mattew05, thanks for filing the issue. I am unable to reproduce the issue. I see the memory getting released when the build fails. Please see the below output   



https://user-images.githubusercontent.com/31410839/165739779-81bb6eb5-838c-4a76-b0f8-d722bae4c8f9.mp4

Does this happen when you compile for any specific platform? I verified when compiling for Android and chrome.


<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
    • Flutter version 2.10.5 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Mattew05** [comment] 2022-04-28 17:15
It only happens when i build for android, windows applications and web ones work fine, i tried using my phone connected with a cable and the emulator from android studio and here is the issue recreated using the emulator from android studio https://youtu.be/xyTF-ClPKJA

**Comment by maheshmnj** [comment] 2022-04-29 06:44
Thanks for the update @Mattew05, But I am unable to reproduce the issue even when building for the Android emulator. I see the allocated memory being cleaned on build failure. 



https://user-images.githubusercontent.com/31410839/165896246-0b6a299f-a9c6-4bd8-bd00-5c53d9721ae3.mp4



 However, I am able to see any difference in the environment of both of our machines that might be causing this issue. Can ou check if the memory remains allocated for other emulators or Physical Android devices too?

Labeling this issue for further investigation from the team.


<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
    • Flutter version 2.10.5 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


<details>
<summary>code sample</summary>

```console
flutter pub add english_words
```

```dart
import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final wordPair = WordPair.random(); 
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: const Center(
			child: Text(wordPair.asPascalCase),
        ),
      ),
    );
  }
}
```
</details>

**Comment by Mattew05** [comment] 2022-04-29 08:34
The only things I have to add is that I had problems with getting flutter doctor to see the java version and the steps that I went through were: reinstalling android studio 2 times, changing the java_home path to jdk instead of the default jre and deleting the old android studio folders. When I tried compiling while it wasn't seeing the java version it was giving me the same error as now:

C:\Users\matei\Desktop\startup_namer>flutter` run
Launching lib\main.dart on S88Pro in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Unable to find a usable idle daemon. I have connected to 100 different daemons but I could not use any of them to run the build. BuildActionParameters were DefaultBuildActionParameters{, currentDir=C:\Users\matei\Desktop\startup_namer\android, systemProperties size=55, envVariables size=65, logLevel=QUIET, useDaemon=true, continuous=false, injectedPluginClasspath=[]}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Running Gradle task 'assembleDebug'...                            252.2s
Exception: Gradle task assembleDebug failed with exit code 1

Android Studio works fine, can't recreate the error in it though due to the nature of it.

Flutter doctor -v:

C:\Users\matei>flutter doctor -v
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
    • Flutter version 2.10.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (11 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\matei\AppData\Local\Android\sdk
    • Platform android-31, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\matei\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • S88Pro (mobile)   • E977UA1ZM18160624 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows           • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge              • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by blasten** [comment] 2022-05-10 17:37
I'd suggest asking this question on stackoverflow. If you do ask there, please close this issue as well. Thanks!

**Closed** 2022-05-16 08:07 UTC
Labels: platform-android, tool, a: build, perf: memory, needs repro info
