### ISSUE TITLE
FlutterPluginAppLifeCycleDelegateTest testWillEnterForeground is flaky

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#68485] opened 2020-10-19 15:25 UTC
On an unrelated commit (f7da9d687d37e814fce71e768d11a5536182b052), it crashed with:
```
2020-10-18 00:23:40.982895-0700 IosUnitTests[38379:327388] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSSet ocmock_replaced_setWithObjects:count:]: unrecognized selector sent to class 0x1026c6fb0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001023fabde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x0000000101896b20 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010241b604 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00000001023ff7Test Case '-[FlutterPluginAppLifeCycleDelegateTest testDidEnterBackground]' passed (0.001 seconds).
bc ___forwarding___ + 1436
	4   CoreFoundation                      0x00000001024016c8 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x000000010240195c __invoking___ + 140
	6   CoreFoundation                      0x00000001023fed8f -[NSInvocation invoke] + 287
	7   CoreFoundation                      0x00000001023ff566 ___forwarding___ + 838
	8   CoreFoundation                      0x00000001024016c8 _CF_forwarding_prep_0 + 120
	9   CoreFoundation                      0x00000001024212f6 -[NSSet setByAddingObjectsFromSet:] + 710
	10  DTXConnectionServices               0x000000011d63f0c2 -[DTXProxyChannel _allowedClassesForReturnValues] + 109
	11  DTXConnectionServices               0x000000011d63f7ee __42-[DTXProxyChannel _sendInvocationMessage:]_block_invoke + 260
	12  DTXConnectionServices               0x000000011d64c8d2 __51-[DTXChannel _scheduleMessage:tracker:withHandler:]_block_invoke.617 + 159
	13  libdispatch.dylib                   0x0000000103223888 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00000001032247f9 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x000000010322a566 _dispatch_lane_serial_drain + 707
	16  libdispatch.dylib                   0x000000010322af9c _dispatch_lane_invoke + 388
	17  libdispatch.dylib                   0x000000010323506c _dispatch_workloop_worker_thread + 626
	18  libsystem_pthread.dylib             0x00007fff5141fa3d _pthread_wqthread + 290
	19  libsystem_pthread.dylib             0x00007fff5141eb77 start_wqthread + 15
)
Test Case '-[FlutterPluginAppLifeCycleDelegateTest testWillEnterForeground]' started.
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by dnfield** [comment] 2020-10-19 15:37
Probably related to https://github.com/flutter/flutter/issues/67603

**Comment by gaaclarke** [comment] 2020-10-19 21:47
duplicate of https://github.com/flutter/flutter/issues/67603

**Closed by gaaclarke** 2020-10-19 21:47 UTC
Labels: P3, a: tests, engine, passed first triage, team, team: flakes
