### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect., errno = 123

### ISSUE THREAD

**Issue by salahamara** [flutter/flutter#127651] opened 2023-05-26 09:33 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:244:64)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:

**Comment by huycozy** [comment] 2023-05-26 09:58
Closing as duplicate of https://github.com/flutter/flutter/issues/99954.

**Closed by huycozy** 2023-05-26 09:58 UTC
Labels: in triage
