### ISSUE TITLE
Text widget not rendering line breaks correctly on iOS

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#47980] opened 2019-12-30 13:26 UTC
Hi, I'm pulling some data from a custom build API, it has some text in it with line breaks. If I render this text in a flutter TextWidget the line breaks get reandered with [x], but only on ios, on android it renders correctly. Any advice?
<img width="278" alt="Screenshot 2019-12-30 at 05 20 29" src="https://user-images.githubusercontent.com/51141584/71583830-f0323400-2ac4-11ea-84cc-5da35a8513c7.png">

**Comment by iapicca** [comment] 2019-12-30 14:57
Hi @jellyNoone 
can you please provide your `flutter doctor -v` 
and a minimal code sample
or the steps to reproduce the problem?
Thank you

**Comment by jellyNoone** [comment] 2019-12-31 08:14
Hi, sorry for the wait, had to replicate the issue on a smaller scale.

Flutter doctor -v output:
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/jellynoone/Desktop/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jellynoone/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 9810561E-B5B3-4139-AB6D-AF0ACABF1032 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
[ios-render-line-breaks.zip](https://github.com/flutter/flutter/files/4012187/ios-render-line-breaks.zip)

**Comment by jellyNoone** [comment] 2019-12-31 08:17
I've attached the minimal code sample. The problem occures if you set the fontWeight of a Text widget to less then the default w400. In production the json format is fetched from the server, I've added a static asset that simulates the job.

**Comment by iapicca** [comment] 2019-12-31 09:36
thank you @jellyNoone

**Comment by jellyNoone** [comment] 2019-12-31 10:56
Sure, thing.

**Comment by jellyNoone** [comment] 2020-03-09 16:57
I'd like to share a discovery on this issue. While testing I discovered that the problem occures if I use \r\n while a regular \n works as expected and a single \r throws the [x]-s

**Comment by iapicca** [comment] 2020-03-13 13:54
HI @jellyNoone 
I'm sorry this took me forever,
I can reproduce 2 separate behaviours from 
mobile 
![image](https://user-images.githubusercontent.com/45637986/76626750-65e56200-6542-11ea-97c9-03b8cdbde258.png)
and web
![image](https://user-images.githubusercontent.com/45637986/76626915-b361cf00-6542-11ea-85d9-ad36675266c8.png)
using this [code sample](https://dartpad.dartlang.org/c3d50ddd7b341947000141c360795123)
thank you for reporting this issue

**Comment by TahaTesser** [comment] 2020-09-22 15:10
![Image from iOS](https://user-images.githubusercontent.com/48603081/93901086-c7696300-fd13-11ea-86a6-deab3b219458.png)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  static const String RNR_NO_WEIGHT = 'RNR No\r\n\r\nWeight';
  static const String RNR_WEIGHT_300 = 'RNR Weight\r\n\r\n300';
  static const String RNR_WEIGHT_800 = 'RNR Weight\r\n\r\n800';
  static const String N_NO_WEIGHT = 'N No\n\nWeight';
  static const String N_WEIGHT_300 = 'N Weight\n\n300';
  static const String N_WEIGHT_800 = 'N Weight\n\n800';
  @override
  Widget build(BuildContext context) => Scaffold(
        body: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                Center(
                  child: Text(
                    RNR_NO_WEIGHT,
                  ),
                ),
                Center(
                  child: Text(
                    RNR_WEIGHT_300,
                    style: TextStyle(fontWeight: FontWeight.w300),
                  ),
                ),
                Center(
                  child: Text(
                    RNR_WEIGHT_800,
                    style: TextStyle(fontWeight: FontWeight.w800),
                  ),
                ),
              ],
            ),
            Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                Center(
                  child: Text(
                    N_NO_WEIGHT,
                  ),
                ),
                Center(
                  child: Text(
                    N_WEIGHT_300,
                    style: TextStyle(fontWeight: FontWeight.w300),
                  ),
                ),
                Center(
                  child: Text(
                    N_WEIGHT_800,
                    style: TextStyle(fontWeight: FontWeight.w800),
                  ),
                ),
              ],
            ),
          ],
        ),
      );
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.281, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.281 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 511367aa5a (15 hours ago), 2020-09-21 15:33:32 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021 x86_64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2022-11-24 01:08
Hi @ghost, I am unable to reproduce the issue on the latest master channel. Looks like it is fixed. 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/31410839/203671872-db9bcdf1-0246-4adf-8850-3d03415c5fd4.png">

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  static const String RNR_NO_WEIGHT = 'RNR No\r\n\r\nWeight';
  static const String RNR_WEIGHT_300 = 'RNR Weight\r\n\r\n300';
  static const String RNR_WEIGHT_800 = 'RNR Weight\r\n\r\n800';
  static const String N_NO_WEIGHT = 'N No\n\nWeight';
  static const String N_WEIGHT_300 = 'N Weight\n\n300';
  static const String N_WEIGHT_800 = 'N Weight\n\n800';
  @override
  Widget build(BuildContext context) => Scaffold(
        body: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children:const <Widget>[
                Center(
                  child: Text(
                    RNR_NO_WEIGHT,
                  ),
                ),
                Center(
                  child: Text(
                    RNR_WEIGHT_300,
                    style: TextStyle(fontWeight: FontWeight.w300),
                  ),
                ),
                Center(
                  child: Text(
                    RNR_WEIGHT_800,
                    style: TextStyle(fontWeight: FontWeight.w800),
                  ),
                ),
              ],
            ),
            Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children:const<Widget>[
                Center(
                  child:  Text(
                    N_NO_WEIGHT,
                  ),
                ),
                Center(
                  child: Text(
                    N_WEIGHT_300,
                    style: TextStyle(fontWeight: FontWeight.w300),
                  ),
                ),
                Center(
                  child: Text(
                    N_WEIGHT_800,
                    style: TextStyle(fontWeight: FontWeight.w800),
                  ),
                ),
              ],
            ),
          ],
        ),
      );
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as fixed. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-11-24 01:08 UTC
Labels: platform-ios, framework, a: typography, has reproducible steps, found in release: 1.22
