### ISSUE TITLE
Image_Picker Causes Device Restart

### ISSUE THREAD

**Issue by NobleCT** [flutter/flutter#152857] opened 2024-08-05 09:40 UTC
using the image_picker , i have used  2 given  option one is for pick image from the user gallery and another is from the device camera, the pick-up from the user gallery  having no-problem , but while opening the camera the device gets restarts, check on multiple devices, , checked on physical device version like 8 and 12 no issue found but in 10 this issue encountered, any solution for this will be a great help, below are the dependencys uses,
 - image_picker: ^1.1.2,
 - permission_handler: ^11.1.0
 
 also checked the flutter docter-v , no issues found , without any single error marked this issue is happened,

**Comment by huycozy** [comment] 2024-08-05 11:06
This looks similar to https://github.com/flutter/flutter/issues/48016, please check https://github.com/flutter/flutter/issues/48016#issuecomment-971918009 for the applicable solution to see if it helps for you. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/48016. If you disagree, please open a new issue with all information indicated in [Flutter's first-party packages issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml) so that we have more information to investigate. Thanks!

**Closed by huycozy** 2024-08-05 11:06 UTC
Labels: in triage
