### ISSUE TITLE
Flutter support for variable font attribute FontFeature('wght', x) request

### ISSUE THREAD

**Issue by timbutler-ag** [flutter/flutter#87291] opened 2021-07-29 19:26 UTC
Internal: b/195883187

## Use case
A device platform using Flutter required us to establish and maintain a completely separate icon font (250±) just to use icons at a different size/weight from platform to platform.

## Proposal
Would like Flutter to add support for the weight attribute of variable fonts. It seems to support all other attributes other than weight.

**Comment by chinmaygarde** [comment] 2021-08-02 17:42
Per Jason, exposing the feature is easy enough. It would be good to have an instance of the font so we can verify the implementation.

**Comment by chinmaygarde** [comment] 2021-08-02 17:42
@Hixie I see the customer label. Can you cross reference with the internal issue so we can follow along on any internal discussions please?

**Comment by timbutler-ag** [comment] 2021-08-02 17:46
> Per Jason, exposing the feature is easy enough. It would be good to have an instance of the font so we can verify the implementation.

It would be the Google GM icons font. Nothing otherwise custom.

**Comment by jason-simmons** [comment] 2021-08-06 00:18
The `FontFeature` API only supports feature tags.

'wght' is a variation axis used by variable fonts.  Flutter does not currently support variable fonts, but this has been a longstanding feature request (https://github.com/flutter/flutter/issues/33709)

I looked into this and confirmed that Skia and the font shaping libraries used by Flutter can handle variable fonts.  As an experiment I tried patching Libtxt to use `SkFontArguments::setVariationDesignPosition` and `SkTypeface::makeClone` to create an `SkTypeface` based on an OpenType variable font.  The font rendered as expected.

More work will be required to expose this as an API.  This will also need to be supported in SkParagraph.

**Comment by chinmaygarde** [comment] 2021-08-09 17:41
This is going to be implemented in both the SkParagraph and libTXT backends.

**Comment by chinmaygarde** [comment] 2021-08-16 17:38
This doesn't seem to be a blocker just yet. It is on Jason's TODO list for later in the month. Adjusting priority.

**Comment by Hixie** [comment] 2021-08-17 20:09
Is it possible we can just skip the libtxt implementation?

**Comment by jason-simmons** [comment] 2021-08-17 21:11
Perhaps, although I don't expect that Libtxt-specific work would be a major part of the overall effort.

On the engine side we need to set up the API and verify that the font loading/rendering libraries that we are using work as intended with these features.  If we do a Libtxt implementation, it's mostly serving as a way to validate those parts and possibly for backward compatibility until everyone is migrated.

**Comment by davelab6** [comment] 2022-04-18 19:39
As https://github.com/flutter/flutter/pull/100978 is merged, can this be closed?

**Comment by guidezpl** [comment] 2022-05-05 14:33
Yea, I've created an issue for the remaining work. #103131

**Closed by guidezpl** 2022-05-05 14:33 UTC
Labels: engine, dependency: skia, a: typography, customer: dream (g3), passed first triage, P3
