### ISSUE TITLE
Ability to show action options (e.g. Share) from text selection menu

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4961] opened 2016-07-18 23:00 UTC
iOS:

![screen shot 2016-07-18 at 3 57 11 pm](https://cloud.githubusercontent.com/assets/5479/16933186/64c21098-4d00-11e6-9bc2-0897bd71b988.png)

Android:

![screen shot 2016-07-18 at 3 59 42 pm](https://cloud.githubusercontent.com/assets/5479/16933233/b2de07c8-4d00-11e6-82c1-f4c15b9e60a0.png)

Notice how there is a "Share..." option after text has been selected. That brings up the share panel.

**Comment by sethladd** [comment] 2016-07-18 23:01
@mpcomplete can we do this today?

**Comment by zoechi** [comment] 2018-12-28 14:09
Looks like a Duplicate of #3944

**Comment by gnprice** [comment] 2023-05-17 02:53
I think this is now subsumed by:
* #107578
* #107603

> actions provided by other apps (on iOS it's always just the current app, but on Android it might be other apps too?)

Yeah, on at least Android they can come from other apps. That part is #107603.


> can a developer add an option to this pop-up?

This one became #31412, and has been done.

**Closed by gnprice** 2023-05-17 02:53 UTC
Labels: a: text input, new feature, framework, a: fidelity, P4
