### ISSUE TITLE
in Windows use Android UX

### ISSUE THREAD

**Issue by au-top** [flutter/flutter#82422] opened 2021-05-13 06:16 UTC
I noticed that it is no longer possible to drag and scroll on windows,
  On ListView, only the scroll wheel can be used. Is this a bug or a Windows platform UX behavior? If you switch this platform behavior to Android

```

[√] Flutter (Channel master, 2.3.0-2.0.pre.107, on Microsoft Windows [Version 10.0.17763.1879], locale zh-CN)
    • Flutter version 2.3.0-2.0.pre.107 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 55354aa28b (2 days ago), 2021-05-11 03:24:03 -0700
    • Engine revision 5d3dde58ef
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\autopMateBook\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\androidstudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\androidstudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at D:\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code
    • VS Code at C:\Users\autopMateBook\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] VS Code, 64-bit edition (version 1.55.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (4 available)
    • FRL AN00a (mobile)                 • EYDNW20A27001031 • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows          • windows-x64    • Microsoft Windows [Version 10.0.17763.1879]
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome 90.0.4430.212

• No issues found!


```

**Comment by TahaTesser** [comment] 2021-05-13 09:23
Hi @au-top 
This is a recent change https://github.com/flutter/flutter/pull/81569, working as intended
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-13 09:23 UTC
Labels: in triage
