### ISSUE TITLE
Cann't delete characters after enter "Win" key.

### ISSUE THREAD

**Issue by Chuanbin-Wang** [flutter/flutter#87978] opened 2021-08-10 03:08 UTC
OS: Windows 10.
Flutter Version: latest stable .
Language: CN

A test app with only have a TextField widget.

In TextField, Input something with default en language. it's OK.
Then use Win+Space  switch IME to MS pinyin .
The entered characters cannot be deleted with "Backspace" key.

my temporary solution:
edit the sdk: raw_keyboard.dart .  _handleKeyEvent function. 
block the event dispatch if it's LogicalKeyboardKey.metaLeft or metaRight.

**Comment by TahaTesser** [comment] 2021-08-10 09:42
Hi @Chuanbin-Wang 
This is probably fixed by https://github.com/flutter/flutter/issues/73377

I can still reproduce on stable, however, it doesn't reproduce on the beta channel 

Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

Closing as duplicate of  https://github.com/flutter/flutter/issues/73377

**Closed by TahaTesser** 2021-08-10 09:42 UTC
Labels: in triage
