### ISSUE TITLE
Move examples to xcworkspace model?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8613] opened 2017-03-07 16:53 UTC
Our error message expect the xcworkspace model:
```
═══════════════════════════════════════════════════════════════════════════════════
Building an iOS app requires a selected Development Team with a Provisioning Profile
Please ensure that a Development Team is selected by:
  1- Opening the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- In the 'General' tab, make sure a 'Development Team' is selected

For more information, please visit:
  https://flutter.io/setup/#deploy-to-ios-devices

Or run on an iOS simulator
═══════════════════════════════════════════════════════════════════════════════════
Encountered error while building for device.
```

But many of our examples use xcodeproj instead of xcworkspace.

**Comment by cbracken** [comment] 2017-03-07 23:39
Dupe of #8062

**Closed by cbracken** 2017-03-07 23:39 UTC
Labels: ⌺‬ platform-ios
