### ISSUE TITLE
google_sign_in doesn't work with sign_in_with_apple

### ISSUE THREAD

**Issue by Flajt** [flutter/flutter#73646] opened 2021-01-09 15:40 UTC
Hello everybody,
as mentioned in the title I can't use google_sign_in with sign_in_with_apple.

How to reproduce:
Add: `google_sign_in:^4.5.9` and `sing_in_with_apple:^2.5.4` in the pubspec.yaml.

My result:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-20.0.jar (com.google.guava:guava:20.0) and listenablefuture-1.0.jar(com.google.guava:listenablefuture:1.0)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
2
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
```
Note: You can use one without the other but not both together (by removing either of the dependencies). 
I belive that they might use different versions of flutter as dependencies? But I'm not sure, just a guess.
Should I create this issue at the repo for sign_in_with_apple as well?

**Comment by TahaTesser** [comment] 2021-01-11 09:50
Hi @Flajt 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/aboutyou/dart_packages/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-11 09:50 UTC
