### ISSUE TITLE
pls help, Can't remove khmer unicode from textform field

### ISSUE THREAD

**Issue by sinsarath** [flutter/flutter#24203] opened 2018-11-10 04:52 UTC
**1. on android device**

![photo_2018-11-10_10-42-26](https://user-images.githubusercontent.com/42288051/48297214-8c6e3580-e4d5-11e8-8e25-21e97b13571a.jpg)

for android device can remove text as normal but why cursor run to behind of text ?

![ezgif-4-3b8e84322aec](https://user-images.githubusercontent.com/42288051/48297360-89c10f80-e4d8-11e8-9316-76e7c9583365.gif)

**2. on ios device**

for ios device i can't remove text in textformfiled after cursor run to behind of text?

![ezgif-4-a2c80e032805](https://user-images.githubusercontent.com/42288051/48297592-fa6b2a80-e4de-11e8-8b72-ebb469430e1b.gif)

please help me to check this.

Best regard.

**Comment by zoechi** [comment] 2018-11-11 12:50
Please add the output of `flutter doctor -v`.

**Comment by sinsarath** [comment] 2018-11-11 13:55
![image](https://user-images.githubusercontent.com/42288051/48313812-1c0a0600-e5f4-11e8-846f-9fe80809c191.png)

**Comment by sinsarath** [comment] 2018-11-11 13:57
Sent from Mail for Windows 10

**Comment by sinsarath** [comment] 2018-11-11 14:02
thank so much, for check my issue.

**Comment by zoechi** [comment] 2018-11-12 15:05
Can you please add the `flutter doctor -v` output as text instead of as screenshot?

**Comment by sinsarath** [comment] 2018-11-13 02:21
*- On window*
Microsoft Windows [Version 10.0.17134.345]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\SINSARATH>flutter doctor -v
[√] Flutter (Channel master, v0.10.1-pre.77, on Microsoft Windows [Version
10.0.17134.345], locale en-US)
    • Flutter version 0.10.1-pre.77 at D:\Flutter\flutter
    • Framework revision 5193affb27 (4 weeks ago), 2018-10-18 04:15:02 -0400
    • Engine revision cc2ec365b7
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\SINSARATH\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native
profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\SINSARATH\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter
doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.5
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[√] VS Code (version 1.28.2)
    • VS Code at C:\Users\SINSARATH\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] VS Code, 64-bit edition (version 1.26.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.20.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

*- On iMac*

[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G3025, locale
en-US)
    • Flutter version 0.9.4 at /Users/bill24/Drive D/flutter
    • Framework revision f37c235c32 (7 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/bill24/Library/Android/sdk
    • Android NDK at /Users/bill24/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-915-b08)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by sinsarath** [comment] 2018-11-13 02:22
*thank for your support.*

**Comment by sinsarath** [comment] 2018-11-15 04:04
please help feedback me, when you fixed this issue done.

**Comment by GaryQian** [comment] 2018-11-27 01:37
The cause is that certain glyphs/characters that make use of surrogate pairs or zero width joiners take up more than two 16-bit chunks of data. We only support codepoints consisting of 32 bits, and when there are more than two 16-bit data that define a glyph, the offset of 2 is not enough to draw a rectangle around the character, and so is omitted.

**Comment by yimankaing** [comment] 2019-04-01 09:31
the question has been asked since Nov 10, 2018. Until now there is still an issue with the TextField. I also face that issue and looking for help.

**Comment by kimhan** [comment] 2019-07-12 11:06
I got the same problem, Khmer unicode keyboard still not working well on iOS device

**Comment by GaryQian** [comment] 2019-07-12 20:30
Do you know if it is happening on just iOS or android also? Also, since it has been a while, is the bug still the same as originally reported or is it slightly different? There have been a few changes in the meantime that may have helped with this.

**Comment by pkmis4it** [comment] 2019-07-19 06:49
> Do you know if it is happening on just iOS or android also? Also, since it has been a while, is the bug still the same as originally reported or is it slightly different? There have been a few changes in the meantime that may have helped with this.

It is happening only for iOS (when removing text, it doesn't work properly). Thanks I am appreciate your help.

**Comment by VladyslavBondarenko** [comment] 2020-07-08 15:10
I can't reproduce it with current `1.20.0-3.0.pre.163`.
Tried with iOS 13.5 simulator and iPhone XR iOS 13.5.

Cursor behaves properly.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.163, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.163 at /Users/nevercode/dev/flutter
    • Framework revision f0e396710a (10 hours ago), 2020-07-07 22:22:08 -0700
    • Engine revision d0d6a4c236
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 69aba23371)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)      • 6345c469                             • android-arm64  • Android 9 (API 28)
    • iPhone 11 Pro Max (mobile) • 9F9AFD9B-7F22-468E-8096-B47E993E0619 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

Closing as fixed. Please comment here or file a new issue if I'm wrong

**Closed by VladyslavBondarenko** 2020-07-08 15:10 UTC
Labels: P4, a: internationalization, a: text input, engine, framework
