### ISSUE TITLE
Flutter web with custom port sometimes crashes

### ISSUE THREAD

**Issue by yahu1031** [flutter/flutter#82051] opened 2021-05-07 18:40 UTC
## Steps to Reproduce

I don't think so this can be reproduceable , But when I'm running a web project this problem occurs with both Chrome and Edge. I don't know what's wrong. But my debug console shows no error. This is frequently happening. But sometimes it works fine.

**Expected results:** 

This expected result was from already [deployed site](https://password-magnager.web.app/).

![image](https://user-images.githubusercontent.com/35523357/117493903-3b9a0380-af91-11eb-81a8-82fa852c3ed4.png)

**Actual results:** 

This actual result is from the development side.

![image](https://user-images.githubusercontent.com/35523357/117492730-a1858b80-af8f-11eb-82a2-76e5b813077f.png)

The code is my `launch.json` and the `debug console` looks like that. I quite don't understand what's happening.

<details>
  <summary>Logs</summary>
     

```
[ +126 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +161 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[ +115 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[ +104 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +120 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +88 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +152 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +86 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +158 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +113 ms] executing: C:\Users\yaswa\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +106 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +130 ms] executing: C:\Users\yaswa\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +23 ms] Skipping pub get: version match.
[  +48 ms] Found plugin cloud_firestore at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-1.0.7\
[  +17 ms] Found plugin cloud_firestore_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.7\
[  +19 ms] Found plugin firebase_auth at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-1.1.2\
[   +7 ms] Found plugin firebase_auth_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.0\
[   +3 ms] Found plugin firebase_core at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.1.0\
[   +8 ms] Found plugin firebase_core_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\
[   +3 ms] Found plugin firebase_storage at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-8.0.5\
[   +6 ms] Found plugin firebase_storage_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage_web-1.0.5\
[   +7 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.1\
[   +3 ms] Found plugin google_sign_in at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-5.0.2\
[   +6 ms] Found plugin google_sign_in_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[  +14 ms] Found plugin image_picker at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.7.4\
[   +5 ms] Found plugin image_picker_for_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image_picker_for_web-2.0.0\
[  +20 ms] Found plugin path_provider at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +2 ms] Found plugin path_provider_linux at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +3 ms] Found plugin path_provider_macos at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +7 ms] Found plugin path_provider_windows at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +17 ms] Found plugin qr_code_scanner at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.4.0\
[  +11 ms] Found plugin sqflite at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\sqflite-2.0.0+3\
[  +17 ms] Found plugin url_launcher at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +3 ms] Found plugin url_launcher_linux at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +5 ms] Found plugin url_launcher_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[ +192 ms] Found plugin cloud_firestore at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-1.0.7\
[   +5 ms] Found plugin cloud_firestore_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.7\
[  +13 ms] Found plugin firebase_auth at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-1.1.2\
[   +4 ms] Found plugin firebase_auth_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.0\
[   +3 ms] Found plugin firebase_core at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.1.0\
[   +4 ms] Found plugin firebase_core_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\
[   +2 ms] Found plugin firebase_storage at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-8.0.5\
[   +3 ms] Found plugin firebase_storage_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage_web-1.0.5\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.1\
[   +3 ms] Found plugin google_sign_in at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-5.0.2\
[   +3 ms] Found plugin google_sign_in_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[   +6 ms] Found plugin image_picker at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.7.4\
[   +2 ms] Found plugin image_picker_for_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image_picker_for_web-2.0.0\
[  +15 ms] Found plugin path_provider at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +2 ms] Found plugin path_provider_linux at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +3 ms] Found plugin path_provider_macos at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +5 ms] Found plugin path_provider_windows at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +14 ms] Found plugin qr_code_scanner at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.4.0\
[   +6 ms] Found plugin sqflite at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\sqflite-2.0.0+3\
[  +12 ms] Found plugin url_launcher at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +42 ms] Generating C:\Users\yaswa\Documents\Projects\Flutter\password\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +101 ms] List of devices attached
           15ee7c3a0806           device product:olive model:Redmi_8 device:olive transport_id:5
[  +98 ms] List of devices attached
           15ee7c3a0806           device product:olive model:Redmi_8 device:olive transport_id:5
[ +113 ms] Launching lib\main.dart on Chrome in debug mode...
[ +264 ms] Updating assets
[ +297 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +26 ms] Found plugin cloud_firestore at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-1.0.7\
[   +2 ms] Found plugin cloud_firestore_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.7\
[   +9 ms] Found plugin firebase_auth at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-1.1.2\
[   +2 ms] Found plugin firebase_auth_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.0\
[   +1 ms] Found plugin firebase_core at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.1.0\
[   +3 ms] Found plugin firebase_core_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\
[   +1 ms] Found plugin firebase_storage at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-8.0.5\
[   +4 ms] Found plugin firebase_storage_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage_web-1.0.5\
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.1\
[   +1 ms] Found plugin google_sign_in at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-5.0.2\
[   +2 ms] Found plugin google_sign_in_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[   +4 ms] Found plugin image_picker at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.7.4\
[   +2 ms] Found plugin image_picker_for_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image_picker_for_web-2.0.0\
[  +12 ms] Found plugin path_provider at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +1 ms] Found plugin path_provider_linux at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +6 ms] Found plugin path_provider_windows at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +9 ms] Found plugin qr_code_scanner at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.4.0\
[   +9 ms] Found plugin sqflite at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\sqflite-2.0.0+3\
[  +11 ms] Found plugin url_launcher at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +2 ms] Found plugin url_launcher_windows at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +30 ms] Found plugin cloud_firestore at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-1.0.7\
[   +2 ms] Found plugin cloud_firestore_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.7\
[   +8 ms] Found plugin firebase_auth at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-1.1.2\
[   +2 ms] Found plugin firebase_auth_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.0\
[   +1 ms] Found plugin firebase_core at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.1.0\
[   +2 ms] Found plugin firebase_core_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\
[   +1 ms] Found plugin firebase_storage at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-8.0.5\
[   +2 ms] Found plugin firebase_storage_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage_web-1.0.5\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.1\
[   +2 ms] Found plugin google_sign_in at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-5.0.2\
[   +3 ms] Found plugin google_sign_in_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[   +4 ms] Found plugin image_picker at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image_picker-0.7.4\
[   +2 ms] Found plugin image_picker_for_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\image_picker_for_web-2.0.0\
[  +10 ms] Found plugin path_provider at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +1 ms] Found plugin path_provider_linux at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +2 ms] Found plugin path_provider_windows at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +9 ms] Found plugin qr_code_scanner at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\qr_code_scanner-0.4.0\
[   +4 ms] Found plugin sqflite at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\sqflite-2.0.0+3\
[   +9 ms] Found plugin url_launcher at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\Users\yaswa\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[ +301 ms] <- reset
[  +28 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false --output-dill C:\Users\yaswa\AppData\Local\Temp\flutter_tools.befa55d3\flutter_tool.9b526919\app.dill --libraries-spec file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\yaswa\Documents\Projects\Flutter\password\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\yaswa\AppData\Local\Temp\flutter_tools.befa55d3\flutter_tools.9241dc --filesystem-scheme org-dartlang-app --initialize-from-dill build\f11f07cf0df8b0238ccdbad84c2f241c.cache.dill.track.dill --platform file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[38;5;248m[  +16 ms] <- compile org-dartlang-app:/web_entrypoint.dart[39;49m
[+48821 ms] Synced 43.8MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[+55166 ms] Using
[+1377 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:58666/devtools/browser/ebea54e8-9289-471c-9031-d6b5a681a60c
[+2648 ms] DwdsInjector: Received request for entrypoint at http://localhost:1031/main_module.bootstrap.js
[  +15 ms] MetadataProvider: Loading debug metadata...
[  +63 ms] MetadataProvider: Loaded debug metadata
[  +28 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:1031/main_module.bootstrap.js
[+23058 ms] DevHandler: Debug service listening on ws://127.0.0.1:58726/Bw6UESGQlTM%3D/ws
[  +12 ms] Debug service listening on ws://127.0.0.1:58726/Bw6UESGQlTM=/ws
[        ]  Running with sound null safety
Connecting to VM Service at ws://127.0.0.1:58726/Bw6UESGQlTM=/ws
```

**`flutter analyze`**

```
PS C:\Users\yaswa\Documents\Projects\Flutter\password> flutter analyze
Analyzing password...                                                   
No issues found! (ran in 103.5s)
```

**`flutter doctor -v`**

```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.21376.1], locale en-IN)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (8 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\yaswa\AppData\Local\Android\sdk\
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\yaswa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\yaswa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.0)
    • VS Code at C:\Users\yaswa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (4 available)
    • Redmi 8 (mobile)  • 15ee7c3a0806 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [Version 10.0.21376.1]
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-05-10 08:39
Hi @yahu1031 
Indeed it is doesn't reproduce, tried it several times on the `stable` channel using the same config


<details> 
<summary>config</summary> 
	
```console
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "stable_flutter",
            "request": "launch",
            "type": "dart",
            "flutterMode": "debug",
            "args": [
                "-d",
                "chrome",
                "--web-renderer",
                "html",
                "--web-port",
                "1031"
            ]
        }
    ]
}
```

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.6 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 1d9032c7e1 (10 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!
```
		
</details>

I see you're experiencing this issue in the production app, are you able to reproduce the issue using a new project with no modifications on the same channel and same config?
Thank uou

**Comment by yahu1031** [comment] 2021-05-10 08:41
@TahaTesser Yes, I'm facing it. But not every time. It is like most likely 2-3 attempts out of 10.

**Comment by ditman** [comment] 2022-04-21 18:44
`STATUS_ACCESS_VIOLATION` errors seem to be caused by a bunch of different causes, see in [Monorail](https://bugs.chromium.org/p/chromium/issues/list?q=STATUS_ACCESS_VIOLATION&can=2&sort=-modified).

However, we can't debug this (nor create a new issue for Chrome) without a minimal repro case.

@yahu1031 are you still experiencing this, or did updating Chrome alleviate the issue? If you're still seeing the error, could you please provide a minimal code reproduction so we have something to debug with?

**Comment by yahu1031** [comment] 2022-04-21 18:47
@ditman This was a very old issue that i haven't worked and couldn't reproduce every time.  So we can close this. If things break as mentioned again, I will reopen it. 

Regards

**Comment by ditman** [comment] 2022-04-21 19:39
Thanks, I'll close this then. As you said, feel free to reopen (or create a new issue) if needed!

**Closed by ditman** 2022-04-21 19:39 UTC
Labels: severe: crash, tool, platform-web, passed first triage
