### ISSUE TITLE
JobParameters.java

### ISSUE THREAD

**Issue by BeshoyAdelHemaya** [flutter/flutter#75589] opened 2021-02-07 14:49 UTC
Hi dears,

I have issues appear on Firebase crashlytics and i couldn't find a solution for them till now as the following:-

**- JobParameters.java line 273
android.app.job.JobParameters.completeWork**

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:399)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**- JobParameters.java line 282
android.app.job.JobParameters.completeWork**

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:399)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

Flutter version 1.20.1
Dart version 2.9.0
Engine revision c8e3b94853
Framework revision 2ae34518b8 (6 months ago), 2020-08-05 19:53:19 -0700

 Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by iapicca** [comment] 2021-02-07 15:07
@BeshoyAdelHemaya 
your flutter version is quite old, can you run 
```console
flutter upgrade -f
```
and provide your updated `flutter doctor -v`,  your `flutter run --release -v` and the list of affected devices

**Comment by pedromassangocode** [comment] 2021-02-08 08:51
Hi @BeshoyAdelHemaya 
Please provide what was asked in the comment above.
Thank you

**Comment by BeshoyAdelHemaya** [comment] 2021-02-08 09:54
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bhemaya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • LYA L29 (mobile) • LHS7N19216018439 • android-arm64 • Android 10 (API 29)

**Comment by pedromassangocode** [comment] 2021-02-08 11:51
Hi @BeshoyAdelHemaya 
This does not seems to be complete!

**Comment by BeshoyAdelHemaya** [comment] 2021-02-08 11:54
I updated it to the latest versions 

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.22.6 at G:\Flutter\flutter_windows_v1.7.8+hotfix.3-stable00\flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

**Comment by pedromassangocode** [comment] 2021-02-08 12:12
We need 

> and provide your updated `flutter doctor -v`, your `flutter run --release -v` and the list of affected devices

as well.

Do you have any more crash logs information to share? This does not seems enough to find the root cause of the issue.
Are you able to reproduce the issue?

**Comment by BeshoyAdelHemaya** [comment] 2021-02-08 12:43
Hi @pedromassangocode we got the issues from Firebase Crashlytics as we couldn't have any device reproduce the issues so i think we will need to publish the new release and feedback you with Firebase Crashlytics results.

On the other side we run the commends you mentioned and below are the results.

G:\Flutter\flutter_windows_v1.7.8+hotfix.3-stable00\flutter\bin\flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.22.6 at G:\Flutter\flutter_windows_v1.7.8+hotfix.3-stable00\flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bhemaya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • INE LX1 (mobile) • GVV7N18728012673 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.


The Application is built successfully and release apk generated successfully too

**Comment by pedromassangocode** [comment] 2021-02-09 06:59
> Hi @pedromassangocode we got the issues from Firebase Crashlytics as we couldn't have any device reproduce the issues so i think we will need to publish the new release and feedback you with Firebase Crashlytics results.

Ok, since your Flutter version was too old and looks like you've upgraded to the latest version, I'm going to close this issue for now. Please write in the comments bellow if the issue start to happen again once you release a new version of your app with the latest Flutter version and I will reopen the issue.
Thank you

**Comment by BeshoyAdelHemaya** [comment] 2021-02-24 08:19
We updated Flutter version to the latest then we released the new update but we still face the same issues on JobParameters.java as the attached screenshot
![crashes_error](https://user-images.githubusercontent.com/45786751/108968675-bdb0a680-7689-11eb-956a-fa2d40164fd1.PNG)

**Comment by pedromassangocode** [comment] 2021-02-25 11:09
Hi @BeshoyAdelHemaya 
Can you please provide your `flutter doctor -v` and your `pubspec.yaml`?
Thank you

**Comment by BeshoyAdelHemaya** [comment] 2021-02-25 11:12
Sure 

**Flutter Doctor**
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.22.6 at G:\Flutter\flutter_windows_v1.7.8+hotfix.3-stable00\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bhemaya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • INE LX1 (mobile) • GVV7N18728012673 • android-arm64 • Android 9 (API 28)
    • LYA L29 (mobile) • LHS7N19216018439 • android-arm64 • Android 10 (API 29)


**pubspec.yaml**

name: ic_filfan
description: FilFan

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0
  # validate: ^1.7.0
  intl: ^0.16.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: any


  flutter_google_ad_manager: ^0.10.1 #was ^0.10.1 but had issues with iOS bec. it was referencing another pod with deprecated and unfound files
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  gradient_widgets: ^0.5.0
  connectivity: ^0.3.2
  share: ^0.6.3+6
  shared_preferences: ^0.5.3+4
  flutter_advanced_networkimage: ^0.6.4
  auto_size_text: ^2.1.0
  async: ^2.2.0
  scroll_to_index: ^1.0.2
  popup_menu: ^1.0.3
  random_string: ^1.1.0
  get_it: ^3.0.0+1
  get_version: ^0.1.0
  flutter_dialog: ^0.0.1
  firebase_core : ^0.5.0+1
  firebase_analytics: ^5.0.16
  #firebase_crashlytics: ^0.1.4+1
  firebase_crashlytics: ^0.2.1+1 #^0.1.3+3
  rate_my_app: ^0.7.2 #rate_my_app: ^0.6.1+6
  smooth_star_rating: ^1.1.1
  netmera_flutter_sdk: ^1.0.5
  uni_links: ^0.2.0
  flutter_widgets: ^0.1.6
  fluttertoast: ^4.0.1 #was 4.0.0 but had issues in ios
  #device_info: ^0.4.0+4
  flushbar: ^1.10.4 #^1.10.4 had an issue with ios build (method 'FlushbarRoute.install' has fewer positional arguments) (https://github.com/AndreHaueisen/flushbar/issues/110#issuecomment-619368001)
  pull_to_refresh: ^1.5.7
  flutter_inappwebview: ^4.0.0+4 #was ^3.1.0
  flutter_tags: ^0.4.8
  flutter_swiper: ^1.1.6
  timeago: ^2.0.26
  youtube_player_flutter: ^6.1.1  #was 6.1.0+7
  flutter_html: ^0.11.1
  photo_view: ^0.9.2
  image_downloader: ^0.19.2
  carousel_slider: ^2.0.0
  huawei_analytics: ^4.0.4

#  huawei_ads:
#    path: ./huawei_ads/

dev_dependencies:
  flutter_test:
    sdk: flutter


  json_serializable: ^2.0.0
  flutter_lifecycle_state: ^1.0.0

  build_runner: ^1.1.2

  flutter_launcher_icons: ^0.7.3

  url_launcher: ^5.0.2
  #device_apps: ^1.0.9


flutter_icons:
    image_path: "assets/app_icon.png"
    android: true
    ios: true
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/filfan.html
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: din
      fonts:
        - asset: fonts/din.otf

**Comment by pedromassangocode** [comment] 2021-02-25 12:31
Can you please provide the crash logs if they are somehow different from the ones you shared in the OP?
Thank you

**Comment by BeshoyAdelHemaya** [comment] 2021-02-25 14:07
**JobParameters.java line 273**

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)

Caused by java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=2 intent=Intent { act=onPushRegister (has extras) } dcount=1}
       at android.app.job.JobParameters.completeWork(JobParameters.java:273)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:268)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$3.call(AsyncTask.java:389)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)

**JobParameters.java line 282**
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:399)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
Caused by java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=1 intent=Intent { act=onPushReceive (has extras) } dcount=1}
       at android.app.job.JobParameters.completeWork(JobParameters.java:282)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:268)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**JobParameters.java line 268**
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:354)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=1 intent=Intent { act=onPushReceive (has extras) } dcount=1}
       at android.app.job.JobParameters.completeWork(JobParameters.java:268)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:268)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**JobParameters.java line 316**

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:415)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=2 intent=Intent { act=onPushDismiss (has extras) } dcount=1}
       at android.app.job.JobParameters.completeWork(JobParameters.java:316)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:268)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**JobParameters.java line 312**
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:415)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)


Caused by java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=1 intent=Intent { act=onPushRegister (has extras) } dcount=2}
       at android.app.job.JobParameters.completeWork(JobParameters.java:312)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:268)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**JobParameters.java line 233**

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:365)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)

Caused by java.lang.IllegalArgumentException: Given work is not active: JobWorkItem{id=1 intent=Intent { act=onPushReceive (has extras) } dcount=1}
       at android.app.job.JobParameters.completeWork(JobParameters.java:233)
       at androidx.core.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:268)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:345)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)


I mentioned all crash logs we faced on our two Apps.

**Comment by pedromassangocode** [comment] 2021-02-25 14:14
It would help a bit if could provide your `pubspec.yaml`. This may be something to do with any Android plugin. You can share both `pubspec` files of the two apps crashing.
Thank you

**Comment by BeshoyAdelHemaya** [comment] 2021-02-25 14:18
Both Apps have same sdks. I sent you yaml of one of them above. Most of these crashes appear with high percentage on background. I am not sure if these issues related to push notifications that we implement using Flutter_netmera sdk or not.

**Comment by BeshoyAdelHemaya** [comment] 2021-03-01 07:56
Hi @pedromassangocode , Do you need any inputs from my side ?

**Comment by pedromassangocode** [comment] 2021-03-01 11:51
> Hi @pedromassangocode , Do you need any inputs from my side ?

No, thank you!

**Comment by chinmaygarde** [comment] 2021-03-01 18:58
There is no Flutter frame in any of the backtraces, `JobParameters` is not used by directly by the engine, and there is no reproducible test case. This issue is not actionable in its current state.

Looks like @pedromassango is still working on finding the responsible plugin. If that is not successful, we'll need a reproducible test case.

**Comment by pedromassangocode** [comment] 2021-03-02 09:37
> `JobParameters` is not used by directly by the engine

So I fear that there is nothing the Flutter team can do about this issue.


> I am not sure if these issues related to push notifications that we implement using Flutter_netmera sdk or not.

I was not able to find the responsible plugin. @BeshoyAdelHemaya can you please try to remove it and see if the issue still happening without it? I would suggest to do the same with all other plugins until you find the responsible plugin.

If by any chance you find the steps to reproduce please let me know.
Thank you

**Comment by BeshoyAdelHemaya** [comment] 2021-03-02 09:59
@pedromassangocode I will try your suggestion but i am not sure if i will success or not.

**Comment by pedromassangocode** [comment] 2021-03-24 12:52
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-24 12:52 UTC
Labels: P4, a: release, engine, passed first triage, platform-android, severe: fatal crash, waiting for customer response
