### ISSUE TITLE
Could not prepare to run the isolate.

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#23771] opened 2018-10-31 10:44 UTC
下拉刷新网络请求无反应。
--- translate ---
Drop-down refreshes network requests without response.

## Steps to Reproduce

1. 在FlutterViewController上present一个WebViewController。
    --- translate ---
    On FlutterViewController, present a WebViewController.
    [self presentViewController:viewControllerToPresent animated:flag completion:completion];
2. 返回FlutterViewController，刷新网络请求。
    --- translate ---
    Return to FlutterViewController to refresh the network request.
3. 如果没出现，则重复步骤1、2
    --- translate ---
    If it does not appear, repeat steps 1 and 2.

## Logs

```
[VERBOSE-2:engine.cc(157)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(116)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(462)] Could not launch engine with configuration.
```

```
bogon:star_admin v7lin$ flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.9.4 at /Users/v7lin/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/v7lin/Library/Android/sdk
    • Android NDK at /Users/v7lin/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/v7lin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)

```

**Comment by zoechi** [comment] 2018-12-11 14:46
Duplicate of #21221

**Closed by zoechi** 2018-12-11 14:46 UTC
Labels: waiting for customer response

**Comment by zoechi** [comment] 2018-12-11 14:52
Duplicate of #21221
