### ISSUE TITLE
Skia crash when doing a specific action in the flutter_gallery demo app.

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#11221] opened 2017-07-14 01:36 UTC
## Steps to Reproduce

1. Run the flutter gallery app
2. Open the "Shrine" shopping demo
3. Select the light blue radio ($300) option.
4. Tap the shopping cart icon at the top.
5. Tap the triple dots top open a small menu. Select empty shopping cart.
6. Rapidly open the same menu and alternate between selecting Sort by price and Sort by product.

## Logs

Logs from "flutter run"

D/skia    ( 4144): ../../third_party/skia/src/utils/SkInsetConvexPolygon.cpp:287: fatal error: "assert(is_convex(*insetPolygon))"
F/libc    ( 4144): Fatal signal 6 (SIGABRT), code -6 in tid 4159 (gpu_thread)

Backtrace from gdb:

#0  0xb6c9ef50 in tgkill () from target:/system/lib/libc.so
#1  0xb6c9cb60 in pthread_kill () from target:/system/lib/libc.so
#2  0xb6c79312 in raise () from target:/system/lib/libc.so
#3  0xb6c764c4 in __libc_android_abort () from target:/system/lib/libc.so
#4  0xb6c744b0 in abort () from target:/system/lib/libc.so
#5  0xa0d0f06e in dart::OS::Abort() ()
   from target:/data/app/io.flutter.examples.gallery-2/lib/arm/libflutter.so
#6  0xa0ce4a9c in SkInsetConvexPolygon(SkPoint const*, int, std::__ndk1::function<float (int)>, SkTDArray<SkPoint>*) ()
   from target:/data/app/io.flutter.examples.gallery-2/lib/arm/libflutter.so
#7  0xa0cf00ac in ?? ()
   from target:/data/app/io.flutter.examples.gallery-2/lib/arm/libflutter.so
#8  0xa0cef48a in SkSpotShadowTessellator::SkSpotShadowTessellator(SkPath const&, SkMatrix const&, SkPoint3 const&, SkPoint3 const&, float, bool) ()
   from target:/data/app/io.flutter.examples.gallery-2/lib/arm/libflutter.so
#9  0xa0cf0e34 in SkShadowTessellator::MakeSpot(SkPath const&, SkMatrix const&, SkPoint3 const&, SkPoint3 const&, float, bool) ()
   from target:/data/app/io.flutter.examples.gallery-2/lib/arm/libflutter.so
#10 0xa0cf5e22 in ?? ()
   from target:/data/app/io.flutter.examples.gallery-2/lib/arm/libflutter.so
#11 0xa0cf61a0 in ?? ()
   from target:/data/app/io.flutter.examples.gallery-2/lib/arm/libflutter.so
#12 0xa0cf5cdc in ?? ()

This is on a Nexus 5 device.

**Comment by eseidelGoogle** [comment] 2017-07-14 01:45
Definitely shouldn't be possible to crash Skia like this. :/ . FYI @chinmaygarde

**Comment by chinmaygarde** [comment] 2017-07-14 03:16
This is a debug assertion that happens to fail in release as well but doesnt take down the engine. Will investigate what is going on.

**Comment by jason-simmons** [comment] 2017-07-14 17:56
This is in the SkShadowUtils code.  I can still reproduce it when I roll forward to the Skia tip of tree.

@jvanverth

**Comment by jvanverth** [comment] 2017-07-17 14:25
I believe the reveal clip is generating what it thinks is a concave path -- which shouldn't be possible since it's the intersection of two convex paths. I'll see if I can figure out what is going on there.

**Comment by jvanverth** [comment] 2017-07-24 18:32
Should be fixed by https://skia-review.googlesource.com/c/24124/.

**Closed** 2017-10-17 23:13 UTC
Labels: crash, dependency: skia, prod: engine
