### ISSUE TITLE
Notification not receiving when app terminated android

### ISSUE THREAD

**Issue by subaharan** [flutter/flutter#44689] opened 2019-11-12 11:17 UTC
I have used 
 firebase_messaging:
    git:
      url: https://github.com/kroikie/plugins.git
      ref: fcm_background
      path: packages/firebase_messaging

Working  in IOS foreground, background and terminated 
but in Android foreground and background are working, not working on terminated 

Can you help me in this

**Comment by iapicca** [comment] 2019-11-12 13:52
Hi @subaharan 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-12 13:52 UTC
