### ISSUE TITLE
No animation when I use pushNamedAndRemoveUntil 

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#15030] opened 2018-03-01 19:12 UTC
A have this series of screens A->B->C. When I'm in C I want to push D and clear the stack bellow until A so I can have A->D. I use pushNamedAndRemoveUntil for this and it works perfectly but it doesn't animate the transition from C to D, it just changes.

![ezgif-2-76796c815c](https://user-images.githubusercontent.com/9283414/36869002-d49a78fa-1da2-11e8-9ae5-e54c81c42afc.gif)

**Comment by long1eu** [comment] 2018-03-12 11:11
is there a way to speed this up?

**Comment by qwilbird** [comment] 2018-07-30 10:40
@zoechi Hi, do you know when this is going to be solved?

**Comment by long1eu** [comment] 2018-07-30 15:31
This issue could be fixed if https://github.com/flutter/flutter/pull/15764 would be merged. Still I don't think it works as intended since all push methods convey the animation along with the page change. Still look like you(@zoechi) feel the same since your added the framework label.

**Comment by Hixie** [comment] 2018-07-30 22:04
Weird, I wonder why this doesn't work.

**Comment by goderbauer** [comment] 2019-03-30 07:45
Dupe of https://github.com/flutter/flutter/issues/25080.

**Closed by goderbauer** 2019-03-30 07:45 UTC
Labels: f: routes, framework

**Comment by long1eu** [comment] 2019-03-30 08:59
How is this a dup if is early than 25080, like way earlier?? :))

**Comment by goderbauer** [comment] 2019-03-30 09:07
The other one has more information (it includes a runnable code sample for example). Therefore I picked it as the canonical candidate for this bug.
