### ISSUE TITLE
Flutter memory leak on Mac Air M1 Monterey

### ISSUE THREAD

**Issue by Skufler** [flutter/flutter#98015] opened 2022-02-08 08:12 UTC
## Steps to Reproduce

1. Launch app
2. Write some code
3. Problem is about to show after 15-30 min avg
The ```dart process``` is running in a background and consuming a lot of battery power and cpu utlization

### Case 1
if IntelliJ shows that there is some error with hot reload/hot restart, you no longer be able to stop app, except using ```kill``` with ```-9``` flag. Buttons in IDE do not react on tap.

OR
### Case 2
You will see something like this:
```
DevFS: Deleting filesystem on the device (file:///data/user/0/$APP_NAME/code_cache/$APP_NAME-YMJVBL/$APP_NAME/)
DevFS: Deleted filesystem on the device (file:///data/user/0/$APP_NAME/code_cache/$APP_NAME/$APP_NAME/)
executing: /Library/Android/sdk/platform-tools/adb -s 192.168.2.77:5555 shell am force-stop $APP_NAME
```
And also you can't stop flutter app without sending SIGKILL (SIGTERM won't help either, stop button won't help too)

## Solutions tried:
- [x] Reinstall IntelliJ
- [x] Reinstall Flutter plugin
- [x] Reinstall Flutter
- [x] Reinstall dart
- [x] Reinstall android sdk, ndk, cmdline-tools, etc
- [x] Use another device
- [x] Use adb over wifi or cable

Here is my ```flutter doctor -v```
```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-RU)
    • Flutter version 2.8.1 at /Users/skufler/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/skufler/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/skufler/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/skufler/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code 4.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.
```

Setup:
```
OS: macOS 12.1 21C52 arm64 
Host: MacBookAir10,1 
Kernel: 21.2.0 
IntelliJ: IntelliJ IDEA 2021.3.1 (Ultimate Edition)
  Build #IU-213.6461.79, built on December 28, 2021
  Runtime version: 11.0.13+7-b1751.21 aarch64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  GC: G1 Young Generation, G1 Old Generation
  Memory: 2048M
Dart: Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"
Kotlin: 213-1.6.10-release-944-IJ6461.79
Device: Samsung Galaxy Note 10 Lite, Samsung Galaxy S8
```

**Comment by maheshmnj** [comment] 2022-02-08 13:20
Hi  @Skufler, Does this issue occur when only running from intellij? or when running from other IDES's or terminal too? Could you please try upgrading to `stable 2.10.0` and see if that fixes the issue.
You can upgrade by running 
```
flutter upgrade
```
> Problem is about to show after 15-30 min avg

Also if I am understanding it right you left the android app running in the background and you see the error in the console after  15-30 mins and there is peak consumption of battery and CPU,  is that correct?

**Comment by aiss83** [comment] 2022-02-08 17:04
The same thing happens on Intel MacBook Pro

[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-x64, locale
    ru-RU)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

-----
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 28, 2022
Licensed to Alexander Shaykhrazeev
Subscription is active until February 16, 2022.
Runtime version: 11.0.13+7-b1751.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Non-Bundled Plugins:
    org.jetbrains.kotlin (213-1.6.10-release-944-IJ6461.79)
    Dart (213.5744.122)
    io.flutter (64.0.4)

Kotlin: 213-1.6.10-release-944-IJ6461.79

**Comment by Skufler** [comment] 2022-02-08 20:45
@aiss83 Hi! Have you tried to solve ```flutter doctor``` issue on IntelliJ doctor check?
Both of us have the same error, maybe this is the key to solution?

**Comment by aiss83** [comment] 2022-02-09 05:37
Hi! I also have tried on my Windows workstation and got the same results with IntelliJ. This issue appears after an update from 2.8.x to 2.10.x of the Flutter SDK.
It seems that everything still work properly except the flutter doctor issue.

Best regards,
Aleksandr

**Comment by maheshmnj** [comment] 2022-02-09 07:56
Thanks for the info @Skufler,

Your flutter doctor error seems to be related to https://github.com/flutter/flutter/issues/94060 see [this comment](https://github.com/flutter/flutter/issues/94060#issuecomment-1008040192) for a fix. 

 I am not able to reproduce the issue. The application continues to run and I don't see any error in the console, The application has been in the background for almost 25 minutes and the debugger closed with "lost connection to device" but no unusual error. 

Here's the IntelliJ version I am using.

```
IntelliJ IDEA 2021.2.1 (Community Edition)
Build #IC-212.5080.55, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Registry: suggest.all.run.configurations.from.context=true
Non-Bundled Plugins: Dart (212.5080.8), io.flutter (61.2.4)
Kotlin: 212-1.5.10-release-IJ5080.55 
```

I am on stable 2.10.0 too but my intellij doesn't report any error

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (6 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 14F40EC6-3B73-469A-A1C0-8CF0B152290F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Could you please try fixing the doctor issue and give this another try?

**Comment by Skufler** [comment] 2022-02-09 10:12
@maheshmnj Just tried to use ```flutter update-packages --force-upgrade```, but flutter doctor issue about IntelliJ still persist

Here is my ```flutter doctor --verbose```
```
✦2 ➜ flutter doctor --verbose
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-RU)
    • Flutter version 2.10.0 at /Users/skufler/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (8 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/skufler/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/skufler/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/skufler/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code 4.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • SM N770F (mobile) • 192.168.179.5:5555 • android-arm64  • Android 12 (API 31)
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
~ took 12s 
```

**Comment by maheshmnj** [comment] 2022-02-10 06:06
if this issue occurs only with intellij then, I believe this should be the right repository https://github.com/flutter/flutter-intellij to investigate this issue further.

**Comment by Skufler** [comment] 2022-02-10 09:47
@maheshmnj Okay, I'm moving this issue to flutter IntelliJ plugin repository
FYI @aiss83 

Considering dart process, I think that IntelliJ plugin doesn't dispose resources properly and this process still running

**Comment by maheshmnj** [comment] 2022-02-10 11:16
Closing this issue for now in case you feel this is related to flutter, feel free to write in the comments and we will reopen it.

Thank you.

**Comment by stevemessick** [comment] 2022-02-10 18:22
@Skufler It seems like this occurs fairly often for you. Could you enable verbose logging in the plugin then share the log after the next hang? The log file could become quite large so it would be best to delete it before starting your app. Also, please verify that no confidential information is included.

**Closed** 2022-03-03 19:09 UTC
Labels: waiting for customer response
