### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: File name too long, errno = 63

### ISSUE THREAD

**Issue by Mihar0302** [flutter/flutter#134397] opened 2023-09-11 04:26 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=25DF9298-73DE-4EE9-AC45-A2D5E683CCC1 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: File name too long, errno = 63
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      RunCommand.usageValues (package:flutter_tools/src/commands/run.dart:482:14)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1565:15)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
```
```
[✓] Flutter (Channel stable, 3.10.6, on macOS 12.5 21G72 darwin-x64, locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/mac/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.82.0)
    • VS Code at /Users/mac/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • 25DF9298-73DE-4EE9-AC45-A2D5E683CCC1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9944297138845a94256f1cf37beb88ff9a8e811a
### Plugins
file_picker-5.5.0
firebase_core-2.15.1
firebase_core_web-2.7.0
firebase_messaging-14.6.7
firebase_messaging_web-3.5.6
flutter_downloader-1.11.0
flutter_launch-0.3.0
flutter_local_notifications-15.1.1
flutter_plugin_android_lifecycle-2.0.16
flutter_vlc_player-7.2.0
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.4
path_provider_linux-2.1.11
path_provider_windows-2.1.7
shared_preferences-2.1.2
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
syncfusion_flutter_pdfviewer-20.4.54
syncfusion_pdfviewer_macos-20.4.54
syncfusion_pdfviewer_web-20.4.54
syncfusion_pdfviewer_windows-20.4.54
url_launcher-6.1.11
url_launcher_android-6.0.36
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6

**Comment by dam-ease** [comment] 2023-09-11 10:20
Closing this as a duplicate of https://github.com/flutter/flutter/issues/80873

**Closed by dam-ease** 2023-09-11 10:20 UTC
Labels: in triage
