### ISSUE TITLE
Crash when whitelist 10.0.2.2 for HTTP traffic on Android

### ISSUE THREAD

**Issue by michaelcheng27** [flutter/flutter#68688] opened 2020-10-21 08:37 UTC
## Steps to Reproduce

Android application crash 100% when trying to enable HTTP traffic to my localhost.

## debug console:
```
Launching lib\main.dart on sdk gphone x86 in debug mode...
lib\main.dart:1
√ Built build\app\outputs\flutter-apk\app-debug.apk.
E/flutter ( 8722): [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: Invalid argument (domain): Invalid domain name: "10.0.2.2", stack trace: #0      new _DomainNetworkPolicy (dart:io/network_policy.dart:85:7)
E/flutter ( 8722): #1      _constructDomainPolicies (dart:io/network_policy.dart:181:22)
E/flutter ( 8722): #2      _EmbedderConfig._setDomainPolicies (dart:io/embedder_config.dart:44:23)
E/flutter ( 8722):
F/flutter ( 8722): [FATAL:flutter/lib/io/dart_io.cc(38)] Check failed: !LogIfError(set_domain_network_policy_result).
E/flutter ( 8722): [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: Invalid argument (domain): Invalid domain name: "10.0.2.2", stack trace: #0      new _DomainNetworkPolicy (dart:io/network_policy.dart:85:7)
E/flutter ( 8722): #1      _constructDomainPolicies (dart:io/network_policy.dart:181:22)
E/flutter ( 8722): #2      _EmbedderConfig._setDomainPolicies (dart:io/embedder_config.dart:44:23)
E/flutter ( 8722):
F/flutter ( 8722): [FATAL:flutter/lib/io/dart_io.cc(38)] Check failed: !LogIfError(set_domain_network_policy_result).
```

## network security config:
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">10.0.2.2</domain>
    </domain-config>
</network-security-config>
```

Did some research, it appears Dart explicitly disallow IP address in domain. 
https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/network_policy.dart#L48

Is there any way to work around it? My use case is to allow local Android Emulator to connect to local server.

Thanks in advance!

```

PS C:\ws\flutter_gudu> flutter doctor -v
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\ws\flutter
    • Framework revision 198df796aa (6 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\micha\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\micha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!

```
```

</details>

**Comment by darshankawar** [comment] 2020-10-21 10:09
@michaelcheng27 
Insecure HTTP connections are disabled by default on both platforms. See [this](https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android) link for more details, reference and workaround for both platforms.

Closing this as working as intended. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-10-21 10:09 UTC

**Comment by darshankawar** [comment] 2020-10-21 10:41
@michaelcheng27 
There's similar open issue describing your case, [68691](https://github.com/flutter/flutter/issues/68691).
Please follow-up there for updates and any questions.
Closing this as duplicate.
