### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by al-habibi-1107** [flutter/flutter#60454] opened 2020-06-28 05:46 UTC
# CODE

## ProductGrid widget:
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../providers/products.dart';
import './product_item.dart';

class ProductsGrid extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final productsData = Provider.of<Products>(context);
    final products = productsData.items;
    return GridView.builder(
      padding: const EdgeInsets.all(10.0),
      itemCount: products.length,
      itemBuilder: (ctx, i) => ChangeNotifierProvider(
           
            child: ProductItem(
                
                ),
                create: (_)=>products[i],
          ),
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        childAspectRatio: 3 / 2,
        crossAxisSpacing: 10,
        mainAxisSpacing: 10,
      ),
    );
  }
}

## Product Item WIdget:

import 'package:flutter/material.dart';
import '../screens/product_detail_screen.dart';
import 'package:provider/provider.dart';
import '../providers/product.dart';

class ProductItem extends StatelessWidget {
  

  @override
  Widget build(BuildContext context) {
    var product = Provider.of<Product>(context,listen: true);
    return ClipRRect(
      borderRadius: BorderRadius.circular(10),
      child: GridTile(
        child: GestureDetector(
          onTap: () {
            Navigator.of(context).pushNamed(
              ProductDetailScreen.routeName,
              arguments: product.id,
            );
          },
          child: Image.network(
            product.imageUrl,
            fit: BoxFit.cover,
          ),
        ),
        footer: GridTileBar(
          backgroundColor: Colors.black87,
          leading: IconButton(
            icon: Icon(
              product.isFavorite ? Icons.favorite : Icons.favorite_border,
            ),
            color: Theme.of(context).accentColor,
            onPressed: () {
              product.toggleFavoriteStatus();
            },
          ),
          title: Text(
            product.title,
            textAlign: TextAlign.center,
          ),
          trailing: IconButton(
            icon: Icon(
              Icons.shopping_cart,
            ),
            onPressed: () {},
            color: Theme.of(context).accentColor,
          ),
        ),
      ),
    );
  }
}

# Logs:
═══════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building ProductItem(dirty, dependencies: [InheritedProvider<Product>]):
Failed assertion: boolean expression must not be null

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
    ProductItem 
lib/widgets/products_grid.dart:18
When the exception was thrown, this was the stack
#0      ProductItem.build 
package:shoppers/widgets/product_item.dart:37
#1      StatelessElement.build 
package:flutter/…/widgets/framework.dart:4291
#2      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4223
#3      Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
#4      StatelessElement.update 
package:flutter/…/widgets/framework.dart:4298
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Failed assertion: boolean expression must not be null
The relevant error-causing widget was
    ProductItem 
lib/widgets/products_grid.dart:18
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Failed assertion: boolean expression must not be null
The relevant error-causing widget was
    ProductItem 
lib/widgets/products_grid.dart:18
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Failed assertion: boolean expression must not be null
The relevant error-causing widget was
    ProductItem 
lib/widgets/products_grid.dart:18
════════════════════════════════════════════════════════════════════════════════
Reloaded 3 of 494 libraries in 447ms.
D/FlutterView( 4128): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@43129b8
D/EGL_emulation( 4128): eglCreateContext: 0xa18855a0: maj 3 min 0 rcv 3

**Comment by iapicca** [comment] 2020-06-29 11:01
Hi @al-habibi-1107 
From what I can see, the issue is related to the 3rd party plugin [provider](https://pub.dev/packages/provider) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-29 11:01 UTC
