### ISSUE TITLE
When trying to launch a page on iOS 18, navigator is bugged don't show the page you gave him

### ISSUE THREAD

**Issue by CreeperFarm** [flutter/flutter#156543] opened 2024-10-10 20:06 UTC
### What package does this bug report belong to?

url_launcher

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

https://pastebin.com/KZeJAnAf

</details>

### Steps to reproduce

1. Build an app with a variable as uri
2. Launch App
3. Lauch the page

### Expected results

I should see my website OAuth page (the url_launcher work on android so I know it work

### Actual results

Picture is better than word (you have to exit the app to close safari) :

<img src="https://github.com/user-attachments/assets/f27f550e-2583-4318-af41-a54a435c67aa" width="300" />

<img src="https://github.com/user-attachments/assets/ec58e854-390f-4979-a0ad-d3860e42e6f5" width="300"/>

### Code sample

<details open><summary>Code sample</summary>

https://pastebin.com/VXVjGaab

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

<img src="https://github.com/user-attachments/assets/f27f550e-2583-4318-af41-a54a435c67aa" width="300" />

<img src="https://github.com/user-attachments/assets/ec58e854-390f-4979-a0ad-d3860e42e6f5" width="300"/>

</details>

### Logs

<details open><summary>Logs</summary>

https://pastebin.com/Mmah3qY5

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

[Doctor Output](https://pastebin.com/Xbzgk8p3)

</details>

**Comment by danagbemava-nc** [comment] 2024-10-11 07:03
Hi @CreeperFarm, are you seeing this only on simulators or do you see it on physical devices as well? 

Do you see this with the `url_launcher` example app as well?

**Comment by CreeperFarm** [comment] 2024-10-11 08:03
I didn't test on a true iPhone because I don't own one however, this problem don't show on both android emu and android phone

**Comment by CreeperFarm** [comment] 2024-10-11 08:04
And when i you the url_launcher project, this problem don't came

**Comment by danagbemava-nc** [comment] 2024-10-11 13:17
Please provide a complete minimal reproducible code sample so that we can properly investigate this. 

Thank you

**Comment by CreeperFarm** [comment] 2024-10-12 09:05
To recroduce, you need this to launch the connection :
```dart
GestureDetector(
                      onTap: () => {
                        PocketBaseConnector().signInWithGoogle(context),
                        context.go('/profile'),
                      },
                      child: Container(
                        padding: const EdgeInsets.all(20),
                        decoration: BoxDecoration(
                          border:
                              Border.all(color: Colors.grey.shade400, width: 2),
                          borderRadius: BorderRadius.circular(16),
                        ),
                        child: Image.asset(
                          'assets/images/google.png',
                          height: 40,
                        ),
                      ),
                    ),
```
You also need this to launch the execution of the web app

```dart
class PocketBaseConnector {
  late PocketBase _pocketBase;

  Future<void> init() async {
    _pocketBase = PocketBase(
      'https://api.mymangatheque.com',
      lang: 'fr-FR',
    );
  }

  // Singleton
  static final PocketBaseConnector _singleton = PocketBaseConnector._internal();

  factory PocketBaseConnector() {
    return _singleton;
  }

  final BehaviorSubject<User?> _connectedUser = BehaviorSubject<User?>();

  PocketBaseConnector._internal()
      : _pocketBase =
            PocketBase('https://api.mymangatheque.com', lang: 'fr-FR');

  Future<void> refresh() async {
    if (!_pocketBase.authStore.isValid) {
      // TODO: The token has expired. Ask the user to sign in again.
      return;
    }
    final authData = await _pocketBase.collection('users').authRefresh();
  }

  // Check if your logged-in
  bool isLoggedIn() {
    return _connectedUser.valueOrNull != null;
  }

  Future<void> _launchUrl(Uri url) async {
    if (!await launchUrl(url)) {
      throw Exception('Could not launch $url');
    }
  }

  signInWithGoogle(context) async {
    final authData = await _pocketBase
        .collection('users')
        .authWithOAuth2('google', (url) async {
      await _launchUrl(url);
    }, scopes: [
      'email',
      'profile',
      'https://www.googleapis.com/auth/user.gender.read',
      'https://www.googleapis.com/auth/user.birthday.read'
    ], createData: {
      "role": "user",
      "emailVisibility": true,
      "gender": "other",
    });
    print(authData);
    dynamic authData2 = json.decode(authData.toString());
    print(authData2['meta']);
    print(authData2['meta']['isNew']);

    var meta = authData.meta;
    print(meta);

    if (authData2['meta']['isNew']) {
      var data = authData2['meta']['rawUser'];
      print('The email is ' + data['email']);
      print('The link is ' + data['picture']);
      try {
        /*var imageId = await ImageDownloader.downloadImage(data['picture']);
        if (imageId == null) {
          return;
        }
        var fileName = await ImageDownloader.findName(imageId);
        var path = await ImageDownloader.findPath(imageId);*/
        var body = <String, dynamic>{
          "email": data['email'],
          "birthday": DateTime.now().toString(),
        };

        // Upload the image of the user
        var sendImg = await _pocketBase
            .collection('users')
            .update(_pocketBase.authStore.model.id, body: body, files: [
          /*http.MultipartFile.fromBytes(
            'avatar',
            File(path!).readAsBytesSync(),
            filename: fileName,
          )*/
        ]);
        print(sendImg);
      } on PlatformException catch (e) {
        print(e);
        showMessage("Un erreur s'est déroullé", context);
      }
    } else {
      print('User already exists');
    }
    print(authData2['meta']['rawUser']['email']);
    _connectedUser.add(await findUser(
        authData2['meta']['rawUser']['email'].toString().toLowerCase()));
    await closeInAppWebView();
  }

  // Update User Data
  Future<User?> updateUserData(String email) async {
    try {
      _connectedUser.add(await findUser(email));
      return _connectedUser.value;
    } catch (err) {
      return null;
    }
  }

  // Log Out
  void logOut() {
    _pocketBase.authStore.clear();
    _connectedUser.add(null);
  }

  Future resetPassword(String email, context) async {
    await _pocketBase.collection('users').requestPasswordReset(email);
    return showMessage(
        'Un lien vous as été envoyé pour la réinitialisation de votre mots de passe, vérifiez vos spams.',
        context);
  }

  // Watch if someone connect or disconnect from his account
  Stream<User?> listenToUserChanges() {
    return _connectedUser.stream;
  }

  // Check if the user is logged in
  User? getConnectedUser() {
    return _connectedUser.valueOrNull;
  }

  sendVerification(String email) {
    return _pocketBase.collection('users').requestVerification(email);
  }

  // Find the user in the collection of users
  Future<User?> findUser(String email) {
    assert(email.isNotEmpty);
    return _pocketBase
        .collection('users')
        .getFirstListItem('email="$email"')
        .then(
          (value) => User.fromJSON(value.id, value.collectionId, value.data),
        );
  }

  // Update the avatar of the user
  updateAvatar(String collectionId, String userId, String fileName,
      String filePath, context) {
    return _pocketBase.collection(collectionId).update(userId, files: [
      MultipartFile.fromBytes(
        'avatar',
        File(filePath).readAsBytesSync(),
        filename: fileName,
      )
    ]).catchError((e) {
      print(e.toString());
      showMessage('Une erreur est arrivé', context);
    });
  }


  String get serverUrl => _pocketBase.baseUrl;
}
```

And need those so that the pocketbaseconnector works fine :

- This one call utils.dart : ```dart
import 'dart:async';

import 'package:pocketbase/pocketbase.dart';

extension CollectionExtension on RecordService {
  Stream<RecordSubscriptionEvent> listen() {
    StreamController<RecordSubscriptionEvent> controller =
        StreamController<RecordSubscriptionEvent>();

    subscribe('*', (RecordSubscriptionEvent e) {
      controller.add(e);
    }).then((value) => controller.onCancel = () => value());

    return controller.stream;
  }
}
```
- This one in a folder call models and his name is file.dart : 
```dart
import 'package:pocketbase/pocketbase.dart';

class PocketBaseFile {
  final String _id;
  final String _collectionId;
  final String _fileName;

  PocketBaseFile({
    required String id,
    required String collectionId,
    required String fileName,
  })  : _id = id,
        _collectionId = collectionId,
        _fileName = fileName;

  PocketBaseFile.fromRecordModel(RecordModel model, String fieldName)
      : this(
          id: model.id,
          collectionId: model.collectionId,
          fileName: model.data[fieldName],
        );

  String? get path => 'api/files/$_collectionId/$_id/$_fileName';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PocketBaseFile &&
          runtimeType == other.runtimeType &&
          _id == other._id &&
          _collectionId == other._collectionId &&
          _fileName == other._fileName;

  @override
  int get hashCode =>
      _id.hashCode ^ _collectionId.hashCode ^ _fileName.hashCode;
}
```

 - This one in a folder call models and his name is user.dart :
```dart
import 'package:mymangatheque/src/services/models/file.dart';

class User {
  final String id;
  final String username;
  final String email;
  final String gender;
  final PocketBaseFile? avatar;
  final DateTime? birthday;
  final DateTime? created;
  final DateTime? updated;

  User.fromJSON(this.id, String collectionId, Map<dynamic, dynamic> json)
      : username = json['username'],
        email = json['email'],
        gender = json['gender'],
        avatar = json['avatar'] != null ? PocketBaseFile(id: id, collectionId: collectionId, fileName: json['avatar']) : null,
        created = json['created'] != null ? DateTime.parse(json['created']) : null,
        updated = json['updated'] != null ? DateTime.parse(json['updated']) : null,
        birthday = json['birthday'] != null ? DateTime.parse(json['birthday']) : null;
}
```

**Comment by danagbemava-nc** [comment] 2024-10-14 06:21
Hi @CreeperFarm, can you share your `Podfile` & `Podfile.lock`?

**Comment by CreeperFarm** [comment] 2024-10-14 16:28
Podfile : https://pastebin.com/hKWuab3V

Podfile.lock : https://pastebin.com/EX5j0e9z

**Comment by danagbemava-nc** [comment] 2024-10-15 06:00
Hi @CreeperFarm, can you open your `ios/Runner.xcworkspace` and make a list of the pods that have excluded arm64 in their build settings? You can see an example here https://github.com/flutter/flutter/issues/79641#issuecomment-2299412011. If the build settings looks like the screenshot, particularly  for `url_launcher`, then that is the reason you're facing this issue.

**Comment by CreeperFarm** [comment] 2024-10-15 08:09
The only excluded architecture for this package is i386
![IMG_20241015_100844.jpg](https://github.com/user-attachments/assets/15463f97-4e97-43c2-8830-6d45843596fd)

**Comment by danagbemava-nc** [comment] 2024-10-15 13:18
Hi @CreeperFarm, do any of your dependencies have `arm64` in the excluded architectures?

**Comment by CreeperFarm** [comment] 2024-10-15 14:04
I just saw that Pods runner excluded arm64. I'm going to launch it again in a few hours, I'm keeping you updated

**Comment by CreeperFarm** [comment] 2024-10-15 19:08
Now it simply don't build anymore, and this error shows up :

```
Error (Xcode): Building for 'iOS-simulator', but linking in object file (/Users/creeperfarm/Documents/GitHub/MyMangatheque/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage[arm64][2](GMLImage.o)) built for 'iOS'```

**Comment by danagbemava-nc** [comment] 2024-10-16 05:53
Hi @CreeperFarm, can you share the full verbose build log? Also, what plugin introduced that Pod? And is the Pod compatible with arm64?

**Comment by CreeperFarm** [comment] 2024-10-16 08:06
Hi @danagbemava-nc, the full build log is : 
```Launching lib/main.dart on iPhone 16 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           20,7s
Failed to build iOS app
Error (Xcode): Building for 'iOS-simulator', but linking in object file (/Users/creeperfarm/Documents/GitHub/MyMangatheque/ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage[arm64][2] (GMLImage.o)) built for 'iOS'

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro Max.

**Comment by danagbemava-nc** [comment] 2024-10-17 06:38
The GoogleMLKit pod does not support M-series Mac simulators. See https://developers.google.com/ml-kit/known-issues#ios_issues

The issue you're facing with url launcher is because arm64 was excluded in your architectures.

You can try following https://github.com/juliansteenbakker/mobile_scanner/issues/585#issuecomment-1932708726 but unfortunately, both issues you're facing are out of flutter's control. 

As such I'll be closing this issue. 

Thank you

**Closed by danagbemava-nc** 2024-10-17 06:38 UTC
Labels: in triage
