### ISSUE TITLE
I would like to be able to play audio files on iOS through the video_player plugin

### ISSUE THREAD

**Issue by mauzepeda** [flutter/flutter#57713] opened 2020-05-21 03:43 UTC
## Use case

Many people develop apps that play media files and it's important to have a reliable and officially supported plugin to accomplish this. 

eg. https://stackoverflow.com/questions/43813386/how-to-play-a-custom-sound-in-flutter

Right now this is possible on Android through Exo Player. However, I can't play an mp3 file on iOS 13.4.1 (Physical device) running the sample project but only changing the remote url to an mp3 file.

## Proposal

I believe this is related to the iOS specific implementation of the plugin and not because my device is not able to play mp3 or wav files remotely through AVPlayer. I can confirm that if I load the sample asset Butterfly-209.mp4 remotely from the same storage it does play the sound.

Would it be possible to extend the iOS plugin to support playing mp3 and audio files in general?

**Comment by TahaTesser** [comment] 2020-05-21 11:21
Hi @mauzepeda 
video_player is meant for video playback but there is already support https://github.com/flutter/flutter/issues/47105 and it address a lot of the concern you mentioned 
duplicate of https://github.com/flutter/flutter/issues/47105

**Closed by TahaTesser** 2020-05-21 11:21 UTC

**Comment by mauzepeda** [comment] 2020-05-21 16:52
That makes sense, thank you! I will use `just_audio` by @ryanheise as suggested in [#47105](https://github.com/flutter/flutter/issues/47105). It seems to be the most reliable plugin for this use case as of today.
