### ISSUE TITLE
The following assertion was thrown while finalizing the widget tree

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#36828] opened 2019-07-24 10:44 UTC
```
 ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5994): The following assertion was thrown while finalizing the widget tree:
I/flutter ( 5994): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 687 pos 12: 'pixels !=
I/flutter ( 5994): null': is not true.
I/flutter ( 5994): 
I/flutter ( 5994): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5994): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5994): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5994):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5994): 
I/flutter ( 5994): When the exception was thrown, this was the stack:
I/flutter ( 5994): #2      ScrollPosition.dispose (package:flutter/src/widgets/scroll_position.dart:687:12)
I/flutter ( 5994): #3      ScrollPositionWithSingleContext.dispose (package:flutter/src/widgets/scroll_position_with_single_context.dart:257:11)
I/flutter ( 5994): #4      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:367:14)
I/flutter ( 5994): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3916:12)
I/flutter ( 5994): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
I/flutter ( 5994): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #14     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter ( 5994): #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter ( 5994): #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter ( 5994): #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #29     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4965:16)
I/flutter ( 5994): #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #41     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4965:16)
I/flutter ( 5994): #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #53     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter ( 5994): #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #59     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter ( 5994): #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #89     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter ( 5994): #90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #92     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter ( 5994): #93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 5994): #101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter ( 5994): #102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 5994): #103    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter ( 5994): #104    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1706:25)
I/flutter ( 5994): #105    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2364:27)
I/flutter ( 5994): #106    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2196:15)
I/flutter ( 5994): #107    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2363:7)
I/flutter ( 5994): #108    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:18)
I/flutter ( 5994): #109    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 5994): #110    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 5994): #111    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 5994): #112    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 5994): #116    _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 5994): #117    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 5994): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 5994): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor -v
```
[√] Flutter (Channel v1.5.4-hotfixes, v1.5.4-hotfix.2-pre.1, on Microsoft Windows [Version 10.0.17134.885], locale en-US)
    • Flutter version 1.5.4-hotfix.2-pre.1 at C:\src\flutter
    • Framework revision 953bbe2ccd (3 months ago), 2019-05-02 09:59:16 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\src\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = C:\src\android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\Pedro Massango\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

```
## To Reproduce

1. Use PageView
2. Switch between tabView's pages

**Comment by BondarenkoStas** [comment] 2019-09-22 15:35
Duplicate of #36417

**Closed by BondarenkoStas** 2019-09-22 15:35 UTC
