### ISSUE TITLE
Error: The getter 'bottomAppBarColor' isn't defined for the class 'ThemeData'.  - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart'

### ISSUE THREAD

**Issue by Sidneyp91** [flutter/flutter#155649] opened 2024-09-25 04:50 UTC
### Steps to reproduce

1. Upgrade to Flutter SDK 3.24.2 or later
2. flutter run

### Expected results

Code should run successfully and install app on device or emulator

### Actual results

Build fails with an exception as shown below
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/misc.dart:132:9: Error: No named parameter with the name 'size'.
        size: logicalSize,
        ^^^^
../../fvm/versions/3.24.3/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/misc_build/build_color.dart:53:48: Error: The getter 'bottomAppBarColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bottomAppBarColor'.
  Color get bottomAppBar => Theme.of(_context).bottomAppBarColor;
                                               ^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/misc_build/build_color.dart:88:47: Error: The getter 'selectedRowColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'selectedRowColor'.
  Color get selectedRow => Theme.of(_context).selectedRowColor;

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/misc.dart:132:9: Error: No named parameter with the name 'size'.
        size: logicalSize,
        ^^^^
../../fvm/versions/3.24.3/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/misc_build/build_color.dart:53:48: Error: The getter 'bottomAppBarColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bottomAppBarColor'.
  Color get bottomAppBar => Theme.of(_context).bottomAppBarColor;
                                               ^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/misc_build/build_color.dart:88:47: Error: The getter 'selectedRowColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'selectedRowColor'.
  Color get selectedRow => Theme.of(_context).selectedRowColor;
                                              ^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/misc_build/build_color.dart:119:46: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'backgroundColor'.
  Color get background => Theme.of(_context).backgroundColor;
                                             ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/misc_build/build_color.dart:139:41: Error: The getter 'errorColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'errorColor'.
  Color get error => Theme.of(_context).errorColor;
                                        ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/misc_build/build_color.dart:144:52: Error: The getter 'toggleableActiveColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'toggleableActiveColor'.
  Color get toggleableActive => Theme.of(_context).toggleableActiveColor;
                                                   ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/numeric_pad.dart:131:37: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                  context.textTheme.bodyText1 ??
                                    ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:130:34: Error: The getter 'headline1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline1'.
        style: context.textTheme.headline1!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:258:34: Error: The getter 'headline2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline2'.
        style: context.textTheme.headline2!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:386:34: Error: The getter 'headline3' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline3'.
        style: context.textTheme.headline3!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:514:34: Error: The getter 'headline4' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline4'.
        style: context.textTheme.headline4!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:642:34: Error: The getter 'headline5' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline5'.
        style: context.textTheme.headline5!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:770:34: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
        style: context.textTheme.headline6!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:898:34: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
        style: context.textTheme.subtitle1!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:1026:34: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle2'.
        style: context.textTheme.subtitle2!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:1154:34: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
        style: context.textTheme.bodyText1!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:1282:34: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
        style: context.textTheme.bodyText2!.merge(style));
                                 ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:1410:34: Error: The getter 'caption' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'caption'.
        style: context.textTheme.caption!.merge(style));
                                 ^^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:1538:34: Error: The getter 'button' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'button'.
        style: context.textTheme.button!.merge(style));
                                 ^^^^^^
../../.pub-cache/hosted/pub.dev/helpers-1.2.3/lib/helpers/widgets/text.dart:1668:32: Error: The getter 'overline' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../fvm/versions/3.24.3/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'overline'.
      style: context.textTheme.overline!.merge(style),
                               ^^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildChurchpadtestDebug'.
> Process 'command '/Users/mac/fvm/versions/3.24.3/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A5264n darwin-arm64 (Rosetta), locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      For re-installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.90.0)
```

</details>

**Comment by danagbemava-nc** [comment] 2024-09-25 07:50
This is caused by the `helpers` package. See https://github.com/seel-channel/helpers/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

Closing from here as this is caused by a third-party package. 

Thank you

**Closed by danagbemava-nc** 2024-09-25 07:50 UTC
Labels: in triage
