### ISSUE TITLE
Padding added to the whole application when I added padding to the layer list's item in splash screen android

### ISSUE THREAD

**Issue by abuzarsaddiqui** [flutter/flutter#53163] opened 2020-03-24 12:30 UTC
Here is the code of splash screen and padding is on the whole application on top and bottom

```
`<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <padding android:left="0dp" android:right="0dp" android:top="20dp" android:bottom="20dp"/>
            <solid android:color="@color/ddcolor"/>
        </shape>
    </item>
    <item android:gravity="center">
        <shape android:shape="rectangle" >
            <corners android:radius="19dp"/>
            <solid android:color="@color/white"/>
        </shape>
    </item>
    <item android:gravity="center">
        <bitmap android:src="@mipmap/splash"
            android:gravity="center" />
    </item>
</layer-list>`
```

**Comment by VladyslavBondarenko** [comment] 2020-03-24 13:24
Hi @abuzarsaddiqui 
could you post here complete `launch_background.xml` and provide your `flutter doctor -v`?

**Comment by abuzarsaddiqui** [comment] 2020-03-24 13:30
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/macbook/development/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro • 814BB3D2-8262-49D9-8D3F-D209210680A7 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by abuzarsaddiqui** [comment] 2020-03-24 13:31
<?xml version="1.0" encoding="utf-8"?>
    

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <padding android:left="0dp" android:right="0dp" android:top="20dp" android:bottom="20dp"/>
            <solid android:color="@color/ddcolor"/>
        </shape>
    </item>
    <item android:gravity="center">
        <shape android:shape="rectangle" >

            <corners android:radius="19dp"/>
            <solid android:color="@color/white"/>
        </shape>
    </item>
    <item android:gravity="center">
        <bitmap android:src="@mipmap/splash"
            android:gravity="center" />
    </item>
</layer-list>

**Comment by abuzarsaddiqui** [comment] 2020-03-24 13:32
`<?xml version="1.0" encoding="utf-8"?>
    

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <padding android:left="0dp" android:right="0dp" android:top="20dp" android:bottom="20dp"/>
            <solid android:color="@color/ddcolor"/>
        </shape>
    </item>
    <item android:gravity="center">
        <shape android:shape="rectangle" >

            <corners android:radius="19dp"/>
            <solid android:color="@color/white"/>
        </shape>
    </item>
    <item android:gravity="center">
        <bitmap android:src="@mipmap/splash"
            android:gravity="center" />
    </item>
</layer-list>`

**Comment by abuzarsaddiqui** [comment] 2020-03-24 13:32
"
<?xml version="1.0" encoding="utf-8"?>
    

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <padding android:left="0dp" android:right="0dp" android:top="20dp" android:bottom="20dp"/>
            <solid android:color="@color/ddcolor"/>
        </shape>
    </item>
    <item android:gravity="center">
        <shape android:shape="rectangle" >

            <corners android:radius="19dp"/>
            <solid android:color="@color/white"/>
        </shape>
    </item>
    <item android:gravity="center">
        <bitmap android:src="@mipmap/splash"
            android:gravity="center" />
    </item>
</layer-list>"

**Comment by abuzarsaddiqui** [comment] 2020-03-24 13:36
updated the code snippet @VladyslavBondarenko

**Comment by VladyslavBondarenko** [comment] 2020-03-24 15:27
Thanks @abuzarsaddiqui
I see what do you mean.
But If you add more items - each of the will have own padding.

<details>
 <summary>Summary Goes Here</summary>

```
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <padding android:left="0dp" android:right="0dp" android:top="20dp" android:bottom="20dp"/>
            <solid android:color="#00ff00"/>
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle">
            <padding android:left="0dp" android:right="0dp" android:top="20dp" android:bottom="20dp"/>
            <solid android:color="#0000ff"/>
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle">
            <padding android:left="0dp" android:right="0dp" android:top="20dp" android:bottom="20dp"/>
            <solid android:color="#ff0000"/>
        </shape>
    </item>
    <item android:gravity="center">
        <shape android:shape="rectangle" >
            <corners android:radius="19dp"/>
            <solid android:color="#ffffff"/>
        </shape>
    </item>
    <item android:gravity="center">
        <bitmap android:src="@mipmap/ic_launcher" android:gravity="center" />
    </item>
</layer-list>
```

</details>

For me it doesn't look like an issue, especially an issue with flutter, closing,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by abuzarsaddiqui** [comment] 2020-03-24 16:53
![spalsh](https://user-images.githubusercontent.com/13914266/77454010-ce252500-6e19-11ea-9615-a24c9fc331c7.png)
![spalsh2](https://user-images.githubusercontent.com/13914266/77454032-d2514280-6e19-11ea-81f5-efc5ba8a0880.png)
as you can see in these screeshots padding after splash is still visible

**Comment by abuzarsaddiqui** [comment] 2020-03-25 07:31
@VladyslavBondarenko waiting for your response.

**Comment by VladyslavBondarenko** [comment] 2020-03-25 09:49
@abuzarsaddiqui 
Sorry, I misunderstood, because I can't see these paddings after splash screen neither with Android 9 real device nor with Android 10 simulator.
What device are you using?

**Comment by abuzarsaddiqui** [comment] 2020-03-25 10:30
android 9 Samsung device, android 6 and other devices as well.

**Comment by VladyslavBondarenko** [comment] 2020-03-25 11:56
@TahaTesser confirmed that it's true for his Samsung Galaxy M30 (Android 10)

**Comment by darshankawar** [comment] 2020-12-08 10:45
@abuzarsaddiqui 
Is this still a valid issue using latest Flutter version or has this been resolved ?
I tried your code sample for `launch_background.xml`, but what are the other steps to replicate the issue if it persists with latest version ?

**Comment by pedromassangocode** [comment] 2020-12-30 11:30
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 11:30 UTC
Labels: a: layout, dependency: android, e: device-specific, engine, platform-android, waiting for customer response
