### ISSUE TITLE
Error on flutter/packages/flutter_tools/gradle/flutter.gradle' line: 946

### ISSUE THREAD

**Issue by prasant10050** [flutter/flutter#36846] opened 2019-07-24 14:22 UTC
I am facing issue on Production app
Flutter version 1.8.2-pre.165 
Dart version 2.5.0 (build 2.5.0-dev.1.0 fedd74669a)
```
[   +5 ms] Gradle task assembleAarDebug failed with exit code 1
[ +194 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/me/Library/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 946
[        ] * What went wrong:
[        ] Execution failed for task ':app:buildPluginDebugPermissionHandle'.
[        ] > Process 'command '/Users/prasantpandey/Library/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[   +3 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 19s
```
Please resolve it as soon as possible

**Comment by mklim** [comment] 2019-07-24 17:18
Thanks for filing the bug report!

From the stack trace this looks like a duplicate of flutter/flutter#36776. @prasant10050 is this happening to you every single time or is it a flaky failure?

/cc @blasten

**Comment by mklim** [comment] 2019-07-24 20:34
I went from a state where this error would happen very infrequently to where it was suddenly happening every time and blocking all my builds. After debugging I figured out that it was because of a syntax error in the plugin's Java source code I was working on.

I think maybe this Gradle error is logged every time a plugin dependency fails to compile for any reason.

Disabling the new build flag with `flutter config --no-enable-build-plugin-as-aar` and reverting to the old compile system ended up printing the actual syntax error instead of the Gradle one. Fixing the syntax error fixed the Gradle failure when I switched back to the new system.

**Comment by zanderso** [comment] 2019-07-26 15:59
@blasten it sound like the issue here is properly surfacing the error without reverting back to the old build.

**Comment by blasten** [comment] 2019-07-26 16:18
Definitely. We had to disable the new build temporarily https://github.com/flutter/flutter/pull/36966 since we found an issue in newer versions of Gradle.

**Comment by TahaTesser** [comment] 2020-03-11 14:56
Hi @prasant10050 
Are you still experiencing this issue?
Thank you

**Comment by buzzicards** [comment] 2020-03-13 01:15
I have same error

**Comment by jmagman** [comment] 2020-04-07 17:52
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-04-07 17:52 UTC
Labels: a: build, platform-android, severe: crash, t: gradle, tool, waiting for customer response
