### ISSUE TITLE
WebView is not opening, only blank screen comes. 

### ISSUE THREAD

**Issue by vinaykumars110** [flutter/flutter#58919] opened 2020-06-07 13:17 UTC
I am very new to Flutter and App Development. So, cannot give any technical details of the Error. Pasting the full build log and flutter doctor below.

**Full build log:**
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Debug service listening on ws://127.0.0.1:50234/aiqeoTBUjoI=/ws
Syncing files to device sdk gphone x86...
D/EGL_emulation(23322): eglMakeCurrent: 0xf432b740: ver 3 0 (tinfo 0xf467c610)
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
I/engappflutterv(23322): Background young concurrent copying GC freed 21267(1418KB) AllocSpace objects, 0(0B) LOS objects, 92% free, 1865KB/25MB, paused 4.228ms total 149.350ms
I/WebViewFactory(23322): Loading com.google.android.webview version 82.0.4085.12 (code 408501281)
W/Gralloc4(23322): allocator 3.x is not supported
I/engappflutterv(23322): The ClassLoaderContext is a special shared library.
I/engappflutterv(23322): The ClassLoaderContext is a special shared library.
W/engappflutterv(23322): Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/engappflutterv(23322): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist,core-platform-api, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist,core-platform-api, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist,core-platform-api, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist,core-platform-api, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist,core-platform-api, reflection, allowed)
W/engappflutterv(23322): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist,core-platform-api, reflection, allowed)
I/cr_LibraryLoader(23322): Loaded native library version number "82.0.4085.12"
I/cr_CachingUmaRecorder(23322): Flushed 3 samples from 3 histograms.
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
I/TetheringManager(23322): registerTetheringEventCallback:com.example.myengappflutterv3
W/chromium(23322): [WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
W/engappflutterv(23322): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/HostConnection(23322): HostConnection::get() New Host Connection established 0xf4528570, tid 23409
W/cr_media(23322): Requires BLUETOOTH permission
D/HostConnection(23322): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
E/MethodChannel#flutter/platform_views(23322): Failed to handle method call
E/MethodChannel#flutter/platform_views(23322): android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@31cedab -- the specified display can not be found
E/MethodChannel#flutter/platform_views(23322): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1069)
E/MethodChannel#flutter/platform_views(23322): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:397)
E/MethodChannel#flutter/platform_views(23322): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:108)
E/MethodChannel#flutter/platform_views(23322): 	at android.app.Dialog.show(Dialog.java:340)
E/MethodChannel#flutter/platform_views(23322): 	at android.app.Presentation.show(Presentation.java:252)
E/MethodChannel#flutter/platform_views(23322): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
E/MethodChannel#flutter/platform_views(23322): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:53)
E/MethodChannel#flutter/platform_views(23322): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:105)
E/MethodChannel#flutter/platform_views(23322): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/MethodChannel#flutter/platform_views(23322): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(23322): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter/platform_views(23322): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter/platform_views(23322): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter/platform_views(23322): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(23322): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/platform_views(23322): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter/platform_views(23322): 	at android.app.ActivityThread.main(ActivityThread.java:7476)
E/MethodChannel#flutter/platform_views(23322): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(23322): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/MethodChannel#flutter/platform_views(23322): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:939)
D/EGL_emulation(23322): eglCreateContext: 0xf43216b0: maj 3 min 0 rcv 3
D/EGL_emulation(23322): eglMakeCurrent: 0xf43216b0: ver 3 0 (tinfo 0xbf6a7630)
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
E/flutter (23322): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unable to add window android.view.ViewRootImpl$W@31cedab -- the specified display can not be found, null)
E/flutter (23322): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (23322): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (23322): <asynchronous suspension>
E/flutter (23322): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (23322): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:633:54)
E/flutter (23322): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:550:14)
E/flutter (23322): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
E/flutter (23322): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
E/flutter (23322): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
E/flutter (23322): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #12     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
E/flutter (23322): #13     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (23322): #14     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
E/flutter (23322): #15     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
E/flutter (23322): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #20     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1247:11)
E/flutter (23322): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #37     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3219:13)
E/flutter (23322): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #39     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:700:15)
E/flutter (23322): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter (23322): #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter (23322): #42     RenderObject.layout (pack
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
D/skia    (23322): Shader compilation error
D/skia    (23322): ------------------------
D/skia    (23322): Errors:
D/skia    (23322): 
I/engappflutterv(23322): Waiting for a blocking GC ProfileSaver
I/VideoCapabilities(23322): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil(23322): HW encoder for video/avc is not available on this device.
D/EGL_emulation(23322): eglCreateContext: 0xf4310000: maj 3 min 0 rcv 3
D/EGL_emulation(23322): eglMakeCurrent: 0xf4310000: ver 3 0 (tinfo 0xbf6a7630)
E/eglCodecCommon(23322): glUtilsParamSize: unknow param 0x000088ef
I/chatty  (23322): uid=10151(com.example.myengappflutterv3) Chrome_InProcGp identical 10 lines
E/eglCodecCommon(23322): glUtilsParamSize: unknow param 0x000088ef

**Flutter doctor output:**
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.17134.1488], locale en-US)
    • Flutter version 1.14.6 at C:\flutter
    • Framework revision fabeb2a16f (4 months ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\skvinay\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.43.2)
    • VS Code at C:\Users\skvinay\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by TahaTesser** [comment] 2020-06-08 09:54
Hi @vinaykumars110 
Looks like you're running a few months old `beta` channel
Please upgrade to latest `beta` channel and try again
Execute the following
`flutter channel beta`
`flutter upgrade`
`flutter doctor --verbose`

If the problem persist,  can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-06-30 15:18
@vinaykumars110 
I hope you've solved the issue.
Closing as additional information isn't provided

**Closed by VladyslavBondarenko** 2020-06-30 15:18 UTC
Labels: in triage, waiting for customer response
