### ISSUE TITLE
MediaQuery PlatformBrightness is not updated on iOS when toggling dark mode during the app is running

### ISSUE THREAD

**Issue by fongja** [flutter/flutter#86064] opened 2021-07-08 03:54 UTC
## Steps to Reproduce

1. Run below example on iPhone iOS 13.7 or iPhone 14.6
2. While the app is up and running
3. Toggle between dark or light mode in iPhone setting or Control Center

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Platform Brightness',
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    Brightness brightness = MediaQuery.of(context).platformBrightness;
    return Scaffold(
      body: Container(
        color: brightness == Brightness.dark ? Colors.black : Colors.white,
        alignment: Alignment.center,
        child: DefaultTextStyle(
          style: TextStyle(
            color: brightness == Brightness.dark ? Colors.white : Colors.black,
            fontSize: 20,
          ),
          child: brightness == Brightness.dark ? Text('DARK') : Text('LIGHT'),
        ),
      ),
    );
  }
}
```

## Expected results:

When Dark or Light mode changed, Flutter should trigger rebuild. 'MediaQuery.of(context).platformBrightness' should get the correct value and UI should update accordingly.

## Actual results:

MediaQuery.of(context).platformBrightness didn't update at all. No rebuild is being triggered and no UI update.

![Jul-08-2021 11-30-58](https://user-images.githubusercontent.com/20963772/124858114-0a18d500-dfe0-11eb-9889-a959e76620b3.gif)

<details>
  <summary>Logs</summary>

```

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/jason/flutter
    • Framework revision f4abaa0735 (6 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jason/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Pixel 4 (mobile)         • 9B061FFAZ00CJQ            • android-arm64  • Android 11 (API 30)
    • iPhone 11 (mobile) • 00008030-000170402290802E • ios            • iOS 13.7
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2021-07-08 14:35
Hi @fongja 
This is a known issue, closing as a duplicate of https://github.com/flutter/flutter/issues/43806

**Closed by TahaTesser** 2021-07-08 14:35 UTC
Labels: in triage
