### ISSUE TITLE
Debug Chrome Error

### ISSUE THREAD

**Issue by pselvaraj-uas** [flutter/flutter#101358] opened 2022-04-05 13:39 UTC
Error : 

           ` ChromeProxyService: Failed to evaluate expression 'window': InternalError: No frame with index 36.
          `

flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale en-AE)
    • Flutter version 2.10.4 at /Users/pselvaraj/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.65.2)
    • VS Code at /Users/pselvaraj/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] VS Code (version 1.66.0)
    • VS Code at /Users/pselvaraj/Downloads/Visual Studio Code 3.app/Contents
    • Flutter extension version 3.38.1

[✓] VS Code (version 1.66.0)
    • VS Code at /Users/pselvaraj/Downloads/Visual Studio Code 4.app/Contents
    • Flutter extension version 3.38.1

[✓] VS Code (version 1.62.1)
    • VS Code at /Users/pselvaraj/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
exit code 0

When I try debug through chrome the chrome doesn't response throws the above error, Cannot debug my app any more.

**Comment by annagrin** [comment] 2022-04-05 22:56
duplicate of https://github.com/flutter/flutter/issues/101224

**Comment by darshankawar** [comment] 2022-04-06 06:37
Closing this as duplicate of linked issue. Please follow-up in it for further updates.

**Closed by darshankawar** 2022-04-06 06:37 UTC
Labels: in triage
