### ISSUE TITLE
Flutter web app not loading in localhost unless restarted / hot reloaded

### ISSUE THREAD

**Issue by kevan-mtl** [flutter/flutter#118381] opened 2023-01-12 12:26 UTC
hi Flutter team,

I am having a weird issue on a Flutter web project I am currently working on. Essentially, the app loads a blank screen in localhost and only loads properly upon hitting "Hot Reload" or "Restart" in the Run / Debug section of VS Code. Once deployed (on Firebase in this case), the behaviour persists and can be witnessed [here](https://operium-website-dev.web.app/). 

Example of a white screen in localhost:
<img width="1195" alt="Screenshot 2023-01-12 at 2 22 20 AM" src="https://user-images.githubusercontent.com/25143586/212065532-42c0c8f2-3347-4480-bd75-179a9eae96b9.png">

I don't see any obvious errors in the console on the browser, nor in the IDE, nor in the debugging console, etc... 

I tested various theories but none proved accurate so far. Here is an extract of my index.html (very standard, except for the Mapbox activation, but I doubt it's the issue).

```
<!DOCTYPE html>
<html>
<head>
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="operium_website">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <!-- map box setup -->
  <script src='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet' />

  <title>operium_website</title>
  <link rel="manifest" href="manifest.json">

  <script>
    // The value below is injected by flutter build, do not touch.
    var serviceWorkerVersion = null;
  </script>
  <!-- This script adds the flutter initialization JS code -->
  <script src="flutter.js" defer></script>

  
</head>
<body>
  <script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
    
  </script>
</body>
</html>
```

I have of course ran `flutter doctor`, results below:

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale
    en-CA)
    • Flutter version 3.3.10 on channel stable at
      /Users/kevansaba/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/kevansaba/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone_12 (mobile) • 3004CBC9-2780-480F-8DD1-4C17624DCC9E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64
      • macOS 13.1 22C65 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Last but not least, I have tested creating a new flutter web test project and it works well -> so my local installation seems fine.

For reference here is my `pubspec.yaml`:

```
name: operium_website
description: Solutions Operium Inc.'s official website
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^5.2.0
  logger: ^1.1.0
  get_it: ^7.2.0
  flutter_svg: ^1.1.6
  sticky_footer_scrollview: ^1.1.1
  intl: ^0.17.0
  dropdown_search: ^5.0.3
  collection: 
  flutter_bloc: ^8.1.1
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.11.0
  flutter_widget_from_html: ^0.9.0+2
  mapbox_gl: ^0.16.0
  dio: ^4.0.6
  fluttertoast: ^8.1.2
  email_validator: ^2.1.17
  google_fonts: ^3.0.1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_web_compilers: ^3.2.7

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/svg_logos/
    - assets/images/app_icons/
    - assets/images/airport_photos/
    - assets/images/svg_flags/
    - assets/images/app_screenshots/
    - assets/images/other_photos/
    - assets/html/privacy_policy/
    - assets/html/acceptable_use_policy/
    - assets/html/terms_of_use/
    - assets/google_fonts/
  ```

Any ideas what could explain this issue? or on how to dig more? I'm running out of ideas...

Thanks in advance,
K

**Comment by exaby73** [comment] 2023-01-12 15:06
Hello @kevan-mtl. Can you see any logs printed in the chrome devtools console?

**Comment by kevan-mtl** [comment] 2023-01-12 19:47
hi @exaby73 ! thanks for your reply!

Here is a screenshot of the chrome devtools console upon starting the app from the Run and Debug panel from VS Code (i can provide the launch.json info if needed). As you can see, nothing renders and the only issue mentioned seems irrelevant (linked to stack tracer):

<img width="557" alt="Screenshot 2023-01-12 at 9 38 02 AM" src="https://user-images.githubusercontent.com/25143586/212165903-a5176e0b-55b2-4b22-833c-8e868e84cbda.png">

When pressing the "Hot Reload" button, everything renders properly:

<img width="1195" alt="Screenshot 2023-01-12 at 9 43 40 AM" src="https://user-images.githubusercontent.com/25143586/212165994-4732834c-798a-426e-94c2-0d3217c89bf3.png">

The only noticeable difference on both the screenshot is the change from `Flutter Web Bootstrap: Programmatic` to `Flutter Web Bootstrap: Auto`. Could this have something to do with my issue?

**Comment by exaby73** [comment] 2023-01-13 07:57
Could you provide a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify the issue?

**Comment by kevan-mtl** [comment] 2023-01-13 10:38
hi @exaby73 ,

Good news I found a fix and a more precise root cause for the issue! Below is a reproducible error. I tracked down the issue to the launch script in the web/index.html file. 

[flutter_web_bug_test.zip](https://github.com/flutter/flutter/files/10410600/flutter_web_bug_test.zip)

The old version of the launch script was:

```
window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
```

This script will not work with the example I provided, however the new default version of the launch script below which Flutter provides seems to work:

```
window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function(engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function(appRunner) {
        return appRunner.runApp();
      });
    });
```

With this simple change on my original project, I'm in business and able to continue working. However, if you know what the issue is with the old launch code, i'd be curious to know :)

**Comment by exaby73** [comment] 2023-01-13 14:57
Was your project generated with an old version of Flutter? Because if so, I believe the script generated has changed in Flutter 3

**Comment by kevan-mtl** [comment] 2023-01-14 21:21
@exaby73 yes, I noticed, but oddly enough the old script works with simple flutter web apps (for instance the default counter app). Hence my question. But, no worries, since I am unblocked, feel free to close this issue if you want.

**Comment by exaby73** [comment] 2023-01-16 07:15
Since this is a known issue and the fix is to update the script in the `index.html` file, I am closing this issue. Thank you

**Closed by exaby73** 2023-01-16 07:15 UTC
Labels: in triage
