### ISSUE TITLE
Go Router state.uri.queryParameters are null

### ISSUE THREAD

**Issue by jsaulsberry-cvet** [flutter/flutter#137519] opened 2023-10-30 06:22 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install Go Router version 12.0.1
2. Setup a Path and in the builder GoRouterState log state.uri.queryParameters
3. Notice that state.uri.queryParameters is null

### Expected results

state.uri.queryParameters should not be null if there are query parameters present int the url

### Actual results

state.uri.queryParameters returns null

### Code sample

<details><summary>Code sample</summary>

```dart
 GoRoute(
                  path: Routes.reset_password_screen,
                  name: Routes.reset_password_screen,
                  builder: (BuildContext context, GoRouterState state) {
                    RouteStream.routeStream.add(state.name);
                    final String? code = state.uri.queryParameters["oobCode"];
                    if (code == null) {
                      return const NotFound();
                    }
                    return ResetPasswordScreen(
                      code: code,
                    );
                  }),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
 Flutter (Channel stable, 3.13.9, on macOS 13.4.1 22F770820d darwin-x64, locale en-US)
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (4 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/la.jamessaulsberry/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/la.jamessaulsberry/Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Alcatel 5004R (mobile) • QOFYWSINAMZHJZEM • android-arm    • Android 10 (API 29)
    • macOS (desktop)        • macos            • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment] 2023-10-30 10:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137513. Please follow up on it for updates.

**Closed by huycozy** 2023-10-30 10:58 UTC
Labels: in triage
