### ISSUE TITLE
Release build of app crash upon opening, flutter 2.2.0

### ISSUE THREAD

**Issue by rh-id** [flutter/flutter#83393] opened 2021-05-26 07:21 UTC
## Steps to Reproduce

1. open google play store and update the app
2. tap to open the app
3. the app shows splash screen
4. the app crash

![Screenshot_20210526-134731_Market Feedback Agent](https://user-images.githubusercontent.com/58564005/119616958-745c2880-be2b-11eb-9f93-4b22478fcbe4.jpg)

Tested Device: Samsung Galaxy S7, Android 8.0.0

Note on few things:
1. The app didn't crash on Oppo A53, Android 10, Color OS V7.2
2. The app works fine on flutter 2.0.5, it seemed to break after updating to 2.2.0 
3. there seemed to be no issue running on debug mode at emulator.
4. The app works fine after clean re-installation. Uninstalling previous version (flutter 2.0.5) and installing the latest app (flutter 2.2.0)

Flutter Doctor:
```
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0 at /home/rubyh/Flutter/flutter
    • Framework revision b22742018b (11 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/rubyh/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/rubyh/Android/Sdk
    • ANDROID_SDK_ROOT = /home/rubyh/Android/Sdk
    • Java binary at: /home/rubyh/Apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.
```

**Comment by TahaTesser** [comment] 2021-05-26 10:27
Hi @rh-id 
Can you please provide your `crash logs` (instead of screenshot), your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by rh-id** [comment] 2021-05-26 12:47
hi @TahaTesser, no `crash logs` the above screenshot is taken upon crash and tapping `Send Feedback`. the app run with no issue with `flutter run --release --verbose` on flutter 2.2.0

Pubspec:
```
name: my_gig_profile
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.4.6+36

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.1
  path: ^1.7.0
  flutter_localizations:
    sdk: flutter
  provider: ^4.3.2
  uuid: ^2.2.2
  path_provider: ^1.6.22
  flutter_typeahead: ^1.8.8
  pdf: ^1.11.2
  intl: ^0.17.0
  open_file: ^3.0.3
  numberpicker: ^1.3.0
  sortedmap: ^0.4.2+1
  android_alarm_manager: '>=0.4.5+17 <2.0.0'
  rxdart: ^0.24.1
  package_info: ^0.4.3+2
  webview_flutter: ^1.0.7
  launch_review: ^2.0.0
  mime: ^0.9.7
  flushbar: ^1.10.4
  image: ^2.1.19
  auto_animated: ^3.0.0
  shared_preferences:
    git:
      url: https://github.com/rh-apps/plugins.git
      ref: app-shared_preferences
      path: packages/shared_preferences/shared_preferences
  flutter_serviceloader_plugin:
    git:
      url: https://github.com/rh-apps/flutter_serviceloader_plugin.git
      ref: app
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

**Comment by TahaTesser** [comment] 2021-05-27 06:50
Hi @rh-id 

> The app works fine after clean re-installation. Uninstalling previous version (flutter 2.0.5) and installing the latest app (flutter 2.2.0)

The crash only after upgrading? You mean there is no crash if the app is installed after uninstalling the previous one? 

and we need complete crash copy/pasted instead of screenshot to address the issue

**Comment by rh-id** [comment] 2021-05-27 07:55
Hi @TahaTesser, there is no issue if doing clean re-install. the issue happened on update only. cannot get the crash log, the `Send Feedback` on android doesn't seemed to send the logs to play console. 

I tested `flutter run --release --verbose` on flutter 2.0.5 on my previous app version to install the app and then `flutter run --release --verbose` on flutter 2.2.0 on my recent app version to install the latest, and for some reason there is no issue, the app can be opened and the functionalities seemed to be fine. not sure if this is caused by google play store.

I can't simulate it again because there seemed to be no way to rollback the play store to previous version. I will just use 2.0.5 for the time being, thanks.

**Comment by TahaTesser** [comment] 2021-05-27 14:12
Hi @rh-id 
Are you publishing apk or appbundle?  The reason we need complete logs in text form so it run crash symbolized, which is not possible from a screenshot

**Comment by rh-id** [comment] 2021-05-28 03:25
Hi @TahaTesser , I'm using appbundle. the app doesn't have built in logs only depend on google play console to report on the crash and stack traces

**Comment by TahaTesser** [comment] 2021-05-28 06:41
Hi @rh-id 
In order to address the issue, please capture production crash logs in some sort of crash report. You can try Sentry for flutter or any other way to get production crash report

**Comment by rh-id** [comment] 2021-05-28 06:58
Hi @TahaTesser the app doesn't use any backend services and have no plans on adding any backend services. It depends on google play console crash report and the stack trace from it as well. As mentioned previously I'm unable to simulate/reproduce it again because google play console doesn't have any option to rollback the release to previous version.  If you couldn't proceed with this issue from the above provided information, you may proceed to close this issue. thanks

**Comment by TahaTesser** [comment] 2021-05-28 12:31
Hi @rh-id 
Since there are no logs in the text form and n reproducible steps to replicate the issue without third-party packages. We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2021-05-28 12:31 UTC
Labels: in triage
