### ISSUE TITLE
LayoutBuilder does not seem to give the correct constraints

### ISSUE THREAD

**Issue by moneer-muntazah** [flutter/flutter#87458] opened 2021-08-02 09:51 UTC
In the following code the constraint I'm getting is much larger then 50. I'm using web.

```dart

MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Padding(
        padding: const EdgeInsets.all(50),
        child: ConstrainedBox(
          constraints: BoxConstraints(maxWidth: 50),
          child: LayoutBuilder(
            builder: (context, constraints) {
              print(constraints.maxWidth);
              return SizedBox();
            },
          ),
        ),
      ),
    );
```

I have no idea why this doesn't print 50 My understanding is that constraints are added to that of the parent. So if the parent has a `maxWidth` of 800 my `ConstrainedBox` should of limited it down to 50 right?

I tried asking elsewhere and no one seems to have an answer.

here is my `flutter doctor -v`

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Moneer\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Moneer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Moneer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)                       • edge          • web-javascript • Microsoft Edge 92.0.902.62

• No issues found!
```

**Comment by xclud** [comment] 2021-08-02 10:06
I tried wrapping your `Padding` with a `Scaffold` and it worked as expected. As far as I know scaffold must be added to the widget tree. Try replacing `SizedBox` with a `Text` and you will see the text looks ugly. I seems the engine is not able to layout without `Scaffold`.

```
return MaterialApp(
  title: 'Flutter Demo',
  theme: ThemeData(
    primarySwatch: Colors.blue,
  ),
  home: Scaffold(
    body: Padding(
      padding: const EdgeInsets.all(50),
      child: ConstrainedBox(
        constraints: const BoxConstraints(maxWidth: 50),
        child: LayoutBuilder(
          builder: (context, constraints) {
            print(constraints.maxWidth);
            return const Text('some text');
          },
        ),
      ),
    ),
  ),
);
```

**Comment by maheshmnj** [comment] 2021-08-02 14:01
@moneer-muntazah this is the expected behavior  constrained box takes the constraints from its parent since you have not defined any widget above the constrained box it by default takes in the screen width and height as its max constraints. regardless of whatever constraints you assign, You can fix this by adding a constrained box within a parent that has defined size like scaffold, Column, ListView etc

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        color: Colors.white,
        title: 'Flutter Demo',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: Material(
          child: Column( ///  this can be ListView, scaffold 
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Padding(
                padding: const EdgeInsets.all(50.0),
                child: ConstrainedBox(
                  constraints: BoxConstraints(maxHeight: 50),
                  child: LayoutBuilder(
                    builder: (context, constraints) {
                      print(constraints.maxHeight);
                      print(constraints.maxWidth);
                      return Container(color: Colors.red);
                    },
                  ),
                ),
              ),
            ],
          ),
        ));
  }
}
```
Closing this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-08-02 14:01 UTC
Labels: in triage
