### ISSUE TITLE
[ImagePicker] preferredCameraDevice: CameraDevice.rear does not work

### ISSUE THREAD

**Issue by aw4git** [flutter/flutter#96114] opened 2022-01-04 13:45 UTC
Hi,
on my Samsung Galaxy S10 (Android 11), trying to opening the rear camera (default parameter) does not work : it is always the front camera that opens. But unfortunately, the main purpose of my function is not to take a selfie ...
The user can still manually switch from front to rear, but it can be a bit tricky.
I am using the latest 0.8.4+4 version. 
PS: surprisingly, it is working fine on a OnePlus (also running Android 11)
Regards,

**Comment by darshankawar** [comment] 2022-01-05 07:10
@aw4git 
This is intended behavior. See this from `image_picker` source code:

```
/// Defaults to [CameraDevice.rear]. Note that Android has no documented parameter for an intent to specify if
  /// the front or rear camera should be opened, this function is not guaranteed
  /// to work on an Android device.
```

https://github.com/flutter/plugins/blob/a10ac2e0d8a8cd878fd0d0a54aa9a87c44c7d7c5/packages/image_picker/image_picker/lib/image_picker.dart#L49

Above change was added in the documentation as part of the this PR : https://github.com/flutter/plugins/pull/3037/

With this, I am closing this as not an issue in the plugin, but a limitation on Android side itself.

**Closed by darshankawar** 2022-01-05 07:10 UTC
Labels: in triage
