### ISSUE TITLE
iOS 10.3 is a thing. Ensuring we have bot coverage

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9053] opened 2017-03-28 17:14 UTC
Tracking issue, but we might want to add 10.3 to our bots.

**Comment by sethladd** [comment] 2017-03-28 17:15
Maybe we have it now?

cc @cbracken @yjbanov

**Comment by cbracken** [comment] 2017-03-28 18:27
As of today, devicelab is still at Xcode 8.2.1 and iOS 10.2.1 but I think we should update this week. iOS 10.3 / Xcode 8.3 are verified to work fine with our toolchain and we should probably migrate the bots later this week.

We did have to make a bunch of engine fixes last month to ensure we were ready for iOS 10.3 working though, so I also filed #8697 (we should have a bot machine running the latest beta).

**Comment by yjbanov** [comment] 2017-03-28 22:19
If we're talking about the devicelab bots, we do not have the capability to _add_ more versions of Xcode to our bots. One reason is we don't have enough bots. The other reason is this would cause quite a bit of maintenance overhead.

However, we can _upgrade_ the _existing_ bots to the latest Xcode. Would that be a good enough fix for this issue?

**Comment by sethladd** [comment] 2017-03-28 23:02
I'd imagine we want a window where we support both 10.2.x and 10.3. Not sure how fast the majority of iOS users will upgrade to 10.3, so I'm not sure how long that window is. But I think for now, we need to test on both versions of the OS. Happy to work with you on a policy for how long we support multiple versions of iOS.

**Comment by cbracken** [comment] 2017-05-24 00:18
@yjbanov do you know if we're on Xcode 8.3 / iOS 10.3 on the devicelab bots now?

**Comment by yjbanov** [comment] 2017-05-24 00:24
Yes, we are.

**Comment by yjbanov** [comment] 2017-05-24 01:13
But also, we're not running the old versions any more.

**Comment by cbracken** [comment] 2017-05-24 01:25
Should we close this as a dupe of #8697?

**Comment by yjbanov** [comment] 2017-05-24 01:45
I'm ok with closing.

**Comment by cbracken** [comment] 2017-05-24 01:46
sgtm!

**Closed by cbracken** 2017-05-24 01:46 UTC
Labels: dev: tests, ⌺‬ platform-ios
