### ISSUE TITLE
Text is not laid out correctly, tested on iOS 

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#151952] opened 2024-07-18 11:00 UTC
### Steps to reproduce

Either `textPainter.layout` is broken or `Text` is laid out wrongly.

In the sample provided below, a text containing some emojis is stated to be rendered over 2 lines (coz text width is bigger than the allowed layout's `maxWidth`). However, text is rendered over 1 line only. By changing the value of `maxWidth` the behaviour changes and results are mostly unpredictable. Another text, which has no emojis,  seems to behave correctly.

Please run the code below and look at the amber-colored container. It should be laid out over 2 lines accordingly to `textPainter` but is instead rendered on one line.

**Why this bug is severe:** Without being able to get correct text width and lines via `textPainter` is impossible to create a "chat bubble" widget. This widget (see whatsapp and the likes) lays down a timestamp next to a message or below it on a separate row. If `textPainter` returns wrong values, it is impossible to understand when the two elements overlap. Also, text rendering is unpredictable.

**Note:** We have always noticed that `textPainter`'s values were not very precise when text contains emojis. However, the error in calculating text-width was small and rendering was consistent enough. After upgrading to latest master 3.24.0-1.0.pre.151 we have been hit by this new issue.

### Expected results

Text should be laid out in a way that is consistent with `textPainter` values and layout constraints. So, if `textPainter` says that text is rendered out over a precise number of lines, we expect that text is really rendered that way.

### Actual results

Wrong result, text in the amber container should be laid out over 2 lines but it is laid out over 1 line only.

<img width="400" src="https://github.com/user-attachments/assets/8e1a6b9c-5b18-46e5-aaa7-4f3853966f92">

Correct result,  text in the amber container is laid out over 2 lines. Correct results occur rarely.

<img width="400" src="https://github.com/user-attachments/assets/d7d82ce3-16f8-482d-8114-cf018875db10">

Correct result for green text, it seems that bug occurs only if text contains emojis

<img width="400" src="https://github.com/user-attachments/assets/3ce603dc-bd74-4151-9ca0-5e3a17dc7283">

### Code sample

<details open><summary>Code sample</summary>

Tested on iphone 13 pro. 

```
import 'dart:math';
import 'dart:ui';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      showPerformanceOverlay: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage()
    );
  }
}

class MyHomePage extends StatefulWidget {

  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    // Note: set .55 to .45 and the text will behave correctly. 
    // This means either that [Text] is not respecting [textPainter.layout]
    // correctly or [textPainter.layout] is broken and return wrong values
    // Note2: Issue seems to not occur if text has no emojis (see: green container)
    double bubbleMaxWidth = 215; //MediaQuery.sizeOf(context).width * .55;
    //double bubbleMaxWidth = MediaQuery.sizeOf(context).width * .45;
    double textMaxWidth = bubbleMaxWidth - 20;

    TextStyle style =  TextStyle(
      fontSize: 17,
      fontWeight: FontWeight.w400,
      textBaseline: TextBaseline.alphabetic,
    );


    return Material(
      type: MaterialType.transparency,
      child: LayoutBuilder(builder: (context, constraints) {
        String text = 'Hello my dear 😍😍😍😍';
        String text2 = 'Hello my dear Hello my dear';
        final textSpan = TextSpan(
          text: text2,
          style: style,
        );
        final textPainter = TextPainter(text: textSpan, textDirection: TextDirection.ltr);
        // Layout textPainter with a maxWidth constraint
        textPainter.layout(maxWidth: textMaxWidth);
        final textLines = textPainter.computeLineMetrics();
        final textWidth = textPainter.width;
        double longestLineWidth = 0;
        for (final line in textLines) {
          longestLineWidth = max(longestLineWidth, line.width);
        }

        // A few prints to let understand what is happening
        print("DEBUG bubbleMaxWidth ${bubbleMaxWidth}");
        print("DEBUG textMaxWidth ${textMaxWidth}");
        print("DEBUG textWidth ${textWidth}");
        print("DEBUG textLines ${textLines}");
        print("DEBUG textLines count ${textLines.length}");
        print("DEBUG lastLineWidth ${textLines.last.width}");
        print("DEBUG longestLineWidth ${longestLineWidth}");

        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[

            // Amber container, text has emoji and text is laid out wrongly
            // on one line, when it should have been laid out on 2 lines.
            Padding(
              padding: EdgeInsets.only(left: 20, right: 20),
              child: Center(child:Container(
                color: Colors.amber,
                width: bubbleMaxWidth-20,
                child: Text(
                  text,
                  style: style.copyWith(color: Colors.white),
                )
              ),)
            ),
            SizedBox(height:20),
            // Green container, text2 has no emoji and text is laid out correctly
            // on two lines
            Padding(
                padding: EdgeInsets.only(left: 20, right: 20),
                child: Center(child:Container(
                    color: Colors.lightGreen,
                    width: bubbleMaxWidth-20,
                    child: Text(
                      text2,
                      style: style.copyWith(color: Colors.white),
                    )
                ),)
            )
        ]);
      }),
    );

  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.24.0-1.0.pre.151, on macOS 14.2.1 23C71 darwin-arm64, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
```

</details>

**Comment by navaronbracke** [comment] 2024-07-18 11:53
Does this reproduce with Impeller disabled?

**Comment by darshankawar** [comment] 2024-07-18 12:45
@delfme 
I see the same reported behavior in latest stable and master versions on iOS and Android. Although on Android emulator, I also see the green content in one line:

<img width="266" alt="Screenshot 2024-07-18 at 6 13 47 PM" src="https://github.com/user-attachments/assets/a58648c1-4e49-4df8-8468-f00a92adba92">



When you say regression, do you know in which previous version it worked before you upgraded to latest master ?

Also, I noticed that you are always on master version which is upgraded everyday and may break things.

**Comment by delfme** [comment] 2024-07-18 12:46
@darshankawar just noticed that the error was caused by using a difference value for the Container width, it should be
`width: bubbleMaxWidth -20,`
instead of
`width: bubbleMaxWidth.`
I fixed this in the sample code.

But can you guys have a check if the width's values returned by `textPainter` are really precise?

**Comment by delfme** [comment] 2024-07-18 13:00
Im not sure, but I think, `textPainter` is not precise when returning text width when text contains emojis. Prolly due to the emoji size issue. Would it be possible to return the text of each lineMetric?

For example, instead of
```
[LineMetrics(hardBreak: false, ascent: 16.1865234375, descent: 4.1005859375, unscaledAscent: 16.1865234375, height: 20.0, width: 184.4599609375, left: 0.0, baseline: 15.8994140625, lineNumber: 0), LineMetrics(hardBreak: true, ascent: 16.1865234375, descent: 4.1005859375, unscaledAscent: 16.1865234375, height: 20.0, width: 36.0087890625, left: 0.0, baseline: 35.8994140625, lineNumber: 1)]
```
Having something like:
```
[LineMetrics(hardBreak: false, ascent: 16.1865234375, descent: 4.1005859375, unscaledAscent: 16.1865234375, height: 20.0, width: 184.4599609375, left: 0.0, baseline: 15.8994140625, lineNumber: 0, lineText: "Hello my dear 😍"), LineMetrics(hardBreak: true, ascent: 16.1865234375, descent: 4.1005859375, unscaledAscent: 16.1865234375, height: 20.0, width: 36.0087890625, left: 0.0, baseline: 35.8994140625, lineNumber: 1, lineText: "😍😍😍")]
```
Where I have added property `lineText` inside each `LineMetrics`.

**Advantages:**  That extra data would allow us to better check the width values and correct value when emoji are inside text by, for example, adding a multiplier in pixel for each emoji inside the line. This way, even if flutter still cannot render emoji size precisely, we can workaround issue by increasing emoji size and also correct width value returned by `textPainter`, if required.

**Comment by LongCatIsLooong** [comment] 2024-07-18 16:14
`TextPainter`'s painting logic depends on line breaking, and painting is done per line. If in the `layout` method text painter determines there's one line then it's very unlikely that there will be glyphs on the second line. 

What you are seeing is usually because the text painter that renders text (usually in a `Text` widget) and the text painter you are using to measure the text have different configurations (`TextStyle`s for example).

**Comment by delfme** [comment] 2024-08-18 11:00
Hello, my apologies for the belated reply, the notification got lost in my inbox.

@LongCatIsLooong The text style configuration is the same. Will try to create a new example but basically what we noticed is that flutter engine fails to assign a correct measure to text with. For example, we have to apply a "delta" amount of px for each white space (does flutter trim the text before calculating the width?) and also apply corrections when inside the text there are emojis (since they are not rendered properly on iOS, both size and letterspacing https://github.com/flutter/flutter/issues/28894)

**Comment by huycozy** [comment] 2024-08-19 07:02
Reproduced this on `Channel stable, 3.24.0` and `Channel master, 3.24.0-1.0.pre.623`. I observe the different results between iOS and Android devices. Keeping this for further input.

| iOS (iPhone 7, iOS 15.8) | Android (Pixel 7, Android 14) |
| --------------- | --------------- |
<img width="400" src="https://github.com/user-attachments/assets/904b773c-3252-4f47-999a-4c33e1430a72"> | <img width="400" src="https://github.com/user-attachments/assets/f0269b9e-3de6-4cd0-934e-94eb2520ea17">

**Comment by LongCatIsLooong** [comment] 2024-08-19 17:14
The  `Text` widget inherits styles from the ambient `DefaultTextStyle` which I don't think the TextPainter in the sample code does.

See: https://main-api.flutter.dev/flutter/widgets/Text/build.html,

**Comment by delfme** [comment] 2024-08-21 19:32
@LongCatIsLooong I dont get this, what the sample code should be?

**Comment by delfme** [comment] 2024-08-21 19:40
Also, is there a sample code used by flutter team to test that textPainter's data is precise? Coz I get unconsistent results when emojis are in the text and also it seems that the pixels assigned to white spaces are not correct.

**Comment by LongCatIsLooong** [comment] 2024-08-23 05:39
> @LongCatIsLooong I dont get this, what the sample code should be?

The `Text` widget merges its style with the ambient text style in the widget tree. So it's likely that you're using a different TextStyle in your TextPainter. Material3 typography uses a non-zero letter spacing so that could make a difference.
```
  final DefaultTextStyle defaultTextStyle = DefaultTextStyle.of(context);
  TextStyle? effectiveTextStyle = style;
  if (style == null || style!.inherit) {
    effectiveTextStyle = defaultTextStyle.style.merge(style);
  }
  if (MediaQuery.boldTextOf(context)) {
    effectiveTextStyle = effectiveTextStyle!.merge(const TextStyle(fontWeight: FontWeight.bold));
  }
```

**Comment by delfme** [comment] 2024-08-23 13:26
Sample code uses system font, just set fontSize and regular fontWeight. 
```
 TextStyle style =  TextStyle(
      fontSize: 17,
      fontWeight: FontWeight.w400,
      textBaseline: TextBaseline.alphabetic,
    );
```

It is more likely that this is a bug. As mentioned, we get inconsistent results from TextPainter, especially when emoji are inside the text, but also when they are not. It would be helpful if we could see the code used to debug TextPainter. I have no clue about how TextPainter calculates the lines' width, but my best guess is that there are issues with assigning the correct width-value to punctuation symbols, white spaces, and emojis. Hence, the more the text is longer (or the more emojis), and the more the issue is noticeable.

**Comment by delfme** [comment] 2024-08-23 16:12
Here is an example.
We have two bubbles (see 1 and 2), and an "widgets overlapping" issue inside bubble 1. The width of last line returned by TextPainter is wrong by some pixels. There are 3 white spaces and if we increase the width by adding a multiplier for `whiteSpacesCount`, we patch the issue. This is why I was asking if text maybe gets trimmed before lines' width is calculated. If that is the case, it would be a bug.

Same issue occurs when emojis are inside the text (with is wrong and we must apply a correction factor). Can you guys please mention who could shed more light on that?

![Screenshot_2024-08-23-18-00-56-366_is presence app](https://github.com/user-attachments/assets/6165723d-a680-43b4-b611-7ace4c03f1e8)

**Comment by delfme** [comment] 2024-08-23 16:41
Idk if `right` can be easily added to `LineMetrics`.

If so, a quick check to gain more info about the issue would be getting `right` and print below log. If it returns 'false', that would mean that `textLines.last.width` is indeed wrong.
```
final textLines = textPainter.computeLineMetrics();
print('textLines.last.right == textLines.last.left + textLines.last.width')
```

In that case, having `right` would also provide a way to workaround issue, coz we would prevent that collision by comparing `textLines.last.right` with the right rect's `left`.

**Comment by delfme** [comment] 2024-08-23 21:44
@LongCatIsLooong can rawText be exposed inside `LineMetrics`? This way we could quickly access `textPainter.computeLineMetrics().last.rawText` and correct last line's width.

**Comment by LongCatIsLooong** [comment] 2024-08-23 22:03
Are you looking for https://main-api.flutter.dev/flutter/painting/TextPainter/getLineBoundary.html?

**Comment by delfme** [comment] 2024-08-23 23:03
I'd need to get the text of last line, see pic below.
I see that 
```
final range = textPainter.getLineBoundary(const TextPosition(offset:0));
```
gives me the index of first string. If I understood it correctly, I should iterate all lines so to update Offset of subsequent line in order to eventually get last line range indexes and then substring the whole text to get the last line's text :-/

Isn't it possible to simple expose line's text as a metric? Sort of
`textPainter.computeLineMetrics().last.rawText`
or equivalent?

![Screenshot_2024-08-23-18-00-56-366_is presence app](https://github.com/user-attachments/assets/4d35927a-29e4-41a1-b382-305209f82b08)

**Comment by delfme** [comment] 2024-08-23 23:11
Note: I saw other open issues where people get inconsistent results: sometime correct ones and other times wrong ones. Style is almost blamed for that, but from what I see, it might be an issue (skia?) with computing width for white spaces and emojis. That would explain why sometimes the result looks correct (if text is short or has a few white spaces, or if text has no emojis).

In any event, by exposing the raw text of each line, we would for now adjust the width for these edge cases.

**Comment by LongCatIsLooong** [comment] 2024-08-24 00:00
If you dump the render tree in the sample app here's the style used:

```dart
                       ╎                                       └─child: RenderParagraph#d287a relayoutBoundary=up5
                       ╎                                         │ creator: RichText ← Text ← ColoredBox ← ConstrainedBox ←
                       ╎                                         │   Container ← Center ← Padding ← Column ← LayoutBuilder ←
                       ╎                                         │   DefaultTextStyle ← AnimatedDefaultTextStyle ←
                       ╎                                         │   _InkFeatures-[GlobalKey#d141f ink renderer] ← ⋯
                       ╎                                         │ parentData: <none> (can use size)
                       ╎                                         │ constraints: BoxConstraints(w=195.0, 0.0<=h<=Infinity)
                       ╎                                         │ size: Size(195.0, 147.0)
                       ╎                                         │ textAlign: start
                       ╎                                         │ textDirection: ltr
                       ╎                                         │ softWrap: wrapping at box width
                       ╎                                         │ overflow: clip
                       ╎                                         │ textScaler: linear (2.0x)
                       ╎                                         │ locale: en_US
                       ╎                                         │ maxLines: unlimited
                       ╎                                         ╘═╦══ text ═══
                       ╎                                           ║ TextSpan:
                       ╎                                           ║   debugLabel: ((englishLike bodyMedium
                       ╎                                           ║     2021).merge((blackMountainView
                       ╎                                           ║     bodyMedium).apply)).merge(unknown)
                       ╎                                           ║   inherit: false
                       ╎                                           ║   color: Color(0xffffffff)
                       ╎                                           ║   family: Roboto
                       ╎                                           ║   size: 17.0
                       ╎                                           ║   weight: 400
                       ╎                                           ║   letterSpacing: 0.3
                       ╎                                           ║   baseline: alphabetic
                       ╎                                           ║   height: 1.4x
                       ╎                                           ║   leadingDistribution: even
                       ╎                                           ║   decoration: Color(0xff1d1b20) TextDecoration.none
                       ╎                                           ║   "Hello my dear Hello my dear"
                       ╎                                           ╚═══════════
```

This is not the same style used by the painter.

**Comment by delfme** [comment] 2024-08-24 07:13
No idea where that letterspacing comes from, sample code assigns no letter-spacing. Maybe it is the result of the style merge? If so, I don't see how to avoid this issue by code.

**Comment by delfme** [comment] 2024-08-24 07:20
> I'd need to get the text of last line, see pic below. I see that
> 
> ```
> final range = textPainter.getLineBoundary(const TextPosition(offset:0));
> ```
> 
> gives me the index of first string. If I understood it correctly, I should iterate all lines so to update Offset of subsequent line in order to eventually get last line range indexes and then substring the whole text to get the last line's text :-/
> 
> Isn't it possible to simple expose line's text as a metric? Sort of `textPainter.computeLineMetrics().last.rawText` or equivalent?
> 
> ![Screenshot_2024-08-23-18-00-56-366_is presence app](https://private-user-images.githubusercontent.com/53510751/361078737-4d35927a-29e4-41a1-b382-305209f82b08.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0ODM1NjgsIm5iZiI6MTcyNDQ4MzI2OCwicGF0aCI6Ii81MzUxMDc1MS8zNjEwNzg3MzctNGQzNTkyN2EtMjllNC00MWExLWIzODItMzA1MjA5ZjgyYjA4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwNzA3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjkyOTA0MWE3NjE4NzM0MjY3Zjk2ZTY3ODE3Yzk0MzY0NTM2MjZkMjYyYTBhYTg5YjU4NWI5MzhkNGI1MDM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1GqN6fvV2_z55q6qIdhjpQIHtFmla-SLHVg5ufbonOU)


Can this or equivalent be done? Just thought that `rawText` would be required for only the `last` line, or maybe `first` and `last`. The engine lays out the lines and knows the `rawText` of each line, if you guys can expose rawText for these edge lines somewhere, that would be much helpful.

Note: have you tried sample code with a perfect matching style? I have read comments elsewhere where people still get wrong results, which might be due to white-spaces and emojis.

**Comment by delfme** [comment] 2024-08-27 12:28
@LongCatIsLooong found a way to get what needed. Paste code below in case it is useful to others.

```
  Future<String?> calculateLastText(TextSpan textSpan, TextPainter textPainter) async {
    List<String> lineTexts = [];
    if (textSpan.text != null ) {
      String rawText = textSpan.text!;
      List<TextBox> boxes = textPainter.getBoxesForSelection(
          TextSelection(baseOffset: 0, extentOffset: textSpan.text!.length));
      int start = 0;
      int end;
      // Loop through each text box to populate lineTexts
      for (final box in boxes) {
        var lineBoundary = textPainter.getLineBoundary(TextPosition(offset:start));
        end = lineBoundary.end;
        start = end;
        var lineText = rawText.substring(lineBoundary.start, lineBoundary.end);
        lineTexts.add(lineText);
      }
    }
    // Return last line rawText
    print("DEBUG: last line text ${lineTexts.last}");
    return lineTexts.last;
  }
```

### WHEN THIS CODE CAN BE USEFUL:
`TextPainter` sometimes fail to return precise values for the lines' width.
This workaround is based on the idea of extracting the last line's rawText and then apply correction to textPainter's last line's width accordingly to rawText. For example, width can be increased/decreased based on whether last line's text contain emojis, etc. Also, a width can be calculated only for last line, in case TextPainter is more precise with one-line text that are no longer impacted by the text wrap.

**Comment by delfme** [comment] 2024-08-27 13:59
Also providing mockups to showcase the results we have been able to achieve with the above workaround. 
From our tests, we think that the issue is maybe not from flutter but from skia. We noticed that the failures are somehow related to the presence of **emojis** and **whitespaces** in the text (prolly also **punctuation**).

As you can see from pic below, **text** and **timestamp** never overlaps. This was achieved by extracting last line rawText and use it to correct the last line's width returned by textPainter. The corrections depends on the number of white spaces and number of emojis inside the last line. The same test reported below fails if we trust textPainter as a source of truth, no matter the `letterSpacing` and `DefaultTextStyle`.

![1724766162789](https://github.com/user-attachments/assets/06d3ce7b-4dec-4157-ba58-a49a7dd43748)

![1724766162786](https://github.com/user-attachments/assets/a475351c-77be-41b9-ad83-8985a76e7be6)

**Comment by loic-sharma** [comment] 2024-09-11 21:11
@LongCatIsLooong Should this be a text input team bug? Feel free to reassign back to us if this is an iOS bug.

**Comment by justinmc** [comment] 2024-09-26 22:20
Sounds like the bug might lie in @delfme's user code here? I'll close this, but let me know if I'm wrong and there's something we should be tracking in the framework here.

**Closed by justinmc** 2024-09-26 22:20 UTC
Labels: platform-ios, framework, engine, a: typography, has reproducible steps, team-text-input, found in release: 3.24
