### ISSUE TITLE
Flutter crash report - Web rendering

### ISSUE THREAD

**Issue by jaiparkashsingh** [flutter/flutter#117676] opened 2022-12-27 09:42 UTC
Flutter crash report.

## command

flutter run -d c --web-renderer html

## exception

StateError: Bad state: Future already completed

```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      ChromeProxyService.createIsolate.<anonymous closure> (package:dwds/src/services/chrome_proxy_service.dart:260:25)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, 3.7.0-5.0.pre.3, on macOS 13.0.1 22A400 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.7.0-5.0.pre.3 on channel master at /Users/jp/opt/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision eefbe85c8b (3 weeks ago), 2022-12-08 22:32:07 -0600
    [32m•[39m Engine revision 8d83b98c55
    [32m•[39m Dart version 3.0.0 (build 3.0.0-0.0.dev)
    [32m•[39m DevTools version 2.20.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    [32m•[39m Android SDK at /Users/jp/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 31.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14B47b
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.74.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version null

[32m[✓][39m Connected device (3 available)
    [32m•[39m Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 9 (API 28) (emulator)
    [32m•[39m macOS (desktop)                      • macos         • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    [32m•[39m Chrome (web)                         • chrome        • web-javascript • Google Chrome 108.0.5359.124

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!
```

**Comment by huycozy** [comment] 2022-12-27 11:20
@jaiparkashsingh Does this issue only happen with `html` renderer? Can you provide the complete output of `flutter run -v` (with the corresponding affected renderer)?

Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thank you!

**Comment by jaiparkashsingh** [comment] 2022-12-27 11:41
Hi,

Thanks for your reply.

There is not a specific case or scenario to reproduce the submitted bug. I
was working on my app, when all of sudden it crashed. As per log message,
it says to report it as a bug report, which I did.

Please let me know, if you have any further query on the same.

Thanks and Regards,
Jai
91-93122-77816

**Comment by jaiparkashsingh** [comment] 2022-12-27 11:47
Hi,

Just got a fresh one.

https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+StateError%3A+Bad+state%3A+Future+already+completed&body=%23%23+Command%0A%60%60%60%0Aflutter+run+-d+c+--web-renderer+html%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AStateError%3A+Bad+state%3A+Future+already+completed%0A%60%60%60%0A%230++++++_AsyncCompleter.complete+%28dart%3Aasync%2Ffuture_impl.dart%3A35%3A31%29%0A%231++++++ChromeProxyService.createIsolate.%3Canonymous+closure%3E+%28package%3Adwds%2Fsrc%2Fservices%2Fchrome_proxy_service.dart%3A260%3A25%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel+master%2C+3.7.0-5.0.pre.3%2C+on+macOS+13.0.1+22A400+darwin-arm64%2C+locale+en-IN%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.7.0-5.0.pre.3+on+channel+master+at+%2FUsers%2Fjp%2Fopt%2Fflutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Framework+revision+eefbe85c8b+%283+weeks+ago%29%2C+2022-12-08+22%3A32%3A07+-0600%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+8d83b98c55%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+3.0.0+%28build+3.0.0-0.0.dev%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+version+2.20.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+31.0.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+%2FUsers%2Fjp%2FLibrary%2FAndroid%2Fsdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platform+android-33%2C+build-tools+31.0.0%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+binary+at%3A+%2FApplications%2FAndroid+Studio.app%2FContents%2Fjre%2FContents%2FHome%2Fbin%2Fjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B0-b1504.28-7817840%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses+accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Xcode+-+develop+for+iOS+and+macOS+%28Xcode+14.1%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Xcode+at+%2FApplications%2FXcode.app%2FContents%2FDeveloper%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Build+14B47b%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+CocoaPods+version+1.11.3%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+%2FApplications%2FGoogle+Chrome.app%2FContents%2FMacOS%2FGoogle+Chrome%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+Studio+%28version+2021.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+at+%2FApplications%2FAndroid+Studio.app%2FContents%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B0-b1504.28-7817840%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.74.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+%2FApplications%2FVisual+Studio+Code.app%2FContents%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+null%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%283+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+built+for+arm64+%28mobile%29+%E2%80%A2+emulator-5554+%E2%80%A2+android-arm64++%E2%80%A2+Android+9+%28API+28%29+%28emulator%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+macOS+%28desktop%29++++++++++++++++++++++%E2%80%A2+macos+++++++++%E2%80%A2+darwin-arm64+++%E2%80%A2+macOS+13.0.1+22A400+darwin-arm64%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28web%29+++++++++++++++++++++++++%E2%80%A2+chrome++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+108.0.5359.124%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+HTTP+Host+Availability%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+required+HTTP+hosts+are+available%0A%0A%1B%5B32m%E2%80%A2%1B%5B39m+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B4%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+master%0A%2A%2ACreation+framework+version%2A%2A%3A+eefbe85c8bd4185a087cd83251e552be326568ad%0A%23%23%23+Plugins%0Acloud_firestore_web-3.1.1%0Adevice_info_plus-4.1.3%0Adevice_info_plus_linux-3.0.0%0Adevice_info_plus_macos-3.0.0%0Adevice_info_plus_web-3.0.0%0Adevice_info_plus_windows-4.1.0%0Afirebase_core-2.4.0%0Afirebase_core_web-2.0.2%0Afirebase_crashlytics-3.0.7%0Afirebase_messaging-14.1.4%0Afirebase_messaging_web-3.2.9%0Amap_launcher-2.4.0%0Apath_provider-2.0.11%0Apath_provider_android-2.0.22%0Apath_provider_ios-2.0.11%0Apath_provider_linux-2.1.7%0Apath_provider_macos-2.0.6%0Apath_provider_windows-2.1.3%0Ashared_preferences-2.0.15%0Ashared_preferences_android-2.0.14%0Ashared_preferences_ios-2.1.1%0Ashared_preferences_linux-2.1.2%0Ashared_preferences_macos-2.0.4%0Ashared_preferences_web-2.0.4%0Ashared_preferences_windows-2.1.2%0Asqflite-2.2.2%0Aurl_launcher-6.1.7%0Aurl_launcher_android-6.0.22%0Aurl_launcher_ios-6.0.17%0Aurl_launcher_linux-3.0.1%0Aurl_launcher_macos-3.0.1%0Aurl_launcher_web-2.0.13%0Aurl_launcher_windows-3.0.1%0Avideo_player-2.4.9%0Avideo_player_android-2.3.9%0Avideo_player_avfoundation-2.3.7%0Avideo_player_web-2.0.12%0Awakelock-0.6.2%0Awakelock_macos-0.4.0%0Awakelock_web-0.4.0%0Awebview_flutter-2.8.0%0Awebview_flutter_android-2.10.4%0Awebview_flutter_wkwebview-2.9.5%0A%0A&labels=tool%2Csevere%3A+crash


Thanks and Regards,
Jai
91-93122-77816

**Comment by huycozy** [comment] 2022-12-28 04:33
>I was working on my app, when all of sudden it crashed

Do you use or configure proxy settings on Chrome? Also, do you remember what action you took before the issue occurred? (`hot reload` or `restart` for example)

**Comment by christopherfujino** [comment] 2023-01-03 20:23
This is the top crasher on the current beta release, 3.7.0-1.2.pre.

**Comment by christopherfujino** [comment] 2023-01-03 21:05
cc @elliette

**Comment by elliette** [comment] 2023-01-03 22:43
`AppConnection` has its own `_startedCompleter` which is completed when `runMain` is called: [code link](https://github.com/dart-lang/webdev/blob/b6439072d118b740fbc2d0e5af4e10952642d864/dwds/lib/src/connections/app_connection.dart#L37)

`ChromeProxyService` also has its own `_startedCompleter` which is completed with the `AppConnection`'s `_startedCompleter` is completed: [code link](https://github.com/dart-lang/webdev/blob/b6439072d118b740fbc2d0e5af4e10952642d864/dwds/lib/src/services/chrome_proxy_service.dart#L260).
**This is the completer that is throwing an error due to already being completed.** It was added in  https://github.com/dart-lang/webdev/pull/1704. 

A simple fix would be to simply not try to complete it if it's already completed, but I'm guessing this indicates a larger underlying issue. I will need to do more investigating to figure out why this is being called twice.

**Comment by christopherfujino** [comment] 2023-01-03 22:59
> `AppConnection` has its own `_startedCompleter` which is completed when `runMain` is called: [code link](https://github.com/dart-lang/webdev/blob/b6439072d118b740fbc2d0e5af4e10952642d864/dwds/lib/src/connections/app_connection.dart#L37)
> 
> `ChromeProxyService` also has its own `_startedCompleter` which is completed with the `AppConnection`'s `_startedCompleter` is completed: [code link](https://github.com/dart-lang/webdev/blob/b6439072d118b740fbc2d0e5af4e10952642d864/dwds/lib/src/services/chrome_proxy_service.dart#L260). **This is the completer that is throwing an error due to already being completed.** It was added in [dart-lang/webdev#1704](https://github.com/dart-lang/webdev/pull/1704).
> 
> A simple fix would be to simply not try to complete it if it's already completed, but I'm guessing this indicates a larger underlying issue. I will need to do more investigating to figure out why this is being called twice.

That sounds good to me, thanks for taking a look!

**Comment by elliette** [comment] 2023-01-03 23:25
A few more notes:

DWDS tries to complete the completer any time `createIsolate` is called. It is called a few times in the codebase (see [list]( https://github.com/search?q=repo%3Adart-lang%2Fwebdev%20createIsolate&type=code)). Most likely when the error was encountered it was called as [this `unawaited` future](https://github.com/dart-lang/webdev/blob/8795ca5b89df0f912e31b0f5fa372b90f2a0bf66/dwds/lib/src/services/chrome_proxy_service.dart#L169) (since we are missing stack trace info).

On a page refresh, the `_startedCompleter` is reset: [code link](https://github.com/dart-lang/webdev/blob/8795ca5b89df0f912e31b0f5fa372b90f2a0bf66/dwds/lib/src/services/chrome_proxy_service.dart#L343). If `createIsolate` is called and there hasn't been a refresh, then the completer would already be complete. 

It's pretty hard to track down exactly what's happened without a stacktrace / way to repro, but since the `startedCompleter` in  `ChromeProxyService` is essentially a duplicate of the `startedCompleter` in `AppConnection`, I think we can remove it and just depend on the one in `AppConnection`.

**Comment by elliette** [comment] 2023-01-04 00:17
I understand this a bit more. The reason the changes in https://github.com/dart-lang/webdev/pull/1704 were made was to try to guarantee that the debugger was paused when doing stack frame calculations. I think for clarity the check for whether the debugger is paused should happen as part of `debugger.getStackTrace` and not from the chrome proxy service call site. 

It looks like the test that this was trying to fix ended up getting disabled afterwards anyways (https://github.com/dart-lang/webdev/pull/1751) so it  should be safe to just completely revert https://github.com/dart-lang/webdev/pull/1704 . 

Follow up work to fix the test and re-enable the tests will be tracked at https://github.com/dart-lang/webdev/issues/1749

**Comment by annagrin** [comment] 2023-01-04 23:06
I was not able to repro the crash. To any reporters - please share a reliable repro if available, or the steps you have taken before the crash (what is the command you are running, did you use hot restart, breakpoints, etc).

I was able to re-create another error using the current dwds version - if you hot restart fast twice, dwds fails to evaluate 'true' to prewarm expression compiler cache. This does not cause a crash, but gives us the idea that 2 createIsolate calls can interleave. We can fix this and see if it helps the original issue.

**Closed** 2023-01-10 21:23 UTC
Labels: tool, platform-web, P3
