### ISSUE TITLE
'package:flutter/src/material/tabs.dart': Failed assertion: line 609 pos 15: 'indicator != null || (indicatorWeight != null && indicatorWeight > 0.0)': is not true.

### ISSUE THREAD

**Issue by luhongwei123** [flutter/flutter#47643] opened 2019-12-23 03:28 UTC
## Steps to Reproduce

1. 
```dart
return new AppBar(
        elevation: 0.1,
        backgroundColor:Color(0xffffffff),
        title: TabBar(
          controller: controller,
          tabs: tabs,
          isScrollable: true,
          indicator: UnderlineTabIndicator(
                borderSide:BorderSide(width: 0.0, color: Colors.white),
                insets :EdgeInsets.zero,
              ),
          indicatorWeight: 0.01,
          indicatorSize: TabBarIndicatorSize.tab,
          indicatorPadding : EdgeInsets.zero,
          // labelPadding: EdgeInsets.only(left: 20),
          labelColor: Colors.pinkAccent,
          
          labelStyle: TextStyle(
            fontSize: 15.0,
          ),
          unselectedLabelColor: Colors.grey,
          unselectedLabelStyle: TextStyle(
            fontSize: 12.0,
          ),
        ),
        bottom: new TextSearcher()
      );
```
2. `flutter run`

**Target Platform:**  Linux
**Target OS version/browser:** Manjaro Linux 5.4.2-1 
**Devices:**  Android emulator

## Logs

```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
I/flutter (11233): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11233): The following assertion was thrown building AppScene(dirty, state: _AppSceneState#789a4(ticker
I/flutter (11233): inactive)):                                          
I/flutter (11233): 'package:flutter/src/material/tabs.dart': Failed assertion: line 609 pos 15: 'indicator != null ||
I/flutter (11233): (indicatorWeight != null && indicatorWeight > 0.0)': is not true.
I/flutter (11233):                                                      
I/flutter (11233): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11233): more information in this error message to help you determine and fix the underlying cause.
I/flutter (11233): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (11233):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (11233):                                                      
I/flutter (11233): The relevant error-causing widget was:               
I/flutter (11233):   AppScene file:///home/luhongwei/projects/xiongmao_app/lib/main.dart:12:13
I/flutter (11233):                                                      
I/flutter (11233): When the exception was thrown, this was the stack:   
I/flutter (11233): #2      new TabBar (package:flutter/src/material/tabs.dart:609:15)
I/flutter (11233): #3      _AppSceneState.dynamicAppBar (package:xiongmao_app/root/app_scence.dart:135:16)
I/flutter (11233): #4      _AppSceneState.build (package:xiongmao_app/root/app_scence.dart:54:15)
I/flutter (11233): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (11233): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (11233): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (11233): #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (11233): #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (11233): #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (11233): #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (11233): #13     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
I/flutter (11233): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (11233): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (11233): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (11233): (elided 3 frames from class _AssertionError and package dart:async-patch)
I/flutter (11233):                                                      
I/flutter (11233): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11233): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11233): The following assertion was thrown building AppScene(dirty, state: _AppSceneState#789a4(ticker
I/flutter (11233): inactive)):                                          
I/flutter (11233): 'package:flutter/src/material/tabs.dart': Failed assertion: line 609 pos 15: 'indicator != null ||
I/flutter (11233): (indicatorWeight != null && indicatorWeight > 0.0)': is not true.
I/flutter (11233):                                                      
I/flutter (11233): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11233): more information in this error message to help you determine and fix the underlying cause.
I/flutter (11233): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (11233):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (11233):                                                      
I/flutter (11233): The relevant error-causing widget was:               
I/flutter (11233):   AppScene file:///home/luhongwei/projects/xiongmao_app/lib/main.dart:12:13
I/flutter (11233):                                                      
I/flutter (11233): When the exception was thrown, this was the stack:   
I/flutter (11233): #2      new TabBar (package:flutter/src/material/tabs.dart:609:15)
I/flutter (11233): #3      _AppSceneState.dynamicAppBar (package:xiongmao_app/root/app_scence.dart:135:16)
I/flutter (11233): #4      _AppSceneState.build (package:xiongmao_app/root/app_scence.dart:54:15)
I/flutter (11233): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (11233): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (11233): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (11233): #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (11233): #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (11233): #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (11233): #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (11233): #13     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
I/flutter (11233): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (11233): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (11233): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (11233): (elided 3 frames from class _AssertionError and package dart:async-patch)
I/flutter (11233):                                                      
I/flutter (11233): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11233): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11233): The following assertion was thrown building AppBar(dirty, dependencies: [_ModalScopeStatus,
I/flutter (11233): _LocalizationsScope-[GlobalKey#2606b], _InheritedTheme], state: _AppBarState#a0737):
I/flutter (11233): 'package:flutter/src/animation/curves.dart': Failed assertion: line 43 pos 12: 't >= 0.0 && t <=
I/flutter (11233): 1.0': is not true.                                   
I/flutter (11233):                                                      
I/flutter (11233): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11233): more information in this error message to help you determine and fix the underlying cause.
I/flutter (11233): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (11233):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (11233):                                                      
I/flutter (11233): The relevant error-causing widget was:               
I/flutter (11233):   AppBar file:///home/luhongwei/projects/xiongmao_app/lib/root/app_scence.dart:132:18
I/flutter (11233):                                                      
I/flutter (11233): When the exception was thrown, this was the stack:   
I/flutter (11233): #2      Curve.transform (package:flutter/src/animation/curves.dart:43:12)
I/flutter (11233): #3      _AppBarState.build (package:flutter/src/material/app_bar.dart:444:85)
I/flutter (11233): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (11233): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (11233): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11233): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11233): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11233): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #17     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11233): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11233): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #23     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (11233): #24     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (11233): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #28     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11233): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11233): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11233): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11233): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (11233): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (11233): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11233): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11233): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11233): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #60     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (11233): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #64     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (11233): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (11233): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (11233): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (11233): #68     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (11233): #69     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (11233): #70     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (11233): #71     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (11233): #72     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (11233): #73     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
I/flutter (11233): #75     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (11233): #76     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (11233): #77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (11233): (elided 3 frames from class _AssertionError and package dart:async-patch)
I/flutter (11233):                                                      
I/flutter (11233): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12698): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12698): The following assertion was thrown building AppScene(dirty, state: _AppSceneState#4e6ec(ticker
I/flutter (12698): inactive)):                                          
I/flutter (12698): 'package:flutter/src/material/tabs.dart': Failed assertion: line 609 pos 15: 'indicator != null ||
I/flutter (12698): (indicatorWeight != null && indicatorWeight > 0.0)': is not true.
I/flutter (12698):                                                      
I/flutter (12698): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12698): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12698): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12698):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (12698):                                                      
I/flutter (12698): The relevant error-causing widget was:               
I/flutter (12698):   AppScene file:///home/luhongwei/projects/xiongmao_app/lib/main.dart:13:13
I/flutter (12698):                                                      
I/flutter (12698): When the exception was thrown, this was the stack:   
I/flutter (12698): #2      new TabBar (package:flutter/src/material/tabs.dart:609:15)
I/flutter (12698): #3      _AppSceneState.dynamicAppBar (package:xiongmao_app/root/app_scence.dart:135:16)
I/flutter (12698): #4      _AppSceneState.build (package:xiongmao_app/root/app_scence.dart:53:15)
I/flutter (12698): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (12698): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (12698): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12698): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (12698): #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (12698): #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (12698): #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (12698): #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (12698): #13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (12698): #17     _invoke (dart:ui/hooks.dart:259:10)          
I/flutter (12698): #18     _drawFrame (dart:ui/hooks.dart:217:3)        
I/flutter (12698): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (12698):                                                      
I/flutter (12698): ════════════════════════════════════════════════════════════════════════════════════════════════════
Running Gradle task 'assembleDebug'...                 
```

## Flutter analyze & doctor

```
Analyzing xiongmao_app...                                               
No issues found! (ran in 1.6s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/luhongwei/Android/flutter
    • Framework revision 27321ebbad (12 天前), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/luhongwei/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/luhongwei/Android/Sdk
    • Java binary at: /home/luhongwei/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at /home/luhongwei/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by janmoppel** [comment] 2019-12-23 08:01
Hello @luhongwei123 !

Thank you for posting an issue.
Seems like a similar case to #38483.

**Comment by shihaohong** [comment] 2019-12-23 20:29
I created [a gist](https://gist.github.com/shihaohong/470820fa2d0f4e83ff06e797d420a818) with the sample you provided and could not reproduce the issue. 

Since `TextSearcher` has to be a `PreferredSizeWidget`, it might be the case that it's a `TabBar` with an inappropriately defined `indicator` or `indicatorWeight`? Please update the your example with more details.

**Comment by shihaohong** [comment] 2019-12-23 20:32
Also, it might be the case that you might have accidentally put the `TabBar` in `AppBar.title`. I would imagine that your widget would look more like: 
```
Scaffold(
      appBar: AppBar(
        title: Text('Title of the AppBar'),
        bottom: TabBar(
          controller: controller,
          tabs: tabs,
          indicator: UnderlineTabIndicator(
            borderSide: BorderSide(width: 0.0, color: Colors.white),
            insets: EdgeInsets.zero,
          ),
          indicatorWeight: 0.01,
          indicatorSize: TabBarIndicatorSize.tab,
          indicatorPadding : EdgeInsets.zero,
        ),
      ),
      body: Center(child: Text('Hello World')),
    );
```

**Comment by luhongwei123** [comment] 2019-12-23 23:29
thinks😃



---Original---

**Comment by shihaohong** [comment] 2019-12-24 01:47
Did you figure out the problem? If you did, we should close this issue :)

**Comment by shihaohong** [comment] 2019-12-26 19:58
I will close this issue for now since I assumed you have figured it out! Please feel free to reopen with more information if otherwise!

**Closed by shihaohong** 2019-12-26 19:58 UTC
Labels: f: material design, framework, severe: crash
