### ISSUE TITLE
showTimePicker theme

### ISSUE THREAD

**Issue by xiaofei9070** [flutter/flutter#75128] opened 2021-02-01 09:34 UTC
This _TimePickerHeader can't update background color, cur version is 1.20

**Comment by pedromassangocode** [comment] 2021-02-01 10:35
Closing as duplicate of https://github.com/flutter/flutter/issues/58493.

**Comment by HansMuller** [comment] 2021-02-01 18:08
CC @darrenaustin 
Should this really be closed as as a duplicate of #58493?

**Comment by darrenaustin** [comment] 2021-02-01 21:01
@HansMuller is correct, this isn't a dup of #58493, as this is referring to the Time picker not the Date picker.

As to the issue, here, can you give us more information on what you are trying to configure @xiaofei9070?

You should be able to customize the look of the time picker with either `Theme.colorScheme`, or directly with the `ThemeData.timePickerTheme` (specifically the `TimePickerThemeData.backgroundColor`).

**Comment by pedromassangocode** [comment] 2021-02-03 09:00
Yes, this does not seems to be a duplicate of #58493.

@xiaofei9070 please provide your `flutter doctor -v` as well.

**Comment by pedromassangocode** [comment] 2021-02-26 13:16
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-26 13:16 UTC
Labels: f: material design, framework, waiting for customer response
