### ISSUE TITLE
Runner.app size is about 414mb. How to reduce it?

### ISSUE THREAD

**Issue by charanjsingh29** [flutter/flutter#51827] opened 2020-03-03 09:03 UTC
I build IOS app using
<code>flutter build ios --release</code>
<strong>The build size of RUNNER.APP is 414 mb.</strong>
I searched online and also tried <strong>switching to stable channel, but results are same.</strong>

**Actual results:** 
![Screenshot 2020-03-03 at 2 29 02 PM](https://user-images.githubusercontent.com/46475573/75759552-ccf16280-5d5b-11ea-9d07-4200efd98605.png)

<details>
  <summary>Logs</summary>

```
```
## Flutter analyze

Analyzing ecommerce...                                                  

   info • Name non-constant identifiers using lowerCamelCase • lib/blocs/SyncBloc.dart:388:15 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/database/CartTable.dart:147:45 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/database/CartTable.dart:147:59 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/database/CategoryTable.dart:90:49 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/database/CategoryTable.dart:90:63 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/database/OrderItemTable.dart:77:43 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/database/ProductTable.dart:321:35 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CartModel.dart:16:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CartModel.dart:17:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CartModel.dart:24:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CartModel.dart:25:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:14:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:15:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:16:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:17:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:18:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:19:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:20:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:21:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:22:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:23:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:27:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:28:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:29:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:30:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:31:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:32:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:33:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:34:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:35:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/CategoryModel.dart:36:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:16:7 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:17:7 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:18:7 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:19:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:20:7 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:21:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:22:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:26:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:27:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:28:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:29:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:30:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:31:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderItemModel.dart:32:10 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:14:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:15:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:16:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:17:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:18:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:19:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:20:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:21:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:22:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:23:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:26:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:27:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:28:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:29:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:30:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:31:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:32:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:33:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:34:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/OrderModel.dart:35:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:14:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:15:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:16:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:17:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:18:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:19:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:20:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:21:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:22:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:23:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:24:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:25:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:28:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:29:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:30:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:31:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:32:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:33:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:34:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:35:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:36:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:37:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:38:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/models/ProductModel.dart:39:10 • non_constant_identifier_names
   info • The member 'positions' can only be used within instance members of subclasses of
          'package:flutter/src/widgets/scroll_controller.dart' • lib/pages/Product - Copy.dart:104:50 •
          invalid_use_of_protected_member
   info • The declaration '_onScroll' isn't referenced • lib/pages/Product - Copy2.dart:150:8 • unused_element
   info • The declaration '_goToPage' isn't referenced • lib/pages/Product - Copy2.dart:169:8 • unused_element
   info • The declaration '_updateStream' isn't referenced • lib/pages/Product - Copy2.dart:175:8 • unused_element
   info • The member 'activity' can only be used within 'package:flutter/src/widgets/scroll_position.dart' or a test •
          lib/pages/Product - Copy3.dart:169:37 • invalid_use_of_visible_for_testing_member
   info • The member 'activity' can only be used within instance members of subclasses of
          'package:flutter/src/widgets/scroll_position.dart' • lib/pages/Product - Copy3.dart:169:37 •
          invalid_use_of_protected_member
   info • The member 'activity' can only be used within 'package:flutter/src/widgets/scroll_position.dart' or a test •
          lib/pages/Product - Copy3.dart:170:35 • invalid_use_of_visible_for_testing_member
   info • The member 'activity' can only be used within instance members of subclasses of
          'package:flutter/src/widgets/scroll_position.dart' • lib/pages/Product - Copy3.dart:170:35 •
          invalid_use_of_protected_member
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance
          fields are not final: ShowWeight.melting • lib/pages/ProductDetail.dart:338:7 • must_be_immutable
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance
          fields are not final: AppInfo.failedDownloads • lib/pages/Sync.dart:46:7 • must_be_immutable

99 issues found. (ran in 4.3s)

```
```
## Flutter Doctor
✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/vebieestudio/Development/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vebieestudio/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 13.0.2+8)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```
```

</details>

**Comment by TahaTesser** [comment] 2020-03-03 09:16
Hi @charanjsingh29 

[Measuring your app's size](https://flutter.dev/docs/perf/app-size#ios)
Please look at these comments [comment](https://github.com/flutter/flutter/issues/47101#issuecomment-567522077) and [comment](https://github.com/flutter/flutter/issues/45519#issuecomment-568935022rl)

Duplicate of [#47101](https://github.com/flutter/flutter/issues/47101)
Closing as such 
Thank you

**Closed by TahaTesser** 2020-03-03 09:16 UTC
