### ISSUE TITLE
Flutter Shortcuts - Removing from one portion of my app

### ISSUE THREAD

**Issue by cracklye** [flutter/flutter#105684] opened 2022-06-09 10:06 UTC
I have set up shortcuts for my app which apply to all the widgets.  However I have a few text fields in the widget tree that I want to exclude the Shortcuts from.  Is there any way I can do this? 

While my app is a lot more complicated, the following code demonstrates what I want to do.  I have a shortcut of a, ctrl+a, Left/Right arrows set up which will print a message to the console (when the button has focus).  However when I am in the text fields and try and type 'a' it calls the shortcut rather than adding the 'a' to the text in the widget.    I tried using the following: 
- wrapping the text field DefaultTextEditingShortcuts (the arrows work but not the a) 
- Adding a new shortcut round the text field
- Adding a new shortcut round the text field with a new shortcut manager

How would I exclude the TextBoxes from the shortcuts above without applying the shortcuts to just the button - in my actual app this would mean wrapping lots of widgets in the same shortcuts which seems an overhead I wanted to avoid.

```

class TestIntent extends Intent {
  final String message;
  const TestIntent(this.message);
}

class MyApp extends StatelessWidget {
  const MyApp({key});

  static const String title = 'Shortcuts Issue';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: title,
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          appBar: AppBar(
            title: const Text("Test Overriding Shortcut"),
          ),
          body: Shortcuts(
              //manager: LoggingShortcutManager(),
              shortcuts: <LogicalKeySet, Intent>{
                LogicalKeySet(LogicalKeyboardKey.keyA):
                    const TestIntent("a Pressed"),
                LogicalKeySet(
                        LogicalKeyboardKey.keyA, LogicalKeyboardKey.control):
                    const TestIntent("ctrl + a Pressed"),
                LogicalKeySet(LogicalKeyboardKey.arrowLeft):
                    const TestIntent("left arrow Pressed"),
                LogicalKeySet(LogicalKeyboardKey.arrowRight):
                    const TestIntent("right arrow Pressed"),
              },
              child: Actions(
                  actions: {
                    TestIntent: CallbackAction<TestIntent>(
                        onInvoke: (intent) =>
                            print("Called Intent ${intent.message}"))
                  },
                  child: Column(
                    children: [
                      ElevatedButton(
                          onPressed: () => print("clicked"),
                          child: const Text("Representing lots of widgets")),
                      const Text(
                          "Plain Field - typing a doesn't add the text, and using left or right arrow doesn't move cursor"),
                      const TextField(),
                      const Text(
                          "Field with DefaultTextEditingShortcuts - left/right arrows now work but a doesn't"),
                      DefaultTextEditingShortcuts(child: const TextField()),
                      const Text(
                          "Field with new shortcut - inherits from previous"),
                      const Shortcuts(
                          child: TextField(),
                          shortcuts: <LogicalKeySet, Intent>{}),
                      const Text(
                          "Field with new shortcut and new manager - still seems to inherits from previous"),
                      Shortcuts(
                          manager: ShortcutManager(),
                          child: const TextField(),
                          shortcuts: const <LogicalKeySet, Intent>{}),
                    ],
                  ))),
        ));
  }
}

void main() => runApp(const MyApp());
```

**Comment by exaby73** [comment] 2022-06-09 11:59
Hello @cracklye. You can achieve what you need by the following code. `ShortcutManager` has a `modal` field ([read more here](https://api.flutter.dev/flutter/widgets/ShortcutManager/modal.html)) that if set to `true`, will stop the propagation of key presses to ancestor shortcut managers.

<details><summary>Code sample</summary>

```dart
Shortcuts(
  manager: ShortcutManager(modal: true),
  shortcuts: const <LogicalKeySet, Intent>{},
  child: DefaultTextEditingShortcuts(
    child: const TextField(),
  ),
),
```

</details>

Setting `modal` to `true` in my opinion should also catch the arrow key shortcuts. Though in this case it doesn't. Which is why I also wrapped it in a `DefaultTextEditingShortcuts` widget. Hope this is a suitable solution for you. Closing this issue since this is not a bug or feature request.

**Closed by exaby73** 2022-06-09 11:59 UTC
Labels: in triage
