### ISSUE TITLE
Swift flutter plugin breaks flutter module and generates wrong paths for config files.

### ISSUE THREAD

**Issue by shehabic** [flutter/flutter#23277] opened 2018-10-18 23:35 UTC
I have created a very basic flutter plugin here:  
https://github.com/shehabic/dhplugin
and used it in this module:
https://github.com/shehabic/flutter-test-module
this module is supposed to be the module that will have all the customer plugin we'll create in our company, we import this module into our existing apps and it'll grab all of our custom plugins with it.

I've spent 5 days now having trouble with and I couldn't get it to work.
here is the error:

## Steps to Reproduce

1. Checkout the module above
2. Run ```flutter packages get```
3. Run ```flutter build ios --debug```

## Logs

```
Building com.shehabic.module.mymodule for device (ios)...
Signing iOS app for device deployment using developer identity: "iPhone Developer: My Name (TeamNumber)"
Starting Xcode build...
Xcode build done.                                            9.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET flutter_webview_plugin OF PROJECT Pods WITH CONFIGURATION Debug ===
    dhplugin.xcconfig line 12: Unable to find included file "../.ios/Flutter/Generated.xcconfig"
    dhplugin.xcconfig line 13: Unable to find included file "../.ios/Flutter/Generated.xcconfig"
    === BUILD TARGET flutter_webview_plugin OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/shehabic/development/flutter/.pub-cache/git/dhplugin-d25caf5fc30cf036675d3e2a4fab393243f112f2/ios/Classes/DhpluginPlugin.m:2:9: fatal error:
    'dhplugin/dhplugin-Swift.h' file not found
    #import <dhplugin/dhplugin-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    flutter_webview_plugin.xcconfig line 11: Unable to find included file "../.ios/Flutter/Generated.xcconfig"
    flutter_webview_plugin.xcconfig line 12: Unable to find included file "../.ios/Flutter/Generated.xcconfig"
    /Users/shehabic/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1+2/ios/Classes/FlutterWebviewPlugin.m:71:22: warning: incompatible pointer
    to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id _Nullable' [-Wint-conversion]
        _enableAppScheme = call.arguments[@"enableAppScheme"];
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/shehabic/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1+2/ios/Classes/FlutterWebviewPlugin.m:244:78: warning: values of type
    'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
        id data = [FlutterError errorWithCode:[NSString stringWithFormat:@"%ld", error.code]
                                                                           ~~~   ^~~~~~~~~~
                                                                           %ld   (long)
    /Users/shehabic/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.2.1+2/ios/Classes/FlutterWebviewPlugin.m:254:102: warning: values of type
    'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
            [channel invokeMethod:@"onHttpError" arguments:@{@"code": [NSString stringWithFormat:@"%ld", response.statusCode], @"url": webView.URL.absoluteString}];
                                                                                                   ~~~   ^~~~~~~~~~~~~~~~~~~
                                                                                                   %ld   (long)
    3 warnings generated.
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.10.1-pre.78, on Mac OS X 10.14 18A391, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2017.3.2)
[✓] VS Code (version 1.28.2)
[!] Connected device
    ! No devices available
```

**Comment by shehabic** [comment] 2018-10-18 23:37
The second time I run it I get
```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET dhplugin OF PROJECT Pods WITH CONFIGURATION Debug ===
    flutter_webview_plugin.xcconfig line 11: Unable to find included file "../.ios/Flutter/Generated.xcconfig"
    flutter_webview_plugin.xcconfig line 12: Unable to find included file "../.ios/Flutter/Generated.xcconfig"
    === BUILD TARGET dhplugin OF PROJECT Pods WITH CONFIGURATION Debug ===
    dhplugin.xcconfig line 12: Unable to find included file "../.ios/Flutter/Generated.xcconfig"
    dhplugin.xcconfig line 13: Unable to find included file "../.ios/Flutter/Generated.xcconfig"
    === BUILD TARGET dhplugin OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/shehabic/development/flutter/.pub-cache/git/dhplugin-d25caf5fc30cf036675d3e2a4fab393243f112f2/ios/Classes/DhpluginPlugin.m:2:9: fatal error:
    'dhplugin/dhplugin-Swift.h' file not found
    #import <dhplugin/dhplugin-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    /Users/shehabic/development/flutter/.pub-cache/git/dhplugin-d25caf5fc30cf036675d3e2a4fab393243f112f2/ios/Classes/DhpluginPlugin.m:2:9: fatal error:
    'dhplugin/dhplugin-Swift.h' file not found
    #import <dhplugin/dhplugin-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by zhouweidong** [comment] 2018-11-09 08:04
I face the same problem when update to flutter 0.11.0, anyone solved?

**Comment by jmagman** [comment] 2019-07-30 00:39
Seems related to the Swift podspec not enabling module headers http://blog.cocoapods.org/CocoaPods-1.5.0/
Adding s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' } to the dhplugin podspec wasn't enough and I still see that issue.
This works when I add `use_frameworks!` to the module Podfile.  
Swapping `dhplugin-Swift.h` from a system import to a project worked when the pods were installed as dynamic libraries, but it breaks installing them as frameworks.

**Comment by jmagman** [comment] 2019-09-19 03:33
See https://github.com/flutter/flutter/issues/25676 and https://github.com/CocoaPods/CocoaPods/issues/7594#issuecomment-381930381.

**Comment by jmagman** [comment] 2019-10-10 00:28
Workaround is to update the plugin implementation import:
```objective-c
#if __has_include(<test_swift_plugin/test_swift_plugin-Swift.h>)
#import <test_swift_plugin/test_swift_plugin-Swift.h>
#else
#import "test_swift_plugin-Swift.h"
#endif
```
So in your case:
```objective-c
#if __has_include(<dhplugin/dhplugin-Swift.h>)
#import <dhplugin/dhplugin-Swift.h>
#else
#import "dhplugin-Swift.h"
#endif
```

**Comment by jmagman** [comment] 2019-10-10 00:34
https://github.com/flutter/flutter/issues/25676 is a duplicate of this, but that one has more context and comments, so I'm going to close this one.  Sorry about that!
Duplicate of https://github.com/flutter/flutter/issues/25676.

**Closed** 2019-10-10 19:58 UTC
Labels: p: framework, severe: crash, tool, ⌺‬ platform-ios
