### ISSUE TITLE
local_auth no cancel possibility for onscreen fingerprint

### ISSUE THREAD

**Issue by Samotron1105** [flutter/flutter#35616] opened 2019-07-05 04:35 UTC
Hi guys,

I'm using and debugging with my OnePlus 7 Pro which has an onscreen fingerprint. Unfortunately using local_auth to use that fingerprint shows up location of that sensor like wanted, but there is no option to cancel that operation.
When I use android's back button it pops my page, but fingerprint keeps on display.
Also there is no method inside LocalAuthentication to cancel operation.

**Comment by SamuelMTDavies** [comment] 2019-07-30 19:54
I've also had this issue on a Mate20 Pro. Have you found a workaround? I haven't had a chance to look at it in my code yet.

I have been thinking to use face ID over fingerprint where both are available.

**Comment by Samotron1105** [comment] 2019-08-08 08:41
No workaround yet.
Since authentication were one of the first features of my app, there is still a lot of time, until I will release it. So there is no urgent need for me to fix this bug or so.

Hopefully there will some cancel option soon.
Also when using it beside entering a PIN and the user enters the PIN correctly, the indisplay fingerprint will not disappear and is still visible.

**Comment by SamuelMTDavies** [comment] 2019-09-11 14:20
Hi @sethladd,

I just wanted to draw this to your attention to see if this can be assigned to the correct person with the Flutter team. It's really poor UX and is currently stopping me from releasing a production app. 

I hope this isn't poor form to @ you in the comments.

Best,

Sam

**Comment by masewo** [comment] 2019-09-26 09:51
Oneplus devices do not show up the "original" modal screen so that might be the problem. I am also affected by this issue.
![image](https://user-images.githubusercontent.com/6759840/65678623-ec20f100-e053-11e9-9c99-3f3ff1d0bbc0.png)

**Comment by matthewrice345** [comment] 2019-11-05 17:19
The only way currently to fix this is to modify the `local_auth` plugin with your own code. I tried adding the androidx biometric library and use the cancelBiometrics function with no luck. After digging into the code it's because the library uses an atomic boolean to prevent resetting the authentication progress state. 

I added something like this to the `LocalAuthPlugin.java`: 

`   else if (call.method.equals("cancelBiometrics")) {
            Activity activity = registrar.activity();
            if (activity == null || activity.isFinishing()) {
              result.error("no_activity", "local_auth plugin requires a foreground activity", null);
              return;
            }
            authInProgress.compareAndSet(true, false);
        } else {
            result.notImplemented();
        }`

Then a function to call it from the dart plugin `LocalAuthentication.dart`:

`  Future<bool> cancelBiometrics() async {
    final Map<String, Object> args = <String, Object>{
      'localizedReason': "",
      'useErrorDialogs': false,
      'stickyAuth': false,
    };

    AndroidAuthMessages androidAuthStrings = const AndroidAuthMessages();
    IOSAuthMessages iOSAuthStrings = const IOSAuthMessages();

    if (_platform.isIOS) {
      args.addAll(iOSAuthStrings.args);
    } else if (_platform.isAndroid) {
      args.addAll(androidAuthStrings.args);
    } else {
      throw PlatformException(
          code: otherOperatingSystem,
          message: 'Local authentication does not support non-Android/iOS '
              'operating systems.',
          details: 'Your operating system is ${_platform.operatingSystem}');
    }

    return await _channel.invokeMethod<bool>("cancelBiometrics", args);
  }`

Once that code exists I can call cancelBiometrics whenever I need too.

**Comment by SamuelMTDavies** [comment] 2019-11-05 18:31
@matthewrice345 not had a chance to try this but if it works then we'll done, great work. 

Maybe worth a pull request to add it the the package?

**Comment by matthewrice345** [comment] 2019-11-05 18:35
I just noticed that 6 days ago work was done to fix this https://github.com/flutter/plugins/pull/2111 @SamuelMTDavies

**Comment by masewo** [comment] 2019-12-27 22:53
I can confirm that flutter/plugins#2111 fixes this issue. You only have to call stopAuthentication e. g. in your dispose override.

**Comment by sohitEngg** [comment] 2020-01-14 04:16
In latest version of local_auth package, there is method to cancel it.

Use localAuth.cancelAuthentication()

**Comment by Renatinaveen** [comment] 2020-05-21 12:16
I'm having issues with on screen finger print. First thing there's no dialog showing up. If an unregistered fingerprint is used the scanner just disappear and the error will be auth_in_progress. But when it comes to ios and hardware fingerprints there's no issue.

This is my main activity

import android.os.Bundle
import io.flutter.app.FlutterFragmentActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
override fun onCreate(savedInstanceState: Bundle?) {
super.onCreate(savedInstanceState)
GeneratedPluginRegistrant.registerWith(this)
}
}

**Comment by DineshBanksathi** [comment] 2021-02-18 06:27
I'm having issues with onePlus6T mobile  on screen finger print. If an unregistered fingerprint is used the scanner just disappear and local_auth not triggering any event, i am unable to perform action on wrong fingerprint event.

please give us any solution or any update idea

**Comment by stuartmorgan** [comment] 2021-04-02 20:06
Closing, as this was fixed by flutter/plugins#2111. Please file new issues for unrelated bugs.

**Closed by stuartmorgan** 2021-04-02 20:06 UTC
Labels: p: local_auth, plugin, severe: new feature
