### ISSUE TITLE
Flutter Image widget load local image too slow

### ISSUE THREAD

**Issue by EflakeEver** [flutter/flutter#26580] opened 2019-01-15 09:42 UTC
The case is simple

I was trying to use a simple Image Widget to load a fullscreen local image as a splash page, but I have found that regardless the image size, it was always too slow for loading local image. It causes a little moment of white screen between the initial open image and splash page, please tell me the reason or any solution to solve this problem, thanks.

the code is simply just like that:

```dart
 Container(
              width: DeviceUtil.getScreenWidth(context),
              height: DeviceUtil.getScreenHeight(context),
              child: Image.asset(
                "images/splash_bg.png",
                fit: BoxFit.cover,
              ),
            ),
```

**Comment by wouterhardeman** [comment] 2019-01-15 09:47
Have you tried a release build? Debug builds are very slow because of debug features like hot reloading.

**Comment by zoechi** [comment] 2019-01-15 09:59
Duplicate of #26127

Also related #25713

**Closed by zoechi** 2019-01-15 09:59 UTC

**Comment by EflakeEver** [comment] 2019-01-16 01:47
> Have you tried a release build? Debug builds are very slow because of debug features like hot reloading.

I have tried this in release mode and it works fine, thank you

**Comment by dineshsy** [comment] 2019-09-16 08:27
> > Have you tried a release build? Debug builds are very slow because of debug features like hot reloading.
> 
> I have tried this in release mode and it works fine, thank you

What is release mode? Because I have the same issue.

**Comment by arsalanrex** [comment] 2019-10-01 23:32
> > > Have you tried a release build? Debug builds are very slow because of debug features like hot reloading.
> > 
> > 
> > I have tried this in release mode and it works fine, thank you
> 
> What is release mode? Because I have the same issue.
Go to the location of the flutter app and use the following command:
`flutter build apk --release`
It should save a release version of the app in /build/app/outputs/apk/release/
Also the release apk is quite smaller in size than the debug version of the app.

**Comment by kadnan0900** [comment] 2019-12-02 10:11
After i release a build but still i am facing the same issue. Please guide me in proper way Thanks

**Comment by moslem-deris** [comment] 2020-03-04 21:34
Try using this code before `return` of your application root widget to cache the image before you attempt to use the image:
`precacheImage(AssetImage("images/splash_bg.png"), context);`

**Comment by Emex4gman** [comment] 2020-04-11 14:09
> Try using this code before `return` of your application root widget to cache the image before you attempt to use the image:
> `precacheImage(AssetImage("images/splash_bg.png"), context);`

tried this, but it still takes a sec to load
