### ISSUE TITLE
[go_router] 9.0.3 context.pushReplacementNamed("/path"); doesn't update the URL anymore.

### ISSUE THREAD

**Issue by ps6067966** [flutter/flutter#130650] opened 2023-07-15 04:06 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Use this in latest version of go_router in flutter web :- context.pushReplacementNamed("/path")

### Expected results

Url should update.

### Actual results

show full url in browser

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2023-07-17 08:59
@ps6067966 Please check the migration guide at [Migrating to 8.0.0](https://flutter.dev/go/go-router-v8-breaking-changes) for more information and check my [previous comment](https://github.com/flutter/flutter/issues/129893#issuecomment-1617762284) as well.

Closing this issue since it's changed as intended.

**Closed by huycozy** 2023-07-17 08:59 UTC
Labels: in triage

**Comment by ps6067966** [comment] 2023-07-17 09:05
@huycozy  Thank you so much for helping. 
Using this as per document that you shared 
GoRouter.optionURLReflectsImperativeAPIs = true;
Issue is fixed. 

But i wanted to know is there any new way of writing code in go_router 9.0.3 
as i'm not finding any documentation for this.

**Comment by huycozy** [comment] 2023-07-17 09:10
You can check the [Changlog](https://pub.dev/packages/go_router/changelog) for updates and package's [Readme](https://pub.dev/packages/go_router) for details.
