### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by Super-Crab** [flutter/flutter#21635] opened 2018-09-10 09:12 UTC
I/flutter (18291): The following assertion was thrown building Index(dirty, state: IndexState#1315d):
I/flutter (18291): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1656 pos 14:
I/flutter (18291): '!children.any((Widget child) => child == null)': is not true.

**Comment by Super-Crab** [comment] 2018-09-10 09:13
import 'package:flutter/material.dart';
import 'package:flutter_app/widget/banner.dart';

import 'package:flutter_app/http/HttpUtil.dart';
import 'package:flutter_app/http/Api.dart';

import '../widget/WebViewWidget.dart';
import '../widget/ToolBar.dart';

class Index extends StatefulWidget {
  @override
  IndexState createState() => new IndexState();
}

class IndexState extends State<Index> {

  BannerView _bannerView;
  var bannerData;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Stack(
        children: <Widget>[
          _bannerView,
          new Align(
            alignment: FractionalOffset.topRight,
            child: new Container(
              width: 1000.0,
              color: const Color(0x50000000),
              padding: const EdgeInsets.all(25.0),
              child: new ToolBar(),
            ),
          )
        ],
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    getBanner();
  }

  void getBanner() {
    HttpUtil.get(Api.BANNER, (data) {
      if (data != null) {
        setState(() {
          bannerData = data;
          _bannerView = new BannerView(
              data: bannerData,
              onBannerClickListener: (index, data) {
                var imgUrl = data['url'];
                var title = data['title'];
                Navigator.of(context).push(new MaterialPageRoute(
                    builder: (ctx) => new WebViewWidget(imgUrl,title)
                ));
              });
        });
      }
    });
  }
}

**Comment by Super-Crab** [comment] 2018-09-10 09:14
class Index extends StatefulWidget {
  @override
  IndexState createState() => new IndexState();
}

class IndexState extends State<Index> {

  BannerView _bannerView;
  var bannerData;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Stack(
        children: <Widget>[
          _bannerView,
          new Align(
            alignment: FractionalOffset.topRight,
            child: new Container(
              width: 1000.0,
              color: const Color(0x50000000),
              padding: const EdgeInsets.all(25.0),
              child: new ToolBar(),
            ),
          )
        ],
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    getBanner();
  }

  void getBanner() {
    HttpUtil.get(Api.BANNER, (data) {
      if (data != null) {
        setState(() {
          bannerData = data;
          _bannerView = new BannerView(
              data: bannerData,
              onBannerClickListener: (index, data) {
                var imgUrl = data['url'];
                var title = data['title'];
                Navigator.of(context).push(new MaterialPageRoute(
                    builder: (ctx) => new WebViewWidget(imgUrl,title)
                ));
              });
        });
      }
    });
  }
}

**Comment by zoechi** [comment] 2018-09-11 10:09
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2018-09-11 10:12
`getBanner();` only assigns a widget instance to `_bannerView` when `data != null` and therefore when `build()` is called the first time `_bannerView` in 
```dart
        children: <Widget>[
          _bannerView,
```
is `null` which is what the exception is about.

Closing as working as intended.

**Closed by zoechi** 2018-09-11 10:12 UTC
