### ISSUE TITLE
EditableText text not align

### ISSUE THREAD

**Issue by wenerme** [flutter/flutter#19935] opened 2018-07-28 04:58 UTC
## Steps to Reproduce

```dart
        Container(
          decoration: BoxDecoration(
            border: Border.all(color: Colors.blue),
          ),
          padding: const EdgeInsets.all(8.0),
          margin: const EdgeInsets.all(8.0),
          child: EditableText(
            controller: new TextEditingController(text: "123你好WM1😄"),
            focusNode: new FocusNode(),
            style: TextStyle(fontSize: 14.0, color: Colors.black),
            cursorColor: Colors.lightBlueAccent,
          ),
        ),
```

I don't expect the content pulled up when deleting.

![out](https://user-images.githubusercontent.com/1777211/43353232-867c5e62-9265-11e8-88ff-61b4ee4f6ef1.gif)

## Logs

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G2112, locale en-CN)
    • Flutter version 0.5.7 at ~/gits/flutter
    • Framework revision 66091f9696 (3 weeks ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Users/wener/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • iPhone X • 902675A6-F27B-42EC-B1DC-68E28B70E0DB • ios • iOS 11.4 (simulator)

! Doctor found issues in 3 categories.
```

**Comment by jason-simmons** [comment] 2018-08-07 22:46
All text in a line will be aligned vertically at the same baseline.  If text spans with different fonts are added to a line, then the baseline will adjust to allow the maximum ascent of any font within the line.

**Comment by pedromassangocode** [comment] 2020-07-23 11:28
Hi @wenerme 
I can't reproduce this on the current `dev` and `stable` channel of Flutter. 

![Kapture 2020-07-23 at 12 25 53](https://user-images.githubusercontent.com/67424416/88281509-b84c4180-ccdf-11ea-9b51-cdef70c320e7.gif)


I'm assuming that this issue was fixed so I'm going to close it. Please comment bellow if you disagree and I will reopen it.

Thank you.

<details>
<summary> Complete sample code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          decoration: BoxDecoration(
            border: Border.all(color: Colors.blue),
          ),
          padding: const EdgeInsets.all(8.0),
          margin: const EdgeInsets.all(8.0),
          child: EditableText(
            backgroundCursorColor: Colors.black,
            controller: new TextEditingController(text: "123你好WM1😄"),
            focusNode: new FocusNode(),
            style: TextStyle(fontSize: 14.0, color: Colors.black),
            cursorColor: Colors.lightBlueAccent,
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-AO)
    • Flutter version 1.21.0-1.0.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision f25bd9c55c (8 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe)
    ! /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe is not
      executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server (web)             • web-server    • web-javascript • Flutter
      Tools

! Doctor found issues in 1 category.
```
</details>

**Closed by pedromassangocode** 2020-07-23 11:28 UTC
Labels: P4, a: text input, a: typography, framework
