### ISSUE TITLE
`flutter_tester` process is not terminated when a test run is terminated

### ISSUE THREAD

**Issue by wurikiji** [flutter/flutter#144222] opened 2024-02-27 12:24 UTC
### Steps to reproduce

1. write any test (Sample below)

```dart
import 'dart:developer';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('test', () {
    test('dummy', () {
      debugger();
    });
  });
}
```

2. Add breakpoint. `debugger()` sets the breakpoint on the sample. Run a test using VSCode's `Debug test` feature. (See an image below)
![image](https://github.com/flutter/flutter/assets/5652744/53b4cb3e-c6ae-4e66-b083-68d710ea430b)

3. When the debugger pauses, stop the test runner. (Right-most button in the image below). 
![image](https://github.com/flutter/flutter/assets/5652744/9f7ad97a-2744-451f-8284-31d2aad1ccaa)

4. See the `Activity Monitor` app or run `ps -ef |grep flutter_tester` in terminal.

5. `flutter_tester` process is not terminated.

### Expected results

`flutter_tester` process must be terminated.

### Actual results

`flutter_tester` process is not terminated but accumulated. It ends up with memory pressure.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:developer';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('test', () {
    test('dummy', () {
      debugger();
    });
  });
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

After running tests multiple times.

![image](https://github.com/flutter/flutter/assets/5652744/5cf12832-8612-4c52-888b-d18b2ea166af)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-KR)
    • Flutter version 3.19.1 on channel stable at /Users/wain/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (7 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/wain/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 122.0.6261.69

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-02-28 07:33
Thanks for the report @wurikiji 
There's a related [issue](https://github.com/flutter/flutter/issues/20949) that you can check and see if it resembles your case or not.
If not, for your case, is there a way for you to check if it only occurs using vscode only and not if you directly try to run and debug via terminal / command line outside of IDE ?

**Comment by darshankawar** [comment] 2024-02-29 05:25
Thanks for the update. Yes, I also tried with AS with which I wasn't able to replicate. I don't have VSCode, so can't confirm it, but based on your findings, I'll label it for team's attention / input.

/cc @DanTup for thoughts.

**Comment by DanTup** [comment] 2024-02-29 11:29
I can also repro on Windows, so not Mac-specific.

**Comment by DanTup** [comment] 2024-02-29 11:34
On Windows I can actually easily reproduce this from a terminal. Using the test above, run with:

```
 flutter test .\test\widget_test.dart
```

Wait until the counter is counting up (because the test paused, even though there's no debugger) and then press Ctrl+C. The `flutter_tester` process remains.

So my feeling is that this is a `flutter test` issue (and neither VS Code or DAP) and something doesn't clean up correctly in this case. If that's resolved, it probably resolves for VS Code too.

**Comment by qrhfz** [comment] 2024-03-14 21:22
also happening on vs code on linux.

**Comment by jason-simmons** [comment] 2024-05-02 00:38
Reproduced this on Windows.

This is related to how Dart configures child processes on Windows.  The flutter_tester process is terminated as expected if I apply the patch in https://github.com/dart-lang/sdk/issues/49234#issuecomment-1984392929

**Comment by MelbourneDeveloper** [comment] 2024-07-24 06:46
@darshankawar I have this problem on macOS. It sometimes ends up depleting all my memory and my machine can't do anything.

**Comment by matanlurey** [comment] 2024-11-19 19:28
Raising to P1 and assigning to Jason - I believe this is a cause of moderate/major CI instability as well as bad user experiences. There is a possibility we will need the Dart team's help for a systemic fix, but I'd love to know if flutter_tester is itself doing something odd _or_ this is just Dart process management issues.

**Comment by matanlurey** [comment] 2024-11-20 19:35
I believe the particular case observed here is/was closed by https://github.com/flutter/flutter/pull/159115.

Other cases may be solved by https://github.com/flutter/flutter/pull/159170, but unrelated directly.

**Closed by matanlurey** 2024-11-20 19:35 UTC
Labels: a: tests, tool, P1, team-tool, triaged-tool
