### ISSUE TITLE
Hot restart should also get new assets in the web

### ISSUE THREAD

**Issue by phackwer** [flutter/flutter#65587] opened 2020-09-10 22:04 UTC
## Use case

When you work adding new images or translation strings from the project, you need to kill the web app and restart again to have your translation file loaded. This makes the dev process very long and tedious.

## Proposal

Instead of copying the files, make symlink to the assets/folders, that way a hot restart would be enough saving at least 30 seconds of our lives that will never come back. :'( This is so sad... :'(

**Comment by jonahwilliams** [comment] 2020-09-10 22:38
duplicate of https://github.com/flutter/flutter/issues/40861

**Closed by jonahwilliams** 2020-09-10 22:38 UTC
