### ISSUE TITLE
Flutter test t is taking an unusually long time to connect to the VM...

### ISSUE THREAD

**Issue by 1312818364** [flutter/flutter#53395] opened 2020-03-27 06:33 UTC
when I first use command flutter drive --target=test_driver/app.dart  
and then use second with --no-build params ,the console 
show that :

I/flutter (11014): Observatory listening on http://127.0.0.1:41295/fB4QJrshDFQ=/
I/flutter (11304): Observatory listening on http://127.0.0.1:40145/AcHTfffBX5M=/
I/flutter (11512): Observatory listening on http://127.0.0.1:39219/05pG_6V-ChI=/
00:00 +0: ud_student_flutter (setUpAll)

[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:60570/AcHTfffBX5M=/
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...

it seems like there has multi  Observatory listening on localhost, and has different  uri token , but the flutter driver used wrong token to connect with application , it makes the flutter driver can not connect to the VM.

**Comment by 1312818364** [comment] 2020-03-27 07:28
localhost:ud-student-flutter yangfeng$  flutter drive --target=test_driver/app.dart --no-build
Using device MI 8.
Starting application: test_driver/app.dart
Error waiting for a debug connection: Bad state: No element
Application failed to start. Will not run test. Quitting.
localhost:ud-student-flutter yangfeng$  flutter drive --target=test_driver/app.dart --no-build
Using device MI 8.
Starting application: test_driver/app.dart
I/flutter ( 5568): Observatory listening on http://127.0.0.1:41859/CXryHaz8B6I=/
00:00 +0: ud_student_flutter (setUpAll)

[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:49597/CXryHaz8B6I=/
[trace] FlutterDriver: Isolate found with number: 4460699078492399
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
I/flutter ( 5568): 初始化环境
I/flutter ( 5568): 初始化==========finish=========
[warning] FlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().
^Clocalhost:ud-student-flutter yangfeng$  flutter drive --target=test_driver/app.dart --no-build
Using device MI 8.
Starting application: test_driver/app.dart
I/flutter ( 5568): Observatory listening on http://127.0.0.1:41859/CXryHaz8B6I=/
I/flutter ( 5568): 初始化环境
I/flutter ( 5568): 初始化==========finish=========
I/flutter ( 8392): Observatory listening on http://127.0.0.1:42169/QXViHWCWP-Q=/
00:00 +0: ud_student_flutter (setUpAll)

[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:49674/CXryHaz8B6I=/
^Clocalhost:ud-student-flutter yangfeng$  flutter drive --target=test_driver/app.dart --no-build
Using device MI 8.
Starting application: test_driver/app.dart
I/flutter ( 5568): Observatory listening on http://127.0.0.1:41859/CXryHaz8B6I=/
I/flutter ( 5568): 初始化环境
I/flutter ( 5568): 初始化==========finish=========
I/flutter ( 8392): Observatory listening on http://127.0.0.1:42169/QXViHWCWP-Q=/
I/flutter ( 9306): Observatory listening on http://127.0.0.1:38029/jiMlbIBPO4o=/
00:00 +0: ud_student_flutter (setUpAll)

[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:49733/QXViHWCWP-Q=/
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...
[warning] FlutterDriver: It is taking an unusually long time to connect to the VM...

**Comment by TahaTesser** [comment] 2020-03-27 07:54
Duplicate of [#50898](https://github.com/flutter/flutter/issues/50898)

**Closed by TahaTesser** 2020-03-27 07:54 UTC

**Comment by 1312818364** [comment] 2020-03-27 08:10
thanks , upgrade flutter , everything is ok
