### ISSUE TITLE
Card flickers, when user taps on any content

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49889] opened 2020-01-31 16:50 UTC
https://b.corp.google.com/issues/148504495.

cc @chinmaygarde who's been commenting on the Google issue.

**Comment by cbracken** [comment] 2020-02-03 18:59
Closing as dupe of #50011.

**Comment by chinmaygarde** [comment] 2020-02-03 19:18
@cbracken I don't believe this is related to https://github.com/flutter/flutter/issues/50011. These platforms use entirely different subsystems and the fencing+retained surfaces hypothesis that is a plausible explanation for that issue cannot be relevant here as that technique is Fuchsia specific.

**Comment by chinmaygarde** [comment] 2020-02-17 23:25
Update: This cannot be reproduced in the test harness. I am going to verify that custom compositor integration is not susceptible to the order in which the external view embedder returns canvases for embedder managed render targets.

Currently my primary focus.

**Comment by chinmaygarde** [comment] 2020-02-23 00:36
Closing as this cannot be reproduced. Will open again if a reproducible reduced test case is provided.

**Closed by chinmaygarde** 2020-02-23 00:36 UTC
Labels: customer: dream (g3), engine, severe: customer blocker
