### ISSUE TITLE
android new project, request permission, return to the desktop, and then go back to the black screen

### ISSUE THREAD

**Issue by alienzh** [flutter/flutter#58002] opened 2020-05-26 12:06 UTC
> 新建项目, 请求权限, 退回桌面,打开其他应用,  再进入flutter 项目页面黑屏了

Create a new project, request permission, return to the desktop, open another application, and then enter the flutter project page black screen

```console
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)
```

**Comment by alienzh** [comment] 2020-05-27 01:30
https://github.com/alienzh/flutter_app/blob/master/SVID_20200527_091146_1.mp4
here is the blackscreen.mp4

**Comment by iapicca** [comment] 2020-05-29 08:44
Hi @alienzh 
Can you please provide your `flutter run --verbose`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by alienzh** [comment] 2020-06-01 07:21
hi, @iapicca 
I upgraded flutter to 1.17.2. but still black screen.

name: flutterapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  permission_handler: 4.2.0+hotfix.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


here is demo 
https://github.com/alienzh/flutter_app

**Comment by TahaTesser** [comment] 2020-06-02 08:17
Hi @alienzh 
This issue isn't reproducible with just Flutter code

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Baseflow/flutter-permission-handler/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you"

**Closed by TahaTesser** 2020-06-02 08:17 UTC
Labels: in triage

**Comment by sidvenu** [comment] 2020-11-09 02:25
@TahaTesser this is not a problem with the plugin, but rather Flutter itself. @pinpong reported this issue at https://github.com/Baseflow/flutter-permission-handler/issues/363 saying that they have the same issue when they try to use In-App billing dialog from Google.

I have the same issue when I try to integrate a native plugin that has a Bottom Sheet Dialog. When the dialog is open, if I switch apps and come back to this immediately, the activity hosting the dialog seems to go 'black'.

**Comment by TahaTesser** [comment] 2020-11-09 12:07
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by gerominoapps** [comment] 2021-01-04 19:07
It is easy to reproduce:

1. Request Location permission.
2. While the location dialog is showing move the app to the background. 
3. Bring the app back to the foreground. 
4. A black screen is showing instead of the screen content. 
5. Accepting/Denying the permission - the black screen disappears and the screen is visible as expected. 

![WhatsApp Image 2021-01-04 at 20 59 39](https://user-images.githubusercontent.com/25132272/103569613-46a03280-4ed0-11eb-9199-911d0c0b2421.jpeg)



Flutter Docor 
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-IL)
    • Flutter version 1.22.5 at /Users/galgeromino/Programs/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/galgeromino/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • SM G980F (mobile) • RF8N31E3H3D • android-arm64 • Android 10 (API 29)
