### ISSUE TITLE
low frame rate in 120hz mode

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#64433] opened 2020-08-24 03:12 UTC
1. same performance comparing with android native in 60hz mode.
2. low frame rate in 120hz on flutter.

tested on oneplus 8pro.

**Comment by sidrao2006** [comment] 2020-08-24 14:37
Can you please provide the output of `flutter doctor -v` and attach the reports from dart devtools.
Thanks

**Comment by liyuqian** [comment] 2020-08-24 21:46
Could this be https://github.com/flutter/flutter/issues/35162 ?

**Comment by pedromassangocode** [comment] 2020-08-25 12:07
Hi @hamberluo 
Also please provide your `flutter doctor -v`
Thank you

**Comment by hamberluo** [comment] 2020-09-06 03:19
@pedromassangocode 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-CN)
    • Flutter version 1.20.2 at /Users/hamberluo/Documents/Dev/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hamberluo/Documents/Dev/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/hamberluo/Documents/Dev/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.


[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • IN2020 (mobile) • 192.168.0.116:5555 • android-arm64 • Android 10 (API 29)
```

**Comment by hamberluo** [comment] 2020-09-14 02:36
Hi, pedromassangocode,
any update?

**Comment by pedromassangocode** [comment] 2020-09-14 07:38
> Could this be #35162 ?
> 
> @hamberluo : specifically, can you please try the plugin in [#35162 (comment)](https://github.com/flutter/flutter/issues/35162#issuecomment-609000841) to see if it can fix your problem?

@hamberluo have you tried this?

**Comment by hamberluo** [comment] 2020-09-23 14:21
> > Could this be #35162 ?
> > @hamberluo : specifically, can you please try the plugin in [#35162 (comment)](https://github.com/flutter/flutter/issues/35162#issuecomment-609000841) to see if it can fix your problem?
> 
> @hamberluo have you tried this?

@pedromassangocode this works!

**Comment by hamberluo** [comment] 2020-09-24 03:24
only works in debug mode
not works in profile and release mode

**Comment by hamberluo** [comment] 2020-09-24 04:40
@pedromassangocode 
Finally I found why it works in Debug Mode.
Debug Mode get refresh rate at 60Hz, I set to 120Hz.
Profile and Release Mode get refresh rate at 120Hz, but its behavior like 60Hz, I need to set to 60Hz first and then set to 120Hz.

**Comment by liyuqian** [comment] 2020-09-24 20:27
The problem in profile and release mode might be an issue for https://github.com/ajinasokan/flutter_displaymode. Would you like to file an issue there and contact its author @ajinasokan ?

**Comment by ajinasokan** [comment] 2020-09-25 02:17
@hamberluo Could you try the example app in flutter_displaymode repo? It has manual controls. If it didn't work then please file an issue. Will check it out.

**Comment by hamberluo** [comment] 2020-09-25 06:40
@ajinasokan sorry I made a mistake.
When device refresh rate is 120Hz,
Debug mode has 60Hz refresh rate in app.
Profile and Release mode has 120Hz refresh rate in app, but it behaves like 60Hz.

No matter what refresh rate in app, `flutter_displaymode` should always be use to reset 120Hz.

**Comment by ajinasokan** [comment] 2020-09-25 06:45
@hamberluo Yes. If you choose 120Hz in settings that is just a preference, it doesn't force apps to run in 120Hz. So Flutter app runs in 60Hz. And then you use `flutter_displaymode` to find the appropriate mode iterating through the mode list and set it once at the app launch.

**Comment by chinmaygarde** [comment] 2020-10-12 18:07
@liyuqian It looks like this is a case of the plugin not reporting the desired frame rate to the engine? If that's the case, we can close this issue in the engine in favor of opening one in the plugin repository? OTOH, if this is a case of the engine not respecting preferences, we need to take a closer look. Can you clarify please?

**Comment by liyuqian** [comment] 2020-10-12 18:41
The plugin lets developer to choose the refresh rate in Dart, and the plugin will talk with the native Android API to change it. The Android should be the one to tell the engine the final refresh rate. I agree that we can close this issue as the problem is most likely to be among the app Dart code, the plugin, and the Android API. There's no sign of an engine issue here.

**Closed by liyuqian** 2020-10-12 18:41 UTC
Labels: P4, engine, passed first triage, perf: speed, platform-android, severe: performance
