### ISSUE TITLE
Can't install flutter 

### ISSUE THREAD

**Issue by Juliojules** [flutter/flutter#90730] opened 2021-09-25 22:38 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by Josiassejod1** [comment] 2021-09-26 02:11
Can you provide more details in your pr? Seems like it is missing some information

**Comment by danagbemava-nc** [comment] 2021-09-27 11:03
Hi @Juliojules, when filing an issue, it is important that you provide as much information as possible so that the issue is actionable. 

Your title alone doesn't provide us with any information to act on. 

As such I'm going to close this issue. 

If you are still experiencing the issue, kindly file a new issue and provide at the minimum, the following information: 

1. What platform are you trying to install flutter on?
2. What error are you getting? 

Thank you

**Closed by danagbemava-nc** 2021-09-27 11:03 UTC
Labels: in triage

**Comment by Juliojules** [comment] 2021-09-27 12:09
Okay thank you was a mistake sorry
