### ISSUE TITLE
when first call RenderBox->performLayout  constraints is BoxConstraints(w=0.0, h=0.0) in profile mode but not as debug mode

### ISSUE THREAD

**Issue by ganluo960214** [flutter/flutter#139805] opened 2023-12-08 15:34 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter run --profile 
flutter run

### Expected results

same as debug mode(BoxConstraints(w=X, h=X) )

### Actual results

same as debug mode(BoxConstraints(w=X, h=X) )

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: SafeArea(
        child: MCRO(),
      ),
    );
  }



}

class MCRO extends MultiChildRenderObjectWidget{
  const MCRO({
    super.key,
  });

  @override
  RenderObject createRenderObject(BuildContext context) => RenderMCRO();

}

class RenderMCROParentData extends ContainerBoxParentData<RenderBox> with ContainerParentDataMixin<RenderBox> {}

class RenderMCRO extends RenderBox with
    ContainerRenderObjectMixin<RenderBox, RenderMCROParentData>{
  RenderMCRO();

  @override
  void performLayout() {
    print(constraints);
    size = constraints.biggest;
  }

  @override
  void paint(PaintingContext context, Offset offset) {
  }



  @override
  void setupParentData(covariant RenderObject child) {
    child.parentData = RenderMCROParentData();
  }

}


```

</details>

https://dartpad.dev/?id=98a4de95dc949aae698f1f9ddb08f97b

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
PS E:\source\flutter\demo> flutter run --profile
Connected devices:
SM G9350 (mobile)                     • efab64e2      • android-arm64 • Android 8.0.0 (API 26)
Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64   • Android 10 (API 29) (emulator)  
[1]: SM G9350 (efab64e2)
[2]: Android SDK built for x86 64 (emulator-5554)
Please choose one (or "q" to quit): 1
Launching lib\main.dart on SM G9350 in profile mode...
Running Gradle task 'assembleProfile'...                           29.1s
√  Built build\app\outputs\flutter-apk\app-profile.apk (12.9MB).
Installing build\app\outputs\flutter-apk\app-profile.apk...         5.7s
I/flutter (27907): BoxConstraints(w=0.0, h=0.0)                 <------------------
I/flutter (27907): BoxConstraints(0.0<=w<=360.0, 0.0<=h<=616.0) <-------------------

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
A Dart VM Service on SM G9350 is available at: http://127.0.0.1:58665/ptizW3XNsLY=/
The Flutter DevTools debugger and profiler on SM G9350 is available at:
http://127.0.0.1:9104?uri=http://127.0.0.1:58665/ptizW3XNsLY=/
I/zygote64(27907): Debugger is no longer active
V/InputMethodManager(27907): Starting input: tba=android.view.inputmethod.EditorInfo@a97fe5d nm : com.example.demo ic=null
I/InputMethodManager(27907): startInputInner - mService.startInputOrWindowGainedFocus
D/SurfaceView(27907): BG show() Surface(name=Background for - SurfaceView - com.example.demo/com.example
.demo.MainActivity@e0cd50f@0) io.flutter.embedding.android.FlutterSurfaceView{e0cd50f V.E...... ........ 0,0-720,1280}
D/SurfaceView(27907): surfaceDestroyed 1 io.flutter.embedding.android.FlutterSurfaceView{e0cd50f V.E...... ........ 0,0-720,1280}
D/SurfaceView(27907): BG hide() Surface(name=Background for - SurfaceView - com.example.demo/com.example
.demo.MainActivity@e0cd50f@0) true false io.flutter.embedding.android.FlutterSurfaceView{e0cd50f G.E...... ......I. 0,0-720,1280}
D/OpenGLRenderer(27907): eglDestroySurface = 0x7cecddba10
D/ViewRootImpl@716128[MainActivity](27907): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x5 surface={valid=false 0} changed=true
D/ViewRootImpl@716128[MainActivity](27907): MSG_WINDOW_FOCUS_CHANGED 0

Application finished.

--------------------------------------------------------------------------

PS E:\source\flutter\demo> flutter run          
Connected devices:
SM G9350 (mobile)                     • efab64e2      • android-arm64 • Android 8.0.0 (API 26)
Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64   • Android 10 (API 29) (emulator)  
[1]: SM G9350 (efab64e2)
[2]: Android SDK built for x86 64 (emulator-5554)
Please choose one (or "q" to quit): 1
Launching lib\main.dart on SM G9350 in debug mode...
Running Gradle task 'assembleDebug'...                             24.2s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app-debug.apk...          12.2s
Syncing files to device SM G9350...                                397ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on SM G9350 is available at: http://127.0.0.1:60383/F4fMwSXrjKs=/
I/flutter (29315): BoxConstraints(0.0<=w<=360.0, 0.0<=h<=616.0)   <------------------------------------
The Flutter DevTools debugger and profiler on SM G9350 is available at:
http://127.0.0.1:9104?uri=http://127.0.0.1:60383/F4fMwSXrjKs=/
D/libGLESv2(29315): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.demo
I/vndksupport(29315): sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8996.so from the current namespace instead.
I/zygote64(29315): Debugger is no longer active

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22631.2715], locale en-US)
    • Flutter version 3.16.3 on channel stable at E:\source\runtime\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (3 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at E:\source\runtime\Android\Sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = E:\source\runtime\Android\Sdk
    • Java binary at: E:\application\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.1)
    • Visual Studio at E:\application\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34316.72
    • Windows 10 SDK version 10.0.22621.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the  
      "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.3)
    • Android Studio at E:\application\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at E:\application\ideaIU
    • Flutter plugin version 76.3.4
    • Dart plugin version 233.11799.172

[√] Proxy Configuration
    • NO_PROXY contains localhost
    • NO_PROXY contains ::1
    • NO_PROXY contains 127.0.0.1

[√] Connected device (5 available)
    • SM G9350 (mobile)                     • efab64e2      • android-arm64  • Android 8.0.0 (API 26)   
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29)      
      (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows        
      [Version 10.0.22631.2715]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome
      120.0.6099.71
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge
      120.0.2210.61

[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by huycozy** [comment] 2023-12-11 06:03
Thanks for filing a separate issue. I checked this issue and see it seems to only happen on Android platform. On other platforms (macOS, iOS, Windows), it outputs the same BoxConstraints in both debug and profile modes.

### Android

- Debug mode:
```console
I/flutter ( 3100): BoxConstraints(0.0<=w<=360.0, 0.0<=h<=717.7)
```

- Profile mode:
```console
I/flutter ( 3100): BoxConstraints(w=0.0, h=0.0)
I/flutter ( 3100): BoxConstraints(0.0<=w<=360.0, 0.0<=h<=717.7)
```

### macOS/Windows/iOS

- Debug/Profile mode:

```console
flutter: BoxConstraints(0.0<=w<=800.0, 0.0<=h<=600.0) // macOS

flutter: BoxConstraints(0.0<=w<=1264.0, 0.0<=h<=681.0) // windows

flutter: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=647.0) // iOS
```

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.16.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (23 hours ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe Patch 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.18.0-7.0.pre.58, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.18.0-7.0.pre.58 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c0a481e31d (4 hours ago), 2023-12-10 17:46:24 -0500
    • Engine revision bc0222b64c
    • Dart version 3.3.0 (build 3.3.0-214.0.dev)
    • DevTools version 2.30.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio Giraffe Patch 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 120.0.6099.71

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by huycozy** [comment] 2023-12-11 07:49
Hi @ganluo960214, I see there was a similar issue at https://github.com/flutter/flutter/issues/106858. Please check https://github.com/flutter/flutter/issues/106858#issuecomment-1517733501 and https://github.com/flutter/flutter/issues/106858#issuecomment-1734188331 for more information. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/106858.

**Closed by huycozy** 2023-12-11 07:49 UTC
Labels: platform-android, framework, has reproducible steps, team-android, found in release: 3.16, found in release: 3.18
