### ISSUE TITLE
[camera][ios] Landscape orientation seems to be inverted on iOS

### ISSUE THREAD

**Issue by letsar** [flutter/flutter#117981] opened 2023-01-04 16:00 UTC
## Steps to Reproduce

1. Execute `flutter run` on and iOS device, on the code sample available on this repo: https://github.com/letsar/flutter_camera_ios_orientation_issue
2. Rotate the device to the left so that it will display `DeviceOrientation.landscapeLeft` at the top-right of the screen
3. Take a photo with the FAB

**Expected results:**
The picture should be in the right orientation

**Actual results:** 
The picture is upside down

![IMG_0013](https://user-images.githubusercontent.com/9378033/210594670-da313871-215b-4f68-bf64-0de894a6ccd9.PNG)

<details>
<summary>Code sample</summary>

The code is available on a [dedicated](https://github.com/letsar/flutter_camera_ios_orientation_issue) repo because it's easier to reproduce this way.

</details>

<details>
  <summary>Logs</summary>

```
[  +73 ms] ------ Debug phase ------
[        ] Starting debug of 00008030-000139323E86402E (D79AP, iPhone SE 2G, iphoneos, arm64e, 15.6.1, 19G82) a.k.a. 'iPhone' connected through USB...
[+1291 ms] [  0%] Looking up developer disk image
[  +13 ms] [ 95%] Developer disk image mounted successfully
[  +76 ms] Symbol Path: /Users/user/Library/Developer/Xcode/iOS DeviceSupport/15.6.1 (19G82) arm64e/Symbols
[ +345 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +211 ms] (lldb) command source -s 0 '/tmp/A3B7F0DE-1719-44BA-A0CB-6E838EF6BB20/fruitstrap-lldb-prep-cmds-00008030_000139323E86402E'
[        ] Executing commands in '/tmp/A3B7F0DE-1719-44BA-A0CB-6E838EF6BB20/fruitstrap-lldb-prep-cmds-00008030_000139323E86402E'.
[        ] (lldb)     platform select remote-'ios' --sysroot '/Users/user/Library/Developer/Xcode/iOS DeviceSupport/15.6.1 (19G82) arm64e/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/user/Library/Developer/Xcode/iOS DeviceSupport/15.6.1 (19G82) arm64e/Symbols"
[        ] (lldb)     target create "/Users/user/projets/perso/flutter_camera_ios_orientation_issue/build/ios/iphoneos/Runner.app"
[+2897 ms] Current executable set to '/Users/user/projets/perso/flutter_camera_ios_orientation_issue/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/C6E8D036-1CE4-417E-AE3D-068B00F69A56/Runner.app"
[ +130 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:60765"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/user/Library/Developer/Xcode/iOS DeviceSupport/15.6.1 (19G82) arm64e/Symbols/usr" /System "/Users/user/Library/Developer/Xcode/iOS DeviceSupport/15.6.1 (19G82) arm64e/Symbols/System" "/private/var/containers/Bundle/Application/C6E8D036-1CE4-417E-AE3D-068B00F69A56" "/Users/user/projets/perso/flutter_camera_ios_orientation_issue/build/ios/iphoneos" "/var/containers/Bundle/Application/C6E8D036-1CE4-417E-AE3D-068B00F69A56" "/Users/user/projets/perso/flutter_camera_ios_orientation_issue/build/ios/iphoneos" /Developer "/Users/user/Library/Developer/Xcode/iOS DeviceSupport/15.6.1 (19G82) arm64e/Symbols/Developer"
[   +8 ms] (lldb)     command script import "/tmp/A3B7F0DE-1719-44BA-A0CB-6E838EF6BB20/fruitstrap_00008030_000139323E86402E.py"
[   +3 ms] (lldb)     command script add -f fruitstrap_00008030_000139323E86402E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008030_000139323E86402E.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008030_000139323E86402E.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008030_000139323E86402E.safequit_command safequit
[        ] (lldb)     connect
[  +37 ms] (lldb)     run
[ +174 ms] success
[        ] Application launched on the device. Waiting for observatory url.
[+1596 ms] Observatory URL on device: http://127.0.0.1:59819/
[   +1 ms] Attempting to forward device port 59819 to host port 60773
[        ] executing: /Users/user/dev/flutter/bin/cache/artifacts/usbmuxd/iproxy 60773:59819 --udid 00008030-000139323E86402E --debug
[ +453 ms] The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
[ +553 ms] Forwarded port ForwardedPort HOST:60773 to DEVICE:59819
[        ] Forwarded host port 60773 to device port 59819 for Observatory
[   +1 ms] Installing and launching... (completed in 9,8s)
[        ] Caching compiled dill
[  +29 ms] Connecting to service protocol: http://127.0.0.1:60773/
[ +110 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:60773/.
[  +50 ms] DDS is listening at http://127.0.0.1:60776/d8CORtEsXI8=/.
[  +26 ms] Successfully connected to service protocol: http://127.0.0.1:60773/
[  +16 ms] DevFS: Creating new filesystem on the device (null)
[  +12 ms] DevFS: Created new filesystem on the device (file:///private/var/mobile/Containers/Data/Application/5577B2F5-0636-4410-9551-DA14A54FC104/tmp/flutter_camera_ios_orientation_issueyUttMU/flutter_camera_ios_orientation_issue/)
[   +1 ms] Updating assets
[  +52 ms] Syncing files to device iPhone...
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:flutter_camera_ios_orientation_issue/main.dart c5a01c89-37ca-42c2-a90c-6a22bae1d0f4
[        ] <- c5a01c89-37ca-42c2-a90c-6a22bae1d0f4
[        ] Bundle processing done.
[  +27 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device iPhone... (completed in 30ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] Connected to _flutterView/0x10381dc20.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on iPhone is available at: http://127.0.0.1:60776/d8CORtEsXI8=/
[  +11 ms] The Flutter DevTools debugger and profiler on iPhone is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:60776/d8CORtEsXI8=/
[+11969 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/5577B2F5-0636-4410-9551-DA14A54FC104/tmp/flutter_camera_ios_orientation_issueyUttMU/flutter_camera_ios_orientation_issue/)
[  +12 ms] DevFS: Deleted filesystem on the device (file:///private/var/mobile/Containers/Data/Application/5577B2F5-0636-4410-9551-DA14A54FC104/tmp/flutter_camera_ios_orientation_issueyUttMU/flutter_camera_ios_orientation_issue/)
[   +3 ms] Application finished.
[   +3 ms] "flutter run" took 72 171ms.
[   +3 ms] ios-deploy exited with code 0
[   +9 ms] Service protocol connection closed.
[  +36 ms] ensureAnalyticsSent: 47ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

```
Analyzing flutter_camera_ios_orientation_issue...                       
No issues found! (ran in 1.4s)
```

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.5.1 21G83 darwin-arm, locale fr-FR)
    • Flutter version 3.3.7 on channel stable at /Users/user/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (il y a 9 semaines), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode-14.0.0.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • IN2023 (mobile) • 87950fce                  • android-arm64  • Android 13 (API 33)
    • iPhone (mobile) • 00008030-000139323E86402E • ios            • iOS 15.6.1 19G82
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by darshankawar** [comment] 2023-01-05 07:24
Thanks for the report @letsar 
From the repro code you provided, I see that there are couple of third party packages implemented, `native_device_orientation` and `collection`. Would be good to check if the reported behavior occurs only using `camera` plugin without these plugins, so that we know it could be an issue in `camera` plugin or not.

With `camera` [plugin example](https://github.com/flutter/plugins/tree/main/packages/camera/camera/example), I checked using the steps you provided, and see the preview in proper orientation:

<img width="1088" alt="Screenshot 2023-01-05 at 12 53 24 PM" src="https://user-images.githubusercontent.com/67046386/210724448-832d22aa-9239-4f4b-badb-bb4d54ce0fc5.png">

**Comment by letsar** [comment] 2023-01-05 07:58
Thanks for the investigation @darshankawar. In the repro code we use an external plugin to get the orientation, because we want to be able to get the device orientation when the orientation of the app is locked. In the repro code you can see we use   `await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);` to achieve it. In the example code of the camera, it works well because the orientation is not locked.

In our app, we don't want to rotate all the screen when the device orientation change, but we want to be able to get it in order to give to the taken picture, the real orientation of the device. So that when the device is landscape-left oriented, the image will also be.
I'm not aware of a way of doing this only with the `camera` plugin.
In the camera example for example, if the auto-rotation is system locked, and we take a picture with a landscape-left oriented phone, the picture will still be portrait-up oriented because it is sync with the UI orientation.

Does this explanation help you to better understand the issue we're facing ?

**Comment by darshankawar** [comment] 2023-01-05 13:18
Thanks for the feedback. I am able to replicate the reported behavior using code sample provided.

<img width="346" alt="Screenshot 2023-01-05 at 6 47 23 PM" src="https://user-images.githubusercontent.com/67046386/210788941-35b428fe-d6b2-44c8-9933-d05fa397a60a.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.10 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (15 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-14.0.pre.40, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.7.0-14.0.pre.40 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a562fe2d8a (11 minutes ago), 2023-01-04 23:53:41 -0500
    • Engine revision b9b0193ea8
    • Dart version 3.0.0 (build 3.0.0-85.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by camsim99** [comment] 2023-01-06 18:53
@hellohuanlin The regression that PR fixes would have impacted unlocking the device orientation or other use cases trying to clear the locked orientation (pausing the preview, stopping the recording of a video). I don't see the sample provided trying to do any of those upon first glance, but if I'm missing something there it could definitely be related.

**Comment by bssughosh** [comment] 2023-03-08 10:46
Any solution found to tackle this issue?

**Comment by mnock** [comment] 2023-05-08 05:56
Any solution found to tackle this issue?

**Comment by brunosp15** [comment] 2023-07-26 19:07
Any solution found to tackle this issue?

**Comment by AlexV525** [comment] 2023-10-30 04:33
The root cause is, as @hellohuanlin already been spotted in the last year, https://github.com/flutter/plugins/pull/3390/files#diff-c4f9451d94273e889e4527592876709aa327c9256e9a4d88c53fb05b8e9048cd
![image](https://github.com/flutter/flutter/assets/15884415/99ab8fc1-d8e0-4c8e-9f1f-606ed1e9e557)
The fix would be simple, invert the strings so it can return a correct result.

**Comment by AlexV525** [comment] 2023-10-30 04:47
However, no one in the team was able to push a quick fix for this, which is a good lesson to rethink about it.

**Closed** 2023-10-31 23:16 UTC
Labels: platform-ios, p: camera, package, a: layout, has reproducible steps, P2, found in release: 3.3, found in release: 3.7, team-ios, triaged-ios, multiteam-retriage-candidate
