### ISSUE TITLE
Unexpected Container layout behavior

### ISSUE THREAD

**Issue by xster** [flutter/flutter#19289] opened 2018-07-11 23:45 UTC
```dart
Container(
  height: 300.0,
  width: 300.0,
  color: Colors.red,
  child: Container(
    height: 100.0,
    width: 100.0,
    color: Colors.blue,
  ),
),
```
unexpectedly ends up making 2 overlapping 300x300 boxes

**Comment by jarvys** [comment] 2018-08-11 05:56
You can workaround this use `Column` like this:

```dart
Column(children: [
      Container(
          height: 300.0,
          width: 300.0,
          color: Colors.red,
          child: Column(children: [
            Container(height: 100.0, width: 100.0, color: Colors.blue)
          ])
    )
]);
```

**Comment by imdragonet** [comment] 2018-08-11 14:07
https://docs.flutter.io/flutter/widgets/Container-class.html
> If the widget has no child and no alignment, but a height, width, or constraints are provided, then the Container tries to be as small as possible given the combination of those constraints and the parent's constraints.

**Comment by Hixie** [comment] 2018-08-24 21:15
`width` and `height` set the size of the child, yeah. Looks like it's working as intended to me.

**Comment by Kartik1607** [comment] 2019-01-28 04:31
The documentation of `Container` is really confusing. There is no mention that *height* and *width* are bounds for children and not Container itself.

Further, Container layout is totally non-intuitive. For example, without running and just by looking at code below what output is expected?

```dart
          Container(
              width: 300.0,
              height: 300.0,
              color: Colors.red,
              child: Container(
                color: Colors.green,
                height: 100,
                width: 100,
                child: Container(
                  height: 50,
                  width: 50,
                  color: Colors.blue,
                ),
              ),
            )
```

I expected to see 3 colors, but rather we get a *300 x 300* container of color blue. I have some questions buzzing in my mind and unable to understand what is happening and why is the behavior happening like this. Should container layout be changed (based on intuition and expectation), or perhaps documentation should be made better. ( A truth-table in documentation? )

**Comment by VinciShark** [comment] 2019-02-19 09:22
```dart
                  Container(
                      width: double.maxFinite,
                      margin: EdgeInsets.fromLTRB(0, 16, 0, 0),
                      color: Color(0x88FFFFFF),
                      height: 2,
                      child: Row(children: [
                        Container(
                            color: Color(0xFFFFE100), height: 2, width: 200),
                      ]))
```

works, but it smells……

**Comment by Hixie** [comment] 2019-02-19 17:30
The key here is that the `alignment` argument defaults to "apply the `constraints` (which can be set using `width` and `height`) to the `child`". If you set the `alignment` to a non-null value, then the `child` will be aligned within the `constraints` instead.

To put it another way, what would you want the red/green/blue example above to actually look like? Where should the children end up, if they're a different size than the parent? You haven't set an alignment, so the Container widget doesn't know what should happen...

**Comment by Kartik1607** [comment] 2019-02-20 04:32
> The key here is that the `alignment` argument defaults to "apply the `constraints` (which can be set using `width` and `height`) to the `child`". If you set the `alignment` to a non-null value, then the `child` will be aligned within the `constraints` instead.
> 
> To put it another way, what would you want the red/green/blue example above to actually look like? Where should the children end up, if they're a different size than the parent? You haven't set an alignment, so the Container widget doesn't know what should happen...

Ah hah. `Alignment` does make sense totally. I believe this point and a sample should end up in documentation. Maybe two samples with and without an `Align` widget could be added to docs to help clarify issue for first time explorers.

**Comment by Hixie** [comment] 2019-02-21 22:21
Might make sense to have a Troubleshooting question in the API docs that says something similar to my comment above, much like we do for Row and Column.

**Comment by Nipodemos** [comment] 2019-05-10 01:14
I just wanna say thank you for clarification :smile: 
with your explanation, the code will be like:
```dart
Container(
  width: 300.0,
  height: 300.0,
  alignment: Alignment.center,
  color: Colors.red,
  child: Container(
    color: Colors.green,
    alignment: Alignment.center,
    height: 100,
    width: 100,
    child: Container(
      height: 50,
      width: 50,
      color: Colors.blue,
    ),
  ),
);
```
![image](https://user-images.githubusercontent.com/11494727/57496136-cd3de000-72a7-11e9-895c-e596d7555817.png)

and works as expected

**Comment by pedromassangocode** [comment] 2020-07-24 06:14
I couldn't find the explanation or example related to this issue in the current Container documentation.

https://api.flutter.dev/flutter/widgets/Container-class.html

**Comment by pedromassangocode** [comment] 2021-01-19 14:02
Hi @xster 
Does those comments in the docs clarifies the expected behavior? I think it explains what @Hixie  said in https://github.com/flutter/flutter/issues/19289#issuecomment-465231292.

![Screen Shot 2021-01-19 at 14 57 58](https://user-images.githubusercontent.com/67424416/105044300-ddd7bf00-5a66-11eb-8cf4-486a2f5d64bf.png)

**Comment by pedromassangocode** [comment] 2021-02-12 10:27
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-12 10:27 UTC
Labels: P4, d: api docs, documentation, found in release: 1.17, framework, has reproducible steps, waiting for customer response
