### ISSUE TITLE
RTL indicator back to start after clicking space

### ISSUE THREAD

**Issue by FlutterIODev** [flutter/flutter#22627] opened 2018-10-03 19:12 UTC
Hello

When enabling force RTL in flutter gallery app I have founded two issue

When clicking space the indicator back to the start
When long pressing on the text input field I got a bad state error ( I think this error related to the first one).

Please see my explanation video.

https://drive.google.com/file/d/16wujF0f5KcqT71mybRbsDafWks86T_f1/view?usp=drivesdk

**Comment by GaryQian** [comment] 2018-10-03 19:45
cc @jason-simmons I believe you have worked with the bidi code? Thoughts?

**Comment by GaryQian** [comment] 2018-10-04 19:50
I believe this is symptomatic of a larger issue of how we handle RTL languages.
Consider the following tests for bounding rects:
![paragraphtest_getrectsforrangeparagraph_1](https://user-images.githubusercontent.com/1887398/46499113-05da8000-c7d4-11e8-9d28-3867356da9b0.png)
RTL version:
![paragraphtest_getrectsforrangertlparagraph_1](https://user-images.githubusercontent.com/1887398/46499118-0b37ca80-c7d4-11e8-914e-4b8c905ca3fd.png)
I'll file a more broad bug for RTL handling.

**Comment by FlutterIODev** [comment] 2018-10-04 21:42
Thanks Gary,
Do you have any suggestions to work around this issue before it's been fixed in Flutter, our app is in production stage and it will target mainly Arabs users ( RTL ) .

**Comment by aameen951** [comment] 2018-10-18 15:03
The issue #17087 is actually the same problem. This is another way of producing the same problem.

The problem is in this line:
https://github.com/flutter/flutter/blob/7ce28d1277056e2471b323e3f1ff45a8d43731ca/packages/flutter/lib/src/rendering/editable.dart#L931

Explanation: After a long press (in a way that causes a selection to a white space), The property `selection.isCollapsed` is returning `true` (because `selection.start != selection.end`). However, the `getBoxesForSelection` is not returning any boxes (I'm assuming because it is white space) and the two lines following the one referenced above are trying to access the first and last boxes which is an error.

Possible solutions:
1. Changing `getBoxesForSelection` to return the box containing the white space.
2. Changing `selection.isCollapsed` to take into consideration the cases that will make `getBoxesForSelection` not return any box.

I hope this will help solving this issue faster.

Thank you

**Comment by GaryQian** [comment] 2020-04-30 10:20
We have since landed multiple changes that improve handling of RTL carets. Please verify if this fixed.

**Comment by FlutterIODev** [comment] 2020-04-30 18:19
The two problems described above has been solved but I think solving them cause other problem.

Now when you write Arabic words and try to delete them, everything works fine, but if you tried to write English words then try to delete them flutter will be stuck after deleting one word and will never respond to the delete button from the keyboard.

The problem appears on a physical device as well as on the Android emulator.

The following [video](https://drive.google.com/open?id=1HBtWoRbv90puAelCSiK1TgtssZrs24GN) describes the problem.

# Flutter Version
```
[√] Flutter: is fully installed. (Channel master, v1.18.0-9.0.pre.14, on Microsoft Windows [Version 10.0.17763.805],
    locale en-US)
[√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.1)
[√] Chrome - develop for the web: is fully installed.
[√] Android Studio: is fully installed. (version 3.5)
[√] IntelliJ IDEA Community Edition: is fully installed. (version 2019.1)
[√] VS Code: is fully installed. (version 1.44.2)
[√] Connected device: is fully installed. (3 available)
```

# Sample Code
```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [Locale("ar")],
      locale: Locale("ar"),
      home: Scaffold(
        appBar: AppBar(),
        body: Padding(
          padding: EdgeInsets.all(8),
          child: TextField(),
        ),
      ),
    );
  }
}
```

**Comment by GaryQian** [comment] 2020-05-01 21:35
I believe this PR: https://github.com/flutter/engine/pull/17960 is being worked on to handle deleting better, although I thought @alimahdiyar 's previous patch resolved deleting arabic/english mixes.

**Comment by GaryQian** [comment] 2020-05-01 22:00
@FlutterIODev Yeah, I was able to repro that bug. Let me file another issue on it and track it separately. We should close this one as the original reported bug is fixed.

**Closed by GaryQian** 2020-05-01 22:00 UTC
Labels: a: internationalization, a: text input, a: typography, engine, framework

**Comment by GaryQian** [comment] 2020-05-01 22:05
Let's continue work to resolve the new issue here: https://github.com/flutter/flutter/issues/56149
