### ISSUE TITLE
Flutter Animation on Android: D/skia    (22985): Could not invert viewmatrix

### ISSUE THREAD

**Issue by jvanderen1** [flutter/flutter#16615] opened 2018-04-16 04:45 UTC
## Steps to Reproduce

Without going too deep in the code, I have an animation triggered every time the time changes, where:

```dart
@override
  Widget build(BuildContext context) {

    if (this._currentTime != widget.amountOfTime) {
      this._changeTimeAnimation();
    }

    return new AnimatedBuilder(
      animation: this._animation,
      builder: (BuildContext context, Widget child) => this._flipAnimation(child),
      child: new Text(
        this._currentTime,
        textAlign: TextAlign.left,
        style: new TextStyle(fontSize: 100.0),
      ),
    );
  }
```
And *this._flipAnimation()* is the following:

```dart
Transform _flipAnimation(Widget child) {
    /// Function used to generate a flip animation for the time

    final Matrix4 transform = new Matrix4.identity()
      ..scale(1.0, this._animation.value, 1.0);

    return Transform(
      transform: transform,
      alignment: FractionalOffset.center,
      child: child,
    );
  }
```

Every time the animation is triggered, I get the message 

```
D/skia    (22985): Could not invert viewmatrix
```
Why is that?

I will note, the animation appears to be working just fine on the device, but that printout is odd.

## Logs

After `flutter run`:

```
Performing full restart...
Restarted app in 2,182ms.
D/skia    (22985): Could not invert viewmatrix
D/skia    (22985): Could not invert viewmatrix
D/skia    (22985): Could not invert viewmatrix
D/skia    (22985): Could not invert viewmatrix
D/skia    (22985): Could not invert viewmatrix
```

## Flutter Doctor

After running `flutter doctor -v`:

```
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.2.8 at /Users/jvanderen11/flutter
    • Framework revision b397406561 (13 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jvanderen11/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Developer Tools/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Developer Tools/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Users/jvanderen11/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

**Comment by jvanderen1** [comment] 2018-04-17 17:40
Yes. I don't think that having a scale factor of 0.0 should warrant `D/skia (22985): Could not invert viewmatrix`. Maybe anything < 0.0 should.

**Comment by markusaksli-nc** [comment] 2020-10-14 08:38
Either the problem was some other value during the animation or this is fixed now.

In any case closing this as not reproducible on the latest master `1.23.0-19.0.pre.19`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.23.0-19.0.pre.19, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.23.0-19.0.pre.19 at C:\Development\flutter_master
    • Framework revision 4b351ac1b4 (4 hours ago), 2020-10-13 21:29:23 -0700
    • Engine revision adf5b59485
    • Dart version 2.11.0 (build 2.11.0-217.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.4449.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 85.0.564.70

• No issues found!
```
</details>
<details>
 <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final Matrix4 transform = new Matrix4.identity()..scale(1.0, 0.0, 1.0);
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Center(
          child: Transform(
            transform: transform,
            alignment: FractionalOffset.center,
            child: Container(
              color: Colors.red,
              width: 100,
              height: 100,
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Closed by markusaksli-nc** 2020-10-14 08:38 UTC
Labels: P4, dependency: skia, engine
