### ISSUE TITLE
Link pageviews

### ISSUE THREAD

**Issue by phanirithvij** [flutter/flutter#44808] opened 2019-11-13 12:05 UTC
How to link two PageView controllers (without using a bigger pageview.)
It is possible to change the page using `jumpTo` but it doesn't work in another pageview's `addListener` callback.
The method `PageController.position.setPixels()` doesn't work either.

<details>
<summary>sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setEnabledSystemUIOverlays([]);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Experiments',
      theme: ThemeData.dark(),
      home: MyHomePage(title: 'FlutterExps'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<PageController> _controllers;
  ValueNotifier<int> _horizPage = ValueNotifier(0);
  ValueNotifier<double> _vertPage = ValueNotifier(0);

  @override
  void initState() {
    _controllers = [
      PageController(keepPage: true),
      PageController(keepPage: true),
    ];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: [
          ColPageView(
            idx: 0,
            currHoriz: _horizPage,
            vertstate: _vertPage,
            controllers: _controllers,
            children: <Widget>[
              ColoredWidget(
                color: Colors.cyan,
                direction: ">",
              ),
              ColoredWidget(
                color: Colors.orange,
                direction: ">>",
              ),
            ],
          ),
          ColPageView(
            idx: 1,
            currHoriz: _horizPage,
            vertstate: _vertPage,
            controllers: _controllers,
            children: [
              ColoredWidget(
                color: Colors.green,
                direction: "<",
              ),
              ColoredWidget(
                color: Colors.yellow,
                direction: "<<",
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class ColPageView extends StatefulWidget {
  final int idx;
  final List<Widget> children;
  final List<PageController> controllers;
  final ValueNotifier<int> currHoriz;
  final ValueNotifier<double> vertstate;

  const ColPageView({
    Key key,
    this.children = const <Widget>[],
    @required this.controllers,
    @required this.currHoriz,
    @required this.vertstate,
    @required this.idx,
  }) : super(key: key);

  @override
  _ColPageViewState createState() => _ColPageViewState();
}

class _ColPageViewState extends State<ColPageView> {
  @override
  void initState() {
    widget.controllers[widget.idx] = PageController(
      initialPage: widget.vertstate.value.floor() ?? 0,
      keepPage: true,
    )..addListener(_onPageChanged);

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    var container = Container(
      width: MediaQuery.of(context).size.width / 2,
      child: PageView(
        controller: widget.controllers[widget.idx],
        scrollDirection: Axis.vertical,
        children: widget.children,
      ),
    );
    return container;
  }

  void _onPageChanged() {
    // print("Curr horiz ${widget.currHoriz.value} ${widget.vertstate.value}");
    // print(
    //     "onPageCallback ${widget.controllers[widget.idx].page} for ${widget.idx}");
    // if (widget.currHoriz.value == null) {
    //   widget.currHoriz.value = widget.idx;
    // }
    if (widget.idx == widget.currHoriz.value) {
      widget.controllers.forEach((colpv) {
        if (colpv != widget.controllers[widget.idx]) {
          // print("has clients and ${colpv.hasClients}");
          if (colpv.hasClients) {
            // print(colpv);
            colpv.position.setPixels(widget.controllers[widget.idx].page);
            // colpv.jumpTo(
            //   widget.controllers[widget.idx].page,
            //   // curve: Curves.easeIn,
            //   // duration: Duration(milliseconds: 300),
            // );
            // setState(() {});
          }
        }
      });
      // set horizontal coord to be this
      // widget.currHoriz.value = null;
      // Set latest vertical position
      widget.vertstate.value = widget.controllers[widget.idx].page;

      // print("col-${widget.idx} changed to $pno");
    } else {
      // print("other widget");
      // print("${widget.controllers[widget.idx].page}");
      return null;
    }
  }
}

class ColoredWidget extends StatefulWidget {
  final Color color;
  final String direction;

  const ColoredWidget({
    Key key,
    @required this.color,
    @required this.direction,
  }) : super(key: key);

  @override
  _ColoredWidgetState createState() => _ColoredWidgetState();
}

class _ColoredWidgetState extends State<ColoredWidget> {
  @override
  Widget build(BuildContext context) {
    return Container(
        color: widget.color,
        child: Center(
          child: Text(
            widget.direction,
            style: TextStyle(
              fontSize: 100,
              color: Colors.black,
            ),
          ),
        ));
  }
}
```

</details>

I think this isn't entirely a support question as `jumpTo` as I said doesn't work when called with a fractional value.

**Comment by phanirithvij** [comment] 2019-11-13 12:07
I think this isn't entirely a support question as `jumpTo` as I said doesn't work when called with a fractional value.

**Comment by iapicca** [comment] 2019-11-14 10:42
Hi @phanirithvij 
could you please provide your updated  `flutter doctor -v`?
thank you

**Comment by phanirithvij** [comment] 2019-11-14 14:43
I don't see how this is relevant.

```shell
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18363.476], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at D:\Software\flutter\flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Software\AndroidSDK\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Software\AndroidSDK\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\Rithvij\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available
```

**Comment by markusaksli-nc** [comment] 2020-09-23 09:00
`setPixels` isn't really meant to be used like this, as documented:

> This should only be called by the current ScrollActivity, either during the transient callback phase or in response to user input.

The controller has the [animateTo](https://master-api.flutter.dev/flutter/widgets/ScrollController/animateTo.html) and [animateToPage](https://master-api.flutter.dev/flutter/widgets/PageController/animateToPage.html) methods for this. Your sample can be made to work with the simple one-line solution:
```dart
  void _onPageChanged() {
    if (widget.currHoriz.value == null) {
      widget.currHoriz.value = widget.idx;
    }
    if (widget.idx == widget.currHoriz.value) {
      widget.controllers.forEach((colpv) {
        if (colpv != widget.controllers[widget.idx]) {
          if (colpv.hasClients) {
            //This
            colpv.animateTo(widget.controllers[widget.idx].position.pixels,
                duration: Duration(milliseconds: 100), curve: Curves.ease);
          }
        }
      });
      widget.vertstate.value = widget.controllers[widget.idx].page;
    } else {
      return null;
    }
  }
```
Closing since this is documented and working as intended.

**Closed by markusaksli-nc** 2020-09-23 09:00 UTC
Labels: d: stackoverflow, f: scrolling, framework
