### ISSUE TITLE
Load local assets like HTML and linked files in a Flutter app using WebView

### ISSUE THREAD

**Issue by MaruQuarky** [flutter/flutter#66932] opened 2020-09-29 19:33 UTC
I've tried loading my local HTML and other files linked to it using Flutter WebView.

Here is my sample code:

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'dart:async';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<String> localLoader() async {
    return await rootBundle.loadString('assets/sample.html');
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<String>(
        future: localLoader(),
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return WebView(
              initialUrl:
                  new Uri.dataFromString(snapshot.data, mimeType: 'text/html')
                      .toString(),
              javascriptMode: JavascriptMode.unrestricted,
            );
          } else if (snapshot.hasError) {
            return Text("${snapshot.error}");
          }
          return CircularProgressIndicator();
        });
  }
}
```
I'm using the Flutter plugin [webview_flutter](https://pub.dev/packages/webview_flutter) and this is the output look like:

**Actual output:**
Only the HTML file was loaded.

![Screenshot_1601328465](https://user-images.githubusercontent.com/42828461/94602629-b3030880-02c7-11eb-887d-5a41e7754f3d.png)

**Expected output:**
HTML, CSS and the image was loaded.

![Screenshot_1601330190](https://user-images.githubusercontent.com/42828461/94602765-e3e33d80-02c7-11eb-9a0e-cec1d9f9f143.png)

What I've tried so far to meet the expected output was to use a different plugin which is [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview). Here is how my code look like:

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'dart:async';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<String> localLoader() async {
    return await rootBundle.loadString('assets/sample.html');
  }

  InAppWebViewController _webViewController;
  String url = "";
  double progress = 0;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<String>(
        future: localLoader(),
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return SafeArea(
              child: Container(
                margin: const EdgeInsets.all(10.0),
                decoration:
                    BoxDecoration(border: Border.all(color: Colors.blueAccent)),
                child: InAppWebView(
                  initialFile: "assets/sample.html",
                  initialHeaders: {},
                  initialOptions: InAppWebViewGroupOptions(
                      crossPlatform: InAppWebViewOptions(
                    debuggingEnabled: true,
                  )),
                  onWebViewCreated: (InAppWebViewController controller) {
                    _webViewController = controller;
                  },
                  onLoadStart: (InAppWebViewController controller, String url) {
                    setState(() {
                      this.url = url;
                    });
                  },
                  onLoadStop:
                      (InAppWebViewController controller, String url) async {
                    setState(() {
                      this.url = url;
                    });
                  },
                  onProgressChanged:
                      (InAppWebViewController controller, int progress) {
                    setState(() {
                      this.progress = progress / 100;
                    });
                  },
                ),
              ),
            );
          } else if (snapshot.hasError) {
            return Text("${snapshot.error}");
          }
          return CircularProgressIndicator();
        });
  }
}
```
For reference, here are my HTML and CSS files:

_sample.html_
Note: flutter_logo.png could be any image available.
```
 <!DOCTYPE html>
    <meta charset="utf-8">
    <title>Sample HTML</title>
    <html>
        <head>
            <link rel="stylesheet" href="sample.css">
        </head>
        <body>
            <h1>Flutter Webview</h1>
            <p>This paragraph have styles.</p>
        </body>
        <img src="flutter_logo.png" alt="">
    </html>
```

_sample.css_
```
body{
        background-color: aliceblue;
    }
    h1{
        text-align: center;
        font-style: bold;
        color: blue;
    }
    p{
        text-align: center;
        font-style: italic;
        color: cornflowerblue
    }
    img{
        display: block;
        margin-left: auto;
        margin-right: auto;
        height: 15%;
        width: 15%;
    }
```
I am not sure if Flutter WebView is supporting something like [Android's WebView](https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader) functionality.

**Comment by blasten** [comment] 2020-09-29 21:49
The Android's WebView API surface is pretty large.  It's unlikely that we would ever expose it all in a way that covers the same use cases as the underlaying Android API. However, I wonder if for long tail cases like this, we should provide a platform hook that allows the app or another plugin to configure the native WebView object directly. 

cc @amirh for thoughts.

**Comment by zhihuitang** [comment] 2021-01-30 20:10
Hi @MaruQuarky , have you found a solution?

**Comment by zhihuitang** [comment] 2021-01-31 10:05
Hi @MaruQuarky , I found a workaround, use `flutter_inappwebview` to create a local web server and host your HTML on it. It works for me. [reference](https://medium.com/flutter-community/inappwebview-the-real-power-of-webviews-in-flutter-c6d52374209d)

```
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

InAppLocalhostServer localhostServer = new InAppLocalhostServer();
Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await localhostServer.start();
  print("InAppLocalhostServer started");
  runApp(new MyApp());
}
```

home_page.dart
```
class HomePage extends StatelessWidget {
  InAppWebViewController _webViewController;
  final String homeUrl = "http://127.0.0.1:8080/assets/www/index1.html";

  @override
  Widget build(BuildContext context) {
    bool haptic = DepartureSettingStateContainer.of(context).hapticFeedback;
    print("loading ${homeUrl}");
    return Scaffold(
      body: Center(
          child: InAppWebView(
        initialUrl: homeUrl,
        initialOptions: InAppWebViewGroupOptions(
            crossPlatform: InAppWebViewOptions(
          debuggingEnabled: true,
        )),
        onWebViewCreated: (InAppWebViewController controller) {
          _webViewController = controller;
          print("onWebViewCreated");
        },
        onLoadStart: (InAppWebViewController controller, String url) {
          print("onLoadStart: ${url}");
        },
        onLoadStop: (InAppWebViewController controller, String url) async {},
        onProgressChanged: (InAppWebViewController controller, int progress) {
          print("onProgressChanged: ${progress}");
        },
      )),
    );
  }

```

**Comment by greensopinion** [comment] 2021-05-15 17:34
There's also [asset_webview](https://pub.dev/packages/asset_webview)

**Comment by AntonShipunov** [comment] 2021-07-08 05:19
Hi @MaruQuarky.
The problem is that the files are located in assets. I faced the same problem on Java.
For this to work, need to move html and linked files to directory.
I found the solution for webview_flutter on:
[https://stackoverflow.com/questions/59007345/how-to-use-local-js-or-css-file-while-using-webview-flutter-plugin](url)

`WebView(
        onWebViewCreated: (WebViewController webViewController) async {
          _controller = webViewController;
          await _loadHtml();
        },`
`Future<void> _loadHtml() async {
    String cssText = await rootBundle.loadString('assets/html/sample.css');
    String htmlText = await rootBundle.loadString('assets/html/sample.html');

    final tempDir = await getTemporaryDirectory();
    final cssPath = join(tempDir.path, 'sample.css');
    final htmlPath = join(tempDir.path, 'sample.html');

    await File(cssPath).writeAsString(cssText);
    await File(htmlPath).writeAsString(htmlText);

    _controller.loadUrl(Uri(scheme: 'file', path: htmlPath).toString());
  }`

It works.
![image](https://user-images.githubusercontent.com/59964420/124866391-66bec480-dfcd-11eb-94c7-63e8cc01495a.png)

**Comment by yfujiki** [comment] 2023-02-16 12:03
@AntonShipunov Nice!! what of the image assets?

**Comment by stuartmorgan** [comment] 2023-04-17 23:03
Closing as a duplicate of https://github.com/flutter/flutter/issues/27086.

**Closed by stuartmorgan** 2023-04-17 23:03 UTC
Labels: plugin, p: webview, proposal, passed first triage, P5
