### ISSUE TITLE
Playing DRM content 

### ISSUE THREAD

**Issue by gowthamkrishnabj** [flutter/flutter#61160] opened 2020-07-09 11:26 UTC
My question is based on DRM.

A) does flutter support DRM ?
B) If Yes how to use DRM in flutter?
c) is flutter good for OTT application?

**Comment by TahaTesser** [comment] 2020-07-09 15:20
duplicate of https://github.com/flutter/flutter/issues/24923

**Closed by TahaTesser** 2020-07-09 15:20 UTC
