### ISSUE TITLE
Trying to build ios app using codemagic

### ISSUE THREAD

**Issue by grajwan1906** [flutter/flutter#52573] opened 2020-03-13 22:08 UTC
Hi,

I am trying to build ios app using codemagic.
when I tried to build for android its worked but when I trying to build it to ios I getting a build error.
I don't know why I got an error and how can I fix this?

This is the error:

== Building for iOS ==

> /usr/local/bin/flutter build ios --release --no-codesign

Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.urduns.hapoelrgg for device (ios-release)...

Running pod install...                                          
  358.9s (!)
CocoaPods' output:
↳

      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

**Comment by jonahwilliams** [comment] 2020-03-14 19:45
This does not include a build error. Did you include all of the logs?

**Comment by grajwan1906** [comment] 2020-03-15 01:59
> This does not include a build error. Did you include all of the logs?
The code is too long so I upload a text file with it to this link: https://www102.zippyshare.com/v/51z72Rs7/file.html

**Comment by jonahwilliams** [comment] 2020-03-15 03:27
My browser freezes whenever I visit that site. Could you perhaps upload the file somewhere like a github gist?

**Comment by grajwan1906** [comment] 2020-03-15 11:51
> My browser freezes whenever I visit that site. Could you perhaps upload the file somewhere like a github gist?

Ok, Try this link: https://gist.github.com/grajwan1906/d1504221d06f947d6480be7df788a3bb

**Comment by jonahwilliams** [comment] 2020-03-15 22:18
Thanks! I see an "Error running pod install" at the end. What happens if you manually run cocoapods? Does this reproduce on a blank project (with atleast one pod dependency?)

**Comment by grajwan1906** [comment] 2020-03-16 00:37
> Thanks! I see an "Error running pod install" at the end. What happens if you manually run cocoapods? Does this reproduce on a blank project (with atleast one pod dependency?)

I don't have a mac so I tried to build this using codemagic.
When I build a blank project the build is successful.
What is cocoapods?
What that I not understand it's that when I build it for android its working but not for ios so I think that the problem is with the ios files (but I am not sure).

**Comment by iapicca** [comment] 2020-03-16 07:33
Hi @grajwan1906 
the problem is likely related with your project configuration
rather then flutter itself;
since you are using codemagic you can get some help from the [community](https://join.slack.com/t/codemagicio/shared_invite/enQtNzQyODExMTQyMDcwLTQ2NTJjODE3NTA2Njg3Y2ViYmZiNGE1MWMyYWNjY2I0MzRmM2M2YmZhOTE1YTc5YjNkMmI0MzQzZWU0MzA4OGM)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2020-03-16 07:33 UTC
Labels: in triage
