### ISSUE TITLE
A problem occurred evaluating project ':cloud_firestore'.

### ISSUE THREAD

**Issue by farukoflaz** [flutter/flutter#76249] opened 2021-02-17 23:44 UTC
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\development\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0\android\build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':cloud_firestore'.
> build_2yq8w8slntfd1pcrdfbqqhulb$_run_closure2$_closure4

Lines of codes as follows 
```
39   android {
40     compileSdkVersion` 29
41     compileOptions {
42         sourceCompatibility JavaVersion.VERSION_1_8
43         targetCompatibility JavaVersion.VERSION_1_8
44     }
```
Is the problem about JAVA version or firestore?

**Comment by TahaTesser** [comment] 2021-02-18 07:42
Hi @farukoflaz 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-18 07:42 UTC
