### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists., errno = 183

### ISSUE THREAD

**Issue by BPOTW** [flutter/flutter#133995] opened 2023-09-04 17:00 UTC
## Command
```
flutter build windows
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Cannot create a file when that file already exists.
, errno = 183
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#6      buildWindows (package:flutter_tools/src/windows/build_windows.dart:64:3)
#7      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:56:11)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.23419.1000], locale en-PK)
    [32m•[39m Flutter version 3.10.1 on channel stable at D:\Flutter\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision d3d8effc68 (4 months ago), 2023-05-16 17:59:05 -0700
    [32m•[39m Engine revision b4fb11214d
    [32m•[39m Dart version 3.0.1
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at D:\Android\SDK
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m Java binary at: C:\Program Files\Java\jdk-18.0.2\bin\java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 18.0.2+9-61)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.81.1)
    [32m•[39m VS Code at C:\Users\Rehman Computers\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.72.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.23419.1000]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.141
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.12

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: d3d8effc686d73e0114d71abdcccef63fa1f25d2
### Plugins
file_picker-5.3.3
firebase_core-2.15.0
firebase_core_web-2.6.0
firebase_database-10.2.4
firebase_database_web-0.2.3+4
firebase_storage-11.2.5
firebase_storage_web-3.6.5
flutter_plugin_android_lifecycle-2.0.15

**Comment by huycozy** [comment] 2023-09-05 04:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/90028.

**Closed by huycozy** 2023-09-05 04:55 UTC
Labels: in triage
