### ISSUE TITLE
 ExoPlayer has been deprecated and integrated into the AndroidX Media3 library as of 2024

### ISSUE THREAD

**Issue by spdeol20** [flutter/flutter#155682] opened 2024-09-25 11:04 UTC
Migrating to Media3 (v1.1.1) is the recommended action, as it ensures that you are using the latest, more secure version of the media player framework.
Recommended Action:
Migrate to AndroidX Media3: This migration is more likely to resolve any issues related to random number generation and other security concerns.
Use Secure Random Number Generators: If the application uses random number generation directly, consider replacing any insecure generators like java.util.Random with more secure alternatives such as java.security.SecureRandom.

Please fix it

**Comment by darshankawar** [comment] 2024-09-25 12:49
@spdeol20 
This seems to be already fixed as part of https://github.com/flutter/flutter/issues/130272 that you can check.

**Comment by spdeol20** [comment] 2024-09-25 14:51
pls check this as well  did they replace  java.util.Random with   java.security.SecureRandom. this is more secure

**Comment by stuartmorgan** [comment] 2024-09-25 16:21
As mentioned above, the only Flutter-team-controlled code using an older version of ExoPlayer is already migrated. Closing as that is a duplicate, and there is nothing else actionable here given that there is source provided for the errors, no attribution to any specific code, and no reproduction steps.

If you have warnings when analyzing your application with some system, please isolate the specific thing causing the warning—which could be Flutter itself, a Flutter-team-owned package, a third-party package, or your own code; we have no way of determining that from just the message—and file a detailed issue against the relevant author.

**Closed by stuartmorgan** 2024-09-25 16:21 UTC
Labels: in triage
