### ISSUE TITLE
iOS status bar very difficult to read with dark material theme

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#3544] opened 2016-04-25 23:13 UTC
Open the Material Gallery demo app, set it to the dark theme and visit the weather demo. Note that the iOS status bar is very difficult to read because it is black text on a dark gray background. Probably should tell iOS to use white text like the iOS stocks app does.

**Comment by sethladd** [comment] 2016-04-25 23:14
Thanks for the feedback!

**Comment by eseidelGoogle** [comment] 2016-05-20 16:41
I've asked @tvolkert to own or find an owner for.

**Comment by eseidelGoogle** [comment] 2016-05-31 16:09
FYI: @abarth ran into this this weekend when writing an app. :/  Seems like a rather common occurrence.

**Comment by tvolkert** [comment] 2016-05-31 19:57
@rmacnak-google I'm seeing the same behavior on the Stocks example - did you see white text in the iOS status bar in stocks?

**Comment by rmacnak-google** [comment] 2016-05-31 20:05
To clarify, I was comparing Apple's stocks app as a dark-themed app that updates the status bar to white text, not saying the Flutter gallery app and Flutter stocks app behave differently.

**Comment by tvolkert** [comment] 2016-05-31 21:02
The issue is that we [explicitly opt out of view controller based status bar appearance](https://github.com/flutter/engine/blob/master/sky/build/Info.plist#L45) because [we want to able to modify the visibility on the fly](https://github.com/flutter/engine/blob/master/sky/services/platform/ios/system_chrome_impl.mm#L70).  So although we [specify in the controller](https://github.com/flutter/engine/blob/master/sky/shell/platform/ios/framework/Source/FlutterViewController.mm#L454) that the status bar should use light content, the view controller is never consulted.

This opens a new question though - should we try to manage the status bar appearance automatically in the engine the same way we manage the status bar visibility, or should we provide a way in Dart to specify this?

**Comment by abarth** [comment] 2016-05-31 21:06
In the framework, the `Title` widget is what we use to control these sorts of system UI colors.  We could either compute the color we want for the status bar text from `Title.color` or we could add a new field on that object to communicate that information.

**Comment by abarth** [comment] 2016-05-31 21:07
Looks like `Title` currently backends into activity.mojom.  We should probably add something to `sky/services/platform` to receive this data in a less Android-specific way.

**Comment by abarth** [comment] 2016-05-31 21:08
Looks like `sky/services/platform/system_chrome.mojom` might be the right place to plumb this data.

**Comment by tvolkert** [comment] 2016-06-01 05:57
FYI, working on a patch to fix this

**Comment by tvolkert** [comment] 2016-06-07 21:40
Fixed by #4422

**Closed by tvolkert** 2016-06-07 21:40 UTC
Labels: customer: gallery, ⌺‬ platform-ios, ⚠ bug
