### ISSUE TITLE
Unable to find bundle Java + Android license 

### ISSUE THREAD

**Issue by Kellie8** [flutter/flutter#120227] opened 2023-02-07 21:19 UTC
Hello 👋 
I'm struggling! I haven't found any solution to this problem ⚠️

[✓] Flutter (Channel stable, 3.7.1, on macOS 13.1 22C65 darwin-arm64 (Rosetta),
    locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ❌ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
   ❌Unable to find bundled Java version.
[✓] Connected device (3 available)
[✓] HTTP Host Availability

I've tried:
👉  Go to android studio/ studio manager / SDK Tools
👉  Run flutter config --android-studio-dir <directory> zsh: parse error near `\n'
👉  path/to/sdkmanager --install "cmdline-tools;latest"
👉  flutter doctor --android-licenses
👉  https://github.com/flutter/flutter/issues/118502

**My specs:**

Macbook Apple M1
MacOS 13.1 (22C65)
Android Studio Electric Eel | 2022.1.1

**Comment by darshankawar** [comment] 2023-02-08 07:47
@Kellie8 
This issue has been fixed as part of https://github.com/flutter/flutter/issues/106674 so please switch to latest master and try again to see the fix working.

Also, for `Android license status unknown`, follow the instructions mentioned below it to make it work:

```
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for
```

Closing this as duplicate of linked issue.

**Closed by darshankawar** 2023-02-08 07:47 UTC
Labels: in triage

**Comment by Kellie8** [comment] 2023-02-08 13:11
@darshankawar I have tried Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for
and this is what I get:flutter doctor --android-licenses
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:669)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:65

**Comment by darshankawar** [comment] 2023-02-09 05:09
@Kellie8 
You'll need to just update to a higher jdk version.

**Comment by Kellie8** [comment] 2023-02-12 21:23
I have updated to java 19 does it exist a higher version than that?

**Comment by darshankawar** [comment] 2023-02-13 05:18
Please check [this](https://github.com/flutter/flutter/issues/120388) similar issue and underlying comments and see if they help in your case.
