### ISSUE TITLE
Oops; flutter has exited unexpectedly: "type 'Null' is not a subtype of type 'String' in type cast"

### ISSUE THREAD

**Issue by M1chlCZ** [flutter/flutter#111922] opened 2022-09-17 00:50 UTC
## Steps to Reproduce

Have latest version of the Flutter on channel dev with Android Studio 2021.1.31 and IntelliJ Flutter Tools 70.0.0.4

I did Flutter Upgrade, at time of writing version 3.4.0-19.0.pre.323 and it came immediately  after update

Flutter version: Channel master, commit `0161731c359b411333111c4fcf0cdce6da01e008` running on macOS 12.6 on M1 OG MacBook 13 Pro

flutter doctor -v

```
Oops; flutter has exited unexpectedly: "type 'Null' is not a subtype of type 'String' in type cast".
Unable to generate crash report due to secondary error: type 'Null' is not a subtype of type 'String' in type cast
#0      AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:52:90)
flutter/flutter-intellij#1      AndroidStudio._allMacOS.<anonymous closure> (package:flutter_tools/src/android/android_studio.dart:316:68)
flutter/flutter-intellij#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:31)
flutter/flutter-intellij#3      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
flutter/flutter-intellij#4      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:870:20)
flutter/flutter-intellij#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
flutter/flutter-intellij#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
flutter/flutter-intellij#7      new List.of (dart:core-patch/array_patch.dart:51:28)
flutter/flutter-intellij#8      Iterable.toList (dart:core/iterable.dart:470:12)
flutter/flutter-intellij#9      AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:318:10)
flutter/flutter-intellij#10     AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:247:34)
flutter/flutter-intellij#11     AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:33:55)
flutter/flutter-intellij#12     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:110:35)
flutter/flutter-intellij#13     Doctor.validators (package:flutter_tools/src/doctor.dart:229:47)
flutter/flutter-intellij#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:235:45)
flutter/flutter-intellij#15     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:694:60)
flutter/flutter-intellij#16     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
flutter/flutter-intellij#17     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:698:53)
flutter/flutter-intellij#18     DoctorText.text (package:flutter_tools/src/doctor.dart:690:36)
flutter/flutter-intellij#19     DoctorText.text (package:flutter_tools/src/doctor.dart)
flutter/flutter-intellij#20     _createLocalCrashReport (package:flutter_tools/runner.dart:211:51)
flutter/flutter-intellij#21     _handleToolError (package:flutter_tools/runner.dart:167:31)
<asynchronous suspension>
flutter/flutter-intellij#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
flutter/flutter-intellij#23     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "type 'Null' is not a subtype of type 'String' in type cast".
Unable to generate crash report due to secondary error: type 'Null' is not a subtype of type 'String' in type cast
#0      AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:52:90)
flutter/flutter-intellij#1      AndroidStudio._allMacOS.<anonymous closure> (package:flutter_tools/src/android/android_studio.dart:316:68)
flutter/flutter-intellij#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:31)
flutter/flutter-intellij#3      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
flutter/flutter-intellij#4      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:870:20)
flutter/flutter-intellij#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
flutter/flutter-intellij#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
flutter/flutter-intellij#7      new List.of (dart:core-patch/array_patch.dart:51:28)
flutter/flutter-intellij#8      Iterable.toList (dart:core/iterable.dart:470:12)
flutter/flutter-intellij#9      AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:318:10)
flutter/flutter-intellij#10     AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:247:34)
flutter/flutter-intellij#11     AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:33:55)
flutter/flutter-intellij#12     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:110:35)
flutter/flutter-intellij#13     Doctor.validators (package:flutter_tools/src/doctor.dart:229:47)
flutter/flutter-intellij#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:235:45)
flutter/flutter-intellij#15     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:694:60)
flutter/flutter-intellij#16     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
flutter/flutter-intellij#17     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:698:53)
flutter/flutter-intellij#18     DoctorText.text (package:flutter_tools/src/doctor.dart:690:36)
flutter/flutter-intellij#19     DoctorText.text (package:flutter_tools/src/doctor.dart)
flutter/flutter-intellij#20     _createLocalCrashReport (package:flutter_tools/runner.dart:211:51)
flutter/flutter-intellij#21     _handleToolError (package:flutter_tools/runner.dart:167:31)
<asynchronous suspension>
flutter/flutter-intellij#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:86:7)
<asynchronous suspension>

Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:181:7)
<asynchronous suspension>
flutter/flutter-intellij#1      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:86:7)
<asynchronous suspension>
Process finished with exit code 255
```

**Comment by huycozy** [comment] 2022-09-20 09:00
Hi @M1chlCZ, thanks for filing the issue. 
But I can not reproduce the issue on latest `stable` and `master` channels.
My device info: `macOS 12.6 21G115 darwin-x64` 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.379, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.379 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d5bee36d24 (2 hours ago), 2022-09-20 15:13:47 +0800
    • Engine revision 6aa226bbce
    • Dart version 2.19.0 (build 2.19.0-219.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

Could you try again on stable channel `3.3.2` to see if the issue is reproducible?

**Comment by M1chlCZ** [comment] 2022-09-20 11:14
@huycozy Hey, the problem does not exist on Stable channel. I think it's time to close, because it seems that not even on new master channel this issue no longer exists. Sorry for overreaction.

**Comment by huycozy** [comment] 2022-09-20 11:32
Hi @M1chlCZ 
Based on the last comment, I will close this issue as fixed on the latest `master` channel. Thank you for confirming!

**Closed by huycozy** 2022-09-20 11:32 UTC
Labels: in triage
