### ISSUE TITLE
any solution??  when i play mp4 video then getting ther crash error for android tv

### ISSUE THREAD

**Issue by iamwasimaftab** [flutter/flutter#97094] opened 2022-01-23 11:47 UTC
E/flutter ( 6778): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

**Comment by darshankawar** [comment] 2022-01-24 10:10
Closing this as a duplicate of https://github.com/flutter/flutter/issues/75995

**Closed by darshankawar** 2022-01-24 10:10 UTC
Labels: in triage
