### ISSUE TITLE
specific device have a flickering  issue  in our app

### ISSUE THREAD

**Issue by rkd618** [flutter/flutter#129978] opened 2023-07-05 06:14 UTC
I am trying to fix my app issue which is made of  Flutter and Golang. Some clients facing a flickering issue only have a flickering with only my. Can anyone tell me how to create an environment  for solving that flickering issue? Surprisingly only few users are facing it how should I solve it ? Any help will be appreciated. all three are different devices from different companies                                           1) Galaxy Z Flip 4
2) OnePlus 10R 5G 
Processor - mediates
Android 13 Dimensity 8100- Max

https://github.com/flutter/flutter/assets/124025953/73099b53-7e90-4d44-8b22-a1ae8772979f

Ram 8.00 GB+ 6.00 GB
3) Google pixel 6
Android 13. It's 3 device totally were issue occurred.
 I checked even on the emulator but in the emulator it's working properly All three are Android 13,  but i checked many real devices of Android 13  there working fine
![937eb91d-5cf0-4757-af96-28982ff15acb](https://github.com/flutter/flutter/assets/124025953/23a201e0-48e2-4cb0-85e8-52e90b049b40)

**Comment by danagbemava-nc** [comment] 2023-07-05 08:45
Hi @rkd618, this is a duplicate of https://github.com/flutter/flutter/issues/123123. 

Kindly share the following information requested in the original issue. 

> A code sample and detailed reproduction steps that triggers the issue, or
> Full un-redacted device logs collected starting from just before the flickering starts.

Can you also upgrade to the latest stable version of flutter to see if the issue still reproduces(if you can upgrade at this time)?

Thank you

**Closed** 2023-07-26 09:08 UTC
Labels: waiting for customer response, in triage
