### ISSUE TITLE
Text field of showDatePicker() only allows numbers to be entered on some devices

### ISSUE THREAD

**Issue by jsstanley** [flutter/flutter#68100] opened 2020-10-14 12:14 UTC
## Steps to Reproduce

1. Open a showDatePicker() (all default settings apart from colour changes):

![](https://user-images.githubusercontent.com/50111317/95986298-ab8e4400-0e1d-11eb-972f-2e25d3d10ccb.png)

2. Press the pencil icon to obtain the text entry option:

![](https://user-images.githubusercontent.com/50111317/95986327-b648d900-0e1d-11eb-9363-a23380b58684.png)

**Expected results:** 
The input keyboard should have an option to add forward slashes to the text field across all devices.

**Actual results:** 
The above screenshots show a Nexus 5X Emulator device (running Android 10) working as intended. However, on some devices, such as the Samsung Note 10+ (also running Android 10), the input keyboard displayed only gives the option of entering numbers:

1. Open a showDatePicker():

![](https://user-images.githubusercontent.com/50111317/95986819-7afada00-0e1e-11eb-8b59-74eba0f09b6c.png)

2. Press the pencil icon to obtain the text entry option:

![](https://user-images.githubusercontent.com/50111317/95986858-8bab5000-0e1e-11eb-8316-e1dba91ed9a3.png)

Due to this restricted number input on some devices, only entering numbers into the text field returns an `Invalid format.` error in the UI.

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel beta, 1.22.1, on Microsoft Windows [Version 10.0.19041.508], locale en-GB)
    • Flutter version 1.22.1 at C:\Flutter\flutter
    • Framework revision f30b7f4db9 (6 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.1

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.38

! Doctor found issues in 1 category.
```

</details>

**Comment by jsstanley** [comment] 2020-10-14 12:16
I should add that due to the restricted number input on some devices, only entering numbers into the text field returns an `Invalid format.` error in the UI.

**Comment by darshankawar** [comment] 2020-10-14 12:45
Closing this as duplicate of [62401](https://github.com/flutter/flutter/issues/62401)

**Closed by darshankawar** 2020-10-14 12:45 UTC

**Comment by jsstanley** [comment] 2020-10-14 12:53
Thanks, didn't see that issue in my search prior to posting.
