### ISSUE TITLE
ListTile sugests alternartive

### ISSUE THREAD

**Issue by staminna** [flutter/flutter#74499] opened 2021-01-22 15:53 UTC
Hi everyone,

I am completely new to flutter, so this may be obvious to you.
I am trying to create a ListTile inside a Container using 85% of the width.
ps. Line 183 is child: new ListTile(

Here follows the code:

```dart
class EntryItem extends StatelessWidget {
  const EntryItem(this.entry);

  final ListEntry entry;

  @override
  Widget build(BuildContext context) {
    return new Container(
      color: AppColorsTheme.myTheme.secondaryGradientColor,
      child: FractionallySizedBox(
        widthFactor: 0.85,
        //heightFactor: 0.3,
      child: new ListTile(
        title: new Text(entry.title),
        subtitle: new Text(entry.description),
        leading: new Icon(
          Icons.dashboard,
          color: AppColorsTheme.myTheme.primarySwatch,
        ),
        trailing: new Row(
          verticalDirection: VerticalDirection.up,
          children: <Widget>[
            new CategoryIcon(Icons.remove_red_eye, entry.views.toString(), false),
            new CategoryIcon(Icons.comment, entry.responses.toString(), false),
          ],
        ),
        onTap: () {Navigator.pushNamed(context, '/forum/1');},
      ),
      ),
    );
  }}

```

<details>
<summary>logs</summary>

```bash

flutter: The following assertion was thrown during performLayout():
flutter: Trailing widget consumes entire tile width. Please use a sized widget, or consider replacing
flutter: ListTile with a custom widget (see
flutter: https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
flutter: 'package:flutter/src/material/list_tile.dart':
flutter: Failed assertion: line 1553 pos 7: 'tileWidth != trailingSize.width'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   ListTile file:///Users/.../mobile-apps/App/lib/forum.dart:183:18
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:1553:7)
flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:12)
flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #18     RenderFractionallySizedOverflowBox.performLayout (package:flutter/src/rendering/shifted_box.dart:958:14)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #26     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:205:28)
flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #28     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:132:12)
flutter: #29     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
flutter: #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #31     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:507:13)
flutter: #32     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1904:12)
flutter: #33     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1862:20)
flutter: #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #47     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:768:15)
flutter: #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #49     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
flutter: #50     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:498:7)
flutter: #51     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
flutter: #52     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
flutter: #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #57     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1308:11)
flutter: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #65     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:560:15)
flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #77     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3220:14)
flutter: #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
flutter: #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
flutter: #81     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:685:15)
flutter: #82     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
flutter: #83     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
flutter: #84     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:436:19)
flutter: #85     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
flutter: #86     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
flutter: #87     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #88     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
flutter: #89     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
flutter: #93     _invoke (dart:ui/hooks.dart:251:10)
flutter: #94     _drawFrame (dart:ui/hooks.dart:209:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: _RenderListTile#3025d relayoutBoundary=up22 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← ColoredBox ← Semantics ← _PointerListener ←
flutter:     Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ← _RawMouseRegion ← ⋯
flutter:   parentData: offset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: BoxConstraints(w=331.8, 0.0<=h<=Infinity)
flutter:   size: MISSING
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     leading: RenderSemanticsAnnotations#8b19e relayoutBoundary=up23 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child: RenderExcludeSemantics#23909 relayoutBoundary=up24 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderConstrainedBox#09c65 relayoutBoundary=up25 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderPositionedBox#123c9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderParagraph#ba4c9 relayoutBoundary=up1 NEEDS-PAINT
flutter:     title: RenderParagraph#66388 NEEDS-LAYOUT NEEDS-PAINT
flutter:       text: TextSpan
flutter:     subtitle: RenderParagraph#ff3b4 NEEDS-LAYOUT NEEDS-PAINT
flutter:       text: TextSpan
flutter:     trailing: RenderFlex#506fb relayoutBoundary=up23 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child 1: RenderFlex#8a2aa relayoutBoundary=up24 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE OVERFLOWING
flutter:         child 1: RenderSemanticsAnnotations#59f94 relayoutBoundary=up25 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderSemanticsAnnotations#9caec relayoutBoundary=up26 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderMouseRegion#2c5e8 relayoutBoundary=up27 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child 2: RenderParagraph#f7dbb relayoutBoundary=up25 NEEDS-PAINT
flutter:           text: TextSpan
flutter:       child 2: RenderFlex#df3ed relayoutBoundary=up24 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE OVERFLOWING
flutter:         child 1: RenderSemanticsAnnotations#144d6 relayoutBoundary=up25 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderSemanticsAnnotations#31821 relayoutBoundary=up26 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderMouseRegion#5ec08 relayoutBoundary=up27 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child 2: RenderParagraph#5e2f5 relayoutBoundary=up25 NEEDS-PAINT
flutter:           text: TextSpan
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderBox was not laid out: _RenderListTile#3025d relayoutBoundary=up22 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPadding#46d75 relayoutBoundary=up21 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderColoredBox#e57d2 relayoutBoundary=up20 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#42669 relayoutBoundary=up19 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#e03a9 relayoutBoundary=up18 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#49ad9 relayoutBoundary=up17 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderMouseRegion#3305c relayoutBoundary=up16 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#f0aa9 relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderFractionallySizedOverflowBox#bfa6d relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderColoredBox#e12ab relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#9dec4 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 545 pos 12: 'child.hasSize': is not true.
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#f15b6 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#211e8 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#319e5 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#1e2a5 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#ee1e3 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#14873 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#75a5b relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#ddc76 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: Null check operator used on a null value
flutter: Another exception was thrown: Null check operator used on a null value
```
</details>

**Comment by TahaTesser** [comment] 2021-01-25 08:40
Hi @staminna 

> flutter: Trailing widget consumes entire tile width. Please use a sized widget, or consider replacing
> flutter: ListTile with a custom widget (see
> flutter: https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
> flutter: 'package:flutter/src/material/list_tile.dart':
> flutter: Failed assertion: line 1553 pos 7: 'tileWidth != trailingSize.width'


This is because you're trying to fit a `Row` in trailing which has a width wider than the maximum trailing width size. 
It can reproduce this way 
```dart
   body: Center(
        child: FractionallySizedBox(
          widthFactor: 0.85,
          child: ListTile(
            tileColor: Colors.grey[700],
            leading: FlutterLogo(),
            title: Text('One-line with leading widget'),
            trailing: Row(
              children: [
                FlutterLogo(
                  size: 100,
                ),
              ],
            ),
          ),
        ),
      ),
```

but no issue  if you constraint `Row`s width with `SizedBox`
```dart
     body: Center(
        child: FractionallySizedBox(
          widthFactor: 0.85,
          child: ListTile(
            tileColor: Colors.grey[700],
            leading: FlutterLogo(),
            title: Text('One-line with leading widget'),
            trailing: SizedBox(
              child: Row(
                children: [
                  FlutterLogo(
                    size: 100,
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
```




<details>
<summary>complete runnable code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: FractionallySizedBox(
          widthFactor: 0.85,
          child: ListTile(
            tileColor: Colors.grey[700],
            leading: FlutterLogo(),
            title: Text('One-line with leading widget'),
            trailing: Row(
              children: [
                FlutterLogo(
                  size: 100,
                ),
              ],
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

</details>


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-25 08:40 UTC
