### ISSUE TITLE
StreamBuilders cannot be the first child of CustomScrollView

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#25861] opened 2018-12-29 01:26 UTC
Hello,

I found a bug where if a StreamBuilder is the first child of a CustomScrollView it will throw these two errors randomly.

```
flutter: Another exception was thrown: 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1213 pos 12: 'center.parent == this': is not true.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
```

It does not matter if the StreamBuilder is returning a sliver or not.

What's worse is it's not consistent. Out of 10 tries it will happen maybe 6 times and in seemingly random order. Possible race condition?

The workaround is to place a `SliverToBoxAdapter()` as the first child, then the problem goes away.

**Comment by vaibhav93** [comment] 2018-12-30 07:52
I am facing the same issue.


## Steps to Reproduce



Minimal main.dart

[https://gist.github.com/vaibhav93/d62f3e8cb715f8b0ee0c1cb4f6329a45](https://gist.github.com/vaibhav93/d62f3e8cb715f8b0ee0c1cb4f6329a45)

## Logs

https://gist.github.com/vaibhav93/cd52388bd13555ad18aef3dc79a35cbe


## flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale
    en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android
    SDK 28.0.3)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific
      functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-12-30 14:55
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment] 2018-12-30 14:56
Please add the output of `flutter doctor -v`.

**Comment by wendux** [comment] 2019-03-31 09:16
I am facing the same issue.

**Comment by meysammahfouzi** [comment] 2019-04-04 20:43
I'm getting the same error with `FutureBuilder` as the first child of `CustomScrollView`. And it does not happen after hot reload.

**Comment by sarthak1singhal** [comment] 2019-07-20 07:23
Even I am having the same issue. Did anyone found the solution ?

**Comment by sarthak1singhal** [comment] 2019-07-20 07:24
> Hello,
> 
> I found a bug where if a StreamBuilder is the first child of a CustomScrollView it will throw these two errors randomly.
> 
> ```
> flutter: Another exception was thrown: 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1213 pos 12: 'center.parent == this': is not true.
> flutter: Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
> ```
> 
> It does not matter if the StreamBuilder is returning a sliver or not.
> 
> What's worse is it's not consistent. Out of 10 tries it will happen maybe 6 times and in seemingly random order. Possible race condition?
> 
> The workaround is to place a `SliverToBoxAdapter()` as the first child, then the problem goes away.


How did you solved this issue ?

**Comment by sarthak1singhal** [comment] 2019-07-20 07:29
I think I solved the issue by passing 

SliverList(
            delegate: SliverChildListDelegate([
              Container(
              )
            ]),
          ),
as the first widget in the customScrollView

**Comment by lukepighetti** [comment] 2019-07-20 12:22
@sarthak1singhal yes that is a workaround for the time being

**Comment by benoitjadinon** [comment] 2019-08-18 18:54
also happened to me when I've added a widget containing a StreamBuilder as first list item of a CustomScrollView, may have something to do with a keyboard focus as well, the above workaround fixes it. very weird

**Comment by figengungor** [comment] 2019-12-19 09:55
Interesting buggie. Thanks for the temp fix. I fixed it like that: 
`slivers.insert(0, SliverToBoxAdapter());`

**Comment by Nico04** [comment] 2020-01-31 11:56
Same issue with latest stable Flutter.
Thanks for the workaround thought, I just added `SliverToBoxAdapter()` as the first sliver.

**Comment by iapicca** [comment] 2020-02-05 10:14
Hi @lukepighetti 
I feel @Nico04 's and @figengungor _workaround_ more as a solution
https://github.com/flutter/flutter/issues/30253#issuecomment-478311459
does this solve the issue for you?
thank you

**Comment by iapicca** [comment] 2020-02-26 10:49
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by iapicca** [comment] 2020-02-27 09:13
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Nico04** [comment] 2020-02-27 09:42
To me only workaround are suggested, there are not solutions.
And it seems that the issue is happening for everyone, doesn't it ?

**Comment by lukepighetti** [comment] 2020-02-28 14:32
@iapicca what response are you waiting for? Issue is clear and reproducible.

**Comment by iapicca** [comment] 2020-02-28 15:08
@lukepighetti 
I thought I found a fix, but I was wrong;
I deleted the message (with the wrong fix), but I forgot to remove the label
thank you for notifying it to me

**Comment by iapicca** [comment] 2020-02-28 15:09
Hi @lukepighetti 
I didn't add the label` waiting for customer response`, I removed it.

**Comment by lukepighetti** [comment] 2020-02-28 18:28
Thanks for clarifying, that was my mistake.

**Comment by mklpathak** [comment] 2020-03-29 18:30
WorkAround for me 
I put 
         CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(
              child: SizedBox(),
            ),
            _feedListDelegate,])

**Comment by HTibs** [comment] 2020-04-18 17:10
This is the error i am getting after wrapping the stream builder in SliverToBoxAdapter:
**A RenderRepaintBoundary expected a child of type RenderBox but received a child of type RenderSliverToBoxAdapter.**
`
SliverToBoxAdapter(

                   child: StreamBuilder(
                   stream: _firestore.collection('items').snapshots(),
                    builder: (context, snapshot) {
                     if (!snapshot.hasData) {
                         print("NONO");
                          return SliverToBoxAdapter(
                          child: SliverList(
                                  delegate:
                                      SliverChildListDelegate([Container()])),
                            );
                          }
                          print("THIS IS BEONG PRINTED");
                          return SliverToBoxAdapter(
                            child: SliverList(
                              delegate:
                                  SliverChildBuilderDelegate((context, index) {
                                return AllItemsTile();
                              }, childCount: snapshot.data.documents.length),
                            ),
                          );
                        },
                      ),
                    ),
`

**Comment by iapicca** [comment] 2020-07-24 10:32
Hi @lukepighetti 
testing this [code sample](https://dartpad.dev/2df4114b8bf4bc64e8c1b89b821de0eb) with the latest master

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/nevercode/development/flutter_master
    • Framework revision e64fe11542 (9 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

the issue seems to be resolved
I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by willladislaw** [comment] 2020-07-29 19:08
Issue remains on beta channel.

**Comment by lukepighetti** [comment] 2020-07-29 20:14
Typically issues that have been fixed in master are closed.

**Comment by willladislaw** [comment] 2020-07-30 13:36
Ah.

**Comment by willladislaw** [comment] 2020-07-30 13:37
Ah!

**Comment by LakshithVithana** [comment] 2020-11-12 12:11
> WorkAround for me
> I put
> 
> ```dart
>       CustomScrollView(
>           slivers: <Widget>[
>             SliverToBoxAdapter(
>               child: SizedBox(),
>             ),
>             _feedListDelegate,])
> ```

thanks a lot, this works well

**Comment by CoderUni** [comment] 2021-04-30 14:58
Any updates? This issue exists when `BlocBuilder` is the first widget of `CustomScrollView` and when it checks for certain states.

To reproduce:
```dart
CustomScrollView(
          slivers: [
            BlocBuilder<SomeBloc, SomeState>(
              builder: (context, state) {
                if (state is StateInitial) {
                  return SliverToBoxAdapter(
                    child: Container(),
                  );
                }
                return SomeSliverList();
              },
            ),
          ],
        ),
```
The only workaround is to make `SliverToBoxAdapter` your first sliver.

**Comment by lewcianci** [comment] 2021-07-10 22:36
This is still occuring in Flutter beta channel.

**Closed** 2022-01-14 01:40 UTC
Labels: framework, f: scrolling, customer: crowd, has reproducible steps, P4
