### ISSUE TITLE
Unexpected uncaught exception passed to `onError` of `runZonedGuarded()` despite `try`/`catch`

### ISSUE THREAD

**Issue by cbatson** [flutter/flutter#121439] opened 2023-02-25 02:50 UTC
## Steps to Reproduce

Given the following complete minimal example run on Flutter 3.7.3 and Dart 2.19.2:

<details>
<summary>Code sample</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runZonedGuarded(() {
    runApp(const MyApp());
  }, (error, stack) {
    print('onError: $error\n$stack');
  });
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final http.Client _httpClient = http.Client();

  @override
  void initState() {
    super.initState();
    request().then((value) => print('then')).catchError((error) => print('catchError'));
  }

  Future<void> request() async {
    try {
      var request = http.Request('POST', Uri.parse('http://192.168.0.1'));
      await _httpClient.send(request);
    }
    catch (error) {
      print('catch: $error');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: const Center(
        child: Text('Push the button'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _httpClient.close(), // this leads to the exceptions
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

When the "+" button on the UI is pressed, a `SocketException` is both passed to the `onError` callback of the `runZonedGuarded()` and also the `catch` block of the HTTP request.

The console output is:

```
Restarted application in 720ms.
flutter: onError: SocketException: Connection attempt cancelled, host: 192.168.0.1, port: 80
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:694:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1855:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2078:22)
#4      Socket.startConnect (dart:io/socket.dart:763:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2466:20)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2906:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2911:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2766:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2604:7)
#10     IOClient.send
#11     _MyHomePageState.request
#12     _MyHomePageState.initState
#13     StatefulElement._firstBuild
#14     ComponentElement.mount
--- 8< ---
#384    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)<…>
flutter: catch: Connection attempt cancelled, host: 192.168.0.1, port: 80
flutter: then
```

**Expected results:**

1. A single exception
2. The exception handled by the `catch` and not `onError` of `runZonedGuarded()`

**Actual results:**

1. Two exceptions
2. One exception in `onError` of `runZonedGuarded()` and one in `catch`

It's not clear to me if this is a bug or "as designed" behavior, but I found it surprising.

## Questions

1. Why are two apparently identical exceptions raised rather than one? (The two exception objects have different identity hash codes, but otherwise appear equivalent.)
2. Why, if the exception passed to `onError` is considered uncaught, does the stack trace for that very exception clearly show the `try`/`catch` block as an ancestor?
4. How can I catch the uncaught exception? So that it can be dealt with at the call site and not be uncaught?

## Notes

1. It's intentional for this demonstration that the HTTP request and subsequent client closure results in a `SocketException`. I'm not asking why this results in a `SocketException`. I'm asking why there are *two* exceptions, one of which is considered uncaught, despite the use of `try`/`catch`.
2. Originally posed as a question [on stackoverflow](https://stackoverflow.com/q/75453561) (with no response).
3. Posting in the `flutter` repo and not `dart-lang` because the behavior described does not appear to occur when the call to `WidgetsFlutterBinding.ensureInitialized()` is commented out.
5. This behavior was observed on an iOS device.

**Comment by danagbemava-nc** [comment] 2023-02-27 07:50
I can reproduce the issue using the code sample provided above. 

Labeling for further insight. 

<details>
<summary>logs</summary>

### without calling `WidgetsFlutterBinding.ensureInitialized()`

```
Launching lib/main.dart on M2007J20CG in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54145/YKzYPFUvE3Q=/ws
E/com.example.sa(19728): open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
D/DecorView[](19728): onWindowFocusChanged hasWindowFocus true
D/MIUIInput(19728): [MotionEvent] ViewRootImpl windowName 'com.example.sam/com.example.sam.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=815282959, downTime=815282959, phoneEventTime=07:38:46.312 } moveCount:0
D/MIUIInput(19728): [MotionEvent] ViewRootImpl windowName 'com.example.sam/com.example.sam.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=815283045, downTime=815282959, phoneEventTime=07:38:46.398 } moveCount:10
I/flutter (19728): catch: Connection attempt cancelled, host: 192.168.0.1, port: 80
I/flutter (19728): then
```


### calling `WidgetsFlutterBinding.ensureInitialized()`

```
Launching lib/main.dart on M2007J20CG in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54292/ZTTSNyMD_WQ=/ws
E/com.example.sa(19929): open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
D/DecorView[](19929): onWindowFocusChanged hasWindowFocus true
D/MIUIInput(19929): [MotionEvent] ViewRootImpl windowName 'com.example.sam/com.example.sam.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=815337952, downTime=815337952, phoneEventTime=07:39:41.305 } moveCount:0
D/MIUIInput(19929): [MotionEvent] ViewRootImpl windowName 'com.example.sam/com.example.sam.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=815338067, downTime=815337952, phoneEventTime=07:39:41.420 } moveCount:4
I/flutter (19929): onError: SocketException: Connection attempt cancelled, host: 192.168.0.1, port: 80
I/flutter (19929): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:689:35)
I/flutter (19929): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1849:26)
I/flutter (19929): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
I/flutter (19929): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:2072:22)
I/flutter (19929): #4      Socket.startConnect (dart:io/socket.dart:765:21)
I/flutter (19929): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2478:20)
I/flutter (19929): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2916:12)
I/flutter (19929): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2921:12)
I/flutter (19929): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2776:12)
I/flutter (19929): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2614:7)
I/flutter (19929): #10     IOClient.send
I/flutter (19929): #11     _MyHomePageState.request
I/flutter (19929): #12     _MyHomePageState.initState
I/flutter (19929): #13     StatefulElement._firstBuild (package:flutter/
I/flutter (19929): catch: Connection attempt cancelled, host: 192.168.0.1, port: 80
I/flutter (19929): then
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.7.5 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (4 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • adb-5dd3be00-17AYzd._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • iPhone 14 Pro (mobile) • 7256EA18-F2CB-4F96-9398-80DC7756A275       • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                      • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)           • chrome                                     • web-javascript • Google Chrome 110.0.5481.100

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: Failed to connect to host in 10 seconds

! Doctor found issues in 3 categories.
```

```
[!] Flutter (Channel master, 3.8.0-16.0.pre.57, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.8.0-16.0.pre.57 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 45723adf4d (3 hours ago), 2023-02-26 23:35:37 -0500
    • Engine revision 88b48c357b
    • Dart version 3.0.0 (build 3.0.0-275.0.dev)
    • DevTools version 2.22.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (5 available)
    • M2007J20CG (mobile)    • adb-5dd3be00-17AYzd._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)
    • iPhone 14 Pro (mobile) • 7256EA18-F2CB-4F96-9398-80DC7756A275       • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                      • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Web Server (web)       • web-server                                 • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                                     • web-javascript • Google Chrome 110.0.5481.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by jason-simmons** [comment] 2023-02-28 01:51
This will work as intended if the call to `WidgetsFlutterBinding.ensureInitialized()` is moved into the function passed to `runZonedGuarded`.

The Flutter framework expects that the binding initialization and the call to `runApp` will happen in the same zone.  If binding initialization happens in a different zone, then callbacks set up by the binding will be associated with that zone.  Exceptions thrown within those callbacks could then be dispatched to that zone's uncaught exception handler, causing the results above.

See https://github.com/flutter/flutter/issues/94123

**Comment by cbatson** [comment] 2023-02-28 04:30
Thank you @jason-simmons, that discussion thread was quite enlightening.

It really would be fantastic if this was documented under `WidgetsFlutterBinding.ensureInitialized()`. And also if those caveats/subtleties of zones discussed were captured in the docs for zones.

**Comment by goderbauer** [comment] 2023-02-28 23:29
We have a PR out to provide a better warning here: https://github.com/flutter/flutter/pull/117113

Closing this as duplicate of https://github.com/flutter/flutter/issues/94123.

**Closed by goderbauer** 2023-02-28 23:29 UTC
Labels: framework, has reproducible steps, found in release: 3.7, found in release: 3.8
