### ISSUE TITLE
Please do not make Color sealed

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#160613] opened 2024-12-19 19:21 UTC
On the page https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework, it states:

```dart
Note
Flutter plans to eventually lock the Color class down and make it sealed.

Now might be a good opportunity to switch from [inheritance to composition](https://en.wikipedia.org/wiki/Composition_over_inheritance) and stop reimplementing Color.
```

I kindly ask you to reconsider this decision. Locking the `Color` class and making it sealed would break my package https://pub.dev/packages/themed. Unfortunately, this package **cannot be switched from inheritance to composition** without fundamentally compromising its functionality. If the `Color` class becomes sealed, the package would simply stop working, with no way to fix it.

Currently, the package works seamlessly and provides significant usability benefits. For example, instead of writing:

```dart
Container(
   color: Theme.of(context).primary,
   child: Text('Hello', style: TextStyle(color: Theme.of(context).secondary)),
)
```

You can simply write:

```dart
Container(
   color: myColor,
   child: const Text('Hello', style: myStyle),
)
```

The package also allows colors to be used directly in **constructors**, such as:

```dart
MyWidget({
    this.color = myColor,
});
```

Without this package, the following is not possible:

```dart
MyWidget({
    this.color = Theme.of(context).primary, // This won't work!
});
```

The flexibility and simplicity offered by this package are invaluable to everyone that uses it. Sealing the `Color` class would force its deprecation, leaving no viable alternative.

Please note, I’ve been contributing to the Flutter ecosystem for a long time. I have 16 published packages (https://pub.dev/publishers/glasberg.dev/packages), and I also wrote this page in the official Flutter documentation: https://docs.flutter.dev/ui/layout/constraints

I truly value the direction and improvements Flutter continues to bring, and I hope this feedback highlights the importance of keeping the Color class open for use cases like mine. Thank you for considering this request.

**Comment by matanlurey** [comment] 2024-12-23 19:06
Thanks for filing an issue.

It's not totally clear to me what a `ColorRef` does, but the pattern we're recommending (composition) means your `ColorRef` should _provide_ a color, instead of _being_ a color. In fact, you already have implemented this (somewhat) as [`ColorRef.color`](https://pub.dev/documentation/themed/latest/themed/ColorRef/color.html).

Because of how Flutter is built, as long as your users write something like:

```diff
Widget build(BuildContext context) {
-   return SomeWidget(color: colorRef);
+   return SomeWidget(color: colorRef.color);
}
```

... you should still the dynamic updates you are looking for without needing to _be_ a color.

There is likely a long path ahead to sealing the Color class (even the framework implements colors today), but it would allow us to continue to make high quality changes and optimizations that are either impossible or cumbersome to do today due to anyone being able to implement Color.

**Comment by marcglasberg** [comment] 2024-12-23 20:27
Yes, I understand composition. First, writing `colorRef.color` adds unnecessary boilerplate, which undermines the purpose of using the package. Second, `colorRef.color` cannot be used as a default constructor parameter because it's a getter, and that simply doesn't work. If the day comes when the Color class is sealed, my package will break, forcing everyone using it to migrate elsewhere. There is no fix.

Of course, I understand if you seal classes you are more free to change and optimize things. But this comes at the cost of removing that same freedom from users and package authors.

I'm concerned with this trend of sealing native Flutter classes. One of Flutter's greatest strengths is its openness, giving developers the flexibility to adapt it to their needs. Sealing everything will make Flutter a closed ecosystem, stifling creativity. Instead of empowering developers, it could create unnecessary roadblocks and limitations.

**Comment by matanlurey** [comment] 2024-12-23 21:21
If the day comes we make _any_ change to Color, your package will break.

In any case, I'm closing this issue as it's not a bug and we've already decided to (eventually, at some point) change the type hierarchy. I'm sure this and other issues will be discussed (including possible mitigations) if and when we get to that point.

**Closed by matanlurey** 2024-12-23 21:21 UTC
Labels: framework, c: proposal, team-framework
