### ISSUE TITLE
setState not working with listview updates

### ISSUE THREAD

**Issue by AhmedAlaa96** [flutter/flutter#55466] opened 2020-04-23 15:15 UTC
Hi, everyone

I'm using `ListView.builder()` to build list view in my application and using ` List<Message>` messages as my list items which is `Message` is a custom component I made it
When I update any element in the list and `setState`  nothing happening 

```  
String getKey(List conditionKeys,selectionObject){
 if(selectionObject == null) return null;
   var _value = selectionObject[conditionKeys[0]];
   for(int i = 1;i < conditionKeys.length;i++){
     _value = _value[conditionKeys[i]];

   }

   return _value.toString();
 }



 visibilityButtonsWithConditions(final selectedObject){


   selectionObject = selectedObject;

   bool isButtonVisible;
  for(Message message in messages){
     if(message.type == "button"){
       isButtonVisible = true;
       if(message.conditions!= null){
         List<bool> operations = List<bool>();
         for(int j = 0 ; j < message.conditions.length;j++){
           String keyValue = getKey(message.conditions[j]['Key'],selectedObject);
           String value =message.conditions[j]['Value'];

           operations.add(value == keyValue);
         }
         isButtonVisible = operations[0];
         for(int j = 1;j < operations.length;j++){
           /// TODO : HANDLING MANY CONDITIONS & IF THERE IS && OR || lATER
           isButtonVisible = operations[j];
         }
       }

         setState(() {
            message.isButtonVisible = isButtonVisible;
         });
     }
     else{
       break;
     }
   }


 }
```
all I make is to call this function in callback function can anyone help me with this issue?

Thank you

**Comment by iapicca** [comment] 2020-04-24 05:36
Hi @AhmedAlaa96 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a **reproducible** minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-05-15 13:55
@AhmedAlaa96 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.

**Closed by VladyslavBondarenko** 2020-05-15 13:55 UTC
Labels: in triage, waiting for customer response

**Comment by sabinbajracharya** [comment] 2020-06-06 10:28
I am having this weird problem where using "setState" does not work with ListView.builder().
Here is the code that I run in the "dartpad.dev/flutter".
```

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'dart:developer';

void main() {
  runApp(MyApp());
}

class ItemData {
  final int id;
  final String lable;
  bool isChecked;
  
  ItemData({@required this.id, @required this.lable, this.isChecked});
}

class MyApp extends StatefulWidget {
  const MyApp({ Key key }) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}


class _MyAppState extends State<MyApp>  {
  
  List<ItemData> items = [
    ItemData(id: 1, lable: "Sabin", isChecked: false),
    ItemData(id: 12, lable: "Babin", isChecked: false),
    ItemData(id: 22, lable: "Zebin", isChecked: false),
  ];

  @override
  Widget build(BuildContext context) {
    final title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Column(
          children: [
            Expanded(
              child:ListView.builder(
          itemCount: items.length,
          itemBuilder: (context, index) {
            var item = items[index];
            return ListItem(
              key: ValueKey(item.id),
              id:items[index].id,
              lable: items[index].lable,
              isChecked: item.isChecked,
            );
          },
        ),
            )
          ]
        ),
        floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
          _items[2].isChecked = true;
          items.add(ItemData(id: 199, lable: "Batman", isChecked: true));
          setState(() => {});_
        },
        label: Text('Check'),
        icon: Icon(Icons.thumb_up),
        backgroundColor: Colors.pink,
      ),
      ),
    );
  }
}

class ListItem extends StatefulWidget {
  final int id;
  final String lable;
  final bool isChecked;
  
  ListItem({ Key key, this.id, this.lable , this.isChecked}) : super(key: key);

  @override
  _ListItemState createState() => _ListItemState();
}

class _ListItemState extends State<ListItem> with AutomaticKeepAliveClientMixin {
  
  @override
  bool get wantKeepAlive => true;
  
  int id;
  String lable;
  var cache;
  Map<int, Widget> cacheMap = Map();
  bool isChecked;
  
  @override
  initState() {
    super.initState();
    id = widget.id;
    lable = widget.lable;
    isChecked = widget.isChecked;
  }
  
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Container(
      height: 100,
      width: double.infinity,
      child: Column(
        children: [
          Checkbox(
            value: isChecked,
            onChanged: (bool value) {
                setState(() {
                    isChecked = value;
                });
            },
          ),
          Text('id=$id & lable=$lable'),
        ],
      )
     );
  }
}
```

**Now the expected behavior is:**
1. We have 3 items with 3 check-boxes and labels.
2. When I click the FAB button:
    a. The item in index number "2" should be marked as checked.
    b. A new item should be added at index number 3.

**But the actual output is:**
- The news item is added to the 3rd index but the item in the 2nd index is not checked because its build function is not called.

**Upon digging for some time I found that there are 2 ways to "check" the item at index 2.**
 - You have to also change the value of the Key, so in this example you have to change the id as it is used for the key.
 - Or, you have to remove an item above the 2nd index i.e "items.removeAt(0)" or "items.removeAt(1);" to force the items below it to re-render ;

Is this the intended behavior?
