### ISSUE TITLE
New, default Flutter Projects fail on build with NDK...did not have a source.properties file.

### ISSUE THREAD

**Issue by firephreek** [flutter/flutter#102831] opened 2022-04-29 17:29 UTC
## Steps to Reproduce
1. Android Studio: *File -> New -> New Flutter Project*
2. Accept Default Configuration:
    - *Dart SDK*: Default/Installed SDK (see Environment/Flutter Doctor details below) 
    -  _Project Type_: Application
    - _Android Language_: Kotlin
    - _iOS language_: Swift
    - _Platforms_: Android/iOS
3. Launch `main.dart` using the default 'debug' configuration
    - Targeting API 30 on an emulator with default configuration from the AVD
 
## Expected Results:
Should see the basic example 'Counter' app with counter display and button to trigger incrementing display.

## Actual Results:
The following error message is shown:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:stripDebugDebugSymbols'.
> NDK at C:\Users\...\ndk-bundle did not have a source.properties file
```

## Additional Notes
- Looking at `android\build.gradle`, the buildscript dependencies contains a reference to `classpath 'com.android.tools.build:gradle:4.1.0'` while `gradle\wrapper\gradle-wrapper.properties` has a property `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip`

- Project Structure has no default SDK set even though there are multiple available. Regardless of the selected SDK (tested with 28, 29. 30. 32), the same error message is returned.

- The docs at [https://developer.android.com/studio/releases/gradle-plugin](https://developer.android.com/studio/releases/gradle-plugin) contain instructions for updating the Gradle Plugin Version by going to *File -> Project Structure -> Project`, but there is no entry/field/box that suggests anything about Gradle. Only "Project Name", "Project SDK", "Project Language Level" and "Project compiler output"

- Without having changed, edited, updatedor otherwise altered the default project or code, the Project Structure dialog 'Problems' section shows the following issues: 
  - Module untitled6_android: invalid item 'Flutter for Android' in the dependencies list
  - Module untitled6_android: invalid item 'KotlinJavaRuntime' in the dependencies list
  - Library Flutter Plugins is not used [Fix]

### Flutter Doctor
- See attached [flutter_doctor.log](https://github.com/flutter/flutter/files/8592595/flutter_doctor.log)

### Flutter Run
- See attached [flutter_run.log](https://github.com/flutter/flutter/files/8592594/flutter_run.log)

### Flutter Analyze
```
Analyzing untitled6...
No issues found! (ran in 2.0s)
```

### Plugins
- Flutter 66.0.1
- Dart 211.7817

### Environment
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 36
Registry: external.system.auto.import.disabled=true, suggest.all.run.configurations.from.context=true, ide.instant.shutdown=false
Non-Bundled Plugins: co.anbora.labs.firebase-syntax-highlighting (2.7.1), com.bloc.intellij_generator_plugin (3.3.0), com.markskelton.one-dark-theme (5.5.2), com.samdark.intellij-visual-studio-code-dark-plus (2.5), com.vecheslav.darculaDarkerTheme (1.2.0), de.netnexus.camelcaseplugin (3.0.12), idea.plugin.protoeditor (2.3.1), com.jetbrains.upsource (2020.1.1990.11), Dart (211.7817), com.localizely.flutter-intl (1.17.2-2020.3), Jetbrains TeamCity Plugin (2022.4.108502), org.moe.community (1.4.10), org.jetbrains.kotlin (211-1.6.21-release-334-AS7442.40), io.flutter (66.0.1)

**Comment by abderrahmanebenhalima** [comment] 2022-05-01 01:32
same issue here, I thought it's only me
I don't know wheredid this issue comes from

**Comment by IndiaFF77** [comment] 2022-05-01 03:15
> ## Steps to Reproduce
> 1. Android Studio: _File -> New -> New Flutter Project_
> 2. Accept Default Configuration:
>    
>    * _Dart SDK_: Default/Installed SDK (see Environment/Flutter Doctor details below)
>    * _Project Type_: Application
>    * _Android Language_: Kotlin
>    * _iOS language_: Swift
>    * _Platforms_: Android/iOS
> 3. Launch `main.dart` using the default 'debug' configuration
>    
>    * Targeting API 30 on an emulator with default configuration from the AVD
> 
> ## Expected Results:
> Should see the basic example 'Counter' app with counter display and button to trigger incrementing display.
> 
> ## Actual Results:
> The following error message is shown:
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:stripDebugDebugSymbols'.
> > NDK at C:\Users\...\ndk-bundle did not have a source.properties file
> ```
> 
> ## Additional Notes
> * Looking at `android\build.gradle`, the buildscript dependencies contains a reference to `classpath 'com.android.tools.build:gradle:4.1.0'` while `gradle\wrapper\gradle-wrapper.properties` has a property `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip`
> * Project Structure has no default SDK set even though there are multiple available. Regardless of the selected SDK (tested with 28, 29. 30. 32), the same error message is returned.
> * The docs at https://developer.android.com/studio/releases/gradle-plugin contain instructions for updating the Gradle Plugin Version by going to *File -> Project Structure -> Project`, but there is no entry/field/box that suggests anything about Gradle. Only "Project Name", "Project SDK", "Project Language Level" and "Project compiler output"
> * Without having changed, edited, updatedor otherwise altered the default project or code, the Project Structure dialog 'Problems' section shows the following issues:
>   
>   * Module untitled6_android: invalid item 'Flutter for Android' in the dependencies list
>   * Module untitled6_android: invalid item 'KotlinJavaRuntime' in the dependencies list
>   * Library Flutter Plugins is not used [Fix]
> 
> ### Flutter Doctor
> * See attached [flutter_doctor.log](https://github.com/flutter/flutter/files/8592595/flutter_doctor.log)
> 
> ### Flutter Run
> * See attached [flutter_run.log](https://github.com/flutter/flutter/files/8592594/flutter_run.log)
> 
> ### Flutter Analyze
> ```
> Analyzing untitled6...
> No issues found! (ran in 2.0s)
> ```
> 
> ### Plugins
> * Flutter 66.0.1
> * Dart 211.7817
> 
> ### Environment
> Android Studio Bumblebee | 2021.1.1 Patch 2 Build #AI-211.7628.21.2111.8193401, built on February 17, 2022 Runtime version: 11.0.11+9-b60-7590822 amd64 VM: OpenJDK 64-Bit Server VM by Oracle Corporation Windows 10 10.0 GC: G1 Young Generation, G1 Old Generation Memory: 4096M Cores: 36 Registry: external.system.auto.import.disabled=true, suggest.all.run.configurations.from.context=true, ide.instant.shutdown=false Non-Bundled Plugins: co.anbora.labs.firebase-syntax-highlighting (2.7.1), com.bloc.intellij_generator_plugin (3.3.0), com.markskelton.one-dark-theme (5.5.2), com.samdark.intellij-visual-studio-code-dark-plus (2.5), com.vecheslav.darculaDarkerTheme (1.2.0), de.netnexus.camelcaseplugin (3.0.12), idea.plugin.protoeditor (2.3.1), com.jetbrains.upsource (2020.1.1990.11), Dart (211.7817), com.localizely.flutter-intl (1.17.2-2020.3), Jetbrains TeamCity Plugin (2022.4.108502), org.moe.community (1.4.10), org.jetbrains.kotlin (211-1.6.21-release-334-AS7442.40), io.flutter (66.0.1)

val fullScreenIntent = Intent(this, CallActivity::class.java)
val fullScreenPendingIntent = PendingIntent.getActivity(this, 0,
    fullScreenIntent, PendingIntent.FLAG_UPDATE_CURRENT)

val notificationBuilder =
        NotificationCompat.Builder(this, CHANNEL_ID)
    .setSmallIcon(R.drawable.notification_icon)
    .setContentTitle("Incoming call")
    .setContentText("(919) 555-1234")
    .setPriority(NotificationCompat.PRIORITY_HIGH)
    .setCategory(NotificationCompat.CATEGORY_CALL)

    // Use a full-screen intent only for the highest-priority alerts where you
    // have an associated activity that you would like to launch after the user
    // interacts with the notification. Also, if your app targets Android  #98298 
    // or higher, you need to request the USE_FULL_SCREEN_INTENT permission in
    // order for the platform to invoke this notification.
    .setFullScreenIntent(fullScreenPendingIntent, true)

val incomingCallNotification = notificationBuilder.build()

**Comment by maheshmnj** [comment] 2022-05-02 08:35
Hi @firephreek, Thanks for filing the issue. Your flutter run log doesn't seem to show the original error that you reported. However, this seems to be a known issue and is being tracked here https://github.com/flutter/flutter/issues/72639. Please follow up there for further updates.  Closing this issue as a duplicate of the above-linked issue. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-05-02 08:35 UTC
Labels: in triage

**Comment by sickofgooglesshit** [comment] 2022-05-07 16:51
Here's the rest of the log. I had piped the output of `flutter run -v` into a file but only stdout was captured and not stderr content. \#windowsThings.   Here's the rest of the log:

```
[+2145 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[   +1 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:stripDebugDebugSymbols'.
[        ] > NDK at C:\...\AppData\Local\Android\sdk\ndk-bundle did not have a source.properties file
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 16s
[   +2 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```
