### ISSUE TITLE
Flutter run broken on iOS devices

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10885] opened 2017-06-21 10:29 UTC
## Steps to Reproduce

The following steps work as expected:

```
flutter create test1
cd test1
flutter run -d i (a simulator)
```

The following steps don't:

```
flutter create test1
cd test1
flutter run -d M (an iPod physical device)
Select some signing key when prompted
```

=>

```
mit-macbookpro2:testapp11 mit$ ~/dev/github/flutter/bin/flutter run -d M
Launching lib/main.dart on Michael Thomsen’s iPod in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: EQHXZ8M8AV
Running Xcode build...                                9.9s
2017-06-21 12:23:47.638 ios-deploy[44334:9492205] [ !! ] Unable to locate DeviceSupport directory. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
Could not install build/ios/Release-iphoneos/Runner.app on 20f968aaf25ce0287216e515f31c36f8d7c25eb5.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Michael Thomsen’s iPod.
```

## Flutter Doctor

```
mit-macbookpro2:testapp12 mit$ ~/dev/github/flutter/bin/flutter doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-DK, channel master)
    • Flutter at /Users/mit/dev/github/flutter
    • Framework revision ceb814aa64 (5 hours ago), 2017-06-20 22:14:59 -0700
    • Engine revision fffe502d43
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/mit/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.3.old
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Michael Thomsen’s iPod • 20f968aaf25ce0287216e515f31c36f8d7c25eb5 • ios • iOS 10.3.2
    • iPhone 6               • 6617F753-8F58-4655-8F2C-3C07087296A4     • ios • iOS 10.3 (simulator)

```

**Comment by mit-mit** [comment] 2017-06-21 12:14
cc @cbracken I guess this is some kind of configuration issue, but I am not aware of making any changes to my setup.

**Comment by eseidelGoogle** [comment] 2017-06-21 14:00
Any luck with:
```
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace
```

FYI @xster

**Comment by mit-mit** [comment] 2017-06-21 14:04
It runs with no errors or warnings from Xcode. But it consistently fails from the terminal.

**Comment by cbracken** [comment] 2017-06-21 15:13
This seems like a dupe of #4326, which includes a workaround until ios-deploy is patched upstream. Please re-open if it seems like something different.

**Closed by cbracken** 2017-06-21 15:13 UTC
Labels: regression, ⌺‬ platform-ios

**Comment by mit-mit** [comment] 2017-06-22 11:56
Confirmed that the workaround from #4326 worked.

**Comment by ollydixon** [comment] 2020-07-07 09:37
This is still broken in 2020, version 17.0.5.

**Comment by eseidelGoogle** [comment] 2020-07-07 16:33
@ollydixon this is a very old bug which we believe is fixed.  If you are seeing flutter run broken for iOS, that's definitely unexpected.  We'd *love* a new issue so we can help find resolution.  Would you be willing to file one?  flutter.dev/support

**Comment by ollydixon** [comment] 2020-07-08 12:13
@eseidelGoogle https://github.com/flutter/flutter/issues/61093

**Comment by robwafle-scripd** [comment] 2020-10-04 14:37
I am experiencing this for the first time today, on both stable and dev branches:

Launching lib/main.dart on CM2 in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 98BR9YH3P3
Xcode build done.                                           40.1s
═══════════════════════════════════════════════════════════════════════════════════
Error launching app. Try launching from within Xcode via:
    open ios/Runner.xcworkspace

Your Xcode version may be too old for your iOS version.
═══════════════════════════════════════════════════════════════════════════════════
Could not run build/ios/iphoneos/Runner.app on 25c44d678e695bcd27b2b1c76d2aee3bc303a582.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on CM2.
Exited (sigterm)

flutter doctor --verbose
Downloading android-arm-profile/darwin-x64 tools...                 0.5s
Downloading android-arm-release/darwin-x64 tools...                 0.2s
Downloading android-arm64-profile/darwin-x64 tools...               0.2s
Downloading android-arm64-release/darwin-x64 tools...               0.2s
Downloading android-x64-profile/darwin-x64 tools...                 0.2s
Downloading android-x64-release/darwin-x64 tools...                 0.2s
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-US)
    • Flutter version 1.23.0-7.0.pre at /Users/rob/dev/flutter
    • Framework revision db6e2d8aa5 (9 days ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rob/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • CM2 (mobile)     • 25c44d678e695bcd27b2b1c76d2aee3bc303a582 • ios            • iOS 14.0.1
    • Web Server (web) • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 85.0.4183.121

Anyone else suddenly experiencing this?
