### ISSUE TITLE
Paste triggers permission dialog every time on iOS 16

### ISSUE THREAD

**Issue by AlexanderFarkas** [flutter/flutter#124503] opened 2023-04-10 10:02 UTC
[Issue 112515](https://github.com/flutter/flutter/issues/112515) - this issue is related.

Just wanted to know, if it's possible for Flutter to not trigger this permission dialog? E.g. render native "paste" option

Reproduce:
1. Copy any text
2. Click "Paste" on any TextField
-> You receive permission alert every time, even if you allowed

**Comment by danagbemava-nc** [comment] 2023-04-10 10:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/103163.

Kindly subscribe to the issue linked above for updates. 

PS: you might be able to use the https://pub.dev/packages/flutter_native_text_input to workaround this for now although it also has it's own issues.

Thank you

**Closed by danagbemava-nc** 2023-04-10 10:11 UTC
Labels: in triage
