### ISSUE TITLE
MacOS app - Window menu option disappears on closing app.

### ISSUE THREAD

**Issue by subhash279** [flutter/flutter#97091] opened 2022-01-23 11:26 UTC
## Steps to Reproduce

1. Run any macOS app using Flutter. The name of the App appears in the Window menu as expected.
2. Close the macOS app using the red icon on the top-left.(applicationShouldTerminateAfterLastWindowClosed is set to false so that the window only closes but the app is still running the background).
3. The App name disappears in the window menu. This should still appear as app is running in the background and this button should be available to bring the app to the foreground.

**Expected results:** 
![image](https://user-images.githubusercontent.com/23074764/150675918-eb7f64a3-9080-42b5-aae3-61038152738a.png)

**Actual results:** 
![Screenshot 2022-01-23 at 11 20 59](https://user-images.githubusercontent.com/23074764/150676174-e549a9ba-200c-4fbe-ad25-db11cab00044.png)

I even tried to moidy the MainMenu.xib file. But I couldn't actually find the appName menu item there. It looks like the app name in Window menu is actually being set dynamically(I couldn't figure out where). This option should stay even when the app is closed.

AppDelegate.swift file 
`@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    return false
  }

  override func applicationShouldHandleReopen(_ sender: NSApplication, hasVisibleWindows flag: Bool) -> Bool {
    if !flag {
        for window: AnyObject in sender.windows {
            window.makeKeyAndOrderFront(self)
        }
    }
    return true
  }
}`

<details>
<summary>
</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment] 2022-01-23 13:24
> 1. The name of the App appears in the Window menu as expected.

The title of the *window* appears in the window menu, because that's a list of windows. By default a Flutter template-created app uses that application name as the windows title.



> 2\. Close the macOS app using the red icon on the top-left.(applicationShouldTerminateAfterLastWindowClosed is set to false so that the window only closes

You are not closing the app in this scenario, only the window.

> but the app is still running the background).

The app is running in the foreground at this point, just with no windows. Otherwise the application's menubar wouldn't be showing.

> 3\. The App name disappears in the window menu.

The entry for the window whose title happened to be the application's name goes away because you closed the window.

> 3\. This should still appear as app is running in the background and this button should be available to bring the app to the foreground.

This is not at all how the window menu in macOS works, so I'm not sure why you think this is what should happen.

What you are describing isn't even possible, because if the app is in the background you can't access its menu at all. The menubar always correspond to the foreground application.

> It looks like the app name in Window menu is actually being set dynamically(I couldn't figure out where).

It's managed by macOS itself.

It sounds like what you want is for the window close box to hide the window instead of closing it. That's completely non-standard behavior; if you want to modify your runner to do that you certainly could, but it's not what you've described doing, and it certainly isn't going to be the default behavior of the template.

**Closed by stuartmorgan** 2022-01-23 13:24 UTC

**Comment by subhash279** [comment] 2022-01-23 20:03
@stuartmorgan I don't think it is non-standard behaviour. Apple Podcasts itself and even Spotify do the same thing. 
You can try either of these apps. If you close the red button on top-left, the menu bar still appears and the app name shows up in the Window menu. Clicking on the appName opens the window again.

![image](https://user-images.githubusercontent.com/23074764/150695897-9d63b414-86dc-4808-a0cc-c1d1687fd96c.png)

![image](https://user-images.githubusercontent.com/23074764/150695908-cb79b0ae-112a-45e1-8d43-278fbd193448.png)

**Comment by stuartmorgan** [comment] 2022-01-24 03:04
> @stuartmorgan I don't think it is non-standard behaviour. Apple Podcasts itself and even Spotify do the same thing.

The existence of apps that do something isn't inconsistent with something being non-standard (and in fact it's common for some of Apple's own applications to have one-off non-standard behaviors, styles, etc.).
- It's not how most applications work.
- It's not how the default application created by Xcode's template works.
- There is no automatic functionality for this built into the Window menu, unlike almost everything else in that menu (such as the window list).
  - There is not even an API to enable this behavior; it must be built by any developer who wants it using the core `NSMenu` APIs. (Notice that in your screenshot the keyboard shortcuts are *completely* different across the two applications, which is not something you would see with standard menu items.)
- Apple's Human Interface Guidelines section describing the standard elements of the Window menu makes absolutely no mention of this.

You are welcome to implement it in your own application, but it is unambiguously non-standard.

**Comment by subhash279** [comment] 2022-01-24 09:11
@stuartmorgan my app was rejected because it doesn't follow the "Apple's Human Interface Guidelines". That's why I opened this issue.

Here's the full message:
"
Design Preamble


The user interface of your app is not consistent with the macOS Human Interface Guidelines.

Specifically, we found that when the user closes the main application window there is no menu item to re-open it.

Next Steps

It would be appropriate for the app to implement a Window menu that lists the main window so it can be reopened, or provide similar functionality in another menu item. macOS Human Interface Guidelines state that "The menu bar [a]lways contains [a] Window menu".

Alternatively, if the application is a single-window app, it might be appropriate to save data and quit the app when the main window is closed.

For information on managing windows in macOS, please review the following sections in Apple Human Interface Guidelines:

* The Menu Bar and Its Menus
* The Window Menu
* The File Menu
* Clicking in the Dock
* Window Behavior

Please evaluate how you can implement the appropriate changes, and resubmit your app for review.
"

If this isn't something we can do in Flutter directly, can you pls point me in the direction of implementing it in native Swift? Thanks.

**Comment by stuartmorgan** [comment] 2022-01-24 13:26
> macOS Human Interface Guidelines state that "The menu bar [a]lways contains [a] Window menu".

This is very bizarre thing for them to quote; your menu bar does contain a Window menu. It's the thing that's open in your screenshot. That text has nothing to do with the issue they have raised.

But certainly leaving the app open without any way to open a window doesn't make sense. (The standard way to do this is the menu item that makes new windows (e.g., File > New Window) because typically only multi-window apps stay open.)

> Alternatively, if the application is a single-window app, it might be appropriate to save data and quit the app when the main window is closed.

This is of course the standard behavior implemented by the template app.

The issue is not with the standard Flutter template behavior, but with the changes you made.

> If this isn't something we can do in Flutter directly

Flutter does not currently provide window management or menu management capabilities.

> can you pls point me in the direction of implementing it in native Swift?

I don't have beginning macOS references to point you to offhand. I'm sure many introductions to windows and menus for macOS exist though; there's nothing Flutter-specific about it.
