### ISSUE TITLE
SocketException not caught on iOS in beta/dev (works in stable)

### ISSUE THREAD

**Issue by peterlauri** [flutter/flutter#66488] opened 2020-09-23 21:00 UTC
## Summary

The real scenario that when we try to make an http call and the call fails due to not having internet or similar, a SocketException is thrown. The below code makes a call to a domain that does not exist, which results in a SocketException as well. With beta and dev channel the exception is never caught, while stable works as expected.

## Steps to Reproduce

This does **NOT** reproduce in stable channel (1.20.4). This does **NOT** reproduce deploying to Android devices.

Reproduced using combinations of beta/dev and iOS 13.5 and 14.0 devices / simulators.

1. Use beta (1.22.0-12.1.pre) or dev (1.23.0-4.0.pre)
2. Start iOS simulator with iOS 14 and iPhone 11 pro (or iOS 13.5)
3. Create a new project, and add **http: 0.12.2** as dependency
4. Replace main.dart with this code:

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _loading = false;
  int _statusCode;
  bool _catch;
  bool _finally;

  void _incrementCounter() async {
    setState(() {
      _loading = true;
      _statusCode = null;
      _catch = null;
      _finally = null;
    });
    try {
      final response = await http.get('https://some-domain-that-does.not.exist.com');
      setState(() {
        _statusCode = response.statusCode;
        _catch = false;
      });
    } catch (err) {
      setState(() {
        _catch = true;
      });
    } finally {
      setState(() {
        _loading = false;
        _finally = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Press the button to make network call'),
            Text('_loading: $_loading'),
            Text('Status code: ${_statusCode ?? '-'}'),
            Text('Catch: ${_catch ?? '-'}'),
            Text('Finally: ${_finally ?? '-'}'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.cloud_download),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
5. Start the application on the simulator (or real device).
6. Click the fab in the bottom right

**Expected results**: we should see **_catch: true** shown

**Actual results**: we see **_catch: -**, that implies that the catch block was never reached. You also see the following exception in the console:

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: SocketException: Failed host lookup: 'some-domain-that-does.not.exist.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:502:9)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _CustomZone.bindCallbackGuarded.<anony<…>
```

<details>
  <summary>Logs</summary>

```
VERBOSE LOG ATTACHED AS FILE.
```

[socket-exception-handling-verbose-log-output.txt](https://github.com/flutter/flutter/files/5271888/socket-exception-handling-verbose-log-output.txt)

```
➜  socketexception git:(master) ✗ flutter analyze
Analyzing socketexception...
No issues found! (ran in 1.9s)
```

```
➜  socketexception git:(master) ✗ flutter doctor -v
Downloading android-arm-profile/darwin-x64 tools...                 1.0s
Downloading android-arm-release/darwin-x64 tools...                 0.5s
Downloading android-arm64-profile/darwin-x64 tools...               0.5s
Downloading android-arm64-release/darwin-x64 tools...               0.4s
Downloading android-x64-profile/darwin-x64 tools...                 0.3s
Downloading android-x64-release/darwin-x64 tools...                 0.4s
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-12.1.pre at /Users/plauri/apps/flutter
    • Framework revision 8b3760638a (8 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/plauri/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • iPhone 11 Pro (mobile) • 66875199-47A5-4314-9488-A77EB481553E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-09-24 07:54
Hi @peterlauri 
I cannot reproduce this issue on the latest `master` channel.
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _loading = false;
  int _statusCode;
  bool _catch;
  bool _finally;

  void _incrementCounter() async {
    setState(() {
      _loading = true;
      _statusCode = null;
      _catch = null;
      _finally = null;
    });
    try {
      final response =
          await http.get('https://some-domain-that-does.not.exist.com');
      setState(() {
        _statusCode = response.statusCode;
        _catch = false;
      });
    } catch (err) {
      setState(() {
        _catch = true;
      });
    } finally {
      setState(() {
        _loading = false;
        _finally = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Press the button to make network call'),
            Text('_loading: $_loading'),
            Text('Status code: ${_statusCode ?? '-'}'),
            Text('Catch: ${_catch ?? '-'}'),
            Text('Finally: ${_finally ?? '-'}'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.cloud_download),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.340 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 1fef5912cf (3 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK
    version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (4 available)            
    • iPhone 11 (mobile) • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • Mac OS X
      10.15.6 19G2021 x86_64
    • Web Server (web)   • web-server                           • web-javascript • Flutter
      Tools
    • Chrome (web)       • chrome                               • web-javascript • Google
      Chrome 85.0.4183.102

• No issues found!

```

</details>

**Comment by peterlauri** [comment] 2020-09-24 15:08
> Hi @peterlauri
> I cannot reproduce this issue on the latest `master` channel.
> Can you please upgrade to the latest `master` and try again
> `flutter channel master`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> code sample
> flutter doctor -v

I can confirm your finding, that in master channel it works as expected. 

We have to stick to stable version for now, but that breaks our Web support :( But there is a nice workaround to use stable channel with web, so we are fine for now...

**Comment by TahaTesser** [comment] 2020-09-25 05:25
Hi @peterlauri 
Thank for confirming, since this is no longer reproducible on the latest `master` 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-25 05:25 UTC
Labels: in triage

**Comment by peterlauri** [comment] 2020-09-25 07:02
Yes it is ok to close this. However, how to actually get feedback when the
fix is in beta? Is there any referenced commit / PR that one can follow to
understand when it is in beta?

**Comment by orestesgaolin** [comment] 2020-09-25 09:18
The easiest way is to track [beta branch commits](https://github.com/flutter/flutter/commits/beta) but without knowledge which commit fixed that it's hard to tell :/

**Comment by jmagman** [comment] 2020-09-30 17:55
@peterlauri Can you try on latest beta `1.22.0-12.3.pre`?  We think it may be fixed there.

**Comment by peterlauri** [comment] 2020-10-01 04:29
> @peterlauri Can you try on latest beta `1.22.0-12.3.pre`? We think it may be fixed there.

@jmagman confirmed that the test case works on 1.22.0-12.3.pre. Thanks 😍
