### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by CodeLawd** [flutter/flutter#89096] opened 2021-08-28 08:28 UTC
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      ForwardingFile.openSync (package:file/src/forwarding/forwarding_file.dart:71:16)
#3      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:308:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
#5      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:307:5)
#6      FlutterWebSdk.updateInner (package:flutter_tools/src/flutter_cache.dart:201:16)
<asynchronous suspension>
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:677:5)
<asynchronous suspension>
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:546:9)
<asynchronous suspension>
#9      PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:169:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
```
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_NG.UTF-8)
    • Flutter version 2.2.3 at /home/codelawd/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/codelawd/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/codelawd/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/codelawd/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment] 2021-08-30 07:25
Closing this as duplicate of https://github.com/flutter/flutter/issues/68958

**Closed by darshankawar** 2021-08-30 07:25 UTC
Labels: in triage
