### ISSUE TITLE
TabBarView nested problem

### ISSUE THREAD

**Issue by YWD** [flutter/flutter#29420] opened 2019-03-15 09:10 UTC
tarbarview doesn't keepalive. please run the code below.

I switch in 'first'/'second' tab or 'second'/'third' tab, second tab keeps alive, but if I switch 'first'/'third' tab, the second page always 'init'(I choose in tab c, it shows tab a), the initState method invoked.

```dart
import 'package:flutter/material.dart';

void main() {
runApp(MyApp());
}

class MyApp extends StatefulWidget {
@override
_MyAppState createState() => _MyAppState();
}

class _MyAppState extends State with SingleTickerProviderStateMixin {

var tabController;
@override
void initState() {
super.initState();

tabController = TabController(length: 3,vsync: this);
}

@override
Widget build(BuildContext context) {
return MaterialApp(
home: Scaffold(
appBar: CustomAppBar(),
body: TabBarView(children: [
First(),
Second(),
Third(),
],
controller: tabController,physics: NeverScrollableScrollPhysics()),
bottomNavigationBar: TabBar(tabs: [
Text('first',style: TextStyle(fontSize: 25,color: Colors.black),),
Text('second',style: TextStyle(fontSize: 25,color: Colors.black),),
Text('third',style: TextStyle(fontSize: 25,color: Colors.black),),
],
controller: tabController,),
),
);
}
}

class First extends StatefulWidget {
@override
FirstState createState() => FirstState();
}

class FirstState extends State {

@override
void initState() {
super.initState();
print('first init');
}

@override
void dispose() {
print('first dispose');
super.dispose();
}

@override
Widget build(BuildContext context) {
return Container();
}
}

class Third extends StatefulWidget {
@override
_ThirdState createState() => _ThirdState();
}

class _ThirdState extends State {

@override
void initState() {
super.initState();
print('third init');
}

@override
void dispose() {
print('third dispose');
super.dispose();
}

@override
Widget build(BuildContext context) {
return Container();
}
}

class Second extends StatefulWidget {
@override
_SecondState createState() => _SecondState();
}

class _SecondState extends State with SingleTickerProviderStateMixin, AutomaticKeepAliveClientMixin {

@override
bool get wantKeepAlive => true;

var innerTabController;
GlobalKey<_SecondState> key = GlobalKey<_SecondState>();
@override
void initState() {
super.initState();
print('second initState');
innerTabController = TabController(length: 3,vsync: this,);
}

@override
void dispose() {
print('second dispose');
super.dispose();
}

@override
Widget build(BuildContext context) {
return Scaffold(
appBar: CustomAppBar(),
body: TabBarView(children: [
Container(color: Colors.red,),
Container(color: Colors.yellow,),
Container(color: Colors.blue,),
],
controller: innerTabController,physics: NeverScrollableScrollPhysics(),key: key,),

  bottomNavigationBar: TabBar(tabs: [
    Text('A',style: TextStyle(fontSize: 25,color: Colors.black),),
    Text('B',style: TextStyle(fontSize: 25,color: Colors.black),),
    Text('C',style: TextStyle(fontSize: 25,color: Colors.black),),
  ],
    controller: innerTabController,),
);
}
}

class CustomAppBar extends StatefulWidget implements PreferredSizeWidget {
@override
_CustomAppBarState createState() => _CustomAppBarState();

@override
Size get preferredSize => Size.fromHeight(kToolbarHeight);
}

class _CustomAppBarState extends State {
@override
Widget build(BuildContext context) {
return Container(
color: Colors.yellow,
child: SizedBox(
height: 0,
),
);
}
}

 ```

**Comment by mliitfall** [comment] 2019-05-01 15:29
Is this fixed? it's seem kind a bug when switch tab from 1 to 3 in nestedscrollview with tabbarview, then the 2nd page will initialize again and not keep alive.

**Comment by VladyslavBondarenko** [comment] 2020-04-06 13:58
Hi @YWD 
Does the issue persist?
I can't reproduce it with `dev v1.18.0`

**Comment by iapicca** [comment] 2020-05-29 13:54
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-05-29 13:54 UTC
Labels: f: material design, f: scrolling, framework, waiting for customer response
