### ISSUE TITLE
Backdrop filter is inconsistent on software rendering

### ISSUE THREAD

**Issue by maxlapides** [flutter/flutter#24946] opened 2018-12-04 02:10 UTC
If you create an instance of `CupertinoNavigationBar` and view it on an iPhone that has a home button (i.e. iPhone 8), you can see that the blur isn't being applied consistently. It looks like the top is more blurred than the bottom.

See how the words "Test Test Test" are not readable in this screenshot:

<img width="398" alt="screen shot 2018-12-03 at 6 09 19 pm" src="https://user-images.githubusercontent.com/1874682/49413986-a7277900-f726-11e8-8211-c3c61ec9e2ef.png">

But if I scroll down a little further, you can read them clearly:

<img width="398" alt="screen shot 2018-12-03 at 6 08 04 pm" src="https://user-images.githubusercontent.com/1874682/49413963-8b23d780-f726-11e8-84c1-638afe0215f9.png">

**Comment by maxlapides** [comment] 2018-12-04 04:58
The same issue occurs with `CupertinoTabBar`. The common pattern looks like this:

```
class Blurred extends StatelessWidget {
  const Blurred({@required this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return ClipRect(
      child: BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
        child: child,
      ),
    );
  }
}
```

The issue is that using this `ImageFilter` at the edge of the screen seems to affect the blur.

**Comment by maxlapides** [comment] 2018-12-04 06:51
```
[✓] Flutter (Channel beta, v0.11.13, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.11.13 at /Users/maxlapides/flutter
    • Framework revision 58c8489fcd (4 days ago), 2018-11-29 19:20:18 -0500
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/maxlapides/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/maxlapides/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • iPhone 8  • DA693BD1-5236-4840-AAA6-C63BB1F4A445 • ios • iOS 12.1 (simulator)
    • iPhone XS • 9CFC4B23-BE03-4DC9-B1CD-5E1226F5A183 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by wouterhardeman** [comment] 2018-12-04 16:41
Have you tried to use the backgroundColor property in the CupertinoTabBar?

> If the given backgroundColor's opacity is not 1.0 (which is the case by default), it will produce a blurring effect to the content behind it.

(source: [https://docs.flutter.io/flutter/cupertino/CupertinoTabBar-class.html](https://docs.flutter.io/flutter/cupertino/CupertinoTabBar-class.html))

This is probably still an issue though.

**Comment by maxlapides** [comment] 2018-12-04 18:01
@wouterhardeman yes, this is an issue regardless of backgroundColor (assuming it’s partially transparent).

**Comment by cbracken** [comment] 2018-12-04 22:45
/cc @liyuqian 

Reported upstream to skia: https://bugs.chromium.org/p/skia/issues/detail?id=8591

**Comment by liyuqian** [comment] 2018-12-04 22:48
Right, this is a Skia software backend issue. Besides iOS simulators, I can also reproduce it in Android devices with "--enable-software-rendering". I guess that the bug would be gone in real iOS devices since we use Skia's GPU backends there.

**Comment by stevenspiel** [comment] 2019-02-17 02:40
+1 on this. Here is more information:

https://stackoverflow.com/questions/54657729/flutter-blur-image-edges-are-unaffected-ios-only/54718685

**Comment by ShannonHeylmun** [comment] 2019-02-19 15:07
+1 on this.  Running into the same issue as @stevenspiel.

**Comment by vanlooverenkoen** [comment] 2020-02-10 15:40
Any update on this?

**Comment by liyuqian** [comment] 2020-02-11 18:55
@vanelizarov : this bug is currently tracked by Skia in https://bugs.chromium.org/p/skia/issues/detail?id=8591 . Please see the latest update there.

**Comment by TahaTesser** [comment] 2020-09-08 15:28
Hi @maxlapides 
I have XR, don't have a device with the home button. 

Are you still experiencing this issue? Can you please confirm on latest flutter version?

**Comment by vanlooverenkoen** [comment] 2020-09-08 15:29
@TahaTesser you mean a xr simulator right? This is only a simulator bug

**Comment by TahaTesser** [comment] 2020-09-08 15:32
Oops, thanks @vanlooverenkoen 
I will reproduce it soon

**Comment by maxlapides** [comment] 2020-09-08 16:20
Correct, this is a simulator bug that is still reproducible.

**Comment by TahaTesser** [comment] 2020-09-09 12:35
it's very hard to notice the issue, I tried several times based on the description with `CupertinoNavigationBar` and `CupertinoTabBar` 

To better address the issue, Can you please provide a complete reproducible minimal code sample. Something like https://github.com/flutter/flutter/issues/16614#issuecomment-680897806
Thank you

**Comment by markusaksli-nc** [comment] 2020-10-07 08:17
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by passsy** [comment] 2020-10-07 08:36
All information is here. The bug is in [skia](https://bugs.chromium.org/p/skia/issues/detail?id=8591). The issue there also includes a minimal reproducible code [sample](https://fiddle.skia.org/c/44ac5482fd7936746a4f430f1e0df61d).

I suggest leaving this issue open as a tracking issue as it is not resolved.

**Comment by markusaksli-nc** [comment] 2020-10-07 08:40
My bad, closed for timeout but it seems like it was irrelevant.

**Comment by kkoken** [comment] 2021-09-07 13:39
Still cannot apply blur.

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-TR)
    • Flutter version 2.2.3 at /Users/kaantahakoken/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kaantahakoken/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/kaantahakoken/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008030-001439DE0A87802E • ios            • iOS 14.5
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 93.0.4577.63

• No issues found!

```

**Comment by Lampadina17** [comment] 2023-09-12 17:47
in 2023 this issue still exist

**Comment by cyberpwnn** [comment] 2024-08-26 21:53
Any updates on this?

**Comment by jonahwilliams** [comment] 2024-10-08 18:42
Software rendering support is being removed from iOS simulators. Closing as obsolete.

**Closed by jonahwilliams** 2024-10-08 18:42 UTC
Labels: framework, engine, dependency: skia, customer: crowd, c: rendering, P2, team-engine, triaged-engine
