### ISSUE TITLE
macOS desktop title customization

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#64716] opened 2020-08-27 13:20 UTC
is there a way to rename the title name rather than change the whole project name?

![image](https://user-images.githubusercontent.com/21303438/91447348-266dc080-e8ab-11ea-9869-749dbc3c568e.png)

**Comment by sidrao2006** [comment] 2020-08-27 13:26
Hi @jinfagang , have you tried changing the `title` property of the `MaterialApp`

**Comment by stuartmorgan** [comment] 2020-08-27 17:10
You can change `PRODUCT_NAME` in AppInfo.xconfig of you want to change the application band everywhere, including the default window title. This will be documented once macOS is discussed on the main docs page about releasing rather than just the one desktop page.

(If you want to change just the window title, dynamically, that would be https://github.com/flutter/flutter/issues/30712)

**Comment by jinfagang** [comment] 2020-08-28 08:46
@stuartmorgan Thanks for your answer, change PRODUCT_NAME seems what I want. But as for your option for change title only does there any snippet / API to call to change it? The dicussion you guys talk there I can't still know where to edit

**Comment by gspencergoog** [comment] 2020-10-14 22:56
This is a duplicate of #30712

**Closed by gspencergoog** 2020-10-14 22:56 UTC
Labels: a: desktop, documentation, passed first triage, platform-mac
