### ISSUE TITLE
[in_app_purchase]introductoryPriceAmountMicros cause error: type 'int' is not a subtype of type 'String?' in type cast

### ISSUE THREAD

**Issue by y0unghe** [flutter/flutter#90565] opened 2021-09-23 02:10 UTC
## Steps to Reproduce

1. call await _inAppPurchase.queryProductDetails(_productIds);

**Expected results:** 
Should return a ProductDetailsResponse object
**Actual results:** 
json to dart cause this error: introductoryPriceAmountMicros : type 'int' is not a subtype of type 'String?' in type cast

<details>
  <summary>Logs</summary>

```
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)
    ! Error: yong’s iPhone 11 is not connected. Xcode will continue when yong’s iPhone 11 is connected. (code -13)

• No issues found!
```

```
> flutter analyze
Analyzing chatfun...
No issues found! (ran in 1.8s)
```

```
> flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/yonghe/Downloads/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/yonghe/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/yonghe/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • SM N9600 (mobile)         • 27ecb22c69217ece          • android-arm64  • Android 10 (API 29)
    • yong’s iPhone 11 (mobile) • 00008030-000424491103802E • ios            • iOS 14.6
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2021-09-23 07:07
@y0unghe 
This is a duplicate of 
https://github.com/flutter/flutter/issues/90509.

Please see [this](https://github.com/flutter/flutter/issues/90509#issuecomment-924748571) issue comment for further reference.
Closing from here.

**Closed by darshankawar** 2021-09-23 07:07 UTC
Labels: in triage
