### ISSUE TITLE
Flutter Web: Refreshing browser resets navigation stack and local variables

### ISSUE THREAD

**Issue by huffSamuel** [flutter/flutter#59277] opened 2020-06-11 18:15 UTC
## Steps to Reproduce

1. Run `git clone https://github.com/huffSamuel/flutter_browser_navigation.git`
2. Run the application in Chrome and follow on-screen instructions.

**Expected results:** 
Refreshing the browser refreshes the current page. Navigator stack and local variables are not cleared.

**Actual results:** 
Current page refreshes but all local properties are null. Navigator stack is cleared so pressing the back arrow results in odd behavior.

<details>
  <summary>Logs</summary>

```
[  +13 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +90 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f994b769743368b36b9c03fb359f62230b60ab92
[        ] executing: [C:\flutter/] git tag --contains HEAD
[ +374 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.19.0-4.1.pre
[  +11 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +49 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +103 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +67 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] executing: C:\Users\xsand\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +43 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +211 ms] Generating C:\Users\xsand\src\browser_refresh\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +96 ms] This application is not configured to build on the web.
[        ] To add web support to a project, run `flutter create .`.
[   +1 ms] Launching lib\main.dart on Chrome in debug mode...
[  +65 ms] Updating assets
[  +95 ms] Syncing files to device Chrome...
[  +46 ms] Generating C:\Users\xsand\src\browser_refresh\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +59 ms] <- reset
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev --old_gen_heap_size=2000 C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc
--debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\xsand\AppData\Local\Temp\flutter_tools.4c1f4105\flutter_tool.66061fbb\app.dill --libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\xsand\AppData\Local\Temp\flutter_tools.4c1f4105\flutter_tools.8b774b50 --filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill --platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +12 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+12148 ms] Syncing files to device Chrome... (completed in 12,264ms, longer than expected)
[   +1 ms] Synced 22.2MB.
[        ] <- accept     
[ +168 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:64332/devtools/browser/59681b2b-cb9f-48a9-b3b3-6bbda5c37881
[+5009 ms] Debug service listening on ws://127.0.0.1:64367/KYznAAIYw2A=

[ +537 ms] Debug service listening on ws://127.0.0.1:64367/KYznAAIYw2A=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
```

```
Analyzing browser_refresh...
No issues found! (ran in 1.9s)
```

```
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.19.0-4.1.pre at C:\flutter
    • Framework revision f994b76974 (2 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\xsand\AppData\Local\Android\Sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\xsand\AppData\Local\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\xsand\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2020-06-12 10:40
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision d9653445f4 (3 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[✓] Connected device (4 available)            
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.19.0-4.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision f994b76974 (3 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[✓] Connected device (3 available)            
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
``` 

</details>

**Comment by mdebbar** [comment] 2020-06-22 20:46
When you refresh the page, the entire app is destroyed and launched again. This is how the browser works, nothing specific to Flutter here. So the values of local variables are expected to disappear.

The way navigation works today is by keeping the navigation stack in memory. This means the stack is destroyed on page refresh, and the history is lost.

There are a few projects coming along that will help with these issues:

1. **[Navigator 2.0](https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit)**: We are designing the Navigator/Router changes in the framework in a way that gives us better history on the web. cc @chunhtai 
1. **[State Restoration](https://docs.google.com/document/d/1KIiq5CdqnSXxQXbZIDy2Ukc-JHFyLak1JR8e2cm3eO4/edit)**: This will give app developers the possibility to store state and recover it after a page refresh (or after the app is killed in the background on mobile). cc @goderbauer

**Comment by diegolaballos** [comment] 2020-09-16 21:01
Any updates on this? There seems to be, at least a partial implementation for the Navigator 2.0 in the latest release but I'm not sure if everything needed to reset the navigation stack is there.

**Comment by egorikem** [comment] 2020-10-02 08:38
Any update on this? I do believe it is quite strange that there still is no solution to this obvious problem

**Comment by chunhtai** [comment] 2020-10-02 16:16
Do you still see the issue if you use Router?

**Comment by atereshkov** [comment] 2020-11-13 12:36
It's unfortunately refreshing the entire app, not only navigation stack

**Comment by phamnhuvu-dev** [comment] 2020-12-28 10:54
I think this problem by this issue https://bugs.chromium.org/p/chromium/issues/detail?id=1098388.

**Comment by rlee1990** [comment] 2021-01-14 17:19
Using navigator 2.0 still does not resolve this issue.

**Comment by michaeldwu** [comment] 2021-01-31 22:49
I'm not sure if this is entirely useful, but here's a stackoverflow suggestion from the dart:html package that detects when the page is being refreshed or closed (tested on my end and it works). My current working theory is that if I can detect when the page is being refreshed, I can set the local properties to previous values. Haven't completely figured it out yet, just thought I'd drop this if it's useful for anyone else.

https://stackoverflow.com/questions/62237262/flutter-web-detect-browser-tab-close-or-refresh

**Comment by michaeldwu** [comment] 2021-01-31 22:57
Followup, I think I've found a semi-promising but incomplete solution to the browser back arrow creating weird results issue after refreshing leads to the Navigator stack getting cleared.

Essentially I set up the `html.window.onBeforeUnload.listen((event) async {...}` listener inside my build function to detect when the browser is refreshed, and then push the same navigation route inside like this:

`html.window.onBeforeUnload.listen((event) async {
      Navigator.pushNamed(context, 'charities');
    });`

(The existing page that's being refreshed has a route name of '/charities').

What this does is it stacks a new navigation stack and disables the back button from being pressed so the funky browser back arrow action can't happen. I know it's not perfect but I think it's somewhat of a start. Please do lmk if anyone comes up with a better solution.

**Comment by Wissperwind** [comment] 2021-04-27 09:37
How can I preserve my token?
I use fluro router. And if the user presses refresh, my url is still there, but my session token in my variable is gone. So I redirect to login. But the user does not expect that on refresh.
I know how to execute code before unload, but what to execute to save my token?

**Comment by LiangHuangBC** [comment] 2021-06-21 15:25
Any update?  For my app, when browser's refresh button clicked, it should stay at same page, but when close button clicked, next time when reopen it, it should go to sign in page.  html.window.onBeforeUnload.listen can not work on this case.

**Comment by amitsingh6391** [comment] 2021-07-10 13:09
@LiangHuangBC could you share your code ?

**Comment by omatt** [comment] 2021-09-11 19:31
Flutter treats page refresh on web as an app restart. What I did as a workaround is I keep track of my current page in SharedPreferences. On page refresh, app checks if there's a page stored in SharedPreferences. If yes, it then the stored page was pushed. Otherwise, the default page will be displayed. Keep tabs on the current page by calling `setCurrentPage(currentPage);` during navigation.

```dart
@override
void initState(){
    super.initState();
    ...
    getCurrentPage().then((currentPageState) {
       _navigatorKey.currentState!.pushReplacementNamed(currentPageState);
    }
}

/// Fetch stored page. Display default page if null.
Future<String> getCurrentPage() async {
    var pref = await SharedPreferences.getInstance();
    return pref.getString(SharedPrefKey.currentPage) ?? NavigatorHelper.home;
}

/// Store current [page] to restore into during page refresh on web
Future<void> setCurrentPage(String page) async {
    var pref = await SharedPreferences.getInstance();
    pref.setString(SharedPrefKey.currentPage, page);
}
```

If named routes was used, the Navigation Stack for the previous named routes should persist on page refresh.

`root_domain/#/` -> `root_domain/#/page` (page refresh) -> Going back to `root_domain/#/` is possible

**Comment by ckp78** [comment] 2021-09-16 14:06
Any updates? As far as I am aware (please correct me if I'm wrong), there is nothing in the Navigator 2.0 API which allows developers to solve this problem, which seems quite a major one.

**Comment by Vaibhavsaharan** [comment] 2021-11-26 06:59
Waiting for Navigator 3.0 to solve this  🐞.

**Comment by RitvikSardana** [comment] 2022-08-10 07:21
Was anyone able to solve this? 
I am facing the same issue

**Comment by CoderWeiLee** [comment] 2022-08-26 09:04
same issue + 1

**Comment by hatemragab** [comment] 2022-09-17 22:06
Any updates?

**Comment by dengzq** [comment] 2022-09-19 06:55
Same issue. I think this should be the top issue for flutter web cause it's really a bad experience for h5 users.

**Comment by armaniv11** [comment] 2022-09-26 16:09
Same Issue + 1

**Comment by kleber-rr** [comment] 2022-09-29 16:05
Same issue :(

**Comment by miguelchiarello** [comment] 2022-10-07 21:47
Same issue here guys.

**Comment by adhnan-e** [comment] 2022-11-11 04:36
Same Issue + 1

**Comment by chunhtai** [comment] 2022-11-11 16:47
Can be solve by https://github.com/flutter/flutter/issues/65777#issuecomment-1306328740

**Comment by Zeeshan0201** [comment] 2022-12-13 13:35
Same Issue + 1

**Comment by altafkhan8719** [comment] 2022-12-20 07:45
same issue, any update?

**Comment by NkITaa** [comment] 2022-12-25 13:21
Same Issue + 1

**Comment by iamtechmanish** [comment] 2022-12-25 18:34
any update ?

**Comment by LimaCliqxer** [comment] 2022-12-30 20:56
any update?

**Comment by prasant10050** [comment] 2023-01-02 13:34
Facing same issue, any update?

**Comment by stashtechnologies** [comment] 2023-01-10 05:46
Same Issue...

**Comment by pranil-iottive** [comment] 2023-01-10 13:35
any update ?

**Comment by VictorWork0209** [comment] 2023-02-14 01:26
any update?

**Comment by Navaf-N** [comment] 2023-02-14 10:12
any update?

**Comment by elio1fiore** [comment] 2023-02-17 21:13
+ 1. Any update ?

**Comment by elio1fiore** [comment] 2023-02-17 21:14
any update? +1

**Comment by mdebbar** [comment] 2023-02-17 21:23
Folks, this is expected behavior on the web. When you refresh the page, the app starts from scratch with all state cleared.

Flutter has the concept of state restoration which can help here, but it's not implemented for the web (yet). Please follow along in the corresponding issue (and add your thumbs ups there).

State restoration for web: https://github.com/flutter/flutter/issues/65777

I'm closing this issue because there's no extra value to be provided here.

**Closed by mdebbar** 2023-02-17 21:23 UTC
Labels: framework, f: routes, platform-web, has reproducible steps, found in release: 1.19, P5, found in release: 1.20
