### ISSUE TITLE
[tool_crash] FileSystemException: writeFrom failed, OS Error: There is not enough space on the disk., errno = 112

### ISSUE THREAD

**Issue by BadmusQudusAyomide** [flutter/flutter#154609] opened 2024-09-04 09:54 UTC
## Command
```
flutter build apk --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: writeFrom failed, OS Error: There is not enough space on the disk.
, errno = 112
```
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:905:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:646:14)
#2      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#3      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#4      LogHandler.save (package:unified_analytics/src/log_handler.dart:296:15)
#5      AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:622:17)
#6      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:487:16)
<asynchronous suspension>
#7      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:518:13)
<asynchronous suspension>
#8      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:223:5)
<asynchronous suspension>
#9      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:140:5)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4529], locale en-US)
    [32m•[39m Flutter version 3.22.2 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 761747bfc5 (3 months ago), 2024-06-05 22:15:13 +0200
    [32m•[39m Engine revision edd8546116
    [32m•[39m Dart version 3.4.3
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at C:\Users\DELL\AppData\Local\Android\Sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m ANDROID_HOME = C:\Users\DELL\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m android-studio-dir = C:\Program Files\Android\Android Studio
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m SM G973F (mobile) • emulator-5554 • android-x86    • Android 7.1.2 (API 25)
    [32m•[39m Windows (desktop) • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4529]
    [32m•[39m Chrome (web)      • chrome        • web-javascript • Google Chrome 128.0.6613.115
    [32m•[39m Edge (web)        • edge          • web-javascript • Microsoft Edge 128.0.2739.54

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
cloud_firestore-5.4.0
cloud_firestore_web-4.2.0
firebase_analytics-11.3.0
firebase_analytics_web-0.5.9+2
firebase_auth-5.2.0
firebase_auth_web-5.12.6
firebase_core-3.4.0
firebase_core_web-2.17.5
firebase_storage-12.2.0
firebase_storage_web-3.9.13

**Comment by darshankawar** [comment] 2024-09-04 11:47
Closing this as a duplicate of https://github.com/flutter/flutter/issues/54213

**Closed by darshankawar** 2024-09-04 11:47 UTC
Labels: in triage
