### ISSUE TITLE
Unable to Use identity-server 4 in Flutter web

### ISSUE THREAD

**Issue by Allamprabhu11** [flutter/flutter#144137] opened 2024-02-26 12:42 UTC
### Steps to reproduce

Unable to use any api methods in identity-server 4 in web.

### Expected results

I should get the response as per the request. It is working fine in Angular and .Net Project.

### Actual results

Same

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-02-27 06:13
Hi @Allamprabhu11 
For us to investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by Allamprabhu11** [comment] 2024-02-27 06:15
Are we supporting Identity Server-4 authentication and login in flutter web?

**Comment by huycozy** [comment] 2024-02-28 03:26
Flutter framework doesn't support a specific OAuth framework. You can check this [thread](https://www.reddit.com/r/FlutterDev/comments/16a8jbq/my_head_is_exploding_ive_found_9_different/) to have idea on an appropriate package for OAuth implementation on Flutter. May be [oauth2](https://pub.dev/packages/oauth2) is a good package to go with, as it's supported on all current target platforms (include Web).

Closing this as it seems to be an implementation issue. If you still believe this is a Flutter framework bug, please try to provide all information indicated in the issue template so that we can verify this.

**Closed by huycozy** 2024-02-28 03:26 UTC
Labels: in triage
