### ISSUE TITLE
whatsapp icon removed from material icons

### ISSUE THREAD

**Issue by abdullahalamodi** [flutter/flutter#119608] opened 2023-01-31 07:54 UTC
I am using **Icons.whatsapp** from the material icons package in my app 
 and when I update flutter to 3.7 looks like the icon does not exist anymore.

- does flutter remove WhatsApp Icon in the last update?

**Comment by huycozy** [comment] 2023-01-31 09:25
Closing as a duplicate of #111667. Please take a look at https://github.com/flutter/flutter/issues/111667#issuecomment-1249224509 as an explain for this.

**Closed by huycozy** 2023-01-31 09:25 UTC
Labels: in triage

**Comment by ettaegbe** [comment] 2023-01-31 16:04
> 

Please, there's no solution there. I'm still looking for the solution to build a new update.

**Comment by ettaegbe** [comment] 2023-01-31 16:06
Please when marking as duplicate, make sure the problem is resolved. 

It's an issue and the solution is to provide a solution.

**Comment by jeisux92** [comment] 2023-03-02 23:12
Hey  @ettaegbe, I know is not a solution, but you could use this package in the meantime https://pub.dev/packages/font_awesome_flutter. I just use it and it looks fine, just like the native package.
