### ISSUE TITLE
Adding google maps as dependency breaks listViews scroll behaviuour on iOS

### ISSUE THREAD

**Issue by Csierram96** [flutter/flutter#126394] opened 2023-05-10 02:54 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

All testing is done on iOS device, iPhone 14 pro max iOS 16.4 simulator

1. Create a flutter app
3. Add a listview or SingleChildScrollView with enough items so you can scroll -> scrolling in the listview is smooth as spected
4. Add `google_maps_flutter` as a dependency to the app. No need to use it. -> scrolling in listviews is not smooth

### Expected results

scrolling should be smooth

### Actual results

scrolling is not smooth

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          body: SingleChildScrollView(
        child: Column(
          children: const [
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
            SizedBox(height: 20),
            Text('SAMPLE TEXT'),
            SizedBox(height: 20),
          ],
        ),
      )),
      title: 'APP',
      debugShowCheckedModeBanner: false,
    );
  }
}



```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale en-CO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 14.3)
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.78.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by huycozy** [comment] 2023-05-10 08:15
Hi @Csierram96 
TBH this seems weird to me :). But I also try this but can't see the issue. 

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/82ed59b4-7b73-4ee2-88dd-15989025c92e
</details>

Since this looks like a performance issue, I would suggest you check this on a physical device for better results. Also, can you please provide a recorded video for this as well?

**Comment by stuartmorgan** [comment] 2023-05-10 10:57
Closing as a duplicate of https://github.com/flutter/flutter/issues/94491

See https://github.com/flutter/flutter/issues/93177#issuecomment-984004447

**Closed by stuartmorgan** 2023-05-10 10:57 UTC
Labels: waiting for customer response, in triage
