### ISSUE TITLE
Uri scheme https opening launchUri as in same domain

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#123544] opened 2023-03-27 16:05 UTC
I am creating a uri on flutter web like this

 final uri = Uri(
        scheme: 'https',
        path: 'accounts.google.com/o/oauth2/v2/auth',
        queryParameters: data);

Where data is some Map<String, dynamic>. I will ignore the queryParameters for simplicity.

When I print the uri, it displays like this

`https:accounts.google.com/o/oauth2/v2/auth?queryParam1=aaa`

Then when I go to

```
if (!await launchUrl(
      uri,
      webOnlyWindowName: '_self',
    )) {
      throw Exception('Could not launch $uri');
    }
```

It tries to open the link in the same domain, as if it didn't have a scheme. It goes to https://mydomain.com/accounts.google.com/o/oauth2/v2/auth

I don't know if the error is in how the Uri is done or if the error is in launch_url library.

Also it is worth noticing that this does not happen on localhost where I am using development mode, there it works properly, and does happen on a production build

Using   url_launcher: ^6.1.10

[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.19045.2728], locale en-CA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by stuartmorgan** [comment] 2023-03-27 18:57
You've created a URI without a host, so it's expected that it behaves as if it doesn't have a host. If you want a host (which appears to be the case; `accounts.google.com` looks like a host to me), you need to provide one in the constructor.

Closing as the issue is in the provided code, not the package.

**Closed by stuartmorgan** 2023-03-27 18:57 UTC
