### ISSUE TITLE
Flutter 3.1.0 on channel dev error while building app

### ISSUE THREAD

**Issue by fabios9702** [flutter/flutter#105601] opened 2022-06-08 15:29 UTC
Hi, I've switched to flutter channel dev, but when I run the App I get some of these errors:  Error:

The method 'FlatButton' isn't defined for the class 'FlutterRoundedButtonAction'.
../…/src/flutter_rounded_button_action.dart:36
    Try correcting the name to the name of an existing method, or defining a method named 'FlatButton'.
        final Widget negativeButton = FlatButton(...

Are the FlatButton deprecated in 3.1.0?
 
Thank you for your help

**Comment by exaby73** [comment] 2022-06-08 15:48
Hello @fabios9702. `FlatButton` was deprecated after `v1.26.0-18.0.pre`. Please use `TextButton` instead. Closing this issue as this is not a bug. Also, please be sure to search online for solutions to your issues, on StackOverflow for example, before raising an issue here :)

**Closed by exaby73** 2022-06-08 15:48 UTC
