### ISSUE TITLE
Provider.of<AppData>(context); causing Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by letto4135** [flutter/flutter#81021] opened 2021-04-23 02:06 UTC
I'm having an issue with provider package on web it seems. I've also tried context.watch<AppData>(); in place of Provider.of<AppData>(context); but have the same error. The first print statement runs, the second does not.

```import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:provider/provider.dart';
import 'AppData.dart';
import 'VærBurger.dart';
import 'bitsAndBobs/AdBar.dart';
import 'bitsAndBobs/Astro.dart';
import 'bitsAndBobs/ChartsHourly.dart';
import 'bitsAndBobs/ChartsDaily.dart';
import 'bitsAndBobs/MyLocation.dart';
import 'bitsAndBobs/Summary.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  Future<InitializationStatus> _initGoogleMobileAds() {
    return MobileAds.instance.initialize();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        home: ChangeNotifierProvider(
          create: (context) => AppData(context),
          child: MyHomePage(title: 'Flutter Demo Home Page'),
        ));
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    print("test");
    final appData = Provider.of<AppData>(context);
    print("test2");
    final theme = appData.backgroundColor != null
        ? appData.backgroundColor[400]
        : appData.backgroundColor;
    final background =
        appData.theme != null ? appData.theme[400] : appData.defaultThemeColor;

    List<Widget> children = [
      AdBar(),
      MyLocation(),
      Summary(),
      Astro(),
    ];

    Map<String, List<String>> weatherData = {
      'temp': ['day', 'night'],
      'feels_like': ['day', 'night'],
      'humidity': [],
    };

    weatherData.forEach((key, values) {
      children.add(Container(height: 20));
      if (appData.dataWanted == 0 || appData.dataWanted == 1) {
        children.add(ChartsHourly(key));
      } else {
        children.add(ChartsDaily(key, values));
      }
    });

    return Container(
      child: Scaffold(
        backgroundColor: background,
        drawer: VaerBurger(),
        appBar: AppBar(
          backgroundColor: theme,
          title: Text("Weather App"),
        ),
        body: SingleChildScrollView(
          child: Column(mainAxisSize: MainAxisSize.min, children: children),
        ),
      ),
    );
  }
}
```

**Comment by pedromassangocode** [comment] 2021-04-23 07:27
Hi @letto4135 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-04-23 07:27 UTC
Labels: in triage
