### ISSUE TITLE
i always get this when i check flutter by cmd. is there any way to install flutter on windows 7 32-bit ?

### ISSUE THREAD

**Issue by MoShehata7920** [flutter/flutter#99510] opened 2022-03-03 20:24 UTC
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Mohamed>flutter
This version of C:\src\flutter\bin\mingit\cmd\git.exe is not compatible with the
 version of Windows you're running. Check your computer's system information to
see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and
then contact the software publisher.
Building flutter tool...
Running pub upgrade...
This version of C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe is not compatible
 with the version of Windows you're running. Check your computer's system inform
ation to see whether you need a x86 (32-bit) or x64 (64-bit) version of the prog
ram, and then contact the software publisher.
Error (216): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (
9 tries left)

Waiting for 1 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)?

**Comment by stuartmorgan** [comment] 2022-03-04 02:59
Duplicate of https://github.com/flutter/flutter/issues/33862

**Closed by stuartmorgan** 2022-03-04 02:59 UTC
