### ISSUE TITLE
Builds are not "clean"

### ISSUE THREAD

**Issue by tiwiz** [flutter/flutter#12176] opened 2017-09-19 21:27 UTC
When rebuilding, changes are not always applied

## Steps to Reproduce
Please check [this video](https://drive.google.com/file/d/0B77uAjKpun_RVjhTc01KS3dqcE0/view?usp=sharing) for steps to reproduce

**Comment by Hixie** [comment] 2018-05-18 22:07
cc @tvolkert @a-siva

**Comment by Hixie** [comment] 2018-05-18 22:07
(This might be obsolete.)

**Comment by zoechi** [comment] 2018-05-20 12:35
dup of #16604 ?

**Comment by zoechi** [comment] 2019-01-21 13:08
Duplicate of #16604

**Closed by zoechi** 2019-01-21 13:08 UTC
Labels: tool
