### ISSUE TITLE
[Impeller] ColorFilter.matrix doesn't work correctly (3.10.0)

### ISSUE THREAD

**Issue by pamir72** [flutter/flutter#126583] opened 2023-05-11 19:14 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Apply any ColorFilter.matrix to any picture using impeller. 

### Expected results

For example, using a identity matrix I do not get the original image.
But with the impeller disabled, everything works as expected !

//Matrix
const ColorFilter identity = ColorFilter.matrix(<double>[
  1, 0, 0, 0, 0,
  0, 1, 0, 0, 0,
  0, 0, 1, 0, 0,
  0, 0, 0, 1, 0,
]);

### Actual results

<img src="https://github.com/flutter/flutter/assets/4150061/cdf21b62-7d32-401a-b97f-ce20ca12d3a7" width="300" />

### Code sample

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

//Matrix
const ColorFilter identity = ColorFilter.matrix(<double>[
  1, 0, 0, 0, 0,
  0, 1, 0, 0, 0,
  0, 0, 1, 0, 0,
  0, 0, 0, 1, 0,
]);

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('Original image'),
            Image.asset('assets/picture.png', width: 100, height: 100, fit: BoxFit.contain),
            const Padding(
              padding: EdgeInsets.only(top: 40.0),
              child: Text('Image with IDENTITY ColorFilter.matrix'),
            ),
            ColorFiltered(
              colorFilter: identity,
              child: Image.asset('assets/picture.png', width: 100, height: 100, fit: BoxFit.contain),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img src="https://github.com/flutter/flutter/assets/4150061/05981ebe-b40f-4125-a134-f46892b00160" width="300"/>

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-x64, locale ru-RU)
    • Flutter version 3.10.0 on channel stable at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at ...
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • D3A66CFB-ECC6-4476-813D-9921CCD32579 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2023-05-12 07:55
Hi @pamir72, can you share the asset you used in your reproduction? I used an image of dash, but there was no difference between impeller and skia. See the screenshot below

<img src="https://github.com/flutter/flutter/assets/88313112/bfb8899c-82d2-4c8c-84ff-7be1999ab568" width="300"/>

**Comment by pamir72** [comment] 2023-05-12 07:57
![picture](https://github.com/flutter/flutter/assets/4150061/da0b26b5-d998-4d0f-94ff-56eb19563846)

I tried it only on emulators, I didn't try it on a real device

**Comment by danagbemava-nc** [comment] 2023-05-12 13:50
Hi @pamir72, I can't seem to repro on the simulator either. I tested this on stable btw. Is there any additional information you can provide?

<img width="1402" alt="Screenshot 2023-05-12 at 13 46 05" src="https://github.com/flutter/flutter/assets/88313112/a532db4d-0bf5-4c63-8875-a5751345f26a">

**Comment by pamir72** [comment] 2023-05-12 14:10
But there are problems. See 2 pictures 1) with "flutter run". and 2) with "flutter run --no-enable-impeller
<img width="1680" alt="Снимок экрана 2023-05-12 в 17 02 54" src="https://github.com/flutter/flutter/assets/4150061/93320a41-70b9-4e10-866f-7e4e580496db">
<img width="1680" alt="Снимок экрана 2023-05-12 в 17 05 54" src="https://github.com/flutter/flutter/assets/4150061/4bb582d0-303d-4178-8dba-89c9fcf1100d">
"

**Comment by danagbemava-nc** [comment] 2023-05-15 06:54
Hi @pamir72, can you try running on the `master` channel to see if you still have this issue? I asked one of my colleagues to check on his mac and he also couldn't reproduce the bug either. He tested on physical devices as well as the simulator. He's also running an intel mac

**Comment by pamir72** [comment] 2023-05-16 13:06
I would not like to switch to the master channel now, I will wait for the stable version 3.11 and higher and try.

**Comment by chinmaygarde** [comment] 2023-05-22 18:09
@pamir72 We tried to reproduce this on a device as well as simulator but were unsuccessful. Can you dump the information about your host ( -> "About This Mac") so we can investigate this further?

**Comment by pamir72** [comment] 2023-05-23 05:22
<img width="317" alt="Снимок экрана 2023-05-23 в 08 18 01" src="https://github.com/flutter/flutter/assets/4150061/164051e2-d0c6-44ba-8fdb-7997e25c1b25">

**Comment by alidiker-hub** [comment] 2023-05-25 07:18
The problem still persists in version 3.10.2.

**Comment by gerken-tss** [comment] 2023-06-09 15:27
Can confirm. Having the same issue with 3.10.4. Noticed it with Matrix and BackdropFilter.

**Comment by gerken-tss** [comment] 2023-06-22 17:25
@chinmaygarde 
Do you need anything more? Can I help you in reproducing the bug? It's very problematic for us as it interferes with a production feature that several thousands of people are using :(.

**Comment by chinmaygarde** [comment] 2023-06-22 18:44
@gerken-tss We were trying to reproduce this on devices and the few simulators handy but weren't successful. You mentioned production features, so I'm assuming you observed this is on devices. Can you confirm an iOS device and version you definitely see this on? I am pretty sure we can get our hands on any device and this information will help us narrow down what to focus on. I'll surface this again with the team to see if anything pops up as well.

**Comment by gerken-tss** [comment] 2023-06-26 07:11
@chinmaygarde 
Thanks for the response.
Yes, it's even reproducible on the iOS and Android emulators. Let me transform our company-specific code into a isolated, generic example and come back to you.

**Comment by gerken-tss** [comment] 2023-07-05 15:31
@chinmaygarde 

Soo …

Sorry I got you waiting. I was a little busy and it took me some time to isolate the issue.
But now I have an easy-to-test example!

First the symptoms:

https://github.com/flutter/flutter/assets/84321030/9c68718f-461a-4544-b625-b23180cd87f0

As you can see, the `BackDropFilter` that is being used by [RawMagnifier](https://api.flutter.dev/flutter/widgets/RawMagnifier-class.html) widget here behaves strangely. While the right part of the image is being scaled properly within the magnifier, when I cross a certain threshold with the cursor, it kind of skips an area of the image.

I had a look into the implementation of `RawMagnifier` and saw that [Matrix4](https://api.flutter.dev/flutter/vector_math_64/Matrix4-class.html) is in use there.

Now the code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final double _size = 160;
  Offset _position = Offset.zero;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          GestureDetector(
            onPanUpdate: (DragUpdateDetails details) {
              final RenderBox? box = context.findRenderObject() as RenderBox?;

              setState(() {
                _position = _calculateFocalPointOffset(
                  box,
                  details.globalPosition,
                );
              });
            },
            child: Wrap(
              children: [
                for (int i = 1; i <= 100; i++)
                  Container(
                    width: 32,
                    height: 32,
                    color: i % 2 == 0 ? Colors.red : Colors.green,
                  ),
              ],
            ),
          ),
          Align(
            alignment: Alignment.topRight,
            child: RawMagnifier(
              decoration: MagnifierDecoration(
                shape: CircleBorder(
                  side: BorderSide(
                    color: Theme.of(context).primaryColor,
                    width: 5,
                  ),
                ),
              ),
              size: Size(_size, _size),
              focalPointOffset: _position,
              magnificationScale: 2.0,
            ),
          ),
        ],
      ),
    );
  }

  Offset _calculateFocalPointOffset(RenderBox? box, Offset globalTouchPoint) {
    return Offset(
      globalTouchPoint.dx - (box?.size.width ?? 0) + (_size / 2),
      globalTouchPoint.dy - (_size / 2),
    );
  }
}
```

You can just copy this off into the `main.dart` file of your application and run it. By dragging over the green-red-tiled widget you control the focal point of the magnifier. 
I replaced the image asset by this tiled widget in order for you to have no dependencies of downloading an image before running it.

* If you run this application in the iOS simulator (or real device) with impeller, you get the same behaviour as in the video
* If you run it with the `--no-enable-impeller` flag, everything works fine
* I also realized that replacing the `Alignment` widget with a `Positioned` widget makes it work. But in any case, the behaviour should not differ at all between the impeller app and the skia app.

I also tested re-implementing the `RawMagnifier` widget with my own implementation using a `Matrix4` and I got the same results, so it's nothing related to this particular `Magnifier` widget.

**Comment by gerken-tss** [comment] 2023-07-21 14:08
@chinmaygarde

This shouldn't be marked as done :(. Can you reproduce the behavior using my description above?

**Comment by chinmaygarde** [comment] 2023-07-22 02:30
@gerken-tss @pamir72 This should not have been closed.

I forgot to remove the "waiting for customer response" tag after triaging and automations likely introduced as part of [flutter.dev/go/triage-2023-rfc](http://flutter.dev/go/triage-2023-rfc) closed issues that had the tag for a long time. It was my mistake.

I'm updating the weekly triage guidance to avoid this in the future and reviewing issues closed in the past couple of weeks due to the additional automations. Thanks for explicitly pinging.

Sorry about the churn and thanks to @gerken-tss for the reduced test case. We have all we need to find and fix this.

**Comment by gerken-tss** [comment] 2023-07-22 07:13
@chinmaygarde 
No worries and thank you for clearing it up 🙂. Looking forward to the fix.

**Comment by gaaclarke** [comment] 2023-09-29 16:36
I ran the reproduction code in https://github.com/flutter/flutter/issues/126583#issuecomment-1622004268 through the new canvas trace mechanism.  The difference between working and not working frame is the parameters to the `MatrixImageFilter`.  The inflection point is around (150, -310), anything left or below that is wrong.

## works
```
}] [((0.000000, 0.000000), (160.000000, 160.000000))] [{MatrixImageFilter matrix: (
       2.000000,       0.000000,       0.000000,      85.000000,
       0.000000,       2.000000,       0.000000,    -191.000000,
       0.000000,       0.000000,       1.000000,       0.000000,
       0.000000,       0.000000,       0.000000,       1.000000,
)}]
```
## broken
```
}] [((0.000000, 0.000000), (160.000000, 160.000000))] [{MatrixImageFilter matrix: (
       2.000000,       0.000000,       0.000000,     221.000000,
       0.000000,       2.000000,       0.000000,    -193.000000,
       0.000000,       0.000000,       1.000000,       0.000000,
       0.000000,       0.000000,       0.000000,       1.000000,
)}]
```

**Comment by gaaclarke** [comment] 2023-09-29 18:30
I've looked through this a bit more.  In the case where it is rendering correctly `FilterContents::Render` is getting called, it isn't called in the non-working case.  In both cases `MatrixImageFilter::WrapInput` is getting called which should be making the contents that should get rendered.

I've also tested the MatrixImageFilter in isolation and it seems to be working.  There is some combination required to create the bug.  Probably the transform or clip that is making it a circle in the top right corner.

I'm also a bit dubious that the reproducible bug in the comment is the same one listed in the description (that others had a hard time reproducing).

**Comment by gaaclarke** [comment] 2023-09-29 18:47
Here is the point in the code where it is deciding not to render the MatrixImageFilter in the pathological case: https://github.com/flutter/engine/blob/48973d7f9bebaa5f850e35a75b2549c2534c3e95/impeller/entity/entity_pass.cc#L773

**Comment by gaaclarke** [comment] 2023-09-29 19:03
Specifically in Contents::ShouldRender, it is returning false because there is no intersection between `stencil_coverage` and `coverage` https://github.com/flutter/engine/blob/48973d7f9bebaa5f850e35a75b2549c2534c3e95/impeller/entity/contents/contents.cc#L148

example:
```
stencil_coverage = (x:0 y:0 w:320 h:320)
coverage = (x: 90 y: -752 w:640 h:640)
```

**Comment by gaaclarke** [comment] 2023-09-29 20:44
Hey @bdero, I chatted with @chinmaygarde a bit about this issue and it sounds like this is related to the other stencil coverage work you are looking into.  Basically I'm seeing a stencil_coverage mixmatch when rendering a clip area with a matriximagefilter that is doing scaling and translating.  It results in the filter deciding it shouldn't be rendered erroneously.  Let's sync up when you are back.

**Comment by bdero** [comment] 2023-09-29 21:38
(We ended up meeting about this offline -- I think there are a few subtle overlapping problems still going on with coverage. These are a bit hard to dedupe, but I suspect this doesn't overlap with the stuff I'm investigating right now)

**Comment by gaaclarke** [comment] 2023-09-29 23:09
notes:
1) overriding MatrixImageFilter::ShouldRender to also return true doesn't work around the issue
1) changing the magnification to 1.0 moves the inflection point down, not left or right and the bug still persists
1) moving the magnifier to the top left corner does not remove the problem.  The inflection point flips so rendering is wrong when the finger is right or below it instead.
1) I started to try to reproduce this case in a golden test and I found a much simpler problem which may be related: https://github.com/flutter/flutter/issues/135777

**Comment by bdero** [comment] 2023-10-05 19:26
Note to self and other onlookers. The original color matrix filter issue that this bug addresses is long gone, and this bug has been refocused on a completely different problem related to matrix image filters beginning here: https://github.com/flutter/flutter/issues/126583#issuecomment-1584767251

**Comment by gaaclarke** [comment] 2023-10-06 03:30
> Note to self and other onlookers. The original color matrix filter issue that this bug addresses is long gone, and this bug has been refocused on a completely different problem related to matrix image filters beginning here: [#126583 (comment)](https://github.com/flutter/flutter/issues/126583#issuecomment-1584767251)

I'm going to close this issue as fixed and spawn out the existing one in a new issue then: https://github.com/flutter/flutter/issues/136058

**Closed by gaaclarke** 2023-10-06 03:30 UTC
Labels: engine, P2, e: impeller, found in release: 3.10, team-engine, triaged-engine
