### ISSUE TITLE
google-services plugin could not detect any version of com.google.android.gms or .....

### ISSUE THREAD

**Issue by ish12321** [flutter/flutter#34393] opened 2019-06-13 09:37 UTC
Hello,
I recently started working with flutter and this is some error I am getting. I searched the web but could not find any solution. Could someone please help me out with it? 
```
> * Error running Gradle:
> ProcessException: Process "F:\flutterApps\peer_vpn\android\gradlew.bat" exited abnormally:
> 
> > Configure project :app
> google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 11.4.2 will be used.
> please apply google-services plugin at the bottom of the build file.
> Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> Could not find google-services.json while looking in [src/nullnull/dynamicProfile, src/dynamicProfile/nullnull, src/nullnull, src/dynamicProfile,
> src/nullnullDynamicProfile]
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> Could not find google-services.json while looking in [src/nullnull/profile, src/profile/nullnull, src/nullnull, src/profile, src/nullnullProfile]
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> Could not find google-services.json while looking in [src/nullnull/dynamicRelease, src/dynamicRelease/nullnull, src/nullnull, src/dynamicRelease,
> src/nullnullDynamicRelease]
> registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
> WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
> It will be removed at the end of 2019.
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
> To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
> WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
> It will be removed at the end of 2019.
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
> To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
>          *********************************************************
> WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
>          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
>          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
>          *********************************************************
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'F:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+4\android\build.gradle' line: 44
> 
> * What went wrong:
> A problem occurred evaluating project ':firebase_core'.
> > ..\..\pubspec.yaml (The system cannot find the file specified)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 9s
>   Command: F:\flutterApps\peer_vpn\android\gradlew.bat app:properties
> 
> 
> Please review your Gradle project setup in the android/ folder.
```
[gradle build.zip](https://github.com/flutter/flutter/files/3285235/gradle.build.zip)

**Comment by Kurotsu5761** [comment] 2019-06-13 10:39
```
* Error running Gradle:
ProcessException: Process "D:\Work\RaGen\RaCon\racon_survey\android\gradlew.bat" exited abnormally:

> Configure project :app
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 11.4.2 will be used.
please apply google-services plugin at the bottom of the build file.
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/dynamicProfile, src/dynamicProfile/nullnull, src/nullnull, src/dynamicProfile,
src/nullnullDynamicProfile]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/profile, src/profile/nullnull, src/nullnull, src/profile, src/nullnullProfile]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/dynamicRelease, src/dynamicRelease/nullnull, src/nullnull, src/dynamicRelease,
src/nullnullDynamicRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
         *********************************************************
WARNING: This version of camera will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+4\android\build.gradle' line: 44

* What went wrong:
A problem occurred evaluating project ':firebase_core'.
> ..\..\pubspec.yaml (The system cannot find the file specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: D:\Work\RaGen\RaCon\racon_survey\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder
```

**Comment by SunlightDave** [comment] 2019-06-13 11:48
Duplicate of https://github.com/flutter/flutter/issues/34385
to fix downgrade to:
`firebase_core: 0.4.0+3`

**Comment by ish12321** [comment] 2019-06-14 08:59
Hello,
I changed the version in pubspec.yaml for firebase_core to +3 however, it still keeps using +4. I even restarted my pc after doing the change and saving. Today, I find a error about +5 version. I dont know why but somehow it is using the latest version on internet and not the one i am mentioning. Can someone please help me out? I am using VSCode

**Comment by mikhail-tokarev** [comment] 2019-10-08 12:05
Hi @ish12321 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your _`flutter doctor -v`_

**Comment by mep72** [comment] 2019-10-18 15:16
Try removing `pubspec.lock` this files keeps a copy of the dependencies, then run the` flutter packages get` command to retrieve the versions specified in your pubspec.yaml file, don't run the `flutter packages upgrade` command or you'll end with a newer version of the dependencies

**Comment by iapicca** [comment] 2019-11-08 14:05
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 14:05 UTC
Labels: waiting for customer response
