### ISSUE TITLE
error "No Material widget found" when using IconButton with Positioned, Draggable

### ISSUE THREAD

**Issue by srkrishnan1989** [flutter/flutter#107621] opened 2022-07-14 07:27 UTC
In Android app , 

when IconButton used with Positioned, Draggable error shown "No Material widget found" ,

same code TextButton used with Positioned, Draggabl,e its works fine,

minimum code to reproduce the error 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

class ListviewDemo extends StatefulWidget {
  const ListviewDemo({Key? key}) : super(key: key);

  @override
  State<ListviewDemo> createState() => _ListviewDemoState();
}

class _ListviewDemoState extends State<ListviewDemo> {
  double _svalue = 19.0;
  bool scrolllockbutton = false;
  bool iconlockbutton = false;

  late double sleft;
  late double stop;




  final keyText = GlobalKey();

  List<String> dataList = [
    "2K",
    "86-DOS",
    "A/UX",
    "Acados",
    "ACP (Airline Control Program)",
    "AdaOS",
    "ADMIRAL",
    "Adrenaline",
    "aerolitheOS",
    "Aimos",
    "AIOS",
    "AIX",
    "Allegro",
    "AllianceOS",
    "Alpha OS",
    "Alto OS",
    "Amiga OS",
    "Amoeba",
    "Amstrad",
    "AMX RTOS",
    "AneedA",
  ];
  @override
  void initState() {
    super.initState();
    initposition();
  }

  initposition() {
    sleft = 10;
    stop = 10;
  }


  Widget scrolllockappbutton() {
    return IconButton(
        icon: scrolllockbutton
            ? const Icon(Icons.lock, color: Colors.red, size: 25)
            : const Icon(Icons.lock_open_sharp, color: Colors.green, size: 25),
        onPressed: () {
          setState(() {
            scrolllockbutton = !scrolllockbutton;
          });
        }
        //)
        );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
          // controller: ancon,
          floatHeaderSlivers: true,
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverAppBar(
                snap: true,
                pinned: false,
                floating: true,
                title: const Text("Demo"),
                actions: <Widget>[
                  scrolllockappbutton(),
                ],
              ),
            ];
          },
          body: Stack(children: [
           Column(children: [
            Expanded(
              child: ListView.builder(
                  itemCount: dataList.length,
                  itemBuilder: (context, index) {
                    return Column(children: [
                      ListTile(
                        title: Text(
                          '\n${dataList[index]}',
                          style: const TextStyle(fontSize: 50),
                        ),
                      ),
                      const Divider(
                        height: 1,
                        color: Colors.grey,
                      )
                    ]);
                  }),
            ),]),
            Positioned(
                left: sleft,
                top: stop,
                child: GestureDetector(
                  onLongPress: () {
                    print('onLongPress');
                  },
                  onTap: () {
                    print('onTap');
                  },
                  child: scrolllockbutton
                      ? showbutton()
                      : Draggable(
                          feedback: showbutton(),
                          child: showbutton(),
                          onDragEnd: (drag) {
                            final renderbox =
                                context.findRenderObject() as RenderBox;
                            Offset off = renderbox.globalToLocal(drag.offset);
                            setState(() {
                              stop = off.dy - 55;
                              sleft = off.dx + 5;
                            });
                          },
                        ),
                ))
          ])),
    );
  }

  showbutton() {
    return
        //Container(child: Text('hello'));
        Container(
            // key: keyText,
            child: ClipRRect(
                borderRadius: BorderRadius.circular(5.0),
                child: Container(
                    //height: 50.0,
                    color: Colors.red.shade100,
                    child: iconlockbutton
                        ? TextButton(
                            // color: Colors.blue,
                            // icon:
                            child: const Icon(Icons.add_a_photo),
                            //const Text('data'),
                            onPressed: () {
                              setState(() {
                                iconlockbutton = !iconlockbutton;
                              });
                            },
                          )
                        : IconButton(
                            color: Colors.blue,
                            icon: const Icon(Icons.add_a_photo),
                            onPressed: () {
                              setState(() {
                                iconlockbutton = !iconlockbutton;
                              });
                            },
                          ))));
  }
}

```
</details> 

https://user-images.githubusercontent.com/6891619/178925885-b5fa003c-1caf-4617-8faa-0df48e732af2.mp4

**Comment by maheshmnj** [comment] 2022-07-14 10:29
Hi @srkrishnan1989, Thanks for filing the issue. This is working as intended `Draggable.feedback`  is an overlay which requires to be wrapped in a material widget. please see this simplified code 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const ListviewDemo(),
    );
  }
}

class ListviewDemo extends StatefulWidget {
  const ListviewDemo({Key? key}) : super(key: key);

  @override
  State<ListviewDemo> createState() => _ListviewDemoState();
}

class _ListviewDemoState extends State<ListviewDemo> {
  double _svalue = 19.0;
  bool scrolllockbutton = false;
  bool iconlockbutton = false;

  late double sleft;
  late double stop;

  final keyText = GlobalKey();

  List<String> dataList = [
    "2K",
    "86-DOS",
    "A/UX",
    "Acados",
    "ACP (Airline Control Program)",
    "AdaOS",
    "ADMIRAL",
    "Adrenaline",
    "aerolitheOS",
    "Aimos",
    "AIOS",
    "AIX",
    "Allegro",
    "AllianceOS",
    "Alpha OS",
    "Alto OS",
    "Amiga OS",
    "Amoeba",
    "Amstrad",
    "AMX RTOS",
    "AneedA",
  ];
  @override
  void initState() {
    super.initState();
    initposition();
  }

  initposition() {
    sleft = 10;
    stop = 10;
  }

  Widget scrolllockappbutton() {
    return IconButton(
        icon: scrolllockbutton
            ? const Icon(Icons.lock, color: Colors.red, size: 25)
            : const Icon(Icons.lock_open_sharp, color: Colors.green, size: 25),
        onPressed: () {
          setState(() {
            scrolllockbutton = !scrolllockbutton;
          });
        }
        //)
        );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
          // controller: ancon,
          floatHeaderSlivers: true,
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverAppBar(
                snap: true,
                pinned: false,
                floating: true,
                title: const Text("Demo"),
                actions: <Widget>[
                  scrolllockappbutton(),
                ],
              ),
            ];
          },
          body: Stack(children: [
            Positioned(
                left: sleft,
                top: stop,
                child: scrolllockbutton
                    ? showbutton()
                    : Draggable(
                        feedback: showbutton(),
                        child: showbutton(),
                        onDragEnd: (drag) {
                          final renderbox =
                              context.findRenderObject() as RenderBox;
                          Offset off = renderbox.globalToLocal(drag.offset);
                          setState(() {
                            stop = off.dy - 55;
                            sleft = off.dx + 5;
                          });
                        },
                      ))
          ])),
    );
  }

  showbutton() {
    return Material(
        // key: keyText,
        child: ClipRRect(
            borderRadius: BorderRadius.circular(5.0),
            child: Container(
                //height: 50.0,
                color: Colors.red.shade100,
                child: iconlockbutton
                    ? TextButton(
                        // color: Colors.blue,
                        // icon:
                        child: const Icon(Icons.add_a_photo),
                        //const Text('data'),
                        onPressed: () {
                          setState(() {
                            iconlockbutton = !iconlockbutton;
                          });
                        },
                      )
                    : IconButton(
                        color: Colors.blue,
                        icon: const Icon(Icons.add_a_photo),
                        onPressed: () {
                          setState(() {
                            iconlockbutton = !iconlockbutton;
                          });
                        },
                      ))));
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as this is working as intended. Incase you disagree feel free to write in the comments and we will reopen it.

thanks you.

**Closed** 2022-07-14 10:29 UTC
Labels: in triage
