### ISSUE TITLE
Google sign_in throwing PlatformException

### ISSUE THREAD

**Issue by Rawnly** [flutter/flutter#55455] opened 2020-04-23 12:39 UTC
## Steps to Reproduce

1. Run the app.
2. Login
3. Then when it prompts the Google modal, just dismiss it.

**Expected results:** 
Catch the exception.

**Actual results:** 
`
	PlatformException (PlatformException(sign_in_canceled, com.google.GIDSignIn, The user canceled the sign-in flow.))
`

### Method
```dart
static Future<FirebaseUser> signInWithGoogle() async {
    final GoogleSignInAccount googleSignInAccount = await googleSignIn.signIn();

    if (googleSignInAccount == null) {
      // Sign in flow canceled.
      return null;
    }

    final GoogleSignInAuthentication googleSignInAuthentication = await googleSignInAccount.authentication;

    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleSignInAuthentication.accessToken,
      idToken: googleSignInAuthentication.idToken,
    );

    final AuthResult authResult = await _auth.signInWithCredential(credential);
    final FirebaseUser user = authResult.user;

    assert(!user.isAnonymous);
    assert(await user.getIdToken() != null);

    final FirebaseUser currentUser = await _auth.currentUser();
    assert(user.uid == currentUser.uid);

    print("Sign in completed. Welcome ${user.displayName}");

    return user;
  }
```

### Implementation
Then in my `main.dart`

```dart
	FloatButton (
		child: Text("Google Login"),
		onPressed: () async {
        	setState(() {
	          this.isLoading = true;
    	    });

        	try {
	          FirebaseUser firebaseUser = await SignInUtility.signInWithGoogle();

        	  setState(() {
    	        this.user = firebaseUser;
	            this.isLoading = false;
    	      });
        	} catch (e) {
	          print("Error");
	          print(e);
    	    }
    	  }
	)
```

**Comment by Rawnly** [comment] 2020-04-23 12:41
Am I doing something wrong? I've seen similar issues but I haven't find a solution yet.

**Comment by TahaTesser** [comment] 2020-04-23 14:32
duplicate of [#44431](https://github.com/flutter/flutter/issues/44431)

**Closed by TahaTesser** 2020-04-23 14:32 UTC
