### ISSUE TITLE
[pigeon] Kotlin generation got exception when using a nullable enum in method parameters

### ISSUE THREAD

**Issue by unes0111** [flutter/flutter#125031] opened 2023-04-18 10:59 UTC
When I define one of the method parameters as a nullable enum, Pigeon generates a Kotlin setUp function that uses a ternary condition in the wrong syntax for Kotlin.

This is the Dart code:
```dart
enum Level {
  easy,
  medium,
  hard,
}

@HostApi()
abstract class TestApi {
  String getMessages(Level? level);
}
``` 

The generated Kotlin code:
```kotlin
interface TestApi {
  fun getMessages(level: Level?): String

  companion object {
    /** The codec used by TestApi. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `TestApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: TestApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.TestApi.getMessages", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] == null ? null : Level.ofRaw(args[0] as Int)  // <--- this line is wrong in Kotlin
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getMessages(levelArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
``` 

As you can see the format of ternary condition is wrong for Kotlin and should be replaced with something like this:
```kotlin
val levelArg = if (args[0] == null) null else Level.ofRaw(args[0] as Int)
```

**Comment by stuartmorgan** [comment] 2023-04-18 11:39
Enums aren't fully supported yet; see also https://github.com/flutter/packages/tree/main/packages/pigeon#null-safety-nnbd

Closing as a duplicate of https://github.com/flutter/flutter/issues/87307

**Closed by stuartmorgan** 2023-04-18 11:39 UTC
Labels: in triage
