### ISSUE TITLE
FR: allow BoxDecoration for Material

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#21125] opened 2018-08-28 18:34 UTC
I just noticed today that it is nearly impossible to give a RaisedButton a gradient. So I'm asking that BoxDecoration, or a Gradient property, be added to all material components.

**Comment by sir-boformer** [comment] 2018-09-01 22:32
You could wrap it into a `DecoratedBox`/`Container` and make the `Material` transparent.

**Comment by 2015-lizaiyang** [comment] 2018-10-17 05:58
I also encountered this problem, RaisedButton could not add fade

**Comment by shihaohong** [comment] 2019-10-04 00:05
I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/41627, but we also shouldn't be supporting this type of modification since it directly violates the Material specification. 

On the other hand, a custom button widget could be made by composing a `GestureDetector` with a `Container`, which takes a `Decoration`.

**Closed by shihaohong** 2019-10-04 00:05 UTC
Labels: f: material design, framework, severe: new feature

**Comment by lukepighetti** [comment] 2019-10-06 16:07
@shihaohong Why don't we factor `package:flutter/material.dart` into it's own project and then provide more low-level widgets for buttons etc. Many projects don't follow material guidelines so only servicing material guidelines too tightly scopes Flutter IMHO.

**Comment by shihaohong** [comment] 2019-10-07 05:03
I agree with you about creating a library with lower-level support. I think it is a good idea and was a topic of discussion on the Flutter dev discord (I tagged you in the channel where I asked about it).

Currently, my understanding is that the Material library is an out-of-the-box solution for developers who intend to follow the Material design specifications, much like how the Cupertino library was created to mimic iOS native as close as possible. 

There are issues I considered about building out additional functionality outside of the scope of the specifications and guidelines are:
- **An increasingly large API surface for Flutter devs** - Developers using the material library would have to grapple with a ton of parameters for the widget. It becomes difficult to figure out the exact modifications you need to get a look you want (and might be forcing it to have)
- **Difficulty of maintenance** - The material widgets will become increasingly complex if we build for additional flexibility while trying to uphold/maintain the material specs. This makes it increasingly difficult for the framework developers to maintain the code. 

Overall, I think it makes more sense to create a new, lower-level widget library to help better service Flutter developers who want a more custom look and feel to their applications, but have no desire to follow the Material/Cupertino spec.

**Comment by lukepighetti** [comment] 2019-10-07 16:15
I agree 100% on a mid-level API that people can build upon. `material` is too integral to the development process at the moment. That way `material` can be kept svelte and clean and people can build out whatever they need on the mid-level api.
