### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by menezes85** [flutter/flutter#59412] opened 2020-06-14 03:19 UTC
url_launcher-5.4.10/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java:47: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
          return super.shouldOverrideUrlLoading(view, url);

Using API 29 / URL Launcher: 5.4.10

**Comment by MagnumDingusEdu** [comment] 2020-06-14 04:58
Possible duplicate of #37616. Upgrading to a higher minSdkVersion, or migrating to Android X should fix this error.

**Comment by iapicca** [comment] 2020-06-15 07:24
Hi @menezes85 
as @MagnumDingusEdu  pointed out there's an open [issue](https://github.com/flutter/flutter/issues/37616) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-15 07:24 UTC
