### ISSUE TITLE
Installation app blocked by play protect

### ISSUE THREAD

**Issue by yp101** [flutter/flutter#95451] opened 2021-12-17 06:46 UTC
Hi there!
when trying to install a signed application app-release.apk , a "Blocked by Play Protect" message is shown and the app is not installed.

i follow the steps on this page for release apk:
https://flutter.dev/docs/deployment/android

how to solve this!

![ss](https://user-images.githubusercontent.com/92661919/146501071-1c151d6f-adcd-49ea-ae03-188c36d95107.png)

**Comment by mamuseferha** [comment] 2021-12-17 08:34
Hi @yp101, this happens because the app has not been uploaded to playstore yet. You can tap on `install anyway` to install the app.

Closing this now as it is not a bug or feature request.

**Closed by mamuseferha** 2021-12-17 08:34 UTC
Labels: in triage

**Comment by yp101** [comment] 2021-12-18 05:07
hi @mamuseferha, i want to publish app on samsung galaxy play store and they don't accept apps blocked by play protect. that's why i wanted to know the solution.

**Comment by mamuseferha** [comment] 2021-12-23 08:51
@yp101 please see https://stackoverflow.com/questions/51080755/installation-app-blocked-by-play-protect
