### ISSUE TITLE
Expose wrapper of Dart_PostCObject in libflutter_engine.so

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46694] opened 2019-12-10 16:45 UTC
https://buganizer.corp.google.com/issues/145982720.

cc @chinmaygarde

**Comment by chinmaygarde** [comment] 2019-12-12 02:23
Duplicate of https://github.com/flutter/flutter/issues/46624

**Closed by chinmaygarde** 2019-12-12 02:23 UTC
Labels: customer: dream (g3), engine
