### ISSUE TITLE
wordSpacing has no effect on RTL text

### ISSUE THREAD

**Issue by dickermoshe** [flutter/flutter#124480] opened 2023-04-09 15:24 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 
Setting the `wordSpacing` in the text style should add more spacing between words.  
**Actual results:** 
Setting `wordSpacing` on RLT text/languageshas no effect.  
This happens whether you set the `textDirection` on the `Text` widget or not.  
See this [dartpad](https://dartpad.dev/aa55719bcd6fbdcab90b6e4faa8451cd).
<details>
<summary>Code sample</summary>

Run this in [dartpad](https://dartpad.dev/aa55719bcd6fbdcab90b6e4faa8451cd).
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    double wordSpacingAmount = 20;
    String englishText = 'Lorem ipsum dolor sit amet';
    String hebrewText = 'טקסט ללא רווח בין מילים';
    String arabicText = 'نص مع عدم وجود مسافات بين الكلمات';

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'English',
              style: TextStyle(fontSize: 24),
            ),
            Text(
              englishText,
              style: TextStyle(),
            ),
            Text(
              englishText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
            SizedBox(height: 20),
            Text(
              'Hebrew',
              style: TextStyle(fontSize: 24),
            ),
            Text(
              hebrewText,
              style: TextStyle(),
            ),
            Text(
              hebrewText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
            SizedBox(height: 20),
            Text(
              'Arabic',
              style: TextStyle(fontSize: 24),
            ),
            Text(
              arabicText,
              style: TextStyle(),
            ),
            Text(
              arabicText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
            SizedBox(height: 20),
            Text(
              'Hebrew with RTL',
              textDirection: TextDirection.rtl,
              style: TextStyle(fontSize: 24),
            ),
            Text(
              hebrewText,
              style: TextStyle(),
            ),
            Text(
              hebrewText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
            SizedBox(height: 20),
            Text(
              'Arabic with RTL',
              textDirection: TextDirection.rtl,
              style: TextStyle(fontSize: 24),
            ),
            Text(
              arabicText,
              style: TextStyle(),
            ),
            Text(
              arabicText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
PS C:\Users\Moshe Dicker\Documents\DickerSystems\bug_flutter> flutter analyze
Analyzing bug_flutter...
No issues found! (ran in 0.8s)
```

```
PS C:\Users\Moshe Dicker\Documents\DickerSystems\bug_flutter> flutter doctor -v
[✓] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.22621.1413], locale en-US)
    • Flutter version 3.7.10 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (6 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\ANDROID_SDK
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.4.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code, 64-bit edition (version 1.76.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 112.0.5615.49
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 112.0.1722.34

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<img width="201" alt="image" src="https://user-images.githubusercontent.com/75931499/230780718-352b0e25-b5d2-4920-89f7-faae85811a26.png">

**Comment by exaby73** [comment] 2023-04-10 11:29
Hellp @dickermoshe. Is this issue reproducible on the latest master version?

**Comment by dickermoshe** [comment] 2023-04-10 13:04
Yes.
```dart
[√] Flutter (Channel master, 3.10.0-2.0.pre.30, on Microsoft Windows [Version 10.0.22621.1413], locale en-US)
    • Flutter version 3.10.0-2.0.pre.30 on channel master at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8eb1c9d1f6 (42 minutes ago), 2023-04-10 08:21:42 -0400
    • Engine revision 44d1656444
    • Dart version 3.0.0 (build 3.0.0-417.0.dev)
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\ANDROID_SDK
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.4.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code, 64-bit edition (version 1.76.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.62.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 112.0.5615.49
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 112.0.1722.34

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
<img width="242" alt="image" src="https://user-images.githubusercontent.com/75931499/230906477-aa7b8ca2-6f88-4ee5-8af1-c8250ca2c1e0.png">

**Comment by exaby73** [comment] 2023-04-10 13:46
I can reproduce this issue with `Master (3.9.0-22.0.pre.28)`. `wordSpacing` works with English words set to RTL as well, just not for native RTL languages.

<details>
<summary>Code Sample With English RTL</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    double wordSpacingAmount = 20;
    String englishText = 'Lorem ipsum dolor sit amet';
    String hebrewText = 'טקסט ללא רווח בין מילים';
    String arabicText = 'نص مع عدم وجود مسافات بين الكلمات';

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'English',
              style: TextStyle(fontSize: 24),
            ),
            Text(
              englishText,
              style: const TextStyle(),
            ),
            Text(
              englishText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
            const SizedBox(height: 20),
            const Text(
              'Hebrew',
              style: TextStyle(fontSize: 24),
            ),
            Text(
              hebrewText,
              style: const TextStyle(),
            ),
            Text(
              hebrewText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
            const SizedBox(height: 20),
            const Text(
              'Arabic',
              style: TextStyle(fontSize: 24),
            ),
            Text(
              arabicText,
              style: const TextStyle(),
            ),
            Text(
              arabicText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
            const SizedBox(height: 20),
            const Text(
              'English with RTL',
              style: TextStyle(fontSize: 24),
            ),
            Text(
              englishText,
              textDirection: TextDirection.rtl,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
            const SizedBox(height: 20),
            const Text(
              'Hebrew with RTL',
              textDirection: TextDirection.rtl,
              style: TextStyle(fontSize: 24),
            ),
            Text(
              hebrewText,
              style: const TextStyle(),
            ),
            Text(
              hebrewText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
            const SizedBox(height: 20),
            const Text(
              'Arabic with RTL',
              textDirection: TextDirection.rtl,
              style: TextStyle(fontSize: 24),
            ),
            Text(
              arabicText,
              style: const TextStyle(),
            ),
            Text(
              arabicText,
              style: TextStyle(wordSpacing: wordSpacingAmount),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.9.0-22.0.pre.28, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
    • Flutter version 3.9.0-22.0.pre.28 on channel master at /Users/nabeelparkar/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nabeelparkar/fvm/versions/master. Consider adding /Users/nabeelparkar/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a6a20cdc6 (2 hours ago), 2023-04-05 06:39:09 +0100
    • Engine revision 4219c72ac8
    • Dart version 3.0.0 (build 3.0.0-408.0.dev)
    • DevTools version 2.23.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 111.1.49.132

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dickermoshe** [comment] 2023-04-10 13:53
I just ran the your code sample on dartpad, all the english text has working `wordSpacing`

**Comment by jason-simmons** [comment] 2023-04-19 01:08
One issue is that the word spacing implementation in `ParagraphImpl::applySpacingAndBuildClusterTable` currently operates only within each run.

The Hebrew and Arabic text in this example is split into separate runs for each word because the words and the spaces are mapped to different fonts.

@Rusino

**Comment by dickermoshe** [comment] 2023-04-19 04:14
Using a font that has explicit Hebrew/Arabic support works.
Thanks so much.
This can be used as a temporary fix.
See the following [dartpad](https://dartpad.dev/?id=2ac2f423d26bd7a12ecb26445e013323)
<img width="478" alt="image" src="https://user-images.githubusercontent.com/75931499/232965353-8a017fe7-63ad-49ab-8500-9fdfb6cf0e04.png">

**Comment by Rusino** [comment] 2024-02-08 18:41
I reproduced it in Skia. Working on it.

**Comment by Rusino** [comment] 2024-02-13 17:58
Fixed with https://skia-review.googlesource.com/c/skia/+/811817.

**Comment by dickermoshe** [comment] 2024-02-13 18:22
Awesome, thanks for the update!

**Closed** 2024-03-24 12:33 UTC
Labels: engine, dependency: skia, a: typography, has reproducible steps, P2, found in release: 3.7, found in release: 3.9, team-engine, triaged-engine
