### ISSUE TITLE
CRASH - Exception on Desktop (Win11) - "A KeyUpEvent is dispatched"

### ISSUE THREAD

**Issue by Agondev** [flutter/flutter#92538] opened 2021-10-27 01:53 UTC
Happened unexpectedly after **alt tabbing** back to app.

To reproduce:

1. Play around with Flutter app.
2. Hit alt tab.
3. Play around with unrelated random app
4. Hit alt tab to get back to Flutter app.
5. App crashes silently and force closes.

Stack trace following the crash 👇.

```
"[debug] Capture from onError 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#e98d6(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 1:37:11.219476)"

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#e98d6(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 1:37:11.219476)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
package:flutter/…/services/hardware_keyboard.dart:441
#3      HardwareKeyboard._assertEventIsRegular
package:flutter/…/services/hardware_keyboard.dart:452
#4      HardwareKeyboard.handleKeyEvent
package:flutter/…/services/hardware_keyboard.dart:543
#5      KeyEventManager.handleRawKeyMessage
package:flutter/…/services/hardware_keyboard.dart:821
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:73
#7      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:72
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:379
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:376
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#14     _invoke2 (dart:ui/hooks.dart:204:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
Lost connection to device.
Exited (sigterm)
```

Doctor:

```
PS C:\Users\Agone> flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.282], locale en-US)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (11 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Agone\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.61.2)
    • VS Code at C:\Users\Agone\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[✓] VS Code (version 1.62.0-insider)
    • VS Code at C:\Users\Agone\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • Redmi Note 5 (mobile) • 192.168.31.218:5556 • android-arm64 • Android 11 (API 30)
    • Windows (desktop)     • windows             • windows-x64   • Microsoft Windows [Version 10.0.22000.282]

• No issues found!
```

**Comment by dkwingsmt** [comment] 2021-11-08 19:23
(Reopening since it doesn't look like a duplicate.)

Hi @Agondev, can you see if it persists on the latest master? Also I want to confirm my reproduction step, which doesn't seem to trigger any errors on Win10:
1. Start an empty Flutter app
2. AltLeft-Tab out (and release all keys) 
3. AltLeft-Tab in
4. See if keyboard still works. (It does.)

**Comment by Agondev** [comment] 2021-11-09 01:28
Turns out it's actually pretty random. Seems to not make a difference if it's a new project or in-dev one. Can go for hours without this exception. (Still on stable channel, haven't switched to another.)

**Comment by dkwingsmt** [comment] 2021-11-09 02:19
Yeah, how much you have developed should not affect very much since it should mostly be a platform side bug. I'll recommend you to stick to the master channel (or beta at least) if you're mostly experimenting on desktop since we're still stabilizing it.

**Comment by Agondev** [comment] 2021-11-09 03:20
> Yeah, how much you have developed should not affect very much since it should mostly be a platform side bug.
> 
> What triggers it should be a combination of something, such as holding a key while switching apps and come back to press some other keys. That's what makes it rare.
> 
> Also I'll recommend you to stick to the master channel (or beta at least) if you're mostly experimenting on desktop since we're still stabilizing it.

Using stable for production mobile app dev, but debugging in desktop for the performance.

I'll switch to beta channel for now and see how that goes. Might take some time before there's anything to report back, though.

**Comment by dkwingsmt** [comment] 2021-11-09 03:42
Thank you. I'll close this issue for now, but feel free to reopen or file a new one if any error occurs.

**Closed by dkwingsmt** 2021-11-09 03:42 UTC
Labels: r: duplicate
