### ISSUE TITLE
ScrollController attached to multiple scroll views

### ISSUE THREAD

**Issue by iykeprince** [flutter/flutter#71946] opened 2020-12-08 21:50 UTC
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
Error from flutter tabbar

**Comment by pedromassangocode** [comment] 2020-12-09 07:57
Hi @iykeprince 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by hillelcoren** [comment] 2020-12-09 13:25
We've started seeing the same error with our app after upgrading to the latest Flutter dev release. 

We're using a ReorderableListView inside of a TabBarView which I think may be related as we use the ReorderableListView in other places in the app without an issue. I'll see I can create a reproduceable example.

**Comment by hillelcoren** [comment] 2020-12-09 14:20
It looks the problem happens when you have two Scaffolds on the screen, this used to work but sadly no longer does...

@Piinks any thoughts, maybe related to the scroll changes?

    return MaterialApp(
      home: Row(
        children: [
          Flexible(
            child: Scaffold(
              body: ReorderableListView(
                onReorder: (oldIndex, newIndex) => null,
                children: [
                  ListTile(
                    key: Key('item1'),
                    title: Text('Item 1'),
                  ),
                  ListTile(
                    key: Key('item2'),
                    title: Text('Item 2'),
                  ),
                ],
              ),
            ),
          ),
          Flexible(
            child: Scaffold(
              body: ReorderableListView(
                onReorder: (oldIndex, newIndex) => null,
                children: [
                  ListTile(
                    key: Key('item1'),
                    title: Text('Item 1'),
                  ),
                  ListTile(
                    key: Key('item2'),
                    title: Text('Item 2'),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );

**Comment by hillelcoren** [comment] 2020-12-09 14:34
Just to note... it looks like setting a controller for the ReorderableListView resolves the error

**Comment by Piinks** [comment] 2020-12-09 17:41
Thanks for the repro @hillelcoren!
This is due to the fact that the `ReorderableListView` uses the `PrimaryScrollController` if a controller has not been provided.
There used to be a `PrimaryScrollController` in each `Scaffold`, but https://github.com/flutter/flutter/pull/70893 moved it - there is now a `PrimaryScrollController` for each route. This change was made to enable default keyboard shortcuts.

To resolve, you can provide a `ScrollController` to the `ReorderableListView`, or place a `PrimaryScrollController` above each `ReorderableListView`. 

@darrenaustin is working on a new/updated `ReorderableListView`,  will it still use the `PrimaryScrollController` in this way?

**Comment by pedromassango** [comment] 2020-12-09 20:47
Duplicate of https://github.com/flutter/flutter/issues/71682.

**Comment by goderbauer** [comment] 2020-12-09 23:07
Closing as a duplicate per previous comment.

**Closed by goderbauer** 2020-12-09 23:07 UTC
Labels: f: scrolling, framework, in triage, waiting for customer response
