### ISSUE TITLE
Error handling 'serviceExtension' custom request: app 'db0a751c-64a2-4367-aa56-94319e9e948a' not found[tool_crash] StateError: Bad state: Cannot add event after closing

### ISSUE THREAD

**Issue by ecesevenay** [flutter/flutter#88034] opened 2021-08-11 12:56 UTC
Ok so I am new in Flutter programming and simply trying to debug an app but cannot see how it looks.

## Command
```
flutter run --machine --start-paused -d chrome --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9101/ --target lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Cannot add event after closing
```
#0      _StreamController.add (dart:async/stream_controller.dart:553:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:826:13)
#2      AppConnection.runMain (package:dwds/src/connections/app_connection.dart:33:22)
#3      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:669:25)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1110], locale tr-TR)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\pc\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio
    • Android Studio at \Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ android-studio-dir = \Program Files\Android\Android Studio
    ✗ Android Studio not found at \Program Files\Android\Android Studio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.59.0)
    • VS Code at C:\Users\pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03

**Comment by TahaTesser** [comment] 2021-08-12 09:28
Hi @ecesevenay 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/59757
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-12 09:28 UTC
Labels: in triage
