### ISSUE TITLE
[iOS] Missed frames in flutter 2.8+

### ISSUE THREAD

**Issue by wapchief** [flutter/flutter#95852] opened 2021-12-27 11:40 UTC
## Details

``run --release`` or  ``build ipa --release`` , and flutter sdk in 2.8+

Swipe up and down on your ios device at a slower speed , The problem arises.

We switched between three apps and  divices in iphonex,iphone12,iphone8, Will all have problems.

Eventually we switch Flutter SDK to 2.5

https://user-images.githubusercontent.com/20102206/147468725-61507042-79cb-4e1c-b6f5-65a9b42555aa.mov

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

```

</details>

**Comment by Ec7i9se** [comment] 2021-12-27 12:36
Same to me. Please check. I have a problem with Cupertino page route back transition. It's lagging and skips frames on 2.8, 2.9 betta. On 2.5 absolutely smooth. Video for demonstration with 2.5 build. Tested on iPhone 7 and 12 pro. All in release mode. If it's needed i can upload video with 2.8.

https://user-images.githubusercontent.com/39343708/147472150-7ec6bc15-849b-4469-9f46-aaf02df41bfa.mp4

**Comment by danagbemava-nc** [comment] 2021-12-28 13:58
Hi @wapchief, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample/repo that we can use to verify this. 

@Ec7i9se kindly file a new issue and provide the necessary information. 

Thank you

**Comment by nt4f04uNd** [comment] 2021-12-28 14:53
Duplicate of https://github.com/flutter/flutter/issues/95838

**Closed by nt4f04uNd** 2021-12-28 14:53 UTC
Labels: waiting for customer response, in triage
