### ISSUE TITLE
out/ios_release/clang_x64/gen_snapshot renamed to gen_snapshot_arm64?

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#49175] opened 2020-01-20 14:05 UTC
Did we rename `gen_snapshot`?

```
$ flutter --local-engine-src-path ~/flt/engine/src/ --local-engine ios_release run --release
Launching lib/main.dart on DartVM Team AAR iPod in release mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Automatically signing iOS for device deployment using specified development team in Xcode project: S8QB4VV633
Running Xcode build...                                                  
 ├─Building Dart code...                                    12.6s
Xcode build done.                                           13.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Building AOT snapshot in release mode (ios_release)...          

    Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for /Users/dacoharkes/flt/engine/src/out/ios_release/clang_x64/gen_snapshot_arm64.".

    A crash report has been written to /Users/dacoharkes/flt/engine/flutter/dev/integration_tests/ffi/flutter_04.log.

    This crash may already be reported. Check GitHub for similar crashes.

    https://git.io/JvICr


    To report your crash to the Flutter team, first read the guide to filing a bug.

    https://flutter.dev/docs/resources/bug-reports


    Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!

    https://git.io/JvI8h

    Failed to build /Users/dacoharkes/flt/engine/flutter/dev/integration_tests/ffi.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.
```

After doing `clang_x64 dacoharkes$ cp gen_snapshot gen_snapshot_arm64` it works fine.

This is HHH (flutter, engine, dart) from this morning.

I'm testing the tests in https://github.com/flutter/flutter/pull/46078.

**Comment by jmagman** [comment] 2020-02-12 02:41
Duplicate of https://github.com/flutter/flutter/issues/38933.

**Closed by jmagman** 2020-02-12 02:41 UTC
Labels: engine, team
