### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by echohunter20** [flutter/flutter#101678] opened 2022-04-11 03:02 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=3412459788000FL --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:45:36)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#5      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1077:32)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:316:5)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1310:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel beta, 2.12.0-4.2.pre, on Microsoft Windows [Version 10.0.19044.1586], locale zh-CN)
    • Flutter version 2.12.0-4.2.pre at E:\Android\FlutterSDK\flutter_windows_2.12.0-4.2.pre-beta\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c931b769b (12 days ago), 2022-03-29 10:49:29 -0500
    • Engine revision 486f4a749e
    • Dart version 2.17.0 (build 2.17.0-182.2.beta)
    • DevTools version 2.11.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at E:\Android\Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = E:\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\yangsanmei\AppData\Local\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio 15 生成工具 2017 15.9.41)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio 15 生成工具 2017 version 15.9.28307.1745
    • Windows 10 SDK version 10.0.17763.0
    ✗ Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2020.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (4 available)
    • V2164A (mobile)   • 3412459788000FL • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [Version 10.0.19044.1586]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 99.0.1150.46

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.7.0+32
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
### Plugins
android_intent-2.0.2
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info-2.0.3
fluttertoast-8.0.9
package_info-2.0.2
path_provider-2.0.8
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
permission_handler-8.3.0
share-2.0.4
shared_preferences-2.0.10
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.1
url_launcher-6.0.17
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-2.0.3
url_launcher_macos-2.0.3
url_launcher_web-2.0.9
url_launcher_windows-2.0.2
webview_flutter-3.0.0
webview_flutter_android-2.8.5
webview_flutter_wkwebview-2.7.2

**Comment by danagbemava-nc** [comment] 2022-04-11 11:30
Duplicate of #65021

**Closed by danagbemava-nc** 2022-04-11 11:30 UTC
Labels: in triage
