### ISSUE TITLE
camera package Windows Mac Linux web support 

### ISSUE THREAD

**Issue by rupamking1** [flutter/flutter#85688] opened 2021-07-01 09:18 UTC
can we use camera package Windows Mac Linux web

**Comment by stuartmorgan** [comment] 2021-07-01 10:51
Duplicate of https://github.com/flutter/flutter/issues/45297 https://github.com/flutter/flutter/issues/41709 https://github.com/flutter/flutter/issues/41710 and https://github.com/flutter/flutter/issues/41708

**Closed by stuartmorgan** 2021-07-01 10:51 UTC
