### ISSUE TITLE
Ios TextField limits the maximum length input Chinese pinyin bar will flash back

### ISSUE THREAD

**Issue by ztj666** [flutter/flutter#26407] opened 2019-01-11 03:47 UTC
Ios TextField限制最大长度输入汉字拼音栏超过会闪退

Google Translate: Ios TextField limits the maximum length input Chinese pinyin bar will flash back

**Comment by zoechi** [comment] 2019-01-11 07:00
Please add the output of `flutter doctor -v`.

Perhaps you can demonstrate the issue using https://github.com/flutter/flutter/wiki/Making-animated-GIFs-of-Flutter-apps

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by ztj666** [comment] 2019-01-12 02:17
> 请添加输出`flutter doctor -v`。
> 
> 也许你可以使用https://github.com/flutter/flutter/wiki/Making-animated-GIFs-of-Flutter-apps来证明这个问题[](https://github.com/flutter/flutter/wiki/Making-animated-GIFs-of-Flutter-apps)
> 
> 为了研究我们需要将最小的可运行再现
> 作为单个文件，以便我们可以将您的代码复制到`lib/main.dart`一个新项目中并运行以重现。

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16251034/51068031-32175f80-1653-11e9-9b6f-2b84c81025f0.gif)

**Comment by ztj666** [comment] 2019-01-12 03:04
Container(
        color: Colors.white,
        padding: EdgeInsets.all(15.0),
        child: new TextField(
          style: TextStyle(color: Colors.black87, fontSize: 15.0),
          decoration: new InputDecoration(
            hintText: "商品名称",
            hintStyle: new TextStyle(color: const Color(0xFF808080)),
          ),
          maxLines: 1,
          maxLength: 10,
          controller: _phoneController,
        ),
      ),

**Comment by kangwang1988** [comment] 2019-01-13 07:51
@ztj666 
Sorry, but it's not a minimal demo project to help reproduce this issue.
Besides, `flutter doctor -v` is missing.

**Comment by TomassMaximum** [comment] 2019-01-16 02:42
I came across the same issue. It happens when the TextField was limited to a certain length, like 200. After I typed 199 characters, the next input was a group which contains more than one character, eg. "字母", the app crashed. Here is the reported error from Xcode: 
2019-01-16 10:23:08.347422+0800 Runner[17156:722717] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {199, 1} out of bounds; string length 199'
*** First throw call stack:
(0x239010ec4 0x2381e1a40 0x238f17594 0x238f057ac 0x265d53a04 0x265d4307c 0x265d94b5c 0x265d9326c 0x265d93c44 0x265d43030 0x265d55128 0x102d487b8 0x102d49cbc 0x102d37588 0x102d55540 0x102d59610 0x102dad168 0x102d652c8 0x102d6877c 0x238fa1828 0x238fa1558 0x238fa0d8c 0x238f9bc68 0x238f9b1f0 0x23b214584 0x265f1f4c0 0x10250da84 0x238a5abb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

Flutter doctor output:
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G4015, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/chuangkegongchang/flutter/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/chuangkegongchang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • 大iPad • b32bb2c2456154a0c4cecd5a2c7d6da01ca49dd5 • ios • iOS 12.1.1

• No issues found!

**Comment by kangwang1988** [comment] 2019-01-16 06:44
@TomassMaximum 
Have you tried with the latest master?

**Comment by zoechi** [comment] 2019-02-12 07:52
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-02-12 07:52 UTC
Labels: a: text input, engine, framework, waiting for customer response

**Comment by FrunkPiano** [comment] 2020-10-21 07:30
try my flutter textfield plugin [custom_text_field](https://github.com/FrunkPiano/CustomTextField.git)
soleve the problem
