### ISSUE TITLE
[webview_flutter] File Upload not working with new refactored architecture

### ISSUE THREAD

**Issue by Shubhankt1** [flutter/flutter#108446] opened 2022-07-27 15:45 UTC
This is regarding the same issue as #27924

After the refactoring of the `webview_flutter` architecture, the old solution provided in https://github.com/flutter/plugins/pull/3225 for file upload to work in android stopped working.

I again tried to get it working in the new architecture based on the PR: https://github.com/flutter/plugins/pull/5172/files as mentioned by @danagbemava-nc [HERE](https://github.com/flutter/flutter/issues/102814#issuecomment-1117330354) but nothing worked again.

Is there any way I can roll back to older implementation? I am using `webview_flutter: ^2.0.4`, but seems like after I updated the `compileSdkVersion` to `31`, the new webview implementation came. Clearly, I cannot fallback to API 30 as Google Play Store won't accept it starting from Aug 2022.

I have already released the app to the production and clients are gonna be furious.

## Steps to Reproduce
1. Open a webview in Android and try to upload a file.

**Expected results:** 
File chooser intent should show.

**Actual results:** 
Nothing happens

**Comment by stuartmorgan** [comment] 2022-07-27 17:48
Closing as a duplicate of https://github.com/flutter/flutter/issues/27924

The issue tracker is specifically for bug reports and feature requests; the portion of this issue that is a feature request is tracked by the issue above. For help with your own project configuration (such as how to specify specific versions of packages), consider one of the resources list at https://flutter.dev/community#community-grid.

**Closed by stuartmorgan** 2022-07-27 17:48 UTC

**Comment by Shubhankt1** [comment] 2022-07-27 18:42
Hi, @stuartmorgan 
the issue is that even after updating the code as the mentioned PR, file upload still doesnt work and I've literally searched everywhere and nobody has an answer.

**Comment by stuartmorgan** [comment] 2022-07-27 18:51
Using code from in-progress PRs isn't something we support, so we can't help you here.
