### ISSUE TITLE
Cannot submit score to leaderboard with google_sign_in plugin

### ISSUE THREAD

**Issue by yum650350** [flutter/flutter#31799] opened 2019-04-29 19:01 UTC
Hi everyone, I'm in pain accessing play service.

I create a leaderboard and according to [Scores: list](https://developers.google.com/games/services/web/api/scores/list) I do
`GET https://www.googleapis.com/games/v1/leaderboards/$LEADERBOARD_ID/scores/PUBLIC?timeSpan=ALL_TIME`

It returns 
```
{
  kind: games#leaderboardScores, 
  numScores: 0
} 
```  
seems ok,
and after that I want to submit a score, so according to [Scores: submit](https://developers.google.com/games/services/web/api/scores/submit) I do 
`POST https://www.googleapis.com/games/v1/leaderboards/$LEADERBOARD_ID/scores?score=$score`    
but the response is
`code: 401, message: There is no linked app associated with this client ID.`

I've linked, re-linked, re-re-linked the app at Play Console but it does not work at all,
the same problem also appears at [Scores: get](https://developers.google.com/games/services/web/api/scores/get)
`GET https://www.googleapis.com/games/v1/players/$id/leaderboards/$LEADERBOARD_ID/scores/ALL_TIME` 
 
If someone knows how to solve this , I appreciate your help.

Btw here's my code:

```dart
import 'dart:convert';
import "package:http/http.dart" as http;
import 'package:google_sign_in/google_sign_in.dart';
import 'package:BallPhobia/playgames.dart';  
class PlayServices {
  static const LEADERBOARD_ID='MY_LEADERBOARD_ID';
  static final GoogleSignIn _googleSignIn = GoogleSignIn(signInOption: SignInOption.games,scopes: ['https://www.googleapis.com/auth/games']);
  static GoogleSignInAccount account;
  static Map<String, dynamic> userData;
  static Future singIn() async { 
      account = await _googleSignIn.signIn(); 
      final http.Response response = await http.get(
        'https://www.googleapis.com/games/v1/players/me',
        headers: await account.authHeaders,
      );
      userData = json.decode(response.body);
      print(userData);
  }
  
  static Future<ScoreResults> loadScores() async {
    final http.Response response = await http.get(
      'https://www.googleapis.com/games/v1/leaderboards/$LEADERBOARD_ID/scores/PUBLIC?timeSpan=ALL_TIME',
      headers: await account.authHeaders,
    );
    final Map<String, dynamic> data = json.decode(response.body); 
    print(data); 
  }

  // returns code: 401, message: There is no linked app associated with this client ID.
  static Future<ScoreResults> loadMyScores() async { 
  final id = userData['playerId'] ;
  final http.Response response = await http.get(
    'https://www.googleapis.com/games/v1/players/$id/leaderboards/$LEADERBOARD_ID/scores/ALL_TIME',
      headers: await account.authHeaders,
    );
    final Map<String, dynamic> data = json.decode(response.body);
    print(data); 
  }

 // returns code: 401, message: There is no linked app associated with this client ID.
  static Future writeScore(int score) async {  
    final http.Response response = await http.post(
      'https://www.googleapis.com/games/v1/leaderboards/$LEADERBOARD_ID/scores?score=$score',
      headers: await account.authHeaders,
    );
    final Map<String, dynamic> data = json.decode(response.body);
    print(data);
  }
}
```

**Comment by BondarenkoStas** [comment] 2019-10-16 12:59
@yum650350 did you manage to get it working?

**Comment by iapicca** [comment] 2019-11-08 09:56
Hi @yum650350   
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-08 09:56 UTC
Labels: waiting for customer response
