### ISSUE TITLE
[iOS]: When moving the cursor using keyboard, the Korean input does not start anew and is merged with the last input characters.

### ISSUE THREAD

**Issue by nero-angela** [flutter/flutter#98590] opened 2022-02-16 16:32 UTC
Problem when typing Korean in iOS TextField.
- This issue occurs in Korean.
- Occurs both on the iOS emulator and on the actual device.

## Steps to Reproduce 1
1. Enter `아`.
2. Move the cursor forward `아`.
3. Enter `ㄴ`.
4. It is entered as `안아` instead of `ㄴ아`.

## Steps to Reproduce 2
1. Enter `ㅅ`.
2. Move the cursor forward `ㅅ`.
3. Enter `ㅅ` again.
4. It is entered as `ㅆㅅ` instead of `ㅅㅅ`.

## Steps to Reproduce 3
1. Enter `ㅁ`.
2. Move the cursor forward `ㅁ`.
3. Enter `ㅁ` again.
4. It is entered as `ㅁㅁ`. There is no problem because `ㅅㅅ` can be combined with `ㅆ`, but `ㅁㅁ` cannot be combined in korean.

## Steps to Reproduce 4
1. Type `-`.
2. Move the cursor forward of `-`.
3. Enter `아`.
4. Moves the cursor back to `-`.
5. Enter `ㄴ`.
5. If is entered as `아안` instead of `아-ㄴ`. The `-` also disappears and the character string is entered incorrectly.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: EdgeInsets.all(8.0),
            child: TextField(),
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel unknown, 2.11.0-0.0.pre.542, on macOS 12.0.1 21A559 darwin-x64, locale
    ko-KR)
    • Flutter version 2.11.0-0.0.pre.542 at /Users/nero/Project/FlutterContribution/flutter
    • Upstream repository unknown
    • Framework revision 1958656943 (2 days ago), 2022-02-14 05:15:17 -0500
    • Engine revision b63614c306
    • Dart version 2.17.0 (build 2.17.0-104.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nero/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Volumes/Lecture HD/Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Volumes/Lecture HD/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] VS Code (version 1.63.2)
    • VS Code at /Volumes/Lecture HD/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • nero의 iPad (mobile) • 00008027-000A41CE0C0A402E            • ios            • iOS 14.6
      18F72
    • iPhone 13 (mobile)  • 2A06E0D7-FBAB-4FBD-AFA9-34FB720E1B61 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)        • chrome                               • web-javascript • Google Chrome
      98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by nero-angela** [comment] 2022-02-17 08:11
@darshankawar 
Sorry for the lack of explanation.
I thought while shooting the video, there is no problem when the cursor is moved by touching the TextField when the app is first launched on iOS, but the problem occurs after moving the cursor using the keyboard.
| video1 | video2 |
|:--:|:--:|
| <video src="https://user-images.githubusercontent.com/26322627/154432093-b6e1c5a5-7ddb-4b8d-af2d-0445ba50eb92.MP4" /> | <video src="https://user-images.githubusercontent.com/26322627/154432133-1071b761-9d61-43c0-b804-c088b0bc59f2.MP4"/> |

**Comment by darshankawar** [comment] 2022-02-17 13:17
> Can you also check if this issue is similar / related to your case, ? #96209

@nero-angela Can you confirm this too that this is or isn't related to your current case ?

**Comment by nero-angela** [comment] 2022-02-17 13:57
@darshankawar 
It's not exact, but it seems to be related in that Korean input behavior is different from other languages.
In iOS, when moving the cursor to the keyboard, the input does not start anew and is merged with the last input characters, which seems to cause a problem.

**Comment by darshankawar** [comment] 2022-02-18 06:05
Thanks for the details. With that, I was able to replicate the behavior reported. The main thing to note while replicating this is to move the cursor using keyboard and not tapping before and after the character.

<img width="349" alt="Screenshot 2022-02-18 at 11 29 03 AM" src="https://user-images.githubusercontent.com/67046386/154627186-09b9efdc-3b9d-44aa-87d6-f962588f80da.png">
<img width="350" alt="Screenshot 2022-02-18 at 11 29 10 AM" src="https://user-images.githubusercontent.com/67046386/154627191-11e5ab07-ea80-4c6d-8990-d4c4a5968baa.png">


<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.11.0-0.0.pre.612, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.612 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c50b02f2c3 (60 minutes ago), 2022-02-17 22:44:23 -0500
    • Engine revision 605454e201
    • Dart version 2.17.0 (build 2.17.0-118.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>


I'll try to check on Android too if the same behavior occurs or not to confirm whether this is iOS specific issue or not. For now, I'll label it as `platform-ios`.

**Comment by jmagman** [comment] 2022-02-18 19:15
@cbracken might have context.

**Comment by cbracken** [comment] 2022-04-26 00:06
@jmagman missed this earlier. In Korean input mode, input goes something like this:
1. START: empty composing range, collapsed selection at (0,0)
2. User presses a key: composing range contains that character (0,1), collapsed selection at (1,1)
3. User presses another key:
   1. If the key pressed can be merged into the character being composed, it is, and the composing range remains (0,1) but its contents are updated, selection remains (1,1)
   2. If the key pressed cannot be merged into the character being composed, the composing region is committed, and composing is immediately continued at (1,2) which contains the new character being worked on. The collapsed selection is updated to (2,2).
   3. If the user presses an arrow key, the composing range is committed and becomes empty, the collapsed selection is updated to the new cursor position.

What's going on in this bug is that final scenario in step 3. If I were to guess, it sounds like what's going on is that iOS has committed the mark range (composing range) and moved the cursor, so the engine state is _probably_ updated, but we're not sending an update to the framework with the new text (which is unchanged) and composing range (which will be changed).

**Comment by LongCatIsLooong** [comment] 2022-04-26 17:13
This is caused by adding `UITextInteraction` to the input view in `beginFloatingCursorAtPoint`.

**Closed** 2022-04-28 16:44 UTC
Labels: a: text input, platform-ios, framework, engine, a: internationalization, a: typography, has reproducible steps, P4, found in release: 2.10, found in release: 2.11
