### ISSUE TITLE
 failed for task ':firebase_core_web:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by Ghaliah-f** [flutter/flutter#83161] opened 2021-05-22 06:43 UTC
This when running this command: flutter create bug
<--Creating project bug...
  bug/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  bug/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  bug/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  bug/ios/Runner/Info.plist (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  bug/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  bug/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  bug/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  bug/ios/Runner/Base.lproj/Main.storyboard (created)
  bug/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  bug/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  bug/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  bug/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  bug/ios/Flutter/Debug.xcconfig (created)
  bug/ios/Flutter/Release.xcconfig (created)
  bug/ios/Flutter/AppFrameworkInfo.plist (created)
  bug/ios/.gitignore (created)
  bug/test/widget_test.dart (created)
  bug/bug.iml (created)
  bug/.gitignore (created)
  bug/web/favicon.png (created)
  bug/web/index.html (created)
  bug/web/manifest.json (created)
  bug/web/icons/Icon-192.png (created)
  bug/web/icons/Icon-512.png (created)
  bug/.metadata (created)
  bug/macos/Runner.xcworkspace/contents.xcworkspacedata (created)
  bug/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  bug/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png (created)
  bug/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png (created)
  bug/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png (created)
  bug/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png (created)
  bug/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png (created)
  bug/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png (created)
  bug/macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  bug/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png (created)
  bug/macos/Runner/DebugProfile.entitlements (created)
  bug/macos/Runner/Base.lproj/MainMenu.xib (created)
  bug/macos/Runner/MainFlutterWindow.swift (created)
  bug/macos/Runner/Configs/Debug.xcconfig (created)
  bug/macos/Runner/Configs/Release.xcconfig (created)
  bug/macos/Runner/Configs/Warnings.xcconfig (created)
  bug/macos/Runner/Configs/AppInfo.xcconfig (created)
  bug/macos/Runner/AppDelegate.swift (created)
  bug/macos/Runner/Info.plist (created)
  bug/macos/Runner/Release.entitlements (created)
  bug/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  bug/macos/Runner.xcodeproj/project.pbxproj (created)
  bug/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  bug/macos/Flutter/Flutter-Debug.xcconfig (created)
  bug/macos/Flutter/Flutter-Release.xcconfig (created)
  bug/macos/.gitignore (created)
  bug/android/app/src/profile/AndroidManifest.xml (created)
  bug/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  bug/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  bug/android/app/src/main/res/drawable/launch_background.xml (created)
  bug/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  bug/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  bug/android/app/src/main/res/values-night/styles.xml (created)
  bug/android/app/src/main/res/values/styles.xml (created)
  bug/android/app/src/main/res/drawable-v21/launch_background.xml (created)
  bug/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  bug/android/app/src/main/AndroidManifest.xml (created)
  bug/android/app/src/debug/AndroidManifest.xml (created)
  bug/android/gradle/wrapper/gradle-wrapper.properties (created)
  bug/android/gradle.properties (created)
  bug/android/.gitignore (created)
  bug/android/settings.gradle (created)
  bug/android/app/build.gradle (created)
  bug/android/app/src/main/kotlin/com/example/bug/MainActivity.kt (created)
  bug/android/build.gradle (created)
  bug/android/bug_android.iml (created)
  bug/pubspec.yaml (created)
  bug/README.md (created)
  bug/ios/Runner/Runner-Bridging-Header.h (created)
  bug/ios/Runner/AppDelegate.swift (created)
  bug/ios/Runner.xcodeproj/project.pbxproj (created)
  bug/lib/main.dart (created)
  bug/analysis_options.yaml (created)
  bug/.idea/runConfigurations/main_dart.xml (created)
  bug/.idea/libraries/Dart_SDK.xml (created)
  bug/.idea/libraries/KotlinJavaRuntime.xml (created)
  bug/.idea/modules.xml (created)
  bug/.idea/workspace.xml (created)
Running "flutter pub get" in bug...                              2,264ms
Wrote 105 files.

All done!
In order to run your application, type:

  $ cd bug
  $ flutter run

Your application code is in bug/lib/main.dart.>

```
```

output command flutter doctor -v:
[✓] Flutter (Channel master, 2.3.0-13.0.pre.59, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.3.0-13.0.pre.59 at /Users/macbook/Develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1e35f4c0c6 (2 days ago), 2021-05-20 03:14:01 -0400
    • Engine revision 67c537d41b
    • Dart version 2.14.0 (build 2.14.0-129.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.54.3)
    • VS Code at /Users/macbook/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

when run a project this output
Using hardware rendering with device Android SDK built for x86. If you notice graphics artefacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
/Users/macbook/Develop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/android/src/main/java/io/flutter/plugins/firebase_core_web/FirebaseCoreWebPlugin.java:7: error: FirebaseCoreWebPlugin is not abstract and does not override abstract method onDetachedFromEngine(FlutterPluginBinding) in FlutterPlugin
public class FirebaseCoreWebPlugin<FlutterPluginBinding> implements FlutterPlugin {
       ^
/Users/macbook/Develop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/android/src/main/java/io/flutter/plugins/firebase_core_web/FirebaseCoreWebPlugin.java:8: error: method does not override or implement a method from a supertype
  @Override
  ^
**/Users/macbook/Develop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/android/src/main/java/io/flutter/plugins/firebase_core_web/FirebaseCoreWebPlugin.java:13: error: method does not override or implement a method from a supertype
  @Override**
  ^
**Note: /Users/macbook/Develop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/android/src/main/java/io/flutter/plugins/firebase_core_web/FirebaseCoreWebPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_core_web:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Running Gradle task 'assembleDebug'...                              5.0s
Exception: Gradle task assembleDebug failed with exit code 1

The problem I have the same error in FirebaseCoreWebPlugin.java

**Comment by TahaTesser** [comment] 2021-05-24 09:53
Hi @Ghaliah-f 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-24 09:53 UTC
Labels: in triage
