### ISSUE TITLE
smoke_catalina_hot_mode_dev_cycle_ios__benchmark_hotReloadMillisecondsToFrameAfterChange regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#51412] opened 2020-02-25 15:59 UTC
May be https://github.com/flutter/flutter/pull/49405. 
![Screenshot 2020-02-25 at 07 58 06](https://user-images.githubusercontent.com/1435716/75264673-9d16ed80-57a4-11ea-9d57-07939d89c785.png)

smoke_catalina_hot_mode_dev_cycle_ios__benchmark_hotRestartMillisecondsToFrame shows a similar regression around the same commit:

**Comment by jonahwilliams** [comment] 2020-02-25 16:55
The first regression happened on https://github.com/flutter/flutter/commit/1d4667bb3835079276246e8695ea12b657b4493f for `hotRestartMillisecondsToFrame`, which leads me to believe its a device issue. Also, there were no regressions on other platforms. I'll be OOO today, so if this is blocking anything please revert. Otherwise I'll take a look on Wednesday

**Comment by jonahwilliams** [comment] 2020-02-26 15:40
I landed a revert of the PR in question and the benchmark did not noticeably improve.


![2020-02-26](https://user-images.githubusercontent.com/8975114/75360851-3d374a00-586b-11ea-84fc-6a4ed9c39e86.png)

I think this is an issue with the machine in question. Adding @godofredoc for infra triage

**Comment by godofredoc** [comment] 2020-02-26 16:26
In general catalina machines performance degrades ~after a week. In most cases killing usbmux fixes the problem but there are some other cases when only rebooting the machines fixes the issue.

For now I'll reboot the catalina machines

**Comment by godofredoc** [comment] 2020-02-27 03:30
Duplicate of https://github.com/flutter/flutter/issues/45112

**Closed** 2020-02-27 03:30 UTC
Labels: severe: performance, severe: regression, tool, ‎‍💻platform-catalina
