### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Could not resolve package dependencies:  Packages are not supported when using legacy build locations, but the current project has them enabled.  Command: /usr/bin/xcodebuild -list

### ISSUE THREAD

**Issue by rllanos2310** [flutter/flutter#59721] opened 2020-06-17 23:01 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled.
  Command: /usr/bin/xcodebuild -list
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:389:50)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:108:78)
#4      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:83:43)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#13     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
```
```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale es-PE)
    • Flutter version 1.17.2 at /Users/rogeliollanos/development/flutter
    • Framework revision 5f21edf8b6 (3 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rogeliollanos/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.2.5
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: cc949a8e8b9cf394b9290a8e80f87af3e207dce5
### Plugins
connectivity-0.4.8+6
connectivity_macos-0.1.0+3
contacts_service-0.4.6
facebook_app_events-0.6.0
firebase_analytics-5.0.14
firebase_in_app_messaging-0.1.2
flutter_plugin_android_lifecycle-1.0.8
flutter_secure_storage-3.3.3
flutter_segment-2.1.0
flutter_statusbarcolor-0.2.3
geolocator-5.3.1
google_api_availability-2.0.4
google_maps_flutter-0.5.28+1
image_picker-0.6.7
location_permissions-2.0.5
native_device_orientation-0.3.0
package_info-0.4.0+18
path_provider-1.6.9
path_provider_macos-0.0.4+3
permission_handler-4.4.0+hotfix.4
qr_mobile_vision-1.0.1+1
share-0.6.4+3
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+9
shared_preferences_web-0.1.2+7
sqflite-1.3.0+2
url_launcher-5.4.10
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6
video_player-0.10.11+1
video_player_web-0.1.3+1
webview_flutter-0.3.22+1

**Comment by jmagman** [comment] 2020-06-23 21:04
Duplicate of https://github.com/flutter/flutter/issues/57083.

**Closed by jmagman** 2020-06-23 21:04 UTC
Labels: a: build, platform-ios, severe: crash, tool
