### ISSUE TITLE
[google_sign_in] Assuming wrong credentials when performing sign in flow

### ISSUE THREAD

**Issue by ggirotto** [flutter/flutter#86348] opened 2021-07-13 13:46 UTC
The `google_sign_in` SDK seems to assume credentials that were already used to login in another app in the same device and it automatically fails with 403 error, not even letting the user sign in with a different account.

I'm not sure how can I provide a demo example without providing my own `GoogleServices-Info.plist` - although it's a public file I'm not sure if it's ok to share it publicly here in the issue - so I'll record a video trying to demonstrate the issue:

Steps:
1 - Sign in in a completely different application;
2- Tries to sign in on the application with organization restrictions;
3- The sign in flow fails.

Demo:

https://user-images.githubusercontent.com/11745745/125462341-24dafa88-53f6-4c96-995e-e79c843658de.mp4

Important Notes:
- The second app - Elefante Letrado - has organization restrictions to only allow users with the suffix `@educar.rs.gov.be` to authenticate in the app. It uses Google Classroom API to authenticate students;
- The seconds app is using parametrized `clientId`:
```dart
final userGoogleAccount = await GoogleSignIn(
                    clientId: <CLIENT_ID>,
                    scopes: ['email', 'https://www.googleapis.com/auth/classroom.courses.readonly'],
                  ).signIn();
```

If there's anything that I can do to help this issue demonstration, please let me know.

This issue is possible related with:
- https://github.com/flutter/flutter/issues/86049;
- https://stackoverflow.com/questions/65821740/google-api-oauth-2-sign-in-something-went-wrong-with-new-oauth-2-client

**Comment by TahaTesser** [comment] 2021-07-14 10:18
Hi @ggirotto 
I just tried the snippet you provided on iOS, when I login into another app and then log in to a Flutter app, I have been presented with an option to choose an account even if I have a single Google Account, running on iOS 14.6. Since I can choose to login (in your case, it automatically assumes you wanna log in to the account used in another app) and I can choose to log in with that and try different as an account be could be restricted or not part of the organization, which makes the not reproducible for me.


<details> 
<summary>minimal code sample</summary> 

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'dart:convert' show json;

import "package:http/http.dart" as http;
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  // Optional clientId
  // clientId: '479882132969-9i9aqik3jfjd7qhci1nqf0bm2g71rm1u.apps.googleusercontent.com',
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() {
  runApp(
    MaterialApp(
      title: 'Google Sign In',
      home: SignInDemo(),
    ),
  );
}

class SignInDemo extends StatefulWidget {
  @override
  State createState() => SignInDemoState();
}

class SignInDemoState extends State<SignInDemo> {
  GoogleSignInAccount? _currentUser;
  String _contactText = '';

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount? account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        _handleGetContact(_currentUser!);
      }
    });
    _googleSignIn.signInSilently();
  }

  Future<void> _handleGetContact(GoogleSignInAccount user) async {
    setState(() {
      _contactText = "Loading contact info...";
    });
    final http.Response response = await http.get(
      Uri.parse('https://people.googleapis.com/v1/people/me/connections'
          '?requestMask.includeField=person.names'),
      headers: await user.authHeaders,
    );
    if (response.statusCode != 200) {
      setState(() {
        _contactText = "People API gave a ${response.statusCode} "
            "response. Check logs for details.";
      });
      print('People API ${response.statusCode} response: ${response.body}');
      return;
    }
    final Map<String, dynamic> data = json.decode(response.body);
    final String? namedContact = _pickFirstNamedContact(data);
    setState(() {
      if (namedContact != null) {
        _contactText = "I see you know $namedContact!";
      } else {
        _contactText = "No contacts to display.";
      }
    });
  }

  String? _pickFirstNamedContact(Map<String, dynamic> data) {
    final List<dynamic>? connections = data['connections'];
    final Map<String, dynamic>? contact = connections?.firstWhere(
      (dynamic contact) => contact['names'] != null,
      orElse: () => null,
    );
    if (contact != null) {
      final Map<String, dynamic>? name = contact['names'].firstWhere(
        (dynamic name) => name['displayName'] != null,
        orElse: () => null,
      );
      if (name != null) {
        return name['displayName'];
      }
    }
    return null;
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

  Future<void> _handleSignOut() => _googleSignIn.disconnect();

  Widget _buildBody() {
    GoogleSignInAccount? user = _currentUser;
    if (user != null) {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          ListTile(
            leading: GoogleUserCircleAvatar(
              identity: user,
            ),
            title: Text(user.displayName ?? ''),
            subtitle: Text(user.email),
          ),
          const Text("Signed in successfully."),
          Text(_contactText),
          ElevatedButton(
            child: const Text('SIGN OUT'),
            onPressed: _handleSignOut,
          ),
          ElevatedButton(
            child: const Text('REFRESH'),
            onPressed: () => _handleGetContact(user),
          ),
        ],
      );
    } else {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          const Text("You are not currently signed in."),
          ElevatedButton(
            child: const Text('SIGN IN'),
            onPressed: _handleSignIn,
          ),
        ],
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Google Sign In'),
        ),
        body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: _buildBody(),
        ));
  }
}

``` 

</details>

Given the information above and your video, you automatically get logged in without able to use another Google Account. Can you please try clearing Safari browsing data and repeat the Login flow and also provide which iOS version you're using and most importantly make sure you're latest `google_sign_in`

**Comment by ggirotto** [comment] 2021-07-14 20:26
Hey @TahaTesser thanks for the feedback. I was able to reproduce the issue on an iOS simulator 14.5 and physical device running iOS 14.6 using `google_sign_in` version `5.0.4`.

> Can you please try clearing Safari browsing data and repeat the Login flow

I'm reseting the simulator settings every time I do the sign in workflow in Device -> Erase all content and settings. I understand that the DEMO video I've provided is not enough information to reproduce the issue, so I'm trying to reproduce by creating two demo firebase project were I can safely share the `GoogleService-Info.plist` with you.

I was thinking if it could be something related with Google Classroom integration, since the second app (Elefante Letrado) has an integration with this API (and possibly is why the modal presents `org_internal` error). I'll keep trying to create a reproducible demo so we can proceed with this issue debugging, otherwise we will have just hypothesis about what could be happening

**Comment by TahaTesser** [comment] 2021-07-15 07:23
Hi @ggirotto 
If it narrows down to classroom API,  let me know as soon as you've more information

**Comment by ggirotto** [comment] 2021-07-15 17:18
@TahaTesser I could successfully made a demo reproducing the issue but using our google project, which is linked with Google Classroom API. I'm with some difficult to create a similar demo project linked with the Classroom API, so I would like to ask if there's a private channel where I can send you the demo using our project `clientId` so you can reproduce the issue I'm facing.

**Comment by TahaTesser** [comment] 2021-07-16 07:20
@ggirotto
You can simply provide minimal code sample and steps to reproduce the issue with steps tp enable those API if the issue reproduces because of it.

**Comment by ggirotto** [comment] 2021-07-27 18:04
@TahaTesser It took me some time, but I finally could reproduce the issue. I'll try to be more descriptive as possible.

The issue seems to be related with Google oAuth consent screen. When trying to sign in in an app that has "User Type" configured to be "Internal" with any kind of restriction, the SDK tries to assume the current logged in account but, since it doesn't satisfy the new login restrictions, it shows the restriction page without letting the user logout or choose a different account.

I could reproduce the issue by creating two different projects
- "External Demo": This project has normal oAuth sign in configured using Firebase; 
- "Internal Demo": This project has content screen restrictions and is marked as "Internal", adding restrictions about the available domains that can be used to sign in in the application.

So basically, the steps that I did to reproduce the issue are:
1. Clone `google_sign_in` example project.
2. Create a new project in Firebase named "External" (this is the project without restrictions)
3. Go to Authentication and enable Google Sign In
4. Create a new iOS app adding its bundle identifier `com.example.external` or something like that
5. Download `GoogleService-Info.plist` and add it to the example project of `google_sign_in`.
6. Updates `Info.plist` from example project with the `REVERSED_CLIENT_ID` from previously downloaded `GoogleService-Info.plist`.

This is the "External" project. Now lets create the Internal one. The steps are similar, but it has a few extra configurations in Google Cloud Platfom:

1. Clone `google_sign_in` example project (again)
2. Update the iOS example bundle identifier, to it be recognized as a different app
3. Create a new project in Firebase named "External" (this is the project without restrictions)
4. Go to Authentication and enable Google Sign In
5. Go to Google Cloud Platform -> API -> oAuth Content Screen
6. Configure `User Type` to `Internal` and adds a domain restriction (in my case, I added `educar.rs.gov.br` as the allowed domains to sign in).
7. Save the project settings
8. Create a new iOS app in Firebase adding its bundle identifier `com.example.internal` or something like that
9. Download `GoogleService-Info.plist` and add it to the example project of `google_sign_in`.
10. Updates `Info.plist` from example project with the `REVERSED_CLIENT_ID` from previously downloaded `GoogleService-Info.plist`.

Now there are 2 apps configured in Firebase to use Google Sign In, the first without restrictions and the second with domain restrictions set to users with email ending with `educar.rs.gov.br`. There are also two example flutter apps, each one configured to use a different Firebase project. Now, to reproduce the issue, follow the steps:

1. Run the **External** app first (less restrictive) and sign in with any account. It should complete the sign in flow normally.
2. Close the app
3. Run the **Internal** app (with domain restriction) and taps "Sign In""
4. You should see a blocking page that doesn't allow the user to chose which account to sign in.

These are the steps I've made to reproduce the issue. I'll also attach to this response a video reproducing the bug and the code I've used to reproduce it (including both `GoogleService-Info.plist` from the demo projects I've created to reproduce it). If necessary, I can add you as a contributor to both Google/Firebase projects.

I hope this information is enough to simulate the issue. If you need anything else please let me know!

[google_sign_in_example.zip](https://github.com/flutter/flutter/files/6887681/google_sign_in_example.zip)

OBS: Both projects (external and internal) are in the respective folders `google_sign_in_external` and `google_sign_in_internal`)
OBS2: I've made the tests in an iOS Simulator running iOS 14.5 and reseted (Device -> Erase all content and settings)


https://user-images.githubusercontent.com/11745745/127205065-de0311f4-81e5-4bf2-b560-481158ff49f2.mp4

**Comment by TahaTesser** [comment] 2021-07-28 07:48
Hi @ggirotto 
That's a great investigation, I am glad you were able to figure out the cause but the OAuth is simply involved by Google APIs, the steps you provided, at least to me, don't make it sound like it is the package issue, package only invokes the google sign in now, it doesn't implement this by itself,  rather than Google 0Auth. 

Since you have the firebase setup for this test, Is it possible, you can replicate this issue using a regular native iOS App? It only needs to have one button to log in and see if you can see the login flow issue.

Let me know how it goes

**Comment by ggirotto** [comment] 2021-07-28 15:02
Hey @TahaTesser , I'll implement using native iOS but, if it doesn't relates to the package, where can I report this situation?

**Comment by TahaTesser** [comment] 2021-07-29 06:46
Hi @ggirotto 
That's a good question, I am not really, it has gotta be it somewhere on https://console.cloud.google.com/, first, we need to make sure it is not the package, let me know how results with the native test

Thank you

**Comment by ggirotto** [comment] 2021-07-29 14:30
Hey @TahaTesser , finished both demos with native projects. I'll attach both projects source code and demo video below. Please let me know the next steps.

[iOS Demos.zip](https://github.com/flutter/flutter/files/6901275/iOS.Demos.zip)


https://user-images.githubusercontent.com/11745745/127510235-6a9eef02-6901-4cf4-8996-cce5f23b4507.mp4

**Comment by TahaTesser** [comment] 2021-07-30 07:07
Hi @ggirotto 
Thanks so much for the native test, looks you get the same results in the native iOS too? If I am not mistaken
Since this is the same behaviour without using `google_sign_in`, (which simply invokes Google APIs)
If you agree, I will close the issue and probably file an issue here https://issuetracker.google.com/savedsearches/559662, it has OAuth issues, for [example](https://issuetracker.google.com/issues/35907249)

**Comment by ggirotto** [comment] 2021-07-30 13:57
Hey @TahaTesser , I've created https://issuetracker.google.com/issues/195021096 and further information will be shared there. I think this issue can be closed since it doesn't belong to the SDK scope. Thanks for the help.

**Comment by TahaTesser** [comment] 2021-08-02 07:09
Hi @ggirotto 
Thanks, hope you get this resolved, closing

**Closed by TahaTesser** 2021-08-02 07:09 UTC
Labels: in triage
