### ISSUE TITLE
licenses.dart': Failed assertion: line 158: 'result.text.trimLeft()

### ISSUE THREAD

**Issue by zocker1996** [flutter/flutter#15436] opened 2018-03-12 12:29 UTC
I didn't like the look of the license page so I decided to build my own.
First I obtained a list of all LicenseEntry and then showed them using ListView.builder.
There are by default 539 license entries. This is quite a big amount, even if some of them like boringssl are listed multiple times. The year of the copyright is different but because of that the licenses are treated as different entries. I can't scroll down to the last element, after several licenses with the title 'icu' the following exception told me to open an issue here:

```
 ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4018): The following assertion was thrown during performLayout():
I/flutter ( 4018): 'package:flutter/src/foundation/licenses.dart': Failed assertion: line 158: 'result.text.trimLeft()
I/flutter ( 4018): == result.text': is not true.
I/flutter ( 4018): 
I/flutter ( 4018): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4018): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4018): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4018):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4018): 
I/flutter ( 4018): When the exception was thrown, this was the stack:
I/flutter ( 4018): #2      LicenseEntryWithLineBreaks.paragraphs.getParagraph (package:flutter/src/foundation/licenses.dart:158)
I/flutter ( 4018): #3      LicenseEntryWithLineBreaks.paragraphs (package:flutter/src/foundation/licenses.dart:202)
I/flutter ( 4018): #4      _SyncIterator.moveNext (dart:core-patch/dart:core/core_patch.dart:153)
I/flutter ( 4018): #5      _MyLicensePageState._entryTileBuilder (file:///C:/Users/Zocker/android_studio/my_app/lib/MyLicensePage.dart:114)
I/flutter ( 4018): #6      _MyLicensePageState._afterLoading.<anonymous closure> (file:///C:/Users/Zocker/android_studio/my_app/lib/MyLicensePage.dart:99)
I/flutter ( 4018): #7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:197)
I/flutter ( 4018): #8      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:716)
I/flutter ( 4018): #9      _HashMap.putIfAbsent (dart:collection-patch/dart:collection/collection_patch.dart:143)
I/flutter ( 4018): #10     SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:716)
I/flutter ( 4018): #11     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729)
I/flutter ( 4018): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205)
I/flutter ( 4018): #13     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722)
I/flutter ( 4018): #14     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254)
I/flutter ( 4018): #15     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666)
I/flutter ( 4018): #16     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740)
I/flutter ( 4018): #17     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666)
I/flutter ( 4018): #18     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243)
I/flutter ( 4018): #19     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:411)
I/flutter ( 4018): #20     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190)
I/flutter ( 4018): #21     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233)
I/flutter ( 4018): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 4018): #23     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182)
I/flutter ( 4018): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 4018): #25     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285)
I/flutter ( 4018): #26     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1008)
I/flutter ( 4018): #27     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:932)
I/flutter ( 4018): #28     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445)
I/flutter ( 4018): #29     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709)
I/flutter ( 4018): #30     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270)
I/flutter ( 4018): #31     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622)
I/flutter ( 4018): #32     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
I/flutter ( 4018): #33     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter ( 4018): #34     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter ( 4018): #35     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
I/flutter ( 4018): #36     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
I/flutter ( 4018): #37     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter ( 4018): (elided 2 frames from class _AssertionError)
I/flutter ( 4018): 
I/flutter ( 4018): The following RenderObject was being processed when the exception was fired:
I/flutter ( 4018):   RenderSliverList#d8c5f relayoutBoundary=up2
I/flutter ( 4018):   creator: SliverList ← MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter ( 4018):   IgnorePointer-[GlobalKey#8af2d] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 4018):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#7cf80] ←
I/flutter ( 4018):   _ExcludableScrollSemantics-[GlobalKey#645be] ← RepaintBoundary ← ⋯
I/flutter ( 4018):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter ( 4018):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward,
I/flutter ( 4018):   ScrollDirection.reverse, scrollOffset: 22117.2, remainingPaintExtent: 592.0, crossAxisExtent:
I/flutter ( 4018):   360.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 592.0)
I/flutter ( 4018):   geometry: SliverGeometry(scrollExtent: 31813.0, paintExtent: 592.0, maxPaintExtent: 31813.0,
I/flutter ( 4018):   hasVisualOverflow: true)
I/flutter ( 4018):   currently live children: 377 to 387
I/flutter ( 4018): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 4018):   RenderRepaintBoundary#6c767 relayoutBoundary=up3
I/flutter ( 4018):     RenderDecoratedBox#f7c50 relayoutBoundary=up4
I/flutter ( 4018):       RenderDecoratedBox#52f51 relayoutBoundary=up5
I/flutter ( 4018):         RenderPadding#64ce0 relayoutBoundary=up6
I/flutter ( 4018):           RenderFlex#51a87 relayoutBoundary=up7
I/flutter ( 4018):   RenderRepaintBoundary#d3a8b relayoutBoundary=up3
I/flutter ( 4018):     RenderDecoratedBox#dcf16 relayoutBoundary=up4
I/flutter ( 4018):       RenderDecoratedBox#f37b7 relayoutBoundary=up5
I/flutter ( 4018):         RenderPadding#27c74 relayoutBoundary=up6
I/flutter ( 4018):           RenderFlex#cb8ed relayoutBoundary=up7
I/flutter ( 4018):   RenderRepaintBoundary#240d3 relayoutBoundary=up3
I/flutter ( 4018):     RenderDecoratedBox#1f482 relayoutBoundary=up4
I/flutter ( 4018):       RenderDecoratedBox#da4bb relayoutBoundary=up5
I/flutter ( 4018):         RenderPadding#077c2 relayoutBoundary=up6
I/flutter ( 4018):           RenderFlex#2e960 relayoutBoundary=up7
I/flutter ( 4018):   RenderRepaintBoundary#fee98 relayoutBoundary=up3
I/flutter ( 4018):     RenderDecoratedBox#5ab1d relayoutBoundary=up4
I/flutter ( 4018):       RenderDecoratedBox#6e6dc relayoutBoundary=up5
I/flutter ( 4018):         RenderPadding#eab07 relayoutBoundary=up6
I/flutter ( 4018):           RenderFlex#db182 relayoutBoundary=up7
I/flutter ( 4018):   RenderRepaintBoundary#8cd10 relayoutBoundary=up3
I/flutter ( 4018):     RenderDecoratedBox#3866c relayoutBoundary=up4
I/flutter ( 4018):       RenderDecoratedBox#a0622 relayoutBoundary=up5
I/flutter ( 4018):         RenderPadding#22dfa relayoutBoundary=up6
I/flutter ( 4018):           RenderFlex#c6117 relayoutBoundary=up7
I/flutter ( 4018):   ...(descendants list truncated after 25 lines)
I/flutter ( 4018): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4018): Another exception was thrown: 'package:flutter/src/foundation/licenses.dart': Failed assertion: line 158: 'result.text.trimLeft() == result.text': is not true.
```

The last line is repeated about a 100 times.

This is my code:

```dart
Widget _afterLoading(BuildContext context,List<LicenseEntry> entries){
    return new ListView.builder(
        itemCount: entries.length+1,
        itemBuilder: (BuildContext context,int index) {
          Widget item;
          if (index == 0) {
            item= _licensePreamble(
                context: context,
                applicationLegalese:  null
            );
          } else {
            item= new ExpansionTile(
              title: new Text(entries[index].packages.join(', ')),
              children: _entryTileBuilder(entries[index]),
            );
          }
          if(index ==entries.length){
            print('END: $index');
          }
          return Utils.divider(
              context: context,
              tile: item);
        }
    );
  }
```

'END: $index' gets never printed.

**Comment by Hixie** [comment] 2018-08-10 00:47
@zocker1996 Can you provide more of your code? The code above is not complete and I wasn't able to reproduce the problem.

**Comment by zoechi** [comment] 2018-08-23 09:03
This sounds like license content starts with whitespace which seems to cause this error.

**Comment by zoechi** [comment] 2018-12-18 16:04
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-12-18 16:04 UTC
Labels: framework, severe: crash, waiting for customer response

**Comment by mendieta** [comment] 2019-07-15 03:41
I have this same issue, the dependencies I have un the pubspec are:

`
dependencies:
  ads: ^0.11.0
  app_review: ^1.0.0
  fluro: ^1.5.0
  firebase_admob: ^0.9.0+1
  firebase_analytics: ^3.0.3
  firebase_core: ^0.4.0+6
  firebase_database: ^3.0.4
  firebase_dynamic_links: ^0.4.0+4
  firebase_remote_config: ^0.2.0+3
  cloud_functions: ^0.4.0+2
  device_id: ^0.2.0
  mobx: ^0.3.3+2
  flutter_mobx: ^0.3.0+1
  provider: ^3.0.0+1
  sqflite:
  shared_preferences: ^0.5.3+2
  url_launcher: ^5.0.5
  flutter_platform_widgets: ^0.12.0
  flutter_inner_drawer: ^0.3.0
  flutter_secure_storage: ^3.2.1+1
  package_info: ^0.4.0+4
  share: ^0.6.1+1
  flutter_search_bar:
  after_layout:
  flutter_map:
`

The error log is:

`
I/flutter (23452): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23452): The following assertion was thrown during a task callback:
I/flutter (23452): 'package:flutter/src/foundation/licenses.dart': Failed assertion: line 160 pos 14:
I/flutter (23452): 'result.text.trimLeft() == result.text': is not true.
`

hope this helps to solve this issue

**Comment by romatallinn** [comment] 2019-07-28 17:34
I am also having this exception. It seems that the problem is in the framework because it arises when I click _View License_ in the standard _showAbout_ window.

**Comment by Hixie** [comment] 2019-07-29 00:30
Try taking out dependencies one by one (or do a binary search if you want to go quicker) to figure out which dependency is doing it. It's probably got a poorly-formatted license.

Please file a new bug if you're seeing this. This bug is closed. Thanks!
