### ISSUE TITLE
[FEATURE REQUEST] Add parameter for separation for Row and Columns

### ISSUE THREAD

**Issue by ousvat** [flutter/flutter#95263] opened 2021-12-14 13:44 UTC
## Use case

Very often I need to add some distance between widgets in a row or a column and for this I need to insert some `SizedBox`es widgets.   

## Proposal

It would be amazingly useful if `Column` and `Row` would have a parameter for adding some space between the children. Inspiration comes from `Wrap` widget which has `runSpacing` and `spacing` parameters.

**Comment by danagbemava-nc** [comment] 2021-12-14 14:04
Duplicate of #55378

**Closed by danagbemava-nc** 2021-12-14 14:04 UTC
Labels: in triage
