### ISSUE TITLE
Wrong render color for emoji input from IOS keyboard

### ISSUE THREAD

**Issue by vqthanh1412489** [flutter/flutter#134516] opened 2023-09-12 09:30 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use TextField to input data
2. Open the soft keyboard and select the **Heart** emoji. 
3. Get the wrong UI for **Heart** emoji. Other emoji work.

### Expected results

-  **Heart** emoji have red (origin) color.

### Actual results

-  **Heart** emoji have black (origin) color.

### Code sample

<details><summary>Code sample</summary>

```dart
TextField(
                                          controller: _con!.notesTextController,
                                          decoration: InputDecoration(
                                            border: InputBorder.none,
                                            hintText: 'Nhập ghi chú của bạn',
                                            hintStyle: Theme.of(context).textTheme.bodyMedium,
                                          ),
                                        )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Imgur](https://i.imgur.com/RDrJ53B.mp4)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

<a href="https://imgur.com/EQB4cZS"><img src="https://i.imgur.com/EQB4cZS.png" title="source: imgur.com" /></a>

</details>

**Comment by dam-ease** [comment] 2023-09-12 12:21
Hi @vqthanh1412489. Thanks for filing this. I'm unable to reproduce this using the code sample below. Are you setting a dark ThemeData in your app that could possibly make this happen? Kindly check this out to see if it still reproduces on your end.

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const ExampleApp());

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: PopScope(
        child: Scaffold(
          appBar: AppBar(title: const Text('Sample')),
          body: const ExpansionTileExample(),
        ),
      ),
    );
  }
}

class ExpansionTileExample extends StatelessWidget {
  const ExpansionTileExample({super.key});

  @override
  Widget build(BuildContext context) {
    TextEditingController notesTextController = TextEditingController();
    return Column(
      children: <Widget>[
        TextField(
          controller: notesTextController,
          decoration: InputDecoration(
            border: InputBorder.none,
            hintText: 'Nhập ghi chú của bạn',
            hintStyle: Theme.of(context).textTheme.bodyMedium,
          ),
        )
      ],
    );
  }
}

``` 

</p>
</details> 

<details><summary>Screen Record</summary>
<p>

https://github.com/flutter/flutter/assets/53122008/d782699d-c70e-48a6-87ce-2d55b7f60473


</p>
</details> 

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.3 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (5 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (6 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 13 Pro (mobile)      • 14B6FEE4-2F1C-401F-8804-A5115D7A6DA2 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile)          • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro (mobile)      • 6548B0D1-7674-4306-9852-198C465F1104 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.14.0-14.0.pre.211, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.14.0-14.0.pre.211 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 69f6e7d15d (16 hours ago), 2023-09-11 00:50:38 -0400
    • Engine revision 7e41b064eb
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (6 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 13 Pro (mobile)      • 14B6FEE4-2F1C-401F-8804-A5115D7A6DA2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile)          • 1A122DE2-0CAB-4C3E-A395-691BF27D626F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro (mobile)      • 6548B0D1-7674-4306-9852-198C465F1104 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by vqthanh1412489** [comment] 2023-09-15 08:21
> Hi @vqthanh1412489. Thanks for filing this. I'm unable to reproduce this using the code sample below. Are you setting a dark ThemeData in your app that could possibly make this happen? Kindly check this out to see if it still reproduces on your end.
> 
> Code Sample
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(const ExampleApp());
> 
> class ExampleApp extends StatelessWidget {
>   const ExampleApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       theme: ThemeData(useMaterial3: true),
>       home: PopScope(
>         child: Scaffold(
>           appBar: AppBar(title: const Text('Sample')),
>           body: const ExpansionTileExample(),
>         ),
>       ),
>     );
>   }
> }
> 
> class ExpansionTileExample extends StatelessWidget {
>   const ExpansionTileExample({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     TextEditingController notesTextController = TextEditingController();
>     return Column(
>       children: <Widget>[
>         TextField(
>           controller: notesTextController,
>           decoration: InputDecoration(
>             border: InputBorder.none,
>             hintText: 'Nhập ghi chú của bạn',
>             hintStyle: Theme.of(context).textTheme.bodyMedium,
>           ),
>         )
>       ],
>     );
>   }
> }
> ```
> 
> Screen Record
>  Simulator.Screen.Recording.-.iPhone.14.Pro.-.2023-09-12.at.13.17.54.mp4 
> stable, master flutter doctor -v

Thank you for your reply. I try to run your code and it works for this emoji. But wrong for the second emoji.

https://github.com/flutter/flutter/assets/22234638/1e8abe5d-7a1b-46c9-b46e-8f585e6c8695

**Comment by dam-ease** [comment] 2023-09-15 16:20
Thanks for your response @vqthanh1412489. I can see this on my end as well. Thank you!

<img height=500 src="https://github.com/flutter/flutter/assets/53122008/fd966c08-db3d-4541-b23b-7c6556b06260">

**Comment by stuartmorgan** [comment] 2023-09-18 19:21
Moving to Framework for initial investigation; this feels like a font issue (although I'm not sure if it's framework side or engine side) since the playing card suit emojis do render differently in some fonts.

**Comment by jason-simmons** [comment] 2023-09-18 21:00
See https://github.com/flutter/flutter/issues/100964

**Comment by LongCatIsLooong** [comment] 2023-09-21 21:38
Closing in favor of https://github.com/flutter/flutter/issues/100964

**Closed by LongCatIsLooong** 2023-09-21 21:38 UTC
Labels: a: text input, platform-ios, engine, has reproducible steps, team-engine, found in release: 3.13, found in release: 3.14
