### ISSUE TITLE
RTL AppBar Leading Icon Misalignment and Direction Issue After Flutter SDK Upgrade

### ISSUE THREAD

**Issue by helal-muneer** [flutter/flutter#153133] opened 2024-08-08 23:58 UTC
### Steps to reproduce

After upgrading the Flutter SDK and packages, I noticed an issue with the AppBar in RTL (Right-to-Left) languages. Specifically, the default leading icon in the AppBar is not following the device's locale. The AppBar itself is correctly displayed in RTL, but the leading icon:
- Appears half-hidden.
- Is not flipped to the correct RTL direction.

**Appears half-hidden.**
Is not flipped to the correct RTL direction.
This issue persists even when using the `Directionality` widget above the AppBar, despite the fact that the app is RTL by default due to the selected language.

**Steps to Reproduce:**
1. Create a Flutter app with an AppBar.
3. Set the locale to an RTL language (e.g., Arabic or Hebrew).
4. Upgrade Flutter SDK and packages to the latest versions.
5. Run the app and observe the leading icon in the AppBar.

**Additional Notes:**

- This issue did not occur before upgrading the Flutter SDK and packages.
- The issue persists even when using the Directionality widget.

### Expected results

The leading icon should be fully visible and correctly flipped to match the RTL direction when the app's locale is set to an RTL language.

### Actual results

The leading icon appears half-hidden and is not flipped to the correct RTL direction, as if the app is in LTR (Left-to-Right) mode.

### Code sample

<details open><summary>Code sample</summary>

```dart
appBar: AppBar(
        title: Text(title),
        centerTitle: true,
        actions: [
          IconButton(onPressed: () {}, icon: const Icon(Icons.search)),
          IconButton(onPressed: () {}, icon: const Icon(Icons.info)),
        ],
      ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-09 at 02 55 06](https://github.com/user-attachments/assets/31241e53-070a-48f4-b4cf-35298679dfb6)
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6 23G80 darwin-arm64, locale
    en-TR)
    • Flutter version 3.24.0 on channel stable at
      /Users/helal/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (9 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/helal/Development/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • 8E26C0BC-BCB2-4BC9-A58A-1F668A4BEB6E •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 14.6 23G80 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 127.0.6533.99

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment] 2024-08-09 00:48
Duplicate of https://github.com/flutter/flutter/issues/153036

**Closed by jonahwilliams** 2024-08-09 00:48 UTC
