### ISSUE TITLE
[Web] Custom Google maps markers are not rendered in mobile web browser

### ISSUE THREAD

**Issue by abigotado** [flutter/flutter#147746] opened 2024-05-02 21:37 UTC
### Steps to reproduce

Create a web project with Google maps and custom markers (from svg) on it.

I do it this way:
```dart
Future<BitmapDescriptor> getBitmapDescriptorFromSvgAsset(
    final BuildContext context,
    final String assetName, {
    final Size size = const Size.square(30),
    final ColorMapper? colorMapper,
  }) async {
    final ui.FlutterView view = View.of(context);
    final PictureInfo pictureInfo = await vg.loadPicture(
      SvgAssetLoader(assetName, colorMapper: colorMapper),
      context,
    );

    final double devicePixelRatio = view.devicePixelRatio;
    final int width = (size.width * devicePixelRatio).toInt();
    final int height = (size.height * devicePixelRatio).toInt();

    final double scaleFactor = min(
      width / pictureInfo.size.width,
      height / pictureInfo.size.height,
    );

    final ui.PictureRecorder recorder = ui.PictureRecorder();

    ui.Canvas(recorder)
      ..scale(scaleFactor)
      ..drawPicture(pictureInfo.picture);

    final ui.Picture rasterPicture = recorder.endRecording();

    final ui.Image image = rasterPicture.toImageSync(width, height);
    final ByteData bytes =
        (await image.toByteData(format: ui.ImageByteFormat.png))!;

    return BitmapDescriptor.fromBytes(bytes.buffer.asUint8List());
  }
```

Then run the project. When you run it in standard Chrome browser - everything works fine, but if you run it in a browser of mobile device - markers don't render. As it is throwing 

```
Uncaught Unsupported operation: toImageSync is not supported on the HTML backend. Use drawPicture instead, or toImage.
```

I tried to replace  `final ui.Image image = rasterPicture.toImageSync(width, height);` with `final ui.Image image = await rasterPicture.toImage(width, height);`

Well, it sometimes works (not always, can't find out in which cases it works, in which not). But it renders markers incorrectly:
Instead of this <img width="95" alt="Снимок экрана 2024-05-02 в 18 26 25" src="https://github.com/flutter/flutter/assets/82471392/5ed748a9-2e26-446b-beb6-8e847c148d49"> it renders this <img width="92" alt="Снимок экрана 2024-05-02 в 18 30 41" src="https://github.com/flutter/flutter/assets/82471392/4deea79d-46d6-4605-83ff-445cbbde2adb">. As you can see - some white frame appears around the picture.

I think the problem is related to the HTML renderer, 'cause the problem disappears, if you use `--web-renderer=canvaskit`. But with canvaskit the marker becomes larger in mobile browser (in desktop Chrome everything is okay). <img width="212" alt="Снимок экрана 2024-05-02 в 18 34 09" src="https://github.com/flutter/flutter/assets/82471392/451e5a3c-dd0c-4175-9704-b20faea1b5f7">

### Expected results

Markers rendered correctly.

### Actual results

Markers not rendered or rendered incorrectly.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:math';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(
    const MapsPage(),
  );
}

class MapsPage extends StatelessWidget {
  const MapsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MapsHome(),
    );
  }
}

class MapsHome extends StatefulWidget {
  const MapsHome({super.key});

  @override
  State<MapsHome> createState() => _MapsHomeState();
}

class _MapsHomeState extends State<MapsHome> {
  final LatLng _kMapCenter = const LatLng(52.4478, -3.5402);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _setMarkers(),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        if (snapshot.hasData) {
          return GoogleMap(
            initialCameraPosition: CameraPosition(
              target: _kMapCenter,
              zoom: 18.0,
            ),
            markers: snapshot.data,
          );
        } else {
          return const Center(
            child: CircularProgressIndicator(),
          );
        }
      },
    );
  }

  Future<Set<Marker>> _setMarkers() async {
    final BitmapDescriptor icon1 = await volleyball(
      context,
    );
    final BitmapDescriptor icon =
        await SvgConverter.getClusterBitmap(48, text: '48');

    return {
      Marker(
        markerId: const MarkerId('marker_1'),
        position: _kMapCenter,
        icon: icon,
      ),
      Marker(
        markerId: const MarkerId('marker_2'),
        position: const LatLng(52.4476, -3.5405),
        icon: icon1,
      ),
    };
  }

  /// Volleyball icon.
  static Future<BitmapDescriptor> volleyball(final BuildContext context) async {
    return SvgConverter.getBitmapDescriptorFromSvgAsset(
      context,
      'assets/volleyball.svg',
    );
  }
}

/// Utility for converting SVG.
class SvgConverter {
  /// Converts SVG to [BitmapDescriptor].
  static Future<BitmapDescriptor> getBitmapDescriptorFromSvgAsset(
    final BuildContext context,
    final String assetName, {
    final Size size = const Size.square(30),
    final ColorMapper? colorMapper,
  }) async {
    final ui.FlutterView view = View.of(context);
    final PictureInfo pictureInfo = await vg.loadPicture(
      SvgAssetLoader(assetName, colorMapper: colorMapper),
      context,
    );

    final double devicePixelRatio = view.devicePixelRatio;
    final int width = (size.width * devicePixelRatio).toInt();
    final int height = (size.height * devicePixelRatio).toInt();

    final double scaleFactor = min(
      width / pictureInfo.size.width,
      height / pictureInfo.size.height,
    );

    final ui.PictureRecorder recorder = ui.PictureRecorder();

    ui.Canvas(recorder)
      ..scale(scaleFactor)
      ..drawPicture(pictureInfo.picture);

    final ui.Picture rasterPicture = recorder.endRecording();

    final ui.Image image = rasterPicture.toImageSync(width, height);
    final ByteData bytes =
        (await image.toByteData(format: ui.ImageByteFormat.png))!;

    return BitmapDescriptor.fromBytes(bytes.buffer.asUint8List());
  }

  static Future<BitmapDescriptor> getClusterBitmap(
    final int size, {
    final String? text,
  }) async {
    final ui.PictureRecorder pictureRecorder = ui.PictureRecorder();
    final Canvas canvas = Canvas(pictureRecorder);
    final Paint paint1 = Paint()..color = Colors.blue.withOpacity(0.3);
    final Paint paint2 = Paint()..color = Colors.blue;
    final Paint paint3 = Paint()..color = Colors.white;

    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.0, paint1);
    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.4, paint2);
    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.6, paint3);

    final TextPainter painter = TextPainter(textDirection: TextDirection.ltr);
    painter.text = TextSpan(
      text: text,
      style: TextStyle(
        fontSize: size / 3,
        color: Colors.blue,
        fontWeight: FontWeight.w500,
      ),
    );
    painter.layout();
    painter.paint(
      canvas,
      Offset(size / 2 - painter.width / 2, size / 2 - painter.height / 2),
    );

    final ui.Image img =
        await pictureRecorder.endRecording().toImage(size, size);
    final ByteData data =
        (await img.toByteData(format: ui.ImageByteFormat.png))!;

    return BitmapDescriptor.fromBytes(data.buffer.asUint8List());
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhoneK. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment] 2024-05-03 08:08
Hi @abigotado, I believe this is a duplicate of https://github.com/flutter/flutter/issues/147522. 

Can you confirm if this is similar to your case?

**Comment by abigotado** [comment] 2024-05-03 20:46
Hi @danagbemava-nc! Yes, it is similar, but there are some additional info in my topic, which are not mentioned in the other one, maybe it can be helpful

**Comment by danagbemava-nc** [comment] 2024-05-06 06:28
Hi @abigotado, please feel free to add the additional information in the other thread. As this shares a root cause with #147522 I'll be closing this in favor of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-05-06 06:28 UTC
Labels: in triage
