### ISSUE TITLE
admob plugin causes Android to crash on startup

### ISSUE THREAD

**Issue by skrizanovic** [flutter/flutter#23659] opened 2018-10-29 05:07 UTC
When I add the ad_mob (firebase_admob: ^0.6.1+1) Android emulator crashing before any code executes. As soon as I take it out, it works. I tried to start LogCat, but no logs are generated (I am using VS Code)

I have the following plugins working successfully with firebase
flutter_crashlytics: ^0.1.1
firebase_analytics: ^1.0.4

But ad_mob just won't work.

**Comment by superciccio** [comment] 2018-10-29 07:51
I had the exact issue few days ago... I solved with this
copy that in your AndroidManifest.xml
`        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>
`
where value in this case is the test one

**Comment by zoechi** [comment] 2018-10-29 08:19
Please add the output of `flutter doctor -v`.

**Comment by skrizanovic** [comment] 2018-10-30 22:31
Hi supercicco, I tried to add the line to the AndroidManifest.xml and it still did not start.

Zoechi, here is the output of flutter doctor
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
    • Flutter version 0.9.4 at C:\flutter\v0.8.2\flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Stevek\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.28.2)
    • VS Code at C:\Users\Stevek\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!

**Comment by dnfield** [comment] 2018-11-02 03:29
I'm able to reproduce this on an emulator.  Will investigate.

**Comment by dnfield** [comment] 2018-11-02 03:41
Looks like a configuration issue that we need to document better.  I also get warnings about deprecated API in that plugin.  Here are some logs:

```
11-01 20:39:33.118 25235 25235 E AndroidRuntime: FATAL EXCEPTION: main
11-01 20:39:33.118 25235 25235 E AndroidRuntime: Process: io.flutter.plugins.firebaseadmobexample, PID: 25235
11-01 20:39:33.118 25235 25235 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 
11-01 20:39:33.118 25235 25235 E AndroidRuntime: ******************************************************************************
11-01 20:39:33.118 25235 25235 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
11-01 20:39:33.118 25235 25235 E AndroidRuntime: * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
11-01 20:39:33.118 25235 25235 E AndroidRuntime: * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
11-01 20:39:33.118 25235 25235 E AndroidRuntime: * follow instructions here: https://goo.gl/h17b6x.                           *
11-01 20:39:33.118 25235 25235 E AndroidRuntime: ******************************************************************************
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: Caused by: java.lang.IllegalStateException: 
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 
11-01 20:39:33.118 25235 25235 E AndroidRuntime: ******************************************************************************
11-01 20:39:33.118 25235 25235 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
11-01 20:39:33.118 25235 25235 E AndroidRuntime: * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
11-01 20:39:33.118 25235 25235 E AndroidRuntime: * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
11-01 20:39:33.118 25235 25235 E AndroidRuntime: * follow instructions here: https://goo.gl/h17b6x.                           *
11-01 20:39:33.118 25235 25235 E AndroidRuntime: ******************************************************************************
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at com.google.android.gms.internal.ads.zzmn.attachInfo(Unknown Source:17)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(Unknown Source:3)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
11-01 20:39:33.118 25235 25235 E AndroidRuntime: 	... 10 more
```

**Comment by dnfield** [comment] 2018-11-02 03:57
The suggestion by @superciccio is correct - you just need to make sure you're correlating that AppID with whatever you're passing in in your app.  The one mentioned in the post there is suitable for samples.

I'll update the instructions in the plugin for this as well.

**Comment by dnfield** [comment] 2018-11-02 04:35
You can avoid this error by consuming version `0.6.1` of this package, or correctly updating your AndroidManifest.  I have a PR opened to address this issue.

Let me know if you think anything else needs to be done here - otherwise I think we should be good to close this.

**Comment by dnfield** [comment] 2018-11-02 04:36
(Also FYI - you can run `adb logcat` independently from `flutter run` to get the logs I found)

**Comment by skrizanovic** [comment] 2018-11-06 04:18
Thank you so much for that. I was able to run adb logcat and found that I put the meta data tag in the wrong spot. 

I put it in the activity node, not in the application. This seems to have fixed my problem. 

Thanks you all for your help.

**Closed** 2018-11-14 00:33 UTC
Labels: p: firebase, p: first party, plugin, severe: crash, waiting for PR to land (fixed)

**Comment by willvlad** [comment] 2019-05-31 23:16
Facing the same issue. Tried all the above, no joy so far...

**Comment by nenio-traduko** [comment] 2019-06-11 22:39
@willvlad Did you find a solution by any chance?

**Comment by hemangjoshi37a** [comment] 2019-06-15 15:13
> I had the exact issue few days ago... I solved with this
> copy that in your AndroidManifest.xml
> ` <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713"/>`
> where value in this case is the test one

Where exactly to add this line in the android manifest file?? Please help.

**Comment by wongni** [comment] 2019-08-23 19:39
> > I had the exact issue few days ago... I solved with this
> > copy that in your AndroidManifest.xml
> > ` <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713"/>`
> > where value in this case is the test one
> 
> Where exactly to add this line in the android manifest file or replace any existing one?? Please help.

It must be under <application> tag. 

For example, 
```
<manifest>
    <application>
        <!-- TODO: Replace with your real AdMob app ID -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-################~##########"/>
    </application>
</manifest>
```

**Comment by kroikie** [comment] 2019-10-13 18:43
@skrizanovic

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/591. Any further collaboration will be done there.

**Comment by erperejildo** [comment] 2020-01-02 15:28
My problem was that I was adding `<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID"` but with my real app id when it's exactly like with `APPLICATION_ID`.

The id goes on `value`, not on `name`

**Comment by tonypottera24** [comment] 2020-02-20 15:23
In my case, it crash when using android emulator without google play.
`I/DynamiteModule( 2982): Selected local version of com.google.android.gms.ads.dynamite
W/Ads     ( 2982): #007 Could not call remote method. @28
W/Ads     ( 2982): com.google.android.gms.internal.ads.zzayz: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to instantiate module class: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzayx.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:3)
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzaku.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:17)
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzaku.zzd(com.google.android.gms:play-services-ads-lite@@18.3.0:44)
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzakt.run(com.google.android.gms:play-services-ads-lite@@18.3.0)
W/Ads     ( 2982):      at java.lang.Thread.run(Thread.java:856)
W/Ads     ( 2982): Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to instantiate module class: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
W/Ads     ( 2982):      at com.google.android.gms.dynamite.DynamiteModule.instantiate(Unknown Source)
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzayx.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:1)
W/Ads     ( 2982):      ... 4 more
W/Ads     ( 2982): Caused by: java.lang.ClassNotFoundException: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
W/Ads     ( 2982):      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
W/Ads     ( 2982):      at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
W/Ads     ( 2982):      at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
W/Ads     ( 2982):      at com.google.android.gms.dynamite.DynamiteModule.instantiate(Unknown Source)
W/Ads     ( 2982):      ... 5 more`

**Comment by waqaraliu** [comment] 2020-04-04 22:31
If any one still having trouble, then change the package name in your MainActivity file. because manifest and main activity should have same package names. like com.abc.admob
