### ISSUE TITLE
How to show html page

### ISSUE THREAD

**Issue by cloderW** [flutter/flutter#13347] opened 2017-12-05 07:16 UTC
I have a string contain html tag with css, i want to show it ,what use Widget show?

**Comment by zoechi** [comment] 2017-12-05 10:42
I think https://github.com/dart-flitter/flutter_webview_plugin is the way to go.
It seems it currently only supports fullscreen

**Comment by Hixie** [comment] 2018-03-07 17:41
Dupe of https://github.com/flutter/flutter/issues/730

**Closed by Hixie** 2018-03-07 17:41 UTC
