### ISSUE TITLE
TextField changing textAlign via state property, causing !_needsLayout assertion fail.

### ISSUE THREAD

**Issue by laszlo-galosi** [flutter/flutter#27546] opened 2019-02-05 15:46 UTC
I have this assertion fail, when I'm trying to change a TextFormField textAlign via a state property.
I think, it could be related to [#20611](https://github.com/flutter/flutter/issues/20611)
```
02-05 16:24:37.656 8598-11306/hu.extremenet.fluttercarousel I/flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
02-05 16:24:37.668 8598-11306/hu.extremenet.fluttercarousel I/flutter: The following assertion was thrown during paint():
02-05 16:24:37.668 8598-11306/hu.extremenet.fluttercarousel I/flutter: TextPainter.paint called when text geometry was not yet calculated.
02-05 16:24:37.668 8598-11306/hu.extremenet.fluttercarousel I/flutter: Please call layout() before paint() to position the text before painting it.
02-05 16:24:37.670 8598-11306/hu.extremenet.fluttercarousel I/flutter: When the exception was thrown, this was the stack:
02-05 16:24:37.687 8598-11306/hu.extremenet.fluttercarousel I/flutter: #0      TextPainter.paint.<anonymous closure> (package:flutter/src/painting/text_painter.dart:381:9)
02-05 16:24:37.687 8598-11306/hu.extremenet.fluttercarousel I/flutter: #1      TextPainter.paint (package:flutter/src/painting/text_painter.dart:387:6)
02-05 16:24:37.687 8598-11306/hu.extremenet.fluttercarousel I/flutter: #2      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1412:18)
02-05 16:24:37.687 8598-11306/hu.extremenet.fluttercarousel I/flutter: #3      RenderEditable.paint (package:flutter/src/rendering/editable.dart:1426:7)
02-05 16:24:37.687 8598-11306/hu.extremenet.fluttercarousel I/flutter: #4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
02-05 16:24:37.687 8598-11306/hu.extremenet.fluttercarousel I/flutter: #5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
02-05 16:24:37.687 8598-11306/hu.extremenet.fluttercarousel I/flutter: #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
02-05 16:24:37.687 8598-11306/hu.extremenet.fluttercarousel I/flutter: #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
02-05 16:24:37.687 8598-11306/hu.extremenet.fluttercarousel I/flutter: #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #10     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #11     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4429:13)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
02-05 16:24:37.688 8598-11306/hu.extremenet.fluttercarousel I/flutter: #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
02-05 16:24:37.689 8598-11306/hu.extremenet.fluttercarousel I/flutter: #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
02-05 16:24:37.689 8598-11306/hu.extremenet.fluttercarousel I/flutter: #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
02-05 16:24:37.689 8598-11306/hu.extremenet.fluttercarousel I/flutter: #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
02-05 16:24:37.689 8598-11306/hu.extremenet.fluttercarousel I/flutter: #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
02-05 16:24:37.689 8598-11306/hu.extremenet.fluttercarousel I/flutter: #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
02-05 16:24:37.689 8598-11306/hu.extremenet.fluttercarousel I/flutter: #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2094:7)
02-05 16:24:37.689 8598-11306/hu.extremenet.fluttercarousel I/flutter: #25     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
02-05 16:24:37.690 8598-11306/hu.extremenet.fluttercarousel I/flutter: #26     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
02-05 16:24:37.699 8598-11306/hu.extremenet.fluttercarousel I/flutter: #27     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:855:29)
02-05 16:24:37.699 8598-11306/hu.extremenet.fluttercarousel I/flutter: #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:283:19)
02-05 16:24:37.699 8598-11306/hu.extremenet.fluttercarousel I/flutter: #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:686:13)
02-05 16:24:37.699 8598-11306/hu.extremenet.fluttercarousel I/flutter: #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
02-05 16:24:37.699 8598-11306/hu.extremenet.fluttercarousel I/flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
02-05 16:24:37.700 8598-11306/hu.extremenet.fluttercarousel I/flutter: #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
02-05 16:24:37.700 8598-11306/hu.extremenet.fluttercarousel I/flutter: #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
02-05 16:24:37.700 8598-11306/hu.extremenet.fluttercarousel I/flutter: #34     _invoke (dart:ui/hooks.dart:159:13)
02-05 16:24:37.700 8598-11306/hu.extremenet.fluttercarousel I/flutter: #35     _drawFrame (dart:ui/hooks.dart:148:3)
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter: The following RenderObject was being processed when the exception was fired:
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   RenderEditable#9ded8 relayoutBoundary=up15
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   creator: _Editable-[GlobalKey#25f6f] ← Semantics ← CompositedTransformTarget ← _ScrollableScope ←
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   IgnorePointer-[GlobalKey#b194e] ← Semantics ← Listener ←
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#22ded] ← RepaintBoundary ←
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification> ← ⋯
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   parentData: <none> (can use size)
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   constraints: BoxConstraints(w=336.0, 0.0<=h<=Infinity)
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   size: Size(336.0, 19.0)
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   cursorColor: Color(0xff4285f4)
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   showCursor: ValueNotifier<bool>#25da3(false)
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   maxLines: 1
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   selectionColor: Color(0xff90caf9)
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   textScaleFactor: 1.0
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   locale: en_US
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream,
02-05 16:24:37.764 8598-11306/hu.extremenet.fluttercarousel I/flutter:   isDirectional: false)
02-05 16:24:37.765 8598-11306/hu.extremenet.fluttercarousel I/flutter:   offset: ScrollPositionWithSingleContext#a3203(offset: 0.0, range: 0.0..0.0, viewport: 336.0,
02-05 16:24:37.765 8598-11306/hu.extremenet.fluttercarousel I/flutter:   ScrollableState, ClampingScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#440a2,
02-05 16:24:37.765 8598-11306/hu.extremenet.fluttercarousel I/flutter:   ScrollDirection.idle)
02-05 16:24:37.765 8598-11306/hu.extremenet.fluttercarousel I/flutter: This RenderObject has no descendants.
02-05 16:24:37.765 8598-11306/hu.extremenet.fluttercarousel I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
02-05 16:24:37.832 8598-11306/hu.extremenet.fluttercarousel I/flutter: Another exception was thrown: 'package:flutter/src/painting/text_painter.dart': Failed assertion: line 298 pos 12: '!_needsLayout': is not true.
02-05 16:24:37.833 8598-11306/hu.extremenet.fluttercarousel I/flutter: Another exception was thrown: 'package:flutter/src/painting/text_painter.dart': Failed assertion: line 307 pos 12: '!_needsLayout': is not true.
02-05 16:24:37.845 8598-11306/hu.extremenet.fluttercarousel I/flutter: Another exception was thrown: TextPainter.paint called when text geometry was not yet calculated.

```
My enviroment is (the issues found is related to the iOS toolchain, no XCode installed)
```
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.11.3 15D21, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)

...

[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.30.2)
[✓] Connected device (2 available)

! Doctor found issues in 4 categories.
```

The sample to reproduce is, simply click the button to focus/unfocus the TextFormField.
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  HomePageState createState() => new HomePageState();
}

class HomePageState extends State<HomePage> {
  FocusNode _focusNode;
  TextAlign _textAlign = TextAlign.start;

  @override
  void initState() {
    super.initState();
    _focusNode = new FocusNode();
    _focusNode.addListener(_handleFocusChanged);
   }

  void _handleFocusChanged() {
    setState(() {
      _textAlign = _focusNode.hasFocus ? TextAlign.start : TextAlign.end;
    });
  }

  @override
  void dispose() {
    _focusNode.removeListener(_handleFocusChanged);
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: AppBar(title: Text('Test')),
        body: Column(children: [
          new TextFormField(
            decoration: InputDecoration(
              border: const UnderlineInputBorder(),
              filled: true,
              hintText: "Enter your full name",
              labelText: "Name",
            ),
            textAlign: _textAlign,
            initialValue: '10000',
            focusNode: _focusNode,
            autofocus: true,
          ),
          SizedBox(
            height: 24.0,
          ),
          FlatButton(
            color: Colors.indigo,
            textColor: Colors.white,
            child: Text('${_focusNode.hasFocus ? "Unfocus" : "Focus"}'),
            onPressed: () => _focusNode.hasFocus
                ? _focusNode.unfocus()
                : FocusScope.of(context).requestFocus(_focusNode),
          ),
        ]));
  }
}
```

If the textAlign not changed such as:
`_textAlign = _focusNode.hasFocus ? TextAlign.start : TextAlign.start;` 
, the issue is not occured.

**Comment by jonahwilliams** [comment] 2019-02-05 19:04
duplicate of https://github.com/flutter/flutter/issues/20611

**Closed by jonahwilliams** 2019-02-05 19:04 UTC
