### ISSUE TITLE
flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required, but app depends on intl ^0.18.1

### ISSUE THREAD

**Issue by parteekpassi** [flutter/flutter#125493] opened 2023-04-25 15:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have upgraded my sample_app dependency to  intl: ^0.18.1 from  intl: ^0.17.0 and I started getting Error:

Because sample_app depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because sample_app depends on intl ^0.18.1, version solving failed

environment:
  sdk: ">=2.17.0 <3.0.0"
  
flutter doctor -v
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3 22E252 darwin-x64, locale en-CA)
    • Flutter version 3.7.12 on channel stable at /Users/parteek/Development/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (8 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/parteek/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.3)
    • VS Code at /Users/parteek/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPad Pro (11-inch) (4th generation) (mobile) • 4D1680C2-8EB4-4DD3-85A6-EDAF23F6AF1A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                              • macos                                • darwin-x64     • macOS 13.3 22E252 darwin-x64
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

### Expected results

How to fix this Error ?

### Actual results

Getting Error: Because sample_app depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required. So, because sample_app depends on intl ^0.18.1, version solving failed

### Code sample

.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment] 2023-04-25 16:40
Duplicate of https://github.com/flutter/flutter/issues/117163

**Closed by stuartmorgan** 2023-04-25 16:40 UTC
