### ISSUE TITLE
Visual Studio - develop for Windows (the doctor check crashed) 

### ISSUE THREAD

**Issue by aspnetcwtm** [flutter/flutter#104571] opened 2022-05-25 01:46 UTC
Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string:   
{
          "instanceId": "7ebea4d0",
          "installDate": "2022-01-05T15:40:09Z",
          "installationName": "VisualStudio/17.0.4+32014.148",
          "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise",
          "installationVersion": "17.0.32014.148",
          "productId": "Microsoft.VisualStudio.Product.Enterprise",
          "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.exe",
          "state": 4294967295,
          "isComplete": true,
          "isLaunchable": true,
          "isPrerelease": false,
          "isRebootRequired": false,
          "displayName": "Visual Studio Enterprise 2022",
          "description": "�����κι�ģ�Ŷ��ṩ�Ŀ����š��˵��˽������",
          "channelId": "VisualStudio.17.Release",
          "channelUri": "https://aka.ms/vs/17/release/channel",
          "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
          "installedChannelUri": "https://aka.ms/vs/17/release/channel",
          "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.0#17.0.4",
          "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
          "updateDate": "2022-01-05T15:40:09.5405942Z",
          "catalog": {
            "buildBranch": "d17.0",
            "buildVersion": "17.0.32014.148",
            "id": "VisualStudio/17.0.4+32014.148",
            "localBuild": "build-lab",
            "manifestName": "VisualStudio",
            "manifestType": "installer",
            "productDisplayVersion": "17.0.4",
            "productLine": "Dev17",
            "productLineVersion": "2022",
            "productMilestone": "RTW",
            "productMilestoneIsPreRelease": "False",
            "productName": "Visual Studio",
            "productPatchVersion": "4",
            "productPreReleaseMilestoneSuffix": "1.0",
            "productSemanticVersion": "17.0.4+32014.148",
            "requiredEngineVersion": "3.0.4496.34889"
          },
          "properties": {
            "campaignId": "2022",
            "channelManifestId": "VisualStudio.17.Release/17.0.4+32014.148",
            "nickname": "",
            "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
          }
        }
      ]

**Comment by darshankawar** [comment] 2022-05-25 07:07
Closing this as duplicate of https://github.com/flutter/flutter/issues/102451. For workaround, see https://github.com/flutter/flutter/issues/102451#issuecomment-1136423118

**Closed by darshankawar** 2022-05-25 07:07 UTC
Labels: in triage
