### ISSUE TITLE
[local_auth] useErrorDialogs not work properly

### ISSUE THREAD

**Issue by PierreBizos** [flutter/flutter#85300] opened 2021-06-25 09:44 UTC
## Steps to Reproduce

- Run example of local_auth in version 1.1.6 and with a device with no fingerprint register
- Try to authenticate with the last button in the example view. 
- Throw notEnrolled exception with no dialogs to go to settings.

- Do the same thing with version 0.6.3+4 and works fine. Maybe related to null safety migration ? 
<img src="https://user-images.githubusercontent.com/36700341/123405757-6d4f4400-d5aa-11eb-9885-eb09aad906d5.png" height="450" />	

## Device

Tested on OnePlus 3 with android 9.0.6

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[√] Flutter (Channel unknown, 2.2.0, on Microsoft Windows [version 10.0.19042.1052], locale fr-FR)
    • Flutter version 2.2.0 at D:\dart_sdks\_flutter\flutter2x
    • Framework revision b22742018b (6 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\pnv_pbi.ASP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\pnv_pbi.ASP\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\pnv_pbi.ASP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • ONEPLUS A3003 (mobile) • 24835fa4 • android-arm64  • Android 9 (API 28)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 90.0.818.62

```

</details>

**Comment by TahaTesser** [comment] 2021-06-28 09:35
Hi @PierreBizos 
This is a known issue, please see https://github.com/flutter/flutter/issues/80259, it is definitely a regression in the package
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/80259
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-28 09:35 UTC
Labels: in triage
