### ISSUE TITLE
Obscure text is being exposed when deleting newly inserted characters.

### ISSUE THREAD

**Issue by trungPa** [flutter/flutter#72190] opened 2020-12-12 08:35 UTC
## Steps to Reproduce

1. Enter 123456 in a TextField with obscureText set to true.
2. Place the cursor right before the third character.
3. Enter any character and delete it with backspace immediately before _obscureShowCharTicksPending timeout.
4. the text field will now be showing the third character: ••3•••

**Expected results:** 
The third character is not shown.
**Actual results:** 
The third character '3' is shown.

![Screen Recording 2020-12-12 at 15 17 12](https://user-images.githubusercontent.com/17810017/101979278-555b4700-3c8e-11eb-81ac-006109ac47b3.gif)

We are currently using this workaround.
In /flutter/packages/flutter/lib/src/widgets/editable_text.dart, add these lines after line 1647 (inside updateEditingValue method):
```
if (widget.obscureText && value.text.length < _value.text.length){
  _obscureShowCharTicksPending = 0;
}
```
<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en)
    • Flutter version 1.22.4 at /Users/x/UserApps/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/x/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Google Pixel 2 (mobile) • 192.168.56.103:5555 • android-x86 • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.
```
</details>

**Comment by darshankawar** [comment] 2020-12-14 07:36
@trungPa 
With `obscureText: true`, when we type in any value, it first shows the value and then obscures it, and the same is happening in your case. Do you think this is not an intended behavior ?

**Comment by pedromassangocode** [comment] 2021-01-06 12:28
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-06 12:28 UTC
Labels: a: text input, f: material design, framework, in triage, waiting for customer response
