### ISSUE TITLE
IOS real phone reported this error:

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#90933] opened 2021-09-29 07:32 UTC
IOS real phone reported this error:
![5b89ff1f1de9d267e2e3d89e9f67efa](https://user-images.githubusercontent.com/91245043/135223199-d9002418-b15a-4326-881a-10fb9131cbfe.jpg)

**Comment by TahaTesser** [comment] 2021-09-29 09:23
duplicate of https://github.com/flutter/flutter/issues/90935

**Closed by TahaTesser** 2021-09-29 09:23 UTC
Labels: in triage
