### ISSUE TITLE
[LINUX] Buttons freeze if tapped repeatedly or using multiple fingers using a touchscreen device

### ISSUE THREAD

**Issue by HugoCSWork** [flutter/flutter#110270] opened 2022-08-25 15:17 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample.
2. Use a touchscreen device to click repeatedly very fast or use multiple fingers on the button.
3. Button will freeze highlighted and an error will appear in the console.

As a note - clicking on random areas on the screen very fast or with multiple fingers will also cause this error in the console.

**Operating System:**
Currently only tested on - Linux Desktop Ubuntu 22.04.01.

**Expected results:**
Button to be clickable multiple times or with multiple fingers without breaking.

**Actual results:** 
Button breaks and becomes disabled and is unable to be clicked.

<details>
<summary>Code sample</summary>

Can also be found here - https://github.com/HugoCSWork/FlutterTouchscreenDesktopBug

```dart
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Touchscreen button click bug',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            // GestureDetector(
            //   onTap:_incrementCounter,
            //   child: Container(
            //     width: 100,
            //     height: 100,
            //     color: Colors.red,
            //     child: Text(_counter.toString()),
            //   ),
            // )
            TextButton(
              onPressed: _incrementCounter,
              style: ButtonStyle(
                fixedSize: MaterialStateProperty.all(const Size(100, 100)),
                backgroundColor: MaterialStateProperty.all(Colors.red),
              ),
              child: Text(_counter.toString()),
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

**There is an example of the error at the bottom of this one**
```
[  +55 ms] executing: uname -m
[  +26 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +5 ms] executing: [/home/hugo/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] executing: [/home/hugo/snap/flutter/common/flutter/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[  +15 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] 3.0.5
[   +8 ms] executing: [/home/hugo/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/hugo/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +83 ms] Unable to locate an Android SDK.
[   +4 ms] executing: [/home/hugo/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +56 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] Skipping pub get: version match.
[  +99 ms] Generating /home/hugo/work/touchscreen_button_click/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +89 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +5 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/hugo/work/touchscreen_button_click/.dart_tool/package_config_subset}
[  +20 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +2 ms] complete
[   +7 ms] Launching lib/main.dart on Linux in debug mode...
[   +5 ms] /home/hugo/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/hugo/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/hugo/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.TKACCC/flutter_tool.QGKFQE/app.dill --packages /home/hugo/work/touchscreen_button_click/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +32 ms] Building Linux application...
[  +23 ms] <- compile package:touchscreen_button_click/main.dart
[   +2 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/hugo/work/touchscreen_button_click/linux
[  +91 ms] -- Configuring done
[        ] -- Generating done
[        ] -- Build files have been written to: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug
[   +4 ms] executing: ninja -C build/linux/x64/debug install
[  +10 ms] ninja: Entering directory `build/linux/x64/debug'
[+2646 ms] [1/5] Generating /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/hugo/work/touchscreen_button_click/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +4 ms] [  +68 ms] executing: uname -m
[        ] [  +52 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +9 ms] executing: [/home/hugo/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +9 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] [        ] executing: [/home/hugo/snap/flutter/common/flutter/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] [  +18 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] [        ] 3.0.5
[        ] [   +9 ms] executing: [/home/hugo/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/hugo/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +69 ms] Unable to locate an Android SDK.
[        ] [   +6 ms] executing: [/home/hugo/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +58 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +109 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +44 ms] Initializing file store
[        ] [   +9 ms] Done initializing file store
[        ] [  +53 ms] Skipping target: gen_localizations
[        ] [  +11 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +587 ms] Skipping target: unpack_linux
[        ] [ +417 ms] Skipping target: kernel_snapshot
[        ] [ +307 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [  +20 ms] Done persisting file store
[        ] [   +5 ms] build succeeded.
[        ] [   +9 ms] "flutter assemble" took 1,603ms.
[        ] [ +134 ms] ensureAnalyticsSent: 129ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +354 ms] [2/5] Building CXX object CMakeFiles/touchscreen_button_click.dir/flutter/generated_plugin_registrant.cc.o
[  +50 ms] [3/5] Building CXX object CMakeFiles/touchscreen_button_click.dir/my_application.cc.o
[ +141 ms] [4/5] Linking CXX executable intermediates_do_not_run/touchscreen_button_click
[        ] [4/5] Install the project...
[  +12 ms] -- Install configuration: "Debug"
[  +23 ms] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/touchscreen_button_click
[        ] -- Set runtime path of "/home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/touchscreen_button_click" to "$ORIGIN/lib"
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/icudtl.dat
[   +2 ms] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[  +82 ms] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +3 ms] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +88 ms] -- Installing: /home/hugo/work/touchscreen_button_click/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[  +10 ms] Building Linux application... (completed in 3.6s)
[ +309 ms] Observatory URL on device: http://127.0.0.1:45121/qnO2xhlSDT8=/
[   +6 ms] Caching compiled dill
[  +89 ms] Connecting to service protocol: http://127.0.0.1:45121/qnO2xhlSDT8=/
[ +166 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:45121/qnO2xhlSDT8=/.
[  +93 ms] DDS is listening at http://127.0.0.1:38869/I2-7FFbu2HY=/.
[  +58 ms] Successfully connected to service protocol: http://127.0.0.1:45121/qnO2xhlSDT8=/
[  +45 ms] DevFS: Creating new filesystem on the device (null)
[  +18 ms] DevFS: Created new filesystem on the device (file:///tmp/touchscreen_button_clickAFWCNY/touchscreen_button_click/)
[   +3 ms] Updating assets
[  +94 ms] Syncing files to device Linux...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:touchscreen_button_click/main.dart 8a7282ff-3d9c-4907-a717-1936bf18e69a
[        ] <- 8a7282ff-3d9c-4907-a717-1936bf18e69a
[   +1 ms] Bundle processing done.
[ +118 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Linux... (completed in 122ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +2 ms] Connected to _flutterView/0x1f55140.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:38869/I2-7FFbu2HY=/
[ +167 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:38869/I2-7FFbu2HY=/
[+1965 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 227 pos 12: '(event is PointerAddedEvent) == (lastEvent is
PointerRemovedEvent)': is not true.
[   +1 ms] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
[        ] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
[        ] #2      MouseTracker._shouldMarkStateDirty (package:flutter/src/rendering/mouse_tracker.dart:227:12)
[        ] #3      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:313:10)
[        ] #4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:321:20)
[        ] #5      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
[        ] #6      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
[        ] #7      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
[        ] #8      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
[        ] #9      _rootRunUnary (dart:async/zone.dart:1442:13)
[        ] #10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
[        ] #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
[        ] #12     _invoke1 (dart:ui/hooks.dart:170:10)
[        ] #13     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
[        ] #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)

```

```
flutter analyze
Analyzing touchscreen_button_click...                                   
No issues found! (ran in 1.5s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 22.04.1 LTS 5.15.0-46-generic, locale en_GB.UTF-8)
    • Flutter version 3.0.5 at /home/hugo/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.46.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.1 LTS 5.15.0-46-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

**Comment by huycozy** [comment] 2022-08-26 03:43
Hi @HugoCSWork, thanks for filing the issue.
But I can not reproduce the issue due to no touchscreen device. With my Linux PC (Ubuntu 20.04), it works normally.
Based on the exception logs:
>[+1965 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 227 pos 12: '(event is PointerAddedEvent) == (lastEvent is
PointerRemovedEvent)': is not true.

It looks similar to https://github.com/flutter/flutter/issues/80746#issuecomment-876647593. Could you please try reproducing the issue on Web? 
Also, please try using `TextButton` without `ButtonStyle` so we can verify whether two issues have the same cause or not.
Thanks you!

**Comment by HugoCSWork** [comment] 2022-08-26 08:02
Hi @huycozy, thanks for the fast response.

I can't seem to replicate this on Web with the simple configuration I used as the error never occurs when clicking very fast or when you try to tap with multiple fingers as it thinks you're right clicking. The component has different styling in that example so let me know if you want me to test it with their configuration. 

I have removed the  `ButtonStyle` but am still encountering the same issue.  It seems like less to do with the button widget as wrapping a `Container` with a `GestureDetector` still causes the same problem.

**Comment by huycozy** [comment] 2022-08-26 12:03
Hi @HugoCSWork 
Could you please try reproducing the issue on Flutter master channel? Also, please provide device information as well. Thanks!

**Comment by HugoCSWork** [comment] 2022-08-26 18:09
Hi @huycozy 

Can confirm switching to the master channel fixes this issue.

My Device Information is
Operating System - Ubuntu 22.04.1
Laptop - HP Spectre x360 (Model 13-ae053na) Processor I7 8th Gen, 16GB Ram

**Comment by huycozy** [comment] 2022-08-29 02:34
Hi @HugoCSWork, thanks for confirming. 
I'll be closing this issue since it has already been fixed on the master channel. The fix should land on the stable channel in future releases.
If you still experience this issue on the master channel or later versions of flutter, kindly file a new issue.
Thank you!

**Closed by huycozy** 2022-08-29 02:34 UTC
Labels: in triage
