### ISSUE TITLE
[tool] Target unpack_windows_uwp failed: Exception: Missing clientSourceDirectory

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#84489] opened 2021-06-12 09:51 UTC
## Info
- Visual Studio Installer: (`通用 Windows 平台开发` equals to `Universal Windows Platform development`)
  ![image](https://user-images.githubusercontent.com/15884415/121772270-fa57cd80-cba6-11eb-93aa-0444f09122fe.png)
- flutter doctor -v: (just synced with the upstream)
  <details>
  
  ```
  [√] Flutter (Channel master, 2.3.0-17.0.pre.337, on Microsoft Windows [Version 10.0.19043.985], locale zh-CN)
    • Flutter version 2.3.0-17.0.pre.337 at J:\SDK\flutter-master
    • Upstream repository https://github.com/AlexV525/flutter
    • Framework revision ea6b6d0178 (2 hours ago), 2021-06-12 03:39:04 -0400
    • Engine revision 5d422a2e71
    • Dart version 2.14.0 (build 2.14.0-204.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
  
  [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0
  
  [√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at J:\IDEs\apps\IDEA-U\ch-0\211.6693.111
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233
  
  [√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19043.985]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 91.0.4472.101
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 89.0.774.54
  ```
  </details>

## Step to reproduce
1. `flutter create uwp_demo`
2. `flutter run -d winuwp`

## Logs
<details>

```
[  +58 ms] executing: [J:\SDK\flutter-master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ea6b6d01789949e23ae84718351b08e87ecb6c48
[        ] executing: [J:\SDK\flutter-master/] git tag --points-at ea6b6d01789949e23ae84718351b08e87ecb6c48
[  +71 ms] Exit code 0 from: git tag --points-at ea6b6d01789949e23ae84718351b08e87ecb6c48
[   +1 ms] executing: [J:\SDK\flutter-master/] git describe --match *.*.* --long --tags ea6b6d01789949e23ae84718351b08e87ecb6c48
[ +127 ms] Exit code 0 from: git describe --match *.*.* --long --tags ea6b6d01789949e23ae84718351b08e87ecb6c48
[        ] 2.3.0-16.0.pre-337-gea6b6d0178
[   +4 ms] executing: [J:\SDK\flutter-master/] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [J:\SDK\flutter-master/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/AlexV525/flutter
[ +101 ms] executing: [J:\SDK\flutter-master/] git rev-parse --abbrev-ref HEAD
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +65 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] executing: J:/Android/SDK\platform-tools\adb.exe devices -l
[  +21 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +55 ms] executing: J:/Android/SDK\platform-tools\adb.exe devices -l
[  +15 ms] Skipping pub get: version match.
[  +84 ms] Generating J:\Coding\Garages\FlutterGarage\uwp_demo\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +96 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +3 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[   +1 ms] complete
[   +4 ms] Launching lib\main.dart on Windows (UWP) in debug mode...
[   +4 ms] J:\SDK\flutter-master\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev J:\SDK\flutter-master\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root J:\SDK\flutter-master\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\alexv\AppData\Local\Temp\flutter_tools.41d91b1c\flutter_tool.da81fcb5\app.dill --packages J:\Coding\Garages\FlutterGarage\uwp_demo\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --initialize-from-dill build\8dc25f9ea0dde274efae03d7664ce829.cache.dill.track.dill --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[  +89 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +30 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "0ef76b37",
               "installDate": "2021-03-27T06:12:39Z",
               "installationName": "VisualStudio/16.9.2+31112.23",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.9.31112.23",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "功能强大的 IDE，供学生、开放源代码参与者和个人免费使用",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.9#16.9.2",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2021-03-27T06:12:39.2046247Z",
               "catalog": {
                 "buildBranch": "d16.9",
                 "buildVersion": "16.9.31112.23",
                 "id": "VisualStudio/16.9.2+31112.23",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.9.2",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "2",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.9.2+31112.23",
                 "requiredEngineVersion": "2.9.3365.38425"
               },
               "properties": {
                 "campaignId": "491550614.1593607331",
                 "channelManifestId": "VisualStudio.16.Release/16.9.2+31112.23",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
Building Windows UWP application...
[  +86 ms] <- compile package:uwp_demo/main.dart
[   +1 ms] executing: J:\SDK\flutter-master\bin\flutter --verbose assemble --no-version-check --output=build -dTargetPlatform=windows-uwp-x64 -dTrackWidgetCreation=true -dBuildMode=debug -dTargetFile=J:\Coding\Garages\FlutterGarage\uwp_demo\lib\main.dart -dTreeShakeIcons="false" -dDartObfuscation=false --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== debug_bundle_windows_assets_uwp
[  +11 ms] List of devices attached
[   +2 ms] List of devices attached
[ +646 ms] [  +65 ms] executing: [J:\SDK\flutter-master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +53 ms] [  +63 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] ea6b6d01789949e23ae84718351b08e87ecb6c48
[        ] [        ] executing: [J:\SDK\flutter-master/] git tag --points-at ea6b6d01789949e23ae84718351b08e87ecb6c48
[  +72 ms] [  +72 ms] Exit code 0 from: git tag --points-at ea6b6d01789949e23ae84718351b08e87ecb6c48
[   +1 ms] [   +1 ms] executing: [J:\SDK\flutter-master/] git describe --match *.*.* --long --tags ea6b6d01789949e23ae84718351b08e87ecb6c48
[ +137 ms] [ +136 ms] Exit code 0 from: git describe --match *.*.* --long --tags ea6b6d01789949e23ae84718351b08e87ecb6c48
[        ] [        ] 2.3.0-16.0.pre-337-gea6b6d0178
[   +4 ms] [   +4 ms] executing: [J:\SDK\flutter-master/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] [  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [J:\SDK\flutter-master/] git ls-remote --get-url origin
[  +34 ms] [  +34 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/AlexV525/flutter
[  +57 ms] [  +57 ms] executing: [J:\SDK\flutter-master/] git rev-parse --abbrev-ref HEAD
[  +41 ms] [  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[  +52 ms] [  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +87 ms] [  +87 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] [   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +35 ms] [  +36 ms] Initializing file store
[  +11 ms] [  +11 ms] Done initializing file store
[  +33 ms] [  +33 ms] Skipping target: gen_localizations
[   +8 ms] [   +8 ms] Skipping target: gen_dart_plugin_registrant
[        ] [        ] unpack_windows_uwp: Starting due to {}
[ +752 ms] [ +752 ms] Skipping target: kernel_snapshot
[   +4 ms] [   +4 ms] Persisting file store
[   +7 ms] [   +7 ms] Done persisting file store
[   +3 ms] [   +8 ms] "flutter assemble" took 978ms.
[   +6 ms] [   +4 ms] Target unpack_windows_uwp failed: Exception: Missing clientSourceDirectory: J:\SDK\flutter-master\bin\cache\artifacts\engine\windows-x64\cpp_client_wrapper
[   +1 ms]            #0      unpackDesktopArtifacts (package:flutter_tools/src/build_system/targets/desktop.dart:62:7)
[        ]            #1      UnpackWindowsUwp.build (package:flutter_tools/src/build_system/targets/windows.dart:159:29)
[        ]            #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:27)
[        ]            <asynchronous suspension>
[        ]            #3      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
[        ]            <asynchronous suspension>
[        ]            #6      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[        ]            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #9      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #15     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[   +4 ms] [   +4 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[ +259 ms] [ +260 ms] ensureAnalyticsSent: 259ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[+3572 ms] Exception: Unable to generate build files
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:571:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[   +9 ms] "flutter run" took 6,550ms.
```
</details>

**Comment by AlexV525** [comment] 2021-06-12 12:27
Removed mirror site and tested again, found an abnormal behavior when the `flutter-cpp-client-wrapper.zip` is downloaded, it's not been extracted after downloaded. After I delete all artifacts, I saw a `HttpException` when downloading, which seems cause this problem.

```
[+6575 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools...
[   +6 ms] HttpException: Connection closed before full header was received, uri = https://storage.googleapis.com/flutter_infra_release/flutter/5d422a2e71c023da199ced3aa88445cbe9a3189e/windows-x64/flutter-cpp-client-wrapper.zip
[   +2 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools... (completed in 7ms)
[        ] Downloading windows-x64/flutter-cpp-client-wrapper tools...
[+1025 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/5d422a2e71c023da199ced3aa88445cbe9a3189e/windows-x64/flutter-cpp-client-wrapper.zip md5 hash: vJ+hY1Qe8WGkdL2R3teBVg==
[ +703 ms] Downloading windows-x64/flutter-cpp-client-wrapper tools... (completed in 1,728ms)
```

**Comment by AlexV525** [comment] 2021-06-12 12:38
A clear install with Flutter SDK does not contain `cpp_client_wrapper` after all required artifacts have been downloaded.
![image](https://user-images.githubusercontent.com/15884415/121776188-0c913600-cbbe-11eb-9df1-05c24e77356e.png)

**Comment by AlexV525** [comment] 2021-06-12 14:49
Related to #82917, and it's a more specific problem.

**Comment by AlexV525** [comment] 2021-06-12 15:23
Maybe also related to #82723 . /cc @stuartmorgan @jonahwilliams

**Comment by jonahwilliams** [comment] 2021-06-12 19:22
Duplicate of https://github.com/flutter/flutter/issues/82723  (Its the same issue)

**Closed by jonahwilliams** 2021-06-12 19:22 UTC
Labels: e: uwp, platform-windows, tool
