### ISSUE TITLE
Add option to create plugin with Swift

### ISSUE THREAD

**Issue by Gustash** [flutter/flutter#10143] opened 2017-05-17 16:45 UTC
Currently `flutter create --plugin example_plugin` creates a skeleton for a plugin with Obj-C for iOS. There should be an option to start the plugin directory with Swift instead of Obj-C.

**Comment by eseidelGoogle** [comment] 2017-05-17 17:08
I think this is a dupe of https://github.com/flutter/flutter/issues/7312?

**Closed by eseidelGoogle** 2017-05-17 17:08 UTC

**Comment by Gustash** [comment] 2017-05-18 08:35
Whoops, I looked but didn't find that one. Sorry. Yes, it is a dupe. Thank you
