### ISSUE TITLE
The bad performance for TextField in iOS when type in something.

### ISSUE THREAD

**Issue by 7syw** [flutter/flutter#35577] opened 2019-07-04 06:32 UTC
Hi, 
we got a really bad performance issue for textfield widget, the application would be hang on for a second when type in a couple of words with the keyboard. it is a really big issue for us. we only faced this issue for iOS, but can not reproduce it for android. please help for this issue, any workaround or suggested widget could fix this issue.

here is the code for TextField.
`TextField(
                  decoration: InputDecoration(
                    labelText: '请输入',   //please type in.
                  ),
                  autofocus: true,
                  maxLength: 500,
                  maxLines: null,
                  controller: _controller,
)`

here is the information of flutter version.
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (9 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

Yawei

**Comment by 7syw** [comment] 2019-07-04 06:42
BTW, 
the issue could be reproduced both for iOS 12.3.1 and 12.1.

**Comment by 7syw** [comment] 2019-07-05 14:09
flutter experts,  any ideas or suggestion?

**Comment by calvinmuller** [comment] 2019-07-07 12:50
don’t use platform views if you using a webview or google maps. it’s a known issue
https://github.com/flutter/flutter/issues/31138 so i’d suggest trying to find some other route or don’t use text input - flutters only draw back imho

**Comment by 7syw** [comment] 2019-07-08 00:42
@calvinmuller sounds bad, thanks anyway.

**Comment by gisinator** [comment] 2019-07-08 06:58
It also happens without webviews or google maps. I hope the devs can fix it, soon

**Comment by pythoneer** [comment] 2019-07-08 07:28
@gisinator are you sure? If so, can you reproduce it and report it back to the main issue https://github.com/flutter/flutter/issues/31138? This is one probably getting closed due to being a duplicate

**Comment by gisinator** [comment] 2019-07-08 07:36
Right, let's make sure we're talking about the same thing: My testers reported about this keyboard-lag issue a couple of weeks ago. It happens on my login page where I do have a "Webview" Widget with terms and conditions loaded from a webpage, but it also happens once you're registered and actually use the app, where there is no more webview involved. Even when you close and reopen the app and pass the login page (since you're already logged in), the lag occurs in an inputfield.
I dont use Google Maps at all.
So, are we talking about the same thing? :)

**Comment by gisinator** [comment] 2019-07-08 07:41
Update: Oh ok, I just read about the embedded_views_preview key and since it is set to true for the login page, it 's basically true whenever you use the app, no matter whether login-page is called or not. My bad.

**Comment by pythoneer** [comment] 2019-07-08 16:57
@gisinator that's right. It does not even matter if you use any embedded view (webview, maps ...) in your app at all. Just the fact that you have activated the `embedded_views_preview` is enough to trigger the behavior.

**Comment by 7syw** [comment] 2019-07-09 00:40
sounds stranger, what's the relationship between this setting and current issue? we set it as true cause   a webcast widget used in our app.  so far the webcast doesn't work anymore once switch off it in our app. anyway we expect the flutter team could solve this issue asap.

**Comment by dnfield** [comment] 2019-07-09 05:33
This is a duplicate of #31138 - please follow that issue for updates.

Also, please update that issue if this is still an issue on the current stable release (1.7.8-hotfix.something).

**Closed** 2019-07-09 05:33 UTC
