### ISSUE TITLE
show data Firestore in radio button(group) 

### ISSUE THREAD

**Issue by SilasPaes** [flutter/flutter#39763] opened 2019-09-03 18:32 UTC
Hi, I have 4 options radio button in app, I want to leave the option checked when o user close and open app again, I am using Firestore.
my code:
```
void _handleRadioValueChange(int value) {
    setState(() {
      _radioValue = value;
  
      switch (_radioValue) {
        case 0:   // SEM AVALIAÇÃO
          Firestore.instance
        .collection('testando')
        .document(widget.suid)
        .collection(widget.uid).document(widget.uid)
        .setData({'Avaliacao': 0,
        'uid': widget.uid,
        'isExcelente': true, 
        });        
          break;
        case 1: // EXCELENTE
          Firestore.instance
        .collection('testando')
        .document(widget.suid)
        .collection(widget.uid).document(widget.uid)
        .setData({'Avaliacao': 5,
        'uid': widget.uid,
        'isExcelente': true, 
        });
          break;
        case 2: // NORMAL
          Firestore.instance
        .collection('testando')
        .document(widget.suid)
        .collection(widget.uid).document(widget.uid)
        .setData({'Avaliacao': 3,
        'uid': widget.uid,
        'isNormal': true, 
        });
          break;
        case 3: // DEIXA A DESEJAR
          Firestore.instance
        .collection('testando')
        .document(widget.suid)
        .collection(widget.uid).document(widget.uid)
        .setData({'Avaliacao': 1,
        'uid': widget.uid,
        'isDesejar': true, 
        });
        break;
      }
    });
}

@override
  Widget build(BuildContext context) {    
   
     return Scaffold(   
       backgroundColor: Colors.teal[300],     
        body: Center(
          child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
         
  Center(
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
        Column(
          children: <Widget>[
          Text("Sem avaliação"),
          Radio(
          value: 0,
          groupValue: _radioValue,
          onChanged: _handleRadioValueChange,
              ),
        ],),

        Column(
          children: <Widget>[
          Text("Excelente"),
          Radio(                       
          value: 1, 
          groupValue: _radioValue,
          onChanged: _handleRadioValueChange,
              ),
        ],),
        
        Column(
          children: <Widget>[
          Text("Normal"),
          Radio(
          value: 2,
          groupValue: _radioValue,
          onChanged: _handleRadioValueChange,
              ),
        ],),
        
        Column(
          children: <Widget>[
          Text("Deixa a desejar"),
          Radio(
          value: 3,
          groupValue: _radioValue,
          onChanged: _handleRadioValueChange,
              ),
        ],),

      ],),
    ),
```

**Comment by superciccio** [comment] 2019-09-04 07:32
Hi, this kind of question are for StackOverflow.

anyway there is an issue, that I can see, you're doing much work in the `setState` it should only have _radioValue = value;

_radioValue must be setted in the `initState `of the `StatefulWidget`, then everything should work as expected.

just giving you an idea :)

**Comment by BondarenkoStas** [comment] 2019-09-04 11:12
@SilasPaes once again, this kind of questions is better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation.
It would be helpful for the community if you post it to stackoverflow, and after solving it put the link here.
Closing it as it's not an issue report.
If it will turn out that the problem is related to flutter itself, feel free to open a new issue. Thank you for understanding.

**Closed by BondarenkoStas** 2019-09-04 11:12 UTC
