### ISSUE TITLE
url_launcher opens mailto link with plus(+) character in subject and body

### ISSUE THREAD

**Issue by kashishkhullar** [flutter/flutter#75552] opened 2021-02-06 09:54 UTC
## Steps to Reproduce
1. Create a new flutter app
2. Add [url_launcher](https://pub.dev/packages/url_launcher) package
3. Create URI
4. Create a button and call lauch( uri_instance.toString())
5. Clicking the button would opens Gmail in my case.

## Code
```dart

// To create email with params
final Uri _emailLaunchUri = Uri(
    scheme: 'mailto',
    path: GlobalStrings.email,
    queryParameters: {'subject': "This is my subject", 'body': "Hey Kashish here goes the body"},
  );

// To launch the link
launch(_emailLaunchUri.toString());

```

**Expected results:** 
Gmail app compose page opens with required body and subject having space separated words

**Actual results:** 
Gmail app compose page opens with required body and subject having "+" separated words

Screenshot
![image](https://user-images.githubusercontent.com/22838528/107114816-d26dfb80-688e-11eb-93d3-296528ade57b.png)

**Comment by parthdave93** [comment] 2021-02-07 09:10
The url launcher have
```
query = _makeQuery(query, 0, _stringOrNullLength(query), queryParameters);
```
when we do url.tostring what it generates is a url for launch something like this: `mailto:GlobalStrings.email?subject=Hey%20Kashish&body=body` in the code you have written it's generated like this: `mailto:GlobalStrings.email?subject=This+is+my+subject&body=Hey+Kashish+here+goes+the+body` why?

because when we pass queryparameters take a look at below code it goes to writeParameter function block for every paramters and we go to `Uri.encodeQueryComponent(value)` 
```
static String? _makeQuery(String? query, int start, int end,
      Map<String, dynamic /*String|Iterable<String>*/ >? queryParameters) {
    if (query != null) {
      if (queryParameters != null) {
        throw ArgumentError('Both query and queryParameters specified');
      }
      return _normalizeOrSubstring(query, start, end, _queryCharTable,
          escapeDelimiters: true);
    }
    if (queryParameters == null) return null;

    var result = StringBuffer();
    var separator = "";

    void writeParameter(String key, String? value) {
      result.write(separator);
      separator = "&";
      result.write(Uri.encodeQueryComponent(key));
      if (value != null && value.isNotEmpty) {
        result.write("=");
        result.write(Uri.encodeQueryComponent(value));
      }
    }

    queryParameters.forEach((key, value) {
      if (value == null || value is String) {
        writeParameter(key, value);
      } else {
        Iterable values = value;
        for (String value in values) {
          writeParameter(key, value);
        }
      }
    });
    return result.toString();
  }
```

which is stating that first every value will be encoded to utf8 and then the spaces will get transformed to + sign so that's the issue you're facing but it's not a bug.
```
/*
....
 * The component is first encoded to bytes using [encoding].
   * The default is to use [utf8] encoding, which preserves all
   * the characters that don't need encoding.

   * Then the resulting bytes are "percent-encoded". This transforms
   * spaces (U+0020) to a plus sign ('+') and all bytes that are not
   * the ASCII decimal digits, letters or one of '-._~' are written as
   * a percent sign '%' followed by the two-digit hexadecimal
   * representation of the byte.
   ....
*/
static String encodeQueryComponent(String component,
      {Encoding encoding = utf8}) {
    return _Uri._uriEncode(_Uri._unreservedTable, component, encoding, true);
  }
```

replace your code with this:
```
    var body = "Hey Kashish here goes the body";
    var subject = "This is my subject";
    final Uri _emailLaunchUri = Uri(
      scheme: 'mailto',
      path: GlobalStrings.email,
      query: 'subject=$subject&body=$body',
    );
```

**Comment by parthdave93** [comment] 2021-02-07 09:11
> ## Steps to Reproduce
> 1. Create a new flutter app
> 2. Add [url_launcher](https://pub.dev/packages/url_launcher) package
> 3. Create URI
> 4. Create a button and call lauch( uri_instance.toString())
> 5. Clicking the button would opens Gmail in my case.
> 
> ## Code
> ```dart
> // To create email with params
> final Uri _emailLaunchUri = Uri(
>     scheme: 'mailto',
>     path: GlobalStrings.email,
>     queryParameters: {'subject': "This is my subject", 'body': "Hey Kashish here goes the body"},
>   );
> 
> // To launch the link
> launch(_emailLaunchUri.toString());
> ```
> 
> **Expected results:**
> Gmail app compose page opens with required body and subject having space separated words
> 
> **Actual results:**
> Gmail app compose page opens with required body and subject having "+" separated words
> 
> Screenshot
> ![image](https://user-images.githubusercontent.com/22838528/107114816-d26dfb80-688e-11eb-93d3-296528ade57b.png)

The url launcher have
```
query = _makeQuery(query, 0, _stringOrNullLength(query), queryParameters);
```
when we do url.tostring what it generates is a url for launch something like this: `mailto:GlobalStrings.email?subject=Hey%20Kashish&body=body` in the code you have written it's generated like this: `mailto:GlobalStrings.email?subject=This+is+my+subject&body=Hey+Kashish+here+goes+the+body` why?

because when we pass queryparameters take a look at below code it goes to writeParameter function block for every paramters and we go to `Uri.encodeQueryComponent(value)` 
```
static String? _makeQuery(String? query, int start, int end,
      Map<String, dynamic /*String|Iterable<String>*/ >? queryParameters) {
    if (query != null) {
      if (queryParameters != null) {
        throw ArgumentError('Both query and queryParameters specified');
      }
      return _normalizeOrSubstring(query, start, end, _queryCharTable,
          escapeDelimiters: true);
    }
    if (queryParameters == null) return null;

    var result = StringBuffer();
    var separator = "";

    void writeParameter(String key, String? value) {
      result.write(separator);
      separator = "&";
      result.write(Uri.encodeQueryComponent(key));
      if (value != null && value.isNotEmpty) {
        result.write("=");
        result.write(Uri.encodeQueryComponent(value));
      }
    }

    queryParameters.forEach((key, value) {
      if (value == null || value is String) {
        writeParameter(key, value);
      } else {
        Iterable values = value;
        for (String value in values) {
          writeParameter(key, value);
        }
      }
    });
    return result.toString();
  }
```

which is stating that first every value will be encoded to utf8 and then the spaces will get transformed to + sign so that's the issue you're facing but it's not a bug.
```
/*
....
 * The component is first encoded to bytes using [encoding].
   * The default is to use [utf8] encoding, which preserves all
   * the characters that don't need encoding.

   * Then the resulting bytes are "percent-encoded". This transforms
   * spaces (U+0020) to a plus sign ('+') and all bytes that are not
   * the ASCII decimal digits, letters or one of '-._~' are written as
   * a percent sign '%' followed by the two-digit hexadecimal
   * representation of the byte.
   ....
*/
static String encodeQueryComponent(String component,
      {Encoding encoding = utf8}) {
    return _Uri._uriEncode(_Uri._unreservedTable, component, encoding, true);
  }
```

replace your code with this:
```
    var body = "Hey Kashish here goes the body";
    var subject = "This is my subject";
    final Uri _emailLaunchUri = Uri(
      scheme: 'mailto',
      path: GlobalStrings.email,
      query: 'subject=$subject&body=$body',
    );
```

**Comment by darshankawar** [comment] 2021-02-08 07:54
@kashishkhullar 
Can you provide `flutter doctor -v` ? Also,  what are the steps to create URI, as you mentioned in step 3 ?

**Comment by kashishkhullar** [comment] 2021-02-08 15:40
### Flutter Doctor output:

<details>
<summary>flutter doctor -v</summary>

```cmd
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.746], locale en-IN)
    • Flutter version 1.22.6 at G:\flutter_windows_v1.12.13+hotfix.5-stable\flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2) 
    • Android SDK at G:\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = G:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • Nokia 5 1 Plus (mobile) • PDAID18092305525 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```
</details>

### Source code of a sample app to replicate this issue:
<details>
<summary>source code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final Uri _emailLaunchUri = Uri(scheme: 'mailto', path: 'smith@example.com', queryParameters: {'subject': 'Example Subject & Symbols are allowed!'});

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: RaisedButton(
        onPressed: () {
          launch(_emailLaunchUri.toString());
        },
        child: Text("Send email"),
      )),
    );
  }
}

```
</details>

### URI used for this issue
I have used the same code to create the URI as given in the documentation.
```dart
import 'dart:core';
import 'package:url_launcher/url_launcher.dart';

final Uri _emailLaunchUri = Uri(
  scheme: 'mailto',
  path: 'smith@example.com',
  queryParameters: {
    'subject': 'Example Subject & Symbols are allowed!'
  }
);

// ...

// mailto:smith@example.com?subject=Example+Subject+%26+Symbols+are+allowed%21
launch(_emailLaunchUri.toString());
```
### Screenshots using the URI in the documentation
![image](https://user-images.githubusercontent.com/22838528/107242281-d26a2900-6a51-11eb-83e0-bda5be57b432.png)
![image](https://user-images.githubusercontent.com/22838528/107242302-d7c77380-6a51-11eb-9cd9-5730154f968b.png)

**Comment by parthdave93** [comment] 2021-02-09 05:14
Need to understand the difference between query and QueryParamters difference in uri_launcher package

as 
```
    final Uri _emailLaunchUri = Uri(
      scheme: 'mailto',
      path: "GlobalStrings.email",
      query: 'subject=$subject&body=$body',
    );
```
this code returns `mailto:GlobalStrings.email?subject=Hey%20Kashish&body=body when we do _emailLaunchUri.toString()`
while 
for this
```
_emailLaunchUriIssue = Uri(
      scheme: 'mailto',
      path: "GlobalStrings.email",
      queryParameters: {'subject': "This is my subject", 'body': "Hey Kashish here goes the body"},
    );
```
toString returns this: mailto:GlobalStrings.email?subject=This+is+my+subject&body=Hey+Kashish+here+goes+the+body 
which reason we are encoding queryParamerts as application/x-www-form-urlencoded ? 

code which replaces space with + 
```
 static String encodeQueryComponent(String component,
      {Encoding encoding = utf8}) {
    return _Uri._uriEncode(_Uri._unreservedTable, component, encoding, true);
  }
```
exactly what's the difference between query and queryParameters ?
and for mobile users `mailto:GlobalStrings.email?subject=Hey%20Kashish&body=body` this is the perfect intent which is missing from documentation https://pub.dev/packages/url_launcher

I think in documentation there should be clear red line to what differences are if any. else there's a bug in the `encodeQueryComponent` for queryParameters

**Comment by darshankawar** [comment] 2021-02-09 06:14
Thanks @kashishkhullar for code sample. Seems to be happening on Android 10 devices, since it doesn't occur on 8.1.0 device I tried.

<img width="317" alt="Screenshot 2021-02-09 at 11 38 03 AM" src="https://user-images.githubusercontent.com/67046386/107322925-60cec100-6acb-11eb-99f2-818d32a431a0.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2021-02-09 06:16
Similar to https://github.com/flutter/flutter/issues/73717

**Comment by stuartmorgan** [comment] 2021-02-22 12:32
> Need to understand the difference between query and QueryParamters difference in uri_launcher package

They aren't part of `url_launcher`, they are part of `Uri`, which is from the Dart SDK.

> this code returns `mailto:GlobalStrings.email?subject=Hey%20Kashish&body=body when we do _emailLaunchUri.toString()`

Which is an invalid URI, because it contains spaces.

> toString returns this: `mailto:GlobalStrings.email?subject=This+is+my+subject&body=Hey+Kashish+here+goes+the+body`

Which is a correctly encoded URI.

> exactly what's the difference between query and queryParameters ?

The `Uri` constructor documentation explicitly addresses this. In the former, it is your responsibility to provide a valid, URI-escaped query string (which your code above does not, this the invalid resulting URI.)

> and for mobile users `mailto:GlobalStrings.email?subject=Hey%20Kashish&body=body` this is the perfect intent which is missing from documentation https://pub.dev/packages/url_launcher

No, that's an invalid URI; the example in the `url_launcher` docs is there specifically because many people did what you are suggesting and got bad outcomes because theh were paying invalid URIs. (Subjects or bodies with "&"s being one common source of bugs, for instance.)


As for the specific issue you are having, does this happen with a different `mailto` handler? This looks like a bug in the handler to me, since `+` is a standard encoding for spaces in query parameters.

**Comment by pedromassangocode** [comment] 2021-04-07 12:45
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-07 12:45 UTC
Labels: P5, found in release: 1.22, has reproducible steps, p: first party, p: url_launcher, plugin, waiting for customer response

**Comment by d9media** [comment] 2021-04-13 14:23
Confirming this issue

**Comment by stuartmorgan** [comment] 2021-04-13 14:28
See https://github.com/flutter/flutter/issues/73717#issuecomment-816039811 for more details; this general issue is now tracked there.
