### ISSUE TITLE
swift FlutterViewController memory not released after page return

### ISSUE THREAD

**Issue by zhaoxianxin** [flutter/flutter#129935] opened 2023-07-04 05:40 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Flutter 3.10.0，3.10.5 
2.      let engineGroup = FlutterEngineGroup(name: "ds-flutter-group", project: nil);
         let engine = engineGroup.makeEngine(withEntrypoint: nil, libraryURI: nil, initialRoute: path)
         engine.run()
        GeneratedPluginRegistrant.register(with: engine)
        
        let vc = DSMyFlutterViewController(engine: engine, nibName: nil, bundle: nil)
        let navc = from.navigationController ?? UIViewController.currentNavigationController()
        navc?.pushViewController(vc, animated: true)
3.goback to Native page, FlutterViewController didn't deinit

### Expected results

FlutterViewController memory release

### Actual results

FlutterViewController memory didn't release

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```tyzl@192 workplace % flutter doctor

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Found an existing Pub cache at /Users/tyzl/.pub-cache.
It can be repaired by running `dart pub cache repair`.
It can be reset by running `dart pub cache clear`.
Found an existing Dart Analysis Server cache at /Users/tyzl/.dartServer.
It can be reset by deleting /Users/tyzl/.dartServer.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.4 22F66 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!


</details>

**Comment by danagbemava-nc** [comment] 2023-07-04 07:48
Hi, @zhaoxianxin 

this is a duplicate of https://github.com/flutter/flutter/issues/126560

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2023-07-04 07:48 UTC
Labels: in triage
