### ISSUE TITLE
a bug of RichText display when debugging an Android project.

### ISSUE THREAD

**Issue by ljx697** [flutter/flutter#123515] opened 2023-03-27 03:28 UTC
Hello flutter team, I encountered a bug of RichText display when debugging an Android project. The wiget hierarchy is shown in the code. 
 RichText(
                textScaleFactor: 1.4,
                text: TextSpan(children: [
                  TextSpan(
                      text: "f",
                      style: TextStyle(
                          color: Colors.blueAccent,
                          fontSize: 17,
                          fontWeight: FontWeight.w400,
                          height: (17 + 4.0) / 17,
                          wordSpacing: 1,
                          letterSpacing: 1,
                          fontFamily: "default")
                      // style: TextStyle(color: Colors.blueAccent ,fontFamily: "default")
                      ),
                  TextSpan(
                      text: "l",
                      style: TextStyle(
                          color: Colors.grey,
                          fontSize: 17,
                          fontWeight: FontWeight.w400,
                          height: (17 + 4.0) / 17,
                          wordSpacing: 1,
                          letterSpacing: 1,
                          textBaseline: TextBaseline.alphabetic,
                          fontFamily: "default")
                      // style: TextStyle(color: Colors.blueAccent ,fontFamily: "default")
                      ),
                  TextSpan(
                      text: "h",
                      style: TextStyle(
                          color: Colors.grey,
                          fontSize: 17,
                          fontWeight: FontWeight.w400,
                          height: (17 + 4.0) / 17,
                          wordSpacing: 1,
                          letterSpacing: 1,
                          textBaseline: TextBaseline.alphabetic,
                          fontFamily: "default")
                      // style: TextStyle(color: Colors.blueAccent ,fontFamily: "default")
                      ),
                ])),
As the screenshot shown below, there are some letter display problems on flutter pages. I found that flutter would display letter f and l repeatedly. Besides, if the final letter is letter h, then it would not be displayed. We tested on HUAWEI mate 40 and Redmi 9A devices, with system font set as Default.
 
![image](https://user-images.githubusercontent.com/23309530/227833691-ae567e6e-bd22-4438-ac13-577ebffef420.png)

If there are any errors in my code, please do let me know.

**Comment by ljx697** [comment] 2023-03-28 02:38
Thank you for your answer, I have confirmed the question on https://github.com/flutter/flutter/issues/123529。

**Comment by huycozy** [comment] 2023-03-28 03:23
I can see your Flutter version is `3.3.9`, please retry on the latest stable or master channels to see if the issue is fixed or not (as I don't have such devices, I can not verify this). 

Also, please check this on other devices as well.

**Comment by jason-simmons** [comment] 2023-03-28 19:23
See https://github.com/flutter/flutter/issues/104884.  This should be fixed on the current master branch.

**Closed** 2023-04-18 04:10 UTC
Labels: waiting for customer response, in triage
