### ISSUE TITLE
Incorrect clipping for touched ListTile

### ISSUE THREAD

**Issue by mauriceraguseinit** [flutter/flutter#140316] opened 2023-12-18 11:54 UTC
### Steps to reproduce

1. Add a ListView 
2. return a ListTile Widget with a Text Widget as title property with onTap action in itemBuilder
3. Wrap ListView in Padding (top value eg. 30)
4. scroll list up until the first ListTile is cutted by 50%
5. tap and hold the ListTile

### Expected results

Highlight/Focused color of ListTile is clipped by 50% ListTile height

### Actual results

Highlight/focus box is complete visible (no clipping)

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Scaffold(
          body: Padding(
            padding: const EdgeInsets.only(top: 30),
            child: ListView.builder(
              itemBuilder: (_, __) {
                return ListTile(
                  onTap: () {},
                  title: const Text('TEST'),
                );
              },
            ),
          ),
        ),
      ),
    ),
  );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/80750776/07ae3631-aaa5-4aa3-9643-62c1c814c52b

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.16.2, on macOS 14.2 23C64 darwin-x64, locale de-DE)
    • Flutter version 3.16.2 on channel stable at /Users/mraguse/fvm/versions/3.16.2
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.2.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/mraguse/fvm/versions/3.16.2. Consider adding /Users/mraguse/fvm/versions/3.16.2/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (3 weeks ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mraguse/Library/Android/sdk
    • Platform android-34, build-tools 30.0.3
    • ANDROID_HOME = /Users/mraguse/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 14.2 23C64 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 120.0.6099.109
    ! Error: iPhone von Maurice has recently restarted. Xcode will continue when iPhone von Maurice is unlocked. (code -14)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-12-19 06:54
Hi @mauriceraguseinit, I believe this is caused by how `Ink` works in the framework, it paints on the nearest `Material` ancestor. In this case, this would be your `Scaffold`. 

Can you try wrapping your `ListTile` in a `Material` widget to see if you still experience this issue?

https://api.flutter.dev/flutter/material/InkResponse-class.html

**Comment by mauriceraguseinit** [comment] 2023-12-19 07:30
Hi thanks for your response... Wrapping the ListTile or the whole ListView works here to clip the Ink.

**Comment by danagbemava-nc** [comment] 2023-12-20 07:12
Ideally, no, but this is how `Ink` currently behaves; and at its core, `ListTile` is an `Ink` widget wrapped in an `InkWell`. There are issues tracking improving this behaviour in https://github.com/flutter/flutter/issues/73315 & https://github.com/flutter/flutter/issues/86584 that you can follow for updates. 

For now, you can work around using the `Material` either on the `ListTile` or the `ListView`. 

Kindly follow up in the issues linked above for updates.

Closing from here.

Thank you

**Closed by danagbemava-nc** 2023-12-20 07:12 UTC
Labels: in triage
