### ISSUE TITLE
Engine compiled error: compile_platform.gni file occurs error

### ISSUE THREAD

**Issue by lulusudoku** [flutter/flutter#19408] opened 2018-07-16 14:19 UTC
I want to build engine, and I referred this guide:https://github.com/flutter/engine/wiki/Rolling-Dart, but I encountered below issues, can anyone help me.. Thanks.
```
+ flutter/tools/gn --goma --unoptimized --runtime-mode=debug
gn gen --check in out/host_debug_unopt
ERROR at //third_party/dart/utils/compile_platform.gni:17:3: Assertion failed.
  assert(defined(invoker.sources), "Need 'sources' in $target_name")
  ^-----
Need 'sources' in non_strong_platform
See //flutter/lib/snapshot/BUILD.gn:221:1: whence it was called.
compile_platform("non_strong_platform") {
^----------------------------------------
See //flutter/BUILD.gn:11:5: which caused the file to be included.
    "$flutter_root/lib/snapshot:generate_snapshot_bin",
    ^-------------------------------------------------
```
I updated dart_reversion in DEPS file and executed `gclient sync`, then I can not compile.

**Comment by Kila2** [comment] 2019-06-04 08:35
same issue how to fix it.

**Comment by Kila2** [comment] 2019-06-10 07:36
I found that the cause of this problem may be that the src/third_party/dart/tools/sdks/dart-sdk/bin directory is empty.

**Comment by markusaksli-nc** [comment] 2020-10-19 11:06
Hi @lulusudoku @Kila2 
Is this still a relevant issue for you?
Thank you

**Comment by Kila2** [comment] 2020-10-19 11:11
> Hi @lulusudoku @Kila2
> Is this still a relevant issue for you?
> Thank you

No, I don't remember a bit. It should be possible to close the issue

**Comment by markusaksli-nc** [comment] 2020-10-19 11:14
Thank you, closing this. If anyone else runs into this problem please open a new issue describing your case.

**Closed by markusaksli-nc** 2020-10-19 11:14 UTC
Labels: P4, engine, waiting for customer response
