### ISSUE TITLE
Error connecting to the service protocol: WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://127.0.0.1:8102/ws#' was not upgraded to websocket

### ISSUE THREAD

**Issue by JDoe34** [flutter/flutter#13832] opened 2018-01-02 15:03 UTC
Hello, I am trying to run the unmodified Flutter demo app and get the following error message (same msg if I run directly from AndroidStudio or on the commandline (w or w/o local administrator rights)

[   +9 ms] Connecting to service protocol: http://127.0.0.1:8102/
[ +119 ms] Error connecting to the service protocol: WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://127.0.0.1:8102/ws#' was not upgraded to websocket
[{"event":"app.stop","params":{"appId":"84ae9a0f-891f-4123-b492-627c7a65c01f"}}]

This happens when running on an emulator or on an Android 6 phone.
Win7 / 64 Bit. Corporate Laptop, Windows own firewall. 

## Logs
```
C:\Users\user@domain.com\AndroidStudioProjects\flutter_app>flutter run -d emulator-5554 -v > runlog.txt
[  +71 ms] Error connecting to the service protocol: WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://127.0.0.1:8
104/ws#' was not upgraded to websocket

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:341)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
<asynchronous suspension>
#3      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      new Future.sync (dart:async/future.dart:222)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#10     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1120)
#14     _CustomZone.run (dart:async/zone.dart:1001)
#15     runZoned (dart:async/zone.dart:1467)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#19     main (file:///c:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

Flutter analyze output:

Analyzing C:\Users\user@domain.com\AndroidStudioProjects\flutter_app...
  lint - Name types using UpperCamelCase at lib\generated\i18n.dart:26:7 - camel_case_types
1 issue found.
(Ran in 15.4s)

## Flutter Doctor

[√] Flutter (on Microsoft Windows [Version 6.1.7601], locale de-DE, channel alpha)
    • Flutter at c:\flutter
    • Framework revision 8f65fec5f5 (3 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\user@domain.com\AppData\Local\Android\android-sdk
    • Android NDK at C:\Users\user@domain.com\AppData\Local\Android\android-sdk\ndk-bundle
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = C:\Users\user@domain.com\AppData\Local\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

Error retrieving device properties for ro.product.cpu.abi:
error: closed

[√] Connected devices
    • emulator-5564                • emulator-5564    • android-arm • Android null (API null)
    • Android SDK built for x86 64 • emulator-5554    • android-x64 • Android 5.1.1 (API 22) (emulator)
    • x600                         • JNY95PZSSS5LUWSC • android-arm • Android 6.0 (API 23)

**Comment by cv0cv0** [comment] 2018-04-17 01:11
Error connecting to the service protocol: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 50031

**Comment by zoechi** [comment] 2018-07-16 15:32
@DanTup do you think this is a dup of #19056 ?

**Comment by DanTup** [comment] 2018-07-16 16:13
Definitely seems like a dupe of #11444, but not sure about the other one. My comments at https://github.com/flutter/flutter/issues/11444#issuecomment-405300827 apply here too.

**Comment by zoechi** [comment] 2018-07-16 16:38
Ok, tentatively closing as dup of #11444

**Closed by zoechi** 2018-07-16 16:38 UTC
