### ISSUE TITLE
debug_full_compile_millis regression

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#29177] opened 2019-03-11 19:52 UTC
Value for `basic_material_app_win__compile` and `complex_layout_win__compile` significantly regressed around commit https://github.com/flutter/flutter/commit/9b810b54d3e6aef2c14843a9aa4c5021d151bc17 (exact commit not super clear due to missing values and noise).

/cc @a-siva @aam

**Comment by goderbauer** [comment] 2019-03-11 19:53
`flutter_gallery_win__compile` shows the same problem.

**Comment by dnfield** [comment] 2019-03-11 20:20
We've had issues on the Windows machines with AV running and using a lot of resources.  It's very possible that the scanner  is causing this.

**Comment by goderbauer** [comment] 2019-03-11 20:27
@mklim Dan mentioned you were looking at the Virus Scanner on device lab machines. Did you change anything around that time? Are we currently excluding our working directory from scanning?

**Comment by dnfield** [comment] 2019-03-11 20:27
(This started after the most recent Windows Update on those machines.  I think @mklim might have looked at disabling it for that directory but I may be wrong).

**Comment by mklim** [comment] 2019-03-11 20:32
Discussed lab machines offline.

**Comment by dnfield** [comment] 2019-03-11 21:31
I'll leave this open for now - I've tried to exclude some more directories from scanning,b ut the machines are pegged at ~40-50% utilization by Windows Defender at all times right now.  Going to remove the today label.

**Comment by dnfield** [comment] 2019-03-11 21:33
Rebaselined the metrics so they don't show up as red for now in the dashboard.

**Comment by liyuqian** [comment] 2019-04-22 22:10
Any follow up? Or shall we close this bug?

**Comment by franciscojma86** [comment] 2019-07-30 17:47
This benchmark still shows regressions consistently. Should we mark this as TODAY again?

**Comment by a-siva** [comment] 2019-07-30 18:25
Are you referring to the windows version of this benchmark?

**Comment by franciscojma86** [comment] 2019-07-30 18:39
I'm talking about basic_material_app_win__compile debug_full_compile_millis. 

complex_layout_win__compile seems ok to me

**Comment by a-siva** [comment] 2019-07-30 21:05
The recent spike seems to have started after https://github.com/flutter/flutter/pull/36785

**Comment by franciscojma86** [comment] 2019-08-01 16:47
@zanderso

**Comment by liyuqian** [comment] 2019-09-30 22:45
Any update? Are we still working on this?

**Comment by liyuqian** [comment] 2019-11-21 00:48
I wasn't able to check the benchmark number back in Feb 2019 when this regression happened. @CaseyHillers : is this due to the newly introduced Redis memcache? I'd like to check the old numbers to see if this has been fixed.

**Comment by CaseyHillers** [comment] 2019-11-21 00:55
@liyuqian no those requests don't get cached, just the one that covers the whole page. 

@keyonghan do you know why this would be?

**Comment by keyonghan** [comment] 2019-11-21 01:07
I am not sure. BTW: all debug_full_compile_millis related metrics already went back to normal since around mid Oct.

**Comment by liyuqian** [comment] 2019-11-21 01:09
CC @digiter @godofredoc to see why we're missing early data.

**Comment by Hixie** [comment] 2019-12-02 23:23
It used to be called `release_size_bytes__dart1`, dunno if that matters. That said, I don't see historical data for that benchmark either.

**Comment by liyuqian** [comment] 2019-12-03 00:02
@Hixie : we've found the cause thanks to @keyonghan and @digiter . Cocoon only retrieves  metrics for the last 1500 commits. Last year, we don't have that many commits per year so 1500 commits can cover quite a long history. Now we've uploaded a lot more commits per year so we can only see a few months of history. As a temp workaround, @keyonghan is going to raise 1500 to 6000. Soon, we'll migrate the metrics to Skia perf so we can freely query any historic range.

**Comment by keyonghan** [comment] 2019-12-03 00:48
Deployed with 6000 records. You should be able to see the old data now @liyuqian

**Comment by liyuqian** [comment] 2019-12-03 19:33
@keyonghan : confirmed that I can now see the old data.

basic_material_app_win__compile debug_full_compile_millis is now at ~25000ms, and it was at ~22000ms back in February. So there's still a small regression, but much better than the regression in March (~35000ms).

I wonder if there's anything more we can do for this regression? Does anyone have any way to further improve it, or should just close it as this regression is so old that we probably can't simply revert anything.

**Comment by a-siva** [comment] 2019-12-03 23:42
is this a windows specific regression ?

**Comment by liyuqian** [comment] 2019-12-04 20:55
@a-siva : it seems so

**Comment by liyuqian** [comment] 2019-12-09 23:11
@a-siva : do you think if this issue is appropriate to be assigned to someone in the Dart team?

**Comment by CaseyHillers** [comment] 2020-01-16 23:44
Closing this since `basic_material_app_win_` and `complex_layout_win__compile` have been brought to a passing level as of October 2019

**Closed by CaseyHillers** 2020-01-16 23:44 UTC
Labels: dependency: dart, engine, passed secondary triage, severe: performance, severe: regression, team, team: infra, ❖ platform-windows
