### ISSUE TITLE
ios build error after upgrade to Flutter 3.10 ( 'textTheme' isn't defined for the class 'AppBarTheme'.)

### ISSUE THREAD

**Issue by fullflash** [flutter/flutter#126619] opened 2023-05-11 23:58 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

after upgrading to flutter 3.10 unable to build for ios

### Actual results

```
Failed to build iOS app
Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/flutter_neumorphic-3.2.0/lib/src/widget/app_bar.dart:183:29: Error: The getter 'textTheme' isn't defined for the class 'AppBarTheme'.
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

flutter doctor -v
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-x64, locale en-TR)
    • Flutter version 3.10.0 on channel stable at /Users/*****/SDK_all/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/*******/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • E25B3542-E984-48E8-87BA-BA53223E2924 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     •
      macOS 13.3.1 22E261 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript •
      Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!


```

</details>

tried flutter pub cache repair also deleting .pubcache folder and redownloading flutter 

also tried 
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by fullflash** [comment] 2023-05-12 01:14
had to downgrade to flutter 3.7.5

**Comment by kishan-dhankecha** [comment] 2023-05-12 05:22
This is not an error. `textTheme` property from `AppBarTheme` was mark as deprecated and has been removed from this new release [3.10].

`textTheme` has been removed, and is replaced by either `toolbarTextStyle` or `titleTextStyle`.

Read more [here](https://docs.flutter.dev/release/breaking-changes/3-7-deprecations#appbar-sliverappbar-and-appbartheme-updates).

**Comment by danagbemava-nc** [comment] 2023-05-12 08:25
Hi @fullflash, the issue is caused by `flutter_neumorphic`. It is using an API that has been removed. See https://github.com/Idean/Flutter-Neumorphic/issues/275

Closing from here as this is not a flutter issue. 

Thank you

**Closed by danagbemava-nc** 2023-05-12 08:25 UTC
Labels: r: invalid

**Comment by fullflash** [comment] 2023-05-12 09:23
> Hi @fullflash, the issue is caused by `flutter_neumorphic`. It is using an API that has been removed. See [Idean/Flutter-Neumorphic#275](https://github.com/Idean/Flutter-Neumorphic/issues/275)
> 
> Closing from here as this is not a flutter issue.
> 
> Thank you

Thanks @danagbemava-nc you are correct it was related to flutter_neumorphic plugin. and there is no textTheme in our app we migrate it already.
