### ISSUE TITLE
Error on trying to run the app

### ISSUE THREAD

**Issue by hbmascarenhas** [flutter/flutter#55242] opened 2020-04-20 22:05 UTC
Hi, I've recently bought the FluxNews and Im trying to follow the guide, but im having issues on the first step, I can't emulate. This is the error im getting:

Error:Internal error: (java.lang.ClassNotFoundException) javax.xml.bind.annotation.XmlSchema
java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:157)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:76)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:82)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidTarget(AndroidJpsUtil.java:404)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidPlatform(AndroidJpsUtil.java:480)
	at org.jetbrains.jps.android.builder.AndroidPreDexBuildTarget.computeRootDescriptors(AndroidPreDexBuildTarget.java:118)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.addRoots(BuildRootIndexImpl.java:69)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.<init>(BuildRootIndexImpl.java:59)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:82)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:274)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by TahaTesser** [comment] 2020-04-21 09:07
Hi @hbmascarenhas 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by hbmascarenhas** [comment] 2020-04-21 16:22
Hi @TahaTesser i`ve manage to solve the problem above, but im having a new issue, it happen after customized logo, links and firebase.:

> Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           307,1s
	path: satisfied (Path is satisfied), interface: en0
Configuring the default Firebase app...
	path: satisfied (Path is satisfied), interface: en0
Configured the default Firebase app __FIRAPP_DEFAULT.
	path: satisfied (Path is satisfied), interface: en0
	path: satisfied (Path is satisfied), interface: en0
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
Debug service listening on ws://127.0.0.1:54735/7rjXEfUnvKI=/ws
Syncing files to device iPhone SE (2nd generation)...
WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
	path: satisfied (Path is satisfied), interface: en0
	[C1.1 93AFF16B-3811-4765-AB3F-D469C0B7260F 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54733<->2a03:2880:f033:11:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 1.300s, DNS @0.071s took 0.043s, TCP @0.126s took 0.015s, TLS took 0.049s
	bytes in/out: 4697/1360, packets in/out: 8/10, rtt: 0.016s, retransmitted packets: 1, out-of-order packets: 0
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
	[C2.1 034FF98F-A15C-4EC2-A126-AA609C344E8D 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54734<->2a03:2880:f033:11:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 1.236s, DNS @0.000s took 0.041s, TCP @0.054s took 0.017s, TLS took 0.053s
	bytes in/out: 4415/1291, packets in/out: 8/9, rtt: 0.011s, retransmitted packets: 0, out-of-order packets: 0
WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
	[C4.1 32F91B81-16C3-4249-A16E-FEA8D2757F41 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54740<->2a03:2880:f033:11:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.536s, DNS @0.000s took 0.037s, TCP @0.040s took 0.021s, TLS took 0.044s
	bytes in/out: 4459/1232, packets in/out: 8/9, rtt: 0.017s, retransmitted packets: 1, out-of-order packets: 0
	[C5.1 3B96A3A8-8547-45BE-A183-3548CBFE59C9 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54741<->2a03:2880:f033:11:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.510s, DNS @0.001s took 0.012s, TCP @0.015s took 0.020s, TLS took 0.048s
	bytes in/out: 4590/963, packets in/out: 8/9, rtt: 0.016s, retransmitted packets: 1, out-of-order packets: 0
	[C6.1 D5D9C4DA-9023-4660-9D9E-E2F5CFAD8BCE 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54742<->2a03:2880:f033:11:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.551s, DNS @0.001s took 0.003s, TCP @0.005s took 0.039s, TLS took 0.056s
	bytes in/out: 3920/1314, packets in/out: 8/10, rtt: 0.025s, retransmitted packets: 0, out-of-order packets: 0
	[C9.1 E1AF42E1-94EE-419B-A245-A52A634AE3CA 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54745<->2a03:2880:f033:11:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.639s, DNS @0.000s took 0.012s, TCP @0.020s took 0.013s, TLS took 0.037s
	bytes in/out: 3893/1531, packets in/out: 7/9, rtt: 0.010s, retransmitted packets: 0, out-of-order packets: 0
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building Consumer<AppModel>(dirty, dependencies:
flutter: [_InheritedTheme, _LocalizationsScope-[GlobalKey#65ad8], _DefaultInheritedProviderScope<AppModel>]):
flutter: The method '[]' was called on null.
flutter: Receiver: null
flutter: Tried calling: []("Setting")
flutter:
flutter: The relevant error-causing widget was:
flutter:   Consumer<AppModel>
flutter:   file:///Users/henriquemascarenhas/Development/FluxNews/fluxnew.1.3.0/source/lib/app.dart:159:14
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
flutter: #1      MyAppState.build.<anonymous closure> (package:fstore/app.dart:207:50)
flutter: #2      Consumer.buildWithChild (package:provider/src/consumer.dart:175:12)
flutter: #3      SingleChildStatelessWidget.build (package:nested/nested.dart:260:41)
flutter: #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
flutter: #5      SingleChildStatelessElement.build (package:nested/nested.dart:280:18)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
flutter: #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
flutter: #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
flutter: #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
flutter: #13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
flutter: #17     _invoke (dart:ui/hooks.dart:259:10)
flutter: #18     _drawFrame (dart:ui/hooks.dart:217:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
	[C12.1 F612E8F4-DEE0-4201-A2DE-FF1ADB3A7899 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54762<->2800:3f0:4004:805::200e.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.207s, DNS @0.000s took 0.004s, TCP @0.005s took 0.016s, TLS took 0.087s
	bytes in/out: 4007/1128, packets in/out: 9/10, rtt: 0.014s, retransmitted packets: 0, out-of-order packets: 0
	[C13.1 BF3701D1-6DA9-4175-B14B-52AE6AF31A97 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54765<->2800:3f0:4004:805::200e.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 1.042s, DNS @0.000s took 0.003s, TCP @0.004s took 0.016s, TLS took 0.084s
	bytes in/out: 4237/1021, packets in/out: 9/9, rtt: 0.015s, retransmitted packets: 0, out-of-order packets: 0
	[C14.1 6CD7F3EA-9F2B-48F0-A498-631B6E9E3FB4 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54766<->2800:3f0:4004:805::200e.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.276s, DNS @0.001s took 0.002s, TCP @0.005s took 0.015s, TLS took 0.122s
	bytes in/out: 3877/1539, packets in/out: 8/10, rtt: 0.014s, retransmitted packets: 0, out-of-order packets: 0
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
	[C8.1 F20D1222-A3B7-4F8C-9450-0BB2D26F94A6 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54744<->2804:7f2:3000:1:face:b00c:0:a7.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 30.114s, DNS @0.000s took 0.016s, TCP @0.018s took 0.007s, TLS took 0.044s
	bytes in/out: 250864/1073, packets in/out: 185/3, rtt: 0.002s, retransmitted packets: 0, out-of-order packets: 0
Request <OSRequestRegisterUser: 0x6000037e70c0> success result {
    id = "7a031c78-b690-4633-a65b-10e8a221622c";
    success = 1;
}
	[C10.1 4AA7A3B1-A33F-4EA5-9AEE-9E48DC2686CA 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54746<->2800:3f0:4004:807::200a.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 120.531s, DNS @0.000s took 0.009s, TCP @0.010s took 0.015s, TLS took 0.080s
	bytes in/out: 4678/1482, packets in/out: 9/10, rtt: 0.010s, retransmitted packets: 0, out-of-order packets: 0
	[C15.1 BE10D1F2-425B-44E8-B9B0-E06C972A170B 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54787<->2800:3f0:4004:808::200a.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 120.415s, DNS @0.000s took 0.004s, TCP @0.005s took 0.013s, TLS took 0.083s
	bytes in/out: 4267/1517, packets in/out: 9/10, rtt: 0.013s, retransmitted packets: 0, out-of-order packets: 0
	[C3.1 381230B0-AEF0-48D7-911A-20C99A42E015 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54736<->2800:3f0:4004:800::200a.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 240.104s, DNS @0.000s took 0.013s, TCP @0.015s took 0.014s, TLS took 0.079s
	bytes in/out: 5099/1239, packets in/out: 10/10, rtt: 0.011s, retransmitted packets: 0, out-of-order packets: 0
	[C11.1 32AE99AD-B3F5-4B59-BB06-8583EC4B4419 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54752<->2800:3f0:4004:805::200a.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 240.981s, DNS @0.000s took 0.009s, TCP @0.010s took 0.013s, TLS took 0.078s
	bytes in/out: 5056/2172, packets in/out: 14/14, rtt: 0.010s, retransmitted packets: 0, out-of-order packets: 0
	[C7.1 FE27C5A6-AD07-4548-91F4-449A16ABE7CA 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54743<->2606:4700::6812:e134.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 241.541s, DNS @0.000s took 0.006s, TCP @0.008s took 0.039s, TLS took 0.099s
	bytes in/out: 3531/1053, packets in/out: 8/8, rtt: 0.030s, retransmitted packets: 0, out-of-order packets: 0
	[C16.1 53B0E2AE-60D8-4A5A-AC76-0AAB5D04B085 2804:7f2:2782:86f2:89c3:45fd:d0b8:1cd1.54788<->2606:4700::6812:e234.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 240.092s, DNS @0.000s took 0.008s, TCP @0.009s took 0.026s, TLS took 0.073s
	bytes in/out: 3429/1557, packets in/out: 8/9, rtt: 0.023s, retransmitted packets: 0, out-of-order packets: 0

**Comment by TahaTesser** [comment] 2020-04-22 07:25
Hi @hbmascarenhas 
the [fluxstore](https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325) seems to be a commercial product rather than part of flutter framework;
the warning you from your logs invites to contact admin, this might be the right course of action to take.

Related to [#55158](https://github.com/flutter/flutter/issues/55158)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by TahaTesser** 2020-04-22 07:25 UTC
Labels: in triage

**Comment by hbmascarenhas** [comment] 2020-04-22 20:39
Sorry. I thought I was in their repository. Keep the good work
