### ISSUE TITLE
Material 3 ListView jitters when slide up and down

### ISSUE THREAD

**Issue by lemon37564** [flutter/flutter#118578] opened 2023-01-16 16:38 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Slide the ListView up and down
3. The ListView jitters

**Expected results:** 
It should not jitter

**Actual results:** 
Video:

https://user-images.githubusercontent.com/65079334/212726985-a1109280-9ff0-430f-acc7-58a60261483c.mp4

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Test'),
        ),
        body: ListView(
          children: <Widget>[
            ListTile(
              title: const Text('A'),
              onTap: () {},
            ),
            ListTile(
              title: const Text('B'),
              onTap: () {},
            ),
            ListTile(
              title: const Text('C'),
              onTap: () {},
            ),
            ListTile(
              title: const Text('D'),
              onTap: () {},
            ),
            ListTile(
              title: const Text('E'),
              onTap: () {},
            ),
            ListTile(
              title: const Text('F'),
              onTap: () {},
            ),
          ],
        ));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

Output of `flutter analyze`:
```
Analyzing test...                                                       
No issues found! (ran in 1.5s)
```

Output of `flutter doctor -v`:
```
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.04.1 LTS 5.15.0-58-generic, locale zh_TW.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /home/user/Android/Sdk
    • Java binary at: /home/user/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/user/android-studio
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-58-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

*Also tested on physical phone with Android 9 and Android 11.

**Comment by whiskeyPeak** [comment] 2023-01-16 17:36
I remember this being fixed a while back. Can you see if the issue is reproducible on the master channel? Thanks!

**Comment by lemon37564** [comment] 2023-01-16 17:56
It looks like this is still present in the master channel (but the jitter seems to become smaller), here's the test video: 


https://user-images.githubusercontent.com/65079334/212739510-7d6008cf-2972-4ec4-8647-3780e7d346ff.mp4


(I ran `flutter channel master; flutter upgrade; flutter pub get; flutter run`)

Part of output of `flutter doctor -v`:
```
[✓] Flutter (Channel master, 3.7.0-21.0.pre.44, on Ubuntu 22.04.1 LTS 5.15.0-58-generic, locale zh_TW.UTF-8)
    • Flutter version 3.7.0-21.0.pre.44 on channel master at /home/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c2fdb803e (6 hours ago), 2023-01-16 11:51:11 +0000
    • Engine revision f790304409
    • Dart version 3.0.0 (build 3.0.0-122.0.dev)
    • DevTools version 2.20.0
```

I also tested beta(which is 3.7.0-1.4.pre) and have the same result.

**Comment by huycozy** [comment] 2023-01-17 11:10
Thanks for the report! This is a known issue being tracked at #118145. Closing this issue as a duplicate, so please follow up on it for further updates.

**Closed by huycozy** 2023-01-17 11:10 UTC
Labels: in triage
