### ISSUE TITLE
[tool_crash] Oops; flutter has exited unexpectedly: "failed to connect to http://127.0.0.1:52104/sVE7sHl4bLU=/".

### ISSUE THREAD

**Issue by bashirHassan-appness** [flutter/flutter#131598] opened 2023-07-31 08:17 UTC
## Command
```
flutter run --profile
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```

```
```
[32m[✓][39m Flutter (Channel stable, 3.10.5, on macOS 13.3 22E252 darwin-arm64, locale en-OM)
    [32m•[39m Flutter version 3.10.5 on channel stable at /Users/myuser/Documents/Development/mobile/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 796c8ef792 (7 weeks ago), 2023-06-13 15:51:02 -0700
    [32m•[39m Engine revision 45f6e00911
    [32m•[39m Dart version 3.0.5
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/myuser/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E300c
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.79.2)
    [32m•[39m VS Code at /Users/myuser/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.68.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m My iPhone (mobile) • 00008110-001918A201FA801E • ios            • iOS 16.0 20A362
    [32m•[39m macOS (desktop)          • macos                     • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    [32m•[39m Chrome (web)             • chrome                    • web-javascript • Google Chrome 115.0.5790.114

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.18
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
connectivity_plus-4.0.1
firebase_auth-4.7.0
firebase_auth_web-5.6.0
firebase_core-2.15.0
firebase_core_web-2.6.0
firebase_dynamic_links-5.3.4
firebase_messaging-14.6.5
firebase_messaging_web-3.5.4
flutter_local_notifications-15.1.0+1
flutter_native_splash-2.3.1
libphonenumber_plugin-0.3.2
libphonenumber_web-0.3.1
newrelic_mobile-1.0.1
open_filex-4.3.2
package_info_plus-4.0.2
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.4
path_provider_linux-2.1.11
path_provider_windows-2.1.7
posthog_flutter-3.1.0
shared_preferences-2.2.0
shared_preferences_android-2.2.0
shared_preferences_foundation-2.3.2
shared_preferences_linux-2.3.0
shared_preferences_web-2.2.0
shared_preferences_windows-2.3.0
url_launcher-6.1.12
url_launcher_android-6.0.36
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.6
url_launcher_web-2.0.18
url_launcher_windows-3.0.7
webview_flutter-4.2.2
webview_flutter_android-3.9.1
webview_flutter_wkwebview-3.7.0

**Comment by danagbemava-nc** [comment] 2023-07-31 08:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108812

**Closed by danagbemava-nc** 2023-07-31 08:55 UTC
Labels: in triage
