### ISSUE TITLE
Firebase_Admob reward does not return the correct reward amount.

### ISSUE THREAD

**Issue by JosephDunivan** [flutter/flutter#24991] opened 2018-12-05 18:43 UTC
The code will always return `int 10` no matter what is set on the admob settings. 
``` Dart
void initState() {
    super.initState();
    print("Coins: $_coins");
    FirebaseAdMob.instance.initialize(appId: FirebaseAdMob.testAppId);
    RewardedVideoAd.instance.load(
          adUnitId: RewardedVideoAd.testAdUnitId, targetingInfo: targetingInfo);
    RewardedVideoAd.instance.listener =
        (RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
      print("RewardedVideoAd event $event");
      if (event == RewardedVideoAdEvent.rewarded) {
        setState(() {
          _coins += rewardAmount;
        });
        print("Coins: $_coins");
      }
    };
  }
```

**Comment by JosephDunivan** [comment] 2018-12-05 18:49
@dnfield

**Comment by JosephDunivan** [comment] 2018-12-06 08:32
Update: It is unclear how to change a testAppId to an actual id for production.

**Comment by kroikie** [comment] 2019-10-13 18:39
@JosephDunivan

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/559. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:54
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment] 2019-10-22 14:40
Hi @JosephDunivan
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-15 12:26
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-15 12:26 UTC
Labels: p: firebase, p: firebase_admob, p: first party, plugin, waiting for customer response
