### ISSUE TITLE
Hotreload and hotrestart error

### ISSUE THREAD

**Issue by rifky41** [flutter/flutter#30199] opened 2019-03-29 18:12 UTC
this error appear when i try to hotrestart or hotreload, idk why. last time i didn't get this error, but after i do flutter upgrade and run the app, this error appear

```
NoSuchMethodError: The method 'isAfter' was called on null.
Receiver: null
Tried calling: isAfter(Instance of 'DateTime')
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      _ManifestAssetBundle.needsBuild (package:flutter_tools/src/asset.dart:91:41)
#2      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:311:44)
<asynchronous suspension>
#3      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:622:47)
<asynchronous suspension>
#4      HotRunner.restart (package:flutter_tools/src/run_hot.dart:566:24)
<asynchronous suspension>
#5      HotRunner.handleTerminalCommand (package:flutter_tools/src/run_hot.dart:281:24)
<asynchronous suspension>
#6      ResidentRunner.processTerminalInput
(package:flutter_tools/src/resident_runner.dart:890:15)
<asynchronous suspension>
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _SyncBroadcastStreamController._sendData
(dart:async/broadcast_stream_controller.dart:375:20)
#13     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#14     _AsBroadcastStreamController.add
(dart:async/broadcast_stream_controller.dart:474:11)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#23     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#24     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#25     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:252:17)
#26     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:238:5)
#27     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#28     _SinkTransformerStreamSubscription._handleData
(dart:async/stream_transformers.dart:120:24)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#35     _StreamController._add (dart:async/stream_controller.dart:640:7)
#36     _StreamController.add (dart:async/stream_controller.dart:586:5)
#37     _Socket._onData (dart:io/runtime/bin/socket_patch.dart:1774:41)
#38     _rootRunUnary (dart:async/zone.dart:1136:13)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#43     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#44     _StreamController._add (dart:async/stream_controller.dart:640:7)
#45     _StreamController.add (dart:async/stream_controller.dart:586:5)
#46     new _RawSocket.<anonymous closure> (dart:io/runtime/bin/socket_patch.dart:1323:33)
#47     _NativeSocket.issueReadEvent.issue (dart:io/runtime/bin/socket_patch.dart:844:14)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#50     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#51     _RawReceivePortImpl._handleMessage
(dart:isolate/runtime/lib/isolate_patch.dart:172:5)


Application finished.
```

**Comment by jonahwilliams** [comment] 2019-03-29 19:13
duplicate of https://github.com/flutter/flutter/issues/30172

**Closed by jonahwilliams** 2019-03-29 19:13 UTC
