### ISSUE TITLE
 Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry'

### ISSUE THREAD

**Issue by KalaliEhsan** [flutter/flutter#137890] opened 2023-11-04 09:09 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have a project with the old Flutter SDK. I upgraded Flutter SDK to 3.13.9. I want to build my project with this new version. But this issue occurred.

### Expected results

I expected to build my project.

### Actual results

```console
../../AppData/Local/Pub/Cache/hosted/pub.dev/division-0.9.0/lib/src/build.dart:100:48: Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.
 - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart' ('/F:/flutter/packages/flutter/lib/src/painting/border_radius.dart').
 - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('/F:/flutter/packages/flutter/lib/src/painting/border_radius.dart').
        borderRadius: decoration?.borderRadius as BorderRadius?,
                                               ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'F:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
Exception: Gradle task assembleDebug failed with exit code 1

```

### Code sample

<details><summary>Code sample</summary>

```dart
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
../../AppData/Local/Pub/Cache/hosted/pub.dev/division-0.9.0/lib/src/build.dart:100:48: Error: The argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.
 - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart' ('/F:/flutter/packages/flutter/lib/src/painting/border_radius.dart').
 - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart' ('/F:/flutter/packages/flutter/lib/src/painting/border_radius.dart').
        borderRadius: decoration?.borderRadius as BorderRadius?,
                                               ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'F:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
Exception: Gradle task assembleDebug failed with exit code 1

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.83.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

```

</details>

**Comment by moffatman** [comment] 2023-11-04 11:29
The `division` package is unmaintained and needs to be updated to support the new flutter SDK. Looks like a pretty simple change, just need to add a default borderRadius on the line indicated.

**Comment by darshankawar** [comment] 2023-11-06 08:38
@KalaliEhsan 
As explained above, the error is coming from https://pub.dev/packages/division/versions/0.9.0 and there's similar issue reported in that repo: https://github.com/ReinBentdal/division/issues/75 with workaround that you can try.

Closing from here, as the issue is coming from third party package.

**Closed by darshankawar** 2023-11-06 08:38 UTC
Labels: in triage
