### ISSUE TITLE
InkWell is not shown under the indicator while clicking and NavigationDestination bounces up

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#117565] opened 2022-12-23 00:33 UTC
#91605
![Screenshot_1671755513](https://user-images.githubusercontent.com/102767277/209247725-70dbca85-baf9-4c54-a274-5fa207663b87.png)
![Screenshot_1671754555](https://user-images.githubusercontent.com/102767277/209247595-76632208-8735-44ba-a115-ec4e0b9a9c70.png)
![Screenshot_1671755200](https://user-images.githubusercontent.com/102767277/209247600-4f35bce6-ae40-4f26-b285-ba1bb02ee083.png)

**Comment by MaxYablochkin** [comment] 2022-12-23 00:35
```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.41, on Microsoft Windows [Version 10.0.22621.963], locale ru-UA)
    • Flutter version 3.7.0-13.0.pre.41 on channel master at C:\Flutter-SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8d5d9c46c (6 hours ago), 2022-12-22 10:52:58 -0800
    • Engine revision a90c45db3f
    • Dart version 3.0.0 (build 3.0.0-55.0.dev)
    • DevTools version 2.20.0

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\yablo\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin version 71.0.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.74.2)
    • VS Code at C:\Users\yablo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.963]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by MaxYablochkin** [comment] 2022-12-23 00:37
> #91605 ![Screenshot_1671755513](https://user-images.githubusercontent.com/102767277/209247725-70dbca85-baf9-4c54-a274-5fa207663b87.png) ![Screenshot_1671754555](https://user-images.githubusercontent.com/102767277/209247595-76632208-8735-44ba-a115-ec4e0b9a9c70.png) ![Screenshot_1671755200](https://user-images.githubusercontent.com/102767277/209247600-4f35bce6-ae40-4f26-b285-ba1bb02ee083.png)

The behavior is similar to Google Play, but this is rather not true regarding the specification

**Comment by TahaTesser** [comment] 2022-12-23 08:59
duplicate of https://github.com/flutter/flutter/issues/117420

**Closed** 2022-12-23 08:59 UTC
