### ISSUE TITLE
AppBar has additional space when parameter "primary" is false

### ISSUE THREAD

**Issue by jagrdev** [flutter/flutter#69858] opened 2020-11-05 07:26 UTC
I want customize SafeArea above AppBar in my application but can't because there is additional area below when I set a parameter "primary" to false.

## Steps to Reproduce

1. Run `flutter create empty_app`.
2. Update AppBar in main.dart: 
`appBar: AppBar(
        title: Text(widget.title),
        primary: false,
      ),`

**Actual results:** 
![image](https://user-images.githubusercontent.com/15156666/98209597-ee5dba80-1f8a-11eb-8244-4796e61a0ca9.png)

**Expected results:** 
![image](https://user-images.githubusercontent.com/15156666/98209969-8b205800-1f8b-11eb-848b-c8af4c51a360.png)

<details>
  <summary>flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.94, on Mac OS X 10.15.6 19G2021 darwin-x64, locale ru-RU)
    • Flutter version 1.24.0-8.0.pre.94 at /Users/sizyikh/Documents/sdk/flutter
    • Framework revision 9470a7e864 (72 minutes ago), 2020-11-04 21:49:59 -0800
    • Engine revision bf259226b2
    • Dart version 2.12.0 (build 2.12.0-21.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sizyikh/Documents/sdk/Android
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/sizyikh/Documents/sdk/Android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • EB439C15-2FC6-48B2-9B9A-259D82E7D304 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment] 2020-11-05 08:26
Hi @jagrdev 
This is expected, you can see the documentation of the primary property for more info. Here is what it says:

> Whether this app bar is being displayed at the top of the screen.
> 
> If true, the app bar's toolbar elements and [bottom] widget will be
> padded on top by the height of the system status bar. The layout
> of the [flexibleSpace] is not affected by the [primary] property.

Closing as this is working as intended.

**Closed by pedromassangocode** 2020-11-05 08:26 UTC
