### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by bdlukaa** [flutter/flutter#96746] opened 2022-01-17 17:22 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. Run the app
2. Hot reload

This doesn't happen often, but happened with me 4-5 times

## Logs
SentinelException
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1626:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2109:21)
#2      VmService.reloadSources (package:vm_service/src/vm_service.dart:1980:7)
#3      _reloadDeviceSources (package:flutter_tools/src/run_hot.dart:1176:32)
<asynchronous suspension>
#4      _defaultReloadSourcesHelper (package:flutter_tools/src/run_hot.dart:1115:65)
<asynchronous suspension>
#5      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:897:38)
<asynchronous suspension>
#6      HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:809:16)
<asynchronous suspension>
#7      HotRunner.restart (package:flutter_tools/src/run_hot.dart:711:36)
<asynchronous suspension>
#8      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1606:40)
<asynchronous suspension>
#9      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1659:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [versÃ£o 10.0.22000.434], locale pt-BR)
    • Flutter version 2.5.3 at C:\Users\bruno\Documents\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\bruno\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\bruno\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • SM A325M (mobile) • RQ8RC0519KV • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [versÃ£o 10.0.22000.434]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 97.0.1072.62

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
audio_session-0.1.6+1
better_player-0.0.81
camera-0.9.4+5
camera_web-0.2.1+1
ffmpeg_kit_flutter_min_gpl-4.5.0-LTS
firebase_auth-1.4.1
firebase_auth_web-1.3.1
firebase_core-1.11.0
firebase_core_web-1.5.3
flutter_fgbg-0.1.0
flutter_keyboard_visibility-5.1.0
flutter_keyboard_visibility_web-2.0.0
flutter_native_text_input-1.3.1
flutter_plugin_android_lifecycle-2.0.5
image_crop-0.4.0
image_cropper-1.4.1
image_editor-1.0.2
image_picker-0.7.5+4
image_picker_for_web-2.1.5
just_audio-0.9.18
just_audio_web-0.4.2
location-4.3.0
location_web-3.1.1
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
permission_handler-8.3.0
photo_manager-2.0.0-dev.2
record-3.0.2
record_web-0.2.1
share_plus-2.2.0
share_plus_macos-2.0.2
share_plus_web-2.0.4
shared_preferences-2.0.12
shared_preferences_android-2.0.10
shared_preferences_ios-2.0.9
shared_preferences_linux-2.0.4
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.3
shared_preferences_windows-2.0.4
sqflite-2.0.1
url_launcher-6.0.18
url_launcher_android-6.0.14
url_launcher_ios-6.0.14
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.6
url_launcher_windows-2.0.2
video_player-2.2.11
video_player_web-2.0.6
video_thumbnail-0.4.3
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.8.0
webview_flutter_android-2.8.2
webview_flutter_wkwebview-2.7.1

**Comment by danagbemava-nc** [comment] 2022-01-18 09:50
Closing as duplicate of #78214

**Closed by danagbemava-nc** 2022-01-18 09:50 UTC
Labels: in triage
