### ISSUE TITLE
Flutter web with  FLUTTER_WEB_USE_SKIA=true  Chinese garbled

### ISSUE THREAD

**Issue by ZhangLiuCheng** [flutter/flutter#71308] opened 2020-11-27 09:25 UTC
flutter build web --release  everything is all right.

flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true --release.     The Chinese language appears disorderly code.

**Comment by iapicca** [comment] 2020-11-27 09:58
@ZhangLiuCheng 
testing the code below with the latest master

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Text('你好，世界'),
        ),
      ),
    );

```

```console
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-8.0.pre.374 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 183f0e797a (15 hours ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.66

• No issues found!

```

![image](https://user-images.githubusercontent.com/45637986/100436282-d1a73500-30a7-11eb-8420-45a78d1015f7.png)

the fonts are unreadable

**Comment by darshankawar** [comment] 2020-11-27 10:15
<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-8.0.pre.374 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 183f0e797a (16 hours ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      87.0.4280.67

• No issues found!


```

</details>

<img width="401" alt="Screenshot 2020-11-27 at 3 41 14 PM" src="https://user-images.githubusercontent.com/67046386/100437951-8dc42800-30c7-11eb-92c5-84293d201b71.png">
<img width="395" alt="Screenshot 2020-11-27 at 3 42 28 PM" src="https://user-images.githubusercontent.com/67046386/100437960-8f8deb80-30c7-11eb-98e5-34da2d1d8a51.png">

**Comment by darshankawar** [comment] 2020-11-27 10:17
May be related to https://github.com/flutter/flutter/issues/68704

**Comment by ZhangLiuCheng** [comment] 2020-11-27 13:38
> zhangliucheng@zhangliuchengdeMacBook-Pro Desktop % flutter doctor -v  
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading package sky_engine...                                  732ms
Downloading flutter_patched_sdk tools...                         2,557ms
Downloading flutter_patched_sdk_product tools...                 2,573ms
Downloading darwin-x64 tools...                                   119.1s
Downloading darwin-x64/font-subset tools...                        975ms
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans)
    • Flutter version 1.24.0-8.0.pre.374 at /Users/zhangliucheng/Documents/software/flutter
    • Framework revision 183f0e797a (19 hours ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/zhangliucheng/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • zhangliucheng-iphone (mobile) • 00008030-001065691169802E • ios            • iOS 14.1
    • Web Server (web)              • web-server                • web-javascript • Flutter Tools
    • Chrome (web)                  • chrome                    • web-javascript • Google Chrome 87.0.4280.67

! Doctor found issues in 1 category.
zhangliucheng@zhangliuchengdeMacBook-Pro Desktop %

**Comment by hterkelsen** [comment] 2020-12-03 17:56
Closing this as a duplicate of https://github.com/flutter/flutter/issues/53897

I am working on a fix now

**Closed by hterkelsen** 2020-12-03 17:56 UTC
Labels: a: release, e: web_canvaskit, found in release: 1.24, has reproducible steps, platform-web, severe: rendering

**Comment by sunjianan9900** [comment] 2020-12-13 05:12
> Closing this as a duplicate of #53897
> 
> I am working on a fix now

Another issuse , if i put chinese.ttf in assets , it works and show the chinese
BUT "TextSpan" still show xxx
please notice this issuse on your fixing, thanks

**Comment by chintandave3019** [comment] 2021-07-28 08:33
> Closing this as a duplicate of #53897
> 
> I am working on a fix now

hey, I face the same issues. can you help me, please.

**Comment by fzyzcjy** [comment] 2021-08-07 23:55
Any updates? I still face this in 2.2!

![image](https://user-images.githubusercontent.com/5236035/128616535-339ee1ff-18a1-4b2f-ba9a-0701237ff66b.png)
