### ISSUE TITLE
[web] Browser Context menu is not usable by TextField if readOnly is true

### ISSUE THREAD

**Issue by treeder** [flutter/flutter#53572] opened 2020-03-30 13:02 UTC
## Steps to Reproduce

* Latest Android, Pixel 4 XL.
* Tried Flutter beta 1.15.17 and Flutter dev 1.16.3

The following shows no menu:

```dart
        TextField(
                controller:
                    TextEditingController(text: "hello"),
                autofocus: true,
                readOnly: true,
                decoration: null,
                maxLines: null)));
```

The menu does come up:

```dart
        TextField(
                controller:
                    TextEditingController(text: "hello"),
                autofocus: true,
                readOnly: false,
                decoration: null,
                maxLines: null)));
```

But even then, I have to try selecting the text (holding it down), then clicking copy a few times before it actually copies the text. 

**Expected results:** 

Copy/Paste/select menu to pop up when `readOnly: true`. And the copy to actual work the first time.  

**Actual results:** 

See steps to reproduce.

**Comment by VladyslavBondarenko** [comment] 2020-07-30 14:22
Persists with current master `1.21.0-6.0.pre.117`. 
Tried also in iOS Safari - the same.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.117 at /Users/nevercode/dev/flutter
    • Framework revision 7ec2d360bc (2 hours ago), 2020-07-29 23:25:38 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by nturgut** [comment] 2020-07-30 16:59
Does this happen on Flutter for Web? We do not bring any copy/paste menu on Flutter for Web, we are relying on the context menu of the browser. Or one can use CTRL+C, CTRL+V, CTRL+X

Please let me know if you saw a toolbar menu on the web for copy/paste (that would be a regression). I'm removing the web label for now.

Thanks for filing the issue.

**Comment by nturgut** [comment] 2020-07-30 17:05
Sharing the code her for further reference, in Flutter for Web the toolbar (which has copy/paste) should not be visible: https://github.com/flutter/flutter/blob/88a7d83a32804cede64c2d622aeed6f8a8ed1576/packages/flutter/lib/src/widgets/editable_text.dart#L2210

If this is related to the context menu of the browser let's rename the issue, thanks!

**Comment by treeder** [comment] 2020-07-30 17:17
This is flutter for web using chrome on android device. This is not related to `platform-android`.

**Comment by nturgut** [comment] 2020-07-30 17:37
@treeder can you share a screenshot of copy/paste toolbar coming on Flutter for Web (text disabled or not). As I shared on the code, that codepath is not executed by Flutter for Web.

I believe there might be a misunderstanding between context menu of browser and Copy/Paste toolbar, if so we can merge this to another issue which is already on our near term goals.

**Comment by treeder** [comment] 2020-07-30 18:16
Perhaps @VladyslavBondarenko can take a screenshot quickly since it sounds like he just tested it? Otherwise it may take a few days for me to get around to it.

**Comment by VladyslavBondarenko** [comment] 2020-07-31 07:14
Hi @nturgut 

This is what I'm experiencing - In web I can select readOnly text, but the context menu isn't shown. 
But the menu is shown for readOnly text when I run it as Android app

https://fltx.netlify.app/

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextField(
              controller: TextEditingController(text: "hello"),
              autofocus: true,
              readOnly: true,
              decoration: null,
              maxLines: null,
            ),
            TextField(
              controller: TextEditingController(text: "hello"),
              autofocus: true,
              readOnly: false,
              decoration: null,
              maxLines: null,
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

Chrome
<img src="https://user-images.githubusercontent.com/17024977/89008860-19919780-d314-11ea-8bb5-8ee139585487.jpg" width="250" /> <img src="https://user-images.githubusercontent.com/17024977/89009127-99b7fd00-d314-11ea-9465-80252e9b5829.jpg" width="250" /> <img src="https://user-images.githubusercontent.com/17024977/89009326-fd422a80-d314-11ea-96df-e261c0157835.jpg" width="250" />

Android app
<img src="https://user-images.githubusercontent.com/17024977/89009510-5ad67700-d315-11ea-9e52-65f25b0eea2d.jpg" width="250" /> <img src="https://user-images.githubusercontent.com/17024977/89009520-5d38d100-d315-11ea-9f9b-ac9e0acc2c05.jpg" width="250" />

**Comment by nturgut** [comment] 2020-07-31 16:19
thanks for the screenshots. @VladyslavBondarenko yes this is the browser context menu (you can also see options like translate depending on the browser).

In summary: With the current way we are implementing text input platform channel the information on this text field won't be send to web engine on read only mode. Therefore this involves a bigger change. I added 'severe: new feature' label. I also left framework label since we first need to address in on framework.

**Comment by huycozy** [comment] 2022-11-08 10:41
Hi @treeder. This issue seems to be fixed on the latest `stable` and `master` channels. Please see the demo. 

<details>
<summary>Demo</summary>

| readOnly true | readOnly false |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/200541619-5e2e7c6f-a410-463d-9549-02f54c300ace.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/200541635-0dde4764-eae2-4ecf-84e6-022524178a6e.png">

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.3.7 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (27 hours ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.5.0-12.0.pre.168, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-12.0.pre.168 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a1432a9c5d (39 minutes ago), 2022-11-07 19:17:03 -0600
    • Engine revision e7d7edab98
    • Dart version 2.19.0 (build 2.19.0-374.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

Please try running app again on the latest stable or master channel and confirm if this issue is fixed.

**Closed** 2022-11-29 11:09 UTC
Labels: a: text input, new feature, waiting for customer response, framework, engine, platform-web, has reproducible steps, P4, found in release: 1.21
