### ISSUE TITLE
BottomNavigationBar feedback region too wide

### ISSUE THREAD

**Issue by cdprete** [flutter/flutter#96822] opened 2022-01-18 23:49 UTC
Hi.
When running a Flutter application on Windows, the `BottomNavigationBar`  gives too much space to the buttons in it for the click.
See the picture at https://ibb.co/300TFm8
The mouse was almost at the center and one of the two buttons (Favorites in that case) was clickable.

Further info:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1466], locale it-CH)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[!] Android Studio (not installed)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X FormatException: Unexpected extension byte (at offset 5)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

**Comment by danagbemava-nc** [comment] 2022-01-19 08:08
Hi @cdprete, the `BottomNavigationBar` was designed according to `Material Design Spec` and according to the spec the `BottomNavigationBar` should not be used on devices larger than tablets. It is recommended to use either a `NavigationRail` or a `NavigationDrawer` for larger screens. Seeing as this is not the intended use of the widget, I believe this should be expected. If you're designing your app to be responsive, I would recommend taking a look at https://pub.dev/packages/responsive_builder which should help you with organizing your code and UI for responsive design. There are other packages as well that you can use over on pub.dev

Seeing as the `BottomNavigationBar` isn't intended to be used in desktop scenarios, I'm going to close this issue. 

Thank you

[Material 2 BottomNavigationBar usage](https://material.io/components/bottom-navigation#usage)
[Material 3 BottomNavigationBar](https://m3.material.io/components/navigation-bar/guidelines#bfa65899-098c-43d5-9639-1e7f2461ca06)

**Closed by danagbemava-nc** 2022-01-19 08:08 UTC
Labels: in triage

**Comment by cdprete** [comment] 2022-01-22 15:39
Hi @danagbemava-nc.
Thanks for the valuable information. I was not aware that the BottomNavigationBar is not designed for desktop nor web.
