### ISSUE TITLE
Absolute paths don't seem to work with flutter.yaml assets

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#7021] opened 2016-11-26 19:08 UTC
Add an absolute path to assets in flutter.yaml.
Try to build (any flavor works).
Error.

```
% flutter build flx
Error: unable to locate asset entry in flutter.yaml: "/my/valid/absolute/path.png".
Error building build/app.flx: 1
```

**Comment by zoechi** [comment] 2019-01-18 09:56
Perhaps the same as #26108, #8403

**Comment by jonahwilliams** [comment] 2019-04-22 00:11
Duplicate of https://github.com/flutter/flutter/issues/8403

**Closed by jonahwilliams** 2019-04-22 00:11 UTC
Labels: a: assets, tool
