### ISSUE TITLE
NestedScrollView with TabBarView and SliverPersistentHeader bug - Multiple tab bar view with different heights.

### ISSUE THREAD

**Issue by naamapps** [flutter/flutter#70606] opened 2020-11-16 11:39 UTC
## Problem Description
I have two tab bar views, one with a list of 20 items, and another with 5 items. both are inside a `NestedScrollView`.
When scrolling for the first time in the initial tab bar view (index zero), the scroll and the persistent header are working as expected. 
However, when switching to the second tab bar view with the 5 items, and then switching back to the first view, the persistent header will show up when scrolling as if I scrolled in the second shorter tab bar view.
This happens when combining `NestedScrollView` with `TabBarView` and `SliverPersistentHeader`, while the tab bar views have different heights (list view with more items).
It is important to note that both children of the `TabBarView` are statefull widgets that with `AutomaticKeepAliveClientMixin` and wantKeepAlive always true.

See here the problem: 
[HeaderBug.mp4.zip](https://github.com/flutter/flutter/files/5545517/HeaderBug.mp4.zip)

<details>
  <summary>Flutter doctor -v</summary>
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B29, locale en-IL)
    • Flutter version 1.22.3 at /Users/naamapps/flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/naamapps/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • SM G955F (mobile) • ce031713b9cc111e01 • android-arm64 • Android 9 (API
      28)

! Doctor found issues in 1 category.
</details>

Here is the github repo to reproduce the issue:
https://github.com/naamapps/nestedHeaderBug
Thanks.

**Comment by pedromassangocode** [comment] 2020-11-17 10:54
Hi @naamapps 

Can you please provide a minimal complete reproducible code sample? The code you shared is not minimal and contains too much code that may distract me while trying to reproduce the issue.

I saw the video you attached and was not able to notice any unexpected behavior!

Thank you

**Comment by naamapps** [comment] 2020-11-17 11:29
Hi @pedromassangocode,
I'm sorry, but this is the most minimal code I can provide, as this bug is pretty complicated.
Please watch the video again and this time pay closer attention at 00:13. At this time in the video, you can see that the header shows up before reaching the top of the items list (Visible at 00:15). 
The header should only show up when reaching the top of the items.

As I said in the original post, this happens when there are two tab bar view.
But only when there are difference in the item count.

> When scrolling for the first time in the initial tab bar view (index zero), the scroll and the persistent header are working as expected.
> However, when switching to the second tab bar view with the 5 items, and then switching back to the first view, the persistent header will show up when scrolling as if I scrolled in the second shorter tab bar view.

I think you can see that very clearly in the video.
The times the bug shows up in the video: 
00:13, 00:30, 00:35
Thanks.

**Comment by naamapps** [comment] 2020-11-23 09:35
@pedromassangocode 
Can you help please?

**Comment by pedromassangocode** [comment] 2020-11-23 14:04
Cc @Piinks 

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (10 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

```
</details>

**Comment by Piinks** [comment] 2022-06-16 22:40
This looks like a duplicate of https://github.com/flutter/flutter/issues/81619 I am going to close this to focus conversation and work in one place, please continue to follow https://github.com/flutter/flutter/issues/81619.

If you feel that this is a separate issue, let us know and we can take another look! Thanks!

**Closed by Piinks** 2022-06-16 22:40 UTC
Labels: framework, f: scrolling, has reproducible steps, found in release: 1.22
