### ISSUE TITLE
dart:core  _Uri.resolve error in Flutter SDK 2 web part

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#77565] opened 2021-03-08 06:57 UTC
2 Days ago, I clean install **Flutter SDK 2** and created a new project. I also use:
`flutter create .`
to add web capability into my project. Everything worked as I expected. I read and watch some information about Flutter SDK 2. And finally I decide to convert my previous project to **Flutter SDK 2**. After I converted I had some issues from http, provider etc. Then I change all my plugin to new one (null safety version). I also run **Flutter Fix** and check if anything needs to be corrected in my app. Everything worked perfectly.

I run my app using iOS and android simulator and it worked. My published app version was 1.6.5, and I am work with flutter since 2018.

After seeing that Flutter SDK 2 stable is works perfectly than I try to run my app for web. I choose **Chrome Web** to run my app but **I got following error.** This is my first time to work with Flutter web.

**Error:**
```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:54232/EGkH5yR9qp0=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:54232/EGkH5yR9qp0=/ws
Error: Unsupported operation: Platform._localeName
    at Object.throw_ [as throw] (http://localhost:54145/dart_sdk.js:5334:11)
    at Function._localeName (http://localhost:54145/dart_sdk.js:56171:17)
    at Function.localeName (http://localhost:54145/dart_sdk.js:56177:71)
    at Function.get localeName [as localeName] (http://localhost:54145/dart_sdk.js:56053:27)
    at AppLanguage.AppLanguage.new.fetchLocale (http://localhost:54145/packages/my_app/AppLanguage.dart.lib.js:39:41)
    at fetchLocale.next (<anonymous>)
    at runBody (http://localhost:54145/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:54145/dart_sdk.js:39083:7)
    at AppLanguage.AppLanguage.new.fetchLocale (http://localhost:54145/packages/my_app/AppLanguage.dart.lib.js:38:20)
    at main$ (http://localhost:54145/packages/my_app/summary_login.dart.lib.js:21578:25)
    at main$.next (<anonymous>)
    at http://localhost:54145/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:54145/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54145/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:54145/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:54145/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:54145/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54145/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:54145/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:54145/dart_sdk.js:39182:13)
    at http://localhost:54145/dart_sdk.js:34689:9
ERROR - 2021-03-08 08:38:35.826571
GET /dart_sdk.js:5334:11
Error thrown by handler.
FormatException: Illegal scheme character (at character 5)
dart_sdk.js:5334:11
    ^

dart:core                                                 _Uri.resolve
package:flutter_tools/src/isolated/devfs_web.dart 503:57  WebAssetServer._resolveDartFile
package:flutter_tools/src/isolated/devfs_web.dart 395:17  WebAssetServer.handleRequest
package:dwds/src/handlers/injector.dart 110:32            DwdsInjector.middleware.<fn>.<fn>
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.1 at /Users/**********/flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/**********/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/**********/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

```

**flutter and dart plugin version:**
<img width="396" alt="Screenshot 2021-03-08 at 08 57 45" src="https://user-images.githubusercontent.com/33287468/110285794-7365e880-7fec-11eb-965e-a9814e0c0703.png">

**Comment by guidezpl** [comment] 2021-03-08 08:43
This is a duplicate of https://github.com/flutter/flutter/issues/39998

**Closed by guidezpl** 2021-03-08 08:43 UTC

**Comment by NTMS2017** [comment] 2021-03-09 05:17
Sorry I am new to Web part, and didn't understand correctly the  #39998. So I need better examples for this if you can point me the direction much appricated.

**Comment by guidezpl** [comment] 2021-03-09 07:20
Web doesn't yet have full support for 'dart:io' which `http://localhost:54145/packages/my_app/AppLanguage.dart.lib.js:39:41` depends on. For the time being, there are multiple workarounds listed on the issue linked above
