### ISSUE TITLE
App support of x64-bit Android devices

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#32131] opened 2019-05-06 07:39 UTC
Hi there, In order to support my android app for x64-bit android devices, I have added 
```
defalutConfig{
.....
ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'`
...
}
```
in my `app/build.gradle` file.
But, when I uploaded App Bundle to playstore  only` armeabi-v7a `native paltform is showing up and also an **Warning** stating about 64-bit.
![Screenshot (32)](https://user-images.githubusercontent.com/22256553/57212034-06542700-7000-11e9-99a8-6738a545b670.png)
**Am I missing something! How to support all native platforms??**

**Comment by huuchi207** [comment] 2019-06-25 13:37
have the same issue. Hope any one help.

**Comment by giovannibozzo** [comment] 2019-07-08 12:44
Hi,

I have added this changes:

In gradle.properties:
```
ABI_FILTERS=armeabi;armeabi-v7a;mips;arm64-v8a;x86;x86_64
```

Then in build.gradle:
```
buildTypes {
        release {
            ...
            ndk {
                abiFilters = []
                abiFilters.addAll(ABI_FILTERS.split(';').collect{it as String})
            }          
        }
}
```

**Comment by BondarenkoStas** [comment] 2019-10-08 16:53
thank you @giovannibozzo ! @harshapulikollu did it help?

**Comment by jonahwilliams** [comment] 2019-10-08 17:29
Duplicate of https://github.com/flutter/flutter/issues/9253

**Closed by jonahwilliams** 2019-10-08 17:29 UTC
Labels: waiting for customer response
