### ISSUE TITLE
Leading AppBar back button is not aligned with the icon itself in flutter when changing the app to  Right-to-Left (RTL)

### ISSUE THREAD

**Issue by EgHubs** [flutter/flutter#153408] opened 2024-08-14 03:39 UTC
### Steps to reproduce

1.Made a appbar in my app
   ```
 return Scaffold(
      appBar: AppBar(
          automaticallyImplyLeading: true,
          centerTitle: true,
          title: Text(
            Languages.of(context)!.text321,
            style: TextStyle(
              color: Colors.white,
              fontSize: 20.0,
            ),
          )),
      body: 
```
2. run the app in the latest simulator version
3. changing the app from LTR to RTL 

### Expected results

The leading default back icon should be aligned and centered withe the button itself that appears as a circle when i long press on it!
It works with LTR apps when the leading icon is on the left but when i change the app to the RTL the leading icon goes very far to the right of the screen while the leading button itself is in the location it should be (lets say padding 50 from the right).
for far demonstrating here is the screen shots, these are with the same code mentioned!

<img width="342" alt="image" src="https://github.com/user-attachments/assets/1a6cbce1-e9e3-4884-a88d-3875ae98b680">
<img width="347" alt="Screenshot 2024-08-13 at 8 46 20 PM" src="https://github.com/user-attachments/assets/824dd56b-d776-48e0-8799-621464b24c40">

### Actual results

the leading icon goes very far to the right of the screen while the leading button itself is in the location it should be (lets say padding 50 from the right).

### Code sample

<details open><summary>Code sample</summary>

```dart
 return Scaffold(
      appBar: AppBar(
          automaticallyImplyLeading: true,
          centerTitle: true,
          title: Text(
            Languages.of(context)!.text321,
            style: TextStyle(
              color: Colors.white,
              fontSize: 20.0,
            ),
          )),
      body: Container()
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-14 07:21
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153036

**Closed by danagbemava-nc** 2024-08-14 07:21 UTC
Labels: in triage
