### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by Akhil2836** [flutter/flutter#152153] opened 2024-07-23 09:12 UTC
## Command
```
flutter run -d web-server --web-port=3000 --target=lib/features/keycloak/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#5      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:854:57)
#6      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:549:56)
<asynchronous suspension>
#7      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:319:41)
<asynchronous suspension>
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.22621.3880], locale en-IN)
    [32m•[39m Flutter version 3.19.0 on channel stable at C:\Flutter 3.19\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision bae5e49bc2 (), 2024-02-13 17:46:18 -0800
    [32m•[39m Engine revision 04817c99c9
    [32m•[39m Dart version 3.3.0
    [32m•[39m DevTools version 2.31.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    [32m•[39m Android SDK at C:\Users\proje\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 33.0.1
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[32m[✓][39m VS Code (version 1.91.1)
    [32m•[39m VS Code at C:\Users\proje\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.92.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.22621.3880]
    [32m•[39m Web Server (web)  • web-server • web-javascript • Flutter Tools
    [32m•[39m Chrome (web)      • chrome     • web-javascript • Google Chrome 126.0.6478.182
    [32m•[39m Edge (web)        • edge       • web-javascript • Microsoft Edge 126.0.2592.113

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 3778e3c76c60ad0a4462a0f7a2d097c52e63d16f
### Plugins
catcher-0.8.0**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 3778e3c76c60ad0a4462a0f7a2d097c52e63d16f
### Plugins
catcher-0.8.0
device_info_plus-9.1.2
file_picker-5.5.0
flutter_dropzone-3.0.7
flutter_dropzone_web-3.0.13
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_mailer-2.1.2
flutter_plugin_android_lifecycle-2.0.19
flutter_timezone-1.0.8
fluttertoast-8.2.5
package_info_plus-4.2.0
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
printing-5.12.0
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
url_launcher-6.2.6
url_launcher_android-6.3.2
url_launcher_ios-6.3.0
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1

**Comment by danagbemava-nc** [comment] 2024-07-23 09:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/68958

**Closed by danagbemava-nc** 2024-07-23 09:58 UTC
Labels: in triage
