### ISSUE TITLE
replace expat with a hand-rolled parser

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#888] opened 2015-12-11 23:35 UTC
We use expat to parse the Android fonts XML file. We could hand-roll a parser that is just enough to read the shipped fonts.xml files that would be both faster and smaller than expat.

**Comment by dnfield** [comment] 2019-12-01 01:17
This is a duplicate of #43517 - which came much later but now has more context.  Closing in favor of that one.

**Closed by dnfield** 2019-12-01 01:17 UTC
Labels: a: size, dependency: skia, engine, severe: performance, team
