### ISSUE TITLE
Unable to accept android licenses

### ISSUE THREAD

**Issue by OlleLindgren** [flutter/flutter#53648] opened 2020-03-31 11:15 UTC
## Problem

I am unable to run Flutter because I can't accept some licenses.

## Steps to Reproduce

1. Find a computer that runs Windows 10 x64 build 18363.720
2. Install Flutter and Android Studio
3. Set JAVA_HOME to the jre that ships with Android Studio
4. Install Android SDK Tools 26.1.1 using Android Studio
5. Set ANDROID_SDK_ROOT to ...\AppData\Local\Android\Sdk
6. Open a non-elevated Powershell window
7. Run the commands below in order

### flutter --verbose doctor

~~~~

The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Windows, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\lindg\sw\flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at C:\Users\lindg\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 30.0.0-rc2
    • ANDROID_SDK_ROOT = C:\Users\lindg\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

~~~~
### flutter --verbose doctor --android-licenses
~~~~
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
[  +15 ms] executing: [C:\Users\lindg\sw\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +5 ms] executing: [C:\Users\lindg\sw\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +44 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +14 ms] executing: [C:\Users\lindg\sw\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[        ] executing: [C:\Users\lindg\sw\flutter\] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +86 ms] executing: [C:\Users\lindg\sw\flutter\] git rev-parse --abbrev-ref HEAD
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +89 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +7 ms] executing: C:\Users\lindg\AppData\Local\Android\Sdk\tools\bin\sdkmanager --version
[ +946 ms] Exit code 1 from: C:\Users\lindg\AppData\Local\Android\Sdk\tools\bin\sdkmanager --version
[   +7 ms] 26.1.1
[        ] The system cannot find the path specified.
[        ] sdkmanager --version failed: exitCode: 1 stdout: 26.1.1

            stderr: The system cannot find the path specified.

[  +22 ms] "flutter doctor" took 1,245ms.
A newer version of the Android SDK is required. To update, run:
C:\Users\lindg\AppData\Local\Android\Sdk\tools\bin\sdkmanager --update



#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:317:7)
#2      Doctor.diagnose (package:flutter_tools/src/doctor.dart:243:38)
#3      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
~~~~
### C:\Users\lindg\AppData\Local\Android\Sdk\tools\bin\sdkmanager --verbose --update
~~~~
The system cannot find the path specified.
Info: Parsing C:\Users\lindg\AppData\Local\Android\Sdk\build-tools\28.0.3\package.xml
Info: Parsing C:\Users\lindg\AppData\Local\Android\Sdk\build-tools\30.0.0-rc2\package.xml
Info: Parsing C:\Users\lindg\AppData\Local\Android\Sdk\emulator\package.xml
Info: Parsing C:\Users\lindg\AppData\Local\Android\Sdk\patcher\v4\package.xml
Info: Parsing C:\Users\lindg\AppData\Local\Android\Sdk\platform-tools\package.xml
Info: Parsing C:\Users\lindg\AppData\Local\Android\Sdk\platforms\android-29\package.xml
Info: Parsing C:\Users\lindg\AppData\Local\Android\Sdk\sources\android-29\package.xml
Info: Parsing C:\Users\lindg\AppData\Local\Android\Sdk\tools\package.xml
[=======================================] 100% Computing updates...
~~~~

### flutter --verbose doctor --android-licenses
~~~~

The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
[  +13 ms] executing: [C:\Users\lindg\sw\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +4 ms] executing: [C:\Users\lindg\sw\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +40 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +6 ms] v1.12.13+hotfix.8-0-g0b8abb472
[   +9 ms] executing: [C:\Users\lindg\sw\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +4 ms] executing: [C:\Users\lindg\sw\flutter\] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +79 ms] executing: [C:\Users\lindg\sw\flutter\] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +52 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +86 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +8 ms] executing: C:\Users\lindg\AppData\Local\Android\Sdk\tools\bin\sdkmanager --version
[ +845 ms] Exit code 1 from: C:\Users\lindg\AppData\Local\Android\Sdk\tools\bin\sdkmanager --version
[   +7 ms] 26.1.1
[        ] The system cannot find the path specified.
[        ] sdkmanager --version failed: exitCode: 1 stdout: 26.1.1

            stderr: The system cannot find the path specified.

[  +18 ms] "flutter doctor" took 1,137ms.
A newer version of the Android SDK is required. To update, run:
C:\Users\lindg\AppData\Local\Android\Sdk\tools\bin\sdkmanager --update



#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:317:7)
#2      Doctor.diagnose (package:flutter_tools/src/doctor.dart:243:38)
#3      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

~~~~

## flutter doctor -v

~~~~

The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Windows, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\lindg\sw\flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at C:\Users\lindg\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 30.0.0-rc2
    • ANDROID_SDK_ROOT = C:\Users\lindg\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
~~~~

## C:\Users\lindg\AppData\Local\Android\Sdk\tools\bin\sdkmanager --version
~~~~

The system cannot find the path specified.
26.1.1
~~~~

**Comment by andredealmei** [comment] 2020-03-31 11:46
you can try :

1. open Android Studio.
2. Click on configure.
3. Sdk manager.
4. Tab "**SDK Tools**".
5. Uncheck "**Hide obsolete Packages**".
6. Check "**Android Sdk Platform tools 26.1.1**".
7. apply and try the flutter doctor again.

**Comment by OlleLindgren** [comment] 2020-03-31 12:03
> you can try :
> 
> 1. open Android Studio.
> 2. Click on configure.
> 3. Sdk manager.
> 4. Tab "**SDK Tools**".
> 5. Uncheck "**Hide obsolete Packages**".
> 6. Check "**Android Sdk Platform tools 26.1.1**".
> 7. apply and try the flutter doctor again.

Already have Android SDK Platform tools 29.0.6, but I'm guessing you mean the Android SDK tools (not platform)? I have Android SDK Tools 26.1.1 installed, it doesn't help. Flutter doctor seems to conclude that 26.1.1 is outdated and should be updated

**Comment by TahaTesser** [comment] 2020-03-31 12:05
hi @OlleLindgren 

For `The system cannot find the path specified.`
Please check this [answer](https://stackoverflow.com/a/59271508)

Reinstall. SDK tools and Please execute `flutter doctor  --android-licenses`  and not `flutter --verbose doctor --android-licenses`

Thank you

**Comment by OlleLindgren** [comment] 2020-03-31 12:17
> hi @OlleLindgren
> 
> For `The system cannot find the path specified.`
> Please check this [answer](https://stackoverflow.com/a/59271508)

The problem this person had was an & sign in the windows username. my username is lindg, how is the solution applicable?

> 
> Reinstall. SDK tools and Please execute `flutter doctor --android-licenses` and not `flutter --verbose doctor --android-licenses`
> 
> Thank you

The result of running `flutter doctor --android-licenses` after uninstalling sdk tools, rebooting and reinstalling:
~~~~
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
A newer version of the Android SDK is required. To update, run:
C:\Users\lindg\AppData\Local\Android\Sdk\tools\bin\sdkmanager --update
~~~~

**Comment by TahaTesser** [comment] 2020-03-31 12:35
Hi @OlleLindgren 
I linked the solution since it could be admin access issue, reproducing same error in both cases.

**Comment by OlleLindgren** [comment] 2020-03-31 13:42
> Hi @OlleLindgren
> I linked the solution since it could be admin access issue, reproducing same error in both cases.

I'm not sure how to fix that. My user account already has admin privileges but I have uninstalled Android Studio, the Android SDK and Flutter and reinstalled them into `C:\Users\lindg\sw`, a folder that does not require admin privileges. I have the same problems as before. I ran the following commands in succession:

`flutter doctor --android-licenses`
~~~~

The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
A newer version of the Android SDK is required. To update, run:
C:\Users\lindg\sw\Android\Sdk\tools\bin\sdkmanager --update
~~~~

`C:\Users\lindg\sw\Android\Sdk\tools\bin\sdkmanager --update`

~~~~

The system cannot find the path specified.
[=======================================] 100% Computing updates...
PS C:\Users\lindg>

~~~~

`C:\Users\lindg\sw\Android\Sdk\tools\bin\sdkmanager --version`
~~~~

The system cannot find the path specified.
26.1.1
~~~~


`flutter doctor --android-licenses`
~~~~

The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
A newer version of the Android SDK is required. To update, run:
C:\Users\lindg\sw\Android\Sdk\tools\bin\sdkmanager --update
~~~~

**Comment by jonahwilliams** [comment] 2020-03-31 16:09
Duplicate of https://github.com/flutter/flutter/issues/51712

**Closed by jonahwilliams** 2020-03-31 16:09 UTC
Labels: platform-android, tool
