### ISSUE TITLE
[image_picker] Crash on iOS by double-clicking on the image

### ISSUE THREAD

**Issue by iKrupp** [flutter/flutter#55300] opened 2020-04-21 14:28 UTC
Hi! I use the **image_picker** package to get pictures from the system gallery.
I ran into a problem on **iOS** when I get a crash when I double-click on a picture.
I know that there was a fix for this problem in version **0.4.12**, but now it is reproduce on version **0.6.5+1**

<details>
  <summary>Logs</summary>

```
2020-04-21 18:10:06.706981+0400 Runner[3369:1008611] CGImageSourceCreateWithData:3273: *** ERROR: CGImageSourceCreateWithData: data is nil
2020-04-21 18:10:06.707022+0400 Runner[3369:1008611] CGImageSourceGetType:3548: *** ERROR: CGImageSourceGetType: source is nil
2020-04-21 18:10:06.707038+0400 Runner[3369:1008611] CGImageDestinationCreateWithData:3086: *** ERROR: CGImageDestinationCreateWithData: type is nil
2020-04-21 18:10:06.707051+0400 Runner[3369:1008611] CGImageDestinationAddImageFromSource:3283: *** ERROR: CGImageDestinationAddImageFromSource: destination is nil
2020-04-21 18:10:06.707067+0400 Runner[3369:1008611] CGImageDestinationFinalize:3394: *** ERROR: CGImageDestinationFinalize: destination is nil
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/parfenov/tools/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/parfenov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)

```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-04-21 15:07
Hi @iKrupp 
Is https://github.com/flutter/flutter/issues/55063 your case?
I can reproduce only with specified maxWidth or maxHeight

**Comment by iKrupp** [comment] 2020-04-21 15:09
@VladyslavBondarenko yes, I pass these parameters too

**Comment by cyanglaz** [comment] 2020-04-21 17:55
Is seems to be the same issue with #55063
Which is fixed by 0.6.5+2

**Comment by iKrupp** [comment] 2020-04-21 19:54
@cyanglaz It seems that in version 0.6.5 + 2 the problem is fixed. Thank you

**Comment by cyanglaz** [comment] 2020-04-21 20:33
@iKrupp thank you for verifying. I'm going to close this PR then! Feel free to open new PRs!

**Closed by cyanglaz** 2020-04-21 20:33 UTC
Labels: in triage
