### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by sherman-github** [flutter/flutter#146113] opened 2024-04-02 05:35 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=334075bc --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#6      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:210:53)
#7      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:158:49)
#8      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart)
#9      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:152:30)
#10     _extractPlatformMaps (package:flutter_tools/src/flutter_plugins.dart:361:40)
#11     _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:375:53)
#12     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1164:11)
<asynchronous suspension>
#13     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:378:5)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1648:7)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
```
```
[✓] Flutter (Channel stable, 3.16.5, on Microsoft Windows [版本 10.0.22631.3296], locale zh-CN)
    • Flutter version 3.16.5 on channel stable at D:\flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 months ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\androidSDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\androidSDK
    • Java binary at: D:\androidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version unknown)
    • Android Studio at D:\androidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • android-studio-dir = D:\androidStudio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\idea\IntelliJ IDEA 2019.3.5
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at D:\idea2023\IntelliJ IDEA 2023.3.4
    • Flutter plugin version 78.1.1
    • Dart plugin version 233.13763.5

[✓] Connected device (4 available)
    • V1981A (mobile)   • 334075bc • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [版本 10.0.22631.3296]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 123.0.6312.86
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 123.0.2420.65

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78666c8dc57e9f7548ca9f8dd0740fbf0c658dc9
### Plugins
fijkplayer-0.11.0
permission_handler-11.3.1
permission_handler_android-12.0.5
permission_handler_apple-9.4.4
permission_handler_html-0.1.1
permission_handler_windows-0.2.1

**Comment by danagbemava-nc** [comment] 2024-04-02 07:26
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

Please do not file multiple issues to report the same bug in the future. 

Thank you

**Closed by danagbemava-nc** 2024-04-02 07:26 UTC
Labels: in triage
