### ISSUE TITLE
CupertinoDatePicker doesn't work with some sizes

### ISSUE THREAD

**Issue by RobertBrunhage** [flutter/flutter#126157] opened 2023-05-05 13:52 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use the Code sample below and `flutter run` it with `--enable-impeller` on an iOS device.

### Expected results

Hot reload and restart works as expected, irrespective of the value of `SizedBox.height`.

### Actual results

When the `SizedBox.height` is less than around 170, everything works as expected. But values more than that cause a lot of jank. If the first built starts with a value >~200, app starts with a blank screen and takes a long time.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          body: SizedBox(
            height: 550,
            child: CupertinoDatePicker(
              mode: CupertinoDatePickerMode.date,
              backgroundColor: Colors.white,
              onDateTimeChanged: print,
              initialDateTime: DateTime.now(),
              minimumYear: 1925,
              maximumYear: 2025,
            ),
          ),
        ),
      ),
    );

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://user-images.githubusercontent.com/44755140/236612583-e2bbb2dd-ca3c-4290-b502-53b084ea5dd6.mov

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-arm64, locale en-SE)
    • Flutter version 3.7.12 on channel stable at /Users/robertbrunhage/tools/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/robertbrunhage/Library/Android/Sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/robertbrunhage/Library/Android/Sdk
    • ANDROID_SDK_ROOT = /Users/robertbrunhage/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • Robert’s iPhone (mobile) • 00008120-001149E03433401E • ios            • iOS 16.4.1 20E252
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 112.0.5615.137
    ! Error: Robert’s iPhone is busy: Fetching debug symbols for Robert’s iPhone. Xcode will continue when Robert’s iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by werainkhatri** [comment] 2023-05-06 06:55
> It doesn't work in some heights such as 200 where 100 or 400 works.

could you elaborate on what doesn't work? a screenshot / video would be quite helpful.

if its the scrolling or `onDateTimeChanged`, stable and master seem to work just fine.

https://user-images.githubusercontent.com/44755140/236608316-e60a3ea2-cefe-4810-881d-ea6c00aac690.mov

**Comment by RobertBrunhage** [comment] 2023-05-06 06:58
@werainkhatri oh I wonder if it's because I use impeller, for me it either just doesn't render at all (everything is stuck), or if I hotreload it's not able to scroll.

Not home now will see if I can get a video on Monday!

**Comment by werainkhatri** [comment] 2023-05-06 08:29
> oh I wonder if it's because I use impeller

yeah you're right. i've updated the description with what I found and a video. when you're back, feel free to add if you find anything missing. thanks!

**Comment by jonahwilliams** [comment] 2023-05-06 17:24
This should be fixed in the latest beta. Duplicate of https://github.com/flutter/flutter/issues/124658

**Closed by jonahwilliams** 2023-05-06 17:24 UTC
Labels: engine, impeller
