### ISSUE TITLE
.\gn --runtime-mode=jit_release --android --android-cpu=x86  DON1T WORK

### ISSUE THREAD

**Issue by joswan2567** [flutter/flutter#76303] opened 2021-02-18 13:19 UTC
```
PS C:\engine\tools> G:/Python38/python .\gn --runtime-mode=jit_release --android --android-cpu=x86 
GOMA usage was specified but can't be found, falling back to local builds. Set the GOMA_DIR environment variable to fix GOMA.
Generating GN files in: out\android_jit_release_x86
Traceback (most recent call last):
  File ".\gn", line 503, in <module>
    sys.exit(main(sys.argv))
  File ".\gn", line 471, in main
    gn_call_result = subprocess.call(command, cwd=SRC_ROOT)
  File "G:\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "G:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "G:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado
PS C:\engine\tools>
```

**Comment by iapicca** [comment] 2021-02-18 13:42
@joswan2567 
not sure this is flutter related
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by joswan2567** [comment] 2021-02-18 13:48
The error happens when I try to execute the command in order to build release versions x_86 using JIT Release Modes

https://github.com/flutter/flutter/wiki/JIT-Release-Modes

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [versÃ£o 10.0.18363.1379], locale pt-BR)
    • Flutter version 1.22.5 at C:\src\flutter\flutter_windows_1.22.3-stable\flutter
    • Framework revision 7891006299 (2 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\joswan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

**Comment by darshankawar** [comment] 2021-02-18 13:54
@joswan2567 
Can you check out [this](https://github.com/flutter/flutter/issues/41372) issue and see if it resemble yours ?

**Comment by joswan2567** [comment] 2021-02-18 14:03
it looks like we did the same process, but we came up with different errors. I believe I should leave my mistake in the same question, tks

**Comment by darshankawar** [comment] 2021-02-19 06:45
@joswan2567 
If I understand correctly, you would like to keep this issue open or follow-up in referred link ? 
If not, can you elaborate how and where do we need to run this command ? Also since I am on mac, I may hit the same issue as in referred issue.

**Comment by pedromassangocode** [comment] 2021-03-12 14:07
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-12 14:07 UTC
Labels: in triage, waiting for customer response
