### ISSUE TITLE
[release blocker] doc test failing on beta branch (next stable)

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#131942] opened 2023-08-04 17:37 UTC
As seen on flutter dashboard, doc test has been failing on beta branch throughout multiple releases.  https://flutter-dashboard.appspot.com/#/build?repo=flutter&branch=flutter-3.13-candidate.0

When we promote beta to stable in a few weeks, would be great if the doc test is green. [Attempted a fix](https://chat.google.com/room/AAAAc_4rqiI/pl4B0W45bLA) but after many hours we couldn't find the root cause of the error. Would be great if expert like @godofredoc @sealesj could help provide some insights. Thank you!

cc @CaseyHillers

**Comment by godofredoc** [comment] 2023-08-04 20:25
This seems like a problem with the docs generation.

```
\s*<iframe\s+class="snippet-dartpad"\s+src="https:\/\/dartpad.dev\/embed-flutter.html\?.*?\bsample_channel=flutter-3.13-candidate.0\b.*">\s*<\/iframe>' in dev/docs/doc/api/widgets/Listener-class.html.
```

What happens when you checkout the release candidate branch and run: `./dev/bots/docs.sh`?

**Comment by XilaiZhang** [comment] 2023-08-04 20:42
thanks for inspecting! yeah running docs.sh on release candidate branch 3.13.0 gives many exceptions in https://paste.googleplex.com/5282349536247808

**Comment by XilaiZhang** [comment] 2023-08-07 21:54
Still unsure why doc tests fail.

For context, Greg verified that when release branch is checked out locally, doc tests pass. However, if doc tests fail on luci, it would not upload the docs to the [api.flutter.dev](http://api.flutter.dev/) website. and this might be bad if we later decide to promote this branch to stable, because the docs would be out of sync

**Comment by CaseyHillers** [comment] 2023-08-09 01:46
Moving out of release blockers.

I was able to manually verify the latest beta hash's doc.zip, and looking at the culprit api page I do not see any regressions. I sampled a few other pages as well and do not see other issues.

**Comment by godofredoc** [comment] 2023-08-10 03:46
The problem is that current list of branches is returned with white spaces:

```
['* (HEAD detached at 7e07cd41cb)', '  remotes/origin/flutter-3.13-candidate.0']
```

And the logic fails here: https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/repo_util/api.py;l=336?q=is_release_candidate_branch&ss=flutter

**Comment by godofredoc** [comment] 2023-08-15 16:58
Fixed with https://flutter-review.googlesource.com/c/recipes/+/48980

**Closed by godofredoc** 2023-08-15 16:58 UTC
Labels: P2, team-release

**Comment by XilaiZhang** [comment] 2023-08-15 17:03
Yeah thanks a lot for the fix for both doc test and code sign!
