### ISSUE TITLE
how can i click on allow pub up message to grant permission by integration test package in flutter ? 

### ISSUE THREAD

**Issue by ahmadhamedd** [flutter/flutter#87665] opened 2021-08-04 16:12 UTC
i wrote an integration test by `integration test` package with `flutter`.
but my app need to grant location permission, and it show native pub up message to allow or deny
i want to click on allow button by automated test using `integration test package`

**Comment by stuartmorgan** [comment] 2021-08-04 16:35
Duplicate of https://github.com/flutter/flutter/issues/87440

**Closed by stuartmorgan** 2021-08-04 16:35 UTC
