### ISSUE TITLE
Unable to have a clean run Flutter doctor

### ISSUE THREAD

**Issue by buisine** [flutter/flutter#14109] opened 2018-01-16 00:01 UTC
## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Invalid locale 'ia_FR.UTF-8'

```
#0      Intl._throwLocaleError (package:intl/intl.dart:231)
#1      Intl.verifiedLocale (package:intl/intl.dart:225)
#2      Intl.verifiedLocale (package:intl/intl.dart:210)
#3      new NumberFormat._forPattern (package:intl/src/intl/number_format.dart:486)
#4      new NumberFormat.decimalPattern (package:intl/src/intl/number_format.dart:175)
#5      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:97)
#6      kMillisecondsFormat (package:flutter_tools/src/base/utils.dart:97)
#7      getElapsedAsMilliseconds (package:flutter_tools/src/base/utils.dart:105)
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:202)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1467)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#24     main (file:///home/dawd/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Linux, locale ia_FR.UTF-8, channel alpha)
    • Flutter at /home/dawd/flutter
    • Framework revision 8f65fec5f5 (5 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /home/dawd/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.4127.31

[-] Connected devices
    • None

**Comment by Hixie** [comment] 2018-05-23 21:02
Duplicate of https://github.com/flutter/flutter/issues/11151

**Closed by Hixie** 2018-05-23 21:02 UTC
