### ISSUE TITLE
closing app using SystemNavigator.pop not working in iOS

### ISSUE THREAD

**Issue by metarsul** [flutter/flutter#55760] opened 2020-04-27 20:07 UTC
Hi, I'm trying to close my app if the user do not accept the service agreement.
So inside a button, I`m doing:

```
onPressed: ()async{
  SharedPreferences prefs = await SharedPreferences.getInstance();
  prefs.setBool('accepted', false);
  SystemChannels.platform.invokeMethod<void>('SystemNavigator.pop');
}
```
when i click, nothing happens!

* working fine in Android! 
```
[✓] Flutter (Channel master, v1.18.0-8.0.pre.3, on Mac OS X 10.15.4 19E287, locale pt-BR)
    • Flutter version 1.18.0-8.0.pre.3 at /Users/rodrigo/development/flutter
    • Framework revision 9f92ec2651 (4 days ago), 2020-04-23 22:53:31 +0300
    • Engine revision 8fff8da38d
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rodrigo/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11                 • EAB4F9A8-7EEC-4179-9EE3-63D5685EA278 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment] 2020-04-28 07:48
Hi @metarsul ,
this is intended behaviour, please take a look at https://api.flutter.dev/flutter/services/SystemNavigator/pop.html 
and https://stackoverflow.com/questions/58680475/how-to-use-systemnavigator-pop-in-below-code-to-exit-app-in-flutter

**Comment by VladyslavBondarenko** [comment] 2020-04-28 10:34
Closing the issue, since this is not a flutter specific issue, but rather of native platform,
If you disagree please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-04-28 10:34 UTC
