### ISSUE TITLE
[Proposal] Size Configuration for RadioThemeData

### ISSUE THREAD

**Issue by evandrmb** [flutter/flutter#98601] opened 2022-02-16 19:36 UTC
## Use case

Flutter only allow developers to set size indirectly by using `MaterialTapTargetSize`  in Radio. Wich is probably motivated by accessibility concerns, but the same could be implied to buttons and yet we can set size directly into them.

Even tho we can use visual density to change it a bit, I don't think it's enough.

## Proposal
Create a nullable property `size` which would allow developers to set it by themselves and in case it's not informed use the `MaterialTapTargetSize` default configuration which is:

```dart
  switch (effectiveMaterialTapTargetSize) {
      case MaterialTapTargetSize.padded:
        size = const Size(kMinInteractiveDimension, kMinInteractiveDimension);
        break;
      case MaterialTapTargetSize.shrinkWrap:
        size = const Size(kMinInteractiveDimension - 8.0, kMinInteractiveDimension - 8.0);
        break;
    }
```

**Comment by danagbemava-nc** [comment] 2022-02-17 08:04
Hi @evandrmb, there's a similar proposal in https://github.com/flutter/flutter/issues/81334. I've added a link to this issue so that your suggestion can also properly reviewed. Considering these two issues are requesting the same thing, albeit with different approaches, I'm going to close this issue as a duplicate of https://github.com/flutter/flutter/issues/81334. 

Thank you

**Closed by danagbemava-nc** 2022-02-17 08:04 UTC
Labels: in triage
