### ISSUE TITLE
webview_flutter: allow the target url to access geolocation

### ISSUE THREAD

**Issue by NewITCorp** [flutter/flutter#38021] opened 2019-08-10 06:18 UTC
Hi, I am using Openlayers bundled in the app using webview_flutter (official plugin). the target website needs to access the device location. in browser it will popup like 

> this website needs to access your location. (allow or deny)

but the problem when attach it to the webview it does not ask anything and seems to deny by default. so how to allow it programmatically? or at least allow popup to the user.

you can try using this url to test:

https://gps-coordinates.org/

thanks

**Comment by wangslo** [comment] 2019-11-26 10:30
me too!!!

**Comment by khalithartmann** [comment] 2021-07-31 21:52
any news?

**Comment by stuartmorgan** [comment] 2023-04-17 23:15
Duplicate of https://github.com/flutter/flutter/issues/27472

**Closed by stuartmorgan** 2023-04-17 23:15 UTC
Labels: plugin, customer: crowd, p: webview, proposal, P5
