### ISSUE TITLE
flutter video player updated to 0.8.0,  Once you have called dispose() 

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter#25936] opened 2019-01-01 07:51 UTC
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (32582): The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#16736](state:
I/flutter (32582): OverlayState#a5811(entries: [OverlayEntry#82b2f(opaque: true; maintainState: false),
I/flutter (32582): OverlayEntry#32acf(opaque: false; maintainState: true)])):
I/flutter (32582): A VideoPlayerController was used after being disposed.
I/flutter (32582): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
I/flutter (32582): 
I/flutter (32582): When the exception was thrown, this was the stack:
I/flutter (32582): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:108:9)
I/flutter (32582): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:114:6)
I/flutter (32582): #2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:169:12)
I/flutter (32582): #3      _VideoPlayerState.deactivate (package:video_player/video_player.dart:473:23)
I/flutter (32582): #4      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:3893:12)
I/flutter (32582): #5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1727:13)
I/flutter (32582): #6      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (32582): #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (32582): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (32582): #9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
```

**Comment by zoechi** [comment] 2019-01-02 09:04
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by Seifon** [comment] 2019-01-03 15:17
```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D32a, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/seifon/dev-tool/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/seifon/dev-tool/Android_Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/seifon/dev-tool/Android_Sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java
    • Java version java version "1.8.0_191"
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4588.61

[✓] Connected device (3 available)
    • M10                       • 0123456789ABCDEF                     • android-arm • Android 7.0 (API 19)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.0 (API 24) (emulator)
    • iPhone XR                 • 03B35AED-25E5-4CEF-A485-DCB0C21154C7 • ios         • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.

```

**Comment by zoechi** [comment] 2019-01-28 09:46
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-28 09:46 UTC
Labels: p: first party, plugin, severe: crash, waiting for customer response

**Comment by dkuzovenkov** [comment] 2019-01-28 20:56
Hello! I have the same problem on this example (https://pub.dartlang.org/packages/camera#-example-tab-) when trying to start video record / stop record and again start record / stop record or when start video record / stop record and then take picture.

**Comment by noelmansour** [comment] 2019-03-04 19:05
@zoechi I think this issue should be reopened. It's either a bug in the video_player plugin or camera plugin example.

It can be reproduced by running the camera plugin example and doing the following:
(After providing permission and selecting a camera)
1. Record a video
2. Press stop
3. Record another video
4. Press stop. 

Exception is thrown with `A VideoPlayerController was used after being disposed.` message.

It seems to be caused by the `VideoPlayer` and `VideoPlayerController` lifecycles being out of sync. It starts with this code from the camera plugin example.

```dart
  Future<void> _startVideoPlayer() async {
    final VideoPlayerController vcontroller =
        VideoPlayerController.file(File(videoPath));
    videoPlayerListener = () {
      if (videoController != null && videoController.value.size != null) {
        // Refreshing the state to update video player with the correct ratio.
        if (mounted) setState(() {}); // <<<<< This triggers a didUpdateWidget() in VideoPlayer
        videoController.removeListener(videoPlayerListener);
      }
    };
    vcontroller.addListener(videoPlayerListener);
    await vcontroller.setLooping(true);
    await vcontroller.initialize();
    await videoController?.dispose(); // <<<<< This is disposing the old controller
    if (mounted) {
        setState(() {
        imagePath = null;
        videoController = vcontroller;
      });
    }
    await vcontroller.play(); // <<<<< Triggers videoPlayerListener
  }
```

When `videoController?.dispose()` is called, the old controller gets disposed. However, the `vcontroller.play()` call will trigger the `videPlayerListener`. The listener will then call `setState()` which triggers `didUpdateWidget()` inside `VideoPlayer`.

```dart
  @override
  void didUpdateWidget(VideoPlayer oldWidget) {
    super.didUpdateWidget(oldWidget);
    oldWidget.controller.removeListener(_listener); // <<<<< controller has already been disposed at this point resulting in the exception being thrown
    _textureId = widget.controller.textureId;
    widget.controller.addListener(_listener);
  }
```

`didUpdateWidget()` attempts to remove the internal listener from the old controller. Because the old controller has already been disposed, an exception is thrown.

If the camera example calls `dispose()` after the `play()` call, it seems to resolve the issue:
```dart
  Future<void> _startVideoPlayer() async {
    final VideoPlayerController vcontroller =
        VideoPlayerController.file(File(videoPath));
    videoPlayerListener = () {
      if (videoController != null && videoController.value.size != null) {
        // Refreshing the state to update video player with the correct ratio.
        if (mounted) setState(() {});
        videoController.removeListener(videoPlayerListener);
      }
    };
    vcontroller.addListener(videoPlayerListener);
    await vcontroller.setLooping(true);
    await vcontroller.initialize();
    final VideoPlayerController oldController = videoController;
    if (mounted) {
      setState(() {
        imagePath = null;
        videoController = vcontroller;
      });
    }
    await vcontroller.play();
    await oldController?.dispose();
  }
```

However, it may make more sense for the `VideoPlayer` to check if the controller is disposed before calling `removeListener()`:

```dart
  @override
  void didUpdateWidget(VideoPlayer oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (!oldWidget.controller._isDisposed) {
      oldWidget.controller.removeListener(_listener);
    }
    _textureId = widget.controller.textureId;
    widget.controller.addListener(_listener);
  }
```

I'd be happy to open a PR with either of the fixes, but not sure if there's some underlying design decisions behind the current approach.

Finally, here's my flutter doctor output, if needed:

```
[✓] Flutter (Channel master, v1.3.3-pre.18, on Mac OS X 10.14.3 18D109, locale en-CA)
    • Flutter version 1.3.3-pre.18 at /Users/noel/dev/flutter
    • Framework revision 2bab21b2bd (32 hours ago), 2019-03-03 05:15:28 -0500
    • Engine revision a28329cb91
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Users/noel/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 32.0.2
    • Dart plugin version 183.4588.61

[✓] Connected device (1 available)
    • Nexus 5 • 0401edaf220d07a7 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by anztrax** [comment] 2019-03-30 20:53
thanks @noelmansour , your solution works for me 👍

**Comment by jasonkaruza** [comment] 2019-05-03 22:05
I too am having the same issue and have the latest video_player v 0.10.0+8.

`[√] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 3.3)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)`

I am not using the camera app, so the exact situation is not quite the same (there is only one VideoController for example), but I am getting the same "A VideoPlayerController was used after being disposed." error.

`I/flutter (14442): Stack trace:
main.<fn>
FlutterError.reportError
_debugReportException
ComponentElement.performRebuild
Element.rebuild
StatelessElement.update
Element.updateChild
RenderObjectElement.updateChildren
MultiChildRenderObjectElement.update
Element.updateChild
SingleChildRenderObjectElement.update
I/flutter (14442): pac
I/flutter (14442): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (14442): The following assertion was thrown building Container(constraints: BoxConstraints(w=349.7,
I/flutter (14442): h=370.3)):
I/flutter (14442): A VideoPlayerController was used after being disposed.
I/flutter (14442): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
I/flutter (14442):
I/flutter (14442): When the exception was thrown, this was the stack:
I/flutter (14442): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> 
I/flutter (14442): #1      ChangeNotifier._debugAssertNotDisposed 
I/flutter (14442): #2      ChangeNotifier.removeListener 
I/flutter (14442): #3      _VideoPlayerState.deactivate
I/flutter (14442): #4      StatefulElement.deactivate 
I/flutter (14442): #5      _InactiveElements._deactivateRecursively 
I/flutter (14442): #6      SingleChildRenderObjectElement.visitChildren 
I/flutter (14442): #7      _InactiveElements._deactivateRecursively 
I/flutter (14442): #8      SingleChildRenderObjectElement.visitChildren 
I/flutter (14442): #9      _InactiveElements._deactivateRecursively 
I/flutter (14442): #10     _InactiveElements.add 
I/flutter (14442): #11     Element.deactivateChild 
I/flutter (14442): #12     Element.updateChild 
I/flutter (14442): #13     SingleChildRenderObjectElement.update 
I/flutter (14442): #14     Element.updateChild 
I/flutter (14442): #15     ComponentElement.performRebuild 
I/flutter (14442): #16     Element.rebuild 
I/flutter (14442): #17     StatelessElement.update 
I/flutter (14442): #18     Element.updateChild 
I/flutter (14442): #19     RenderObjectElement.updateChildren 
I/flutter (14442): #20     MultiChildRenderObjectElement.update 
I/flutter (14442): #21     Element.updateChild 
I/flutter (14442): #22     SingleChildRenderObjectElement.update 
I/flutter (14442): #23     Element.updateChild 
I/flutter (14442): #24     ComponentElement.performRebuild 
I/flutter (14442): #25     Element.rebuild 
I/flutter (14442): #26     StatelessElement.update 
I/flutter (14442): #27     Element.updateChild 
I/flutter (14442): #28     ComponentElement.performRebuild 
I/flutter (14442): #29     Element.rebuild 
I/flutter (14442): #30     ProxyElement.update 
I/flutter (14442): #31     Element.updateChild 
I/flutter (14442): #32     ComponentElement.performRebuild 
I/flutter (14442): #33     Element.rebuild 
I/flutter (14442): #34     ProxyElement.update 
I/flutter (14442): #35     Element.updateChild 
I/flutter (14442): #36     RenderObjectElement.updateChildren 
I/flutter (14442): #37     MultiChildRenderObjectElement.update 
I/flutter (14442): #38     Element.updateChild 
I/flutter (14442): #39     ComponentElement.performRebuild 
I/flutter (14442): #40     Element.rebuild 
I/flutter (14442): #41     StatefulElement.update 
I/flutter (14442): #42     Element.updateChild 
I/flutter (14442): #43     ComponentElement.performRebuild 
I/flutter (14442): #44     Element.rebuild 
I/flutter (14442): #45     ProxyElement.update 
I/flutter (14442): #46     Element.updateChild 
I/flutter (14442): #47     ComponentElement.performRebuild 
I/flutter (14442): #48     Element.rebuild 
I/flutter (14442): #49     StatefulElement.update 
I/flutter (14442): #50     Element.updateChild 
I/flutter (14442): #51     SingleChildRenderObjectElement.update 
I/flutter (14442): #52     Element.updateChild 
I/flutter (14442): #53     ComponentElement.performRebuild 
I/flutter (14442): #54     Element.rebuild 
I/flutter (14442): #55     StatelessElement.update 
I/flutter (14442): #56     Element.updateChild 
I/flutter (14442): #57     SingleChildRenderObjectElement.update 
I/flutter (14442): #58     Element.updateChild 
I/flutter (14442): #59     ComponentElement.performRebuild 
I/flutter (14442): #60     Element.rebuild 
I/flutter (14442): #61     StatefulElement.update 
I/flutter (14442): #62     Element.updateChild 
I/flutter (14442): #63     ComponentElement.performRebuild 
I/flutter (14442): #64     Element.rebuild 
I/flutter (14442): #65     StatefulElement.update 
I/flutter (14442): #66     Element.updateChild 
I/flutter (14442): #67     ComponentElement.performRebuild 
I/flutter (14442): #68     Element.rebuild 
I/flutter (14442): #69     ProxyElement.update 
I/flutter (14442): #70     Element.updateChild 
I/flutter (14442): #71     ComponentElement.performRebuild 
I/flutter (14442): #72     Element.rebuild 
I/flutter (14442): #73     ProxyElement.update 
I/flutter (14442): #74     Element.updateChild 
I/flutter (14442): #75     ComponentElement.performRebuild 
I/flutter (14442): #76     Element.rebuild 
I/flutter (14442): #77     StatefulElement.update 
I/flutter (14442): #78     Element.updateChild 
I/flutter (14442): #79     ComponentElement.performRebuild 
I/flutter (14442): #80     Element.rebuild 
I/flutter (14442): #81     StatefulElement.update 
I/flutter (14442): #82     Element.updateChild 
I/flutter (14442): #83     ComponentElement.performRebuild 
I/flutter (14442): #84     Element.rebuild 
I/flutter (14442): #85     BuildOwner.buildScope 
I/flutter (14442): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
I/flutter (14442): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
I/flutter (14442): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
I/flutter (14442): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
I/flutter (14442): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
I/flutter (14442): #94     _invoke (dart:ui/hooks.dart:219:10)
I/flutter (14442): #95     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (14442): (elided 3 frames from package dart:async)`

It looks like the Authors of the plugin haven't implemented the suggestion above from noelmansour: https://github.com/flutter/plugins/blob/master/packages/video_player/lib/video_player.dart#L492

```
  VideoPlayerController _videoController;
  VoidCallback _videoListener;

@override
  void initState() {
    super.initState();


     _videoController = VideoPlayerController.file(file)
       ..initialize().then((_) {
         if (mounted) {
            setState(() {
              print("Initialized video Player.");
            });
          }
        });
      _videoListener = () {
        if (_videoController.value.hasError) {
          print(
              "Video player failed to initialize: ${_videoController.value.errorDescription}");
        }
      };
      _videoController.addListener(_videoListener);
      _videoController.setLooping(true);
    });

   @override
  void dispose() {;
    disposeVideoController();
    super.dispose();
  }

void disposeVideoController() {
    if (_videoController == null) {
      print("VideoController already disposed. Returning.");
      return;
    }
    try {
      print("Killing the Video Controller.");
      // Kill the video controller
      _videoController.removeListener(_videoListener);
      _videoController?.dispose();
      _videoController = null;
    } catch (error, stack) {
      print("Failed to dispose of Video Controller: $error", stack);
    }
  }

@override
  Widget build(BuildContext context) {
    // Store when we have a context
    stateData.setBuildContext(context);
    // Show any alert dialogs queued
    NotificationController.showDialogNotification(context);

    // If the video isn't playing but is initialized, play
    if (_videoController != null &&
        _videoController.value.initialized &&
        !_videoController.value.isPlaying) {
      print("Video is not playing, so calling _play()");
      _videoController.play();
    }

    List<Widget> childrenWidgets = [
      // The video
      Container(
        child: (_videoController != null && _videoController.value.initialized)
            ? ClipRRect(
                borderRadius:
                    new BorderRadius.circular(sizeVideoPlayerBorderRadius),
                child: AspectRatio(
                  aspectRatio: _videoController.value.aspectRatio,
                  child: VideoPlayer(_videoController),
                ))
            : Column(
                children: <Widget>[
                  Center(child: CircularProgressIndicator()),
                ],
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
              ),
        height: MediaQuery.of(context).size.height * videoHeightPercent,
        width: MediaQuery.of(context).size.width * videoWidthPercent,
      ),
    ];

    return WillPopScope(
        onWillPop: () async => false,
        child: Scaffold(
            appBar: AppBar(
              backgroundColor: Colors.transparent,
              elevation: 0.0,
            ),
            body: Container(
              alignment: Alignment.center,
              child: Column(
                children: childrenWidgets,
              ),
            )));
  }
```

Can anyone see what I am doing wrong? Thank you in advance.

**Comment by jasonkaruza** [comment] 2019-05-05 21:02
Disregard my previous post. I was calling dispose() explicitly elsewhere, which was prematurely disposing while build() was still being called. By allowing the natural widget's dispose() method to be called, and just disposing of the video controller inside of that, it resolved the issue for me (I think). More testing to confirm.

**Comment by carlosalito** [comment] 2020-05-03 17:00
@noelmansour your are great! Save my week!!!! tks
