### ISSUE TITLE
TextField rendering issue when overflowing

### ISSUE THREAD

**Issue by leonardocustodio** [flutter/flutter#67344] opened 2020-10-05 20:33 UTC
Hi,

I'm having this issue with the TextField widget:

![](https://i.imgur.com/Mzq38bK.gif)

Here is the TextField code used:

```
Container(
                                  height: 48.0,
                                  margin: const EdgeInsets.only(top: 6.0),
                                  child: TextField(
                                    maxLines: 1,
                                    onChanged: pinStore.setEmail,
                                    decoration: InputDecoration(
                                      fillColor: Color(0xFFF1F3F5),
                                      filled: true,
                                      border: OutlineInputBorder(
                                        borderSide: BorderSide(
                                          color: Color(0xFFE2E4E5),
                                          width: 1.0,
                                        ),
                                        borderRadius: BorderRadius.circular(8.0),
                                      ),
                                      enabledBorder: OutlineInputBorder(
                                        borderSide: BorderSide(
                                          color: Color(0xFFE2E4E5),
                                          width: 1.0,
                                        ),
                                        borderRadius: BorderRadius.circular(8.0),
                                      ),
                                      focusedBorder: OutlineInputBorder(
                                        borderSide: BorderSide(
                                          color: Color(0xFFE2E4E5),
                                          width: 1.0,
                                        ),
                                        borderRadius: BorderRadius.circular(8.0),
                                      ),
                                    ),
                                  ),
                                ),
```

Flutter doctor:

```
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale pt-BR)
    • Flutter version 1.22.0 at C:\flutter
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\NVPACK\android-sdk-windows
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\NVPACK\android-sdk-windows
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
```

Regards,

**Comment by leonardocustodio** [comment] 2020-10-05 20:39
If setting the content padding, removing vertical padding, as followed it fixes the issue. But I don't think the default behavior should be as the above.

`contentPadding: const EdgeInsets.symmetric(horizontal: 10.0),`

**Comment by Calamity210** [comment] 2020-10-06 00:46
Was able to reproduce this where a `focusedBorder` or `border` was given, using `enabledBorder` alone seems to be functioning correctly. Haven't gotten around to testing anything else

**Comment by darshankawar** [comment] 2020-10-06 09:39
Issue replicable on latest master as well and probably seems to be happening due to the Container height. If we remove `height`, the text overflow goes on properly, but with `height`, the text starts to cut-off.

![67344](https://user-images.githubusercontent.com/67046386/95185037-d2c58f80-07e5-11eb-9c93-ad849ad14b67.png)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.132, on Mac OS X 10.15.4 19E2269
    x86_64, locale en-IN)
    • Flutter version 1.23.0-8.0.pre.132 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 5e97eed895 (26 hours ago), 2020-10-05 00:42:50 -0700
    • Engine revision a8d7d97bef
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos       • darwin-x64     • Mac OS X 10.15.4
      19E2269 x86_64
    • Web Server (web)  • web-server  • web-javascript • Flutter Tools
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!

```

</details>

**Comment by jason-simmons** [comment] 2020-10-07 01:52
See https://github.com/flutter/flutter/issues/51257

**Comment by darshankawar** [comment] 2020-10-07 05:30
Closing this as duplicate of [51257](https://github.com/flutter/flutter/issues/51257).

**Closed by darshankawar** 2020-10-07 05:30 UTC
Labels: a: text input, a: typography, f: material design, found in release: 1.23, framework, has reproducible steps
