### ISSUE TITLE
`flutter run` failed on Ubuntu

### ISSUE THREAD

**Issue by bulsond** [flutter/flutter#115910] opened 2022-11-23 09:16 UTC
## Steps to Reproduce

1. `flutter create --platforms=linux app_test`
2. `cd app_test`
3. `flutter run`

## Logs
```bash
Launching lib/main.dart on Linux in debug mode...
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/bul/Desktop/app_test/build/linux/x64/debug/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/ninja cmTC_6702a && [1/2] Building CXX object CMakeFiles/cmTC_6702a.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_6702a
    FAILED: cmTC_6702a 
    : && /usr/bin/clang++   CMakeFiles/cmTC_6702a.dir/testCXXCompiler.cxx.o -o cmTC_6702a   && :
    /usr/bin/ld: cannot find -lstdc++: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


Building Linux application...                                           
Exception: Unable to generate build files
```
if I give the command: `ls -dl /usr/bin/ld` then `lrwxrwxrwx 1 root root 19 июл 19 13:17 /usr/bin/ld -> x86_64-linux-gnu-ld`

## Flutter doctor
```bash
[✓] Flutter (Channel stable, 3.3.8, on Ubuntu 22.04.1 LTS 5.15.0-53-generic, locale en_US.UTF-8)
    • Flutter version 3.3.8 on channel stable at /home/bul/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (2 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/bul/Android/Sdk/
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /home/bul/bin/idea-IC-222.4345.14
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-53-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by exaby73** [comment] 2022-11-23 11:55
Closing as duplicate of https://github.com/flutter/flutter/issues/115909

**Closed by exaby73** 2022-11-23 11:55 UTC
Labels: in triage
