### ISSUE TITLE
Adding inner shadow support

### ISSUE THREAD

**Issue by Gianthard-cyh** [flutter/flutter#88526] opened 2021-08-19 12:57 UTC
## Use case

I'm having some problems in adding Inner shadows to my application. Although some developers had already posted [a few practicable solutions](https://stackoverflow.com/questions/54061964/inner-shadow-effect-in-flutter), some of them are not so perfect. Most of them are in conflict with drop shadows, which means I can just apply one of them. Although there is a package called [sums_inner](https://pub.dev/packages/sums_inner) that adds inner shadow support to flutter, it was last updated on Sep 30, 2020, and do not support null safety, I cannot use it in my own project. So I hope that flutter will support inner shadow natively, because I think it's necessary for building a modern-style app, which is beautiful enough.

## Proposal

Add inner shadow support to flutter and make it native.
Here is the way I hope to use inner shadow:
```
Container(
  boxShadow: [
    BoxShadow(
      inner: true //this constructs an inner shadow 
    ),
    BoxShadow(
      inner: false //this constructs a drop shadow, and the default value of inner parameter should be "false" 
    ),
  ]
);
```

**Comment by Gianthard-cyh** [comment] 2021-08-19 13:04
This problem is also mentioned in #18636, I can't believe that a modern UI platform doesn't support inner shadow natively.

**Comment by darshankawar** [comment] 2021-08-23 06:43
Similar / related: https://github.com/flutter/flutter/issues/18636

/Cc: @HansMuller

**Comment by nt4f04uNd** [comment] 2021-08-23 14:16
I believe both #18636 and this issue are duplicates of https://github.com/flutter/flutter/issues/52999 (since it has a PR linked to it)

**Comment by darshankawar** [comment] 2021-08-24 06:17
Thanks @nt4f04uNd for the tip.
Closing this as duplicate of https://github.com/flutter/flutter/issues/88526.
@Gianthard-cyh Please follow-up in linked issue.

Note: Keeping 18636 as-is, since it's a crowd issue.

**Closed by darshankawar** 2021-08-24 06:17 UTC
Labels: severe: new feature, framework, f: material design, proposal, passed first triage
