### ISSUE TITLE
flutter 2.5 android BackgroundMode use transparent,sometimes page is show black screen

### ISSUE THREAD

**Issue by lzhAndroid** [flutter/flutter#92902] opened 2021-11-02 10:19 UTC
<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.4.0-54-generic, locale en_US.UTF-8)
    • Flutter version 2.5.3 at /home/monkey/Codesoft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/monkey/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/monkey/Android/Sdk
    • ANDROID_SDK_ROOT = /home/monkey/Android/Sdk
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.1)
    • Android Studio at /home/monkey/Codesoft/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8430
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • MI 6 (mobile)   • 75df9a8c • android-arm64  • Android 9 (API 28)
    • Linux (desktop) • linux    • linux-x64      • Ubuntu 20.04.3 LTS 5.4.0-54-generic
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 95.0.4638.54
```
</details>

**Comment by danagbemava-nc** [comment] 2021-11-02 10:47
Hi @lzhAndroid, thanks for filing the issue, please provide a complete minimal reproducible code sample. 

Thank you

**Comment by luojt** [comment] 2021-11-04 10:22
me too

**Comment by lzhAndroid** [comment] 2021-11-05 01:33
[https://github.com/lzhAndroid/res/blob/main/%E9%A3%9E%E4%B9%A620211105-093000.mp4?raw=true](url)

**Comment by lzhAndroid** [comment] 2021-11-05 01:37
> [https://github.com/lzhAndroid/res/blob/main/%E9%A3%9E%E4%B9%A620211105-093000.mp4?raw=true](url)

record it on my app,I'll try remove code make a sample demo,but the sample demo,only show this issue on phone with HUAWEI and try 100 times only show 1 or 2 times;

**Comment by lzhAndroid** [comment] 2021-11-05 01:44
kill activity and restart it ,sometime it show balck,and you can see log is right.you can enter screen the button can click and can jump to another page but the screen is always black.

**Comment by lzhAndroid** [comment] 2021-11-05 01:47
on black state,I click a button to a page which it have a flutter_webview,the page it's right show.

**Comment by luojt** [comment] 2021-11-05 01:51
@lzhAndroid I think so. When the flutter engine is recycled and the activity is still active, a black screen will appear, because it has not been rendered, but the black screen interface can still be clicked, because the event is still valid. When the engine is started, click the app again to display the normal screen; If the activity and the flutter engine are recycled at the same time, open the app and restart it.

**Comment by luojt** [comment] 2021-11-05 01:59
Please watch the video.


https://user-images.githubusercontent.com/20235738/140445496-bfd7e6b5-67cb-45d2-a4ef-a1bc57c49af0.mp4

**Comment by lzhAndroid** [comment] 2021-11-05 02:03
> Please watch the video.
> 
>  SVID_20211105_095522_1.mp4

the same

**Comment by lzhAndroid** [comment] 2021-11-05 04:05
I use Navigator2.0,if I replace Navigator to Container,it's ok.and you? @luojt

**Comment by luojt** [comment] 2021-11-05 05:26
> I use Navigator2.0,if I replace Navigator to Container,it's ok.and you? @luojt
> 
> ![image](https://github.com/lzhAndroid/res/blob/main/%E9%A3%9E%E4%B9%A620211105-120752.png?raw=true)

Sorry, I can't understand your context.

**Comment by luojt** [comment] 2021-11-05 05:29
> I use Navigator2.0,if I replace Navigator to Container,it's ok.and you? @luojt
> 
> ![image](https://github.com/lzhAndroid/res/blob/main/%E9%A3%9E%E4%B9%A620211105-120752.png?raw=true)

My QQ number is 1337843618.Shall we discuss it.

**Comment by danagbemava-nc** [comment] 2021-11-05 06:17
> kill activity and restart it ,sometime it show black, and you can see log is right.you can enter screen the button can click and can jump to another page but the screen it's always black.

@lzhAndroid, we will need a sample reproduction code to make this issue actionable. Kindly provide a sample without any third party dependencies. 
Thank you

**Comment by tnvinh2711** [comment] 2021-11-12 02:13
hi @lzhAndroid, did you preproduce. I had same problem, sometimes black screen appear..

**Comment by llgoer** [comment] 2021-11-21 12:38
same problem

**Comment by lzhAndroid** [comment] 2021-11-30 05:43
In channel beta,flutter 2.8.0-3.2.pre,this error is fixed.

**Comment by danagbemava-nc** [comment] 2021-11-30 06:24
Given the comment in https://github.com/flutter/flutter/issues/92902#issuecomment-982306103, 

I feel it is safe to close this issue. 

Closing as fixed. 

If anyone still experiences this issue, kindly provide the output of `flutter doctor -v` and a complete minimal reproducible code sample. Thank you

**Closed by danagbemava-nc** 2021-11-30 06:24 UTC
Labels: in triage
