### ISSUE TITLE
How to set flutter version in snapcraft.yaml.

### ISSUE THREAD

**Issue by zschao** [flutter/flutter#126808] opened 2023-05-15 09:15 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I cannot set the Flutter version.

### Actual results

My project is developed based on Flutter 3.3.10, but Snapcraft will automatically upgrade to the latest version of Flutter. What should I do?

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment] 2023-05-15 09:44
Please do not file multiple issues for the same bug. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/126798.

The flutter team does not handle snapcraft or how to use it, kindly ask your question on stackoverflow.

**Closed by danagbemava-nc** 2023-05-15 09:44 UTC
Labels: in triage
