### ISSUE TITLE
%5Btool_crash%5D FileSystemException%3A Cannot open file%2C OS Error%3A The system cannot find the path specified.%0D%0A%2C errno %3D 3

### ISSUE THREAD

**Issue by Antoni-Vasilev** [flutter/flutter#150173] opened 2024-06-13 07:42 UTC
%23%23 Command%0A%60%60%60%0Aflutter gen-l10n%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0AFileSystemException%3A Cannot open file%2C OS Error%3A The system cannot find the path specified.%0D%0A%2C errno %3D 3%0A%60%60%

**Comment by danagbemava-nc** [comment] 2024-06-13 09:13
Closing this as a duplicate of https://github.com/flutter/flutter/issues/106953

In the future, please provide a fully formatted issue with all the relevant details. 

Thank you

**Closed by danagbemava-nc** 2024-06-13 09:13 UTC
Labels: in triage
