### ISSUE TITLE
Flutter 1.17.0 showing debug logs on every screen tap

### ISSUE THREAD

**Issue by 55ahmedsalah** [flutter/flutter#56831] opened 2020-05-10 14:00 UTC
I already made an issue before with the 1.12.3 version
[flutter_windows_v1.12.13+hotfix.8-stable logging on every tap or when changing screens](https://github.com/flutter/flutter/issues/50892)
I am wondering why is this also occurring with the new 1.17.0 version

```
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision e6b34c2b5c (8 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)

• No issues found!

```

**Comment by VladyslavBondarenko** [comment] 2020-05-11 11:26
Hi @55ahmedsalah 
could you provide a minimal complete reproducible code sample?

**Comment by 55ahmedsalah** [comment] 2020-05-11 17:59
> Hi @55ahmedsalah
> could you provide a minimal complete reproducible code sample?

I just created a new project without adding anything an ran it. Every tap on the screen make a log which gets annoying as time progresses.

**Comment by VladyslavBondarenko** [comment] 2020-05-12 07:45
On windows 10.0.18362.778 with `stable v1.17.0` I have run default project from `flutter create` on Android 9 device and I can't see the logs on tapping

**Comment by 55ahmedsalah** [comment] 2020-05-12 16:31
> On windows 10.0.18362.778 with `stable v1.17.0` I have run default project from `flutter create` on Android 9 device and I can't see the logs on tapping

So what do you suggest me to do for my problem? Is it a Windows issue or device issue?
My Android version is 7.0.

**Comment by 55ahmedsalah** [comment] 2020-05-12 21:05
I also have a problem with Android Studio that the logcat gives a "Please configure Android SDK" message and I can't view the device file explorer as it says "Error intializing ADB: Android Debug Bridge not found". Any solutions for these 2 problems?
![Screenshot](https://user-images.githubusercontent.com/26046136/81745363-030e3980-94a5-11ea-8e76-ac53bb585fd0.png)

**Comment by 55ahmedsalah** [comment] 2020-05-17 17:25
`
I/art     ( 1104): Do partial code cache collection, code=124KB, data=104KB
I/art     ( 1104): After code cache collection, code=124KB, data=104KB
I/art     ( 1104): Increasing code cache capacity to 512KB
D/ViewRootImpl@38b14ac[MainActivity]( 1104): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@38b14ac[MainActivity]( 1104): ViewPostImeInputStage processPointer 1
D/ViewRootImpl@38b14ac[MainActivity]( 1104): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@38b14ac[MainActivity]( 1104): ViewPostImeInputStage processPointer 1
I/MediaRecorderJNI( 1104): release
I/MediaRecorderJNI( 1104): setup
I/MediaRecorderJNI( 1104): setVideoSource(2)
I/MediaRecorderJNI( 1104): setVideoEncoder(2)
I/MediaRecorderJNI( 1104): setParameter()
I/MediaRecorderJNI( 1104): setVideoFrameRate(30)
I/MediaRecorderJNI( 1104): setVideoSize(320, 240)
I/MediaRecorderJNI( 1104): setParameter()
I/MediaRecorderJNI( 1104): setOutputFile
I/MediaRecorderJNI( 1104): prepare
I/MediaRecorderJNI( 1104): getSurface
I/MediaRecorderJNI( 1104): start
I/MediaRecorderJNI( 1104): stop
I/MediaRecorderJNI( 1104): native_reset
I/ExoPlayerImpl( 1104): Init 172f7c2 [ExoPlayerLib/2.9.6] [zeroflte, SM-G920F, samsung, 24]
I/ACodec  ( 1104):  [] Now uninitialized
I/ACodec  ( 1104): [] onAllocateComponent
I/OMXClient( 1104): MuxOMX ctor
I/ACodec  ( 1104): [OMX.Exynos.avc.dec] Now Loaded
I/MediaCodec( 1104): [OMX.Exynos.avc.dec] setting surface generation to 1130498
I/ACodec  ( 1104): can't find wfdsink-exynos-enable
I/ACodec  ( 1104): codec does not support config priority (err -1010)
I/ACodec  ( 1104): [OMX.Exynos.avc.dec] Now Loaded->Idle
D/SurfaceUtils( 1104): set up nativeWindow 0x7bcf7b6c10 for 320x240, color 0x105, rotation 270, usage 0x2900
I/ACodec  ( 1104): [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 9, minUndequeuedBuffers : 5
I/ACodec  ( 1104): [OMX.Exynos.avc.dec] Now Idle->Executing
I/ACodec  ( 1104): [OMX.Exynos.avc.dec] Now Executing
I/ACodec  ( 1104): [OMX.Exynos.avc.dec] Now handling output port settings change
D/SurfaceUtils( 1104): set up nativeWindow 0x7bcf7b6c10 for 320x240, color 0x105, rotation 270, usage 0x2900
I/ACodec  ( 1104): [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 13, minUndequeuedBuffers : 5
I/ACodec  ( 1104): [OMX.Exynos.avc.dec] Now Executing
D/InputMethodManager( 1104): ISS - flag : 0Pid : 1104 view : com.lipify.lipify
V/InputMethodManager( 1104): Starting input: tba=android.view.inputmethod.EditorInfo@69a02e9 nm : com.lipify.lipify ic=io.flutter.plugin.editing.InputConnectionAdaptor@5ac6b6e
I/InputMethodManager( 1104): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1104): Input channel constructed: fd=174
D/InputTransport( 1104): Input channel destroyed: fd=97
V/InputMethodManager( 1104): Starting input: tba=android.view.inputmethod.EditorInfo@7d0529c nm : com.lipify.lipify ic=io.flutter.plugin.editing.InputConnectionAdaptor@d86e4a5
I/InputMethodManager( 1104): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1104): Input channel constructed: fd=111
D/InputTransport( 1104): Input channel destroyed: fd=174
D/InputMethodManager( 1104): ISS - flag : 0Pid : 1104 view : com.lipify.lipify
W/IInputConnectionWrapper( 1104): getCursorCapsMode on inactive InputConnection
I/MediaRecorderJNI( 1104): finalize
I/MediaRecorderJNI( 1104): release
D/ViewRootImpl@38b14ac[MainActivity]( 1104): MSG_RESIZED: ci=Rect(0, 84 - 0, 840) vi=Rect(0, 84 - 0, 840) or=1
D/ViewRootImpl@38b14ac[MainActivity]( 1104): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={isValid=true 532364443136} surfaceGenerationChanged=false
`
Here are some more of those logs. I believe those are Android logs so how can I hide those as its getting annoying.

**Comment by jmagman** [comment] 2020-07-28 22:55
Duplicate of https://github.com/flutter/flutter/issues/50628.  See also https://github.com/flutter/flutter/issues/50808.

**Closed by jmagman** 2020-07-28 22:55 UTC
Labels: engine, platform-windows
