### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by trunkszi** [flutter/flutter#85596] opened 2021-06-30 05:04 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9101 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:221:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:220:12)
#6      isAppUsingAndroidX (package:flutter_tools/src/android/gradle.dart:898:21)
#7      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:626:17)
#8      injectPlugins (package:flutter_tools/src/plugins.dart:1202:11)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:322:5)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1175:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
```
```
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1052], locale zh-CN)
    • Flutter version 2.2.2 at D:\flutter_windows_2.2.2-stable\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\jdk-16\bin\java
    • Java version OpenJDK Runtime Environment (build 16+36-2231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.3
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7665

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.59

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: adc687823a831bbebe28bdccfac1a628ca621513
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
device_info-2.0.2
devicelocale-0.4.1
flutter_image_compress-1.0.0
flutter_inappwebview-5.3.2
flutter_keyboard_visibility-5.0.2
flutter_keyboard_visibility_web-2.0.0
flutter_plugin_android_lifecycle-2.0.2
flutter_tts-3.1.0
fluttertoast-8.0.7
image_gallery_saver-1.6.9
image_picker-0.7.5+4
image_picker_for_web-2.0.0
launch_review-3.0.1
package_info-2.0.2
path_provider-2.0.2
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
permission_handler-8.1.1
photo_manager-1.2.2
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
url_launcher-6.0.5
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0
wakelock-0.5.2
wakelock_macos-0.1.0+1
wakelock_web-0.2.0+1

**Comment by darshankawar** [comment] 2021-06-30 11:39
Closing this as duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by darshankawar** 2021-06-30 11:39 UTC
Labels: in triage
