### ISSUE TITLE
Issue with hot-restart - dispose method

### ISSUE THREAD

**Issue by tiholic** [flutter/flutter#27463] opened 2019-02-03 12:43 UTC
Socket.IO resource is opened in initState and trying to close on dispose.
Either dispose method is not being called on hot-restart or an async function that is called inside dispose is not executed.

Since the log gets cleared on hot-restart in android studio, there is no logs being printed which are written inside dispose method.

Ref:
https://github.com/infitio/flutter_socket_io/issues/6

**Comment by zoechi** [comment] 2019-02-07 10:07
Please add the output of `flutter doctor -v`.

**Comment by tiholic** [comment] 2019-02-08 06:40
`flutter doctor -v` logs

```
GrackN-33c0:ideaspace rohit$ flutter doctor -v       
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-IN)
    • Flutter version 1.0.0 at /Users/rohit/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/rohit/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rohit/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Rohit’s iPhone • a1836ea42708e12f466c74fdd13774825b94e2db • ios • iOS 12.1.2

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2019-02-08 09:28
https://docs.flutter.io/flutter/widgets/State/reassemble.html might help to work around.

**Comment by tiholic** [comment] 2019-02-18 18:52
@zoechi `reassemble` doesn't work.

Here is what's happening.

dart resources are cleared out on hot-reload but objects created by platform code are still in-tact.
Say an object is created `J-S1` to create a socket connection from android platform code, and we have a dart object instance `D-S1` interacting with `J-S1`.

Now, I perform a hot-reload. `D-S1` is cleared from dart memory, but `J-S1` is still present in android memory.

I would like to be able to clear `J-S1` on hot reload

**Comment by zoechi** [comment] 2019-02-18 20:54
As far as I know there are plans to make native side code for plugins aware of hot-reload if this helps.

> `D-S1` is cleared from dart memory

Not sure how you conclude. Hot-reload is about Dart state to be kept intact.

**Comment by tiholic** [comment] 2019-02-19 07:30
@zoechi i was referring to hot-restart (like in the issue title), my bad.

**Comment by tiholic** [comment] 2019-02-19 07:34
> As far as I know there are plans to make native side code for plugins aware of hot-reload if this helps.

Great to hear! Will native code be made aware of hot-restart along with this enhancement?

**Comment by zoechi** [comment] 2019-02-19 08:15
> dart resources are cleared out on hot-reload but objects created by platform code are still in-tact.

I can't imagine something like this happening with hot-restart.

Hot restart is a complete restart of the app. The only difference is that the build step is skipped and Dart code changes applied to the already running VM on the device/emulator.

Can you please edit all comments and replace hot-reload with hot-restart where applicable.
In the current state this whole issue can not become any more confusing.

**Comment by tiholic** [comment] 2019-02-26 06:23
@zoechi updated the comments.

----
To understand the behavior better, check out my [flutter_socket_io repo](https://github.com/infitio/flutter_socket_io) and try [running the example](https://github.com/infitio/flutter_socket_io#running-example) server and app.

You will be able to see in server logs that **total connected sockets** will keep increasing on every hot-restart

**Comment by zoechi** [comment] 2019-02-26 07:05
It seems I need to run some additional server (`"http://192.168.1.5:7000/"`) to run your example.

I think this is a duplicate of #10437 which should allow your native code to react to hot-reload or hot restart.

**Comment by tiholic** [comment] 2019-02-26 18:10
Yes that issue is similar to this. Plugin code need to know if `hot-restart` event occurred to clear resources.

------
Steps to run server are as below, same is shared in [2nd point of running the example](https://github.com/infitio/flutter_socket_io#running-example)
```
cd example/socket.io.server
run npm i
run npm start
```

open `example/lib/main.dart` and edit the URI in main.dart#7 to point to your local ip (socket server instance) as mentioned above

**Comment by jonahwilliams** [comment] 2019-04-22 03:41
Duplicate of https://github.com/flutter/flutter/issues/10437

**Closed by jonahwilliams** 2019-04-22 03:41 UTC
Labels: framework, p: framework, t: hot reload, tool
