### ISSUE TITLE
It is recommended that 'Image.network' add the errorBuilder parameter

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#52085] opened 2020-03-06 06:51 UTC
It is recommended that 'Image.network' add the errorBuilder parameter

**Comment by TahaTesser** [comment] 2020-03-06 07:58
Hi @2534290808 

If you're experiencing an issue with `Image.network`

If it is a new feature request, please explain in detail 

### Checkout this code sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Image.network('https://i.imgur.com/C5xknx8.png'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
Thank you

**Comment by 2534290808** [comment] 2020-03-06 08:06
I want to add a placeholder when the image download fails, just as `loadingBuilder` adds a placeholder while the image is loading

**Comment by TahaTesser** [comment] 2020-03-06 08:50
Hi @2534290808 

Meanwhile you could use [cached_network_image](https://pub.dev/packages/cached_network_image) to resolve this issue 

Thank you

**Comment by TahaTesser** [comment] 2020-03-06 08:52
Duplicate of [#19996](https://github.com/flutter/flutter/issues/19996)

**Closed by TahaTesser** 2020-03-06 08:52 UTC
