### ISSUE TITLE
Allow optionally getting rid of blur behind `CupertinoNavigationBar` with transparent background color

### ISSUE THREAD

**Issue by intervall-mohammed** [flutter/flutter#151716] opened 2024-07-13 18:33 UTC
### Use case

I simply want to show a background image behind my navigation bar without the blur that is automatically added when I set the background color to `Color(0x00000000)`.

### Proposal

Add a way to disable this behaviour, possibly via a boolean argument to the `CupertinoNaivgationBar` constructor.

**Comment by darshankawar** [comment] 2024-07-15 10:14
Most likely it is similar to https://github.com/flutter/flutter/pull/149102 that is fixed already that you can check and confirm.

**Comment by darshankawar** [comment] 2024-07-16 05:11
Can you provide us a reproducible code sample that shows current behavior along with expected behavior ?

**Comment by lucasjinreal** [comment] 2024-07-21 06:39
Same here, CupertinoNavbar has a Image.fitler harded in source code of flutter.
Does it possible make it optional? So that users might remove the blurred effect of CupertinoNavbar even set transparent?

**Comment by MitchellGoodwin** [comment] 2024-07-25 17:38
Apologies for bumping into triage, but I was looking into #149102 and saw this issue being discussed so I'll give some context in a drive by. #149102 didn't enable this request to remove the blur. But it will make it easy to do so, as that PR did improve the ability to conditionally disable the blur. It just happens automatically instead of being controlled by the developer. I made a quick code sample from [the sample code in the docs](https://api.flutter.dev/flutter/cupertino/CupertinoNavigationBar-class.html).

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(const NavBarApp());

class NavBarApp extends StatelessWidget {
  const NavBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      theme: CupertinoThemeData(brightness: Brightness.light),
      home: NavBarExample(),
    );
  }
}

class NavBarExample extends StatefulWidget {
  const NavBarExample({super.key});

  @override
  State<NavBarExample> createState() => _NavBarExampleState();
}

class _NavBarExampleState extends State<NavBarExample> {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        backgroundColor: Color(0x00000000),
        middle: Text(
          'CupertinoNavigationBar Sample',
          style: TextStyle(color: CupertinoColors.white)
        ),
      ),
      child: Image(
        image: NetworkImage('https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg'),
      ),
    );
  }
}

```

</details>

Which looks like this: 
<img width="435" alt="Screenshot 2024-07-25 at 10 30 19 AM" src="https://github.com/user-attachments/assets/0b901b39-e513-4934-ac6d-f8dc5398dd3b">

The requested behavior is the ability to not blur the top of the owl picture, which is currently not possible.

#149102 adds some automatic transparency that goes away on scroll, so it will temporarily be transparent with no blur, but that will go away once the page is scrolled.

Should be able to be fixed by just adding a boolean to the constructor, but some care would be needed with documentation and testing.

**Comment by darshankawar** [comment] 2024-07-26 05:46
Thanks for providing further insights and code sample @MitchellGoodwin 
I will treat this as a proposal.

**Comment by lucasjinreal** [comment] 2024-07-26 06:47
Thank u for the attention and considerations. @darshankawar 

Stick with iOS standared is one way, while still we might keep the customizable feature as iOS as well so that we make an App on iOS could match simillar appearance than the native one.

**Closed** 2024-08-26 21:40 UTC
Labels: c: new feature, framework, f: cupertino, c: proposal, P2, team-design, triaged-design
