### ISSUE TITLE
编译不过啊？

### ISSUE THREAD

**Issue by jj89757hhb** [flutter/flutter#26264] opened 2019-01-09 02:05 UTC

**Comment by kangwang1988** [comment] 2019-01-09 02:36
@jj89757hhb 

Paster `flutter doctor -v`.
Error message why it fails.
Sample code to reproduce this problem.

**Comment by zoechi** [comment] 2019-01-09 07:54
Closing because there is no actionable information.
If you are still seeing this please create a new issue with more information about how to reproduce.

**Closed by zoechi** 2019-01-09 07:54 UTC
Labels: waiting for customer response
