### ISSUE TITLE
Flake in TypeConversionsTest.CanConvertListOfStrings

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#80964] opened 2021-04-22 17:01 UTC
Seen on: https://github.com/flutter/engine/pull/25706

Backtrace:

```
[ RUN      ] TypeConversionsTest.CanConvertEmptyList
[       OK ] TypeConversionsTest.CanConvertEmptyList (53 ms)
[ RUN      ] TypeConversionsTest.CanConvertListOfStrings
[FATAL:flutter/runtime/dart_isolate.cc(358)] Check failed: GetMessageHandlingTaskRunner()->RunsTasksOnCurrentThread(). 
```

**Comment by chinmaygarde** [comment] 2021-04-26 17:44
I believe the test was re-run. So its hard to figure out how to get the full logs for the specific failing run. Can we past the full link to the failing presubmit when we file flake reports please?

**Comment by Hixie** [comment] 2021-04-27 22:34
(https://github.com/flutter/flutter/issues/52770 had a similar signature)

**Comment by Hixie** [comment] 2021-04-27 22:35
Given the lack of logs or links to logs, this is probably not actionable.

**Comment by zanderso** [comment] 2021-04-30 20:25
Saw this again here: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Host%20Engine/9885/overview

Logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848503154150488272/+/u/Host_Tests_for_host_debug_unopt/stdout?format=raw

But the logs are still not terribly useful since the assertion failure is missing a backtrace. @chinmaygarde Should we be getting backtraces in the logs on a failed `FML_DCHECK`?

**Comment by chinmaygarde** [comment] 2021-04-30 22:59
I tried quite hard (on Mac) to reproduce this locally and the test passes fine 10,000 times repeatedly. [TSAN runs found one issue in the tracing subsystem](https://gist.github.com/chinmaygarde/24358731d3a868d516c4ed3dfad5b1fe) that is not related to this failure and should not affect this test. But, after patching that, TSAN runs were fine too. I am not sure if this is platform specific.

I am going to focus on why backtraces are not available here. Tracking bug for this is  at https://github.com/flutter/flutter/issues/81584.

**Comment by chinmaygarde** [comment] 2021-05-03 17:38
@dnfield s guidance was that using the `cpulimit` tool to make this problem more apparent. https://github.com/flutter/flutter/issues/81584 has a good hypothesis on understanding why the backtraces are unreliable. Let's try to make progress on both fronts to attack this flake.

**Comment by dnfield** [comment] 2021-05-03 17:46
I've run this locally through a few thousand iterations without failure.

I ran through a few dozen iterations using `cpulimit -l 1` and `cpulimit -l 2` without any luck, although I'm doing it on macOS and the only linked failure I see here was on Linux. Unfortunately, even 1% of my Linux box is still probably faster than CI :\

**Comment by jason-simmons** [comment] 2021-05-03 21:51
Took a look at this, and I have an idea about what is happening.

https://github.com/flutter/engine/blob/master/testing/dart_isolate_runner.cc#L21 creates a lambda that holds a `shared_ptr` to the `DartIsolate` and then posts it to the `AutoIsolateShutdown`'s task runner.

During the call to `RunNowOrPostTask` two copies of the lambda exist - the original lambda that is passed as an argument, and a copy placed in the task runner's queue.  Both of these copies hold a `shared_ptr<DartIsolate>` referencing the `DartIsolate` that was moved out of the `AutoIsolateShutdown`'s `isolate_`.

The task runner's lambda executes on another thread, and it could finish and be deleted before the original lambda's destructor runs.  If that happens, then the original lambda's destructor will drop the last reference to the `DartIsolate`.  So deletion of the `DartIsolate` will happen on the test main thread, which triggers the assertion.

**Comment by zanderso** [comment] 2021-05-03 22:16
@jason-simmons @chinmaygarde Are there any anti-patterns around use of lambdas that we should be documenting or ASSERTing against to avoid problems like this? For example, are there any ASSERTs that could be added to e.g. `RunNowOrPostTask` that would complain when passed a lambda that captures something that it shouldn't?

**Comment by jason-simmons** [comment] 2021-05-03 22:59
I think the main anti-pattern here is the use of shared_ptr with an object that must be deleted on a specific thread.  It's easy to write code that implicitly creates copies of the shared_ptr, and the code needs to be careful to ensure that all other shared_ptr instances have been deleted before the final reference is deleted on the appropriate thread.

I'm not sure how to guard against this at the level of lambda captures or TaskRunner APIs.  One option might be some kind of wrapper that schedules deletion of the object on the designated thread.  We do something like this for Skia objects (see https://github.com/flutter/engine/blob/master/flow/skia_gpu_object.h)

**Comment by dnfield** [comment] 2021-05-03 23:00
Perhaps we should change `CreateRunningRootIsolate from using a `std::weak_ptr`, which claims to be thread safe, to a `fml::WeakPtr`?

**Comment by chinmaygarde** [comment] 2021-05-03 23:35
Jason is right. We shouldn't use the `std::shared_ptr` for objects that must be "used" (destroyed in this case) somehow on a specific thread. In this specific case, we ought to remove [`std::enable_shared_from_this<DartState>`](https://github.com/flutter/engine/blob/33d483b29ef1126ba0f29c6643de41adc36d8351/third_party/tonic/dart_state.h#L28) and switch to using `fml::WeakPtr` with weak pointer factories instead.

> Are there any anti-patterns around use of lambdas that we should be documenting or ASSERTing against to avoid problems like this?

We were actually doing exactly this here. [Asserting in debug only](https://github.com/flutter/engine/blob/33d483b29ef1126ba0f29c6643de41adc36d8351/runtime/dart_isolate.cc#L358) that the thread was correct. We knew that this object had strict threading requirement. That these requirements were being violated in such a subtle and hard to reproduce manner and racy manner was problematic.

IMO, we shouldn't be using std::shared_ptr for objects that need external synchronization or have threading restrictions. I don't this we do this often though.

**Comment by chinmaygarde** [comment] 2021-05-10 17:32
Fixed in https://github.com/flutter/engine/pull/25899.

**Closed by chinmaygarde** 2021-05-10 17:32 UTC
Labels: P2, engine, passed first triage, team: flakes
