### ISSUE TITLE
MaskFilter blur adding an offset

### ISSUE THREAD

**Issue by aaumond** [flutter/flutter#137716] opened 2023-11-01 19:00 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I draw a circle with `CustomPaint`. When I apply a `MaksFilter.blur`, the circle is completely shifted on the horizontal axis, using Flutter version higher than **3.10.6**.

If I downgrade Flutter to version 3.10.6, the trace is not shifted.

I'm guessing this is due to the use of Impeller. Would I be misusing the notion of blur from this version?

### Expected results

The circle should not be horizontally offset.

### Actual results

The circle line is completely shifted horizontally as soon as the blur is present. Without blur, the circle is well positioned.

### Code sample

<details><summary>Code sample</summary>

```dart
    final Paint paint = Paint()
      ..color = darken ? color.darken(20) : color
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 3);

    final Path path = Path()
      ..arcTo(
        Rect.fromCircle(center: center, radius: radius),
        pi,
        pi,
        true,
      )
      ..close();

    canvas.drawPath(path, paint);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

With `MaskFilter.blur` and Flutter v3.13.9:
<img width="398" alt="Capture d’écran 2023-11-01 à 19 44 40" src="https://github.com/flutter/flutter/assets/79145906/4e4376cb-6192-40de-b6be-656c4f0b16bf">

With `MaskFilter.blur` and Flutter v3.10.6:
<img width="395" alt="Capture d’écran 2023-11-01 à 19 47 37" src="https://github.com/flutter/flutter/assets/79145906/2512ed7d-759a-4b5b-b400-f488b4397d1e">

</details>

### Logs

<details><summary>Logs</summary>

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale fr-FR)
    • Flutter version 3.13.9 on channel stable at /Users/anthony.aumond/fvm/versions/3.13.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (7 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/anthony.aumond/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone Anthony (mobile) • 00008030-001119CE1112802E            • ios            • iOS 17.0.3 21A360
    • iPhone 15 (mobile)      • 311DA4D2-973E-45A5-87B7-9C2EDFD6FCFB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2023-11-02 06:36
Thanks for the report @aaumond 
Can you provide us complete runnable reproducible code sample that shows the reported behavior ?
Is the behavior specific to iOS + impeller ?

**Comment by aaumond** [comment] 2023-11-02 09:25
@darshankawar The problem is only with iOS.

Here is a minimal reproductible code sample.

```dart
import 'package:flutter/material.dart';

import 'dart:math';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({
    super.key,
  });

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const BlurDemo(),
    );
  }
}

class BlurDemo extends StatelessWidget {
  const BlurDemo({
    super.key,
  });

  @override
  Widget build(BuildContext context) => Scaffold(
    body: LayoutBuilder(
      builder: (context, constraints) {
        final Offset circleCenter = Offset(
          constraints.biggest.width * 0.5,
          constraints.biggest.width * 0.7,
        );
        final double radius = constraints.biggest.width * 0.7;

        return Stack(
          clipBehavior: Clip.none,
          children: [
            /// ... Other widgets
            ///
            CustomPaint(
              painter: HalfCircleShadowPainter(
                center: circleCenter,
                radius: radius,
              ),
              child: SizedBox(
                width: constraints.biggest.width,
              ),
            ),

            /// ... Other widgets
          ],
        );
      },
    ),
  );
}

class HalfCircleShadowPainter extends CustomPainter {
  const HalfCircleShadowPainter({
    required this.center,
    required this.radius,
  });

  final Offset center;
  final double radius;

  @override
  void paint(Canvas canvas, Size size) {
    final Paint paint = Paint()
      ..color = Colors.orange
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 10);

    final Path path = Path()
      ..moveTo(center.dx, center.dy)
      ..arcTo(
        Rect.fromCircle(center: center, radius: radius),
        pi,
        pi,
        false,
      )
      ..close();

    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}
``` 

Android & Flutter 3.10.6:
![android_3 10 6](https://github.com/flutter/flutter/assets/79145906/67a05f3a-1291-4856-b7b3-35d8a7f0ff0b)

Android & Flutter 3.13.9:
![android_3 13 9](https://github.com/flutter/flutter/assets/79145906/45878bf3-295a-48f8-a6d9-743a82264ec1)

iOS & Flutter 3.10.6:
![ios_3 10 6](https://github.com/flutter/flutter/assets/79145906/1e706b1c-b025-48b6-8d2c-97fc055a139f)

iOS & Flutter 3.13.9:
![ios_3 13 9](https://github.com/flutter/flutter/assets/79145906/e15b1f90-2cc5-4d39-87fa-e0c4150757b4)

**Comment by darshankawar** [comment] 2023-11-03 05:52
Thanks for the update @aaumond 
It seems to be working as expected on master version:

<img width="358" alt="Screenshot 2023-11-03 at 11 20 48 AM" src="https://github.com/flutter/flutter/assets/67046386/10fd38a9-a1f6-4097-9ccf-88e21e61f7ae">

The fix doesn't seem to be in stable yet but should be available in next stable release. Since it works on master, per our triage policy, I'll consider this as fixed and will close this issue. If you disagree, write in comments and I'll reopen it.

`Channel master, 3.16.0-22.0.pre.4`

**Closed by darshankawar** 2023-11-03 05:52 UTC
Labels: in triage
