### ISSUE TITLE
flutter.jar/assets/flutter_shared will not merge into aar's assets path.

### ISSUE THREAD

**Issue by ZhangQinglian** [flutter/flutter#21107] opened 2018-08-28 08:49 UTC
Consult [Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#experiment-turn-the-flutter-project-into-a-module)

I use ./gradlew flutter:assembleDebug to assemble `flutter-debug.aar`  and add it into my project.

`flutter.jar/assets/flutter_shared` was not merged into `flutter-debug.aar` which cause my app crash .

**Comment by dannyreis** [comment] 2018-10-29 18:49
@dnfield Any idea on a timeline to fix this? Seems the issue is that the icudtl.dat is required. 

Currently the solution is to manually add this in .android/Flutter/src/main/assets/flutter_shared/icudtl.dat

**Comment by dnfield** [comment] 2018-10-29 20:24
I'd defer to @matthew-carroll  who's more actively working on the Android embedding side of things.

**Comment by Graydalf** [comment] 2018-10-30 02:37
Please refer to https://github.com/flutter/flutter/issues/18025, hope this helps.

**Comment by sunjianshun** [comment] 2019-01-07 10:05
In my case, when i use: 
```
classpath 'com.android.tools.build:gradle:2.3.2'
```
contains flutter_shared.

The gradle plugin version 3.0.0+, will missing icudtl.dat.

**Comment by tvolkert** [comment] 2019-01-15 18:23
Fixed by https://github.com/flutter/flutter/pull/23782

**Comment by tvolkert** [comment] 2019-01-16 22:08
Re-opening because the change broke `--local-engine` and was reverted.  It's being re-applied in https://github.com/flutter/flutter/pull/26668

**Comment by jmagman** [comment] 2019-08-15 22:32
We have since built the `flutter build aar` command (https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#1-depend-on-the-android-archive-aar) which accomplishes what you seem to want more formally. It should merge assets properly. Please give it a try feel free to open another issue if there are problems with that flow.

**Closed by jmagman** 2019-08-15 22:32 UTC
Labels: a: existing-apps, t: gradle, tool
