### ISSUE TITLE
[web]: Flutter Web has no side scroll bar

### ISSUE THREAD

**Issue by andresribeiro** [flutter/flutter#47671] opened 2019-12-23 12:35 UTC
The web versions do not have the scroll sidebar, regardless of the browser.

**Comment by janmoppel** [comment] 2019-12-23 13:40
Hello @andresribeiro !

Thank you for posting an issue.
Can you please also provide additional information such as an output of the `flutter doctor -v` command and minimal example to reproduce this issue?

Thank you.

**Comment by andresribeiro** [comment] 2019-12-23 13:49
[✓] Flutter (Channel dev, v1.13.2, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.13.2 at /home/andre/Downloads/flutter
    • Framework revision 4944622b5d (11 days ago), 2019-12-12 18:43:58 +0000
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/andre/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/andre/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/andre/Downloads/android-studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by andresribeiro** [comment] 2019-12-23 14:04
[✓] Flutter (Channel dev, v1.13.2, on Linux, locale pt_BR.UTF-8)
• Flutter version 1.13.2 at /home/andre/Downloads/flutter
• Framework revision 4944622 (11 days ago), 2019-12-12 18:43:58 +0000
• Engine revision 12bf95fd49
• Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /home/andre/Android/Sdk
• Android NDK location not configured (optional; useful for native profiling
support)
• Platform android-29, build-tools 29.0.2
• Java binary at: /home/andre/Downloads/android-studio/jre/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_202-release-1483-b49-5587405)
• All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find chrome executable at
google-chrome)
! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 3.5)
• Android Studio at /home/andre/Downloads/android-studio
• Flutter plugin version 42.0.1
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build
1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
• VS Code at /usr/share/code
• Flutter extension version 3.7.1

[✓] Connected device (1 available)
• Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by yjbanov** [comment] 2020-01-03 22:30
This is a duplicate of https://github.com/flutter/flutter/issues/40107

**Closed by yjbanov** 2020-01-03 22:30 UTC
Labels: f: scrolling, framework, ☸ platform-web
