### ISSUE TITLE
[CanvasKit] drawAtlas does not work on web

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#88220] opened 2021-08-14 14:50 UTC
The `Canvas.drawAtlas` function does not seem to work when running on Flutter web.

| Running on macOS (desktop) | Running on Chrome (web) |
| ----------------------------- | -------------------------- |
| <img width="791" alt="Screen Shot 2021-08-14 at 14 45 05" src="https://user-images.githubusercontent.com/19204050/129450094-d0b7d4c3-8cea-4b67-8733-bcfebb859e58.png"> | <img width="791" alt="Screen Shot 2021-08-14 at 14 46 56" src="https://user-images.githubusercontent.com/19204050/129450141-aa21b6ec-febb-49c2-b60b-3af3f3433c6b.png"> |

## Steps to Reproduce

I tried to package the sample into minimal code, without doing any investigation yet.

1. Run `flutter create bug`.
2. Update `main.dart` to the following code:

<details><summary>Click to expand sample code</summary>

```dart
import 'dart:math';
import 'dart:ui';

import 'package:flutter/material.dart' hide Image;
import 'package:flutter/painting.dart';
import 'package:flutter/scheduler.dart';

void main() => runApp(const BugContainer());

/// Code fully inlined from my `funvas` package: https://github.com/creativecreatorormaybenot/funvas/blob/e1af15d80785e564fa020c6ab4f0200f1ae6b0c2/funvas_tweets/lib/src/38.dart#L11.
class BugContainer extends StatefulWidget {
  const BugContainer({Key? key}) : super(key: key);

  @override
  _BugContainerState createState() => _BugContainerState();
}

class _BugContainerState extends State<BugContainer>
    with SingleTickerProviderStateMixin {
  late final ValueNotifier<double> _time;
  late final Ticker _ticker;

  @override
  void initState() {
    super.initState();
    _time = ValueNotifier(0);
    _ticker = createTicker(_update)..start();
  }

  @override
  void dispose() {
    _time.dispose();
    _ticker.dispose();
    super.dispose();
  }

  void _update(Duration elapsed) {
    _time.value = elapsed.inMicroseconds / 1e6;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SizedBox.expand(
          child: CustomPaint(
            willChange: _ticker.isActive,
            painter: Bug(_time),
          ),
        ),
      ),
    );
  }
}

class Bug extends CustomPainter {
  Bug(this.time) : super(repaint: time) {
    final stream = ResizeImage(
      NetworkImage('https://i.imgur.com/skxsba4.png'),
      width: _ps,
      height: _ps,
    ).resolve(const ImageConfiguration());
    late final ImageStreamListener listener;
    listener = ImageStreamListener((info, _) {
      _particle = info.image;
      stream.removeListener(listener);
    });
    stream.addListener(listener);
  }

  static const _d = 750.0, _ps = 42, _n = 4200;

  final ValueNotifier<double> time;
  final _particles = <_Particle>[];

  double get t => time.value;

  Image? _particle;
  double? _pt;
  late double _it;

  @override
  void paint(Canvas canvas, Size size) {
    if (_particle == null) return;

    if (_pt == null || _pt! > t) {
      _it = _pt = t;
      _advance(t, t - _it);
    } else {
      _advance(t - _pt!, t - _it);
      _pt = t;
    }

    canvas.translate((size.width - size.shortestSide) / 2,
        (size.height - size.shortestSide) / 2);
    canvas.scale(size.shortestSide / _d);
    canvas.clipRect(Offset.zero & Size.square(_d));
    canvas.drawColor(const Color(0xff3a3a3a), BlendMode.srcOver);
    canvas.translate(_d / 2, _d / 2);
    canvas.drawAtlas(
      _particle!,
      [
        for (final particle in _particles)
          RSTransform.fromComponents(
            rotation: particle.v.direction + pi / 4,
            scale: particle.scale,
            anchorX: _ps / 2,
            anchorY: _ps / 2,
            translateX: particle.p.dx,
            translateY: particle.p.dy,
          ),
      ],
      List.filled(
        _particles.length,
        const Rect.fromLTWH(0, 0, _ps / 1, _ps / 1),
      ),
      [
        for (final particle in _particles)
          HSLColor.fromAHSL(
            min(
              min(1, max(.75, 169 / _particles.length)),
              particle.p.distanceSquared / (_d * 1e2),
            ),
            particle.hue,
            3 / 4,
            3 / 4,
          ).toColor(),
      ],
      BlendMode.modulate,
      const Rect.fromLTWH(-_d / 2, -_d / 2, _d, _d),
      Paint(),
    );
  }

  void _advance(double dt, double t) {
    if (dt <= 0) return;
    _particles.forEach((element) => element.advance(dt, _d));
    _particles.removeWhere((element) => element.oob(_d, _ps / 1));
    final random = Random();
    double v() => random.nextDouble() * 2 - 1;
    for (var i = 0; i < 64; i++) {
      if (_particles.length >= _n) break;
      _particles.add(_Particle(
        Offset.fromDirection(v() * pi * 4, 5 + v() / 2),
        180 + 180 * v(),
        1.1 + v() * 2,
      ));
    }
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}

class _Particle {
  _Particle(this.v, this.hue, this.scale);

  final Offset v;
  final double hue, scale;
  var p = Offset.zero;

  void advance(double dt, double d) => p += v * dt * d / 9;

  bool oob(double d, double s) =>
      p.dx.abs() - s / 2 * scale > d / 2 || p.dy.abs() - s / 2 * scale > d / 2;
}
```

</details>

3. Run on macOS (desktop) - remember to add `<key>com.apple.security.network.client</key><true/>` to the `DebugProfile.entitlements` for the network image.
4. Run on Chrome (web).

**Expected results:** same on both platforms

**Actual results:** only works on native.

<details><summary>Click to expand flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-7.0.pre.80, on macOS 11.5 20G71 darwin-x64,
    locale en-US)
    • Flutter version 2.5.0-7.0.pre.80 at /Users/user/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1422bfa723 (7 hours ago), 2021-08-14 04:02:06 -0400
    • Engine revision a447901bc5
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)


[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5 20G71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.13
```

</details>

**Comment by darshankawar** [comment] 2021-08-16 10:04
@creativecreatorormaybenot 
It could be becuase `Canvas.drawAtlas` isn't supported on web yet. See [this](https://github.com/flutter/flutter/issues/32217) open feature request for same.
I am going ahead and closing this in favor of the original. 
Thanks.

**Comment by creativecreatorormaybenot** [comment] 2021-08-16 14:16
@darshankawar No, I do not think so. @yjbanov told me it should be supported in CanvasKit. He told me I should open a bug about it. I will adjust it to mention that it is about CanvasKit - it is not in the steps to reproduce as CanvasKit is now the default backend for web.

**Comment by darshankawar** [comment] 2021-08-17 06:14
@creativecreatorormaybenot 
Thanks for clarifying. Reopening.

**Comment by darshankawar** [comment] 2021-08-17 06:15
Verified this on latest master and stable using both renderers and below is the result:

1. Canvaskit:

<img width="944" alt="Screenshot 2021-08-17 at 11 37 34 AM" src="https://user-images.githubusercontent.com/67046386/129673348-8d66a51c-5726-40b7-a0ec-721e8212796d.png">


2. Html:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during paint():
UnimplementedError
```


<details>
<summary> stable and masterflutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!

[✓] Flutter (Channel master, 2.5.0-7.0.pre.104, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.104 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 060e4608b1 (2 hours ago), 2021-08-16 21:37:03 -0700
    • Engine revision 7dc8eba6ae
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114






```

</details>

**Comment by bdero** [comment] 2021-08-24 02:28
I recall running into this limitation on a personal project not too long ago. Here's a reduced javascript case with `CanvasKit.drawAtlas` not drawing a 2x2 square:

```typescript
const surface = CanvasKit.MakeCanvasSurface(canvas.id);
const skcanvas = surface.getCanvas();
const paint = new CanvasKit.Paint();
const image = CanvasKit.MakeImage(
  {
    width: 2, height: 2,
    alphaType: CanvasKit.AlphaType.Opaque,
    colorType: CanvasKit.ColorType.RGBA_8888,
    colorSpace: CanvasKit.ColorSpace.SRGB,
  },
  new Uint8Array([0, 0, 0xff, 0xff, 0, 0, 0xff, 0xff, 0, 0, 0xff, 0xff, 0, 0, 0xff, 0xff]),
  8,
);
skcanvas.drawAtlas(
  image,
  [0, 0, 2, 2],
  [0, 0, 10, 10],
  paint
);
surface.flush();
```

**Comment by hterkelsen** [comment] 2022-10-25 23:00
I believe this is caused by https://github.com/flutter/flutter/issues/34075.

@bdero your example would work but your transform scales the image to `0` so nothing is rendered. This example works:

```
const surface = CanvasKit.MakeCanvasSurface(canvas.id);
const skcanvas = surface.getCanvas();
const paint = new CanvasKit.Paint();
const image = CanvasKit.MakeImage(
  {
    width: 2, height: 2,
    alphaType: CanvasKit.AlphaType.Opaque,
    colorType: CanvasKit.ColorType.RGBA_8888,
    colorSpace: CanvasKit.ColorSpace.SRGB,
  },
  new Uint8Array([0, 0, 0xff, 0xff, 0, 0, 0xff, 0xff, 0, 0, 0xff, 0xff, 0, 0, 0xff, 0xff]),
  8,
);
skcanvas.drawAtlas(
  image,
  [0, 0, 2, 2],
  [10, 0, 10, 10],
  paint
);
surface.flush();
```

**Comment by alanwutang11** [comment] 2022-12-21 21:21
This should now be fixed with: 

Framework side PR:
https://github.com/flutter/flutter/pull/117423

**Closed** 2022-12-21 21:22 UTC
Labels: engine, platform-web, severe: rendering, e: web_canvaskit, has reproducible steps, P3, found in release: 2.2, found in release: 2.5, customer: chilli
