### ISSUE TITLE
Failed to recognize a platform plugin after Flutter 3.27

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#160143] opened 2024-12-12 07:36 UTC
> This crashes users without notice or awareness, please consider this a severe regression.

### Workaround

Adding the plugin to `app/pubspec.yaml` can solve the issue.

#### See https://github.com/AlexV525/flutter_issue_160143 for a reproducible example

1. `flutter create app`
2. `flutter create --template=package foundation`
3. Under the `foundation`, run `flutter pub add fvp`
4. Under the `app`, run `flutter pub add 'foundation:{"path":"../foundation"}'
5. Run `flutter pub get` for `app`
6. No `com.mediadevkit.fvp` was generated in the `android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java`.
7. Import `package:fvp/fvp.dart` and add `registerWith()` before `runApp`.
8. Run the app on Android and see exceptions occurred.

### Expected results

The plugin registrant should be generated no matter the plugin was declared at once it's been referenced.

### Actual results

The plugin was unrecognized through the above setup.

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

<details><summary>No editing with 3.27</summary>

```console
[  +15 ms] Connecting to service protocol: http://127.0.0.1:65508/G1CaQpu8g9k=/
[+1195 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:65508/G1CaQpu8g9k=/.
[ +130 ms] E/flutter (28118): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Invalid
argument(s): Failed to load dynamic library 'libfvp_plugin.so': dlopen failed: library "libfvp_plugin.so" not found
[        ] E/flutter (28118): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
[        ] E/flutter (28118): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
[        ] E/flutter (28118): #2      Libfvp._load (package:fvp/src/lib.dart:52:29)
[        ] E/flutter (28118): #3      Libfvp.instance (package:fvp/src/lib.dart:58:27)
[        ] E/flutter (28118): #4      Libfvp.instance (package:fvp/src/lib.dart)
[        ] E/flutter (28118): #5      Libfvp.isEmulator (package:fvp/src/lib.dart:83:29)
[        ] E/flutter (28118): #6      Libfvp.isEmulator (package:fvp/src/lib.dart)
[        ] E/flutter (28118): #7      PlatformEx.isAndroidEmulator (package:fvp/src/extensions.dart:17:19)
[        ] E/flutter (28118): #8      MdkVideoPlayerPlatform.registerVideoPlayerPlatformsWith
(package:fvp/src/video_player_mdk.dart:150:42)
[        ] E/flutter (28118): #9      registerWith (package:fvp/fvp.dart:47:26)
[        ] E/flutter (28118): #10     main (package:app/main.dart:6:14)
[        ] E/flutter (28118): #11     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
[        ] E/flutter (28118): #12     _delayEntrypointInvocation.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:297:19)
[        ] E/flutter (28118): #13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[        ] E/flutter (28118):
[ +417 ms] Successfully connected to service protocol: http://127.0.0.1:65508/G1CaQpu8g9k=/
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.22631.4602], locale en-US)
    • Flutter version 3.27.0 on channel stable at X:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (33 hours ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at X:\Android\SDK
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = X:\Android\SDK
    • ANDROID_SDK_ROOT = X:\Android\SDK
    • Java binary at: X:\IDEs\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Android Studio (version 2024.2)
    • Android Studio at X:\IDEs\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
```

</details>

**Comment by darshankawar** [comment] 2024-12-12 10:14
Thanks for the report @AlexV525 
I tried to follow the steps provided but at step 4, I am hitting below error:

```
Using a naked argument for directory is deprecated and will stop working in a
  future Flutter release.

  Use --directory instead.
Expected to find project root in foundation:{"path":"../foundation"}.
```

Which is same as https://github.com/flutter/flutter/issues/144898

Is there a way for you to provide us a repo that we can directly clone to verify this further ?

**Comment by AlexV525** [comment] 2024-12-12 10:16
> Is there a way for you to provide us a repo that we can directly clone to verify this further ?

Yes as mentioned above: https://github.com/AlexV525/flutter_issue_160143

**Comment by darshankawar** [comment] 2024-12-12 10:39
Thanks for it. I somehow missed it from OP. 
Using the repo, I was able to replicate on latest sdk versions (stable and master).
Based on the report and error received with it, I will keep the issue open for team's tracking.
I wasn't able to verify this on previous stable though due to version conflict, as the message said to upgrade to latest stable.

```
stable : 3.27.0
master : 3.28.0-1.0.pre.87
```

**Comment by AlexV525** [comment] 2024-12-12 10:50
@darshankawar Could you do another round of checks? I've updated the example to enable it with Flutter 3.24.

**Comment by darshankawar** [comment] 2024-12-12 11:14
Thanks, I verified on stable 3.24.4 wherein the app builds properly without throwing the reported error.

**Comment by reidbaker** [comment] 2024-12-12 15:39
Next step is to bisect to find the problem commit/pr.

**Comment by jason-simmons** [comment] 2024-12-12 17:23
This started with https://github.com/flutter/flutter/commit/d55a5f96c117725c134099b78deb7af431a93902

**Comment by jason-simmons** [comment] 2024-12-12 20:40
The example app involves the `fvp` plugin.  This plugin's `pubspec.yaml` delcares  `implements: video_player` and also lists a dependency on `video_player`.
(see https://github.com/wang-bin/fvp/blob/master/pubspec.yaml)

The logic in `_resolvePluginImplementationsByPlatform` selects a single plugin that implements a particular plugin name for a given platform.  In this case, it is selecting `video_player_android` as the implementation of `video_player`.

The `fvp` plugin is therefore not included in the build.  The app then fails during launch when it can not find the native libraries from `fvp`.

Prior to https://github.com/flutter/flutter/commit/d55a5f96c117725c134099b78deb7af431a93902 both the `fvp` and `video_player` plugins would be included when building this app.

**Comment by jason-simmons** [comment] 2024-12-12 20:55
As noted in https://github.com/flutter/flutter/issues/160143#issue-2735097155 this app works if `fvp` is added as a dependency in `app/pubspec.yaml`.

That works because `_resolveImplementationOfPlugin` has special handling that overrides the selected implementation of a given plugin name if a direct dependency is present.

@camsim99 @stuartmorgan Is this the intended behavior?

**Comment by camsim99** [comment] 2024-12-12 21:04
Reading through the "Platform Implementation Selection" part of the [design doc](https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edit?tab=t.0#heading=h.rky4syx8vrqs) that https://github.com/flutter/flutter/pull/137040 is based on, I would expect the `foundation` plugin to behave the same as the following case of a Flutter app choosing a platform implementation for a plugin it depends on:

> If there is a single direct dependency on a package that implements the frontend plugin for the target platform, this package is the selected implementation.

In this case, `foundation` depends directly on `fvp` that implements `video_player`, so I would expect `fvp` for sure to be chosen and included in the build. I suppose `video_player` too because it's not listed as a dev dependncy, but less sure there.

@stuartmorgan what do you think?

**Comment by stuartmorgan** [comment] 2024-12-12 21:33
> As noted in [#160143 (comment)](https://github.com/flutter/flutter/issues/160143#issue-2735097155) this app works if `fvp` is added as a dependency in `app/pubspec.yaml`.
> 
> That works because `_resolveImplementationOfPlugin` has special handling that overrides the selected implementation of a given plugin name if a direct dependency is present.
> 
> @camsim99 @stuartmorgan Is this the intended behavior?

Yes, that's the intended behavior, as spec'd in the original design doc for federated plugins. It appears from the `fvp` README and a look at the registration code it references that the plugin was designed around the (incorrect) previous behavior that we were always including all the native code for *every* transitive implementation, which was undesirable.

The intended way for application developers to select overrides is, per the design doc, to directly depend on the overriding plugin it their pubspec.yaml.

> In this case, `foundation` depends directly on `fvp` that implements `video_player`, so I would expect `fvp` for sure to be chosen and included in the build.

That section is describing *application* builds; a direct dependency of an application build is something listed in the application's `pubspec.yaml`. In this case, all implementations of `video_player` are transitive dependencies of the app, none are direct dependencies, so it falls under case 3.

The structure of that plugin is very odd; I've never seen a plugin that both `implements` foo and also *depends* on `foo`. That's not a configuration that we intended to have any meaning.

Closing as this is the intended behavior, and the change is as desired (even if not in this particular case), since having multiple native implementations in the shipped app when only one was used was a bug (a bug this plugin was relying on). I'll follow up in the plugin issue.

**Closed by stuartmorgan** 2024-12-12 21:34 UTC
Labels: c: regression, platform-android, tool, has reproducible steps, P1, a: plugins, team-android, found in release: 3.27, found in release: 3.28

**Comment by AlexV525** [comment] 2024-12-13 01:56
@stuartmorgan Thanks for the clarification.

> In this case, `foundation` depends directly on `fvp` that implements `video_player`, so I would expect `fvp` for sure to be chosen and included in the build.

Yes, that is what I was expecting too.

> The intended way for application developers to select overrides is, per the design doc, to directly depend on the overriding plugin it their pubspec.yaml.

Given the first intuition that people might have, do we accept improvements around dependency overwrites by depth?
Consider the current structure of dependencies:
There is a case in which people will use a base package to export dependencies as a single point so they might set up a similar structure to the issue.
Consider the current structure of dependencies (> means directly depend on, < means endorsed):
```
app
  --> foundation
    --> video_player
      --< video_player_android
    --> fvp
```
In this case, `fvp` is explicitly declared as a dependency at the same level as the base (`video_player`), which means depending on `foundation` is confirmed to accept the `fvp` as a platform implementation. (At least that's what I was expecting.)

### More context

The reason I've noticed the plugin has not been picked is we used to write a worse declaration in the foundation and it worked:
```yaml
dependencies:
  video_player:
  video_player_android:
  fvp:
```

After Flutter 3.27, deps are not able to resolve when we run `flutter pub get` and this is an expected behavior:
```console
Resolving dependencies...
Downloading packages...
......
Got dependencies!
Plugin video_player:android has conflicting direct dependency implementations:
  fvp
  video_player_android
To fix this issue, remove all but one of these dependencies from pubspec.yaml.
```

But even in this circumstance, `app` can still resolve deps:
```console
Resolving dependencies...
Downloading packages...
......
Got dependencies!
```

And the `pubspec.lock` still tells that the `fvp` is a direct dependency:
```yaml
fvp:
  dependency: "direct main"
```

So I wouldn't expect to ignore the implementation here.

**Comment by AlexV525** [comment] 2024-12-13 02:58
> That is (as I would expect) not what [your repro case lists](https://github.com/AlexV525/flutter_issue_160143/blob/5af519b0d27473d3ebcceeca2f15feecc01de268/app/pubspec.lock#L62). `app`->`foundation`->`fvp` is, by definition, a transitive dependency between `app` and `fvp`.

You are correct, I've overlooked that I was looking our production project that applies the new patch (declared the dependency directly in the pubspec).

> If a sibling package to `foundation` directly depends on a _different_ override, which is "confirmed"? What if the sibling package directly depends on `video_player` but no override? What if the app directly depends on `video_player` with no override, but a transitive dependency depends with an override? What if the app has an override that conflicts with a package override? A resolution system needs some answer to every possible case.如果`foundation`的同级包直接依赖于_不同的_覆盖，这是否是“确认”？如果同级包直接依赖于`video_player`但没有覆盖怎么办？如果应用程序直接依赖于`video_player`而没有覆盖，但传递依赖依赖于覆盖，该怎么办？如果应用程序的覆盖与包覆盖冲突怎么办？解决系统需要对每种可能的情况给出一些答案。

These are good points and I'll consider them if I'm going to investigate more about the implementation improvement.
