### ISSUE TITLE
IconButton's ripple is out of bounds in Card

### ISSUE THREAD

**Issue by xVemu** [flutter/flutter#109027] opened 2022-08-05 08:30 UTC
When IconButton is placed inside Card, it doesn't respect Card's borderRadius. On the picture below, you can see that ripple of icon button is not rounded and stands out of Card.

![image](https://user-images.githubusercontent.com/38427679/183032044-241bc386-46b3-4fd3-8e6b-38cbbe41816c.png)

<details>
  <summary>Code sample</summary>

  ```dart
Card(
      child: SizedBox(
        height: 70,
        width: 180,
        child: IconButton(
          splashRadius: 100,
          onPressed: () {},
          icon: Icon(Icons.check_outlined),
        ),
      ),
    )
```
</details>

<details>
  <summary>Flutter doctor</summary>

  ```
  [✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale pl-PL)
    • Flutter version 3.0.5 at C:\Users\kkras\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\kkras\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile)       • emulator-5554 • android-arm    • Android null (API null)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-arm    • Android null (API null)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 103.0.1264.49
    ! Device emulator-5554 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
  ```
</details>

**Comment by adilwahla** [comment] 2022-08-05 09:23
@xVemu Hey dont't just put radius in IconButton(), put this in  property of Card(borderRadius: BorderRadius.circular(),),

`
Card(
  shape: RoundedRectangleBorder(
    borderRadius: BorderRadius.circular(15.0),
  ),
  child: Text(
    'Card with circular border',
    textScaleFactor: 1.2,
  ),
),

This way ...!
`

**Comment by adilwahla** [comment] 2022-08-05 09:31
@xVemu Feel free to reach me out if still got stuck I would be happy to help you out dude:)

**Comment by exaby73** [comment] 2022-08-05 10:27
Hello @xVemu. You can wrap the `IconButton` in a `ClipRRect` to fix this. This is working as intended. Therefore, I am closing this issue. If you have any further issues, try Stackoverflow or you can find other communities on https://flutter.dev/community. Thank you

**Closed by exaby73** 2022-08-05 10:27 UTC
Labels: in triage

**Comment by xVemu** [comment] 2022-08-05 10:46
@exaby73 doing this produces the same result.

```
Card(
      child: SizedBox(
        height: 70,
        width: 180,
        child: ClipRRect(
          borderRadius: BorderRadius.circular(12),
          child: IconButton(
            splashRadius: 100,
            onPressed: () {},
            icon: Icon(Icons.check_outlined),
          ),
        ),
      ),
    )
```

**Comment by exaby73** [comment] 2022-08-05 11:50
If you wrap the `IconButton` in a `Material`, it would work.

```dart
Card(
  child: SizedBox(
    height: 70,
    width: 180,
    child: ClipRRect(
      borderRadius: BorderRadius.circular(12),
      child: Material(
        child: IconButton(
          splashRadius: 100,
          onPressed: () {},
          icon: const Icon(Icons.check_outlined),
        ),
      ),
    ),
  ),
)
```

**Comment by xVemu** [comment] 2022-08-05 11:54
Yep, it's working now. Thank you!
