### ISSUE TITLE
Unable to override floatingActionButtonAnimator

### ISSUE THREAD

**Issue by NBTX** [flutter/flutter#25123] opened 2018-12-08 21:58 UTC
## Steps to Reproduce

1. Create a MaterialApp and Scaffold
2. Try to apply a `floatingActionButtonAnimation`
3. The results are ignored.

## Logs

```bash
[        ] Connected to _flutterView/0x7336838c18.
[   +3 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on Pixel 2 is available at: http://127.0.0.1:49684/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
```

No analysis errors.

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 1.0.0 at /Users/NBTX/development/flutter
    • Framework revision 5391447fae (9 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/NBTX/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[✓] Connected device (1 available)
    • ...

• No issues found!
```

**Comment by zoechi** [comment] 2018-12-09 14:15
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by NBTX** [comment] 2018-12-15 20:56
Here's an example `main.dart` - I've cut out the irrelevant bits.

```dart
import 'dart:math' as math;

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Issue #25123',
      home: FlutterDemo(),
    );
  }
}

class FlutterDemo extends StatefulWidget {
  FlutterDemo({Key key}) : super(key: key);

  @override
  FlutterDemoState createState() => FlutterDemoState();
}

class FlutterDemoState extends State<FlutterDemo> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Flutter Issue #25123"),
      ),
      body: Center(
            Text("Hello world.")
      ),
      floatingActionButton: FloatingActionButton(
        onPressed:(){
          print("FAB pressed.");
        },
        tooltip: 'Add',
        child: const Icon(Icons.add),
      ),
      floatingActionButtonAnimator: AnimationToolkit.floatingButtonAnimator()
    );
  }
}

// AnimationToolkit.dart
class AnimationToolkit {
    // ...
    static const FloatingActionButtonAnimator floatingButtonAnimator = _FloatingButtonAnimator();
}

class _FloatingButtonAnimator extends FloatingActionButtonAnimator {
    const _FloatingButtonAnimator();

  @override
  Offset getOffset({Offset begin, Offset end, double progress}) {
    if (progress < 0.5) {
      return begin;
    } else {
      return end;
    }
  }

  // If the animation was just starting, we'll continue from where we left off.
  // If the animation was finishing, we'll treat it as if we were starting at that point in reverse.
  // This avoids a size jump during the animation.
  @override
  double getAnimationRestart(double previousValue) => math.min(1.0 - previousValue, previousValue);

  @override
  Animation<double> getScaleAnimation({Animation<double> parent}) {
    return Tween<double>(begin: 1.0, end: 1.0).animate(parent);
  }

  @override
  Animation<double> getRotationAnimation({Animation<double> parent}) {
    return Tween<double>(begin: 1.0, end: 1.0).animate(parent);
  }
}
```

In this specific example, my aim was to have the FAB scale but not rotate as it's a full-width rectangular block and it just looks really weird when the whole thing spins.

**Comment by johnsonmh** [comment] 2019-04-18 03:59
Hi there! I think what might be the problem you're encountering is that your `getScaleAnimation` override **begins** and ends at `1.0`. By changing that to `begin: 0, end: 1.0`, I was able to get the animation I believe you're describing:

![giphy](https://user-images.githubusercontent.com/4229329/56335965-878c6c80-616c-11e9-9562-2ca37cadd6ef.gif)

I also just had to override `getOffset`.

Full working code snippet:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Issue #25123',
      home: FlutterDemo(),
    );
  }
}

class FlutterDemo extends StatefulWidget {
  FlutterDemo({Key key}) : super(key: key);

  @override
  FlutterDemoState createState() => FlutterDemoState();
}

class FlutterDemoState extends State<FlutterDemo> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text("Flutter Issue #25123"),
        ),
        body: Center(
            child: Text("Hello world.")
        ),
        floatingActionButton: FloatingActionButton(
          onPressed:(){
            print("FAB pressed.");
          },
          tooltip: 'Add',
          child: const Icon(Icons.add),
        ),
        floatingActionButtonAnimator: AnimationToolkit.floatingButtonAnimator
    );
  }
}

// AnimationToolkit.dart
class AnimationToolkit {
  // ...
  static const FloatingActionButtonAnimator floatingButtonAnimator = _FloatingButtonAnimator();
}

class _FloatingButtonAnimator extends FloatingActionButtonAnimator {
  const _FloatingButtonAnimator();

  @override
  Animation<double> getScaleAnimation({Animation<double> parent}) {
    return Tween<double>(begin: 1.0, end: 1.0).animate(parent);
  }

  @override
  Animation<double> getRotationAnimation({Animation<double> parent}) {
    return Tween<double>(begin: 0, end: 1.0).animate(parent);
  }

  @override
  Offset getOffset({Offset begin, Offset end, double progress}) {
    return end;
  }
}
```

I'm closing this issue, but feel free to follow up/reopen if you aren't able to get it working.

**Closed by johnsonmh** 2019-04-18 03:59 UTC
Labels: f: material design, framework, severe: new feature

**Comment by cohortor** [comment] 2019-08-26 11:19
I would kindly like to revisit and reopen this issue. IMHO the problem is in `scaffold.dart` -> `_FloatingActionButtonTransitionState` -> `_updateAnimations()`.

In particular, `_entranceTurnTween` is always applied, rotating the FAB by `kFloatingActionButtonTurnInterval` (currently 0.125, i.e. 45 degrees). Changing this value to 0.0 stops FAB rotation.

DISCUSSION:

The previously suggested "solution":
```
  @override
  Animation<double> getRotationAnimation({Animation<double> parent}) {
    return Tween<double>(begin: 0.0, end: 1.0).animate(parent);
  }
```
1. contradicts the API DOCs of `FloatingActionButtonAnimator.getRotationAnimation()`, suggesting that the animation should both start and end with a value of 0.0 or 1.0,
2. should actually result in a rotation animation that rotates the FAB through a full circle.
3. in my case (FAB placed horizontally centered) results in a 45deg FAB rotation the first time the FAB is shown, followed by no rotation during subsequent hides/shows.

The final value of the rotation is determined by the FAB's current and previous locations, the animation controller's state, and also the final `TrainHopping` animation, which right now is responsible for chaining the previously mentioned `_entranceTurnTween`'s hardcoded values.

PROPOSED SOLUTION:

Fix/remove the application of `_entranceTurnTween` on the FAB.

**Comment by NBTX** [comment] 2019-08-26 11:34
I *knew* something was up! (We actually ended up just getting rid of the FAB because it didn't fit the design anyway.)

**Comment by cohortor** [comment] 2020-02-16 16:47
@NBTX or @johnsonmh could you please reopen this issue as per my last comment above?
Thank you...

**Comment by NBTX** [comment] 2020-02-18 14:19
@cohortor I'm unable to re-open the issue.
