### ISSUE TITLE
Showing Admob Ads only in selected pages

### ISSUE THREAD

**Issue by Purus** [flutter/flutter#25773] opened 2018-12-26 11:18 UTC
When following the exact steps as mentioned in the documentation, the ads(banner) are showing in all pages even though I initialize and display in one particular page. 

There is no way to decide the pages that I want to display the add. 

There is also an SO question which is open for long with a solution.

https://stackoverflow.com/questions/50972863/admob-banner-how-to-show-only-on-home

**Comment by mulderpf** [comment] 2018-12-27 09:34
I've worked around this by disposing and reloading the ad when the user navigates to and from a page which shouldn't display ads.  It seems to be holding up in production at the moment, but it is a bit flaky having to reinitialise everything all the time.  It would be better just being able to hide and show the ad, rather than disposing and reloading the whole thing all the time.

**Comment by zoechi** [comment] 2018-12-27 09:50
Duplicate of #17452

**Closed by zoechi** 2018-12-27 09:50 UTC

**Comment by Purus** [comment] 2018-12-27 10:41
This is not duplicate. The mentioned issue is about ad position. Not this
one. Please reevaluate.

Thanks,

Purusothaman Ramanujam

**Comment by zoechi** [comment] 2018-12-27 10:52
I'm pretty sure it's the same root cause.
The admob plugin uses native view which has some limitations about positioning. 
It needs to be reimplemented using the new PlatformView feature.
The mentioned community plugin https://github.com/YoussefKababe/admob_flutter probably does that (haven't checked)

**Comment by Purus** [comment] 2018-12-27 10:58
Ok. Can we keep this open for tracking as this is on more test that need to
be done for the root cause?

Thanks,

Purusothaman Ramanujam

**Comment by zoechi** [comment] 2018-12-27 11:13
The plugin will work quite differently and it would be better to create issues that still happen after the plugin was updated.

**Comment by Purus** [comment] 2018-12-27 11:16
Thank you. It makes sense.

Thanks,

Purusothaman Ramanujam

On Dec 27, 2018 4:43 PM, "Günter Zöchbauer" <notifications@github.com>
wrote:

The plugin will work quite differently and it would be better to create
issues that still happen after the plugin was updated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/flutter/flutter/issues/25773#issuecomment-450131497>,
or mute the thread
