### ISSUE TITLE
Stuck keys on MacOS when CMD+Tabbing

### ISSUE THREAD

**Issue by luigi-rosso** [flutter/flutter#59293] opened 2020-06-12 00:47 UTC
Pressing a combination of keys and then cmd + tabbing to another window causes the MacOS Flutter app to retain certain keys as pressed when returning focus to the Flutter MacOS window.

For example, press **F**+CMD+Tab. The app will show that it thinks **F** and CMD (meta) is pressed. MacOS will have focused another window. Return to the Flutter window and you'll note that **F** and Meta are still pressed. Press any key except for **F** and you'll see that Meta autocorrect and removes itself from the list.

However, the **F** key will remain pressed until it is pressed again.

Using an example app which shows the pressed keys: https://github.com/luigi-rosso/flutter_mac_keys_bug

Fundamentally, any non-meta key that was pressed prior to switching focused window will remain in ```RawKeyboard.instance.keysPressed``` until it is pressed again.

Currently on dev, but we've seen it on other branches too.

Doctor's visit:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)

• No issues found!
```

**Comment by stuartmorgan** [comment] 2020-06-12 03:50
Closing as a duplicate of https://github.com/flutter/flutter/issues/50553 since the underlying issue is stuck keys.

**Closed** 2020-06-12 05:04 UTC
