### ISSUE TITLE
Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by BanMugen** [flutter/flutter#57300] opened 2020-05-15 09:27 UTC
Just started using flutter, but failed miserably. Followed the exact instructions given at flutter's website.
Here are some of the snaps........I have tried using both emulator and my own android device, but nothing seems to work.
![flutter_error](https://user-images.githubusercontent.com/33145181/82034421-c700f180-96bb-11ea-9a46-d27b97c96132.jpg)

Please help me...

**Comment by BanMugen** [comment] 2020-05-15 10:37
And here are the snaps of doctor and --android-licenses
![console](https://user-images.githubusercontent.com/33145181/82041581-03d1e600-96c6-11ea-984d-a6c06410802a.jpg)
![doc](https://user-images.githubusercontent.com/33145181/82041625-18ae7980-96c6-11ea-93d7-61d0b4e47b96.jpg)

**Comment by iapicca** [comment] 2020-05-15 10:57
Hi @BanMugen 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose` 

Please refrain from posting pictures if not necessary.
Thank you

**Comment by BanMugen** [comment] 2020-05-15 11:18
```
C:\Users\VIVEK BANZADE>flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-IN)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (2 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\VIVEK BANZADE\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\VIVEK BANZADE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by BanMugen** [comment] 2020-05-15 11:22
C:\code\hello_world>flutter run --verbose
```

[  +14 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[        ] executing: [C:\src\flutter/] git tag --contains HEAD
[ +205 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.1
[   +6 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +32 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +86 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[  +43 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] executing: C:\Users\VIVEK BANZADE\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +44 ms] List of devices attached
           ZF62223VJD             device product:ali model:moto_g_6_ device:ali transport_id:1
[   +8 ms] C:\Users\VIVEK BANZADE\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZF62223VJD shell getprop
[ +150 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +192 ms] Generating C:\code\hello_world\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +24 ms] ro.hardware = qcom
[  +44 ms] Launching lib\main.dart on moto g 6 in debug mode...
[   +7 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\WINDOWS\TEMP\flutter_tool.3b633f86-969e-11ea-bb5f-54bf642903b4\app.dill --packages C:\code\hello_world\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build\cache.dill
[  +20 ms] executing: C:\Users\VIVEK BANZADE\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZF62223VJD shell -x logcat -v time -t 1
[  +85 ms] Exit code 0 from: C:\Users\VIVEK BANZADE\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZF62223VJD shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           05-15 16:51:35.166 D/libc    ( 2700): dns request timeout: netid(101), id(0xd9fd), server(49.45.0.1)
[  +12 ms] <- compile package:hello_world/main.dart
[   +7 ms] executing: C:\Users\VIVEK BANZADE\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +42 ms] Android Debug Bridge version 1.0.41
           Version 30.0.1-6435776
           Installed as C:\Users\VIVEK BANZADE\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +8 ms] executing: C:\Users\VIVEK BANZADE\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +47 ms] Building APK
[  +23 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] gradle.properties already sets `android.enableR8`
[  +12 ms] Using gradle from C:\code\hello_world\android\gradlew.bat.
[   +7 ms] C:\code\hello_world\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +18 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +111 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +4 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[  +10 ms] executing: [C:\code\hello_world\android/] C:\code\hello_world\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm -Ptarget=C:\code\hello_world\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +294 ms] Unzipping C:\Users\VIVEK BANZADE\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip to C:\Users\VIVEK
BANZADE\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb
[  +11 ms] Exception in thread "main" java.util.zip.ZipException: error in opening zip file
[   +4 ms]      at java.util.zip.ZipFile.open(Native Method)
[   +1 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[   +3 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[   +2 ms]      at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[   +5 ms]      at org.gradle.wrapper.Install.unzip(Install.java:214)
[   +4 ms]      at org.gradle.wrapper.Install.access$600(Install.java:27)
[   +1 ms]      at org.gradle.wrapper.Install$1.call(Install.java:74)
[   +2 ms]      at org.gradle.wrapper.Install$1.call(Install.java:48)
[   +5 ms]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[   +1 ms]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[   +5 ms]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[   +2 ms]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[  +23 ms] Running Gradle task 'assembleDebug'... (completed in 0.5s)
[  +10 ms] [!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
[   +4 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from C:\code\hello_world\android\gradlew.bat.
[   +1 ms] C:\code\hello_world\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +1 ms] executing: [C:\code\hello_world\android/] C:\code\hello_world\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm -Ptarget=C:\code\hello_world\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +186 ms] Unzipping C:\Users\VIVEK BANZADE\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip to C:\Users\VIVEK
BANZADE\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb
[   +4 ms] Exception in thread "main" java.util.zip.ZipException: error in opening zip file
[   +5 ms]      at java.util.zip.ZipFile.open(Native Method)
[        ]      at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[        ]      at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[        ]      at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[        ]      at org.gradle.wrapper.Install.unzip(Install.java:214)
[        ]      at org.gradle.wrapper.Install.access$600(Install.java:27)
[   +1 ms]      at org.gradle.wrapper.Install$1.call(Install.java:74)
[   +7 ms]      at org.gradle.wrapper.Install$1.call(Install.java:48)
[   +3 ms]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[   +2 ms]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[   +1 ms]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[   +1 ms]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[  +37 ms] Running Gradle task 'assembleDebug'... (completed in 0.3s)
[   +3 ms] [!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
[+4083 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 5,811ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by iapicca** [comment] 2020-05-15 13:28
Hi @BanMugen 
```bash
[   +3 ms] [!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
[+4083 ms] Exception: Gradle task assembleDebug failed with exit code 1
```
I see there's an open [issue](https://github.com/flutter/flutter/issues/56552) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-05-15 13:28 UTC
Labels: in triage

**Comment by BanMugen** [comment] 2020-05-15 15:08
So, is there any problem with my android licenses as shown by flutter doctor...
Can you help me to rectify that at the least.
And @iapicca I can see my problem to be similar with that of https://github.com/flutter/flutter/issues/56552
but 56552 doesn't have any problems with its android sdks....
Can you help me with that ?

**Comment by iapicca** [comment] 2020-05-20 11:51
Hi @banzade for the issue with android_licenses
please follow up [here](https://github.com/flutter/flutter/issues/51712)
Thank you

**Comment by banzade** [comment] 2020-05-20 12:19
Thanks.
Anyway the problem is already solved by a fresh installation of all the tool kits.
I shouldn't have faced the problem in the first place as my current flutter version is 1.17.1.
