### ISSUE TITLE
sample app for autofill doesn't work on pixel 5a live daily driver device.

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#97684] opened 2022-02-03 00:41 UTC
Steps to reproduce
1. flutter create --sample=widgets.AutofillGroup.1 mysample
2. open and try all the fields
Note: Android sample project _is_ working so it's probably not user error.
Checked my autofill settings. logcat

[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale en-US)

Further notes
On successful android i get stuff like this
`2022-02-02 18:38:29.886 14582-14582/com.example.android.autofill.app V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:38:30.013 14582-14582/com.example.android.autofill.app V/AutofillManager: updateSessionLocked(): id=1073741824, bounds=null, value=[type=1, value=52_chars], action=2, flags=0
2022-02-02 18:38:31.468 14582-14582/com.example.android.autofill.app V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:38:33.902 14582-14582/com.example.android.autofill.app V/AutofillManager: updateSessionLocked(): id=1073741824, bounds=null, value=[type=1, value=53_chars], action=4, flags=0
2022-02-02 18:38:35.923 14582-14582/com.example.android.autofill.app V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:38:35.990 14582-14582/com.example.android.autofill.app V/AutofillManager: updateSessionLocked(): id=1073741824, bounds=null, value=[type=1, value=53_chars], action=2, flags=0
2022-02-02 18:38:37.237 14582-14582/com.example.android.autofill.app V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:38:39.392 14582-14582/com.example.android.autofill.app V/AutofillManager: updateSessionLocked(): id=1073741824, bounds=null, value=[type=1, value=0_chars], action=4, flags=0
2022-02-02 18:38:39.401 14582-14582/com.example.android.autofill.app V/AutofillManager: notifyCallback(): sessionId=1006844058, autofillId=1073741824@1006844058, event=1
2022-02-02 18:38:58.706 14582-14582/com.example.android.autofill.app V/AutofillManager: notifyCallback(): sessionId=1006844058, autofillId=1073741824@1006844058, event=2
2022-02-02 18:38:58.715 14582-14582/com.example.android.autofill.app V/AutofillManager: updateSessionLocked(): id=1073741824, bounds=null, value=[type=1, value=52_chars], action=4, flags=0
`
on flutter project i get stuff like this when i tap in the fields.  no code changes at all from the sample

`
2022-02-02 18:40:17.136 16527-16527/com.example.mysample V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:40:17.258 16527-16527/com.example.mysample V/AutofillManager: notifyViewExited(1073741824, -1118964257
2022-02-02 18:40:26.382 16527-16527/com.example.mysample V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:40:26.489 16527-16527/com.example.mysample V/AutofillManager: notifyViewExited(1073741824, 234849508
2022-02-02 18:40:29.721 16527-16527/com.example.mysample V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:40:29.794 16527-16527/com.example.mysample V/AutofillManager: notifyViewExited(1073741824, 412349948
2022-02-02 18:40:34.306 16527-16527/com.example.mysample V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:40:34.387 16527-16527/com.example.mysample V/AutofillManager: notifyViewExited(1073741824, 1208734164
2022-02-02 18:40:36.048 16527-16527/com.example.mysample V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:40:36.985 16527-16527/com.example.mysample V/AutofillManager: requestHideFillUi(null): anchor = null
2022-02-02 18:40:37.083 16527-16527/com.example.mysample V/AutofillManager: notifyViewExited(1073741824, -181669963
`

**Comment by maheshmnj** [comment] 2022-02-03 08:26
Hi @neiljaywarner,  I can confirm that the autofill is not working on `stable 2.8.1` This was a known bug and is fixed on the latest master channel, You may verify this by switching to the master channel  by running 
```
flutter channel master
flutter upgrade
```
In case you still face the issue, we can continue the discussion here https://github.com/flutter/flutter/issues/97633

Closing this issue as a duplicate of the above-linked issue

**Closed by maheshmnj** 2022-02-03 08:26 UTC
Labels: in triage
