### ISSUE TITLE
[Impeller] Support non-AA drawing.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#104721] opened 2022-05-26 15:09 UTC
This is an uncommon use-case that Flutter's API currently supports. We may choose to support it in Impeller with a performance penalty.

See https://api.flutter.dev/flutter/dart-ui/Paint/isAntiAlias.html

**Comment by bdero** [comment] 2022-05-26 20:14
Would this actually incur a performance penalty? In Metal/modern GL/Vulkan, my understanding is that MSAA is a pipeline concern and the resolve texture is just like any other texture. Turning off MSAA for a draw just means rendering to it using a non-MSAA pipeline, which shouldn't be a problem for both the onscreen/offscreen targets.

For ancient GLES2, I think we're going to need an alternative mechanism to MSAA anyhow, as offscreen textures can't be rendered using MSAA. This excludes MSAA as a solution for antialiasing anything rendered to a SaveLayer or passed through a filter, because the root pass MSAA will only antialias the texture border of the SaveLayer/filter output.

**Comment by zanderso** [comment] 2022-05-26 20:24
Sorry, I wasn't saying that there *would* definitely be a performance penalty, but rather that the design space could include options that would entail one, if needed.

**Comment by bdero** [comment] 2022-05-26 21:44
Gotcha. We also need to make sure we're anti aliasing in the first place. Added a bug for that here: https://github.com/flutter/flutter/issues/104759

**Comment by dnfield** [comment] 2023-05-17 17:26
https://github.com/flutter/flutter/issues/126801 provides a use case for this - using aliased drawing of strokes to dynamically create a pixel-perfect pattern for shading other paths.

**Comment by feinstein** [comment] 2023-05-17 17:54
But this is only possible with a CustomPaint widget, right? I have seen AA issues in widgets with different colors close to each other, like trying to make a data table that alternates the color in each cell.

**Comment by jonahwilliams** [comment] 2023-09-27 18:29
@feinstein I think you've misunderstood the problems/solutions here. In the Skia renderer, the hariline artifacts are caused by their anti aliasing implementation - so turning off AA may fix the problem. In Impeller, you will not get hariline artifacts from our AA implementation, so turning it off is pointless (even if it did something).

**Comment by chinmaygarde** [comment] 2023-09-27 18:58
We discussed supporting this and came to the conclusion that the use-cases this was necessary for have been handled already.

* Conflation artifacts and the case @feinstein  is running into (likely https://github.com/flutter/flutter/issues/14288) are fixed because of Impellers reliance on MSAA. So turning off AA won’t be necessary because the issue it fixes in the legacy renderer is no longer present.
* Impeller's application of AA uniformly also fixes cases where AA was inexplicably not working. Like https://github.com/flutter/flutter/issues/77485.
* The case of “pixel art” comes up when talking about AA but that is handled by sampling and explicitly recreating surface aliasing which the isAntiAlias didn’t do either and is well supported in Impeller.

For these reasons, closing this as wont-fix.

**Closed by chinmaygarde** 2023-09-27 18:58 UTC
Labels: engine, c: rendering, P3, e: impeller, team-engine, triaged-engine

**Comment by feinstein** [comment] 2023-09-27 22:47
@chinmaygarde thank you for the explanation.

@mateusfccp it would be nice to validate these points with the cases we run into this AA issue in the past, by testing them with Impeller.
