### ISSUE TITLE
[performance] a small iOS app built by Flutter has too much battery impact

### ISSUE THREAD

**Issue by PerrchicK** [flutter/flutter#26895] opened 2019-01-22 17:30 UTC
## Description

Every time I use an app built by Flutter the Xcode indicates a very high energy impact.

I first noticed this reaction when playing a flare animation. But later I noticed it appears in every render of the UI. Am I using it wrong? Does everybody see this in their projects?

The GPU average usage meter may seem legit, since it’s an average there’s a good explanation for that. But why does it affect the battery so much? I want to build an app for production usage but doesn't seem quite healthy.

Uploaded this demo clip:
https://www.youtube.com/watch?v=I_VacxqDKDg
Downloadable code (Flutter, iOS & Android projects), in case you'll find some mistake there:
https://www.dropbox.com/s/dt32jpuihcg7gm4/battery_impact_example.zip?dl=0

Thanks a lot!

## Preconditions
* The app should have a scrollable scroll view (even an empty one would reproduce this issue).
* You can have a lite endless animation instead.
* Build the app using Flutter.
* Use a real device (in my case I used iPhone Xs).

## Steps to Reproduce

1. Run the iOS app from your Xcode.
2. Go to "Debug Navigator" pane.
3. Scroll the UI back and forth / observe the endless animation.
4. While scrolling / animation is playing, observe the battery impact and the GPU usage.

## Expected result
A production app shouldn't impact the battery so much.

## Actual result
According to Xcode's profiler, the app consumes too much battery.

**Comment by eseidelGoogle** [comment] 2019-01-22 20:38
I would not expect to see consistent usage from "screen", unless he screen is actually doing work every frame.  I haven't looked at the code, but it's possible it's calling setState on some widget every frame even though nothing is changing?

**Comment by PerrchicK** [comment] 2019-01-22 22:20
I tend to agree that this may be a root of this kind of issue, but still pretty sure that’s not the case. I’ll verify it soon.

**Comment by PerrchicK** [comment] 2019-01-23 14:45
Thanks, I'll check it out.

I looked in the code and also put a breakpoint in _framework.dart_, line 1127 (in my Flutter version), where the code is `final dynamic result = fn() as dynamic;` and I didn't see any endless recursive calls.

It happens in every Flutter app that has a scrollable scroll view (for example).

**Comment by cikelengfeng** [comment] 2019-06-21 09:39
here is a little example (endless animation)
[iOS-native.zip](https://github.com/flutter/flutter/files/3313844/iOS-native.zip)
[flutter.zip](https://github.com/flutter/flutter/files/3313850/flutter.zip)

here is energy impact in Xcode:

**Comment by liyuqian** [comment] 2019-10-07 22:22
This seems to be duplicate to https://github.com/flutter/flutter/issues/31865 . Our first step is https://github.com/flutter/flutter/issues/33899 (which is very similar to https://github.com/OkunaOrg/okuna-app/issues/420). Here's some high-level summary so far:

We did some research and find the Xcode/instrument's battery profiling tool to be quite unreliable 
and inaccurate.

In the long run, we might be adding some special hardware (e.g., [Monsoon](https://www.msoon.com/online-store)) to our lab to accurately measure the voltage and amps to calculate the exact power usage.

For now, we think that CPU and GPU percentage can be used to estimate Flutter's power usage as screen brightness and wireless signals are not directly managed by Flutter. Therefore, we recently added https://pub.dev/packages/gauge, which is currently used in [simple_animation_perf_iphonexs](https://github.com/flutter/flutter/blob/master/dev/devicelab/manifest.yaml#L538). The benchmark numbers are available in public through https://flutter-dashboard.appspot.com/benchmarks.html.

**Comment by liyuqian** [comment] 2019-11-21 01:08
Closing this as a duplicate of https://github.com/flutter/flutter/issues/31865 . Further discussion should happen there.

**Closed by liyuqian** 2019-11-21 01:08 UTC
Labels: engine, framework, severe: performance, ⌺‬ platform-ios
