### ISSUE TITLE
Add WidgetSpan support for TextField/RenderEditable

### ISSUE THREAD

**Issue by znshje** [flutter/flutter#30688] opened 2019-04-08 11:40 UTC
I don't need a passage editor like **Zefyr** which has styles like BOLD and ITALIC, what I want is a text field in which I can insert plain text, inline image(faces/emoji), block image, mention symbol(@) and topic symbol(#topic#).
It can be implemented on Android by SpannableString. I hope I can do it on Flutter, too.
So anyone knows how to do this?

**Comment by HansMuller** [comment] 2019-06-21 16:48
cc @GaryQian

**Comment by GaryQian** [comment] 2019-06-27 18:11
`Text.rich` supports building text from a tree of `InlineSpan`s, which in turn support any of the properties in `TextStyle`. We have recently added support for inline widgets. Simply include a `WidgetSpan` in your `InlineSpan` tree. This includes images, as well as any other arbitrary widget. You can add a @ symbol and make it linkable by adding a `GestureRecognizer` in a `TextSpan`.

Please refer to our (master channel) docs for more info.

- TextSpan https://master-api.flutter.dev/flutter/painting/TextSpan-class.html
- WidgetSpan https://master-api.flutter.dev/flutter/widgets/WidgetSpan-class.html
- InlineSpan https://master-api.flutter.dev/flutter/painting/InlineSpan-class.html
- TextStyle https://master-api.flutter.dev/flutter/dart-ui/TextStyle-class.html

**Comment by heinrichreimer** [comment] 2019-07-12 13:04
@GaryQian I don't think you've fully understood the issue.
There is `Text.rich()` which allows for formatting a `TextWidget`, but there is no `TextField` which could be styled like that.

**Comment by GaryQian** [comment] 2019-07-12 18:25
Ahh I see, my bad! I don't think there is a built in way right now, but the building blocks are there, it is a matter of assembling them such that we allow inputting custom `InlineSpan` trees into a text field.

**Comment by Sp4Rx** [comment] 2019-07-24 09:10
Could you elaborate about the implementation? @GaryQian

**Comment by GaryQian** [comment] 2019-07-24 17:49
So what kind of functionality would you require for this "Rich TextField"? We currently have the InlineSpan tree API that allows you to build a tree of InlineSpan objects that inherit TextStyles.

Would the functionality of being able to append independently styled InlineSpans to the contents of the TextField be sufficient?

**Comment by Sp4Rx** [comment] 2019-07-25 06:57
As I can see from [InlineSpan ](https://master-api.flutter.dev/flutter/painting/InlineSpan-class.html) example that it can have multiple `TextField` with different styles. But I want a single `TextField` where I can insert different styles. For example take Facebook's or any major platform's `@mention`

**Comment by GaryQian** [comment] 2019-07-26 23:53
Well since we don't have this explicit capability yet, it would be helpful if you could provide pseudo/fake sample code on how you would like the API to work.

There are a couple of ways this could work, one of them being keeping a stack of TextStyles and push/pop methods. Any text inserted through keyboard or through a manual method would then have the style the top TextStyle in the stack. This system would be very similar to our existing ParagraphBuilder works.

Other approaches could be either more or less structured, but it would be very helpful to have examples of the kind of code you want to be able to write to achieve what you want. Feel free to make up methods/classes/API! This way, we can add the functionality that would best fit your (and other's uses)

**Comment by Sp4Rx** [comment] 2019-07-27 11:51
Flutter has a class called [Chip](https://api.flutter.dev/flutter/material/Chip-class.html). I don't know it is the right question to ask  or not, is it possible to insert `Chip` in `TextField`?

As flutter don't provide inserting styling by positions like  [SpannableString](https://developer.android.com/reference/android/text/SpannableString) so I can think of the pseudo code similar to `RichText`

    //pseudo code
    RichTextField(
      style: DefaultTextStyle.of(context).style,
      children: <SubTextField>[
        SubTextField(
          style: TextStyle(
            color: Colors.white,
          ),
        ),
        SubTextField(),
      ],
    )

**Comment by seeps001** [comment] 2019-07-27 22:48
Any thoughts on a core rich text plugin similar to CKEditor?

**Comment by gerry05** [comment] 2019-07-29 19:02
how to get the  url/image of GIF in keyboard?    I got this message when I try to select a gif. **App Name doesn't support image insertion here.**

**Comment by TonAbs** [comment] 2019-08-04 07:22
Perhaps this package can help!
https://pub.dev/packages/extended_text_field#-readme-tab-

**Comment by Sp4Rx** [comment] 2019-08-04 09:14
[extended_text_field  ](https://pub.dev/packages/extended_text_field)Looks promising , I will implement and share my feedback.

**Comment by GaryQian** [comment] 2019-08-08 22:57
We may be able to work with the author of that package to see if we can come up with a reasonable way to integrate some of its core features directly and efficiently into Flutter, as it seems that package accomplishes  much of what is being requested here.

For now, the extended_text_field looks like a good solution to achieve the desired effect.

**Comment by RAN3000** [comment] 2019-11-17 18:01
Has there been any progress on this issue?

**Comment by TonAbs** [comment] 2019-11-17 18:19
You can now override the `buildTextSpan` method in the `textEditingController` to achieve the desired effect

**Comment by RAN3000** [comment] 2019-11-17 18:39
True. 
It is not complete though.
I can add custom styles to `TextSpan`s, as you say. Now I'm on my way to add `WidgetSpan` support, `RenderEditable` does not support it yet.
Is anybody else working on this?

**Comment by GaryQian** [comment] 2019-11-20 00:19
I have not been able to get to it yet. If someone has the time, I would be happy to review any PRs for this feature. You should be able to use RenderParagraph's impl as a guide.

I'll try my best to get to this eventually, but have higher priority/sensitive issues to tackle at the moment.

**Comment by RAN3000** [comment] 2019-11-22 08:34
Thank you!
I got a basic version working, basically by fitting RenderParagraph stuff into RenderEditable.
Now I'm focusing on something else, but will get back to it soon.

It would be awesome to have Flutter support this without having to reimplement EditableText and so on, so I'll be happy to help.

**Comment by Ahmadre** [comment] 2019-12-26 01:38
@All any updates?

**Comment by gliese667c** [comment] 2020-01-29 02:52
Any NEW updates?

**Comment by hungbu** [comment] 2020-03-03 04:57
I am very looking forward to this, hope this issue is support soon.

**Comment by kazbeksultanov** [comment] 2020-05-04 18:42
Seems like no updates but I will ask anyway. Any NEW updates?

**Comment by fzyzcjy** [comment] 2020-05-30 01:50
This is very attractive feature! Any updates?

**Comment by bitweng** [comment] 2020-06-14 15:43
> Thank you!
> I got a basic version working, basically by fitting RenderParagraph stuff into RenderEditable.
> Now I'm focusing on something else, but will get back to it soon.
> 
> It would be awesome to have Flutter support this without having to reimplement EditableText and so on, so I'll be happy to help.

@RAN3000  Any NEW updates?

**Comment by hungbu** [comment] 2020-08-07 11:10
rich_text_controller has support `#Hashtag` `@mentions` .. 
[https://pub.dev/packages/rich_text_controller](https://pub.dev/packages/rich_text_controller)

but hashtag content does not include spaces.
I think it can help a lot of people, but not me :(  
I need hashtag content include spaces .. wait feature of this topic

**Comment by mr-mamali** [comment] 2020-08-30 10:37
any update here ?

**Comment by brianschardt** [comment] 2020-10-23 15:20
Any updates on being able to add WidgetSpans to textFields?

**Comment by AlexV525** [comment] 2020-11-05 12:38
I think we don't have a plan for this currently, but there is a package that implement a similar feature already: https://pub.dev/packages/extended_text_field

**Comment by zmtzawqlp** [comment] 2020-11-05 15:22
I'm the author of https://pub.dev/packages/extended_text_field. As I see, we have following problems need to be solved.
1. [SelectableText widget supports WidgetSpan](https://github.com/flutter/flutter/issues/38474), we need the help who charge TextPainter api in flutter engine. We can't get the right position for WidgetSpan now.
2. TextDirection.rtl is not right for WidgetSpan now.
3. Think about what we want? What kind of api we need. I have done something in https://pub.dev/packages/extended_text and https://pub.dev/packages/extended_text_field. We need more feedback.

**Comment by spazzlite** [comment] 2021-01-29 06:00
I need to get WidgetSpan from method buildSpan() in TextEditingController, but now it always throw exceptions... Any progress on this?

**Comment by mindeng** [comment] 2021-02-07 13:07
> I need to get WidgetSpan from method buildSpan() in TextEditingController, but now it always throw exceptions... Any progress on this?

I need this too ...

**Comment by josefrvaldes** [comment] 2021-02-16 15:36
Another one here trying to make it work. At the moment I can't user WidgedSpan inside TextEditingController.

**Comment by Niklas212** [comment] 2021-02-17 15:04
Any new update

**Comment by mordivgor** [comment] 2021-03-11 15:16
For anyone who is looking for some simple editor, you can check https://pub.dev/packages/flutter_quill.
I am not an author, but I just found it and at least images in textField works.

**Comment by spazzlite** [comment] 2021-03-19 04:32
I don't need editor, I need to add tag in a text field with autocomplete functionality. That's why i need widget span.

**Comment by Teio07** [comment] 2021-03-20 14:27
I'm trying to implement it by myself and got something "kind of working".

This is the piece of code I put inside the "buildTextSpan" method of TextEditingController :
<img width="1680" alt="Capture d’écran 2021-03-20 à 14 48 21" src="https://user-images.githubusercontent.com/50293307/111871735-02c7b000-898c-11eb-8760-de9d811c006d.png">

And what it looks like in action :

https://user-images.githubusercontent.com/50293307/111871799-44585b00-898c-11eb-8828-f37faad76cd4.mov

As you can see there's an offset problem of two characters because of the two WidgetSpans added before the TextSpan. There's also the problem of the cursor not adapting its height to the WidgetSpan.
I just did what @GaryQian said above and took a look at RenderParagraph and Copy-Pasted some code inside RenderEditable (as well as some minor modifications inside EditableText).
I'll try and read those file and see if I can solve those problems.

I'm also building a RichTextField using the default TextField Widget Flutter is offering and it looks kind of promising, here's a peek :

https://user-images.githubusercontent.com/50293307/111873208-88009400-898f-11eb-85d4-5a4622c9c199.mov

You'll be able to customize the toolbar or provide your own and create as many styles as you want.

**Comment by MatrixDev** [comment] 2021-03-23 09:40
Is there any official progress from Dart team on this bug? Maybe, just maybe, someone has started working on it?

**Comment by GaryQian** [comment] 2021-04-13 11:55
I've begun to look at implementing a solution for this based on RegExp matching in https://github.com/flutter/flutter/pull/80185

If you would like to help shape the API for this, please take a look at the PR and see if you think the proposed API would be good/useful/sufficient to serve your use cases! I would welcome any feedback, as this particular problem can be approached from many different ways. I've currently prototyped out the Pattern matching version as it seems to be a good balance between general versatility and complexity.

**Comment by MatrixDev** [comment] 2021-04-13 12:00
@GaryQian  why are you using RegExp for this? It limits how it can be used.
`TextEditingController` already supports spans via `buildTextSpan`. Only problem that code will crash when `WidgetSpan` is present.

**Comment by GaryQian** [comment] 2021-04-13 12:04
This PR will allow WidgetSpans to be rendered regardless of how they are inserted into the Textfield.

The regexp system is separate and adds an easier to use layer on top of the lower level editable classes to allow easier implementation of most common use cases.

You are always welcome to override buildTextSpan for your own solutions, which will work with the rest of the code in RenderEditable/_Editable/etc

**Comment by MatrixDev** [comment] 2021-04-13 12:07
@GaryQian sorry, I misunderstood PR. As for me `WidgetSpan` support is great, everything else - is just an icing on the cake :)

**Comment by GaryQian** [comment] 2021-04-13 12:09
But now that you mention it, I will probably move the RegExp/Pattern matching controller into a separate extension of the base TextEditingController so as to not add any overhead to non-widgetspan fields which I expect to be much more common that widgetspan fields.

**Comment by Teio07** [comment] 2021-04-17 08:47
Hi @GaryQian 
Would that enable the possibility of having indents at the beginning of a paragraph ?
I noticed you considered a WidgetSpan to be accounted as a single character which would be the way to go in most cases (for inline images, tag chips,...) but in my case, I need to have an indent at the beginning of each paragraph and this indent should not be deleted unless the paragraph itself is deleted, plus the user should not be able to navigate at the start of this indent (probably a SizedBox with a given width).

If you need something more visual here’s what I’m trying to achieve (it’s an excerpt from a screenplay) :

![IMG_0020](https://user-images.githubusercontent.com/50293307/115107248-f7a37800-9f69-11eb-95bb-9ee1740629e2.PNG)

**Comment by GaryQian** [comment] 2021-05-12 10:50
@Teio07 Unfortunately, what you are trying to do is not within the scope of the feature being discussed here. You may be able to piece together a custom system that can accomplish it that involves WidgetSpans but I don't think advanced editor layout can be added as part of this WidgetSpan feature. What you are asking here is essentially a simple version of a proper document editor like Google docs or MS word, which we have no plans of directly supporting in Flutter. That being said, I think I have found examples of document editors built in Flutter, so it should be possible.

**Comment by Teio07** [comment] 2021-05-12 11:31
I think I could make it work if I replace all « new line characters » using the replacement method you implemented with a WidgetSpan which would have a SizedBox (with some predefined height and width). But then I’ll have the problem of the user being able to put the cursor behind the WidgetSpan. I tried something like this some time ago (https://github.com/flutter/flutter/issues/30688#issuecomment-803360473) and it looks like it could work.
I’m not sure because it sounds really « hackish » 🤷‍♂️
Also I’m not really sure how I could do the « align text to end » stuff. I guess it would imply doing some sort of calculations with TextPainter to create a SizedBox the right width.

**Comment by MatrixDev** [comment] 2021-05-12 12:22
@Teio07 it actually should be pretty easy to do by just wrapping part of text into `WidgetSpan` and add paddings or whatever. Unfortunately you can't do this because `TextField`/`RenderEditable` doesn't support `WidgetSpan` and will just crash.

**Comment by Teio07** [comment] 2021-05-12 14:11
@MatrixDev I'm not sure I could do it this way since `WidgetSpan` takes a `Widget` as a child which `TextSpan` isn't and I think `RenderEditable` uses `TextSpan`s to calculate metrics using `TextPainter` so I think the only way would be to override `buildTextSpan` and build paragraphs like this :

```
TextSpan(children: [
      // Paragraph 1
      TextSpan(children: [
        WidgetSpan(
          child: SizedBox(width: paddingLeftParagraph1),
        ),
        TextSpan(textForParagraph1),
      ]),

      // Paragraph 2
      TextSpan(children: [
        WidgetSpan(
          child: SizedBox(width: paddingLeftParagraph2),
        ),
        TextSpan(textForParagraph2),
      ]),

      // Paragraph 3
      TextSpan(children: [
        WidgetSpan(
          child: SizedBox(width: paddingLeftParagraph3),
        ),
        TextSpan(textForParagraph3),
      ]),
    ]);
```

But, then I have no idea how to deal with right side padding... 😕

**Comment by mordivgor** [comment] 2021-05-14 16:14
Hello @GaryQian ,
This is very expected feature from my point of view and I am very thankful that you are working on it.
One question from my side - how text field will be rendered after editing it? We have already couple of rich text editors built in flutter, but I am struggling with one problem - when I am editing the whole text field, all widgets are being rebuilt constantly (e.g.  https://github.com/singerdmx/flutter-quill/issues/89#issuecomment-801209237).
Do you know how it would be done here? Will widgetSpan be constantly rebuilding because of editing the text field? I believe all is about internal implementation - most (all?) current text editors went through whole text and built all widgets from the beginning.

**Comment by MatrixDev** [comment] 2021-05-14 16:56
@mordivgor, I really don't think (yet hope) they will implement dynamic/editable spans like `Editable` in Android. It'll most probably will require complete rewrite of current span implementation. I hope they at least implement `WidgetSpan` without big compromises.

**Comment by devilyard** [comment] 2021-05-19 10:47
any updates for this?

**Comment by GaryQian** [comment] 2021-06-01 21:27
I will be attempting to land this as two parts:

- The core WidgetSpan rendering support in RenderEditable
- User-friendly API to handle the TextEditingValue -> TextSpan+WidgetSpan conversion process.

The core rendering support will land first, which will allow more advanced users to begin modifying their TextEditingControllers to provide to RenderEditable. The second part requires more detailed planning and work.

**Comment by GaryQian** [comment] 2021-06-16 07:08
Core widgetspan support has landed. RenderEditable, and by extension, textfields, can now display WidgetSpans if the TextEditingController outputs WidgetSpans.

**Comment by spideythewebhead** [comment] 2021-06-28 20:54
Hello! In what version is this api available? I am currently using 2.2.1, i was reading through `TextEditingController`
and i saw this method `TextSpan buildTextSpan({required BuildContext context, TextStyle? style , required bool withComposing}) {..}`, in the comments it says we should override this if we want to provide customized text.

I wrote this function

```dart
  @override
  TextSpan buildTextSpan({required BuildContext context, TextStyle? style, required bool withComposing}) {
    final atIndex = text.indexOf('@');
    var spans = <InlineSpan>[];

    if (atIndex != -1) {
      spans.add(TextSpan(text: text.substring(0, atIndex)));
      spans.add(
        WidgetSpan(
          alignment: PlaceholderAlignment.middle,
          child: Card(
            child: Padding(
              padding: const EdgeInsets.all(4.0),
              child: Text('@'),
            ),
          ),
        ),
      );
      spans.add(TextSpan(text: text.substring(1 + atIndex)));
    } else {
      spans.add(TextSpan(text: text));
    }

    return TextSpan(
      children: spans,
    );
  }
```
What is does, it replaces the `@` symbol with a widget, but this crashes with this assertion
'package:flutter/src/widgets/widget_span.dart': Failed assertion: line 105 pos 12: 'dimensions != null': is not true.

I probably dont understand how it should be done, is there any guide or its not available yet? thanks!

**Comment by Paul-cbt** [comment] 2021-06-29 12:41
Hello @spideythewebhead, I have also rewrote the buildTextSpan method, but as soon as I add a WidgetSpan into the mix:
```
The following assertion was thrown during performLayout():
Assertion failed:
..\…\widgets\widget_span.dart:105
dimensions != null
is not true


The relevant error-causing widget was
TextField-[GlobalKey#d0c03 rectoinputText]
lib\…\flashCardCreate_tile\flashcardcreate_tile.dart:1972
When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/flutter/src/widgets/widget_span.dart 105:22                                                                       build
packages/flutter/src/painting/text_span.dart 252:14                                                                        build
packages/flutter/src/painting/text_painter.dart 569:7                                                                      layout
...
The following RenderObject was being processed when the exception was fired: RenderEditable#a1504 relayoutBoundary=up73 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderEditable#a1504 relayoutBoundary=up73 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=1335.8, 0.0<=h<=Infinity)
    size: MISSING
    cursorColor: Color(0x00f46b45)
    showCursor: ValueNotifier<bool>#47e2f(true)
    maxLines: null
    minLines: 1
    selectionColor: Color(0x662196f3)
    textScaleFactor: 1.0
    locale: en_US
    selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false)
    offset: ScrollPositionWithSingleContext#4e4f3(offset: 0.0, range: null..null, viewport: null, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e2324, ScrollDirection.idle)
    text: TextSpan
        debugLabel: (englishLike subhead 2014).merge((blackRedmond subtitle1).apply)
        inherit: false
        color: Color(0xdd000000)
        family: Noto
        size: 16.0
        weight: 400
        baseline: alphabetic
```

```
Assertion failed:
..\…\rendering\box.dart:1930
hasSize
"RenderBox was not laid out: RenderSemanticsAnnotations#17089 relayoutBoundary=up69 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE"

The relevant error-causing widget was
TextField-[GlobalKey#d0c03 rectoinputText]
lib\…\flashCardCreate_tile\flashcardcreate_tile.dart:1972

```

**Comment by spideythewebhead** [comment] 2021-06-29 18:06
@GaryQian Hi, any idea for this problem?

**Comment by jasonhoo95** [comment] 2021-07-13 09:24
> r



> I'm trying to implement it by myself and got something "kind of working".
> 
> This is the piece of code I put inside the "buildTextSpan" method of TextEditingController :
> <img alt="Capture d’écran 2021-03-20 à 14 48 21" width="1680" src="https://user-images.githubusercontent.com/50293307/111871735-02c7b000-898c-11eb-8760-de9d811c006d.png">
> 
> And what it looks like in action :
> 
>  WidgetSpan_Offset_Problem.mov 
> As you can see there's an offset problem of two characters because of the two WidgetSpans added before the TextSpan. There's also the problem of the cursor not adapting its height to the WidgetSpan.
> I just did what @GaryQian said above and took a look at RenderParagraph and Copy-Pasted some code inside RenderEditable (as well as some minor modifications inside EditableText).
> I'll try and read those file and see if I can solve those problems.
> 
> I'm also building a RichTextField using the default TextField Widget Flutter is offering and it looks kind of promising, here's a peek :
> 
>  RichTextField_Peek.mov 
> You'll be able to customize the toolbar or provide your own and create as many styles as you want.

Hi do u mind sharing your code to me for the rich textfield it looks really cool, and i need to implement that

**Comment by jasonhoo95** [comment] 2021-07-19 12:52
<img width="319" alt="Screenshot 2021-07-19 at 8 50 37 PM" src="https://user-images.githubusercontent.com/13375280/126162290-2d5ba366-4381-43fb-8527-4a58e4d71f70.png">
Any idea how to solve this, the text span of textfield when i set background colour to it, the selection highlight colour will not be visible anymore, i think this is a bug need to fix, am I right? or there is a way to fix this?

**Comment by GaryQian** [comment] 2021-07-20 06:34
@jasonhoo95 This particular issue is actually more difficult to solve depending on what you want. Currently, the background color is drawn as part of the text layout and painting, while the selection highlight is drawn separately. We are presented with two options: Draw highlight behind the text (including the bg) or over the text (including bg). For most cases, drawing behind is correct as we want the text to remain readable. However, in this case, the bg just ends up obscuring the highlight.

You could try modifying RenderEditable to paint the highlight after the text and playing with the opacity, but it would still obscure the text. Slipping the highlight between the text and the bg is a fairly complex change that modifies the layout engine and I don't think there is enough demand for that capability to justify it as of now.

**Comment by jasonhoo95** [comment] 2021-07-22 06:53
@GaryQian Hmm but can I ask, in ios native layout engine is possible to set the highlight to overlay above the bg and text am I right?

**Comment by derkro99** [comment] 2021-08-23 13:18
> Hello @spideythewebhead, I have also rewrote the buildTextSpan method, but as soon as I add a WidgetSpan into the mix:
> 
> ```
> The following assertion was thrown during performLayout():
> Assertion failed:
> ..\…\widgets\widget_span.dart:105
> dimensions != null
> is not true
> 
> 
> The relevant error-causing widget was
> TextField-[GlobalKey#d0c03 rectoinputText]
> lib\…\flashCardCreate_tile\flashcardcreate_tile.dart:1972
> When the exception was thrown, this was the stack
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
> packages/flutter/src/widgets/widget_span.dart 105:22                                                                       build
> packages/flutter/src/painting/text_span.dart 252:14                                                                        build
> packages/flutter/src/painting/text_painter.dart 569:7                                                                      layout
> ...
> The following RenderObject was being processed when the exception was fired: RenderEditable#a1504 relayoutBoundary=up73 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
> RenderObject: RenderEditable#a1504 relayoutBoundary=up73 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
>     parentData: <none> (can use size)
>     constraints: BoxConstraints(w=1335.8, 0.0<=h<=Infinity)
>     size: MISSING
>     cursorColor: Color(0x00f46b45)
>     showCursor: ValueNotifier<bool>#47e2f(true)
>     maxLines: null
>     minLines: 1
>     selectionColor: Color(0x662196f3)
>     textScaleFactor: 1.0
>     locale: en_US
>     selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false)
>     offset: ScrollPositionWithSingleContext#4e4f3(offset: 0.0, range: null..null, viewport: null, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e2324, ScrollDirection.idle)
>     text: TextSpan
>         debugLabel: (englishLike subhead 2014).merge((blackRedmond subtitle1).apply)
>         inherit: false
>         color: Color(0xdd000000)
>         family: Noto
>         size: 16.0
>         weight: 400
>         baseline: alphabetic
> ```
> 
> ```
> Assertion failed:
> ..\…\rendering\box.dart:1930
> hasSize
> "RenderBox was not laid out: RenderSemanticsAnnotations#17089 relayoutBoundary=up69 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE"
> 
> The relevant error-causing widget was
> TextField-[GlobalKey#d0c03 rectoinputText]
> lib\…\flashCardCreate_tile\flashcardcreate_tile.dart:1972
> ```
@Paul-cbt Did you manage to find a solution for this problem?

**Comment by wrteam-priyansh** [comment] 2021-11-17 07:56
> I'm trying to implement it by myself and got something "kind of working".
> 
> This is the piece of code I put inside the "buildTextSpan" method of TextEditingController : <img alt="Capture d’écran 2021-03-20 à 14 48 21" width="1680" src="https://user-images.githubusercontent.com/50293307/111871735-02c7b000-898c-11eb-8760-de9d811c006d.png">
> 
> And what it looks like in action :
> 
>  WidgetSpan_Offset_Problem.mov 
> As you can see there's an offset problem of two characters because of the two WidgetSpans added before the TextSpan. There's also the problem of the cursor not adapting its height to the WidgetSpan. I just did what @GaryQian said above and took a look at RenderParagraph and Copy-Pasted some code inside RenderEditable (as well as some minor modifications inside EditableText). I'll try and read those file and see if I can solve those problems.
> 
> I'm also building a RichTextField using the default TextField Widget Flutter is offering and it looks kind of promising, here's a peek :
> 
>  RichTextField_Peek.mov 
> You'll be able to customize the toolbar or provide your own and create as many styles as you want.

Hello sir, can you please share some initial building blocks to build RichTextField with some basic functionality?
Thanks

**Comment by hwasoocho** [comment] 2022-02-13 04:28
Any progress on this issue?

**Comment by Renzo-Olivares** [comment] 2022-03-17 20:23
```
```

**Comment by yohom** [comment] 2022-03-18 00:57
> I made a simple example to show that `WidgetSpans` render inside of a `TextField` inline with other text. Core support for this was added in #83537 . Is this what this issue is asking for? If not please explain further.
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: const MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({Key? key, required this.title}) : super(key: key);
> 
>   final String title;
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   final WidgetSpanTextEditingController _controller =
>       WidgetSpanTextEditingController(
>           text: 'The quick brown fox jumps over the lazy \uffff dog.');
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text(widget.title),
>       ),
>       body: Center(
>         child: TextField(
>           controller: _controller,
>           maxLines: null,
>         ),
>       ),
>     );
>   }
> }
> 
> class WidgetSpanTextEditingController extends TextEditingController {
>   WidgetSpanTextEditingController({String? text})
>       : super.fromValue(text == null
>             ? TextEditingValue.empty
>             : TextEditingValue(text: text));
> 
>   @override
>   TextSpan buildTextSpan(
>       {required BuildContext context,
>       TextStyle? style,
>       required bool withComposing}) {
> 
>     TextRange? matchedRange;
> 
>     if (text.contains('\uffff')) {
>       matchedRange = _findMatchedRange(text);
>     }
> 
>     if (matchedRange != null) {
>       return TextSpan(
>         children: [
>           TextSpan(text: matchedRange.textBefore(text)),
>           const WidgetSpan(child: FlutterLogo()),
>           TextSpan(text: matchedRange.textAfter(text)),
>         ],
>         style: style,
>       );
>     }
> 
>     return TextSpan(text: text, style: style);
>   }
> 
>   TextRange _findMatchedRange(String text) {
>     final RegExp matchPattern = RegExp(RegExp.escape('\uffff'));
>     late TextRange matchedRange;
>     
>     for (final Match match in matchPattern.allMatches(text)) {
>       matchedRange = TextRange(start: match.start, end: match.end);
>     }
> 
>     return matchedRange;
>   }
> }
> ```
> 
> <img alt="Screen Shot 2022-03-17 at 1 33 53 PM" width="1199" src="https://user-images.githubusercontent.com/948037/158890495-afb843be-c37a-436a-a056-ec9d3c38e1d9.png">

The `buildTextSpan` renders WidgetSpan successfully in a TextField, but the cursor can not locate to the last position. When you try to move the cursor to the last position, the cursor jumps to the first position.
My `flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
[✓] VS Code (version 1.65.2)
```

**Comment by Renzo-Olivares** [comment] 2022-03-18 20:57
@yohom thanks for trying it out. I was able to reproduce your issue on stable as well. It is fixed on the master branch (video below). 

https://user-images.githubusercontent.com/948037/159081384-d428597a-9bb4-4733-aed0-1ff6c1f1a075.mp4

**Closed** 2022-03-18 21:01 UTC
Labels: a: text input, severe: new feature, waiting for customer response, framework, f: material design, proposal, P3
