### ISSUE TITLE
Problem Run flutter On Emulator

### ISSUE THREAD

**Issue by collinspro** [flutter/flutter#37469] opened 2019-08-02 10:11 UTC
hello guys please i Encountered  This Error when running my application. please i need help
```
C:\flutterApp\fluttertutorial>flutter run
```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                                 /
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 74e719945ec1c5a4)
Initializing gradle...
Crash report written to C:\flutterApp\fluttertutorial\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

Secondly  i Ran it using the Android Studio And this was the error i got . please  i need help and solutions 
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "C:\flutterApp\fluttertutorial\android\gradlew.bat" exited abnormally:
Unzipping C:\Users\ONUMBA COLLINS\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip to C:\Users\ONUMBA COLLINS\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv
```
```
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\flutterApp\fluttertutorial\android\gradlew.bat -v
```

**Comment by collinspro** [comment] 2019-08-02 10:11
PLEASE  HELP

**Comment by BaderEddineOuaich** [comment] 2019-08-02 11:52
try run
<pre>flutter run --enable-software-rendering</pre>
as mentioned in the error.

**Comment by collinspro** [comment] 2019-08-02 11:58
Thanks for the reply but don't realm know how to enable (software rendering ) ,do you have the step on how to do so ?

**Comment by BaderEddineOuaich** [comment] 2019-08-02 12:06
simply run the command  `flutter run --enable-software-rendering` and it will take care of it.

**Comment by collinspro** [comment] 2019-08-02 14:09
After running  flutter run --enable-software-rendering this was the error i encountered. Any suggestions 


C:\flutterApp\fluttertutorial>flutter run --enable-software-rendering
Using software rendering with device Android SDK built for x86. You may get better performance with hardware mode by
configuring hardware rendering for your device.
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                                 -
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Failed host lookup: 'clients2.google.com' (OS
Error: No such host is known.
, errno = 11001)
Initializing gradle...
Crash report written to C:\flutterApp\fluttertutorial\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.

> simply run the command `flutter run --enable-software-rendering` and it will take care of it.

**Comment by BondarenkoStas** [comment] 2019-09-19 15:12
@collinspro Can you provide that ```flutter_03.log```? Because in this case it may be totally different issue.

**Comment by jonahwilliams** [comment] 2019-10-15 19:30
Duplicate of https://github.com/flutter/flutter/issues/40517

**Closed by jonahwilliams** 2019-10-15 19:30 UTC
Labels: waiting for customer response
