### ISSUE TITLE
setPreferredOrientations not updates after fixing one orientation

### ISSUE THREAD

**Issue by AshotKhachatryan1995** [flutter/flutter#121785] opened 2023-03-02 09:25 UTC
## Steps to Reproduce

1. Push to "first page" from home 
2. In "first page" setPreferredOrientations([DeviceOrientation.landscapeLeft])
3. Push to "second page" 
4. In "second page" setPreferredOrientations(DeviceOrientation.values)

After this steps not return in portrait mode.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-x64, locale en)
    • Flutter version 3.7.6 on channel stable at /Users/admin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (15 hours ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (1 available)
    • iPhone 13 Pro (mobile) • 00008110-00065D890C2A801E • ios • iOS 16.3.1 20D67

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
</details>

**Comment by AshotKhachatryan1995** [comment] 2023-03-02 09:30
```

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Orientation Change Demo app'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations(DeviceOrientation.values.toList());
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.push(context,
            MaterialPageRoute(builder: (context) => const PushFirstPage())),
        child: const Icon(Icons.navigate_next),
      ),
    );
  }
}

class PushFirstPage extends StatefulWidget {
  const PushFirstPage({super.key});

  @override
  State<StatefulWidget> createState() => _PushFirstPageState();
}

class _PushFirstPageState extends State<PushFirstPage> {
  @override
  void initState() {
    super.initState();

    SystemChrome.setPreferredOrientations(
        [DeviceOrientation.landscapeLeft, DeviceOrientation.landscapeRight]);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("First Page"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.push(context,
            MaterialPageRoute(builder: (context) => const PushSecondPage())),
        child: const Icon(Icons.navigate_next),
      ),
    );
  }
}

class PushSecondPage extends StatefulWidget {
  const PushSecondPage({super.key});

  @override
  State<StatefulWidget> createState() => _PushSecondPageState();
}

class _PushSecondPageState extends State<PushSecondPage> {
  @override
  void initState() {
    super.initState();

    SystemChrome.setPreferredOrientations(DeviceOrientation.values);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Second Page"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.pop(context),
        child: const Icon(Icons.navigate_next),
      ),
    );
  }
}
```

**Comment by danagbemava-nc** [comment] 2023-03-02 10:43
Hi @AshotKhachatryan1995, I believe this is a duplicate of https://github.com/flutter/flutter/issues/57748.

Kindly subscribe to the issue linked above for updates. 

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2023-03-02 10:43 UTC
Labels: in triage

**Comment by AshotKhachatryan1995** [comment] 2023-03-02 10:47
Hi @danagbemava-nc. Yeah I think same issue.

Thank you
