### ISSUE TITLE
Flutter embedded in webapp hijacks the spacebar

### ISSUE THREAD

**Issue by cmarques2** [flutter/flutter#144097] opened 2024-02-25 05:32 UTC
### Steps to reproduce

- Create a flutter app that uses the SingleChildScrollView
- Embed it in a web app
- once shown, the web app doesn't respond to the spacebar anymore

Two sample apps and instructions are included to reproduce the issue.

In the readme for the examples, I forget two steps.  
You also need to run this command after installing dart
```
pub global activate webdev
```
And ensure that your path is updated with 
```
%LocalAppData%\Pub\Cache\bin
```

### Expected results

that it doesn't do that

### Actual results

It does that

### Code sample

<details open><summary>Code sample</summary>

```dart
// Files have been attached that include 
// an Angular Dart web app and a Flutter app 
// with instructions for building and running them.
```

</details>

[spacebar_issue_testapp.zip](https://github.com/flutter/flutter/files/14395328/spacebar_issue_testapp.zip)

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-02-26 08:40
>First install dart sdk 2.13.4

Hi @cmarques2, unfortunately I don't have this version on my machine. `flutter pub get` is failed on your `angular_test_focus` project:

```console
The lower bound of "sdk: '>=2.8.1 <3.0.0'" must be 2.12.0'
or higher to enable null safety.

The current Dart SDK (3.3.0) only supports null safety.

For details, see https://dart.dev/null-safety
exit code 65
```

When I upgrade the sdk constraint, it leads to this error:
```console
Because embed_flutter depends on angular_components any which doesn't support null safety, version solving failed.
```

[angular_components](https://pub.dev/packages/angular_components) is discontinued and you can try using [ngcomponents](https://pub.dev/packages/ngcomponents) instead. 

I would be appreciated if you can use a simpler web app setup (a pure HTML sample?) so that the issue is easier to be verified. Thanks!

**Comment by cmarques2** [comment] 2024-02-26 14:42
you can force a dart-sdk version install. 
```
choco install dart-sdk --force --version 2.13.4
```
Then you can go back to latest. It's pretty quick.

I have flutter and 2.13.4 on the same machine. works fine.

This is our environment. We jumped on the AngularDart train and it got sunset on us...

**Comment by huycozy** [comment] 2024-02-27 06:08
Hi @cmarques2
Since it's an 3rd party component running on a quite old Dart version, it will take time for others look into this and try to investigate the issue. So I would recommend you provide a simpler web app as I mentioned above. 

The issue may be fixed on the latest Flutter channels, please help to check it. Please also share the output of `flutter doctor -v` if the issue still persists. Thanks!

**Comment by huycozy** [comment] 2024-02-28 05:48
Thanks for the update. 

For the build command param, you should use `--output` instead, see PR changed this: https://github.com/flutter/flutter/pull/113076.

```console 
-o, --output The absolute path to the directory where the repository is generated. By default, this is <current-directory>/build/<target-platform>.
```

<details>
<summary>Demo build command and video</summary>

```console
➜  flutter_test_focus flutter build web --output=../web_test_focus/test_focus

Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons), but found (MaterialIcons). This usually means you are referring to font families in an IconData class but not
including them in the assets section of your pubspec.yaml, are missing the package that would include them, or are missing "uses-material-design: true".
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7692 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building
your app.
Compiling lib/main.dart for the Web...                             37.2s
➜  flutter_test_focus 
```

https://github.com/flutter/flutter/assets/104349824/c67cbe92-7126-4514-bf4e-1670a516b31e


</details>

### More tests on this:

1. There are both `Focus` and `SingleChildScrollView` widgets (original sample code) -> The issue is reproduced ❗
2. Remove `Focus`, keep `SingleChildScrollView` widget -> The issue is not reproduced ✅
3. Remove `SingleChildScrollView` , keep `Focus` widget  -> The issue is not reproduced ✅

✅: No Issue ❗: Issue reproduced

That being said, this relates to focus as well. Reproduced this issue on the latest Flutter stable/master channels.
<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (29 hours ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-15.0.pre.20, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-15.0.pre.20 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71fd015d05 (33 minutes ago), 2024-02-28 02:26:59 +0000
    • Engine revision fe7ea6d9c3
    • Dart version 3.4.0 (build 3.4.0-180.0.dev)
    • DevTools version 2.33.0-dev.11
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 2B171FDH20084L                           • android-arm64  • Android 14 (API 34)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 122.0.6261.69

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by yjbanov** [comment] 2024-02-29 03:14
Deduplicating into https://github.com/flutter/flutter/issues/137443

**Closed by yjbanov** 2024-02-29 03:14 UTC
Labels: framework, f: scrolling, a: existing-apps, platform-web, f: focus, has reproducible steps, team-web, found in release: 3.19, found in release: 3.20
