### ISSUE TITLE
The ripple animation goes beyond the swipe list

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#127794] opened 2023-05-29 13:32 UTC
#91605

### Steps to reproduce

1. Click or hold the ListTile widget
2. Scroll the list up while holding the desired widget

### Expected results

When clicking on a ListTile while scrolling through the list in the Search view, the ripple effect should hide under the Divider, just like the ListTile widgets themselves.

### Actual results

When clicking on a ListTile while scrolling through the list in the Search view, a ripple effect is played over the text field starting from Divider.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true, brightness: Brightness.light),
      darkTheme: ThemeData(useMaterial3: true, brightness: Brightness.dark),
      home: SearchBarsScreen(),
    );
  }
}

class SearchBarsScreen extends StatefulWidget {
  const SearchBarsScreen({super.key});

  @override
  State<SearchBarsScreen> createState() => _SearchBarsScreenState();
}

class _SearchBarsScreenState extends State<SearchBarsScreen> {
  final searchController = SearchController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Text('Search view - full screen'),
          SearchAnchor.bar(
            suggestionsBuilder: (context, controller) {
              return List<ListTile>.generate(50, (int index) {
                final item = 'item ${index + 1}';
                return ListTile(
                  title: Text(item),
                  onTap: () {
                    setState(() => controller.closeView(item));
                  },
                );
              });
            },
          ),
          SearchAnchor(
            builder: (context, controller) {
              return IconButton.filledTonal(
                icon: Icon(Icons.search),
                onPressed: () {
                  controller.openView();
                },
              );
            },
            suggestionsBuilder: (context, controller) {
              return List<ListTile>.generate(50, (int index) {
                final item = 'item ${index + 1}';
                return ListTile(
                  title: Text(item),
                  onTap: () {
                    setState(() => controller.closeView(item));
                  },
                );
              });
            },
          ),
          Divider(),
          Text('Search view - docked'),
          SearchAnchor.bar(
            isFullScreen: false,
            suggestionsBuilder: (context, controller) {
              return List<ListTile>.generate(50, (int index) {
                final item = 'item ${index + 1}';
                return ListTile(
                  title: Text(item),
                  onTap: () {
                    setState(() => controller.closeView(item));
                  },
                );
              });
            },
          ),
          SearchAnchor(
            isFullScreen: false,
            searchController: searchController,
            builder: (context, controller) {
              return IconButton.filledTonal(
                icon: Icon(Icons.search),
                onPressed: () {
                  controller.openView();
                },
              );
            },
            suggestionsBuilder: (context, controller) {
              return List<ListTile>.generate(50, (int index) {
                final item = 'item ${index + 1}';
                return ListTile(
                  title: Text(item),
                  onTap: () {
                    setState(() => controller.closeView(item));
                  },
                );
              });
            },
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_1685365811](https://github.com/flutter/flutter/assets/102767277/82d485d7-09cc-4c59-a839-7c6542d3f445)

![Screenshot_1685365856](https://github.com/flutter/flutter/assets/102767277/534afdcc-5549-4e9d-bb4e-b8826553b5d6)

</details>

### Flutter Doctor output

<details>

<summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.11.0-14.0.pre.67, on Microsoft Windows [Version 10.0.22621.1702], locale ru-UA)
    • Flutter version 3.11.0-14.0.pre.67 on channel master at C:\Flutter-SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 87bc2193e6 (2 hours ago), 2023-05-29 07:26:24 -0400
    • Engine revision 91bc423843
    • Dart version 3.1.0 (build 3.1.0-155.0.dev)
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\yablo\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\yablo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.57

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-05-29 14:37
Reproducible on the latest `master` and `stable` channels.

<details> <summary> flutter doctor -v </summary>

```bash
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (3 weeks ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)    • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
```bash
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3 22E252 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.2 on channel stable at /Users/dammya/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (5 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)    • DCF2031A-7EA9-42FF-8CD4-D4584F3E7A6D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                •
      darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)              • chrome                               •
      web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Comment by bleroux** [comment] 2023-06-19 13:29
@MaxYablochkin Thanks for the detailed report
@dam-ease Thanks for confirming this.

`ListTile` ripple effect is not painted directly by each `ListTile` but on the parent `Material` widget.
This is not very intuitive but this works as intended and the solution in this particular example to wrap each `ListTile` on a `Material` (this is not done by defaut due to performance concerns: in some cases there might be hundreds of `ListTile`). See [ListTile documentation](https://api.flutter.dev/flutter/material/ListTile-class.html) for more information.

<details><summary>Updated code sample with Material widgets wrapping each ListTile</summary>
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true, brightness: Brightness.light),
      darkTheme: ThemeData(useMaterial3: true, brightness: Brightness.dark),
      home: SearchBarsScreen(),
    );
  }
}

class SearchBarsScreen extends StatefulWidget {
  const SearchBarsScreen({super.key});

  @override
  State<SearchBarsScreen> createState() => _SearchBarsScreenState();
}

class _SearchBarsScreenState extends State<SearchBarsScreen> {
  final searchController = SearchController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Text('Search view - full screen'),
          SearchAnchor.bar(
            suggestionsBuilder: (context, controller) {
              return List<Widget>.generate(50, (int index) {
                final item = 'item ${index + 1}';
                return Material(
                  type: MaterialType.transparency,
                  child: ListTile(
                    title: Text(item),
                    onTap: () {
                      setState(() => controller.closeView(item));
                    },
                  ),
                );
              });
            },
          ),
          SearchAnchor(
            builder: (context, controller) {
              return IconButton.filledTonal(
                icon: Icon(Icons.search),
                onPressed: () {
                  controller.openView();
                },
              );
            },
            suggestionsBuilder: (context, controller) {
              return List<Widget>.generate(50, (int index) {
                final item = 'item ${index + 1}';
                return Material(
                  type: MaterialType.transparency,
                  child: ListTile(
                    title: Text(item),
                    onTap: () {
                      setState(() => controller.closeView(item));
                    },
                  ),
                );
              });
            },
          ),
          Divider(),
          Text('Search view - docked'),
          SearchAnchor.bar(
            isFullScreen: false,
            suggestionsBuilder: (context, controller) {
              return List<Widget>.generate(50, (int index) {
                final item = 'item ${index + 1}';
                return Material(
                  type: MaterialType.transparency,
                  child: ListTile(
                    title: Text(item),
                    onTap: () {
                      setState(() => controller.closeView(item));
                    },
                  ),
                );
              });
            },
          ),
          SearchAnchor(
            isFullScreen: false,
            searchController: searchController,
            builder: (context, controller) {
              return IconButton.filledTonal(
                icon: Icon(Icons.search),
                onPressed: () {
                  controller.openView();
                },
              );
            },
            suggestionsBuilder: (context, controller) {
              return List<Widget>.generate(50, (int index) {
                final item = 'item ${index + 1}';
                return Material(
                  type: MaterialType.transparency,
                  child: ListTile(
                    title: Text(item),
                    onTap: () {
                      setState(() => controller.closeView(item));
                    },
                  ),
                );
              });
            },
          ),
        ],
      ),
    );
  }
}

```
</details>

**Comment by bleroux** [comment] 2024-08-12 07:02
Closing per https://github.com/flutter/flutter/issues/127794#issuecomment-1597198550

**Closed by bleroux** 2024-08-12 07:02 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.10, found in release: 3.11, team-design
