### ISSUE TITLE
Command gen-l10n generates files with flutter_lints 3 use_super_parameters rule warning

### ISSUE THREAD

**Issue by eshfield** [flutter/flutter#140787] opened 2024-01-02 06:30 UTC
### Steps to reproduce

1. Create a new Flutter project with `Empty Application` template
2. Add [standard internationalization packages](https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#setting-up):
```
 flutter pub add flutter_localizations --sdk=flutter
 flutter pub add intl:any
```
3. Create `l10n.yaml` in the project root directory with the following content:
```
arb-dir: lib/l10n
output-dir: lib/l10n/gen
output-localization-file: app_localizations.dart
synthetic-package: false
template-arb-file: app_en.arb

```
4. Add `app_en.arb` file to `lib/l10n`:
```
{
  "@@locale": "en",
  "greeting": "Hello!"
}
```
5. Run `flutter gen-l10n` command. It creates files `app_localizations_en.dart` and `app_localizations.dart` in the `lib/l10n/gen/` directory as we asked via `l10n.yaml` settings file
6. Update `flutter_lints` package from default `^2.0.0` to `>=3` version (`^3.0.1` in my case):
`flutter pub add dev:flutter_lints`
7.  Now we have a lint warning at the line `5` in the file `lib/l10n/gen/app_localizations_en.dart`:
```
import 'app_localizations.dart';

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale); // ← this one

  @override
  String get greeting => 'Hello!';
}

```
The warning says: `Convert 'locale' to a super parameter.`

### Expected results

I expect no lint warnings in the generated files.
If we run `dart fix --apply` than the problem line
```
AppLocalizationsEn([String locale = 'en']) : super(locale);
```
will change to:
```
AppLocalizationsEn([super.locale = 'en']);
```
That's an expected result

### Actual results

Violation of `use_super_parameters` rule in the generated file

### Code sample

Code sample is described in the `Steps to reproduce` section

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on Fedora Linux 39 (Workstation Edition)
    6.6.8-200.fc39.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-01-02 09:58
Closing this as a duplicate of https://github.com/flutter/flutter/issues/106150. 

Kinsly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-01-02 09:58 UTC
Labels: in triage
