### ISSUE TITLE
[Flutter Web] Dropdown does not respond to navigation key events (up/down arrow).

### ISSUE THREAD

**Issue by asmengistu** [flutter/flutter#75929] opened 2021-02-12 20:09 UTC
1. Create a simple dropdown widget. [Dartpad link](https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b)
2. Run it for web (either canvaskit or htmlkit)
3. Expand dialog button (either click with mouse or focus and hit space)
4. Try navigating through drop down items using keyboard.

**Expected results:** Keyboard navigation works. 🙂

**Actual results:** Keyboard navigation doesn't work. 😔

<details>
flutter doctor -v output:
```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.3 19D76 darwin-x64, locale en-US)
    • Flutter version 1.25.0-8.1.pre at /Users/abelsm/development/flutter
    • Framework revision 8f89f6505b (8 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/abelsm/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```
</details>

**Comment by darshankawar** [comment] 2021-02-15 07:31
@asmengistu 
You seem to be on older version of Beta. Can you upgrade to latest (1.26) and try again to see if you still get same behavior ?

**Comment by asmengistu** [comment] 2021-02-17 00:46
Yes, I still get the same behavior.

**Comment by darshankawar** [comment] 2021-02-17 05:55
@asmengistu 
Thanks for verifying. I believe there's similar open issue describing your case, https://github.com/flutter/flutter/issues/58494
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by asmengistu** [comment] 2021-02-17 07:14
Thanks @darshankawar.

I believe the issues are slightly different, this issue is being able to navigate the choices by using the up/down arrow keys. #58494 is about typing out keys to match an option. So both are issues with key events on dropdowns, but have significant differences. Maybe the other issues can be edited to also include navigation?

**Comment by darshankawar** [comment] 2021-02-17 11:45
Thanks @asmengistu for clarifying. Reopening.

**Comment by darshankawar** [comment] 2021-02-17 11:47
Verified sample dropdown using latest master and confirmed that unable to navigate through dropdown menu items using keyboard up down events / key.

<img width="680" alt="Screenshot 2021-02-17 at 5 11 33 PM" src="https://user-images.githubusercontent.com/67046386/108200012-d24de580-7143-11eb-88c1-97f1802957e9.png">

<details>
<summary>code sample</summary>

```
/// Flutter code sample for DropdownButton

// This sample shows a `DropdownButton` with a large arrow icon,
// purple text style, and bold purple underline, whose value is one of "One",
// "Two", "Free", or "Four".
//
// ![](https://flutter.github.io/assets-for-api-docs/assets/material/dropdown_button.png)

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

/// This is the stateful widget that the main application instantiates.
class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

/// This is the private State class that goes with MyStatefulWidget.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  String dropdownValue = 'One';

  @override
  Widget build(BuildContext context) {
    return DropdownButton<String>(
      value: dropdownValue,
      icon: Icon(Icons.arrow_downward),
      iconSize: 24,
      elevation: 16,
      style: TextStyle(color: Colors.deepPurple),
      underline: Container(
        height: 2,
        color: Colors.deepPurpleAccent,
      ),
      onChanged: (String newValue) {
        setState(() {
          dropdownValue = newValue;
        });
      },
      items: <String>['One', 'Two', 'Free', 'Four']
          .map<DropdownMenuItem<String>>((String value) {
        return DropdownMenuItem<String>(
          value: value,
          child: Text(value),
        );
      }).toList(),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.126, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
    • Flutter version 1.27.0-2.0.pre.126 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 50897c98fc (7 hours ago), 2021-02-16 20:13:53 -0800
    • Engine revision 9bcb3bfb0e
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment] 2021-02-17 12:15
Update: This seems to be specific to web, because on desktop (macOS), I was able to navigate through menu items using keyboard.

**Closed** 2021-02-24 22:08 UTC
Labels: assigned for triage, engine, f: material design, found in release: 1.27, framework, has reproducible steps, platform-web
