### ISSUE TITLE
Execution of the command buffer was aborted due to an error during execution.

### ISSUE THREAD

**Issue by mazhengshui** [flutter/flutter#121583] opened 2023-02-28 04:23 UTC
## Steps to Reproduce

1. When you start the app and scroll up the list, you find the app flash screen.

2. The list element contains the map sdk (google_maps_flutter

）

3. In the debug mode, when the app enters the home page, it quickly cuts out the app bug from the bottom, and the recurrence rate is very high.

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>

```
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)

```
</summary>

```
```

```


```

```

```

</details>
➜   flutter doctor -v

```

[✓] Flutter (Channel stable, 3.3.5, on macOS 13.2 22D49 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.5 on channel stable at /Users/**/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (4 months ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/**/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • 小马哥 (mobile)    • 00008020-00034C220A92002E • ios            • iOS 15.0 19A346
    • macOS (desktop) • macos                     • darwin-x64     • macOS 13.2 22D49 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

https://user-images.githubusercontent.com/16952456/221752951-a7c034d4-dd05-42bd-bad8-6522dfbc3b66.mp4

**Comment by darshankawar** [comment] 2023-02-28 08:17
@mazhengshui 
I believe you are hitting https://github.com/flutter/flutter/issues/100522, so please follow-up in that issue for further updates.
Closing this as a duplicate.

**Comment by zanderso** [comment] 2023-03-02 15:07
Based on the video, this is different from https://github.com/flutter/flutter/issues/100522 because it is the map plugin that is flickering rather than the Flutter rendered content.

@mazhengshui However, we are unlikely to be able to make progress on this issue without a small reproducible test case. Do you have a small example that shows this issue?

**Comment by mazhengshui** [comment] 2023-03-03 01:30
Sorry, this is an accidental problem. When trying to reproduce, the bug of the flash screen cannot be reproduced.

**Comment by zanderso** [comment] 2023-03-03 18:26
Closing based on the comment in https://github.com/flutter/flutter/issues/121583#issuecomment-1452804915

**Closed by zanderso** 2023-03-03 18:26 UTC
Labels: platform-ios, engine, severe: rendering, passed first triage
