### ISSUE TITLE
iOS scroll wheel support

### ISSUE THREAD

**Issue by Kavantix** [flutter/flutter#54663] opened 2020-04-13 14:09 UTC
When I connect a mouse to my iPad running iOS 13.4 I can scroll using the mouse wheel in native applications.
Flutter apps however don't seem to support this

**Comment by x4080** [comment] 2020-04-16 20:50
Yes, this will be very good for ipad pro with desktop features

**Comment by alexmarkley** [comment] 2020-09-19 22:06
Do we know how this issue affects iOS apps running on macOS 11 / Apple Silicon? ( Ref: https://github.com/flutter/flutter/issues/66184 ) If we're not sure, I am happy to test the behavior.

**Comment by alexmarkley** [comment] 2020-09-20 02:08
I can confirm this issue impacts Flutter iOS apps running on macOS 11 / Apple Silicon. (The issue is trivial to reproduce; simply add a ListView with a ton of children to the template project and launch it under Xcode using the "My Mac (Designed for iPad)" target.)

I propose that this issue be prioritized (other pointer features too, but especially scrolling support) because Apple is setting expectations with end users that they will be able to seamlessly run iOS and iPad apps directly on new Macs with Apple Silicon. Furthermore, Apple is **defaulting all iOS and iPad apps to be distributed in the Mac App Store** by the end of this year. Developers will have to explicitly opt-out if their app is not ready.

This situation, combined with Flutter's lack of scroll wheel support on a Mac, seems likely to cause a tidal wave of end users confused why they can't scroll on their favorite app. (The default behavior of "click and drag to scroll" is completely unintuitive on devices with a mouse or trackpad and no direct touch input.)

Please let me know if I can help. I'm happy to test experimental builds, but I'm also happy to write some patches if someone would be so kind as to _point_ (har har) me in the right direction.

**Comment by Kavantix** [comment] 2020-09-20 09:01
flutter/engine#19965 should implement this but it was closed because it was stale

**Comment by alexmarkley** [comment] 2020-09-21 22:23
@Kavantix Any idea what needs to be done to kickstart work on this? The pull request you linked to also seemed to have a range of issues that were not addressed, beyond just being stale.

Also, I grabbed a screen recording showing this issue on my WIP Flutter App (built today by Flutter stable) on macOS: https://youtu.be/vVbv064Hn70

As you can see, it's running using the iOS / iPad binary, installed directly on the Mac. You can see me clicking around the app and click/drag scrolling. What you cannot see is that I am trying to scroll up and down using my trackball's scroll ring, and there is no response within the app.

This is expected behavior given the current state of iPad pointer support in Flutter stable, but will not be expected by users who will be running these apps on their Macs around the end of this year.

**Comment by SoolyChristy** [comment] 2020-09-23 02:52
any progress?

**Comment by gw280** [comment] 2021-01-11 18:36
This is now fixed.

**Closed by gw280** 2021-01-11 18:36 UTC
Labels: a: fidelity, a: mouse, f: gestures, framework, platform-ios, severe: new feature
