### ISSUE TITLE
Potential UiKitView regression on master

### ISSUE THREAD

**Issue by csjames** [flutter/flutter#26750] opened 2019-01-18 11:09 UTC
I am using a `UiKitView` to integrate `Mapbox` Navigation into my application.

On tip of dev branch, this works completely fine and I am able to inflate a `UiKitView` widget configured to inflate a `NavigationViewController` + it's subview.

If I switch to master (which I need to use as it contains other critical fixes), the following debug is printed:
```
[VERBOSE-2:gpu_surface_gl.cc(42)] Could not make the context current to setup the gr context.
[VERBOSE-2:gpu_surface_gl.cc(274)] Could not make the context current to acquire the frame.
```
and the view is not shown inside its parent container widget. The voiceover from the satellite navigation continues to play in the background, indicating that the view has been successfully inflated, and is simply not being shown in the OpenGL canvas.

This issue does not effect other UiKitViews in my application

**Working Flutter Doctor Output**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14 18A391, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.30.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```
**Potentially Regressed Flutter Doctor Output**
```
[✓] Flutter (Channel master, v1.1.10-pre.117, on Mac OS X 10.14 18A391, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.30.1)
[✓] Connected device (1 available)
```

**Comment by zoechi** [comment] 2019-01-23 16:27
Closing as duplicate of #26966 because it has a reproduction project

**Closed by zoechi** 2019-01-23 16:27 UTC
Labels: a: existing-apps, a: platform-views, engine
