### ISSUE TITLE
invokeMethod didn't call result callbacks on ios 

### ISSUE THREAD

**Issue by karabanovbs** [flutter/flutter#136567] opened 2023-10-13 23:56 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Full example here: https://github.com/karabanovbs/ios_invoke_method_result/tree/main

I want get a result from dart function in ios native synchronous function. When i call it, dart function complete, but ios did't get a result and freeze.

### Expected results

invokeMethod result callback was called

### Actual results

invokeMethod result callback didn't called

### Code sample

<details><summary>Code sample</summary>

```dart
@pragma('vm:entry-point')
void getButtonName() {
  print("getButtonName");
  WidgetsFlutterBinding.ensureInitialized();

  const methodChannel = MethodChannel('com.example/foo');
  methodChannel.setMethodCallHandler((call) async {
    print(call);
    return 'Show Flutter';
  });
}
```

```swift
    func getButtonName() -> String {
        let flutterEngine = FlutterEngine(name: "getButtonName engine")
        
        flutterEngine.run(withEntrypoint: "getButtonName");
                
        var buttonName = ""
        
        let methodChannel = FlutterMethodChannel(name: "com.example/foo", binaryMessenger: flutterEngine.binaryMessenger)
        
        let group = DispatchGroup()
            group.enter()
        
        DispatchQueue.global(qos: .default).async {
            methodChannel.invokeMethod("getButtonName", arguments: nil) { result in
                buttonName = result as? String ?? ""
                group.leave()
            }
        }
        
        group.wait()
        return buttonName
    }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
2023-10-14 04:43:21.232803+0500 Runner[3122:1039396] Metal API Validation Enabled
2023-10-14 04:43:21.477963+0500 Runner[3122:1039396] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
2023-10-14 04:43:21.537354+0500 Runner[3122:1039396] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
2023-10-14 04:43:28.039625+0500 Runner[3122:1039696] flutter: getButtonName
2023-10-14 04:43:28.040251+0500 Runner[3122:1039696] flutter: MethodCall(getButtonName, null)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.2.1 22D68 darwin-arm64
    (Rosetta), locale en-AE)
    • Flutter version 3.13.6 on channel stable at
      /Users/boriskarabanov/fvm/versions/3.13.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/boriskarabanov/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/boriskarabanov/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/boriskarabanov/Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/boriskarabanov/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/boriskarabanov/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Users/boriskarabanov/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.9559.62/IntelliJ IDEA.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/boriskarabanov/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)            
    • iPad (Boris) (mobile) • 00008101-001954262E98001E • ios            • iOS
      16.6.1 20G81
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS
      13.2.1 22D68 darwin-arm64 (Rosetta)
    • Chrome (web)          • chrome                    • web-javascript •
      Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2023-10-14 01:14
> ios did't get a result and freeze.

It's frozen because the main thread is blocked by the `group.wait()` call, and platform channel call results are returned on the main thread; there is no wait for the callback passed to `invokeMethod` to ever be called in that code, because the thread it would be called on is blocked, preventing the runloop from running.

Also, while it is not the cause of the hang, calling `invokeMethod` from an arbitrary dispatch queue [violates the threading requirements of that API](https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading). Calling it from any thread other than the main thread has undefined behavior.

Closing as the bug here is in the provided code rather than Flutter. Platform channels do not allow synchronous use.

**Closed by stuartmorgan** 2023-10-14 01:14 UTC

**Comment by karabanovbs** [comment] 2023-10-14 01:21
@stuartmorgan Hi, can i wait result of invokeMethod synchronous? Which way is correct?
