### ISSUE TITLE
flutter google map can support the GeoJson URL in mobile app

### ISSUE THREAD

**Issue by MukeshWrms** [flutter/flutter#157156] opened 2024-10-18 10:21 UTC
### Use case

flutter google map can support the GeoJson URL in mobile app

I am using the google map on flutter but i need the GeoJson Url Pass on the google map.

other pub lib  is not work properly.

Please add on this feature on google map.  

### Proposal

[](url)
![368937232-9b974925-ff1a-45b2-a305-da51c3553588](https://github.com/user-attachments/assets/66d1ddfa-e9a7-488c-973a-f92c38cc9280)

**Comment by danagbemava-nc** [comment] 2024-10-18 11:03
Closing this as a duplicate of  https://github.com/flutter/flutter/issues/33514

Kindly follow up in the original issue for updates

Thank you

**Closed by danagbemava-nc** 2024-10-18 11:03 UTC
Labels: in triage
