### ISSUE TITLE
Error launching Flutter App - Permission denied @ dir_s_mkdir 

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#32977] opened 2019-05-18 20:09 UTC
This issue is very serious and has been reported in CocoaPods repo.

https://github.com/CocoaPods/CocoaPods/issues/7927

**Comment by azamsharp** [comment] 2019-05-18 20:22
When I downloaded flutter I saved it in the document location. 

~/Documents/development/flutter

**Comment by eseidelGoogle** [comment] 2019-05-22 16:14
I believe this is tracked as https://github.com/flutter/flutter/issues/19338 ?

**Comment by jmagman** [comment] 2020-02-12 02:52
That CocoaPods issue is closed with a comment "it does seem to be related to something that Flutter is doing" but I don't know what that could be.  This is a duplicate of https://github.com/flutter/flutter/issues/19338, which is closed because I couldn't get more information and the crash location moved

Are you still this or a similar issue on CocoaPods >1.6.0 since that's the new minimum, and CocoaPods no longer will crash in the same place?

See https://github.com/flutter/flutter/issues/19338#issuecomment-503776123

**Comment by jmagman** [comment] 2020-03-06 03:09
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-03-06 03:09 UTC
Labels: tool, waiting for customer response, ⌺‬ platform-ios
