### ISSUE TITLE
Firestore: snapshot.hasData has a null value instead of false or true

### ISSUE THREAD

**Issue by ram231** [flutter/flutter#22199] opened 2018-09-24 03:51 UTC
## Steps to Reproduce
For instance, I have a StreamBuilder to query a collection in Firestore
```dart
StreamBuilder(
                            stream: Firestore.instance
                                .collection('myCollection')
                                .snapshots(),
                            builder: (context, snapshot) {
                              if (!snapshot.hasData) return Text("Loading"); // This will return either true or false??
                              return ListView.builder( //my hidden code);

```

1.  
`I/flutter (32146): Another exception was thrown: NoSuchMethodError: The getter 'documents' was called on null.` The Document was called on null, then in a split second, the data is shown. I have no widget to replace the red screen of error. 
2. ` if(!snapshot.hasData && snapshot.data.documents == null) return Text("Loading")` and still getting a redscreen, later on will disappear in a split second.

## Logs

```
flutter doctor -v
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-PH)
    • Flutter version 0.8.2 at D:\flutter-beta\flutter
    • Framework revision 5ab9e70727 (2 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Clueless\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.26.0)
    • VS Code at C:\Users\Clueless\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • myX8 • MYPHONEMYX803629 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

flutter analyze
```
No issues found. 
```

```
flutter doctor -v
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-PH)
    • Flutter version 0.8.2 at D:\flutter-beta\flutter
    • Framework revision 5ab9e70727 (2 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Clueless\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.26.0)
    • VS Code at C:\Users\Clueless\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • myX8 • MYPHONEMYX803629 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by alanrussian** [comment] 2018-09-26 04:00
To solve 1, you would have to pass in some initialData to the StreamBuilder. Without initialData, there will always be a frame rendered without data. 

To solve 2, I think you want an *or* not an *and* operator there? 

I don't think it's possible for `snapshot.hasData` to ever be null.

**Comment by zoechi** [comment] 2018-09-26 08:14
Actually I think this code is expected to cause this exception
```dart
if(!snapshot.hasData && snapshot.data.documents == null)
```
If `!snapshot.hasData` is `true` `snapshot.data` is expected to be `null` and `snapshot.data.documents == null` to cause the exception. 

Perhaps you meant

```dart
if(!snapshot.hasData || snapshot.data.documents == null)
```

**Comment by zoechi** [comment] 2018-12-11 12:15
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-12-11 12:15 UTC
Labels: p: firebase, p: first party, severe: crash

**Comment by FilipeOS** [comment] 2019-06-26 16:40
I'm having the same issue and don't know how to fix it...

I have a StreamBuilder that gets all the users snapshots that are friends, if the user don't have friends = subcollection don't exist or is empty (without documents).

The problem is that it's assuming that `snapshot.hasData` is always true.

@zoechi can you please advise? Your last messages don't fix.

It should only return `snapshot.hasData` when the collection exist or there's documents inside it.

**Comment by FilipeOS** [comment] 2019-06-26 21:40
Fixed by using `snapshot.data.documents.length > 0` and not `snapshot.hasData`

**Comment by SilasPaes** [comment] 2019-09-02 06:13
I have same problem, when document is empty, return error. what do I do?
my code: 
StreamBuilder(
      stream: Firestore.instance
                .collection("testando").document(widget.suid) 
                .collection(widget.uid).document(widget.uid)
                .snapshots(),
                //initialData: ,
      builder: (context, snapshot) {        
        if (!snapshot.hasData||
          snapshot.connectionState == ConnectionState.waiting) {
            return CircularProgressIndicator(); 
        }
        if (snapshot.hasData ){       
        return GestureDetector(       
                      child: 
                      snapshot.data['isLiked']                      
                          ? Icon(
                              Icons.favorite,
                              color: Colors.red,
                            )
                          : Icon(
                              FontAwesomeIcons.heart,
                              color: null,
                            ),
                      onTap: () {
                        if (!snapshot.data['isLiked']) {
                          setState(()  {
  Firestore.instance
        .collection('testando')
        .document(widget.suid).collection(widget.uid).document(widget.uid)
        .setData({'contador': FieldValue.increment(1),
        'uid': widget.uid,
        'isLiked': true, 
        });
        
        snapshot.data['isLiked'] = true;
                 });  
                        } else {
                          setState(()  {                            
  Firestore.instance
        .collection('testando')
        .document(widget.suid).collection(widget.uid).document(widget.uid)
        .setData({'contador': FieldValue.increment(-1),
        'uid': widget.uid,
        'isLiked': false, 
        });
        snapshot.data['isLiked'] = false;                
                          });        
                        }
                        }
);
        }
      }),

**Comment by kroikie** [comment] 2019-10-13 18:49
@ram231

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/649. Any further collaboration will be done there.

**Comment by Vasanth-Korada** [comment] 2020-04-09 18:02
Worked this way!

if (!snapshot.hasData || snapshot.data.documents.isEmpty){
.....
}
