### ISSUE TITLE
Scrolling Performance Degradation in Flutter ListView Builder

### ISSUE THREAD

**Issue by Tamilarasan-Paranthaman** [flutter/flutter#114809] opened 2022-11-07 13:09 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample (Platform-->`Windows`)
2. Scroll vertically through the `Scrollbar`

**Expected results:** The ListView should scroll without any delay

**Actual results:** The scrolling is not smooth when continuously scrolling vertically.
<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: "ListView Builder",
        theme: ThemeData(primarySwatch: Colors.blue),
        debugShowCheckedModeBanner: false,
        home: const ListViewBuilder());
  }
}

class ListViewBuilder extends StatelessWidget {
  const ListViewBuilder({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("ListView Builder")),
      body: ListView.builder(
          itemCount: 4000,
          itemBuilder: (BuildContext context, int index) {
            return SizedBox(
              height: 400,
              child: ListTile(
                  title: Text(
                      "$index Flutter is an open source framework by Google for building beautiful, natively compiled, multi-platform applications from a single codebase. Flutter code compiles to ARM or Intel machine code as well as JavaScript, for fast performance on any device")),
            );
          }),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.19043.2006], locale en-IN)
    • Flutter version 3.3.6 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (13 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio new
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.73.0)
    • VS Code at C:\Users\TamilarasanParantham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.2006]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.26

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details>
  <summary>Output</summary>

https://user-images.githubusercontent.com/93904422/200317068-a81b195a-d183-4e74-8863-de8b80cedfb2.mp4

</details>

**Comment by knopp** [comment] 2022-11-07 13:22
This is a known issue with how SliverList calculates layout. If ListView has fixed extent, like in your example, can specify the extent in ListView constructor and it should fix the issue (i.e. `itemExtent=400,`).

For large lists with dynamic extents you can try using something like [`super_sliver_list`](https://pub.dev/packages/super_sliver_list). Though you will need to use CustomScroll view for that and it's quite experimental.

**Comment by knopp** [comment] 2022-11-07 13:48
Closing as duplicate of https://github.com/flutter/flutter/issues/52207.

**Closed by knopp** 2022-11-07 13:48 UTC
