### ISSUE TITLE
Flutter Web TextField with autofill: Error: LateInitializationError: Local 'command' has not been initialized.

### ISSUE THREAD

**Issue by g-adorni** [flutter/flutter#83724] opened 2021-06-01 17:19 UTC
Today i upgraded flutter 2.2.1 but with Web it throws Exception when a TextField with autofillHints has focus. If i downgrade to flutter 2.2 or use Android there are no problems.
I tried the sample project in https://api.flutter.dev/flutter/widgets/AutofillGroup-class.html but it's the same.

## Steps to Reproduce

1. Create sample project with flutter create --sample=widgets.AutofillGroup.1 mysample
2. flutter run -d chrome
3. Click on any TextField or focus them with Tab

<details>
  <summary>Logs</summary>

```
[+13474 ms] Error: LateInitializationError: Local 'command' has not been initialized.
                         at Object.throw_ [as throw] (http://localhost:51030/dart_sdk.js:5041:11)
                         at command$35get (http://localhost:51030/dart_sdk.js:170859:41)
                         at _engine.TextEditingChannel.new.handleTextInput (http://localhost:51030/dart_sdk.js:170936:41)
                         at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:51030/dart_sdk.js:157234:39)
                         at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:51030/dart_sdk.js:157101:33)
                         at _DefaultBinaryMessenger.[_sendPlatformMessage]
(http://localhost:51030/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
                         at _DefaultBinaryMessenger.send
(http://localhost:51030/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
                         at OptionalMethodChannel._invokeMethod
(http://localhost:51030/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
                         at _invokeMethod.next (<anonymous>)
                         at runBody (http://localhost:51030/dart_sdk.js:37422:34)
                         at Object._async [as async] (http://localhost:51030/dart_sdk.js:37453:7)
                         at OptionalMethodChannel.[_invokeMethod]
(http://localhost:51030/packages/flutter/src/services/system_channels.dart.lib.js:936:20)
                         at OptionalMethodChannel.[_invokeMethod]
(http://localhost:51030/packages/flutter/src/services/system_channels.dart.lib.js:1059:34)
                         at OptionalMethodChannel.invokeMethod
(http://localhost:51030/packages/flutter/src/services/system_channels.dart.lib.js:1039:36)
                         at invokeMethod.next (<anonymous>)
                         at runBody (http://localhost:51030/dart_sdk.js:37422:34)
                         at Object._async [as async] (http://localhost:51030/dart_sdk.js:37453:7)
                         at OptionalMethodChannel.invokeMethod
(http://localhost:51030/packages/flutter/src/services/system_channels.dart.lib.js:1038:20)
                         at text_input.TextInput.__.[_requestAutofill]
(http://localhost:51030/packages/flutter/src/services/text_input.dart.lib.js:1315:22)
                         at text_input.TextInputConnection.__.requestAutofill
(http://localhost:51030/packages/flutter/src/services/text_input.dart.lib.js:1060:55)
                         at editable_text.EditableTextState.new.[_openInputConnection]
                         (http://localhost:51030/packages/flutter/src/widgets/widget_span.dart.lib.js:45128:56)
                         at editable_text.EditableTextState.new.[_openOrCloseInputConnectionIfNeeded]
                         (http://localhost:51030/packages/flutter/src/widgets/widget_span.dart.lib.js:45150:37)
                         at editable_text.EditableTextState.new.[_handleFocusChanged]
                         (http://localhost:51030/packages/flutter/src/widgets/widget_span.dart.lib.js:45358:50)
                         at focus_manager.FocusNode.new.notifyListeners
(http://localhost:51030/packages/flutter/src/foundation/change_notifier.dart.lib.js:106:41)
                         at focus_manager.FocusNode.new.[_notify]
(http://localhost:51030/packages/flutter/src/widgets/widget_span.dart.lib.js:48239:12)
                         at focus_manager.FocusManager.new.[_applyFocusChange]
(http://localhost:51030/packages/flutter/src/widgets/widget_span.dart.lib.js:48969:26)
                         at Object._microtaskLoop (http://localhost:51030/dart_sdk.js:37526:13)
                         at _startMicrotaskLoop (http://localhost:51030/dart_sdk.js:37532:13)
                         at http://localhost:51030/dart_sdk.js:33303:9
```

```
Analyzing mysample...                                                   
No issues found! (ran in 4.6s)
```

```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Versione 10.0.19041.985], locale it-IT)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (5 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Gabor\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\Gabor\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
```

</details>

**Comment by stx** [comment] 2021-06-01 17:36
https://github.com/flutter/flutter/issues/83618

**Comment by TahaTesser** [comment] 2021-06-02 10:53
Closing as duplicate of https://github.com/flutter/flutter/issues/83618

**Closed by TahaTesser** 2021-06-02 10:53 UTC
Labels: in triage
