### ISSUE TITLE
flutter run crashed

### ISSUE THREAD

**Issue by ijt** [flutter/flutter#50744] opened 2020-02-13 19:02 UTC
## Steps to Reproduce

1. `flutter create crash`
2. `cd crash`
3. `sed -i.bak 's/FLUTTER_BUILD_NAME/MARKETING_VERSION/' ios/Runner/Info.plist`
4. `flutter run -d $some_ios_device`

```
Launching lib/main.dart on iPhone 8 in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           6.3s
 └─Compiling, linking and signing...                         5.7s
Xcode build done.                                           13.3s

Sending crash report to Google.
Crash report sent (report ID: 252d15f09024e23d)
Oops; flutter has exited unexpectedly.
Crash report written to /private/tmp/crash/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

## Logs

/private/tmp/crash/flutter_01.log:
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d 18CC5E7D-255D-4967-AD8C-41F742B318C2

## exception

ProcessException: ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleShortVersionString.
Ensure your bundle contains a CFBundleShortVersionString.
  Command: /usr/bin/xcrun simctl install 18CC5E7D-255D-4967-AD8C-41F742B318C2 /private/tmp/crash/build/ios/iphonesimulator/Runner.app


#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      SimControl.install (package:flutter_tools/src/ios/simulators.dart:148:29)
#3      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:454:31)
<asynchronous suspension>
#4      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:354:15)
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#15     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#25     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#27     _rootRunUnary (dart:async/zone.dart:1134:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#33     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#34     _rootRun (dart:async/zone.dart:1126:13)
#35     _CustomZone.run (dart:async/zone.dart:1023:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#38     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#40     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor -v

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/issactrotts/Downloads/flutter
    • Framework revision 0b8abb4724 (2 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/issactrotts/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/issactrotts/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Issac’s iPad • df3231597eaa32ea3a2fc564ee6fb64c01587d52 • ios • iOS 13.3.1
    • iPhone 8     • 18CC5E7D-255D-4967-AD8C-41F742B318C2     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-02-14 10:42
Duplicate of [#50744](https://github.com/flutter/flutter/issues/50744)

**Closed by TahaTesser** 2020-02-14 10:42 UTC
Labels: framework, severe: crash, ⌺‬ platform-ios
