### ISSUE TITLE
Low priority of recipe-led-tests builders causes TIMED_OUT

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#67741] opened 2020-10-09 16:04 UTC
Now `recipe-led-tests` is with a lower priority when scheduling builders, and this will cause TIMED_OUT:
https://ci.chromium.org/p/flutter/builders/try/recipes-with-led/b8866966661549953824?
https://chromium-swarm.appspot.com/task?id=4f234cd1eda1ad10&o=true&w=true

**Comment by godofredoc** [comment] 2020-10-15 22:28
@mohrr do you know why we get different priorities from the led-tests?

**Comment by mohrr** [comment] 2020-10-15 23:50
See http://crbug.com/438394. Basically this is by design in led, but they're open to options to change it. I fixed it in Fuchsia with https://fuchsia-review.googlesource.com/c/infra/recipes/+/438394.

**Comment by godofredoc** [comment] 2020-10-16 00:25
Does the -10 needs to get decreased to -20? the original builds have a priority of 30 but the ones triggered by led tests have a priority of 40.

As your change is in the recipe module flutter recipe led tests should be already using your change.

**Comment by mohrr** [comment] 2020-10-16 02:10
My change went into Fuchsia after this issue was filed. It's probably no longer an issue for you.

**Comment by godofredoc** [comment] 2020-10-16 18:38
ok, I'll fork the module to flutter recipes to give it a try

**Comment by godofredoc** [comment] 2021-04-23 21:16
I haven't seen this issue in a very long time. Closing as obsolete.

**Closed by godofredoc** 2021-04-23 21:16 UTC
Labels: P3, passed first triage, passed secondary triage, team: infra
