### ISSUE TITLE
_getSemanticsForParent should cache result for smoother scrolling

### ISSUE THREAD

**Issue by michael4snupps** [flutter/flutter#28204] opened 2019-02-20 13:08 UTC
Using Observatory to profile our app, we identified the code path through `_getSemanticsForParent` as the most significant use of CPU when scrolling a complex "infinite scroll" ListView.

After reviewing the code in `src/rendering/object.dart` it appears that this computation is largely redundant, and the results could safely be cached.  After applying the following patch, the frame render time reduced from 8-16ms/frame to 1-2ms/frame, and garbage collections were greatly reduced as well.

There may be other issues with this particular patch, but it's working very well for us at the moment.

```
diff --git a/packages/flutter/lib/src/rendering/object.dart b/packages/flutter/lib/src/rendering/object.dart
index a96ae36d1..74df42cba 100644
--- a/packages/flutter/lib/src/rendering/object.dart
+++ b/packages/flutter/lib/src/rendering/object.dart
@@ -2299,6 +2299,7 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
 
   bool _needsSemanticsUpdate = true;
   SemanticsNode _semantics;
+  _SemanticsFragment _parentSemanticsFragment = null;
 
   /// The semantics of this render object.
   ///
@@ -2327,6 +2328,7 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
   void clearSemantics() {
     _needsSemanticsUpdate = true;
     _semantics = null;
+    _parentSemanticsFragment = null;
     visitChildren((RenderObject child) {
       child.clearSemantics();
     });
@@ -2339,6 +2341,7 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
   /// any way to update the semantics tree.
   void markNeedsSemanticsUpdate() {
     assert(!attached || !owner._debugDoingSemantics);
+    _parentSemanticsFragment = null;
     if (!attached || owner._semanticsOwner == null) {
       _cachedSemanticsConfiguration = null;
       return;
@@ -2391,6 +2394,7 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
   /// Updates the semantic information of the render object.
   void _updateSemantics() {
     assert(_semanticsConfiguration.isSemanticBoundary || parent is! RenderObject);
+    _parentSemanticsFragment = null;
     if (_needsLayout) {
       // There's not enough information in this subtree to compute semantics.
       // The subtree is probably being kept alive by a viewport but not laid out.
@@ -2417,6 +2421,10 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
     assert(mergeIntoParent != null);
     assert(!_needsLayout, 'Updated layout information required for $this to calculate semantics.');
 
+    if (_parentSemanticsFragment != null) {
+      return _parentSemanticsFragment;
+    }
+
     final SemanticsConfiguration config = _semanticsConfiguration;
     bool dropSemanticsOfPreviousSiblings = config.isBlockingSemanticsOfPreviouslyPaintedNodes;
 
@@ -2508,6 +2516,8 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
 
     result.addAll(fragments);
 
+    _parentSemanticsFragment = result;
+
     return result;
   }
 
```

**Comment by JaspervanRiet** [comment] 2019-08-31 15:39
We're seeing this problem impact all of our more complex lists, using the `ExcludeSemantics` widget has taken some of our performance from ~35 FPS to almost perfect 60. That's obviously pretty terrible since that removes all Semantics.

**Comment by filiph** [comment] 2019-09-09 16:27
Hi @JaspervanRiet, @michael4snupps,

Is there a simple reproduction for this performance issue? This would be great to add to [the benchmarks](https://flutter-dashboard.appspot.com/benchmarks.html).

**Comment by JaspervanRiet** [comment] 2019-09-11 14:02
@filiph The following code with arbitrarily complex list items (which are similar in complexity to the list items we have in our actual app) is unable to maintain 60 FPS. Using ExcludeSemantics increases performance:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _page = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: NotificationListener(
        onNotification: (Notification notification) {
          if (notification is ScrollNotification) {
            if (notification.metrics.extentAfter == 0) {
              Future.delayed(const Duration(seconds: 2)).then((_) {
                print("Loading a new page!");
                setState(() {
                  _page++;
                });
              });
            }
          }
          return true;
        },
        child: CustomScrollView(
          slivers: <Widget>[
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (BuildContext context, int index) {
                  return _ListItem();
                },
                childCount: 10 + 10 * _page,
              ),
            ),
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.all(20),
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _ListItem extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ExcludeSemantics(
      child: Container(
        margin: const EdgeInsets.all(10),
        padding: const EdgeInsets.all(10),
        decoration: BoxDecoration(
          color: Colors.white,
          boxShadow: [
            BoxShadow(
              color: Colors.black,
              offset: Offset(0, 1),
              blurRadius: 5,
            ),
          ],
          borderRadius: BorderRadius.all(Radius.circular(15)),
        ),
        child: Column(
          children: <Widget>[
            Container(
              color: Colors.red,
              height: 20,
            ),
            new Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text("Test",
                    style: TextStyle(color: Colors.black, fontSize: 15)),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  color: Colors.blue,
                  child: Text("Test",
                      style: TextStyle(color: Colors.black, fontSize: 20)),
                ),
                Image.network(
                  'https://picsum.photos/250?image=9',
                  height: 20,
                  width: 20,
                ),
                Image.network(
                  'https://picsum.photos/250?image=8',
                  height: 20,
                  width: 20,
                ),
                Text("Test",
                    style: TextStyle(color: Colors.black, fontSize: 15)),
              ],
            ),
            Row(
              children: <Widget>[
                Column(
                  children: <Widget>[
                    Container(
                      color: Colors.green,
                      height: 30,
                      width: 30,
                    ),
                    Container(
                      color: Colors.yellow,
                      height: 30,
                      width: 30,
                    ),
                  ],
                ),
                Expanded(
                  child: Text(
                      "This is a long piece of text. Is it though? I'm not sure it is quite long enough"),
                ),
                FlatButton(
                  child: Text("A button"),
                  onPressed: () {
                    print("Pressed");
                  },
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by filiph** [comment] 2019-09-11 16:44
Thanks you @JaspervanRiet, this is great!

**Comment by goderbauer** [comment] 2019-09-11 17:14
@michael4snupps @JaspervanRiet do you have any accessibility services enabled on your phone? We only generate the semantics tree if the platform asks for it (e.g. because an accessibility services needs it). An a11y service can also be something that is not necessarily associated with accessibility like tools that automate certain things on your phone.

When semantics tree generation is turned on, a certain performance cost is expected. However, we have never performance-optimized that code, so there may be some low hanging performance optimizing options in there.

**Comment by JaspervanRiet** [comment] 2019-09-11 17:39
@goderbauer I personally have a password manager enabled with accessibility services for autofill. However, our app is in use by a number of testers in addition to our dev team, and even among users who did not have any accessibility services enabled (I just checked with them to verify) the change to exclude semantics made a noticeable difference.

We have a decently advanced performance testing mechanisms set up using integration tests. I could quite easily have it run the commit before and the commit after the change with accessibility services enabled and disabled to see if ExcludeSemantics truly did make a difference in performance for users with all services disabled.

**Comment by JaspervanRiet** [comment] 2019-09-11 17:42
Also, considering the prevalence of accessibility for things like password managers, I think a performance drop of almost 50% in scrolling performance (as described in my first post on this issue) is significant.

**Comment by goderbauer** [comment] 2019-09-12 00:30
The caching mechanism suggested in the first post doesn't look sufficient because Fragments returned by `_getSemanticsForParent` are mutated by the caller of the function. That mutates the cached value and next time `_getSemanticsForParent` gets called the mutated value is returned (the mutation may no longer be valid, though).

There are probably other performance improvements that can be made though.

**Comment by liyuqian** [comment] 2019-11-21 01:04
The improvement does seem to be very significant. @goderbauer : is there a solution that can solve your concern in https://github.com/flutter/flutter/issues/28204#issuecomment-530616318 ?

**Comment by liyuqian** [comment] 2020-03-16 22:04
Gentle ping for @goderbauer

**Comment by kf6gpe** [comment] 2020-04-13 21:41
Another gentle ping for @goderbauer.

**Comment by goderbauer** [comment] 2020-04-13 21:48
We currently don't have any immediate plans to work on this. It is not clear that this will give us the biggest bang for the bug in terms of a11y performance. However, if somebody wants to work on it: Happy to review PRs.

**Comment by kf6gpe** [comment] 2020-05-04 21:47
Moving to Stretch Goals as we don't have any immediate plans to work on this.

**Comment by SwissCheese5** [comment] 2020-10-16 08:53
I just had this issue pop up on my end as well.
Significant points:
![image](https://user-images.githubusercontent.com/7407478/96235173-1e74f780-0fa3-11eb-8992-4e0a47933cf8.png)
![image](https://user-images.githubusercontent.com/7407478/96236038-34cf8300-0fa4-11eb-8cff-2c38c2aa9a01.png)
Half of this flamechart is dominated by semantics. It's a list of lists of lists, but it's limited to 30 items max. It's not a massive tree of widgets, but they are complex. Think of a reddit comment chain.

The CPU and GPU perform well, but there is VERY clear jank when scrolling on lists that hold complex widgets.
I did some debugging and found that this code  I have here, if commented out, will immediately resolve all the jank I have when scrolling:
```dart
class BottomRow extends StatefulWidget {
  final Branch branch;
  final Chunk chunk;
  final bool spotlight;
  final Color color;
  final Function(bool) onCollapse;

  const BottomRow(
      {Key key,
      @required this.branch,
      @required this.spotlight,
      @required this.chunk,
      @required this.color,
      @required this.onCollapse})
      : super(key: key);

  @override
  _BottomRowState createState() => _BottomRowState();
}

class _BottomRowState extends State<BottomRow> {
  bool voting = false;
  bool collapsed = false;
  bool saving = false;

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.center,
      mainAxisAlignment: MainAxisAlignment.end,
      children: [
        if (widget.branch.saved != null && widget.branch.saved > 0)
          Text('${widget.branch.saved}',
              style: Theme.of(context).textTheme.subtitle2.copyWith(
                    color: Theme.of(context).accentColor.withOpacity(0.5),
                  )),
        if (widget.branch.saved != null && widget.branch.saved > 0)
          Icon(
            Icons.star,
            color: Theme.of(context).accentColor.withOpacity(0.5),
          ),
        IconButton(
            icon: Icon(Icons.thumb_up,
                color: voting
                    ? Theme.of(context).disabledColor
                    : (widget.branch?.upvotes?.contains(
                                FirebaseAuth.instance.currentUser.uid) ??
                            false)
                        ? Theme.of(context).accentColor
                        : Theme.of(context).iconTheme.color),
            splashRadius: 20,
            iconSize: 20,
            onPressed: widget.branch == null || voting
                ? null
                : () {
                    setState(() {
                      voting = true;
                      widget.branch
                          .upvote()
                          .then((_) => setState(() => voting = false));
                    });
                  }),
        AnimatedSwitcher(
          duration: const Duration(milliseconds: 500),
          switchInCurve: Curves.easeOutQuint,
          switchOutCurve: Curves.easeOutQuint,
          transitionBuilder: (child, animation) =>
              ScaleTransition(scale: animation, child: child),
          child: voting
              ? SizedBox(
                  width: Theme.of(context).textTheme.subtitle2.fontSize,
                  height: Theme.of(context).textTheme.subtitle2.fontSize,
                  child: CircularProgressIndicator())
              : Text(
                  '${(widget.branch?.upvotes?.length ?? 0) - (widget.branch?.downvotes?.length ?? 0)}',
                  style: Theme.of(context).textTheme.subtitle2),
        ),
        if (!widget.spotlight)
          IconButton(
              icon: Icon(Icons.thumb_down,
                  color: voting
                      ? Theme.of(context).disabledColor
                      : (widget.branch?.downvotes?.contains(
                                  FirebaseAuth.instance.currentUser.uid) ??
                              false)
                          ? Theme.of(context).accentColor
                          : Theme.of(context).iconTheme.color),
              splashRadius: 20,
              iconSize: 20,
              onPressed: widget.branch == null || voting
                  ? null
                  : () {
                      setState(() {
                        voting = true;
                        widget.branch
                            .downvote()
                            .then((_) => setState(() => voting = false));
                      });
                    }),
        if (!widget.spotlight)
          IconButton(
              icon: const Icon(Icons.reply),
              splashRadius: 20,
              iconSize: 20,
              onPressed: widget.branch == null
                  ? null
                  : () {
                      Navigator.of(context)
                          .push(MaterialPageRoute(
                              builder: (context) => ReplyPage(
                                  branch: widget.branch,
                                  chunk: widget.chunk,
                                  color: widget.color)))
                          .whenComplete(() {});
                    }),
        if (!widget.spotlight &&
            widget.branch.userId != FirebaseAuth.instance.currentUser.uid)
          BlocBuilder<UserCubit, KUser>(builder: (context, user) {
            return AnimatedSwitcher(
              duration: const Duration(milliseconds: 500),
              switchInCurve: Curves.easeOutQuint,
              switchOutCurve: Curves.easeOutQuint,
              transitionBuilder: (child, animation) =>
                  ScaleTransition(scale: animation, child: child),
              child: saving
                  ? SizedBox(
                      width: Theme.of(context).textTheme.subtitle2.fontSize,
                      height: Theme.of(context).textTheme.subtitle2.fontSize,
                      child: CircularProgressIndicator())
                  : IconButton(
                      icon: Icon(user.saved.containsKey(widget.branch.branchId)
                          ? Icons.star
                          : Icons.star_border),
                      splashRadius: 20,
                      iconSize: 20,
                      onPressed: widget.branch == null || saving
                          ? null
                          : () {
                              setState(() {
                                saving = true;
                                if (user.saved
                                    .containsKey(widget.branch.branchId)) {
                                  widget.branch.unsave().then(
                                      (_) => setState(() => saving = false));
                                } else {
                                  widget.branch.save().then(
                                      (_) => setState(() => saving = false));
                                }
                              });
                            }),
            );
          }),
        if (widget.branch?.children?.isNotEmpty ?? false)
          IconButton(
              icon: Icon(!collapsed ? Icons.unfold_less : Icons.unfold_more,
                  color: collapsed
                      ? Theme.of(context).accentColor
                      : Theme.of(context).iconTheme.color),
              splashRadius: 20,
              iconSize: 20,
              onPressed: () {
                setState(() {
                  collapsed = !collapsed;
                  widget.onCollapse(collapsed);
                });
              }),
        if (!widget.spotlight)
          IconButton(
              icon: const Icon(Icons.more_vert),
              splashRadius: 20,
              iconSize: 20,
              onPressed: () {
                showDialog(
                    context: context,
                    builder: (context) {
                      return OptionsDialog(
                          branch: widget.branch,
                          chunk: widget.chunk,
                          color: widget.color);
                    });
              }),
      ],
    );
  }
}
```

It's trying to paint this bottom row of IconButtons here:
![image](https://user-images.githubusercontent.com/7407478/96235686-bffc4900-0fa3-11eb-9742-cb95f570e6a7.png)


After wrapping this BottomRow with ExcludeSemantics, my scrolling jank is gone. But the milliseconds it takes for semantics to build is still high somehow.
![image](https://user-images.githubusercontent.com/7407478/96236835-35b4e480-0fa5-11eb-9c40-d98c5408213b.png)
![image](https://user-images.githubusercontent.com/7407478/96236854-3c435c00-0fa5-11eb-9122-36381e1cfe02.png)

And it still takes up half the flamechart.
So it seems semantics is taking up performance SOMEWHERE, but the GPU and CPU aren't reporting any frames being rendered over 16 ms in either case.

**Comment by ketan-jainn** [comment] 2021-08-23 11:38
Why this is listed as p5 when there is a performance issue due to this bug?

**Comment by sgehrman** [comment] 2021-09-12 21:32
I'm seeing this too.  Ping.

**Comment by vysakhrj** [comment] 2021-11-03 18:42
Moving to a higher priority will be useful😐

**Comment by nabil6391** [comment] 2022-08-07 22:49
Would love to get an update about this improvement

**Comment by darshankawar** [comment] 2024-04-10 10:59
Revisited this issue and ran the [sample code](https://github.com/flutter/flutter/issues/28204#issuecomment-530394886) provided on Samsung S10 device (Android 12) using latest stable version (3.19.5) and observed that the scrolling on the device was smooth and there were not huge amount of performance jank as shown in below video:


https://github.com/flutter/flutter/assets/67046386/2b204317-132f-4448-bfc2-6bc00d28cf21

@michael4snupps or others in this thread facing this issue before, can anyone confirm if the originally reported issue still occurs at your end ?

**Closed** 2024-05-01 11:08 UTC
Labels: waiting for customer response, framework, c: performance, a: accessibility, f: scrolling, a: quality, customer: crowd, a: annoyance, perf: speed, has reproducible steps, P3, found in release: 1.22, team-framework, triaged-framework
