### ISSUE TITLE
Shift to SPM and stop using cocoapods

### ISSUE THREAD

**Issue by j-h-a** [flutter/flutter#139567] opened 2023-12-05 15:57 UTC
Cocoapods is an archaic dependency management system, and it's really not needed any more for iOS and macOS development. I suspect there are a few old unmaintained packages that still haven't added SPM support, but I think most apps and their dependencies these days can be built entirely without it (I managed to finally eliminate it from my workflow over 3 years ago).

There are flutter packages, like `url_launcher` for example, that really don't need to introduce cocoapods to the build environment. Is there any existing discussion or effort to remove the need for cocoapods on more and more packages over time (especially the core ones) until it can be removed from the workflow entirely?

This seems like it would be a worthwhile initiative to me. How can I learn more?

**Comment by stuartmorgan** [comment] 2023-12-05 15:59
Closing as a duplicate of https://github.com/flutter/flutter/issues/33850

**Closed by stuartmorgan** 2023-12-05 15:59 UTC
