### ISSUE TITLE
Gradle build fails after Flutter Upgrade 

### ISSUE THREAD

**Issue by NoEnigmas** [flutter/flutter#20511] opened 2018-08-13 00:27 UTC
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.gms:play-services-tasks' has different version for the compile (11.8.0) and runtime (15.0.1) classpath. You should manually set the same version via DependencyResolution

-----------------------------------------------------------------------------------------------------------
```
Microsoft Windows [Version 10.0.17134.165]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\FlutterProjects\wait_not>flutter doctor -v
[√] Flutter (Channel dev, v0.5.8, on Microsoft Windows [Version 10.0.17134.165], locale en-US)
    • Flutter version 0.5.8 at C:\git\flutter
    • Framework revision e4b989bf3d (3 days ago), 2018-08-09 09:45:44 -0700
    • Engine revision 3777931801
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.17.1

[√] Connected devices (1 available)
    • SCH I959 • 4d004c0e6d66401f • android-arm • Android 5.0.1 (API 21)

• No issues found!
```

**Comment by zoechi** [comment] 2018-08-22 20:00
Have you tried `flutter clean` and `pod install` in `ios/` project sub directory?

**Comment by NoEnigmas** [comment] 2018-08-24 01:37
No, but I will give it a try ASAP. Thank you

**Comment by zoechi** [comment] 2018-09-02 09:45
Is this still an issue?

**Comment by zoechi** [comment] 2018-09-06 08:46
See also https://stackoverflow.com/questions/44653261/android-dependency-has-different-version-for-the-compile-and-runtime

**Comment by zoechi** [comment] 2018-10-23 06:41
See also https://github.com/flutter/flutter/issues/14020#issuecomment-380178542

**Comment by jonahwilliams** [comment] 2019-04-22 00:53
Duplicate of https://github.com/flutter/flutter/issues/14020#issuecomment-380178542

**Closed by jonahwilliams** 2019-04-22 00:53 UTC
Labels: p: framework, severe: crash, t: gradle, tool
