### ISSUE TITLE
ColorScheme with copyWith works unexpectedly in Appbar and Card

### ISSUE THREAD

**Issue by cruvie** [flutter/flutter#138998] opened 2023-11-25 15:14 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run the code on macos14

### Expected results

appbar and card should be in dark mode

### Actual results

appbar and card should be in light mode

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

main() async {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final primaryColor = Colors.teal;
  late ColorScheme colorScheme = ColorScheme.fromSeed(seedColor: primaryColor);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(),
      //bad
      darkTheme: ThemeData.dark().copyWith(
        colorScheme: colorScheme.copyWith(brightness: Brightness.dark),
      ),
      //good
      // darkTheme: ThemeData.dark().copyWith(
      //   colorScheme: ColorScheme.fromSeed(seedColor: primaryColor,brightness: Brightness.dark),
      // ),
      themeMode: ThemeMode.dark,
      home: const One(),
    );
  }
}

class One extends StatelessWidget {
  const One({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: const Card(
          child: FlutterLogo(
            size: 100,
          ),
        ));
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
<img width="723" alt="Xnip2023-11-25_23-12-58" src="https://github.com/flutter/flutter/assets/55651847/9f9cc347-2e20-43df-9655-a52529e8773f">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
cruvie@CruvieMac testone % flutter doctor -v
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.16.0 on channel stable at /Users/cruvie/Documents/DevelopmentEnvironment/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (10 天前), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/cruvie/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/cruvie/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
cruvie@CruvieMac testone % 


```

</details>

**Comment by huycozy** [comment] 2023-11-27 09:33
Hi @cruvie 
I can reproduce this issue on the latest master channel as well. But I see there is an issue that looks similar https://github.com/flutter/flutter/issues/136613. Could you check https://github.com/flutter/flutter/issues/136613#issuecomment-1766838128 to see if the explanation there fits your case?

**Comment by huycozy** [comment] 2023-11-28 04:30
Thanks for your confirmation. Closing this as a duplicate of https://github.com/flutter/flutter/issues/136613.

**Closed by huycozy** 2023-11-28 04:30 UTC
Labels: in triage
