### ISSUE TITLE
revert bot not landing reverts

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#135670] opened 2023-09-28 13:48 UTC
https://github.com/flutter/flutter/pull/135668

It looks like the fluttergithubbot is not able to lgtm a change, and my lgtm appears to to appease the checks.

As a reminder, it is a requirement that the framework gardener and engine sheriff be able to land reverts without waiting for approvals or presubmit checks.

cc @godofredoc @ricardoamador

**Comment by zanderso** [comment] 2023-09-28 14:41
I landed the revert the old way at https://github.com/flutter/flutter/pull/135672. Removing P0.

**Comment by ricardoamador** [comment] 2023-09-28 15:53
Well shoot. Okay I think I know what the issue is. @godofredoc can you make sure that auto-submit[bot] is able to push to this repo please?

**Comment by godofredoc** [comment] 2023-09-28 15:53
The problem is that the PR is trying to merge to main rather than master.

**Comment by godofredoc** [comment] 2023-09-28 15:54
The error is correct, main is just the replica of master. Nothing should be merged to main.

**Comment by ricardoamador** [comment] 2023-09-28 15:59
Not sure if this notifies on edits but @zanderso ^ was main intentionally the target of the merge?

**Comment by godofredoc** [comment] 2023-09-28 16:03
Let's land a change and revert to validate the functionality end to end. We can use https://github.com/flutter/flutter/pull/135567

**Comment by zanderso** [comment] 2023-09-28 16:04
No. I only applied the `revert` label to the PR I wanted to revert, and that is the PR that was created as a result.

**Comment by zanderso** [comment] 2023-09-28 16:05
You can see me adding the label here: https://github.com/flutter/flutter/pull/135645

**Comment by ricardoamador** [comment] 2023-09-28 16:14
Got it. Thanks.

**Closed** 2023-09-28 21:23 UTC
Labels: team-infra, P1, triaged-infra
