### ISSUE TITLE
Orientation change breaks rendering of ListView with UIKitView children

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#45902] opened 2019-12-02 14:23 UTC
If cacheExtent is set on ListView, rendering is glitchy when orientation changes and UIKitViews are in the list. Red rectangles are UIKitViews, Green rectangles are Container.

![Issue](https://user-images.githubusercontent.com/14054224/69966888-949d7680-1517-11ea-8eff-bb2738525ed1.gif)

## Steps to Reproduce

1. Create flutter project with iOS language set to swift
2. Paste the two demo files below

**Target Platform:** iOS
**Devices:** All iOS devices

#### lib/main.dart
```
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Issue(),
    );
  }
}

class Issue extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Issue'),
      ),
      body: ListView(
        cacheExtent: double.infinity, // Important!
        children: <Widget>[
          UIView(),
          Container(
            height: 700.0,
            color: Colors.green,
          ),
          UIView(),
          Container(
            height: 700.0,
            color: Colors.green,
          ),
          UIView(),
          Container(
            height: 700.0,
            color: Colors.green,
          ),
        ],
      ),
    );
  }
}

class UIView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
        width: double.infinity,
        height: 150.0,
        child: UiKitView(viewType: 'rect')
    );
  }
}
```

#### ios/Runner/AppDelegate.swift

```
import UIKit
import Flutter

class UIRectViewFactory: NSObject, FlutterPlatformViewFactory {
    func create(
        withFrame frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?
    ) -> FlutterPlatformView {
        return UIRectView(frame)
    }
}

class UIRectView: NSObject, FlutterPlatformView {
    let frame: CGRect

    init(_ frame: CGRect) {
        self.frame = frame
    }

    func view() -> UIView {
        let view: UIView = UIView(frame: frame)
        view.backgroundColor = UIColor.red
        return view
    }
}

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    registrar(forPlugin: "flutter").register(UIRectViewFactory(), withId: "rect")
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

## Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.16-pre.35, on Mac OS X 10.14.6 18G103, locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by iapicca** [comment] 2019-12-02 14:41
possible duplicate https://github.com/flutter/flutter/issues/45443

**Comment by gaaclarke** [comment] 2019-12-02 23:45
I agree with @iapicca.  That issue has a posted fix which hasn't been merged yet if you want to try it out.  The review machine is a bit slow because of US holidays.

**Comment by christian-muertz** [comment] 2019-12-06 11:36
With the fix merged the issue slightly changed. The app bar is not gitching somewhere else but flickers sometimes when scrolling.

**Comment by gaaclarke** [comment] 2019-12-06 16:29
https://github.com/flutter/engine/pull/14018 . Has been merged into master.  I can give this specific case a look.

**Comment by gaaclarke** [comment] 2019-12-06 18:00
@christian-muertz I was unable to reproduce this on master (240305238ef2fcda3b23f7e84d7cd4d6e5350207).  I'm getting errors when it tries to create the platform views.
```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: SemanticsNode#6(Rect.fromLTRB(0.0, 0.0, 0.0, 0.0), tags: [RenderViewport.twoPane], invisible) (with
flutter: null) tried to set a non-finite rect.                          
flutter: 'package:flutter/src/semantics/semantics.dart':                
flutter: Failed assertion: line 1245 pos 12: 'value.isFinite' 
```

Can you include your output to `flutter doctor -v` to make it easier for me to reproduce.  A gif of the problem now would be helpful as well.

When I was looking through the code I saw that the views are getting removed and added to their superview.  I suspect that can cause a flicker.

**Comment by christian-muertz** [comment] 2019-12-07 12:25
Here is the gif:

![RPReplay_Final1575719900](https://user-images.githubusercontent.com/14054224/70374379-bf117a00-18f1-11ea-8bb5-f391569268ec.gif)

#### flutter doctor -v

```
[✓] Flutter (Channel master, v1.13.1-pre.59, on Mac OS X 10.14.6 18G103, locale de-DE)
    • Flutter version 1.13.1-pre.59 at /Users/chris/Development/flutter
    • Framework revision e58dc16d7b (10 hours ago), 2019-12-06 18:21:52 -0800
    • Engine revision e7b69ced2e
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.0.3
    • Dart plugin version 192.7761

• No issues found!

```

**Comment by christian-muertz** [comment] 2019-12-16 12:00
> @christian-muertz I was unable to reproduce this on master ([2403052](https://github.com/flutter/flutter/commit/240305238ef2fcda3b23f7e84d7cd4d6e5350207)). I'm getting errors when it tries to create the platform views.
> 
> ```
> flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
> flutter: The following assertion was thrown during a scheduler callback:
> flutter: SemanticsNode#6(Rect.fromLTRB(0.0, 0.0, 0.0, 0.0), tags: [RenderViewport.twoPane], invisible) (with
> flutter: null) tried to set a non-finite rect.                          
> flutter: 'package:flutter/src/semantics/semantics.dart':                
> flutter: Failed assertion: line 1245 pos 12: 'value.isFinite' 
> ```
> 
> Can you include your output to `flutter doctor -v` to make it easier for me to reproduce. A gif of the problem now would be helpful as well.
> 
> When I was looking through the code I saw that the views are getting removed and added to their superview. I suspect that can cause a flicker.

Getting the same errors

**Comment by christian-muertz** [comment] 2019-12-16 12:06
It has definitely something to do with the infinite cacheExtent.

**Comment by iapicca** [comment] 2020-03-16 15:13
Hi @christian-muertz 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you


https://github.com/flutter/flutter/issues/45443#issuecomment-562346398

**Comment by jmagman** [comment] 2020-04-30 01:03
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-04-30 01:03 UTC
Labels: f: scrolling, framework, platform-ios, severe: rendering, waiting for customer response

**Comment by MichaelShuai** [comment] 2020-05-06 07:46
A normal ListView tries to apply, and a few more slides up and down will reproduce the error.


#2      SemanticsNode.rect= 
package:flutter/…/semantics/semantics.dart:1245
#3      _SwitchableSemanticsFragment.compileChildren 
package:flutter/…/rendering/object.dart:3596
#4      _SyncIterator.moveNext  (dart:core-patch/core_patch.dart:146:12)
#5      _SyncIterator.moveNext  (dart:core-patch/core_patch.dart:139:32)
#6      ExpandIterator.moveNext  (dart:_internal/iterable.dart:478:31)
...
════════════════════════════════════════════════════════════════════════════════

**Comment by iapicca** [comment] 2020-05-06 09:33
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
