### ISSUE TITLE
Add2App for Flutter Web

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#54761] opened 2020-04-14 17:22 UTC
# Add2App for Flutter Web

## Use case

If you have an existing web app, a large-scale project, written in a JavaScript-based framework, it would be very useful to be able to add some components to that web app using Flutter. This way, the same Flutter component could be added to an existing native Android and iOS app **+** the existing web app.

## Current situation

Currently, Flutter makes it very hard to add a module to an existing HTML-based project; the only possible solution seems to be `<iframe>`s.

## Proposal

Provide a way that allows attaching a Flutter module to HTML elements.

**Comment by ferhatb** [comment] 2020-04-16 22:23
Duplicate of #32329

**Closed** 2020-04-16 22:23 UTC
Labels: a: existing-apps, engine, platform-web, proposal, severe: new feature
