### ISSUE TITLE
why chinese character display unreadable code, when flutter for web loaded successful on PC in Chrome?

### ISSUE THREAD

**Issue by wjxfhxy** [flutter/flutter#82400] opened 2021-05-13 01:35 UTC
when loaded successful, it look like this

![企业微信截图_16208686818073](https://user-images.githubusercontent.com/4960861/118064794-4a881800-b3ce-11eb-9ea7-2ee6aa1a1db4.png)

but after 1 second, it reander normal

![企业微信截图_16208686894716](https://user-images.githubusercontent.com/4960861/118064800-4e1b9f00-b3ce-11eb-84c5-eb8da3c3b164.png)

**Comment by darshankawar** [comment] 2021-05-13 08:02
Closing this as duplicate of https://github.com/flutter/flutter/issues/77023

**Closed by darshankawar** 2021-05-13 08:02 UTC
Labels: in triage
