### ISSUE TITLE
App not compiling after upgrading / downgrading SDK

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#80290] opened 2021-04-12 17:02 UTC
Hello i was trying to upgrade flutter to null safety but realised that there amny dependencies that are not still ready So i decided to revert it back. After reverting my project is not compiling any more. I have tried everything i know even re-installed flutter. But i still getting this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Problems reading data from Binary store in C:\Users\...\AppData\Local\Temp\gradle1077061253750656152.bin offset 379137 exists? true

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
I already reported this issue in another section but there I am not receiving much help apart - ask stackoverflow.com. But I searched and stackoverflow.com and tried all solutions but nothing works. https://stackoverflow.com/questions/34421193/could-not-determine-the-dependencies-of-task-appcrashlyticsstoredeobsdebug-i

This issue has appeared after upgrading / downgrading flutter so it is clearly a bug that left somewhere ref to file which is missing. 

I would appreciate if you can help me to resolve it.

Thanks

**Comment by mayurdhurpate** [comment] 2021-04-12 17:52
Same issue for me, but in my case, I did not upgrade/downgrade Flutter for this to happen. It suddenly started happening out of the blue:

```
+39197 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Could not determine the dependencies of task ':app:compileProdDebugJavaWithJavac'.
[        ] > Could not resolve all dependencies for configuration ':app:prodDebugCompileClasspath'.
[        ]    > Problems reading data from Binary store in /private/var/folders/m6/ydzzkqm5733960v2v8pwqjw80000gn/T/gradle1892749619680126024.bin
offset 661905 exists? true
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 48s
[ +704 ms] Running Gradle task 'assembleProdDebug'... (completed in 49.9s)
[  +15 ms] Exception: Gradle task assembleProdDebug failed with exit code 1
[   +9 ms] "flutter run" took 56,914ms.
```

**Comment by TahaTesser** [comment] 2021-04-13 07:31
Hi @vytautas-pranskunas- 
This seems related to Gradle than Flutter itself 
https://github.com/gradle/gradle/issues/8489 
https://github.com/gradle/gradle/issues/13316
Make sure you're running the latest stable flutter channel and `com.android.tools.build:gradle:4.1.0` in your build.gradle
If the issue persists, please file a new issue in https://github.com/gradle/gradle/issues

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-13 07:31 UTC
Labels: in triage

**Comment by vytautas-pranskunas-** [comment] 2021-04-13 07:58
@TahaTesser how can i make sure that i am running on latest chanel if canno migrate to null safety because of other dependencies...

Maybe you have a guide hot to migrate to null safety, with higher SDK while packages that i depending on still not there. Because i can run flutter with no sound but as soon i increase SDK version packages not being resolved any more.

**Comment by vytautas-pranskunas-** [comment] 2021-04-13 08:04
```
cd <your_project>/android
./gradlew clean
```

helped. 

But question regarding upgrade stays - how can i migrate to null safety when i have 30% packages that are not there yet... ?

**Comment by TahaTesser** [comment] 2021-04-13 10:23
@vytautas-pranskunas- 
Unfortunately, you cannot upgrade, that's because the third party packages, has nothing to do with this issue. if it is a Flutter, you could've reproduced using the latest versions, that's what I meant. 
Glad you resolved the issue
