### ISSUE TITLE
Shallow clone causes v0.0.0-unknown problem

### ISSUE THREAD

**Issue by twlz0ne** [flutter/flutter#32684] opened 2019-05-14 09:07 UTC
## Steps to Reproduce

1. `git clone --depth 1 https://github.com/flutter/flutter.git ~/flutter` 
2. `flutter doctor -v`

## Logs

```
[✓] Flutter (Channel master, v0.0.0-unknown, on Mac OS X 10.12.6 16G1918, locale en-CN)
    • Flutter version 0.0.0-unknown at /Users/*/flutter
    • Framework revision b76a1e8312 (4 hours ago), 2019-05-13 09:06:30 +0100
    • Engine revision 816d3fc586
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that
      location.
      You may also want to add it to your PATH environment variable.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[!] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected device (2 available)
    • iPhone 6 • ########-####-####-####-############ • ios        • iOS 9.2 (simulator)
    • macOS    • macOS                                • darwin-x64 • Mac OS X 10.12.6
```

**Comment by twlz0ne** [comment] 2019-05-14 09:07
My temporary solution is to add a fake tag `git tag v1.6.0`

**Comment by jonahwilliams** [comment] 2019-10-30 17:52
Our versions and channels are determined by git tags and commits. If you shallow clone you certainly won't get this information. We have no immediate plans to change how we distribute Flutter

**Comment by jmagman** [comment] 2020-01-10 23:58
Duplicate of https://github.com/flutter/flutter/issues/18532.

**Closed by jmagman** 2020-01-10 23:58 UTC
Labels: tool
