### ISSUE TITLE
ios build fails: `'Flutter/Flutter.h' file not found`

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#100224] opened 2022-03-16 15:35 UTC
Hi, I seem to be having loads of issues with iOS. My app is in production and live on both the play store & app store however since upgrading to support null saftey I've been unable to get the iOS build working.

### Error logs:

- Output of `flutter build ios --verbose`: [flutter_build_ios.log](https://github.com/flutter/flutter/files/8264189/flutter_build_ios.log) (2.5Mb)
- Output of xcode trying to run on device: 
[Build Runner_2022-03-16T15-17-53.txt](https://github.com/flutter/flutter/files/8264442/Build.Runner_2022-03-16T15-17-53.txt) (18.6Mb)

I've tried removing ios/Flutter/Flutter.podspec, I've made sure I'm running the most up to date packages.  I've generally been having a generally bad experience with iOS + flutter for a while, maybe something in my case is wrong and fixable? These are the issues i've been living with:

- Builds take 5-10 minutes which is just a nightmare for fixing issues or diagnosing build problems like this
- I'm unable to run from VSCode - it tells me that i should try running from Xcode instead

Please let me know if you have any advice for sorting out my ios builds, thanks!

<details>
  <summary>Flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-x64, locale en-GB)
    • Flutter version 2.10.3 at /Users/jimmyff/flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Platform android-31, build-tools 29.0.3
    • Java binary at: /Applications/Development/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Development/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /Applications/Development/IntelliJ IDEA.app
    ✗ Flutter plugin version 15.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 172.3317.48
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-172.1909.2)
    • IntelliJ at /Applications/Development/IntelliJ IDEA 2017.1.2 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.65.1)
    • VS Code at /Applications/Development/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • James’s iPhone (mobile) • 00008020-001A0D811A78002E • ios            • iOS 15.3.1 19D52
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by maheshmnj** [comment] 2022-03-18 13:57
Hi @jimmyff, Thanks for filing the issue. Sorry for the delayed response for some reason this issue didn't show up in untriaged issues.  


> /Users/jimmyff/Development/esc_party/esc_app/ios/Runner/Runner-Bridging-Header.h:1:9: note: in file included from /Users/jimmyff/Development/esc_party/esc_app/ios/Runner/Runner-Bridging-Header.h:1:
               #import "GeneratedPluginRegistrant.h"
                       ^
               /Users/jimmyff/Development/esc_party/esc_app/ios/Runner/GeneratedPluginRegistrant.h:10:9: error: 'Flutter/Flutter.h' file not found
               #import <Flutter/Flutter.h>
                       ^
               1 error generated.
               <unknown>:0: error: failed to emit precompiled header '/Users/jimmyff/Library/Developer/Xcode/DerivedData/Runner-gvjwzkyvgjwthnbmjzvxikjasgyi/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_3B2RD1630KUEL-clang_56KV530HTHM6.pch' for bridging header '/Users/jimmyff/Development/esc_party/esc_app/ios/Runner/Runner-Bridging-Header.h'
               /Users/jimmyff/Development/esc_party/esc_app/ios/Runner/Runner-Bridging-Header.h:1:9: note: in file included from /Users/jimmyff/Development/esc_party/esc_app/ios/Runner/Runner-Bridging-Header.h:1:
               #import "GeneratedPluginRegistrant.h"
                       ^
               2 errors generated.

From your logs this issue looks same as this https://github.com/flutter/flutter/issues/99387, 

> Builds take 5-10 minutes which is just a nightmare for fixing issues or diagnosing build problems like this

Is this issue with a newly created flutter project too? if so I would recommend you to please file that as a separate issue.

> I'm unable to run from VSCode - it tells me that i should try running from Xcode instead

Could you please share the complete error/message when this happens.

Closing as the duplicate of the above linked issue. Please follow up there for further updates. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-03-18 13:57 UTC
Labels: in triage
