### ISSUE TITLE
[tool_crash] _TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))

### ISSUE THREAD

**Issue by Muhammad-Sharif-Ullah** [flutter/flutter#131145] opened 2023-07-23 06:29 UTC
## Command
```
flutter build apk --target-platform android-arm --analyze-size
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))
```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:548:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on Ubuntu 22.04.2 LTS 5.19.0-46-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.10.6 on channel stable at /home/appdev/snap/flutter/common/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (10 days ago), 2023-07-12 15:19:05 -0700
    [32m•[39m

**Comment by danagbemava-nc** [comment] 2023-07-24 07:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/129706

**Closed by danagbemava-nc** 2023-07-24 07:02 UTC
Labels: in triage
