### ISSUE TITLE
macOS: assertion: Should never encounter KeyData when transitMode is rawKeyData.

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#90329] opened 2021-09-18 18:08 UTC
## Issue description

Occasionally when debugging my macOS application, I get the following assert in hardware_keyboard.dart (seems to happen on window switch with Command+Tab while running the app from Visual Studio Code in debug mode):

```
Exception has occurred.
_AssertionError ('package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 787 pos 16: 'false': Should never encounter KeyData when transitMode is rawKeyData.)
```

The assert is hit here:
```
  bool handleKeyData(ui.KeyData data) {
    _transitMode ??= KeyDataTransitMode.keyDataThenRawKeyData;
    switch (_transitMode!) {
      case KeyDataTransitMode.rawKeyData:
        assert(false, 'Should never encounter KeyData when transitMode is rawKeyData.');
```

`data` value when the issue last happened:

```
KeyData (KeyData(key down, physical: 0x700e3, logical: 0x200000106 (Flutter), character: <none>))
character:null
logical:8589934854
physical:458979
synthesized:false
timeStamp:Duration (0:21:12.336174)
type:KeyEventType (KeyEventType.down)
_name:"KeyEventType.down"
index:0
hashCode:3858975340
runtimeType:Type (KeyEventType)
hashCode:2823476307
runtimeType:Type (KeyData)
```

Call originating from:

```
void _dispatchKeyData(ByteData packet, int responseId) {
  PlatformDispatcher.instance._dispatchKeyData(packet, responseId);
}
```

`packet` parameter dump:
```
_ByteDataView (TypedDataView(cid: 147))
runtimeType:Type (_ByteDataView)
_typedData:[0, 0, 0, 0, 0, 0, 0, 0, 46, 79, 214, 75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 227, 0, 7, 0, 0, 0, 0, 0, 6, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
buffer:_ByteBuffer
elementSizeInBytes:1
hashCode:3993723895
length:48
lengthInBytes:48
offsetInBytes:0
```
`responseId` = 9

## Steps to Reproduce

None yet. App is too big to publish here and no minimum code to reproduce found yet.

<details>
  <summary>Logs</summary>

```
% flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-6.0.pre.147, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.147 at /Library/Frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83dfb2237a (14 hours ago), 2021-09-17 23:48:04 -0400
    • Engine revision 31792e0340
    • Dart version 2.15.0 (build 2.15.0-120.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tgucio/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2021-09-20 10:36
Hi @tgucio, Thanks for filing the issue. I suspect this issue to be a duplicate of https://github.com/flutter/flutter/issues/89245 but can't be assured Unless we have a proper reproducible step, Could you please try to create a minimal and complete reproducible code with the exact steps to reproduce the issue.

Thanks

**Comment by onumengine** [comment] 2021-09-30 22:10
I experienced the same issue building for iOS. Same steps to reproduce, same everything

**Comment by maheshmnj** [comment] 2021-10-01 04:55
>I experienced the same issue building for iOS. Same steps to reproduce, same everything

Could you please share what are the steps to reproduce?

**Comment by spkersten** [comment] 2021-10-08 08:46
Same issue here. For some builds typing works, for other is doesn't.

```
[✓] Flutter (Channel unknown, 2.5.2, on macOS 11.5.2 20G95 darwin-x64, locale en-NL)
    • Flutter version 2.5.2 at
    • Upstream repository unknown
    • Framework revision 3595343e20 (8 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3
```

**Comment by maheshmnj** [comment] 2021-10-08 09:09
Everyone who is facing this similar issue, it would be great if you could share the reproducible steps.

Thanks.

**Closed** 2021-10-11 11:09 UTC
Labels: waiting for customer response, in triage
