### ISSUE TITLE
Document that debug Flutter apps cannot be manually launched on the device on iOS 14

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#62531] opened 2020-07-29 23:31 UTC
On iOS 14 execution of JIT fails when the debugger is not attached, and debug Flutter apps (including host add-to-app applications) [crash on launch](https://github.com/flutter/flutter/issues/60657) when manually launched from the home screen on a physical device.

### Reproduction steps
```
$ flutter create test_crash
$ cd test_crash
$ flutter run --debug -d physical-device-ios-14-identifier
<q> (quit)
```
On the device’s home screen, launch the newly installed Flutter app.

Write up documentation that the engine/tool can link and can be published as an "annoyance" describing this new limitation.

**Comment by jmagman** [comment] 2020-07-29 23:31
Issue tracking some UI in the engine to display and link to this documentation, instead of crashing:
https://github.com/flutter/flutter/issues/62518

**Comment by jmagman** [comment] 2020-07-29 23:32
@sfshaza2 Do you think this belongs on the website?

**Comment by jmagman** [comment] 2020-07-29 23:34
\cc @RedBrogdon @filiph

**Comment by filiph** [comment] 2020-07-30 01:26
Trying to understand better, please let me know if I'm wrong about any of this:

* This only happens on iOS 14 and there's no (or very low) chance it will manifest in iOS 13, for example.
* This must be fixed on our side. It's not an example of some regression bug in iOS 14.
* iOS is not yet available for consumer use, and is expected to be in Fall (i.e. months from now).
* But all iOS developers have access to iOS 14 for testing / dev purposes.
* And iOS 14 is at the stage when developers are encouraged by Apple to start developing for iOS 14 and having it installed on their dev devices.

Again, I'm not sure about any of the above, and would welcome any correction.

FWIW, I think we should tweet about this sooner rather than later, assuming all of my assumptions are true.

**Comment by jmagman** [comment] 2020-07-30 01:47
A little more context:
This crash is only relevant for physical iOS 14 devices and debug versions of the Flutter app.  iOS 13 and below, simulators, and release versions of the app (so what end-customers will see) is unaffected.

The following will not work targeting an iOS 14 device:
- On the device, launching the app by tapping an installed Flutter debug app on the home screen or a Siri search result
- `flutter install` then launching the debug app manually from the home screen
- Archiving and deploying a debug version of the app for testing (distribution to QA, etc), installing, and launching manually from the home screen

The following does work on iOS 14:
- Launching the app from the Flutter command line with `flutter run --debug` or an IDE like Android Studio
- Running the app from Xcode on the host Mac (`ios/Runner.xcworkspace` or an add-to-app host app)
- Launching from the home screen on a simulator manually from the home screen
- Launching release version of the app manually from the home screen

> * This only happens on iOS 14 and there's no (or very low) chance it will manifest in iOS 13, for example.

Yes, iOS 14 only.

> * This must be fixed on our side. It's not an example of some regression bug in iOS 14.

Apple changed some kernel behavior that disallowed an API dart is relying on, and we assume it was a purposeful change on their side.

> * iOS is not yet available for consumer use, and is expected to be in Fall (i.e. months from now).
> * But all iOS developers have access to iOS 14 for testing / dev purposes.
> * And iOS 14 is at the stage when developers are encouraged by Apple to start developing for iOS 14 and having it installed on their dev devices.

Yes, yes, and yes.

> FWIW, I think we should tweet about this sooner rather than later, assuming all of my assumptions are true.

I'd like to hold off a bit until we decide how it will manifest to the user.  We may be able to work around this issue completely (probably unlikely), and if not will likely show UI in the app that explains why what they tried won't work, and a link to documentation (tracked by this issue).  \cc @zanderso

**Comment by filiph** [comment] 2020-07-30 02:12
Thanks, that's very helpful!

For what it's worth, while I think it's good to see if we can work around this quickly, we should not wait too long. Assuming this is happening to developers out there right now, and given the potentially frustrating aspect of "crashed while I was demoing my work to someone", I'd rather be proactive.

**Comment by jmagman** [comment] 2020-07-30 02:18
@filiph Responding quickly makes sense.  We likely won't have anything working by Thursday, I definitely defer to whenever you and @zanderso think is best to get the word out.  We don't plan to ship the next stable with this crash-on-launch behavior, I just don't want them to think that will be Flutter's expected behavior moving forward.

**Comment by filiph** [comment] 2020-07-30 02:38
Oh, additional question:

* This is a problem for the current `stable` Flutter, correct? In other words, this does not affect only `dev` or `master` users, it affects everyone, right? It looks like it from the linked bug (https://github.com/flutter/flutter/issues/60657) — just making sure.

**Comment by jmagman** [comment] 2020-07-30 02:42
Yes, all channels are impacted, including current stable.

**Comment by jmagman** [comment] 2020-07-31 00:26
Summary of this issue, and other iOS 14 annoyances:

**Debug crash on launch**
Flutter debug applications crash when manually launched from the home screen on a physical iOS 14 device.  Add-to-app debug applications will crash when the Flutter module loads.
This will not impact release versions of the application, and is not visible to end-users.

Workarounds:
- Launch the app from the Flutter command line with `flutter run` or an IDE like Android Studio.
- Run the app from Xcode on the host Mac (`ios/Runner.xcworkspace` or an add-to-app host app).
- Run the profile or release version of the app.
- Run on an iOS 14 simulator.

GitHub issue: https://github.com/flutter/flutter/issues/60657

**Local network notification**
The dart observatory in Flutter debug applications prompts a permission notification that your app "would like to find and connect to devices on your local network". To use hot reload, make sure to select "OK" instead of "Don't Allow".
This will not impact release versions of the application, and is not visible to end-users.

GitHub issue: https://github.com/flutter/flutter/issues/60634

**Clipboard notifications**
Flutter apps will show notifications that the app is pasting from your clipboard when no paste was initiated. This will impact released apps, and end-users will see this when running the app on iOS 14. A fix for this behavior will soon be available on the master channel.

GitHub issue: https://github.com/flutter/flutter/issues/60145

**Comment by sfshaza2** [comment] 2020-08-05 01:11
I've handled this in PR https://github.com/flutter/website/pull/4435. I've incorporated Jenn's feedback, but need approval.

**Comment by sfshaza2** [comment] 2020-08-06 01:52
Merged.

**Comment by pedromassangocode** [comment] 2020-08-07 14:00
> Merged.

Is this still a valid issue?

**Comment by jmagman** [comment] 2020-08-07 18:33
I think @xster wanted more add-to-app documentation.  flutter/website#4435 is a good start though!

**Comment by xster** [comment] 2020-09-17 15:50
Documented on https://flutter.dev/docs/development/ios-14 now.

**Closed by xster** 2020-09-17 15:50 UTC
Labels: documentation, platform-ios

**Comment by kherld-hussein** [comment] 2020-09-18 18:27
Closed

**Comment by PerrchicK** [comment] 2020-12-31 09:50
Question, is everyone OK with this new behaviour? 😯
