### ISSUE TITLE
Not getting Firebase push Notification in Release build but getting the notification content in on message Method.

### ISSUE THREAD

**Issue by gotirahul96** [flutter/flutter#57021] opened 2020-05-12 17:02 UTC
I'm getting Notification in Debug mode but not able to receive in release Apk.Please Help.
Here is my Flutter Doctor Summary:-
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.19.0-1.0.pre.49, on Microsoft Windows [Version 10.0.18362.778], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.5.4)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.0)
[√] Connected device (2 available)

• No issues found!
here is the on message : on message {notification: {title: Hello Jagdish, body: xczczxc}, data: {testing: working, name: Rahul}}

**Comment by gotirahul96** [comment] 2020-05-12 18:09
Its a bug in Flutter when we quit the app using the 'Q' command in the terminal the app doesn't receive the notification but if you remove the device without quitting the app the app receives the notification.

**Comment by iapicca** [comment] 2020-05-13 07:43
Hi @gotirahul96 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-05-13 07:43 UTC
