### ISSUE TITLE
[Regression]: Assertion failure in `/material/scaffold.dart` throws `_appBarMaxHeight! >= 0.0 && _appBarMaxHeight!.isFinite is not true`

### ISSUE THREAD

**Issue by ChristopherBanas** [flutter/flutter#89808] opened 2021-09-10 01:20 UTC
Error being thrown is
`Assertion failed: file:///Applications/flutter/packages/flutter/lib/src/material/scaffold.dart:3251:14
_appBarMaxHeight! >= 0.0 && _appBarMaxHeight!.isFinite
is not true`
Flutter doctor is
```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
[✓] Connected device (1 available)
```
The app bar that throws the error is
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Games"),
        toolbarHeight: 100,
        bottom: PreferredSize(
          preferredSize: const Size.fromWidth(1),
          child: SizedBox(
            height: 30,
            child: Center(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 10.0),
                child: Text(
                  //widget.gamesList[0].valueMap[gameEnums.DATE],
                  '12/25/2020',
                  style: TextStyle(color: Colors.white),
                ),
              ),
            ),
          ),
        ),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(
            bottom: Radius.circular(20),
          ),
        ),
      ),
```

This was compiling and working fine before upgrading to the newest version of flutter. Not sure if upgrading is the reason why this error is now being thrown.

**Comment by ChristopherBanas** [comment] 2021-09-10 01:32
Upon further testing it has something to do with the bottom widget within the app bar. Once removed the code compiles and runs

**Comment by darshankawar** [comment] 2021-09-10 10:08
This appears to be a regression in 2.5 and 2.6.  I verified this on stable 2.2.3 on which it works properly as below:

<img width="376" alt="Screenshot 2021-09-10 at 3 31 00 PM" src="https://user-images.githubusercontent.com/67046386/132837504-558fbdf1-85c2-47f1-bb26-ecb624f3b54f.png">

But running the code sample on latest master and stable throws below exception:

<details>
<summary>console error log</summary>



```
Syncing files to device iPhone 12 Pro Max...

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Scaffold(dirty, dependencies: [MediaQuery, UnmanagedRestorationScope, _LocalizationsScope-[GlobalKey#45223], Directionality, _ScaffoldMessengerScope, _InheritedTheme, _EffectiveTickerMode], state: ScaffoldState#0119d(tickers: tracking 2 tickers)):
'package:flutter/src/material/scaffold.dart': Failed assertion: line 2840 pos 14: '_appBarMaxHeight! >= 0.0 && _appBarMaxHeight!.isFinite': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///Users/dhs/Downloads/demo/lib/main.dart:10:13
When the exception was thrown, this was the stack: 
#2      ScaffoldState.build (package:flutter/src/material/scaffold.dart:2840:14)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4700:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4583:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4561:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4749:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4556:5)
...     Normal element mounting (24 frames)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#34     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6251:36)
#35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6262:32)
...     Normal element mounting (173 frames)
#208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#209    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6251:36)
#210    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6262:32)
...     Normal element mounting (362 frames)
#572    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#573    Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#574    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#575    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#576    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#577    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#578    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#579    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#580    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================

```


</details>

<details>
<summary> latest stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.5.0 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 93.0.4577.63

• No issues found!

[✓] Flutter (Channel master, 2.6.0-1.0.pre.237, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.237 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a54b10254a (5 hours ago), 2021-09-10 07:22:02 +0300
    • Engine revision 57bc7414b8
    • Dart version 2.15.0 (build 2.15.0-92.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!




```

</details>

<details>
<summary> working stable flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

**Comment by Piinks** [comment] 2021-09-13 17:02
Hey @ChristopherBanas thanks for reporting!
This may be intentional.. it looks like the error is caused by your PreferredSize widget not being provided a height. Here's a stripped down reproduction:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Reproduction #89808'),
        bottom: const PreferredSize(
          // Error caused by not providing a height here.
          preferredSize: Size.fromWidth(1),
          child: SizedBox(
            height: 30,
            child: Center(
              child: Text('Bottom Text'),
            ),
          ),
        ),
      ),
    );
  }
}

```

I am working on bisecting this now to the change that introduced it, but if you provide a height it works fine.

**Comment by HansMuller** [comment] 2021-09-13 20:26
The assertion wasn't expected, however I think it's correct. AppBar.preferredSize is just used to compute the app bar's overall height (see https://api.flutter.dev/flutter/material/AppBar/preferredSize.html). So setting it to infinity with Size.fromWidth(...) was always an error, but it's one that we were not catching before.

**Comment by ChristopherBanas** [comment] 2021-09-14 02:02
> Hey @ChristopherBanas thanks for reporting!
> This may be intentional.. it looks like the error is caused by your PreferredSize widget not being provided a height.
> I am working on bisecting this now to the change that introduced it, but if you provide a height it works fine.
> 
> Update: Removing repro, it does not capture the regression as it also breaks in earlier versions. Still digging into what the cause is here.

Chaning my code from 

> preferredSize: const Size.fromWidth(1),

to
>preferredSize: const Size.fromHeight(1),

Fixed my problem and rendered the app bar the same as before. Thank you.

**Comment by Piinks** [comment] 2021-09-14 18:28
Ok great! Thanks for the input @HansMuller and the update @ChristopherBanas! It sounds like this is confirmed as expected behavior so I am going to close this.

**Closed by Piinks** 2021-09-14 18:28 UTC
Labels: severe: regression, framework, f: material design, has reproducible steps, found in release: 2.5, found in release: 2.6
