### ISSUE TITLE
[webview_flutter] App crash on iOS 13 when loading webview

### ISSUE THREAD

**Issue by Nolat** [flutter/flutter#82247] opened 2021-05-11 07:45 UTC
## Steps to Reproduce

1. Clone this repo : https://github.com/Nolat/webview-test (this repo is using webview_flutter example)
2. Simply start the application on iOS 13

**Expected results:** 
The webview should display flutter.dev page.

**Actual results:** 
The app crashes.

<details>
  <summary>Logs</summary>

`flutter run --verbose`
[20210511_094251.Logging.w1t1p0.A9081DEB-59E7-4A97-882E-B019FFDC6E82.464.614033523.log](https://github.com/flutter/flutter/files/6457359/20210511_094251.Logging.w1t1p0.A9081DEB-59E7-4A97-882E-B019FFDC6E82.464.614033523.log)

```
[11/05/2021 at 9:38:03,951 AM] ❯ flutter analyze
[11/05/2021 at 9:38:13,729 AM] Analyzing webview_test...
[11/05/2021 at 9:38:19,113 AM] No issues found! (ran in 5.3s)
```

```
[11/05/2021 at 9:39:16,800 AM] ❯ flutter doctor -v
[11/05/2021 at 9:39:29,309 AM]  [✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-arm, locale fr-FR)
[11/05/2021 at 9:39:29,339 AM]     • Flutter version 2.0.6 at /Users/a.talon/Documents/repo/flutter
[11/05/2021 at 9:39:29,339 AM]     • Framework revision 1d9032c7e1 (11 days ago), 2021-04-29 17:37:58 -0700
[11/05/2021 at 9:39:29,339 AM]     • Engine revision 05e680e202
[11/05/2021 at 9:39:29,339 AM]     • Dart version 2.12.3

[11/05/2021 at 9:39:29,339 AM]  [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[11/05/2021 at 9:40:07,203 AM]     • Android SDK at /Users/a.talon/Library/Android/sdk
[11/05/2021 at 9:40:07,205 AM]     • Platform android-30, build-tools 30.0.2
[11/05/2021 at 9:40:07,211 AM]     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[11/05/2021 at 9:40:07,212 AM]     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[11/05/2021 at 9:40:07,212 AM]     • All Android licenses accepted.

[11/05/2021 at 9:40:07,216 AM]  [✓] Xcode - develop for iOS and macOS
[11/05/2021 at 9:40:07,216 AM]     • Xcode at /Applications/Xcode.app/Contents/Developer
[11/05/2021 at 9:40:07,216 AM]     • Xcode 12.5, Build version 12E262
[11/05/2021 at 9:40:07,216 AM]     • CocoaPods version 1.10.0

[11/05/2021 at 9:40:07,216 AM]  [✓] Chrome - develop for the web
[11/05/2021 at 9:40:07,216 AM]     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[11/05/2021 at 9:40:07,216 AM]  [✓] Android Studio (version 4.1)
[11/05/2021 at 9:40:07,223 AM]     • Android Studio at /Applications/Android Studio.app/Contents
[11/05/2021 at 9:40:07,223 AM]     • Flutter plugin can be installed from:
[11/05/2021 at 9:40:07,264 AM]       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
[11/05/2021 at 9:40:07,266 AM]     • Dart plugin can be installed from:
[11/05/2021 at 9:40:07,267 AM]       🔨 https://plugins.jetbrains.com/plugin/6351-dart
[11/05/2021 at 9:40:07,267 AM]     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[11/05/2021 at 9:40:07,267 AM]  ⣽ [✓] Connected device (2 available)
[11/05/2021 at 9:40:07,273 AM]     • iPhone 11 Pro (mobile) • FDC8F82C-E0D9-4A05-A954-D9447522BE52 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
[11/05/2021 at 9:40:07,273 AM]     • Chrome (web)           • chrome                               • web-javascript • Google Chrome 90.0.4430.93

[11/05/2021 at 9:40:07,273 AM] • No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-05-11 12:06
Hi @Nolat 
Thanks for filing the issue. I'm unable to reproduce the issue using your code on `iOS 13.7` simulator on the `stable` channel

Reproduced the issue using the following minimal code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
``` 

</details>


<details> 
<summary>logs</summary> 
	
```console
                        USE_LLVM_TARGET_TRIPLES_FOR_CLANG = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_LD = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_TAPI = YES
                        USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES = YES
                        VALIDATE_PRODUCT = NO
                        VALIDATE_WORKSPACE = NO
                        VALID_ARCHS = arm64 arm64e i386 x86_64
                        VERBOSE_PBXCP = NO
                        VERBOSE_SCRIPT_LOGGING = YES
                        VERSIONING_SYSTEM = apple-generic
                        VERSIONPLIST_PATH = Runner.app/version.plist
                        VERSION_INFO_BUILDER = tahatesser
                        VERSION_INFO_FILE = Runner_vers.c
                        VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
                        WRAPPER_EXTENSION = app
                        WRAPPER_NAME = Runner.app
                        WRAPPER_SUFFIX = .app
                        WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
                        XCODE_APP_SUPPORT_DIR =
                        /Volumes/Extreme/Xcode.app/Contents/Developer/Library/Xcode
                        XCODE_PRODUCT_BUILD_VERSION = 12E262
                        XCODE_VERSION_ACTUAL = 1250
                        XCODE_VERSION_MAJOR = 1200
                        XCODE_VERSION_MINOR = 1250
                        XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
                        YACC = yacc
                        arch = x86_64
                        variant = normal
[ +260 ms] executing: xcrun simctl install A8AC71AD-7DA7-4AE8-8CC2-1A7C8787F9CA
/Users/tahatesser/AndroidStudioProjects/webview-test/build/ios/iphonesimulator/Runner.app
[ +747 ms] executing: /usr/bin/plutil -convert json -o -
/Users/tahatesser/AndroidStudioProjects/webview-test/build/ios/iphonesimulator/Runner.app/Info.pli
st
[  +12 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Users/tahatesser/AndroidStudioProjects/webview-test/build/ios/iphonesimulator/Runner.app/Info.pli
st
[        ]
{"CFBundleName":"webview_test","DTSDKName":"iphonesimulator14.5","DTXcode":"1250","CFBundleIcons~i
pad":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","Ap
pIcon60x60","AppIcon76x76","AppIcon83.5x83.5"],"CFBundleIconName":"AppIcon"}},"UILaunchStoryboardN
ame":"LaunchScreen","DTSDKBuild":"18E182","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","
BuildMachineOSBuild":"20E232","DTPlatformName":"iphonesimulator","CFBundlePackageType":"APPL","CFB
undleShortVersionString":"1.0.0","CFBundleSupportedPlatforms":["iPhoneSimulator"],"UIMainStoryboar
dFile":"Main","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"Runner","DTCompiler":"co
m.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientation
Portrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInte
rfaceOrientationLandscapeRight"],"MinimumOSVersion":"9.0","CFBundleIdentifier":"com.example.webvie
wTest","UIDeviceFamily":[1,2],"CFBundleSignature":"????","DTPlatformVersion":"14.5","CFBundleIcons
":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIc
on60x60"],"CFBundleIconName":"AppIcon"}},"DTXcodeBuild":"12E262","LSRequiresIPhoneOS":true,"UISupp
ortedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft
","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":false,"DTPlat
formBuild":"18E182"}
[   +3 ms] executing: xcrun simctl launch A8AC71AD-7DA7-4AE8-8CC2-1A7C8787F9CA
com.example.webviewTest --enable-dart-profiling --enable-checked-mode --verify-entry-points
--observatory-port=0
[ +249 ms] com.example.webviewTest: 22350
[        ] Waiting for observatory port to be available...
[ +565 ms] Observatory URL on device: http://127.0.0.1:56737/Vzr8hP38ATQ=/
[   +3 ms] Caching compiled dill
[ +188 ms] Connecting to service protocol: http://127.0.0.1:56737/Vzr8hP38ATQ=/
[ +181 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to
VM service at http://127.0.0.1:56737/Vzr8hP38ATQ=/.
[  +87 ms] DDS is listening at http://127.0.0.1:56745/AikzusVwZqI=/.
[  +81 ms] Successfully connected to service protocol: http://127.0.0.1:56737/Vzr8hP38ATQ=/
[ +760 ms] 
                    ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
                    ╞═══════════════════════════════════════════════════════════
                    The following _CastError was thrown building
FutureBuilder<WebViewController>(dirty, state:
                    _FutureBuilderState<WebViewController>#1753d):
                    Null check operator used on a null value
                    
                    The relevant error-causing widget was:
                      FutureBuilder<WebViewController>

file:///Users/tahatesser/AndroidStudioProjects/webview-test/lib/main.dart:299:12
                    
                    When the exception was thrown, this was the stack:
                    #0      NavigationControls.build.<anonymous closure>
(package:webview_test/main.dart:305:59)
                    #1      _FutureBuilderState.build
(package:flutter/src/widgets/async.dart:773:55)
                    #2      StatefulElement.build
(package:flutter/src/widgets/framework.dart:4612:27)
                    #3      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4495:15)
                    #4      StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4667:11)
                    #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
                    #6      ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:4474:5)
                    #7      StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:4658:11)
                    #8      ComponentElement.mount
(package:flutter/src/widgets/framework.dart:4469:5)
                    ...     Normal element mounting (7 frames)
                    #15     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3541:14)
                    #16     MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6094:32)
                    ...     Normal element mounting (19 frames)
                    #35     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3541:14)
                    #36     MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6094:32)
                    ...     Normal element mounting (129 frames)
                    #165    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3541:14)
                    #166    MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6094:32)
                    ...     Normal element mounting (96 frames)
                    #262    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3541:14)
                    #263    MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6094:32)
                    ...     Normal element mounting (170 frames)
                    #433    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3541:14)
                    #434    MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6094:32)
                    ...     Normal element mounting (309 frames)
                    #743    Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3541:14)
                    #744    Element.updateChild
(package:flutter/src/widgets/framework.dart:3306:18)
                    #745    RenderObjectToWidgetElement._rebuild
(package:flutter/src/widgets/binding.dart:1182:16)
                    #746    RenderObjectToWidgetElement.mount
(package:flutter/src/widgets/binding.dart:1153:5)
                    #747    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
                    (package:flutter/src/widgets/binding.dart:1095:18)
                    #748    BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2647:19)
                    #749    RenderObjectToWidgetAdapter.attachToRenderTree
                    (package:flutter/src/widgets/binding.dart:1094:13)
                    #750    WidgetsBinding.attachRootWidget
(package:flutter/src/widgets/binding.dart:934:7)
                    #751    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
                    (package:flutter/src/widgets/binding.dart:915:7)
                    (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async,
and dart:async-patch)
                    

══════════════════════════════════════════════════════════════════════════════════════════════════
                    ══
[ +227 ms] DevFS: Creating new filesystem on the device (null)
[  +13 ms] DevFS: Created new filesystem on the device
(file:///Users/tahatesser/Library/Developer/CoreSimulator/Devices/A8AC71AD-7DA7-4AE8-8CC2-1A7C8787
F9CA/data/Containers/Data/Application/5EA2007C-6427-470B-BB9A-3F901FDE9DF2/tmp/webview-testQ144kA/
webview-test/)
[   +4 ms] Updating assets
[  +85 ms] Syncing files to device iPhone 11...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:webview_test/main.dart 4b07dab5-2e4c-4590-b178-906b9e70e781
[        ] <- 4b07dab5-2e4c-4590-b178-906b9e70e781
[   +4 ms] 
           Another exception was thrown: A RenderFlex overflowed by 99634 pixels on the right.
[  +35 ms] flutter: WebView is loading (progress : 10%)
[   +4 ms] flutter: allowing navigation to NavigationRequest(url: https://flutter.dev/,
isForMainFrame: true)
[  +17 ms] flutter: Page started loading: https://flutter.dev/
[        ] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device iPhone 11... (completed in 68ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +7 ms] Connected to _flutterView/0x7f925c01cc20.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 11 is available at:
           http://127.0.0.1:56745/AikzusVwZqI=/
[   +1 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on iPhone 11 is available at:
           http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A56745%2FAikzusVwZqI%3D%2F
[        ] 💪 Running with sound null safety 💪
[  +61 ms] flutter: WebView is loading (progress : 30%)
[ +280 ms] flutter: blocking navigation to NavigationRequest(url:
https://www.youtube.com/embed/IdrCyS7EF8M, isForMainFrame: false)}
[   +1 ms] flutter: blocking navigation to NavigationRequest(url:
https://www.youtube.com/embed/fq4N0hgOWzU?cc_lang_pref=en&cc_load_policy=1&enablejsapi=1,
isForMainFrame: false)}
[  +49 ms] flutter: WebView is loading (progress : 89%)
[ +169 ms] flutter: blocking navigation to NavigationRequest(url:
https://www.youtube.com/embed/IdrCyS7EF8M?enablejsapi=1&origin=https%3A%2F%2Fflutter.dev,
isForMainFrame: false)}
[  +23 ms] flutter: WebView is loading (progress : 89%)
[  +38 ms] flutter: WebView is loading (progress : 100%)
[        ] flutter: Page finished loading: https://flutter.dev/

```

</details>


Reproduced on the following channel
|  `stable` |
| :---: 
|  ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (11 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.5.1
    • iPhone 11 (mobile)     • A8AC71AD-7DA7-4AE8-8CC2-1A7C8787F9CA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.3
      20E232 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```
		
</details>


Are you able to run webview on iOS 14 simulator?

**Comment by markusaksli-nc** [comment] 2021-05-11 13:50
Reproducible on M1 iOS 13.7 Simulator.
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-2.0.pre.107, on macOS 11.2.3 20D91
    darwin-arm, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.107 at
      /Users/nevercode/development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 55354aa28b (3 hours ago), 2021-05-11 03:24:03 -0700
    • Engine revision 5d3dde58ef
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7322048/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7322048/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7322048/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (5 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb •
      ios            • iOS 14.5
    • iPhone 12 Pro Max (mobile)  • 70FAF0FF-11C3-4D94-A759-C6F4C0D7EF56     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • iPhone 11 Pro Max (mobile)  • 9E5DEA93-6944-486E-9290-20DEB271CEA4     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)             • macos                                    •
      darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)                • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
</details>

Tried to get crash logs from device logs but couldn't tell what exactly caused the crash. After flutter printed the listening to observatory message this was logged
```
[xpcservice<com.apple.CloudDocs.MobileDocumentsFileProvider>:48563] pid_suspend() failed with error 1: Operation not permitted
```

**Comment by cyanglaz** [comment] 2021-05-13 17:38
Closing as dup https://github.com/flutter/flutter/issues/81381

**Closed by cyanglaz** 2021-05-13 17:38 UTC
Labels: e: OS Version specific, found in release: 2.3, has reproducible steps, p: first party, p: webview, platform-host-arm, platform-ios, plugin, severe: crash
