### ISSUE TITLE
jbr jre problem. Flutter [!] Android Studio (version 2022.1) X Unable to find bundled Java version

### ISSUE THREAD

**Issue by crucifyer** [flutter/flutter#119801] opened 2023-02-02 09:40 UTC
## Steps to Reproduce

https://stackoverflow.com/questions/75115909/flutter-android-studio-version-2022-1-x-unable-to-find-bundled-java-versio

There are jbr and jre folders in the new android studio, but flutter doctor doesn't recognize jbr, so I have to copy the contents of jbr into the jre folder to make it recognized.
It needs to be modified to recognize jbr.

**Comment by danagbemava-nc** [comment] 2023-02-02 09:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/106674

**Closed by danagbemava-nc** 2023-02-02 09:55 UTC
Labels: in triage
