### ISSUE TITLE
[infra] LUCI bots determine tree greenness using the wrong order

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#90997] opened 2021-09-29 23:44 UTC
LUCI seems to be using the build order rather that the commit order to determine tree greenness, causing the tree to remain red after the fixing commit has landed. Example:

![build-status](https://user-images.githubusercontent.com/211513/135363160-4bec4382-4081-4ec5-a2fa-beaf66128542.png)

Commit 2a2e1167 was red. Then 9224a17d fixed it. However, the build jobs completed in the opposite order (probably due to some latency unpredictability):

![out-of-order-builds](https://user-images.githubusercontent.com/211513/135363264-dd2405e5-e219-4574-910a-aa2ceb06ca37.png)

This caused the tree to remain closed after the green commit landed.

**Comment by godofredoc** [comment] 2021-10-04 17:58
duplicate of https://github.com/flutter/flutter/issues/90569

**Closed by godofredoc** 2021-10-04 17:58 UTC
Labels: team, passed first triage, team: infra
