### ISSUE TITLE
my child widget gesture detector ontap function rebuild the parent widget

### ISSUE THREAD

**Issue by poojasen** [flutter/flutter#49414] opened 2020-01-24 06:31 UTC
//// the week data widget rebuild every time when lessonlist widget gesture detector on tap function called and the code below. 

```dart
  Widget getLessonList(data) {
    return Container(
        child: ListView.builder(
            scrollDirection: Axis.vertical,
            shrinkWrap: true,
            itemCount: data.length,
            physics: NeverScrollableScrollPhysics(),
            itemBuilder: (context, index) {
              return new Column(
                children: <Widget>[
                  ListTile(
                    title: GestureDetector(

                      child: Text(
                          'Lesson: ${index + 1}  ${(data[index]['Description'].length <= 35) ? (data[index]['Description']) : (data[index]['Description'].substring(0, 35) + '...')}',
                          style: TextStyle(color: Colors.grey[1000], fontSize: 14,
                            letterSpacing: 0.7,)
                      ),
                        onTap: () {
                            Navigator.of(context).push(
                              new MaterialPageRoute( builder: (BuildContext context) => new WeekDetail(
                                  week : 'Week_' + '${index + 1}',
                                  description : data[index]['Description'],
                                  videoLink: data[index]['Link'],
                                  courseId : widget.courseId,
                                  weekIndex: index,
                                ),
                              ),
                            );
                          }
                    )
                  )
                ],
              );
            }));
  }

  Widget getWeekData(data) {
    print('week list passing: $data');

    if (data != null && data.length != 0) {
      return Container(
        child: ListView.builder(
          scrollDirection: Axis.vertical,
          shrinkWrap: true,
          itemCount: data.length,
          physics: NeverScrollableScrollPhysics(),
          itemBuilder: (context, index) {
            return Padding(
              padding: EdgeInsets.only(top: 20, left: 8.0,right: 8.0),
              child: new Container(
                padding: const EdgeInsets.only(top:10.0,left: 10.0),
                  decoration: new BoxDecoration(
                    color: Colors.white,
                    border: Border.all(
                      width: 0.1, //
                    ),
                    borderRadius: BorderRadius.all(
                        Radius.circular(5.0) //
                    ),
                  ),
                  child: ExpandablePanel(
                    header: Text(
                      'Topic ${index + 1} - ${(data[index]['Weekly_description'].length <= 58) ? (data[index]['Weekly_description']) : (data[index]['Weekly_description'].substring(0, 58) + '...')} ',
                      style: TextStyle(
                          fontSize: 14,
                          letterSpacing: 0.7,
                          color: Colors.grey[1000]),
                    ),
                    expanded: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: <Widget>[
                        Flexible(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: <Widget>[
                              getLessonList(data[index]['Week_' + '${index + 1}']),
                            ],
                          ),
                        ),
                      ],
                    ),
                    tapHeaderToExpand: true,
                    hasIcon: true,
                  ),
              )
            );
          },
        ),
      );
    } else {
      return Container(
        // width: c_width,
        child: new Column(
          children: <Widget>[
            DefaultTextStyle.merge(
              style: const TextStyle(
                fontSize: 16.0,
                letterSpacing: .4,
              ),
              child: Padding(
                padding: EdgeInsets.fromLTRB(140, 50, 30, 30),
                child: new Text(
                  "No content yet",
                  style: TextStyle(
                      fontStyle: FontStyle.italic,
                      fontWeight: FontWeight.bold,
                      color: Colors.blue),
                  textAlign: TextAlign.center,
                ),
              ),
            ),
          ],
        ),
      );
    }
  }



 @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        leading: const BackButton(),
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.share),
            onPressed: () {
              Share.share('check out my website https://example.com');
            },
          ),
        ],
      ),

      floatingActionButton: Visibility(
        visible: scrollTopButton,
        child: FloatingActionButton(
          onPressed: () {

            _homeController.animateTo(
              0.0,
              curve: Curves.easeOut,
              duration: const Duration(milliseconds: 300),
            );
          },
          child: Icon(Icons.arrow_upward),
          backgroundColor: Colors.blue,
        ),
      ),

      body: new NotificationListener(
//        onNotification: (scrollNotification) {
//          if (scrollNotification is ScrollStartNotification) {
//            setState(() {
//              scrollTopButton = true;
//            });
//
//          }
//          else if (scrollNotification is ScrollEndNotification) {
//            setState(() {
//              scrollTopButton = true;
//            });
//          }
//        },
        child: SingleChildScrollView(
          controller: _homeController,
          child: new Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              textDirection: TextDirection.ltr,
              mainAxisSize: MainAxisSize.min,

              children: [
                Container(
                  child: SizedBox(
                    height: 190.0,
                    width: 520.0,
                    child: Card(
                      child: Container(
                        padding: EdgeInsets.only(left: 16.0),
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          textDirection: TextDirection.ltr,
                          children: <Widget>[
                            Text(
                              '${widget.topic}',
                              style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                  fontSize: 18,
                                  letterSpacing: 0.7,
                                  color: Colors.black),
                            ),
                            SmoothStarRating(
                                allowHalfRating: true,
                                onRatingChanged: (v) {},
                                starCount: 5,
                                rating: widget.rating,
                                size: 20.0,
                                color: Colors.redAccent,
                                borderColor: Colors.black26,
                                spacing: 0.0),
                            Text('${widget.courseName}'),
                            getNotebookButton(),
                            getSubsButton(),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
                Container(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    textDirection: TextDirection.ltr,
                    children: [
                      Row(children: <Widget>[
                        Padding(
                          padding: EdgeInsets.only(top: 15.0, left: 18.0),
                          child: new Text(
                            'About this course',
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 18,
                                letterSpacing: 0.7,
                                color: Colors.black),
                          ),
                        ),
                      ], crossAxisAlignment: CrossAxisAlignment.start),
                      getAboutCourse(),
                    ],
                  ),
                ),
//              Divider(
//                color: const Color(0xFF167F67),
//              ),
                Container(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.spaceAround,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    textDirection: TextDirection.ltr,
                    children: [
                      Column(children: <Widget>[
                        Padding(
                          padding: EdgeInsets.only(top: 20.0, left: 12.0),
                          child: new Text(
                            'Syllabus: what will you learn in this course',
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 18,
                                letterSpacing: 0.7,
                                color: Colors.black),
                          ),
                        ),
                      ], crossAxisAlignment: CrossAxisAlignment.start),
                      getWeekData(CourseDetail.weekData),
                    ],
                  ),
                ),
                Container(
                  child: Column(
                    children: <Widget>[
                      Row(children: <Widget>[
                        Padding(
                          padding: EdgeInsets.only(top: 25.0, left: 12.0),
                          child: new Text(
                            'Instructors',
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 18,
                                letterSpacing: 0.7,
                                color: Colors.black),
                          ),
                        ),
                      ], crossAxisAlignment: CrossAxisAlignment.start),
                      getInstructorListView(CourseDetail.instructor),
                    ],
                  ),
                )
              ]),
        ),
      ),
    );
  }
```

**Comment by dnfield** [comment] 2020-01-24 08:41
I strongly suspect this would be fixed by @goderbauer 's recent PR to make pushing opaque routes on the screen not rebuild what they're covering.

Could you try to checkout https://github.com/flutter/flutter/pull/49376 and see if it resolves this for you?

If not, could you try to create a smaller example?

**Comment by goderbauer** [comment] 2020-01-24 17:35
Yeah, this looks like a duplicate of #45797, which should be fixed with the PR mentioned by @dnfield.

**Comment by dnfield** [comment] 2020-01-24 17:41
I'm going to close this as a duplicate of #45797.

@poojasen - please feel free to add a comment with a smaller repro if you can demonstrate this is not related to navigator pushing opaque routes and we will reopen

**Closed by dnfield** 2020-01-24 17:41 UTC
Labels: framework, waiting for customer response
