### ISSUE TITLE
canvas.drawImageRect can't output the image

### ISSUE THREAD

**Issue by dikeboy** [flutter/flutter#25875] opened 2018-12-29 09:55 UTC
When i use the  drawRect, The out byte can display on the image widget,
But  when  i use the  drawImageRect, I found the out byte  always be the same code , and it can't display on the image widget.   But I can draw it on the  CustomPainter

If  I change the image2 to the source image, It will be ok.

How can i do  to  get the cut image

 ```RaisedButton(
                child: Text("image"),
                onPressed: (){
                var source = Rect.fromLTWH(0, 0, this.image.width.toDouble(), this.image.height.toDouble());
                var dest = Rect.fromLTWH(0,0,200,200);
                PictureRecorder recorder =  PictureRecorder();
                Canvas canvas2 = Canvas(recorder);
                Paint paint2 = new Paint();
                paint2.color =Colors.red;
                canvas2.drawRect(Rect.fromLTWH(0, 0, 150, 150), paint2);
                canvas2.drawImageRect(image, source, dest, paint2);
                var image2 = recorder.endRecording().toImage(dest.width.toInt(), dest.height.toInt());
                image2.toByteData(format:ui.ImageByteFormat.png).then((byte){
                  imageDes=   Uint8List.view(byte.buffer);
                var mByte=byte.buffer.asUint8List();
                print("aaa ${mByte}");
                getApplicationDocumentsDirectory().then((dir){
                String path = dir.path +"/test.png";
                new File(path).writeAsBytesSync(mByte);
                print(path);
                });
                setState(() {
                  imageDes =mByte;
                });
                });
               print(imageDes);
            Navigator.push(context,new MaterialPageRoute(builder: (context) =>  ImageTestPage(title: "image",image: byte.buffer.asUint8List())));
         },
       );
            }),` ` 
` 


`class SignaturePainter extends CustomPainter {
  SignaturePainter(this.points,this.isStart,this.width,this.height,this.cWidth,this.cHeight,this.image);
  bool  isStart = false;
  double startX=0;
  double startY=0;
  double cWidth =200;
  double cHeight =200;
  double width;
  double height;
  flutterui.Image image;

  final List<Offset> points; 

  void paint(Canvas canvas, Size size) {
    Paint paint = new Paint()
      ..color = Colors.blue[200]
      ..strokeCap = StrokeCap.round
      ..isAntiAlias = true
      ..strokeWidth = 2.0

      ..strokeJoin = StrokeJoin.bevel;
//    print("change ${this.points}");
    if(image!=null){

      double dwidth =0;
      double dheight =0;
      if(image.width.toDouble()/width>image.height.toDouble()/height){
        dwidth = width;
        dheight = image.height.toDouble()*dwidth/image.width.toDouble();
      }
      else{
        dheight = height;
        dwidth = image.width.toDouble() * dheight/image.height.toDouble();
      }
      canvas.drawImageRect(image, Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble()), Rect.fromLTWH((width-dwidth)/2,
          (height-dheight)/2, dwidth,dheight), paint);

//      var source = Rect.fromLTWH(0, 0, this.image.width.toDouble(), this.image.height.toDouble());
//      var dest = Rect.fromLTWH(0,0,400,400);
//      PictureRecorder recorder =  PictureRecorder();
//      Canvas canvas2 = Canvas(recorder);
//      Paint paint2 = new Paint();
//      canvas2.drawImageRect(image, source, dest, paint2);
//      var image2 = recorder.endRecording().toImage(dest.width.toInt(), dest.height.toInt());
////    canvas.drawImageRect(image2, Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble()), Rect.fromLTWH(0,0,400,400), paint);
//      image2.toByteData(format:ui.ImageByteFormat.png).then((byte){
//        var mByte=byte.buffer.asUint8List();
//        print("aaa ${mByte}");
//        getApplicationDocumentsDirectory().then((dir){
//          String path = dir.path +"/test.png";
//          new File(path).writeAsBytesSync(mByte);
//          print(path);
//        });
//      });
    }

    if(this.points.length>1){
      double startX = points[1].dx - points[0].dx+points[2].dx;
      double startY = points[1].dy - points[0].dy+points[2].dy;
      if(startX<0)
        startX = 0;
      else if(startX+cWidth>width){
        startX = width-cWidth;
      }
      if(startY<0)
        startY=0;
      else if(startY + cHeight>height){
        startY = height-cHeight;
      }
//      canvas.drawRect(Rect.fromLTRB(startX,startY,startX+200,startY+200), paint);
      List<Offset> points2 =[
        Offset(startX,startY),
        Offset(startX+cWidth,startY),
        Offset(startX+cWidth,startY+cHeight),
        Offset(startX,startY+cHeight),
        Offset(startX,startY),
      ];
      canvas.drawPoints(PointMode.polygon, points2, paint);
    }
    else{
      List<Offset> points2 =[
        Offset(startX,startY),
        Offset(startX+cWidth,startY),
        Offset(startX+cWidth,startY+cHeight),
        Offset(startX,startY+cHeight),
        Offset(startX,startY),
      ];
      canvas.drawPoints(PointMode.polygon, points2, paint);
    }

  }`

**Comment by zoechi** [comment] 2018-12-30 16:11
I assume this is a 
Duplicate of #23621

**Closed by zoechi** 2018-12-30 16:11 UTC
