### ISSUE TITLE
Flutter-engine 3.13.0 fails to cross compile for embedded linux at analytics_manager.dart. The method 'send' isn't defined for the class 'Analytics'.

### ISSUE THREAD

**Issue by aduskett** [flutter/flutter#132765] opened 2023-08-17 16:47 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`git clone https://gitlab.com/aduskett/buildroot-flutter.git -b flutter-3.13.0-dev && cd buildroot-flutter && make flutter_x86_64_efi_demo_defconfig && make flutter-engine-depends -Otarget -j$(nproc) && make flutter-engine`

### Expected results

A cross-compiled libflutter_engine.so file.

Note: This is using https://buildroot.org/, an embedded Linux SDK like Yocto. This is not using a custom flutter buildroot.
Also note: 3.10.6 compiles without error and works properly with the exact same arguments. If you wish to revert to 3.10.6 for testing, change the FLUTTER_ENGINE_VERSION line in the `package/flutter-engine/flutter-engine.mk` file and run the following commands: `make flutter_x86_64_efi_demo_defconfig && make clean && make flutter-engine-depends -j$(nproc) -Otarget && make flutter-engine`

### Actual results

analytics_manager.dart:224:23: Error: The method 'send' isn't defined for the class 'Analytics'.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
FAILED: gen/third_party/dart/utils/analysis_server/analysis_server.dart.dill 
vpython3 ../../third_party/dart/build/gn_run_binary.py compiled_action ../../third_party/dart/tools/sdks/dart-sdk/bin/dart -Dsdk_hash=1b9c3b35ce --dfe=../../third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot gen/third_party/dart/utils/gen_kernel/bootstrap_gen_kernel.dill --packages=../../third_party/dart/.dart_tool/package_config.json --platform=vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=gen/third_party/dart/utils/analysis_server/analysis_server.dart.dill --depfile=gen/third_party/dart/utils/analysis_server/analysis_server.dart.dill.d -Dsdk_hash=1b9c3b35ce -Ddart.vm.product=true ../../third_party/dart/pkg/analysis_server/bin/server.dart
Command failed: /home/adam/Downloads/buildroot-flutter/output/build/flutter-engine-3.13.0/third_party/dart/tools/sdks/dart-sdk/bin/dart -Dsdk_hash=1b9c3b35ce --dfe=../../third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot gen/third_party/dart/utils/gen_kernel/bootstrap_gen_kernel.dill --packages=../../third_party/dart/.dart_tool/package_config.json --platform=vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=gen/third_party/dart/utils/analysis_server/analysis_server.dart.dill --depfile=gen/third_party/dart/utils/analysis_server/analysis_server.dart.dill.d -Dsdk_hash=1b9c3b35ce -Ddart.vm.product=true ../../third_party/dart/pkg/analysis_server/bin/server.dart
output: ../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:224:23: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
      await analytics.send(Event.memoryInfo(
                      ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:224:28: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
      await analytics.send(Event.memoryInfo(
                           ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:232:21: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
    await analytics.send(Event.memoryInfo(
                    ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:232:26: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
    await analytics.send(Event.memoryInfo(
                         ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:472:23: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
      await analytics.send(Event.contextStructure(
                      ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:472:28: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
      await analytics.send(Event.contextStructure(
                           ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:496:25: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
        await analytics.send(Event.lintUsageCount(
                        ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:496:30: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
        await analytics.send(Event.lintUsageCount(
                             ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:510:25: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
        await analytics.send(Event.clientNotification(
                        ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:510:30: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
        await analytics.send(Event.clientNotification(
                             ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:537:27: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
          await analytics.send(Event.pluginRequest(
                          ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:537:32: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
          await analytics.send(Event.pluginRequest(
                               ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:553:25: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
        await analytics.send(Event.clientRequest(
                        ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:553:30: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
        await analytics.send(Event.clientRequest(
                             ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:570:29: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
            await analytics.send(Event.commandExecuted(
                            ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:570:34: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
            await analytics.send(Event.commandExecuted(
                                 ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:588:21: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
    await analytics.send(Event.serverSession(
                    ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:588:26: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
    await analytics.send(Event.serverSession(
                         ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:596:23: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
      await analytics.send(Event.pluginUse(
                      ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:596:28: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
      await analytics.send(Event.pluginUse(
                           ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:610:25: Error: The method 'send' isn't defined for the class 'Analytics'.
 - 'Analytics' is from 'package:unified_analytics/src/analytics.dart' ('../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart').
Try correcting the name to the name of an existing method, or defining a method named 'send'.
        await analytics.send(Event.severityAdjustment(
                        ^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:610:30: Error: The getter 'Event' isn't defined for the class 'AnalyticsManager'.
 - 'AnalyticsManager' is from 'package:analysis_server/src/analytics/analytics_manager.dart' ('../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Event'.
        await analytics.send(Event.severityAdjustment(
                             ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/noop_analytics.dart:46:26: Error: Type 'Event' not found.
  Future<Response>? send(Event event) {
                         ^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/noop_analytics.dart:10:7: Error: The non-abstract class 'NoopAnalytics' is missing implementations for these members:
 - Analytics.sendEvent
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class NoopAnalytics implements Analytics {
      ^^^^^^^^^^^^^
../../third_party/dart/third_party/pkg/tools/pkgs/unified_analytics/lib/src/analytics.dart:246:21: Context: 'Analytics.sendEvent' is defined here.
  Future<Response>? sendEvent({
                    ^^^^^^^^^
../../third_party/dart/pkg/analysis_server/lib/src/analytics/noop_analytics.dart:46:26: Error: 'Event' isn't a type.
  Future<Response>? send(Event event) {
                         ^^^^^
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2023-08-18 08:37
Hi @aduskett 
Looks like it's caused by API changes between channels. Can you confirm this on the master channel as well?

**Comment by r3flow** [comment] 2023-08-25 19:15
I can confirm that this problem exists in 3.14.0-0.1.pre and the master channel as well. 

I have tried the master hash (25 Aug. cb58abd773268d62008120f270759cb9a3904f11) with dart-sdk ab417bc74bb1a81acbb3b981d440d4bfe68f5051 (3.2.0-97.0.dev).

```
| Command failed: /home/build/cadsp3-kirkstone-build/raspberrypi4-64/tmp/work/cortexa72-poky-linux/flutter-engine/git-r0/src/third_party/dart/tools/sdks/dart-sdk/bin/dart -Dsdk_hash=ab417bc74b --dfe=../../third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot gen/third_party/dart/utils/gen_kernel/bootstrap_gen_kernel.dill --packages=../../third_party/dart/.dart_tool/package_config.json --platform=vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=gen/third_party/dart/utils/analysis_server/analysis_server.dart.dill --depfile=gen/third_party/dart/utils/analysis_server/analysis_server.dart.dill.d -Dsdk_hash=ab417bc74b -Ddart.vm.product=false ../../third_party/dart/pkg/analysis_server/bin/server.dart
| output: Error: Couldn't resolve the package 'linter' in 'package:linter/src/rules.dart'.
| ../../third_party/dart/pkg/analysis_server/lib/src/analytics/analytics_manager.dart:223:23: Error: The method 'send' isn't defined for the class 'Analytics'.
```

**Comment by aduskett** [comment] 2023-08-25 20:16
Thanks @r3flow I was going to test it today!

**Comment by aduskett** [comment] 2023-08-28 17:15
Happens with 3.14 beta as well.

**Comment by chinmaygarde** [comment] 2023-08-28 17:40
Triage: This seems to be happening because the dart SDK is being built from source instead of a pre-built. cc @zanderso who might know what is going on.

**Comment by zanderso** [comment] 2023-08-28 20:35
Unfortunately, we'll probably only be able to help track this down if it reproduces with a checkout of the Engine that's obtained following the instructions on our wiki. We currently lack the resources to support building the engine with custom toolchains, buildroots, etc. If you obtain a checkout following the wiki instructions, and still can't build on `main` (or on a recent release branch) then we'll be able to help track that down. In the meantime, I'll go ahead and close this.

**Closed by zanderso** 2023-08-28 20:35 UTC
Labels: c: regression, engine, platform-linux, P2, team-engine, triaged-engine

**Comment by aduskett** [comment] 2023-08-28 20:53
@zanderso This isn't using a custom buildroot. As stated in the original post, this uses buildroot from http://www.buildroot.org, an embedded Linux SDK much like Yocto. If a pre-built dart SDK is necessary to build the flutter-engine package, why include the option --no-prebuilt-dart-sdk?

Looking at the wiki (how I created the buildroot packages in the first place), I don't see anything I'm not doing. You can take a look at the current patch here: https://patchwork.ozlabs.org/project/buildroot/patch/20230828175858.309974-5-adam.duskett@amarulasolutions.com/

Again, I have to insist that this is a regression. 3.10.6 works fine; the latest releases do not.

**Comment by aduskett** [comment] 2023-08-29 02:27
This problem boiled down to me copying the meta-flutter repo and then porting the flutter-engine recipe without understanding the .gclient file properly. 
The Yocto .gclient file has the following:

```

"custom_deps": {
    "src/third_party/dart/third_party/pkg/tools": "https://dart.googlesource.com/tools.git@unified_analytics-v1.1.0"
 }

Which, I guess, is for more analytic reporting? Either way, Buildroot does not want nor need tracking or analytic reporting, mainly when the customer doesn't expressly consent.  Removing those lines fixed the problem.
```
