### ISSUE TITLE
[Flutter 2.5.0] ThemeData.primaryColor does not take effect

### ISSUE THREAD

**Issue by ggdream** [flutter/flutter#89839] opened 2021-09-10 10:41 UTC
## Steps to Reproduce
Just run app on Flutter 2.5.0
~~~dart
 static final global = ThemeData(
    primaryColor: ColorsX.primary,
)
~~~
There is no problem on 2.2.3, but 2.5.0 is displayed as the default blue color and does not work.

Env
~~~sh
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.18362.1082], locale zh-CN)
    • Flutter version 2.5.0 at F:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at F:\android\SDK
    • Platform android-30, build-tools 31.0.0
    • ANDROID_HOME = F:\android\SDK
    • Java binary at: F:\jetbrains\apps\AndroidStudio\ch-0\202.7351085\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.2)
    • Android Studio at F:\jetbrains\apps\AndroidStudio\ch-0\202.7351085
    • Flutter plugin version 59.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18362.1082]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.84

• No issues found!

~~~

**Comment by maheshmnj** [comment] 2021-09-10 11:13
Hi @ggdream, Thanks for filing the issue. I can reproduce the issue, `primary color` does not take effect. There's an ongoing [change in progress](https://github.com/flutter/flutter/issues/36624 ) to migrate to ColorScheme. But I believe this bug is not intentional.  

However, you can set the `primaryColor` as of now using [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html)

```dart
theme: ThemeData(
        colorScheme: ColorScheme.light().copyWith(primary:  ColorsX.primary,),
      ),
```

Labeling this issue as a bug for further investigation 

cc @HansMuller

**Comment by ggdream** [comment] 2021-09-10 11:17
> Hi @ggdream, Thanks for filing the issue. I can reproduce the issue, `primary color` does not take effect. There's an ongoing [change in progress](https://github.com/flutter/flutter/issues/36624) to migrate to ColorScheme. But I believe this bug is not intentional.
> 
> However, you can set the `primaryColor` as of now using [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html)
> 
> ```dart
> theme: ThemeData(
>         colorScheme: ColorScheme.light().copyWith(primary:  ColorsX.primary,),
>       ),
> ```
> 
> Labeling this issue as a bug for further investigation
> 
> cc @HansMuller

I will try it, thank you for the reply and the solution.

**Comment by efraimbart** [comment] 2021-09-14 02:58
When setting the primary color via `primaryColor`, did it take into account text that would be affected by the change? With `colorScheme` it definitely does not.

> Hi @ggdream, Thanks for filing the issue. I can reproduce the issue, `primary color` does not take effect. There's an ongoing [work in progress](https://github.com/flutter/flutter/issues/36624) to migrate to ColorScheme. But I believe this change (primaryColor) is not intentional.
> 
> However, you can set the `primaryColor` as of now using [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html)
> 
> ```dart
> theme: ThemeData(
>         colorScheme: ColorScheme.light().copyWith(primary:  ColorsX.primary,),
>       ),
> ```
> 
> Labeling this issue as a bug for further investigation
> 
> flutter doctor -v
> cc @HansMuller

**Comment by darrenaustin** [comment] 2021-09-14 19:07
This was part of the work that we are doing to [clean up the Theme system](https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit#heading=h.pub7jnop54q0) and make everything more consistent and based off of the `ColorScheme` colors.

In this case the AppBar's default background color was changed to use `ColorScheme.primary` as part of #71184. 

We will eventually be moving all components away from `ThemeData.primaryColor`. As mentioned by @maheshmnj above, you can fix this by also providing a color scheme with the same primary color that you desire:

```dart
   theme: ThemeData(
     primaryColor: ColorsX.primary,
     colorScheme: ColorScheme.light().copyWith(primary: ColorsX.primary),
  );
```

Closing this as it is working as intended.

**Closed by darrenaustin** 2021-09-14 19:07 UTC
Labels: severe: regression, framework, f: material design, has reproducible steps, found in release: 2.5, found in release: 2.6

**Comment by efraimbart** [comment] 2021-09-14 19:29
One can temporarily use `backwardsCompatibility: true,` in the app bar to revert to `ThemeData.primaryColor`.

**Comment by efraimbart** [comment] 2021-09-14 19:35
@darrenaustin When using `ThemeData.primaryColor` for the app bar the text color is automatically set to something that contrasts with it, but when using `ColorScheme` that is not the case. Is something like `colorScheme: ColorScheme.light().copyWith(primary: ColorsX.primary)` considered bad practice as one should always be using a complementing and complete `ColorScheme` rather than just overriding one of a given one's properties?

**Comment by efraimbart** [comment] 2021-09-14 19:38
I'm not sure whose responsibility this is, but you guys should consider updating the reference to `ThemeData.primaryColor` in [codelabs](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#6)

**Comment by ggdream** [comment] 2021-09-15 00:35
Thanks all.
