### ISSUE TITLE
`const` decorated child widget didn't update when parent call `setState`

### ISSUE THREAD

**Issue by narumishi** [flutter/flutter#89974] opened 2021-09-13 10:02 UTC
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: HomePage());
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int count=0;
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            print('call setState');
            count++;
          });
        },
        child: Icon(Icons.refresh),
      ),
      body: Column(
        children: [
          // add const here
          const ChildWidget(name: 'Child A'),
          ChildWidget(name: 'Child B'),
        ],
      ),
    );
  }
}

class ChildWidget extends StatefulWidget {
  final String name;

  const ChildWidget({Key? key, required this.name}) : super(key: key);

  @override
  _ChildWidgetState createState() => _ChildWidgetState();
}

class _ChildWidgetState extends State<ChildWidget> {
  @override
  Widget build(BuildContext context) {
    print('building child widget: ${widget.name}');
    return Center(child: Text(widget.name));
  }
}
```

**Expected results:** all child widgets rebuild whenever `const` or not.

**Actual results:** only child B rebuild.
console log
```
Running "flutter pub get" in test_bug...
Launching lib/main.dart on macOS in debug mode...
Building macOS application...
Debug service listening on ws://127.0.0.1:61325/7KNvyp2ML7g=/ws
Syncing files to device macOS...
flutter: building child widget: Child A
flutter: building child widget: Child B
flutter: call setState
flutter: building child widget: Child B
flutter: call setState
flutter: building child widget: Child B
```

**flutter_lints** suggest me to add `const` decorated, but const child never rebuild on parent `setState`.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 2.5.0, on macOS 11.3.1 20E241 darwin-x64, locale en-CN)
    • Flutter version 2.5.0 at /Users/narumi/Library/flutter-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/narumi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/narumi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/narumi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/narumi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

**Comment by narumishi** [comment] 2021-09-13 10:06
I guess, maybe when checking which child should rebuild, there is such a validation: `thisWidget==oldWidget`, but since it's `const` and no parameters, so this equation always return true?

**Comment by maheshmnj** [comment] 2021-09-13 11:06
Hi @narumishi If the instance of a widget `ChildWidget` doesn't change then they are not rebuilt, Assigning a const indicates that the instance will always be the same and hence they are not rebuilt, So this is intended behavior, Closing the issue as invalid, If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-13 11:06 UTC
Labels: in triage

**Comment by narumishi** [comment] 2021-09-13 11:12
@maheshmnj thanks for your reply. I agree with your points. But what bothers me is `flutter_lints` let me add `const` for stateful widget's class constructor, which should rebuild when parent update. 

I need to add `// ignore: prefer_const_constructors_in_immutables` for many classes.

Is there any other nice solution except marking ignore?

**Comment by maheshmnj** [comment] 2021-09-13 11:57
To ignore a specific you could turn it off in `analysis_options.yaml` file 

```
linter:
  rules:
    prefer_const_constructors_in_immutables: false
```

please take a look at this docs https://dart.dev/guides/language/analysis-options

**Comment by narumishi** [comment] 2021-09-13 15:17
@maheshmnj thanks, does help.
