### ISSUE TITLE
Poor performance with blurred list contents

### ISSUE THREAD

**Issue by AndrsDev** [flutter/flutter#26830] opened 2019-01-21 01:17 UTC
I've noticed that With FHD+ screens the `ListView.builder` scroll action looses FPS. When I change the screen resolution of my phone to HD, the scroll animation is the smoothest experience. My guess is that the widgets I'm trying to scroll are two heavy (these components include images, shadows, and stack widgets).
 
Maybe a performance improvement could be to temporarily downgrade the viewport resolution of the widget while scroll action is performed. 

## Example code
Because of the asset files, you can run the app from this example project. Code where it has the `ListView.builder` is on file lib/screens/profile.dart on line 92.

[platzi_reto.zip](https://github.com/flutter/flutter/files/2780505/platzi_reto.zip)

#### steps to reproduce
1. Run the app on release mode
2. Go to section "Profile" on buttonNavigationBar
3. Scroll the list of widgets. 

## Flutter doctor:
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [VersiÃ³n 10.0.17134.523], locale es-GT)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Developer\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Developer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • ANE LX3 • 6NUDU18605002140 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by davidmartos96** [comment] 2019-01-21 07:18
Have you tried running it like `flutter run --profile`?. Otherwise it could be laggy in some cases.

**Comment by AndrsDev** [comment] 2019-01-21 21:07
@davidmartos96 yes I have, indeed I ran the project on release mode on a physical device. 
@zoechi all done!!! review the chenges on the original post

**Comment by AndrsDev** [comment] 2019-01-22 01:13
I've been testing and found out that the `CupertinoTabBar` widget significally decreases performance. Repacing it with `BottomNavigationBar` provided on the material.package seems to be a good alternative. Probably is because the opacity that  `CupertinoTabBar` has is hard for the GPU thread. Anyway performance on cupertino.dart widgets should be improved

**Comment by jonahwilliams** [comment] 2019-01-22 02:17
If the performance impact of the CupertinoTabBar is that noticeable we shouldn't close this issue

**Comment by xster** [comment] 2019-02-07 21:36
Shuffling the tags a bit. Unfortunately blurs are expensive.

**Comment by TahaTesser** [comment] 2020-09-23 13:48
Running `1080x2400 pixels` device, which i believe is FHD+  and the scrolling is smooth  using your code sample (in a new project due to gradle issues in your zip project)

[Record_2020-09-23-19-13-50_f0a5da16151fb602eeacb67ea37fa49e.mp4.zip](https://github.com/flutter/flutter/files/5268544/Record_2020-09-23-19-13-50_f0a5da16151fb602eeacb67ea37fa49e.mp4.zip)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.317, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.317 at /home/taha/Code/flutter_master
    • Framework revision 10febea877 (6 hours ago), 2020-09-23 07:22:10 +0200
    • Engine revision 57ee3d4b32
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details> 

Are you still experiencing this issue? 

If yes, can you please provide your `flutter doctor -v` with latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by TahaTesser** [comment] 2020-10-16 12:42
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-16 12:42 UTC
Labels: P4, engine, framework, severe: performance
