### ISSUE TITLE
[image_picker] Missing exif tags in resized images

### ISSUE THREAD

**Issue by RobertOdrowaz** [flutter/flutter#132827] opened 2023-08-18 06:59 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

image_picker

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      sha256: "841837258e0b42c80946c43443054fc726f5e8aa84a97f363eb9ef0d45b33c14"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
  image_picker_android:
    dependency: transitive
    description:
      name: image_picker_android
      sha256: "8179b54039b50eee561676232304f487602e2950ffb3e8995ed9034d6505ca34"
      url: "https://pub.dev"
    source: hosted
    version: "0.8.7+4"
  image_picker_for_web:
    dependency: transitive
    description:
      name: image_picker_for_web
      sha256: "8b6c160cdbe572199103a091c783685b236110e4a0fd7a4947f32ff5b7da8765"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"
  image_picker_ios:
    dependency: transitive
    description:
      name: image_picker_ios
      sha256: b3e2f21feb28b24dd73a35d7ad6e83f568337c70afab5eabac876e23803f264b
      url: "https://pub.dev"
    source: hosted
    version: "0.8.8"
  image_picker_linux:
    dependency: transitive
    description:
      name: image_picker_linux
      sha256: "02cbc21fe1706b97942b575966e5fbbeaac535e76deef70d3a242e4afb857831"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1"
  image_picker_macos:
    dependency: transitive
    description:
      name: image_picker_macos
      sha256: cee2aa86c56780c13af2c77b5f2f72973464db204569e1ba2dd744459a065af4
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1"
  image_picker_platform_interface:
    dependency: transitive
    description:
      name: image_picker_platform_interface
      sha256: c1134543ae2187e85299996d21c526b2f403854994026d575ae4cf30d7bb2a32
      url: "https://pub.dev"
    source: hosted
    version: "2.9.0"
  image_picker_windows:
    dependency: transitive
    description:
      name: image_picker_windows
      sha256: c3066601ea42113922232c7b7b3330a2d86f029f685bba99d82c30e799914952
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1"
```

</details>

### Steps to reproduce

1. Call pickImage with `maxWidth` and/or `maxHeight` arguments
2. Select photo bigger than specified dimensions
3. Check received photo exif data

### Expected results

Resided photo contains DateTimeOriginal tag

### Actual results

Missing DateTimeOriginal tag

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:native_exif/native_exif.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Column(
            children: [
              ElevatedButton(
                child: Text('Pick image resized (100px)'),
                onPressed: () async {
                  final image = await ImagePicker().pickImage(
                    source: ImageSource.gallery,
                    maxHeight: 100,
                    maxWidth: 100,
                  );

                  final exif = await Exif.fromPath(image!.path);

                  print(
                      'resized original date: ${await exif.getOriginalDate()}');
                },
              ),
              ElevatedButton(
                child: const Text('Pick image'),
                onPressed: () async {
                  final image = await ImagePicker()
                      .pickImage(source: ImageSource.gallery);

                  final exif = await Exif.fromPath(image!.path);

                  print(
                      'non-resized original date: ${await exif.getOriginalDate()}');
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="521" alt="image" src="https://github.com/flutter/flutter/assets/9675199/e632cda6-2b1e-4b09-a253-efcc0813d4c1">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.0.1 22A400 darwin-arm64, locale en-PL)
    • Flutter version 3.7.12 on channel stable at /Users/robert/fvm/versions/3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (4 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/robert/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-08-18 11:34
Hi @RobertOdrowaz. Thanks for filing this. Tried reproducing this and can't seem to reproduce on my end. I see you are on an older version of flutter and similar issues have been closed as fixed. Can you upgrade to the latest flutter version to confirm this issue still persists? If it does, kindly attach samples of the images you are testing with.

**Comment by RobertOdrowaz** [comment] 2023-08-18 12:17
I've tried on flutter 3.13.0 and the issue still persists. 

FYI I know what is causing this issue and have submitted a pull request to resolve it https://github.com/flutter/packages/pull/4738. The problem is that preserved tags are explicitly listed in `ExifDataCopier` (which seems to be necessary because of `ExifInterface` api) and many of them are missing including DateTimeOriginal which is important for.
https://github.com/flutter/packages/blob/main/packages/image_picker/image_picker_android/android/src/main/java/io/flutter/plugins/imagepicker/ExifDataCopier.java#L18

You can try to reproduce with this image 
![photo](https://github.com/flutter/flutter/assets/9675199/48beaae9-ae58-484f-a9f5-405c121dd9de)

**Comment by dam-ease** [comment] 2023-08-21 09:34
Hi @RobertOdrowaz. Thanks for your response. I am able to reproduce this on the latest `master` and `stable` channels. This seems to be reproducible only on Android as I couldn't replicate same behaviour on iOS.

<details><summary>Log</summary>
<p>

```
I/flutter ( 5613): non-resized original date: 2023-02-14 18:55:19.000
D/EGL_emulation( 5613): app_time_stats: avg=1466.29ms min=1466.29ms max=1466.29ms count=1
D/EGL_emulation( 5613): app_time_stats: avg=69.19ms min=9.59ms max=1746.89ms count=34
I/flutter ( 5613): resized original date: null
``` 

</p>
</details> 

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.0 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (5 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14
      (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0
      22A380 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 
```
[✓] Flutter (Channel master, 3.14.0-8.0.pre.21, on macOS 13.0 22A380 darwin-arm64, locale en-NG)
    • Flutter version 3.14.0-8.0.pre.21 on channel master at /Users/damilolaalimi/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c328d03928 (6 hours ago), 2023-08-20 23:21:32 -0400
    • Engine revision e7d7451117
    • Dart version 3.2.0 (build 3.2.0-90.0.dev)
    • DevTools version 2.26.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by Vavinci** [comment] 2023-09-07 21:20
I am seeing a similar issue where GPS information is missing or rather set to 0 and in my case I am not resizing the image. 

This is what output looks like
GPS GPSLatitudeRef: 
GPS GPSLatitude: [0/0, 0/0, 0/0]
GPS GPSLongitudeRef: 
GPS GPSLongitude: [0/0, 0/0, 0/0]
GPS GPSAltitudeRef: 0
GPS GPSAltitude: 0/0

The Image has GPS information. I ran this on IOS and it works fine there. Seems to be an android issue.

**Comment by gmackall** [comment] 2023-09-19 19:24
closing as resolved in https://github.com/flutter/packages/pull/4738

**Closed by gmackall** 2023-09-19 19:24 UTC
Labels: platform-android, p: image_picker, package, has reproducible steps, P2, team-android, triaged-android, found in release: 3.13, found in release: 3.14
