### ISSUE TITLE
ARkit plugin (image anchor )

### ISSUE THREAD

**Issue by rubenteste** [flutter/flutter#78986] opened 2021-03-24 17:25 UTC
Hello,
  I am making an application using flutter and I am using AR.
  I already managed to use the arkit, but with images for anchors, if the images are very similar the plugin will confuse the images and will not work well.
      Does anyone know any solutions to detect similar images?

**Comment by iapicca** [comment] 2021-03-24 17:44
@rubenteste 
this issue doesn't seem to describe a bug or a feature request
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or ask on [discord](https://discord.gg/N7Yshp4), [reddit](https://www.reddit.com/r/FlutterDev/) and [slack](https://fluttercommunity.dev/joinslack)

**Comment by darshankawar** [comment] 2021-03-25 09:30
@rubenteste 
Assuming you are referring to and using `arkit_flutter_plugin`, I suggest you to ask this question in dedicated repo: https://github.com/olexale/arkit_flutter_plugin/issues

Closing from here, as it's not a bug or feature request as mentioned above.
Thanks.

**Closed by darshankawar** 2021-03-25 09:30 UTC
Labels: in triage
