### ISSUE TITLE
How to reuse a stateful widget in flutter with the exact state it has?

### ISSUE THREAD

**Issue by meowofficial** [flutter/flutter#41023] opened 2019-09-21 13:08 UTC
I am trying to make a simple page slider.
This is how transition looks like:

![0MJ2e (3)](https://user-images.githubusercontent.com/35203503/65373659-c84b5d00-dc99-11e9-89b7-c1919a6cb98a.jpg)![Ax5sg (3)](https://user-images.githubusercontent.com/35203503/65373660-c84b5d00-dc99-11e9-9bd7-691284fd93a6.jpg)

I set random color in initState of page widget. This is function that builds slider depending on current state (sliding or not):

```
Widget _buildPages() {
    switch (_transitionType) {
      case TransitionType.none:
        return _currentPage;
      case TransitionType.sliding:
        return Stack(
          children: [
            AbsorbPointer(
              absorbing: _slideAnimationController.isAnimating,
              child: _currentPage,
            ),
            AbsorbPointer(
              absorbing: _slideAnimationController.isAnimating,
              child: SlideTransition(
                position: _slideAnimation,
                child: _nextPage,
              ),
            ),
          ],
        );
    }
  }
```

Initial `_transitionType` is `TransitionType.none`. When I press `next` button it becomes `TransitionType.sliding`. The problem is I can't reuse `_currentPage` widget with the exact state it has (`initState` always is called in spite of the fact I initialize widget only once). You can see it on screenshots (first page color is changed when transition starts).

Can you please help me?

**Comment by BondarenkoStas** [comment] 2019-09-21 17:03
@meowofficial This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to the implementation. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.

**Comment by meowofficial** [comment] 2019-09-21 17:40
My question relate to unexpected behavior of method `initState`. As I said, widget is initialized once, but `initState` is called multiple times. So I posted this issue to get an explanation of that behavior and ways to fix.

**Comment by nt4f04uNd** [comment] 2019-10-13 16:37
@meowofficial my suggestion is to calculate next and current colors in parent and just pass them into children, or, a better option, just create in parent class fields with `UniqueKeys` and update them whenever you need to update children state

**Comment by pedromassangocode** [comment] 2020-08-18 12:45
Hi @meowofficial 
Are you still facing this issue? If yes then please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by TahaTesser** [comment] 2020-09-09 14:49
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-09-09 14:49 UTC
Labels: framework
