### ISSUE TITLE
InputDatePickerFormField not respecting ambient locale

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#68044] opened 2020-10-13 19:32 UTC
The `InputDatePickerFormField` docs say:

> When the field is saved or submitted, the text will be parsed into a [DateTime] according to the ambient locale's compact date format

But it should also show the date input text form as the current locale.

My locale is `pt_BR`, confirmed by running `print(Intl.systemLocale);` under `build()`:

![image](https://user-images.githubusercontent.com/8120472/95907131-79270d00-0d71-11eb-84c6-0d9f4ef11bde.png)

And this is what is shown:

![image](https://user-images.githubusercontent.com/8120472/95907175-87752900-0d71-11eb-9cbc-53d05c17a71a.png)

`mm/dd/yyyy` is a `en_US` date standard, in Brazil (`pt_BR` we use `dd/mm/yyyy` and `InputDatePickerFormField` fails to automatically switch to it.

The `fieldHintText` docs say:

```dart
/// The hint text displayed in the [TextField].
///
/// If this is null, it will default to the date format string. For example,
/// 'mm/dd/yyyy' for en_US.
```

Which leads me to believe that it will get the ambient locale's string format, but it doesn't.

**Comment by HansMuller** [comment] 2020-10-13 23:03
CC @darrenaustin

**Comment by feinstein** [comment] 2020-10-14 06:56
Ok, I figured it out, I didn't configure any localization on Flutter for this App as its only supposed to be used in Brazil.

I think the localized widgets should default to the system locale if no localization information was configured into the `MaterialApp`.

**Comment by TahaTesser** [comment] 2020-10-15 13:47
Hi @feinstein 
We discussed this on another issue  https://github.com/flutter/flutter/issues/68055
Closing as duplicate of https://github.com/flutter/flutter/issues/68055

**Closed by TahaTesser** 2020-10-15 13:47 UTC
Labels: a: internationalization, f: date/time picker, f: material design, framework
