### ISSUE TITLE
The method pumpAndSettle() don't wait for the widget to finish.

### ISSUE THREAD

**Issue by Gusttavogs** [flutter/flutter#95912] opened 2021-12-28 18:01 UTC
I have a question about the flutter integration test.

In the integration test we have `pumpAndSettle()`, which is used to wait for widget to finish, but there are times in tests I have wait for a external API and I need to put for example `pumpAndSettle(const Duration(seconds: 5))` because the `pumpAndSettle` alone does not solve. 

My question is, does flutter have another way for me to wait for the widget is finished or it have a method of intercept and wait a external API request.

**Comment by navaronbracke** [comment] 2021-12-28 19:41
Actually waiting on a _real_ API request during tests is a bad practice. Use a test stub / mock class for your API calls that return a value like `Future.value(myFakeApiResponse)`.

**Comment by maheshmnj** [comment] 2021-12-29 07:10
Hi @Gusttavogs,  This is working as intended when you don't pass a duration to `pumpAndSettle` it pumps for 100 milliseconds. Passing a duration seems to be the right way  for more please refer the docs https://api.flutter.dev/flutter/flutter_test/WidgetTester/pumpAndSettle.html

Closing as this is neither a bug nor a feature request.

**Closed by maheshmnj** 2021-12-29 07:10 UTC
Labels: in triage
