### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by amirsaleemahmad** [flutter/flutter#69191] opened 2020-10-28 13:54 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=edge --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:47:7)
<asynchronous suspension>
#1      AppInspector.contextId (package:dwds/src/debugging/inspector.dart:156:50)
#2      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:497:26)
#3      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:98:40)
<asynchronous suspension>
#4      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#5      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:171:37)
<asynchronous suspension>
#6      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:138:23)
#7      DebugService.start (package:dwds/src/services/debug_service.dart:142:55)
#8      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:184:25)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#15     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
```
[✓] Flutter (Channel beta, 1.22.1, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.1 at C:\flutter
    • Framework revision f30b7f4db9 (3 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\amirs\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.49.1)
    • VS Code at C:\Users\amirs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.56

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: abfad9cc4994b61de64c9ef1cb096498e18275dc
### Plugins
path_provider-1.6.5
path_provider_macos-0.0.4
sqflite-1.3.0
url_launcher-5.4.2
url_launcher_macos-0.0.1+4
url_launcher_web-0.1.1+1

**Comment by TahaTesser** [comment] 2020-10-28 15:31
Hi @amirsaleemahmad 
Closing as duplicate of https://github.com/flutter/flutter/issues/60495
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-28 15:31 UTC
