### ISSUE TITLE
A more convenient IDE solution for apps that do both native android kotlin and flutter

### ISSUE THREAD

**Issue by StokeMasterJack** [flutter/flutter#17692] opened 2018-05-17 12:19 UTC
Android Studio and IntelliJ are normally great with Kotlin and Android. And IntelliJ is great with Dart.

The problem comes when you try to edit Android code in a Dart project. Too many hoops to jump through.  It would be nice if you could could open a single Dart/AndroidKotln  project and every thing just works.

Thanks!

**Comment by zoechi** [comment] 2018-08-03 11:58
cc @devoncarew

**Comment by devoncarew** [comment] 2018-08-03 14:40
Thanks for the feedback! This is being worked on; /cc @stevemessick.

**Comment by stevemessick** [comment] 2018-08-03 16:14
The initial support was added with https://github.com/flutter/flutter-intellij/pull/2474. It will be in the next (M27) plugin release, but won't be enabled. It is actually hard to enable, by design, because it is still not quite stable.

**Comment by stevemessick** [comment] 2018-08-03 16:17
Oops! It is actually easy to enable. I forgot I added a preference for that a few days ago.

**Comment by zoechi** [comment] 2019-01-29 17:09
@stevemessick is this work completed (issue still relevant)?

**Comment by stevemessick** [comment] 2019-01-29 17:57
There is an experimental option to enable code completion etc for Java code in Android modules of Flutter projects. At this point, I think it should be usable, so we could close this issue (if that's what you're asking).

**Comment by zoechi** [comment] 2019-01-29 18:06
Yes, that's what I was asking. 
So if there are issues or missing features there will be more concrete issues.
Thanks for the update!

**Closed by zoechi** 2019-01-29 18:06 UTC
Labels: severe: new feature, tool
