### ISSUE TITLE
"The setter 'readEventsEnabled=' was called on null" Flutter tool error on Ubuntu

### ISSUE THREAD

**Issue by xzyan** [flutter/flutter#12702] opened 2017-10-25 01:49 UTC
```console
ubuntu:~$ flutter doctor
Building flutter tool...
The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false
package:pub/src/source/hosted.dart 338                    BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 140                    BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 165                           BoundSource.getVersions
package:pub/src/solver/version_solver.dart 231            SolverCache.getVersions.<fn>
dart:async                                                runZoned
package:pub/src/http.dart 228                             withDependencyType
package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
===== asynchronous gap ===========================
package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
===== asynchronous gap ===========================
dart:async                                                _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 70          VersionSelection.select.<fn>
dart:async                                                _completeOnAsyncReturn
package:pub/src/solver/unselected_package_queue.dart 54   UnselectedPackageQueue.add
dart:async                                                _completeOnAsyncReturn
package:pub/src/solver/unselected_package_queue.dart 128  UnselectedPackageQueue._getNumVersions
dart:async                                                _Completer.completeError
package:pub/src/solver/version_solver.dart 254            SolverCache.getVersions
dart:async                                                _Completer.completeError
package:pub/src/source/hosted.dart 153                    BoundHostedSource.doGetVersions
dart:async                                                _Completer.completeError
package:http/src/base_client.dart 172                     BaseClient._sendUnstreamed
dart:async                                                _Completer.completeError
package:http_throttle/http_throttle.dart 51               ThrottleClient.send
dart:async                                                _Completer.completeError
package:pub/src/http.dart 127                             _PubHttpClient.send
dart:async                                                _Completer.completeError
package:http/src/io_client.dart 66                        IOClient.send
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error --no-packages-dir

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
```

**Comment by eseidelGoogle** [comment] 2017-10-30 15:05
This looks like a pub failure we may need to file this at https://github.com/dart-lang/pub instead.

**Comment by kendeng9898** [comment] 2018-01-09 07:39
My Ubuntu 16.04 still got this error. Any Idea?

**Comment by Hixie** [comment] 2018-01-09 07:53
These are all probably dupes of each other: https://github.com/flutter/flutter/issues/12301 https://github.com/flutter/flutter/issues/12702 https://github.com/flutter/flutter/issues/13222 https://github.com/flutter/flutter/issues/13349

**Comment by mit-mit** [comment] 2018-01-09 14:31
@yan-xz, @kendeng9898 either of you in China? If so, can you try this and let us know if that works?
https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

**Comment by zoechi** [comment] 2019-01-17 10:38
Duplicate of #12301

**Closed by zoechi** 2019-01-17 10:38 UTC
Labels: a: first hour, t: flutter doctor, tool

**Comment by medz** [comment] 2020-05-19 06:46
Why this bug has not listened to any trends for three years is a strange situation!
