### ISSUE TITLE
[tool_crash] _CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))

### ISSUE THREAD

**Issue by mpastorino1** [flutter/flutter#120522] opened 2023-02-11 12:54 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))
```
#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34)
#1      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:142:21)
#2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:78:21)
#3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#5      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:179:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     Flutte

**Comment by iapicca** [comment] 2023-02-11 13:54
@mpastorino1 looks like 3rd party plugins are involved, could you provide a code sample?

**Comment by danagbemava-nc** [comment] 2023-02-13 06:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/115738

**Closed by danagbemava-nc** 2023-02-13 06:25 UTC
Labels: in triage
