### ISSUE TITLE
video_player plugin: Update exoplayer to 2.14 for RTSP support

### ISSUE THREAD

**Issue by kjeremy** [flutter/flutter#82567] opened 2021-05-14 20:12 UTC
It would be great if the video_player plugin could upgrade exoplayer so that RTSP is supported.

**Comment by kjeremy** [comment] 2021-05-17 13:37
See here for relevant info: https://exoplayer.dev/rtsp.html

**Comment by kjeremy** [comment] 2021-05-19 19:32
flutter/plugins#3933

**Comment by stuartmorgan** [comment] 2023-03-05 21:31
Closing as a duplicate of https://github.com/flutter/flutter/issues/18061

**Closed by stuartmorgan** 2023-03-05 21:31 UTC
Labels: new feature, platform-android, plugin, p: video_player, proposal, passed first triage, P5
