### ISSUE TITLE
Hot restart 'myapp' will be output twice!

### ISSUE THREAD

**Issue by ddxl123** [flutter/flutter#86337] opened 2021-07-13 08:14 UTC
Hot restart 'myapp' will be output twice, why？

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('myapp');
    return Container();
  }
}
```

Hot restart 'myapp' will be output twice, cause the following code to click on the button, and an error will be reported :

`LateInitializationError: Field 'animationController' has not been initialized.`

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('myapp');
    return FlutterTest();
  }
}

class FlutterTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) => A(aController: AController());
}
class A extends StatefulWidget {
  const A({required this.aController});

  final AController aController;

  @override
  _AState createState() => _AState();
}
class _AState extends State<A> with TickerProviderStateMixin {
  @override
  void initState() {
    super.initState();
    widget.aController.animationController = AnimationController(vsync: this);
    print('init');
  }
  @override
  Widget build(BuildContext context) {
    print('build  ' + widget.aController.hashCode.toString());
    return MaterialApp(
      home: FloatingActionButton(
        onPressed: () {
          widget.aController.func();
        },
        child: const Text('button'),
      ),
    );
  }
}
class AController {
  late final AnimationController animationController;
  void func() => print(animationController.value);
}

```

```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 783ms.
I/flutter ( 5732): myapp
I/flutter ( 5732): init
I/flutter ( 5732): build  897585748
I/flutter ( 5732): myapp
I/flutter ( 5732): build  1067757993

======== Exception caught by gesture ===============================================================
The following LateError was thrown while handling a gesture:
LateInitializationError: Field 'animationController' has not been initialized.
```

Doctor :

```
D:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.22000.65], locale zh-CN)
    • Flutter version 2.2.1 at D:\flutter
    • Framework revision 02c026b03c (7 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\10338\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at D:\idea\IntelliJ IDEA 2021.1.2
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7665

[√] VS Code (version 1.58.0)
    • VS Code at C:\Users\10338\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by TahaTesser** [comment] 2021-07-13 08:46
Hi @ddxl123 
This is not an issue, the build function could be called multiple times,
Closing as duplicate of https://github.com/flutter/flutter/issues/33566 https://github.com/flutter/flutter/issues/86315

**Closed by TahaTesser** 2021-07-13 08:46 UTC
Labels: in triage
