### ISSUE TITLE
[tool_crash] _CastError: (#0      LocalizationsGenerator._generateMethod.generateVariables (package:flutter_tools/src/localizations/gen_l10n.dart:1166:54))

### ISSUE THREAD

**Issue by Pratik-canopas** [flutter/flutter#119503] opened 2023-01-30 10:22 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      LocalizationsGenerator._generateMethod.generateVariables (package:flutter_tools/src/localizations/gen_l10n.dart:1166:54))
```
#0      LocalizationsGenerator._generateMethod.generateVariables (package:flutter_tools/src/localizations/gen_l10n.dart:1166:54)
#1      LocalizationsGenerator._generateMethod.generateVariables.<anonymous closure> (package:flutter_tools/src/localizations/gen_l10n.dart:1126:20)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:52:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#8      LocalizationsGenerator._generateMethod.generateVariables (package:flutter_tools/src/localizations/gen_l10n.dart:1127:14)
#9      LocalizationsGenerator._generateMethod (package:flutter_tools/src/localizations/gen_l10n.dart:1212:34)
#10     LocalizationsGenerator._generateBaseClassFile.<anonymous closure> (package:flutter_tools/src/localizations/gen_l10n.dart:918:14)
#11     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#12     ListIterable.join (dart:_internal/iterable.dart:156:22)
#13     LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:931:41)
#14     LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1026:46)
#15     LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1230:47)
#16     generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:73:9)
#17     GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#18     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:27)
<asynchronous suspension>
#19     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#20     generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1402:7)
```
```
[✓] Flutter (Channel stable, 3.7.0, on Ubuntu 22.04.1 LTS 5.15.0-58-generic, locale en_IN)
    • Flutter version 3.7.0 on channel stable at /home/pratik/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (6 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/pratik/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-58-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 135454af32477f815a7525073027a3ff9eff1bfd
### Plugins
cloud_firestore-4.3.1
cloud_firestore_web-3.2.1
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
device_info_plus-6.0.0
device_info_plus_linux-5.0.0
device_info_plus_macos-5.0.0
device_info_plus_web-5.0.0
device_info_plus_windows-6.0.0
firebase_auth-4.2.5
firebase_auth_web-5.2.4
firebase_core-2.4.1
firebase_core_web-2.1.0
flutter_secure_storage-7.0.1
flutter_secure_storage_linux-1.1.2
flutter_secure_storage_macos-2.0.1
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-1.1.3
google_sign_in-5.4.4
google_sign_in_android-6.1.5
google_sign_in_ios-5.5.1
google_sign_in_web-0.10.2+1
package_info_plus-2.0.0
package_info_plus_linux-2.0.0
package_info_plus_macos-2.0.0
package_info_plus_web-2.0.0
package_info_plus_windows-3.0.0
path_provider_linux-2.1.7
path_provider_windows-2.1.3
shared_preferences-2.0.17
shared_preferences_android-2.0.15
shared_preferences_foundation-2.1.2
shared_preferences_linux-2.1.3
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.3
url_launcher-6.1.8
url_launcher_android-6.0.23
url_launcher_ios-6.0.18
url_launcher_linux-3.0.2
url_launcher_macos-3.0.2
url_launcher_web-2.0.14
url_launcher_windows-3.0.3
window_to_front-0.0.3

**Comment by danagbemava-nc** [comment] 2023-01-30 13:03
Closing this as a duplicate of https://github.com/flutter/flutter/issues/116459.

**Closed by danagbemava-nc** 2023-01-30 13:03 UTC
Labels: in triage
