### ISSUE TITLE
Desktop ThemeData is not using given primarySwatch on ThemeMode.dark

### ISSUE THREAD

**Issue by dotupNET** [flutter/flutter#90604] opened 2021-09-23 14:55 UTC
This behavior is on macOS with Flutter v2.5.1.

**Expected results:** 

```
Same Color for AppBar on light and dark thememode
```

**Actual results:**

![image](https://user-images.githubusercontent.com/7642282/134530247-8c01b4b2-ae29-448e-bf07-f9369724b7d4.png)

## Steps to Reproduce

1. Run this on desktop and iOS simulator

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        brightness: Brightness.light,
        primarySwatch: Colors.yellow,
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        primarySwatch: Colors.yellow,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SafeArea(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headline4,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.1 20G80 darwin-arm, locale de-DE)
    • Flutter version 2.5.1 at /Users/peterullrich/data/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (6 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/peterullrich/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/peterullrich/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 59B8895A-9442-48E9-B282-9AEF64FFE08B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-09-23 15:08
Hi @dotupNET 
The reason for this behavior is your system theme, if you set your system to light, you will get a light theme in Flutter and vice versa, you also get a dark theme in the simulator, you go to settings, developer option and enable dark mode 


https://user-images.githubusercontent.com/48603081/134533139-ace6316f-bdbf-4fe5-a4ea-0de56713f7a9.mov

**Comment by TahaTesser** [comment] 2021-09-23 15:22
Hi @dotupNET 
Dark theme is actually overriding primarySwatch, duplicate of https://github.com/flutter/flutter/issues/64426

**Closed by TahaTesser** 2021-09-23 15:22 UTC
Labels: in triage
