### ISSUE TITLE
Allow macOS view to run with a transparent view

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#68739] opened 2020-10-21 21:43 UTC
See https://github.com/flutter/engine/blob/fc72bd2ada5d8d9b4ab2c1255d4f960cc44b5de0/shell/platform/darwin/macos/framework/Source/FlutterView.mm#L39

In the iOS embedding, we have https://github.com/flutter/engine/blob/fc72bd2ada5d8d9b4ab2c1255d4f960cc44b5de0/shell/platform/darwin/ios/framework/Source/FlutterView.mm#L53 which allows for initializing a transparent FlutterView so that it can be placed over native UI.

@stuartmorgan @iskakaushik 

/cc @dannyvalentesonos

**Comment by stuartmorgan** [comment] 2020-10-21 23:06
Duplicate of https://github.com/flutter/flutter/issues/59969. It's just never been added.

**Closed by stuartmorgan** 2020-10-21 23:06 UTC
Labels: P5, a: existing-apps, engine, platform-mac, severe: new feature
