### ISSUE TITLE
Run Issue

### ISSUE THREAD

**Issue by umar195** [flutter/flutter#71996] opened 2020-12-09 13:16 UTC
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by YazeedAlKhalaf** [comment] 2020-12-09 13:48
This issue seems to be more of a JAVA problem and that it is not in your path.
You have to add it to your path or set `JAVA_HOME` variable to the right path.

Please provide us with `flutter doctor -v`.
And a quick google search about adding java to path or setting `JAVA_HOME` will probably solve your issue.

**Comment by TahaTesser** [comment] 2020-12-09 14:00
Hi @umar195 
This is not an issue with Flutter itself, you're misisng JAVA_HOME environment varaiable
Please point JAVA_HOME to your Android Studio JAVA or java 1.8, point to the same `JAVA_HOME`
`export JAVA_HOME=/home/your_user/Code/android-studio/jre`  

If the problem persists after this change, Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by umar195** [comment] 2020-12-09 14:03
Thank You so much for this helping.

**Comment by TahaTesser** [comment] 2020-12-09 14:13
Hi @umar195 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-12-09 14:13 UTC
Labels: in triage
