### ISSUE TITLE
Support android gradle build tool 4.0

### ISSUE THREAD

**Issue by hamberluo** [flutter/flutter#61693] opened 2020-07-17 04:08 UTC

**Comment by TahaTesser** [comment] 2020-07-17 09:49
hI @hamberluo 
This is being worked on
Closing as duplicate of https://github.com/flutter/flutter/issues/58247   https://github.com/flutter/flutter/issues/58479
if you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-17 09:49 UTC
