### ISSUE TITLE
[iOS] Improve the experience when running on a locked device

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#95924] opened 2021-12-29 05:57 UTC
Currently, this is what's happening when users are trying to run a Flutter app on a locked iOS device.

```
Launching lib/main.dart on Alex’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXXXX
Running Xcode build...
Xcode build done.                                           76.9s
Installing and launching...
═══════════════════════════════════════════════════════════════════════════════════
Your device is locked. Unlock your device first before running.
═══════════════════════════════════════════════════════════════════════════════════
Could not run build/ios/iphoneos/Runner.app on XXXXXXXX-XXXXXXXXXXXXXXXXX.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Alex’s iPhone.
```

This is correct behavior since we cannot run on a locked device, but it's especially hurt when the build processes take minutes.

## Proposal

Maybe we can make a blocking action to wait for further steps from users, similar to Xcode:
![image](https://user-images.githubusercontent.com/15884415/147631752-e3af6112-53bb-4eb3-bcc4-4d1111b6497d.png)

**Comment by danagbemava-nc** [comment] 2021-12-29 07:22
Duplicate of #34817

**Closed by danagbemava-nc** 2021-12-29 07:22 UTC
Labels: in triage

**Comment by AlexV525** [comment] 2021-12-29 07:47
> Duplicate of #34817

@danagbemava-nc Thanks for the reference!
