### ISSUE TITLE
PathFillType.evenOdd is not working in Web with HTML renderer

### ISSUE THREAD

**Issue by AriasBros** [flutter/flutter#109924] opened 2022-08-20 14:55 UTC
It seems like `PathFillType.evenOdd` doesn't have any effect when we run the app with the HTML renderer.
Running the same app with the CanvasKit renderer, the clipping is working as expected. See below.

This issue #81637 is very similar, but it is focused on images behind the clip area, when actually that doesn't matter, in the code sample of this issue I use a Text component, for example.

## Steps to Reproduce

1. Just execute `flutter run -d chrome --web-renderer html` on the code sample

**Expected results:** 
<img width="796" alt="expected" src="https://user-images.githubusercontent.com/331765/185751936-2ec56c54-c1ec-40db-bf28-81eac5f898f9.png">

**Actual results:** 
<img width="796" alt="actual" src="https://user-images.githubusercontent.com/331765/185751940-bcfda7e1-e39e-40f1-b850-a9091b38e23e.png">

<details>
<summary>Code sample</summary>

[code_sample.zip](https://github.com/flutter/flutter/files/9387357/code_sample.zip)

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomeView(),
    );
  }
}

class HomeView extends StatelessWidget {
  const HomeView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: const [
        Center(child: Text("Hello!!")),
        Positioned.fill(
          child: ClipPath(
            clipper: InvertedClipper(),
            child: ColoredBox(color: Colors.blue),
          ),
        ),
      ],
    );
  }
}

class InvertedClipper extends CustomClipper<Path> {
  const InvertedClipper({Listenable? reclip}) : super(reclip: reclip);

  @override
  Path getClip(Size size) {
    Path path = Path();

    // This code is not working in HTML renderer.
    path.addRect(Rect.fromLTWH((size.width - 200) / 2, (size.height - 100) / 2, 200, 100));
    path.addRect(Rect.fromLTWH(0, 0, size.width, size.height));
    path.fillType = PathFillType.evenOdd;

    return path;
  }

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) => true;
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale es-ES)
    • Flutter version 3.0.5 at /Users/david/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/david/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2022-08-22 10:03
Hi @AriasBros, thanks for filing the issue. 
When I tried removing `fillType = PathFillType.evenOdd`, the result is still the same. So I think the issue is caused by `ClipPath` whether it's an Image or a Text widget in there. It looks like two issues are similar and we should only keep one. 

Closing as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. If you disagree, please write in the comment and I will reopen this. Thank you!

**Comment by AriasBros** [comment] 2022-08-22 11:10
Sorry @huycozy, but I don't understand the reason to remove `fillType = PathFillType.evenOdd` from the code. If you do that the issue is not fired. Of course, the bug itself can be in `ClipPath`, or wherever, I don't know. But if you don't use `PathFillType.evenOdd` you will not be able to see the issue happening.

Below you can see a better images with the actual issue. They are done with this code:

```dart
path.addRect(Rect.fromLTWH((size.width - 200) / 2, (size.height - 100) / 2, 200, 100));
path.addRect(Rect.fromLTWH((size.width - 400) / 2, (size.height - 300) / 2, 400, 300));
path.fillType = PathFillType.evenOdd;
```

As you can see, the ClipPath is doing the clip, but only it is clipping the outer part of the Path, the inner clipping is not being done. And who tells that the inner clipping must be done is `fillType = PathFillType.evenOdd`. If you don't use `fillType` with `PathFillType.evenOdd` you never will see the inner clip (what that is the right thing). I don't know if I am explaining me... 

Said this, thanks for your reply @huycozy, I don't mind the issue is closed, that is one of the reasons I linked my original message with that issue. But also I think the title of the original issue is wrong because is giving the understanding that the origin of the issue is to have images in the stack, when that is not the case. The problem seems to be that `ClipPath` is ignoring the `fillType` of the `Path`.

**Expected results:**
<img width="796" alt="expected" src="https://user-images.githubusercontent.com/331765/185904365-c95381bc-5757-458b-bf79-7d9f60faacb4.png">

**Actual results:**
<img width="796" alt="actual" src="https://user-images.githubusercontent.com/331765/185904371-aa1b1807-f699-429e-b3b8-dff2bb0fbafe.png">

**Comment by huycozy** [comment] 2022-08-23 06:16
Hi @AriasBros 
I reopen the issue for further discussion.

>I don't understand the reason to remove fillType = PathFillType.evenOdd from the code.

Because I see that issue #81637 is about `ClipPath`, I tried removing `fillType = PathFillType.evenOdd` to see if this issue is still reproducible. And the issue is still reproducible after removing that property, but it seems not like that from your side, right? If so, I'm sorry for the subjective judgment. 

>But also I think the title of the original issue is wrong because is giving the understanding that the origin of the issue is to have images in the stack, when that is not the case.

Don't worry about this. Once this issue is closed as a duplicate, please write a comment on the issue #81637 about your case. I will also update its title as well to be appropriate with cases. What do you think?

**Comment by AriasBros** [comment] 2022-08-26 07:28
Thanks for your help @huycozy

> Because I see that issue #81637 is about `ClipPath`, I tried removing `fillType = PathFillType.evenOdd` to see if this issue is still reproducible.

Yes, the issue is about `ClipPath`... but it seems that it is ignoring the property `fillType`, so if you remove  that line you are removing the source of the issue and you will not able to replicate it. 

> And the issue is still reproducible after removing that property, but it seems not like that from your side, right? If so, I'm sorry for the subjective judgment.

This issue that I open and the issue https://github.com/flutter/flutter/issues/81637 are the same in my opinion. But because I am not sure and I am not an expert, I decided to open a new issue to not disturb in the other issue.

> Don't worry about this. Once this issue is closed as a duplicate, please write a comment on the issue https://github.com/flutter/flutter/issues/81637 about your case. I will also update its title as well to be appropriate with cases. What do you think?

Ok, I will comment there with a link to this issue.

Again, thanks a lot @huycozy

**Comment by huycozy** [comment] 2022-08-26 11:46
Hi @AriasBros, I will close this issue as a duplicate, so please follow up on issue #81637 for further updates. Thank you!

**Closed by huycozy** 2022-08-26 11:46 UTC
Labels: in triage
