### ISSUE TITLE
flutter build apk  Too many positional arguments  XML.XmlElement

### ISSUE THREAD

**Issue by marcmorente** [flutter/flutter#26234] opened 2019-01-08 16:03 UTC
When I try to generate the apk release with the command "flutter build apk", the console generates the following error:
```
Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:303:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var info = new XML.XmlElement(new XML.XmlName('info'), attrs, []);
                                       ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:308:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var node = new XML.XmlElement(new XML.XmlName('common'), attrs, []);
                                       ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:313:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var page = new XML.XmlElement(new XML.XmlName('page'), attrs, []);
                                       ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:321:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var node = new XML.XmlElement(new XML.XmlName('char'), attrs, []);
                                       ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:329:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var node = new XML.XmlElement(new XML.XmlName('kerning'), attrs, []);
                                       ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:336:36: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
      var node = new XML.XmlElement(new XML.XmlName('chars'), charsAttrs,
                                   ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:342:36: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
      var node = new XML.XmlElement(new XML.XmlName('kernings'), kerningsAttrs,
                                   ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:348:37: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
      var pages = new XML.XmlElement(new XML.XmlName('pages'), [], pageList);
                                    ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:352:33: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
    var xml = new XML.XmlElement(new XML.XmlName('font'), [], children);
                                ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
Compiler terminated unexpectedly.
Gradle task 'assembleRelease'... Done                       39,4s
Gradle task assembleRelease failed with exit code 1
```
I tried to generate the apk with the flutter channels stable, master and beta, and I still have the same error. 

This is my flutter doctor:
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [VersiÃ³n 10.0.17134.472], locale es-ES)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\MMorente\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\MMorente\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.0)
    • VS Code at C:\Users\MMorente\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 64-bit edition (version 1.28.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2019-01-08 16:14
Caused by https://github.com/renggli/dart-xml/issues/53

Until this is solved, you should be able to work around by adding

```yml
dependencies:
  xml: '>=2.0.0 <=3.2.0'
```

**Comment by zoechi** [comment] 2019-01-08 16:16
I'm closing because this is not related to Flutter.

**Closed by zoechi** 2019-01-08 16:16 UTC
