### ISSUE TITLE
google maps animateCamera doesn't work correctly on iOS simulator

### ISSUE THREAD

**Issue by BabarJan90** [flutter/flutter#70600] opened 2020-11-16 09:55 UTC
CameraPosition _kCurrentLocation1;

      mapController = await _controller.future;
      _kCurrentLocation1 = CameraPosition(
          target: LatLng(
            mapAssetModel.mapAssetInfo.lat,
            mapAssetModel.mapAssetInfo.lng,
          ),
          zoom: 17.0);
      await mapController
          .animateCamera(CameraUpdate.newCameraPosition(_kCurrentLocation1));

Using this setup, the app works fine on android. However on iOS, this initial camera animation is not working INITIALLY. However after this initial phase like the above person reports, if user triggers some other actions like going to a different location, then this functions seems to work fine.

**Comment by TahaTesser** [comment] 2020-11-16 14:54
Hi @BabarJan90 
Can you please provide your `flutter doctor -v`,  your `pubspec.yaml` , and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by TahaTesser** [comment] 2020-11-18 08:40
duplicate of https://github.com/flutter/flutter/issues/70033

**Closed by TahaTesser** 2020-11-18 08:40 UTC
Labels: in triage, waiting for customer response
