### ISSUE TITLE
iOS compilation error: Assets.xcassets distill failed for unknown reasons

### ISSUE THREAD

**Issue by mtellect** [flutter/flutter#42502] opened 2019-10-11 06:15 UTC
Hi guys i don't know if this issue as a result of Xcode 11? i am currently facing this same issue on 
https://github.com/flutter/flutter/issues/40031
And also i have updated my Xcode several times from app store

and i also have a blank screen on my ios simulator
Mac OS Catalina

![image](https://user-images.githubusercontent.com/29234654/66628131-ca983b80-ebf5-11e9-8fdd-6bbebee84729.png)

FLUTTER DOCTOR
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.15 19A487m, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
```

FLUTTER DOCTOR --VERBOSE
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.15 19A487m, locale en-GB)
    • Flutter version 1.9.1+hotfix.2 at /Users/bappstack/flutter
    • Framework revision 2d2a1ffec9 (5 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bappstack/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • E0287B30-CC7A-45A2-9CB6-F902E34DF5D5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

ERROR
```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           23.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-10-11 07:02 xcodebuild[1328] (FSEvents.framework) fsevent_realpath: err(2): [No such file or directory]

    ** BUILD FAILED **


Xcode's output:
↳
    2019-10-11 07:02:35.324 ibtoold[1444:147805] DEBUG: Added to environment: {
        TMPDIR = "/var/folders/4d/526ywq0j4zs8bqrvvb46p03r0000gn/T/CA9BF82B-7CDC-4777-BCF6-68698AD0F237";
    }
    2019-10-11 07:02:36.859 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
    2019-10-11 07:02:36.867 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
    2019-10-11 07:02:36.868 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
    2019-10-11 07:02:36.869 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
    2019-10-11 07:02:36.869 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
    2019-10-11 07:02:36.869 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
    2019-10-11 07:02:36.870 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
    2019-10-11 07:02:36.871 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
    2019-10-11 07:02:36.871 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
    2019-10-11 07:02:36.872 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
    2019-10-11 07:02:36.873 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
    2019-10-11 07:02:36.873 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
    2019-10-11 07:02:36.874 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
    2019-10-11 07:02:36.875 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
    2019-10-11 07:02:36.875 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
    2019-10-11 07:02:36.876 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
    2019-10-11 07:02:36.877 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
    2019-10-11 07:02:36.877 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
    2019-10-11 07:02:36.878 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
    2019-10-11 07:02:36.878 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
    2019-10-11 07:02:36.879 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
    2019-10-11 07:02:36.884 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
    2019-10-11 07:02:36.885 IBCocoaTouchImageCatalogTool[1447:147962] Unable to get image dimensions for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
    2019-10-11 07:02:36.897 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
    2019-10-11 07:02:36.897 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
    2019-10-11 07:02:36.898 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
    2019-10-11 07:02:36.898 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
    2019-10-11 07:02:36.898 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
    2019-10-11 07:02:36.898 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
    2019-10-11 07:02:36.898 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
    2019-10-11 07:02:36.899 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
    2019-10-11 07:02:36.899 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
    2019-10-11 07:02:36.899 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
    2019-10-11 07:02:36.899 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
    2019-10-11 07:02:36.900 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
    2019-10-11 07:02:36.900 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
    2019-10-11 07:02:36.900 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
    2019-10-11 07:02:36.900 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
    2019-10-11 07:02:36.901 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
    2019-10-11 07:02:36.901 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
    2019-10-11 07:02:36.901 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
    2019-10-11 07:02:36.901 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
    2019-10-11 07:02:36.902 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
    2019-10-11 07:02:36.902 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
    2019-10-11 07:02:36.902 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
    2019-10-11 07:02:36.902 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
    2019-10-11 07:02:36.902 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
    2019-10-11 07:02:36.903 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
    2019-10-11 07:02:36.903 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
    2019-10-11 07:02:36.903 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
    2019-10-11 07:02:36.903 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
    2019-10-11 07:02:36.904 IBCocoaTouchImageCatalogTool[1447:147962] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
    2019-10-11 07:02:36.961 IBCocoaTouchImageCatalogTool[1447:148151] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
    2019-10-11 07:02:36.961 IBCocoaTouchImageCatalogTool[1447:148189] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
    2019-10-11 07:02:36.961 IBCocoaTouchImageCatalogTool[1447:148200] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
    2019-10-11 07:02:36.961 IBCocoaTouchImageCatalogTool[1447:148199] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
    2019-10-11 07:02:36.962 IBCocoaTouchImageCatalogTool[1447:148201] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
    2019-10-11 07:02:36.962 IBCocoaTouchImageCatalogTool[1447:148151] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
    2019-10-11 07:02:36.962 IBCocoaTouchImageCatalogTool[1447:148189] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
    2019-10-11 07:02:36.962 IBCocoaTouchImageCatalogTool[1447:148199] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
    2019-10-11 07:02:36.963 IBCocoaTouchImageCatalogTool[1447:148201] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
    2019-10-11 07:02:36.963 IBCocoaTouchImageCatalogTool[1447:148200] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
    2019-10-11 07:02:36.963 IBCocoaTouchImageCatalogTool[1447:148151] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
    2019-10-11 07:02:36.963 IBCocoaTouchImageCatalogTool[1447:148189] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
    2019-10-11 07:02:36.964 IBCocoaTouchImageCatalogTool[1447:148199] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
    2019-10-11 07:02:36.964 IBCocoaTouchImageCatalogTool[1447:148200] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
    2019-10-11 07:02:36.965 IBCocoaTouchImageCatalogTool[1447:148200] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
    2019-10-11 07:02:36.965 IBCocoaTouchImageCatalogTool[1447:148199] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
    2019-10-11 07:02:36.965 IBCocoaTouchImageCatalogTool[1447Could not build the application for the simulator.:148200] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
    2019-10-11 07:02:36.965 IBCocoaTouchImageCatalogTool[1447:148199] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png

    2019-10-11 07:02:36.966 IBCocoaTouchImageCatalogTool[1447:148200] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
    2019-10-11 07:02:36.966 IBCocoaTouchImageCatalogTool[1447:148201] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
    2019-10-11 07:02:36.967 IBCocoaTouchImageCatalogTool[1447:148189] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
    2019-10-11 07:02:36.967 IBCocoaTouchImageCatalogTool[1447:148201] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
    2019-10-11 07:02:36.967 IBCocoaTouchImageCatalogTool[1447:148189] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
Error launching application on iPhone 11 Pro Max.
    2019-10-11 07:02:36.968 IBCocoaTouchImageCatalogTool[1447:148201] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
    2019-10-11 07:02:36.968 IBCocoaTouchImageCatalogTool[1447:148189] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
    2019-10-11 07:02:36.968 IBCocoaTouchImageCatalogTool[1447:148151] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
    2019-10-11 07:02:36.969 IBCocoaTouchImageCatalogTool[1447:148151] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
    2019-10-11 07:02:36.969 IBCocoaTouchImageCatalogTool[1447:148199] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
    2019-10-11 07:02:36.969 IBCocoaTouchImageCatalogTool[1447:148151] CoreThemeDefinition: Unable to create image for file:///Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
    /* com.apple.actool.errors */
    /Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets: error: Distill failed for unknown reasons.
    /* com.apple.actool.compilation-results */
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon20x20@2x.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon20x20@3x.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon29x29.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon29x29@2x.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon29x29@3x.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon40x40@2x.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon40x40@3x.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon60x60@2x.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon60x60@3x.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon20x20~ipad.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon20x20@2x~ipad.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon29x29~ipad.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon29x29@2x~ipad.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon40x40~ipad.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon40x40@2x~ipad.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon76x76~ipad.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon76x76@2x~ipad.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/AppIcon83.5x83.5@2x~ipad.png
    /Users/bappstack/AndroidStudioProjects/payzeeros/build/ios/Debug-iphonesimulator/Runner.app/Assets.car
    /Users/bappstack/Library/Developer/Xcode/DerivedData/Runner-gznzxlqdjfkayldskzkgguyizpwb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/assetcatalog_generated_info.plist

    note: Using new build systemnote: Planning buildnote: Constructing build description


```

**Comment by jmagman** [comment] 2019-10-11 18:42
```
/Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets: error: Distill failed for unknown reasons.
```
Did you alter your Assets.xcassets in the Xcode project (images, etc)?
https://stackoverflow.com/questions/20580968/xcode-error-distill-failed-for-unknown-reasons

**Comment by tbrabec** [comment] 2019-10-14 09:22
I've got the same issue with macOS Catalina. I was able to work around the issue by using macOS 10.14.6, still with Xcode 11. Took me a lot of time to find out though.

**Comment by lwerner-lshigh** [comment] 2019-11-06 18:45
I also have this issue, Xcode 11.

**Comment by jmagman** [comment] 2019-11-07 18:21
> ```
> /Users/bappstack/AndroidStudioProjects/payzeeros/ios/Runner/Assets.xcassets: error: Distill failed for unknown reasons.
> ```
> 
> Did you alter your Assets.xcassets in the Xcode project (images, etc)?
> https://stackoverflow.com/questions/20580968/xcode-error-distill-failed-for-unknown-reasons

@tbrabec @lwerner-lshigh I'll reopen if I can get an answer to this question from anyone reproducing this, or an example project demonstrating the issue.

**Comment by nfodor** [comment] 2019-12-06 03:49
Got the same problem here but even with an ios only xcode project, same issue. Appeared the first time when using Flutter with xcode.

**Comment by AtomicNicos** [comment] 2020-02-16 00:17
XCode and Console build still fail on ios. Wanted to test out the application in ios setting and this breaks the build (only 2 assets: AppIcon and LaunchImage, there since the start).

**Comment by AtomicNicos** [comment] 2020-02-20 11:48
Solution use XCode 10.3 and related build tools / simulators, XCode 11.3 is not yet supported by Flutter.

**Comment by jmagman** [comment] 2020-02-20 18:54
> Temporary Solution: use XCode 10.3 and related build tools / simulators, XCode 11.3 is not yet supported by Flutter apparently.

@AtomicNicos Xcode 11.0 is the minimum version supported by Flutter.  Are you seeing an issue with Xcode 11.3?

**Comment by AtomicNicos** [comment] 2020-02-20 19:21
Yes, which is why I downgraded to 10.3, as that seemed to work. I wasn't doing `flutter run` from a terminal, just a standard build and launch in simulator straight from XCode. Tried cleaning project etc. to no avail.

**Comment by AtomicNicos** [comment] 2020-02-25 07:32
Running on branch `master` if that's of any help.

**Comment by jmagman** [comment] 2020-02-25 18:45
We need a reproduction case to investigate.

**Comment by jmagman** [comment] 2020-03-18 01:00
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-03-18 01:00 UTC
Labels: t: xcode, tool, waiting for customer response, ⌺‬ platform-ios
