### ISSUE TITLE
[Web] Add scope to ServiceWorker

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#51706] opened 2020-02-29 19:13 UTC
The current registration of the service worker in the index.html template is
```js
navigator.serviceWorker.register('/flutter_service_worker.js');
```

I would like to modify it, to use scope:
 ```js
navigator.serviceWorker.register('flutter_service_worker.js', {scope: './'});
```

From [Google Web: introduction-to-service-worker](https://developers.google.com/web/ilt/pwa/introduction-to-service-worker)
> The scope of the service worker determines which files the service worker controls, in other words, from which path the service worker will intercept requests. The default scope is the location of the service worker file, and extends to all directories below. So if service-worker.js is located in the root directory, the service worker will control requests from all files at this domain.

## Why?
Currently i am working on a flutter website deployed in https://jamesblasco.github.io/arb_editor/master/.
Because it is not the root directory https://jamesblasco.github.io/, the service worker won't register correctly.

But if I use the scope param `'./'` to register the serviceWorker for the directory of the index.html/flutter project it works as expected.

**Comment by chunhtai** [comment] 2020-03-03 22:46
cc @mdebbar this seems to be on engine side

**Comment by mdebbar** [comment] 2020-03-05 20:24
We need a way to allow developers to configure the base path of their application. There's already an issue for this: https://github.com/flutter/flutter/issues/50580.

Duplicate of https://github.com/flutter/flutter/issues/50580

**Closed by mdebbar** 2020-03-05 20:24 UTC
Labels: engine, proposal, ☸ platform-web
