### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2

### ISSUE THREAD

**Issue by khangpham202** [flutter/flutter#136063] opened 2023-10-06 09:16 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:169:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:157:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1813:56)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1831:13)
#8      _rootRunUnary (dart:async/zone.dart:1407:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _rootRunUnary (dart:async/zone.dart:1407:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    [32m•[39m Flutter version 3.13.5 on channel stable at D:\programer\Mobile App\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 12fccda598 (2 weeks ago), 2023-09-19 13:56:11 -0700
    [32m•[39m Engine revision bd986c5ed2
    [32m•[39m Dart version 3.1.2
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\doang\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: D:\programer\Mobile App\android studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at D:\programer\Mobile App\android studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[32m[✓][39m VS Code (version unknown)
    [32m•[39m VS Code at C:\Users\doang\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.74.0
    [31m✗[39m Unable to determine VS Code version.

[32m[✓][39m Connected device (2 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.47

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 12fccda598477eddd19f93040a1dba24f915b9be

**Comment by danagbemava-nc** [comment] 2023-10-06 09:29
Closing this as a duplicate of https://github.com/flutter/flutter/issues/95142. 

You can fix this by installing Google Chrome on your system or doing what is recommended by flutter doctor in 

```
�[31m[✗]�[39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    �[33m!�[39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
```

**Closed by danagbemava-nc** 2023-10-06 09:29 UTC
Labels: in triage
