### ISSUE TITLE
Changes that break test_runner aren't caught in presubmit checks

### ISSUE THREAD

**Issue by ianloic** [flutter/flutter#11176] opened 2017-07-12 18:16 UTC
https://github.com/flutter/engine/pull/3833 breaks the fuchsia build because of this error in the host (Linux) test_runner build:
```
../../flutter/shell/testing/test_runner.cc:17:19: error: no member named 'Attach' in 'shell::PlatformView'
 platform_view_->Attach();
 ~~~~~~~~~~~~~~  ^
```
This should be caught by travis builds and reflected in the dashboards.

**Comment by jason-simmons** [comment] 2017-07-12 18:23
The engine Travis script doesn't build the engine binaries for any platform - it runs dartanalyzer on the engine's Dart code and runs the license checker script.  The Chromium buildbot scripts build the engine, but that doesn't run until a change is submitted.

@yjbanov

**Comment by zoechi** [comment] 2018-12-04 12:14
Is this issue still relevant?

**Comment by kf6gpe** [comment] 2019-06-06 17:37
This will be fixed when we extract the Flutter runner into the engine; work being done as part of FL-250.

**Comment by kf6gpe** [comment] 2019-06-06 18:00
FL-250 is tracked in github as https://github.com/flutter/flutter/issues/33991

**Comment by iapicca** [comment] 2019-11-01 13:11
Hi @ianloic 
given the merged  PR 
is this issue still meant to be open?

**Comment by iskakaushik** [comment] 2020-02-14 21:28
duplicate of: https://github.com/flutter/flutter/issues/44826

**Closed by iskakaushik** 2020-02-14 21:28 UTC
Labels: a: tests, customer: fuchsia, dependency: fuchsia, engine, team, ○ platform-fuchsia
