### ISSUE TITLE
Scrollbar thumb behaviour is erratic when scrolling through items of uneven heights

### ISSUE THREAD

**Issue by mattrussell-sonocent** [flutter/flutter#51470] opened 2020-02-26 12:26 UTC
## Steps to Reproduce
1. Run `flutter create bug`.
2. Update the files as follows:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Scrollbar(
          child: ListView(
            physics: AlwaysScrollableScrollPhysics(),
            children: ListTile.divideTiles(
              context: context,
              tiles: [
                for (var i = 0; i < 51; i += 1)
                  ListTile(
                    title: Text("foobar\n" * ((i * 11) % 51)),
                  ),
              ],
            ).toList(),
          ),
        ),
      ),
    );
  }
}
```

3. Swipe to scroll through the list

**Expected results:** Smooth movement of the scrollbar thumb

**Actual results:** Scrollbar thumb jumps forwards and backwards erratically

![scrollbar-jump](https://user-images.githubusercontent.com/45822724/75344729-21479e80-5893-11ea-9101-ee263fe71373.gif)

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/matt/lib/flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/matt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

</details>

**Comment by sdlcdhc** [comment] 2020-04-22 03:01
I’m suffering the same issue, anybody give a suggestion?

**Comment by TahaTesser** [comment] 2020-07-08 15:12
duplicate of https://github.com/flutter/flutter/issues/59404

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (4 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (5 available)
    • SM M305F (mobile)                  • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 6.0 (API 23)
      (emulator)
    • Taha’s iPhone (mobile)             • 00008020-001059882212002E • ios            • iOS 13.5.1
    • Web Server (web)                   • web-server                • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 83.0.4103.116

• No issues found!


``` 

</details>

**Comment by mattrussell-sonocent** [comment] 2020-07-08 15:18
@TahaTesser Can I request we reopen this, as I think it's a different issue: this is about the scroll thumb jumping backwards and forwards erratically. #59404 is about animation not being fluid, which I think is a slightly different issue (i.e. that issue is more about performance than correctness).

**Comment by TahaTesser** [comment] 2020-07-08 15:27
Hi @mattrussell-sonocent 
It's the same behaviour, the mentioned issue has same scrollbar issue jumping backwards and forward  and cause  of the issue is same 


### This issues code sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Scrollbar(
          child: ListView(
            physics: AlwaysScrollableScrollPhysics(),
            children: ListTile.divideTiles(
              context: context,
              tiles: [
                for (var i = 0; i < 51; i += 1)
                  ListTile(
                    title: Text("foobar\n" * ((i * 11) % 51)),
                  ),
              ],
            ).toList(),
          ),
        ),
      ),
    );
  }
}
```
### Mentioned issue's code sample

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(100, (i) => "Item $i"),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;

  MyApp({Key key, @required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Scrollbar(
          child: ListView.builder(
            itemCount: items.length,
            itemBuilder: (context, index) {
              return ListTile(
                title: Text('${items[index]}'),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

leaving this open for additional triage

**Comment by Hixie** [comment] 2020-07-30 20:35
This is by design. The scrollbar logic guesses at the position based on what it knows currently.

You can improve the UI if you can provide a better implementation of estimateMaxScrollOffset.

**Comment by Piinks** [comment] 2020-10-22 16:30
This appears to be a duplicate of https://github.com/flutter/flutter/issues/25652. Please track that issue for updates. If you believe I've made an error, please reply here with more details that explain the difference and we'll re-open this issue. :) Thanks!

**Closed by Piinks** 2020-10-22 16:30 UTC
Labels: P4, f: material design, f: scrolling, found in release: 1.20, framework, has reproducible steps
