### ISSUE TITLE
Flutter build apk crash Ubuntu

### ISSUE THREAD

**Issue by bingzhang** [flutter/flutter#31276] opened 2019-04-18 19:47 UTC
Hello:

I installed flutter stable on ubuntu 16.04. flutter build apk crashed. I can provide gradle and android sdk versions. 

## Steps to Reproduce

1. wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.2.1-stable.tar.xz
2. tar xf flutter_linux_v1.2.1-stable.tar.xz
3. Flutter channels:
  beta
  dev
  master
* stable

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build aot --suppress-analytics --quiet --target lib/main.dart --target-platform android-arm --output-dir /home/ubuntu/savvi-client/build/app/intermediates/flutter/release --target-platform android-arm --release

## exception

ProcessException: ProcessException: No such file or directory
  Command: /home/ubuntu/android/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot --causal_async_stacks --packages=.packages --deterministic --snapshot_kind=app-aot-blobs --vm_snapshot_data=/home/ubuntu/savvi-client/build/app/intermediates/flutter/release/vm_snapshot_data --isolate_snapshot_data=/home/ubuntu/savvi-client/build/app/intermediates/flutter/release/isolate_snapshot_data --vm_snapshot_instructions=/home/ubuntu/savvi-client/build/app/intermediates/flutter/release/vm_snapshot_instr --isolate_snapshot_instructions=/home/ubuntu/savvi-client/build/app/intermediates/flutter/release/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /home/ubuntu/savvi-client/build/app/intermediates/flutter/release/app.dill

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:140:27)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:68:12)
#2      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:55)
<asynchronous suspension>
#3      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:137:56)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:111:11)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:51:10)
#35     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#36     main (file:///b/rr/tmpx8KOIL/w/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
```

## flutter doctor

```
[!] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/ubuntu/android/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5 (you need to enable multilib: https://wiki.archlinux.org/index.php/Official_repositories#multilib)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/ubuntu/android/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/ubuntu/android/android-sdk
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```
```

**Comment by jonahwilliams** [comment] 2019-04-18 19:57
@bingzhang if you run  `rm -rf flutter/bin/cache` and then run `flutter precache` does that download additional artifacts? It looks like the artifact `android-arm-release/linux-x64/gen_snapshot` is missing

**Comment by bingzhang** [comment] 2019-04-18 19:59
@jonahwilliams, I run the above commands you pointed out. 

```
ubuntu@polyglot-2:~/savvi-client$ rm -rf flutter/bin/cache
ubuntu@polyglot-2:~/savvi-client$ flutter precache
Already up-to-date
```

**Comment by jonahwilliams** [comment] 2019-04-18 20:03
`/bin/cache` should be relative to the flutter root, wherever you've downloaded it to

**Comment by bingzhang** [comment] 2019-04-18 20:14
Thanks, after remove bin/cache folder under flutter root folder, It can download, however the flutter build apk still falied.

```
ubuntu@polyglot-2:~/savvi-client$ flutter build apk
Running "flutter packages get" in savvi-client...                   0.5s
Initializing gradle...                                              0.6s
Resolving dependencies...                                           1.6s
                                                                        
Oops; flutter has exited unexpectedly.                                  
Crash report written to /home/ubuntu/savvi-client/flutter_04.log;       
please let us know at https://github.com/flutter/flutter/issues.        
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       4.6s
Gradle task assembleRelease failed with exit code 1
```

```
ubuntu@polyglot-2:~/android/flutter$ flutter precache
Downloading Dart SDK from Flutter engine 3757390fa4b00d2d261bfdf5182d2e87c9113ff9...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 70.6M  100 70.6M    0     0  22.2M      0  0:00:03  0:00:03 --:--:-- 22.2M
Building flutter tool...
Downloading Material fonts...                                       0.6s
Downloading package sky_engine...                                   0.4s
Downloading common tools...                                         1.5s
Downloading linux-x64 tools...                                      3.2s
Downloading android-arm-profile/linux-x64 tools...                  0.7s
Downloading android-arm-release/linux-x64 tools...                  0.5s
Downloading android-arm64-profile/linux-x64 tools...                0.7s
Downloading android-arm64-release/linux-x64 tools...                0.6s
Downloading android-arm-dynamic-profile/linux-x64 tools...          0.8s
Downloading android-arm-dynamic-release/linux-x64 tools...          1.1s
Downloading android-arm64-dynamic-profile/linux-x64 tools...         0.6s
Downloading android-arm64-dynamic-release/linux-x64 tools...         0.5s
Downloading android-x86 tools...                                    1.9s
Downloading android-x64 tools...                                    2.3s
Downloading android-arm tools...                                    1.0s
Downloading android-arm-profile tools...                            1.0s
Downloading android-arm-release tools...                            0.8s
Downloading android-arm64 tools...                                  1.2s
Downloading android-arm64-profile tools...                          1.0s
Downloading android-arm64-release tools...                          0.9s
Downloading android-arm-dynamic-profile tools...                    1.0s
Downloading android-arm-dynamic-release tools...                    1.0s
Downloading android-arm64-dynamic-profile tools...                  1.3s
Downloading android-arm64-dynamic-release tools...                  1.0s
Downloading Gradle Wrapper...                                       0.4s
```

**Comment by jonahwilliams** [comment] 2019-04-18 20:31
Is it still crashing with the same no such file error? Does /home/ubuntu/android/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot exist?

**Comment by bingzhang** [comment] 2019-04-18 20:36
The file exists.

The error is still no such file.

## command

flutter build aot --suppress-analytics --quiet --target lib/main.dart --target-platform android-arm --output-dir /home/ubuntu/savvi-client/build/app/intermediates/flutter/release --target-platform android-arm --release

## exception

```
ProcessException: ProcessException: No such file or directory
  Command: /home/ubuntu/android/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot --causal_async_stacks --packages=.packages --deterministic --snapshot_kind=app-aot-blobs --vm_snapshot_data=/home/ubuntu/savvi-client/build/app/intermediates/flutter/release/vm_snapshot_data --isolate_snapshot_data=/home/ubuntu/savvi-client/build/app/intermediates/flutter/release/isolate_snapshot_data --vm_snapshot_instructions=/home/ubuntu/savvi-client/build/app/intermediates/flutter/release/vm_snapshot_instr --isolate_snapshot_instructions=/home/ubuntu/savvi-client/build/app/intermediates/flutter/release/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /home/ubuntu/savvi-client/build/app/intermediates/flutter/release/app.dill
```



ubuntu@polyglot-2:~/savvi-client$ ls -lah /home/ubuntu/android/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot
-rwxr-xr-x 1 ubuntu ubuntu 4.0M Feb 13 15:30 /home/ubuntu/android/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot

**Comment by jonahwilliams** [comment] 2019-04-18 21:04
For Ubuntu, can you run `sudo apt-get install lib32stdc++6`?

**Comment by bingzhang** [comment] 2019-04-18 21:13
yup, after install lib32stdc++6. I got another error. But it is another problem.

```
ubuntu@polyglot-2:~/savvi-client$ flutter build apk
Initializing gradle...                                              0.6s
Resolving dependencies...                                           1.3s
Error: Unable to write file: /home/ubuntu/savvi-client/build/app/intermediates/flutter/release/vm_snapshot_data
                                                                        
Dart snapshot generator failed with exit code 255                       
Snapshotting exited with non-zero exit code: 255                        
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      12.8s
Gradle task assembleRelease failed with exit code 1
```

**Comment by jonahwilliams** [comment] 2019-04-18 21:19
Do you have write permissions in that directory?

**Comment by bingzhang** [comment] 2019-04-18 21:22
yes, I think so. 

```
ubuntu@polyglot-2:~/savvi-client$ ls -lah /home/ubuntu/savvi-client/build/app/intermediates/flutter/release/vm_snapshot_data
total 8.0K
drwxrwxr-x 2 ubuntu ubuntu 4.0K Apr 18 19:56 .
drwxrwxr-x 3 ubuntu ubuntu 4.0K Apr 18 19:56 ..
```

I run flutter build apk -v, there is some information.

```
[+11666 ms] > Task :app:flutterBuildRelease FAILED
[        ] 39 actionable tasks: 1 executed, 38 up-to-date
[        ]          *********************************************************
[        ] WARNING: This version of flutter_webview_plugin will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] Error: Unable to write file: /home/ubuntu/savvi-client/build/app/intermediates/flutter/release/vm_snapshot_data
[   +1 ms] Dart snapshot generator failed with exit code 255
[        ] Snapshotting exited with non-zero exit code: 255
[ +315 ms] Running Gradle task 'assembleRelease'... (completed in 12.9s)
[        ] *******************************************************************************************
[        ] The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
[        ] See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ] *******************************************************************************************
[   +3 ms] "flutter apk" took 15,342ms.
[        ] "flutter apk" took 15,342ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:462:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:331:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:45:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by jonahwilliams** [comment] 2019-04-26 07:26
It looks like the issue is due to androidX incompatibilities, see https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility for more information

**Comment by Unfreeze-kk** [comment] 2019-05-24 08:57
Try switching to master channel.

**Comment by timsneath** [comment] 2020-01-03 00:27
Closing issue for now, per Jonah's comment. Please reopen it if you have a reproducible issue after making the required changes.

**Closed by timsneath** 2020-01-03 00:27 UTC
Labels: tool
