### ISSUE TITLE
Flutter Channel Master upgrade failing

### ISSUE THREAD

**Issue by FlatCodeIq** [flutter/flutter#83607] opened 2021-05-29 21:01 UTC
Hello,

Today i  have tried to upgrade flutter using `flutter upgrade`
However it is failing, and now every single command even just `flutter `fails the same way.
I even restarted my computer and removed flutter and cleaned all caches in AppData and C://src/bin/
But it's still the same issue. I downloaded Flutter Stable and it worked, even `flutter upgrade` showed latest version for stable channel. and then i changed the channel to Master, and tried to   `flutter upgrade` but it started failing the same way. Also downloading a Master channel directly from Github Repo and running `flutter upgrade`, also fails the same way.
 

## Steps to Reproduce

Note: you must be on Master Channel

1. Open CMD
2. `flutter upgrade`

## Logs

Pub failed to delete entry because it was in use by another process. 
This may be caused by a virus scanner or having a file in the directory open in another application.

## Temporary Solution

Note: i had to change to stable channel until the Devs fix it.

1. Download flutter stable channel from [flutter.dev](https://flutter.dev/docs/get-started/install/windows ), at the time of writing the button reads **flutter_windows_2.2.1-stable.zip**
2. extract the folder.
3. put "flutter" folder in C://src/
4. make sure you got the directory in your env. variables under PATH.
5. `flutter --version` and `flutter upgrade` works now.

**Comment by TahaTesser** [comment] 2021-05-31 11:50
Hi @FlatCodeIq 
Duplicate issue was filed here https://github.com/flutter/flutter/issues/83590

I just upgrade to the latest master with no issues
```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.121, on Microsoft Windows [Version 10.0.19043.1023], locale en-US)
    • Flutter version 2.3.0-17.0.pre.121 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71e711547f (9 hours ago), 2021-05-30 19:31:03 -0700
    • Engine revision 73fe3dd31c
    • Dart version 2.14.0 (build 2.14.0-165.0.dev)
```

Closing as duplicate of https://github.com/flutter/flutter/issues/83590
Thank you

**Closed by TahaTesser** 2021-05-31 11:50 UTC
Labels: in triage
