### ISSUE TITLE
Nothing to do! Android SDK is up to date. SDK emulator directory is missing

### ISSUE THREAD

**Issue by z7b** [flutter/flutter#83479] opened 2021-05-27 13:45 UTC
```
C:\Users\Administrator>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.3.0-12.1.pre, on Microsoft Windows [Version 10.0.19043.985], locale ar-SA)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Android Studio (version 4.2.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

C:\Users\Administrator>
...

**Comment by z7b** [comment] 2021-05-27 13:47
https://www.facebook.com/groups/FlutterEgypt/permalink/754820855203096/

**Comment by TahaTesser** [comment] 2021-05-27 13:49
duplicate of https://github.com/flutter/flutter/issues/83232

**Closed by TahaTesser** 2021-05-27 13:49 UTC
Labels: in triage
