### ISSUE TITLE
[web]: /assets/FontManifest.json 404 Not found Error in Build

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#32477] opened 2019-05-10 09:22 UTC
Flutter version

```
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.13.6 17G4015, locale en-CN)
```

Workflow, use stagehand:

```
$ mkdir foo && cd foo
$ stagehand flutter-web-preview
$ flutter packages pub global activate webdev
$ flutter packages pub upgrade
$ flutter packages pub global run webdev build
$ cd build
$ http-server .
```

Error:

```
"GET /assets/FontManifest.json" Error (404): "Not found"
```

Expected:

Wether or not I need to use `Icon`, this error message should not be present in the production build result.

**Comment by Kiruel** [comment] 2019-05-11 11:48
Follow this dude https://www.didierboelens.com/2019/05/flutter-for-the-web/

**Comment by sgon00** [comment] 2019-05-11 11:55
@Kiruel Very good page. Thanks a lot for the info. :)

**Comment by yjbanov** [comment] 2019-05-30 17:42
Closing as duplicate of https://github.com/flutter/flutter/issues/32245.

**Closed by yjbanov** 2019-05-30 17:42 UTC
Labels: severe: new feature, ☸ platform-web
