### ISSUE TITLE
Layout fails when open the app during beacon ranging

### ISSUE THREAD

**Issue by Marcoslima016** [flutter/flutter#60126] opened 2020-06-23 20:17 UTC
Since last week my project started to present a bug that did not happen before.

I'm using the scan beacon and when opening the app during a ranging, the app opens with its corrupted layout.

package used: flutter_beacon 0.3.0

Thanks for help!

**Comment by iapicca** [comment] 2020-06-24 10:03
Hi @Marcoslima016 
From what I can see, the issue is related to the 3rd party plugin [flutter_beacon](https://pub.dev/packages/flutter_beacon) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/alann-maulana/flutter_beacon/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-24 10:03 UTC

**Comment by Marcoslima016** [comment] 2020-06-29 17:13
I understand that it appears to be related to the plugin.But I've been using the plugin for some time without problems and started to present the bug after an update of the flutter. Going back to flutter version 1.16.1 the bug stops running

**Comment by iapicca** [comment] 2020-07-01 07:39
Hi @Marcoslima016 
I do not doubt that there could be an incompatibility,
but the right way to address the issue is thorough the plugin's github repo,
Thank you
