### ISSUE TITLE
Appveyor flake

### ISSUE THREAD

**Issue by sigurdm** [flutter/flutter#18400] opened 2018-06-12 09:02 UTC
https://ci.appveyor.com/project/flutter/flutter/build/1.0.13956 failed.
After a restart it turned green.

Stack trace:
```
01:03 +10 -1: loading C:\projects\flutter sdk\examples\flutter_gallery\test\smoke_test.dart [E]                                                                                                        
  Shell subprocess crashed with unexpected exit code -1073741819 after tests finished.
  Test: C:\projects\flutter sdk\examples\flutter_gallery\test\smoke_test.dart
  Shell: C:\projects\flutter sdk\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe
  
  
  dart:async/stream_controller.dart 594                      _StreamController.addError
  dart:async/stream_controller.dart 862                      _StreamSinkWrapper.addError
  package:stream_channel/src/guarantee_channel.dart 140      _GuaranteeSink._addError
  package:stream_channel/src/guarantee_channel.dart 131      _GuaranteeSink.addError
  package:flutter_tools/src/test/flutter_platform.dart 448   _FlutterPlatform._startTest.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                  _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77            _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart 438   _FlutterPlatform._startTest.<fn>
  package:flutter_tools/src/test/flutter_platform.dart 624   _FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                  _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77            _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart 370   _FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 363   _FlutterPlatform.loadChannel
  package:test/src/runner/plugin/platform.dart 63            PlatformPlugin.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                     scheduleMicrotask
  dart:async/future.dart 198                                 new Future.microtask
  package:test/src/runner/plugin/platform.dart 60            PlatformPlugin.load
  package:test/src/runner/loader.dart 250                    Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                  _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77            _asyncThenWrapperHelper
  package:test/src/runner/loader.dart 244                    Loader.loadFile.<fn>
  package:test/src/runner/load_suite.dart 89                 new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                     scheduleMicrotask
  dart:async/future.dart 198                                 new Future.microtask
  package:test/src/runner/load_suite.dart 88                 new LoadSuite.<fn>.<fn>
  package:test/src/utils.dart 247                            invoke
  package:test/src/runner/load_suite.dart 88                 new LoadSuite.<fn>
  package:test/src/backend/invoker.dart 403                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                     scheduleMicrotask
  dart:async/future.dart 198                                 new Future.microtask
  package:test/src/backend/invoker.dart 402                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                 new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 925                                   _CustomZone.runGuarded
  dart:async/zone.dart 965                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 949                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21            Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 382        _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416        _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                   new Timer
  dart:async/timer.dart 87                                   Timer.run
  dart:async/future.dart 172                                 new Future
  package:test/src/backend/invoker.dart 402                  Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                  _CustomZone.registerCallback
  dart:async/zone.dart 964                                   _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                     scheduleMicrotask
  dart:async/future.dart 198                                 new Future.microtask
  package:test/src/backend/invoker.dart 389                  Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 1518                                  _runZoned
  dart:async/zone.dart 1465                                  runZoned
  package:test/src/backend/invoker.dart 389                  Invoker._onRun.<fn>.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 1518                                  _runZoned
  dart:async/zone.dart 1465                                  runZoned
  package:test/src/backend/invoker.dart 144                  Invoker.guard
  package:test/src/backend/invoker.dart 441                  Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 388                  Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101                     Chain.capture.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 1518                                  _runZoned
  dart:async/zone.dart 1465                                  runZoned
  package:stack_trace/src/chain.dart 99                      Chain.capture
  package:test/src/backend/invoker.dart 387                  Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188     LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40      _LiveTest.run
  dart:async/future.dart 200                                 new Future.microtask.<fn>
  dart:async/zone.dart 1126                                  _rootRun
  dart:async/zone.dart 1023                                  _CustomZone.run
  dart:async/zone.dart 949                                   _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                      _microtaskLoop
  dart:async/schedule_microtask.dart 50                      _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/isolate_patch.dart 113     _runPendingImmediateCallback
  dart:isolate-patch/dart:isolate/isolate_patch.dart 166     _RawReceivePortImpl._handleMessage
  
01:05 +11 -1: Some tests failed.                                                                                                                                                                       
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Command exited with code 1
```

**Comment by DanTup** [comment] 2018-07-02 12:34
This looks like a dupe of https://github.com/flutter/flutter/issues/18287.

**Closed by DanTup** 2018-07-02 12:34 UTC
Labels: team: flakes
