### ISSUE TITLE
Analysis tool for breaking down app size on Android and iOS

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#51594] opened 2020-02-27 21:55 UTC
Today, you have to run

```
flutter build aot --extra-gen-snapshot-options=--write-v8-snapshot-profile-to=heapsnapshot.json
```

Which will create a heapsnapshot json file. It would be great if we just had a flag or command to do this, so I can stop looking it up every time I need to do it and we can tell customers how to do it more easily.

Bonus points if we can include something (even just a link to a web page) to visualize these.  This helps developers figure out what's ending up in their final code.

/cc @xster

**Comment by xster** [comment] 2020-02-27 21:59
Some instructions https://github.com/dart-lang/sdk/blob/master/runtime/docs/snapshot_profiling.md and https://github.com/flutter/flutter/wiki/Comparing-AOT-Snapshot-Sizes.

It would be great to have ergonomics like `flutter build apk --analyze` or some such.

**Comment by xster** [comment] 2020-02-27 22:26
@devoncarew it would be great to also have a part of this capability in the IDEs (and also in case you guys have spare bandwidth for current planning :D)

**Comment by dnfield** [comment] 2020-03-02 03:33
We probably really want `--print-instructions-sizes-to`, which can give us a tree map of the .so:

```
flutter build aot --release --extra-gen-snapshot-options=--print-instructions-sizes-to=./gallery_instruction_sizes.json
dart ~/src/flutter/engine/src/third_party/dart/pkg/vm/bin/run_binary_size_analysis.dart gallery_instruction_sizes.json ./gallerysize
```

**Comment by jonahwilliams** [comment] 2020-03-03 06:50
Duplicate of https://github.com/flutter/flutter/issues/26609?

**Comment by dnfield** [comment] 2020-03-03 13:58
Going to close that one since this one had more details now

**Comment by jonahwilliams** [comment] 2020-03-06 01:29
Spoke offline about this today - we should probably always write the heapsnapshot to a standard location. Then we could teach tooling how to find it or move it around

**Comment by xster** [comment] 2020-06-02 07:15
@mraleph it's for this ticket. Having the html page to be able to click into for more details is great but I'd love to be able to print a max-depth 1 human readable summary too. 

Mock output:

```shell
$ flutter build apk --analyze

You built build/apk/release/app.apk. 
Total download size: 100mb

Uncompressed breakdown
- Assets and resources: 15mb
- Java dex: 13mb
  - com.example.app 1mb
  - com.example.plugin 5mb
  - com.example.protos 5mb
  - io.flutter.plugins 2mb
- Dart AOT: 9mb
  - package:flutter 3mb
  - package:dart.io 1mb
  - package:video_player 1mb
  - package:app 4mb
- Flutter engine: 27mb
  - x86_64 9mb
  - arm-v7 9mb
  - arm64-v8 9mb
```

or something. I'm making numbers up.

**Comment by jacob314** [comment] 2020-06-02 18:01
Fyi @kenzieschmoll

**Comment by xster** [comment] 2020-06-04 23:18
@jacob314 / @peterdjlee is there a tracking bug for the IDE visualization? We should ideally populate both CLI and IDE/DevTools from the same source. I think we'll need a CLI option for quick glances and CI etc but CLI can at best show max-depth=1 for these things. We should be able to both trigger the analyze output option in IDE and also see the output or transition from the CLI summary into the expanded IDE/DevTools view.

**Comment by jacob314** [comment] 2020-06-05 15:05
Fyi @kenzieschmoll 
Is there a tracking bug filed yet?
Logic that we want to share between devtools and a cli tool can be put in the devtools_shared package which is where existing logic shared between devtools_server and devtools_app. The mock output looks like a good overall summary.

**Comment by kenzieschmoll** [comment] 2020-06-05 16:27
Tracking issue: https://github.com/flutter/devtools/issues/2043

**Comment by xster** [comment] 2020-06-05 20:15
@jacob314 sounds reasonable to me. I see devtools_shared transitively brought into flutter_tools already. @jonahwilliams @jmagman, any thoughts on precedents for flutter_tools commands directly using devtools_shared?

**Comment by jonahwilliams** [comment] 2020-06-05 20:20
> . I see devtools_shared transitively brought into flutter_tools

It does not. The public API of the flutter tools are the command line arguments and registered service extensions. If this feature cannot be implemented with what exists today, then we can add new commands or service extensions.

**Comment by xster** [comment] 2020-06-05 20:23
You might have not answered my question :D I meant in this new command, you guys ok architecturally with it delegating the analysis logic to the devtools_shared package? i.e make the flutter_tools dependency explicit.

**Comment by jonahwilliams** [comment] 2020-06-05 20:26
Oh yeah, that is fine with me - provided there is a reasonable public API. I'm not sure that devtools_shared is the right place for it, but I'd leave that decision to the devtools team

**Comment by jacob314** [comment] 2020-06-05 20:45
we can follow the standard pub package convention that only code outside of the lib/src directory of devtools_shared is part of the public API and then take care not to break the public api. Unless I'm missing something, I expect this should require a minimal public api.

**Comment by jonahwilliams** [comment] 2020-06-05 20:56
SGTM

**Comment by dnfield** [comment] 2020-06-05 21:16
Here's a Dart script that will give some of what @xster is looking for, assuming `galleryJson` contains a string with the output of the instruction sizes json:

```dart
import 'dart:convert';

void main() {
  final SymbolNode root = parseSymbols(json.decode(galleryJson));
  for (SymbolNode node in root.children) {
    print('${node.name}: ${(node.value / 1000).toStringAsFixed(2)}');
    if (node.name == 'package:flutter') {
      for (SymbolNode flutterNode in node.children.first.children) {
        print('  ${flutterNode.name}: ${(flutterNode.value / 1000).toStringAsFixed(2)}');
      }
    }
  }
}

class SymbolNode {
  SymbolNode(
    this.name, {
    int value = 0,
  })  : assert(name != null),
        assert(value != null),
        _children = <String, SymbolNode>{},
        _value = value;

  /// The human friendly identifier for this node.
  final String name;

  int _value;
  int get value {
    _value ??= children.fold(
      0,
      (int accumulator, SymbolNode node) => accumulator + node.value,
    );
    return _value;
  }

  SymbolNode _parent;
  SymbolNode get parent => _parent;

  final Map<String, SymbolNode> _children;

  Iterable<SymbolNode> get children => _children.values;

  SymbolNode childByName(String name) => _children[name];

  SymbolNode addChild(SymbolNode child) {
    assert(child.parent == null);
    assert(!_children.containsKey(child.name),
        'Cannot add duplicate child key ${child.name}');

    child._parent = this;
    _children[child.name] = child;
    SymbolNode ancestor = this;
    while (ancestor != null) {
      ancestor._value += child.value;
      ancestor = ancestor.parent;
    }
    return child;
  }

  List<SymbolNode> get ancestors {
    List<SymbolNode> nodes = <SymbolNode>[];
    SymbolNode current = this;
    while (current.parent != null) {
      nodes.add(current.parent);
      current = current.parent;
    }
    return nodes;
  }

  bool get isLeaf => _children.isEmpty;

  Iterable<SymbolNode> get siblings {
    List<SymbolNode> result = <SymbolNode>[];
    if (parent == null) {
      return result;
    }
    for (SymbolNode sibling in parent.children) {
      if (sibling != this) {
        result.add(sibling);
      }
    }
    return result;
  }
}

SymbolNode parseSymbols(List<dynamic> symbols) {
  final iter = symbols.cast<Map<String, dynamic>>().map(Symbol.fromMap);
  final SymbolNode root = SymbolNode('root');
  SymbolNode currentParent = root;
  for (Symbol symbol in iter) {
    SymbolNode parentReset = currentParent;
    for (String pathPart in symbol.parts.take(symbol.parts.length - 1)) {
      currentParent = currentParent.childByName(pathPart) ??
          currentParent.addChild(SymbolNode(pathPart));
    }
    // TODO: this shouldn't be necessary, https://github.com/dart-lang/sdk/issues/41137
    String leafName = symbol.parts.last;
    int duplicates = 0;
    while (currentParent.childByName(leafName) != null) {
      duplicates += 1;
      leafName = '${symbol.parts.last}_$duplicates';
    }
    currentParent.addChild(
      SymbolNode(leafName, value: symbol.size),
    );
    currentParent = parentReset;
  }
  return root;
}

class Symbol {
  const Symbol({
    /* @required */ this.name,
    /* @required */ this.size,
    this.libraryUri,
    this.className,
  })  : assert(name != null),
        assert(size != null);

  static Symbol fromMap(Map<String, dynamic> json) {
    return Symbol(
      name: (json['n'] as String).replaceAll('[Optimized] ', ''),
      size: json['s'] as int,
      className: json['c'] as String,
      libraryUri: json['l'] as String,
    );
  }

  final String name;
  final int size;
  final String libraryUri;
  final String className;

  List<String> get parts {
    return <String>[
      if (libraryUri != null) ...libraryUri.split('/') else '@stubs',
      if (className != null && className.isNotEmpty) className,
      name,
    ];
  }
}
```

**Comment by jmagman** [comment] 2020-07-27 22:59
See https://pub.dev/packages/vm_snapshot_analysis README if you want to try this functionality before it's fully integrated into Flutter.

**Comment by xster** [comment] 2020-07-29 18:58
Slight clarification: https://pub.dev/packages/vm_snapshot_analysis is a package being used to produce part of the content (AOT breakdown) this tool is meant to produce (APK/APP breakdown).

**Comment by jonahwilliams** [comment] 2020-09-01 22:00
I think we finished this one up, can you confirm @kenzieschmoll @xster ?

**Comment by xster** [comment] 2020-09-02 00:05
Ya, we're done for this branch cut. The only thing remaining is adding some documentation around it and rewrite https://flutter.dev/docs/perf/app-size slightly.

**Closed** 2020-09-18 21:58 UTC
Labels: P5, a: size, perf: app size, platform-android, platform-ios, severe: new feature, severe: performance, tool
