### ISSUE TITLE
Null Safety static analysis not working using contains

### ISSUE THREAD

**Issue by saveKenny** [flutter/flutter#109984] opened 2022-08-22 07:00 UTC
Dart static analysis does not detect null safety free issues using `contains` statement.

For example:
```
void main() {
  final String? a = 'a';
  final String? b = 'b';
  
  if (a != null && b != null) {
    print(a + b); // <--- All good, no problem with the static analysis
  }
  
  if (![a, b].contains(null)) {
    print(a + b); // <--- Raise: The operator '+' can't be unconditionally invoked because the receiver can be 'null' 
  }
}
```

The above function raise:

> The operator '+' can't be unconditionally invoked because the receiver can be 'null'

Checkout the [dartpad gist](https://dartpad.dev/?fcf4c14ad9b3dd3949e97a821b83b646) that reproduce this issue.

**Comment by exaby73** [comment] 2022-08-22 13:02
Hello @saveKenny. For Dart, `.contains()` is just another method. It doesn't know that this code would result in the condition only being true when there is no `null`s. 

In your first example, Dart understands that you are checking that both variables are not `null`. In the second statement, all Date see's is that you are calling a method that returns a `bool`. It has no context of the login within the method itself since this is not an operator or keyword. And it would be impractical to expect Dart to analyze code to try and figure out what logic you have implemented.

For this reason, I am closing this issue as this is not a bug nor a feature request, and is working as expected. Thank you.

**Closed by exaby73** 2022-08-22 13:02 UTC
Labels: in triage

**Comment by saveKenny** [comment] 2022-08-22 22:48
Very clear answer. Thanks for the clarification! 🙏
