### ISSUE TITLE
'widget span' wrong position in 'Text.rich'

### ISSUE THREAD

**Issue by HassanEm** [flutter/flutter#95904] opened 2021-12-28 13:35 UTC
Hello everyone, it looks like there is an issue in showing `WidgetSpan` in `Text.rich`. it's happened when I use Arabic or Persian.
![Screenshot (255)](https://user-images.githubusercontent.com/24267954/147570711-e7faba3a-66ed-40ee-8e83-f358e34166a8.png)

as you can see in the picture the icons positions are wrong.

and these are the whole code that I tested in https://dartpad.dev/

```dart
import 'package:flutter/material.dart';


void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child:  Text.rich(
              TextSpan(children: [
                TextSpan(text: 'مقدار'),
                WidgetSpan(child: Icon(Icons.one_k)),
               
                TextSpan(text: 'در معادله'),
                
                WidgetSpan(child: Icon(Icons.two_k)),
                TextSpan(text: 'چقدر است'),
              ]),
              // textAlign: TextAlign.start,
            )
        ),
      ),
    );
  }
}
```

**Comment by maheshmnj** [comment] 2021-12-29 05:24
Hi @HassanEm, Thanks for filing the issue, I am seeing similar output on web and Desktop, Is the issue with Directionality? Can you please share what is the expected output?

![image](https://user-images.githubusercontent.com/31410839/147630008-84ac032a-aa97-4be6-998d-248f7c11a4c7.png)

**Comment by HassanEm** [comment] 2021-12-29 08:22
> Hi @HassanEm, Thanks for filing the issue, I am seeing similar output on web and Desktop, Is the issue with Directionality? Can you please share what is the expected output?
> 
> ![image](https://user-images.githubusercontent.com/31410839/147630008-84ac032a-aa97-4be6-998d-248f7c11a4c7.png)

Hello @maheshmnj, thanks for your response actually, in Persian the text is written from right to left, and flutter does it as well but seems the rich text doesn't touch the widget span.

![Screenshot (256)](https://user-images.githubusercontent.com/24267954/147640128-ac377ea2-9598-4b32-bd36-1becdd4ca72f.png)

 ### text == متن

take a look at this case I have to see text 1 and one_k icon together, but I see text 1 and three_k icon together

### Expected 
![Screenshot (259)](https://user-images.githubusercontent.com/24267954/147641180-e4d7ff55-58be-4524-b4fb-ed44a377417b.png)
I think I have to see one of these results

**Comment by maheshmnj** [comment] 2021-12-29 11:12
Thanks for the info @HassanEm, I believe this issue is a duplicate of https://github.com/flutter/flutter/issues/44449. Closing this issue as a duplicate, if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-12-29 11:12 UTC
Labels: in triage
