### ISSUE TITLE
FLUTTER 3.7.0 : Text emoticons doesnt show its regular color

### ISSUE THREAD

**Issue by Sulav-Beehave** [flutter/flutter#119602] opened 2023-01-31 06:30 UTC
After update to 3.7.0 (stable branch) the text emoticons (for example: 😄) doesnt display in original color. 

Current Result:
![Screenshot_20230131_120439](https://user-images.githubusercontent.com/57428250/215683179-ba8499cf-0cad-4de9-8414-ad2b1f1339fc.png)

Expected Result:
![Screenshot_20230131_120933](https://user-images.githubusercontent.com/57428250/215683324-7c7d0b28-81a2-45d0-a82b-7945b8abc75e.png)

**Comment by KnucklesEQ** [comment] 2023-01-31 08:28
Similar issue: https://github.com/flutter/flutter/issues/119536

**Comment by exaby73** [comment] 2023-01-31 09:07
This looks like a duplicate of https://github.com/flutter/flutter/issues/119536. Therefore, I am closing the issue. Thank you

**Closed by exaby73** 2023-01-31 09:07 UTC
Labels: in triage
