### ISSUE TITLE
Flutter run build failed with an exception

### ISSUE THREAD

**Issue by rakakhrl** [flutter/flutter#53552] opened 2020-03-30 05:04 UTC
I got this error when i try to run my project to my device.

```
Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar_route.dart:303:8: Error: The method 'FlushbarRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
  void install() {
       ^
/C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install(OverlayEntry insertionPoint) {
       ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar_route.dart:311:18: Error: Too few positional arguments: 1 required, 0 given.
    super.install();
                 ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
```

## Steps to Reproduce

1. Run `flutter create project && cd project`.
2. Run `flutter run`.

**Expected results:** The project run on the device connected

**Actual results:** Project build failed

<details>
  <summary>Logs</summary>

flutter run --verbose
```
[  +36 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +55 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +33 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +7 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +82 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +129 ms] executing: C:\Users\TOSHIBA\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +16 ms] Exit code 0 from: C:\Users\TOSHIBA\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           GCAZGF00K849GGM        device product:WW_Phone model:ASUS_Z017DB device:ASUS_Z017D_1 transport_id:6
[  +17 ms] C:\Users\TOSHIBA\AppData\Local\Android\sdk\platform-tools\adb.exe -s GCAZGF00K849GGM shell getprop
[  +92 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] Found plugin cloud_firestore at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\
[   +7 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+2\
[   +6 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+2\
[  +15 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\
[   +2 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +3 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +2 ms] Found plugin firebase_messaging at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-5.1.8\
[  +81 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+3\
[   +1 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\
[   +3 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[  +74 ms] Found plugin cloud_firestore at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\
[   +2 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+2\
[   +1 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+2\
[   +7 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+12\
[   +1 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +2 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +1 ms] Found plugin firebase_messaging at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-5.1.8\
[  +38 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+3\
[   +1 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\
[   +2 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[ +113 ms] Generating D:\Project\avicenna-mobile\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +39 ms] ro.hardware = qcom
[  +80 ms] Launching lib\main.dart on ASUS Z017DB in debug mode...
[  +15 ms] executing: C:\Users\TOSHIBA\AppData\Local\Android\sdk\platform-tools\adb.exe -s GCAZGF00K849GGM shell -x logcat -v time
-t 1
[ +213 ms] Exit code 0 from: C:\Users\TOSHIBA\AppData\Local\Android\sdk\platform-tools\adb.exe -s GCAZGF00K849GGM shell -x logcat -v
time -t 1
[        ] --------- beginning of main
           03-30 11:56:09.037 D/WifiStateMachine( 1538): [wlan]: ["SCI", ac:64:62:dc:37:e0]=(-64, 65)
[   +6 ms] executing: C:\Users\TOSHIBA\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +1 ms] executing: C:\Users\TOSHIBA\AppData\Local\Android\sdk\platform-tools\adb.exe -s GCAZGF00K849GGM logcat -v time -T 03-30
11:56:09.037
[  +63 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\TOSHIBA\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\TOSHIBA\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +24 ms] Building APK
[  +22 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from D:\Project\avicenna-mobile\android\gradlew.bat.
[  +44 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +103 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +4 ms] executing: [D:\Project\avicenna-mobile\android\] D:\Project\avicenna-mobile\android\gradlew.bat -Pverbose=true
-Ptarget=D:\Project\avicenna-mobile\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm64 assembleDebug
[+1448 ms] > Configure project :app
[        ] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[        ] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[   +1 ms] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[+2980 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +38 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] [        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +32 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.8-0-g0b8abb472
[        ] [   +9 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\flutter\] git ls-remote --get-url origin
[        ] [  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +66 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[        ] [  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +24 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +99 ms] Initializing file store
[        ] [  +17 ms] Done initializing file store
[ +186 ms] [+1246 ms] kernel_snapshot: Starting due to {InvalidatedReason.inputChanged}
[ +102 ms] [  +18 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-ca
ll-instructions --enable-asserts --track-widget-creation --no-link-platform --packages D:\Project\avicenna-mobile\.packages
--output-dill D:\Project\avicenna-mobile\.dart_tool\flutter_build\5bd48c80585c84671087f6b0787f84f4\app.dill --depfile
D:\Project\avicenna-mobile\.dart_tool\flutter_build\5bd48c80585c84671087f6b0787f84f4\kernel_snapshot.d
package:avicenna_mobile/main.dart
[+1598 ms] [+1612 ms]
[   +1 ms]            Compiler message:
[        ] [   +1 ms] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar_route.dart:303:8: Error: The
method 'FlushbarRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
[        ] [        ]   void install() {
[        ] [        ]        ^
[        ] [        ] /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method
('install').
[        ] [        ]   void install(OverlayEntry insertionPoint) {
[        ] [        ]        ^
[+3093 ms] [+3165 ms] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar_route.dart:311:18: Error: Too few
positional arguments: 1 required, 0 given.
[   +1 ms] [        ]     super.install();
[        ] [        ]                  ^
[+2799 ms] [+2770 ms] Persisting file store
[        ] [  +23 ms] Done persisting file store
[        ] [   +1 ms] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[        ] build failed.
[        ] [   +7 ms] "flutter assemble" took 9.019ms.
[  +75 ms] #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
[        ] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:183:7)
[        ] <asynchronous suspension>
[        ] #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
[   +1 ms] <asynchronous suspension>
[        ] #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
[        ] <asynchronous suspension>
[        ] #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
[        ] #5      _rootRun (dart:async/zone.dart:1126:13)
[        ] #6      _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #7      _runZoned (dart:async/zone.dart:1518:10)
[        ] #8      runZoned (dart:async/zone.dart:1465:12)
[        ] #9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
[        ] #10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
[        ] #11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
[        ] #12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
[        ] <asynchronous suspension>
[        ] #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
[        ] #14     _rootRun (dart:async/zone.dart:1126:13)
[        ] #15     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #16     _runZoned (dart:async/zone.dart:1518:10)
[        ] #17     runZoned (dart:async/zone.dart:1465:12)
[        ] #18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
[        ] #19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
[        ] #20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
[        ] #21     new Future.sync (dart:async/future.dart:224:31)
[        ] #22     CommandRunner.run (package:args/command_runner.dart:112:14)
[        ] #23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
[   +1 ms] #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
[        ] #25     _rootRun (dart:async/zone.dart:1126:13)
[        ] #26     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #27     _runZoned (dart:async/zone.dart:1518:10)
[        ] #28     runZoned (dart:async/zone.dart:1502:12)
[        ] #29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
[        ] <asynchronous suspension>
[        ] #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
[        ] #31     _rootRun (dart:async/zone.dart:1126:13)
[        ] #32     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #33     _runZoned (dart:async/zone.dart:1518:10)
[        ] #34     runZoned (dart:async/zone.dart:1465:12)
[        ] #35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
[        ] #36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
[        ] #37     run (package:flutter_tools/runner.dart:50:10)
[        ] #38     main (package:flutter_tools/executable.dart:65:9)
[        ] #39     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
[        ] #40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
[        ] #41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[        ] > Task :app:compileFlutterBuildDebug FAILED
[   +3 ms] 1 actionable task: 1 executed
[   +1 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 12s
[ +318 ms] Running Gradle task 'assembleDebug'... (completed in 12,8s)
[   +5 ms] "flutter run" took 14.044ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
```

flutter doctor -v
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.10240], locale id-ID)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\TOSHIBA\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\TOSHIBA\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • ASUS Z017DB • GCAZGF00K849GGM • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

</details>

**Comment by iapicca** [comment] 2020-03-30 06:06
Hi @rakakhrl 
the error in you logs seems to be caused by the third party plugin or package [flushbar](https://pub.dev/packages/flushbar) you may want to open an issue in the dedicated [github](https://github.com/AndreHaueisen/flushbar/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2020-03-30 06:06 UTC
Labels: p: third party

**Comment by rakakhrl** [comment] 2020-03-30 06:18
Ah yes you're right, sorry for not reading the error message properly
