### ISSUE TITLE
[web]: screenshot RepaintBoundary contains Image  don't work

### ISSUE THREAD

**Issue by tv009** [flutter/flutter#115822] opened 2022-11-22 10:16 UTC
**RepaintBoundary contains Image  don't work
RepaintBoundary contains Canvas(image)   don't work**

Canvaskit no warning, Html render null Exception!

Other platform is fine!

Obx(() {
              return RepaintBoundary(
                key: logic.out_key,
                child: Container(
                  alignment: Alignment.center,
                  width: 500,
                  height: 500,
                  child: Column(
                    children: [
                      Image.asset("/images/little.jpeg")
                      ,Text(state.back_img.value.toString())
                      // CustomPaint(
                      //   painter: MyImgPaint(state.back_img.value),
                      //   // foregroundPainter: MyImgPaint(state.foreground_img.value),
                      //   child: Image.asset("/images/little.jpeg"),
                      // ),
                    ],
                  ),
                ),
              );
            })

[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6.1 21G217 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.8 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (13 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at 
    • Platform android-33, build-tools 33.0.0
    • Java binary at: 
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at 
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at 
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.110

**Comment by huycozy** [comment] 2022-11-23 05:12
@tv009 thanks for providing sample code. But I think it relates to CORS issue rather than RepaintBoundary. When removing RepaintBoundary, the image also can not display and there is exception log from the console.

<details>
<summary>Exception logs</summary>

```bash
An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:51980/ect3YGMI-Oo=
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following ImageCodecException was thrown resolving an image codec:
Failed to load network image.
Image URL: https://www.baidu.com/img/flexible/logo/pc/result@2.png
Trying to load an image from another domain? Find answers at:
https://flutter.dev/docs/development/platform-integration/web-images

When the exception was thrown, this was the stack

Image provider: NetworkImage("https://www.baidu.com/img/flexible/logo/pc/result@2.png", scale: 1)
Image key: NetworkImage("https://www.baidu.com/img/flexible/logo/pc/result@2.png", scale: 1)
════════════════════════════════════════════════════════════════════════════════════════════════════
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51980/ect3YGMI-Oo=
```
</details>

When using another image (for eg [this image](https://www.online-image-editor.com/styles/2019/images/power_girl.png)), the issue is not reproducible.

<details>
<summary>Demo (another image source)</summary>

![Screenshot 2022-11-23 at 12 07 48](https://user-images.githubusercontent.com/104349824/203472728-7f9ac879-85ef-44bb-a87c-c5c53ef6bf55.png)

</details>

<details>
<summary>Sample code</summary>

```dart
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Uint8List bytes = Uint8List(0);
  var rbkey = GlobalKey();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            RepaintBoundary(
              key:rbkey,
              child: Column(
                children: [
                  const Text(
                    'I can show below',
                  ),
                  Image.network("https://www.online-image-editor.com/styles/2019/images/power_girl.png"), //but Image don't show below
                ],
              ),
            ),

            ElevatedButton(onPressed: (){
              fetchData(rbkey).then((value) =>
                  setState(() {
                    bytes = value;
                    print(bytes);
                  })
              );
            }, child: Text("press me")),
            if(bytes.isNotEmpty)Image.memory(bytes)
          ],
        ),
      ),
    );
  }
}

Future<Uint8List> fetchData(GlobalKey key) async {
  var boundary = key.currentContext!.findRenderObject()! as RenderRepaintBoundary;
  final ui.Image image = await boundary.toImage();
  final ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
  final Uint8List pngBytes = byteData!.buffer.asUint8List();
  return pngBytes;
}

```
</details>

This is also a known issue #92344. Please check flutter docs [rendering images on the web](https://flutter.dev/docs/development/platform-integration/web-images) as a reference for this. 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. Thank you!

**Closed by huycozy** 2022-11-23 05:12 UTC
Labels: in triage

**Comment by tv009** [comment] 2022-11-23 06:18
![nothing](https://user-images.githubusercontent.com/3796662/203480938-162dc575-3295-4404-9944-e9c328b6ca8b.png)
![loacal_network](https://user-images.githubusercontent.com/3796662/203480937-1203b04c-64fa-49c2-a428-ec981878f7ce.png)

The following code contains local images
`import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Uint8List bytes = Uint8List(0);
  var rbkey = GlobalKey();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: <Widget>[
          RepaintBoundary(
            key:rbkey,
            child: Column(
              children: [
                Image.asset('/images/little.jpeg',width:100,height:100),
                const Text(
                  'I can show below',
                ),
                Image.network("https://www.online-image-editor.com/styles/2019/images/power_girl.png"
                  ,width: 100,height: 100,), //but Image don't show below
              ],
            ),
          ),

          ElevatedButton(onPressed: (){
            fetchData(rbkey).then((value) =>
                setState(() {
                  bytes = value;
                  print(bytes);
                })
            );
          }, child: Text("press me")),
          if(bytes.isNotEmpty)Image.memory(bytes)
        ],
      ),
    );
  }
}

Future<Uint8List> fetchData(GlobalKey key) async {
  var boundary = key.currentContext!.findRenderObject()! as RenderRepaintBoundary;
  final ui.Image image = await boundary.toImage();
  final ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
  final Uint8List pngBytes = byteData!.buffer.asUint8List();
  return pngBytes;
}
`

CORS issue will cause the above figure to be unable to be displayed, so I don't agree with you. I now suspect that there is something wrong with my environment

Thank you again for your attention

**Comment by tv009** [comment] 2022-11-24 23:52
A solution has been found. The same code Windows compiles normally, but the mac compiles abnormally!
@huycozy

**Comment by huycozy** [comment] 2022-11-25 05:42
>The fluttr version of the mac environment has been changed from stable to master, which is now a perfect solution!

@tv009 Yes, my previous demo at https://github.com/flutter/flutter/issues/115822#issuecomment-1324562166 is built with Flutter master channel `3.6.0`. That's reason why I didn't see the same behavior as yours at https://github.com/flutter/flutter/issues/115822#issuecomment-1324603055. 

Update the label corresponding to the investigation. Thanks!
