### ISSUE TITLE
Exception caught by gesture

### ISSUE THREAD

**Issue by kentcb** [flutter/flutter#14380] opened 2018-01-31 04:18 UTC
## Steps to Reproduce

Don't really know - was just writing my app at the time. I see a lot of these kinds of issues open, but not really sure whether mine is unique or not.

## Logs

```
I/flutter (21656): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (21656): The following assertion was thrown while handling a gesture:
I/flutter (21656): 'package:flutter/src/material/ink_well.dart': Failed assertion: line 41 pos 15: 'controller !=
I/flutter (21656): null': is not true.
I/flutter (21656): 
I/flutter (21656): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (21656): more information in this error message to help you determine and fix the underlying cause.
I/flutter (21656): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (21656):   https://github.com/flutter/flutter/issues/new
I/flutter (21656): 
I/flutter (21656): When the exception was thrown, this was the stack:
I/flutter (21656): #2      new InteractiveInkFeature (package:flutter/src/material/ink_well.dart:41:15)
I/flutter (21656): #3      new InkSplash (package:flutter/src/material/ink_splash.dart:130:8)
I/flutter (21656): #4      _InkSplashFactory.create (package:flutter/src/material/ink_splash.dart:61:16)
I/flutter (21656): #5      _TextFieldState._createInkFeature (package:flutter/src/material/text_field.dart:366:46)
I/flutter (21656): #6      _TextFieldState._startSplash (package:flutter/src/material/text_field.dart:405:42)
I/flutter (21656): #7      _TextFieldState._handleTapDown (package:flutter/src/material/text_field.dart:384:5)
I/flutter (21656): #8      TapGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:142:57)
I/flutter (21656): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (21656): #10     TapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:142:9)
I/flutter (21656): #11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:121:7)
I/flutter (21656): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (21656): #13     BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter (21656): #14     BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (21656): #15     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (21656): #16     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (21656): #17     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (21656): #18     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:134)
I/flutter (21656): #19     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
I/flutter (21656): (elided 2 frames from class _AssertionError)
I/flutter (21656): 
I/flutter (21656): Handler: onTapDown
I/flutter (21656): Recognizer:
I/flutter (21656):   TapGestureRecognizer#cf498(debugOwner: GestureDetector, state: ready, finalPosition: Offset(111.6,
I/flutter (21656):   333.0))
I/flutter (21656): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale en-AU, channel master)
    • Flutter version 0.0.21-pre.299 at C:\Users\kent\Repository\flutter
    • Framework revision 84580b545a (6 days ago), 2018-01-24 13:16:23 -0800
    • Engine revision d715860925
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.8d9d68751a505426eb5f59a9d29f103fde6bd474

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.4127.31

[√] Connected devices
    • Pixel • FA6AF0303979 • android-arm • Android 8.1.0 (API 27)
```

**Comment by Hixie** [comment] 2018-01-31 04:53
cc @HansMuller who wrote this code recently.

**Comment by zoechi** [comment] 2019-01-21 16:38
Duplicate of #14764

**Closed by zoechi** 2019-01-21 16:38 UTC
Labels: f: material design, framework, severe: crash
