### ISSUE TITLE
[tool_crash] SessionNotCreatedException

### ISSUE THREAD

**Issue by ZhuChanJuan** [flutter/flutter#148029] opened 2024-05-09 01:49 UTC
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome --release --browser-name=edge -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SessionNotCreatedException
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:81:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:157:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:324:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel beta, 3.22.0-0.3.pre, on macOS 14.3.1 23D60 darwin-arm64, locale en-CN)
    [32m•[39m Flutter version 3.22.0-0.3.pre on channel beta at /Users/vickyzhu/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 87b652410d (2 weeks ago), 2024-04-23 21:41:18 -0500
    [32m•[39m Engine revision b4bfd45986
    [32m•[39m Dart version 3.4.0 (build 3.4.0-282.3.beta)
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/vickyzhu/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/vickyzhu/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15E204a
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version 1.76.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.3.1 23D60 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                • web-javascript • Google Chrome 124.0.6367.156

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 87b652410dbf20003c437ab6512118622d95770f
### Plugins
integration_test

**Comment by danagbemava-nc** [comment] 2024-05-09 06:36
Closing this as a duplicate of https://github.com/flutter/flutter/issues/141010

**Closed by danagbemava-nc** 2024-05-09 06:36 UTC
Labels: in triage

**Comment by ZhuChanJuan** [comment] 2024-05-09 06:41
hi @danagbemava-nc , actually they're not same issues.

on my Mac,  i could run flutter native test cases on MacOS Chrome web browser successfully without any exceptions with command : `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome --release `.
since i download chrome webdriver by command and they're compatible with each other.


but if i added other parameter `--browser-name=edge -v`, i receive a crash error without exception. the error details has pasted in the top.

**Comment by danagbemava-nc** [comment] 2024-05-09 13:31
They are the same issue because the crash happens within the same methods in the flutter tool. The command you run itself isn't the issue

**Comment by ZhuChanJuan** [comment] 2024-05-13 02:15
oh, if so , then it seems the root cause maybe "flutter drive" command isn't that stable.
