### ISSUE TITLE
Error about no more pages showing in Flutter

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#112916] opened 2022-10-05 05:47 UTC
I get an error about no more pages showing up in Flutter, here is the debug console:

    ════════ Exception caught by gesture ═══════════════════════════════════════════
    The following assertion was thrown while handling a gesture:
    have popped the last page off of the stack; there are no pages left to show
    'package:go_router/src/go_router_delegate.dart':
    Failed assertion: line 178 pos 12: '_matches.isNotEmpty'
    
    
    When the exception was thrown, this was the stack
    #2      GoRouterDelegate.pop
    #3      GoRouterDelegate._builder.<anonymous closure>
    #4      NavigatorState.pop
    #5      _ABCScreenState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>
    #6      showAlertDialog.<anonymous closure>.<anonymous closure>
    #7      _InkResponseState._handleTap
    #8      GestureRecognizer.invokeCallback
    #9      TapGestureRecognizer.handleTapUp
    #10     BaseTapGestureRecognizer._checkUp
    #11     BaseTapGestureRecognizer.handlePrimaryPointer
    #12     PrimaryPointerGestureRecognizer.handleEvent
    #13     PointerRouter._dispatch
    #14     PointerRouter._dispatchEventToRoutes.<anonymous closure>
    #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
    #16     PointerRouter._dispatchEventToRoutes
    #17     PointerRouter.route
    #18     GestureBinding.handleEvent
    #19     GestureBinding.dispatchEvent
    #20     RendererBinding.dispatchEvent
    #21     GestureBinding._handlePointerEventImmediately
    #22     GestureBinding.handlePointerEvent
    #23     GestureBinding._flushPointerEventQueue
    #24     GestureBinding._handlePointerDataPacket
    #28     _invoke1 (dart:ui/hooks.dart:170:10)
    #29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
    #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
    (elided 5 frames from class _AssertionError and dart:async)
    Handler: "onTap"
    Recognizer: TapGestureRecognizer#2278a
        debugOwner: GestureDetector
        state: possible
        won arena
        finalPosition: Offset(257.4, 487.2)
        finalLocalPosition: Offset(23.1, 28.6)
        button: 1
        sent tap down
    ════════════════════════════════════════════════════════════════════════════════

The error above looks like I'm using too many popups and there are no more screens for me to pop, but I only use one, which is `Navigator.of(context).pop(true)`. I use it when a dialog pops up asking the user if they are sure they want to delete something.

I also didn't use `context.pop(context)`(function in [`go_router`][1]), but why is there the word ***"go_router"*** in error_message. So, I don't know where exactly the problem is.

Here is some code:

`package:go_router/src/go_router_delegate.dart`(line 178):

    assert(_matches.isNotEmpty,

`Dismissible` widget(delete something):
```
Dismissible(
  key: Key("key"),
  background: Container(
    color: Colors.red,
    child: Padding(
      padding: const EdgeInsets.all(padding),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.end,
        children: const [
          Icon(
            Icons.delete,
            color: AppColors.kIconColor,
          ),
        ],
      ),
    ),
  ),
  direction: DismissDirection.endToStart,
  onDismissed: (direction) async => await _delete(
    context,
    list[index],
  ),
  confirmDismiss: (DismissDirection direction) async {
    return await showConfirmDeletionDialog(
      context,
      "something",
      () => Navigator.of(context).pop(true),
    );
  },
  child: child,
),
```

`_delete`(function to delete something):
```
Future<void> _delete(
  BuildContext context,
  Model model,
) async {
  try {
    function
  } on FirebaseException catch (e) {
    function
  }
}
```

`showConfirmDeletionDialog`(pops the dialog to make sure something will be deleted):
```
Future<dynamic> showConfirmDeletionDialog(
  BuildContext context,
  String thingsToDelete,
  VoidCallback delete,
) async {
  return await showAlertDialog(
    context,
    "Confirm $thingsToDelete deletion".hardcoded,
    "Are you sure you with to delete this?".hardcoded,
    "Cancel".hardcoded,
    "Delete $thingsToDelete".hardcoded,
    delete,
  );
}
```

`showAlertDialog`(popup dialog):
```
Future<dynamic> showAlertDialog(
  BuildContext context,
  String title,
  String content,
  String cancelActionText,
  String defaultActionText,
  VoidCallback? onDefaultActionButtonTap,
) async {
  if (kIsWeb || Platform.isAndroid) {
    return await showDialog(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppColors.kBackgroundColor,
        title: Text(
          title,
          style: AppTextStyles.kDefaultStyle,
        ),
        content: Text(
          content,
          style: AppTextStyles.kDefaultStyle,
        ),
        actions: <Widget>[
          if (cancelActionText.isNotEmpty)
            TextButton(
              onPressed: cancelActionText.isEmpty
                  ? null
                  : () => Navigator.of(context).pop(false),
              child: Text(
                cancelActionText,
                style: AppTextStyles.kDefaultStyle,
              ),
            ),
          TextButton(
            onPressed: () {
              try {
                onDefaultActionButtonTap!.call();
              } finally {
                Navigator.of(context).pop(true);
              }
            },
            child: Text(
              defaultActionText,
              style: AppTextStyles.kDefaultStyle,
            ),
          ),
        ],
      ),
    );
  } else {
    return await showCupertinoDialog(
      context: context,
      builder: (context) => CupertinoAlertDialog(
        title: Text(
          title,
          style: AppTextStyles.kDefaultStyle,
        ),
        content: Text(
          content,
          style: AppTextStyles.kDefaultStyle,
        ),
        actions: <Widget>[
          if (cancelActionText.isEmpty)
            CupertinoButton(
              onPressed: cancelActionText.isEmpty
                  ? null
                  : () => Navigator.of(context).pop(false),
              child: Text(
                cancelActionText,
                style: AppTextStyles.kDefaultStyle,
              ),
            ),
          CupertinoButton(
            onPressed: onDefaultActionButtonTap,
            child: Text(
              defaultActionText,
              style: AppTextStyles.kDefaultStyle,
            ),
          ),
        ],
      ),
    );
  }
}
```

I checked my code many times but I still can't find other popups, if you see any other popups please remember to comment this question.

Feel free to comment me if you need more complete information.

How can I fix this error? I don't know how to fix this. Appreciate if someone can advise. Thank you in advance!

  [1]: https://pub.dev/packages/go_router

**Comment by darshankawar** [comment] 2022-10-05 08:04
Based on the error log, closing as duplicate of https://github.com/flutter/flutter/issues/106166

**Closed by darshankawar** 2022-10-05 08:04 UTC
Labels: in triage

**Comment by mycar98765** [comment] 2022-10-05 12:17
@darshankawar I don't think this is a duplicate because I'm not using `context.pop(context)`(function in [`go_router`][1])

  [1]: https://pub.dev/packages/go_router
