### ISSUE TITLE
Keyboard obstructs the text field on focus on 3.8 beta channel

### ISSUE THREAD

**Issue by khaiql** [flutter/flutter#121124] opened 2023-02-21 06:32 UTC
## Steps to Reproduce

I have a chat page with the list of messages and the chat input at the bottom of the page. After upgrading to the latest version on channel beta 3.8, the behaviour has been changed unexpectedly that the keyboard obstructs the text field instead of pushing it up like in previous version

**Expected results:** 

On 3.7

https://user-images.githubusercontent.com/9031129/220264865-66f22322-16bd-46e5-bb0c-acfedeb4b240.mp4

**Actual results:** 

On 3.8

https://user-images.githubusercontent.com/9031129/220264841-0e6eb0d9-4b0f-42ec-acdc-3483a1a0f04c.mp4

<details>
<summary>Code sample</summary>

```dart
// Chat Page
                return GestureDetector(
                  onTap: _focusNode.unfocus,
                  child: Scaffold(
                    appBar: AppBar(
                      title: Text(_thread!.displayName),
                      actions: _appbarActions(),
                    ),
                    body: Column(
                      children: [
                        EnableNotificationsReminderFlash(
                            message: '$_i18nRoot.enable_notifications_reminder'
                                .tr()),
                        Flexible(
                            child: Padding(
                          padding:
                              const EdgeInsets.all(AppThemes.contentPadding),
                          child: buildChatMessages(),
                        )),
                        ChatInput(
                          focusNode: _focusNode,
                          thread: _thread!,
                          initialMessage: widget.initialMessage,
                          onSent: (_) {
                            // https://github.com/google/flutter.widgets/issues/287
                            Future.delayed(const Duration(milliseconds: 300),
                                () {
                              _scrollController.scrollTo(
                                index: 0,
                                duration: _scrollDuration,
                              );
                            });
                          },
                        ),
                      ],
                    ),
                  ),
                );
```

```dart
// ChatInput widget
          return SafeArea(
            child: Container(
              width: double.infinity,
              decoration: const BoxDecoration(
                  border:
                      Border(top: BorderSide(color: Colors.grey, width: 0.5)),
                  color: Colors.white),
              child: Row(
                children: <Widget>[
                  // Button send image
                  IconButton(
                    icon: const Icon(
                      Icons.image,
                      color: AppThemes.accentColor,
                    ),
                    onPressed: () {
                      _showAttachmentBottomSheet(isChattingToEachOther);
                    },
                  ),

                  // Edit text
                  Flexible(
                    child: TextField(
                      maxLines: null,
                      controller: _textController,
                      focusNode: widget.focusNode,
                      onSubmitted: (value) {
                        _sendTextMessage(
                          isChattingToEachOther: isChattingToEachOther,
                        );
                      },
                      decoration: InputDecoration.collapsed(
                        hintText: '$_i18nRoot.enter_text'.tr(),
                      ),
                    ),
                  ),

                  // Button send message
                  IconButton(
                      icon: const Icon(Icons.send),
                      color: AppThemes.accentColor,
                      onPressed: () {
                        _sendTextMessage(
                            isChattingToEachOther: isChattingToEachOther);
                      }),
                ],
              ),
            ),
          );
        });

```

</details>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.8.0-10.1.pre, on macOS 12.6.1 21G217 darwin-arm64,
    locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by exaby73** [comment] 2023-02-21 09:49
Hey @khaiql. Can you provide a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), ideally a single `main.dart` file that can be run directly? Also, can you reproduce this issue on Android or is it specific to iOS?

**Comment by khaiql** [comment] 2023-02-23 14:50
so this happens on Android, iOS and web. However when trying to pull the code out for a working example, I can't reproduce even though they have the same implementation, just one in a newly created flutter project and the other one is the main repo. I'm not sure how I can tell the difference or provide a working example because the codebase that has problem is quite large.

**Comment by khaiql** [comment] 2023-02-23 15:15
looks like it's because the ScreenUtils widget at the top, removing it fixed the issue.

**Comment by huycozy** [comment] 2023-02-28 10:31
Hi @khaiql 
Looks like the issue is caused by your implementation, I will close the issue from here. When you have this issue again, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may continue to verify the issue.
Thank you!

**Closed by huycozy** 2023-02-28 10:31 UTC
Labels: in triage
