### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function., errno = 1

### ISSUE THREAD

**Issue by homkoding** [flutter/flutter#121988] opened 2023-03-06 04:10 UTC
## Command
```
flutter build apk --split-per-abi
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1057:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:987:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1089:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1412:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1265], locale en-US)
    [32m•[39m Flutter version 3.7.3 on channel stable at c:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 9944297138 (4 weeks ago), 2023-02-08 15:46:04 -0800
    [32m•[39m Engine revision 248290d6d5
    [32m•[39m Dart version 2.19.2
    [32m•[39m DevTools version 2.20.1

[31m[✗][39m Windows Version (Exit status from running `systeminfo` was unsuccessful)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at C:\src\android_sdk
    [32m•[39m Platform android-33-ext4, build-tools 33.0.0
    [32m•[39m ANDROID_HOME = C:\src\android_sdk
    [32m•[39m ANDROID_SDK_ROOT = c:\src\android_sdk
    [32m•[39m Java binary at: C:\Program Files\Java\jdk-11\bin\java
    [32m•[39m Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.5)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.4.33403.182
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[33m[!][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m VS Code (version 1.76.0)
    [32m•[39m VS Code at C:\Users\lenov\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    [32m•[39m Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1265]
    [32m•[39m Chrome (web)                 • chrome        • web-javascript • Google Chrome 110.0.5481.104
    [32m•[39m Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.63

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b8f7f1f9869bb2d116aa6a70dbeac61000b52849
### Plugins
path_provider-2.0.13
path_provider_android-2.0.23
path_provider_foundation-2.1.2
path_provider_linux-2.1.9
path_provider_windows-2.1.4

**Comment by danagbemava-nc** [comment] 2023-03-06 10:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/66224

**Closed by danagbemava-nc** 2023-03-06 10:16 UTC
Labels: in triage
