### ISSUE TITLE
Create a development environment for testing using flutter-dashboard-dev

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#116791] opened 2022-12-09 19:04 UTC
We do not want to use the prod environment for testing as that can cause issues with developers work.

**Comment by CaseyHillers** [comment] 2022-12-09 19:17
Dupe of https://github.com/flutter/flutter/issues/60157

**Closed by CaseyHillers** 2022-12-09 19:17 UTC
Labels: team: infra

**Comment by ricardoamador** [comment] 2022-12-09 19:25
Oh, yeah we can close as duplicate.
