### ISSUE TITLE
Font issue & high memory usage (web canvas)

### ISSUE THREAD

**Issue by mzdm** [flutter/flutter#75970] opened 2021-02-13 15:00 UTC
## Describe the issue
After my app stopped responding I was really curious what was causing it (#75583) #75478

There seems to be some issue with font rendering (taking too long) and caching incrementally increases memory usage (only on Web Canvas). 
**300 MB initial memory usage up to 1GB** (sometimes can app stops responding due to out of memory)

It occurs since the Flutter version: 
- **1.26.0-17.2.pre (dev)** - memory usage up to 1 GB (on master as well - 1.27.0-2.0.pre.96)
- ( if running with `--web-renderer=html` memory usage max 100 MB ~)

Also notice that some characters are not rendered while on downgraded are.

But on version:
- 1.26.0-8.0.pre (dev) worked fine (memory usage max 80 - 100 MB ~)
- ( if running with `--web-renderer=html` memory usage max 100 MB ~)

[Sample video (master version)](https://streamable.com/j0gme6)
[Sample video (downgraded 1.26.0-8.0 dev version)](https://streamable.com/xflu9y)

## Steps to Reproduce

1. [Complete example repo](https://github.com/mzdm/font_rendering_error_example) or

add  `google_fonts: ^1.1.2` to pubspec.yaml and run this code via `flutter run -d chrome --release`:

<details>
  <summary>Steps to Reproduce</summary>

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {
  final fontsList = <String>[];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Test')),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            // 'fonts' or 'localFonts'
            for (final it in List.generate(12, (_) => 0))
              fontsList.addAll(fonts.split('\n'));

            Navigator.of(context).push(MaterialPageRoute(
              builder: (_) => FontsPage(fontsList: fontsList),
            ));
          },
          child: Text('Next Page'),
        ),
      ),
    );
  }
}

class FontsPage extends StatelessWidget {
  const FontsPage({
    Key key,
    @required this.fontsList,
  }) : super(key: key);

  final List<String> fontsList;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Scrollbar(
        child: ListView.separated(
          itemCount: fontsList.length,
          separatorBuilder: (_, __) => Divider(height: 40.0),
          itemBuilder: (_, index) {
            final isEven = index % 2 == 0;
            return Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                isEven ? 'přížíéščé č' : '订单, asdf',
                // if using 'localFonts' uncomment this:
                // style: TextStyle(
                //   fontFamily: fontsList[index],
                //   fontSize: 58.0,
                // ),
                style: GoogleFonts.getFont(fontsList[index]).copyWith(
                  fontSize: 58,
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

// Google Fonts
const fonts = """
Ubuntu
Titillium Web
Stalinist One
Source Sans Pro
Source Code Pro
Roboto Condensed
Roboto
PT Serif
PT Sans Narrow
PT Sans
Poppins
Oxygen
Open Sans
Nunito Sans
Nunito
Noto Serif
Noto Sans
Nanum Gothic
Mukta
Montserrat
Merriweather
Lobster
Libre Baskerville
Lexend Mega
Lexend Giga
Lato
Jomhuria
IBM Plex Sans
Hind Siliguri
Hanalei
Hammersmith One
Fjalla One
Fira Sans
Crimson Text
Big Shoulders Display
Bebas Neue
Barlow
Anton
Abel""";

// load fonts from assets without GoogleFonts lib
const localFonts = """
Ubuntu
TitilliumWeb
StalinistOne
SourceSansPro
SourceCodePro
Slabo27px
RobotoCondensed
Roboto
PTSerif
PTSansNarrow
PTSans
Poppins
Oxygen
OpenSans
NunitoSans
Nunito
NotoSerif
NotoSans
NanumGothic
Mukta
Montserrat
Merriweather
Lobster
LibreBaskerville
LexendMega
LexendGiga
Lato
Jomhuria
IBMPlexSans
HindSiliguri
Hanalei
HammersmithOne
FjallaOne
FiraSans
CrimsonText
BigShouldersDisplay
Benne
BebasNeue
Barlow
Anton
Abel
""";

```

</details>

Even though I use a package for it there was not any major change recently so don't think it is an issue with the package directly.

**Comment by TahaTesser** [comment] 2021-02-15 12:44
Hi @mzdm 
Thanks for filing, I can reproduce the issue 1.26 and even on 1.25 using canvaskit

### Canvaskit
![Screenshot 2021-02-15 175159](https://user-images.githubusercontent.com/48603081/107947629-a7835600-6fb8-11eb-9384-7be165b80059.png)


### HTML

![Screenshot 2021-02-15 175448](https://user-images.githubusercontent.com/48603081/107947633-a94d1980-6fb8-11eb-8a7e-9495bea956d9.png)


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.25.0-8.3.pre at C:\Users\Taha\Code\flutter
    • Framework revision 5d36f2e7f5 (5 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe
[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 84.0.522.52
• No issues found!
```
```bash
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.26.0-17.5.pre at C:\Users\Taha\Code\flutter_beta
    • Framework revision 1fe38dcb5f (5 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe
[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 84.0.522.52
• No issues found!
```

</details>

Looks like a duplicate of https://github.com/flutter/flutter/issues/66614
Not sure why you have no issue  `1.26.0-8.0.pre `, memory usage never under 100 for me 
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-15 12:44 UTC
