### ISSUE TITLE
Not an issue but a thank you

### ISSUE THREAD

**Issue by thejobsmarket** [flutter/flutter#151269] opened 2024-07-03 21:27 UTC
Whoever recently updated the readme with information on how to create your onw library, use state, args,… just two words: excellent job. Really helpful and well written.

**Comment by huycozy** [comment] 2024-07-04 06:02
Hi @thejobsmarket, I'm not sure which page you are referring to but I'm glad it's helpful to you. Closing this as it's not a bug or feature request.

**Closed by huycozy** 2024-07-04 06:02 UTC
Labels: in triage
