### ISSUE TITLE
 Socket.io connection problem

### ISSUE THREAD

**Issue by laurant94** [flutter/flutter#75382] opened 2021-02-04 01:52 UTC
##Socket.io connection problem

Hello community
I have a problem. I am developing a flutter application that communicates with a nodeJs server.

My flutter application manages to communicate with the server locally. But once I deploy my server on my hosting, flutter can no longer connect.

Can you help me please..
I am using the **flutter_socket_io: ^ 0.6.0** package

**Comment by pedromassangocode** [comment] 2021-02-04 08:35
Hi @laurant94 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/flutter/flutter/issues/75382).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-04 08:35 UTC
