### ISSUE TITLE
Disable vmservice RPC timeout when debugging

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7470] opened 2017-01-12 22:05 UTC
Our VM service RPCs have timeouts. They shouldn't when the user is debugging the Flutter application.

**Comment by johnmccutchan** [comment] 2017-01-17 15:34
I'm not a fan of putting policy in library code. The caller of the vm service rpc should decide what an appropriate timeout should be.

**Comment by Hixie** [comment] 2017-02-28 00:06
Dupe of https://github.com/flutter/flutter/issues/7310.

**Closed by Hixie** 2017-02-28 00:06 UTC
Labels: dev: tool
