### ISSUE TITLE
image_picker iOS opens camera instead of multipicker

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#85959] opened 2021-07-06 10:09 UTC
I noticed that on iOS real device prod build when trying to select multi images camera opens instead of gallery.

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1052], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.57.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-07-06 11:56
Hi @vytautas-pranskunas- 
Can you please provide your `flutter doctor -v` with verbose, a complete reproducible minimal code sample and iOS version which reproduces the issue
Thank you

**Comment by vytautas-pranskunas-** [comment] 2021-07-06 12:03
Hi, sure:here is minimal code:

```
IconButton(
              icon: Icon(Icons.photo_library),
              color: CustomColors.carePurple,
              onPressed: () async {
var files = await imagePicker.getMultiImage(maxWidth: 300, imageQuality: 90);
},
```


```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-CH)
    • Flutter version 2.2.2 at /Users/vytautaspranskunas/Desktop/Development/flutter
    • Framework revision d79295af24 (4 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vytautaspranskunas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                            • android-x86    • Android 11 (API
      30) (emulator)
    • iPhone (mobile)         • 5935f70317a32d4d30efb973538d730fab59c362 • ios            • iOS 12.5.4
    • iPhone 11 Pro (mobile)  • 5FFCAA1C-1C61-48D4-A4C6-7B4E79075B90     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome
      91.0.4472.114

• No issues found!
```

iOS version 12.5.4

**Comment by TahaTesser** [comment] 2021-07-07 11:09
Hi  @vytautas-pranskunas- 
This is not an issue since you're using  `iOS 12.5.4`, Multi-image picker requires iOS 14 and up. It is also [documented](https://pub.dev/packages/image_picker#ios) since it doesn't support it falls back to the camera which is first In `ImageSource`

Closing, as this isn't an issue with `image_picker` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-07 11:09 UTC
Labels: in triage

**Comment by vytautas-pranskunas-** [comment] 2021-07-07 11:29
Can we reduce OS requirements? Because required iOS version removes a lot of devices and i have to use https://pub.dev/packages/file_picker instead. But it would be nice to have one picker for all.
