### ISSUE TITLE
[Deep Link] iOS not getting initial route after first launch

### ISSUE THREAD

**Issue by jdbenito** [flutter/flutter#109165] opened 2022-08-08 17:21 UTC
I am working on an app with both deep and universal linking support.  We use Navigator 2 via the auto_route plugin.

In Android, **opening a deep link when the app is not launched** always triggers an initial route with the route specified in the deep link. iOS, unfortunately, does not do the same if it's starting from an unlaunched state.

According to the official [Flutter documentation](https://docs.flutter.dev/development/ui/navigation/deep-linking):
> #### iOS (not launched)
> App gets initialRoute (“/”) and a short time after uses the RouteInformationParser to parse the route and call RouterDelegate.setNewRoutePath, which configures the Navigator with the corresponding Page.

Am I misinterpreting these docs? Is the **actual** initial route pushed a short time after at all? 

=====
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.1 21C52 darwin-arm, locale en-CA)
    • Flutter version 3.0.5 at /Users/jdbenito/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jdbenito/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/jdbenito/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode13_4.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

**Comment by huycozy** [comment] 2022-08-09 08:03
Hi @jdbenito 
From what I can see, the issue is related to a 3rd party plugin (auto_route) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/Milad-Akarie/auto_route_library/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2022-08-09 08:03 UTC
Labels: in triage

**Comment by marvin-kolja** [comment] 2022-08-11 18:06
I figured out the issue. In our app we initialize some things before rendering the `WidgetsApp` widget. I used the routing example to create a minimal reproduciable code sample. The example doesn't make too much sense but it reflects the issue. 

<details>
  <summary>Bookstore example</summary>

```dart
class Bookstore extends StatefulWidget {
  const Bookstore({super.key});

  @override
  State<Bookstore> createState() => _BookstoreState();
}

class _BookstoreState extends State<Bookstore> {
  final _auth = BookstoreAuth();
  final _navigatorKey = GlobalKey<NavigatorState>();
  late final RouteState _routeState;
  late final SimpleRouterDelegate _routerDelegate;
  late final TemplateRouteParser _routeParser;
  late bool loading;

  @override
  void initState() {
    loading = true;

    // This function simulates some loading
    Future<void>.delayed(const Duration(seconds: 3)).then((_) {
      setState(() {
        loading = false;
      });
    });

    /// Configure the parser with all of the app's allowed path templates.
    _routeParser = TemplateRouteParser(
      allowedPaths: [
        '/signin',
        '/authors',
        '/settings',
        '/books/new',
        '/books/all',
        '/books/popular',
        '/book/:bookId',
        '/author/:authorId',
      ],
      guard: _guard,
      initialRoute: '/authors',
    );

    _routeState = RouteState(_routeParser);

    _routerDelegate = SimpleRouterDelegate(
      routeState: _routeState,
      navigatorKey: _navigatorKey,
      builder: (context) => BookstoreNavigator(
        navigatorKey: _navigatorKey,
      ),
    );

    // Listen for when the user logs out and display the signin screen.
    _auth.addListener(_handleAuthStateChanged);

    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    // In our app this looks a bit different but we are conditionally rendering the `WidgetsApp` widget.
    if (loading) {

      return const Center(
        child: CircularProgressIndicator(),
      );
    }

    return RouteStateScope(
      notifier: _routeState,
      child: BookstoreAuthScope(
        notifier: _auth,
        child: MaterialApp.router(
          routerDelegate: _routerDelegate,
          routeInformationParser: _routeParser,
          // Revert back to pre-Flutter-2.5 transition behavior:
          // https://github.com/flutter/flutter/issues/82053
          theme: ThemeData(
            pageTransitionsTheme: const PageTransitionsTheme(
              builders: {
                TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
                TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
                TargetPlatform.linux: FadeUpwardsPageTransitionsBuilder(),
                TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
                TargetPlatform.windows: FadeUpwardsPageTransitionsBuilder(),
              },
            ),
          ),
        ),
      ),
    );
  }
```
</details>

For clarification why we do it that way: Our `WidgetApp` requires state that is initialized async and needs the BuildContext. The `pushRoute` event is triggered but since the `WidgetApp` isn't rendered yet the `onGenerateRoute` isn't called. It seems to be some sort of timing issue since it works fine on Android. Here a quick look how we render the widgets:

<details>
    <summary>Our apps build method</summary>

```dart
  @override
  Widget build(BuildContext context) {
    return MietzProvider(
      child: HeroControllerScope(
        controller: HeroController(),
        child: Builder(
          builder: (context) {
            if (!loading && !loaded) {
              loading = true;
              load(context); // load async things
            }

            if (loading) return const LoadingView();

            // These providers are used inside `WidgetsApp` but must be initialized async (happens inside the load function)
            final analytics = AnalyticsProvider.of(context);
            final settingsProvider = SettingsProvider.of(context);
            localeChangeController.add(settingsProvider.locale);

            return WidgetsApp(
              localizationsDelegates: [
                !kDebugMode && ServerAppLocalizationDelegate.isAvailable
                    ? ServerAppLocalizationDelegate()
                    : S.delegate,
                GlobalWidgetsLocalizations.delegate,
                DateTimeFormattingLocalization.delegate,
                DefaultMaterialLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
                GlobalMaterialLocalizations.delegate,
                DefaultCupertinoLocalizations.delegate,
              ],
              supportedLocales: S.delegate.supportedLocales,
              locale: settingsProvider.locale,
              onGenerateRoute: generateRoute,
              navigatorObservers: [
                AnalyticsNavigatorObserver(analytics),
                routeObserver
              ],
              navigatorKey: navigationKey,
              debugShowCheckedModeBanner: false,
              builder: (context, child) {
                final themeVariant =
                    settingsProvider.theme.determineVariant(context);
                Widget content = AnimatedInheritedMietzTheme(
                  variant: themeVariant,
                  child: child ?? const SizedBox(),
                );

                if (!productionMode) {
                  final theme = MietzTheme.themes[themeVariant]!;
                  content = Banner(
                    message: 'Test mode',
                    location: BannerLocation.bottomStart,
                    color: theme.warning,
                    textStyle: theme.body2.copyWith(
                      fontSize: 11,
                      color: theme.onWarning,
                    ),
                    child: content,
                  );
                }

                return content;
              },
              color: MietzTheme.light.primary,
            );
          },
        ),
      ),
    );
  }
```
</details>

<details>
    <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-arm, locale en-DE)
    • Flutter version 3.0.5 at /Users/marvinwillms/fvm/versions/3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/marvinwillms/development/android_sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Users/marvinwillms/Library/Java/JavaVirtualMachines/azul-1.8.0_322/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.60.0.21-CA-macos-aarch64) (build 1.8.0_322-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Users/marvinwillms/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Users/marvinwillms/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.22/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Users/marvinwillms/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5591.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 12 mini (mobile) • FA5A666F-41A5-4934-ACCD-5B3F6C9E8229 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 104.0.5112.79
    ! Error: Marvin is not connected. Xcode will continue when Marvin is connected. (code -13)
    ! Error: Marvin is not connected. Xcode will continue when Marvin is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```
</details>

**Comment by huycozy** [comment] 2022-08-22 09:22
Hi @marvin-kolja, sorry for replying late. 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.
Thank you!

**Comment by huycozy** [comment] 2022-08-22 09:24
Hi @marvin-kolja, sorry for replying late. 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. 
In case you could provide a sample, please open a new issue so that we can investigate the issue properly from the beginning.
Thank you!
