### ISSUE TITLE
ColorScheme.background is not applied as scaffoldBackgroundColor when ThemeData.colorScheme is set

### ISSUE THREAD

**Issue by foxanna** [flutter/flutter#101389] opened 2022-04-05 22:14 UTC
## Steps to Reproduce

**Expected and Actual results:** see in the code example

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(ExampleApp());
}

// ✅ expected and actual result: Scaffold widget background is orange
class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        // is applied as Scaffold widget background
        scaffoldBackgroundColor: Colors.orange,    
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.green),
      ),
      home: Scaffold(body: Container()),
    );
  }
}

// ✅ expected and actual result: Scaffold widget background is dark
class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        // when ColorScheme is generated inside ThemeData constructor 
        // with ColorScheme.fromSeed(seedColor: colorSchemeSeed),
        // it's .background field is applied as Scaffold widget background
        colorSchemeSeed: Colors.green,
        brightness: Brightness.dark,    
      ),
      home: Scaffold(body: Container()),
    );
  }
}

// ❌ expected result: Scaffold widget background is orange
// ❌ actual result: Scaffold widget background is light
class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          // is not being applied as Scaffold widget background
          background: Colors.orange,  
        ),
      ),
      home: Scaffold(body: Container()),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.65.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```
</details>

The issue is reproducible in DartPad `Based on Flutter 2.10.4 Dart SDK 2.16.2`

**Comment by foxanna** [comment] 2022-04-05 22:20
I believe the problem is inside the `ThemeData` constructor. It has:
```dart
factory ThemeData({
  ...
  ColorScheme? colorScheme,
  Color? colorSchemeSeed,
  Color? scaffoldBackgroundColor,
  ...
}) {
  ...
  if (colorSchemeSeed != null) {
    colorScheme = ColorScheme.fromSeed(seedColor: colorSchemeSeed, brightness: _brightness);
    ...
    scaffoldBackgroundColor ??= colorScheme.background;
    ...
  }
  ...
  canvasColor ??= isDark ? Colors.grey[850]! : Colors.grey[50]!;
  scaffoldBackgroundColor ??= canvasColor;
}
```

The `scaffoldBackgroundColor` is updated from the generated `ColorScheme`, but not from the one passed to the `ThemeData` constructor.

**Comment by danagbemava-nc** [comment] 2022-04-06 09:11
Author's observations can be reproduced using the code samples provided above. Updated the sample to make it easier to test. 

Leaving this for further insight from the team. 


<details>
<summary>screenshots</summary>

| example 1 | example 2 | example 3 | 
| -- | -- | -- |
| <img width="505" alt="Screenshot 2022-04-06 at 08 17 01" src="https://user-images.githubusercontent.com/88313112/161937695-69025364-12e4-4baf-80c7-8e233530d13f.png"> | <img width="505" alt="Screenshot 2022-04-06 at 08 19 30" src="https://user-images.githubusercontent.com/88313112/161937976-6e8c21f5-15d0-43a3-858d-22985fd6417c.png"> | <img width="505" alt="Screenshot 2022-04-06 at 08 20 24" src="https://user-images.githubusercontent.com/88313112/161938066-82cdda7d-669f-4b34-b9aa-21a601e881f4.png"> | 

</details>

<details>
<summary>updated code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
   	runApp(const ExampleApp());
  // runApp(const ExampleApp1());
  // runApp(const ExampleApp2());
}

// ✅ expected and actual result: Scaffold widget background is orange
class ExampleApp extends StatelessWidget {
  const ExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ExampleApp',
      theme: ThemeData(
        // is applied as Scaffold widget background
        scaffoldBackgroundColor: Colors.orange,    
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.green),
      ),
      home: Scaffold(body: Container()),
    );
  }
}

// ✅ expected and actual result: Scaffold widget background is dark
class ExampleApp1 extends StatelessWidget {
  const ExampleApp1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        // when ColorScheme is generated inside ThemeData constructor 
        // with ColorScheme.fromSeed(seedColor: colorSchemeSeed),
        // it's .background field is applied as Scaffold widget background
        colorSchemeSeed: Colors.green,
        brightness: Brightness.dark,    
      ),
      home: Scaffold(body: Container()),
    );
  }
}

// ❌ expected result: Scaffold widget background is orange
// ❌ actual result: Scaffold widget background is light
class ExampleApp2 extends StatelessWidget {
  const ExampleApp2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          // is not being applied as Scaffold widget background
          background: Colors.orange,  
        ),
      ),
      home: Scaffold(body: Container()),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (12 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.391, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.391 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 08c46bcb58 (7 hours ago), 2022-04-05 22:24:05 -0400
    • Engine revision 45bedbe841
    • Dart version 2.17.0 (build 2.17.0-266.0.dev)
    • DevTools version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by johnpryan** [comment] 2022-04-14 20:26
I think the problem is that the [background](https://api.flutter.dev/flutter/material/ColorScheme/background.html) parameter doesn't control the background color of a Scaffold, so it looks to me like this is working as intended.

It _does_ control things like the background of a LinearProgressIndicator, for example:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(ExampleApp());
}

class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        scaffoldBackgroundColor: Colors.grey,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.red,
          background: Colors.pink.shade50,
        ),
        // colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        appBar: AppBar(),
        body: const Center(
          child: LinearProgressIndicator(),
        ),
      ),
    );
  }
}
```

**Comment by foxanna** [comment] 2022-04-15 07:30
@johnpryan, a few additional arguments to justify this issue, and why I believe currently this is not working as intended:

1. As a user of such API, I would be really surprised to find out there is no way to control `Scaffold.background` through `ColorScheme`. There has to be one, and looking at [Roles in a scheme](https://m3.material.io/styles/color/the-color-system/color-roles#55d2b7d2-0202-4616-887e-f575a7946aac) I cannot think of a better `colorScheme` property than `background`.

2. Comments in `ThemeData` constructor above the `colorScheme` parameter says:
```
    // [colorScheme] is the preferred way to configure colors. The other color
    // properties (as well as primaryColorBrightness, and primarySwatch)
    // will gradually be phased out, see https://github.com/flutter/flutter/issues/91772.
```

3. If the `colorScheme` gets generated inside `ThemeData` constructor, the `scaffoldBackgroundColor` value can be changed:
```dart
if (colorSchemeSeed != null) {
    colorScheme = ColorScheme.fromSeed(seedColor: colorSchemeSeed, brightness: _brightness);
    ...
    scaffoldBackgroundColor ??= colorScheme.background;
    ...
}
```
So there clearly was an intention to take the `colorScheme.background` value into account. I cannot think of a rationale behind such a distinction, whether the `colorScheme` was generated inside the `ThemeData` constructor or passed as its argument. The [suggested fix](https://github.com/flutter/flutter/pull/101419/files#diff-9d9b537da8ee2b1c3d29615749e838767109e585bd59cdbd4ac356e30f344505) by @TahaTesser makes total sense to me.

**Comment by foxanna** [comment] 2022-04-15 07:31
@johnpryan, I understand your argument about the background of `LinearProgressIndicator`. It means if this issue is fixed as suggested, its background color will not be visible on the `Scaffold` background color, because they will be the same. But, as a matter of fact, we might be looking at another bug here, because this is already happening if `ThemeData` is created with `colorSchemeSeed` parameter.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(ExampleApp());
}

class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        appBar: AppBar(),
        body: const Center(
          child: LinearProgressIndicator(),
        ),
      ),
    );
  }
}
```
</details>


<details>
<summary>Screenshot</summary>
<img width="476" alt="Screenshot 2022-04-15 at 10 28 30" src="https://user-images.githubusercontent.com/1845144/163539726-277a3e88-1acb-422a-a58a-7329bfe48864.png">
</details>

**Comment by TahaTesser** [comment] 2022-04-18 08:50
@johnpryan 

Scaffold takes background from `ThemeData` and it ignores themeing from the color scheme when `ThemeData. colorSchemeSeed` is null but the author is trying to create a color scheme with custom parameters so when using `ThemeData.colorsScheme` (instead of `ThemeData. colorSchemeSeed` as it looks a single color) to create a color scheme from seed with custom parameters but theme data ignores.

https://github.com/flutter/flutter/blob/f4875ae865e9d42644a93bbab2164fc7baac4ff7/packages/flutter/lib/src/material/scaffold.dart#L2835


`ColorScheme.background` should be relevant regardless of how the color scheme was created, `ThemeData.colorsScheme` not working but `ThemeData. colorSchemeSeed` works. 

You can test this by removing condition here

https://github.com/flutter/flutter/blob/f4875ae865e9d42644a93bbab2164fc7baac4ff7/packages/flutter/lib/src/material/theme_data.dart#L439

and overriding `scaffoldBackgroundColor` parameter here.

https://github.com/flutter/flutter/blob/f4875ae865e9d42644a93bbab2164fc7baac4ff7/packages/flutter/lib/src/material/theme_data.dart#L452

**Comment by TahaTesser** [comment] 2022-04-18 08:51
@foxanna 
I looked into this https://github.com/flutter/flutter/issues/101389#issuecomment-1099929097, the green color is the track color in your screenshot and if you override the color scheme background, the indicator background is updated, it looks like it is working as intended.

**Comment by johnpryan** [comment] 2022-04-18 18:11
@guidezpl could you take a look and let us know if this is working as intended?

**Comment by guidezpl** [comment] 2022-04-20 08:47
`Scaffold` is a Flutter-only concept but the color scheme comes directly from the design system, hence `Scaffold` doesn't use `ColorScheme.background`. Ultimately, the complete fix would be to deprecate `scaffoldBackgroundColor`, making its replacement `ScaffoldThemeData.background` (see with https://github.com/flutter/flutter/issues/91772,).

**Comment by foxanna** [comment] 2022-04-20 10:49
@guidezpl, thanks for the explanation!

If `Scaffold` should not use `ColorScheme.background`, does it mean that updating `scaffoldBackgroundColor` under `if` in a `ThemeData` constructor is a mistake then?
```dart
factory ThemeData({
  ...
  ColorScheme? colorScheme,
  Color? colorSchemeSeed,
  Color? scaffoldBackgroundColor,
  ...
}) {
  ...
  if (colorSchemeSeed != null) {
    colorScheme = ColorScheme.fromSeed(seedColor: colorSchemeSeed, brightness: _brightness);
    ...
    scaffoldBackgroundColor ??= colorScheme.background;
    ...
  }
  ...
  canvasColor ??= isDark ? Colors.grey[850]! : Colors.grey[50]!;
  scaffoldBackgroundColor ??= canvasColor;
}
```

**Comment by guidezpl** [comment] 2022-04-20 13:21
That was probably a reasonable default at the time. So long as it can be customised easily (constructor, `copyWith`), I think it's fine as is.

**Comment by guidezpl** [comment] 2023-01-26 13:42
Thanks for bringing this up @foxanna. Since this is working as intended, I'm going to close this issue. The very related solution to this problem is found in the deprecation of `scaffoldBackgroundColor` and in the introduction of `ScaffoldThemeData`, both of which I do in https://github.com/flutter/flutter/pull/116341. Please follow that PR and the linked issue for updates

**Closed by guidezpl** 2023-01-26 13:42 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 2.10, found in release: 2.13
