### ISSUE TITLE
Missing, tools after upgrade Flutter 2.2.1 .

### ISSUE THREAD

**Issue by DabPb** [flutter/flutter#83777] opened 2021-06-02 07:38 UTC
Android Studio 4.2.1 on Macbook Pro. Latest stable Flutter version. If I create a Flutter project It missing Database inspector, profiler, emulator window, AVD manager under View -> Tools Windows. And also Device File explorer is gone and I can't search my database adb file. Flutter doctor gives no error. Everything worked fine until the upgrade to flutter 2.2.1. how can I get those tools back? 
please find attachment for more reference.
Thank you.

<img width="1440" alt="before" src="https://user-images.githubusercontent.com/66239037/120442477-46369580-c3a3-11eb-91da-0cf41abd4f76.png">

<img width="1440" alt="updated" src="https://user-images.githubusercontent.com/66239037/120442501-4c2c7680-c3a3-11eb-92e5-c7a0895bbd89.png">

**Comment by TahaTesser** [comment] 2021-06-02 13:58
Hi @DabPb 
This is not an issue with Flutter itself,  still tested I can see the those tools

![image](https://user-images.githubusercontent.com/48603081/120493039-46df2400-c3c3-11eb-8867-1a15fee27100.png)

Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-02 13:58 UTC
Labels: in triage
