### ISSUE TITLE
How to get started on a Windows PC

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1437] opened 2016-01-28 19:20 UTC
_From @RobDolinMS on October 1, 2015 20:49_

I was looking at: http://flutter.io/getting-started/ and it lists how to get started on Mac and Linux, but not Windows.  

_Copied from original issue: flutter/website#15_

**Comment by FlutterIssues** [comment] 2016-01-28 19:20
_From @abarth on October 1, 2015 21:5_

Yes, we don't yet support Windows hosts yet.  It's something we want to support.  We just have a few tooling-related issues we want to take care of first (e.g., converting our tooling from Python to Dart).

**Comment by FlutterIssues** [comment] 2016-01-28 19:20
_From @RobDolinMS on October 1, 2015 21:12_

@abarth Thanks for the quick reply.  :)

**Comment by FlutterIssues** [comment] 2016-01-28 19:20
_From @abarth on October 24, 2015 3:31_

We're making progress on Windows support.  @TheBosZ was able to get a Flutter app running from a Window host today.  After that bakes for a while, we'll update the documentation to say how to use Windows.

**Comment by FlutterIssues** [comment] 2016-01-28 19:20
_From @RobDolinMS on November 13, 2015 22:31_

Thanks @abarth and @TheBosZ.  Do you have an ETA on when http://flutter.io/getting-started/ will be updated with Windows documentation.  I'd love to be a guinea pig.  :)

**Comment by FlutterIssues** [comment] 2016-01-28 19:20
_From @abarth on November 13, 2015 22:33_

The current blocking issue is that we need to build a binary for the host machine (in this case Windows) that produces the Dart snapshot that runs on the device.

**Comment by FlutterIssues** [comment] 2016-01-28 19:20
_From @TheBosZ on November 14, 2015 19:25_

@abarth What needs to happen to build the binary? I'd love to step in here and help out.

**Comment by FlutterIssues** [comment] 2016-01-28 19:20
_From @abarth on November 14, 2015 21:9_

I replied on IRC:

```
11:35 AM <abarth> TheBosZ: i'm not sure entirely what's involved
11:35 AM <abarth> the target is called "sky_snapshot"
11:35 AM <abarth> we currently build it on mac and linux
11:36 AM <abarth> it's built from the engine.git repo
11:36 AM <abarth> there are two parts (1) building it once and (2) building it every time we release the engine
```

**Comment by eseidelGoogle** [comment] 2016-10-27 12:59
I think this can be a dupe of https://github.com/flutter/flutter/issues/138.  We currently have no windows support, but do intend to build some soon.

**Closed by eseidelGoogle** 2016-10-27 12:59 UTC
Labels: ⚠ clear documentation
