### ISSUE TITLE
Flutter on MacOS catalina showing SDK and/or project is installed in a location that has  read/write permission

### ISSUE THREAD

**Issue by backslashflutter** [flutter/flutter#92961] opened 2021-11-03 06:15 UTC
First of all, i know people are asking this quesiton in flutter community a lot reagrding the flutter doctor command. But i have tried all the methods that are available online and cannot find anything that is working for me. 1. When i try to run the flutter doctor command, then i am shown with the particular error

## Steps to Reproduce

1. flutter doctor -v 
OR, 
2. flutter doctor also

## Logs

<details>
<summary>Logs</summary>

```
```

```
sudeepkulkarni@Sudeeps-MacBook-Air Developer % flutter doctor -v 
The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has
read/write permissions for the current user.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException
(package:flutter_tools/src/base/error_handling_io.dart:813:3)
#2      _handlePosixException
(package:flutter_tools/src/base/error_handling_io.dart:761:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:614:7)
#4      ErrorHandlingProcessManager.runSync
(package:flutter_tools/src/base/error_handling_io.dart:711:12)
#5      _DefaultProcessUtils.runSync
(package:flutter_tools/src/base/process.dart:373:51)
#6      AndroidStudio._init
(package:flutter_tools/src/android/android_studio.dart:462:39)
#7      new AndroidStudio
(package:flutter_tools/src/android/android_studio.dart:40:5)
#8      new AndroidStudio.fromMacOSBundle
(package:flutter_tools/src/android/android_studio.dart:94:12)
#9      AndroidStudio._allMacOS.<anonymous closure>
(package:flutter_tools/src/android/android_studio.dart:320:67)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#12     WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
#13     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#14     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#15     new List.of (dart:core-patch/array_patch.dart:50:28)
#16     Iterable.toList (dart:core/iterable.dart:388:12)
#17     AndroidStudio._allMacOS
(package:flutter_tools/src/android/android_studio.dart:322:10)
#18     AndroidStudio.allInstalled
(package:flutter_tools/src/android/android_studio.dart:251:34)
#19     AndroidStudio.latestValid
(package:flutter_tools/src/android/android_studio.dart:236:41)
#20     AppContext._generateIfNecessary.<anonymous closure>
(package:flutter_tools/src/base/context.dart:104:42)
#21     _LinkedHashMapMixin.putIfAbsent
(dart:collection-patch/compact_hash.dart:314:23)
#22     AppContext._generateIfNecessary
(package:flutter_tools/src/base/context.dart:92:20)
#23     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#24     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#25     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#26     androidStudio
(package:flutter_tools/src/globals_null_migrated.dart:54:45)
#27     runInContext.<anonymous closure>
(package:flutter_tools/src/context_runner.dart:104:32)
#28     AppContext._generateIfNecessary.<anonymous closure>
(package:flutter_tools/src/base/context.dart:104:42)
#29     _LinkedHashMapMixin.putIfAbsent
(dart:collection-patch/compact_hash.dart:314:23)
#30     AppContext._generateIfNecessary
(package:flutter_tools/src/base/context.dart:92:20)
#31     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#32     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#33     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#34     androidLicenseValidator
(package:flutter_tools/src/android/android_workflow.dart:28:65)
#35     DoctorCommand.runCommand
(package:flutter_tools/src/commands/doctor.dart:53:32)
#36     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1274:12)
<asynchronous suspension>
#37     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#39     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#40     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#41     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#42     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#43     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#44     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#45     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

</details>

**Comment by maheshmnj** [comment] 2021-11-03 07:48
Hi @backslashflutter, This issue looks like a duplicate of https://github.com/flutter/flutter/issues/70216. I would advise you to please follow up on that issue for further updates. 

As the description says this issue seems to be caused by the broken version of Android Studio. Please try installing some other version and see if that fixes the issue.

Closing in favor of the linked issue.

Thanks

**Closed by maheshmnj** 2021-11-03 07:48 UTC
Labels: in triage
