### ISSUE TITLE
[go_router] `.pushReplacement()` and `pushAndRemoveUntil()` equivalent

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#107052] opened 2022-07-04 07:55 UTC
## Use case

With navigator 1.0, we can use 2 methods:
- `.pushReplacement()`
- `pushAndRemoveUntil()`

Those where very useful, especially when the user is going through a wizard. The wizard could walk the user through different screens and those screens could be removed at the end of the wizard so the user cannot go back to them.

I didn't see any equivalent in GoRouter. Or maybe I missed them?

## Proposal

It would be useful to implement `.pushReplacement()` and `pushAndRemoveUntil()` equivalent.

**Comment by exaby73** [comment] 2022-07-04 12:04
Duplicate of https://github.com/flutter/flutter/issues/106402

**Closed by exaby73** 2022-07-04 12:04 UTC
Labels: in triage

**Comment by ValentinVignal** [comment] 2022-07-04 15:22
@exaby73 Actually, unlike the other issue, this one also includes `pushAndRemoveUntil()`. Do we want to keep it or modify the other issue?

**Comment by exaby73** [comment] 2022-07-05 06:39
Since it's very similar, maybe adding that to the original issue as a suggestion
