### ISSUE TITLE
Dart types/imports not canonicalized

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#419] opened 2015-11-17 05:51 UTC
As of `0.0.18` Flutter apps exhibit behavior described in https://github.com/dart-lang/sdk/issues/24942. It seems `flutter start` launches the Dart VM using [_file path_](https://github.com/flutter/flutter/blob/a0227cab15e230a564fb6316347b8e0ce3d21f6c/packages/flutter_tools/lib/src/commands/start.dart#L69) to `lib/main.dart` rather than _package path_.

https://github.com/dart-lang/sdk/issues/24942#issuecomment-157275671 shows how to solve the problem with standalone Dart VM.

**Comment by abarth** [comment] 2015-11-17 06:34
I haven't tested it, but there's a good chance this is fixed in 6e7f5759504fd367f5fc8af4d453563790feb2a1 , which is available in the most recent version of the flutter package.

We're no longer publishing package:flutter on pub.dartlang.org.  Instead, the getting started [1] instructions recommend that you clone the `alpha` branch of this repo and use the package directly with a path dependency.

[1] http://flutter.io/getting-started/

**Comment by yjbanov** [comment] 2015-11-17 06:53
Still reproducible in the alpha branch.

**Comment by abarth** [comment] 2015-11-17 07:27
Thanks.  I'll take a look.

**Comment by abarth** [comment] 2015-11-17 07:29
Ah, I see.  This is a different issue.  The current package is also symlinked into the packages directory, so it has two paths.

**Comment by abarth** [comment] 2015-11-17 07:36
Looks like there are three ways to fix this issue:

1. Switch to using the `.packages` file instead of the `packages` symlinks
2. Switch to using real paths when canonicalizing package names
3. Teach `flutter start` to use the package path for "main" instead of the file path

Option (3) isn't great because it's not clear how that interacts with the `-t` option.  We'd probably have to check whether the target from `-t` is in the `lib` directory of some package and rewrite the target to use the package path.

Option (1) is the most attractive because we need to switch to using `.packages` anyway.

Is this issue blocking you?  If not, I'd prefer to wait a bit and fix this issue by adopting `.packages` across Flutter.

**Comment by iposva-google** [comment] 2015-11-17 16:23
@abarth Option (1) will not solve the issue if you continue referring to the main entry point using a "file:" URI as package URIs will still have a different import URI than your original script.

**Comment by abarth** [comment] 2015-11-17 16:45
@iposva-google Isn't the relevant factor what our library tag handler returns for `Dart_kCanonicalizeUrl` ?  In Flutter's case, we support only file paths and canonicalize everything to an absolute file path.  With `.packages`, there will be only absolute file path for each library, which means very way of naming the library will canonicalize to the same string.

That doesn't work today because `lib/foo.dart` has two files paths, `/path/to/app/lib/foo.dart` and `/path/to/app/packages/app/foo.dart`, due to the symlinks in the `packages` directory.

**Comment by yjbanov** [comment] 2015-11-17 17:16
This is not blocking me. The workaround is: use `package:` imports everywhere.

**Comment by Hixie** [comment] 2016-01-17 06:14
Sounds like this is really a duplicate of https://github.com/flutter/flutter/issues/60.

**Comment by sethladd** [comment] 2016-09-14 17:19
#60 is closed. Going to close this one. Please reopen if required.

**Closed by sethladd** 2016-09-14 17:19 UTC
Labels: affects: dev experience, affects: tools, ⚠ bug
