### ISSUE TITLE
having problem setting up firebase

### ISSUE THREAD

**Issue by pandeyhitesh** [flutter/flutter#46798] opened 2019-12-11 18:58 UTC
> Running "flutter pub get" in dashboard...                       
> The current Flutter SDK version is 1.9.1+hotfix.6.
> 
> Because dashboard depends on firebase_auth >=0.15.1+1 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.

current SDK version is 1.9.1
firebase_auth >=0.15.1+1 which requires Flutter SDK version >=1.10.0 <2.0.0
SDK version in my `environment` is sdk: ">=2.1.0 <3.0.0"

here is my `.yaml` file 

>

>  version: 1.0.0+1
> 
> environment:
>   sdk: ">=2.1.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
>   percent_indicator: "^2.1.1"
>   firebase_core: ^0.4.3
>   firebase_auth: ^0.15.2
>   cloud_firestore: ^0.13.0+1
> 
>   cupertino_icons: ^0.1.2
>   font_awesome_flutter: ^8.1.2
> dev_dependencies:
>   flutter_test:
>     sdk: flutter

**Comment by iapicca** [comment] 2019-12-11 20:30
Hi @pandeyhitesh 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-11 20:30 UTC
