### ISSUE TITLE
New flutter app fails to build/run on iOS with `flutter run`

### ISSUE THREAD

**Issue by akesling** [flutter/flutter#84788] opened 2021-06-17 16:35 UTC
## Steps to Reproduce

1. Install XCode 12.5
2. Download Flutter 2.2.2 zip archive as recommended by https://flutter.dev/docs/get-started/install/macos.
3. Run flutter doctor and get everything into a "happy" state
4. Run `flutter create example`
5. Run `open -a Simulator`
6. Run `flutter run` and select the simulator

Note that `flutter run` selecting MacOS or Chrome works.  This specifically fails for iOS targets (whether the simulator or, if I configure certs correctly, a real iOS device).

## Logs

<details>
<summary>Logs</summary>

Full output (too long to include here) of `flutter run -v` with simulator selected using `-d [SIMULATOR_ID]`: https://gist.github.com/akesling/a260458120ac1004792482d006cd1a9e

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/akesling/flutter/flutter_2_2_2
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/akesling/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (4 available)
    • Alex’s iPad (mobile)                 • 00008027-000A25A42EEB002E            • ios            • iOS 14.6
    • iPod touch (7th generation) (mobile) • 53A1C165-4C6F-41C0-8DE3-489E969DB366 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)                      • macos                                • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 91.0.4472.106

! Doctor found issues in 1 category.
```

</details>

**Comment by akesling** [comment] 2021-06-17 18:26
I was led to file a new issue by https://github.com/flutter/flutter/issues/57940#issuecomment-760125210

**Comment by TahaTesser** [comment] 2021-06-18 08:27
Hi @akesling 
Thanks for filing the issue

 Look like the wrong SDK for targeted, it is getting `MacOSX.sdk` when building for the simulator.

  `[   +5 ms] Target debug_universal_framework failed: ProcessException: Process exited abnormally:                          ld: building for iOS Simulator, but linking in .tbd file (/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd) built for macOS/Mac Catalyst, file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64`


Fortunately, I cleaned MacBook with fresh Big Sur just yesterday and so I can confirm this isn't an issue even on a new setup. Based on reproducible steps, it doesn't reproduce and it looks like author is trying to run the app without modifying too. 


cc: @jmagman

**Comment by akesling** [comment] 2021-06-23 20:05
Do you have any hints/recommendations for next steps on how to fix this?

I'm trying to build a prototype to prove out whether Flutter will work for an iOS app we're working on... and I don't know how much further I should go with using Desktop/Android before actually trying this out on the target device.

I will note that I'm able to build regular iOS apps with no issue.  There's just something about Flutter that isn't working.

**Comment by akesling** [comment] 2021-06-23 20:38
With some further experimentation, it appears that adding `--release` allows me to run the example on an iPad w/ `flutter run`.  It reports that it is incompatible with the Simulator, however.

Further, I can build the debug version for iOS (both Simulator and iPad) directly via XCode.  I have not found a way to get a debug build running via `flutter run` on any device either virtual or physical.

I'm wondering if this line in the log is of importance:
```
(null) deviceType from 00008027-000A25A42EEB002E was NULL when -platform called.
```

I've found a few references around the web to people having similar problems with Flutter and other frameworks when this error is present.  Unclear if it's a red herring or not.  Perhaps the MacOS lib is being pulled in because it can't determine build platform by default?  How does the `flutter run --release` build differ that it would work where lacking `--release` fails?

**Comment by jmagman** [comment] 2021-06-23 21:02
@akesling Can you try on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels)?  I'm wondering if https://github.com/flutter/flutter/pull/84729 fixed this for you.

**Comment by jmagman** [comment] 2021-06-23 21:09
Also:
1. The logs you provided were from your simulator build, which may be fixed by https://github.com/flutter/flutter/pull/84729, but that wouldn't have impacted a physical build.  Can you attach your `flutter run -v` logs from trying on a physical device?  I want to check at what point `(null) deviceType from 00008027-000A25A42EEB002E was NULL when -platform called.` errors.
2. What model number is your iPad (Settings > General > About > Model Number)
3. Do you have an older physical device to try it on?

**Comment by akesling** [comment] 2021-06-28 15:45
Here is the output for `flutter run -v` when building for my iPad Pro w/ Flutter 2.2.2: https://gist.github.com/akesling/1eb4986dce15a897d1c03c4580cd0a29

I'll try building from master channel next.

**Comment by leechor** [comment] 2022-10-03 13:25
> I ran `flutter channel master` followed by `flutter upgrade`. Now my logs when trying to build for the Simulator look like: https://gist.github.com/akesling/b3ab977264d0a90dbf1f0a7414fe81d8
> 
> It appears that the error about a NULL deviceType is no longer there, but it's still trying to link in the MacOS libSystem.tbd.
> 
> Note, my output from `flutter upgrade` was:
> 
> ```
> Flutter 2.3.0-17.0.pre.540 • channel master • https://github.com/flutter/flutter.git
> Framework • revision d586873275 (5 minutes ago) • 2021-06-28 08:41:59 -0700
> Engine • revision 5d287a2061
> Tools • Dart 2.14.0

I have the same error, when use real iPhone device, how do you solve this link erorr problem? it has trouble me for a long time.

**Comment by jmagman** [comment] 2022-10-03 17:32
@leechor can you also attach your `flutter run -v` output?

**Comment by leechor** [comment] 2022-10-05 00:42
> @leechor can you also attach your `flutter run -v` output?

[https://github.com/flutter/flutter/issues/112797](My Question).
 [https://github.com/flutter/flutter/issues/112797#issuecomment-1265494589](I solved it temporarily)
But not know why.

**Comment by jmagman** [comment] 2024-02-08 22:51
Suspect this was leftover bug from adopting arm Macs.  If anyone is still seeing this, please file a new issue and completely fill out the template with a reproducible case.  Thanks!

**Closed by jmagman** 2024-02-08 22:51 UTC
Labels: c: crash, platform-ios, tool, a: first hour, P2, team-ios, triaged-ios, multiteam-retriage-candidate
