### ISSUE TITLE
Using Scrollbar to scroll throws `The Scrollbar's ScrollController has no ScrollPosition attached` error

### ISSUE THREAD

**Issue by KKStudios** [flutter/flutter#97873] opened 2022-02-05 17:07 UTC
Hey Flutter Team,

I just upgraded to the latest version on the Master channel and my List implementation suddenly throws errors at me on Windows which it didnt in the previous version I had.

So here is my very basic List implementation building items from a prototype I pass into the widget:

```dart

class KKListWidget<T> extends StatelessWidget{
  const KKListWidget({
    Key? key,
    required this.scrollController,
    required this.sourceList,
    this.searchResultList,
    required this.cardProtoType,
    required this.padding,
    this.onEntryClicked,
  }) : super(key: key);

  final ScrollController scrollController;
  final EdgeInsets padding;
  final List<T>? searchResultList;
  final List<T> sourceList;
  final ListCard<T> cardProtoType;
  final ValueChanged<T>? onEntryClicked;

  @override
  Widget build(BuildContext context) {
    return Expanded(
        child: Scrollbar(
          thumbVisibility: true,
          controller: scrollController,
          child: ListView.builder(
              controller: scrollController,
              itemCount: searchResultList == null ? sourceList.length : searchResultList!.length,
              padding: padding,
              itemBuilder: (context, index){
                Widget card = cardProtoType.fromPrototype(listItem: searchResultList == null ? sourceList[index] : searchResultList![index]);
                if(onEntryClicked != null){
                  return InkWell(onTap: () => onEntryClicked!(searchResultList == null ? sourceList[index] : searchResultList![index]), child: card);
                }
                return Padding(padding: const EdgeInsets.symmetric(horizontal: 8), child: card);
              }
          ),
        )
    );
  }
}

```

As you can see clearly, the scrollcontroller is the same for scrollbar and listview...
But still I'm getting the following error message when scrolling to fast on a large list:

```
The Scrollbar's ScrollController has no ScrollPosition attached.
A Scrollbar cannot be painted without a ScrollPosition.
The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to. When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1446:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1471:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1402:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#6      _rootRun (dart:async/zone.dart:1426:13)
#7      _CustomZone.run (dart:async/zone.dart:1328:19)
#8      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#9      _invoke (dart:ui/hooks.dart:151:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#11     _drawFrame (dart:ui/hooks.dart:115:31)`
```
For smallerish lists with a few hundred items it's no problem, as well as scrolling with the mousewheel so "slow mode".
But when I drag the scrollbar for a list of more than 1000 Items i get the error after the usual stuttering.

The behaviour ONLY appears in Debug mode! When building the application and executing the release version, all the problems are gone..

But still the error is a little annoying because it is caught by my custom errorhandler every time.

Here's what Dr Flutter says:

``` 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.11.0-0.0.pre.448, on Microsoft Windows [Version 10.0.19044.1466], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 2021.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by darshankawar** [comment] 2022-02-07 11:15
@KKStudios 
Can you provide complete minimal reproducible code sample ? I tried the one you shared but it' erroring out on `final ListCard<T> cardProtoType;`.

Also, are you running this on windows desktop and using mouse to scroll ?

**Comment by KKStudios** [comment] 2022-02-07 12:01
@darshankawar 
Thank you for coming back to this.

Yes platform where the error occurs is windows and as stated, the error only happens when scrolling using the scrollbar (so clicking the thumb and dragging it) at faster scroll rates with large lists.

For the minimal reproducible code sample I tried to replicate it by a simple ListView.builder with 5000 cards with numbers in it and the error strangely did not appear. I'm now rebuilding my implementation to find out if I can isolate the error somehow and reproduce it for you, so give me a day or two for that. 

But still the errormessage is nonsense because the listview and scrollbar do have the same scrollcontroller attached (As per required variable in constructor)

Cheers

**Comment by KKStudios** [comment] 2022-02-07 13:31
@darshankawar 

Ok so I could finally isolate the issue and found out the code i gave you above is perfectly fine.
The vertical Listview I showed above is creating Cards representing the Listobject. On one implementation of such a Card, it contains a horizontal Listview (which was not a problem before, but on latest master seems to be).

Here is the example to reproduce the bug:

```

import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Listview Bug Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Listview Bug Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class TestObject{

  TestObject(){
    int amount = Random().nextInt(10);

    for(int i = 0; i < amount; i++){
      testNumbers.add(i.toString());
    }
  }

  List<String> testNumbers = [];
}

class _MyHomePageState extends State<MyHomePage> {

  var testList = List.generate(5000, (index) => TestObject());
  var controller = ScrollController();

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Scrollbar(
        thumbVisibility: true,
        interactive: true,
        controller: controller,
        child: ListView.builder(
            controller: controller,
            itemCount: testList.length,
            itemBuilder: (c, i){
              return Card(
                child: SizedBox(
                  height: 100,
                  child: TestAvatarList(testList: testList[i].testNumbers),
                ),
              );
            }
        ),
      ),
    );
  }
}

class TestAvatarList extends StatefulWidget{
  const TestAvatarList({Key? key, required this.testList}) : super(key: key);

  final List<String> testList;

  @override
  _State createState() => _State();
}

class _State extends State<TestAvatarList>{

  final ScrollController _controller = ScrollController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 70,
      child: Scrollbar(
        controller: _controller,
        thumbVisibility: true,
        scrollbarOrientation: ScrollbarOrientation.bottom,
        child: Align(
          alignment: Alignment.center,
          child: ListView.builder(
              shrinkWrap: true,
              controller: _controller,
              scrollDirection: Axis.horizontal,
              itemCount: widget.testList.length,
              itemBuilder: (context, index){


                return Padding(
                  padding: const EdgeInsets.all(5.0),
                  child: CircleAvatar(
                    radius: 20,
                    child: Tooltip(
                        preferBelow: false,
                        message: widget.testList[index],
                        child: Text(widget.testList[index])
                    ),
                  ),
                );
              }
          ),
        ),
      ),
    );
  }
}

```

Now drag the thumb down a little faster on windows and voilà:

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to. When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1446:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1471:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1402:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#9      _invoke (dart:ui/hooks.dart:151:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#11     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

```

I hope this information is sufficient.

**Comment by darshankawar** [comment] 2022-02-08 07:02
@KKStudios 
This doesn't seem to be specific to windows platform, as I am able to see the same behavior running your code on mac and on mobile. Looking at the error in the console:

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to. When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.
```
Check [this](https://github.com/flutter/flutter/issues/82573) similar issue and [this](https://github.com/flutter/flutter/issues/82573#issuecomment-854942643) issue comment and see if it helps.

**Comment by KKStudios** [comment] 2022-02-08 10:40
@darshankawar 
I'm not quite sure using Scrollbehaviour is the solution to that problem. I tried wrapping the inner horizontal listview in it and it did work in terms of not throwing errors at me, however with Scrollbehaviour I did not find a way of displaying a Scrollbar that is always shown.

Here is the code I tried changing:

```

class TestAvatarList extends StatefulWidget{
  const TestAvatarList({Key? key, required this.testList}) : super(key: key);

  final List<String> testList;

  @override
  _State createState() => _State();
}

class _State extends State<TestAvatarList>{

  final ScrollController _controller = ScrollController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 70,
      child: const ScrollBehavior().buildScrollbar(context, _child, ScrollableDetails(direction: AxisDirection.down, controller: _controller)),
    );
  }

  Widget get _child => Align(
    alignment: Alignment.center,
    child: ListView.builder(
        shrinkWrap: true,
        controller: _controller,
        scrollDirection: Axis.horizontal,
        itemCount: widget.testList.length,
        itemBuilder: (context, index){


          return Padding(
            padding: const EdgeInsets.all(5.0),
            child: CircleAvatar(
              radius: 20,
              child: Tooltip(
                  preferBelow: false,
                  message: widget.testList[index],
                  child: Text(widget.testList[index])
              ),
            ),
          );
        }
    ),
  );
}
```

So that solution does not differ from just removing the Scrollbar Widget in the above code in terms of behaviour and outcome, but seems to worsen performance somehow.

What I'm trying to achieve is have a Vertical Scrollview with the Scrollbar always shown that has List items in it that have a horizontal scrollview with a scrollbar always shown. 
Without adding a scrollbar to the latter one to set thumbVisibility: true all is good.

And since I want my users to see that they can scroll horizontally here, I don't want to remove the scrollbar widget, or is there another way to have a scrollbar on the List that is always shown?

**Comment by darshankawar** [comment] 2022-02-09 05:51
Thanks for the update. On latest master and stable, using scrollbar to scroll throws below exception:

<details>
<summary> console error log </summary>

```

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to. When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1446:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1471:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1402:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#9      _invoke (dart:ui/hooks.dart:151:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#11     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

```

</details>

The error is thrown only when using the Scrollbar. If we scroll without it, there's no issue.

Similar / related: https://github.com/flutter/flutter/issues/82573

<details>
<summary> stable, master flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 2.10.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.0 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (7 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.11.0-0.0.pre.487, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.487 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3bdea6bb92 (44 minutes ago), 2022-02-08 20:11:08 -0800
    • Engine revision 7bf74069a5
    • Dart version 2.17.0 (build 2.17.0-87.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

/cc @Piinks

**Comment by Piinks** [comment] 2022-02-17 22:53
> however with Scrollbehaviour I did not find a way of displaying a Scrollbar that is always shown.

You can do this using ScrollbarTheme

**Comment by Piinks** [comment] 2022-02-17 22:57
I am looking into this, but also of note, on desktop platforms, the ScrollBehavior automatically applies a Scrollbar, so you may be experiencing duplicates since you are adding one manually on Windows.

**Comment by Piinks** [comment] 2022-02-17 23:02
> it did work in terms of not throwing errors at me, however with Scrollbehaviour I did not find a way of displaying a Scrollbar that is always shown.

I think this is your solution, you can either use themimg or create your own scrollbehavior to make it always shown

**Comment by KKStudios** [comment] 2022-02-21 11:32
Hey @Piinks, thank you for looking into it.

Ok so I'm not quite sure on how to apply that ScrollbarTheme here. I tried wraping the ListView.builder widget with the ScrollbarTheme widget and that doesn't change a thing. 

Then I tried wrapping the Scrollbehaviour.buildScrollbar widget with the ScrollbarTheme and that wont let me always show the thumb.

Also when I'm creating the horizontal Listview wihtout scrollbar or scrollbehaviour as parent, there is no scrollbar automatically added as far as I can see, as the view is neither scrollable by mousewheel, by dragging nor is there a thumb that comes up on hovering over so one can drag.

So here is what I tried:

Scrollbar shown, but not always shown, and no error:

```
class TestAvatarList extends StatefulWidget{
  const TestAvatarList({Key? key, required this.testList}) : super(key: key);

  final List<String> testList;

  @override
  _State createState() => _State();
}

class _State extends State<TestAvatarList>{

  final ScrollController _controller = ScrollController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ScrollbarTheme(
      data: ScrollbarTheme.of(context).copyWith(thumbVisibility: MaterialStateProperty.all(true)),
      child: SizedBox(
        height: 70,
        child: const ScrollBehavior().buildScrollbar(context, _child, ScrollableDetails(direction: AxisDirection.down, controller: _controller)),
      ),
    );
  }

  Widget get _child => Align(
    alignment: Alignment.center,
    child: ListView.builder(
        shrinkWrap: true,
        controller: _controller,
        scrollDirection: Axis.horizontal,
        itemCount: widget.testList.length,
        itemBuilder: (context, index){

          return Padding(
            padding: const EdgeInsets.all(5.0),
            child: CircleAvatar(
              radius: 20,
              child: Tooltip(
                  preferBelow: false,
                  message: widget.testList[index],
                  child: Text(widget.testList[index])
              ),
            ),
          );
        }
    ),
  );
}
``` 

No Scrollbar shown, and no visible scrollbehaviour:
```
class TestAvatarList extends StatefulWidget{
  const TestAvatarList({Key? key, required this.testList}) : super(key: key);

  final List<String> testList;

  @override
  _State createState() => _State();
}

class _State extends State<TestAvatarList>{

  final ScrollController _controller = ScrollController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 70,
      child: Align(
        alignment: Alignment.center,
        child: ScrollbarTheme(
          data: ScrollbarTheme.of(context).copyWith(thumbVisibility: MaterialStateProperty.all(true)),
          child: ListView.builder(
              shrinkWrap: true,
              controller: _controller,
              scrollDirection: Axis.horizontal,
              itemCount: widget.testList.length,
              itemBuilder: (context, index){

                return Padding(
                  padding: const EdgeInsets.all(5.0),
                  child: CircleAvatar(
                    radius: 20,
                    child: Tooltip(
                        preferBelow: false,
                        message: widget.testList[index],
                        child: Text(widget.testList[index])
                    ),
                  ),
                );
              }
          ),
        ),
      )
    );
  }
}
```

Maybe I did something wrong here?

**Comment by Piinks** [comment] 2022-02-22 19:54
I would recommend reading this migration guide that discusses all of these things: https://docs.flutter.dev/release/breaking-changes/default-desktop-scrollbars

Re: horizontal scroll views, in this case I do not think the scrollbar is applied. I would read the documentation for ScrollBehavior, along with the subclasses MaterialScrollBehavior and CupertinoScrollBehavior.

If the docs are missing helpful info, please let us know, we can always make our documentation better. :)

**Comment by KKStudios** [comment] 2022-02-23 11:16
@Piinks 
Ok thank you for the reference. I read the docs and tried for about an hour now to implement that but for the horizontal scroll.
No luck with that so far.

Here's what I did:

```

class TestAvatarList extends StatefulWidget{
  const TestAvatarList({Key? key, required this.testList}) : super(key: key);

  final List<String> testList;

  @override
  _State createState() => _State();
}

class _State extends State<TestAvatarList>{

  final ScrollController _controller = ScrollController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 70,
      child: Align(
        alignment: Alignment.center,
        child: ScrollConfiguration(
          behavior: HorizontalScrollBehaviour(),
          child: ListView.builder(
              shrinkWrap: true,
              controller: _controller,
              scrollDirection: Axis.horizontal,
              itemCount: widget.testList.length,
              itemBuilder: (context, index){

                return Padding(
                  padding: const EdgeInsets.all(5.0),
                  child: CircleAvatar(
                    radius: 20,
                    child: Tooltip(
                        preferBelow: false,
                        message: widget.testList[index],
                        child: Text(widget.testList[index])
                    ),
                  ),
                );
              }
          ),
        ),
      )
    );
  }
}

class HorizontalScrollBehaviour extends ScrollBehavior{

  @override
  Widget buildScrollbar(BuildContext context, Widget child, ScrollableDetails details) {
    return Scrollbar(child: child, controller: details.controller, thumbVisibility: true);
  }
}

```

The problem is, this throws errors because the scrollcontroller of the scrollbar and the scrollview below are not the same.

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to. When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1446:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1471:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1402:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#9      _invoke (dart:ui/hooks.dart:151:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#11     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
```

However neither when extending scrollconfiguration nor ScrollBehaviour classes, one can set the ScrollableDetails somewhere which tell the Scrollbar in the buildScrollbar function which controller to use.

I find this whole approach to just customizing a scrollbar or setting one for horizontal scrollviews rather complicated to be honest.

Before the latest version of flutter one could just set a Scrollbar as parent widget and done. That was a matter of seconds.
Maybe I'm missing something, but then again, why make it more complicated then before?

Cheers

**Comment by KKStudios** [comment] 2022-02-23 11:21
Oh and I also tried this:

```
class TestAvatarList extends StatefulWidget{
  const TestAvatarList({Key? key, required this.testList}) : super(key: key);

  final List<String> testList;

  @override
  _State createState() => _State();
}

class _State extends State<TestAvatarList>{

  final ScrollController _controller = ScrollController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 70,
      child: Align(
        alignment: Alignment.center,
        child: ScrollConfiguration(
          behavior: HorizontalScrollBehaviour(),
          child: HorizontalScrollBehaviour().buildScrollbar(context, scrollbar, ScrollableDetails(direction: AxisDirection.right, controller: _controller)),
        )
      )
    );
  }

  Widget get scrollbar => ListView.builder(
      shrinkWrap: true,
      controller: _controller,
      scrollDirection: Axis.horizontal,
      itemCount: widget.testList.length,
      itemBuilder: (context, index){

        return Padding(
          padding: const EdgeInsets.all(5.0),
          child: CircleAvatar(
            radius: 20,
            child: Tooltip(
                preferBelow: false,
                message: widget.testList[index],
                child: Text(widget.testList[index])
            ),
          ),
        );
      }
  );
}

class HorizontalScrollBehaviour extends MaterialScrollBehavior{
  
  @override
  Widget buildScrollbar(BuildContext context, Widget child, ScrollableDetails details) {
    return Scrollbar(child: child, controller: details.controller, thumbVisibility: true);
  }
}
```

Still throws that error:

```
======= Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition. 

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to. When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1446:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1471:6)
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1402:14)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#9      _invoke (dart:ui/hooks.dart:151:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#11     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```

**Comment by zeevgrim** [comment] 2022-03-20 22:15
same issue with Flutter web project. 
Does anyone find out how to solve this one?

**Comment by ali-1989** [comment] 2022-04-02 02:57
same issue with Flutter web project. 2022/3

**Comment by AndriiHarashchak** [comment] 2022-04-03 17:32
I have the same issue on the latest master version 2.10.4. But in my case, I use only list view and no other scrollable widgets.  But one interesting thing is that this exception occurs not every time. Sometimes it not occur and sometimes it occurs a few times during one widget with list rendering. Here is console message:
`════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
The Scrollbar's ScrollController has no ScrollPosition attached.

A Scrollbar cannot be painted without a ScrollPosition.

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to. When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

When the exception was thrown, this was the stack
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1300
#1      RawScrollbarState._debugCheckHasValidScrollPosition
package:flutter/…/widgets/scrollbar.dart:1325
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1258
#3      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
#4      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1089
#5      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:995
#9      _invoke (dart:ui/hooks.dart:151:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#11     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)`

**Comment by Piinks** [comment] 2022-04-05 18:29
@zeevgrim @ali-1989 @AndriiHarashchak can you please file issues with runnable reproductions that are giving you this error? I believe this error can present itself from different root causes and I and looking into it. Each of your cases may be different, and there is currently no way to diagnose without a reproduction.

The PrimaryScrollController may be causing some of these issues, please see https://github.com/flutter/flutter/issues/100264

**Comment by didifend** [comment] 2022-06-06 04:27
I just added a controller like this to fix this issue,

```
SingleChildScrollView(
     controller: ScrollController(),
     .....
)
```

**Comment by UlyssesAlves** [comment] 2022-06-06 20:37
It works for me when I set the same ScrollController for both my ListView and ScrollBar.

**Comment by martinpelli** [comment] 2022-09-28 11:55
In flutter web, with pageview there is no fix. 

```
Scrollbar(
                controller: pageController,
                thumbVisibility: true,
                child: PageView(
                  controller: pageController,
                  pageSnapping: false,
                  scrollDirection: Axis.vertical))

```
> The provided ScrollController is currently attached to more than one ScrollPosition.
> The Scrollbar requires a single ScrollPosition in order to be painted.
> When Scrollbar.thumbVisibility is true, the associated ScrollController must only have one
> ScrollPosition attached.The provided ScrollController must be unique to one ScrollView widget.

If you remove the controller from the ScrollBar

```
 Scrollbar(
                thumbVisibility: true,
                child: PageView(
                  controller: pageController,
                  pageSnapping: false,
                  scrollDirection: Axis.vertical))
```

> The Scrollbar's ScrollController has no ScrollPosition attached.
> A Scrollbar cannot be painted without a ScrollPosition.
> The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be
> associated with the ScrollView that the Scrollbar is being applied to.A ScrollView with an
> Axis.vertical ScrollDirection on mobile platforms will automatically use the PrimaryScrollController
> if the user has not provided a ScrollController. To use the PrimaryScrollController explicitly, set
> ScrollView.primary to true for the Scrollable widget.

if you remove the controller from the PageView

```
 Scrollbar(
                thumbVisibility: true,
                controller: pageController,
                child: PageView(
                  pageSnapping: false,
                  scrollDirection: Axis.vertical))
```

> The Scrollbar's ScrollController has no ScrollPosition attached.
> A Scrollbar cannot be painted without a ScrollPosition.
> The Scrollbar attempted to use the provided ScrollController. This ScrollController should be
> associated with the ScrollView that the Scrollbar is being applied to.When providing your own
> ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

**Comment by bitinerant** [comment] 2022-10-08 16:36
https://stackoverflow.com/a/71490688 solved this issue for me on Linux, Flutter 3.3.4.

**Comment by Dampfwalze** [comment] 2023-02-15 10:18
When you want to use the `PrimaryScrollController` of the current context, the behavior is platform specific:

When the controller property of the `Scrollbar` is absent, it will use the `PrimaryScrollController` (Not platform specific).
From the docstring:
> If the [controller] is null, the default behavior is to enable scrollbar dragging using the [PrimaryScrollController].

A `ScrollView` on the other hand, tries to adapt to the platform if its behavior is undefined by the user. These lines determine the used controller of a ScrollView:

https://github.com/flutter/flutter/blob/31c73fcfebf4a9a58688055d24030f9bb3547f9b/packages/flutter/lib/src/widgets/scroll_view.dart#L410-L415

https://github.com/flutter/flutter/blob/31c73fcfebf4a9a58688055d24030f9bb3547f9b/packages/flutter/lib/src/widgets/primary_scroll_controller.dart#L100-L123

To fix this, you could just set the `primary` parameter on the `ScrollView` to `true`:

```dart
Scrollbar(
  child: ListView(
    primary: true,
    children: [
      ...
    ],
  ),
),
```

**Comment by Piinks** [comment] 2023-02-23 17:24
I am going to close this issue as since the last update we have landed many updates to documentation, guides on the website, videos on youtube, and several fixes to scrollbar theming. AFAICT, the issue described here is resolved, but if we missed something, please file a new issue with a code sample to reproduce it and the output of flutter doctor. Thanks all!

**Closed by Piinks** 2023-02-23 17:24 UTC
Labels: framework, f: material design, f: scrolling, d: api docs, d: examples, d: stackoverflow, documentation, a: error message, has reproducible steps, found in release: 2.10, found in release: 2.11
