### ISSUE TITLE
Error when loading large network images on Android.

### ISSUE THREAD

**Issue by bibekpanda55** [flutter/flutter#135296] opened 2023-09-22 11:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Store any large image file (more than 50 mb) in Firebase Storage.
2. Use Image.network() or CachedNetworkImage etc to display the image url in physical Android device.
3.Link to the images:
NetworkImage("https://firebasestorage.googleapis.com/v0/b/dna-club-f8bb8.appspot.com/o/events%2FMAIN.png1694108565150?alt=media&token=fa7d4db8-981d-4a79-bc91-77596352cb1c", scale: 0.5)
Image key: NetworkImage("https://firebasestorage.googleapis.com/v0/b/dna-club-f8bb8.appspot.com/o/events%2FMAIN.png1694108565150?alt=media&token=fa7d4db8-981d-4a79-bc91-77596352cb1c", scale: 0.5)

### Expected results

The image should be displayed when the url is passed to above Image.network constructor,but instead it shows the above error.

### Actual results

I am getting the error Exception caught by image resource service. Instead of the image it's showing "Exception Invalid Image Data". But on changing the image to JPG format using the [image](https://pub.dev/packages/image) package and then showing it using Image.memory() works. Someone suggested me that PNG decoder in Android doesn't work. I just want to know the exact issue behind this.  

### Code sample

<details><summary>Code sample</summary>

```dart
 Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 10),
            width: double.infinity,
            height: 300.0,
            decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(10.0),
                image: DecorationImage(
                    fit: BoxFit.fill,
                    // colorFilter: ColorFilter.mode(
                    //     Colors.black.withOpacity(0.7), BlendMode.dstATop),
                    image: CachedNetworkImageProvider(
                      imageUrl,
                    ))),
          ),
//Here imageUrl is the Firebase Storage imageUrl that I am getting for each image file .
final data =
          await _storage.ref("coverImage").child(imagePath).getDownloadURL();
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
![error](https://github.com/flutter/flutter/assets/53937166/5a410e45-d02d-48cb-a99b-5af4e31fbbe0)

![error 1](https://github.com/flutter/flutter/assets/53937166/cfde5e13-0a9c-4c91-bb61-4720fb4f773b)

</details>

- [ ] 

### Logs

<details><summary>Logs</summary>

```console
Exception caught by image resource service ════════════════════════════
Exception: Invalid image data
════════════════════════════════════════════════════════════════════════════════
E/FlutterJNI(18810): Failed to decode image
E/FlutterJNI(18810): android.graphics.ImageDecoder$DecodeException: Input was incomplete.
E/FlutterJNI(18810):     at android.graphics.ImageDecoder.nCreate(Native Method)
E/FlutterJNI(18810):     at android.graphics.ImageDecoder.-$$Nest$smnCreate(Unknown Source:0)
E/FlutterJNI(18810):     at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:248)
E/FlutterJNI(18810):     at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1896)
E/FlutterJNI(18810):     at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1889)
E/FlutterJNI(18810):     at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:554)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

 Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale
    en-IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] Network resources

```

</details>

**Comment by darshankawar** [comment] 2023-09-22 13:07
> I just want to know the exact issue behind this.

@bibekpanda55 I think your question / query is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this looks like a code implementation or third party package issue. See https://github.com/flutter/flutter/issues/132184#issuecomment-1672338002 for reference.

If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-09-22 13:07 UTC
Labels: in triage

**Comment by bibekpanda55** [comment] 2023-09-22 14:51
Actually, it's a flutter issue as far as I tested it. As my code implementation was correct and also there isn't any dependency on any third party package. The issue is mostly related to how Flutter manages to decode large file after fetching it from network on Android devices. It might be for only PNG image file type but I am not sure of that. But it's not code implementation or third party package issue that I am sure of.

**Comment by darshankawar** [comment] 2023-09-25 05:33
Thanks for the feedback. Can you provide us a runnable reproducible code sample preferably without using any third party package code, with which the reported error still occurs ?
