### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by Clasender** [flutter/flutter#102286] opened 2022-04-21 08:14 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1892:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1436:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
#14     _rootRunUnary (dart:async/zone.dart:1444:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#20     _StreamController._add (dart:async/stream_controller.dart:607:7)
#21     _StreamController.add (dart:async/stream_controller.dart:554:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1702:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.3 21E230 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/smart/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/smart/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.3, Build version 13E113
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • iPhone SE (3rd generation) (mobile) • 05EFD03E-15C9-49E8-860D-808407AB121B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 100.0.4896.127

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.4.9
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
Alipay_kit
basechannellib-1.0.1
better_socket-1.1.4
camera-0.9.2+2
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info-2.0.3
flutter_bugly-0.4.4
flutter_full_pdf_viewer
flutter_local_notifications-5.0.0+4
flutter_plugin_android_lifecycle-2.0.5
flutter_ringtone_player-3.1.1
flutter_webview_plugin-0.3.12+6
fluttertoast-8.0.9
im_flutter_sdk
image_cropper-1.4.0
image_picker-0.8.5
image_picker_android-0.8.4+11
image_picker_for_web-2.1.6
image_picker_ios-0.8.4+11
install_plugin-2.0.1
jpush_flutter-2.2.4
flutter_location
native_screenshot-1.0.0
ngr_base_lib
ngr_channel_lib
ngr_path_provider
ngr_work_standard
ngr_video_flutter
package_info-0.4.3+4
path_provider_linux-2.1.5
path_provider_windows-2.0.5
permission_handler-6.0.1+1
qr_code_scanner-202320ff4c883670736fed466271801fe743afb3
shared_preferences-2.0.7
shared_preferences_linux-2.0.4
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.3
shared_preferences_windows-2.0.4
sign_in_with_apple-3.3.0
sign_in_with_apple_web-1.0.1
tencent_rtc_plugin-0.1.13
url_launcher-6.0.10
url_launcher_linux-2.0.3
url_launcher_macos-2.0.3
url_launcher_web-2.0.7
url_launcher_windows-2.0.2
ngr_wakelock
wakelock_macos-0.4.0
wakelock_web-0.4.0
wechat_kit
zz_face_verify

**Comment by danagbemava-nc** [comment] 2022-04-21 08:47
Closing as duplicate of #81666

**Closed by danagbemava-nc** 2022-04-21 08:47 UTC
Labels: in triage
