### ISSUE TITLE
[Web] Right click after text selection in TextField selects single word

### ISSUE THREAD

**Issue by ConcenTech** [flutter/flutter#79592] opened 2021-04-01 21:51 UTC
## Steps to Reproduce

1. Run example
2. Select text from left to right and right click
3. Select text from right to left and right click

**Expected results:** 
Right click on selection will allow me to copy selected text.

**Actual results:** 
If selecting from right to left, once I right click, the selection changes to the word the mouse was over.
Selecting from left to right seems to show the appropriate behaviour.

<details>
  <summary>Doctor</summary>

```
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.870], locale en-GB)
    • Flutter version 2.1.0-12.2.pre at C:\src\flutter
    • Framework revision 5bedb7b1d5 (2 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\kgcar\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\kgcar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```
</details>

<details>
<summary>Example</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
            child: TextFormField(
          initialValue:
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam gravida turpis eget congue suscipit. Nulla vitae faucibus nisl. Pellentesque dapibus magna ante, ut malesuada libero pellentesque sit amet. In hac habitasse platea dictumst. Sed tellus dui, dictum at ex sed, bibendum faucibus metus. Integer ornare a mi nec egestas. Quisque id commodo metus. Etiam at lorem vel ex varius imperdiet in nec enim.',
          maxLines: 5,
          minLines: 1,
        )),
      ),
    );
  }
}

```

</details>

<details>
<summary>GIF</summary>

![github](https://user-images.githubusercontent.com/70274454/113357934-c22d4680-933c-11eb-8ddf-89debfe37392.gif)

</details

**Comment by nt4f04uNd** [comment] 2021-04-02 10:35
duplicate of https://github.com/flutter/flutter/issues/79157

**Comment by ConcenTech** [comment] 2021-04-02 11:20
I did see that issue before I opened this but, although similar, it's not the same. 

Different widgets, context menus work fine. 
Referenced issue doesn't mention direction of selection.

**Comment by TahaTesser** [comment] 2021-04-05 10:25
Hi @ConcenTech 
@nt4f04uNd is correct, this is a duplicate, TextField uses same `TextSelectionGestureDetectorBuilderDelegate` as `SelectableText` does. 

`class _TextFieldState extends State<TextField> with RestorationMixin implements TextSelectionGestureDetectorBuilderDelegate {`

`class _SelectableTextState extends State<SelectableText> with AutomaticKeepAliveClientMixin implements TextSelectionGestureDetectorBuilderDelegate {`

Correct  me if I am mistaken


Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/79157
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-05 10:25 UTC
Labels: in triage

**Comment by ludwiktrammer** [comment] 2021-04-10 09:51
I don't believe it's an duplicate. This issue is about different secondary-click behavior depending on whether the selection was performed from right-to-left or from left-to-right. The same issue was also reported in #80119. I proposed a Pull Request fixing it in #80186.

On the other hand #79157 is a completely different issue (which questions how the secondary-clicks whiting selectable widgets should behave in general).
