### ISSUE TITLE
Is the duplicate libflutter.so in android-x86/artifacts.zip redundant?

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#94667] opened 2021-12-04 15:42 UTC
The libflutter.so is already zipped in flutter.jar in artifacts.zip. But I found another same outside libflutter.so in android-x86's artifacts.zip and android-x64's artifacts.zip. It wastes about 2*10MB+ (after zipped) in every version of flutter engine's artifacts. 

![image](https://user-images.githubusercontent.com/922837/144715470-5a47c53e-b97d-46a7-810c-7408e572d02c.png)

![image](https://user-images.githubusercontent.com/922837/144715665-e2a136fb-f128-4ae0-a25d-00cae641daf1.png)

![image](https://user-images.githubusercontent.com/922837/144715987-d1c7cad7-a541-4180-affb-a691179f7a95.png)

This gn code stores the extra libflutter.so, let's check whether it is still used or not? And is it safe to remove it? @dnfield 😄

https://github.com/flutter/engine/blob/93f3991842fb18574aeb8e567376b02ad48fc331/shell/platform/android/BUILD.gn#L539
```gn
  if (current_cpu == "x86" || current_cpu == "x64") {
    files += [
      {
        source = "$root_build_dir/lib.stripped/libflutter.so"
        destination = "libflutter.so"
      },
    ]
    deps += [ ":flutter_shell_native" ]
  }
```
The `flutter_jar_zip` depends on `android_jar`, and the `flutter_shell_native` is already in deps of `android_jar` target. So I think they can be removed.

```gn
action("android_jar") {
  script = "//build/android/gyp/create_flutter_jar.py"
  # etc...

  deps = [
    ":flutter_shell_java",
    ":flutter_shell_native", # <--- here
    ":pom_embedding",
    ":pom_libflutter",
  ]
```

Related: 
* https://github.com/flutter/engine/pull/13059
* https://github.com/flutter/flutter/issues/42140

**Comment by dnfield** [comment] 2021-12-04 16:16
I believe this is used by Google's build system internally.

**Comment by dnfield** [comment] 2021-12-04 16:16
@xster do you know?

**Comment by eggfly** [comment] 2021-12-04 16:23
I filed https://github.com/flutter/engine/pull/30130 for a test, let CI build system to have check.

**Comment by dnfield** [comment] 2021-12-04 16:51
Unfortunately this wouldn't get caught until a later process in the roll to the framework and Google's internal repo

**Comment by chinmaygarde** [comment] 2021-12-06 19:15
For now, this is working as intended and is necessary. We can keep this issue open to track removing the internal dependency. @dnfield Is there an issue filed for this internally?

**Comment by dnfield** [comment] 2021-12-07 00:48
I'm not even really sure if it's used internally, or why this was only done for x86/x64 exclusively. Maybe an emulator thing? 

It looks like this was introduded in https://chromium.googlesource.com/chromium/tools/build.git/+/50473c9737b3f8c4c82425c08be0cec018e345e8 by @jason-simmons and @cbracken. Any chance either of you remember why this was done?

**Comment by dnfield** [comment] 2021-12-07 00:50
I can't find evidence that this is used internally, and I can't find evidence that it's used in the tool either. The linked change won't do enough to fix it because it's still the recipe driving this decision. It might be fine to just change it and see what breaks...?

**Comment by jason-simmons** [comment] 2021-12-07 01:40
I think the extra copy of `libflutter.so` is obsolete.

IIRC `libflutter.so` was published as a separate artifact for use by an older version of the flutter_tools APK builder.  However, the current builder uses a Maven repository to obtain `flutter.jar` and `libflutter.so` binaries.

I don't think the `bin/cache/artifacts/engine/android-{x86,x64}/libflutter.so` binaries are used anywhere.  It looks like they are only downloaded if you do a `flutter precache -a`. 
 They will not be downloaded on demand when building an APK.

The engine build script change in https://github.com/flutter/engine/pull/30130 already landed as part of https://github.com/flutter/engine/commit/68d320d449733db02d6109c28973a58552297e26.  So far it looks like that has not caused any issues.

To remove the extra `libflutter.so` from the uploaded artifacts we should remove this from the recipe:
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine.py#714

**Comment by jason-simmons** [comment] 2021-12-09 00:02
Fixed by https://flutter.googlesource.com/recipes/+/b460186d5bac1a775cb4b557f4f97c0f53bac425

**Closed by jason-simmons** 2021-12-09 00:02 UTC
Labels: team, platform-android, engine, passed first triage, P5
