### ISSUE TITLE
Problem taking a .toImage() screenshot of a widget that contains the CameraPreview.

### ISSUE THREAD

**Issue by eduardkieser** [flutter/flutter#18989] opened 2018-07-02 11:50 UTC
## Steps to Reproduce

1. Create a widget that contains a CameraPreview.
2. Try to take a screenshot using this method: https://docs.flutter.io/flutter/rendering/RenderRepaintBoundary/toImage.html
3. I made a small demo app that can be found at: https://gist.github.com/eduardkieser/ffea183945d56f537d789888008cbc4e (You can move the blue square around)
4. Short video here: https://www.youtube.com/watch?v=CWBLjCwH5c0

Expected Behaviour: That the screenshot should include the CameraPreview.
Actual behaviour: The screenshot contains painted widgets, but no Camera data.

## Logs

```
Performing hot restart...
[+7732 ms] Refreshing active FlutterViews before restarting.
[        ] _flutter.listViews: {isolateId: isolates/301279252}
[ +405 ms] DevFS: Starting sync from LocalDirectory: 'C:\Users\Eduard\Google Drive\WorkSpaces\flutter\widget_paint_test'
[        ] Scanning project files
[        ] Scanning package files
[  +45 ms] Scanning asset files
[        ] Scanning for deleted files
[  +22 ms] Compiling dart to kernel with 0 updated files
[ +190 ms] Updating files
[ +603 ms] DevFS: Sync finished
[        ] Synced 0.0MB.
[        ] getIsolate: {isolateId: isolates/301279252}
[  +44 ms] _flutter.runInView: {viewId: _flutterView/0x725824b498, mainScript: /data/user/0/com.kieserengineering.widgetpainttest/cache/widget_paint_testEDMOVU/widget_paint_test/lib/bugExample.dart.dill, packagesFile: /data/user/0/com.kieserengineering.widgetpainttest/cache/widget_paint_testEDMOVU/widget_paint_test/.packages, assetDirectory: /data/user/0/com.kieserengineering.widgetpainttest/cache/widget_paint_testEDMOVU/widget_paint_test/build/flutter_assets}
[ +595 ms] {streamId: Isolate, event: {type: Event, kind: IsolateStart, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531814327}}
[   +3 ms] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531814332, extensionRPC: ext.ui.window.scheduleFrame}}
[   +1 ms] getIsolate: {isolateId: isolates/513879693}
[   +2 ms] {streamId: Isolate, event: {type: Event, kind: IsolateExit, isolate: {type: @Isolate, fixedId: true, id: isolates/301279252, name: main.dart:main(), number: 301279252}, timestamp: 1530531814348}}
[        ] {streamId: Isolate, event: {type: Event, kind: IsolateRunnable, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531814611}}
[        ] Isolate is runnable.
[        ] _flutter.listViews: {isolateId: isolates/513879693}
[  +61 ms] Restart performed in 1 952ms.
[   +3 ms] Restarted app in 1 987ms.
[ +381 ms] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815095, extensionRPC: ext.flutter.reassemble}}
[   +2 ms] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815095, extensionRPC: ext.flutter.exit}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815095, extensionRPC: ext.flutter.frameworkPresent}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815095, extensionRPC: ext.flutter.platformOverride}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815096, extensionRPC: ext.flutter.evict}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815096, extensionRPC: ext.flutter.timeDilation}}
[   +1 ms] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.debugPaint}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.debugPaintBaselinesEnabled}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.repaintRainbow}}
[   +2 ms] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.debugDumpRenderTree}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.debugDumpLayerTree}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.debugDumpSemanticsTreeInTraversalOrder}}
[   +2 ms] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.debugDumpSemanticsTreeInInverseHitTestOrder}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.debugDumpApp}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.showPerformanceOverlay}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.debugAllowBanner}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815097, extensionRPC: ext.flutter.debugWidgetInspector}}
[   +3 ms] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815102, extensionRPC: ext.flutter.inspector.show}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815103, extensionRPC: ext.flutter.inspector.disposeAllGroups}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815103, extensionRPC: ext.flutter.inspector.disposeGroup}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815103, extensionRPC: ext.flutter.inspector.isWidgetTreeReady}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815104, extensionRPC: ext.flutter.inspector.disposeId}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815104, extensionRPC: ext.flutter.inspector.setPubRootDirectories}}
[   +2 ms] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815104, extensionRPC: ext.flutter.inspector.setSelectionById}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815104, extensionRPC: ext.flutter.inspector.getParentChain}}
[   +3 ms] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815108, extensionRPC: ext.flutter.inspector.getProperties}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815109, extensionRPC: ext.flutter.inspector.getChildren}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815109, extensionRPC: ext.flutter.inspector.getChildrenSummaryTree}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815109, extensionRPC: ext.flutter.inspector.getChildrenDetailsSubtree}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815109, extensionRPC: ext.flutter.inspector.getRootWidget}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815109, extensionRPC: ext.flutter.inspector.getRootRenderObject}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815109, extensionRPC: ext.flutter.inspector.getRootWidgetSummaryTree}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815109, extensionRPC: ext.flutter.inspector.getDetailsSubtree}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815109, extensionRPC: ext.flutter.inspector.getSelectedRenderObject}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815109, extensionRPC: ext.flutter.inspector.getSelectedWidget}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815110, extensionRPC: ext.flutter.inspector.getSelectedSummaryWidget}}
[        ] {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/513879693, name: main.dart:main(), number: 513879693}, timestamp: 1530531815110, extensionRPC: ext.flutter.inspector.isWidgetCreationTracked}}
[        ] ext.flutter.inspector.setPubRootDirectories: {arg0: file:///C:/Users/Eduard/Google Drive/WorkSpaces/flutter/widget_paint_test, isolateId: isolates/513879693}
[ +532 ms] E/libc    ( 3950): Access denied finding property "persist.camera.cfa.packagelist"
[        ] W/widgetpainttest( 3950): type=1400 audit(0.0:102586): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=22660 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
[ +147 ms] ext.flutter.inspector.getSelectedSummaryWidget: {objectGroup: selection_214, isolateId: isolates/513879693}
[  +31 ms] ext.flutter.inspector.getSelectedWidget: {objectGroup: selection_214, isolateId: isolates/513879693}
[  +15 ms] ext.flutter.inspector.getRootWidgetSummaryTree: {objectGroup: tree_215, isolateId: isolates/513879693}
[+2738 ms] I/zygote64( 3950): Do full code cache collection, code=123KB, data=83KB
[   +1 ms] I/zygote64( 3950): After code cache collection, code=116KB, data=72KB
[+9214 ms] I/zygote64( 3950): Do partial code cache collection, code=122KB, data=77KB
[        ] I/zygote64( 3950): After code cache collection, code=122KB, data=77KB
[        ] I/zygote64( 3950): Increasing code cache capacity to 512KB

```

All the issues look like they are related to other files (i didn't create a separate project for the example code...
```
Analyzing widget_paint_test...

   info - Unused import: 'dart:async' - lib\display_window.dart:4:8
   info - Unused import: 'dart:typed_data' - lib\display_window.dart:6:8
   info - This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) - lib\display_window.dart:10:7
   info - The value of the field '_offset' isn't used - lib\display_window.dart:41:10
   info - The method '_toggleActive' isn't used - lib\display_window.dart:113:8
   info - Unused import: 'GlobalState.dart' - lib\main.dart:2:8
   info - Avoid using braces in interpolation when not needed - lib\mlkit_minimum_test.dart:127:16
   info - Avoid using braces in interpolation when not needed - lib\mlkit_minimum_test.dart:160:34
   info - Avoid using braces in interpolation when not needed - lib\mlkit_minimum_test.dart:172:22
   info - Avoid using braces in interpolation when not needed - lib\mlkit_minimum_test.dart:176:21
   info - Avoid using braces in interpolation when not needed - lib\mlkit_minimum_test.dart:177:28
   info - Avoid using braces in interpolation when not needed - lib\mlkit_minimum_test.dart:181:29
   info - This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) - lib\roi_window.dart:5:7
   info - The value of the field '_implementationType' isn't used - lib\roi_window.dart:34:7
   info - The value of the field '_offset' isn't used - lib\roi_window.dart:36:10
   info - Unused import: 'diagonally_movable_button.dart' - lib\stack_test.dart:2:8
   info - Unused import: 'package:mlkit/mlkit.dart' - lib\stack_test.dart:7:8
   info - Unused import: 'dart:typed_data' - lib\stack_test.dart:11:8
   info - Unused import: 'display_window.dart' - lib\stack_test.dart:13:8
   info - Avoid using braces in interpolation when not needed - lib\stack_test.dart:129:44
   info - Unused import: 'package:widget_paint_test/main.dart' - test\widget_test.dart:10:8
  error - The constructor returns type 'dynamic' that isn't of expected type 'Widget' - test\widget_test.dart:15:29
  error - Undefined class 'MyApp' - test\widget_test.dart:15:33

23 issues found. (ran in 10.7s)

```

```
C:\Users\Eduard\Google Drive\WorkSpaces\flutter\widget_paint_test>flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.492], locale en-ZA)
    • Flutter version 0.5.1 at C:\Program Files\Android\flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Eduard\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.4
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700

[√] Connected devices (1 available)
    • ONEPLUS A5000 • 77cd7290 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

**Comment by MisterJimson** [comment] 2018-10-18 15:04
Also running into this. Anyone know a way to get an image of the camera preview without taking a picture and reading it from a file?

**Comment by hariprasadiit** [comment] 2018-11-02 07:01
@MisterJimson this is somewhat related to #17687 . Please try `0.10.2` which includes fix for mentioned issue. that might solve issue with camera preview too.

**Comment by MisterJimson** [comment] 2018-11-02 13:09
![0 10 2-flutter](https://user-images.githubusercontent.com/7351329/47917153-f73cc280-de7e-11e8-9843-f587b0569a97.png)

Not fixed on Android 0.10.2 from dev branch. Same result.

**Comment by hariprasadiit** [comment] 2018-11-02 14:17
@chinmaygarde any idea why we are not able to capture camera preview? I thought `Scene.toImage()` would fix this issue too.

**Comment by chinmaygarde** [comment] 2018-11-03 18:38
It may be that the external texture (that the camera plugin gives the engine) has been collected by the time the screenshot request is serviced. I'll investigate this next. Thanks for the reduced test case.

**Comment by eduardkieser** [comment] 2018-11-24 12:50
Any updates on camera preview screen capture?

**Comment by callumclift** [comment] 2019-02-27 09:23
having the same issue, i've managed to incorporate pinch & zoom on the camera but when the camera takes the picture is gives the user the full image not the zoomed image. So my workaround was to screenshot the camera preview however the repaintBoundary screenshot is not working. Any updates on this??

**Comment by tim-fdc** [comment] 2019-04-04 14:15
Same here if the `RenderRepaintBoundary` contains google map view (native).

**Comment by BoHellgren** [comment] 2019-11-27 10:54
This issue has now been open for 16 months.

RepaintBoundary + RenderRepaintBoundary does not work as expected if the RepaintBoundary widget wraps a CameraPreview widget. 

For code to reproduce, see for example
https://stackoverflow.com/questions/51103815/how-to-take-a-screenshot-of-the-camerapreview-in-flutter

I have tested this with several Flutter versions including Flutter 1.12.13 (channel dev).

Any hope of ever getting this fixed? (I need it for an on-line car license plate scanner.)

**Comment by fabdotnet** [comment] 2020-02-04 04:08
Anyone got a workaround for this?

**Comment by qiuguian** [comment] 2020-03-06 08:37
Anyone know a way to get an image of the camera preview without taking a picture and reading it from a file?

**Comment by BoHellgren** [comment] 2020-03-06 10:53
The Medium post
[Build a Dog Camera using Flutter and Tensorflow](https://medium.com/swlh/build-a-dog-camera-using-flutter-and-tensorflow-312022b716c6)
describes how to do this.

**Comment by panmari** [comment] 2020-06-20 18:39
@kf6gpe I'm also running into this. Any guidance on how I could debug this on my own? I'd be happy to contribute a patch, but I don't even know where to start.

**Comment by darshankawar** [comment] 2020-08-26 12:17
Hi @eduardkieser,
Can you please confirm if this is still an issue on latest stable or master version ?
Thanks.

**Comment by benlrichards** [comment] 2020-08-27 17:56
@darshankawar This is still an issue. Found this issue page today while encountering this. Cannot capture camera preview.

**Comment by pedromassangocode** [comment] 2020-09-18 13:31
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-09-18 13:31 UTC
Labels: P4, customer: crowd, engine, framework, p: camera, p: first party, plugin, waiting for customer response

**Comment by MisterJimson** [comment] 2020-09-18 14:20
Here is a reproduction repo: https://github.com/MisterJimson/camera_preview_repaint_bug

Steps:
- Run the repo
- Move the blue square over the camera preview
- Observe that `boundary.toImage` is ignoring the camera preview

Here is my Flutter doctor

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-CA)
    • Flutter version 1.20.4 at /Users/jrai/dev/flutter
    • Framework revision fba99f6cf9 (4 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jrai/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/jrai/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/jrai/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1


[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86 • Android 10 (API 29) (emulator)
    • Jason's iPhone (mobile)            • 00008030-001A30DA0C90802E • ios         • iOS 13.7
```

**Comment by Sunbreak** [comment] 2020-11-12 02:37
> I'm a little confused. It's very simple to reproduce this issue as noted in the original comments. What information are you missing?

Maybe device specific?

**Comment by KorbinianMossandl** [comment] 2020-11-25 10:59
@pedromassango can you please reopen this? it was never resolved and the issue is super easy to reproduce with the demo app provided. i see no point why we should open new issues, if this already explains the problem perfectly.

**Comment by gabeschine** [comment] 2020-12-29 22:03
@pedromassangocode yes please re-open this. It's easy to reproduce. It affects all platform views.

**Comment by pedromassangocode** [comment] 2020-12-30 10:10
There is a duplicate issue that has more information and that is easily reproducible and is still opened: https://github.com/flutter/flutter/issues/25306. Please follow up on that issue. They are the same and there is no need to track same issue in different places.

**Comment by gabeschine** [comment] 2020-12-30 15:57
Got it. Thank you!
