### ISSUE TITLE
[video_player] Videos are slow when in Play Store

### ISSUE THREAD

**Issue by CripyIce** [flutter/flutter#93614] opened 2021-11-14 08:27 UTC
## Steps to Reproduce

It's a bit hard for me to write down the steps to reproduce this issue, but this is what i'm doing:
1. Using WordPress API to get post content.
2. Parsing the `html` code into widgets using `flutter_html` library.
3. The library finds video content and replaces it with a `chewie` widget which is based on `video_player`.
4. Running `flutter build apk` and installing it directly on a device works perfectly fine.
5. When uploading to Play Store all the videos becomes extremely laggy.

**Expected results:** videos to be played as smooth as they should, just like when I install the APK file directly to my device.

**Actual results:** videos becomes extremely laggy.

APK directly installed to my device:

https://user-images.githubusercontent.com/26387823/141673545-8f3f5365-ddae-4a9b-8839-2d766db6f14a.mp4

APK installed from Play Store:

https://user-images.githubusercontent.com/26387823/141673542-1865f073-dc12-4202-8962-60ec9db56dd8.mp4

**Comment by imihirpaldhikar** [comment] 2021-11-15 04:01
This might be due to the banner ads showing in the bottom of the screen. The current issue with the Google ads plugin that is app frames are dropping while showing ads. In the 1st video in the debug mode no ads are shown thus the video plays smoothly. But after uploading to Play Store, the ads are showing thus making the video frame drops

**Comment by CripyIce** [comment] 2021-11-15 07:41
@imihirpaldhikar Thanks! I will check it immediately!

But there is something strange, the video with no ads is also a release version of the APK.
It’s strange that the ads are only sowing once uploaded to the store.
I’ll try uploading a new APK to alpha channel to see if it works smooth without the ads.

**Comment by imihirpaldhikar** [comment] 2021-11-15 07:43
Yup that's because the ads are only shown if the app is download from Play Store. That's how it's works.

Nothing strange in that.

**Comment by darshankawar** [comment] 2021-11-15 09:24
@CripyIce 
Do confirm if it's happening due to ads and not specific to video_player. If so, you'll need to open this issue in dedicated repo: https://github.com/googleads/googleads-mobile-flutter/issues.
If you are able to isolate the issue specific to video_player, we will need a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins, to make this issue actionable.
Thanks.

**Comment by CripyIce** [comment] 2021-11-22 07:04
@darshankawar I have added the following code and now it works!
```dart
  if (Platform.isAndroid) {
    PlatformViewsService.synchronizeToNativeViewHierarchy(false);
  }
```

**Comment by mamuseferha** [comment] 2021-11-22 08:13
Hi @CripyIce 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by mamuseferha** 2021-11-22 08:13 UTC
Labels: in triage
