### ISSUE TITLE
BackButton on the AppBar is not taking `foregroundColor` from ThemeData

### ISSUE THREAD

**Issue by OutdatedGuy** [flutter/flutter#111286] opened 2022-09-09 17:42 UTC
After upgrading to Flutter version `3.3.0`, the `BackButton` on the `AppBar` is not taking color from the `foregroundColor` property.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click on the button `Go to Second Page`
3. See BackButton color is not white

**Expected results:** 
`BackButton` should have the same color as value of `foregroundColor`.

**Actual results:** 
`BackButton` color is not decided by value of `foregroundColor`

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.purple,
          foregroundColor: Colors.white,
        ),
      ),
      home: const FirstPage(),
    );
  }
}

class FirstPage extends StatelessWidget {
  const FirstPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => const SecondPage()),
            );
          },
          child: const Text('Go to Second Page'),
        ),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Page'),
      ),
      body: const Center(
        child: Text('Second Page'),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```bash
Analyzing whats_that_anime...                                           
No issues found! (ran in 17.5s)
```

```bash
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.22622.590], locale en-IN)
    • Flutter version 3.3.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (3 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Dell\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.71.0)
    • VS Code at C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.590]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Before Flutter 3.3.0 (on Flutter 3.0.5)
![image](https://user-images.githubusercontent.com/74326345/189378575-35c5fe51-e832-40d0-b0be-df28045af7c9.png)

After Flutter 3.3.0
![image](https://user-images.githubusercontent.com/74326345/189378460-f152c89b-0035-4f41-bf3a-2d43103fc744.png)

**Comment by huycozy** [comment] 2022-09-12 05:44
Hi @OutdatedGuy, this issue seems to have been fixed on the master channel as I cannot reproduce it there. See the demo below.

<details>
<summary>Demo</summary>

| stable | master |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/189581509-74356aed-b58f-462f-8dc2-5570a10f29e7.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/189581499-5472929a-6e1c-4fc5-b193-84edd6f2fb02.png">

</details>

I'll be closing this issue since it has already been fixed on the master channel.
If you still experience this issue on the master channel, kindly leave a comment below and I will reopen this.
Thank you!

**Closed by huycozy** 2022-09-12 05:44 UTC
Labels: in triage
