### ISSUE TITLE
incorrect behaviour of the callback method 'onPageFinished' in webview_flutter on iOS

### ISSUE THREAD

**Issue by 7syw** [flutter/flutter#35787] opened 2019-07-09 05:03 UTC
Hi,

We use the callback method 'onPageFinished' to control the visibility of busybee, but the behaviour is different for android and ios. this callback method works fine for ios, but it doesn't work for android. it was called for twice in Android device when start page loading and finish page loading, it was called once for ios when finish page loading.

BTW, version: - webview_flutter: 0.3.6

Yawei

**Comment by Piinks** [comment] 2019-07-09 18:39
Hi @7syw. Can you post a reproduction of the issue? We will need more information to help you resolve it.

**Comment by 7syw** [comment] 2019-07-10 01:37
@Piinks , see below code, expect the callback method 'onPageFinished' only run once when the page (H5 application) loading is finished. it run once for iOS, but twice for Android which both for starting page load and loading finished. 
We saw the comments for this mehod which is 'Invoked when a page has finished loading.', the actual behavious is conflicted with comments.

```
  @override
 void initState() {
    super.initState();
    debugPrint('@@@url:' + widget.url);
    webView = new WebView(
      initialUrl: widget.url,
     // we expect the below callback method only run once.
      onPageFinished: (url) {
        loading = false;
        setState(() {
        });
      },
     // we expect the below callback method only run once.
      onWebViewCreated: (WebViewController webViewController) {
        _controller = webViewController;
        _controller.clearCache();
      },
      javascriptChannels: <JavascriptChannel>[_channel(context),].toSet(),
      javascriptMode: JavascriptMode.unrestricted,
    );
  }
```

**Comment by 7syw** [comment] 2019-07-10 01:40
this issue only occurs for android.

**Comment by fracon** [comment] 2019-09-01 11:11
I am facing the same problem but in iOS environment. 

Version 0.3.13.

**Comment by josephmangmang** [comment] 2020-01-20 13:58
onPageFinished not called in ios but called in android. Weird

**Comment by darshankawar** [comment] 2020-06-26 10:13
I observed that `onPageFinished` and `onWebviewCreated` methods are being called on iOS (13.3) once, but on Android, `onPageFinished` is not called. 
Issue persists on latest `dev channel (1.20.0-0.0.pre)` and with latest version of `webview_flutter` plugin.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.20.0-0.0.pre at /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2021-08-09 07:21
The issue is not reproducible on the latest `stable 2.2.3` and `master 2.5.0-6.0.pre.29`. Closing and marking as fixed. 
For reference, find the code sample used below as well as the logs. 

<details>
<summary> code sample</summary>

```dart
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: WebViewExample(),
    );
  }
}

class WebViewExample extends StatefulWidget {
  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: WebView(
          initialUrl: 'https://master-docs-flutter-io.firebaseapp.com/',
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
            print(
              "+=================================+\n\n [${Platform.operatingSystem}] onWebViewCreated\n\n+=================================+",
            );
          },
          onPageFinished: (String url) {
            print(
              "+=================================+\n\n [${Platform.operatingSystem}] onPageFinishCalled\n\n+=================================+",
            );
          },
          javascriptChannels: <JavascriptChannel>{
            JavascriptChannel(
              name: 'Log',
              onMessageReceived: (JavascriptMessage msg) {
                print("+====${msg.message}====+");
              },
            )
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Container(
          color: Colors.orange,
        ),
        onPressed: () {},
      ),
    );
  }
}

```
</details>

<details> 
<summary>logs</summary>

```
Launching lib/main.dart on iPhone 12 in debug mode...
Running pod install...                                           1,030ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         3.2s
Xcode build done.                                           19.7s
Syncing files to device iPhone 12...                               167ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 12 is available at:
http://127.0.0.1:52814/JoY6nRvBcIg=/
flutter: +=================================+

 [ios] onWebViewCreated

+=================================+
The Flutter DevTools debugger and profiler on iPhone 12 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:52814/JoY6nRvBcIg=/
flutter: +=================================+

 [ios] onPageFinishCalled

+=================================+
```

```
Running Gradle task 'assembleDebug'...                              5.9s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
I/WebViewFactory(11439): Loading com.google.android.webview version 91.0.4472.114 (code 447211484)
W/xample.aug_nin(11439): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/xample.aug_nin(11439): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/xample.aug_nin(11439): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/xample.aug_nin(11439): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/xample.aug_nin(11439): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_VariationsUtils(11439): Failed reading seed file "/data/user/0/com.example.aug_nine/app_webview/variations_seed_new"
I/cr_VariationsUtils(11439): Failed reading seed file "/data/user/0/com.example.aug_nine/app_webview/variations_seed"
I/cr_LibraryLoader(11439): Loaded native library version number "91.0.4472.114"
I/cr_CachingUmaRecorder(11439): Flushed 6 samples from 6 histograms.
I/TetheringManager(11439): registerTetheringEventCallback:com.example.aug_nine
W/chromium(11439): [WARNING:dns_config_service_android.cc(153)] Failed to read DnsConfig.
D/CompatibilityChangeReporter(11439): Compat change id reported: 171228096; UID 10154; state: ENABLED
W/xample.aug_nin(11439): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
W/cr_media(11439): Requires BLUETOOTH permission
D/HostConnection(11439): createUnique: call
D/HostConnection(11439): HostConnection::get() New Host Connection established 0xb400007cce6ed490, tid 11520
D/HostConnection(11439): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation(11439): eglCreateContext: 0xb400007cce6ee510: maj 3 min 0 rcv 3
Syncing files to device sdk gphone64 arm64...                      200ms
D/EGL_emulation(11439): eglMakeCurrent: 0xb400007cce6ee510: ver 3 0 (tinfo 0x7edd478280) (first time)

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on sdk gphone64 arm64 is available at:
http://127.0.0.1:53167/-oJVD3TFvf4=/
D/EGL_emulation(11439): eglCreateContext: 0xb400007cce6edf10: maj 3 min 0 rcv 3
I/flutter (11439): +=================================+
I/flutter (11439): 
I/flutter (11439):  [android] onWebViewCreated
I/flutter (11439): 
I/flutter (11439): +=================================+
D/EGL_emulation(11439): eglCreateContext: 0xb400007cce6f0fd0: maj 3 min 0 rcv 3
D/EGL_emulation(11439): eglMakeCurrent: 0xb400007cce6e6110: ver 3 0 (tinfo 0x7edd478080) (first time)
I/flutter (11439): +=================================+
I/flutter (11439): 
I/flutter (11439):  [android] onPageFinishCalled
I/flutter (11439): 
I/flutter (11439): +=================================+
D/EGL_emulation(11439): app_time_stats: avg=169.69ms min=5.54ms max=870.47ms count=8
The Flutter DevTools debugger and profiler on sdk gphone64 arm64 is available at:
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.29, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.5.0-6.0.pre.29 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6876c52b5b (8 hours ago), 2021-08-08 15:34:09 -0700
    • Engine revision c0e59bc7b6
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```


```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```
</details>

If anyone still experiences this issue, kindly leave a comment with `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I will reopen this issue. 
Thank you

**Closed by danagbemava-nc** 2021-08-09 07:21 UTC
Labels: platform-android, platform-ios, plugin, p: first party, p: webview, has reproducible steps, P4, found in release: 1.20
