### ISSUE TITLE
Draw/Clip a bezier curve path is very slow

### ISSUE THREAD

**Issue by windrunner414** [flutter/flutter#27453] opened 2019-02-03 04:13 UTC
Draw a complex path is very slow,even though the final result of the path is the same as a simple path.

**Comment by HansMuller** [comment] 2019-02-04 17:17
Could you provide a small example of the kind of path drawing you're referring to?

**Comment by windrunner414** [comment] 2019-02-05 05:37
![image](https://user-images.githubusercontent.com/31621968/52254719-05045700-294a-11e9-81a0-cb3562e2858f.png)
use two bezier curve and some line.if don't draw bezier curve,it is much faster 
![image](https://user-images.githubusercontent.com/31621968/52254787-6a584800-294a-11e9-96da-67730afa4e64.png)
Area C shows the text of area A with rotation and translation,and there are some shadows on the edge of area C
the performance is laggy
But when don't use the bezier curve,  like this.
![image](https://user-images.githubusercontent.com/31621968/52254841-cf13a280-294a-11e9-8d82-a2c3f328dfc0.png)
performance will be much better

**Comment by zoechi** [comment] 2019-02-07 11:05
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by windrunner414** [comment] 2019-02-09 16:44
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class MyPainter extends CustomPainter {
  final Offset a;
  Offset b,c,d,e,f,g,h,i,j,k;

  MyPainter({this.a});

  @override
  void paint(Canvas canvas, Size size) {
    f = Offset(size.width, size.height);
    calcPointsXY();
    Path pathAll = Path()..lineTo(0, size.height)..lineTo(size.width, size.height)..lineTo(size.width, 0)..close();
    canvas.drawPath(pathAll, Paint()..color=Colors.green);
    Path pathA = Path()
      ..lineTo(0, size.height)
      ..lineTo(c.dx, c.dy)
      ..quadraticBezierTo(e.dx, e.dy, b.dx, b.dy)
      ..lineTo(a.dx, a.dy)
      ..lineTo(k.dx, k.dy)
      ..quadraticBezierTo(h.dx, h.dy, j.dx, j.dy)
      ..lineTo(size.width, 0)
      ..close();
    
    /*pathA = Path()
      ..lineTo(0, size.height)
      ..lineTo(a.dx, size.height)
      ..lineTo(a.dx, 0)
      ..close();*/

    canvas.drawPath(pathA, Paint()..color=Colors.black);
    canvas.save();
    canvas.clipPath(Path.combine(PathOperation.reverseDifference, pathA, pathAll));
    TextPainter(
      textDirection: TextDirection.ltr,
      text: TextSpan(
        text: 'hello' * 500,
      ),
    )..layout(maxWidth: size.width)..paint(canvas, Offset(0, 0));
    canvas.restore();
    canvas.save();
    canvas.clipPath(pathA);
    TextPainter(
      textDirection: TextDirection.ltr,
      text: TextSpan(
        text: 'world' * 500,
      ),
    )..layout(maxWidth: size.width)..paint(canvas, Offset(0, 0));
    canvas.restore();
  }

  void calcPointsXY() {
    g = Offset((a.dx + f.dx) / 2, (a.dy + f.dy) / 2);
    e = Offset(g.dx - (f.dy - g.dy) * (f.dy - g.dy) / (f.dx - g.dx), f.dy);
    h = Offset(f.dx, g.dy - (f.dx - g.dx) * (f.dx - g.dx) / (f.dy - g.dy));
    c = Offset(e.dx - (f.dx - e.dx) / 2, f.dy);
    j = Offset(f.dx, h.dy - (f.dy - h.dy) / 2);
    b = getIntersectionPoint(a,e,c,j);
    k = getIntersectionPoint(a,h,c,j);
    d = Offset((c.dx + 2 * e.dx + b.dx) / 4, (2 * e.dy + c.dy + b.dy) / 4);
    i = Offset((j.dx + 2 * h.dx + k.dx) / 4, (2 * h.dy + j.dy + k.dy) / 4);
  }

  Offset getIntersectionPoint(Offset lineOne_My_pointOne, Offset lineOne_My_pointTwo, Offset lineTwo_My_pointOne, Offset lineTwo_My_pointTwo){
    double x1,y1,x2,y2,x3,y3,x4,y4;
    x1 = lineOne_My_pointOne.dx;
    y1 = lineOne_My_pointOne.dy;
    x2 = lineOne_My_pointTwo.dx;
    y2 = lineOne_My_pointTwo.dy;
    x3 = lineTwo_My_pointOne.dx;
    y3 = lineTwo_My_pointOne.dy;
    x4 = lineTwo_My_pointTwo.dx;
    y4 = lineTwo_My_pointTwo.dy;

    double pointX =((x1 - x2) * (x3 * y4 - x4 * y3) - (x3 - x4) * (x1 * y2 - x2 * y1))
        / ((x3 - x4) * (y1 - y2) - (x1 - x2) * (y3 - y4));
    double pointY =((y1 - y2) * (x3 * y4 - x4 * y3) - (x1 * y2 - x2 * y1) * (y3 - y4))
        / ((y1 - y2) * (x3 - x4) - (x1 - x2) * (y3 - y4));

    return Offset(pointX, pointY);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}

class _MyHomePageState extends State<MyHomePage> {
  Offset p = Offset.zero;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        onPanUpdate: (DragUpdateDetails details) {
          setState(() {
            p = details.globalPosition;
          });
        },
        child: CustomPaint(
          painter: MyPainter(a: p),
          size: MediaQuery.of(context).size,
          isComplex: true,
          willChange: true,
        ),
      ),
    );
  }
}

```

**Comment by windrunner414** [comment] 2019-02-09 16:49
![image](https://user-images.githubusercontent.com/31621968/52523533-8737a700-2ccd-11e9-98f0-350815228c69.png)

if uncomment
```
pathA = Path()
      ..lineTo(0, size.height)
      ..lineTo(a.dx, size.height)
      ..lineTo(a.dx, 0)
      ..close();
```
![image](https://user-images.githubusercontent.com/31621968/52523555-acc4b080-2ccd-11e9-9377-4f435612ad40.png)

**Comment by windrunner414** [comment] 2019-02-09 16:57
Once bezier curved is used,it will be very slow.
```
void paint(Canvas canvas, Size size) {
    f = Offset(size.width, size.height);
    calcPointsXY();
    Path pathAll = Path()..lineTo(0, size.height)..lineTo(size.width, size.height)..lineTo(size.width, 0)..close();

    Path pathA = Path()
      ..quadraticBezierTo(e.dx, e.dy, b.dx, b.dy)
      ..close();

    canvas.save();
    canvas.clipPath(Path.combine(PathOperation.reverseDifference, pathA, pathAll));
    canvas.drawColor(Colors.red, BlendMode.src);
    canvas.restore();
    canvas.drawPath(pathA, Paint()..color=Colors.black);
  }
```
![image](https://user-images.githubusercontent.com/31621968/52523661-b13d9900-2cce-11e9-9687-624fc3f45cb8.png)

**Comment by darshankawar** [comment] 2020-12-02 12:00
@windrunner414 
Tried your code sample using latest stable version on Android emulator (Pixel 3XL) and observed below performance, which if we compare to your screenshots (while using bezier curve) seems to be normal. Didn't notice slowness during draw / clip.

<img width="346" alt="Screenshot 2020-12-02 at 5 28 17 PM" src="https://user-images.githubusercontent.com/67046386/100870052-fe9e8200-34c3-11eb-9fdf-6f4ee414d38c.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!

```

</details>

I am going ahead and closing this as fixed. If you disagree, or think this still persists at your end, write in comments and I'll reopen it.
Thanks.

**Comment by dsyrstad** [comment] 2020-12-02 13:13
@darshankawar The raster thread in your screenshot is getting 32.1ms/frame avg, and 61.9ms/frame max. This is 2x-4x the budget for a 60fps frame (16ms). In my opinion, I would say it is not fixed.

**Comment by darshankawar** [comment] 2020-12-02 13:20
Thanks @dsyrstad.

**Comment by huycozy** [comment] 2022-12-14 09:54
This issue is reproducible on the latest `stable` and `master` channels. Verifying on `Samsung Galaxy Tab A7 Lite, Android 12 OneUI 4.1, SM-T225`.

<details>
<summary>Demo image (performance overlay)</summary>

![Screenshot 2022-12-14 at 16 48 16](https://user-images.githubusercontent.com/104349824/207562440-cc6366ee-da09-4319-a5a3-640af78d410b.png)


</details>

Attach the timeline trace JSON file: 
[dart_devtools_2022_12_14-1671011272820000.json.zip](https://github.com/flutter/flutter/files/10226487/dart_devtools_2022_12_14-1671011272820000.json.zip)


<details>
<summary>Sample code (be compatible with the new flutter version)</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class MyPainter extends CustomPainter {
  final Offset a;
  late Offset b,c,d,e,f,g,h,i,j,k;

  MyPainter({required this.a});

  @override
  void paint(Canvas canvas, Size size) {
    f = Offset(size.width, size.height);
    calcPointsXY();
    Path pathAll = Path()..lineTo(0, size.height)..lineTo(size.width, size.height)..lineTo(size.width, 0)..close();
    canvas.drawPath(pathAll, Paint()..color=Colors.green);
    Path pathA = Path()
      ..lineTo(0, size.height)
      ..lineTo(c.dx, c.dy)
      ..quadraticBezierTo(e.dx, e.dy, b.dx, b.dy)
      ..lineTo(a.dx, a.dy)
      ..lineTo(k.dx, k.dy)
      ..quadraticBezierTo(h.dx, h.dy, j.dx, j.dy)
      ..lineTo(size.width, 0)
      ..close();

    /*pathA = Path()
      ..lineTo(0, size.height)
      ..lineTo(a.dx, size.height)
      ..lineTo(a.dx, 0)
      ..close();*/

    canvas.drawPath(pathA, Paint()..color=Colors.black);
    canvas.save();
    canvas.clipPath(Path.combine(PathOperation.reverseDifference, pathA, pathAll));
    TextPainter(
      textDirection: TextDirection.ltr,
      text: TextSpan(
        text: 'hello' * 500,
      ),
    )..layout(maxWidth: size.width)..paint(canvas, Offset(0, 0));
    canvas.restore();
    canvas.save();
    canvas.clipPath(pathA);
    TextPainter(
      textDirection: TextDirection.ltr,
      text: TextSpan(
        text: 'world' * 500,
      ),
    )..layout(maxWidth: size.width)..paint(canvas, Offset(0, 0));
    canvas.restore();
  }

  void calcPointsXY() {
    g = Offset((a.dx + f.dx) / 2, (a.dy + f.dy) / 2);
    e = Offset(g.dx - (f.dy - g.dy) * (f.dy - g.dy) / (f.dx - g.dx), f.dy);
    h = Offset(f.dx, g.dy - (f.dx - g.dx) * (f.dx - g.dx) / (f.dy - g.dy));
    c = Offset(e.dx - (f.dx - e.dx) / 2, f.dy);
    j = Offset(f.dx, h.dy - (f.dy - h.dy) / 2);
    b = getIntersectionPoint(a,e,c,j);
    k = getIntersectionPoint(a,h,c,j);
    d = Offset((c.dx + 2 * e.dx + b.dx) / 4, (2 * e.dy + c.dy + b.dy) / 4);
    i = Offset((j.dx + 2 * h.dx + k.dx) / 4, (2 * h.dy + j.dy + k.dy) / 4);
  }

  Offset getIntersectionPoint(Offset lineOne_My_pointOne, Offset lineOne_My_pointTwo, Offset lineTwo_My_pointOne, Offset lineTwo_My_pointTwo){
    double x1,y1,x2,y2,x3,y3,x4,y4;
    x1 = lineOne_My_pointOne.dx;
    y1 = lineOne_My_pointOne.dy;
    x2 = lineOne_My_pointTwo.dx;
    y2 = lineOne_My_pointTwo.dy;
    x3 = lineTwo_My_pointOne.dx;
    y3 = lineTwo_My_pointOne.dy;
    x4 = lineTwo_My_pointTwo.dx;
    y4 = lineTwo_My_pointTwo.dy;

    double pointX =((x1 - x2) * (x3 * y4 - x4 * y3) - (x3 - x4) * (x1 * y2 - x2 * y1))
        / ((x3 - x4) * (y1 - y2) - (x1 - x2) * (y3 - y4));
    double pointY =((y1 - y2) * (x3 * y4 - x4 * y3) - (x1 * y2 - x2 * y1) * (y3 - y4))
        / ((y1 - y2) * (x3 - x4) - (x1 - x2) * (y3 - y4));

    return Offset(pointX, pointY);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}

class _MyHomePageState extends State<MyHomePage> {
  Offset p = Offset.zero;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        onPanUpdate: (DragUpdateDetails details) {
          setState(() {
            p = details.globalPosition;
          });
        },
        child: CustomPaint(
          painter: MyPainter(a: p),
          size: MediaQuery.of(context).size,
          isComplex: true,
          willChange: true,
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.3.9 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (31 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-7.0.pre.18, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-7.0.pre.18 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f07db4018a (12 minutes ago), 2022-12-14 03:25:49 +0200
    • Engine revision 14194c40ec
    • Dart version 3.0.0 (build 3.0.0-19.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by jonahwilliams** [comment] 2024-08-13 03:23
We believe this is fixed with Impeller, though Impeller is not yet available on all platforms

**Comment by huycozy** [comment] 2024-08-14 03:51
Re-visiting and checking this with Flutter stable 3.24.0, Impeller enabled, I see a significant performance improvement since the last time I checked above on the same device. It now has 20ms/frame max and 11ms/frame avg from Devtools.

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/4c41c5c6-7d81-49e4-9046-2b691e5cc563

</details>

@windrunner414 I'm going to close this as fixed. If you are still experiencing this on your end, please write in the comments. Thanks!

**Closed by huycozy** 2024-08-14 03:51 UTC
Labels: engine, c: performance, has reproducible steps, P2, found in release: 3.3, found in release: 3.7, team-engine, triaged-engine
