### ISSUE TITLE
[Regression] runZonedGuarded + Firebase + Exception having issues with Null Safety

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#69611] opened 2020-11-02 21:45 UTC
It seems this commit
https://github.com/flutter/flutter/commit/324b78eb12618d3193c164a90e7bd22b3e11413c, which is more than welcome, is breaking some things.

We have:
```dart
  runZonedGuarded<Future<Null>>(() async {
    runApp(App());
  }, (error, stackTrace) async {
    await errorHelper.reportError(error, stackTrace);
  });
```
And:
```dart
try {
    await FirebaseAuth.instance.createUserWithEmailAndPassword(email: email, password: password)
    return true;
} catch (e) {
    return false;
}
```
Yet, when that code is run, with invalid attributes, the widget temporarily crashes with the message below. That wasn't happening on Friday, or on the dev branch.

```
Another exception was thrown: Expected a value of type '() => void', but got one of type 'Null'
The following TypeErrorImpl was thrown building _SignInSignUpButton(dirty):
Expected a value of type '() => void', but got one of type 'Null'
The relevant error-causing widget was: _SignInSignUpButton

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 64:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 442:10  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 863:12       as
packages/my_project/auth/auth_forms.dart 635:3                            build
packages/flutter/src/widgets/framework.dart 4749:28                               build
packages/flutter/src/widgets/framework.dart 4675:15                               performRebuild
packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
packages/flutter/src/widgets/framework.dart 4756:5                                update
packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
packages/flutter/src/widgets/framework.dart 5693:32                               updateChildren
packages/flutter/src/widgets/framework.dart 6293:17                               update
packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
packages/flutter/src/widgets/framework.dart 5033:5                                update
packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4847:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
packages/flutter/src/widgets/framework.dart 4879:5                                update
packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4847:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
packages/flutter/src/widgets/framework.dart 4879:5                                update
packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
packages/flutter/src/widgets/framework.dart 5033:5                                update
packages/flutter/src/widgets/inherited_notifier.dart 181:11                       update
packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
packages/flutter/src/widgets/framework.dart 6171:14                               update
packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4847:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
packages/flutter/src/widgets/framework.dart 4879:5                                update
packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4847:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
packages/flutter/src/widgets/framework.dart 2777:31                               buildScope
packages/flutter/src/widgets/binding.dart 894:9                                   drawFrame
packages/flutter/src/rendering/binding.dart 320:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1117:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1055:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 971:5                                 [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 876:13                                _invoke
lib/_engine/engine/platform_dispatcher.dart 145:5                                 invokeOnDrawFrame
lib/_engine/engine.dart 239:45                                                    <fn>
dart-sdk/lib/async/zone.dart 1206:13                                              _rootRunUnary
dart-sdk/lib/async/zone.dart 1100:19                                              runUnary
dart-sdk/lib/async/zone.dart 1005:7                                               runUnaryGuarded
dart-sdk/lib/async/zone.dart 1042:26                                              <fn>
```

Tested on Flutter Web on both last beta and last master.
```
➜ flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-7.0.pre.61, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-BR)
    • Flutter version 1.24.0-7.0.pre.61 at /usr/local/flutter
    • Framework revision b7a92f05d2 (27 minutes ago), 2020-11-02 22:18:06 +0100
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)
```

**Comment by pedromassangocode** [comment] 2020-11-03 08:47
Hi @bernaferrari 
Can you please provide your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by bernaferrari** [comment] 2020-11-03 14:52
Exactly the same error. I can't, because Firebase is not testable/reproducible. But I'm just doing what I told you, a simple login inside a try/catch with a zonedGuarded around and it is causing this issue.

```dart
[+9009 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +1 ms] The following TypeErrorImpl was thrown building _SignInSignUpButton(dirty):
[        ] Expected a value of type '() => void', but got one of type 'Null'
[        ] The relevant error-causing widget was:
[        ]   _SignInSignUpButton
[        ]   file:///[...]forms.dart:154:13
[        ] When the exception was thrown, this was the stack:
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49      throw_
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 64:3        castError
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 442:10  cast
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 863:12       as
[   +1 ms] packages/codelessly_flutter/auth/auth_forms.dart 680:28                           build
[        ] packages/flutter/src/widgets/framework.dart 4749:28                               build
[        ] packages/flutter/src/widgets/framework.dart 4675:15                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
[        ] packages/flutter/src/widgets/framework.dart 4756:5                                update
[        ] packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
[        ] packages/flutter/src/widgets/framework.dart 5693:32                               updateChildren
[        ] packages/flutter/src/widgets/framework.dart 6293:17                               update
[        ] packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
[        ] packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
[        ] packages/flutter/src/widgets/framework.dart 5033:5                                update
[        ] packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
[        ] packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4847:11                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
[        ] packages/flutter/src/widgets/framework.dart 4879:5                                update
[   +1 ms] packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
[        ] packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4847:11                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
[        ] packages/flutter/src/widgets/framework.dart 4879:5                                update
[        ] packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
[        ] packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
[        ] packages/flutter/src/widgets/framework.dart 5033:5                                update
[        ] packages/flutter/src/widgets/inherited_notifier.dart 181:11                       update
[        ] packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
[        ] packages/flutter/src/widgets/framework.dart 6171:14                               update
[        ] packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
[        ] packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4847:11                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
[        ] packages/flutter/src/widgets/framework.dart 4879:5                                update
[        ] packages/flutter/src/widgets/framework.dart 3367:14                               updateChild
[        ] packages/flutter/src/widgets/framework.dart 4700:16                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4847:11                               performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4369:5                                rebuild
[   +1 ms] packages/flutter/src/widgets/framework.dart 2777:31                               buildScope
[        ] packages/flutter/src/widgets/binding.dart 894:9                                   drawFrame
[        ] packages/flutter/src/rendering/binding.dart 320:5                                 [_handlePersistentFrameCallback]
[        ] packages/flutter/src/scheduler/binding.dart 1117:15                               [_invokeFrameCallback]
[        ] packages/flutter/src/scheduler/binding.dart 1055:9                                handleDrawFrame
[        ] packages/flutter/src/scheduler/binding.dart 971:5                                 [_handleDrawFrame]
[        ] lib/_engine/engine/platform_dispatcher.dart 876:13                                _invoke
[        ] lib/_engine/engine/platform_dispatcher.dart 145:5                                 invokeOnDrawFrame
[        ] lib/_engine/engine.dart 239:45                                                    <fn>
[        ] dart-sdk/lib/async/zone.dart 1206:13                                              _rootRunUnary
[        ] dart-sdk/lib/async/zone.dart 1100:19                                              runUnary
[        ] dart-sdk/lib/async/zone.dart 1005:7                                               runUnaryGuarded
[        ] dart-sdk/lib/async/zone.dart 1042:26                                              <fn>
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +6 ms] Another exception was thrown: Expected a value of type '() => void', but got one of type 'Null'
[  +20 ms] Another exception was thrown: A RenderFlex overflowed by 199480 pixels on the bottom.
```

**Comment by pedromassangocode** [comment] 2020-11-04 07:00
Hi @bernaferrari 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-04 07:00 UTC
Labels: in triage
