### ISSUE TITLE
Properly report hot restart and hot reload times to benchmarks

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#17888] opened 2018-05-24 22:45 UTC
We've had a number of regressions to the hot reload performance recently. We should return to our previous numbers, possibly by reverting offending patches.

cc @cbracken @a-siva @tvolkert @aam

**Comment by cbracken** [comment] 2018-05-24 22:59
#17705 tracks two of these.

**Comment by mehmetf** [comment] 2018-05-29 18:07
My recommended solution is to roll back https://github.com/flutter/flutter/pull/17616 until  #17956 can be fixed then roll it forward.

Talked to @aam about it and he believes https://github.com/flutter/flutter/issues/17434 which was fixed by the PR mentioned above is more important the regression. @Hixie, what do you think?

**Comment by mit-mit** [comment] 2018-05-29 19:41
If we indeed have a 3x regression of hot reload, then that is important enough that we should revert.

But I cannot repro that regression. I tried to download both 0.4.4 and 0.2.8 from https://flutter.io/sdk-archive/, ran flutter_gallery from both, made a tweak to Shrine, and hot reloaded. I saw ~800ms in 0.2.8 and ~900ms in 0.4.4.

Is the regression after we shipped 0.4.4? Is it only in certain cases that I'm not hitting with my simple change (i'm just changing some padding)?

**Comment by mehmetf** [comment] 2018-05-29 19:45
I had the same idea as @mit-mit. Trying this from tip of tree, these are the numbers I am observing for gallery:

```
Initializing hot reload...                                       
flutter: service extension method received: ext.flutter.evict({value: AssetManifest.json, isolateId: isolates/31324121})
flutter: Action "Wait for outer event loop" took 0:00:00.001102
flutter: service extension method received: ext.flutter.evict({value: FontManifest.json, isolateId: isolates/31324121})
flutter: Action "Wait for outer event loop" took 0:00:00.000175
flutter: service extension method received: ext.flutter.evict({value: LICENSE, isolateId: isolates/31324121})
flutter: Action "Wait for outer event loop" took 0:00:00.000147
flutter: service extension method received: ext.flutter.reassemble({isolateId: isolates/31324121})
flutter: Action "Wait for outer event loop" took 0:00:00.000163
Reloaded 6 of 510 libraries in 1,487ms.

Performing hot reload...                                         
flutter: service extension method received: ext.flutter.reassemble({isolateId: isolates/31324121})
flutter: Action "Wait for outer event loop" took 0:00:00.000305
Reloaded 6 of 510 libraries in 795ms.

Performing hot reload...                                         
flutter: service extension method received: ext.flutter.reassemble({isolateId: isolates/31324121})
flutter: Action "Wait for outer event loop" took 0:00:00.000306
Reloaded 6 of 510 libraries in 717ms.
```

The subsequent hot reloads seem fine. The first hot reload is indeed bad but I thought that's always been the case. If these numbers look reasonable, perhaps this is only about fixing the benchmark so it measures the real user experience?

**Comment by tvolkert** [comment] 2018-05-29 19:51
There's definitely something weird going on in our reporting, because if I introduce an arbitrary delay in between our hot restart benchmark and hot reload benchmark<span>[1]</span>, I see a significant decrease in the reported hot reload time.  It would seem that our app is still "doing stuff" after we report the hot restart as complete, which in turn means we're probably _under_ reporting our hot restart times.

<span>[1]</span> https://github.com/flutter/flutter/blob/c7ea3ca377e909469c68f2ab878a5bc53d3cf66b/packages/flutter_tools/lib/src/run_hot.dart#L168-L172

**Comment by mehmetf** [comment] 2018-05-29 19:57
I locally reverted https://github.com/flutter/flutter/pull/17616. I don't see a perceptible change to hot reload times (first or subsequent).

**Comment by tvolkert** [comment] 2018-05-29 20:01
It sounds like we think that the reporting of our hot reload times can't be trusted and that we're actually ok in terms of user-perceived hot reload times?

If that's the case:
1. How do we gain enough confidence in that assessment to stop trying to track down what are actually phantom regressions?
1. let's re-purpose this bug to be "properly report hot restart and hot reload times to benchmarks"

**Comment by Hixie** [comment] 2018-05-29 20:01
Ok let's assume that this is a bug in the benchmark then. I believe @tvolkert is already looking down that path.

**Comment by goderbauer** [comment] 2018-06-15 20:38
For the time being I am rebasing all the affected `hotReload*` benchmark with a very high baseline so they don't show up as red on our dashboard. Them being red creates a lot of visual noise that's not really actionable until this bug is resolved.

**Comment by Hixie** [comment] 2018-06-19 23:30
@tvolkert I've moved this to beta7 on the assumption that you're still planning on working on this; please let me know if not.

**Comment by Hixie** [comment] 2018-07-18 00:23
Chatted with Todd, the plan is to look at this in the coming weeks.

**Comment by aam** [comment] 2018-08-29 16:12
Not sure whether anybody looked at this further, but I think we want to rebase the benchmarks as they have been stable for a while now and seem to reliably report performance changes(hopefully improvements) in hot reload/restart flows.

**Comment by Hixie** [comment] 2018-08-30 18:58
Unless we changed something I see no reason to believe they are any more reliable now than before... would we trust a regression today? As in, would we automatically revert a patch that caused these numbers to regress?

BTW I've hidden all the intermediate numbers on the dashboard, we only show the "to frame" numbers at the moment.

**Comment by aam** [comment] 2018-08-30 19:11
>  As in, would we automatically revert a patch that caused these numbers to regress?

Not sure whether we would _automatically_ revert, but we would definitely investigate it. We did so in the past(when benchmark went red) and it helped to find real regressions. Now regressions will go unnoticed.

> BTW I've hidden all the intermediate numbers on the dashboard, we only show the "to frame" numbers at the moment.

Ah, interesting. Was the rationale for this was the same - the benchmarks were deemed unreliable?

**Comment by Hixie** [comment] 2018-08-30 19:20
> Ah, interesting. Was the rationale for this was the same - the benchmarks were deemed unreliable?

It's two-fold. One is that we had so many benchmarks that actual issues were getting lost in the noise, so we're adopting a policy of having top-level numbers on the benchmarks dashboard and having the more detailed numbers available hidden for when we want to debug (e.g. we would happily take a regression in one for the same improvement in another, so long as the end number is the same or better). The other reason is as you say, these specific numbers don't seem to be representing reality and until we investigate them and verify that they're really real, it's pointless to show them.

Anyway, if we are going to take the numbers seriously, then sure, let's rebaseline them. That's independent of whether we go and make them more reliable. I just don't want to have benchmarks that we trivially ignore any time they go red.

> Not sure whether we would automatically revert, but we would definitely investigate it.

FWIW, I'd much rather we start reverting pre-emptively and investigate later than have multiple in-flight potential regressions at once. Part of getting Flutter stable is making sure we are ruthlessly unwilling to regress anything.

**Comment by dnfield** [comment] 2018-08-30 22:32
I just ran the `hot_mode_dev_cycle__benchmark` locally, and the numbers I'm getting are pretty close to my machine's numbers when doing the same things manually:

```
Task result:
{
  "success": true,
  "data": {
    "hotReloadInitialDevFSSyncMilliseconds": 3120,
    "hotRestartMillisecondsToFrame": 1387,
    "hotReloadMillisecondsToFrame": 592,
    "hotReloadDevFSSyncMilliseconds": 265,
    "hotReloadFlutterReassembleMilliseconds": 319,
    "hotReloadVMReloadMilliseconds": 6,
    "hotReloadMillisecondsToFrameAfterChange": 458,
    "hotReloadDevFSSyncMillisecondsAfterChange": 275,
    "hotReloadFlutterReassembleMillisecondsAfterChange": 103,
    "hotReloadVMReloadMillisecondsAfterChange": 79,
    "hotReloadInitialDevFSSyncAfterRelaunchMilliseconds": 3067
  },
 ...
}
```

- Manual runs on a hot restart range from 1,275ms to 1,439ms.
- Manual runs on a hot reload range from 319ms (no changes) to 613ms (changes).

In both cases, the benchmark is coming up within reasonable range of the manual tests.  That said, my machine is running significantly faster than the times I see on the dashboard.  That seems likely to be environmental.

This all seems to support the hypothesis that the benchmarks were actually broken in the past, and are more accurate now - and just need to be rebased.

**Comment by aam** [comment] 2018-08-31 15:58
> BTW I've hidden all the intermediate numbers on the dashboard, we only show the "to frame" numbers at the moment.

One other point regarding this - some of the benchmarks (like https://flutter-dashboard.appspot.com/benchmarks.html?filter=hotReloadInitialDevFSSyncAfterRelaunchMilliseconds which is archived - you need to click 'Show archived' after following the link) are not necessarily intermediate. They don't reflect 'to frame' experience, no, but they reflect user experience with the tool - the longer this 'initial devfs sync' takes, the longer user have to wait before flutter tool is able to process next hot-reload command after launch.

**Comment by dnfield** [comment] 2018-08-31 17:27
I'm closing this for now because as far as I can tell, the benchmarks are accurate - whatever jump happened in them was either related to more accurate reporting or some other issue that has since been resolved.

I've rebaselined the benchmarks in the dashboard to reflect current status quo.

**Closed by dnfield** 2018-08-31 17:27 UTC
Labels: dependency: dart, engine, severe: performance, t: hot reload, tool
