### ISSUE TITLE
WebView touchstart events are invoked even when the WebView is not hit tested on iOS

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#30143] opened 2019-03-28 22:27 UTC
Internal: b/126614142
Internal: b/285315999

Sample repro app:
```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: WebViewExample()));

class WebViewExample extends StatelessWidget {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: WebView(
        initialUrl: 'https://master-docs-flutter-io.firebaseapp.com/',
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) {
          _controller.complete(webViewController);
        },
        onPageFinished: (String url) {
          injectTouchListener();
        },
        javascriptChannels: <JavascriptChannel> [
          JavascriptChannel(name: 'Log', onMessageReceived: (JavascriptMessage msg) { print(msg.message); })
        ].toSet() ,
      ),
      floatingActionButton: FloatingActionButton(
        child: Container(color: Colors.orange,),
          onPressed: () {}
          ),
    );
  }
  Future<void> injectTouchListener() async {
    final WebViewController controller = await _controller.future;
    controller.evaluateJavascript("document.addEventListener('touchstart', (event) => { Log.postMessage(String(event)); }, true);");
  }
}
```
On iOS the message is printing even when tapping the FAB.

**Comment by amirh** [comment] 2019-03-28 23:07
cc @cyanglaz

**Comment by cyanglaz** [comment] 2019-04-02 00:04
Spent some time investigate this issue with @amirh and @chinmaygarde debugging this issue. We tried replacing 'touchstart' with a different event like 'click', it works fine. We think there could be some special case handling for events like 'touchstart' in iOS. We have not found any way to work around it.

Meanwhile, if anyone encounter this issue, I suggest working around it with a different event type.

**Comment by asavartsov** [comment] 2020-10-19 12:51
In my case, it even worse. When I tap a block in front of WebView, WebView receives touchstart, but does not receive touchend. And it will receive touchend ont he next tap with new touchstart right after it. This behavior breaks my Leaflet map completely. Adding IgnorePointer/AbsorbPointer does not help here. Somehow the page inside WebView still receives touchstart/touchend.

And it is probably connected to issues about broken map controls. I'm testing on iOS 13.6.

**Comment by asavartsov** [comment] 2020-10-19 18:14
A little clarification. As for Leaflet, it actually does not use the problem is that it detects support for pointer events and uses it instead of touchstart/touchend. And glitches occur because if WebView is touched directly it receives pointerup and pointerdown. But if a block in front of WebView is touched, pointerup event does not occur leaving pointerdown alone in the Leaflet's internal array of pointer events. For my project I fixed that by overriding pointer detection @ https://github.com/Leaflet/Leaflet/blob/9b0d7c2a7023e6a83222d96febaee74880601ad8/src/core/Browser.js#L96 setting it to false. Leaflet fallbacks to touchstart/touchend and even though it does receive events from other blocks when it shouldn't because of this bug it maintains internal state correctly.

**Comment by danagbemava-nc** [comment] 2021-08-09 06:48
The issue is reproducible on the latest `master (2.5.0-6.0.pre.29)` and `stable (2.2.3)` with the latest `webview_flutter: ^2.0.10`.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.29, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.5.0-6.0.pre.29 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6876c52b5b (8 hours ago), 2021-08-08 15:34:09 -0700
    • Engine revision c0e59bc7b6
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```


```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```
</details>

**Comment by ggirotto** [comment] 2022-03-29 15:08
We are facing the exactly same issue as @asavartsov described, but when using `UiKitView`.

**Comment by ert485** [comment] 2023-03-14 14:56
Thanks @asavartsov for the description and your workaround. I can't seem to do the same workaround since I'm using a third party library in the webview - I tried catching/disabling touchstart events and creating fake touchend events, but couldn't get it to work with the library. My options left are (1) don't put buttons on top of the webview (below/beside instead), or (2) put the buttons inside the webview instead of being implemented in flutter (and have the html buttons trigger events that get noticed in flutter)

**Comment by kcisoul** [comment] 2023-04-10 09:08
I spent couple of days to solve this problem. 
I think I tried every workaround here and stackOverflow. 
Finally I got the answer myself.
When you need to draw widgets over WebView, add empty transparent webView over the original webView. 

I wrote code  like this 

Stack(children: [
                  Opacity(
                    opacity: 0.01,
                    child: WebViewWidget(controller: WebViewController())                    
                  ),
                    const CircularProgressIndicator(),                  
                ]);

This works fine so far.

**Comment by cyanglaz** [comment] 2023-06-08 17:16
@kcisoul Thanks for providing the workaround. To make the workaround easier, I think you only need to create an empty transparent PlatformView (UIView) to cover the region that you don't want the WebView to be interacted with.

**Comment by 903496130** [comment] 2023-07-05 15:46
> 

you are my superman

**Comment by 903496130** [comment] 2023-07-05 15:47
> 我花了几天时间来解决这个问题。我想我在这里尝试了所有解决方法并堆叠溢出。最后我自己得到了答案。（这只是简单的解决方法。当您需要在 Web 视图上绘制小部件时，请在原始 Web 视图上添加空的透明 Web 视图。
> 
> 我写了这样的代码
> 
> Stack（子项： [ 不透明度（ 不透明度： 0.01， 子项： WebViewWidget（控制器： WebViewController（）） ）， const CircularProgressIndicator（）， ]);
> 
> 到目前为止，这工作正常。

you are my superman, boy

**Comment by cyanglaz** [comment] 2023-07-12 16:22
Update: I will be working on evaluating a solution that when handling hittests, on Platform thread, we wait for the UIThread to report back the gesture result. This solution makes the the gesture handling synchronize, at the expense of losing performance. This feature will needed to be explicitly turned on by the developer by turning on a flag (defaults to false).

It is still in discussion stage and the prototype will likely take some time to implement because PlatformThread and UIThread were not designed to be synchronized, so blocking the PlatformThread is might cause some unknown issue.

**Comment by cyanglaz** [comment] 2023-07-18 18:13
I wired up a quick and ugly prototype to demonstrate a solution that blocks the touch events synchronously. If anyone can try it out and give some feedback that'd be great. https://github.com/flutter/engine/pull/43778

The particular feedback I'm looking for is whether this solution drastically reduces performance.

**Comment by stuartmorgan** [comment] 2023-07-24 19:22
Update from triage: still in development, testing is underway.

**Comment by cyanglaz** [comment] 2023-08-01 17:36
The prototype seems to working on several general scenarios that i tested. I will start to work on the design and implementation.

**Comment by llooz** [comment] 2023-08-04 10:37
@cyanglaz 
I'm looking forward to this because with [google_mobile_ads](https://pub.dev/packages/google_mobile_ads) we're encountering a lot of issues.

It depends on how the creativity of an Ad handles the click event, in some cases it works correctly but in other we're getting random Ad opening just because the user wanted to scroll or interact with a Flutter widget on top of a list that contains an Ad (e.g. an actionable bar in overlay etc).

This is very important to us because our app monetization is mostly based on having Ad widgets in lists and our app UI / UX was designed by not knowing of this kind of issues.
Moreover we're already having performance issues on iPhone >= 12 because of https://github.com/flutter/flutter/issues/129632 so having a fix that could further decrease performance it's not a good scenario for us.

We're available to offer any help that can lead to a fix for this!

**Comment by cyanglaz** [comment] 2023-08-04 13:07
@llooz Thank you for offering helps :) It would be nice if you could help test the prototype in https://github.com/flutter/engine/pull/43778 and report any issues in the PR as you see them.

**Comment by cyanglaz** [comment] 2023-08-21 19:09
I have been out for almost 2 weeks and have been working on some random fires for the last week, so I haven't been working on it. I plan to cycle back to this issue this week.

**Comment by cyanglaz** [comment] 2023-08-29 22:34
The design doc the ready: https://flutter.dev/go/ios-platform-view-hittest-blocking

**Comment by cyanglaz** [comment] 2023-09-08 18:50
We are going to provide a plugin solution using https://pub.dev/packages/pointer_interceptor

**Comment by cyanglaz** [comment] 2023-09-19 22:33
I'm currently working on the plug-in solution. I should open a PR no later than end of next week.

**Comment by cyanglaz** [comment] 2023-09-27 23:21
@LouiseHsu is going to take over this issue.

**Comment by LouiseHsu** [comment] 2023-10-11 00:00
Just started working on this issue, will keep this issue updated!

**Comment by LouiseHsu** [comment] 2023-10-24 23:05
Update: Have a draft PR coming sometime this week - working on testing and cleaning up :)

**Comment by LouiseHsu** [comment] 2023-10-31 21:21
PR is out! working on fixing tests.

**Comment by LouiseHsu** [comment] 2023-11-07 22:57
Hoping to land PR this week :)

**Comment by krokyze** [comment] 2023-11-07 23:01
> Hoping to land PR this week :)

By any chance, will it be included in the next minor release? 🙂

**Comment by LouiseHsu** [comment] 2023-11-22 00:31
@krokyze yep! thats the plan

**Comment by LouiseHsu** [comment] 2023-11-22 00:32
Update: Plan to merge next week post holiday weekend

**Comment by LouiseHsu** [comment] 2023-12-11 19:52
The new pointer_interceptor package should be available on pub.dev. now! https://pub.dev/packages/pointer_interceptor

**Closed by LouiseHsu** 2023-12-11 19:52 UTC
Labels: platform-ios, a: platform-views, p: webview, package, customer: money (g3), P0, found in release: 2.2, found in release: 2.5, team-ios, triaged-ios, multiteam-retriage-candidate
