### ISSUE TITLE
Shortcuts widget ignore LogicalKeyboardKey.audioVolumeUp on Android HW

### ISSUE THREAD

**Issue by Kozubi** [flutter/flutter#91086] opened 2021-10-01 12:00 UTC
## Steps to Reproduce

1. Run code on Android HW
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class IncrementIntent extends Intent {
  const IncrementIntent();
}

class DecrementIntent extends Intent {
  const DecrementIntent();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        systemOverlayStyle: SystemUiOverlayStyle(
          systemNavigationBarColor: Colors.purple, // Navigation bar
          statusBarColor: Colors.pink, // Status bar
        ),
      ),
      body: Shortcuts(
        shortcuts: {
          LogicalKeySet(LogicalKeyboardKey.audioVolumeUp): IncrementIntent(),
          LogicalKeySet(LogicalKeyboardKey.audioVolumeDown): DecrementIntent(),
          LogicalKeySet(LogicalKeyboardKey.arrowUp): IncrementIntent(),
          LogicalKeySet(LogicalKeyboardKey.arrowDown): DecrementIntent(),
        },
        child: Actions(
          actions: {
            DecrementIntent:
                CallbackAction<DecrementIntent>(onInvoke: (intent) {
              setState(() {
                _counter--;
              });
            }),
            IncrementIntent:
                CallbackAction<IncrementIntent>(onInvoke: (intent) {
              setState(() {
                _counter++;
              });
            })
          },
          child: Focus(
            autofocus: true,
            child: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text(
                    'You have pushed the button this many times:',
                  ),
                  Text(
                    '$_counter',
                    style: Theme.of(context).textTheme.headline4,
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```
2. Press VolumeUp or VolumeDown key

**Expected results:** 
2 . Counter variable should increase / decrease 

The weird thing is: when you connect HW keyboard to device (like BT keyboard) and press ArrowUp / ArrowDown - they works. And now when you use volume keys - they also works...
**Actual results:** 
2. Volume of device is changing, counter variable is not affected

**Flutter Doctor output:**

```
[✓] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1237], locale pl-PL)
    • Flutter version 2.5.2 at C:\Users\MarcinKo\Documents\ANDROID_SDK\Flutter_sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (16 hours ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\MarcinKo\Documents\ANDROID_SDK
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code, 64-bit edition (version 1.60.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19043.1237]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 94.0.4606.71
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 94.0.992.31
```

</details>

**Comment by darshankawar** [comment] 2021-10-01 12:50
@Kozubi 
This seems to be similar / duplicate of https://github.com/flutter/flutter/issues/71144. Are you trying to run on an emulator ?
If so, check [this](https://github.com/flutter/flutter/issues/71144#issuecomment-735936110) issue comment.
You may follow-up in the original issue for further updates.

**Comment by Kozubi** [comment] 2021-10-01 13:00
> @Kozubi 
> This seems to be similar / duplicate of https://github.com/flutter/flutter/issues/71144. Are you trying to run on an emulator ?
> If so, check [this](https://github.com/flutter/flutter/issues/71144#issuecomment-735936110) issue comment.
> You may follow-up in the original issue for further updates.
> 
 I'm running this on physical device. Xiaomi Redmi Note 8 pro (Android 11)

And mentioned issue look the same. So feel free to close this...

**Comment by darshankawar** [comment] 2021-10-01 13:38
Closing this as duplicate.

**Closed by darshankawar** 2021-10-01 13:38 UTC
Labels: in triage
