### ISSUE TITLE
App process isn't terminating when closing

### ISSUE THREAD

**Issue by Aturex1** [flutter/flutter#154795] opened 2024-09-08 18:40 UTC
### Steps to reproduce

1. Run any flutter app in release mode (e. g. the code sample) with `flutter run --release`
2. Wait
3. Wait longer
4. Admit the app process (in terminal for example) isn't terminating

### Expected results

The terminal process is terminating when the app is closed. Somehow that happen in profile and debug mode.

### Actual results

The app process in the terminal isn't terminating.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: const Center(
        child: Text('Here could be anything'),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

\<No media necessary\>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on Fedora Linux 40 (Workstation Edition)
    6.10.6-200.fc40.x86_64, locale de_DE.UTF-8)
    • Flutter version 3.24.1 on channel stable at ~/.local/share/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (13 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at ~/.local/share/android-sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = ~/.local/share/android-sdk/
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (Red_Hat-17.0.12.0.7-2) (build 17.0.12+7)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.6 (Fedora 18.1.6-3.fc40)
    • cmake version 3.28.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 40 (Workstation Edition)
      6.10.6-200.fc40.x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment] 2024-09-09 10:14
Thanks for the report @Aturex1 
Can you provide us error log that might be useful to properly debug this further ? 
Also, I see from your flutter doctor -v that you might be seeing this behavior in desktop, but does it occur in any other platforms as well (ex: mobile, web) using Linux ?

**Comment by Aturex1** [comment] 2024-09-09 18:55
There are no error logs, the terminal process just isn't stopping after the app is closed (see screenshot below). The issue also occurred on Android.

![grafic](https://github.com/user-attachments/assets/b3416b6d-332b-4c56-bbb8-e7a3f08bb568)
That's what happens after the app is closed (↑). On Linux and Android is the same behavior observed.

**Comment by darshankawar** [comment] 2024-09-10 06:07
@Aturex1 Ok.
Are you saying that, once you run on desktop release mode for example, and if you close the app, the console doesn't update and still shows the blinking cursor, as below:

<img width="705" alt="Screenshot 2024-09-10 at 11 36 25 AM" src="https://github.com/user-attachments/assets/347a8d6f-0c42-4805-b1e1-009001554967">

**Comment by darshankawar** [comment] 2024-09-10 06:08
> * Wait
> * Wait longer

Is there any concrete time we have to wait until it starts showing the behavior ?

**Comment by Aturex1** [comment] 2024-09-10 21:16
> Are you saying that, once you run on desktop release mode for example, and if you close the app, the console doesn't update and still shows the blinking cursor, as below:

That's what happens (↑), pressing q works as expected. It doesn't depend on how long you wait, the process in the terminal isn't stopping even after a long time.
It is just that, the app window closes properly. Strangely, in release and profile the terminal process quits when the app window is closed

**Comment by darshankawar** [comment] 2024-09-11 05:34
Most likely similar / duplicate of https://github.com/flutter/flutter/issues/58459, so please follow-up in it for further updates.
Closing in favor of it.

**Closed by darshankawar** 2024-09-11 05:34 UTC
Labels: in triage

**Comment by Aturex1** [comment] 2024-09-11 13:45
Right, but it also occurred on Android.
