### ISSUE TITLE
Issue with a TextField in Flutter for Web

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#41238] opened 2019-09-25 00:41 UTC
This occurs when I hot reload.

```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for FocusNode:
Assertion failed: org-dartlang-app:///packages/flutter/src/rendering/box.dart:1678:12
ssert(h
"RenderBox was not laid out: RenderEditable#7c095 NEEDS-LAYOUT NEEDS-PAINT"

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
package:build_web_compilers/src/dev_compiler/dart_sdk.js 3991:11   throw_
package:build_web_compilers/src/dev_compiler/dart_sdk.js 3937:15   assertFailed
package:flutter/src/rendering/box.dart 1678:12                     get size
package:flutter/src/widgets/editable_text.dart 1656:40             [_updateSizeAndTransform]
package:flutter/src/widgets/editable_text.dart 1350:7              [_openInputConnection]
package:flutter/src/widgets/editable_text.dart 1375:7              [_openOrCloseInputConnectionIfNeeded]
package:flutter/src/widgets/editable_text.dart 1631:5              [_handleFocusChanged]
package:flutter/src/foundation/change_notifier.dart 206:21         notifyListeners
package:flutter/src/widgets/focus_manager.dart 765:5               [_notify]
package:flutter/src/widgets/focus_manager.dart 1331:11             [_applyFocusChange]
package:build_web_compilers/src/dev_compiler/dart_sdk.js 41669:13  _microtaskLoop
package:build_web_compilers/src/dev_compiler/dart_sdk.js 41675:13  _startMicrotaskLoop
package:build_web_compilers/src/dev_compiler/dart_sdk.js 38072:9   <fn>
```

**Comment by escamoteur** [comment] 2019-09-25 08:19
Hi,

please provide us the output of `flutter doctor` and give us more context. Show us please the full error message and your code.

Are you experience this on windows or mac?

Otherwise we cannot help you.

**Comment by DaveShuckerow** [comment] 2019-09-25 17:25
Thanks for the doctor reminder, @escamoteur.

```
$ flutter doctor                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.4-pre.46, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (3 available)

! Doctor found issues in 3 categories.
```

**Comment by nturgut** [comment] 2019-09-25 17:47
Thanks for filing the issue.

Since _updateSizeAndTransform method is on the line 1656, I am assuming this is not the latest code in the master. We resolved an editing issue yesterday. Can you please sync to the latest code?

If the issue persists, can you share code for the text editing widget you are using? It doesn't have to be exact. I am particularly curious to see the focusNode and autofocus properties.

Another question, is there a text editing related problem on the UI when you run flutter first time (I mean before using the hot restart)?

**Comment by DaveShuckerow** [comment] 2019-10-01 20:29
Hi Nurhan, the code is here: https://github.com/flutter/devtools/pull/1106/files

I'm still seeing the issue.  It should be reproducible by pulling down that repo and `flutter run -d chrome` from packages/devtools_flutter.

**Comment by nturgut** [comment] 2019-10-01 22:28
I see. Thanks for the reply. 

I think this is a hot reload problem we encountered before. I will update the main issue soon. 

Duplicate of https://github.com/flutter/flutter/issues/41284

**Closed by nturgut** 2019-10-01 22:28 UTC
Labels: a: text input, customer: webeap, ☸ platform-web
