### ISSUE TITLE
InputMethodManager( 5324): showSoftInput() view=io.flutter.embedding.android.FlutterView{88bd8f0 VFE...... .F...... 0,0-1080,2340 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT

### ISSUE THREAD

**Issue by vignesh235** [flutter/flutter#120068] opened 2023-02-06 09:20 UTC
I'm facing this issue during type. It becomes prolonged.

**Comment by danagbemava-nc** [comment] 2023-02-06 10:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/117995.

**Closed by danagbemava-nc** 2023-02-06 10:55 UTC
Labels: in triage
