### ISSUE TITLE
debug mode works fine,but 'flutter build apk ' command exit with error code -1073741819

### ISSUE THREAD

**Issue by hyz1992** [flutter/flutter#21900] opened 2018-09-15 02:04 UTC
In flutter version beta 0.5.1, my project has been working normally for months.
but when I upgrade flutter to beta 0.6.0 or higher,it can't build release apk any more,and debug mode works fine.

flutter build apk
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleRelease'...
Dart snapshot generator failed with exit code -1073741819
Snapshotting exited with non-zero exit code: -1073741819

my configure is correct, and a helloworld can also build release apk well, or if I relpase my project't "lib/main.dart" with helloworld's, it build success too.

and if I switch to beta 0.5.1 again, build release success too.

maybe there is something different with dart 2.0,caused this problem?

**Comment by mraleph** [comment] 2018-09-15 06:33
For now treating this as a duplicate of #21685.

**Comment by mraleph** [comment] 2018-09-15 06:34
Duplicate of #21685

**Closed by mraleph** 2018-09-15 06:34 UTC

**Comment by chankruze** [comment] 2018-12-25 07:36
@mraleph but this is for android not ios.
the details of problem is [here](https://github.com/flutter/flutter/issues/15722#issuecomment-449763529).

**Comment by mraleph** [comment] 2018-12-25 11:44
@chankruze it does not matter whether it is iOS or Android - `gen_snapshot` is used in both cases. 

This bug has been fixed - if you are still seeing it and you are using new version of flutter - then you most likely have discovered a new bug. 

Thus please don't add comments to already closed bugs, instead please file a new bug and provide information necessary to reproduce it (e.g. output of `flutter doctor -v` and detailed steps to reproduce the bug).  

Thank you.
