### ISSUE TITLE
CamcorderProfile.get is deprecated in Android 31

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#89609] opened 2021-09-07 21:33 UTC
The camera plugin is using [CamcorderProfile.get](https://developer.android.com/reference/android/media/CamcorderProfile#get(int,%20int)) which is deprecated in Android 31.

Logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836758871796798737/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_3_4/test_stdout

cc @stuartmorgan

**Comment by TahaTesser** [comment] 2021-09-08 07:34
Reproduction https://github.com/flutter/flutter/issues/89578#issuecomment-914260875
Duplicate of https://github.com/flutter/flutter/issues/89578

**Closed by TahaTesser** 2021-09-08 07:34 UTC
Labels: platform-android, plugin, p: first party, p: camera, passed first triage
