### ISSUE TITLE
Paypal Integration with Webview in flutter

### ISSUE THREAD

**Issue by aTeamSolace** [flutter/flutter#61813] opened 2020-07-19 10:01 UTC
I tried almost from the last 3-4 days for PayPal integration I'm new in flutter development I need to add PayPal payment gateway I know there is no special plugin available for Paypal. so I decided to call a web view for PayPal. But still, which URL I should call for that or which code I should add for showing PayPal method I don't know if anyone has a solution please let me know. 
thanks in advance

**Comment by TahaTesser** [comment] 2020-07-20 11:49
duplicate of https://github.com/flutter/flutter/issues/61790

**Closed by TahaTesser** 2020-07-20 11:49 UTC
