### ISSUE TITLE
TextField has bug when input space

### ISSUE THREAD

**Issue by findtheway10** [flutter/flutter#43699] opened 2019-10-29 05:53 UTC
## Steps to Reproduce

1. source code 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('title'),
        ),
        body: Center(
          child:
          TextField(
            maxLines: null,
          ),
        ),
      ),
    );
  }
}
```

2. capture
![ezgif-1-62c8a3cc74ac](https://user-images.githubusercontent.com/13478322/67740881-be680700-fa5a-11e9-8d72-6224f290e641.gif)

When I type in the middle of a post,
If I enter a space, the position of the cursor does not change.
I'm not sure if this is a bug.
Is there a way I can fix it?

**Target Platform: android
**Target OS version: android api 25
**Devices: google pixel 2

## Logs

```
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[√] Connected device (1 available)
    • google Pixel 2 • emulator-5554 • android-x86 • Android 5.1.1 (API 22)
```

**Comment by BondarenkoStas** [comment] 2019-10-29 14:00
@findtheway10 thank you for the report! Reproduced it on stable and master.

**Comment by jason-simmons** [comment] 2019-11-11 19:46
Duplicate of https://github.com/flutter/flutter/issues/40095

**Closed by jason-simmons** 2019-11-11 19:46 UTC
Labels: a: text input, f: material design, framework, ▣ platform-android
