### ISSUE TITLE
MaterialLocalizations.of should not return null under a MaterialApp

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#13617] opened 2017-12-15 22:42 UTC
Example snippet that crashes when the flutter_localization package is not included:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      locale: const Locale('he'),
      home: new Scaffold(
        appBar: new AppBar(),
        body: new Container(),
        drawer: new Container(),
      ),
    );
  }
}
```

This can currently crash with:
```
I/flutter ( 3887): The following NoSuchMethodError was thrown building AppBar(dirty, state: _AppBarState#5d89b):
I/flutter ( 3887): The getter 'openAppDrawerTooltip' was called on null.
I/flutter ( 3887): Receiver: null
I/flutter ( 3887): Tried calling: openAppDrawerTooltip
I/flutter ( 3887): 
I/flutter ( 3887): When the exception was thrown, this was the stack:
I/flutter ( 3887): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter ( 3887): #1      _AppBarState.build (package:flutter/src/material/app_bar.dart:370:54)
...
```

The crash is because without the localization package `MaterialLocalizations.of(context)` is null when we do (in app_bar.dart):
```
          tooltip: MaterialLocalizations.of(context).openAppDrawerTooltip,
```

**Comment by Hixie** [comment] 2017-12-15 22:52
We should assert that `locale` is one of the locales in `supportedLocales`.

**Comment by amirh** [comment] 2017-12-15 22:56
+1 for that.
In this case I just wanted to minimize the snippet so removed every line I could :)

To be clear, this one line longer snippet crashes the same way:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      locale: const Locale('he'),
      supportedLocales: const <Locale>[const Locale('he')],
      home: new Scaffold(
        appBar: new AppBar(),
        body: new Container(),
        drawer: new Container(),
      ),
    );
  }
}
```

**Comment by Hixie** [comment] 2017-12-16 02:42
We should also assert if you specify a `supportedLocales` that doesn't have a delegate provided that can service that locale. :-)

**Comment by kengorab** [comment] 2018-06-06 02:44
This is still not yet fixed, correct? I'm working in an application that I created a few days ago and I'm trying to display a bottom modal sheet (following [this](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/modal_bottom_sheet_demo.dart) example), and I'm getting a similar error:

```
E/flutter (25415): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (25415): NoSuchMethodError: The getter 'modalBarrierDismissLabel' was called on null.
E/flutter (25415): Receiver: null
E/flutter (25415): Tried calling: modalBarrierDismissLabel
E/flutter (25415): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
E/flutter (25415): #1      showModalBottomSheet (package:flutter/src/material/bottom_sheet.dart:286:53)
```

In fact, when I evaluate just

```
MaterialLocalizations.of(context);
```

I get `null`. Is there any workaround in the meantime while this issue gets addressed?

**Comment by HansMuller** [comment] 2018-06-06 14:55
This has not been fixed (yet), I will try resolve it this week.

The null is a usually a symptom of using an unsupported locale, i.e. a lcoale that's not in the app's supportedLocales list. Is that what's happening in your case? 

The planned fix is to improve the error reorting. Not to fallback to a supported but possibly incomprehensible language.

**Comment by kengorab** [comment] 2018-06-06 15:05
Hmm, in my example I hadn't specified any locales. Do I need to? I was only planning on supporting en-US for now, so I didn't specify anything. In the localization docs I see that I can pass parameters to the `MaterialApp` in order to specify supported locales.

If we need to have locales properly configured in order to show bottom modal sheets, I think some documentation around that would be good, considering they seem pretty disparate to me.

**Comment by Hixie** [comment] 2018-06-06 15:26
@kengorab Please file a new bug, I think what you're seeing may be different.

**Comment by kengorab** [comment] 2018-06-06 23:37
@Hixie I submitted: #18254

**Comment by ilikerobots** [comment] 2018-06-11 14:27
If anyone is encountering this while supporting a locale that is not one of Flutter's currently supported locales, the "fix" is to implement a LocalizationsDelegate for that locale, as documented by @HansMuller  in https://github.com/flutter/flutter/pull/12645

**Comment by jonahwilliams** [comment] 2018-11-27 15:01
The above snippet now provides the following warning but doesn't error yet. Of course if you don't actually provide the locale it will crash immediately after.

```
Performing hot restart...                                        
Restarted application in 1,506ms.
I/flutter (18779): ════════
I/flutter (18779): Warning: This application's locale, he, is not supported by all of its
I/flutter (18779): localization delegates.
I/flutter (18779): > A MaterialLocalizations delegate that supports the he locale was not found.
I/flutter (18779): See https://flutter.io/tutorials/internationalization/ for more
I/flutter (18779): information about configuring an app's locale, supportedLocales,
I/flutter (18779): and localizationsDelegates parameters.
```

**Comment by HansMuller** [comment] 2018-11-27 16:35
It will not crash immediately afterwards (otherwise many tests would crash) unless your code tries to retreive a localized string.

**Comment by jonahwilliams** [comment] 2018-11-27 17:05
In this case I had the drawer open on iOS which called the modalDismissBarrier (and failed to find Localizations). So not right after, you're correct

**Comment by TahaTesser** [comment] 2020-03-25 13:24
Hi @amirh 
Are you still experiencing this issue? I couldn't reproduce it 

### Code Sample 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      locale: const Locale('he'),
      title: 'Material App',
      home: new Scaffold(
        appBar: new AppBar(),
        body: new Container(),
        drawer: new Container(),
      ),
    );
  }
}
```

### Logs
```
Launching lib/main.dart on SM M305F in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         1.6s
✓ Built build/app/outputs/apk/debug/app-debug.apk.
D/FlutterView(21109): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@5974154
D/FlutterActivity(21218): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(21218): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(21218): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(21218): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(21218): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@5974154
D/FlutterActivityAndFragmentDelegate(21218): Executing Dart entrypoint: main, and sending initial route: /
Syncing files to device SM M305F...                                     
 5,000ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on SM M305F is available at: http://127.0.0.1:52186/CLbc7LOUoiA=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
D/InputMethodManager(21218): prepareNavigationBarInfo() DecorView@a7d419a[MainActivity]
D/InputMethodManager(21218): getNavigationBarColor() -855310
V/InputMethodManager(21218): Starting input: tba=com.example.stable_flutter ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(21218): startInputInner - Id : 0
I/InputMethodManager(21218): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(21218): Input channel destroyed: 'ClientS', fd=85
D/ViewRootImpl@1dddd66[MainActivity](21218): stopped(true) old=false
D/SurfaceView(21218): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{ee8c7f9 V.E...... ........ 0,0-1080,2301} of ViewRootImpl@1dddd66[MainActivity]
D/SurfaceView(21218): surfaceDestroyed callback.size 1 #1 io.flutter.embedding.android.FlutterSurfaceView{ee8c7f9 V.E...... ........ 0,0-1080,2301}
W/libEGL  (21218): EGLNativeWindowType 0x7515193010 disconnect failed
D/SurfaceView(21218): remove() io.flutter.embedding.android.FlutterSurfaceView{ee8c7f9 V.E...... ........ 0,0-1080,2301} Surface(name=SurfaceView - com.example.stable_flutter/com.example.stable_flutter.MainActivity@ee8c7f9@0)/@0xb9c05d8
D/FlutterView(21218): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@5974154
E/ViewRootImpl@1dddd66[MainActivity](21218): Surface is not valid.
D/ViewRootImpl@1dddd66[MainActivity](21218): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(21218): prepareNavigationBarInfo() DecorView@a7d419a[MainActivity]
D/InputMethodManager(21218): getNavigationBarColor() -855310

```

Thank you

**Comment by Lurzapps** [comment] 2020-11-13 14:18
════════
I/flutter (22601): Warning: This application's locale, de, is not supported by all of its
I/flutter (22601): localization delegates.
I/flutter (22601): > A MaterialLocalizations delegate that supports the de locale was not found.
I/flutter (22601): See https://flutter.dev/tutorials/internationalization/ for more
I/flutter (22601): information about configuring an app's locale, supportedLocales,
I/flutter (22601): and localizationsDelegates parameters.
I/flutter (22601): 
════════
I get this message and cant use various widgets because Localizations.of<MaterialLocalizations>(context, MaterialLocalizations) returns null. German is listed as a supported locale, and i have registered supportedLanguages as well as localizationDelegates. As main app I use the MaterialApp, so why do I receive an error?! Cant fix this since days.

**Comment by asashour** [comment] 2021-07-11 19:46
Could we have an updated sample code? I get errors regarding `localeResolutionCallback` in the last sample provided.

**Comment by darshankawar** [comment] 2022-12-13 11:57
I tried below code sample that shows a warning in the console log which indicates what we need to do in order to fix the error:

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    locale: const Locale('he'),
    supportedLocales: const <Locale>[const Locale('he')],
    home: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Container(),
        drawer: Container(),
      ),
    );
  }
}

```

</details>

<details>
<summary> console log </summary>

```
======== Exception caught by widgets ===============================================================
The following message was thrown:
Warning: This application's locale, he, is not supported by all of its localization delegates.

• A MaterialLocalizations delegate that supports the he locale was not found.
• A CupertinoLocalizations delegate that supports the he locale was not found.

The declared supported locales for this app are: he

See https://flutter.dev/tutorials/internationalization/ for more information about configuring an app's locale, supportedLocales, and localizationsDelegates parameters.
====================================================================================================

======== Exception caught by widgets ===============================================================
The following message was thrown:
Warning: This application's locale, he, is not supported by all of its localization delegates.

• A MaterialLocalizations delegate that supports the he locale was not found.
• A CupertinoLocalizations delegate that supports the he locale was not found.

The declared supported locales for this app are: he

See https://flutter.dev/tutorials/internationalization/ for more information about configuring an app's locale, supportedLocales, and localizationsDelegates parameters.
====================================================================================================

```

</details>

As we can see from the console log, it doesn't throw the null error as originally described, but a warning on how to proceed to fix the error. So the fix for it per the log is to add below inside `MaterialApp()` and running updated code sample then does not show the warning or any error.

```
localizationsDelegates: [
      GlobalMaterialLocalizations.delegate,
      GlobalCupertinoLocalizations.delegate
    ],    
```

<details>
<summary> fixed code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';


void main() {
  runApp(MaterialApp(
    localizationsDelegates: [
      GlobalMaterialLocalizations.delegate,
      GlobalCupertinoLocalizations.delegate
    ],
    locale: const Locale('he'),
    supportedLocales: const <Locale>[const Locale('he')],
    home: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Container(),
        drawer: Container(),
      ),
    );
  }
}

```

</details>

With above, I am going ahead and closing this as fixed, as the original error reported that threw null log isn't occuring anymore.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.9 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (12 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-6.0.pre.23, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.7.0-6.0.pre.23 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 04ee5926a2 (76 minutes ago), 2022-12-12 19:42:23 -0800
    • Engine revision 290f3a35ee
    • Dart version 3.0.0 (build 3.0.0-19.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Closed by darshankawar** 2022-12-13 11:57 UTC
Labels: severe: crash, framework, f: material design, a: internationalization, has reproducible steps, P4, found in release: 1.21
