### ISSUE TITLE
High latency on frames on linux desktop

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#88996] opened 2021-08-26 20:55 UTC
STEPS TO REPRODUCE
1. `flutter create issue88996`
2. `cd issue88996`
3. `flutter run -d linux --profile`
4. Wait for the app to launch.
5. Tap the floating action button a few times.
6. Open DevTools using the URL from the console.
7. Click on one of the last frames and observe the time between build and raster.

For me, this reliably shows 10+ms between when the build thread finishes its work and the raster thread begins.

![2021-08-26-135256_2489x1237_scrot](https://user-images.githubusercontent.com/551196/131034499-1570b6ff-0100-429b-a6d2-725cd5ff5a43.png)

Sample profile: [profile.json](https://github.com/flutter/flutter/files/7062672/profile.json.txt)

**Comment by jason-simmons** [comment] 2021-08-28 02:06
Did a quick profile and noticed that the platform/raster thread was spending significant time in rendering callbacks for GTK widgets representing composited layers (`fl_gl_area_draw`).  So the raster thread may not be available to respond immediately after a frame finishes building.

The latency between frame building and rasterization was minimal in the simpler FlRenderer implementation used prior to  https://github.com/flutter/engine/commit/f94cf140c52c0cc3769d9281d5579e935886fbac

I'm wondering if it would be feasible to switch to a rendering approach with less overhead in the common case where there is only one layer.

**Comment by huanghongxun** [comment] 2021-09-02 13:02
GTK requires us to draw textures on platform thread. And Flutter composites layers on Raster Thread. To reduce cross-thread operations, we joined the platform and raster thread as simple solution. If the embedder API allows us to create an onscreen and an offscreen buffer, we can fully decouple platform thread and raster thread.

For another solution, we may decouple platform/raster thread by RasterThreadMerger. But according to what @jason-simmons said, `fl_gl_area_draw` may consume significant time, which will still blocks raster thread using RasterThreadMerger. We may find out why `fl_gl_area_draw` takes unexpectedly long time first.

**Comment by knopp** [comment] 2021-09-02 13:16
FWIW, on macOS, there is separate raster thread, but actually presenting the surface is done on platform thread (AppKit is generally not thread safe). We schedule the present callback on platform thread and then block raster thread until it is presented. This is handled by `FlutterResizeSynchronizer`. I think similar approach could be used in Linux embedder if sharing raster and platform thread causes too much latency. That said, this would still block the raster thread until frame is presented, but it has the advantage of not hogging platform thread during rasterization.

I think right now there's only one `FlGlArea` widget anyway, since platform views support is not complete on linux yet. The `fl_gl_area_draw` "just" blits an opengl texture, not quite sure why it would show as a bottleneck, unless it's using the slow path perhaps (reading the pixels)?

**Comment by huanghongxun** [comment] 2021-09-02 13:29
`fl_gl_area_draw` is backed with `gdk_cairo_draw_from_gl`, which is hardware accelerated and should be fast.

I found that on macOS, you can simply call `swapBuffers` and `[CATransaction commit]` to submit new buffers. But GTK requires us to draw GL textures in its draw callback. We should invoke draw first, and do finally draw at next tick. The buffer should be kept valid until next Flutter frame, because GTK may invoke our draw callback at any time (may be invoked by system-wide redraw), we must make sure that the buffer is still valid at that time. So platform thread should block raster thread when draw_callback is invoked no matter it is triggered by Flutter or system.

**Comment by TahaTesser** [comment] 2021-09-06 12:49
<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.193, on Pop!_OS 21.04
    5.11.0-7633-generic, locale en_US.UTF-8)
    • Flutter version 2.6.0-1.0.pre.193 at /home/taha/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0c5431d99c (10 hours ago), 2021-09-05 22:31:02 -0400
    • Engine revision b9c633900e
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 21.04
      5.11.0-7633-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
	
</details>

**Comment by cbracken** [comment] 2021-09-21 23:01
@robert-ancell have you had any time to have a look?

**Comment by cbracken** [comment] 2021-10-05 23:41
@chinmaygarde in case he's got thoughts (or can think of someone else who may have thoughts).

**Comment by cbracken** [comment] 2021-10-13 20:25
@robert-ancell mentioned he's begun looking at this and is working with others at Canonical to identify a way forward.

**Comment by Hixie** [comment] 2021-10-15 03:11
`uname -a` says `Linux burmese 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by robert-ancell** [comment] 2021-10-15 03:48
I've got a [branch] that logs the delays and durations of tasks and rendering - this might be useful for anyone with large delays to see if that shows anything interesting.

What I do see here is a long "queue delay", which is the time between us requesting a draw from GTK and the draw being performed. But that is expected as we're not aligned to vsync so that delay is likely to be between 0-16ms. 

I am sometimes seeing a log "task delay", which is the time between Flutter requesting a task on the GTK thread and it being run. But not enough to cause consistent frame issues.

**Comment by hansihe** [comment] 2021-11-22 11:39
@robert-ancell using your branch, I am seeing the following delays:

```
Nov 22 11:35:37 task delay=18ms
Nov 22 11:35:37 draw duration=11ms
Nov 22 11:35:37 task delay=11ms
Nov 22 11:35:37 task delay=6ms
Nov 22 11:35:37 draw duration=11ms
Nov 22 11:35:37 task delay=11ms
Nov 22 11:35:37 draw duration=10ms
Nov 22 11:35:37 task delay=17ms
Nov 22 11:35:37 draw duration=10ms
Nov 22 11:35:37 draw duration=10ms
Nov 22 11:35:37 task delay=8ms
Nov 22 11:35:37 draw duration=11ms
Nov 22 11:35:37 task delay=9ms
Nov 22 11:35:37 task delay=18ms
Nov 22 11:35:37 draw duration=11ms
Nov 22 11:35:37 task delay=6ms
Nov 22 11:35:37 draw duration=10ms
Nov 22 11:35:37 task delay=10ms
Nov 22 11:35:37 draw duration=10ms
Nov 22 11:35:37 task delay=17ms
Nov 22 11:35:37 draw duration=10ms
Nov 22 11:35:37 draw duration=10ms
Nov 22 11:35:37 task delay=8ms
Nov 22 11:35:37 draw duration=11ms
```

I would be happy to provide any other info if needed.

**Comment by hansihe** [comment] 2021-12-14 15:40
I profiled this a little bit, and it seems like a lot of time is spent in `gdk_gl_context_upload_texture`. 

(The attached screenshot is from a ~15s profile)

![2021-12-14T16:31:12,426745975+01:00](https://user-images.githubusercontent.com/843730/146028758-d25f1d9c-f2b7-4b79-8a62-1f70e15b254e.png)

I wonder if some format is being used that makes it fall back to some cpu copy? Here is the codepath from `gdk_gl_context_upload_texture` I believe is being run:

```
      glPixelStorei (GL_UNPACK_ALIGNMENT, 4);
      glPixelStorei (GL_UNPACK_ROW_LENGTH, cairo_image_surface_get_stride (image_surface) / 4);

      glTexImage2D (texture_target, 0, GL_RGBA, width, height, 0, GL_BGRA, GL_UNSIGNED_INT_8_8_8_8_REV,
                    cairo_image_surface_get_data (image_surface));

      glPixelStorei (GL_UNPACK_ROW_LENGTH, 0);
```

Confused as to why the profiler wouldn't pick up the `glTexImage2D` symbol name, but as it's the only other function being called I assume that is the correct one.

Anything below here is mostly a dead end for the profiler since it's from `libnvidia-eglcore.so.470.63.01`, which is proprietary.

**Comment by hansihe** [comment] 2021-12-14 15:43
A function deep below `gdk_gl_context_upload_texture` in the depths of the nvidia driver retires like 54 billion instructions, which might again point at some blitting loop happening?

**Comment by alexmercerind** [comment] 2022-02-14 08:12
Hey there!

I rarely comment on issues where I don't have much knowledge, but this issue seems bit serious to me.

I notice a large number of framedrops when running Flutter on x11 (unfortunately many DEs like the elementaryOS's Pantheon still doesn't have Wayland support).
Frame-drops are most noticeable (from my observation) when loading new images e.g. I scroll in a long `ListVIew` full of images & there is substantial amount of lag in the app. On Wayland however, the experience is butter smooth.

Thankyou.

**Comment by kenvandine** [comment] 2022-02-16 19:35
> @jpnurmi my understanding from @kenvandine is that a fix for this will be rolling out?

More information on this can be found at https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1960947

**Comment by jpnurmi** [comment] 2022-02-16 19:43
The fix is actually for #75948. I wish we had a fix for this too. :)

**Comment by hansihe** [comment] 2022-02-16 19:47
@alexmercerind I am running with the HeaderBar disabled and still have the same issue. There might be several distinct issues that manifest similarly?

**Comment by kenvandine** [comment] 2022-02-16 20:03
> 

@cbracken sorry for the confusion, I didn't realize there were two distinct headerbar issues :)

**Comment by whiskeyPeak** [comment] 2023-01-11 17:46
I think I may have identified the issue. I profiled a Flutter app running a simple animation with perf and got this as a result:

![Screenshot from 2023-01-11 04-17-49](https://user-images.githubusercontent.com/73116038/211876776-c2fe2a34-a10a-45ec-96d7-07671a43bba1.png)

From the screenshot, a lot of time is spent in the ```XGetVisualInfo``` function. I did some further searching online and found this issue in GTK related to gdk_x11_gl_context: https://gitlab.gnome.org/GNOME/gtk/-/issues/4704. That specific code path seems to loop over an GLXFBConfig array every frame to fetch the given the ```glXGetVisualFromFBConfig```, which is used to get the ```XGetVisualInfo```. We could store that value in a static variable and circumvent  that loop for all future frames.

It would seem that on some X11 systems, this code path is taken which leads to the slow down. I'd be interested in seeing if people experiencing this issue also see a really high ```XGetVisualInfo``` usage on their system. Also from what I can tell from this thread, this issue has only affected X11 backends?

Possible solutions here include:
- Implementing our own gdk_cairo_draw_from_gl() function so that we have immediate control over which code path to choose from.
- Fix the issue in GTK and wait for distros to roll in the changes.

CC @robert-ancell @jpnurmi fyi @kenvandine :)

**Comment by whiskeyPeak** [comment] 2023-04-01 00:04
I locally tested a patch for the constant looping of the ```GLXFBConfig``` array and can still reproduce the lag. I think the best solution would be to implement our own texture drawing function.

**Comment by whiskeyPeak** [comment] 2023-05-31 22:36
I've opened up a PR on the GDK side of things that removes the painfully slow X11 code-path. With this change, Flutter apps on my computer are noticeably smoother and also utilise ~2-3 times less CPU. :)

Given that this is all OpenGL related, I wonder if we could implement our own texture rendering function so that these benefits can be experienced immediately instead of having to wait for each distro to ship a patched version of GTK.

**Comment by whiskeyPeak** [comment] 2023-06-01 11:22
The fix has been merged at https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6042.

**Comment by gnprice** [comment] 2023-06-19 03:53
@whiskeyPeak Great work! It looks like that fix should be in the next GTK 3.24.x release, which would be GTK 3.24.39.

Does the bug also exist in GTK 4?

What do you think it would look like to try to work around the issue within Flutter? If there's a clean way to do so, that could be useful in case some users' distros might not take the update until a future major distro release. But if a workaround would require a big hack, then it's probably best to leave it for distros to update.

**Comment by whiskeyPeak** [comment] 2023-06-19 05:48
> Does the bug also exist in GTK 4?

It's hard to test this given that Flutter doesn't make use of GTK4 at the moment, but given that I can't reproduce the lag with an OpenGL Area in a traditional GTK4 app, the fact that the slow function has been removed from the X11 backend and that the backend now makes use of EGL, I think it's fair to say that the issue most likely isn't present anymore.

> What do you think it would look like to try to work around the issue within Flutter? If there's a clean way to do so, that could be useful in case some users' distros might not take the update until a future major distro release. But if a workaround would require a big hack, then it's probably best to leave it for distros to update.

I tried to implement a custom `gdk_cairo_draw_from_gl()` function that would be specific to flutter's needs, but GDK doesn't expose the required functions/headers for that to be possible unfortunately. 

If we wanted users who are affected by this issue to get the fix quicker, we could open up patches over at different distros, though this isn't an area that i am familiar with.

**Comment by gnprice** [comment] 2023-06-20 03:51
> given […], I think it's fair to say that the issue most likely isn't present anymore.

Cool, makes sense.


> If we wanted users who are affected by this issue to get the fix quicker, we could open up patches over at different distros, though this isn't an area that i am familiar with.

Probably the first step is to wait for an upstream GTK 3.x release that has the fix. From [recent history](https://gitlab.gnome.org/GNOME/gtk/-/tags) it looks like those happen every couple of months or so.

Then after that's been out for a few weeks, you can look at a couple of major distros and see if any of them haven't yet taken the update, and if not then open issues in their respective trackers. (For example one can find the Debian changelog [here](https://packages.debian.org/source/bookworm/gtk+3.0), and see if it mentions taking your patch.)

**Comment by cbracken** [comment] 2023-08-29 22:04
@Hixie with all OS updates installed on your machine, is this still an issue?

**Closed** 2023-09-19 22:08 UTC
Labels: waiting for customer response, engine, c: performance, platform-linux, a: desktop, perf: speed, has reproducible steps, P1, found in release: 2.6, team-desktop, triaged-desktop, multiteam-retriage-candidate

**Comment by gnprice** [comment] 2024-02-17 04:26
Following up briefly on this: [GTK 3.24.39 released](https://gitlab.gnome.org/GNOME/gtk/-/tags/3.24.39) in December. It presumably contains @whiskeyPeak's fix, unless for some reason that got reverted.

And that in turn has been propagating into distros. For example [Debian testing now has](https://packages.debian.org/source/trixie/gtk+3.0) GTK 3.24.41.

So at this point I'd expect that users of fast-updating distros are seeing the benefit of this fix already, and others will get it at the pace of their respective distros.
