### ISSUE TITLE
[Android][Samsung]: app throws `SamsungSmartSuggestion stopped working` error while opening and closing keyboard.

### ISSUE THREAD

**Issue by Miiite** [flutter/flutter#98505] opened 2022-02-15 15:08 UTC
## Steps to Reproduce

On a Samsung Galaxy S20FE, run the sample provided:
[focus_node.zip](https://github.com/flutter/flutter/files/8072222/focus_node.zip)

- Start the app
- Focus on the TextField
- Play with the floating button to open and close the keyboard
- Kill the app
- Start it again, and repeat the above operation

About 50% of the time, I end up with a crash from Samsung's SmartSuggestion service:

![Screenshot_20220215-155927](https://user-images.githubusercontent.com/475526/154089428-86bc92cf-2af7-4d79-8d05-edb40222ebeb.jpg)

This service error **does not** crashes my app. But it is not a behavior we were seeing in flutter 2.8.1.

 
```
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale
    en-FR)
    • Flutter version 2.10.1 at /Users/adrien.padol/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (6 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/adrien.padol/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • SM A510F (mobile)  • 33005c841a9393a7                     • android-arm •
      Android 7.0 (API 24)
    • iPhone 13 (mobile) • 01FB688F-C492-46BE-B50D-625063182646 • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by Miiite** [comment] 2022-02-16 08:09
@andesappal Both files are available in the sample project I provided.
Here is the android gradle:
```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
And here is the app gradle file:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.focus_node"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

But these are the default values after doing a `flutter create` with flutter 2.10.1

**Comment by darshankawar** [comment] 2022-02-16 08:53
I verified this behavior on Samsung S10 device and was able to replicate it only first time, wherein, it shows below:

<img width="323" alt="Screenshot 2022-02-16 at 2 20 16 PM" src="https://user-images.githubusercontent.com/67046386/154228742-f2d42984-6079-4829-8c33-4ecec8bf6269.png">

Upon subsequent tries, I wasn't able to replicate it consistently.
also tried on latest master after uninstalling the app and redoing the steps, but wan't able to replicate on it.

Below is the SmartSuggestion setting on my phone:

<img width="331" alt="Screenshot 2022-02-16 at 2 20 24 PM" src="https://user-images.githubusercontent.com/67046386/154228910-fa436210-4b1c-4190-982f-542844c95dc6.png">



Keeping it open and labeling it for further insights from the team.

```
[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

I'll try later on previous stable version to see if it was replicable or not per author's comment and to check if it has regressed or not.

/cc @LongCatIsLooong

**Comment by wonpyohong** [comment] 2022-02-26 20:13
I have the same issue when focus to TextField.

first time focus -> replicate (I close the dialog by back button)
subsequent focus -> cannot replicate
retry after several minutes -> replicate

This is my TextField
```
TextField(
  minLines: 1,
  maxLines: 1000,
  enableSuggestions: false,        // it can replicate if true
  controller: controller.textEditingController,
  decoration: InputDecoration(
  border: const OutlineInputBorder(),
  focusedBorder: OutlineInputBorder(borderSide: BorderSide(width: 2, color: AppColor.primary.withOpacity(0.7)))),
  autocorrect: false,                // it can replicate if false
)
```

My phone is Galaxy S21.
```
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6 20G165 darwin-x64, locale ko-KR)
    • Flutter version 2.10.2 at /Users/wonpyohong/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (8일 전), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/wonpyohong/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/wonpyohong/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • SM G991N (mobile)            • R3CR603S38Z               • android-arm64  • Android 11 (API 30)
    • AOSP on IA Emulator (mobile) • emulator-5554             • android-x86    • Android 9 (API 28) (emulator)
    • Wonpyo의 iPhone 11 (mobile)   • 00008030-000E0CCA36B9802E • ios            • iOS 15.3 19D50
    • Chrome (web)                 • chrome                    • web-javascript • Google Chrome 98.0.4758.109
    ! Error: Wonpyo의 iPhone 11 is busy: Preparing the watch for development via Wonpyo의 iPhone 11. Xcode will continue when Wonpyo의 iPhone 11 is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by MikolajPorebny** [comment] 2022-03-01 17:38
Samsung S10



    
    TextField(
        enabled: widget.siecModel.zakresPrac == "D"
            ? false
            : true,
        onChanged: (String newValue) async {
          saveToPref();
        },
        //focusNode: focusNode,
        keyboardType: TextInputType.text,
        minLines: 1,
        maxLines: 1,
        textInputAction: TextInputAction.done,
        style: TextStyles.normalMediumStyleBlack(
            context),
        controller: nakladkaPoController,
        decoration: InputDecoration(
          contentPadding: EdgeInsets.all(
              MediaQuery.of(context).size.width / 56),
          //hintText: "",
          //hintStyle: TextStyles.inputStyleBlack(context),
          filled: true,
          fillColor: Colors.white,
          disabledBorder: OutlineInputBorder(
              borderRadius: new BorderRadius.circular(
                  MediaQuery.of(context).size.width /
                      56),
              borderSide:
                  BorderSide(color: Colors.grey)),
          focusedBorder: OutlineInputBorder(
            borderRadius: new BorderRadius.circular(
                MediaQuery.of(context).size.width /
                    56),
            borderSide:
                BorderSide(color: Colors.black),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: new BorderRadius.circular(
                MediaQuery.of(context).size.width /
                    56),
            borderSide:
                BorderSide(color: Colors.black),
          ),
        ),
      ),



[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19041.1415], locale pl-PL)
    • Flutter version 2.10.2 at C:\Projekty\Flutter\flutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (11 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\mporebny\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run path/to/sdkmanager --install "cmdline-tools;latest"
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mporebny\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1415]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by ken-ng-esotec** [comment] 2022-03-12 08:11
We are getting this issue and this is affecting our production users making the app look bad when it's not within our control. Can you please fix this?

**Comment by frankpepermans** [comment] 2022-03-14 21:31
Also facing this issue in production, the keyboard on my Samsung S21 is behaving erradic.

Aside from the suggestions crash, I also find that sometimes focus to the text input is not correctly set: eg tap on the text input, the caret is now showing, but any keyboard text input does not update the text field.

I have to tap the text input again, and only then keyboard input suddenly works.

**Comment by Kirill-Karmazin** [comment] 2022-03-19 19:39
> I faced same issue on my S10e and some Samsung phone(I don't know the model).... and I solved it changing TextField to TextFormField (and only add controller) Try it!

May God bless you and your children and children of your children! It worked.

**Comment by kostov** [comment] 2022-04-06 11:04
> and I solved it changing TextField to TextFormField (and only add controller) Try it!

God bless you again! It really helps.

**Comment by YarostheLaunchpadder** [comment] 2022-04-16 22:41
This is still an issue, how can I fix this?

**Comment by justinmc** [comment] 2022-04-29 23:04
I tried to reproduce this on my old S6 running Android 7 with no luck.  Maybe it doesn't even have smart suggestions though.  

I'll try to get ahold of a newer Samsung device.  I'm really curious why this would happen with TextField but not TextFormField...

**Comment by PawanFyers** [comment] 2022-05-16 09:32
Same errors are faced by many users in our app.

Sorry I don't have reproduction steps.

![image](https://user-images.githubusercontent.com/99729739/168563015-d075e7ab-51cf-4232-a593-56fbc93d4aee.png)
.

**Comment by YarostheLaunchpadder** [comment] 2022-05-16 10:11
I solved it changing TextField to TextFormField

**Comment by SoftWyer** [comment] 2022-05-18 08:18
Attached is the log file and associated stack trace seen when this service crashes. Whilst it looks to be due to some poor bounds checking by Samsung, it's interesting that the Flutter SDK 2.10.x change has exacerbated this.

<details><summary>Log File</summary>

```
I/flutter (12997): INFO: 2022-05-17 11:30:02.741981: RegistrationServiceImpl has been constructed
D/InputMethodManager(12997): prepareNavigationBarInfo() DecorView@482c8ce[MainActivity]
D/InputMethodManager(12997): getNavigationBarColor() -16777216
V/InputMethodManager(12997): Starting input: tba=com.myapp ic=io.flutter.plugin.editing.InputConnectionAdaptor@79f1ec7 mNaviBarColor -16777216 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(12997): startInputInner - Id : 0
I/InputMethodManager(12997): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(12997): Input channel constructed: 'ClientS', fd=119
D/InputTransport(12997): Input channel destroyed: 'ClientS', fd=120
D/InputMethodManager(12997): SSI - flag : 0 Pid : 12997 view : com.myapp
D/InputMethodManager(12997): prepareNavigationBarInfo() DecorView@482c8ce[MainActivity]
D/InputMethodManager(12997): getNavigationBarColor() -16777216
D/InputMethodManager(12997): SSI - flag : 0 Pid : 12997 view : com.myapp
D/InputMethodManager(12997): prepareNavigationBarInfo() DecorView@482c8ce[MainActivity]
D/InputMethodManager(12997): getNavigationBarColor() -16777216
E/myapp             (12997): No package ID 24 found for ID 0x245a3c5c.
E/myapp             (12997): No package ID 24 found for ID 0x245a3c5c.
I/AssistStructure(12997): Flattened final assist data: 476 bytes, containing 1 windows, 3 views
D/InputConnectionAdaptor(12997): The input method toggled cursor monitoring on
D/InputConnectionAdaptor(12997): The input method toggled text monitoring on
E/AndroidRuntime(15779): FATAL EXCEPTION: main
E/AndroidRuntime(15779): Process: com.samsung.android.smartsuggestions, PID: 15779
E/AndroidRuntime(15779): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime(15779):    at com.samsung.android.smartsuggestions.assist.AssistStructureParser.getHint(AssistStructureParser.java:154)
E/AndroidRuntime(15779):    at com.samsung.android.smartsuggestions.assist.AssistStructureParser.addAutofillableFields(AssistStructureParser.java:54)
E/AndroidRuntime(15779):    at com.samsung.android.smartsuggestions.assist.AssistStructureParser.addAutofillableFields(AssistStructureParser.java:68)
E/AndroidRuntime(15779):    at com.samsung.android.smartsuggestions.assist.AssistStructureParser.addAutofillableFields(AssistStructureParser.java:68)
E/AndroidRuntime(15779):    at com.samsung.android.smartsuggestions.assist.AssistStructureParser.getAutofillableFields(AssistStructureParser.java:43)
E/AndroidRuntime(15779):    at com.samsung.android.smartsuggestions.assist.AssistStructureParser.getHint(AssistStructureParser.java:248)
E/AndroidRuntime(15779):    at com.samsung.android.smartsuggestions.services.AugmentedAutofillService.onFillRequest(AugmentedAutofillService.java:77)
E/AndroidRuntime(15779):    at android.service.autofill.augmented.AugmentedAutofillService.handleOnFillRequest(AugmentedAutofillService.java:284)
E/AndroidRuntime(15779):    at android.service.autofill.augmented.AugmentedAutofillService.access$200(AugmentedAutofillService.java:74)
E/AndroidRuntime(15779):    at android.service.autofill.augmented.AugmentedAutofillService$AugmentedAutofillServiceImpl.lambda$onFillRequest$2(AugmentedAutofillService.java:118)
E/AndroidRuntime(15779):    at android.service.autofill.augmented.-$$Lambda$AugmentedAutofillService$AugmentedAutofillServiceImpl$rg4bgWPXG7Diy30M48ekR52l-AY.accept(Unknown Source:40)
E/AndroidRuntime(15779):    at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:423)
E/AndroidRuntime(15779):    at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
E/AndroidRuntime(15779):    at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/AndroidRuntime(15779):    at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(15779):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(15779):    at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(15779):    at android.app.ActivityThread.main(ActivityThread.java:8456)
E/AndroidRuntime(15779):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15779):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
E/AndroidRuntime(15779):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
D/InsetsSourceConsumer(12997): setRequestedVisible: visible=true, type=13, host=com.myapp/com.myapp.MainActivity, from=android.view.InsetsSourceConsumer.show:229 android.view.InsetsController.showDirectly:1432 android.view.InsetsController.controlAnimationUnchecked:1105 android.view.InsetsController.applyAnimation:1412 android.view.InsetsController.show:957 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6006 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 android.app.ActivityThread.main:8456 java.lang.reflect.Method.invoke:-2 
D/SurfaceControl(12997): hide : mNativeObject = -5476376613083089216 - sc.mNativeObject = -5476376613620682752 - Surface(name=Surface(name=aacd20b InputMethod)/@0x84762bf - animation-leash)/@0xc4a0e92
D/SurfaceControl(12997): nativeSetFlags Done : Surface(name=Surface(name=aacd20b InputMethod)/@0x84762bf - animation-leash)/@0xc4a0e92
D/SurfaceControl(12997): hide : mNativeObject = -5476376613083168240 - sc.mNativeObject = -5476376613620682752 - Surface(name=Surface(name=aacd20b InputMethod)/@0x84762bf - animation-leash)/@0xc4a0e92
D/SurfaceControl(12997): nativeSetFlags Done : Surface(name=Surface(name=aacd20b InputMethod)/@0x84762bf - animation-leash)/@0xc4a0e92
I/SurfaceControl(12997): release : mNativeObject = -5476376613620682752 - Surface(name=Surface(name=aacd20b InputMethod)/@0x84762bf - animation-leash)/@0xc4a0e92 / android.view.ViewRootInsetsControllerHost.lambda$releaseSurfaceControlFromRt$0:216 android.view.-$$Lambda$ViewRootInsetsControllerHost$3v_KSpxQXUSxSM3D_S6T5-aZKoQ.onFrameDraw:2 android.view.ViewRootImpl.lambda$registerRtFrameCallback$0:1606 android.view.-$$Lambda$ViewRootImpl$IReiNMSbDakZSGbIZuL_ifaFWn8.onFrameDraw:2 
I/SurfaceControl(12997): nativeRelease nativeObject s[-5476376613620682752]
I/SurfaceControl(12997): nativeRelease nativeObject e[-5476376613620682752]
I/SurfaceControl(12997): release : mNativeObject = -5476376613620618240 - Surface(name=Surface(name=aacd20b InputMethod)/@0x84762bf - animation-leash)/@0x2a1a8e2 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
I/SurfaceControl(12997): nativeRelease nativeObject s[-5476376613620618240]
I/SurfaceControl(12997): nativeRelease nativeObject e[-5476376613620618240]
I/SurfaceControl(12997): release : mNativeObject = -5476376613620686896 - Surface(name=Surface(name=a8bd98c NavigationBar0)/@0xc466989 - animation-leash)/@0x763e460 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
I/SurfaceControl(12997): nativeRelease nativeObject s[-5476376613620686896]
I/SurfaceControl(12997): nativeRelease nativeObject e[-5476376613620686896]
I/SurfaceControl(12997): release : mNativeObject = -5476376613620618576 - Surface(name=Surface(name=2d59c76 StatusBar)/@0x2450f42 - animation-leash)/@0x75dad19 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
I/SurfaceControl(12997): nativeRelease nativeObject s[-5476376613620618576]
I/SurfaceControl(12997): nativeRelease nativeObject e[-5476376613620618576]
I/ViewRootImpl@2190e69[MainActivity](12997): MSG_WINDOW_FOCUS_CHANGED 0 1
```

</details>

**Comment by lual98** [comment] 2022-06-05 15:52
I experienced this issue with a Samsung Galaxy A50 with Android 11 using a SearchDelegate. I suppose this happened because the SearchDelegate uses a TextField somewhere inside it

**Comment by letsar** [comment] 2022-06-08 08:04
Hey, I don't have a Samsung device to test it, so would need someone to test an idea.
I noticed that the `autofillHints` property has not the same default value in `TextFormField` and `TextField`. In `TextFormField` it null and it's set to an empty list in `TextField`. 
Can someone test to use a `TextField` and set explicitly `autofillHints` to null to test if there is still an issue with smartsuggestions ?

**Comment by letsar** [comment] 2022-06-09 12:01
Setting `autofillHints` to null is working great on our side. It seems to be a wanted decision (see https://github.com/flutter/flutter/pull/86312), so I won't make a PR to change the default value. We should tell Samsung to fix this issue on their side.
Does anyone knows how to contact the team responsible for this app?

**Comment by alhamri** [comment] 2022-06-25 14:04
> I faced same issue on my S10e and some Samsung phone(I don't know the model).... and I solved it changing TextField to TextFormField (and only add controller) Try it!

Thank you, worked for me

**Comment by Andy-Vmire** [comment] 2022-07-05 03:46
I'm facing the same issue. My log is attached.
My phone Samsung A71
[log.txt](https://github.com/flutter/flutter/files/9043071/log.txt)
.

**Comment by LongCatIsLooong** [comment] 2022-07-06 05:16
This is already patched from One UI 4.1, which had been released at early 2022. Closing.

**Closed by LongCatIsLooong** 2022-07-06 05:16 UTC
Labels: a: text input, e: device-specific, platform-android, engine, has reproducible steps, P4, found in release: 2.10, e: Samsung

**Comment by Siriwatb** [comment] 2022-07-07 04:38
> I faced same issue on my S10e and some Samsung phone(I don't know the model).... and I solved it changing TextField to TextFormField (and only add controller) Try it!

May the Force Be with You

**Comment by chejdj** [comment] 2022-07-20 04:17
@LongCatIsLooong  Hi, Could you please cherry-pick to Flutter stable channel ?
