### ISSUE TITLE
Help me to fix this Error

### ISSUE THREAD

**Issue by Ryxusnine** [flutter/flutter#48115] opened 2020-01-03 09:32 UTC
```
E/flutter ( 8445): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter ( 8445):
F/flutter ( 8445): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
√ Built build\app\outputs\apk\debug\app-debug.apk.
E/flutter ( 8591): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter ( 8591):
F/flutter ( 8591): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
Lost connection to device.
```

**Comment by VladyslavBondarenko** [comment] 2020-01-03 09:58
Hi @Ryxusnine 
Does [this comment](https://github.com/flutter/flutter/issues/21719#issuecomment-567857835) seems as solution to your problem?
Also you can search for your problem among posted earlier issues (for example [this one](https://github.com/flutter/flutter/issues/23645)).
It's difficult to identify exactly your issue on the only provided info.
Thank you

**Comment by pk3199** [comment] 2020-01-14 07:12
Hi @VladyslavBondarenko 

The problem is the **declaration of assets name with white space**. Flutter reads the sentence with underscore easily then with white space. Try declaring the **assets name with underscore** and neglect the usage of white space in between the name.
And while debugging it shows the same error in the debug console yet it is just a cache file of error loaded while using that application. Wait for the app to load in the emulator. The application will work perfectly.

**Comment by TahaTesser** [comment] 2020-02-10 13:14
Hi @Ryxusnine 
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you

**Closed by TahaTesser** 2020-02-10 13:14 UTC
Labels: waiting for customer response
