### ISSUE TITLE
camera and video_player plugins crash when used in add-to-app module

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#45755] opened 2019-11-28 05:52 UTC
I want to add add flutter to my exist app with camera and video_player; but which caused my app crashed;
my flutter is in the dev channel;

brokens both on dev[1.12.15] channel and master channel;

[✓] Flutter (Channel master, v1.12.16-pre.32, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.12.16-pre.32 at /opt/google/flutter
    • Framework revision 714650d7e4 (4 hours ago), 2019-11-27 20:54:32 -0500
    • Engine revision 4bdd15cd54
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/google/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /opt/google/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • COL AL10 • VBJDU18725002458 • android-arm64 • Android 9 (API 28)

the broken stack of camea is 
```
    --------- beginning of crash
2019-11-28 12:56:49.492 20515-20515/cn.plaso.userinnermodule E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.plaso.userinnermodule, PID: 20515
    java.lang.BootstrapMethodError: Exception from call site #94 bootstrap method
        at io.flutter.plugins.camera.CameraPlugin.onAttachedToActivity(CameraPlugin.java:71)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.attachToActivity(FlutterEnginePluginRegistry.java:308)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:179)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:418)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

video_player exception;
```
    Process: cn.plaso.userinnermodule, PID: 26370
    java.lang.RuntimeException: Unable to destroy activity {cn.plaso.userinnermodule/io.flutter.embedding.android.FlutterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugins.videoplayer.VideoPlayerPlugin$FlutterState.stopListening()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5176)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5195)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugins.videoplayer.VideoPlayerPlugin$FlutterState.stopListening()' on a null object reference
        at io.flutter.plugins.videoplayer.VideoPlayerPlugin.onDetachedFromEngine(VideoPlayerPlugin.java:68)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:244)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:260)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:116)
        at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:267)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:468)
        at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:588)
        at android.app.Activity.performDestroy(Activity.java:7737)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1327)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5161)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5195) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by iapicca** [comment] 2019-11-28 08:14
Hi @wanjm 
if I understand correctly you are adding 
[video_player](https://pub.dev/packages/video_player) and [camera](https://pub.dev/packages/camera) 
to your app following this [documentation](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps).am I correct?
Thank you

**Comment by wanjm** [comment] 2019-11-28 11:23
almost correct! more detail;
1. I have a native APP ( Android and IOS);
2. we plan to use Flutter, so we pick one module A to start with;
3. module A need to use video_player and camera;  so we use the plugin from pub.dartlang.org;
4. everything is ok; then we add this module native APP according to that document;

**Comment by wanjm** [comment] 2019-11-30 05:05
```
    try {
      Class<?> generatedPluginRegistrant = Class.forName("io.flutter.plugins.GeneratedPluginRegistrant");
      Method registrationMethod = generatedPluginRegistrant.getDeclaredMethod("registerWith", FlutterEngine.class);
      registrationMethod.invoke(null, this);
    } catch (Exception e) {
      Log.w(TAG, "Tried to automatically register plugins with FlutterEngine ("
          + this + ") but could not find and invoke the GeneratedPluginRegistrant.");
    }
```
please print the exception details instead of say not find .

**Comment by askarsyzdykov** [comment] 2019-12-01 14:46
Same issue

**Comment by wanjm** [comment] 2019-12-03 00:37
@askarsyzdykov  try to react you project and submodule and run again;

currently, my app doesn't crash any more, I still need to check every plugin works as expected;

**Comment by matthew-carroll** [comment] 2020-01-30 03:41
@wanjm in your last comment you mentioned that your project no longer crashes. Is your problem gone?

@askarsyzdykov are you still seeing a problem on your end?

**Comment by askarsyzdykov** [comment] 2020-01-30 04:12
@matthew-carroll  nope

**Comment by matthew-carroll** [comment] 2020-02-07 23:12
I'm going to close this issue under the assumption that the problem is solved. If it's not, please re-open.

**Closed by matthew-carroll** 2020-02-07 23:12 UTC
Labels: a: existing-apps, engine, p: camera, p: video_player, plugin, severe: crash, waiting for customer response, ▣ platform-android
