### ISSUE TITLE
flutter web run on mobile show blank page( waitForActivation(reg.installing ?? reg.waiting);   Uncaught SyntaxError: Unexpected token '?')

### ISSUE THREAD

**Issue by adhope** [flutter/flutter#85362] opened 2021-06-26 02:25 UTC
I run flutter build web  and put the result in  back server.
when i visit the website in windows chrome . all is ok.
But when I visit in mobie chrome , it run  to a blank page error.
i show the console with chrome://inspect/#devices and i get this error.
Uncaught SyntaxError: Unexpected token '?'
the error code is 
![image](https://user-images.githubusercontent.com/28976170/123499306-66870680-d668-11eb-9f56-9ee2d3597bbb.png)
is there hava some solution for this?I'm not familiar with serviceWorker and it is not used in my project.
thanks.

**Comment by JAVPHP** [comment] 2021-07-03 08:23
`if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              if (reg.installing == null) waitForActivation(reg.waiting)    // << Modified here
              else waitForActivation(reg.installing);                                 // << Modified here
              //waitForActivation(reg.installing ?? reg.waiting);              // << Modified here
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }`

**Comment by JAVPHP** [comment] 2021-07-03 08:23
if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              if (reg.installing == null) waitForActivation(reg.waiting)    // << Modified here
              else waitForActivation(reg.installing);                                 // << Modified here
              //waitForActivation(reg.installing ?? reg.waiting);              // << Modified here
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }

**Comment by maheshmnj** [comment] 2021-07-06 05:37
Hi @adhope,
Thanks for filing the issue could you please provide a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) with the exact steps to reproduce the issue, This  will help to better investigate the issue.

Thank you.

**Comment by andrew-tpz** [comment] 2021-07-15 11:46
I faced with the same issue. As I can see, flutter generates code `waitForActivation(reg.installing ?? reg.waiting); ` in index.html, but **JS doens't have '??' operator**. 

Steps to reproduce:
1. Create new flutter project in Android Studio
2. Run "flutter build web" in terminal
3. See index.html in output folder at line 67 - wrong JS syntax.

flutter doctor -v output:
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1052], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] Connected device (4 available)

• No issues found!

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1052], locale ru-RU)
    • Flutter version 2.2.3 at D:\Program Files\flutter_sdk
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

...

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
...

**Comment by maheshmnj** [comment] 2021-07-15 12:05
Hi @andrew-tpz, Thanks for the details could you also share the logs.
Thank you.

**Comment by adhope** [comment] 2021-07-17 04:18
> ```
> if (!reg.active && (reg.installing || reg.waiting)) {
>     // No active web worker and we have installed or are installing
>     // one for the first time. Simply wait for it to activate.
>     if (reg.installing == null) waitForActivation(reg.waiting)    // << Modified here
>     else waitForActivation(reg.installing);                                 // << Modified here
>         //waitForActivation(reg.installing ?? reg.waiting);              // << Modified here
>     } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
>               // When the app updates the serviceWorkerVersion changes, so we
>               // need to ask the service worker to update.
>               console.log('New service worker available.');
>               reg.update();
>               waitForActivation(reg.installing);
>     } else {
>          // Existing service worker is still good.
>          console.log('Loading app from service worker.');
>           loadMainDartJs();
>   }
> ```

it is right,maybe this code need backwards  compatible .

**Comment by maheshmnj** [comment] 2021-07-19 06:20
The issue is reproducible on the stable and the master channel, Here's a flutter[ counter app deployed to github pages](https://maheshmnj.github.io/counter) The app fails to load in both mobile and desktop and chrome browsers. The generated files to this app can be [found here ](https://github.com/maheshmnj/maheshmnj.github.io/tree/master/counter)

<details>

<summary>build/web/index.html</summary>

```
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
  -->
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="flutter_application_new">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <title>flutter_application_new</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    var serviceWorkerVersion = '3743490212';
    var scriptLoaded = false;
    function loadMainDartJs() {
      if (scriptLoaded) {
        return;
      }
      scriptLoaded = true;
      var scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js';
      scriptTag.type = 'application/javascript';
      document.body.append(scriptTag);
    }

    if ('serviceWorker' in navigator) {
      // Service workers are supported. Use them.
      window.addEventListener('load', function () {
        // Wait for registration to finish before dropping the <script> tag.
        // Otherwise, the browser will load the script multiple times,
        // potentially different versions.
        var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
        navigator.serviceWorker.register(serviceWorkerUrl)
          .then((reg) => {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener('statechange', () => {
                if (serviceWorker.state == 'activated') {
                  console.log('Installed new service worker.');
                  loadMainDartJs();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              waitForActivation(reg.installing ?? reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
          });

        // If service worker doesn't succeed in a reasonable amount of time,
        // fallback to plaint <script> tag.
        setTimeout(() => {
          if (!scriptLoaded) {
            console.warn(
              'Failed to load app from service worker. Falling back to plain <script> tag.',
            );
            loadMainDartJs();
          }
        }, 4000);
      });
    } else {
      // Service workers not supported. Just drop the <script> tag.
      loadMainDartJs();
    }
  </script>
</body>
</html>
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

```
[✓] Flutter (Channel master, 2.4.0-1.0.pre.149, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.4.0-1.0.pre.149 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d71c0eb1d8 (10 days ago), 2021-07-09 06:01:04 -0400
    • Engine revision 024cc455fe
    • Dart version 2.14.0 (build 2.14.0-293.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2021-07-19 07:50
@adhope @andrew-tpz, 
I deployed the [counter app on netify](https://fluttercounter.netlify.app/)  and I could see the app running, could you please try deploying it on netlify and see if that works for you on desktop and mobile Chrome browsers.

**Comment by andrew-tpz** [comment] 2021-07-19 08:08
I can't deploy, but in my case I deployed app on local server and it worked on my computer, but didn't work on another two computers. When I patched index.html by removing "??", app worked on all three computers.

I think, this line of code is not executed in some cases.

**Comment by adhope** [comment] 2021-07-19 08:32
@maheshmnj 
I run on google chrome on mobile phone and inspect on desktop chrome.this is the result.
![image](https://user-images.githubusercontent.com/28976170/126128704-542031ef-7f41-4c96-bc65-6f8a0fff023c.png)
this is the detail.
![image](https://user-images.githubusercontent.com/28976170/126129020-a9cf72e9-ca16-46f3-9c3d-3933b7a065eb.png)

**Comment by maheshmnj** [comment] 2021-07-19 09:20
This looks like a browser issue and not flutter specific issue. Can you also try on different browsers e.g the built-in edge chromium browser.

Here is the output on my side in the chrome browser.

![image](https://user-images.githubusercontent.com/31410839/126135910-3bc259b0-c342-412f-9590-389a216a4951.png)

**Comment by adhope** [comment] 2021-07-19 09:23
Have you tried it with Chrome on mobile？I have no problem with the computer side of the browser.

**Comment by maheshmnj** [comment] 2021-07-19 09:44
Yes it works fine there too. 

<img src="https://user-images.githubusercontent.com/31410839/126140220-071a2d9c-7879-482e-a960-ae88f32e5c42.jpg" width="350"/>

**Comment by maheshmnj** [comment] 2021-07-19 09:46
Can you please share more details 

- the version of your mobile chrome browser
-  the name of the phone and the os version

**Comment by adhope** [comment] 2021-07-19 09:48
![微信图片_20210719174823](https://user-images.githubusercontent.com/28976170/126141027-40bee983-689b-4cf8-979f-65354cde5bb6.png)

**Comment by adhope** [comment] 2021-07-19 09:50
it have chiniese  ,but maybe you can guess to understand it.

**Comment by maheshmnj** [comment] 2021-07-19 11:27
Could you please [try this app](https://flutterhtml.netlify.app/#/) built using the [html renderer](https://flutter.dev/docs/development/tools/web-renderers)

**Comment by adhope** [comment] 2021-07-20 05:31
![image](https://user-images.githubusercontent.com/28976170/126266829-7fb26e73-58c7-4cc7-9f26-ecf9431094c4.png)
same mistake

**Comment by maheshmnj** [comment] 2021-07-20 06:49
@adhope,  Please share your output of ```flutter doctor -v```

**Comment by adhope** [comment] 2021-07-23 07:48
![image](https://user-images.githubusercontent.com/28976170/126752198-d89ad8be-833d-4c1a-b81e-7cb5f2e6baeb.png)

**Comment by maheshmnj** [comment] 2021-07-23 08:59
@adhope can you please try upgrading to the latest stable version by running `flutter upgrade` and see if that helps.

Thank you.

**Comment by maheshmnj** [comment] 2021-07-23 09:57
@adhope, since you are not able to access these two flutter deployed apps in your browser which works fine on all browsers as verified on mobile/Desktop.

https://fluttercounter.netlify.app/#/ (auto)
https://flutterhtml.netlify.app/#/. (HTML renderer)

From this, I could infer that this is not an issue with flutter but probably with your browser or ISP or some other unknown issue. So I am going to close this issue as invalid if you disagree feel free to comment and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-07-23 09:57 UTC
Labels: in triage
