### ISSUE TITLE
Apple about to deny webview_flutter

### ISSUE THREAD

**Issue by jodymac** [flutter/flutter#39672] opened 2019-09-02 04:56 UTC
I'm running ```webview_flutter 0.3.10+2``` and have been uploading test builds everyday to testflight.  Now, today, September 1st, apple sent the message that I was using deprecated Uiwebviews.  It still took the test build for now, but looks like a deny will be coming soon.
```
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
```

**Comment by jodymac** [comment] 2019-09-02 05:52
Got it again using 0.3.13.  So it does the latest version will be affected too.

**Comment by BondarenkoStas** [comment] 2019-09-02 11:32
Duplicate of #39470, there is also comment https://github.com/flutter/flutter/issues/39470#issuecomment-526412518.
No worries, this is already known, hope it will be solved soon. So closing the issue, the above mentioned one will still contain the link to it.

**Closed by BondarenkoStas** 2019-09-02 11:32 UTC
