### ISSUE TITLE
Gallery videos do resume playing after placing app in background on Android

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#16576] opened 2018-04-14 00:04 UTC
To reproduce build the gallery on Android (only tested debug mode).  Open the videos tab, the place the app in the background.  Reopen the app, and you will see the blank screens below.  There are no additional error messages printed in the console.

Going back to the main gallery route and then re-opening videos makes them work again

<img width="400" src="https://user-images.githubusercontent.com/8975114/38761991-3c4a767a-3f3c-11e8-8627-4b1c91aa7e55.png"></img>

**Comment by eseidelGoogle** [comment] 2018-04-14 02:11
FYI @sigurdm

**Comment by eseidelGoogle** [comment] 2018-04-14 02:12
@mjohnsullivan Will this affect customer:gold?

**Comment by sigurdm** [comment] 2018-04-16 08:05
I was not able to reproduce this now on a Nexus 5x.
Do you have more details?
What steps do you take to put the gallery app in the background?
What is the output of `flutter doctor --verbose`?
Are you running the flutter gallery from the flutter folder?
What is the android device and version?

**Comment by jonahwilliams** [comment] 2018-04-16 17:07
After syncing to master and rebuilding this morning I am unable to reproduce this either - I think the issue should be closed.  Presumably I might have forgotten to completely rebuild at some point after updating the engine which caused the issue above

**Comment by sigurdm** [comment] 2018-04-17 07:47
I'll close it. Please reopen if you manage to reproduce again!

**Closed by sigurdm** 2018-04-17 07:47 UTC
Labels: video
