### ISSUE TITLE
[camera] 0.9.4+21 : Crash java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by albertocappellina** [flutter/flutter#104698] opened 2022-05-26 10:13 UTC
Hi guys,

   as stated in subject i've got a crash with camera plugin. Sadly i cannot reproduce it but it happens in some conditions i cant replicate yet.

The only information i got is that it occurs especially on Samsung phones, it does not happen on apple devices.

Here's the crashlog

Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:14)
       at io.flutter.plugins.camera.DartMessenger.lambda$error$1(DartMessenger.java)
       at io.flutter.plugins.camera.-$$Lambda$DartMessenger$krbe0U6WyCV-abVIr3C49ocj43E.run(-.java:8)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

So it's something related to a double reply but i can't understand how/why it's happening.

Can you provide me some help ?

Thanks
Alberto

**Comment by maheshmnj** [comment] 2022-05-26 12:18
Hi @albertocappellina, Thanks for filing the issue. Are you By any chance invoking two method channels at the same time? This seems to be same as https://github.com/flutter/flutter/issues/29092. Can you please share the output of `flutter doctor -v` along with a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to investigate further ?

**Comment by maheshmnj** [comment] 2022-05-27 06:19
Closing as a duplicate of https://github.com/flutter/flutter/issues/88598, Please follow up there for further updates.

**Closed by maheshmnj** 2022-05-27 06:19 UTC
Labels: waiting for customer response, in triage

**Comment by albertocappellina** [comment] 2022-05-27 12:44
Hi @maheshmnj ,  sadly i cannot send code because client doesn't allow me to.

I'm not sure i'm not calling at the same time 2 channels, i'm going to investigate more deeply on this hypothesis. 
Do you have any hint for me to check for this?

Thanks,
A

**Comment by maheshmnj** [comment] 2022-05-30 13:58
> Do you have any hint for me to check for this?

Not really,  Please follow up on the original issue for further updates and potential solutions.
