### ISSUE TITLE
I can't run the app flutter throws an error at Flutter Version 3.10.0 on channel stable

### ISSUE THREAD

**Issue by MrBoOodY** [flutter/flutter#126784] opened 2023-05-14 20:16 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run the app

### Actual results

flutter throwing an error

### Logs

<details>
<summary>Logs</summary>

```console

 
> : Error: The parameter 'details' of the method '_SelectableTextSelectionGestureDetectorBuilder.onTapDown' has type 'TapDownDetails', which does not match the corresponding type, 'TapDragDownDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onTapDown'.
selectable_text.dart:70
- 'TapDownDetails' is from 'package:flutter/src/gestures/tap.dart' ('/C:/src/flutter/packages/flutter/lib/src/gestures/tap.dart').
tap.dart:1
- 'TapDragDownDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
tap_and_drag_gestures.dart:1
Change to a supertype of 'TapDragDownDetails', or, for a covariant parameter, a subtype.
  void onTapDown(TapDownDetails details) {
                                ^
/C:/src/flutter/packages/flutter/lib/src/widgets/text_selection.dart:2043:8: Context: This is the overridden method ('onTapDown').
  void onTapDown(TapDragDownDetails details) {
       ^
: Error: The parameter 'details' of the method '_SelectableTextSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match the corresponding type, 'TapDragUpDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.
selectable_text.dart:94
- 'TapUpDetails' is from 'package:flutter/src/gestures/tap.dart' ('/C:/src/flutter/packages/flutter/lib/src/gestures/tap.dart').
tap.dart:1

- 'TapDragUpDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
tap_and_drag_gestures.dart:1
Change to a supertype of 'TapDragUpDetails', or, for a covariant parameter, a subtype.
  void onSingleTapUp(TapUpDetails details) {
                                  ^
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1
 

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19042.1526], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (5 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\BoOodY.DESKTOP-QF59TU1\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\BoOodY.DESKTOP-QF59TU1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1526]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment] 2023-05-15 09:23
@MrBoOodY 
Can you provide [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the reported error ?

**Comment by dreamchrome** [comment] 2023-05-15 16:34
I'm also experiencing this and having a tough time pinning it down. It only happens to one of my client's apps (primary a flutter web app). I can't reproduce it in a simple sample app just yet. The file it actually has an error with is:

/Users/dreamchrome/.pub-cache/hosted/pub.dev/macos_ui-1.12.2/lib/src/fields/text_field.dart

I've tried repairing the pub cache, cleaning the folder etc. I don't compile for Mac, just web.  My actual error is a little different:

`: Error: The parameter 'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onSingleTapUp' has type 'TapUpDetails', which does not match the corresponding type, 'TapDragUpDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onSingleTapUp'.
text_field.dart:108
- 'TapUpDetails' is from 'package:flutter/src/gestures/tap.dart' ('/users/dreamchrome/flutter/packages/flutter/lib/src/gestures/tap.dart').
tap.dart:1
- 'TapDragUpDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('/users/dreamchrome/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
tap_and_drag_gestures.dart:1
Change to a supertype of 'TapDragUpDetails', or, for a covariant parameter, a subtype.
  void onSingleTapUp(TapUpDetails details) {
                                  ^
/users/dreamchrome/flutter/packages/flutter/lib/src/widgets/text_selection.dart:2161:8: Context: This is the overridden method ('onSingleTapUp').
  void onSingleTapUp(TapDragUpDetails details) {
       ^

: Error: The parameter 'details' of the method '_TextFieldSelectionGestureDetectorBuilder.onDragSelectionEnd' has type 'DragEndDetails', which does not match the corresponding type, 'TapDragEndDetails', in the overridden method, 'TextSelectionGestureDetectorBuilder.onDragSelectionEnd'.
text_field.dart:130
- 'DragEndDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('/users/dreamchrome/flutter/packages/flutter/lib/src/gestures/drag_details.dart').
drag_details.dart:1

- 'TapDragEndDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('/users/dreamchrome/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
tap_and_drag_gestures.dart:1
Change to a supertype of 'TapDragEndDetails', or, for a covariant parameter, a subtype.
  void onDragSelectionEnd(DragEndDetails details) {
                                         ^
/users/dreamchrome/flutter/packages/flutter/lib/src/widgets/text_selection.dart:2839:8: Context: This is the overridden method ('onDragSelectionEnd').
  void onDragSelectionEnd(TapDragEndDetails details) {
       ^

Failed to compile application.`

**Comment by mahesawp45** [comment] 2023-05-16 03:49
I faced the same issue and managed to fix it by upgrading certain packages related to the problematic package or to something that was causing the error.

**Comment by darshankawar** [comment] 2023-05-16 05:26
@MrBoOodY 
Check above comments and see if any of the package you are using probably needs an update.

**Comment by dreamchrome** [comment] 2023-05-16 14:49
Turns out it was the adaptive_dialog package that needed updating to a prerelease version addressing this issue. The stable version may also fix this by now.

**Comment by MrBoOodY** [comment] 2023-05-16 20:23
somehow the app ran with me without any additional move, I Have just checked out the old pr of my project and then returned to the new pr and it worked. I don't know how but if it's working I'm happy.

**Comment by darshankawar** [comment] 2023-05-17 06:41
Closing based on above comments.

**Closed by darshankawar** 2023-05-17 06:41 UTC
Labels: in triage

**Comment by cyclotron3k** [comment] 2023-05-22 01:05
For me it was transitive dependencies of the `flutter_html` 2.x.x package that were causing the issue.

I was able to resolve the problem by using version `3.0.0-beta.1` of `flutter_html`.
