### ISSUE TITLE
Set max length is 3 digits, then type 4 digits. If I would like to delete whole current number in text input, I have to tap on button clear 4 times instead of 3 times as expected.

### ISSUE THREAD

**Issue by PhongNgo1776** [flutter/flutter#68582] opened 2020-10-20 08:27 UTC
- Set max length is 3 digits: LengthLimitingTextInputFormatter(3)
- Then I enter: "1234". Obviously, text input just show "123".
- But then I would like to delete "123" then:
Actual: I have to tap on button clear 4 times to delete whole available number ("123") in the text input.
Expected: Tap on button clear 3 times to delete whole available number ("123") in the text input.

**Comment by sidrao2006** [comment] 2020-10-20 08:37
Duplicate of #67898

Hey @PhongNgo1776 , I found an open issue addressing your problem. Please follow up there.

Thanks

**Comment by pedromassangocode** [comment] 2020-10-20 08:47
Hi @PhongNgo1776 
This issue is a duplicate of https://github.com/flutter/flutter/issues/67963 and it was already fixed by https://github.com/flutter/flutter/pull/67892.

The fix is on the latest master channel and it will be in the stable version of Flutter in the future.
Thank you

**Closed by pedromassangocode** 2020-10-20 08:47 UTC
