### ISSUE TITLE
[web] Severe memory leak on the latest `dev` and `master`  in debug mode

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#87100] opened 2021-07-27 11:09 UTC
Greetings, 

A few weeks back I upgraded from 2.3.0-17.0.pre.227 master to 2.3.0-17.0.pre.630 master and noticed a Flutter Web debug memory leak that would exceed 10GB after a few minutes and then I'd have to stop it and restart. I was busy and downgraded to 2.3.0-24.0.pre Dev channel and the issue went away again.

When I upgraded to 2.4.0-5.0.pre.79 master and now the latest 2.4.0-5.0.pre.203 the issue immediately reappears.

I realized last night that the issue is specifically related to redraws and having a sample app with just the circular progress indicator is enough to leak around 30-50MBytes / second! And the CPU is quite high as well. Chrome says the Java VM is stable around 60MB, the memory leak is in the Dart.exe itself whether called from command line or from Visual Studio. 

Sample code:
<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: const Center(
          child: CircularProgressIndicator(),
        ),
      ),
    );
  }
}`
``` 

</details>

**Issue seen with:**
<details> 
<summary>flutter doctor -v</summary> 
	
```console
[√] Flutter (Channel master, 2.4.0-5.0.pre.203, on Microsoft Windows [Version 10.0.17763.2061], locale en-IE)
    • Flutter version 2.4.0-5.0.pre.203 at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 738ce43d97 (4 hours ago), 2021-07-26 23:40:49 -0700
    • Engine revision 717d55cdd4
    • Dart version 2.14.0 (build 2.14.0-354.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.70

• No issues found!
```

</details>

**Issue also seen with:**

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[√] Flutter (Channel master, 2.4.0-5.0.pre.79, on Microsoft Windows [Version 10.0.17763.2061], locale en-IE)
    • Flutter version 2.4.0-5.0.pre.79 at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 72ae6e236e (11 days ago), 2021-07-16 13:46:03 -0400
    • Engine revision 26b6520a0c
    • Dart version 2.14.0 (build 2.14.0-321.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.70



**No Memory leak on 2.3.0-24.0.pre**

[√] Flutter (Channel dev, 2.3.0-24.0.pre, on Microsoft Windows [Version 10.0.17763.2061], locale en-IE)
    • Flutter version 2.3.0-24.0.pre at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2b9537c783 (6 weeks ago), 2021-06-11 22:11:53 -0700
    • Engine revision ddbac024d1
    • Dart version 2.14.0 (build 2.14.0-188.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.70
```

</details>

**Comment by maheshmnj** [comment] 2021-07-28 14:19
Hi @zambetpentru,
Could you please share how you are detecting these memory leaks and possibly both the actual and the expected results.

Thank you.

**Comment by zambetpentru** [comment] 2021-07-28 19:43
Greetings @maheshmnj,

I can see it in the Windows Task manager (and eventually the system will become unresponsive as it starts swapping like mad).

![image](https://user-images.githubusercontent.com/81489824/127385715-0526cac0-0d56-4fb2-90be-069e026f0710.png)

**Comment by maheshmnj** [comment] 2021-07-29 10:36
@zambetpentru  I believe this issue is related to https://github.com/flutter/flutter/issues/13203

**Comment by zambetpentru** [comment] 2021-07-30 07:07
Hi, I confirm the issue is still there with Flutter Clean.
It also is unrelated to the circular progress indicator I think, that was just a simple way to replicate the issue.

Are you seeing this on a Windows test machine?

**Comment by TahaTesser** [comment] 2021-07-30 14:16
Hi @zambetpentru 
Thanks for filing the issue!

I attempted to reproduce the issue on Windows 10 on the latest `beta, 2.4.0-4.2.pre` and ``, my memory usage doesn't go above 110MB, which is normal

![image](https://user-images.githubusercontent.com/48603081/127665946-c9357ae8-764e-471c-b956-af6932f7ccca.png)

|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.4.0-4.2.pre, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.4.0-4.2.pre at C:\Users\Taha\Code\flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f18b9281c2 (8 days ago), 2021-07-22 14:08:30 -0700
    • Engine revision 844c29f42a
    • Dart version 2.14.0 (build 2.14.0-301.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.55

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.5.0-2.0.pre.87, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.5.0-2.0.pre.87 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ade9f6a9f0 (9 hours ago), 2021-07-30 10:30:44 +0530
    • Engine revision 884e9dacb9
    • Dart version 2.14.0 (build 2.14.0-363.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio-preview\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio-preview
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19043.1110]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 92.0.4515.107
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 92.0.902.55

• No issues found!
```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by TahaTesser** [comment] 2021-07-30 15:38
Hi @zambetpentru 
I can reproduce the issue on the latest `dev` and `master`, memory usage increases drastically when any animation is on the web, doesn't happen on the windows app.

Reproduced on Linux (took almost all RAM), WIndows (About 5GB RAM), macOS (About 3.8GB RAM).


So I used a different example to be sure

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: AnimationRoute(),
    );
  }
}
class AnimationRoute extends StatefulWidget {
  @override
  AnimationRouteState createState() => AnimationRouteState();
}
class AnimationRouteState extends State<AnimationRoute> with SingleTickerProviderStateMixin {
  Animation<double> animation;
  AnimationController controller;
  initState() {
    super.initState();
    // Controller sets the animation duration
         // vsync sets a TickerProvider, the current State is mixed with SingleTickerProviderStateMixin is a TickerProvider
    controller = AnimationController(
        duration: Duration(seconds: 5),
        vsync: this //
    );
         // Tween sets the interval value of animation, animate () method passes in an Animation, and AnimationController inherits Animation
    animation = new Tween(begin: 100.0, end: 200.0).animate(controller);
    controller.repeat();
//    controller.repeat(reverse: true);
  }
  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
        animation: animation,
        builder: (BuildContext ctx, Widget child) {
          return Center(
            child: Container(
              color: Colors.green,
              alignment: Alignment.center,
              width: animation.value,
              height: animation.value,
              child: FloatingActionButton(
                  onPressed: (){
                    controller.stop();
                  },
                                     child: Text ('Stop')
              ),
            ),
          );
        }
    );
  }
  @override
  void dispose() {
         // release resources
    controller.dispose();
    super.dispose();
  }
}
``` 

</details>



|  `stable`  |  `beta`  | `dev` | `master` |
| :---: | :---: | :---: |:---: |
|  ✅  |   ✅  |  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.55

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel beta, 2.4.0-4.2.pre, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.4.0-4.2.pre at C:\Users\Taha\Code\flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f18b9281c2 (8 days ago), 2021-07-22 14:08:30 -0700
    • Engine revision 844c29f42a
    • Dart version 2.14.0 (build 2.14.0-301.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.55

• No issues found!
```

```console
[✓] Flutter (Channel dev, 2.5.0-1.0.pre, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.5.0-1.0.pre at C:\Users\Taha\Code\flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 184e5871be (4 days ago), 2021-07-26 04:38:02 -0400
    • Engine revision a877f6fed6
    • Dart version 2.14.0 (build 2.14.0-350.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio-preview\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio-preview
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19043.1110]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 92.0.4515.107
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 92.0.902.55

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.5.0-2.0.pre.87, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.5.0-2.0.pre.87 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ade9f6a9f0 (11 hours ago), 2021-07-30 10:30:44 +0530
    • Engine revision 884e9dacb9
    • Dart version 2.14.0 (build 2.14.0-363.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio-preview\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio-preview
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19043.1110]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 92.0.4515.107
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 92.0.902.55

• No issues found!
```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by ditman** [comment] 2021-07-30 17:47
@zambetpentru Can you also send `flutter doctor -v` of a revision that **worked well** for you? That way we can narrow down the culprit commit more easily.

**Comment by zambetpentru** [comment] 2021-07-30 20:00
Hi @ditman,

Here you go!

[√] Flutter (Channel dev, 2.3.0-24.0.pre, on Microsoft Windows [Version 10.0.17763.2061], locale en-IE)
    • Flutter version 2.3.0-24.0.pre at C:\Code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2b9537c783 (7 weeks ago), 2021-06-11 22:11:53 -0700
    • Engine revision ddbac024d1
    • Dart version 2.14.0 (build 2.14.0-188.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Omega\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Code\FlutterTesting\ChromeCORS.bat

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.70

• No issues found!

**Comment by ditman** [comment] 2021-07-30 20:18
Some data for bisection:

First known bad revision:

```
    • Framework revision 72ae6e236e (11 days ago), 2021-07-16 13:46:03 -0400
    • Engine revision 26b6520a0c
```

Last known good revision:

```
• Framework revision 2b9537c (7 weeks ago), 2021-06-11 22:11:53 -0700
• Engine revision ddbac024d1
```

**Comment by jason-simmons** [comment] 2021-07-30 20:35
I tried bisecting this, and it appears to have started with a Dart roll: https://github.com/flutter/engine/commit/ccec8b35ada48c64e81a8018ae0b4a8856e5c96d

**Comment by jason-simmons** [comment] 2021-07-30 20:56
Specifically this started with https://github.com/dart-lang/sdk/commit/c83eeac5b89ada105c6df3be75b54bce97d5de1b

@nshahan

**Comment by grouma** [comment] 2021-07-30 21:47
dart-lang/sdk@c83eeac is not the actual root cause since that PR only impacts logic run within Chrome. It does however enable this change: https://github.com/dart-lang/webdev/pull/1322

There isn't much we do different due that change. Instead of parsing a Webkit Inspection Protocol Event to send as a Dart VM Protocol event, we now parse a Built Value event in much the same way.

I have a suspicion that the memory leak is here: https://github.com/dart-lang/webdev/blob/9d10ec7de3d0b4a273edc99522483452bddd1282/dwds/lib/src/handlers/dev_handler.dart#L244

@davidmorgan is it possible that Built Value deserializer has a memory leak? As far as I can tell we don't hold onto the `message` or `data` objects otherwise.

**Comment by jason-simmons** [comment] 2021-07-31 00:33
The increase in memory usage is coming from the `LoggingRepository` in DDS
(see https://github.com/dart-lang/sdk/blob/master/pkg/dds/lib/src/stream_manager.dart#L121)

Flutter sends an event each time it renders a frame.  With the change in https://github.com/dart-lang/sdk/commit/c83eeac, each of these events results in calls to DWDS' `emitDebugEvent` hook and `ChromeProxyService.parseDebugEvent`.  `parseDebugEvent` then publishes the event to the `kExtension` event stream.

The DDS `StreamManager` has a set of streams that are associated with a `LoggingRepository`, and `kExtension` is one of these streams.  The `LoggingRepository` contains a ring buffer holding up to 10000 of these events.

The objects received on the event stream include a map containing a representation of the isolate.  This isolate map is a lot larger when generated by the code path added in https://github.com/dart-lang/sdk/commit/c83eeac.  So the total size of the buffered events adds up quickly.

@bkonyi

**Comment by jason-simmons** [comment] 2021-07-31 01:46
I tried patching DWDS' `ChromeProxyService.parseDebugEvent` to construct the event using `_inspector.isolateRef` instead of `_inspector.isolate`.

With that change the events in the stream contain the smaller version of the isolate map that had been used prior to https://github.com/dart-lang/sdk/commit/c83eeac

@grouma would that work?

**Comment by yjbanov** [comment] 2021-08-02 16:47
Thanks, @jason-simmons, for shaving this yak!

Setting P2 as this can make debug mode unusable for many people.

@grouma @sigmundch can we have someone on the Dart SDK team assigned to this issue? It seems to be purely a Dart SDK bug. Is @jason-simmons' [suggestion](https://github.com/flutter/flutter/issues/87100#issuecomment-890274257) a good fix or workaround that we can apply quickly?

**Comment by sigmundch** [comment] 2021-08-02 18:01
@nshahan and @annagrin should be able to help

**Comment by annagrin** [comment] 2021-08-02 19:24
I’ll look into that, thanks!

**Comment by annagrin** [comment] 2021-08-03 16:30
thanks @nshahan for the fix! I am going to publish new dwds version and pull it into flutter.

**Comment by nshahan** [comment] 2021-08-03 17:12
Thank you @jason-simmons for your investigation! Your suggestion seems like the right fix for this issue.

**Closed** 2021-08-03 23:37 UTC
Labels: P2, dependency: dart, engine, found in release: 2.5, has reproducible steps, perf: memory, platform-web, severe: performance, severe: regression, tool

**Comment by grouma** [comment] 2021-08-05 16:32
Getting back from vacation. Thanks all for resolving this, especially @jason-simmons for digging into the issue.
