### ISSUE TITLE
Is there a way to get the past purchases whether they are pending, successful, failed or canceled in IOS for consumable?

### ISSUE THREAD

**Issue by Adrien300101** [flutter/flutter#144119] opened 2024-02-26 05:43 UTC
### Use case

I want to be able to handle the situation where the user already paid for the consumable but before the completePurchase() function is called the app closed. I noticed from the documentation that if the completePurchase() has not been called after 3 days for a purchase then the user will be refunded. Then is there any feature that I can use on app launch to check the staatus of a specific past purchase and if it requires to run the completePurchase() function, the function will be called. Is there such a feature for IOS?

### Proposal

Retrieve all past purchases or only one depending on the transaction id passed (whether the purchase is failed, pending, successful or cancelled) for IOS for consumables and non-consumables.

**Comment by dam-ease** [comment] 2024-02-26 10:02
Thanks for proposing this @Adrien300101.
This is similar/related to https://github.com/flutter/flutter/issues/109523.
Kindly upvote, comment and follow up on this issue for updates.
Closing this as a duplicate of the existing issue, if you disagree, please comment and I'll reopen this.

**Closed by dam-ease** 2024-02-26 10:02 UTC
Labels: in triage
