### ISSUE TITLE
The registration form on my flutter app selects network providers 

### ISSUE THREAD

**Issue by Irewoleo** [flutter/flutter#76441] opened 2021-02-20 07:14 UTC
I am asking this question from Nigeria. My flutter app on play store does not allow some users to register, it says registration fail when they use MTN network provider and some others but when they use other networks, it registers them. I don't know what is going on. Please help. The app is on play store, "content gram".

**Comment by iapicca** [comment] 2021-02-20 07:26
@Irewoleo 
can you provide your `flutter doctor -v`, your `pubspec.yaml`, any `crashlog` and the list of devices affected

**Comment by Irewoleo** [comment] 2021-02-20 08:51
`[✓] Flutter (Channel master, 1.24.0-8.0.pre.344, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.344 at /Users/arowojoluirewole/DEVELOPMENT/flutter
    • Framework revision de56c6ad72 (3 months ago), 2020-11-23 05:28:06 +0900
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/arowojoluirewole/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

**Comment by Irewoleo** [comment] 2021-02-20 08:51
`name: contentgram
description: A Video Streaming Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.2.3+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7+3
  provider: ^4.3.2+2
  http: ^0.12.2
  path_provider: ^1.6.11
  sticky_headers: ^0.1.8+1
  flutter_facebook_login: ^3.0.0
  fluttertoast: ^7.1.1
  flutter_html: ^1.1.1
  intro_slider: ^2.3.1
  image_picker: ^0.6.7+4
  cached_network_image: ^2.2.0+1
  sqflite: ^1.3.1
  flutter_cache_manager: ^1.4.1
  flutter_secure_storage: ^3.3.3
  shimmer: ^1.1.1
  flutter_swiper: ^1.1.6
  intl: ^0.16.1
  share: ^0.6.5
  launch_review: ^2.0.0
  page_transition: ^1.1.7+2
  flutter_downloader: ^1.5.2
  wakelock: ^0.2.1+1
  permission_handler: ^4.0.0
  rating_bar: ^0.2.0
  font_awesome_flutter: ^8.10.0
  webview_flutter: ^1.0.7
  stripe_api: ^1.1.0
  bubble_tab_indicator: ^0.1.4
  open_iconic_flutter: ^0.3.0
  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.3+1
  google_sign_in: ^4.5.6
  http_auth: ^0.3.1
  braintree_payment: ^1.2.4
  razorpay_flutter: ^1.2.1
  paytm: ^1.0.8
  flutter_paystack: ^1.0.4+1
  in_app_update: ^1.1.14
  dio: ^3.0.10
  flutter_inapp_purchase: ^3.0.1
  flutter_rating_bar: ^3.2.0+1
  get_ip: ^0.4.0
  connectivity: ^2.0.2
  firebase_admob: ^0.10.1
  onesignal_flutter: ^2.6.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by Irewoleo** [comment] 2021-02-20 09:18
This is the error code I get "D/EGL_emulation(27804): eglMakeCurrent: 0x7b603180: ver 3 0 (tinfo 0x83c9b0f0)" on my terminal.

**Comment by iapicca** [comment] 2021-02-20 09:21
> This is the error code I get "D/EGL_emulation(27804): eglMakeCurrent: 0x7b603180: ver 3 0 (tinfo 0x83c9b0f0)" on my terminal.

@Irewoleo 
I apologize, I may have misunderstood the issue;
are you getting crash reports from your production app from certain devices
or your apps fails to register testing it on your device as well?

**Comment by Irewoleo** [comment] 2021-02-20 09:36
Yes, the app fails locally too.

**Comment by iapicca** [comment] 2021-02-20 09:48
> Yes, the app fails locally too.

@Irewoleo 
in that case the issue might not depend from flutter, 
but from the 3rd party packages that registration, from your pubspec I see
[flutter_facebook_login](https://pub.dev/packages/flutter_facebook_login)
[http_auth](https://pub.dev/packages/http_auth)
[firebase_auth](https://pub.dev/packages/firebase_auth)
that might be the cause of the problem,  please reported the issue in the plugin github 
(it's impossible to say which one without looking at the code)


if instead you believe the issue is caused by flutter run 
```console
flutter channel beta
flutter upgrade -f
```
and provide the updated `flutter doctor -v` 
and most importantly a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by pedromassangocode** [comment] 2021-02-22 08:27
Closing this for now as this seems to not be a Flutter issue, if you disagree please provide a minimal code and steps to reproduce the issue as mentioned above (see https://github.com/flutter/flutter/issues/76441#issuecomment-782597090) and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-22 08:27 UTC
