### ISSUE TITLE
JAVA_HOME is not set and no 'java' command could be found in your PATH

### ISSUE THREAD

**Issue by MunibullahShah** [flutter/flutter#119325] opened 2023-01-27 11:21 UTC
## Steps to Reproduce

1. fresh install android studio
2. try to run any flutter app

## Logs

<details>
<summary>Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Exception: Gradle task assembleDebug failed with exit code 1
</summary>

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22000.1516], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2022.1)
    X Unable to find bundled Java version.
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 3 categories.

```

</details>

**Comment by MunibullahShah** [comment] 2023-01-27 11:22
btw I managed to solve this issue by coping the content of jbr directory in jre.
But it still a bug and I have spent 2 days debugging it.

**Comment by darshankawar** [comment] 2023-01-27 13:10
Thanks for the report @MunibullahShah 
I think your issue probably is similar to https://github.com/flutter/flutter/issues/110807 so please check the same and confirm if you can follow-up in that issue for further updates.

**Comment by Gryzor** [comment] 2023-01-27 13:17
The issue is that Jetbrains moved the location of the Java runtime from `jre` to `jrb` and the code in `flutter/packages/flutter_tools/lib/src/android/android_studio.dart`, does this:

```
final String javaPath = globals.platform.isMacOS ?
        version != null && version.major < 2020 ?
        globals.fs.path.join(directory, 'jre', 'jdk', 'Contents', 'Home') :
        globals.fs.path.join(directory, 'jre', 'Contents', 'Home') :
        globals.fs.path.join(directory, 'jre');
```

For this to work, it should either have an "else" to deal with newer versions (2022.1 'electric eel' is the new one) where the path is `jbr` instead.

I have not tried this, as modifying the Dart files alone is not enough according to my limited understanding on how `flutter <command>` functions; one would have to "recompile" the flutter binary.

**Comment by MunibullahShah** [comment] 2023-01-27 13:23
@darshankawar mine is little different, the issue you mentioned does not want to use default jdk, I want to use that but it can't find jdk.
It moved its jdk from jre to jbr but it still looks in jre for the files

**Comment by darshankawar** [comment] 2023-01-30 05:00
Thanks for the update @MunibullahShah and for sharing your findings @Gryzor 
I see that there's similar issue with all the details and a potential fix related to AS Electric eel version https://github.com/flutter/flutter/issues/106674 in which you can follow-up for further updates. You may also share your findings in that issue for better tracking.

I'll close this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-01-30 05:00 UTC
Labels: in triage
