### ISSUE TITLE
Camera preview is stretching horizonatlly with 4:3 aspect ratio

### ISSUE THREAD

**Issue by nayanbabariya95** [flutter/flutter#84275] opened 2021-06-09 16:34 UTC
> Camera preview is stretching when changing aspect ratio from 16:9 to 4:3.
I am changing previewSize on IconButton click
camera plugin version: 0.8.1+3
Device information: Zenfone Max Pro M1  • android-arm64  • Android 11 (API 30)

```
class CameraScreenGithub extends StatefulWidget {
  const CameraScreenGithub({Key? key}) : super(key: key);

  @override
  _CameraScreenGithubState createState() => _CameraScreenGithubState();
}

class _CameraScreenGithubState extends State<CameraScreenGithub> {
  CameraController? _cameraController;
  Future<void>? _initializeControllerFuture;
  List<CameraDescription> _cameraDescription = [];

  @override
  void initState() {
    super.initState();
    _initializeCamera();
  }

  Future<void> _initializeCamera() async {
    _cameraDescription.addAll(await availableCameras());
    _setCamera(_cameraDescription[0]);
  }

  _setCamera(CameraDescription description) {
    _cameraController = CameraController(description, ResolutionPreset.high);
    _initializeControllerFuture = _cameraController?.initialize();
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    _cameraController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: Stack(
                children: [
                  Center(
                    child: _cameraPreview(),
                  ),
                  Positioned(
                    top: 20,
                    left: 20,
                    right: 20,
                    child: _aspectRatioButton(),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _cameraPreview() => ClipRRect(
        borderRadius: BorderRadius.circular(16),
        child: FutureBuilder<void>(
          future: _initializeControllerFuture,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              return CameraPreview(_cameraController!);
            }
            return Container();
          },
        ),
      );

  Widget _aspectRatioButton() => IconButton(
        icon: Icon(
          Icons.aspect_ratio,
          color: Colors.white,
        ),
        onPressed: () {
          _cameraController?.value =
              _cameraController!.value.copyWith(previewSize: Size(320, 240));
          setState(() {});
        },
      );
}
```

---

<details>
<summary>flutter doctor -v</summary>
<br>
<pre>
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IN)
    • Flutter version 2.2.1 at /Users/nayan/Public/flutter
    • Framework revision 02c026b03c (13 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/nayan/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/nayan/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • Zenfone Max Pro M1 (mobile) • 192.168.0.100:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
</pre>
</details>

**Comment by TahaTesser** [comment] 2021-06-10 13:01
Hi @nayanbabariya95 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/15953
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-10 13:01 UTC
Labels: in triage

**Comment by nayanbabariya95** [comment] 2021-06-14 16:06
@TahaTesser I am disagree with you because my point was to change aspect ratio to 4:3 from 16:9 and there is no option to change aspect ratio in camera controller. so had changed preview size but it was stretching.
Also set resolution to ResolutionPreset.max in camera controller does not set maximum resolution. it set 1280x720

**Comment by TahaTesser** [comment] 2021-07-01 10:18
@nayanbabariya95 
https://github.com/flutter/flutter/issues/15953's is not api docs, updated it accordingly, so it  should address your bug, provide the option to aspect ratio if needed
