### ISSUE TITLE
GestureRecognizer can be tricked into processing secondary-button double-tap

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#82034] opened 2021-05-07 14:56 UTC
## Issue

DoubleTapGestureRecognizer looks to see if the second tap has different buttons than the first tap, and if so, it resets the recognizer and then tracks the new tap:

https://github.com/flutter/flutter/blob/c84528d9da6c5af3bbd660139f6c9590880548d1/packages/flutter/lib/src/gestures/multitap.dart#L215-L219

The problem is: had the first tap not already been recorded, it wouldn't have allowed the tap with anything other than the primary button:

https://github.com/flutter/flutter/blob/c84528d9da6c5af3bbd660139f6c9590880548d1/packages/flutter/lib/src/gestures/multitap.dart#L195-L204

So the fact that it's a second tap effectively gives it a "back door" into tricking the recognizer to process a double tap using the secondary button.  This in turn causes downstream problems (an assertion failure).

## Steps to reproduce

Add the following test to `double_tap_test.dart` and run it:

```dart
  // Down/up pair 7: normal tap sequence same as pair 6
  const PointerDownEvent down7 = PointerDownEvent(
    pointer: 7,
    position: Offset(10.0, 10.0),
    buttons: kSecondaryMouseButton,
  );

  const PointerUpEvent up7 = PointerUpEvent(
    pointer: 7,
    position: Offset(11.0, 9.0),
  );

  testGesture('Second tap of secondary button does not start tracking as new double-tap', (GestureTester tester) {
    tap.addPointer(down1);
    tester.closeArena(1);
    tester.route(down1);
    tester.route(up1);
    GestureBinding.instance!.gestureArena.sweep(1);

    tester.async.elapse(const Duration(milliseconds: 100));
    tap.addPointer(down6);
    tester.closeArena(6);
    tester.route(down6);
    tester.route(up6);
    GestureBinding.instance!.gestureArena.sweep(6);

    tester.async.elapse(const Duration(milliseconds: 100));
    tap.addPointer(down7);
    tester.closeArena(7);
    tester.route(down7);
    tester.route(up7);
    GestureBinding.instance!.gestureArena.sweep(2);

    expect(doubleTapRecognized, isFalse);
  });
```

## Version info

Found in 133a55ae51df1128fe8433b039e1a7ed976e9439

**Comment by bleroux** [comment] 2023-12-12 14:00
Closing because the crash is no more reproducible.
This was fixes by https://github.com/flutter/flutter/pull/111852 (especially the change proposed in the following comment: https://github.com/flutter/flutter/pull/111852/files#r1065171746) .

**Closed by bleroux** 2023-12-12 14:00 UTC
Labels: c: crash, framework, f: gestures, P1, team-framework
