### ISSUE TITLE
location and geolocator plugins don't work with android_alarm_manager

### ISSUE THREAD

**Issue by alexandranb** [flutter/flutter#25912] opened 2018-12-30 21:36 UTC
Hello,

When I try to use android_alarm_manager with location or geolocator, I get the folllowing error
```
I/AlarmService(32723): Starting AlarmService...
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32723): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32723): java.lang.IllegalStateException: registrar.activity() must not be null
```

**Comment by zoechi** [comment] 2018-12-31 08:08
Looks like https://github.com/flutter/flutter/issues/20913#issuecomment-439709544

**Comment by zoechi** [comment] 2018-12-31 08:09
Please add the output of `flutter doctor -v`.

**Comment by Hixie** [comment] 2019-01-03 07:33
The issue is probably that these plugins are assuming there's an activity when they're registered.

I suspect there is more to the crash than described in the original comment. It would be helpful to have the entire log of the program execution (e.g. the stack trace).

**Comment by alexandranb** [comment] 2019-01-04 11:46
Hello,

I managed to make it work with both of the plugins. I needed to add the import location plugin in the new GeneratedPluginRegistrant created and then remove it in alreadyRegisteredWith for plugin's name.

I think it can be closed for now.

Thanks

**Comment by farconada** [comment] 2019-01-20 14:30
@alexandranb would you mind to provide a code example, please? . I'm on the same point

**Comment by alexandranb** [comment] 2019-01-22 08:48
Hi,

I will provide a code example as soon as I get my laptop from repairing. However, you need to know that the plugin doesn't work when the app is terminated. I tried to use it with local notifications and, when the app is closed (not in foreground) it doesn't trigger any notifications. So, the plugin is a bit irrelevant until they make some changes.

Thanks

**Comment by estevez-dev** [comment] 2019-08-28 15:13
Did someone managed to solve this?
@alexandranb please provide code example of this:
```
I needed to add the import location plugin in the new GeneratedPluginRegistrant created and then remove it in alreadyRegisteredWith for plugin's name.
```

**Comment by stuartmorgan** [comment] 2021-05-27 15:49
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).

**Closed by stuartmorgan** 2021-05-27 15:49 UTC
Labels: P4, p: android_alarm_manager, p: first party, platform-android, plugin, severe: crash
