### ISSUE TITLE
Flutter Template App cannot link for iOS 14.2 Simulator using Xcode 12.2 Beta on Apple Silicon / DTK

### ISSUE THREAD

**Issue by alexmarkley** [flutter/flutter#66181] opened 2020-09-19 14:42 UTC
This issue is related to https://github.com/flutter/flutter/issues/65132 but this issue is not the same. Specifically, in this issue, I am using Xcode itself to build and launch the Runner project, as a workaround to the `flutter run` tooling issues currently present in this environment.

## Steps to Reproduce

1. Run `flutter create helloWorld`.
2. Navigate (in Finder) to `helloWorld/ios` and double-click `Runner.xcworkspace`
3. Select a valid iOS Simulators target and click Run.

**Expected results:**

Expected to see a running Template app in my simulator.

**Actual results:**

Link failure:

```
Ld /Users/alex/Library/Developer/Xcode/DerivedData/Runner-eikyewjnqquahfalgdirgcytylcj/Build/Products/Debug-iphonesimulator/Runner.app/Runner normal (in target 'Runner' from project 'Runner')
    cd /Users/alex/Documents/MarkleyBros/flutter_helloworld/helloWorldTwo/ios
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios9.0-simulator -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk -L/Users/alex/Library/Developer/Xcode/DerivedData/Runner-eikyewjnqquahfalgdirgcytylcj/Build/Products/Debug-iphonesimulator -L/Users/alex/Documents/MarkleyBros/flutter_helloworld/helloWorldTwo/ios/Flutter -F/Users/alex/Library/Developer/Xcode/DerivedData/Runner-eikyewjnqquahfalgdirgcytylcj/Build/Products/Debug-iphonesimulator -F/Users/alex/Documents/MarkleyBros/flutter_helloworld/helloWorldTwo/ios/Flutter -filelist /Users/alex/Library/Developer/Xcode/DerivedData/Runner-eikyewjnqquahfalgdirgcytylcj/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/alex/Library/Developer/Xcode/DerivedData/Runner-eikyewjnqquahfalgdirgcytylcj/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/alex/Library/Developer/Xcode/DerivedData/Runner-eikyewjnqquahfalgdirgcytylcj/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.swiftmodule -framework Flutter -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/alex/Library/Developer/Xcode/DerivedData/Runner-eikyewjnqquahfalgdirgcytylcj/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent -Xlinker -dependency_info -Xlinker /Users/alex/Library/Developer/Xcode/DerivedData/Runner-eikyewjnqquahfalgdirgcytylcj/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat -o /Users/alex/Library/Developer/Xcode/DerivedData/Runner-eikyewjnqquahfalgdirgcytylcj/Build/Products/Debug-iphonesimulator/Runner.app/Runner

ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/alex/Documents/MarkleyBros/flutter_helloworld/helloWorldTwo/ios/Flutter/Flutter.framework/Flutter' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

![image](https://user-images.githubusercontent.com/1566468/93669866-be069f00-fa64-11ea-8d5e-caf576d7b539.png)

<details>
  <summary>LOGS - flutter doctor:</summary>

**Note:** Flutter master updated today.

```
DTK:flutter_helloworld alex$ flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.264, on macOS 11.0 20A5374g x86_64, locale en-US)
    • Flutter version 1.22.0-10.0.pre.264 at /Users/alex/Development/Flutter/flutter
    • Framework revision 3e6863ab2b (11 hours ago), 2020-09-18 21:05:27 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5018i
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Alex's iPhone (mobile) • 00f777378e33cc1c0fd0af01b429e8b0fe04ba87 • ios • iOS 13.6.1

! Doctor found issues in 2 categories.
DTK:flutter_helloworld alex$ 
```

</details>

<details>

  <summary>LOGS - Initially creating the app:</summary>

```
DTK:flutter_helloworld alex$ flutter create helloWorldTwo
Creating project helloWorldTwo...
  helloWorldTwo/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  helloWorldTwo/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  helloWorldTwo/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  helloWorldTwo/ios/Runner/Info.plist (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  helloWorldTwo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  helloWorldTwo/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  helloWorldTwo/ios/Runner/Base.lproj/Main.storyboard (created)
  helloWorldTwo/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  helloWorldTwo/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  helloWorldTwo/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  helloWorldTwo/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  helloWorldTwo/ios/Flutter/Debug.xcconfig (created)
  helloWorldTwo/ios/Flutter/Release.xcconfig (created)
  helloWorldTwo/ios/Flutter/AppFrameworkInfo.plist (created)
  helloWorldTwo/ios/.gitignore (created)
  helloWorldTwo/test/widget_test.dart (created)
  helloWorldTwo/helloWorldTwo.iml (created)
  helloWorldTwo/.gitignore (created)
  helloWorldTwo/.metadata (created)
  helloWorldTwo/android/app/src/profile/AndroidManifest.xml (created)
  helloWorldTwo/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  helloWorldTwo/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  helloWorldTwo/android/app/src/main/res/drawable/launch_background.xml (created)
  helloWorldTwo/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  helloWorldTwo/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  helloWorldTwo/android/app/src/main/res/values-night/styles.xml (created)
  helloWorldTwo/android/app/src/main/res/values/styles.xml (created)
  helloWorldTwo/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  helloWorldTwo/android/app/src/main/AndroidManifest.xml (created)
  helloWorldTwo/android/app/src/debug/AndroidManifest.xml (created)
  helloWorldTwo/android/gradle/wrapper/gradle-wrapper.properties (created)
  helloWorldTwo/android/gradle.properties (created)
  helloWorldTwo/android/.gitignore (created)
  helloWorldTwo/android/settings.gradle (created)
  helloWorldTwo/android/app/build.gradle (created)
  helloWorldTwo/android/app/src/main/kotlin/com/example/helloWorldTwo/MainActivity.kt (created)
  helloWorldTwo/android/build.gradle (created)
  helloWorldTwo/android/helloWorldTwo_android.iml (created)
  helloWorldTwo/pubspec.yaml (created)
  helloWorldTwo/README.md (created)
  helloWorldTwo/ios/Runner/Runner-Bridging-Header.h (created)
  helloWorldTwo/ios/Runner/AppDelegate.swift (created)
  helloWorldTwo/ios/Runner.xcodeproj/project.pbxproj (created)
  helloWorldTwo/lib/main.dart (created)
  helloWorldTwo/.idea/runConfigurations/main_dart.xml (created)
  helloWorldTwo/.idea/libraries/Dart_SDK.xml (created)
  helloWorldTwo/.idea/libraries/KotlinJavaRuntime.xml (created)
  helloWorldTwo/.idea/modules.xml (created)
  helloWorldTwo/.idea/workspace.xml (created)
Running "flutter pub get" in helloWorldTwo...                       1.6s
Wrote 72 files.

All done!
[✓] Flutter: is fully installed. (Channel master, 1.22.0-10.0.pre.264, on macOS 11.0 20A5374g x86_64, locale en-US)
[✗] Android toolchain - develop for Android devices: is not installed.
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 12.2)
[!] Android Studio: is not available. (not installed)
[✓] Connected device: is fully installed. (1 available)

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd helloWorldTwo
  $ flutter run

Your application code is in helloWorldTwo/lib/main.dart.

DTK:flutter_helloworld alex$ 
```

</details>

**Comment by jmagman** [comment] 2020-09-19 17:56
Duplicate of https://github.com/flutter/flutter/issues/64502.

**Closed by jmagman** 2020-09-19 17:56 UTC
