### ISSUE TITLE
Oops; flutter has exited unexpectedly: "Invalid argument(s): Invalid type for "path": null".

### ISSUE THREAD

**Issue by gene9** [flutter/flutter#78587] opened 2021-03-19 00:15 UTC
flutter version:

```
flutter --version
Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8962f6dc68 (7 days ago) • 2021-03-11 13:22:20 -0800
Engine • revision 5d8bf811b3
Tools • Dart 2.12.1


```
flutter create myapp

```
Creating project myapp...

Oops; flutter has exited unexpectedly: "Invalid argument(s): Invalid type for "path": null".
A crash report has been written to C:\as\projects\Clip\DigitalClipboard_Backend\flutter_03.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+Invalid+argument%28s%29%3A+Invalid+type+for+%22path%22%3A+null

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JmwKY
```

**Comment by gene9** [comment] 2021-03-19 00:17
[flutter_03.log](https://github.com/flutter/flutter/files/6167832/flutter_03.log)

**Comment by gene9** [comment] 2021-03-19 00:18
flutter_03.log is attached

**Comment by darshankawar** [comment] 2021-03-19 08:41
Closing this as duplicate of https://github.com/flutter/flutter/issues/56811

As a workaround, try [this](https://github.com/flutter/flutter/issues/56811#issuecomment-792510148) and see if it works.

**Closed by darshankawar** 2021-03-19 08:41 UTC
Labels: in triage
