### ISSUE TITLE
In release mode, Flutter for web using package google_maps, we cannot call an event listener on a map marker 

### ISSUE THREAD

**Issue by corymalcolmtaylor** [flutter/flutter#54026] opened 2020-04-05 02:43 UTC
Hi,
I am using a Flutter for web (latest master, though I was also getting this error in the previous master) and am using package "google_maps" .  In my dart code I attach several listeners to some map markers with attempt to open an infowindow.   When that code runs in release mode (not debug mode) I get no infoWindow but in the console I get an error below ( the verbose version ):

## Steps to Reproduce

1. create a new project using the google_maps package, make a  map and include a marker
2. attach a click listener to the marker, in the callback include an attempt to open an infoWindow on the marker.  Sample code:
```
   m = gm.Marker(gm.MarkerOptions()
      ..position = myLatlng
      ..map = map
      ..draggable = true
      ..zIndex = zindex
      ..icon = gm.Icon().url = url
      ..title = title);
    m.set('dId', docId);

  bool isopen = false;
    void toggleInfo() {
      print('toggleinfo ${m.clickable}');
      if (!isopen) {
        isopen = true;
        infoWindow.open(map, m);
      } else {
        isopen = false;
        infoWindow.close();
      }
    }
  m.addListener('click', toggleInfo);
```
3. run the code   in release mode, ie via "flutter run -d chrome --profile --verbose", or "Flutter build web" to see the non-minified version and then firebase deploy to firebase hosting (error does not occur when running from the Run menu or via f5 or ^f5 ) and click on the marker. Look in console for the error.

## Logs
 
```

 Uncaught NoSuchMethodError: method not found: 'call'
Receiver: Closure 'FireMapState_makeMarker_toggleInfo'
Arguments: [Instance of 'JsObject']
    at Object.wrapException (http://localhost:51861/main.dart.js:3845:17)
    at FireMapState_makeMarker_toggleInfo.noSuchMethod$1 (http://localhost:51861/main.dart.js:46189:15)
    at Object.noSuchMethod$1$ (http://localhost:51861/main.dart.js:6568:42)
    at Object.Primitives_functionNoSuchMethod (http://localhost:51861/main.dart.js:3724:16)
    at Object.Primitives__genericApplyFunction2 (http://localhost:51861/main.dart.js:3781:18)
    at Object.Primitives_applyFunction (http://localhost:51861/main.dart.js:3757:16)
    at Object.Function_apply (http://localhost:51861/main.dart.js:8401:16)
    at _callDartFunction (http://localhost:51861/main.dart.js:10033:31)
    at _.pg.<anonymous> (http://localhost:51861/main.dart.js:49066:18)
    at re.H (https://maps.googleapis.com/maps/api/js?key=...:187:294)


non-verbose/non-minified version:
js_helper.dart:1343 Uncaught NoSuchMethodError: method not found: 'call'
Receiver: Closure 'minified:Ob'
Arguments: [Instance of 'minified:aB']
    at Object.d (https://asdasd...com/myapp/main.dart.js:1958:3)
     at Ob.pn (https://asdasd....com/myapp/main.dart.js:24990:26)
    at Object.acG (https://asdasd....com/myapp/main.dart.js:3165:34)
    at Object.o0 (https://asdasd....com/myapp/main.dart.js:1912:10)
    at Object.aeO (https://asdasd....com/myapp/main.dart.js:1935:10)
    at Object.aeQ (https://asdasd....com/myapp/main.dart.js:1920:41)
    at Object.a7g (https://asdasd.......com/myapp/main.dart.js:4087:28)
    at agK (https://asdasd....com/myapp/main.dart.js:4854:15)
    at _.pg.<anonymous> (https://asdasd....com/myapp/main.dart.js:26342:63)
    at re.H (https://maps.googleapis.com/maps/api/js?key=...2wQUX...:187:294)
```

```
flutter doctor -v
[✓] Flutter (Channel master, v1.18.1-pre.4, on Mac OS X 10.15.4 19E266, locale en-CA)
    • Flutter version 1.18.1-pre.4 at /Volumes/macex/flutter
    • Framework revision 46ce54db88 (2 hours ago), 2020-04-04 19:46:01 -0400
    • Engine revision 4cfbe45033
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 e736495eb7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Volumes/macex/androidSDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (3 available)
    • iPhone 11  • FEBA6B31-98FA-4B14-B88B-5F01E9EDC350 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4
      (simulator)
    • Chrome     • chrome                               • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server                           • web-javascript • Flutter Tools

```

I tried running it with `--no-minify`  but that setting didn't seem to help - in fact only when I ran `flutter run -d chrome --profile --verbose`  did I get what looks like  non-minified js.

**Comment by TahaTesser** [comment] 2020-04-06 09:26
Hi @corymalcolmtaylor 
For issue related to the 3rd party plugin [google_maps](https://pub.dev/packages/google_maps) you may want to open an issue in the dedicated [github](hhttps://github.com/a14n/dart-google-maps/issues).

I am not sure if you meant to use official [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) package 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-04-06 09:26 UTC

**Comment by corymalcolmtaylor** [comment] 2020-04-06 13:20
Hi @TahaTesser,
  Since the code works fine in debug mode (in VS Code I use the Run menu's "Start Debugging" item and target Chrome) but not in release mode (use "Flutter build web", then deploy the ./build/web code to firebase hosting and run on there )  I thought the problem was probably in that "flutter build web" process and not in the 3rd party [google_maps](https://pub.dev/packages/google_maps) package.  That package is basically just a wrapper around the Google Maps SDK for javascript.
  I am specifically targeting the web in this app so the google_maps_flutter package is not an option as it does not target the web.

**Comment by mraleph** [comment] 2020-04-07 06:05
@corymalcolmtaylor Change you code to add a parameter to `void toggleInfo() {`, e.g. 

```dart
    void toggleInfo(e) {
    // ...
    }
```

Dart is very strict with parameters, compared to JavaScript. You can see from the error that it is trying to call your closure with an argument:

```
Arguments: [Instance of 'JsObject']
```

However you closure has 0 parameters - so it can't be called with an argument. Hence an error.

**Comment by corymalcolmtaylor** [comment] 2020-04-07 12:55
@mraleph That got it!  Thank you!

**Comment by alanstyong71** [comment] 2020-04-14 02:50
This same issue has been bugging me for days until I went back and read a few examples. Javascript is very sensitive, and while this code works on the emulator:

m.addListener('click', toggleInfo);

It actually breaks when you deploy it to a web server.

I changed this code to a click event:

mymarker.onClick.listen((e) {
            myinfowindow.open(mymap, mymarker);
          });

and it works. The problem is with the addListener code.

In your case, you should be writing the above code as:

m.onClick.listen((e){
    toggleInfo();
}

Hope this helps.
