### ISSUE TITLE
[google_maps_flutter_web] bring the version into line with the [google_maps_flutter] version

### ISSUE THREAD

**Issue by Sammius** [flutter/flutter#76916] opened 2021-02-27 06:53 UTC
Hello!

I'd like to raise the **[google_maps_flutter]** version to **2.0.0** but there is a conflict with the current **[google_maps_flutter_web]** version:

```
[flutt] flutter pub get
Running "flutter pub get" in flutt...                           
Because google_maps_flutter_web >=0.1.1 depends on google_maps_flutter_platform_interface ^1.1.0 and google_maps_flutter 2.0.0 depends on google_maps_flutter_platform_interface ^2.0.0, google_maps_flutter_web >=0.1.1 is incompatible with google_maps_flutter 2.0.0.
And because no versions of google_maps_flutter match >2.0.0 <3.0.0, google_maps_flutter_web >=0.1.1 is incompatible with google_maps_flutter ^2.0.0.
So, because App depends on both google_maps_flutter ^2.0.0 and google_maps_flutter_web ^0.1.1, version solving failed.


pub get failed (1; So, because App depends on both google_maps_flutter ^2.0.0 and google_maps_flutter_web ^0.1.1, version solving failed.)
exit code 1
```

Is it possible to fix it somehow?

/cc @ditman

**Comment by stuartmorgan** [comment] 2021-02-27 13:35
Duplicate of https://github.com/flutter/flutter/issues/75236

**Closed by stuartmorgan** 2021-02-27 13:35 UTC
