### ISSUE TITLE
RangeError during Flutter Android build since v1.17.1

### ISSUE THREAD

**Issue by devjeff** [flutter/flutter#58602] opened 2020-06-03 15:22 UTC
**Steps to Reproduce**
When I run the command `flutter build appbundle` with version 1.12 or with version 1.19.x (on master) everything works fine and the bundle is successfully created. But with 1.17.1 and 1.17.2 I get the following error:

Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:146:60)
#1      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:691:47)
...
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Programmieren\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'E:\Programmieren\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

<details>
**Full Log:**

Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:146:60)
#1      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:691:47)
#2      Typ
eFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1358:52)
#3      _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:247:42)
#4      _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:181:14)
#5      _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1243:32)
#6      _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:397:44)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#8      _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:372:12)
#9      _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1243:32)
#10     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1462:23)
#11     Call.apply (package:vm/transformations/type_flow/summary.dart:221:31)
#12     Summary.apply (package:vm/transformations/type_flow/summary.dart:652:33)
#13     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:256:24)
#14     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:181:14)

#15     _WorkList.processInvocation (package:vm/transformations/type_fl
ow/analysis.dart:1243:32)
#16     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:397:44)
#17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#18
     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:372:12)
#19     _WorkList.processInvocation (package:vm/
transformations/type_flow/analysis.dart:1243:32)
#20     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1462:23)
#21     Call.apply (package:vm/transf
ormations/type_flow/summary.dart:221:31)
#22     Summary.apply (package:vm/transformations/type_flow/summary.dart:652:33)
#23     _DirectInvocation._processFunction (package:vm
/transformations/type_flow/analysis.dart:256:24)
#24     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:181:14)
#25     _WorkList.processInvocation (package:vm
/transformations/type_flow/analysis.dart:1243:32)
#26     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:397:44)
#27
     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#28     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.
dart:372:12)
#29     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1243:32)
#30     TypeFlowAnalysis.applyCall (package:vm/transformations/ty
pe_flow/analysis.dart:1462:23)
#31     Call.apply (package:vm/transformations/type_flow/summary.dart:221:31)
#32     Summary.apply (pac
kage:vm/transformations/type_flow/summary.dart:652:33)
#33     _DirectInvocation._processFunction (
package:vm/transformations/type_flow/analysis.dart:256:24)
#34     _DirectInvocation.process
 (package:vm/transformations/type_flow/analysis.dart:181:14)
#35     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1243:32)
#36     _DispatchableIn
vocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:397:44)
#37     _LinkedHashMapMi
xin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#38     _DispatchableInvocation.process (package:vm/
transformations/type_flow/analysis.dart:372:12)
#39     _WorkList.processInvocation (
package:vm/transformations/type_flow/analysis.dart:1243:32)
#40     TypeFlowAnalysis.applyCa
ll (package:vm/transformations/type_flow/analysis.dart:1462:23)
#41     Cal
l.apply (package:vm/transformations/type_flow/summary.dart:221:31)
#42     Summary.apply (pac
kage:vm/transformations/type_flow/summary.dart:652:33)
#43     _DirectInvocation._processFunc
tion (package:vm/transformations/type_flow/analysis.dart:256:24)
#44     _DirectInvocation.p
rocess (package:vm/transformations/type_flow/analysis.dart:181:14)
#45     _WorkList.processInvocation (package:
vm/transformations/type_flow/analysis.dart:1243:32)
#46     _DispatchableInvocation.process.<a
nonymous closure> (package:vm/transformations/type_flow/analysis.dart:397:44)
#47     _LinkedH
ashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#48     _Dispat
chableInvocation.process (package:vm/transformations/type_flow/analysis.dart:372:12)
#49     _WorkLi
st.processInvocation (package:vm/transformations/type_flow/analysis.dart:1243:32)
#50     TypeFlo
wAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1462:23)
#51     Call
.apply (package:vm/transformations/type_flow/summary.dart:221:31)
#52     Summary.apply (pack
age:vm/transformations/type_flow/summary.dart:652:33)
#53     _DirectInvocation._p
rocessFunction (package:vm/transformations/type_flow/analysis.dart:256:24)
#54     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:181:14)
#55     _WorkList.processInvocation (package:v
m/transformations/type_flow/analysis.dart:1243:32)
#56     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1223:7)
#57     
T
ypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1372:14)
#58     transformComponent (package:vm/transformations/type_flow/transformer.dart:64:20)
#59     runGlobalTransformations (package:vm/kernel_front_end.dart
:425:5)

#60     compileToKernel (package:vm/kernel_front_end.dart:336:11)
<asynchronous suspension>
#61     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_ser
ver.dart:510:54)
#62     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#63     _rootRun (d
art:async/zone.dart:1180:38)
#64     _CustomZone.run (dart:async/zone.dart:1077:19)
#65     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#66     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#67     _ro
otRun (dart:async/zone.dart:1184:13)
#68     _CustomZone.run (dart:async/zone.dart:1077:19)
#69     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
#70     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#71     _Timer.
_runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#72     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#73     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Programmieren\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'E:\Programmieren\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

**Doctor:**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.17.1, on Microsoft Windows [Version 10.0.18362.295], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.0)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)

• No issues found!

```
```

</details>

**Comment by NTMS2017** [comment] 2020-06-03 15:34
Also iphonesimulator failed. :(

```
Launching lib/main.dart on iPhone 11 in debug mode...
Running pod install...                                              2.7s
Running Xcode build...
Xcode build done.                                           77.4s
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
Error launching application on iPhone 11.
```

**Comment by alexmarkov** [comment] 2020-06-03 21:23
It looks like number of `member.forwardingStubSuperTarget.function.namedParameters` doesn't match `member.function.namedParameters` for a forwarding stub. @johnniwinther Do you know if there were any bugs or fixes related to that?

@devjeff Could you provide an example (or the whole application, if it is open-source) which could be used to reproduce the problem?

**Comment by johnniwinther** [comment] 2020-06-04 05:57
There hasn't been any recent changes to forwarding stubs. Last change was in February (implementing the consolidated model for mixed inheritance which shares implementation with the creation of forwarding stubs).

Sounds like we should assert the relation between `member.forwardingStubSuperTarget.function.namedParameters` and `member.function.namedParameters` in the verifier.

**Comment by devjeff** [comment] 2020-06-04 20:40
Hey, the app is not open source unfortunately. I have tried to create a fresh flutter app from scratch and could not build a bundle successfully. I tried to copy some parts of the original app, but still didn't find the code that makes the build break. I'll try to modify it further. Hopefully I can find the problematic part soon.

**Comment by devjeff** [comment] 2020-08-12 19:43
I wasn't able to extract the relevant code part that causes this problem. However, as the problem no longer occurs with version 1.20.1, I think, the issue can be closed.

**Comment by pedromassangocode** [comment] 2020-09-01 10:09
Hi @devjeff
Given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by pedromassangocode** 2020-09-01 10:09 UTC
Labels: a: build, dependency: dart, framework, severe: crash
