### ISSUE TITLE
flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by GayatriDarji** [flutter/flutter#36674] opened 2019-07-22 10:51 UTC
## command
```
flutter --no-color run --machine --track-widget-creation --device-id=54d85b5a lib\main.dart
```
## exception
```
FileSystemException: FileSystemException: Cannot open file, path = 'C:\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\ca31a7c57bada458fa7f5c0d3f36bc1af4ccbc79\android-arm-profile\windows-x64.zip' (OS Error: Access is denied.
, errno = 5)
```
```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)
#3      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:124:16)
#4      _downloadFile (package:flutter_tools/src/cache.dart:917:12)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:408:17)
<asynchronous suspension>
#6      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:437:26)
<asynchronous suspension>
#7      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:404:12)
#8      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:424:12)
#9      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:571:13)
<asynchronous suspension>
#10     CachedArtifact.update (package:flutter_tools/src/cache.dart:367:11)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:291:26)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:543:19)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:111:11)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#41     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#42     run (package:flutter_tools/runner.dart:51:10)
#43     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#44     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.5.4 at C:\flutter
    • Framework revision b593f5167b (3 months ago), 2019-04-22 07:51:33 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\android-sdk-window
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\android-sdk-window
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • ONEPLUS A3003 • 54d85b5a • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by BondarenkoStas** [comment] 2019-09-23 16:01
@GayatriDarji Is the issue still relevant? Did you experience it with current stable version of flutter? It also can be caused by an antivirus blocking the folder.

**Comment by iapicca** [comment] 2019-11-11 15:50
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-11 15:50 UTC
Labels: waiting for customer response
