### ISSUE TITLE
took 12 hours to find simple thing.

### ISSUE THREAD

**Issue by Puspharaj** [flutter/flutter#78209] opened 2021-03-15 12:57 UTC
I just recently started to develop flutter web application, Unfortunately the firebase updates are really slow compared to flutter development.

Simple List<String> to Map causing to throw error. And in firestore it works. Meaning it saves the data but on console still throws the below error. 

` Expected a value of type 'List<String>', but got one of type 'List<dynamic>'`

**Comment by iapicca** [comment] 2021-03-15 13:33
@Puspharaj 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by darshankawar** [comment] 2021-03-16 07:59
@Puspharaj 
Looks like a firebase related issue. Please open this issue as suggested above.
Closing from here.

**Closed by darshankawar** 2021-03-16 07:59 UTC
Labels: in triage
