### ISSUE TITLE
Linux Desktop App: Memory usage while opening links

### ISSUE THREAD

**Issue by rjcalifornia** [flutter/flutter#150899] opened 2024-06-27 04:53 UTC
### Steps to reproduce

1. Renders a real link on the web with the Link() widget
2. Click on the link. The web browser will open as expected.
3. Watch the app memory usage increase somehow.

### Code sample

So, I have this desktop Linux app, and I have some links for license and attribution. Works well, but I noticed that whenever a link is opened, the app memory usage increases kinda like if it is opening an in-app web browser.

<details open><summary>Code sample</summary>

```dart
Link(
                  uri: url,
                  target: LinkTarget.blank,
                  builder: (BuildContext ctx, FollowLink? openLink) {
                    return TextButton.icon(
                      onPressed: openLink,
                      label: const Text(
                        'Sample text',
                        style: TextStyle(color: Color(0xfffafafa)),
                      ),
                      icon: const Icon(
                        Icons.web_asset_outlined,
                        color: Color(0xfffafafa),
                      ),
                    );
                  },
                ),
```

</details>

Is there a workaround or a fix to that? Cannot find info regarding this particular issue.

### What target platforms are you seeing this bug on?

Linux

### OS/Browser name and version | Device information

Target Platform: Desktop
Target OS version/browser: Chrome Version 110.0.5481.180 (Official Build) (64-bit)
Devices: Ubuntu 22.04

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on Ubuntu 22.04.4 LTS 6.5.0-35-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by huycozy** [comment] 2024-06-27 08:33
Hi @rjcalifornia 
Are you using [url_launcher](https://pub.dev/packages/url_launcher) package? How much did you see that the memory increased after opening the URL?

I checked this using package [example](https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher/example) on my Ubuntu machine but didn't see the issue. Could you also try this and confirm?

**Comment by rjcalifornia** [comment] 2024-06-27 14:54
> Hi @rjcalifornia Are you using [url_launcher](https://pub.dev/packages/url_launcher) package? 
Yes, I am using the URL launcher

`import 'package:url_launcher/link.dart';`

>How much did you see that the memory increased after opening the URL?

App uses 64mb but when I opened the url, it went up to 600+mb

> I checked this using package [example](https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher/example) on my Ubuntu machine but didn't see the issue. Could you also try this and confirm?

I am using the method described here in line 240:

https://github.com/flutter/packages/blob/main/packages/url_launcher/url_launcher/example/lib/main.dart

**Comment by rjcalifornia** [comment] 2024-06-27 16:23
Alright, this is interesting:

If the web browser is already opened, and you click on a link this doesn't happen. However, if no browser is open and you click on the link it will behave as a in-app browser (or webview?) and memory usage will increase.

**Comment by huycozy** [comment] 2024-06-28 07:39
I still can't reproduce this. I'm on the latest Flutter stable channel 3.22.2. Could you try upgrading Flutter SDK to this version and retry?

**Comment by rjcalifornia** [comment] 2024-06-29 04:18
Upgraded flutter, same issue.

> Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (3 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

Forgot to mention, Edge is my default web browser (yeah I know Ubuntu). 

If Edge is open, memory is fine. If Edge is not open and click on the link, the memory usage by the app will increase.

**Comment by huycozy** [comment] 2024-07-01 05:10
I installed Edge browser and then set it as the default but still couldn't see the issue. You can watch my recorded video to see if I missed a steps:

[Screencast from 01-07-2024 11:57:34.webm](https://github.com/flutter/flutter/assets/104349824/1c313dd9-30df-43cb-85f0-ff54bc130b44)

Some other aspects can be considered:
- Can you check if Edge browser is up-to-date? (it's `Version 126.0.2592.81 (Official build) (64-bit)` on my machine currently)
- Can you try running this [simple GTK program](https://gist.github.com/huycozy/e3971da2fe0c3cea96e2f44030c383bf) which opens an URL on browser on your machine to see if the issue appears?

**Comment by rjcalifornia** [comment] 2024-07-06 22:47
>     * Can you try running this [simple GTK program](https://gist.github.com/huycozy/e3971da2fe0c3cea96e2f44030c383bf) which opens an URL on browser on your machine to see if the issue appears?


You can close this now. It also happens with the simple GTK program, it looks like it might be an issue with KDE or Ubuntu.

Not related to Flutter. Sorry.

**Comment by huycozy** [comment] 2024-07-08 03:19
Thanks for checking that. Closing the issue from here.

**Closed by huycozy** 2024-07-08 03:19 UTC
Labels: in triage
