### ISSUE TITLE
add flutter to an existing desktop app

### ISSUE THREAD

**Issue by tongzifang** [flutter/flutter#117767] opened 2022-12-29 04:33 UTC
Is there a way to make flutter accessible to windows applications as a plugin or module? Like Android(aar) and iOS (xcframwork)

**Comment by darshankawar** [comment] 2022-12-29 07:32
Closing as duplicate of https://github.com/flutter/flutter/issues/80339

**Closed by darshankawar** 2022-12-29 07:32 UTC
Labels: in triage
