### ISSUE TITLE
ar_core issue

### ISSUE THREAD

**Issue by akshat102** [flutter/flutter#61853] opened 2020-07-20 11:26 UTC
i built an application using arcore_flutter plugin. the app works perfectly in debug mode. but it is not working in release mode.
i have attached below the expected and observed outputs of the application kindly help me in resolving the issue.

This is what i get in release mode. i am unable to see the outputs.  
![Screenshot (150)](https://user-images.githubusercontent.com/48102705/87932754-aa14e000-caa9-11ea-8cc6-9f9dfb214cef.png)

This is what i get in debug mode. i can see my outputs(planets).
![Screenshot (151)](https://user-images.githubusercontent.com/48102705/87932764-abdea380-caa9-11ea-8777-263bd00aaab3.png)

Kindly help.!!

**Comment by akshat102** [comment] 2020-07-20 11:29
Outputs of my flutter doctor -v command is as follows:


C:\---------\AndroidStudioProjects\ar_core_example>flutter doctor -v
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.959], locale en-IN)
    • Flutter version 1.17.3 at C:\flutter
    • Framework revision b041144f83 (7 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\-------\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\-----\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • GM1911           • 5a78b3ea • android-arm64 • Android 9 (API 28)
    • Redmi Note 5 Pro • 92ec6a26 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by iapicca** [comment] 2020-07-20 11:45
Hi @akshat102 
From what I can see, the issue is related to the 3rd party plugin [arcore_flutter_plugin](https://pub.dev/packages/arcore_flutter_plugin)  rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/giandifra/arcore_flutter_plugin/issues).

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-20 11:45 UTC
