### ISSUE TITLE
[team] flutter_gallery_ios32__transition_perf flakes "Original error: Bad state: The client closed with pending request "ext.flutter.driver""

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#60559] opened 2020-06-29 22:01 UTC
This test passes locally in attempts by myself and @jmagman, but failed twice in the devicelab, while passing on a third try (all on the same host, mac 11. This is a subset of the devicelab logs:

```
2020-06-29T13:35:45.473687: stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.479773: stdout: 
stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.487072: stdout: 
stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.497545: stdout: 
stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.502830: stdout: 
stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.536602: stdout: 
stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.549874: stdout: 
stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.551607: stdout: 
2020-06-29T13:35:45.551681: stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.555817: stdout: 
stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.562232: stdout: 
stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.568375: stdout: 
stdout: [VERBOSE0:compositor_context.cc(89)] Using SaveLayer to protect non-readback surface
2020-06-29T13:35:45.574812: stdout: 
stdout: flutter: > VideoDemo initController "butterfly" 
2020-06-29T13:35:45.586061: stdout: 
stdout: flutter: > VideoDemo initController "bee" 
2020-06-29T13:35:45.592605: stdout: 
stdout: flutter: > VideoDemo dispose
2020-06-29T13:35:45.598697: stdout: 
stdout: flutter: < VideoDemo dispose
2020-06-29T13:35:45.604924: stdout: 
stdout: flutter: > VideoDemo initController "butterfly" 
2020-06-29T13:35:45.631057: stdout: 
stdout: flutter: > VideoDemo initController "bee" 
2020-06-29T13:35:45.642029: stdout: 
stdout: flutter: > VideoDemo dispose
2020-06-29T13:35:45.650979: stdout: 
stdout: flutter: < VideoDemo dispose
2020-06-29T13:36:56.570709: stdout: Xcode build done.                                           72.5s
2020-06-29T13:37:34.524157: stdout:   dart:async/schedule_microtask.dart 50:5                         _startMicrotaskLoop
stdout:   dart:isolate-patch/isolate_patch.dart 118:13                    _runPendingImmediateCallback
stdout:   dart:isolate-patch/timer_impl.dart 404:11                       _Timer._runTimers
stdout:   dart:isolate-patch/timer_impl.dart 428:5                        _Timer._handleMessage
stdout:   dart:isolate-patch/isolate_patch.dart 168:12                    _RawReceivePortImpl._handleMessage
stdout: 
stdout: 
2020-06-29T13:37:34.525599: stdout:   DriverError: Failed to fulfill Scroll due to remote error
stdout:   Original error: Bad state: The client closed with pending request "ext.flutter.driver".
stdout:   Original stack trace:
stdout:   #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
stdout:   #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
stdout:   #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
stdout:   #3      _rootRun (dart:async/zone.dart:1182:47)
stdout:   #4      _CustomZone.run (dart:async/zone.dart:1093:19)
stdout:   #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
stdout:   #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
stdout:   #7      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
stdout:   #8      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
stdout:   #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
stdout:   #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
stdout:   #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
stdout:   #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
stdout:   #13     _rootRun (dart:async/zone.dart:1190:13)
2020-06-29T13:37:34.526147: stdout:   #14     _CustomZone.run (dart:async/zone.dart:1093:19)
stdout:   #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
stdout:   #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
stdout:   #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
stdout:   #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
stdout:   #19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
2020-06-29T13:37:34.526386: stdout:   #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by christopherfujino** [comment] 2020-06-30 00:29
A similar failure occurred previous to my PR landing in https://github.com/flutter/flutter/commit/f6cd2d4b354afa8bb00031b06b78995b8dc0202c, so I am considering this a flake and will re-land.

**Comment by tvolkert** [comment] 2020-07-17 05:47
This has happened 22 out of the last 24 runs of the test.  I'm going to mark the test as flaky and set the priority of this at P2 (where the customer is the Flutter team).

**Comment by Hixie** [comment] 2020-07-21 22:24
cc @goderbauer

**Comment by liyuqian** [comment] 2020-07-22 01:07
My newly added test `flutter_gallery_sksl_warmup_ios32__transition_perf` is flaky probably for the same reason. It executes the driver test of `flutter_gallery_ios32__transition_perf` 3 times so it significantly magnifies the failure chance. Commit https://github.com/flutter/flutter/commit/a74310242e655dc8b4b825e1ed06b7ac78cb3cd2 is the last one that successfully ran my test so the flaky regression probably started somewhere near that commit 16 days ago.

Meanwhile, it seems to me that many of our flaky devicelab tests (not just this issue) are related with VMService connection and the `flutter_driver` package (lost connection, driver timeout, memory issue caused by a huge amount of tracing events, ...). @CareF is working on host-independent performance tests that remove the dependency of `flutter_driver`, VMService, and the host connection (see https://github.com/flutter/flutter/pull/61509 for an example). We might be able to significantly reduce the flaky rate and increase our team velocity by migrating some of the most flaky tests to be host-independent.

**Comment by CareF** [comment] 2020-07-22 01:14
> Meanwhile, it seems to me that many of our flaky devicelab tests (not just this issue) are related with VMService connection and the `flutter_driver` package (lost connection, driver timeout, memory issue caused by a huge amount of tracing events, ...). @CareF is working on host-independent performance tests that remove the dependency of `flutter_driver`, VMService, and the host connection (see #61509 for an example). We might be able to significantly reduce the flaky rate and increase our team velocity by migrating some of the most flaky tests to be host-independent.

Technically it's still indirectly depending on `flutter_driver` via `e2e`, which is what we need for run the test on a host-device structure, but by removing the dependence of timeline, we can avoid #59263.

**Comment by liyuqian** [comment] 2020-07-22 01:19
@CareF : your commit https://github.com/flutter/flutter/commit/c3217dac7fca317af138781e69c6f064038b9e03 is very close to https://github.com/flutter/flutter/commit/a74310242e655dc8b4b825e1ed06b7ac78cb3cd2 (the last commit to successfully run of my test). Can you please check if c3217dac7fca317af138781e69c6f064038b9e03 made the test more flaky? The ios32 test is using the iPhone 4s which Ray sends you.

**Comment by CareF** [comment] 2020-07-22 02:19
@liyuqian I'll try but very not likely. The related file `dev/integration_tests/flutter_gallery/test_driver/transitions_perf_test.dart` had already `await` this 4 years ago. #60774 is to make others being consistent with that.

**Comment by CareF** [comment] 2020-07-22 05:00
> @CareF : your commit [c3217da](https://github.com/flutter/flutter/commit/c3217dac7fca317af138781e69c6f064038b9e03) is very close to [a743102](https://github.com/flutter/flutter/commit/a74310242e655dc8b4b825e1ed06b7ac78cb3cd2) (the last commit to successfully run of my test). Can you please check if [c3217da](https://github.com/flutter/flutter/commit/c3217dac7fca317af138781e69c6f064038b9e03) made the test more flaky? The ios32 test is using the iPhone 4s which Ray sends you.
> 
> BTW, other than saving the timeline tracing events, I believe host-independent tests could also significantly reduce flakiness by removing the need of driving the app through VMService connection. All widget controlling will be happening purely on device without relying on network connections.

I'm not able to reproduce the error message for `flutter_gallery_sksl_warmup_ios32__transition_perf` because I failed with:
```
[flutter_gallery_sksl_warmup_ios32__transition_perf] [STDOUT] stdout: Error output from Xcode build:
[flutter_gallery_sksl_warmup_ios32__transition_perf] [STDOUT] stdout: ↳
[flutter_gallery_sksl_warmup_ios32__transition_perf] [STDOUT] stdout:     ** BUILD FAILED **
[flutter_gallery_sksl_warmup_ios32__transition_perf] [STDOUT] stdout: 
[flutter_gallery_sksl_warmup_ios32__transition_perf] [STDOUT] stdout: 
[flutter_gallery_sksl_warmup_ios32__transition_perf] [STDOUT] stdout: Xcode's output:
[flutter_gallery_sksl_warmup_ios32__transition_perf] [STDOUT] stdout: ↳
[flutter_gallery_sksl_warmup_ios32__transition_perf] [STDOUT] stdout:     /Users/minglyu/flutter/dev/integration_tests/flutter_gallery/flutter_01.sksl.json does not exist.
```

Other than that, I can't see constant flaky with or without #60774 using `flutter drive -t test_driver/transitions_perf.dart -d iphone --profile --trace-startup` (under flutter_gallery dir) or `dart bin/run.dart -t flutter_gallery_ios32__transition_perf` (under devicelab dir) and I only observed it once out of >10 runs after I run multiple `dart bin/run.dart -t flutter_gallery_sksl_warmup_ios32__transition_perf`

Running on iPhone 4s with iOS 9.6.3.
xcode version
```bash
$ xcodebuild -version
Xcode 11.5
Build version 11E608c
```
@liyuqian

**Comment by liyuqian** [comment] 2020-07-22 18:07
Thanks @CareF for the investigation. I'm glad that we've ruled out c3217da. I just double checked the devicelab error message on `flutter_gallery_sksl_warmup_ios32__transition_perf ` which is like the following and similar to the one in https://github.com/flutter/flutter/issues/60559#issue-647700363. Let's discuss offline how you get a different error message in our next meeting.
```
2020-07-21T16:28:44.406159: run stdout: [   +1 ms] exiting with code 0
2020-07-21T16:28:44.406991: stdout: [   +1 ms]   DriverError: Failed to fulfill Tap due to remote error
2020-07-21T16:28:44.407338: stdout: [        ]   Original error: Bad state: The client closed with pending request "ext.flutter.driver".
stdout: [        ]   Original stack trace:
stdout: [        ]   #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)```

**Comment by zanderso** [comment] 2020-08-10 16:40
Was the root cause of this issue isolated? Will switching to the host-independent setup address the root cause?

**Comment by CareF** [comment] 2020-08-10 18:12
@zanderso The host-independent setup (#62064) will land soon. 
I'm not able to reproduce the error message locally so I can't say anything about finding the root cause.

**Comment by goderbauer** [comment] 2020-08-26 21:33
I see that #62064 landed. Did that help?

**Comment by liyuqian** [comment] 2020-08-26 22:04
According to [this table][3], flutter_gallery__transition_perf_e2e_ios32's flaky rate is about 2% while flutter_gallery_ios32__transition_perf's flaky rate is about 10%.

Most perf metrics seems to be quite close between [flutter_gallery__transition_perf_e2e_ios32 and flutter_gallery_ios32__transition_perf][1], except the worst rasterization time.

[The worst rasterization time is bi-modal and it seems that the e2e version is more likely to get the slower time.][2]

If we're Ok with those metrics and the non-e2e version is too flaky, we can probably close this by turning off the non-e2e tests and only preserve the e2e test. CC @CareF  

[1]: https://flutter-flutter-perf.skia.org/e/?keys=X5665bdef4ba6dcf7c72460efc67eeffd
[2]: https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dflutter_gallery__transition_perf_e2e_ios32%26test%3Dflutter_gallery_ios32__transition_perf
[3]: https://docs.google.com/document/d/1rTLxAxsshEir-B2vE6DU_MaqMMusOdCgLGEGpBYG3CM/edit#bookmark=id.uqv7pxvy90wc

**Comment by CareF** [comment] 2020-08-27 04:43
I think the worst rasterization time is a very unstable number when changing detailed implementation: this is not smoothed by other samples and as long as there's a single crazy frame this number changes significantly. I would trust more on the my result with `FrameTiming`, since in the old test the times are calculated from timestamps, and the number of the frame building time and  rasterization time samples are not always agree, I have reason to doubt if we get any mixing of timeline events for the old numbers.

**Comment by zanderso** [comment] 2020-08-27 15:02
Do we know the root cause of the worst rasterization time being bimodal?

**Comment by liyuqian** [comment] 2020-08-28 07:22
I believe the bimodal benchmark is caused by https://github.com/flutter/flutter/issues/64781. I also created another issue https://github.com/flutter/flutter/issues/64778 for the difference between e2e and flutter_driver perf tests. That difference should be fixed by https://github.com/flutter/flutter/pull/64780.

**Comment by liyuqian** [comment] 2020-09-08 19:55
https://github.com/flutter/flutter/pull/65415 should fix this.

Copied from the PR description of #65415:

> flutter_gallery__transition_perf_e2e_ios32 will be replacing this flaky
test and all performance metrics are quite close:
>
> https://flutter-flutter-perf.skia.org/e/?queries=test%3Dflutter_gallery__transition_perf_e2e_ios32%26test%3Dflutter_gallery_ios32__transition_perf
>
> In the future, one can also compare the historical performance trend by
adding those two tests in the same plot.

**Closed** 2020-09-08 22:55 UTC
Labels: P2, framework, passed secondary triage, platform-ios, team, team: flakes, team: infra
