### ISSUE TITLE
flutter_advanced_networkimage: The superclass, 'PictureProvider<AdvancedNetworkSvg>', has no unnamed constructor that takes no arguments. 

### ISSUE THREAD

**Issue by ReineVanessa** [flutter/flutter#82676] opened 2021-05-17 06:53 UTC
Hello here,
I have a project that was working fine, but after the flutter update, i got many errors because of the outdated podfile, that i tried to solve with some recommandations found on different blogs.

now i have this as the current last error i have to solve,

`
../../../Flutter/.pub-cache/git/flutter_advanced_networkimage-f0f599fb89c494d9158fb6f13d4870582f8ecfcb/lib/src/provider/flutter_advanced_networksvg.dart:17:9: Error: The superclass, 'PictureProvider<AdvancedNetworkSvg>', has no unnamed constructor that takes no arguments.
  const AdvancedNetworkSvg(
        ^^^^^^^^^^^^^^^^^^

Command PhaseScriptExecution failed with a nonzero exit code. 
`

my pubspec.yaml looks like this fr this dependency
`
flutter_advanced_networkimage: 
    git:
      url: https://github.com/mchome/flutter_advanced_networkimage
      ref: master
`

Has anybody faced this problem with a Flutter app please?

**Comment by TahaTesser** [comment] 2021-05-17 13:20
Hi @ReineVanessa 
You seem to be using a `DISCONTINUED` package
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. 
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-17 13:20 UTC
Labels: in triage
