### ISSUE TITLE
[tool_crash] RPCError - App crashes after adding awesome_notification and icon_notification icon

### ISSUE THREAD

**Issue by kcibdev** [flutter/flutter#159728] opened 2024-12-03 15:04 UTC
## Command
```sh
flutter run --verbose
```

## Steps to Reproduce
1. run flutter 

## Logs
RPCError
```console
#0      VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#2      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#3      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4460], locale en-US)
    [32m•[39m Flutter version 3.24.3 on channel stable at C:\Developer\Flutter\SDK\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2663184aa7 (3 months ago), 2024-09-11 16:27:48 -0500
    [32m•[39m Engine revision 36335019a8
    [32m•[39m Dart version 3.5.3
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\Nnam0\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.6)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.11.35431.28
    [32m•[39m Windows 10 SDK version 10.0.22621.0
    [31m✗[39m The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[32m[✓][39m VS Code (version 1.95.3)
    [32m•[39m VS Code at C:\Users\Nnam0\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.102.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    [32m•[39m Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4460]
    [32m•[39m Edge (web)                   • edge          • web-javascript • Microsoft Edge 131.0.2903.70

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
awesome_notifications-0.10.0
device_info_plus-11.1.1
firebase_core-3.8.0
firebase_core_web-2.18.1
firebase_messaging-15.1.5
firebase_messaging_web-3.9.4
flutter_native_contact_picker_plus-0.0.3
package_info_plus-8.1.1
path_provider-2.1.5
path_provider_android-2.2.14
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
printing-5.13.4
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.1
url_launcher_linux-3.2.1
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
webview_flutter-4.10.0
webview_flutter_android-4.1.0
webview_flutter_wkwebview-3.16.3

**Comment by danagbemava-nc** [comment] 2024-12-04 07:15
Closing this as a duplicate of https://github.com/flutter/flutter/issues/154903

**Closed by danagbemava-nc** 2024-12-04 07:15 UTC
Labels: in triage
