### ISSUE TITLE
defaultTargetPlatform on web thinks it's Android (on Linux & Windows)

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#61321] opened 2020-07-12 15:06 UTC
defaultTargetPlatform returns TargetPlatform.android for web builds (on Linux & Windows)

There is already a closed ticket (#43633), but the related PR (https://github.com/flutter/flutter/pull/56081) fixed it only for macOS & iOS.

**Comment by TahaTesser** [comment] 2020-07-13 13:08
Related https://github.com/flutter/flutter/issues/60271

**Comment by gspencergoog** [comment] 2020-07-15 23:02
Actually a duplicate of #60271, because the theme gets its information from `defaultTargetPlatform`.

**Closed by gspencergoog** 2020-07-15 23:02 UTC
Labels: a: desktop, found in release: 1.20, framework, has reproducible steps, platform-linux, platform-web, platform-windows
