### ISSUE TITLE
flutter_plugin_tools exits Error 255

### ISSUE THREAD

**Issue by Sameerkash** [flutter/flutter#75828] opened 2021-02-11 05:09 UTC
## Steps to Reproduce

1. Clone flutter/plugins
2. Run flutter pub global run flutter_plugin_tools format 
**Expected results:** 

Formats all files

**Actual results:** 

Exits with code 255

<details> 
<summary>logs</summary> 

```bash
ios/Runner/GeneratedPluginRegistrant.h" in /Users/sameerkashyap/Documents/Projects/plugins/packages
Unhandled exception:
ProcessException: No such file or directory
  Command: clang-format -i --style=Google /Users/sameerkashyap/Documents/Projects/plugins/packages/android_alarm_manager/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/android_alarm_manager/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/android_alarm_manager/ios/Classes/AndroidAlarmManagerPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/android_intent/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/android_intent/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/android_intent/ios/Classes/AndroidIntentPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/battery/battery/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/battery/battery/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/battery/battery/ios/Classes/FLTBatteryPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/camera/camera/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/camera/camera/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/camera/camera/ios/Classes/CameraPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/connectivity/connectivity/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/connectivity/connectivity/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/connectivity/connectivity/ios/Classes/FLTConnectivityPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/connectivity/connectivity_for_web/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/connectivity/connectivity_macos/macos/Classes/IPHelper.h /Users/sameerkashyap/Documents/Projects/plugins/packages/connectivity/connectivity_macos/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/connectivity/connectivity_macos/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/device_info/device_info/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/device_info/device_info/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/device_info/device_info/ios/Classes/FLTDeviceInfoPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/espresso/example/ios/Runner/Runner-Bridging-Header.h /Users/sameerkashyap/Documents/Projects/plugins/packages/espresso/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/espresso/ios/Classes/EspressoPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/file_selector/file_selector_web/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/flutter_plugin_android_lifecycle/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/flutter_plugin_android_lifecycle/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/flutter_plugin_android_lifecycle/ios/Classes/FlutterAndroidLifecyclePlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapMarkerController.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/FLTGoogleMapsPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/JsonConversions.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapPolygonController.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapPolylineController.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/FLTGoogleMapTileOverlayController.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapCircleController.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_maps_flutter/google_maps_flutter_web/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_sign_in/extension_google_sign_in_as_googleapis_auth/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_sign_in/extension_google_sign_in_as_googleapis_auth/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_sign_in/google_sign_in/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_sign_in/google_sign_in/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_sign_in/google_sign_in/ios/Classes/FLTGoogleSignInPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/google_sign_in/google_sign_in_web/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/image_picker/image_picker/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/image_picker/image_picker/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/image_picker/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.h /Users/sameerkashyap/Documents/Projects/plugins/packages/image_picker/image_picker/ios/Classes/FLTImagePickerMetaDataUtil.h /Users/sameerkashyap/Documents/Projects/plugins/packages/image_picker/image_picker/ios/Classes/FLTImagePickerImageUtil.h /Users/sameerkashyap/Documents/Projects/plugins/packages/image_picker/image_picker/ios/Tests/ImagePickerTestImages.h /Users/sameerkashyap/Documents/Projects/plugins/packages/image_picker/image_picker_for_web/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/in_app_purchase/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/in_app_purchase/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/in_app_purchase/ios/Classes/FIAPReceiptManager.h /Users/sameerkashyap/Documents/Projects/plugins/packages/in_app_purchase/ios/Classes/FIAObjectTranslator.h /Users/sameerkashyap/Documents/Projects/plugins/packages/in_app_purchase/ios/Classes/FIAPaymentQueueHandler.h /Users/sameerkashyap/Documents/Projects/plugins/packages/in_app_purchase/ios/Classes/FIAPRequestHandler.h /Users/sameerkashyap/Documents/Projects/plugins/packages/in_app_purchase/ios/Tests/Stubs.h /Users/sameerkashyap/Documents/Projects/plugins/packages/integration_test/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/integration_test/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/integration_test/ios/Classes/IntegrationTestIosTest.h /Users/sameerkashyap/Documents/Projects/plugins/packages/integration_test/ios/Classes/IntegrationTestPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/ios_platform_images/example/ios/Runner/Runner-Bridging-Header.h /Users/sameerkashyap/Documents/Projects/plugins/packages/ios_platform_images/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/ios_platform_images/ios/Classes/IosPlatformImagesPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/ios_platform_images/ios/Classes/UIImage+ios_platform_images.h /Users/sameerkashyap/Documents/Projects/plugins/packages/local_auth/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/local_auth/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/local_auth/ios/Classes/FLTLocalAuthPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/package_info/macos/Classes/FLTPackageInfoPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/package_info/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/package_info/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/package_info/ios/Classes/FLTPackageInfoPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/linux/my_application.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/linux/flutter/generated_plugin_registrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/windows/runner/utils.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/windows/runner/run_loop.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/windows/runner/win32_window.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/windows/runner/resource.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/windows/runner/flutter_window.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/example/windows/flutter/generated_plugin_registrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider/ios/Classes/FLTPathProviderPlugin.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_linux/example/linux/my_application.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_linux/example/linux/flutter/generated_plugin_registrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_macos/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_macos/example/ios/Runner/GeneratedPluginRegistrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_windows/example/windows/runner/utils.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_windows/example/windows/runner/run_loop.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_windows/example/windows/runner/win32_window.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_windows/example/windows/runner/resource.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_windows/example/windows/runner/flutter_window.h /Users/sameerkashyap/Documents/Projects/plugins/packages/path_provider/path_provider_windows/example/windows/flutter/generated_plugin_registrant.h /Users/sameerkashyap/Documents/Projects/plugins/packages/quick_actions/example/ios/Runner/AppDelegate.h /Users/sameerkashyap/Documents/Projects/plugins/packages/quick_actions/example/ios/Runner/GeneratedPluginRegistrant.h
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      ProcessRunner.runAndStream (package:flutter_plugin_tools/src/common.dart:390:49)
#3      FormatCommand._formatCppAndObjectiveC (package:flutter_plugin_tools/src/format_command.dart:98:27)
<asynchronous suspension>
#4      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:47:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#6      main.<anonymous closure> (package:flutter_plugin_tools/src/main.dart)
<asynchronous suspension>
pub finished with exit code 255
```

</details>

<details>
    <summary>flutter doctor -v</summary>

```
sameerkashyap@Sameers-MacBook-Pro packages % flutter doctor -v
[✓] Flutter (Channel dev, 1.26.0-17.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-US)
    • Flutter version 1.26.0-17.2.pre at /Users/sameerkashyap/Documents/Development/flutter
    • Framework revision 79b49b9e10 (7 days ago), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sameerkashyap/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2021-02-11 11:27
Hi @Sameerkash 
This is a duplicate of https://github.com/flutter/flutter/issues/33964
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-11 11:27 UTC
