### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by AIYO77** [flutter/flutter#146886] opened 2024-04-17 11:58 UTC
## Command
```
flutter attach
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:325:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.0, on macOS 14.3 23D56 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.0 at /Volumes/P4800X/xw/flutter/sdk/flutter300
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (1 year, 11 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.16.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.16.1+1-LTS-1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.15.2

[!] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.88.1)
    • VS Code at /Volumes/P4800X/app/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • MI 9 (mobile)   • 192.168.6.149:5555        • android-arm64 • Android 10 (API 29)
    • iPhone (mobile) • 00008030-001E508C1ED0802E • ios           • iOS 17.4.1 21E236
    • macOS (desktop) • macos                     • darwin-x64    • macOS 14.3 23D56 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+2
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.flutter_module
**iOS bundle identifier**: com.example.flutterModule
**Creation channel**: stable
**Creation framework version**: 300451adae589accbece3490f4396f10bdf15e6e
### Plugins
flutter_boost-1c7b7c967a5917a83b5d060685bdadf7de825ee5
fluttertoast-8.2.4
image_gallery_saver-21f92e5f99d5b7d6198735eb06d2d4cd0f81bf82
path_provider_linux-2.1.10
path_provider_windows-2.1.6
permission_handler-11.0.1
permission_handler_android-11.1.0
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0

**Comment by danagbemava-nc** [comment] 2024-04-17 12:49
Closing this as a duplicate of https://github.com/flutter/flutter/issues/77581

**Closed by danagbemava-nc** 2024-04-17 12:49 UTC
Labels: in triage
