### ISSUE TITLE
Textfield text not visible on flutter web

### ISSUE THREAD

**Issue by GMC254** [flutter/flutter#40039] opened 2019-09-07 19:52 UTC
## TextField text color defaults to transparent when used in flutter web. 
Same applies to TextFormField. The cursor doesn't move and text typed is not visible. 

Looking through chrome developer tools (Version 76.0.3809.132 (Official Build) (64-bit)), the text
defaults to transparent despite efforts to change its color through vscode. On unchecking the transparent box on chrome developer tools, the text becomes visible but cursor doesn't move from starting point. I have also tried setting enabled to true among other code settings but it does not work. 

## Steps to Reproduce
```
import 'package:flutter_web/material.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Hello, World!',
            ),
            ListTile(
              title: Text('Main header'),
              subtitle: TextField(
                style: TextStyle(color: Colors.black),
                enabled: true,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

![code2](https://user-images.githubusercontent.com/31553284/64479465-09cf0900-d1c0-11e9-8067-9c8db725bd10.png)
![code3](https://user-images.githubusercontent.com/31553284/64479467-0cc9f980-d1c0-11e9-9514-159b9e6c3a88.png)

##Flutter Analyze:
```
flutter analyze
No issues found! (ran in 6.8s)
```
##Flutter Doctor
```
! Doctor found issues in 1 category.
PS C:\...herro> flutter doctor      
Doctor summary (to see all details, run flutter doctor -v):     
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft      
    Windows [Version 10.0.18362.295], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK    version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.38.0)
[!] Connected device
    ! No devices available
```

**Comment by jonahwilliams** [comment] 2019-09-08 17:29
Please do not include screenshots of code. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example.

**Comment by GMC254** [comment] 2019-09-08 17:47
Sorry for that, it's just the basic 'hello world' demo web app with the Textfield as a ListTile's child. I have edited the file to include the code above.

**Comment by jonahwilliams** [comment] 2019-09-08 18:32
I can't reproduce on 5a3a46ada2417957415c58a5a1adff0fc11f7fc5.

Please try the unforked workflow at https://github.com/flutter/flutter/wiki/Building-a-web-application-with-Flutter  and see if you still have the issue

**Comment by xeu100** [comment] 2019-09-08 18:38
I can't seem to run my project with the unforked webflow at the moment.

**Comment by GMC254** [comment] 2019-09-08 18:57
Thanks. Will do.

**Comment by xeu100** [comment] 2019-09-08 19:03
Any solution for people that can't run the unforked webflow?

**Comment by tauu** [comment] 2019-09-08 23:10
@xeu100 A fix for this Issue is provided in PR https://github.com/flutter/flutter_web/pull/125 :-)

**Comment by GMC254** [comment] 2019-09-09 14:40
Due to some limitations, I also can't use the unforked work flow at the moment

> I can't reproduce on [5a3a46a](https://github.com/flutter/flutter/commit/5a3a46ada2417957415c58a5a1adff0fc11f7fc5).
> 
> Please try the unforked workflow at https://github.com/flutter/flutter/wiki/Building-a-web-application-with-Flutter and see if you still have the issue

Due to some limitations, I also can't use the unforked work flow at the moment.

**Comment by alex89607** [comment] 2019-09-10 06:10
The same error, there is invisible text in text flutter form. It is web-app, I have tested it in firefox 69.0 and chrome 76.0.3809.132 . I tried use TextFormField from flutter Developoers guide(https://api.flutter.dev/flutter/widgets/Form-class.html) and tried reinstall flutter and also generate new project by stagehand but nothing happened.

Its look like a invisible font - I pressing the key, on the screen nothind display. But if I will select  - that text suddenly appear! and if I make that region  copy to other text window(other application, like Notepad), text also became visible.

Flutter 1.9.1+hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2d2a1ffec9 (3 days ago) • 2019-09-06 18:39:49 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

**Comment by dtoledos** [comment] 2019-09-11 00:13
I am using https://flutter.dev/docs/get-started/web with the version 1.9 is working all well :)

**Comment by piedcipher** [comment] 2019-09-13 14:47
I'm facing the same issue as @alex89607

**Comment by GMC254** [comment] 2019-09-18 04:52
The unforked workflow works. Thanks for the pointers.

**Comment by nturgut** [comment] 2019-09-18 19:01
Thanks for the response. I'm closing the issue.

**Closed by nturgut** 2019-09-18 19:01 UTC
Labels: a: text input, ☸ platform-web
