### ISSUE TITLE
[proposal] Support compile the Android engine on Windows

### ISSUE THREAD

**Issue by luori-mvp77** [flutter/flutter#48072] opened 2020-01-02 12:30 UTC
I try to do compile engine on Win10 and use local-engine to run my app recently.

1. I can compile flutter engine on my win10 env, Although there has some unicode error(i fixed them)
2. I found the productions of compile engine with android mode exclude flutter.jar , so i try to run app  use local-engine use :
`flutter run --local-engine-src-path=e:\engineX\e1213a\src --local-engine=android_debug_arm64` [flutter-tool](https://github.com/flutter/flutter/wiki/The-flutter-tool),  but it takes error:
```
The file e:\engineX\e1213a\src\out\android_debug_arm64\flutter_embedding_debug.pom wasn't found in the local engine out directory.
```

then i copy a flutter_embedding_debug.pom from linux production, but take another exception:
```
C:\Users\xxx1\AppData\Local\Temp\flutter_tool_local_engine_repo.552c6b38-2d58-11ea-a188-b885849b2818\io\flutter\flutter_embedding_debug\1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695\flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom->E:\engine\src\out\android_debug_unopt_arm64\flutter_embedding_debug.pom: FileSystemException: Cannot create link, path =
'C:\Users\L00446~1\AppData\Local\Temp\flutter_tool_local_engine_repo.552c6b38-2d58-11ea-a188-b885849b2818\io\flutter\flutter_embedding_debug\1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695\flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom' (OS Error: 系统找不到指定的路径。
```

i think maybe mainly reason is Windows not support length of path more then  260 characters .

So , please let me know if  flutter engine already support compile on windows env and if ok, can i use local-engine to specify my engine version. thanks.

**Comment by luori-mvp77** [comment] 2020-01-03 02:01
@VladyslavBondarenko  Can you supply help to solve the problem.

**Comment by luori-mvp77** [comment] 2020-01-04 12:59
No guys can reply this issue?

**Comment by chinmaygarde** [comment] 2020-06-13 01:08
Compiling the Android engine on Windows and using that for local development is not a supported workflow.

**Comment by jonahwilliams** [comment] 2022-05-10 19:26
FWIW I just built an android engine on linux and when i trying to run with a local engine I also get "Exception: The file /home/jonahwilliams/engine/src/out/android_profile_arm64/flutter_embedding_debug.pom wasn't found in the local engine out
directory."

What is broken here?

**Comment by jonahwilliams** [comment] 2022-05-10 19:27
ahh that is because I built the wrong variant - we should fix this error message

**Comment by jonahwilliams** [comment] 2024-08-13 03:35
Duplicate of https://github.com/flutter/flutter/issues/13841

**Closed by jonahwilliams** 2024-08-13 03:35 UTC
Labels: engine, platform-windows, c: proposal, P3, team-engine, triaged-engine
