### ISSUE TITLE
Flutter missing libflutter.so crashes

### ISSUE THREAD

**Issue by aldwnesx** [flutter/flutter#53461] opened 2020-03-28 04:26 UTC
I used app bundle and it keeps crashing on pixel 2 device.

I searched for hours for solution and they suggest using android-arm64 as target etc.

What should I actually do?

**Comment by canewsin** [comment] 2020-03-28 04:41
submit a minimal code to reproduce issue.

**Comment by aldwnesx** [comment] 2020-03-28 04:45
> submit a minimal code to reproduce issue.

can you tell me which codes i need to submit?

**Comment by iapicca** [comment] 2020-03-30 07:58
Hi @aldwnesx 
did you try to proposed [solution](https://github.com/flutter/flutter/issues/53411#issuecomment-605385160)?
Thank you

**Comment by aldwnesx** [comment] 2020-04-01 07:47
> Hi @aldwnesx
> did you try to proposed [solution](https://github.com/flutter/flutter/issues/53411#issuecomment-605385160)?
> Thank you

still crashing

**Comment by iapicca** [comment] 2020-04-03 08:00
Hi @aldwnesx 
according to your [message](https://github.com/flutter/flutter/issues/53459#issuecomment-607091010)  this issue seems to be a duplicate of the referenced [issue](https://github.com/flutter/flutter/issues/53461) 

Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-04-03 08:00 UTC
