### ISSUE TITLE
[Android] TakeSnapshot Crashes app

### ISSUE THREAD

**Issue by GeeRajasekaran** [flutter/flutter#141005] opened 2024-01-05 05:35 UTC
### Steps to reproduce

      try {
        // Take a snapshot of the map
        var mapImage = await controller.takeSnapshot();
       
      } catch (e, stacktrace) {
        // Log the error and stack trace for debugging
        print("Error taking snapshot: $e");
        print("Stacktrace: $stacktrace");
      }

### Expected results

need to get snapshot of map

### Actual results

```
FATAL EXCEPTION: main
E/AndroidRuntime(26987): Process: com., PID: 2
E/AndroidRuntime(26987): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
E/AndroidRuntime(26987): 	at android.graphics.Canvas.<init>(Canvas.java:113)
E/AndroidRuntime(26987): 	at com.google.maps.api.android.lib6.impl.a.a(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:3)
E/AndroidRuntime(26987): 	at com.google.maps.api.android.lib6.phoenix.dn.run(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:9)
E/AndroidRuntime(26987): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(26987): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26987): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(26987): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(26987): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(26987): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26987): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(26987): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/Process (26987): Sending signal. PID: 26987 SIG: 9
Lost connection to device.
```

### Code sample

<details open><summary>Code sample</summary>

```dart
final GoogleMapController controller = await mapController.future;

      try {
        // Take a snapshot of the map
        var mapImage = await controller.takeSnapshot();
       
      } catch (e, stacktrace) {
        // Log the error and stack trace for debugging
        print("Error taking snapshot: $e");
        print("Stacktrace: $stacktrace");
      }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
FATAL EXCEPTION: main
E/AndroidRuntime(26987): Process: com., PID: 2
E/AndroidRuntime(26987): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
E/AndroidRuntime(26987): at android.graphics.Canvas.(Canvas.java:113)
E/AndroidRuntime(26987): at com.google.maps.api.android.lib6.impl.a.a(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:3)
E/AndroidRuntime(26987): at com.google.maps.api.android.lib6.phoenix.dn.run(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:9)
E/AndroidRuntime(26987): at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(26987): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26987): at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(26987): at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(26987): at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(26987): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26987): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(26987): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/Process (26987): Sending signal. PID: 26987 SIG: 9
Lost connection to device.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (4 available)
[✓] Network resources


```

</details>

**Comment by danagbemava-nc** [comment] 2024-01-05 09:57
Hi @GeeRajasekaran, what version of `google_maps_flutter` & `google_maps_flutter_android` are you using? 

Also, what device(s) are you seeing this on?

**Comment by GeeRajasekaran** [comment] 2024-01-05 10:09
Hi,
I am using google_maps_flutter-2.5.1 and google_maps_flutter_android-2.6.1.
I am trying my simulator, Pixel 6a, Android 14.0.

**Comment by danagbemava-nc** [comment] 2024-01-08 06:55
Hi @GeeRajasekaran, do you have markers or any similar items displayed on your map at the time you try to take the snapshot? I used the code sample below but I can't seem to reproduce the crash. I tested on a Pixel 7 running android 14. Can you run the code sample below to see if you experience the crash with it? If not, please provide a complete minimal reproducible code sample so that we can investigate this issue. 

Thank you

<details>
<summary>code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MapCrash());
}

class MapCrash extends StatelessWidget {
  const MapCrash({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller =
      Completer<GoogleMapController>();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    try {
        // Take a snapshot of the map
        var mapImage = await controller.takeSnapshot();

        print(mapImage);
       
      } catch (e, stacktrace) {
        // Log the error and stack trace for debugging
        print("Error taking snapshot: $e");
        print("Stacktrace: $stacktrace");
      }
  }
}
```
</details>

**Comment by GeeRajasekaran** [comment] 2024-01-09 08:06
Yes, I have markers during the snapshot process, and even though I have commented out all the code relating to markers, the snapshot still crashes. 

  _markers.add(Marker(
          markerId: const MarkerId('Home'),
          position: LatLng(double.parse(locationMap.latitude),
              double.parse(locationMap.longitude))));

Steps to reproduce.
You need to try multiple times from one screen to the next while taking a snapshot it crashes.

Crash log:

D/AndroidRuntime(24641): Shutting down VM
E/AndroidRuntime(24641): FATAL EXCEPTION: main
E/AndroidRuntime(24641): Process: com., PID:
E/AndroidRuntime(24641): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
E/AndroidRuntime(24641): 	at android.graphics.Canvas.<init>(Canvas.java:113)
E/AndroidRuntime(24641): 	at com.google.maps.api.android.lib6.impl.a.a(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:3)
E/AndroidRuntime(24641): 	at com.google.maps.api.android.lib6.phoenix.dn.run(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:9)
E/AndroidRuntime(24641): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(24641): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24641): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(24641): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(24641): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(24641): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24641): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(24641): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/Process (24641): Sending signal. PID: 24641 SIG: 9
Lost connection to device.

https://github.com/flutter/flutter/assets/17061447/6bf1eb72-4cf7-42b9-ac3d-b610d68c26a6

**Comment by danagbemava-nc** [comment] 2024-01-10 06:51
Hi @GeeRajasekaran, can you please provide a complete minimal reproducible code sample based on the video shared in https://github.com/flutter/flutter/issues/141005#issuecomment-1882580091 so that we can investigate this? 

Thank you

**Comment by GeeRajasekaran** [comment] 2024-01-11 07:44
Code:

class MapSample extends StatefulWidget {
  const MapSample({
    Key? key,
  }) : super(key: key);

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  
  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  ///map controller
  Completer<GoogleMapController> mapController = Completer();
  final Set<Marker> _markers = {};

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    loadMap();
  }

  void loadMap() async {
    final GoogleMapController controller = await mapController.future;

    Future.delayed(const Duration(seconds: 2), () {
      controller.animateCamera(CameraUpdate.newCameraPosition(const CameraPosition(
        target: LatLng(37.334606, -122.009102),
        zoom: 16.0,
      )));
      _markers.add(const Marker(
          markerId: MarkerId('Home'),
          position: LatLng(37.334606, -122.009102)));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Map"),
      ),
      body: Padding(
        padding: const EdgeInsets.only(left: 10, right: 10, top: 24),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Pulled from your current Location',
                style: TextStyle(
                    fontFamily: 'Nunito',
                    fontWeight: FontWeight.w400,
                    color: Colors.red),
              ),
              InkWell(
                onTap: () {
                  showDialog<String>(
                    context: context,
                    barrierDismissible: false,
                    builder: (BuildContext context) => AlertDialog(
                      //title: const Text('AlertDialog Title'),
                      content: const Text(
                          'Your current location will override existing location!'),
                      actions: <Widget>[
                        TextButton(
                          onPressed: () => Navigator.pop(context),
                          child: const Text('Cancel'),
                        ),
                        TextButton(
                          onPressed: () {
                            Navigator.pop(context);
                          },
                          child: const Text('Confirm'),
                        ),
                      ],
                    ),
                  );
                },
                child: const Text(
                  'Change',
                  style: TextStyle(
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w700,
                      color: Colors.red),
                ),
              )
            ],
          ),
          Container(
              width: double.infinity,
              padding: const EdgeInsets.only(top: 16),
              height: 350,
              child: GoogleMap(
                //mapType: MapType.normal,
                mapType: MapType.hybrid,
                initialCameraPosition: _kGooglePlex,
                onMapCreated: (GoogleMapController controller) {
                  setState(() {
                    if (!mapController.isCompleted) {
                      mapController.complete(controller);
                    }
                  });
                },
                markers: _markers,
              )),
        ]),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: submitImageData,
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }

  void submitImageData() async {
    await photoStringToSent();
  }

  Future<String> photoStringToSent() async {
    String img64 = "";
    try {
      if (true) {
        final GoogleMapController controller = await mapController.future;
        print("Say Hello");
        var mapImage = await controller.takeSnapshot();

        if (mapImage != null) {
          print("Hello");
          showDialog(
              context: context,
              builder: (context) {
                return AlertDialog(
                  content: SizedBox(
                    height: 300,
                    width: 300,
                    child: Image.memory(mapImage),
                  ),
                );
              });
        }
      }
    } catch (e) {
      if (kDebugMode) {
        print(e);
      }
    }

    return jsonEncode([
      {
        "fileB64": img64,
      }
    ]);
  }
}

**Comment by huycozy** [comment] 2024-01-12 06:26
@GeeRajasekaran I can't reproduce the issue with below complete sample code below. But look at your demo video, it seems you click on capture button too quickly, before the map is loaded I think. Can you check if the issue occurs after a while when the map is loaded?

Also, does this happen on a physical device (if you have one to check)?

<details>
<summary>Sample code</summary>

```dart
import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() async {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const FirstScreen(),
        '/second': (context) => const MapSample(),
      },
    ),
  );
}

class FirstScreen extends StatelessWidget {
  const FirstScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('First Screen'),
      ),
      body: Center(
        child: ElevatedButton(
          // Within the `FirstScreen` widget
          onPressed: () {
            // Navigate to the second screen using a named route.
            Navigator.pushNamed(context, '/second');
          },
          child: const Text('Launch screen'),
        ),
      ),
    );
  }
}

class MapSample extends StatefulWidget {
  const MapSample({
    Key? key,
  }) : super(key: key);

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  ///map controller
  Completer<GoogleMapController> mapController = Completer();
  final Set<Marker> _markers = {};

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    loadMap();
  }

  void loadMap() async {
    final GoogleMapController controller = await mapController.future;

    Future.delayed(const Duration(seconds: 2), () {
      controller.animateCamera(CameraUpdate.newCameraPosition(const CameraPosition(
        target: LatLng(37.334606, -122.009102),
        zoom: 16.0,
      )));
      _markers.add(const Marker(markerId: MarkerId('Home'), position: LatLng(37.334606, -122.009102)));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Map"),
      ),
      body: Padding(
        padding: const EdgeInsets.only(left: 10, right: 10, top: 24),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Pulled from your current Location',
                style: TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w400, color: Colors.red),
              ),
              InkWell(
                onTap: () {
                  showDialog<String>(
                    context: context,
                    barrierDismissible: false,
                    builder: (BuildContext context) => AlertDialog(
                      //title: const Text('AlertDialog Title'),
                      content: const Text('Your current location will override existing location!'),
                      actions: <Widget>[
                        TextButton(
                          onPressed: () => Navigator.pop(context),
                          child: const Text('Cancel'),
                        ),
                        TextButton(
                          onPressed: () {
                            Navigator.pop(context);
                          },
                          child: const Text('Confirm'),
                        ),
                      ],
                    ),
                  );
                },
                child: const Text(
                  'Change',
                  style: TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w700, color: Colors.red),
                ),
              )
            ],
          ),
          Container(
              width: double.infinity,
              padding: const EdgeInsets.only(top: 16),
              height: 350,
              child: GoogleMap(
                //mapType: MapType.normal,
                mapType: MapType.hybrid,
                initialCameraPosition: _kGooglePlex,
                onMapCreated: (GoogleMapController controller) {
                  setState(() {
                    if (!mapController.isCompleted) {
                      mapController.complete(controller);
                    }
                  });
                },
                markers: _markers,
              )),
        ]),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: submitImageData,
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }

  void submitImageData() async {
    await photoStringToSent();
  }

  Future<String> photoStringToSent() async {
    String img64 = "";
    try {
      if (true) {
        final GoogleMapController controller = await mapController.future;
        print("Say Hello");
        var mapImage = await controller.takeSnapshot();

        if (mapImage != null) {
          print("Hello");
          showDialog(
              context: context,
              builder: (context) {
                return AlertDialog(
                  content: SizedBox(
                    height: 300,
                    width: 300,
                    child: Image.memory(mapImage),
                  ),
                );
              });
        }
      }
    } catch (e) {
      if (kDebugMode) {
        print(e);
      }
    }

    return jsonEncode([
      {
        "fileB64": img64,
      }
    ]);
  }
}

```
</details>

**Comment by huycozy** [comment] 2024-01-17 04:55
I tried again but still can't reproduce this. But I see there is an filed issue https://github.com/flutter/flutter/issues/127834 which happens in production without reproduction case. Since you can reproduce this, it would be appreciated if you could share the case there. 

Closing this in favor of that issue. Thanks for your patience.

**Closed by huycozy** 2024-01-17 04:55 UTC
Labels: in triage
