### ISSUE TITLE
[web] Canvas Kit issue when using dart:ui/Path.from - BindingError: Tried to invoke ctor of Path with invalid number of parameters (1) - expected (0) parameters instead! #75473

### ISSUE THREAD

**Issue by kaumudpa** [flutter/flutter#76186] opened 2021-02-17 08:22 UTC
#This is a duplicate of - `[web] Canvas Kit issue when using dart:ui/Path.from - BindingError: Tried to invoke ctor of Path with invalid number of parameters (1) - expected (0) parameters instead!`   #75473  . The issue was said to have been fixed, but apparently its not. The issue is still there on Master, Dev & Beta. Please reopen #75473 and close this as i am creating this issue to bring your attention.

**Comment by kaumudpa** [comment] 2021-02-17 08:24
#75473

**Comment by darshankawar** [comment] 2021-02-17 09:08
@kaumudpa 
I verified the issue mentioned in 75473 using latest master ( 1.27.0-2.0.pre.126) and I don't see the issue anymore. The error isn't reproducible.

Running `flutter run -d chrome --web-renderer canvaskit` properly renders the path, as expected.

<img width="626" alt="Screenshot 2021-02-17 at 2 29 10 PM" src="https://user-images.githubusercontent.com/67046386/108180518-df130f00-712c-11eb-9911-125c77386ea5.png">

<details>
<summary>latest master flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.126, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
    • Flutter version 1.27.0-2.0.pre.126 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 50897c98fc (5 hours ago), 2021-02-16 20:13:53 -0800
    • Engine revision 9bcb3bfb0e
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM A260G (mobile)                  • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5556    • android-x86    • Android 8.1.0 (API 27)
      (emulator)
    • macOS (desktop)                    • macos            • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome
      88.0.4324.150

! Doctor found issues in 1 category.

```

</details>

I recommend you to upgrade to latest master and try again to confirm at your end. Since the issue fix is landed in latest master, it'll land soon on latest beta and dev.
I am going ahead and closing this issue as acknowledged, verified and addressed. If you disagree or still facing the issue on latest master, write in comments here and I'll address it.
Thanks.

**Closed by darshankawar** 2021-02-17 09:08 UTC
Labels: in triage
