### ISSUE TITLE
Hot reload received invalid response

### ISSUE THREAD

**Issue by xvrh** [flutter/flutter#55552] opened 2020-04-24 12:19 UTC
From time to time I have this error message when doing a "hot reload" `Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}`.

![Screenshot 2020-04-24 at 14 12 35](https://user-images.githubusercontent.com/5110923/80211612-50ca1b80-8636-11ea-966e-595ba691d8b6.png)

When this happens, this is hard to get back to a correct workflow.
If I "hot restart", the file that I'm currently editing stays "stale": it keeps the old code even when I edit it. It looks like Flutter has a cache issue and does not detect that the file was edited.
I have to stop the app and do a full build again.

Environment:
- Device: iPhone 11 and iOS 13.3
- Host: macOS 10.15.4
- Flutter: beta 1.17.0-3.2.pre (I had the same problem with the previous beta)
- IntelliJ IDEA with flutter plugin 45.1.2

```
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.4 19E287, locale en-BE)
    • Flutter version 1.17.0-3.2.pre at /Users/xavier/projects/flutter_stable
    • Framework revision 2a7bc389f2 (2 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xavier/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6494.35

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (4 available)
    • Moto G 5 Plus   • ZY224FKBCL                • android-arm    • Android 8.1.0 (API 27)
    • Xavier’s iPhone • 00008030-00012D9C0212802E • ios            • iOS 13.3.1
    • Chrome          • chrome                    • web-javascript • Google Chrome 81.0.4044.122
    • Web Server      • web-server                • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by HerrNiklasRaab** [comment] 2020-04-27 08:48
Can confirm this too. @xvrh Do you know a beta build, were this works?

**Comment by orestesgaolin** [comment] 2020-04-30 11:07
After upgrading to newest beta it started to occur again (I don't recall having it in one version before). I did full flutter clean after upgrading to current beta.

```
[✓] Flutter (Channel beta, v1.17.0-3.3.pre, on Mac OS X 10.15.4 19E287, locale pl-PL)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by SebAubin** [comment] 2020-05-11 14:35
Happening to me as well after upgrading to 1.17.0

**Comment by jonahwilliams** [comment] 2020-05-11 16:30
Can anyone that is experiencing this provide logs from flutter run so we can determine where this is happening?

**Comment by SebAubin** [comment] 2020-05-11 16:35
I don't have more than this: 
`Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}` when Hot reloading on iOS on device running iOS 13.3.1 on Flutter 1.17.0

**Comment by jonahwilliams** [comment] 2020-05-11 16:36
you need to gather verbose logs from `flutter run -v`

**Comment by philiplindberg** [comment] 2020-05-11 17:54
Seeing this too, but only under specific circumstances. Seems to start happening after doing a hot restart while debugging on a physical device in VS Code. After doing just a single hot restart, all additional hot reloads return the following error: `Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}`. 

Not seeing the error when running from the terminal (via `flutter run -v`) or when debugging with the simulator in VS Code, even after a hot restart.

**Comment by miguelpruivo** [comment] 2020-05-12 15:42
Seeing this too often lately (iOS device). I'm running latest stable (1.17) on OSX.

**Comment by PritishSawant** [comment] 2020-05-13 06:17
Though my code is correct, Hot reload gets stuck for me on Android Xiaomi device. I have to restart the app from startch

**Comment by akshayyadav76** [comment] 2020-05-13 08:39
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}

i never encounter this error before....
but after upgrade  to 1.17 i am having this error 
Is this is only related to 1.17 update

**Comment by miguelpruivo** [comment] 2020-05-13 11:54
Is this suitable for a hotfix? Because it's terrible to have to do a full restart anytime this happens — which is ~80% now when running on a real device.

Sometimes I even receive `Isolate cannot be reloaded`

**Comment by sharpner** [comment] 2020-05-13 12:52
I have the same problem on OS X using `--pid-file=` and signals.... 

Flutter Version: 
```
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (11 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```

**Comment by jonahwilliams** [comment] 2020-05-13 13:27
If you're experiencing this issue, what would really help track it down is logs from a `flutter run -v` when it occurs.

**Comment by sharpner** [comment] 2020-05-13 13:47
Hope it helps:

```[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: IsolateStart, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549768}}
[        ] Sending to VM service: getIsolate({isolateId: isolates/3429825870713255})
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549771, extensionRPC: ext.dart.io.getHttpEnableTimelineLogging}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549771, extensionRPC: ext.dart.io.setHttpEnableTimelineLogging}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549771, extensionRPC: ext.dart.io.getSocketProfile}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549771, extensionRPC: ext.dart.io.startSocketProfiling}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549771, extensionRPC: ext.dart.io.pauseSocketProfiling}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549771, extensionRPC: ext.dart.io.clearSocketProfile}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549771, extensionRPC: ext.dart.io.getVersion}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: IsolateRunnable, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549850}}
[        ] Notification from VM: {streamId: Isolate, event: {type: Event, kind: IsolateExit, isolate: {type: @Isolate, id: isolates/3429825870713255, name: _spawn, number: 3429825870713255}, timestamp: 1589377549864}}
[        ] Result: {type: Sentinel, kind: Collected, valueAsString: <collected>}
[+2193 ms] Performing hot reload...
[        ] Refreshing active FlutterViews before reloading.
[        ] Sending to VM service: _flutter.listViews({})
[        ] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7ff0f003da20, isolate: {type: @Isolate, fixedId: true, id: isolates/1357078446785167, name: main.dart$main-1357078446785167, number: 1357078446785167}}]}
[   +6 ms] Scanned through 917 files in 5ms
[        ] Syncing files to device iPhone 11 Pro Max...
[        ] Scanning asset files
[   +4 ms] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:plus_app/main.dart 238357a6-9b73-49b4-a35d-0fa6d97f9c3d
[        ] <- 238357a6-9b73-49b4-a35d-0fa6d97f9c3d
[   +8 ms] Updating files
[   +2 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 11 Pro Max... (completed in 16ms)
[        ] Synced 0.0MB.
[        ] Sending to VM service: _reloadSources({pause: false, rootLibUri:
file:///Users/nwagensonner/Library/Developer/CoreSimulator/Devices/7BA8AF4B-5AD4-4C11-81CA-11D8D4156C60/data/Containers/Data/Application/06FEB603-8623-4882-957B-45F12EA1D4F6/tmp/removedD1jcrp/project/lib/main.dart.incremental.dill, isolateId: isolates/3171659015402283})
[        ] Sending to VM service: _reloadSources({pause: false, rootLibUri:
file:///Users/nwagensonner/Library/Developer/CoreSimulator/Devices/7BA8AF4B-5AD4-4C11-81CA-11D8D4156C60/data/Containers/Data/Application/06FEB603-8623-4882-957B-45F12EA1D4F6/tmp/removedD1jcrp/project/lib/main.dart.incremental.dill, isolateId: isolates/1357078446785167})
[        ] Result: {type: Sentinel, kind: Collected, valueAsString: <collected>}
[        ] Result: {type: ReloadReport, success: true, details: {finalLibraryCount: 1442, receivedLibraryCount: 0, receivedLibrariesBytes: 120, receivedClassesCount: 0, receivedProceduresCount: 0, savedLibraryCount: 1442, loadedLibraryCount: 0}}
[        ] <- reject
[  +50 ms] Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
[        ] Performing hot reload... (completed in 77ms)
```

**Comment by jonahwilliams** [comment] 2020-05-13 13:56
Thanks @sharpner . Does this always start happening following at hot restart? Or does it happen only on hot reloads too?

**Comment by SebAubin** [comment] 2020-05-13 14:01
Hot reload only for me.

**Comment by miguelpruivo** [comment] 2020-05-13 14:36
Yes, that happens mostly after a hot-reload.

**Comment by jonahwilliams** [comment] 2020-05-13 14:38
This was most likely caused by bugs in the implementation of https://github.com/flutter/flutter/commit/d98213c46f0bcf3d0b6183a24d867975ef4a18d8

**Comment by jonahwilliams** [comment] 2020-05-13 15:02
The safest fix we could make on 1.17.0 would be to revert the commit above. Alternatively, a newer  beta contains a fix for the issue

**Comment by tapizquent** [comment] 2020-05-14 22:27
Can confirm this only happens after a Hot Restart. Every Hot Reload after the first Hot Restart print out the error.

**Comment by sharpner** [comment] 2020-05-18 13:51
beta works for me
```
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (2 weeks ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
```

**Comment by ollydixon** [comment] 2020-05-20 12:21
I'm a bit lost. Many of us are doing commercial apps with Flutter now and with each of the new updates the past year there are loads of shallow bugs introduced and broken packages.

Do they not test releases with some standard template or on actual devices??..

**Comment by miguelpruivo** [comment] 2020-05-20 12:41
@ollydixon there’s no need to be rude. You can actually help them testing by contributing to Flutter, there are plenty issues yet to be fixed.

Unfortunately, maintaining open source projects at this scale is not easy and no matter how much they test, eventually new bugs may arise. You can think of having 10 bugs instead of 10000 due to the fact of it being tested in a lot of iterations before deploying into stable. 

One thing I’ve learnt in my early days when studying CS, is that there’s no software without bugs, and Flutter is no exception to that.

**Comment by ollydixon** [comment] 2020-05-20 12:58
@miguelpruivo any developer worth their salt works on a team with decent quality control. Especially before production 'stable' release. I'd rather this project go closed source then have thousands of juniors throwing broken pull requests at it (which is happening right now); while our 
critical fixes for things like 'video_player' get ignored.

Going back to this issue. We now have to ```flutter clean``` and build each time we want to see the screen refresh. Capital 'R' reload doesn't refresh the code. Neither does lower r.
You can run 'flutter run -v' to access the commands manually instead of from VSC/Studio plugins.

**Comment by tvolkert** [comment] 2020-05-20 21:25
@jonahwilliams @zanderso what risks do you see associated with cherry-picking a revert on 1.17?

**Comment by jonahwilliams** [comment] 2020-05-20 21:38
It slipped my mind, but @jason-simmons actually fixed this with a fairly small change: https://github.com/flutter/flutter/pull/53960/files

**Comment by tvolkert** [comment] 2020-05-20 21:45
eng approval for cp of https://github.com/flutter/flutter/pull/53960 into 1.17

**Comment by GULERTOLGA** [comment] 2020-05-26 14:29
This problem makes development impossible. Switching to the beta channel was not a solution for me.

**Comment by charleshan** [comment] 2020-05-28 11:47
This is happening with the latest stable version.

```
$flutter doctor -v

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G4032, locale en-US)
    • Flutter version 1.17.1 at /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/User/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/User/Library/Android/sdk
    • Java binary at: /Users/User/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/User/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
```

**Comment by tvolkert** [comment] 2020-05-28 15:53
FYI, we're going to cherry-pick the fix into a 1.17 update release in the near future.

**Comment by shipon-eye** [comment] 2020-05-30 14:53
Latest stable version v1.17.2 also has same issue. It shows:
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}

Development without hot loading getting painful and time consuming. :(


Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)

• No issues found!

**Comment by tapizquent** [comment] 2020-05-30 14:57
> Latest stable version v1.17.2 also has same issue. It shows:
> 
> Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
> 
> 
> 
> Development without hot loading getting painful and time consuming. :(
> 
> 
> 
> 
> 
> Doctor summary (to see all details, run flutter doctor -v):
> 
> [√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
> 
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> 
> [√] Android Studio (version 3.6)
> 
> [√] VS Code (version 1.45.1)
> 
> [√] Connected device (1 available)
> 
> 
> 
> • No issues found!

Make sure you do “flutter clean” after upgrading. I was receiving the error on 1.17.2 before that but a clean fixed it

**Comment by shipon-eye** [comment] 2020-05-30 17:33
@tapizquent I did it multiple times. Even sometimes I found that without clean and build, my app didn't get the changes. I don't know why now a days it behaves mysteriously. To resolve it, I have migrated my application to use flutterEmbedding 2, but didn't get any benefits.

**Comment by GULERTOLGA** [comment] 2020-06-05 09:30
Stable v1.17.3 still happening.
```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E287, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)
```

**Comment by quetool** [comment] 2020-06-09 13:18
> Stable v1.17.3 still happening.
> 
> ```
> [✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E287, locale en-TR)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
> [✓] Android Studio (version 3.4)
> [!] IntelliJ IDEA Community Edition (version 2020.1.1)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] VS Code (version 1.45.1)
> [✓] Connected device (1 available)
> ```

Yep... 1.17.3 in stable channel is such a buggy version... Every new Flutter version I am one step closer to go back to native development

**Comment by pcsosinski** [comment] 2020-06-09 15:59
@jonahwilliams any idea why this is still happening even with https://github.com/flutter/flutter/pull/53960/files ?

**Comment by quetool** [comment] 2020-06-09 16:34
It seems to be time-related with something... In my case I receive 
```
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
```
If I not hot reload my app for a while... I mean, if for some reason I spend like 2 or 3 minutes coding without hitting hot reload when I want to hot reload it I get that error... And for some reason neither a hot restart solves it... Even if I hot restart my app the code I just added is not being executed so I need to stop the process and start it again...

I hope I explained myself...

**Comment by quetool** [comment] 2020-06-09 18:51
Not happening when I run my app with `flutter run`. Could be related to VScode plugin?

**Comment by jamie1192** [comment] 2020-06-12 03:24
Still happening for me on stable 1.17.3 while using VSCode, but can't doesn't seem to be happening in Android Studio:

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F96, locale en-AU)
    • Flutter version 1.17.3 at /Users/jamie/Library/flutter
    • Framework revision b041144f83 (7 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jamie/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone-SE • {redacted} • ios • iOS 13.5

• No issues found!
```

**Comment by jonahwilliams** [comment] 2020-06-12 16:27
If you're experiencing this still, it would be helpful if you could attach logs from a run where this happened. It might be there is a different code path that has this bug we were previously unaware of, but it seems odd that this would only happen in VS code.

You might also try the latest beta version 1.19.0-4.1.pre, to see if that resolves the issue for you.

**Comment by jamie1192** [comment] 2020-06-15 02:39
thanks @jonahwilliams , can't seem to replicate on 1.19.0-4.1.pre, definitely still present in stable 1.17.3 though.

**Comment by DanTup** [comment] 2020-06-15 08:45
> seems odd that this would only happen in VS code

Comment at https://github.com/flutter/flutter/issues/56455#issuecomment-643809058 suggests maybe it happens in IntelliJ too (perhaps only if running with debugger? in VS Code, with-debugger is the default way).

**Comment by fralways** [comment] 2020-06-15 08:52
@jonahwilliams  For me it happens in Android Studio. I hit run with debug, hot restart, hot reload, error pops up. Flutter clean did not help. using stable channel - 1.17.3. I posted log at https://github.com/flutter/flutter/issues/56455#issuecomment-629878587

**Comment by fralways** [comment] 2020-06-15 08:57
Should note it happens with physical iOS device, Simulator seems it's okay.

**Comment by pcsosinski** [comment] 2020-06-22 17:36
thanks all - we're going to mark this issue as closed - it is fixed on the beta channel.

the work to fix this on 1.17 is too risky, so we will not be cherrypicking any other fixes.

**Closed by pcsosinski** 2020-06-22 17:36 UTC
Labels: P3, cp: 1.17, hotfix: 1.17, severe: crash, tool

**Comment by ollydixon** [comment] 2020-06-22 17:37
@pcsosinski where can I find the release notes for 1.17.4?

**Comment by lslv1243** [comment] 2020-06-24 17:41
It started happening to me when I updated to version 1.17.4.

**Comment by liri2006** [comment] 2020-06-24 18:23
After updating to 1.17.4 it started to appear after only few hot reloads. The only way to get rid of it is to fully restart the project which takes a lot of time.

**Comment by shinriyo** [comment] 2020-06-30 02:55
```
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (12 days ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

me too~~~ `1.17.3` is better?

**Comment by quetool** [comment] 2020-07-08 13:21
We need this on stable channel please!

**Comment by ayush221b** [comment] 2020-07-09 08:14
This issue is making it impossible to work with physical iOS devices on the Stable channel.

**Comment by edgarfroes** [comment] 2020-07-20 17:05
Come on guys, not a fix yet on 1.17.5? My project takes 8 ~ 15 minutes to start build, can't afford waist that amount time.

**Comment by tvolkert** [comment] 2020-07-20 21:55
We are very close to issuing the next stable release, which has this fix.  Sorry - we know this bug is a pain!

**Comment by adarshbalu** [comment] 2020-07-26 15:19
> We are very close to issuing the next stable release, which has this fix. Sorry - we know this bug is a pain!

Yes, it really is  :(

**Comment by abhishekkumar8** [comment] 2020-07-28 10:24
> We are very close to issuing the next stable release, which has this fix. Sorry - we know this bug is a pain!

how close Mr :)

**Comment by tvolkert** [comment] 2020-07-28 23:41
`1.20.x`, currently live on the beta channel, will be the next stable version (though it may receive a few cherrypicks before promotion to stable).  If you're itching to pick up this fix (which I understand), I'd recommend temporarily switching to the beta channel, since the current version will be API-compatible with the upcoming stable.

**Comment by G-RAWR** [comment] 2020-10-10 05:34
Any news on this issue?

**Comment by navgts** [comment] 2020-12-29 16:27
This issue is still around !!

**Comment by zanderso** [comment] 2021-01-05 16:18
@navgts This issue has been closed for quite some time and is presumed fixed. If you are still seeing something like this, please file a new issue with full details. Thanks!

**Comment by joaovirgilicw** [comment] 2021-02-09 19:17
I'm still having this issue but now more frequently. May it be related to M1 chips?
![Captura de Tela 2021-02-09 às 16 08 52](https://user-images.githubusercontent.com/78375092/107415369-0d239e00-6af2-11eb-87f6-06da7caf68a1.png)

**Comment by zanderso** [comment] 2021-02-09 19:33
Hi @joaovirgilicw, this issue is closed. Please file a new issue with full details. Thanks!
