### ISSUE TITLE
Build dashboard failed to get updated for LUCI tests due to `BuildBucketException`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#74451] opened 2021-01-21 23:58 UTC
Detailed error:

```
BuildBucketException: [500]: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

#0      BuildBucketClient._postRequest (package:cocoon_service/src/service/buildbucket.dart:86:5)
<asynchronous suspension>
#1      BuildBucketClient.batch (package:cocoon_service/src/service/buildbucket.dart:113:42)
#2      LuciService.getBuilds (package:cocoon_service/src/service/luci.dart:158:65)
#3      LuciService.getBranchRecentTasks (package:cocoon_service/src/service/luci.dart:66:42)
<asynchronous suspension>
#4      RefreshChromebotStatus.get (package:cocoon_service/src/request_handlers/refresh_chromebot_status.dart:56:93)
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZoned (dart:async/zone.dart:1550:10)
#10     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#11     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:144:19)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _runZoned (dart:async/zone.dart:1630:10)
#15     runZoned (dart:async/zone.dart:1550:10)
#16     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:143:11)
<asynchronous suspension>
#17     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:133:23)
#18     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#19     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#20     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#21     _rootRun (dart:async/zone.dart:1190:13)
#22     _CustomZone.run (dart:async/zone.dart:1093:19)
#23     _runZoned (dart:async/zone.dart:1630:10)
#24     runZonedGuarded (dart:async/zone.dart:1618:12)
#25     runZoned (dart:async/zone.dart:1547:12)
#26     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#27     fork (package:gcloud/service_scope.dart:104:30)
```

**Comment by keyonghan** [comment] 2021-01-21 23:59
I am guessing the increased builders add burden to the RPC call.

**Comment by godofredoc** [comment] 2021-01-22 01:19
Seems like we need a retry with backoff for those RPC calls and for the long term we'll need the pubsub messages to update task state/results.

**Comment by godofredoc** [comment] 2021-01-22 01:19
\cc @yusufm

**Comment by godofredoc** [comment] 2021-01-25 19:28
This is a duplicate of https://github.com/flutter/flutter/issues/74536

**Closed by godofredoc** 2021-01-25 19:28 UTC
Labels: passed first triage, team, team: infra
