### ISSUE TITLE
[go_router] Add a equivalent to `pushAndRemoveUntil()` 

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#109128] opened 2022-08-08 04:03 UTC
This is a follow up of https://github.com/flutter/flutter/issues/107052 that was marked as a duplicate of https://github.com/flutter/flutter/issues/106402 but https://github.com/flutter/flutter/issues/106402 wasn't mentioning `pushAndRemoveUntil()`.

## Use case

With navigator 1.0, we can use 2 methods:

- `.pushAndRemoveUntil()`

It is very useful, especially when the user is going through a wizard. The wizard could walk the user through different screens and those screens could be removed at the end of the wizard so the user cannot go back to them.

I didn't see any equivalent in GoRouter. Or maybe I missed them?

## Proposal

It would be useful to implement `.pushAndRemoveUntil()` equivalent.

**Comment by exaby73** [comment] 2022-08-08 10:28
Hello @ValentinVignal. This issue looks like a duplicate of https://github.com/flutter/flutter/issues/99112. Please follow up and upvote the original issue. Thank you

**Closed by exaby73** 2022-08-08 10:28 UTC
Labels: in triage
