### ISSUE TITLE
Physical Devices crash on debug after upgrade to 3.13.9

### ISSUE THREAD

**Issue by nagringapp** [flutter/flutter#137598] opened 2023-10-31 07:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Can't reproduce

### Expected results

Run smootlhy

### Actual results

Hi Team,

I have upgraded Flutter to the latest 3.13.9 and my physical devices started to suddenly crash. I can't provide any more details as it happens and does not give any log.

I debug in two physical iPhones simultaneously.

I had an issue when Upgrading the iOS to 17 and running on MacOS Ventura.

The previous version was running smoothly and after upgrading to this new one it crashes now and then.

Just fyi

### Code sample

.

### Screenshots or Video

.

### Logs

.

### Flutter Doctor output

flutter doctor -v
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.6 22G120 darwin-arm64, locale en-AU)
    • Flutter version 3.13.9 on channel stable at /Users/caco/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (5 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/caco/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/caco/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (5 available)
    • SM A217F (mobile) • RF8R51DXW4L                              • android-arm64  •
      Android 12 (API 31)
    • iPhoneX (mobile)  • 26c572951929f1725c51ca6a99108845355576d3 • ios            • iOS
      16.7.1 20H30
    • iPhone11 (mobile) • 00008030-00016CC60C90802E                • ios            • iOS
      17.0.3 21A360
    • macOS (desktop)   • macos                                    • darwin-arm64   • macOS
      13.6 22G120 darwin-arm64
    • Chrome (web)      • chrome                                   • web-javascript •
      Google Chrome 118.0.5993.117
    ! Error: Browsing on the local area network for Caco’s iPad Pro. Ensure the device is
      unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by mraleph** [comment] 2023-10-31 07:59
Duplicate of https://github.com/flutter/flutter/issues/136980

**Closed by mraleph** 2023-10-31 07:59 UTC
