### ISSUE TITLE
[windows] Key state exception threw during hot restart/load

### ISSUE THREAD

**Issue by PassionPenguin** [flutter/flutter#110911] opened 2022-09-03 17:07 UTC
## Related different platform issue

#67866 [macos] Changing caps Lock key input source throws exception
#74138 [macos] occasionally Shift keyPressed throws failed assertion exception
#87038 [windows][uwp] ctrl +shift + s crashes the app

## Steps to reproduce

1. open and run any flutter project running on Windows (tested on Windows 10 21H2, lang=en)
2. inside ide edit something and save it to trigger hot reload
3. immediately after you have pressed ctrl/cmd + s, press another key like ctrl, shift, alt or key combo with these keys like ctrl + a
4. you can receive exception from flutter

```log
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#09686(physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left"), logicalKey: LogicalKeyboardKey#00100(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), character: null, timeStamp: 74:35:38.514627)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:881:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#8      _invoke2 (dart:ui/hooks.dart:186:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by PassionPenguin** [comment] 2022-09-03 17:08
flutter ver:

```log
[✓] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.3.0 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (5 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.1.3)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.19041.0

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Users\hoarfroster\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6777.52
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code, 64-bit edition (version 1.69.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19044.1889]

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by PassionPenguin** [comment] 2022-09-03 17:16
The bug, in fact, has no effects on real production, as it will not have impact on the interactive ui, but considering it's pretty much bothering since it will be triggered endlessly by pressing any key once it's triggered, and it will corrupt the logs....with thousands of SAME EXCEPTION LOG

**Comment by PassionPenguin** [comment] 2022-09-03 17:22
u can jump to 00:22:00 to see how the app threw the exception with keyboard interaction:

https://user-images.githubusercontent.com/41184947/188281627-e7cf5619-d44d-4e17-bb03-731f964e226b.mp4

**Comment by darkalfx** [comment] 2022-09-04 20:55
> The bug, in fact, has no effects on real production, as it will not have impact on the interactive ui, but considering it's pretty much bothering since it will be triggered endlessly by pressing any key once it's triggered, and it will corrupt the logs....with thousands of SAME EXCEPTION LOG

This bug has a very real effect on production, if you're using TextFields on for an application deployed on Windows, **then using the shift keys for capitalization are going to crash your app.**

**This is a severe regression.**

**Comment by exaby73** [comment] 2022-09-05 08:51
@PassionPenguin I cannot reproduce this issue on my Windows 11 machine. Does this reproduce with the default counter app? I tried running the app from the terminal as well as from Android Studio.

### Flutter Doctor

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.918], locale en-IN)
    • Flutter version 3.3.0 on channel stable at C:\Users\Nabeel\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (6 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.72, on Microsoft Windows [Version 10.0.22000.918], locale en-IN)
    • Flutter version 3.4.0-19.0.pre.72 on channel master at C:\Users\Nabeel\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 202f5771f4 (6 hours ago), 2022-09-04 20:28:23 -0400
    • Engine revision b94120dfe9
    • Dart version 2.19.0 (build 2.19.0-168.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by PassionPenguin** [comment] 2022-09-05 10:31
Yes it does cause the same problem on the counter app.@exaby73

**Comment by PassionPenguin** [comment] 2022-09-05 10:52
(ps. you may failed because you did not follow what i said in the `reprodce` section..?)

1. `flutter create tmp`
2. open it with an ide or command line, but make sure it does support **hot reload**.
3. run it with `-d windows`
4. after it showed up the window, type some spacebar or add a comment in the dart source code to trigger the hot reload
5. as soon as you press `ctrl+s`, use the windows hotkey combo `alt+tab` or macos combo `cmd+tab` to change windows's focus node on the counter app (that is, focus the counter app before it is hot reloaded)
6. press ctrl, shift or alt, or some key combo with these three keys (what i press is ctrl +alt)

https://user-images.githubusercontent.com/41184947/188430570-dbe7f4c4-7500-4b36-8889-63c133e5633a.mp4

**Comment by PassionPenguin** [comment] 2022-09-05 10:52
https://user-images.githubusercontent.com/41184947/188432613-543da24f-15ad-480d-ad4b-e5d3f0d1416e.mp4

**Comment by PassionPenguin** [comment] 2022-09-05 10:56
> 

well tbh since the problem here comes along with hot reload, what happened in real prod may not be the same prob, but the inside logic may be the same ( what i think is the way dart process key input makes things worse...? )

**Comment by PassionPenguin** [comment] 2022-09-05 11:06
May be related to the same prob: 

#110967
#94502

**Comment by darkalfx** [comment] 2022-09-05 13:42
> @PassionPenguin I cannot reproduce this issue on my Windows 11 machine. Does this reproduce with the default counter app? I tried running the app from the terminal as well as from Android Studio.
> ### Flutter Doctor
> `flutter doctor -v` (Stable)
> `flutter doctor -v` (Master)

I build and use the app for **Windows**, not android, ios or anything else, and not via a remote desktop either, but natively on the same computer that I'm coding on.

This was not happening prior to Flutter 3.3

**REPRO STEPS:**

Open a command prompt, type:
`flutter create `

Then add
`TextFormField(),` in the `column`.

Then run the app in debug, focus the textfield and press the right and left shift a couple of times and then boom:
```

════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#b8065(physicalKey: PhysicalKeyboardKey#00036(usbHidUsage: "0x1600000036", debugName: "Key with ID 0x1600000036"), logicalKey: LogicalKeyboardKey#00103(keyId: "0x200000103", keyLabel: "Shift Right", debugName: "Shift Right"), character: null, timeStamp: 12:23:19.108656)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

════════════════════════════════════════════════════════════════════════════════
Unable to parse JSON message:
The document is empty.
```

When running a release build of the app, it will literally crash the app if I use the shift keys.

**Comment by exaby73** [comment] 2022-09-05 15:06
I cannot reproduce the issue. Maybe bacause I'm not fast enough or maybe there is a difference in the 2 windows versions (I am on Windows 11 and I can see you are using Windows 10). I am not sure, but I'll label this issue for further insights from the team.

**Comment by exaby73** [comment] 2022-09-06 09:05
I can reproduce this issue. Here's what I did to reproduce it reliably:

- Run the application in a terminal
- Press <kbd>Shift</kbd> + <kbd>R</kbd> to hot restart, then immediately <kbd>R</kbd> to hot reload. Flutter queue the hot reload until the hot restart is complete.
- While the app is hot restarting/reloading, <kbd>ALT</kbd> + <kbd>Tab</kbd> to the Flutter app, and press a modifier key like <kbd>ALT</kbd>.
- The error should appear. Note: this error is only thrown when you press the key while the app is reloading, and not after.

Using the same technique, I couldn't reproduce it on Mac but that may be due to an error on my end. However, I will still label this as Windows only.

### Reproducible on

- `Stable (3.3.0)`
- `Master (3.4.0-19.0.pre.86)`

### Flutter Doctor

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.918], locale en-IN)
    • Flutter version 3.3.0 on channel stable at C:\Users\Nabeel\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (7 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.86, on Microsoft Windows [Version 10.0.22000.918], locale en-IN)
    • Flutter version 3.4.0-19.0.pre.86 on channel master at C:\Users\Nabeel\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a04e6b7618 (49 minutes ago), 2022-09-06 02:08:10 -0400
    • Engine revision 623b80157c
    • Dart version 2.19.0 (build 2.19.0-171.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by chinmaygarde** [comment] 2022-09-06 19:01
cc @loic-sharma @cbracken

**Comment by PassionPenguin** [comment] 2022-09-08 14:23
@exaby73 @chinmaygarde 
in addition to the exception thrown during hot reload, pressing alt or other modifier key (ctrl, shift, etc) causes exceptions as well:

```log
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#8b4e8(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 48:27:23.672463)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:881:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#8      _invoke2 (dart:ui/hooks.dart:186:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Comment by cbracken** [comment] 2022-09-08 17:43
Thanks @PassionPenguin this one is a known issue and something that's been in our plans to address for a while, but behind some other user-facing (rather than developer-facing) crashers that we've been knocking off. Thanks for filing!

**Comment by dkwingsmt** [comment] 2022-09-08 18:20
It looks like a duplicate issue as https://github.com/flutter/flutter/issues/87391. Closing this one.

**Closed by dkwingsmt** 2022-09-08 18:20 UTC
Labels: a: text input, severe: crash, engine, platform-windows, a: desktop, has reproducible steps, P4, r: duplicate, found in release: 3.3, found in release: 3.4

**Comment by PassionPenguin** [comment] 2022-09-09 12:09
> ======== Exception caught by services library ======================================================
> The following assertion was thrown during a platform message callback:
> A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#8b4e8(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 48:27:23.672463)
> 'package:flutter/src/services/hardware_keyboard.dart':
> Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'
> 
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
>   https://github.com/flutter/flutter/issues/new?template=2_bug.md
> 
> When the exception was thrown, this was the stack: 
> #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
> #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
> #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
> #5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:881:37)
> #6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
> #7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
> #8      _invoke2 (dart:ui/hooks.dart:186:13)
> #9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
> #10     _Channel.push (dart:ui/channel_buffers.dart:132:31)
> #11     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
> #12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
> #13     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
> (elided 2 frames from class _AssertionError)
> ====================================================================================================

@dkwingsmt well this is not the similar one you mentioned above, as this issue is not a during non-hot-restart-peroid-only one, but it can be reproduced through flutter app's normal states.

**Comment by cbracken** [comment] 2022-09-09 19:27
If there's a separate keyboard issue happening that doesn't involve hot-reload, please check if there's an existing issue filed and add a thumb-up to it to help it get prioritised, of it no existing bug covers it, please file one. The original issue described here was related to hot restart/reload.
