### ISSUE TITLE
AndroidView does not work on OPPO and vivo brand phones, it displays as a black block

### ISSUE THREAD

**Issue by huuang** [flutter/flutter#29346] opened 2019-03-14 08:34 UTC
## Steps to Reproduce

1. `flutter run` webview_flutter-0.3.4 example

## Logs

```
Launching lib/main.dart on PACM00 in debug mode...
Initializing gradle...                                              1.1s
Resolving dependencies...                                           2.0s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         2.0s
Built build/app/outputs/apk/debug/app-debug.apk.
D/libEGL  (22211): ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0xcdb77e00)     
I/BufferQueue(22211): [unnamed-22211-0](this:0xcb406000,id:0,api:0,p:-1,c:-1) BufferQueue core=(22211:com.example.test_android_view)
**_W/GuiExt  (22211): Cannot find GuiExtService                            
E/GED     (22211): ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, 7_**        
I/GLConsumer(22211): [SurfaceTexture-0-22211-0] detachFromContext       
I/Presentation(22211): Presentation is being dismissed because the display metrics have changed since it was created.
D/WindowClient(22211): Add to mViews: DecorView@dec1649[], this = android.view.WindowManagerGlobal@4e69e9e
I/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) connect(P): api=1 producer=(415:???) producerControlledByApp=false
D/ViewRootImpl[MainActivity](22211): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
I/InputTransport(22211): Create ARC handle: 0xcccd5110                  
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/View    (22211): [Warning] assignParent to null: this = DecorView@dec1649[]
I/InputTransport(22211): Destroy ARC handle: 0xcccd5110                 
D/WindowClient(22211): Remove from mViews: DecorView@dec1649[], this = android.view.WindowManagerGlobal@4e69e9e
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
I/GLConsumer(22211): [SurfaceTexture-0-22211-0] attachToContext         
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/HWUIExtension(22211): MTKProgramCache.generateProgram: 562984313159681
D/HWUIExtension(22211): createProgram 0x0002000800000001, binary 0xeea22cac, length 5080, format 36705 within 282ns
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
D/BufferQueueProducer(22211): [SurfaceTexture-0-22211-0](this:0xcb406000,id:0,api:1,p:415,c:-1) cancelBuffer: slot 0
```

```
flutter analyze
Analyzing example...                                                    
No issues found! (ran in 2.4s)
```

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.3.2, on Mac OS X 10.14.3 18D109, locale en-CN)
    • Flutter version 1.3.2 at /Users/xxxx/Development/flutter
    • Framework revision 046f960ae2 (13 days ago), 2019-02-28 23:05:45 -0800
    • Engine revision 99f3f7a9c2
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • xxxx's iPhone X • 902918b17e723a15acc7a4f8c3f22d4665a13fd1 • ios • iOS 12.1.4

• No issues found!
```

**Comment by huuang** [comment] 2019-03-14 08:39
AndroidView works well on the other Android phones but OPPO and vivo brand phones which occupy half of the Android mobile phone market in China.

This issue blocks my application publishing. I need help, Thank you very much.

**Comment by Purus** [comment] 2019-03-14 10:39
Attaching your error screeshots might help for developers to understand better

**Comment by huuang** [comment] 2019-03-14 10:47
webview_flutter-0.3.4 example screenshot:


![WechatIMG101](https://user-images.githubusercontent.com/14324434/54351037-8ce82a00-4689-11e9-8abe-16f9e8cf4820.png)

**Comment by huuang** [comment] 2019-03-14 10:53
Same problem with this issue: https://github.com/flutter/flutter/issues/27285

**Comment by amirh** [comment] 2019-03-14 16:56
Duplicate of #24974

**Closed by amirh** 2019-03-14 16:56 UTC

**Comment by xuzhengquan** [comment] 2020-05-29 09:03
Anyone solve this?

**Comment by ikkyu0319** [comment] 2020-06-19 07:51
@xuzhengquan @huuang 你们怎么了这个问题么？

**Comment by conghaonet** [comment] 2020-06-26 20:02
I have the same problem.

**Comment by suhail-zartek** [comment] 2020-09-11 11:57
Same situation in OPPO Color OS7 while using exoplayer.The audio plays well. But the video is on the black screen. Please reopen this issue

**Comment by phamnhuvu-dev** [comment] 2020-09-14 10:42
I have same issue on Oppo F5 https://www.gsmarena.com/oppo_f5-8889.php please re open

**Comment by Nazmul1607081** [comment] 2020-10-05 05:39
Same situation in OPPO Color OS7 while using flutter_pdf view in release mode.User claim when they can not open any pdf file in this pdf viewer on my app downloaded from play store.

**Comment by prashantspandey** [comment] 2020-10-06 17:47
> Same situation in OPPO Color OS7 while using exoplayer.The audio plays well. But the video is on the black screen. Please reopen this issue



> Same situation in OPPO Color OS7 while using flutter_pdf view in release mode.User claim when they can not open any pdf file in this pdf viewer on my app downloaded from play store.

Same problems, any solution to this?

**Comment by CatEatFishs** [comment] 2021-01-21 07:41
I have the same problem. vivo x20 does not display WebView, VirtualDisplay Test display normally,

**Comment by mahimakaushik-oss** [comment] 2021-06-21 08:52
i also have same problem . vivo z1 pro is not able to run flutter application... anyone here who can help me..
thank you in advance
