### ISSUE TITLE
[Request] Add option to disable fontPadding (or trim font height)

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#69540] opened 2020-11-01 21:37 UTC
This is really common and I believe it might be duplicated, but I couldn't find any issue here. Basically..

Android has [this question](https://stackoverflow.com/questions/4768738/android-textview-remove-spacing-and-padding-on-top-and-bottom) with 159k views, with the answer `android:includeFontPadding="false"`.

Microsoft released a few months ago this post: https://medium.com/microsoft-design/leading-trim-the-future-of-digital-typesetting-d082d84b202. It describes how `text-edge: cap alphabetic; leading-trim: both;` can be **extremely** helpful in CSS.
![image](https://miro.medium.com/max/1400/1*gXfB7QR3LpWwJEuA12drqw.gif)

And Flutter, well, there is [this issue](https://stackoverflow.com/questions/57008822/flutter-how-do-i-remove-unwanted-padding-from-text-widget) with 7k views and no answer. People suggest using lineHeight, Stack or even a complex renderBox, but all solutions are bad.

I've also seen some kind of similar issues (https://github.com/flutter/flutter/issues/69281) that would probably not exist if Flutter had a proper way to disable font padding.

I am having an issue where a custom font has a bottom padding and there is no easy way to fix it. So, this is my request. Could you add a disablePadding attribute to TextStyle?
![image](https://user-images.githubusercontent.com/351125/97815995-dd523800-1c70-11eb-93b5-370887fac7c2.png)

**Comment by a-eniou-pvotal** [comment] 2021-10-11 15:55
looks like an important feature

**Comment by johnsonmh** [comment] 2021-11-15 21:42
It's not _exactly_ what you're asking for, but I suspect a good workaround is to use `TextLeadingDistribution.even` [[1]](https://api.flutter.dev/flutter/dart-ui/TextLeadingDistribution-class.html). At least the padding will be equal on the top and bottom, and not larger one side (and therefore uneven).

**Comment by bernaferrari** [comment] 2021-11-15 22:00
@johnsonmh I just want a way to disable the FontPadding (or even customize like CSS but disabling would be good enough for me). That doesn't work:

```dart
Text(
    "TAKE A LOOK",
    style:   GoogleFonts.hind(
        fontWeight: FontWeight.w600,
        textStyle: TextStyle(leadingDistribution: TextLeadingDistribution.even),
    ),
),
```

![image](https://user-images.githubusercontent.com/351125/141859729-240d3973-12e9-4bb3-b012-3bf1f1dcd9c3.png)

**Comment by johnsonmh** [comment] 2021-11-15 22:13
I see, yes there is no way to accomplish "leading trim", but since you're using all caps here, `height: 1.0` will probably get you the same effect.

It's actually referred to as "line height" rather than "padding". There's a great article by figma about it if you are curious: https://www.figma.com/blog/line-height-changes/

**Comment by sonyamoonglade** [comment] 2022-04-12 16:37
Hey, use a height property in TextStyle(). This will remove unnecessary space on-top of your text.
`Text("Sample",
                    style: const TextStyle(
                    fontSize: 13,
                    height: 0.2
)`

**Comment by fzyzcjy** [comment] 2022-07-28 06:19
Hi is there any updates?

**Comment by bernaferrari** [comment] 2023-03-28 21:05
@johnsonmh news from Figma land. The option to customize vertical trim:
https://twitter.com/figma/status/1640750882613493760

**Comment by lukepighetti** [comment] 2024-02-20 11:54
This is desperately needed. It's simply not possible to layout type in Flutter to the satisfaction of the average UI designer without a lot of hacks and shims

What we have:

<img width="364" alt="GGvTHWrXEAAriqN" src="https://github.com/flutter/flutter/assets/666539/e22323a2-0050-41ed-b7b9-a38fa30970fb">

What we need:

![GGvURSHW4AA97pz](https://github.com/flutter/flutter/assets/666539/683943d9-ce7f-40ea-99a2-4ca292639347)

**Comment by iapicca** [comment] 2024-02-20 14:12
@darshankawar 
is this issue meant to be `p3` as in "2020 p3" or "2024 p3"?

**Comment by Hixie** [comment] 2024-04-15 22:42
This issue is very confusing because it seems to be requesting a particular feature rather than describing a problem to solve. I would recommend filing a new issue that is focused on the actual use case / problem being met, and then closing this one as a duplicate of that one. That would likely lead to it being addressed sooner.

**Comment by bernaferrari** [comment] 2024-04-15 23:42
The problem is that when you have a custom font, there is no way to define "I want the font without any padding" as I showed in some pictures + a sample, which makes it impossible to have custom font text centered in a button.

**Comment by fzyzcjy** [comment] 2024-04-16 00:17
+1 (for better styling such as centering), and I guess reading why people on Android and on Web needs the equivalent feature / how they uses it may also serve as context.

**Comment by moffatman** [comment] 2024-04-16 01:24
For me this is 100% about centering one line of text with an arbitrary font reliably

**Comment by Hixie** [comment] 2024-04-16 03:26
Are we specifically talking about optically vertically centering the x-height, the median, the cap height, the midpoint of the alphabetic baseline and the cap height, something else? Is this just for text that uses an alphabetic baseline?

A specific example of a Flutter demo app that doesn't do what you're looking for, and a diagram of what you are looking for, would help a lot.

**Comment by Hixie** [comment] 2024-04-16 03:27
If it helps, this diagram from Wikipedia might be a useful reference:
![](https://github.com/flutter/flutter/assets/551196/1e7d6dc5-ffdf-492b-9c18-82ac2a62e200)

**Comment by moffatman** [comment] 2024-04-16 04:21
I noticed this as I made a system font picker which showed all the fonts available, and saw many were not centered right (E.g. below: "Al Nile", "Al Tarikh"). But actually, macOS doesn't center them right either in use, it seems to be due to a really large descender (because of the arabic characters).

<img width="217" alt="image" src="https://github.com/flutter/flutter/assets/789275/77fa92ef-fd76-4a67-ad26-d75ada228541">

Is ascender+descender supports to be part of the centering? Seems like it works well for most english fonts, ascender - cap height ≈ descender. So it's just a bit of symmetric padding. But doesn't work for English characters alone in an Arabic font. There, the css "cap alphabetic" thing shown in the OP may work better.

<img width="765" alt="image" src="https://github.com/flutter/flutter/assets/789275/a3511cdd-9519-4321-8b60-c79029ec2abc">


And there's also the weird font AcademyEngravedLetPlain which has the baseline going through the middle of the characters instead of along the bottom... I guess the answer is, don't put your UI in a typographic font.

**Comment by Hixie** [comment] 2024-04-16 06:43
I guess I don't understand what you mean by "not centered right". What exactly do you want centered? It looks like the text in that screenshot is centered based on the ascent+descent (the default line height) of the text. What would you prefer? Would you want the baseline to be positioned half an x-height below the vertical center of the box?

**Comment by lukepighetti** [comment] 2024-04-16 09:43
> I guess I don't understand what you mean by "not centered right". What exactly do you want centered? It looks like the text in that screenshot is centered based on the ascent+descent (the default line height) of the text. What would you prefer? Would you want the baseline to be positioned half an x-height below the vertical center of the box?

Cap height to baseline is the industry standard for text layout right now. The way Flutter handles font padding makes buttons look bad because it doesn't properly vertically align it

**Comment by lukepighetti** [comment] 2024-04-16 10:11
It would be nice to also have this to be able to tweak things as needed, although there may be a way to do this now that I'm not aware of

```dart
TextStyle(
  double verticalOffset // % of line height
)
```

**Comment by Hixie** [comment] 2024-04-16 20:22
> Cap height to baseline is the industry standard (in North America anyway) for laying out microcopy in UI elements like buttons.

"Cap height to baseline" is a distance, it's not a standard anything. I'm trying to figure out what exactly y'all want, but it's hard if you won't actually describe it precisely. :-)

Right now we render text using the typographic standard that has been used for centuries[^1], wherein the baseline is positioned at a distance from the top of its box according to the line height metrics in the font(s) used on the line (unless you set the `height` property of the text style, which overrides the line height font metrics), where the "line height" is defined as a distance above and a distance below the baseline.

It sounds like you are asking for the distance from the top of the box to the baseline to be the cap height? What distance below the baseline do you want to be considered part of the total height?

(FWIW, such an alignment will look off-center in a world with pure-lowercase (where you probably want to center the x-height-to-baseline distance), and with non-alphabetic-baseline text (e.g. CJK).)


> Here: [#69540 (comment)](https://github.com/flutter/flutter/issues/69540#issuecomment-969361756)

That sample does not show anything like the screenshot you are including here, so I am not sure how to interpret it. In the screenshot the distance from the top of the rounded rectangle to the top of the caps is within a few pixels of the distance from the alphabetic baseline to the bottom of the rounded rectangle. Is that difference what you are looking to change?


[^1]: In the past this was literally based on the height of the block of lead, in recent decades with digitization of fonts it's just a number encoded in the font file.

**Comment by bernaferrari** [comment] 2024-04-16 20:41
In Hind font, for example, the font is slightly uncentered. In order to force center, most frameworks (css, android) and tools (figma) allow to remove the "padding" or (vertical trim), so it can be centered. If you have a "g", the bottom curve wouldn't be included in the height calculation, only the upper part.

This repo has the calculation: https://github.com/rudeayelo/leading-trim
This here also has: https://github.com/markdalgleish/figma-leading-trim/blob/7245bf55ed8f915d8a2d4b862317c7a1fc15ef44/src/core.ts#L161

Seems to be 
const marginTop = Math.round(parseFloat(capsizeValues.capHeightTrim) * textNode.fontSize);
const marginBottom = Math.round(parseFloat(capsizeValues.baselineTrim) * textNode.fontSize);


This Google Fonts article tells a bit about the feature: https://fonts.google.com/knowledge/using_type/vertical_spacing_and_line_height_in_design_systems

![image](https://github.com/flutter/flutter/assets/351125/fa52607f-b9a5-47f6-993f-290a88efe797)

The sphinx example using hind font:

<img width="555" alt="image" src="https://github.com/flutter/flutter/assets/351125/dceddc0c-df03-4e99-bee0-deae16a64b86">


<img width="575" alt="image" src="https://github.com/flutter/flutter/assets/351125/9d3b3a83-434f-46e4-9a85-ff7b15ec5785">

**Comment by Hixie** [comment] 2024-04-16 21:48
Ok it sounds like what you're asking for is a way to set the `height` to be the distance from the alphabetic baseline to the cap height, with zero descending distance.

**Comment by bernaferrari** [comment] 2024-04-16 21:50
Yes, while respecting the current height value (should only affect top/bottom padding).

**Comment by Hixie** [comment] 2024-04-16 21:51
I don't know what that means. You can't respect the `height` if you're also setting the height to some other value, and fonts don't really have a concept of "padding".

Please define your terms in typographic terms -- distance from a specified baseline to a font metric above and a font metric below.

**Comment by bernaferrari** [comment] 2024-04-16 22:10
I found this with details on how css did it (+ their discussions): https://github.com/w3c/csswg-drafts/issues/3240

**Comment by Hixie** [comment] 2024-04-16 22:22
Wait, this only applies to the first and last line? That's completely different than what I thought we were talking about.

So you're really just asking for a way to specify in the `TextHeightBehavior` that you want to clip the ascent to the cap height and clip the descent to the alphabetic baseline?

**Comment by bernaferrari** [comment] 2024-04-16 22:24
Yeah, something like that. The ascent on first line and descent on last line. Because lineHeight already controls "the middle", what people really want is to control the "edges" of a text object.

**Comment by Hixie** [comment] 2024-04-16 22:36
ok i'm going to file a new bug that explains that because this bug is a complete mess and we'll never get it fixed if we just rely on this one!

**Comment by bernaferrari** [comment] 2024-04-16 22:37
But then you will loose the 70 stars :( feel free to just edit/rewrite my description.

**Comment by Hixie** [comment] 2024-04-17 00:02
Most of those upvotes came within a very narrow window, which probably means they were the result of someone campaigning for the issue. We tend to discount that kind of thing anyway, so it's no great loss.

**Comment by Hixie** [comment] 2024-04-17 03:43
Closing as duplicate of the more clearly described https://github.com/flutter/flutter/issues/146860.

**Closed by Hixie** 2024-04-17 03:43 UTC
Labels: framework, engine, a: typography, customer: crowd, c: proposal, P3, team-engine, triaged-engine
