### ISSUE TITLE
Automation issue on devices with notch in landscape mode

### ISSUE THREAD

**Issue by jungleeut** [flutter/flutter#88341] opened 2021-08-17 08:01 UTC
My application works on the landscape as well as on portrait mode. When I try to run automation on my application in portrait mode I am able to get all the elements at the right position but when I do the same in the case of landscape the elements show a shifted position in these automation tools in case of a notch device. The UI seems to be fine though. Everything works fine for non-notch devices. 

My application is using SafeArea.
I have tried two automating tools Airtest and Appium.
Attaching screenshots from Appium for reference

<img width="1432" alt="Screenshot 2021-08-17 at 1 23 36 PM" src="https://user-images.githubusercontent.com/59562423/129687235-f6716b46-5ce7-4e16-a69a-e0f20de9f03d.png">
<img width="1431" alt="Screenshot 2021-08-17 at 1 23 54 PM" src="https://user-images.githubusercontent.com/59562423/129687253-4c7683f0-6962-4009-b51a-912a21528c02.png">

**Comment by TahaTesser** [comment] 2021-08-17 10:28
Hi @jungleeut
This is most likely because the app focus windows are not are in a location in the landscape

I've attempted to reproduce the issue using a simple sample that left a menu in the landscape, use voice over to see focus windows but everything looks normal 

![flutter_01](https://user-images.githubusercontent.com/48603081/129710291-fa36b01e-639d-4ceb-bb2b-1de3dcb0ff51.png)


Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment] 2021-09-08 09:58
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-08 09:58 UTC
