### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Uri org-dartlang-app:/web_plugin_registrant.dart must have scheme 'file:'.

### ISSUE THREAD

**Issue by ravimandal06** [flutter/flutter#124036] opened 2023-04-03 17:12 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Uri org-dartlang-app:/web_plugin_registrant.dart must have scheme 'file:'.
```
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:86:7)
#1      Context.fromUri (package:path/src/context.dart:1000:32)
#2      FileSystem.getPath (package:file/src/interface/file_system.dart:158:24)
#3      LocalFileSystem.file (package:file/src/backends/local/local_file_system.dart:26:54)
#4      ErrorHandlingFileSystem.file (package:flutter_tools/src/base/error_handling_io.dart:123:24)
#5      ProjectFileInvalidator.findInvalidated (package:flutter_tools/src/run_hot.dart:1486:25)
#6      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:477:80)
#7      ResidentWebRunner.restart (package:flutter_tools/src/isolated/resident_web_runner.dart:355:43)
<asynchronous suspension>
#8      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1720:40)
<asynchronous suspension>
#9      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1760:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.7, on Microsoft
    Windows [Version 10.0.22621.1413], locale
    en-IN)
    [32m•[39m Flutter version 3.7.7 on channel stable at
      C:\src\flutter\flutter
    [32m•[39m Upstream repository
      https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2ad6cd72c0 (4 weeks
      ago), 2023-03-08 09:41:59 -0800
    [32m•[39m Engine revision 1837b5be5f
    [32m•[39m Dart version 2.19.4
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Windows Version (Installed version of Windows
    is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android
    devices (Android SDK version 33.0.0-rc2)
    [32m•[39m Android SDK at
      C:\Users\91707\AppData\Local\Android\Sdk
    [32m•[39m Platform android-33, build-tools 33.0.0-rc2
    [32m•[39m ANDROID_HOME =
      C:\Users\91707\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program
      Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment
      (build 11.0.12+7-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program
      Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual
    Studio Build Tools 2019 16.9.4)
    [32m•[39m Visual Studio at C:\Program Files
      (x86)\Microsoft Visual
      Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version
      16.9.31205.134
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at C:\Program
      Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-f
      lutter
    [32m•[39m Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-d
      art
    [32m•[39m Java version OpenJDK Runtime Environment
      (build 11.0.12+7-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.77.0)
    [32m•[39m VS Code at
      C:\Users\91707\AppData\Local\Programs\Micro
      soft VS Code
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64
      • Microsoft Windows [Version
      10.0.22621.1413]
    [32m•[39m Chrome (web)      • chrome  •
      web-javascript • Google Chrome
      111.0.5563.147
    [32m•[39m Edge (web)        • edge    •
      web-javascript • Microsoft Edge
      111.0.1661.62

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 12cb4eb7a009f52b347b62ade7cb4854b926af72
### Plugins
path_provider-2.0.14
path_provider_android-2.0.24
path_provider_foundation-2.2.1
path_provider_linux-2.1.10
path_provider_windows-2.1.5

**Comment by huycozy** [comment] 2023-04-04 05:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/107592 which has a similar stack trace.

**Closed by huycozy** 2023-04-04 05:55 UTC
Labels: in triage
