### ISSUE TITLE
Feature Request: Material-compliant 'standard' bottom sheets

### ISSUE THREAD

**Issue by johnfesa** [flutter/flutter#17928] opened 2018-05-26 00:23 UTC
The existing functionality for displaying a "persistent bottom sheet" seems like it's intended to behave like what the Material spec now calls a "[standard bottom sheet](https://material.io/design/components/sheets-bottom.html#standard-bottom-sheet)", but the implementation doesn't behave like the Material spec in a couple of ways and the API doesn't really work well for typical usage scenarios.

Mulligan has a UX-approved design for features that requires this functionality.

Outline of acceptance criteria based on the design:
1. The spec mentions that a standard bottom sheet _may_ appear, but we also need the ability to ergonomically create a Scaffold that, at construction time, specifies a standard bottom sheet.
2. The bottom sheet should be separately modifiable after construction of the Scaffold; this may mean changing height based on its contents changing, without direct user interaction.
3. The bottom sheet shouldn't be able to be swiped off the screen. Maybe make this a configuration option, but the Material spec only describes _modal_ bottom sheets as being dismissible. Not standard (or 'persistent') bottom sheets.
4. The standard bottom sheet shouldn't interact with the back/close button in the Scaffold or routes. Or at least this should not be the default behavior/it should be opt-in. It seems more useful to do this if the bottom sheet can expand to a full-screen treatment, which the Material spec documents bottom sheets can do, but we don't need this full-screen-expansion treatment at this time.

References:
https://docs.flutter.io/flutter/material/ScaffoldState/showBottomSheet.html
https://github.com/flutter/flutter/blob/7587f54b204a61c1dbe84926caf3330d635cfa62/examples/flutter_gallery/lib/demo/material/persistent_bottom_sheet_demo.dart

**Comment by HansMuller** [comment] 2018-05-29 18:53
> The spec mentions that a standard bottom sheet may appear, but we also need the ability to ergonomically create a Scaffold that, at construction time, specifies a standard bottom sheet.

I agree. Just filed #17998. Will certainly address this before 1.0

> The bottom sheet should be separately modifiable after construction of the Scaffold; this may mean changing height based on its contents changing, without direct user interaction.

This would be implicit in the fix for #17998; you could just build the scaffold with a new bottom sheet. You can rebuild a persistent bottom sheet now with PersistentBottomSheetController.setState. The controller is returned by showBottomSheet().

> The bottom sheet shouldn't be able to be swiped off the screen. Maybe make this a configuration option, but the Material spec only describes modal bottom sheets as being dismissible. Not standard (or 'persistent') bottom sheets.

You're right, swipe to dismiss isn't in the spec for standard bottom sheets. Will make that optional as part of the resolving this issue.

> The standard bottom sheet shouldn't interact with the back/close button in the Scaffold or routes. Or at least this should not be the default behavior/it should be opt-in. It seems more useful to do this if the bottom sheet can expand to a full-screen treatment, which the Material spec documents bottom sheets can do, but we don't need this full-screen-expansion treatment at this time

Agreed. This should probably be an optional feature as well.

**Comment by tvolkert** [comment] 2018-06-06 16:40
Bumped this up from 1.0 to the current bucket because this needs to be done for Mulligan's launch.  FYI @HansMuller

**Closed** 2018-06-12 21:28 UTC
Labels: a: fidelity, customer: mulligan (g3), f: material design, framework, severe: customer critical

**Comment by feinstein** [comment] 2018-11-20 23:37
@HansMuller I think there are still things missing on the Bottom Sheet.

I am new to Flutter and I am trying to figure it out how to convert my app to Flutter. After reading the docs, seeing some samples and trying some code, I can't control my Bottom Sheet on Flutter as I do in Android, maybe the problem is me, but AFAICS there's some stuff missing on the Bottom Sheet API or in the docs.

My application has a Persistent Bottom Sheet that can't be dismissed, it has something as a `minimum height`, when the user drags the Bottom Sheet up, the contents animate and change, expand, revealing new items. This animated expansion can also be triggered by a button.

In android this is kinda easy, because the `BottomSheetBehavior` exposes a `slideOffset` with a `float` indicating how much the Bottom Sheet has slided (0-1), also it exposes a `State` that can be set, so we can trigger the Bottom Sheet to `expand` and `collapse`. The Bottom Sheet also can be set to be `hidable` or not.

In Flutter I can't see how do I get this behavior with a Persistent Bottom Sheet.

Is it there a way (preferably simple and easy to implement) to make a Bottom Sheet that can't be hidden (has a minimum height), can be expanded to a given height (maybe the entire screen) on drag or triggered by a method call, and exposes how much it has expanded so we can animate widgets inside it, changing the Bottom Sheet contents according to how much of the screen space it's taking?

This is basically the Bottom Sheet that the Google Maps App for Android has, the only difference is theirs is hidable and mine isn't, and I believe if this Bottom Sheet behavior was expected in the Google Maps App, than it should be part of the Bottom Sheet API.

**Comment by kjeremy** [comment] 2018-12-07 16:13
@feinstein I'm having the exact same issue.

**Comment by feinstein** [comment] 2018-12-07 16:20
@kjeremy after talking to some people at the Flutter team, I concluded that Bottom Sheets and Backdrops are considered advanced widgets that vary too much from case to case, so they recommend that we implement our own from scratch, getting some inspiration from the samples, specially Shrine, since there's an animated Bottom Sheet there and many other stuff.

**Comment by kjeremy** [comment] 2018-12-07 16:48
@feinstein That's disappointing. Where is the animated bottom sheet in shrine? The only one I see is the modal one when displaying the shopping cart.

**Comment by kjeremy** [comment] 2018-12-07 17:07
Hm I don't see that on Android.

**Comment by feinstein** [comment] 2018-12-07 17:15
Look for the sample app directly, not the one inside the Gallery App.

**Comment by skjagini** [comment] 2019-01-15 22:40
@feinstein  can you help me which gallery app you are suggesting, I couldn't find either like @kjeremy

**Comment by feinstein** [comment] 2019-01-15 22:47
Look into the samples of the Flutter main repository, there's one there called Shrine

**Comment by skjagini** [comment] 2019-01-15 22:53
@feinstein  are you talking about this one: https://github.com/flutter/flutter/tree/master/examples/flutter_gallery/lib/demo/shrine

**Comment by feinstein** [comment] 2019-01-15 22:56
Yes

**Comment by skjagini** [comment] 2019-01-15 22:58
hmm, not sure I find miniaturized shopping carts which grow in there.

**Comment by feinstein** [comment] 2019-01-15 23:02
It's a sample of what can be done, such as expanding, holding items, taking the whole screen, animating... It's up to you to modify it to your specific needs.
