### ISSUE TITLE
web: have text fields trigger "onsubmitted" ONLY for enter key on 

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#55042] opened 2020-04-17 13:22 UTC
https://github.com/flutter/flutter/issues/35435#issuecomment-613990245

I often find myself hitting enter for a text field to make it "go" on the PC/web site.  I would love if I could trigger onFieldSubmitted for flutter web ONLY for the enter key.  Today per the above issue thread you see that any focus change will trigger the onFieldSubmitted() callback.

**Comment by TahaTesser** [comment] 2020-04-17 14:06
Hi @jdeltoft 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jdeltoft** [comment] 2020-04-24 20:11
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G3020, locale en-US)
    • Flutter version 1.17.0 at /Users/jeltoft/flutter/flutter
    • Framework revision d3ed9ec945 (3 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jeltoft/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.122
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by jdeltoft** [comment] 2020-04-24 20:13
sure, here is a snippet:

```
              CustomTextField(
                validator: (value) {
                  if (_loginAttempted) {
                    if ((value.isEmpty) || (!isValidEmail(value))) {
                      return 'Please enter a valid email';
                    }
                  }
                  return null;
                },
                controller: _emailController,
                horizontalPad: 15,
                keyboardType: TextInputType.emailAddress,
                autoFocus: false,
                icon: Icon(Icons.email),
                labelText: "Email",
                onFieldSubmitted: (value) => _handleSubmitted(false, value),
              ),
```

**Comment by jdeltoft** [comment] 2020-04-24 20:14
If you use onFieldSubmitted() on any TextFormField() widget, you'll notice that if you just lose focus in flutter for web, that it triggers this handler.  But it would be great if it only did that for hitting "enter" key on your keyboard.

**Comment by Mateis** [comment] 2020-04-25 16:27
I have the same request.

See my post here: https://github.com/flutter/flutter/issues/55583

**Comment by nturgut** [comment] 2020-05-28 22:59
duplicate of: https://github.com/flutter/flutter/issues/49785

**Closed by nturgut** 2020-05-28 22:59 UTC
Labels: a: desktop, a: text input, assigned for triage, customer: gather, customer: web10, f: material design, framework, platform-web, proposal, severe: new feature

**Comment by nturgut** [comment] 2020-06-03 20:53
@jdeltoft

Thanks again for filing the issue. I made a change in the connection close logic for text editing. For the desktop browsers, the text field won't finalize text editing when the user clicks other areas on the page. Please have another look.

**Comment by jdeltoft** [comment] 2020-06-24 22:42
@nturgut Awesome!  I'll take a look tomorrow.  Thanks so much for making the changes!

**Comment by Mateis** [comment] 2020-06-25 12:01
> 
> 
> @jdeltoft
> 
> Thanks again for filing the issue. I made a change in the connection close logic for text editing. For the desktop browsers, the text field won't finalize text editing when the user clicks other areas on the page. Please have another look.

Awesome, i'd like to implement it in my webapp!

To use this, should I use `flutter channel master` and build with that?
When will the commit go from master to dev and then beta, how does this work?

**Comment by jdeltoft** [comment] 2020-11-25 21:24
@nturgut I know it's crazy late but I just had so many other things going on.  I just went back to this and it works great, thanks again.  

@Mateis Not sure if you still need anything from me?  The onFieldSubmitted works great now.
