### ISSUE TITLE
Regression in Android build time

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#137436] opened 2023-10-27 18:16 UTC
SkiaPerf is reporting a regression in `release_full_compile_millis` on the PR https://github.com/flutter/flutter/pull/136880

https://flutter-flutter-perf.skia.org/e/?begin=1698368710&end=1698427832&keys=X6204acaf96c14c08af685caed6b33add&num_commits=50&request_type=1&xbaroffset=37678

Based on the discussion on the PR, I'm guessing this is potentially expected, but filing the issue anyway in case any further investigation is needed.

cc @reidbaker @mkustermann

**Comment by camsim99** [comment] 2023-10-27 18:18
Just a heads up that this looks like a duplicate of https://github.com/flutter/flutter/issues/137432. I did revert this PR just now but they should probably still take a look for re-landing it. cc @gaaclarke

**Comment by gaaclarke** [comment] 2023-10-27 18:21
Thanks @camsim99, definitely a dup, closing this.  Can you link the revert in the other issue please.

**Closed by gaaclarke** 2023-10-27 18:21 UTC
Labels: c: performance, team-android
