### ISSUE TITLE
DateTime(5) when formatted to display Weekday indicating wrong output

### ISSUE THREAD

**Issue by AksharPrasanna** [flutter/flutter#65726] opened 2020-09-13 17:43 UTC
`DateFormat('EEEE').format(DateTime(int)) ` Indicating wrong output when integer is 5.

**Expected output** for `DateFormat('EEEE').format(DateTime(5))` is **Friday**.

**Received output - Saturday**

`for (int index = 1; index <= 7; index++) {
      print(DateFormat('EEEE').format(DateTime(index)).toString());
    }`

<img width="242" alt="Screenshot 2020-09-13 at 11 12 29 PM" src="https://user-images.githubusercontent.com/33616248/93024789-a075a780-f616-11ea-9a13-c6d98be9ec16.png">

**Comment by aviveershetty** [comment] 2020-09-13 17:57
Hi Team, even am facing this issue in my project-due for release next week. Can you please let me know the fix if any at the earliest. Thanks in advance.

**Comment by pedromassangocode** [comment] 2020-09-14 09:35
Hi @AksharPrasanna 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you

**Comment by AksharPrasanna** [comment] 2020-09-14 11:09
Thank you @pedromassangocode 
Please find the details below - 

<img width="391" alt="Screenshot 2020-09-14 at 4 37 56 PM" src="https://user-images.githubusercontent.com/33616248/93078797-bd5abb00-f6a8-11ea-8e19-f3344ddb3931.png">

**Output of flutter doctor -v**
```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.5 19F101, locale en-IN)
    • Flutter version 1.20.3 at /Users/aksharprasanna/projects/flutter
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/aksharprasanna/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/aksharprasanna/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

 
[✓] Connected device (1 available)            
    • ONEPLUS A6010 (mobile) • 175572d • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

**pubspec.yaml**
```
name: dateTime_issue
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```


**Sample Code**
```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            for (int index = 0; index < 40;index ++)
              Text('DateFormat(\'EEEE\').format(DateTime(${index})) - ' +
                  DateFormat('EEEE').format(DateTime(index)).toString()),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

**Comment by pedromassangocode** [comment] 2020-09-14 11:54
Hi @AksharPrasanna 
From what I can see, the issue is related to a Dart language plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/intl).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-14 11:54 UTC
Labels: in triage
