### ISSUE TITLE
This is not working with chewie

### ISSUE THREAD

**Issue by imSanjaySoni** [flutter/flutter#59925] opened 2020-06-20 14:06 UTC
@WoKee  try this
```yaml
video_player:
    git:
      url: git://github.com/shmy/video_player_flutter.git
```

_Originally posted by @shmy in https://github.com/flutter/flutter/issues/28494#issuecomment-476198373_

**Comment by TahaTesser** [comment] 2020-06-22 10:13
Hi @imSanjaySoni 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/brianegan/chewie/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-22 10:13 UTC
