### ISSUE TITLE
I have a problem with firebase notification

### ISSUE THREAD

**Issue by EdulimaProg** [flutter/flutter#114729] opened 2022-11-05 01:15 UTC
`FAILURE: Build failed with an exception.

* Where:
Build file 'C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-12.0.3\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':flutter_local_notifications'.
> No signature of method: build_8750infkrvmeod8p4m0v5g8ph.android() is applicable for argument types: (build_8750infkrvmeod8p4m0v5g8ph$_run_closure2) values: [build_8750infkrvmeod8p4m0v5g8ph$_run_closure2@590c0a12]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by iapicca** [comment] 2022-11-06 18:04
@EdulimaProg 
if the problem is with firebase maybe it's better to open the issue [here](https://github.com/firebase/flutterfire/issues)

**Comment by darshankawar** [comment] 2022-11-07 07:20
Please open this issue in Flutterfire's dedicated repo as suggested above.
Closing from here.

**Closed by darshankawar** 2022-11-07 07:20 UTC
Labels: in triage
