### ISSUE TITLE
TabBar does not scroll to the correct tab after controller is changed

### ISSUE THREAD

**Issue by absar** [flutter/flutter#115917] opened 2022-11-23 12:34 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Press the + button to increase the number of tabs

**Expected results:**
TabBar should scroll to the last tab but it does not, even though that becomes the selected tab as you can see by manually scrolling to the right

**Actual results:**
TabBar does not scroll to the correct tab

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const TabBarNotScrollingHome());

class TabBarNotScrollingHome extends StatelessWidget {
  const TabBarNotScrollingHome({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const TabBarNotScrollingAfterControllerChanged(),
    );
  }
}

class TabBarNotScrollingAfterControllerChanged extends StatefulWidget {
  const TabBarNotScrollingAfterControllerChanged({super.key});

  @override
  State<TabBarNotScrollingAfterControllerChanged> createState() =>
      _TabBarNotScrollingAfterControllerChangedState();
}

class _TabBarNotScrollingAfterControllerChangedState
    extends State<TabBarNotScrollingAfterControllerChanged>
    with TickerProviderStateMixin {
  final _scrollViewController = ScrollController(initialScrollOffset: 0.0);
  TabController? _tabController;
  late List<Widget> tabPages;
  bool increaseTabs = false;
  int _totalTabs = 10;
  TabBar? _tabBar;

  @override
  void initState() {
    super.initState();
    _generateTabs();
  }

  @override
  void dispose() {
    _tabController?.dispose();
    _scrollViewController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final buildBody =
        TabBarView(controller: _tabController, children: tabPages);

    return Scaffold(
      body: NestedScrollView(
        controller: _scrollViewController,
        floatHeaderSlivers: true,
        headerSliverBuilder: buildAppBar,
        body: buildBody,
      ),
    );
  }

  List<Widget> buildAppBar(BuildContext context, bool isScrolled) {
    final addButton = IconButton(
      icon: Icon(increaseTabs ? Icons.remove : Icons.add),
      onPressed: () {
        increaseTabs = !increaseTabs;
        _generateTabs();
        setState(() {});
      },
    );

    return <Widget>[
      SliverAppBar(
        title: const Text('Press + to increase tabs =>'),
        bottom: _tabBar,
        pinned: true,
        snap: false,
        primary: true,
        actions: [addButton],
      ),
    ];
  }

  void _generateTabs() {
    if (increaseTabs) {
      _totalTabs = 15;
    } else {
      _totalTabs = 10;
    }
    _tabController = TabController(
        vsync: this, length: _totalTabs, initialIndex: _totalTabs - 1);

    _tabBar = TabBar(
      tabs: List.generate(
          _totalTabs, (index) => Center(child: Tab(text: 'Tab $index'))),
      controller: _tabController,
      isScrollable: true,
    );

    tabPages = List.generate(
      _totalTabs,
      (index) => Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Page $index', textAlign: TextAlign.center),
            const SizedBox(height: 20),
            const Text(
              'After pressing the + button to increase the tabs this page '
              'will change but the tab above will not scroll to the last Tab '
              'even though that becomes the selected tab. However if you press '
              'again to decrease the tabs it will scroll to the new last tab',
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.red),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.19045.2251], locale en-US)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

```

</details>

https://user-images.githubusercontent.com/1186833/203547727-f768c7ff-f22a-4037-a385-5752f257609f.mp4

**Comment by absar** [comment] 2022-11-23 12:47
cc @bleroux

**Comment by bleroux** [comment] 2022-11-23 13:04
@absar 
Thanks for the detailed report.

I wonder if this case have been fixed by the following PR:  https://github.com/flutter/flutter/pull/112168.
This PR is only on master channel, can you try to repro this on master channel?

Another question, is the issue still reproducible if you remove the `NestedScrollView`?

**Comment by absar** [comment] 2022-11-23 19:40
@bleroux 
Same issue on Flutter Channel master 3.6.0-7.0.pre.39.
There is no relation to `NestedScrollView`, issue persists without `NestedScrollView`, code without it appended below

<details>
<summary>Code without NestedScrollView</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const TabBarNotScrollingHome());

class TabBarNotScrollingHome extends StatelessWidget {
  const TabBarNotScrollingHome({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const TabBarNotScrollingAfterControllerChanged(),
    );
  }
}

class TabBarNotScrollingAfterControllerChanged extends StatefulWidget {
  const TabBarNotScrollingAfterControllerChanged({super.key});

  @override
  State<TabBarNotScrollingAfterControllerChanged> createState() =>
      _TabBarNotScrollingAfterControllerChangedState();
}

class _TabBarNotScrollingAfterControllerChangedState
    extends State<TabBarNotScrollingAfterControllerChanged>
    with TickerProviderStateMixin {
  TabController? _tabController;
  late List<Widget> tabPages;
  bool increaseTabs = false;
  int _totalTabs = 10;
  TabBar? _tabBar;

  @override
  void initState() {
    super.initState();
    _generateTabs();
  }

  @override
  void dispose() {
    _tabController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final buildBody =
        TabBarView(controller: _tabController, children: tabPages);

    final addButton = IconButton(
      icon: Icon(increaseTabs ? Icons.remove : Icons.add),
      onPressed: () {
        increaseTabs = !increaseTabs;
        _generateTabs();
        setState(() {});
      },
    );

    final buildAppBar = AppBar(
      title: const Text('Press + to increase tabs =>'),
      bottom: _tabBar,
      primary: true,
      actions: [addButton],
    );

    return Scaffold(appBar: buildAppBar, body: buildBody);
  }

  void _generateTabs() {
    if (increaseTabs) {
      _totalTabs = 15;
    } else {
      _totalTabs = 10;
    }
    _tabController = TabController(
        vsync: this, length: _totalTabs, initialIndex: _totalTabs - 1);

    _tabBar = TabBar(
      tabs: List.generate(
          _totalTabs, (index) => Center(child: Tab(text: 'Tab $index'))),
      controller: _tabController,
      isScrollable: true,
    );

    tabPages = List.generate(
      _totalTabs,
      (index) => Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Page $index', textAlign: TextAlign.center),
            const SizedBox(height: 20),
            const Text(
              'After pressing the + button to increase the tabs this page '
              'will change but the tab above will not scroll to the last Tab '
              'even though that becomes the selected tab. However if you press '
              'again to decrease the tabs it will scroll to the new last tab',
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.red),
            ),
          ],
        ),
      ),
    );
  }
}


```

</details>

**Comment by danagbemava-nc** [comment] 2022-11-24 06:13
The issue is reproducible using the code sample provided in https://github.com/flutter/flutter/issues/115917#issuecomment-1325572674.

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/203707187-8c2e3b2d-ddd5-4def-b26a-549bc9405cd9.mp4
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale en-GB)
    • Flutter version 3.3.8 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (2 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 4F72110C-F38B-4CF9-93C4-4D6042148D28 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

```
[!] Flutter (Channel master, 3.6.0-7.0.pre.45, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.6.0-7.0.pre.45 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d0352f55db (5 hours ago), 2022-11-23 20:01:26 -0500
    • Engine revision 9b2895724c
    • Dart version 2.19.0 (build 2.19.0-424.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 4F72110C-F38B-4CF9-93C4-4D6042148D28 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```
</details>

**Comment by bleroux** [comment] 2022-11-25 13:58
@absar Many thanks for pointing out this issue and for the great repro.
I filed a PR for this issue: https://github.com/flutter/flutter/pull/116019.

@TahaTesser noticed that there is a duplicate (https://github.com/flutter/flutter/issues/96718).
I will close this one as a duplicate, thank you to follow up on https://github.com/flutter/flutter/issues/96718.

**Closed by bleroux** 2022-11-25 13:58 UTC
Labels: framework, f: material design, has reproducible steps, r: duplicate, found in release: 3.3, found in release: 3.6
