### ISSUE TITLE
[tool_crash] HttpException: Connection closed before full header was received

### ISSUE THREAD

**Issue by cooldreamz** [flutter/flutter#95414] opened 2021-12-16 17:16 UTC
## Command
```
flutter drive --profile --device-timeout=20
```

## Steps to Reproduce
This happens seemingly at random after the first run of 'flutter drive'. After many attempts I am not able to reproduce the problem on-demand. Once it happens it continues to happen every time. I have tried the following with limited success:
a) flutter clean
b) uninstalling the app from the target device
c) disconnecting and re-connecting the USB cable to the device
d) ensuring the screen on the target device is unlocked

It seems to relate to how long I wait before re-attempting the 'flutter drive' command, it seems like something (maybe on the target device?) is taking time to clean up?

## Logs
HttpException
```

```
```
[✓] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19042.1348], locale en-GB)
    • Flutter version 2.8.0 at C:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Dev\Android-SDK
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Users\Chris Thompson\AppData\Local\Google\Chrome SxS\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at C:\Users\Chris Thompson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • GT I9505 (mobile) • 2d03b7aa • android-arm    • Android 5.0.1 (API 21)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.1348]
    • Chrome (web)      • chrome   • web-javascript • unknown
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 96.0.1054.53

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ffb2ecea5223acdd139a5039be2f9c796962833d
### Plugins
path_provider-2.0.8
path_provider_android-2.0.9
path_provider_ios-2.0.7
path_provider_linux-2.1.4
path_provider_macos-2.0.4
path_provider_windows-2.0.4

**Comment by darshankawar** [comment] 2021-12-17 07:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/79748

**Closed by darshankawar** 2021-12-17 07:40 UTC
Labels: in triage
