### ISSUE TITLE
await url_launcher.launch() returns null (iOS only)

### ISSUE THREAD

**Issue by eggnstone** [flutter/flutter#45900] opened 2019-12-02 12:28 UTC
Calling await url_launcher.launch() with a legal URL returns null but should return a bool.
This works on Android but doesn't work on iOS.

```
bool resultLaunch = await ul.launch(url);
print("resultLaunch: $resultLaunch");
```
`flutter: resultLaunch: null`

$flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-DE)
    • Flutter version 1.9.1+hotfix.6 at /Users/xyz/dev/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xyz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPhone 8 • xxx • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

**Comment by eggnstone** [comment] 2019-12-02 12:31
I missed the import:
`import 'package:url_launcher/url_launcher.dart' as ul;`

And if you want to test:
`String url = "https://flutter.dev";`

**Comment by eggnstone** [comment] 2019-12-02 12:32
Suggested labels:
p: url_launcher
plugin
⌺‬ platform-ios

**Comment by iapicca** [comment] 2019-12-02 15:24
Hi @eggnstone 
<details>
  <summary>sample</summary>

```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
// https://pub.dev/packages/url_launcher

const String _url = 'https://flutter.dev/clock';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: HomePage(),
  );
}

class HomePage extends StatelessWidget {

  static void _launch() async => await canLaunch(_url)
    ? print(await launch(_url))
    : throw 'Could not launch $_url';
    
  @override
  Widget build(BuildContext context) => SafeArea(
    child: Center(
      child: GestureDetector(
        onTap: ()=> _launch(),
        child:FlutterLogo(
          size: 80,
  ),),),);
}
```
</details>

thank for the suggestion

**Comment by pizzalbj** [comment] 2019-12-07 11:08
I also found it in my ios device(iphonex)
"http://www.qq.com" return null 
"iosamap://navi?sourceApplication=applicationName&backScheme=applicationScheme&poiname=fangheng&poiid=BGVIS&lat=36.547901&lon=104.258354&dev=1&style=2" return false, but it can luanch my “高德地图” app ~

**Comment by dvaldivia** [comment] 2020-04-15 20:00
Same problem, launch future never returns if awaited on `iOS 13.4` testing on device

**Comment by iapicca** [comment] 2020-04-17 12:51
Hi @eggnstone 
are you experiencing the issue with the latest stable version of flutter
and [url_launcher 5.4.2](pub.dev/packages/url_launcher)?
thank you

**Comment by VladyslavBondarenko** [comment] 2020-05-19 11:35
Persists with `url_launcher: ^5.4.7` and `dev 1.19.0-1.0.pre`

**Comment by iapicca** [comment] 2020-07-24 11:04
testing the code below with the latest master and [url_launcher](https://pub.dev/packages/url_launcher) `5.5.0`

<details><summary>code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(
      const MyApp(
        key: Key('app'),
      ),
    );

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: const MyHomePage(
          key: Key('home'),
        ),
      );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _launchURL() async {
    const String _url = 'https://flutter.dev';
    if (await canLaunch(_url)) {
      final bool _l = await launch(_url);
      print('$_l');
    } else {
      print('Could not launch $_url');
    }
  }

  @override
  Widget build(BuildContext context) => Material(
        child: Center(
          child: MaterialButton(
            color: Colors.blueAccent,
            child: const Text('launch'),
            onPressed: _launchURL,
          ),
        ),
      );
}
```

</details>

<details><summary>logs</summary>

```bash
[ +265 ms] Syncing files to device iPhone 11 Pro Max...
[   +4 ms] Scanning asset files
[   +5 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:master/main.dart 4bc391a0-9c86-4cdc-9eb9-899ab4c3f93b
[        ] <- 4bc391a0-9c86-4cdc-9eb9-899ab4c3f93b
[ +271 ms] Updating files
[ +130 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 11 Pro Max... (completed in 417ms)
[   +1 ms] Synced 0.8MB.
[   +1 ms] <- accept
[   +2 ms] Connected to _flutterView/0x7f84ae039020.
[   +3 ms] Flutter run key commands.
[   +8 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 11 Pro Max is available at: http://127.0.0.1:60988/WhnFXXk36rs=/
[+97730 ms] flutter: null
[+11677 ms] Service protocol connection closed.
[   +4 ms] Lost connection to device.
[  +13 ms] DevFS: Deleting filesystem on the device
(file:///Users/nevercode/Library/Developer/CoreSimulator/Devices/D6967F45-CB0F-4D4E-AFD5-278816A21CAE/data/Containers/Data/Application/758A08A9-1D92-40B2-BC6B-F8DB8AAFDB21/tmp/ma
sterFtwq89/master/)
[ +262 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +4 ms] "flutter run" took 352,254ms.
[   +9 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +7 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/nevercode/development/flutter_master
    • Framework revision e64fe11542 (10 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

the issue still persists
Thank you

**Comment by sayhicoelho** [comment] 2020-12-16 19:21
same issue here

**Comment by sayhicoelho** [comment] 2020-12-19 19:32
Maybe you are missing `LSApplicationQueriesSchemes` in Info.plist. 

Ref: https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl

**Comment by iapicca** [comment] 2020-12-19 21:11
@eggnstone 
does the [proopsed solution](https://github.com/flutter/flutter/issues/45900#issuecomment-748515464) work for you?

tagging @TahaTesser  for visibility

**Comment by TahaTesser** [comment] 2020-12-22 09:59
Can confirm it is fixed by adding `LSApplicationQueriesSchemes` 
I already have PR for it https://github.com/flutter/plugins/pull/3252
Closing  as duplicate of https://github.com/flutter/flutter/issues/65936

**Closed by TahaTesser** 2020-12-22 09:59 UTC
Labels: found in release: 1.21, has reproducible steps, p: first party, p: url_launcher, platform-ios, plugin
