### ISSUE TITLE
Debugger is crashing the App

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#52364] opened 2020-03-10 22:41 UTC
My App was under a breakpoint in IntelliJ IDEA and suddenly the App closed on my Android Emulator, this was the error message:

F/libc    (31521): Fatal signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0 in tid 3067 (Thread-5), pid 31521 (yapp.myapp)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:9/PSR1.180720.117/5875966:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 31521, tid: 3067, name: Thread-5  >>> com.myapp.myapp <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    eax b4fa4b52  ebx 64c8fdda  ecx cb57ef3c  edx 64f27632
    edi 64d5a09a  esi 7fada462
    ebp 7fada4fa  esp 7fada7ae  eip ef1a1ce3
backtrace:
    #00 pc 0001fce3  /system/lib/libc.so (sigsetjmp+99)
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"1677","method":"resume","params":{"isolateId":"isolates/3688252752053767"}}

______________________
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

**Comment by mraleph** [comment] 2020-03-23 20:23
Duplicate of #27077

**Closed by mraleph** 2020-03-23 20:23 UTC
Labels: a: debugging, engine, framework, severe: crash
