### ISSUE TITLE
Image does not load properly when a number of errors are occurred

### ISSUE THREAD

**Issue by violet-dev** [flutter/flutter#106463] opened 2022-06-23 07:06 UTC
![image](https://user-images.githubusercontent.com/66541802/175233743-260f0d22-655b-4dc3-8b48-fc5a378b0c2a.png)

The picture above shows the error I'm getting.

Assume a situation where I need to show many images at once. Since the server only sends about 3 images at a time, the rest of the requests return a 503 error. If I continue to load images despite these 503 errors, the image should load normally without errors someday. 

However, images with 503 error 3 times are no longer displayed. It just sends a 503 error to the `loadingErrorWidgetBuilder`.
As you can see in the picture above, a `http.get` request normally returns 200. The code below works fine with no problems.

I suspect it's because the HttpClientRequest caches the response, but I reproduced it and confirmed that it doesn't cache the response.
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/_network_image_io.dart#L106
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/_network_image_web.dart#L126
```dart
if (hc == null) hc = HttpClient()..autoUncompress = false;
hc!.getUrl(Uri.parse(url)).then((e) async {
  _headerCache![index]
      ?.forEach((String name, String value) {
    e.headers.add(name, value);
  });
  final HttpClientResponse response = await e.close();
  print(response.statusCode);
});
```
![image](https://user-images.githubusercontent.com/66541802/175236488-23157efb-501a-4a26-8c70-bcc506ed1bda.png)
An HttpClient singleton instance always produces a different response for every request.

I cannot reproduce the behavior because this problem occurs intermittently.

My flutter version is this

```
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (6 weeks ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2
```

**Comment by violet-dev** [comment] 2022-06-23 13:20
@huycozy 
Hi, 
This issue is a logically non-reproducible issue, and since I'm using a server, I can't clearly state that it's a flutter issue, so I haven't created reproducible code.

However, assuming it is not a server problem, you can run the following example.

https://github.com/violet-dev/asdfasdfshaszvxcvcvbxx
To reproduce the problem, you need to scroll very fast, download images simultaneously, and intentionally throw a 503 error.

The reason of need a `ScriptManager` is that the image address can change with low probability.
If you get a 404 error, you may have to try again in 3 minutes or so.

![8](https://user-images.githubusercontent.com/66541802/175307594-e932a570-cd1d-45f4-ac8f-b5f90fed0595.gif)

Above, the `Image.file` returns a 503 error, but you can see that httpclient and http.get get the request normally.
https://github.com/violet-dev/asdfasdfshaszvxcvcvbxx/blob/master/lib/main.dart#L75
The 503 error is a problem that occurs even after removing the client and get requests.

**Comment by huycozy** [comment] 2022-06-24 04:41
Hi @violet-dev 
From what I can see, the issue is related to a 3rd party plugin `flutter_js` rather than to Flutter itself. Furthermore,  `flutter_js` is forked from [repo](https://github.com/abner/flutter_js). So, please open the issue in the dedicated [repository](https://github.com/abner/flutter_js).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2022-06-24 04:41 UTC
Labels: in triage

**Comment by violet-dev** [comment] 2022-06-24 15:07
@huycozy 
this is not the flutter_js issue.
many try to fix this bug, I found bug that flutter core image cache (resize) mechanism occurred.

I found that to fix this bug I had to change a lot of code.
For now, I simply changed the image to only resize the loaded image, bypassing the flutter cache mechanism.
This is not a good solution, but I don't think there is any other way.
