### ISSUE TITLE
Hardware keyboard bug?

### ISSUE THREAD

**Issue by MiesSuomesta** [flutter/flutter#157797] opened 2024-10-29 16:27 UTC
### Steps to reproduce

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this
occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please
ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This
was the event: KeyDownEvent#29484(physicalKey: PhysicalKeyboardKey#f0183(usbHidUsage: "0x000700e2",
debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#e5ce6(keyId: "0x200000104", keyLabel: "Alt
Left", debugName: "Alt Left"), character: null, timeStamp: 19:06:16.127000)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 509 pos 16: '!_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:509:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:524:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:646:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1167:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:618:35)
#8      _invoke2 (dart:ui/hooks.dart:344:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)

### Expected results

No exceptions.

### Actual results

I dont know, just sumble don this while doing showDialog with:

showDialog(
      context: context,
      builder: (BuildContext context) {
        this.EditorActionLoadNote("dummy");

        return AlertDialog(
          title: Text('Editoi muistiinpanoa..'),
          content: editor as Widget, // Oma widgetti
          actions: [
            ElevatedButton(
              onPressed: () {
                restoreData();
                push_message_to_user("Note restored...");
              },
              child: Text('Restore'),
            ),
            SizedBox(width: 10),
            ElevatedButton(
              onPressed: () {
                saveData();
                push_message_to_user("Note saved...");
              },
              child: Text('Save'),
            ),
            SizedBox(width: 10),
            ElevatedButton(
              onPressed: () {
                saveData();
                setState(() {
                  open_editor = false;
                  this.EditorActionCloseNote(_controller.text);
                });
                Navigator.of(context).pop();
                push_message_to_user("Closing editor ....");
              },
              child: Text('Close editor'),
            ),
            TextButton(
              child: Text('Sulje'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
          ],
        );
      },
    );

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by rehmaan-dev** [comment] 2024-10-30 04:09
Have a look at this:
https://stackoverflow.com/questions/69113977/getting-assertion-failed-pressedkeys-containskeyevent-physicalkey-error-in

**Comment by danagbemava-nc** [comment] 2024-10-30 06:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/107972

Kindly subscribe to the original issue for updates.

Thank you

**Closed by danagbemava-nc** 2024-10-30 06:16 UTC
Labels: in triage
