### ISSUE TITLE
[web]: safari blank page production build

### ISSUE THREAD

**Issue by tapeo** [flutter/flutter#35982] opened 2019-07-11 13:26 UTC
After running `flutter packages pub global run webdev build` or `flutter packages pub global run webdev serve -r` web app loads all resources but shows a blank page with Safari. 
With Chrome all works.

Browser console logs:

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (stack_trace_mapper.dart.js.map, line 0)`

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (dart_sdk.js.map, line 0)`

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (client.dart.js.map, line 0)`

`[Error] Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
	_rethrow (dart_sdk.js:28306)
	(funzione anonima) (dart_sdk.js:28302)
	_microtaskLoop (dart_sdk.js:25002)
	_startMicrotaskLoop (dart_sdk.js:25008)
	(funzione anonima) (dart_sdk.js:25083)
	promiseReactionJob`

**Comment by 04Basti04** [comment] 2019-07-13 20:32
Got the same issue!

**Comment by grouma** [comment] 2019-07-22 16:38
This appears to be a DDC issue. @vsmenon to triage.

**Comment by vsmenon** [comment] 2019-07-22 16:46
@grouma - The `-r` should mean dart2js, not ddc.  But we should only serve `stack_trace_mapper.dart` and (I think) `client.dart` with ddc.  Is something getting mixed up here?

**Comment by grouma** [comment] 2019-07-22 17:34
Ahh I missed that.

Yes we should not be serving `client.js` in release mode. I tried reproducing this locally with `webdev` version `2.2.0` and was unable to do so.

@taepo what version of webdev are you using? You can run `flutter packages pub global run webdev --version`

**Comment by tapeo** [comment] 2019-07-25 08:26
The version after `flutter packages pub global run webdev --version` is 2.2.0

**Comment by grouma** [comment] 2019-07-25 22:28
Please run with the latest `webdev` version `2.3.0` and see if you can reproduce the issue. Please provide further details on your set up including if possible a sample application.

**Comment by tapeo** [comment] 2019-07-26 09:14
I update `webdev` to `2.3.0`.
With Chrome keeps working, using Safari, it prints these logs:
The last one log is called multiple times until I close the tab.

```
[Error] TypeError: null is not an object (evaluating 'this.gWQ().$3')
	oW (main.dart.js:52915)
	z3 (main.dart.js:48158)
	$1 (main.dart.js:48165)
	abQ (main.dart.js:571)
	(funzione anonima) (main.dart.js:580)
[Error] 
	$0 (main.dart.js:18417)
	aaI (main.dart.js:1625)
	aaM (main.dart.js:1627)
	$1 (main.dart.js:17666)
	abQ (main.dart.js:571)
	(funzione anonima) (main.dart.js:580)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (main.dart.js.map, line 0)
[Error] TypeError: null is not an object (evaluating 'this.gWS().$1')
	WT (main.dart.js:52912)
	PI (main.dart.js:48191)
	(funzione anonima) (Script anonimo 1 (linea 2))
	$1 (main.dart.js:48335)
	$1 (main.dart.js:48200)
	abQ (main.dart.js:571)
	(funzione anonima) (main.dart.js:580)
```


Using the debug build version, safari logs these:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (stack_trace_mapper.dart.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (dart_sdk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (client.dart.js.map, line 0)
[Debug] dart.developer.registerExtension – "ext.flutter.disassemble" (dart_sdk.js, line 45147)
[Error] Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
	_rethrow (dart_sdk.js:28723)
	(funzione anonima) (dart_sdk.js:28719)
	_microtaskLoop (dart_sdk.js:25352)
	_startMicrotaskLoop (dart_sdk.js:25358)
	(funzione anonima) (dart_sdk.js:25433)
	promiseReactionJob
[Error] TypeError: t3.onPointerDataPacket is not a function. (In 't3.onPointerDataPacket(packet)', 't3.onPointerDataPacket' is null)
	(funzione anonima) (ui.ddc.js:5304)
	[_onPointerData]
	(funzione anonima) (ui.ddc.js:5595)
	(funzione anonima) (ui.ddc.js:5407)
```

**Comment by grouma** [comment] 2019-07-26 16:43
I'm struggling to reproduce this issue with any of our sample Flutter apps. Can you provide a small zip containing a repo?

**Comment by tapeo** [comment] 2019-07-31 12:51
Here it is the sample.

[issue_sample.zip](https://github.com/flutter/flutter/files/3451884/issue_sample.zip)

**Comment by grouma** [comment] 2019-08-07 15:49
Thanks for the sample. I was able to reproduce your issue locally. This appears to be an issue with both DDC and Dart2JS but only in Safari. Very strange!

The errors I'm seeing are:
DDC: `Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.`
Dart2JS: `TypeError: null is not an object`

Note that compilation with `webdev` succeeds. Bouncing over to @vsmenon to triage and resolve.

**Comment by vsmenon** [comment] 2019-08-12 23:22
This appears to be some Font related issue.  The app is hitting an error on this line in Safari:

https://github.com/flutter/flutter_web/blob/4520a11a3499ca4c487dddfbbf45e20644de0df8/packages/flutter_web_ui/lib/src/engine/text/font_collection.dart#L126

due to `style: 'bold'`.  If I edit `FontManifest.json` to remove the `bold`, the app loads fine.

@ferhatb - can you please retriage?

**Comment by ferhatb** [comment] 2019-08-21 20:38
@tapeo , Please see font issue above and close if that resolves your issue.

**Comment by iapicca** [comment] 2019-11-15 13:05
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-15 13:05 UTC
Labels: waiting for customer response, ☸ platform-web

**Comment by suhmeanhuck** [comment] 2021-03-03 19:40
I have the exact same issue **only on Safari**. Firefox, Microsoft Edge, and Chrome are all working perfectly. I tried to delete the font weights using bold and deleting Cupertino icons and fonts to no effect.

Safari Console:

[Error] 
	$0 (main.dart.js:34302)
	aWS (main.dart.js:4369)
	aXa (main.dart.js:4371)
	$1 (main.dart.js:33185)
	aYZ (main.dart.js:2806)
	(anonymous function) (main.dart.js:2814)

Flutter Doctor -v report:

[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.22.0 at /Users/redacted/Downloads/flutter
    • Framework revision d408d302e2 (5 months ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/redacted/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • D0C7B53E-F48C-41CA-804D-2FB21EF32023 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)  • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 88.0.4324.192

• No issues found!

**Comment by suhmeanhuck** [comment] 2021-03-03 20:09
P.ayb.prototype = {
        $0: function() {
            var s = H.d(this.a)
            s.stack = J.b9(this.b)
            throw s
        }, <-----------------------------------------------------the console shows that the error is here?-------------------
        $S: 0
    }

<img width="1280" alt="Screen Shot 2021-03-03 at 2 06 20 PM" src="https://user-images.githubusercontent.com/4127689/109865703-fd4b3580-7c29-11eb-8d55-10d88c752c23.png">
