### ISSUE TITLE
The following _CastError was thrown building MyAppFul(dirty, dependencies: [MediaQuery], state: _MyAppFulState#4fca6): Null check operator used on a null value  The relevant error-causing widget was:   MyAppFul

### ISSUE THREAD

**Issue by Priyanshu078** [flutter/flutter#84508] opened 2021-06-13 04:48 UTC

**Comment by TahaTesser** [comment] 2021-06-14 11:22
duplicate of https://github.com/flutter/flutter/issues/84509

**Closed by TahaTesser** 2021-06-14 11:22 UTC
Labels: in triage
