### ISSUE TITLE
Unable to build flutter on Termux

### ISSUE THREAD

**Issue by nekoedges** [flutter/flutter#157078] opened 2024-10-17 06:08 UTC
### Steps to reproduce

1. Install git and clone flutter repo to `$HOME/development/flutter`
2. Run `export PATH=$PATH:$HOME/development/flutter/bin`
3. Run `flutter doctor`

### Actual results

Flutter can't find 'pub upgrade' command

### Logs

<details open>
<summary>Logs</summary>

```console

~/development/flutter $ flutter --verbose doctor  Downloading Linux arm64 Dart SDK from Flutter engine 36335019a8eab588c3c2ea783c618d90505be233...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:-  0  202M    0 72379    0     0  87513      0  0:4  0  202M    0 1134k    0     0   623k      0  0:0  1  202M    1 2159k    0     0   735k      0  0:0  1  202M    1 2943k    0     0   741k      0  0:0  1  202M    1 3823k    0     0   792k      0  0:0  2  202M    2 5040k    0     0   866k      0  0:0  2  202M    2 6032k    0     0   884k      0  0:0  3  202M    
<...>
 99  202M   99  200M    0     0  1715k      0  0:0100  202M  100  202M    0     0  1722k      0  0:02:00  0:02:00 --:--:-- 2797k
Building flutter tool...
/data/data/com.termux/files/home/development/flutter/bin/internal/shared.sh: line 23: /data/data/com.termux/files/home/development/flutter/bin/cache/dart-sdk/bin/dart: cannot execute: required file not found                                           Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)             /data/data/com.termux/files/home/development/flutter/bin/internal/shared.sh: line 23: /data/data/com.termux/files/home/development/flutter/bin/cache/dart-sdk/bin/dart: cannot execute: required file not found
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

flutter doctor -v
Building flutter tool...
/data/data/com.termux/files/home/development/flutter/bin/internal/shared.sh: line 23: /data/data/com.termux/files/home/development/flutter/bin/cache/dart-sdk/bin/dart: cannot execute: required file not found                                           Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

```

</details>

**Comment by huycozy** [comment] 2024-10-17 10:08
Closing this as a duplicate of https://github.com/flutter/flutter/issues/75864.

**Closed by huycozy** 2024-10-17 10:08 UTC
Labels: in triage
