### ISSUE TITLE
The `run_debug_test` and `run_release_test` tests are flaky on every commit for all platforms

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#123139] opened 2023-03-21 17:31 UTC
The flake happens since engine roll: https://github.com/flutter/flutter/commit/7d1b0b5b6bf9c7b4df6a3705b83c06b9ffbf7d1c

Example build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20run_debug_test_linux/424/overview

```
 run:stdout: Application finished.
[run_debug_test_linux] [STDERR] Task failed: flutter run  had unexpected output on standard error.
[run_debug_test_linux] [STDERR] 
[run_debug_test_linux] [STDERR] Stack trace:
[run_debug_test_linux] [STDERR] package:flutter_devicelab/tasks/run_tests.dart 332:9       RunOutputTask.call.<fn>
[run_debug_test_linux] [STDERR] ===== asynchronous gap ===========================
[run_debug_test_linux] [STDERR] dart:async                                                 _CustomZone.registerBinaryCallback
[run_debug_test_linux] [STDERR] package:flutter_devicelab/framework/framework.dart 274:26  _TaskRunner._performTask.<fn>
[run_debug_test_linux] [STDERR] package:stack_trace                                        Chain.capture
[run_debug_test_linux] [STDERR] package:flutter_devicelab/framework/framework.dart 273:11  _TaskRunner._performTask
[run_debug_test_linux] [STDERR] package:flutter_devicelab/framework/framework.dart 166:43  _TaskRunner.run
```

<img width="507" alt="Screenshot 2023-03-21 at 10 30 43 AM" src="https://user-images.githubusercontent.com/54558023/226693200-6e4aa53d-4709-44b4-b108-2d48d9104ce6.png">

**Comment by loic-sharma** [comment] 2023-03-21 17:47
It looks like this is a dupe of other issues: https://github.com/flutter/flutter/issues/123066, https://github.com/flutter/flutter/issues/123066.

Fix is here: https://github.com/flutter/flutter/pull/123133

**Comment by christopherfujino** [comment] 2023-03-21 17:56
Closing as a duplicate of https://github.com/flutter/flutter/issues/123066

**Closed by christopherfujino** 2023-03-21 17:56 UTC
Labels: tool, team: flakes, P1, severe: flake
