### ISSUE TITLE
Wrong menu bar when use TextField as Scaffold appBar title on iOS

### ISSUE THREAD

**Issue by anchaoLu** [flutter/flutter#119883] opened 2023-02-03 02:28 UTC
When use TextField as Scaffold appBar title
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const TextField(),
        ),
        body: const Center(
          child: Text('textfield long press'),
        ),
      ),
    );
  }
}
```
after long press textfield, the menu bar offset too large
![IMG_0187](https://user-images.githubusercontent.com/106209730/216249143-7f60e75e-cae9-4bd6-adce-4cf14099a40b.PNG)

and this code meets same problem
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: TextField(),
        ),
      ),
    );
  }
}
```

**Comment by gnprice** [comment] 2023-02-03 04:58
This looks like a duplicate of #119441.

**Comment by danagbemava-nc** [comment] 2023-02-03 06:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/119441

**Closed by danagbemava-nc** 2023-02-03 06:41 UTC
Labels: in triage
