### ISSUE TITLE
TextPainter.computeLineMetrics return weird results

### ISSUE THREAD

**Issue by marco2250** [flutter/flutter#49062] opened 2020-01-17 16:15 UTC
channel "master". last flutter version taken yesterday

```console
MaxWidth: 252.42857142857144
FontSize: 12
Font name: Poppins
MaxLines: 3
```

Two text examples:
> Pão fresquinho, hamburgúer suíno de 200g (pernil suino, bacon, cebola, molho shoyu, molho ingles, alho e sal), queijo alface americana e tomate. acompanha

Above text returns 4 lines (this is right!)

> Pão de hambúrguer, hambúrguer artesanal 150g, maionese artesanal, geléia de frutas vermelhas, bacon e queijo brie.

Above text returns 3 lines (this is wrong. when it renders, it shows 4 lines).

Code to get the number of lines:

```dart
final textSpan = TextSpan(
      text: text,
      style: style,
    );

    final textPainter = TextPainter(
      text: textSpan,
      textDirection: TextDirection.ltr,
      maxLines: maxLines
    );

    textPainter.layout(
      //minWidth: minWidth,
      maxWidth: maxWidth,
    );

    List<ui.LineMetrics> lines = textPainter.computeLineMetrics();
```

Thank you in advance

**Comment by markusaksli-nc** [comment] 2020-09-25 09:37
This still remains unchanged on the latest master `1.22.0-10.0.pre.356` https://github.com/flutter/flutter/blob/0d945a1a5643ab9d1091e9bc56aed4b281f05463/packages/flutter/lib/src/widgets/scroll_physics.dart#L646

**Comment by markusaksli-nc** [comment] 2020-09-25 09:55
Closing since this seems to be working as intended on the latest master `1.22.0-10.0.pre.356`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.356, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.356 at C:\Development\flutter_master
    • Framework revision c412fd9967 (2 hours ago), 2020-09-24 22:47:03 -0700
    • Engine revision 435db234e4
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.51

• No issues found!
```
</details>
<details>
 <summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final textSpan = TextSpan(
      text:
          'Pão de hambúrguer, hambúrguer artesanal 150g, maionese artesanal, geléia de frutas vermelhas, bacon e queijo brie.',
      style: TextStyle(
        color: Colors.black,
        fontSize: 12,
      ),
    );

    final textPainter = TextPainter(
        text: textSpan, textDirection: TextDirection.ltr, maxLines: 3);

    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
          appBar: AppBar(
            title: Text('Sample'),
          ),
          body: Column(
            children: [
              ConstrainedBox(
                constraints: BoxConstraints(maxWidth: 252.42857142857144),
                child: RichText(
                  text: textSpan,
                ),
              ),
              RaisedButton(
                onPressed: () {
                  textPainter.layout(
                    maxWidth: 252.42857142857144,
                  );
                  List<LineMetrics> lines = textPainter.computeLineMetrics();
                  print(lines.length);
                },
              ),
            ],
          )),
    );
  }
}
```
</details>

If you disagree, please let me know and I'll re-open.

**Closed by markusaksli-nc** 2020-09-25 09:55 UTC
Labels: a: typography, framework
