### ISSUE TITLE
Slow performance on an older phone

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#11861] opened 2017-08-31 01:32 UTC
Report of poor performance for a specific older phone, in a comment on the Medium article:
https://medium.com/@carlos_2267/flutter-looks-promising-but-right-now-it-doesnt-perform-well-against-react-native-on-my-4-year-old-a43505951003

"Flutter looks promising but right now it doesn’t perform well against React Native on my 4 year old phone (Sony Xperia ZL: Android 5.1, 1080p, 2GB RAM, etc — http://www.gsmarena.com/sony_xperia_zl-5203.php). 
React Native’s UIExplorer is butter smooth whereas Flutter’s Gallery takes very long to start and animations skip a lot causing bad user experience."

**Comment by eseidelGoogle** [comment] 2017-08-31 04:55
That's a relatively old device (4 years), however I would still expect Flutter should probably run fine.

The GPU is Adreno 320 which is quite common (3.4% of all devices, according to unity stats).

I don't know how this compares to the Moto G4 (which is our current low-end test target).

**Comment by sisel** [comment] 2017-09-29 10:12
Obviously lag on motion when I try hamilton app
Device:OneplusOne (801soc 3gb ram) full charged

**Comment by timahrentlov** [comment] 2017-11-29 14:42
Just tried the default project on an x-cover 3 api 22 samsung phone. Boy is it slow. In both debug/release mode. It takes 4+ seconds from when I tap the floating button until the counter is updated.

Fresh flutter install on my main xamarin forms development machine. Oh well. Will try again in a few weeks to see whats the speed rave is all about :o)

**Comment by rrousselGit** [comment] 2017-11-29 15:12
I'm using a nexus 5 (4 years old) but I don't have any problem. Even in debug mode.

**Comment by timahrentlov** [comment] 2017-11-29 15:36
I wish I could say the same.

I installed flutter today. Tooling works. It’s pretty much plug and play :+1:

It is just slow. Even in my iOS simulator it is not all that snappy. Feels like everything is interpreted.

But I will revist later on and test on my x-cover 3 again which btw is a production phone model for a xamarin forms project i’m working on ;-)

Tim Ahrentløv
Frozengnu ApS

**Comment by sethladd** [comment] 2017-11-29 16:43
@timahrentlov just to double check, is there a "slow mode" banner in the upper right?

**Comment by sethladd** [comment] 2017-11-29 18:24
@timahrentlov just to be clear, in release mode the performance is too slow on an x-cover 3 api 22 samsung phone?

If you've confirmed that you're using Release Mode (no "slow mode banner"), something odd is going on. No one should see a 4-second delay when tapping on a button.

I just purchased a "Galaxy Xcover 3 SM-G389F 8GB" to see if we see the same behavior.

**Comment by timahrentlov** [comment] 2017-11-29 18:36
That is correct. Tomorrow I can make a small video for you. I will also try the same procedure on my laptop to see if the problem is local to my stationary.

Tim Ahrentløv
Frozengnu ApS

**Comment by timahrentlov** [comment] 2017-11-30 07:52
Heres a small video record with Vysor: https://www.dropbox.com/s/c4fvfhn8j7dwc5g/screencapture-1512028202422.mp4?dl=0

Tim Ahrentløv
Frozengnu ApS

**Comment by timahrentlov** [comment] 2017-11-30 14:03
As promised, tried building it on my laptop and now it is fast: https://www.dropbox.com/s/2hmxfn3a6cxq97p/screencapture-1512050385703.mp4?dl=0

So it is the toolchain that somehow did not land well on my iMac. Dunno why. Yet.

**Comment by sethladd** [comment] 2017-11-30 16:47
Thank you for the followup! I'm not sure what would trigger a four-second delay on button taps from our toolchain. I'm glad you found a workaround.

**Comment by shifujun** [comment] 2018-03-24 09:39
I got same problem on Samsung S4.
Demo tap to count app response very slow when I tap quickly.And the Flutter Gallery I build myself is very slow too. And of cause they are built with `flutter build apk` in release mode.
I use a Ubuntu 18.04 in VMware. Is this really matters? 

bad luck for me, the other device I have is YQ601, which crash at start up...

**Comment by eseidelGoogle** [comment] 2018-03-26 14:51
@shifujun Sorry to hear about the trouble.  Would you be willing to to file a bug about the crash on the YQ601?  That's definitely not expected and we would love to learn more:
https://github.com/flutter/flutter/issues/new

**Comment by newfivefour** [comment] 2018-03-28 23:31
On my Nexus 4 the animations are smooth. 

On my Nexus 7, however, the animations are much slower and choppier. 

Is there a good way to profile and detail the performance problems without recording a video?

**Comment by shifujun** [comment] 2018-03-29 13:48
@eseidelGoogle I found there is a same issue #15228. And I'd love to report bugs.

**Comment by JaysusM** [comment] 2018-04-01 15:07
Same problem here with Huawei ale-L21 (2015), the same APK installed in newer phones works nice, are there any solutions?

**Comment by dahabit** [comment] 2018-04-30 21:16
Hello, Dartisans any updates about this issue?

**Comment by johnson-yeap** [comment] 2018-05-01 02:28
It is running slow on my Samsung S4 too.

**Comment by al1b** [comment] 2018-05-14 03:53
I've downloaded Flutter Gallery on my `HTC One A9`:


Chipset | Qualcomm MSM8952 Snapdragon 617
-- | --
CPU | Octa-core (4x1.5 GHz Cortex-A53 & 4x1.2 GHz Cortex-A53)
GPU | Adreno 405

It seems slow and not smooth at all.

Here is the frame-rates in `material` and `chips` page.

Section	|	Frame-rates
-- | --
GPU	|	3.6 fps
UI	|	8.4 fps

**Comment by AtomStar** [comment] 2018-05-18 10:21
I can confirm the slow startup on a **Samsung Mini S4** running `Android Kitkat 4.4.2`. I installed the APK (debug mode) of a simple app and it takes 8 seconds to startup. Once it runs the performance seems fine. In South Africa we have lots of older devices still in use. Hope this will get fixed

**Comment by PhillipMwaniki** [comment] 2018-05-19 09:39
I can form there is a lag on flutter apps. I have a nexus 6p and the transition from one textfield to another is so slow that I can actually see the labels transition to floating. Is there a fix for this ?

**Comment by PhillipMwaniki** [comment] 2018-05-21 20:27
@eseidelGoogle Yeah that was it. Saw it in the readme.

**Comment by TheBosZ** [comment] 2018-05-24 17:17
I can confirm the results by @al1b on an HTC One A9 (running LineageOS 14.1).

Chips page:
GPU - 4.9 fps
UI - 7.6 fps

Other pages **start** slow, but speed up after the list is fully scrolled (like the items are getting built, but once they're all built/cached, everything is fine).

I see that happening on the "Material" page or any of the item pages on the "Shopping" app.

**Comment by al1b** [comment] 2018-05-24 17:29
@TheBosZ I have created an issue here #17694

**Comment by miliakhaled** [comment] 2018-07-19 14:37
I also confirm, the app is very slow . I installed "Shrine" from the store and it has the same problem: a slow performance.

**Comment by eseidelGoogle** [comment] 2018-07-19 17:49
@mikejurka I assume you mean https://play.google.com/store/apps/details?id=nicholaslie.flutter.shrine ?  Would be useful to know more about what hardware you're running on. :)

**Comment by miliakhaled** [comment] 2018-07-19 18:32
A Chinese phone called Gionee M5 mini
1.3 GHz quad core mediatek MT6580 CPU with 2gb RAM

**Comment by yaronlevi** [comment] 2018-08-01 06:38
Hope those performance issues on old devices will be ironed out in future releases. Could be a show stopper for some when making the switch from native or react native.

**Comment by zoechi** [comment] 2018-08-01 06:55
@yaronlevi ensure you do performance evaluation only with release builds. Debug builds have different performance characteristics. 
And of course the Flutter team continually works on improving performance.

**Comment by jmihelcic** [comment] 2018-08-05 19:32
I am also experiencing jank on both the gallery app (downloaded from Play Store) and my own apps.
I am testing on my **Nexus 4 (6.0.1 Android version)**. 

Currently I'm writing a simple timetable application and I'm hitting a wall with scrolling performance.
This is the gist of the problem:
[https://gist.github.com/jmihelcic/1ee86b4790efa021a25d52188b284b3a](https://gist.github.com/jmihelcic/1ee86b4790efa021a25d52188b284b3a)

As you can see I've tried multiple approaches all of which produce stuttering when scrolling. I've been playing around with this for about 4 hours now, and I've noticed that when I use **any** kind of container **(Row, Column, ListTile)** the performance suffers. Only when I use **Text()** do I get butter smooth 60 fps.

ps. The item count is around 40. And the app is build with flutter run --release

**Comment by kgamecarter** [comment] 2019-01-10 05:42
the 2018 new phone with S660 + Adreno 512
is still a little slow

**Comment by honey-hoper** [comment] 2019-04-15 11:30
slow performance on Xiaomi Redmi 2 (Kitkat). I build the company name generator app from Flutter docs. List View scrolling janks and transition to other screen is also slow.

**Comment by jnaval04** [comment] 2019-08-06 02:21
Any updates on this one? I am encountering performance issue deploying my release apk to Asus Zenfone 5 (T00j). I think this is the phone [specs](https://www.gsmarena.com/asus_zenfone_5_a500cg_(2014)-5952.php).

Here is my flutter doctor:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F203, locale en-PH)
    • Flutter version 1.7.8+hotfix.4 at /Users/jnaval/Workspace/FlutterWorkspace/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/jnaval/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • ASUS T00J • F1AZFG016863 • android-x86 • Android 4.4.2 (API 19)
```

**Comment by iapicca** [comment] 2019-11-01 13:32
Hi @wmleler 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Closed by iapicca** 2019-11-01 13:32 UTC
Labels: e: device-specific, engine, from: review, severe: performance
