### ISSUE TITLE
[pointer_interceptor] Widget flickers when page rebuilt under pointer_interceptor 

### ISSUE THREAD

**Issue by jeannelim** [flutter/flutter#77369] opened 2021-03-05 14:24 UTC
I am still having the same problems when using flutter widgets on top of HtmlElementView. I read the comments on issue #54027 and it looks like it is still a bug and the temporary fix is to use Pointer Interceptor. Is this still the case? It has been a while since the last comment and the bug report has been closed.

**Comment by TahaTesser** [comment] 2021-03-05 14:57
Hi @jeannelim 
This has been into a package, check out https://github.com/flutter/flutter/issues/54027#issuecomment-747132587,  not a temporary fix, hence the issue is closed 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by jeannelim** [comment] 2021-03-05 16:26
Thanks for the clarification. I'm using the Pointer Interceptor package and it works on some cases and not in others. I tried to replicate it in a sample app. When MyHomePage is rebuilt, with the Pointer Interceptor the page flickers when the comment button appears and without the Pointer Interceptor the comment button just appears without any flickering. What would you suggest?

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    print('counter pressed');
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(children: <Widget>[
        MyHtmlView(
          src: "assets/sample.pdf",
        ),
        if (_counter==2) PointerInterceptor(
          child: 
          Center(
            child: FloatingActionButton(
              onPressed: () => print('comment button pressed'),
              child: Icon(Icons.comment),
            ),
          ),
        ),
      ]),
      floatingActionButton: PointerInterceptor(
        child: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Increment',
          child: Icon(Icons.add),
        ),
      ),
    );
  }
}

class MyHtmlView extends StatefulWidget {
  final Key key;
  final String src;
  final double height, width;
  MyHtmlView({this.key, this.src, this.height, this.width});

  @override
  State<StatefulWidget> createState() {
    return MyHtmlViewState();
  }
}

class MyHtmlViewState extends State<MyHtmlView>
    with AutomaticKeepAliveClientMixin {
  @override
  void initState() {
    super.initState();
    final html.IFrameElement _iframeElement = html.IFrameElement()
      ..height = '100%'
      ..width = '100%'
      ..src = widget.src
      ..style.border = 'none'
      ..style.overflow = "hidden"
      ..allow = "autoplay"
      ..allowFullscreen = true;
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      widget.src,
      (int viewId) => _iframeElement,
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Stack(children: <Widget>[
      Center(
        child: HtmlElementView(
          viewType: widget.src,
        ),
      ),
    ]);
  }
}

**Comment by TahaTesser** [comment] 2021-03-09 12:15
Hi @jeannelim 
Can you please provide your `flutter doctor -v`  and a complete reproducible minimal code sample including sample asset such as pdf here
Thank you

**Comment by jeannelim** [comment] 2021-03-09 13:24
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale
    en-CA)
    • Flutter version 2.0.1 at /Users/jeanne.lim/development/flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jeanne.lim/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPad (8th generation) (mobile) • 526D8BD4-02C3-4B6E-8A78-78C44C883EB8 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                   • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

• No issues found!


[sample.pdf](https://github.com/flutter/flutter/files/6108753/sample.pdf)


And the exact code in my main.dart:

import 'package:flutter/material.dart';
import 'dart:html' as html;
import 'dart:ui' as ui;

import 'package:pointer_interceptor/pointer_interceptor.dart';

void main() {
  runApp(MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    print('counter pressed');
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(children: <Widget>[
        MyHtmlView(
          src: "assets/sample.pdf",
        ),
        if (_counter == 2)
          //PointerInterceptor(
            //child: 
            Center(
              child: FloatingActionButton(
                onPressed: () => print('comment button pressed'),
                child: Icon(Icons.comment),
              ),
            ),
          //),
      ]),
      floatingActionButton: PointerInterceptor(
        child: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Increment',
          child: Icon(Icons.add),
        ),
      ),
    );
  }
}

class MyHtmlView extends StatefulWidget {
  final Key key;
  final String src;
  final double height, width;
  MyHtmlView({this.key, this.src, this.height, this.width});

  @override
  State<StatefulWidget> createState() {
    return MyHtmlViewState();
  }
}

class MyHtmlViewState extends State<MyHtmlView>
    with AutomaticKeepAliveClientMixin {
  @override
  void initState() {
    super.initState();
    final html.IFrameElement _iframeElement = html.IFrameElement()
      ..height = '100%'
      ..width = '100%'
      ..src = widget.src
      ..style.border = 'none'
      ..style.overflow = "hidden"
      ..allow = "autoplay"
      ..allowFullscreen = true;
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      widget.src,
      (int viewId) => _iframeElement,
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Stack(children: <Widget>[
      Center(
        child: HtmlElementView(
          viewType: widget.src,
        ),
      ),
    ]);
  }
}

**Comment by TahaTesser** [comment] 2021-03-10 08:40
Hi @jeannelim 
Thanks for the complete code sample, I can reproduce `flickering` FAB with `pointer_interceptor: ^0.9.0`

<details> 
<summary>code sample</summary> 

```dart
import 'dart:html' as html;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:pointer_interceptor/pointer_interceptor.dart';

void main() {
  runApp(MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    print('counter pressed');
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(children: <Widget>[
        MyHtmlView(
          src: "assets/sample.pdf",
        ),
        if (_counter == 2)
          //If this PointerInterceptor is commented out no flickering, but the button can't be clicked
          // PointerInterceptor(
          // child:
          Center(
            child: FloatingActionButton(
              onPressed: () => print('comment button pressed'),
              child: Icon(Icons.comment),
            ),
          ),
        // ),
      ]),
      floatingActionButton: PointerInterceptor(
        child: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Increment',
          child: Icon(Icons.add),
        ),
      ),
    );
  }
}

class MyHtmlView extends StatefulWidget {
  final Key key;
  final String src;
  final double height, width;
  MyHtmlView({this.key, this.src, this.height, this.width});

  @override
  State<StatefulWidget> createState() {
    return MyHtmlViewState();
  }
}

class MyHtmlViewState extends State<MyHtmlView>
    with AutomaticKeepAliveClientMixin {
  @override
  void initState() {
    super.initState();
    final html.IFrameElement _iframeElement = html.IFrameElement()
      ..height = '100%'
      ..width = '100%'
      ..src = widget.src
      ..style.border = 'none'
      ..style.overflow = "hidden"
      ..allow = "autoplay"
      ..allowFullscreen = true;
    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      widget.src,
      (int viewId) => _iframeElement,
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Stack(children: <Widget>[
      Center(
        child: HtmlElementView(
          viewType: widget.src,
        ),
      ),
    ]);
  }
}

``` 

</details>

[sample.pdf](https://github.com/flutter/flutter/files/6114429/sample.pdf)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.4.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 89.0.4389.82
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!
```

</details>

Thanks for filing  the issue!

**Comment by ditman** [comment] 2021-03-11 19:41
This is most likely related to https://github.com/flutter/flutter/issues/71888; @jeannelim can you take a look at 71888 and see if it seems familiar?

**Comment by jeannelim** [comment] 2021-03-12 19:18
No, I don't think it's the same issue.

My problem is using Pointer Interceptor when the state changes. Originally in my sample code I have this

```dart
        if (_counter == 2)
          //If this PointerInterceptor is commented out no flickering, but the button can't be clicked
          PointerInterceptor(
            child: 
            Center(
              child: FloatingActionButton(
                onPressed: () => print('comment button pressed'),
                child: Icon(Icons.comment),
              ),
            ),
          ),
```

so when _counter == 2 the page would flicker because of the Pointer Interceptor. But if I move the condition to the child it doesn't flicker anymore.

```dart
        //if (_counter == 2)
          //If this PointerInterceptor is commented out no flickering, but the button can't be clicked
          PointerInterceptor(
            child: _counter == 2 ?
            Center(
              child: FloatingActionButton(
                onPressed: () => print('comment button pressed'),
                child: Icon(Icons.comment),
              ),
            )
            : Container(width: 1, height: 1),
          ),
```

So it's like the Pointer Interceptor has to be built on the first build. Does that make sense?

**Comment by gib40f** [comment] 2021-04-07 00:40
I am seeing a similar issue. I have a PDF being rendered and I am showing an AlertDialog. If I wrap the AlertDialog with PointerInterceptor I can click on fields and buttons but when the AlertDialog is shown it does a "load" on the PDF viewer inside the HtmlElementView and re-renders it at the beginning of the PDF document. 

If I don't wrap with PointerInterceptor it doesn't do a load again and remains at same position but I can't click on buttons and fields in the AlertDialog.

**Comment by ditman** [comment] 2021-04-07 00:58
@gib40f can you minimally reproduce the issue (in a new flutter issue?). I'm currently working in rendering HtmlElementViews in a way that shouldn't reload, and the more test cases, the better!

**Comment by gib40f** [comment] 2021-04-07 02:00
David,

Here is a link to a minimal Flutter project that I think demonstrates the behaviour.

https://github.com/gib40f/flutterpointerinterceptor

Much appreciated that you are looking into it.

Thanks

Simon

Simon Gibson
Software Engineer | The Australian e-Health Research Centre
CSIRO Health and Biosecurity

T: +61 7 3253 3613 |  M: 044 976 8823
E: ***@***.*** | www.csiro.au | www.aehrc.com
Address: Level 5 - UQ Health Sciences Building 901/16, Royal Brisbane and Women's Hospital,  Herston   Qld  4029
________________________________

**Comment by ditman** [comment] 2021-04-15 18:58
I've started working on this, please track progress here: https://github.com/flutter/flutter/issues/80524

**Closed by ditman** 2021-04-15 18:58 UTC
Labels: assigned for triage, found in release: 2.0, has reproducible steps, p: first party, p: pointer_interceptor, package, platform-web

**Comment by ditman** [comment] 2021-04-19 18:54
@gib40f it seems that your platform view is *not* being rendered underneath the bottom bar.

In the example that you produced there's no need for the pointer interceptor. It is only required when the buttons are OVERLAID on top of the HtmlElementView (think of a Stacked widget, is the most extreme case of this)

This is what your app looks like, in `html` render mode, in the chrome devtools:

<img width="1538" alt="Screen Shot 2021-04-19 at 11 51 35 AM" src="https://user-images.githubusercontent.com/1255594/115288038-d37c9e00-a105-11eb-9f27-2b0d9b0044db.png">

**Comment by ditman** [comment] 2021-04-19 23:37
@gib40f ahhh, I misunderstood, I thought it was the two buttons in the first page. My apologies. Let me verify again with the experimental engine I'm building!

**Comment by ditman** [comment] 2021-04-19 23:53
@gib40f here's the deployed version of your demo app with the experimental engine applied, the PDF is not reloading anymore:

https://dit-grain-pdf-reload.web.app

(Note that "Without PointerInterceptor" is letting mouse events go through the modal and into the PDF, so I guess the preferred way of showing this modal is **With** PointerInterceptor.)

The only modification I had to do to your code is just to ensure the iframe has a 100% height/width so it fills the allocated space by the framework:

```diff
$ git diff lib
diff --git a/lib/main.dart b/lib/main.dart
index f85adbf..eb56868 100644
--- a/lib/main.dart
+++ b/lib/main.dart
@@ -152,6 +152,8 @@ class _MyHomePageState extends State<MyHomePage> {
         ..id = uri.hashCode.toString()
         ..src = uri
         ..style.border = 'black'
+        ..style.width = '100%'
+        ..style.height = '100%'
         ..addEventListener('load', (event) {
           print('load event happened - ${event.type}');
         });
```
