### ISSUE TITLE
Installation of MS Visual Studio 2022

### ISSUE THREAD

**Issue by andreiholder** [flutter/flutter#105211] opened 2022-06-02 10:20 UTC
After i have installed the new Visual Studio 2022, current
Version 17.2.3, the flutter doctor crashed.
[crash report.txt](https://github.com/flutter/flutter/files/8822861/crash.report.txt)

**Comment by danagbemava-nc** [comment] 2022-06-02 10:26
Closing this as a duplicate of #102451. 

Kindly follow up in the linked issue for updates. 

Thank you

**Closed by danagbemava-nc** 2022-06-02 10:26 UTC
Labels: in triage
