### ISSUE TITLE
The following assertion was thrown during a scheduler callback: 'package:flutter/src/rendering/object.dart': Failed assertion: line 5184 pos 18: '!ancestor._needsSemanticsUpdate': is not true.

### ISSUE THREAD

**Issue by ronjb** [flutter/flutter#155785] opened 2024-09-26 21:08 UTC
### Steps to reproduce

1. Compile and run the provided sample code.
2. Tap the Settings icon in the app bar.

### Expected results

Expected no exception.

### Actual results

The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 5184 pos 18: '!ancestor._needsSemanticsUpdate': is not true.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';

void main() {
  runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
    home: Navigator(
        onGenerateRoute: (settings) => MaterialPageRoute<dynamic>(
            settings: settings, builder: (context) => const CitiesScreen())),
  ));
}

class CitiesScreen extends StatelessWidget {
  const CitiesScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Cities'),
        actions: [
          IconButton(
            icon: const Icon(Icons.settings),
            onPressed: () => context.rootNavigator?.push(MaterialPageRoute<dynamic>(
                builder: (context) => Scaffold(appBar: AppBar(title: const Text('Settings'))))),
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Semantics(
          container: true,
          label: 'Search for a city',
          // Using a [TextField] instead of a [TypeAheadField] results in no exceptions.
          // child: const TextField(),
          child: TypeAheadField<String>(
            suggestionsCallback: (search) => CityService().find(search),
            builder: (context, controller, focusNode) {
              return TextField(
                controller: controller,
                focusNode: focusNode,
                autofocus: false,
                decoration: const InputDecoration(border: OutlineInputBorder(), labelText: 'City'),
              );
            },
            itemBuilder: (context, city) => ListTile(title: Text(city)),
            onSelected: (city) => context.rootNavigator?.push(
              MaterialPageRoute<dynamic>(
                builder: (context) => Scaffold(appBar: AppBar(title: Text(city))),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class CityService {
  final cities = ['London', 'Paris', 'Madrid', 'Rome', 'Berlin'];

  List<String> find(String search) {
    return cities.where((city) => city.toLowerCase().contains(search.toLowerCase())).toList();
  }
}

extension on BuildContext {
  /// Returns the root [NavigatorState] of this [BuildContext].
  NavigatorState? get rootNavigator {
    NavigatorState? navigator;
    visitAncestorElements((Element element) {
      if (element is StatefulElement && element.state is NavigatorState) {
        navigator = element.state as NavigatorState;
      }

      // Continue visiting ancestors.
      return true;
    });

    return navigator;
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPad mini (6th generation) in debug mode...
Xcode build done.                                           22.3s
Connecting to VM Service at ws://127.0.0.1:65053/VIgk5qtmN0g=/ws
Connected to the VM Service.

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 5184 pos 18: '!ancestor._needsSemanticsUpdate': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      _SemanticsGeometry._computeValues (package:flutter/src/rendering/object.dart:5184:18)
#3      new _SemanticsGeometry (package:flutter/src/rendering/object.dart:5125:5)
#4      _SwitchableSemanticsFragment._computeSemanticsGeometry (package:flutter/src/rendering/object.dart:5059:9)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4973:42)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:5022:16)
#7      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3701:25)
#8      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1303:16)
#9      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1308:15)
#10     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:609:25)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#16     _invoke (dart:ui/hooks.dart:312:13)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#18     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/ronbooth/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ronbooth/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • iPad mini (6th generation) (mobile) • 137E360C-C0CE-4CE5-8DC3-663E8C4C3653 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 15.0 24A335
      darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 15.0 24A335
      darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome
      129.0.6668.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ronjb** [comment] 2024-09-26 21:15
Here's a public project with the sample app: https://github.com/ronjb/needs_semantics_update_exception

**Comment by huycozy** [comment] 2024-09-27 09:03
Hi @ronjb 
I can't reproduce this issue on my end but I see an issue that has a similar error trace: https://github.com/flutter/flutter/issues/153692. It could be fixed on Flutter beta/master channel per https://github.com/flutter/flutter/issues/153692#issuecomment-2296475357, so can you switch to Flutter beta or master channel and confirm?

**Comment by ronjb** [comment] 2024-09-27 13:30
I'm seeing the same exception on beta:

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPad mini (6th generation) in debug mode...
.gitignore does not ignore Swift Package Manager build directories, updating.
Xcode build done.                                           18.6s
Connecting to VM Service at ws://127.0.0.1:62613/BRyDHLaygVQ=/ws
Connected to the VM Service.

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 5213 pos 18: '!ancestor._needsSemanticsUpdate': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      _SemanticsGeometry._computeValues (package:flutter/src/rendering/object.dart:5213:18)
#3      new _SemanticsGeometry (package:flutter/src/rendering/object.dart:5154:5)
#4      _SwitchableSemanticsFragment._computeSemanticsGeometry (package:flutter/src/rendering/object.dart:5088:9)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:5002:42)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:5051:16)
#7      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3730:25)
#8      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1313:16)
#9      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1318:15)
#10     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:616:25)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1178:13)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#16     _invoke (dart:ui/hooks.dart:312:13)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#18     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.25.0-0.1.pre, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.25.0-0.1.pre on channel beta at /Users/ronbooth/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3733fcb0e (5 weeks ago), 2024-08-21 10:27:04 -0500
    • Engine revision 062b3a72fc
    • Dart version 3.6.0 (build 3.6.0-149.3.beta)
    • DevTools version 2.38.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ronbooth/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • iPad mini (6th generation) (mobile) • 137E360C-C0CE-4CE5-8DC3-663E8C4C3653 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 15.0 24A335
      darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 15.0 24A335
      darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome
      129.0.6668.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ronjb** [comment] 2024-09-27 13:33
@huycozy,

I'm surprised you can reproduce it. Are you trying it on beta or stable? Note, I don't see the exception on web, but I see it every time on iOS.

**Comment by huycozy** [comment] 2024-09-30 04:45
Thanks for checking this on beta channel. I can reproduce this issue now on iOS 18.0 as yours, checked on iPhone 16 Pro emulator and Flutter stable 3.24.3 and master 3.26.0-1.0.pre.263. 

The issue is not reproduced on my device `iPhone 7, iOS 15.8`. I also checked on Android 14 device but the issue is not reproduced there. This seems to be an OS-specific issue on iOS platform.

It seems the issue is related to OverlayPortal. I see the sample code uses a 3rd party package `flutter_typeahead`. Can you please try to narrow the sample code down into a simpler one without using it? That would be helpful for team to quickly look into. Thanks!

**Closed** 2024-10-21 05:09 UTC
Labels: waiting for customer response, in triage
