### ISSUE TITLE
flutter web !state.down is not true

### ISSUE THREAD

**Issue by cooosuper** [flutter/flutter#40550] opened 2019-09-16 04:00 UTC
my code as below:

**main.dart start**
```
import 'package:flutter/material.dart';

import 'c_page_util.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Hello Flutter'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });

    CPageUtil.goToLogin(context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}
```

**c_page_util.dart**
```
import 'package:flutter/material.dart';

import 'login_page.dart';

class CPageUtil {
  static void goToLogin(BuildContext context, {Function onPop}) {
    var future = Navigator.of(context).push(
      new MaterialPageRoute(
          builder: (BuildContext context) => new LoginPage()),);
    if (onPop != null) {
      future.then(onPop);
    }
  }
}
```

**login_page.dart**
```
import 'package:flutter/material.dart';

class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => new _LoginPageState();
}

class _LoginPageState extends State<LoginPage>
    with SingleTickerProviderStateMixin {

  _LoginPageState instance;

  TabController _tabController;
  TextEditingController phoneController = new TextEditingController();
  TextEditingController passwordController = new TextEditingController();

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  _refresh() {
    instance.setState(() {

    });
  }

  void initState() {
    super.initState();
    instance = this;
    _tabController = new TabController(vsync: this, length: 1);
  }

  @override
  Widget build(BuildContext context) {
    return new DefaultTabController(
      length: 1,
      child: new Scaffold(
        appBar: new AppBar(
          title: new Text('登录'),
          actions: <Widget>[
          ],
          centerTitle: true,
        ),
        body: new TabBarView(
          controller: _tabController,
          children: <Widget>[
            new Column(
              children: <Widget>[
                new Container(
                  margin: EdgeInsets.all(10.0),
                  child: new TextField(
                    keyboardType: TextInputType.number,
                    controller: phoneController,
                    decoration: InputDecoration(
                      icon: Icon(Icons.account_circle),
                    ),
                    onChanged: (String str) {},
                  ),
                ),

                new Container(
                  margin: EdgeInsets.all(10.0),
                  child: new TextField(
                    controller: passwordController,
                    keyboardType: TextInputType.number,
                    decoration: InputDecoration(
                      icon: Icon(Icons.lock),
                    ),
                  ),
                ),

                new Container(
                  child: new RaisedButton(
                    color: Theme
                        .of(context)
                        .primaryColor,
                    padding: EdgeInsets.all(10.0),
                    child: new Text('登录'),
                    textColor: Colors.white,
                    onPressed: () {},
                  ),
                  width: double.infinity,
                  padding: EdgeInsets.all(10.0),
                ),

                new Container(
                  child: new Text(
                    '登录遇到问题？',
                    style: new TextStyle(
                      fontSize: 16.0,
                      textBaseline: null,
                      decoration: TextDecoration.none,
                      color: Theme
                          .of(context)
                          .primaryColor,
                      fontStyle: FontStyle.normal,
                      fontWeight: FontWeight.normal,
                    ),
                  ),
                  padding: EdgeInsets.all(10.0),
                ),
              ],
            )
          ],
        ),
      ),
    );
  }
}
```

1. Try select the `phoneTextField` and `passwordTextField`, then the error will occur.
2. Select one by one, the `TextField` will become unable to select.

Please help fix it. Thank you very much.

**Comment by janmoppel** [comment] 2019-09-16 07:14
Hello @cooosuper !

Thank you for posting an issue. 
As it is not clear, whether this problem caused by the Flutter itself or not, this question is more suitable for the StackOverflow. Flutter has a very active and helpful community there, so feel free to post it there. 
Also, it would be very helpful if you could create a self-contained repository with provided code. So that your issue could be easily reproduced.

Closing the issue here for now.

Thank you.

**Closed by janmoppel** 2019-09-16 07:14 UTC
Labels: d: stackoverflow

**Comment by cooosuper** [comment] 2019-09-16 09:57
Here is the exception:
Uncaught Error: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/converter.dart:110:20
!_pointers.containsKey(datum.device)
is not true
    at Object.throw_ [as throw] (errors.dart:191)
    at Object.assertFailed (errors.dart:24)
    at SyncIterable.new.expand (converter.dart:110)
    at expand.next (<anonymous>)
    at ListQueue.new.addAll (queue.dart:655)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (binding.dart:84)
    at _engine.PointerBinding.new.[_onPointerData] (pointer_binding.dart:85)
    at pointer_binding.dart:207
    at HTMLElement.<anonymous> (pointer_binding.dart:143)

 the step to reproduce the issue is very simple. as below:
step1. create a flutter web project
step2. copy my code [main.dart][c_page_util][login_page]
step3. run the cmd: [flutter run -d chrome]
step4. click the TextField one by one. The issue will happen.

And thank you for format my issue. ^.^
