### ISSUE TITLE
TextField's text is duplicated on iOS Japanese Keyboard

### ISSUE THREAD

**Issue by mono0926** [flutter/flutter#59734] opened 2020-06-18 03:22 UTC
TextField's text is duplicated on iOS with Japanese Keyboard at `v1.20.0-0.0.pre`(and also confirmed that is is also broken at latest master `1.20.0-1.0.pre.91`).
This was also reproduced at v1.15.21 and fixed at v1.16.0(#52718, @dnfield), but afterwards it was broken again.

On Android, there are no problems.

## Steps to Reproduce

Run this on iOS simulator or device(I confirmed it by iPhone 11 Pro simulator with iOS 11.5).

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(),
      ),
    );
  }
}
```

1. Full restart the app
1. Focus to the text field
1. Firstly, Japanese keyboard is selected
    - If not, select Japanese keyboard and do full restart again
1. Type 「あ」
1. Type 「か」
1. Type 「さ」

### Expected results:

「あかさ」should be shown and 「あかさ」is selected until return key typed.

![](https://user-images.githubusercontent.com/1255062/76823503-c7197800-6857-11ea-910c-8989bf93654c.gif)

### Actual results:

「あああかあかあかさあかさ」was shown and text wasn't selected(no underline).

![2020-06-18_12-18-50 (1)](https://user-images.githubusercontent.com/1255062/84974336-107ea980-b15e-11ea-9dda-5dd25e9e87fa.gif)

<details>
  <summary>Logs</summary>

```
[   +9 ms] DevFS: Created new filesystem on the device
(file:///Users/mono/Library/Developer/CoreSimulator/Devices/129D38BF-AA4E-4678-BA05-2447CC2CD83E/data/Containers/Data/Application/D5228312-DE45-44A0-80B
D-C90BD9747D60/tmp/flutter_playgroundOtRcms/flutter_playground/)
[   +1 ms] Updating assets
[ +126 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +9 ms] Syncing files to device iPhone 11 Pro...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:flutter_playground/main.dart 1a4440e7-5c9b-4cbc-92f4-7e1b2af1daba
[        ] <- 1a4440e7-5c9b-4cbc-92f4-7e1b2af1daba
[  +35 ms] Updating files
[  +63 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 11 Pro... (completed in 105ms)
[        ] Synced 1.4MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0x7fdc21031a20.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 11 Pro is available at: http://127.0.0.1:61165/9N94MyvFWLw=/
```

```
❯ flutter analyze
Analyzing flutter_app...                                                
No issues found! (ran in 6.8s)
```

```
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale en-JP)
    • Flutter version 1.20.0-0.0.pre at /Users/mono/Git/flutter
    • Framework revision d9653445f4 (8 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mono/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[✓] Connected device (5 available)            
    • Android SDK built for x86 • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone 11 Pro             • 129D38BF-AA4E-4678-BA05-2447CC2CD83E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS                     • macOS                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server                • web-server                           • web-javascript • Flutter Tools
    • Chrome                    • chrome                               • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

</details>

**Comment by LongCatIsLooong** [comment] 2020-06-18 06:12
Couldn't reproduce it on an iOS 13.5 device. I created a new project, replaced the `main.dart` file with the code provided and ran it against the latest master branch.
```
• Framework revision 9c3f0faa6d (7 hours ago), 2020-06-17 18:47:54 -0400
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)
```

I noticed that in your 2nd clip (iOS) the battery indicator icon didn't turn dark when the app launches. That bug should be fixed a few months ago. Could you double check if you're really testing against `1.20.0-1.0.pre.91`?  

![repro](https://user-images.githubusercontent.com/31859944/84983823-6b78b800-b0ee-11ea-82a5-1bc5e1f32159.gif)

**Comment by mono0926** [comment] 2020-06-18 06:30
@LongCatIsLooong 

Thanks for the quick response 🙏 

> I noticed that in your 2nd clip (iOS) the battery indicator icon didn't turn dark when the app launches.

The simulator was dark mode, and after changing it to light mode, the icon color turned to dark correctly.

> Could you double check if you're really testing against 1.20.0-1.0.pre.91?

I confirmed that the version is correct.

These are important steps to reproduce the issue(so, my second clip is recorded before the app was launched):

> 1. Full restart the app
> 1. Focus to the text field
> 1. Firstly, Japanese keyboard is selected
>     - If not, select Japanese keyboard and do full restart again


After switching keyboard or trying second time, text input works well.

**Comment by LongCatIsLooong** [comment] 2020-06-18 06:50
Hmm I think I did exactly that. Before I started recording, I launched the app, switched the keyboard to Japanese, and force killed the app from the app switcher. Then I launched the app again and started recording the gif above. Let's wait and see if anyone else can reproduce this.

**Comment by mono0926** [comment] 2020-06-18 08:16
@LongCatIsLooong 

> I created a new project, replaced the main.dart file with the code provided and ran it against the latest master branch.

Indeed, by this procedure, the issue isn't reproduced 🤔 

Actually, it was reproduced on my other project with dev channel, and after that I verified the issue here with latest master channel(`1.20.0-1.0.pre.91`):
https://github.com/mono0926/flutter_playground/blob/master/lib/main_text_field.dart

```sh
flutter run -t lib/main_text_field.dart
```

This is plain project, created quite a while ago.

And I was doing some additional research now and it stopped reproducing 🤔 
(And on the other project, it keeps broken.)

I'm very confused now, but I'll keep examining for a while.

Thanks!

**Comment by VladyslavBondarenko** [comment] 2020-06-18 13:03
I couldn't reproduce it with current master `1.20.0-1.0.pre.91` on both iPhone 7 iOS 13.5 and iPhone 11 Pro iOS 13.5 (simulator).
But It reproduced with current dev `1.20.0-0.0.pre` on iPhone 7 iOS 13.5, but not on simulator.

**Comment by LongCatIsLooong** [comment] 2020-06-18 22:32
I created a new project using the latest dev branch and run that against the current `upstream/master`, still couldn't repro. However the current `dev` branch is indeed broken (it's already listed as a bad build for a different reason: https://github.com/flutter/flutter/wiki/Bad-Builds).

@mono0926 @VladyslavBondarenko could you try switching to the master channel and upgrading flutter to the latest version (`flutter doctor -v` would be helpful so that we can see the engine/dart hash), and see if it still happens on any of your projects?

**Comment by mono0926** [comment] 2020-06-18 22:53
@LongCatIsLooong 

My verification result is same as this:

> Reproduces when running with any current flutter version (stable 1.17.3, beta 1.19.0-4.1.pre, dev 1.20.0-0.0.pre or master 1.20.0-1.0.pre.91 on iPhone 11 Pro iOS 13.5 (simulator), but with condition that project is created with current dev (doesn't reproduce when project is created with master).

---

> (doesn't reproduce when project is created with master).
> and see if it still happens on any of your projects?

Although there are no problems with clean master project, I'm in trouble with my existing project.
On my exiting project, the problem is reproduced with master channel and I don't know how to fix it.

> could you try switching to the master channel and upgrading flutter to the latest version (flutter doctor -v would be helpful so that we can see the engine/dart hash)

Here it is.

```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.111, on Mac OS X 10.15.5 19F101, locale en-JP)
    • Flutter version 1.20.0-1.0.pre.111 at /Users/mono/Git/flutterm
    • Framework revision bdbe6774a3 (5 minutes ago), 2020-06-18 15:30:00 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mono/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone 11 Pro             • 129D38BF-AA4E-4678-BA05-2447CC2CD83E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS desktop             • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server                • web-server                           • web-javascript • Flutter Tools
    • Chrome                    • chrome                               • web-javascript • Google Chrome 83.0.4103.106
```

**Comment by VladyslavBondarenko** [comment] 2020-06-19 07:58
@LongCatIsLooong 
I needed to stress that problem is not with master. It doesn't reproduce if you create project with master and run it with master (but reproduces if you create project with master and run it with dev).
Probably I applied `regression` label incorrectly, I meant regression in relation to fixed https://github.com/flutter/flutter/issues/52718. 
This is master version used yesterday, which didn't have the problem

```
Flutter 1.20.0-1.0.pre.91 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9c3f0faa6d (11 hours ago) • 2020-06-17 18:47:54 -0400
Engine • revision 965fbbed17
Tools • Dart 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)
```

This is current dev, which has the problem

```
Flutter 1.20.0-0.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision d9653445f4 (9 days ago) • 2020-06-09 18:43:03 -0400
Engine • revision e8c13aa012
Tools • Dart 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)
```

Looks like it's fixed somewhere in between.

<details>
 <summary>Current master doesn't have the problem the same as yesterday's master</summary>

```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.118, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.118 at /Users/nevercode/dev/flutter
    • Framework revision 8665e13801 (6 hours ago), 2020-06-18 18:08:01 -0700
    • Engine revision b5f5e6332c
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 54481776c9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • Nevercode’s iPhone • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.5
    • iPhone 11 Pro      • 6DD22F23-00CF-4A8B-B9E2-AC4DE0B5D263     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS desktop      • macos                                    • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server         • web-server                               • web-javascript • Flutter Tools
    • Chrome             • chrome                                   • web-javascript • Google Chrome 83.0.4103.106

• No issues found!
```

</details>

**Comment by LongCatIsLooong** [comment] 2020-06-19 21:25
FYI the problem still exists on master (at least part of it). I'm experiencing some problems running flutter using a recent engine commit, so I'm not sure exactly why it works on master, but it seems in the framework `EditableText` now has more robust handling of iOS text input plugin messages.

**Closed** 2020-06-22 16:37 UTC
Labels: a: internationalization, a: text input, customer: crowd, engine, f: material design, found in release: 1.17, found in release: 1.19, found in release: 1.20, framework, has reproducible steps, platform-ios, severe: regression
