### ISSUE TITLE
Filtering updateAcquireFence: Did not find frame. out from running embed youtube video

### ISSUE THREAD

**Issue by DiegoGW** [flutter/flutter#138623] opened 2023-11-17 15:17 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Get latest version of Wonderous app (commit 5d7f14fd17038c8bdd3a75ce8cf3e6200728c54d (HEAD -> main, origin/main, origin/HEAD)
  Author: Shawn [shawn@gskinner.com](mailto:shawn@gskinner.com)
  Date: Fri Nov 3 14:30:05 2023 -0600
  Fix centering issue in photo gallery with hidden collectibles )
2. Run Wonderous in Android Studio (target: Pixel 7 + Android 14)
3. Navigate to the Great Wall (Navigate to: /wonder/greatWall?t=0)
4. Once you are in the Great Wall scroll down until you find the youtube video
5. Play the youtube video
6. Check that the errors logged:

```
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
```

### Expected results

No errors should be logged.

### Actual results

Playing a youtube video floods the logs with errors.

### Code sample

<details><summary>Code sample</summary>

```
git clone https://github.com/gskinnerTeam/flutter-wonderous-app.git
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
E/FrameEvents( 6331): updateAcquireFence: Did not find frame.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.17.0-10.0.pre.5, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.17.0-10.0.pre.5 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ca31aa17b2 (38 minutes ago), 2023-11-15 14:48:18 -0500
    • Engine revision 30327eae08
    • Dart version 3.3.0 (build 3.3.0-135.0.dev)
    • DevTools version 2.30.0-dev.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • Somnio’s iPhone (mobile) • 00008120-001168D83C87C01E • ios            • iOS 17.1.1 21B91
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 14.1 23B74 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by DiegoGW** [comment] 2023-11-17 15:18
Similar issues that could be related to this one: https://github.com/flutter/flutter/issues/104268 and https://github.com/flutter/flutter/issues/109939

**Comment by DiegoGW** [comment] 2023-11-22 20:10
Also the following crash is logged after stopping the youtube video:
```
E/chromium( 1531): [ERROR:aw_browser_terminator.cc(156)] Renderer process (7050) crash detected (code -1).
```

**Comment by goderbauer** [comment] 2023-12-05 23:46
Closing as duplicate of https://github.com/flutter/flutter/issues/104268.

**Closed by goderbauer** 2023-12-05 23:46 UTC
Labels: will need additional triage, from: manual-qa
