### ISSUE TITLE
Error When I am run my app.

### ISSUE THREAD

**Issue by lkrjangid1** [flutter/flutter#78291] opened 2021-03-16 04:37 UTC
Today when i am  update flutter using flutter upgrade. and when I am run my app it shows me this error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.flutter:x86_debug:1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_debug:1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4/x86_debug-1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4/x86_debug-1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve io.flutter:x86_64_debug:1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_64_debug:1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4/x86_64_debug-1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4/x86_64_debug-1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.pom'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
Exception: Gradle task assembleDebug failed with exit code 1
```

Flutter Doctor

```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.21327.1010], locale en-IN)
    • Flutter version 2.0.2 at C:\Program Files\flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\lkrja\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31105.61
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\lkrja\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.21327.1010]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!
```

**Comment by sgehrman** [comment] 2021-03-16 04:53
same issue.  Is there a replacement for jcenter?

**Comment by sgehrman** [comment] 2021-03-16 05:04
Seems to be back up now.  Someone suggested switching jcenter() to mavenCentral(), but that failed too.  Java is a disaster.  Flutter Android needs to dump Java if possible.

**Comment by pedromassangocode** [comment] 2021-03-16 09:01
Hi @thealteria 
Can you please provide your `flutter run --release --verbose` (running on same Android device) and your `pubspec.yaml`. 
Thank you


Similar to https://github.com/flutter/flutter/issues/78293

**Comment by pedromassangocode** [comment] 2021-03-17 10:16
I'm going to close this as duplicate of https://github.com/flutter/flutter/issues/78338 as this was caused by JCenter being down. 

Flutter team is planning to move android repositories away from JCenter.
Thank you

**Closed by pedromassangocode** 2021-03-17 10:16 UTC
Labels: in triage, waiting for customer response
