### ISSUE TITLE
Make  ExpansionPanelList's  expansion icon customizable

### ISSUE THREAD

**Issue by welstone** [flutter/flutter#32802] opened 2019-05-16 09:17 UTC
## Use case

I want to change the right-top icon to another one,  but there is no such option for ExpansionPanelList; 
Actually, ExpansionPanelList hardcode this icon to ExpandIcon instead;

<img width="380" alt="9A987ECC-51A6-40F8-851A-780EFED7F258" src="https://user-images.githubusercontent.com/17942332/57842485-3ae59100-77ff-11e9-8528-635d77c3adb1.png">

## Proposal
I want to add an option for ExpansionPanelList: expansionIndicator, which can be customiszed by users to change it to another one if needed;
Is that OK?

**Comment by HansMuller** [comment] 2019-05-16 15:26
That sounds like a reasonable change, yes.

**Comment by shihaohong** [comment] 2020-03-02 19:21
I'm un-assigning myself since I have other higher priority work to do. Please feel free to continue work on this if there is a need, my [closed PR](https://github.com/flutter/flutter/pull/35416) has some existing progress if anybody is interested!

**Comment by AyushBherwani1998** [comment] 2020-07-17 16:55
@shihaohong I would like to pick it up.

**Comment by shihaohong** [comment] 2020-07-22 16:58
@AyushBherwani1998 See https://github.com/flutter/flutter/pull/35416, as it was the closest PR to get to completion. The toughest issue to solve is the issue of animating icons and how we want to handle those. See https://github.com/flutter/flutter/pull/35416#discussion_r301331751 for some context.

I think another tricky issue is that there is a weirdness with what true/false means when passed to `expansionCallback`: https://github.com/flutter/flutter/pull/35416/files#diff-8da44ccd11c3493f86a5e4662d74e9c8R581, but maybe we can make that a separate PR.

**Comment by AyushBherwani1998** [comment] 2020-07-23 13:39
@shihaohong I did check the PR. I understand the difficulty of animating icons. I also felt the solution was like an open canvas for the developers to do what they want to customize the indicator icon. At the same time, it can be confusing to the developers without the proper documentation on how to use the API.

**Comment by shihaohong** [comment] 2020-07-23 23:39
I believe that we still want to take the same approach. If there's any way to minimize API difficulty/confusion, we should try to get it there

**Comment by AyushBherwani1998** [comment] 2020-07-24 14:31
I was thinking to merge your branch into my branch to start and revert the change for `expansionCallback` but you have deleted your branch. I'll start by recreating your work and submit a PR so we can start from where it was left last time.

**Comment by shihaohong** [comment] 2020-07-27 01:25
Sounds good, thanks for working on this! I'll assign the issue to you for now

**Comment by AyushBherwani1998** [comment] 2020-07-28 11:22
Hey, @shihaohong I have recreated your work form previous PR. I have not removed [WIP] cause I was not able to analyze the interactive samples. Running the `analyze-sample-code.dart` was taking forever. How much time does it usually take to analyze the samples?  I waited for around 15-20 mins .

**Comment by HansMuller** [comment] 2020-08-05 00:37
To give the developer as much flexibility as possible for updating this animated icon (widget), I would think we'd want a builder property with a value of `Widget Function(BuildContext context, Animation<double> animation)`. Where the animation's value was 0 when the panel was closed and 1 when open. Hopefully we could document a simple example of this property in terms of an Icon and RotationTransition.

**Comment by AyushBherwani1998** [comment] 2020-08-06 07:11
So, as far as I understand, we should have two builder properties, one for those who have their own gesture handlers, and one for the `AnimatedIcon` with an internal gesture detector, which returns animation progress, so developers don't have to go through creating their own `AnimationController`?

**Comment by AyushBherwani1998** [comment] 2020-08-20 12:10
cc:\ @shihaohong @HansMuller

**Comment by ilkercat** [comment] 2020-10-17 13:23
When will come this feature? Waiting for that one.

**Comment by henriquetroiano** [comment] 2022-05-30 13:57
Any update on this?

**Comment by Hixie** [comment] 2023-07-31 01:43
Duplicate of #108973.

**Closed by Hixie** 2023-07-31 01:43 UTC
Labels: c: new feature, framework, f: material design, c: proposal, P3, team-design, multiteam-retriage-candidate, :hourglass_flowing_sand:
