### ISSUE TITLE
[tool_crash] SocketException: Write failed, OS Error: Broken pipe, errno = 32

### ISSUE THREAD

**Issue by Barack09** [flutter/flutter#143068] opened 2024-02-07 11:50 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Write failed, OS Error: Broken pipe, errno = 32
```
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1189:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1915:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2355:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2103:26)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2077:11)
#5      _rootRunUnary (dart:async/zone.dart:1406:47)
#6      _CustomZone.runUnary (dart:async/zone.dar

**Comment by dam-ease** [comment] 2024-02-07 12:30
Hello @Barack09.
There is a similar issue to this currently open https://github.com/flutter/flutter/issues/100584.
Closing this as a duplicate of the existing issue.

**Closed by dam-ease** 2024-02-07 12:30 UTC
Labels: in triage
