### ISSUE TITLE
(google_maps_flutter) BitmapDescriptor.bytes for map markers is not working as expected

### ISSUE THREAD

**Issue by arabnology** [flutter/flutter#149626] opened 2024-06-03 23:19 UTC
### Steps to reproduce

Since `BitmapDescriptor.fromBytes()` is deprecated in Flutter 3.22.1, I converted to using `BitmapDescriptor.bytes()`. Unfortunately, it is not working as expected, it shows the default map marker instead.

I'm using an asset image for map markers.
I'm converting this asset image into a `Uint8List`, then assigning it to a map marker.

### Expected results

Show the exact image as a map marker after it is successfully converted into a `Uint8List` and assigned to the map marker.

### Actual results

The default marker is shown instead of the custom map marker.

### Code sample

<details open><summary>Code sample</summary>

```dart
//Asset image to Uint8List.
static Future<Uint8List?> getUint8ListFromImage({
    required final String imagePath,
    final int? width,
    final int? height,
    final VoidCallback? onStart,
    final Function(Uint8List uint8List)? onSuccess,
    final Function(String errorTextKey)? onError,
    final VoidCallback? onComplete,
  }) async {
    try {
      onStart?.call();
      final ByteData byteDataFromImage = await rootBundle.load(imagePath).timeout(const Duration(seconds: 8));
      final ui.Codec codec = await ui
          .instantiateImageCodec(byteDataFromImage.buffer.asUint8List(), targetHeight: height, targetWidth: width)
          .timeout(const Duration(seconds: 8));
      final ui.FrameInfo frameInfo = await codec.getNextFrame().timeout(const Duration(seconds: 8));
      final ByteData? byteDataFromFrame =
          await frameInfo.image.toByteData(format: ui.ImageByteFormat.png).timeout(const Duration(seconds: 8));
      if (byteDataFromFrame != null) {
        final Uint8List uint8List = byteDataFromFrame.buffer.asUint8List();
        onSuccess?.call(uint8List);
        return uint8List;
      } else {
        onError?.call("error_try_again");
      }
    } on TimeoutException {
      onError?.call("connection_timeout");
    } catch (_) {
      onError?.call("error_try_again");
    } finally {
      onComplete?.call();
    }
    return null;
  }

     //Assign it to map marker.
      _driverMarkerIcon ??= await Helpers.getUint8ListFromImage(
        width: 64,
        imagePath: "assets/images/v2/map_car.png",
      );
      late final BitmapDescriptor markerIcon;
      if (_driverMarkerIcon != null) {
        markerIcon = BitmapDescriptor.bytes(_driverMarkerIcon!); //<--- Successfully assigned.
      } else {
        markerIcon = BitmapDescriptor.defaultMarkerWithHue(BitmapDescriptor.hueBlue);
      }
      //...
      Marker(
            markerId: MarkerId(driver.userId),
            position: LatLng(
              driver.lat,
              driver.lng,
            ),
            icon: markerIcon,
            zIndex: 1.0,
            rotation: markerRotation,
            anchor: const Offset(0.5, 0.1),
            infoWindow: InfoWindow(
              title: Helpers.translateNumbers(
                text: TripHelpers.distanceAsString(
                  input: driverDistance,
                ),
              ),
            ),
            consumeTapEvents: false,
          ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1648" alt="sh_frombytes" src="https://github.com/flutter/flutter/assets/88229381/7295b051-6fda-4c97-a328-d9966d7de4cf">
<img width="1627" alt="sh_bytes" src="https://github.com/flutter/flutter/assets/88229381/52d42a32-8945-433e-b18c-c60761524b24">

</details>

### Logs

<details open><summary>Logs</summary>

```console
No logs.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale
    en-SA)
    • Flutter version 3.22.1 on channel stable at /Users/mimac/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (12 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mimac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPad (mobile)      • 00008020-000D70D622BA402E            • ios
      • iOS 17.5.1 21F90
    • iPhone 14 (mobile) • 78D844D2-4CB5-4AF0-B165-24EC86D854F6 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 14.5 23F79 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 125.0.6422.113

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2024-06-03 23:32
This is a feature that has only been partially rolled out, and there was a mistake in the rollout order. The deprecation has been reverted, and for now you will need to continue to use `.fromBytes`.

Closing as a duplicate of https://github.com/flutter/flutter/issues/149183

**Closed by stuartmorgan** 2024-06-03 23:32 UTC
