### ISSUE TITLE
[image_picker] FEATURE: Add function for getting photo and video from one place

### ISSUE THREAD

**Issue by AshotKhachatryan1995** [flutter/flutter#121860] opened 2023-03-03 07:48 UTC
At this time I want to open gallery photo and video together, but now only supports .pickImage() or .pickVideo()

**Comment by darshankawar** [comment] 2023-03-03 09:20
Closing as duplicate of https://github.com/flutter/flutter/issues/89159
Please do leave a thumbs up on the original author's post so we can track and prioritize the issue base on severity and demand. Thanks!

**Closed by darshankawar** 2023-03-03 09:20 UTC
Labels: in triage
