### ISSUE TITLE
Exception: Failed to access the internal image decoder registry on this isolate.

### ISSUE THREAD

**Issue by pmaritz16** [flutter/flutter#115030] opened 2022-11-09 23:10 UTC
I encountered the following error trying use the following packages in an Isolate:

```
import 'dart:ui' as UI;
import 'package:image/image.dart' as DI;
```

```
[ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
Exception: Failed to access the internal image decoder registry on this isolate. Please file a bug on https://github.com/flutter/flutter/issues.
#0      _futurize (dart:ui/painting.dart:5886:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5741:12)
#2      instantiateImageCodecFromBuffer (dart:ui/painting.dart:2092:60)
#3      instantiateImageCodec (dart:ui/painting.dart:2050:10)
<asynchronous suspension>
#4      _decodeImageFromListAsync (dart:ui/painting.dart:2119:23)
<asynchronous suspension>
```

**Comment by danagbemava-nc** [comment] 2022-11-10 07:42
Hi @pmaritz16,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by pmaritz16** [comment] 2022-11-10 15:49
See attached for requested files and a link to a minimal bug repro case:

https://drive.google.com/drive/folders/1o2U_QjjEFNfCHFmDLjf6mhcVE3jhl6g0?usp=share_link

 

Thanks, Paul Maritz

**Comment by pmaritz16** [comment] 2022-11-11 02:33
FYI... it should be obvious from the repro code but to reproduce the bug on Windows using the repro code as-is, link below, you need to provision 3 JPG files in directory c:\temp and call them i00.jpg, i01.jpg, i02.jpg. Any JPG files will do.

 

From: ***@***.*** ***@***.***> 
Sent: Thursday, November 10, 2022 7:50 AM
To: 'flutter/flutter' ***@***.***>; 'flutter/flutter' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [flutter/flutter] Exception: Failed to access the internal image decoder registry on this isolate. Please file a bug (Issue #115030)

 

See attached for requested files and a link to a minimal bug repro case:

https://drive.google.com/drive/folders/1o2U_QjjEFNfCHFmDLjf6mhcVE3jhl6g0?usp=share_link

 

Thanks, Paul Maritz

**Comment by danagbemava-nc** [comment] 2022-11-11 09:31
Hi @pmaritz16, can you reduce your code sample to only the parts required to reproduce the issue? Ideally a self-contained single main.dart file that contains the image(s) required as well would be best. 

Please also do not reply through email as it clutters the thread since the email messages cannot be formatted. 

Thank you

**Comment by pmaritz16** [comment] 2022-11-11 17:29
[bug_repro.zip](https://github.com/flutter/flutter/files/9992300/bug_repro.zip)
I have attached a ZIP containing the 'lib' directory (contains only one file 'main.dart'), pubspec.yaml, and the same JPG file (image.jpg) which must be place in same directory as 'lib'. Should be all that is needed to repro. Tried to make it simple as possible.

**Comment by pmaritz16** [comment] 2022-11-11 18:06
[bug_repro.zip](https://github.com/flutter/flutter/files/9992482/bug_repro.zip)
Apologies, just removed unnecessary font assets from pubspec.yaml. Otherwise as above.

**Comment by danagbemava-nc** [comment] 2022-11-14 06:56
Issue is reproducible using the sample provided in https://github.com/flutter/flutter/issues/115030#issuecomment-1312011064

A runnable project has been attached below. 

The code was tested on `windows` but this should likely reproduce on other platforms as well. 

Labeling for further investigation

```
[ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
Exception: Failed to access the internal image decoder registry on this isolate. Please file a bug on https://github.com/flutter/flutter/issues.
#0      _futurize (dart:ui/painting.dart:6365:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6222:12)
#2      instantiateImageCodecFromBuffer (dart:ui/painting.dart:2150:60)
#3      instantiateImageCodec (dart:ui/painting.dart:2108:10)
<asynchronous suspension>
#4      _decodeImageFromListAsync (dart:ui/painting.dart:2176:23)
<asynchronous suspension>
```

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.19043.2130], locale en-GH)
    • Flutter version 3.3.7 on channel stable at c:\src\sdks\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (12 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.73.0)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.2130]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 107.0.1418.35

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.6.0-3.0.pre.1, on Microsoft Windows [Version 10.0.19043.2130], locale en-GH)
    • Flutter version 3.6.0-3.0.pre.1 on channel master at c:\src\sdks\master\flutter
    ! Warning: `flutter` on your path resolves to C:\src\sdks\stable\flutter\bin\flutter, which is not inside your      
      current Flutter SDK checkout at c:\src\sdks\master\flutter. Consider adding c:\src\sdks\master\flutter\bin to the 
      front of your path.
    ! Warning: `dart` on your path resolves to C:\src\sdks\stable\flutter\bin\dart, which is not inside your current    
      Flutter SDK checkout at c:\src\sdks\master\flutter. Consider adding c:\src\sdks\master\flutter\bin to the front of      your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cb224d10e3 (4 hours ago), 2022-11-13 21:57:38 -0500
    • Engine revision b7567b92c7
    • Dart version 2.19.0 (build 2.19.0-394.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.73.0)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.2130]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 107.0.1418.35

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

[image_isolate.zip](https://github.com/flutter/flutter/files/10000328/image_isolate.zip)

**Comment by zanderso** [comment] 2022-11-14 19:07
`dart:ui` is not supported or expected to work outside of the main isolate, so I'll go ahead and close this. You might file a new issue that describes your use case, though, so we can get more ideas for why it would be useful.

**Closed by zanderso** 2022-11-14 19:07 UTC
Labels: severe: crash, engine, a: images, has reproducible steps, found in release: 3.3, found in release: 3.6
