### ISSUE TITLE
Navigating Custom Pages error in Framework.dart file while working with BottomNavigationBar

### ISSUE THREAD

**Issue by MohammadAlib6233** [flutter/flutter#129195] opened 2023-06-20 17:48 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am new to Flutter. I am facing a problem while navigating to other custom pages. The code is working properly when I use "Text" but when I use "Homepage(), Explanation()" or custom pages like this, it shows me error in the Framework.dart "Exception has occurred. _AssertionError"

### Expected results

I want the custom pages Homepage(), Explanation(), GetStarted(), Profile() to work fine like as Text('Home'), Text('Explanation'), Text('Get Started'), Text('Profile') are working. This code in attached image is working fine
![Screenshot 2023-06-20 224404](https://github.com/flutter/flutter/assets/80781392/ba4c1cb9-6a45-46d2-addd-c5029edfcb2a)

### Actual results

[
![Screenshot 2023-06-20 223309](https://github.com/flutter/flutter/assets/80781392/741e95de-0606-4886-8588-f3dcc113084e)
](url)

### Code sample

<details><summary>Code sample</summary>

```dart
[ 
import 'package:flutter/material.dart';
import 'package:nexgen_app/explanation.dart';
import 'package:nexgen_app/get_started.dart';
import 'package:nexgen_app/profile.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int selectedItem = 0;

  final _widgetOptions = [
    HomePage(),
    Explanation(),
    GetStarted(),
    Profile(),
  ];

  void _onItemTap(int index) {
    setState(() {
      selectedItem = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Bottom Nav Bar'),
        centerTitle: true,
        backgroundColor: Colors.red,
      ),
      body: Center(child: _widgetOptions.elementAt(selectedItem)),
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        backgroundColor: Colors.red,
        selectedItemColor: Colors.white,
        unselectedItemColor: Colors.red.shade200,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.list),
            label: 'Explanation',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.details),
            label: 'Get Started',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: 'Profile',
          ),
        ],
        currentIndex: selectedItem,
        onTap: _onItemTap,
      ),
    );
  }
}
]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste 
![Screenshot 2023-06-20 223246](https://github.com/flutter/flutter/assets/80781392/d3951fc0-48fa-4ca9-869a-583f48072a4f)
your output here]
```

</details>

**Comment by darshankawar** [comment] 2023-06-21 07:38
@MohammadAlib6233 
In order to properly address the issue, please provide complete but minimal reproducible code sample that we can directly run. Also, provide the complete error log if you can.

Note: Please don't paste screenshots of the code or error as it is not helpful to use. Always provide these details in properly formatted text.

**Comment by MohammadAlib6233** [comment] 2023-06-21 13:21
The problem I am facing is that the custom pages  Homepage(), Explanation(), GetStarted(), Profile() are not working and throwing an error on device due to which the screen turn all white, also redirecting me to Framework.dart with error " Exception has occurred. _AssertionError " on line number 4809 at " assert(owner!._debugCurrentBuildTarget == this); ". But if I use " Text('Home'), Text('Explanation'), Text('Get Started'), Text('Profile') " the code is working perfectly and showing excellent result of BottomNavigationBar.

The code which is working excellent is:

import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int selectedItem = 0;

  final _widgetOptions = [
    Text('Home'),
    Text('Explanation'),
    Text('Get Started'),
    Text('Profile'),
    
  ];

  void _onItemTap(int index) {
    setState(() {
      selectedItem = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Bottom Nav Bar'),
        centerTitle: true,
        backgroundColor: Colors.red,
      ),
      body: Center(child: _widgetOptions.elementAt(selectedItem)),
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        backgroundColor: Colors.red,
        selectedItemColor: Colors.white,
        unselectedItemColor: Colors.red.shade200,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.list),
            label: 'Explanation',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.details),
            label: 'Get Started',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: 'Profile',
          ),
        ],
        currentIndex: selectedItem,
        onTap: _onItemTap,
      ),
    );
  }
}


Whereas, the code which is creating an issue is:

import 'package:flutter/material.dart';
import 'package:nexgen_app/explanation.dart';
import 'package:nexgen_app/get_started.dart';
import 'package:nexgen_app/profile.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int selectedItem = 0;

  final _widgetOptions = [
    HomePage(),
    Explanation(),
    GetStarted(),
    Profile(),
  ];

  void _onItemTap(int index) {
    setState(() {
      selectedItem = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Bottom Nav Bar'),
        centerTitle: true,
        backgroundColor: Colors.red,
      ),
      body: Center(child: _widgetOptions.elementAt(selectedItem)),
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        backgroundColor: Colors.red,
        selectedItemColor: Colors.white,
        unselectedItemColor: Colors.red.shade200,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.list),
            label: 'Explanation',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.details),
            label: 'Get Started',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: 'Profile',
          ),
        ],
        currentIndex: selectedItem,
        onTap: _onItemTap,
      ),
    );
  }
}

**Comment by darshankawar** [comment] 2023-06-22 05:28
> final _widgetOptions = [
>     Text('Home'),
>     Text('Explanation'),
>     Text('Get Started'),
>     Text('Profile'),
>     
>   ];

@MohammadAlib6233 Here, you are passing list / array of widgets `Text`, but in other part, you are trying to pass a class which could be causing the issue you are reporting.

This looks like a code implementation issue rather than bug in framework.

I suggest you to ask this question on support channels like StackOverflow or you'll need to revisit your code implementation. 
I'll close it for now. If you disagree or think there's a genuine bug in framework, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-06-22 05:28 UTC
Labels: in triage
