### ISSUE TITLE
when i use extra to navigate in flutter go router and come back fluttertoast does not work

### ISSUE THREAD

**Issue by mahdiqdi** [flutter/flutter#124439] opened 2023-04-08 08:02 UTC
flutter doctor
[✓] Flutter (Channel stable, 3.7.5, on macOS 12.6.1 21G217 darwin-x64, locale en-TR)
    • Flutter version 3.7.5 on channel stable at /Users/mac/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (6 weeks ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1
                                                                                                                                                                                                    Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.0)
    • VS Code at /Users/mac/iCloud Drive (Archive)/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • 21061119AG (mobile) • adb-105f2bfe0506-pcQwEZ._adb-tls-connect._tcp. • android-arm64  • Android 12 (API 31)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

i use 
  fluttertoast: ^8.2.1
  go_router: ^6.5.5

the problem is when i navigate to new screen with pushNamed like below and return back with Navigator.of(context).pop() my flutterToast does not work and says overlay is null but when i use params for passing data to new screen this problem does not happen
  context.pushNamed('test', extra: {'isActive': state.isActive});

i need to pass extra for sending boolean or other types not only string
what is the problem of extra and how to solve this issue please help me

**Comment by darshankawar** [comment] 2023-04-10 07:17
@mahdiqdi 
Looks like your case is similar to https://github.com/flutter/flutter/issues/105294, so follow-up in it for further updates.
Closing this as a duplicate.

**Comment by mahdiqdi** [comment] 2023-04-10 08:23
@darshankawar there is no similarity between my issue and #105294.plz read my issue.this problem is really teasing me

**Comment by darshankawar** [comment] 2023-04-11 05:19
@mahdiqdi 
Since fluttertoast is a third party package, does the same behavior occur using snackbar ? If so, please provide complete minimal reproducible code sample that shows current behavior and expected result you are looking for.

**Comment by mahdiqdi** [comment] 2023-04-11 09:06
no.its okay with flutter snackbar.but fluttertoast shows me error

**Comment by iapicca** [comment] 2023-04-11 12:32
> no.its okay with flutter snackbar.but fluttertoast shows me error

@mahdiqdi 
than it's clearly a [fluttertoast](https://pub.dev/packages/fluttertoast) issue and should be open [here](https://github.com/ponnamkarthik/FlutterToast/issues)

**Comment by darshankawar** [comment] 2023-04-11 12:49
As mentioned above, this seems to be a third party plugin issue and not with go_router. 
Closing from here.

**Closed by darshankawar** 2023-04-11 12:49 UTC
Labels: in triage
