### ISSUE TITLE
[Flutter Web] Document how to use material icons in faq and/or migration guide

### ISSUE THREAD

**Issue by samrat19** [flutter/flutter#33231] opened 2019-05-22 23:52 UTC
when i am using  in flutter web
drawer : Drawer()

the hamburger icon is not coming. but it is available in flutter mobile

**Comment by rostopira** [comment] 2019-05-23 14:08
Follow this guide to add custom font https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md#webassetsfontmanifestjson-optional

Like this
```json
  {
    "family": "MaterialIcons",
    "fonts": [
      {
        "asset": "MaterialIcons-Regular.ttf"
      }
    ]
  }
```

**Comment by iampawan** [comment] 2019-05-23 17:11
or you can directly use the below code in FontManifest.json file resides in web/assets folder

`[
  {
    "family": "MaterialIcons",
    "fonts": [
      {
        "asset": "https://fonts.gstatic.com/s/materialicons/v42/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2"
      }
    ]
  }
]`

**Comment by yjbanov** [comment] 2019-06-06 17:38
Closing as duplicate of https://github.com/flutter/flutter/issues/32245

**Closed by yjbanov** 2019-06-06 17:38 UTC
Labels: ☸ platform-web

**Comment by timtraversy** [comment] 2019-09-14 15:40
If anyone comes across this, _don't_ use https://github.com/google/material-design-icons/tree/master/iconfont. That repo hasn't been updated in 4 years and is missing many of the icons in the current Material spec.
