### ISSUE TITLE
[web][a11y][Android] TalkBack adding "double-tap to activate" to all elements

### ISSUE THREAD

**Issue by volodymyrparanytsia** [flutter/flutter#148954] opened 2024-05-23 15:14 UTC
### Steps to reproduce

1. Use Android phone(in my case Pixel 3a, Android 10)
2. Enable TalkBack
3. Open the website(code provided below) in browser
4. Tap on elements like text widget or text span

### Expected results

TalkBack should read the content of the Text/TextSpan and other widgets and if there is no additional actions related to the specific widget it should not add "double-tap to activate"

### Actual results

"double-tap to activate" always added to the end of the content TalkBack is reading

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const TextWidgetA11yTest());
}

class TextWidgetA11yTest extends StatelessWidget {
  const TextWidgetA11yTest({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Column(
          children: [
            Semantics(
              readOnly: true,
              child: Text('Read Only Text'),
            ),
            Text('I am test'),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4.1 23E224 darwin-x64, locale en-GB)
    • Flutter version 3.19.4 on channel stable at /Users/xxxxx/program_files/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (9 weeks ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xxxxx/Library/Android/sdk
    • Platform android-34, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.89.1)
    • VS Code at /Users/xxxxx/program_files/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.4.1 23E224 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.41

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2024-05-24 07:25
@volodymyrparanytsia 
This has been fixed already as part of https://github.com/flutter/flutter/issues/144364 which should be available in latest stable version, so you'll need to upgrade and re-run your scenario to see it work as expected.

Closing this, as it has been already fixed and is a duplicate of linked issue.

**Closed by darshankawar** 2024-05-24 07:25 UTC
Labels: in triage

**Comment by volodymyrparanytsia** [comment] 2024-05-24 08:47
@darshankawar amazing news. Thank you.
