### ISSUE TITLE
Autofill feature causing weird UI resizing effects on iOS

### ISSUE THREAD

**Issue by thassio-vinicius** [flutter/flutter#127618] opened 2023-05-25 20:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just write a simple code with forms and make sure it has any UI elements close to the middle and bottom of the screen to see the resizing more clearly, wrap those forms in an `AutofillGroup` widget and set up the `autofillHints` parameters. After that, any time the autofill pop up gets triggered on iOS, upon closing it, the resizing of the UI elements will occur. As far as I know, this is only happening on iOS. I'm not entirely sure if this also happens in older Flutter versions, but I'm using `Flutter 3.10.0`

### Expected results

Use the Autofill feature without any unexpected behaviours affecting the UI.

### Actual results

Using the Autofill feature triggers some sort of bouncing effect.

### Code sample

<details><summary>Code sample</summary>

```dart
class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final TextEditingController _email = TextEditingController();
  final TextEditingController _password = TextEditingController();

  void _onSubmitForm(BuildContext context) {
    TextInput.finishAutofillContext();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.blue,
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(
                width: double.infinity,
                child: Text(
                  'Autofill example',
                  style: TextStyle(color: Colors.black, fontSize: 32),
                  textAlign: TextAlign.center,
                ),
              ),
              Expanded(
                child: Center(
                  child: SingleChildScrollView(
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Container(
                          width: double.infinity,
                          padding: const EdgeInsets.all(8),
                          decoration: BoxDecoration(
                            color: Colors.grey.shade100,
                            borderRadius: BorderRadius.circular(8),
                          ),
                          constraints: const BoxConstraints(
                            maxWidth: 550,
                          ),
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(8),
                            child: SingleChildScrollView(
                                child: Column(children: [
                              const SizedBox(height: 16),
                              AutofillGroup(
                                child: Column(
                                  children: [
                                    TextFormField(
                                      controller: _email,
                                      autofillHints: const [AutofillHints.email],
                                    ),
                                    const SizedBox(
                                      height: 32,
                                    ),
                                    TextFormField(
                                      controller: _password,
                                      textInputAction: TextInputAction.done,
                                      onFieldSubmitted: (_) => _onSubmitForm(context),
                                      autofillHints: const [AutofillHints.password],
                                    ),
                                    const SizedBox(height: 42),
                                    ElevatedButton(
                                      onPressed: () => _onSubmitForm(context),
                                      child: const Text('SUBMIT FORMS'),
                                    )
                                  ],
                                ),
                              ),
                            ])),
                          ),
                        )
                      ],
                    ),
                  ),
                ),
              ),
              const SizedBox(
                width: double.infinity,
                child: Text(
                  'Placeholder text',
                  style: TextStyle(
                    color: Colors.black,
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

https://github.com/flutter/flutter/assets/56059776/6fff95c3-6b0d-406a-95a6-f862d4d2ec57

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-GB)
    • Flutter version 3.10.0 on channel stable at /Users/thassio/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/thassio/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • ANDROID_HOME = /Users/thassio/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (6 available)
    • Pixel 4a (mobile)                   • 192.168.1.7:5555                     • android-arm64  • Android 13 (API 33)
    • iPhone de Thassio (mobile)          • 00008120-000928140ADB401E            • ios            • iOS 16.4.1 20E252
    • iPhone SE (3rd generation) (mobile) • 2CA2863A-FA2B-472A-A5EC-39A559A1D256 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro Max (mobile)          • 0F1D42BB-6695-4B2D-9B02-358A9F6B4F02 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 113.0.5672.126
    ! Error: Apple Watch de Thassio needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both
      devices may also need to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment] 2023-05-26 08:37
Closing as duplicate of #112281. Kindly follow up with the issue for updates.

**Closed by dam-ease** 2023-05-26 08:37 UTC
Labels: in triage
