### ISSUE TITLE
TabBar throws an error on back navigation when used together with initialRoute

### ISSUE THREAD

**Issue by vendik** [flutter/flutter#152837] opened 2024-08-04 14:14 UTC
### Steps to reproduce

1. Run the example code
2. Press the button to navigate back
3. Observe logs in the console

### Expected results

No error

### Actual results

Error, see the Logs section

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/deep',
      routes: {
        '/': (context) => RootScreen(),
        '/deep': (context) => DeepScreen(),
      },
    );
  }
}

class RootScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const DefaultTabController(
      length: 0,
      child: Scaffold(
        backgroundColor: Colors.white,
        body: TabBarView(children: []),
        bottomNavigationBar: TabBar(tabs: []),
      ),
    );
  }
}

class DeepScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      child: Text('Click to go back to RootScreen'),
      onPressed: () => Navigator.pop(context),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown while rebuilding dirty elements:
Null check operator used on a null value

The relevant error-causing widget was: 
  TabBarView TabBarView:file:///C:/Users/Admin/Projects/tab_crash/lib/main.dart:25:15
When the exception was thrown, this was the stack: 
#0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:260:53)
#1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:381:19)
#2      PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:215:30)
#3      _TabBarViewState.didChangeDependencies (package:flutter/src/material/tabs.dart:1976:24)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5647:13)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#12     _invoke (dart:ui/hooks.dart:312:13)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#14     _drawFrame (dart:ui/hooks.dart:283:31)
The element being rebuilt at the time was index 14 of 15: TabBarView
  dirty
  dependencies: [_TabControllerScope]
  state: _TabBarViewState#2d5ab
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
buildScope missed some dirty elements.


This probably indicates that the dirty list should have been resorted but was not.

The list of dirty elements at the end of the buildScope call was: 
  : ElevatedButton
    dependencies: [MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#6a39c]]
    state: _ButtonStyleState#8fa4d
  : DefaultTabController
    dependencies: [_EffectiveTickerMode]
    state: _DefaultTabControllerState#7acad(ticker inactive)
  : TabBar
    dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#6a39c], _TabControllerScope]
    state: _TabBarState#d9092
  : TabBarView
    dirty
    dependencies: [_TabControllerScope]
    state: _TabBarViewState#2d5ab
  ...
When the exception was thrown, this was the stack: 
#0      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2943:11)
#1      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2950:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:21)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#7      _invoke (dart:ui/hooks.dart:312:13)
#8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#9      _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19044.1288], locale sv-SE)
    • Flutter version 3.22.3 on channel stable at C:\Users\Admin\AppData\Local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Admin\AppData\Local\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.1288]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 127.0.6533.89
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 126.0.2592.102

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by SuicaLondon** [comment] 2024-08-04 23:13
That is because you set '/' not a default route. When you start your app, The routes will push the '/' page at first, then push the '/' deep route. When you call Navigator.pop(context), the previous page `TabBarView`'s `didChangeDependencies` will be called by `DefaultTabController.maybeOf(context)`. Then it will call the `_pageController!.jumpToPage(_currentIndex!);` which requires `viewportDimension` to calculate the position to jump.

**Comment by anyaven** [comment] 2024-08-05 07:46
I'm aware how initalRoute works, using it like this is intentional. TabBarView needs to be able to handle this scenario without throwing errors.

**Comment by vendik** [comment] 2024-08-05 07:51
Using initialRoute like this is intentional.

TabBarView needs to handle this scenario without throwing errors.

**Comment by danagbemava-nc** [comment] 2024-08-05 09:39
Reproducible using the code sample provided above. 

<details>
<summary>flutter doctor -v</summary>


```
[!] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.22.3 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```
 
```
[✓] Flutter (Channel master, 3.24.0-1.0.pre.438, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.24.0-1.0.pre.438 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cbfb222446 (32 hours ago), 2024-08-03 21:13:39 -0400
    • Engine revision 16012e2f8c
    • Dart version 3.6.0 (build 3.6.0-114.0.dev)
    • DevTools version 2.38.0
```
</details>

**Comment by SuicaLondon** [comment] 2024-08-05 09:42
@danagbemava-nc I am currently looking on that. The problem seems to be the the '/' page was created without calling applyViewportDimension.

**Comment by Piinks** [comment] 2024-08-05 22:43
This looks like a duplicate of https://github.com/flutter/flutter/issues/86222 so I am going to close it to consolidate there

**Closed by Piinks** 2024-08-05 22:43 UTC
Labels: framework, f: material design, f: routes, a: error message, has reproducible steps, team-design, found in release: 3.22, found in release: 3.24

**Comment by SuicaLondon** [comment] 2024-08-06 00:33
@Piinks I think they have the same cause and it is fine to close this issue, also I have updated my PR solve these ticket.
