### ISSUE TITLE
Empty space after Bananas in the Chips part of the Gallery demo

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#987] opened 2015-12-17 23:30 UTC
Tapping the space makes the Chip go away, which makes me think that something needs to be there?

![screenshot_20151217-152908](https://cloud.githubusercontent.com/assets/5479/11885062/103d806e-a4d3-11e5-9f53-aa1cf535ef68.png)

**Comment by Hixie** [comment] 2015-12-17 23:38
I bet this is a dupe of https://github.com/flutter/flutter/issues/915.

**Closed by Hixie** 2015-12-17 23:38 UTC
Labels: affects: material design, customer: demos

**Comment by abarth** [comment] 2015-12-18 04:50
Yeah, it's supposed to have a close button.
