### ISSUE TITLE
Flutter not rendering images after sitting idle (iOS)

### ISSUE THREAD

**Issue by aaronscherbing** [flutter/flutter#64660] opened 2020-08-26 19:07 UTC
We are experiencing an issue in the 1.20.2 stable release. Our application appears to render all views correctly when the application is initially run. However, we discovered in our TestFlight builds that once the application has been sitting idle in the background for a while, image rendering becomes very broken.

I assume this is somehow related to the Metal transition. I was able to downgrade to 1.15.4, and we didn't experience the issue there.

This is a major issue that will prevent us from releasing using the newest version of Flutter.

## Steps to Reproduce

We've seen this on at least iPhone X and 11 iOS 13.4.1 physical devices.
We've never seen the issue in a simulator.

I wish I could give you an exact path to recreating this, but it's one of those issues that takes time to reveal itself. So frustrating, I know...

There was an attempted fix with this issue: https://github.com/flutter/flutter/issues/57676

The fix above did solve text rendering issues, but images are still rendering improperly.

**Expected results:** 
Images should render, even when the application is idle for long periods of time.

**Actual results:**
Please see screenshots below.

<details>
  <summary>Logs</summary>

`flutter run --verbose`
[output.txt](https://github.com/flutter/flutter/files/5132114/output.txt)

```
Analyzing mobile...                                                     
   info • 'fileFetcher' is deprecated and shouldn't be used. Use FileService instead • lib/common/image.dart:123:9 • deprecated_member_use
   info • Name non-constant identifiers using lowerCamelCase • lib/common/web-socket.connector.dart:34:10 • non_constant_identifier_names
   info • Close instances of `dart.core.Sink` • lib/common/web-socket.connector.dart:49:19 • close_sinks
   info • Unused import: 'package:yodelay/shared/message-attachment-chat.component.dart' • lib/shared/common/post-gallery-cell.component.dart:8:8 • unused_import
   info • Unused import: 'package:yodelay/shared/post-chat.component.dart' • lib/shared/common/post-gallery-cell.component.dart:11:8 • unused_import
   info • The value of the local variable 'count' isn't used • lib/shared/common/space-cell.component.dart:83:19 • unused_local_variable
   info • 'subtitle' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is subtitle2. This feature was deprecated after v1.13.8. • lib/shared/common/theme.dart:34:31 • deprecated_member_use
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/shared/feed.component.dart:223:38 • missing_return
   info • 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. • lib/shared/intro.component.dart:80:33 • deprecated_member_use
   info • 'subtitle' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is subtitle2. This feature was deprecated after v1.13.8. • lib/shared/intro.component.dart:83:36 • deprecated_member_use

10 issues found. (ran in 7.9s)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.2 at /usr/local/flutter-default
    • Framework revision bbfbf1770c (13 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/aaronscherbing/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Aaron’s iPhone 11 (mobile) • 00008030-00040C241AFA802E            • ios • iOS 13.6.1
    • iPhone 11 (mobile)         • 2A0826B9-ABBF-4B45-AF7F-C04E3C0EC2E0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by aaronscherbing** [comment] 2020-08-26 19:09
![90925535-045dd500-e3b7-11ea-9209-58fcbaecba5f](https://user-images.githubusercontent.com/11944082/91345939-c5a89000-e7a5-11ea-82f0-f5f8146c2531.png)

**Comment by sidrao2006** [comment] 2020-08-27 06:32
Duplicate of #64558

**Comment by markusaksli-nc** [comment] 2020-08-27 07:44
Hi @aaronscherbing 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/64558.
Please follow up on that issue, I'm closing the current one as a duplicate.
Since the author of the mentioned issue has not yet responded to this:

> Does this happen if the images are in listview or rows? The layout doesn't matter?

Could you clarify this as well? I'm going to try to reproduce this, but some additional information would be useful since this is such an obscure setup. What exact widget(s) are you using to display the images in the screenshot? You can comment this information on the mentioned issue.
Could everyone else who is facing this issue please thumbs up the original one and comment there with any relevant unmentioned information.
Thank you

**Closed by markusaksli-nc** 2020-08-27 07:44 UTC
