### ISSUE TITLE
The "ensure checkout cache" step on LUCI is flaky and causes tree closures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#68328] opened 2020-10-16 19:50 UTC
An example of a failure of this kind [is here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8866259083662940240/+/steps/Ensure_checkout_cache/0/logs/execution_details/0). The specific error was the following script failing with an unknown error (`-9` return):
```
Executing command [
  '/opt/s/w/ir/cipd_bin_packages/vpython',
  '-u',
  '/opt/s/w/ir/kitchen-checkout/recipe_engine/recipe_modules/file/resources/fileutil.py',
  '--json-output',
  '/opt/s/w/ir/tmp/t/tmprxrZ52.json',
  'ensure-directory',
  '--mode',
  '0777',
  '/opt/s/w/ir/cache/builder',
]
```

**Comment by chinmaygarde** [comment] 2020-10-16 19:55
[Another instance of this](https://ci.chromium.org/p/flutter/builders/prod/Mac%20Android%20Debug%20Engine/7271) issue on the very next build.

**Comment by keyonghan** [comment] 2020-10-16 20:07
Duplicate of https://github.com/flutter/flutter/issues/68322.

**Closed by keyonghan** 2020-10-16 20:07 UTC
Labels: P0, team: flakes, team: infra
