### ISSUE TITLE
TextField maxLength not working anymore.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#70102] opened 2020-11-09 15:30 UTC
MaxLength is not working anymore. I am able to type more chars than allowed, and then when I press a space it cuts the typed text.

I very much hope this is a bug and not a "feature".

```
flutter doctor -v
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [versÃ£o 10.0.18363.1139], locale pt-BR)
    • Flutter version 1.22.3 at C:\flutter
    • Framework revision 8874f21e79 (11 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\m\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

**Comment by sidrao2006** [comment] 2020-11-09 15:37
Possible duplicate of #67898

**Comment by AlexV525** [comment] 2020-11-09 15:42
@sidrao2006 Thanks for the ping.

Yes, this is a duplicate of #67898 .

**Closed by AlexV525** 2020-11-09 15:42 UTC
