### ISSUE TITLE
Stop telling people to mess up their Podfile in firebase_messaging docs

### ISSUE THREAD

**Issue by mleonhard** [flutter/flutter#31466] opened 2019-04-23 03:02 UTC
The [firebase_messaging docs](https://pub.dartlang.org/packages/firebase_messaging) instruct the user to remove the `use_frameworks!` line from `ios/Podfile`.  This is no longer necessary and it breaks other flutter plugins, such as [`geolocator`](https://github.com/baseflowit/flutter-geolocator/issues?utf8=✓&q=is%3Aissue+use_frameworks).

I wasted an hour figuring out why all of my other modules stopped compiling after installing firebase_messaging.  The cause was the change to `Podfile`.  How about saving other engineers' time by removing the offending instruction from the docs?

**Comment by iqbalmineraltown** [comment] 2019-04-23 03:40
duplicate of https://github.com/flutter/flutter/issues/25172 ?

**Comment by mleonhard** [comment] 2019-04-23 06:17
Duplicate of #25172

**Closed** 2019-04-23 06:17 UTC
