### ISSUE TITLE
[web]: FormatException when running new Flutter web project

### ISSUE THREAD

**Issue by contrix09** [flutter/flutter#38368] opened 2019-08-12 23:47 UTC
FormatException while trying to run newly created Flutter web project in VS Code.

Debug Console:
```
[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 352ms
[INFO]
[INFO] Deleted previous snapshot due to core package update
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 13.6s
[INFO]
[INFO] Starting daemon...
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 294ms
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 294ms
[INFO]
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.1s
[INFO]
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 2ms
[INFO]
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving DevTools at http://127.0.0.1:57653
[INFO] Serving `web` on http://127.0.0.1:57645
[INFO] About to build [web]...
[INFO] Running build...
[INFO] Running build completed, took 850ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 444ms
[INFO] Succeeded after 1.3s with 0 outputs (0 actions)
[INFO] ------------------------------------------------------------------------
Unhandled exception:
FormatException: Unexpected character (at character 1)
Not Found
^
[38;5;244m#0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1392:5)[39;49m
[38;5;244m#1      _ChunkedJsonParser.parseNumber  (dart:convert-patch/convert_patch.dart:1259:9)[39;49m
[38;5;244m#2      _ChunkedJsonParser.parse  (dart:convert-patch/convert_patch.dart:924:22)[39;49m
[38;5;244m#3      _parseJson  (dart:convert-patch/convert_patch.dart:29:10)[39;49m
[38;5;244m#4      JsonDecoder.convert  (dart:convert/json.dart:493:36)[39;49m
[38;5;244m#5      JsonCodec.decode  (dart:convert/json.dart:151:41)[39;49m
[38;5;244m#6      jsonDecode  (dart:convert/json.dart:94:10)[39;49m
[38;5;248m#7      parse[39;49m
[38;5;248m#8      Sources.scriptParsed  (package:dwds/src/debugging/sources.dart:55:19)[39;49m
<asynchronous suspension>
[38;5;244m#9      _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)[39;49m
[38;5;244m#10     CastStreamSubscription._onData  (dart:_internal/async_cast.dart:81:11)[39;49m
[38;5;244m#11     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)[39;49m
[38;5;244m#12     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)[39;49m
[38;5;244m#13     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:263:7)[39;49m
[38;5;244m#14     _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:68:11)[39;49m
[38;5;244m#15     _EventSinkWrapper.add  (dart:async/stream_transformers.dart:15:11)[39;49m
[38;5;248m#16     WipDomain.eventStream.<anonymous closure>.<anonymous closure>  (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:301:26)[39;49m
[38;5;244m#17     _HandlerEventSink.add  (dart:async/stream_transformers.dart:228:7)[39;49m
[38;5;244m#18     _SinkTransformerStreamSubscription._handleData  (dart:async/stream_transformers.dart:120:24)[39;49m
[38;5;244m#19     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)[39;49m
[38;5;244m#20     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)[39;49m
[38;5;244m#21     _DelayedData.perform  (dart:async/stream_impl.dart:591:14)[39;49m
[38;5;244m#22     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:707:11)[39;49m
[38;5;244m#23     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:667:7)[39;49m
[38;5;244m#24     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)[39;49m
[38;5;244m#25     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)[39;49m
[38;5;244m#26     _runPendingImmediateCallback  (dart:isolate-patch/isolate_patch.dart:116:13)[39;49m
[38;5;244m#27     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:173:5)[39;49m

Exited (255)
```

Flutter Doctor:
```
[√] Flutter (Channel master, v1.8.5-pre.130, on Microsoft Windows [Version 10.0.18362.239], locale en-PH)
    • Flutter version 1.8.5-pre.130 at C:\Users\CADN\.flutter\sdk
    • Framework revision ca5411e3aa (81 minutes ago), 2019-08-12 15:21:28 -0700
    • Engine revision ff49ca1c6e
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 f29f41f1a5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\CADN\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\CADN\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.1.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.1.29020.237

[!] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.36.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18362.239]

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment] 2019-08-13 00:48
duplicate of https://github.com/flutter/flutter/issues/37584

**Closed by jonahwilliams** 2019-08-13 00:48 UTC
