### ISSUE TITLE
Unable to compile after I upgrade to Flutter 1.7.8+hotfix.3

### ISSUE THREAD

**Issue by jacksun0124** [flutter/flutter#35883] opened 2019-07-10 15:42 UTC
I got several error messages after I upgrade my Flutter version to 1.7.8+hotfix.3.

Here is the message:

```
file:///Users/shijiesun/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:75:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/shijiesun/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///Users/shijiesun/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:168:65: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/shijiesun/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: '$runtimeType failed to load ${instructions.uri}',
                                                                ^
Compiler failed on /Users/shijiesun/flutterApp/tiantianapp/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/shijiesun/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 665

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugArm64'.
> Process 'command '/Users/shijiesun/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

Here is my Flutter Doctor info:

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CA)
    • Flutter version 1.7.8+hotfix.3 at /Users/shijiesun/flutter
    • Framework revision b712a172f9 (19 hours ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shijiesun/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • SM N920W8 • 07157df70a968e29                         • android-arm64 • Android 7.0 (API 24)
    • iPhone    • 2bcd6a14db3a0eece9c6c35443716c3827c98570 • ios           • iOS 12.3.1
 
```

I am not sure what went wrong. Please give me some advice or a word round. Thanks

Mainly. I am not sure flutter_image-1.0.0 is a something inside Flutter core or it is a package I include in the pubspec.yaml file.

**Comment by tb2761** [comment] 2019-07-10 18:19
The package flutter_image isn't compatible with the new Flutter Version. They change the something on calling FlutterError i guess. 
You have 2 options, first file an issues on the flutter_image repo on github and second open the flutter_image package and follow the error messages which hopefully appear.

**Comment by tb2761** [comment] 2019-07-10 18:21
I looked at the package and they provide an fix for it. Update to Version 2.0.0. Should fix your problems

**Comment by MsXam** [comment] 2019-07-10 18:49
I also have an issue now upgrading to 1.7.8. Previously I was on 1.54 Hotfix 3 which worked seamlessly. Can no longer build on iOS , 

1. Have done an exhaustive clean including 
removing Pods, .lock, .packages, flutter_plugins, .pub_cache, DerivedData
2. Have repaired pub cache
3. Have done a Pod install
4. Have done a packages get etc

Lots of warnings and errors such as :

**When Device Attached** 

> Xcode build done.                                            5.0s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     2019-07-10 19:43:07.979 xcodebuild[26220:171795]  DTDeviceKit: deviceType from 00008006-0004E88822E2002E was NULL
>     2019-07-10 19:43:07.979 xcodebuild[26220:171795]  DTDeviceKit: deviceType from 00008006-0004E88822E2002E was NULL
>     2019-07-10 19:43:07.979 xcodebuild[26220:171795]  iPhoneSupport: 📱<DVTiOSDevice (0x7f8fe70f81b0), lasz’s iPhone, iPhone, 12.3.1 (16F203), 88a18410346ac8a86bd9cb1f76ef1350e39ece81> unable to mount DeveloperDiskImage (Error Domain=com.apple.dtdevicekit Code=601 "Could not find platform" UserInfo={NSLocalizedDescription=Could not find platform})
>     2019-07-10 19:43:08.107 xcodebuild[26220:171787] [MT] DTDeviceKit: deviceType from 00008006-0004E88822E2002E was NULL
>     2019-07-10 19:43:08.113 xcodebuild[26220:171787] [MT] DTDeviceKit: deviceType from 00008006-0004E88822E2002E was NULL
>     2019-07-10 19:43:08.119 xcodebuild[26220:171787] [MT] DTDeviceKit: deviceType from 00008006-0004E88822E2002E was NULL
>     2019-07-10 19:43:08.711 xcodebuild[26220:171787] [MT] DTDeviceKit: deviceType from 00008006-0004E88822E2002E was NULL
>     2019-07-10 19:43:08.717 xcodebuild[26220:171787] [MT] DTDeviceKit: deviceType from 00008006-0004E88822E2002E was NULL
>     2019-07-10 19:43:08.721 xcodebuild[26220:171787] [MT] DTDeviceKit: deviceType from 00008006-0004E88822E2002E was NULL
>     ** BUILD FAILED **
> 

**When device not attached** 

>  === BUILD TARGET connectivity OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/fuser/workspace/_projects/paoke/ios/Pods/Protobuf/objectivec/google/protobuf/Any.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Any.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Any.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Any.pbobjc.h>
    1 warning generated.
    === BUILD TARGET connectivity OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/fuser/workspace/_projects/paoke/ios/Pods/Protobuf/objectivec/google/protobuf/Api.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Api.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Api.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Api.pbobjc.h>
    /Users/fuser/workspace/_projects/paoke/ios/Pods/Protobuf/objectivec/google/protobuf/Api.pbobjc.m:18:10: warning: non-portable path to file '<protobuf/SourceContext.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/SourceContext.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/SourceContext.pbobjc.h>
    /Users/fuser/workspace/_projects/paoke/ios/Pods/Protobuf/objectivec/google/protobuf/Api.pbobjc.m:19:10: warning: non-portable path to file '<protobuf/Type.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Type.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Type.pbobjc.h>
    3 warnings generated.
    === BUILD TARGET connectivity OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/fuser/workspace/_projects/paoke/ios/Pods/Protobuf/objectivec/google/protobuf/Duration.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Duration.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Duration.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Duration.pbobjc.h>
    1 warning generated.
    === BUILD TARGET connectivity OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/fuser/workspace/_projects/paoke/ios/Pods/Protobuf/objectivec/google/protobuf/Empty.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Empty.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Empty.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Empty.pbobjc.h>

**Comment by m4kz** [comment] 2019-07-10 18:56
> 
> 
> I looked at the package and they provide an fix for it. Update to Version 2.0.0. Should fix your problems

Im having the same issue described at the top. How do I update flutter_image? 
i mean is not in my pubspec.yaml, since it is a package included with flutter it self.

**Comment by m4kz** [comment] 2019-07-10 19:01
> 
> 
> > I looked at the package and they provide an fix for it. Update to Version 2.0.0. Should fix your problems
> 
> Im having the same issue described at the top. How do I update flutter_image?
> i mean is not in my pubspec.yaml, since it is a package included with flutter it self.

nevermind, a simple packages update fixed it.

**Comment by stuartmorgan** [comment] 2019-07-10 20:42
Duplicate of #31962

**Closed by stuartmorgan** 2019-07-10 20:42 UTC

**Comment by maheshmnj** [comment] 2019-07-12 16:27
I think you should try ```flutter upgrade``` again I just did and it woks fine

**Comment by gondaimgano** [comment] 2019-07-24 17:19
Guys I am completely stuck after upgrading to the 1.7.8+hotfix.3 I have been unable to compile in iOS. I have tried downgrading back to 1.5 but the error is still there. I have tried creating a new project and just once it managed to compile to the simulator. After that its been giving me nightmares. Please please. When is this issue going to be resolved. We are dealing with tight timelines for my clients projects. I am now at an advanced stage of the project. Please I need a resolution to this. This is severe.

**Comment by ClaudineiOlSantos** [comment] 2019-07-26 02:46
```
Running Gradle task 'assembleDebug'...

Compiler message:
file:///C:/Users/claudinei/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.4.2/lib/cached_network_image.dart:199:38: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/claudinei/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/claudinei/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      oldImageStream?.removeListener(_handleImageChanged);
                                     ^
file:///C:/Users/claudinei/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.4.2/lib/cached_network_image.dart:200:32: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/claudinei/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/claudinei/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      _imageStream.addListener(_handleImageChanged);
                               ^
file:///C:/Users/claudinei/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.4.2/lib/cached_network_image.dart:210:34: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/claudinei/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/Users/claudinei/flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    _imageStream?.removeListener(_handleImageChanged);
                                 ^
file:///C:/Users/claudinei/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.4.2/lib/cached_network_image.dart:464:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/Users/claudinei/flutter/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on C:\Users\claudinei\projetos\risa_shop\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\claudinei\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 665

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugArm'.
> Process 'command 'C:\Users\claudinei\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 56s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by gondaimgano** [comment] 2019-07-26 09:41
`Automatically signing iOS for device deployment using specified development team in Xcode project: TCM8BVJ365
Running pod install...                                              1.6s
Running Xcode build...                                                  
 ├─Building Dart code...                                    20.6s
 ├─Generating dSYM file...                                   0.6s
 ├─Stripping debug symbols...                                0.1s
 ├─Assembling Flutter resources...                           3.0s
 └─Compiling, linking and signing...                        18.6s
Xcode build done.                                           44.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    While building module 'barcode_scan' imported from /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/ios/Runner/GeneratedPluginRegistrant.m:6:
    In file included from <module-includes>:1:
    In file included from /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/build/ios/Release-iphoneos/barcode_scan/barcode_scan.framework/Headers/barcode_scan-umbrella.h:15:
    /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/build/ios/Release-iphoneos/barcode_scan/barcode_scan.framework/Headers/BarcodeScanPlugin.h:12:1: warning: retain'ed block property does
    not copy the block - use copy attribute instead [-Wobjc-noncopy-retain-block-property]
    @property(nonatomic, retain) FlutterResult result;
    ^
    1 warning generated.
    1 warning generated.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    While building module 'barcode_scan' imported from /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/ios/Runner/GeneratedPluginRegistrant.m:6:
    In file included from <module-includes>:1:
    In file included from /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/build/ios/Release-iphoneos/barcode_scan/barcode_scan.framework/Headers/barcode_scan-umbrella.h:15:
    /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/build/ios/Release-iphoneos/barcode_scan/barcode_scan.framework/Headers/BarcodeScanPlugin.h:12:1: warning: retain'ed block property does
    not copy the block - use copy attribute instead [-Wobjc-noncopy-retain-block-property]
    @property(nonatomic, retain) FlutterResult result;
    ^
    1 warning generated.
    1 warning generated.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    ld: warning: ignoring file /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/ios/Flutter/App.framework/App, file was built for x86_64 which is not the architecture being linked (armv7):
    /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/ios/Flutter/App.framework/App
    ld: warning: ignoring file /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/ios/Flutter/App.framework/App, file was built for x86_64 which is not the architecture being linked (arm64):
    /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/ios/Flutter/App.framework/App
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Non-fat binary /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/App is not armv7. Running lipo -info:
    Non-fat file: /Users/gondaimgano/Documents/work/ios/squareUniversalIOS/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/App is architecture: x86_64
    Command /bin/sh failed with exit code 1

Encountered error while building for device.`
