### ISSUE TITLE
Copy and Paste controls in a text field do not appear when the value ​​of the text field is blank

### ISSUE THREAD

**Issue by rikiyanuar** [flutter/flutter#36665] opened 2019-07-22 08:32 UTC
No changes to any code. I just upgrade flutter version from Stable Channel 1.2.1 to Dev Channel 1.8.1.
I got Copy and Paste controls in a text field don't appear when text field is blank. But when I type something in text field then try to Long Press on text field Copy and Paste controls are appear.

I've tried to move to latest Stable Channel but Copy and Paste controls don't appear.

this is my flutter doctor

[✓] Flutter (Channel dev, v1.8.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.8.1 at /home/kangjuki/flutter
    • Framework revision d3eee57c0b (2 weeks ago), 2019-07-08 11:04:24 -0700
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/kangjuki/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/kangjuki/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/kangjuki/Documents/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /opt/idea-IC-182.3684.101
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Redmi 4X • 46c34d67ce40 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!

**Comment by justinmc** [comment] 2019-07-22 16:43
I think this is a duplicate of https://github.com/flutter/flutter/issues/35998

It seems like it's really affecting people, so I'll try to fix it soon.  Let me know if you think this issue is different and I can reopen.

**Closed by justinmc** 2019-07-22 16:43 UTC
Labels: f: material design, framework
