### ISSUE TITLE
`flutter_desktop_darwin_unittests` flakey on "Could not create Metal command queue."

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#127436] opened 2023-05-23 21:54 UTC
## steps to reproduce
1) `flutter/tools/gn --runtime-mode=debug --goma --no-lto --unoptimized --enable-impeller-vulkan --build-embedder-examples`
1) `out/host_debug_unopt/flutter_desktop_darwin_unittests --gtest_repeat=100`

## seen in

82c30a04d0d5a2621a3c8abd08d3e6c8dd2e0e5d

## example failures:
```
[ RUN      ] FlutterEmbedderExternalTextureUnittests.TestPopulateExternalTextureYUVA
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm(35)] Could not create Metal command queue.
Segmentation fault: 11
```

```
[ RUN      ] FlutterTextInputPluginTest.TestFirstRectForCharacterRange
2023-05-23 14:53:17.287 flutter_desktop_darwin_unittests[67505:10721731] Could not create Metal command queue.
2023-05-23 14:53:17.288 flutter_desktop_darwin_unittests[67505:10721731] Unable to create FlutterView; no MTLDevice or MTLCommandQueue available.
2023-05-23 14:53:17.307 flutter_desktop_darwin_unittests[67505:10721731] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Did not record an invocation in OCMStub/OCMExpect/OCMReject.
Possible causes are:
- The receiver is not a mock object.
- The selector conflicts with a selector implemented by OCMStubRecorder/OCMExpectationRecorder.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff807034be2 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff806b5c75c objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff807034a48 +[NSException raise:format:] + 206
	3   flutter_desktop_darwin_unittests    0x000000010438e125 +[OCMMacroState endStubMacro] + 261
	4   flutter_desktop_darwin_unittests    0x00000001010b5b10 -[FlutterInputPluginTestObjc testFirstRectForCharacterRange] + 1616
	5   flutter_desktop_darwin_unittests    0x00000001010d5033 _ZN7flutter7testing62FlutterTextInputPluginTest_TestFirstRectForCharacterRange_Test8TestBodyEv + 67
	6   flutter_desktop_darwin_unittests    0x00000001044e1be9 _ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc + 137
	7   flutter_desktop_darwin_unittests    0x00000001044b7e25 _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc + 117
	8   flutter_desktop_darwin_unittests    0x00000001044b7d51 _ZN7testing4Test3RunEv + 209
	9   flutter_desktop_darwin_unittests    0x00000001044b8ad2 _ZN7testing8TestInfo3RunEv + 290
	10  flutter_desktop_darwin_unittests    0x00000001044b9e9b _ZN7testing9TestSuite3RunEv + 331
	11  flutter_desktop_darwin_unittests    0x00000001044c6b3d _ZN7testing8internal12UnitTestImpl11RunAllTestsEv + 973
	12  flutter_desktop_darwin_unittests    0x00000001044e8399 _ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc + 137
	13  flutter_desktop_darwin_unittests    0x00000001044c66d5 _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc + 117
	14  flutter_desktop_darwin_unittests    0x00000001044c656a _ZN7testing8UnitTest3RunEv + 186
	15  flutter_desktop_darwin_unittests    0x00000001012e1433 _Z13RUN_ALL_TESTSv + 35
	16  flutter_desktop_darwin_unittests    0x00000001012e1338 main + 552
	17  dyld                                0x000000020ceb741f start + 1903
)
libc++abi: terminating due to uncaught exception of type NSException
Abort trap: 6
```

**Comment by gaaclarke** [comment] 2023-05-23 21:55
cc @cbracken

**Comment by gaaclarke** [comment] 2023-05-23 22:02
This is probably a duplicate of https://github.com/flutter/flutter/issues/104789

**Comment by cbracken** [comment] 2023-05-24 16:34
This seems likely to be a dupe of https://github.com/flutter/flutter/issues/104789.

**Closed** 2023-05-30 19:55 UTC
Labels: engine
