### ISSUE TITLE
Not able to view JS alert using this package in webview

### ISSUE THREAD

**Issue by ShiyanaSam** [flutter/flutter#137609] opened 2023-10-31 11:24 UTC
Js alerts are not displayed when using this package in IOS(not tested for android)
Following is the code :

```dart
class SetPinWebviewPage extends StatefulWidget {
  const SetPinWebviewPage({
    required this.url,
    Key? key,
  }) : super(key: key);

  final String url;
  @override
  State<StatefulWidget> createState() => _SetPinWebviewPage();
}

class _SetPinWebviewPage extends State<SetPinWebviewPage> {
  bool isLoading = true;
  WebViewController controller = WebViewController();

  @override
  void initState() {
    controller
          ..setJavaScriptMode(JavaScriptMode.unrestricted)
          ..loadRequest(Uri.parse(widget.url))
          ..setBackgroundColor(AppColors.webViewColor)

 
        ;
    super.initState();
  }

  @override
  Widget build(BuildContext context) => Unfocuser(
        child: LifecycleComponent(
          softLogOut: () {
            appRouter.pushAndPopUntil(
              const SplashRoute(),
              predicate: (Route<dynamic> route) => false,
            );
          },
          currentRouteName: SetPinWebviewRoute.name,
          child: ColoredSafeArea.darkOverlay(
            color: AppColors.webViewColor,
            child: Scaffold(
              backgroundColor: AppColors.webViewColor,
              body: Stack(
                children: [
                  WebViewWidget(controller: controller),
                  InkWell(
                    onTap: () {
                      Navigator.of(context).popUntil((route) => route.isFirst);
   
                    },
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: CloseIcon(),
                    ),

              
                  ),
                ],
              ),
            ),
          ),
        ),
      );
}
```

**Comment by dam-ease** [comment] 2023-10-31 12:27
Hi @ShiyanaSam. Thanks for filing this. Please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), usually a single `main.dart` file we can run directly
- The output of flutter doctor -v
- Reproduction steps

Thank you!

**Comment by stuartmorgan** [comment] 2023-10-31 14:47
Duplicate of https://github.com/flutter/flutter/issues/30358

**Closed by stuartmorgan** 2023-10-31 14:47 UTC
Labels: waiting for customer response, in triage
