### ISSUE TITLE
[web] IFrame with button top becomes disable 

### ISSUE THREAD

**Issue by inagornyi** [flutter/flutter#56477] opened 2020-05-06 21:10 UTC
I use flutter to develop one of my tasks for my project. I am using an iframe (IFrameElement) widget to display a video stream. But this widget has bugs - for example, when other elements, such as buttons appear on top of this widget, these components become disable for pressing, and this widget starts to be re-init, and accordingly, the blinking effect appears.

Who knows how to get around this problem?

```
import 'package:flutter/material.dart';
import 'dart:html' show IFrameElement;
import 'dart:ui' as ui;

class VideoFeed extends StatelessWidget {
  Widget _iframeWidget;
  final IFrameElement _iframeElement = IFrameElement();

  VideoFeed() {
    _iframeElement.src = 'http://0.0.0.0:8080/video_feed';
    _iframeElement.style.border = 'none';
    _iframeElement.style.position = "absolute";
    _iframeElement.allowFullscreen = false;

    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => _iframeElement,
    );

    _iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: 'iframeElement',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 576,
      width: 600,
      alignment: Alignment.center,
      color: Colors.green,
      child: _iframeWidget,
    );
  }
}
```

**Comment by TahaTesser** [comment] 2020-05-07 15:15
Hi @inagornyi 
Please check out this code sample, i noticed with a button top of the element, video controls still working on latest `dev` channel

Feel free to modify this code sample to represent the issue you're facing 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'dart:html' show IFrameElement;
import 'dart:ui' as ui;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Stack(
          children: [
            VideoFeed(),
            Positioned(
                bottom: 200,
                child: RaisedButton(onPressed: () {}, child: Text('Button')))
          ],
        ),
      ),
    );
  }
}

class VideoFeed extends StatelessWidget {
  Widget _iframeWidget;
  final IFrameElement _iframeElement = IFrameElement();

  VideoFeed() {
    _iframeElement.src =
        'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4';
    _iframeElement.style.border = 'none';
    _iframeElement.style.position = "absolute";
    _iframeElement.allowFullscreen = false;

    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => _iframeElement,
    );

    _iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: 'iframeElement',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 576,
      width: 600,
      alignment: Alignment.center,
      color: Colors.green,
      child: _iframeWidget,
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.18.0-12.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-12.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision c2b7342ca4 (21 hours ago), 2020-05-06 23:16:03 +0800
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome 81.0.4044.138

• No issues found!



``` 

</details> 




can you please provide your `flutter doctor -v` and `flutter run --verbose`? 

Thank you

Thank you

**Comment by inagornyi** [comment] 2020-05-07 16:03
Hi @TahaTesser 
Thank you for your response. I did everything as you wrote and it still didn’t work for me (
1) I changed the channel to dev;
2) run the command `flutter upgrade`;
3) `flutter doctor -v`;
4) copied your sample and placed it in my project;
4) `flutter run -d chrome`;
5) result work `https://drive.google.com/file/d/1uiZHHRiY8rtriEDaakAX_czhUGiRXIRm/view?usp=sharing`.

Help me, please!!!

**Comment by inagornyi** [comment] 2020-05-15 14:01
Hi, @TahaTesser
Is there any progress? Or how could this problem be circumvented?

**Comment by TahaTesser** [comment] 2020-09-09 15:16
<details> 
<summary>code sample</summary> 

```dart
import 'dart:html';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(child: VideoFeed()),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

class VideoFeed extends StatelessWidget {
  Widget _iframeWidget;
  final IFrameElement _iframeElement = IFrameElement();

  VideoFeed() {
    _iframeElement.src = 'http://0.0.0.0:8080/video_feed';
    _iframeElement.style.border = 'none';
    _iframeElement.style.position = "absolute";
    _iframeElement.allowFullscreen = false;

    // ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      'iframeElement',
      (int viewId) => _iframeElement,
    );

    _iframeWidget = HtmlElementView(
      key: UniqueKey(),
      viewType: 'iframeElement',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 576,
      width: 600,
      alignment: Alignment.center,
      color: Colors.green,
      child: _iframeWidget,
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.21.0-9.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 81a45ec2e5 (13 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.83

• No issues found!
```

</details>

**Comment by yjbanov** [comment] 2020-09-11 18:33
This is a duplicate of https://github.com/flutter/flutter/issues/54027

**Closed by yjbanov** 2020-09-11 18:33 UTC
Labels: dependency: dart, e: web_html, engine, found in release: 1.18, found in release: 1.21, has reproducible steps, platform-web
