### ISSUE TITLE
XCODE Build results in 0x6f697463

### ISSUE THREAD

**Issue by southernsons** [flutter/flutter#39649] opened 2019-09-01 17:15 UTC
## Steps to Reproduce
When I try to archive my Build and prepare for TestFlight Upload the build warning is as follows:

**Building AOT snapshot in release mode (ios-release)...          
Building App.framework for arm64...

Building App.framework for armv7...
Building AOT snapshot in release mode (ios-release)...             61,9s
Built to build/aot/.
warning: parsing line table prologue at offset 0x6f697463 found unsupported version 0x00
warning: line table parameters mismatch. Cannot emit.
note: while processing /Users/xxxxx/Documents/xxxxx/xxxxx/build/aot/armv7/snapshot_assembly.o
Project /Users/xxxxx/Documents/xxxxx/xxxxx built and packaged successfully.**

The Build seems the be successful but when I upload onto Testflight the following error occurs:

`ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _ptrace. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions.`

What I have done: flutter clean and I remove the entire .framework project. I have updated flutter and reinstalled the pods, always the same error.

I cannot find anything that's related to **_ptrace**.

## Logs

```
[✓] Flutter (Channel master, v1.9.8-pre.1, on Mac OS X 10.14.6 18G87, locale en-ZA)
    • Flutter version 1.9.8-pre.1 at /Users/martinspautz/flutter
    • Framework revision 9f4ab273f1 (4 days ago), 2019-08-28 20:02:08 -0700
    • Engine revision f52c0b9270
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] VS Code (version 1.21.1)
    • VS Code at /Users/xxx/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
The only issue here is that my iPhone is not connected.

**Comment by stuartmorgan** [comment] 2019-09-01 20:34
Duplicate of #37850

**Closed by stuartmorgan** 2019-09-01 20:34 UTC

**Comment by jupiterjosh** [comment] 2019-09-26 04:26
@stuartmorgan when you said this was a dup, were you saying that because of the e-mail response from that @southernsons received or were you referring to the warnings. or both?
```
warning: parsing line table prologue at offset 0x6f697463 found unsupported version 0x00
warning: line table parameters mismatch. Cannot emit.
```
Because I'm getting these warnings too even after I followed all the suggestions described in #37850.  I've been able to upload my app to TestFlght without any ITMS e-mails from apple, but  I'm concerned I have a ticking time-bomb somewhere in the app that is related to the warnings.

Any additional insight would be appreciated.

**Comment by stuartmorgan** [comment] 2019-09-26 05:09
> were you saying that because of the e-mail response from that @southernsons received or were you referring to the warnings. or both?

The former; despite the title of the issue, the primary concern seemed to be the rejection due to `_ptrace`. It's likely that the warning is unrelated given that you see the warning but not the rejection (it's common for people to only notice warnings when there's some later error, and then assume that the warning is related).

I would suggest filing a new bug about the warning; I would re-open this one, but I think the inclusion of the `_ptrace` rejection would confuse things.

**Comment by jupiterjosh** [comment] 2019-09-26 14:58
Thanks @stuartmorgan for the insight.  I downgraded flutter to the 1.7.8 hotfix4 release this morning and the warnings disappeared. If I see the warnings again when I upgrade back to the Flutter 1.9.x release (after I get a few action items off my plate) I will post a bug.

**Comment by egorges** [comment] 2019-10-18 00:04
I downgraded to 1.7.8 and then upgraded again to **v1.9.1+hotfix.4**. Still the same error, which is _**critical**_.
I currently can build apk --release and ios --debug
but can't build ios --release

**Comment by AlexBacich** [comment] 2019-10-20 17:09
Yes, critical. Can't upload to iOS as of this.

**Comment by stuartmorgan** [comment] 2019-10-20 17:21
Again, this bug has been closed as a duplicate. You want to follow the bug referenced above, not this one.
