### ISSUE TITLE
ios-deploy: Unable to locate DeviceSupport directory

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#11163] opened 2017-07-12 01:16 UTC
## Steps to Reproduce

`flutter run` in examples/flutter_gallery

## Flutter Doctor

Paste the output of running `flutter doctor` here.

[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/rmacnak/Flutter/flutter
    • Framework revision 69679be528 (6 days ago), 2017-07-05 13:01:40 -0700
    • Engine revision 8ad1576f27
    • Tools Dart version 1.25.0-dev.4.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/rmacnak/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • iPod touch • f73d01ae6367fbc7b50cad846bbc5735098c3276 • ios • iOS 10.3.2

**Comment by cbracken** [comment] 2017-07-24 05:57
Duplicate of #4326

**Closed by cbracken** 2017-07-24 05:57 UTC
Labels: ⌺‬ platform-ios
