### ISSUE TITLE
flutter_gallery__transition_perf_e2e_ios32 should be removed since it is too flaky

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#64748] opened 2020-08-27 19:28 UTC
This test (flutter_gallery__transition_perf_e2e_ios32) has failed five times since being added to the manifest (2 days ago).
This is excessively flaky. I suggest removing it until we can figure out the cause of the flakiness.

cc @liyuqian

**Comment by CareF** [comment] 2020-08-27 19:42
`flutter_gallery__transition_perf_e2e_ios32` is added since Aug. 17th and according to the record in https://datastudio.google.com/c/u/0/reporting/1o_27AedMBxv-sa_HE78BMWff7uhPglj9/page/dwwAB it failed 4 times out of 156 runs. Do you mean some other tests?

**Comment by liyuqian** [comment] 2020-08-27 19:44
`flutter_gallery__transition_perf_e2e_ios32` was an improvement (on flakiness) over its counterpart `flutter_gallery_ios32__transition_perf`:

In the same period (last 2 days),
- 5 failures for `flutter_gallery__transition_perf_e2e_ios32`
- 9 failures for `flutter_gallery_ios32__transition_perf`

This was consistent with @CareF 's [calculation][1] where e2e version has 10% flaky rate and the old version has 20% flaky rate. The remaining 10% flakiness was caused during app installation according to @CareF 's presentation (go/flutter-nonhost-slides) and e2e won't be able to help that.

Therefore, if we're going to remove a test, `flutter_gallery_ios32__transition_perf` would be a better choice than `flutter_gallery__transition_perf_e2e_ios32`. There's an ongoing discussion in https://github.com/flutter/flutter/issues/60559#issuecomment-681147504 about whether we should remove `flutter_gallery_ios32__transition_perf` now.

[1]: https://docs.google.com/document/d/1rTLxAxsshEir-B2vE6DU_MaqMMusOdCgLGEGpBYG3CM/edit#bookmark=id.uqv7pxvy90wc

**Comment by CareF** [comment] 2020-08-27 19:51
Those failed runs, the log says `Task failed: DeviceException: No connected iOS devices found.`. I think it might not be the test but the device lab.

**Comment by liyuqian** [comment] 2020-08-27 19:52
I created https://github.com/flutter/flutter/issues/64753 to hopefully solve the root cause of this flakiness.

**Comment by Hixie** [comment] 2020-08-27 20:24
I was just looking at https://flutter-dashboard.appspot.com/#/build, where I see this test as being added to the manifest in https://github.com/flutter/flutter/commit/13d1ff8c67c4da16dc5824101115d99a76594ae0, and there's been 5 failures for that test since that commit (3 yellow squares, representing 1 failure each, and 1 red square, which represents two failures).

**Comment by Hixie** [comment] 2020-08-27 20:27
And to clarify, yes, this is a more strict stance against flakiness than in the past. As we have a catastrophically bad flakiness problem right now, I'm trying to make sure we don't make things even worse as well as trying to help us make things better. If this test is a better version of an existing more-flaky test, we should definitely just remove the more flaky one, since that's a net improvement.

**Comment by jmagman** [comment] 2020-09-24 00:13
Was this was resolved with https://github.com/flutter/cocoon/pull/929?  This test hasn't flaked in a long time.

**Comment by liyuqian** [comment] 2020-09-24 02:45
Yes. The test has already been marked as nonflaky. Closing this issue.

**Closed by liyuqian** 2020-09-24 02:45 UTC
Labels: P3, a: tests, passed first triage, passed secondary triage, team, team: flakes, team: infra
