### ISSUE TITLE
firebase_ml_vision on iOS only works when in landscape

### ISSUE THREAD

**Issue by TehRaab** [flutter/flutter#59488] opened 2020-06-15 18:25 UTC
## Steps to Reproduce

When taking photo of some text, no text is recognised.  This seems to only be an issue on iOS devices.  For example:  On an iPhone 6 the text is not recognised at all in portrait, but OCR works fine in portrait.  There is also an issue with iPad mini 2 where text is either not recognised or it is mirrored/flipped!  I think the image capture from iOS changes the orientation of the saved image or exif data is messed up!  I have not seen any of these issues when testing on Android devices.

I have the podfile setup to include 'Firebase/MLVisionTextModel'.  This works fine on Android and only appears to be an issue on iOS which is now preventing me from releasing my app.

**pubspec.yaml added plugins**
`    firebase_ml_vision: ^0.9.4
  image_picker: ^0.6.7+1
  path:
  path_provider: ^1.6.7`

**main.dart**
`
    import 'dart:io';
    import 'package:firebase_ml_vision/firebase_ml_vision.dart';
    import 'package:flutter/material.dart';
    import 'package:image_picker/image_picker.dart';
    import 'package:path_provider/path_provider.dart' as syspaths;
    import 'package:path/path.dart' as path;
    
    void main() => runApp(MyApp());
    
    class MyApp extends StatefulWidget {
      @override
      _MyAppState createState() => _MyAppState();
    }
    
    class _MyAppState extends State<MyApp> {
      File _image;
      String _detectedText = '';
    
    Future<String> _takePicture() async {
        setState(() {
              _image = null;
        });
   
        final _picker = ImagePicker();
        final PickedFile image = await _picker.getImage(
            source: ImageSource.camera,
            imageQuality: 100,
        );
        
        final File imageFile = File(image.path);
        
        if (imageFile == null) {
            return null;
        }
        
        final appDir = await syspaths.getApplicationDocumentsDirectory();
        final fileName = path.basename(imageFile.path);
        
        final savedImage = await imageFile.copy('${appDir.path}/$fileName');
        return '${appDir.path}/$fileName';
    }
      
    void _cameraScanSearch() async {
        print('_cameraScanSearch()');
        _image = null;

    final imagePath = await _takePicture();
    if (imagePath == null || imagePath.isEmpty) {
      print('_cameraScanSearch() - imagePath is null');
      return;
    }

    setState(() {
      _image = File(imagePath);
    });

    try {
      var stopWatch = Stopwatch()..start();

      print('_cameraScanSearch() - Camera Scan..');
      final FirebaseVisionImage visionImage =
      FirebaseVisionImage.fromFilePath(imagePath);

      final TextRecognizer _recognizer = FirebaseVision.instance.textRecognizer();
      final VisionText readText = await _recognizer.processImage(visionImage);
      setState(() {
        _detectedText = readText.text;
      });
        
          print('_cameraScanSearch() - VisionText found -> ${readText.text}');
        
          var blocks = readText.blocks;
          if (blocks.length == 0) {
            print('_cameraScanSearch() - blocks.length == 0');
          }
        
          for (TextBlock block in blocks) {
            print('_cameraScanSearch() - block -> $block');
          }
          print('_cameraScanSearch() - search took: ${stopWatch.elapsed}');
          stopWatch.stop();
          _recognizer.close();
        } catch (error) {
              print('_cameraScanSearch() - error: $error');
        }
    }

    @override
    Widget build(BuildContext context) {
    
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text(
            'Firebase_ML_Vision - MPV',
            style: TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.w400,
            ),
          ),
        ),
        body: SingleChildScrollView(
          child: Container(
            child: Column(
              mainAxisSize: MainAxisSize.max,
              children: <Widget>[
                Center(
                  child: FlatButton.icon(
                    onPressed: _cameraScanSearch,
                    icon: Icon(Icons.camera_alt),
                    label: Text('Take Photo'),
                  ),
                ),
                Text (
                    'Detected Text: $_detectedText'
                ),

                if(_image != null)
                  Image.file(_image),
              ],
            ),
          ),
        ),
      ), //Scaffold
    );
      }
    }
`

**Expected results:** Firebase ML Vision Text should be detecting text in all orientations

**Actual results:** Text is recognised correctly on Android in both portrait and landscape, however for iOS text is not detected.  There may actually be two issues here.  1) Text is not recognised in Portrait, but is detected when the picture is taken in landscape. 2) On iPad Mini 2, text is not recognised and when outputting text it seems to be mirrored and garbage!  I think the photo orientation is off when taking photos in iOS devices.

<details>
  <summary>Logs</summary>

C:\Users\Rob\Desktop\ocr_test>flutter doctor -v
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.17.0 at C:\flutter
    • Framework revision e6b34c2b5c (6 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Rob\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2
    • Flutter plugin version 45.1.2
    • Dart plugin version 201.7223.43

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Rob\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```
```

</details>

**Comment by TehRaab** [comment] 2020-06-15 18:35
I hope this is ok - i've also uploaded a screen shot of my iPhone 6 after i had taken a picture of the word "Hello" whilst in portrait and landscape.  This text was not detected.

**Portrait - Not Working**
[https://ibb.co/WpmSwdX](url)

**Landscape - Working**
[https://ibb.co/drYQM5M](url)

**Comment by TahaTesser** [comment] 2020-06-16 09:02
Hi @TehRaab 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank yoU

**Closed by TahaTesser** 2020-06-16 09:02 UTC
