### ISSUE TITLE
[animations] OpenContainer 'open action' should return Future<T> to match Navigator.push()

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#51750] opened 2020-03-01 21:55 UTC
It's a very common workflow to push() a pageRoute, and await on it's results, then doing more work once the page has been popped and returns it's results. It would be nice to still be able to do this with OpenContainer, since it really is just a fancy pageRoute. 

Currently I can't seem to find a way to do this with OpenContainer(). The "open" action is VoidCallback, not allowing any results or async await.  

Couldn't you pass back the async Navigator.push result since it's being run through navigator anyways? I think would enable most use cases.

In a similar vein, the close action, should accept a dynamic payload, since it's essentially a standin for **.pop()**

**Comment by goderbauer** [comment] 2020-03-30 17:14
Duplicate of https://github.com/flutter/flutter/issues/51458.

**Closed by goderbauer** 2020-03-30 17:14 UTC
Labels: p: animations, plugin, proposal
