### ISSUE TITLE
Textfield scrolls back into view after covered by keyboard expecting a value greather than 65

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#76131] opened 2021-02-16 18:16 UTC
integration_ui_ios_textfield is failing occasionally the textfield scrolls back into view after covered by keyboard expecting a value greather than 65.

Logs:
https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20integration_ui_ios_textfield/381

If this validation is affected by the number of CPUs and memory available in the hosts we may need to adjust it as the new machines have double the specs as the previous devicelab ones.

```
[integration_ui_ios_textfield] [STDOUT] stdout: [        ] Application launched on the device. Waiting for observatory port.
[integration_ui_ios_textfield] [STDOUT] stdout: [ +833 ms] Observatory URL on device: http://127.0.0.1:55647/
[integration_ui_ios_textfield] [STDOUT] stdout: [   +6 ms] Attempting to forward device port 55647 to host port 49642
[integration_ui_ios_textfield] [STDOUT] stdout: [        ] executing: /opt/s/w/ir/k/recipe_cleanup/tmpAWwPpI/flutter sdk/bin/cache/artifacts/usbmuxd/iproxy 49642:55647 --udid 4e131215b69d6679703d698c2418e1e3ddcdf8c6
[integration_ui_ios_textfield] [STDOUT] stdout: [+1118 ms] Forwarded port ForwardedPort HOST:49642 to DEVICE:55647
[integration_ui_ios_textfield] [STDOUT] stdout: [        ] Forwarded host port 49642 to device port 55647 for Observatory
[integration_ui_ios_textfield] [STDOUT] stdout: [   +2 ms] Installing and launching... (completed in 12.5s)
[integration_ui_ios_textfield] [STDOUT] stdout: [   +4 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:49642/.
[integration_ui_ios_textfield] [STDOUT] stdout: [ +258 ms] DDS is listening at http://127.0.0.1:49644/xQOirUl5-Hs=/.
[integration_ui_ios_textfield] [STDOUT] stdout: [  +90 ms] executing: /opt/s/w/ir/k/recipe_cleanup/tmpAWwPpI/flutter sdk/bin/cache/dart-sdk/bin/dart /opt/s/w/ir/k/recipe_cleanup/tmpAWwPpI/flutter sdk/dev/integration_tests/ui/test_driver/keyboard_textfield_test.dart -rexpanded
[integration_ui_ios_textfield] [STDOUT] stdout: [+1843 ms] 00:00 [32m+0[0m: end-to-end test (setUpAll)[0m
[integration_ui_ios_textfield] [STDOUT] stderr: [  +29 ms] VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:49644/xQOirUl5-Hs=/
[integration_ui_ios_textfield] [STDOUT] stderr: [ +145 ms] VMServiceFlutterDriver: Isolate found with number: 2066044368802283
[integration_ui_ios_textfield] [STDOUT] stderr: [  +41 ms] VMServiceFlutterDriver: Isolate is paused at start.
[integration_ui_ios_textfield] [STDOUT] stderr: [        ] VMServiceFlutterDriver: Attempting to resume isolate
[integration_ui_ios_textfield] [STDOUT] stdout: [ +230 ms] fopen failed for data file: errno = 2 (No such file or directory)
[integration_ui_ios_textfield] [STDOUT] stdout: [        ] Errors found! Invalidating cache...
[integration_ui_ios_textfield] [STDOUT] stdout: [ +108 ms] fopen failed for data file: errno = 2 (No such file or directory)
[integration_ui_ios_textfield] [STDOUT] stdout: [        ] Errors found! Invalidating cache...
[integration_ui_ios_textfield] [STDOUT] stderr: [ +875 ms] VMServiceFlutterDriver: Connected to Flutter application.
[integration_ui_ios_textfield] [STDOUT] stdout: [   +4 ms] 00:01 [32m+0[0m: end-to-end test Textfield scrolls back into view after covered by keyboard[0m
[integration_ui_ios_textfield] [STDOUT] stdout: [+4622 ms] 00:06 [32m+0[0m[31m -1[0m: end-to-end test Textfield scrolls back into view after covered by keyboard [1m[31m[E][0m[0m
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   Expected: a value greater than <65.0>
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]     Actual: <65.0>
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]      Which: is not a value greater than <65.0>
[integration_ui_ios_textfield] [STDOUT] stdout: [  +22 ms]   package:test_api/src/frontend/expect.dart 155:31               fail
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/frontend/expect.dart 150:3                _expect
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/frontend/expect.dart 59:3                 expect
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   test_driver/keyboard_textfield_test.dart 49:7                  main.<fn>.<fn>
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1294:19                                   _CustomZone.registerBinaryCallback
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async-patch/async_patch.dart 61:8                         _asyncErrorWrapperHelper
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                   _rootRun
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                   _CustomZone.run
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1789:10                                   _runZoned
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1711:10                                   runZoned
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 383:17               Invoker._onRun.<fn>.<fn>.<fn>
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1286:19                                   _CustomZone.registerUnaryCallback
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async-patch/async_patch.dart 45:22                        _asyncThenWrapperHelper
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                   _rootRun
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                   _CustomZone.run
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1789:10                                   _runZoned
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1711:10                                   runZoned
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 370:9                Invoker._onRun.<fn>.<fn>
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 415:15               Invoker._guardIfGuarded
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 369:7                Invoker._onRun.<fn>
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:stack_trace/src/chain.dart 94:24                       Chain.capture.<fn>
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                   _rootRun
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                   _CustomZone.run
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1789:10                                   _runZoned
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   dart:async/zone.dart 1711:10                                   runZoned
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:stack_trace/src/chain.dart 92:12                       Chain.capture
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 368:11               Invoker._onRun
[integration_ui_ios_textfield] [STDOUT] stdout: [        ]   package:test_api/src/backend/live_test_controller.dart 153:11  LiveTestController.run
```

**Comment by godofredoc** [comment] 2021-02-16 18:17
\cc @jmagman @jonahwilliams

**Comment by jmagman** [comment] 2021-02-16 22:10
Those logs show a iPhone 6s.  I wasn't able to reproduce in portrait or landscape on my own iPhone 6s.

**Comment by jmagman** [comment] 2021-02-16 22:12
Failing expectation is https://github.com/flutter/flutter/blob/e605b7c2250e803f46017b1d544fc8c297007546/dev/integration_tests/ui/test_driver/keyboard_textfield_test.dart#L49

**Comment by goderbauer** [comment] 2021-02-17 00:21
@jmagman Do you happen to remember what this looks like on device when the test fails? Is the textfield in question actually still covered by the keyboard or does it scroll up to not be covered by the keyboard? I am wondering whether the scroll doesn't work at all or we are just looking at the scrollable too early before the scroll actually finished executing...

**Comment by goderbauer** [comment] 2021-02-17 01:04
I am also unable to repro this failure locally. Furthermore, in the history of this test on LUCI I can only find one instance in which it failed in this way...

**Comment by Hixie** [comment] 2021-02-23 23:51
Sounds like we should close this as an unexplained fluke flake that we don't believe is causing ongoing issues?

**Closed** 2021-02-24 17:10 UTC
Labels: P2, a: text input, framework, passed first triage, team, team: flakes
