### ISSUE TITLE
Create an iOS or Android library for native apps, that happens to use Flutter

### ISSUE THREAD

**Issue by dodongo** [flutter/flutter#24621] opened 2018-11-21 15:52 UTC
Hoping to get more eyes on this question: https://stackoverflow.com/questions/53348524/integrate-flutter-into-cocoatouch-sdk. Does my approach seem ok here? Is the ability to integrate flutter into iOS or Android frameworks a goal of the project?

**Comment by zoechi** [comment] 2018-11-22 15:08
@Hixie

**Comment by dnfield** [comment] 2019-01-16 07:36
Is this the same as https://github.com/flutter/flutter/issues/26099?

**Comment by jmagman** [comment] 2019-12-19 00:20
@xster This seems like a duplicate of https://github.com/flutter/flutter/issues/39027.

**Comment by xster** [comment] 2019-12-19 00:21
It is. Let's dedup.

**Closed by xster** 2019-12-19 00:21 UTC
Labels: a: existing-apps, e: embedder, engine, tool
