### ISSUE TITLE
Drawer looks wrong if using CupertinoPageTransitionsBuilder

### ISSUE THREAD

**Issue by shcahill** [flutter/flutter#37842] opened 2019-08-08 05:08 UTC
## Steps to Reproduce

sample project
https://github.com/shcahill/DrawerWithCupertino

1. set CupertinoPageTransitionsBuilder into ThemeData#pageTransitionsTheme 
2. Navigator.push to any page.
3. open Drawer
4. Drawer will not open and previous page will overlap

![sample](https://user-images.githubusercontent.com/6898223/62676484-fa547880-b9e5-11e9-9ac7-6af5ef625611.gif)

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.3 18D109, locale ja-JP)
    • Flutter version 1.7.8+hotfix.4 at /Users/kosuke-matsumura/Develop/lib/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kosuke-matsumura/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_SDK_ROOT = /Users/kosuke-matsumura/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
```

**Comment by timsneath** [comment] 2020-01-03 04:05
I cannot reproduce this on an iPhone running Flutter 1.12. See below: 
![drawer_1](https://user-images.githubusercontent.com/2319867/71706652-1a247880-2d9b-11ea-94bc-154b45373257.gif)

I'm closing this issue for now, but please feel free to reopen if you are able to reproduce it on 1.12 with an iPhone simulator or physical device. Thanks!

**Comment by shcahill** [comment] 2020-01-03 04:18
Thanks for your reply.
I tried again on Android device, it seems have not fixed yet...
(iPhone seems be good, thanks)

`Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0`

**Comment by timsneath** [comment] 2020-01-03 05:17
Hmm... not seeing this reproduce on my Android emulator either? Can you take a look at this animation and verify that this is the expected behavior.

![test](https://user-images.githubusercontent.com/2319867/71708294-1d246680-2da5-11ea-8d71-5943640dee8f.gif)

**Comment by shcahill** [comment] 2020-01-09 12:53
Sorry for response. I using Pixel 3a(Android 10).
![output](https://user-images.githubusercontent.com/6898223/72068991-8833e700-3329-11ea-9f7d-0daeebfc5563.gif)

the problem seems only when open drawer with edge swipe. (using drawer-icon is successful.)
In this gif, first half is open drawer with drawer-icon and it seems no problem.
and second half is open drawer with edge swipe, then problem appeared.
after that, any button has no response.(FAB and drawer-icon)

**Comment by talatkuyuk** [comment] 2020-04-17 17:24
The same issue i have.

I have used pageTransitionsTheme in ThemeData.  When I remove the themeData there is no problem with drawer. But the themeData say pageTransitionsTheme comes in play, the drawer acts as weird. The drawer is opening when I click a menu icon (with openDrawer()), but the problem occurs when open drawer with edge swipe, say from left edge. In my case, a black screen comes from left, actually the drawer has to come .

Also issue with drawer opening animation, forexample the duration is destroyed and smooth behaviour disappears, the drawer comes to play in sudden when i click to menü icon.

Again, when i remove the theme  CupertinoPageTransitionsBuilder, there is no any issue.

ThemeData theme = ThemeData(
  fontFamily: 'FiraSans',
  //primaryColor: Colors.white,
  accentColor: ipikukaBlue,
  brightness: Brightness.light,
  primaryColorBrightness: Brightness.light,
  scaffoldBackgroundColor: Color(0xFFFFFFFF),
  backgroundColor: Color(0xFFFFFFFF),
  appBarTheme: AppBarTheme(
    color: Colors.white,
    brightness: Brightness.dark,
  ),
  pageTransitionsTheme: PageTransitionsTheme(
    builders: {
      TargetPlatform.android: CupertinoPageTransitionsBuilder(),
      TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
      TargetPlatform.fuchsia: CupertinoPageTransitionsBuilder(),
    },
  ),
);

**Comment by TahaTesser** [comment] 2020-09-11 15:29
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Drawer Sample',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        pageTransitionsTheme: PageTransitionsTheme(builders: {
          TargetPlatform.android: CupertinoPageTransitionsBuilder(),
        }),
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(child: Text("TOP PAGE")),
      drawer: Drawer(child: Text("Drawer")),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context).push(
              MaterialPageRoute(builder: (BuildContext context) => NextPage()));
        },
        child: Icon(Icons.add),
      ),
    );
  }
}

class NextPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Next Page"),
      ),
      body: Text("Body"),
      drawer: Drawer(
        child: Text("Drawer"),
      ),
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.138, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.138 at /Users/tahatesser/Code/flutter_master
    • Framework revision 620cd16cf0 (54 minutes ago), 2020-09-11 10:35:03 -0400
    • Engine revision a0bd862cc0
    • Dart version 2.10.0 (build 2.10.0-115.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-11-09 13:08
This issue is no longer reproducible on `Master (3.5.0-12.0.pre.175)`. Closing as fixed

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Drawer Sample',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        pageTransitionsTheme: const PageTransitionsTheme(builders: {
          TargetPlatform.android: CupertinoPageTransitionsBuilder(),
        }),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: const Center(child: Text("TOP PAGE")),
      drawer: const Drawer(child: Text("Drawer")),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(
              builder: (BuildContext context) => const NextPage(),
            ),
          );
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

class NextPage extends StatelessWidget {
  const NextPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Next Page")),
      body: const Text("Body"),
      drawer: const Drawer(child: Text("Drawer")),
    );
  }
}
```

</details>

<details>
<summary>Video</summary>

<img width="300" src="https://user-images.githubusercontent.com/50555895/200838337-b0a9968f-9f88-4b04-97b4-6c4cf5be023c.gif">

</details>

**Closed by exaby73** 2022-11-09 13:08 UTC
Labels: framework, f: material design, f: cupertino, f: routes, has reproducible steps, found in release: 1.22
