### ISSUE TITLE
Error: No named parameter with the name 'nullOk'.             context != null ? Localizations.localeOf(context, nullOk: true) : null,

### ISSUE THREAD

**Issue by ychhatre** [flutter/flutter#75172] opened 2021-02-01 21:40 UTC
## Steps to Reproduce
1. switch to flutter channel master
2. downgrade to the lowest version that flutter allows for flutter channel master 
3. flutter clean & remove pods, podfile.lock, and podfile from {app}/ios 
4. "flutter run" 

**Expected results:** 
The app should open up on my emulator 

**Actual results:** 
```
/Library/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
            context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                              ^^^^^^
    /Library/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
      static Locale localeOf(BuildContext context) {
                    ^^^^^^^^
    /Library/flutter/.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/overlay.dart:156:19: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.
     - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/Library/flutter/packages/flutter/lib/src/widgets/framework.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'.
          if (context.ancestorWidgetOfExactType(OverlaySupport) != null) {
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
    /Library/flutter/.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/overlay_entry.dart:17:37: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.
     - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/Library/flutter/packages/flutter/lib/src/widgets/framework.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'.
        final animatedOverlay = context.ancestorWidgetOfExactType(_AnimatedOverlay);
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
    /Library/flutter/.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/theme.dart:53:20: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
     - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/Library/flutter/packages/flutter/lib/src/widgets/framework.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        return context.inheritFromWidgetOfExactType(OverlaySupportTheme) as OverlaySupportTheme;
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
```
<details>
  <summary>Logs</summary>

#0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:627:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1159:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1011:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:280:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:66:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:64:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:75:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +222 ms] ensureAnalyticsSent: 218ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1

```
```

```
```

[✓] Flutter (Channel master, 1.26.0-18.0.pre.96, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
    • Flutter version 1.26.0-18.0.pre.96 at /Library/flutter
    • Framework revision 091a74dab6 (4 hours ago), 2021-02-01 23:29:53 +0530
    • Engine revision 833d9953a7
    • Dart version 2.12.0 (build 2.12.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/krishmalik/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 6D435317-BCE1-45F3-8180-A3EC9CEEED04 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 88.0.4324.96

• No issues found!

```
```

</details>

**Comment by pedromassangocode** [comment] 2021-02-02 06:29
Hi @ychhatre 
From what I can see, the issue is related to a 3rd party plugins/packages rather than to Flutter itself. Please open the issue in the dedicated repository [overlay_support](https://github.com/boyan01/overlay_support), [flutter_svg](https://pub.dev/packages/flutter_svg).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-02 06:29 UTC

**Comment by omarreess** [comment] 2021-02-02 12:29
I have the issue too any Help

**Comment by mario125** [comment] 2021-02-05 00:38
tengo el mismo problemas

**Comment by agavrel** [comment] 2021-02-07 00:29
You can solve it by using ```flutter downgrade``` (along with flutter pub get and invalidate cache and restart)
The latest release has some breaking changes as it seems.

**Comment by funmidev** [comment] 2021-02-11 11:51
Running Gradle task 'assembleDebug'...
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.19.1/lib/src/picture_provider.dart:52:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
/C:/Users/artfu/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:1111:7: Info: Struct 'ENUMLOGFONTEX' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class ENUMLOGFONTEX extends Struct {
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2835:7: Info: Struct 'BLUETOOTH_PIN_INFO' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class BLUETOOTH_PIN_INFO extends Struct {
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2960:7: Info: Struct 'EXCEPINFO' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class EXCEPINFO extends Struct {}
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2966:7: Info: Struct 'PROPERTYKEY' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class PROPERTYKEY extends Struct {}
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2973:7: Info: Struct 'PROPVARIANT' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class PROPVARIANT extends Struct {}
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2978:7: Info: Struct 'SAFEARRAY' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class SAFEARRAY extends Struct {}
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2985:7: Info: Struct 'CLSID' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class CLSID extends Struct {}
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2992:7: Info: Struct 'STATSTG' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class STATSTG extends Struct {}
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart:2999:7: Info: Struct 'NLM_SIMULATED_PROFILE_INFO' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class NLM_SIMULATED_PROFILE_INFO extends Struct {}
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart:23:7: Info: Struct 'Utf8' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class Utf8 extends Struct {
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf16.dart:16:7: Info: Struct 'Utf16' is empty. Support for empty structs is deprecated and will be removed in the next stable version of Dart. Use Opaque instead.
class Utf16 extends Struct {
      ^
/C:/Users/artfu/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/allocation.dart:47:33: Info: Support for using non-constant type arguments 'T' in this FFI API is deprecated and will be removed in the next stable version of Dart. Rewrite the code to ensure that type arguments are compile time constants referring to a valid native type.
  final int totalSize = count * sizeOf<T>();
                                ^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\artfu\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\artfu\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by funmidev** [comment] 2021-02-11 11:52
i tried to downgrade the flutter : 

There is no previously recorded version for channel "beta".
Channel "dev" was previously on: 1.26.0-17.2.pre
.

**Comment by eleresearch** [comment] 2021-02-17 02:25
I was having this issue and the cause was the flutter_svg package, but if you implement the dev version it has a null safety feature that will take care of the error.

**Comment by funmidev** [comment] 2021-02-17 02:28
Already solved it, thank you so much 😊 but I have some difficulties in my
current , I don’t know if can ask for your help/assistance pls.

Thank you in advance.

**Comment by nadysaptra** [comment] 2021-02-17 05:36
I was able to solve this by downgrade flutter to 1.26.0-12pre and flutter_html to ^1.2.0 (if you used it) and intl: 0.17.0-nullsafety.2

**Comment by funmidev** [comment] 2021-02-17 09:30
Awesome, thanks! Yeah same this I did. 😊

**Comment by Saurab-Rakshit** [comment] 2021-02-17 12:48
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.1/lib/src/picture_provider.dart:52:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^        
/C:/src/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but 
the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
                                          
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. 
Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      47.2s
Gradle task assembleRelease failed with exit code 1

facing this issue while generating apk for the flutter project

**Comment by codesxt** [comment] 2021-02-17 15:13
@Saurab-Rakshit LocaleOf does not use the parameter nullOk anymore. You can see the source code [here](maybeLocaleOf).

Now there are two versions:

- in line 413 localeOf: this one is null safe
- in line 439 maybeLocaleOf: this one can return null

You can either use any of them according to your case. I just faced the same problem and solved it by using maybeLocaleOf because my code considered the null response. If your locale will never be null, I recommend you using localeOf.

More info on null safety [here](https://dart.dev/null-safety/understanding-null-safety).

**Comment by ychhatre** [comment] 2021-02-17 18:53
I was able to find a fix for the issue -- it was seriously dumb and I have no clue how it worked, but the flutter_svg package has a "1.3.0^" (this is a random version number) and instead you should be doing just 1.3.0 without the karot, and for the most odd reason this worked! - gonna close the issue now but for future references this should fix it, try this for the packages that are giving you the null safety error !

**Comment by funmidev** [comment] 2021-02-17 18:54
Awesome, thanks!

**Comment by funder7** [comment] 2021-02-27 01:14
https://flutter.dev/docs/release/breaking-changes/eliminating-nullok-parameters 
Maybe there's something interesting here

**Comment by ahmedalmubarak** [comment] 2021-03-06 05:02
I solve this issue by updating flutter_svg package to Latest version .

**Comment by steveny909** [comment] 2021-03-08 23:34
solved by going to flutter_svg: ^0.19.3

**Comment by gourab337** [comment] 2021-03-21 17:39
Try to specify specific versions for your 3rd party packages in pubspec.yaml (under dependencies). Eg: flutter_svg: / or file_picker: , etc to flutter_svg: ^0.20.0-nullsafety.3

**Comment by felipecastrosales** [comment] 2021-06-05 04:53
I had this problem in a project using readmore version 1.0.1. I managed to resolve when switching to version 2.0.0!

**Comment by exeptionerror** [comment] 2021-06-24 09:27
All Possible solution added [[Solved] No named parameter with the name 'nullOk' error in flutter](https://fluttercorner.com/no-named-parameter-with-the-name-nullok-error-in-flutter/)
