### ISSUE TITLE
Add NoAnimationPageTransitionsBuilder

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#99514] opened 2022-03-03 21:55 UTC
I recently learned that Material Design apps shouldn't display transition animations on desktop platforms. If this is the case, the default builders in the `PageTransitionsTheme` class don't seem to be using the correct `PageTransitionsBuilder`:

```dart
  static const Map<TargetPlatform, PageTransitionsBuilder> _defaultBuilders = <TargetPlatform, PageTransitionsBuilder>{
    TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
    TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
    TargetPlatform.linux: FadeUpwardsPageTransitionsBuilder(),
    TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
    TargetPlatform.windows: FadeUpwardsPageTransitionsBuilder(),
  };
```

## Proposal

Create a new class, `NoAnimationPageTransitionsBuilder` and use that as the default PageTransitionsBuilder for linux, macOS, and Windows:

```dart
class NoAnimationPageTransitionsBuilder extends PageTransitionsBuilder {
  const NoAnimationPageTransitionsBuilder();

  @override
  Widget buildTransitions<T>(
      PageRoute<T> route,
      BuildContext context,
      Animation<double> animation,
      Animation<double> secondaryAnimation,
      Widget child,
      ) {
    return child;
  }
}
```

**Comment by johnpryan** [comment] 2022-03-03 22:00
After more investigation, it looks like this behavior was reverted due to the navigation delay: https://github.com/flutter/flutter/pull/89997

cc: @darrenaustin WDYT?

**Comment by maheshmnj** [comment] 2022-03-04 08:11
Hi @johnpryan, Thanks for filing the issue. This issue is already filed and is being tracked here https://github.com/flutter/flutter/issues/99052

Please followup there for further updates, Closing this issue as a duplicate of the linked issue.

**Closed by maheshmnj** 2022-03-04 08:11 UTC
Labels: in triage
