### ISSUE TITLE
flutter pub add error while installing shared_preferences package

### ISSUE THREAD

**Issue by fawzibr** [flutter/flutter#120196] opened 2023-02-07 15:12 UTC
I'm trying to install the shared_preferences package and it is giving me the following error:

Exception: ERROR_ACCESS_DENIED file system exception thrown while trying to create a symlink from source to dest

Developer mode IS enabled.
Windows 11 Home (22H2) - NTFS file system

I installed Android studio at one computer (home computer) gave me a similar error (link related) googled that if I set Developer Mode to on would solve it. In that computer it worked, for some reason not in this one (work computer). Uninstalled Android Studio/flutter, reinstalled, still fails. Uninstalled and installed in another location (different NTFS disk,just in case), fails. Just trying to find out why things fail on the work computer. 

## Steps to Reproduce

1. flutter pub add shared_preferences -v

## Logs

<details>
<summary>flutter pub add shared_preferences -v</summary>

MSG : Logs written to C:\Users\fawzi\AppData\Local\Pub\Cache\log\pub_log.txt.
[+2534 ms] Found plugin path_provider_linux at C:\Users\fawzi\AppData\Local\Pub\Cache\hosted\pub.dev\path_provider_linux-2.1.7\
[   +5 ms] Found plugin path_provider_windows at C:\Users\fawzi\AppData\Local\Pub\Cache\hosted\pub.dev\path_provider_windows-2.1.3\
[   +5 ms] Found plugin shared_preferences at C:\Users\fawzi\AppData\Local\Pub\Cache\hosted\pub.dev\shared_preferences-2.0.17\
[   +1 ms] Found plugin shared_preferences_android at C:\Users\fawzi\AppData\Local\Pub\Cache\hosted\pub.dev\shared_preferences_android-2.0.15\
[   +1 ms] Found plugin shared_preferences_foundation at C:\Users\fawzi\AppData\Local\Pub\Cache\hosted\pub.dev\shared_preferences_foundation-2.1.3\
[   +2 ms] Found plugin shared_preferences_linux at C:\Users\fawzi\AppData\Local\Pub\Cache\hosted\pub.dev\shared_preferences_linux-2.1.3\
[   +2 ms] Found plugin shared_preferences_web at C:\Users\fawzi\AppData\Local\Pub\Cache\hosted\pub.dev\shared_preferences_web-2.0.4\
[   +1 ms] Found plugin shared_preferences_windows at C:\Users\fawzi\AppData\Local\Pub\Cache\hosted\pub.dev\shared_preferences_windows-2.1.3\
[ +107 ms] "flutter add" took 2,829ms.
[   +3 ms] ERROR_ACCESS_DENIED file system exception thrown while trying to create a symlink from source to dest
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      handleSymlinkException (package:flutter_tools/src/flutter_plugins.dart:1014:7)
           #2      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1059:7)
           #3      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:987:5)
           #4      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1089:5)
           <asynchronous suspension>
           #5      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
           <asynchronous suspension>
           #6      PackagesInteractiveGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:357:5)
           <asynchronous suspension>
           #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
</details>

<details>
<summary>flutter doctor -v</summary>
                                                                                        
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
    • Flutter version 3.7.1 on channel stable at D:\Android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (6 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\fawzi\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: D:\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31605.320
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at D:\Android\Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.74.1)
    • VS Code at C:\Users\fawzi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.78

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by huycozy** [comment] 2023-02-08 07:48
Hi @fawzibr,
It seems the issue is related to anti-virus apps and it is intentional (as mentioned here at https://github.com/flutter/flutter/issues/62425) but I don't see any specific advice given from your stacktrace. Looks like it will continue working at https://github.com/flutter/flutter/issues/61997.

But in the meantime, can you try adding Flutter SDK/project directory/pub cache directory to anti-virus whitelist and check if it works?

**Comment by fawzibr** [comment] 2023-02-09 13:29
> Hi @fawzibr, It seems the issue is related to anti-virus apps and it is intentional (as mentioned here at #62425) but I don't see any specific advice given from your stacktrace. Looks like it will continue working at #61997.
> 
> But in the meantime, can you try adding Flutter SDK/project directory/pub cache directory to anti-virus whitelist and check if it works?

That wasn't it, the project file was in a Samba share and aparently links in shares do not work by default. After looking around found how to set it up, leaving solution here for others to find (myself included), now it works:

For Windows SMB clients to traverse each type of symbolic link, you must enable them on the client. Windows supports the following link types:

- local to local
- remote to remote
- local to remote
- remote to local

You must run the following Windows command to enable all four link types:

`fsutil behavior set SymlinkEvaluation L2L:1 R2R:1 L2R:1 R2L:1`

For POSIX clients using Samba, you must set the following options in the [global] section of your Samba configuration file (smb.conf) to enable Samba clients to traverse relative and absolute links:

```
follow symlinks=yes 

wide links=yes
```

In this case, “wide links” in the smb.conf file refers to absolute links. The default setting in this file is no.

**Comment by huycozy** [comment] 2023-02-10 03:43
Given your last message, I feel safe to close this issue as solved. Thanks for your contribution!

**Closed by huycozy** 2023-02-10 03:43 UTC
Labels: in triage
