### ISSUE TITLE
Scroll drag not working in Listview

### ISSUE THREAD

**Issue by TFSThiagoBR98** [flutter/flutter#84627] opened 2021-06-15 12:22 UTC
For some reason scroll drag don't work in desktop(linux) and web (channel dev, master).

## Steps to Reproduce

1. flutter create scrollbug
2. Replace main.dart content with
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text("Scroll bug"),
        ),
        body: Container(
          margin: EdgeInsets.symmetric(vertical: 20.0),
          height: 200.0,
          child: ListView(
            cacheExtent: 500,
            scrollDirection: Axis.horizontal,
            children: <Widget>[
              Container(
                width: 160.0,
                color: Colors.red,
              ),
              Container(
                width: 160.0,
                color: Colors.blue,
              ),
              Container(
                width: 160.0,
                color: Colors.green,
              ),
              Container(
                width: 160.0,
                color: Colors.yellow,
              ),
              Container(
                width: 160.0,
                color: Colors.orange,
              ),
              Container(
                width: 160.0,
                color: Colors.red,
              ),
              Container(
                width: 160.0,
                color: Colors.blue,
              ),
              Container(
                width: 160.0,
                color: Colors.green,
              ),
              Container(
                width: 160.0,
                color: Colors.yellow,
              ),
              Container(
                width: 160.0,
                color: Colors.orange,
              ),
              Container(
                width: 160.0,
                color: Colors.red,
              ),
              Container(
                width: 160.0,
                color: Colors.blue,
              ),
              Container(
                width: 160.0,
                color: Colors.green,
              ),
              Container(
                width: 160.0,
                color: Colors.yellow,
              ),
              Container(
                width: 160.0,
                color: Colors.orange,
              ),
              Container(
                width: 160.0,
                color: Colors.red,
              ),
              Container(
                width: 160.0,
                color: Colors.blue,
              ),
              Container(
                width: 160.0,
                color: Colors.green,
              ),
              Container(
                width: 160.0,
                color: Colors.yellow,
              ),
              Container(
                width: 160.0,
                color: Colors.orange,
              ),
            ],
          ),
        ),
      )
    );
  }
}
```

**Expected results: (Linux)** 
```
Flutter 2.2.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (3 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

https://user-images.githubusercontent.com/16943898/121945625-5ac34800-cd2a-11eb-8a12-ff7ff855977e.mp4

**Actual results: (Linux)** 
```
Flutter 2.3.0-16.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision fa5883b78e (3 weeks ago) • 2021-05-21 13:04:03 -0700
Engine • revision 2f067fc4c5
Tools • Dart 2.14.0 (build 2.14.0-136.0.dev)
```

https://user-images.githubusercontent.com/16943898/121943938-775e8080-cd28-11eb-8216-094cee48a1f0.mp4

<details>
  <summary>Logs</summary>

```
```

```
Analyzing scroll_test...                                                
No issues found! (ran in 1.9s)
```

Working:
```
[✓] Flutter (Channel beta, 2.2.2, on Linux, locale pt_BR.UTF-8)
    • Flutter version 2.2.2 at /home/tfsthiagobr98/Android/Flutter/flutter
    • Framework revision d79295af24 (3 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/tfsthiagobr98/Android/Sdk/
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/tfsthiagobr98/Android/Sdk/
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.0
    • cmake version 3.20.3
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /usr/share/idea
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.8538.45

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 91.0.4472.101 Arch Linux

• No issues found!
```

Not working:

```
[✓] Flutter (Channel dev, 2.3.0-16.0.pre, on Arch Linux 5.10.42-1-lts, locale pt_BR.UTF-8)
    • Flutter version 2.3.0-16.0.pre at /home/tfsthiagobr98/Android/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fa5883b78e (3 weeks ago), 2021-05-21 13:04:03 -0700
    • Engine revision 2f067fc4c5
    • Dart version 2.14.0 (build 2.14.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/tfsthiagobr98/Android/Sdk/
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/tfsthiagobr98/Android/Sdk/
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.0
    • cmake version 3.20.3
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /usr/share/idea
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.8538.45

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Arch Linux 5.10.42-1-lts
    • Chrome (web)                       • chrome        • web-javascript • Chromium 91.0.4472.101 Arch Linux

• No issues found!
```

</details>

**Comment by kushankurxd** [comment] 2021-06-15 14:20
Not sure about **Desktop** but **web** works well when I tried your code
Here is my version check if it helps
![image](https://user-images.githubusercontent.com/37204706/122069510-1a0b1380-cdaa-11eb-8554-f0b6c01d7758.png)

**Comment by TFSThiagoBR98** [comment] 2021-06-15 14:37
It seems that this issue only affects the dev and master channels

**Comment by TahaTesser** [comment] 2021-06-16 11:16
HI @TFSThiagoBR98 
This is not a bug, mouse drag to scroll disabled by default on desktop/web apps when running on the desktop environment in https://github.com/flutter/flutter/pull/81569

You can use shift + scroll to scroll horizontally although it is broken on Linux and windows right now https://github.com/flutter/flutter/issues/83359  https://github.com/flutter/flutter/issues/75180
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-16 11:16 UTC
Labels: in triage

**Comment by TFSThiagoBR98** [comment] 2021-06-16 14:03
Thank you, I did the migration as per https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag and now it's working
