### ISSUE TITLE
Flutter issue "Flutter NSException: Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options "

### ISSUE THREAD

**Issue by Farial-mahmod** [flutter/flutter#100431] opened 2022-03-20 03:19 UTC
We have configured Firebase settings as needed mentioned in the Firebase docs  and GoogleService-info.plist file does already have the IDs . The app runs smoothly in Android devices but stops during the initial splash on iOS simulator device each time.  There is no other errors in the log / run . Ours is the latest Flutter, Dart and MacOS Monterey versions - all up-to-date .

We have already tried clean-build, replacing iOS-Firebase files, https://github.com/fechanique/cordova-plugin-fcm/issues/308 and https://stackoverflow.com/questions/62787686/flutter-nsexception-configuration-fails-it-may-be-caused-by-an-invalid-google but none of these old solutions work.

Your solution would be appreciated .

**Comment by ryzizub** [comment] 2022-03-20 11:44
Have you tried adding GoogleService-Info.plist via XCode not via Finder, lot's of times there is problem in it.

**Comment by Farial-mahmod** [comment] 2022-03-21 03:15
I've dragged that file from Homescreen to Xcode project several times (not via Finder) and ran clean-build-run -- no change yet .

**Comment by darshankawar** [comment] 2022-03-21 07:46
@Farial-mahmod 
Looking at the error:

`Flutter NSException: Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options`

Have you confirmed that your appId id is an iOS one ?  If you look in your appId you'll see the platform mentioned as part of it. 
Also this seems to be related to firebase which has dedicated repo for tracking issues: https://github.com/FirebaseExtended/flutterfire/issues. Please open this issue there and provide all requested details in the template so that we can address it properly.
Closing from here, as this isn't a Flutter issue.

**Closed by darshankawar** 2022-03-21 07:46 UTC
Labels: in triage
