### ISSUE TITLE
Cannot resize Flutter window on macOS when Platform View is shown

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/flutter#109929] opened 2022-08-20 22:33 UTC
## Steps to Reproduce

Not sure if this is related to https://github.com/flutter/flutter/issues/96668 but when trying to display NSView on macOS with latest master the window cannot be resized. Am I making some mistake here? I was trying to follow example from [here](https://github.com/iskakaushik/flutter_macos_platform_view_example) but with SwiftUI.

<img width="912" alt="CleanShot 2022-08-21 at 00 28 49@2x" src="https://user-images.githubusercontent.com/16854239/185768129-92e6f66f-e2c4-499c-8044-421db98ab2d2.png">

1. Run the example here https://github.com/orestesgaolin/flutter_issue_platform_views on macOS
2. Observe the log throwing a following exception
3. Try to resize window
4. Observe the app to freeze

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

import 'package:native_view/native_view.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      themeMode: ThemeMode.dark,
      theme: ThemeData(),
      darkTheme: ThemeData.dark(),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: const NSBox(),
      ),
    );
  }
}

```

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'native_view_platform_interface.dart';

class NativeView {
  Future<String?> getPlatformVersion() {
    return NativeViewPlatform.instance.getPlatformVersion();
  }
}

class NSBox extends StatelessWidget {
  const NSBox({super.key});

  @override
  Widget build(BuildContext context) {
    // This is used in the platform side to register the view.
    const viewType = '@views/native-view';
    // Pass parameters to the platform side.
    final creationParams = <String, dynamic>{};

    return UiKitView(
      viewType: viewType,
      layoutDirection: TextDirection.ltr,
      creationParams: creationParams,
      gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{
        Factory<OneSequenceGestureRecognizer>(
          EagerGestureRecognizer.new,
        ),
      },
      creationParamsCodec: const StandardMessageCodec(),
    );
  }
}

```

```swift

import SwiftUI
import Cocoa
import FlutterMacOS
import Foundation

@available(macOS 11.00, *)
public class NativeViewPlugin: NSObject, FlutterPlugin {
  public static func register(with registrar: FlutterPluginRegistrar) {
    let channel = FlutterMethodChannel(name: "native_view", binaryMessenger: registrar.messenger)
    let instance = NativeViewPlugin()
    registrar.addMethodCallDelegate(instance, channel: channel)

    let factory = FLNativeViewFactory(messenger: registrar.messenger)
    registrar.register(factory, withId: "@views/native-view")
  }

  public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    switch call.method {
    case "getPlatformVersion":
      result("macOS ")
    default:
      result(FlutterMethodNotImplemented)
    }
  }
}

@available(macOS 11.00, *)
class FLNativeViewFactory: NSObject, FlutterPlatformViewFactory {
    private var messenger: FlutterBinaryMessenger
    
    init(messenger: FlutterBinaryMessenger) {
        self.messenger = messenger
        super.init()
    }
    
    func create(withViewIdentifier viewId: Int64, arguments args: Any?) -> NSView {
        return NSHostingView(rootView: MyNativeView())
    }
}


@available(macOS 11.00, *)
struct MyNativeView: View {
    @State var size: CGFloat = 1.0
    var body: some View {
        VStack(alignment: .center) {
            Text("Hello from SwiftUI")
                .font(.headline)
            Text("within Flutter")
                .font(.body)
        }
    }
}

@available(macOS 11.00, *)
struct MyNativeView_Previews: PreviewProvider {
    @available(macOS 11.00.0, *)
    static var previews: some View {
        MyNativeView()
    }
}
```

</details>

<details>
  <summary>Logs</summary>

```
2022-08-21 00:19:22.124031+0200 native_view_example[37793:14666551] Metal API Validation Enabled
flutter: The Dart VM service is listening on http://127.0.0.1:64883/5LdC7RtwWDw=/
=================================================================
Main Thread Checker: UI API called on a background thread: -[NSView setFrame:]
PID: 37793, TID: 14667144, Thread name: io.flutter.raster, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   FlutterMacOS                        0x0000000107513cc8 _ZN7flutter22FlutterMetalCompositor19PresentPlatformViewEPK12FlutterLayerm + 188
5   FlutterMacOS                        0x0000000107513b30 _ZN7flutter22FlutterMetalCompositor7PresentEPPK12FlutterLayerm + 108
6   FlutterMacOS                        0x0000000107d56b54 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZL33InferExternalViewEmbedderFromArgsPK17FlutterCompositorE3$_4NS_9allocatorIS5_EEFbRKNS_6vectorIPK12FlutterLayerNS6_ISB_EEEEEEclESF_ + 88
7   FlutterMacOS                        0x0000000107d66b08 _ZNK7flutter14EmbedderLayers21InvokePresentCallbackERKNSt21_LIBCPP_ABI_NAMESPACE8functionIFbRKNS1_6vectorIPK12FlutterLayerNS1_9allocatorIS6_EEEEEEE + 364
8   FlutterMacOS                        0x0000000107d64f8c _ZN7flutter28EmbedderExternalViewEmbedder11SubmitFrameEP15GrDirectContextNSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_12SurfaceFrameENS3_14default_deleteIS5_EEEE + 932
9   FlutterMacOS                        0x0000000107ba585c _ZN7flutter10Rasterizer19DrawToSurfaceUnsafeERNS_20FrameTimingsRecorderERNS_9LayerTreeE + 1052
10  FlutterMacOS                        0x0000000107ba4cc4 _ZN7flutter10Rasterizer6DoDrawENSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_20FrameTimingsRecorderENS1_14default_deleteIS3_EEEENS1_10shared_ptrINS_9LayerTreeEEE + 208
11  FlutterMacOS                        0x0000000107ba6c48 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZN7flutter10Rasterizer4DrawENS_10shared_ptrINS2_8PipelineINS2_13LayerTreeItemEEEEENS_8functionIFbRNS2_9LayerTreeEEEEE3$_2NS_9allocatorISE_EEFvNS_10unique_ptrIS6_NS_14default_deleteIS6_EEEEEEclEOSK_ + 204
12  FlutterMacOS                        0x0000000107ba3f1c _ZN7flutter8PipelineINS_13LayerTreeItemEE7ConsumeERKNSt21_LIBCPP_ABI_NAMESPACE8functionIFvNS3_10unique_ptrIS1_NS3_14default_deleteIS1_EEEEEEE + 160
13  FlutterMacOS                        0x0000000107ba38ac _ZN7flutter10Rasterizer4DrawENSt21_LIBCPP_ABI_NAMESPACE10shared_ptrINS_8PipelineINS_13LayerTreeItemEEEEENS1_8functionIFbRNS_9LayerTreeEEEE + 152
14  FlutterMacOS                        0x0000000107bc4ce0 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter5Shell14OnAnimatorDrawENS_10shared_ptrINS5_8PipelineINS5_13LayerTreeItemEEEEEE4$_12EENS_9allocatorISD_EEFvvEEclEv + 208
15  FlutterMacOS                        0x0000000107563478 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 252
16  FlutterMacOS                        0x000000010756c024 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 52
17  CoreFoundation                      0x0000000186d7f954 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
18  CoreFoundation                      0x0000000186d7f53c __CFRunLoopDoTimer + 1064
19  CoreFoundation                      0x0000000186d7efc4 __CFRunLoopDoTimers + 392
20  CoreFoundation                      0x0000000186d63a54 __CFRunLoopRun + 1936
21  CoreFoundation                      0x0000000186d62b24 CFRunLoopRunSpecific + 600
22  FlutterMacOS                        0x000000010756c2bc _ZN3fml17MessageLoopDarwin3RunEv + 184
23  FlutterMacOS                        0x0000000107563270 _ZN3fml15MessageLoopImpl5DoRunEv + 60
24  FlutterMacOS                        0x000000010756a43c _ZNSt21_LIBCPP_ABI_NAMESPACE14__thread_proxyB6v15000INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_8functionIFvRKNS8_12ThreadConfigEEEESC_E3$_0EEEEEPvSJ_ + 228
25  libsystem_pthread.dylib             0x0000000104ab5890 _pthread_start + 148
26  libsystem_pthread.dylib             0x0000000104abfaa8 thread_start + 8
2022-08-21 00:19:22.797046+0200 native_view_example[37793:14667144] [reports] Main Thread Checker: UI API called on a background thread: -[NSView setFrame:]
PID: 37793, TID: 14667144, Thread name: io.flutter.raster, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   FlutterMacOS                        0x0000000107513cc8 _ZN7flutter22FlutterMetalCompositor19PresentPlatformViewEPK12FlutterLayerm + 188
5   FlutterMacOS                        0x0000000107513b30 _ZN7flutter22FlutterMetalCompositor7PresentEPPK12FlutterLayerm + 108
6   FlutterMacOS                        0x0000000107d56b54 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZL33InferExternalViewEmbedderFromArgsPK17FlutterCompositorE3$_4NS_9allocatorIS5_EEFbRKNS_6vectorIPK12FlutterLayerNS6_ISB_EEEEEEclESF_ + 88
7   FlutterMacOS                        0x0000000107d66b08 _ZNK7flutter14EmbedderLayers21InvokePresentCallbackERKNSt21_LIBCPP_ABI_NAMESPACE8functionIFbRKNS1_6vectorIPK12FlutterLayerNS1_9allocatorIS6_EEEEEEE + 364
8   FlutterMacOS                        0x0000000107d64f8c _ZN7flutter28EmbedderExternalViewEmbedder11SubmitFrameEP15GrDirectContextNSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_12SurfaceFrameENS3_14default_deleteIS5_EEEE + 932
9   FlutterMacOS                        0x0000000107ba585c _ZN7flutter10Rasterizer19DrawToSurfaceUnsafeERNS_20FrameTimingsRecorderERNS_9LayerTreeE + 1052
10  FlutterMacOS                        0x0000000107ba4cc4 _ZN7flutter10Rasterizer6DoDrawENSt21_LIBCPP_ABI_NAMESPACE10unique_ptrINS_20FrameTimingsRecorderENS1_14default_deleteIS3_EEEENS1_10shared_ptrINS_9LayerTreeEEE + 208
11  FlutterMacOS                        0x0000000107ba6c48 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIZN7flutter10Rasterizer4DrawENS_10shared_ptrINS2_8PipelineINS2_13LayerTreeItemEEEEENS_8functionIFbRNS2_9LayerTreeEEEEE3$_2NS_9allocatorISE_EEFvNS_10unique_ptrIS6_NS_14default_deleteIS6_EEEEEEclEOSK_ + 204
12  FlutterMacOS                        0x0000000107ba3f1c _ZN7flutter8PipelineINS_13LayerTreeItemEE7ConsumeERKNSt21_LIBCPP_ABI_NAMESPACE8functionIFvNS3_10unique_ptrIS1_NS3_14default_deleteIS1_EEEEEEE + 160
13  FlutterMacOS                        0x0000000107ba38ac _ZN7flutter10Rasterizer4DrawENSt21_LIBCPP_ABI_NAMESPACE10shared_ptrINS_8PipelineINS_13LayerTreeItemEEEEENS1_8functionIFbRNS_9LayerTreeEEEE + 152
14  FlutterMacOS                        0x0000000107bc4ce0 _ZNSt21_LIBCPP_ABI_NAMESPACE10__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter5Shell14OnAnimatorDrawENS_10shared_ptrINS5_8PipelineINS5_13LayerTreeItemEEEEEE4$_12EENS_9allocatorISD_EEFvvEEclEv + 208
15  FlutterMacOS                        0x0000000107563478 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 252
16  FlutterMacOS                        0x000000010756c024 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 52
17  CoreFoundation                      0x0000000186d7f954 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
18  CoreFoundation                      0x0000000186d7f53c __CFRunLoopDoTimer + 1064
19  CoreFoundation                      0x0000000186d7efc4 __CFRunLoopDoTimers + 392
20  CoreFoundation                      0x0000000186d63a54 __CFRunLoopRun + 1936
21  CoreFoundation                      0x0000000186d62b24 CFRunLoopRunSpecific + 600
22  FlutterMacOS                        0x000000010756c2bc _ZN3fml17MessageLoopDarwin3RunEv + 184
23  FlutterMacOS                        0x0000000107563270 _ZN3fml15MessageLoopImpl5DoRunEv + 60
24  FlutterMacOS                        0x000000010756a43c _ZNSt21_LIBCPP_ABI_NAMESPACE14__thread_proxyB6v15000INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_8functionIFvRKNS8_12ThreadConfigEEEESC_E3$_0EEEEEPvSJ_ + 228
25  libsystem_pthread.dylib             0x0000000104ab5890 _pthread_start + 148
26  libsystem_pthread.dylib             0x0000000104abfaa8 thread_start + 8

```

```
Analyzing native_view...
No issues found! (ran in 1.5s)

```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2392, on macOS 12.4 21F79 darwin-arm, locale pl-PL)
    • Flutter version 3.1.0-0.0.pre.2392 on channel master at /Users/dominik/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 723609bff1 (9 hours ago), 2022-08-20 09:14:25 -0400
    • Engine revision d89aae21e9
    • Dart version 2.19.0 (build 2.19.0-119.0.dev)
    • DevTools version 2.16.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dominik/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • 100678F9-BADC-4EFD-B557-D736E72E3A57 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

# Related: 

https://github.com/flutter/flutter/issues/41722
https://github.com/flutter/flutter/issues/41725
https://github.com/flutter/engine/pull/35409
https://github.com/iskakaushik/flutter_macos_platform_view_example

**Comment by exaby73** [comment] 2022-08-22 09:08
I can reproduce this issue on stable and master. Unfortunately, there is no error logs that show up even when running from Xcode.

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
    • Flutter version 3.0.5 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 104.1.42.97

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2403, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.2403 on channel master at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a10c921aba (3 hours ago), 2022-08-21 23:44:38 -0400
    • Engine revision d311584c79
    • Dart version 2.19.0 (build 2.19.0-120.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 104.1.42.97

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by knopp** [comment] 2022-09-01 13:32
This happens because the view is mutate on raster thread. Should resolved once https://github.com/flutter/flutter/issues/96668 is fixed.

**Comment by knopp** [comment] 2022-09-02 21:34
Closing as duplicate of https://github.com/flutter/flutter/issues/96668.

**Closed by knopp** 2022-09-02 21:34 UTC
Labels: severe: crash, engine, platform-mac, a: platform-views, a: desktop, has reproducible steps, P4, severe: fatal crash, found in release: 3.0, found in release: 3.1
