### ISSUE TITLE
iOS not reproduce m3u8

### ISSUE THREAD

**Issue by jjuandiaz** [flutter/flutter#48546] opened 2020-01-10 01:48 UTC
Is only an issue for me or the player not support this code m3u8 ?

This work fine on android 
Trying this on iPhone device 6s , SE and 8 
The same issue

**Comment by dnfield** [comment] 2020-01-10 04:06
Which player? What version of flutter? What plugin are you using? What's the output of flutter doctor? Where is a reproducible example?

Please feel free to ping this issue if you can update it to add these things - I'm going to close it as either not actionable or a stackoverflow type question for now.  If it turns out there's a bug in a plugin we can reopen.

**Comment by jjuandiaz** [comment] 2020-01-10 11:47
There is the player package video_player 0.10.5+1 link https://pub.dev/packages/video_player
To reproduce the error use an m3u8 link 
And replace bug bunny video 
This source code VideoPlayerController.network(
        'http://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4')

For VideoPlayerController.network(
        'M3U8 VIDEO')
      

Flutter doctor and console debug not show  errors

**Comment by dnfield** [comment] 2020-01-10 15:24
Could you share a m3u8 link that reproduces this?

**Comment by jjuandiaz** [comment] 2020-01-10 15:28
> Could you share a m3u8 link that reproduces this?

try this https://content.uplynk.com/channel/92c7be9fb47143a58683d202e321e571.m3u8

**Comment by jjuandiaz** [comment] 2020-01-23 13:44
Up! 
Any solution about this problem ?

**Comment by TahaTesser** [comment] 2020-03-13 13:17
Related [#48670](https://github.com/flutter/flutter/issues/48670) [#21932](https://github.com/flutter/flutter/issues/21932)  [#35402](https://github.com/flutter/flutter/issues/35402)

**Comment by VladyslavBondarenko** [comment] 2020-04-22 07:39
Closing as duplicate of https://github.com/flutter/flutter/issues/48670
@jjuandiaz please follow up on the issue

**Closed by VladyslavBondarenko** 2020-04-22 07:39 UTC
Labels: a: video, d: stackoverflow, p: first party, p: video_player, platform-ios, plugin
