### ISSUE TITLE
[Desktop, Web] The provided ScrollController is currently attached to more than one ScrollPosition.

### ISSUE THREAD

**Issue by mykdavies** [flutter/flutter#93979] opened 2021-11-20 19:52 UTC
Using an IndexedStack to switch between ListViews works fine in Android emulator, but gives the above error when I run the app as a desktop client in Ubuntu. My understanding is that the IndexedStack should only be exposing the selected child, and so the Android emulator is showing the correct behaviour. Apologies in advance if this is not the case.

### Stripped down code
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ScrollController demo',
      home: MultiProvider(
        providers: [
          ChangeNotifierProvider(create: (context) => TabManager()),
        ],
        child: const Home(),
      ),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  static List<Widget> pages = <Widget>[
    const MyFirstView(),
    const MySecondView(),
  ];

  @override
  Widget build(BuildContext context) {
    return Consumer<TabManager>(
      builder: (context, tabManager, child) {
        return Scaffold(
          appBar: AppBar(
            title: const Text(
              'Scroll list contents to trigger',
            ),
          ),
          // TODO: Replace body: with commented-out version and restart
          // to toggle problem.
          body: IndexedStack(index: tabManager.selectedTab, children: pages),
          // body: pages[tabManager.selectedTab],

          bottomNavigationBar: BottomNavigationBar(
            currentIndex: tabManager.selectedTab,
            onTap: (index) => tabManager.goToTab(index),
            items: const <BottomNavigationBarItem>[
              BottomNavigationBarItem(
                icon: Icon(Icons.arrow_upward),
                label: 'First',
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.arrow_downward),
                label: 'Second',
              ),
            ],
          ),
        );
      },
    );
  }
}

class TabManager extends ChangeNotifier {
  int selectedTab = 0;
  void goToTab(index) {
    selectedTab = index;
    notifyListeners();
  }
}

/// Simulates a slow-building list.
class MyFirstView extends StatelessWidget {
  const MyFirstView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: Future.delayed(const Duration(milliseconds: 2000)),
        builder: (context, AsyncSnapshot s) {
          if (s.connectionState != ConnectionState.done) {
            return const Center(child: CircularProgressIndicator());
          }
          return ListView(
            children:
                Iterable.generate(100, (i) => Text('first slow list - line $i'))
                    .toList(),
          );
        });
  }
}

/// Simulates another slow-building list.
class MySecondView extends StatelessWidget {
  const MySecondView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: Future.delayed(const Duration(milliseconds: 2000)),
        builder: (context, AsyncSnapshot s) {
          if (s.connectionState != ConnectionState.done) {
            return const Center(child: CircularProgressIndicator());
          }
          return ListView(
            children: Iterable.generate(
                100, (i) => Text('second slow list - line $i')).toList(),
          );
        });
  }
}

```
</details>

### Steps to reproduce
Run the above code in the Linux desktop client and attempt to scroll either ListView.

### doctor output
```
$ flutter doctor -v
[✓] Flutter (Channel beta, 2.8.0-3.2.pre, on Ubuntu 20.04.3 LTS
    5.4.0-90-generic, locale en_GB.UTF-8)
    • Flutter version 2.8.0-3.2.pre at /home/jester/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 2901cd7208 (2 days ago), 2021-11-18 11:15:09 -0800
    • Engine revision bcc2b7f12c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jester/Android/Sdk
    • Platform android-31, build-tools 29.0.2
    • Java binary at: /home/jester/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/jester/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS
      5.4.0-90-generic
    • Chrome (web)    • chrome • web-javascript • Chromium 96.0.4664.45 snap

• No issues found!
```

### Stack trace

```console
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1284
#1      RawScrollbarState._debugCheckHasValidScrollPosition
package:flutter/…/widgets/scrollbar.dart:1308
#2      RawScrollbarState._validateInteractions
package:flutter/…/widgets/scrollbar.dart:1223
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners
package:flutter/…/animation/listener_helpers.dart:233
#4      AnimationController._checkStatusChanged
package:flutter/…/animation/animation_controller.dart:815
#5      AnimationController._startSimulation
package:flutter/…/animation/animation_controller.dart:749
#6      AnimationController._animateToInternal
package:flutter/…/animation/animation_controller.dart:612
#7      AnimationController.forward
package:flutter/…/animation/animation_controller.dart:461
#8      RawScrollbarState._handleScrollNotification
package:flutter/…/widgets/scrollbar.dart:1591
#9      NotificationListener._dispatch
package:flutter/…/widgets/notification_listener.dart:151
#10     Notification.visitAncestor
package:flutter/…/widgets/notification_listener.dart:67
#11     ViewportNotificationMixin.visitAncestor
package:flutter/…/widgets/scroll_notification.dart:31
#12     Element.visitAncestorElements
package:flutter/…/widgets/framework.dart:4091
#13     Notification.dispatch
package:flutter/…/widgets/notification_listener.dart:83
#14     ScrollActivity.dispatchScrollUpdateNotification
package:flutter/…/widgets/scroll_activity.dart:94
#15     ScrollPosition.didUpdateScrollPositionBy
package:flutter/…/widgets/scroll_position.dart:900
#16     ScrollPositionWithSingleContext.pointerScroll
package:flutter/…/widgets/scroll_position_with_single_context.dart:221
#17     ScrollableState._handlePointerScroll
package:flutter/…/widgets/scrollable.dart:717
#18     PointerSignalResolver.resolve
package:flutter/…/gestures/pointer_signal_resolver.dart:88
#19     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:445
#20     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:419
#21     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:322
#22     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#23     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338
#24     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:296
#25     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:279
#29     _invoke1 (dart:ui/hooks.dart:169:10)
#30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#31     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 3 frames from dart:async)
The AnimationController notifying status listeners was: AnimationController#adc7f(▶ 0.000)
```

**Comment by maheshmnj** [comment] 2021-11-23 09:44
Hi @mykdavies, Thanks for filing the issue. I was able to reproduce the issue on stable and the master channel on Web and Desktop and works fine on Android. Looks like the same instance of ScrollController is getting attached to both the ListViews.


<details>
<summary>minimal sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'ScrollController demo',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  List<Widget> pages = <Widget>[
    const MyFirstView(),
    const MySecondView(),
  ];

  int currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text(
            'Scroll list contents to trigger',
          ),
        ),
        body: IndexedStack(index: currentIndex, children: pages),
        bottomNavigationBar: BottomNavigationBar(
          currentIndex: currentIndex,
          onTap: (index) {
            setState(() {
              currentIndex = index;
            });
          },
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.arrow_upward),
              label: 'First',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.arrow_downward),
              label: 'Second',
            ),
          ],
        ));
  }
}

/// Simulates a slow-building list.
class MyFirstView extends StatelessWidget {
  const MyFirstView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView(
      // controller: ScrollController(), /// adding a scrollController fixes this issue
      children: Iterable.generate(100, (i) => Text('first slow list - line $i'))
          .toList(),
    );
  }
}

/// Simulates another slow-building list.
class MySecondView extends StatelessWidget {
  const MySecondView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: Iterable.generate(50, (i) => Text('first slow list - line $i'))
          .toList(),
    );
  }
}

```
</details>

<details>
<summary>logs</summary>

```console
Restarted application in 329ms.

════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure>
#1      RawScrollbarState._debugCheckHasValidScrollPosition
#2      RawScrollbarState._validateInteractions
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners
#4      AnimationController._checkStatusChanged
#5      AnimationController._startSimulation
#6      AnimationController._animateToInternal
#7      AnimationController.forward
#8      RawScrollbarState._handleScrollNotification
#9      NotificationListener._dispatch
#10     Notification.visitAncestor
#11     ViewportNotificationMixin.visitAncestor
#12     Element.visitAncestorElements
#13     Notification.dispatch
#14     ScrollActivity.dispatchScrollUpdateNotification
#15     ScrollPosition.didUpdateScrollPositionBy
#16     ScrollPositionWithSingleContext.pointerScroll
#17     ScrollableState._handlePointerScroll
#18     PointerSignalResolver.resolve
#19     GestureBinding.handleEvent
#20     GestureBinding.dispatchEvent
#21     RendererBinding.dispatchEvent
#22     GestureBinding._handlePointerEventImmediately
#23     GestureBinding.handlePointerEvent
#24     GestureBinding._flushPointerEventQueue
#25     GestureBinding._handlePointerDataPacket
#29     _invoke1 (dart:ui/hooks.dart:170:10)
#30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#31     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
The AnimationController notifying status listeners was: AnimationController#e1c49(▶ 0.000)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
The provided ScrollController is currently attached to more than one ScrollPosition.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
The provided ScrollController is currently attached to more than one ScrollPosition.
════════════════════════════════════════════════════════════════════════════════
```
</details>



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.790, on Ubuntu 20.04.3 LTS 5.11.0-40-generic, locale en_GB.UTF-8)
    • Flutter version 2.6.0-12.0.pre.790 at /home/mahesh/Development/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a18e6ee42 (24 hours ago), 2021-11-22 13:01:00 +0300
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)         • linux         • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-40-generic
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```

```
mahesh@mahesh:~/Desktop/hello$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-40-generic, locale en_GB.UTF-8)
    • Flutter version 2.5.3 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)         • linux         • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-40-generic
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 96.0.4664.45

• No issues found!
```
</details>

**Comment by mykdavies** [comment] 2021-11-23 16:07
Thanks for the confirmation and for tidying up the description @maheshmnj, I'll leave it to you guys now :-)

**Comment by xu-baolin** [comment] 2021-11-24 09:20
The root cause of the problem is that the two lists use the same default PrimaryScrollController, and the interaction of the scrollbar is enabled by default on the Windows platform, so the assertion is triggered.
Solution:
By customizing MaterialApp.scrollBehavior to not show the bar. If you need to display the bar, you need to introduce the Scrollbar widgets explicitly, 

CC @Piinks This assertion is too easy to trigger on windows if the app has more than one scrollable widget.

**Comment by TahaTesser** [comment] 2021-11-24 10:07
duplicate of https://github.com/flutter/flutter/issues/88428

**Closed by TahaTesser** 2021-11-24 10:07 UTC
Labels: framework, f: scrolling, platform-web, a: desktop, has reproducible steps, found in release: 2.5, found in release: 2.6, found in release: 2.8

**Comment by mykdavies** [comment] 2021-11-26 13:23
Hi @TahaTesser, thanks for the reference to the other issue. Can I just confirm my understanding here? The reason that this causes an error on desktop platforms is that the Flutter code for desktop has been written differently in order to support those desktop environments where the scrollbar is always displayed (eg Windows), and that this requires all ListViews to maintain a reference to their ScrollController, even when these ListViews are not visible.

Do you happen to know if there's somewhere where any such differences are publicly documented? (e.g. something like https://docs.flutter.dev/resources/platform-adaptations but for desktop).
