### ISSUE TITLE
The method 'call' was called on null. Using AutoCompleteTextField

### ISSUE THREAD

**Issue by razdahan** [flutter/flutter#33723] opened 2019-06-02 10:02 UTC
This is my file called ViewReview It should take the driving instructors names from the firestore and then isert them to autocompletetextfield so user can see which instructors are available.
But every time I start typing in the auto complete text field i get this error
```
I/flutter ( 2422): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter ( 2422): The following NoSuchMethodError was thrown while dispatching notifications for FocusNode:
I/flutter ( 2422): The method 'call' was called on null.
I/flutter ( 2422): Receiver: null
I/flutter ( 2422): Tried calling: call(true)
I/flutter ( 2422): When the exception was thrown, this was the stack:
I/flutter ( 2422): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 2422): #1      new AutoCompleteTextFieldState.<anonymous closure> (package:autocomplete_textfield/autocomplete_textfield.dart:182:4)
I/flutter ( 2422): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
I/flutter ( 2422): #3      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:103:5)
I/flutter ( 2422): #4      FocusManager._update (package:flutter/src/widgets/focus_manager.dart:474:20)
I/flutter ( 2422): (elided 10 frames from package dart:async)
I/flutter ( 2422): The FocusNode sending notification was:
I/flutter ( 2422):   FocusNode#965e3(FOCUSED)
I/flutter ( 2422): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

This is my code

```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:main/Pages/Home.dart';
import 'package:main/Pages/Setup/SignIn.dart';
import 'package:main/Pages/Setup/Welcome.dart';
import "package:autocomplete_textfield/autocomplete_textfield.dart";

class ViewReview extends StatefulWidget {
  @override
  _ViewReviewState createState() => _ViewReviewState();

  const ViewReview({Key key, this.user}) : super(key: key);
  final FirebaseUser user;
}

class DrivingInstructor {
  const DrivingInstructor(
      {@required this.phone_number,
      @required this.name,
      @required this.price,
      @required this.test_area});

  final String test_area;
  final String price;
  final String name;
  final String phone_number;

  Map<String, dynamic> toJson() => {
        'phone_number': phone_number,
        'price': price,
        'name': name,
        'test_area': test_area
      };
}

class _ViewReviewState extends State<ViewReview> {
  AutoCompleteTextField search;
  GlobalKey<AutoCompleteTextFieldState<DrivingInstructor>> key =
      new GlobalKey();
  String _InstructorName, _AuthornName, _Text;
  bool InstructorNameValidator;
  int _Rating;
  static List<DrivingInstructor> Inst = new List<DrivingInstructor>();
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  bool loading = true;
  void getInstructors() async {
    final QuerySnapshot result = await Firestore.instance
        .collection('DrivingInstructors')
        .getDocuments();
    final List<DocumentSnapshot> documents = result.documents;
    Inst = new List<DrivingInstructor>();

    for (int i = 0; i < documents.length; i++) {
      DrivingInstructor d = new DrivingInstructor(
          phone_number: documents[i].data['phone_number'],
          name: documents[i].data['name'],
          price: documents[i].data['price'],
          test_area: documents[i].data['test_area']);
      print('asdasdasdsadsadasdasdasdas');
      Inst.add(d);
    }
    setState(() {
      loading = false;
    });
  }

  @override
  void initState() {
    getInstructors();
  }

  Widget row(DrivingInstructor d) {
    return Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Text(
            d.name,
            style: TextStyle(fontSize: 16.0),
          ),
          Padding(
            padding: EdgeInsets.all(15.0),
          ),
          Text(
            d.test_area,
          )
        ]);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('חפש ביקורות על מורה'),
        ),
        body: Form(
            key: _formKey,
            child: Column(
              children: <Widget>[
                loading
                    ? LinearProgressIndicator()
                    : search = AutoCompleteTextField<DrivingInstructor>(
                        clearOnSubmit: false,
                        key: key,
                        suggestions: Inst,
                        style: TextStyle(color: Colors.black, fontSize: 16.0),
                        decoration: InputDecoration(
                          contentPadding:
                              EdgeInsets.fromLTRB(10.0, 30.0, 10.0, 20.0),
                          hintText: "חפש מורה",
                          hintStyle: TextStyle(color: Colors.black),
                        ),
                        itemFilter: (item, query) {
                          return item.name.startsWith(query);
                        },
                        itemSorter: (a, b) {
                          return a.name.compareTo(b.name);
                        },
                        itemSubmitted: (item) {
                          setState(() {
                            search.textField.controller.text = item.name;
                          });
                        },
                        itemBuilder: (context, item) {
                          return row(item);
                        },
                      )
              ],
            )));
  }
}
```

**Comment by renatopastor1** [comment] 2019-06-05 16:57
Same here, any solutions?

**Comment by renatopastor1** [comment] 2019-06-05 18:13
Found a solution, the problem is with the focus node 

You just need to add:
onFocusChanged: (hasFocus) {},
to AutoCompleteTextField

**Comment by iapicca** [comment] 2019-10-08 15:34
Hi @razdahan 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`

**Comment by iapicca** [comment] 2019-11-08 12:28
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 12:28 UTC
Labels: waiting for customer response

**Comment by praharshbhatt** [comment] 2020-01-06 08:45
I am having the same issue.

Code:
```//Search
                FutureBuilder(
                  builder: (BuildContext context, AsyncSnapshot snapshot) {
                    if (snapshot == null || snapshot.data == null || snapshot.hasData == false) {
                      return Center(
                        child: CircularProgressIndicator(
                          valueColor: AlwaysStoppedAnimation<Color>(Colors.green),
                          strokeWidth: 5,
                        ),
                      );
                    } else {
                      return Container(
                        color: Colors.white,
                        child: Padding(
                          padding: const EdgeInsets.fromLTRB(10, 10, 10, 0),
                          child: AutoCompleteTextField<CustomerList>(
                            decoration:
                                new InputDecoration(hintText: "Search Customers:", prefixIcon: new Icon(Icons.search)),
                            itemSubmitted: (item) {
                              setState(() {
                                //Update the _selectedCustomer
                                _selectedCustomer = item;

                                //Update the Name and Phone number fields of the text fields
                                _tecName.text = _selectedCustomer.strFirstName;
                                _tecPhoneNumber.text = _selectedCustomer.strPhoneNumber;
                              });
                            },
                            key: _searchKey,
                            onFocusChanged: (hasFocus) {},
                            suggestions: _lstCustomerList,
                            itemBuilder: (context, suggestion) => Padding(
                                child: new ListTile(
                                    title: new Text(suggestion.strFirstName + " " + suggestion.strLastName),
                                    trailing: new Text("Phone: ${suggestion.strPhoneNumber}")),
                                padding: EdgeInsets.all(8.0)),
                            itemSorter: (a, b) => a.strFirstName == b.strFirstName
                                ? 0
                                : a.strFirstName.compareTo(b.strPhoneNumber) > 0 ? -1 : 1,
                            itemFilter: (suggestion, input) =>
                                suggestion.strFirstName.toLowerCase().startsWith(input.toLowerCase()),
                          ),
                        ),
                      );
                    }
                  },
                  future: getCustomerList(),
                ),
```



Error:

```E/flutter (13153): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (13153): Receiver: null
E/flutter (13153): Tried calling: call("")
E/flutter (13153): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (13153): #1      getTextFormFieldLogin.<anonymous closure> (package:wizpay_merchant/widgets/form.dart:43:36)
E/flutter (13153): #2      FormFieldState._validate (package:flutter/src/widgets/form.dart)
E/flutter (13153): #3      FormFieldState.validate.<anonymous closure> (package:flutter/src/widgets/form.dart:370:7)
E/flutter (13153): #4      State.setState (package:flutter/src/widgets/framework.dart:1164:30)
E/flutter (13153): #5      FormFieldState.validate (package:flutter/src/widgets/form.dart:369:5)
E/flutter (13153): #6      FormState._validate (package:flutter/src/widgets/form.dart:209:25)
E/flutter (13153): #7      FormState.validate (package:flutter/src/widgets/form.dart:203:12)
E/flutter (13153): #8      _CreateLinkScreenState.build.<anonymous closure> (package:wizpay_merchant/screens/Create_Links/create_link.dart:338:56)
E/flutter (13153): #9      primaryRaisedButton.<anonymous closure> (package:wizpay_merchant/widgets/buttons.dart:58:33)
E/flutter (13153): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:705:14)
E/flutter (13153): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:788:36)
E/flutter (13153): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (13153): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (13153): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (13153): #15     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (13153): #16     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (13153): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (13153): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (13153): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (13153): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (13153): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (13153): #22     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (13153): #23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (13153): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (13153): #25     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (13153): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (13153): 
```

**Comment by iapicca** [comment] 2020-01-10 10:14
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by jhwsx** [comment] 2020-06-02 08:40
```
Waiting for H60 L01 to report its views...                           8ms
I/flutter (24268): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (24268): The following NoSuchMethodError was thrown attaching to the render tree:
I/flutter (24268): The method '_debugTypesAreRight' was called on null. 
I/flutter (24268): Receiver: null                                       
I/flutter (24268): Tried calling: _debugTypesAreRight(Instance of 'MyApp')
I/flutter (24268): When the exception was thrown, this was the stack:   
I/flutter (24268): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (24268): #1      new StatefulElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:4598:19)
I/flutter (24268): #2      new StatefulElement (package:flutter/src/widgets/framework.dart:4609:6)
I/flutter (24268): #3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:894:38)
I/flutter (24268): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3445:40)
I/flutter (24268): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
I/flutter (24268): #6      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1132:16)
I/flutter (24268): #7      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1103:5)
I/flutter (24268): #8      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1045:17)
I/flutter (24268): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter (24268): #10     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1044:13)
I/flutter (24268): #11     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:925:7)
I/flutter (24268): #12     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
I/flutter (24268): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (24268): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device H60 L01...                                 409ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on H60 L01 is available at: http://127.0.0.1:44357/nQrJLhw1Zcs=/
D/KeyEvent(24268): obtain, mHwFlags=-1697920983
D/KeyEvent(24268): obtain, mHwFlags=-1697920983
W/InputMethodManager(24268): Current bind isn't success!
Lost connection to device.
(base) wzc@wzc:~/AndroidStudioProjects/FlutterInAction/stateful_widget_demo$ 
(base) wzc@wzc:~/AndroidStudioProjects/FlutterInAction/stateful_widget_demo$ 
(base) wzc@wzc:~/AndroidStudioProjects/FlutterInAction/stateful_widget_demo$ flutter doctor -v
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.18.0-11.1.pre at /home/wzc/develop/flutter
    • Framework revision 2738a1148b (3 周前), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/wzc/AndroidSDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/wzc/AndroidSDK
    • Java binary at: /home/wzc/develop/Android/android-studio-361/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/wzc/develop/Android/android-studio-361
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • H60 L01    • 7N2SSE155U004832 • android-arm    • Android 6.0 (API 23)
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 81.0.4044.122
```

**Comment by B-Houssam** [comment] 2020-06-20 18:18
you need to assign the global key to the scaffold key propriety
     key : "your scaffold key",
     body: ......

**Comment by MenachemMaron** [comment] 2020-08-11 04:49
> you need to assign the global key to the scaffold key propriety
> key : "your scaffold key",
> body: ......

How do I find the key?
