### ISSUE TITLE
Webview_flutter is supported on MACOS and Windows desktops

### ISSUE THREAD

**Issue by qinuoyun** [flutter/flutter#95666] opened 2021-12-22 09:28 UTC
Webview_flutter is supported on MACOS and Windows desktops

**Comment by darshankawar** [comment] 2021-12-22 09:33
Closing as duplicate of:

https://github.com/flutter/flutter/issues/37597
https://github.com/flutter/flutter/issues/41725

**Closed by darshankawar** 2021-12-22 09:33 UTC
Labels: in triage
