### ISSUE TITLE
App crash on windows 7 64bit but works fine in win 10

### ISSUE THREAD

**Issue by anandsubbu007** [flutter/flutter#70807] opened 2020-11-19 02:21 UTC
![WhatsApp Image 2020-11-19 at 7 53 25 AM](https://user-images.githubusercontent.com/55450843/99614059-b781ad00-2a3e-11eb-9ad0-df304b1b3db6.jpeg)

I build windows with sample app on windows 10 device. It is working fine in windows 10. 
But when I try to open build app in windows 7 64 bit ultimate SP1 the app crash. It is not even showing error.

**Comment by sidrao2006** [comment] 2020-11-19 04:01
Hello @anandsubbu007 ,
Could you please post the outputs of `flutter run -v` and `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by anandsubbu007** [comment] 2020-11-19 09:15
```[√] Flutter (Channel dev, 1.24.0-10.1.pre, on Microsoft Windows [Version 10.0.19041.630], locale en-IN)
    • Flutter version 1.24.0-10.1.pre at C:\Flutter Components\flutter
    • Framework revision 405c85fe7e (5 days ago), 2020-11-13 21:22:10 -0800
    • Engine revision bd390c0310
    • Dart version 2.12.0 (build 2.12.0-29.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\anand\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\anand\AppData\Local\Android\Sdk
    • Java binary at: C:\Flutter Components\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.6)
    • Android Studio at C:\Flutter Components\Android Studio
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\anand\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.193
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.69

• No issues found!
```

```import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by hamdikahloun** [comment] 2020-11-19 10:26
Related Issue https://github.com/flutter/flutter/issues/61703

**Comment by hamdikahloun** [comment] 2020-11-19 10:27
Related Issue https://github.com/flutter/flutter/issues/61703 (Closed)

**Comment by hamdikahloun** [comment] 2020-11-19 10:29
Hi @anandsubbu007 @stuartmorgan 



## Steps to Reproduce



1. Run `flutter create bug`.
2. Run `flutter build windows`.
3. Start the application in Windows 7 X64 Clean Install (Other Machine) | Visual C++ Redistributable Packages installed

**Expected results:** Application Start

**Actual results:** Crash

<details>
  <summary>Logs Machine Dev</summary>



```
flutter doctor -v
[√] Flutter (Channel dev, 1.23.0-18.0.pre, on Microsoft Windows [version 10.0.19041.630], locale fr-FR)
    • Flutter version 1.23.0-18.0.pre at D:\fork\flutter
    • Framework revision 37ebe3d82a (5 weeks ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\hamdi\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\hamdi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30225.117
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\hamdi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [version 10.0.19041.630]

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment] 2020-11-19 16:28
Per my comment in the issue referenced above, we need crash logs to make progress here. Without that, we don't know what the cause of this issue is, or if it is actually related to any other crash issue.

**Comment by anandsubbu007** [comment] 2020-11-19 17:00
Here is the Dump file of sample flutter windows app from win 7 64bit.
may I know, How to create a crash log? i tried 
https://github.com/flutter/flutter/issues/61703#issuecomment-664505737
this but I can't able to find logs
https://drive.google.com/file/d/1NOdJXnpXyvtu0BhfEdS1NjhsCAdWypmy/view?usp=sharing

**Comment by anandsubbu007** [comment] 2020-11-21 09:16
any update

**Comment by callmemc** [comment] 2020-11-22 03:58
I am also seeing the same exact issue with the same exact error logs as @anandsubbu007

**Comment by stuartmorgan** [comment] 2020-11-25 21:39
I'll see if I can get a symbolicated stack from the dump file.

**Comment by callmemc** [comment] 2020-11-27 20:43
@stuartmorgan sweet does that mean you were able to reproduce the issue?

**Comment by leielyq** [comment] 2020-12-27 08:29
Me too.May be about gpu.

**Comment by stuartmorgan** [comment] 2021-01-13 16:27
> Here is the Dump file of sample flutter windows app from win 7 64bit.

That file is no longer available for download; can you either re-post it, or if you no longer have it, generate a new dump and post it? I'd like to try to symbolicate it (as mentioned above; unfortunately I was out for about a month and only just now have had time to get back to this).

**Comment by stuartmorgan** [comment] 2021-01-13 16:29
(Alternately, if anyone else who can repro wants to post a dump file I can look at that. Just be sure to provide your `flutter doctor -v` output so I have the exact engine hash you used to build it.)

**Comment by anandsubbu007** [comment] 2021-01-14 03:30
> > Here is the Dump file of sample flutter windows app from win 7 64bit.
> 
> That file is no longer available for download; can you either re-post it, or if you no longer have it, generate a new dump and post it? I'd like to try to symbolicate it (as mentioned above; unfortunately I was out for about a month and only just now have had time to get back to this).

Please check that drive link again

**Comment by stuartmorgan** [comment] 2021-01-14 17:57
This is a duplicate of https://github.com/flutter/flutter/issues/51286; it's not crashing, but aborting on the `gl_version_string` check.

Please provide the output from `dxdiag` from the failing machine here, as we are collecting data about video card/drivers that aren't currently supported by Flutter applications.

**Closed by stuartmorgan** 2021-01-14 17:57 UTC
Labels: P3, a: desktop, e: OS Version specific, engine, passed first triage, platform-windows, severe: crash
