### ISSUE TITLE
PageView null operator error

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#105037] opened 2022-05-31 17:31 UTC
## Steps to Reproduce

I do not know how to reproduce the problem. It comes from crashlytics.

<details>
  <summary>StackTrace from crashlytics</summary>

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at _PagePosition.applyViewportDimension(page_view.dart:455)
       at RenderViewport.performLayout(viewport.dart:1456)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderCustomPaint.performLayout(custom_paint.dart:545)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at MultiChildLayoutDelegate.layoutChild(custom_layout.dart:171)
       at _ScaffoldLayout.performLayout(scaffold.dart:1003)
       at MultiChildLayoutDelegate._callPerformLayout(custom_layout.dart:240)
       at RenderCustomMultiChildLayoutBox.performLayout(custom_layout.dart:403)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at _RenderCustomClip.performLayout(proxy_box.dart:1376)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderOffstage.performLayout(proxy_box.dart:3462)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at _RenderTheatre.performLayout(overlay.dart:749)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderProxyBoxMixin.performLayout(proxy_box.dart:116)
       at RenderObject.layout(object.dart:1915)
       at RenderView.performLayout(view.dart:165)
       at RenderObject._layoutWithoutResize(object.dart:1757)
       at PipelineOwner.flushLayout(object.dart:887)
       at RendererBinding.drawFrame(binding.dart:504)
       at WidgetsBinding.drawFrame(binding.dart:892)
       at RendererBinding._handlePersistentFrameCallback(binding.dart:370)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1146)
       at SchedulerBinding.handleDrawFrame(binding.dart:1083)
       at SchedulerBinding._handleDrawFrame(binding.dart:997)
```

</details>

The error concerns this line : 

```
else if (oldViewportDimensions == 0.0) {
      // If resize from zero, we should use the _cachedPage to recover the state.
      page = _cachedPage!;
}
```
`_cachedPage` is set to null if `viewportDimension` is 0. So if `applyViewportDimension()` is called twice with this being 0, you'll get an error as `oldViewportDimensions` would be 0 the second time and `_cachedPage` having been set to null.

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [version 10.0.19044.1706], locale fr-BE)
    • Flutter version 3.0.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\me\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.67.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (2 available)
    • SM A750FN (mobile) • 32005e294fcf368d • android-arm64 • Android 10 (API 29)
    • Windows (desktop)  • windows          • windows-x64   • Microsoft Windows [version 10.0.19044.1706]

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2022-06-01 05:17
Closing this as duplicate of https://github.com/flutter/flutter/issues/101007. There's an open PR to fix this that you can subscribe to for further update : https://github.com/flutter/flutter/pull/104405

**Closed by darshankawar** 2022-06-01 05:17 UTC
Labels: in triage
