### ISSUE TITLE
Memory regression diff-maxend-maxend-medianend-min flutter_gallery__back_button_memory

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#68315] opened 2020-10-16 16:18 UTC
See https://flutter-flutter-perf.skia.org/e/?begin=1602714272&end=1602741425&keys=X0394285421bc8feb15fab9583133b561&num_commits=50&request_type=1&xbaroffset=22015. Pretty clear signal.

Looks like commit https://github.com/flutter/flutter/pull/68148.

**Comment by gaaclarke** [comment] 2020-10-16 17:14
That engine roll contains 3 commits: one affects the linter, one affects vulkan, the other affects android.  The regressing test is running on android without vulkan which means the regression should have appeared in flutter/engine#21839.  @iskakaushik is it expected that that commit should increase resident memory by ~10,000 KB?

**Comment by jason-simmons** [comment] 2020-10-16 18:40
If I repeatedly suspend and resume Gallery and then run `adb shell dumpsys meminfo` I'm seeing the Native Heap metric increase by around 1MB on each cycle.

It looks like that started with https://github.com/flutter/engine/pull/21839

**Comment by gaaclarke** [comment] 2020-10-16 23:57
https://github.com/flutter/engine/pull/21918  Landed, we'll wait until the numbers drop before we close this.

**Comment by chinmaygarde** [comment] 2020-10-19 17:35
Jason is confident the revert will fix the issue.

**Comment by gaaclarke** [comment] 2020-10-19 17:55
https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3Dend-max%26test%3Dflutter_gallery__back_button_memory

This change rolled to the engine and there was a drop in the memory usage.
end-max went from 63122KB to 55149KB
The regression was 49693KB to 60917KB

Considering the matter closed, thanks @jason-simmons

**Closed by gaaclarke** 2020-10-19 17:55 UTC
Labels: P0, engine, passed first triage, perf: memory, severe: performance, severe: regression, team: benchmark
