### ISSUE TITLE
Flutter tests do not start

### ISSUE THREAD

**Issue by mreichelt** [flutter/flutter#60519] opened 2020-06-29 13:20 UTC
## Steps to Reproduce

1. Create new Flutter application with Android Studio 4.0 and Flutter 1.17.4 stable (on MacOS 10.15.5)
2. Create new run config (Flutter Test, 'All in directory', choose 'test' directory from project)
3. Run that run config with the 'Run' icon (Ctrl + R on Mac)

Then, you will see this for a couple of minutes (the warning itself seems to have nothing to do with it):
![image](https://user-images.githubusercontent.com/400322/86010133-456ee400-ba1b-11ea-9696-bd244252ce22.png)

After that, the test suite will fail:

## Logs

```
Testing started at 15:09 ...
/Users/mreichelt/bin/flutter/bin/flutter --no-color test --machine --start-paused test
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.


dart:async/stream_controller.dart 609:43                       _StreamController.addError
dart:async/stream_controller.dart 877:13                       _StreamSinkWrapper.addError
package:stream_channel/src/guarantee_channel.dart 144:14       _GuaranteeSink._addError
package:stream_channel/src/guarantee_channel.dart 135:5        _GuaranteeSink.addError
package:flutter_tools/src/test/flutter_platform.dart 570:27    FlutterPlatform._startTest
===== asynchronous gap ===========================
dart:async/zone.dart 1109:19                                   _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 79:23                        _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart 359:36    FlutterPlatform.loadChannel
package:flutter_tools/src/test/flutter_platform.dart 312:46    FlutterPlatform.load
package:test_core/src/runner/loader.dart 232:38                Loader.loadFile.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1109:19                                   _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 79:23                        _asyncThenWrapperHelper
package:test_core/src/runner/loader.dart                       Loader.loadFile.<fn>
package:test_core/src/runner/load_suite.dart 98:31             new LoadSuite.<fn>.<fn>
package:test_core/src/runner/load_suite.dart 108:8             new LoadSuite.<fn>
package:test_api/src/backend/invoker.dart 400:30               Invoker._onRun.<fn>.<fn>.<fn>.<fn>
dart:async/future.dart 176:37                                  new Future.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1180:38                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1003:23                                   _CustomZone.bindCallback.<fn>
dart:async-patch/timer_patch.dart 23:15                        Timer._createTimer.<fn>
dart:isolate-patch/timer_impl.dart 398:19                      _Timer._runTimers
dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 1101:19                                   _CustomZone.registerCallback
dart:async/zone.dart 1018:22                                   _CustomZone.bindCallbackGuarded
dart:async/timer.dart 54:45                                    new Timer
dart:async/timer.dart 91:9                                     Timer.run
dart:async/future.dart 174:11                                  new Future
package:test_api/src/backend/invoker.dart 399:21               Invoker._onRun.<fn>.<fn>.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1619:10                                   _runZoned
dart:async/zone.dart 1539:10                                   runZoned
package:test_api/src/backend/invoker.dart 387:9                Invoker._onRun.<fn>.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1619:10                                   _runZoned
dart:async/zone.dart 1539:10                                   runZoned
package:test_api/src/backend/invoker.dart 148:7                Invoker.guard
package:test_api/src/backend/invoker.dart 436:15               Invoker._guardIfGuarded
package:test_api/src/backend/invoker.dart 386:7                Invoker._onRun.<fn>
package:stack_trace/src/chain.dart 101:24                      Chain.capture.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1619:10                                   _runZoned
dart:async/zone.dart 1539:10                                   runZoned
package:stack_trace/src/chain.dart 99:12                       Chain.capture
package:test_api/src/backend/invoker.dart 385:11               Invoker._onRun
package:test_api/src/backend/live_test_controller.dart 197:11  LiveTestController._run
package:test_api/src/backend/live_test_controller.dart 50:37   _LiveTest.run
dart:async/future.dart 202:37                                  new Future.microtask.<fn>
dart:async/zone.dart 1180:38                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 43:21                       _microtaskLoop
dart:async/schedule_microtask.dart 52:5                        _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 169:5                    _RawReceivePortImpl._handleMessage

Failed to load "/Users/mreichelt/Projects/other/flutter_issue_tests_hang/flutter_app/test/widget_test.dart":
Test never connected to test harness.
Test: /Users/mreichelt/Projects/other/flutter_issue_tests_hang/flutter_app/test/widget_test.dart
Shell: /Users/mreichelt/bin/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester
```

The same will happen if you right-click on `widget_test.dart` and select the Flutter tests.
But: if you **debug** the same file, the tests will start and run just fine.

`flutter doctor -v` prints:

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale de-DE)
    • Flutter version 1.17.4 at /Users/mreichelt/bin/flutter
    • Framework revision 1ad9baa8b9 (12 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/mreichelt/bin/android-sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/mreichelt/bin/android-sdk
    • Java binary at: /Users/mreichelt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/mreichelt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[redacted]

[✓] Connected device (1 available)
[redacted]

! Doctor found issues in 2 categories.
```

**Comment by VladyslavBondarenko** [comment] 2020-06-29 15:05
Hi @mreichelt 
Is it indeed new project?
I tried to follow this

>Create new Flutter application with Android Studio 4.0 and Flutter 1.17.4 stable (on MacOS 10.15.5)
Create new run config (Flutter Test, 'All in directory', choose 'test' directory from project)
Run that run config with the 'Run' icon (Ctrl + R on Mac)

but couldn't reproduce
![image](https://user-images.githubusercontent.com/17024977/86022069-89b9ae80-ba32-11ea-93eb-1ffc9f7f2cba.png)

**Comment by jonasanker** [comment] 2020-06-29 17:59
I'm getting the same issue as here and as another used reported in #60512 . In my case the issue started after I upgraded the Flutter plugin (to version 47.0.2) this weekend. 

I can reproduce it in both and existing project (see [CoffeeCard repository](https://github.com/AnalogIO/coffeecard_app/tree/feature/jonas/repository-tests)) or when creating a new project.

**Comment by jonasanker** [comment] 2020-06-29 18:09
Seems to be addressed (and solved in) https://github.com/flutter/flutter-intellij/issues/4666. Temporary workaround is to downgrade the Flutter plugin to a previous version

**Comment by VladyslavBondarenko** [comment] 2020-06-30 07:19
@jonasanker Thanks! I see, I had previous flutter plugin version. And yes, I'm experiencing the error after upgrade to 47.0.2.
Please who are experiencing this use v46 until new version is released https://github.com/flutter/flutter-intellij/pull/4622#issuecomment-651252966.
Closing as issue with flutter-intellij plugin and not with flutter itself, follow up on https://github.com/flutter/flutter-intellij/pull/4622

**Closed by VladyslavBondarenko** 2020-06-30 07:19 UTC
Labels: in triage, waiting for customer response
