### ISSUE TITLE
Add2App: cocopods: Failed to find assets path

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#63134] opened 2020-08-06 21:37 UTC
I ran through the documentation in (Option A):
https://flutter.dev/docs/development/add-to-app/ios/project-setup

The application links and executes but the following error is given when trying to launch the flutter engine:
```
2020-08-06 14:29:49.311338-0700 GiantsA2A[97957:8631425] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
2020-08-06 14:29:49.344677-0700 GiantsA2A[97957:8631722] [VERBOSE-2:engine.cc(135)] Engine run configuration was invalid.
2020-08-06 14:29:49.344873-0700 GiantsA2A[97957:8631722] [VERBOSE-2:shell.cc(487)] Could not launch engine with configuration.
2020-08-06 14:29:49.403579-0700 GiantsA2A[97957:8631739] flutter: Observatory listening on http://127.0.0.1:60681/wsj8jKvfEE8=/
```

**Comment by gaaclarke** [comment] 2020-08-06 21:39
Changing the channel of my flutter installation seemed to flush out the problem: `flutter channel master`

**Comment by gaaclarke** [comment] 2020-08-06 21:40
@jmagman I'm not sure if this makes sense to you, feel free to close it out if you can't find something actionable.

**Comment by jmagman** [comment] 2020-08-06 23:38
Do you know what version of Flutter you were using before?  That error looks like the App.framework wasn't embedded.

**Comment by gaaclarke** [comment] 2020-08-06 23:42
I was at `30aef0a3b9611763f8e60985e7cca9cb30c1ea6a`

**Comment by KevinTheGray** [comment] 2020-08-10 18:25
I'm seeing a similar issue after we tried to upgrade from `beta` `1.19.0-4.1.pre` to `stable` `1.20.1`

The error is 
```
❌  ld: framework not found App

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Is this related to: https://github.com/flutter/flutter/issues/32454?   Is there a problem with moving from using the `beta` channel to the `stable` channel?  The reason we want to move to stable is because it's currently newer than the latest `beta` branch

**Comment by jmagman** [comment] 2020-08-12 16:49
I think this is a duplicate of https://github.com/flutter/flutter/issues/63176.  PR at https://github.com/flutter/flutter/pull/63412.

**Closed by jmagman** 2020-08-12 16:49 UTC
Labels: tool
