### ISSUE TITLE
Scrollbar stutter on basic ListView!!

### ISSUE THREAD

**Issue by GeylanKalafMohe** [flutter/flutter#132216] opened 2023-08-09 12:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use`Scrollbar` view with a `ListView` widget containing 200 basic items
2. Scroll fast or little bit slower and you will see the stutter of the scrollbar on the right side.

### Expected results

No Stutter should happen

### Actual results

Scrollbar is hardly stuttering. The more widgets each item has it gets worse.

### Code sample

<details><summary>Code sample</summary>

```dart
final controller = ScrollController();

Scaffold(
      appBar: AppBar(title: const Text('Scrollbar stutter issue!!')),
      body: Scrollbar(
        controller: controller,
        child: ListView.separated(
          controller: controller,
          separatorBuilder: (BuildContext context, int index) =>
              const Divider(),
          itemCount: 200,
          itemBuilder: (BuildContext context, int index) {
            return Column(
              children: [
                const SizedBox(
                  height: 10,
                ),
                Text(
                  'See Scrollbar, index: $index',
                ),
                const SizedBox(
                  height: 10,
                ),
              ],
            );
          },
        ),
      ),
    );
```

</details>

### Screenshots or Video

<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/42656134/325e8ba0-f584-401e-aac1-13e2aeacf52d

### Flutter Doctor output

<summary>Doctor output</summary>

```console
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (4 weeks ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.3.1 22E772610a darwin-x64, locale en-SA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

**Comment by dam-ease** [comment] 2023-08-09 13:23
Hi @GeylanKalafMohe. Thanks for filing this issue. I can almost not reproduce testing with iPhone 14 (iOS 16.4) both on the master and stable channels but can still see a little pause

https://github.com/flutter/flutter/assets/53122008/65941ab7-7139-4f26-a427-5b8fd62264b1

Thanks for your input @moffatman. Awaiting your response per https://github.com/flutter/flutter/issues/132216#issuecomment-1671304046

**Comment by dam-ease** [comment] 2023-08-10 09:11
Thanks for your response @GeylanKalafMohe. I am able to reproduce this on the latest `master` and `stable` channels quite evidently on iOS. Although the stutter on Android as well doesn't seem too noticeable. Can you please test on Android to see if it reproduces?

[untitled.webm](https://github.com/flutter/flutter/assets/53122008/50ff549d-748e-44dc-9c58-9c00ec530271)

**Comment by GeylanKalafMohe** [comment] 2023-08-10 10:28
> Thanks for your response @GeylanKalafMohe. I am able to reproduce this on the latest `master` and `stable` channels quite evidently on iOS. Although the stutter on Android as well doesn't seem too noticeable. Can you please test on Android to see if it reproduces?
> 
>  untitled.webm

The same issue happens on Android as well. As I said the more complex each list item is the more noticeable it will be even with less list item count.

**Comment by moffatman** [comment] 2023-08-10 13:48
It doesn't have to do with list item complexity, but rather the difference in height

**Comment by GeylanKalafMohe** [comment] 2023-08-10 13:52
> It doesn't have to do with list item complexity, but rather the difference in height

Could be most probably. The question is why does it happen 🤔 It should be fixed soon by the Flutter team as it impacts all Flutter apps.

**Comment by moffatman** [comment] 2023-08-10 14:32
It's because the component which estimates the height of the scrolling widget, doesn't have all the information about the list that you give to ListView. And doesn't do any caching, which means as items appear and disappear off the top of the screen, the estimate changes rapidly.

**Comment by GeylanKalafMohe** [comment] 2023-08-16 05:51
@dam-ease @moffatman Yeah but when there is no other solution the flutter team should add slight animation to get rid of this or another workaround.

Also this issue does not happen when developing natively. Kindly tackle this issue.

**Comment by Piinks** [comment] 2023-08-16 19:58
> It's because the component which estimates the height of the scrolling widget, doesn't have all the information about the list that you give to ListView. 

This is correct.

This issue is a duplicate of https://github.com/flutter/flutter/issues/25652, please follow there for updates. Thank you!

**Closed by Piinks** 2023-08-16 19:58 UTC
Labels: framework, f: scrolling, has reproducible steps, found in release: 3.10, team-framework, found in release: 3.14
