### ISSUE TITLE
[web] Blurry text for custom fonts in certain conditions 

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#60442] opened 2020-06-27 20:30 UTC
Continuation of #32274 as this still seems to happen for custom fonts.

Running on Chrome with Flutter `master, 1.20.0-3.0.pre.60`.

---

## Reproduction

See the GIF: it becomes blurred at some resolutions when zooming. For some users it is also blurred right away.  
The example uses [this font](https://github.com/KaTeX/katex-fonts/blob/master/fonts/KaTeX_AMS-Regular.ttf).

![](https://i.imgur.com/a878xmf.gif)

It also seems that it matters where the text is in the tab, i.e. text with the same font of the same size is variably blurry or not.

**Comment by TahaTesser** [comment] 2020-06-29 12:29
Hi @creativecreatorormaybenot 
Issue isn't reproducible when zooming in chrome on latest `dev`  using the font you mentioned 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text(
            'Example Text',
            style: TextStyle(fontFamily: 'KaTeX_AMS'),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}


``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (6 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (4 available)
    • SM M305F      • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos            • darwin-x64     • Mac OS X 10.15.5
      19F101
    • Web Server    • web-server       • web-javascript • Flutter Tools
    • Chrome        • chrome           • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by creativecreatorormaybenot** [comment] 2020-07-01 11:32
@TahaTesser Now, I can share the code 🙃

See https://simpleclub.github.io/CaTeX - the logo (and try now output) use the font and seem to be blurred at some levels of zoom.

Source would be https://github.com/simpleclub/CaTeX/tree/master/demo.

**Comment by TahaTesser** [comment] 2020-07-23 07:19
Hi @creativecreatorormaybenot 
Using your demo https://github.com/simpleclub/CaTeX/tree/master/demo, it's not still reproducing on MBP 
Can you please on latest `master` 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.95, on Mac OS X 10.15.6 19G73,
    locale en-GB)
    • Flutter version 1.21.0-2.0.pre.95 at /Users/tahatesser/Code/flutter_master
    • Framework revision 50b87dc6c3 (13 hours ago), 2020-07-22 11:09:59 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.89

• No issues found!
```

</details> 

Also give us more details on platforms you experiencing this issue? Mac, Windows or linux?  is it same on mobile web as well?
Thank you

**Comment by creativecreatorormaybenot** [comment] 2020-07-25 17:34
@TahaTesser I think it depends on where the text is placed, i.e. the coordinates, window size, etc. So it is difficult to reproduce 😶

**Comment by TahaTesser** [comment] 2020-07-27 07:00
I’m unable to reproduce the issue to pinpoint the cause but it does seem like a serious issue, The issue needs further investigation.

**Comment by Hixie** [comment] 2020-07-28 23:33
cc @ferhatb @yjbanov Can you reproduce this?

**Comment by ferhatb** [comment] 2020-07-30 16:55
@creativecreatorormaybenot : Which version of Chrome and OS version ?

**Comment by creativecreatorormaybenot** [comment] 2020-07-31 05:26
@ferhatb 

```
Chromium: 84.0.4147.105 (Official Build) nightly (64-bit)
Windows 10 Version 2004
```

I also tested it on a MacBook and I am **not** seeing the issue there with the same version of Chromium.

**Comment by markusaksli-nc** [comment] 2020-09-10 06:46
Closing this in favor of https://github.com/flutter/flutter/issues/62291 this issue is too vague and is likely caused by the same thing.

**Closed by markusaksli-nc** 2020-09-10 06:46 UTC
Labels: P4, a: typography, engine, framework, platform-web
