### ISSUE TITLE
Error with Flutter TextField or TextFormField

### ISSUE THREAD

**Issue by sgarg15** [flutter/flutter#65700] opened 2020-09-12 21:06 UTC
# Steps to Reproduce

I seem to be having a problem with `TextField` and `TextFormField`. The code I have is as follows
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _FirstRouteState createState() => _FirstRouteState();
}

class _FirstRouteState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: TextFormField(),
    ));
  }
}
```
To reproduce the issue simply create a stateful widget and try to use TextField or TextFormField. The error should come up when you do `flutter run`

<details>
  <summary>Logs</summary>

```
W/System.err(26651): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ClipData.getItemCount()' on a null 
object reference
W/System.err(26651):    at android.os.Parcel.readException(Parcel.java:1626)
W/System.err(26651):    at android.os.Parcel.readException(Parcel.java:1573)
W/System.err(26651):    at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:197)
W/System.err(26651):    at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:247)
W/System.err(26651):    at io.flutter.plugin.platform.PlatformPlugin.getClipboardData(PlatformPlugin.java:274)
W/System.err(26651):    at io.flutter.plugin.platform.PlatformPlugin.access$700(PlatformPlugin.java:24)
W/System.err(26651):    at io.flutter.plugin.platform.PlatformPlugin$1.getClipboardData(PlatformPlugin.java:81)
W/System.err(26651):    at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:141)
W/System.err(26651):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
W/System.err(26651):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(26651):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/System.err(26651):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(26651):    at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err(26651):    at android.os.Looper.loop(Looper.java:143)
W/System.err(26651):    at android.app.ActivityThread.main(ActivityThread.java:7224)
W/System.err(26651):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(26651):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
W/System.err(26651):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
# flutter run -v
```
[+1884 ms] W/System.err( 9868): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ClipData.getItemCount()'on a null object reference
[   +9 ms] W/System.err( 9868):         at android.os.Parcel.readException(Parcel.java:1626)
[  +40 ms] W/System.err( 9868):         at android.os.Parcel.readException(Parcel.java:1573)
[  +47 ms] W/System.err( 9868):         at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:197)
[  +10 ms] W/System.err( 9868):         at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:247)
[  +45 ms] W/System.err( 9868):         at io.flutter.plugin.platform.PlatformPlugin.getClipboardData(PlatformPlugin.java:274)
[  +48 ms] W/System.err( 9868):         at io.flutter.plugin.platform.PlatformPlugin.access$700(PlatformPlugin.java:24)
[  +42 ms] W/System.err( 9868):         at io.flutter.plugin.platform.PlatformPlugin$1.getClipboardData(PlatformPlugin.java:81)
[   +4 ms] W/System.err( 9868):         at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:141)[  +38 ms] W/System.err( 9868):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
[   +4 ms] W/System.err( 9868):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)        
[   +2 ms] W/System.err( 9868):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
[   +3 ms] W/System.err( 9868):         at android.os.MessageQueue.nativePollOnce(Native Method)
[   +3 ms] W/System.err( 9868):         at android.os.MessageQueue.next(MessageQueue.java:323)
[  +40 ms] W/System.err( 9868):         at android.os.Looper.loop(Looper.java:143)
[   +6 ms] W/System.err( 9868):         at android.app.ActivityThread.main(ActivityThread.java:7224)
[   +6 ms] W/System.err( 9868):         at java.lang.reflect.Method.invoke(Native Method)
[  +38 ms] W/System.err( 9868):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[   +4 ms] W/System.err( 9868):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

# flutter doctor -v
```
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.959], locale en-CA)
    • Flutter version 1.20.3 at C:\src\flutter
    • Framework revision 216dee60c0 (11 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\apnas\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\apnas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • SM G900W8 (mobile) • 48d4988d • android-arm • Android 6.0.1 (API 23)

• No issues found!
```

</details>

**Comment by hamdikahloun** [comment] 2020-09-12 21:18
Hi @sgarg15 
Maybe it's the same issue https://github.com/flutter/flutter/issues/63766, can you please take a look.

**Comment by sgarg15** [comment] 2020-09-12 21:24
> Hi @sgarg15
> Maybe it's the same issue #63766, can you please take a look.

I looked through that already, but wasn't able to find a solution. That issue seems to be filled with two people going back and forth without a solution actually coming out

**Comment by hamdikahloun** [comment] 2020-09-12 21:27
Do you have the same device or same android version as mentioned in the issue?

> android 6.0.1 (My Samsung Galaxy Note 4)

**Comment by sgarg15** [comment] 2020-09-12 21:34
> Do you have the same device or same android version as mentioned in the issue?
> 
> > android 6.0.1 (My Samsung Galaxy Note 4)

I am using a Samsung S5 which is an actual device and not an emulator. Also why should the device matter since, all the users won't have that device?

**Comment by hamdikahloun** [comment] 2020-09-12 21:39
I just try to understand the issue cause. Can you please provide the android version

**Comment by sgarg15** [comment] 2020-09-12 21:42
> I just try to understand the issue cause. Can you please provide the android version
6.0.1 is my phones android version

**Comment by sgarg15** [comment] 2020-09-12 22:18
@hamdikahloun 
Any idea on how I could fix this issue?

**Comment by hamdikahloun** [comment] 2020-09-12 22:35
For now you can add your `flutter doctor -v` and your phone model and android version in the opened issue https://github.com/flutter/flutter/issues/63766. Having more than one issue for same issue don't help to tracking.

**Comment by sgarg15** [comment] 2020-09-12 23:05
@hamdikahloun 
Just to let you know if it helps, I copy pasted the exact code from the flutter website on forms (https://flutter.dev/docs/cookbook/forms/validation) 

And I got the same error

**Comment by sayannath** [comment] 2020-09-12 23:51
Can u wrap that TextFormField with a container?

**Comment by sgarg15** [comment] 2020-09-13 00:03
@sayannath 
> Can u wrap that TextFormField with a container?

Do you mean like this
```dart
class _FirstRouteState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: TextFormField(),
    );
  }
}
```

**Comment by berrylawchingman** [comment] 2020-09-13 00:05
Ok

**Comment by berrylawchingman** [comment] 2020-09-13 00:05
Ok

**Comment by sgarg15** [comment] 2020-09-13 00:15
@sayannath 
Hey so i tried both
```dart
class _FirstRouteState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: TextFormField(),
    );
  }
}
```
and i get this error 
https://paste.ubuntu.com/p/y8kvQXMQYF/

And I also tried 
```dart
class _FirstRouteState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Scaffold(
        body: TextFormField(),
      ),
    );
  }
}
```
and i get this error
https://paste.ubuntu.com/p/rdgfzfSQKh/

Also @berrylawchingman could you please delete your comments so the issue isnt cluttered up

**Comment by sgarg15** [comment] 2020-09-13 22:52
@hamdikahloun 
Any idea when this issue might be fixed, and if it is going to take a bit of time, are there any alternatives to this, so my project can continue?

**Comment by PixelToast** [comment] 2020-09-13 22:53
Closing as duplicate of #63766

**Closed by PixelToast** 2020-09-13 22:53 UTC

**Comment by faridistiqlal** [comment] 2021-01-13 13:17
Hey buddy . Are you solved this issue?
