### ISSUE TITLE
Flake in DartIsolateTest.ValidLoadingUnitSucceeds

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#72312] opened 2020-12-14 23:43 UTC
Seeing this flake:

```[ RUN      ] DartIsolateTest.ValidLoadingUnitSucceeds
flutter: In function canCallDeferredLibrary
[ERROR:flutter/runtime/dart_isolate.cc(1051)] Platform Configuration was null. Deferred library load requestfor loading unit id 2 was not sent.
[ERROR:flutter/runtime/dart_isolate_unittests.cc(495)] Hello from Dart!
../../third_party/dart/runtime/vm/dart_api_impl.cc: 1542: error: Isolate canCallDeferredLibrary is already scheduled on mutator thread 0x7f96d4018e00, failed to schedule from os thread 0x10fab5dc0

version=2.12.0-150.0.dev (dev) (Mon Dec 14 12:05:40 2020 -0800) on "macos_x64"
pid=24557, thread=775, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=10be02000
  pc 0x0000000108943c15 fp 0x00007ffee757a0f0 dart::Profiler::DumpStackTrace(void*)+0x85
  pc 0x0000000108865612 fp 0x00007ffee757a1d0 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x0000000108e71330 fp 0x00007ffee757a210 Dart_ThreadDisableProfiling+0x0
  pc 0x00000001086d4edf fp 0x00007ffee757a230 tonic::DartState::Scope::Scope(tonic::DartState*)+0x1f
  pc 0x00000001086a5a9a fp 0x00007ffee757a2f0 flutter::DartIsolate::LoadLoadingUnit(long, std::__1::unique_ptr<fml::Mapping const, std::__1::default_delete<fml::Mapping const> >, std::__1::unique_ptr<fml::Mapping const, std::__1::default_delete<fml::Mapping const> >)+0x3a
  pc 0x000000010868f067 fp 0x00007ffee757b0a0 flutter::testing::DartIsolateTest_ValidLoadingUnitSucceeds_Test::TestBody()+0x9b7
  pc 0x0000000108ecb560 fp 0x00007ffee757b0e0 testing::Test::Run()+0xe0
  pc 0x0000000108ecc2b0 fp 0x00007ffee757b140 testing::TestInfo::Run()+0x110
  pc 0x0000000108eccd07 fp 0x00007ffee757b190 testing::TestSuite::Run()+0x127
  pc 0x0000000108eda177 fp 0x00007ffee757b250 testing::internal::UnitTestImpl::RunAllTests()+0x3b7
  pc 0x0000000108ed9d0f fp 0x00007ffee757b2a0 testing::UnitTest::Run()+0x7f
  pc 0x00000001086c99ff fp 0x00007ffee757b400 main+0x12f
  pc 0x00007fff73ad2cc9 fp 0x00007ffee757b418 start+0x1
-- End of DumpStackTrace
Traceback (most recent call last):
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 506, in <module>
    sys.exit(main())
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 476, in main
    RunCCTests(build_dir, engine_filter)
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 136, in RunCCTests
    RunEngineExecutable(build_dir, 'runtime_unittests', filter, shuffle_flags)
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 94, in RunEngineExecutable
    RunCmd(test_command, cwd=cwd)
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 47, in RunCmd
    raise Exception('Command "%s" exited with code %d' % (command_string, process.returncode))
Exception: Command "/opt/s/w/ir/cache/builder/src/out/host_profile/runtime_unittests --gtest_shuffle --gtest_repeat=2" exited with code -6```

Not sure what PR has caused it, but I noticed it on a Dart SDK roll - https://dart.googlesource.com/sdk.git/+log/68d1c7504f7d..f166571c7bc4

**Comment by zanderso** [comment] 2020-12-14 23:51
This test looks very suspicious. It looks like there are potentially two `Signal()`s but only one `Wait()` for starters.

**Comment by GaryQian** [comment] 2020-12-14 23:54
This is my test, I'll take another look.

**Comment by GaryQian** [comment] 2020-12-15 04:55
Is this blocking anything? If it is, I can temporarily disable it, since I traced the problem somewhere rather opaque within dart. Since this (should be) the first usage of this dart feature, it may take a bit of time to properly resolve.

**Comment by GaryQian** [comment] 2020-12-15 05:02
https://github.com/flutter/engine/pull/23070

**Comment by zanderso** [comment] 2020-12-15 16:43
> Is this blocking anything?

Getting this unit test passing seems like it would be a prerequisite for declaring success on deferred-loading/split AOT?

**Comment by GaryQian** [comment] 2020-12-16 03:41
Yeah, though after chatting with Ryan about the problem, it seems it is most likely to be a problem with the testing infra rather than the split aot feature itself.

**Comment by zanderso** [comment] 2020-12-17 17:55
Sure. We should do whatever is the necessary work to write a non-flaky test of the thing you're trying to test.

**Comment by tvolkert** [comment] 2020-12-17 21:51
I got the same flake in `task_overlay_test.dart: TaskOverlay shows the right message for nondevicelab tasks`, so it would appear the problem is not in the test.

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20customer_testing/7559/overview
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8860637636394934576/+/steps/prepare_environment/0/steps/Customer_testing/0/steps/customer_testing/0/stdout

```
| 00:07 +38: /b/s/w/ir/tmp/t/flutter_customer_testing.flutter_cocoon.CMCCJS/tests/app_flutter/test/widgets/task_overlay_test.dart: TaskOverlay shows the right message for nondevicelab tasks
| Shell: ../../third_party/dart/runtime/vm/dart_api_impl.cc: 1542: error: Isolate main is already scheduled on mutator thread 0x30b8460, failed to schedule from os thread 0x7fe49feb7700
| Shell:
| Shell: version=2.12.0-157.0.dev (dev) (Wed Dec 16 01:04:40 2020 -0800) on "linux_x64"
| Shell: pid=4587, thread=4589, isolate_group=(nil)((nil)), isolate=(nil)((nil))
| Shell: isolate_instructions=0, vm_instructions=c9a1a0
| Shell:   pc 0x000000000134c47c fp 0x00007fe49feb6c60 /b/s/w/ir/k/flutter sdk/bin/cache/artifacts/engine/linux-x64/flutter_tester+0x114c47c
| Shell:   pc 0x000000000122aaba fp 0x00007fe49feb6e60 /b/s/w/ir/k/flutter sdk/bin/cache/artifacts/engine/linux-x64/flutter_tester+0x102aaba
| Shell: -- End of DumpStackTrace
| 00:07 +38 -1: loading /b/s/w/ir/tmp/t/flutter_customer_testing.flutter_cocoon.CMCCJS/tests/app_flutter/test/widgets/task_overlay_test.dart [E]
|   Shell subprocess crashed with SIGABRT (-6) after tests finished.
|   Test: /b/s/w/ir/tmp/t/flutter_customer_testing.flutter_cocoon.CMCCJS/tests/app_flutter/test/widgets/task_overlay_test.dart
|   Shell: /b/s/w/ir/k/flutter sdk/bin/cache/artifacts/engine/linux-x64/flutter_tester
```

**Comment by jmagman** [comment] 2021-01-06 22:20
Seen again in the same spot as @tvolkert https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858817424874367760/+/steps/prepare_environment/0/steps/Customer_testing/0/steps/customer_testing/0/stdout
```
| 00:13 +159: /b/s/w/ir/tmp/t/flutter_customer_testing.flutter_cocoon.CABRMP/tests/app_flutter/test/widgets/task_overlay_test.dart: TaskOverlay shows the right message for nondevicelab tasks
| Shell: ../../third_party/dart/runtime/vm/dart_api_impl.cc: 1542: error: Isolate main is already scheduled on mutator thread 0x25a5e40, failed to schedule from os thread 0x7f8be8f17700
| Shell:
| Shell: version=2.12.0-179.0.dev (dev) (Wed Dec 23 21:08:22 2020 -0800) on "linux_x64"
| Shell: pid=23996, thread=24001, isolate_group=(nil)((nil)), isolate=(nil)((nil))
| Shell: isolate_instructions=0, vm_instructions=c99d80
| Shell:   pc 0x00000000013501fc fp 0x00007f8be8f16c60 /b/s/w/ir/k/flutter sdk/bin/cache/artifacts/engine/linux-x64/flutter_tester+0x11501fc
| Shell:   pc 0x000000000122e23a fp 0x00007f8be8f16e60 /b/s/w/ir/k/flutter sdk/bin/cache/artifacts/engine/linux-x64/flutter_tester+0x102e23a
| Shell: -- End of DumpStackTrace
| 00:14 +159 -1: loading /b/s/w/ir/tmp/t/flutter_customer_testing.flutter_cocoon.CABRMP/tests/app_flutter/test/widgets/task_overlay_test.dart [E]
|   Shell subprocess crashed with SIGABRT (-6) after tests finished.
|   Test: /b/s/w/ir/tmp/t/flutter_customer_testing.flutter_cocoon.CABRMP/tests/app_flutter/test/widgets/task_overlay_test.dart
|   Shell: /b/s/w/ir/k/flutter sdk/bin/cache/artifacts/engine/linux-x64/flutter_tester
```

**Comment by zanderso** [comment] 2021-01-06 22:47
Unless `task_overlay_test.dart` is using deferred loading, I think that it's unlikely that the crashes from @tvolkert and @jmagman are from the same bug as in @GaryQian's test. I'll create a separate issue.

**Comment by zanderso** [comment] 2021-07-28 21:20
From engine flake triage: @GaryQian Did you get a chance to look into this further? The test is still disabled.

**Comment by GaryQian** [comment] 2021-07-29 06:13
Not yet, I can look into it next.

**Comment by tvolkert** [comment] 2021-08-10 05:07
@GaryQian any update?

**Comment by GaryQian** [comment] 2021-08-10 05:39
Due to limitations in dart in a test env, I plan on testing this with a full integration test on an AVD instead as a unit test. My other line of work getting AVDs running in pre and postsubmit luci will make this test possible

**Comment by GaryQian** [comment] 2021-08-11 19:31
PR for integration tests to properly test this: https://github.com/flutter/flutter/pull/88030

**Comment by zanderso** [comment] 2022-01-26 22:11
From flaky issue triage: @GaryQian Did you delete the flaky test? Can we close this?

**Closed** 2022-04-27 23:09 UTC
Labels: engine, team: flakes, passed first triage, P4, severe: disabled test
