### ISSUE TITLE
[webview_flutter] How to destroy the Android WebView in webview_flutter 4.0.1

### ISSUE THREAD

**Issue by jakky1** [flutter/flutter#118539] opened 2023-01-16 02:53 UTC
## Steps to Reproduce

in ``webview_flutter: ^4.0.1``
1. Execute ``flutter run`` on the code sample
2. Scroll down the webpage to anywhere, or navigate to another webpage by tapping link
3. Click the "Hide" button ( re-build widgets without webview inside )
4. Click the "Show" button ( re-build widgets with webview inside )

**Expected results:**
The Android WebView should be destroyed, and create a new one

**Actual results:** 
The webview shows immediately and webpage keeps the state ( url , scroll position ) after clicking "Show" button.
The Android WebView seems not be destroyed after webview widget disposed.

I wanna to know how to destroy the Android WebView, cleanup all the resource used by the WebView.

For more information:
I also tried ``webview_flutter: 3.0.3`` with modifying some code ( for different API ),
the Android WebView in 3.0.3 seems be destroyed after clicking "Hide" button,
and shows about 2 second blank screen to reload webpage after clicking "Show" button, without keeping the old state (scroll position, url).

<details>
<summary>Code sample</summary>

```

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final controller = WebViewController();

  @override
  void initState() {
    super.initState();
    controller.setJavaScriptMode(JavaScriptMode.unrestricted);
    controller.loadRequest(Uri.parse("https://www.youtube.com/"));
  }

  bool mShow = true;
  void show(bool bShow) {
    setState(() {
      mShow = bShow;
    });
  }

  @override
  Widget build(BuildContext context) {
    Widget webview = WebViewWidget(controller: controller);
    Widget all = Column(children: [
      Row(children: [
        ElevatedButton(onPressed: () => show(true), child: const Text("Show")),
        ElevatedButton(onPressed: () => show(false), child: const Text("Hide")),
      ]),
      if (mShow) Expanded(child: webview),
    ]);

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Windows Webview example app'),
        ),
        body: all,
      ),
    );
  }
}
```

</details>

**Comment by exaby73** [comment] 2023-01-16 11:41
Hello @jakky1. Have you tied using the `key` property? See how to use keys [here](https://www.youtube.com/watch?v=kn0EOS-ZiIc).

**Comment by jakky1** [comment] 2023-01-16 13:18
I tried to tied with a ValueKey, and result are all the same:
```
Widget webview = WebViewWidget(key: const ValueKey("abc"), controller: controller);
```

**Comment by stuartmorgan** [comment] 2023-01-16 13:42
> The Android WebView seems not be destroyed after webview widget disposed.

This is intentional; the lifetime of the native webview in v4 is bound to the controller, not the widget. This allows for things like loading a page before displaying it, which was commonly requested.

Closing as the code here is behaving as intended, since the controller in it is persistant. If you want a fresh webview, you need to create a new controller.

**Closed by stuartmorgan** 2023-01-16 13:42 UTC
Labels: in triage
