### ISSUE TITLE
EditableTextState.toggleToolbar (package:flutter/src/widgets/editable_text.dart:3123)

### ISSUE THREAD

**Issue by bineanzhou** [flutter/flutter#113174] opened 2022-10-09 07:34 UTC
```
#0      EditableTextState.toggleToolbar (package:flutter/src/widgets/editable_text.dart:3123)
#1      TextSelectionGestureDetectorBuilder.onSecondaryTap (package:flutter/src/widgets/text_selection.dart:1715)
#2      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:635)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:635)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306)
#6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:239)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:615)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617)
#11     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440)
#15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337)
#16     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395)
#17     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357)
#18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314)
#19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295)
#20     _rootRunUnary (dart:async/zone.dart:1407)
#21     _CustomZone.runUnary (dart:async/zone.dart:1300)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209)
#23     _invoke1 (dart:ui/hooks.dart:169)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:94)

Null check operator used on a null value
```

**Comment by darshankawar** [comment] 2022-10-10 06:54
Closing this as duplicate of https://github.com/flutter/flutter/issues/111660, please follow-up in it for further updates.

**Closed by darshankawar** 2022-10-10 06:54 UTC
Labels: in triage
