### ISSUE TITLE
Unable to get max resolution of device setting at the moment!

### ISSUE THREAD

**Issue by Giacomo1993** [flutter/flutter#90376] opened 2021-09-20 10:21 UTC
Hi at all!  I need that camera widget to take max resolution of video available on the device camera at that moment.

I have done these tests:

Samsung Galaxy S7

First Test:

setting camera to 1920*1080
ResolutionPreset setting to :
/// 2160p (3840x2160)
ultraHigh,
output video: 1920*1080

Second Test:

setting camera to 2560*1440
ResolutionPreset setting to :
/// 2160p (3840x2160)
ultraHigh,
output video : 1920 * 1080.

Third Test:

setting camera to 3840*2160
ResolutionPreset setting to:
/// 2160p (3840x2160)
ultraHigh,
output video: 1920 * 1080.

it seems to be that the Camera widget uses a default value of resolution, how Can I resolve it? 
@ianloic @anaisbetts @sgraham  @gmoothart @sethladd

**Comment by TahaTesser** [comment] 2021-09-20 11:32
duplicate of https://github.com/flutter/flutter/issues/58163

**Closed by TahaTesser** 2021-09-20 11:32 UTC
Labels: in triage
