### ISSUE TITLE
FlutterTexture function - `(void)onTextureUnregistered:(NSObject<FlutterTexture>*)texture`  isn't called

### ISSUE THREAD

**Issue by jtyan123** [flutter/flutter#123683] opened 2023-03-29 12:12 UTC
## Details

when i call textureRegistry unregisterTexture function like this:

```
[self.textureRegistry unregisterTexture:self.textureId];
```

the FlutterTexture protocol function 

```
- (void)onTextureUnregistered:(NSObject<FlutterTexture>*)texture 
```

 doesn't return a callback.

**Target Platform:*macos*
**Target OS version/browser:*13.2.1*
**Devices:*Mac Pro M1*

## Logs

<details>
<summary>Logs</summary>

```
```

```
 flutter doctor -v
[!] Flutter (Channel unknown, 3.3.10, on macOS 13.2.1 22D68 darwin-arm, locale zh-Hans-CN)
    ! Flutter version 3.3.10 on channel unknown at /Users/yjt/Desktop/flutter/flutter
    ! Upstream repository unknown
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/yjt/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/yjt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by danagbemava-nc** [comment] 2023-03-29 13:41
Hi @jtyan123, you're on an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.7.8) to see if you still experience this issue. 

If you do, please provide a complete minimal reproducible code sample so that we can investigate this. 

Thank you

**Comment by jtyan123** [comment] 2023-03-30 03:10
Thank you for responding to my question.I upgrade flutter version to 3.7.8 the problem persists。

##### flutter doctor -v
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.76.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!


##### I hid some logic of the buffer_cache. this the oc code
```
- (void)onMethodCall:(FlutterMethodCall *)call result:(FlutterResult)result {
  if ([@"createTextureRender" isEqualToString:call.method]) {
      TextureRender *textureRender = [[TextureRender alloc]
          initWithTextureRegistry:self.textureRegistry
                        messenger:self.messenger];
      int64_t textureId = [textureRender textureId];
      self.textureRenders[@(textureId)] = textureRender;
      result(@(textureId));
  } else if ([@"destroyTextureRender" isEqualToString:call.method]) {
      NSNumber *textureId = call.arguments;
      TextureRender *textureRender = [self.textureRenders objectForKey:textureId];
      if (textureRender != nil) {
          [self.textureRegistry unregisterTexture:textureId.longValue];
      }
      result(@(YES));
  }
}
```


```
@interface TextureRender ()<FlutterTexture>
@property(nonatomic) CVPixelBufferRef buffer_cache;
@property(nonatomic, assign) int64_t textureId;
@property(nonatomic, weak) NSObject<FlutterTextureRegistry> *textureRegistry;
@end

@implementation TextureRender

- (instancetype) initWithTextureRegistry:(NSObject<FlutterTextureRegistry> *)textureRegistry
                               messenger:(NSObject<FlutterBinaryMessenger> *)messenger{
    self = [super init];
    if (self) {
        self.textureRegistry = textureRegistry;
        self.textureId = [self.textureRegistry registerTexture:self];
    }
    return self;
}

- (CVPixelBufferRef _Nullable)copyPixelBuffer {
    return CVPixelBufferRetain(self.buffer_cache);
}

- (void)onTextureUnregistered:(NSObject<FlutterTexture> *)texture {
    NSLog(@"%s",__func__);
    if (self.buffer_cache) {
        CVPixelBufferRelease(self.buffer_cache);
        self.buffer_cache = NULL;
    }
}

- (void)dealloc {
    NSLog(@"%s",__func__);
}

@end
```

**Comment by danagbemava-nc** [comment] 2023-03-30 06:37
Hi @jtyan123, the code sample you have provided is missing the flutter parts as well. Please provide a complete runnable minimal reproducible code sample (preferably in a repo, that we can clone) along with steps to reproduce so that we can investigate this. 

Thank you

**Comment by jtyan123** [comment] 2023-03-31 07:51
##### Hi,thanks very mach,this the demo repo.please open and run the example/main.dart. start render the texture while the switch on open.destory render while switch on close .
##### demo
```
https://github.com/jtyan123/flutter_desktop_texture_demo.git
```

**Comment by danagbemava-nc** [comment] 2023-04-03 07:12
Hi @jtyan123, the code sample you shared contains some third-party plugins & packages. Would it be possible for you to provide a standalone sample (without 3rd party plugins/packages) so that we can determine if this is related to something on our end or if it's being caused by one of the third-party plugins?

**Comment by jtyan123** [comment] 2023-04-04 03:37
##### Hi,i already remove the third-party plugins.still have this problem.
```
https://github.com/jtyan123/flutter_desktop_texture_demo.git
```

**Comment by jtyan123** [comment] 2023-04-04 07:49
Hello @danagbemava-nc .it's the same problem with [#88134](https://github.com/flutter/flutter/issues/88134).Is there any solution? 
Thank you!

**Comment by danagbemava-nc** [comment] 2023-04-05 06:38
Hi @jtyan123, thanks for confirming. Unfortunately, there doesn't seem to be one at the moment. 

Since this issue is already being tracked, I'll be closing this as a duplicate of #88134. 

Kindly subscribe to the issue linked above for further updates. 

Thank you

**Closed by danagbemava-nc** 2023-04-05 06:38 UTC
Labels: in triage
