### ISSUE TITLE
download.flutter.io not available via HTTPS

### ISSUE THREAD

**Issue by licaon-kter** [flutter/flutter#51932] opened 2020-03-04 14:04 UTC
I could just [PR these 3 links](https://github.com/flutter/flutter/search?l=Gradle&q=http%3A%2F%2F), but:

> Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for download.flutter.io. The certificate is only valid for the following names: *.storage.googleapis.com, *.appspot.com.storage.googleapis.com, *.commondatastorage.googleapis.com, *.content-storage-download.googleapis.com, *.content-storage-upload.googleapis.com, *.content-storage.googleapis.com, *.googleapis.com, *.storage-download.googleapis.com, *.storage-upload.googleapis.com, *.storage.select.googleapis.com, commondatastorage.googleapis.com, storage.googleapis.com, storage.select.googleapis.com, unfiltered.news
> 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

Ref: https://gitlab.com/fdroid/fdroidserver/issues/624

**Comment by jmagman** [comment] 2020-03-05 00:19
@kf6gpe  Do you know who to reach out to about this?

**Comment by kf6gpe** [comment] 2020-03-05 00:42
flutter.io has been deprecated for some time; the TLD currently redirects to flutter.dev through Firebase.

I'm not sure what's trying to access flutter.io --- the downloadable packages I see are in storage.googleapis.com, which doesn't seem to have the same problem. Who's the referent for flutter.io, and that may help us pin it down?

**Comment by jmagman** [comment] 2020-03-05 00:49
It's the maven repo URL from the tool, @licaon-kter linked to the references.
\cc @blasten may know more.

**Comment by jmagman** [comment] 2020-03-05 01:17
https://github.com/flutter/flutter/issues/11439#issuecomment-536800477

**Comment by licaon-kter** [comment] 2020-03-05 08:27
An app: https://gitlab.com/jugendhackt/fff_info/
A build recipe: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/cf.fridays.fff_info.yml#L34
The error: https://gist.github.com/licaon-kter/a1b69897bebabe569def9533a78bc843

**Comment by jmagman** [comment] 2020-03-05 20:34
Duplicate of https://github.com/flutter/flutter/issues/47452.

**Closed by jmagman** 2020-03-05 20:34 UTC
Labels: tool
