### ISSUE TITLE
Calculator: back button on iOS very hard to see

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4740] opened 2016-06-24 17:54 UTC
The white on white makes it hard to see the upper-left back button.

![2765da88-e1fe-4e3c-9096-fbdfc9dd108d](https://cloud.githubusercontent.com/assets/5479/16346010/f3be2b52-39f9-11e6-8e5c-36c353318e3f.PNG)

**Comment by Hixie** [comment] 2017-10-24 22:55
Dupe of #4630.

**Closed by Hixie** 2017-10-24 22:55 UTC
Labels: prod: framework, prod: material design, team: gallery, ⌺‬ platform-ios
