### ISSUE TITLE
how can we draw bitmap and after drawing how to rotate that bitmap in flutter..?

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#41288] opened 2019-09-25 13:16 UTC
https://stackoverflow.com/questions/58099224/how-can-we-draw-bitmap-and-after-drawing-how-to-rotate-that-bitmap-in-flutter

``` Paint top_side = new Paint()
      ..shader = ImageShader( image, TileMode.repeated, TileMode.repeated, deviceTransform );```

I use this in flutter but now I want to send the rotated image to that Image shader how to send this image

**Comment by tvolkert** [comment] 2020-01-13 02:34
The link to StackOverflow is a 404, but this does look like a question that would better asked on StackOverflow, as it's not a bug in Flutter.  As such, closing.

**Closed by tvolkert** 2020-01-13 02:34 UTC
Labels: d: stackoverflow
