### ISSUE TITLE
Flutter Told Me To Report A Rendering Error Here

### ISSUE THREAD

**Issue by graham-l** [flutter/flutter#18107] opened 2018-06-01 08:36 UTC
Using Flutter in Android Studio, receiving and error message while rendering the page on my phone telling me to report a bug. Two sections follow - the error message and the code:

Section 1 - The Error Message
```
Performing hot reload...
I/flutter (12349): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (12349): The following assertion was thrown during performLayout():
I/flutter (12349): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1514 pos 12:
I/flutter (12349): '!_debugDoingThisLayout': is not true.
I/flutter (12349): 
I/flutter (12349): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12349): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12349): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12349):   https://github.com/flutter/flutter/issues/new
I/flutter (12349): 
I/flutter (12349): When the exception was thrown, this was the stack:
I/flutter (12349): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1514:12)
I/flutter (12349): #3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (12349): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #5      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12349): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #7      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124:11)
I/flutter (12349): #8      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:257:7)
I/flutter (12349): #9      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
I/flutter (12349): #10     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
I/flutter (12349): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #12     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #14     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #15     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1141:24)
I/flutter (12349): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #17     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #19     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #21     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #26     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2713:26)
I/flutter (12349): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #28     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #30     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:509:15)
I/flutter (12349): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #32     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #34     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #36     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #38     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #40     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (12349): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12349): #42     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter (12349): #43     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (12349): #44     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (12349): #45     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (12349): #46     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622:22)
I/flutter (12349): #47     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (12349): #48     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (12349): #49     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (12349): #50     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (12349): #52     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
I/flutter (12349): #53     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
I/flutter (12349): #54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
I/flutter (12349): (elided 3 frames from class _AssertionError and package dart:async-patch)
I/flutter (12349): 
I/flutter (12349): The following RenderObject was being processed when the exception was fired:
I/flutter (12349):   RenderFlex#5782e relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):   creator: Column ← Padding ← Container ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter (12349):   CustomMultiChildLayout ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (12349):   _InkFeatures-[GlobalKey#b859f ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (12349):   PhysicalModel ← AnimatedPhysicalModel ← ⋯
I/flutter (12349):   parentData: offset=Offset(20.0, 20.0) (can use size)
I/flutter (12349):   constraints: BoxConstraints(0.0<=w<=320.0, 0.0<=h<=520.0)
I/flutter (12349):   size: MISSING
I/flutter (12349):   direction: vertical
I/flutter (12349):   mainAxisAlignment: spaceEvenly
I/flutter (12349):   mainAxisSize: max
I/flutter (12349):   crossAxisAlignment: center
I/flutter (12349):   verticalDirection: down
I/flutter (12349): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (12349):   RenderFlex#368ab relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):     RenderParagraph#28294 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):     RenderSemanticsAnnotations#ee90f relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):       RenderPointerListener#a4154 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):         _RenderDecoration#e2772 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):           RenderRepaintBoundary#0aa21 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):           RenderOpacity#fc0bc relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):           RenderConstrainedBox#7ccd7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):           RenderCustomPaint#47c68 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):   RenderFlex#09a61 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):     RenderParagraph#ad905 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):     RenderSemanticsAnnotations#b3c63 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):       RenderPointerListener#c62c7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):         _RenderDecoration#c340f NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):           RenderRepaintBoundary#72b70 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):           RenderOpacity#bac69 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):           RenderConstrainedBox#7e422 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349):           RenderCustomPaint#e3a16 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12349): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12349): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1446 pos 12: 'hasSize': is not true.
I/flutter (12349): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1446 pos 12: 'hasSize': is not true.
I/flutter (12349): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
Reloaded 1 of 483 libraries in 1,210ms.
D/ViewRootImpl@6433391[MainActivity](12349): MSG_WINDOW_FOCUS_CHANGED 0
D/SurfaceView(12349): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={Surface(name=null)/@0x63376f7 isValid=false 0}
D/ViewRootImpl@6433391[MainActivity](12349): mHardwareRenderer.destroy()#1
D/ViewRootImpl@6433391[MainActivity](12349): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
D/ViewRootImpl@6433391[MainActivity](12349): mHardwareRenderer.destroy()#1
D/ViewRootImpl@6433391[MainActivity](12349): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
D/InputTransport(12349): Input channel destroyed: fd=97
W/IInputConnectionWrapper(12349): reportFullscreenMode on inexistent InputConnection
W/IInputConnectionWrapper(12349): finishComposingText on inactive InputConnection
```
Section 2 - The Code

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Welcome to Flutter',
      home: new Scaffold(
          appBar: new AppBar(
            title: new Text('Welcome to Flutter'),
          ),
          body: new Container(
            padding: new EdgeInsets.all(20.0),
            child: new Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                //new Text('User Name'),
                new Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    new Text('User Name'),
                    new TextField(
                      autofocus: true,
                      decoration: new InputDecoration(
                          border: InputBorder.none,
                          hintText: 'Please enter your user name'),
                    ),
                  ],
                ),
                new Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    new Text('User Name'),
                    new TextField(
                      decoration: new InputDecoration(
                          border: InputBorder.none,
                          hintText: 'Please enter your pasword'),
                    ),
                  ],
                ),
              ],
            ),
          )),
    );
  }
}
```

**Comment by mgonher** [comment] 2018-08-16 18:11
Same problem  :(

**Comment by zoechi** [comment] 2018-10-23 06:59
Might be related to #9781

**Comment by goderbauer** [comment] 2018-12-29 01:49
This is a dupe of https://github.com/flutter/flutter/issues/9781.

**Closed by goderbauer** 2018-12-29 01:49 UTC
Labels: framework, severe: crash
