### ISSUE TITLE
Broken intellisense on vs-code version 1.51

### ISSUE THREAD

**Issue by CrystalxCode** [flutter/flutter#80314] opened 2021-04-12 22:55 UTC
## Steps to Reproduce

1. Unsure how to reproduce (install 1.51??)

## The issue
Whenever I will try to enter some valid flutter code, there is no intellisense. Even with force mode(CTRL + SPACE) nothing but my snippets show.

![image](https://user-images.githubusercontent.com/60084007/114472765-e13f9a00-9bc0-11eb-99bc-93b4d578ca36.png)

<details>
<summary>Logs</summary>

No commands, just vs-code.

```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /home/david/snap/flutter/common/flutter
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/david/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.21.0

[!] Connected device
    ! Device ZY223QBV7S is not authorized.
      You might need to check your device for an authorization dialog.

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-04-13 07:41
Hi @CrystalxCode 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-13 07:41 UTC
Labels: in triage
