### ISSUE TITLE
[Desktop] InteractiveViewer default pan operation using two fingers is not supported.

### ISSUE THREAD

**Issue by erf** [flutter/flutter#94541] opened 2021-12-02 11:37 UTC
## Use case

I'm building a desktop app for macOS and I would like to use `InteractiveViewer` to pan a Widget larger than the window, but i noticed that i can only pan with click and drag, and that the default pan operation for macOS using two fingers is not supported.

## Proposal

I would like for the two finger pan to be the default behavoiur for the `InteractiveViewer` with the possibility for customization of using other gestures.

**Comment by maheshmnj** [comment] 2021-12-03 07:26
> but I noticed that I can only pan with click and drag, and that the default pan operation for macOS using two fingers is not supported.
Hi @erf, when panning on a desktop with two fingers do you mean on a trackpad? if so I see that working I am able to scale with two fingers you can verify this interactive example https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html

**Comment by erf** [comment] 2021-12-03 10:33
@maheshmnj yes the trackpad on a macbook air, i can't pan / move the view, i have not tried to zoom.

**Comment by erf** [comment] 2021-12-03 12:43
Here is an example:

Make sure the content is larger than the window and try to pan/move with two fingers on a macOS / Desktop app (which is the default behaviour). Does not work for me. I have to press and drag.

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final controller = TransformationController();

  @override
  void initState() {
    super.initState();

    //controller.value = Matrix4.translation(translation)
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('InteractiveViewer test'),
      ),
      body: InteractiveViewer(
        scaleEnabled: false,
        constrained: false,
        transformationController: controller,
        child: Center(
          child: Container(
            alignment: Alignment.center,
            color: Colors.blue,
            width: 1500,
            height: 1500,
            child: Stack(
              children: [
                Container(
                  alignment: Alignment.topLeft,
                  color: Colors.green,
                  width: 250,
                  height: 250,
                ),
                Container(
                  alignment: Alignment.center,
                  color: Colors.red,
                  width: 250,
                  height: 250,
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by maheshmnj** [comment] 2021-12-03 13:56
Thanks for the code sample @erf, I can reproduce the issue the container does move with tap and drag but not with two-finger gestures from trackpad.


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55
    ! Device 192.168.1.6:5555 is offline.

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.789, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.789 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ae721de3d (12 days ago), 2021-11-21 15:22:37 -0500
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55
    ! Device 192.168.1.6:5555 is offline.

• No issues found!
```
</details>

**Comment by gspencergoog** [comment] 2022-01-27 19:06
This is a duplicate of https://github.com/flutter/flutter/issues/63084

**Closed by gspencergoog** 2022-01-27 19:06 UTC
Labels: framework, f: gestures, a: desktop, has reproducible steps, found in release: 2.5, found in release: 2.6
