### ISSUE TITLE
`image_picker` on Android opens the File Selector instead of showing the Photo & Video picker

### ISSUE THREAD

**Issue by dovahkiin98** [flutter/flutter#151422] opened 2024-07-08 17:36 UTC
### Steps to reproduce

1- Choose `pickMedia` on Android

### Expected results

The Photo & Video Picker is opened

### Actual results

The Android FilePicker is opened

### Code sample

<details open><summary>Code sample</summary>

```dart
final imagePicker = ImagePicker();

final media = await imagePicker.pickMedia(
    requestFullMetadata: false,
);
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22635.3790], locale en-GB)
    • Flutter version 3.22.2 on channel stable at J:\Programming\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
    • Android SDK at J:\Programming\Android\Android_SDK
    • Platform android-35, build-tools 35.0.0-rc4
    • ANDROID_HOME = J:\Programming\Android\Android_SDK
    • ANDROID_SDK_ROOT = J:\Programming\Android\Android_SDK
    • Java binary at: J:\Programming\Android\Android_Studio_Canary\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at J:\VisualStudio\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2024.1)
    • Android Studio at J:\Programming\Android\Android_Studio_Canary
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] IntelliJ IDEA Community Edition (version 2024.1)
    • IntelliJ at J:\IntelliJ IDEA
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17890.8

[√] VS Code (version 1.90.2)
    • VS Code at C:\Users\ahmad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22635.3790]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 126.0.2592.24

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-07-09 07:26
You are reporting `file_selector` issue but the code sample is using `image_picker` instead. Which package are you reporting bugs for? 

Please provide the complete and minimal sample code. Also, please be more specific in the `Steps to reproduce` section by providing step-by-step instructions on reproducing the issue.

**Comment by dovahkiin98** [comment] 2024-07-09 11:52
Sorry, wrong title. I'm reporting an issue in `image_picker`

**Comment by huycozy** [comment] 2024-07-10 05:10
I checked this using [package example](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) and added `requestFullMetadata: false` to `pickMedia` call (in `_onImageButtonPressed` method) but the picker is showing images as expected (without showing files) on my device Pixel 7, Android 14. 

Could you also try using this example and confirm? Also, are you seeing this on `Android 15 (API 35) (emulator)` only? Could you share a demo of the bug? (a recorded video would be appreciated)

**Comment by dovahkiin98** [comment] 2024-07-10 16:56
I'm testing it on my Samsung S24 Ultra (Android 14). The normal image or video picker works, but not the Media ones (Same on my S21 (Android 14)

Android 35 Emulator, same thing

Android 34 Emulator, same thing

**Comment by huycozy** [comment] 2024-07-11 03:16
>The normal image or video picker works, but not the Media ones

Sorry, I don't get this. Can you share a demo video of the actual result you see? As you described above in the original comment, `The Android FilePicker is opened`, does it mean the picker contains non-media files only? (as I understand, media is image or video)

**Comment by dovahkiin98** [comment] 2024-07-11 17:04
Android Native Picker

https://github.com/flutter/flutter/assets/8161112/a68e4ed0-9bff-425e-ae13-41c138e7885b

Flutter Image Picker

https://github.com/flutter/flutter/assets/8161112/24805c06-e6c5-41a9-9499-cf464be3cd94

If you can see in the videos. In the Android solution, the Image & Video picker shows if you want a video or an image.

While in Flutter's `image_picker`, the File picker is shown, even though the Android Picker has support for Image & Video together

**Comment by huycozy** [comment] 2024-07-12 05:56
I see. The above happens due to you are using `pickMedia`, but not `getMedia` which is already implemented at https://github.com/flutter/flutter/issues/89159. You can check [image_picker_android example](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker_android/example) on how to use it. Closing this as duplicate of #89159.

**Closed by huycozy** 2024-07-12 05:56 UTC
Labels: in triage

**Comment by dovahkiin98** [comment] 2024-07-12 09:39
What is the difference between using `ImagePickerPlatform` and using `ImagePicker`?
