### ISSUE TITLE
[web] ImageDescriptor.raw flips and inverts images (partial reason included)

### ISSUE THREAD

**Issue by Proberts** [flutter/flutter#89610] opened 2021-09-07 21:42 UTC
![flutter_bug_imageraw](https://user-images.githubusercontent.com/778115/132413746-e382ece8-525b-44a7-a66a-18ae4f1aeb9d.png)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace main.dart with the main.dart in  [main.dart.zip](https://github.com/flutter/flutter/files/7124451/main.dart.zip)
3. Run for web target and mobile target

**Expected results:** 
Consistent behavior between platforms for pixel packing and image coordinates when exporting image raw bytes then creating an image using the exported raw bytes.

**Actual results:** 
The mobile engine appears to have consistent packing and coordinates
Web flips image vertically and expects(?) different packing

Looking at the web_ui source: https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/ui/painting.dart (line 786)
The web engine is prepending a BMP header on the raw image data and passing it to the BMP codec. Image.toByteData() appears to export image bytes with an upper-left origin (0,0). Unlike most image formats BMP expects a lower-left origin (0,0): the first row of pixels in the BMP file is the bottom row in the image, not the top row. This likely explains the flip.

Image.toByteData()'s only format option is Rgba. The web raw codec inverts colors when fed the data back as rgba. If incorrectly specifying the data is bgra the resulting image has correct colors.

<details>
<summary> flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /devel/_common/flutter/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/proberts/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /devel/_common/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /devel/_common/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /devel/_common/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Pixel 4 (mobile)                   • 99041FFAZ00BZS • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554  • android-x86    • Android 7.0 (API 24) (emulator)
    • Chrome (web)                       • chrome         • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2021-09-08 10:01
Issue is reproducible on `master` and `stable` and occurs on only `web`. 
All other platforms have consistent behaviour. 

## Screenshots

<details>

| platform | screenshot |
| -------- | ---------- |
| android  | ![photo_2021-09-08 09 57 56](https://user-images.githubusercontent.com/88313112/132489138-60ba68a2-22a2-431a-b3c3-26c42696849b.jpeg) |
| ios	   |  ![IMG_2911](https://user-images.githubusercontent.com/88313112/132489236-23c39bab-f687-49e6-a532-0dc1db1ce266.PNG)|
| macOS    | <img width="565" alt="Screenshot 2021-09-08 at 09 50 44" src="https://user-images.githubusercontent.com/88313112/132489294-1f4ee36c-75af-4bbf-894e-3bf2cd905e81.png"> |
| web (chrome) |  <img width="640" alt="Screenshot 2021-09-08 at 09 42 35" src="https://user-images.githubusercontent.com/88313112/132489368-4a73fb16-ddd0-4f3f-8c4d-080753a17944.png"> |

 


</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.7.1
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 93.0.4577.63

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.199, on macOS 11.5.1 20G80
    darwin-arm, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.199 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d2de2adb6b (6 hours ago), 2021-09-07 23:41:05 -0400
    • Engine revision 4159d7f0f1
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.7.1 18G82
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 93.0.4577.63

• No issues found!
```
</details>

**Comment by zambetpentru** [comment] 2021-12-10 13:00
Hi,

I've been trying to work through my issue on https://github.com/flutter/flutter/issues/93615 
and I notice now on the latest master 2.6.0-12.0.pre.978 the images don't decode at all anymore.

![image](https://user-images.githubusercontent.com/81489824/145577720-eff80988-2ff3-4175-8225-7028e33b54fd.png)

<details> 
<summary>error
Error: Failed to encode the image into bytes.

    at Object.createErrorWithStack (http://localhost:52657/dart_sdk.js:5078:12)
    at Function._throw (http://localhost:52657/dart_sdk.js:20305:18)
    at Function.throwWithStackTrace (http://localhost:52657/dart_sdk.js:20302:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52657/dart_sdk.js:40823:18)
    at Object._microtaskLoop (http://localhost:52657/dart_sdk.js:40680:13)
    at _startMicrotaskLoop (http://localhost:52657/dart_sdk.js:40686:13)
    at http://localhost:52657/dart_sdk.js:36161:9
Error: Failed to encode the image into bytes.


    at Object.createErrorWithStack (http://localhost:52657/dart_sdk.js:5078:12)
    at Function._throw (http://localhost:52657/dart_sdk.js:20305:18)
    at Function.throwWithStackTrace (http://localhost:52657/dart_sdk.js:20302:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52657/dart_sdk.js:40823:18)
    at Object._microtaskLoop (http://localhost:52657/dart_sdk.js:40680:13)
    at _startMicrotaskLoop (http://localhost:52657/dart_sdk.js:40686:13)
    at http://localhost:52657/dart_sdk.js:36161:9
</summary> 
</details>

<details> 
<summary>flutter doctor</summary> 
[√] Flutter (Channel master, 2.6.0-12.0.pre.978, on Microsoft Windows [Version 10.0.17763.2300], locale en-IE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (2 available)
</details>

**Comment by zambetpentru** [comment] 2021-12-14 20:50
This issue is fixed since: https://github.com/flutter/engine/commit/64a9a1a06acb7008d814c025e7f85f7d72895360

flutter-2.8-candidate.8:
![image](https://user-images.githubusercontent.com/81489824/146077208-7cacf552-43b6-48f3-9c21-59ec0c3ba12d.png)

**Comment by zambetpentru** [comment] 2021-12-14 20:57
@danagbemava-nc What is the recommended protocol here? The original issue was fixed by @dkwingsmt but now there is a different error in the current version of the framework, does this ticket get closed and a new one opened for that?

**Comment by danagbemava-nc** [comment] 2021-12-15 06:46
Hi @zambetpentru,  if the issue has been confirmed fixed, then yes, we can close this issue. 

It is always better to create a new issue in such cases and just reference the relevant issues/prs. 
However, I'm not seeing the new error on the latest master. Can you confirm this? 

<details>
<summary>screenshot</summary>

<img width="898" alt="Screenshot 2021-12-15 at 06 45 19" src="https://user-images.githubusercontent.com/88313112/146136948-519a65db-3e11-48c3-88a8-e03628cf1273.png">

</details>

**Comment by zambetpentru** [comment] 2021-12-15 10:23
Hi @danagbemava-nc,

I just tried on the latest master 2.9.0-1.0.pre.95 now so something fixed it since 2.6.0-12.0.pre.978 (I just reconfirmed it is broken here) a few days ago - so all looks good! :-)

**Comment by Proberts** [comment] 2021-12-16 21:04
Appears correct in master 2.9.0-1.0.pre.117: 

![image](https://user-images.githubusercontent.com/778115/146447733-691d0416-e69b-4c64-9338-193d8f56cac1.png)

<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel master, 2.9.0-1.0.pre.117, on Linux Mint 19.3 5.4.0-91-generic, locale en_US.UTF-8)
    • Flutter version 2.9.0-1.0.pre.117 at /devel/_common/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 82c00c12a6 (14 minutes ago), 2021-12-16 15:39:20 -0500
    • Engine revision a86f51231f
    • Dart version 2.16.0 (build 2.16.0-116.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/proberts/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /devel/_common/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /devel/_common/android-studio
    • Flutter plugin version 62.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • SM G930V (mobile) • 83fd532c • android-arm64  • Android 8.0.0 (API 26)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by danagbemava-nc** [comment] 2021-12-17 05:56
Given https://github.com/flutter/flutter/issues/89610#issuecomment-996192340 and https://github.com/flutter/flutter/issues/89610#issuecomment-994631857, I feel it is safe to close this issue. 

Closing as fixed. 

Thank you

**Closed by danagbemava-nc** 2021-12-17 05:56 UTC
Labels: engine, platform-web, e: web_canvaskit, has reproducible steps, P4, found in release: 2.2, found in release: 2.6
