### ISSUE TITLE
MultiFlutterEngine on iOS consumes a lot of memory

### ISSUE THREAD

**Issue by icespring** [flutter/flutter#79023] opened 2021-03-25 06:47 UTC
## Steps to Reproduce

1. use sample code for multiple flutters on iOS here : https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters
2. run the sample code on iOS real devices with flutter release mode build
3. push "next" button, see the memory monitor 

I created about 5 FluttterViewControllers，the memory is up to 200M+
![image](https://user-images.githubusercontent.com/2375279/112430149-b4922280-8d78-11eb-8974-d0924cd96de6.png)

But as the "[Multiple Flutter screens or views](https://flutter.dev/docs/development/add-to-app/multiple-flutters)" page note that 

>The 2.0.0 Flutter release drastically reduces the memory footprint of additional Flutter engines from ~19MB on Android and ~13MB on iOS, to ~180kB on Android and iOS. This ~99% fixed cost reduction allows the multiple Flutters pattern to be used more liberally in your add-to-app integration.

Am I wrong with something?  I expected create FlutterEngine would save much memory.

finally, with flutter doctor 

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.6 19G2021 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.3 at /Users/icespring/bin/flutter
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/icespring/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/icespring/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7136282/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • ONEPLUS A6013 (mobile)       • 9ab75e76                             • android-arm64  • Android 10 (API 29)
    • “icespring”的 iPhone (mobile) • 00008020-000565163A79002E            • ios            • iOS 14.0
    • iPhone 12 Pro Max (mobile)   • 0B485DD1-7E98-439F-B96F-84CCA087C6A0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 89.0.4389.90

```

**Comment by TahaTesser** [comment] 2021-03-25 12:05
Hi @icespring 
You're monitoring memory from Xcode, how did you run in release mode?  Can you please clarify 


When simply running the native app`multiple_flutters_ios` with module from Xcode, I do see 250+MB memory usage 

<img width="461" alt="Screenshot 2021-03-25 at 2 01 44 PM" src="https://user-images.githubusercontent.com/48603081/112469987-c96bb780-8d72-11eb-8406-86d991f4e583.png">

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 89.0.4389.90

• No issues found!
```
	
</details>

**Comment by icespring** [comment] 2021-03-26 06:21
@TahaTesser

Sorry for not clarifying. 

Because I noticed the debug mode consume much more memory，I Build release mode in flutter and debug mode in iOS app. I modified the `FLUTTER_SDK_PATH/packages/flutter_tools/bin/xcode_backend.sh`， line 46 to `local build_mode="release"`

**Comment by TahaTesser** [comment] 2021-03-26 10:05
Hi @icespring 
Thanks for the details!

When running in release mode, initially takes more RAM than debug mode, However, if you keep going next after next, memory usage keeps increasing and UI becomes sluggish and  Below is the preview

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/112615632-64c06380-8e2b-11eb-8c2e-9a8217302e56.gif)


<img width="879" alt="Screenshot 2021-03-26 at 10 34 02 AM" src="https://user-images.githubusercontent.com/48603081/112615586-52462a00-8e2b-11eb-857f-ec394391257e.png">



I could only reproduce on the `stable`, I am running into another when trying to test on the master channel with bitcode error 



<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (5 available)
    • SM M025F (mobile)      • R9ZR205XX0A                          •
      android-arm    • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.4.1
    • iPhone 12 (mobile)     • 72918AE2-FA3C-4ED7-983C-B5A4CB05346E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```
	
</details>

Thank you

**Comment by chinmaygarde** [comment] 2021-03-29 18:23
cc @gaaclarke @xster

**Comment by gaaclarke** [comment] 2021-03-29 20:02
Duplicate of https://github.com/flutter/flutter/issues/77621

**Closed by gaaclarke** 2021-03-29 20:02 UTC
Labels: P4, a: existing-apps, engine, found in release: 2.0, has reproducible steps, perf: memory, platform-ios, severe: performance
