### ISSUE TITLE
[macOS] Avoid using `TextEditingDeltaNonTextUpdate` for syncing state.

### ISSUE THREAD

**Issue by angelosilvestre** [flutter/flutter#118759] opened 2023-01-19 00:23 UTC
On macOS, every time we call `setEditingState`, the engine sends us back a `TextEditingDeltaNonTextUpdate`, as we can see in the engine code:

https://github.com/flutter/engine/blob/8ed6790b5977c5d91e99a3c75e5b4ceb17cca38b/shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm#L349-L364

We have no way to know if the `TextEditingDeltaNonTextUpdate` is sent because the IME is trying to update the selection, like swiping on the spacebar on Android, or if it's the engine trying to sync its state.

This also happens on Android in some cases, as described in https://github.com/flutter/flutter/issues/113253.

Flutter should use a different kind of delta for syncing state, so we can know if we are changing the selection/composing region, or if the engine is syncing its state.

## Steps to Reproduce

1. Execute `flutter run` on the code sample on macOS
2. Type some letter

**Expected results:** We don't get a `TextEditingDeltaNonTextUpdate`

**Actual results:** We get a `TextEditingDeltaNonTextUpdate`

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(
    MaterialApp(
      home: InputExample(),
    ),
  );
}

class InputExample extends StatefulWidget {
  const InputExample({super.key});

  @override
  State<InputExample> createState() => _InputExampleState();
}

class _InputExampleState extends State<InputExample> with TextInputClient, DeltaTextInputClient {
  TextInputConnection? _connection;
  TextEditingValue _currentEditingValue = const TextEditingValue();
  TextEditingValue _lastValueSent = const TextEditingValue();

  @override
  void initState() {
    super.initState();

    _attachToIme();
  }

  @override
  void dispose() {
    super.dispose();
    _detachFromIme();
  }

  @override
  void updateEditingValueWithDeltas(List<TextEditingDelta> textEditingDeltas) {
    TextEditingValue newEditingValue = _currentEditingValue;

    for (final delta in textEditingDeltas) {
      print('Processing delta: ${delta}');
      // We could make arbitrary changes to the newEditingValue
      newEditingValue = delta.apply(newEditingValue);
    }

    _updateEditingStateOnPlatform(newEditingValue);

    setState(() {
      _currentEditingValue = newEditingValue;
    });
  }

  void _attachToIme() {
    const config = TextInputConfiguration(
      enableDeltaModel: true,
    );
    _connection = TextInput.attach(this, config);
    _connection!.show();
    print('attached to IME');
  }

  void _detachFromIme() {
    _connection?.close();
    print('detached from IME');
  }

  void _updateEditingStateOnPlatform(TextEditingValue value) {
    if (_connection == null) {
      return;
    }
    if (value == _lastValueSent) {
      return;
    }
    _connection!.setEditingState(value);
    _lastValueSent = value;
  }

  @override
  void connectionClosed() {}

  @override
  AutofillScope? get currentAutofillScope => throw UnimplementedError();

  @override
  TextEditingValue? get currentTextEditingValue => throw UnimplementedError();

  @override
  void performAction(TextInputAction action) {}

  @override
  void performPrivateCommand(String action, Map<String, dynamic> data) {}

  @override
  void showAutocorrectionPromptRect(int start, int end) {}

  @override
  void updateEditingValue(TextEditingValue value) {}

  @override
  void updateFloatingCursor(RawFloatingCursorPoint point) {}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(_currentEditingValue.text),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
flutter run --verbose

No relevant info
```

```
flutter analyze

No relevant info
```

```
flutter doctor -v

[!] Flutter (Channel master, 3.7.0-23.0.pre.16, on macOS 12.6.1 21G217
    darwin-x64, locale pt-BR)
    • Flutter version 3.7.0-23.0.pre.16 on channel master at
      /Users/user223563/Downloads/flutter
    ! The flutter binary is not on your path. Consider adding
      /Users/user223563/Downloads/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding
      /Users/user223563/Downloads/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b3059d2c09 (41 minutes ago), 2023-01-18 23:27:27 +0000
    • Engine revision 290636c1cb
    • Dart version 3.0.0 (build 3.0.0-122.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment] 2023-01-19 09:12
Thanks for the detailed report.
Upon running the code sample on macOS desktop platform and inputing any letter I get below in console:

```
flutter: attached to IME
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:52073/9Kbv7-iHRfM=/
flutter: Processing delta: Instance of 'TextEditingDeltaInsertion'
flutter: Processing delta: Instance of 'TextEditingDeltaNonTextUpdate'
flutter: Processing delta: Instance of 'TextEditingDeltaInsertion'
flutter: Processing delta: Instance of 'TextEditingDeltaNonTextUpdate'
flutter: Processing delta: Instance of 'TextEditingDeltaInsertion'
flutter: Processing delta: Instance of 'TextEditingDeltaNonTextUpdate'
flutter: Processing delta: Instance of 'TextEditingDeltaInsertion'
flutter: Processing delta: Instance of 'TextEditingDeltaNonTextUpdate'
flutter: Processing delta: Instance of 'TextEditingDeltaInsertion'
```

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.10 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (15 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-23.0.pre.21, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.7.0-23.0.pre.21 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6a9b2db4ac (3 hours ago), 2023-01-18 21:03:37 -0500
    • Engine revision 95b0c151f7
    • Dart version 3.0.0 (build 3.0.0-136.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by matthew-carroll** [comment] 2023-01-19 22:11
CC @justinmc @Renzo-Olivares

**Comment by matthew-carroll** [comment] 2023-01-19 22:12
I filed a duplicate of this issue and closed it. But here's my explanation from that issue, to add more context to this ticket:

There are four types of IME deltas: insertion, replacement, deletion, non-text update.

The non-text update informs an app that a text selection or composing region was changed by the user, without any content changes, and the app should update accordingly.

On Mac (and maybe other platforms), when the app sends an update to the IME, the IME responds back with a `TextEditingDeltaNonTextUpdate`, which repeats the selection and composing region that the app just sent to the IME. This creates a couple of problems.

First, if the app developer doesn't check whether the new IME value is different from the existing local `TextEditingValue`, the app developer might apply the change and send it right back to the IME, which yields an endless loop. The IME notifies the app, the app notifies the IME, the IME notifies the app, etc. And yet, it's the same value every time. This problem can be avoided if the developer knows what to look for, but it seems like an unnecessary footgun.

Second, and the bigger issue, is that IME client changes that happen quickly can cause an unavoidable endless loop with the IME. I'll illustrate with an example. Let's assume the following text field values as the user tags somebody in a text field.

    I'm tagging @M|
    I'm tagging @Matt|
    I'm tagging @Matt |

We type "I'm tagging @M", then we select a suggested name, which results in "I'm tagging @Matt". That part works fine. But as soon as the tag name is added, we have our code immediately insert a space " ". This is where the problem comes in. We'll end up in an IME loop like the following:

    I'm tagging @Matt|
    I'm tagging @Matt |
    I'm tagging @Matt|
    I'm tagging @Matt |
    I'm tagging @Matt|
    I'm tagging @Matt |

First we tell the IME that the value is "I'm tagging @Matt|". Then we immediately tell the IME that the value is "I'm tagging @Matt |". Then the IME sends us a `TextEditingDeltaNonTextUpdate` telling us the caret should be positioned as "I'm tagging @Matt|". This is different than our app-side state, so we send the value back to the IME "I'm tagging @Matt|". Then the IME catches up with our earlier message and tells us to move the caret to "I'm tagging @Matt |". So we make that change. And then this pattern continues.

It's unclear how we're supposed to differentiate IME deltas that essentially "confirm" a value we've already sent, versus IME deltas that want us to change the selection in response to user actions.

**Comment by matthew-carroll** [comment] 2023-01-21 00:54
FYI - Here's a change that we made in `super_editor` to hack around this. Obviously, we'd like to remove this hack as soon as possible, but feel free to use this for reference: https://github.com/superlistapp/super_editor/pull/974

**Comment by Renzo-Olivares** [comment] 2023-01-26 21:55
Sorry for the delayed response on this, and thanks for bringing it to my attention. Your example makes me think this issue might be related to https://github.com/flutter/flutter/issues/89394. 

I'm currently investigating if its possible to differentiate a change that is the result of the engine syncing its state with the frameworks through a `setEditingState` call, or if the delta originated from the IME. I think that might help the issue here.

We have faced similar issues on the framework's `EditableText` 
https://github.com/flutter/flutter/blob/a04ab7129b373a1b887b150e8178c0846e36204a/packages/flutter/lib/src/widgets/editable_text.dart#L3378 and this was the PR that addressed it #66864. It looks like we try to batch all of our edits into one before we send it to the engine, I'm not sure if this is possible with `super_editor`.

I agree about the unnecessary footgun of having to check `_localValue == _incomingValue`, maybe `TextInputClient` should provide that check, or it could be clearly stated in the documentation.

**Comment by Renzo-Olivares** [comment] 2023-05-17 18:40
I tried making a minimal example to reproduce this in a Flutter TextField but was unable to.

**Closed** 2023-05-26 21:07 UTC
Labels: a: text input, engine, platform-mac, a: desktop, has reproducible steps, P5, found in release: 3.3, found in release: 3.7

**Comment by matthew-carroll** [comment] 2023-05-26 21:25
@angelosilvestre - Can you confirm that this issue was solved in Super Editor?

**Comment by angelosilvestre** [comment] 2023-06-03 19:39
@matthew-carroll I removed our workaround code and tested it in both master and stable branches:

SuperEditor: I wasn't able to reproduce it in both branches. I guess one of our recent changes to the IME code fixed the bug for us.

SuperTextField: I was able to reproduce it in stable, but not in master, so I think it's solved.
