### ISSUE TITLE
Add-to-app mode got NullPointerException when use BackgroundMode.transparent

### ISSUE THREAD

**Issue by peterlpt** [flutter/flutter#56125] opened 2020-05-01 15:32 UTC
cause I can't find `flutter create bug` for the add-to-app mode, I reproduce the problem base on template module created by `flutter create module` and blank host app created by Android Studio.

## Steps to Reproduce

1. modification point:
* configure the host app and the flutter module follow [Adding a Flutter screen to an Android app](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen)
* host app's MainActivity add a button, click to Jump flutter module with transparent background.

host app:

```java
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // click button to jump flutter activity
        findViewById(R.id.tv_test).setOnClickListener((view) -> {
            Intent intent = FlutterActivity.withNewEngine()
                    // with transparent BackgroundMode,  app run fine if comment this line
                    .backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent) 
                    .build(MainActivity.this);
            startActivity(intent);
        });
    }
}
```

flutter module `main.dart` , replace template code with:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter Module Page'),
        ),
        body: Center(
          child: Text('This is a flutter module page'),
        ),
      )
    );
  }
}
```

2. run host app, and got a cash when i click button on host app's mainActivity 
3. **comment the backgroundMode config, and app will run fine.**
4. follow the cash stack trace, found that: 

```
Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference
```

debug host app, found that we create FlutterView with 

```java
 private FlutterView(
      @NonNull Context context,
      @Nullable AttributeSet attrs,
      @NonNull FlutterTextureView flutterTextureView) {
    super(context, attrs);

    this.flutterTextureView = flutterTextureView;
   //here assign a null flutterSurfaceView to renderSurface ?
    this.renderSurface = flutterSurfaceView;

    init();
  }
```

<details>
  <summary>Logs</summary>

```
2020-05-01 23:09:54.917 26615-26615/? I/Timeline: Timeline: Activity_launch_request time:15239977
2020-05-01 23:09:54.939 26615-26615/? W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@e4029bb
2020-05-01 23:09:54.944 26615-26653/? D/ViewContentFactory: initViewContentFetcherClass
2020-05-01 23:09:54.945 26615-26653/? I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
2020-05-01 23:09:54.945 26615-26653/? D/ViewContentFactory: createInterceptor took 0ms
2020-05-01 23:09:54.947 26615-26696/? I/ResourceExtractor: Found extracted resources res_timestamp-1-1588345751632
2020-05-01 23:09:55.009 26615-26615/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-05-01 23:09:55.010 26615-26615/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.peter.myapplication, PID: 26615
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.peter.myapplication/io.flutter.embedding.android.FlutterActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference
        at io.flutter.embedding.android.FlutterView.attachToFlutterEngine(FlutterView.java:699)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:290)
        at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:519)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:413)
        at android.app.Activity.performCreate(Activity.java:7894)
        at android.app.Activity.performCreate(Activity.java:7881)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7520) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2020-05-01 23:09:55.020 26615-26615/? I/Process: Sending signal. PID: 26615 SIG: 9
```

```
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.3 19D76, locale
    zh-Hans-CN)
    • Flutter version 1.17.0-3.2.pre at /Users/peter/Data/flutter
    • Framework revision 2a7bc389f2 (9 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/peter/Data/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/peter/Data/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

</details>

**Comment by BernardGatt** [comment] 2020-05-04 10:43
I am getting the same error but with FlutterFragment. Setting the render mode to Texture causes the exact error.

This was fixed some time ago on master, see:
https://github.com/flutter/flutter/issues/53857
https://github.com/flutter/engine/pull/17486

Not sure how it resurfaced on the latest beta.

**Comment by iapicca** [comment] 2020-05-04 11:38
Hi @peterlpt 
the PR @BernardGatt mentioned might not have reach `beta` yet,
are you experiencing the issue with the latest stable master?
Thank you

**Comment by BernardGatt** [comment] 2020-05-04 11:41
1.12 stable works fine. This issue has been happening on beta for quite some time.

Was hoping it gets fixed before we reach 1.17 stable.

**Comment by peterlpt** [comment] 2020-05-05 03:40
> Hi @peterlpt
> the PR @BernardGatt mentioned might not have reach `beta` yet,
> are you experiencing the issue with the latest stable master?
> Thank you

1.12 stable and 1.14 beta works fine.
Was hoping it gets fixed before we reach next beta upgrade.

**Comment by TahaTesser** [comment] 2020-05-05 07:42
Hi @peterlpt 
Can you please upgrade to latest `master` channel and confirm issue doesn't exist?
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-05-06 13:42
@BernardGatt thanks for the investigating,
I can't reproduce it with current master `1.18.0-10.0.pre`

**Comment by jmagman** [comment] 2020-05-07 21:21
https://github.com/flutter/engine/pull/17486 is in 1.18.0-dev.0.0, which is currently on the dev channel.

\cc @dnfield @jason-simmons Is this worth a hotfix?

**Comment by dnfield** [comment] 2020-05-07 23:29
IMO this should not be hotfixed. It only impacts a small subset of developers, and we should just let it flow through our normal process. If you really need this fix, picking up dev should be fine for now.

Closing as fixed

**Closed by dnfield** 2020-05-07 23:29 UTC
Labels: a: existing-apps, engine, found in release: 1.17, has reproducible steps, severe: regression

**Comment by BernardGatt** [comment] 2020-05-08 08:33
Not sure about the amount of developers this is effecting but the new release process suggests that this fix won't hit stable until next quarter. Does it make sense to have everyone impacted by this switch to dev (and potentially break other things) just for this fix issue.

**Comment by dnfield** [comment] 2020-05-08 13:05
It will be on beta soon :)

I understand that this is frustrating. At the same time, there are significant risks to doing a hotfix, and there are a lot of bugs getting fixed every day that flow through this way, including other crash related bugs.

If this bug was affecting all development on Android, or meant all flutter apps would crash on a specific Android version, or meant no flutter app could be accepted to the store, or would always crash for users turning on accessibility services, or something of that nature, it's a better candidate for a hotfix.

If using stable is important for you, you could also locally patch your engine against the stable revision and have this fixed on stable as well.

**Comment by peterlpt** [comment] 2020-05-10 00:34
> Hi @peterlpt
> Can you please upgrade to latest `master` channel and confirm issue doesn't exist?
> Thank you

Unfortunately, `master` channel break my build,  I'm using in China, means that some latest dependencies might can not be reached, and i had tried several mirror sites and vpn. Just like:

```shell
> Could not resolve io.flutter:x86_64_debug:1.0.0-9b905d3f03f27a332ad861934da0f5111c24d347.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-9b905d3f03f27a332ad861934da0f5111c24d347/x86_64_debug-1.0.0-9b905d3f03f27a332ad861934da0f5111c24d347.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-9b905d3f03f27a332ad861934da0f5111c24d347/x86_64_debug-1.0.0-9b905d3f03f27a332ad861934da0f5111c24d347.pom'.
               > Remote host closed connection during handshake
``` 

<details>
  <summary>flutter doctor -v</summary>
$ flutter doctor -v

[✓] Flutter (Channel master, 1.19.0-1.0.pre.21, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.19.0-1.0.pre.21 at /Users/peter/Data/flutter
    • Framework revision f5d2c8c770 (24 hours ago), 2020-05-08 17:35:40 -0700
    • Engine revision 9b905d3f03
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 617bc54b71)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/peter/Data/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/peter/Data/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 1 category.

</details>

**Comment by peterlpt** [comment] 2020-05-10 03:16
> It will be on beta soon :)
> 
> I understand that this is frustrating. At the same time, there are significant risks to doing a hotfix, and there are a lot of bugs getting fixed every day that flow through this way, including other crash related bugs.
> 
> If this bug was affecting all development on Android, or meant all flutter apps would crash on a specific Android version, or meant no flutter app could be accepted to the store, or would always crash for users turning on accessibility services, or something of that nature, it's a better candidate for a hotfix.
> 
> If using stable is important for you, you could also locally patch your engine against the stable revision and have this fixed on stable as well.

@dnfield 
Waiting for this beta upgrade. 
And now, my app cash on `Channel stable, v1.17.0` ...
Considering the risk of version upgrades, modify the engine to locally patch may not be a good choice for me.

<details>
  <summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale
    zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/peter/Data/flutter
    • Framework revision e6b34c2b5c (7 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

</details>

**Comment by lslv1243** [comment] 2020-07-06 11:46
There is a workaround to make it work on Flutter 1.17: https://github.com/flutter/flutter/issues/57096#issuecomment-654184123
