### ISSUE TITLE
This thread has been automatically locked since there has not been any recent activity after it was closed. If you are still experiencing a similar issue, please open a new bug, including the output of `flutter doctor -v` and a minimal reproduction of the issue.

### ISSUE THREAD

**Issue by TechnoAtanu** [flutter/flutter#137603] opened 2023-10-31 09:45 UTC
This thread has been automatically locked since there has not been any recent activity after it was closed. If you are still experiencing a similar issue, please open a new bug, including the output of `flutter doctor -v` and a minimal reproduction of the issue.

_Originally posted by @github-actions[bot] in https://github.com/flutter/flutter/issues/122281#issuecomment-1484680513_
            

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E261 darwin-arm64, locale en-IN)
    • Flutter version 3.10.5 on channel stable at /Users/technoexponent10/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/technoexponent10/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/technoexponent10/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • FC3D43E5-016E-418B-A9AB-6AF447CFC83B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by dam-ease** [comment] 2023-10-31 10:48
Hi @TechnoAtanu. When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:


- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps


I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-10-31 10:48 UTC
Labels: in triage

**Comment by TechnoAtanu** [comment] 2023-11-03 05:44
Code example

**Comment by TechnoAtanu** [comment] 2023-11-03 05:46
Code Example
TeXView(
                                      renderingEngine:
                                          const TeXViewRenderingEngine.katex(),
                                    
                                      child: TeXViewDocument(
                                          _jambController
                                              .jambQuestionsList[_jambController
                                                  .modelIndex.value]
                                              .questions![_jambController
                                                  .questionIndex.value]
                                              .questionDetails!
                                              .questionText
                                              .toString()
                                              .trim(),
                                          style: TeXViewStyle(
                                              contentColor: Color(0xFF303030),
                                              fontStyle: TeXViewFontStyle(
                                                fontSize: 18,
                                                fontFamily: 'Lato',
                                              ))),
                                    ),
Error log
2023-11-03 11:01:23.108054+0530 Runner[18318:126310] flutter: Server Error: SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8) #0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:520:9)
#1      _rootRunUnary (dart:async/zone.dart:1407:47)
<asynchronous suspension>
#2      _NativeSocket._resolveHost (dart:io-patch/socket_patch.dart:1000:20)
<asynchronous suspension>
#3      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1014:21)
<asynchronous suspension>
2023-11-03 11:01:23.108346+0530 Runner[18318:126310] flutter: Server Error: SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8) #0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:520:9)
#1      _rootRunUnary (dart:async/zone.dart:1407:47)
<asynchronous suspension>
#2      _NativeSocket._resolveHost (dart:io-patch/socket_patch.dart:1000:20)
<asynchronous suspension>
#3      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1014:21)
<asynchronous suspension>
2023-11-03 11:01:23.108517+0530 Runner[18318:126310] flutter: Server Error: SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8) #0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:520:9)
#1      _rootRunUnary (dart:async/zone.dart:1407:47)
<asynchronous suspension>
#2      _NativeSocket._resolveHost (dart:io-patch/socket_patch.dart:1000:20)
<asynchronous suspension>
#3      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1014:21)
<asynchronous suspension>
2023-11-03 11:01:23.108651+0530 Runner[18318:126310] flutter: Server Error: SocketException: Failed host lookup: 'localhost' (OS Error: nodename nor servname provided, or not known, errno = 8) #0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:520:9)
#1      _rootRunUnary (dart:async/zone.dart:1407:47)
<asynchronous suspension>
#2      _NativeSocket._resolveHost (dart:io-patch/socket_patch.dart:1000:20)
<asynchronous suspension>
#3      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1014:21)
<asynchronous suspension>
Flutter Doctor Output
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E261 darwin-arm64, locale en-IN)
• Flutter version 3.10.5 on channel stable at /Users/technoexponent10/Development/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/796c8ef79279f9c774545b3771238c3098dbefab (5 months ago), 2023-06-13 15:51:02 -0700
• Engine revision 45f6e00911
• Dart version 3.0.5
• DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
• Android SDK at /Users/technoexponent10/Library/Android/sdk
• Platform android-33, build-tools 33.0.0
• ANDROID_HOME = /Users/technoexponent10/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14E300c
• CocoaPods version 1.12.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.83.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.74.0

[✓] Connected device (3 available)
• iPhone 14 Pro Max (mobile) • FC3D43E5-016E-418B-A9AB-6AF447CFC83B • ios • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
• macOS (desktop) • macos • darwin-arm64 • macOS 13.3.1 22E261 darwin-arm64
• Chrome (web) • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
• All expected network resources are available.

**Comment by dam-ease** [comment] 2023-11-06 08:37
Hi @TechnoAtanu. Kindly upgrade to the latest `stable` channels and try this on with a stable internet connection to see if this still persists?

**Comment by TechnoAtanu** [comment] 2023-11-17 12:30
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.3.1 22E261 darwin-arm64, locale en-IN)
    • Flutter version 3.16.0 on channel stable at /Users/technoexponent10/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (2 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/technoexponent10/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/technoexponent10/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • FC3D43E5-016E-418B-A9AB-6AF447CFC83B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!


This is my flutter doctor -v result. Same I am facing the issue.

**Comment by dam-ease** [comment] 2023-11-20 07:20
Thanks for sharing these. 
Please can you create a new flutter project and run `flutter run -v` to confirm whether this issue exists with a new project or is peculiar to existing projects. If this exists with new projects, please share the output of your `flutter run -v` and if with existing projects, alongside the output of your `flutter run -v`, kindly share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
