### ISSUE TITLE
Auto Update windows-macos app fluently and deployment

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#80982] opened 2021-04-22 19:16 UTC
It has been two years using the framework and I love how it is evolving, however as more platform is added there is a need to have a unified of making an update to a deployed app and making auto-update more fluently than ever, this is why I think it is very important to have a clear way on how the windows, mac os can be updated and deployed sort of providing auto-update after packaging the app.

**Comment by stuartmorgan** [comment] 2021-04-22 21:57
Duplicate of https://github.com/flutter/flutter/issues/63622

**Closed by stuartmorgan** 2021-04-22 21:57 UTC
