### ISSUE TITLE
Enable flutter to share Dart SDK for mixed-project building

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#22004] opened 2018-09-18 21:29 UTC
For projects with a flutter component (front end) and back end in Dart, you end up needing to install two SDKs, and then go through gymnastics to share the code when building between the SDKs. 

Would be good to do one or more of these:

- Document (with a sample project) how this can be done easily with some shared code,
- Enable Flutter to optionally install and keep up-to-date a Dart SDK and not carry its own subset of the Dart SDK
- Ship the full Dart SDK with Flutter so that anything you can build in Dart you can also build in Flutter.

**Comment by zoechi** [comment] 2018-09-25 08:48
The Flutter SDK is customized and there is no way to share the SDK between web and Flutter.

I have split my projects to 
- a package that contains platform-independent code and that I share with all platforms
- a Flutter package and
- an Angular package that have the shared package as dependency

Closing as working as intended.

**Comment by jonahwilliams** [comment] 2020-05-23 18:54
We now expose `dart` through the flutter sdk. The remaining work is capture in https://github.com/flutter/flutter/issues/56573

**Closed by jonahwilliams** 2020-05-23 18:54 UTC
Labels: d: examples, dependency: dart, tool
