### ISSUE TITLE
Android - Release Mode - Unhandled PlatformException in dart_vm_initializer

### ISSUE THREAD

**Issue by SamuelMTDavies** [flutter/flutter#135983] opened 2023-10-04 14:18 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Running my app in release mode on a real device or simulator crashes. I can't make a minimum reproducible sample as I have no clue what is causing the crash. I initially thought it was due to the video_player plugin but removing it did nothing. I have reverted back to the last commit that gave me a working version of the application but that is now no longer working. I am completely at a loss. 

I have cleaned and invalidated the caches multiple times. Even going back to an old working commit has now broken my CI/CD builds. So using the exact same commit that gave me a working appbundle 9 days ago now gives me an app bundle that crashes.

### Expected results

App should run as is does in profile and debug mode but with release tree shaking etc

### Actual results

App crashes when in release mode.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
E/flutter (25890): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (25890): #0      Hya.cUb (kyh:86)
E/flutter (25890): <asynchronous suspension>
E/flutter (25890): #1      Nle (jyh:120)
E/flutter (25890): <asynchronous suspension>
E/flutter (25890): #2      uJe (Mth:12)
E/flutter (25890): <asynchronous suspension>
E/flutter (25890): #3      main (UCh:44)
E/flutter (25890): <asynchronous suspension>
E/flutter (25890): 

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB)
    • Flutter version 3.13.6 on channel stable at /Users/sam/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (7 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/sam/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Volumes/NVMe 2TB Drive/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Volumes/NVMe 2TB Drive/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos            • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment] 2023-10-04 15:11
Hi @SamuelMTDavies. Thanks for filing this. I see similar issues with the same log seems to be related to `video_player` or `webview_flutter`. Are you making use of any of these?
Also, can you please run your command with `-v` and share the full output in -txt?

**Comment by SamuelMTDavies** [comment] 2023-10-04 15:58
> Hi @SamuelMTDavies. Thanks for filing this. I see similar issues with the same log seems to be related to `video_player` or `webview_flutter`. Are you making use of any of these?
> Also, can you please run your command with `-v` and share the full output in -txt?

I saw those and have completely removed the video player package with no effect.

I will send a verbose log ASAP as this is effecting a large production application.

**Comment by SamuelMTDavies** [comment] 2023-10-04 16:16
@dam-ease 
[verbose-log.txt](https://github.com/flutter/flutter/files/12805763/verbose-log.txt)

**Comment by dam-ease** [comment] 2023-10-05 07:32
Thanks for your response. I'd label this for more insights but it would be really helpful if you could help provide reproducible information that produces the crash (if possible a pattern you observe).
Thank you!

**Comment by SamuelMTDavies** [comment] 2023-10-05 13:08
I can't produce a minimal reproducible example as of yet. I am painstakingly going back over every single commit and running it against the version of stable that was released at the time and the current stable HEAD to isolate exactly what caused the problem. However this is over a number of commits with multiple changes and across 4 stable releases.

As soon as I have more information I will post my finding here. Currently I am down to a few last changes to test.

**Comment by SamuelMTDavies** [comment] 2023-10-09 09:38
Ok so I have narrowed this down to a code magnification and obfuscation issue. The following changes were made and this caused the release build to stop working. Beyond that I don't know why it would lead to this error or which parts of these changes are the offending lines. Any help and guidance would be greatly appreciated. Maybe it's how code magnification and obfuscation interact with certain packages (video_player) that cause the crash?


app/build.gradle
```
buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
``` 

proguard-rule.pro
```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class io.flutter.plugin.editing.** { *; }
#Firebase
-keep class com.google.firebase.** { *; }
-keep class com.firebase.** { *; }
-keep class org.apache.** { *; }
-keepnames class com.fasterxml.jackson.** { *; }
-keepnames class javax.servlet.** { *; }
-keepnames class org.ietf.jgss.** { *; }
-dontwarn org.w3c.dom.**
-dontwarn org.joda.time.**
-dontwarn org.shaded.apache.**
-dontwarn org.ietf.jgss.**
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes EnclosingMethod
-keepattributes InnerClasses
-keep class androidx.lifecycle.DefaultLifecycleObserver
#Crashlytics
-keepattributes SourceFile,LineNumberTable        # Keep file names and line numbers.
-keep public class * extends java.lang.Exception
-keep class com.ito_technologies.soudan.** { *; }
```


grade.properties
```
android.enableR8.fullMode=true
android.bundle.enableUncompressedNativeLibs=true
extra-gen-snapshot-options=--obfuscate
```


@dam-ease

**Comment by navaronbracke** [comment] 2023-10-09 10:24
@SamuelMTDavies I had a similar issue myself a few weeks ago. I had also set up my own proguard file, which apparently broke release builds.

The Flutter tool adds some default settings for release builds.
I did two things to fix it:
- I removed the `minifyEnabled`, `shrinkResources` as those are added already.
- since Flutter adds _its own proguard rules_, I kind of broke my build by doing 

```
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```
like you did, as that excludes the Flutter specific rules.
So I removed the `proguardFiles` line, as Flutter already has the default specify "proguard-rules.pro" as an extra ruleset.
You can add extra rules to `proguard-rules.pro`, as usual.

See https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L302-L312
and https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter_proguard_rules.pro

**Comment by SamuelMTDavies** [comment] 2023-10-09 12:22
@navaronbracke Thanks for chiming in with your experience.

So just for clarity. What changes did you make to which files in the end?

My project doesn't have a proguard file at the moment as I reverted back all the changes mentioned above. Did you create one and then not mention `class io.flutter.*` as that is already handle by the flutter-tools?

Did you have the following lines in your project?

grade.properties
```
android.enableR8.fullMode=true
android.bundle.enableUncompressedNativeLibs=true
extra-gen-snapshot-options=--obfuscate
```

**Comment by navaronbracke** [comment] 2023-10-09 12:43
I have Gradle 8.0.1 and I have the following setup: 

```
    // android/app/build.gradle 
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
    
    // android/app/proguard-rules.pro
    # This file can be used to add extra ProGuard rules.
    # The Flutter Gradle Plugin already includes the rules in "proguard-android.txt"
    # and it also defines some rules itself.
    
    // android/gradle.properties
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false    
```

Yes, my proguard file is currently empty. Perhaps some of your extra settings break it? I would try to see with which settings enabled it still works.

**Comment by SamuelMTDavies** [comment] 2023-10-09 12:57
Ok thank you.

I'm not very familiar with the android build system but from what I can tell the three following lines are only necessary because you are using Gradle 8.0.1 and not a lower version correct?
```
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false  
```

I will try add my proguard rules and see if it breaks again or not without the flutter rules.

**Comment by navaronbracke** [comment] 2023-10-09 13:04
Yes, Android Studio added those for me when running the migration assistant from 7.5 -> 8.0

**Comment by SamuelMTDavies** [comment] 2023-10-09 13:10
Ok so hopefully this clears things up @dam-ease 

The offending code is as follows:

```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class io.flutter.plugin.editing.** { *; }
```

I think this is interfering with the flutter-tools default proguard settings. It's not clear in the documentation and there has been a lot of movement on this as flutter has progressed. Are the docs in a repo that I can contribute to with a PR, if so please let me know where it is?

It's worth checking with the other issue owners if they have proguard rules in place when it's not necessary.

Thank you @navaronbracke for helping shed light on the doubling up of proguard rules.

**Comment by camsim99** [comment] 2023-10-19 18:10
Closing this issue at it seems to be resolved. An issue filed to create documentation for defining proguard rule for plugins will be linked in the future.

**Closed by camsim99** 2023-10-19 18:10 UTC
Labels: platform-android, a: release, c: fatal crash, needs repro info, team-android
