### ISSUE TITLE
Fragment Programs hot reload, but FragmentShaders do not

### ISSUE THREAD

**Issue by craiglabenz** [flutter/flutter#125079] opened 2023-04-19 00:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Set up an app like this
    ```dart
    late FragmentShader loadedShader;

    Future<void> main() async {
      loadedShader = (await FragmentProgram.fromAsset('assets/shaders/my_shader.frag')).fragmentShader();
      runApp(const MainApp());
    }
    ```

2. Use `loadedShader` somewhere in your widget tree.
3. Make changes to the GLSL code within `my_shader.frag`.
4. Hot reload (NOT hot restart)
5. Notice your shader NOT update

### Expected results

Since we are excited about hot reloading shaders, I would expect the above to trigger repaint the app with my updated shader.

### Actual results

The app never updates and the new shader code is not included.

### Code sample

The following changes to the above code make hot reloads work just fine. I understand that this is the intended way for developers to include custom shaders, but it's a bit of a foot-gun.

```dart
late FragmentProgram loadedProgram;

Future<void> main() async {
  loadedProgram = await FragmentProgram.fromAsset('assets/shaders/my_shader.frag');
  runApp(const MainApp());
}
```

And then in your widget tree:

```dart
SomeWidgetThatAcceptsAFragmentShader(
  shader: loadedProgram.fragmentShader();
);
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.9.0-22.0.pre.14, on macOS 13.3 22E252 darwin-arm64,
    locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.77.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by Zabadam** [comment] 2023-08-11 03:36
Does `my_shader.frag` have any `#include <other_file.glsl>` statements?

I have noticed issues hot reloading in those cases as well. Searching for an existing issue on it now.

**Comment by domesticmouse** [comment] 2023-08-11 09:56
> Does `my_shader.frag` have any `#include <other_file.glsl>` statements?
> 
> I have noticed issues hot reloading in those cases as well. Searching for an existing issue on it now.

Please raise a new issue with a minimised reproduction case. Thanks!

**Comment by domesticmouse** [comment] 2023-08-11 09:57
Closing this as working as intended.

**Closed** 2023-08-11 09:57 UTC
Labels: engine, P2, team-engine, triaged-engine
