### ISSUE TITLE
Inconsistency of rendering column with buttons between Web and Android

### ISSUE THREAD

**Issue by andrey-brill** [flutter/flutter#120693] opened 2023-02-14 15:00 UTC
## Steps to Reproduce

1. Create Column with `ElevatedButton`-s (or `OutlineButton`-s, or `TextButton`-s)
2. Run on Web and Android (probably desk, iOS also)

[render_issue.zip](https://github.com/flutter/flutter/files/10733637/render_issue.zip)

**Expected results:** 

Same render for web and mobile.

**Actual results:** 

<img width="382" alt="image" src="https://user-images.githubusercontent.com/19698358/218763578-18141184-bd75-4985-8938-e55d9e1db7a9.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/19698358/218763927-f6af446b-ffd7-49b0-bb94-25c21b1a885a.png">

<details>
<summary>Code sample</summary>

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            ElevatedButton(onPressed: _incrementCounter, child: Text("1")),
            ElevatedButton(onPressed: _incrementCounter, child: Text("2")),
            ElevatedButton(onPressed: _incrementCounter, child: Text("3")),
            ElevatedButton(onPressed: _incrementCounter, child: Text("4")),
            ElevatedButton(onPressed: _incrementCounter, child: Text("5")),
          ],
      ),
    );
  }
```

</details>

<details>
<summary> `flutter doctor -v`  </summary>

```
[√] Flutter (Channel beta, 3.7.0-1.5.pre, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
    • Flutter version 3.7.0-1.5.pre on channel beta at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 099b3f4bf1 (4 weeks ago), 2023-01-20 18:35:12 -0800
    • Engine revision 45c5586f2a
    • Dart version 2.19.0 (build 2.19.0-444.6.beta)
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at ...
    • Platform android-33, build-tools 33.0.1
    • Java binary at: ...
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 110.0.5481.77
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 110.0.1587.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by maRci002** [comment] 2023-02-14 20:28
Try changing your `ThemeData` to use uniform
```dart
visualDensity: VisualDensity.standard,
materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
```

**Comment by danagbemava-nc** [comment] 2023-02-15 06:52
Hi @andrey-brill, as pointed out above you can achieve the desired effect by setting the visualDensity and the `materialTapTargetSize`. 
See https://github.com/flutter/flutter/issues/85729#issuecomment-878640953 for more context. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/85729. 

Thank you

**Closed by danagbemava-nc** 2023-02-15 06:52 UTC
Labels: in triage
