### ISSUE TITLE
Different text alignment on Web, Web-skia compared to everything else

### ISSUE THREAD

**Issue by ilopX** [flutter/flutter#63690] opened 2020-08-13 18:53 UTC
Hi devs!!! :smiley:

I get different font rendering on platforms: **Windows**, **Web**, **Web-skia**

![Captu2re](https://user-images.githubusercontent.com/8049534/90174231-5480da00-ddae-11ea-8cdd-c61e36485125.PNG)

| | Platform | Font Height | Font Family | Vertical Align | Unknown chars "(", ")"|
| --- | --- | --- |--- |--- |--- |
| :blush: | `flutter build windows` | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| :confused: | `flutter build web` |  :white_check_mark: | :white_check_mark: | :x: | :white_check_mark: |
| :cry: | `flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true` **Flutter version ~~1.21.0-10.0.pre.18~~ 1.21.0-10.0.pre.111** |  :x: | :x: | :heavy_multiplication_x: | :x: |
<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final textStyle = const TextStyle(
      fontFamily: 'Arial',
      fontSize: 32,
      height: 3,
      color: Colors.white,
    );

    return MaterialApp(
      theme: ThemeData.dark(),
      home: Scaffold(
        body: Center(
          child: Container(
            height: textStyle.fontSize * textStyle.height * 3,
            color: Colors.grey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  color: Colors.red,
                  child: Text(
                    '01: begin: Alignment(1, 1)',
                    style: textStyle.copyWith(fontFamily: 'Times New Roman'),
                  ),
                ),
                Container(
                  color: Colors.green,
                  child: Text(
                    '02: end: Alignment(-1, -1)',
                    style: textStyle,
                  ),
                ),
                Container(
                  color: Colors.blue,
                  child: Text(
                    '03: colors[red, blue]',
                    style: textStyle.copyWith(fontFamily: 'Georgia'),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.18, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.21.0-10.0.pre.18 at c:\flutter
    • Framework revision c8d051295a (3 days ago), 2020-08-11 00:26:02 -0400
    • Engine revision a62703778b
    • Dart version 2.10.0 (build 2.10.0-5.0.dev e2a67723ca)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ilopX\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.4.29613.14
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[√] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.535]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

Thanks :pray:

**Comment by markusaksli-nc** [comment] 2020-08-14 06:58
Hi @ilopX 
This should have been fixed by https://github.com/flutter/engine/pull/20272 as discussed in https://github.com/flutter/flutter/issues/56319 and https://github.com/flutter/flutter/issues/62595. I can't reproduce the web-skia issue you are seeing on the latest master `1.21.0-10.0.pre.94`. Could you try upgrading to the latest master and trying again? What browser are you seeing this on?

The alignment is a different issue, checking for duplicates.
Thank you

**Comment by ilopX** [comment] 2020-08-14 09:53
Hello @markusaksli-nc 

Unfortunately I see the same picture 😢

**Chrome:** 84.0.4147.125 (Official Build) (64-bit)
**Firefox:** 79.0
**Microsoft Edge:** 44.18362.449.0

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.95, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.21.0-10.0.pre.95 at C:\flutter_origin
    • Framework revision 48b9c3d39b (3 hours ago), 2020-08-14 00:04:33 -0700
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ilopX\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.4.29613.14
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[√] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.535]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```

</details>

**Comment by markusaksli-nc** [comment] 2020-08-14 10:25
@ilopX Did you add the custom fonts to your project? On windows, in my experience Flutter can detect fonts installed on the system. As a general rule, I'd add any fonts you want to use to the project as described in [Use a custom font](https://flutter.dev/docs/cookbook/design/fonts), otherwise, the text will use the system default, as described in [fontFamily](https://api.flutter.dev/flutter/painting/TextStyle/fontFamily.html).

On Windows, it seems like Flutter can use any fonts installed on the system. It's strange that some defaults exist for `flutter build web --release`. I would have expected for the fonts to just be the default like what happens with `flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true`.

Still unsure where this padding/alignment stems from. Doesn't seem like a regression but I would have expected it to already have a bunch of duplicate issues in that case.

**Comment by ilopX** [comment] 2020-08-14 11:13
> Did you add the custom fonts to your project?

No. I'm use empty project `flutter create some`

**Sample Project**
https://github.com/ilopX/web_skia_issues
online web-skia: https://ilopx.github.io/web_skia_issues/index.html

**Windows**
![image](https://user-images.githubusercontent.com/8049534/90242275-60fc4580-de35-11ea-8aa9-6ab3ad3c4af5.png)

**Comment by ilopX** [comment] 2020-08-14 12:16
@markusaksli-nc If I use a custom font then an unknown character pops up

`flutter build web`
![issue_3_5](https://user-images.githubusercontent.com/8049534/90247175-ba1ca700-de3e-11ea-9e55-7d8947e6d4af.PNG)

`flutter build web  --dart-define=FLUTTER_WEB_USE_SKIA=true`
![issue_3](https://user-images.githubusercontent.com/8049534/90247227-d7517580-de3e-11ea-8b6d-423f0f8f224e.PNG)

source: https://github.com/ilopX/issue_web_skia_custom_font_unknown_charset
online web-skia: https://ilopx.github.io/issue_web_skia_custom_font_unknown_charset/

<details>
  <summary>Code Sample</summary>

`pubspec.yaml`
```yaml
name: we_skia_custom_font
description: we_skia_custom_font.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/Segoe_UI.ttf

```

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      home: Scaffold(
        body: Center(
          child: Container(
            height: 70,
            color: Colors.grey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  color: Colors.blue,
                  child: Text(
                    '01: Default font [ end: Alignment(-1, -1) ]',
                  ),
                ),
                Container(
                  color: Colors.amber,
                  child: Text(
                    '02: Custom font [  end: Alignment(-1, -1) ]',
                    style: const TextStyle(fontFamily: 'Arial'),
                  ),
                ),
                Container(
                  color: Colors.green,
                  child: Text(
                    '03: Import asset custom font [ end: Alignment(-1, -1) ]',
                    style: const TextStyle(
                      fontFamily: 'Segoe',
                      color: Colors.white,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.95, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.21.0-10.0.pre.95 at C:\flutter_origin
    • Framework revision 48b9c3d39b (3 hours ago), 2020-08-14 00:04:33 -0700
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ilopX\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.4.29613.14
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[√] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.535]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

Thank you 🙏

**Comment by markusaksli-nc** [comment] 2020-08-14 12:46
Like I said the fonts being reverted to default is expected behavior here since you have not added custom fonts to the project. The height issue is just a duplicate of https://github.com/flutter/flutter/issues/62948. What is notable here is the difference between the Text baselines when comparing everything else to web, and web with canvaskit:
<details>
 <summary>Android, iOS, Windows</summary>

![Annotation 2020-08-14 153401](https://user-images.githubusercontent.com/68219924/90250162-55fce180-de44-11ea-9121-b4b3ebac2061.png)
</details>
<details>
 <summary>flutter build web --release and flutter run on web</summary>

![Annotation 2020-08-14 153416](https://user-images.githubusercontent.com/68219924/90250194-6319d080-de44-11ea-9d8a-a082fd82c12f.png)
</details>
<details>
 <summary>flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true</summary>

![Annotation 2020-08-14 153447](https://user-images.githubusercontent.com/68219924/90250200-657c2a80-de44-11ea-9041-0349c007d41e.png)
</details>
<details>
 <summary>flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true with forced correct Containter height</summary>

![Annotation 2020-08-14 153730](https://user-images.githubusercontent.com/68219924/90250204-66ad5780-de44-11ea-9359-de55e0948265.png)
</details>

Going to mark this as reproducible on the latest master `1.21.0-10.0.pre.94`.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final textStyle = const TextStyle(
      fontSize: 20,
      height: 3,
      color: Colors.white,
    );

    var _height = textStyle.fontSize * textStyle.height;

    return MaterialApp(
      theme: ThemeData.dark(),
      home: Scaffold(
        body: Center(
          child: Container(
            color: Colors.red,
            height: _height,
            alignment: Alignment.center,
            child: Container(
              color: Colors.blue,
              //height: _height,
              child: Text(
                  "Text height: ${textStyle.height}, Container height: $_height",
                style: textStyle.copyWith(fontFamily: 'Georgia'),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.94, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.94 at C:\Development\flutter_master
    • Framework revision 58feba8edd (65 minutes ago), 2020-08-13 21:16:04 -0700
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

**Comment by markusaksli-nc** [comment] 2020-08-14 12:52
@ilopX That is another known issue https://github.com/flutter/flutter/issues/58506

**Comment by ilopX** [comment] 2020-08-15 14:42
The characters '(' and ')' doesn't render on the web with some fonts when Skia is enabled. The characters are rendered when I disable custom font.

![dds](https://user-images.githubusercontent.com/8049534/90314015-51eec380-df19-11ea-8e6c-dc5a2884aadf.PNG)
[live](https://ilopx.github.io/issue_web_skia_custom_font_unknown_charset)


<details>
  <summary>😊flutter build web </summary>

![on](https://user-images.githubusercontent.com/8049534/90314409-3a650a00-df1c-11ea-8bef-d7027d606f97.PNG)
</details>

<details>
  <summary>😕flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true </summary>

![two](https://user-images.githubusercontent.com/8049534/90314470-af384400-df1c-11ea-9359-644089957c38.PNG)


</details>

<details>
  <summary>Minimal reproducible code sample</summary>

`pubspec.yaml`
```yaml
flutter:
  uses-material-design: true
  fonts:
    - family: Segoe_form_assets
      fonts:
        - asset: assets/Segoe_UI.ttf
```

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final defaultFont = TextStyle(
      fontFamily: 'Sergeo UI',
      fontSize: 30,
    );
    final customFont = TextStyle(
      fontFamily: 'Segoe_form_assets',
      fontSize: 30,
    );

    return MaterialApp(
      theme: ThemeData.dark(),
      home: Scaffold(
        body:Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text('(', style: defaultFont,),
                  Text('.',),
                  Text(')', style: defaultFont,),
                  Text('(', style: customFont,),
                  Text('.',),
                  Text(')', style: customFont,),
                ],
              ),
              Text('^'),
              Text('(~~)'),
            ],
          ),
        ) ,
      ),
    );
  }
}
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.111, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.21.0-10.0.pre.111 at C:\flutter_origin
    • Framework revision d1583fc39b (11 hours ago), 2020-08-14 20:09:41 -0700
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ilopX\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.4.29613.14
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[√] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.535]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```

</details>

**Comment by markusaksli-nc** [comment] 2020-08-17 07:42
Going to mark this as off topic since this is still probably just a duplicate of #58506

**Comment by yjbanov** [comment] 2020-08-20 20:05
@hterkelsen is working on a fix for CanvasKit, I think.
@mdebbar do we already have an issue for the HTML renderer?

The font family issue is probably due to a missing font file. When using the HTML renderer the browser can use the system font installed, but it doesn't let CanvasKit load system fonts (it's a browser limitation). Consider including a font file that CanvasKit would be able to download and use.

**Comment by mdebbar** [comment] 2020-08-20 20:54
@yjbanov the alignment/line-height issue in the HTML renderer is captured in https://github.com/flutter/flutter/issues/53914.

**Closed** 2020-10-15 23:33 UTC
Labels: P3, a: typography, e: web_canvaskit, e: web_html, engine, found in release: 1.21, has reproducible steps, platform-web
