### ISSUE TITLE
flutter object scanning using the camera without clicking

### ISSUE THREAD

**Issue by msiraj57** [flutter/flutter#135427] opened 2023-09-25 13:55 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi Everyone,
I want to ask a query related to the flutter scanning object.
For example if i want to hover the camera on any objects and it scans the object without clicking the capture the image.
thanks

### Proposal

as mention above

**Comment by danagbemava-nc** [comment] 2023-09-26 06:46
You can do this and there are examples of this available online. See https://flutterawesome.com/flutter-realtime-object-detection-with-tensorflow-lite/. 

Closing from here as this is not a bug or a feature request. 

PS: In the future, the best place to ask these types of questions is one the various flutter community channels. 

Thank youj

**Closed by danagbemava-nc** 2023-09-26 06:46 UTC
Labels: in triage
