### ISSUE TITLE
The API examples for the Shortcuts class don't compile in Dartpad

### ISSUE THREAD

**Issue by benthillerkus** [flutter/flutter#85977] opened 2021-07-06 16:14 UTC
The error says that the code won't compile to JavaScript.
[api.flutter.dev/flutter/widgets/Shortcuts-class.html](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html)

**Comment by asashour** [comment] 2021-07-06 16:59
This is duplicate of #85854

**Comment by darshankawar** [comment] 2021-07-07 08:16
Closing this as duplicate as linked above and [reason](https://github.com/flutter/flutter/issues/85854#issuecomment-874174271).

**Closed by darshankawar** 2021-07-07 08:16 UTC
Labels: in triage
