### ISSUE TITLE
Samsung keyboard does not show comma for number with decimals TextField

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#98200] opened 2022-02-10 16:00 UTC
Samsung keyboard shows disabled comma character and enabled dot character when using a `TextField` with `TextInputType.numberWithOptions(decimal: true)` keyboard type. In the Polish language, a comma is a correct decimal separator.

This issue looks like it's actually bug in Android or Samsung keyboard itself and it's not only for Polish language, those StackOverflow threads may suggest that (comments too):
* [Comma doesnt work on Samsung Android Keyboard](https://stackoverflow.com/q/65184373/3158312)
* [Decimal separator comma (',') with numberDecimal inputType in EditText](https://stackoverflow.com/q/3821539/3158312)

But just to be sure and have a record of such behavior I'm creating this issue.

<details><summary>Reproduction steps</summary>

Add `flutter_localizations` to dependencies in `pubspec.yaml`.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(
    const MaterialApp(
      locale: Locale('pl'),
      supportedLocales: [Locale('pl')],
      localizationsDelegates: GlobalMaterialLocalizations.delegates,
      home: Scaffold(
        body: Center(
          child: TextField(
            keyboardType: TextInputType.numberWithOptions(
              decimal: true,
            ),
          ),
        ),
      ),
    ),
  );
}
```

</details>

<details><summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale en-PL)
    • Flutter version 2.10.1 at /Users/albert/fvm/versions/2.10.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (20 hours ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/albert/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/albert/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Connected device (3 available)
    • SM A505FN (mobile) • R58M83HT50T • android-arm64  • Android 11 (API 30)
```

</details>

<details><summary>Screenshot on Samsung A50 with Android 11 with Polish as a default OS language</summary>

![Screenshot_20220210-170155](https://user-images.githubusercontent.com/4085280/153446588-23067460-dad9-4584-b95a-bff707ba9b02.jpg)

</details>

**Comment by darshankawar** [comment] 2022-02-11 06:57
Closing this as a duplicate of https://github.com/flutter/flutter/issues/61175

**Closed by darshankawar** 2022-02-11 06:57 UTC
Labels: in triage
