### ISSUE TITLE
Flutter web: url_launcher Plugin show blank page on dismiss

### ISSUE THREAD

**Issue by 10686142** [flutter/flutter#51461] opened 2020-02-26 10:01 UTC
My Flutter PWA shows a blank screen when returning from an opened url with the url_launcher plugin. Kind of like the problem people have experienced back in 2017 on android: https://github.com/flutter/flutter/issues/13123

Eitherway, I am seeing the blank screen on return when I have added the Flutter web App to my Iphone homescreen. I also experience a similar issue when I visit the PWA's website in my browser (so when it's not added to the homescreen); It triggers a new tab and than opens the email application, and when done I return to the blank screen.

## Steps to Reproduce

1. Launch a share url on Flutter web like:
`await launch("mailto:?subject=TestSubject&body=emailBoday");`

2. Let the app open the url scheme, like mailto.

3. Then hit return or cancel in that app, so you are returning the the PWA.

**Expected results:** 
![WhatsApp Image 2020-02-26 at 10 54 00 (1)](https://user-images.githubusercontent.com/23178404/75333430-6ca78000-5886-11ea-93de-c8b55b9fffdb.jpeg)

**Actual results:** 
![WhatsApp Image 2020-02-26 at 10 54 00](https://user-images.githubusercontent.com/23178404/75333464-76c97e80-5886-11ea-9005-3ddbad841eb0.jpeg)

## Other info
I also tested this on a Samsung J3, and the bug was not apparent. So it maybe Iphone related.

Thanks in advance for any help:)

**Comment by ditman** [comment] 2020-02-28 01:05
Interesting, may be related to this: https://stackoverflow.com/a/56153685

**Comment by ditman** [comment] 2020-02-28 01:11
The culprit seems to be opening links in `target="_blank"` when in `standalone` mode.

> It triggers a new tab and than opens the email application, and when done I return to the blank screen.

I think this is exactly what's happening, but in standalone mode you can't close that extra tab that was opened, @10686142.

**Comment by ditman** [comment] 2020-02-28 01:14
I'm going to label this as a `[good-first-issue]`, here's the code that's opening a new tab:

https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart#L22

In case anybody wants to contribute a fix faster than I can get to this (wink, wink @10686142 :P)

**Comment by jamesblasco** [comment] 2020-02-29 19:51
Hello I would be happy to contribute to this issue

I have been looking on the solutions from stackoverflow. In order to check if it is running on standalone mode on Safari iOS, it should be used [Navigator.standalone](https://developer.mozilla.org/en-US/docs/Web/API/Navigator). I think this not implemented in the [Navigator of dart-html](https://api.dart.dev/stable/2.7.1/dart-html/Navigator-class.html)

Should I submit an issue there first?

**Comment by ditman** [comment] 2020-03-02 19:11
@jamesblasco I don't think you need to modify dart:html here. You can create your own JS Interop facade with package:js that is able to look (just) at `standalone` in the global Navigator object.

This is how I did it for `navigator.connection` without having to change dart:html [here](https://github.com/ditman/plugins/blob/connectivity-web/packages/connectivity/connectivity_web/lib/src/generated/network_information_types.dart). (Your solution may be even simpler!)

**Comment by ditman** [comment] 2020-04-09 18:22
Hey @tugorez, do you want to take a look at this one?

**Comment by ditman** [comment] 2020-04-09 22:30
Note: there has been a feature request of opening urls in web in the same tab (specified from the source), so that'd be a nice addition.

_Making a note here so I don't forget :)_

**Comment by tugorez** [comment] 2020-04-10 17:34
Hey @ditman. Sure thing, let me take a look!

**Comment by ditman** [comment] 2020-04-20 19:09
Hey @10686142, @jamesblasco!

@tugorez has a potential fix for the issue in the [PR above](https://github.com/flutter/plugins/pull/2656). Do you mind giving it a shot? (I'm testing this on my end as well, to have this merged today/tomorrow).

**Comment by ditman** [comment] 2020-04-23 20:53
[url_launcher_web 0.1.1+2](https://pub.dev/packages/url_launcher_web/versions/0.1.1+2#0112) is now in pub, please refresh your dependencies!

**Comment by Faiyyaz** [comment] 2020-04-29 05:07
For me on chrome on macOS it opens in a new tab rather than the same app

**Comment by tugorez** [comment] 2020-04-29 05:35
> For me on chrome on macOS it opens in a new tab rather than the same tab

First of all, thank you so much for taking the time to test it. I thought the bug was only happening on iOS devices therefore I only modified the behavior for those cases. If you can reproduce the bug on your mac I will be happy to extend this fix to cover that case too :)

**Comment by Faiyyaz** [comment] 2020-04-29 09:40
> > For me on chrome on macOS it opens in a new tab rather than the same tab
> 
> First of all, thank you so much for taking the time to test it. I thought the bug was only happening on iOS devices therefore I only modified the behavior for those cases. If you can reproduce the bug on your mac I will be happy to extend this fix to cover that case too :)

Yes i tried but the thing it doesn't open in my web app tab rather it opens a new tab and open the link there

**Comment by ditman** [comment] 2020-04-29 18:02
@Faiyyaz are you opening your app in regular Chrome, or do you have it installed as a PWA?

**Comment by Faiyyaz** [comment] 2020-04-30 11:48
regular chrome from android studio

**Comment by ditman** [comment] 2020-04-30 18:28
Let's take another look!

**Comment by ditman** [comment] 2020-05-01 18:11
So it seems that regardless of the PWA status of the App, in iOS (at least), it needs to pass `_top` as the target for "share" URLs (like `mailto:`). If so, I think we can remove the `standalone` check, and rewrite the logic that determines what the "target" for the `window.open` is, so you don't need custom JS interop code.

**Comment by tugorez** [comment] 2020-05-07 06:19
Ok so I prepared a quick POC assuming we should open `mailto` urls with `_top` as target only on iOS devices. Am I right? 

I currently don't have any apple mobile device so I will ask for your to help to test this.

**Comment by tugorez** [comment] 2020-05-11 05:53
@ditman @10686142 @Faiyyaz can you take a look to the PR and help me to test it?

**Comment by Faiyyaz** [comment] 2020-05-11 13:15
Sorry for the late reply, I will test it by tomorrow and post the status

**Comment by 10686142** [comment] 2020-05-11 14:19
I am looking into it, but I can't seem to get your fix of url_launcher_web into my project, what am I doing wrong here:
````
  url_launcher_web:
    git:
      url: git://github.com/tugorez/plugins/tree/fix/51461/packages/url_launcher/url_launcher_web.git
````
And I tried:
````
  url_launcher_web:
    git:
      url: git://github.com/tugorez/plugins/packages/url_launcher/url_launcher_web.git
      ref: fix/51461
````

**Comment by tugorez** [comment] 2020-05-11 15:46
> Also which PR to test?

No problem @Faiyyaz :) This one please https://github.com/flutter/plugins/pull/2740


> I am looking into it, but I can't seem to get your fix of url_launcher_web into my project, what am I doing wrong here:

I think you need to do something like this:
```yaml
dependencies:
  url_launcher_web:
    git:
      url: git://github.com/tugorez/plugins.git
      ref: fix/51461
      path: packages/url_launcher/url_launcher_web
```

Also please be aware that if in your project you have  `url_launcher` as dependency adding `url_launcher_web` to the same project won't overwrite `url_launcher` dependencies.

**Comment by Faiyyaz** [comment] 2020-05-12 03:05
Unable to build the app getting this error

Attaching my pubspec file screenshot too

<img width="1440" alt="Screenshot 2020-05-12 at 8 34 23 AM" src="https://user-images.githubusercontent.com/18116236/81633904-66f41c00-942b-11ea-9d76-e1d520eb9506.png">

<img width="1440" alt="Screenshot 2020-05-12 at 8 34 58 AM" src="https://user-images.githubusercontent.com/18116236/81633960-825f2700-942b-11ea-82c9-954e9b6826bd.png">

**Comment by 10686142** [comment] 2020-05-12 10:35
Alright I just tested it out and saw that a few things didn't work which is maybe due to the fact that I wasn't 100% clear in the explanation from my side. This implementation with explanation, is how it works for me on iOS:

### Browser

#### Regular url
This will work with the regular implementation, so no _top needed since opening this url a new tab is probably what a user wants compared to loading a new url in the same window and therefore also exiting the App.

#### Share url
Here I implemented the following function:
````
function openUrlPwa(url) {
  var win = window.open(url, '_top');
  win.focus();
}
````
Because you the ".focus()" method makes sure you don't leave the current screen, because by default safari implementation for "_top" (in standalone) opens another tab from which it opens your email app. 

_Note: This also works without the ".focus()", but the Standalone method for the same functionality does require ".focus()" to be called. So I think it's maybe easier to just call this when an email url is being opened and also because you could then skip the whole standalone check._


### Standalone

#### Regular url
This will work with the regular implementation, so you don't want to use "_top", because you don't want to open the link in the same Standalone tab window. You want it to open in in a pop-up (which is a new tab for iOS standalone) for which you can click "Done" when you're actually done with that, compared to clicking "Done" if it's loaded in the same tab, which will try to close the actual PWA and then reload the whole App. I added screen recordings to show the differences:
- The one on the left is the one with the "_top" implementation, where you can see that the whole apps restarts because it's loaded in the same window. 
- The one the right is where it just opens another tab by "popping" it on top of the App's tab, and therefore on return would not yield any change since it was a new window that has been closed.
![](https://media.giphy.com/media/WopUcQldUEsJ5qtJ31/giphy.gif) | ![](https://media.giphy.com/media/S664qNlVisBnvI49Zh/giphy.gif)

#### Share url
I am using the exact same function as for sharing when in the browser, because you never want the Web App to open another empty tab which it uses to open the actual sharing App (email), because this will result in that empty tab when you're returning to the App from your sharing App (email). 
_You can also check out the screen recordings from my initial issue to see this in action._


## Bottomline:
1) Regular urls need no changing.
2) For share urls like "mailto" you want to use the "window.open(url, '_top')" function in combination with ".focus()" method to make sure everything is loaded from the same window.


## Caveat

### iOS Browser
I noticed that when the user doesn't have the App installed for which you want to use a share url (e.g. "twitter://post"), and you don't have the that App installed (e.g. Twitter), the opening of the url by using "window.open(url, '_top')" would not work and it would not yield any error message. 

However, I do think it's fair to assume that people have a Mail App installed on their phone, so therefore the implementation for "mailto" is valid (correct me if I am wrong though).

If someday Flutter is looking to support other sharing schemes for platforms like Twitter, LinkedIn, Facebook etc, than something like the answer given below is the only way to validate if a url can actually be opened in iOS Safari:
https://stackoverflow.com/a/14706422/8970591

**Comment by ditman** [comment] 2020-05-12 18:06
We did a quick fix with an app that does (I think) what everybody expects (open mailto links without a new tab):

https://dit-url-launcher-debug.web.app

The above is currently in PR.

_Note that the different behavior seems to be on Safari; MacOS X also exhibited the same behavior of opening a blank page, and then triggering the mailto link, so it also needs to open mailto links in `_top`._

**Comment by ditman** [comment] 2020-05-12 18:11
There's also a proposal on letting people pass whatever `target` they want to the url_launcher, [here](https://github.com/flutter/flutter/issues/56867). (And a proper `Link` widget within the framework)

**Comment by ditman** [comment] 2020-05-19 19:32
@10686142, @Faiyyaz we've just published the `0.1.1+6` version of `url_launcher_web` to pub.dev, which should fix this issue.

https://pub.dev/packages/url_launcher_web#0116

Please let us know if it doesn't!

**Closed by ditman** 2020-05-19 19:32 UTC
Labels: good first contribution, p: url_launcher, platform-web, plugin

**Comment by liubrandon** [comment] 2020-12-24 20:45
I also struggled with this same issue returning to a blank page with the "done" button while using the latest url_launcher and url_launcher_web. It was happening in both my PWA and from the in-app browser in iOS Telegram. My URLs are Instagram links that automatically opens in the Instagram app (at least in iOS).

Thankfully it's solved switching to a Link widget with target: LinkTarget.blank. Thanks so much! Currently there's no example on the pub.dev page for url_launcher for using the Link class, so it would be helpful to add it there too @ditman @tugorez.

```
Link(
  uri: Uri.parse(urlString),
  target: LinkTarget.blank,
  builder: (BuildContext context, FollowLink followLink) => ListTile(
    ...
    onTap: () => followLink(),
  )),
```

**Comment by ditman** [comment] 2021-01-05 22:02
@liubrandon this is great, I'm sure @mdebbar will be happy to see that you found his widget! The Link widget is rather new, so examples/docs might not be fully in place. There's this: https://pub.dev/documentation/url_launcher/latest/link/Link-class.html but I agree it's not the most findable resource.

**Comment by ditman** [comment] 2021-01-05 22:05
Note that [recent versions](https://github.com/flutter/flutter/issues/56867#issuecomment-683160219) of the url_launcher plugin have the parameter: `webOnlyWindowName` that can be set to `"_blank"` so it does the same as the LinkTarget.blank.

> `webOnlyWindowName` is an Web only setting . `_blank` opens the new url in new tab , `_self` opens the new url in current tab. Default behaviour is to open the url in new tab.

**Comment by liubrandon** [comment] 2021-01-05 22:10
Thanks for the follow up! Just FYI I removed the Link widget a few days ago because strangely it increased scrolling performance in my ListView a lot when I removed the Link wrapper and just used launch(). I'm not sure why, but I had downgraded to Flutter 1.23.x to fix another issue (https://github.com/flutter/flutter/issues/72171) which could be related. Haven't had time to isolate these bugs as everything seems to just work now using launch again in my web app

**Comment by ditman** [comment] 2021-01-05 23:11
> I removed the Link widget a few days ago because strangely it increased scrolling performance in my ListView a lot

@liubrandon was this on web, or other platforms? Can you file [a new issue](https://github.com/flutter/flutter/issues/new/choose) with some more details? We're hunting those performance issues!

(There's a **"My app is slow or missing frames."** category for performance issues; it'll ask you some details about your app and its code!).
