### ISSUE TITLE
Skipped 53 frames! The application may be doing too much work on its main thread while using charts.

### ISSUE THREAD

**Issue by rohitbakoliya** [flutter/flutter#57144] opened 2020-05-13 18:19 UTC
## Details

1.  I'm using charts_flutter: ^0.9.0 for implementing 3 dynamic bar and 3 dynamic line charts after some API calls.

## Logs

```

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
I/OpenGLRenderer(32062): Initialized EGL, version 1.4
D/OpenGLRenderer(32062): Swap behavior 1
D/HostConnection(32062): HostConnection::get() New Host Connection established 0xe33a1820, tid 32115
D/HostConnection(32062): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
W/OpenGLRenderer(32062): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer(32062): Swap behavior 0
D/eglCodecCommon(32062): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(32062): eglCreateContext: 0xe3384900: maj 2 min 0 rcv 2
D/EGL_emulation(32062): eglMakeCurrent: 0xe3384900: ver 2 0 (tinfo 0xcb5fae70)
D/HostConnection(32062): HostConnection::get() New Host Connection established 0xce8da370, tid 32096
D/HostConnection(32062): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
D/HostConnection(32062): createUnique: call
D/HostConnection(32062): HostConnection::get() New Host Connection established 0xe33a1b90, tid 32115
D/HostConnection(32062): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
E/eglCodecCommon(32062): GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
D/eglCodecCommon(32062): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(32062): eglCreateContext: 0xe34518e0: maj 2 min 0 rcv 2
D/EGL_emulation(32062): eglMakeCurrent: 0xe34518e0: ver 2 0 (tinfo 0xe1aa1b00)
I/Choreographer(32062): Skipped 47 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(32062): eglMakeCurrent: 0xe3384900: ver 2 0 (tinfo 0xcb5fae70)
I/OpenGLRenderer(32062): Davey! duration=1037ms; Flags=1, IntendedVsync=100899408191318, Vsync=100900191524620, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=100900195777600, AnimationStart=100900195913200, PerformTraversalsStart=100900195977100, DrawStart=100900212844600, SyncQueued=100900218925800, SyncStart=100900226126800, IssueDrawCommandsStart=100900226399300, SwapBuffers=100900280615000, FrameCompleted=100900453276400, DequeueBufferDuration=39373000, QueueBufferDuration=2616000,
D/EGL_emulation(32062): eglMakeCurrent: 0xe34518e0: ver 2 0 (tinfo 0xe1aa1b00)
D/eglCodecCommon(32062): setVertexArrayObject: set vao to 0 (0) 1 0

```

`flutter doctor -v` 

```
√] Flutter (Channel master, v1.15.4-pre.134, on Microsoft Windows [Version 10.0.18362.778], locale en-IN)
    • Flutter version 1.15.4-pre.134 at C:\src\flutter
    • Framework revision bf8e2c1449 (3 months ago), 2020-02-21 14:21:25 -0800
    • Engine revision f2f8c342be
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 0f141be8bd)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Rohit Bakoliya\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\Rohit Bakoliya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)
```

### My Code

```dart
import 'dart:math';

import 'package:covid_19/widgets/app_drawer.dart';
import 'package:covid_19/widgets/dots.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:charts_flutter/flutter.dart' as charts;
import 'package:http/http.dart';
import 'dart:convert';
import 'package:covid_19/widgets/counter.dart';
import 'package:covid_19/widgets/myheader.dart';
import 'package:covid_19/constant.dart';
import 'package:covid_19/screens/detailed_table.dart';
import 'package:covid_19/utils/utils.dart';

class Home extends StatefulWidget {
  
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final controller = ScrollController();
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();

  Map<String,double> states={};
  bool loading = true;
  double offset = 0;
  String selected="India";
  int infected = -1;
  int deaths = -1;
  double constant = 300;
  List<dynamic> list = [];
  int recovered = -1;
  Map data = {};
  String lastUpdated="";
  bool infectedSwitchControl = false;
  bool recoveredSwitchControl = false;
  bool deathsSwitchControl = false;
  @override
  void initState() {
    super.initState();
    getData();
    controller.addListener(onScroll);
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  void onScroll() {
    setState(() {
      offset = (controller.hasClients) ? controller.offset : 0;
    });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      endDrawer: AppDrawer(),
      body: Builder(
            builder: (context)=>SingleChildScrollView(
            controller: controller,
            child: Column(
            children: <Widget>[
              Padding(
                padding: EdgeInsets.symmetric(horizontal: 20),
                child: Column(
                  children: <Widget>[
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: <Widget>[
                        Text(
                          "Spread Trends",
                          style: kTitleTextstyle,
                        ),
                      ],
                    ),
                    SizedBox(height: 10),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: <Widget>[
                          Text(
                          'Infected',
                            style: TextStyle(
                              color : Colors.deepOrange,
                              fontSize: 16
                            ),
                          ), 
                          Row(
                            children: <Widget>[
                              Text(
                                'Daily',
                                style: TextStyle(
                                  color: infectedSwitchControl==true?kInfectedColor:kTextLightColor
                                ),
                              ),
                              Switch(
                                onChanged: (bool value){
                                  setState(() {
                                    infectedSwitchControl = !infectedSwitchControl;
                                  });
                                },
                                value: infectedSwitchControl,
                                activeColor: kInfectedColor,
                                activeTrackColor: Colors.orange[100],
                                inactiveThumbColor: Colors.white,
                                inactiveTrackColor: Colors.grey,
                              ),
                            ],
                          )
                      ],
                    ),
                    Container(
                      margin: EdgeInsets.only(top : 20),
                      padding: EdgeInsets.only(top: 10 , bottom:  20, left: 10),
                      height: 300,
                      width: double.infinity,
                      child: infectedSwitchControl? createBarChart('dailyconfirmed') : createChart('totalconfirmed'),
                    ),
                    SizedBox(height: 10),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: <Widget>[
                          Text(
                          'Recovered',
                            style: TextStyle(
                              color : kRecovercolor,
                              fontSize: 16
                            ),
                          ), 
                          Row(
                            children: <Widget>[
                              Text(
                                'Daily',
                                style: TextStyle(
                                  color: recoveredSwitchControl ==true?kRecovercolor:kTextLightColor
                                ),
                              ),
                              Switch(
                                onChanged: (bool value){
                                  setState(() {
                                    recoveredSwitchControl = !recoveredSwitchControl;
                                  });
                                },
                                value: recoveredSwitchControl,
                                activeColor: kRecovercolor,
                                activeTrackColor: Colors.green[100],
                                inactiveThumbColor: Colors.white,
                                inactiveTrackColor: Colors.grey,
                              ),
                            ],
                          )
                      ],
                    ),
                    Container(
                      margin: EdgeInsets.only(top : 20),
                      padding: EdgeInsets.only(top: 10 , bottom:  20, left: 10),
                      height: 300,
                      width: double.infinity,
                      child: recoveredSwitchControl==true? createBarChart('dailyrecovered') : createChart('totalrecovered'),
                    ),
                    SizedBox(height: 10),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: <Widget>[
                          Text(
                          'Deaths',
                            style: TextStyle(
                              color : kDeathColor,
                              fontSize: 16
                            ),
                          ), 
                          Row(
                            children: <Widget>[
                              Text(
                                'Daily',
                                style: TextStyle(
                                  color: deathsSwitchControl==true ? kDeathColor:kTextLightColor
                                ),
                              ),
                              Switch(
                                onChanged: (bool value){
                                  setState(() {
                                    deathsSwitchControl = !deathsSwitchControl;
                                  });
                                },
                                value: deathsSwitchControl,
                                activeColor: kDeathColor,
                                activeTrackColor: Colors.red[100],
                                inactiveThumbColor: Colors.white,
                                inactiveTrackColor: Colors.grey,
                              ),
                            ],
                          )
                      ],
                    ),
                    Container(
                      height: 300,
                      width: double.infinity,
                      child: deathsSwitchControl==true ? createBarChart('dailydeceased') : createChart('totaldeceased'),
                    ),
                    SizedBox(height: 30)
                  ],
                ),
              )
            ],
          ),
        ),
      ),
    );
  }

  //Spread trends
  charts.Series<TimeSeriesNums, DateTime> createSeries(String id, int i, String type){
    return charts.Series<TimeSeriesNums, DateTime>(
      id : id,
      colorFn: (_, index) => type=="totalconfirmed" || type =="dailyconfirmed" ? charts.MaterialPalette.deepOrange.shadeDefault 
      : type=="totalrecovered" || type == "dailyrecovered"? 
      charts.MaterialPalette.green.shadeDefault : charts.MaterialPalette.red.shadeDefault,
      domainFn: (TimeSeriesNums sales, _) => sales.time,
      measureFn: (TimeSeriesNums sales, _) => sales.nums,
      data: [
        TimeSeriesNums(Utils().reformatDate(list[i]['date']), int.parse(list[i][type]))
      ]
    );
  }
  Widget createChart(String type){
    List<charts.Series<TimeSeriesNums , DateTime >> seriesList = [];
    for(int i=0; i< min(list.length, 60); i++){
      String id = 'XYZ${i+1}';
      seriesList.add(createSeries(id, i, type));
    }
    return charts.TimeSeriesChart(
      seriesList,
      animate: true,
      primaryMeasureAxis: new charts.NumericAxisSpec(
        tickProviderSpec: new charts.BasicNumericTickProviderSpec(desiredTickCount: 10)
      ),
      defaultRenderer: new charts.LineRendererConfig(),
    );
  }
  Widget createBarChart(String type){
    List<charts.Series<TimeSeriesNums , DateTime >> seriesList = [];
    for(int i=0; i< min(list.length, 60); i++){
      String id = 'XYZ${i+1}';
      seriesList.add(createSeries(id, i, type));
    }
    return new charts.TimeSeriesChart(
      seriesList,
      animate: true,
      primaryMeasureAxis: new charts.NumericAxisSpec(
        tickProviderSpec: new charts.BasicNumericTickProviderSpec(desiredTickCount: 10)
      ),
      defaultRenderer: new charts.BarRendererConfig<DateTime>(),
      dateTimeFactory: const charts.LocalDateTimeFactory(),
    );
  }
  

}
class TimeSeriesNums {
  final DateTime time;
  final int nums;
  TimeSeriesNums(this.time, this.nums);
}


```

So how can I fix this issue without removing these charts?
see  [github](https://github.com/rohitbakoliya/covid-19INDIAl)

**Comment by iapicca** [comment] 2020-05-15 11:17
Hi @rohitbakoliya 
the issue seems to be related with [charts_flutter](https://pub.dev/packages/charts_flutter);
since it is a 3rd party plugin you may want to open an issue in the dedicated [github](https://github.com/google/charts/issues)
if this isn't the case 
please run `flutter upgrade --force`
and provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample
(that doesn't use 3rd party plugins)
Thank you

**Comment by rohitbakoliya** [comment] 2020-05-16 18:23
I think it is a performance issue with flutter not for charts so I shouldn't open an issue at [charts](https://github.com/google/charts/issues). moreover, I already tried google charts on web also. It never creates any performance issues or any lags.
So I upgraded the flutter version as you said.

`$flutter doctor -v`

```
[√] Flutter (Channel master, 1.19.0-2.0.pre.73, on Microsoft Windows [Version 10.0.18362.836], locale en-IN)
    • Flutter version 1.19.0-2.0.pre.73 at C:\src\flutter
    • Framework revision 32547dcc7e (24 hours ago), 2020-05-15 10:42:37 -0700
    • Engine revision 50e55cf69e
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Rohit Bakoliya\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\Rohit Bakoliya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

### Logs

`flutter run --verbose`

```


[ +468 ms] Syncing files to device AOSP on IA Emulator...
[   +4 ms] Scanning asset files
[  +31 ms] <- reset
[   +9 ms] Compiling dart to kernel with 0 updated files
[   +5 ms] <- recompile package:covid_19/main.dart b01a3dd9-d8bd-4c4e-9852-161c3e23626e
[   +1 ms] <- b01a3dd9-d8bd-4c4e-9852-161c3e23626e
[   +3 ms] I/OpenGLRenderer(32536): Initialized EGL, version 1.4
[   +1 ms] D/OpenGLRenderer(32536): Swap behavior 1
[   +1 ms] D/HostConnection(32536): HostConnection::get() New Host Connection established 0xe33a1370, tid 32614
[  +24 ms] D/HostConnection(32536): HostConnection::get() New Host Connection established 0xe33a13c0, tid 32603
[   +2 ms] D/HostConnection(32536): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache        
GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
[   +2 ms] W/OpenGLRenderer(32536): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[   +1 ms] D/OpenGLRenderer(32536): Swap behavior 0
[   +3 ms] D/eglCodecCommon(32536): setVertexArrayObject: set vao to 0 (0) 0 0
[  +22 ms] D/EGL_emulation(32536): eglCreateContext: 0xe33845a0: maj 2 min 0 rcv 2
[   +3 ms] D/HostConnection(32536): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache        
GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
[   +3 ms] D/eglCodecCommon(32536): setVertexArrayObject: set vao to 0 (0) 0 0
[   +2 ms] D/EGL_emulation(32536): eglCreateContext: 0xe33846c0: maj 2 min 0 rcv 2
[  +25 ms] D/EGL_emulation(32536): eglMakeCurrent: 0xe33845a0: ver 2 0 (tinfo 0xe33837f0)
[  +33 ms] D/HostConnection(32536): createUnique: call
[   +2 ms] D/HostConnection(32536): createUnique: call
[   +3 ms] D/HostConnection(32536): HostConnection::get() New Host Connection established 0xe33a1410, tid 32603
[  +26 ms] D/HostConnection(32536): HostConnection::get() New Host Connection established 0xce8e69d0, tid 32614
[   +3 ms] D/HostConnection(32536): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache        
GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
[   +3 ms] E/eglCodecCommon(32536): GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
[  +27 ms] D/HostConnection(32536): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache
GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
[   +5 ms] D/EGL_emulation(32536): eglMakeCurrent: 0xe33846c0: ver 2 0 (tinfo 0xe3383700)
[ +282 ms] Updating files
**[  +55 ms] I/Choreographer(32536): Skipped 56 frames!  The application may be doing too much work on its main thread.**
[  +55 ms] D/EGL_emulation(32536): eglMakeCurrent: 0xe33845a0: ver 2 0 (tinfo 0xe33837f0)
[ +217 ms] I/OpenGLRenderer(32536): Davey! duration=1226ms; Flags=1, IntendedVsync=102804247651211, Vsync=102805180984507, OldestInputEvent=9223372036854775807,
NewestInputEvent=0, HandleInputStart=102805183843000, AnimationStart=102805184013000, PerformTraversalsStart=102805184073200, DrawStart=102805217613000,
SyncQueued=102805240955300, SyncStart=102805249924700, IssueDrawCommandsStart=102805259358000, SwapBuffers=102805339243700, FrameCompleted=102805482744400,
DequeueBufferDuration=37889000, QueueBufferDuration=902000,
[+1912 ms] DevFS: Sync finished
``` 

### See this is reproducible minimal code sample with explanation

```Dart
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:charts_flutter/flutter.dart' as charts;

class Home extends StatefulWidget {  
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {

  Map<String,double> states={};
  List<dynamic> list = [];
  bool switchControl = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
            child: Column(
            children: <Widget>[
            //similarly i'm making another 2 charts.
              Row(
                children: <Widget>[
                    Text('Infected'), 
                    Row(
                      children: <Widget>[
                        Text(
                          'Daily',
                          style: TextStyle(
                            color: switchControl==true?Colors.deepOrange:Colors.black87
                          ),
                        ),
                        //depanding upon switchControl value i'm ploting bar-chart or line-chart
                        Switch(
                          onChanged: (bool value){
                            setState(() {
                              switchControl = !switchControl;
                            });
                          },
                          value: switchControl,
                        ),
                      ],
                    )
                ],
              ),
              Container(
                height: 300,
                width: double.infinity,
                child: switchControl? createBarChart() : createLineChart(),
              )
            ],
          ),
        ),
    );
  }

  // here list<dynamic> is filled after some api calls 
  //after api calls list look like this
  /*
    list = [
      {
        'date' : '28/02/2000,
        'some-type' : '3000445'
        'another-type' : '2323232'
      },
      {
        'date' : '22/08/2019,
        'some-type' : '3000445'
        'another-type' : '2323232'
      },
      {
        'date' : '02/12/2010,
        'some-type' : '3000445'
        'another-type' : '2323232'
      }
    ]
  */ 

  //Spread trends
  charts.Series<TimeSeriesNums, DateTime> createSeries(String id, int i){
    return charts.Series<TimeSeriesNums, DateTime>(
      id : id,
      domainFn: (TimeSeriesNums sales, _) => sales.time,
      measureFn: (TimeSeriesNums sales, _) => sales.nums,
      data: [
        TimeSeriesNums(DateTime(list[i]['date']), int.parse(list[i]['some-type']))
      ]
    );
  }

  //for ploting line-chart 
  Widget createLineChart(){
    List<charts.Series<TimeSeriesNums , DateTime >> seriesList = [];
    for(int i=0; i< min(list.length, 60); i++){
      String id = 'XYZ${i+1}';
      seriesList.add(createSeries(id, i));
    }
    return charts.TimeSeriesChart(
      seriesList,
      animate: false,
      primaryMeasureAxis: new charts.NumericAxisSpec(
        tickProviderSpec: new charts.BasicNumericTickProviderSpec(desiredTickCount: 10)
      ),
      defaultRenderer: new charts.LineRendererConfig(),
    );
  }
  //for ploting bar-chart 
  Widget createBarChart(){
    List<charts.Series<TimeSeriesNums , DateTime >> seriesList = [];
    for(int i=0; i< min(list.length, 60); i++){
      String id = 'XYZ${i+1}';
      seriesList.add(createSeries(id, i));
    }
    return new charts.TimeSeriesChart(
      seriesList,
      animate: false,
      primaryMeasureAxis: new charts.NumericAxisSpec(
        tickProviderSpec: new charts.BasicNumericTickProviderSpec(desiredTickCount: 10)
      ),
      defaultRenderer: new charts.BarRendererConfig<DateTime>(),
      dateTimeFactory: const charts.LocalDateTimeFactory(),
    );
  }
  

}
class TimeSeriesNums {
  final DateTime time;
  final int nums;
  TimeSeriesNums(this.time, this.nums);
}

```

As we can see from logs charts were prepared only by main thread so can we use multi-threading to reduce load over the main thread?

**Comment by iapicca** [comment] 2020-05-18 06:52
Hi @rohitbakoliya 
could you please provide a reproducible minimal code sample
that does not rely on 3rd party plugins
Thank you

**Comment by rohitbakoliya** [comment] 2020-05-18 07:47
Hello @iapicca 
I already provided you reproducible minimal code check this [comment](https://github.com/flutter/flutter/issues/57144#issuecomment-629687473). It must rely on flutter_charts without it never creates such a performance issue.
Thanks!

**Comment by TahaTesser** [comment] 2020-05-19 09:14
Hi @rohitbakoliya 
That code sample you provided is using a third package which producing this message

For issue related to the 3rd party plugin [charts_flutter](https://pub.dev/packages/charts_flutter) you may want to open an issue in the dedicated [GitHub](https://github.com/google/charts/issues.)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it /
Thank you

**Closed by TahaTesser** 2020-05-19 09:14 UTC
Labels: in triage
