### ISSUE TITLE
Gesture didn't work while widget is bigger than screen!!

### ISSUE THREAD

**Issue by LynGao** [flutter/flutter#25702] opened 2018-12-23 03:05 UTC
As title say, a widget with a tapGesture。While a widget's frame is bigger than screen，out of part of screen，the gesture did not work anyway。how can i fix that problem！
![11111](https://user-images.githubusercontent.com/6290757/50380453-b99c2f00-06a2-11e9-969e-f199fddccc7e.png)

**Comment by zoechi** [comment] 2018-12-23 11:42
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment] 2018-12-23 11:43
Probably similar to 

- https://stackoverflow.com/questions/51188344/gesture-response-outside-of-stack-boundary-not-recieved
- https://stackoverflow.com/questions/51366761/in-flutter-how-can-a-positioned-widget-feel-taps-outside-of-its-parent-stack-ar

**Comment by LynGao** [comment] 2018-12-24 08:53
> Probably similar to
> 
> * https://stackoverflow.com/questions/51188344/gesture-response-outside-of-stack-boundary-not-recieved
> * https://stackoverflow.com/questions/51366761/in-flutter-how-can-a-positioned-widget-feel-taps-outside-of-its-parent-stack-ar

Thanks zoechi.
But my question are not the same as these question. 
In my application, while the application init, i build a widget which  some area is out of screen, just liek the upper picture u see.

Here the code like this:

return new Center(
        child:
        new Transform.scale(
          scale: frameScale,
          child:
          new Transform.translate(
              offset: frameOffset,
              child:
              new Transform(
                  alignment: dir,
                  transform: matrix4,
                  child: RepaintBoundary(
                      key: frameGlobalKey,
                      child:
                      new Stack(
                          children: getViews()
                      )))),
        ));

So, i can change the 'scale', let the widget can fit with screen. (make widget is smaller than screen size)
At this time, i found that some area can't no response to the gesture handler.
I guess these area is out of screen's  area  before change the 'scale'.

So, how can i solve that problem?

**Comment by kf6gpe** [comment] 2020-01-07 21:11
Closing due to lack of reproducible case. If there's one posted to this bug, feel free to reopen. Thanks!

**Closed by kf6gpe** 2020-01-07 21:11 UTC
Labels: f: gestures, framework
