### ISSUE TITLE
Flutter shouldn't grow image cache arbitrarily

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#48576] opened 2020-01-10 16:33 UTC
https://b.corp.google.com/issues/147479267.

cc @cbracken , @mehmetf  (to whom the internal bug was originally assigned).

**Comment by jamesderlin** [comment] 2020-01-10 23:25
I think that this is a duplicate of https://github.com/flutter/flutter/issues/45643.

**Closed by jamesderlin** 2020-01-10 23:25 UTC
Labels: customer: dream (g3), perf: memory
