### ISSUE TITLE
Flutter-web hot restart leaves web-sockets open

### ISSUE THREAD

**Issue by ravenblackx** [flutter/flutter#84500] opened 2021-06-12 22:03 UTC
## Steps to Reproduce

1. Make an app that uses `WebSocketChannel.connect` to a server that supports a connection.
2. Have the server log connections and disconnections.
3. Run the app in web mode, on Chrome-linux, from Android Studio; observe the connection status.
4. Hot restart, do whatever is required to connect again, observe in the server log that another connection is made, but no disconnection.
5. Hit F5 to refresh in the chrome test window, observe that this closes both the connections.

I would expect the connection to persist for hot reload (if that worked at all), but it should be cleared for hot restart. Suggestion, hot restart should, after updating the files, force a browser page refresh to clear out all residual javascript state (I'm assuming it's leaking any kinds of listeners that are registered with the document).

## flutter doctor -v

```
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.1 at /home/ravenblack/snap/flutter/common/flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ravenblack/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/103/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/103/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-06-14 11:15
Hi @ravenblackx 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/web_socket_channel/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-14 11:15 UTC
Labels: in triage

**Comment by ravenblackx** [comment] 2021-06-14 11:50
Ah, fair enough, though it wouldn't help to file a bug against the third party plugin, because a third party plugin can't do anything about it, because of #10437

**Comment by TahaTesser** [comment] 2021-07-01 09:57
@ravenblackx 
Thanks, in that case, it's Flutter limitation, not a bug

**Comment by ravenblackx** [comment] 2021-07-01 11:46
Digging a little bit deeper, it looks like the websockets library is not even a plugin, just a dart abstraction around dart:io or dart:html. So if anything it appears it's dart:html's implementation of WebSocket that needs the cleanup (not sure yet whether dart:html's implementation involves a plugin.)

After following links from #10437 to #7160 it appears that if there *is* a plugin involved then it can potentially fix this issue by treating an "initialize" call as also a "clean up after existing instance" call.
