### ISSUE TITLE
[video_player] - 0.10.8+1, freezes the application with the latest dev channel

### ISSUE THREAD

**Issue by janosdupai** [flutter/flutter#53097] opened 2020-03-23 15:21 UTC
I use the video_player pub, and everything worked fine, but since the latest flutter upgrade, sometimes the video does not start, or stops during playback.

Sometimes it starts, but when  I push the app in background, and open again, it is also freezing.

Another weird thing: if the app freezes, and I push the app to background and reactivate, it will work again smoothly...

When I changed back the channel to "beta", everything works fine. But at 'master', 'stable', 'dev' channels causes this weird error.

```bash
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.3 19D76, locale hu-HU)
    • Flutter version 1.15.17 at /Users/janosdupai/Developer/flutter
    • Framework revision 2294d75bfa (2 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/janosdupai/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/janosdupai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (4 available)
    • MATCHmeeting      • 00008020-0002242E1A29002E            • ios            • iOS 13.1.2
    • iPhone 11 Pro Max • D441D7C8-ACB0-47BC-8CF6-A4A245BF352A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.149
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

**Comment by lenli** [comment] 2020-03-26 06:52
I just started picking up Flutter last week and was trying to implement `video_player`  and also found many issues resuming a backgrounded video.

Coming from a native iOS background and digging into `FLTVideoPlayer`, I suspect that some of these issues might be related to not using an `AVPlayerLayer` in the implementation.

Note:  Though I don't know the root reason, I have also found that resetting the `AVPlayer` in the `AVPlayerLayer` fixes a lot of issues when resuming playback from background.

**Comment by priezz** [comment] 2020-03-26 23:52
I have exactly the same behaviour in iOS. I have noticed, that it is enough to load the video w/o showing it to get the app freeze. Is there any fix or a workaround for this issue?

**Comment by priezz** [comment] 2020-03-27 20:35
For me the only solution was to switch to another package, which does not rely on AVPlayer.

**Comment by kf6gpe** [comment] 2020-03-30 21:41
cc @amirh for plugin triage visibility.

**Comment by leszekkrol** [comment] 2020-07-23 13:22
Anu update in that case?

**Comment by leszekkrol** [comment] 2020-07-23 13:32
2020-07-23 15:31:45.159345+0200 Runner[28300:413281] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <FLTVideoPlayer 0x600003d56800> for the key path "status" from <AVPlayerItem 0x60000114cfd0> because it is not registered as an observer.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   Foundation                          0x00007fff259114ff -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 601
	3   Foundation                          0x00007fff2591190d -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 74
	4   Foundation                          0x00007fff2591183a -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:context:] + 177
	5   better_player                       0x0000000105864cd2 -[FLTVideoPlayer disposeSansEventChannel] + 130
	6   better_player                       0x0000000105864ec4 -[FLTVideoPlayer dispose] + 36
	7   better_player                       0x0000000105866efb __48-[FLTVideoPlayerPlugin handleMethodCall:result:]_block_invoke + 75
	8   libdispatch.dylib                   0x00000001068bee8e _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00000001068c17a3 _dispatch_continuation_pop + 552
	10  libdispatch.dylib                   0x00000001068d4b2c _dispatch_source_invoke + 2205
	11  libdispatch.dylib                   0x00000001068ccbce _dispatch_main_queue_callback_4CF + 692
	12  CoreFoundation                      0x00007fff23da1869 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x00007fff23d9c3b9 __CFRunLoopRun + 2041
	14  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	15  GraphicsServices                    0x00007fff38c39bbe GSEventRunModal + 139
	16  UIKitCore                           0x00007fff49325968 UIApplicationMain + 1605
	17  Runner                              0x0000000102d9fe3b main + 75
	18  libdyld.dylib                       0x00007fff520ce1fd start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by kf6gpe** [comment] 2020-11-09 22:32
@TahaTesser Do you folks have a repro case for this coded up? If you do, would you mind retesting? If not, I wouldn't take the time to retest. I'm just wondering if we've fixed it along the way without knowing it, or if it's still an issue. Thanks!

**Comment by TahaTesser** [comment] 2020-11-10 08:26
Hi  @janosdupai
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

@kf6gpe 
I don't believe we have rerpo case, thanks for bringing attention to this

**Comment by pedromassangocode** [comment] 2020-12-02 08:49
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-02 08:49 UTC
Labels: P4, p: first party, p: video_player, platform-ios, plugin, severe: performance, severe: regression, waiting for customer response
