### ISSUE TITLE
Error: HandshakeException: Connection terminated during handshake

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#133704] opened 2023-08-30 22:19 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Try to run an http package request to any valid url

### Expected results

That the response will be returned

### Actual results

I am receiving the below error on Android
```Error: HandshakeException: Connection terminated during handshake```
This started after updating to Flutter 3.13.1. It will not let me sign into my app. It also will not let someone that is signed in authenticate with the saved credentials.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```

```
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.1 22G90 darwin-arm64, locale en-US)
    • Flutter version 3.13.1 on channel stable at /Users/rickeylee/Desktop/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (8 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/rickeylee/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/rickeylee/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • SM F926U (mobile)            • RFCR802EMHY                              • android-arm64  • Android 13 (API 33)
    • rickey lee’s iPhone (mobile) • d0545eb2ff26e1c087d1b29c26f8e15da19284bb • ios            • iOS 16.6 20G75
    • macOS (desktop)              • macos                                    • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)                 • chrome                                   • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```

</details>

**Comment by rlee1990** [comment] 2023-08-31 02:17
I can confirm downgrading back to 3.10 works.

**Comment by darshankawar** [comment] 2023-08-31 08:27
@rlee1990 
Can you check [this](https://github.com/flutter/flutter/issues/132912) and see if you are case resembles it or not ? 
If yes, you'll need to follow-up in the linked dart-lang issue.

**Comment by rlee1990** [comment] 2023-08-31 13:09
@darshankawar I looked at this and do not believe this is the same. I do not receive any error towards any package I just receive an error for any connection attempt since upgrading the Flutter SDK.

**Comment by darshankawar** [comment] 2023-09-01 05:37
@rlee1990 Thanks for the update. Does the error occur only using VSCode in debug mode ?

**Comment by rlee1990** [comment] 2023-09-01 12:36
@darshankawar no I got it also in android studio in debug mode

**Comment by darshankawar** [comment] 2023-09-04 05:50
Using the [example](https://docs.flutter.dev/cookbook/networking/fetch-data) here and running with latest master version in Pixel 6 emulator doesn't give me the reported error.

**Comment by rlee1990** [comment] 2023-09-04 06:10
@darshankawar we are not using master we are using the stable channel.

**Comment by danielnordh** [comment] 2023-09-04 11:38
I'm also having this issue after upgrading from 3.10 to 3.13.2 on Stable channel.
All coming from the http package when making https calls.

Happens in debug mode on both Android and iOS device.

**Comment by DanTup** [comment] 2023-09-05 09:51
> @DanTup for thoughts on the error reported.

It's hard to say without a repro (or confirmation it occurs with the example linked above).

Two questions I have for those that are hitting this though:

- If you ensure both "All Exceptions" and "Uncaught Exceptions" are **unticked** in the VS Code debug sidebar, does this still occur?
- If you click the Resume (play) button on the debug toolbar when the error occurs, does the app continue normally or show an error?

**Comment by danielnordh** [comment] 2023-09-05 10:17
> * If you ensure both "All Exceptions" and "Uncaught Exceptions" are **unticked** in the VS Code debug sidebar, does this still occur?

No, if I untick both things _seem_ to work normally (have not done conclusive testing on all parts of app).

> * If you click the Resume (play) button on the debug toolbar when the error occurs, does the app continue normally or show an error?

Clicking the Resume button skips to the next exception (every network call basically).

**Comment by DanTup** [comment] 2023-09-05 11:24
> No, if I untick both things seem to work normally (have not done conclusive testing on all parts of app).

And if you have only "Uncaught exceptions" ticked, does it occur?

If so, then I think this is likely the same issue as https://github.com/dart-lang/sdk/issues/53334. A recent bug causes the VM to treat some _caught_ exceptions as _uncaught_ and pause the debugger. I believe there's a plan to hotfix this but for now the best workaround is to leave the exception tickboxes unticked unless specifically debugging an exception.

If it doesn't occur when only "Uncaught exceptions" is ticked and only occurs when "All exceptions" is ticked, then this is working as intended (that is, you're asking the debugger to pause on all exceptions, even though that are handled/caught). There's an issue at https://github.com/flutter/devtools/issues/5883 discussing whether this behaviour is really desirable or whether caught exceptions in non-debuggable code should be excluded.

**Comment by danielnordh** [comment] 2023-09-05 13:07
> And if you have only "Uncaught exceptions" ticked, does it occur?

Yes. All exceptions was unticked.
Thanks for the debugging. I will leave both unticked for now. 👍

**Comment by rlee1990** [comment] 2023-09-05 13:37
So yes the example runs just fine.
My issue is only on Android when the Uncaught exceptions are ticked it will not allow the app to function at all.
When I untick the Uncaught exceptions

**Comment by huycozy** [comment] 2023-09-06 08:24
Thanks for confirming this. Based on comments above, I will close this issue, please follow up on the Dart issue for updates.

**Closed by huycozy** 2023-09-06 08:24 UTC
Labels: in triage
