### ISSUE TITLE
Incompatibility with "flutter_facebook_auth" plugin

### ISSUE THREAD

**Issue by fabienlierville** [flutter/flutter#73335] opened 2021-01-05 16:27 UTC
## Steps to Reproduce

1. Create Flutter Projet
2. Add to Pubspec.yaml 
```
  flutter_facebook_auth: ^1.0.2+2
  image_picker: ^0.6.7+17
```

3. Create a Widget to pick image like the ReadMe section 
4. Run the application

I get this error :

```
E/flutter ( 6252): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
E/flutter ( 6252): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 6252): <asynchronous suspension>
E/flutter ( 6252): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 6252): #2      MethodChannelImagePicker.pickImagePath (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
E/flutter ( 6252): #3      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:25)
E/flutter ( 6252): #4      ImagePicker.getImage (package:image_picker/image_picker.dart:106:21)
E/flutter ( 6252): #5      _MyHomePageState.getImage (package:flutter_imagepickr/main.dart:65:37)
E/flutter ( 6252): #6      _MyHomePageState.build.<anonymous closure> (package:flutter_imagepickr/main.dart:53:19)
E/flutter ( 6252): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 6252): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 6252): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 6252): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 6252): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 6252): #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 6252): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 6252): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 6252): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 6252): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 6252): #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 6252): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 6252): #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter ( 6252): #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 6252): #21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 6252): #22     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 6252): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 6252): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 6252): #25     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 6252): #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6252): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 6252): #28     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 6252): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 6252): 
```

When I remove "flutter_facebook_auth: ^1.0.2+2" in pubspec, I don't have problem

**Comment by iapicca** [comment] 2021-01-05 19:53
@fabienlierville 
this seems to be an issue with the 3rd party plugin [flutter_facebook_auth](https://pub.dev/packages/flutter_facebook_auth) rather than flutter,
I recommend to open an issue in the dedicated [github](https://github.com/darwin-morocho/flutter-facebook-auth/issues)

you may also look at this possible [solution](https://github.com/flutter/flutter/issues/73209#issuecomment-753645788)

**Comment by TahaTesser** [comment] 2021-01-06 07:43
Hi @fabienlierville 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/darwin-morocho/flutter-facebook-auth/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-06 07:43 UTC
