### ISSUE TITLE
flake: docs-linux fails with missing source file from pub-cache

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#48431] opened 2020-01-08 18:33 UTC
`docs-linux` (https://cirrus-ci.com/task/6043942168821760?command=main#L50) failed with:

```
Downloading dartdoc 0.29.2...
Precompiling executables...
Failed to precompile dartdoc:dartdoc:
/root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.29.2/lib/src/model/package_builder.dart:24:8: Error: Error when reading '/root/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.3/lib/src/source/sdk_ext.dart': No such file or directory
import 'package:analyzer/src/source/sdk_ext.dart';
       ^
/root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.29.2/lib/src/model/package_builder.dart:117:19: Error: The method 'SdkExtUriResolver' isn't defined for the class 'PackageBuilder'.
 - 'PackageBuilder' is from 'package:dartdoc/src/model/package_builder.dart' ('/root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.29.2/lib/src/model/package_builder.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SdkExtUriResolver'.
    resolvers.add(SdkExtUriResolver(packageMap));
                  ^^^^^^^^^^^^^^^^^
```

Passed on re-run.

**Comment by godofredoc** [comment] 2020-01-09 23:17
Chris is this the same as dart-docs in devicelab?

**Comment by christopherfujino** [comment] 2020-01-10 16:54
No, this is `flutter/dev/bots/docs.sh`, it builds the api docs. It looks like the devicelab `dartdocs` benchmark counts class members without dartdoc annotation.

**Comment by godsoul** [comment] 2020-01-30 12:54
Failed to precompile dartdoc:dartdoc:
../../.pub-cache/hosted/pub.flutter-io.cn/dartdoc-0.29.1/lib/src/model.dart:46:8: Error: Error when reading '../../.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.39.4/lib/src/source/sdk_ext.dart': No such file or directory
import 'package:analyzer/src/source/sdk_ext.dart';
       ^
../../.pub-cache/hosted/pub.flutter-io.cn/dartdoc-0.29.1/lib/src/model.dart:6972:19: Error: The method 'SdkExtUriResolver' isn't defined for the class 'PackageBuilder'.
 - 'PackageBuilder' is from 'package:dartdoc/src/model.dart' ('../../.pub-cache/hosted/pub.flutter-io.cn/dartdoc-0.29.1/lib/src/model.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SdkExtUriResolver'.
    resolvers.add(SdkExtUriResolver(packageMap));
                  ^^^^^^^^^^^^^^^^^

**Comment by Hixie** [comment] 2020-08-03 21:55
Closing since we haven't reproduced this in months and it's not really actionable in its current state...

**Closed by Hixie** 2020-08-03 21:55 UTC
Labels: passed secondary triage, team, team: flakes, team: infra
