### ISSUE TITLE
PanGestureRecognizer don't perform as expected.

### ISSUE THREAD

**Issue by LucasXu0** [flutter/flutter#110759] opened 2022-09-01 07:16 UTC
Hi, I found that after upgrading flutter to 3.3.0, the `PanGestureRecognizer` seems to behave unexpectedly. Even using two fingers to move around the trackpad in macOS, the `PanGestureRecognizer`'s callbacks still be called. 

Before upgrading, the `PanGestureRecognizer`'s callbacks only work on three fingers movement in macOS.

## Steps to Reproduce

1. Execute `flutter run` on the code sample with version **3.3.0**. 
2. Use **two** fingers to move around the trackpad.

**Expected results:** 
The `PanGestureRecognizer`'s callbacks, like `onStart`, `onUpdate` and `onEnd`, should not be called.

**Actual results:** 
The `PanGestureRecognizer`'s callbacks, like `onStart`, `onUpdate` and `onEnd`, have been called.

**Code sample**
```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: Sample(),
      ),
    );
  }
}

class Sample extends StatelessWidget {
  const Sample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: RawGestureDetector(
        behavior: HitTestBehavior.translucent,
        gestures: {
          PanGestureRecognizer:
              GestureRecognizerFactoryWithHandlers<PanGestureRecognizer>(
            () => PanGestureRecognizer(),
            (recognizer) {
              recognizer
                ..onStart = (details) {
                  debugPrint('onStart');
                }
                ..onUpdate = (details) {
                  debugPrint('onUpdate');
                }
                ..onEnd = (details) {
                  debugPrint('onEnd');
                };
            },
          ),
        },
        child: Column(
          children: List<Widget>.filled(
            100,
            const Text(
              'ABC',
              style: TextStyle(fontSize: 50),
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by exaby73** [comment] 2022-09-01 20:30
Hello @LucasXu0. I am not able to reproduce the behavior you are describing. I do not see any logs printed to the console with two or three finger swipes on either `3.3.0` or `3.0.5`. 

Could you leave detailed steps to reproduce the issue with a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as well as your logs of `flutter doctor -v`?

**Comment by LucasXu0** [comment] 2022-09-02 02:08
Hi, @exaby73. I uploaded a video and the full sample code. 

In this video, I swipe **horizontally** on the trackpad with two fingers.

https://user-images.githubusercontent.com/11863087/188042824-9c208587-fe8e-46af-973b-1f8d5e48941b.mov

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: Sample(),
      ),
    );
  }
}

class Sample extends StatelessWidget {
  const Sample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: RawGestureDetector(
        behavior: HitTestBehavior.translucent,
        gestures: {
          PanGestureRecognizer:
              GestureRecognizerFactoryWithHandlers<PanGestureRecognizer>(
            () => PanGestureRecognizer(),
            (recognizer) {
              recognizer
                ..onStart = (details) {
                  debugPrint('onStart ${details.kind}');
                }
                ..onUpdate = (details) {
                  debugPrint('onUpdate');
                }
                ..onEnd = (details) {
                  debugPrint('onEnd');
                };
            },
          ),
        },
        child: Column(
          children: List<Widget>.filled(
            100,
            const Text(
              'ABC',
              style: TextStyle(fontSize: 50),
            ),
          ),
        ),
      ),
    );
  }
}
```

Here is the `flutter doctor -v` result.
```shell
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.0 on channel stable at /Users/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.52

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101
```

**Comment by exaby73** [comment] 2022-09-02 07:06
I can reproduce this issue.

### Reproducible on

- `Stable (3.3.0)`
- `Master (3.4.0-19.0.pre.35)`

### Info

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: Sample(),
      ),
    );
  }
}

class Sample extends StatelessWidget {
  const Sample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: RawGestureDetector(
        behavior: HitTestBehavior.translucent,
        gestures: {
          PanGestureRecognizer:
              GestureRecognizerFactoryWithHandlers<PanGestureRecognizer>(
            () => PanGestureRecognizer(),
            (recognizer) {
              recognizer
                ..onStart = (details) {
                  print('onStart');
                }
                ..onUpdate = (details) {
                  print('onUpdate');
                }
                ..onEnd = (details) {
                  print('onEnd');
                };
            },
          ),
        },
        child: Column(
          children: List<Widget>.filled(
            100,
            const Text(
              'ABC',
              style: TextStyle(fontSize: 50),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
    • Flutter version 3.3.0 on channel stable at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 104.1.42.97

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.35, on macOS 12.5.1 21G83 darwin-arm64, locale en-US)
    • Flutter version 3.4.0-19.0.pre.35 on channel master at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7731fe7a71 (2 hours ago), 2022-09-02 00:40:11 -0400
    • Engine revision f1aa081cbe
    • Dart version 2.19.0 (build 2.19.0-154.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 104.1.42.97

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by LucasXu0** [comment] 2022-09-02 12:54
It's a breaking change that makes my editor app run unexpectedly. Looks forward to the fixing. Thanks. 😁

**Comment by moffatman** [comment] 2022-09-02 14:46
@LucasXu0 It's an intended change. You can use `supportedDevices` parameter on the gesture detector if you don't want to get events based on trackpad gestures. I was waiting for some additional change to be assigned a version number to write-up a full migration guide.

**Comment by exaby73** [comment] 2022-09-05 07:02
@moffatman Thanks for the clarification. Since this is an intended change, I am closing this issue.

**Closed by exaby73** 2022-09-05 07:02 UTC
Labels: severe: regression, framework, f: gestures, a: desktop, has reproducible steps, found in release: 3.3, found in release: 3.4

**Comment by moffatman** [comment] 2022-09-06 03:47
@LucasXu0 I wrote a guide to help with migration here: https://docs.flutter.dev/release/breaking-changes/trackpad-gestures
