### ISSUE TITLE
Tooltip Menu Shown behind Status Bar / Notch

### ISSUE THREAD

**Issue by iqbalmineraltown** [flutter/flutter#25066] opened 2018-12-07 07:48 UTC
This might be related to #19954 

## Steps to Reproduce
1. Create `TextField` and put it on the top side of the screen. Wrap it with `SafeArea`
2. Type some text then tap and hold it until tooltip menu appear

## Expected Result
Tooltip menu appears below TextField, avoiding notch and status bar
<img width="342" alt="screen shot 2018-12-07 at 14 03 37" src="https://user-images.githubusercontent.com/3488542/49633654-c2e39580-fa2c-11e8-810e-5b1ef0d74fb6.png">
<img width="389" alt="screen shot 2018-12-07 at 14 27 23" src="https://user-images.githubusercontent.com/3488542/49633655-c37c2c00-fa2c-11e8-8159-5b8b5f9d16df.png">

## Actual Result
Tooltip menu taking space behind notch / status bar, even after I use `SafeArea` to wrap everything (see first screenshot)
<img width="339" alt="screen shot 2018-12-07 at 14 01 50" src="https://user-images.githubusercontent.com/3488542/49633771-34234880-fa2d-11e8-8f41-2607217ddd33.png">
<img width="388" alt="screen shot 2018-12-07 at 14 27 08" src="https://user-images.githubusercontent.com/3488542/49633772-34bbdf00-fa2d-11e8-8924-b2342c6df63b.png">
This happened on both iOS and Android

## `flutter doctor -v` Output
(dont mind the license status, it's related to issue where I need to execute sdkmanager update)
```
$ flutter doctor -v
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-ID)
    • Flutter version 1.0.0 at /Users/iqbal/dev/flutter
    • Framework revision 5391447fae (7 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/iqbal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/iqbal/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone XR • FD82670D-E505-4E7B-834A-DC428D7DE457 • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-12-28 14:11
Related to #3945

**Comment by goderbauer** [comment] 2019-01-04 21:58
This is a dupe of https://github.com/flutter/flutter/issues/3945. The third comment there mentions that these positions should be avoided.

**Closed by goderbauer** 2019-01-04 21:58 UTC
Labels: a: fidelity, a: text input, framework
