### ISSUE TITLE
Sometimes it says Gradle exited abnormally sometimes says apply plugin in app/gradle

### ISSUE THREAD

**Issue by vijaysolankii** [flutter/flutter#37932] opened 2019-08-09 14:27 UTC
![Capture](https://user-images.githubusercontent.com/37324125/62786207-c3fb2400-badf-11e9-9a65-f4a4ce6f8de2.JPG)

Please help me...(<_>)

**Comment by axel-op** [comment] 2019-09-04 11:35
What command did you run? 
Try to execute it with `-v`

**Comment by vijaysolankii** [comment] 2019-09-05 16:59
flutter doctor -v
then i run with this command
flutter run

**Comment by BondarenkoStas** [comment] 2019-09-18 13:22
Duplicate of #38163.
If you disagree, please comment and I will re-open it right away.

**Closed by BondarenkoStas** 2019-09-18 13:22 UTC
