### ISSUE TITLE
Could not issue any flutter commands due to "startup lock"

### ISSUE THREAD

**Issue by edbienes** [flutter/flutter#7768] opened 2017-02-01 00:46 UTC
## Steps to Reproduce

1. Open Flutter Project via Intellij
2. The play/stop buttons at the top is not enabled even after opening a simulator
3. Open terminal (inside/out of intellij) and enter command: `flutter doctor`

## Logs

Only outputs:
`Waiting for another flutter command to release the startup lock...`

## Flutter Doctor

The same output message as above after running `flutter doctor`
Could not run other commands like `flutter analyze`

## Additional details

- `lockfile` exists at `flutter/bin/cache`
- `flutter/` dir is set to chmod 777 already just in case the system file is read-only
- no other flutter related results after issuing `ps` command

**Comment by Hixie** [comment] 2017-02-01 00:52
What happens if you run `touch flutter/bin/cache/lockfile`?
What happens if you run `flock -x -n 8 8< bin/cache/lockfile`?
Does `ps` list any dart processes?
Does it work if you reboot and don't have IntelliJ running?

**Comment by edbienes** [comment] 2017-02-01 01:29
- nothing happened after the `touch...`
- `flock` command is not found
- no dart nor flutter processes after `ps` run
- directly running `flutter doctor` (without Intellij )and it's `Downloading package sky_engine...`

Seems the problem is with Intellij. The download took a loong time then I did a `flutter run` and now it's doing this so far...

```
> flutter run
Downloading package sky_engine...                   5300ms
Running 'flutter packages get' in sky_engine...     1227ms
Building Dart SDK spec summary...                   3053ms
Building Dart SDK strong summary...                 1482ms
Downloading engine artifacts android-arm...             |
```

Will let you know once this is finished.

**Comment by edbienes** [comment] 2017-02-01 03:31
The download hasn't finished.. So can't tell yet if this will work or not.

```
> flutter doctor
Downloading package sky_engine...                   989ms
Running 'flutter packages get' in sky_engine...     738ms
Building Dart SDK spec summary...                   2161ms
Building Dart SDK strong summary...                 1036ms
Downloading engine artifacts android-arm...         28493ms
Downloading engine artifacts android-arm-profile... 26910ms
Downloading engine artifacts android-arm-release... 22572ms
Downloading engine artifacts android-x64...         55432ms
Downloading engine artifacts android-x86...         34115ms
Downloading engine artifacts ios...                 31268ms
Downloading engine artifacts ios-profile...         28250ms
Downloading engine artifacts ios-release...         27296ms
Downloading darwin-x64 tools...                     45699ms
Downloading android-arm-profile/darwin-x64 tools...     -
```

**Comment by edbienes** [comment] 2017-02-01 07:38
When I run `ps` after the `flutter run` command, I see this:

```
 2496 ttys002    0:00.01 /bin/bash /[...redacted...]/flutter/bin/flutter run
 2508 ttys002    0:00.70 /[...redacted...]/flutter/bin/cache/dart-sdk/bin/dart /[...redacted...]/flutter/bin/cache/flutter_tools.snap
```

Please advise.

**Comment by Hixie** [comment] 2017-02-01 22:12
Yeah the first is the shell script and the second is the dart program that the shell script launches.

When you don't have IntelliJ up it works fine right? It's only when IntelliJ is up that there's a problem?
What does `ps` show when it's not working?

**Comment by edbienes** [comment] 2017-02-02 02:20
`ps` shows the same results (those 2 lines) when running Intellij or not.

The difference is, when opening the project in Intellij, you could not process any other commands like `flutter doctor` and you'd get the message about "startup lock".

**Comment by Hixie** [comment] 2017-02-02 05:47
I'm confused as to the state of your system. I don't really understand what's going on. `ps` should only be showing those lines if you're running the `flutter` tool. Can you describe in more detail your methodology for testing the above? Are you running `flutter run` and IntelliJ and `ps` all at once, or one after the other, or what?

**Comment by edbienes** [comment] 2017-02-02 07:01
It is just very weird. I am not doing anything (except for the following below) and now it just works!

** There was a Flutter plugin update earlier to 0.1.9 and it did somehow fix the issue. Then followed by a successful `flutter doctor`.**

As for the methodology you asked, here's what I did to test:
I. With Intellij
1. Open project with Intellij
2. ** No play button on Intellij **
3. So do a `flutter run` on terminal
4. "Startup lock" message occurs

II. Without Intellij
1. `cd` to the project directory
2. `flutter doctor` or `flutter run` would download sky_engine all the time then get stuck on the next downloads as pasted on the previous comment.

**Comment by Hixie** [comment] 2017-02-02 07:29
I wonder if maybe IntelliJ was downloading the artifacts in the background and then getting stuck just like `flutter run` for you. While downloading the artifacts you can't run other flutter processes.

**Comment by eseidelGoogle** [comment] 2017-02-02 16:17
We've had numerous complaints about our artifact downloads being too big/too long.  https://github.com/flutter/flutter/issues/6491 is one bug on file about making commands only download what they need.  `flutter deamon` presumably doesn't need any?

**Comment by devoncarew** [comment] 2017-02-02 16:23
I don't think it would, it just handles device notifications. That needs the native toolchains to be available, but wouldn't use any of the artifacts for building / running apps.

**Comment by Hixie** [comment] 2017-11-29 00:37
@sethladd Does this count as an example of a "getting started blocker" or should we punt to m4?

**Comment by sethladd** [comment] 2017-11-29 16:40
I think we can close this because the issue is pretty old. But if others report it, we can re-open the issue.

@edbienes apologies for the trouble here! Hope it's working now for you.

**Closed** 2017-12-20 02:38 UTC

**Comment by baileyfriend** [comment] 2018-01-23 00:31
Currently having this issue myself. Ran a `flutter packages get` and got the 

> Waiting for another flutter command to release the startup lock...

`ps` results in the following:
`
  PID TTY           TIME CMD
21625 ttys001    0:00.04 /bin/bash --rcfile /Applications/IntelliJ IDEA CE.app/Contents/plugins/terminal/jediterm-bash.in --login -i
 4807 ttys002    0:00.27 -bash
`

Any idea what the cause of this is?

**Comment by fmatosqg** [comment] 2018-03-20 07:04
going to flutter dir and ```rm ./bin/cache/lockfile``` solved my problem, but I was sure it wasn't running.

**Comment by deborah-ufw** [comment] 2018-03-20 07:14
It did eventually run. I think the real problem for me was that "packages get" is getting some very large packages, making it seem like the process has crashed when really it is just taking a very long time. However, I needed a way to kill the process really dead and there does not appear to be a way.

**Comment by KEYART** [comment] 2018-05-15 08:34
I also just experienced the issue.
I solved it by executing `rm ./bin/cache/lockfile`.

**Comment by zakiso** [comment] 2018-12-31 14:31
ps -ef | grep flutter | grep -v grep | awk '{print $2}' | xargs kill -9 

kill all flutter process solved it.

**Comment by messouaboya** [comment] 2019-03-31 12:23
yes delete lockfile and restart it works

**Comment by ciez** [comment] 2019-04-16 15:44
constant 
> Waiting for another flutter command to release the startup lock...
message

killing process, rm lockfile does not work for me.

Flutter 1.2.1
Dart 2.1.2

**Comment by netwiser** [comment] 2019-05-21 15:27
Not sure this issue is relative to Intellij IDEA Ultimate 2019.1 or Dart. With the IDEA running none of the other flutter commands can be run.  The lock file under $flutter/bin/cache is locked and can't be removed, has to shut down the IDEA, wait for hundred of dart.exe threads finish.

**Comment by ArtHoffmann** [comment] 2019-05-27 08:07
> 
Not sure this issue is relative to Intellij IDEA Ultimate 2019.1 or Dart. With the IDEA running none of the other flutter commands can be run. The lock file under $flutter/bin/cache is locked and can't be removed, has to shut down the IDEA, wait for hundred of dart.exe threads finish.
> 

i have the same problem, nothing helps unfortunately

**Comment by theindianappguy** [comment] 2019-12-18 07:21
deleting locks file does not work for MAC

**Comment by theindianappguy** [comment] 2019-12-18 07:31
🎉 Found Solution
For Mac Users
1. Go to System Preferences
2. Click Security & Privacy
3. There will be option > allow apps downloaded from, click on allow anyway
4. will be shown a popup click allow
5.  another popup click open

DONE
Happy Coding

**Comment by eseidelGoogle** [comment] 2019-12-18 15:03
@theindianappguy We sign our binaries on mac so that shouldn't be necessary. If others are seeing such, we would love a new bug.

**Comment by aneesalahsab** [comment] 2020-04-03 19:38
write this in terminal 
killall -9 dart
