### ISSUE TITLE
Transition performance regressed slightly due to OpacityLayer raster cache miss

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#52864] opened 2020-03-18 23:59 UTC
The regression is introduced by https://github.com/flutter/engine/pull/14024 around 12/4/2019 on flutter_gallery__transition_perf average_frame_rasterizer_time_millis. It's small so it didn't turn the graph red:

<img width="240" alt="Screen Shot 2020-03-18 at 4 53 29 PM" src="https://user-images.githubusercontent.com/22987568/77018050-619db800-6939-11ea-991f-411ca964d09e.png">

@flar first noticed this issue while he was working on `ImageFilteredLayer` and he's working on a fix https://github.com/flutter/engine/pull/17175

**Comment by kf6gpe** [comment] 2020-03-30 21:36
Looks like it may still be an issue, looking at the recent history here. @flar, any thoughts?

![Screen Shot 2020-03-30 at 2 35 51 PM](https://user-images.githubusercontent.com/1435716/77964382-d0f99d00-7293-11ea-97d7-06be6b5284ce.png)

**Comment by flar** [comment] 2020-03-30 23:48
The original issue has never gone away and will continue to be a problem until https://github.com/flutter/engine/pull/17175 lands, hopefully in the next week.

The recent spikes could represent an additional problem, I'd have to investigate them. In particular, this may be the first evidence that the vsync-locking issue that affects iOS/OpenGL can also affect Android.

**Comment by kf6gpe** [comment] 2020-04-21 16:49
This looks like it, or something else, is also affecting the 99th_percentile_frame_rasterizer_time_millis
 and worst_frame_rasterizer_time_millis benchmarks at this point.

**Comment by flar** [comment] 2020-04-21 19:49
Can you be more specific about which benchmarks and what time frame?

I looked briefly at the transitions benchmarks and did find https://github.com/flutter/flutter/issues/55319 but that is on the average build times.

There seems to be little changing with the 99th% rasterization times of the android transitions benchmark but the worst rasterization time has a couple of recent but isolated spikes. Neither graph shows much change around when the original issue with opacity caching was introduced to the engine, though (around 12/4/2019).

**Comment by kf6gpe** [comment] 2020-04-22 15:59
Sorry. flutter_gallery__transition_perf average_frame_rasterizer_time_millis, about the same time frame:
![Screen Shot 2020-04-22 at 8 56 48 AM](https://user-images.githubusercontent.com/1435716/80004487-3bf35980-8477-11ea-96fd-0a0a7b8bf3cb.png)

**Comment by flar** [comment] 2020-04-22 16:16
To be clear the time frame for this issue is December of last year. April 4th is 4 months after the problem described by this bug report.

The spikes you see are usually not themselves the result of a regression. The fact that they don't happen on every sample is usually an indication that we were near a threshold where the system locks us out until a vsync curtain and we got slightly closer to the threshold and are now triggering it more often. If you ignore them then the times aren't too significantly different than they were before April, but the build times may have gotten worse and pushed the completion of the frames closer to the mysterious deadline that causes this. Unfortunately, the build time benchmark appears to have been archived so it doesn't show up in the benchmark window. If you show the archived benchmarks then you can see that the build times recently became spiky and are averaging nearly half a ms longer than they were starting in late March.

The opacity raster cache misses are not the cause of the recent spikes you see. But they may be among a number of contributing factors that helped us get closer to that precipice. When the opacity fix goes in, it may bring us back from that threshold which might be enough to make the spikes disappear, but that won't mean that there wasn't a recent regression somewhere else.

**Comment by chinmaygarde** [comment] 2020-06-11 01:21
Triage: Is there anything to do here. From @flar's last comment, it seems like we were on the edge earlier and now we go over it more often.  Since this issue looks parked for later investigation the opacity fix goes in, assigning a P6. Feel free to revise.

**Comment by flar** [comment] 2020-06-11 07:34
This issue is about a bug that was introduced in December. We had a small regression in December for a known issue.

Other than the original comment from March 18, the comments on this thread (including the ones I added) have been mostly about something else that is unrelated to the original issue.

The fix for the original issue went in with the engine roll (https://github.com/flutter/flutter/pull/58230) which included the engine caching fix for opacity layers (https://github.com/flutter/engine/pull/17914).

Unfortunately, with all of the spikiness that has been happening over the past couple of months (which does not reproduce locally leading us to believe it was a devicelab issue that we can't diagnose remotely) we have no clear data to observe the improvement from the fix for the gallery transitions benchmark mentioned in the first comment and since it was 6 months from the bug to the fix, other issues may have come into play which would make the fix have minimal impact. The original regression was small and the benchmark noise that was happening when it was fixed prevent us from getting a good statistical measure of how much the fix helped.

Fortunately, there is another benchmark specifically designed to measure the performance of opacity layers and that benchmark shows an obvious improvement in average rasterizer times when the fix went in (see fading_child_animation_perf__timeline_summary on the benchmark page).

I am going to close this issue as the original bug is fixed as can be seen in the new benchmark.

**Closed by flar** 2020-06-11 07:34 UTC
Labels: P6, engine, perf: speed, severe: performance, severe: regression
