### ISSUE TITLE
Const constructor for column and row

### ISSUE THREAD

**Issue by Lafannn** [flutter/flutter#93626] opened 2021-11-14 21:09 UTC
## Use case

Flutter doesn't rebuild widgets that marked created through const constructor and main part of flutter widgets support const constructors. Except Column and Row

## Proposal

Add const constructor for Column and Row

**Comment by Tinomuchenje** [comment] 2021-11-14 22:31
This is allowed in the form of making the children const. Syntax `Column( children: const [ ])` . The same works for Row. 
Bear in mind Column and Row are just layout widgets.

**Comment by danagbemava-nc** [comment] 2021-11-15 07:59
Hi @Lafannn, as pointed out above, this is already possible. 

The `Column/Row` themselves do not need to be `const` as they're only for laying out the widgets, it's the children that need to `const`.  The same behavior applies to the rest of the Multi child layout widgets. 

Closing as this is the intended behavior. 

If you disagree, kindly leave a comment below and I will reopen. 

Thank you

**Comment by Lafannn** [comment] 2021-11-17 10:32
@danagbemava-nc yes, but I can't make parent of column `const`. In case when parent of const is complex widget and I want to do it `const` it is problem.

**Comment by danagbemava-nc** [comment] 2021-11-17 13:22
I'm not sure I get what you want to achieve. 
Can you share such an example of a complex widget?

**Comment by goderbauer** [comment] 2021-11-17 22:49
We cannot make this const at this time because of https://github.com/dart-lang/sdk/issues/29276.

**Closed by goderbauer** 2021-11-17 22:49 UTC
Labels: waiting for customer response, in triage
