### ISSUE TITLE
Flutter Web Gives route forcely to my app and then says firebase app is not initialized when i refresh the page

### ISSUE THREAD

**Issue by drakenz** [flutter/flutter#60328] opened 2020-06-26 00:45 UTC
I made a flutter web app and im having a problem with firebase
Problem Statement:
The app 

This is my main widget
```
class _LoginScreen extends State<MyApp> {
/*void _redirect() {
  Navigator.pushReplacement(context,MaterialPageRoute(builder: (BuildContext context) => LoginRegister()));
}*/

Widget build(context)
{
  return MaterialApp(
    home: LoginRegister()
  );

}
```

The app start as www.myurl.com/#/ on my pc and when i navigate there are no routes
But when i upload it to firebase it forcely gives a route on login screen
Also , whenever i refresh the page i get JS error says : FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
Though the script is called in index.html
Any suggestions ?

**Comment by iapicca** [comment] 2020-06-26 11:03
Hi @drakenz 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-26 11:03 UTC
