### ISSUE TITLE
  image_picker: ^0.6.1+4   why unsupported .png format file???

### ISSUE THREAD

**Issue by zhanghaigang666** [flutter/flutter#41346] opened 2019-09-26 04:42 UTC
```
E/OpenGLRenderer(19176): hwui_debug::CanvasContext createSurface sur=0x0, isValid =0
E/OpenGLRenderer(19176): hwui_debug::CanvasContext createSurface sur=0x0, isValid =0
I/ExifInterface_JNI(19176): Raw image not detected
W/ExifInterface(19176): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
W/ExifInterface(19176): java.io.IOException: Invalid marker: 89
W/ExifInterface(19176): 	at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1893)
W/ExifInterface(19176): 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1505)
W/ExifInterface(19176): 	at android.media.ExifInterface.<init>(ExifInterface.java:1130)
W/ExifInterface(19176): 	at io.flutter.plugins.imagepicker.ExifDataCopier.copyExif(ExifDataCopier.java:15)
W/ExifInterface(19176): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:41)
W/ExifInterface(19176): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:530)
W/ExifInterface(19176): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
W/ExifInterface(19176): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
W/ExifInterface(19176): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
W/ExifInterface(19176): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
W/ExifInterface(19176): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
W/ExifInterface(19176): 	at android.app.Activity.dispatchActivityResult(Activity.java:7283)
W/ExifInterface(19176): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4396)
W/ExifInterface(19176): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4443)
W/ExifInterface(19176): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
W/ExifInterface(19176): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
W/ExifInterface(19176): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/ExifInterface(19176): 	at android.os.Looper.loop(Looper.java:185)
W/ExifInterface(19176): 	at android.app.ActivityThread.main(ActivityThread.java:6615)
W/ExifInterface(19176): 	at java.lang.reflect.Method.invoke(Native Method)
W/ExifInterface(19176): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
W/ExifInterface(19176): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)
I/ExifInterface_JNI(19176): Raw image not detected
```

**Comment by escamoteur** [comment] 2019-09-26 13:56
Hi,
thanks for reorting this issue. Could  you please add the utout of `flutter doctor` here and attach the image that makes the problem?

**Comment by zhanghaigang666** [comment] 2019-09-28 01:50
C:\Users\zhanghg\Desktop\flutter-book-master>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.16299.967], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

• No issues found!

**Comment by escamoteur** [comment] 2019-09-28 05:00
Does it happen with all images or only specific ones?

If only one image makes the problem please attach it here

Have you tried it on different Phone types?

**Comment by zhanghaigang666** [comment] 2019-09-29 01:43
I specified the screenshot png format file will report an error, the specified album jpg format file will not report an error, and I found that although the report is wrong, it does not affect my use of this plugin, can also call me "file" if the error is reported.

Also, I found that the plugin using version 0.4.10 will not report an error, and the latest version will report an error.

**Comment by escamoteur** [comment] 2019-09-29 09:33
Thanks, that's valuable information.
Which Android version is your phone where you experience this?

**Comment by zhanghaigang666** [comment] 2019-09-30 01:43
android 7.1.1

**Comment by nottyjay** [comment] 2019-10-15 00:57
It also happend on my device. Android 9

**Comment by mkubasz** [comment] 2019-10-28 17:42
This same for me. Android API 25.

**Comment by mkubasz** [comment] 2019-10-29 08:35
I want to add that the issue is related to Camera too. I can't choose from the folder photo and take a photo. @escamoteur

**Comment by mkubasz** [comment] 2019-10-30 19:40
@escamoteur Yes, I have a new AndroidX. New version fix that is working but still in the background I can see the exception. So hurra it's working on Android but will be good for working without any exception codes. On iOS this package turns off application without a message. Only "lost connection to device":

`D/ImageResizer(14561): image_picker: compressing is not supported for type PNG. Returning the image with original quality
I/ExifInterface_JNI(14561): Raw image not detected
W/ExifInterface(14561): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
W/ExifInterface(14561): java.io.IOException: Invalid marker: 89
W/ExifInterface(14561): 	at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
W/ExifInterface(14561): 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
W/ExifInterface(14561): 	at android.media.ExifInterface.<init>(ExifInterface.java:1112)
W/ExifInterface(14561): 	at io.flutter.plugins.imagepicker.ExifDataCopier.copyExif(ExifDataCopier.java:15)
W/ExifInterface(14561): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:41)
W/ExifInterface(14561): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:530)
W/ExifInterface(14561): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
W/ExifInterface(14561): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
W/ExifInterface(14561): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
W/ExifInterface(14561): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:131)
W/ExifInterface(14561): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
W/ExifInterface(14561): 	at android.app.Activity.dispatchActivityResult(Activity.java:7109)
W/ExifInterface(14561): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4192)
W/ExifInterface(14561): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239)
W/ExifInterface(14561): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
W/ExifInterface(14561): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
W/ExifInterface(14561): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/ExifInterface(14561): 	at android.os.Looper.loop(Looper.java:165)
W/ExifInterface(14561): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
W/ExifInterface(14561): 	at java.lang.reflect.Method.invoke(Native Method)
W/ExifInterface(14561): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
W/ExifInterface(14561): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)`

**Comment by escamoteur** [comment] 2019-10-31 08:56
@mkubasz on which flutter channel and version are you?

**Comment by mkubasz** [comment] 2019-10-31 10:42
@escamoteur Flutter (Channel master, v1.10.15-pre.252, on Linux, locale en_US.UTF-8) This error message comes API 25 but on API 29 is working. I tested on Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-PL) and on iOS iPhone application down but on Android 28 API I didn't see an error. I think that is only related with API version of Android. But on iOS I have not idea.

**Comment by blackholegalaxy** [comment] 2019-11-01 01:04
It also happen on our side. Channel stable of flutter, just updated, image_picker 0.6.1+10. Happens on emulator every time you try using camera (with the fake image from emulator, in PNG format) then using image.

**Comment by i6x86** [comment] 2019-11-12 14:12
same issue on iphone 7
 I/ExifInterface_JNI: Raw image not detected
>  W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.

I sent the same image via WhatsApp on Android and there's no problem to upload it

**Comment by i6x86** [comment] 2019-11-12 18:00
> same issue on iphone 7
> I/ExifInterface_JNI: Raw image not detected
> 
> > W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
> 
> I sent the same image via WhatsApp on Android and there's no problem to upload it

My bad the log is from Android device, but it crashes on iPhone 7, on Android it builds and works fine, despite the message.

**Comment by jonataslaw** [comment] 2020-01-23 19:32
This error remain on last version on android devices

**Comment by lifenautjoe** [comment] 2020-02-15 14:42
Can confirm the same issue.

**Comment by Apollo108** [comment] 2020-02-20 14:08
The same issue here in the latest v.0.6.3+3. When choosing .png file it the debugger I can it assigns .jpg extension to chosen file instead of .png for some reason, and my GRPC server doesn't like it at all :)

**Comment by lifenautjoe** [comment] 2020-02-24 21:40
Any update on this? 🙏

**Comment by cyanglaz** [comment] 2020-03-12 18:22
Un-assign myself from this issue as I don't have cycle to actively working on it.

**Comment by aryan29** [comment] 2020-06-05 09:49
I am using latest version of imae picker and image picker is saving my PNG files too in .jpg format

**Comment by darshankawar** [comment] 2021-02-10 12:14
Verified this issue on latest stable using Samsung S10 device and official `image_picker` plugin example as code sample. Selected a .png image from `downloads` section of the device, which was returned properly without any issues.

<img width="341" alt="Screenshot 2021-02-10 at 5 41 42 PM" src="https://user-images.githubusercontent.com/67046386/107508584-4417b380-6bc7-11eb-83a1-10c927e52abe.png">

<img width="1083" alt="Screenshot 2021-02-10 at 5 37 19 PM" src="https://user-images.githubusercontent.com/67046386/107508609-4ed24880-6bc7-11eb-924d-882d59e2579c.png">

<details>
<summary>console log</summary>

```
I/ViewRootImpl@246733[FlutterActivity](15627): ViewPostIme pointer 0
I/ViewRootImpl@246733[FlutterActivity](15627): ViewPostIme pointer 1
I/ViewRootImpl@246733[FlutterActivity](15627): ViewPostIme pointer 0
I/ViewRootImpl@246733[FlutterActivity](15627): ViewPostIme pointer 1
I/ViewRootImpl@246733[FlutterActivity](15627): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(15627): prepareNavigationBarInfo() DecorView@2011431[FlutterActivity]
D/InputMethodManager(15627): getNavigationBarColor() -855310
D/InputTransport(15627): Input channel destroyed: 'ClientS', fd=95
I/SurfaceView(15627): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154} of ViewRootImpl@246733[FlutterActivity]
I/SurfaceView(15627): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154}
I/mali_egl(15627): eglDestroySurface() in
I/mali_winsys(15627): delete_surface() [1080x2154] return
I/mali_egl(15627): eglDestroySurface() out
W/libEGL  (15627): EGLNativeWindowType 0x7f1e141010 disconnect failed
I/SurfaceView(15627): remove() io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154} Surface(name=SurfaceView - io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity@b67effa@2)/@0xd6e3b44
D/OpenGLRenderer(15627): makeCurrent EglSurface : 0x7f27c29700 -> 0x0
D/OpenGLRenderer(15627): destroyEglSurface : 0x7f27c29700
I/mali_egl(15627): eglDestroySurface() in
I/mali_winsys(15627): delete_surface() [1080x2280] return
I/mali_egl(15627): eglDestroySurface() out
E/OpenGLRenderer(15627): ReliableSurface: perform returned an error
W/libEGL  (15627): EGLNativeWindowType 0x7f27c1bbd0 disconnect failed
D/OpenGLRenderer(15627): ~ReliableSurface : 0x7f27c1bbc0
I/ViewRootImpl@246733[FlutterActivity](15627): Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)8 dur=5 res=0x5 s={false 0} ch=true
I/ViewRootImpl@246733[FlutterActivity](15627): stopped(true) old=false
I/SurfaceView(15627): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154} of ViewRootImpl@246733[FlutterActivity]
I/SurfaceView(15627): onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154} of ViewRootImpl@246733[FlutterActivity]
I/ViewRootImpl@246733[FlutterActivity](15627): Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)4 dur=5 res=0x1 s={false 0} ch=false
I/ViewRootImpl@246733[FlutterActivity](15627): stopped(false) old=true
I/SurfaceView(15627): windowStopped(false) false io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154} of ViewRootImpl@246733[FlutterActivity]
I/ViewRootImpl@246733[FlutterActivity](15627): stopped(false) old=false
I/SurfaceView(15627): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154} of ViewRootImpl@246733[FlutterActivity]
I/ViewRootImpl@246733[FlutterActivity](15627): Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=6 res=0x7 s={true 545965494272} ch=true
D/OpenGLRenderer(15627): createReliableSurface : 0x7f27c1bbc0(0x7f1e145000)
I/mali_winsys(15627): new_window_surface() [1080x2280] return: 0x3000
D/OpenGLRenderer(15627): eglCreateWindowSurface : 0x7f27c29700
I/SurfaceView(15627): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154}
I/mali_winsys(15627): new_window_surface() [1080x2154] return: 0x3000
I/SurfaceView(15627): surfaceChanged (1080,2154) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154}
D/OpenGLRenderer(15627): makeCurrent EglSurface : 0x0 -> 0x7f27c29700
I/OpenGLRenderer(15627): doUpdatePositionAsync is called and callVoidMethod
I/ViewRootImpl@246733[FlutterActivity](15627): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(15627): prepareNavigationBarInfo() DecorView@2011431[FlutterActivity]
D/InputMethodManager(15627): getNavigationBarColor() -855310
D/InputMethodManager(15627): prepareNavigationBarInfo() DecorView@2011431[FlutterActivity]
D/InputMethodManager(15627): getNavigationBarColor() -855310
V/InputMethodManager(15627): Starting input: tba=io.flutter.plugins.imagepicker.example ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(15627): startInputInner - Id : 0
I/InputMethodManager(15627): startInputInner - mService.startInputOrWindowGainedFocus
I/ViewRootImpl@246733[FlutterActivity](15627): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(15627): prepareNavigationBarInfo() DecorView@2011431[FlutterActivity]
D/InputMethodManager(15627): getNavigationBarColor() -855310
D/InputTransport(15627): Input channel destroyed: 'ClientS', fd=95
I/SurfaceView(15627): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154} of ViewRootImpl@246733[FlutterActivity]
I/SurfaceView(15627): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154}
I/mali_egl(15627): eglDestroySurface() in
I/mali_winsys(15627): delete_surface() [1080x2154] return
I/mali_egl(15627): eglDestroySurface() out
W/libEGL  (15627): EGLNativeWindowType 0x7f2017b010 disconnect failed
I/SurfaceView(15627): remove() io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154} Surface(name=SurfaceView - io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity@b67effa@3)/@0x6312147
D/OpenGLRenderer(15627): makeCurrent EglSurface : 0x7f27c29700 -> 0x0
D/OpenGLRenderer(15627): destroyEglSurface : 0x7f27c29700
I/mali_egl(15627): eglDestroySurface() in
I/mali_winsys(15627): delete_surface() [1080x2280] return
I/mali_egl(15627): eglDestroySurface() out
E/OpenGLRenderer(15627): ReliableSurface: perform returned an error
W/libEGL  (15627): EGLNativeWindowType 0x7f27c1bbd0 disconnect failed
D/OpenGLRenderer(15627): ~ReliableSurface : 0x7f27c1bbc0
I/ViewRootImpl@246733[FlutterActivity](15627): Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)8 dur=4 res=0x5 s={false 0} ch=true
I/ViewRootImpl@246733[FlutterActivity](15627): stopped(true) old=false
I/SurfaceView(15627): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{b67effa V.E...... ........ 0,0-1080,2154} of ViewRootImpl@246733[FlutterActivity]


```

</details>

Also, a recent similar [issue](https://github.com/flutter/flutter/issues/64999) was fixed and merged.

Closing this as not reproducible and fixed with latest plugin version. If anybody disagrees, write in comments and I'll reopen it.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64, locale
    en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

</details>

**Closed by darshankawar** 2021-02-10 12:14 UTC
Labels: p: first party, p: image_picker, platform-android, plugin, severe: crash, severe: regression

**Comment by Kamel38** [comment] 2021-03-13 10:46
For some reason I get the same proble when trying to select that picture : https://imgshare.io/images/2021/03/13/b0g5munvjzp51.png

flutter doctor - v 
<details>
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [version 10.0.19043.867], locale fr-FR)
    • Flutter version 2.0.1 at C:\Users\Kamel\flutter
    • Framework revision c5a4b4029c (9 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Kamel\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Kamel\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.54.2)
    • VS Code at C:\Users\Kamel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • SM G960F (mobile) • 215b1c745c0d7ece • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!
</details>

logs : 

<details>
W/ExifInterface( 1435): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
W/ExifInterface( 1435): java.io.IOException: Invalid byte order: ffff8950
W/ExifInterface( 1435):         at android.media.ExifInterface.readByteOrder(ExifInterface.java:3164)
W/ExifInterface( 1435):         at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2457)
W/ExifInterface( 1435):         at android.media.ExifInterface.getMimeType(ExifInterface.java:2335)
W/ExifInterface( 1435):         at android.media.ExifInterface.loadAttributes(ExifInterface.java:1761)
W/ExifInterface( 1435):         at android.media.ExifInterface.initForFilename(ExifInterface.java:2317)
W/ExifInterface( 1435):         at android.media.ExifInterface.<init>(ExifInterface.java:1392)
W/ExifInterface( 1435):         at com.example.flutternativeimage.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:100)      
W/ExifInterface( 1435):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)     
W/ExifInterface( 1435):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/ExifInterface( 1435):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/ExifInterface( 1435):         at android.os.MessageQueue.nativePollOnce(Native Method)
W/ExifInterface( 1435):         at android.os.MessageQueue.next(MessageQueue.java:336)
W/ExifInterface( 1435):         at android.os.Looper.loop(Looper.java:197)
W/ExifInterface( 1435):         at android.app.ActivityThread.main(ActivityThread.java:8167)
W/ExifInterface( 1435):         at java.lang.reflect.Method.invoke(Native Method)
W/ExifInterface( 1435):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
W/ExifInterface( 1435):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
D/InputMethodManager( 1435): HSIFW - flag : 0
W/ExifInterface( 1435): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
W/ExifInterface( 1435): java.io.IOException: Invalid byte order: ffff8950
W/ExifInterface( 1435):         at android.media.ExifInterface.readByteOrder(ExifInterface.java:3164)
W/ExifInterface( 1435):         at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2457)
W/ExifInterface( 1435):         at android.media.ExifInterface.getMimeType(ExifInterface.java:2335)
W/ExifInterface( 1435):         at android.media.ExifInterface.loadAttributes(ExifInterface.java:1761)
W/ExifInterface( 1435):         at android.media.ExifInterface.initForFilename(ExifInterface.java:2317)
W/ExifInterface( 1435):         at android.media.ExifInterface.<init>(ExifInterface.java:1392)
W/ExifInterface( 1435):         at com.example.flutternativeimage.MethodCallHandlerImpl.copyExif(MethodCallHandlerImpl.java:180)
W/ExifInterface( 1435):         at com.example.flutternativeimage.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:69)       
W/ExifInterface( 1435):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)     
W/ExifInterface( 1435):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/ExifInterface( 1435):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/ExifInterface( 1435):         at android.os.MessageQueue.nativePollOnce(Native Method)
W/ExifInterface( 1435):         at android.os.MessageQueue.next(MessageQueue.java:336)
W/ExifInterface( 1435):         at android.os.Looper.loop(Looper.java:197)
W/ExifInterface( 1435):         at android.app.ActivityThread.main(ActivityThread.java:8167)
W/ExifInterface( 1435):         at java.lang.reflect.Method.invoke(Native Method)
W/ExifInterface( 1435):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
</details>
