### ISSUE TITLE
Documentation: developing-packages

### ISSUE THREAD

**Issue by bsr203** [flutter/flutter#38897] opened 2019-08-20 16:42 UTC
Following the documentation to develop a new plugin

As pet the doc ```The iOS platform code of your plugin is located in Pods/Development Pods/hello/Classes/ in the Project Navigator.```

But as seen in the below image, the `Classes` directory is deep inside a hierarchy not  under `Development Pods/hello`. 

Please update the doc, or is there a way to fix/configure it. Thanks.

<img width="308" alt="Screen Shot 2019-08-20 at 12 37 08 PM" src="https://user-images.githubusercontent.com/1966521/63366408-acc1ff00-c347-11e9-8659-6fe4e0ecc813.png">

**Comment by BondarenkoStas** [comment] 2019-09-04 14:28
Duplicate of #19601

**Closed by BondarenkoStas** 2019-09-04 14:28 UTC
