### ISSUE TITLE
Stepper right overflowd 197 pixels

### ISSUE THREAD

**Issue by saravananmnm** [flutter/flutter#35864] opened 2019-07-10 10:35 UTC
` List<Step> my_steps = [
      new Step(
          title: new Text('First step'),
          content: new Text('this is the  first step.'),
          isActive: (CurrentStep >= 0),
          state: (CurrentStep == 0) ? StepState.complete : StepState.disabled),
      new Step(
        title: new Text('Second step'),
        content: Text('this is the second step'),
        isActive: (CurrentStep >= 0),
        state: (CurrentStep == 1) ? StepState.complete : StepState.disabled,
      ),
      new Step(
        title: new Text('Third step'),
        content: new Text('this is third step'),
        isActive: (CurrentStep >= 0),
        state: (CurrentStep == 2) ? StepState.complete : StepState.disabled,
      ),
      new Step(
        title: new Text('Third step'),
        content: new Text('this is third step'),
        isActive: (CurrentStep >= 0),
        state: (CurrentStep == 3) ? StepState.complete : StepState.disabled,
      ),
      new Step(
        title: new Text('Third step'),
        content: new Text('this is third step'),
        isActive: (CurrentStep >= 0),
        state: (CurrentStep == 4) ? StepState.complete : StepState.disabled,
      ),
    ];
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      appBar: AppBar(
        title: Text('Load Provider'),
        centerTitle: true,
      ),
      body: Container(
        constraints: BoxConstraints.tightFor(height: 200.0),
        child: Stack(
          children: <Widget>[
            Stepper(
                type: StepperType.horizontal,
                currentStep: CurrentStep,
                onStepTapped: (step) {
                  setState(() {
                    CurrentStep = step;
                  });
                },
                steps: my_steps,
                controlsBuilder: (context, {onStepContinue, onStepCancel}) {}),
          ],
        ),
      ),
      bottomNavigationBar: new Container(
        margin: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 4.0),
        color: Colors.blue,
        child: new ConstrainedBox(
          constraints: const BoxConstraints.tightFor(height: 48.0),
          child: new Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              new FlatButton(
                onPressed: () {
                  setState(() {
                    if (CurrentStep > 0) {
                      CurrentStep = CurrentStep - 1;
                    } else {
                      CurrentStep = 0;
                    }
                  });
                },
                textColor: Colors.white,
                textTheme: ButtonTextTheme.normal,
                child: new Row(children: <Widget>[
                  const Icon(Icons.chevron_left),
                  const Text('BACK')
                ]),
              ),
              new FlatButton(
                onPressed: () {
                  setState(() {
                    if (CurrentStep < my_steps.length - 1) {
                      CurrentStep = CurrentStep + 1;
                    } else {
                      CurrentStep = 0;
                    }
                  });
                },
                textColor: Colors.white,
                textTheme: ButtonTextTheme.normal,
                child: new Row(children: const <Widget>[
                  const Text('NEXT'),
                  const Icon(Icons.chevron_right)
                ]),
              )
            ],
          ),
        ),
      ),
![screenshot-2019-07-10_16 06 22 042](https://user-images.githubusercontent.com/23417457/60962800-c295da80-a32c-11e9-81b0-459cc927c529.png)

    );`

**Comment by saravananmnm** [comment] 2019-07-11 12:22
Kindly provide any solution for this.

**Comment by saravananmnm** [comment] 2019-07-12 05:52
could any fixes for that issue.

**Comment by saravananmnm** [comment] 2019-07-22 06:47
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17134.885], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

• No issues found!

**Comment by saravananmnm** [comment] 2019-08-17 04:49
![screenshot-2019-08-17_10 18 01 454](https://user-images.githubusercontent.com/23417457/63206775-62871680-c0d8-11e9-89c5-5f592d7ff1ed.png)

kindly provide any solution

**Comment by AniaBerthelot** [comment] 2019-12-21 14:11
up

**Comment by AniaBerthelot** [comment] 2019-12-21 14:12
@saravananmnm 	did you find any solution for that issue  ?

**Comment by saravananmnm** [comment] 2019-12-22 03:44
Even I didn't get any solution for that issue.

---- AniaBerthelot wrote ----


up

**Comment by AniaBerthelot** [comment] 2019-12-22 17:55
:/

**Comment by TahaTesser** [comment] 2020-05-06 14:11
This issue still exist
Closing as duplicate of [#40601](https://github.com/flutter/flutter/issues/40601) with recent activity

**Closed by TahaTesser** 2020-05-06 14:11 UTC
Labels: f: material design, framework
