### ISSUE TITLE
Flake in `ImageDecoderFixtureTest.ExifDataIsRespectedOnDecode`

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#80582] opened 2021-04-16 16:02 UTC
This happened for the first time here: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8849862738570696432/+/steps/Host_Tests_for_host_release/0/stdout.

Seems like a pretty simple test, unclear why it failed.

**Comment by chinmaygarde** [comment] 2021-04-19 17:49
We saw in the presubmit failure reports as well.

**Comment by chinmaygarde** [comment] 2021-04-26 17:36
I haven't seen this error over the past week. Also, there are no error messages associated with that failure. This should be [fixed now](https://github.com/flutter/engine/commit/71fc4c1dd319d4926b836d0973ef85af4c83ca31).

**Comment by zanderso** [comment] 2021-04-28 19:51
This does come up every so often, see the previous instance here: https://github.com/flutter/flutter/issues/64475.

**Comment by chinmaygarde** [comment] 2021-07-28 21:48
This is a duplicate of https://github.com/flutter/flutter/issues/83141

**Closed by chinmaygarde** 2021-07-28 21:48 UTC
Labels: P4, engine, team: flakes
