### ISSUE TITLE
Framework calling rebuild on when page is navigated out.

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#16117] opened 2018-03-30 22:21 UTC
On Navigating out of a page to the next page I see the build method called on the page going out to view. Is that expected. Here is the code. The app goes from Screen 1--> Screen 2 --> Screen 3.

When I go from Screen 2 to Screen 3 i see the build method of Screen 2 is called. When when I go from Screen 1 to Screen 2 Screen 1 build is not called. I reversed the order and then I see Screen 1 build called when it pushes the next screen on the stack . So basically only the first screen does not show this behavior. All other pushes cause the build method called on the screen being navigated out.

```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() {
  runApp(new MaterialApp(home: new NavigatorSample()));
}


class NavigatorSample extends StatelessWidget {

    static var routes = <String, WidgetBuilder> {
      '/': (BuildContext context) => new Screen2(),
      '/1': (BuildContext context) => new Screen1(),
      '/2': (BuildContext context) => new Screen2(),
      '/3': (BuildContext context) => new Screen3()
    };
    
    static Route<BuildContext> _getRoute(RouteSettings settings) {
      var builder = routes[settings.name];
      if(builder != null) {
          return new MaterialPageRoute(
              settings: settings,
              builder: builder,
          );
      }
      return null;
    }

    Widget build(BuildContext context) {
        var app = new MaterialApp(
          home: new Screen1() ,
          onGenerateRoute: _getRoute,
        );
        
        return app;
    }
}


class Screen1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold( // 1
      appBar: new AppBar(
        title: new Text("Screen 1"), // screen title
      ),
      body: new Center(
        child: new Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[ 
           new RaisedButton(
                onPressed:(){
                  Navigator.of(context).pushNamed("/2");
                },
                child: new Text("Go to Screen 2"),
              
            )
          ]
        )
      )
    );
  }
}

class Screen2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold( // 1
      appBar: new AppBar(
        title: new Text("Screen 2"), // screen title
      ),
      body: new Center(
        child: new Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[ 
           new RaisedButton(
                onPressed:(){
                  Navigator.of(context).pushNamed("/3");
                },
                child: new Text("Go to Screen 3"),
              
            )
          ]
        )
      )
    );
  }
}

class Screen3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold( // 1
      appBar: new AppBar(
        title: new Text("Screen 3"), // screen title
      ),
      body: new Center(
                child: new Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    new Text("Screen 3"),
                  ]
                )
              )
        );
  }
}
```

**Comment by xster** [comment] 2018-03-31 02:17
Similar issue to #14124

**Comment by pulyaevskiy** [comment] 2018-03-31 20:08
It worth noting that if the two routes create AppBar widgets of different brightness this messes up system overlay style and rebuild of previousRoute always overwrites style set by the new route.

Not sure how to workaround this yet.

**Comment by xster** [comment] 2018-04-02 18:29
You can locally fix the issue by applying https://github.com/flutter/flutter/pull/14941 as a workaround. Though the general fix will be done when we resolve https://github.com/flutter/flutter/issues/4630

**Comment by pulyaevskiy** [comment] 2018-04-02 18:41
Thanks! I tried that workaround and found it doesn't cover one edge case when user uses edge swipe to dismiss current route. In this case widget below current route gets rebuilt before it becomes current.

For now I'm just trying to stick to the same brightness in all routes. Subscribed to #4630.

**Comment by brooth** [comment] 2018-04-24 00:35
@xster Thanks for the workaround! This issue really screwed up my whole day.

**Comment by goderbauer** [comment] 2018-12-28 22:01
This seems to be a dupe of https://github.com/flutter/flutter/issues/14124, which has more context.

**Closed by goderbauer** 2018-12-28 22:01 UTC
Labels: f: routes, framework
