### ISSUE TITLE
Google Maps Flutter M1 Chips support

### ISSUE THREAD

**Issue by ujjwalll** [flutter/flutter#125305] opened 2023-04-21 15:22 UTC
Hi all, I am using flutter in my native android and iOS application. I have some maps components in flutter which uses google maps flutter. I noticed that you guys haven't supported this google maps for flutter for M1 arch. Hence not able to test it properly in iOS simulators. Are you guys planning to bump up the version so that it will support M1 arch? 

I am planning to use it in my application very soon. when can I expect proper M1 chip support (arm-64) for google maps flutter?

Please let me know about it. Thanks!

**Comment by stuartmorgan** [comment] 2023-04-21 21:34
Duplicate of https://github.com/flutter/flutter/issues/94491

**Closed by stuartmorgan** 2023-04-21 21:34 UTC
