### ISSUE TITLE
We request the development of google_sign_in for macos.

### ISSUE THREAD

**Issue by TakaTeke** [flutter/flutter#136376] opened 2023-10-11 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to create an application that accesses gmail and imports the email text on macOS.

### Proposal

Hello.
I looked into past articles on this thread, but why can't you create google_sign_in for macos?
I think there is a huge demand for it.
We would appreciate it if you could create a google_sign_in for macos.

Thank you for your understanding.

**Comment by stuartmorgan** [comment] 2023-10-11 17:38
Duplicate of https://github.com/flutter/flutter/issues/46157

**Closed by stuartmorgan** 2023-10-11 17:38 UTC
