### ISSUE TITLE
flutter attach - > NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null. Receiver: null Tried calling: port

### ISSUE THREAD

**Issue by Jentlezhi** [flutter/flutter#31975] opened 2019-05-02 12:41 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by Jentlezhi** [comment] 2019-05-02 13:04
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter attach

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null.
Receiver: null
Tried calling: port

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:219:78)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.5.9-pre.42, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.5.9-pre.42 at /Users/Jentle/flutter
    [32m•[39m Framework revision cbfa4e5483 (5 days ago), 2019-04-26 20:25:02 -0700
    [32m•[39m Engine revision 7f753f8f52
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.3 c46deebfb6)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/Jentle/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[33m[!][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [31m✗[39m Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.7.0.beta.3

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 35.1.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.33.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.25.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xʀ • 61F35846-7EF9-4CE8-B72E-E5B545E7EDFC • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2
      (simulator)

[33m![39m Doctor found issues in 1 category.
```

**Comment by gscool** [comment] 2019-05-10 07:46
I have the same question

**Comment by lvpengwei** [comment] 2019-05-13 06:08
I have the same question

**Comment by AlexKel** [comment] 2019-05-13 10:59
I have the same issue

## command

flutter attach -d 4A7E74AA-D187-40C1-8623-11F17BCE0579

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null.
Receiver: null
Tried calling: port

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:219:78)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```sh
[32m[✓][39m Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-GB)
    [32m•[39m Flutter version 1.5.8 at /Users/aleksandrkelbas/flutter
    [32m•[39m Framework revision 0ba67226ee (3 weeks ago), 2019-04-24 17:18:28 -0700
    [32m•[39m Engine revision c63d1cf9c9
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/aleksandrkelbas/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/aleksandrkelbas/Library/Android
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.6.1

[33m[!][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m VS Code (version 1.33.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.0.1

[32m[✓][39m Connected device (2 available)
    [32m•[39m Alex’s iPhone • ffed4855585ed787031edb1862d82d3236d6a429 • ios • iOS 12.2
    [32m•[39m iPhone Xʀ     • 4A7E74AA-D187-40C1-8623-11F17BCE0579     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

[33m![39m Doctor found issues in 1 category.
```

**Comment by AlexKel** [comment] 2019-05-14 14:58
Switching to master branch doesn't help. I get another error when refreshing there: `Error 105 received from application: Isolate must be runnable`

**Comment by CoderWeiXiao** [comment] 2019-06-11 02:51
I have the same issues

**Comment by IphoneCoder** [comment] 2019-06-27 03:53
I have the same issues

**Comment by damoncoo** [comment] 2019-07-06 07:20
I have the same issue

**Comment by fuiyu** [comment] 2019-07-30 09:46
I have the same issue

**Comment by BondarenkoStas** [comment] 2019-10-15 13:29
Duplicate of #40225. The issue should have been fixed in https://github.com/flutter/flutter/pull/32126 in 1.6.0. 
Please report if you encounter it still.

**Closed by BondarenkoStas** 2019-10-15 13:29 UTC
