### ISSUE TITLE
Camera exception : Previous capture has not returned yet - On Android Emulator

### ISSUE THREAD

**Issue by nehemiekoffi** [flutter/flutter#114152] opened 2022-10-27 13:03 UTC
## Steps to Reproduce

I have implemented Camera plugin, I get on exception when I call controller!.takePicture() on Android Emulators (API26 to API33).
But It works well on real device and on Android Emulator API22

1. Install camera package [0.10.0+4](https://pub.dev/packages/camera/versions/0.10.0+4)
2. Implement the camera sreen
3. Capture picture via `await controller!.takePicture();`

**Expected results:** 
Get the Xfile captured

**Actual results:** 

`CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)
`
<details>
<summary>Code sample</summary>

```dart
  void _onCapturePressed() async {
    if (controller != null) {
      try {
        final XFile capturedFile = await controller!.takePicture();
      } catch (e) {
        print(e);
      }
    }
  }
```

</details>

<details>
  <summary>Logs</summary>

```
D/CameraCaptureCallback( 5285): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 2
D/CameraCaptureCallback( 5285): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
I/Camera  ( 5285): unlockAutoFocus
I/Camera  ( 5285): open | onError
I/Camera  ( 5285): close
I/Camera  ( 5285): closeCaptureSession
E/CameraCaptureSession( 5285): Session 0: Exception while stopping repeating:
E/CameraCaptureSession( 5285): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession( 5285): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2185)
E/CameraCaptureSession( 5285): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:988)
E/CameraCaptureSession( 5285): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:390)
E/CameraCaptureSession( 5285): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1057)
E/CameraCaptureSession( 5285): 	at io.flutter.plugins.camera.Camera.close(Camera.java:1064)
E/CameraCaptureSession( 5285): 	at io.flutter.plugins.camera.Camera$1.onError(Camera.java:288)
E/CameraCaptureSession( 5285): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks$1.run(CameraDeviceImpl.java:1756)
E/CameraCaptureSession( 5285): 	at android.os.Handler.handleCallback(Handler.java:789)
E/CameraCaptureSession( 5285): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/CameraCaptureSession( 5285): 	at android.os.Looper.loop(Looper.java:164)
E/CameraCaptureSession( 5285): 	at android.os.HandlerThread.run(HandlerThread.java:65)
D/        ( 5285): HostConnection::get() New Host Connection established 0x71e244bfe0, tid 5397
6
I/flutter ( 5285): CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)
Application finished.
```

```
```

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale fr-CI)
    • Flutter version 3.3.2 on channel stable at /Users/nehemie/Documents/Dev/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nehemie/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)          • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • Android SDK built for arm64 (mobile) • emulator-5556 • android-arm64  • Android 8.0.0 (API 26) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by exaby73** [comment] 2022-10-27 15:14
Hello @nehemiekoffi. Can you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by huycozy** [comment] 2022-11-03 04:09
Duplicate of #114029

**Comment by exaby73** [comment] 2022-11-03 06:50
Thanks @huycozy for catching this duplicate. Closing the issue for the same reason.

**Closed by exaby73** 2022-11-03 06:50 UTC
Labels: waiting for customer response, in triage
