### ISSUE TITLE
When the TextField focus, keyboard appear and then exit app, The app will Crash

### ISSUE THREAD

**Issue by yk3372** [flutter/flutter#29508] opened 2019-03-17 11:50 UTC
## Reproduce
Write a Flutter app with TextField widget, click the TextField and the keyboard will appear,
then press Android's back, The App will crash.

## The crash log:
```
java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
 at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:553)
 at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:477)
 at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
 at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:163)
 at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
 at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:71)
 at io.flutter.embedding.engine.systemchannels.TextInputChannel.updateEditingState(TextInputChannel.java:117)
 at io.flutter.plugin.editing.InputConnectionAdaptor.updateEditingState(InputConnectionAdaptor.java:61)
 at io.flutter.plugin.editing.InputConnectionAdaptor.endBatchEdit(InputConnectionAdaptor.java:86)
 at android.view.inputmethod.BaseInputConnection.finishComposingText(BaseInputConnection.java:442)
 at android.view.inputmethod.BaseInputConnection.closeConnection(BaseInputConnection.java:161)
 at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:541)
 at com.android.internal.view.IInputConnectionWrapper.dispatchMessage(IInputConnectionWrapper.java:225)
 at com.android.internal.view.IInputConnectionWrapper.closeConnection(IInputConnectionWrapper.java:211)
 at android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper.deactivate(InputMethodManager.java:588)
 at android.view.inputmethod.InputMethodManager.clearConnectionLocked(InputMethodManager.java:917)
 at android.view.inputmethod.InputMethodManager.finishInputLocked(InputMethodManager.java:939)
 at android.view.inputmethod.InputMethodManager.windowDismissed(InputMethodManager.java:1405)
 at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:499)
 at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:440)
 at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:126)
 at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4557)
 at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6806)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

## flutter doctor -v
```
[✓] Flutter (Channel master, v1.3.11-pre.34, on Mac OS X 10.14.2 18C54, locale en-CN)
    • Flutter version 1.3.11-pre.34 at /Applications/flutter
    • Framework revision 0bf0f5c1da (30 hours ago), 2019-03-15 22:03:13 -0700
    • Engine revision 015c0246ae
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Applications/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Applications/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[✓] Connected device (1 available)
    • MIX 3 • 902cef95 • android-arm64 • Android 9 (API 28)

• No issues found!

```

## The Test Code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() =>runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
//      theme: ThemeData(primaryColor: Colors.white),
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: LoginState(),
      backgroundColor: Colors.white,
    );
  }
}

class LoginState extends StatefulWidget {
  @override
  _LoginStateState createState() => _LoginStateState();
}

class _LoginStateState extends State<LoginState> {
  TextEditingController nameController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    var loginNameView = Stack(
      alignment: Alignment.bottomLeft,
      children: <Widget>[
        Padding(
          child: Text('Account', style: TextStyle(color: Colors.black, fontSize: 16)),
          padding: EdgeInsets.only(bottom: 10),
        ),
        TextField(
          decoration: InputDecoration(
              fillColor: Color(0xffbebebe),
              hintStyle: TextStyle(fontSize: 15),
              hintText: 'input',
              contentPadding: EdgeInsets.only(left: 75, top: 10, bottom: 10, right: 10)),
          maxLines: 1,
          textInputAction: TextInputAction.next,
          controller: nameController,
          style: TextStyle(
            color: Colors.black,
            fontSize: 19,
          ),
        )
      ],
    );

    var loginContainer = Container(
      child: Column(
        children: <Widget>[
          loginNameView,
        ],
      ),
      margin: EdgeInsets.only(top: 56, left: 17, right: 17),
    );


    return Container(
      child: loginContainer,
    );
  }
}
```

**Comment by jonahwilliams** [comment] 2019-03-18 04:51
This looks like https://github.com/flutter/flutter/issues/28651, but the version is from after when that fix landed.  cc @matthew-carroll

**Comment by matthew-carroll** [comment] 2019-03-18 05:27
I'll take a look at it.  This issue is happening on a platform message "send" rather than a callback.  I'll see if I can reproduce it.

**Comment by matthew-carroll** [comment] 2019-03-18 19:09
@yk3372 can you please let me know what type of device you're testing with, and which version of Android you're running on that device?

**Comment by matthew-carroll** [comment] 2019-03-18 19:28
I was unable to reproduce this issue on a Pixel 2 emulator, Nexus 5x emulator, or Nexus emulator.  In each of these cases the "back" button turned into a "down" button and closed the keyboard as expected.

I was also unable to reproduce this issue on a Samsung Galaxy J7 running Android 7.0.  In this case there was a physical back button.  Upon pressing the back button, the keyboard disappeared as expected.

@yk3372 do you have any additional repro information that might help?

**Comment by yk3372** [comment] 2019-03-19 00:47
@matthew- carroll hi， My Android device is XIAOMI MIX3, Android 9.0, MIUI 10.
I use the flutter on master branch.
 
MIX 3 • 902cef95 • android-arm64 • Android 9 (API 28)

**Comment by yk3372** [comment] 2019-03-19 00:55
My reproduce step:
1. run the code.
2. click the textfield, then the key board appear.
3. press the back
4. the key board disappear
5. press the back
6. the app exit and then the app crash

**Comment by matthew-carroll** [comment] 2019-03-19 18:59
@yk3372 - Unfortunately, I'm still unable to reproduce.  When I press "back" the first time, the keyboard closes.  When I press "back" a second time, the app exits.  But I don't see any crash in my logs.

Have you made any other alterations to your app at all that might explain this issue?  Can you try to reproduce in an emulator, or maybe on a Pixel, Pixel 2, or Samsung?

**Comment by rafaelrgi** [comment] 2019-04-03 12:28
Hi,
I have the same issue running my code in an Android 6 emulator (it doesn't happen on my Android 8 device).
 
It just happens if the keyboard was shown before close the app.

```
java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
  at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:514)
  at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:444)
  at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
  at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:163)
  at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
  at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:71)
  at io.flutter.embedding.engine.systemchannels.TextInputChannel.updateEditingState(TextInputChannel.java:117)
  at io.flutter.plugin.editing.InputConnectionAdaptor.updateEditingState(InputConnectionAdaptor.java:61)
  at io.flutter.plugin.editing.InputConnectionAdaptor.endBatchEdit(InputConnectionAdaptor.java:86)
  at android.view.inputmethod.BaseInputConnection.finishComposingText(BaseInputConnection.java:275)
  at android.view.inputmethod.InputMethodManager.reportFinishInputConnection(InputMethodManager.java:852)
  at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3439)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by matthew-carroll** [comment] 2019-04-05 00:30
@rafaelrgi would you mind providing a minimal source code example that reproduces the issue?

**Comment by rafaelrgi** [comment] 2019-04-05 15:47
> @rafaelrgi would you mind providing a minimal source code example that reproduces the issue?

Sure, here it is:

`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: TextFormField(autofocus: true,),
    );
  }
}
`

**Comment by matthew-carroll** [comment] 2019-04-09 00:34
@rafaelrgi I created an Android 6 emulator and tried your code, but opening the keyboard and pressing back twice does not cause a crash for me.

Does this issue still happen for you on the latest `master` commit?

**Comment by rafaelrgi** [comment] 2019-04-09 12:44
Oh, my mistake, I was on the `beta channel`.

Master channel: the issue doesn't happen
Stable channel: the issue doesn't happen

**Comment by yk3372** [comment] 2019-04-10 01:42
I find the latest master branch can not reproduce the issue on my MIX3

**Closed** 2019-04-10 01:47 UTC
Labels: severe: crash, ▣ platform-android

**Comment by najeira** [comment] 2019-04-12 01:09
I also face this exception with v1.3.8. Does anyone know which commit fixed this? I want to pick it.
