### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by SukumarRaja** [flutter/flutter#120439] opened 2023-02-10 13:55 UTC
## Command
```
flutter --no-color run --machine --device-id=192.168.1.8:5555 --profile --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:133:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:54:22)
<asynchronous suspension>
#3      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:266:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19045.2486], locale en-IN)
    • Flutter version 3.3.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (6 months ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.22)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33130.400
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.0)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • POCO X2 (mobile)  • 192.168.1.8:5555 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.2486]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 109.0.1518.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 676cefaaff197f27424942307668886253e1ec35
### Plugins
app_links-2.2.2
app_links_web-0.2.0
audio_service-0.18.8
audio_service_web-0.1.1
audio_session-0.1.10
audiotagger-2.2.1
file_picker-5.2.4
flutter_archive-5.0.0
flutter_displaymode-0.5.0
flutter_plugin_android_lifecycle-2.0.7
just_audio-0.9.30
just_audio_web-0.4.7
msix-3.7.0
on_audio_query-2.6.1
on_audio_query_web-1.3.2+2
package_info_plus-3.0.2
path_provider-2.0.11
path_provider_android-2.0.21
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
receive_sharing_intent-1.4.5
share_plus-6.3.0
sqflite-2.2.0+3
url_launcher-6.1.7
url_launcher_android-6.0.21
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1

**Comment by huycozy** [comment] 2023-02-13 04:11
Closing as duplicate of #118400 which has the same crash log. May be also related: #108812.

**Closed by huycozy** 2023-02-13 04:11 UTC
Labels: in triage
