### ISSUE TITLE
Flutter doctor check crashes with Visual Studio 

### ISSUE THREAD

**Issue by ThisBebson** [flutter/flutter#103622] opened 2022-05-12 14:00 UTC
Hi.
While running flutter doctor I get the following output:

Microsoft Windows [Version 10.0.19044.1288]
(c) Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Users\Kamil>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1288], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: [
        {
          "instanceId": "514fab05",
          "installDate": "2022-05-12T13:33:31Z",
          "installationName": "VisualStudio/17.2.0+32505.173",
          "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
          "installationVersion": "17.2.32505.173",
          "productId": "Microsoft.VisualStudio.Product.Community",
          "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
          "state": 4294967295,
          "isComplete": true,
          "isLaunchable": true,
          "isPrerelease": false,
          "isRebootRequired": false,
          "displayName": "Visual Studio Community 2022",
          "description": "Zaawansowane �rodowisko IDE - bezp�atne dla uczni�w i student�w, wsp��autor�w oprogramowania
          open source oraz indywidualnych os�b",
          "channelId": "VisualStudio.17.Release",
          "channelUri": "https://aka.ms/vs/17/release/channel",
          "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
          Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
          "installedChannelUri": "https://aka.ms/vs/17/release/channel",
          "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.2#17.2.0",
          "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
          "updateDate": "2022-05-12T13:33:31.5316882Z",
          "catalog": {
            "buildBranch": "d17.2",
            "buildVersion": "17.2.32505.173",
            "id": "VisualStudio/17.2.0+32505.173",
            "localBuild": "build-lab",
            "manifestName": "VisualStudio",
            "manifestType": "installer",
            "productDisplayVersion": "17.2.0",
            "productLine": "Dev17",
            "productLineVersion": "2022",
            "productMilestone": "RTW",
            "productMilestoneIsPreRelease": "False",
            "productName": "Visual Studio",
            "productPatchVersion": "0",
            "productPreReleaseMilestoneSuffix": "7.0",
            "productSemanticVersion": "17.2.0+32505.173",
            "requiredEngineVersion": "3.2.2146.50370"
          },
          "properties": {
            "campaignId": "2030:73b9fccf-217a-44ac-9ccd-1fa916766e11",
            "channelManifestId": "VisualStudio.17.Release/17.2.0+32505.173",
            "nickname": "",
            "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
          }
        }
      ]
      . The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when
      this happened:
      https://github.com/flutter/flutter/issues/new/choose
      The source bytes were:
      [91, 13, 10, 32, 32, 123, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 110, 99, 101, 73, 100, 34, 58, 32,
      34, 53, 49, 52, 102, 97, 98, 48, 53, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 68, 97,
      116, 101, 34, 58, 32, 34, 50, 48, 50, 50, 45, 48, 53, 45, 49, 50, 84, 49, 51, 58, 51, 51, 58, 51, 49, 90, 34, 44,
      13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 78, 97, 109, 101, 34, 58,
      32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 47, 49, 55, 46, 50, 46, 48, 43, 51, 50, 53, 48,
      53, 46, 49, 55, 51, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110,
      80, 97, 116, 104, 34, 58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 92,
      92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111,
      92, 92, 50, 48, 50, 50, 92, 92, 67, 111, 109, 109, 117, 110, 105, 116, 121, 34, 44, 13, 10, 32, 32, 32, 32, 34,
      105, 110, 115, 116, 97, 108, 108, 97, 116, 105, 111, 110, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49,
      55, 46, 50, 46, 51, 50, 53, 48, 53, 46, 49, 55, 51, 34, 44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117,
      99, 116, 73, 100, 34, 58, 32, 34, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 86, 105, 115, 117, 97, 108, 83,
      116, 117, 100, 105, 111, 46, 80, 114, 111, 100, 117, 99, 116, 46, 67, 111, 109, 109, 117, 110, 105, 116, 121, 34,
      44, 13, 10, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 80, 97, 116, 104, 34, 58, 32, 34, 67, 58, 92,
      92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102,
      116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92, 92, 50, 48, 50, 50, 92, 92, 67, 111,
      109, 109, 117, 110, 105, 116, 121, 92, 92, 67, 111, 109, 109, 111, 110, 55, 92, 92, 73, 68, 69, 92, 92, 100, 101,
      118, 101, 110, 118, 46, 101, 120, 101, 34, 44, 13, 10, 32, 32, 32, 32, 34, 115, 116, 97, 116, 101, 34, 58, 32, 52,
      50, 57, 52, 57, 54, 55, 50, 57, 53, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115, 67, 111, 109, 112, 108, 101, 116,
      101, 34, 58, 32, 116, 114, 117, 101, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115, 76, 97, 117, 110, 99, 104, 97, 98,
      108, 101, 34, 58, 32, 116, 114, 117, 101, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115, 80, 114, 101, 114, 101, 108,
      101, 97, 115, 101, 34, 58, 32, 102, 97, 108, 115, 101, 44, 13, 10, 32, 32, 32, 32, 34, 105, 115, 82, 101, 98, 111,
      111, 116, 82, 101, 113, 117, 105, 114, 101, 100, 34, 58, 32, 102, 97, 108, 115, 101, 44, 13, 10, 32, 32, 32, 32,
      34, 100, 105, 115, 112, 108, 97, 121, 78, 97, 109, 101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 32, 83, 116,
      117, 100, 105, 111, 32, 67, 111, 109, 109, 117, 110, 105, 116, 121, 32, 50, 48, 50, 50, 34, 44, 13, 10, 32, 32,
      32, 32, 34, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 34, 58, 32, 34, 90, 97, 97, 119, 97, 110, 115,
      111, 119, 97, 110, 101, 32, 152, 114, 111, 100, 111, 119, 105, 115, 107, 111, 32, 73, 68, 69, 32, 45, 32, 98, 101,
      122, 112, 136, 97, 116, 110, 101, 32, 100, 108, 97, 32, 117, 99, 122, 110, 105, 162, 119, 32, 105, 32, 115, 116,
      117, 100, 101, 110, 116, 162, 119, 44, 32, 119, 115, 112, 162, 136, 97, 117, 116, 111, 114, 162, 119, 32, 111,
      112, 114, 111, 103, 114, 97, 109, 111, 119, 97, 110, 105, 97, 32, 111, 112, 101, 110, 32, 115, 111, 117, 114, 99,
      101, 32, 111, 114, 97, 122, 32, 105, 110, 100, 121, 119, 105, 100, 117, 97, 108, 110, 121, 99, 104, 32, 111, 115,
      162, 98, 34, 44, 13, 10, 32, 32, 32, 32, 34, 99, 104, 97, 110, 110, 101, 108, 73, 100, 34, 58, 32, 34, 86, 105,
      115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 49, 55, 46, 82, 101, 108, 101, 97, 115, 101, 34, 44, 13, 10,
      32, 32, 32, 32, 34, 99, 104, 97, 110, 110, 101, 108, 85, 114, 105, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58,
      47, 47, 97, 107, 97, 46, 109, 115, 47, 118, 115, 47, 49, 55, 47, 114, 101, 108, 101, 97, 115, 101, 47, 99, 104,
      97, 110, 110, 101, 108, 34, 44, 13, 10, 32, 32, 32, 32, 34, 101, 110, 103, 105, 110, 101, 80, 97, 116, 104, 34,
      58, 32, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 32, 40, 120, 56, 54, 41,
      92, 92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105,
      111, 92, 92, 73, 110, 115, 116, 97, 108, 108, 101, 114, 92, 92, 114, 101, 115, 111, 117, 114, 99, 101, 115, 92,
      92, 97, 112, 112, 92, 92, 83, 101, 114, 118, 105, 99, 101, 72, 117, 98, 92, 92, 83, 101, 114, 118, 105, 99, 101,
      115, 92, 92, 77, 105, 99, 114, 111, 115, 111, 102, 116, 46, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105,
      111, 46, 83, 101, 116, 117, 112, 46, 83, 101, 114, 118, 105, 99, 101, 34, 44, 13, 10, 32, 32, 32, 32, 34, 105,
      110, 115, 116, 97, 108, 108, 101, 100, 67, 104, 97, 110, 110, 101, 108, 85, 114, 105, 34, 58, 32, 34, 104, 116,
      116, 112, 115, 58, 47, 47, 97, 107, 97, 46, 109, 115, 47, 118, 115, 47, 49, 55, 47, 114, 101, 108, 101, 97, 115,
      101, 47, 99, 104, 97, 110, 110, 101, 108, 34, 44, 13, 10, 32, 32, 32, 32, 34, 114, 101, 108, 101, 97, 115, 101,
      78, 111, 116, 101, 115, 34, 58, 32, 34, 104, 116, 116, 112, 115, 58, 47, 47, 100, 111, 99, 115, 46, 109, 105, 99,
      114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 101, 110, 45, 117, 115, 47, 118, 105, 115, 117, 97, 108, 115,
      116, 117, 100, 105, 111, 47, 114, 101, 108, 101, 97, 115, 101, 115, 47, 50, 48, 50, 50, 47, 114, 101, 108, 101,
      97, 115, 101, 45, 110, 111, 116, 101, 115, 45, 118, 49, 55, 46, 50, 35, 49, 55, 46, 50, 46, 48, 34, 44, 13, 10,
      32, 32, 32, 32, 34, 116, 104, 105, 114, 100, 80, 97, 114, 116, 121, 78, 111, 116, 105, 99, 101, 115, 34, 58, 32,
      34, 104, 116, 116, 112, 115, 58, 47, 47, 103, 111, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111,
      109, 47, 102, 119, 108, 105, 110, 107, 47, 63, 76, 105, 110, 107, 73, 100, 61, 54, 54, 49, 50, 56, 56, 34, 44, 13,
      10, 32, 32, 32, 32, 34, 117, 112, 100, 97, 116, 101, 68, 97, 116, 101, 34, 58, 32, 34, 50, 48, 50, 50, 45, 48, 53,
      45, 49, 50, 84, 49, 51, 58, 51, 51, 58, 51, 49, 46, 53, 51, 49, 54, 56, 56, 50, 90, 34, 44, 13, 10, 32, 32, 32,
      32, 34, 99, 97, 116, 97, 108, 111, 103, 34, 58, 32, 123, 13, 10, 32, 32, 32, 32, 32, 32, 34, 98, 117, 105, 108,
      100, 66, 114, 97, 110, 99, 104, 34, 58, 32, 34, 100, 49, 55, 46, 50, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34,
      98, 117, 105, 108, 100, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 55, 46, 50, 46, 51, 50, 53, 48, 53,
      46, 49, 55, 51, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 105, 100, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108,
      83, 116, 117, 100, 105, 111, 47, 49, 55, 46, 50, 46, 48, 43, 51, 50, 53, 48, 53, 46, 49, 55, 51, 34, 44, 13, 10,
      32, 32, 32, 32, 32, 32, 34, 108, 111, 99, 97, 108, 66, 117, 105, 108, 100, 34, 58, 32, 34, 98, 117, 105, 108, 100,
      45, 108, 97, 98, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 109, 97, 110, 105, 102, 101, 115, 116, 78, 97, 109,
      101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 34, 44, 13, 10, 32, 32, 32, 32, 32,
      32, 34, 109, 97, 110, 105, 102, 101, 115, 116, 84, 121, 112, 101, 34, 58, 32, 34, 105, 110, 115, 116, 97, 108,
      108, 101, 114, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 68, 105, 115, 112,
      108, 97, 121, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 49, 55, 46, 50, 46, 48, 34, 44, 13, 10, 32, 32,
      32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 76, 105, 110, 101, 34, 58, 32, 34, 68, 101, 118, 49, 55, 34,
      44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 76, 105, 110, 101, 86, 101, 114, 115,
      105, 111, 110, 34, 58, 32, 34, 50, 48, 50, 50, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100,
      117, 99, 116, 77, 105, 108, 101, 115, 116, 111, 110, 101, 34, 58, 32, 34, 82, 84, 87, 34, 44, 13, 10, 32, 32, 32,
      32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 77, 105, 108, 101, 115, 116, 111, 110, 101, 73, 115, 80, 114,
      101, 82, 101, 108, 101, 97, 115, 101, 34, 58, 32, 34, 70, 97, 108, 115, 101, 34, 44, 13, 10, 32, 32, 32, 32, 32,
      32, 34, 112, 114, 111, 100, 117, 99, 116, 78, 97, 109, 101, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 32, 83,
      116, 117, 100, 105, 111, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 112, 114, 111, 100, 117, 99, 116, 80, 97,
      116, 99, 104, 86, 101, 114, 115, 105, 111, 110, 34, 58, 32, 34, 48, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34,
      112, 114, 111, 100, 117, 99, 116, 80, 114, 101, 82, 101, 108, 101, 97, 115, 101, 77, 105, 108, 101, 115, 116, 111,
      110, 101, 83, 117, 102, 102, 105, 120, 34, 58, 32, 34, 55, 46, 48, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34,
      112, 114, 111, 100, 117, 99, 116, 83, 101, 109, 97, 110, 116, 105, 99, 86, 101, 114, 115, 105, 111, 110, 34, 58,
      32, 34, 49, 55, 46, 50, 46, 48, 43, 51, 50, 53, 48, 53, 46, 49, 55, 51, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32,
      34, 114, 101, 113, 117, 105, 114, 101, 100, 69, 110, 103, 105, 110, 101, 86, 101, 114, 115, 105, 111, 110, 34, 58,
      32, 34, 51, 46, 50, 46, 50, 49, 52, 54, 46, 53, 48, 51, 55, 48, 34, 13, 10, 32, 32, 32, 32, 125, 44, 13, 10, 32,
      32, 32, 32, 34, 112, 114, 111, 112, 101, 114, 116, 105, 101, 115, 34, 58, 32, 123, 13, 10, 32, 32, 32, 32, 32, 32,
      34, 99, 97, 109, 112, 97, 105, 103, 110, 73, 100, 34, 58, 32, 34, 50, 48, 51, 48, 58, 55, 51, 98, 57, 102, 99, 99,
      102, 45, 50, 49, 55, 97, 45, 52, 52, 97, 99, 45, 57, 99, 99, 100, 45, 49, 102, 97, 57, 49, 54, 55, 54, 54, 101,
      49, 49, 34, 44, 13, 10, 32, 32, 32, 32, 32, 32, 34, 99, 104, 97, 110, 110, 101, 108, 77, 97, 110, 105, 102, 101,
      115, 116, 73, 100, 34, 58, 32, 34, 86, 105, 115, 117, 97, 108, 83, 116, 117, 100, 105, 111, 46, 49, 55, 46, 82,
      101, 108, 101, 97, 115, 101, 47, 49, 55, 46, 50, 46, 48, 43, 51, 50, 53, 48, 53, 46, 49, 55, 51, 34, 44, 13, 10,
      32, 32, 32, 32, 32, 32, 34, 110, 105, 99, 107, 110, 97, 109, 101, 34, 58, 32, 34, 34, 44, 13, 10, 32, 32, 32, 32,
      32, 32, 34, 115, 101, 116, 117, 112, 69, 110, 103, 105, 110, 101, 70, 105, 108, 101, 80, 97, 116, 104, 34, 58, 32,
      34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 70, 105, 108, 101, 115, 32, 40, 120, 56, 54, 41, 92, 92,
      77, 105, 99, 114, 111, 115, 111, 102, 116, 32, 86, 105, 115, 117, 97, 108, 32, 83, 116, 117, 100, 105, 111, 92,
      92, 73, 110, 115, 116, 97, 108, 108, 101, 114, 92, 92, 115, 101, 116, 117, 112, 46, 101, 120, 101, 34, 13, 10, 32,
      32, 32, 32, 125, 13, 10, 32, 32, 125, 13, 10, 93, 13, 10]

[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

I've honestly no clue why it's crashing >:|

**Comment by fkbeys** [comment] 2022-05-12 16:07
i have same issue too

**Comment by TrebuchKill** [comment] 2022-05-12 16:53
Had/have this issue too. Seems vswhere provided by the Visual Studio Installer is outdated (there was a bug with the -utf8, see https://github.com/microsoft/vswhere/issues/262).
I replaced the provided vswhere.exe inside the visual studio installer with version 3.0.2 (https://github.com/microsoft/vswhere/releases/tag/3.0.2) and it works now.

**Comment by Dancovich** [comment] 2022-05-12 19:03
> Had/have this issue too. Seems vswhere provided by the Visual Studio Installer is outdated (there was a bug with the "-utf8" switch, see [microsoft/vswhere#262](https://github.com/microsoft/vswhere/issues/262)). I replaced the provided vswhere.exe inside the visual studio installer with version 3.0.2 (https://github.com/microsoft/vswhere/releases/tag/3.0.2) and it works now.

Can confirm this works for me. Does someone know if the VS team will ever deploy an update? I just installed VS 2022 and Visual Studio Installer yet the vswhere executable is still out of date.

**Comment by berkhanozkan** [comment] 2022-05-12 20:21
Thanks @TrebuchKill . It works.

**Comment by No898** [comment] 2022-05-12 23:04
I had same problem, @TrebuchKill  helps works. Thank you mate.

**Comment by gezamboni** [comment] 2022-05-13 03:11
> 

Sorry, can you explain me how do I change the vswhere.exe inside the visual studio installer with version 3.0.2

**Comment by CodeDoctorDE** [comment] 2022-05-13 05:28
This is the same issue reported in https://github.com/flutter/flutter/issues/102451

**Comment by darshankawar** [comment] 2022-05-13 07:20
Closing this as duplicate of https://github.com/flutter/flutter/issues/102451. Please follow-up in it for further updates.

**Closed by darshankawar** 2022-05-13 07:20 UTC
Labels: in triage

**Comment by Eider12** [comment] 2022-05-13 15:42
> > 
> 
> Lo siento, ¿puede explicarme cómo cambio vswhere.exe dentro del instalador de Visual Studio con la versión 3.0.2?

quitar 'vswhere.exe' de esta ubicación 'ProgramFiles(x86)%\Microsoft Visual Studio\Installer', reemplazar con este 'https://github.com/microsoft/vswhere/releases/tag/3.0.2

**Comment by Temirlan2022** [comment] 2022-05-13 16:08
> Была/есть эта проблема тоже. Кажется, vswhere, предоставленный установщиком Visual Studio, устарел (была ошибка с переключателем «-utf8», см. [microsoft/vswhere#262](https://github.com/microsoft/vswhere/issues/262) ). Я заменил предоставленный vswhere.exe внутри установщика Visual Studio на версию 3.0.2 ( https://github.com/microsoft/vswhere/releases/tag/3.0.2 ), и теперь он работает.

sorry, but I didn't understand where to find this 'vswhere.exe' and replace it. I have been trying to solve this problem for half a day now. Please explain

**Comment by Temirlan2022** [comment] 2022-05-13 16:09
> 

sorry, but I didn't understand where to find this 'vswhere.exe' and replace it. I have been trying to solve this problem for half a day now. Please explain

**Comment by CodeDoctorDE** [comment] 2022-05-13 16:10
> > 
> 
> sorry, but I didn't understand where to find this 'vswhere.exe' and replace it. I have been trying to solve this problem for half a day now. Please explain

Look here https://github.com/flutter/flutter/issues/102451#issuecomment-1124651845

**Comment by Temirlan2022** [comment] 2022-05-14 05:55
> > > 
> > 
> > 
> > sorry, but I didn't understand where to find this 'vswhere.exe' and replace it. I have been trying to solve this problem for half a day now. Please explain
> 
> Look here [#102451 (comment)](https://github.com/flutter/flutter/issues/102451#issuecomment-1124651845)

Thank you helped

**Comment by IgorBraga21** [comment] 2022-05-21 15:33
> Had/have this issue too. Seems vswhere provided by the Visual Studio Installer is outdated (there was a bug with the "-utf8" switch, see [microsoft/vswhere#262](https://github.com/microsoft/vswhere/issues/262)). I replaced the provided vswhere.exe inside the visual studio installer with version 3.0.2 (https://github.com/microsoft/vswhere/releases/tag/3.0.2) and it works now.

Thank you very much, it worked

**Comment by valdemirc** [comment] 2022-05-30 17:40
Thank you helped
