### ISSUE TITLE
Add-to-app Option-B for Android does not document build modes usage

### ISSUE THREAD

**Issue by abhaysood** [flutter/flutter#79939] opened 2021-04-07 10:58 UTC
I am integrating Flutter in an existing Android application using [Option B](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-b---depend-on-the-modules-source-code)

I am not able to find a way to change the build modes for Flutter (Debug, Profile, Release) using this approach. How to do so and can this be added to the documentation?

**Comment by TahaTesser** [comment] 2021-04-07 12:35
Hi @abhaysood 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/75775
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-07 12:35 UTC
Labels: in triage

**Comment by abhaysood** [comment] 2021-04-09 08:04
@TahaTesser The workaround mentioned in #75775 would work out. But I'd like to discuss the possibility of having a simpler way of doing so via command line flags or by providing a configuration file. 

It would be great if this is supported without modifying the existing build types of the host application.
