### ISSUE TITLE
ProcessException: Failed to find "cmake" in the search path. Command: cmake 

### ISSUE THREAD

**Issue by sherbertowo** [flutter/flutter#95794] opened 2021-12-25 05:42 UTC
I get the error while trying to use command `flutter run`
`ProcessException: Failed to find "cmake" in the search path. Command: cmake` 

heres the verbose ooutput:
```
[  +49 ms] executing: uname -m
[  +21 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +5 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8f1f9c10f04b8f106d78275e93ceead8ea837d8b
[        ] executing: [/opt/flutter/] git tag --points-at 8f1f9c10f04b8f106d78275e93ceead8ea837d8b
[   +7 ms] Exit code 0 from: git tag --points-at 8f1f9c10f04b8f106d78275e93ceead8ea837d8b
[        ] 2.9.0-0.1.pre
[   +6 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +1 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +50 ms] Unable to locate an Android SDK.
[   +3 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +54 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +96 ms] Skipping pub get: version match.
[  +70 ms] Generating
/home/joe/Desktop/sus/consowole/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +84 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +6 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following
inputs have updated contents: /home/joe/Desktop/sus/consowole/.dart_tool/package_config_subset}
[  +23 ms] gen_dart_plugin_registrant: Complete
[   +2 ms] Skipping target: _composite
[   +1 ms] complete
[   +7 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/opt/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.UGGECD/flutter_tool.DDRTHB/app.dill --packages
/home/joe/Desktop/sus/consowole/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +26 ms] Building Linux application...
[  +27 ms] <- compile package:consowole/main.dart
[   +3 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
-DFLUTTER_TARGET_PLATFORM=linux-x64 /home/joe/Desktop/sus/consowole/linux
[  +10 ms] Building Linux application... (completed in 34ms)
[+6069 ms] ProcessException: Failed to find "cmake" in the search path.
Command: cmake 
[   +1 ms] "flutter run" took 6,550ms.
[   +3 ms] 
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:684:9)
<asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>


[ +124 ms] ensureAnalyticsSent: 122ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
``` 
im using arch linux and i installed flutter from the aur

**Comment by darshankawar** [comment] 2021-12-27 08:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/88897

**Closed by darshankawar** 2021-12-27 08:19 UTC
Labels: in triage
