### ISSUE TITLE
[tool] The fallback to the directory name for `--project-name` is non-obvious for users

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#150609] opened 2024-06-21 09:29 UTC
### Steps to reproduce

1. flutter create name_bug --platforms=android
2. mv name_bug name-bug (so that the project directory is not a valid Dart identifier)
3. cd name-bug
4. flutter create . --platforms=web
5. The tool exits with an error about the project name not being a valid Dart name

### Expected results

I would expect the tool to take the `name` field of the pubspec.yaml, and only if that is invalid, go look at the directory name.

We could also improve the error message:
- if the pubspec name is invalid, print a warning indicating the pubspec name is invalid and we're going to use the current directory name
- if both the pubspec name and directory name are invalid, print a warning indicating that the project name is invalid and that we tried looking at the pubspec name and directory name

### Actual results

The tool uses the project directory basename, per https://github.com/flutter/flutter/blob/c63339866d4f7477777e7377bf044f14b743f71c/packages/flutter_tools/lib/src/commands/create_base.dart#L322-L336

but never specified that in the error message, causing some confusion.

### Code sample

<details open><summary>Code sample</summary>

```dart
N/A
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

N/A

</details>

### Logs

<details open><summary>Logs</summary>

```console
navaronbracke@MacBook-Pro-van-Navaron ~ % cd Desktop
navaronbracke@MacBook-Pro-van-Navaron Desktop % flutter create name_bug --platforms=android
Creating project name_bug...
Resolving dependencies in `name_bug`... 
Downloading packages... 
Got dependencies in `name_bug`.
Wrote 35 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd name_bug
  $ flutter run

Your application code is in name_bug/lib/main.dart.

navaronbracke@MacBook-Pro-van-Navaron Desktop % mv name_bug name-bug
navaronbracke@MacBook-Pro-van-Navaron Desktop % cd name-bug
navaronbracke@MacBook-Pro-van-Navaron name-bug % flutter create . --platforms=web
"name-bug" is not a valid Dart package name.

The name should be all lowercase, with underscores to separate words, "just_like_this".Use only basic Latin letters and Arabic digits:
[a-z0-9_].Also, make sure the name is a valid Dart identifier—that it doesn't start with digits and isn't a reserved word.
See https://dart.dev/tools/pub/pubspec#name for more information.
Try "name_bug" instead.
navaronbracke@MacBook-Pro-van-Navaron name-bug %
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-x64, locale
    en-BE)
    • Flutter version 3.22.1 on channel stable at
      /Users/navaronbracke/Documents/flutter
    • Upstream repository git@github.com:navaronbracke/flutter.git
    • FLUTTER_GIT_URL = git@github.com:navaronbracke/flutter.git
    • Framework revision a14f74ff3a (4 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • motorola one (mobile) • ZL5228NFL7 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)       • macos      • darwin-x64     • macOS 14.4.1 23E224
      darwin-x64
    • Chrome (web)          • chrome     • web-javascript • Google Chrome
      126.0.6478.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### Additional context

I had cloned a project through a version control program (i.e. Github Desktop) where I could create a new folder to clone the project in. Since I had given that folder a `kebab-case` name, I ran into this bug.

**Comment by danagbemava-nc** [comment] 2024-06-21 10:40
Hi @navaronbracke, I believe this is a duplicate of  https://github.com/flutter/flutter/issues/53106

Kindly follow up in the original issue for updates. Please feel free to share your comments in there.

Closing this in favour of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-06-21 10:40 UTC
Labels: in triage
