### ISSUE TITLE
[sensor] Not detecting events from the stream on iOS simulator

### ISSUE THREAD

**Issue by lzhuor** [flutter/flutter#65620] opened 2020-09-11 09:27 UTC
I have a shake detector using `sensor`. It works fine on actual devices but not on iOS Simulator -> `Shake` feature.

```dart

import 'dart:async';
import 'dart:math';
import 'package:rxdart/rxdart.dart';
import 'package:sensors/sensors.dart';

class SensorBloc {
  StreamSubscription<dynamic> _accelerometerStream;

  //INPUT
  final _thresholdController = StreamController<int>();
  Sink<int> get threshold => _thresholdController.sink;

  // OUTPUT
  final  _shakeDetector = StreamController<bool>();
  Stream<bool> get shakeEvent => _shakeDetector.stream.transform(ThrottleStreamTransformer((_) => TimerStream(true, const Duration(seconds: 2))));

  SensorBloc() {
    const CircularBufferSize = 10;
    double detectionThreshold = 70.0;

    List<double> circularBuffer = List.filled(CircularBufferSize,0.0);
    int index = 0;
    double minX=0.0, maxX=0.0;

    _thresholdController.stream.listen((value){
      // safety
      if (value > 30) detectionThreshold = value*1.0;
    });

    _accelerometerStream =  accelerometerEvents.listen((AccelerometerEvent event){
      index = (index == CircularBufferSize -1 ) ? 0: index+1;

      var oldX = circularBuffer[index];

      if (oldX == maxX) {
        maxX = circularBuffer.reduce(max);
      }
      if (oldX == minX) {
        minX = circularBuffer.reduce(min);
      }

      circularBuffer[index] = event.x;
      if (event.x < minX ) minX=event.x;
      if (event.x> maxX) maxX = event.x;

      if (maxX-minX>detectionThreshold)
      {
        _shakeDetector.add(true);
        circularBuffer.fillRange(0, CircularBufferSize, 0.0);
        minX=0.0;
        maxX=0.0;
      }


    });

  }

  void dispose() {
    _shakeDetector.close();
    _accelerometerStream.cancel();
    _thresholdController.close();
  }
}
```

![image](https://user-images.githubusercontent.com/14172220/92902693-0d8d0f80-f454-11ea-8915-ddf373d66d6d.png)

**Comment by TahaTesser** [comment] 2020-09-11 11:50
I can reproduce the issue, iOS shale has no effect on sensors value while the Android emulator shows values when using the virtual sensors option on `sensors: ^0.4.2+4` 

<details> 
<summary>code sample</summary> 

```dart
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:sensors/sensors.dart';

import 'snake.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sensors Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const int _snakeRows = 20;
  static const int _snakeColumns = 20;
  static const double _snakeCellSize = 10.0;

  List<double> _accelerometerValues;
  List<double> _userAccelerometerValues;
  List<double> _gyroscopeValues;
  List<StreamSubscription<dynamic>> _streamSubscriptions =
      <StreamSubscription<dynamic>>[];

  @override
  Widget build(BuildContext context) {
    final List<String> accelerometer =
        _accelerometerValues?.map((double v) => v.toStringAsFixed(1))?.toList();
    final List<String> gyroscope =
        _gyroscopeValues?.map((double v) => v.toStringAsFixed(1))?.toList();
    final List<String> userAccelerometer = _userAccelerometerValues
        ?.map((double v) => v.toStringAsFixed(1))
        ?.toList();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Sensor Example'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          Center(
            child: DecoratedBox(
              decoration: BoxDecoration(
                border: Border.all(width: 1.0, color: Colors.black38),
              ),
              child: SizedBox(
                height: _snakeRows * _snakeCellSize,
                width: _snakeColumns * _snakeCellSize,
                child: Snake(
                  rows: _snakeRows,
                  columns: _snakeColumns,
                  cellSize: _snakeCellSize,
                ),
              ),
            ),
          ),
          Padding(
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text('Accelerometer: $accelerometer'),
              ],
            ),
            padding: const EdgeInsets.all(16.0),
          ),
          Padding(
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text('UserAccelerometer: $userAccelerometer'),
              ],
            ),
            padding: const EdgeInsets.all(16.0),
          ),
          Padding(
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Text('Gyroscope: $gyroscope'),
              ],
            ),
            padding: const EdgeInsets.all(16.0),
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    for (StreamSubscription<dynamic> subscription in _streamSubscriptions) {
      subscription.cancel();
    }
  }

  @override
  void initState() {
    super.initState();
    _streamSubscriptions
        .add(accelerometerEvents.listen((AccelerometerEvent event) {
      setState(() {
        _accelerometerValues = <double>[event.x, event.y, event.z];
      });
    }));
    _streamSubscriptions.add(gyroscopeEvents.listen((GyroscopeEvent event) {
      setState(() {
        _gyroscopeValues = <double>[event.x, event.y, event.z];
      });
    }));
    _streamSubscriptions
        .add(userAccelerometerEvents.listen((UserAccelerometerEvent event) {
      setState(() {
        _userAccelerometerValues = <double>[event.x, event.y, event.z];
      });
    }));
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.137, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.137 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 37e2013774 (4 hours ago), 2020-09-11 04:05:02 -0400
    • Engine revision bdaac368f8
    • Dart version 2.10.0 (build 2.10.0-115.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!
```

</details>

**Comment by SAGARSURI** [comment] 2021-02-26 13:11
Any update on this?

**Comment by stuartmorgan** [comment] 2021-05-27 15:14
Closing as `sensors` is deprecated in favor of [`sensors_plus`](https://pub.dev/packages/sensors_plus).

**Closed by stuartmorgan** 2021-05-27 15:14 UTC
Labels: P6, found in release: 1.22, has reproducible steps, p: first party, p: sensors, platform-ios, plugin

**Comment by SAGARSURI** [comment] 2021-05-27 15:24
@stuartmorgan is the issue resolved in sensor_plus plugin or do I need to create this issue in that repository?

**Comment by stuartmorgan** [comment] 2021-05-27 15:53
I don't know what changes have been made since it was forked by the new maintainers; you'd need to test and/or check their issue database.
