### ISSUE TITLE
[go_router] Parameter validation does not work with wildcard path parameter

### ISSUE THREAD

**Issue by CodeDoctorDE** [flutter/flutter#109463] opened 2022-08-12 17:42 UTC
## Steps to Reproduce

1. Create a route with this path: `:path(.*)` (see code example)
2. Open it in initialLocation

**Expected results:** 
Navigate to this page

**Actual results:** 
Error while validation the parameters

<details>
<summary>Code sample</summary>

```dart
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final GoRouter _router =
      GoRouter(initialLocation: '/native/hello/world', routes: [
    GoRoute(
      name: 'home',
      path: '/',
      builder: (context, state) {
        return Text("Home");
      },
    ),
    GoRoute(
        name: 'native',
        path: '/native/:path(.*)',
        builder: (context, state) {
          return Center(
            child: Text(
              state.params['path'] ?? '',
              style: const TextStyle(fontSize: 24),
            ),
          );
        }),
  ]);
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      routeInformationProvider: _router.routeInformationProvider,
      routeInformationParser: _router.routeInformationParser,
      routerDelegate: _router.routerDelegate,
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
encodedParams[path] is not encoded properly: "hello/world"
'package:go_router/src/match.dart':
package:go_router/src/match.dart:1
Failed assertion: line 31 pos 20: 'p.value == Uri.encodeComponent(Uri.decodeComponent(p.value))'
```

```
Analyzing app...                                                        
No issues found! (ran in 2.1s)
```

```
[✓] Flutter (Channel stable, 3.0.5, on Fedora Linux 36 (KDE Plasma) 5.18.16-200.fc36.x86_64, locale de_DE.UTF-8)
    • Flutter version 3.0.5 at /home/jan-andrej/Apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (vor 4 Wochen), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium-browser

[✓] Linux toolchain - develop for Linux desktop
    • clang version 14.0.0 (Fedora 14.0.0-1.fc36)
    • cmake version 3.22.2
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /home/jan-andrej/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3345.118
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[✓] VS Code (version 1.70.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 36 (KDE Plasma) 5.18.16-200.fc36.x86_64
    • Chrome (web)    • chrome • web-javascript • Chromium 103.0.5060.114 Fedora Project

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

I'm using go_router 4.2.7

**Comment by danagbemava-nc** [comment] 2022-08-15 07:52
Hi @CodeDoctorDE, the exception below is what I see in my console

```
Launching lib/main.dart on iPhone 13 Pro in debug mode...
lib/main.dart:1
Xcode build done.                                           13.9s
Connecting to VM Service at ws://127.0.0.1:63567/FqFIxNZr3bc=/ws

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
encodedParams[path] is not encoded properly: "hello/world"
'package:go_router/src/match.dart':
package:go_router/src/match.dart:1
Failed assertion: line 31 pos 20: 'p.value == Uri.encodeComponent(Uri.decodeComponent(p.value))'
```

Is that the same exception you are getting?

**Comment by CodeDoctorDE** [comment] 2022-08-15 08:01
Yes, it's the "path" property that throws the exception

**Comment by danagbemava-nc** [comment] 2022-08-16 06:50
Thanks for the info. 

Reproducible on `stable` and `master` using the code sample provided above. 

Labeling for further investigation. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2293, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2293 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9758aa35b6 (83 minutes ago), 2022-08-16 01:24:29 -0400
    • Engine revision 280e9a7bec
    • Dart version 2.19.0 (build 2.19.0-100.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

[verbose_log.txt](https://github.com/flutter/flutter/files/9348475/verbose_log.txt)

**Comment by CodeDoctorDE** [comment] 2022-09-03 12:03
Why p4? I would call it a bug instead of a feature

**Comment by danagbemava-nc** [comment] 2022-09-05 06:12
Hi @CodeDoctorDE, P4, is the default label for bugs, P5 is rather for features

**Comment by AceChen1** [comment] 2022-11-30 07:36
@danagbemava-nc  hi may know go router is support wildcard param now?  just have a requirement need to use it...

**Comment by CodeDoctorDE** [comment] 2022-11-30 10:47
What's the difference between the project "priority" and the label priority?

**Comment by chunhtai** [comment] 2022-12-15 23:22
Hi @hangyujin can you take a look at this issue?

**Comment by hangyujin** [comment] 2022-12-20 23:09
Closing this because I can't reproduce this issue on master branch.

**Closed by hangyujin** 2022-12-20 23:09 UTC
Labels: severe: crash, p: first party, package, has reproducible steps, P4, p: go_router, found in release: 3.0, found in release: 3.1
