### ISSUE TITLE
Tracking bug for Android emulator hangs and crashes when running Vulkan apps.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#144631] opened 2024-03-05 18:57 UTC
In https://github.com/flutter/engine/pull/50730#issuecomment-1977758346, we ran into hangs and crashes on the Android emulators. This has been reproduced and reported to the Android emulator team in [b/327501571](http://b/327501571). This issue tracks a resolution of that internal bug.

**Comment by dnfield** [comment] 2024-03-05 19:00
Duplicate of https://github.com/flutter/flutter/issues/144232

**Closed by dnfield** 2024-03-05 19:00 UTC
Labels: team-engine
