### ISSUE TITLE
On Mouse Hover feedback for Cupertino clickable elements

### ISSUE THREAD

**Issue by iqfareez** [flutter/flutter#82088] opened 2021-05-08 04:22 UTC
Sorry I'm not sure if there is already a similar open issue in here.

## Use case

Buttons, and other clickable element should give feedback. ie, change colour, change mouse pointer. For Android and iOS maybe, this feature is not needed as there is no cursor. 

## Proposal

Add on hover mouse feedback on **Cupertino** interactive/clickable elements. (Similar like the one Material offer)

Refer video below where I compare Material widget and Cupertino Widget on Flutter Web.

https://user-images.githubusercontent.com/60868965/117526476-f5c45600-aff7-11eb-9d7f-33cdd5dfe790.mp4

**Comment by darshankawar** [comment] 2021-05-10 08:15
@iqfareez 
Can you check and confirm if [this](https://github.com/flutter/flutter/issues/58192) issue resemble your request ?

**Comment by iqfareez** [comment] 2021-05-10 08:22
Thanks @darshankawar. Yes it is! Same issue but i could find it in the first place.

**Comment by darshankawar** [comment] 2021-05-10 13:45
Closing this as duplicate of https://github.com/flutter/flutter/issues/58192. Please comment your observation in original issue for tracking.

**Closed by darshankawar** 2021-05-10 13:45 UTC
Labels: in triage
