### ISSUE TITLE
[windows][uwp] ` ctrl +shift + s` crashes the app

### ISSUE THREAD

**Issue by PassionPenguin** [flutter/flutter#87038] opened 2021-07-26 09:55 UTC
see #67866 #74138 

similar to the problem on macOS, this problem is caused by a hot key `ctrl +shift + s` on Windows 10 with built-in Screenshot support. In macOS, the problem is caused by language changing hot key `caps lock`.

tested positive with any code, built-in template, no changes, only need to perform the screenshot hotkey after the application is loaded.

<details> 
<summary>logs</summary> 
	
```console
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key
event being sent doesn't properly set its modifier flags. This was the event:
RawKeyDownEvent#36232(logicalKey: LogicalKeyboardKey#00109(keyId: "0x30000000109", keyLabel: "Meta
Left", debugName: "Meta Left"), physicalKey: PhysicalKeyboardKey#700e3(usbHidUsage: "0x000700e3",
debugName: "Meta Left")) and its data: Instance of 'RawKeyEventDataWindows'
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 666 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:666:7)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:359:35)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:356:46)
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:203:15)
#11     _invoke2 (dart:ui/hooks.dart:202:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:536:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Attempted to send a key down event when no keys are in keysPressed. This state can occur
if the key event being sent doesn't properly set its modifier flags. This was the event:
RawKeyDownEvent#7ca12(logicalKey: LogicalKeyboardKey#0010d(keyId: "0x3000000010d", keyLabel: "Shift Left", debugName:
"Shift Left"), physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left")) and its data:
Instance of 'RawKeyEventDataWindows'
```
	
</details>

## min reproducable code

```sh
mkdir tmp
cd tmp
flutter create .
flutter run -d winuwp
# waiting for loaded
```

\+

`ctrl + shift + s`

**tested positive** as well.

**Comment by PassionPenguin** [comment] 2021-07-26 09:57
instead of the exception log on macos, on winuwp this will lead to crash

**Comment by PassionPenguin** [comment] 2021-07-26 10:00
the problem is not existed on windows native c++ program(traditional windows c++).

**Comment by TahaTesser** [comment] 2021-07-26 15:29
Hi @PassionPenguin 
Thanks for filing the issue, I can reproduce the issue on the latest `master` 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.4.0-5.0.pre.182, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.4.0-5.0.pre.182 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff49d35c90 (9 hours ago), 2021-07-26 02:28:03 -0400
    • Engine revision 420fa3a18f
    • Dart version 2.14.0 (build 2.14.0-350.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio-preview\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Taha\Code\android-studio-preview
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19043.1110]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 91.0.4472.164
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 91.0.864.71

• No issues found!
```

</details>

**Comment by gspencergoog** [comment] 2021-07-29 18:13
cc @dkwingsmt

**Comment by cbracken** [comment] 2022-04-14 19:46
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495

**Closed by cbracken** 2022-04-14 19:46 UTC
Labels: a: text input, severe: regression, engine, platform-windows, a: desktop, has reproducible steps, P4, severe: fatal crash, e: uwp, found in release: 2.4

**Comment by PassionPenguin** [comment] 2022-04-15 04:20
this should be great....but the issue was suspended for really a long time, forcing me to change to native sdk development
