### ISSUE TITLE
[tool_crash] RangeError: RangeError: Value not in range: 1254

### ISSUE THREAD

**Issue by SuhJaeHyeon** [flutter/flutter#152533] opened 2024-07-30 02:29 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=00008110-001A24C62E79401E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RangeError: RangeError: Value not in range: 1254
```
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:5242:5)
#1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1925:5)
#2      new Uint8List.view (dart:typed_data:891:19)
#3      decodeMDnsResponse.readResourceRecord (package:multicast_dns/src/packet.dart:343:23)
#4      decodeMDnsResponse (package:multicast_dns/src/packet.dart:372:38)
#5      MDnsClient._handleIncoming (package:multicast_dns/multicast_dns.dart:239:46)
#6      MDnsClient.start.<anonymous closure> (package:multicast_dns/multicast_dns.dart:160:47)
#7      _rootRunUnary (dart:async/zone.dart:1415:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#13     _StreamController._add (dart:async/stream_controller.dart:658:7)
#14     _StreamController.add (dart:async/stream_controller.dart:606:5)
#15     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2535:33)
#16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.5 23F79 darwin-arm64, locale en-KR)
    • Flutter version 3.19.2 on channel stable at /Users/martin/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (5 months ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/martin/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (3 available)
    • 재현 (mobile)     • 00008110-001A24C62E79401E • ios            • iOS 17.5.1 21F90
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 127.0.6533.72
    ! Error: Browsing on the local area network for Jh_pad (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7482962148e8d758338d8a28f589f317e1e42ba4

**Comment by danagbemava-nc** [comment] 2024-07-30 08:43
Closing this as a duplicate of https://github.com/flutter/flutter/issues/136008

**Closed by danagbemava-nc** 2024-07-30 08:43 UTC
Labels: in triage
