### ISSUE TITLE
 error: incompatible types: MainActivity cannot be converted to FlutterEngine    GeneratedPluginRegistrant.registerWith(this)

### ISSUE THREAD

**Issue by zommerberg** [flutter/flutter#65630] opened 2020-09-11 11:55 UTC
Hello, I am creating an android service with Java .
A part of the my AppService.java looks like that

```
  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        GeneratedPluginRegistrant.registerWith(this);
    }
```

However when booting the app I get a ` error: incompatible types: MainActivity cannot be converted to FlutterEngine    GeneratedPluginRegistrant.registerWith(this)`

How can I resolve this error ?
I saw a potential solution for Kotlin in #58347 , however how would we solve that when I need to build the service in Java?

I am using flutter version 1.20.2

**Comment by zommerberg** [comment] 2020-09-11 11:57
My verbose looks like this:
```
[ +126 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] bbfbf1770cca2da7c82e887e4e4af910034800b6        
[        ] executing: [C:\flutter/] git tag --contains HEAD
[  +71 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.2
[  +14 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +35 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: no upstream configured for branch 'stable'
[  +23 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +80 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +17 ms] executing: C:\Users\hetzb\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +56 ms] List of devices attached
           12601a93               device product:lavender_eea model:Redmi_Note_7 device:lavender transport_id:6
[   +7 ms] C:\Users\hetzb\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 12601a93 shell getprop
[  +94 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +114 ms] Found plugin vibration at C:\Users\hetzb\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\vibration-1.4.0\
[  +63 ms] Found plugin vibration at C:\Users\hetzb\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\vibration-1.4.0\
[  +53 ms] Generating C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +31 ms] ro.hardware = qcom
[  +62 ms] Starting incremental build...
[   +3 ms] Initializing file store
[  +32 ms] Skipping target: gen_localizations
[  +19 ms] complete
[   +5 ms] Launching lib\main.dart on Redmi Note 7 in debug mode...
[  +26 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\hetzb\AppData\Local\Temp\flutter_tools.f6f143ab\flutter_tool.be66380d\app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +19 ms] executing: C:\Users\hetzb\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 12601a93 shell -x logcat -v time -t 1
[ +143 ms] Exit code 0 from: C:\Users\hetzb\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 12601a93 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           09-11 14:57:09.512 E/subsystem_ramdump(20250): Unable to open /sys/module/subsystem_restart/parameters/enable_ramdumps
[   +2 ms] executing: C:\Users\hetzb\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 12601a93 shell -x logcat -v time -t 1
[ +134 ms] Exit code 0 from: C:\Users\hetzb\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 12601a93 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           09-11 14:57:09.512 E/subsystem_ramdump(20250): Unable to open /sys/module/subsystem_restart/parameters/enable_ramdumps
[  +16 ms] <- compile package:rest/main.dart
[  +21 ms] executing: C:\Users\hetzb\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[  +44 ms] Android Debug Bridge version 1.0.41
           Version 30.0.3-6597393
           Installed as C:\Users\hetzb\AppData\Local\Android\Sdk\platform-tools\adb.exe
[  +18 ms] executing: C:\Users\hetzb\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[  +48 ms] Building APK
[  +33 ms] Running Gradle task 'assembleDebug'...
[  +15 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\android\gradlew.bat.
[   +1 ms] C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +10 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +112 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +84 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +4 ms] executing: [C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\android/] C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3096 ms] > Task :app:compileFlutterBuildDebug
[        ] [ +120 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +64 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] bbfbf1770cca2da7c82e887e4e4af910034800b6
[        ] [        ] executing: [C:\flutter/] git tag --contains HEAD
[        ] [  +70 ms] Exit code 0 from: git tag --contains HEAD
[        ] [        ] 1.20.2
[        ] [  +10 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +33 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] fatal: no upstream configured for branch 'stable'
[        ] [  +24 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +32 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +32 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +52 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +13 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +24 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [  +72 ms] Initializing file store
[  +26 ms] [  +16 ms] Skipping target: gen_localizations
[        ] [   +8 ms] kernel_snapshot: Starting due to {}
[        ] [  +32 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true    
-Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages
C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\.packages --output-dill C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\.dart_tool\flutter_build\05ff4002af6edd6d407df13e90006539\app.dill --depfile
C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\.dart_tool\flutter_build\05ff4002af6edd6d407df13e90006539\kernel_snapshot.d package:rest/main.dart
[+5419 ms] [+6234 ms] kernel_snapshot: Complete
[ +699 ms] [ +682 ms] debug_android_application: Starting due to {}
[  +99 ms] [ +157 ms] debug_android_application: Complete
[ +500 ms] [ +524 ms] Persisting file store
[  +99 ms] [  +26 ms] Done persisting file store
[        ] [  +14 ms] build succeeded.
[        ] [  +19 ms] "flutter assemble" took 7,814ms.
[        ] [   +4 ms] ensureAnalyticsSent: 0ms
[  +17 ms] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +179 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :vibration:preBuild UP-TO-DATE
[        ] > Task :vibration:preDebugBuild UP-TO-DATE
[        ] > Task :vibration:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :vibration:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :vibration:mergeDebugShaders UP-TO-DATE
[        ] > Task :vibration:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :vibration:generateDebugAssets UP-TO-DATE
[  +17 ms] > Task :vibration:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +272 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :vibration:generateDebugResValues UP-TO-DATE
[        ] > Task :vibration:compileDebugRenderscript NO-SOURCE
[        ] > Task :vibration:generateDebugResources UP-TO-DATE
[        ] > Task :vibration:packageDebugResources UP-TO-DATE
[  +95 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :vibration:checkDebugManifest UP-TO-DATE
[        ] > Task :vibration:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :vibration:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :vibration:generateDebugRFile UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :vibration:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :vibration:javaPreCompileDebug UP-TO-DATE
[        ] > Task :vibration:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :vibration:bundleLibCompileDebug UP-TO-DATE
[ +193 ms] > Task :app:compileDebugKotlin
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +172 ms] > Task :app:compileDebugJavaWithJavac FAILED
[   +1 ms] C:\Users\hetzb\Desktop\Learning\t-mer-backgorund-service\rest\android\app\src\main\java\dev\protium\rest\MainActivity.java:34: error: incompatible types: MainActivity cannot be converted to FlutterEngine
[   +1 ms]         GeneratedPluginRegistrant.registerWith(this);
[  +18 ms]                                                ^
[        ] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
[        ] 1 error
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 10s
[        ] 31 actionable tasks: 6 executed, 25 up-to-date
[ +339 ms] Running Gradle task 'assembleDebug'... (completed in 11.6s)
[   +9 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +11 ms] "flutter run" took 12,794ms.
[  +21 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +118 ms] ensureAnalyticsSent: 110ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by zommerberg** [comment] 2020-09-11 12:01
I could provide the full MainActivity and AppService if needed

**Comment by pedromassangocode** [comment] 2020-09-11 12:46
Hi @zommerberg 
Please provide a complete flutter project sample that reproduces the issue you are facing.
Thank you

**Comment by zommerberg** [comment] 2020-09-11 14:37
Hello  @pedromassangocode  
This is a repo where you can reproduce the issue.
https://github.com/zommerberg/rest-flutter-1.20-

If you try to run the app then you will encounter the error

**Comment by pedromassangocode** [comment] 2020-09-11 15:24
Hi @zommerberg 
It is recommended to edit your Android code using Android Studio because it shows you errors while you write code, I run you project using Android Studio and it clearly shows the error.

![Screen Shot 2020-09-11 at 16 24 11](https://user-images.githubusercontent.com/67424416/92943895-3ceb4e80-f44b-11ea-85cb-8c85c890cef5.png)

You may be setting up your plugin in the wrong place. Please see https://flutter.dev/docs/development/platform-integration/platform-channels to learn more about custom platform code.

Closing this as this is not an issue with Flutter itself. if you disagree please write a comment bellow and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-11 15:24 UTC
Labels: in triage

**Comment by GeeSuth** [comment] 2020-09-13 18:15
> 
> 
> Hi @zommerberg
> It is recommended to edit your Android code using Android Studio because it shows you errors while you write code, I run you project using Android Studio and it clearly shows the error.
> 
> ![Screen Shot 2020-09-11 at 16 24 11](https://user-images.githubusercontent.com/67424416/92943895-3ceb4e80-f44b-11ea-85cb-8c85c890cef5.png)
> 
> You may be setting up your plugin in the wrong place. Please see https://flutter.dev/docs/development/platform-integration/platform-channels to learn more about custom platform code.
> 
> Closing this as this is not an issue with Flutter itself. if you disagree please write a comment bellow and I will reopen it.
> Thank you

I changed this to "MainActivity" like you say then i occur others problem 
`flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());`
@pedromassango 

![Annotation 2020-09-13 211457](https://user-images.githubusercontent.com/10328974/93025385-39e88d80-f606-11ea-9e39-088f752c430b.jpg)

**Comment by pedromassangocode** [comment] 2020-09-14 07:26
Hi @zommerberg 
You just changed the name of the parameter. The link bellow can help you better understand how platform channels work, please take a look at it
https://flutter.dev/docs/development/platform-integration/platform-channels
