### ISSUE TITLE
DefaultTabController nesting a PaginatedDataTable using a toggle tab will cause the page to become blank

### ISSUE THREAD

**Issue by 370966584** [flutter/flutter#29080] opened 2019-03-09 02:36 UTC
There was a problem upgrading to stable1.2.1

Before switching tabs
![CD70AE70-53DB-4011-9EE6-1C09CD6BA4A7](https://user-images.githubusercontent.com/26058251/54065129-fc5bb500-4256-11e9-9c88-22644dc99138.png)

After switching tabs

![1EDCB5BA-5237-4A5C-96C4-C85BA732F356](https://user-images.githubusercontent.com/26058251/54065132-08e00d80-4257-11e9-9870-fa12656913a0.png)

<details>
<summary> Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {

      _counter++;
    });
  }

 @override
    Widget build(BuildContext context) {

    return DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          title: Text('测试'),
          bottom: PreferredSize(
            preferredSize: Size.fromHeight(kTextTabBarHeight),
            child: Container(
              width: double.infinity,
              child: TabBar(
                labelColor: Theme.of(context).primaryColor,
                // labelStyle: TextStyle(fontSize: 15,),
                unselectedLabelColor: Colors.black,
                // unselectedLabelStyle: TextStyle(fontSize: 13,),
                indicatorColor: Colors.blueAccent,
                // labelPadding: EdgeInsets.symmetric(horizontal: 10),
                isScrollable: true,
                tabs: [
                  Tab(text: 'tab1',),
                  Tab(text: 'tab2',),
                  
                ],
              ),color: Colors.white,
            ),
          ),
        ),
        body: TabBarView(
          
          children: [
            GJBBPage(),
            GJBBPage(),
          ],
        ),
      ),
    );
  }
}

class GJBBPage extends StatefulWidget {
  @override
  _GJBBPageState createState() => _GJBBPageState();
}

class _GJBBPageState extends State<GJBBPage> with AutomaticKeepAliveClientMixin{

@override
  bool get wantKeepAlive => true;

  final List columStrings = ['colum1','colum2','colum3','colum4','colum5','colum6','colum7'];
  

@override
  void initState() {
    super.initState();

  }

 @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      padding: EdgeInsets.only(top: 5),
      child: SingleChildScrollView(
        child:_dataTableWidget(),
      ),
    );
  }

  _dataTableWidget(){
      
        return PaginatedDataTable(
          rowsPerPage: 10,
          onPageChanged: ( page){
            print('当前页一个index=$page');
          },
          // onRowsPerPageChanged:(int value) { setState(() { _rowsPerPage = value; }); },
          source: GJBBTable(),
          header: Text('header',textAlign: TextAlign.center, style: TextStyle(fontSize: 16),),
          columns: this.columStrings.map((title){
            return DataColumn(label: Text(title));
          }).toList(),
        );
    }


}

class GJBBTable extends DataTableSource{

  
  GJBBTable();

  // final ValueChanged<int> selectRowCallback;

  @override
  DataRow getRow(int index) {
  
    return DataRow.byIndex(
        cells: [
          DataCell(Text('cell1')),
          DataCell(Text('cell222222')),
          DataCell(Text('cell33')),
          DataCell(Text('cell44')),
          DataCell(Text('cell555')),
          DataCell(Text('cell6666666')),
          DataCell(Text('cell77777777')),

        ],
        selected: false,
        index: index,
        onSelectChanged: null,
      );
  }
  @override
  bool get isRowCountApproximate => false;


  @override
  int get rowCount => 3;

  @override
  int get selectedRowCount => 0;

}
```
</details>

<details>
<summary> Logs</summary>

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
D/        ( 8736): HostConnection::get() New Host Connection established 0xec51d540, tid 8759
D/EGL_emulation( 8736): eglMakeCurrent: 0xecd20780: ver 3 0 (tinfo 0xec5032e0)
I/flutter ( 8736): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 8736): The following NoSuchMethodError was thrown during paint():
I/flutter ( 8736): The method '[]' was called on null.
I/flutter ( 8736): Receiver: null
I/flutter ( 8736): Tried calling: [](0)
I/flutter ( 8736): 
I/flutter ( 8736): When the exception was thrown, this was the stack:
I/flutter ( 8736): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 8736): #1      RenderTable.paint 
I/flutter ( 8736): #2      RenderObject._paintWithContext 
I/flutter ( 8736): #3      PaintingContext.paintChild 
I/flutter ( 8736): #4      _RenderSingleChildViewport.paint.paintContents 
I/flutter ( 8736): #5      PaintingContext.pushLayer 
I/flutter ( 8736): #6      PaintingContext.pushClipRect 
I/flutter ( 8736): #7      _RenderSingleChildViewport.paint 
I/flutter ( 8736): #8      RenderObject._paintWithContext 
I/flutter ( 8736): #9      PaintingContext._repaintCompositedChild 
I/flutter ( 8736): #10     PaintingContext.repaintCompositedChild 
I/flutter ( 8736): #11     PipelineOwner.flushPaint 
I/flutter ( 8736): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 
I/flutter ( 8736): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
I/flutter ( 8736): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
I/flutter ( 8736): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
I/flutter ( 8736): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
I/flutter ( 8736): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
I/flutter ( 8736): #21     _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 8736): #22     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 8736): (elided 3 frames from package dart:async)
I/flutter ( 8736): 
I/flutter ( 8736): The following RenderObject was being processed when the exception was fired:
I/flutter ( 8736):   RenderTable#6a76d relayoutBoundary=up17
I/flutter ( 8736):   creator: Table ← DataTable-[GlobalKey#1ed45] ← _SingleChildViewport ←
I/flutter ( 8736):   IgnorePointer-[GlobalKey#d2a84] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 8736):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#bfc1c] ← _ScrollableScope ←
I/flutter ( 8736):   _ScrollSemantics-[GlobalKey#51979] ← RepaintBoundary ← CustomPaint ← ⋯
I/flutter ( 8736):   parentData: <none> (can use size)
I/flutter ( 8736):   constraints: BoxConstraints(unconstrained)
I/flutter ( 8736):   size: Size(835.0, 536.0)
I/flutter ( 8736):   specified column widths: {0: IntrinsicColumnWidth(flex: null), 1: IntrinsicColumnWidth(flex:
I/flutter ( 8736):   null), 2: IntrinsicColumnWidth(flex: null), 3: IntrinsicColumnWidth(flex: null), 4:
I/flutter ( 8736):   IntrinsicColumnWidth(flex: null), 5: IntrinsicColumnWidth(flex: null), 6:
I/flutter ( 8736):   IntrinsicColumnWidth(flex: null)}
I/flutter ( 8736):   default column width: FlexColumnWidth(1.0)
I/flutter ( 8736):   table size: 7×11
I/flutter ( 8736):   column offsets: 0.0, 111.0, 231.0, 346.0, 461.0, 576.0, 704.0
I/flutter ( 8736):   row offsets: 0.0, 56.0, 104.0, 152.0, 200.0, 248.0, 296.0, 344.0, 392.0, 440.0, 488.0, 536.0
I/flutter ( 8736): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 8736):   RenderSemanticsGestureHandler#a17c1 relayoutBoundary=up18
I/flutter ( 8736):     RenderPointerListener#a01d1 relayoutBoundary=up19
I/flutter ( 8736):       RenderConstrainedBox#ecaf5 relayoutBoundary=up20
I/flutter ( 8736):         RenderPadding#5df3a
I/flutter ( 8736):           RenderPositionedBox#97c77
I/flutter ( 8736):   RenderSemanticsGestureHandler#a2705 relayoutBoundary=up18
I/flutter ( 8736):     RenderPointerListener#0515e relayoutBoundary=up19
I/flutter ( 8736):       RenderConstrainedBox#7d383 relayoutBoundary=up20
I/flutter ( 8736):         RenderPadding#59a40
I/flutter ( 8736):           RenderPositionedBox#568d8
I/flutter ( 8736):   RenderSemanticsGestureHandler#25a2d relayoutBoundary=up18
I/flutter ( 8736):     RenderPointerListener#c0a3b relayoutBoundary=up19
I/flutter ( 8736):       RenderConstrainedBox#6e24d relayoutBoundary=up20
I/flutter ( 8736):         RenderPadding#bbe5f
I/flutter ( 8736):           RenderPositionedBox#683f4
I/flutter ( 8736):   RenderSemanticsGestureHandler#624a3 relayoutBoundary=up18
I/flutter ( 8736):     RenderPointerListener#3bb7f relayoutBoundary=up19
I/flutter ( 8736):       RenderConstrainedBox#a1765 relayoutBoundary=up20
I/flutter ( 8736):         RenderPadding#555bc
I/flutter ( 8736):           RenderPositionedBox#bc30b
I/flutter ( 8736):   RenderSemanticsGestureHandler#3c244 relayoutBoundary=up18
I/flutter ( 8736):     RenderPointerListener#0b3db relayoutBoundary=up19
I/flutter ( 8736):       RenderConstrainedBox#01e97 relayoutBoundary=up20
I/flutter ( 8736):         RenderPadding#b368e
I/flutter ( 8736):           RenderPositionedBox#8cca4
I/flutter ( 8736):   ...(descendants list truncated after 25 lines)
I/flutter ( 8736): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8736): Another exception was thrown: NoSuchMethodError: The method '[]' was called on null.
I/chatty  ( 8736): uid=10098(com.example.lianxi) 1.ui identical 16 lines
I/flutter ( 8736): Another exception was thrown: NoSuchMethodError: The method '[]' was called on null.
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14 18A391, locale
    zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/haoran1/Flutter/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/haoran1/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)
```
</details>

**Comment by fleetcor** [comment] 2019-04-20 12:59
I also met this issue, any update
@370966584

**Comment by shihaohong** [comment] 2019-05-30 00:57
I just tested this on the `master` branch and it seems to be working fine. Is this only a problem with `stable1.2.1`?

**Comment by 370966584** [comment] 2019-06-04 06:51
> I just tested this on the `master` branch and it seems to be working fine. Is this only a problem with `stable1.2.1`?

I just tested it in stable1.5.4-hotfix.2, and the same problem will still occur.

The test process is like this:
On the tab1 page, slide the PaginatedDataTable, then switch tab2, then switch back to tab1 to slide the PaginatedDataTable.

**Comment by pedromassangocode** [comment] 2020-07-16 14:58
Hi @370966584 
I cannot reproduce this issue on latest `dev` and `stable` channel.
Please update to the latest `stable` channel by running:
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

<details>
<summary> Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {

      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          title: Text('测试'),
          bottom: PreferredSize(
            preferredSize: Size.fromHeight(kTextTabBarHeight),
            child: Container(
              width: double.infinity,
              child: TabBar(
                labelColor: Theme.of(context).primaryColor,
                // labelStyle: TextStyle(fontSize: 15,),
                unselectedLabelColor: Colors.black,
                // unselectedLabelStyle: TextStyle(fontSize: 13,),
                indicatorColor: Colors.blueAccent,
                // labelPadding: EdgeInsets.symmetric(horizontal: 10),
                isScrollable: true,
                tabs: [
                  Tab(text: 'tab1',),
                  Tab(text: 'tab2',),

                ],
              ),color: Colors.white,
            ),
          ),
        ),
        body: TabBarView(

          children: [
            GJBBPage(),
            GJBBPage(),
          ],
        ),
      ),
    );
  }
}




class GJBBPage extends StatefulWidget {
  @override
  _GJBBPageState createState() => _GJBBPageState();
}

class _GJBBPageState extends State<GJBBPage> with AutomaticKeepAliveClientMixin{

  @override
  bool get wantKeepAlive => true;

  final List columStrings = ['colum1','colum2','colum3','colum4','colum5','colum6','colum7'];


  @override
  void initState() {
    super.initState();

  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      padding: EdgeInsets.only(top: 5),
      child: SingleChildScrollView(
        child:_dataTableWidget(),
      ),
    );
  }

  _dataTableWidget(){

    return PaginatedDataTable(
      rowsPerPage: 10,
      onPageChanged: ( page){
        print('当前页一个index=$page');
      },
      // onRowsPerPageChanged:(int value) { setState(() { _rowsPerPage = value; }); },
      source: GJBBTable(),
      header: Text('header',textAlign: TextAlign.center, style: TextStyle(fontSize: 16),),
      columns: this.columStrings.map((title){
        return DataColumn(label: Text(title));
      }).toList(),
    );
  }


}

class GJBBTable extends DataTableSource{


  GJBBTable();

  // final ValueChanged<int> selectRowCallback;

  @override
  DataRow getRow(int index) {

    return DataRow.byIndex(
      cells: [
        DataCell(Text('cell1')),
        DataCell(Text('cell222222')),
        DataCell(Text('cell33')),
        DataCell(Text('cell44')),
        DataCell(Text('cell555')),
        DataCell(Text('cell6666666')),
        DataCell(Text('cell77777777')),

      ],
      selected: false,
      index: index,
      onSelectChanged: null,
    );
  }
  @override
  bool get isRowCountApproximate => false;


  @override
  int get rowCount => 3;

  @override
  int get selectedRowCount => 0;

}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-AO)
    • Flutter version 1.17.5 at /Users/pedro/dev/SDKs/flutter_stable
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28)
      (emulator)

• No issues found!
```
</details>

Closing this since the issue seems to be fixed. 
Please feel free to comment if you still facing this issue and I will reopen it.

**Closed by pedromassangocode** 2020-07-16 14:58 UTC
Labels: P4, f: material design, framework
