### ISSUE TITLE
\CreateProcessW failed 193 Unhandled exception: ProcessException: %1 non

### ISSUE THREAD

**Issue by LorenzoPantano** [flutter/flutter#30329] opened 2019-04-01 18:39 UTC
I downloaded flutter zip file (version 1.2.1), installed and also installed Android Studio, with android sdk ecc. I also have java-12 jdk. I updated the path variable with flutter/bin and when I try to run any flutter command the process ends with different messages depending on the command. For example with flutter doctor: \CreateProcessW failed 193 Unhandled exception: ProcessException: %1 non
If I try to create a project: Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 289bec89adcae115)
\CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 non
 
## Logs

```
    C:\Users\Lorenzo Pantano>flutter --verbose create foo
[  +28 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +88 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +52 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +1 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[   +1 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%ar
[  +52 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 7 weeks ago
[   +3 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +59 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.2.1-0-g8661d8aec
[ +335 ms] Creating project foo...
[  +74 ms]   foo\.gitignore (created)
[  +38 ms]   foo\.idea\libraries\Dart_SDK.xml (created)
[  +34 ms]   foo\.idea\libraries\Flutter_for_Android.xml (created)
[  +17 ms]   foo\.idea\libraries\KotlinJavaRuntime.xml (created)
[  +12 ms]   foo\.idea\modules.xml (created)
[  +16 ms]   foo\.idea\runConfigurations\main_dart.xml (created)
[  +10 ms]   foo\.idea\workspace.xml (created)
[  +11 ms]   foo\.metadata (created)
[  +12 ms]   foo\android\app\build.gradle (created)
[  +20 ms]   foo\android\app\src\main\java\com\example\foo\MainActivity.java (created)
[  +16 ms]   foo\android\build.gradle (created)
[  +13 ms]   foo\android\foo_android.iml (created)
[  +16 ms]   foo\android\app\src\debug\AndroidManifest.xml (created)
[  +17 ms]   foo\android\app\src\main\AndroidManifest.xml (created)
[  +17 ms]   foo\android\app\src\main\res\drawable\launch_background.xml (created)
[  +10 ms]   foo\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
[   +4 ms]   foo\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
[   +8 ms]   foo\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
[   +6 ms]   foo\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
[   +6 ms]   foo\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
[   +7 ms]   foo\android\app\src\main\res\values\styles.xml (created)
[  +40 ms]   foo\android\app\src\profile\AndroidManifest.xml (created)
[   +7 ms]   foo\android\gradle\wrapper\gradle-wrapper.properties (created)
[   +8 ms]   foo\android\gradle.properties (created)
[   +9 ms]   foo\android\settings.gradle (created)
[  +54 ms]   foo\ios\Runner\AppDelegate.h (created)
[  +10 ms]   foo\ios\Runner\AppDelegate.m (created)
[  +10 ms]   foo\ios\Runner\main.m (created)
[  +12 ms]   foo\ios\Runner.xcodeproj\project.pbxproj (created)
[  +62 ms]   foo\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
[  +25 ms]   foo\ios\Flutter\AppFrameworkInfo.plist (created)
[  +10 ms]   foo\ios\Flutter\Debug.xcconfig (created)
[  +11 ms]   foo\ios\Flutter\Release.xcconfig (created)
[   +6 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
[  +14 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
[ +125 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
[   +8 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
[   +6 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
[   +7 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
[   +6 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
[  +10 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
[   +7 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
[   +7 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
[  +23 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
[   +9 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
[  +15 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
[   +7 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
[   +9 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
[   +7 ms]   foo\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
[  +51 ms]   foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
[  +23 ms]   foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
[   +6 ms]   foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
[   +7 ms]   foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
[   +7 ms]   foo\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
[   +8 ms]   foo\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
[  +14 ms]   foo\ios\Runner\Base.lproj\Main.storyboard (created)
[  +11 ms]   foo\ios\Runner\Info.plist (created)
[  +13 ms]   foo\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
[  +10 ms]   foo\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (existing - skipped)
[   +2 ms]   foo\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
[   +6 ms]   foo\lib\main.dart (created)
[  +19 ms]   foo\foo.iml (created)
[  +13 ms]   foo\pubspec.yaml (created)
[  +17 ms]   foo\README.md (created)
[  +12 ms]   foo\test\widget_test.dart (created)
[ +440 ms] Running "flutter packages get" in foo...
[   +8 ms] Using C:\flutter\.pub-cache for the pub cache.
[   +3 ms] executing: [C:\Users\Lorenzo Pantano\foo\] C:\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning
--verbose get --no-precompile
[+6236 ms] Running "flutter packages get" in foo... (completed in 6,2s)
[ +180 ms] Wrote 66 files.
[        ]
           All done!
[ +378 ms] java -version
[ +161 ms] executing: C:\Users\Lorenzo Pantano\AppData\Local\Android\sdk\tools\bin\sdkmanager --licenses
CreateProcessW failed 193
[   +6 ms] "flutter create" took 8.768ms.
[        ] "flutter create" took 8.768ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 53d9376a8a56ffa8)
\CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 non
```

-----DOCTOR---

```C:\Users\Lorenzo Pantano>flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Versione 10.0.17134.648], locale it-IT)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

\CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 non
```

**Comment by dnfield** [comment] 2019-04-01 23:15
Does this reproduce for you with the JDK8?  Some of the Android SDK tools are a bit funny about what version of the JDK you have.

**Comment by powext** [comment] 2019-10-04 11:18
You have a space in your Windows User name and flutter doesn't handle it...

check this: [https://stackoverflow.com/a/53232266](url)

The space can be also in "Program Files" (my current situation) and i can't do nothing... certainly i can't reinstall all the programs because of this...

**Comment by dnfield** [comment] 2019-10-04 14:13
We test that flutter can work in directories with spaces.  Program files will be a problem because it requires admin access to write to.  You should not install flutter in a location that requires elevated privileges to write to.

**Comment by iapicca** [comment] 2020-01-14 12:09
Hi @LorenzoPantano 
Are you still experiencing the issue with the latest stable version of Flutter?
If so, can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by iapicca** [comment] 2020-02-04 08:26
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-02-04 08:26 UTC
Labels: severe: crash, tool, waiting for customer response, ▣ platform-android
