### ISSUE TITLE
Sometimes there's screen flickering or flashing on IOS devices

### ISSUE THREAD

**Issue by Yangpengtao** [flutter/flutter#105940] opened 2022-06-14 03:33 UTC
We can't reproduce the problem This problem arises under uncertain circumstances. It usually appears on IOS devices. The screen flashes between black and white
![GIF](https://user-images.githubusercontent.com/17306239/173487597-108f2432-b35b-4268-b982-6824f2400018.gif)
.

**Comment by Yangpengtao** [comment] 2022-06-14 03:35
flutter SDK: 2.10.3
device: apple 12 PM, apple 12

**Comment by manuelduarte077** [comment] 2022-06-14 05:42
Hmm, I miss that problem which version of iOS are you testing to discard the device would be that you try it with another version if you are testing in the simulator try with a physical device.

**Comment by Yangpengtao** [comment] 2022-06-14 07:42
Yes the screen flickering was on physical devices, which are our real users'devices.




---Original---
From: "Manuel ***@***.***&gt;
Date: Tue, Jun 14, 2022 13:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [flutter/flutter] Sometimes there's screen flickering or flashing on IOS devices (Issue #105940)




 
Hmm, I miss that problem which version of iOS are you testing to discard the device would be that you try it with another version if you are testing in the simulator try with a physical device.

**Comment by danagbemava-nc** [comment] 2022-06-14 08:31
Closing this as a duplicate of #100522. 

Kindly follow up in the linked issue for updates. If you have any information to share, kindly see https://github.com/flutter/flutter/issues/100522#issuecomment-1133075980. 

Thank you

**Closed by danagbemava-nc** 2022-06-14 08:31 UTC
Labels: in triage
