### ISSUE TITLE
Make `flutter build ios --config-only` provide the correct `Flutter.framework` library for bitcode configured project

### ISSUE THREAD

**Issue by avi-mastov** [flutter/flutter#85871] opened 2021-07-04 19:50 UTC
## Use case

`flutter build ios --config-only`, when used with bitcode, this doesn't install the bitcode support for the Flutter library, and then the build fails:

> bitcode bundle could not be generated because '/Users/vagrant/git/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/vagrant/git/ios/Flutter/Flutter.framework/Flutter' for architecture arm64

I have to revert to running `flutter build ios` before xcode archive, which makes the `--config-only` option unusable with a bitcode application. I have no choice but to use bitcode, because my app has a watchOS companion app.

## Proposal

Make the build step that selects the bitcode/regular binary of the Flutter iOS library (according to the project's settings) available via the `--config-only` option.

**Comment by LongXiangGuo** [comment] 2021-07-05 05:56
I could not build the project  success with the flutter command tools, from the building logs, it seems to be must special a real device id for it , and currently it not support build it by simulator with flutter command tools.

```
[        ] Watch companion app found. Adjusting build settings.
[        ] No simulator device ID has been set.
[        ] A device ID is required to build an app with a watchOS companion app.
[        ] Please run "flutter devices" to get a list of available device IDs
[        ] and specify one using the -d, --device-id flag.
[  +24 ms] "flutter ios" took 5,495ms.
[   +6 ms] Encountered error while building for simulator.
```

Commands had tried those build instruction combinations via the `Usage: flutter build ios [arguments]`, none of them can succeed

```
example % flutter build ios --target=lib/main.dart --flavor universal  --verbose --simulator -d 077DFA15-0590-4441-93A4-0FC7B5458317

flutter build ios --target=lib/main.dart --flavor universal  --verbose --simulator 

flutter build ios --target=lib/main.dart --flavor universal  --verbose --debug  --no-tree-shake-icons --no-config-only 

flutter build ios --device-id 077DFA15-0590-4441-93A4-0FC7B5458317 --target=lib/main.dart --flavor universal  --verbose --debug  --no-tree-shake-icons --simulator --no-config-only --no-codesign
```

**Comment by jmagman** [comment] 2022-05-02 20:34
@LongXiangGuo that's unrelated, I fixed that in https://github.com/flutter/flutter/issues/96600.

**Comment by jmagman** [comment] 2022-05-02 20:44
@avi-mastov I know you filed this awhile ago, but I wasn't able to reproduce this anymore.  I opened an example project, set `ENABLE_BITCODE` then ran `flutter build ios --config-only`.  From there I was able to build the app from Xcode, or `flutter run` in release and debug mode.  I'm not sure what version you saw this in.
Any chance you have more complete steps to reproduce?

**Comment by jmagman** [comment] 2022-05-02 20:46
(maybe you hit https://github.com/flutter/flutter/issues/78589 which was fixed in https://github.com/flutter/flutter/pull/78592)

**Comment by avi-mastov** [comment] 2022-05-03 06:38
Hi @jmagman. Thanks a lot for getting back to me on that. Unfortunately, I am no longer working on that project. @YanivAmram will take over this issue.

**Comment by jmagman** [comment] 2022-05-03 17:17
Thanks @avi-mastov sorry again for the delay.
@yanivamram are you able to reproduce this?  If so, can you give more complete steps to reproduce?

**Comment by jmagman** [comment] 2022-07-19 02:48
Closing this, I was never able to reproduce, and the only bitcode work we're going to do at this point is remove it https://github.com/flutter/flutter/issues/107887.

**Closed by jmagman** 2022-07-19 02:48 UTC
Labels: platform-ios, tool, proposal, a: build, passed first triage
