### ISSUE TITLE
Websocket disconnects for no reason on flutter web

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#85146] opened 2021-06-23 18:21 UTC
This issue seems irrelevant to the flutter version as we went through several versions and the issue remains

We have a connection made with https://pub.dev/packages/web_socket_channel

We are sending the ping message within the interval required by the server

The connection lasts. sometimes 17 minutes, sometimes 7 hours, it varies, but eventually it disconnects,

This has been tested both on development build and production build in several devices.

Code is

```
_subscription = _channel!.stream.listen(
    (e) => _handlePusherEvent(e),
    onDone: () => _onDone(), // Clean disconnection here for no reason
    onError: (e) => _onWebsocketError(e),
);


void _onDone() {
  print("onDone");
}
```
The connection per se has no issue given that we are able to connect and send and receive messages while it is active.

Back end sends no errors whatsoever.

Thank you

[✓] Flutter (Channel master, 2.3.0-17.0.pre.416, on Linux Mint 20.1 5.4.0-58-generic, locale en_US.UTF-8)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

**Comment by TahaTesser** [comment] 2021-06-25 11:07
HI @arualana 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/web_socket_channel/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-25 11:07 UTC
Labels: in triage

**Comment by arualana** [comment] 2021-06-25 13:38
@TahaTesser  how do I do a minimal reproducible code sample that does not use 3rd party plugins?

The example I used came from the flutter docs https://flutter.dev/docs/cookbook/networking/web-sockets

If the flutter documentations uses this library, I think it is a flutter problem.

Could you share a code example with no 3rd party library please?
