### ISSUE TITLE
E/MethodChannel#plugins.flutter.io/shared_preferences: Failed to handle method call

### ISSUE THREAD

**Issue by s2yed** [flutter/flutter#77783] opened 2021-03-10 09:32 UTC
E/MethodChannel#plugins.flutter.io/shared_preferences: Failed to handle method call
    java.util.concurrent.RejectedExecutionException: Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@801df75 rejected from java.util.concurrent.ThreadPoolExecutor@6287280[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 4]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
        at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.commitAsync(MethodCallHandlerImpl.java:137)
        at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:66)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
E/MethodChannel#plugins.flutter.io/shared_preferences: Failed to handle method call

**Comment by pedromassangocode** [comment] 2021-03-10 09:46
Hi @s2yed 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, a minimal complete reproducible code sample and the steps to reproduce this issue?
Thank you

**Comment by stuartmorgan** [comment] 2021-03-10 11:27
Duplicate of https://github.com/flutter/flutter/issues/77155#issuecomment-795197250

**Closed by stuartmorgan** 2021-03-10 11:27 UTC
Labels: in triage, waiting for customer response
