### ISSUE TITLE
[tool_crash] StateError: Bad state: Cannot add event after closing

### ISSUE THREAD

**Issue by Grk26** [flutter/flutter#90126] opened 2021-09-15 13:07 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9101 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Cannot add event after closing
```
#0      _StreamController.add (dart:async/stream_controller.dart:553:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:826:13)
#2      AppConnection.runMain (package:dwds/src/connections/app_connection.dart:33:22)
#3      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:669:25)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.2.3 at D:\Program Files\flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:/Android/sdk
    • Java binary at: D:\Program Files\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\Program Files\IntelliJ IDEA 2021.1.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.47

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.3.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 216dee60c0cc9449f0b29bcf922974d612263e24
### Plugins
cloud_firestore-2.5.2
cloud_firestore_web-2.4.2
connectivity-3.0.6
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
file_picker-4.0.2
firebase_auth-3.1.1
firebase_auth_web-3.1.0
firebase_core-1.6.0
firebase_core_web-1.1.0
firebase_messaging-10.0.4
firebase_messaging_web-2.0.3
firebase_storage-10.0.3
firebase_storage_web-3.0.2
flutter_paystack-1.0.5+1
flutter_plugin_android_lifecycle-2.0.2
fluttertoast-8.0.8
geolocator-7.4.0
geolocator_android-1.0.0
geolocator_apple-1.0.0
geolocator_web-2.0.6
google_maps_flutter-2.0.6
image_picker-0.7.5+4
image_picker_for_web-2.1.2
open_file-3.2.1
path_provider-2.0.2
path_provider_linux-2.0.2
path_provider_macos-2.0.2
path_provider_windows-2.0.3
razorpay_flutter-1.2.7
shared_preferences-2.0.6
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.1
shared_preferences_windows-2.0.2
url_launcher-6.0.10
url_launcher_linux-2.0.1
url_launcher_macos-2.0.1
url_launcher_web-2.0.2
url_launcher_windows-2.0.1
video_player-2.1.12
video_player_web-2.0.2
wakelock-0.5.3+3
wakelock_macos-0.1.0+2
wakelock_web-0.2.0+2
webview_flutter-2.0.12

**Comment by danagbemava-nc** [comment] 2021-09-16 08:12
Hi @Grk26, you appear to be on an older version of `stable` can you please upgrade to the latest `stable` and see if you still experience this issue?

Thank you

**Comment by darshankawar** [comment] 2021-09-22 07:26
Closing this as duplicate of https://github.com/flutter/flutter/issues/59757

**Closed by darshankawar** 2021-09-22 07:26 UTC
Labels: waiting for customer response, in triage
