### ISSUE TITLE
Some glyphs are not replaced with Ahem font in tests

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#7978] opened 2017-02-08 20:23 UTC
## Steps to Reproduce

1. In the engine repo, `ninja -C out/host_debug_unopt`
2. From the Flutter repo root:
```
% cd packages/flutter
% $PATH_TO_ENGINE/src/out/host_debug_unopt/SkyShell.app/Contents/MacOS/SkyShell \
      --packages=.packages \
      --use-test-fonts \
      test/material/paginated_data_table_test.dart
```

**Expected:** table contents rendered in Ahem font.
**Actual:** table contents rendered in system font.

Tested on macOS; I haven't yet verified on a Linux/Windows build.

**Comment by tvolkert** [comment] 2017-04-06 03:33
Running this against the `flutter_tester` that's in `bin/cache/artifacts/engine/darwin-x64`, I get the following:

```
2017-04-05 20:32:04.630 flutter_tester[18983:7478030] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
```

**Comment by tvolkert** [comment] 2017-04-06 04:15
Nevermind - looks like the `bin/cache` tester isn't sufficient.

**Comment by tvolkert** [comment] 2017-04-06 04:42
Ok, I'm able to reproduce this in [`test/widgets/focus_test.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/focus_test.dart).

### Relying on --use-test-fonts

If I run the test as it's checked in, the Text widgets in the test are rendered using a real system font:
  * [before the tap](https://cloud.githubusercontent.com/assets/15253456/24737826/8d8f0ef4-1a46-11e7-8c81-fa4ea8030f43.png)
  * [after the tap](https://cloud.githubusercontent.com/assets/15253456/24737867/bcd28ec0-1a46-11e7-8f91-3e9df9fe4ac9.png)

### Hard-coding Ahem font in tests

If I explicitly use the Ahem font in the test by adding a `style: new TextStyle(fontFamily: 'Ahem')` parameter to the `Text` widget's constructor call, then it uses the Ahem font:
  * [before the tap](https://cloud.githubusercontent.com/assets/15253456/24737918/fe672eb8-1a46-11e7-9466-f2a75be5a9f4.png)
  * [after the tap](https://cloud.githubusercontent.com/assets/15253456/24738099/46f6b616-1a48-11e7-9184-95c676d1c76d.png)

This is actually blocking a roll of Flutter into Google because on a local machine, the fact that it's using a system default font generally doesn't affect the operation of a test, but in Google's production automation infrastructure, there is no default system font, and the text widgets end up with a size of `(0, 0)`, causing tests to fail.

@chinmaygarde

**Comment by chinmaygarde** [comment] 2017-04-06 18:41
The way the test fonts are wired up makes it so that initial font resolution is done by SkFontHost per platform. If the font resolved by that backend cannot resolve the required glyphs, our test fallbacks take hold. Fixing.

**Comment by jason-simmons** [comment] 2017-04-06 18:50
Another option would be an implementation of FontCache for tests with a different policy for resolving the last resort fallback font

**Closed** 2017-04-06 19:38 UTC
Labels: prod: engine
