### ISSUE TITLE
problem in sending data to firestore using `StreamBuilder`

### ISSUE THREAD

**Issue by oGranny** [flutter/flutter#69501] opened 2020-10-31 18:47 UTC
hello, 
I am building an app similar to instagram where I am displaying all the posts in a stream builder but I have made the like button such that whenever user clicks on his uid will get stored in firestore database and if he click it again it will be removed using `removeUnion(uid)` but it sometime works sometime doesn't like I have hosted it on (https://smirk-debug.web.app)[https://smirk-debug.web.app] you can login using email: pefex25950@soowz.com with pass `123123` you can also manage the number of posts in the add tab if there will be 1 post it will work fine but if the number of post increases it doesn't work or works very strange

`flutter doctor -v`:
```txt
$ flutter doctor -v
[√] Flutter (Channel beta, 1.22.0, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.0 at F:\f\mohit\flutter2\flutter
    • Framework revision d408d302e2 (5 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at f:\f\mohit\Android
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = F:\f\mohit\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\bro\AppData\Local\Google\Chrome\Application\chrome.exe  

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\bro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.111      
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.58       

• No issues found!
```

streambuilder:
```dart
return StreamBuilder(
        stream: FirebaseFirestore.instance
            .collection("posts")
            .orderBy("timeStamp", descending: true)
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasError) {
            return Center(child: CircularProgressIndicator());
          }
          return ListView.builder(
            itemCount: snapshot.data.documents.length,
            itemBuilder: (context, index) {
              // final int likes = finalList.length;
              DocumentSnapshot posts = snapshot.data.documents[index];
              bool liked = _isliked(posts);
              bool likedd = false;
              // bool likedd = posts["like"].forEach((val) {
              //   if (user?.uid == val)
              //     return true;
              //   else
              //     return false;
              // });
              return Container(
                width: double.infinity,
                color: Theme.of(context).accentColor,
                padding: const EdgeInsets.symmetric(vertical: 4.0),
                child: Column(
                  children: [
                    Padding(
                      padding: const EdgeInsets.fromLTRB(7, 7, 7, 0),
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          CircleAvatar(
                            backgroundColor: Theme.of(context).accentColor,
                            backgroundImage: NetworkImage(posts["avatarUrl"]),
                          ),
                          SizedBox(width: 9),
                          Text(posts["name"] ?? "null"),
                          Spacer(),
                          Text(posts["timeDifference"] ?? "null"),
                          SizedBox(width: 4),
                        ],
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 4),
                      child: Divider(
                        color: Colors.grey[250],
                      ),
                    ),
                    Image.network(posts["memeUrl"]),
                    Padding(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8.0, vertical: 4),
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          Text("${posts["like"].length ?? "null"} likes • ",
                              style: TextStyle(
                                fontSize: 12,
                              )),
                          Text(
                            "${posts["comments"] ?? "null"} comments",
                            style: TextStyle(
                              fontSize: 12,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 4.0, vertical: 0),
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          IconButton(
                            icon: liked
                                ? Icon(
                                    FontAwesomeIcons.solidHeart,
                                    color: Colors.red,
                                  )
                                : Icon(
                                    FontAwesomeIcons.heart,
                                    color: Colors.red,
                                  ),
                            onPressed: () {
                              // print(user?.uid);
                              print(posts["like"]);
                              // FirestoreService().updatePost();
                              // posts["like"].forEach((val) {
                              //   user.uid == val
                              //       // ? setState(() {
                              //       ? likedd = true
                              //       // })
                              //       // : setState(() {
                              //       : likedd = false;
                              //   // });
                              // });
                              // print(likedd);
                              // liked = _isliked(posts);
                              print(index);
                              print(user.uid);
                              print(posts["like"]);
                              liked
                                  ? FirestoreService().updatePost1(index)
                                  : FirestoreService().updatePost(index);
                            },
                          ),
                          SizedBox(width: 3),
                          IconButton(
                            icon: Icon(FontAwesomeIcons.comment),
                            onPressed: () {
                              print(posts["uid"]);
                              print(_isliked(posts).toString());
                              print(posts["like"]);
                              print(user?.uid);
                              liked
                                  ? FirestoreService().updatePost1(index)
                                  : FirestoreService().updatePost(index);
                              // posts["comments"]++;
                              // setState(() {});
                            },
                          ),
                          Spacer(),
                          PopupMenuButton(
                            child: Icon(Icons.more_horiz),
                            itemBuilder: (context) {
                              return [
                                PopupMenuItem(
                                    value: "download",
                                    child: Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.spaceBetween,
                                      children: [
                                        Icon(Icons.download_rounded),
                                        Text("Download"),
                                      ],
                                    )),
                                if (posts["uid"] == user?.uid)
                                  PopupMenuItem(
                                      value: "delete",
                                      child: Row(
                                        mainAxisAlignment:
                                            MainAxisAlignment.spaceBetween,
                                        children: [
                                          Icon(Icons.delete_forever),
                                          Text("Delete"),
                                        ],
                                      ))
                              ];
                            },
                            tooltip: "more",
                            onSelected: (value) async {
                              if (value == "download" && !kIsWeb) {
                                print("download requested");

                                GallerySaver.saveImage(posts["memeUrl"]).then(
                                    (value) => value
                                        ? Scaffold.of(context)
                                            .showSnackBar(SnackBar(
                                            content: Text("Image downloaded"),
                                          ))
                                        : Scaffold.of(context)
                                            .showSnackBar(SnackBar(
                                            content:
                                                Text("Error downloading image"),
                                          )));
                              }
                              if (value == "download" && kIsWeb) {
                                _launchURL(posts["memeUrl"]);
                              }

                              if (value == "delete") {
                                FirestoreService().deletePost(index);
                              }
                            },
                          ),
                          SizedBox(width: 10),
                        ],
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8.0, vertical: 1),
                      child: Container(
                        alignment: Alignment.centerLeft,
                        child: Text(
                          posts["caption"] ?? "null",
                          style: TextStyle(fontWeight: FontWeight.w500),
                        ),
                      ),
                    ),
                    SizedBox(height: 2)
                  ],
                ),
              );
            },
          );
        });
  }
```
isLiked function:
```dart

  bool _isliked(DocumentSnapshot posts) {
    for (var i in posts["like"]) {
      if (i == user?.uid) {
        return true;
      } else {
        return false;
      }
    }
    return false;
  }
}
```

updatePost and updatePost1:
```dart

  updatePost(int index) async {
    List listLikes = await FirebaseFirestore.instance
        .collection("posts")
        .get()
        .then((value) => value.docs);
    await FirebaseFirestore.instance
        .collection("posts")
        .doc(listLikes[index].id.toString())
        .update({
      "like": FieldValue.arrayUnion([user.uid])
    });
  }

  updatePost1(int index) async {
    List listLikes = await FirebaseFirestore.instance
        .collection("posts")
        .get()
        .then((value) => value.docs);
    await FirebaseFirestore.instance
        .collection("posts")
        .doc(listLikes[index].id.toString())
        .update({
      "like": FieldValue.arrayRemove([user.uid])
![firebase-structure](https://user-images.githubusercontent.com/68510259/97787404-f35fea00-1bd7-11eb-81e2-b86fe5e5be06.PNG)

    });
  }
```

firestore structure:
![firebase-structure](https://user-images.githubusercontent.com/68510259/97787467-60737f80-1bd8-11eb-84c4-e41c4f013409.PNG)

PS: i have also tried android but same error

**Comment by iapicca** [comment] 2020-10-31 21:04
@oGranny 
Issues with `firebase` should be opened [here](https://github.com/FirebaseExtended/flutterfire/issues)
and, as the [new issue menu](https://github.com/flutter/flutter/issues/new/choose) suggesta 
question like `I want help writing my application` should be asked on [stackoverflow](https://stackoverflow.com/)

**Comment by hamdikahloun** [comment] 2020-11-01 09:47
Hi @oGranny 

@iapicca  is correct

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues) .
Closing, as this isn't an issue with Flutter itself.
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`, your `pubspec.yaml` and a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.

Thank you

**Closed by hamdikahloun** 2020-11-01 09:47 UTC
