### ISSUE TITLE
IOS 13.3 TextStyle FontWeight being completely Ignored

### ISSUE THREAD

**Issue by x4080** [flutter/flutter#49492] opened 2020-01-25 23:50 UTC
Hi, after upgrade my ios to 13.3, my flutter app cannot display bold (compare to before upgrade and in android)

Is it problem with ios 13.3 ? Or there's breaking changes in flutter for ios ? Android works fine

**Comment by iapicca** [comment] 2020-01-27 08:24
Hi @x4080  
can you please provide your `flutter doctor -v` ,
and if possible a reproducible minimal code sample.
Thank you

**Comment by x4080** [comment] 2020-01-28 00:01
@iapicca Thanks for quick response,

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.5-pre.35, on Mac OS X 10.14.5 18F132, locale en-ID)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

Source is using default flutter create [projectname]
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title:
              // Text(widget.title,
              //           style: Theme.of(context).primaryTextTheme.headline5,)
              Text(
        widget.title,
        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 25),
      )),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

![android emulator](https://user-images.githubusercontent.com/10181090/73224340-c93a5100-419b-11ea-8ac7-eac28694ef3d.png)
![ios simulator 13 3](https://user-images.githubusercontent.com/10181090/73224341-c9d2e780-419b-11ea-92f6-ee4b6f7de8d5.png)

```

Attached the result in ios simulator and android emulator using bold

BTW it seems that headline5 now is not include bold after I did flutter upgrade on my other computer

But the bold is not displaying in IOS still happened

**Comment by pamir72** [comment] 2020-01-28 05:52
Confirm. Flutter 1.14.5. iOS 13.3. Font with bold weight (and w500, w600, w700 .....) is not displayed for the emulator or on the real device.

**Comment by x4080** [comment] 2020-01-28 05:57
@pamir72 thanks so its not just me

**Comment by pamir72** [comment] 2020-01-28 06:02
It's not only headline5. Any with bold for me

**Comment by calvinmuller** [comment] 2020-01-28 10:35
Same issue for me.

**Comment by athornz** [comment] 2020-01-28 18:21
For me the issue is reversed - all fonts are bold and don't respect the FontWeight.

**Comment by Crisis2010** [comment] 2020-01-28 19:32
Same here

**Comment by roysprojects** [comment] 2020-02-02 06:53
This isn't exclusive to iOS. I don't know if it's a problem with my phone, but when the apk is installed on my phone, fontWeight is completely ignored and my Text widgets don't look the same as they do on the simulator.

**Comment by Livinglist** [comment] 2020-02-05 02:10
Same here. FontWeight is not working properly on iOS

**Comment by EliasDeuss** [comment] 2020-02-05 21:57
The issue has made it to the beta channel, not just in master or dev channels @iapicca

**Comment by dpedrinha** [comment] 2020-02-06 04:06
I'm also facing this problem. 
But I didn't figure it was related to the iOS version. I thought it was a problem with device models.
Newer devices doesn't show bold and older devices do.
I created a test app for that if needed.
[](https://github.com/dpedrinha/ios-bold-text-bug)
Just build and run. It shows bold on iPhone 6 but not on 11.

**Comment by pamir72** [comment] 2020-02-06 05:06
11 Pro Max and SE4 the same issue

**Comment by mrm** [comment] 2020-02-06 12:58
I can confirm this is related to the flutter version, with the latest flutter version all my headings are no longer bold. My previous build, with an older flutter version, works as it should on an iPhone 11 pro with the latest iOS version.

**Comment by Jethro87** [comment] 2020-02-06 18:26
Same issue for me - nothing is bold on iOS anymore. Running the app on an iPhone 8.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.2 19C57, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)
```

**Comment by EliasDeuss** [comment] 2020-02-07 12:20
@x4080 Probably should just change the title to “TextStyle FontWeight being completely Ignored”

**Comment by sanekyy** [comment] 2020-02-09 14:47
Same issue, faced in beta channel.

**Comment by m-j-g** [comment] 2020-02-12 14:03
Poor iOS.  Seems no one ran an app one time on iOS for this build, bc its a pretty dramatic UI change when all the font weights are dropped from your app.

**Comment by calvinmuller** [comment] 2020-02-12 14:09
I guess the flutter team have moved on to better things 🤷‍♂

**Comment by dpedrinha** [comment] 2020-02-12 17:19
Is there a single dev from the flutter team following this?
This is not a critical bug but I consider it major. Should be addressed with urgency.

**Comment by xster** [comment] 2020-02-12 21:25
Seems like a pretty severe regression. @GaryQian could you take a swing at this one? 

@ others, is this specifically an iOS 13.3 issue that's not reproducible in other iOS versions?

**Comment by jason-simmons** [comment] 2020-02-13 00:07
This regressed due to a change in Skia: https://github.com/google/skia/commit/d5eebba99ee2a20b9f812094614b401440b2132f

**Comment by xster** [comment] 2020-02-13 01:40
Thanks for the quick find. Can we start a rollback in the meantime?

**Comment by dnfield** [comment] 2020-02-13 21:26
There's some chat going on now with the Skia team about how to properly resolve this.

**Comment by dnfield** [comment] 2020-02-15 04:33
Quick update - apparently we can't revert the offending commit because it's necessary for Chrome.  Still trying to figure out right way to fix this.

**Comment by howieweiner** [comment] 2020-02-17 20:51
> @ others, is this specifically an iOS 13.3 issue that's not reproducible in other iOS versions?

Yes. Not sure if it is specifically 13.3 that introduces the issue, but definitely not there in 12.4 I just tested on the simulators

<img width="673" alt="flutter-ios-12-13" src="https://user-images.githubusercontent.com/955237/74685709-33f11200-51c7-11ea-9c1f-d7b80f7f59d3.png">

**Comment by EliasDeuss** [comment] 2020-02-18 04:58
> > @ others, is this specifically an iOS 13.3 issue that's not reproducible in other iOS versions?
> 
> Yes. Not sure if it is specifically 13.3 that introduces the issue, but definitely not there in 12.4 I just tested on the simulators
> 
> <img alt="flutter-ios-12-13" width="673" src="https://user-images.githubusercontent.com/955237/74685709-33f11200-51c7-11ea-9c1f-d7b80f7f59d3.png">

Yes I think it effects all iOS versions, looks like a issue with the flutter engine.

I have tested it on these devices:
iPhone 11 Pro (13.4)
iPhone 7 (13.3) 
iPhone 5s (12)

**Comment by dnfield** [comment] 2020-02-19 00:09
@bungeman believes he has a fix for this that will be ready in the next day or two.

**Comment by xster** [comment] 2020-02-19 00:19
Thanks for following up @dnfield. Can someone confirm that https://github.com/google/skia/commit/d5eebba99ee2a20b9f812094614b401440b2132f was the cause of the font weight issue on all iOS versions (and that this problem indeed affects all versions)?

**Comment by dnfield** [comment] 2020-02-19 00:22
@xster - according to Ben, we cannot revert that PR because it fixes something essential for Chrome. We're fairly sure that it is the cause, but we need a different work around landed than reverting it.

Perhaps Ben will be able to update this issue with more details.

**Comment by pamir72** [comment] 2020-02-20 15:52
Any news ?

**Comment by dpedrinha** [comment] 2020-02-20 16:55
Hello guys.
Isn't it about time to find a temporary fix for this? This is a pretty relevant bug and it has been around for weeks already.
If `skia `can't rollback, then can't `flutter `rollback on the `skia `version?
Or add an `if(CHROME)` or something? It isn't pretty but we need a workaround for this until a permanent fix is found.
I'm getting pretty bad reviews and complains because of this and as we all know, this hurts badly.

**Comment by dnfield** [comment] 2020-02-20 18:03
There is a patch for Skia that should fix this being reviewed now.

Unfortunately, the internals of this involve a bunch of strangeness around the way CoreText handles fonts.  It's not a trivial thing to manage or just ifdef out.  And unfortunately, the severity of this bug did not come to the attention of anyone who could act on it until well after it had been reported.  

This is very actively being worked on, and should have a resolution soon.  For now, your best bet is to use the stable channel of Flutter, and avoid beta until this is resolved.

**Comment by dpedrinha** [comment] 2020-02-20 21:15
Thanks for the reply @dnfield.
I`m using `master` because the `stable` were giving me other problems. Maybe it`s fized now, I`ll give it a try.

**Comment by x4080** [comment] 2020-02-20 22:25
@dpedrinha Is it fix now in master ? I'm using master too

**Comment by dnfield** [comment] 2020-02-22 08:14
https://skia-review.googlesource.com/c/skia/+/272116 Is the latest attempt.

No, this is still not fixed on master.

**Comment by dpedrinha** [comment] 2020-02-23 05:29
I tried using the stable channel but then I get `Error: No named parameter with the name 'bodyText2'. `and I can't compile. If I use `body2`, I keep getting a warning of it being deprecated and that I should use `bodyText2`. But, it doesn't work. 
So the stable channel is not that stable.

**Comment by lukepighetti** [comment] 2020-02-23 17:14
I have a couple projects that are backed into a corner because of this. We're using the new Material textTheme on `dev` so we cannot revert to `stable` because these new properties are missing.

**Comment by lukepighetti** [comment] 2020-02-23 17:16
Can someone provide an ETA on this landing on `dev`, much appreciated.

**Comment by howieweiner** [comment] 2020-02-24 19:57
Please can you advise what version I can revert to, to mitigate this issue? I assume this is possible? Thx

**Comment by dpedrinha** [comment] 2020-02-25 01:15
> Please can you advise what version I can revert to, to mitigate this issue? I assume this is possible? Thx

Stable version is working.

`flutter channel stable` does the trick.

**Comment by lukepighetti** [comment] 2020-02-25 01:55
Stable works but it’s missing the new material theme properties which one of our apps depends on heavily.

**Comment by xster** [comment] 2020-02-25 03:44
https://skia-review.googlesource.com/c/skia/+/272116 landed upstream in Skia. It'll take a day or 2 for it to percolate through to Flutter master.

**Comment by dnfield** [comment] 2020-02-27 21:46
This should be fixed on master now, after https://github.com/flutter/flutter/pull/51480

Can anyone experiencing this pleast test on master and verify?

**Comment by passsy** [comment] 2020-02-28 10:40
I can verify the fix is working.

Upgrading from `beta` to `master` wasn't easy due to some recent breaking changes I ran into https://github.com/flutter/flutter/pull/48346, https://github.com/flutter/flutter/pull/44930, https://github.com/flutter/flutter/pull/51435

**Comment by gliese667c** [comment] 2020-02-28 12:33
Verified too, on `master` commit `1cc8cc299`

**Comment by sanekyy** [comment] 2020-02-28 12:53
I confirm, fixed.

**Closed** 2020-02-28 20:45 UTC
Labels: a: typography, customer: crowd, dependency: skia, f: material design, framework, severe: regression, ⌺‬ platform-ios

**Comment by scopendo** [comment] 2020-02-29 18:11
Will this be expedited to the beta channel, or are the dependencies too big to allow it?

**Comment by dnfield** [comment] 2020-02-29 18:40
@tvolkert

**Comment by tvolkert** [comment] 2020-02-29 23:13
@scopendo it should make it to the beta channel in the next beta release, but it won't be cherry-picked, so the next beta release will also contain the API-breaking changes you see on master.

**Comment by jlubeck** [comment] 2020-03-05 13:48
Hey @tvolkert. I'm new to flutter dev so sorry if this is an obvious question. But are there periodic releases to beta channel or is it just "whenever it happens"? Just trying to figure out if I can wait for this or find an alternative. Thank you!

**Comment by tvolkert** [comment] 2020-03-05 18:32
@jlubeck see https://github.com/flutter/flutter/wiki/Release-process#rolling-the-beta-channel.  tldr: beta releases are generally once a month early in the month (will likely be early next week).

Side-note: we're in the process of defining a new release process that should allow us to publish a calendar so people can plan on our beta and stable releases.  Stay tuned 🙂

**Comment by jlubeck** [comment] 2020-03-05 18:52
Nice, thank you @tvolkert !

**Comment by jlubeck** [comment] 2020-03-18 14:47
Nice, beta was published and this is now fixed on beta channel
