### ISSUE TITLE
ios release mode still has debug banner showing

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#52242] opened 2020-03-09 16:20 UTC
I've been through the instructions (below) and followed everything to the letter however my build always has the red 'debug' banner at the top right. 
https://flutter.dev/docs/deployment/ios

I've run `flutter clean`, and tried building with `--release`

Output of my build:
```
> Executing task in folder eurovision: cd mobile && flutter build ios --release <

Building app.eurovision.mobile for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: U4KM65Y22D
Running pod install...                                              2.9s
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                        28.7s
Xcode build done.                                           116.7s
Built /Users/jimmyff/Development/eurovision/mobile/build/ios/iphoneos/Runner.app.

Terminal will be reused by tasks, press any key to close it.
```

After running the build, I then open xcode (using Runner.xcworkspace), I then select the app `Runner` from the left, and run it using an simulator, and my app works but has the red debug banner in the top right.  I have tried everything, but I simply cannot get rid of the red debug banner!

### Flutter doctor output

```
jimmypro-7:mobile jimmyff$ flutter doctor -v
[✓] Flutter (Channel master, v1.15.19-pre.17, on Mac OS X 10.14.6 18G1012, locale en-GB)
    • Flutter version 1.15.19-pre.17 at /Users/jimmyff/flutter-sdk
    • Framework revision 5b0a79dbdb (15 hours ago), 2020-03-08 21:16:01 -0400
    • Engine revision 981c03631e
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Development/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Development/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /Applications/Development/IntelliJ IDEA.app
    ✗ Flutter plugin version 15.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 172.3317.48
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Pixel 3           • 8B5X140C0                            • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro Max • 40B9123E-2BB5-4437-A9BF-D9D9B4C40710 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
```

**Comment by muzemmil-dotcom** [comment] 2020-03-09 16:30
Pada tanggal 10 Mar 2020 1.23 AM, "Jimmy Forrester-Fellowes" <
notifications@github.com> menulis:
>
> I've been through the instructions (below) and followed everything to the
letter however my build always has the red 'debug' banner at the top right.
> https://flutter.dev/docs/deployment/ios
>
> I've run flutter clean, and tried building with --release
>
> Output of my build:
>
> > Executing task in folder eurovision: cd mobile && flutter build ios
--release <
>
>
>
> Building app.eurovision.mobile for device (ios-release)...
>
> Automatically signing iOS for device deployment using specified
development team in Xcode project: U4KM65Y22D
>
> Running pod install...                                              2.9s
>
> Running Xcode build...
>
>
>
>  └─Compiling, linking and signing...                        28.7s
>
> Xcode build done.                                           116.7s
>
> Built
/Users/jimmyff/Development/eurovision/mobile/build/ios/iphoneos/Runner.app.
>
>
>
> Terminal will be reused by tasks, press any key to close it.
>
> After running the build, I then open xcode (using Runner.xcworkspace), I
then select the app Runner from the left, and run it using an simulator,
and my app works but has the red debug banner in the top right. I have
tried everything, but I simply cannot get rid of the red debug banner!
>
> Flutter doctor output
>
> jimmypro-7:mobile jimmyff$ flutter doctor -v
>
> [✓] Flutter (Channel master, v1.15.19-pre.17, on Mac OS X 10.14.6
18G1012, locale en-GB)
>
>     • Flutter version 1.15.19-pre.17 at /Users/jimmyff/flutter-sdk
>
>     • Framework revision 5b0a79dbdb (15 hours ago), 2020-03-08 21:16:01
-0400
>
>     • Engine revision 981c03631e
>
>     • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
>
>
>
>
>
> [✓] Android toolchain - develop for Android devices (Android SDK version
29.0.2)
>
>     • Android SDK at /Users/jimmyff/Library/Android/sdk
>
>     • Android NDK location not configured (optional; useful for native
profiling support)
>
>     • Platform android-29, build-tools 29.0.2
>
>     • Java binary at: /Applications/Development/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>
>     • Java version OpenJDK Runtime Environment (build
1.8.0_202-release-1483-b49-5587405)
>
>     • All Android licenses accepted.
>
>
>
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
>
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>
>     • Xcode 11.3.1, Build version 11C504
>
>     • CocoaPods version 1.9.0
>
>
>
> [✓] Android Studio (version 3.5)
>
>     • Android Studio at /Applications/Development/Android
Studio.app/Contents
>
>     • Flutter plugin version 40.2.2
>
>     • Dart plugin version 191.8593
>
>     • Java version OpenJDK Runtime Environment (build
1.8.0_202-release-1483-b49-5587405)
>
>
>
> [!] IntelliJ IDEA Ultimate Edition (version 2017.2)
>
>     • IntelliJ at /Applications/Development/IntelliJ IDEA.app
>
>     ✗ Flutter plugin version 15.1 - the recommended minimum version is
16.0.0
>
>     • Dart plugin version 172.3317.48
>
>     • For information about installing plugins, see
>
>       https://flutter.dev/intellij-setup/#installing-the-plugins
>
>
>
> [✓] Connected device (2 available)
>
>     • Pixel 3           • 8B5X140C0                            •
android-arm64 • Android 10 (API 29)
>
>     • iPhone 11 Pro Max • 40B9123E-2BB5-4437-A9BF-D9D9B4C40710 •
ios           •

**Comment by VladyslavBondarenko** [comment] 2020-03-09 17:49
Hi @jimmyff 
Could you check is it only for master or the same with some earlier version? like the last dev or the last stable

**Comment by jimmyff** [comment] 2020-03-10 11:30
@VladyslavBondarenko I switched to `dev` channel, flutter clean & upgrade, rebuild, still same issue: the red debug banner was in the top right corner.

I then tried `stable`. which didn't work at all. When I tried to run the release build in the simulator I just got a white screen. 

Here is the output:
```
> Executing task in folder eurovision: cd mobile && flutter build ios --release <

Downloading ios tools...                                            2.6s
Downloading ios-profile tools...                                    2.0s
Downloading ios-release tools...                                   10.5s
Downloading package sky_engine...                                   0.2s
Downloading common tools...                                         0.8s
Downloading common tools...                                         0.8s
Downloading darwin-x64 tools...                                     2.4s
Running "flutter pub get" in mobile...                              1.2s
Building app.eurovision.mobile for device
(ios-release)...
 
Automatically signing iOS for device deployment using
specified development team in Xcode project: U4KM65Y22D
Running pod install...                                             76.9s
Running Xcode build...                                                  
                                                   
 ├─Building Dart code...                                    48.5s
 ├─Generating dSYM file...                                   0.9s
 ├─Stripping debug symbols...                                0.8s
 ├─Assembling Flutter resources...                           1.7s
 └─Compiling, linking and signing...                        26.6s
Xcode build done.
93.3s
Built
/Users/jimmyff/Development/eurovision/mobile/build/ios/
iphoneos/Runner.app.

Terminal will be reused by tasks, press any key to close it.

```
here is the output in Xcode when i run the build in simulator:

```
2020-03-10 11:10:58.834239+0000 Runner[4179:1642075]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2020-03-10 11:10:59.415293+0000 Runner[4179:1641680] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
2020-03-10 11:10:59.499912+0000 Runner[4179:1641680] Configuring the default Firebase app...
2020-03-10 11:10:59.525122+0000 Runner[4179:1641680] Configured the default Firebase app __FIRAPP_DEFAULT.
2020-03-10 11:10:59.558026+0000 Runner[4179:1642114] flutter: Observatory listening on http://127.0.0.1:56815/UqhFW6iRYKw=/
2020-03-10 11:10:59.559520+0000 Runner[4179:1642101] [VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
2020-03-10 11:10:59.559699+0000 Runner[4179:1642101] [VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.
2020-03-10 11:10:59.582555+0000 Runner[4179:1642073] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-03-10 11:10:59.582560+0000 Runner[4179:1642143] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-03-10 11:10:59.582825+0000 Runner[4179:1642073] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-03-10 11:10:59.584001+0000 Runner[4179:1642143] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-03-10 11:10:59.584036+0000 Runner[4179:1642073] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-03-10 11:10:59.586329+0000 Runner[4179:1642143] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-03-10 11:10:59.586384+0000 Runner[4179:1642073] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-03-10 11:10:59.634044+0000 Runner[4179:1642075] 6.10.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
2020-03-10 11:11:00.195374+0000 Runner[4179:1642076] 6.10.0 - [Firebase/Analytics][I-ACS025028] AdMob and Firebase are in use in this app, but are not linked. For analytics data consistency and integrity, it is highly recommended that you link your AdMob app to the corresponding Firebase app and re-download the GoogleServices-Info.plist file. See https://support.google.com/admob/answer/6383165 for more information.
2020-03-10 11:11:00.198546+0000 Runner[4179:1642076] 6.10.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60103000 started
2020-03-10 11:11:00.200059+0000 Runner[4179:1642076] 6.10.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-03-10 11:11:00.236079+0000 Runner[4179:1642076] 6.10.0 - [Firebase/Analytics][I-ACS025026] Deferring to Firebase for event data collection
```

Just to check I wasn't going mad and I'd done something wrong, I switched back to the dev channel, clean, upgrade, build and the app now worked however it has the red debug banner.

It's worth mentioning that this app is currently released on the android play store and the release version does not have the debug banner!

**Comment by jmagman** [comment] 2020-03-10 23:58
Duplicate of https://github.com/flutter/flutter/issues/51673 (see https://github.com/flutter/flutter/issues/51673#issuecomment-597215128)

**Closed by jmagman** 2020-03-10 23:58 UTC
Labels: a: release, framework, ⌺‬ platform-ios
