### ISSUE TITLE
Microsoft.CppCommon.targets(234,5): error MSB6006: "cmd.exe" in flutter desktop.

### ISSUE THREAD

**Issue by Hadi7546** [flutter/flutter#75345] opened 2021-02-03 18:28 UTC
Hy.

im after runing ```flutter run -d windows```:
```
E:\App\VS\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): error MSB6006: "cmd.exe" exited with code 1. [E:\HADI Folder\Documents\Programming\Flutter\sms_bomber\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Exception: Build process failed.
```

flutter doctor: 
```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.124, on Microsoft Windows [Version 10.0.19042.746], locale fa-IR)
    • Flutter version 1.26.0-18.0.pre.124 at E:\SDKs\flutter
    • Framework revision 0a4618943c (2 days ago), 2021-02-02 14:56:03 +0800
    • Engine revision bb2bbde4d0
    • Dart version 2.12.0 (build 2.12.0-279.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\SDKs\Android\android-sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = E:\SDKs\Android\android-sdk
    • ANDROID_SDK_ROOT = E:\SDKs\Android\android-sdk\tools
    • Java binary at: C:\Program Files\Java\jre1.8.0_271\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.7.0)
    • Visual Studio at E:\App\VS
    • Visual Studio Enterprise 2019 version 16.7.30330.147
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.56

! Doctor found issues in 1 category.
```

Please Help me!!!!

**Comment by TahaTesser** [comment] 2021-02-04 08:47
Hi @Hadi7546 
This is caused by a space in your path to project
` [E:\HADI Folder\Documents\Programming\Flutter\sms_bomber\build\windows\flutter\flutter_assemble.vcxproj]` 
`HADI  FOLDER`, rename it to `HADI-FOLDER` or `HAD_FOLDER` and try with `futter clean` and then `flutter run -d windows`.
Hope this helps.

If the problem persists, Can you please provide flutter run -d windows --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Hadi7546** [comment] 2021-02-05 20:50
> Hi @Hadi7546
> This is caused by a space in your path to your project
> ` [E:\HADI Folder\Documents\Programming\Flutter\sms_bomber\build\windows\flutter\flutter_assemble.vcxproj]`
> `HADI FOLDER`, rename it to `HADI-FOLDER` or `HAD_FOLDER` and try with `futter clean` and then `flutter run -d windows`.
> Hope this helps.
> Related to #73644
> 
> If the problem persists, Can you please provide `flutter run -d windows --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

Surprisingly it was done.
I came to the conclusion after running by vscode
Thanks

**Comment by TahaTesser** [comment] 2021-02-08 07:22
Created https://github.com/flutter/flutter/issues/75611 to avoid this
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-02-08 07:22 UTC
Labels: in triage

**Comment by narumishi** [comment] 2021-03-13 15:16
Searched for these similar issues, all of them said it's because of space. But my project path doesn't contain any space. And Visual Studio installation path shouldn't affect?
```
CUSTOMBUILD : error : Cannot run with sound null safety, because the following dependencies [D:\Projects\AndroidStudioProjects\chaldea\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: “D:\Projects\AndroidStudioProjects\chaldea\build\windows\CMakeFiles\2c21de2b84d9b6545c94e8d94db28668\flutter_windows.dll.rule;D:\Projects\AndroidStudioProjects\chaldea\build\windows\CMakeFiles\bcb427c67bf25df9983d6e85816a704a\flutter_assemble.rule”的自定义生成已退出，代码为 1。 
```
I cannot figure out the reason, @TahaTesser could you please give me some idea? thanks!

**Comment by stuartmorgan** [comment] 2021-03-13 15:26
> MSB8066

This is not at all the same error code; your issue is unrelated to this one.

The line above in the output is explaining the cause of your problem. If you run in verbose mode you'll be able to see the list of dependencies that are causing issues for you.

**Comment by narumishi** [comment] 2021-03-13 15:47
@stuartmorgan Thanks to your words, suddenly understand! I just focused on the wrong key point which should be `sound null safety` rather `MSB8066`.
