### ISSUE TITLE
errorBuilder callback of Image.network not invoked when in DecorationImage

### ISSUE THREAD

**Issue by costacoz** [flutter/flutter#105784] opened 2022-06-10 15:50 UTC
Why does `errorBuilder` of `Image.network` not get invoked when in `DecorationImage`?

Instead error that occurs in `Image.network` invokes `onError` of `DecorationImage`. So I cannot substitute failed image with another widget.

Here is the code with this situation. I took the example from the [documentation for errorBuilder](https://api.flutter.dev/flutter/widgets/Image/errorBuilder.html) and amended it so that `Image.network` is in `DecorationImage`. See below:

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: Scaffold(
        body: Center(
          child: MyStatelessWidget(),
        ),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
          color: Colors.white,
          border: Border.all(),
          borderRadius: BorderRadius.circular(20),
          image: DecorationImage(
              onError: (obj, st) {
                  print('ONERROR-ONERROR-ONERROR');
              },
              image: Image.network(
                'https://example.does.not.exist/image.jpg',
                errorBuilder:
                    (BuildContext context, Object exception, StackTrace? stackTrace) {
                  return const Text('ERROR');
                },
              ).image
          )
      ),
      child: const SizedBox(height: 200, width: 200),
    );
  }
}
```

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. See in the console `ONERROR-ONERROR-ONERROR` appeared
3. See that `Image.network` didn't use the callback generated substitution widget.

**Expected results:** widget in callback to be rendered

**Actual results:** widget in callback wasn't rendered, only parent `onError` invoked.

**Comment by jonahwilliams** [comment] 2022-06-10 19:45
Duplicate of https://github.com/flutter/flutter/pull/104569

This will be fixed via https://github.com/flutter/flutter/issues/104580 in the next stable cherry pick

**Closed by jonahwilliams** 2022-06-10 19:45 UTC
