### ISSUE TITLE
In 3.7.0,When running app for the web in html renderer,text widget can't render content correctly with TextOverflow.fade!

### ISSUE THREAD

**Issue by bluealert455** [flutter/flutter#120057] opened 2023-02-06 05:01 UTC
My code like this:
`SizedBox(
                width: 100,
                child: Text(
                  'You have pushed the button this many times:',
                  softWrap: false,
                  overflow: TextOverflow.fade,
                ))`
When I run app by "flutter run -d chrome" ,it's ok.
But, if I add "--web-renderer html" option to the command,the text in Text widget is covered by a color block almostly.
Like this:
https://github.com/bluealert455/text_fade_test/blob/main/error.png

This is test code:
https://github.com/bluealert455/text_fade_test

**Comment by danagbemava-nc** [comment] 2023-02-06 08:56
Hi @bluealert455, see https://github.com/flutter/flutter/issues/71413#issuecomment-921300335.

Closing this as a duplicate of https://github.com/flutter/flutter/issues/48417

**Closed by danagbemava-nc** 2023-02-06 08:56 UTC
Labels: in triage
