### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listUser defaults from command line:    IDEPackageSupportUseBuiltinSCM = YES2023-06-14 11:08:35.550 xcodebuild[21473:207286] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)2023-06-14 11:08:35.580 xcodebuild[21473:207286] Writing error result bundle to /var/folders/y9/jhdrnk497_l48qz5w9kr20jw0000gq/T/ResultBundle_2023-14-06_11-08-0035.xcresultxcodebuild: error: The directory /Users/arunkumar/AndroidStudioProjects/artesian_loyalty/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: xcrun, OS error code: 78

### ISSUE THREAD

**Issue by arundidauli** [flutter/flutter#128852] opened 2023-06-14 05:39 UTC
## Command
```
flutter build ios --flavor prod -t lib/main_prod.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2023-06-14 11:08:35.550 xcodebuild[21473:207286] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
2023-06-14 11:08:35.580 xcodebuild[21473:207286] Writing error result bundle to /var/folders/y9/jhdrnk497_l48qz5w9kr20jw0000gq/T/ResultBundle_2023-14-06_11-08-0035.xcresult
xcodebuild: error: The directory /Users/arunkumar/AndroidStudioProjects/artesian_loyalty/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: xcrun, OS error code: 78
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:278:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:321:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/xcode_project.dart:325:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/xcode_project.dart:285:36)
<asynchronous suspension>
#5      IosProject._parseHostAppBundleName (package:flutter_tools/src/xcode_project.dart:261:55)
<asynchronous suspension>
#6      IosProject.hostAppBundleName (package:flutter_tools/src/xcode_project.dart:250:35)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:116:39)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:82:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp.<anonymous closure> (package:flutter_tools/src/commands/build_ios.dart:604:34)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:641:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-x64, locale en-GB)
    [32m•[39m Flutter version 3.10.2 on channel stable at /Users/arunkumar/Downloads/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 9cd

**Comment by darshankawar** [comment] 2023-06-14 06:58
> xcodebuild: error: The directory /Users/arunkumar/AndroidStudioProjects/artesian_loyalty/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: xcrun, OS error code: 78

@arundidauli As this line of the log indicates, it seems you have multiple copies of .xcodeproj file in ios sub-directory. The flutter build process correctly detected it and presented the error as mentioned, so the build process is working properly. The error seems to be in your project config / setup that you need to revisit and remove any duplicate project files.

Closing, as this is not a bug.

**Closed by darshankawar** 2023-06-14 06:58 UTC
Labels: in triage
