### ISSUE TITLE
Gesture detection when transform matrix is applied

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#73701] opened 2021-01-11 11:37 UTC
I can't seem get proper gesture detection when applying a Matrix to a widget. My best guess is that it has something to do with FractionallySizedBox and transform matrix. 

![ezgif-7-bfad5fcd6145](https://user-images.githubusercontent.com/9283414/104177801-067e0a00-5412-11eb-9c2c-c37789a5a88b.gif)

Here is a MCVE:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final Size size = MediaQuery.of(context).size;
    final double scaleFactor = size.aspectRatio;
    final Matrix4 matrix = Matrix4.diagonal3Values(scaleFactor, scaleFactor, 1.0);
    return Scaffold(
      backgroundColor: Colors.red.shade100,
      body: Center(
        child: Container(
          width: size.width,
          height: size.height * scaleFactor,
          padding: const EdgeInsets.symmetric(horizontal: 16.0),
          child: Container(
            transform: matrix,
            child: FractionallySizedBox(
              widthFactor: 1 / scaleFactor,
              heightFactor: 1 / scaleFactor,
              alignment: AlignmentDirectional.topStart,
              child: Row(
                children: <Widget>[
                  Expanded(
                    child: Container(
                      width: size.width,
                      height: size.height,
                      child: const Page(
                        title: 'PageA',
                      ),
                    ),
                  ),
                  const SizedBox(width: 16.0),
                  Expanded(
                    child: Container(
                      width: size.width,
                      height: size.height,
                      child: const Page(
                        title: 'PageB',
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class Page extends StatelessWidget {
  const Page({Key key, @required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: FlatButton(
        child: const Text('Press me'),
        onPressed: () {
          print('$title onPressed');
        },
      ),
    );
  }
}
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on Mac OS X 10.15.6 19G2005 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (4 available)

• No issues found!
```

Maybe related to https://github.com/flutter/flutter/issues/6606#issuecomment-257446632

**Comment by darshankawar** [comment] 2021-01-11 13:09
@long1eu 
From your code sample, if I comment out `transform.matrix` line, the tap gesture is detected for PageB:

```
flutter: PageA onPressed
flutter: PageB onPressed
flutter: PageB onPressed
```

From the issue comment your referred above, it states that:

`The transform is applied to the hit-testing as well, but it transforms the box into the overflow of the container, so the parent doesn't think you're hitting it and so doesn't check the children.
`
From the underlying comments of that issue, it seems to be the intended behavior. https://github.com/flutter/flutter/issues/6606#issuecomment-258228526

I am going ahead and closing this as WAI. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-01-11 13:09 UTC

**Comment by long1eu** [comment] 2021-01-11 13:11
I definitely disagree. This is a bug.

**Comment by long1eu** [comment] 2021-01-11 13:51
I've managed to solve the issue with FittedBox.

```dart
// File created by
// Lung Razvan <long1eu>
// on 11/01/2021

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final Size size = MediaQuery.of(context).size;

    return Scaffold(
      backgroundColor: Colors.red.shade100,
      body: FittedBox(
        alignment: AlignmentDirectional.center,
        child: SizedBox(
          width: size.width * 2 + 16,
          height: size.height,
          child: Row(
            children: const <Widget>[
              Expanded(
                child: Page(
                  title: 'PageA',
                ),
              ),
              SizedBox(width: 16.0),
              Expanded(
                child: Page(
                  title: 'PageB',
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class Page extends StatelessWidget {
  const Page({Key key, @required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: FlatButton(
        child: const Text('Press me'),
        onPressed: () {
          print('$title onPressed');
        },
      ),
    );
  }
}
```

Thanks @slightfoot
