### ISSUE TITLE
[web][windows] Crash when inputing an emoji

### ISSUE THREAD

**Issue by angelosilvestre** [flutter/flutter#141186] opened 2024-01-09 18:21 UTC
### Steps to reproduce

1. Run the sample code on web, on windows.
2. Tap on the textfield to give it focus
3. Press Windows logo key  + . (period)
4. Select an emoji and hit ENTER

### Expected results

The selected emoji is inserted in the textfield

### Actual results

The emoji in inserted, but the following exception happens:

```console
Error: Assertion failed: file:///c:/git/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart:512:16
_pressedKeys[event.physicalKey] == event.logicalKey
"A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#fd285(physicalKey: PhysicalKeyboardKey#700e3(usbHidUsage: \"0x000700e3\", debugName: \"Meta Left\"), logicalKey: LogicalKeyboardKey#602a3(keyId: \"0x10000070f\", keyLabel: \"Process\", debugName: \"Process\"), character: null, timeStamp: 0:00:28.422599, synthesized) and the recorded logical key LogicalKeyboardKey#4b191(keyId: \"0x200000106\", keyLabel: \"Meta Left\", debugName: \"Meta Left\")"
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3        assertFailed
packages/flutter/src/services/hardware_keyboard.dart 512:56                       <fn>
packages/flutter/src/services/hardware_keyboard.dart 519:14                       [_assertEventIsRegular]
packages/flutter/src/services/hardware_keyboard.dart 643:5                        handleKeyEvent
packages/flutter/src/services/hardware_keyboard.dart 1087:11                      handleKeyData
lib/_engine/engine/platform_dispatcher.dart 315:33                                <fn>
lib/_engine/engine/platform_dispatcher.dart 1346:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 314:7                                 invokeOnKeyData
lib/_engine/engine/keyboard_binding.dart 164:30                                   [_onKeyData]
lib/_engine/engine/keyboard_binding.dart 584:36                                   <fn>
lib/_engine/engine/keyboard_binding.dart 462:11                                   [_handleEvent]
lib/_engine/engine/keyboard_binding.dart 587:7                                    handleEvent
lib/_engine/engine/keyboard_binding.dart 98:7                                     <fn>
lib/_engine/engine/keyboard_binding.dart 143:9                                    loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39  dcall
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/7597082/a6cf7a14-315b-4702-8230-eef272c5cc0c

</details>

### Logs

<details open><summary>Logs</summary>

```console
No other relevant output
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.18.0-19.0.pre.125, on Microsoft Windows [versÆo 10.0.22000.2538], locale pt-BR)
    • Flutter version 3.18.0-19.0.pre.125 on channel master at c:\git\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 126302dfb4 (2 hours ago), 2024-01-09 11:45:07 -0500
    • Engine revision b3c8597df0
    • Dart version 3.4.0 (build 3.4.0-9.0.dev)
    • DevTools version 2.31.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\angelo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.85.1)
    • VS Code at C:\Users\angelo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.200
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.121

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-01-10 07:31
Hi @angelosilvestre, does this occur for you 100% of the time? I attempted the steps to reproduce but I do not see any errors in my console after selecting and emoji and hitting enter

**Comment by angelosilvestre** [comment] 2024-01-13 16:26
@danagbemava-nc Yes, I modified the PR description to include a video.

**Comment by huycozy** [comment] 2024-01-15 05:01
@angelosilvestre I checked this on my previous master channel `3.18.0-18.0.pre.47` and the latest master `3.19.0-5.0.pre.45` but the issue is not reproduced (checking on Windows 10):

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/cb8cfb77-ec69-45d0-a8d4-5f928e931d1b
</details>

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.16.7 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (3 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio Hedgehog\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android StudioGiraffe
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio Hedgehog
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.19.0-5.0.pre.45, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.19.0-5.0.pre.45 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at C:\WIP\flutter_master.
      Consider adding C:\WIP\flutter_master\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK checkout at C:\WIP\flutter_master.
      Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8e94423e6a (3 hours ago), 2024-01-15 01:53:26 +0000
    • Engine revision f20657354d
    • Dart version 3.4.0 (build 3.4.0-24.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio Hedgehog\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android StudioGiraffe
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio Hedgehog
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Could you also check this on Windows app target to see if the issue occurs there? 

Also, looks like you are using Windows 11. Maybe this is an OS-specific issue; my other Windows 11 machine is not available now, but I will check this issue on it when it is.

**Comment by angelosilvestre** [comment] 2024-01-15 12:18
@huycozy This issue doesn't happen using windows app as the target. Only happens on the web target.

**Comment by huycozy** [comment] 2024-01-16 05:00
I just checked this on my Windows 11 machine but the issue is not reproduced there as well (on web target platform).  I also tried with Portuguese (Brazil) as yours: keyboard input source or browser language but still can reproduce this. 

<details>
<summary>flutter doctor -v (stable and master - Windows 11)</summary>

```bash
[!] Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.16.7 on channel stable at C:\WORKING\SDK\flutter
    ! Warning: `flutter` on your path resolves to C:\Aliases\flutter.bat, which is not inside your current Flutter SDK checkout at C:\WORKING\SDK\flutter. Consider adding
      C:\WORKING\SDK\flutter\bin to the front of your path.
    ! The dart binary is not on your path. Consider adding C:\WORKING\SDK\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (4 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\huynq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

```bash
[!] Flutter (Channel master, 3.19.0-5.0.pre.45, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.19.0-5.0.pre.45 on channel master at C:\WORKING\SDK\flutter_master
    ! Warning: `flutter` on your path resolves to C:\Aliases\flutter.bat, which is not inside your current Flutter SDK checkout at C:\WORKING\SDK\flutter_master. Consider
      adding C:\WORKING\SDK\flutter_master\bin to the front of your path.
    ! The dart binary is not on your path. Consider adding C:\WORKING\SDK\flutter_master\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8e94423e6a (25 hours ago), 2024-01-15 01:53:26 +0000
    • Engine revision f20657354d
    • Dart version 3.4.0 (build 3.4.0-24.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\huynq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```
</details>

Labeling this for other's insights.

**Comment by htoor3** [comment] 2024-01-18 18:36
Possibly related to https://github.com/flutter/flutter/issues/126247.  Will look into this further to see if it needs a de-dupe, but it's interesting that this is only happening on windows web

**Comment by bleroux** [comment] 2024-01-23 16:09
> Possibly related to https://github.com/flutter/flutter/issues/126247.

@htoor3 Can you have a look to https://github.com/flutter/engine/pull/49087? It fixes https://github.com/flutter/flutter/issues/126247 so it might also fix this one.

**Comment by bleroux** [comment] 2024-01-24 06:36
@angelosilvestre https://github.com/flutter/engine/pull/49087 has landed, thank you to check if this issue is still reproducible on master.

**Comment by angelosilvestre** [comment] 2024-01-24 23:50
Hi @bleroux, thanks for looking into this. Now I'm getting a different exception:


```console
The following assertion was thrown during a platform message callback:
Assertion failed:
file:///c:/git/flutter/packages/flutter/lib/src/services/raw_keyboard.dart:8
65:7
event is! RawKeyDownEvent || _keysPressed.isNotEmpty
"Attempted to send a key down event when no keys are in keysPressed. This
state can occur if the key
event being sent doesn't properly set its modifier flags. This was the
event:
RawKeyDownEvent#f3ebb(logicalKey: LogicalKeyboardKey#602a3(keyId:
\"0x10000070f\", keyLabel:
\"Process\", debugName: \"Process\"), physicalKey:
PhysicalKeyboardKey#700e3(usbHidUsage:
\"0x000700e3\", debugName: \"Meta Left\"), repeat: true) and its data:
RawKeyEventDataWeb#ad93c(code: MetaLeft, key: Process, location: 1,
metaState: 0, keyCode: 229)"

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 328:3
throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3
assertFailed
packages/flutter/src/services/raw_keyboard.dart 865:49
handleRawKeyEvent
packages/flutter/src/services/hardware_keyboard.dart 1164:30
handleRawKeyMessage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54
runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5
_async
packages/flutter/src/services/hardware_keyboard.dart 1136:51
handleRawKeyMessage
packages/flutter/src/services/platform_channel.dart 235:49
<fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54
runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5
_async
packages/flutter/src/services/platform_channel.dart 234:58
<fn>
packages/flutter/src/services/binding.dart 603:35
<fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54
runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5
_async
packages/flutter/src/services/binding.dart 600:98
<fn>
lib/_engine/engine/platform_dispatcher.dart 1377:5
invoke2
lib/ui/channel_buffers.dart 25:12
invoke
lib/ui/channel_buffers.dart 65:7
push
lib/ui/channel_buffers.dart 131:16
push
lib/_engine/engine/platform_dispatcher.dart 421:10
invokeOnPlatformMessage
lib/_engine/engine/raw_keyboard.dart 131:30
handleHtmlEvent
lib/_engine/engine/keyboard_binding.dart 99:29
<fn>
lib/_engine/engine/keyboard_binding.dart 143:9
loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart
550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart
555:39  dcall
```

<details><summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 3.19.0-9.0.pre.128, on Microsoft Windows
    [versÆo 10.0.22000.2538], locale pt-BR)
    • Flutter version 3.19.0-9.0.pre.128 on channel master at c:\git\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 990e2a562b (2 hours ago), 2024-01-24 16:56:33 -0500
    • Engine revision ed498f111d
    • Dart version 3.4.0 (build 3.4.0-68.0.dev)
    • DevTools version 2.31.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0)
    • Android SDK at C:\Users\angelo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022
    17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual
      Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.85.1)
    • VS Code at C:\Users\angelo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows
      [versÆo 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome
      120.0.6099.217
    • Edge (web)        • edge    • web-javascript • Microsoft Edge
      120.0.2210.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</summary>

**Comment by bleroux** [comment] 2024-02-12 08:57
@angelosilvestre
Thank for your feedback.
I tried to reproduce this on Win11+Chrome but the emoji panel works without error on my side.
Can you check on master (thank you for synching before)?
If you still get the error, I'm interested in a new stack trace (line numbers might have change) and possibly some details about your OS and chrome version.

**Comment by angelosilvestre** [comment] 2024-02-19 22:27
@bleroux I'm still getting the errors on the latest master branch.

Chrome version: 121.0.6167.185
Windows version: Edição	Windows 11 Home Single Language 21H2 22000.2538


<details><summary>Stack trace</summary>

```console
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Assertion failed:
event is! RawKeyDownEvent || _keysPressed.isNotEmpty
"Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key
event being sent doesn't properly set its modifier flags. This was the event:
RawKeyDownEvent#e8c62(logicalKey: LogicalKeyboardKey#602a3(keyId: \"0x10000070f\", keyLabel:
\"Process\", debugName: \"Process\"), physicalKey: PhysicalKeyboardKey#700e3(usbHidUsage:
\"0x000700e3\", debugName: \"Meta Left\"), repeat: true) and its data:
RawKeyEventDataWeb#f0699(code: MetaLeft, key: Process, location: 1, metaState: 0, keyCode: 229)"
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
packages/flutter/src/services/raw_keyboard.dart 865:49                            handleRawKeyEvent
packages/flutter/src/services/hardware_keyboard.dart 1161:30                      handleRawKeyMessage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/hardware_keyboard.dart 1133:51                      handleRawKeyMessage
packages/flutter/src/services/platform_channel.dart 235:49                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/platform_channel.dart 234:58                        <fn>
packages/flutter/src/services/binding.dart 602:35                                 <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/binding.dart 599:98                                 <fn>
lib/_engine/engine/platform_dispatcher.dart 1421:5                                invoke2
lib/ui/channel_buffers.dart 25:12                                                 invoke
lib/ui/channel_buffers.dart 65:7                                                  push
lib/ui/channel_buffers.dart 131:16                                                push
lib/_engine/engine/platform_dispatcher.dart 467:10                                invokeOnPlatformMessage
lib/_engine/engine/raw_keyboard.dart 131:30                                       handleHtmlEvent
lib/_engine/engine/keyboard_binding.dart 99:29                                    <fn>
lib/_engine/engine/keyboard_binding.dart 143:9                                    loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
════════════════════════════════════════════════════════════════════════════════════════════════════

``` 

</details>

**Closed** 2024-02-21 05:37 UTC
Labels: a: text input, c: crash, engine, platform-web, P2, needs repro info, team-web, triaged-web

**Comment by bleroux** [comment] 2024-02-21 05:44
@angelosilvestre A fix for the exception you got has landed (it is on flutter/engine so let's wait one day that it rolls into flutter/flutter). Because the issue did not repro on my side, I can't check if it is fully fixed or if another exception is thrown. If it is not fixed, we will reopen this issue. Thanks!

**Comment by angelosilvestre** [comment] 2024-02-26 22:17
@bleroux It seems to be fixed. Thanks.
