### ISSUE TITLE
[firebase_auth] FlutterFirebaseAuthPlugin crash! Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod

### ISSUE THREAD

**Issue by nemoryoliver** [flutter/flutter#70813] opened 2020-11-19 04:13 UTC
I've been getting these crashlytics crash reports from my app for a week now I guess.

**Firebase Crashlytics Logs**

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object, io.flutter.plugin.common.MethodChannel$Result)' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object, io.flutter.plugin.common.MethodChannel$Result)' on a null object reference
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.a(FlutterFirebaseAuthPlugin.java:25)
       at io.flutter.plugins.firebase.auth.-$$Lambda$FlutterFirebaseAuthPlugin$tWHRqndMAmD1Pw4Ghd6GrE-h3DA.onAuthStateChanged(-.java:4)
       at com.google.firebase.auth.zzh.run(zzh.java:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage(zzj.java)
       at android.os.Looper.loop(Looper.java:230)
       at android.app.ActivityThread.main(ActivityThread.java:7836)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Flutter Doctor**

```
✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-PH)
    • Flutter version 1.22.4 at /Users/nemoryoliver/Development/flutter
    • Framework revision 1aafb3a8b9 (5 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/nemoryoliver/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/nemoryoliver/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • IN2010 (mobile)          • 022666eb                                 • android-arm64 • Android 11 (API 30)
    • Oliver’s iPhone (mobile) • b3d99ff4ed9f1a1a3aa41eb597b33b6ddc7d2752 • ios           • iOS 13.7

! Doctor found issues in 1 category.
```

**pubspec.yaml**

```
environment:
  sdk: ">=2.9.0-13.0 <3.0.0" # DART SDK VERSION
  # flutter: ">=1.22.0 <2.0.0" # FLUTTER SDK VERSION

dependencies:
  flutter:
    sdk: flutter

  #FIREBASE
  firebase_core: 0.5.2
  firebase_auth: 0.18.3
  firebase_remote_config: 0.4.2
  firebase_admob: 0.10.2
  flutter_native_admob: 2.1.0+3
  firebase_analytics: 6.2.0
  firebase_performance: 0.4.2
  cloud_firestore: 0.14.3
  firebase_database: 4.3.0
  firebase_crashlytics: 0.2.3
  firebase_in_app_messaging: 0.2.2
  firebase_messaging: 7.0.3
  #INFO
  device_info: 1.0.0
  package_info: 0.4.3+2
  #SOCIAL
  google_sign_in: 4.5.6
  flutter_facebook_login: 3.0.0 # switch to flutter_facebook_auth
  flutter_twitter_login: # switch to newer package
    git: https://github.com/deckerst/flutter_twitter_login
  #MEDIA
  chewie: 0.12.0 # switch to better_player or flutter_playout
  youtube_player_flutter: 7.0.0+7
  cached_network_image: 2.3.3
  flutter_cache_manager: 1.4.2
  photo_view: 0.10.3
  flutter_spinkit: 4.1.2+1
  flutter_icons: 1.1.0
  transparent_image: 1.0.0
  #FILE
  path_provider: 1.6.24
  path_provider_ex:
    git: https://github.com/AmudAnan/flutter_path_provider_ex
  path: 1.7.0
  file_picker: 2.0.13
  ext_storage: 1.0.3
  image_gallery_saver: 1.6.5
  #NETWORK
  dio: 3.0.10
  dio_cookie_manager: 1.0.0
  connectivity: 2.0.2
  #SECURITY
  flutter_screen_lock: 1.2.4
  local_auth: 0.6.3+4
  crypto: 2.1.5
  encrypt: 4.1.0
  #LOCATION
  location: 3.1.0
  geocoding: 1.0.5
  #UTILS
  get: 3.17.1
  get_storage: 1.3.2
  background_fetch: 0.6.0
  supercharged: 1.11.1
  either_option: 1.0.6
  in_app_review: 1.0.3
  # in_app_update: 1.1.7
  app_settings: 4.0.4
  flutter_local_notifications: 3.0.1+4
  hive: 1.4.4+1
  hive_flutter: 0.3.1
  purchases_flutter: 1.4.3 #revenuecat
  url_launcher: 5.7.10
  timeago: 2.0.28
  uuid: 2.2.2
  random_string: 2.1.0
  flutter_user_agent: 1.2.2
  logger: 0.9.4
  share: 0.6.5+4
  tuple: 1.0.3
  validators: 2.0.1
  permission_handler: 5.0.1+1
  flutter_email_sender: 3.0.1
  intl: 0.16.1
  http_parser: 3.1.4
  # WEBVIEW
  webview_flutter: 1.0.7
  flutter_inappwebview: 4.0.0+4 # for voice/video calling on android
  webview_cookie_manager: 1.0.4
  #USER INTERFACE
  flutter_linkify: 4.0.2
  pull_to_refresh: 1.6.3 # use flutter_easyrefresh
  simple_animations: 2.2.3
  google_fonts: 1.1.1
  bubble_tab_indicator: 0.1.4
  step_progress_indicator: 0.2.4+7
  badges: 1.1.4
  shimmer: 1.1.2
  flutter_rating_bar: 3.2.0

# DEVELOPER DEPENDENCIES
dev_dependencies:
  build_runner: 1.10.4
  flutter_launcher_icons: 0.8.1
  hive_generator: 0.8.2
  flutter_native_splash: 0.1.9
```

**android/build.gradle**

```
buildscript {
    ext.kotlin_version = '1.4.10'
    
    // background fetch
    ext {
        compileSdkVersion = 29
        targetSdkVersion = 29
        appCompatVersion = "1.1.0"
    }

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4' // Google Services
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1' // Firebase Crashlytics
    }
}

allprojects {
    repositories {
        google()
        jcenter()
         // background fetch
        maven { 
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**app/build.gradle**

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.firebase.crashlytics' // crashlytics

apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion rootProject.ext.compileSdkVersion // background fetch

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        // checkReleaseBuilds false
    }

    defaultConfig {
        minSdkVersion 19 // for webview_flutter
        targetSdkVersion rootProject.ext.targetSdkVersion // background fetch
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            useProguard false
        }

        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions "app"
    productFlavors {
        bluer {
            dimension "app"
            applicationId "com.nemorystudios.android.bluer.facebook"
            versionCode 102
            versionName "2.0.7"
            resValue "string", "app_name", "Bluer"
        }

        bluerDebugMode {
            dimension "app"
            applicationId "com.nemorystudios.android.bluer.facebook.debug"
            versionCode 1
            versionName "1.0.0"
            resValue "string", "app_name", "Bluer Debug"
        }

        noseen {
            dimension "app"
            applicationId "com.stackwares.android.noseen.facebook"
            versionCode 163
            versionName "3.9.7"
        }

        savestory {
            dimension "app"
            applicationId "com.stackwares.android.storysaver.facebook"
            versionCode 138
            versionName "2.0.7"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'com.android.installreferrer:installreferrer:2.1'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.google.android.play:core:1.8.3' // in app review/update
    implementation 'com.google.firebase:firebase-messaging:21.0.0'
    // fix for: https://github.com/FirebaseExtended/flutterfire/issues/4090
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    // fix for: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules
    implementation "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"
    // background fetch
    androidTestImplementation 'androidx.test:runner:1.3.0'                   // or higher
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'   // or higher
}
```

**Comment by sidrao2006** [comment] 2020-11-19 09:30
Hey @nemoryoliver ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with firebase, please close this issue and open it [here](https://github.com/FirebaseExtended/flutterfire/issues) instead.

Thanks

**Comment by pedromassangocode** [comment] 2020-11-19 10:14
Hi @nemoryoliver 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-19 10:14 UTC
