### ISSUE TITLE
 ios14   CupertinoTime selector 

### ISSUE THREAD

**Issue by jahnli** [flutter/flutter#87631] opened 2021-08-04 06:56 UTC
## Proposal

Currently, the selector takes up a lot of space
Supports the new CupertinoTime Selector

![image](https://user-images.githubusercontent.com/20943608/128135620-51477980-fc65-41d3-8261-6d6a2b9ec4a5.png)
![image](https://user-images.githubusercontent.com/20943608/128135799-4f30be59-466d-4cb9-84d3-23e67a0173b0.png)

**Comment by TahaTesser** [comment] 2021-08-04 14:32
Hi @jahnli 
This is already proposed in https://github.com/flutter/flutter/issues/68177, I just updated the issue
Closing as duplicate of https://github.com/flutter/flutter/issues/68177

**Closed by TahaTesser** 2021-08-04 14:32 UTC
Labels: in triage

**Comment by jahnli** [comment] 2021-08-05 00:59
@TahaTesser    When is flutter expected to be supported
