### ISSUE TITLE
Flutter 3.7 never invokes flutter_typehead's onTap callback

### ISSUE THREAD

**Issue by emersion** [flutter/flutter#119092] opened 2023-01-24 23:51 UTC
## Steps to Reproduce

Run the example from the `flutter_typehead` package, from this branch: https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/443

**Expected results:** Focusing the text input and clicking an item should fill the text input.

**Actual results:** Clicking an item does nothing.

This is a 3.7 regression. The `InkWell`'s `onTap` callback is never called.

<details>
  <summary>Logs</summary>

```
[   +5 ms] executing: uname -m
[   +7 ms] Exit code 0 from: uname -m
[        ] x86_64
[        ] executing: [/home/simon/src/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] executing: [/home/simon/src/flutter/] git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[  +10 ms] Exit code 0 from: git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] 3.7.0
[  +11 ms] executing: [/home/simon/src/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/home/simon/src/flutter/] git ls-remote --get-url origin
[   +1 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git
[  +17 ms] executing: [/home/simon/src/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +23 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +61 ms] Skipping pub get: version match.
[  +18 ms] Found plugin flutter_keyboard_visibility at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility-5.4.0/
[   +3 ms] Found plugin flutter_keyboard_visibility_linux at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_linux-1.0.0/
[   +1 ms] Found plugin flutter_keyboard_visibility_macos at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_macos-1.0.0/
[   +2 ms] Found plugin flutter_keyboard_visibility_web at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_web-2.0.0/
[   +1 ms] Found plugin flutter_keyboard_visibility_windows at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_windows-1.0.0/
[  +53 ms] Found plugin flutter_keyboard_visibility at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility-5.4.0/
[        ] Found plugin flutter_keyboard_visibility_linux at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_linux-1.0.0/
[        ] Found plugin flutter_keyboard_visibility_macos at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_macos-1.0.0/
[   +1 ms] Found plugin flutter_keyboard_visibility_web at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_web-2.0.0/
[        ] Found plugin flutter_keyboard_visibility_windows at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_windows-1.0.0/
[  +67 ms] Generating /home/simon/src/flutter_typeahead/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +64 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/simon/src/flutter_typeahead/example/.dart_tool/package_config_subset,/home/simon/src/flutter_typeahead/example/.dart_tool/flutter_build/dart_plugin_registrant.dart}
[   +5 ms] Found plugin flutter_keyboard_visibility at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility-5.4.0/
[        ] Found plugin flutter_keyboard_visibility_linux at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_linux-1.0.0/
[        ] Found plugin flutter_keyboard_visibility_macos at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_macos-1.0.0/
[        ] Found plugin flutter_keyboard_visibility_web at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_web-2.0.0/
[        ] Found plugin flutter_keyboard_visibility_windows at /home/simon/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility_windows-1.0.0/
[   +7 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +2 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +3 ms] /home/simon/src/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/simon/src/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /home/simon/src/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.LIXKXL/flutter_tool.WAYMTQ/app.dill --packages /home/simon/src/flutter_typeahead/example/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --source file:///home/simon/src/flutter_typeahead/example/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///home/simon/src/flutter_typeahead/example/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +13 ms] Building Linux application...
[  +12 ms] <- compile package:example/main.dart
[   +1 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/simon/src/flutter_typeahead/example/linux
[  +43 ms] -- Configuring done
[        ] -- Generating done
[        ] -- Build files have been written to: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug
[   +3 ms] executing: ninja -C build/linux/x64/debug install
[   +4 ms] ninja: Entering directory `build/linux/x64/debug'
[+1385 ms] [1/5] Generating /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/simon/src/flutter_typeahead/example/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[        ] [   +7 ms] executing: uname -m
[        ] [   +7 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [        ] executing: [/home/simon/src/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +2 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] [        ] executing: [/home/simon/src/flutter/] git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] [  +10 ms] Exit code 0 from: git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] [        ] 3.7.0
[        ] [  +10 ms] executing: [/home/simon/src/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +11 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +67 ms] executing: [/home/simon/src/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/simon/src/flutter/] git ls-remote --get-url origin
[        ] [   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] git@github.com:flutter/flutter.git
[        ] [        ] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +27 ms] Initializing file store
[        ] [   +4 ms] Done initializing file store
[        ] [  +28 ms] Skipping target: gen_localizations
[        ] [  +11 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +375 ms] Skipping target: unpack_linux
[        ] [ +273 ms] Skipping target: kernel_snapshot
[        ] [ +181 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [   +6 ms] "flutter assemble" took 1,005ms.
[        ] [  +69 ms] ensureAnalyticsSent: 66ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +372 ms] [2/5] Building CXX object CMakeFiles/example.dir/flutter/generated_plugin_registrant.cc.o
[  +38 ms] [3/5] Building CXX object CMakeFiles/example.dir/my_application.cc.o
[ +134 ms] [4/5] Linking CXX executable intermediates_do_not_run/example
[        ] [4/5] Install the project...
[   +5 ms] -- Install configuration: "Debug"
[   +5 ms] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/example
[   +8 ms] -- Set runtime path of "/home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/example" to "$ORIGIN/lib"
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/icudtl.dat
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/shaders
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/shaders/ink_sparkle.frag
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/simon/src/flutter_typeahead/example/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[  +12 ms] Building Linux application... (completed in 2,027ms)
[ +190 ms] Observatory URL on device: http://127.0.0.1:44923/NxEYA03UnsM=/
[   +2 ms] Caching compiled dill
[  +29 ms] Connecting to service protocol: http://127.0.0.1:44923/NxEYA03UnsM=/
[  +88 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:44923/NxEYA03UnsM=/.
[  +43 ms] DDS is listening at http://127.0.0.1:40923/En1hN3c-FGI=/.
[  +36 ms] Successfully connected to service protocol: http://127.0.0.1:44923/NxEYA03UnsM=/
[ +127 ms] DevFS: Creating new filesystem on the device (null)
[   +8 ms] DevFS: Created new filesystem on the device (file:///tmp/exampleKIKUWY/example/)
[   +1 ms] Updating assets
[  +49 ms] Syncing files to device Linux...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:example/main.dart 5995be45-108d-41b0-b1c5-f2c54017bdd3
[        ] <- 5995be45-108d-41b0-b1c5-f2c54017bdd3
[        ] Bundle processing done.
[  +54 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 58ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0x55e2b20253f0.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:40923/En1hN3c-FGI=/
[ +509 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:40923/En1hN3c-FGI=/
[+4263 ms] Application finished.
```

```
Analyzing example...                                            

   info • 'headline5' is deprecated and shouldn't be used. Use headlineSmall instead. This feature was deprecated after
          v3.1.0-0.0.pre • lib/material_app.dart:167:50 • deprecated_member_use
   info • 'subtitle1' is deprecated and shouldn't be used. Use titleMedium instead. This feature was deprecated after
          v3.1.0-0.0.pre • lib/material_app.dart:171:50 • deprecated_member_use

2 issues found. (ran in 5.6s)
```

```
[!] Flutter (Channel stable, 3.7.0, on Arch Linux 6.1.6-arch1-3, locale en_US.UTF-8)
    • Flutter version 3.7.0 on channel stable at /home/simon/src/flutter
    ! The dart binary is not on your path. Consider adding /home/simon/src/flutter/bin to your path.
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision b06b8b2710 (23 hours ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/simon/.Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.25.2
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[!] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 70.1.3
    • Dart plugin version 213.7433
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Arch Linux 6.1.6-arch1-3

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

(Maybe related: #119054)

**Comment by danagbemava-nc** [comment] 2023-01-25 08:40
Hi @emersion, kindly report this on the `flutter_typeahead` repo so they can investigate and come up with a minimal reproducible code sample. It could be an issue with how they're doing their implementation. 

I tested the [Autocomplete](https://api.flutter.dev/flutter/material/Autocomplete-class.html) example (which also uses an `InkWell`) and there was no issue there, so the issue may not be related to `InkWell`s

https://github.com/flutter/flutter/issues/119054 also happens on stable 3.3.10, so it's unlikely that they're related. 

I'll be closing this since the issue is in a third-party package and they have their own custom implementation. 

If you could also come up with a minimal sample that reproduces the issue, that would be fine as well. 

Thank you

**Closed by danagbemava-nc** 2023-01-25 08:40 UTC
Labels: in triage
