### ISSUE TITLE
Desktop apps on Linux starting but not displaying anything ("Unable to create a GL context")

### ISSUE THREAD

**Issue by yeedle** [flutter/flutter#76578] opened 2021-02-23 02:43 UTC
When running `flutter run -d linux` the window that opens is empty and in the console the following is printed:

```
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

** (dummy_desktop:10814): WARNING **: Failed to start Flutter renderer: Unable to create a GL context

** (dummy_desktop:10814): WARNING **: Unable to retrieve framework response: No engine to send to
```

## Steps to Reproduce

```
flutter created dummy_desktop && cd dummy_desktop && flutter run -d linux
```
**Expected results:** 
Expected is for the he template app appear.
**Actual results:** 
An empty screen, and the above in the logs.

```
$ flutter run -d linux
[  +62 ms] executing: uname -m
[  +30 ms] Exit code 0 from: uname -m
[   +1 ms] x86_64
[  +14 ms] executing: [/home/yeedle/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[        ] executing: [/home/yeedle/snap/flutter/common/flutter/] git tag --points-at f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[  +13 ms] Exit code 0 from: git tag --points-at f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[        ] 1.27.0-4.0.pre
[  +45 ms] executing: [/home/yeedle/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/yeedle/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +42 ms] executing: [/home/yeedle/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +73 ms] executing: /home/yeedle/Android/Sdk/platform-tools/adb devices -l
[  +23 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +108 ms] executing: /home/yeedle/Android/Sdk/platform-tools/adb devices -l
[  +25 ms] Skipping pub get: version match.
[ +127 ms] Generating /home/yeedle/dummy_desktop/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +102 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +7 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +5 ms] /home/yeedle/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/yeedle/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/yeedle/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.ZDCGRF/flutter_tool.VGCTMT/app.dill --packages /home/yeedle/dummy_desktop/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
[  +33 ms] Building Linux application...
[  +38 ms] <- compile package:dummy_desktop/main.dart
[   +2 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/yeedle/dummy_desktop/linux
[  +12 ms] List of devices attached
[   +3 ms] List of devices attached
[ +100 ms] -- Configuring done
[        ] -- Generating done
[        ] -- Build files have been written to: /home/yeedle/dummy_desktop/build/linux/x64/debug
[   +2 ms] executing: ninja -C build/linux/x64/debug install
[  +13 ms] ninja: Entering directory `build/linux/x64/debug'
[+4833 ms] [1/5] Generating /home/yeedle/dummy_desktop/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/yeedle/dummy_desktop/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +40 ms] [  +84 ms] executing: uname -m
[        ] [  +36 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +14 ms] executing: [/home/yeedle/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[        ] [        ] executing: [/home/yeedle/snap/flutter/common/flutter/] git tag --points-at f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[        ] [  +14 ms] Exit code 0 from: git tag --points-at f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[        ] [        ] 1.27.0-4.0.pre
[        ] [  +51 ms] executing: [/home/yeedle/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/dev
[        ] [        ] executing: [/home/yeedle/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +59 ms] executing: [/home/yeedle/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +87 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [ +124 ms] Initializing file store
[        ] [  +10 ms] Done initializing file store
[   +8 ms] [  +46 ms] Skipping target: gen_localizations
[        ] [+2147 ms] Skipping target: unpack_linux
[        ] [ +540 ms] Skipping target: kernel_snapshot
[        ] [ +391 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [  +28 ms] Done persisting file store
[        ] [   +8 ms] build succeeded.
[        ] [  +18 ms] "flutter assemble" took 3,426ms.
[        ] [ +183 ms] ensureAnalyticsSent: 175ms
[        ] [   +4 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +548 ms] [2/5] Building CXX object CMakeFiles/dummy_desktop.dir/flutter/generated_plugin_registrant.cc.o
[  +25 ms] [3/5] Building CXX object CMakeFiles/dummy_desktop.dir/my_application.cc.o
[ +155 ms] [4/5] Linking CXX executable intermediates_do_not_run/dummy_desktop
[        ] [4/5] Install the project...
[  +21 ms] -- Install configuration: "Debug"
[  +32 ms] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/dummy_desktop
[        ] -- Set runtime path of "/home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/dummy_desktop" to "$ORIGIN/lib"
[        ] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/icudtl.dat
[   +1 ms] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[ +121 ms] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES
[   +1 ms] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +36 ms] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[   +5 ms] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/yeedle/dummy_desktop/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[  +17 ms] Building Linux application... (completed in 6.0s)
[ +162 ms] libGL error: unable to load driver: swrast_dri.so
[        ] libGL error: failed to load driver: swrast
[        ] ** (dummy_desktop:11547): WARNING **: Failed to start Flutter renderer: Unable to create a GL context

```

```
$ flutter analyze
Analyzing dummy_desktop...                                              
No issues found! (ran in 16.1s)

```

```
$ flutter doctor -v
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-4.0.pre at /home/yeedle/snap/flutter/common/flutter
    • Framework revision f8cd24de95 (6 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/yeedle/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/yeedle/Android/Sdk
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```

```
$ uname -a; echo $XDG_SESSION_TYPE; sudo lshw -C display
Linux thinkpad 4.4.0-201-generic #233-Ubuntu SMP Thu Jan 14 06:10:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
x11
[sudo] password for yeedle:         
  *-display               
       description: VGA compatible controller
       product: Skylake GT2 [HD Graphics 520]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915_bpo latency=0
       resources: irq:133 memory:f0000000-f0ffffff memory:e0000000-efffffff ioport:e000(size=64)
```
```
$ cat /etc/issue
elementary OS Loki \n \l
```

```
$ loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type
Type=x11
```

```
$ loginctl show-session
EnableWallMessages=no
NAutoVTs=6
KillExcludeUsers=root
KillUserProcesses=no
RebootToFirmwareSetup=no
IdleHint=no
IdleSinceHint=1614047056603542
IdleSinceHintMonotonic=61321109487
BlockInhibited=handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch
DelayInhibited=sleep
InhibitDelayMaxUSec=30s
HandlePowerKey=poweroff
HandleSuspendKey=suspend
HandleHibernateKey=hibernate
HandleLidSwitch=suspend
HandleLidSwitchDocked=suspend
HoldoffTimeoutUSec=30s
IdleAction=ignore
IdleActionUSec=30min
PreparingForShutdown=no
PreparingForSleep=no
Docked=yes
```

```
$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 18.0.5
```

**Comment by cbracken** [comment] 2021-02-23 18:39
Marking as duplicate of https://github.com/flutter/flutter/issues/76178. @yeedle thanks for filing. Please click the _subscribe_ button to follow that issue.

**Closed by cbracken** 2021-02-23 18:39 UTC
Labels: a: desktop, engine, passed first triage, platform-linux, severe: crash, severe: rendering

**Comment by yeedle** [comment] 2021-02-23 21:20
hey @cbracken, thanks! Do you want me to work with you on answering the questions in that issue?
