### ISSUE TITLE
Updating Flutter and an apps packages as of Feb 2019, broke my app completely.

### ISSUE THREAD

**Issue by kasonde** [flutter/flutter#28038] opened 2019-02-16 06:17 UTC
## Steps to Reproduce
 
1. Create a new app
2. Install permission_handler and geocator
3. watch it fail

**Comment by kangwang1988** [comment] 2019-02-16 09:55
Fail to search geocator in pub.dartlang.org.

Thanks for filing an issue, but I’m going to close it for lack of a description. If you add a comment with details, we’ll reopen the issue.

**Comment by kasonde** [comment] 2019-02-16 10:05
The package is geolocator. That was a previous typo in the original post. 

I didn't think I needed to describe anything because I have added the steps to reproduce. But here goes a little more detail. 

I updated my flutter and ran 'flutter upgrade' in my project. After that, I was not able to run my project. I was getting messages signifying that the build error is because my project is AndroidX compatible. 

After creating a new project, I found that those two packages, which are integral to my project aren't able to run successfully. I don't see why you closed the issue without attempting to perform the error reproduction.

**Comment by kangwang1988** [comment] 2019-02-16 10:08
geolocator is good.
When you say it failed, paste the log for the failure.

**Comment by kangwang1988** [comment] 2019-02-16 11:01
If it's a android x problem, refer to: https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility

**Comment by kasonde** [comment] 2019-02-17 05:18
That link has not been helpful at all. The migration to AndroidX is inconsistent. Some packages work sometimes. It all depends on the combination of how I add them to the pubspec.yaml. Right now this is the error I'm getting with using google_sign_in and google_maps_flutter

D8: Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/177.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/142.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/162.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/128.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/107.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/192.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/129.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/97.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/157.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/89.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/187.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/122.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/137.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/131.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/147.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/152.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/22.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/91.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/130.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/167.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/117.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/90.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/102.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/172.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/88.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/182.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/197.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/127.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/112.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/24.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/32.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/16.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/40.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/31.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/25.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/26.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/17.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/35.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/30.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/12.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/19.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/36.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/41.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/37.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/29.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/38.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/39.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/13.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/34.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/21.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/14.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/27.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/20.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/28.jar, /Users/richard/work/apps/final_smartsaver/smart_saver_zambia/build/app/intermediates/transforms/dexBuilder/debug/15.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by zoechi** [comment] 2019-02-17 14:53
If you use packages that are compatible with AndroidX together with packages that aren't, then it can't work. 
Either you restrict dependency versions to versions that do not depend on AndroidX, or you use only dependency versions that do depend on AndroidX.

I'm closing as duplicate of #27901
Also related to #27829

**Closed by zoechi** 2019-02-17 14:53 UTC
Labels: t: gradle

**Comment by pneves001** [comment] 2019-03-01 23:10
I can second this. I'm going through the same issues as kasonde. My app is completely messed up. Some of my plugins are broken. And I don't have a solution to fix it.
