### ISSUE TITLE
Hot restart isnt closing keyboard

### ISSUE THREAD

**Issue by amanv8060** [flutter/flutter#68030] opened 2020-10-13 16:13 UTC
it might be too minor to  be worked on if its valid issue

1 .create two screens (Page1 with button that naviagates to page2 , Page 2 has a textFormfield)
2. Navigate to page 2 using that button . start typing in that textfield, while the keyboard is open hot restart your app , keyboard doesnt closes 

**Code for reproducing** : https://pastebin.com/zZhhtAX7

**Expected Outcome :** keyboard should also close

**Comment by jonahwilliams** [comment] 2020-10-13 18:19
Duplicate of https://github.com/flutter/flutter/issues/10713

**Closed by jonahwilliams** 2020-10-13 18:19 UTC
Labels: a: text input, framework, t: hot reload

**Comment by amanv8060** [comment] 2020-10-13 18:39
ok
