### ISSUE TITLE
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2): ios simulator

### ISSUE THREAD

**Issue by R3ll36** [flutter/flutter#52052] opened 2020-03-05 21:52 UTC
launching from vscode on ios simulator is getting this error, i've tried delete ios and build folder folder, still the same error:

```
Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           53.8s
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
  Command: /usr/bin/xcrun simctl install 63B396D1-4CDD-4922-B845-166794D46667 /Volumes/Macintosh Data/ragogna/build/ios/iphonesimulator/Runner.app
Exited (sigterm)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F132, locale en-IT)
    • Flutter version 1.12.13+hotfix.8 at /Users/cosminrus/Utils/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cosminrus/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 • 63B396D1-4CDD-4922-B845-166794D46667 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment] 2020-03-06 09:00
@R3ll36 
does `/Volumes/Macintosh Data/ragogna/build/ios/iphonesimulator/Runner.app` exist?

**Comment by R3ll36** [comment] 2020-03-06 13:59
Yes it is, i confirm

**Comment by jmagman** [comment] 2020-03-06 21:37
Duplicate of https://github.com/flutter/flutter/issues/51422.

**Closed by jmagman** 2020-03-06 21:37 UTC
Labels: tool, ⌺‬ platform-ios

**Comment by Dhruv-Garg79** [comment] 2021-01-11 16:15
Did you found any solution? I am currently facing this issue

**Comment by Selast** [comment] 2021-05-23 23:27
Same for me. This error occurred when I added a new extension to my Flutter app

**Comment by jmagman** [comment] 2021-05-24 17:51
This is being tracked in duplicate #51422.  If you are seeing a different problem please file an issue and completely fill out the template.
