### ISSUE TITLE
Flutter project fail to build on iphone , the error message is "ld: library not found for -lcrypto"

### ISSUE THREAD

**Issue by owenchenwifigarden** [flutter/flutter#92706] opened 2021-10-29 07:17 UTC
I just upgrade my flutter project to flutter2.0 yesterday, and I can still built it well on android system, but when I want to build on iphone11(os ver:14.8), it will fail.

Xcode version is 13.1, the error message and flutter doctor screenshot is as below, thanks. 
<img width="268" alt="截圖 2021-10-29 上午11 12 52" src="https://user-images.githubusercontent.com/74166223/139392161-a8b69702-711c-443e-ac17-71307ea1ac91.png">
<img width="986" alt="截圖 2021-10-29 上午11 18 08" src="https://user-images.githubusercontent.com/74166223/139392173-d05bb6db-d0f1-4b05-a5aa-f653cb4408db.png">

**Comment by owenchenwifigarden** [comment] 2021-11-01 02:23
@darshankawar Hi , sorry for replying late.
[podfileAndRunVerbose.zip](https://github.com/flutter/flutter/files/7450377/podfileAndRunVerbose.zip)

Attached as podfile and fluuter run --verbose log, thanks a lot.

**Comment by owenchenwifigarden** [comment] 2021-11-01 02:33
@darshankawar Hi , sorry for replying late.

[podfileAndRunVerbose.zip](https://github.com/flutter/flutter/files/7450414/podfileAndRunVerbose.zip)

Attached as podfile and fluuter run --verbose log, thanks a lot.

**Comment by darshankawar** [comment] 2021-11-01 05:06
the podfile you shared doesn't seem to be correct or complete. Also the verbose log you shared shows the below error due to which it isn't running:

```
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.5.1/lib/
flutter_datetime_picker.dart:311:32: Warning: Operand of null-aware operation
'??' has type 'Color' which excludes null.
[  +11 ms]  - 'Color' is from 'dart:ui'.
[        ]                   color: theme.backgroundColor ?? Colors.white,
[        ]  
```

which is pointing to 3rd party plugin which you need to fix the error it's pointing to. Fix that and see if you still get the same error or not.

**Comment by owenchenwifigarden** [comment] 2021-11-01 06:19
@darshankawar Hi, sorry for the wrong podfile attaching.

I removed the flutter_datetime_picker library, and I still build fail, attached as the new podfile and flutter run --verbose log.

[podfileAndRunVerbose.zip](https://github.com/flutter/flutter/files/7451082/podfileAndRunVerbose.zip)

**Comment by owenchenwifigarden** [comment] 2021-11-02 03:20
[flutter_run_verbose.zip](https://github.com/flutter/flutter/files/7457608/flutter_run_verbose.zip)
@darshankawar I fixed the previous log's error, and now it will still occur "ld: library not found for -lcrypto " error , like the attached file, just let you know the newest result i got, thank you.

**Comment by darshankawar** [comment] 2021-11-02 06:10
@owenchenwifigarden 
Can you also provide `pubspec.yaml` ? The verbose log you shared doesn't seem to contain the `library not found` error in it. Provide the log which shows that error.

**Comment by owenchenwifigarden** [comment] 2021-11-02 07:13
@darshankawar
[pubspec.yaml.zip](https://github.com/flutter/flutter/files/7458493/pubspec.yaml.zip)
 
Thanks .

**Comment by owenchenwifigarden** [comment] 2021-11-02 07:47
[verbose.zip](https://github.com/flutter/flutter/files/7458720/verbose.zip)
@darshankawar verbose log I just create if needed.

**Comment by darshankawar** [comment] 2021-11-03 05:15
@owenchenwifigarden 
```

`/Users/owen/dev/ultronApp/build/ios/Debug-iphoneos/Runner.app/Runner
                        ld: library not found for -lcrypto
                        clang: error: linker command failed with exit code 1`
```

which is pointing to dart package you are using https://pub.dev/packages/crypto, and you may need to reach out in dedicated repo for it: https://github.com/dart-lang/crypto/issues

**Comment by owenchenwifigarden** [comment] 2021-11-03 06:33
@darshankawar Ok, I have done it, thanks you so much for helping.

**Comment by natebosch** [comment] 2021-11-04 00:42
> which is pointing to dart package you are using https://pub.dev/packages/crypto, and you may need to reach out in

`-lcrypt` does not point to `package:crypto`.

`package:crypto` is a pure dart library and `clang` does not compile or link it.

**Comment by darshankawar** [comment] 2021-11-04 06:06
@owenchenwifigarden 
If you open the same project from xcode (Runner.xcworkspace) and try to run, does it work properly ?
If not, can you provide the xcode build logs ?

**Comment by owenchenwifigarden** [comment] 2021-11-04 12:04
@darshankawar Hi, I think I didn't upgrate to flutter 2 properly and I did it again today, "ld: library not found for -lcrypto" do not show right now.

However, now I got some errors such as "ld: framework not found FIRAnalyticsConnector", not only this one.

I find the solution tells that I need to remove the library inside the Xcode build setting "Other Linker Flag", the image show how many libs I have deleted.
<img width="1081" alt="截圖 2021-11-04 下午7 56 27" src="https://user-images.githubusercontent.com/74166223/140310209-5e48090b-344a-42a2-98bf-b61320decc52.png">

Is this a good way to fix this ? Thanks.

**Comment by darshankawar** [comment] 2021-11-05 05:14
@owenchenwifigarden 
From above screenshot, you seem to be opening `Runner.xcodeproj`, but usually you should open `Runner.xcworkspace` and try again. Also make sure you run `pod install`, then `pod repo update` or `pod deintegrate` and then `pod install `, `pod repo update` to see if it works, because as you said your upgrade didn't work properly, so that could be the cause as why you are seeing such issues.
With that said, it seems to be due to an incomplete upgrade and not necessarily a framework issue, so I am going ahead and closing it. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-11-05 05:14 UTC
Labels: in triage

**Comment by owenchenwifigarden** [comment] 2021-11-05 07:39
@darshankawar Hi, I'm so sorry for keeping bothering you. I did what you taught (pod deintegrate and then pod install , pod repo update), and I tried to build by Runner.xcworkspace the  with Xcode , it still showed the message "ld: framework not found FIRAnalyticsConnector" as follow image,
![image](https://user-images.githubusercontent.com/74166223/140474994-5f832ced-b038-4e02-bf18-0fe46c50fa9d.png)

I'm so confused with it, and sorry again.
