### ISSUE TITLE
App crashes on latest master on Samsung Fold (SM F907B) and Samsung Tab S6 on startup

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#89537] opened 2021-09-06 09:38 UTC
So far this happened only on this two devices, but my hunch is that it will happen on any Android device that supports multiple users. It also doesn't happen with every app, so I can't provide a reproduction project. 
The same code works without any problems with the current stable channel.
This is a serious problem because our production app needs to run on this sort devices.

```
Connecting to VM Service at ws://127.0.0.1:56320/H6XoPaKScfs=/ws
E/flutter (11964): [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.SecurityException: Permission Denial: broadcast from android asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
E/flutter (11964): 	at android.os.Parcel.createException(Parcel.java:1966)
E/flutter (11964): 	at android.os.Parcel.readException(Parcel.java:1934)
E/flutter (11964): 	at android.os.Parcel.readException(Parcel.java:1884)
E/flutter (11964): 	at android.app.IActivityManager$Stub$Proxy.reportActivityFullyDrawn(IActivityManager.java:7304)
E/flutter (11964): 	at android.app.Activity.reportFullyDrawn(Activity.java:2092)
E/flutter (11964): 	at io.flutter.embedding.android.FlutterActivity.onFlutterUiDisplayed(FlutterActivity.java:1100)
E/flutter (11964): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$1.onFlutterUiDisplayed(FlutterActivityAndFragmentDelegate.java:88)
E/flutter (11964): 	at io.flutter.embedding.android.FlutterView$2.onFlutterUiDisplayed(FlutterView.java:133)
E/flutter (11964): 	at io.flutter.embedding.engine.FlutterJNI.onFirstFrame(FlutterJNI.java:462)
E/flutter (11964): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (11964): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (11964): 	at android.os.Looper.loop(Looper.java:181)
E/flutter (11964): 	at android.app.ActivityThread.main(ActivityThread.java:7168)
E/flutter (11964): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11964): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/flutter (11964): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/flutter (11964): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter (11964): 	at com.android.server.am.UserController.handleIncomingUser(UserController.java:1827)
E/flutter (11964): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:26096)
E/flutter (11964): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:26027)
E/flutter (11964): 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:26897)
E/flutter (11964): 	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1264)
2
E/flutter (11964):
F/flutter (11964): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1220)] Check failed: fml::jni::CheckException(env).
F/libc    (11964): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 11964 (.aaronia.aartos), pid 11964 (.aaronia.aartos)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/winnerxeea/winner:9/PPR1.180610.011/F907BXXU2ASK9:user/release-keys'
Revision: '7'
ABI: 'arm64'
pid: 11964, tid: 11964, name: .aaronia.aartos  >>> de.aaronia.aartos <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1220)] Check failed: fml::jni::CheckException(env).
'
    x0  0000000000000000  x1  0000000000002ebc  x2  0000000000000006  x3  0000000000000008
    x4  0000008000000000  x5  0000008000000000  x6  0000008000000000  x7  0000000080000000
    x8  0000000000000083  x9  a522a3518ff4218b  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 0000000000000020  x14 ffffffffffffffff  x15 0000582da62a1a32
    x16 00000076380e1298  x17 00000076380021c4  x18 0000000000000010  x19 0000000000002ebc
    x20 0000000000002ebc  x21 0000007fd9f5a048  x22 00000075993c5730  x23 00000075993c5718
    x24 0000000000000039  x25 0000007fd9f5a2d0  x26 000000763a0c85f8  x27 0000000000000039
    x28 0000000000000001  x29 0000007fd9f5a020
```

```
C:\Entwicklung\projects\Aaronia\trunk\Sources\RTSAMobileDev\aartos>flutter doctor -v
[√] Flutter (Channel master, 2.6.0-1.0.pre.193, on Microsoft Windows [Version 10.0.18363.1500], locale de-DE)
    • Flutter version 2.6.0-1.0.pre.193 at C:\Entwicklung\flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 0c5431d99c (7 hours ago), 2021-09-05 22:31:02 -0400
    • Engine revision b9c633900e
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25

[√] VS Code, 64-bit edition (version 1.59.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] VS Code (version 1.39.0-insider)
    • VS Code at C:\Users\escam\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.4.1

[√] Connected device (4 available)
    • SM F907B (mobile) • R3CM90AK4KM • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.18363.1500]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 91.0.864.70

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2021-09-06 09:53
Hi @escamoteur 
This is a duplicate of https://github.com/flutter/flutter/issues/88767

**Closed by TahaTesser** 2021-09-06 09:53 UTC
Labels: severe: regression, e: device-specific, platform-android, severe: fatal crash
