### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2

### ISSUE THREAD

**Issue by benardelia** [flutter/flutter#125742] opened 2023-04-29 10:47 UTC
## Command
```
flutter run --debug
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:131:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:119:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1742:56)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1760:13)
#8      _rootRunUnary (dart:async/zone.dart:1406:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _rootRunUnary (dart:async/zone.dart:1406:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19044.2728], locale en-TZ)
    [32m•[39m Flutter version 3.7.12 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4d9e56e694 (11 days ago), 2023-04-17 21:47:46 -0400
    [32m•[39m Engine revision 1a65d409c7
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    [32m•[39m Android SDK at C:\Users\BenAgust\AppData\Local\Android\sdk
    [32m•[39m Platform android-33, build-tools 33.0.0-rc2
    [32m•[39m Java binary at: C:\Program Files\Android\AndroidStudio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.2)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.2.32519.379
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2020.3)
    [32m•[39m Android Studio at C:\Program Files\Android\AndroidStudio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[32m[✓][39m VS Code (version 1.77.3)
    [32m•[39m VS Code at C:\Users\BenAgust\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.62.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m SM G950U (mobile) • 988b19303351343851 • android-arm64  • Android 9 (API 28)
    [32m•[39m Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19044.2728]
    [32m•[39m Edge (web)        • edge               • web-javascript • Microsoft Edge 111.0.1661.62

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf

**Comment by danagbemava-nc** [comment] 2023-05-02 07:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/95142. 

You can fix this by installing Google Chrome on your system or doing what is recommended by flutter doctor in 

```
�[31m[✗]�[39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    �[33m!�[39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
```

**Closed by danagbemava-nc** 2023-05-02 07:14 UTC
Labels: in triage
