### ISSUE TITLE
Observatory is blank screen in Safari but works fine in Chrome

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#26296] opened 2019-01-09 15:53 UTC
<img width="1216" alt="screen shot 2019-01-09 at 11 52 41 pm" src="https://user-images.githubusercontent.com/817851/50910885-ae4e4f00-1469-11e9-9bb0-f9f9b64e1853.png">

@eseidelGoogle 

flutter doctor -v
```
KyleWongdeMacBook-Pro:~ kylewong$ /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/bin/flutter doctor -v
[✓] Flutter (Channel master, v1.1.8-pre.15, on Mac OS X 10.14.3 18D32a, locale
    en-CN)
    • Flutter version 1.1.8-pre.15 at
      /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision 003c9fac71 (12 days ago), 2018-12-29 10:05:35 +0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK at /Users/kylewong/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
```

**Comment by zoechi** [comment] 2019-01-09 15:57
Duplicate of https://github.com/dart-lang/sdk/issues/34293

**Comment by zoechi** [comment] 2019-01-09 15:57
I think it's better maintained in the Dart SDK. I hope it's fine with you.

**Closed by zoechi** 2019-01-09 15:57 UTC
