### ISSUE TITLE
flutter_gallery_ios32__transition_perf 90th_percentile_frame_rasterizer_time_millis and flutter_gallery_ios__transition_perf 90th_percentile_frame_rasterizer_time_millis regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#49300] opened 2020-01-22 16:24 UTC
Pretty clear jump at https://github.com/flutter/flutter/pull/45130 for both.

Update on 03/02/2020 thanks to some discussions in https://github.com/flutter/flutter/pull/51791:

The actual regression is that between 3c65463 and d189b94 (11/18/2019 - 01/21/2020), a commit has regressed the iOS rasterization time if more than one layer tree gets rasterized per VSync.

Before 3c65463 and after d189b94, Flutter has a pipeline depth greater than 1 which allows multiple-rasterizations-per-vsync. Between those two commits, the pipeline depth is restricted to 1 so the regression isn't revealed until d189b94.

There are two ways to get rid of this regression:

1. EITHER land an engine PR that limits the pipeline depth to 1. It's similar to https://github.com/flutter/engine/pull/16175.

2. OR bisect the offending commit between 3c65463 and d189b94, and revert that commit. For each commit X in the middle, do the following
    1. `git checkout X`
    2. `git revert 3c65463` or `git cherry-pick d189b94` to set the pipeline depth above 1.
    3. Run flutter_gallery_ios__transition_perf locally to see if the commits up until X already has the regression.

**Comment by bparrishMines** [comment] 2020-01-22 20:56
Synced offline with @amirh. The PR was already reverted.

**Comment by tvolkert** [comment] 2020-02-29 23:24
Not clear why this was closed - the revert PR is what **caused** to performance regression.

![mtxLr7F8MQ4](https://user-images.githubusercontent.com/15253456/75616587-93281e00-5b07-11ea-87f2-c30f9b9901fc.png)

**Comment by flar** [comment] 2020-03-02 23:15
> Between those two commits, the pipeline depth is restricted to 1 so the regression isn't revealed until [d189b94](https://github.com/flutter/flutter/commit/d189b94bad7ee1adc9d676c6f36a4a07b5586e80).

Where do you get that the depth was restricted to 1?

I don't remember ever seeing the depth reduction committed to the repo. It's a hack that lets us see if vsync locking is causing a problem, but since its down side is magnifying the lag on complex scenes we've never committed that change to the repo ever. We've been investigating how to fix the vsync lock problem without reducing the depth instead, but we don't have a solution.

**Comment by liyuqian** [comment] 2020-03-02 23:37
@amirh first brought the pipeline depth up so I think Amir may have the answer.

**Comment by amirh** [comment] 2020-03-02 23:42
> Where do you get that the depth was restricted to 1?

The code here: https://github.com/flutter/engine/blob/63bdf3e1be12c8bfe26f3c4a63f44f922817c492/shell/common/animator.cc#L37 resulted in a pipeline depth of 1 when platform views are enabled. I overlooked that when enabling platform views for the Gallery app. The next time we enabled platform views with thread merging the pipeline depth would not be special cased.

**Comment by liyuqian** [comment] 2020-03-03 00:57
There's actually no regression. The benchmark today is on par with the benchmark in November 2019 before https://github.com/flutter/flutter/commit/3c65463f890636ce687bbbaf5bcd19dee930cce6.

<img width="1676" alt="Screen Shot 2020-03-02 at 4 45 07 PM" src="https://user-images.githubusercontent.com/22987568/75731876-c0123780-5ca5-11ea-9ef0-2b18999a457a.png">

https://github.com/flutter/flutter/commit/3c65463f890636ce687bbbaf5bcd19dee930cce6 improved the benchmark significantly because it sets the pipeline depth to 1. That's problematic and we don't want that.

So this seemingly severe regression is the manifest of two other issues:
1. iOS apps on OpenGL can sometimes get blocked while rendering frames (https://github.com/flutter/flutter/issues/51809) and setting pipeline depth to 1 dramatically reduces such blocking time. We'll figure out a better way to reduce that blocking time without setting the pipeline depth to 1.

2. Our performance dashboard isn't very good at viewing metrics that span across multiple months, so it takes us quite some time to see that we're actually just back to the level 4 months ago. We'll track the improvement of our performance dashboard in https://github.com/flutter/flutter/issues/37434

Closing this issue.

**Closed by liyuqian** 2020-03-03 00:57 UTC
Labels: engine, perf: speed, severe: performance, severe: regression, ⌺‬ platform-ios, ⚠ TODAY
