### ISSUE TITLE
Bad UTF-8 encoding found while decoding string

### ISSUE THREAD

**Issue by derrickleep** [flutter/flutter#76291] opened 2021-02-18 09:24 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2021-02-18 11:21
@derrickleep 
Your issue description is empty with no details, so it's tough to properly address issue like this, just providing issue in title won't help. Please provide all requested details as in [this](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) template so that we can help you.

Closing this, since the issue is empty.

**Closed by darshankawar** 2021-02-18 11:21 UTC
