### ISSUE TITLE
i figure out this problem, because some ip was blocked, like 172.217.160.83 and 215.58.200.243.

### ISSUE THREAD

**Issue by sixand33** [flutter/flutter#59518] opened 2020-06-16 01:08 UTC
i figure out this problem, because some ip was blocked, like 172.217.160.83 and 215.58.200.243.

_Originally posted by @Cheemer in https://github.com/flutter/flutter/issues/52246#issuecomment-596927976_

Hi @Cheemer, I have the same problem. Please tell me how fix it, step by step.

**Comment by stuartmorgan** [comment] 2020-06-16 04:56
For peer-to-peer discussion, please use one of the community options at flutter.dev/community. If you have a bug to report, please open a new bug and fill out the template.

Closing as this is not a bug report.

**Closed by stuartmorgan** 2020-06-16 04:56 UTC
