### ISSUE TITLE
Build error when adding invalid "Additional arguments"

### ISSUE THREAD

**Issue by diegoflassa** [flutter/flutter#71169] opened 2020-11-24 20:01 UTC
## Steps to Reproduce

1. Run Android Studio
2. Open a flutter application
3. Verify it is compiling
4. Open the "Edit Run/Debug configurations"  dialog
5. In the "Additional Arguments" field, add , for example "--enable-experiment=nnon-nullable"

**Expected results:** 
The app compiling successfully.

**Actual results:** 
You will get

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Users\Diego\Programming\SDKs\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 900

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Users\Diego\Programming\SDKs\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 53s
Exception: Gradle task assembleDebug failed with exit code 1

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.630], locale
    en-US)
    • Flutter version 1.24.0-10.2.pre at d:\Users\Diego\Programming\SDKs\flutter
    • Framework revision 022b333a08 (6 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Users\Diego\Programming\SDKs\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Users\Diego\Programming\SDKs\android-sdk
    • ANDROID_SDK_ROOT = D:\Users\Diego\Programming\SDKs\android-sdk
    • Java binary at: C:\Program Files\Java\jdk-11.0.9\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\Diego\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • MotoG3 (mobile)  • 192.168.0.11:5555 • android-arm    • Android 9 (API 28)
    • Web Server (web) • web-server        • web-javascript • Flutter Tools
    • Chrome (web)     • chrome            • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)       • edge              • web-javascript • Microsoft Edge 86.0.622.61
```

</details>

**Comment by darshankawar** [comment] 2020-11-25 07:31
@diegoflassa 
You probably have a typo in the parameter you are passing. The correct parameter should be :  `--enable-experiment=non-nullable` adding which compiles and run application without any issues.

<img width="584" alt="Screenshot 2020-11-25 at 12 57 37 PM" src="https://user-images.githubusercontent.com/67046386/100195965-21f28b80-2f1e-11eb-85dd-552a867e4093.png">
<img width="582" alt="Screenshot 2020-11-25 at 12 57 48 PM" src="https://user-images.githubusercontent.com/67046386/100195968-23bc4f00-2f1e-11eb-8918-ad7904877b8e.png">

Closing this as working as intended with correct parameter passed. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2020-11-25 07:31 UTC

**Comment by diegoflassa** [comment] 2020-11-25 12:08
Hy! I just think that if an invalid parameter is passed, it should be ignored, not throw an error.
