### ISSUE TITLE
[tool_crash] FileSystemException: Cannot resolve symbolic links, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by williamz64** [flutter/flutter#140635] opened 2023-12-27 05:19 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile /Users/william/Documents/plant_glow/build/app/intermediates/flutter/debug/flutter_build.d --output /Users/william/Documents/plant_glow/build/app/intermediates/flutter/debug -dTargetFile=/Users/william/Documents/plant_glow/lib/main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9iOGQzNTgxMGU5MWFiOGZjMzliYTVlN2E0MWJmZjZmNjk3ZThlM2E4Lw== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot resolve symbolic links, OS Error: No such file or directory, errno = 2
```
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:839:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:358:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#4      SourceVisitor.visitPattern (package:flutter_tools/src/build_system/source.dart:116:67)
#5      _PatternSource.accept (package:flutter_tools/src/build_system/source.dart:255:49)
#6      Target._resolveConfiguration (package:flutter_tools/src/build_system/build_system.dart:249:14)
#7      Target.resolveOutputs (package:flutter_tools/src/build_system/build_system.dart:204:12)
#8      Target._toNode (package:flutter_tools/src/build_system/build_system.dart:150:39)
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:609:30)
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:51)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1616:12)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.13.3, on macOS 14.2.1 23C71 darwin-x64, locale zh-Hant-TW)
    • Flutter version 3.13.3 on channel stable at /Users/william/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (4 months ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/william/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • RMX1911 (mobile) • a68b36a4 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos    • darwin-x64     • macOS 14.2.1 23C71 darwin-x64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2524052335ec76bb03e04ede244b071f1b86d190
### Plugins
barcode_scan2-4.2.4
connectivity-3.0.6
connectivity_for_web-0.4.0+1
connectivity_macos-0.2.1+2
device_info-2.0.3
esptouch_flutter-1.1.0-androidv2
firebase_core-2.15.1
firebase_core_web-2.7.0
firebase_messaging-14.6.7
firebase_messaging_web-3.5.6
flutter_blue-0.8.0
flutter_native_timezone_updated_gradle-2.0.3
path_provider-2.1.1
path_provider_android-2.2.0
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
sqflite-2.3.0
wifi_info_flutter-2.0.2

**Comment by danagbemava-nc** [comment] 2023-12-27 13:33
Closing this as a duplicate of https://github.com/flutter/flutter/issues/59770

**Closed by danagbemava-nc** 2023-12-27 13:33 UTC
Labels: in triage
