### ISSUE TITLE
Button onPressed() bug when using openBuilder() (Animations 2.0.0)

### ISSUE THREAD

**Issue by aalexisp** [flutter/flutter#78610] opened 2021-03-19 12:56 UTC
Hello,

I'm currently developing an application using flutter with the widget Animations 2.0.0. I'm trying to do a login form and I want to send some information to the server when the a button is clicked. 

I'm trying to use the Animation widget in order to have some cool transitions when the buttons are clicked but I've found an issue (which probably is not a bug and has solution). The thing is that when I'm using the OpenContainer() widget I have to use the closedBuilder and the openBuilder parameters. Inside the closedBuilder I have my button (which is an ElevatedButton) but when I use the onPressed() function it replaces the action that the openBuilder has written in.

So if I have like a print("Hello") written in the onPressed() function when I click the button the only thing that will happen is printing that "Hello" by terminal without transition (not swapping the form). If I remove it, then, as I have a return LoginForm() in the openBuilder function the program makes successfully the transition.

Another important thing is that I guess that the execution of the openBuilder function is done more than one time (maybe more than one thread ?) because if I have that print("Hello") when I click the button the Hello message is printed sometime twice, sometimes never... So for that reason I undertand that I can't put this print("Hello") inside the openBuilder function and I want it to be inside the onPressed() function.

I'm attaching an example of button creation with the OpenContainer widget.

``` Dart
Widget _buildAnimatedButton(String text, bool login) {
    return OpenContainer(
      closedShape: RoundedRectangleBorder(
        borderRadius: BorderRadius.all(Radius.circular(50)),
      ),
      openShape: RoundedRectangleBorder(
        borderRadius: BorderRadius.all(Radius.circular(30)),
      ),
      openElevation: 5.0,
      closedElevation: 5.0,
      closedBuilder: (context, action) {
        return ElevatedButton(
            onPressed: () {
              print("Hello");
            },
            child: Text(
              "Button text",
            ));
      },
      openBuilder: (context, action) {
        return login ? LoginForm() : RegisterScreen();
      },
    );
  }
```

**Comment by pedromassangocode** [comment] 2021-03-19 13:45
Hi @aalexisp 
This is expected since ElevatedButton has its own hitTes/ Gesture detector. To solve this issue you should prevent the `OpenContainer` widget from handling the hitTest and pass it down to your button and call `action()` inside of the `onPressed(){}` to open the container when the button is pressed.

Here is how you code should be:

 ```dart
 Widget _buildAnimatedButton(String text) {
    return OpenContainer(
      tappable: false,     // This disable hit test
      closedBuilder: (context, action) {
        return ElevatedButton(
            onPressed: () {
              print("Hello");
              action();  // this will open the container once this button is pressed.
            },
            child: Text("Button text"),
        );
      },
      openBuilder: (context, action) {
        return Scaffold(
          backgroundColor: Colors.blueGrey,
        );
      },
    );
  }
```

Closing as this is working as intended.
Thank you

**Closed by pedromassangocode** 2021-03-19 13:45 UTC
Labels: in triage

**Comment by aalexisp** [comment] 2021-03-19 13:47
Thank you so much!
