### ISSUE TITLE
some image shows different color between Flutter app and iOS native app

### ISSUE THREAD

**Issue by haohongwei** [flutter/flutter#97115] opened 2022-01-24 05:59 UTC
origin image
![example](https://user-images.githubusercontent.com/35680007/150729154-dd196020-6d19-4e8f-bbde-42914160c4c2.png)

|  Flutter app in iOS device screenshot   |  iOS native app screenshot | Flutter app in Android device screenshot  | 
|  ----  | ----  | ----  |
|  ![3221642996744_ pic](https://user-images.githubusercontent.com/35680007/150729192-d7666221-dad8-40dd-a255-7fe554402b2f.jpg)  | ![3211642996743_ pic](https://user-images.githubusercontent.com/35680007/150729232-a00410b9-fd75-4394-96ee-1a0e4415f8f7.jpg)  | ![3241642997638_ pic](https://user-images.githubusercontent.com/35680007/150729256-a7084144-e1e0-412c-a731-06aed7470e0f.jpg)  |

iOS project

```
//
//  ViewController.m
//  ios_native
//
//  Created by 郝宏伟 on 2022/1/22.
//

#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    UIImage *image = [UIImage imageNamed:@"example.png"];
    UIImageView *view = [[UIImageView alloc]initWithImage: image];
    view.frame = CGRectMake((UIScreen.mainScreen.bounds.size.width - image.size.width)/2, 102, image.size.width, image.size.height);
    [self.view addSubview:view];
    
}


@end
```

Flutter progect

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
        elevation: 0,
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Image.asset(
              'images/example.png',
              fit: BoxFit.fitWidth,
              filterQuality:FilterQuality.high,
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

flutter doctor
```

Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale

    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)

[✓] Chrome - develop for the web

[✓] Android Studio (version 2020.3)

[✓] VS Code (version 1.45.1)

[✓] Connected device (2 available)



• No issues found!
```

**Comment by darshankawar** [comment] 2022-01-24 11:32
Closing this as a duplicate of https://github.com/flutter/flutter/issues/96733

**Closed by darshankawar** 2022-01-24 11:32 UTC
Labels: in triage
