### ISSUE TITLE
Add missing "Contact Emergency" icon

### ISSUE THREAD

**Issue by solshuffle** [flutter/flutter#116180] opened 2022-11-29 12:39 UTC
## Use case

The Icon class does not include the [Material Icon "contact_emergency"](https://fonts.google.com/icons?selected=Material%20Icons%3Acontact_emergency%3A)

## Proposal

Update the Icon class to include this icon. 

```
  /// <i class="material-icons md-36">contact_emergency</i> &#x2014; material icon named "contact emergency".
  static const IconData contact_emergency = IconData( ... , fontFamily: 'MaterialIcons');
  ```

**Comment by exaby73** [comment] 2022-11-29 14:05
Marking this as a duplicate of https://github.com/flutter/flutter/issues/99973

**Closed by exaby73** 2022-11-29 14:05 UTC
Labels: in triage
