### ISSUE TITLE
Keyboard  navigation doesn't work for Linux apps

### ISSUE THREAD

**Issue by mivoligo** [flutter/flutter#63078] opened 2020-08-06 12:24 UTC
Looks like I'm not able to use keyboard to navigate or interact with a Linux app. 
Pressing Tab, Enter, Space or arrows has no effect on the app. Meanwhile when I run the app in Android emulator, I can use my keyboard without any problems.
Here's link to video of the behaviour on the Linux app: https://youtu.be/TS4-RJmU0Cg 
Here's link to video of the behaviour on the Android app: https://youtu.be/wBx6kA6tlms 

App code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _text = 'Text to change!';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Keyboard test'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Text(_text),
            FlatButton(
              onPressed: () => setState(() {
                _text = 'Flat button 1 pressed';
              }),
              child: Text('Flat button 1'),
              color: Colors.grey,
              focusColor: Colors.red,
            ),
            FlatButton(
              onPressed: () => setState(() {
                _text = 'Flat button 2 pressed';
              }),
              child: Text('Flat button 2'),
              color: Colors.grey,
              focusColor: Colors.blue,
            ),
            RaisedButton(
              onPressed: () => setState(() {
                _text = 'Raised button pressed';
              }),
              child: Text('Raised button'),
              focusColor: Colors.green,
            ),
          ],
        ),
      ),
    );
  }
}

```

flutter doctor -v:

```

michal@michal-laptop:~/VSCodeProjects/FlutterProjects/keyboard_test$ flutter doctor -v
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Linux, locale pl_PL.UTF-8)
    • Flutter version 1.21.0-1.0.pre at /home/michal/DevelFlutter/flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/michal/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/91/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/91/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 6.0 (API 23) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Linux
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
michal@michal-laptop:~/VSCodeProjects/FlutterProjects/keyboard_test$
```

</details>

**Comment by TahaTesser** [comment] 2020-08-06 13:12
Hi @mivoligo 
This is accessibly on Android, which is not supported by desktop yet  

I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/23601
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-06 13:12 UTC

**Comment by mivoligo** [comment] 2020-08-06 13:23
Hi @TahaTesser 
Thanks for pointing me to that issue. I'll subscribe there.

**Comment by mivoligo** [comment] 2020-08-10 21:05
According to @gspencergoog, keyboard navigation should work without accessibility stuff.

**Comment by gspencergoog** [comment] 2020-08-10 21:15
This is a duplicate of https://github.com/flutter/flutter/issues/60922, actually.

**Comment by mivoligo** [comment] 2020-08-10 21:18
Thanks @gspencergoog I'll sub there.

**Comment by TahaTesser** [comment] 2020-08-11 13:55
Interesting, it would highlight and navigate without accessibility support, thanks @mivolig
