### ISSUE TITLE
Launch devtools faster/earlier to make it easier to profile app startup 

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#79554] opened 2021-04-01 14:15 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Run the app using profile mode
3. Try to profile the app starting process

**Expected results:** 

As we know, the startup time is important to user experience. Therefore, I want to know why my app needs several seconds to start - which parts need how much time, such that I can try to optimize the startup time.

**Actual results:** 

In order to profile the app and see detailed stack, I need to open the DevTools (you know, that web page). However, it takes seconds to initialize and open devtools. Unfortunately, when devtools is finally opened, the app startup has almost finished! So I cannot profile anything for the startup procedure... :(

<details>
  <summary>Logs</summary>

```
N/A
```

```
N/A everything is normal (just an auto-created app)
```

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H524 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.3 at /Users/tom/opt/flutter
    • Framework revision 4d7946a68d (2 周前), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/tom/Library/Android/sdk
    • Java binary at: /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Users/tom/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 14CE77E4-C2C5-4267-B565-520FA291E237 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-04-01 15:13
Hi @fzyzcjy 
Profile mode isn't users, they would be on release mode if I am not mistaken. But I understand profile being slower could be an issue when testing startup of your app, I've been in situations like that where the app is already finished loading while devtools still loads.

This sounds more related to devtools than actual profile mode, what if there was a way to start devtools first before the app, once the devtools is initialized then it can let the app start and listen to it 

I've edited the title, let me know what you think
Thank you

**Comment by fzyzcjy** [comment] 2021-04-01 23:17
@TahaTesser That is one possible method to do so, thanks!

Another possible way is to allow "hot restart" (notice no need for "hot reload") in profile mode. By doing so, I can (slowly) launch the devtools, and then hot restart the whole app (and profile what is happening). 

Indeed, personally I perfer the second way, because with that way, I can happily profile the startup as many times as I want. (in the first way, I have to re-compile the app again if want to profile).

**Comment by TahaTesser** [comment] 2021-04-05 07:58
@fzyzcjy 
What is proposing, is already in https://github.com/flutter/flutter/issues/37987
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/37987
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-05 07:58 UTC
Labels: in triage

**Comment by fzyzcjy** [comment] 2021-04-05 08:14
@TahaTesser Sounds reasonable. Thanks!

**Comment by fzyzcjy** [comment] 2021-04-05 08:16
@TahaTesser Hmm wait a bit... That is a **P5** issue. In my life of more than a year of flutter experiences, I almost never see a P5 issue solved...

However, this is quite a critical problem. As you know, **it is very important to have fast enough startup time, otherwise no user will want to use the app!** And the best way to know how to improve the startup speed is by profiling.
