### ISSUE TITLE
Flutter Google Map No option for localization.

### ISSUE THREAD

**Issue by salman0017** [flutter/flutter#142855] opened 2024-02-03 08:46 UTC
### Steps to reproduce

1. App locale is set to moroco. (ar_MA,fr_MA)
2. Google map shows Western sahara region where as official google map does not show this.
3. no option in google map widget to set locale and region.

### Expected results

I want to display moroco based google map to the user. Which does not show Moroco and western sahara as 2 different regions.

### Actual results

Google map displays moroco and western sahara with boundaries.

### Code sample

 Widget _materialApp() {
    AppUtil.printTime("Home GetMaterialApp BEF");

    return GetMaterialApp(
      // theme: ThemeData(
      //     useMaterial3: true, colorSchemeSeed: const Color(0xff6750a4)),
      initialBinding: CommonBinding(),
      supportedLocales: [
        Locale('en', 'US'),
        Locale('en', 'MA'),
        Locale('ar', 'MA'),
        Locale('fr', 'MA'),
        Locale("he", "IL"),
        Locale("ar", 'IL'),
        Locale("hi", 'IN'),
        Locale("kn", 'IN'),
        Locale("es", 'PR'),
        Locale('fr', 'FR'),
      ],
      localizationsDelegates: [
        CountryLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      builder: (context, child) => MediaQuery(
          data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
          child: child!),
      translations: LocaleString(),
      locale: AppUtil.appLocale,
      debugShowCheckedModeBanner: false,
      title: AppString().appName,
      theme: AppTheme.lightTheme,
      home: Home(),
    );
  }

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
![image](https://github.com/flutter/flutter/assets/97174419/80ce6c8a-dcde-4042-9f0d-33b83324af1e)

[Upload media here]</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2024-02-05 08:52
Closing this as a duplicate of https://github.com/flutter/flutter/issues/100118 and you can check [this](https://github.com/flutter/flutter/issues/100118#issuecomment-1068406783) response for your reference.

**Closed by darshankawar** 2024-02-05 08:52 UTC
Labels: in triage

**Comment by salman0017** [comment] 2024-02-05 09:11
I am from India, and I would like to know how to check Morocco-based Google Maps from India. What settings or tools should I use to view maps specific to Morocco from within India.
