### ISSUE TITLE
[Impeller] App crashes on image compression in Skia with wide-gamut enabled.

### ISSUE THREAD

**Issue by Hari-07** [flutter/flutter#133942] opened 2023-09-03 18:06 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. This snippet was adapted from [flutter_cache_manager](https://github.com/Baseflow/flutter_cache_manager/blob/32b71c1da1689b97434959ac407b03b74d7e405c/flutter_cache_manager/lib/src/cache_managers/image_cache_manager.dart#L97-L100)
2. Look at snippet below
3. The particular image url I'm using is [link](https://images.unsplash.com/photo-1685016925614-d41b39fb66b5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDI2fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60)

### Expected results

Both calls to `toByteData` should work without errors

### Actual results

After upgrading to 3.13, on a physical device (Tested on iphone 14 pro)
```
.toByteData(format: ui.ImageByteFormat.png)
```
throws error
```
[VERBOSE-2:image_encoding.cc(123)] Could not convert raster image to PNG.
_TypeError: Null check operator used on a null value
  File "painting.dart", line 1959, in _Image.toByteData.<fn>.<fn>
```

However running with `--no-enable-impeller` seems to run without error.

FYI the image is a jpeg. I'm not sure if JPEG images are supposed to work with `ImageByteFormat.png` however it does work when not using impeller, so definitely seems like a regression

### Code sample

<details><summary>Code sample</summary>

```dart
  void test() async {
    final img = NetworkImage(_imageUrl);

    final im = await _decodeImage(img);

   await im.toByteData();
   await im.toByteData(format: ui.ImageByteFormat.png);
  }

  Future<ui.Image> _decodeImage(
    ImageProvider imageProvider,
  ) {
    final image = imageProvider;
    final completer = Completer<ui.Image>();
    image.resolve(ImageConfiguration.empty).addListener(
      ImageStreamListener((info, _) {
        completer.complete(info.image);
        image.evict();
      }),
    );
    return completer.future;
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
hari@<name>-MacBook-Pro <app> % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.1 22G90 darwin-arm64, locale en-IN)
    • Flutter version 3.13.1 on channel stable at /Users/<name>/Softwares/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (12 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/<name>/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.3345.108

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • iPhone (mobile) • 00008120-001444280A00C01E            • ios            • iOS 16.6 20G75
    • iPhone 14 Pro (mobile)       • BCD80EB9-B8A8-43F9-9D7F-D96DF7A457CD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)              • macos                                • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 116.0.5845.140
    ! Error: iPhone is busy: Fetching debug symbols for Harinandan’s iPhone. Xcode will continue when Harinandan’s iPhone is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by chinmaygarde** [comment] 2023-09-05 21:08
We moved to wide-gamut rendering in 3.13 and ran into separate issues with image decoding. Perhaps the same issue happens with image encoding as well? cc @gaaclarke

**Comment by gaaclarke** [comment] 2023-09-05 21:23
Happy to look at this, @Hari-07 can you please supply full reproduction code so I can reproduce this locally?

**Comment by Hari-07** [comment] 2023-09-06 04:02
In this sample, the 2nd call to `.toByteData` throws the error
```bash
[VERBOSE-2:image_encoding.cc(123)] Could not convert raster image to PNG.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1959:25)
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const _imageUrl =
      'https://images.unsplash.com/photo-1685016925614-d41b39fb66b5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDI2fHRvd0paRnNrcEdnfHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60';

  @override
  void initState() {
    test();
    super.initState();
  }

  void test() async {
    const img = NetworkImage(_imageUrl);

    final im = await _decodeImage(img);

    await im.toByteData();
    await im.toByteData(format: ui.ImageByteFormat.png);
  }

  Future<ui.Image> _decodeImage(
    ImageProvider imageProvider,
  ) {
    final image = imageProvider;
    final completer = Completer<ui.Image>();
    image.resolve(ImageConfiguration.empty).addListener(
      ImageStreamListener((info, _) {
        completer.complete(info.image);
        image.evict();
      }),
    );
    return completer.future;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.primary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          height: 300,
          width: 300,
          color: Colors.red,
        ),
      ),
    );
  }
}

```

</details>

**Comment by gaaclarke** [comment] 2023-09-06 16:54
> Also there was no stacktrace on this error, is there anything we can do that would enable stacktrace for errors that originate from non dart code as well? Atleast the dart call stack that led to the external function call

When I investigate this I'll run your code with a locally built debug engine, launching the xcodeproj from xcode.  That launches it with lldb attached.  Then I'll start adding breakpoints around the code that prints that error.  It should be obvious what is wrong (hopefully) now that you supplied reproduction code.  There's no need to investigate further unless you want.

**Comment by gaaclarke** [comment] 2023-09-06 17:41
So, this is related to wide gamut.  In skia, when we try to encode the PNG, when setting the header there is a switch over the pixel format that is missing support for BGR101010x_XR ([link](https://github.com/google/skia/blob/487cd92405710cd01293ec7e7158504a94a98498/src/encode/SkPngEncoderImpl.cpp#L126)).

```
#0	0x000000010c0fb670 in SkPngEncoderMgr::setHeader(SkImageInfo const&, SkPngEncoder::Options const&) at /Users/aaclarke/dev/engine/src/third_party/skia/src/encode/SkPngEncoderImpl.cpp:126
#1	0x000000010c0fcea0 in SkPngEncoder::Make(SkWStream*, SkPixmap const&, SkPngEncoder::Options const&) at /Users/aaclarke/dev/engine/src/third_party/skia/src/encode/SkPngEncoderImpl.cpp:474
#2	0x000000010c0fd19c in SkPngEncoder::Encode(SkWStream*, SkPixmap const&, SkPngEncoder::Options const&) at /Users/aaclarke/dev/engine/src/third_party/skia/src/encode/SkPngEncoderImpl.cpp:492
#3	0x000000010c0fd2bc in SkPngEncoder::Encode(GrDirectContext*, SkImage const*, SkPngEncoder::Options const&) at /Users/aaclarke/dev/engine/src/third_party/skia/src/encode/SkPngEncoderImpl.cpp:505
#4	0x000000010d24a164 in flutter::(anonymous namespace)::EncodeImage(sk_sp<SkImage> const&, flutter::(anonymous namespace)::ImageByteFormat) at /Users/aaclarke/dev/engine/src/flutter/lib/ui/painting/image_encoding.cc:120
#5	0x000000010d249fa4 in flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1::operator()(sk_sp<SkImage> const&) const at /Users/aaclarke/dev/engine/src/flutter/lib/ui/painting/image_encoding.cc:169
#6	0x000000010d249f58 in decltype(std::declval<flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1&>()(std::declval<sk_sp<SkImage> >())) std::_LIBCPP_ABI_NAMESPACE::__invoke[abi:v15000]<flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1&, sk_sp<SkImage> >(flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1&, sk_sp<SkImage>&&) at /Users/aaclarke/dev/engine/src/third_party/libcxx/include/__functional/invoke.h:403
#7	0x000000010d249f08 in void std::_LIBCPP_ABI_NAMESPACE::__invoke_void_return_wrapper<void, true>::__call<flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1&, sk_sp<SkImage> >(flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1&, sk_sp<SkImage>&&) at /Users/aaclarke/dev/engine/src/third_party/libcxx/include/__functional/invoke.h:488
#8	0x000000010d249edc in std::_LIBCPP_ABI_NAMESPACE::__function::__alloc_func<flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1, std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1>, void (sk_sp<SkImage>)>::operator()[abi:v15000](sk_sp<SkImage>&&) at /Users/aaclarke/dev/engine/src/third_party/libcxx/include/__functional/function.h:185
#9	0x000000010d248e00 in std::_LIBCPP_ABI_NAMESPACE::__function::__func<flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1, std::_LIBCPP_ABI_NAMESPACE::allocator<flutter::(anonymous namespace)::EncodeImageAndInvokeDataCallback(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<tonic::DartPersistentValue, std::_LIBCPP_ABI_NAMESPACE::default_delete<tonic::DartPersistentValue> >, flutter::(anonymous namespace)::ImageByteFormat, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, fml::WeakPtr<GrDirectContext> const&, fml::TaskRunnerAffineWeakPtr<flutter::SnapshotDelegate> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&, bool)::$_1>, void (sk_sp<SkImage>)>::operator()(sk_sp<SkImage>&&) at /Users/aaclarke/dev/engine/src/third_party/libcxx/include/__functional/function.h:359
#10	0x000000010d24d5f8 in std::_LIBCPP_ABI_NAMESPACE::__function::__value_func<void (sk_sp<SkImage>)>::operator()[abi:v15000](sk_sp<SkImage>&&) const at /Users/aaclarke/dev/engine/src/third_party/libcxx/include/__functional/function.h:512
#11	0x000000010d24d3e0 in std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<SkImage>)>::operator()(sk_sp<SkImage>) const at /Users/aaclarke/dev/engine/src/third_party/libcxx/include/__functional/function.h:1187
#12	0x000000010d2f1f74 in flutter::ImageEncodingImpeller::ConvertImageToRaster(sk_sp<flutter::DlImage> const&, std::_LIBCPP_ABI_NAMESPACE::function<void (sk_sp<SkImage>)>, fml::RefPtr<fml::TaskRunner> const&, fml::RefPtr<fml::TaskRunner> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<fml::SyncSwitch const> const&, std::_LIBCPP_ABI_NAMESPACE::shared_ptr<impeller::Context> const&)::$_0::operator()(sk_sp<SkImage>)::'lambda'()::operator()() const at /Users/aaclarke/dev/engine/src/flutter/lib/ui/painting/image_encoding_impeller.cc:149
```

The point-of-contact for this code is out of office.  I'm not sure if we want to change Skia to support this pixel format, or if we should just manually convert the image to `kRGBA_F16_SkColorType` before passing it down to Skia.  I'm not sure how often this code path is used by Skia so we should make sure that the resulting PNG file is wide gamut too.

**Comment by chinmaygarde** [comment] 2023-09-06 17:51
Thanks for the sleuthing! The workaround is to disable wide gamut rendering in the app in the meantime right (`FLTEnableWideGamut`)?

**Comment by chinmaygarde** [comment] 2023-09-06 17:52
Also, would it be useful to dedupe it with the wide-gamut decoding bug?

**Comment by gaaclarke** [comment] 2023-09-06 17:55
> Thanks for the sleuthing! The workaround is to disable wide gamut rendering in the app in the meantime right (FLTEnableWideGamut)?

Yep, that will avoid the issue, but of course encoded images will not be wide gamut.

> Also, would it be useful to dedupe it with the wide-gamut decoding bug?

Nope, these are 2 different bugs that require 2 different patches to Skia to fix.

**Comment by chinmaygarde** [comment] 2023-09-06 18:11
xref decompression issue: https://github.com/flutter/flutter/issues/133013

**Comment by gaaclarke** [comment] 2023-09-06 18:33
Here is a better workaround than turning wide gamut off.  Convert the image to non-wide gamut data before encoding it to PNG.  That way you can still render your app in full color:

From reproduction code:
```dart
  void test() async {
    const img = NetworkImage(_imageUrl);

    final im = await _decodeImage(img);
    final bytes = await im.toByteData(format: ui.ImageByteFormat.rawRgba);
    if (bytes != null) {
      ui.decodeImageFromPixels(
          Uint8List.view(bytes.buffer),
          im.width,
          im.height,
          ui.PixelFormat.rgba8888, (result) async {
        await result.toByteData(format: ui.ImageByteFormat.png);
      });
    }
  }
```

**Comment by gaaclarke** [comment] 2023-09-06 18:54
The fix in skia seems straight forward.  I'll implement a test in Flutter to verify that it is working: https://skia-review.googlesource.com/c/skia/+/752596

**Comment by Hari-07** [comment] 2023-09-07 12:27
> When I investigate this I'll run your code with a locally built debug engine, launching the xcodeproj from xcode. That launches it with lldb attached. Then I'll start adding breakpoints around the code that prints that error. It should be obvious what is wrong (hopefully) now that you supplied reproduction code. There's no need to investigate further unless you want.


Not to investigate further but in the future also, from an observability pov, it's quite concerning to me if we see errors that don't have stacktraces as that makes it much harder to figure out what went wrong, if it's on us or if not on whom. So I just asked to see if there's anything that would help in that aspect

**Comment by Hari-07** [comment] 2023-09-07 12:39
>switch over the pixel format that is missing support for BGR101010x_XR ([link](https://github.com/google/skia/blob/487cd92405710cd01293ec7e7158504a94a98498/src/encode/SkPngEncoderImpl.cpp#L126)).

I've seen that in flutter in some places, it's mentioned if this error occurs open an issue. I think in the default case for this switch too something like that could be included , which also prints out the pixel format. Would save users and you guys time in the future if there's other formats that are missing support

**Comment by gaaclarke** [comment] 2023-09-18 18:38
https://skia-review.googlesource.com/c/skia/+/752596 fixed this issue, it has landed and rolled.  It doesn't have a test inside of flutter though.

**Comment by Hari-07** [comment] 2023-09-18 20:11
Is this something that can be considered to cherry pick and get it out?

**Comment by gaaclarke** [comment] 2023-09-18 20:16
> Is this something that can be considered to cherry pick and get it out?

This would require a test to be cherry-picked.  I can look into it.  I remember thinking it may be hard to add a test for some reason.

**Comment by gaaclarke** [comment] 2023-09-18 21:49
I've attempted to write a unit test against this fix and it seems to crash with memory corruption.  I'm less confident in our skia fix now.  Filed an issue is skia: https://g-issues.skia.org/issues/300986800

**Comment by Hari-07** [comment] 2023-09-19 13:11
While that's a little unfortunate seems like the test did its job. Awesome! 🚀

**Closed** 2023-09-19 21:24 UTC
Labels: P2, e: impeller, team-engine, triaged-engine
