### ISSUE TITLE
[tool_crash] StateError: Bad state: The client closed with pending request "streamListen".

### ISSUE THREAD

**Issue by LichKing255** [flutter/flutter#66180] opened 2020-09-19 13:32 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: The client closed with pending request "streamListen".
```
#0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
#1      _rootRun (dart:async/zone.dart:1182:47)
#2      _CustomZone.run (dart:async/zone.dart:1093:19)
#3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
#4      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
#5      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
#6      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
#7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.264, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.264 at E:\Application\android-sdk-windows\flutter
    • Framework revision 3e6863ab2b (9 hours ago), 2020-09-18 21:05:27 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:/Application/android-sdk-windows
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = E:/Application/android-sdk-windows
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: fabeb2a16f1d008ab8230f450c49141d35669798

**Comment by d9j** [comment] 2020-09-20 08:16
same problem here. trying to integrate flutter in existing project. after such issues no way gonna consider flutter for development. too much time getting wasted on resolving issues of cross platform frameworks .

**Comment by jinguoliang** [comment] 2020-09-20 14:59
same program when I ran "flutter run", even the application was just created

**Comment by pedromassangocode** [comment] 2020-09-21 08:12
Possibly related to https://github.com/flutter/flutter/issues/61274

**Comment by jmagman** [comment] 2020-09-25 02:13
@jonahwilliams said https://github.com/flutter/flutter/issues/61274 was fixed by reverting a "dds" change, though I'm not sure which one.
\cc @bkonyi 

@LichKing255 there's been [some work](https://github.com/flutter/flutter/commit/a3b3d53d62333a5b36e835a0e526b805c19ff258) in this area since you filed it, would you mind updating on the master channel and seeing if you can reproduce it?

**Comment by jmagman** [comment] 2020-09-25 02:15
Sorry for the forward duplicate, there's already conversation happening at https://github.com/flutter/flutter/issues/66514
Duplicate of https://github.com/flutter/flutter/issues/66514.

**Closed by jmagman** 2020-09-25 02:15 UTC
Labels: P4, severe: crash, tool, waiting for customer response
