### ISSUE TITLE
[Web] Tall font characters extremities are not fully displayed after release build

### ISSUE THREAD

**Issue by aragonet** [flutter/flutter#52321] opened 2020-03-10 14:50 UTC
## Steps to Reproduce

The use of google font IBMPlexSans makes that the upper and lower parts of a tall letter are hidden (see images below). I think this will happen on different fonts, not only this one, I have not tried though.

This only happens when compiling the code for release. On debug works just fine and on mobile too.

**Expected results:** 
--- Debug text display ---
![image](https://user-images.githubusercontent.com/20858599/76324456-523dbf80-62e6-11ea-8013-228684433bec.png)

**Actual results:** 
--- Release text display ---
![image](https://user-images.githubusercontent.com/20858599/76324478-5b2e9100-62e6-11ea-8ec6-57e1863477c6.png)
(The g lower pixels are hidden)

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale es_ES.utf8)
    • Flutter version 1.14.6 at /flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /development/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /development/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2020-03-10 15:11
Duplicate of [#40037](https://github.com/flutter/flutter/issues/40037)

**Closed by TahaTesser** 2020-03-10 15:11 UTC
