### ISSUE TITLE
Some Emoji not displaying on iOS

### ISSUE THREAD

**Issue by mentalmap** [flutter/flutter#54071] opened 2020-04-06 07:36 UTC
# flutter doctor
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
[✓] VS Code (version 1.42.1)
[✓] Connected device (3 available)
```

# program
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Text(
            '⭐︎✯✡︎✩✪✫✬✭✮✶✷✵✸✹✺❊✻✽✼❉✱✲✾❃❋✳︎✴︎❇︎❈※❅❆❄︎⚙︎✿❀❁❂✓',
            style: TextStyle(
              fontSize: 48.0,
              color: Colors.blue,
            ),
          ),
        ),
      ),
    );
  }
}
```
![Screenshot_1586157966](https://user-images.githubusercontent.com/1574662/78533753-08c88d80-781c-11ea-8fa2-5013fb4b896f.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-06 at 15 26 13](https://user-images.githubusercontent.com/1574662/78533756-0a925100-781c-11ea-9334-50b7b920ccd4.png)

**Comment by andrewsoohwanlee** [comment] 2020-04-22 20:11
I'm experiencing the same issue (looks like the same as https://github.com/flutter/flutter/issues/49627). This happens for number emoji's like 3️⃣ or 7️⃣ as well.

I would love to enable emoji's in my app which includes user generated content, but this is a blocker.

**Comment by iapicca** [comment] 2020-07-01 12:40
Hi @mentalmap 
are you still experiencing the issue with the latest stable or above?
Thank you

**Comment by mentalmap** [comment] 2020-07-01 13:48
on 1.17.5:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-01 at 21 47 15](https://user-images.githubusercontent.com/1574662/86251473-7ea68000-bbe4-11ea-8400-7f9a3073087c.png)

**Comment by iapicca** [comment] 2020-07-03 08:38
Hi @mentalmap 

I do experience this behaviour with the latest master

<details>
  <summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/86449808-5cfee300-bd21-11ea-8972-2c4ffa3f5dfe.png)


</details>


<details>
  <summary>logs</summary>

```console
[✓] Flutter (Channel master, 1.20.0-3.0.pre.126, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.126 at /Users/nevercode/development/flutter_master
    • Framework revision 462b0ea76e (12 hours ago), 2020-07-02 16:13:02 -0400
    • Engine revision 51ca1432b3
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 8afe9875a6)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • D6967F45-CB0F-4D4E-AFD5-278816A21CAE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```


</details>

Thank you

**Comment by c9addy** [comment] 2020-08-27 17:55
Don't we use Unicode for Emoji??

**Comment by krokyze** [comment] 2020-09-01 21:11
![GitHub Logo](https://i.imgur.com/lkmj5rG.jpg)

✌️☝️✍️

Flutter version: 1.20.2

**Comment by jdosornio** [comment] 2021-12-10 21:43
I'm experiencing this issue as well on flutter 2.5.3

**Comment by vernalclareai** [comment] 2022-07-25 02:05
I am also experiencing the issue on Flutter 3.0.2.

**Comment by rahul-2501** [comment] 2022-07-25 09:26
> I am also experiencing the issue for number emojis on Flutter 3.0.2. ![image](https://user-images.githubusercontent.com/61595318/180679736-f391d1b2-499e-43b2-845f-fa2a057635fd.png)

same

**Comment by AG-Akash09** [comment] 2022-12-31 09:55
I am also experiencing same issue on flutter 3.3.10. When we begin text with 10 digit icon, everything works smoothly. If we begin with 0 to 9 digit icon, then there is rendering issue.

**Comment by maheshmnj** [comment] 2023-01-14 04:33
I verified the issue on the latest master channel 3.7 on iphone 12 pro simulator and it seems to render the icons fine.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/31410839/212450703-67f368a0-a4a0-4700-9879-60243465b32a.png">

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: const Center(
          child: Text(
            '⭐︎✯✡︎✩✪✫✬✭✮✶✷✵✸✹✺❊✻✽✼❉✱✲✾❃❋✳︎✴︎❇︎❈※❅❆❄︎⚙︎✿❀❁❂✓\n0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣',
            style: TextStyle(
              fontSize: 48.0,
              color: Colors.blue,
            ),
          ),
        ),
      ),
    );
  }
}

```
</details> 
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


Closing this issue as fixed. Incase you still encounter the issue, then please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2023-01-14 04:33 UTC
Labels: platform-ios, framework, a: typography, has reproducible steps, P4, found in release: 1.20

**Comment by wadeowenwatt** [comment] 2023-03-02 03:00
> I verified the issue on the latest master channel 3.7 on iphone 12 pro simulator and it seems to render the icons fine.
> 
> <img alt="image" width="328" src="https://user-images.githubusercontent.com/31410839/212450703-67f368a0-a4a0-4700-9879-60243465b32a.png">
> 
> code sample
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(const MyApp());
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Welcome to Flutter',
>       debugShowCheckedModeBanner: false,
>       home: Scaffold(
>         appBar: AppBar(
>           title: const Text('Welcome to Flutter'),
>         ),
>         body: const Center(
>           child: Text(
>             '⭐︎✯✡︎✩✪✫✬✭✮✶✷✵✸✹✺❊✻✽✼❉✱✲✾❃❋✳︎✴︎❇︎❈※❅❆❄︎⚙︎✿❀❁❂✓\n0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣',
>             style: TextStyle(
>               fontSize: 48.0,
>               color: Colors.blue,
>             ),
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> flutter doctor -v (mac)
> Closing this issue as fixed. Incase you still encounter the issue, then please feel free to write in the comments and we will reopen it.
> 

> Thank you.

@maheshmnj 
if I put some emoji in front of 1️⃣, it will display. But I only type 1️⃣ in textfield, it will show two box with question mark and the Text widget also displays like that. 
It happen when I run debug in iPhone 14 simulator with iOS version 16.1

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 13.0.1 22A400 darwin-arm, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

![Screenshot 2023-03-02 at 09 45 23](https://user-images.githubusercontent.com/73239433/222319021-e4c2e34e-b879-4da9-a049-29eabd59b6be.png)

![Screenshot 2023-03-02 at 09 45 54](https://user-images.githubusercontent.com/73239433/222319030-113e4ce5-8eed-41b3-aec3-6ff2f5fe58be.png)

**Comment by maheshmnj** [comment] 2023-03-02 06:44
cc: @danagbemava-nc

**Comment by danagbemava-nc** [comment] 2023-03-02 07:14
Hi @wadeowenwatt, you are on an older version of flutter can you upgrade to the latest version of flutter stable(3.7.6) to see if you can still reproduce the issue?  Can you also check on the latest `master` channel to see if it reproduces as well?

There's a similar report in https://github.com/flutter/flutter/issues/36062

**Comment by wadeowenwatt** [comment] 2023-03-03 03:31
> Hi @wadeowenwatt, you are on an older version of flutter can you upgrade to the latest version of flutter stable(3.7.6) to see if you can still reproduce the issue? Can you also check on the latest `master` channel to see if it reproduces as well?
> 
> There's a similar report in #36062

Thanks for your support @danagbemava-nc, I tried updating the latest flutter version, but I can still reproduce this issue. I think this issue is not the same as the one you mentioned because it occurs in both TextField.

**Comment by danagbemava-nc** [comment] 2023-03-03 06:23
Hi @wadeowenwatt, since this issue was about a specific scenario that has since been fixed, kindly file a new issue for the scenario you're facing so that it can be looked at independently. 

Thank you
