### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'showSnackBar' was called on null.

### ISSUE THREAD

**Issue by atom808** [flutter/flutter#76704] opened 2021-02-24 14:45 UTC
I am getting this following error when i try to show a snackbar. This snackbar was working porperly last time i checked: 

> [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'showSnackBar' was called on null.
> Receiver: null
> Tried calling: showSnackBar(Instance of 'SnackBar')

**Code:**
`void connectionSnackBar() {
    final snackbar = SnackBar(
      content: Text("Falha ao conectar-se ao servidor. Verifique sua conexão."),
      backgroundColor: Colors.red,
    );
    _scaffoldKey.currentState.showSnackBar(snackbar);
  }`

**Flutter Doctor:**

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [versÃ£o 10.0.19041.804], locale pt-BR)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\diego\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\diego\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by atom808** [comment] 2021-02-24 14:46
Print of the code to make it easer to read:

![image](https://user-images.githubusercontent.com/20194456/109017398-e50d7080-7695-11eb-9ca9-ed2dcf219e97.png)

**Comment by iapicca** [comment] 2021-02-24 16:24
@atom808 
the issue might depend from your implementation rather than being a bug with flutter
can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by atom808** [comment] 2021-02-24 17:36
> @atom808
> the issue might depend from your implementation rather than being a bug with flutter
> can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Basically, i have a button inside a form that calls this function:

```
onPressed: () {
    if (_formKey.currentState.validate()) {
      signIn(_emailController.text,
          _passwordController.text);
    }
  },
```

And inside the function i run some validations. When certain condition passes, it calls this snackback, like this:

```
else if (response.statusCode == 401) {
      print("erro do usuário");
      print(response.body);
      setState(() {
        _isLoading = false;
      });
      wrongUserSnackBar();
    }
```


And here is the full error message:

E/flutter (17049): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'showSnackBar' was called on null.
E/flutter (17049): Receiver: null
E/flutter (17049): Tried calling: showSnackBar(Instance of 'SnackBar')
E/flutter (17049): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (17049): #1      _LoginPageState.wrongUserSnackBar (package:tita_mobile/views/login_page.dart:46:31)
E/flutter (17049): #2      _LoginPageState.signIn (package:tita_mobile/views/login_page.dart:318:7)
E/flutter (17049): <asynchronous suspension>
E/flutter (17049): #3      _LoginPageState._loginForm.<anonymous closure> (package:tita_mobile/views/login_page.dart:383:29)
E/flutter (17049): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (17049): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (17049): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (17049): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (17049): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (17049): #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (17049): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (17049): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (17049): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (17049): #13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (17049): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (17049): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (17049): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (17049): #17     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (17049): #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (17049): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (17049): #20     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (17049): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (17049):

**Comment by iapicca** [comment] 2021-02-24 19:39
@atom808 
[snackbar](https://api.flutter.dev/flutter/material/SnackBar-class.html) seems to work fine, please try this code sample [code sample](https://dartpad.dartlang.org/cebbe68b1cf76bdad136e86c3350473b)

if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by darshankawar** [comment] 2021-02-25 06:52
@atom808 
This is a very common error while using `snackbar` which often causes due to the way the code is implemented. You may refer [this](https://stackoverflow.com/questions/54063473/flutter-showsnackbar-called-on-null) SO link to get help on why it may be causing. 
Also, use the above referred link to get more help on your issue.
Closing from here.

**Closed by darshankawar** 2021-02-25 06:52 UTC
Labels: in triage
