### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by 01krupal** [flutter/flutter#139060] opened 2023-11-27 13:10 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1928:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2493:21)
#2      VmService.callServiceExtension (package:

**Comment by danagbemava-nc** [comment] 2023-11-28 06:56
Closing this as a duplicate of https://github.com/flutter/flutter/issues/102994

**Closed by danagbemava-nc** 2023-11-28 06:56 UTC
Labels: in triage
