### ISSUE TITLE
ListView/ScrollView - Scrolling jumps to the bottom regardless of items on M1 iOS Simulator

### ISSUE THREAD

**Issue by louisoftokyo** [flutter/flutter#117632] opened 2022-12-25 18:19 UTC
This is the same issue as [this](https://github.com/flutter/flutter/issues/79641), which is marked as closed. Please see that issue for details. According to that issue this was caused by the arm64 simulator and was fixed in an update, however, I have recently started Flutter development and am currently experiencing this issue.

Flutter 3.3.10
Xcode 14.2
M1  MacBook Pro

The scrolling behaviour works as expected on Android.

**Comment by huycozy** [comment] 2022-12-26 11:49
@louisoftokyo Can you retry on the latest Flutter master channel (3.7.0.) to check if the issue still persists or not?

**Comment by louisoftokyo** [comment] 2022-12-27 10:42
@huycozy I've switched to master (`flutter doctor` says `Flutter (Channel master, 3.7.0-13.0.pre.79, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)`) and the issue is still occurring.

**Comment by huycozy** [comment] 2022-12-29 07:00
@louisoftokyo Can you confirm whether the issue happens with the normal list (from OP in #79641) or with Google Maps plugin as mentioned at https://github.com/flutter/flutter/issues/79641#issuecomment-868368492?

**Comment by louisoftokyo** [comment] 2022-12-29 16:16
@huycozy I am using a normal ListView.separated().

**Comment by danagbemava-nc** [comment] 2022-12-30 06:25
Hi @louisoftokyo, do you happen to have `google_maps_flutter` in your `pubspec.yaml`? If you have it included in the project, the simulator is run in Rosetta mode by default. See https://github.com/flutter/flutter/issues/112244#issuecomment-1259785112

**Comment by louisoftokyo** [comment] 2022-12-30 18:38
@danagbemava-nc I do not have `google_maps_flutter` in my `pubspec.yaml`. Here it is:

```
name: my_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: any
  get_it: ^7.2.0
  intl: ^0.18.0
  timeago: ^3.2.2
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  animations: ^2.0.7
  zoom_tap_animation: ^1.1.0
  bubble: ^1.2.1
  dropdown_button2: ^1.9.2
  fluttertoast: ^8.1.2
  rounded_loading_button: ^2.1.0
  custom_refresh_indicator: ^2.0.1
  uuid: ^3.0.7
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**Comment by danagbemava-nc** [comment] 2023-01-02 06:24
Hi @louisoftokyo, I used the sample from #79641 (updated for the latest version of flutter) but I cannot seem to reproduce the issue. 
Can you check if your Simulator is running in rosetta mode? Can you also try in a new project with no dependencies to see if there's an issue with the scrolling? 

Thank you

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/210200015-02af0b93-6fb8-4a66-9995-7cb0e0e4dbf4.mov
</details>


<details>
<summary>updated sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        Container(color: Colors.red, height: 100),
        Container(color: Colors.blue, height: 100),
        Container(color: Colors.red, height: 100),
        Container(color: Colors.blue, height: 100),
        Container(color: Colors.red, height: 100),
        Container(color: Colors.blue, height: 100),
        Container(color: Colors.red, height: 100),
        Container(color: Colors.blue, height: 100),
        Container(color: Colors.red, height: 100),
        Container(color: Colors.blue, height: 100),
        Container(color: Colors.red, height: 100),
        Container(color: Colors.blue, height: 100),
        Container(color: Colors.red, height: 100),
        Container(color: Colors.blue, height: 100),
        Container(color: Colors.red, height: 100),
        Container(color: Colors.blue, height: 100),
      ],
    );
  }
}
```
</details>

**Comment by SexyBeast007** [comment] 2023-01-02 07:45
Having the exact same issue!
This makes the simulator almost unusable, almost totally useless.

Situation:
Simulator works perfectly on my Intel MacOS.
Issue occurs on my new M1 Pro.
Latest version of all of everything installed and running flutter stable & beta - same scrolling for both.

Some info which may help in solving this:
If I use my simulator and navigate to settings and scroll one of the longer screens and it scrolls perfectly normal. When I then navigate to my app it scrolls like haywire, like described in this issue.
I tried running simulator with rosetta my command line and this does not work.

**Comment by danagbemava-nc** [comment] 2023-01-03 06:14
Hi @SexyBeast007, I'm curious, are you also running into this issue with the default sample app?

**Comment by louisoftokyo** [comment] 2023-01-06 05:05
@danagbemava-nc After some investigation I've found that the issue seems to be being triggered by the package fluttertoast. If you add `fluttertoast: ^8.1.2` to the `pubspec.yaml` in #79641, it triggers this behaviour.

**Comment by danagbemava-nc** [comment] 2023-01-06 07:20
Hi @louisoftokyo, I can reproduce this with `fluttertoast` in the project. You'd have to report this on their repo since `fluttertoast` is a plugin. 

There's a chance that there's a dependency that they're using hasn't been updated to support the 
M1 simulator. In which case, that would explain why it is behaving the way it is and in that case, there's nothing we can do from our end. 

We recently had a similar case which was caused by `google_maps_flutter` in https://github.com/flutter/flutter/issues/112244. The current `google_maps_flutter` plugin doesn't support the M1 simulator, which is why I asked if you had it in your project. Support for that will be added in https://github.com/flutter/flutter/issues/94491

In light of this, I'll be closing this issue as not actionable from our end. If you report this on the `fluttertoast` repo and you are redirected here, kindly leave a comment below this and I will reopen this issue. 

Thank you

**Closed by danagbemava-nc** 2023-01-06 07:20 UTC
Labels: in triage
