### ISSUE TITLE
Unhandled Exception: Cannot get renderObject of inactive element.

### ISSUE THREAD

**Issue by getpu** [flutter/flutter#89902] opened 2021-09-11 07:26 UTC
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Cannot get renderObject of inactive element.
In order for an element to have a valid renderObject, it must be active, which means it is part of the tree.
Instead, this element is in the _ElementLifecycle.defunct state.
If you called this method from a State object, consider guarding it with State.mounted.
The findRenderObject() method was called for the following element:
  StatelessElement#00806(DEFUNCT)

Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (3 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

I had this error after upgrading。

 final RenderObject? renderObject = item.context.findRenderObject();

Can't this version write like this？？？

**Comment by getpu** [comment] 2021-09-11 10:44
I build apk after is normal work... only debug model

**Comment by darshankawar** [comment] 2021-09-13 07:31
@getpu 
Can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

**Comment by getpu** [comment] 2021-09-14 01:48
I used inview_notifier_list  plugins, in previous version is all normally. now this problem will arise in this example. you can try it.

`import 'package:flutter/material.dart';
import 'package:inview_notifier_list/inview_notifier_list.dart';

import 'box.dart';

class MyList extends StatelessWidget {
  final int itemsLength;
  final IsInViewPortCondition? inViewPortCondition;
  final Widget? inViewArea;
  final List<String> initialInViewIds;
  final ScrollController? controller;

  const MyList({
    Key? key,
    this.itemsLength = 30,
    this.inViewPortCondition,
    this.inViewArea,
    this.initialInViewIds = const [],
    this.controller,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final IsInViewPortCondition condition = inViewPortCondition ??
        (double deltaTop, double deltaBottom, double vpHeight) {
          return deltaTop < (0.5 * vpHeight) && deltaBottom > (0.5 * vpHeight);
        };

    return Stack(
      fit: StackFit.expand,
      children: <Widget>[
        InViewNotifierList(
          controller: controller,
          initialInViewIds: initialInViewIds,
          isInViewPortCondition: condition,
          itemCount: itemsLength,
          builder: (BuildContext context, int index) {
            return Container(
              width: double.infinity,
              height: 300.0,
              color: Colors.blueGrey,
              alignment: Alignment.center,
              margin: EdgeInsets.symmetric(vertical: 50.0),
              child: Box(id: '$index'),
            );
          },
        ),
        IgnorePointer(
          ignoring: true,
          child: Align(
            alignment: Alignment.center,
            child: inViewArea ?? Container(),
          ),
        ),
      ],
    );
  }
}`

**Comment by darshankawar** [comment] 2021-09-14 05:55
@getpu 
Since you use a 3rd party plugin, `inview_notifier_list`, it could be a case that the new stable release may have broke some functionality of the plugin, so you'll need to raise this issue in plugin's dedicated repo. https://github.com/rvamsikrishna/inview_notifier_list/issues

I am going ahead and closing this from here. If you think this issue is related to the framework itself and not the plugin, write in comments and I'll reopen it, or if you are able to replicate this issue using core framework without any 3rd party plugin, write in comments here.

**Closed by darshankawar** 2021-09-14 05:55 UTC
Labels: in triage
