### ISSUE TITLE
Testflight app goes in background on iPhone 5C

### ISSUE THREAD

**Issue by ypelud** [flutter/flutter#17619] opened 2018-05-15 18:39 UTC
My app run on simulator, iPhone 6s and iPhone 5c without any issue with the command flutter run.

I build the app for Testflight as describe here: https://flutter.io/ios-release/#create-a-build-archive
After downloading from Testflight the app run on iPhone 6s but not on iPhone 5c.

Noted that I'm on the last master and I've prepare my app to armv7 as describe here: https://github.com/flutter/engine/wiki/iOS-Builds-Supporting-ARMv7

I can see the app starting but it goes on background immediately. I can see it when I double tap on the main button. If I tap on the app in background it goes background again.

Any idea ?

flutter doctor -v

[✓] Flutter (Channel master, v0.4.5-pre.1, on Mac OS X 10.13.4 17E202, locale fr-FR)
    • Flutter version 0.4.5-pre.1 at /Users/yann/Developpement/SDKs/flutter-master
    • Framework revision 4931b46772 (28 hours ago), 2018-05-14 16:36:54 +0200
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/yann/Library/Android/sdk
    • Android NDK at /Users/yann/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/yann/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by ypelud** [comment] 2018-05-16 07:31
I've tried with the app created with flutter create.
Same issue.

**Comment by cbracken** [comment] 2018-06-01 04:43
Closing as dupe of #16124 (which is now fixed on master)

**Closed by cbracken** 2018-06-01 04:43 UTC

**Comment by ypelud** [comment] 2018-06-01 06:59
@cbracken I've tested it works like a charm, thanks a lot for this !

**Comment by cbracken** [comment] 2018-06-01 07:14
@ypelud thanks for confirming!
