### ISSUE TITLE
Odd crash when handling strings

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#47086] opened 2019-12-15 17:46 UTC
Internal: b/145877713

customer:quill reports:

```
Thread 0 main thread CRASHEDArgumentError: Invalid argument(s): string is not well-formed UTF-16
at ParagraphBuilder.addText     (text.dart:1935 )
at TextSpan.build       (text_span.dart:203 )
at TextSpan.build       (text_span.dart:207 )
at TextPainter.layout   (text_painter.dart:543 )
at RenderEditable._layoutText   (editable.dart:1573 )
at RenderEditable.performLayout (editable.dart:1604 )
at RenderObject.layout  (object.dart:1701 )
at RenderProxyBoxMixin.performLayout    (proxy_box.dart:105 )
at RenderObject.layout  (object.dart:1701 )
at RenderProxyBoxMixin.performLayout    (proxy_box.dart:105 )
at RenderObject.layout  (object.dart:1701 )
at RenderProxyBoxMixin.performLayout    (proxy_box.dart:105 )
at RenderObject.layout  (object.dart:1701 )
```

No repro given.

**Comment by yintaibing** [comment] 2019-12-20 06:58
may be same issue caused by emoji.
see [#43302](https://github.com/flutter/flutter/issues/43302) and [#36557](https://github.com/flutter/flutter/issues/36557)

**Comment by wakandan** [comment] 2020-03-10 06:47
I'm having the same issue with utf-16 string. The only difference is I tried to render the text via a Text widget (e.g `Text(some_random_string)`)

**Comment by wakandan** [comment] 2020-03-10 06:49
and this issue https://github.com/flutter/flutter/issues/43302

**Comment by GaryQian** [comment] 2020-03-23 20:18
Emojis can be compounded together using a "zero width joiner", forming an "extended grapheme cluster" which can take up many codepoints. @wakandan are you seeing this with all emojis, or just complex ones (eg, flags, family) emojis? If it happens to complex but not simple ones (basic smileys, etc) then this could be a case of malformed zwj. Maybe the solution is to log an error instead of crash since the user could reasonably enter malformed strings into textfields.

**Comment by jmagman** [comment] 2020-04-30 01:11
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-04-30 01:11 UTC
Labels: a: typography, customer: quill (g3), framework, severe: crash, waiting for customer response
