### ISSUE TITLE
How can we prevent the soft keyboard from popping up

### ISSUE THREAD

**Issue by keiing** [flutter/flutter#145086] opened 2024-03-13 14:21 UTC
### Steps to reproduce

On a large-screen Android device, when an external device is enabled and a USB keyboard is connected, opening an app and pressing keys on the keyboard will not trigger the appearance of the soft keyboard. However, once an input box is selected and gains focus, causing the soft keyboard to pop up, if the soft keyboard is subsequently closed and the focus of the input box is cleared, pressing any key on the keyboard in subsequent operations will still trigger the appearance of the soft keyboard, regardless of whether there is focus on any input box at that moment.
<img width="458" alt="1710338964102" src="https://github.com/flutter/flutter/assets/49868852/522fedc4-75a2-4d64-9ee2-1e0326654d87">

### Expected results

When an Android device is connected to an external keyboard, regardless of whether the soft keyboard has popped up initially or not, pressing keys on the keyboard after the input box has lost focus will not trigger the appearance of the soft keyboard.

### Actual results

If an Android device is connected to an external keyboard, and if the soft keyboard has never popped up before, pressing the keys on the external keyboard will not trigger the appearance of the soft keyboard. However, if the soft keyboard has popped up before, even if there is no input box on the screen and the user presses keys on the keyboard to input, the soft keyboard will still appear.
How can we prevent the soft keyboard from popping up?

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('example app'),
        ),
        body: Column(
          children: [
            TextField(),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<img width="458" alt="1710338964102" src="https://github.com/flutter/flutter/assets/49868852/ca43d954-9829-4e1f-b523-3dfd68c14f4e">

[keyborad.webm](https://github.com/flutter/flutter/assets/49868852/07d79325-218e-4959-a765-9081a9d012fb)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [版本 10.0.22631.3155], locale zh-CN)
    • Flutter version 3.19.3 on channel stable at C:\Users\cc\onSDKS\flutterDir\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\cc\AppData\Local\Android\Sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\cc\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\cc\.jdks\corretto-17.0.9\bin\java.exe
    • Java version OpenJDK Runtime Environment Corretto-17.0.9.8.1 (build 17.0.9+8-LTS)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at C:\Program Files (x86)\Chromebrowser\Chrome.exe)
    ! C:\Program Files (x86)\Chromebrowser\Chrome.exe is not executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.7)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34601.278
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.3
    • Flutter plugin version 77.1.3
    • Dart plugin version 232.10248

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\cc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • sdk gpc x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [版本 10.0.22631.3155]
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 122.0.2365.80

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by keiing** [comment] 2024-03-13 14:24
I hope that after the soft keyboard pops up for the first time, subsequent pressing of keys on the external keyboard will not trigger the appearance of the soft keyboard even if the input box has lost focus.

**Comment by keiing** [comment] 2024-03-13 14:25
I hope that after the soft keyboard pops up for the first time, subsequent pressing of keys on the external keyboard will not trigger the appearance of the soft keyboard even if the input box has lost focus.

**Comment by huycozy** [comment] 2024-03-14 08:33
I can reproduce this issue on the latest stable channel with this setup: casting Android device to host machine (macOS) using [scrcpy](https://github.com/Genymobile/scrcpy) and use the connected physical keyboard to reproduce this. Even when I `unfocus` the TextField when tapping outside it with `FocusScope.of(context).unfocus()`, the issue still occurs.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      title: 'Flutter Demo',
      home: Home(),
    ),
  );
}

class Home extends StatelessWidget {
  const Home({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: const Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}

```
</details>

However, when I switch to master channel, it seems to be fixed. Could you switch to master channel and re-check this with your setup?

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 hours ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.21.0-7.0.pre.25, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.21.0-7.0.pre.25 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fa2f64ad1a (66 minutes ago), 2024-03-13 22:10:38 -0400
    • Engine revision 599dbd7382
    • Dart version 3.4.0 (build 3.4.0-229.0.dev)
    • DevTools version 2.33.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D          • android-arm64  • Android 11 (API 30)
    • iPad (mobile)    • 00008103-000A1464346A201E • ios            • iOS 17.2 21C62
    • macOS (desktop)  • macos                     • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 122.0.6261.128
    ! Error: iPhone has recently restarted. Xcode will continue when iPhone is unlocked. (code -14)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by keiing** [comment] 2024-03-23 07:03
Yes, when I switch to the main channel, I found that using peripheral devices did not call up the soft keyboard display. I have restricted the soft keyboard popping up when pressing the peripheral devices in the stable version.

I would like to ask if in the future motherboard, the soft keyboard input display and the issue of the soft keyboard popping up again after clicking the peripheral keyboard after losing focus in the stable version have been updated and fixed.

<details open><summary>Doctor output</summary>

```console

flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel master, 3.21.0-13.0.pre.20, on Microsoft Windows [版本 10.0.22631.3296], locale zh-CN)
    • Flutter version 3.21.0-13.0.pre.20 on channel master at C:\Users\cc\onSDKS\flutterDir\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 085dbd85f9 (5 hours ago), 2024-03-22 21:43:20 -0400
    • Engine revision 8a51e124fb
    • Dart version 3.4.0 (build 3.4.0-262.0.dev)
    • DevTools version 2.34.0-dev.12
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\cc\AppData\Local\Android\Sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\cc\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at C:\Program Files (x86)\Chromebrowser\Chrome.exe)
    ! C:\Program Files (x86)\Chromebrowser\Chrome.exe is not executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.7)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34601.278
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.3
    • Flutter plugin version 77.1.3
    • Dart plugin version 232.10248

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\cc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • D3 503 (mobile)   • 192.168.0.104:5555 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [版本 10.0.22631.3296]
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 122.0.2365.92

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2024-03-25 04:55
>I would like to ask if in the future motherboard, the soft keyboard input display and the issue of the soft keyboard popping up again after clicking the peripheral keyboard after losing focus in the stable version have been updated and fixed.

It seems you are asking about the time when the fix lands on Flutter stable channel, right? If so, it will take a couple of months to land stable fixes to release channels. You can read more about the build release channels here: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels. 

Since the issue doesn't appear in main/master channel, I'm going to close it as fixed. Thanks for confirming this.

**Closed by huycozy** 2024-03-25 04:55 UTC
Labels: in triage
