### ISSUE TITLE
Future Builder can't work as well as before

### ISSUE THREAD

**Issue by billbull21** [flutter/flutter#58149] opened 2020-05-28 07:48 UTC
why after upgrading my flutter version to 1.17, my future builder can't work as i expected before...

before version 1.17, when my screen/page was onResume or did some change.. future builder will update the data. 
what happend with future builder. did some update or improvement on new version??

and then, i try to do with WidgetBindingObserver to achieve my goal with updating data. and still not working either...

please help me..
sorry about my english, regards

**Comment by Andy-Python-Programmer** [comment] 2020-05-28 08:03
Yes it happens in my app also. I do not know why ?

**Comment by billbull21** [comment] 2020-05-28 09:22
> Yes it happens in my app also. I do not know why ?
> This needs to be solved as my whole app is dependent on futures.
> 
> ### More Information
> The future builder does not update by itself until the page is refreshed. In my case I am using an sql database and when I indirectly refresh the page by searching it shows the next item added to the db. It is problem that needs a solution without real-time functionality it destroys the user experience.

yes, i know that. when the screen have state on Resume.. the data it will be refreshed from future builder

**Comment by TahaTesser** [comment] 2020-05-28 12:20
Hi @billbull21 
Do you think this is a regression?
Can you please provide your `flutter doctor -v`, and a minimal complete reproducible code sample.
Thank you"

**Comment by pushpam5** [comment] 2020-05-28 20:00
I don't think it's a regression because I have used it and i am using flutter version 1.17.1
Here's a snippet of  my flutter doctor -v:



```
Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.17.1 at C:\flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
    • Android SDK at C:\Users\RealMe\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.0-rc1
    • ANDROID_HOME = C:\Users\RealMe\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)


```

**Comment by TahaTesser** [comment] 2020-06-19 15:21
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2020-06-19 15:21 UTC
Labels: in triage, waiting for customer response
