### ISSUE TITLE
[Web] Images can't be loaded only on iOS

### ISSUE THREAD

**Issue by KodaiTakata** [flutter/flutter#47141] opened 2019-12-16 16:56 UTC
I just published website with `firebase hosting` and everything works fine except on only iOS.
Images can't be loaded on iOS.
I'm not sure if it works on macOS or iPadOSeither.
How can I fix this?

Here is the URL

[Link](https://flutter-web-928b9.firebaseapp.com)

And code and flutter doctor output.

`SideKick` is this package.
[Link](https://pub.dev/packages/flutter_sidekick)

Thanks!

```
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: MediaQuery.of(context).size.width * 0.8,
          height: 300.0,
          child: HorizontalImgList(
            images: [
              'web/assets/icon.jpg',
              'web/assets/icon.jpg',
              'web/assets/icon.jpg',
              'web/assets/icon.jpg',
              'web/assets/icon.jpg',
            ],
            radius: 30.0,
            onPressed: (int index) {
              print('pressed: $index');
            },
          ),
        ),
      ),
    );
  }
}

class GreenDivider extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 30.0, vertical: 10.0),
      child: Container(height: 1.5, width: double.infinity, color: Colors.green),
    );
  }
}


class HorizontalImgList extends StatelessWidget {
  final List<String> images;
  final double radius;
  final Function onPressed;
  const HorizontalImgList({
    @required this.images,
    @required this.radius,
    @required this.onPressed
  });
  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        GreenDivider(),
        Center(
          child: Wrap(
            spacing: 4.0,
            runSpacing: 4.0,
            children: List.generate(images.length, (int index) {
             return Sidekick(
               tag: '${index}_${images[index]}',
               targetTag: 'source$index',
               child: GestureDetector(
                 child: CircleAvatar(
                 backgroundColor: Theme.of(context).scaffoldBackgroundColor,
                 backgroundImage: AssetImage(images[index]),
                 radius: radius
               ),
               onTap: () => onPressed(index)
             )
            );
           })
          ),
        ),
       GreenDivider()
      ],
    );
  }
}
```

```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.17763.914], locale ja-JP)
    • Flutter version 1.12.13+hotfix.6 at C:\Users\yusak\Desktop\flutter
    • Framework revision 18cd7a3601 (5 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\yusak\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\yusak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by KodaiTakata** [comment] 2019-12-17 10:49
I found what causes this error.

You can use `Image.asset` with no problems.
But if you use `AssetImage `, this happens.

Any workaround for this?
Thanks!

**Comment by yjbanov** [comment] 2019-12-19 23:42
This seems to be a duplicate of https://github.com/flutter/flutter/issues/46945

/cc @ferhatb

**Closed by yjbanov** 2019-12-19 23:42 UTC
Labels: a: images, e: device-specific, ☸ platform-web
