### ISSUE TITLE
A memory leak occurred while I was using a Canvas receipt image and converting it to ui.Image

### ISSUE THREAD

**Issue by linb1111111** [flutter/flutter#145210] opened 2024-03-15 13:59 UTC
### Steps to reproduce

```dart
void setPixelcolor(List<Offset> points, double brushsize, Color color)(_recorder ??= ui.PictureRecorder()；
_canvas ??= ui.Canvas(_recorder!)；
_canvas?.dravImage(layers[currentEditLayout].uiImage!, Offset.zero, Paint())；
canvas!.drawPoints(
ui.PointMode.points, 
points, 
Paint()
..color = color
..strokeWidth = 1);
_picture = _recorder!.endRecording();
layers[currentEditLayout].uiImage = _picture!.toImageSync(canvassize.width.toInt(),canvassize.height.toInt())；picture!.dispose()；
_picture = null;
```

This is the function executed

### Expected results

Memory is stable

### Actual results

I execute 5000 times, and the memory goes up badly

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-03-18 05:45
Hi @linb1111111 
Which platform are you seeing the issue? And which tool are you using to observe memory? 

For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by linb1111111** [comment] 2024-03-19 02:13
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  ui.Image? layerImg;

  void setPixelColor(List<Offset> points, double brushSize, Color color) async {
    ui.PictureRecorder? recorder = ui.PictureRecorder();
    ui.Canvas? canvas = ui.Canvas(recorder);

    canvas.drawPoints(
        ui.PointMode.points,
        points,
        Paint()
          ..color = color
          ..strokeWidth = 1);

    ui.Picture? picture = recorder.endRecording();

    if (null != layerImg) {
      layerImg!.dispose();
      layerImg = null;
    }

    layerImg = await picture.toImage(1000, 1000);
    picture.dispose();
    recorder = null;
    canvas = null;
    picture = null;
  }

  void _incrementCounter() {
    for (int i = 0; i < 1000; i++) {
      setPixelColor([Offset(1, 1)], 2, Colors.black);
      print(i);
    }
    print('exec sucess!!!');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: TextButton(
          onPressed: _incrementCounter,
          child: const Text('test'),
        ),
      ),
    );
  }
}

import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  ui.Image? layerImg;

  void setPixelColor(List<Offset> points, double brushSize, Color color) async {
    ui.PictureRecorder? recorder = ui.PictureRecorder();
    ui.Canvas? canvas = ui.Canvas(recorder);

    canvas.drawPoints(
        ui.PointMode.points,
        points,
        Paint()
          ..color = color
          ..strokeWidth = 1);

    ui.Picture? picture = recorder.endRecording();

    if (null != layerImg) {
      layerImg!.dispose();
      layerImg = null;
    }

    layerImg = await picture.toImage(1000, 1000);
    picture.dispose();
    recorder = null;
    canvas = null;
    picture = null;
  }

  void _incrementCounter() {
    for (int i = 0; i < 1000; i++) {
      setPixelColor([Offset(1, 1)], 2, Colors.black);
      print(i);
    }
    print('exec sucess!!!');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: TextButton(
          onPressed: _incrementCounter,
          child: const Text('test'),
        ),
      ),
    );
  }
}

import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  ui.Image? layerImg;

  void setPixelColor(List<Offset> points, double brushSize, Color color) async {
    ui.PictureRecorder? recorder = ui.PictureRecorder();
    ui.Canvas? canvas = ui.Canvas(recorder);

    canvas.drawPoints(
        ui.PointMode.points,
        points,
        Paint()
          ..color = color
          ..strokeWidth = 1);

    ui.Picture? picture = recorder.endRecording();

    if (null != layerImg) {
      layerImg!.dispose();
      layerImg = null;
    }

    layerImg = await picture.toImage(1000, 1000);
    picture.dispose();
    recorder = null;
    canvas = null;
    picture = null;
  }

  void _incrementCounter() {
    for (int i = 0; i < 1000; i++) {
      setPixelColor([Offset(1, 1)], 2, Colors.black);
      print(i);
    }
    print('exec sucess!!!');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: TextButton(
          onPressed: _incrementCounter,
          child: const Text('test'),
        ),
      ),
    );
  }
}

**Comment by linb1111111** [comment] 2024-03-19 02:14
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  ui.Image? layerImg;

  void setPixelColor(List<Offset> points, double brushSize, Color color) async {
    ui.PictureRecorder? recorder = ui.PictureRecorder();
    ui.Canvas? canvas = ui.Canvas(recorder);

    canvas.drawPoints(
        ui.PointMode.points,
        points,
        Paint()
          ..color = color
          ..strokeWidth = 1);

    ui.Picture? picture = recorder.endRecording();

    if (null != layerImg) {
      layerImg!.dispose();
      layerImg = null;
    }

    layerImg = await picture.toImage(1000, 1000);
    picture.dispose();
    recorder = null;
    canvas = null;
    picture = null;
  }

  void _incrementCounter() {
    for (int i = 0; i < 1000; i++) {
      setPixelColor([Offset(1, 1)], 2, Colors.black);
      print(i);
    }
    print('exec sucess!!!');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: TextButton(
          onPressed: _incrementCounter,
          child: const Text('test'),
        ),
      ),
    );
  }
}

The above is the smallest instance that can be run

**Comment by linb1111111** [comment] 2024-03-19 02:16
![image](https://github.com/flutter/flutter/assets/163548107/896dfe33-474c-4c89-9373-617e9d7393b4)
![屏幕截图 2024-03-19 101537](https://github.com/flutter/flutter/assets/163548107/d983eb04-bc2a-4b99-8960-d2a523ff9286)

**Comment by linb1111111** [comment] 2024-03-19 02:17
@huycozy thanks four your help

**Comment by linb1111111** [comment] 2024-03-19 02:18
@huycozy thinks for your help

**Comment by linb1111111** [comment] 2024-03-19 02:18
@huycozy thanks for your help

**Comment by linb1111111** [comment] 2024-03-19 02:21
This code does not cause memory explosion in ios but it does cause memory explosion in Android. I tried using toImage but it did not solve my problem @huycozy

**Comment by linb1111111** [comment] 2024-03-19 02:59
flutter doctor -v

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [版本 10.0.22631.3155], locale zh-CN)
    • Flutter version 3.16.5 on channel stable at D:\flutter_windows_3.16.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 months ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Android\SDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\86195\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3155]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.92

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

@huycozy

**Comment by huycozy** [comment] 2024-03-19 07:58
Thanks for the update. I checked this on Android (`Realme 6, Android 11`), ran the example in profile mode but the issue didn't seem to appear:

```console
...
I/flutter (26541): 998
I/flutter (26541): 999
I/flutter (26541): exec sucess!!!
```

>the memory goes up badly

How do you observe this?

Also, I'm on the latest Flutter stable channel 3.19.3. Could you try upgrading your Flutter SDK to this version and re-check?

**Comment by linb1111111** [comment] 2024-03-20 13:53
I switched to the stable version and ran flutter channel stable, which is the latest version 3.16.5，I then switched to the beta version and the problem persisted

**Comment by linb1111111** [comment] 2024-03-20 13:53
I'm not sure if there's a problem with my usage, I don't understand it

**Comment by linb1111111** [comment] 2024-03-20 13:54
@huycozy

**Comment by linb1111111** [comment] 2024-03-20 14:16
I ran flutter --version
Flutter 3.19.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ba39319843 (13 days ago) • 2024-03-07 15:22:21 -0600
Engine • revision 2e4ba9c6fb
Tools • Dart 3.3.1 • DevTools 2.31.1

I've updated the flutter version to be the same as yours, but the issue persists

**Comment by linb1111111** [comment] 2024-03-20 14:17
@huycozy

**Comment by linb1111111** [comment] 2024-03-21 01:12
I went to mac this morning to use ios emulator test, using devtool to check the memory status, found very stable, it seems that the problem exists in the android side @huycozy

**Comment by linb1111111** [comment] 2024-03-21 02:02
This problem also occurred when I was debugging the real thing on my ipad

**Comment by linb1111111** [comment] 2024-03-21 03:11
I call toImageSync very frequently, much more than 100 times, and I reduced the number of calls in the minimal implementation I gave you @huycozy

**Comment by huycozy** [comment] 2024-03-21 05:39
So, you can observe this issue on both Android and iOS, right? 

I also check this by running Android app target in profile mode, and observe memory in Devtools but don't see memory leaks or sudden changes:

<details>
<summary>Devtools memory observation</summary>


https://github.com/flutter/flutter/assets/104349824/d029500f-68b5-4d12-b204-5f60146a87f6


</details>

Can you share the indicators that you think memory is leaking? Or demo the video you see on Devtools > Memory page

(Please write the update in fewer comments that will help the issue easier to read. Thank you!)

**Comment by linb1111111** [comment] 2024-03-21 05:48
Yes, you can currently see this issue on real devices on android and ios

**Comment by linb1111111** [comment] 2024-03-21 06:07
https://github.com/flutter/flutter/assets/163548107/2ad5e4cb-c6ac-4c3a-9695-81173867b9ee

Note that devtool exits automatically later @huycozy

**Comment by linb1111111** [comment] 2024-03-21 06:08
This is also the case if you increase the number of loops

**Comment by linb1111111** [comment] 2024-03-21 06:13
> So, you can observe this issue on both Android and iOS, right?
> 
> I also check this by running Android app target in profile mode, and observe memory in Devtools but don't see memory leaks or sudden changes:
> 
> Devtools memory observation
> Can you share the indicators that you think memory is leaking? Or demo the video you see on Devtools > Memory page
> 
> (Please write the update in fewer comments that will help the issue easier to read. Thank you!)

I took a look at your memory status. Isn't this the realization of a memory leak? Memory grew rapidly. Eventually leading to a crash

**Comment by linb1111111** [comment] 2024-03-21 07:24
I am not sure if this situation is normal, from my understanding I think this situation is not normal, I think the increase memory should be reduced to the size before the increase in a short time. If this were normal I would probably have to rewrite my app in another language or framework, which I would be extremely reluctant to do @huycozy

**Comment by huycozy** [comment] 2024-03-21 13:45
If memory increases suddenly or it is not freed, then it is a valid bug and we need to escalate the issue to the appropriate teams for investigation. However, I need to be able to reproduce this issue first because it needs more clarity.

>I took a look at your memory status. Isn't this the realization of a memory leak? Memory grew rapidly. Eventually leading to a crash

Could you please point out (take a screenshot) from my demo when you see the memory leak? I am trying to understand the problem by giving factual demo and observable aspects. It would be better if you could also show a demo from your side (video/screenshot) that would move the issue along faster. Thank you!

**Comment by linb1111111** [comment] 2024-03-21 14:01
I think we may need to adjust our perspective on this problem. My current words are that if memory goes up and there is no gc to release, I think it is a memory leak. Because I can't understand why memory keeps rising without being freed after calling this function, it is a very important problem for me. Is there something wrong with my writing? If there is nothing wrong with my writing, then why didn't the intrinsic value fall after rising? I've considered some issues, such as the execution gap is too small, it doesn't have time to do gc, if this were the case, i think it would do a gc operation after a period of idle time, which means that its memory usage would drop, but i did not see the results i expected @huycozy

**Comment by linb1111111** [comment] 2024-03-21 14:11
And very importantly, I need to determine whether this is a bug or not. This is related to whether I need to rewrite this APP in other languages, thank you very much

**Comment by huycozy** [comment] 2024-03-22 04:39
>if memory goes up and there is no gc to release, I think it is a memory leak.
>i think it would do a gc operation after a period of idle time, which means that its memory usage would drop

Thanks, I got your point. It seems the memory has not been freed even though you disposed of objects each time creating image from picture. 

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (29 hours ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.58

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.21.0-12.0.pre.40, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.21.0-12.0.pre.40 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d755bc222b (28 minutes ago), 2024-03-21 19:44:55 -0700
    • Engine revision e2f324beac
    • Dart version 3.4.0 (build 3.4.0-257.0.dev)
    • DevTools version 2.34.0-dev.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.58

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by linb1111111** [comment] 2024-03-22 04:44
> > if memory goes up and there is no gc to release, I think it is a memory leak.
> > i think it would do a gc operation after a period of idle time, which means that its memory usage would drop
> 
> Thanks, I got your point. It seems the memory has not been freed even though you disposed of objects each time creating image from picture.
> 
> flutter doctor -v (stable and master)

Yes, I don't understand it. And I need to know if it's a bug, and if so, roughly how long it will take to fix. This is related to my follow-up tools, currently there are some users waiting for my app. @huycozy

**Comment by linb1111111** [comment] 2024-03-22 04:47
At present, I need to determine whether this is a bug or not, and whether there is a problem in my operation, which relates to my subsequent work. Please reply as soon as possible. Thank you very much @huycozy

**Comment by jason-simmons** [comment] 2024-03-24 22:51
This is a known issue in the implementation of `toImageSync`.  See https://github.com/flutter/flutter/issues/138627#issuecomment-1839815337

An image returned by `toImageSync` holds a reference to the display list that was used to create the image.

The code in https://github.com/flutter/flutter/issues/145210#issue-2188584551 is drawing the image returned by the previous `toImageSync` call into the current picture.  When `toImageSync` is called on the current picture, it will retain a reference to the previous `toImageSync` image and its display list.  As the app continues to reuse `toImageSync` output in new pictures, it will effectively build a linked list of all the previous images that will consume unbounded amounts of memory.

Use `toImage` instead of `toImageSync` to create a bitmap that does not need to hold the picture's display list.

**Comment by jonahwilliams** [comment] 2024-03-25 17:33
I'm going to close this issue, its xref'd in #138627 which is the caconical issue for this bug.

**Closed by jonahwilliams** 2024-03-25 17:33 UTC
Labels: engine, c: performance, perf: memory, has reproducible steps, team-engine, found in release: 3.19, found in release: 3.21
