### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by predatorx7** [flutter/flutter#99061] opened 2022-02-24 12:25 UTC
## Command
```
flutter run --flavor development lib/main_devel.dart
```

## Steps to Reproduce

I don't know how to reproduce this issue. This happened when performing hot reload on an Android TV.

## Logs
SentinelException
```
[Sentinel kind: Collected, valueAsString: <collected>] from reloadSources()
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1718:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2225:21)
#2      VmService.reloadSources (package:vm_service/src/vm_service.dart:2084:7)
#3      _reloadDeviceSources (package:flutter_tools/src/run_hot.dart:1185:32)
<asynchronous suspension>
#4      _defaultReloadSourcesHelper (package:flutter_tools/src/run_hot.dart:1124:65)
<asynchronous suspension>
#5      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:906:38)
<asynchronous suspension>
#6      HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:818:16)
<asynchronous suspension>
#7      HotRunner.restart (package:flutter_tools/src/run_hot.dart:720:36)
<asynchronous suspension>
#8      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1627:40)
<asynchronous suspension>
#9      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1680:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.527], locale en-IN)
    • Flutter version 2.10.2 at D:\Devel\flutter_2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (5 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Linux\devel\android-sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\Apps\IntelliJ IDEA 2021.2.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at C:\Users\smush\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[✓] Connected device (4 available)
    • MiTV AESP0 (mobile) • 192.168.5.163:5555 • android-arm    • Android 9 (API 28)
    • Windows (desktop)   • windows            • windows-x64    • Microsoft Windows [Version 10.0.22000.527]
    • Chrome (web)        • chrome             • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)          • edge               • web-javascript • Microsoft Edge 98.0.1108.56

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.2.14+22010124
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
android_intent-2.0.2
appsflyer_sdk-6.5.2
auto_orientation-2.2.1
device_configs
device_info_plus-3.2.2
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.2
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
device_information-0.0.4
facebook_app_events-0.14.8
firebase_analytics-9.1.0
firebase_analytics_web-0.4.0+6
firebase_app_check-0.0.6+5
firebase_app_check_web-0.0.5+5
firebase_core-1.12.0
firebase_core_web-1.5.4
firebase_crashlytics-2.5.1
firebase_performance-0.8.0+5
firebase_performance_web-0.1.0+5
flutter_html_to_pdf-0.7.0
flutter_windowmanager-0.2.0
in_app_review-2.0.4
onesignal_flutter-3.2.8
open_file-3.2.1
package_info_plus-1.4.0
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.4
path_provider-2.0.9
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
permission_handler-9.1.0
permission_handler_android-9.0.2
permission_handler_apple-9.0.2
share_plus-3.1.0
share_plus_macos-2.0.2
share_plus_web-2.0.4
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sms_autofill-2.2.0
sqflite-2.0.2
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.8
url_launcher_windows-3.0.0
video_player-2.2.18
video_player_android-2.3.0
video_player_avfoundation-2.3.0
video_player_web-2.0.7
video_player_web_hls-0.1.11+4
wakelock-0.6.1+1
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.0
webview_flutter_android-2.8.3
webview_flutter_wkwebview-2.7.1

**Comment by danagbemava-nc** [comment] 2022-02-25 10:16
Duplicate of #78214

**Closed by danagbemava-nc** 2022-02-25 10:16 UTC
Labels: in triage
