### ISSUE TITLE
[go_router] Duplicate GlobalKey detected in widget tree exception thrown in Flutter Web when click web browser backward button

### ISSUE THREAD

**Issue by pickledbrill** [flutter/flutter#145075] opened 2024-03-13 09:41 UTC
### Steps to reproduce

In debug mode, click `Go To PageTwo` button to navigate to PageTwo, then click the back button of the browser to return to PageOne.

### Expected results

PageOne should be displayed.

### Actual results

The view doesn't change, the debug portal throws `Duplicate GlobalKey detected in widget tree` exception.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

GlobalKey<NavigatorState> rootNavigatorKey = GlobalKey<NavigatorState>();

final router = GoRouter(
    debugLogDiagnostics: true,
    navigatorKey: rootNavigatorKey,
    initialLocation: "/",
    routes: [
      GoRoute(path: '/', builder: (context, state) => const PageOne()),
      GoRoute(path: '/2', builder: (context, state) => const PageTwo()),
    ]);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: MaterialApp.router(
          routerConfig: router,
        ));
  }
}

class PageOne extends StatelessWidget {
  const PageOne({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('PageOne'),
            const SizedBox(
              height: 30,
            ),
            ElevatedButton(
                onPressed: () {
                  context.go('/2');
                },
                child: const Text('Go To PageTwo'))
          ],
        ),
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  const PageTwo({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('Page Two'),
            const SizedBox(
              height: 30,
            ),
            ElevatedButton(
                onPressed: () {
                  context.go('/');
                },
                child: const Text('Back to PageOne'))
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![1](https://github.com/flutter/flutter/assets/52510584/83a60b3a-e4e4-4919-ab66-883d05cbaf23)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.19.3 on channel stable at /Users/billchen/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /Users/billchen/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA 2.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-03-13 11:45
Thanks for the report. I also can reproduce this issue.

<details>
<summary>Output exception</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.
The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of
the widget tree being truncated unexpectedly, because the second time a key is seen, the previous
instance is moved to the new location. The key was:
- [LabeledGlobalKey<NavigatorState>#37443]
This was determined by noticing that after the widget with the above global key was moved out of its
previous parent, that previous parent never updated during this frame, meaning that it either did
not update at all or updated before the widget was moved, in either case implying that it still
thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to
GlobalKey reparenting is:
- HeroControllerScope
A GlobalKey can only be specified on one widget at a time in the widget tree.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
packages/flutter/src/widgets/framework.dart 3235:15                               <fn>
packages/flutter/src/widgets/framework.dart 3259:16                               finalizeTree
packages/flutter/src/widgets/binding.dart 1028:7                                  drawFrame
packages/flutter/src/rendering/binding.dart 443:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1392:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1313:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1171:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1404:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 307:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 187:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 hours ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.21.0-4.0.pre.37, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.21.0-4.0.pre.37 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8270872f86 (3 hours ago), 2024-03-12 17:52:24 -0700
    • Engine revision ea848c3b24
    • Dart version 3.4.0 (build 3.4.0-227.0.dev)
    • DevTools version 2.33.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 122.0.6261.112
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by pickledbrill** [comment] 2024-03-14 07:20
> I encountered the same since upgrading to **Flutter 3.19.3** and the latest **GoRouter 13.2.0** for my **Flutter Web** project. The issue does not only create duplicate GlobalKey, it creates duplicate of branches of widgets under MaterialApp.router during rebuild of pages navigation. In my case, whenever the page is refresh or the signs out. Please have a look at the Widget Inspector below. 4 scaffolds were rebuild when I click on page refresh.
> 
> ![Screenshot 2024-03-14 at 3 00 39 PM](https://private-user-images.githubusercontent.com/46311851/312732725-3a05bb09-ef9f-493a-a7f4-1baf1a668494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDA3MzIsIm5iZiI6MTcxMDQwMDQzMiwicGF0aCI6Ii80NjMxMTg1MS8zMTI3MzI3MjUtM2EwNWJiMDktZWY5Zi00OTNhLWE3ZjQtMWJhZjFhNjY4NDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3MTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMDY3YzY1YWYwNGI4YjI5MDU1OGY0OGRlM2JhYjUxNjU2MTk4MjBjMTY0NDBlODVkZjJhZjE2YjhkMTU5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0jjPs1mlCgSo-6YOt7CN7HGsuQR_JovSNRlkER07Tk)
> 
> Because of the rebuild, other than GlobalKey, it also duplicates the ScrollController.
> 
> When the widget tree becomes unstable, the following exception comes out:
> 
> ════════ Exception caught by scheduler library ═════════════════════════════════
> 
> The following assertion was thrown during a scheduler callback:
> 
> Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:91:12 !isDisposed "Trying to render a disposed EngineFlutterView."
> 
> When the exception was thrown, this was the stack: http://localhost:55987/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3 throw_ http://localhost:55987/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3 assertFailed http://localhost:55987/lib/_engine/engine/window.dart 91:13 render http://localhost:55987/packages/flutter/src/rendering/view.dart 256:7 compositeFrame http://localhost:55987/packages/flutter/src/rendering/binding.dart 587:19 drawFrame http://localhost:55987/packages/flutter/src/widgets/binding.dart 991:13 drawFrame http://localhost:55987/packages/flutter/src/rendering/binding.dart 448:5 [_handlePersistentFrameCallback] http://localhost:55987/packages/flutter/src/scheduler/binding.dart 1386:7 [_invokeFrameCallback] http://localhost:55987/packages/flutter/src/scheduler/binding.dart 1311:9 handleDrawFrame http://localhost:55987/packages/flutter/src/scheduler/binding.dart 1169:5 [_handleDrawFrame] http://localhost:55987/lib/_engine/engine/platform_dispatcher.dart 1346:5 invoke http://localhost:55987/lib/_engine/engine/platform_dispatcher.dart 260:5 invokeOnDrawFrame http://localhost:55987/lib/_engine/engine/initialization.dart 185:36 http://localhost:55987/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37 _checkAndCall http://localhost:55987/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39 dcall
> 
> ════════════════════════════════════════════════════════════════════════════════

The problem you're facing may have been solved on beta/master channel, please take a look at this: [https://github.com/flutter/flutter/issues/141253](url)

**Comment by pickledbrill** [comment] 2024-03-14 09:01
> > > I encountered the same since upgrading to **Flutter 3.19.3** and the latest **GoRouter 13.2.0** for my **Flutter Web** project. The issue does not only create duplicate GlobalKey, it creates duplicate of branches of widgets under MaterialApp.router during rebuild of pages navigation. In my case, whenever the page is refresh or the signs out. Please have a look at the Widget Inspector below. 4 scaffolds were rebuild when I click on page refresh.
> > > ![Screenshot 2024-03-14 at 3 00 39 PM](https://private-user-images.githubusercontent.com/46311851/312732725-3a05bb09-ef9f-493a-a7f4-1baf1a668494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDA3MzIsIm5iZiI6MTcxMDQwMDQzMiwicGF0aCI6Ii80NjMxMTg1MS8zMTI3MzI3MjUtM2EwNWJiMDktZWY5Zi00OTNhLWE3ZjQtMWJhZjFhNjY4NDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3MTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMDY3YzY1YWYwNGI4YjI5MDU1OGY0OGRlM2JhYjUxNjU2MTk4MjBjMTY0NDBlODVkZjJhZjE2YjhkMTU5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v0jjPs1mlCgSo-6YOt7CN7HGsuQR_JovSNRlkER07Tk)
> > > Because of the rebuild, other than GlobalKey, it also duplicates the ScrollController.
> > > When the widget tree becomes unstable, the following exception comes out:
> > > ════════ Exception caught by scheduler library ═════════════════════════════════
> > > The following assertion was thrown during a scheduler callback:
> > > Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:91:12 !isDisposed "Trying to render a disposed EngineFlutterView."
> > > When the exception was thrown, this was the stack: http://localhost:55987/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3 throw_ http://localhost:55987/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3 assertFailed http://localhost:55987/lib/_engine/engine/window.dart 91:13 render http://localhost:55987/packages/flutter/src/rendering/view.dart 256:7 compositeFrame http://localhost:55987/packages/flutter/src/rendering/binding.dart 587:19 drawFrame http://localhost:55987/packages/flutter/src/widgets/binding.dart 991:13 drawFrame http://localhost:55987/packages/flutter/src/rendering/binding.dart 448:5 [_handlePersistentFrameCallback] http://localhost:55987/packages/flutter/src/scheduler/binding.dart 1386:7 [_invokeFrameCallback] http://localhost:55987/packages/flutter/src/scheduler/binding.dart 1311:9 handleDrawFrame http://localhost:55987/packages/flutter/src/scheduler/binding.dart 1169:5 [_handleDrawFrame] http://localhost:55987/lib/_engine/engine/platform_dispatcher.dart 1346:5 invoke http://localhost:55987/lib/_engine/engine/platform_dispatcher.dart 260:5 invokeOnDrawFrame http://localhost:55987/lib/_engine/engine/initialization.dart 185:36 http://localhost:55987/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37 _checkAndCall http://localhost:55987/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39 dcall
> > > ════════════════════════════════════════════════════════════════════════════════
> > 
> > 
> > The problem you're facing may have been solved on beta/master channel, please take a look at this: [https://github.com/flutter/flutter/issues/141253](url)
> 
> Thank you for letting me the solution on beta/master. I've checked both. Unfortunately the issue of Duplicate GlobalKey is still there. The child under MaterialApp.router duplicates itself after rebuild from user signout.
> 
> ![Screenshot 2024-03-14 at 4 21 19 PM](https://private-user-images.githubusercontent.com/46311851/312760958-c9a9cc9b-bb1a-4661-9d39-8d41a5046b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDY3MTgsIm5iZiI6MTcxMDQwNjQxOCwicGF0aCI6Ii80NjMxMTg1MS8zMTI3NjA5NTgtYzlhOWNjOWItYmIxYS00NjYxLTlkMzktOGQ0MWE1MDQ2YjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA4NTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZGYxYzI1ZTUxMjlmYWY1OTQ2NmVjODg2YTdiYThlYjY5MjQxMDQxYzc3ODdmNmQ5MmMwNDgxNDI1MmY5NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ag_h3U18OvH_ZZ_sAf25DmUOAmTVumE2MQEzGoGGv64)

I found If we assign `UniqueKey` to the widget, then the Duplicate error would be gone. But I don't think that's the correct way to solve the issue.
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      key: UniqueKey(),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('PageOne'),
            const SizedBox(
              height: 30,
            ),
            ElevatedButton(
              onPressed: () {
                context.go('/2');
              },
              child: const Text('Go To PageTwo'),
            ),
          ],
        ),
      ),
    );
  }
```

**Comment by pickledbrill** [comment] 2024-04-16 07:37
Any updates on this issue?

**Comment by VictorJava** [comment] 2024-09-10 08:16
I’m experiencing the same issue, which seems to be related to the GoRouter.of library. In my custom AppBar, I check canPop using the injected GoRouter with getIt<AppRouter>().canPop().

The issue is resolved if I replace it with GoRouter.of(context).canPop().

It’s important to note that the crash only occurs when the next route overrides the previous one. For example:
- Login route -> Main route (where the canPop check is located) -> crash occurs.
- If the user is already logged in (skipping the login route) -> Main route -> no crash.

As mentioned, replacing getIt<AppRouter>().canPop() with GoRouter.of(context).canPop() solved the issue for me.

**Comment by hangyujin** [comment] 2024-10-14 13:20
I'm closing this per comment https://github.com/flutter/flutter/issues/145075#issuecomment-2399714930 since this is a misconfiguration

**Closed** 2024-10-14 13:20 UTC
Labels: platform-web, package, has reproducible steps, P1, p: go_router, team-go_router, triaged-go_router, :hourglass_flowing_sand:, found in release: 3.19, found in release: 3.21
