### ISSUE TITLE
Doesn't work on IOS simulator

### ISSUE THREAD

**Issue by therasuldev** [flutter/flutter#127707] opened 2023-05-26 21:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Launching lib/main.dart on iPhone 14 in debug mode...
main.dart:1
Xcode build done.                                           12.4s
Failed to build iOS app
Error (Xcode): ../../../FlutterDev/flutter/packages/flutter_test/lib/src/_goldens_io.dart:12:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/test_api-0.6.0/lib/expect.dart': No such file or directory
_goldens_io.dart:12
Could not build the application for the simulator.
Error launching application on iPhone 14.
Exited

### Expected results

Launching lib/main.dart on iPhone 14 in debug mode...
main.dart:1
Xcode build done.                                           12.4s
Failed to build iOS app
Error (Xcode): ../../../FlutterDev/flutter/packages/flutter_test/lib/src/_goldens_io.dart:12:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/test_api-0.6.0/lib/expect.dart': No such file or directory
_goldens_io.dart:12
Could not build the application for the simulator.
Error launching application on iPhone 14.
Exited

### Actual results

Launching lib/main.dart on iPhone 14 in debug mode...
main.dart:1
Xcode build done.                                           12.4s
Failed to build iOS app
Error (Xcode): ../../../FlutterDev/flutter/packages/flutter_test/lib/src/_goldens_io.dart:12:8: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/test_api-0.6.0/lib/expect.dart': No such file or directory
_goldens_io.dart:12
Could not build the application for the simulator.
Error launching application on iPhone 14.
Exited

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Dionysius7** [comment] 2023-05-27 08:51
I have the same issue, please help :(

<img width="1453" alt="image" src="https://github.com/flutter/flutter/assets/44280445/55ddb1d1-7fda-40a1-917c-1eb990b5e701">

**Comment by therasuldev** [comment] 2023-05-27 09:07
Your project is old or new ?

сб, 27 мая 2023 г., 12:51 lostmusic ***@***.***>:

**Comment by DiRuffy** [comment] 2023-05-27 13:26
same problem

**Comment by huycozy** [comment] 2023-05-29 05:02
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/127571.

**Closed by huycozy** 2023-05-29 05:02 UTC
Labels: in triage
