### ISSUE TITLE
When there is an Image in the ListView, the value of controller.position.maxScrollExtent will change. Is this a bug?

### ISSUE THREAD

**Issue by huang-weilong** [flutter/flutter#25448] opened 2018-12-17 07:22 UTC
For example, I build a `ListView `that contains 200 `Text `widgets. No matter where I scroll the list, the `maxScrollExtent `I get is the same, which is the same as expected.print `maxScrollExtent:2639.0`
code:
```dart
class _Test4State extends State<Test4> {
  ScrollController controller = ScrollController();
  List<Widget> list = List.generate(200, (index) {
    return Text('item  $index');
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
        elevation: 0.0,
        actions: <Widget>[
          IconButton(
              icon: Icon(Icons.room),
              onPressed: () {
                print('maxScrollExtent:${controller.position.maxScrollExtent}');
                controller.jumpTo(controller.position.maxScrollExtent);
              })
        ],
      ),
      body: Center(
        child: ListView(
          controller: controller,
          children: list.toList(),
        ),
      ),
    );
  }
}
```
However, when I insert one (or more) `Image `widgets in it, the value of `maxScrollExtent `will be problematic.
Change the above `list `to:
```dart
List<Widget> list = List.generate(200, (index) {
    if (index == 130) return Image.asset('assets/images/img.jpg');
    return Text('item  $index');
  });
```
Now when I get the value of `maxScrollExtent `in the first click, I got `maxScrollExtent:2639.0`, This is not the distance of max. The value of `maxScrollExtent `obtained by clicking the button again is `maxScrollExtent:3009.4615384615386`

**Comment by zoechi** [comment] 2018-12-17 09:00
I wild guess is this is due the elements being of various height. If Flutter doesn't render all items, it can only calculate the `maxScrollExtent` using the heights of the rendered (visible) items.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce. 

Please also add the output of `flutter doctor -v`.

**Comment by huang-weilong** [comment] 2018-12-17 09:19
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  ScrollController controller = ScrollController();
  List<Widget> list = List.generate(200, (index) {
    if (index == 100) return Image.asset('assets/images/img.jpg');
    return Text('item  $index');
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Demo Home Page'),
        elevation: 0.0,
      ),
      body: Center(
        child: ListView(
          controller: controller,
          children: list.toList(),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Text('print'),
        onPressed: () {
          print('maxScrollExtent:${controller.position.maxScrollExtent}');
          controller.jumpTo(controller.position.maxScrollExtent);
        },
      ),
    );
  }
}
```
Image, you may need to add one yourself.

**Comment by huang-weilong** [comment] 2018-12-17 09:20
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.471], locale zh-CN)
    • Flutter version 1.0.0 at D:\flutter\flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\55045\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected device (1 available)
    • vivo X6D • UOGUJFT4TCQ479JJ • android-arm64 • Android 5.1 (API 22)

• No issues found!
```

**Comment by zoechi** [comment] 2018-12-19 15:54
Same behavior with 
```dart
class _MyHomePageState extends State<MyHomePage> {
  ScrollController controller = ScrollController();
  List<Widget> list = List.generate(200, (index) {
    if (index == 100) {
//      return Image.asset(
//          'packages/flutter_gallery_assets/food/butternut_squash_soup.png');
      return SizedBox(height: 250, child: Text('item sized $index'));
    }
    return Text('item  $index');
  });
```

So the list calculates the scroll extent from the height of the currently visible items and the length of the data. It doesn't know the height of the items outside the visible area because they are not rendered for performance reasons.

This is why #12319 is difficult to implement. 

I'm going to close as duplicate.
Feel free to add a comment if you disagree to have it reopened.

**Comment by zoechi** [comment] 2018-12-19 15:54
Duplicate of #12319

**Closed by zoechi** 2018-12-19 15:54 UTC
Labels: f: scrolling, framework
