### ISSUE TITLE
[Flutter Web - 2.5] Hot Restart not working in Flutter Web

### ISSUE THREAD

**Issue by AbhishekDoshi26** [flutter/flutter#90120] opened 2021-09-15 11:31 UTC
## Steps to Reproduce

1. Run default app in web and click on hot-restart.
### Reproducible code: https://github.com/AbhishekDoshi26/password_manager

**Expected results:** Hot Restart should work

**Actual results:** Hot Restart is taking an infinite time

## Logs
<details>
  <summary> flutter run -v </summary>

```
flutter run -v
[  +60 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[   +1 ms] executing: [C:\flutter/] git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[  +45 ms] Exit code 0 from: git tag --points-at 4cc385b4b84ac2f816d939a49ea1f328c4e0b48e
[        ] 2.5.0
[   +8 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +95 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +68 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +53 ms] executing: C:\Users\Bacancy Technology\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +37 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +73 ms] Multiple devices found:
[  +21 ms] Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82
[        ] Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.47
[   +1 ms] [1]: Chrome (chrome)
[   +1 ms] [2]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+2094 ms] 1
[  +19 ms] Skipping pub get: version match.
[ +123 ms] Generating D:\Flutter Projects\password_manager\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +81 ms] Launching lib\main.dart on Chrome in debug mode...
[ +104 ms] Updating assets
[  +74 ms] Waiting for connection from debug service on Chrome...
[  +92 ms] <- reset
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\BACANC~1\AppData\Local\Temp\flutter_tools.2b2b1488\flutter_tool.e6c693e\app.dill --libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages D:\Flutter
Projects\password_manager\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\BACANC~1\AppData\Local\Temp\flutter_tools.2b2b1488\flutter_tools.303ec221 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[   +9 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+13999 ms] Waiting for connection from debug service on Chrome... (completed in 14.1s)
[   +1 ms] Synced 26.2MB.
[        ] <- accept
[        ] Caching compiled dill
[ +740 ms] [CHROME]:
[   +4 ms] [CHROME]:DevTools listening on ws://127.0.0.1:61272/devtools/browser/c0734545-6616-413e-a0b8-0f4cf20d26d8
[ +336 ms] DwdsInjector: Received request for entrypoint at http://localhost:61260/main_module.bootstrap.js
[   +7 ms] MetadataProvider: Loading debug metadata...
[  +27 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +14 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:61260/main_module.bootstrap.js
[+1422 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +63 ms] DevHandler: Debug service listening on ws://127.0.0.1:56829/Qkvu4JYTkSI=/ws

[  +23 ms] This app is linked to the debug service: ws://127.0.0.1:56829/Qkvu4JYTkSI=/ws
[  +11 ms] Debug service listening on ws://127.0.0.1:56829/Qkvu4JYTkSI=/ws
[        ]  Running with sound null safety 
[   +3 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:56829/Qkvu4JYTkSI=
[ +652 ms] DevTools activation throttled until 2021-09-16 00:55:48.340409.
[ +646 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:56829/Qkvu4JYTkSI=
[+9830 ms] Performing hot restart...
[   +6 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +4 ms] Skipping target: gen_dart_plugin_registrant
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[  +39 ms] Scanned through 523 files in 38ms
[        ] Waiting for connection from debug service on Chrome...
[   +2 ms] <- recompile org-dartlang-app:/web_entrypoint.dart cf411f94-c28b-4500-82d1-b7628c095ebe
[   +1 ms] <- cf411f94-c28b-4500-82d1-b7628c095ebe
[  +14 ms] Waiting for connection from debug service on Chrome... (completed in 16ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] DwdsVmClient: Attempting a hot restart
[   +1 ms] DwdsVmClient: Attempting to disable breakpoints and resume the isolate
[+3917 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[        ] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[  +19 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +21 ms] DwdsVmClient: $dartHotRestart request complete.
[        ] DwdsVmClient: Waiting for Isolate Start event.
[   +1 ms] DwdsVmClient: Successful hot restart
[   +6 ms] Performing hot restart... (completed in 4.1s)
[        ] Restarted application in 4,057ms.
[+46608 ms] Performing hot restart...
[   +3 ms] Skipping target: gen_localizations
[   +1 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[  +32 ms] Scanned through 523 files in 32ms
[        ] Waiting for connection from debug service on Chrome...
[        ] <- recompile org-dartlang-app:/web_entrypoint.dart 47110534-6279-4a25-a40d-d1e55af31fcc
[        ] package:password_manager/screens/home/home.dart
[        ] <- 47110534-6279-4a25-a40d-d1e55af31fcc
[  +58 ms] Waiting for connection from debug service on Chrome... (completed in 59ms)
[        ] Synced 0.0MB.
[        ] <- accept
[        ] DwdsVmClient: Attempting a hot restart
[        ] DwdsVmClient: Attempting to disable breakpoints and resume the isolate
[+37022 ms] Ignoring terminal input: "R" because we are busy.
[+55434 ms] Ignoring terminal input: "R" because we are busy.
[+1277 ms] Ignoring terminal input: "q" because we are busy.
```
</details>

<details>
<summary> flutter analyze </summary>

```
flutter analyze
Analyzing password_manager...
No issues found! (ran in 1.2s)
```
</details>

<details>
<summary> flutter doctor </summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1165], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1)
[√] VS Code (version 1.60.1)
[√] Connected device (2 available)
```
</details>

**Comment by danagbemava-nc** [comment] 2021-09-15 13:45
Hi @AbhishekDoshi26, while I can reproduce this issue on `stable`, I cannot reproduce it on `master`. 

Can you confirm if you can reproduce the issue on `master`?

**Comment by AbhishekDoshi26** [comment] 2021-09-15 13:54
@danagbemava-nc Sure, let me checkthe same

**Comment by AbhishekDoshi26** [comment] 2021-09-15 14:02
@danagbemava-nc Not reproducible in master!

**Comment by danagbemava-nc** [comment] 2021-09-15 14:03
Thanks for confirming. 

Closing as fixed.

**Closed by danagbemava-nc** 2021-09-15 14:03 UTC
Labels: in triage
