### ISSUE TITLE
Unhandled error MissingPluginException when running on Android, no issues in iOS

### ISSUE THREAD

**Issue by jorjyeah** [flutter/flutter#75320] opened 2021-02-03 11:24 UTC
```
E/flutter (25706): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Unhandled error MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in) occurred in bloc Instance of 'SocmedSignInBloc'.
E/flutter (25706): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (25706): <asynchronous suspension>
E/flutter (25706): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (25706): #2      MethodChannelGoogleSignIn.init (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:28:20)
E/flutter (25706): #3      GoogleSignIn._ensureInitialized (package:google_sign_in/google_sign_in.dart:249:62)
E/flutter (25706): #4      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:231:11)
E/flutter (25706): #5      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:288:18)
E/flutter (25706): #6      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:359:9)
....

```
I've developed an app and runs on iOS and Android and I use google_sign_in + flutter_facebook_auth. I had an issue missing plugin when I run my app on Android. Nothing wrong with iOS, all work well. I've been looking for an answer on StackOverflow but mostly suggest to run "flutter clean" and rebuild the app. 

note:
I've also checked my firebase and I thought there was nothing wrong with it.

**pubspect.yaml**
<img width="242" alt="Screen Shot 2021-02-03 at 18 07 17" src="https://user-images.githubusercontent.com/33625457/106738568-a9f5bf80-664a-11eb-9240-75f12bbc1654.png">

**Comment by TahaTesser** [comment] 2021-02-03 14:22
Hi @jorjyeah 
This might be caused by the third-party package  `flutter_facebook_auth`, please try again without third-party packages. 

 if you can reproduce the issue using `google_sign_in`. , Can you please provide your `flutter doctor -v`  and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by jorjyeah** [comment] 2021-02-04 03:45
> Hi @jorjyeah
> This might be caused by the third-party package `flutter_facebook_auth`, please try again without third-party packages.
> 
> If you can reproduce the issue using `google_sign_in`. , Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> Thank you

I've already figured it out. The first problem is, I don't generate keystore and not update buildType in build.gradle. But, I don't know why there are no instructions to do that. Second, yes, flutter_facebook_auth also caused another problem. When I add flutter_facebook_auth with google_sign_in it will replicate the same error as before.

**Comment by jorjyeah** [comment] 2021-02-04 03:47
![IMAGE 2021-02-04 10:46:47](https://user-images.githubusercontent.com/33625457/106842288-5466f480-66d6-11eb-98c3-3b59e1844c6e.jpg)

here it is @TahaTesser

**Comment by TahaTesser** [comment] 2021-02-04 07:28
Hi @jorjyeah 
If you're building for release, you can follow [Build and release an Android app](https://flutter.dev/docs/deployment/android)
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/darwin-morocho/flutter-facebook-auth/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-04 07:28 UTC
Labels: in triage

**Comment by alectogeek** [comment] 2021-02-08 00:12
@jorjyeah Have you figured out the cause of the problem?
I also have the same error after adding facebook_app_events to my app. Looks like it conflicting with firebase_core somehow

**Comment by jorjyeah** [comment] 2021-02-08 02:38
@alectogeek I try to combine google_sign_in and flutter_facebook_auth but it turns out the error I mentioned before. So, I use another package to flutter_facebook_login. And it works well.
