### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by cinacio-cross** [flutter/flutter#154928] opened 2024-09-10 16:05 UTC
## Command
```sh
flutter run --flavor dev -t lib/main_dev.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:261:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1778:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1790:8)
#3      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#4      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#5      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.2, on Ubuntu 24.04.1 LTS 6.8.0-41-generic, locale fr_FR.UTF-8)
    [32m•[39m Flutter version 3.24.2 on channel stable at /usr/bin/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4cf269e36d (il y a 7 jours), 2024-09-03 14:30:00 -0700
    [32m•[39m Engine revision a6bd3f1de1
    [32m•[39m Dart version 3.5.2
    [32m•[39m DevTools version 2.37.2

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /home/carlos/Android/Sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/linux-android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Ubuntu clang version 18.1.3 (1ubuntu1)
    [32m•[39m cmake version 3.28.3
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 1.8.1

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /opt/android-studio-2024.1.2/android-studio
    [32m•[39m Flutter plugin version 81.0.2
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[33m[!][39m Android Studio (version unknown)
    [32m•[39m Android Studio at /opt/android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to determine Android Studio version.
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.93.0)
    [32m•[39m VS Code at /snap/code/current/usr/share/code
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    [32m•[39m Linux (desktop)              • linux         • linux-x64      • Ubuntu 24.04.1 LTS 6.8.0-41-generic
    [32m•[39m Chrome (web)                 • chrome        • web-javascript • Google Chrome 100.0.4896.75

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4cf269e36de2573851eaef3c763994f8f9be494d
### Plugins
cloud_firestore-5.4.0
cloud_firestore_web-4.2.0
firebase_auth-5.2.0
firebase_auth_web-5.12.6
firebase_core-3.4.0
firebase_core_web-2.17.5
flutter_plugin_android_lifecycle-2.0.22
google_maps_flutter-2.9.0
google_maps_flutter_android-2.14.5
google_maps_flutter_ios-2.13.0
google_maps_flutter_web-0.5.10
location-7.0.0
location_web-5.0.3

**Comment by darshankawar** [comment] 2024-09-11 07:12
Closing as duplicate of https://github.com/flutter/flutter/issues/153471

**Closed by darshankawar** 2024-09-11 07:12 UTC
Labels: in triage

**Comment by andrewkolos** [comment] 2024-09-11 17:00
This is specifically a duplicate of https://github.com/flutter/flutter/issues/154903 (I see `VmService.getVM` in the callstack).

If you have a reliable way to reproduce this crash, please let us know.
