### ISSUE TITLE
LayoutBuilder rebuilds even if constraints don't change.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6142] opened 2016-09-29 19:05 UTC

**Comment by abarth** [comment] 2016-09-30 04:38
Can you say more about what the issue is?  A layout builder rebuilds if its parent rebuilds, for example, and that might not trigger different constraints.

**Comment by apwilson** [comment] 2016-09-30 17:05
Sorry.  In my case I've an Overlay as a child of LayoutBuilder.  If I drag a Draggable that's a child of that Overlay, the LayoutBuilder rebuilds.  I verified the parent doesn't rebuild or change.  And I've verified the constraints didn't change.

**Comment by Hixie** [comment] 2016-10-02 19:09
Enable debugPrintScheduleBuildForStacks and see what's causing it to be marked dirty, if anything.

**Comment by abarth** [comment] 2016-10-02 19:53
Most likely the `LayoutBuilder` is the layout root in this case.  The draggable is triggering the overlay to relayout, which walks up to the nearest layout root, in this case something that includes the layout builder.

**Comment by abarth** [comment] 2016-10-23 05:33
Duplicate of #6469

**Closed by abarth** 2016-10-23 05:33 UTC
