### ISSUE TITLE
Conflit between intl and esay_localiztion dependency issue:

### ISSUE THREAD

**Issue by muhammadshoaib06** [flutter/flutter#75100] opened 2021-01-31 19:40 UTC
Hey!
In my project, **intl and easy_localization** have **conflict**. I pore over an issue which says that you have to override intl dependence. 
But when I override the dependency: 

```
dependency_overrides:
  intl: any
```

It`s communicate the following warning.

```
Warning: You are using these overridden dependencies:
! intl 0.17.0-nullsafety.2
```

**After that I build the project it shows below error:**

```
/Users//Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
context != null ? Localizations.localeOf(context, nullOk: true) : null,
^^^^^^
/Users//Desktop/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
static Locale localeOf(BuildContext context) {
^^^^^^^^
/Users//Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:83:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
resizeToAvoidBottomPadding: false,
^^^^^^^^^^^^^^^^^^^^^^^^^^
/Users//Desktop/flutter/packages/flutter/lib/src/material/scaffold.dart:1449:9: Context: Found this candidate, but the arguments don't match.
const Scaffold({
^^^^^^^^
/Users/*****/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:276:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.

'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/Users/*****/Desktop/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
context.inheritFromWidgetOfExactType(_ChewieControllerProvider)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FAILURE: Build failed with an exception.

Where:
Script '/Users/*****/Desktop/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.

Process 'command '/Users/shoaib/Desktop/flutter/bin/flutter'' finished with non-zero exit value 1

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org
### ### ### 
BUILD FAILED in 48s
Exception: Gradle task assembleDebug failed with exit code 1### 
```

- flutter_ doctor -v

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-18.0.pre.90, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by iapicca** [comment] 2021-01-31 20:15
[easy_localization](https://pub.dev/packages/easy_localization) is a 3rd party plugin, please open an issue in the dedicated [github]https://github.com/aissat/easy_localization/issues)

the issue likely depend from the import 
```yaml
  intl: ">=0.16.0 <0.17.0"
```
in [easy_localization's pubspec.yaml](https://github.com/aissat/easy_localization/blob/develop/pubspec.yaml)

**Comment by pedromassangocode** [comment] 2021-02-01 07:55
Hi @...
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/aissat/easy_localization/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-01 07:55 UTC

**Comment by avikdutta111191** [comment] 2021-03-01 09:35
`moibledev@cocselab:~$ flutter doctor -v
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-17.5.pre at
      /home/moibledev/snap/flutter/common/flutter
    • Framework revision 1fe38dcb5f (3 weeks ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/moibledev/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • itel W6502 (mobile) • 05803370AG002037 • android-arm • Android 10 (API 29)

! Doctor found issues in 1 category.
`

`moibledev@cocselab:~$ flutter run -v
[  +71 ms] executing: [/home/moibledev/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 1fe38dcb5fc58242c6e0904a318bcc3ed5a4d837
[        ] executing: [/home/moibledev/snap/flutter/common/flutter/] git tag
--points-at 1fe38dcb5fc58242c6e0904a318bcc3ed5a4d837
[  +27 ms] Exit code 0 from: git tag --points-at
1fe38dcb5fc58242c6e0904a318bcc3ed5a4d837
[   +1 ms] 1.26.0-17.5.pre
[  +53 ms] executing: [/home/moibledev/snap/flutter/common/flutter/] git
rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/moibledev/snap/flutter/common/flutter/] git
ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +62 ms] executing: [/home/moibledev/snap/flutter/common/flutter/] git
rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +48 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +55 ms] executing: /home/moibledev/Android/Sdk/platform-tools/adb devices -l
[  +54 ms] List of devices attached
           05803370AG002037       device usb:1-8 product:F3108 model:itel_W6502
           device:itel-W6502 transport_id:30
[   +6 ms] /home/moibledev/Android/Sdk/platform-tools/adb -s 05803370AG002037
shell getprop
[ +120 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +34 ms] "flutter run" took 285ms.
[  +21 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +3 ms] 
           #0      FlutterCommand.validateCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1274:11)
           #1      RunCommand.validateCommand
           (package:flutter_tools/src/commands/run.dart:437:19)
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1114:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand
(package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure>
(package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext
(package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +256 ms] ensureAnalyticsSent: 253ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
`

**Comment by vijayvaghela72** [comment] 2021-04-09 16:35
> [easy_localization](https://pub.dev/packages/easy_localization) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/aissat/easy_localization/issues)
> 
> the issue likely depend from the import
> 
> ```yaml
>   intl: ">=0.16.0 <0.17.0"
> ```
> 
> in [easy_localization's pubspec.yaml](https://github.com/aissat/easy_localization/blob/develop/pubspec.yaml)

please try your self and then give to anyone else...

**Comment by iapicca** [comment] 2021-04-10 09:51
> > [easy_localization](https://pub.dev/packages/easy_localization) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/aissat/easy_localization/issues)
> > the issue likely depend from the import
> > ```yaml
> >   intl: ">=0.16.0 <0.17.0"
> > ```
> > 
> > 
> > in [easy_localization's pubspec.yaml](https://github.com/aissat/easy_localization/blob/develop/pubspec.yaml)
> 
> please try your self and then give to anyone else...

@vijayvaghela72 
(I'm answering because, even if not tagged I feel that this post is an answer to [mine](https://github.com/flutter/flutter/issues/75100#issuecomment-770443458))

I think I will not, fixing 3rd party packages issues is not in the scope of flutter repo
I recommend to bring up the issue in the correct repo
https://github.com/aissat/easy_localization/issues
