### ISSUE TITLE
Handle corrupted gradle zip file more gracefully

### ISSUE THREAD

**Issue by jayword** [flutter/flutter#13645] opened 2017-12-18 12:02 UTC
I tried running flutter for the first time from android studio and i got a gradle error. I have connected my phone to my computer and it recognized it alright. I tried to run it again and it gave me the same error message.

like this:
```
Launching lib\main.dart on SZ622YHRZW in debug mode...
Initializing gradle...
Finished with error: Exit code 1 from: C:\Users\Andi\jet_flutter_app\android\gradlew.bat -v:
Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping C:\Users\Andi\.gradle\wrapper\dists\gradle-3.3-all\55gk2rcmfc6p2dg9u9ohc3hw9\gradle-3.3-all.zip to C:\Users\Andi\.gradle\wrapper\dists\gradle-3.3-all\55gk2rcmfc6p2dg9u9ohc3hw9

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```
Please check my command line feedback on the error from the attached txt file.
Flutter doctor runs alright.

**Comment by cbracken** [comment] 2017-12-19 01:50
Thanks for filing! Would you mind adding the output of a `flutter doctor` run?

**Comment by jayword** [comment] 2017-12-19 09:37
This came from flutter doctor:

C:\Users\Andi\jet_flutter_app>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.10240], locale en-US, channel alpha)
    • Flutter at C:\Users\Andi\
    • Framework revision 8f65fec5f5 (7 days ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at C:\Users\Andi\Applications\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3942.31

[√] Connected devices
    • SZ622YHRZW • SZ622YHRZW • android-arm • Android 4.1.2 (API 16)

**Comment by mit-mit** [comment] 2018-01-02 14:59
@jayword did this resolve itself on a second run, or is it consistently failing this step? It looks like the downloaded file might have been corrupt.

**Comment by muhammad-hamdi** [comment] 2018-02-01 12:19
I'm facing the same problem, any solutions yet ???

**Comment by mit-mit** [comment] 2018-02-01 13:51
@muhammad-hamdi can you run "regular" Android app projects from Android Studio without problems?

Also, can you try to run `flutter -v build apk` in a terminal, and share the output?

**Comment by muhammad-hamdi** [comment] 2018-02-01 16:01
@jayword @mit-mit I've found the solution
the problem was with the Gradle distribution `.zip` compressed file, because the file was corrupted the flutter tool wasn't able to extract its contents,

the solution is to download the Gradle distribution file from [here](https://services.gradle.org/distributions/) and replace the corrupted file with it
be sure to download the right version for flutter which is currently [gradle-3.3-all.zip](https://services.gradle.org/distributions/gradle-3.3-all.zip)

Good Luck!

**Comment by MaStanford** [comment] 2018-03-14 18:58
I also get this issue.  

iOS builds fine. 

Android is getting the Gradle error

`sta125212-msta:flutter_learning m.stanford$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.12.6 16G1212, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.21.0)
[✓] Connected devices (1 available)

• No issues found!
`

`sta125212-msta:flutter_learning m.stanford$ gradle --version

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.12.6 x86_64
`

`sta125212-msta:flutter_learning m.stanford$ flutter build apk
Initializing gradle...                                   |
Oops; flutter has exited unexpectedly: "Exit code 1 from: /Users/m.stanford/Workspace/flutter_learning/android/gradlew -v:
Unzipping /Users/m.stanford/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1-all.zip to /Users/m.stanford/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)".
 
Sending crash report to Google.
Crash report sent (report ID: d9f0368a07cf4c88)
Crash report written to /Users/m.stanford/Workspace/flutter_learning/flutter_06.log;
please let us know at https://github.com/flutter/flutter/issues.
`

**Comment by MaStanford** [comment] 2018-03-14 19:07
The fix is the same as Mr. @muhammad-hamdi put there.  Replace the bad .zip in your .gradle/wrapper directory.  

`sta125212-msta:flutter_learning m.stanford$ flutter build apk
Initializing gradle...                               10.2s
Resolving dependencies...                            31.3s
Running 'gradlew assembleRelease'...                      
Skipping AOT snapshot build. Fingerprint match.
Built build/app/outputs/apk/release/app-release.apk (7.6MB).`

**Comment by saadnaveed453** [comment] 2018-04-04 14:13
ajeeb bakwass cheez ha ye

**Comment by Hixie** [comment] 2018-05-24 21:32
Looks like this has happened to more than one person, so it might be worth detecting this case somehow.

**Comment by hsian** [comment] 2018-06-07 07:16
thanks for @muhammad-hamdi

**Comment by imkerwin** [comment] 2018-06-11 16:21
My gradle is just damaged,then i manually unzip the zip to the correct file.It is run now. Thanks for @muhammad-hamdi

**Comment by zoechi** [comment] 2018-09-03 07:58
See also https://github.com/flutter/flutter/issues/15721#issuecomment-402905062 for a workaround.

**Comment by kararsaadkd** [comment] 2018-11-09 21:52
please help me 
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\karrar\IdeaProjects\botonf\android\gradlew.bat" exited abnormally:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\karrar\IdeaProjects\botonf\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar'.
            > dl.google.com
   > Could not download sdk-common.jar (com.android.tools:sdk-common:26.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.2.1/sdk-common-26.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.2.1/sdk-common-26.2.1.jar'.
            > dl.google.com
   > Could not download ddmlib.jar (com.android.tools.ddms:ddmlib:26.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.2.1/ddmlib-26.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.2.1/ddmlib-26.2.1.jar'.
            > dl.google.com
   > Could not download asm.jar (org.ow2.asm:asm:6.0)
      > Could not get resource 'https://jcenter.bintray.com/org/ow2/asm/asm/6.0/asm-6.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/ow2/asm/asm/6.0/asm-6.0.jar'.
            > jcenter.bintray.com
   > Could not download annotations.jar (com.android.tools:annotations:26.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.2.1/annotations-26.2.1.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.2.1/annotations-26.2.1.jar'.
            > dl.google.com
   > Could not download httpmime.jar (org.apache.httpcomponents:httpmime:4.5.2)
      > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar'.
            > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: C:\Users\karrar\IdeaProjects\botonf\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by tomake** [comment] 2018-11-16 01:35
maybe the zip files is damaged.
open $HOME/.gradle/wrapper/dists and delete gralde-xxx-all . then execute command:  flutter run  again.  it works for me

**Comment by iyoushe1703** [comment] 2018-11-24 11:15
My dists folder contains two files: 
gradle-4.10.2-all (zip file) and gradle-4.10.2-all.zip (LCK file)   
Should I delete the LCK file too?

**Comment by Alam969** [comment] 2018-12-01 10:38
good

**Comment by keshiim** [comment] 2019-03-18 09:53
> My dists folder contains two files:
> gradle-4.10.2-all (zip file)
> gradle-4.10.2-all.zip (LCK file)
> Should I delete the LCK file too?

It will be gradle-4.10.2-all

**Comment by iqbal7271** [comment] 2019-05-25 12:38
![main error](https://user-images.githubusercontent.com/1922065/58369399-2d22c080-7f0f-11e9-9a4f-7d082a9dcb3a.png)
I get this error when running flutter run command in terminal or f5 in vscode or shift+f10 on android studio, but in the meanwhile flutter doctor command displays the below message that all is fine. 
![flutter doctor](https://user-images.githubusercontent.com/1922065/58369432-6fe49880-7f0f-11e9-8510-ce3ddc79a79c.png)
and even running flutter analyze commands shows nothing other all is fine.
![flutter analyze](https://user-images.githubusercontent.com/1922065/58369448-a5898180-7f0f-11e9-92ed-d08cae6565be.png)

What should i do? Please help me figure it out.

**Comment by dlintin** [comment] 2019-06-03 03:00
> maybe the zip files is damaged.
> open `$HOME/.gradle/wrapper/dists` and delete `gralde-xxx-all` . then execute command: `flutter run` again. it works for me

Thanks! work great!

**Comment by blasten** [comment] 2019-08-06 17:53
Duplicate of https://github.com/flutter/flutter/issues/36282

**Closed by blasten** 2019-08-06 17:53 UTC
Labels: a: quality, t: gradle, tool

**Comment by correiarangel** [comment] 2019-10-30 00:31
Today and my first contact with flutter I prepared the environment I created the first demo project but it did not run neither **vs** nor **Android Studio**.
Just returned
**ProcessException: ProcessException: Process "/ home / rangel / FlutterProjects / HelloWord / hello_word_app / android / gradlew" exited abnormally:
Unzipping /home/rangel/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv/gradle-4.10.2-all.zip to /home/rangel/.gradle/wrapper/dists/gradle-4.10.2 -all / 9fahxiiecdb76a5g3aw9oi8rv**

Exception in thread "main" java.util.zip.ZipException: error in opening zip file.
After studying the log calmly after wasting half a day trying to start the project I saw the mistake.

Ta gradle-4.10.2-all in the face is corrupted the log makes it clear hooll as I am slow.
So I downloaded a new copy at   https://services.gradle.org/distributions/
After replacing the gradle corrupted by the new copy all flowed.
**IF YOU HAVE THAT RETURN ERROR ENOUGH CHANGE THE CORRUPTED FILE ARRIVED BY LOG IN OUR CASE gradle-4.10.2-all.zip**

**Comment by Muhammad-Altabba** [comment] 2020-02-18 13:18
An alternative solution to downloading the zip file manually is to delete the corrupted file and then run the command again. This way the zip file will be automatically downloaded again. The issue is that the command does not download the zip file again if it is corrupted.

The file were located in `/home/developer/.gradle/wrapper/dists/gradle-[VERSION]-[TAG]/`. And in my version specifically at `/home/developer/.gradle/wrapper/dists/gradle-5.5-all/byeise1led9a3w3p149d02kfj/gradle-5.5-all.zip`

**Comment by mohamed1199** [comment] 2020-03-21 12:37
hi , have the same problem, and I dowloaded the the same version of my flutter gradle app , but I don't find that directory(/home/developer/.gradle/wrapper/dists/gradle-[VERSION]-[TAG]/) to replace with it.

please can you help me

**Comment by correiarangel** [comment] 2020-03-21 13:56
try to access the file in question, shown in the error return, see if it is really corrupted if yes delete, download the same version of.
https://services.gradle.org/distributions/
and subscribe to the downloaded version. if you already did it post the error message returned to better understand the error

**Comment by mohamed1199** [comment] 2020-03-21 14:02
there is no file in the error 
<img width="1002" alt="Capture d’écran 1441-07-26 à 12 56 31" src="https://user-images.githubusercontent.com/49884768/77228059-f6482600-6b84-11ea-8180-c49172a2d5b4.png">

**Comment by mohamed1199** [comment] 2020-03-21 14:02
that is my error output

**Comment by correiarangel** [comment] 2020-03-21 14:49
the error says it cannot process the file
  it really looks corrupted.

1 - run the flutter doctor to make sure that everything is ok with the flutter installations if there is a post error.
2 - If no error is returned, try to access this directory (dists) with
cd /home/developer/.gradle/wrapper/dists/ see if you have access to the directory

if the directory exists there is the procedure that I indicated if you know the version of the gradle he is complaining about, download this version at https://services.gradle.org/distributions/ and move to the directory (dists) -> / home / developer /.gradle/wrapper/dists/

3- Or you can use Android Studio, also try to open the project in it, it may be that it can solve the problem or point out a solution.
But for the error returned I believe that step 2 can solve and what I would do

**Comment by mohamed1199** [comment] 2020-03-21 15:34
when I run flutter doctor , everything is ok , but now my problem is to find such as directory , I run what you said in terminal , and they tell me that  no such file or directory: /home/developer/.gradle/wrapper/dists/.
there is no way to create manually ?

**Comment by correiarangel** [comment] 2020-03-22 06:07
Good if the directory doesn't exist try to run the command:
 
->  **gradle -v**

If you have the gradle you will have a return similar to the one below

------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------
Build time:   2012-12-21 00:00:00 UTC
Revision:     none
Groovy:       2.4.16
Ant:          Apache Ant(TM) version 1.10.5 compiled on March 28 2019
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Linux 4.15.0-91-generic amd64

If you do not return your gradle version, then you must install it

On Linux use:

installation and update the package list, respectively:
At the terminal run:        
                                                
1  - sudo add-apt-repository ppa:cwchien/gradle
2  - sudo apt-get update

Now search for the most current version of Gradle to install:

3 - sudo apt-cache search gradle

Install Gradle with:
                                        
4 - sudo apt-get install gradle-4.4.1 

I'm using gradle-4.4.1 but can install the most current version

And again run                                     

5 - gradle -v

Confirm that it has been installed

consult the documentation if necessary

https://gradle.org/install/

**Comment by mohamed1199** [comment] 2020-03-22 17:53
I do all the stuff , but still not working , this is my terminal output when I ran gradle -v .

<img width="572" alt="Capture d’écran 1441-07-27 à 18 51 36" src="https://user-images.githubusercontent.com/49884768/77256409-52d34000-6c6e-11ea-8888-ee2d7cb33270.png">

**Comment by johnmelodyme** [comment] 2020-03-28 16:53
Tried ```flutter upgrade```?
