### ISSUE TITLE
[web][canvas-kit] problem that Japanese is rendered in simple Chinese at flutter web canvaskit render

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#77894] opened 2021-03-11 09:36 UTC
## Steps to Reproduce

this is minimum code 
```
import 'package:flutter/material.dart';

class SamplePage extends StatefulWidget {

  SamplePage(): super();

  @override
  SamplePageState createState() => SamplePageState();
}

class SamplePageState extends State<SamplePage> with WidgetsBindingObserver {

  Widget build(BuildContext context){

    Widget bodyScaffold = Scaffold(
      body: Container(child:Text("与", style: TextStyle(color: Colors.grey),)),
    );

    return bodyScaffold;
  }
}
```
1. Run `flutter run -d chrome --web-renderer=canvaskit`.

**Expected results:** 
The text shod be "与"
You can see that the horizontal line below this letter runs through the vertical line

**Actual results:** 
You can see that the horizontal line below this letter does **not** go through the vertical line
![無題](https://user-images.githubusercontent.com/7422251/110767173-4c800e80-8299-11eb-8e49-6d5980322e44.png)

**Comment by AviadKatani** [comment] 2021-03-11 09:39
Can you explain the issue you're experiencing?

**Comment by hatano0x06** [comment] 2021-03-11 09:42
@AviadKatani 
Sorry 
I made a mistake and posted it on the way
I fixed it

**Comment by pedromassangocode** [comment] 2021-03-11 10:33
Hi @hatano0x06 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by hatano0x06** [comment] 2021-03-11 10:36
@pedromassangocode 
It meant that I posted the problem in the middle and fixed it later.
Please reopen as we need to confirm and discuss the issue

**Comment by pedromassangocode** [comment] 2021-03-11 13:09
Hi @hatano0x06 
Can you please elaborate what the issue is? I can't notice any obvious issue in the image bellow.

![Screen Shot 2021-03-11 at 14 07 24](https://user-images.githubusercontent.com/67424416/110791964-1def3d00-8273-11eb-9c14-2f3ce87e10da.png)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  return runApp(MaterialApp(
    home: Scaffold(
      body: Scaffold(
        body: Text("与",
          style: TextStyle(color: Colors.grey, fontSize: 400),
        ),
      ),
    ),
  ));
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.205, on macOS 11.2.2 20D80 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-11.0.pre.205 at /Users/pedromassango/Code/flutter_master
    • Framework revision 267f66a7dc (2 hours ago), 2021-03-10 23:15:03 -0500
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

**Comment by hatano0x06** [comment] 2021-03-11 13:11
@pedromassangocode 
I want to display japanese word "与"
but, it is displaying simple chinese

**Comment by hatano0x06** [comment] 2021-03-11 13:33
I also check to add local option data but doesn't work
```

**Comment by hatano0x06** [comment] 2021-03-11 13:33
``

**Comment by hatano0x06** [comment] 2021-03-11 13:34
Sorry I pressed close button by mistake

**Comment by pedromassangocode** [comment] 2021-03-11 13:49
> @pedromassangocode
> I want to display japanese word "与"
> but, it is displaying simple chinese

Isn't this the same as what is in the image I provided in https://github.com/flutter/flutter/issues/77894#issuecomment-796723700?
Can you share an image of the expected character you want?

**Comment by hatano0x06** [comment] 2021-03-11 13:58
this is expected character (japanese)
You can see the difference from the horizontal line
you get character by rendering type of html
`flutter run -d chrome --web-renderer=html` 

![無題](https://user-images.githubusercontent.com/7422251/110797826-e0170680-82bc-11eb-97ba-9cb806b159e7.png)

**Comment by pedromassangocode** [comment] 2021-03-11 14:17
I got the same result building witth HTML renderer.

![Screen Shot 2021-03-11 at 15 15 59](https://user-images.githubusercontent.com/67424416/110800642-b1793b80-827c-11eb-879d-3a064c06d080.png)

Please provide your `flutter doctor -v`.
Thank you

**Comment by hatano0x06** [comment] 2021-03-11 14:35
hmm...
It's strange that can not get same result.

can you also check it by setting local parameter?
`Container(child:Text("与", style: TextStyle(color: Colors.grey), locale: Locale("en", ''),)),`

This is my `flutter doctor -v`
```
[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale ja-JP)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\hatadev\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\hatadev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.48
```

**Comment by yjbanov** [comment] 2021-03-11 23:41
I believe this is due to us not handling `locale` correctly. I'm going to deduplicate with https://github.com/flutter/flutter/issues/74687.

**Closed by yjbanov** 2021-03-11 23:41 UTC
Labels: in triage
