### ISSUE TITLE
Flutter Web: Canvas renderer is not usable offline

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#85624] opened 2021-06-30 15:25 UTC
Hi,

For Flutter web you can choose the beautiful canvas renderer. Everything looks good and the same in each browsere.
But this renderer is loaded from a specific server on the internet if you open a flutter website.
But in some cases your flutter website is used in an intranet with no connection to the server that provides canvas kit.
In this case, the site is just blank. No error displayed to the user.

My points were as follows:

- Could you make an option to host canvaskit with your site? So that if you build your flutter website ALL necessary files will be placed under build/web.
- There is an option to set renderer to auto. This makes flutter use the html renderer on mobile. But I would prefer if the html renderer would be used automatically if on mobile, OR on desktop with no connection to the server to download canvaskit.
- If the renderer is set to canvaskit and it cannot be loaded, there should be an understandable message that says, no connection to the internet or something.

**Comment by TahaTesser** [comment] 2021-06-30 16:31
Hi @Wissperwind 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/70101
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-30 16:31 UTC
Labels: in triage
