### ISSUE TITLE
flutter has exited unexpectedly, handler not found

### ISSUE THREAD

**Issue by pyetti** [flutter/flutter#36239] opened 2019-07-16 05:36 UTC
During hot restart, the following was printed to the console:

> Performing hot restart...
Syncing files to device LM Q610 FGN...
Error -32000 received from application: Service protocol could not handle or find a handler for the requested method.
> Oops; flutter has exited unexpectedly.
> Sending crash report to Google.
> Restarted application in 1,455ms.
> Crash report sent (report ID: 1199322e84c25fdd)
> please let us know at https://github.com/flutter/flutter/issues.

[flutter_01.log](https://github.com/flutter/flutter/files/3395460/flutter_01.log)

I had been testing video playback with `video_player: ^0.10.1+4`, which was throwing an error saying the Video Controller had been disposed. 

(content of the file)
## command
```
flutter --no-color run --machine --track-widget-creation --device-id=LMQ610TA35997ea --start-paused lib/main.dart
```
## exception
```
RpcException: JSON-RPC error -32000: Service protocol could not handle or find a handler for the requested method.
```
```
package:json_rpc_2/src/client.dart 110:64              Client.sendRequest
package:json_rpc_2/src/peer.dart 79:15                 Peer.sendRequest
package:flutter_tools/src/vmservice.dart 316:13        VMService._sendRequest
package:flutter_tools/src/vmservice.dart 851:60        VM.invokeRpcRaw
===== asynchronous gap ===========================
package:flutter_tools/src/vmservice.dart 872:49        VM.invokeRpc
===== asynchronous gap ===========================
package:flutter_tools/src/vmservice.dart 941:12        VM.runInView
package:flutter_tools/src/vmservice.dart 1455:20       FlutterView.runFromSource
===== asynchronous gap ===========================
package:flutter_tools/src/run_hot.dart 372:24          HotRunner._launchInView
package:flutter_tools/src/run_hot.dart 387:19          HotRunner._launchFromDevFS
===== asynchronous gap ===========================
package:flutter_tools/src/run_hot.dart 458:11          HotRunner._restartFromSources
===== asynchronous gap ===========================
package:flutter_tools/src/run_hot.dart 546:46          HotRunner.restart
===== asynchronous gap ===========================
package:flutter_tools/src/commands/daemon.dart 874:19  AppInstance.restart
package:flutter_tools/src/commands/daemon.dart 544:18  AppDomain.restart.<fn>
package:flutter_tools/src/base/context.dart 153:29     AppContext.run.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1124:13                           _rootRun
dart:async/zone.dart 1021:19                           _CustomZone.run
dart:async/zone.dart 1516:10                           _runZoned
dart:async/zone.dart 1463:12                           runZoned
package:flutter_tools/src/base/context.dart 152:18     AppContext.run
===== asynchronous gap ===========================
package:flutter_tools/src/commands/daemon.dart 887:20  AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 543:32  AppDomain.restart
===== asynchronous gap ===========================
package:flutter_tools/src/commands/daemon.dart 189:34  Domain.handleCommand.<fn>
dart:async/future.dart 224:31                          new Future.sync
package:flutter_tools/src/commands/daemon.dart 186:77  Domain.handleCommand
package:flutter_tools/src/commands/daemon.dart 145:26  Daemon._handleRequest
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_pipe.dart 132:11                     _ForwardingStreamSubscription._add
dart:async/stream_pipe.dart 232:10                     _MapStream._handleData
dart:async/stream_pipe.dart 164:13                     _ForwardingStreamSubscription._handleData
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_pipe.dart 132:11                     _ForwardingStreamSubscription._add
dart:async/stream_pipe.dart 207:12                     _WhereStream._handleData
dart:async/stream_pipe.dart 164:13                     _ForwardingStreamSubscription._handleData
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_transformers.dart 68:11              _SinkTransformerStreamSubscription._add
dart:async/stream_transformers.dart 15:11              _EventSinkWrapper.add
dart:convert/string_conversion.dart 236:11             _StringAdapterSink.add
dart:convert/line_splitter.dart 150:13                 _LineSplitterSink._addLines
dart:convert/line_splitter.dart 125:5                  _LineSplitterSink.addSlice
dart:convert/string_conversion.dart 163:5              StringConversionSinkMixin.add
dart:async/stream_transformers.dart 120:24             _SinkTransformerStreamSubscription._handleData
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_transformers.dart 68:11              _SinkTransformerStreamSubscription._add
dart:async/stream_transformers.dart 15:11              _EventSinkWrapper.add
dart:convert/string_conversion.dart 236:11             _StringAdapterSink.add
dart:convert/string_conversion.dart 241:7              _StringAdapterSink.addSlice
dart:convert/string_conversion.dart 312:20             _Utf8ConversionSink.addSlice
dart:convert/string_conversion.dart 305:5              _Utf8ConversionSink.add
dart:convert/chunked_conversion.dart 72:18             _ConverterStreamEventSink.add
dart:async/stream_transformers.dart 120:24             _SinkTransformerStreamSubscription._handleData
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_controller.dart 764:19               _SyncStreamController._sendData
dart:async/stream_controller.dart 640:7                _StreamController._add
dart:async/stream_controller.dart 586:5                _StreamController.add
dart:io-patch/socket_patch.dart 1786:41                _Socket._onData
dart:async/zone.dart 1136:13                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_controller.dart 764:19               _SyncStreamController._sendData
dart:async/stream_controller.dart 640:7                _StreamController._add
dart:async/stream_controller.dart 586:5                _StreamController.add
dart:io-patch/socket_patch.dart 1335:33                new _RawSocket.<fn>
dart:io-patch/socket_patch.dart 856:14                 _NativeSocket.issueReadEvent.issue
dart:async/schedule_microtask.dart 41:21               _microtaskLoop
dart:async/schedule_microtask.dart 50:5                _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 116:13           _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 173:5            _RawReceivePortImpl._handleMessage
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.7.8+hotfix.3 at /Users/peteryetti/development/flutter
    • Framework revision b712a172f9 (6 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/peteryetti/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/devTools/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/devTools/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/devTools/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • LM Q610 FGN • LMQ610TA35997ea • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by BondarenkoStas** [comment] 2019-09-27 23:06
@pyetti Closing as a duplicate of #39809. The fix is on master, please try to use it and reply if you encounter the issue again.

**Closed by BondarenkoStas** 2019-09-27 23:06 UTC
