### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Incorrect function., errno = 1

### ISSUE THREAD

**Issue by munirubawa** [flutter/flutter#98304] opened 2022-02-12 02:09 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Incorrect function.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1029:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:964:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1055:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:316:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:177:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19041.1415], locale en-US)
    • Flutter version 2.10.0 at D:\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (10 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:/Users/Clinton Paul/AppData/Local/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:/Users/Clinton Paul/AppData/Local/Android/Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.43

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
cloud_firestore-3.1.7
cloud_firestore_web-2.6.7
desktop_webview_auth-0.0.2
desktop_window-0.4.0
firebase_auth-3.3.6
firebase_auth_web-3.3.7
firebase_core-1.12.0
firebase_core_desktop-0.1.1-dev.3
firebase_core_web-1.5.4
firebase_database-9.0.6
firebase_database_web-0.2.0+5
firebase_dynamic_links-4.0.5
flutter_facebook_auth-4.0.1
flutter_facebook_auth_web-3.0.0+1
google_sign_in-5.2.3
google_sign_in_web-0.10.0+4
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
sign_in_with_apple-3.3.0
sign_in_with_apple_web-1.0.1
twitter_login-4.0.1

**Comment by darshankawar** [comment] 2022-02-14 07:18
Closing this as duplicate of https://github.com/flutter/flutter/issues/66224

**Closed by darshankawar** 2022-02-14 07:18 UTC
Labels: in triage
