### ISSUE TITLE
Cannot Trigger SliverAppBar Stretch in NestedScrollView

### ISSUE THREAD

**Issue by shaochenguang** [flutter/flutter#149569] opened 2024-06-03 06:34 UTC
### Steps to reproduce

Run the provided code and modify the body type of the `NestedScrollView`.

When stretch is set to true in a `SliverAppBar` and the body of the `NestedScrollView` contains a scrollable widget, such as a `ListView`, with `physics` set to `ClampingScrollPhysics`, pulling down the page does not trigger the `SliverAppBar` stretch behavior. 
However, if the body does not contain a scrollable widget, such as a `Text`, the stretch behavior works as expected.

I believe that the scroll delta of the nested scrollable widget should also be handled within the `NestedScrollView`.

### Expected results

Triggers SliverAppBar Stretch Effect.

### Actual results

Does Not Trigger SliverAppBar Stretch Effect.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: NestedScrollViewExample(),
    );
  }
}

class NestedScrollViewExample extends StatelessWidget {
  const NestedScrollViewExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        physics: const BouncingScrollPhysics(),
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              expandedHeight: 200.0,
              pinned: true,
              stretch: true,
              flexibleSpace: FlexibleSpaceBar(
                title: const Text('SliverAppBar Test'),
                background: Image.network(
                  'https://flutter.github.io/assets-for-api-docs/assets/widgets/owl-2.jpg',
                  fit: BoxFit.cover,
                ),
              ),
            ),
          ];
        },
        body: ListView.builder(
          physics: const ClampingScrollPhysics(),
          itemCount: 20,
          itemBuilder: (BuildContext context, int index) {
            return ListTile(
              title: Text('Item $index'),
            );
          },
        ),
        // body: Text("This is text"),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/33643378/39f25276-685f-45d3-b2df-df0981155dee

https://github.com/flutter/flutter/assets/33643378/8f3faf1d-6bb1-4fd4-bf1e-412a0a10eae8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    ! Warning: `flutter` on your path resolves to /Users/chenguangshao/code/flutter_private/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/chenguangshao/code/github/flutter. Consider adding
      /Users/chenguangshao/code/github/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/chenguangshao/code/flutter_private/bin/dart, which is not inside your current Flutter SDK checkout at /Users/chenguangshao/code/github/flutter. Consider adding
      /Users/chenguangshao/code/github/flutter/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Chenguang的iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for com. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment] 2024-06-03 11:37
Thank you for filing the issue and proposing a fix. However, there is already a similar issue at https://github.com/flutter/flutter/issues/54059. 

Closing this as a duplicate of that issue. Please link your PR to that issue.

**Closed by huycozy** 2024-06-03 11:37 UTC
Labels: in triage
