### ISSUE TITLE
 [google_maps_flutter] [webview_flutter] GoogleMap is blocking pop action from another screen with WebView widget, after app is paused.

### ISSUE THREAD

**Issue by admarwick** [flutter/flutter#40251] opened 2019-09-11 13:24 UTC
An issue that occurs in Release Mode on IOS when from a page containing a GoogleMap widget (google_maps_flutter) a second page is pushed that contains a WebView (webview_flutter).

The issue is that a white screen is shown when returning to the GoogleMap page from the WebView page, if the app has been paused from the WebView page, then resumed.
This issue does not occur when running in debug mode, or on Android.

Code of a simple app that illustrates the issue is at [**Edit**: fixed url] https://github.com/admarwick/issue_map_webview

## Steps to Reproduce
- Merge the repo (link above) into a fresh Flutter app project.
- Add the needed google map keys to ios/Runner/AppDelegate.swift and
android/app/src/main/AndroidManifest.xml
- Run the app on IOS in Release Mode.
- Navigate to the second page by pressing the button.
- Press the iPhone "Home" button to pause the app, then return to the 
running app.
- Use the back button on the second page's app bar. Instead of returning
to the first page, a white screen is shown.

## Logs
```
[no runtime output from flutter run --release --verbose]
```

```
[no issues found by flutter analyze]
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/alan/Documents/util/flutter
    • Framework revision 2d2a1ffec9 (5 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/alan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.5153.38

[✓] Connected device (1 available)
    • Alan’s iPhone 5S • fb2c341f9cecedf031922c7a9f3977426a476bf6 • ios • iOS 12.4.1

• No issues found!

```

**Comment by VladyslavBondarenko** [comment] 2020-03-05 15:01
I can't reproduce it with flutter v1.12.13+hotfix.8, iOS 12.4 simulator, and

```
webview_flutter: ^0.3.19+8
google_maps_flutter: ^0.5.24+1
```

May be fixed. Closing
@admarwick 
Comment please if you are still experiencing this and I'll reopen

**Closed by VladyslavBondarenko** 2020-03-05 15:01 UTC
Labels: p: maps, p: webview, plugin, ⌺‬ platform-ios
