### ISSUE TITLE
The getter 'size' isn't defined for the class 'dart.ui::PointerData'.

### ISSUE THREAD

**Issue by LimitedDani** [flutter/flutter#23672] opened 2018-10-29 12:29 UTC
## Steps to Reproduce

When i want to open my nav drawer i get this error in my log:

## Logs

```
D/ViewRootImpl@baaffa0[MainActivity](20091): ViewPostImeInputStage processPointer 1
E/flutter (20091): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (20091): 'package:flutter/src/gestures/converter.dart': error: line 130 pos 25: file:///Users/daniquedejong/tools/flutter/packages/flutter/lib/src/gestures/converter.dart:130:25: Error: The getter 'size' isn't defined for the class 'dart.ui::PointerData'.
E/flutter (20091): Try correcting the name to the name of an existing getter, or defining a getter or field named 'size'.
E/flutter (20091):             size: datum.size,
E/flutter (20091):                         ^
E/flutter (20091):             size: datum.size,
E/flutter (20091):                         ^
E/flutter (20091): 
E/flutter (20091): #0      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
E/flutter (20091): #1      ListQueue.addAll (dart:collection/queue.dart:715:25)
E/flutter (20091): #2      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
E/flutter (20091): #3      _invoke1 (dart:ui/hooks.dart:159:13)
E/flutter (20091): #4      _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
```

```
Analyzing curawow_app...                                         

   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/main.dart:13:7 • must_be_immutable
   info • Name non-constant identifiers using lowerCamelCase • lib/main.dart:58:12 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/objects/user.dart:8:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/objects/user.dart:11:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/objects/user.dart:15:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/objects/user.dart:19:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/objects/user.dart:23:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/objects/user.dart:27:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/objects/user.dart:31:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/objects/user.dart:35:7 • non_constant_identifier_names
   info • The value of the local variable 'prefs' isn't used • lib/pages/home.dart:55:11 • unused_local_variable
   info • 'child' is deprecated and shouldn't be used • lib/pages/home.dart:127:9 • deprecated_member_use
   info • Unused import: 'package:flutter_socket_io/socket_io_manager.dart' • lib/pages/login.dart:3:8 • unused_import
   info • The value of the field '_scaffoldKey' isn't used • lib/pages/login.dart:31:34 • unused_field
   info • 'child' is deprecated and shouldn't be used • lib/pages/login.dart:85:7 • deprecated_member_use
   info • 'child' is deprecated and shouldn't be used • lib/pages/login.dart:192:9 • deprecated_member_use
   info • Unused import: 'package:flutter_socket_io/socket_io_manager.dart' • lib/pages/register.dart:3:8 • unused_import
   info • Unused import: 'package:flutter_date_picker/flutter_date_picker.dart' • lib/pages/register.dart:6:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/register.dart:23:11 • non_constant_identifier_names
   info • The method '_setDate' isn't used • lib/pages/register.dart:60:3 • unused_element
   info • Name non-constant identifiers using lowerCamelCase • lib/utils.dart:35:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils.dart:43:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils.dart:51:8 • non_constant_identifier_names

23 issues found. (ran in 61.2s)
```

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.10.2-pre.88, on Mac OS X 10.13.6 17G65, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] Connected device (2 available)
```

**Comment by yongboQu** [comment] 2018-11-21 03:49
seems like   the same error occured in my application, when I tap my page I reveived this:

Receiver: Instance of 'PointerData'
Tried calling: size
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:205:25)
#2      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
#3      ListQueue.addAll (dart:collection/queue.dart:715:25)
#4      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#5      _rootRunUnary (dart:async/zone.dart:1136:13)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _invoke1 (dart:ui/hooks.dart:161:10)
#9      _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)

my flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.11.0, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

my flutter --version

Flutter 0.11.0 • channel unknown • unknown source
Framework • revision c319b890b3 (3 weeks ago) • 2018-10-29 19:44:36 -0700
Engine • revision 162b2e98c0
Tools • Dart 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

BTW my work together use the same flutter version and dart version, but he donot has this error!

**Comment by yongboQu** [comment] 2018-11-21 07:59
> @yongboQu
> 
> `Channel unknown` in
> 
> > [✓] Flutter (Channel unknown, v0.11.0,
> 
> looks quite suspicious.
> Can you try
> 
> ```
> git clean -xfd
> git pull
> flutter doctor
> ```
> in your Flutter install directory?

Thanks for your answer!
the 'channel unknown' info may because I tried to solve the question use 
git checkout v0.11.x 
to change the flutter version
but in the v0.11.1 v0.11.3 v0.11.6 7 8 version it breaks into the new error like this:

NoSuchMethodError: Class 'Locale' has no instance getter 'scriptCode'

and my page shows nothing but an red error view.

Now I flutter version of **v0.10.1**，and all the error was gone. It works fine!

**Comment by zoechi** [comment] 2018-11-21 08:03
@yongboQu perhaps https://github.com/flutter/flutter/issues/24369 would help.

**Comment by goderbauer** [comment] 2018-12-03 22:44
Looks like the issue is resolved. Please reopen with additional information if that's not the case.

**Closed by goderbauer** 2018-12-03 22:44 UTC
Labels: framework, severe: crash
