### ISSUE TITLE
Issues encountered when archiving the flutter project after building ipa

### ISSUE THREAD

**Issue by Trodenn** [flutter/flutter#84846] opened 2021-06-18 09:55 UTC
[error.txt](https://github.com/flutter/flutter/files/6676211/error.txt)
The above file includes the error that I obtain whenever I run `flutter build ipa`
After researching myself on this forum, I understood that the issue is not the error outputs below but something else in my project.
`   objc[45333]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1efc56c10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x116bd02b8). One of the two will be used. Which one is undefined. `
 ` objc[45333]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1efc56c60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x116bd0308). One of the two will be used. Which one is undefined.
    ** ARCHIVE FAILED **`
However, after spending several hours on it, I just can't find what might the reason for this failure in archiving. 
I use macOS Big Sur v.11.4 on a MacBook Pro (13-inch, M1, 2020)
Haven't tried it on other devices yet.
Would appreciate all kinds of help or at least directions, thanks in advance.

**Comment by TahaTesser** [comment] 2021-06-18 11:16
Hi @Trodenn 
Looks like an error is coming from `extended_nested_scroll_view` 

Can you please try to reproduce the issue without this package?

If the problem persists
Please provide your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
Thank you

**Comment by darshankawar** [comment] 2021-07-09 12:55
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-07-09 12:55 UTC
Labels: in triage, waiting for customer response
