### ISSUE TITLE
[Impeller] backdrop filter regressions from `Reland DlAiksCanvas`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#133771] opened 2023-08-31 16:12 UTC
**test:** backdrop_filter_perf_ios__timeline_summary
**average cpu regression:** 244%
**average gpu regression:** 400%

**skiaperf:** [skiaperf](https://flutter-flutter-perf.skia.org/e/?begin=1693434545&end=1693479925&keys=X711aa6c13f994bdd30843f360c7e708f&selected=commit%3D36592%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_cpu_usage%252Ctest%253Dpost_backdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=36592)

cc @dnfield

**Comment by jonahwilliams** [comment] 2023-08-31 18:24
The cause of the regression is validation errors, see also: https://github.com/flutter/flutter/issues/133731

**Comment by jonahwilliams** [comment] 2023-08-31 18:25
We've since reverted dl_aiks_canvas again, but we'll need to fix this before relanding

**Comment by chinmaygarde** [comment] 2023-09-05 20:58
Closing as the Aiks Canvas patch was reverted. Will re-open if observed again.

**Closed by chinmaygarde** 2023-09-05 20:58 UTC
Labels: engine, e: impeller, team-engine
