### ISSUE TITLE
InputDecorator rendering issue height is incorrect

### ISSUE THREAD

**Issue by taorepoara** [flutter/flutter#82709] opened 2021-05-17 16:51 UTC
On Flutter Web (no issue on Android) InputDecorator is smaller than it should.

Example: 
https://dartpad.dartlang.org/705d6b4cd43a594ab189f00deee6d76e?null_safety=true
source: https://gist.github.com/taorepoara/705d6b4cd43a594ab189f00deee6d76e

You can see on this example that the blue elements are smaller than the red ones with an equivalent child.

**Comment by darshankawar** [comment] 2021-05-18 07:57
Verified this using both renderers and noticed below:

1. On web:

<img width="1051" alt="Screenshot 2021-05-18 at 1 24 19 PM" src="https://user-images.githubusercontent.com/67046386/118613771-b0b0d880-b7dc-11eb-8be6-3a9e22808404.png">


2. On Mobile:

<img width="333" alt="Screenshot 2021-05-18 at 1 23 28 PM" src="https://user-images.githubusercontent.com/67046386/118613805-b9a1aa00-b7dc-11eb-8ad1-3b9800c567ef.png">


<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.3.0-2.0.pre.253, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.253 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bac5a0db3b (5 hours ago), 2021-05-18 10:19:03 +0800
    • Engine revision 3cda7f5807
    • Dart version 2.14.0 (build 2.14.0-119.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.



```

</details>

**Comment by darshankawar** [comment] 2021-05-18 07:58
Maybe related to https://github.com/flutter/flutter/issues/55317

**Comment by taorepoara** [comment] 2021-05-18 15:34
Just notice that I have detected this issue trying to make my TextFields the same height as a button. The issue impact the TextField component since it use InputDecorator.

**Comment by yjbanov** [comment] 2021-05-20 22:31
Looks like a framework issue.

**Comment by maheshmnj** [comment] 2022-08-04 04:40
I am able to reproduce the issue on the Desktop platforms and it renders fine on mobile platforms.

 Canvaskit   ❌      |  HTML ❌
:-------------------------:|:-------------------------:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/31410839/182762790-c6cf2783-416b-4d8d-b097-29dc02746578.png">  | <img width="846" alt="image" src="https://user-images.githubusercontent.com/31410839/182762851-146b1c90-c96c-415b-a9d2-3c1f49e64325.png">


Android ✅   |  IOS ✅
:-------------------------:|:-------------------------:
![Screenshot_1659586982](https://user-images.githubusercontent.com/31410839/182762832-afbaf582-bccc-4f76-b634-1d735b9ef85f.png) |  ![Simulator Screen Shot - iPhone 12 Pro - 2022-08-04 at 10 03 03](https://user-images.githubusercontent.com/31410839/182763828-1c609344-26d2-48ea-bd61-a9679c954e0a.png)


### Desktop ❌
<img width="912" alt="image" src="https://user-images.githubusercontent.com/31410839/182763175-8b4b33ed-67b2-48a4-a0b3-cdae966ceecc.png">

|  `Android`  | `IOS` | `MacOs` | `Web` |
| :---: |:---: |:---: |:---: |
| ✅   |  ✅  |  ❌  |   ❌   |

✅ : No Issue ❌: Issue reproduced 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2009, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2009 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9d96c7b8be (3 days ago), 2022-08-01 00:39:06 -0400
    • Engine revision cf0db3e546
    • Dart version 2.19.0 (build 2.19.0-49.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • C217DCBE-806E-4BC7-A952-61E4A647A7DA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.4 21F79
      darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by cbracken** [comment] 2022-08-04 18:23
This looks like it may be the same issue as https://github.com/flutter/flutter/issues/108813.

/cc @hangyujin

**Comment by hangyujin** [comment] 2022-08-25 12:16
Yes it's the same cause as #108813,

`Child` property in `InputDecorator` is Typically an inputText and it uses densityOffset to adjust its size.

A simple workaround is to set `visualDensity: VisualDensity.standard` in `ThemeData`. 

Or maybe we should change the `computeMinIntrinsicHeight` logic in inputDecorator.

**Comment by hangyujin** [comment] 2022-08-25 12:18
Duplicate of #108813

**Comment by darshankawar** [comment] 2022-08-25 13:30
Closing this as a duplicate based on above comment.

**Closed by darshankawar** 2022-08-25 13:30 UTC
Labels: framework, f: material design, a: desktop, has reproducible steps, P4, parity, found in release: 3.0, found in release: 3.1
