### ISSUE TITLE
stock example - generation of localisation files does not work

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#13588] opened 2017-12-15 00:37 UTC
## Steps to Reproduce
I try to regenerate the i18n directory to try out the localisation process but there is no output
(see below)
This in the stock example. The process is described in the regenerate.md
It seems like the complete process relies on that process to work.
Platform is Windows 10
## Logs

```
C:\sdks\flutter\examples\stocks>flutter --verbose  pub pub run intl_translation:extract_to_arb --output-dir=lib\i lib\stock_strings.dart
[  +25 ms] [c:\sdks\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +82 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[        ] [c:\sdks\flutter\] git rev-parse --abbrev-ref HEAD
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] alpha
[        ] [c:\sdks\flutter\] git ls-remote --get-url origin
[  +62 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [c:\sdks\flutter\] git log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8f65fec5f5f7d7afbb0965f4a44bdb330a28fb19
[        ] [c:\sdks\flutter\] git log -n 1 --pretty=format:%ar
[  +62 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 days ago
[ +162 ms] c:\sdks\flutter\bin\cache\dart-sdk\bin\pub.bat run intl_translation:extract_to_arb --output-dir=lib\i lib\stock_strings.dart
c:\sdks\flutter\packages\flutter\pubspec.yaml has changed since the pubspec.lock file was generated, please run "pub get" again.
[ +403 ms] "flutter pub" took 442ms.
pub finished with exit code 65

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:176)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
<asynchronous suspension>
#4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#8      new Future.sync (dart:async/future.dart:222)
#9      CommandRunner.run (package:args/command_runner.dart:109)
#10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#11     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#13     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     runZoned (dart:async/zone.dart:1467)
#17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#18     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#20     main (file:///c:/sdks/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[  +51 ms] ensureAnalyticsSent: 43ms
[   +8 ms] exiting with code 65

C:\sdks\flutter\examples\stocks>

```

## Flutter Doctor
```
C:\sdks\flutter\examples\stocks>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.16299.98], locale en-US, channel alpha)
    • Flutter at c:\sdks\flutter
    • Framework revision 8f65fec5f5 (2 days ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • Moto G 5 Plus             • ZY224DHFWG    • android-arm • Android 7.0 (API 24)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

```

**Comment by robinbakkerus** [comment] 2017-12-26 08:52
I have the same problem on Windows 8, but I get the following 

```
C:\my-dev\Projects\flutter\flutter-master\examples\stocks>flutter pub pub run intl_translation:extract_to_arb --output-dir=lib/i18n lib/stock_strings.dart
c:\my-dev\ide\flutter\packages\flutter\pubspec.yaml has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65
```

**Comment by ride4sun** [comment] 2017-12-26 19:50
@robinbakkerus  Can u run on verbose and see if you get more info.

**Comment by sethladd** [comment] 2018-01-18 01:29
Does it work for you on a fresh/clean project? Wondering if the issue is Windows, or the Stocks example.

cc @HansMuller who has some experience with our localization

**Comment by realcarlos** [comment] 2018-02-07 11:41
Stocks example run failed.

**Comment by ride4sun** [comment] 2018-02-12 17:06
@sethladd could we add the _look_ label to this.

**Comment by sethladd** [comment] 2018-02-12 18:05
done, thanks!

**Comment by zoechi** [comment] 2018-07-24 11:12
This works for me now. 
Can we close the issue?

**Closed** 2018-08-18 04:12 UTC
Labels: a: internationalization, customer: look, waiting for customer response, ❖ platform-windows
