### ISSUE TITLE
[Web] TextField: Cursor misplaced on word tap (mobile devices)

### ISSUE THREAD

**Issue by yaymalaga** [flutter/flutter#87356] opened 2021-07-30 17:56 UTC
I'm using an expanded TextEdit widget as a text input for an app and so far I didn't have any issue on Android or Web (desktop). However, when using the Web version on mobiles (chrome/brave/etc) the cursor is totally broken when the text is larger than the screen (once you scroll), making it real difficult to interact with the text. This happens in Android and Ios devices.

This is the simplified version of the code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(24.0),
          child: TextField(
            scrollPhysics: const BouncingScrollPhysics(),
            cursorColor: Colors.black,
            expands: true,
            textAlignVertical: TextAlignVertical.top,
            decoration: InputDecoration(
              border: OutlineInputBorder(
                borderSide: BorderSide(),
              ),
            ),
            maxLines: null,
            showCursor: true,
            keyboardType: TextInputType.multiline,
            scrollPadding: const EdgeInsets.all(25),
          ),
        ),
      ),
    );
  }
}
```

You can access a deployed version for testing in [https://yaymalaga.netlify.app/](https://yaymalaga.netlify.app/).

To reproduce the issue, just paste a long text, scroll a little bit and try to select a word. You will see that the cursor is misplaced with a huge offset, making the text to even scroll sometimes. Interestingly enough, it works fine just some on some words. Also, some times I can see two markers, one blue and another one red/orange.

In the following video you can see the behavior described. Even thought the red/orange marker seems to be in the correct place, the cursor is going all crazy.

https://user-images.githubusercontent.com/2735961/127692797-acfd533a-9324-4be4-933e-3bd7e84a10ce.mp4

**Comment by yaymalaga** [comment] 2021-07-30 18:04
This is tested in stable:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

• No issues found!
```

However, same behavior in beta, dev and master channels. In this case, the app is built using `flutter build web`, but the same result is found when forcing both html or canvaskit renders.

**Comment by TahaTesser** [comment] 2021-08-02 12:26
Hi @yaymalaga 
Thanks for filing the issue, I can reproduce the issue on iOS and Android on the latest `stable `as well as `master` using both renderers 

Used the following minimal code sample

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(24.0),
          child: TextField(
            scrollPhysics: const BouncingScrollPhysics(),
            cursorColor: Colors.black,
            expands: true,
            textAlignVertical: TextAlignVertical.top,
            decoration: InputDecoration(
              border: OutlineInputBorder(
                borderSide: BorderSide(),
              ),
            ),
            maxLines: null,
            showCursor: true,
            keyboardType: TextInputType.multiline,
            scrollPadding: const EdgeInsets.all(25),
          ),
        ),
      ),
    );
  }
}

``` 

</details>

### Steps to reproduce
1. `flutter build web --web-renderer html` or `flutter build web --web-renderer canvaskit`
2. Paste the long scrollable text paragraph such as one below
<details> 
<summary>sample text</summary> 
	
```console
The first version of Flutter was known as codename "Sky" and ran on the Android operating system. It was unveiled at the 2015 Dart developer summit[6] with the stated intent of being able to render consistently at 120 frames per second.[7] During the keynote of Google Developer Days in Shanghai, Google announced Flutter Release Preview 2, which is the last big release before Flutter 1.0. On December 4, 2018, Flutter 1.0 was released at the Flutter Live event, denoting the first "stable" version of the Framework. On December 11, 2019, Flutter 1.12 was released at the Flutter Interactive event.[8]

On May 6, 2020, the Dart software development kit (SDK) in version 2.8 and the Flutter in version 1.17.0 were released, where support was added to the Metal API, improving performance on iOS devices (approximately 50%), new Material widgets, and new network tracking.

On March 3, 2021, Google released Flutter 2 during an online Flutter Engage event. This major update brought official support for web-based applications with new CanvasKit renderer and web specific widgets, early-access desktop application support for Windows, macOS, and Linux and improved Add-to-App APIs.[9] This release included sound null-safety, which caused many breaking changes and issues with many external packages, but the Flutter team included instructions to mitigate these changes as well.
```
	
</details>
3. Scroll a little bit up and down, then tap a word you can select and tap somewhere else repeat, you will unexpected cursor placement in few tries. 

### Preview (same result on iOS and Android)

https://user-images.githubusercontent.com/48603081/127861408-f2356883-dd3c-401e-9574-f685cdcf5634.mp4



|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.5.0-2.0.pre.113, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.5.0-2.0.pre.113 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0abf02f855 (3 days ago), 2021-07-30 17:44:02 -0700
    • Engine revision 29f9df723f
    • Dart version 2.14.0 (build 2.14.0-368.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```
		
</details>

✅: No Issue ❌: Issue reproduced



Related issues
https://github.com/flutter/flutter/issues/78031
https://github.com/flutter/flutter/issues/77083

**Comment by mdebbar** [comment] 2021-08-05 21:58
Duplicate of https://github.com/flutter/flutter/issues/78031

**Closed by mdebbar** 2021-08-05 21:58 UTC
Labels: a: text input, a: typography, platform-web, has reproducible steps, found in release: 2.2, found in release: 2.5
