### ISSUE TITLE
Flutter always initializes gradle

### ISSUE THREAD

**Issue by lujunoo** [flutter/flutter#26077] opened 2019-01-04 16:53 UTC
Many methods have been tried, there is no effect at all, the program still can not start, please help me

**Comment by zoechi** [comment] 2019-01-04 18:07
Please elaborate what the issue is about.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment] 2019-01-04 18:07
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2019-01-28 09:48
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-28 09:48 UTC
Labels: t: gradle, tool, waiting for customer response
