### ISSUE TITLE
Text selection does not work with a mouse

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15754] opened 2018-03-20 18:00 UTC
The user should be able to press the mouse button, drag over text to select, then release.

**Comment by zoechi** [comment] 2018-12-21 09:08
Related to #757

**Comment by goderbauer** [comment] 2018-12-28 21:33
@gspencergoog FYI

**Comment by mdebbar** [comment] 2019-05-17 21:06
@tvolkert if this is specifically about selection in text fields, then this issue can be closed. I submitted multiple PRs but this is the main one: https://github.com/flutter/flutter/pull/28290

If the issue is about text selection in general, then it should remain open since general text selection hasn't been implemented yet (even for touch).

**Comment by tvolkert** [comment] 2019-05-17 21:15
Cool - thanks for the heads up @mdebbar.  Deferring to @gspencergoog on whether this should remain open.

**Comment by gspencergoog** [comment] 2019-05-18 00:39
Closing: I think this has been addressed, and general text selection is another beast.

**Closed by gspencergoog** 2019-05-18 00:39 UTC
Labels: customer: mulligan (g3), engine, framework, ⎊ platform-chromebook
