### ISSUE TITLE
image_picker: Android app crashes if image without extension is selected

### ISSUE THREAD

**Issue by igolubic** [flutter/flutter#25176] opened 2018-12-10 23:40 UTC
Image picker version: 0.4.10

When image without extension is selected this exception is thrown:

```
E/AndroidRuntime( 8438): FATAL EXCEPTION: main
E/AndroidRuntime( 8438): Process: com.mepigu.mepigu, PID: 8438
E/AndroidRuntime( 8438): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/4461 flg=0x1 }} to activity {com.mepigu.mepigu/com.mepigu.mepigu.MainActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/4461
E/AndroidRuntime( 8438): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5035)
E/AndroidRuntime( 8438): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5078)
E/AndroidRuntime( 8438): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime( 8438): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
E/AndroidRuntime( 8438): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime( 8438): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime( 8438): 	at android.app.ActivityThread.main(ActivityThread.java:7523)
E/AndroidRuntime( 8438): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8438): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime( 8438): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/AndroidRuntime( 8438): Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/4461
E/AndroidRuntime( 8438): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
E/AndroidRuntime( 8438): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime( 8438): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
E/AndroidRuntime( 8438): 	at android.content.ContentResolver.query(ContentResolver.java:766)
E/AndroidRuntime( 8438): 	at android.content.ContentResolver.query(ContentResolver.java:716)
E/AndroidRuntime( 8438): 	at android.content.ContentResolver.query(ContentResolver.java:667)
E/AndroidRuntime( 8438): 	at io.flutter.plugins.imagepicker.FileUtils.getDataColumn(FileUtils.java:117)
E/AndroidRuntime( 8438): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromLocalUri(FileUtils.java:69)
E/AndroidRuntime( 8438): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:41)
E/AndroidRuntime( 8438): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:395)
E/AndroidRuntime( 8438): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime( 8438): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime( 8438): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime( 8438): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime( 8438): 	at android.app.Activity.dispatchActivityResult(Activity.java:7701)
E/AndroidRuntime( 8438): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5031)
E/AndroidRuntime( 8438): 	... 9 more
I/Process ( 8438): Sending signal. PID: 8438 SIG: 9
Lost connection to device.
```

**Comment by CaiJingLong** [comment] 2018-12-11 00:38
Hi, I build a library([photo](https://github.com/CaiJingLong/flutter_photo)) for pick photo. 
Before your problem is solved, you can try it.

**Comment by zoechi** [comment] 2018-12-11 09:34
Please add the output of `flutter doctor -v`.

**Comment by igolubic** [comment] 2018-12-11 11:43
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/igolubic/Flutter/flutter
    • Framework revision 5391447fae (11 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/igolubic/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/igolubic/Software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/igolubic/Software/android-studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /home/igolubic/Software/intellij/ideaIC-2018.2.4/idea-IC-182.4505.22
    • Flutter plugin version 29.0.4
    • Dart plugin version 182.4505.50

[✓] Connected device (1 available)
    • VTR L09 • 6PQ0217711000226 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by truongsinh** [comment] 2018-12-13 16:17
this is actually duplicate of #21863

**Comment by zoechi** [comment] 2018-12-13 18:06
Duplicate of #21863

**Closed by zoechi** 2018-12-13 18:06 UTC
Labels: p: first party, plugin, severe: crash
