### ISSUE TITLE
android.view.View.getContext() java.lang.NullPointerException

### ISSUE THREAD

**Issue by kingofglory** [flutter/flutter#60166] opened 2020-06-24 04:02 UTC
```bash
#1 main

java.lang.NullPointerException

Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
1 io.flutter.plugin.platform.PlatformViewsController.checkInputConnectionProxy(PlatformViewsController.java:393)
2 io.flutter.view.FlutterView.checkInputConnectionProxy(FlutterView.java:445)
3 android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1354)
4 android.view.inputmethod.InputMethodManager.onAmigoPostWindowFocus(InputMethodManager.java:1845)
5 android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4157)
6 android.os.Handler.dispatchMessage(Handler.java:110)
7 android.os.Looper.loop(Looper.java:203)
8 android.app.ActivityThread.main(ActivityThread.java:6354)
9 java.lang.reflect.Method.invoke(Native Method)
10 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1111)
11 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:972)
```
flutter doctor -v:

```console
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/xuguorong/Flutter/flutter
    • Framework revision e6b34c2b5c (7 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xuguorong/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/xuguorong/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

```

**Comment by iapicca** [comment] 2020-06-24 09:22
Hi @kingofglory 
Can you please provide 
 your `flutter run --verbose`, 
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by TahaTesser** [comment] 2020-07-15 15:07
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-15 15:07 UTC
Labels: in triage

**Comment by scofield-hello** [comment] 2020-08-26 07:53
I/ActivityThread(31032): com.chuangdun.flutter.plugin.arcface.DetectActivity activity.onCreate +
W/art     (31032): Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/CrashReport(31032): >>> com.chuangdun.flutter.plugin.arcface.DetectActivity onCreated <<<
I/art     (31032): Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
I/art     (31032):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2436)
I/art     (31032):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/art     (31032):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/art     (31032):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/art     (31032):   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
I/art     (31032):   at void com.chuangdun.flutter.plugin.arcface.DetectActivity.onCreate(android.os.Bundle) (DetectActivity.java:152)
I/art     (31032):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6694)
I/art     (31032):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1121)
I/art     (31032):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2721)
I/art     (31032):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2833)
I/art     (31032):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     (31032):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1561)
I/art     (31032):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:110)
I/art     (31032):   at void android.os.Looper.loop() (Looper.java:203)
I/art     (31032):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6354)
I/art     (31032):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (31032):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1111)
I/art     (31032):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:972)
I/art     (31032): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.chuangdun.borderkeeper-2/base.apk"],nativeLibraryDirectories=[/data/app/com.chuangdun.borderkeeper-2/lib/arm64, /data/app/com.chuangdun.borderkeeper-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
I/art     (31032):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art     (31032):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     (31032):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     (31032):   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2436)
I/art     (31032):   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
I/art     (31032):   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
I/art     (31032):   at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
I/art     (31032):   at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
I/art     (31032):   at void com.chuangdun.flutter.plugin.arcface.DetectActivity.onCreate(android.os.Bundle) (DetectActivity.java:152)
I/art     (31032):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6694)
I/art     (31032):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1121)
I/art     (31032):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2721)
I/art     (31032):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2833)
I/art     (31032):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     (31032):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1561)
I/art     (31032):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:110)
I/art     (31032):   at void android.os.Looper.loop() (Looper.java:203)
I/art     (31032):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6354)
I/art     (31032):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (31032):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1111)
I/art     (31032):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:972)
I/art     (31032): 
D/OpenGLRenderer(31032): ~CanvasContext() 0x79be87c500
I/ActivityThread(31032): com.chuangdun.flutter.plugin.arcface.DetectActivity activity.onCreate -
I/ActivityThread(31032): com.chuangdun.flutter.plugin.arcface.DetectActivity activity.onStart +
I/ActivityThread(31032): com.chuangdun.flutter.plugin.arcface.DetectActivity activity.onStart -
I/ActivityThread(31032): com.chuangdun.flutter.plugin.arcface.DetectActivity activity.onResume +
D/CrashReport(31032): >>> com.chuangdun.flutter.plugin.arcface.DetectActivity onResumed <<<
I/ActivityThread(31032): com.chuangdun.flutter.plugin.arcface.DetectActivity activity.onResume -
V/PhoneWindow(31032): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@ed0da43[]
D/Choreographer(31032): Choreographer: set Context com.android.internal.policy.DecorContext@43f88c0 to android.view.Choreographer@3220bb3
D/WindowClient(31032): Add to mViews: DecorView@ed0da43[DetectActivity], this = android.view.WindowManagerGlobal@481b570
D/OpenGLRenderer(31032): CanvasContext() 0x79be87c500
D/ViewRootImpl[DetectActivity](31032): hardware acceleration is enabled, this = ViewRoot{f37e9f9 com.chuangdun.borderkeeper/com.chuangdun.flutter.plugin.arcface.DetectActivity,ident = 2}
V/PhoneWindow(31032): DecorView setVisiblity: visibility = 0, Parent = ViewRoot{f37e9f9 com.chuangdun.borderkeeper/com.chuangdun.flutter.plugin.arcface.DetectActivity,ident = 2}, this = DecorView@ed0da43[DetectActivity]
D/OpenGLRenderer(31032): CanvasContext() 0x79be87c500 initialize window=0x79bddf9e00, title=com.chuangdun.borderkeeper/com.chuangdun.flutter.plugin.arcface.DetectActivity
D/Surface (31032): Surface::connect(this=0x79bddf9e00,api=1)
W/libEGL  (31032): [ANDROID_RECORDABLE] format: 1
D/mali_winsys(31032): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/MPlugin (31032): com.mediatek.common.telephony.IOnlyOwnerSimSupportClazz exists on mapping table : false
E/MPlugin (31032): Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
D/SettingsInterface(31032):  from settings cache , name = android_id,  value = 26df55a3e52f836a
I/DetectActivity(31032): initEngine:  init: 0  version:VersionInfo{version='3.0.12021020101.4', buildDate='2020-07-10', copyRight='Copyright 2020 ArcSoft Corporation Limited. All rights reserved.'}
D/Camera-JNI(31032): (tid:31032)[MtkJNICameraContext] this:0x79ccae90e0 camera->getStrongCount(3) 
D/Camera  (31032): app passed NULL surface
D/InputMethodManager(31032): onAmigoWindowFocus  restartInput
D/AndroidRuntime(31032): Shutting down VM
E/CrashReport(31032): Java Crash Happen cause by main(1)
W/CrashReport(31032): no read_log permission!
I/CrashReport(31032): user log size:0
E/CrashReport(31032): stack frame :11, has cause false
E/CrashReport(31032): #++++++++++Record By Bugly++++++++++#
E/CrashReport(31032): # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
E/CrashReport(31032): # PKG NAME: com.chuangdun.borderkeeper
E/CrashReport(31032): # APP VER: 1.6.0
E/CrashReport(31032): # LAUNCH TIME: 2020-08-26 15:17:53
E/CrashReport(31032): # CRASH TYPE: JAVA_CRASH
E/CrashReport(31032): # CRASH TIME: 2020-08-26 15:19:17
E/CrashReport(31032): # CRASH PROCESS: com.chuangdun.borderkeeper
E/CrashReport(31032): # CRASH THREAD: main
E/CrashReport(31032): # REPORT ID: 472691fe-de76-4fdb-8dda-a8db9fefeb87
E/CrashReport(31032): # CRASH DEVICE: GIONEE M7L UNROOT
E/CrashReport(31032): # RUNTIME AVAIL RAM:2489204736 ROM:35490496512 SD:35490496512
E/CrashReport(31032): # RUNTIME TOTAL RAM:5870485504 ROM:56282726400 SD:56282726400
E/CrashReport(31032): # CRASH STACK: 
E/CrashReport(31032): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
E/CrashReport(31032): 	at io.flutter.plugin.platform.PlatformViewsController.checkInputConnectionProxy(PlatformViewsController.java:393)
E/CrashReport(31032): 	at io.flutter.embedding.android.FlutterView.checkInputConnectionProxy(FlutterView.java:531)
E/CrashReport(31032): 	at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1354)
E/CrashReport(31032): 	at android.view.inputmethod.InputMethodManager.onAmigoPostWindowFocus(InputMethodManager.java:1845)
E/CrashReport(31032): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4157)
E/CrashReport(31032): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/CrashReport(31032): 	at android.os.Looper.loop(Looper.java:203)
E/CrashReport(31032): 	at android.app.ActivityThread.main(ActivityThread.java:6354)
E/CrashReport(31032): 	at java.lang.reflect.Method.invoke(Native Method)
E/CrashReport(31032): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1111)
E/CrashReport(31032): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:972)
E/CrashReport(31032): #++++++++++++++++++++++++++++++++++++++++++#
D/CrashReport(31032): [Database] deleted t_lr data 0
D/CrashReport(31032): [Database] insert t_lr success.
I/CrashReportInfo(31032): [crash] a crash occur, handling...
D/CrashReport(31032): [Database] insert t_cr success.
D/CrashReport(31032): insert t_cr success!
I/CrashReportInfo(31032): [crash] save crash success
I/CrashReport(31032): try to upload right now
D/CrashReport(31032): attach pageTracingList

**Comment by TahaTesser** [comment] 2020-08-26 09:14
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
