### ISSUE TITLE
Error while using the Firebase

### ISSUE THREAD

**Issue by PartapSBimrah** [flutter/flutter#70283] opened 2020-11-11 10:39 UTC
I have an error while using the `cloud_firestore:`. See the screenshot down below.

`The built failed likely due to AndroidX incompatibilities in a plugin.`

![Screenshot (307)](https://user-images.githubusercontent.com/39325207/98801717-39b71380-2438-11eb-95c1-b2d1ad85b6c2.png)

**Comment by TahaTesser** [comment] 2020-11-11 14:04
Hi @PartapSBimrah 
Please migrated your project to [AndroidX](https://flutter.dev/docs/development/androidx-migration) 
If the problem persists after that, From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-11 14:04 UTC
