### ISSUE TITLE
Flutter android-licenses bug

### ISSUE THREAD

**Issue by eugrro** [flutter/flutter#82138] opened 2021-05-09 04:00 UTC
Am trying to setup flutter: 
Running into this issue. Trying to report this bug.
Also I do have android studio installed so I'm not sure why its saying that

```
C:\Users\me>flutter doctor --verbose
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.964], locale en-US)
    • Flutter version 2.0.5 at C:\Users\me\Documents\flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\me\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Java\jdk-16.0.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 16.0.1+9-24)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.56.0)
    • VS Code at C:\Users\me\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)      • edge     • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 2 categories.
```

```
C:\Users\me>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 5 more

```

**Comment by byytelope** [comment] 2021-05-09 05:28
happening to me too with flutter 2.0.6 android platform tools 31.0.2 and openjdk11 on macOS

**Comment by Cybineer** [comment] 2021-05-09 20:09
I just want to say thank you. i am very new to github and was able to find the solution to the issue i was having with android studio. Thank you so very much.

**Comment by darshankawar** [comment] 2021-05-10 10:13
Closing this as duplicate of https://github.com/flutter/flutter/issues/80273

**Closed by darshankawar** 2021-05-10 10:13 UTC
Labels: in triage
