### ISSUE TITLE
App not installed error after Flutter 2.2

### ISSUE THREAD

**Issue by akfaisel** [flutter/flutter#85301] opened 2021-06-25 09:55 UTC
Hi

Three months back, I developed a Flutter project (using Flutter 1.22) and built apk using `flutter build apk`

Now I have updated my Flutter to 2.2 Stable. I built apk for the same code (without any modification to the source code) but this time the apk is not installing. I'm getting "App not installed"

The apk files are uploaded at https://ufile.io/f/k1gx0

_Note: These apks are neither signed nor available at Play Store. This app is purely for internal circulation only._

**Expected:** The new apk is supposed to install over the old version.

**Actual:** App not installed error.

If I uninstall the old apk and install the new apk, the installation goes well. But if I uninstall, old app data gets cleared. 

### Here is my Flutter Doctor report
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1052], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Connected device (3 available)

• No issues found!
```
### Here is my pubspec.yaml

```
name: projacct
description: Personal Project and Accounting app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  fluttertoast: ^7.1.6
  intl: ^0.16.1
  percent_indicator: ^2.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
```
This issue is driving me nuts.

Please help me.

**Comment by TahaTesser** [comment] 2021-06-28 10:49
Hi @akfaisel 
To reproduce the issue, I've installed `1.22.6`, created a project and built APK from `1.22`, and installed it on the device, and then built APK  from `2.2.2`  and installed that, the app is updated with new APK 


### `1.22.6`

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19043.1081], locale en-US)
    • Flutter version 1.22.6 at C:\Users\Taha\Code\flutter
    • Framework revision 9b2d32b605 (5 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

### `2.2.2`
<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1081], locale en-US)
    • Flutter version 2.2.2 at C:\Users\Taha\Code\flutter_stable
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1081]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 91.0.864.59

! Doctor found issues in 1 category.
```

</details>

Can you please try to reproduce the issue following the steps I mentioned with new projects? If there are any other steps required to reproduce the issue, let me know 
Thanks

**Comment by akfaisel** [comment] 2021-06-28 10:58
2 days back, I downgraded Flutter to 1.22 but still no hope. 

Initially, I was using Android SDK version 28 but recently I have updated to version 30. Is the mismatch due to differences in Android version?

Can you please analyse the difference between 2 apk versions?

Apk 1: Flutter 1.23 + Android 28
Apk 2: Flutter 2.2.2 + Android 30

My client is mad at me as I could not provide him an update.

**Comment by marslannasr7koncepts** [comment] 2021-06-28 12:37
Let me know more about this issue is app is not installed on any device and your getting error **app not installed.?**

> 2 days back, I downgraded Flutter to 1.22 but still no hope.
> 
> Initially, I was using Android SDK version 28 but recently I have updated to version 30. Is the mismatch due to differences in Android version?
> 
> Can you please analyse the difference between 2 apk versions?
> 
> Apk 1: Flutter 1.23 + Android 28
> Apk 2: Flutter 2.2.2 + Android 30
> 
> My client is mad at me as I could not provide him an update.

**Comment by akfaisel** [comment] 2021-06-28 13:50
I'll split into 2 periods.

In period 1, I was using Flutter 1.22 with Android 28. That time I built an apk (say v1) using `flutter build apk`. I am not sure if this is debug or release version.

In period 2, I updated to Flutter 2.2 and Android 30. I built the same code using `flutter build apk` and tried to install (say v2) to the same device v1 was installed and got the error.

I wanted to test in another device. So I installed v1 and then installed v2 over v1, same error is thrown. 

I can uninstall v1 and then install v2 but the data are gone.

**Comment by marslannasr7koncepts** [comment] 2021-06-29 05:21
So that mean your able to install the app within the device now but issue is data gone can you tell me is your using local cache like sqflite or shared preferences.?

> I'll split into 2 periods.
> 
> In period 1, I was using Flutter 1.22 with Android 28. That time I built an apk (say v1) using `flutter build apk`. I am not sure if this is debug or release version.
> 
> In period 2, I updated to Flutter 2.2 and Android 30. I built the same code using `flutter build apk` and tried to install (say v2) to the same device v1 was installed and got the error.
> 
> I wanted to test in another device. So I installed v1 and then installed v2 over v1, same error is thrown.
> 
> I can uninstall v1 and then install v2 but the data are gone.

**Comment by TahaTesser** [comment] 2021-06-29 09:28
Hi @akfaisel 
Unfortunately, it is not possible to analyze your APKs, most likely it is an issue with your situation rather a  bug in Flutter,  as mentioned in my testing, creating a new project and building APK loads fine.

This could also be caused by your sqflite cache, can you please simply reproduce with a new project on both versions, let m know if you can reproduce an issue with flutter build
Thank you

**Comment by TahaTesser** [comment] 2021-07-21 12:08
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-21 12:08 UTC
Labels: in triage, waiting for customer response
