### ISSUE TITLE
complex_layout_scroll_perf__devtools_memory is 4.65% flaky

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#82741] opened 2021-05-17 21:09 UTC
The benchmark test complex_layout_scroll_perf__devtools_memory had a flaky ratio 4.65%, which is above our self-imposed 2% threshold.

(Creating this issue as part of the gardener rotation.)

**Comment by jonahwilliams** [comment] 2021-05-17 21:10
See also: https://github.com/flutter/flutter/pull/82739 which will hopefully reduce some of the startup flakes and https://github.com/flutter/devtools/issues/3037 which means the test is actually producing 0 useful data

**Comment by zanderso** [comment] 2021-05-17 21:35
As @jonahwilliams mentioned, this is due to https://github.com/flutter/flutter/issues/82142

**Comment by zanderso** [comment] 2021-05-20 04:22
The cause of the flakiness has been addressed by fixing https://github.com/flutter/flutter/issues/82142, so closing this as presumed fixed.

**Closed by zanderso** 2021-05-20 04:22 UTC
Labels: P1, d: devtools, team: flakes, tool
