### ISSUE TITLE
Dead link in first flutter app https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#6

### ISSUE THREAD

**Issue by ljsimpkin** [flutter/flutter#93477] opened 2021-11-11 10:30 UTC
## Steps to Reproduce

1. ... Go to https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#6
2. ... Click on "color" hyperlink at the bottom of the page => Inside The <Colors> class in the Material library
3. ... Web linked to looks like this https://docs.flutter.io/flutter/material/Colors-class.html

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by mamuseferha** [comment] 2021-11-11 10:40
Hi @ljsimpkin thank you for filing this issue, I verified it and it is reproducible.

**Comment by DeepP2667** [comment] 2021-11-11 20:13
Hi! I've never contributed to an open source issue and this one seemed like an easier one to do. I was wondering if I could try to fix this issue with some guidance. Just some questions I had. 
Which branch would I be working on?
Where would this type of issue be located in the repo. Would it be in a documentation folder? 
Thanks!

**Comment by RedBrogdon** [comment] 2021-11-11 20:26
The code for our codelabs is generally stored in the flutter/codelabs repo. The text, on the other hand, isn't something we've got an open source infrastructure for, unfortunately, which means we're not able to accept PRs for it anywhere.

That said, finding the dead link is a great catch, so just reporting the issue is a useful contribution!

**Comment by domesticmouse** [comment] 2022-01-07 12:19
For Googler, fix is in cl/420260786

**Closed by domesticmouse** 2022-01-07 12:19 UTC
Labels: d: codelabs, documentation, passed first triage
