### ISSUE TITLE
[tool_crash] StateError: Bad state: Cannot add event after closing

### ISSUE THREAD

**Issue by aihamhasan** [flutter/flutter#69176] opened 2020-10-28 08:23 UTC
## Command
```
flutter run --machine --target lib\main.dart -d web-server --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Cannot add event after closing
```
#0      _StreamController.add (dart:async/stream_controller.dart:623:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:900:13)
#2      AppConnection.runMain (package:dwds/src/connections/app_connection.dart:31:22)
#3      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:732:25)
<asynchronous suspension>
#4      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#12     _rootRun (dart:async/zone.dart:1182:47)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel dev, 1.24.0-3.0.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-IN)
    • Flutter version 1.24.0-3.0.pre at C:\Users\Avin Ronson\flutter
    • Framework revision 2783f8e2e1 (6 days ago), 2020-10-22 09:36:06 -0700
    • Engine revision defa8be2b1
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Avin Ronson\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Avin Ronson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • RMX2030 (mobile) • 8c9797ff   • android-arm64  • Android 9 (API 28)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.51

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.4+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: fabeb2a16f1d008ab8230f450c49141d35669798
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
file_picker-1.13.3
file_picker_web-1.0.2+1
firebase_auth-0.15.5+3
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_storage-3.1.6
flutter_plugin_android_lifecycle-1.0.11
flutter_radio-0.1.8
flutter_web_view-0.0.6
google_maps_flutter-0.5.33
open_file-3.0.1
path_provider-1.6.18
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
shared_preferences-0.5.12
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+1
sqflite-1.3.1+1

**Comment by pedromassangocode** [comment] 2020-10-28 09:36
Closing as a duplicate of https://github.com/flutter/flutter/issues/59757. 

For anyone facing the same issue, please follow on the issue mentioned.

**Closed by pedromassangocode** 2020-10-28 09:36 UTC
Labels: severe: crash, tool
