### ISSUE TITLE
[web] Not able to scroll by mouse wheel when hover selectabletext and other widgets

### ISSUE THREAD

**Issue by mordivgor** [flutter/flutter#71324] opened 2020-11-27 19:12 UTC
## Steps to Reproduce

<details>
  <summary>Code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    List<Widget> _widgets = [];
    for (int i = 0; i < 30; i++) {
      _widgets.add(
        Padding(
          padding: EdgeInsets.symmetric(vertical: 8.0),
          child: Container(
            height: 30,
            width: 200,
            color: Colors.red,
            child: SelectableText(
              'Text' + i.toString()
            ),
          )
        )
      );
    }
    return MaterialApp(
      title: 'Default label',
      home: Scaffold(
        body: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: _widgets,
          )
        )
      )
    );
  }
}
```
</details>

**Expected results:** 

It shall be possible to still scroll the whole screen when hovering selectableText.

**Actual results:** 

When hover selectableText, scrolling by mouse wheel shall be possible.
The same behaviour can be seen also for TextField and some other widgets.

<details>
  <summary>Doctor</summary>

```
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.630], locale pl-PL)
    • Flutter version 1.24.0-10.2.pre at G:\IOT\flutter\flutter
    • Framework revision 022b333a08 (9 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Radek\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.51

• No issues found!
```

</details>

**Comment by eyoeldefare** [comment] 2020-11-27 21:44
no because you gave the `Container` widget a `width: 200`. 
Change that to:
`
    Container(
                height: 30,
                width: double.infinity,
                color: Colors.red,
                child: SelectableText('Text' + i.toString()),
   )

`
Also for it makes no sense `List<Widget> _widgets = [];` should be called every-time the tree is built. Also this question should be in Stackoverflow, not here.

**Comment by mordivgor** [comment] 2020-11-27 22:30
@eyoeldefare it changes nothing. The problem persists.

**Comment by eyoeldefare** [comment] 2020-11-27 23:10
Oh I miss read your question as being scrolling when you press on the whole page instead of using the mouse-wheel specifically. I don't know why using Mousewheel is significant for you. The point is to mimic a hand gesture by pressing and scrolling in native devices.

**Comment by darshankawar** [comment] 2020-11-30 07:44
@mordivgor 
So the expected behavior is when we select a text or hove mouse over any text, we should be able to scroll the screen ?

**Comment by mordivgor** [comment] 2020-11-30 13:09
@darshankawar not quite - when we are using SelectableText widget, then hovering this widget causes unavailability of scrolling. There is no need of select the text to make the scroll unavailable - just use SelectableText and hover the mouse.

**Comment by darshankawar** [comment] 2020-11-30 13:34
Verified and replicable on latest beta. When we hover over SelectableText widget using trackpad or mouse, the screen doesn't scroll. Whereas, the same use case on Android and using trackpad, the screen scrolls properly.

[71324.mov.zip](https://github.com/flutter/flutter/files/5616165/71324.mov.zip)

[71324_and.mov.zip](https://github.com/flutter/flutter/files/5616188/71324_and.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 022b333a08 (12 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.67

• No issues found!

```

</details>

**Comment by yjbanov** [comment] 2020-12-03 23:14
Reassigned from web to desktop. This probably affects all desktop platforms.

/cc @Piinks

**Comment by Piinks** [comment] 2020-12-07 20:05
I believe this was fixed with this issue: https://github.com/flutter/flutter/issues/70948
Please check the mater branch, I have just now checked and it appears to be working.

```
[✓] Flutter (Channel unknown, 1.25.0-5.0.pre.55, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.25.0-5.0.pre.55 at /Users/katelovett/github/flutter
    • Framework revision 7c99326230 (2 minutes ago), 2020-12-07 14:02:42 -0600
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```

**Comment by lifehug** [comment] 2020-12-08 01:43
> I believe this was fixed with this issue: #70948
> Please check the mater branch, I have just now checked and it appears to be working.
> 
> ```
> [✓] Flutter (Channel unknown, 1.25.0-5.0.pre.55, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
>     • Flutter version 1.25.0-5.0.pre.55 at /Users/katelovett/github/flutter
>     • Framework revision 7c99326230 (2 minutes ago), 2020-12-07 14:02:42 -0600
>     • Engine revision 20caf54969
>     • Dart version 2.12.0 (build 2.12.0-76.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/katelovett/Library/Android/sdk
>     • Platform android-29, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.3.1, Build version 11C505
>     • CocoaPods version 1.9.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 48.1.2
>     • Dart plugin version 193.7547
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.51.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.16.0
> 
> [✓] Connected device (3 available)
>     • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
>     • Web Server (web) • web-server • web-javascript • Flutter Tools
>     • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198
> 
> • No issues found!
> ```

will this fix be in beta and other branches too?

**Comment by Piinks** [comment] 2020-12-08 18:45
> will this fix be in beta and other branches too?

@lifehug Of course. Changes always roll master -> dev -> beta -> stable. 
See https://github.com/flutter/flutter/wiki/Flutter-build-release-channels for more info

**Comment by mordivgor** [comment] 2020-12-08 21:32
@Piinks indeed, it looks like it works with "master, 1.25.0-5.0.pre.116"

**Comment by Piinks** [comment] 2020-12-08 21:38
Great! Thank you for checking @mordivgor! I am going to close this as fixed then. :)

**Closed by Piinks** 2020-12-08 21:38 UTC
Labels: a: desktop, f: scrolling, found in release: 1.24, framework, has reproducible steps, passed first triage
