### ISSUE TITLE
Image_Picker plugin fatal exception

### ISSUE THREAD

**Issue by pulstar** [flutter/flutter#68152] opened 2020-10-14 23:12 UTC
When I try to capture an image using the camera, right after I touch the confirmation button, the application exit and I got the errors below. I had this problem more than 6 months ago, since then I upgraded Flutter many times and this problem still remain... The only solution I found was to use the Multi_Image_Picker plugin, but its interface is confusing. User experience was much better with Image_Picker, but it doesn't work anymore. Any idea what is causing this? May another installed plugin have broke it?

```
D/AndroidRuntime(32153): Shutting down VM
E/AndroidRuntime(32153): FATAL EXCEPTION: main
E/AndroidRuntime(32153): Process: com.domain.project, PID: 32153
E/AndroidRuntime(32153): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {com.domain.project/com.domain.project.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
E/AndroidRuntime(32153): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
E/AndroidRuntime(32153): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4433)
E/AndroidRuntime(32153): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(32153): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(32153): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(32153): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
E/AndroidRuntime(32153): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(32153): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(32153): 	at android.app.ActivityThread.main(ActivityThread.java:6702)
E/AndroidRuntime(32153): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32153): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(32153): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
E/AndroidRuntime(32153): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
E/AndroidRuntime(32153): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate$3.getFullImagePath(ImagePickerDelegate.java:158)
E/AndroidRuntime(32153): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.handleCaptureImageResult(ImagePickerDelegate.java:455)
E/AndroidRuntime(32153): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:416)
E/AndroidRuntime(32153): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
E/AndroidRuntime(32153): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime(32153): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:652)
E/AndroidRuntime(32153): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:618)
E/AndroidRuntime(32153): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime(32153): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4384)
E/AndroidRuntime(32153): 	... 11 more
I/Process (32153): Sending signal. PID: 32153 SIG: 9
Lost connection to device.
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [versÃ£o 10.0.18363.1139], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (not installed)  <<<=== but it is installed!
[√] Connected device (5 available)

! Doctor found issues in 2 categories.
```

**Comment by Abhishek01039** [comment] 2020-10-15 05:06
Hi @pulstar 
can you please provide `flutter doctor -v` and minimal reproduction code?
Thanks.

**Comment by pedromassangocode** [comment] 2020-10-15 09:08
@pulstar as asked above we will need a minimal reproducible code sample!

**Comment by pulstar** [comment] 2020-10-31 13:11
As far as I know, this is some kind of conflict between Flutter plugins. At first, I detected that the multi_image_picker plugin was causing this. I installed it after I gave up with image_picker. But after removing it, the problem remain, so any other of my hundreds installed plugins is causing this problem too. If I manage to detect which one is doing this, I will post a minimal reproducible code.

**Comment by hamdikahloun** [comment] 2020-11-01 13:00
Hi @pulstar 

From what I can see, the issue is related to a 3rd party plugin ([image_picker_saver](https://pub.dev/packages/image_picker_saver)) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/cnhefang/image_picker_saver/issues) .

```
E/AndroidRuntime(32153): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
E/AndroidRuntime(32153): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate$3.getFullImagePath(ImagePickerDelegate.java:158)
```
Thank you

**Comment by pedromassangocode** [comment] 2020-11-02 07:22
Good catch @hamdikahloun 

Closing as this is not an issue with Flutter itself.

**Closed by pedromassangocode** 2020-11-02 07:22 UTC
Labels: in triage
