### ISSUE TITLE
Status bar transparency doesn't work an Samsung

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10221] opened 2017-05-19 23:34 UTC
Probably some variation of #6586 and #8802. Though this is on a new Samsung S8 with 7.0. 

![img_2463](https://cloud.githubusercontent.com/assets/156888/26270583/db24764a-3cb0-11e7-8519-0d1ebaa3b36b.JPG)

Left is Nexus with 4.0 and right is S8 with 7.0. (Look at that shinny bright screen though)

**Comment by goderbauer** [comment] 2018-12-27 22:40
Closing as dupe of #8802.

**Closed by goderbauer** 2018-12-27 22:40 UTC
Labels: e: device-specific, framework, ▣ platform-android
