### ISSUE TITLE
socket_patch.dart Invalid internet address type.fit

### ISSUE THREAD

**Issue by ozayr** [flutter/flutter#126665] opened 2023-05-12 12:17 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

upgrade to flutter 3.10

### Expected results

No errors, as was the case in the previous version

### Actual results

socket_patch.dart is throwing a random error, that I cannot even trace. 

`
if (inAddr == null) {
        throw ArgumentError('Invalid internet address $address');
      }
`
address has the value type.fit 

### Code sample

<details><summary>Code sample</summary>

```dart
no code
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.78.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by ozayr** [comment] 2023-05-12 14:02
Hi, apologies type.fit is coming from the code (type.fit although weird should still be a valid internet address). I am making an http request to this url

`
final response = await http.get(Uri.parse('https://type.fit/api/quotes'));
`

it seems this error is coming from the http package, where type.fit is not parsing as a valid internet address.
however the code still runs and the request is made successfully. However code keeps throwing there.

using http: ^0.13.6

**Comment by milindgoel15** [comment] 2023-05-13 02:57
Same issue #126650

**Comment by darshankawar** [comment] 2023-05-15 06:03
@ozayr 
Can you please confirm if the same happens on latest master version as well ?

**Comment by hrrysnplusplus** [comment] 2023-05-15 22:34
yes it does i think the problem is _parse(address). it should be tryParse(address)

**Comment by darshankawar** [comment] 2023-05-16 06:24
Thanks for the update. Let's track this issue in https://github.com/flutter/flutter/issues/126650. I'll close this in favor of the linked issue. If anybody disagrees, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-05-16 06:24 UTC
Labels: waiting for customer response, in triage
