### ISSUE TITLE
Hello, how can I insert a highlighted and one-time deleted string into the TextField?

### ISSUE THREAD

**Issue by hyz1992** [flutter/flutter#25248] opened 2018-12-12 02:27 UTC
![The effect I want is this](https://s1.ax2x.com/2018/12/12/5QdVkG.png)

Can you give me some suggestions?
Thank you very much!

**Comment by zoechi** [comment] 2018-12-12 10:09
I assume this is a
Duplicate of #17809

Feel free to add a comment if you disagree.

**Closed by zoechi** 2018-12-12 10:09 UTC
