### ISSUE TITLE
Scrollbar should have property for displaying always.

### ISSUE THREAD

**Issue by onatcipli** [flutter/flutter#28836] opened 2019-03-04 13:06 UTC
## Scrollbar new property for displaying the Scrollbar always

I think Scrollbar needs a feature for displaying it always.

I think it is something needed :
https://stackoverflow.com/questions/54963284/always-show-scrollbar-flutter

I added this feature in that branch ,Scrollbar not fading out but it is not displaying in the first state without scrolling: https://github.com/onatcipli/flutter/tree/scrollbar_display_always

## Logs
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.316], locale tr-TR)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\msi\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\msi\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\msi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\182.5264788\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Users\msi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\182.5264788
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Users\msi\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\183.5429.30
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by tudor07** [comment] 2019-04-02 11:45
We should be able to customize the `Scrollbar` more. (thickness, color, etc.)

**Comment by dliberman** [comment] 2019-09-20 01:12
Hello @HansMuller! Any update for this - highly wanted - improvement? 😄

**Comment by onatcipli** [comment] 2019-09-20 10:51
there is an example of [Always Visible Scrollbar for Flutter](https://gist.github.com/slightfoot/beb74749bf2e743a6da294b37a7dcf8d) created by @slightfoot  maybe it can help you @dliberman

**Comment by dliberman** [comment] 2019-09-20 13:59
Thank you Onat! I'll look into it.

**Comment by liyuqian** [comment] 2019-10-25 06:52
+1 for always visible option. @HansMuller

**Comment by alectogeek** [comment] 2019-10-30 08:20
+1

**Comment by onatcipli** [comment] 2019-10-31 08:40
@justinmc Sure, I would like to turn into a PR after completing to needed work.

**Comment by omarbelkhodja** [comment] 2019-11-11 10:43
The always visible feature is very important for Flutter on Web, because the web users are expecting to see a scrollbar when the content is overflowing. Also, making the scrollbar draggable is very important. I don't know if we should create another PR for it

**Comment by justinmc** [comment] 2019-11-11 17:17
@omarbelkhodja I would open a separate issue for making the scrollbar draggable if you don't see an existing one.

CupertinoScrollbar is already draggable as of https://github.com/flutter/flutter/pull/35829, so we could reuse some of that code.

**Comment by danielmessi13** [comment] 2019-11-13 12:19
+1

**Comment by isorensen** [comment] 2019-11-13 21:49
+1

**Comment by jaweii** [comment] 2019-12-04 09:45
+1

**Comment by lucasgris** [comment] 2019-12-14 13:48
+1

**Comment by Lootwig** [comment] 2019-12-29 16:20
Optional short flashing when the scrollable view loads would be a nice addition, too.

**Comment by ChristBKK** [comment] 2020-01-03 18:46
+1

**Comment by Marek00Malik** [comment] 2020-01-16 21:37
+1

**Comment by at-toannguyen3** [comment] 2020-01-17 08:41
+1

**Comment by NicolasDionB** [comment] 2020-01-17 14:42
I think you should do a "like" / +1 on the original issue report instead of adding "+1" comments...

**Comment by j5ingh** [comment] 2020-02-04 17:22
@onatcipli any news on this issue?

**Comment by onatcipli** [comment] 2020-02-04 18:52
@j5ingh  work in progress in following PR [44888](https://github.com/flutter/flutter/pull/44888) only test needed, I will write it ASAP

**Comment by thearaks** [comment] 2020-03-06 11:06
I don't know if it's OT but since we're rewriting this feature we should also add the possibility to **never** show the scrollbars, i.e. when the app UI has a custom scrollbar/progressbar.
Or even the ability to provide a custom ScrollbarPainter to the scrollable views.
Thanks!

**Comment by justinmc** [comment] 2020-03-09 22:47
@thearaks When are you getting a scrollbar when you don't want one?

**Comment by thearaks** [comment] 2020-03-10 21:23
@justinmc I know it's a bit of an edge-case but I stumbled upod an UI design of a vertical ListView with an horizontal scrollbar (something like a progress indicator).
In this case I'd like to be able to disable the standard scrollbars or provide a ScrollbarPainter that paints them with transparent color so that I can provide my custom scrollbar implementation.
A custom ScrollbarPainter could also be useful to customize the scrollbar appearance (I don't know if there are other means to obtain such customization).

**Comment by justinmc** [comment] 2020-04-06 22:00
Closing this with https://github.com/flutter/flutter/pull/50752.

There are still some ongoing bufixes in https://github.com/flutter/flutter/issues/53771.

**Comment by justinmc** [comment] 2020-04-06 22:01
@thearaks Are you still interested in the never-show-scrollbar thing?  If so, could you open a new issue with a reproduction case?

**Closed by justinmc** 2020-04-06 22:00 UTC
Labels: a: desktop, f: material design, framework, severe: new feature

**Comment by Piyushhhhh** [comment] 2020-04-23 10:29
fixed for me in version 1.17.0
