### ISSUE TITLE
[Linux Desktop] Cannot type in text field after typing : using Dvorak keyboard

### ISSUE THREAD

**Issue by quaintdev** [flutter/flutter#95502] opened 2021-12-18 14:13 UTC
I am not able to type in a text field on my Linux desktop after typing `:`.

**Note: I am using Dvorak on a hardware QWERTY keyboard**. All other keys work and I can safely type anything until I type `:` which is mapped to Z key.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. In any text field try to type a URL of the form `google.com:80`
3. Just after typing the colon no text can be entered and we see below exception for every key press.

```
** (pinotes:273704): WARNING **: 19:27:27.832: Unable to retrieve framework response: Message is not valid JSON

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#e474f(physicalKey: PhysicalKeyboardKey#7001d(usbHidUsage: "0x0007001d", debugName: "Key Z"), logicalKey: LogicalKeyboardKey#0003b(keyId: "0x0000003b", keyLabel: ";", debugName: "Semicolon"), character: null, timeStamp: 6:08:30.332000) and the recorded logical key LogicalKeyboardKey#0003a(keyId: "0x0000003a", keyLabel: ":", debugName: "Colon")
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'
```

**Comment by maheshmnj** [comment] 2021-12-20 06:49
HI @quaintdev, Thanks for filing the issue. I was able to reproduce it using a qwerty keyboard too on `stable 2.8.0`, when pressing shift followed by a colon (:). But this is not reproducible on `master 2.9.0-1.0.pre.94` channel of flutter.  Please try switching to the latest master by running 

```
flutter channel master
flutter upgrade 
```

And if the issue persists on master then please share the updated output of `flutter doctor -v`.

<details>
<summary>logs</summary>

```
Restarted application in 257ms.
** (counter:4725): WARNING **: 12:01:39.671: Unable to retrieve framework response: Message is not valid JSON

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0516a(physicalKey: PhysicalKeyboardKey#70033(usbHidUsage: "0x00070033", debugName: "Semicolon"), logicalKey: LogicalKeyboardKey#0003a(keyId: "0x0000003a", keyLabel: ":", debugName: "Colon"), character: null, timeStamp: 0:12:49.412000) and the recorded logical key LogicalKeyboardKey#0003b(keyId: "0x0000003b", keyLabel: ";", debugName: "Semicolon")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
#3      HardwareKeyboard._assertEventIsRegular
#4      HardwareKeyboard.handleKeyEvent
#5      KeyEventManager.handleRawKeyMessage
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
#7      BasicMessageChannel.setMessageHandler.<anonymous closure>
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#14     _invoke2 (dart:ui/hooks.dart:188:10)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:83:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
** (counter:4725): WARNING **: 12:01:39.675: Unable to retrieve framework response: Message is not valid JSON

════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0516a(physicalKey: PhysicalKeyboardKey#70033(usbHidUsage: "0x00070033", debugName: "Semicolon"), logicalKey: LogicalKeyboardKey#0003a(keyId: "0x0000003a", keyLabel: ":", debugName: "Colon"), character: null, timeStamp: 0:12:49.412000) and the recorded logical key LogicalKeyboardKey#0003b(keyId: "0x0000003b", keyLabel: ";", debugName: "Semicolon")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'

════════════════════════════════════════════════════════════════════════════════
** (counter:4725): WARNING **: 12:01:39.945: Unable to retrieve framework response: Message is not valid JSON

════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0516a(physicalKey: PhysicalKeyboardKey#70033(usbHidUsage: "0x00070033", debugName: "Semicolon"), logicalKey: LogicalKeyboardKey#0003a(keyId: "0x0000003a", keyLabel: ":", debugName: "Colon"), character: null, timeStamp: 0:12:49.412000) and the recorded logical key LogicalKeyboardKey#0003b(keyId: "0x0000003b", keyLabel: ";", debugName: "Semicolon")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'

════════════════════════════════════════════════════════════════════════════════
** (counter:4725): WARNING **: 12:01:40.161: Unable to retrieve framework response: Message is not valid JSON

════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0516a(physicalKey: PhysicalKeyboardKey#70033(usbHidUsage: "0x00070033", debugName: "Semicolon"), logicalKey: LogicalKeyboardKey#0003a(keyId: "0x0000003a", keyLabel: ":", debugName: "Colon"), character: null, timeStamp: 0:12:49.412000) and the recorded logical key LogicalKeyboardKey#0003b(keyId: "0x0000003b", keyLabel: ";", debugName: "Semicolon")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0516a(physicalKey: PhysicalKeyboardKey#70033(usbHidUsage: "0x00070033", debugName: "Semicolon"), logicalKey: LogicalKeyboardKey#0003a(keyId: "0x0000003a", keyLabel: ":", debugName: "Colon"), character: null, timeStamp: 0:12:49.412000) and the recorded logical key LogicalKeyboardKey#0003b(keyId: "0x0000003b", keyLabel: ";", debugName: "Semicolon")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'

════════════════════════════════════════════════════════════════════════════════
** (counter:4725): WARNING **: 12:01:42.720: Unable to retrieve framework response: Message is not valid JSON



════════ Exception caught by services library ══════════════════════════════════
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#0516a(physicalKey: PhysicalKeyboardKey#70033(usbHidUsage: "0x00070033", debugName: "Semicolon"), logicalKey: LogicalKeyboardKey#0003a(keyId: "0x0000003a", keyLabel: ":", debugName: "Colon"), character: null, timeStamp: 0:12:49.412000) and the recorded logical key LogicalKeyboardKey#0003b(keyId: "0x0000003b", keyLabel: ";", debugName: "Semicolon")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'

════════════════════════════════════════════════════════════════════════════════
** (counter:4725): WARNING **: 12:01:42.779: Unable to retrieve framework response: Message is not valid JSON
Application finished.
Exited (sigterm)
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on Ubuntu 20.04.3 LTS 5.11.0-41-generic, locale en_GB.UTF-8)
    • Flutter version 2.8.0 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (11 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-41-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.94, on Ubuntu 20.04.3 LTS 5.11.0-41-generic, locale en_GB.UTF-8)
    • Flutter version 2.9.0-1.0.pre.94 at /home/mahesh/Development/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 22bd7246c3 (5 days ago), 2021-12-15 01:49:05 -0500
    • Engine revision 57f7719e6e
    • Dart version 2.16.0 (build 2.16.0-109.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-41-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```

</details>


Thanks

**Comment by quaintdev** [comment] 2021-12-20 17:05
I switched to master and did the upgrade but now I am facing another issue which would prevent the application from compiling. Here's the log
'''
ERROR: ../../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.2/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
../…/interface/local_platform.dart:46
ERROR:       io.Platform.packageRoot; // ignore: deprecated_member_use
ERROR:                   ^^^^^^^^^^^
Exception: Build process failed
'''

I already tried repairing pub cache and flutter clean but to no avail.

**Comment by maheshmnj** [comment] 2021-12-21 06:19
@quaintdev, that error is due to the third-party plugin `platform` which isn't related to this issue, Probably you may report that to the maintainer. Can you please try running the app without the third-party plugin or it would be great if you can try to reproduce the issue in a newly created app on the master channel?

**Comment by quaintdev** [comment] 2021-12-21 17:24
I upgraded the platform dependency and now I do not see issue on channel master.

**Comment by maheshmnj** [comment] 2021-12-22 05:18
Thanks for the confirmation. Closing this issue as fixed on master.

**Closed by maheshmnj** 2021-12-22 05:18 UTC
Labels: in triage
