### ISSUE TITLE
In NestedScrollView + TabView scrolling happens even if there is not enough data to scroll

### ISSUE THREAD

**Issue by rahulrmishra** [flutter/flutter#110004] opened 2022-08-22 14:17 UTC
https://user-images.githubusercontent.com/18341427/185942902-a4ca17d8-458b-4947-a872-0f0701fc73d5.mp4

I have implemented a nestedscrollview along with a tabview. In tabview I only have a listview with only 2 items. Even though there are only 2 items, the scrolling takes place.

````
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late TabController tabController;

  @override
  void initState() {
    super.initState();
    tabController = TabController(
      initialIndex: 0,
      length: 2,
      vsync: this,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Demo"),
      ),
      body: NestedScrollView(
        headerSliverBuilder: (context, value) {
          return [
            SliverToBoxAdapter(
                child: Column(
              children: [
                Container(
                  height: 200,
                  width: 200,
                  color: Colors.green,
                ),
                SizedBox(height: 20),
                Container(
                  height: 200,
                  width: 200,
                  color: Colors.yellow,
                )
              ],
            )),
            SliverAppBar(
              backgroundColor: Colors.pink,
              toolbarHeight: 45,
              title: TabBar(
                controller: tabController,
                isScrollable: false,
                indicatorWeight: 2,
                indicatorColor: Colors.red,
                tabs: const [
                  Tab(
                    text: "Tab A",
                  ),
                  Tab(
                    text: "Tab B",
                  )
                ],
              ),
            ),
          ];
        },
        body: TabBarView(
          controller: tabController,
          children: [
            ListView.builder(
              shrinkWrap: true,
              itemCount: 2,
              itemBuilder: (context, index) => Container(
                color: Colors.blue,
                child: Text(
                  '123',
                  style: TextStyle(color: Colors.white),
                ),
              ),
            ),
            ListView.builder(
              shrinkWrap: true,
              itemCount: 2,
              itemBuilder: (context, index) => Container(
                color: Colors.blue,
                child: Text(
                  '123',
                  style: TextStyle(color: Colors.white),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
````

**Comment by maheshmnj** [comment] 2022-08-23 07:47
Hi @rahulrmishra, Thanks for filing the issue. I would say this is working as intended Because TabBarView takes up the available space.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/31410839/186100617-258ad8c0-73b3-4a3b-9946-5effb3a72a63.png">

**Comment by rahulrmishra** [comment] 2022-08-23 13:38
@maheshmnj Oh okay, got it. In that case do we have some mechanism to stop its scroll if sufficient data is not present

**Comment by maheshmnj** [comment] 2022-08-24 04:59
@rahulrmishra I think a solution like this https://stackoverflow.com/questions/54642710/tabbarview-with-dynamic-container-height might work for your use case.

Closing as this is working as intended.

**Closed by maheshmnj** 2022-08-24 04:59 UTC
Labels: in triage
