### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted, local_auth 0.6.2+3

### ISSUE THREAD

**Issue by dkp123100** [flutter/flutter#59318] opened 2020-06-12 10:22 UTC
Hello,

I have used local_auth 0.6.2+3 dependency in flutter for fingerprint authentication.
But I am going for the authenticate then app gone crash and showing following error.
```
java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:231)
        at io.flutter.plugins.localauth.LocalAuthPlugin$1.onSuccess(LocalAuthPlugin.java:102)
        at io.flutter.plugins.localauth.AuthenticationHelper.onAuthenticationSucceeded(AuthenticationHelper.java:171)
        at androidx.biometric.FingerprintHelperFragment$1.lambda$onAuthenticationSucceeded$3$FingerprintHelperFragment$1(FingerprintHelperFragment.java:147)
        at androidx.biometric.-$$Lambda$FingerprintHelperFragment$1$rDjOuSgiro7y44NwdPGXt_KugWQ.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

If anyone know about this issue, can you please help to fix this?

**Comment by TahaTesser** [comment] 2020-06-12 11:50
duplicate of https://github.com/flutter/flutter/issues/29092

**Closed by TahaTesser** 2020-06-12 11:51 UTC

**Comment by Shakhboz95** [comment] 2020-08-05 09:08
Hi all

Did anyone find the solution? I got same problem while using local_ auth 0.6.2+3 version. At first time it works, after reopening application fingerprint auth doesn't work. Show same error!

And I think it is not duplicate of #29092, because there is used MethodChannel, in our case we are getting during biometric 
authention

**Comment by idris11** [comment] 2020-10-08 09:51
Hi all

Did anyone find the solution? I got the same problem, shows the same error!

**Comment by idris11** [comment] 2020-10-09 03:11
> duplicate of #29092

this is not duplicate

**Comment by TahaTesser** [comment] 2020-10-09 12:56
@idris11 
 please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.

**Comment by Shakhboz95** [comment] 2020-10-09 16:45
> Hi all
> 
> Did anyone find the solution? I got the same problem, shows the same error!

if I am not mistaken, I downgraded build gradle to 3.6.2 and I am using local_auth 0.6.3

now it is working well

**Comment by idris11** [comment] 2020-10-10 03:46
> @idris11
> That's my bad, please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.

the issue is same as above
`java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:231)
        at io.flutter.plugins.localauth.LocalAuthPlugin$1.onSuccess(LocalAuthPlugin.java:102)
        at io.flutter.plugins.localauth.AuthenticationHelper.onAuthenticationSucceeded(AuthenticationHelper.java:171)
        at androidx.biometric.FingerprintHelperFragment$1.lambda$onAuthenticationSucceeded$3$FingerprintHelperFragment$1(FingerprintHelperFragment.java:147)
        at androidx.biometric.-$$Lambda$FingerprintHelperFragment$1$rDjOuSgiro7y44NwdPGXt_KugWQ.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)`

**Comment by TahaTesser** [comment] 2020-10-13 11:48
@idris11 

please file a new issue with the exact description of what happens, logs, and the output of flutter doctor -v.

**Comment by GnafGnaf** [comment] 2021-02-04 17:36
We also had this Problem and downgrading build gradle and local_auth as @Shakhboz95 suggested, helped.

**Comment by AnshGaikwad** [comment] 2021-02-09 12:24
@GnafGnaf can you please elaborate a little what you did in order to fix that issue? 
I am facing the same issue right now, the application crashes when it is used to authenticate at the 'resume' life cycle stat of the application. Please help! Thank you!

**Comment by jans-y** [comment] 2021-02-09 12:40
@AnshGaikwad I think switching to **`FlutterFragmentActivity`** fixed it for me


**`android/app/src/main/kotlin/com/example/app/MainActivity.kt`** <– folder names has to match your application ID
```
package com.example.app  <==  change this to your application ID !!!

import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}
```

**Comment by AnshGaikwad** [comment] 2021-02-09 12:47
@jans-y Yes I did that before writing this issue, its noted in the readme file over [here](https://github.com/flutter/plugins/tree/master/packages/local_auth). But unfortunately, it doesn't fix the issue. Whenever the application goes into the resume state and the authentication is done the application crashes, with the message, java.lang.IllegalStateException: Reply already submitted. Tried for a fix everywhere, didn't find any.

**Comment by AnshGaikwad** [comment] 2021-02-09 12:49
> > @idris11
> > That's my bad, please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> 
> the issue is same as above
> `java.lang.IllegalStateException: Reply already submitted at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139) at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:231) at io.flutter.plugins.localauth.LocalAuthPlugin$1.onSuccess(LocalAuthPlugin.java:102) at io.flutter.plugins.localauth.AuthenticationHelper.onAuthenticationSucceeded(AuthenticationHelper.java:171) at androidx.biometric.FingerprintHelperFragment$1.lambda$onAuthenticationSucceeded$3$FingerprintHelperFragment$1(FingerprintHelperFragment.java:147) at androidx.biometric.-$$Lambda$FingerprintHelperFragment$1$rDjOuSgiro7y44NwdPGXt_KugWQ.run(Unknown Source:4) at android.os.Handler.handleCallback(Handler.java:790) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6626) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)`

The log is the same as above.

**Comment by GnafGnaf** [comment] 2021-02-09 13:11
> @GnafGnaf can you please elaborate a little what you did in order to fix that issue?
> I am facing the same issue right now, the application crashes when it is used to authenticate at the 'resume' life cycle stat of the application. Please help! Thank you!

Hi, we went to android/gradle/wrapper/gradle-wrapper.properties and changed the distributionUrl to [...]/gradle-6.1.1-all.zip. We also set the dependency in our pubspec.yaml to local_auth: 0.6.3. 
After that, it worked.

**Comment by AnshGaikwad** [comment] 2021-02-09 13:43
@GnafGnaf Tried it rn, still crashes after authentication at Resume state.
Any other fixes anyone?

**Comment by GnafGnaf** [comment] 2021-02-17 15:40
@TahaTesser Can you reopen this bug report, please? We still get the error on some devices and it triggers a crash. Not the best user experience.

**Comment by AnshGaikwad** [comment] 2021-02-17 16:21
Actually, I got the issue it was happening after the app goes into the inactive stage and calling another screen, which had the biometric authentication code inside it's initState. So, moving it from inactive to resume fixed that but rn, it still crashes when we lock our phone keeping the app running and after unlocking and authenticating with biometric then it crashes. I found a pattern, before crashing, the local auth sends a log statement similar to Platform Exception ......
Whenever this statement comes into the log, it is sure that the app will crash after biometric authentication.

**Comment by TahaTesser** [comment] 2021-02-18 10:21
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
