### ISSUE TITLE
Hot releoad error , after flutter upgrade, dart upgrade;

### ISSUE THREAD

**Issue by Wtoto** [flutter/flutter#82971] opened 2021-05-20 01:56 UTC
<img src="https://user-images.githubusercontent.com/13692239/118907143-9b10ef80-b951-11eb-8e16-f689f30aa507.jpg" height="550" />	

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H114 darwin-x64,
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)]
```

**Comment by Wtoto** [comment] 2021-05-20 05:04
It can be reproduced; I made a  demo to show the case;

**Comment by Wtoto** [comment] 2021-05-20 05:08
1. make a  native app
2. make flutter module
3.  flutter build ios --debug 
4. copy app.framework and flutter.framework to nativeapp
5. attch flutter module from vscode
6. make somechange
7. save
8. error show

**Comment by TahaTesser** [comment] 2021-05-20 13:21
Hi @Wtoto 
The error is from a third-party package

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Comment by Wtoto** [comment] 2021-05-21 02:00
I tried with a minimal reproducible code sample that does not use 3rd party plugins  ;
please download this file;
thanks;


https://ecloud.baidu.com?t=88c90c27e77f0842157edc87075139ce



flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7
    19H114 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.4 at /Users/wuqi/flutter/flutter
    • Framework revision b1395592de (7 weeks ago),
      2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror
      https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices
    (Android SDK version 30.0.2)
    • Android SDK at /Users/wuqi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/wuqi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • 李元芳iPhone6_12.2 (mobile) •
      a41bbbbce82ee7f29986071137255b934c772094 • ios
      • iOS 12.2
    • Chrome (web)             • chrome
      • web-javascript • Google Chrome 90.0.4430.212

**Comment by TahaTesser** [comment] 2021-05-26 12:56
Hi @Wtoto 
The link you provied isn't working, please copy/paste the minimal code sample below

**Comment by Wtoto** [comment] 2021-05-28 02:02
Actually, i just made a empty native project and flutter module;  
flutter build; and copy app.framwork and Flutter.framwork to native project;
open a flutter page from native; 
attach flutter code from vscode;
make some change;
save;
things happend;


by the way, what's the mean of not working? cannot download?

**Comment by TahaTesser** [comment] 2021-05-28 06:39
Hi @Wtoto 
Thanks for the update, however the steps you mentioned are not sufficient to reproduce the issue, please provide a reproducible code sample, please create a sample repository which includes native app and module, complete steps to reproduce the issue

**Comment by Wtoto** [comment] 2021-05-28 07:43
https://github.com/Wtoto/flutter_hot_reload

**Comment by TahaTesser** [comment] 2021-05-28 12:57
Hi @Wtoto 
Running your I see blank sreen due to no UI in main storyboard 

<img width="274" alt="Screenshot 2021-05-28 at 3 53 29 PM" src="https://user-images.githubusercontent.com/48603081/119987160-63e3b380-bfcd-11eb-8c54-face49fcaee3.png">


While trying to attach I get the following error 
```
 flutter attach --app-id com.example.myFlutter
  flutter attach --app-id com.example.myFlutter (2)
```

Instead of this, you can provide to modify code sample from `[flutter/samples`](https://github.com/flutter/samples/tree/master/add_to_app)

**Comment by darshankawar** [comment] 2021-06-18 13:02
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-06-18 13:02 UTC
Labels: in triage, waiting for customer response
