### ISSUE TITLE
Issue from website page Reading and Writing Files

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#13788] opened 2017-12-28 19:49 UTC
From URL: https://flutter.io/reading-writing-files/

I created a new project with flutter create. Copy and pasted this example into main.dart.
Added path_provider: "^0.3.0" to my pubspec.yaml

It does not run in Intellij 2017.3.2
Error :
```Build file '/home/david/.pub-cache/hosted/pub.dartlang.org/path_provider-0.3.0/android/build.gradle' line: 6```
```* What went wrong:```
```A problem occurred evaluating project ':path_provider'.```
```> Could not find method google() for arguments [] on repository container.```

**Comment by mit-mit** [comment] 2017-12-29 09:26
I just tried, and can't seem to repro this.

Can you share the output of running `flutter doctor` in a terminal/console, please?

**Comment by mravn-google** [comment] 2017-12-29 09:29
@Rockvole Version 0.3.0 of the `path_provider` plugin does not work with current `alpha` branch of Flutter. The reason is that the plugin has been upgraded to Gradle 4.1, but the corresponding change to Flutter tooling and project templates are not yet on `alpha` branch.

**Comment by mit-mit** [comment] 2017-12-29 09:30
Ah, that would explain it; I tried master.

@mravn-google, are we rolling alpha?

**Comment by mravn-google** [comment] 2017-12-29 10:25
I have a few Gradle-related changes to make, then I'll do a roll.

**Comment by Rockvole** [comment] 2017-12-29 19:30
Thanks for looking into this for me guys.

**Comment by artAst** [comment] 2017-12-31 01:19
I also tried reverting to 0.2.2 as mentioned by @mravn-google but still it is pointing an error to 0.3.0
I removed the plugin, and still getting the same error:



* Error running Gradle:
Exit code 1 from: /Users/macbook/Documents/flProjects/myapp/android/gradlew app:properties:
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/macbook/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/macbook/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/macbook/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.


BUILD FAILED

Total time: 5.622 secs


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/macbook/.pub-cache/hosted/pub.dartlang.org/path_provider-0.3.0/android/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':path_provider'.
> Could not find method google() for arguments [] on repository container.

**Comment by ianmcxa** [comment] 2018-01-01 03:46
I am also seeing the error, even after updating the gradle files.

**Comment by mravn-google** [comment] 2018-01-01 15:01
@ianmcxa @artAst I was able to reproduce the problem you described above. It appears that the `.flutter-plugins` file is not always correctly rewritten after a change to `pubspec.yaml`. Removing that file should fix it, as Flutter tooling will the recreate it correctly. I'll investigate a bit more, and file an issue on this.

1. Create Flutter project using alpha branch
1. Add dependency on `path_provider` version 0.3.0
1. `flutter run` (fails with Gradle error because the plugin is using Gradle 4.1 API)
1. Downgrade plugin dependency to 0.2.2
1. `flutter run` (still fails with same Gradle error, citing version 0.3.0 of plugin)
1. Observe: `.flutter-plugins` file incorrectly contains a reference to version 0.3.0.
1. Delete `.flutter-plugins`
1. `flutter run` (works)

**Comment by jonahwilliams** [comment] 2020-02-05 03:08
This issue was likely fixed by https://github.com/flutter/flutter/pull/13827

**Closed by jonahwilliams** 2020-02-05 03:08 UTC
Labels: p: first party, p: tooling, plugin, t: gradle, tool
