### ISSUE TITLE
Cannot execute operation because FlutterJNI is not attached to native. Flutter (Channel unknown, v1.17.1)

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#57361] opened 2020-05-16 06:43 UTC
hi
getting below issue with Flutter (Channel unknown, v1.17.1)
```

Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222)
       at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35)
       at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141)
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

![image](https://user-images.githubusercontent.com/47334522/82112847-ac7d5580-9759-11ea-94ad-9da0f3841c87.png)

$ **flutter doctor -v**
[✓] Flutter (Channel unknown, v1.17.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.1 at /home/cirrus/sdks/flutter
    • Framework revision f7a6a7906b (3 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[!] Connected device
    ! No devices available
! Doctor found issues in 3 categories

**Comment by TahaTesser** [comment] 2020-05-18 10:41
Hi @kw2019ltd 
Please explain in detail on what device you experiencing this issue? Is this production app or new project? Can you reproduce the issue locally? Is this add to app?
can you please provide your `flutter doctor -v` with proper setup and `flutter run --verbose`? Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by kw2019ltd** [comment] 2020-05-18 13:00
hi its not in my end one of my user having this issue

Device: Nexus 5X.

for me locally not reproducible, its error reported on firebase 

$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.17.1, on Linux, locale en_US.UTF-8)
• Flutter version 1.17.1 at /home/cirrus/sdks/flutter
• Framework revision f7a6a79 (3 days ago), 2020-05-12 18:39:00 -0700
• Engine revision 6bc433c6b6
• Dart version 2.8.2
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /opt/android-sdk-linux
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /opt/android-sdk-linux
• ANDROID_SDK_ROOT = /opt/android-sdk-linux
• Java binary at: /usr/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[!] Connected device
! No devices available
! Doctor found issues in 3 categories

**Comment by TahaTesser** [comment] 2020-05-18 15:21
Hi @kw2019ltd 
Please provide logs the running your app and post `pubspec.yaml`
Thank you

**Comment by kw2019ltd** [comment] 2020-05-18 19:14
hi i can't provide logs the error taking from Firebase crash report.

pubspec.yaml

version: 2.0.0+82


environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.12.1
  url_launcher: ^5.4.7
  json_annotation: ^3.0.1
  sticky_headers: ^0.1.8+1
  shared_preferences: ^0.5.7+2
  logging: ^0.11.4
  share: ^0.6.4+2
  package_info: ^0.4.0+18
  rxdart: ^0.24.0
  connectivity: ^0.4.8+6
  fluttertoast: ^4.0.1
  charts_flutter: ^0.9.0
  share_extend: ^1.1.5
  path_provider: ^1.6.8
  flutter_html_to_pdf: ^0.5.2
  flutter_slidable: ^0.5.4
  page_transition: ^1.1.5
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  day_night_switcher: ^0.1.0+1
  loading_animations: ^2.1.0
  rate_my_app: ^0.6.0+2
  flutter_staggered_animations: ^0.1.2

  #fireBase
  firebase_core: ^0.4.4+3
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.15
  firebase_admob: ^0.9.3+2
  firebase_remote_config: ^0.3.0+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  build_daemon: ^2.1.4
  build_config: ^0.4.2
  json_serializable: ^3.3.0
  analyzer: ^0.39.8



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

**Comment by TahaTesser** [comment] 2020-05-19 07:10
Hi @kw2019ltd 
I can see you already commented on duplicate isssue https://github.com/flutter/flutter/issues/28651
and since you cannot provide any more information that commented related to crash
i am this closing as duplicate of https://github.com/flutter/flutter/issues/28651

**Closed by TahaTesser** 2020-05-19 07:10 UTC
Labels: in triage
