### ISSUE TITLE
[google_maps_flutter] Pass a GoogleMapController to GoogleMap Widget to prevent inconsistent states

### ISSUE THREAD

**Issue by rubenferreira97** [flutter/flutter#81880] opened 2021-05-05 03:50 UTC
## Use case
Currently `google_maps_flutter` have really weird/unexpected behavior when a `GoogleMap` widget is rebuild in the widget tree (after the very first build), leading to several exceptions and crashes when we use the `GoogleMapController` afterwards. 
An example of this is when we need to update markers given a list of locations. Since `google_maps_flutter` don't expose an API to update markers in the widget itself we need to accomplish this via state management (like `setState` or `StreamBuilder`). 
This is an example, which I believe should only be one of the cases where this Widget breaks given the following bad design:

We can only get the `GoogleMapController` when `GoogleMap` finishes loading `onMapCreated`, which at first seems a reasonable approach however I had crashes given scenarios like this:
1. `GoogleMaps 1` is loading, `GoogleMapController = null` //Documentation says we could use a completer but this seems to make things even worse since we can't call `completer.complete` twice
2. `GoogleMaps 1`  finished loading, `GoogleMapController = controller 1` controlling `GoogleMaps 1` widget
3. User selected a category for markers, which makes a rebuild like **setState{() {markers = locations.filter.map()...}}**
4. `GoogleMaps 2` is loading (new widget since got rebuild), `GoogleMapController = controller 1` controlling `GoogleMaps 1` widget
5. We call `controller.animate` to center the markers as a normal developer might do. //This normally gives me an exception because the controller is assigned to a widget that is not in the widget tree `GoogleMaps 1`.
6. `GoogleMaps 2`  finished loading, `GoogleMapController = controller 2` controlling `GoogleMaps 2` widget. Hurray, now it's safe to use the controller, unless the state is updated again and it still's pointing to Controller 2 and a GoogleMaps 3 is loading, etc...

So the span between `GoogleMaps` dispose (or first build) until a new controller is assigned on `onMapCreated` seems unsafe and can lead to bugs in my experience (or silently drop events like `animate`).

## Proposal
Pass a `GoogleMapController` to `GoogleMap` widget like `TextEditingController` to a `TextField`. 
An implementation idea: controller is like a stream that push events or a notifier. GoogleMap widget listen to them/gets notified. On GoogleMap dispose, stops listening to the controller.  The controller might queue up events (or not) so that events are not lost and the next GoogleMap widget get them (or for example on the first build, where `onMapCreated` might take a while).

This is just a proposal, I would really appreciate a second thought from the Flutter community and team.

**Comment by pedromassangocode** [comment] 2021-05-05 09:11
>leading to several exceptions and crashes when we use the GoogleMapController afterwards.
>An example of this is when we need to update markers given a list of locations. Since google_maps_flutter don't expose >an API to update markers in the widget itself we need to accomplish this via state management (like setState or >StreamBuilder).

Can you please file a new issue describing the steps to reproduce this along with the version of the plugin and your `flutter doctor -v`?

The reason for this proposal seems to be a bug that should be fixed rather than continue with this proposal.

**Comment by TahaTesser** [comment] 2021-05-27 12:51
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-05-27 12:51 UTC
