### ISSUE TITLE
libflutter.so missing error on release apk

### ISSUE THREAD

**Issue by theshivamlko** [flutter/flutter#45088] opened 2019-11-18 06:02 UTC
In one of my app release version is crashing some time, on few phones (more Oneplus 6 n above series). Few days ago it was working fine,  shows error on Firebase Crashlytics
 [Crashlytics Report](https://ibb.co/xJ0jbxK)
 

```
Crashed: Thread: SIGSEGV  0x0000000000000001
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
       at (Missing)()
```

**Android**
**8.0+**
**tested on OnePlus**

 flutter doctor -v

```
C:\Users\Navoki>flutter doctor -v
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine b863200c37df4ed378042de11c4e9ff34e4e58c9...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Downloading package sky_engine...                                   2.1s
Downloading common tools...                                         6.0s
Downloading common tools...                                         6.0s
Downloading windows-x64 tools...                                   11.1s
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.864], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\Users\Navoki\flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Navoki\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Navoki\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2
    • Flutter plugin version 40.1.1
    • Dart plugin version 191.8423

[√] VS Code (version 1.39.0)
    • VS Code at C:\Users\Navoki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by janmoppel** [comment] 2019-11-18 06:52
Hello @theshivamlko !

Thank you for posting an issue. 
This looks like a similar problem to the one reported here: #43252. @iapicca, what do you think?

**Comment by iapicca** [comment] 2019-11-18 08:17
> Hello @theshivamlko !
> 
> Thank you for posting an issue.
> This looks like a similar problem to the one reported here: #43252. @iapicca, what do you think?

I agree.
I'd keep this one open as specific fro OnePlus devices
https://github.com/flutter/flutter/issues/18398

**Comment by gaaclarke** [comment] 2019-11-22 23:38
This doesn't seem to be a crash related to libflutter.so missing, but is a crash and Crashlytics can't symbolicate the crash.  I used to use Crashlytics on iOS and what would happen is that at the end of every build, Crashlytics would upload the debugger symbols to the Crashlytics server.

Something similar would have to happen for Android, either manually or automatically.  You might look to see if you can supply debugger symbols after the fact to help Crashlytics symbolicate the crash.

Here is someone on StackOverflow that is more knowledgable talking about setting up gradle with Android.  @collinjackson might know better how the crashlytics plugin is suppose to work (whether there is extra setup needed to get symbols uploaded to the server with the flutter plugin).

**Comment by cbracken** [comment] 2020-01-10 01:31
@iapicca do you have detailed repro instructions that you can add to help us repro this if we can get our hands on a OnePlus device?

**Comment by iapicca** [comment] 2020-02-05 09:51
@cbracken  I don't have one

Hi @theshivamlko 
are you still experiencing this issue w/ the latest stable version of flutter?
If so would be great if you could provide a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment] 2020-03-20 11:25
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-03-20 11:25 UTC
Labels: e: device-specific, engine, severe: crash, waiting for customer response, ▣ platform-android
