### ISSUE TITLE
go_router package is not supporting hot reload on chrome in Flutter

### ISSUE THREAD

**Issue by amit1172** [flutter/flutter#116476] opened 2022-12-04 06:34 UTC
destination route is not preserved after hot reload.

Sample code:

```
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final _router = GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/',
      name: 'homepage',
      builder: (context, state) => const MyHomePage(),
      routes: [
        GoRoute(
          path: 'shoppingcart',
          name: 'cartpage',
          pageBuilder: (context, state) => MaterialPage(
            key: state.pageKey,
            fullscreenDialog: true,
            child: const ShoppingCartScreen(),
          ),
        )
      ],
    ),
  ],
);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      routerConfig: _router,
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('App Bar'),
          actions: [
            IconButton(
              icon: const Icon(Icons.shopping_cart),
              onPressed: () => context.pushNamed('cartpage'),
            ),
          ],
        ),
        body: Container(
          color: Colors.green[200],
          child: const Center(child: Text("Home Page")),
        ));
  }
}

class ShoppingCartScreen extends StatelessWidget {
  const ShoppingCartScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('shopping cart page'),
      ),
      body: Container(
        color: Colors.purple[200],
        child: const Center(child: Text("Shopping Cart Screen")),
      ),
    );
  }
}

```

Steps to point out issue:

-Step 1: Run above flutter app code on chrome browser.
-Step 2: Click on Shopping Cart icon to go to another screen.
-Step 3: click hot reload

After clicking hot reload, go_router is not persisting "Shopping Cart Screen", instead it is showing home screen.

I am using go_router 5.2.0 in my flutter project but it is not supporting hot reload with the code mentioned above.

**Comment by darshankawar** [comment] 2022-12-05 07:37
Closing as duplicate of https://github.com/flutter/flutter/issues/105553

**Closed by darshankawar** 2022-12-05 07:37 UTC
Labels: in triage
