### ISSUE TITLE
`W/IInputConnectionWrapper`, `D/InputMethodManager`, and `D/InsetsController` dumped to console on interaction with `TextField` on real Android 12 device

### ISSUE THREAD

**Issue by Luckey-Elijah** [flutter/flutter#96662] opened 2022-01-14 16:00 UTC
## Steps to Reproduce

1. `flutter create example`
2. Update `lib/main.dart` to below code sample
3. `flutter run` on physical android device (Pixel 3, running Android 12)
4. Tap on rendered text field and type one letter (`h`, in this example)

**Expected results:** No warning or debug logs dumped to console.

**Actual results:** These types debug, warning, and info logs in console:

```
D/hw-ProcessState
I/Gralloc4
W/Gralloc3
W/Gralloc4
W/Gralloc3
D/InputMethodManager
W/IInputConnectionWrapper
D/InsetsController
D/InputMethodManager
```

See below for more details.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
$ flutter run
Multiple devices found:
Pixel 3 (mobile)          • 8BUX1F6L4                 • android-arm64 • Android 12 (API 31)
<removed>’s iPad (mobile) • 00008030-001D599411E0C02E • ios           • iOS 15.2 19C56
[1]: Pixel 3 (8BUX1F6L4)
[2]: <removed>’s iPad (00008030-001D599411E0C02E)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on Pixel 3 in debug mode...
Running Gradle task 'assembleDebug'...                             13.3s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 4.4s
Syncing files to device Pixel 3...                                  59ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Pixel 3 is available at: http://127.0.0.1:54247/_6o4sC9qciM=/
The Flutter DevTools debugger and profiler on Pixel 3 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:54247/_6o4sC9qciM=/
D/hw-ProcessState(17427): Binder ioctl to enable oneway spam detection failed: Invalid argument
I/Gralloc4(17427): mapper 4.x is not supported
W/Gralloc3(17427): mapper 3.x is not supported
W/Gralloc4(17427): allocator 4.x is not supported
W/Gralloc3(17427): allocator 3.x is not supported
D/InputMethodManager(17427): showSoftInput() view=io.flutter.embedding.android.FlutterView{4a5cef7 VFE...... .F....ID 0,0-1080,2028 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
W/IInputConnectionWrapper(17427): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(17427): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(17427): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(17427): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(17427): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(17427): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(17427): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(17427): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(17427): endBatchEdit on inactive InputConnection
D/InsetsController(17427): show(ime(), fromIme=true)
D/InsetsController(17427): show(ime(), fromIme=true)
D/InputMethodManager(17427): showSoftInput() view=io.flutter.embedding.android.FlutterView{4a5cef7 VFE...... .F...... 0,0-1080,2028 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController(17427): show(ime(), fromIme=true)
Application finished.
```

```console
$ flutter analyze
Analyzing example...                                                    
No issues found! (ran in 1.8s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/<removed>/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/<removed>/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Pixel 3 (mobile)          • 8BUX1F6L4                 • android-arm64 • Android 12 (API 31)
    • <removed>’s iPad (mobile) • 00008030-001D599411E0C02E • ios           • iOS 15.2 19C56

• No issues found!
```

</details>

**Comment by HansMuller** [comment] 2022-01-14 16:35
This appears to be a duplicate of https://github.com/flutter/flutter/issues/9471

**Comment by maheshmnj** [comment] 2022-01-17 07:01
Hi @Luckey-Elijah, thanks for filing the issue, I am seeing similar logs when interacting with TextField on Android 12 emulator, when running on `stable 2.8.1`.

<details>
<summary>logs</summary>


```console
Running Gradle task 'assembleDebug'...                            114.2s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                12.3s
Syncing files to device sdk gphone64 x86 64...                   1,241ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

 Running with sound null safety 

An Observatory debugger and profiler on sdk gphone64 x86 64 is available at:
http://127.0.0.1:52033/KutbX0b-dH0=/
The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:52033/KutbX0b-dH0=/
D/InputMethodManager( 6497): showSoftInput() view=io.flutter.embedding.android.FlutterView{11cfa04 VFE...... 
.F....ID 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6497): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6497): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
D/EGL_emulation( 6497): app_time_stats: avg=13752.17ms min=486.89ms max=27017.44ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=505.62ms min=83.61ms max=927.64ms count=2
D/InsetsController( 6497): show(ime(), fromIme=true)
D/EGL_emulation( 6497): app_time_stats: avg=14410.68ms min=2807.53ms max=26013.84ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=601.07ms min=506.09ms max=696.05ms count=2
D/InputMethodManager( 6497): showSoftInput() view=io.flutter.embedding.android.FlutterView{11cfa04 VFE...... 
.F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 6497): show(ime(), fromIme=true)
D/EGL_emulation( 6497): app_time_stats: avg=289.96ms min=54.13ms max=526.74ms count=4
D/InputMethodManager( 6497): showSoftInput() view=io.flutter.embedding.android.FlutterView{11cfa04 VFE...... 
.F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/TextInputPlugin( 6497): Composing region changed by the framework. Restarting the input method.
D/InsetsController( 6497): show(ime(), fromIme=true)
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6497): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6497): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
D/InsetsController( 6497): show(ime(), fromIme=true)
D/InputMethodManager( 6497): showSoftInput() view=io.flutter.embedding.android.FlutterView{11cfa04 VFE...... 
.F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/TextInputPlugin( 6497): Composing region changed by the framework. Restarting the input method.
W/ListenableEditingState( 6497): a listener was added to EditingState while a batch edit was in progress     
D/EGL_emulation( 6497): app_time_stats: avg=376.85ms min=205.12ms max=563.66ms count=4
W/IInputConnectionWrapper( 6497): getSelectedText on inactive InputConnection
D/InputMethodManager( 6497): showSoftInput() view=io.flutter.embedding.android.FlutterView{11cfa04 VFE...... 
.F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputMethodManager( 6497): showSoftInput() view=io.flutter.embedding.android.FlutterView{11cfa04 VFE...... 
.F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputMethodManager( 6497): showSoftInput() view=io.flutter.embedding.android.FlutterView{11cfa04 VFE...... 
.F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 6497): show(ime(), fromIme=true)
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6497): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6497): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6497): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6497): endBatchEdit on inactive InputConnection
D/InsetsController( 6497): show(ime(), fromIme=true)
D/InsetsController( 6497): show(ime(), fromIme=true)
D/InsetsController( 6497): show(ime(), fromIme=true)
D/InsetsController( 6497): show(ime(), fromIme=true)
D/EGL_emulation( 6497): app_time_stats: avg=362.85ms min=96.78ms max=500.44ms count=4
D/EGL_emulation( 6497): app_time_stats: avg=500.20ms min=500.01ms max=500.40ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=501.30ms min=499.32ms max=503.28ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=498.18ms min=496.43ms max=499.83ms count=3
D/EGL_emulation( 6497): app_time_stats: avg=499.40ms min=498.17ms max=500.07ms count=3
D/EGL_emulation( 6497): app_time_stats: avg=500.40ms min=499.76ms max=501.03ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=501.65ms min=497.33ms max=505.98ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=496.96ms min=490.75ms max=501.30ms count=3
D/EGL_emulation( 6497): app_time_stats: avg=499.72ms min=499.45ms max=500.00ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=499.18ms min=493.94ms max=504.24ms count=3
D/EGL_emulation( 6497): app_time_stats: avg=500.75ms min=499.81ms max=501.69ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=500.04ms min=496.09ms max=503.35ms count=3
D/EGL_emulation( 6497): app_time_stats: avg=500.08ms min=499.43ms max=500.73ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=498.80ms min=496.54ms max=500.84ms count=3
D/EGL_emulation( 6497): app_time_stats: avg=498.95ms min=496.14ms max=501.29ms count=3
D/EGL_emulation( 6497): app_time_stats: avg=499.40ms min=498.61ms max=500.01ms count=3
D/EGL_emulation( 6497): app_time_stats: avg=499.64ms min=498.40ms max=501.00ms count=3
D/EGL_emulation( 6497): app_time_stats: avg=500.86ms min=494.45ms max=507.26ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=506.55ms min=505.61ms max=507.48ms count=2
D/EGL_emulation( 6497): app_time_stats: avg=495.13ms min=484.91ms max=500.32ms count=3

Application finished.
```
</details> 

However, there seems to be a similar issue tracking this bug, as pointed above, Closing as the duplicate of the above-linked issue.

**Closed by maheshmnj** 2022-01-17 07:01 UTC
Labels: in triage
