### ISSUE TITLE
[image_picker] Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:1728287 flg=0x1 }} to activity {com.xx.xxx/com.xx.xx.MainActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by xang555** [flutter/flutter#123201] opened 2023-03-22 09:38 UTC
## Description

The app crashes when picking the image.

## test environment

image_picker: ^0.8.7
flutter  3.7.7
Dart 2.19.4
Android: 8.1.0
Android device: Brand:Vivo, Model:Vivo 1724 

## error message

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:1728287 flg=0x1 }} to activity {com.xx.xxx/com.xx.xxx.MainActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4401)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4445)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6702)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)


Caused by java.lang.StringIndexOutOfBoundsException: String index out of range: -1
       at java.lang.String.substring(String.java:1975)
       at io.flutter.plugins.imagepicker.FileUtils.getBaseName(FileUtils.java:7)
       at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:92)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:13)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:38)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:13)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:10)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:5)
       at android.app.Activity.dispatchActivityResult(Activity.java:7385)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4397)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4445)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6702)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

```

**Comment by huycozy** [comment] 2023-03-22 10:24
Can you please be more specific on `Steps to reproduce`? Does it happen when running [plugin sample code](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example)?

Please provide the complete output of `flutter run -v` so that we may verify the issue. Thanks!

**Comment by EslamShaban07** [comment] 2023-04-02 12:33
the problem still exists

**Comment by rohansohonee1** [comment] 2023-04-10 05:40
Also got this crash. Unable to reproduce this.
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.google.android.apps.docs.storage/document/acc=2;doc=encoded=xBBDAORTtpHpKlzAJ18Sr-aqeG96ISz1lHDuYRHtrONZAO-_Uo_nsSg= flg=0x1 }} to activity {com.agendaboa.app/com.agendaboa.app.MainActivity}: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 10
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5446)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5485)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8098)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
       
       
Caused by java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 10
       at java.lang.String.checkBoundsBeginEnd(String.java:3942)
       at java.lang.String.substring(String.java:2467)
       at io.flutter.plugins.imagepicker.FileUtils.getBaseName(FileUtils.java:134)
       at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:70)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:567)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:544)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
       at android.app.Activity.dispatchActivityResult(Activity.java:8581)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5439)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5485)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8098)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

**Details**
```
Device
Brand:Motorola
Model:Moto G31
Orientation: Portrait
RAM free: 1.64 GB
Disk free: 1.01 GB
Operating System
Version:Android 12
Orientation: Portrait
Rooted:No
Crash
Date:Apr 10, 2023, 7:15:10 AM

image_picker: 0.8.6

flutter stable 3.7.8
```

**Comment by deepak-agendaboa** [comment] 2023-04-12 20:28
Update to https://github.com/flutter/flutter/issues/123201#issuecomment-1501419325

The error happens when the user selects the image from the Google drive.

**Comment by huycozy** [comment] 2023-04-13 03:16
> The error happens when the user selects the image from the Google drive.

@deepak-agendaboa Can you reproduce this issue locally? And do you see it on the similar device (Motorola)?

**Comment by Aruljebaraj** [comment] 2023-04-19 09:59
even im facing the same issue 
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2346, result=-1, data=Intent { flg=0x1 clip={image/* U:content://com.android.providers.downloads.documents/document/4412 ...} }} to activity {com.evis.permassistresident/com.evis.permassistresident.MainActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
E/AndroidRuntime(30633): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4963)
E/AndroidRuntime(30633): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5004)
E/AndroidRuntime(30633): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(30633): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(30633): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(30633): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
E/AndroidRuntime(30633): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(30633): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(30633): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
E/AndroidRuntime(30633): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30633): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(30633): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(30633): Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
E/AndroidRuntime(30633): 	at java.lang.String.substring(String.java:2064)
E/AndroidRuntime(30633): 	at io.flutter.plugins.imagepicker.FileUtils.getBaseName(FileUtils.java:134)
E/AndroidRuntime(30633): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:70)
E/AndroidRuntime(30633): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseMultiImageResult(ImagePickerDelegate.java:580)
E/AndroidRuntime(30633): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:546)
E/AndroidRuntime(30633): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
E/AndroidRuntime(30633): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
E/AndroidRuntime(30633): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
E/AndroidRuntime(30633): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
E/AndroidRuntime(30633): 	at android.app.Activity.dispatchActivityResult(Activity.java:8135)
E/AndroidRuntime(30633): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4956)
E/AndroidRuntime(30633): 	... 11 more
I/Process (30633): Sending signal. PID: 30633 SIG: 9

**Comment by huycozy** [comment] 2023-04-20 03:57
>       at io.flutter.plugins.imagepicker.FileUtils.getBaseName(FileUtils.java:134)

@rohansohonee1  @Aruljebaraj This is a known issue being tracked at https://github.com/flutter/flutter/issues/124821. Please follow up on that issue for further updates.

>        at io.flutter.plugins.imagepicker.FileUtils.getBaseName(FileUtils.java:7)

@xang555 I see this from your stack trace, it looks different than others' stack trace above comments. Can you also check the error again and confirm if it's similar to the issue reported at #124821?

**Comment by huycozy** [comment] 2023-04-20 04:08
>@xang555 I see this from your stack trace, it looks different than others' stack trace above comments. Can you also check the error again and confirm if it's similar to the issue reported at https://github.com/flutter/flutter/issues/124821?

It looks like it's caused by R8 proguard rules, see [this](https://stackoverflow.com/a/73976520/5921933).

Closing this as a duplicate of https://github.com/flutter/flutter/issues/124821.

**Closed by huycozy** 2023-04-20 04:08 UTC
Labels: waiting for customer response, in triage
