### ISSUE TITLE
Android 13 beta issue

### ISSUE THREAD

**Issue by pdrozdowski** [flutter/flutter#109854] opened 2022-08-19 11:58 UTC
Hello Team,

https://play.google.com/console is reporting stability issues when running my Flutter app.
On Android 11, 12 all works perfect, it happens on Android 13 beta.

It throws following Java errors:

```
Error no: 1
FATAL EXCEPTION: main
PID: 23050
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.internal.app.procstats.UidState.updateCombinedState(int, long)' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IActivityManager$Stub$Proxy.attachApplication(IActivityManager.java:5148)
	at android.app.ActivityThread.attach(ActivityThread.java:7586)
	at android.app.ActivityThread.main(ActivityThread.java:7885)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.app.procstats.ProcessState.setCombinedState(ProcessState.java:476)
	at com.android.internal.app.procstats.ProcessState.setState(ProcessState.java:443)
	at com.android.server.am.ProcessProfileRecord.setProcessTrackerState(ProcessProfileRecord.java:621)
	at com.android.server.am.ActivityManagerService.setProcessTrackerStateLOSP(ActivityManagerService.java:15387)
	at com.android.server.am.OomAdjuster.applyOomAdjLSP(OomAdjuster.java:2770)
```

and
```
Error no: 2
FATAL EXCEPTION: main
Process: com.android.systemui, PID: 23831
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.android.systemui.theme.ThemeOverlayController.isSeedColorSet(ThemeOverlayController.java:10)
	at com.android.systemui.theme.ThemeOverlayController.-$$Nest$mhandleWallpaperColors(ThemeOverlayController.java:256)
	at com.android.systemui.theme.ThemeOverlayController$2.onColorsChanged(ThemeOverlayController.java:11)
	at android.app.WallpaperManager$Globals.lambda$onWallpaperColorsChanged$1$android-app-WallpaperManager$Globals(WallpaperManager.java:515)
	at android.app.WallpaperManager$Globals$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

and
```
Error no: 3
FATAL EXCEPTION: main
Process: com.google.android.googlequicksearchbox:interactor, PID: 5807
DeadSystemException: The system died; earlier logs will point to the root cause
```

device described as: "google Redfin 64-bit only" running "Android 13 Beta (SDK 33)" API - arm64-v8a

Happy to attach more details, but not sure which at the moment :)

```
my pubspec.yaml:
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.0.15
  url_launcher: ^6.1.5
  share_plus: ^4.0.10
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  google_mobile_ads: ^2.0.1
  cupertino_icons: ^1.0.2
  flame: 1.2.1
  flame_audio: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    ...

```
I'm on flutter SDK: 3.0.5

```
PS > flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19042.1526], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.0.13)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

```
Regards,

**Comment by darshankawar** [comment] 2022-08-19 13:19
@pdrozdowski 
Looking at the error logs, it seems to be coming from native Android and not from Flutter framework, and since you said you are using Android 13 beta version, could be related to compatibility with Flutter, as, the integration may not be stable yet.

Is there a way for you to replicate it locally on Android 13 beta OS version's device ?

**Comment by pdrozdowski** [comment] 2022-08-19 14:02
tried Emulator - Pixel 5 on API 33 - all works fine locally.

**Comment by pdrozdowski** [comment] 2022-08-19 17:13
can you advise if excluding api33 devices in play console is a valid solution?

**Comment by janschiefer** [comment] 2022-08-20 20:36
This actually also happens in non flutter applications. Seems to be ann Android 33 "Redfin" issue

``08-20 12:17:30.814: W/ziparchive(31772): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/0000000c/dl-Pay.optional_221821100000.dm': No such file or directory
08-20 12:17:30.814: W/ziparchive(31772): [ 08-20 12:17:30.816     0:    0 W/         ]
08-20 12:17:30.814: W/ziparchive(31772): c7  30701 Partial cmo only supported with 1 segment
08-20 12:17:30.814: W/ziparchive(31772): [ 08-20 12:17:30.816     0:    0 W/         ]
08-20 12:17:30.814: W/ziparchive(31772): c7  30701 is dma_set_max_seg_size being set on dev:kgsl-3d0
08-20 12:17:30.814: W/ziparchive(31772): [ 08-20 12:17:30.816     0:    0 I/         ]
08-20 12:17:30.814: W/ziparchive(31772): c7  30701 msm_vidc:   err : ffffffff: .....: qbuf cache ops failed: OUTPUT: idx 43 fd 42 off 0 daddr de600000 size 2359296 filled 2359296 flags 0x0 ts 37838207698000 refcnt 2 mflags 0x1
08-20 12:17:30.829: D/nativeloader(31895): classloader namespace configured for unbundled product apk. library_path=/product/app/Maps/lib/arm64:/product/app/Maps/Maps.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
08-20 12:17:30.829: D/nativeloader(31895): [ 08-20 12:17:30.828     0:    0 W/         ]
08-20 12:17:30.829: D/nativeloader(31895): c7  30701 Partial cmo only supported with 1 segment
08-20 12:17:30.829: D/nativeloader(31895): [ 08-20 12:17:30.828     0:    0 W/         ]
08-20 12:17:30.829: D/nativeloader(31895): c7  30701 is dma_set_max_seg_size being set on dev:kgsl-3d0
08-20 12:17:30.829: D/nativeloader(31895): [ 08-20 12:17:30.828     0:    0 I/         ]
08-20 12:17:30.829: D/nativeloader(31895): c7  30701 msm_vidc:   err : ffffffff: .....: qbuf cache ops failed: OUTPUT: idx 44 fd 51 off 0 daddr dde00000 size 2359296 filled 2359296 flags 0x0 ts 37838219057000 refcnt 2 mflags 0x1
08-20 12:17:30.841: I/Finsky(13291): [72] rqb.r(4): SCH: jobFinished: 10-94. TimeElapsed: 42ms.
08-20 12:17:30.863: I/Robo(30949): Received scrape screen request.
08-20 12:17:30.866: I/Robo(30949): Waiting 30000ms for idleness.
08-20 12:17:30.866: I/Robo(30949): [ 08-20 12:17:30.938     0:    0 W/         ]
08-20 12:17:30.866: I/Robo(30949): c0  30701 Partial cmo only supported with 1 segment
08-20 12:17:30.866: I/Robo(30949): [ 08-20 12:17:30.938     0:    0 W/         ]
08-20 12:17:30.866: I/Robo(30949): c0  30701 is dma_set_max_seg_size being set on dev:kgsl-3d0
08-20 12:17:30.950: V/GraphicsEnvironment(31895): ANGLE Developer option for 'com.google.android.apps.maps' set to: 'default'
08-20 12:17:30.951: V/GraphicsEnvironment(31895): ANGLE GameManagerService for com.google.android.apps.maps: false
08-20 12:17:30.955: D/NetworkSecurityConfig(31895): No Network Security Config specified, using platform default
08-20 12:17:30.957: D/NetworkSecurityConfig(31895): No Network Security Config specified, using platform default
08-20 12:17:30.973: D/BoundBrokerSvc(4863): onUnbind: Intent { act=com.google.android.gms.udc.service.START dat=chimera-action: cmp=com.google.android.gms/.chimera.PersistentApiService }
08-20 12:17:30.979: E/ActivityThread(31533): Failed to find provider info for com.google.android.instantapps.supervisor.SupervisorArchiveProvider
08-20 12:17:31.021: I/Isotope(31533): UID: [10119]  PID: [31533] HygieneTask : Syncing Archive List of size 1
08-20 12:17:31.031: E/ActivityThread(31533): Failed to find provider info for com.google.android.instantapps.supervisor.SupervisorArchiveProvider
08-20 12:17:31.033: I/Isotope(31533): UID: [10119]  PID: [31533] DownloadHandler : file not present on device. Running state machine for com.google.android.instantapps.dna.archive:39.
08-20 12:17:31.033: I/Isotope(31533): UID: [10119]  PID: [31533] DownloadHandler : download state: not_found
08-20 12:17:31.034: I/Isotope(31533): UID: [10119]  PID: [31533] DownloadHandler : FullArchive will be downloaded here: /storage/emulated/0/Android/data/com.android.vending/files/dna_data/FullArchive-12914644121661023051034
08-20 12:17:31.034: I/Isotope(31533): UID: [10119]  PID: [31533] DownloadManagerWrapper : Enqueuing download for url : https://r2---sn-5ualdns6.gvt1.com/play-apps-download-default/download/by-id/AF3DWBcPyOghWqybwzPGzUbuyExVUwnT_qf7AKNIcOTAawHHDfgt0YFVIUexFX-UNZaUpwKL2wW1Znfw4sA0fn1rFAndOTGe0wC3hZwJEhroZT6Q7Xfa_wYkOAZ625xpGfkVU7SPlzB2?cpn=vsy45uk9RKwSEyZy&fexp=20580244&initcwndbps=881250&mh=66&mm=31&mn=sn-5ualdns6&ms=au&mt=1661022554&mv=m&mvi=2&pl=24&expire=1663442249&ip=70.32.128.245&ipbits=0&sparams=expire,ipbits,ip,q:,initcwndbps,mh,mm,mn,ms,mv,mvi,pl&signature=5A1C75B86FF1BC1F1B78ACA6474C12961A599867.95AC985D979023533B349D8C4CFB18917F4321F0&key=am3&playpn=MQ..
08-20 12:17:31.036: D/CompatibilityChangeReporter(1917): Compat change id reported: 135634846; UID 10074; state: DISABLED
08-20 12:17:31.036: D/CompatibilityChangeReporter(1917): Compat change id reported: 177438394; UID 10074; state: DISABLED
08-20 12:17:31.036: D/CompatibilityChangeReporter(1917): Compat change id reported: 135772972; UID 10074; state: DISABLED
08-20 12:17:31.036: D/CompatibilityChangeReporter(1917): Compat change id reported: 135754954; UID 10074; state: ENABLED
08-20 12:17:31.037: D/CompatibilityChangeReporter(1917): Compat change id reported: 143937733; UID 10074; state: ENABLED
08-20 12:17:31.040: W/PlayCommon(31533): [94] adju.m(1): No account for auth token provided
08-20 12:17:31.041: I/PlayCommon(31533): [94] adju.k(169): Connecting to server: https://play.googleapis.com/play/log?format=raw&proto_v2=true
08-20 12:17:31.050: D/Zygote(996): Forked child process 31918
08-20 12:17:31.054: I/ActivityManager(1917): Start proc 31918:android.process.media/u0a74 for content provider {com.android.providers.downloads/com.android.providers.downloads.DownloadProvider}
08-20 12:17:31.061: D/vendor.qti.bluetooth@1.0-health-info(1006): ReportHealthInfo:statistics:
08-20 12:17:31.061: D/vendor.qti.bluetooth@1.0-health-info(1006): ts <19:17:31:061404> rx_vote:0, tx_vote:0, wake_lock holding:0, maximum rx sleep-wake-interval:757sec, maximum tx packet-interval:757secWake_Req sent out:2, Wake_Req received:2Sleep_Ind sent out:2, Sleep_Ind received:2
08-20 12:17:31.064: I/adbd(8421): jdwp connection from 31918
08-20 12:17:31.064: I/adbd(8421): [ 08-20 12:17:31.065     0:    0 I/         ]
08-20 12:17:31.064: I/adbd(8421): c3  31918 binder: 31918:31918 ioctl 40046210 7ffb7bcd18 returned -22
08-20 12:17:31.073: W/ziparchive(29912): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/00000002/PrebuiltGmsCoreSc_DynamiteLoader.dm': No such file or directory
08-20 12:17:31.073: W/ziparchive(29912): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/00000002/PrebuiltGmsCoreSc_DynamiteLoader.dm': No such file or directory
08-20 12:17:31.077: E/ActivityManager(1917): Activity Manager Crash. UID:1000 PID:1917 TRANS:19
08-20 12:17:31.077: E/ActivityManager(1917): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.internal.app.procstats.UidState.updateCombinedState(int, long)' on a null object reference
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.internal.app.procstats.ProcessState.setCombinedState(ProcessState.java:476)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.internal.app.procstats.ProcessState.setState(ProcessState.java:443)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.ProcessProfileRecord.setProcessTrackerState(ProcessProfileRecord.java:621)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.ActivityManagerService.setProcessTrackerStateLOSP(ActivityManagerService.java:15387)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.OomAdjuster.applyOomAdjLSP(OomAdjuster.java:2770)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.OomAdjuster.performUpdateOomAdjLSP(OomAdjuster.java:414)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.OomAdjuster.performUpdateOomAdjLSP(OomAdjuster.java:512)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.OomAdjuster.updateOomAdjLSP(OomAdjuster.java:481)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.OomAdjuster.updateOomAdjLocked(OomAdjuster.java:463)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:15536)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:5000)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:5032)
08-20 12:17:31.077: E/ActivityManager(1917): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2339)
08-20 12:17:31.077: E/ActivityManager(1917): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2638)
08-20 12:17:31.077: E/ActivityManager(1917): 	at android.os.Binder.execTransactInternal(Binder.java:1280)
08-20 12:17:31.077: E/ActivityManager(1917): 	at android.os.Binder.execTransact(Binder.java:1244)
08-20 12:17:31.080: D/AndroidRuntime(31918): Shutting down VM
08-20 12:17:31.080: D/AndroidRuntime(31918): --------- beginning of crash
08-20 12:17:31.082: E/AndroidRuntime(31918): FATAL EXCEPTION: main
08-20 12:17:31.082: E/AndroidRuntime(31918): PID: 31918
08-20 12:17:31.082: E/AndroidRuntime(31918): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.internal.app.procstats.UidState.updateCombinedState(int, long)' on a null object reference
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at android.os.Parcel.createException(Parcel.java:2995)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at android.os.Parcel.readException(Parcel.java:2978)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at android.os.Parcel.readException(Parcel.java:2920)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at android.app.IActivityManager$Stub$Proxy.attachApplication(IActivityManager.java:5148)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at android.app.ActivityThread.attach(ActivityThread.java:7586)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at android.app.ActivityThread.main(ActivityThread.java:7885)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at java.lang.reflect.Method.invoke(Native Method)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
08-20 12:17:31.082: E/AndroidRuntime(31918): Caused by: android.os.RemoteException: Remote stack trace:
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at com.android.internal.app.procstats.ProcessState.setCombinedState(ProcessState.java:476)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at com.android.internal.app.procstats.ProcessState.setState(ProcessState.java:443)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at com.android.server.am.ProcessProfileRecord.setProcessTrackerState(ProcessProfileRecord.java:621)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at com.android.server.am.ActivityManagerService.setProcessTrackerStateLOSP(ActivityManagerService.java:15387)
08-20 12:17:31.082: E/AndroidRuntime(31918): 	at com.android.server.am.OomAdjuster.applyOomAdjLSP(OomAdjuster.java:2770)
08-20 12:17:31.089: I/Process(31918): Sending signal. PID: 31918 SIG: 9
08-20 12:17:31.094: I/DropBoxManagerService(1917): add tag=system_app_crash isTagEnabled=true flags=0x2
08-20 12:17:31.097: D/CompatibilityChangeReporter(31895): Compat change id reported: 160794467; UID 10178; state: ENABLED
08-20 12:17:31.100: I/DynamiteModule(29912): Considering local module com.google.android.gms.measurement.dynamite:65 and remote module com.google.android.gms.measurement.dynamite:73
08-20 12:17:31.100: I/DynamiteModule(29912): Selected remote version of com.google.android.gms.measurement.dynamite, version >= 73
08-20 12:17:31.100: V/DynamiteModule(29912): Dynamite loader version >= 2, using loadModule2NoCrashUtils
08-20 12:17:31.138: D/CompatibilityChangeReporter(1917): Compat change id reported: 161145287; UID 10178; state: DISABLED
08-20 12:17:31.140: W/.apps.messaging(29912): ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/product/priv-app/PrebuiltBugle/PrebuiltBugle.apk*800348155:/product/priv-app/PrebuiltBugle/PrebuiltBugle.apk!classes2.dex*827135511:/product/priv-app/PrebuiltBugle/PrebuiltBugle.apk!classes3.dex*662195856:/product/priv-app/PrebuiltBugle/PrebuiltBugle.apk!classes4.dex*424220233:/product/priv-app/PrebuiltBugle/PrebuiltBugle.apk!classes5.dex*2702298783:/product/priv-app/PrebuiltBugle/PrebuiltBugle.apk!classes6.dex*2996422217]{PCL[/system/framework/org.apache.http.legacy.jar*3145838628]})
08-20 12:17:31.142: I/Zygote(996): Process 31918 exited due to signal 9 (Killed)
08-20 12:17:31.145: I/ActivityManager(1917): Process android.process.media (pid 31918) has died: prcl TRNB
08-20 12:17:31.145: I/libprocessgroup(1917): Successfully killed process cgroup uid 10074 pid 31918 in 0ms
08-20 12:17:31.146: W/BinderNative(1917): Uncaught exception from death notification
08-20 12:17:31.146: W/BinderNative(1917): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.internal.app.procstats.UidState.updateCombinedState(int, long)' on a null object reference
08-20 12:17:31.146: W/BinderNative(1917): 	at com.android.internal.app.procstats.ProcessState.setCombinedState(ProcessState.java:476)
08-20 12:17:31.146: W/BinderNative(1917): 	at com.android.internal.app.procstats.ProcessState.setState(ProcessState.java:443)
08-20 12:17:31.146: W/BinderNative(1917): 	at com.android.server.am.ProcessRecord.resetPackageList(ProcessRecord.java:1213)
08-20 12:17:31.146: W/BinderNative(1917): 	at com.android.server.am.ProcessRecord.onCleanupApplicationRecordLSP(ProcessRecord.java:997)
08-20 12:17:31.146: W/BinderNative(1917): 	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:12321)
08-20 12:17:31.146: W/BinderNative(1917): 	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3237)
08-20 12:17:31.146: W/BinderNative(1917): 	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3344)
08-20 12:17:31.146: W/BinderNative(1917): 	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1478)
08-20 12:17:31.146: W/BinderNative(1917): 	at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:317)
08-20 12:17:31.146: W/BinderNative(1917): 	at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:704)
08-20 12:17:31.148: D/CompatibilityChangeReporter(31895): Compat change id reported: 183155436; UID 10178; state: DISABLED
08-20 12:17:31.148: I/PlayCommon(31533): [94] adju.k(202): Successfully uploaded logs.
08-20 12:17:31.158: I/Robo(30949): Espresso: Milliseconds to extract current screen state: 295
08-20 12:17:31.159: I/Robo(30949): displayWidth = 1080, displayHeight = 2340
08-20 12:17:31.159: I/Robo(30949): [ 08-20 12:17:31.159     0:    0 W/         ]
08-20 12:17:31.159: I/Robo(30949): c0  30701 Partial cmo only supported with 1 segment
08-20 12:17:31.159: I/Robo(30949): [ 08-20 12:17:31.159     0:    0 W/         ]
08-20 12:17:31.159: I/Robo(30949): c0  30701 is dma_set_max_seg_size being set on dev:kgsl-3d0
08-20 12:17:31.159: I/Robo(30949): [ 08-20 12:17:31.159     0:    0 W/         ]
08-20 12:17:31.159: I/Robo(30949): c0  30701 msm_vidc_check_ratelimit: 1 callbacks suppressed
08-20 12:17:31.159: I/Robo(30949): [ 08-20 12:17:31.159     0:    0 I/         ]
08-20 12:17:31.159: I/Robo(30949): c0  30701 msm_vidc:   err : ffffffff: .....: qbuf cache ops failed: OUTPUT: idx 63 fd 45 off 0 daddr de600000 size 2359296 filled 2359296 flags 0x0 ts 37838552763000 refcnt 2 mflags 0x1

**Comment by darshankawar** [comment] 2022-08-22 05:42
Thanks for the update. I think this will need to be reported in dedicated repo here: 
https://issuetracker.google.com/issues, as, a similar issue was reported and fixed. See this for more details as it had same log as mentioned in this issue (Error no: 1): 
https://issuetracker.google.com/issues/233119628

Closing from here. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-08-22 05:42 UTC
Labels: in triage
