### ISSUE TITLE
CupertinoDatePicker not working in Desktop Chrome while working in Chrome on Android

### ISSUE THREAD

**Issue by fbsoftware-stuttgart** [flutter/flutter#94002] opened 2021-11-22 02:03 UTC
CupertinoDatePicker is not reacting in Desktop Chrome browser. Date can not be changed. 

In Chrome on Android, CupertinoDatePicker is working as expected.

```
import 'package:flutter/cupertino.dart';

class DemoActivity extends StatefulWidget {
  DemoActivity({Key? key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => DemoActivityState();
}

class DemoActivityState extends State<DemoActivity> {
  @override
  void initState() {
    super.initState();
}

	@override
  Widget build(BuildContext context) {
    return CupertinoDatePicker(
              mode: CupertinoDatePickerMode.date,
              initialDateTime: DateTime.now(),
              onDateTimeChanged: (DateTime newDateTime) {
              },
            );
	}
  }
```

> flutter doctor -v
> [√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale de-DE)
>     • Flutter version 2.5.3 at C:\Users\[...]\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
>     • Engine revision d3ea636dc5
>     • Dart version 2.14.4
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\[...]\AppData\Local\Android\sdk
>     X cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     X Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 2020.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [√] Connected device (2 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
>     • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.53
> 
> ! Doctor found issues in 1 category.

Is this a bug or a feature?

**Comment by mamuseferha** [comment] 2021-11-22 11:06
Hi @fbsoftware-stuttgart, thank you for filing this issue, I tested this on the latest stable and master channel and the issue is reproducible.


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile)    • emulator-5554                            • android-x86    • Android 11 (API 30)
      (emulator)
    • iPhone (mobile)            • 2cb2f234cda6637b9ad960bd3eae4f38fb3a5896 • ios            • iOS 15.0.2 19A404
    • iPhone 12 Pro Max (mobile) • 98CBBFB1-4069-4A28-B7F7-138911ACBE72     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64     • macOS 11.6.1 20G224
      darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome
      93.0.4577.63

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 2.6.0-12.0.pre.789, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.789 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ae721de3d (12 hours ago), 2021-11-21 15:22:37 -0500
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile)    • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • iPhone (mobile)            • 2cb2f234cda6637b9ad960bd3eae4f38fb3a5896 • ios            • iOS 15.0.2 19A404
    • iPhone 12 Pro Max (mobile) • 98CBBFB1-4069-4A28-B7F7-138911ACBE72     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by mamuseferha** [comment] 2021-11-23 09:23
@fbsoftware-stuttgart 

Drag to scroll is disabled on desktop by default, this has nothing to date picker, any list view by default can't be dragged on desktop. See https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag to restore the behavior.

I'll go ahead and close this issue as it is not a bug or feature request, if you disagree please write in the comments and I will reopen it.

**Closed by mamuseferha** 2021-11-23 09:23 UTC
Labels: framework, f: date/time picker, f: cupertino, platform-web, has reproducible steps, found in release: 2.5, found in release: 2.6
