### ISSUE TITLE
EAGLContext renderbufferStorage fail

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12022] opened 2017-09-09 00:01 UTC
Fails at https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/ios_gl_context.mm#L188.

**Comment by xster** [comment] 2017-09-09 00:24
Strange that it only happens in that project and not in a boiled down version like https://github.com/xster/flutter-test/tree/master/t33_animation_with_native which does more or less the same thing of presentViewController another vc on top of the flutter view which cycles through viewDidDisappear, viewWillAppear

**Comment by xster** [comment] 2017-09-09 00:52
Repro'ed in a reduced case with updated https://github.com/xster/flutter-test/tree/master/t33_animation_with_native using the share plugin. Seems like presentViewController with specifically UIActivityViewController (used by the share dialog) can cause the problem.

**Comment by xster** [comment] 2017-09-13 19:25
As far as I can tell, risks for this whole general category of gl issues can be avoided by fixing #12061. With some testing, it seems to solve the problem for the 2 test cases. 

Going to focus on that approach now.

**Comment by collinjackson** [comment] 2017-10-02 18:26
Reopening because your fix was reverted in https://github.com/flutter/engine/pull/4133

**Comment by collinjackson** [comment] 2017-10-02 19:05
@cbracken can you take a look? @xster is OOO

**Comment by cbracken** [comment] 2017-10-02 19:57
Will do!

**Comment by cbracken** [comment] 2017-10-04 04:28
Re-fixed by #12396

**Comment by najeira** [comment] 2017-10-18 10:39
https://github.com/flutter/engine/pull/4175 reverted the fix

**Comment by xster** [comment] 2017-11-16 20:28
Seems like the code is still in the original state. Re-opening

**Comment by cbracken** [comment] 2017-11-16 23:02
@xster thanks. This is correct. The re-land was reverted due to a performance regression.

**Comment by cbracken** [comment] 2017-11-20 22:17
After investigation of the regressions, I've filed #13111 and re-landed the patch in the engine. I'll be rolling to the framework momentarily.

**Comment by cbracken** [comment] 2017-11-21 00:46
Fixed again in framework in #13114.

**Closed by cbracken** 2017-11-21 00:46 UTC
Labels: customer blocker, customer: posse (eap), plugin, plugin: first party, prod: engine, ⌺‬ platform-ios
