### ISSUE TITLE
Cannot run Flutter app on physical iOS device

### ISSUE THREAD

**Issue by Mikilll94** [flutter/flutter#86699] opened 2021-07-20 08:34 UTC
## Steps to Reproduce

In one of my projects, when I am launching Flutter app on an iOS physical device, I receive the following error:
```
Launching lib/main.dart on My’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: <censored>
Running Xcode build...
Xcode build done.                                            8.2s
Installing and launching...
Could not run build/ios/iphoneos/Runner.app on 00008030-000A18DA1141802E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on My’s iPhone.
```

This error is not present when I create a new Flutter project.

## Logs

<details>
<summary>Logs</summary>

Logs were too long to paste them on Github:

https://pastebin.com/b5q2FHAU

</details>

**Comment by TahaTesser** [comment] 2021-07-20 11:05
Hi @Mikilll94 
This is a duplicate of https://github.com/flutter/flutter/issues/72161
See https://github.com/flutter/flutter/issues/72161#issuecomment-882933889 for more detials
Closing as duplicat eof https://github.com/flutter/flutter/issues/72161
Thank you

**Closed by TahaTesser** 2021-07-20 11:05 UTC
Labels: in triage

**Comment by Mikilll94** [comment] 2021-07-20 15:04
@TahaTesser 
Please reopen my issue. My bug is different and it is not related to observatory timeout. i am not able to run the Flutter app from XCode.

When I run the app from XCode, I receive the following error (which is not a timeout error):
```
Details

Could not launch “Runner”
Domain: IDEDebugSessionErrorDomain
Code: 3
Failure Reason: failed to get the task for process 426
User Info: {
    DVTRadarComponentKey = 855031;
    RawUnderlyingErrorMessage = "failed to get the task for process 426";
}
--


System Information

macOS Version 11.4 (Build 20F71)
Xcode 12.5.1 (18212) (Build 12E507)
Timestamp: 2021-07-20T17:01:01+02:00
```

**Comment by TahaTesser** [comment] 2021-07-21 11:14
@Mikilll94 
These are `flutter run -v` https://github.com/flutter/flutter/issues/86699#issue-948427454 not Xcode 

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by Mikilll94** [comment] 2021-07-21 11:44
@TahaTesser 
Sorry for the confusion. It turned out that I was using Ad-Hoc provisioning profile in debug mode. After I changed it to development provisioning profile, everything is working fine.

Now this issue is resolved for me.
