### ISSUE TITLE
NoSuchMethodError (NoSuchMethodError: The getter 'debugDidSendFirstFrameEvent' was called on null. Receiver: null

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#57943] opened 2020-05-25 12:25 UTC
when start my flutter, it always report error;  as overflowstack tells it will report such error when missing runApp, but I have and the stack is following;
```
Object.noSuchMethod (dart:core-patch/object_patch.dart:53)
Eval (Unknown Source:0)
new Rect.fromCircle (dart:ui/geometry.dart:0)
DefaultShaderWarmUp.warmUpOnCanvas (/opt/google/flutter/packages/flutter/lib/src/painting/shader_warm_up.dart:0)
ShaderWarmUp.execute (/opt/google/flutter/packages/flutter/lib/src/painting/shader_warm_up.dart:0)
PaintingBinding.initInstances (/opt/google/flutter/packages/flutter/lib/src/painting/binding.dart:0)
SemanticsBinding.initInstances (/opt/google/flutter/packages/flutter/lib/src/semantics/binding.dart:0)
RendererBinding.initInstances (/opt/google/flutter/packages/flutter/lib/src/rendering/binding.dart:0)
WidgetsBinding.initInstances (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
new BindingBase (/opt/google/flutter/packages/flutter/lib/src/foundation/binding.dart:0)
new _WidgetsFlutterBinding&BindingBase&GestureBinding (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
new WidgetsFlutterBinding (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
WidgetsFlutterBinding.ensureInitialized (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
runApp (/opt/google/flutter/packages/flutter/lib/src/widgets/binding.dart:0)
main (/Users/wanjm/git/plasoFlutter/ppad/lib/main.dart:31)
main (/Users/wanjm/git/plasoFlutter/ppad/lib/main.dart:0)
_Closure.call (dart:core-patch/function.dart:0)
_runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241)
_rootRun (dart:async/zone.dart:1184)
_rootRun (dart:async/zone.dart:0)
_CustomZone.run (dart:async/zone.dart:1077)
_runZoned (dart:async/zone.dart:1619)
runZonedGuarded (dart:async/zone.dart:1608)
_runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233)
_Closure.call (dart:core-patch/function.dart:0)
_startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301)
_Closure.call (dart:core-patch/function.dart:0)
_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)
```

the result of doctor -v is 
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /opt/google/flutter
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/google/android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/google/android/sdk
    • ANDROID_SDK_ROOT = /opt/google/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Lenovo TB 8705F • HA13B3X2 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

```

**Comment by iapicca** [comment] 2020-05-25 13:53
Hi @wanjm 
Can you please provide
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Thank you

**Comment by wanjm** [comment] 2020-05-28 11:33
it is reproduceable in vscode. how can i add --verbose in vscode;

**Comment by iapicca** [comment] 2020-05-29 07:07
Hi @wanjm 
If you are experiencing the issue only with VS Code,
then following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), 
the correct way to address the problem 
is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).

Otherwise, could you please run from terminal
```console
cd <your app folder>
flutter run --verbose
```
Thank you

**Comment by Ludonope** [comment] 2020-05-29 10:02
I got the same error in VSCode at launch for no apparent reason, cannot reproduce.

I have the `runApp` function.

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-FR)
    • Flutter version 1.17.1 at /Users/ludonope/Code/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ludonope/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • Pixel 3 XL • 896Y045YT • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by wanjm** [comment] 2020-05-29 14:12
is there any difference for vscode to start flutter. does it use "flutter run";  how to config --verbose in vscode.json;

though it happens in vscode, I think there is something wrong with flutter as vscode is just a editor;

**Comment by iapicca** [comment] 2020-05-29 14:23
HI @wanjm 
to make sure that the problem is with flutter
is useful to know if the problem reproduces using terminal,
could you please follow the steps [above](https://github.com/flutter/flutter/issues/57943#issuecomment-635801495)?
Thank you

**Comment by wanjm** [comment] 2020-05-30 15:18
i don't think it is a bug of vscode, maybe vscode environment makes the bug more repeatable; 

any way I can't reprocude it by "flutter run"

**Comment by iapicca** [comment] 2020-06-01 06:20
Hi again @wanjm 
the issue is not workable without a reproducible code sample
could you please provide the information listed [above](https://github.com/flutter/flutter/issues/57943#issuecomment-633583942)
Thank you

**Comment by wanjm** [comment] 2020-06-02 00:39
here is the verbose log, hope it will helps;
[verbose.txt](https://github.com/flutter/flutter/files/4714113/verbose.txt)

**Comment by TahaTesser** [comment] 2020-06-02 08:09
Hi @wanjm 
Looking at logs, there is no `NoSuchMethodError` error in your logs
Can you please upgrade to `1.17.2` and try with updated vs code flutter plugin `3.11.0`?
Thank you

**Comment by wanjm** [comment] 2020-06-03 00:31
the verbose is got under flutter 1.17.2 and flutter plugin 3.11.0

**Comment by iapicca** [comment] 2020-06-03 07:13
Hi @wanjm 
as your logs show the issue does not occur running your flutter app from terminal,
if the issue was with flutter itself it would have shown;
please follow the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) and open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-03 07:13 UTC
Labels: in triage

**Comment by wanjm** [comment] 2020-06-07 13:44
@iapicca  I found the reason why only vscode will come across this, beacuse I checked the break point at all exception (both cached and uncached );  
then the problem is when run in vscode, there will be more such exceptions, but not always;

so there must be something happened though it is cached;
