### ISSUE TITLE
Backward compatibility issue with plugins (v1) while using GeneratedPluginRegistrant in io.flutter.embedding.android.FlutterActivity

### ISSUE THREAD

**Issue by fiFoFy** [flutter/flutter#50484] opened 2020-02-10 18:37 UTC
After updating Flutter from version v1.14.5 (master) to version v1.14.6 (and higher), the application crashes with an error:

```
Unable to start activity ComponentInfo{***.FlutterEmbeddedActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference java.lang.RuntimeException: Unable to start activity ComponentInfo{***.FlutterEmbeddedActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
	at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:118)
	…

```

I am working on hybryd application. There is a class FlutterEmbeddedActivity extended from io.flutter.embedding.android.FlutterActivity. In overrided method configureFlutterEngine(flutterEngine: FlutterEngine) I call GeneratedPluginRegistrant.registerWith method and pass there FlutterEngine, because I need to use plugins. In my flutter module there are some plugins (v1) where the error comes up. So that I can see such warnings:

```
The plugin `audioplayers` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
The plugin `device_apps` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
The plugin `devicelocale` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
The plugin `sqflite` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

```

**Expected results:** 

The ability to use plugins v1 with io.flutter.embedding.android.FlutterActivity

**Actual results:** 

Crash apps when using plugins v1

**Comment by iapicca** [comment] 2020-02-11 07:14
HI @fiFoFy 
following the [link](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration) provided in you error logs we can find the statement

> As of the 1.12 release, new plugin APIs are available for the Android platform. The old APIs based on PluginRegistry.Registrar won’t be immediately deprecated, but we encourage you to migrate to the new APIs based on FlutterPlugin.

my interpretation is that v1 won't be deprecated as for stable `1.12`,
but does hint at a consecutive deprecation, 
therefore there won't be any backward compatibility.

I'm not sure that the line is drawn at the exact version you are using,
which I assume is the latest beta, I'd like to keep this issue open as reference.

About your specific case, according with the information currently available,
I'd recommend to either migrate to `v2` following the link above
or, if it is suitable in your context, use the latest stable or the previous beta.

Thank you

**Comment by fiFoFy** [comment] 2020-02-12 17:21
Hi @iapicca , thank you for your reply)

The point is that those plugins weren't developed by me (some third-party plugins which are crucial to my app at the moment), so I cannot migrate any of those to a new version and I don't know when corresponding developers will do so if ever will.

Given that, it's quite odd that Flutter does not provide any backward compatibility for v1 plugins since many users may potentially rely on such third-party products and are susceptible for unpleasant situations like mine.

I know that master branch is not stable and is not recommened for production environments but I need some new features and there must be a way to use v1 plugins under Flutter ≥1.14.6
I suspect that this kind of backward compatibility was violated unintentionally and I worry if this comes into new stable release of Flutter.

**Comment by xster** [comment] 2020-02-14 03:06
Can you confirm that the issue was not present in 1.12 and 1.14.5 but in 1.14.6? Conceptually, I would have suspected that the problem occurs in all those versions or none of those versions. 

Also, could you paste the rest of the crash stack trace? The real info actually starts right you cut off :D

For general context, we did build in backward compatibility for v1 plugins into io.flutter.embedding.android.FlutterActivity. But only for existing scenarios that existed before 1.12, that is, a full-Flutter app. Add-to-app is a newly supported scenario and while we attempt to bridge the APIs via a backward compatibility layer, the v1 plugin APIs offered abilities that could only be true in full-Flutter. e.g. always be able to retrieve a FlutterView. If a plugin depended on that ability, there's unfortunately no way to automatically convert since in add-to-app, there's frequently no FlutterView. 

Though your report specifically says that 1.14.5 works, which is very curious. Maybe something else is going on.

**Comment by amreniouinnovent** [comment] 2020-05-07 10:59
I wonder if this issue is related
My Parent app has a flutter code to install APK  on root devices
I have in the parent app
```
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

```
So after upgrading to Flutter 1.17 stable, I got null for any library I have in Pubspec that using V1
I tried to fix it to one of my libraries and it works but got for other libraries
Check my fix
I added V2 support  check onAttachedToEngine on my commit
https://github.com/amorenew/ACS_NFC_Flutter/commit/9b9385cec465005a6a2a6ed2591303d563148210
**I can't force all libraries to support V2 if my app has V2 in manifest**

**Comment by darshankawar** [comment] 2020-12-03 12:00
@fiFoFy 
Is this still a valid issue using latest Flutter version or has this been resolved ?
If issue persists, can you provide a reproducible code sample ?
Thanks.

**Comment by pedromassangocode** [comment] 2021-01-06 12:15
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-06 12:15 UTC
Labels: P4, a: existing-apps, engine, p: framework, p: tooling, platform-android, plugin, waiting for customer response
