### ISSUE TITLE
[image-picker] Wrong file format if choosing video from Google Photos

### ISSUE THREAD

**Issue by bytepoets-tka** [flutter/flutter#42315] opened 2019-10-09 08:48 UTC
If using `ImagePicker.pickVideo(ImageSource.gallery)` to pick a video from gallery, a path with .jpg is returned if Google Photos is used (even though the file is .mp4)

The issue can easily be reproduced with the image-picker example project - the video can be played, but the returned path has a wrong extension.

There was a fix for invalid paths from Goolge Photos (https://github.com/flutter/plugins/commit/9023ff2845aa43e0568b4a00d7c242506eae57e3) - but what is the purpose of returning always null?

If the complete check for `isGooglePhotosUri(uri)` is removed and the path is returned with `getDataColumn(context, uri, null, null);` everything seems to work as expected.

**Comment by VladyslavBondarenko** [comment] 2020-03-17 12:39
My be related to https://github.com/flutter/flutter/issues/47719

**Comment by candyd8** [comment] 2020-05-14 19:36
Is there a workaround for this? I need the path to upload to my video hosting site (Publitio, using flutter_publitio package).

**Comment by lzzy12** [comment] 2020-05-15 11:34
Same problem here. Even if I pick a local image, it just changes the format to mp4. I am trying to upload the video with the firebase storage

**Comment by lzzy12** [comment] 2020-05-15 11:50
@candyd8 Was able to fix this by downgrading the library version to 0.6.2

**Comment by candyd8** [comment] 2020-05-19 16:21
> @candyd8 Was able to fix this by downgrading the library version to 0.6.2

Thank you ! This worked for me.

**Comment by duongtruong12** [comment] 2020-05-20 07:35
i have changed to 0.6.2 but still not working

**Comment by lzzy12** [comment] 2020-05-20 07:39
> i have changed to 0.6.2 but still not working, do you guys have any ideal?

Make sure you don't have a ^ character before the version number.
image_picker: 0.6.2

**Comment by sebasobotka** [comment] 2020-05-27 20:00
> Same problem here. Even if I pick a local video file, it just changes the format to jpg. I am trying to upload the video to firebase storage

I've got exactly the same issue.

**Comment by Maus3rSR** [comment] 2020-05-29 19:03
Same here with  the latest version.

**Comment by SpinnerOfYarns** [comment] 2020-05-30 15:33
Solved the same issue on 0.6.6 by downgrading to 0.6.2

**Comment by najafsklptor** [comment] 2020-05-31 08:21
> > i have changed to 0.6.2 but still not working, do you guys have any ideal?
> 
> Make sure you don't have a `^` character before the version number. It should look like this:
> 
> `image_picker: 0.6.2`

I have downgraded my package, yet it still doesn't work :(

**Comment by lzzy12** [comment] 2020-05-31 11:20
v0.6.6 of this plugin is nearly useless. Didn't expect something horrible like this happening in a library maintained by Google. Do they even have tests for this plugin? Because I don't think it's possible to miss something as severe as this and completely breaking the library and even releasing a new version with that bug

**Comment by gajendrabhati** [comment] 2020-06-03 16:17
> > i have changed to 0.6.2 but still not working, do you guys have any ideal?
> 
> Make sure you don't have a `^` character before the version number. It should look like this:
> 
> `image_picker: 0.6.2`

thank you sir its working for me.

**Comment by gajendrabhati** [comment] 2020-06-03 16:20
> > > i have changed to 0.6.2 but still not working, do you guys have any ideal?
> > 
> > 
> > Make sure you don't have a `^` character before the version number. It should look like this:
> > `image_picker: 0.6.2`
> 
> thank you sir its working for me.

after this delete .package file, clean the project and then get packages and then run.
 its work

**Comment by pedromassangocode** [comment] 2021-02-10 14:48
This seems to be a duplicate of https://github.com/flutter/flutter/issues/52419. I~m closing this one since https://github.com/flutter/flutter/issues/52419 has more activity and has some linked PRs. For anyone interested in this, please follow up on https://github.com/flutter/flutter/issues/52419.
Thank you

**Closed by pedromassangocode** 2021-02-10 14:48 UTC
Labels: p: image_picker, plugin, severe: regression
