### ISSUE TITLE
Flutter Plugin for integrating Google Maps

### ISSUE THREAD

**Issue by serahzaveri** [flutter/flutter#62358] opened 2020-07-27 20:45 UTC
[console_output.txt](https://github.com/flutter/flutter/files/5027055/console_output.txt)

Plugin title: google_maps_flutter 0.5.28+1
@kf6gpe 

For iOS documentation in this flutter plugin, an error is produced during build reading unable to read property list from file Info.plist.
This is due to the boolean value added along with key io.flutter.embedded_views_preview in Info.plist. This isn't compatible with the latest version of Xcode. 
However, this can be fixed by changing the boolean value. 
Instead of <boolean> Yes </boolean> one should change it to true/.

Minimal reproduction example: https://github.com/serahzaveri/flutter_googlemaps_plugIn

**Comment by kf6gpe** [comment] 2020-07-27 23:10
@jmagman Is this something in our template, or something the plugin brings in?

cc @cyanglaz

**Comment by jmagman** [comment] 2020-07-27 23:48
@serahzaveri 
1. How exactly are you seeing this error?  Can we get minimal reproduction steps?
1. Can we get the exact error, logs, etc?
1. Attach the Info.plist that is giving you that error.

Xcode's UI sometimes shows `YES` and sometimes shows `1`, but the underlying plist xml should be `<true/>`.

**Comment by cyanglaz** [comment] 2020-07-28 16:59
@kf6gpe 
`io.flutter.embedded_views_preview` needs to be set by the app. The google_maps_flutter plugin has an instruction in the README about setting this up: https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/README.md

In the README, we mentioned to set the value to `YES`. I think it is confusing, especially for people who are not familiar with iOS's plist format.

We should update the README in the google_map_flutter plugin to give an example of the info.plist.

**Comment by jmagman** [comment] 2020-07-28 17:58
> Xcode's UI sometimes shows `YES` and sometimes shows `1`, but the underlying plist xml should be `<true/>`.

<img width="213" alt="Screen Shot 2020-07-28 at 10 55 16 AM" src="https://user-images.githubusercontent.com/682784/88702894-d986a680-d0c0-11ea-8cb6-bac63179095a.png">

People can edit this in another text editor without Xcode if they want, an example sounds fine?
Anyway I think this is a documentation issue (maybe we can just link to https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/PropertyList.html which says it's retired but I don't see another doc describing the boolean XML element should look like), not a bug related to the newest version of Xcode.

**Comment by serahzaveri** [comment] 2020-08-05 08:27
I created the minimal reproduction example and the link to the github has been added to the post along with the console output. You can find the Info.plist in the github project. Before running project add the Google Maps API key in AndroidManifest.xml and AppDelegate.swift.  

According to the data documentation for iOS  to integrate the flutter plugIn it says to add boolean YES to Info.plist. This is what causes the error. Once we change <boolean> YES </boolean> to true/ the error disappears. This boolean instruction is confusing for people not familiar with iOS's plist format such as myself. 

I apologize for the late reply since I had a project due. 
Do let me know if you need anything else.

**Comment by markusaksli-nc** [comment] 2020-10-06 06:24
Closing since this is no longer relevant as of 1.0

> Bump the minimal Flutter SDK to 1.22 where platform views are out of developer preview and performing better on iOS. Flutter 1.22 no longer requires adding the `io.flutter.embedded_views_preview` to `Info.plist` in iOS.

**Closed by markusaksli-nc** 2020-10-06 06:24 UTC
Labels: P3, documentation, has reproducible steps, p: maps, plugin
