### ISSUE TITLE
[SelectionArea] Tooltip disappears if you click "Select All"

### ISSUE THREAD

**Issue by heeyunlee** [flutter/flutter#116128] opened 2022-11-28 19:06 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample  on an Android device
2. Select a text to expose the "Select All" tooltip option
3. Press the "Select All" tooltip 
4. Look for tooltips again by scrolling up/down

**Expected results:** 

Tooltip is visible

**Actual results:** 

Tooltip is not visible

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    HapticFeedback.lightImpact();
    return Scaffold(
      appBar: AppBar(title: const Text('SelectionArea')),
      body: const SelectionArea(
        child: SingleChildScrollView(
          child: Text(
            '''
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque ornare aenean euismod elementum nisi quis. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Facilisis gravida neque convallis a cras semper auctor neque vitae. Nulla aliquet enim tortor at. Suscipit adipiscing bibendum est ultricies. Quis viverra nibh cras pulvinar. Elit ut aliquam purus sit. Sit amet nisl purus in mollis nunc sed. Leo a diam sollicitudin tempor id eu nisl nunc mi. Donec pretium vulputate sapien nec. Lacus vel facilisis volutpat est velit egestas dui id. Nibh nisl condimentum id venenatis. Velit dignissim sodales ut eu sem integer vitae. Sed pulvinar proin gravida hendrerit lectus. Pellentesque pulvinar pellentesque habitant morbi. Purus in massa tempor nec feugiat nisl. Commodo ullamcorper a lacus vestibulum sed arcu. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Aliquet lectus proin nibh nisl.
        
        Integer feugiat scelerisque varius morbi enim nunc faucibus. Feugiat in fermentum posuere urna. Nam libero justo laoreet sit amet cursus sit. Diam in arcu cursus euismod quis viverra nibh. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Elit at imperdiet dui accumsan. Sodales ut eu sem integer vitae. A arcu cursus vitae congue mauris. Sagittis orci a scelerisque purus semper eget duis. Morbi enim nunc faucibus a pellentesque sit amet porttitor eget. Enim nec dui nunc mattis enim ut tellus elementum sagittis. Euismod nisi porta lorem mollis aliquam ut porttitor. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Nunc vel risus commodo viverra maecenas accumsan. Faucibus nisl tincidunt eget nullam non nisi est sit. Pretium vulputate sapien nec sagittis.
        
        Volutpat maecenas volutpat blandit aliquam etiam erat. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Et leo duis ut diam quam nulla. Tristique et egestas quis ipsum suspendisse. Cursus euismod quis viverra nibh. Tincidunt id aliquet risus feugiat in ante metus dictum. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Purus sit amet luctus venenatis lectus magna. Sed viverra ipsum nunc aliquet. Mattis nunc sed blandit libero. Dignissim enim sit amet venenatis urna cursus eget nunc.
        
        Erat imperdiet sed euismod nisi porta lorem. Dolor magna eget est lorem ipsum dolor sit. Augue ut lectus arcu bibendum at varius vel pharetra. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Quam pellentesque nec nam aliquam sem et tortor consequat id. Vehicula ipsum a arcu cursus. Tortor aliquam nulla facilisi cras fermentum odio. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Cras pulvinar mattis nunc sed blandit. Diam phasellus vestibulum lorem sed risus ultricies tristique. Sagittis orci a scelerisque purus semper eget duis at.
        
        Lectus vestibulum mattis ullamcorper velit sed. Quis vel eros donec ac odio. Eget sit amet tellus cras adipiscing. Tellus at urna condimentum mattis. Ullamcorper a lacus vestibulum sed arcu non. Scelerisque fermentum dui faucibus in ornare. Luctus venenatis lectus magna fringilla urna porttitor. Elementum nibh tellus molestie nunc non. Nec dui nunc mattis enim. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus.
        ''',
            style: TextStyle(fontSize: 24),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-arm, locale en-US)
    • Flutter version 3.3.9 on channel stable at /Users/heeyunlee/fvm/versions/3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (6 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/heeyunlee/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • Pixel 4a (mobile)           • 0A301JEC212254 • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554  • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos          • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)                • chrome         • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/32585133/204359046-46d9e30d-c040-43b2-9b69-51bc8536230c.mov

**Comment by exaby73** [comment] 2022-11-29 09:29
## Triage report

I can reproduce this issue with any amount of text on `Master (3.6.0-10.0.pre.13)`. Long pressing on the selected text again, shows the tooltip.

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    HapticFeedback.lightImpact();
    return Scaffold(
      appBar: AppBar(title: const Text('SelectionArea')),
      body: const SelectionArea(
        child: Center(
          child: Text(
            'Lorem ipsum dolor sit amet',
            style: TextStyle(fontSize: 24),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/50555895/204491238-b0b60a27-6527-484a-8921-f9237c01ad01.mp4

</details>

**Comment by goderbauer** [comment] 2022-11-29 23:25
@chunhtai

**Comment by Renzo-Olivares** [comment] 2023-06-14 19:45
Closing as duplicate of #120080 which was has been fixed. More context here https://github.com/flutter/flutter/issues/120080#issuecomment-1575428520 . If the issue has not been fixed feel free to re-open.

**Closed by Renzo-Olivares** 2023-06-14 19:45 UTC
Labels: framework, has reproducible steps, P4, f: selection, found in release: 3.3, customer: flex, found in release: 3.6
