### ISSUE TITLE
Failed to build iOS app because of strange XLinker error after upgrading to XCode 15

### ISSUE THREAD

**Issue by woutervanwijk** [flutter/flutter#137250] opened 2023-10-25 13:29 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1 Upgrade to XCode 15
2 See your previously working flutter project fail to run in VS Code or 'flutter run', because of an XLinker error
3 Try to run it in XCode -> It works!

I think it's something to do with M1 vs Intel and maybe cocoapods. Maybe similar to https://github.com/flutter/flutter/issues/124442

### Expected results

A running project

### Actual results

```
Launching lib/main.dart on iPhone 15 in debug mode...
Running pod install...                                           1,952ms
Running Xcode build...                                                  
Xcode build done.                                            9.1s
Failed to build iOS app
Error (Xcode): Unknown option: -Xlinker


Could not build the application for the simulator.
Error launching application on iPhone 15.
```

### Code sample

<details><summary>Code sample</summary>

```dart
cannot share my code, it's a big project
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone 15 in debug mode...
Running pod install...                                           1,952ms
Running Xcode build...                                                  
Xcode build done.                                            9.1s
Failed to build iOS app
Error (Xcode): Unknown option: -Xlinker


Could not build the application for the simulator.
Error launching application on iPhone 15.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-FR)
    • Flutter version 3.13.8 on channel stable at /Users/wouter/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (7 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/wouter/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /Users/wouter/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPhone 15 (mobile) • XXXXXX • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 118.0.5993.117
    ! Error: Browsing on the local area network for XX. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-10-26 05:37
Hi @woutervanwijk 
Could you check [this](https://github.com/flutter/flutter/issues/124442#issuecomment-1530954679) and documentation url inside to see if it helps you to solve this?

**Comment by aiproff** [comment] 2023-10-30 12:13
i am facing the same issue.
i am having 2.3 GHz Dual-Core Intel Core i5 macbook with macOs Ventura 13.6 .
the following is the flutter doctor -v logs.
`[✓] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-x64, locale
    en-IN)
    • Flutter version 3.13.7 on channel stable at
      /Users/nitinsaraswat/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (3 weeks ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nitinsaraswat/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.28.1)
    • VS Code at /Users/nitinsaraswat/Applications/Visual Studio
      Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • 1CF59B04-70B6-48F3-95AB-EC6C0936AA6A • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 13.6 22G120 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!`
the following is the error log
`Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running Xcode build...
Xcode build done.                                           22.2s
Failed to build iOS app
Error (Xcode): Unknown option: -Xlinker

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.`

the app works fine on running from xcode.
i am using xcode 15.0

**Comment by woutervanwijk** [comment] 2023-10-30 15:07
> Hi @woutervanwijk Could you check [this](https://github.com/flutter/flutter/issues/124442#issuecomment-1530954679) and documentation url inside to see if it helps you to solve this?

I tried everything. Reinstall XCode, flutter, all updates, etc. It's just not working

**Comment by woutervanwijk** [comment] 2023-10-30 15:13
> i am facing the same issue. i am having 2.3 GHz Dual-Core Intel Core i5 macbook with macOs Ventura 13.6 . the following is the flutter doctor -v logs.
> Details
> 
> the following is the error log `Launching lib/main.dart on iPhone 15 Pro in debug mode... Running Xcode build... Xcode build done. 22.2s Failed to build iOS app Error (Xcode): Unknown option: -Xlinker
> 
> Could not build the application for the simulator. Error launching application on iPhone 15 Pro.`
> 
> the app works fine on running from xcode. i am using xcode 15.0
> Podfile
> 
> Also tried upgrading flutter to latest stable version 3.13.9 still the issue persists Also, commenting and uncommenting the "use_frameworks!" line does not help.

So that rules out Rosetta. 

Which plugins do you use?

I use these in my project (ones with probable system-api-interaction):

  cached_network_image
  connectivity_plus
  desktop_window
  device_info_plus
  firebase
  firebase_analytics
  firebase_auth
  firebase_crashlytics
  firebase_dynamic_links
  flutter_custom_tabs
  flutter_device_type
  flutter_inappwebview
  flutter_phoenix
  graphql_flutter
  package_info_plus
  rate_my_app
  receive_sharing_intent
  shared_preferences
  universal_io
  universal_platform
  url_launcher
  wc_flutter_share

**Comment by aiproff** [comment] 2023-10-30 15:28
> > i am facing the same issue. i am having 2.3 GHz Dual-Core Intel Core i5 macbook with macOs Ventura 13.6 . the following is the flutter doctor -v logs.
> > Details
> > the following is the error log `Launching lib/main.dart on iPhone 15 Pro in debug mode... Running Xcode build... Xcode build done. 22.2s Failed to build iOS app Error (Xcode): Unknown option: -Xlinker
> > Could not build the application for the simulator. Error launching application on iPhone 15 Pro.`
> > the app works fine on running from xcode. i am using xcode 15.0
> > Podfile
> > Also tried upgrading flutter to latest stable version 3.13.9 still the issue persists Also, commenting and uncommenting the "use_frameworks!" line does not help.
> 
> So that rules out Rosetta.
> 
> Which plugins do you use?
> 
> I use these in my project (ones with probable system-api-interaction):
> 
> ```
>   cached_network_image
>   connectivity_plus
>   desktop_window
>   device_info_plus
>   firebase
>   firebase_analytics
>   firebase_auth
>   firebase_crashlytics
>   firebase_dynamic_links
>   flutter_custom_tabs
>   flutter_device_type
>   flutter_inappwebview
>   flutter_phoenix
>   graphql_flutter
>   package_info_plus
>   rate_my_app
>   receive_sharing_intent
>   shared_preferences
>   universal_io
>   universal_platform
>   url_launcher
>   wc_flutter_share
> ```
> 
> Podfile:
> 
> ```
> # Uncomment this line to define a global platform for your project
> platform :ios, '12.0'
> 
> # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
> ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> 
> project 'Runner', {
>   'Debug' => :debug,
>   'Profile' => :release,
>   'Release' => :release,
> }
> 
> def flutter_root
>   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
>   unless File.exist?(generated_xcode_build_settings_path)
>     raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
>   end
> 
>   File.foreach(generated_xcode_build_settings_path) do |line|
>     matches = line.match(/FLUTTER_ROOT\=(.*)/)
>     return matches[1].strip if matches
>   end
>   raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
> end
> 
> require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
> 
> flutter_ios_podfile_setup
> 
> target 'Runner' do
>   use_frameworks!
>   use_modular_headers!
> 
>   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
>     end
>   end
> end
> ```

I am facing this issue in Flutter Sample Counter app. 
not using any dependencies

**Comment by aiproff** [comment] 2023-10-30 17:20
> > @woutervanwijk
> > i am facing this issue in Flutter Sample Counter app. not using any dependencies.
> 
> I don't get it in the sample app

i think this is something related to xcode 15

**Comment by huycozy** [comment] 2023-10-31 05:34
@woutervanwijk Based on your Podfile and the issue only occurs on your project, it seems one or more plugin is not compatible with your IPHONEOS_DEPLOYMENT_TARGET in Podfile. I would suggest you double-check plugin changelog to see if you can find the cause.

@aiproff Can you share your minimal sample code here? I'm using Mac Intel so I can check this on my end.

**Comment by aiproff** [comment] 2023-10-31 08:03
@huycozy 
<details><summary>Main.dart file</summary>
<p>
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
</p>
</details> 
this is the only dart file this project have (sample flutter counter app).
I am using iphone 15 pro ios 17.0 simulator.

<details><summary>Podfile.lock</summary>
<p>
PODFILE CHECKSUM: e4cb2d021109b693457f404198e5d63a09168fc3

COCOAPODS: 1.13.0

</p>
</details>

**Comment by huycozy** [comment] 2023-10-31 14:47
@aiproff It would be helpful if you could share the entire sample project as the issue may come from project settings, I think.

**Comment by aiproff** [comment] 2023-10-31 16:39
> @aiproff It would be helpful if you could share the entire sample project as the issue may come from project settings, I think.
[here's the link to whole project](https://drive.google.com/file/d/1jGG5a4m6LqYw3dAin_7zWmIp2znbfs76/view?usp=sharing)

**Comment by usmanIITR** [comment] 2023-11-02 18:12
@huycozy is there any update ?

**Comment by huycozy** [comment] 2023-11-03 03:25
The provided sample project of @aiproff can run normally on my end. I'm guessing this is related to local PATH as mentioned at https://github.com/flutter/flutter/issues/137391#issuecomment-1791285325. Please try to provide the same things here that may be helpful. 

Meanwhile, I'm going to label this issue for other's input.

**Comment by aiproff** [comment] 2023-11-03 17:32
which ld
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld`

echo PATH
`/Users/nitinsaraswat/.gem/bin:/usr/local/opt/llvm/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Users/nitinsaraswat/.rbenv/bin:/usr/local/opt/openjdk/bin:/usr/local/mysql/bin:/usr/local/Cellar/hive/3.1.2/bin:/Users/nitinsaraswat/anaconda3/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin::/Users/nitinsaraswat/Documents/flutter/bin:/Users/nitinsaraswat/.pub-cache/bin:/Users/nitinsaraswat/.rvm/bin`

**Comment by jmagman** [comment] 2023-12-19 20:12
This isn't actionable without verbose logs.

@woutervanwijk or someone else hitting this issue please run `flutter clean` and then attach the output of `flutter build ios --verbose`?  Thanks!

**Comment by aiproff** [comment] 2023-12-20 13:23
@jmagman 
here is the result of the command flutter build ios --verbose .

[logs.txt](https://github.com/flutter/flutter/files/13727826/logs.txt)

**Comment by jmagman** [comment] 2023-12-20 17:01
@aiproff your error is:
> [    +36 ms] Failed to build iOS app
[      +3 ms] Error (Xcode): No profiles for 'com.aiproff.expefy' were found: Xcode couldn't find any iOS App Development provisioning profiles matching
'com.aiproff.expefy'.
                      Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
                      /Users/nitinsaraswat/StudioProjects/expefy/ios/Runner.xcodeproj
                      
[      +3 ms] It appears that there was a problem signing your application prior to installation on the device.
[                ] Verify that the Bundle Identifier in your project is your signing id in Xcode
[                ]      open ios/Runner.xcworkspace
[                ] Also try selecting 'Product > Build' to fix the problem.

That's different than the reported issue:
> Error (Xcode): Unknown option: -Xlinker

You should be able to fix it based on the instructions, but if that doesn't work, please file a new issue.

**Comment by aiproff** [comment] 2024-01-03 14:10
This is the result of flutter run --verbose / flutter build ios --verbose 

`[   +4 ms] Error (Xcode): Unknown option: -Xlinker
           
[   +9 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 15 Pro.
[  +10 ms] "flutter run" took 78,228ms.
[  +11 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:752:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
`

**Comment by jmagman** [comment] 2024-01-03 19:29
I need the entire output, not the end.  You may have to attach it, it's large.

**Comment by aiproff** [comment] 2024-01-04 05:06
[logss.txt](https://github.com/flutter/flutter/files/13826468/logss.txt)

here is the output of 'flutter build ios --verbose > logss.txt'

**Comment by jmagman** [comment] 2024-01-04 21:46
Similar to https://github.com/flutter/flutter/issues/137391#issuecomment-1863408161, this is an environment issue.  That is a _clang_ flag, not a linker flag, but it's being passed to `ld`:

```
/Users/nitinsaraswat/anaconda3/bin/x86_64-apple-darwin13.4.0-ld
```
You probably have some weird toolchain export conda thing going on.  If you deactive conda does it reproduce?  You can try creating a new Xcode project without Flutter, run `xcodebuild`, and see if it builds to validate your environment.

Same question to you @woutervanwijk do you have conda on?  Or nix? Or something else polluting your environment?

**Comment by aiproff** [comment] 2024-01-07 18:46
@jmagman 
I opened my terminal and ran 'conda deactivate'.
Then, in android studio terminal again i ran 'conda deactivate' and the 'flutter run'.

so this time the build was successful (and took more time) but the app crashed after installing (didn't opened).
on clicking the app icon, it's crashing.
when i ran the app from android studio 'play'. button then this time it gives the following error -> 

<details>
<summary>Error</summary>
Running Xcode build...
Xcode build done.                                           36.8s
Failed to build iOS app
Error (Xcode): Unknown option: -Xlinker

Uncategorized (Xcode): Command SwiftEmitModule failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.
</details>

**Comment by woutervanwijk** [comment] 2024-01-07 18:49
> Similar to [#137391 (comment)](https://github.com/flutter/flutter/issues/137391#issuecomment-1863408161), this is an environment issue. That is a _clang_ flag, not a linker flag, but it's being passed to `ld`:
> 
> ```
> /Users/nitinsaraswat/anaconda3/bin/x86_64-apple-darwin13.4.0-ld
> ```
> 
> You probably have some weird toolchain export conda thing going on. If you deactive conda does it reproduce? You can try creating a new Xcode project without Flutter, run `xcodebuild`, and see if it builds to validate your environment.
> 
> Same question to you @woutervanwijk do you have conda on? Or nix? Or something else polluting your environment?

I had to reinstall my whole system, and the problem is gone. I had used Conda in my old system indeed. It must be something like that.

**Comment by jmagman** [comment] 2024-01-08 17:52
I'm going to close this, we've seen other issues where conda stomps on some toolchain exports Xcode relies on, that has nothing to do with Flutter except that Flutter invokes Xcode on the command line via `xcodebuild`.  If anyone sees this issue, try creating a new Xcode project, and from the commandline invoke `xcodebuild`.  If that doesn't work then there's no hope for your Flutter app to build from the command line and you need to resolve your environment issues.

**Closed by jmagman** 2024-01-08 17:52 UTC
Labels: platform-ios, tool, t: xcode, P2, needs repro info, team-ios, triaged-ios
