### ISSUE TITLE
Flutter Windows Backspace not working after pressing (shift, control, ...)

### ISSUE THREAD

**Issue by evan8133** [flutter/flutter#113915] opened 2022-10-23 14:49 UTC
Hello this my first time addressing and issue here sorry for being a noob, but im facing an issue with flutter windows i have a form with some TextFormField and when i want to get first letter capital by shift work fine but i get lots of error in the debug console and i cannot use my backspace or even control + A to select all or anything this is what im getting

**Comment by evan8133** [comment] 2022-10-23 14:51
══════════════ Exception caught by services library ══════════════════════════════════
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#6b3f4(physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left"), logicalKey: LogicalKeyboardKey#00100(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), character: null, timeStamp: 100:04:47.966852)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'
════════════════════════════════════════════════════════════════════════════════
Unable to parse JSON message:
The document is empty.

**Comment by 0x44449** [comment] 2022-10-24 09:46
I have same issue after Windows 11 update (version 22H2)

**Comment by exaby73** [comment] 2022-10-24 11:42
Hello @evan8133. This issue looks like a duplicate of https://github.com/flutter/flutter/issues/107972. Please retry on the master channel and check if the issue was fixed.

**Closed** 2022-11-14 12:11 UTC
Labels: waiting for customer response, in triage
