### ISSUE TITLE
Document how to use git submodules to pin Flutter dependency

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3770] opened 2016-05-06 15:49 UTC
I've seen some developers use git submodules.  Is that a recommended approach?

Once I write my large app, I want to control when the version of flutter changes, and I want it to be the same between all of my developers.

**Comment by sethladd** [comment] 2016-07-19 22:39
Would https://github.com/dart-lang/pub/issues/1432 be sufficient?

**Comment by eseidelGoogle** [comment] 2016-07-19 22:41
I think this ends up being more than just an sdk fix, since if I have two separate flutter projects, we need a clear story as how I configure Atom differently when working with them, or the flutter command line, etc.  Certainly pub support may be part of this, but we also just need a recommended story for Flutter too since so many of our tools are tied into the flutter version.

**Comment by sethladd** [comment] 2016-07-19 22:44
Yes, I'd love per-project SDK configurations in Atom. That would help a lot.

**Comment by Hixie** [comment] 2017-01-28 23:57
This seems to be a dupe of https://github.com/flutter/flutter/issues/3696, so I'm closing it as such. Please reopen if I misunderstood.

**Comment by eseidelGoogle** [comment] 2017-01-31 04:10
This is not the same issue.  This is the how-do-i-pin-the-version-of-flutter-my-app-depends-on question. :)  i.e. so that all of my 10 developers can get the same version of flutter instead of each of them having different flutter sdk versions depending when they last ran `flutter upgrade`.

**Comment by Hixie** [comment] 2017-01-31 04:29
Ah, I see. This is basically about giving the `flutter` tool a way to read your `pubspec.yaml` and follow the same semantics as we want `pub get` to use to determine what version of a package to bring in given a particular `environment` line. Almost the opposite of #3696 in fact.

**Comment by eseidelGoogle** [comment] 2017-01-31 04:36
I have no opinions as to the implementation details.  The user journey is that I have a team of N devs, and Flutter currently has no official releases.  What is the best way for my N devs to make sure we're all working from the same copy of the Flutter sdk.

**Comment by Hixie** [comment] 2017-01-31 05:17
As of today, one way to do it is to pick a flutter repo git hash, and have everyone check that out instead of top of tree.

**Comment by passsy** [comment] 2017-10-30 18:35
Just faced this error. We want to make sure CI and all devs use the same flutter version. I tried adding flutter as submodule but faced this error message:

[`Error: The Flutter directory is not a clone of the GitHub project.`](https://github.com/flutter/flutter/blob/master/bin/flutter.bat#L35)

**Comment by Hixie** [comment] 2017-11-02 18:36
Weird, do submodules not include `.git` directories?

**Comment by passsy** [comment] 2017-11-02 18:42
They use the parents `.git` directory and place content in `.git/modules/<submoduleName>/`

**Comment by amirh** [comment] 2017-11-07 18:11
+1 to make the flutter tool follow the same semantics of pub get for versioning.

I just bumped into this issue on a personal pet project -
1. Flutter tool nudged me to flutter upgrade.
2. I upgraded and pub failed to solve dependency constraints.

After digging into it I found out that the new flutter version had a new dependency on shelf (https://github.com/flutter/flutter/commit/441b5c2031733d0505b8dafdda54cd1ba9887617), which conflicted with my project's dependencies on the built_value toolchain (that required an earlier version of shelf).
My only way out was to change my built_value dependencies to latest (build, build_runner, built_value_generator), which included a breaking API change, so I had to figure out the new API and update my code.

**Comment by Hixie** [comment] 2017-11-09 00:26
Ah, right, I was thinking of `.svn` directories, which are per-folder.

We should just update the `flutter` tool to correctly handle submodules.

**Comment by paulcbetts** [comment] 2018-01-18 18:53
Hey all, with the fix I just PRed, you should be able to now do:

```sh
git submodule add https://github.com/flutter/flutter ./vendor/flutter
```

Then check in a wrapper for your vendored Flutter into your project:

```sh
#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PATH="$DIR/vendor/flutter/bin:$PATH"
exec flutter $@
```

So instead of `flutter doctor`, run `./flutterw doctor`, and you should have reliable builds, albeit slow in CI environments because flutter will have to redownload Dart et al every time.

**Comment by Hixie** [comment] 2018-01-18 18:56
@sethladd could you add something about this to the faq?

**Comment by sethladd** [comment] 2018-01-18 19:06
https://github.com/flutter/website/blob/master/faq.md will gladly accept PRs :)

In the meantime, we should reopen this or open a new issue for the FAQ entry so it doesn't get lost

**Comment by zoechi** [comment] 2018-12-03 18:10
Issue moved to [flutter/website #1845](https://github.com/flutter/website/issues/1845) via [**ZenHub**](https://www.zenhub.com/)

**Closed by zoechi** 2018-12-03 18:10 UTC
Labels: d: website - content
