### ISSUE TITLE
toolbarHeight from M3 specs not applied to AppBar

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#120086] opened 2023-02-06 15:26 UTC
#91605
It seems that the height of the AppBar in M3 is still 56.0, which matches M2, even though the default value is set to 64.0

**Comment by darshankawar** [comment] 2023-02-07 06:30
Closing this as duplicate of https://github.com/flutter/flutter/issues/117903. Please follow-up in that issue for further updates.

**Closed by darshankawar** 2023-02-07 06:30 UTC
Labels: in triage
