### ISSUE TITLE
[integration_test] interacting with native elements in integration_tests

### ISSUE THREAD

**Issue by Giuspepe** [flutter/flutter#83095] opened 2021-05-21 13:22 UTC
Hi 😊
I'm writing end-to-end integration tests and want to interact with a web view (https://pub.dev/packages/webview_flutter). I need to do this to test the login process of the app (authentication happens on a website shown by the web view). The web view does load and show the web page in my integration test, however I'm not able to interact with the web page in the web view. I need to be able to do this to properly test the login process flow though. How can I get this to work?

Another similar problem I have in integration tests is using native file pickers (through https://pub.dev/packages/file_picker). Is there a way to interact with these native elements in integration tests?

**Comment by TahaTesser** [comment] 2021-05-21 15:13
Hi @Giuspepe 
It seems it is currently not possible, see https://github.com/flutter/flutter/issues/34345, confirmed [here](https://github.com/flutter/flutter/issues/34345#issuecomment-830011199) 

Since `flutter_driver` is being under the [hood](https://github.com/flutter/flutter/issues/34345#issuecomment-830003115), closing as a duplicate of https://github.com/flutter/flutter/issues/34345

**Closed by TahaTesser** 2021-05-21 15:13 UTC
Labels: in triage
