### ISSUE TITLE
[iOS] There is an error when typing Korean using the Chunjiin(Korean 10 key) keyboard

### ISSUE THREAD

**Issue by fenryrr** [flutter/flutter#112369] opened 2022-09-26 08:34 UTC
Hi 

I found that Korean is typed unexpectedly when I use Chunjiin(Korean 10 key) keyboard
(When adding Korean keyboard, you can choose Standard or 10 Key)

Please refer to the video.

- When  typing `패브릭쇼파`
If you want to type `패브릭쇼파`, you type like below.
`ㅂㅍ` - `ㅂㅍ` - `ㅣ` - `.` - `ㅣ` - `ㅂㅍ` - `ㅡ` - `ㄴㄹ` - `ㅣ` - `ㄱㅋ` - `ㅅㅎ` - `.` - `.` - `ㅡ` - `ㅂㅍ` - `ㅂㅍ` - `ㅣ` - `.`

expected `패브릭쇼`,  actual `패브릭ㅅㅅ쇼`
expected `패브릭쇼파`,  actual `패브릭ㅅ파 `

https://user-images.githubusercontent.com/40018682/192226242-a232ba10-3828-4caa-9df8-bbfe56c342d3.MP4

- When typing `대형`
If I want to type `대형`, you type like below
`ㄷㅌ`- `ㅣ` - `.` - `ㅣ` - `ㅅㅎ` - `ㅅㅎ` - `.` - `.` - `ㅣ` - `ㅇㅁ`

expected `대형`,  actual `대ㅎㅎ형`

https://user-images.githubusercontent.com/40018682/192230591-8e1b6b4b-ec2a-4cc7-8a86-4c7f0eec60ca.MP4

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.5.1 21G83 darwin-arm, locale ko-KR)
    • Flutter version 3.3.2 on channel stable at /Users/taylor/fvm/versions/3.3.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (12 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/taylor/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (5 available)
    • Pixel 6 (mobile)           • 1A221FDF6003ZH                       • android-arm64 • Android 13 (API 33)
    • SM G991N (mobile)          • R3CT10F9NRX                          • android-arm64 • Android 12 (API 31)
    • iPhone 13 Pro Max (mobile) • 00008110-001929041E52801E            • ios           • iOS 16.0.2 20A380
    • iPhone 13 Pro (mobile)     • 5A6FE182-3CFF-4D68-9B43-5C9287E0A152 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64  • macOS 12.5.1 21G83 darwin-arm
    ! Error: iPhone 13 Pro Max is busy: Fetching debug symbols for iPhone 13 Pro Max. Xcode will continue when iPhone 13 Pro Max is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment] 2022-09-27 03:11
Hi @crunchynurungji, thanks for filing the issue.
But I'm not familiar with Korean language input. Could you please specify `Steps to reproduce`, `Expected result`, and `Actual result` in more detail so that we may verify this properly?

**Comment by tony-soft** [comment] 2022-10-05 12:18
I have the same issue.

**Comment by yunchiri** [comment] 2022-10-05 12:47
Same case
this Error also relate with backspace 

typing "이거" then  "이ㄱ거"


"이ㄱ거"

1 backspace  "이ㄱㄱ·"
2 backspace  "이ㄱ익" // error  I expect **"이ㄱㄱ"** but  **"·" -> "익"**
3 backspace "이ㄱ이"

**Comment by crunchynurungji** [comment] 2022-10-06 01:56
@huycozy 
I added detail about each video. Should I explain it in more detail?

**Comment by huycozy** [comment] 2022-10-06 06:50
@crunchynurungji thanks but what kind of `keyboardType` are you using? It's different than mine.

<details>
<summary>Demo</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/194233204-19da36b0-2e7c-47f1-804a-b3d59a2da09e.png">

</details>

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please try upgrading to the latest Flutter **stable**/**master** channel and retry to see if the issue is still reproducible.

**Comment by tony-soft** [comment] 2022-10-06 06:58
> @crunchynurungji thanks but what kind of `keyboardType` are you using? It's different than mine.
> 
> Demo
> Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please try upgrading to the latest Flutter **stable**/**master** channel and retry to see if the issue is still reproducible.

You can configure the keyboard settings in this order.

https://user-images.githubusercontent.com/70277412/194235039-765302a0-132c-4276-ae32-16e967e43a8b.mp4

**Comment by huycozy** [comment] 2022-10-06 17:18
@crunchynurungji @tony-soft thanks for providing a sample code and guiding me to set up the keyboard.
But it seems to have been fixed on the stable `3.3.4` and master `3.5.0` channels. Please see the demo. 

I only did the test with this case (I'm familiar with the keyboard, sorry).
>expected 대형, actual 대ㅎㅎ형

Please try running app again on the latest master channel and confirm if this issue is fixed. 
And please try all the remaining cases for sure (test with `backspace` key too).

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/194376506-54cc7ffe-cacd-4c70-be8c-6ff3b34327ad.mov

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (23 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-2.0.pre.14, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-2.0.pre.14 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 59d68e03ee (15 minutes ago), 2022-10-05 23:53:34 -0400
    • Engine revision 5f2daf05e0
    • Dart version 2.19.0 (build 2.19.0-273.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by YoungeuNNN** [comment] 2022-10-11 02:33
Hi, I found same issue in flutter project.
I've tested in 3.3.4 version and it occurs only in real device(not simulator) 
Please check this video again.

https://user-images.githubusercontent.com/33536656/194983671-a4f47f4f-9440-4f0f-8d8d-376fe1600737.mp4

**Comment by crunchynurungji** [comment] 2022-10-12 07:26
@huycozy 
error still occurs...

**Comment by huycozy** [comment] 2022-10-13 03:53
>I've tested in 3.3.4 version and it occurs only in real device(not simulator)

@YoungeuNNN Can you provide the device information that you've tested on? (model, iOS version). Is it the same as @crunchynurungji's device? (iPhone 13 Pro Max iOS 16.0.2).
The issue may only reproduce on specific device/iOS versions.

### Actual result (my device)
I tried testing with my physical device (iPhone 7, iOS 15.7), but can not replicate this issue on stable `3.3.4`:

<details>
<summary>Demo (iPhone 7, iOS 15.7)</summary>


https://user-images.githubusercontent.com/104349824/195494770-4efd7788-94d8-40b5-867b-8c9dc5df5127.MP4


</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (23 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-6.0.pre.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-6.0.pre.4 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6e5f95bc3c (15 minutes ago), 2022-10-10 22:57:32 -0400
    • Engine revision 593ae56f04
    • Dart version 2.19.0 (build 2.19.0-298.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Pixel 3a (mobile)      • 964AY0WL20                           • android-arm64  • Android 12 (API 32)
    • iPhone 14 Pro (mobile) • 7CB497D7-2159-4F84-BDBE-D79330FA1E48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by YoungeuNNN** [comment] 2022-10-13 08:00
@huycozy
I've tested on iPhone 11(iOS 16.0.3) and iPhone 11(iOS 15.7). (flutter ver 3.3.4)

It only occurs in iOS 16.x.x. 
 @crunchynurungji 's OS version also over 16.x.x  So It seems to happen depending on the iOS version.

**Comment by crunchynurungji** [comment] 2022-10-14 05:26
@huycozy 
it reproduced on Simulator (iPhone 13 Pro iOS 16.0)

https://user-images.githubusercontent.com/40018682/195768817-6dcbaf12-72c0-49c5-84ad-eeebdf7c4fd6.mp4

**Comment by huycozy** [comment] 2022-10-14 06:31
Thank you all for confirmation. I also can reproduce the issue on iPhone 14 Pro Max (iOS 16.0) on the latest `stable` and `master` channels. Labeling this issue for further investigation from the team.

The issue is happening:
- when using Chunjiin(Korean 10 key) keyboard.
- from iOS 16 onwards.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (23 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-6.0.pre.29, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-6.0.pre.29 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c738c8aa96 (6 hours ago), 2022-10-12 23:49:12 -0400
    • Engine revision 7638a1463b
    • Dart version 2.19.0 (build 2.19.0-307.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by yunchiri** [comment] 2022-10-31 13:37
is fixed?

**Comment by jiyeonjoy** [comment] 2022-11-01 01:40
same issue! please fix it!!!

**Comment by kohry** [comment] 2022-11-04 06:18
Thanks for working on this issue. Many users are complaining everyday (and more and more) about the keyboard issue.
This case is quite urgent, because the keyboard type is quite common one, and I can see many users are using external memo app for copy and paste.

**Comment by yoonk-ang** [comment] 2022-11-04 15:37
Thanks for your hard work on the maintenance of Flutter. The fix for this is needed for many Korean users since more than a month back since it was reported. Could we adjust the priority?

**Comment by jmagman** [comment] 2022-11-04 20:55
cc @LongCatIsLooong

**Comment by LongCatIsLooong** [comment] 2022-11-29 06:46
I tried implementing `UITextInput` with a backing `UITextView` and managed to reproduce the same behavior in a pure UIKit app (interestingly I wasn't able to repro https://github.com/flutter/flutter/issues/111494), so I guess it's UIKit. @jmagman could you help me with filing a radar? 

In the meantime I think the easiest workaround would be to change `FlutterTextInputView` from implementing `UITextInput` to extending `UITextView` so the keyboard switches to using the private `legacyInputDelegate` interface and avoid the problematic callpath.

<details>
<summary>swift code</summary>

```swift
import UIKit

class UITextInputView: UIView, UITextInput {
  let backingView: UITextView = UITextView()
  
  required init?(coder: NSCoder) {
    super.init(coder: coder)
    addSubview(backingView)
    backingView.translatesAutoresizingMaskIntoConstraints = false
    backingView.topAnchor.constraint(equalTo: safeAreaLayoutGuide.topAnchor).isActive = true
    backingView.bottomAnchor.constraint(equalTo: safeAreaLayoutGuide.bottomAnchor).isActive = true
    backingView.leadingAnchor.constraint(equalTo: safeAreaLayoutGuide.leadingAnchor).isActive = true
    backingView.trailingAnchor.constraint(equalTo: safeAreaLayoutGuide.trailingAnchor).isActive = true
    backingView.isUserInteractionEnabled = false
    backingView.font = .systemFont(ofSize: 32)
  }
  
  func text(in range: UITextRange) -> String? {
    backingView.text(in: range)
  }
  
  func replace(_ range: UITextRange, withText text: String) {
    backingView.replace(range, withText: text)
  }
    
  var selectedTextRange: UITextRange? {
    get { backingView.selectedTextRange }
    set { backingView.selectedTextRange = newValue }
  }
  
  var markedTextRange: UITextRange? {
    backingView.markedTextRange
  }
  
  var markedTextStyle: [NSAttributedString.Key : Any]? {
    get { backingView.markedTextStyle }
    set { backingView.markedTextStyle = newValue }
  }
    
  func setMarkedText(_ markedText: String?, selectedRange: NSRange) {
    backingView.setMarkedText(markedText, selectedRange: selectedRange)
  }
  
  func unmarkText() {
    backingView.unmarkText()
  }
  
  var beginningOfDocument: UITextPosition {
    backingView.beginningOfDocument
  }
  
  var endOfDocument: UITextPosition {
    backingView.endOfDocument
  }
  
  func textRange(from fromPosition: UITextPosition, to toPosition: UITextPosition) -> UITextRange? {
    backingView.textRange(from: fromPosition, to: toPosition)
  }
  
  func position(from position: UITextPosition, offset: Int) -> UITextPosition? {
    backingView.position(from: position, offset: offset)
  }
  
  func position(from position: UITextPosition, in direction: UITextLayoutDirection, offset: Int) -> UITextPosition? {
    backingView.position(from: position, in: direction, offset: offset)
  }
  
  func compare(_ position: UITextPosition, to other: UITextPosition) -> ComparisonResult {
    backingView.compare(position, to: other)
  }
  
  func offset(from: UITextPosition, to toPosition: UITextPosition) -> Int {
    backingView.offset(from: from, to: toPosition)
  }
  
  var textInputView: UIView { self }
  weak var inputDelegate: UITextInputDelegate?
  var tokenizer: UITextInputTokenizer { backingView.tokenizer }
  
  func position(within range: UITextRange, farthestIn direction: UITextLayoutDirection) -> UITextPosition? {
    backingView.position(within: range, farthestIn: direction)
  }
  
  func characterRange(byExtending position: UITextPosition, in direction: UITextLayoutDirection) -> UITextRange? {
    backingView.characterRange(byExtending: position, in: direction)
  }
  
  func baseWritingDirection(for position: UITextPosition, in direction: UITextStorageDirection) -> NSWritingDirection {
    backingView.baseWritingDirection(for: position, in: direction)
  }
  
  func setBaseWritingDirection(_ writingDirection: NSWritingDirection, for range: UITextRange) {
    backingView.setBaseWritingDirection(writingDirection, for: range)
  }
  
  func firstRect(for range: UITextRange) -> CGRect {
    backingView.firstRect(for: range)
  }
  
  func caretRect(for position: UITextPosition) -> CGRect {
    backingView.caretRect(for: position)
  }
  
  func selectionRects(for range: UITextRange) -> [UITextSelectionRect] {
    backingView.selectionRects(for: range)
  }
  
  func closestPosition(to point: CGPoint) -> UITextPosition? {
    backingView.closestPosition(to: point)
  }
  
  func closestPosition(to point: CGPoint, within range: UITextRange) -> UITextPosition? {
    backingView.closestPosition(to: point, within: range)
  }
  
  func characterRange(at point: CGPoint) -> UITextRange? {
    backingView.characterRange(at: point)
  }
}

extension UITextInputView: UIKeyInput {
  var hasText: Bool {
    backingView.hasText
  }
  
  func insertText(_ text: String) {
    backingView.insertText(text)
  }
  
  func deleteBackward() {
    backingView.deleteBackward()
  }
}

extension UITextInputView: UITextInputDelegate {
  func selectionWillChange(_ textInput: UITextInput?) {
    inputDelegate?.selectionWillChange(textInput)
  }
  
  func selectionDidChange(_ textInput: UITextInput?) {
    inputDelegate?.selectionDidChange(textInput)
  }
  
  func textWillChange(_ textInput: UITextInput?) {
    inputDelegate?.textWillChange(textInput)
  }
  
  func textDidChange(_ textInput: UITextInput?) {
    inputDelegate?.textDidChange(textInput)
  }
}

extension UITextInputView {
  override var canBecomeFocused: Bool { true }
  override var canBecomeFirstResponder: Bool { true }
  override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
    super.touchesBegan(touches, with: event)
    becomeFirstResponder()
  }
}

```
</details>


https://user-images.githubusercontent.com/31859944/204454059-b467269c-2794-4aba-9b4e-d6ec51f9fa26.mov

**Comment by yoonk-ang** [comment] 2022-12-16 14:41
It seems not happening on iOS 16.2. I was able to reproduce it on 16.1 but not on 16.2. As it's also not reproduced on iOS 15.x, this issue looks to fade away as people using iOS 16 upgrade to 16.2. Maybe we can just close this issue..? @fenryrr Could you help share how this issue looks like on your end using iOS 16.2?

https://user-images.githubusercontent.com/3837732/208121493-7187cb45-9b97-4251-b596-a6cbb98dd6a4.mov

**Comment by tony-soft** [comment] 2022-12-16 22:39
My flutter version is 3.3.10 and iOS version is 16.1.2
Still having this issue.


https://user-images.githubusercontent.com/70277412/208200455-f9e76367-e528-4732-a3bd-88bc830b5186.MP4

**Comment by fenryrr** [comment] 2022-12-19 00:46
I tried three cases as below 
1. iPhone 13 (physical, iOS 16.2)

https://user-images.githubusercontent.com/40018682/208328388-d9e6c918-52a6-4b91-ade2-6c653ba4c4e0.MP4


2. iPhone 13 Pro Max (physical, iOS 16.2)
3. iPhone 14 Pro Max (simulator, iOS 16.2)

https://user-images.githubusercontent.com/40018682/208328424-ee473711-f473-4aeb-b54d-e3f0d9cf8939.mp4



It only happened on simulator (case 3)

**Comment by andynvt** [comment] 2022-12-27 02:16
any updates?

**Comment by LongCatIsLooong** [comment] 2023-01-23 20:49
@fenryrr thanks for the info! I tried this on an iOS 16.3 device and couldn't reproduce the issue. So it seems for iOS 16.2+ the issue is simulator specific. Applying a workaround in flutter is highly risky (a large scale change that may introduce regressions) so I'll discard the attempted fix.

**Comment by tony-soft** [comment] 2023-01-24 02:40
My phone is an iPhone 11, and I've had this problem before. 
But now I don't have this issue. I'm using iOS version 16.2 and an OS update seems to have fixed this issue.

**Comment by justinmc** [comment] 2024-08-15 22:29
@LongCatIsLooong (from triage) can you check if this bug still exists on an iOS 18 simulator?

**Comment by LongCatIsLooong** [comment] 2024-08-16 04:39
No longer reproducible on iOS 18. Closing.

**Closed by LongCatIsLooong** 2024-08-16 04:39 UTC
Labels: a: text input, platform-ios, a: internationalization, e: OS-version specific, has reproducible steps, P3, found in release: 3.3, found in release: 3.5, team-ios, triaged-ios, fyi-text-input
