### ISSUE TITLE
Doing a network request on macOS without the entitlement should tell you how to add the entitlement

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#71384] opened 2020-11-30 00:25 UTC
Right now you just get an error message along the lines of "permission denied", but it doesn't say how to get the permissions.

**Comment by gspencergoog** [comment] 2021-02-05 19:05
(bug triage) This is a duplicate of #63716, we think.

**Closed by gspencergoog** 2021-02-05 19:05 UTC
Labels: P5, a: desktop, a: error message, a: first hour, a: quality, dependency: dart, passed first triage, platform-mac

**Comment by Hixie** [comment] 2021-02-05 19:13
haha i guess i just REALLY think this is a good idea! :-P
