### ISSUE TITLE
Japanese text is displayed in Chinese font

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#12576] opened 2017-10-17 05:35 UTC
## Steps to Reproduce

Japanese text is displayed in Chinese font on some Android models set to Japanese language. Models: Nexus 5 Android 6.0, AQUOS SERIE SHV34 Android 7.0

got:
![2017-10-17 12 29 02](https://user-images.githubusercontent.com/1098127/31646635-f071992a-b33d-11e7-9c41-2a66753fb3ae.png)

expect:
![2017-10-17 12 01 40](https://user-images.githubusercontent.com/1098127/31646627-e5b654e4-b33d-11e7-8880-0f30c38f59f3.png)

The text is "累令直刃漢".

Even if set `Locale` to `MaterialApp`, it has same problem.

```dart
void main() {
  runApp(new MaterialApp(
    locale: const Locale('ja', 'JP'),
    home: new Scaffold(
      appBar: new AppBar(
        title: const Text('Locale'),
      ),
      body: new Container(
        padding: const EdgeInsets.all(20.0),
        child: new Text('累令直刃漢'),
      ),
    ),
  ));
}
```

## Flutter doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale ja-JP, channel master)
    • Flutter at /Applications/flutter
    • Framework revision 51e4e9f9a5 (6 days ago), 2017-10-10 17:41:25 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.1)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34
```

**Comment by najeira** [comment] 2017-10-17 05:39
The following code is related to this behavior:
https://github.com/flutter/engine/blob/master/runtime/platform_impl.cc#L14
"en-US" is hard-coded.

I changed it to "ja-JP", texts are displayed in Japanese font.

I think it should refer to the language and locale of the device.

I searched for similar bugs in Chromium:

- https://bugs.chromium.org/p/chromium/issues/detail?id=403915
- https://bugs.chromium.org/p/chromium/issues/detail?id=422180
- https://bugs.chromium.org/p/chromium/issues/detail?id=433715
- https://bugs.chromium.org/p/chromium/issues/detail?id=413498

That links may be helpful.

**Comment by najeira** [comment] 2017-10-17 06:05
I think I found a solution, I will send a pull request.

**Comment by Hixie** [comment] 2017-10-17 22:52
We need to pass the locale along with the text direction when rendering text.

**Comment by Hixie** [comment] 2017-10-19 20:46
https://github.com/flutter/flutter/issues/12630 is the issue tracking the long-term fix for this.

**Comment by Hixie** [comment] 2017-12-02 01:47
I'm going to close this as a dupe of #12630.

**Closed by Hixie** 2017-12-02 01:47 UTC
Labels: prod: engine, prod: framework, prod: i18n

**Comment by ryomoro** [comment] 2021-04-12 03:19
@najeira 
Now I have this issue. How can I fix [this issue](https://github.com/flutter/flutter/issues/79363#issuecomment-811859056)?

**Comment by najeira** [comment] 2021-04-12 07:05
@ryomoro My workaround is this https://qiita.com/najeira/items/dbf5663d1ed845fb1f51 . I don't know any other way.

**Comment by ryomoro** [comment] 2021-04-12 07:17
@najeira I could fix it by adding fontFamily in TextStyle. Thank you.
