### ISSUE TITLE
Make `flutter test` work on Mac OS w/o having to BYO engine

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3179] opened 2016-04-07 19:47 UTC
Currently one needs to build the Mac version of the shell to be able to run `flutter test` on Mac. It should work out-of-the-box.

/cc @sethladd

**Comment by eseidelGoogle** [comment] 2016-04-07 20:44
Duplicate of #1707

**Closed by eseidelGoogle** 2016-04-07 20:44 UTC
Labels: affects: tests, ⌘‬ platform-mac, ⚠ brand new feature
