### ISSUE TITLE
[proposal][Platform Images]reuse image resource both on Android and iOS

### ISSUE THREAD

**Issue by vimerzhao** [flutter/flutter#79542] opened 2021-04-01 10:23 UTC
## Proposal

Currently, flutter plugins only provide [IOS Platform Images](https://github.com/flutter/plugins/blob/master/packages/ios_platform_images/README.md),which can reuse iOS images. We can reuse Android drawable and assets resources in the same way. Make it a universal plugin on both platform.

A real demo:

https://github.com/vimerzhao/plugins/blob/master/packages/android_platform_images/README.md

**Comment by cyanglaz** [comment] 2021-04-01 17:40
The next step is to evaluate whether it makes sense to make it a new plugin or whether we should have a unified plugins for multiple platforms. This will be relevant for desktops and web as well.

**Comment by vimerzhao** [comment] 2021-04-02 02:36
> The next step is to evaluate whether it makes sense to make it a new plugin or whether we should have a unified plugins for multiple platforms. This will be relevant for desktops and web as well.

As far as I know, for Android and iOS, reuse of resources like images  is very important for the "add to app" scene.
That will make apk size smaller and more easier to manage resource files.

**Comment by stuartmorgan** [comment] 2023-03-11 12:54
Closing as a duplicate of https://github.com/flutter/flutter/issues/43548

**Closed by stuartmorgan** 2023-03-11 12:54 UTC
Labels: new feature, package, proposal, passed first triage, P5
