### ISSUE TITLE
Cloud Firestore returns permission denied error

### ISSUE THREAD

**Issue by EricMiranda-prog** [flutter/flutter#64590] opened 2020-08-25 21:35 UTC
I'm trying to access my firestore data, but whenever I trigger the code block of image1, the flutter returns the error of image2.
The image3 shows the rules of my database, and and image4 is the structure of the database.

![IMG-20200825-WA0027-1](https://user-images.githubusercontent.com/63105084/91230300-a8ba8100-e701-11ea-999d-555bdf6686e3.jpg)
![IMG-20200825-WA0026-2](https://user-images.githubusercontent.com/63105084/91230301-a9531780-e701-11ea-9300-cf12fb522e3b.jpg)
![IMG-20200825-WA0029-1](https://user-images.githubusercontent.com/63105084/91230304-a9ebae00-e701-11ea-9ed4-cf97de760b8c.jpg)
![IMG-20200825-WA0028-1](https://user-images.githubusercontent.com/63105084/91230306-aa844480-e701-11ea-83ee-63c645a7c214.jpg)

**Comment by wliumelb** [comment] 2020-08-25 23:36
Your security rule doesn't make any sense. You should read the manual or search on stackoverflow.

**Comment by hamdikahloun** [comment] 2020-08-26 07:30
Hi @EricMiranda-prog 
remove rules_version = '2';
//mode test
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if
          request.time < timestamp.date(2020, 9, 25);
    }
  }
}
//mode prod
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}

**Comment by darshankawar** [comment] 2020-08-26 07:40
Hi @EricMiranda-prog,
Please try solutions provided above and see if they work for you.
Also this seems to be an issue related to the security rules you set up and not with the firestore plugin.

**Comment by EricMiranda-prog** [comment] 2020-08-26 14:18
I tried all the rules given by @hamdikahloun , but none let me have access to the database.
It returned the same permission denied error.

**Comment by TahaTesser** [comment] 2020-08-27 07:45
Hi @EricMiranda-prog 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-27 07:45 UTC
Labels: in triage
