### ISSUE TITLE
IntelliJ IDEA Ultimate Edition (the doctor check crashed)     X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know       about this issue at https://github.com/flutter/flutter/issues.     X FormatException: Unexpected extension byte (at offset 5)

### ISSUE THREAD

**Issue by lylilee1** [flutter/flutter#96214] opened 2022-01-06 08:12 UTC

**Comment by danagbemava-nc** [comment] 2022-01-06 08:24
Duplicate of #94060

**Closed by danagbemava-nc** 2022-01-06 08:24 UTC
Labels: in triage
