### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Unable to read project 'Runner.xcodeproj'.	Reason: Project /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Runner.xcodeproj cannot be opened because it is missing its project.pbxproj file. Command: /usr/bin/xcodebuild, OS error code: 74

### ISSUE THREAD

**Issue by vashisth00** [flutter/flutter#69851] opened 2020-11-05 03:56 UTC
## Command
```
flutter create .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Project /Users/omkar.vilankar/Downloads/nni/nin/flutter-app/source/ios/Runner.xcodeproj cannot be opened because it is missing its project.pbxproj file. Command: /usr/bin/xcodebuild, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:171:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:323:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:388:50)
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:565:67)
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:547:41)
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:489:56)
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:466:47)
#7      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:109:19)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:380:63)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1080:18)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
```
```
[✓] Flutter (Channel master, 1.24.0-7.0.pre.100, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-IN)
    • Flutter version 1.24.0-7.0.pre.100 at /Users/omkar.vilankar/flu-new/flutter
    • Framework revision 7ceb20417c (7 hours ago), 2020-11-04 12:36:33 -0800
    • Engine revision 59b01e0e5a
    • Dart version 2.12.0 (build 2.12.0-15.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/omkar.vilankar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone 11 Pro (mobile) • A5A741A4-44E5-4383-8F85-092E71F3F799 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 86.0.4240.183

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.7.5+3001
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
app_settings-4.0.0
apple_sign_in-0.1.0
connectivity-0.4.8+6
connectivity_macos-0.1.0+7
facebook_audience_network-0.6.1
firebase_admob-0.9.3+2
firebase_analytics-5.0.14
firebase_auth-0.15.3
firebase_auth_web-0.1.3+1
firebase_core-0.4.4
firebase_core_web-0.1.1+2
firebase_database-3.1.6
firebase_messaging-6.0.16
flutter_facebook_login-3.0.0
flutter_keyboard_visibility-0.7.0
flutter_plugin_android_lifecycle-1.0.11
flutter_statusbarcolor-0.2.3
flutter_webview_plugin-0.3.11
google_maps_flutter-0.5.28+1
google_sign_in-4.5.1
google_sign_in_web-0.9.2
notification_permissions-0.4.4
onesignal_flutter-2.6.1
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+6
path_provider_windows-0.0.4+3
share-0.6.4+3
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
sqflite-1.3.2+1
uni_links-0.4.0
url_launcher-5.4.10
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5
video_player-0.10.11+1
video_player_web-0.1.4
wakelock-0.1.4+2
webview_flutter-0.3.22+1

**Comment by pedromassangocode** [comment] 2020-11-05 07:42
@kiradea  
There's similar open issue describing your case, [57083](https://github.com/flutter/flutter/issues/57083).
Please follow-up there for updates. Also check [this](https://github.com/flutter/flutter/issues/57083#issuecomment-654394040) to see if this workaround works for you.
Closing this as duplicate.

**Closed by pedromassangocode** 2020-11-05 07:42 UTC

**Comment by jmagman** [comment] 2021-05-13 21:04
This isn't a duplicate of 57083.  Tracking instead in https://github.com/flutter/flutter/issues/63280.
