### ISSUE TITLE
no supported devices connected but flutter doctor shows a device

### ISSUE THREAD

**Issue by JAicewizard** [flutter/flutter#50195] opened 2020-02-05 15:43 UTC
EDIT:
The error is because I didn't have the complete flutter file structure setup. It would be nice to get a relevant error indicating that I'm not in a valid flutter environment instead of this incorrect message.

ORIGINAL:

## Steps to Reproduce

1. connect to oneplus 5t using adb
2. try to use flutter run

## Logs

```
jaap@antergos:~/Projects/flutter_clock/analog_clock[master:57](1)>> flutter run --verbose                                                                                 16:38 05-02-2020
[  +16 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +23 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [/opt/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.7-0-g9f5ff2306
[   +5 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +34 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +62 ms] executing: /home/jaap/Android/Sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /home/jaap/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           2fe4949e               device usb:5-4 product:OnePlus5T model:ONEPLUS_A5010 device:OnePlus5T transport_id:1
[  +18 ms] No supported devices connected.
[  +11 ms] "flutter run" took 111ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)



```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.7 at /opt/flutter
    • Framework revision 9f5ff2306b (9 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/jaap/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • ONEPLUS A5010 • 2fe4949e • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

**Comment by JAicewizard** [comment] 2020-02-05 15:47
The error is because I didn't have the complete flutter file structure setup. It would be nice to get a relevant error indicating that I'm not in a valid flutter environment instead of this incorrect message.

**Comment by jonahwilliams** [comment] 2020-02-06 07:48
Duplicate of https://github.com/flutter/flutter/issues/47996

**Closed by jonahwilliams** 2020-02-06 07:48 UTC
Labels: a: error message, tool

**Comment by Z4ck404** [comment] 2020-04-29 05:49
Updated to the last version of both flutter and android studio and still get the error. Indeed the file structure caused the problem and once fixed everything works fine. but as JAicewizard  said the error message has nothing to do with the error.

**Comment by thubamamba** [comment] 2020-04-29 17:24
Cold booting my emulator worked for me.

<img width="763" alt="Screenshot 2020-04-29 at 19 23 30" src="https://user-images.githubusercontent.com/22769109/80626653-0d651800-8a4f-11ea-90a2-20383a9ad659.png">

**Comment by emretufekci** [comment] 2020-07-23 11:38
@thubamamba Thanks man your answer is good for me, you saved my time.

**Comment by anhvoduy** [comment] 2020-12-04 08:55
1. add virtual device from android studio 
2. install suitable sdk version from sdk manager
it should be fine.
