### ISSUE TITLE
The application crashes after running the "flutter clean" command.

### ISSUE THREAD

**Issue by ANopensourcedevelop** [flutter/flutter#77905] opened 2021-03-11 11:00 UTC
The application crashes after running the "flutter clean" command. All codes are red and "get_dependencies" button appears.
After clicking the "get dependencies" button, everything freezes to normal.But after installing the application apk and installing it on the phone, it does not work properly.

`flutter doctor -v`  - There is no problem!

`flutter run --release --verbose`

<details>
<summary>logs</summary>

```bash
[ +172 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +158 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +2 ms] executing: [C:\src\flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[ +118 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +1 ms] 2.0.1
[  +94 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +96 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +86 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +174 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +139 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +12 ms] stable
[ +190 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +26 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +254 ms] executing: C:\Users\User\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +120 ms] List of devices attached
[  +28 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +42 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +250 ms] No supported devices connected.
[  +58 ms] The following devices were found, but are not supported by this project:
           Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
           Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.50
           If you would like your app to run on web, consider running `flutter create .` to generate projects
for these
           platforms.
           
[  +36 ms] "flutter run" took 876ms.
[  +52 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:442:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1114:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +278 ms] ensureAnalyticsSent: 261ms
[   +5 ms] Running shutdown hooks
[   +4 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```
</details>

`pubspec.yaml`

```
name: appname
description: About app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.3
  image_picker: ^0.7.2
  path_provider: ^2.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
```

**Comment by pedromassangocode** [comment] 2021-03-11 11:20
> ```console
> [ +250 ms] No supported devices connected.
> [  +58 ms] The following devices were found, but are not supported by this project:
>            Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
>            Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.50
>            If you would like your app to run on web, consider running `flutter create .` to generate projects
> for these
>            platforms.
>            
> [  +36 ms] "flutter run" took 876ms.
> ```

Please make sure you have a supported device connected.

Can you please provide the crash logs and the steps to reproduce this issue?
Thank you

**Comment by ANopensourcedevelop** [comment] 2021-03-11 11:48
> > ```
> > [ +250 ms] No supported devices connected.
> > [  +58 ms] The following devices were found, but are not supported by this project:
> >            Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
> >            Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.50
> >            If you would like your app to run on web, consider running `flutter create .` to generate projects
> > for these
> >            platforms.
> >            
> > [  +36 ms] "flutter run" took 876ms.
> > ```
> 
> Please make sure you have a supported device connected.
> 
> Can you please provide the crash logs, your `flutter doctor -v` and the steps to reproduce this issue?
> Thank you

`flutter dostor -v`

```
Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\User\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!

```

**Comment by ANopensourcedevelop** [comment] 2021-03-11 11:53
The problem occurred after updating "Flutter".

**Comment by ANopensourcedevelop** [comment] 2021-03-11 12:32
![new](https://user-images.githubusercontent.com/78748753/110787580-cd291580-826d-11eb-912f-0f6939935635.jpg)

```
Deleting build...                                                   6,8s
Deleting .dart_tool...                                              57ms
Deleting .packages...                                               12ms
Deleting Generated.xcconfig...                                       3ms
Deleting flutter_export_environment.sh...                            4ms
Deleting .flutter-plugins-dependencies...                            3ms
Deleting .flutter-plugins...                                         5ms


```
Is it the new feature with the update?"Flutter clean" removes more?

**Comment by pedromassangocode** [comment] 2021-03-11 13:45
Hi @ANopensourcedevelop 
I must run `flutter pub get` after `flutter clean`.

**Comment by ANopensourcedevelop** [comment] 2021-03-11 19:03
> Hi @ANopensourcedevelop
> I must run `flutter pub get` after `flutter clean`.

Nothing has changed

**Comment by pedromassangocode** [comment] 2021-03-12 07:49
What happen you try to run the project? If it provide any error can you share it here?

**Comment by ANopensourcedevelop** [comment] 2021-03-12 12:37
> What happen you try to run the project? If it provide any error can you share it here?

There are no errors in the codes I wrote.It was working great before the Flutter update.Now the emulator also works but after the apk is made, it does not work on the phone.
And now there are multiple different bugs, all of them appeared after the Flutter update.
I already mentioned the first mistake above. "Flutter clean" command does not work correctly.Is it normal that all codes are red after using this command?

second problem - I'm getting this error when changing the program language

`flutter run --release --verbose`

```
[+1699 ms] E/flutter (26259): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found
for method getAll on channel plugins.flutter.io/shared_preferences)
[   +2 ms] E/flutter (26259): 
[+16190 ms] E/flutter (26259): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found
for method getAll on channel plugins.flutter.io/shared_preferences)
[   +3 ms] E/flutter (26259): 

```

I think this error is related to the "Flutter clean" command not working correctly.I'm not getting this error in the emulator

Third error - I get this error when trying to get a picture from the gallery with "Image_picker".

```
[+841007 ms] E/flutter (26259): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(already_active, Image picker
is already active, null, null)
[   +3 ms] E/flutter (26259): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
[   +2 ms] E/flutter (26259): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
[   +1 ms] E/flutter (26259): <asynchronous suspension>
[   +1 ms] E/flutter (26259): #2      MethodChannelImagePicker.pickImage
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29)
[   +2 ms] E/flutter (26259): <asynchronous suspension>
[   +2 ms] E/flutter (26259): #3      _PhotoAndNameState.takePicture (package:appname/photoAndName.dart:22)
[   +2 ms] E/flutter (26259): <asynchronous suspension>
[   +3 ms] E/flutter (26259): 

```

**Comment by pedromassangocode** [comment] 2021-03-12 13:55
> [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found
> for method getAll on channel plugins.flutter.io/shared_preferences)

This is a duplicate of https://github.com/flutter/flutter/issues/66833.

> Unhandled Exception: PlatformException(already_active, Image picker
> is already active, null, null)

This is a duplicate of https://github.com/flutter/flutter/issues/72759.



> Is it normal that all codes are red after using this command?

Yes it is normal, this should be fixed after you run `flutter pub get`. What happens when you run `flutter pub get`?

**Comment by ANopensourcedevelop** [comment] 2021-03-12 16:50
> > [HATA: flutter / lib / ui / ui_dart_state.cc (186)] İşlenmemiş İstisna: MissingPluginException ( 
> > Kanal plugins.flutter.io/shared_preferences üzerinde getAll yöntemi için uygulama bulunamadı )
> 
> Bu, [# 66833'ün kopyasıdır](https://github.com/flutter/flutter/issues/66833) .
> 
> > İşlenmeyen İstisna: PlatformException ( 
> > zaten etkin, Resim seçici zaten etkin, null, null)
> 
> Bu, [# 72759'un kopyasıdır](https://github.com/flutter/flutter/issues/72759) .
> 
> > Bu komutu kullandıktan sonra tüm kodların kırmızı olması normal mi?
> 
> Evet normaldir, koştuktan sonra bu düzeltilmelidir `flutter pub get`. Koşarsan ne olur `flutter pub get`?

Sorry, none of the solutions work.I downgraded Gradle version to 3.5.4.Has crashed a lot of errors and the app is completely broken.I think the only way is to roll back the "Flutter" update.Do you think it's a good idea to undo the Flutter updates? How can I get my "Flutter" 1 version back?

**Comment by ANopensourcedevelop** [comment] 2021-03-12 17:58
> > [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found
> > for method getAll on channel plugins.flutter.io/shared_preferences)
> 
> This is a duplicate of #66833.
> 
> > Unhandled Exception: PlatformException(already_active, Image picker
> > is already active, null, null)
> 
> This is a duplicate of #72759.
> 
> > Is it normal that all codes are red after using this command?
> 
> Yes it is normal, this should be fixed after you run `flutter pub get`. What happens when you run `flutter pub get`?

I found the source of the problem."image_picker" dependency.I removed the "image_picker" dependency completely and the application works fine.When I install it again, it is already not working properly and moreover it affects the "shared_preferences" dependency.What do I have to do now?

**Comment by ANopensourcedevelop** [comment] 2021-03-12 19:35
I found the cause of the problem. I opened a new issue to solve the problem.
#78062

**Closed** 2021-03-14 14:18 UTC
Labels: in triage

**Comment by dienduro** [comment] 2021-07-16 20:22
is the opossite to resolve the issue  first run flutter clean after run flutter pub get
