### ISSUE TITLE
`flutter test -d chrome` does not warn that the `-d` flag was ignored

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#133358] opened 2023-08-25 21:19 UTC
We claim in the tools' help that the `-d` flag applies to all commands, but this is inaccurate. We should move it to the specific commands that support it, so that it is an error to use it on those that don't (like `flutter test`).

**Comment by stuartmorgan** [comment] 2023-08-26 01:13
> so that it is an error to use it on those that don't (like `flutter test`).

`flutter test` does take `-d` [when running integration tests](https://docs.flutter.dev/testing/integration-tests#running-using-the-flutter-command) (the replacement for `flutter drive`), although that doesn't support web. So it's not going to be as simple as just removing it from the command.

**Comment by christopherfujino** [comment] 2023-08-29 16:53
Closing as a duplicate of https://github.com/flutter/flutter/issues/125070. I actually did try doing what this proposal describes, until I discovered what Stuart pointed out.

**Closed by christopherfujino** 2023-08-29 16:53 UTC
Labels: tool, c: proposal, team-tool
