### ISSUE TITLE
Unable to build my app [APPLE SILICON]

### ISSUE THREAD

**Issue by MichelMelhem** [flutter/flutter#72142] opened 2020-12-11 14:58 UTC
Hello,
I'm having issues building my app on a physical device (An iPad air) from an apple Silicon computer (Apple DTK).
The pod install command work just fine but the Xcode Build step is failing with the following output.
Xcode output :
```
Automatically signing iOS for device deployment using specified development team in Xcode project: 4W9BZB47C8
Running pod install...                                             20.5s
Running Xcode build...                                                  
Xcode build done.                                           113.9s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[36473]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1ff69e7a0) and ?? (0x1176ac2b8). One of the two will be used. Which one is undefined.
    objc[36473]: Class AMSupportURLSession is implemented in both ?? (0x1ff69e7f0) and ?? (0x1176ac308). One of the two will be used. Which one is undefined.
    2020-12-11 15:46:58.200 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.333 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.333 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.337 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.337 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.339 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.339 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.581 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.581 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.582 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.583 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.584 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.584 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.871 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.871 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.873 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.873 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.875 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.875 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.981 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.981 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.983 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.984 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.985 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2020-12-11 15:46:58.985 xcodebuild[36473:356101] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17147/IDEiOSSupportCore/DVTiPhoneSimulator.m:689
    Details:  SimDevice native architecture is nil. Device: iPad Air (4th generation) (4003113E-D7CB-419E-BE04-4B99651063BD, iOS 14.1, Shutdown), deviceType: iPad Air (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-), supportedArches: (
    ), runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1, runtimeIdentifier: com.apple.CoreSimulator.SimRuntime.iOS-14-1.
    Object:   <DVTiPhoneSimulator: 0x11e31cb70>
    Method:   -nativeArchitecture
    Thread:   <NSThread: 0x118e18af0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **

```

This is the flutter doctor output :
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-arm, locale en-FR)
    • Flutter version 1.24.0-10.2.pre at /Users/michel/developement/flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/michel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/michel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/michel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Users/michel/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Hanie’s iPad (mobile) • f6cff1ee81b6e0700e86c1caa2920173eca5bdf7 • ios            • iOS 14.1
    • Web Server (web)      • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)          • chrome                                   • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

```
I already checked the  #64502 issue and I was not able to find any corresponding problem
Thank you for your help.

**Comment by TahaTesser** [comment] 2020-12-11 15:07
Hi @MichelMelhem 
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Can you please provide your `flutter doctor -v` with the upgrade, your  complete `flutter run --verbose` (paste in a text file and drop it in the attachment), and a complete reproducible minimal code sample
Thank you

**Comment by MichelMelhem** [comment] 2020-12-11 15:16
Hello @TahaTesser,
Thank you for your answer.
I'm unable to upgrade to master as I'm getting an error with pub get:
```
flutter pub get
Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and best_report depends on intl ^0.16.1, flutter_localizations from sdk is forbidden.
So, because my_app depends on flutter_localizations any from sdk, version solving failed.
```

So you have any fix for that ?

**Comment by TahaTesser** [comment] 2020-12-11 15:22
Hi @MichelMelhem 

Please upgrade and  please try with a fresh new project without using any third party 
Please provide the details asked here https://github.com/flutter/flutter/issues/72142#issuecomment-743246648

**Comment by MichelMelhem** [comment] 2020-12-11 15:28
@TahaTesser  with a fresh project it is working just fine with the latest flutter version on master

**Comment by jerem17** [comment] 2020-12-12 23:41
For new project, it's work fine, but if i take an older project, it's not work

**Comment by TahaTesser** [comment] 2020-12-14 08:09
Hi @MichelMelhem 
This looks like an issue in your project using `extended_image` 
```bash
  /Users/michel/Documents/code/bestreport/.dart_tool/package_config.json --output-dill /Users/michel/Documents/code/bestreport/.dart_tool/flutter_build/e62a540f03548466a410c4d94de09273/app.dill --depfile
                        /Users/michel/Documents/code/bestreport/.dart_tool/flutter_build/e62a540f03548466a410c4d94de09273/kernel_snapshot.d package:best_report/main.dart
                        [+8106 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.4/lib/src/extended_image.dart:725:44: Error: No named parameter with the name 'nullOk'.
                        [  +14 ms]     _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                        [        ]                                            ^^^^^^
                        [        ] ../../../developement/flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
                        [        ]   static MediaQueryData of(BuildContext context) {
```

Can you please remove `extended_image` and try again?

**Comment by TahaTesser** [comment] 2020-12-21 14:52
Looks like a duplicate of https://github.com/flutter/flutter/issues/72142 with more activity

**Closed by TahaTesser** 2020-12-21 14:52 UTC
Labels: in triage, waiting for customer response
