### ISSUE TITLE
Confuse about Flutter Container Layout behavior

### ISSUE THREAD

**Issue by linguowu** [flutter/flutter#23668] opened 2018-10-29 09:22 UTC
when i read the Container layout behavior of [Container document](https://docs.flutter.io/flutter/widgets/Container-class.html):

> If the widget has no child, no height, no width, no constraints, and the parent provides unbounded constraints, then Container tries to size as small as possible.

so i write some code like below ,i think the second container should be as small as possible,but it fill the application’s content area (the entire screen) ，why?

```dart
class ContainerWithScaffold extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Container with scaffold',
      home: Scaffold(
        body: Container(
          color: Colors.blue,
          height: double.infinity, // i want to provides unbounded height constraints for the child container
          width: double.infinity, // i want to provides unbounded width constraints for the child container
          child: new Container(
            color: Colors.white,
          ),
        ),
      ),
    );
  }
}
```

**Comment by zoechi** [comment] 2018-10-29 09:45
This looks like a dup of #5872 to me.

**Comment by linguowu** [comment] 2018-10-29 09:56
@zoechi should double.infinity not equal  unbounded in this case ?

**Comment by zoechi** [comment] 2018-10-29 10:42
What are you actually trying to accomplish?
Wrap it in a scrollable https://flutter.io/widgets/scrolling/ if you want unbounded size.

**Comment by linguowu** [comment] 2018-10-30 01:35
@zoechi  i just confuse about the document below，but it actually seems not as small as possible:
> If the widget has no child, no height, no width, no constraints, and the parent provides unbounded constraints, then Container tries to size as small as possible.

**Comment by goderbauer** [comment] 2019-01-04 00:03
Dupe of https://github.com/flutter/flutter/issues/19289.

**Closed by goderbauer** 2019-01-04 00:03 UTC
Labels: d: api docs, framework
