### ISSUE TITLE
[Windows] Bogus keys reported in RawKeyboard.instance.keysPressed

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#76857] opened 2021-02-26 11:41 UTC
This is similar to #75627 but this time for Windows with easy reproducible steps.

The cause seems to be in the same logic in RawKeyboard that expects that every KeyDown event is followed by a KeyUp event which doesn't seem to be the case on multiple platforms.

Since the current EditableText implementation relies on RawKeyboard.instance.keysPressed, when this issue is hit, all keyboard navigation (plus backspace etc.) stops working forever and ever (or until the "bad" key, the Windows logo in this case, is pressed again which clears its status in keysPressed).

## Steps to Reproduce

1. Run flutter create editable_text_keys.
2. Update main.dart as follows:
```
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'EditableText keys test',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _textController;
  FocusNode _focusNode;

  @override
  void initState() {
    super.initState();
    _textController = TextEditingController(text: 'some\nmulti\nline\ntext\n\njust\na few\nlines\nmore\n...\n...\n');
    _focusNode = FocusNode(
      onKey: (_, RawKeyEvent keyEvent) {
        if (keyEvent is! RawKeyDownEvent) return false;
        final Set<LogicalKeyboardKey> keysPressed = LogicalKeyboardKey.collapseSynonyms(RawKeyboard.instance.keysPressed);
        print('FocusNode onKey RawKeyEvent: $keyEvent | keysPressed: $keysPressed');
        return false;
      }
    );
  }

  @override
  void dispose() {
    _focusNode.dispose();
    _textController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('EditableText keys test')),
      body: Container(
        margin: EdgeInsets.all(10.0),
        child: EditableText(
          controller: _textController,
          focusNode: _focusNode,
          maxLines: null,
          autofocus: true,
          style: TextStyle(fontSize: 24.0, color: Colors.black),
          cursorColor: Colors.amber,
          backgroundCursorColor: Colors.grey,
        ),
      ),
    );
  }
}
```
3. Run the application on Windows 10. Press different keys, including arrow keys and observe in the printed logs if the RawKeyEvent and keysPressed match what's being pressed.
4. Make sure 2 or more keyboard layouts are enabled. Press the default keyboard layout switch shortcut (Windows logo key + space) and press it again so it switches to another layout
5. Switch back to the Flutter app window and repeat step 3.

**Expected results**: Only the actual keys being pressed are reported in the RawKeyboard.instance.keysPressed set.
```
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#570d4(logicalKey: LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up"), physicalKey: PhysicalKeyboardKey#70060(usbHidUsage: "0x00070060", debugName: "Numpad 8")) | keysPressed: {LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#dc135(logicalKey: LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down"), physicalKey: PhysicalKeyboardKey#7005a(usbHidUsage: "0x0007005a", debugName: "Numpad 2")) | keysPressed: {LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#b82a9(logicalKey: LogicalKeyboardKey#7004f(keyId: "0x10007004f", keyLabel: "", debugName: "Arrow Right"), physicalKey: PhysicalKeyboardKey#7005e(usbHidUsage: "0x0007005e", debugName: "Numpad 6")) | keysPressed: {LogicalKeyboardKey#7004f(keyId: "0x10007004f", keyLabel: "", debugName: "Arrow Right")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#02e55(logicalKey: LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up"), physicalKey: PhysicalKeyboardKey#70060(usbHidUsage: "0x00070060", debugName: "Numpad 8")) | keysPressed: {LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up")}
```

**Actual results:** On any key press, The key "Meta" is constantly reported in RawKeyboard.instance.keysPressed despite not being pressed:
```
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#55ec0(logicalKey: LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down"), physicalKey: PhysicalKeyboardKey#7005a(usbHidUsage: "0x0007005a", debugName: "Numpad 2")) | keysPressed: {LogicalKeyboardKey#700e3(keyId: "0x201000700e3", keyLabel: "", debugName: "Meta"), LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#5dcd1(logicalKey: LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up"), physicalKey: PhysicalKeyboardKey#70060(usbHidUsage: "0x00070060", debugName: "Numpad 8")) | keysPressed: {LogicalKeyboardKey#700e3(keyId: "0x201000700e3", keyLabel: "", debugName: "Meta"), LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#5a1c3(logicalKey: LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down"), physicalKey: PhysicalKeyboardKey#7005a(usbHidUsage: "0x0007005a", debugName: "Numpad 2")) | keysPressed: {LogicalKeyboardKey#700e3(keyId: "0x201000700e3", keyLabel: "", debugName: "Meta"), LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#d822d(logicalKey: LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up"), physicalKey: PhysicalKeyboardKey#70060(usbHidUsage: "0x00070060", debugName: "Numpad 8")) | keysPressed: {LogicalKeyboardKey#700e3(keyId: "0x201000700e3", keyLabel: "", debugName: "Meta"), LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up")}
```

<details>
  <summary>Logs</summary>

```
```

```
PS > flutter analyze
Analyzing editable_text_keys...
No issues found! (ran in 4.4s)
```

```
PS > flutter doctor -v
[√] Flutter (Channel dev, 1.27.0-8.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.27.0-8.0.pre at C:\flutter
    • Framework revision b7d4806243 (7 days ago), 2021-02-19 09:22:45 -0800
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.53.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment] 2021-02-26 12:51
Hi @tgucio 
Thanks for filing the issue, I can reproduce it on Windows 10

### Before
```
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#1039a(logicalKey: LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up"), physicalKey: PhysicalKeyboardKey#70060(usbHidUsage: "0x00070060", debugName: "Numpad 8")) | keysPressed: {LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#0f743(logicalKey: LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down"), physicalKey: PhysicalKeyboardKey#7005a(usbHidUsage: "0x0007005a", debugName: "Numpad 2")) | keysPressed: {LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#5931f(logicalKey: LogicalKeyboardKey#7004f(keyId: "0x10007004f", keyLabel: "", debugName: "Arrow Right"), physicalKey: PhysicalKeyboardKey#7005e(usbHidUsage: "0x0007005e", debugName: "Numpad 6")) | keysPressed: {LogicalKeyboardKey#7004f(keyId: "0x10007004f", keyLabel: "", debugName: "Arrow Right")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#f5de9(logicalKey: LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: "", debugName: "Arrow Left"), physicalKey: PhysicalKeyboardKey#7005c(usbHidUsage: "0x0007005c", debugName: "Numpad 4")) | keysPressed: {LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: "", debugName: "Arrow Left")}
```

### After
```bash
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#cf1c9(logicalKey: LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up"), physicalKey: PhysicalKeyboardKey#70060(usbHidUsage: "0x00070060", debugName: "Numpad 8")) | keysPressed: {LogicalKeyboardKey#700e3(keyId: "0x201000700e3", keyLabel: "", debugName: "Meta"), LogicalKeyboardKey#70052(keyId: "0x100070052", keyLabel: "", debugName: "Arrow Up")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#4e514(logicalKey: LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down"), physicalKey: PhysicalKeyboardKey#7005a(usbHidUsage: "0x0007005a", debugName: "Numpad 2")) | keysPressed: {LogicalKeyboardKey#700e3(keyId: "0x201000700e3", keyLabel: "", debugName: "Meta"), LogicalKeyboardKey#70051(keyId: "0x100070051", keyLabel: "", debugName: "Arrow Down")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#cba52(logicalKey: LogicalKeyboardKey#7004f(keyId: "0x10007004f", keyLabel: "", debugName: "Arrow Right"), physicalKey: PhysicalKeyboardKey#7005e(usbHidUsage: "0x0007005e", debugName: "Numpad 6")) | keysPressed: {LogicalKeyboardKey#700e3(keyId: "0x201000700e3", keyLabel: "", debugName: "Meta"), LogicalKeyboardKey#7004f(keyId: "0x10007004f", keyLabel: "", debugName: "Arrow Right")}
flutter: FocusNode onKey RawKeyEvent: RawKeyDownEvent#e61e4(logicalKey: LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: "", debugName: "Arrow Left"), physicalKey: PhysicalKeyboardKey#7005c(usbHidUsage: "0x0007005c", debugName: "Numpad 4")) | keysPressed: {LogicalKeyboardKey#700e3(keyId: "0x201000700e3", keyLabel: "", debugName: "Meta"), LogicalKeyboardKey#70050(keyId: "0x100070050", keyLabel: "", debugName: "Arrow Left")}
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.106, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.27.0-9.0.pre.106 at C:\Users\Taha\Code\flutter_master
    • Framework revision 1610a27476 (3 hours ago), 2021-02-25 20:26:02 -0800
    • Engine revision 1515b1d4a4
    • Dart version 2.13.0 (build 2.13.0-79.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.74

• No issues found!
```

</details>

**Comment by gspencergoog** [comment] 2021-03-11 19:39
cc @dkwingsmt

**Comment by rprx** [comment] 2021-06-23 16:28
The latest master channel has fixed this issue.

**Comment by TahaTesser** [comment] 2021-07-01 12:11
@rprx 
Thanks for the update, I feel safe to close the issue as it seems to be fixed

**Closed by TahaTesser** 2021-07-01 12:11 UTC
Labels: P4, a: desktop, engine, found in release: 1.27, has reproducible steps, platform-windows
