### ISSUE TITLE
Flutter asked me to report this.

### ISSUE THREAD

**Issue by sheppe** [flutter/flutter#124316] opened 2023-04-06 14:24 UTC
I just have a simple PaginatedDataTable that I'm trying to make responsive by reducing the number of columns displayed in it when the display is smaller. I assume that is the underlying problem, and I'm not personally looking for a fix here. I'm just reporting it because Flutter asked me to.

```
---
Launching lib\main.dart on Windows in debug mode...
Connecting to VM Service at ws://127.0.0.1:51934/joT0Ntjn4h8=/ws

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building LayoutBuilder:
'package:flutter/src/material/data_table.dart': Failed assertion: line 416 pos 15: '!rows.any((DataRow row) => row.cells.length != columns.length)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
PaginatedDataTable
When the exception was thrown, this was the stack
#2      new DataTable
#3      PaginatedDataTableState.build.<anonymous closure>
#4      _LayoutBuilderElement._layout.layoutCallback
#5      BuildOwner.buildScope
#6      _LayoutBuilderElement._layout
#7      RenderObject.invokeLayoutCallback.<anonymous closure>
#8      PipelineOwner._enableMutationsToDirtySubtrees
#9      RenderObject.invokeLayoutCallback
#10     RenderConstrainedLayoutBuilder.rebuildIfNecessary
#11     _RenderLayoutBuilder.performLayout
#12     RenderObject.layout
#13     RenderBox.layout
#14     RenderProxyBoxMixin.performLayout
#15     RenderObject.layout
#16     RenderBox.layout
#17     RenderProxyBoxMixin.performLayout
#18     RenderObject.layout
#19     RenderBox.layout
#20     RenderProxyBoxMixin.performLayout
#21     RenderCustomPaint.performLayout
#22     RenderObject.layout
#23     RenderBox.layout
#24     RenderProxyBoxMixin.performLayout
#25     _RenderCustomClip.performLayout
#26     RenderObject.layout
#27     RenderBox.layout
#28     RenderPadding.performLayout
#29     RenderObject.layout
#30     RenderBox.layout
#31     RenderProxyBoxMixin.performLayout
#32     RenderObject.layout
#33     RenderBox.layout
#34     _RenderSingleChildViewport.performLayout
#35     RenderObject.layout
#36     RenderBox.layout
#37     RenderProxyBoxMixin.performLayout
#38     RenderObject.layout
#39     RenderBox.layout
#40     RenderProxyBoxMixin.performLayout
#41     RenderObject.layout
#42     RenderBox.layout
#43     RenderProxyBoxMixin.performLayout
#44     RenderObject.layout
#45     RenderBox.layout
#46     RenderProxyBoxMixin.performLayout
#47     RenderObject.layout
#48     RenderBox.layout
#49     RenderProxyBoxMixin.performLayout
#50     RenderObject.layout
#51     RenderBox.layout
#52     RenderProxyBoxMixin.performLayout
#53     RenderObject.layout
#54     RenderBox.layout
#55     RenderProxyBoxMixin.performLayout
#56     RenderObject.layout
#57     RenderBox.layout
#58     RenderProxyBoxMixin.performLayout
#59     RenderCustomPaint.performLayout
#60     RenderObject.layout
#61     RenderBox.layout
#62     RenderProxyBoxMixin.performLayout
#63     RenderObject.layout
#64     RenderBox.layout
#65     RenderProxyBoxMixin.performLayout
#66     RenderObject.layout
#67     RenderBox.layout
#68     RenderProxyBoxMixin.performLayout
#69     RenderObject.layout
#70     RenderBox.layout
#71     RenderProxyBoxMixin.performLayout
#72     RenderObject.layout
#73     RenderBox.layout
#74     RenderProxyBoxMixin.performLayout
#75     RenderObject.layout
#76     RenderBox.layout
#77     _RenderLayoutBuilder.performLayout
#78     RenderObject.layout
#79     RenderBox.layout
#80     ChildLayoutHelper.layoutChild
#81     RenderFlex._computeSizes
#82     RenderFlex.performLayout
#83     RenderObject.layout
#84     RenderBox.layout
#85     RenderPadding.performLayout
#86     RenderObject.layout
#87     RenderBox.layout
#88     ChildLayoutHelper.layoutChild
#89     RenderStack._computeSize
#90     RenderStack.performLayout
#91     RenderObject.layout
#92     RenderBox.layout
#93     MultiChildLayoutDelegate.layoutChild
#94     _ScaffoldLayout.performLayout
#95     MultiChildLayoutDelegate._callPerformLayout
#96     RenderCustomMultiChildLayoutBox.performLayout
#97     RenderObject.layout
#98     RenderBox.layout
#99     RenderProxyBoxMixin.performLayout
#100    RenderObject.layout
#101    RenderBox.layout
#102    RenderProxyBoxMixin.performLayout
#103    _RenderCustomClip.performLayout
#104    RenderObject.layout
#105    RenderBox.layout
#106    RenderProxyBoxMixin.performLayout
#107    RenderObject.layout
#108    RenderBox.layout
#109    RenderProxyBoxMixin.performLayout
#110    RenderObject.layout
#111    RenderBox.layout
#112    RenderProxyBoxMixin.performLayout
#113    RenderObject.layout
#114    RenderBox.layout
#115    RenderProxyBoxMixin.performLayout
#116    RenderObject.layout
#117    RenderBox.layout
#118    RenderProxyBoxMixin.performLayout
#119    RenderObject.layout
#120    RenderBox.layout
#121    RenderProxyBoxMixin.performLayout
#122    RenderObject.layout
#123    RenderBox.layout
#124    RenderProxyBoxMixin.performLayout
#125    RenderObject.layout
#126    RenderBox.layout
#127    RenderProxyBoxMixin.performLayout
#128    RenderObject.layout
#129    RenderBox.layout
#130    RenderProxyBoxMixin.performLayout
#131    RenderObject.layout
#132    RenderBox.layout
#133    RenderProxyBoxMixin.performLayout
#134    RenderOffstage.performLayout
#135    RenderObject.layout
#136    RenderBox.layout
#137    RenderProxyBoxMixin.performLayout
#138    RenderObject.layout
#139    RenderBox.layout
#140    _RenderTheatre.performLayout
#141    RenderObject.layout
#142    RenderBox.layout
#143    RenderProxyBoxMixin.performLayout
#144    RenderObject.layout
#145    RenderBox.layout
#146    RenderProxyBoxMixin.performLayout
#147    RenderObject.layout
#148    RenderBox.layout
#149    RenderProxyBoxMixin.performLayout
#150    RenderObject.layout
#151    RenderBox.layout
#152    RenderProxyBoxMixin.performLayout
#153    RenderCustomPaint.performLayout
#154    RenderObject.layout
#155    RenderBox.layout
#156    RenderProxyBoxMixin.performLayout
#157    RenderObject.layout
#158    RenderBox.layout
#159    RenderProxyBoxMixin.performLayout
#160    RenderObject.layout
#161    RenderBox.layout
#162    RenderProxyBoxMixin.performLayout
#163    RenderObject.layout
#164    RenderBox.layout
#165    RenderProxyBoxMixin.performLayout
#166    RenderObject.layout
#167    RenderBox.layout
#168    RenderProxyBoxMixin.performLayout
#169    RenderObject.layout
#170    RenderBox.layout
#171    RenderProxyBoxMixin.performLayout
#172    RenderObject.layout
#173    RenderBox.layout
#174    RenderView.performLayout
#175    RenderObject._layoutWithoutResize
#176    PipelineOwner.flushLayout
#177    RendererBinding.drawFrame
#178    WidgetsBinding.drawFrame
#179    RendererBinding._handlePersistentFrameCallback
#180    SchedulerBinding._invokeFrameCallback
#181    SchedulerBinding.handleDrawFrame
#182    SchedulerBinding._handleDrawFrame
#183    _invoke (dart:ui/hooks.dart:145:13)
#184    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#185    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
Application finished.
Exited (sigterm)
```

**Comment by huycozy** [comment] 2023-04-07 05:03
This is caused by your cells distribution does not satisfy this condition of DataTable, please see: https://github.com/flutter/flutter/blob/aa6a0a9dea638dcb17e175f37eb4ad0d614702f6/packages/flutter/lib/src/material/data_table.dart#L448

Please check a [similar issue](https://stackoverflow.com/questions/63978409/populate-a-flutter-datatable-with-data-from-firestore-using-a-streambuilder) on StackOverflow.

Closing as this is intended behavior. Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

**Closed by huycozy** 2023-04-07 05:03 UTC
Labels: in triage
