### ISSUE TITLE
Kernel snapshot exception - when using flutter run with --local-engine

### ISSUE THREAD

**Issue by harsh-im** [flutter/flutter#142589] opened 2024-01-31 07:34 UTC
I am encountering an issue while attempting to run my Flutter app (hello world -android) using a locally built Flutter engine. I have followed the steps outlined in the official documentation [https://github.com/flutter/flutter/wiki/Compiling-the-engine](url) to build the Flutter engine.

Upon executing the command:

`flutter run --local-engine=android_debug_unopt_arm64  --local-engine-host=host_debug_unopt_arm64  --local-engine-src-path=/Users/harsh/research/engine/src`

HOST OS - macos - arm64 M1 chip
Flutter version - 3.16.9

I encounter the following error:

<img width="1049" alt="image" src="https://github.com/flutter/flutter/assets/85297965/ad79791e-9059-48d4-9357-a57b91aa7d73">

I have reviewed the documentation and various resources, but I am unable to resolve this issue. Any assistance or suggestions would be greatly appreciated.

Thank you.

**Comment by huycozy** [comment] 2024-01-31 11:18
Hi @harsh-im 
Please provide the crash log in text format instead of a screenshot for better readability and investigation. Please also provide the information indicated below:

- The output of verbose run (`flutter run ... -v`). It may be long, please save it into a file and attach it here.
- Did you make any modifications to the engine that you built? 
- Which engine hash are you building at?

Thanks!

**Comment by harsh-im** [comment] 2024-01-31 17:09
@huycozy Thanks for the quick response, I figured out that I was building wrong engine hash & after fixing it, I was able to run the app with a local engine.

can you just confirm that we need to build  the flutter engine hash corresponding flutter version? i.e TAG of the commit should be equal to the flutter version?

**Comment by huycozy** [comment] 2024-02-01 05:23
>can you just confirm that we need to build the flutter engine hash corresponding to the flutter version of the device? i.e TAG of the commit should be equal to the flutter version?

I think so. Each Flutter release will contain a rolled/corresponding engine version that makes sure of API compatibility. Your error above seems to be caused by the hash engine not corresponding to the Flutter version you are using. 

Closing this issue as solved.

**Closed by huycozy** 2024-02-01 05:23 UTC
Labels: in triage
