### ISSUE TITLE
[local_auth]Authorization call does not work and crash when app resumed

### ISSUE THREAD

**Issue by Alexfuse** [flutter/flutter#57658] opened 2020-05-20 09:01 UTC
local_auth: ^0.6.2+2 
Authorization call does not work.  Although the rest of the application works. but If you minimize the app and then resume, it crashes on this device Sony Xperia XA1 Plus Android 8.0,Also, everything works on Asus ZB602KL with android 9

```
from firebase
`Fatal Exception: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(:419)
at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(:4)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView()
at androidx.appcompat.app.AppCompatDialog.setContentView(:4)
at androidx.appcompat.app.AlertController.installContent(:6)
at androidx.appcompat.app.AlertDialog.onCreate(:5)
at android.app.Dialog.dispatchOnCreate(Dialog.java:413)
at android.app.Dialog.show(Dialog.java:308)
at androidx.fragment.app.DialogFragment.onStart(:10)
at androidx.fragment.app.Fragment.performStart(:16)
at androidx.fragment.app.FragmentManagerImpl.a(:759)
at androidx.fragment.app.FragmentManagerImpl.i(:93)
at androidx.fragment.app.FragmentManagerImpl.a(:42)
at androidx.fragment.app.BackStackRecord.a(:173)
at androidx.fragment.app.FragmentManagerImpl.executeOps(:38)
at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(:114)
at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(:88)
at androidx.fragment.app.FragmentManagerImpl.execPendingActions(:21)
at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions()
at androidx.biometric.BiometricPrompt.authenticateInternal(:260)
at androidx.biometric.BiometricPrompt.authenticate(:3)
at io.flutter.plugins.localauth.AuthenticationHelper$1.run(:8)
at android.os.Handler.handleCallback(Handler.java:869)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.os.Looper.loop(Looper.java:206)
at android.app.ActivityThread.main(ActivityThread.java:6749)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)`
```
```
flutter doctor -v
`[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.3 19D76, locale ru-RU)
    • Flutter version 1.17.1 at /Users/admin/Flutter_SDK/flutter
    • Framework revision f7a6a7906b (7 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • PSP3495DUO • PSP200590203429 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```
Everything work on old version local_auth: ^0.4.0+1

**Comment by TahaTesser** [comment] 2020-05-20 10:31
duplicate of. https://github.com/flutter/flutter/issues/55638

**Closed by TahaTesser** 2020-05-20 10:31 UTC
