### ISSUE TITLE
InteractiveViewer with constrained: false ignores Center widget and alignment

### ISSUE THREAD

**Issue by alliha** [flutter/flutter#90517] opened 2021-09-22 12:00 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: main.dart at line 79 , wrap the Column:
`child: InteractiveViewer(
  constrained: false,
  child: Column(...),
),`

Alternatively, in your own code, wrap an InteractiveViewer widget in a Center widget (or Align with alignment center) with the parameter "constrained" set to false. 

**Expected results:** 
An InteractiveViewer that's centered on the screen.

**Actual results:** 
An InteractiveViewer that's aligned to the top left of the screen. 

I'm guessing this is because in interactive_viewer.dart line 1091, alignment is set to top left. If this is commented out for testing purposes locally, the widget aligns itself correctly but the zooming behaviour is off. See videos for behaviour (My InteractiveViewer is part of a popup card that contains a table from the flutter_html package):  https://imgur.com/a/1jrNAe6 

<details>
<summary>Logs</summary>

```console
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale nb-NO)
    • Flutter version 2.2.3 at C:\Programs\flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Alfred.Lindal.Haug\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\Alfred.Lindal.Haug\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 93.0.961.52

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment] 2021-09-22 13:01
Hi @alliha, 

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

**Comment by alliha** [comment] 2021-09-22 15:02
I've updated the original post with your requests.

**Comment by danagbemava-nc** [comment] 2021-09-23 08:38
Hi @alliha, this may be the intended behaviour. The `InteractiveViewer` with `constrained:false` takes up as much space as is available. 
From the `InteractiveViewer` api docs on `constrained`.

```dart
/// Whether the normal size constraints at this point in the widget tree are
  /// applied to the child.
  ///
  /// If set to false, then the child will be given infinite constraints. This
  /// is often useful when a child should be bigger than the InteractiveViewer.
```

Also if we use the WidgetInspector, we can see the following: 

<details>
<summary>screenshots</summary>

`constrained: false`

![IMG_2969](https://user-images.githubusercontent.com/88313112/134477399-9d8bc129-b909-4818-a2f5-44b8360d0f2f.PNG)

![IMG_2971](https://user-images.githubusercontent.com/88313112/134477454-baed88b5-5f57-4c1d-8ef3-bbf50106b340.PNG)

`constrained: true`

![IMG_2972](https://user-images.githubusercontent.com/88313112/134477537-a59590e1-2b3a-444e-af31-3159c82f1f9b.PNG)

![IMG_2973](https://user-images.githubusercontent.com/88313112/134477564-00019077-13f5-45f4-8c58-edbf774a8a1b.PNG)

</details>

**Comment by alliha** [comment] 2021-09-23 12:39
If this is the intended behaviour, how in the world am I supposed to center an InteractiveViewer?

**Comment by danagbemava-nc** [comment] 2021-09-23 12:48
Just so we're clear, 

is it the content of the `InteractiveViewer` that you want to center or the `InteractiveViewer` itself?

**Comment by alliha** [comment] 2021-09-23 13:35
Both, no? Technically it would be the child I want centered, but I imagine I would get weird behaviour if the `InteractiveViewer` wasn't centered. I've tried wrapping the child with a `Center` to no avail. 

Would there possibly be a way to change the `Alignment` property of the `OverflowBox` that InteractiveViewer builds from my own code?

**Comment by danagbemava-nc** [comment] 2021-09-23 13:48
I imagine that should be possible with the `InteractiveViewer.builder`, although, is there any reason why you need it to unconstrained?

**Comment by alliha** [comment] 2021-09-23 13:57
Yes, some elements will be quite large and will need to be zoomed in and overflow the screen to be able to be read.

**Comment by danagbemava-nc** [comment] 2021-09-24 11:04
Hi @alliha, 

I attempted with a crude sample and while I do not know if it might help your use case, I just thought I'd share and get feedback.

<details>
<summary>code sample</summary>

```dart 

...

final TransformationController _transformationController =  TransformationController();

...

OverflowBox(
          minWidth: 0.0,
          minHeight: 0.0,
          alignment: Alignment.center,
          child: SizedBox(
            height: double.infinity,
            width: double.infinity,
            child: InteractiveViewer(
              boundaryMargin: const EdgeInsets.all(16.0),
              maxScale: 4.0,
              minScale: 0.25,
              transformationController: _transformationController,
              // alignPanAxis: true,
              child: Container(
                color: Colors.red,
              ),
            ),
          ),
        );
```
</details>

**Comment by alliha** [comment] 2021-09-29 13:48
That didn't work in my case, I ended up just creating an entire new widget from `InteractiveViewer` so I could get the functionality needed.

**Comment by danagbemava-nc** [comment] 2021-09-29 14:18
@alliha, can you share the widget? For now, I will mark as solved because I haven't found any other users requesting for it. If some people do, I believe your solution might help them and if more people require it, it could be integrated into the framework. 

Thank you

**Comment by alliha** [comment] 2021-10-01 07:58
There's not much to share, I straight up copied the entire code from `InteractiveViewer.dart` and simply renamed it, and replaced the alignment property for `OverflowBox` when the `InteractiveViewer` is built with constrained set to false to be centered instead of top-left. This solution makes some interesting behaviour when zooming, but at least it looks slightly better.

**Comment by danagbemava-nc** [comment] 2021-10-01 10:40
Thanks for the feedback. 

Since you've come up with a solution, I feel it is safe to close the issue. 

Closing as solved.

**Closed by danagbemava-nc** 2021-10-01 10:40 UTC
Labels: in triage
