### ISSUE TITLE
Dart define no longer working as expected after upgrading to Flutter 2.2.0

### ISSUE THREAD

**Issue by moseskarunia** [flutter/flutter#83086] opened 2021-05-21 09:32 UTC
Hello, just had a problem running a flutter project which appends postfix to applicationId in build.gradle in flutter 2.2. It works fine in flutter 2.0.6 and previous, using dart define. After reading it, I think it's related to https://github.com/flutter/flutter/pull/75027 but not sure what exactly or how to make it work.

Update: Turns out the problem is there on dart 2.12.3++. It works fine in 2.12.0. Any idea why?

# Problem description

## Inside android/app/build.gradle
```dart
def dartEnvironmentVariables = [
    DART_DEFINE_APP_NAME: 'BackOffice',
    DART_DEFINE_APP_SUFFIX: null
];
if (project.hasProperty('dart-defines')) {
    dartEnvironmentVariables = dartEnvironmentVariables + project.property('dart-defines')
        .split(',')
        .collectEntries { entry ->
            def pair = URLDecoder.decode(entry).split('=')
            [(pair.first()): pair.last()]
        }
}
...
android {
   ...
    defaultConfig {
        ...
        applicationIdSuffix dartEnvironmentVariables.DART_DEFINE_APP_SUFFIX
        resValue "string", "app_name", dartEnvironmentVariables.DART_DEFINE_APP_NAME
        ...
    }
    ...
}
```

## Run using .vscode/launch.json

```
{
  ...
  "configurations": [
        {
      "name": "back office dev",
      "cwd": "apps/back_office",
      "request": "launch",
      "program": "lib/main_dev.dart",
      "type": "dart",
      "args": [
        "--dart-define=DART_DEFINE_APP_NAME=dev-BackOffice",
        "--dart-define=DART_DEFINE_APP_SUFFIX=.dev",
      ]
    },
  ]
}
```

## Error

> FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.myapp.myapp'

# Flutter Doctor -v

```
[✓] Flutter (Channel unknown, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-ID)
    • Flutter version 2.2.0 at /Users/moseskarunia/fvm/versions/2.2.0
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/moseskarunia/Development/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/moseskarunia/Development/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • // truncated
    • // truncated

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-05-21 11:19
Hi @moseskarunia 
This is a duplicate of https://github.com/flutter/flutter/issues/82865, see https://github.com/flutter/flutter/issues/82865#issuecomment-844222972
Closing as duplicate 
Thank you

**Closed by TahaTesser** 2021-05-21 11:19 UTC
Labels: in triage
