### ISSUE TITLE
webview_flutter plugin: Android TV Dpad navigation support

### ISSUE THREAD

**Issue by skymansandy** [flutter/flutter#75322] opened 2021-02-03 11:45 UTC
Hi Team, I'm building an Android TV with flutter and my use-case needs TV remote's D-pad navigation support for webview. Its kind of a Google StreetView type of website and arrow keys are supposed to help navigating. But in Flutter Webview I don't see any way to dispatch Key Events/Motion events to the webview.

PS: `evaluateJavascript()` can't be used since events passed through them won't be considered a trusted event, and hence No action.

Help needed.. TIA!

**Comment by TahaTesser** [comment] 2021-02-03 14:51
Hi @skymansandy 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/54984
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by skymansandy** [comment] 2021-02-03 15:18
Hi @TahaTesser,  Just checked #54984, the issue there seems to be with flutter widgets not getting focus.
However, the problem I'm facing is inside **WebView**. 

When I load any website in the webview, I can't interact(scroll, key events etc) with web page elements, I tried to use the WebView's `evaluateJavascript()` method to simulate Key events in javascript but those don't work since they aren't trusted events.

**Comment by TahaTesser** [comment] 2021-02-04 11:19
Hi @skymansandy 
Are you using hybrid mode? 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by skymansandy** [comment] 2021-02-04 12:10
Hey @TahaTesser 

Here's my doctor report:

```
[✓] Flutter (Channel master, 1.26.0-13.0.pre.50, on Mac OS X 10.15.7 19H114
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-13.0.pre.50 at /Users/sandesh/development/flutter
    • Framework revision 2a188eeca3 (2 weeks ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sandesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.4
    • Dart plugin version 202.8346

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • sdk google atv x86 (mobile) • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 88.0.4324.146

• No issues found!
```

Minimum reproducible code:  https://github.com/skymansandy/flutterTVNavExperiment

For demonstrating a use-case which needs arrow key navigation, I've loaded this URL (https://cinekidplay.nl/ontdekken) in the WebView. In the browser we can navigate using arrow keys but not in Android TV.

**Comment by TahaTesser** [comment] 2021-02-05 07:03
Hi @skymansandy 
Thanks for the details, I don't have access to Android TV, can you please modify your code little and support for [hybrid composition](https://pub.dev/packages/webview_flutter#using-hybrid-composition) and then try again?

Just add following `init` in your `_MyHomePageState` 
```dart
 @override
  void initState() {
    super.initState();
    // Enable hybrid composition.
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }
```
`flutter clean` and `flutter run -v`
Thank you

**Comment by skymansandy** [comment] 2021-02-08 10:10
Hi @TahaTesser 

Hybrid composition fixed the keyboard navigation. Thanks!

Also in _webview_flutter_, is there an API method to simulate key events in the WebView like the android native's `View.dispatchKeyEvent`, `View.dispatchTouchEvent`, etc?

**Comment by TahaTesser** [comment] 2021-02-08 12:48
Hi @skymansandy 
Glad you resolved the issue

That looks like a separate issue than this, maybe a proposal? Please file a new issue for it
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-02-08 12:48 UTC
Labels: in triage
