### ISSUE TITLE
[documentation] document how to align children in row/column independently

### ISSUE THREAD

**Issue by Elvis5566** [flutter/flutter#34500] opened 2019-06-14 15:05 UTC
I am trying to add rows in a column, the height of row depends on children in row, and I need to set different Align for each child like this:
```
Column(
      children: <Widget>[
        Row(
          children: <Widget>[
            Align(
              alignment: Alignment.topCenter,
              child: Container(width: 50, height: 50, color: Colors.red),
            ),
            Align(
              alignment: Alignment.bottomCenter,
              child: Container(width: 100, height: 100, color: Colors.green),
            ),
          ],
        )
      ],
 )
```
The Align does not work, however, if I wrap Row in a fixed size Container, then it works as expected.
I also saw #18356, which says we can set crossAxisAlignment as stretch to make it work.
However, the height of row should be wrap content in my case.
I think the align behavior is inconsistent, seems like a bug.

[Here is example for reference](https://github.com/Elvis5566/flutter-column-row-example)

Thank you

```
```

**Comment by sososdk** [comment] 2019-12-03 09:27
@shihaohong Is there a solution?

**Comment by sososdk** [comment] 2019-12-03 09:27
@Elvis5566 Is there a solution?

**Comment by Elvis5566** [comment] 2019-12-06 03:06
@sososdk 
Yes, you can wrap row in IntrinsicHeight to make this work.

**Comment by androidBuddy** [comment] 2020-02-27 06:09
I think, this may help you:

[https://stackoverflow.com/questions/50365770/flutter-align-two-items-on-extremes-one-on-the-left-and-one-on-the-right](https://stackoverflow.com/questions/50365770/flutter-align-two-items-on-extremes-one-on-the-left-and-one-on-the-right)

**Comment by narek11** [comment] 2020-04-16 21:33
@Elvis5566 thank you, wrapping `Row` or `Column` in my case with `IntrinsicWidth` did help

**Comment by radomir9720** [comment] 2020-06-28 09:27
@narek11, @Elvis5566 Thanksss!

**Comment by goderbauer** [comment] 2023-02-01 23:12
Duplicate of https://github.com/flutter/flutter/issues/34472.

**Closed by goderbauer** 2023-02-01 23:12 UTC
Labels: easy fix, framework, d: api docs, customer: crowd, proposal, documentation, passed first triage, P4
