### ISSUE TITLE
Multiple versions of adb can fight each other, breaking the service protocol

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#9430] opened 2017-04-17 21:09 UTC
Splitting off from:  https://github.com/flutter/flutter/issues/8876

**Comment by Hixie** [comment] 2017-12-13 00:10
We should probably detect this and report it, at least.

**Comment by zoechi** [comment] 2019-01-18 09:45
Duplicate of #9709 ?

**Closed** 2020-01-03 01:55 UTC
Labels: tool, ▣ platform-android
