### ISSUE TITLE
FileSystemException: Cannot create link (OS Error: access denied。 , errno = 5)"

### ISSUE THREAD

**Issue by taoruifu** [flutter/flutter#77561] opened 2021-03-08 05:43 UTC
version info:
--------------------------------------------------------------------------------------------------------
PS E:\app\flokk\flokk_src> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.1.0-10.0.pre, on Microsoft Windows [Version 10.0.17763.1577], locale zh-CN)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
[!] Android Studio (not installed)
[√] VS Code (version 1.53.1)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.
PS E:\app\flokk\flokk_src> flutter devices
2 connected devices:

Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.1577]
Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190

error log:
----------------------------------------------------------------------------------------------------
FileSystemException: FileSystemException: Cannot create link, path = 'E:\app\flokk\flokk_src\windows\flutter\ephemeral\.plugin_symlinks\file_chooser' (OS Error: 拒绝访问。
, errno = 5)

```
#0      _Link.throwIfError (dart:io/link.dart:263:7)
#1      _Link.createSync (dart:io/link.dart:184:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/plugins.dart:1483:12)
#5      createPluginSymlinks (package:flutter_tools/src/plugins.dart:1424:5)
#6      buildWindows (package:flutter_tools/src/windows/build_windows.dart:53:3)
#7      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:55:11)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1186:12)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1037:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#11     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:60:12)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#20     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#21     runInContext (package:flutter_tools/src/context_runner.dart:77:10)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>

**Comment by iapicca** [comment] 2021-03-08 10:54
possible duplicate of https://github.com/flutter/flutter/issues/69116
@taoruifu 
please try this possible [solution](https://github.com/flutter/flutter/issues/69116#issuecomment-775765289)

**Comment by pedromassangocode** [comment] 2021-03-08 13:25
Hi @taoruifu 
Does the suggestion in the comment above solve this issue?
Thank you

**Comment by taoruifu** [comment] 2021-03-09 01:48
@pedromassangocode i tried the method,but still has this problem

**Comment by darshankawar** [comment] 2022-10-05 11:39
@taoruifu 
The channel you were when this error occurs (dev) has been removed from the framework.

Is there a way for you to confirm if this issue still occurs using latest stable version of the framework ?

`flutter channel stable`
`flutter upgrade`

**Closed** 2022-10-26 12:12 UTC
Labels: severe: crash, waiting for customer response, tool, platform-windows, passed first triage
