### ISSUE TITLE
flutter build ios crashes at BuildIOSCommand.runCommand: ArgumentError: Invalid argument(s)

### ISSUE THREAD

**Issue by jackstefansky** [flutter/flutter#28895] opened 2019-03-05 17:31 UTC
## command

flutter build ios

## exception

ArgumentError: Invalid argument(s)

```
#0      _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:842:9)
#1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:77:62)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Mac OS X 10.14 18A391, locale en-GB)
    [32m•[39m Flutter version 1.2.1 at /Users/jackstefansky/flutter
    [32m•[39m Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.


[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 3 categories.
```

**Comment by okalentiev** [comment] 2019-03-08 15:05
I experienced the same issue if the Flutter project was created as a module. I followed [this](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) steps to integrate Flutter into existing application. But now if I want to regenerate `.ios` folder it breaks. 

Is there any other setup or configuration required prior to calling `flutter build ios`?

**Comment by jmagman** [comment] 2019-10-17 00:12
Crash line:
```dart
printStatus('Building $app for $logTarget ($typeName)...');
```

**Comment by Partizann** [comment] 2019-11-11 11:38
I had the same issue and output. After reverting changes in project I found that this issue appeared when the Info.plist file was renamed and moved to another location (we need that because we have multiple targets and configurations). So crash was caused by attempt to open non-exising file. As a solution a've created a symlink named Info.plist in default location to concrete plist file.

**Comment by jmagman** [comment] 2020-05-08 01:37
@jackstefansky I know you filed this awhile ago, but are you seeing this in the latest Flutter stable?  There have been quite a few improvements in this area since you file this.

**Comment by jmagman** [comment] 2020-06-02 21:01
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-06-02 21:01 UTC
Labels: platform-ios, t: xcode, tool, waiting for customer response
