### ISSUE TITLE
[Tested on Windows] Cursor issues

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#84039] opened 2021-06-05 12:19 UTC
1. setState of a parent widget does not change the cursor until mouse is moved
![1cnMws8uRM](https://user-images.githubusercontent.com/63228361/120891369-fa892380-c610-11eb-9e2a-bc6e751f475b.gif)

2. exiting showMenu does not change the cursor until mouse is moved
![D2nmmehhrd](https://user-images.githubusercontent.com/63228361/120891399-25737780-c611-11eb-9a3a-37ad4f86833c.gif)

3. switching between widgets does not change the cursor until mouse is moved
![6dxx3yclvR](https://user-images.githubusercontent.com/63228361/120891436-518ef880-c611-11eb-825f-da4d66eb3b12.gif)

4. Hover the second sample, click on it and do not remove your finger from the mouse button. Move the cursor, stop holding the button and the cursor won't change even though it's no longer on a widget until mouse is moved again.
![RTg8MnrpuW](https://user-images.githubusercontent.com/63228361/120891896-bba89d00-c613-11eb-8c8c-5dcbdd35bf7c.gif)

Code sample with all three examples:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool isFirstActivated = true;
  void callback(bool isFirst) => setState(() => isFirstActivated = isFirst);

  bool showFirstContainer = true;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Row(
            children: [
              TestButton(isFirstActivated ? () => callback(false) : null),
              TestButton(!isFirstActivated ? () => callback(true) : null),
              SizedBox(width: 100.0),
              TestMenu(),
              SizedBox(width: 15.0),
              MouseRegion(
                cursor: SystemMouseCursors.help,
                child: Tooltip(
                  message: 'testMessage',
                  child: Text('ShowTooltip, sample #2, 4'),
                ),
              ),
              SizedBox(width: 100.0),
              Stack(
                children: <Widget>[
                  if(showFirstContainer)
                    GestureDetector(
                      onTap: () => setState(() => showFirstContainer = false),
                      child: MouseRegion(
                        cursor: SystemMouseCursors.precise,
                        child: Container(
                          color: Colors.yellow,
                          width: 200.0,
                          height: 50.0,
                          child: Text("sample #3"),
                        ),
                      ),
                    ),
                  if(!showFirstContainer)
                    GestureDetector(
                      onTap: () => setState(() => showFirstContainer = true),
                      child: MouseRegion(
                        cursor: SystemMouseCursors.forbidden,
                        child: Container(
                          color: Colors.deepOrange,
                          width: 200.0,
                          height: 50.0,
                          child: Text("sample #3"),
                        ),
                      ),
                    ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class TestMenu extends StatelessWidget {
  void _showMenu(BuildContext context, TapDownDetails details) {
    Size size = Size(979.0, 559.0);

    showMenu(
      context: context,
      position: RelativeRect.fromRect(
          details.globalPosition & Size(100, 100), Offset.zero & size),
      items: [
        PopupMenuItem(
          child: Text('test'),
        )
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTapDown: (details) => _showMenu(context, details),
      child: Text("ShowMenu, sample #2, 4"),
    );
  }
}

class TestButton extends StatefulWidget {
  final Function? callback;

  TestButton(this.callback);

  @override
  _TestButtonState createState() => _TestButtonState();
}

class _TestButtonState extends State<TestButton> {
  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      cursor: widget.callback != null
          ? SystemMouseCursors.click
          : MouseCursor.defer,
      child: GestureDetector(
        onTap: widget.callback != null ? () => widget.callback!() : null,
        child: Container(
          width: 150.0,
          height: 35.0,
          color: widget.callback != null ? Colors.red : Colors.green,
          child: Text("sample #1"),
        ),
      ),
    );
  }
}
```
Flutter version: 2.2.1 from Stable channel(provided code sample was also tested on master channel with version 2.3.0-17.0.pre.224)

**Comment by TahaTesser** [comment] 2021-06-07 11:13
Hi @kirill-21 
These are all single source issues
Closing as duplicate of https://github.com/flutter/flutter/issues/76622

**Closed by TahaTesser** 2021-06-07 11:13 UTC
Labels: in triage
