### ISSUE TITLE
Let's create a widget life cycle diagram and text for the website document of flutter

### ISSUE THREAD

**Issue by 120011676** [flutter/flutter#55803] opened 2020-04-28 01:13 UTC
Let's create a widget life cycle diagram and text for the website document of flutter

I need to listen to the event that the widget leaves (push the new one) and returns (pop comes back),not found

Notice that it corresponds to different classes and examples

**Comment by VladyslavBondarenko** [comment] 2020-04-28 08:57
Hi @120011676 ,
In the last link of https://flutter.dev/docs/development/ui/widgets-intro#responding-to-widget-lifecycle-events you can see the link to https://api.flutter.dev/flutter/widgets/State-class.html with detailed description of the widget lifecycle, isn't this enough?

**Comment by 120011676** [comment] 2020-05-07 06:05
@VladyslavBondarenko English is not good. I hope there are pictures,

I need to listen to the event that the widget leaves (push the new one) and returns (pop comes back),How to use

![image](https://user-images.githubusercontent.com/1992933/81259915-87a72500-906b-11ea-9cf5-b70ff048adf2.png)

**Comment by TahaTesser** [comment] 2020-05-07 10:01
Duplicate of [#39227](https://github.com/flutter/flutter/issues/39227)

**Closed by TahaTesser** 2020-05-07 10:01 UTC
Labels: in triage
