### ISSUE TITLE
Wrapping GestureDetector in a Tooltip widget causes onTapCancel 

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#84531] opened 2021-06-13 18:30 UTC
GestureDetector taps(wrapped with a Tooltip widget) longer than 0.6 seconds cause onTapCancel executing instead of onTapUp.

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Tooltip(message: 'test', child: DemoIconButton()),
      ),
    );
  }
}

class DemoIconButton extends StatefulWidget {
  @override
  _DemoIconButtonState createState() => _DemoIconButtonState();
}

class _DemoIconButtonState extends State<DemoIconButton> {
  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      child: GestureDetector(
        onTapDown: (_) => print('onTapDown'),
        onTapUp: (_) => print('onTapUp'),
        onTapCancel: () => print('onTapCancel'),
        child: Icon(
          Icons.phone_locked,
          color: Colors.purple,
        ),
      ),
    );
  }
}
``` 

</details>

Flutter version: 2.2.2 from the stable channel

**Comment by kirill-21** [comment] 2021-06-13 18:32
![lJkKUvorEG](https://user-images.githubusercontent.com/63228361/121818278-d2dc3000-cc8e-11eb-8e80-b1ddef91fe08.gif)

**Comment by danagbemava-nc** [comment] 2021-08-19 06:11
Hi, @kirill-21. Thanks for filing the issue. 
Can you please confirm if you are experiencing this issue on the latest stable version?

Thank you

**Comment by kirill-21** [comment] 2021-08-19 06:28
> Hi, @kirill-21. Thanks for filing the issue.
> Can you please confirm if you are experiencing this issue on the latest stable version?
> 
> Thank you

Yes, I am

**Comment by danagbemava-nc** [comment] 2021-08-19 06:32
Please provide the output of `flutter doctor -v`.

**Comment by kirill-21** [comment] 2021-08-19 07:58
> flutter doctor -v

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.2.3 at C:\Install\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\karnm\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Install\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Install\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Install\IntelliJ IDEA 2020.3.1
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7727

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1165]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2021-08-19 13:56
Issue is reproducible on `master 2.5.0-7.0.pre.155` and `stable 2.2.3`.

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.155, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.155 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff547a9234 (9 hours ago), 2021-08-19 01:17:04 -0400
    • Engine revision 9a54e9e05c
    • Dart version 2.15.0 (build 2.15.0-29.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```
</details>

<details>
<summary> logs</summary>

```console
flutter: onTapDown
flutter: onTapCancel
flutter: onTapDown
flutter: onTapCancel
flutter: onTapDown
flutter: onTapCancel
flutter: onTapDown
flutter: onTapCancel
```
</details>

**Comment by bleroux** [comment] 2022-04-19 12:55
`Tooltip` uses a GestureDetector and relies on its `onLongPress` callback.
If Tooltip child contains its own GestureDetector, this inner GestureDetector will lost in gesture arena for onTap and onLongPress events.

Some solutions :
- Improve documentation to state that inner GestureDetector in Tooltip will not win for `onLongPress` and `onTap`.
- Update `Tooltip` internals and replace its `GestureDetector` with a `Listener` or a `RawGestureDetector` with custom recognizers.

@HansMuller Which solution do you recommend ?

**Comment by kirill-21** [comment] 2022-05-18 21:20
> @kirill-21 On mobile, by default, a tooltip is shown after a long press. If the Tooltip wraps a widget that contains its own GestureDetector (for instance a button), it is expected that the Tooltip GestureDetector wins and the inner GestureDetector looses (and then executes its onTapCancel callback). On desktop it would make sense that the Tooltip shows only on hover (and does not create a GestureDetector). I filed an issue about this : #103703
> 
> Are you targeting mobile or desktop ?

My problem is with desktop application, sometimes you need to wrap an icon-button with tooltip widget to explain user what it does. In such cases this issue confuses people because they do not understand what happens

**Comment by bleroux** [comment] 2022-05-19 07:35
@kirill-21 
I too think this is not user friendly for Desktop apps. 
As I explained in #103703. showing Tooltip after a long press gesture is expected only on mobile.

I closed #103703, because I recently figured out that with `TooltipTriggerMode.manual` we can show Tooltip only when hovered. Doing so, the tooltip GestureDetector no more interferes with inner GestureDetectors.

And this can be set globally for a desktop app using `TooltipThemeData` :

<details>
<summary>Updated code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.fallback().copyWith(
        tooltipTheme: const TooltipThemeData(
          triggerMode: TooltipTriggerMode.manual,
        ),
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: const Tooltip(message: 'test', child: DemoIconButton()),
      ),
    );
  }
}

class DemoIconButton extends StatefulWidget {
  const DemoIconButton({super.key});

  @override
  State<DemoIconButton> createState() => _DemoIconButtonState();
}

class _DemoIconButtonState extends State<DemoIconButton> {
  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      child: GestureDetector(
        onTapDown: (_) => print('onTapDown'),
        onTapUp: (_) => print('onTapUp'),
        onTapCancel: () => print('onTapCancel'),
        child: const Icon(
          Icons.phone_locked,
          color: Colors.purple,
        ),
      ),
    );
  }
}



```
</details>

**Comment by kirill-21** [comment] 2022-05-19 09:49
> ```dart
> theme: ThemeData.fallback().copyWith(
>         tooltipTheme: const TooltipThemeData(
>           triggerMode: TooltipTriggerMode.manual,
>         ),
>       ),
> ```

Works almost good. But if you cause onTapCancel intentionally by moving the cursor inside the button(maybe user realizes that he does not want to click the button anymore after reading the tooltip), the tooltip is not shown again until you move your cursor somewhere outside this button and then inside again

**Comment by bleroux** [comment] 2022-05-19 10:15
it's interesting that you bring this as I wrote a comment about this behavior some hours ago : https://github.com/flutter/flutter/pull/103960#issuecomment-1130579370

The point here is to know what is expected by the Material spec and what would be user-friendly. For the moment this behavior is expected in Tooltip code and we might have to filed another issue to give more context and make it actionnable.

**Comment by bleroux** [comment] 2022-06-07 07:21
@kirill-21
I will close this issue as `TooltipTriggerMode.manual` is a solution for the onTapCancel callback being called.
Could you open a new issue about https://github.com/flutter/flutter/issues/84531#issuecomment-1131483123 ?
It would be interesting to have a comparison with your desktop targeted platform (Windows?).

**Closed by bleroux** 2022-06-07 07:21 UTC
Labels: framework, f: material design, has reproducible steps, P4, found in release: 2.2, found in release: 2.5
