### ISSUE TITLE
Support split screen on android

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#16021] opened 2018-03-28 11:46 UTC
Install Flutter Gallery.
Try to put into split view mode.
the OS will tel you that the app is not designed for Split Screen.

**Comment by jonahwilliams** [comment] 2018-03-28 17:48
Flutter does support split-screen, but the flutter gallery does not since `android:resizeableActivity="true"` is not in the AndroidManifest.

**Comment by jonahwilliams** [comment] 2018-03-28 17:49
See https://developer.android.com/guide/topics/ui/multi-window.html for more information.

**Comment by gedw99** [comment] 2018-03-28 19:58
Ok well thats a relief to know.
SO this issue is a request to update the manifest for Flutter gallery an
release  it so that me and others can test it.

**Comment by MrCsabaToth** [comment] 2021-03-21 10:47
So this ticket can be closed? I'd wonder about PIP support tho https://developer.android.com/guide/topics/ui/picture-in-picture - would require API level 26

**Comment by guidezpl** [comment] 2022-04-13 13:01
Confirmed split screen is currently working, closing.

**Closed by guidezpl** 2022-04-13 13:01 UTC
Labels: team, platform-android, team: gallery, a: fidelity, P4
