### ISSUE TITLE
Analyzer telling me to use const with --preview-dart-2 in IntelliJ

### ISSUE THREAD

**Issue by Pacane** [flutter/flutter#15023] opened 2018-03-01 15:00 UTC
## Steps to Reproduce

I've just removed all `new` and `const` from my components.

Here's what I get

![image](https://user-images.githubusercontent.com/2762440/36850902-e3348440-1d35-11e8-9660-8abd3146f2b7.png)

![image](https://user-images.githubusercontent.com/2762440/36850922-efa37ab0-1d35-11e8-91b4-e63d8419a2b6.png)

It works out of the box in most places, but there are still some places where I'd need to explicitly write `const`.

Update: Turns out I forgot about this rule in the linter:

`prefer_const_constructors`

I'm still wondering though. Is Flutter really not picking the right constructor, or is the linter just badly implemented for `--preview-dart-2`

## Logs

```
 ❯ flutter analyze --preview-dart-2                                                                                                                                                                                    [09:58:00]
Analyzing /home/joel/code/comiko...
  error • The class 'TickerProviderStateMixin' can't be used as a mixin because it extends a class other than Object at lib/account_drawer.dart:22:10 • mixin_inherits_from_not_object
  lint • Prefer const with constant constructors at lib/account_drawer.dart:53:14 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/pages/about_us_page.dart:9:18 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/pages/about_us_page.dart:12:20 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/pages/about_us_page.dart:16:21 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/pages/about_us_page.dart:53:16 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/pages/artist_page.dart:78:20 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/pages/artists_page.dart:19:20 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/pages/event_page.dart:97:29 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/pages/event_page.dart:108:23 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/widgets/artist_card.dart:38:26 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/widgets/datetime_item.dart:30:24 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/widgets/event_card.dart:49:21 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/widgets/event_card.dart:60:21 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/widgets/image_caching_loader.dart:47:25 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/widgets/image_caching_loader.dart:52:28 • prefer_const_constructors
  lint • Prefer const with constant constructors at lib/widgets/search_popup.dart:45:31 • prefer_const_constructors
17 issues found.
(Ran in 5.6s)
```

## Flutter Doctor

```
❯ flutter doctor -v                                                                                                                                                                                                   [09:51:30]
[✓] Flutter (Channel master, v0.1.8-pre.21, on Linux, locale en_CA.UTF-8)
    • Flutter version 0.1.8-pre.21 at /home/joel/code/flutter
    • Framework revision eaa9848fd4 (13 hours ago), 2018-02-28 17:53:38 -0800
    • Engine revision 6607231638
    • Dart version 2.0.0-dev.31.0.flutter-1aaebedd70

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_152-release"
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio
    • Java version openjdk version "1.8.0_152-release"

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /opt/intellij-idea-ue-eap
    • Flutter plugin version 20.0.3
    • Dart plugin version 181.2784.29

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4301.22

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by devoncarew** [comment] 2018-03-01 16:35
It's likely that that lint doesn't take into account optional const. /cc @pq @bwilkerson @a14n

**Comment by mit-mit** [comment] 2018-03-01 21:15
Were you editing one of our apps in /examples/, or an app created with `flutter create`? If the former, I think this is caused by extra lints being on inside our repo.

**Comment by Pacane** [comment] 2018-03-01 21:31
I have added those lints myself a while back, before the dart 2 preview came out.

**Comment by mit-mit** [comment] 2018-03-01 21:35
Got it. Yes, not sure if the linter fully understands inferred const?

**Comment by a14n** [comment] 2018-03-01 22:09
It's likely that `prefer_const_constructors` conflicts with implicit creation. Feel free to file a bug on https://github.com/dart-lang/linter.

**Comment by devoncarew** [comment] 2018-03-01 22:13
Closing in favor of https://github.com/dart-lang/linter/issues/910.

**Closed by devoncarew** 2018-03-01 22:13 UTC
Labels: dart2
