### ISSUE TITLE
venv setup during engine presubmits is flaky.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#75650] opened 2021-02-08 19:58 UTC
[This was reported](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8856442965017925856/+/steps/build_host_release/0/stdout) as a presubmit flake during `venv` setup.

The full error was:

```
[E2021-02-01T19:28:19.855394-08:00 55660 0 config.go:318] Failed to get runtime information:
         {"error":"signal: segmentation fault"}
[E2021-02-01T19:28:19.858041-08:00 55660 0 annotate.go:241] original error: signal: segmentation fault
[E2021-02-01T19:28:19.858089-08:00 55660 0 annotate.go:241] 
[E2021-02-01T19:28:19.858109-08:00 55660 0 annotate.go:241] goroutine 1:
[E2021-02-01T19:28:19.858133-08:00 55660 0 annotate.go:241] #0 go.chromium.org/luci/vpython/venv/config.go:319 - venv.fillRuntime()
[E2021-02-01T19:28:19.858149-08:00 55660 0 annotate.go:241]   reason: failed to get runtime information
[E2021-02-01T19:28:19.858163-08:00 55660 0 annotate.go:241] 
[E2021-02-01T19:28:19.858176-08:00 55660 0 annotate.go:241] #1 go.chromium.org/luci/vpython/venv/config.go:193 - venv.(*Config).makeEnv()
[E2021-02-01T19:28:19.858189-08:00 55660 0 annotate.go:241] #2 go.chromium.org/luci/vpython/venv/venv.go:163 - venv.With()
[E2021-02-01T19:28:19.858202-08:00 55660 0 annotate.go:241] #3 go.chromium.org/luci/vpython/run.go:62 - vpython.Run()
[E2021-02-01T19:28:19.858216-08:00 55660 0 annotate.go:241] #4 go.chromium.org/luci/vpython/application/application.go:320 - application.(*application).mainImpl()
[E2021-02-01T19:28:19.858245-08:00 55660 0 annotate.go:241] #5 go.chromium.org/luci/vpython/application/application.go:408 - application.(*Config).Main.func1()
[E2021-02-01T19:28:19.858271-08:00 55660 0 annotate.go:241] #6 go.chromium.org/luci/vpython/application/support.go:46 - application.run()
[E2021-02-01T19:28:19.858286-08:00 55660 0 annotate.go:241] #7 go.chromium.org/luci/vpython/application/application.go:407 - application.(*Config).Main()
[E2021-02-01T19:28:19.858301-08:00 55660 0 annotate.go:241] #8 vpython/main.go:109 - main.mainImpl()
[E2021-02-01T19:28:19.858318-08:00 55660 0 annotate.go:241] #9 vpython/main.go:115 - main.main()
[E2021-02-01T19:28:19.858364-08:00 55660 0 annotate.go:241] #10 runtime/proc.go:204 - runtime.main()
[E2021-02-01T19:28:19.858392-08:00 55660 0 annotate.go:241] #11 runtime/asm_amd64.s:1374 - runtime.goexit()
```

**Comment by godofredoc** [comment] 2021-02-11 23:09
This is a duplicate of https://github.com/flutter/flutter/issues/68322

**Closed by godofredoc** 2021-02-11 23:09 UTC
Labels: P2, passed first triage, team, team: infra, team: presubmit flakes
