### ISSUE TITLE
Never mind. I found out after all that this is caused by an IntrinsicWidth wrapper.

### ISSUE THREAD

**Issue by purutechno** [flutter/flutter#97661] opened 2022-02-02 18:43 UTC
Never mind. I found out after all that this is caused by an IntrinsicWidth wrapper.

_Originally posted by @footurist in https://github.com/flutter/flutter/issues/92591#issuecomment-953417550_

A/C :
- The menu needs to be full width of the screen, 

Proposed Solution :
- We need a bool setFullScreenWidth so that PopupMenuItem can take the entire available space,

PopupMenuItem<_AuthorInfo>(
                    padding: EdgeInsets.zero,
                    child: SizedBox(
                      width: double.maxFinite,
                      child:  myWidgetWithFullScreenWidth  ,
                      ),
                  ),

**Comment by darshankawar** [comment] 2022-02-03 06:55
@purutechno 
Please don't use comment as an issue title and open an issue like that. Please use new issue template (feature request or other as applicable) and fill out requested details so that we will have clear idea of what the issue is.
Closing for now, as the issue purpose isn't clear. Open a new issue using template so that it can be addressed properly.

**Closed by darshankawar** 2022-02-03 06:55 UTC
Labels: in triage
