### ISSUE TITLE
 CameraException(error, Attempt to invoke virtual method 'java.util.List android.media.EncoderProfiles.getVideoProfiles()' on a null object reference)

### ISSUE THREAD

**Issue by LEHOANGLONG0807** [flutter/flutter#118079] opened 2023-01-06 05:05 UTC
Bug: 
 CameraException(error, Attempt to invoke virtual method 'java.util.List android.media.EncoderProfiles.getVideoProfiles()' on a null object reference)
 
 Flutter version 3.3.8
 Android 13

**Comment by danagbemava-nc** [comment] 2023-01-06 07:51
Closing this as a duplicate of https://github.com/flutter/flutter/issues/109769. 

Kindly follow up in the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2023-01-06 07:51 UTC
Labels: in triage
