### ISSUE TITLE
[ImagePicker] When picking image from Google Photos gallery, after download nothing is returned to the app.

### ISSUE THREAD

**Issue by gbaccetta** [flutter/flutter#16927] opened 2018-04-24 12:32 UTC
using ImagePicker with source.gallery, when I choose to select a photo from Google Photos (using the left Hamburger Menu, if the photo is not stored locally, it is downloaded upon selection.
However flutter does not receive the uri of the donwloaded photo and crash with following error:

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/0/1/mediakey:/local%3A60016a40-64e1-418d-986c-e5ddb11b729f/ORIGINAL/NONE/1646755264 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A60016a40-64e1-418d-986c-e5ddb11b729f/ORIGINAL/NONE/1646755264} }} to activity {com.**************************************************************}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:48)
        at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:37)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleResult(ImagePickerDelegate.java:262)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChoosePictureResult(ImagePickerDelegate.java:230)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:217)
        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:194)
        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:122)
        at android.app.Activity.dispatchActivityResult(Activity.java:7266)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

I'm using ImagePicker 0.4.1

Flutter configuration
Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b397406561 (3 weeks ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

**Comment by zoechi** [comment] 2018-04-24 13:02
Please provide more details.

**Comment by gbaccetta** [comment] 2018-04-24 13:51
I edited my comment, I do not know why the body was missing. I maybe forgot to paste it since I often edit it on an editor. Sorry about that

**Comment by gbaccetta** [comment] 2018-04-29 19:01
just to give more info, it happens with any external source provided by the native image chooser (i.e. google drive, dropbox and others). Picture need to be on the device already

**Comment by gbaccetta** [comment] 2018-04-30 13:15
Actually creating a temp file from remote source input stream works correctly. If interested in my solution I created a pull request. 

just in case here is the code that I included:

        ```
        //replacing this:
        //String path = fileUtils.getPathFromUri(activity, data.getData());
        //handleResult(path);

        //with this: creating a temp file from uri to allow reading pictures from remote sources
        try {
            InputStream inputStream = null;
            OutputStream output = null;
            try {
                inputStream = activity.getContentResolver().openInputStream(data.getData());
                File file = new File(activity.getCacheDir(), "cachedImage.jpg");
                output = new FileOutputStream(file);
                if (inputStream != null) {
                    byte[] buffer = new byte[4 * 1024]; // or other buffer size
                    int read;
                    while ((read = inputStream.read(buffer)) != -1) {
                        output.write(buffer, 0, read);
                    }
                    output.flush();
                    handleResult(file.getPath());
                } else {
                    finishWithError("pickFromGalleryError", "Error while reading selected image");
                }
            } finally {
                if (output != null) output.close();
                if (inputStream != null) inputStream.close();
            }
        } catch (FileNotFoundException e) {
            finishWithError("pickFromGalleryError", "FileNotFoundException - Error while reading selected image");
        } catch (IOException e) {
            finishWithError("pickFromGalleryError", "IOException - Error while reading selected image");
        }
```

**Comment by adityasodhani** [comment] 2018-06-07 03:54
Did you guys find a fix yet?

**Comment by zoechi** [comment] 2018-06-07 03:56
I got the impression this was fixed. Can you please post the output of `flutter doctor`

**Comment by AndreHaueisen** [comment] 2018-06-13 22:37
I have the same problem when I select a photo from Google Drive that is not locally stored. The `File` returned is null.

- Flutter Doctor

[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!
Process finished with exit code 0

**Comment by zoechi** [comment] 2018-06-14 03:37
What version for `image_picker` is registered in `pubspeck.lock`?

**Comment by AndreHaueisen** [comment] 2018-06-14 13:34
Version 0.4.5

```
image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.5"
```

**Comment by zoechi** [comment] 2018-06-14 14:11
Sorry ,I thought that has long landed flutter/plugins#513
It's still work in progress.
I think this is a dup of #17165

**Comment by zoechi** [comment] 2018-06-14 14:13
@gbaccetta I'll close this as dup of #17165. Leave a comment to reopen if you don't agree.

**Closed by zoechi** 2018-06-14 14:13 UTC

**Comment by SkullEnemyX** [comment] 2018-06-19 23:11
Even I am facing this problem. Image picker from the gallery opens a menu for you to select the image but when you select from google photos...image does not appear but when the photo is taken from the local storage, image appears.

**Comment by satish754ss** [comment] 2018-07-26 12:46
Hi, 
I want to pick the image from the gallery!

**Comment by zoechi** [comment] 2019-01-15 09:12
@assafsl Looks like this URL `Unknown URI: content://downloads/public_downloads/1751` caused the issue. This issue is long closed.
Please create a new issue with a minimal reproduction project and the exact steps how to reproduce.
