### ISSUE TITLE
[Mac] Rubber band scrolling is not supported when scrolling with the touchpad in Mac OS

### ISSUE THREAD

**Issue by fanchou** [flutter/flutter#70275] opened 2020-11-11 07:47 UTC

**Comment by darshankawar** [comment] 2020-11-11 08:50
@fanchou 
Please elaborate on this issue. Is this specific to macOS desktop or mobile ?

**Comment by stuartmorgan** [comment] 2020-11-11 14:34
Duplicate of #23604. The reason it doesn't overscroll is that currently trackpad scrolling is treated as a series of scroll wheel events due to the lack of framework sorry for trackpad gestures.

**Closed by stuartmorgan** 2020-11-11 14:34 UTC
Labels: in triage, waiting for customer response
