### ISSUE TITLE
[google_maps_flutter_web] map does not update marker positions after change

### ISSUE THREAD

**Issue by alenas** [flutter/flutter#65255] opened 2020-09-04 17:21 UTC
Seems like map does not update marker position, after it changed.
Even your sample (https://dit-maps-tests.web.app/) has the same bug.
Steps to reproduce in the sample:
1. Click "Place marker"
2. Click "Add" button
3. Move map so marker would be off center.
3. Click on the new marker to select it.
4. Click "change position".
Nothing happens, as marker position is actually updated, but map does not show that.
![image](https://user-images.githubusercontent.com/1384236/92269050-13cb3b00-eeec-11ea-9409-e3f6b84a92bf.png)

**Comment by markusaksli-nc** [comment] 2020-09-07 09:53
Hi @alenas 
Could you please provide your `flutter doctor -v` logs. Did you test this using the latest versions of `google_maps_flutter` and `google_maps_flutter_web`?
Thank you

**Comment by alenas** [comment] 2020-09-07 10:10
google_maps_flutter: ^0.5.28
  google_maps_flutter_web: ^0.1.0

From doctor:
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19042.487], locale en-US)
    • Flutter version 1.21.0-9.2.pre at C:\Repos\flutter
    • Framework revision 81a45ec2e5 (11 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\tools\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\tools\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.44

! Doctor found issues in 1 category.

**Comment by markusaksli-nc** [comment] 2020-09-07 10:21
The issue seems valid from your sample and when testing with a non-signed maps widget on the latest master `1.22.0-10.0.pre.87` however, we don't have billing enabled yet so we can't fully confirm this. Marking for additional triage.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.87, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-10.0.pre.87 at C:\Development\flutter_master
    • Framework revision 4732a214a7 (2 days ago), 2020-09-04 21:05:02 -0400
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.83

• No issues found!
```
</details>

**Comment by alenas** [comment] 2020-09-07 10:26
Ok. I see this problem with billing enabled.

**Comment by Hixie** [comment] 2020-09-08 23:37
I do see the described behaviour with https://dit-maps-tests.web.app/#/, FWIW

**Comment by ramioooz** [comment] 2020-12-01 10:50
Hey @Hixie and @alenas 
I would like to look at the source/repository **code** of the flutter web google maps example
https://dit-maps-tests.web.app/#/FWIW

I can't find it around,
can you please share the link

Thank you

**Comment by alenas** [comment] 2020-12-01 23:12
@ramioooz I am not sure, but could be somewhere here: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example/lib

**Comment by ramioooz** [comment] 2020-12-02 07:33
> 
> 
> @ramioooz I am not sure, but could be somewhere here: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example/lib

hey @alenas 
yes, I can confirm the error now...
I am getting this error when updating an existing marker position :
```
Error: Expected a value of type 'String', but got one of type 'DivElement'
    at Object.throw_ [as throw] (http://localhost:50924/dart_sdk.js:4348:11)
    at Object.castError (http://localhost:50924/dart_sdk.js:4319:15)
    at Object.cast [as as] (http://localhost:50924/dart_sdk.js:4635:17)
    at dart.LegacyType.new.as (http://localhost:50924/dart_sdk.js:6212:60)
    at google_maps_flutter_web.MarkersController.new.[_changeMarker] (http://localhost:50924/packages/google_maps_flutter_web/src/types.dart.lib.js:1282:81)
    at _HashSet.new.forEach (http://localhost:50924/dart_sdk.js:38619:11)
    at google_maps_flutter_web.MarkersController.new.changeMarkers (http://localhost:50924/packages/google_maps_flutter_web/src/types.dart.lib.js:1274:39)
```

we will be looking for a solution to this. 
for the time being this simple workaround worked for me 👌: 

1. remove old marker by setting markers list/map to empty, then call `setState(() {})` to redraw your parent widget.
2. now this is **important**. before adding the marker again, have a delay of about 250 milliseconds. something like : `await Future.delayed(Duration(milliseconds: 250));`
3. then add a new marker with the new position by adding it to markers list/map, then `setState(() {})` again.

not the best solution though because you will have to call `setState(() {})` twice, but should get you going.

Thanks

**Comment by BoHellgren** [comment] 2021-01-10 10:47
@ramioooz I have the same problem. The workaround with two setStates works. But in addition to the user position marker, I have around 27 other markers on the map (showing locations of artworks) and now they all blink every 10 seconds when the two setStates run. Quite annoying. Looking forward to a fix for this bug. Or a better bypass.

**Comment by ditman** [comment] 2021-02-25 23:51
This has just been brought to my attention (in #75778); I'm going to close this ticket, but I'll work on this issue after our first wave of web null-safe plugins lands. I've prioritized this as a P3.

Thanks for the reports, and apologies for the delay responding to this issue, without the `platform-web` label it never showed up in the triage sessions I'm a part of!

**Closed by ditman** 2021-02-25 23:51 UTC
Labels: P4, p: first party, p: maps, plugin
