### ISSUE TITLE
Flutter Driver timeout trying to find widgets by ValueKey. "FlutterDriver: waitFor message is taking a long time to complete..."

### ISSUE THREAD

**Issue by earyzhe** [flutter/flutter#36244] opened 2019-07-16 07:06 UTC
## Steps to Reproduce

When running a flutter driver test the driver cannot find any widgets by ValueKey. I have also tried to find by type but this also does not work.

<img width="541" alt="Screenshot 2019-07-16 at 08 00 58" src="https://user-images.githubusercontent.com/26453863/61272943-3a865980-a7a0-11e9-83e7-b7ec3709b3f9.png">

<img width="585" alt="Screenshot 2019-07-16 at 08 02 12" src="https://user-images.githubusercontent.com/26453863/61272945-3b1ef000-a7a0-11e9-8cc0-f9a81733ee40.png">

<img width="817" alt="Screenshot 2019-07-16 at 08 01 37" src="https://user-images.githubusercontent.com/26453863/61272944-3b1ef000-a7a0-11e9-91dd-9f51f87be8f8.png">

<img width="455" alt="Screenshot 2019-07-16 at 08 02 33" src="https://user-images.githubusercontent.com/26453863/61272946-3bb78680-a7a0-11e9-8cd9-a6f8bb36bfeb.png">

## Logs

**Analyze**
```
Analyzing shutterstock_scroll...                                        
No issues found! (ran in 2.1s)
```

**Output of running `flutter doctor -v`**
```
earyzhe@MacBook-Pro-2:~/dev/FlutterProjects/shutterstock_scroll$ bin/drive flutter drive --target=test_driver/app.dart -v
Found multiple connected devices:
  - Android SDK built for x86
  - Andrew's iPhone

Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Initializing gradle...                                              0.7s
Resolving dependencies...                                           1.3s
Installing build/app/outputs/apk/app.apk...                         1.9s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         1.4s
Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter (12009): Observatory listening on http://127.0.0.1:39080/4gOezxK2p44=/
00:00 +0: (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:55707/4gOezxK2p44=/
[trace] FlutterDriver: Isolate found with number: 408400387
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:01 +0: Check flutter driver health
HealthStatus.ok
00:01 +1: Run smoke tests
Trying to find mainApp
[warning] FlutterDriver: waitFor message is taking a long time to complete...
00:31 +1 -1: Run smoke tests [E]
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  package:test_api/src/backend/invoker.dart 332:28              Invoker._handleError.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 330:10              Invoker._handleError
  package:test_api/src/backend/invoker.dart 283:9               Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 281:38              Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 947:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 21:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 382:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 172:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 946:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1191:21                                  _rootCreateTimer
  dart:async/zone.dart 1088:19                                  _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 280:34              Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 243:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 1516:10                                  _runZoned
  dart:async/zone.dart 1463:12                                  runZoned
  package:test_api/src/backend/declarer.dart 165:13             Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>

00:31 +1 -1: (tearDownAll)
00:31 +1 -1: Run smoke tests [E]
  DriverError: Failed to fulfill WaitFor due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #3      _rootRun (dart:async/zone.dart:1120:38)
  #4      _CustomZone.run (dart:async/zone.dart:1021:19)
  #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150:18)
  #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609:39)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:665:37)
  #8      Future._chainCoreFuture (dart:async/future_impl.dart:454:7)
  #9      Future._complete (dart:async/future_impl.dart:466:9)
  #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
  #11     ChannelManager.close (package:json_rpc_2/src/channel_manager.dart:74:22)
  #12     Client.close (package:json_rpc_2/src/client.dart:90:30)
  #13     Peer.close (package:json_rpc_2/src/peer.dart:124:28)
  #14     VMServiceClient.close (package:vm_service_client/vm_service_client.dart:185:27)
  #15     FlutterDriver.close (package:flutter_driver/src/driver/driver.dart:1018:25)
  <asynchronous suspension>
  #16     main.<anonymous closure> (file:///Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/test_driver/app_test.dart:15:26)
  <asynchronous suspension>
  #17     new Future.sync (dart:async/future.dart:224:31)
  #18     errorsDontStopTest.<anonymous closure> (package:test_api/src/util/test.dart:21:12)
  #19     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
  <asynchronous suspension>
  #20     _rootRun (dart:async/zone.dart:1124:13)
  #21     _CustomZone.run (dart:async/zone.dart:1021:19)
  #22     _runZoned (dart:async/zone.dart:1516:10)
  #23     runZoned (dart:async/zone.dart:1463:12)
  #24     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
  #25     errorsDontStopTest (package:test_api/src/util/test.dart:20:19)
  #26     Declarer._tearDownAll.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:308:19)
  <asynchronous suspension>
  #27     _rootRun (dart:async/zone.dart:1124:13)
  #28     _CustomZone.run (dart:async/zone.dart:1021:19)
  #29     _runZoned (dart:async/zone.dart:1516:10)
  #30     runZoned (dart:async/zone.dart:1463:12)
  #31     Invoker.unclosable (package:test_api/src/backend/invoker.dart:267:12)
  #32     Declarer._tearDownAll.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:306:32)
  #33     _rootRun (dart:async/zone.dart:1124:13)
  #34     _CustomZone.run (dart:async/zone.dart:1021:19)
  #35     _runZoned (dart:async/zone.dart:1516:10)
  #36     runZoned (dart:async/zone.dart:1463:12)
  #37     Declarer._tearDownAll.<anonymous closure> (package:test_api/src/backend/declarer.dart:305:14)
  #38     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
  <asynchronous suspension>
  #39     new Future.<anonymous closure> (dart:async/future.dart:176:37)
  #40     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #41     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #42     _rootRun (dart:async/zone.dart:1120:38)
  #43     _CustomZone.run (dart:async/zone.dart:1021:19)
  #44     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #45     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #46     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #47     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #48     _rootRun (dart:async/zone.dart:1124:13)
  #49     _CustomZone.run (dart:async/zone.dart:1021:19)
  #50     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
  #51     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
  #52     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
  #53     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
  #54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


  package:flutter_driver/src/driver/driver.dart 426:7   FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                     _Completer.completeError
  dart:async-patch/async_patch.dart 40:18               _AsyncAwaitCompleter.completeError
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                          _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 86:23               _asyncErrorWrapperHelper
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 464:11  FlutterDriver.waitFor
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart            Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 250:15      Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                          _CustomZone.registerCallback
  dart:async/zone.dart 962:22                           _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                           new Timer
  dart:async/timer.dart 87:9                            Timer.run
  dart:async/future.dart 174:11                         new Future
  package:test_api/src/backend/invoker.dart 399:21      Invoker._onRun.<fn>.<fn>.<fn>

00:31 +1 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Stopping application instance.
Driver tests failed: 255
```

**Comment by MisterJimson** [comment] 2019-07-16 18:57
Im also running into this

**Comment by psycura** [comment] 2019-07-19 08:07
Me to

**Comment by rockingdice** [comment] 2019-08-31 17:22
Me too. I don't know if this is related to :
https://github.com/flutter/flutter/issues/24795

My situation is taking screenshots for a widget using ui.image. The screenshots cannot be taken and it hangs up there forever.

**Comment by jonsamwell** [comment] 2019-09-10 06:14
I am seeing the same thing but only on a build server not locally

**Comment by BondarenkoStas** [comment] 2019-09-27 00:43
@earyzhe Please do not include screenshots of code. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example. Please provide it as text here.

**Comment by earyzhe** [comment] 2019-09-27 05:22
@BondarenkoStas ok well, I thought the colors would make it easier for you guys. Anyway, the repo is here if it helps: https://github.com/earyzhe/shutterstock_scroll

**Comment by BondarenkoStas** [comment] 2019-09-27 21:13
@earyzhe Thank you! For future, we can see syntax highlight after wrapping the code into triple backticks with type https://help.github.com/en/articles/creating-and-highlighting-code-blocks:)

**Comment by natanloterio** [comment] 2019-12-11 19:02
Guys, any update about this issue?

**Comment by natanloterio** [comment] 2019-12-18 13:08
@BondarenkoStas , any clue about how to solve this issue?

**Comment by belaad** [comment] 2019-12-27 04:49
Bump up! I am also trying to integration test and getting this!

**Comment by nyarian** [comment] 2019-12-30 08:27
Same here
Env: Ubuntu 18.04, x64, Flutter v1.12.13+hotfix.5
Targets: Xiaomi Redmi Note 7 (Android 9, MIUI 11.0.4.0), Nexus 6P (Android 8.1.0), several pure emulators (Pixel 2 API), both x86 and x64

The driver just hangs out and gives me timeout error after 30 seconds when awaiting for any of the driver's methods (e.g. `await driver.getText(finder)`, `await driver.tap(finder)`, etc.`)

Still, `FlutterDriver.connect()` itself seems to be completely operational. 

App that's being tested - basic autogenerated counter sample.

Test itself:

test_driver/app.dart:

`import 'package:flutter_driver/driver_extension.dart';
import 'package:flutter_project_app/main.dart' as app;

void main() {

  enableFlutterDriverExtension();

  app.main();
}`

test_driver/app_test.dart:

`import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('Counter App', () {
    // First, define the Finders and use them to locate widgets from the
    // test suite. Note: the Strings provided to the `byValueKey` method must
    // be the same as the Strings we used for the Keys in step 1.

    FlutterDriver driver;

    // Connect to the Flutter driver before running any tests.
    setUpAll(() async {
      print("Getting driver...");
      driver = await FlutterDriver.connect();
      print("Got driver!");
    });

    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      print("Closing driver...");
      driver?.close();
      print("Closed driver!");
    });

    test('starts at 0', () async {
      // Use the `driver.getText` method to verify the counter starts at 0.
      print("Starting startsAt0 test");
      final counterTextFinder = find.byValueKey('counter');
      String actual = await driver.getText(counterTextFinder);
      expect(actual, "0");
      print("Ended startsAt0 test");
    });

    test('increments the counter', () async {
      // First, tap the button.
      print("Starting increment test");
      print("Tapping the button...");
      final buttonFinder = find.byValueKey('increment');
      await driver.tap(buttonFinder);
      print("Button was tapped!");

      print("Verifying that text changed...");
      // Then, verify the counter text is incremented by 1.
      final counterTextFinder = find.byValueKey('counter');
      expect(await driver.getText(counterTextFinder), "1");
      print("Verification complete!");
    });
  });
}`

pubspec, just in case:

`name: flutter_project_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
`

Here are the errors' logs:

> flutter drive --target=test_driver/app.dart
Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Installing build/app/outputs/apk/app.apk...                         1.5s
I/flutter ( 4703): Observatory listening on http://127.0.0.1:43805/OurRr7J2xBg=/
I/flutter ( 6390): Observatory listening on http://127.0.0.1:35030/uXysth6lDs0=/
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         1.5s
✓ Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter ( 6531): Observatory listening on http://127.0.0.1:40086/I_IogRKrJA4=/
00:00 +0: Counter App (setUpAll)

Getting driver...

[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:43107/I_IogRKrJA4=/
[trace] FlutterDriver: Isolate found with number: 3496726565571303
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
Got driver!

00:00 +0: Counter App starts at 0

Starting startsAt0 test

[warning] FlutterDriver: get_text message is taking a long time to complete...
00:30 +0 -1: Counter App starts at 0 [E]

  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.

  **Long boring stacktrace**

00:30 +0 -1: Counter App increments the counter

Starting increment test

Tapping the button...

[warning] FlutterDriver: tap message is taking a long time to complete...
01:00 +0 -2: Counter App increments the counter [E]

  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.

  **Another boring stacktrace**

01:01 +0 -2: Counter App (tearDownAll)

Closing driver...

Closed driver!

01:01 +0 -2: Counter App starts at 0 [E]

  DriverError: Failed to fulfill GetText due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:

  **Yet another boring stacktrace**

01:01 +0 -2: Counter App increments the counter [E]

  DriverError: Failed to fulfill Tap due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:

  **Yet another...**

**Comment by akaGelo** [comment] 2019-12-30 11:27
if you have animations, flutter driver wait her complete and timeout...

*progress bar* is animation 

please try unsynchronized call and see https://github.com/flutter/flutter/issues/24703 

```dart
  await driver.runUnsynchronized(() async {
          final buttonFinder = find.byValueKey('increment');
          await driver.tap(buttonFinder);
      });

```

**Comment by if316030** [comment] 2020-04-14 04:05
Guys, any update for this issue?
thankyou

**Comment by heypran** [comment] 2020-04-17 11:27
ran into same issue... i could not find a solution.

**Comment by RajeshPerth** [comment] 2020-05-04 17:25
I have the same problem. I found one solution that might help you.
1. Close project and simulator.
2. Reopen the project and simulator, but make sure to wipe the data (cache) in the simulator.
<img width="1005" alt="Screen Shot 2020-05-05 at 1 23 39 am" src="https://user-images.githubusercontent.com/32253057/80994320-1864e180-8e6f-11ea-8059-d7017bb1f78a.png">

3. run the project before run the test.

**Comment by agordeev** [comment] 2020-05-08 13:29
Any updates? Seems like a real issue.

**Comment by RajeshPerth** [comment] 2020-05-09 09:54
Hi Agordeev,
Please try a few things. Maybe you do not need all, but you can try one by one.
1.  Clear the timeline at the beginning of the test.
2. Enclose tap in runUnsynchronised() method.
3. Give some delay after tap. (so you can also see what happened after tap).
4. increase the overall timeout for test
See my code below for an explanation.
let me know if this work

![Screen Shot 2020-05-09 at 5 47 33 pm](https://user-images.githubusercontent.com/32253057/81470562-f1ffc700-921d-11ea-8fe8-7d09792b9d7b.png)

**Comment by phanirithvij** [comment] 2020-06-03 15:10
I'm encountering this on a real device any way to resolve this?

**Comment by dnfield** [comment] 2020-07-23 19:24
I believe this will be fixed by https://github.com/flutter/flutter/pull/61841 - unfortunately, the supplied repo no longer compiles (seems like it refers to things in maven that don't exist anymore, and on iOS the podfile has issues).

**Comment by dnfield** [comment] 2020-07-24 23:09
Since I can't reproduce this and I believe https://github.com/flutter/flutter/pull/61841 fixed it, I'm going to close.

If someone has a reproduction that still happens after https://github.com/flutter/flutter/pull/61841, please feel free to ping this or file a new issue linked to this one.

**Closed by dnfield** 2020-07-24 23:09 UTC
Labels: t: flutter driver, tool
