### ISSUE TITLE
Improve fallback font handling on Linux

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30700] opened 2019-04-08 16:26 UTC
It's common for people running the shell to have missing text; https://github.com/google/flutter-desktop-embedding/issues/57 and https://github.com/google/flutter-desktop-embedding/issues/212 are two examples, but it's come up several other times as well.

We should ensure that the default font fallback handling for Linux has reasonably good behavior with the default fonts on popular distros (and potentially improve logging).

**Comment by stuartmorgan** [comment] 2019-04-08 20:32
As part of this we need a solution for emoji handling; see https://github.com/google/flutter-desktop-embedding/issues/90 and https://github.com/flutter/flutter/issues/17786

**Comment by schmidp** [comment] 2019-09-24 16:39
Happens on my Ubuntu 18.04.3 LTS Desktop as well. No fonts unless specified in the pubspec.yaml
BTW, specifying them like this:

```
fonts:
    - family: 'Roboto'
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf 
    - family: ''
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf 
```

"breaks" flutter web on the otherhand, fonts that should be thin, become bold.

**Comment by franciscojma86** [comment] 2019-10-12 01:28
On Linux, we are not using fontconfig by default, to find all the platform fallback fonts. Instead, a very simple font manager is used (based on a file system lookup to `usr/share/fonts`), that doesn't have the capacity to search for more fonts, if the desired font is not found. So it's likely that people experiencing "missing text" issues are due to not having Roboto installed, and Skia not knowing where to fallback. 

There is a flag `--enable-fontconfig` that will allow for a font manager to use fontconfig, and things work as expected. If Roboto is not found, it queries the system for its default fonts. 

This is the same case with emojis. The fontconfig enable manager is able to lookup fonts per character if a glyph is not found. However, this doesn't guarantee that the best font will be picked. In my tests using emojis, the app would display the wrong type of glyph, since it was using the wrong font.
For this, developers should bundle their emoji fonts, and add them as a [fallback font to a TextStyle](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/text_style.dart#L496). This way, a Text widget that has text and emojis, will be able to use the desired font, and fallback to the right emoji font. This is a relatively new feature.

Maybe we should enable fontconfig in our compiled binaries, but that introduces another dependency that Linux distros are not guaranteed to have. We should definitely make it very clear that it is specially important for apps to ship their fonts on Linux, as fallbacks are not 100% guaranteed. 

cc/ @jason-simmons and @GaryQian that helped me investigate this issue. Please let me know if I missed something :)

**Comment by stuartmorgan** [comment] 2019-10-12 01:50
> We should definitely make it very clear that it is specially important for apps to ship their fonts on Linux

One issue is that there's no way at far as I know to skip fonts for only one platform, so for a multi-platform app (especially if that includes mobile) that can be a pretty large hammer.

Maybe we could consider having a specific extra location relative to the executable that we check for fonts? That could allow Linux packaging to add fonts just for Linux.

**Comment by schmidp** [comment] 2020-01-31 12:46
Any progress on this? including the fonts for linux makes a cross-ui project have fat/strange fonts in web.
For our project this is currently the last issue where we can run the project on linux, windows, mac, ios, android, web

**Comment by stuartmorgan** [comment] 2020-02-01 00:55
> Any progress on this?

Nobody is currently working on this, so no. Please see ["when will my bug be fixed"](https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed).

**Comment by MarcusTomlinson** [comment] 2020-02-11 18:28
@stuartmorgan, could you assign this to me, I'll take a look at this.

**Comment by stuartmorgan** [comment] 2020-02-11 18:29
@franciscojma86 Can you drop a pointer here to the font fallback code in the engine as a starting point?

**Comment by franciscojma86** [comment] 2020-02-12 19:14
The engine uses the Skia font managers to get the right fonts. The logic for that is in this file: https://github.com/flutter/engine/blob/master/third_party/txt/src/txt/font_collection.cc

There is a per-platform fallback in case no font is found at all. The one for Linux is here: 
https://github.com/flutter/engine/blob/master/third_party/txt/src/txt/platform_linux.cc

@jason-simmons and @GaryQian have more context on how this works.

**Comment by franciscojma86** [comment] 2020-02-12 19:15
I believe the actual fallback logic is here: https://github.com/flutter/engine/blob/master/third_party/txt/src/txt/font_collection.cc#L130

**Comment by stuartmorgan** [comment] 2020-03-05 06:11
https://github.com/flutter/engine/pull/16928 should substantially improve this; having no text at all should hopefully be a rare case now. I think the only remaining step is to figure out if we can reasonably query the system font instead of using a hard-coded list.

**Comment by schmidp** [comment] 2020-03-05 08:15
we just tried the new commit, just wanted to give feedback that it works on our ubuntu based systems :) (sorry again for the "Any progress on this?" question)

**Comment by gspencergoog** [comment] 2020-03-05 08:59
In looking into this, we don't think there's actually a better way to do this in a cross-distro/cross-window toolkit kind of way.  Even if we tried to support multiple windowing toolkits, it might not even work, since the libraries might not even be installed. And even if we find a setting for a toolkit, we're not guaranteed that they are even running the toolkit that uses it.

As a concrete example, I implemented lookup of the default font from Gtk, and I was running Cinnamon.  It reported a font that wasn't even installed on my system, and it didn't match the setting in the environment I was running. It was correct for the setting, but I wasn't running GNOME at the moment, so it was just wrong.

Given that, we'd have to implement support for figuring out which of many toolkits/window managers were in use, what the default font is for each of the ones we wanted to support, whether that font is installed, and the right version of default font (e.g. should it use the "document" font, or the "title" font?). And all of this would need to be updated for each new environment we decided to support.

So, since it's likely that we wouldn't actually have any way to find out the default font "correctly", a static list is probably the best we can do.

**Comment by stuartmorgan** [comment] 2020-03-10 19:18
@franciscojma86 is there anything we can do to make default font fallback work for emoji? E.g., if there were a good emoji font commonly available, would adding it to the hard-coded fallback list mean that emoji would do something reasonable out of the box due to the per-glyph lookup you mentioned?

(Assuming there is such a font commonly available on Linux...)

**Comment by stuartmorgan** [comment] 2020-08-03 16:29
Per the bug linked just above, in addition to emoji we're not getting enough coverage of non-western languages with the current list.

**Comment by stuartmorgan** [comment] 2020-08-03 19:21
@kenvandine @robert-ancell Do you happen to know what fonts are used to handle various non-western languages by default on Ubuntu? Is it Noto, or something else? (Ubuntu isn't the only case we want to handle, but it would be a good starting point.)

**Comment by robert-ancell** [comment] 2020-08-17 04:03
> @kenvandine @robert-ancell Do you happen to know what fonts are used to handle various non-western languages by default on Ubuntu? Is it Noto, or something else? (Ubuntu isn't the only case we want to handle, but it would be a good starting point.)

There are a number of Font packages installed by default, the following is the dependencies on the 'ubuntu-desktop' package. It appears that only the Noto fonts for CJK and emoji are installed by default (the others are available in the archive).

Depends:
fonts-dejavu-core
fonts-freefont-ttf

Recommended:
fonts-indic
fonts-kacst-one
fonts-khmeros-core
fonts-lao
fonts-liberation
fonts-liberation2
fonts-lklug-sinhala
fonts-noto-cjk
fonts-noto-color-emoji
fonts-opensymbol
fonts-sil-abyssinica
fonts-sil-padauk
fonts-thai-tlwg
fonts-tibetan-machine
fonts-ubuntu

**Comment by robert-ancell** [comment] 2021-01-12 18:50
It seems like the solution to this is to provide the (ordered) list of available system fonts in the same way that GTK uses them (from fontconfig?).

**Comment by stuartmorgan** [comment] 2021-01-12 18:58
IIRC we discussed that back in the initial sprint and the issue was that there wasn't something generic (i.e., not assuming GTK) that we could talk to in the engine code that controls the fallback.

**Comment by robert-ancell** [comment] 2021-01-13 01:52
> IIRC we discussed that back in the initial sprint and the issue was that there wasn't something generic (i.e., not assuming GTK) that we could talk to in the engine code that controls the fallback.

Right, and perhaps a solution would be to use a channel (`flutter/settings`?) to send this list to the engine.

**Comment by robert-ancell** [comment] 2021-01-13 03:33
I tried this with the following example program:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
	// This widget is the root of your application.
	@override
	Widget build(BuildContext context) {
		return MaterialApp(
			title: 'Flutter Demo',
			home: Material(
				child: Center(
					child: Text("TEST শান্তনু বেরা 🐧")
				),
			),
		);
	}
}
```

I confirmed that the Bengali text and the Emoji didn't show. I updated the `GetDefaultFontFamilies` list in `third_party/txt/src/txt/platform_linux.cc` to add the appropriate fonts for these glyphs, however it appears this function is not being called - it is called when the program exits and not before the `Text` widget is rendered. Is this code functioning correctly @gspencergoog?

![Screenshot from 2021-01-13 16-26-11](https://user-images.githubusercontent.com/126560/104402980-66b0af80-55bc-11eb-9d8d-7030d92dc4a0.png)

I then build the engine with fontconfig support (`./tools/gn --unoptimized --enable-fontconfig`) and this caused the Bengali text to show and the Emoji to render (though the Emoji was not in colour).

![Screenshot from 2021-01-13 16-27-06](https://user-images.githubusercontent.com/126560/104402989-6e705400-55bc-11eb-95f1-88ac8cfee565.png)

I can't see a reason why we wouldn't build the engine on Linux with the fontconfig dependency as @franciscojma86 suggested. We already depend on GTK which depends on fontconfig (required via pango and optionally required in GTK if compiled with X11 support).

**Comment by stuartmorgan** [comment] 2021-01-13 16:16
> I can't see a reason why we wouldn't build the engine on Linux with the fontconfig dependency as @franciscojma86 suggested. We already depend on GTK which depends on fontconfig (required via pango and optionally required in GTK if compiled with X11 support).

If our desktop embedding already requires `fontconfig`, then turning it on for that embedding's build SGTM.

**Comment by robert-ancell** [comment] 2021-01-13 22:44
If we accept the fontconfig change, there will be a follow up issue about the emoji not being in colour. I know GTK required modifications to make this work, so there will be something similar required for Flutter/Skia.

**Comment by robert-ancell** [comment] 2021-02-02 03:34
Opened #75188 to track color Emoji issue.

**Comment by cbracken** [comment] 2021-03-16 18:47
Closing in favour of the emoji issue #75188, which we believe is the main remaining issue here.

**Closed by cbracken** 2021-03-16 18:47 UTC
Labels: P4, a: desktop, a: quality, a: typography, engine, passed first triage, platform-linux
