### ISSUE TITLE
There is a blank area between the appbar and the body

### ISSUE THREAD

**Issue by itMcdull** [flutter/flutter#40947] opened 2019-09-20 07:19 UTC
![image](https://user-images.githubusercontent.com/40596015/65307286-083b1300-dbba-11e9-8d3a-bb29a22a32db.png)

**Comment by kenthinson** [comment] 2019-09-20 08:07
It's not a blank space it's the AppBar's shadow. You can turn it off with the elevation property.
AppBarTheme(
      elevation: 0, // This removes the shadow from all App Bars.
    )

**Comment by itMcdull** [comment] 2019-09-20 08:16
> I believe it's not a blank space it's the AppBar's shadow. You can turn it off with the elevation property.
> AppBarTheme(
> elevation: 0, // This removes the shadow from all App Bars.
> )

This is not a shadow,It is the real spacing 
 AppBarTheme(
elevation: 0 // Not effective
)

**Comment by BondarenkoStas** [comment] 2019-09-20 11:47
Different, but still similar issue #40939.
@itMcdull can you paste here your code example to reproduce it, and your ```flutter doctor -v``` output?

**Comment by itMcdull** [comment] 2019-09-21 02:33
````
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 0, 
        backgroundColor: Color(0xff2196f3),
      ),
      body: Container(
        height: 200,
        color:  Color(0xff2196f3),
      ),
    );
  }
````
![image](https://user-images.githubusercontent.com/40596015/65366787-fa899a00-dc5a-11e9-97d9-f8d86df0f075.png)
![image](https://user-images.githubusercontent.com/40596015/65366803-33297380-dc5b-11e9-90b8-2b2704d437a5.png)

**Comment by Dinosane2** [comment] 2019-12-26 15:34
This problem it confirmed happening in

Flutter 1.13.6-pre.23 • channel master  and  Flutter 1.12.13+hotfix.5 • channel stable

And it is a real "space between". You can check adding a background color to Scaffold:

@override
  Widget build(BuildContext context) {
    return Scaffold(
       backgroundColor: Colors.orange,
      appBar: AppBar(
        elevation: 0, 
        backgroundColor: Color(0xff2196f3),
      ),
      body: Container(
        height: 200,
        color:  Color(0xff2196f3),
      ),
    );
  }

**Comment by ding-zou** [comment] 2020-04-12 05:23
the properties of Scaffold "extendBodyBehindAppBar" may can solve this 
![image](https://user-images.githubusercontent.com/38654563/79061252-bfb38600-7cc0-11ea-93e4-66744f2b260a.png)

**Comment by once10301** [comment] 2020-05-07 03:13
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Color(0xff2196f3),
      ),
      body: Container(
        transform: Matrix4.translationValues(0, -1, 0),
        height: 200,
        color:  Color(0xff2196f3),
      ),
    );
  }

**Comment by chcarmen** [comment] 2020-05-23 11:55
This issue still exsits now in the  latest flutter 1.17.  
 
are there any solutions for it?

**Comment by iapicca** [comment] 2020-05-25 09:53
Hi all,
the issue occur with the latest master,
tested with the code from this [issue](https://github.com/flutter/flutter/issues/57881)

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.19.0-2.0.pre.143, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-2.0.pre.143 at /Users/nevercode/development/flutter_master
    • Framework revision 9d58a87066 (2 days ago), 2020-05-22 22:37:01 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

[Screenshot](https://user-images.githubusercontent.com/45637986/82801942-c4a25280-9e86-11ea-8339-d76a74549a03.png)

**Comment by itMcdull** [comment] 2020-05-25 10:07
> 大家好，
> 这个问题发生在最新的master上，
> 并已使用此[问题中](https://github.com/flutter/flutter/issues/57881)的代码进行了测试[](https://github.com/flutter/flutter/issues/57881)
> 
> 医生
> [屏幕截图](https://user-images.githubusercontent.com/45637986/82801942-c4a25280-9e86-11ea-8339-d76a74549a03.png)

How to deal with it? I rewrote Appbar and solved

**Comment by tomakazu** [comment] 2020-06-04 19:46
I am trying to create a frame of spotify. By making elevation : 0 worked for me.

**Comment by surhidamatya** [comment] 2020-08-31 07:59
```
 return Scaffold(
      appBar: AppBar(
        elevation: 0,
)
)
```

even after adding this code it did not resolved the issue

**Comment by iapicca** [comment] 2020-10-02 14:33
possibly related to https://github.com/flutter/flutter/issues/22056

**Comment by ErickPariseVitorassi** [comment] 2021-01-21 01:37
My temporary solution for this: create an AppBar with shadow with the background color in the shadow color

**Comment by darshankawar** [comment] 2021-01-27 11:45
Verified this issue on latest stable and master using this code sample, https://github.com/flutter/flutter/issues/40947#issuecomment-533760734 and didn't see the blank area / white spacing between appbar and the body.

<img width="543" alt="Screenshot 2021-01-27 at 4 45 54 PM" src="https://user-images.githubusercontent.com/67046386/105986533-13158a00-60c3-11eb-8ccc-bd884931b6ed.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • SM A260G (mobile)      • 5200763ebcfa861f • android-arm • Android 8.1.0
      (API 27)
    • emulator-5554 (mobile) • emulator-5554    • android-x86 • Android 4.1.2
      (API 16) (emulator)

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 1.26.0-13.0.pre.177, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-13.0.pre.177 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 2eeeba9c09 (29 hours ago), 2021-01-25 20:52:30 -0800
    • Engine revision 6e391c5942
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)      • 5200763ebcfa861f • android-arm    • Android 8.1.0
      (API 27)
    • emulator-5554 (mobile) • emulator-5554    • android-x86    • Android 4.1.2
      (API 16) (emulator)
    • macOS (desktop)        • macos            • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)           • chrome           • web-javascript • Google Chrome
      88.0.4324.96

! Doctor found issues in 1 category.

```

</details>

Going ahead and closing this as fixed. If anybody disagrees, write in comment and I'll reopen.
Thanks.

**Closed by darshankawar** 2021-01-27 11:45 UTC
Labels: P4, a: quality, customer: crowd, f: material design, found in release: 1.19, framework, has reproducible steps

**Comment by joharputr** [comment] 2021-03-03 02:16
hello, did anyone have solved this bug?

**Comment by joharputr** [comment] 2021-03-03 02:32
i solved this , set the   preferredSize: const Size.fromHeight(0.0), and use toolbarHeight

  appBar: AppBar(
                backgroundColor: ColorPrimary,
                elevation: 0,
                centerTitle: true,
                toolbarHeight: 80,
                bottom: PreferredSize(
                  preferredSize: const Size.fromHeight(0.0),
                  child: Theme(

**Comment by Sameerkash** [comment] 2021-03-21 17:29
This is still happening, please investigate, just can't accomplish the design which connects the AppBar and scaffold. 







![Screen Shot 2021-03-21 at 10 56 10 PM](https://user-images.githubusercontent.com/40424087/111914606-a2726480-8a98-11eb-96a7-bada9c24ac44.png)

<details>
```

[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-US)
    • Flutter version 2.1.0-12.2.pre at /Users/sameerkashyap/Documents/Development/flutter
    • Framework revision 5bedb7b1d5 (4 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sameerkashyap/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM M405F (mobile) • RZ8M62KF2VV • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.0.1 20B50 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 89.0.4389.90
• No issues found!
```
</details>

**Comment by tfannoush** [comment] 2021-05-26 13:15
I'm facing this issue as well, tried all the solutions suggested above... though adding the backgroundColor property to the Scaffold solved the issue, it didn't solve it for me because I'm using a bottomNavigationBar that would take the Scaffold's backgroundColor as I am trying to give that a different background colour.
