### ISSUE TITLE
Android: Hot Reload (pressing little-r) Crashes the App 

### ISSUE THREAD

**Issue by dvdwasibi** [flutter/flutter#8465] opened 2017-02-28 18:31 UTC
## Steps to Reproduce

As of a few days ago, hot reload (by typing little-r) consistently crashes the Android Flutter application.

@apwilson is also seeing this.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/dayang/fuchsia/lib/flutter
    • Framework revision 0533ffc020 (64 minutes ago), 2017-02-28 18:25:28
    • Engine revision 0edcbb7db4
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/dayang/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_111-b14)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    ✗ ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    ✗ ios-deploy not installed: install via 'brew install ios-deploy'.

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.3)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.8.1

[✓] Connected devices
    • Pixel C • 6119001907 • android-arm • Android 7.0 (API 24)

**Comment by goderbauer** [comment] 2017-02-28 18:43
Thanks for the report. I think this is a duplicate of https://github.com/flutter/flutter/issues/8451. Can you confirm that you have the same setup as described in https://github.com/flutter/flutter/issues/8451#issuecomment-283123212?

**Comment by dvdwasibi** [comment] 2017-02-28 18:49
@goderbauer done

**Comment by goderbauer** [comment] 2017-02-28 18:56
Closing as duplicate.

**Closed by goderbauer** 2017-02-28 18:56 UTC
