### ISSUE TITLE
CRASH si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x0     

### ISSUE THREAD

**Issue by prasant10050** [flutter/flutter#43597] opened 2019-10-27 16:45 UTC
when i am trying to make apk with "flutter build apk" command , i am getting this response and my build failed,I am working on my production app please someone help me
```
===== CRASH =====                                                       
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x0             
Dart snapshot generator failed with exit code -6                        
Snapshotting exited with non-zero exit code: -6                         
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/use/Library/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 768
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildReleaseArm'.         
> Process 'command '/Users/prasantpandey/Library/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 17s                                                  
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      78.2s
Gradle task assembleRelease failed with exit code 1
```

**Comment by BondarenkoStas** [comment] 2019-10-28 13:11
@prasant10050 Please paste your flutter doctor -v output. And if possible some small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/. I wonder does have something to do with https://github.com/flutter/flutter/issues/35121?

**Comment by prasant10050** [comment] 2019-10-28 13:35
Sure

**Comment by BondarenkoStas** [comment] 2019-10-29 12:47
Duplicate of #43707

**Closed by BondarenkoStas** 2019-10-29 12:47 UTC
Labels: severe: crash, waiting for customer response

**Comment by baoxiehao** [comment] 2020-09-11 07:30
flutter channel dev or master
then switch back to stable
WORKS
