### ISSUE TITLE
Create Android and iOS Apps without needing Android Studio and XCode

### ISSUE THREAD

**Issue by cleangist** [flutter/flutter#91211] opened 2021-10-04 05:22 UTC
I'm a newbie whose first Programming Language in my life will be Dart, and the first ever Framework I will encounter in my Life is Flutter. 

In creating a Flutter Project using Android Studio, I find the Link to **New Image Asset** missing. See it here--  https://prnt.sc/1uac6qb

I'm also facing many stupid and senseless issues with Android Studio. 

These predicaments now triggered something in my head, and forced me to ask that -- _Can the Flutter Team not build something that can help us build Android and iOS Apps without needing **Android Studio** and **XCode**_?

If you then ask me the Question-- Are you saying we should create a Flutter IDE that has the power of Android Studio and XCode built-in?

My simple answer is a thundering "**YES**"

Needing to hear from you soon.
Regards

**Comment by devduiux** [comment] 2021-10-04 06:35
Hello @cleangist 

Your suggestion of create new Flutter IDE for both platforms in one IDE it sounds really good.
We can use multiple platforms for android like VS code and IntelliJ IDE but iOS allow only xCode for their app there is big issue.

**Comment by TahaTesser** [comment] 2021-10-04 08:54
Hi @cleangist 
This doesn't sound feasible, Closing
Thank you

**Closed by TahaTesser** 2021-10-04 08:54 UTC
Labels: in triage

**Comment by cleangist** [comment] 2021-10-04 09:29
You see, I don't care a darn, nor do I give a sh*t about iOS.

All I'm interested in for now, is Dart,Flutter and Android Apps.

Now, getting my Flutter project to work seamlessly on Android Studio, is something I've been struggling with, for 3 weeks now--and I've still not made any headway.

All I've been getting is frustrations, headache, and me actually losing hope.

I am trying to access Image Asset, but I can't see it. Here's my screenshot--- https://prntscr.com/1upsw53

Wow, I realized that I'm not the only one facing this problem. There are people on StackOverflow facing the same problem from here--- https://github.com/flutter/flutter-intellij/issues/3512

What offended me is here--- https://prntscr.com/1uqfk4n

Where I think the Dev Team of Android Studio made it sound like Flutter is on Rental to Android Studio-- as if Flutter is borrowing space in Android Studio, and Flutter doesn't have esteemed and equality Status with Android Studio's recognition of Java and Kotlin Projects. 

It's as if the Android Studio Team see Flutter Projects like low-level projects, lower than the heels of Android Studio's Java and Kotlin Projects. As if Flutter/Dart projects are a kind of disdainful and inferior entity.

This is why I believe that the Dart/Flutter project should also be a standalone project.

Since I believe that Android and Android Studio were Google supported creations.

And Dart/Flutter is now a Google supported creation. 

Then it should be no problem allowing Dart/Flutter to use the tools in Android Studio that makes it able to render APK Mobile App formats, without using Android Studio at all.

But through an IDE built specifically for Dart and Flutter to render Android and iOS Apps.

In this way, we don't have to face the nonsense issues that Android Studio causes is to pass through.

Will be interested to see the Flutter/Dart Team tell me that this will be done soon.

Regards.

**Comment by cleangist** [comment] 2021-10-05 06:28
> Hi @cleangist This doesn't sound feasible, Closing Thank you
===============================================================

This is feasible Sir.

I'm facing a lot of issues that are really frustrating me, due to using Android Studio for Flutter Projects. And I've been on this for 3 weeks. 

That's not 3 weeks of productivity. It is 3 weeks of waste: and the reason is because Android Studio will not see my "**res**" folder to enable me add new "Image Asset". Here's my screenshot--- https://prntscr.com/1upsw53

You see, in the **Technology Space**, everything has been possible simply because men of great courage made it possible: and we've been to the moon, to Mars, Jupiter, the Mariana trench, and to deep places that our normal human person wouldn't dare.

There was a time in this world that there was no Google, or Facebook or Android or iPhone. But men of great courage and insight, made these possible and available to all of humanity.

In context here, there was a time that there was no Flutter and No Dart. But men of great courage and insight made these possible and available to all of humanity.

If before your very eyes, great inventions and great things have been born into the world, Why then do you make yourself an enemy of progress, and a clog in the wheel of progress, to say that my idea is not feasible and so you close it?

Why not leave that decision to the Flutter and Dart Team to decide if they seriously believe that Dart/Flutter doesn't need its own standalone IDE?

Regards

**Comment by TahaTesser** [comment] 2021-10-05 07:38
Hi @cleangist 

>  I find the Link to New Image Asset missing. See it here--


You need to open the Android folder of your Flutter app in Android Studio to see all Android Specific options. If you still don't do it, please file an issue on the Android Studio issue tracker. This is not related to Flutter itself

**Comment by TahaTesser** [comment] 2021-10-05 07:39
> Hi @cleangist
> This doesn't sound feasible, Closing
> Thank you

To be clear, the issue is closed for proposing `Create Android and iOS Apps without needing Android Studio and XCode`, which is not feasible
