### ISSUE TITLE
Listview inside a Dismissible(Vertical) widget

### ISSUE THREAD

**Issue by balasubramanian1612s** [flutter/flutter#83795] opened 2021-06-02 14:59 UTC
```
    Dismissible(
background: ListView.builder(
                      itemCount: 500,
                      itemBuilder: (context, indes) => Text(indes.toString())),
child: ListView.builder(
                      itemCount: 500,
                      itemBuilder: (context, indes) => Text(indes.toString())),
secondaryBackground: ListView.builder(
                      itemCount: 500,
                      itemBuilder: (context, indes) => Text(indes.toString())),
resizeDuration: Duration(milliseconds: 10),
                  key: Key(index.toString()),
                  direction: DismissDirection.vertical,
                );
```

This is a Simple Code reproduce of what I require. So after I finished scrolling all 500 items, I should be able to dismiss the widget.

Thank you in Advance.

**Comment by balasubramanian1612s** [comment] 2021-06-02 15:04
**Flutter doctor -v**
[]()https://user-images.githubusercontent.com/61572479/115207327-1dbb4a80-a119-11eb-902a-8cbcf65c53c5.png

**Comment by bernaferrari** [comment] 2021-06-02 17:59
This a hard unsolved problem.

**Comment by balasubramanian1612s** [comment] 2021-06-02 20:45
> This a hard unsolved problem. 

Basically what I need is transition like inshorts app with scrollview in single page.

If you've any work around pls let me know.

**Comment by bernaferrari** [comment] 2021-06-02 20:47
The issue is that ListView.builder doesn't give you the expected size and that widget NEEDS to know how long is the list before. So, endless lists doesn't work. If you can calculate the expected size by hand it becomes easier, but sometimes you really don't know.

That's mostly how Flutter works and there is no easy workaround.

**Comment by balasubramanian1612s** [comment] 2021-06-02 20:49
> The issue is that ListView.builder doesn't give you the expected size and that widget NEEDS to know how long is the list before. So, endless lists doesn't work. If you can calculate the expected size by hand it becomes easier, but sometimes you really don't know.
> 
> That's mostly how Flutter works and there is no easy workaround.
> 
> If you replace ListView.builder with ListView with shrinkSize: true, it should work (but will be a lot less efficient, but there is nothing you can do).

Okay let's say I know the size, but each list view size is different, then will it work?

**Comment by bernaferrari** [comment] 2021-06-02 20:50
ListView + shrinkSize is going to render all at once. It will be super not efficient with 1500 items, but it should work.

**Comment by balasubramanian1612s** [comment] 2021-06-02 20:56
> ListView + shrinkSize is going to render all at once. It will be super not efficient with 1500 items, but it should work.

That code is just for sample.. Can you please provide some example if possible. Like with containers in the list view?

**Comment by bernaferrari** [comment] 2021-06-02 20:57
I can't right now but if you search the issues for Draggable something, you should find what you want. There are plenty of related issues.

**Comment by TahaTesser** [comment] 2021-06-03 11:45
Hi @balasubramanian1612s 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/32954
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-03 11:45 UTC
Labels: in triage
