### ISSUE TITLE
[google_map] google_map widget is on top of his container

### ISSUE THREAD

**Issue by doryanB** [flutter/flutter#49054] opened 2020-01-17 14:41 UTC
### Explanation of the Problem:

on IOS (and only IOS), the GoogleMap Widget  has a weird  behavior. 

I want to wrap my GoogleMap in a  Card (or a Container) to make the angle of the card round. 
for IOS, it's like the Map is over the container and donc take the google shape.
(Works fine for Android)

### Simple sample code: 
```dart
Card(
                        child: GoogleMap(
                          mapType: MapType.normal,
                          initialCameraPosition: eventPos,
                          myLocationButtonEnabled: false,
                        )
                      );`
```
## effect of this code:
![image](https://user-images.githubusercontent.com/16140551/72620422-8a0c3480-393f-11ea-8b8f-39d5a5d05faf.png)

### flutter Doctor:
```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] Connected device (2 available)

• No issues found!
```

Github of a simple reproduction project showing the problem : 
https://github.com/doryanB/google_map_sample

**Comment by steve-rait** [comment] 2020-01-20 14:44
Hi, I confirm that behavior too in my tests, on IOS only.
Google maps widget does not have rounded corners on card widget.
I found other post about similar problems, e.g on https://github.com/flutter/flutter/issues/25965

I tried to use ClipRRect to wrap google map, but it crashes my app when if my clip is in a ListView : 
When i scroll down to see my map, then scroll up to go to the top, the app crashes when ClipRRect in not on screen anymore !

**Comment by doryanB** [comment] 2020-01-20 14:53
So, indeed if you do . that => 
` 

ListView(
    children:[
    ... ,
    Container(
              height: 250,
              child: ClipRRect(
                borderRadius: BorderRadius.circular(15),
                child: GoogleMap( mapType: MapType.normal, initialCameraPosition: CameraPosition(
                  target: LatLng(42.0,28.652),
                  zoom: 14,
                ),  myLocationButtonEnabled: false, ),
              ),
            )
      ])`

the ClipRRect with make your app crash (hard) when you scroll to the map and scroll back to the top (the moment the map disappear from the screen)

**Solution**
`
SingleChildScrollView(
child: 
Column(
    children:[
    ... ,
    Container(
              height: 250,
              child: ClipRRect(
                borderRadius: BorderRadius.circular(15),
                child: GoogleMap( mapType: MapType.normal, initialCameraPosition: CameraPosition(
                  target: LatLng(42.0,28.652),
                  zoom: 14,
                ),  myLocationButtonEnabled: false, ),
              ),
            )
      ])`
  this will have the wanted behaviour and will work :)

**Comment by TahaTesser** [comment] 2021-04-23 12:49
Hi everyone, 
To shape platform views. using ClipRect or ClipRRect and I just tried `ClipRRect` with maps,  I couldn't reproduce any crash


<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: ListView(
        children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(25),
            child: Container(
              height: 200,
              child: GoogleMap(
                mapType: MapType.hybrid,
                initialCameraPosition: _kGooglePlex,
                onMapCreated: (GoogleMapController controller) {
                  _controller.complete(controller);
                },
              ),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (7 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.85

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.2.0-11.0.pre.247, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.247 at
      /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f55b2665e9 (6 hours ago), 2021-04-23 12:39:02 +0530
    • Engine revision 6fa0fb0059
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version unknown)
    ✗ Invalid IntelliJ version number.

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```
	
</details>

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-23 12:49 UTC
Labels: a: quality, p: first party, p: maps, platform-ios, plugin
