### ISSUE TITLE
Bug in FireStore 

### ISSUE THREAD

**Issue by Chetan11-dev** [flutter/flutter#53087] opened 2020-03-23 11:05 UTC
First of all thank you Flutter team for such an amazing Platform. 

I dug into FireStore and discovered that it is creating a a new instance everytime Firestore.instance is called 
==============================buggy code================================
 static Firestore get instance => Firestore();
==============================buggy code================================

First i thought it was correct but then i wrote a test to verify it
==============================TEST CODE============================
void main() {
// CREATE TWO INSTANCE 
    Fire.instance;
    Fire.instance;
}

class Fire {

  static Fire get instance => Fire();

  Fire._();
  factory Fire() {
    print("fire");
    return Fire._();
  }
}

==============================TEST CODE============================
=============Output=================
fire
fire
=============Output=================
This shows it creates a new instance every time Firestore.instance is called .I think this is not the expected behaviour,

Thanks in advance

**Comment by Chetan11-dev** [comment] 2020-03-23 11:08
I forgot to tell the fix 
replace  static Firestore get instance => Firestore();
with   static Firestore get instance = Firestore();

**Comment by iapicca** [comment] 2020-03-23 11:41
Hi @Chetan11-dev 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-03-23 11:41 UTC
