### ISSUE TITLE
Bad framerate in recent builds from Linux

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4918] opened 2016-07-14 17:39 UTC
We built Leafy in release mode from a linux box and ran on a nexus 5 and 5x, and got noticeably low frame rates on both devices when scrolling even small pages.

We will provide additional details momentarily.

**Comment by eseidelGoogle** [comment] 2016-07-14 17:41
@chinmaygarde could this relate to your removing of gfx code?  FYI @jason-simmons @abarth

**Comment by mehmetf** [comment] 2016-07-14 17:41
Just for reference
    • Flutter Framework revision 9c0c0225a6 (3 weeks ago), engine revision bb9865538b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Platform android-23, build-tools 23.0.2

**Comment by DaveShuckerow** [comment] 2016-07-14 17:45
That's correct.  We tried a release build from Atom and from command line.

**Comment by chinmaygarde** [comment] 2016-07-14 18:40
The Flutter framework version @mehmetf listed and the corresponding engine revision does not contain the patchset with the removal of the `gfx::` code. It is about 20 days old while the `gfx::` patches only landed in an engine rev about an hour ago. In any case, the refactor should not have caused any regressions.

Is there a readily available reduced test case I can trace? In any case, I am also going to trace a few builds of the gallery to see if I notice anything odd.

**Comment by eseidelGoogle** [comment] 2016-07-14 19:04
I can show you how to run leafy's app directly.

**Comment by eseidelGoogle** [comment] 2016-07-14 19:35
@jason-simmons built leafy's app and we added showPerformanceOverlay: true to the MaterialApp invocation.  It looks like it never stops posting frames, so presumably something is leaking an animation which could explain this behavior.

**Comment by eseidelGoogle** [comment] 2016-07-14 19:40
If you call debugAssertNoTransientCallbacks from within the Observatory debugger at a time when you expect your app to not be doing anything, it will print the callstack of all registered animations, etc:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/scheduler/binding.dart#L282

I'm happy to walk you through this in person if you like.

**Comment by eseidelGoogle** [comment] 2016-07-14 19:49
I believe the bug is in the _TapMe class, which creates/starts AnimationController, but does not stop it when _TapMe is disposed.

We used to have this bug in ProgressIndicator for example:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/progress_indicator.dart#L161

I've filed https://github.com/flutter/flutter/issues/4921 about making this easier to detect/fix.

**Comment by mehmetf** [comment] 2016-07-14 20:24
@eseidelGoogle your hunch was correct. I fixed this and the stutter is gone.

**Comment by eseidelGoogle** [comment] 2016-07-14 20:51
Thanks.  We can just call this a dupe of #4921.

**Closed by eseidelGoogle** 2016-07-14 20:51 UTC
Labels: ▣ platform-android, ⚠ astounding performance, ⚠ bug (regression)
