### ISSUE TITLE
HTML5 Playable Ad [Flutter Web]

### ISSUE THREAD

**Issue by thize** [flutter/flutter#79786] opened 2021-04-05 15:04 UTC
Flutter web is in production and I believe that a great advance would be the possibility of generating playable ads with it!

The current problem is that the finał web build does not run locally (opening the index.html) making it need a server to run, not being able to be used as a playable ad

**Comment by ferhatb** [comment] 2021-04-08 22:15
Can you please give some detail on use case. We don't have plans to support server side rendering if thats what you are asking. If you are considering using Flutter Web inside another web site, currently your only option is placing it in an iframe.

**Comment by thize** [comment] 2021-04-08 22:54
The use case is to use the release as a playable ad:
https://support.google.com/google-ads/answer/9981650?hl=en
https://www.facebook.com/business/ads/playable-ad-format

Facebook Playable Ad: https://developers.facebook.com/tools/playable-preview/
Google Playable Ad Validator: https://h5validator.appspot.com/adwords/asset

**Comment by mariamhas** [comment] 2021-04-15 22:17
This usecase can be resolved with a custom html element feature;  duplicate of https://github.com/flutter/flutter/issues/32329. closing

**Closed** 2021-04-15 22:29 UTC
Labels: passed first triage, platform-web, proposal, severe: new feature
