### ISSUE TITLE
Can't use hot reload when running on android

### ISSUE THREAD

**Issue by fctorial** [flutter/flutter#52636] opened 2020-03-15 19:44 UTC
## Steps to Reproduce

1. Run an app with `flutter run`

The hot reload message isn't displayed and 'r/R' keys do not have any effect:

```
[$] flutter-beta run
Launching lib/main.dart on 1825 I01 in debug mode...
Running Gradle task 'assembleDebug'...                             63.1s
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         5.5s
^C
```

`flutter-beta doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
[!] IntelliJ IDEA Community Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] Connected device (2 available)

! Doctor found issues in 4 categories.
```

**Comment by fctorial** [comment] 2020-03-15 19:45
`--hot` option doesn't have any effect.

**Comment by jonahwilliams** [comment] 2020-03-15 22:22
Did you exit early from the logs? Did it get stuck?

**Comment by fctorial** [comment] 2020-03-15 23:30
The command `flutter-beta run` builds and launches the app once, displays the above message and then doesn't do anything else. `r/R` keys work with ` -d web-server` option but not with android.

**Comment by jonahwilliams** [comment] 2020-03-15 23:32
What is `flutter-beta`, an alias for a specific `flutter`? 

Are you on Linux 5.5?

**Comment by fctorial** [comment] 2020-03-15 23:39
Yes it's a direct alias to `flutter` binary.

No, I'm on linux 4.19.108.

This is the output of `flutter doctor -v`:  https://gist.github.com/fctorial/05b68f8080523c439ce87ade94930502

**Comment by jonahwilliams** [comment] 2020-03-15 23:41
Could you include the full verbose logs from a `flutter run` that gets stuck?

**Comment by fctorial** [comment] 2020-03-15 23:46
```
[$] flutter-beta run
Launching lib/main.dart on 1825 I01 in debug mode...
Running Gradle task 'assembleDebug'...                             63.1s
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         5.5s
rr
RR
^C
```

This is the complete output before until a `Ctrl-C` which ends the process.

**Comment by fctorial** [comment] 2020-03-16 00:08
@jonahwilliams This is the output of `flutter run --verbose`:

https://gist.github.com/fctorial/409f1b321502ee3798ce8df8052839b6

**Comment by jonahwilliams** [comment] 2020-03-16 06:03
Looks like its having trouble finding the observatory port. Can you confirm that the app is otherwise starting correctly? If so, you could run `adb logcat` and very that somewhere in the output is a string like `observatory listening on...`

**Comment by fctorial** [comment] 2020-03-16 15:08
Yes the app installs and launches correctly.

No there's no such string in the logcat output.

**Comment by jonahwilliams** [comment] 2020-03-16 16:59
Okay, that is definitely odd. This might be an issue unique to your application - if it is otherwise starting correctly but you're not seeing the observatory debugger.

Are you doing add2app or using a custom flutter view? I would see if you could simplify this until you get to a minimum reproduction, and then share what you find.

**Comment by fctorial** [comment] 2020-03-16 19:40
@jonahwilliams A new project created with `flutter create app` shows the same behaviour (launches and hangs with android and works fine with web-server).

**Comment by smolck** [comment] 2020-05-08 21:36
@fctorial I'm not sure if I have exactly the same problem as you, but I was at least able to find a workaround for my issue (#55128).

First, do `$ flutter run -d <your device id>` and let that run. The app should open on your device, which means that even though it hangs at the `Installing ...` part, you can still connect to it using the `flutter attach` command.

Next, leaving the terminal with the `$ flutter run` command open, open a new terminal and enter `$ adb shell` (assuming you only have the one device connected), and then enter `$ logcat -e flutter\|Observatory *:I `. This should give a lot of output, but it should then slow down and you should see a message with `Observatory listening on <url>`. 

Copy that url, and then run this command from the root of your app directory, replacing `<url>` with that url you copied: `$ flutter attach --debug-uri <url>`. It should then connect and you should be able to hot-reload using `r` as normal.

Pretty annoying workaround, but it worked for me and will hopefully work for you until this issue is resolved.

**Comment by tandacedric** [comment] 2020-07-28 11:23
> flutter attach --debug-uri

It work fine

**Comment by iapicca** [comment] 2020-12-27 11:55
@smolck 
are you still experiencing the issue?

**Comment by smolck** [comment] 2021-01-14 21:19
@iapicca I'm not sure as I haven't tested it in a while, but I'd assume it's working fine now since #55128 appears to be fixed, and that issue seemed to be a duplicate of this one.

**Comment by iapicca** [comment] 2021-01-14 22:16
@TahaTesser thoughts?

**Comment by TahaTesser** [comment] 2021-01-15 12:47
There is almost no activity and https://github.com/flutter/flutter/issues/55128 is closed well
Closing, Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
Thank you

**Closed by TahaTesser** 2021-01-15 12:47 UTC
Labels: platform-android, platform-linux, t: hot reload, tool
