### ISSUE TITLE
 3.18.0-0.2.pre → 3.19.0-0.1.pre - Web - Broke something in the HtmlElementView and InputElement

### ISSUE THREAD

**Issue by stefanschaller** [flutter/flutter#149983] opened 2024-06-10 06:36 UTC
### Steps to reproduce

1. Run provided example  

### Expected results

A circle with the following message should be displayed: "Ein Fehler ist aufgetreten".  Which should looks like: 

![Bildschirmfoto 2024-06-10 um 08 13 36](https://github.com/flutter/flutter/assets/30521865/3cabb6b7-fc7e-413c-9657-4bad7f1013a5)

### Actual results

Nothing is shown after upgrading to from 3.19.0-0.1.pre. 

![Bildschirmfoto 2024-06-10 um 08 14 13](https://github.com/flutter/flutter/assets/30521865/a2fccdf1-71d1-4cfb-ae58-de3cc0035324)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:html';
import 'dart:math';
import 'dart:ui_web' as ui;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: WorldlinePaymentHtml(),
    );
  }
}

class WorldlinePaymentHtml extends StatefulWidget {
  const WorldlinePaymentHtml({super.key});

  @override
  State<WorldlinePaymentHtml> createState() => _WorldlinePaymentHtmlState();
}

class _WorldlinePaymentHtmlState extends State<WorldlinePaymentHtml> {
  final _viewId = "${Random().nextInt(99999999)}-view";
  late final FormElement _postRequestFormElement;

  @override
  void initState() {
    super.initState();

    final redirectionVersionInput = InputElement()
      ..type = "hidden"
      ..name = "redirectionVersion"
      ..value = "IR_WS_2.0";

    final redirectionDataInput = InputElement()
      ..type = "hidden"
      ..name = "redirectionData"
      ..value = "TEST";

    _postRequestFormElement = FormElement()
      ..method = "post"
      ..action = "https://payment-web.simu.sips-services.com/payment"
      ..target = 'sips_payment_iframe'
      ..children = [redirectionVersionInput, redirectionDataInput];

    final iFrameElement = IFrameElement()
      ..id = 'sips_payment_iframe'
      ..name = 'sips_payment_iframe'
      ..width = "100%"
      ..height = "100%";

    final bodyElement = BodyElement()
      ..children = [_postRequestFormElement, iFrameElement];

    ui.platformViewRegistry.registerViewFactory(
      _viewId,
      (int id) => bodyElement,
    );
  }

  @override
  Widget build(BuildContext context) {
    return HtmlElementView(
      viewType: _viewId,
      onPlatformViewCreated: (_) {
        _postRequestFormElement.submit();
      },
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

The exact commit, which broke the view is https://github.com/flutter/engine/compare/c70f0a495ace...1b1b2a12a597 with the version: `3.18.0-18.0.pre.13`.
I figured that out while doing a `git bisect` from the last working version `3.18.0-0.2.pre` and the first bad version `3.19.0-0.1.pre`.

Not working commit: 

```console
Flutter 3.18.0-18.0.pre.13 • channel [user-branch] • unknown source
Framework • revision b417fb828b (vor 6 Monaten) • 2023-12-21 17:55:07 -0500
Engine • revision 1b1b2a12a5
Tools • Dart 3.3.0 (build 3.3.0-253.0.dev) • DevTools 2.31.0-dev.0
```

Last official working version: 

```console
[✓] Flutter (Channel beta, 3.18.0-0.2.pre, on macOS 14.4.1 23E224 darwin-arm64 (Rosetta), locale de-DE)
    • Flutter version 3.18.0-0.2.pre on channel beta at /Users/stefanschaller/fvm/versions/3.18.0-0.2.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fed06b31d9 (vor 6 Monaten), 2023-12-13 14:53:33 -0800
    • Engine revision 39c6dc9bdd
    • Dart version 3.3.0 (build 3.3.0-174.3.beta)
    • DevTools version 2.30.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/stefanschaller/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/233.14808.21.2331.11842104/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/233.14808.21.2331.11842104/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/233.14808.21.2331.11709847/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
    • IntelliJ at /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/241.15989.150/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2024.1.2)
    • IntelliJ at /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/241.17011.79/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • Stefan‘s iPhone (mobile) • 00008030-0003395C1432802E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64 (Rosetta)
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

First official version to reproduce the error:

```console
[✓] Flutter (Channel beta, 3.19.0-0.1.pre, on macOS 14.4.1 23E224 darwin-arm64 (Rosetta), locale de-DE)
    • Flutter version 3.19.0-0.1.pre on channel beta at /Users/stefanschaller/fvm/versions/3.19.0-0.1.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a9a60d044 (vor 5 Monaten), 2024-01-10 13:38:09 -0800
    • Engine revision bbebee1465
    • Dart version 3.3.0 (build 3.3.0-279.0.dev)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/stefanschaller/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/233.14808.21.2331.11842104/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/233.14808.21.2331.11842104/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/233.14808.21.2331.11709847/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
    • IntelliJ at /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/241.15989.150/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2024.1.2)
    • IntelliJ at /Users/stefanschaller/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/241.17011.79/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • Stefan‘s iPhone (mobile) • 00008030-0003395C1432802E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64 (Rosetta)
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-06-10 11:42
Thanks for the report. I was able to replicate the reported behavior on latest stable and master versions as well.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.22.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.22.2 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (33 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.23.0-13.0.pre.149, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.23.0-13.0.pre.149 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ae47edab7a (68 minutes ago), 2024-06-07 01:34:14 -0400
    • Engine revision 087feab992
    • Dart version 3.5.0 (build 3.5.0-234.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by ditman** [comment] 2024-06-17 17:38
@stefanschaller due to changes needed for multi-view support, we *did* change the timing of this slightly, and the callback fires when the factory function is run, but slightly before it is actually injected in the DOM.

We documented this here:

* https://api.flutter.dev/flutter/widgets/HtmlElementView-class.html#html-lifecycle

There's APIs in the DOM that can be used to detect when the root element of your platform view is injected into the DOM.

--

(Similar to: https://github.com/flutter/flutter/issues/143922)

**Comment by stefanschaller** [comment] 2024-06-18 06:56
I'm not able to fix the example with the provided documentation. Could take a look? @ditman

**Comment by stefanschaller** [comment] 2024-06-18 07:34
I tried it like this, with the same result: 


```dart 
import 'package:flutter/material.dart';
import 'dart:html';
import 'dart:math';
import 'dart:ui_web' as ui;
import 'package:web/web.dart' as web;
import 'dart:js_interop';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: WorldlinePaymentHtml(),
    );
  }
}

class WorldlinePaymentHtml extends StatefulWidget {
  const WorldlinePaymentHtml({super.key});

  @override
  State<WorldlinePaymentHtml> createState() => _WorldlinePaymentHtmlState();
}

class _WorldlinePaymentHtmlState extends State<WorldlinePaymentHtml> {
  final _viewId = "${Random().nextInt(99999999)}-view";
  final _bodyElementId = "sips_body_element_id";

  late final FormElement _postRequestFormElement;

  @override
  void initState() {
    super.initState();

    final redirectionVersionInput = InputElement()
      ..type = "hidden"
      ..name = "redirectionVersion"
      ..value = "IR_WS_2.0";

    final redirectionDataInput = InputElement()
      ..type = "hidden"
      ..name = "redirectionData"
      ..value = "TEST";

    _postRequestFormElement = FormElement()
      ..method = "post"
      ..action = "https://payment-web.simu.sips-services.com/payment"
      ..target = 'sips_payment_iframe'
      ..children = [redirectionVersionInput, redirectionDataInput];

    final iFrameElement = IFrameElement()
      ..id = 'sips_payment_iframe'
      ..name = 'sips_payment_iframe'
      ..width = "100%"
      ..height = "100%";

    final bodyElement = BodyElement()
      ..id = _bodyElementId
      ..children = [_postRequestFormElement, iFrameElement];

    ui.platformViewRegistry.registerViewFactory(
      _viewId,
          (int id) => bodyElement,
    );
  }

  @override
  Widget build(BuildContext context) {
    return HtmlElementView.fromTagName(
      tagName: _bodyElementId,
      onElementCreated: (element) => _onElementCreated(element),
    );
  }

  void _onElementAttached() {
    // To fulfil the following requirements: https://docs.sips.worldline-solutions.com/en/WLSIPS.316-UG-Sips-Paypage-JSON.html#Exemple-de-formulaire-de-redirection-vers-Paypage_
    // From the 📄:
    //
    // To redirect the customer to the payment pages, you must implement a POST form sending the two following fields: redirectionData and redirectionVersion. The POST form shall redirect the customer to the URL provided in the redirectionUrl field.
    //
    // Below is a sample form that must be submitted automatically:
    //
    // <form method="post" action=”value of redirectionURL”>
    //     <input type="hidden" name="redirectionVersion" value=”value of redirectionVersion”>
    //     <input type="hidden" name="redirectionData" value=”value of redirectionData”>
    //   </form>
    _postRequestFormElement.submit();
  }

  void _onElementCreated(Object element) {
    final htmlElement = element as web.Element;

    // Create the observer
    final web.ResizeObserver observer = web.ResizeObserver(
          (
          JSArray<web.ResizeObserverEntry> entries,
          web.ResizeObserver observer,
          ) {
        if (htmlElement.isConnected) {
          // The observer is done, disconnect it.
          observer.disconnect();
          // Call our callback.
          _onElementAttached();
        }
      }.toJS,
    );

    // Connect the observer.
    observer.observe(htmlElement);
  }
}

```

Flutter: 

```
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (12 days) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

**Comment by ditman** [comment] 2024-06-20 18:29
> I'm not able to fix the example with the provided documentation. Could take a look? @ditman

@stefanschaller are there any errors in the JS console of the browser? Is this browser specific?

**Comment by stefanschaller** [comment] 2024-06-20 18:35
Not a single error in Chrome, Safari. 

Please just take a look by yourself. I don't know how to continue there an I need to upgrade ASAP to the newest Flutter Version, since I need some features from 3.19 and 3.22

**Comment by ditman** [comment] 2024-06-21 00:20
I think I've found the issue and got your sample app working as expected.

### Debugging

Here's some of the steps I took to understand what's happening with the platform view on this app:

1. Used the `elements` panel to see what actually gets injected into the DOM from the app. There's a suspicious element:
   <img width="363" alt="suspicion" src="https://github.com/flutter/flutter/assets/1255594/61955807-46be-4b27-8ef7-5e452be2b723">
2. Tracked that down to the source:
   <img width="611" alt="root-cause" src="https://github.com/flutter/flutter/assets/1255594/2a17867d-442b-4027-aa6f-f6b18f55d6a9">
3. The problem is that the code is mixing `registerViewFactory` with the `fromTagName` constructor:
   <img width="636" alt="Screenshot 2024-06-20 at 4 55 28 PM" src="https://github.com/flutter/flutter/assets/1255594/a4df8723-275d-47c4-acf8-3bdd12093aa0">

### Proposed solution

The `class _WorldlinePaymentHtmlState.build` method should be something like this:

```dart
  @override
  Widget build(BuildContext context) {
    return HtmlElementView(
      viewType: _viewId,
      onPlatformViewCreated: (id) {
        final element = ui.platformViewRegistry.getViewById(id);
        _onElementCreated(element);
      },
    );
  }
```

(With this API, we must obtain the `element` from its platform view `id`, and that's what the `getViewById` API does. That `element` can be passed to `_onElementCreated` as is).

> [!NOTE]
> You could also use `HtmlElementView.fromTagName` without registering the viewFactory, but in that case, you'd need to add all the elements that you're now creating in `initState` into the `element` passed into the `onElementCreated` callback, to customize it before it gets injected into the DOM.

I have a couple more suggestions:

* (~L62) Do not use `BodyElement` to group the form and iframe together, instead use `DivElement` or something like that. Websites should not have multiple `<body>` tags.
* Do not mix `dart:html` and `package:web`; I'd prefer the more modern (and Wasm-compatible) `package:web`. See the [migration guide](https://dart.dev/interop/js-interop/package-web).

---

@stefanschaller let me know if the above helps and is enough to close the issue!

**Comment by stefanschaller** [comment] 2024-06-21 06:42
![Bildschirmfoto 2024-06-21 um 07 53 36](https://github.com/flutter/flutter/assets/30521865/67e2eaff-aa06-4ffe-be12-52adb1b67246)


Looks good, I'm sadly not able to show the full screen, since there are some customer related data, but it's working as expected. Thank you! 

I also migrated from an `BodyElement` to an `DivElement` and also removed the `dart:html` import.

**Comment by ditman** [comment] 2024-06-21 18:31
> Looks good, I'm sadly not able to show the full screen, since there are some customer related data, but it's working as expected. Thank you!
> 
> I also migrated from an `BodyElement` to an `DivElement` and also removed the `dart:html` import.
> 
> @ditman You could close the issue. Thank you for the great support

Closing this one! Thanks for reporting @stefanschaller, keep them coming!

**Closed by ditman** 2024-06-21 18:31 UTC
Labels: c: regression, platform-web, has reproducible steps, team-web, found in release: 3.22, found in release: 3.23
