### ISSUE TITLE
[GoRouter] Implement popUntil Method in GoRouter

### ISSUE THREAD

**Issue by aliaksei-liavonik** [flutter/flutter#128715] opened 2023-06-12 17:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I've identified a use case where it could be beneficial to have a popUntil function in the GoRouter package, similar to the one provided by Navigator in Flutter. 

Versions:
- flutter: 3.10.1
- go_router: 7.1.1
- go_router_builder: 2.0.1

Use case:
There are situations where we might need to pop multiple routes off the stack until we reach a specific route, furthermore, we could not know how many routes were pushed after the target route. This is currently achievable using a workaround, but it would be much cleaner and more intuitive to have this function built into the GoRouter package.

### Proposal

Here's the workaround I am currently using:
```
extension GoRouterEx on GoRouter {
  void popUntil(RouteBase routeBase) {
    while (canPop() &&
        routerDelegate.currentConfiguration.matches.last.route.path !=
            routeBase.path) {
      pop();
    }
  }
}
```
So, the usage of this might look like this: 
```
goRouter.popUntil($myGeneratedRoute);
```
Ideally, I would prefer to use the Type of route instead of a generated getter. But this seems like a good starting point for the proposal.

Also, there are a few things that must be considered:
1. Efficiency. I see it in the way, the pages would be popped without each one being rendered individually and with only 1 animation (I had thoughts about one more improvement, poping all pages in one step for not having a lot of screens popped out but decided to replicate the solution from the Navigator(Anyway, there is no function to pop multiple routes with 1 animation))
2. Compatibility with nested/other navigators

**Comment by maRci002** [comment] 2023-06-13 08:58
Duplicate of #99112

You can still vote `popUntil` implementation, here: https://github.com/flutter/flutter/issues/99112#issuecomment-1583077752

**Comment by chunhtai** [comment] 2023-06-15 21:34
close as duplicate

**Closed by chunhtai** 2023-06-15 21:34 UTC
Labels: new feature, package, proposal, P5, p: go_router
