### ISSUE TITLE
Regression in some microbenchmarks_ios benchmarks.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#68890] opened 2020-10-23 15:53 UTC
https://flutter-flutter-perf.skia.org/e/?begin=1603135693&end=1603434531&keys=X1fa8ce79a6a882d2eacbb51a27b2fec2&requestType=0&xbaroffset=22131

Affects the following benchmarks:
```
stock_animation_close_first_frame_average
stock_animation_open_first_frame_average
stock_animation_subsequent_frame_average
```

First occurred at https://github.com/flutter/flutter/pull/67781, but could be later; it continued to rise. After that, it's dropped a little. Marking P1.

cc @jmagman , originator of that commit.

**Comment by jmagman** [comment] 2020-10-23 17:24
hm, I don't see how #67781 could be related, it introduced a new flag to a command those benchmarks aren't touching.  Though the graph does indeed look like it started there.

**Comment by justinmc** [comment] 2020-10-28 15:58
Another nearby PR was https://github.com/flutter/flutter/pull/66785, which I reviewed, but it similarly seems unrelated.  It only added a pass through parameter to text editing widgets.

What is it that these benchmarks measure exactly?

There is a lot of NNBD work in the vicinity of this change ([relevant commits page](https://github.com/flutter/flutter/commits/master?after=7b86be228e4054ae0ecd0c3896b9cc2641564ba9+104&branch=master)), but I also wouldn't think that would cause this.  CC @goderbauer @jonahwilliams for nearby PRs.

**Comment by goderbauer** [comment] 2020-10-28 18:29
Nothing in that range looks suspicious in the framework - especially for something that would only affect the ios version of these benchmarks (Android seems unaffected). 

Did we ever fix the problem where random iOS pop-ups mess with our benchmark data? Could that be the problem here?

**Comment by goderbauer** [comment] 2020-10-28 18:40
Also: In more recent runs, the benchmark seems to be bi-modal: https://flutter-flutter-perf.skia.org/e/?begin=1602198589&end=1603867624&formulas=norm(shortcut(%22X1fa8ce79a6a882d2eacbb51a27b2fec2%22))&requestType=0&xbaroffset=22131

Some runs are close to what they were before this regression, others are still high.

**Comment by goderbauer** [comment] 2020-10-28 18:52
> Did we ever fix the problem where random iOS pop-ups mess with our benchmark data? Could that be the problem here?

@godofredoc confirmed that those get automatically dismissed now.

**Comment by liyuqian** [comment] 2020-11-02 22:39
Reducing priority as this benchmark recently dropped and increased again on some seemingly unrelated commits. There doesn't seem to be anything actionable other than trying to reproduce it locally. If we can't reproduce locally, something might be happening in our infra that caused these benchmark jumps.

**Comment by godofredoc** [comment] 2020-11-02 22:46
Did those metrics dropped last Thursday after 3:00 PM?

**Comment by liyuqian** [comment] 2020-11-03 18:33
One drop occurred around https://github.com/flutter/flutter/commit/291ee945064845cb0e560b653b328f65bf6b1340 which landed last Tuesday 9am.

Another drop occurred around https://github.com/flutter/flutter/commit/3e41962dfff85701708f4e4b578511d2c46d5668 which landed last Friday 1pm.

This is what I'm looking at: https://flutter-flutter-perf.skia.org/e/?begin=1602548289&end=1604386684&keys=X1fa8ce79a6a882d2eacbb51a27b2fec2&requestType=0&xbaroffset=22131

**Comment by kf6gpe** [comment] 2020-11-09 22:41
triage: The number's gotten slightly better, but the midpoint's still above the old value. I'm going to leave this open for now.

**Comment by kf6gpe** [comment] 2020-11-16 22:33
I don't know if this is a bona fide regression or not --- it's bouncing around slightly higher than the old values on average if I eyeball it, but that's a bad measure.

@liyuqian What do you think?

**Comment by liyuqian** [comment] 2020-11-16 23:34
By focusing on just [microbenchmarks_ios stock_animation_subsequent_frame_average](https://flutter-flutter-perf.skia.org/e/?begin=1602102723&end=1605551441&keys=X5120c09505c1d00cd38db4ab95dd1a3d&requestType=0&xbaroffset=22131), I can see it to be around 290ns before the regression, and now the metric has gradually reduced to a level between 297ns to 340ns. It's much less than the peak regression around 500ns to 600ns.

I'm reducing the priority because the number now is only slightly higher, and the _micro_ benchmarks usually don't have a big impact on the end-user's experience directly.

**Comment by Hixie** [comment] 2021-03-10 00:58
Looks like we dropped the ball on this so I'm just going to close it, too much time has passd now to really do anything.

**Closed by Hixie** 2021-03-10 00:58 UTC
Labels: P5, passed first triage, perf: speed, platform-ios, severe: performance, severe: regression, team: benchmark
