### ISSUE TITLE
A fatal crash due to failed image decoding

### ISSUE THREAD

**Issue by lotusgate** [flutter/flutter#109926] opened 2022-08-20 16:39 UTC
**Issue**
I found two images (their urls) that cause a Flutter app to crash. I've confirmed it on an android emulator and a real android phone. The image names end with `.jpg.avif`. Stripping `.avif` makes everything work and using `.avif` in html just doesn't load the image. I assume the system tries to incorrectly decode the images and Flutter misses to catch the error?

The images in question are:
`https://cdn.anime-pictures.net/previews/790/790217b59cafb622a19a4ef314dbc8ad_bp.jpg.avif`
`https://cdn.anime-pictures.net/previews/a17/a17d6817fb5f1409e6ac5873a7a78ad3_bp.jpg.avif`

**Expected results**
I expect the error to be successfully caught by the `Image` widget.

<details>
<summary>Crash output</summary>

```
D/EGL_emulation(15056): app_time_stats: avg=1358.04ms min=28.01ms max=3972.53ms count=3
E/HeifDecoderImpl(15056): decode: videoFrame is a nullptr
E/FlutterJNI(15056): Failed to decode image
E/FlutterJNI(15056): java.io.IOException: getPixels failed with error invalid input
E/FlutterJNI(15056): 	at android.graphics.ImageDecoder.nDecodeBitmap(Native Method)
E/FlutterJNI(15056): 	at android.graphics.ImageDecoder.decodeBitmapInternal(ImageDecoder.java:1720)
E/FlutterJNI(15056): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1877)
E/FlutterJNI(15056): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1863)
E/FlutterJNI(15056): 	at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:524)
F/libc    (15056): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18 in tid 15084 (io.worker.2), pid 15056 (example.example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone64_x86_64/emulator64_x86_64_arm64:12/S2B2.211203.006/8015633:userdebug/dev-keys'
Revision: '0'
ABI: 'x86_64'
Timestamp: 2022-08-20 19:33:56.119347200+0300
Process uptime: 0s
Cmdline: com.example.example
pid: 15056, tid: 15084, name: io.worker.2  >>> com.example.example <<<
uid: 10149
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
Cause: null pointer dereference
    rax 0000000000000000  rbx 0000735fecdf56b8  rcx 00007362fe220d18  rdx 0000000000000001
    r8  0000000000000000  r9  0000735f00000000  r10 0000000000000000  r11 0000000000000246
    r12 0000735fecdf56a0  r13 0000735fed61f708  r14 0000735fe238a260  r15 0000736109e78450
    rdi 0000736109e78510  rsi 0000000000000081
    rbp 0000000000000258  rsp 0000735fecdf5660  rip 0000735feeec7512
backtrace:
      #00 pc 0000000001a89512  /data/app/~~nCveTWPoO8ZTBzNxAKTXLQ==/com.example.example-j-luqlQX9LnZ8l2DH-2Lug==/lib/x86_64/libflutter.so (BuildId: 9292ed7a57d628289a096bc46aa71468ce209e08)
      #01 pc 0000000001a4bdeb  /data/app/~~nCveTWPoO8ZTBzNxAKTXLQ==/com.example.example-j-luqlQX9LnZ8l2DH-2Lug==/lib/x86_64/libflutter.so (BuildId: 9292ed7a57d628289a096bc46aa71468ce209e08)
      #02 pc 0000000001a48e48  /data/app/~~nCveTWPoO8ZTBzNxAKTXLQ==/com.example.example-j-luqlQX9LnZ8l2DH-2Lug==/lib/x86_64/libflutter.so (BuildId: 9292ed7a57d628289a096bc46aa71468ce209e08)
      #03 pc 0000000001a46ff2  /data/app/~~nCveTWPoO8ZTBzNxAKTXLQ==/com.example.example-j-luqlQX9LnZ8l2DH-2Lug==/lib/x86_64/libflutter.so (BuildId: 9292ed7a57d628289a096bc46aa71468ce209e08)
      #04 pc 0000000001a47c64  /data/app/~~nCveTWPoO8ZTBzNxAKTXLQ==/com.example.example-j-luqlQX9LnZ8l2DH-2Lug==/lib/x86_64/libflutter.so (BuildId: 9292ed7a57d628289a096bc46aa71468ce209e08)
      #05 pc 000000000162ecf5  /data/app/~~nCveTWPoO8ZTBzNxAKTXLQ==/com.example.example-j-luqlQX9LnZ8l2DH-2Lug==/lib/x86_64/libflutter.so (BuildId: 9292ed7a57d628289a096bc46aa71468ce209e08)
      #06 pc 000000000162f35f  /data/app/~~nCveTWPoO8ZTBzNxAKTXLQ==/com.example.example-j-luqlQX9LnZ8l2DH-2Lug==/lib/x86_64/libflutter.so (BuildId: 9292ed7a57d628289a096bc46aa71468ce209e08)
      #07 pc 00000000000c74aa  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+58) (BuildId: 0bac1e57b41382f7871677ca544454ea)
      #08 pc 000000000005fca7  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+55) (BuildId: 0bac1e57b41382f7871677ca544454ea)
Lost connection to device.
```
</details>

<details>
<summary>Reproducible code</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const [
              FatalContainer(_fatalImage1),
              FatalContainer(_fatalImage2),
            ],
          ),
        ),
      ),
    );
  }
}

const _fatalImage1 =
    'https://cdn.anime-pictures.net/previews/790/790217b59cafb622a19a4ef314dbc8ad_bp.jpg.avif';

const _fatalImage2 =
    'https://cdn.anime-pictures.net/previews/a17/a17d6817fb5f1409e6ac5873a7a78ad3_bp.jpg.avif';

class FatalContainer extends StatefulWidget {
  const FatalContainer(this.imageUrl, {super.key});

  final String imageUrl;

  @override
  State<FatalContainer> createState() => _FatalContainerState();
}

class _FatalContainerState extends State<FatalContainer> {
  bool _show = false;

  @override
  Widget build(BuildContext context) {
    return _show
        ? Image.network(
            widget.imageUrl,
            errorBuilder: (context, error, stackTrace) {
              stderr.writeln('CAUGHT ERROR: $error');
              return const Text('The error was caught!');
            },
          )
        : ElevatedButton(
            child: const Text('Show fatal image'),
            onPressed: () => setState(() => _show = true),
          );
  }
}
```
</details>

<details>
  <summary>Related?</summary>

[This issue](https://github.com/flutter/flutter/issues/105532) is possibly related. If you think it's the same problem, I can move this information there and close this issue.
</details>

<details>
  <summary>Logs</summary>

flutter analyze
```
No issues found!
```

flutter doctor -v
```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
    • Flutter version 3.0.5 at E:\programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at E:\programs\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: E:\programs\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at E:\programs\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

flutter run -verbose
```
[  +63 ms] executing: [E:\programs\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +69 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] executing: [E:\programs\flutter/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[  +57 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] 3.0.5
[   +7 ms] executing: [E:\programs\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [E:\programs\flutter/] git ls-remote --get-url origin
[  +34 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +117 ms] executing: [E:\programs\flutter/] git rev-parse --abbrev-ref HEAD
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +70 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] executing: E:\programs\Android\Sdk\platform-tools\adb.exe devices -l
[  +47 ms] List of devices attached
           emulator-5554          device product:sdk_gphone64_x86_64 model:sdk_gphone64_x86_64 device:emulator64_x86_64_arm64 transport_id:4
[   +5 ms] E:\programs\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +50 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +14 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +121 ms] Skipping pub get: version match.
[  +69 ms] Generating E:\dev\example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +60 ms] ro.hardware = ranchu
[  +11 ms] Using hardware rendering with device sdk gphone64 x86 64. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +24 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +6 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: E:\dev\example\.dart_tool\package_config_subset}
[  +25 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[   +5 ms] Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
[   +4 ms] E:\programs\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev E:\programs\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
E:\programs\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true  
--output-dill C:\Users\hrist\AppData\Local\Temp\flutter_tools.312ad88f\flutter_tool.3b604577\app.dill --packages E:\dev\example\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[   +9 ms] executing: E:\programs\Android\Sdk\build-tools\33.0.0\aapt dump xmltree E:\dev\example\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +20 ms] Exit code 0 from: E:\programs\Android\Sdk\build-tools\33.0.0\aapt dump xmltree E:\dev\example\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.example" (Raw: "com.example.example")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="example" (Raw: "example")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.example.MainActivity" (Raw: "com.example.example.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +9 ms] executing: E:\programs\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +13 ms] <- compile package:example/main.dart
[  +89 ms] --------- beginning of system
           08-20 19:31:52.146 I/UsageStatsService(  578): User[0] Flushing usage stats to disk
[   +8 ms] executing: E:\programs\Android\Sdk\platform-tools\adb.exe version
[  +36 ms] Android Debug Bridge version 1.0.41
           Version 33.0.2-8557947
           Installed as E:\programs\Android\Sdk\platform-tools\adb.exe
[   +1 ms] executing: E:\programs\Android\Sdk\platform-tools\adb.exe start-server
[  +31 ms] Building APK
[  +14 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] Using gradle from E:\dev\example\android\gradlew.bat.
[  +11 ms] executing: E:\programs\Android\Android Studio\jre\bin\java -version
[ +134 ms] Exit code 0 from: E:\programs\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +1 ms] executing: [E:\dev\example\android/] E:\dev\example\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x64 -Ptarget=E:\dev\example\lib\main.dart
-Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1032 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +193 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[  +93 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[  +87 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:writeDebugAppMetadata UP-TO-DATE
[        ] > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
[ +501 ms] > Task :app:compressDebugAssets
[   +1 ms] Execution optimizations have been disabled for task ':app:compressDebugAssets' to ensure correctness due to the following reasons:
[        ]   - Gradle detected a problem with the following location: 'E:\dev\example\build\app\intermediates\assets\debug\mergeDebugAssets'. Reason: Task ':app:compressDebugAssets' uses this      
output of task ':app:copyFlutterAssetsDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[   +1 ms] > Task :app:packageDebug UP-TO-DATE
[        ] > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
[  +68 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[        ] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[        ] Please consult deprecation warnings for more details.
[        ] BUILD SUCCESSFUL in 1s
[        ] 35 actionable tasks: 5 executed, 30 up-to-date
[ +528 ms] Running Gradle task 'assembleDebug'... (completed in 2,676ms)
[ +340 ms] calculateSha: LocalDirectory: 'E:\dev\example\build\app\outputs\flutter-apk'/app.apk
[ +449 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +3 ms] executing: E:\programs\Android\Sdk\build-tools\33.0.0\aapt dump xmltree E:\dev\example\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +24 ms] Exit code 0 from: E:\programs\Android\Sdk\build-tools\33.0.0\aapt dump xmltree E:\dev\example\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.example" (Raw: "com.example.example")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="example" (Raw: "example")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.example.MainActivity" (Raw: "com.example.example.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +6 ms] Stopping app 'app.apk' on sdk gphone64 x86 64.
[        ] executing: E:\programs\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell am force-stop com.example.example
[  +52 ms] executing: E:\programs\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell pm list packages com.example.example
[  +44 ms] package:com.example.example
[   +1 ms] executing: E:\programs\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell cat /data/local/tmp/sky.com.example.example.sha1
[  +38 ms] e7d6d342b94b5b29cfba99fca62ca704a19dd2c3
[   +1 ms] Latest build already installed.
[        ] executing: E:\programs\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +73 ms] --------- beginning of main
           08-20 19:32:03.514 D/CarrierSvcBindHelper(  887): No carrier app for: 0
[   +4 ms] executing: E:\programs\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true com.example.example/com.example.example.MainActivity
[  +71 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.example/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +549 ms] Observatory URL on device: http://127.0.0.1:34165/V3g1IKaeDfQ=/
[   +1 ms] executing: E:\programs\Android\Sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:34165
[        ] D/skia    (14969): ------------------------
[        ] D/skia    (14969): Errors:
[        ] D/skia    (14969): link failed but did not provide an info log
[   +5 ms] D/skia    (14969): Shader compilation error
[        ] D/skia    (14969): ------------------------
[        ] D/skia    (14969): Errors:
[        ] D/skia    (14969): link failed but did not provide an info log
[   +6 ms] D/skia    (14969): Shader compilation error
[        ] D/skia    (14969): ------------------------
[        ] D/skia    (14969): Errors:
[   +1 ms] D/skia    (14969): link failed but did not provide an info log
[  +52 ms] The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:50415/io9EjeicMgc=/
```

</details>

**Comment by danagbemava-nc** [comment] 2022-08-22 10:08
Hi @lotusgate, this is indeed a duplicate of https://github.com/flutter/flutter/issues/105532. 

Kindly provide any other relevant info there and please upvote the issue.

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-08-22 10:08 UTC
Labels: in triage
