### ISSUE TITLE
[Question] More detail about the Widget causes "A RenderFlex overflowed by xx pixels on the right.. Error thrown during layout."

### ISSUE THREAD

**Issue by namnh-0652** [flutter/flutter#153074] opened 2024-08-08 04:04 UTC
### Steps to reproduce

There are some cases in the logic code that cause the widget to render issues such as `A RenderFlex overflowed by xx pixels on the right.. Error thrown during layout`. However, when I reported it using `FirebaseCrashlytics`, the `errorDetails` were not very helpful in identifying which widget caused this error. Do you have any suggestions or hints for logging the specific widget responsible for this error?

```dart
FlutterError.onError = (errorDetails) {
  FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
};
```

### Expected results

More detail about the widget caused the error.

### Actual results

Too much core rendered logs not related to application's code.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
FlutterError: A RenderFlex overflowed by xx pixels on the right.. Error thrown during layout

# Crashlytics - Stack trace
# Application: my.app
# Platform: apple
# Version: 1.0.0
# Issue: x
# Session: x
# Date: Thu Aug 08 2024 09:31:53 GMT+0700 (Indochina Time)

Fatal Exception: FlutterError
0   ???                            0x0 FirebaseCrashlytics.recordError + 119 (firebase_crashlytics.dart:119)
1   ???                            0x0 FirebaseCrashlytics.recordFlutterError + 145 (firebase_crashlytics.dart:145)
2   ???                            0x0 FirebaseCrashlytics.recordFlutterFatalError + 160 (firebase_crashlytics.dart:160)
3   ???                            0x0 initializeCrashlytics.<fn> + 219 (main.dart:219)
4   ???                            0x0 FlutterError.reportError + 1181 (assertions.dart:1181)
5   ???                            0x0 DebugOverflowIndicatorMixin._reportOverflow + 246 (debug_overflow_indicator.dart:246)
6   ???                            0x0 DebugOverflowIndicatorMixin.paintOverflowIndicator + 314 (debug_overflow_indicator.dart:314)
7   ???                            0x0 RenderFlex.paint.<fn> + 1063 (flex.dart:1063)
8   ???                            0x0 RenderFlex.paint + 1065 (flex.dart:1065)
9   ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
10  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
11  ???                            0x0 _RenderListTile.paint.doPaint + 1469 (list_tile.dart:1469)
12  ???                            0x0 _RenderListTile.paint + 1473 (list_tile.dart:1473)
13  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
14  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
15  ???                            0x0 RenderShiftedBox.paint + 74 (shifted_box.dart:74)
16  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
17  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
18  ???                            0x0 RenderShiftedBox.paint + 74 (shifted_box.dart:74)
19  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
20  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
21  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
22  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
23  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
24  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
25  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
26  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
27  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
28  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
29  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
30  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
31  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
32  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
33  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
34  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
35  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
36  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
37  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
38  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
39  ???                            0x0 RenderBoxContainerDefaultsMixin.defaultPaint + 3158 (box.dart:3158)
40  ???                            0x0 RenderFlex.paint + 1014 (flex.dart:1014)
41  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
42  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
43  ???                            0x0 RenderShiftedBox.paint + 74 (shifted_box.dart:74)
44  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
45  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
46  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
47  ???                            0x0 RenderDecoratedBox.paint + 2291 (proxy_box.dart:2291)
48  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
49  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
50  ???                            0x0 RenderBoxContainerDefaultsMixin.defaultPaint + 3158 (box.dart:3158)
51  ???                            0x0 RenderStack.paintStack + 633 (stack.dart:633)
52  ???                            0x0 RenderStack.paint + 649 (stack.dart:649)
53  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
54  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
55  ???                            0x0 RenderBoxContainerDefaultsMixin.defaultPaint + 3158 (box.dart:3158)
56  ???                            0x0 RenderStack.paintStack + 633 (stack.dart:633)
57  ???                            0x0 RenderStack.paint + 649 (stack.dart:649)
58  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
59  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
60  ???                            0x0 RenderBoxContainerDefaultsMixin.defaultPaint + 3158 (box.dart:3158)
61  ???                            0x0 RenderFlex.paint + 1014 (flex.dart:1014)
62  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
63  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
64  ???                            0x0 _RenderColoredBox.paint + 7826 (basic.dart:7826)
65  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
66  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
67  ???                            0x0 RenderBoxContainerDefaultsMixin.defaultPaint + 3158 (box.dart:3158)
68  ???                            0x0 RenderFlex.paint + 1014 (flex.dart:1014)
69  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
70  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
71  ???                            0x0 _RenderColoredBox.paint + 7826 (basic.dart:7826)
72  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
73  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
74  ???                            0x0 RenderSliverSingleBoxAdapter.paint + 1870 (sliver.dart:1870)
75  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
76  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
77  ???                            0x0 RenderViewportBase._paintContents + 757 (viewport.dart:757)
78  ???                            0x0 PaintingContext.pushLayer + 486 (object.dart:486)
79  ???                            0x0 PaintingContext.pushClipRect + 546 (object.dart:546)
80  ???                            0x0 RenderViewportBase.paint + 732 (viewport.dart:732)
81  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
82  ???                            0x0 PaintingContext._repaintCompositedChild + 166 (object.dart:166)
83  ???                            0x0 PaintingContext.repaintCompositedChild + 109 (object.dart:109)
84  ???                            0x0 PaintingContext._compositeChild + 261 (object.dart:261)
85  ???                            0x0 PaintingContext.paintChild + 242 (object.dart:242)
86  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
87  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
88  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
89  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
90  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
91  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
92  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
93  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
94  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
95  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
96  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
97  ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
98  ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
99  ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
100 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
101 ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
102 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
103 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
104 ???                            0x0 _RenderLayoutBuilder.paint + 356 (layout_builder.dart:356)
105 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
106 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
107 ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
108 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
109 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
110 ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
111 ???                            0x0 _RenderVisibility.paint + 594 (visibility.dart:594)
112 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
113 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
114 ???                            0x0 RenderIndexedStack.paintStack + 767 (stack.dart:767)
115 ???                            0x0 RenderStack.paint + 649 (stack.dart:649)
116 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
117 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
118 ???                            0x0 RenderBoxContainerDefaultsMixin.defaultPaint + 3158 (box.dart:3158)
119 ???                            0x0 RenderCustomMultiChildLayoutBox.paint + 409 (custom_layout.dart:409)
120 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
121 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
122 ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
123 ???                            0x0 _RenderInkFeatures.paint + 662 (material.dart:662)
124 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
125 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
126 ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
127 ???                            0x0 RenderPhysicalModel.paint.<fn> + 2033 (proxy_box.dart:2033)
128 ???                            0x0 PaintingContext.pushClipRRect + 575 (object.dart:575)
129 ???                            0x0 RenderPhysicalModel.paint + 2020 (proxy_box.dart:2020)
130 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
131 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
132 ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
133 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
134 ???                            0x0 PaintingContext.paintChild + 250 (object.dart:250)
135 ???                            0x0 RenderProxyBoxMixin.paint + 130 (proxy_box.dart:130)
136 ???                            0x0 RenderObject._paintWithContext + 3239 (object.dart:3239)
137 ???                            0x0 PaintingContext._repaintCompositedChild + 166 (object.dart:166)
138 ???                            0x0 PaintingContext.repaintCompositedChild + 109 (object.dart:109)
139 ???                            0x0 PipelineOwner.flushPaint + 1182 (object.dart:1182)
140 ???                            0x0 PipelineOwner.flushPaint + 1192 (object.dart:1192)
141 ???                            0x0 RendererBinding.drawFrame + 579 (binding.dart:579)
142 ???                            0x0 WidgetsBinding.drawFrame + 1138 (binding.dart:1138)
143 ???                            0x0 RendererBinding._handlePersistentFrameCallback + 443 (binding.dart:443)
144 ???                            0x0 SchedulerBinding._invokeFrameCallback + 1392 (binding.dart:1392)
145 ???                            0x0 SchedulerBinding.handleDrawFrame + 1313 (binding.dart:1313)
146 ???                            0x0 SchedulerBinding._handleDrawFrame + 1171 (binding.dart:1171)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment] 2024-08-08 08:51
Closing as duplicate of https://github.com/flutter/flutter/issues/151888

**Closed by darshankawar** 2024-08-08 08:51 UTC
Labels: in triage
