### ISSUE TITLE
ReorderableListView interactive/start time is slow

### ISSUE THREAD

**Issue by gctommy** [flutter/flutter#25065] opened 2018-12-07 06:32 UTC
## Steps to Reproduce

1. Open Google Chrome
2. Go to **Settings** > **Languages**
3. Drag any of the language choices, performance is instant
4. Open **Flutter Gallery** > **Material** > **Lists: reorderable**
5. Drag any item, has a delay before item is selected, then it can be dragged and re-ordered

Is there a way to improve the speed / performance of this widget?

**Comment by zoechi** [comment] 2018-12-07 07:34
Please add the output of `flutter doctor -v`.

**Comment by gctommy** [comment] 2018-12-07 07:43
````
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.407], locale en-GB)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (7 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = C:\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.4
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4733

[√] Connected device (1 available)
    • LG H860 • LGH86066ade69 • android-arm64 • Android 7.0 (API 24)

• No issues found!
````

**Comment by andreidiaconu** [comment] 2019-04-04 12:10
From looking at the code, the drag starts happening after a long press gesture, without any way of manually triggering the drag start. So it's not a performance issue, it was architected with the assumption that the user has to long-press on the item they want to move.

As highlighted by the example in this issue, this behavior is very limiting. 
More so, consider this: 

1. If we want the user to understand that the list can be reordered, a drag indicator like the one presented in [Material Design](https://material.io/design/components/lists.html#behavior) is going to be part of the UI in most cases (Otherwise, the reordering of items is a hidden gesture). 
2. Having the reorder handle on each item creates the expectation that simply dragging it will reorder the list, without the long-press gesture.

I'm trying to make the case that when a reorderable list is needed, the official widget for this is useless for most cases and would benefit from more control over initiating a drag gesture.

I've landed on this issue after trying to use this widget without the long-press gesture.

**Comment by robcleghorn** [comment] 2020-02-03 09:46
https://github.com/flutter/flutter/issues/36314

**Comment by Stainie** [comment] 2020-03-13 18:21
My solution was to create a custom draggable script, copy everything from Reorderable List and change LongPressDraggable widget with just Draggable (with all the parameters remaining the same)

**Comment by iapicca** [comment] 2020-04-09 12:26
Hi @gctommy 
as in this [sample](https://dartpad.dev/77dd46957eb6860f4a59354ca92dac39)
the code still behave as you describe in the latest master

```console
[✓] Flutter (Channel master, v1.18.0-5.0.pre.46, on Mac OS X 10.15.4 19E266, locale en-EE)
    • Flutter version 1.18.0-5.0.pre.46 at /Users/nevercode/development/flutter_master
    • Framework revision 0d459f2326 (8 hours ago), 2020-04-08 21:32:25 -0700
    • Engine revision 5b4b1f33c6
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 dcdc71d763)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

Thank you

**Comment by iapicca** [comment] 2020-07-24 10:13
Testing the [code above](https://github.com/flutter/flutter/issues/25065#issuecomment-611499794) with the latest master

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/nevercode/development/flutter_master
    • Framework revision e64fe11542 (9 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

the issue still occurs
Thank you

**Comment by MilesAdamson** [comment] 2022-03-21 04:25
My users actually think it is a bug that they must tap this long to drag items

**Comment by campovski** [comment] 2022-04-03 10:17
The current behaviour is as follows:

- On desktop tyou get a drag handle which you press and you can reorder instantly.
- On mobile, you have to do a long press and then can reorder.

I am not quite sure how you would like this to function, because on mobile device, if the immediate drag should move the list view, not reorder the tiles. How should the scrolling work then? As far as I see this, we could also add the drag handles to the mobile, or not make the list scrollable.

I can implement the fix, but I would like to know the desired behaviour. Maybe I missed something as well.

**Comment by campovski** [comment] 2022-04-06 18:32
@mtc-jed I will expose the "long-press" duration argument and submit a PR soon, I just want to make sure nothing is going to be broken by it.

**Comment by MilesAdamson** [comment] 2022-04-12 16:31
> I am not quite sure how you would like this to function, because on mobile device, the immediate drag should move the list view, not reorder the tiles. How should the scrolling work then? As far as I see this, we could also add the drag handles to the mobile, or not make the list scrollable.

Ideally I would like it to behave as material has designed it

https://kstatic.googleusercontent.com/files/3b4f47c77955908daec564c62deebb0a1ea2e1dab3cd664580613d4e86675780f36b558adc40d13758e6fa0f8e505398e80ec51f922e1177d0447727077b63f6

You drag the handle, it drags instantly. You drag the list tile, the list scrolls.

In my current project I have copied and modified the material `ReorderableListView` to make 2 simple changes:
- The drag handle is the only part which accepts a drag gesture
- On all platforms, the `ReorderableDragStartListener` is used instead of the one which requires a long tap

```
    return Row(
      key: itemGlobalKey,
      children: [
        Expanded(child: itemWithSemantics),
        ReorderableDragStartListener(
          index: index,
          child: const Padding(
            padding: EdgeInsets.symmetric(horizontal: 32.0),
            child: Icon(
              Icons.drag_handle,
              size: 30.0,
            ),
          ),
        ),
      ],
    );
```

**Comment by campovski** [comment] 2022-04-13 10:42
@MilesAdamson I will add the boolean argument `showDefaultDragHandles` which is by default going to be `false` for backward compatibility but setting this to `true` would add the drag handles to all platforms. Sounds good?

P.S.: I will update the PR linked above, so that a user will also be able to change the duration of delayed drag.

**Comment by maheshmnj** [comment] 2023-01-13 05:13
Hello @gctommy this is not really a performance issue and it is working as intended as mentioned by @andreidiaconu https://github.com/flutter/flutter/issues/25065#issuecomment-479871384 

On Desktop platforms the drag handles are visible by default to drag the listview (without longpress) However we can achieve similar behavior on the mobile platforms using [ReorderableDragStartListener](https://api.flutter.dev/flutter/widgets/ReorderableDragStartListener-class.html)
> A wrapper widget that will recognize the start of a drag on the wrapped widget by a [PointerDownEvent](https://api.flutter.dev/flutter/gestures/PointerDownEvent-class.html), and immediately initiate dragging the wrapped item to a new location in a reorderable list.

chrome | flutter (with DragHandles) | flutter (without DragHandles)
:-: | :-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/212241456-b7632cc0-a81c-4a37-99c6-85287d6b0ecf.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/212241463-dbaff515-1690-4b5b-85ec-3a9eac046400.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/212242038-7b79e4e6-d2c5-49db-b36d-e0bc41389ab5.mov' width=180/> 

<details>
<summary>code sample (With Drag Handles)</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(const ReorderableApp());

class ReorderableApp extends StatelessWidget {
  const ReorderableApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('ReorderableListView Sample')),
        body: const ReorderableExample(),
      ),
    );
  }
}

class ReorderableExample extends StatefulWidget {
  const ReorderableExample({super.key});

  @override
  State<ReorderableExample> createState() => _ReorderableExampleState();
}

class _ReorderableExampleState extends State<ReorderableExample> {
  final List<int> _items = List<int>.generate(50, (int index) => index);

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = Theme.of(context).colorScheme;
    final Color oddItemColor = colorScheme.secondary.withOpacity(0.05);
    final Color evenItemColor = colorScheme.secondary.withOpacity(0.15);
    final Color draggableItemColor = colorScheme.secondary;

    Widget proxyDecorator(
        Widget child, int index, Animation<double> animation) {
      return AnimatedBuilder(
        animation: animation,
        builder: (BuildContext context, Widget? child) {
          final double animValue = Curves.easeInOut.transform(animation.value);
          final double elevation = lerpDouble(0, 6, animValue)!;
          return Material(
            elevation: elevation,
            color: draggableItemColor,
            shadowColor: draggableItemColor,
            child: child,
          );
        },
        child: child,
      );
    }

    return ReorderableListView(
      padding: const EdgeInsets.symmetric(horizontal: 40),
      children: <Widget>[
        for (int index = 0; index < _items.length; index += 1)
          ListTile(
            key: Key('$index'),
            tileColor: _items[index].isOdd ? oddItemColor : evenItemColor,
            title: Text('Item ${_items[index]}'),
            trailing: ReorderableDragStartListener(
              key: ValueKey<int>(_items[index]),
              index: index,
              child: const Icon(Icons.drag_handle),
            ),
          ),
      ],
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },
    );
  }
}

```
</details> 

<details>
<summary>code sample (without drag handles)</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(const ReorderableApp());

class ReorderableApp extends StatelessWidget {
  const ReorderableApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('ReorderableListView Sample')),
        body: const ReorderableExample(),
      ),
    );
  }
}

class ReorderableExample extends StatefulWidget {
  const ReorderableExample({super.key});

  @override
  State<ReorderableExample> createState() => _ReorderableExampleState();
}

class _ReorderableExampleState extends State<ReorderableExample> {
  final List<int> _items = List<int>.generate(50, (int index) => index);

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = Theme.of(context).colorScheme;
    final Color oddItemColor = colorScheme.secondary.withOpacity(0.05);
    final Color evenItemColor = colorScheme.secondary.withOpacity(0.15);
    final Color draggableItemColor = colorScheme.secondary;

    Widget proxyDecorator(
        Widget child, int index, Animation<double> animation) {
      return AnimatedBuilder(
        animation: animation,
        builder: (BuildContext context, Widget? child) {
          final double animValue = Curves.easeInOut.transform(animation.value);
          final double elevation = lerpDouble(0, 6, animValue)!;
          return Material(
            elevation: elevation,
            color: draggableItemColor,
            shadowColor: draggableItemColor,
            child: child,
          );
        },
        child: child,
      );
    }

    return ReorderableListView(
      padding: const EdgeInsets.symmetric(horizontal: 40),
      proxyDecorator: proxyDecorator,
      buildDefaultDragHandles: true,
      children: <Widget>[
        for (int index = 0; index < _items.length; index += 1)
          ReorderableDragStartListener(
            key: ValueKey<int>(_items[index]),
            index: index,
            child: ListTile(
              key: Key('$index'),
              tileColor: _items[index].isOdd ? oddItemColor : evenItemColor,
              title: Text('Item ${_items[index]}'),
            ),
          ),
      ],
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

So, I believe that this is working as intended and the desired behavior can be achieved with the help of existing APIs, I am going to close this issue as invalid, if anyone thinks this is still a bug please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2023-01-13 05:13 UTC
Labels: framework, f: material design, a: fidelity, f: gestures, has reproducible steps, P4, found in release: 1.21
