### ISSUE TITLE
Crash when resizing "flutter create" app on Linux/X11

### ISSUE THREAD

**Issue by CyberShadow** [flutter/flutter#131405] opened 2023-07-27 13:17 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install flutter on Linux/X11
2. Run `flutter create my_app`
3. Run `cd my_app`
4. Run `flutter run -d linux`
5. Resize the window around a bit

### Expected results

Should not crash.

### Actual results

Crashes.

### Code sample

No code changes since creating with `flutter create`.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/160894/1d6940b2-2a0b-4747-a3fd-e41229c7d2fe

</details>

### Logs

<details><summary>Logs</summary>

```console
[   +4 ms] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +10 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[  +16 ms] Exit code 0 from: git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] 3.10.6
[   +3 ms] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +13 ms] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +50 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +35 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +73 ms] Skipping pub get: version match.
[ +103 ms] Generating /home/vladimir/tmp/2023-07-27b/my_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +58 ms] Initializing file store
[   +5 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/vladimir/tmp/2023-07-27b/my_app/.dart_tool/package_config_subset}
[  +18 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib/main.dart on Linux in debug mode...
[   +2 ms] /mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/cdbeda788a293fa29665dc3fa3d6e63bd221cb0d/ --output-dill /tmp/flutter_tools.TTJXBH/flutter_tool.QOFBIA/app.dill --packages /home/vladimir/tmp/2023-07-27b/my_app/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/ade00fc64fa695e0daed02c1105f6d67.cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +18 ms] Building Linux application...
[  +10 ms] <- compile package:my_app/main.dart
[   +1 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/vladimir/tmp/2023-07-27b/my_app/linux
[  +49 ms] -- Configuring done (0.0s)
[   +2 ms] -- Generating done (0.0s)
[  +10 ms] -- Build files have been written to: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug
[   +7 ms] executing: ninja -C build/linux/x64/debug install
[   +6 ms] ninja: Entering directory `build/linux/x64/debug'
[+1461 ms] [1/5] Generating /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/vladimir/tmp/2023-07-27b/my_app/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +2 ms] [   +2 ms] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +11 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] [        ] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] [  +14 ms] Exit code 0 from: git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] [        ] 3.10.6
[        ] [   +3 ms] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +12 ms] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] [        ] origin/stable
[        ] [        ] executing: [/mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [        ] executing: uname -m
[        ] [   +2 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +19 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +62 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +30 ms] Initializing file store
[        ] [   +4 ms] Done initializing file store
[        ] [  +27 ms] Skipping target: gen_localizations
[        ] [   +7 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +324 ms] Skipping target: unpack_linux
[        ] [ +223 ms] Skipping target: kernel_snapshot
[        ] [ +157 ms] Skipping target: debug_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [   +6 ms] "flutter assemble" took 862ms.
[        ] [ +172 ms] ensureAnalyticsSent: 162ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +395 ms] [2/5] Building CXX object CMakeFiles/my_app.dir/flutter/generated_plugin_registrant.cc.o
[  +23 ms] [3/5] Building CXX object CMakeFiles/my_app.dir/my_application.cc.o
[ +120 ms] [4/5] Linking CXX executable intermediates_do_not_run/my_app
[        ] [4/5] Install the project...
[   +9 ms] -- Install configuration: "Debug"
[   +5 ms] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/my_app
[        ] -- Set runtime path of "/home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/my_app" to "$ORIGIN/lib"
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/icudtl.dat
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/shaders
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/shaders/ink_sparkle.frag
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.bin
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[  +10 ms] Building Linux application... (completed in 2,115ms)
[ +248 ms] VM Service URL on device: http://127.0.0.1:38739/pboogzaWt1E=/
[   +4 ms] Caching compiled dill
[  +29 ms] Connecting to service protocol: http://127.0.0.1:38739/pboogzaWt1E=/
[  +99 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:38739/pboogzaWt1E=/.
[  +51 ms] DDS is listening at http://127.0.0.1:39621/CxR4A0ZSZ2c=/.
[  +38 ms] Successfully connected to service protocol: http://127.0.0.1:38739/pboogzaWt1E=/
[ +188 ms] DevFS: Creating new filesystem on the device (null)
[  +16 ms] DevFS: Created new filesystem on the device (file:///tmp/my_appPOIYCT/my_app/)
[   +2 ms] Updating assets
[  +63 ms] Syncing files to device Linux...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:my_app/main.dart 16c41478-00f4-4775-ba67-fd99c22eada7
[        ] <- 16c41478-00f4-4775-ba67-fd99c22eada7
[        ] Bundle processing done.
[  +57 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 60ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +1 ms] Connected to _flutterView/0x5650706ea2d0.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] A Dart VM Service on Linux is available at: http://127.0.0.1:39621/CxR4A0ZSZ2c=/
[ +352 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:39621/CxR4A0ZSZ2c=/
[+2997 ms] ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
                    The following assertion was thrown during layout:
                    A RenderFlex overflowed by 17 pixels on the bottom.
                    
                    The relevant error-causing widget was:
                      Column Column:file:///home/vladimir/tmp/2023-07-27b/my_app/lib/main.dart:92:16
                    
                    To inspect this widget in Flutter DevTools, visit:
                    http://127.0.0.1:9100/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A39621%2FCxR4A0ZSZ2c%3D%2F&inspectorRef=inspector-0
                    
                    The overflowing RenderFlex has an orientation of Axis.vertical.
                    The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
                    black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
                    Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
                    RenderFlex to fit within the available space instead of being sized to their natural size.
                    This is considered an error condition because it indicates that there is content that cannot be
                    seen. If the content is legitimately bigger than the available space, consider clipping it with a
                    ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
                    like a ListView.
                    The specific RenderFlex in question is: RenderFlex#55d8e relayoutBoundary=up2 OVERFLOWING:
                      creator: Column ← Center ← KeyedSubtree-[GlobalKey#99c31] ← _BodyBuilder ← MediaQuery ←
                        LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← _ActionsScope ← Actions ←
                        AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← ⋯
                      parentData: offset=Offset(484.5, 0.0) (can use size)
                      constraints: BoxConstraints(0.0<=w<=1259.0, 0.0<=h<=39.0)
                      size: Size(290.0, 39.0)
                      direction: vertical
                      mainAxisAlignment: center
                      mainAxisSize: max
                      crossAxisAlignment: center
                      verticalDirection: down
                    ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[+4290 ms] ../../third_party/dart/runtime/vm/os_linux.cc: 456: error: unreachable code
[        ] version=3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "linux_x64"
[        ] pid=3905145, thread=3905162, isolate_group=main(0x7f9e1c2bdeb0), isolate=main(0x7f9e1c2a7f80)
[        ] os=linux, arch=x64, comp=no, sim=no
[        ] isolate_instructions=7f9e77166f40, vm_instructions=7f9e77166f40
[        ] fp=7f9e327fa810, sp=7f9e327fa6e0, pc=7f9e7729b17c
[        ]   pc 0x00007f9e7729b17c fp 0x00007f9e327fa810 /home/vladimir/tmp/2023-07-27b/my_app/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so+0x209b17c
[        ] -- End of DumpStackTrace
[        ]   pc 0x0000000000000000 fp 0x00007f9e327fb2b8 sp 0x0000000000000000 Cannot find code object
[        ]   pc 0x00007f9d1f1f1dad fp 0x00007f9e327fb2e8 sp 0x00007f9e327fb2c8 [Optimized] FfiTrampoline___render$Method$FfiNative$Ptr
[        ]   pc 0x00007f9d1f1f1b08 fp 0x00007f9e327fb338 sp 0x00007f9e327fb2f8 [Unoptimized] FlutterView._render@15065589
[        ]   pc 0x00007f9d1f1f19eb fp 0x00007f9e327fb370 sp 0x00007f9e327fb348 [Unoptimized] FlutterView.render
[        ]   pc 0x00007f9d1f1e35eb fp 0x00007f9e327fb3e0 sp 0x00007f9e327fb380 [Unoptimized] RenderView.compositeFrame
[        ]   pc 0x00007f9d1f46deaa fp 0x00007f9e327fb418 sp 0x00007f9e327fb3f0 [Unoptimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding@510399801.drawFrame
[        ]   pc 0x00007f9d1f465e07 fp 0x00007f9e327fb470 sp 0x00007f9e327fb428 [Unoptimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding@510399801.drawFrame
[        ]   pc 0x00007f9d1f46588f fp 0x00007f9e327fb4a8 sp 0x00007f9e327fb480 [Unoptimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding@510399801._handlePersistentFrameCallback@387452173
[        ]   pc 0x00007f9d1f4657ca fp 0x00007f9e327fb4e8 sp 0x00007f9e327fb4b8 [Unoptimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding@510399801._handlePersistentFrameCallback@387452173
[        ]   pc 0x00007f9d1f465355 fp 0x00007f9e327fb590 sp 0x00007f9e327fb4f8 [Unoptimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding@510399801._invokeFrameCallback@430222615
[        ]   pc 0x00007f9d1f464353 fp 0x00007f9e327fb610 sp 0x00007f9e327fb5a0 [Unoptimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding@510399801.handleDrawFrame
[        ]   pc 0x00007f9d1e842827 fp 0x00007f9e327fb648 sp 0x00007f9e327fb620 [Unoptimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding@510399801._handleDrawFrame@430222615
[        ]   pc 0x00007f9d1e842637 fp 0x00007f9e327fb680 sp 0x00007f9e327fb658 [Unoptimized] _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding@510399801._handleDrawFrame@430222615
[        ]   pc 0x00007f9e0090efbe fp 0x00007f9e327fb6b8 sp 0x00007f9e327fb690 [Unoptimized] _invoke@15065589
[        ]   pc 0x00007f9e0096f9a6 fp 0x00007f9e327fb6f8 sp 0x00007f9e327fb6c8 [Unoptimized] PlatformDispatcher._drawFrame@15065589
[        ]   pc 0x00007f9e0096f8ac fp 0x00007f9e327fb728 sp 0x00007f9e327fb708 [Unoptimized] _drawFrame@15065589
[        ]   pc 0x00007f9e0096f806 fp 0x00007f9e327fb750 sp 0x00007f9e327fb738 [Unoptimized] _drawFrame@15065589
[        ]   pc 0x00007f9e50202f0c fp 0x00007f9e327fb7c0 sp 0x00007f9e327fb760 [Stub] InvokeDartCode
[  +27 ms] Service protocol connection closed.
[        ] Lost connection to device.
[        ] DevFS: Deleting filesystem on the device (file:///tmp/my_appPOIYCT/my_app/)
[ +252 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed

[   +2 ms] "flutter run" took 11,202ms.
[  +52 ms] ensureAnalyticsSent: 46ms
[        ] Running 1 shutdown hook
[   +7 ms] Shutdown hooks complete
[        ] exiting with code 0
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on Arch Linux 6.4.4-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/vladimir/opt/adt/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.27.0
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /mnt/2020-nvme-2t-raid/@fastscratch/moved/home/vladimir/opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /usr/share/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • IN2023 (mobile) • 2b161d8a • android-arm64 • Android 12 (API 32)
    • Linux (desktop) • linux    • linux-x64     • Arch Linux 6.4.4-arch1-1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment] 2023-07-28 06:27
Hi @CyberShadow 
I'm using X11 but it's Ubuntu distro. I also see the overflowed stack trace as well, it's an expected exception from the framework since window size is smaller than app content. 

But I can't reproduce the crash on my end. Labeling the issue for the investigation. It will be worth checking out the latest master channel from your side. Thanks!

**Comment by CyberShadow** [comment] 2023-07-28 06:48
Hi @huycozy, thanks for the quick response!

I have investigated it a bit on my end and identified the root cause. It was a LD_PRELOAD library that was intercepting `clock_gettime` calls. Sometimes, libraries are loaded in such a way that when the library tries to forward the call to glibc, it ends up in itself again, and to avoid infinite recursion it returns `EAGAIN`. However, the Dart Linux runtime panics if it sees `clock_gettime` return an error.

Though hypothetically the Dart runtime could be changed to handle the case of `clock_gettime` failing, it is a very unusual case, so feel free to close this issue.

**Comment by huycozy** [comment] 2023-07-28 07:07
Glad to see you solved the issue. Since this's an unusual case, I will close this. Your investigation may be useful to others who encounter it later. Thanks!

**Closed by huycozy** 2023-07-28 07:07 UTC
Labels: c: crash, engine, dependency: dart, platform-linux, a: desktop, c: fatal crash, team-desktop
