### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout:Stderr:/var/folders/mh/xjyz1d8n3pq40y4g80974g4w0000gn/T/flutter_tools.jVVFST/flutter_FlutterMacOS.framework.zip.Rgb41F/Versions/A/FlutterMacOS:  write error (disk full?).  Continue? (y/n/^C) warning:  /var/folders/mh/xjyz1d8n3pq40y4g80974g4w0000gn/T/flutter_tools.jVVFST/flutter_FlutterMacOS.framework.zip.Rgb41F/Versions/A/FlutterMacOS is probably truncated Command: unzip, OS error code: 50

### ISSUE THREAD

**Issue by peteCoder** [flutter/flutter#122975] opened 2023-03-19 16:34 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed
Stdout:

Stderr:
/var/folders/mh/xjyz1d8n3pq40y4g80974g4w0000gn/T/flutter_tools.jVVFST/flutter_FlutterMacOS.framework.zip.Rgb41F/Versions/A/FlutterMacOS:  write error (disk full?).  Continue? (y/n/^C) 
warning:  /var/folders/mh/xjyz1d8n3pq40y4g80974g4w0000gn/T/flutter_tools.jVVFST/flutter_FlutterMacOS.framework.zip.Rgb41F/Versions/A/FlutterMacOS is probably truncated
 Command: unzip, OS error code: 50
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:126:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:414:17)
#2      _MacOSUtils.unzip (package:flutter_tools/src/base/os.dart:438:23)
#3      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:917:30)
<asynchronous suspension>
#4      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
<asynchronous suspension>
#5      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1376:7)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.7, on macOS 11.0.1 20B50 darwin-x64, locale en-NG)
    [32m•[39m Flutter version 3.7.7 on channel stable at /Users/tslnigeria/Documents/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2ad6cd72c0 (11 days ago), 2023-03-08 09:41:59 -0800
    [32m•[39m Engine revision 1837b5be5f
    [32m•[39m Dart version 2.19.4
    [32m•[39m DevTools version 2.20.1

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    [32m•[39m Android SDK at /Users/tslnigeria/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 12.5.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 12E507
    [31m✗[39m Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.74.3)
    [32m•[39m VS Code at /Users/tslnigeria/Downloads/Visual Studio Code 2.app/Contents
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m VS Code (version 1.74.3)
    [32m•[39m VS Code at /Users/tslnigeria/Downloads/Visual Studio Code 3.app/Contents
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m VS Code (version 1.74.3)
    [32m•[39m VS Code at /Users/tslnigeria/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 11.0.1 20B50 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment] 2023-03-20 07:45
Closing this as a duplicate of https://github.com/flutter/flutter/issues/106606

Kindly subscribe to the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2023-03-20 07:45 UTC
Labels: in triage
