### ISSUE TITLE
Gradle.Exception symbol can't be resolved in android\app\build.gradle files (Flutter app) 

### ISSUE THREAD

**Issue by abodamin** [flutter/flutter#43195] opened 2019-10-21 19:22 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment] 2019-10-22 07:37
Hello @abodamin !

Thank you for posting.
However, without any additional information, such as the description of the problem, code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.

But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-10-22 07:37 UTC
