### ISSUE TITLE
Snap Pinned SliverAppBar doesn't hide (NestedScrollView + SliverAppBar + RefreshIndicator + ScrollController)

### ISSUE THREAD

**Issue by samuelg123** [flutter/flutter#31898] opened 2019-05-01 10:40 UTC
## Steps to Reproduce

Hi, I have a problem. When I add ScrollController into SingleChildScrollView, SliverAppBar not hiding anymore. I need scrollcontroller to achieve infinite scroll / load more. 

1. Create NestedScrollView > headerSliverBuilder: SliverAppBar + body: RefreshIndicator > SingleChildScrollView> ScrollController (Look at sample code) 
2. Scroll down / vertically. SliverAppBar won't hiding.

### Sample Code
```dart
return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder: (context, innerBoxScrolled) => [
          SliverAppBar(
            floating: true,
            pinned: true,
            snap: true,
            title: SingleChildScrollView(
              physics: NeverScrollableScrollPhysics(),
              child: Align(
                alignment: Alignment.centerLeft,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    ...
                  ],
                ),
              ),
            ),
            iconTheme: IconThemeData(color: Color.fromARGB(255, 5, 5, 5)),
            backgroundColor: Colors.white,
            elevation: 1,
            bottom: PreferredSize(
              preferredSize: const Size.fromHeight(105.0),
              child: Material(
                elevation: 1,
                color: Colors.white,
                child: Column(
                  children: <Widget>[
                    ...
                  ],
                ),
              ),
            ),
          ),
        ],
        body: RefreshIndicator(
          key: refreshKey,
          onRefresh: () {
            _dispatchRefresh();
            loadingCompleted = Completer();
            return loadingCompleted.future;
          },
          child: SingleChildScrollView(
            controller: _scrollController,//This is the problem. When I remove this line it should work again.
            child: Column(
              children: <Widget>[
                ...
              ],
            ),
          ),
        ),
      ),
    );
```

## Logs

```
   info - Unused import: 'package:aaa/ui/pages/markdown_page.dart' - lib\ui\pages\about_page.dart:1:8 - unused_import
   info - Unused import: 'package:aaa/app.dart' - lib\ui\pages\home_page.dart:1:8 - unused_import
   info - Unused import: 'package:aaa/ui/pages/contact_us_page.dart' - lib\ui\pages\home_page.dart:5:8 - unused_import
   info - The method '_clearCache' isn't used - lib\ui\pages\home_page.dart:44:8 - unused_element
   info - Unused import: 'package:aaa/utils/uidata.dart' - lib\ui\widgets\round_background.dart:2:8 - unused_import
   info - Unused import: 'package:aaa/main.dart' - test\widget_test.dart:11:8 - unused_import

6 issues found. (ran in 5.8s)
```

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.2.1 at C:\Android\flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\...\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.1

• No issues found!
```

**Comment by v7lin** [comment] 2019-08-23 00:47
i have same issue

**Comment by v7lin** [comment] 2019-08-23 06:10
i have slove it
```dart
...
RefreshIndicator(
  displacement: NestedScrollView.sliverOverlapAbsorberHandleFor(context).layoutExtent + 40,
  child: CustomScrollView(
    key: PageStorageKey<String>(widget.name),
    physics: AlwaysScrollableScrollPhysics(),
    slivers: <Widget>[
      SliverOverlapInjector(
        handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
      ),
      SliverPadding(
        padding: const EdgeInsets.all(8.0),
        sliver: SliverFixedExtentList(
          delegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              return ListTile(
                title: Text('Item $index'),
              );
            },
            childCount: _childCount,
          ),
          itemExtent: 48.0,
        ),
      ),
    ],
  ),
  onRefresh: () async {
    ...
  },
);
...
```

**Comment by samuelg123** [comment] 2019-09-19 07:45
@v7lin Thanks!! I'll try that

**Comment by BondarenkoStas** [comment] 2019-10-15 15:14
@samuelg123 did it work for you?

**Comment by samuelg123** [comment] 2019-10-19 16:41
@BondarenkoStas It still didn't work. I think we have different issue. I'm using NestedScrollView and @v7lin is using CustomScrollView.


Please try this example https://gist.github.com/samuelg123/0da30da4d984d9754229276a94f926af

### flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.38.1)
[√] Connected device (2 available)
```

Thanks!

**Comment by petermichaux** [comment] 2019-12-14 20:47
@samuelg123 Any success with this?

**Comment by Piinks** [comment] 2020-07-14 21:36
In the OP, the reproduction points out that passing a `ScrollController` to the inner scrollable, or `NestedScrollView.body`, is what breaks the code. This is actually working as intended, as the `NestedScrollView` creates and manages the `ScrollController`s for the inner and outer scrollables in order to keep them in sync and moving together as one scroll view.

https://github.com/flutter/flutter/issues/11271 provides a bit more context for this. 

[`NestedScrollView. controller`](https://api.flutter.dev/flutter/widgets/NestedScrollView/controller.html) allows you to set the _outer_ `ScrollController`. If you would like to access the outer/inner scroll controllers, there is an example in [`NestedScrollViewState`](https://api.flutter.dev/flutter/widgets/NestedScrollViewState-class.html). 

I am going to close this as WAI, but if you feel this does not solve your issue, let us know and we can re-open it! Thanks! :)

**Closed by Piinks** 2020-07-14 21:36 UTC
Labels: customer: crowd, f: scrolling, found in release: 1.12, found in release: 1.17, found in release: 1.18, framework, has reproducible steps

**Comment by dvaldivia** [comment] 2021-02-27 22:35
@v7lin your solution keeps showing me
```
NestedScrollView.sliverOverlapAbsorberHandleFor must be called with a context that contains a NestedScrollView.
```

even if this is in the body of the NestedScrolLView, any idea why?

**Comment by dvaldivia** [comment] 2021-02-27 22:43
@Piinks but even if you try to access the inner scroll controller with the example, there's no clear path for adding listener to the inner scroll controller to start the infinite scroll requests
