### ISSUE TITLE
Error Message: The camera device has encountered a serious error

### ISSUE THREAD

**Issue by AFwcxx** [flutter/flutter#55434] opened 2020-04-23 03:40 UTC
There seems to be a problem when recording video.
I'm getting the following error on Android. iOS seems to work fine.
The following error only shows up when the video recording is "stopped".
It doesn't show while it was recording.

```
I/CameraDeviceState(23755): Legacy camera service transitioning to state IDLE
I/CameraDeviceState(23755): Legacy camera service transitioning to state CONFIGURING

I/RequestThread-0(23755): Configure outputs: 2 surfaces configured.

E/BufferQueueProducer(23755): [unnamed-23755-22] cancelBuffer: slot 1 is not owned by the producer (state = 0)
E/BufferQueueProducer(23755): [unnamed-23755-22] cancelBuffer: slot 2 is not owned by the producer (state = 0)
E/BufferQueueProducer(23755): [unnamed-23755-22] cancelBuffer: slot 3 is not owned by the producer (state = 3)

D/Camera  (23755): app passed NULL surface

I/CameraDeviceState(23755): Legacy camera service transitioning to state IDLE
I/RequestQueue(23755): Repeating capture request set.

W/LegacyRequestMapper(23755): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyRequestMapper(23755): Only received metering rectangles with weight 0.
W/LegacyRequestMapper(23755): Only received metering rectangles with weight 0.

I/CameraDeviceState(23755): Legacy camera service transitioning to state CAPTURING
D/ViewRootImpl(23755): ViewPostImeInputStage ACTION_DOWN
E/[EGL-ERROR](23755): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0x96a35808; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/[EGL-ERROR](23755): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0x96a35808; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/[EGL-ERROR](23755): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0x96a35808; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/[EGL-ERROR](23755): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0x96a35808; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3

E/CameraDeviceGLThread-0(23755): Received exception on GL render thread:
E/CameraDeviceGLThread-0(23755): java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
E/CameraDeviceGLThread-0(23755): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
E/CameraDeviceGLThread-0(23755): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
E/CameraDeviceGLThread-0(23755): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:729)
E/CameraDeviceGLThread-0(23755): 	at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
E/CameraDeviceGLThread-0(23755): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/CameraDeviceGLThread-0(23755): 	at android.os.Looper.loop(Looper.java:145)
E/CameraDeviceGLThread-0(23755): 	at android.os.HandlerThread.run(HandlerThread.java:61)

I/CameraDeviceState(23755): Legacy camera service transitioning to state ERROR

E/CameraCaptureSession(23755): Session 1: Exception while stopping repeating:
E/CameraCaptureSession(23755): android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error
E/CameraCaptureSession(23755): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1478)
E/CameraCaptureSession(23755): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:677)
E/CameraCaptureSession(23755): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:336)
E/CameraCaptureSession(23755): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:480)
E/CameraCaptureSession(23755): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:290)
E/CameraCaptureSession(23755): 	at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:283)
E/CameraCaptureSession(23755): 	at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
E/CameraCaptureSession(23755): 	at io.flutter.plugins.camera.Camera.stopVideoRecording(Camera.java:373)
E/CameraCaptureSession(23755): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:93)
E/CameraCaptureSession(23755): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/CameraCaptureSession(23755): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/CameraCaptureSession(23755): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/CameraCaptureSession(23755): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CameraCaptureSession(23755): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/CameraCaptureSession(23755): 	at android.os.Looper.loop(Looper.java:130)
E/CameraCaptureSession(23755): 	at android.app.ActivityThread.main(ActivityThread.java:6939)
E/CameraCaptureSession(23755): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(23755): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/CameraCaptureSession(23755): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/CameraCaptureSession(23755): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

I/flutter (23755): Error: videoRecordingFailed
I/flutter (23755): Error Message: The camera device has encountered a serious error
E/RequestThread-0(23755): Timed out while waiting for request to complete.

W/CaptureCollector(23755): Preview buffers dropped for request: 1
E/CameraDeviceState(23755): Cannot receive result while in state: 0
E/CameraDeviceState(23755): Cannot receive result while in state: 0
E/CameraDeviceState(23755): Cannot receive result while in state: 0

W/MessageQueue(23755): Handler (android.graphics.SurfaceTexture$1) {117b20a9} sending message to a Handler on a dead thread
W/MessageQueue(23755): java.lang.IllegalStateException: Handler (android.graphics.SurfaceTexture$1) {117b20a9} sending message to a Handler on a dead thread
W/MessageQueue(23755): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
W/MessageQueue(23755): 	at android.os.Handler.enqueueMessage(Handler.java:631)
W/MessageQueue(23755): 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
W/MessageQueue(23755): 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
W/MessageQueue(23755): 	at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
W/MessageQueue(23755): 	at android.os.Handler.sendEmptyMessage(Handler.java:519)
W/MessageQueue(23755): 	at android.graphics.SurfaceTexture.postEventFromNative(SurfaceTexture.java:368)

E/BufferQueueProducer(23755): [unnamed-23755-23] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23755): [unnamed-23755-23] queueBuffer: BufferQueue has been abandoned

E/BufferQueueProducer(23755): [unnamed-23755-23] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23755): [unnamed-23755-23] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23755): [unnamed-23755-23] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23755): [unnamed-23755-23] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23755): [unnamed-23755-23] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23755): [unnamed-23755-23] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23755): [unnamed-23755-23] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23755): [unnamed-23755-23] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23755): [unnamed-23755-23] cancelBuffer: BufferQueue has been abandoned
```

`flutter doctor -v`:
[✓] Flutter (Channel master, v1.18.0-7.0.pre.44, on Mac OS X 10.15.4 19E266, locale en-MY)
    • Flutter version 1.18.0-7.0.pre.44 at /Users/afwcxx/flutter
    • Framework revision a091206ed1 (32 minutes ago), 2020-04-22 20:03:01 -0700
    • Engine revision d3f1c08f52
    • Dart version 2.9.0 (build 2.9.0-2.0.dev 64b8ded48b)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/afwcxx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by AFwcxx** [comment] 2020-04-23 09:49
Identified that Android 7 and above seems to have no issue.
Which are SDK API level 24 and above.

**Comment by TahaTesser** [comment] 2020-04-23 12:00
Hi @AFwcxx 
can you please provide your `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank yo

**Comment by AFwcxx** [comment] 2020-04-23 14:07
Hi @TahaTesser
`flutter run --verbose` output is in the attachment.
[flutter_run-verbose.txt](https://github.com/flutter/flutter/files/4522709/flutter_run-verbose.txt)
The error pops up in the output file at line 1002.
That's when I tap on the stop icon to stop the recording.

The code example is from example provided from the [camera package doc](https://pub.dev/packages/camera#-example-tab-)

**Comment by TahaTesser** [comment] 2020-04-24 07:24
Hi @AFwcxx 
Thank you for providing logs
Looks similar to [#40519](https://github.com/flutter/flutter/issues/40519) from logs
Closing as duplicate of [#40519](https://github.com/flutter/flutter/issues/40519)

**Closed by TahaTesser** 2020-04-24 07:24 UTC
Labels: in triage

**Comment by AkhilSaji** [comment] 2020-05-20 18:48
i got this issue too

**Comment by ashokYadav0311** [comment] 2020-06-18 18:51
is there any workaround for this.....

**Comment by duranapdan** [comment] 2020-07-29 11:30
Anyone find the solution ?

**Comment by duranapdan** [comment] 2020-07-29 11:43
after record :Error Message: The camera device has encountered a serious error

**Comment by duranapdan** [comment] 2020-07-29 11:44
Samsung S5 after record :Error Message:  The camera device has encountered a serious error -> screen is freezing.

**Comment by TahaTesser** [comment] 2020-07-29 12:07
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by duranapdan** [comment] 2020-07-30 07:30
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.388], locale tr-TR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] Connected device (1 available)


  video_player: ^0.10.11+2
  camera: ^0.5.8+1
  path_provider: ^1.6.8

an error pops up the moment I finish the video.

I/flutter (10369): Error Message: stop failed.
I/ExoPlayerImpl(10369): Init a09bc27 [ExoPlayerLib/2.9.6] [vbox86p, unknown, unknown, 26]
E/ExoPlayerImplInternal(10369): Source error.
E/ExoPlayerImplInternal(10369): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
E/ExoPlayerImplInternal(10369): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
E/ExoPlayerImplInternal(10369): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
E/ExoPlayerImplInternal(10369): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(10369): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal(10369): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal(10369): 	at java.lang.Thread.run(Thread.java:764)

**Comment by Tom3652** [comment] 2021-04-26 12:53
Getting the same error when the phone is automatically locked (for inactivity). 
The error is not shown when i kill my app myself, or put in background or even lock my phone myself. 

But it happens every single time. 
My phone : Android 10, OPPO A5 2020

Flutter version 2.0.5

I spare the output of flutter doctor which is totally fine

```
I/SurfaceView(16018): 138925700  updateSurface this = io.flutter.embedding.android.FlutterSurfaceView{847d684 V.E...... ........ 0,0-720,1600}  surface.isValid = false
D/SurfaceView(16018): 138925700 updateSurface: no valid surface
I/SurfaceView(16018): 138925700  updateSurface this = io.flutter.embedding.android.FlutterSurfaceView{847d684 V.E...... ........ 0,0-720,1600}  surface.isValid = false
D/SurfaceView(16018): 138925700 updateSurface: no valid surface
E/CameraCaptureSession(16018): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(16018): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession(16018): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2670)
E/CameraCaptureSession(16018): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1215)
E/CameraCaptureSession(16018): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:539)
E/CameraCaptureSession(16018): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1171)
E/CameraCaptureSession(16018): 	at io.flutter.plugins.camera.Camera.close(Camera.java:1177)
E/CameraCaptureSession(16018): 	at io.flutter.plugins.camera.Camera$1.onError(Camera.java:252)
E/CameraCaptureSession(16018): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.notifyError(CameraDeviceImpl.java:2146)
E/CameraCaptureSession(16018): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.lambda$Sm85frAzwGZVMAK-NE_gwckYXVQ(Unknown Source:0)
E/CameraCaptureSession(16018): 	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$CameraDeviceCallbacks$Sm85frAzwGZVMAK-NE_gwckYXVQ.accept(Unknown Source:8)
E/CameraCaptureSession(16018): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:271)
E/CameraCaptureSession(16018): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
E/CameraCaptureSession(16018): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
E/CameraCaptureSession(16018): 	at android.os.Handler.handleCallback(Handler.java:899)
E/CameraCaptureSession(16018): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraCaptureSession(16018): 	at android.os.Looper.loop(Looper.java:238)
E/CameraCaptureSession(16018): 	at android.app.ActivityThread.main(ActivityThread.java:7864)
E/CameraCaptureSession(16018): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(16018): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/CameraCaptureSession(16018): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)
```

**Comment by TahaTesser** [comment] 2021-04-27 10:45
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of flutter doctor -v.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.
