### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listUser defaults from command line:    IDEPackageSupportUseBuiltinSCM = YES2023-06-15 19:00:20.559 xcodebuild[32922:2824048] Writing error result bundle to /var/folders/mq/5gdcz06x5q32w246q3xd9d140000gn/T/ResultBundle_2023-15-06_19-00-0020.xcresultxcodebuild: error: The directory /Users/alekhanov_v/Projects/hephaestus/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: xcrun, OS error code: 78

### ISSUE THREAD

**Issue by bruhfessional** [flutter/flutter#128949] opened 2023-06-15 15:01 UTC
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2023-06-15 19:00:20.559 xcodebuild[32922:2824048] Writing error result bundle to /var/folders/mq/5gdcz06x5q32w246q3xd9d140000gn/T/ResultBundle_2023-15-06_19-00-0020.xcresult
xcodebuild: error: The directory /Users/alekhanov_v/Projects/hephaestus/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: xcrun, OS error code: 78
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:278:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:321:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/xcode_project.dart:325:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/xcode_project.dart:285:36)
<asynchronous suspension>
#5      IosProject._parseHostAppBundleName (package:flutter_tools/src/xcode_project.dart:261:55)
<asynchronous suspension>
#6      IosProject.hostAppBundleName (package:flutter_tools/src/xcode_project.dart:250:35)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:116:39)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:82:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp.<anonymous closure> (package:flutter_tools/src/commands/build_ios.dart:604:34)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:641:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channe

**Comment by dam-ease** [comment] 2023-06-15 15:12
@bruhfessional From the log, you seem to have multiple copies of .xcodeproj file in ios sub-directory. The flutter build process detected it correctly and presented the error as mentioned, so the build process works properly. The error is in your project config/setup, you need to revisit and remove any duplicate project files.
Closing, as this is not a bug or an issue with flutter itself.

**Closed by dam-ease** 2023-06-15 15:12 UTC
Labels: in triage
