### ISSUE TITLE
[Impeller] Very slow performance of blur with wide gamut enabled

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#131573] opened 2023-07-30 14:37 UTC
Device: iPhone 13 Pro (A15). A simple full screen blur with sigma = 30 takes **25ms** to rasterize.

<details>
<summary>code</summary>

```dart
import 'dart:ui';
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

const kSigma = 30.0;

class _Blur extends StatelessWidget {
  const _Blur();

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      child: BackdropFilter(
        blendMode: BlendMode.srcIn,
        filter: ImageFilter.blur(
          sigmaX: kSigma,
          sigmaY: kSigma,
        ),
        child: Container(
          color: Colors.red.withAlpha(30),
        ),
      ),
    );
  }
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          fit: StackFit.expand,
          children: [
            ListView.builder(
                itemBuilder: (context, index) {
                  return Container(
                    padding: const EdgeInsets.all(40),
                    child: Container(
                      color: Colors.green,
                      width: 100,
                      height: 100,
                    ),
                  );
                },
                itemCount: 100),
            const IgnorePointer(
              ignoring: true,
              child: _Blur(),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

Performance for `gaussian_blur_noalpha_nodecal_fragment_main`

<img width="566" alt="Screenshot 2023-07-30 at 16 30 08" src="https://github.com/flutter/flutter/assets/96958/bc25cc46-eba5-4f32-9ecb-3e8f334c2822">

There's a lot of sampling performed, which is not that different to non-wide gamut, but L1 misses are significantly worse.

Looking at what skia does - it seems to aggresively downcale the input texture to reach max sigma of 4. That would definitely help with the amout of sampling here.

**Comment by knopp** [comment] 2023-07-30 14:37
cc @bdero @jonahwilliams

**Comment by jonahwilliams** [comment] 2023-07-30 16:29
Might be worth re-investigating in https://github.com/flutter/flutter/issues/123472

I link a patch to switch the Impeller blur implementation with the metal performance shader blur. At the time It seemed to actually be slower; but that investigation was fairly quick and it could use a second look.

**Comment by knopp** [comment] 2023-07-30 16:35
I was thinking about MPF, but then I'd assume this is also going to be a problem on other backends. Is there a reason why the downscaling approach taken by skia wouldn't work here?

**Comment by jonahwilliams** [comment] 2023-07-30 16:36
We're already downscaling, probably too much actually.

**Comment by jonahwilliams** [comment] 2023-07-30 16:49
Also iPhone 13: We're spending about 20-25ms in the frame itself which more or less guarantees backpressure.

![image](https://github.com/flutter/flutter/assets/8975114/d5360d5f-46c0-47d5-bf55-544818d5bed4)

If I disable wide gamut via `<key>FLTEnableWideGamut/key><false/>` in the info.plist then i don't get substantially different numbers


![image](https://github.com/flutter/flutter/assets/8975114/47c11f70-15d4-4a12-b0f9-0f8733dab445)


@knopp are you sure this is wide gamut related?

**Comment by jonahwilliams** [comment] 2023-07-30 17:02
Though on the cache misses, I think that makes sense given how big of a texture we're sampling from. But perhaps there is a better way to structure how we downsample? Right now we downsample in X, then in Y since gaussian is broken down into two stages. But that means for the first pass, our texture will still be fairly large in one dimension (192x1170). The second stage is fully down sampled in this case and happens fairly quickly.

**Comment by knopp** [comment] 2023-07-30 17:22
We are, but differently.

## Skia

For full screen blur (1170x2532) with sigma = 30 skia resamples the original image down to 114x54 and from that samples for the horizontal blur pass

<img width="229" alt="Screenshot 2023-07-30 at 19 03 24" src="https://github.com/flutter/flutter/assets/96958/21636609-c141-4652-9c05-e3c2717c72ea">

.

<img width="316" alt="Screenshot 2023-07-30 at 19 03 34" src="https://github.com/flutter/flutter/assets/96958/d3508695-cb82-45eb-a376-53e87d892dee">

For each of the pixel in the blur pass there seem to be 13 samples (sigma gets scaled down with the image).

## Impeller

Image scaled down horizontally to 94x2532, during the horizontal pass. But with what it seems to be 153 samples per pixel.
In the next pass the entire height is sampled, in this case 153 samples per pixels.

So the downscaling in impeller seem to be quite different. It downscales it as part of directional blur, while skia downscale it with a blit. Skia also downscales sigma while impeller doesn't.

**Comment by knopp** [comment] 2023-07-30 17:34
Regarding whether this is wide gamut related, I originally tested this with slightly smaller blur (3/4 maybe) where the performance without wide gamut was significantly better than with. But I'm suggesting wide-gamut is something magical here, probably just more prone to cache misses.

**Comment by jonahwilliams** [comment] 2023-07-30 17:35
Makes sense. I think its that first pass that is killing us really. We should just take the Skia approach here if possible.

**Comment by bdero** [comment] 2023-07-30 18:43
Oh! Yes, we can proportionally reduce the blur in both directions if we down sample first. Doing so would allow us to simplify the blur filter significantly, fix the fidelity issues (https://github.com/flutter/flutter/issues/127770), and reduce the fragment load for _both_ passes.

I added a couple of issues to track refactoring the blur for this:
- https://github.com/flutter/flutter/issues/131579
- https://github.com/flutter/flutter/issues/131580

**Comment by chinmaygarde** [comment] 2023-08-07 17:51
We are tracking the work items in the linked issues and these are cross referenced so we can find reproductions. If there are work items that haven't been captured in open issues, please let me know. Closing this as a duplicate.

**Closed by chinmaygarde** 2023-08-07 17:51 UTC
Labels: engine, e: impeller, team-engine
