### ISSUE TITLE
tester.enterText doesn't work with Flutter 2.5

### ISSUE THREAD

**Issue by LostInDarkMath** [flutter/flutter#89917] opened 2021-09-11 15:00 UTC
## Steps to Reproduce

```dart
print('before entering second time $publicTagText');
await tester.enterText(find.byKey(const Key('tag_input_input')), publicTagText);
print('entered second time');
await tester.pumpAndSettle();
await tester.pumpAndSettle(Duration(minutes: 2)); // just for verifying that nothing was entered
```

**Expected results:**
The test should be entered to the `TextFormField` like the first time. The `onChanged` method of the `TextFormField` is not called by `enterText`. The first time it works fine, but the second time it doesn't. 

Expected output:
```
I/flutter (17781): onChanged Public Tag
I/flutter (17781): before entering second time Public Tag
I/flutter (17781): entered second time
I/flutter (17781): onChanged Public Tag
```

**Actual results:**
Output:
```
I/flutter (17781): onChanged Public Tag
I/flutter (17781): before entering second time Public Tag
I/flutter (17781): entered second time
```

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 6.1.7601], locale de-DE)
    • Flutter version 2.5.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\WILLI\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\WILLI\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\WILLI\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\WILLI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Mi A2 Lite (mobile) • c1c1eca99806 • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

This might be related to https://github.com/flutter/flutter/issues/87990 and to https://github.com/flutter/flutter/issues/89749
This wasn't an issue before Flutter 2.5

**Comment by darshankawar** [comment] 2021-09-13 13:43
@LostInDarkMath 
I believe this is similar to https://github.com/flutter/flutter/issues/89749, as this seems to be a regression.
Please follow-up in linked issue for further updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-09-13 13:43 UTC
Labels: in triage
