### ISSUE TITLE
flutter_test_performance_implementation_change_elapsed_time_ms & flutter_test_performance_interface_change_elapsed_time_ms regression

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#50016] opened 2020-02-03 16:59 UTC
Looks like it started in https://github.com/flutter/flutter/pull/49835 or https://github.com/flutter/flutter/pull/49873.

**Comment by jason-simmons** [comment] 2020-02-03 17:56
See https://github.com/flutter/flutter/issues/49893

**Comment by Hixie** [comment] 2020-02-03 21:51
Closing as dupe of #49893.

**Closed by Hixie** 2020-02-03 21:51 UTC
Labels: engine, severe: performance, severe: regression, ⚠ TODAY
