### ISSUE TITLE
Directionality Widget is no longer working as Expected in IOS

### ISSUE THREAD

**Issue by AdeebMark** [flutter/flutter#153651] opened 2024-08-18 07:15 UTC
### Steps to reproduce

1- created a new empty app.
2- created a new page for test.
3- create a button to navigate to the secund page
4- in the secund page Wrape the Scaffold to Directionality
5- add textDirection: TextDirection.rtl,
6- Run the app and navigate to this new page

### Expected results

when i use Directionality and set textDirection: TextDirection.rtl, the app bar back button needs to show correctly direction!
but now it is not happening

### Actual results

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-18 at 10 07 42](https://github.com/user-attachments/assets/1d3f9d49-fd68-4356-b96f-44829d0003e3)
the top app back button is not flipping arround and its Gowing to the hard left Align!!

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.rtl,
      child: Scaffold(
        appBar: AppBar(
          title: Text("test ..."),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/user-attachments/assets/3827846e-d7d5-425f-ba7f-82699a2db306

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Last login: Sun Aug 18 09:53:28 on ttys002
adeebmark@Adeebs-MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.4.1 23E224 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.92.1)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!
adeebmark@Adeebs-MacBook-Pro ~ % 


```

</details>

**Comment by Yousef-Alabdulhadi** [comment] 2024-08-18 09:02
Facing same issue when switching to arabic.

**Comment by danagbemava-nc** [comment] 2024-08-19 08:53
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153036

**Closed by danagbemava-nc** 2024-08-19 08:53 UTC
Labels: in triage
