### ISSUE TITLE
Arabic text renders differently between TextSpan and Text widgets

### ISSUE THREAD

**Issue by febryituery** [flutter/flutter#73092] opened 2020-12-29 11:39 UTC
Hi everyone,
I'm having an issues about **RichText**. So i want to show arabic text on **TextSpan** but i don't know what went wrong, this arabic text looks different compare to **Text** widget. I'm using **TextSpan** because i want to add different color on each specific range character of String.

This is using **Text** widget (using custom font)
<img width="455" alt="Jepretan Layar 2020-12-29 pukul 18 31 29" src="https://user-images.githubusercontent.com/16750465/103280915-1c4c0200-4a04-11eb-8ee6-7f5a45bd5b28.png">

it get worst if i'm using **TextSpan** (using custom font)
<img width="449" alt="Jepretan Layar 2020-12-29 pukul 18 24 21" src="https://user-images.githubusercontent.com/16750465/103280987-4a314680-4a04-11eb-8f32-911821530bea.png">

but better result if i use system font, also **TextSpan**
<img width="453" alt="Jepretan Layar 2020-12-29 pukul 18 23 28" src="https://user-images.githubusercontent.com/16750465/103280970-3b4a9400-4a04-11eb-9152-bbeeccff5099.png">

i use this line to generate **TextSpan** from **List**
<img width="893" alt="Jepretan Layar 2020-12-29 pukul 18 25 57" src="https://user-images.githubusercontent.com/16750465/103281071-7cdb3f00-4a04-11eb-9595-83de94b5c51f.png">

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.1 20C69 darwin-x64, locale id-ID)
    • Flutter version 1.22.4 at /Users/febrydwiputra/flutterSDK/flutter
    • Framework revision 1aafb3a8b9 (7 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/febrydwiputra/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/febrydwiputra/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
```

So maybe anyone could help me. Thanks

**Comment by darshankawar** [comment] 2020-12-29 12:14
@febryituery 
Please provide a complete minimal reproducible code sample in text format that we can copy paste and run in IDE to see the issue.
Thanks.

**Comment by febryituery** [comment] 2020-12-29 13:37
> @febryituery
> Please provide a complete minimal reproducible code sample in text format that we can copy paste and run in IDE to see the issue.
> Thanks.

```
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String arabicText = "يَهْدِيْكُمُ اللَّهُ وَيُصْلِحُ بَالَكُمُ";
  String arab1 = "";
  String arab2 = "";
  String arab3 = "";
  List<Tajwid> listTajwid = new List<Tajwid>();

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    processColorTajwid();
  }

  void processColorTajwid() async {
    Tajwid tajwid1 = new Tajwid();
    tajwid1.text = arabicText.substring(0, 5);
    tajwid1.color = Colors.black;
    listTajwid.add(tajwid1);
    Tajwid tajwid2 = new Tajwid();
    tajwid2.text = arabicText.substring(5,15);
    tajwid2.color = Colors.red;
    listTajwid.add(tajwid2);
    Tajwid tajwid3 = new Tajwid();
    tajwid3.text = arabicText.substring(15, arabicText.length);
    tajwid3.color = Colors.black;
    listTajwid.add(tajwid3);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Arabic"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              arabicText,
              style: TextStyle(fontSize: 24),
            ),
            RichText(
                text: TextSpan(
                    children: listTajwid
                        .map((e) => TextSpan(
                            text: e.text,
                            style: TextStyle(fontSize: 24, color: e.color)))
                        .toList()
                )
            )
          ],
        ),
      ),
    );
  }
}

class Tajwid {
  String text;
  Color color;

  Tajwid({this.text, this.color});
}
```

<img width="261" alt="Jepretan Layar 2020-12-29 pukul 20 34 56" src="https://user-images.githubusercontent.com/16750465/103287648-9e90f200-4a15-11eb-9cb3-d1e6ca9c67e2.png">

<img width="78" alt="Jepretan Layar 2020-12-29 pukul 20 35 12" src="https://user-images.githubusercontent.com/16750465/103287655-a355a600-4a15-11eb-9602-c01d41bdd6d5.png">

**Comment by darshankawar** [comment] 2020-12-29 13:55
@febryituery 
Ran your sample code and see below:

<img width="548" alt="Screenshot 2020-12-29 at 7 24 23 PM" src="https://user-images.githubusercontent.com/67046386/103288687-7ac8ae80-4a0b-11eb-8ba4-4ab91cf15b1b.png">

What's the expected behavior / result from your code sample ?

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by febryituery** [comment] 2020-12-29 14:01
> @febryituery
> Ran your sample code and see below:
> 
> <img alt="Screenshot 2020-12-29 at 7 24 23 PM" width="548" src="https://user-images.githubusercontent.com/67046386/103288687-7ac8ae80-4a0b-11eb-8ba4-4ab91cf15b1b.png">
> 
> What's the expected behavior / result from your code sample ?
> 
> flutter doctor -v

there's a lil' bit different between **Text** and **RichText**. i want arabic text that use **RichText** looks like arabic text that use **Text**.
<img width="28" alt="Jepretan Layar 2020-12-29 pukul 20 58 54" src="https://user-images.githubusercontent.com/16750465/103288966-ac944200-4a18-11eb-9848-c8c642ba86cc.png">

**Comment by timsneath** [comment] 2020-12-29 19:45
Interesting bug. If we can validate this, we should add a goldens test to ensure rendering matches with cases like this.

**Comment by justinmc** [comment] 2020-12-29 22:18
CC @GaryQian

**Comment by febryituery** [comment] 2021-01-13 07:27
any update?

**Comment by febryituery** [comment] 2021-03-03 01:37
> Interesting bug. If we can validate this, we should add a goldens test to ensure rendering matches with cases like this.

any update?

**Comment by GaryQian** [comment] 2021-06-21 06:48
Closing as a duplicate of https://github.com/flutter/flutter/issues/73108 due to more detailed discussion there.

**Closed by GaryQian** 2021-06-21 06:48 UTC
Labels: a: internationalization, a: quality, a: typography, f: material design, found in release: 1.22, framework, has reproducible steps, passed first triage
