### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:FAILURE: Build failed with an exception.* What went wrong:Project 'app' not found in root project 'android'.* Try:> Run with --stacktrace option to get the stack trace.> Run with --info or --debug option to get more log output.> Run with --scan to get full insights.* Get more help at https://help.gradle.orgBUILD FAILED in 3s Command: C:\Users\asadbek\Desktop\projects\ohang\android\gradlew.bat, OS error code: 1

### ISSUE THREAD

**Issue by asadbekdev** [flutter/flutter#101661] opened 2022-04-10 09:48 UTC
%23%23 Command
```
flutter build apk --split-per-abi
```

%23%23 Steps to Reproduce
1. ...
2. ...
3. ...

%23%23 Logs
ProcessException: Process exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'android'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s Command: C:\Users\asadbek\Desktop\projects\ohang\android\gradlew.bat, OS error code: 1
```
%230      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
%231      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
%232      flavorUndefinedHandler.<anonymous closure> (package:flutter_tools/src/android/gradle_errors.dart:206:38)
<asynchronous suspension>
%233      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:388:42)
<asynchronous suspension>
%234      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:178:5)
<asynchronous suspension>
%235      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:5)
<asynchronous suspension>
%236      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
%237      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%238      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
%239      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
%2310     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
%2311     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
%2312     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.5.0 at C:\Users\asadbek\fvm\default\bin\versions\2.5.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\asadbek\AppData\Local\Android\sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: D:\Programs\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\asadbek\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2021.1)
    • Android Studio at D:\Programs
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11 9-b60-7590822)

[✓] VS Code (version 1.66.1)
    • VS Code at C:\Users\asadbek\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 99.0.1150.30

• No issues found!

```

%23%23 Flutter Application Metadata
**Type**: null
**Version**: 1.0.0 1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
%23%23%23 Plugins
audio_service-0.18.4
audio_service_web-0.1.1
audio_session-0.1.6 1
flutter_plugin_android_lifecycle-2.0.5
image_picker-0.8.4 11
image_picker_for_web-2.1.6
just_audio-0.9.20
just_audio_web-0.4.7
package_info_plus-1.4.0
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.4
path_provider-2.0.9
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
sentry_flutter-6.4.0
shared_preferences-2.0.13
shared_preferences_android-2.0.10
shared_preferences_ios-2.0.9
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2
webview_flutter-3.0.1
webview_flutter_android-2.8.3
webview_flutter_wkwebview-2.7.1

**Comment by danagbemava-nc** [comment] 2022-04-11 09:55
Duplicate of #59312

**Closed by danagbemava-nc** 2022-04-11 09:55 UTC
Labels: in triage
