### ISSUE TITLE
Image.network should retry if it fails

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#11155] opened 2017-07-11 21:46 UTC
Feature request that Network.image will retry if it fails, right now it just fails and then will never load.

**Comment by sethladd** [comment] 2017-07-11 21:50
Thanks for the feedback!

Meanwhile, you can use the http package to manage your own connection and retry logic, get the image bits, and then give to https://docs.flutter.io/flutter/widgets/Image/Image.memory.html

**Comment by collinjackson** [comment] 2017-07-12 02:16
Marked as customer blocker because posse would like us to find an owner for the framework-level fix.

@sethladd's workaround is a possible fallback if we can't find an owner in time.

**Comment by BenSower** [comment] 2017-07-12 14:37
Very nice feature idea! 
Also, just a curious question: Is there a proper way to handle Network.image not being able to load an image?

**Comment by collinjackson** [comment] 2017-07-12 14:53
Some ideas:

1. The image cache could avoid caching failures if it detects the network is unreachable or the server did not provide a response code.
2. We could use a separate cache for failures that expires after (potentially configurable) amount of retries or time.

**Comment by sethladd** [comment] 2017-07-12 15:59
There's going to be a lot of controls that users will wish to have: timeout times, retries times, backoff strategies, local caches, etc, etc. Image.network just might not be scalable enough to support all the complexity and control users will want when communicating with the network. It may be sufficient to figure out how to layer our system in a way where developers can compose the retry/caching/etc strategies that work best for them.

+1 for helping our customers now, but I'm skeptical that Image.network can or should be all things to all people. Instead, let's expose the layers/callbacks/hooks so that users can piece together their perfect solution.

For example, ideally I'd imagine we'd continue to enhance the http library to support caching strategies, retry time customization, etc.

**Comment by collinjackson** [comment] 2017-07-12 17:05
@yjbanov volunteered to take this one

**Comment by eseidelGoogle** [comment] 2017-07-20 18:08
@collinjackson reconfirmed with Posse just now that this will not block their current application (due to a workaround).

My understanding is that @yjbanov has a partial solution written and would like to learn more?

**Comment by Hixie** [comment] 2017-07-25 20:14
@yjbanov You're working on making a flutter package with a widget that does this, right?

**Comment by yjbanov** [comment] 2017-07-26 21:31
FYI: https://github.com/flutter/flutter_image/pull/3

**Closed** 2017-08-01 20:53 UTC
Labels: customer critical, customer: posse (eap), new feature
