### ISSUE TITLE
flutter app shut down when i use fingerprint local auth

### ISSUE THREAD

**Issue by rifathossain82** [flutter/flutter#108236] opened 2022-07-24 07:04 UTC
In app:
![Screenshot_1658641363](https://user-images.githubusercontent.com/88751768/180636255-666e609c-ddfc-45fe-b09a-bf9c3f987a11.png)

error:
![VM shut down](https://user-images.githubusercontent.com/88751768/180636251-99cc2562-973b-45d2-a103-8443f096f56f.PNG)

flutter doctor:
![doctor_v_1](https://user-images.githubusercontent.com/88751768/180636324-d6e05eb0-45b8-4383-a1b1-58b40fd7d6bf.PNG)
![doctor_v_2](https://user-images.githubusercontent.com/88751768/180636328-2eda2f23-5162-4ee4-bf89-3757ed1b84cb.PNG)

I tried to clone many existing repos but got the same problem.

**Comment by danagbemava-nc** [comment] 2022-07-25 10:34
Hi @rifathossain82, please provide a complete minimal reproducible code sample in text form so that we can investigate this issue. 

Please also make sure that you've followed the [setup guide](https://pub.dev/packages/local_auth#android-integration) in the readme correctly. 

Thank you

**Comment by rifathossain82** [comment] 2022-07-25 12:05
here is my project: https://github.com/rifathossain82/fingerprint_demo

I think I have everything setup, I tried many docs and tutorials. But same error.
That's why I clone and run a project, but here's the same

this is the project which I clone: https://github.com/tusharhow/flutter-biometric

**Comment by danagbemava-nc** [comment] 2022-07-26 07:21
Hi @rifathossain82, this is a duplicate of https://github.com/flutter/flutter/issues/55638. 

Kindly check if the workaround in https://github.com/flutter/flutter/issues/55638#issuecomment-796547472 works for you. 

Kindly follow up in the linked issue for updates and please upvote the original issue.
 
Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-07-26 07:21 UTC
Labels: in triage

**Comment by rifathossain82** [comment] 2022-07-26 10:08
@danagbemava-nc  Thanks a lot, dear
