### ISSUE TITLE
Run flutter application into iOS virtual device on virtualized OSX

### ISSUE THREAD

**Issue by TheFedex87** [flutter/flutter#36261] opened 2019-07-16 14:37 UTC
Hi I have some performance problems running my application inside iOS simulator installed inside a VirtualBox OSx machine. The simulator run and the application is deployed without any problem. But there is lag when the draw has to be redrawed. For example when I click on a button which open a modal sheet, the image is stucked, I can unlock it simply dragging the IOs bottom bar of a few pixel. It's difficult test the application since every time I have to move that bar a few pixel in order to update the phone image. Any suggestion?

**Comment by grandleaf** [comment] 2019-07-19 17:04
Visualized OSX might not have the hardware GPU acceleration.  Sounds not a flutter issue.

**Comment by TheFedex87** [comment] 2019-07-22 06:40
But the strange thing is that this problem occurs only with the flutter app, not with the native app pre installed into ios emulator.
See these two images which show you the problem:
Example with an original app
https://imgur.com/e5UN6fL

Example with a flutter app
https://imgur.com/qeN7ImX

**Comment by chinmaygarde** [comment] 2020-06-15 04:31
This is a duplicate of https://github.com/flutter/flutter/issues/36839. The proposed fix for that is a switch the Metal on iOS simulators. But it is unclear how that will work on virtualized environments.

**Closed by chinmaygarde** 2020-06-15 04:31 UTC
Labels: engine, severe: performance
