### ISSUE TITLE
[web][html]  RTL doesn't work correctly

### ISSUE THREAD

**Issue by Maadhav** [flutter/flutter#80094] opened 2021-04-09 01:44 UTC
## Steps to Reproduce

1. Run `flutter run` on a project that has some rtl text.
OR
1. Flutter Web RTL Example URL: https://codepen.io/MaadhavSharma/full/QWdOrpV
2. When you open the link above in a PC browser, it would show the RTL correctly, but when you open the link in an android device RTL stops working.

**Expected results:** 
 <img src="https://i.imgur.com/5F5N0Fp.png" width="300"> 
**Actual results:** 
 <img src="https://i.imgur.com/d8rURya.jpg" width="300"> 

> The issue was not present in the older versions of Flutter.
    When I ran the project with Flutter 1.20.0, there is no issue. 
     But any update after 1.26.0 has this issue.

**Comment by TahaTesser** [comment] 2021-04-09 12:36
Hi @Maadhav 
Thanks for filing the issue, it's not related to Mobile but `html` renderer (which is the default for mobile when not explicitly providing `--web-renderer`), So we can also reproduce it on desktop using `html` renderer

`flutter run --web-renderer html -d chrome -v`

### Preview
![image](https://user-images.githubusercontent.com/48603081/114179849-31f88e00-9948-11eb-9f17-c07c1e50971e.png)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Directionality(
            textDirection: TextDirection.rtl,
            child: RichText(
              text: TextSpan(
                text: 'שלום וברכה!',
                style: Theme.of(context).textTheme.headline4,
              ),
              textDirection: TextDirection.rtl,
            ),
          ),
        ),
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.4 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b1395592de (8 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.556, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.1.0-13.0.pre.556 at C:\Users\Taha\Code\flutter_master
    • Framework revision 1a36c18497 (6 hours ago), 2021-04-08 23:33:00 -0700
    • Engine revision a9f4883dc8
    • Dart version 2.13.0 (build 2.13.0-219.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.
```
	
</details>

**Comment by Maadhav** [comment] 2021-04-09 12:53
Oh I see, so the html renderer is only used in android? 
Because for the same build i was not having the issue in iOS as well. 
Hope the fix is out soon.

**Comment by TahaTesser** [comment] 2021-04-09 14:44
@Maadhav 
For both mobile platforms, if you omit `--web-renderer`, it uses auto (cankaskit for desktop and HTML for mobile). If you specify either, it renders using specified render on desktop as well as mobile

**Comment by yjbanov** [comment] 2021-04-15 22:18
@mdebbar IIRC this is a duplicate issue

**Comment by mdebbar** [comment] 2021-04-22 21:51
Duplicate of https://github.com/flutter/flutter/issues/69396

**Closed by mdebbar** 2021-04-22 21:51 UTC
Labels: a: internationalization, assigned for triage, e: web_html, engine, found in release: 2.0, found in release: 2.1, has reproducible steps, platform-web
