### ISSUE TITLE
image_picker is working in debug mode but not in release.

### ISSUE THREAD

**Issue by yannainghtun-mk** [flutter/flutter#74779] opened 2021-01-27 04:04 UTC
@When I click image_picker to pick, it show permission request . Then I allow it but nothing is showing after that. Then exit from app and reopen , reclick, it now show images to  pick. But when I select image then it is return nothing. Then reclick on image_picker is showing error "already in active".
That it is!.

currently used is image_picker:0.6.7+21
But it is not working for me is all version.

```bash
[+599182 ms] E/flutter (21453): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
[        ] E/flutter (21453): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
[        ] E/flutter (21453): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
[        ] E/flutter (21453): <asynchronous suspension>
[        ] E/flutter (21453): #2      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30)
[        ] E/flutter (21453): <asynchronous suspension>
[        ] E/flutter (21453): #3      pickProfileImage (package:hindu_youth_society/pages/homepage.dart:369)
[        ] E/flutter (21453): <asynchronous suspension>
[        ] E/flutter (21453): 
```

@ianloic 
@anaisbetts 
@sgraham 
@gmoothart

**Comment by TahaTesser** [comment] 2021-01-27 08:30
Hi @yannainghtun-mk 
This is a duplicate of https://github.com/flutter/flutter/issues/40339
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-27 08:30 UTC
