### ISSUE TITLE
[webview_flutter] stopped working: blank screen

### ISSUE THREAD

**Issue by SammyO** [flutter/flutter#42351] opened 2019-10-09 19:12 UTC
All of a sudden webview_flutter seems to have stopped functioning properly, and is showing a blank screen. 

Output of `flutter doctor -v`: 
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-NL)
    • Flutter version 1.9.1+hotfix.4 at /Users/sammy/Flutter/flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sammy/Library/Android/sdk
    • Android NDK at /Users/sammy/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/sammy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 8F42114A-B0C7-445E-B4C1-80FE37171206 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

! Doctor found issues in 1 category.
```

I've got in `info.plist`:
```
	<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>
```

**Comment by BondarenkoStas** [comment] 2019-10-10 11:39
@SammyO will it help if you use 
```
<key>io.flutter.embedded_views_preview</key>
<true/>
```
?

**Comment by SammyO** [comment] 2019-10-10 12:01
@BondarenkoStas tried that out just now, doesn't help unfortunately. 

My pubspec.yaml:
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path_provider:
  flutter_html: ^0.10.4
  webview_flutter: 0.3.11+3
  flutter_markdown: "^0.2.0"
  firebase_storage:
  cloud_firestore: 0.12.9
  firebase_core: ^0.4.0
  firebase_auth: ^0.13.0
  photo_view: 0.4.2
  connectivity: ^0.4.2

  # Error reporting
  #sentry: 2.2.
  sentry:
    path: ./custom_sentry_client/
  catcher:
    path: ./custom_catcher
  device_info: 0.4.0+2
  package_info: 0.4.0+6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```

I'm trying to figure out what could have caused this. I updated my Flutter install, but I can't figure out how I can determine with which Flutter version previous builds were created (builds up until yesterday's update worked fine), in order to compare them to this build. Furthermore I ran `pod install` and `pod update` a few times, which may have broken things. I've reverted to a previous commit though, and redid `pod install` and `pod update`, but the build still isn't working.

Please let me know if I can provide any more information or test things. Thanks.

**Comment by BondarenkoStas** [comment] 2019-10-10 12:21
@SammyO Are there any error logs when you run it with --verbose flag?

**Comment by SammyO** [comment] 2019-10-10 17:51
No... Could it be related to https://github.com/flutter/flutter/issues/39470? I have been working on trying to fix this error using suggestions provided in the link, after which the build started breaking.

**Comment by SammyO** [comment] 2019-10-12 18:00
I've created a small project in which the issue is reproduced https://github.com/SammyO/broken_webview_flutter

**Comment by SammyO** [comment] 2019-10-14 14:34
@BondarenkoStas please let me know if I can help in any way. I'd be happy to try to fix this, but I don't know where to start with debugging this, as there are no logs or errors indicating anything is going wrong.

**Comment by BondarenkoStas** [comment] 2019-10-14 16:44
Sorry @SammyO, I'm just doing initial triage here, and don't think that I'm able to help. Let's wait for somebody else from the team to pick the issue.

**Comment by SammyO** [comment] 2019-10-14 17:04
I see. Thanks for the quick reply!

**Comment by SammyO** [comment] 2019-10-14 17:32
Some more information.
1. Produces blank screen in iOS
```
  Widget _getWebView(BuildContext context, String rawText) {
    return WebView(
      initialUrl: new Uri.dataFromString(rawText, mimeType: 'text/html', encoding: Encoding.getByName("UTF-8")).toString(),
    );
  }
```
2. Produces blank screen in iOS
```
  Widget _getWebView(BuildContext context, String rawText) {
    return WebView(
      initialUrl: "www.google.com",
    );
  }
```
3. Produces valid Google website
```
  Widget _getWebView(BuildContext context, String rawText) {
    return WebView(
      initialUrl: "https://www.google.com",
    );
  }
```

**Comment by SammyO** [comment] 2019-10-14 18:16
I can furthermore confirm that
```
  Widget _getWebView(BuildContext context, String rawHtml) {
    return WebView(
      initialUrl: '',
      onWebViewCreated: (WebViewController webViewController) {
        _controller = webViewController;
        _setRawHtml(rawHtml);
      },
      navigationDelegate: (NavigationRequest request) {
        return _processHref(context, request.url);
      }
    );
  }

  _setRawHtml(String rawHtml) async {
    _controller.loadUrl(Uri.dataFromString(
        rawHtml,
        mimeType: 'text/html',
        encoding: Encoding.getByName('utf-8')
    ).toString());
  }
``
seems to work.

**Comment by deandreamatias** [comment] 2019-10-17 11:15
Hi @SammyO !
Did you try these solutions? 
https://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9
https://github.com/flutter/flutter/issues/25351#issuecomment-526617475

Maybe solve because your URL is not a valid https.

**Comment by SammyO** [comment] 2019-10-17 11:47
@deandreamatias I tried that too, didn't work either unfortunately.

**Comment by hydeparkk** [comment] 2019-12-13 12:53
I have exactly the same problem, when trying to create webview with data from string. But I've found that when I run app with verbose param there is such log line:
>[  +10 ms] [DEVICE LOG] 2019-12-13 13:46:37.308463+0100  localhost Runner[4051]: (UIKitCore) -canOpenURL: failed for URL: "data:text/html;charset=utf-8,%3Chtml%3E%3Chead%3E%3C/head%3E%3Cbody%20onload=%22 ... /html%3E" - error: "This app is not allowed to query for scheme data"

It looks like it is iOs problem with opening "data:XXX" schemes.  On Android it works fine.

**Comment by josephmangmang** [comment] 2020-01-20 15:17
Same here. Does anybody solve this problem?

**Comment by hydeparkk** [comment] 2020-01-21 09:05
I think it could be related to this issue: #30256
After changing navigationDelegate as described in this issue everything works properly.

**Comment by darshankawar** [comment] 2020-06-25 11:33
Hi @SammyO, can you please confirm if you still experience this issue on latest `dev channel (1.20.0-0.0.pre)` and with latest version of `webview_flutter` plugin ?

According to your comment here (https://github.com/flutter/flutter/issues/42351#issuecomment-541813185), I tried to replicate this issue on iOS simulator (13.3), but didn't see issue for # 1, as you described.

Below code snippet renders properly on screen:

```
return WebView(
      initialUrl: new Uri.dataFromString(rawText, mimeType: 'text/html', encoding: Encoding.getByName("UTF-8")).toString(),
    );
```

<details>
<summary>code sample</summary>

```
  Widget build(BuildContext context) {
    final text = "<html><h1>TEST</h1></h1></head>";
    return Scaffold(
      appBar: AppBar(),
      body: WebView(
        initialUrl: Uri.dataFromString(text, mimeType: 'text/html', encoding: Encoding.getByName("UTF-8")).toString(),
        javascriptMode: JavascriptMode.unrestricted,
      )
    );
  }
```

</details>

![Screen Shot 2020-06-25 at 4 53 40 PM](https://user-images.githubusercontent.com/67046386/85711243-b30dce00-b704-11ea-8fa1-166fe4e24e29.png)

Your code snippet # 2 could be related to [33105](https://github.com/flutter/flutter/issues/33105)

**Comment by TahaTesser** [comment] 2020-07-24 14:55
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-24 14:55 UTC
Labels: p: first party, p: webview, platform-ios, plugin

**Comment by dna2github** [comment] 2020-09-07 09:30
i think the problem is:
- on android emulator, flutter webview shows white screen (but url links are clickable and everything is working like a headless webview ...)
- on real android phone, flutter webview works very well ...
