### ISSUE TITLE
`Listview` with  `Image.network` throwing exception from another children widget when pass to new Screen

### ISSUE THREAD

**Issue by pmatatias** [flutter/flutter#137660] opened 2023-11-01 04:27 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

To reproduce the issue, please copy and run the code in sampe code.

### Expected results

If I tap the child widget, it passes the data as arguments to the new screen. and should not include data on other children.
**for example** : When we tap on the `second child`, which has a valid **image source**, it will navigate to a new screen and will display the provided image.

and in the details screen, the image loaded is just the data passed from navigation (i.e. data[2] )

### Actual results

but it seems that when we navigate, the **first and third** data are also passed to the new screen. and in my example, the first child has an invalid image source, and that causes an exception. (see demo video)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const NotePage(),
    );
  }
}

class NoteModel {
  final String imgSrc;
  final String name;

  NoteModel({this.imgSrc = "", this.name = "Lorem Ipsum dolor sit amet"});
}

List<NoteModel> dummyNote = [
  NoteModel(imgSrc: "https://invalid-source"),
  NoteModel(imgSrc: "https://placehold.co/600x400.png", name: "Lorem 2"),
  NoteModel(imgSrc: "https://placehold.co/600x400.png", name: "Lorem 3"),
  NoteModel(imgSrc: "https://placehold.co/600x400.png", name: "Lorem 4"),
  NoteModel(imgSrc: "https://placehold.co/600x400.png", name: "Lorem 5"),
];

class NotePage extends StatelessWidget {
  const NotePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
          SizedBox(
            height: 130,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemCount: dummyNote.length,
              itemBuilder: (context, index) => SizedBox(
                width: 230,
                child: InkWell(
                  onTap: () => Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => NoteDetailPage(
                          data: dummyNote[index],
                          // key: ValueKey('$index , ${dummyNote[index].imgSrc}'),
                        ),
                      )),
                  child: Card(
                    child: Row(
                      children: [
                        Expanded(
                            child: Image.network(dummyNote[index].imgSrc,
                                fit: BoxFit.cover,
                                semanticLabel: dummyNote[index].name,
                                loadingBuilder: (context, child,
                                        loadingProgress) =>
                                    loadingProgress != null
                                        ? const Center(
                                            child: CircularProgressIndicator())
                                        : child,
                                errorBuilder: errorImageBuilder)),
                        const SizedBox(width: 20),
                        Expanded(child: Text(dummyNote[index].name))
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ),
        ]),
      ),
    );
  }
}

class NoteDetailPage extends StatelessWidget {
  const NoteDetailPage({super.key, required this.data});
  final NoteModel data;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Padding(
        padding: const EdgeInsets.all(18.0),
        child: ListView(
          children: [
            Image.network(
              data.imgSrc,
              errorBuilder: errorImageBuilder,
              loadingBuilder: (context, child, loadingProgress) =>
                  loadingProgress != null
                      ? const Center(child: CircularProgressIndicator())
                      : child,
            ),
            const SizedBox(width: 20),
            Text(data.name)
          ],
        ),
      ),
    );
  }
}

Widget errorImageBuilder(context, error, stackTrace) => const Material(
      color: Colors.purple,
      child: Icon(
        Icons.image, // change to church icon
        color: Colors.white,
      ),
    );
```

</details>

### Screenshots or Video

Video demonstration

https://github.com/flutter/flutter/assets/33835308/f84d4397-e515-4887-aff5-0af5355b4258

### Logs

<details><summary>Logs</summary>

```console
════════ Exception caught by image resource service ════════════════════════════
Failed host lookup: 'invalid-source' (OS Error: No address associated with hostname, errno = 7)
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.0.1 22A400 darwin-arm64, locale en-ID)
    • Flutter version 3.13.6 on channel stable at /Users/gspe/developments/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/gspe/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] VS Code (version 1.82.3)
    • VS Code at /Users/gspe/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-11-01 08:55
Hi @pmatatias 
I can't reproduce this issue on both Android and iOS platforms. There is no exception thrown in the output console. Checking this on the latest Flutter stable channel 3.13.9. Could you try upgrading Flutter and confirm?

**Comment by pmatatias** [comment] 2023-11-01 09:22
Thanks for the response. I've upgrade my flutter.
However, this problem still occurs

I have no idea, i test with mac and widows, both same behavior. 

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.0.1 22A400 darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.83.1)
[✓] VS Code (version 1.82.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by huycozy** [comment] 2023-11-02 05:04
Even though I can't reproduce this issue, I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/97077.

Closing this issue as a duplicate, so please follow up on it for further updates.

**Closed by huycozy** 2023-11-02 05:04 UTC
Labels: in triage
