### ISSUE TITLE
Cannot set resizeToAvoidBottomInset to false within CupertinoTabScaffold

### ISSUE THREAD

**Issue by scaraux** [flutter/flutter#74458] opened 2021-01-22 02:27 UTC
## Steps to Reproduce

When I nest a `CupertinoPageScaffold` inside a `CupertinoTabScaffold`,  the `resizeToAvoidBottomInset` argument seems to be always true no matter what value I pass.

**Expected results:** 

The keyboard should cover the fields

**Actual results:** 

The keyboard pushes the content upwards like if `resizeToAvoidBottomInset` was set to true.

Replace _`home: AppWithTabs()`_ by _`home: PageWithFields()`_ and this is the normal behavior.

**Minimum repro:**

```
 @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      debugShowCheckedModeBanner: true,
      title: 'Issue',
      theme: CupertinoThemeData(
        primaryColor: CupertinoColors.white,
        barBackgroundColor: CupertinoColors.white,
        primaryContrastingColor: CupertinoColors.white,
      ),
      localizationsDelegates: [
        DefaultMaterialLocalizations.delegate,
        DefaultCupertinoLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
      home: AppWithTabs(),
    );
  }
```

```
class AppWithTabs extends StatelessWidget {
  const AppWithTabs({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      backgroundColor: CupertinoColors.white,
      tabBuilder: (BuildContext context, int index) {
        return PageWithFields();
      },
      tabBar: CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Container(child: Icon(CupertinoIcons.add)),
            title: Text('Tab 1'),
          ),
          BottomNavigationBarItem(
            icon: Container(child: Icon(CupertinoIcons.add)),
            title: Text('Tab 1'),
          ),
        ],
      ),
    );
  }
}
```

```
class PageWithFields extends StatelessWidget {
  const PageWithFields({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      resizeToAvoidBottomInset: false,
      child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
          return Material(
            child: Stack(
              children: [
                Positioned(
                  bottom: 0,
                  width: MediaQuery.of(context).size.width,
                  child: Container(
                    height: 300.0,
                    color: EYColors.debug,
                  ),
                ),
                ListView(
                  children: [
                    TextFormField(initialValue: 'This is a field'),
                    TextFormField(initialValue: 'This is a field'),
                    TextFormField(initialValue: 'This is a field'),
                    TextFormField(initialValue: 'This is a field'),
                    TextFormField(initialValue: 'This is a field'),
                  ],
                )
              ],
            ),
          );
        },
      ),
    );
  }
}
```

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel master, 1.25.0-9.0.pre.15, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.25.0-9.0.pre.15 at /Users/oscar/flutter
    • Framework revision c2bfb7b348 (6 weeks ago), 2020-12-10 08:33:04 +0800
    • Engine revision d2ccdefe18
    • Dart version 2.12.0 (build 2.12.0-135.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/oscar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • OSCAR (mobile) • ios            • iOS 14.3
    • Chrome (web)   • chrome                    • web-javascript • Google Chrome 88.0.4324.96

</details>

**Comment by pedromassangocode** [comment] 2021-01-22 08:03
Hi @scaraux 
Did you know that `CupertinoTabScaffold` has a `resizeToAvoidBottomInset` property that is true by default? Yes, it has, and if you set it to false you will get the expected behavior.

```dart
    return CupertinoTabScaffold(
      resizeToAvoidBottomInset: false,
      // your code here
    );
```

I updated your code with the change above to solve the issue.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      debugShowCheckedModeBanner: true,
      title: 'Issue',
      theme: CupertinoThemeData(
        primaryColor: CupertinoColors.white,
        barBackgroundColor: CupertinoColors.white,
        primaryContrastingColor: CupertinoColors.white,
      ),
      localizationsDelegates: [
        DefaultMaterialLocalizations.delegate,
        DefaultCupertinoLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
      home: AppWithTabs(),
    );
  }
}

class AppWithTabs extends StatelessWidget {
  const AppWithTabs({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      resizeToAvoidBottomInset: false,
      backgroundColor: CupertinoColors.white,
      tabBuilder: (BuildContext context, int index) {
        return PageWithFields();
      },
      tabBar: CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Container(child: Icon(CupertinoIcons.add)),
            title: Text('Tab 1'),
          ),
          BottomNavigationBarItem(
            icon: Container(child: Icon(CupertinoIcons.add)),
            title: Text('Tab 1'),
          ),
        ],
      ),
    );
  }
}

class PageWithFields extends StatelessWidget {
  const PageWithFields({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      resizeToAvoidBottomInset: false,
      child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
          return Material(
            child: Stack(
              children: [
                Positioned(
                  bottom: 0,
                  width: MediaQuery.of(context).size.width,
                  child: Container(
                    height: 300.0,
                    color: Colors.red,
                  ),
                ),
                ListView(
                  children: [
                    TextFormField(initialValue: 'This is a field'),
                    TextFormField(initialValue: 'This is a field'),
                    TextFormField(initialValue: 'This is a field'),
                    TextFormField(initialValue: 'This is a field'),
                    TextFormField(initialValue: 'This is a field'),
                  ],
                )
              ],
            ),
          );
        },
      ),
    );
  }
}
```
</details>

Closing as this does not seems to be an issue with Flutter.
Thank you

**Closed by pedromassangocode** 2021-01-22 08:03 UTC

**Comment by scaraux** [comment] 2021-01-22 08:17
> Hi @scaraux
> Did you know that `CupertinoTabScaffold` has a `resizeToAvoidBottomInset` property that is true by default? Yes, it has, and if you set it to false you will get the expected behavior.
> 
> ```dart
>     return CupertinoTabScaffold(
>       resizeToAvoidBottomInset: false,
>       // your code here
>     );
> ```
> 
> I updated your code with the change above to solve the issue.
> 
> code sample
> Closing as this does not seems to be an issue with Flutter.
> Thank you

You are right. Didn't know about this; not an issue then. Thanks.
