### ISSUE TITLE
Flutter Firebase Storage Object does not exist at location.

### ISSUE THREAD

**Issue by macphailmagwira** [flutter/flutter#71134] opened 2020-11-24 06:31 UTC
I keep getting this error every time i run getDownloadURL, it keeps saying no object exists at the location but I added the images I want to download in the root and my file extension is correct, I don't know what I'm doing wrong, it even prints out the URL but says the object does not exist in location 

here is the full error
```
I/flutter (23569): here is your url https://firebasestorage.googleapis.com/v0/b/posweepay.appspot.com/o/cables.jpg?alt=media&token=829a25e4-becd-416f-9b01-3498a3e79546
I/flutter (23569): found data on cloudstore Instance of '_MapStream<QuerySnapshotPlatform, QuerySnapshot>'
E/StorageException(23569): StorageException has occurred.
E/StorageException(23569): Object does not exist at location.
E/StorageException(23569):  Code: -13010 HttpResult: 404
E/StorageException(23569): {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException(23569): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException(23569):  at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:434)
E/StorageException(23569):  at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:451)
E/StorageException(23569):  at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:442)
E/StorageException(23569):  at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
E/StorageException(23569):  at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:286)
E/StorageException(23569):  at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:70)
E/StorageException(23569):  at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:62)
E/StorageException(23569):  at com.google.firebase.storage.GetDownloadUrlTask.run(GetDownloadUrlTask.java:76)
E/StorageException(23569):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/StorageException(23569):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
```
here is my code

```
Reference ref = 
        FirebaseStorage.instance.ref().child('cables.jpg');
       
       var togo = (await ref.getDownloadURL()).toString();
    setState(() {
      url =  togo;
    print('here is your url'+url);
    });
    
}

I later pass it into my network image below

```
I later pass it into my network image below

```
child:Container( margin: EdgeInsets.only(),decoration: BoxDecoration(  
    image: new DecorationImage(
      image: NetworkImage(url),
      fit: BoxFit.cover,),
    

```

these are my rules
```
1
service firebase.storage {
2
  match /b/{bucket}/o {
3
    match /{allPaths=**} {
4
      allow read, write;
5
    }
6
  }
7
}
8
```

here is a screenshot of my firebase storage to prove the file exists
![image](https://user-images.githubusercontent.com/14222186/100057223-b205d780-2e2f-11eb-9f34-865dcf07b141.png)

**Comment by sidrao2006** [comment] 2020-11-24 07:11
Hey @,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with a 3rd party package, please close this issue and open it in the [flutterfire repository](https://github.com/FirebaseExtended/flutterfire/issues) instead.

Thanks

**Comment by pedromassangocode** [comment] 2020-11-24 07:50
Hi @macphailmagwira 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-24 07:50 UTC
