### ISSUE TITLE
[tool_crash] FileSystemException: readSync failed, OS Error: Data error (cyclic redundancy check)., errno = 23

### ISSUE THREAD

**Issue by SameerChorge94** [flutter/flutter#91020] opened 2021-09-30 09:32 UTC
## Command
```
flutter run -d chrome --web-port 60000
```

## Steps to Reproduce
1. Flutter project run for the web with the above command mentioned 

## Logs
FileSystemException: readSync failed, OS Error: Data error (cyclic redundancy check).
, errno = 23
```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:760:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:552:23)
#2      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#4      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:81:41)
#5      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:84:9)
#6      ChromiumLauncher._restoreUserSessionInformation (package:flutter_tools/src/web/chrome.dart:347:24)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:194:7)
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:133:38)
#9      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:521:29)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19043.1151], locale en-IN)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (7 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Sameer.Chorge\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Java\jdk1.8.0_301\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\Sameer.Chorge\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Mi A1 (mobile) • 192.168.5.100:5555 • android-arm64  • Android 9 (API 28)
    • Chrome (web)   • chrome             • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)     • edge               • web-javascript • Microsoft Edge 93.0.961.52

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
### Plugins
file_picker-3.0.4
flutter_keyboard_visibility-5.0.3
flutter_keyboard_visibility_web-2.0.0
flutter_plugin_android_lifecycle-2.0.3
geocoder-0.2.1
google_maps_flutter-2.0.8
location-4.3.0
location_web-3.1.1
package_info-0.4.3+4
path_provider-2.0.3
path_provider_linux-2.0.2
path_provider_macos-2.0.2
path_provider_windows-2.0.3
permission_handler-8.1.4+2
sentry_flutter-4.0.6
simple_auth_flutter-2.0.11
url_launcher-6.0.10
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2
webview_flutter-2.0.12

**Comment by darshankawar** [comment] 2021-09-30 10:30
@SameerChorge94 
This could be happening due to https://github.com/flutter/flutter/issues/61264#issuecomment-656898218
Closing this as duplicate of https://github.com/flutter/flutter/issues/61264

**Closed by darshankawar** 2021-09-30 10:30 UTC
Labels: in triage
