### ISSUE TITLE
[cupertino_icons] Cupertino Icons Gallery link leads to a 404 page

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [flutter/flutter#91341] opened 2021-10-06 06:22 UTC
[Cupertino Icons Gallery](https://flutter.github.io/cupertino_icons) on README of [cupertino_icons package](https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons) always shows 404.

Could you check this?

Thank you.

**Comment by danagbemava-nc** [comment] 2021-10-06 10:16
Duplicate of #88754

**Closed by danagbemava-nc** 2021-10-06 10:16 UTC
Labels: documentation, passed first triage, p: third party, p: cupertino_icons
