### ISSUE TITLE
DeltaTextInputClient as a mixin doesn't work as expected

### ISSUE THREAD

**Issue by angelosilvestre** [flutter/flutter#114380] opened 2022-10-31 22:17 UTC
As of https://github.com/flutter/flutter/pull/104291, `TextInputClient` is a mixin, so we should be able to use it with the `with` keyword, without needing to implement methods that have a default implementation in the mixin. However, when using the `DeltaTextInputClient` with the `with` keyword, we are still obligated to implement all the methods in the mixin, even those with a default implementation.

## Steps to Reproduce

1. Execute `flutter run` on the code sample

**Expected results:** The code should be able to compile.

**Actual results:** The compilation fails. Error message: `Missing concrete implementation of 'TextInputClient.showToolbar'.`

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(
    const MaterialApp(
      home: Scaffold(
        body: TextInputExample(),
      ),
    ),
  );
}

class TextInputExample extends StatefulWidget {
  const TextInputExample({Key? key}) : super(key: key);

  @override
  State<TextInputExample> createState() => _TextInputExampleState();
}

class _TextInputExampleState extends State<TextInputExample> with DeltaTextInputClient {
  @override
  void updateEditingValueWithDeltas(List<TextEditingDelta> textEditingDeltas) {}

  @override
  Widget build(BuildContext context) {
    return SizedBox.shrink();
  }

  // This method has a default implementation in TextInputClient mixin.
  // @override
  // void showToolbar() {}

  @override
  void connectionClosed() {}

  @override
  AutofillScope? get currentAutofillScope => null;

  @override
  TextEditingValue? get currentTextEditingValue => null;

  @override
  void insertTextPlaceholder(Size size) {}

  @override
  void performAction(TextInputAction action) {}

  @override
  void performPrivateCommand(String action, Map<String, dynamic> data) {}

  @override
  void removeTextPlaceholder() {}

  @override
  void showAutocorrectionPromptRect(int start, int end) {}

  @override
  void updateEditingValue(TextEditingValue value) {}

  @override
  void updateFloatingCursor(RawFloatingCursorPoint point) {}
}
```

</details>

<details>
  <summary>Logs</summary>

```
flutter run --verbose
No relevant information.
```

```
flutter analyze
 error - Missing concrete implementation of 'TextInputClient.showToolbar' - lib\main.dart:21:7 - non_abstract_class_inherits_abstract_member  
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.6, on Microsoft Windows [versÆo 10.0.22000.1098], locale pt-BR)
    • Flutter version 3.3.6 on channel stable at c:\git\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (6 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\angelo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32602.215
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at C:\Users\angelo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22000.1098]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.121
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.26

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by matthew-carroll** [comment] 2022-10-31 23:00
@justinmc we tried to switch to a mixin in super_editor to stop breaking when Flutter adds more methods to it. But we ran into this problem.

**Comment by exaby73** [comment] 2022-11-01 07:40
## Triage report

I can reproduce this issue on `Master (3.5.0-12.0.pre.47)`. Changing the mixin to be a `TextInputClient` works.

##### `flutter analyze` error

```console
error • Missing concrete implementations of 'TextInputClient.didChangeInputControl' and 'TextInputClient.performSelector' • lib/main.dart:21:7 • non_abstract_class_inherits_abstract_member
```

**Comment by Renzo-Olivares** [comment] 2022-11-01 20:54
From some initial observation a class will not inherit a mixin's default implementations if those default implementations come from a super class.

dartpad: https://dartpad.dev/?id=09de5ce684b1e4aff55ea090746a032a 

In order to get the default implementations defined in `TextInputClient` it is necessary to do:

```dart
class EditableOne with TextInputClient, DeltaTextInputClient {

}
```

the above change gets the code sample running.

**Comment by justinmc** [comment] 2022-11-01 21:37
Another option is for us to add the same empty implementations to DeltaTextInputClient:

```dart
mixin TextInputClient {
...
  void showToolbar() {}
...
}

mixin DeltaTextInputClient implements TextInputClient {
...
  void showToolbar() {}
...
}
```

Though that is kind of fragile because users that add a new method to TextInputClient in the future may forget to add it to DeltaTextInputClient.

I think the least fragile is the `mixin DeltaTextInputClient on TextInputClient` solution.  That leaves the least room for things to go sideways.  It's probably a small breaking change for super_editor, but I guess it's being broken anyway right now.

**Comment by angelosilvestre** [comment] 2022-11-01 23:16
@Renzo-Olivares Thanks for looking into this. I will use `with TextInputClient, DeltaTextInputClient`

**Comment by Renzo-Olivares** [comment] 2023-10-17 20:46
Closing this since a solution was provided.

**Closed by Renzo-Olivares** 2023-10-17 20:46 UTC
Labels: a: text input, framework, has reproducible steps, P1, found in release: 3.3, found in release: 3.4, team-framework

**Comment by matthew-carroll** [comment] 2023-10-18 21:33
@Renzo-Olivares when closing an issue, it would be helpful if you were explicit about why it's closed and/or what people are supposed to do now that it's closed.

You said you're "closing this since a solution was provided".

Which solution? Where can we find it? How will people know a year from now why exactly this was closed without an associated PR?
