### ISSUE TITLE
Different HEVC video formats are supported

### ISSUE THREAD

**Issue by liangchuying** [flutter/flutter#152542] opened 2024-07-30 07:20 UTC
### Steps to reproduce

Instance code

### Actual results

I used the network addresses of two different HEVC video formats to play, but one of them could not play, and the video was OK. After testing, it could be played on PotPlayer, is it not decoded correctly

### Logs

```
General
Complete name                  : C:\Users\Administrator\Desktop\video(17).mp4
Format                         : MPEG-4
Format profile                 : Base Media / Version 2
Codec ID                       : mp42 (isom/mp41/mp42)
File size                      : 36.1 MiB
Duration                       : 26 s 542 ms
Overall bit rate mode          : Variable
Overall bit rate               : 11.4 Mb/s
Frame rate                     : 30.000 FPS
Encoded date                   : 2024-05-31 07:36:37 UTC
Tagged date                    : 2024-05-31 07:36:37 UTC
Copyright                      : {"WXVer":402665777}
```

Video
```
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L4@Main
HDR format                     : Dolby Vision, Version 1.0, Profile 8.4, dvhe.08.04, BL+RPU, no metadata compression, HLG compatible
Codec ID                       : hvc1
Codec ID/Info                  : High Efficiency Video Coding
Duration                       : 26 s 542 ms
Bit rate                       : 11.2 Mb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Rotation                       : 90°
Frame rate mode                : Variable
Frame rate                     : 30.000 FPS
Minimum frame rate             : 28.571 FPS
Maximum frame rate             : 31.579 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 10 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.179
Stream size                    : 35.3 MiB (98%)
Title                          : Core Media Video
Encoded date                   : 2024-05-31 07:36:37 UTC
Tagged date                    : 2024-05-31 07:36:37 UTC
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : HLG
Matrix coefficients            : BT.2020 non-constant
Metas                          : 3,4,5
Codec configuration box        : hvcC+dvvC
```

Audio
```
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : mp4a-40-2
Duration                       : 26 s 542 ms
Source duration                : 26 s 610 ms
Bit rate mode                  : Variable
Bit rate                       : 186 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 44.1 kHz
Frame rate                     : 43.066 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 602 KiB (2%)
Source stream size             : 604 KiB (2%)
Title                          : Core Media Audio
Encoded date                   : 2024-05-31 07:36:37 UTC
Tagged date                    : 2024-05-31 07:36:37 UTC

```
Other #1
```
ID                             : 3
Type                           : meta
Format                         : mebx
Codec ID                       : mebx
Duration                       : 26 s 542 ms
Title                          : Core Media Metadata
Encoded date                   : 2024-05-31 07:36:37 UTC
Tagged date                    : 2024-05-31 07:36:37 UTC
```

Other #2
```
ID                             : 4
Type                           : meta
Format                         : mebx
Codec ID                       : mebx
Duration                       : 26 s 542 ms
Bit rate mode                  : Variable
Title                          : Core Media Metadata
Encoded date                   : 2024-05-31 07:36:37 UTC
Tagged date                    : 2024-05-31 07:36:37 UTC
```

Other #3
```
ID                             : 5
Type                           : meta
Format                         : mebx
Codec ID                       : mebx
Duration                       : 26 s 542 ms
Bit rate mode                  : Variable
Title                          : Core Media Metadata
Encoded date                   : 2024-05-31 07:36:37 UTC
Tagged date                    : 2024-05-31 07:36:37 UTC
```

### Flutter Doctor output

Initialization failure

**Comment by liangchuying** [comment] 2024-07-30 08:33
Whether there are callbacks for initialization errors

**Comment by darshankawar** [comment] 2024-07-30 10:15
@liangchuying 
What exactly is the issue are you reporting ? What plugin is this related to ? Do you have a code sample that shows the reported behavior ? What platform are you using this for ? Can you provide flutter version ?
Please elaborate or describe the issue by using issue template so that we will have enough information to analyze further.

**Comment by liangchuying** [comment] 2024-07-31 06:33
I'm sorry. It's my description that's wrong. I want to know what to do when the video player does not support the playback format because when I initialize has crashed

E/flutter ( 5588): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/dolby-vision, hev1.08.04, -1, null, [1920, 1080, 29.990328], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, null, null)
E/flutter ( 5588):

**Comment by liangchuying** [comment] 2024-07-31 07:33
https://github.com/flutter/flutter/issues/149721

Something like this

**Comment by darshankawar** [comment] 2024-08-01 05:33
Closing this as duplicate of https://github.com/flutter/flutter/issues/81804 based on initialization error reported. Please follow-up in it for further updates.

**Closed by darshankawar** 2024-08-01 05:33 UTC
Labels: in triage
