### ISSUE TITLE
flutter run crashes when running on ios Simulator: The request to open "com.example.newProject" failed. The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified.

### ISSUE THREAD

**Issue by rjndra** [flutter/flutter#48788] opened 2020-01-14 06:39 UTC
## Steps to Reproduce

Just create new flutter project and run in iOS 10.3.1 simulator.

[Issue in closed issue #27731 ](https://github.com/flutter/flutter/issues/27731#issuecomment-573581747)

**Comment by iapicca** [comment] 2020-01-14 10:43
Hi @rjndra 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by rjndra** [comment] 2020-01-14 15:53
**Faced Similar issue:**

Running in iOS 13.3 simulator , but initial crash in 10.3.1 simulator

**flutter --version**
```
Flutter 1.13.9-pre.59 • channel master • https://github.com/flutter/flutter.git
Framework • revision ab36346af6 (2 days ago) • 2020-01-11 14:20:05 -0500
Engine • revision 3d37d39d95
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 395daaa3ec)
```

**flutter doctor -v**
```
[✓] Flutter (Channel master, v1.13.9-pre.59, on Mac OS X 10.15.2 19C57, locale en-NP)
    • Flutter version 1.13.9-pre.59 at /Users/office/Development/flutter
    • Framework revision ab36346af6 (3 days ago), 2020-01-11 14:20:05 -0500
    • Engine revision 3d37d39d95
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 395daaa3ec)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/office/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • iPhone 11 • 4C8E9273-21A2-4302-A573-2C7AFBC2930F • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPhone 5  • 3C476A01-6AE5-4663-BDA5-F8DF2B2273DA • ios • com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)

• No issues found!
```

**flutter run --verbose**

```
[  +23 ms] executing: [/Users/office/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +39 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ab36346af6e6c61ab4174c753b1ec3f3260fa56a
[        ] executing: [/Users/office/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +22 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.13.8-59-gab36346af
[   +6 ms] executing: [/Users/office/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/office/Development/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [/Users/office/Development/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +6 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19C57
[  +37 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] executing: /Users/office/Library/Android/sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/office/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +14 ms] executing: /Users/office/Development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +77 ms] Error getting attached iOS device: ideviceinfo could not find device:
           No device found with udid 96b479a5754c44bfbc6425f3a98e6f08eac7f8cf, is it plugged in?
           . Try unlocking attached devices.
[   +2 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[        ] executing: /usr/bin/xcodebuild -version
[ +626 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +2 ms] Xcode 11.3
           Build version 11C29
[   +2 ms] /usr/bin/xcrun simctl list --json devices
[ +123 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +4 ms] iPhone 11 • 4C8E9273-21A2-4302-A573-2C7AFBC2930F • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
[        ] iPhone 5  • 3C476A01-6AE5-4663-BDA5-F8DF2B2273DA • ios • com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)
[   +8 ms] "flutter run" took 1,089ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:327:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:618:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:536:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:526:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:289:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:232:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:65:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:63:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
#37     run (package:flutter_tools/runner.dart:52:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/office/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


```
**flutter run**                     
```
More than one device connected; please specify a device with the '-d <deviceId>' flag, or use
'-d all' to act on all devices.

iPhone 11 • 4C8E9273-21A2-4302-A573-2C7AFBC2930F • ios •
com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
iPhone 5  • 3C476A01-6AE5-4663-BDA5-F8DF2B2273DA • ios •
com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)

```

**flutter run -d 3C476A01-6AE5-4663-BDA5-F8DF2B2273DA**
```
Launching lib/main.dart on iPhone 5 in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           2.5s
 └─Compiling, linking and signing...                         4.3s
Xcode build done.                                            8.5s
            PackageType = Developer;
            SimulatorRootPath = "/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot";
            SimulatorUserPath = "/Users/office/Library/Developer/CoreSimulator/Devices/3C476A01-6AE5-4663-BDA5-F8DF2B2273DA/data";
        }
        state->old_bundle: /Users/office/Library/Developer/CoreSimulator/Devices/3C476A01-6AE5-4663-BDA5-F8DF2B2273DA/data/Containers/Bundle/Application/1DFF7DC2-C7C1-4847-B05B-05969E4A9CC2/Runner.app
        state->new_bundle: /Users/office/Documents/flutter_practise/flutter_saving_data/build/ios/iphonesimulator/Runner.app
        state->dst_bundle: /Users/office/Library/Developer/CoreSimulator/Devices/3C476A01-6AE5-4663-BDA5-F8DF2B2273DA/data/Library/Caches/com.apple.mobile.installd.staging/temp.rBxgha/extracted/Payload//Runner.app, binaryDiff flag: FALSE
                dst_ipa: /Users/office/Library/Developer/CoreSimulator/Devices/3C476A01-6AE5-4663-BDA5-F8DF2B2273DA/data/Library/Caches/com.apple.mobile.installd.staging/temp.rBxgha/extracted
            CFBundleIdentifier = "com.example.flutterSavingData";
            PackageType = Developer;
            SimulatorRootPath = "/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot";
            SimulatorUserPath = "/Users/office/Library/Developer/CoreSimulator/Devices/3C476A01-6AE5-4663-BDA5-F8DF2B2273DA/data";
        })
            arguments =     (
                "--enable-dart-profiling",
                "--enable-checked-mode",
                "--verify-entry-points",
                "--observatory-port=0"
            );
            environment =     {
                TERM = "xterm-256color";
            };
        }
                retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
                bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
                bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
                Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
        Simulator booted at: 2020-01-13 05:25:27 +0000
        Current time: 2020-01-13 09:27:11 +0000
        Within boot leeway: NO
Jan 13 15:12:11 Offices-MacBook-Pro com.apple.CoreSimulator.SimDevice.3C476A01-6AE5-4663-BDA5-F8DF2B2273DA[3678] (UIKitApplication:com.example.flutterSavingData[0x6fef][3700][33530]): Program specified by service does not contain one of the requested architectures: 
            description = "The request to open "com.example.flutterSavingData" failed.";
            failureReason = "The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified.";
            underlyingError = <NSError: 0x78e6e570; domain: FBSOpenApplicationErrorDomain; code: 1 (Unspecified)> {
                description = "The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)";
            };
        }
ProcessException: Process exited abnormally:
com.example.flutterSavingData: -1

_An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain,
code=1):
The request to open "com.example.flutterSavingData" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified.
Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
        The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
  Command: /usr/bin/xcrun simctl launch 3C476A01-6AE5-4663-BDA5-F8DF2B2273DA
  com.example.flutterSavingData --enable-dart-profiling --enable-checked-mode
  --verify-entry-points --observatory-port=0
Error launching application on iPhone 5._
```

**Comment by iapicca** [comment] 2020-01-15 08:18
thank you @rjndra

**Comment by Faisalkc4u** [comment] 2020-01-15 14:53
Facing the same issue
Unable to run on ios simulator
 flutter --version


Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (5 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

 flutter doctor -v


[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-AE)
    • Flutter version 1.12.13+hotfix.5 at /Applications/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Lenovo L38083     • HTF02QES                             • android-arm64 • Android 9 (API 28)
    • iPhone 11 Pro Max • 7BA119E2-88D3-4B68-BB17-A3FA82C37D72 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

flutter run --verbose

[  +29 ms] executing: [/Applications/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/Applications/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +17 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[   +8 ms] executing: [/Applications/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Applications/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +66 ms] executing: [/Applications/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +8 ms] executing: sw_vers -productName
[  +19 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +20 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +19 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19C57
[  +36 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +217 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.3.1
           Build version 11C504
[  +73 ms] executing: /Users/apple/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/apple/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           HTF02QES               device usb:336592896X product:L38083 model:Lenovo_L38083 device:L38083 transport_id:2
[  +23 ms] executing: /Applications/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +174 ms] /usr/bin/xcrun simctl list --json devices
[ +386 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +4 ms] /Users/apple/Library/Android/sdk/platform-tools/adb -s HTF02QES shell getprop
[ +141 ms] ro.hardware = mt6765
[        ] ro.build.characteristics = default
[   +4 ms] Lenovo L38083     • HTF02QES                             • android-arm64 • Android 9 (API 28)
[        ] iPhone 11 Pro Max • 7BA119E2-88D3-4B68-BB17-A3FA82C37D72 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
[  +12 ms] "flutter run" took 1,178ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Applications/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by jmagman** [comment] 2020-01-15 19:36
@Faisalkc4u Your logs indicate you need to specify the device when you run `flutter run`, I don't see a simulator crash in there.

```
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.example.newProject" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified.
Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
```

**Comment by Faisalkc4u** [comment] 2020-01-15 20:19
@jmagman  I was working on a project for past 3 months. I use VS code.
Last day there was an update in Xcode. After the update when am running the app in simulator, The app will be installed on simulator still the VS code says the "Xcode Building", in the debug console "Xcode Build id done". When I tried to run the app manually the app is not opening.
If am running the same code with same procedure on real device android and ios both are working as expected. The issue is facing only ios simulator.

**Comment by jmagman** [comment] 2020-01-16 00:27
> @jmagman I was working on a project for past 3 months. I use VS code.
> Last day there was an update in Xcode. After the update when am running the app in simulator, The app will be installed on simulator still the VS code says the "Xcode Building", in the debug console "Xcode Build id done". When I tried to run the app manually the app is not opening.
> If am running the same code with same procedure on real device android and ios both are working as expected. The issue is facing only ios simulator.

@Faisalkc4u Are you seeing the "The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified.
Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):" error?  I don't see it in the logs you attached.

If not, you should file a new issue so we can investigate separately.

**Comment by rjndra** [comment] 2020-01-16 06:31
@jmagman 
**From VSCode:** The flutter app is installed on iPhone 5 simulator(iOS 10.3.1) but as soon as app is installed, it crashes.
**From Xcode:** The flutter app is not installed on iPhone 5 simulator(iOS 10.3.1) with error:

```
ld: framework not found path_provider
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```


**The brand new non-Flutter project is installed and run for iPhone 5 simulator(iOS 10.3.1).**


**Other Case as well**
For iOS Application having flutter integrated as module as created from [documentation](https://flutter.dev/docs/development/add-to-app/ios/project-setup) runs in iphone 11 with simulator 13.3 but  for iPhone 5 simulator(iOS 10.3.1) shows following error
```
ld: warning: ignoring file /Users/office/Documents/new_flutter/.ios/Flutter/engine/Flutter.framework/Flutter, missing required architecture i386 in file Users/office/Documents/new_flutter/.ios/Flutter/engine/Flutter.framework/Flutter (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_METACLASS_$_FlutterAppDelegate", referenced from:
      _OBJC_METACLASS_$__TtC12MyApp_Debug11AppDelegate in AppDelegate.o
  "_OBJC_CLASS_$_FlutterViewController", referenced from:
      objc-class-ref in FlutterRouter.o
  "_FlutterMethodNotImplemented", referenced from:
      closure #1 (__C.FlutterMethodCall, (Any?) -> ()) -> () in MyApp_Debug.FlutterRouter.setupRouteBack(to: __C.FlutterViewController) -> () in FlutterRouter.o
  "_OBJC_CLASS_$_FlutterAppDelegate", referenced from:
      type metadata for MyApp_Debug.AppDelegate in AppDelegate.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in FlutterRouter.o
  "_OBJC_CLASS_$_FlutterEngine", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The brand new app created in Xcode 11.3 and run on same simulator is working fine.

**Comment by jmagman** [comment] 2020-01-16 19:54
```
ld: framework not found path_provider
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Can you confirm you were running ios/Runner.xcworkspace and NOT Runner.xcodeproj in Xcode?

**Comment by rjndra** [comment] 2020-01-17 05:08
> ```
> ld: framework not found path_provider
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> 
> Can you confirm you were running ios/Runner.xcworkspace and NOT Runner.xcodeproj in Xcode?

Yes I was running iOS/Runner.xcworkspace and NOT Runner.xcodeproj.

**Comment by EngAddow** [comment] 2020-11-09 11:11
```
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
 lib/main.dart
Xcode build done.                                           26.6s
Exception: Unable to launch com.johrh.app on 5C58F07A-435D-4EF8-BB22-B26213B70BBE:
ProcessException: Process exited abnormally:
com.johrh.app: -1

An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.johrh.app" failed.
The request was denied by service delegate (SBMainWorkspace).
Underlying error (domain=FBProcessExit, code=64):
	The operation couldn’t be completed. The process failed to launch.
	The process failed to launch.
  Command: /usr/bin/xcrun simctl launch 5C58F07A-435D-4EF8-BB22-B26213B70BBE com.johrh.app --enable-dart-profiling --enable-checked-mode --verify-entry-points --start-paused
Error launching application on iPhone SE (2nd generation).
Exited (sigterm)

``` 

here I guess I have similar issue

**Comment by jmagman** [comment] 2020-11-09 18:29
This is definitely a bug in the simulator, not Flutter.  Stackoverflow answers suggest restarting the simulator.

@EngAddow  If you open Console and look for something related to SBMainWorkspace or your bundle ID `com.johrh.app` at the same timestamp you might find some interesting logs from the simulator.

**Comment by EngAddow** [comment] 2020-11-10 06:04
It was working for me before and I didn't  do any changes. @jmagman

**Comment by jmagman** [comment] 2020-11-10 06:11
> It was working for me before and I didn't do any changes. @jmagman

No doubt, looks like a simulator bug, not something specific to your project.  See [this SO post](https://stackoverflow.com/questions/46081483/the-request-was-denied-by-service-delegate-sbmainworkspace-on-ios-10-0-simula), for example.

> @EngAddow If you open Console and look for something related to SBMainWorkspace or your bundle ID `com.johrh.app` at the same timestamp you might find some interesting logs from the simulator.

**Comment by jmagman** [comment] 2021-03-15 23:59
I'm going to close this one, there's nothing Flutter can do about an iOS simulator bug.

**Comment by jmagman** [comment] 2021-03-15 23:59
Let us know if you're seeing in recent Xcode versions.

**Closed by jmagman** 2021-03-15 23:59 UTC
Labels: P4, d: devtools, platform-ios, severe: crash, tool

**Comment by SebghatYusuf** [comment] 2021-07-19 17:50
@jmagman 
I'm facing the same issue, in Xcode version 12.5
