### ISSUE TITLE
Native YOUTUBE VIDEO PLAYER For Flutter

### ISSUE THREAD

**Issue by Amanullahgit** [flutter/flutter#61302] opened 2020-07-11 17:23 UTC
## Use case
I wanted to play youtube videos in my app, i tried different packages but all having some issue. this is a useful package and has to be added...

## Proposal

Hello Flutter team,

Thank you for providing lots of cool features in flutter, i would be glad if you add this feature as well.

VOTE IF YOU AGREE!

thanks,

**Comment by YazeedAlKhalaf** [comment] 2020-07-11 18:42
We agree my friend but the issue has been stuck for years now
#13756

you can see the progress in the issue mentioned above

This is a duplicate anyways 😊

**Comment by timsneath** [comment] 2020-07-11 21:54
Duplicate of #13756

**Closed by timsneath** 2020-07-11 21:54 UTC
