### ISSUE TITLE
[camera_web] [Safari] Camera preview is not shown

### ISSUE THREAD

**Issue by KochankovID** [flutter/flutter#93241] opened 2021-11-08 11:33 UTC
I've developed a flutter application that uses the camera plugin. I've deployed it and tested it on different browsers. 

The first problem is that it doesn't work on any mobile browsers (but I've found opened an issue for this case).

But the main issue is that it doesn't work on Safari (laptop). When I say "doesn't work" I mean doesn't show the camera feed (strange, but it still can make a photo) and doesn't throw any exceptions. On other browsers (chrome, brave, Yandex) it works perfectly.

How it must work:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/33292483/140703288-6ddb1a84-da2a-473a-b6bd-2e8f496dad77.png">

How it works in Safari:
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/33292483/140703349-97a1481f-f33b-4d08-8472-441363ab8a72.png">

You can try it using this [link](https://rapid-sky-2948.on.fleek.co/) or if you use brave with ipfs (ipfs://bafybeiabfhb2tou5y2nfcfsprqwvb3agofxneomlduj5ptxuuexsevqryq/#/)

## Steps to Reproduce

1. Execute `flutter build web` on the code sample 

<details>
<summary>sample code</summary>

```dart
class ImagePreview extends StatefulWidget {
  final XFile? image;
  final Function(CameraController?) notifyParent;

  const ImagePreview({Key? key, this.image, required this.notifyParent})
      : super(key: key);

  @override
  State<ImagePreview> createState() => _ImagePreviewState();
}

class _ImagePreviewState extends State<ImagePreview> {
  List<CameraDescription>? cameras;
  CameraController? controller;
  Future? _future;

  getCameras() async {
    cameras = await availableCameras();
    controller = CameraController(
        kIsWeb
            ? cameras!.first
            : cameras!.firstWhere(
                (camera) => camera.lensDirection == CameraLensDirection.front),
        ResolutionPreset.high);
    await controller?.initialize();
  }

  @override
  void initState() {
    super.initState();
    _future = getCameras();
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: _future,
        builder: (context, asyncSnapshot) {
          switch (asyncSnapshot.connectionState) {
            case ConnectionState.none:
            case ConnectionState.waiting:
            case ConnectionState.active:
              return const Expanded(
                  child: Center(child: CircularProgressIndicator()));
            case ConnectionState.done:
              widget.notifyParent(controller);

              return Expanded(
                child: Padding(
                  padding: const EdgeInsets.only(
                      top: 8.0, left: 8, right: 8, bottom: 5),
                  child: ClipRRect(
                    borderRadius: const BorderRadius.only(
                        topLeft: Radius.circular(30),
                        topRight: Radius.circular(30)),
                    child: Container(
                        //If we don't chose the image
                        color: Theme.of(context).disabledColor,
                        child:
                            // If has image
                            widget.image != null
                                ? kIsWeb
                                    // If web platform
                                    ? Image.network(
                                        widget.image!.path,
                                        fit: BoxFit.fitHeight,
                                      )
                                    :
                                    // If android platform
                                    Image.file(
                                        File(widget.image!.path),
                                        fit: BoxFit.fitHeight,
                                      )
                                :
                                // If don't have image enable camera
                                !asyncSnapshot.hasError &&
                                        controller!.value.isInitialized
                                    ? Center(
                                        // Has camera access
                                        child: CameraPreview(controller!),
                                      )
                                    :
                                    // Moc icon
                                    const Icon(Icons.add_photo_alternate)),
                  ),
                ),
              );
          }
        });
  }
}
```
</details>

<details>
<summary> Flutter doctor </summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale ru-RU)
    • Flutter version 2.5.3 at /Users/ilyakochankov/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ilyakochankov/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/ilyakochankov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/ilyakochankov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/ilyakochankov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/ilyakochankov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Users/ilyakochankov/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Users/ilyakochankov/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5457.46/IntelliJ IDEA.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5486

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Users/ilyakochankov/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5284.40/IntelliJ IDEA.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5486

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>
---

Also, I've tried to use html web-renderer, and it helps a bit: Safari slowly enable camera view with big latency, but then, when I try to enable it again (for example I want to take another photo, the camera wouldn't work again) and also camera has a bad resolution. 

I can attach any additional info about this issue :)

**Comment by danagbemava-nc** [comment] 2021-11-08 14:02
Hi @KochankovID, your sample seems to require a `notifyParent` method which isn't provided in your sample. 
Please provide a complete minimal reproducible code sample. 

Also what version of `camera` are you using? 

Thank you

**Comment by KochankovID** [comment] 2021-11-09 04:49
@danagbemava-nc 

I've shorted the code of my app a bit, but it still does the trick.

```
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Tonal cream assistant',
      debugShowCheckedModeBanner: false,
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(), // Footer
        bottomSheet: const HomeBottomSheet());
  }
}

class BaseBottomSheet extends StatelessWidget {
  final Widget child;

  const BaseBottomSheet({Key? key, required this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BottomSheet(
      enableDrag: false,
      elevation: 3,
      backgroundColor: Theme.of(context).bottomAppBarColor,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.only(
            topLeft: Radius.circular(30), topRight: Radius.circular(30)),
      ),
      builder: (BuildContext buildContext) {
        return LayoutBuilder(builder: (context, constraints) {
          return SizedBox(
              height: MediaQuery.of(context).size.height /
                  (constraints.maxWidth > 400 ? 2 : 2.65),
              width: double.infinity,
              child: child);
        });
      },
      onClosing: () {},
    );
  }
}

class HomeBottomSheet extends StatefulWidget {
  const HomeBottomSheet({Key? key}) : super(key: key);

  @override
  State<HomeBottomSheet> createState() => _HomeBottomSheetState();
}

class _HomeBottomSheetState extends State<HomeBottomSheet>
    with WidgetsBindingObserver {
  XFile? _image;
  final ImagePicker _picker = ImagePicker();
  List<CameraDescription>? cameras;
  CameraController? controller;
  Future? _future;

  @override
  void initState() {
    super.initState();
    _future = getCameras();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _future = controller?.initialize();
    }
  }

  getCameras() async {
    cameras = await availableCameras();
    controller = CameraController(
        kIsWeb
            ? cameras!.first
            : cameras!.firstWhere(
                (camera) => camera.lensDirection == CameraLensDirection.front),
        ResolutionPreset.max);
    await controller?.initialize();
  }

  _getImageGallery() async {
    XFile? image = await _picker.pickImage(source: ImageSource.gallery);
    setState(() {
      _image = image;
    });
  }

  _getImageCamera() async {
    // If already have image (Take another button)
    if (_image != null) {
      setState(() {
        _future = controller?.initialize();
        _image = null;
      });
    } else {
      final image = await controller?.takePicture();
      setState(() {
        _image = image;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return BaseBottomSheet(
        child: Column(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        FutureBuilder(
            future: _future,
            builder: (context, asyncSnapshot) {
              switch (asyncSnapshot.connectionState) {
                case ConnectionState.none:
                case ConnectionState.waiting:
                case ConnectionState.active:
                  return const Expanded(
                      child: Center(child: CircularProgressIndicator()));
                case ConnectionState.done:
                  if (_image != null) {
                    return ImagePreview(image: _image!);
                  }

                  if (!asyncSnapshot.hasError &&
                      controller!.value.isInitialized) {
                    // Has camera access
                    return Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: ClipRRect(
                          borderRadius: const BorderRadius.only(
                              topLeft: Radius.circular(30),
                              topRight: Radius.circular(30)),
                          child: Container(child: CameraPreview(controller!)),
                        ),
                      ),
                    );
                  } else {
                    // Moc icon
                    return const Icon(Icons.add_photo_alternate);
                  }
              }
            }),
        Padding(
          padding: const EdgeInsets.only(bottom: 5.0),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              BottomSheetButton(
                  icon: Icons.add_photo_alternate,
                  text: 'Gallery',
                  onPressed: _getImageGallery),
              BottomSheetButton(
                  icon: _image == null ? Icons.camera : Icons.repeat,
                  text: _image == null ? "Camera" : "Take another",
                  onPressed: _getImageCamera),
            ],
          ),
        ),
      ],
    ));
  }
}

class ImagePreview extends StatelessWidget {
  final XFile image;

  const ImagePreview({Key? key, required this.image}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Padding(
        padding: const EdgeInsets.only(top: 8.0, left: 8, right: 8, bottom: 5),
        child: ClipRRect(
            borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(30), topRight: Radius.circular(30)),
            child: Container(
                //If we don't chose the image
                color: Theme.of(context).disabledColor,
                child: kIsWeb
                    ?
                    // If web platform
                    Image.network(
                        image.path,
                        fit: BoxFit.fitHeight,
                      )
                    :
                    // If android platform
                    Image.file(
                        File(image.path),
                        fit: BoxFit.fitHeight,
                      ))),
      ),
    );
  }
}

class BottomSheetButton extends StatelessWidget {
  final Function() onPressed;
  final String text;
  final IconData icon;

  const BottomSheetButton(
      {Key? key,
      required this.onPressed,
      required this.text,
      required this.icon})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Padding(
        padding: const EdgeInsets.only(left: 8.0, right: 8.0),
        child: ElevatedButton.icon(
          icon: Icon(
            icon,
            color: Theme.of(context).iconTheme.color,
          ),
          label: Text(
            text,
            style: TextStyle(color: Theme.of(context).iconTheme.color),
          ),
          onPressed: onPressed,
        ),
      ),
    );
  }
}
```

---

What I found out is that safari somehow return 1) Wrong aspect ratio for camera (chrome 1.3, safari 1.7) and also it returns false from ```_isLandscape()``` function in the CameraPreview widget (chrome return true). 

---


My pubspec is:
```
name: TonalCreamAssistant
description: the system which helps people to choose the right color tone for them using photos.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+2
  file_picker: ^4.1.3
  dio: ^4.0.1
  animated_check: ^1.0.5
  bordered_text: ^2.0.0
  camera: ^0.9.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

**Comment by danagbemava-nc** [comment] 2021-11-09 08:07
@KochankovID, thanks for the updated sample. 

Issue is reproducible on `stable` and `master` using `camera: ^0.9.4+3`. 

It is present only in `Safari` only when using the `canvaskit` renderer. 
The `html` renderer shows the camera preview, however, the aspect ratio is off. 


<details>
<summary>screenshots</summary>

| safari (canvaskit) | safari (HTML) | Chrome | 
| -- | -- | -- | 
| ![Screenshot 2021-11-09 at 07 41 29](https://user-images.githubusercontent.com/88313112/140885668-3a4c4b62-71aa-4e61-9349-3f4b139871cb.png) |  ![Screenshot 2021-11-09 at 07 58 37](https://user-images.githubusercontent.com/88313112/140885689-6eded0a1-172a-4d9c-8e8e-c78f8a605e6d.png) | <img width="1431" alt="Screenshot 2021-11-09 at 07 44 28" src="https://user-images.githubusercontent.com/88313112/140885726-20f20b8c-f003-42b4-9c13-047629f654e8.png"> |

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.657, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.657 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a61c57add6 (2 hours ago), 2021-11-08 21:37:48 -0800
    • Engine revision 162d8508f8
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  • Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

**Comment by ditman** [comment] 2021-11-11 21:17
I've just noticed that the video preview of the camera is inside a ClipRRect (or similar, to give it rounded corners). If the `clip-path: url()` styles are removed from the generated output, the video preview shows up as expected.

I think this is caused by these bugs:

* https://github.com/flutter/flutter/issues/80401
* https://github.com/flutter/flutter/issues/91805

Marking as P3 to keep it in sync with the other two issues!

**Comment by Oleh-Sv** [comment] 2022-09-02 18:23
@danagbemava-nc  For fix this problem we just need to add width, height to `flt_clip` tag. I tried to create PR for engine, but code that creates html looks like mess. If you can add height, width to flutter engine do it please.
<img width="1267" alt="Screenshot 2022-09-02 at 19 21 22" src="https://user-images.githubusercontent.com/17007214/188214703-4a0617aa-9c64-4c02-9659-8e2121a3ba0e.png">

**Comment by ditman** [comment] 2022-09-30 00:07
@Oleh-Sv has provided a fix for this issue, here: https://github.com/flutter/engine/pull/35948

Thanks Oleg!

I'm closing this issue as fixed. If anybody still experiences problems, please, create a new issue!

**Closed by ditman** 2022-09-30 00:07 UTC
Labels: engine, plugin, p: first party, platform-web, p: camera, e: web_canvaskit, passed secondary triage, has reproducible steps, browser: safari-macos, P3, found in release: 2.5, found in release: 2.6
