### ISSUE TITLE
WebView's text selection handles are not showing on Android

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#24584] opened 2018-11-20 22:21 UTC
It seems that the selection handles are implemented as a `PopupWindow`, seems like we don't support these well enough.

**Comment by romatroskin** [comment] 2018-12-30 09:48
can we rely on this issue to be fixed soon? it's really important for us :(

**Comment by filipenanclarez** [comment] 2019-04-11 23:13
Without this, we can't made apps to read ebooks.

Please pay attention to this issue.

**Comment by bojie-liu** [comment] 2019-08-10 16:35
Is there any progress for this issue? I studied the source code and found something.
PopupWindows in (Android) WebView requires WebView's hasWindowFocus as true to update its position and drawing state. However the Window the WebView attach to is set to FLAG_NOT_FOCUSABLE in SingleViewPresentation. This NOT_FOCUSABLE commit(42bd86d) is a workaround fix to another keyboard issue according to the commit message. 
As a quick verification if focus on window could make selection handles shown, I tried removing FLAG_NOT_FOCUSABLE for WebView and setLocalFocus for the FlutterView which leads to both Window are focused in Android framework. And it works. Although keyboard in WebView is not shown again. It seems I have to dig deeper to understand what's going on there.

**Comment by amirh** [comment] 2019-08-13 01:07
@bojie-liu thanks for the info, this is really helpful! Can you point to the PopupWindow code that checks for the focus?

Given your findings, it may make sense to override `hasWindowFocus` (the plugin subclasses `WebView` already) and return whether the FlutterView's window is focused.

**Comment by conghaonet** [comment] 2019-11-06 13:57
it is the same with webview_flutter 0.3.15+1

**Comment by bojie-liu** [comment] 2019-11-09 03:24
Sorry for taking two months to reply. It seems I got no notification from user center, although already subscribed. May be I should read some github manuals later.

The PopupWindow related code is in PopupTouchHandleDrawable.java (link is as follows). The updateVisibility() will check if isShowingAllowed() and setVisibility() for current drawable. And one of conditions in isShowingAllowed() is mFocused which was set to containerView.hasWindowFocus() initially. In my experiment, the false mFocused is the cause of invisibility of the handles. 
https://cs.chromium.org/chromium/src/android_webview/java/src/org/chromium/android_webview/PopupTouchHandleDrawable.java?rcl=cf0b4429b5815c4a2bc753e42159f9dc2cb90037&l=443
@amirh

**Comment by Hixie** [comment] 2019-11-27 00:31
@amirh Can we have this assigned and a conservative milestone specified? Thanks!

**Comment by tvqphong001** [comment] 2020-01-20 03:40
in native code, i can selectionm, copy/paste,... need support in next hoxfix

**Comment by acoutts** [comment] 2020-01-28 20:29
Having an issue with this as well.

**Comment by heatonandy** [comment] 2020-01-30 16:41
Can we get an updated timeline for this? Really appreciate all the work being put in to make Flutter better.  This is a pretty serious issue for us.  Thank you very much!

**Comment by acoutts** [comment] 2020-01-30 16:52
@heatonandy if all you need is a webview to open a page, you may want to use this lib instead as it will be much more full-featured (using the system browser) than implementing your own webview: https://pub.dev/packages/flutter_custom_tabs

And if you are needing it for oauth, using the native AppAuth system is always best for that: https://pub.dev/packages/flutter_appauth

**Comment by heatonandy** [comment] 2020-01-30 17:27
> @heatonandy if all you need is a webview to open a page, you may want to use this lib instead as it will be much more full-featured (using the system browser) than implementing your own webview: https://pub.dev/packages/flutter_custom_tabs
> 
> And if you are needing it for oauth, using the native AppAuth system is always best for that: https://pub.dev/packages/flutter_appauth

Thanks @acoutts, I actually need the fix for full text editing with a web editor that is shared between mobile and web.

**Comment by virskor** [comment] 2020-02-14 09:43
i got this issue, bad

**Comment by myriky** [comment] 2020-02-15 10:30
any idea?

**Comment by virskor** [comment] 2020-02-17 14:58
@ lawlsausage did you resolve this problem by adding this merge? i am not sure if paste or copy is working on android now. and i need this feature. Thanks for your  great job

**Comment by lawlsausage** [comment] 2020-02-19 16:15
I'm sorry, I didn't realize that adding the URL to this issue in my own Git commit message would automatically show up here. This was actually just "fixed" in my own project which doesn't have any connection to the flutter/plugins/webview_flutter project.

I will say that what I did is __not__ a complete solution, but overriding `hasWindowFocus` to return true did end up showing the selection handles. I am just as interested in seeing an implementation of `hasWindowFocus` for this issue which accounts for various scenarios where focus must be gained or removed.

**Comment by lawlsausage** [comment] 2020-02-19 16:16
> @ lawlsausage did you resolve this problem by adding this merge? i am not sure if paste or copy is working on android now. and i need this feature. Thanks for your great job

I'm sorry, I didn't realize that adding the URL to this issue in my own Git commit message would automatically show up here. This was actually just "fixed" in my own project which doesn't have any connection to the flutter/plugins/webview_flutter project.

I will say that what I did is not a complete solution, but overriding hasWindowFocus to return true did end up showing the selection handles. I am just as interested in seeing an implementation of hasWindowFocus for this issue which accounts for various scenarios where focus must be gained or removed.

**Comment by grandleaf** [comment] 2020-03-26 16:49
> Is there any progress for this issue? I studied the source code and found something.
> PopupWindows in (Android) WebView requires WebView's hasWindowFocus as true to update its position and drawing state. However the Window the WebView attach to is set to FLAG_NOT_FOCUSABLE in SingleViewPresentation. This NOT_FOCUSABLE commit([42bd86d](https://github.com/flutter/flutter/commit/42bd86d6db3d403f98d5d4f05340d76889031e3f)) is a workaround fix to another keyboard issue according to the commit message.
> As a quick verification if focus on window could make selection handles shown, I tried removing FLAG_NOT_FOCUSABLE for WebView and setLocalFocus for the FlutterView which leads to both Window are focused in Android framework. And it works. Although keyboard in WebView is not shown again. It seems I have to dig deeper to understand what's going on there.

Hi, Would you please share your modification.  I am very interested in it and want have a try.  However, I have no idea how to modify that java file.  It looks belongs to the framework, I cannot find it anywhere. 

Thanks

**Comment by tvolkert** [comment] 2020-04-01 00:05
@bparrishMines this is one of four webview issues marked as critical.  How's your bandwidth for being able to look at these?

**Comment by bparrishMines** [comment] 2020-04-02 19:25
@tvolkert, @amirh and I have already found a solution to this. You can solve this problem by overriding `hasWindowFocus()`. However, it doesn't do much good if someone cant click on the text selection dialog: https://github.com/flutter/flutter/issues/24585.

**Comment by blasten** [comment] 2020-06-04 02:24
I have verified that hybrid composition on Android fixes this issue. However, more testing needs to be done before we decide if this plugin can be migrated to this mode.

We expect to release hybrid composition on Android next stable release.

@bparrishMines let's chat about your findings when you get chance.

**Comment by zanderso** [comment] 2020-06-08 18:05
@blasten @bparrishMines Will this make it in by end of the month? Do you want to adjust the milestone?

**Comment by blasten** [comment] 2020-06-08 18:31
@zanderso sgtm. I updated the milestone.

**Comment by uc-apa** [comment] 2020-06-24 07:07
Please look into this issue and let us know its ETA. It is required for us to build apps for our customers. It is working in iOS but not android. The text itself is not getting selected so the document.addEventListener('selectionchange',... event is also not fired. I am unable to proceed due to this issue. Kindly have a look or provide a workaround if any.

**Comment by Calm-Smile** [comment] 2020-07-04 18:03
I got the same problem in android.. can't copy or paste anything.
PlA-29 Huawei mate 10 pro.

**Comment by ishowfun** [comment] 2020-07-13 06:45
any progress on this issue?
our team stucked in this issue for over one year.
yet it doesn't seem to be give a signal to start this by the flutter team.

**Comment by blasten** [comment] 2020-07-13 16:03
@ishowfun https://github.com/flutter/flutter/issues/61133

**Comment by ishowfun** [comment] 2020-07-14 01:21
@blasten  just like the wechat miniprogram?

**Comment by mrifni** [comment] 2020-07-16 14:38
no offence to flutter, but i can tell you flutter team would take at least 18 months to fix this issue. based on my experience on past reported bugs.

**Comment by chinmaygarde** [comment] 2020-09-14 17:39
Per Ray, this should be fixed in 1.22. That is under verification right now.

**Comment by Xgamefactory** [comment] 2020-09-24 15:04
waiting for fix.

**Comment by blasten** [comment] 2020-10-14 00:05
This has been fixed in Flutter 1.22/ WebView 1.0 - use hybrid composition in the Flutter WebView plugin. 

https://github.com/flutter/plugins/tree/master/packages/webview_flutter#using-hybrid-composition

**Closed by blasten** 2020-10-14 00:05 UTC
Labels: P3, a: platform-views, customer: crowd, customer: product, customer: raven, engine, p: first party, p: webview, platform-android, plugin, waiting for PR to land (fixed)

**Comment by shafimuhammed** [comment] 2021-07-27 11:06
Try this

` @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) {
      WebView.platform = SurfaceAndroidWebView();
    }
  }`
