### ISSUE TITLE
Inkwell touch feedback is flowing over bottomNavigationBar when no background color is provided.

### ISSUE THREAD

**Issue by adnanjpg** [flutter/flutter#93595] opened 2021-11-13 13:05 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Scroll until an item is half visible, and the other half is behind the `bottomNavigationBar`
3. long press on the item to see how the touch feedback is flowing over `bottomNavigationBar` (the body's z-index is greater)

this problem exists because no background color was provided to the `bottomNavigationBar`

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
        itemCount: 20,
        itemBuilder: (BuildContext context, int index) {
          return InkWell(
            onTap: () {},
            child: Container(
              padding: const EdgeInsets.all(50),
              child: Text('Item $index'),
            ),
          );
        },
      ),
      bottomNavigationBar: Container(
        // color: Colors.blue,
        padding: const EdgeInsets.all(30),
        child: const Text('a'),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
adnanfahed@Adnans-MacBook-Pro bug_report % flutter analyze
Analyzing bug_report...                                                 
No issues found! (ran in 2.4s)
```

```
adnanfahed@Adnans-MacBook-Pro bug_report % flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.5.2 20G95 darwin-x64, locale en)
    • Flutter version 2.5.3 at /Users/adnanfahed/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/adnanfahed/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] VS Code (version 1.62.2)
    • VS Code at /Users/adnanfahed/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 7c0edb93134cbbf0493eb34ada73e295cffa68cf • ios            • iOS 15.0.1 19A348
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

</details>

![Screenshot 2021-11-17 at 11 47 34 AM](https://user-images.githubusercontent.com/67046386/142145255-3bcd4474-dbba-4166-ac5e-7db1dda08762.png)
![Screenshot 2021-11-17 at 11 47 46 AM](https://user-images.githubusercontent.com/67046386/142145260-5f523d59-274a-43b0-af96-5721fd00d7ab.png)

**Comment by darshankawar** [comment] 2021-11-15 07:29
@adnanjpg 
You are seeing that behavior because you wrapped `bottomNavigtionbar` with `Container`. If you directly try the official code sample, you'll get the expected behavior as below:

![Screenshot 2021-11-15 at 12 53 31 PM](https://user-images.githubusercontent.com/67046386/141739646-b24b670c-e09b-4da1-ae9e-4438dd2d88df.png)

```
bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.business),
            label: 'Business',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.school),
            label: 'School',
          ),
        ],
      //  currentIndex: _selectedIndex,
        selectedItemColor: Colors.amber[800],
     //   onTap: _onItemTapped,
      ),
```

**Comment by adnanjpg** [comment] 2021-11-15 07:36
Yes you are right, but it is common to use `bottomNavigationBar` for another purposes other than putting multiple navigation items as shown in the example you've provided.

**Comment by rafat-fp** [comment] 2021-11-15 18:42
@adnanjpg There are some default attributes for the **BottomNavigationBar** widget. If you see carefully then you can notice that _bottomNavigationBar_ expects **Widget?** as a parameter, not a **BottomNavigationBar**. You pass any widget as a parameter. So if you want attributes like  **BotBottomNavigationBar** then you have to use it or create a widget that contains the same attributes like **BottomNavigationBar** then it will behave as you are expecting.

**Comment by adnanjpg** [comment] 2021-11-15 18:48
it is not about what i expect, as i mentioned above i was able to make it bahave as i am expecting by providing a background color to the widget provided as a value for the `bottomNavigationBar` parameter. i am not sure if this is an expected behaviour or a bug

**Comment by darshankawar** [comment] 2021-11-16 06:29
@adnanjpg 
Would like to understand more about your use case you are trying to achieve. Can you elaborate on it by providing an example ?

**Comment by adnanjpg** [comment] 2021-11-16 08:49
Sure, here is an example:

```
return Padding(
  padding: const EdgeInsets.all(16),
  child: Row(
    mainAxisAlignment: MainAxisAlignment.spaceBetween,
    children: [
      ElevatedButton(
        onPressed: () {},
        child: const Text('previous'),
      ),
      const Text('1/3'),
      ElevatedButton(
        onPressed: () {},
        child: const Text('next'),
      ),
    ],
  ),
);
```
if the background color is not specified, then this problem will appear

**Comment by darshankawar** [comment] 2021-11-17 06:18
Thanks for the details. Although I am able to replicate it and see the same behavior, but I am not sure if this is a bug. Keeping it open for further insights from the team.

/cc @HansMuller

**Comment by TahaTesser** [comment] 2021-12-22 09:41
Hi  @adnanjpg 
This is a known issue, it seems to be fixed by adding `Material` to ListView. https://github.com/flutter/flutter/issues/86584#issuecomment-916407888



<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Material(
        child: ListView.builder(
          itemCount: 20,
          itemBuilder: (BuildContext context, int index) {
            return InkWell(
              onTap: () {},
              child: Container(
                padding: const EdgeInsets.all(50),
                child: Text('Item $index'),
              ),
            );
          },
        ),
      ),
      bottomNavigationBar: Container(
        // color: Colors.blue,
        padding: const EdgeInsets.all(30),
        child: const Text('a'),
      ),
    );
  }
}
``` 
	
</details>

**Closed by TahaTesser** 2021-12-22 09:41 UTC
Labels: framework, f: material design, f: gestures, has reproducible steps, found in release: 2.5
