### ISSUE TITLE
Flutter Web: Automatic translation of the website from the browser

### ISSUE THREAD

**Issue by Nico1911** [flutter/flutter#144637] opened 2024-03-05 20:10 UTC
### Steps to reproduce

Deploy the initial flutter website and try to find the native icon for translation in your browser, e.g. safari.

### Expected results

I would like to enable visitors to my flutter website to translate the language of my website using the Brwoser internal translation function. Unfortunately, this does not work when I create a new flutter web project.

In Safari, a small translation icon is displayed in the search bar on the right-hand side of every website I visit, but not on a newly created default Flutter website.

In Chrome, there is the option to select text and translate it, but when I click on the "Translate entire page" button, nothing happens.

This can easily be reproduced by creating a new flutter web project.

It would be great if someone could tell me what I need to do to make this function work on my website. Thank you very much!

### Actual results

The translation icon Doesn't show up.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-03-06 07:57
Translation is not yet supported in flutter web. Closing this is as a duplicate of https://github.com/flutter/flutter/issues/131984

**Closed by danagbemava-nc** 2024-03-06 07:57 UTC
Labels: in triage
