### ISSUE TITLE
Errors and warnings in android studio code analysis of the initial hello world app

### ISSUE THREAD

**Issue by noamraph** [flutter/flutter#71825] opened 2020-12-07 06:13 UTC
## Steps to Reproduce

Open android studio.
File -> New -> New Flutter Project.
Flutter application.
Flutter SDK path: /home/noam/snap/flutter/common/flutter
package name: com.example.testapp.
Include Kotlin and Swift.
VCS -> Import into version control -> Create git repository.
VCS -> commit.
Click the topmost checkbox, to select all 62 unversioned files.
Leave "code analysis" checked (the default).

Code analysis fails, with these errors and warnings:

```
/tmp/test_app/android/app/src/main/AndroidManifest.xml
Warning:(1, 2) Should set `android:versionCode` to specify the application version
Warning:(1, 2) Should set `android:versionName` to specify the application version
Error:(9, 23) Class referenced in the manifest, `io.flutter.app.FlutterApplication`, was not found in the project or the libraries
Error:(9, 34) Unresolved package 'app'
Error:(9, 38) Unresolved class 'FlutterApplication'
Error:(11, 23) Cannot resolve symbol '@mipmap/ic_launcher'
Error:(13, 27) `MainActivity` must extend android.app.Activity
Error:(15, 28) Cannot resolve symbol '@style/LaunchTheme'
Warning:(17, 13) Attribute `hardwareAccelerated` is only used in API level 11 and higher (current min is 1)
Warning:(18, 13) Attribute `windowSoftInputMode` is only used in API level 3 and higher (current min is 1)
Error:(25, 33) Cannot resolve symbol '@style/NormalTheme'
Error:(34, 33) Cannot resolve symbol '@drawable/launch_background'
/tmp/test_app/android/app/src/main/kotlin/com/example/test_app/MainActivity.kt
Error:(3, 19) Unresolved reference: embedding
Error:(5, 21) Unresolved reference: FlutterActivity
/tmp/test_app/android/build.gradle
/tmp/test_app/android/app/build.gradle
Error:(11, 15) Cannot resolve symbol 'GradleException'
Warning:(43, 26) Not targeting the latest versions of Android; compatibility modes apply. Consider testing and updating this version. Consult the android.os.Build.VERSION_CODES javadoc for details.
/tmp/test_app/android/app/src/main/res/values/styles.xml
Error:(7, 47) Cannot resolve symbol '@drawable/launch_background'
```

## Logs

Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-53-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin, Dart, io.flutter
Current Desktop: XFCE

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/noam/snap/flutter/common/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/noam/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /home/noam/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/noam/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
Note that the flutter and dart plugins are installed in android studio. This seems like a separate bug.

**Comment by Plegizplegiz** [comment] 2020-12-07 08:06
ma 7.12.2020 klo 8.15 Noam Yorav-Raphael <notifications@github.com>
kirjoitti:

**Comment by pedromassangocode** [comment] 2020-12-07 11:00
Hi @noamraph 
Please provide clear steps to reproduce the issue. Above you said to create a new project and import at the same time and it confuses me.
Thank you

**Comment by noamraph** [comment] 2020-12-07 21:07
Hi @pedromassangocode , it's "Import into version control -> create git repository". It's just initializes a git repository in the directory. You can replace this line with "git init ." in the terminal.

All that this does in to give a list of files to analyze. I just tried something else, which produces the same results:

Open android studio.
File -> New -> New Flutter Project.
Flutter application.
Flutter SDK path: /home/noam/snap/flutter/common/flutter
package name: com.example.testapp.
Include Kotlin and Swift.

Open the file android/app/src/main/AndroidManifest.xml

You see there are 8 errors and 4 warnings. They are listed above, namely:

```
Warning:(1, 2) Should set `android:versionCode` to specify the application version
Warning:(1, 2) Should set `android:versionName` to specify the application version
Error:(9, 23) Class referenced in the manifest, `io.flutter.app.FlutterApplication`, was not found in the project or the libraries
Error:(9, 34) Unresolved package 'app'
Error:(9, 38) Unresolved class 'FlutterApplication'
Error:(11, 23) Cannot resolve symbol '@mipmap/ic_launcher'
Error:(13, 27) `MainActivity` must extend android.app.Activity
Error:(15, 28) Cannot resolve symbol '@style/LaunchTheme'
Warning:(17, 13) Attribute `hardwareAccelerated` is only used in API level 11 and higher (current min is 1)
Warning:(18, 13) Attribute `windowSoftInputMode` is only used in API level 3 and higher (current min is 1)
Error:(25, 33) Cannot resolve symbol '@style/NormalTheme'
Error:(34, 33) Cannot resolve symbol '@drawable/launch_background'
```

In the above listing, you can see that there are errors in those files:

```
/tmp/test_app/android/app/src/main/AndroidManifest.xml
/tmp/test_app/android/app/src/main/kotlin/com/example/test_app/MainActivity.kt
/tmp/test_app/android/app/build.gradle
/tmp/test_app/android/app/src/main/res/values/styles.xml
```

**Comment by pedromassangocode** [comment] 2020-12-08 07:20
That is because the directory you opened is not a valid Android app so the analyzer will not work. Make sure you open the android/ folder as an Android project to get the analyzer working.

Closing as this is not a valid issue.

**Closed by pedromassangocode** 2020-12-08 07:20 UTC
Labels: in triage

**Comment by Eldot** [comment] 2020-12-22 12:06
Hi @pedromassangocode, I have this same problem, but I don't totally understand your answer. I can see this case is closed, so maybe replies to Closed cases are not allowed. For now, I have just unchecked Settings > Version Control > Commit > Before Commit > Perform code analysis, and now I can Commit the code no problem. Can you explain your answer please?

**Comment by pedromassangocode** [comment] 2020-12-22 13:00
Hi @Eldot 
When you want to modify an Android file and you want some autocomplete and analyzer support, you should open the <your-flutter-project>/android directory on Android Studio. Otherwise you will get a lot of red lines as error/warnings because the project you opened is not a valid Android project.
