### ISSUE TITLE
iOS with enabled Impeller App Hanging 

### ISSUE THREAD

**Issue by r-i-c-o** [flutter/flutter#131462] opened 2023-07-28 07:15 UTC
## Details
We released our app with Flutter 3.10.3 version and enabled Impeller. Since then Sentry began to report "App hanging for at least 2000 ms." problems with iOS devices. Almost always it happens after sending ```action: UIKeyboardDidShowNotification``` by the system, so we assume that this can be related with TextField. Before Flutter 3.10 we didn't receive such warnings, also we don't receive them on Android devices. Unfortunately, we could not reproduce it on our test devices. Below I attached some of the stacktraces.

**Target Platform:** iOS
**Target OS version/browser:** iOS 14 - iOS 17
**Devices:** iPhone X and later

## Logs

<details>
<summary>Logs</summary>

```
  libsystem_kernel    0x1f97f7c00  semaphore_wait_trap
  libdispatch         0x1c1d83444  _dispatch_sema4_wait
  libdispatch         0x1c1d83af8  _dispatch_semaphore_wait_slow
  UIKitCore           0x1bd5ea90c  _coerceItemToClass
  UIKitCore           0x1bd5eaa1c  -[_UIConcretePasteboard string]
  Flutter             0x10579e618  <redacted>
  Flutter             0x10579dcbc  <redacted>
  Flutter             0x105d5df98  <redacted>
  Flutter             0x1057bf36c  <redacted>
  libdispatch         0x1c1d8131c  _dispatch_call_block_and_release
  libdispatch         0x1c1d82ea8  _dispatch_client_callout
  libdispatch         0x1c1d916a0  _dispatch_main_queue_drain
  libdispatch         0x1c1d912f0  _dispatch_main_queue_callback_4CF
  CoreFoundation      0x1ba94bc24  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  CoreFoundation      0x1ba92d55c  __CFRunLoopRun
  CoreFoundation      0x1ba9323e8  CFRunLoopRunSpecific
  GraphicsServices    0x1f5dcf358  GSEventRunModal
  UIKitCore           0x1bccbf6e4  -[UIApplication _run]
  UIKitCore           0x1bccbf348  UIApplicationMain
  Runner              0x100bc7cb4  <redacted>
```

```
  libsystem_kernel    0x1db3b8678  write
  Foundation          0x196731868  _NSWriteToFileDescriptorWithProgress
  Foundation          0x19674c4ac  ___NSWriteDataToFileWithExtendedAttributes_block_invoke
  Foundation          0x1966f7870  -[NSData(NSData) enumerateByteRangesUsingBlock:]
  Foundation          0x196715da8  _NSWriteDataToFileWithExtendedAttributes
  Sentry              0x1074a7cf4  0x1074a7c54
  Sentry              0x1074a76d4  0x1074a7574
  Sentry              0x1074d2f6c  0x1074d2ec0
  CoreFoundation      0x19c42e58c  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
  CoreFoundation      0x19c4d2824  ___CFXRegistrationPost_block_invoke
  CoreFoundation      0x19c4b58b4  _CFXRegistrationPost
  CoreFoundation      0x19c442af8  _CFXNotificationPost
  Foundation          0x196705d14  -[NSNotificationCenter postNotificationName:object:userInfo:]
  UIKitCore           0x19e6f38e4  -[UIApplication _deactivateForReason:notify:]
  UIKitCore           0x19e6f1bd4  -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
  UIKitCore           0x19e6f1a80  -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
  UIKitCore           0x19e6f1630  -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
  UIKitCore           0x19e6f14fc  __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
  UIKitCore           0x19eddea64  +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:]
  UIKitCore           0x19ee7d070  _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
  UIKitCore           0x19e59ec6c  -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
  UIKitCore           0x19ea101a8  __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.223
  UIKitCore           0x19e66fc5c  -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
  UIKitCore           0x19e66facc  -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
  UIKitCore           0x19e66f90c  -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
  FrontBoardServices  0x1b247cac4  -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:]
  FrontBoardServices  0x1b247c900  __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2
  FrontBoardServices  0x1b248011c  -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
  FrontBoardServices  0x1b2480038  __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke
  libdispatch         0x1a38c7ea8  _dispatch_client_callout
  libdispatch         0x1a38cb918  _dispatch_block_invoke_direct
  FrontBoardServices  0x1b248a248  __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
  FrontBoardServices  0x1b2489de4  -[FBSSerialQueue _targetQueue_performNextIfPossible]
  FrontBoardServices  0x1b248c690  -[FBSSerialQueue _performNextFromRunLoopSource]
  CoreFoundation      0x19c4ca124  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
  CoreFoundation      0x19c4d67b0  __CFRunLoopDoSource0
  CoreFoundation      0x19c45b644  __CFRunLoopDoSources0
  CoreFoundation      0x19c4710d0  __CFRunLoopRun
  CoreFoundation      0x19c4763e8  CFRunLoopRunSpecific
  GraphicsServices    0x1d798c358  GSEventRunModal
  UIKitCore           0x19e802f54  -[UIApplication _run]
  UIKitCore           0x19e802bb8  UIApplicationMain
  Runner              0x1041a7cb4  <redacted>
```

```
```

</details>

**Comment by huycozy** [comment] 2023-07-28 10:07
Hi @r-i-c-o 
I notice there are some `<redacted>` frames from your stack trace, it looks similar to https://github.com/flutter/flutter/issues/130478. Per https://github.com/flutter/flutter/issues/130478#issuecomment-1640472853, it doesn't seem to know the next action for this. Do you also use `lottie` package?

Also, can you please follow [this instruction](https://github.com/getsentry/sentry-cocoa/issues/280#issuecomment-696860201) to see if there is any progress?

**Comment by r-i-c-o** [comment] 2023-07-28 10:24
thanks for reply, @huycozy. We do not use `lottie` package. As for `<redacted>`, we haven't upload debugging symbols yet. I will leave the same stacktraces without `<redacted>` fields a bit later. Please do not close the issue for now.

**Comment by MobIS1User** [comment] 2023-08-11 21:55
Hello, we are seeing a similar issue in our sentry logs. e.g.: 
https://hunter-industries-mz.sentry.io/share/issue/f125ba134e8841ef863aad591dd327b4/

Since the newer version of Flutter introduced breaking changes in our codebase, we are currently on Flutter 3.7.12. 

Following the advice in last comment above, we used "sentry_dart_plugin: ^1.0.0" in our pubspec today to upload debug symbols to see if early next week the "<redacted>" goes away in any new sentry reports of this issue. We plan to report back here with our findings. Also, we don't recognize this "lottie" package either.

**Comment by Liloupar** [comment] 2023-08-17 13:50
@huycozy 
we are seeing a similar issue in our sentry issue, with dSYM log
```
 libsystem_kernel    0x1f52c05c8  __psynch_rw_wrlock
  libsystem_pthread   0x217a6e434  <redacted>
  libsystem_pthread   0x217a68cd4  <redacted>
  Flutter             0x104acbcac  fml::UniqueLock::UniqueLock (shared_mutex.h:39)
  Flutter             0x104acbcac  fml::UniqueLock::UniqueLock (shared_mutex.h:38)
  Flutter             0x104acbcac  fml::SyncSwitch::SetSwitch (sync_switch.cc:35)
  Flutter             0x104acbcac  flutter::Shell::SetGpuAvailability (shell.cc:2114)
  Flutter             0x1046f44c8  -[FlutterEngine setIsGpuDisabled:] (FlutterEngine.mm:1316)
  Flutter             0x1046f4478  -[FlutterEngine applicationDidEnterBackground:] (FlutterEngine.mm:1306)
  CoreFoundation      0x1af81bd14  <redacted>
  CoreFoundation      0x1af81b6dc  <redacted>
  CoreFoundation      0x1af81b624  <redacted>
  CoreFoundation      0x1af81ab74  _CFXNotificationPost
  Foundation          0x1ae7b6fd4  <redacted>
  UIKitCore           0x1b27fd254  <redacted>
  UIKitCore           0x1b1cc9544  <redacted>
  UIKitCore           0x1b27fd034  <redacted>
  UIKitCore           0x1b1b95e64  <redacted>
  UIKitCore           0x1b1b95b9c  _UIScenePerformActionsWithLifecycleActionMask
  UIKitCore           0x1b1c1d078  <redacted>
  UIKitCore           0x1b1b4200c  <redacted>
  UIKitCore           0x1b1b40a84  <redacted>
  UIKitCore           0x1b1b403ec  <redacted>
  UIKitCore           0x1b1b402bc  <redacted>
  UIKitCore           0x1b1b401c4  <redacted>
  UIKitCore           0x1b1b3fa4c  _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
  UIKitCore           0x1b1b3f6fc  <redacted>
  UIKitCore           0x1b1b3ec7c  <redacted>
  UIKitCore           0x1b1b3e5e0  <redacted>
  UIKitCore           0x1b1b3e450  <redacted>
  UIKitCore           0x1b1b3e290  <redacted>
  FrontBoardServices  0x1c78079bc  <redacted>
  FrontBoardServices  0x1c780772c  <redacted>
  FrontBoardServices  0x1c78075c8  <redacted>
  FrontBoardServices  0x1c78074e4  <redacted>
  libdispatch         0x1b76fa300  <redacted>
  libdispatch         0x1b76fdd48  <redacted>
  FrontBoardServices  0x1c7803a0c  <redacted>
  FrontBoardServices  0x1c780398c  <redacted>
  FrontBoardServices  0x1c7803864  <redacted>
  CoreFoundation      0x1af823b6c  <redacted>
  CoreFoundation      0x1af822de8  <redacted>
  CoreFoundation      0x1af82159c  <redacted>
  CoreFoundation      0x1af8202d8  <redacted>
  CoreFoundation      0x1af81feb8  CFRunLoopRunSpecific
  GraphicsServices    0x1f12bc5ec  GSEventRunModal
  UIKitCore           0x1b1c366b4  <redacted>
  UIKitCore           0x1b1c35cf0  UIApplicationMain
  Runner              0x10288d3bc  <redacted>
```

**Comment by huycozy** [comment] 2023-08-18 10:18
Keeping the issue open for further info.

**Comment by chinmaygarde** [comment] 2023-08-21 21:12
This is [fixed and going to be cherry picked](https://github.com/flutter/flutter/issues/132982). This is a duplicate of https://github.com/flutter/flutter/issues/132666.

**Closed by chinmaygarde** 2023-08-21 21:12 UTC
Labels: c: crash, platform-ios, engine, a: production, needs repro info, e: impeller, team-engine
