### ISSUE TITLE
Something wrong with Ink widget when dialog is show

### ISSUE THREAD

**Issue by voiddog** [flutter/flutter#26217] opened 2019-01-08 06:18 UTC
![](https://github.com/voiddog/flutter_issues_demo/blob/master/media/ink_issues.gif?raw=true)
As you can see the problem in picture, the Ink widget perfrom strange when dialog is show.

I think it's a bug.

You can use this [code](https://github.com/voiddog/flutter_issues_demo/blob/master/lib/demo/ink_issues.dart) to reproduce the problem.

my flutter doctor is:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.2)
[✓] VS Code (version 1.30.1)
[✓] Connected device (2 available)
```

**Comment by voiddog** [comment] 2019-01-08 06:30
Is RaisedButton widget not using Ink widget to achieve watermark effects?

**Comment by kangwang1988** [comment] 2019-01-08 06:40
@voiddog 
You're right. It uses ink widgets finally.
@InMatrix 
Any idea towards this material design issue?

**Comment by zoechi** [comment] 2019-01-08 06:52
Similar to #25534?

**Comment by voiddog** [comment] 2019-01-08 06:59
I think it should be the same.

**Comment by kangwang1988** [comment] 2019-01-08 07:00
Duplicate of: #25534

**Closed** 2019-01-08 07:00 UTC
Labels: f: material design, framework
