### ISSUE TITLE
ReorderableListView should also provide grab handles on Desktop and allow short-click mouse d'n'd

### ISSUE THREAD

**Issue by csells** [flutter/flutter#63709] opened 2020-08-13 21:37 UTC
Several widgets in Flutter support longpress to initiate a drag 'n' drop action, e.g. ReorderableListView. That's a natural gesture on mobile form-factors but not on desktop web or native desktop. The [material guidelines call for grab handles](https://material.io/components/lists#behavior) to indicate drag 'n' drop. Flutter should add grab handles into the widgets that support drag 'n' drop and not require longpress for mouse-initiated drag 'n' drop.

[Here's a DartPad sample](https://dartpad.dev/0fbfd605659c9d57bcf02843b6bc366c) that shows one work-around for adding short-click and drag by creating a clone of ReorderableListView and changing a single line of code (LongPressDraggable => Draggable).

![flutter-long-press-vs-short-press](https://user-images.githubusercontent.com/2568253/90189399-fafaba00-dd71-11ea-8c00-a48c8761f98a.gif)

**Comment by csells** [comment] 2020-08-13 21:37
cc @goderbauer

**Comment by goderbauer** [comment] 2020-08-14 17:48
Let's make this bug specifically about the ReorderableListView since even on desktop not everything that's draggable has a drag handle (example: I can drag any selected text on Mac around and it doesn't have the handles).

**Comment by csells** [comment] 2020-08-14 17:52
Anything that has longpress in Flutter today should be considered a candidate for grab handles and shortpress click + drag, not just ReorderableListView.

**Comment by Ran73Cohen** [comment] 2020-08-15 17:16
duplicate of [#36314](https://github.com/flutter/flutter/issues/36314) I would suggest to close the other issue since this one is more general also I noticed this [comment](https://github.com/flutter/flutter/pull/52582#issuecomment-599644422) and it seems someone is working on it (at least in ReorderableListView)

Generally speaking I really think this class needs a rework with features that I have seen in many different issues (maybe combine them?).
[#25789](https://github.com/flutter/flutter/issues/25789) (.builder, .separator, shrink wrap, primary)
[#56003](https://github.com/flutter/flutter/issues/56033) Scroll Physics
[45799](https://github.com/flutter/flutter/issues/45799) Dragging Background Color

as well as a bug giving the wrong index with a workout around actually written inside the class (instead of fixing the widget)
also renaming scrollcontroller to controller to be more consistent.

**Comment by Ran73Cohen** [comment] 2020-09-08 17:52
@csells I mean ReorderableListView is quite an important widget that is missing a lot of things and doesn't even listen to material design guidelines or aligns with Listview current features.
would be nice if you consider my suggestion or respond in any way...

**Comment by csells** [comment] 2020-09-08 18:54
cc @HansMuller for the feedback on RLV as related to Material design.

**Comment by HansMuller** [comment] 2020-09-08 19:56
@Ran73Cohen - you are correct about ReorderableListView's many inadequacies. We're queuing up a project to remedy the situation now and hope to get your feedback about the TBD plan.

CC @darrenaustin

**Comment by Ran73Cohen** [comment] 2020-09-08 21:50
@HansMuller well as I stated before it seems someone is working on it but I dont see any PR, I would like to help with specific features to speed things up but there needs to be a skeleton class with some of the core fundamentals. (I guess yo are not going to let someone rewrite an entire widget).
I understand you do some work without publishing an issue but It would be nice to see an issue with a list of missing features so that I and others could pick and implement some.

**Comment by HansMuller** [comment] 2020-09-08 22:20
The first step will be to publish a plan that makes the requirements for an updated ReorderableListView clear. We appreciate your offer of help with the implementation!

**Comment by Ran73Cohen** [comment] 2020-09-09 13:58
@HansMuller When you say publish a plan you mean I can create an issue with the full list or features?
I am asking because many of the features required are already in separate smaller issues.

Lets say I publish a plan, Because this is a rework it contains many breaking changes and changes core fundamentals of the RLV. It sounds like something you wouldn't just let me implement, so before I start the implementation I need to understand how to go about it from this front.

**Comment by HansMuller** [comment] 2020-09-09 15:45
We'll publish a doc (and an issue) that covers what we think are the missing features, based on feedback from the Material Design team as well as the existing feature-request issues. I hope that you and other interested developers will review the plan. Once that's sorted out, we'll decide how to implement the changes. Evolving the RLV is possibility, even with breaking changes. Another option is to produce a new replacement widget.

**Comment by darrenaustin** [comment] 2020-09-18 01:20
Hey folks, we are ramping up a design to try to address this and other issues with `ReorderableListView`. We are tracking it with #66080 and in a [design doc](https://docs.google.com/document/d/1JzNtMQ-jnPnSHEBoi6IO0x2qMMylwhvRslEDcmqiwSs/edit#heading=h.pub7jnop54q0). Feedback welcome.

**Comment by cbracken** [comment] 2021-02-09 20:18
@darrenaustin is this complete, or is there still work to be done on this?

**Comment by cbracken** [comment] 2021-03-02 18:39
I have it on good authority that this has been fixed.

**Closed** 2021-03-02 18:39 UTC
Labels: P3, a: desktop, a: mouse, f: material design, f: scrolling, framework, passed first triage, proposal, severe: new feature
