### ISSUE TITLE
iOS Archived error: Frameworks/Flutter.framework/Flutter (x86_64)

### ISSUE THREAD

**Issue by hahahhaczzcz** [flutter/flutter#39864] opened 2019-09-05 01:21 UTC
the error log list:
```
{
            code = 0;
            description = "Failed to verify bitcode in App.framework/App:\nerror: Bundle only contains bitcode-marker /var/folders/q8/7k9gs5q50kgb248mbpr_p6h40000gn/T/IDEDistributionOptionThinning.~~~fXeVcx/Payload/Nongjuanfeng.app/Frameworks/App.framework/App (arm64)\n\n";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";
        },
                {
            code = 0;
            description = "Failed to verify bitcode in Flutter.framework/Flutter:\nerror: Cannot extract bundle from /var/folders/q8/7k9gs5q50kgb248mbpr_p6h40000gn/T/IDEDistributionOptionThinning.~~~fXeVcx/Payload/Nongjuanfeng.app/Frameworks/Flutter.framework/Flutter (x86_64)\n\n";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";
        }
    );
```

**Comment by hahahhaczzcz** [comment] 2019-09-05 02:34
Other error:
ld: warning: Could not find auto-linked framework 'Flutter'
Undefined symbols for architecture armv7:
  "_FlutterMethodNotImplemented", referenced from:
      -[CatcherPlugin handleMethodCall:result:] in CatcherPlugin.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in CatcherPlugin.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by BondarenkoStas** [comment] 2019-09-05 09:46
@hahahhaczzcz Can you provide steps to reproduce the issue? As well as output of your ```flutter doctor -v```

**Comment by hahahhaczzcz** [comment] 2019-09-06 07:31
<img width="705" alt="屏幕快照 2019-09-06 下午3 24 08" src="https://user-images.githubusercontent.com/22882188/64408901-6e07a500-d0ba-11e9-8173-422288ec830b.png">
I'm an iOS developer. When I added a new flutter module to my iOS project, everything was wroks according to the official operation, but after packaging, there was a signature error.
<img width="688" alt="屏幕快照 2019-09-06 下午3 30 28" src="https://user-images.githubusercontent.com/22882188/64409352-4f55de00-d0bb-11e9-9b32-dcaeb3993772.png">

[IDEDistribution.standard.log](https://github.com/flutter/flutter/files/3582716/IDEDistribution.standard.log)
[IDEDistribution.verbose.log](https://github.com/flutter/flutter/files/3582717/IDEDistribution.verbose.log)
[IDEITunesSoftwareService.log](https://github.com/flutter/flutter/files/3582718/IDEITunesSoftwareService.log)

**Comment by BondarenkoStas** [comment] 2019-09-06 09:40
I would advise you to open a question on StackOverflow as well, help there may come faster.

**Comment by jmagman** [comment] 2019-09-09 21:03
@dnfield

**Comment by dnfield** [comment] 2019-09-09 21:20
@hahahhaczzcz - in general, we don't advise using debug or profile builds of the framework for distribution in the store.  For this case specifically, only the release framework contains bitcode. You're likely seeing this error because you're trying to use a debug or profile build while still having bitcode enabled.

**Comment by dnfield** [comment] 2019-09-09 21:21
FWIW, we also don't support shipping x86_64 binaries to the store.

**Comment by sulaysumaria** [comment] 2019-09-21 04:03
Any workaround for this error?

**Comment by sulaysumaria** [comment] 2019-09-24 16:24
Solved for me... I am on `dev` channel btw...

**Comment by jmagman** [comment] 2019-10-04 19:59
I'm going to close this.  Please open a new issue if you are seeing this error after running `flutter build ios` then immediately archiving.

**Closed by jmagman** 2019-10-04 19:59 UTC
Labels: a: existing-apps, d: stackoverflow, t: xcode, tool, waiting for customer response, ⌺‬ platform-ios

**Comment by lawonga** [comment] 2019-12-23 20:49
Running into this issue with iOS add-to-app on 1.12. Did you figure anything out about this issue?

**Comment by jmagman** [comment] 2019-12-23 21:07
@lawonga This issue is closed, can you file a new issue and fill out the template with your reproduction steps and logs?  Please confirm you are trying to archive a Release version of your app, and that you are doing so from Runner.xcworkspace and NOT Runner.xcodeproj.
