### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by saeedbaloch** [flutter/flutter#90599] opened 2021-09-23 14:17 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-09-23 14:20
duplicate of https://github.com/flutter/flutter/issues/90598

**Closed by TahaTesser** 2021-09-23 14:20 UTC
