### ISSUE TITLE
[Feature request] ListView jumpToIndex

### ISSUE THREAD

**Issue by windrunner414** [flutter/flutter#48108] opened 2020-01-03 05:16 UTC
need a efficient way to scroll to a item.now we can only calculate this item's offset and jumpTo, but if the itemExtent not set, it's very slow.Sometimes the items don't have the same extent.
I have a list show many items and group by the first letter, if the item is the first item of this group, a group title widget will show above it and this widget does not have the same extent as other items.

**Comment by iapicca** [comment] 2020-01-03 08:52
Hi @windrunner414 
it is true that `jumpTo()` is expensive right now ([sample code](https://dartpad.dartlang.org/fb35ce721213caab141342c9c522a6a1))
see issue https://github.com/flutter/flutter/issues/45751,
but it `exist`, I'm not sure this is a feature request;
to jump at a specific point of a list you can always use `<your list>.indexOf(<your element>)`
to find out at what index to jump.

does this answer your question?
thank you

**Comment by windrunner414** [comment] 2020-01-03 14:47
@iapicca Thanks, but I think u misunderstood
I mean I need jump to a known index of listview, not to get the index of a element.for example, my listview has 100 items and I need scroll to the 50th item, now I need calculate this item's position in listview and call 'controller.jumpTo(offset)', but is very slow.
I need a efficient way to do it

**Comment by windrunner414** [comment] 2020-01-03 14:49
jumpTo will layout many times to know what item should be display, too slow, it may cause UI frozen for a few seconds.I don't find a way to solve it

**Comment by HansMuller** [comment] 2020-01-03 17:08
See https://github.com/flutter/flutter/issues/12319#issuecomment-569296423

**Comment by goderbauer** [comment] 2020-01-06 21:21
Closing as a duplicate of https://github.com/flutter/flutter/issues/12319.

**Closed by goderbauer** 2020-01-06 21:21 UTC
Labels: f: scrolling, framework
