### ISSUE TITLE
Filter deprecated enum values

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#75621] opened 2021-02-08 10:59 UTC
Let's assume we have an `enum`.
```dart
enum OldEnum {
  none, 
  itemOneFirst
  itemOneSecond,
  itemTwoFirst,
  itemTwoSecond,
  itemThree,
}
```
So indexes are `0,1,2,3,4,5`.
Then they decided to combine items `itemOneX` and `itemsTwoX` to single ones.
```dart
enum NewEnum {
  none,
  itemOne,
  itemTwo,
  @deprecated
  itemOneFirst,
  @deprecated
  itemOneSecond,
  @deprecated
  itemTwoFirst,
  @deprecated
  itemTwoSecond,
  itemThree,
}
```
And indexes are only `0,1,2,5`. Moreover they are already in database.
The problem is when this `newEnum` is used as source for generation of `DropdownButtonFormField` as 
```dart
DropdownButtonFormField(
  items: NewEnum.values.map((item) => DropdownButtonItem(value: item. child: Text(describeEnum(item))));
)
```
it displays items which are should not be visible to user. It would be good to skip `@depreated` items from `values` collection or even create new annotation for this feature.
P.S. Of course, I can create an `extension` which will filter specific items but maybe this feature have a sense?

**Comment by pedromassangocode** [comment] 2021-02-08 12:21
Hi @bambinoua 
From what I can see, the issue is related to Dart rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-08 12:21 UTC
