### ISSUE TITLE
iOS 13 not able to show special string characters. 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#46136] opened 2019-12-05 01:52 UTC
## Steps to Reproduce

Run this code in iOS simulator/device running iOS 13. 

```
Text(
  "➠",
  style: TextStyle(fontSize: 70),
)
```
### Screenshot:

![image](https://user-images.githubusercontent.com/40364434/69901763-3c833a80-1386-11ea-8fc5-4704abfa1095.png)

You don't see special arrow sign used in the code which is **➠** instead it shows a rectangle. 

**iOS:13**
**Simulator/Real device**

### Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.12.13, on Mac OS X 10.15.1 19B88, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
```

**Awesome people who can help:**
@justinmc 
@GaryQian

**Comment by justinmc** [comment] 2019-12-05 21:14
I was able to reproduce this and can confirm it only happens on iOS 13 (not on the iOS 11 simulator or on a physical Android device when I tried).

**Comment by GaryQian** [comment] 2019-12-06 00:22
@dark-chocolate Is this a regression? Were you able to see these characters before? It could be that iOS13 simply does not include the fonts required to display these characters.

A rather clunky solution if missing glyphs was the cause could be to include a font that you know _does_ have the glyphs for these characters.

**Comment by dark-chocolate** [comment] 2019-12-07 07:03
@GaryQian Yes, i was able to see these characters before, I've app on the AppStore and was seeing this special character earlier. 

> It could be that iOS13 simply does not include the fonts required to display these characters.

I also think so. 

> A rather clunky solution if missing glyphs was the cause could be to include a font that you know does have the glyphs for these characters.

I tried some of the famous fonts and none of them showed the character, here are all the fonts I tried:
- Digital
- Rubik
- Serif
- Sans
- Roboto

**Comment by chinmaygarde** [comment] 2020-06-11 02:16
Engine Triage: This looks like a case of the font not specifying a glyph. Unclear what the engine action items are. Removing the label for now. Feel free to add it back if this is an error.

**Comment by gaaclarke** [comment] 2020-10-13 01:00
This appears to be a duplicate of https://github.com/flutter/flutter/issues/40184, @GaryQian can you confirm please?

**Closed by gaaclarke** 2020-10-13 01:00 UTC
Labels: a: typography, passed first triage, platform-ios, severe: regression
