### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for C:\Users\User\Desktop\Flutter v1.9\Flutter\bin\cache\dart-sdk\bin\pub.bat.

### ISSUE THREAD

**Issue by AsadAslamm** [flutter/flutter#46880] opened 2019-12-12 14:11 UTC
## Command
  ```
  flutter packages get
  ```

  ## Steps to Reproduce
  1. ...
  2. ...
  3. ...

  ## Logs
  ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\User\Desktop\Flutter v1.9\Flutter\bin\cache\dart-sdk\bin\pub.bat.
  ```
  #0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:413:27)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:431:35)
#4      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:259:33)
#5      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:176:15)
#6      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:93:17)
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:123:11)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:620:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#10     _rootRunUnary (dart:async/zone.dart:1134:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
  ```
  ```
  [✓] Flutter (Channel dev, v1.13.0, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.13.0 at C:\Users\User\Desktop\Flutter v1.9\Flutter
    • Framework revision 09126abb22 (9 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\User\Desktop\Android Studio
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\User\Desktop\Android Studio
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

  ```

  ## Flutter Application Metadata
  **Version**: 1.0.1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
cloud_firestorefirebase_authfirebase_auth_webfirebase_corefirebase_core_webfirebase_databasegoogle_maps_flutterlocation

**Comment by iapicca** [comment] 2019-12-12 14:13
HI @AsadAslamm 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-12 14:13 UTC

**Comment by AsadAslamm** [comment] 2019-12-12 14:52
Thankyou! @iapicca 
Since the update my every app, even the ones working fine before ,is showing this error.
