### ISSUE TITLE
[web] Pressing any key causes Uncaught Errors in platform_dispatcher.dart

### ISSUE THREAD

**Issue by kubaprzetakiewicz** [flutter/flutter#75423] opened 2021-02-04 15:58 UTC
## Description
Pressing any key on the keyboard causes Uncaught Errors in `platform_dispatcher.dart` to show up in the browser console, e.g.:

```
errors.dart:187 
Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart:923:10
zone != null
is not true
    at Object.throw_ [as throw] (errors.dart:236)
    at Object.assertFailed (errors.dart:29)
    at Object.invoke (platform_dispatcher.dart:923)
    at _engine.EnginePlatformDispatcher.__.invokeOnKeyData (platform_dispatcher.dart:197)
    at _engine.KeyboardBinding.__.[_onKeyData] (keyboard_binding.dart:128)
    at _engine.KeyboardConverter.new.handleEvent (keyboard_binding.dart:476)
    at keyboard_binding.dart:135
    at keyboard_binding.dart:109
```

## Steps to Reproduce

1. Create a new Flutter project.
2. Run it in Chrome via `flutter run -d chrome`
3. Open DevTools, focus the app, press any key on the keyboard and observe errors in the console

## Environment
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.128, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.128 at /Users/kubcio/.flutter
    • Framework revision 502ff3dbfe (2 days ago), 2021-02-02 05:41:03 -0500
    • Engine revision 7334085fc1
    • Dart version 2.12.0 (build 2.12.0-281.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/kubcio/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.0.1 20B50 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.146

• No issues found!
```

</details>

## Screenshot
<img width="1312" alt="Screenshot 2021-02-04 at 16 54 56" src="https://user-images.githubusercontent.com/18512701/106919596-96aa2900-670a-11eb-95b4-bba8dd82abe1.png">

**Comment by pedromassangocode** [comment] 2021-02-05 07:09
This seems to be a duplicate of https://github.com/flutter/flutter/issues/75076 that was recently fixed and the changes made it  on the latest Master channel yesterday https://github.com/flutter/flutter/issues/75076#issuecomment-772848288.

Please upgrade to the latest master channel to get the fix. if it still happening then write in the comments bellow.
Thank you

**Closed by pedromassangocode** 2021-02-05 07:09 UTC
