### ISSUE TITLE
iPadOS 15 showing unsolicited paste notification when typing in textfield

### ISSUE THREAD

**Issue by alexrabin** [flutter/flutter#97220] opened 2022-01-25 17:00 UTC
## Steps to Reproduce

1. Add textfield to state full widget 
2. Run app on iPadOS 15 
3. Click on textfield and every time you enter a character the iOS clipboard notification displays

**Expected results:**  
When typing in textfield the pasted notification should not show

**Actual results:** 
When typing in a textfield on iPadOS 15 the posted notification shows

This does not happen on iOS

**Comment by maheshmnj** [comment] 2022-01-26 09:10
Hi @alexrabin, Thanks for filing the issue. I verified on the latest master channel and I was not able to reproduce the issue.

https://user-images.githubusercontent.com/31410839/151134527-65551f47-f68e-40a0-ba6f-f00204f9a31c.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.504, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.504 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 94d9b02deb (5 hours ago), 2022-01-25 22:00:07 -0600
    • Engine revision 54e1f3f4bb
    • Dart version 2.17.0 (build 2.17.0-54.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 (mobile)     • 2FAADB73-D3EE-48FA-BF0D-B99CE312D366 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```
</details>

**Comment by alexrabin** [comment] 2022-01-26 13:02
You have to type in the textfield. Not just click on it

**Comment by maheshmnj** [comment] 2022-01-26 13:17
@alexrabin typing doesn't make any difference, can you share a video recording for a better visual to understand whats happening? 

https://user-images.githubusercontent.com/31410839/151169466-34ddab94-1ac1-4502-8e2a-44b4e70d222f.mov


> can you please check if this happens in other native apps.

Also, you could try running flutter textfield on web https://gallery.flutter.dev/#/demo/text-field

**Comment by alexrabin** [comment] 2022-01-26 13:35
This is on a physical device not simulator

https://user-images.githubusercontent.com/15949910/151172343-7a9fc196-7214-4e1c-8fa6-072ab1c3cfd8.MOVis

**Comment by alexrabin** [comment] 2022-01-26 14:04
> Also, you could try running flutter textfield on web https://gallery.flutter.dev/#/demo/text-field

The paste message isn't showing up on there. Only on an app running on a physical device

**Comment by alexrabin** [comment] 2022-01-26 14:14
This is my flutter doctor:

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/alexanderrabin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/alexanderrabin/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0
```

**Comment by alexrabin** [comment] 2022-01-26 14:15
> I verified on the latest master channel

I'm on stable branch, not master

**Comment by maheshmnj** [comment] 2022-01-27 07:10
Thanks for the info @alexrabin Could you please share the exact specs of the device on which this issue reproduces? Also would it be possible for you to verify if this happens on a simulator? I verified on iPad pro 9.7inch (ios 15.2) and iPad pro 11 inch 3rd generation (ios 15.2), This issue doesn't reproduce on the latest `stable 2.8.1`.

**Comment by alexrabin** [comment] 2022-01-27 13:08
I don't want to use master. I'm trying to build an app for production. This is a work around, not a fix for production

**Comment by maheshmnj** [comment] 2022-01-27 13:47
@alexrabin This was a known issue that was fixed in the master, you will have to either wait until the fix lands on the stable channel in the upcoming releases or cherry-pick the fix locally.
Heres a related PR: https://github.com/flutter/flutter/pull/87678

**Comment by alexrabin** [comment] 2022-01-27 13:57
Alrighty. Do you know how long it usually takes to get merged into stable?

**Comment by maheshmnj** [comment] 2022-01-28 06:11
Stable releases happen every quarter, branched out from beta channel. You can read more about it here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels.
I see that this issue is also fixed on beta, You may try switching to the beta channel too.

Closing as fixed in new versions.

**Closed by maheshmnj** 2022-01-28 06:11 UTC
Labels: in triage
