### ISSUE TITLE
Input formatter error on Android on Huawei Mate20 

### ISSUE THREAD

**Issue by jkurtw** [flutter/flutter#44773] opened 2019-11-12 23:44 UTC
The generic version of this was fixed in https://github.com/flutter/flutter/issues/41005. However, there is still an issue on Huawei Mate20.

See b/144323703.

I can only input 3 digits. When trying to input the 4th digit, I observed that the formatEditUpdate was called 3 times. In the last formatEditUpdate call, the 4th character was deleted.

We also noticed that the run console displays these complains when trying to put the 4th character:
W/IInputConnectionWrapper(28600): getTextAfterCursor on inactive InputConnection and
W/IInputConnectionWrapper(28600): getTextBeforeCursor on inactive InputConnection

Checked multiple devices, the problem does not happen in Xiaomi, Nexus 5, and Nexus 6. The only device that failes currently is Huawei Mate 20 Pro.

**Comment by mehmetf** [comment] 2019-11-14 01:25
Closed as duplicate of https://github.com/flutter/flutter/issues/44869

**Closed by mehmetf** 2019-11-14 01:25 UTC
Labels: customer: money (g3)
