### ISSUE TITLE
Some google material Icons are strangely loading other icons.

### ISSUE THREAD

**Issue by anggoran** [flutter/flutter#98195] opened 2022-02-10 14:03 UTC
![image](https://user-images.githubusercontent.com/66579441/153423123-8a3f367d-b0e1-4eb7-a2d2-1cfea162c141.png)
the bathing person is Icons.handshake

![image](https://user-images.githubusercontent.com/66579441/153423357-1cc7be99-3691-47d7-81ef-ef25d0097484.png)
the shopping bag is Icons.abc

**Comment by timsneath** [comment] 2022-02-11 02:49
Duplicate of https://github.com/flutter/flutter/issues/97767

**Closed by timsneath** 2022-02-11 02:49 UTC
