### ISSUE TITLE
[Web] Flutter mobile web scrolling motion leads to hang on a blank page

### ISSUE THREAD

**Issue by thesmartrenovation** [flutter/flutter#51232] opened 2020-02-21 22:27 UTC
I have problems with Flutter web in mobile environments. 

In the desktop browser with mobile view my applications work fine. But, on a real mobile phone the scrolling motion is hung on a blank page.

My homePage Code

```dart
Scrollbar(
        child: ListView(
          children: <Widget>[
            Container(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: <Widget>[
                  Text(
                    'TITTLE',
                    style: TextStyle(
                      fontSize: 40.0,
                      fontWeight: FontWeight.w900,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  logo(),
                  leyenda(),
                  playstore(),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      boton('Inicio', '/'),
                      boton('Privacy', '/privacy'),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      );
  }

```
Logo Model

```dart
Widget logo() {
    return Column(
      children: <Widget>[
        Container(
          width: 300.0,
          height: 300.0,
          child: Image(
            image: AssetImage('assets/logo.png'),
          ),
        )
      ],
    );
  }
```

PlayStore Model

```dart
Widget playstore() {
    return Padding(
        padding: const EdgeInsets.all(10.0),
        child: Container(
          child: MaterialButton(
            onPressed: () {
              url.launch(
                  'https://play.google.com/store/apps/details?id=com.smartdev.iptvcontrol');
            },
          ),
          width: 200.0,
          height: 80.0,
          decoration: BoxDecoration(
            image: DecorationImage(
                fit: BoxFit.fill, image: AssetImage('assets/playstore.png')),
          ),
        ).showCursorOnHover.moveUpOnHover);
  }

```
Leyenda Model

```dart
Widget leyenda() {
    return Padding(
      padding: const EdgeInsets.all(10.0),
      child: Text(
          'Some Text Here',
          style: TextStyle(
            fontSize: 40.0,
            fontWeight: FontWeight.w500,
          ),
          textAlign: TextAlign.center),
    );
  }
```

Flutter Doctor

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.15.4-pre.130, on Microsoft Windows [VersiÃ³n 10.0.18362.657], locale es-CO)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.42.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-02-24 13:26
Duplicate of [#46177](https://github.com/flutter/flutter/issues/46177)

**Comment by thesmartrenovation** [comment] 2020-02-24 14:02
My problem isn't lag, my problem is that when i scroll the page go blank.

**Comment by thesmartrenovation** [comment] 2020-02-24 14:18
Look by yourself, open this webpage in iOS browser in a real device (not simulator or desktop browser).

https://smartrenovation.co/iptvcontrol

**Comment by iapicca** [comment] 2020-02-25 07:30
Hi @thesmartrenovation 
I'm not sure of the need of need
for the combination of widgets 

> scrollbar - listview - container - column - (etc..)

regardless, I tried to simplify your the code for reproducibility 
as posted below
and I'm not experiencing the issue you are describing;

could you please provide  your `flutter run -d chrome --verbose`?
thank you

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
    body: Scrollbar(
      child: ListView(
        children: <Widget>[
          Container(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                for (int i = 0; i < 100; ++i) const Padding(
                  padding: EdgeInsets.only(bottom: 10),
                  child: const Center(
                    child: const FlutterLogo(size: 80)
                ),),
              ],
          ),),
        ],
  ),),);
}
```

**Comment by TahaTesser** [comment] 2020-03-20 08:33
Hi @thesmartrenovation 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-03-20 08:33 UTC
Labels: in triage, waiting for customer response
