### ISSUE TITLE
TextInputType.numberWithOptions briefly displays the keyboard with text

### ISSUE THREAD

**Issue by adonisRodxander** [flutter/flutter#155455] opened 2024-09-20 14:41 UTC
### Steps to reproduce

1. Open the application
2. Switch repeatedly between textfields.

### Expected results

The keypad must be displayed at all times.

### Actual results

The normal keyboard appears quickly, with text, causing a strange behavior. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextFormField(keyboardType: const TextInputType.numberWithOptions(decimal: true),),
            const SizedBox(height: 32,),
            TextFormField(keyboardType: const TextInputType.numberWithOptions(decimal: true),),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/f253b733-ca9c-41b2-90ca-9023da2764ff

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on Debian GNU/Linux 12 (bookworm) 6.1.0-25-amd64, locale en_US.UTF-8)
    • Flutter version 3.24.1 on channel stable at /home/user/fvm/versions/3.24.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (4 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /media//
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/user/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/user/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.96.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 12 (bookworm) 6.1.0-25-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2024-09-23 04:24
Hi @adonisRodxander 
This is similar to https://github.com/flutter/flutter/issues/154913 which is indicated as fixed on the latest Flutter beta and master channels. So please switch to one of these channel and retry.

```
flutter channel beta/master
flutter upgrade
```

Closing this as a duplicate of that one.

**Closed by huycozy** 2024-09-23 04:24 UTC
Labels: in triage
