### ISSUE TITLE
CustomPaint is using too much CPU for simple tests

### ISSUE THREAD

**Issue by kakyoism** [flutter/flutter#61721] opened 2020-07-17 13:02 UTC
## Purpose of the test

I'm testing how flutter performs as a realtime data visualizer.

See attached `main.dart`. This is little test program draws randomly generated time-series in realtime in the classic spectrogram style, i.e., bins of floats are mapped to a color collection and drawn on a scrolling 2D view, using `CustomPaint`. It's quite straightforward.

### Test Code

[main.dart.zip](https://github.com/flutter/flutter/files/4937822/main.dart.zip)

The data frame is generated using a timer at a rate close to 60fps. The `CustomPaint` class scrolls the existing "picture" and paints new data at its tail. 

## Observation and Attempts

I noticed that the baseline CPU load observed on iPhone6 from Xcode (after `flutter run --release`) is around 90-100%.

I've tried some optimization ideas

- caching all the computed colors, only computing the newly generated data (around 300 floats as input data per frame at 60 fps)
- using a lookup table storing floats-to-color mapping info and mapping incoming floats quickly to colors, so that the mapping is free from searching

But unfortunately they don't seem to fix the bottleneck, which seems to be in the painter rendering.

## Possible bottlenecks

See in the attached code, I draw data frame of 300+ point bins vertically every frame, and try to interpolate between the data points. [The API I'm using is ](https://api.flutter.dev/flutter/dart-ui/Gradient/Gradient.linear.html).

```dart
ui.Gradient.linear(from, to, colors, colorStops);
```

So each data frame corresponds to a narrow rect this API tries to draw, and each data point represents a `colorStop`. I realize that this means creating hundreds of color objects every frame, e.g., around 600 by 300 points for iPhone6. I wonder if this is the best way for what I want with flutter. 

## Another baseline test

I've also tested just paint the entire screen as a rect with a set of single colors every frame, and found the performance to be about 30-40% on the same iPhone, still a bit shocking to me.

### bitmap

I thought about creating a bitmap from the data and use flutter's image painter to render, but that seems to require extra encoding/decoding step and [the need to add bitmap header](https://github.com/renancaraujo/bitmap). I have no idea about its realtime performance.

### vectorization

Another idea is to use some vector library to vectorize things, but `ui.Gradient.linear` seems a brickwall that blocks this route.

### FFI

I'm really hesitant to go this route because I came to flutter for its advertised 60fps and native-compiled performance, unless I misunderstood the whole idea. The backend of my intended app is already written in C++ and works with frontend through FFI, so I'd really love to solve as many frontend problems with flutter as possible.

## Question

Please advice where I've done wrong in the code, or other options.

**Target Platform:** iOS, Android
**Target OS version/browser:** iOS 8+, Android 8+
**Devices:** 64bit devices

## Logs

```
```

```sh
$ flutter doctor -v
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale en-CN)
    • Flutter version 1.20.0-7.1.pre at /Applications/flutter
    • Framework revision 7736f3bc90 (6 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Applications/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Applications/Android/sdk
    • ANDROID_SDK_ROOT = /Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (2 available)
    • ONEPLUS A6000 (mobile)   •<myudid>                                 • android-arm64 • Android 10 (API 29)
    • MyiPhone (mobile)                •<myudid2>                               • ios           • iOS 13.5.1

• No issues found!
```

**Comment by kakyoism** [comment] 2020-07-19 08:46
[With some further digging on StackOverflow](https://stackoverflow.com/questions/62954833/flutter-custompaint-is-using-too-much-cpu-for-simple-tests), I removed the setState call and used ValueNotifier correctly, but the bottleneck still seems to be in the rendering itself.

**Comment by TahaTesser** [comment] 2020-07-20 12:44
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (6 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
!
```

</details>

**Comment by zanderso** [comment] 2020-07-24 18:13
Profiling your app with the Observatory or Dart DevTools is a good starting point. Eyeballing your app really quickly, if drawing is really the slow step, then you might try drawing rectangles instead by drawing a group of triangle pairs with https://api.flutter.dev/flutter/dart-ui/Canvas/drawVertices.html, reusing the Float32List buffer on each iteration. The downside is that the API is not as well documented as it could be, but it is essentially directly a call to https://api.skia.org/classSkCanvas.html#ae971eebc0c442a0310b830a7711b8798

**Comment by flar** [comment] 2020-07-27 21:56
The overhead of ui.Gradient is very high for single-use gradients. It looks like you recreate each bin's gradient every time you paint it even though it may be on the screen (scrolling) for a long time. So, you are creating a complex gradient which has a high construction and shader compile overhead and then using it once and then recreating it on the next frame (365 shader creations per frame).

The first step might be to only create the shader when the bin first appears and then reuse it on every frame where that bin is in view and only discard it when it scrolls off the screen. In the inner loop you'd then have `_paint.shader = ts.shaders[b];`. Note that a linear gradient does not vary in the axis perpendicular to its defining points, so the use of `xAnchor.toDouble()` in computing the from/to points could be replaced by `0`s which means the gradient can be the same on every frame. If the canvas height might change you could substitute a 1 for its height and then use a vertical scale to stretch it to the appropriate true canvas height.

But with so many complex gradients and a shader being compiled for each you will still take a lot of memory and a lot of shader switching. Linear gradients are essentially just a linear interpolation from color A to color B and you sort of get that computation for free when you render images with LinearInterpolation. If you created an image with all of the indicated color pairs 10x10 colors == 100 pairs, then you could use canvas.drawRawAtlas() to render them efficiently with a list of precomputed rectangular slices of the image and precomputed transforms to apply to them. This technique would require more work on your part to compute and store the lists of "where in the image do you have the 2 colors I'm interpolating next to each other" rectangles and "where do I want their linear interpolated view to appear" transform values, but it would only really need one shader for the GPU which would be compiled and cached on the first frame.

**Comment by kakyoism** [comment] 2020-07-29 08:49
@flar Thanks for the detailed advice! With the help of a SO'er, I made some progress by `drawLine` with `Shader` on only a small number of new data and then wrap them into `ui.Picture`, and `ui.Image` for these bigger patches to move across the screen. Some findings:

- With the usage of `ui.Image` of the size of 64 drawn lines, the CPU% dropped from 100% percent to 40-50%. Still not ideal, but at least the phone will not heat up during the first 15min run time.
- Without the usage of `ui.Image`, only `ui.Picture`, there is no significant improvement.

Your idea of using only precomputed-gradient lookup table is intriguing. I'll try it next.

**Comment by chinmay2505** [comment] 2021-02-23 18:38
Did anyone get the spectrogram working properly?

**Comment by flar** [comment] 2021-02-26 01:04
You can get better results with drawVertices - even more if you cache the Vertices object for each bin. One "gotcha" with caching the vertex lists - the vertex list has the x and y coordinates baked into them so you have to use translations to reposition them and either invalidate them on a resize, or use scaling to resize (scale the canvas by its size in the Y direction and use Y vertex coordinates in the range [0, 1]).

Here is an example of using drawVertices instead (without caching):
```
  void draw() {
    // draw each bin in cache
    for (var b=0; b<ts.bins.length; b++) {
      var xAnchor = _s_xAnchor+b;
//      var from = Offset(xAnchor.toDouble(), _canvasSize.height);
//      var to = Offset(xAnchor.toDouble(), 0);
//      _paint.shader = ui.Gradient.linear(
//        from,
//        to,
//        ts.colors[b],
//        ts.colorStops,
//      );
//      Rect rect =
//      Offset(xAnchor.toDouble(), 0) & Size(1, _canvasSize.height);
//      // display the trace
//      _canvas.drawRect(rect, _paint);

      Float32List positions = Float32List(ts.colorStops.length * 4);
      Int32List colors = Int32List(ts.colorStops.length * 2);
      for (int s = 0; s < ts.colorStops.length; s++) {
        double y = _canvasSize.height * (1.0 - ts.colorStops[s]);
        positions[s * 4] = xAnchor.toDouble();
        positions[s * 4 + 1] = y;
        positions[s * 4 + 2] = xAnchor.toDouble() + 1;
        positions[s * 4 + 3] = y;
        colors[s * 2] = colors[s * 2 + 1] = ts.colors[b][s].value;
      }
      ui.Vertices vertices = ui.Vertices.raw(VertexMode.triangleStrip, positions, colors: colors);
      _canvas.drawVertices(vertices, BlendMode.src, _paint);
    }
  }
```

**Comment by exaby73** [comment] 2023-01-25 14:20
@flar While I don't see any performance problems (using your code) getting about 12ms per frame after running the example for like a minute on profile mode, using xcode I see it using ~250% if CPU, which with some back of the napkin math on my iPhone 12 Pro Max with the A14 chip, it's using around 2-3 of the available 6 cores. I am not sure if this expected or above normal. Do you have any insights on this issue, and whether it's still an issue overall?

**Comment by flar** [comment] 2023-01-25 21:39
@exaby73 something I never debugged was the fact that when you look at the loop in paint() the number of draw calls, controlled by `ts.bins.length` keeps growing forever. Only the last "size.width" items should be rendered it would seem and that might keep the times consistent.

Note that the `ts` is asked to shrink, but I don't think it shrinks by enough - that is where I stopped debugging.

**Comment by flar** [comment] 2023-01-25 21:55
If the maintenance of "out of range bins" was fixed then the performance would probably remain consistent. Indeed, the following draw loop, which attempts to avoid drawing out-of-range stripes as much as it can, maintains consistent frame times for fairly long, though eventually the accumulation of memory associated with the bins would cause the app to bog down due to just unbounded memory growth. At least this patched loop prevents that bug from causing the rendering to render ever increasing numbers of "stripes that won't be visible". (Remove the `count` variable and the print statement for best performance, but that print will demonstrate what I'm talking about with the bins growing uncontrollably and the impact of the new loop code to prevent out-of-bounds rendering calls.)

```
  void draw() {
    // draw each bin in cache
    Float32List positions = Float32List(ts.colorStops.length * 4);
    Int32List colors = Int32List(ts.colorStops.length * 2);
    int count = 0;
    for (int x = 0; x < _canvasSize.width; x++) {
      int b = x - _s_xAnchor;
      if (b < 0) {
        continue;
      }
      if (b > ts.bins.length) {
        break;
      }
      count++;
//      var from = Offset(xAnchor.toDouble(), _canvasSize.height);
//      var to = Offset(xAnchor.toDouble(), 0);
//      _paint.shader = ui.Gradient.linear(
//        from,
//        to,
//        ts.colors[b],
//        ts.colorStops,
//      );
//      Rect rect =
//      Offset(xAnchor.toDouble(), 0) & Size(1, _canvasSize.height);
//      // display the trace
//      _canvas.drawRect(rect, _paint);

      for (int s = 0; s < ts.colorStops.length; s++) {
        double y = _canvasSize.height * (1.0 - ts.colorStops[s]);
        positions[s * 4] = x.toDouble();
        positions[s * 4 + 1] = y;
        positions[s * 4 + 2] = x.toDouble() + 1;
        positions[s * 4 + 3] = y;
        colors[s * 2] = colors[s * 2 + 1] = ts.colors[b][s].value;
      }
      ui.Vertices vertices = ui.Vertices.raw(VertexMode.triangleStrip, positions, colors: colors);
      _canvas.drawVertices(vertices, BlendMode.src, _paint);
    }
    print('drew $count out of ${ts.bins.length}');
  }
```

**Comment by exaby73** [comment] 2023-01-26 08:41
Hmmm... To me it looks like an optimization issue rather than a Flutter issue. Although, I must admit, I am not very familiar with the way Flutter does paint calls. The original issue is about CPU load, which I find to be expected with the amount of draw calls in this code example. If you agree @flar, we can close this issue

**Comment by flar** [comment] 2023-01-26 19:21
> Hmmm... To me it looks like an optimization issue rather than a Flutter issue. Although, I must admit, I am not very familiar with the way Flutter does paint calls. The original issue is about CPU load, which I find to be expected with the amount of draw calls in this code example. If you agree @flar, we can close this issue

I agree. Some of this was about using a rendering op that could achieve the desired effect with less work throughout, and some of it looks like the app needs some optimizations to avoid storing unnecessary data and executing rendering calls that won't be visible.

**Comment by exaby73** [comment] 2023-01-27 06:59
Thanks for the insight :) Since this is an optimization issue, I will close this issue. If anyone can still reproduce unusually high CPU loads for a `CustomPaint` that isn't doing enough work to justify that high load, please provide a code sample with the timeline traces and I can reopen the issue. Thank you

**Closed by exaby73** 2023-01-27 06:59 UTC
Labels: engine, severe: performance, dependency: dart, has reproducible steps, P4, found in release: 1.21
