### ISSUE TITLE
Stream are not properly closed (Canceled) by flutter on initial route

### ISSUE THREAD

**Issue by being-yash-t** [flutter/flutter#53997] opened 2020-04-04 15:23 UTC
Steams are not closed properly on the first route of the app

1. Create an app with a stream builder on the home route (On the first route created by the app) (I am using firebase collection.snapshots() for stream) .
2. Run the app with the stream builder and just press the back button.
3. The stream doesn't close / doesn't call .cancel() on the stream subscription and when the firebase data is updated it tries to call the dart code but it can't as the app is closed it throws an error

```
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/cloud_firestore. Response ID: 0
```

As no dart code is executed when app exits, This clearly means the stream is not properly closed, I use a hacky method & put a blank route before the homepage and then when the app starts this route is opened and it automatically opens the homeroute above it, and when the user exits the home route (press the back button, which automatically call Navigator.pop) I manually call SystemNavigator.pop() from the blank route, by this method the stream is closed as the dispose method is called, is there an alternate way to close my stream?

Example code (Just to get an idea):

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: StreamBuilder<List<SomeClass>>(
            stream: Firestore.instance.collection("Something").snapshots(),
            builder: (context, snapshot) {
                if (snapshot.data != null)
                    return ListView.builder(
                         itemCount: snapshot.data.count,
                         itemBuilder: (context, index) => ListTile(title: Text(snapshot.data[index]["name"]))
                    )
            }
        )
    );
  }
}

```

The class StreamBuilder a method to close the streams, which calls .cancel() on the StreamSubscription object and sets it to null, and it is as it should be, it works fine when the class above is just a Route opened by the Navigator, as when the user goes back to its parent Route, the _unsubscribe() is called inside the dispose() function of class _StreamBuilderBaseState, the stream is actually closed and cloud_firestore knows that the stream is closed and it stops getting further updates.

But if we use this class as runApp(MyApp) instead of calling Navigator.push(context, <ROUTE with MyApp returned by its builder>), the problems comes in here, as said here https://github.com/flutter/flutter/issues/28134
```
When the app is exited then no further Dart code is executed.
So this is working as intended.
```
the dispose method is not called for _StreamBuilderBaseState, as a result the _unsubscribe is not called and the stream is not closed, just the FlutterJNI is detached from the plugin, as a result the cloud_firestore still thinks that stream is open and whenever updates are send by the server to the cloud_firestore it tries to send it to dart but it fails as no dart code is executed by the app after app exits which leads to the this message by the cloud_firestore.
```
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/cloud_firestore. Response ID: 0
```

And just for the record I am on stable channel
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /home/zephyr/.Installs/Flutter
    • Framework revision f139b11009 (8 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/zephyr/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/zephyr/.Installs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/zephyr/.Installs/android-studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2020-04-06 07:23
Hi @being-yash-t 
I'm not sure if the issue you are describing is referred 
to the mentioned FlutterFire plugin or generic stream.

In the first case please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).

If you believe the issue is with Flutter itself
could you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a reproducible minimal code sample (w/o external plugins).
thank you

**Comment by being-yash-t** [comment] 2020-04-08 03:01
I have updated my issue. Please check it

**Comment by iapicca** [comment] 2020-04-08 07:56
Hi @being-yash-t 
in the sample code you are using `Firestore.instance.collection`
as [mentioned](https://github.com/flutter/flutter/issues/53997#issuecomment-609611649), if the issue you are experiencing is due to a `flutterfire` plugin please open an issue in the dedicated github;

does this sample code represent the issue you are encountering?

```dart
import 'dart:async';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  StreamController<int> _controller;

  @override
  void initState() { 
    super.initState();
    _controller = StreamController<int>();
  }

  @override
  void dispose() {
    _controller?.close(); // <== HERE !!!
    super.dispose();
  }

  @override
  Widget build(BuildContext context) =>  StreamBuilder<int>(
    stream: _controller.stream ,
    builder: (BuildContext context, AsyncSnapshot<int> snapshot){
    int _counter = snapshot.data ?? 0;
    return Scaffold(
      appBar: AppBar(
        title: const Text('stream counter'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:',),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _controller.sink.add(_counter+1),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );}
  );
}
```
Thank you

**Comment by being-yash-t** [comment] 2020-04-08 08:32
Yes, dispose method is not called because as said,
```
When the app is exited then no further Dart code is executed.
So this is working as intended.
```
If you try adding a print message in dispose method like so,
```
  @override
  void dispose() {
    _controller?.close(); // <== HERE !!!
    debugPrint("Closed");
    super.dispose();
  }
```
The "Closed" text is not printed, we just see
```
D/FlutterView(14943): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@c08d3c5
D/FlutterActivityAndFragmentDelegate(14943): Detaching FlutterEngine from the Activity that owns this Fragment.
D/FlutterEngine(14943): Destroying.
D/FlutterEnginePluginRegistry(14943): Destroying.
```
It is completely okay if the stream is not canceled in dart, as the whole object is just cleared from memory, but with external plugins it causes problems & it is not issue related to other plugins, the problem is dart code is not executed inside the dispose method, the dispose method is only called when the route is not the first route, if I add a route before this route, it works and the "Closed" text is printed

**Comment by iapicca** [comment] 2020-04-08 09:31
Hi again @being-yash-t 
the issue you are describing seems to be more related to embedding or dart:ffi than 
how streams are handled; again, if it is related to existing plugins the correct way
to address the issue is through the dedicated github,
to address the possible issue with flutter,
since the sample I provided doesn't appear to be representative of the case,
could you please provide a reproducible minimal code sample
that does not involve 3rd party plugins
Thank you

**Comment by being-yash-t** [comment] 2020-04-08 09:48
Hello, your code is perfect representative for the problem thats what I said, the dispose method is not called at all, thats clearly a flutter issue, I don't know about IOS but that is an issue on android, maybe if not you then try to contact someone who works closer to android in flutter team. If you guys prefer that the dispose method should NOT be called when user exits the app, then some kind of guideline should to provided to the plugin developers so they can have a work around. This issue is not about stream, it is about the framework not executing code inside dispose method when app exits, I doubt that even though this is a clear flutter issue I may not get any help, I will use my hacky method, just create a blank route before my home route and close it automatically when the user exits the home route, which means the dispose method of home route is called and all my streams are closed, and It will appear as there is no route/screen before that home route, hereby I close my issue

**Comment by being-yash-t** [comment] 2020-04-08 09:55
Sorry it should remain open, Ig

**Comment by TahaTesser** [comment] 2020-09-24 11:57
This gets called when disposing of the second route with the back button or navigator.pop
```
  @override
  void dispose() {
    _controller?.close(); // <== HERE !!!
    debugPrint("Closed");
    super.dispose();
  }
```

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: IntialPage(),
      );
}

class IntialPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          Navigator.push(
              context, MaterialPageRoute(builder: (_) => MyHomePage()));
        },
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  StreamController<int> _controller;

  @override
  void initState() {
    super.initState();
    _controller = StreamController<int>();
  }

  @override
  void dispose() {
    _controller?.close(); // <== HERE !!!
    debugPrint("Closed");
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => StreamBuilder<int>(
      stream: _controller.stream,
      builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
        int _counter = snapshot.data ?? 0;
        return Scaffold(
          appBar: AppBar(
            title: const Text('stream counter'),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const Text(
                  'You have pushed the button this many times:',
                ),
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline,
                ),
              ],
            ),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: () => _controller.sink.add(_counter + 1),
            tooltip: 'Increment',
            child: Icon(Icons.add),
          ),
        );
      });
}

```

</details> 


But it doesn't call when  put in first scree aka the first route, 


<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class IntialPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          Navigator.push(
              context, MaterialPageRoute(builder: (_) => MyHomePage()));
        },
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  StreamController<int> _controller;

  @override
  void initState() {
    super.initState();
    _controller = StreamController<int>();
  }

  @override
  void dispose() {
    _controller?.close(); // <== HERE !!!
    debugPrint("Closed");
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => StreamBuilder<int>(
      stream: _controller.stream,
      builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
        int _counter = snapshot.data ?? 0;
        return Scaffold(
          appBar: AppBar(
            title: const Text('stream counter'),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const Text(
                  'You have pushed the button this many times:',
                ),
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline,
                ),
              ],
            ),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: () => _controller.sink.add(_counter + 1),
            tooltip: 'Increment',
            child: Icon(Icons.add),
          ),
        );
      });
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.340 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1fef5912cf (6 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.0
    • iPhone 11 (mobile)     • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

</details>

**Comment by raphael-bmec-co** [comment] 2021-01-22 08:26
I am not sure if you are using web but this may be related to https://github.com/FirebaseExtended/flutterfire/issues/4756

**Comment by maheshmnj** [comment] 2023-01-10 04:59
Hello @being-yash-t, this issue is the same as https://github.com/flutter/flutter/issues/40940 and in no way related to streams. I am able to reproduce the issue though `dispose` is not executed when the app exits on the last route. I am going to close this issue as duplicate of the existing issue, incase you disagree feel free to write in the comments and we will reopen it.

<details>
<summary>code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late StreamController<int> _controller;

  @override
  void initState() {
    super.initState();
    _controller = StreamController<int>();
  }

  @override
  void dispose() {
    _controller.close(); // <== HERE !!!
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => StreamBuilder<int>(
      stream: _controller.stream,
      builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
        int counter = snapshot.data ?? 0;
        return Scaffold(
          appBar: AppBar(
            title: const Text('stream counter'),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const Text(
                  'You have pushed the button this many times:',
                ),
                Text(
                  '$counter',
                  style: Theme.of(context).textTheme.headlineLarge,
                ),
              ],
            ),
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: () => _controller.sink.add(counter + 1),
            tooltip: 'Increment',
            child: const Icon(Icons.add),
          ),
        );
      });
}
```
</details> 
 
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Closed by maheshmnj** 2023-01-10 04:59 UTC
Labels: framework, engine, dependency: dart, has reproducible steps, P4, found in release: 1.22
