### ISSUE TITLE
Mechanism to force flutter apps to update to the latest and greatest

### ISSUE THREAD

**Issue by alabiaga** [flutter/flutter#88059] opened 2021-08-11 21:09 UTC
## Use case

The new overscroll stretch behavior is a default opt-in migration path for all apps on an Android 12 device.
There is currently no mechanism for apps built on Flutter for hot pushes/updates, see https://github.com/Flutter/Flutter/issues/14330, thus apps built on Flutter will have the previous "glow" overscroll
experience on an Android 12 develice.
     
## Proposal

Can we force flutter apps that are updating there app to update to the latest and greatest flutter so that they can be opted into the overscroll stretch UX so that we don't have the inconsistency of glow and stretch overscroll experiences in Android 12+. Eventhough all alls regardless of targetSDK are opted into the overscroll stretch experience perhaps we can limit the scope of apps that we want to force update to only those are changing their target  to SDK 29+

**Comment by alabiaga** [comment] 2021-08-11 21:10
cc\ @blasten @Piinks

**Comment by Piinks** [comment] 2021-08-11 21:23
Chatted with @goderbauer & @HansMuller about this yesterday. I think this might be considered a dupe of #14330 and may be closed by our triage team as such.

I don't know that we can force flutter apps to update in this way, particularly because some flutter releases contain breaking changes or require the user to update their code in other ways. If we forced a flutter app to update and it broke, that would be a really bad experience for Flutter users.

If code pushing were possible though, it would still be the responsibility of the developer to push updates to their app as well, not the Flutter team's. This would require action from the developer just as much as it would require them to take action and opt-in their application.

If we were able to do this though (force flutter apps in the wild to update), this type of push would not be able to change their code to opt them in to the stretch behavior you mentioned. Since it is an opt-in, developers need to choose to use it. We would not be able to change their code to make them use it. Otherwise the opt-in would be pointless and unnecessary.

The opt-in strategy proposed in https://github.com/flutter/flutter/pull/87839 is intended to be temporary to allow developers to migrate to the new behavior and make any other changes it necessitates when they update - for example it is expected to affect many many screenshot tests that currently contain the glow. Eventually it will be the new default for all Flutter apps, and will not require users to choose it manually.

**Comment by Piinks** [comment] 2021-08-11 21:29
Another consideration too - not all Flutter apps on Android use the default elements of the Android UX. A fair number of apps design their own UIs and design languages. These apps would likely not want us to change their custom UI.

**Comment by Piinks** [comment] 2021-08-11 21:32
> A fair number of apps design their own UIs and design languages.

A good example of this would be the Phillips Hue app. Their iOS/Android app has its own UX design that is neither iOS or Android.

**Comment by TahaTesser** [comment] 2021-08-12 10:17
Hi @alabiaga 
Please follow up on the duplicate issue, closing as duplicate of https://github.com/flutter/flutter/issues/14330

**Closed by TahaTesser** 2021-08-12 10:17 UTC
Labels: in triage

**Comment by alabiaga** [comment] 2021-08-12 12:53
> > A fair number of apps design their own UIs and design languages.
> 
> A good example of this would be the Phillips Hue app. Their iOS/Android app has its own UX design that is neither iOS or Android.

Right, this is fine as on Android one can define there own custom [EdgeEffect](https://developer.android.com/reference/android/widget/EdgeEffect) and define their own overscroll experience as well.

@Piinks  @TahaTesser  Great, thanks for the clarification and additional info.
