### ISSUE TITLE
flutter 2.2.2 release mode crash

### ISSUE THREAD

**Issue by AKZHW** [flutter/flutter#94517] opened 2021-12-02 03:57 UTC
detail https://github.com/flutter/flutter/issues/92162

when  I use 2.5.3 ,it's work,  not crash
but I hope fix this bug in 2.2.2, Who can help me?

**Comment by AKZHW** [comment] 2021-12-02 04:05
dart::Thread::EnterIsolate(dart::Isolate*, bool) | thread.cc | 284 |   |  
-- | -- | -- | -- | --
1 | Flutter | Dart_EnterIsolate | dart_api_impl.cc | 1546
2 | Flutter | Dart_EnterIsolate | dart_api_impl.cc | 1546
3 | Flutter | tonic::DartIsolateScope::DartIsolateScope(_Dart_Isolate*) | dart_isolate_scope.cc | 17
4 | Flutter | std::__1::__function::__func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()() | functional | 1707
5 | Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) | message_loop_impl.cc | 132
6 | Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) | message_loop_darwin.mm | 76
7 | CoreFoundation | __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ | - | -
8 | CoreFoundation | __CFRunLoopDoTimer | - | -
9 | CoreFoundation | __CFRunLoopDoTimers | - | -
10 | CoreFoundation | __CFRunLoopRun | - | -
11 | CoreFoundation | CFRunLoopRunSpecific | - | -
12 | Flutter | fml::MessageLoopDarwin::Run() | message_loop_darwin.mm | 47
13 | Flutter | void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) | thread | 351
14 | libsystem_pthread.dylib | _pthread_start |   |  


<br class="Apple-interchange-newline">

**Comment by maheshmnj** [comment] 2021-12-02 08:16
Hi @AKZHW, 

> when I use 2.5.3 ,it's work, not crash

Since you are no longer able to reproduce the issue on `2.5.3` so this is likely fixed, You will need to upgrade to stable `2.5.3`, The new fixes are always released with a newer version so it always advisable to use the latest stable release to stay upto date with the latest fixes.
You can read more about How the release process works here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

Closing as fixed on the latest stable.

**Closed by maheshmnj** 2021-12-02 08:16 UTC
Labels: in triage

**Comment by AKZHW** [comment] 2021-12-04 12:49
If we upgrade to 2.5.3, we will face a lot of adaptation costs，We just want to use 2.2.2

**Comment by maheshmnj** [comment] 2021-12-06 05:16
@AKZHW, It isn't feasible to add specific fixes to each stable release, 

> we will face a lot of adaptation costs
I am not sure what costs you are talking about, but upgrading shouldn't be an issue in my opinion.

Alternatively, If you decide not to upgrade then you might want to dig a bit into the stable 2.5.3 release notes and cherry-pick the fix to your stable 2.2.2  SDK.
