### ISSUE TITLE
Firebase Auth/Messaging errors while build to iOS

### ISSUE THREAD

**Issue by Hahnstrong** [flutter/flutter#36181] opened 2019-07-15 08:35 UTC
S, I have had no problems with the Android side. However when I went to try to build to iOS on my MacBook, I have been getting errors for FirebaseAuth and FirebaseMessaging, ie

/Users/hahnstrong/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:264:67:
    error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type
    'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                           completion:^(FIRUser *user, NSError *error) {
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A lot of them.

-My cocoapods is 1.7.4 (I tried lowering it to 1.6, didnt change anything)
-flutter doctor shows every is fine.
-I have tried everything previous threads have said to do (pod repo update, deleting Podfile/Podfile.lock/Pods/.packages etc etc). Ive deleted the derived data from my Xcode. Ive tried different versions of CocoaPods. Ive tried differing versions of the dependencies.

Here is what my current dependencies are now in the pubspec.yaml:
`url_launcher: ^5.0.2
  shared_preferences: ^0.4.3
  sqflite: ^1.1.6

  firebase_core: ^0.2.5
  firebase_auth: ^0.6.6
  firebase_database: ^1.0.5
  firebase_messaging: ^2.0.0
  google_maps_flutter: ^0.5.5`

Help with be much appreciated.

**Comment by jmagman** [comment] 2019-07-18 17:56
Looks like a duplicate of https://github.com/flutter/flutter/issues/32398.

**Closed by jmagman** 2019-07-18 17:56 UTC
