### ISSUE TITLE
Style BottomNavigationBar in Flutter

### ISSUE THREAD

**Issue by dhavalagile** [flutter/flutter#30693] opened 2019-04-08 13:57 UTC
I am unable to distingue BottomNavigationBar selected item background colour and inactive item background colour.

Below is my sample code
```
 bottomNavigationBar: new Theme(
        data: Theme.of(context).copyWith(
            canvasColor: Colors.blue,
            primaryColor: Colors.pink,

            textTheme: Theme
                .of(context)
                .textTheme
                .copyWith(caption: new TextStyle(color: Colors.yellow))
        ),
        child: new BottomNavigationBar(
          type: BottomNavigationBarType.fixed,
          items: [
            new BottomNavigationBarItem(
              icon: new Icon(Icons.home),
              title: Container(height: 0,), backgroundColor: Colors.blue
            ),
            new BottomNavigationBarItem(
              icon: new Icon(Icons.search),
              title: Container(height: 0,),
              backgroundColor: Colors.green
            ),
            new BottomNavigationBarItem(
              icon: new Icon(Icons.undo),
              title: Container(height: 0,),
            ),
            new BottomNavigationBarItem(
              icon: new Icon(Icons.redeem),
              title: Container(height: 0,),
            ),
            new BottomNavigationBarItem(
              icon: new Icon(Icons.cached),
              title: Container(height: 0,),
            ),
          ],
          currentIndex: _index,
          onTap: (int item) {
            setState(() {
              _index = item;
            });
          },
        ),
      ),
```

I want to the distingue active item background colour and inactive item background Colour.

**Comment by TahaTesser** [comment] 2020-02-21 11:07
Duplicate of [#34788](https://github.com/flutter/flutter/issues/34788)

**Closed by TahaTesser** 2020-02-21 11:07 UTC
Labels: f: material design, framework
