### ISSUE TITLE
complex_layout_scroll_perf__timeline_summary worst_frame_rasterizer_time_millis regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#21889] opened 2018-09-14 21:10 UTC
This regression seems to start from https://github.com/flutter/flutter/commit/a07d3719a1fe58c0c43ffde7079be291640fa98b

**Comment by liyuqian** [comment] 2018-09-14 21:10
CC @a14n @Hixie

**Comment by Hixie** [comment] 2018-09-17 16:01
Looking at the numbers again with more data, it looks like this may have just been bad luck with the noise. It's not clear that there's a regression and it's not at all clear where it would have started if we assume that there is. I'm going to close this issue for now and keep an eye on the perf numbers. Thanks for filing it though!

**Closed by Hixie** 2018-09-17 16:01 UTC
Labels: severe: performance, ⚠ TODAY
