### ISSUE TITLE
Linux textfield input is backwards

### ISSUE THREAD

**Issue by NO-ob** [flutter/flutter#77952] opened 2021-03-11 18:55 UTC
![Demo](https://im2.ezgif.com/tmp/ezgif-2-4512d5b8cd8b.gif)
## Steps to Reproduce

1. Run application on linux via "flutter run" or android studios play button
2. Start typing in textfield

**Expected results:** Text input normally

**Actual results:** Text input is backwards

It works fine on android or running on desktop with go-flutter, I have tried both the stable and beta channels with the same result

<details>
  <summary>Logs</summary>

```
```

```
   info • Unused import: 'package:LoliSnatcher/libBooru/BooruHandlerFactory.dart' • lib/DesktopHome.dart:4:8 • unused_import
   info • Unused import: 'package:LoliSnatcher/widgets/MediaViewer.dart' • lib/DesktopHome.dart:7:8 • unused_import
   info • Unused import: 'package:LoliSnatcher/widgets/VideoApp.dart' • lib/DesktopHome.dart:11:8 • unused_import
   info • Unused import: 'package:photo_view/photo_view.dart' • lib/DesktopHome.dart:16:8 • unused_import
   info • Unused import: 'AboutPage.dart' • lib/DesktopHome.dart:18:8 • unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: DesktopHome.settingsHandler, DesktopHome.snatchHandler • lib/DesktopHome.dart:28:7 •
          must_be_immutable
   info • Prefer using /// for doc comments • lib/DesktopHome.dart:234:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/DesktopHome.dart:237:10 • non_constant_identifier_names
   info • Prefer using /// for doc comments • lib/DesktopHome.dart:303:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/DesktopHome.dart:306:10 • non_constant_identifier_names
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: DesktopTagListener.valueNotifier, DesktopTagListener.settingsHandler,
          DesktopTagListener.searchGlobals • lib/DesktopHome.dart:383:7 • must_be_immutable
   info • Name non-constant identifiers using lowerCamelCase • lib/ImageWriter.dart:13:7 • non_constant_identifier_names
   info • Prefer using /// for doc comments • lib/ImageWriter.dart:14:3 • slash_for_doc_comments
   info • 'await' applied to 'String', which is not a 'Future' • lib/ImageWriter.dart:185:19 • await_only_futures
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: NewTagSearchBox.searchGlobals, NewTagSearchBox.searchTagsController,
          NewTagSearchBox.settingsHandler, NewTagSearchBox.searchAction, NewTagSearchBox._focusNode, NewTagSearchBox.booruHandler, NewTagSearchBox.pageNum, NewTagSearchBox.displayTags • lib/NewTagSearchBox.dart:10:7 • must_be_immutable
   info • Unused import: 'package:get/get.dart' • lib/SearchGlobals.dart:6:8 • unused_import
   info • Unused import: 'libBooru/DBHandler.dart' • lib/ServiceHandler.dart:6:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • lib/SettingsHandler.dart:4:8 • unused_import
   info • Unused import: 'package:get/get.dart' • lib/SettingsHandler.dart:7:8 • unused_import
   info • Unused import: 'ThemeItem.dart' • lib/SettingsHandler.dart:8:8 • unused_import
   info • Prefer using /// for doc comments • lib/SettingsHandler.dart:13:1 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/SettingsHandler.dart:21:7 • non_constant_identifier_names
   info • Avoid using unnecessary statements • lib/SettingsHandler.dart:46:7 • unnecessary_statements
   info • The value of the local variable 'prefIndex' isn't used • lib/SettingsHandler.dart:302:9 • unused_local_variable
   info • The operand can't be null, so the condition is always true • lib/SettingsHandler.dart:309:17 • unnecessary_null_comparison
   info • Unused import: 'package:LoliSnatcher/libBooru/DBHandler.dart' • lib/SettingsPage.dart:3:8 • unused_import
   info • Unused import: 'libBooru/BooruOnRailsHandler.dart' • lib/SettingsPage.dart:5:8 • unused_import
   info • Unused import: 'libBooru/GelbooruHandler.dart' • lib/SettingsPage.dart:6:8 • unused_import
   info • Unused import: 'libBooru/GelbooruV1Handler.dart' • lib/SettingsPage.dart:7:8 • unused_import
   info • Unused import: 'libBooru/MoebooruHandler.dart' • lib/SettingsPage.dart:8:8 • unused_import
   info • Unused import: 'libBooru/PhilomenaHandler.dart' • lib/SettingsPage.dart:9:8 • unused_import
   info • Unused import: 'libBooru/DanbooruHandler.dart' • lib/SettingsPage.dart:10:8 • unused_import
   info • Unused import: 'libBooru/ShimmieHandler.dart' • lib/SettingsPage.dart:11:8 • unused_import
   info • Unused import: 'libBooru/SankakuHandler.dart' • lib/SettingsPage.dart:13:8 • unused_import
   info • Unused import: 'libBooru/e621Handler.dart' • lib/SettingsPage.dart:16:8 • unused_import
   info • Unused import: 'libBooru/SzurubooruHandler.dart' • lib/SettingsPage.dart:17:8 • unused_import
   info • Prefer using /// for doc comments • lib/SettingsPage.dart:24:1 • slash_for_doc_comments
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SettingsPage.settingsHandler • lib/SettingsPage.dart:27:7 • must_be_immutable
   info • 'WhitelistingTextInputFormatter' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.allow instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:125:27 • deprecated_member_use
   info • 'digitsOnly' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.digitsOnly instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:125:58 • deprecated_member_use
   info • 'WhitelistingTextInputFormatter' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.allow instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:156:27 • deprecated_member_use
   info • 'digitsOnly' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.digitsOnly instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:156:58 • deprecated_member_use
   info • 'WhitelistingTextInputFormatter' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.allow instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:186:27 • deprecated_member_use
   info • 'digitsOnly' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.digitsOnly instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:186:58 • deprecated_member_use
   info • 'WhitelistingTextInputFormatter' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.allow instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:216:27 • deprecated_member_use
   info • 'digitsOnly' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.digitsOnly instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:216:58 • deprecated_member_use
   info • 'WhitelistingTextInputFormatter' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.allow instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:334:27 • deprecated_member_use
   info • 'digitsOnly' is deprecated and shouldn't be used. Use FilteringTextInputFormatter.digitsOnly instead. This feature was deprecated after v1.20.0-1.0.pre. • lib/SettingsPage.dart:334:58 • deprecated_member_use
   info • Prefer using /// for doc comments • lib/SettingsPage.dart:829:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/SettingsPage.dart:833:10 • non_constant_identifier_names
   info • Prefer using /// for doc comments • lib/SettingsPage.dart:874:1 • slash_for_doc_comments
   info • Name types using UpperCamelCase • lib/SettingsPage.dart:877:7 • camel_case_types
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: booruEdit.settingsHandler, booruEdit.booru, booruEdit.booruType •
          lib/SettingsPage.dart:877:7 • must_be_immutable
   info • Name types using UpperCamelCase • lib/SettingsPage.dart:886:7 • camel_case_types
   info • Prefer using /// for doc comments • lib/SettingsPage.dart:1208:3 • slash_for_doc_comments
   info • Prefer using /// for doc comments • lib/SettingsPage.dart:1256:3 • slash_for_doc_comments
   info • The member 'hasListeners' can only be used within instance members of subclasses of 'package:flutter/src/foundation/change_notifier.dart' • lib/SnatchHandler.dart:28:23 • invalid_use_of_protected_member
   info • Prefer using /// for doc comments • lib/Snatcher.dart:12:1 • slash_for_doc_comments
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SnatcherPage.booru, SnatcherPage.settingsHandler, SnatcherPage.snatchHandler •
          lib/Snatcher.dart:15:7 • must_be_immutable
   info • Prefer using /// for doc comments • lib/Snatcher.dart:182:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/Snatcher.dart:185:10 • non_constant_identifier_names
   info • The operand can't be null, so the condition is always false • lib/Snatcher.dart:187:22 • unnecessary_null_comparison
   info • Prefer using /// for doc comments • lib/getPerms.dart:4:1 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/BooruHandler.dart:16:11 • non_constant_identifier_names
   info • Unused import: 'BooruItem.dart' • lib/libBooru/BooruHandlerFactory.dart:5:8 • unused_import
   info • Unused import: 'package:LoliSnatcher/libBooru/PhilomenaHandler.dart' • lib/libBooru/BooruOnRailsHandler.dart:2:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • lib/libBooru/BooruOnRailsHandler.dart:3:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/BooruOnRailsHandler.dart:14:10 • non_constant_identifier_names
   info • Avoid using braces in interpolation when not needed • lib/libBooru/DBHandler.dart:100:34 • unnecessary_brace_in_string_interps
   info • Prefer using /// for doc comments • lib/libBooru/DanbooruHandler.dart:8:1 • slash_for_doc_comments
   info • Prefer using /// for doc comments • lib/libBooru/DanbooruHandler.dart:17:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/DanbooruHandler.dart:21:10 • non_constant_identifier_names
   info • 'parse' is deprecated and shouldn't be used. Use `XmlDocument.parse` instead • lib/libBooru/DanbooruHandler.dart:37:34 • deprecated_member_use
   info • Unused import: 'package:flutter/material.dart' • lib/libBooru/FavouritesHandler.dart:2:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/FavouritesHandler.dart:15:10 • non_constant_identifier_names
   info • Unused import: 'package:flutter/material.dart' • lib/libBooru/GelbooruHandler.dart:3:8 • unused_import
   info • Prefer using /// for doc comments • lib/libBooru/GelbooruHandler.dart:11:1 • slash_for_doc_comments
   info • Prefer using /// for doc comments • lib/libBooru/GelbooruHandler.dart:20:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/GelbooruHandler.dart:24:10 • non_constant_identifier_names
   info • 'parse' is deprecated and shouldn't be used. Use `XmlDocument.parse` instead • lib/libBooru/GelbooruHandler.dart:41:34 • deprecated_member_use
   info • 'parse' is deprecated and shouldn't be used. Use `XmlDocument.parse` instead • lib/libBooru/GelbooruHandler.dart:115:38 • deprecated_member_use
   info • Prefer using /// for doc comments • lib/libBooru/GelbooruV1Handler.dart:8:1 • slash_for_doc_comments
   info • Prefer using /// for doc comments • lib/libBooru/GelbooruV1Handler.dart:16:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/GelbooruV1Handler.dart:20:10 • non_constant_identifier_names
   info • The operand can't be null, so the condition is always true • lib/libBooru/GelbooruV1Handler.dart:42:19 • unnecessary_null_comparison
   info • Unused import: 'package:flutter/cupertino.dart' • lib/libBooru/HydrusHandler.dart:3:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • lib/libBooru/HydrusHandler.dart:4:8 • unused_import
   info • Unused import: 'package:xml/xml.dart' • lib/libBooru/HydrusHandler.dart:6:8 • unused_import
   info • Prefer using /// for doc comments • lib/libBooru/HydrusHandler.dart:12:1 • slash_for_doc_comments
   info • Prefer using /// for doc comments • lib/libBooru/HydrusHandler.dart:22:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/HydrusHandler.dart:26:10 • non_constant_identifier_names
   info • The value of the local variable 'tagList' isn't used • lib/libBooru/HydrusHandler.dart:27:10 • unused_local_variable
   info • Prefer using /// for doc comments • lib/libBooru/MoebooruHandler.dart:3:1 • slash_for_doc_comments
   info • Unused import: 'package:flutter/material.dart' • lib/libBooru/PhilomenaHandler.dart:2:8 • unused_import
   info • Prefer using /// for doc comments • lib/libBooru/PhilomenaHandler.dart:13:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/PhilomenaHandler.dart:17:10 • non_constant_identifier_names
   info • Unused import: 'package:flutter/material.dart' • lib/libBooru/SankakuHandler.dart:2:8 • unused_import
   info • Prefer using /// for doc comments • lib/libBooru/SankakuHandler.dart:15:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/SankakuHandler.dart:19:10 • non_constant_identifier_names
   info • Unused import: 'dart:convert' • lib/libBooru/ShimmieHandler.dart:1:8 • unused_import
   info • Prefer using /// for doc comments • lib/libBooru/ShimmieHandler.dart:9:1 • slash_for_doc_comments
   info • Prefer using /// for doc comments • lib/libBooru/ShimmieHandler.dart:17:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/ShimmieHandler.dart:21:10 • non_constant_identifier_names
   info • 'parse' is deprecated and shouldn't be used. Use `XmlDocument.parse` instead • lib/libBooru/ShimmieHandler.dart:42:34 • deprecated_member_use
   info • Unused import: 'dart:io' • lib/libBooru/SzurubooruHandler.dart:3:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • lib/libBooru/SzurubooruHandler.dart:4:8 • unused_import
   info • Prefer using /// for doc comments • lib/libBooru/SzurubooruHandler.dart:16:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/SzurubooruHandler.dart:20:10 • non_constant_identifier_names
   info • Avoid empty statements • lib/libBooru/SzurubooruHandler.dart:110:102 • empty_statements
   info • Unused import: 'package:flutter/material.dart' • lib/libBooru/e621Handler.dart:2:8 • unused_import
   info • Name types using UpperCamelCase • lib/libBooru/e621Handler.dart:10:7 • camel_case_types
   info • Prefer using /// for doc comments • lib/libBooru/e621Handler.dart:14:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/libBooru/e621Handler.dart:18:10 • non_constant_identifier_names
   info • The value of the local variable 'posts' isn't used • lib/libBooru/e621Handler.dart:40:13 • unused_local_variable
   info • Unused import: 'dart:io' • lib/main.dart:2:8 • unused_import
   info • Unused import: 'package:LoliSnatcher/widgets/ScrollingText.dart' • lib/main.dart:21:8 • unused_import
   info • Unused import: 'libBooru/BooruHandler.dart' • lib/main.dart:27:8 • unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Preloader.settingsHandler • lib/main.dart:53:7 • must_be_immutable
   info • Prefer using /// for doc comments • lib/main.dart:78:1 • slash_for_doc_comments
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Home.settingsHandler, Home.snatchHandler • lib/main.dart:81:7 • must_be_immutable
   info • Prefer using /// for doc comments • lib/main.dart:364:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/main.dart:367:10 • non_constant_identifier_names
   info • Prefer using /// for doc comments • lib/main.dart:432:3 • slash_for_doc_comments
   info • Name non-constant identifiers using lowerCamelCase • lib/main.dart:435:10 • non_constant_identifier_names
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: ActiveTitle.snatchHandler, ActiveTitle.isSnatching, ActiveTitle.snatchStatus •
          lib/widgets/ActiveTitle.dart:5:7 • must_be_immutable
   info • This method overrides a method annotated as '@mustCallSuper' in 'State', but doesn't invoke the overridden method • lib/widgets/ActiveTitle.dart:17:8 • must_call_super
   info • Unused import: 'ViewerPage.dart' • lib/widgets/DesktopImageListener.dart:14:8 • unused_import
   info • Prefer using /// for doc comments • lib/widgets/DesktopImageListener.dart:16:1 • slash_for_doc_comments
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: DesktopImageListener.searchGlobals, DesktopImageListener.globalsIndex,
          DesktopImageListener.settingsHandler, DesktopImageListener.snatchHandler • lib/widgets/DesktopImageListener.dart:21:7 • must_be_immutable
   info • Unused import: 'package:flutter/services.dart' • lib/widgets/HideableAppbar.dart:4:8 • unused_import
   info • Unused import: '../ServiceHandler.dart' • lib/widgets/HideableAppbar.dart:8:8 • unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: HideableAppBar.title, HideableAppBar.actions, HideableAppBar.searchGlobals,
          HideableAppBar.autoHide • lib/widgets/HideableAppbar.dart:10:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: InfoDialog.title, InfoDialog.bodyWidgets, InfoDialog.horizontalAlignment •
          lib/widgets/InfoDialog.dart:4:7 • must_be_immutable
   info • Don't import implementation files from another package • lib/widgets/LoliControls.dart:4:8 • implementation_imports
   info • Don't import implementation files from another package • lib/widgets/LoliControls.dart:5:8 • implementation_imports
   info • Don't import implementation files from another package • lib/widgets/LoliControls.dart:6:8 • implementation_imports
   info • Don't import implementation files from another package • lib/widgets/LoliControls.dart:7:8 • implementation_imports
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:105:27 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:106:24 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:107:32 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:295:27 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:296:24 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:297:32 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:371:38 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:371:65 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:398:27 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:399:19 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:458:38 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:623:38 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:624:33 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:625:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:663:38 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:664:33 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:665:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:766:32 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:767:38 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:768:33 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/widgets/PreloadPageView.dart:769:28 • unnecessary_null_comparison
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: ScrollingText.text, ScrollingText.size, ScrollingText.mode, ScrollingText.textColor •
          lib/widgets/ScrollingText.dart:4:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: TabBox.searchGlobals, TabBox.globalsIndex, TabBox.searchTagsController,
          TabBox.settingsHandler • lib/widgets/TabBox.dart:9:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: TagSearchBox.searchGlobals, TagSearchBox.searchTagsController, TagSearchBox._focusNode,
          TagSearchBox.settingsHandler, TagSearchBox.searchAction • lib/widgets/TagSearchBox.dart:11:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: TagView.booruItem, TagView.searchGlobals • lib/widgets/TagView.dart:9:7 • must_be_immutable
   info • Unused import: 'dart:typed_data' • lib/widgets/VideoApp.dart:4:8 • unused_import
   info • Unused import: '../DesktopHome.dart' • lib/widgets/ViewerPage.dart:27:8 • unused_import
   info • Prefer using /// for doc comments • lib/widgets/ViewerPage.dart:30:1 • slash_for_doc_comments
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: ViewerPage.fetched, ViewerPage.index, ViewerPage.searchGlobals, ViewerPage.settingsHandler,
          ViewerPage.snatchHandler • lib/widgets/ViewerPage.dart:35:7 • must_be_immutable
   info • The value of the local variable 'fileURL' isn't used • lib/widgets/ViewerPage.dart:130:18 • unused_local_variable
   info • Use `lowercase_with_underscores` for package names • pubspec.yaml:1:7 • package_names
warning • Publishable packages can't have git dependencies • pubspec.yaml:34:5 • invalid_dependency
  error • Target of URI doesn't exist: 'package:loli/main.dart' • test/widget_test.dart:11:8 • uri_does_not_exist
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function

```

```
[✓] Flutter (Channel beta, 2.0.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.1 at /home/kannalo/devShit/flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/kannalo/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.19.6
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.82 Arch Linux

• No issues found!

```

</details>

**Comment by miDeb** [comment] 2021-03-11 20:07
This is a duplicate of https://github.com/flutter/flutter/issues/76383.

**Comment by NO-ob** [comment] 2021-03-11 20:08
oh should i close this then?

**Comment by miDeb** [comment] 2021-03-11 20:09
Yea please :) you can click on "Subscribe" at the other issue to follow its process.

**Comment by NO-ob** [comment] 2021-03-11 20:09
thankyou

**Closed** 2021-03-11 21:51 UTC
