### ISSUE TITLE
Popups and Dropdowns initiated from an Overlay appears behind the overlay

### ISSUE THREAD

**Issue by mortenboye** [flutter/flutter#105108] opened 2022-06-01 09:40 UTC
After upgrading to Flutter 3.0.x this issue has appeared.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Press the "Open overlay" button
3. Open the Dropdown or click the "Open Dialog" button

**Expected results:** 
The Dropdown options and the Dialog panel should appear on top of the overlay. 

**Actual results:** 
The Dropdown options and the Dialog panel appears behind the overlay. 

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: ElevatedButton(
        child: const Text("Open overlay"),
        onPressed: () {
          _openOverlay();
        },
      ),
    ));
  }

  OverlayEntry? _overlayEntry;
  int _selection = 0;

  _closeOverlay() {
    _overlayEntry?.remove();
  }

  _openOverlay() {
    _overlayEntry = OverlayEntry(
      builder: (context) {
        return Material(
          color: Colors.black54,
          child: Stack(
            children: <Widget>[
              GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: _closeOverlay,
              ),
              Positioned(
                left: 100,
                right: 100,
                bottom: 100,
                top: 100,
                child: Card(
                  elevation: 20,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(15.0),
                  ),
                  color: Colors.grey,
                  child: Container(
                    padding: const EdgeInsets.all(12.0),
                    alignment: Alignment.center,
                    child: Column(
                      children: [
                        DropdownButton<int>(
                          value: _selection,
                          onChanged: (val) {
                            setState(() {
                              _selection = val ?? 0;
                            });
                          },
                          items: List.generate(
                            10,
                            (index) => DropdownMenuItem(child: Text("Dropdown $index"), value: index),
                          ),
                        ),
                        ElevatedButton(
                          onPressed: () {
                            showDialog(
                                context: context,
                                builder: (context) {
                                  return AlertDialog(
                                    title: const Text('Material Dialog'),
                                    actions: <Widget>[
                                      TextButton(
                                          onPressed: () {
                                            Navigator.of(context).pop();
                                          },
                                          child: const Text('Close')),
                                      TextButton(
                                        onPressed: () {
                                          Navigator.of(context).pop();
                                        },
                                        child: const Text('HelloWorld!'),
                                      )
                                    ],
                                  );
                                });
                          },
                          child: const Text("Open Dialog"),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
    Overlay.of(context)?.insert(_overlayEntry!);
  }
}
```

</details>

**Comment by TahaTesser** [comment] 2022-06-01 10:05
Hi @mortenboye 
This is a duplicate of https://github.com/flutter/flutter/issues/22917, please read https://github.com/flutter/flutter/issues/22917#issuecomment-431457670.

**Closed by TahaTesser** 2022-06-01 10:05 UTC
Labels: in triage
