### ISSUE TITLE
RTMP publisher plugin app crashes

### ISSUE THREAD

**Issue by abheet-98** [flutter/flutter#59583] opened 2020-06-16 18:13 UTC
Heyy !
Hope everyone is doing well !
I'm stuck with something in the live streaming app. Actually I have used this plugin "https://github.com/espresso3389/flutter_rtmp_publisher/" in my app and app has four different screens.The third screen is the camera preview screen.
Now when I'm pressing the back button on the third screen, I have routed to an exit screen(i.e, fourth screen of the app).
After pressing back button on the exit screen, App crashes giving the logs which are given below.

I'm stuck in this for a week but couldn't resolve this. 
Thanks in advance !

<details>
  <summary>Logs</summary>

```bash
D/ViewRootImpl@a08ca14MainActivity: dispatchDetachedFromWindow
D/InputTransport( 4339): Input channel destroyed: fd=85
D/AndroidRuntime( 4339): Shutting down VM
E/AndroidRuntime( 4339): FATAL EXCEPTION: main
E/AndroidRuntime( 4339): Process: com.example.flutterapp, PID: 4339
E/AndroidRuntime( 4339): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/AndroidRuntime( 4339): at com.takusemba.rtmppublisher.RtmpPublisher.getDeviceRotation(RtmpPublisher.java:166)
E/AndroidRuntime( 4339): at com.takusemba.rtmppublisher.RtmpPublisher.checkOrientation(RtmpPublisher.java:155)
E/AndroidRuntime( 4339): at com.takusemba.rtmppublisher.RtmpPublisher.access$000(RtmpPublisher.java:16)
E/AndroidRuntime( 4339): at com.takusemba.rtmppublisher.RtmpPublisher$1.run(RtmpPublisher.java:65)
E/AndroidRuntime( 4339): at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 4339): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4339): at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 4339): at android.app.ActivityThread.main(ActivityThread.java:7076)
E/AndroidRuntime( 4339): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4339): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 4339): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
I/Process ( 4339): Sending signal. PID: 4339 SIG: 9
Lost connection to device.
```

</details>

**Comment by iapicca** [comment] 2020-06-17 06:44
Hi @abheet-98 
From what I can see, the issue is related to a 3rd party plugin [flutter_rtmp_publisher](https://pub.dev/packages/flutter_rtmp_publisher)
rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/PonnamKarthik/FlutterRtmpPlublisher/issues).

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing a minimal reproducible code sample 
that does not use 3rd party plugins,  and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-17 06:44 UTC
