### ISSUE TITLE
in_app_purchase 0.3.4+10 new crash from "simulatesAskToBuyInSandbox"

### ISSUE THREAD

**Issue by nezoat** [flutter/flutter#67139] opened 2020-10-02 16:09 UTC
Parameters are not @required and should be, otherwise crash results. 

When using the following method, if the 'sandboxTesting' optional parameter is not provided, results in crash:

 ```
InAppPurchaseConnection.instance
          .buyNonConsumable(purchaseParam: PurchaseParam(productDetails: <>, applicationUserName: <>, sandboxTesting: <>));

 App crashes at line 183, InAppPurchasePlugin.m:
[[paymentMap objectForKey:@"simulatesAskToBuyInSandbox"] boolValue];

Results in error: "[NSNull boolValue]: unrecognized selector sent to instance"

Thread#0	0x0000000193a5a5ac in <redacted> ()
#1	0x00000001a7ad442c in objc_exception_throw ()
#5	0x0000000105c90c8c in -[InAppPurchasePlugin addPayment:result:] at /Users/lee/.pub-cache/hosted/pub.dartlang.org/in_app_purchase-0.3.4+10/ios/Classes/InAppPurchasePlugin.m:183
#6	0x0000000105c8f964 in -[InAppPurchasePlugin handleMethodCall:result:] at /Users/lee/.pub-cache/hosted/pub.dartlang.org/in_app_purchase-0.3.4+10/ios/Classes/InAppPurchasePlugin.m:91
#7	0x00000001042456cc in __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke ()
#8	0x0000000103a04cd4 in flutter::PlatformViewIOS::HandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>) ()
#9	0x0000000103cdf54c in std::__1::__function::__func<flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>)::$_33, std::__1::allocator<flutter::Shell::OnEngineHandlePlatformMessage(fml::RefPtr<flutter::PlatformMessage>)::$_33>, void ()>::operator()() ()
#10	0x0000000103a0e27c in fml::MessageLoopImpl::FlushTasks(fml::FlushType) ()
#11	0x0000000103a109a8 in fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) ()
#16	0x00000001939d04bc in CFRunLoopRunSpecific ()
#17	0x00000001aa455820 in GSEventRunModal ()
#18	0x0000000196374734 in <redacted> ()
#19	0x0000000196379e10 in UIApplicationMain ()
#20	0x0000000102158978 in main at /Users/lee/Development/IntelliJProjects/social_chess_flutter/ios/Runner/AppDelegate.swift:7
#21	0x0000000193697e60 in <redacted> ()
```

**Comment by SpajicM** [comment] 2020-10-02 22:34
Duplicate of https://github.com/flutter/flutter/issues/65767

**Comment by darshankawar** [comment] 2020-10-05 06:59
@nezoat 
Please see above referenced ticket and related open [PR](https://github.com/flutter/plugins/pull/3110) to fix the issue.
Closing this as duplicate.

**Closed by darshankawar** 2020-10-05 06:59 UTC
