### ISSUE TITLE
The video_player plugin crashes after change live stream 9 times

### ISSUE THREAD

**Issue by edufolly** [flutter/flutter#29055] opened 2019-03-08 18:32 UTC
## Code

Sample app is provided in the repository: 

https://github.com/edufolly/video_player_test

## Steps to Reproduce

1. Only change the stream 9 times and the app crashes.

## Logs

```
I/flutter ( 2181): http://ebctvnbr-rtmp.adaptive.level3.net/egress/bhandler/ebcremuxlive/tvnbr/manifest.m3u8
I/ExoPlayerImpl( 2181): Init 2798e55 [ExoPlayerLib/2.9.1] [victara, XT1097, motorola, 23]
I/MediaCodec( 2181): name=OMX.qcom.video.decoder.avc isType=false encoder=false
I/OMXClient( 2181): Using client-side OMX mux.
W/ACodec  ( 2181): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  ( 2181): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  ( 2181): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec( 2181): Codec reported err 0xfffffff4, actionCode 0, while in state 1
W/MediaCodec-JNI( 2181): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI( 2181): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodecRenderer( 2181): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer( 2181): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer( 2181): 	at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer( 2181): 	at android.media.MediaCodec.<init>(MediaCodec.java:1677)
W/MediaCodecRenderer( 2181): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1656)
W/MediaCodecRenderer( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer( 2181): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer( 2181): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
W/MediaCodecRenderer( 2181): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
W/MediaCodecRenderer( 2181): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/MediaCodecRenderer( 2181): 	at android.os.Looper.loop(Looper.java:148)
W/MediaCodecRenderer( 2181): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2181): Playback error.
E/ExoPlayerImplInternal( 2181): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(0, null, null, video/avc, avc1.42C01F, 544768, null, [1280, 720, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
E/ExoPlayerImplInternal( 2181): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2181): 	at android.os.Looper.loop(Looper.java:148)
E/ExoPlayerImplInternal( 2181): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2181): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(0, null, null, video/avc, avc1.42C01F, 544768, null, [1280, 720, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal( 2181): 	... 9 more
E/ExoPlayerImplInternal( 2181): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal( 2181): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal( 2181): 	at android.media.MediaCodec.<init>(MediaCodec.java:1677)
E/ExoPlayerImplInternal( 2181): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1656)
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal( 2181): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal( 2181): 	... 10 more
```

```
[✓] Flutter (Channel master, v1.3.8-pre.16, on Mac OS X 10.13.6 17G5019, locale pt-BR)
    • Flutter version 1.3.8-pre.16 at /Users/edufolly/Documents/flutter
    • Framework revision cd1b89c696 (2 days ago), 2019-03-06 17:42:51 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/edufolly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • XT1097 • 0433009317 • android-arm • Android 6.0 (API 23)

• No issues found!
```

Thanks.

**Comment by leonetosoft** [comment] 2019-03-19 05:00
I do not know if you noticed but you're theoretically playing one video on top of the other on the screen.

Slow your app I noticed that if you hold your finger on the video it goes to the next one but it does not clean the old "dispose ()", I faced this same problem then I created a "hack" so that it is possible to change the video:
``` 
 Next() {
    setState(() {
      disposeWidget = true; // disable your interface render "VideoPlayer"
    });

    _controller.pause().then((pause) {
      new Timer(new Duration(milliseconds: 100), () {

        _controller.removeListener(_listenVideo);
        _controller.dispose().then((a)
        {
          this.UpdateVideoController(); // update basics video_player
        });

      });
    });
  }
```

**Comment by edufolly** [comment] 2019-03-22 21:31
Hi @leonetosoft, 

could you show us some more of your code?

Thanks.

**Comment by leonetosoft** [comment] 2019-03-24 23:20
I already know why the playpack error occurs, so I am trying to manipulate the media that is passing in real time. I am building an application where it is possible to host the media on a server and this my application downloads to the internal storage and plays using the video_player.

For you to control the media in real time it is necessary to change the MediaSource, but not in this way as we are doing with "dispose", this is a hack, and causes the playback error after several "dispose".

I solved this problem by adding a new method to api in Java, I have no experience with IOS and I will not even have to do this because my app will only work on Android.

I added this method to the JAVA code:

Add in VideoPlayerPlugin.java line 237:
```
void nextVideo(String dataSource) {
            Uri uri = Uri.parse(dataSource);
            exoPlayer.stop();
            MediaSource mediaSource = buildMediaSource(uri, this._dataSourceFactory, this._context);
            exoPlayer.prepare(mediaSource);
        }
```
Add variables in VideoPlayerPlugin.java line 72:
```
private DataSource.Factory _dataSourceFactory = null;
private Context _context;
```

Add set variables in VideoPlayerPlugin.java line 102:
```
this._context = context;
this._dataSourceFactory = dataSourceFactory;
```
Add in VideoPlayerPlugin.java line 176 in method onPlayerStateChanged to refresh Duration new MediaSource:
```
else if(playbackState == Player.STATE_READY) {
                                //Log.d("CHANGEEEEEEEEEEEEED", "DEU DURACAO HEHE");
                                Map<String, Object> event = new HashMap<>();
                                event.put("event", "changedVideo");
                                event.put("duration", exoPlayer.getDuration());

                                if (exoPlayer.getVideoFormat() != null) {
                                    Format videoFormat = exoPlayer.getVideoFormat();
                                    int width = videoFormat.width;
                                    int height = videoFormat.height;
                                    int rotationDegrees = videoFormat.rotationDegrees;
                                    // Switch the width/height if video was taken in portrait mode
                                    if (rotationDegrees == 90 || rotationDegrees == 270) {
                                        width = exoPlayer.getVideoFormat().height;
                                        height = exoPlayer.getVideoFormat().width;
                                    }
                                    event.put("width", width);
                                    event.put("height", height);
                                }
                                eventSink.success(event);

                            }
```

In video_player.dart  add new case in eventListener after line 250:
```
case 'changedVideo':
          value = value.copyWith(
            duration: Duration(milliseconds: map['duration']),
            size: Size(map['width']?.toDouble() ?? 0.0,
                map['height']?.toDouble() ?? 0.0),
          );
          break;
```

In video_player.dart Add nextVideo function to change media source:
```

**Comment by edufolly** [comment] 2019-03-27 12:13
Hi @leonetosoft,

how do you have to implement the Flutter app without the plugin changes? Can you share it?

If you prefer to talk in Portuguese, send me an email.

Thanks.

**Comment by leonetosoft** [comment] 2019-03-27 15:21
@edufolly 

Prefiro,

Você pode fazer **clone** do projeto **flutter/plugins** e aplicar as alterações em **plugins-master/packages/video_player/**

E refernciar **video_player** desta forma: 

pubspec.yaml
video_player:
    path: [YOUR PATH TO PLUGINS]/plugins-master/packages/video_player

Criei um repositório com as minhas alterações:
Repo: https://github.com/leonetosoft/flutter_video_player/
Commit: https://github.com/leonetosoft/flutter_video_player/commit/6d1b7d00573319f2f31f7857ba21bd3154a9a2af

**Comment by anhtu0101** [comment] 2019-06-20 08:29
@edufolly 
My code works for more than 15 minutes on Ios device (iPhone 6s) (I have just been able to test it in that time).
Repo: [https://github.com/anhtu0101/flutter_video_auto_play/blob/master/lib/video_player.dart](https://github.com/anhtu0101/flutter_video_auto_play/blob/master/lib/video_player.dart)
On Android, after running for 5-6 minutes, the following error is encountered:
Anybody help me find out where I was wrong, thank you verry much.

Error: 
`Introl --->
I/ExoPlayerImpl(28681): Init 6f3dfea [ExoPlayerLib/2.9.6] [vbox86p, Google Nexus 5X, Genymotion, 26]
I/zygote  (28681): Waiting for a blocking GC Alloc
I/zygote  (28681): Clamp target GC heap from 102MB to 96MB
I/zygote  (28681): Starting a blocking GC Alloc
D/SurfaceUtils(28681): connecting to surface 0xcf1a2808, reason connectToSurface
I/MediaCodec(28681): [OMX.google.h264.decoder] setting surface generation to 29369359
D/SurfaceUtils(28681): disconnecting from surface 0xcf1a2808, reason connectToSurface(reconnect)
D/SurfaceUtils(28681): connecting to surface 0xcf1a2808, reason connectToSurface(reconnect)
E/ACodec  (28681): [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec  (28681): codec does not support config priority (err -1010)
I/ACodec  (28681): codec does not support config priority (err -2147483648)
D/MediaCodec(28681): [OMX.google.h264.decoder] setting dataspace on output surface to #103
W/GrallocMapperPassthrough(28681): buffer descriptor with invalid usage bits 0x2000
D/        (28681): HostConnection::get() New Host Connection established 0xcfbd6f00, tid 22107
W/        (28681): Unrecognized GLES max version string in extensions: 
D/SoftwareRenderer(28681): setting dataspace on output surface to #103
E/AudioTrack(28681): AudioFlinger could not create track, status: -12
E/AudioTrack-JNI(28681): Error -12 initializing AudioTrack
E/android.media.AudioTrack(28681): Error code -20 when initializing AudioTrack.
E/ExoPlayerImplInternal(28681): Playback error.
E/ExoPlayerImplInternal(28681): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 82080)
E/ExoPlayerImplInternal(28681): 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:646)
E/ExoPlayerImplInternal(28681): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1355)
E/ExoPlayerImplInternal(28681): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
E/ExoPlayerImplInternal(28681): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(28681): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(28681): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/ExoPlayerImplInternal(28681): 	at android.os.Looper.loop(Looper.java:164)
E/ExoPlayerImplInternal(28681): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(28681): Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 82080)
E/ExoPlayerImplInternal(28681): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1128)
E/ExoPlayerImplInternal(28681): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:532)
E/ExoPlayerImplInternal(28681): 	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:593)
E/ExoPlayerImplInternal(28681): 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:640)
E/ExoPlayerImplInternal(28681): 	... 7 more
D/SurfaceUtils(28681): disconnecting from surface 0xcf1a2808, reason disconnectFromSurface
`

**Comment by iapicca** [comment] 2019-11-06 14:46
Hi @edufolly 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment] 2019-11-27 15:30
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-27 15:30 UTC
Labels: p: video_player, plugin, severe: crash, waiting for customer response
