### ISSUE TITLE
android studio not installed and android toolchain

### ISSUE THREAD

**Issue by SarausAlZoren** [flutter/flutter#68365] opened 2020-10-16 23:07 UTC
i already installed the android studio but i keep having this problem
![Untitled](https://user-images.githubusercontent.com/60129337/96321246-43bb4180-1047-11eb-88df-30e866f661a3.png)

**Comment by sidrao2006** [comment] 2020-10-17 05:49
Hey @SarausAlZoren , could you please check your version of Android Studio and post the output of `flutter doctor -v`

**Comment by hamdikahloun** [comment] 2020-10-17 07:51
Hi @SarausAlZoren 

This was reported in #67986, should be fixed soon in the stable channel with cherry-pick release

Thank you

**Comment by darshankawar** [comment] 2020-10-19 07:45
Could possibly related and duplicate of [67986](https://github.com/flutter/flutter/issues/67986) but to confirm this, please specify the Android Studio version you have installed.
Thanks.

**Comment by pedromassangocode** [comment] 2020-11-09 13:14
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-09 13:14 UTC
Labels: in triage
