### ISSUE TITLE
[Web] assets missing 404 Not Found

### ISSUE THREAD

**Issue by xzghx** [flutter/flutter#108252] opened 2022-07-24 18:00 UTC
Hi
I want to release a flutter web app and after ` flutter build web`, I get this error in console of chrome:
`main.dart.js:7422   GET http://localhost/MySiteName/assets/dotEnv.develop 404 (Not Found)`
but dotEnv.develop exsits in `assets/dotEnv.develop`.
I have created  dotEnv.develop file in root of my project and it contains this url that I'm going to change it to server url later: `baseUrl = 'localhost:80'`.
I've also added it to pubspec.yaml: 
```
  assets:
    - dotEnv.develop
```
In main.dart file I have called:
```
void main() async{
  timeDilation = 3; //slow down animations three times
  await dotenv.load(fileName: "dotEnv.develop");
  runApp(const MyApp());
}
```
and I use it this way:
```
import 'package:flutter_dotenv/flutter_dotenv.dart';
class Links {
 
  static   String baseUrl = dotenv.get('baseUrl')  ;
}
```
and I call  for http methods.
But the released app can not find dotEnv file. (in debug mode there is no problem)

**Comment by norbertkross** [comment] 2022-07-24 22:01
Check the release folder `/build/web/assets` and see if the file is there. You may have to include it there if it's not

**Comment by xzghx** [comment] 2022-07-25 05:25
Yes it already  exists in `/build/web/assets `

**Comment by xzghx** [comment] 2022-07-25 05:39
and this is whole log of chrome console:

```
(index):91 Failed to load app from service worker. Falling back to plain <script> tag.
(anonymous) @ (index):91
/payByAct/assets/dotEnv.develop:1          Failed to load resource: the server responded with a status of 404 (Not Found)
main.dart.js:41783 Error while trying to load an asset: Failed to load asset at "assets/dotEnv.develop" (404)
ajH @ main.dart.js:41783
main.dart.js:6562 Uncaught Instance of 'minified:Nc'
    at Object.c (http://localhost/payByAct/main.dart.js:4330:3)
    at http://localhost/payByAct/main.dart.js:74262:36
    at au1.a (http://localhost/payByAct/main.dart.js:5512:63)
    at au1.$2 (http://localhost/payByAct/main.dart.js:37650:14)
    at asW.$2 (http://localhost/payByAct/main.dart.js:37647:16)
    at a_p.EY (http://localhost/payByAct/main.dart.js:38490:33)
    at kH.afd (http://localhost/payByAct/main.dart.js:37843:18)
    at aos.$0 (http://localhost/payByAct/main.dart.js:37988:37)
    at Object.wM (http://localhost/payByAct/main.dart.js:5605:78)
    at ak.hB (http://localhost/payByAct/main.dart.js:37913:3)
```

**Comment by iapicca** [comment] 2022-07-25 06:09
maybe related to this https://github.com/flutter/flutter/issues/67655

**Comment by xzghx** [comment] 2022-07-25 07:11
So what should I do now? file exists but 404 error is given.

**Comment by iapicca** [comment] 2022-07-25 08:56
> So what should I do now? file exists but 404 error is given.

 change:

```yaml
assets:
    - dotEnv.develop
```

```dart
  await dotenv.load(fileName: "dotEnv.develop");
```

to 

```yaml
assets:
    - assets/dotEnv.develop
```
```dart
  await dotenv.load(fileName: "assets/dotEnv.develop");
```
(and move the files to the `assets` folder)

also [.env example](https://pub.dev/packages/flutter_dotenv/example) points at the same solution

**Comment by xzghx** [comment] 2022-07-26 07:21
@iapicca now gives this error:` Error while trying to load an asset: Failed to load asset at "assets/assets/dotEnv.develop" (404)`
thanks for your guide.
what is an alternative way to read strings for urls not hard coding them in deployed app?
is something like `config.php` file that we can change connection strings and urls in flutter?

**Comment by maheshmnj** [comment] 2022-07-27 12:26
Hi @xzghx, It looks like the flutter app is not able to find the assets. Taking a quick look at the [readme of the package](https://pub.dev/packages/flutter_dotenv) it seems to suggest that you need to create a file with `.env` extension which it isn't  (dotEnv.develop) So I believe that's the issue here.

Alternatively, You could try passing your variables to your app using `--dart-define` or by passing variables in vscode config https://dartcode.org/docs/using-dart-define-in-flutter/

**Comment by xzghx** [comment] 2022-07-28 08:09
Hi @maheshmnj, I changed the extension again it gives 404 error. It seems that file gets hidden for browser. I also tried this way of referencing:`  await dotenv.load(fileName: "fonts/.env");`
and then copy and pasted the .env file to `assets/fonts` folder which is located in `build/web/assets/fonts ` and It's hidden as this image shows.
![assets](https://user-images.githubusercontent.com/55482696/181296903-6c4a03a0-64cb-47d2-a638-6014e00da8d1.jpg)

I'm going to not use this package.
I'm using android studio. using `--dart-define` we can pass compile time variables. Is there any way to edit some variables after compile time(i.e after releasing)?

**Comment by exaby73** [comment] 2022-07-29 06:26
Hello @xzghx. I am unable to reproduce this issue. I have made a sample with `flutter_dotenv` which you can find below which might be able to help you. I have tested using Flutter's own [`rootBundle.loadString`](https://api.flutter.dev/flutter/services/AssetBundle/loadString.html), and it works as expected.

<details>
<summary>Code sample</summary>

##### lib/main.dart

```dart
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

final DotEnv rootEnv = DotEnv();
final DotEnv assetsDotFile = DotEnv();
final DotEnv assetsOther = DotEnv();

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await rootEnv.load(fileName: '.env');
  await assetsDotFile.load(fileName: 'assets/.env');
  await assetsOther.load(fileName: 'assets/dotEnv.develop');

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final fromRoot = rootEnv.get('SAMPLE');
    final fromAssetsDotFile = assetsDotFile.get('SAMPLE');
    final fromAssetsOther = assetsOther.get('SAMPLE');

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('fromRoot: $fromRoot'),
            const SizedBox(height: 20),
            Text('fromAssetsDotFile: $fromAssetsDotFile'),
            const SizedBox(height: 20),
            Text('fromAssetsOther: $fromAssetsOther'),
          ],
        ),
      ),
    );
  }
}
```

##### .env

```env
SAMPLE=From root
```

##### assets/.env

```dotenv
SAMPLE=From assets (.env)
```

##### assets/dotEnv.develop

```env
SAMPLE=From assets (dotEnv.develop)
```

##### pubspec.yaml

```yaml
name: issue_108252
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/dotEnv.develop
    - .env
```

</details>

<details>
<summary>Screenshot</summary>

<img width="600" alt="image" src="https://user-images.githubusercontent.com/50555895/181696404-d9585c71-52ce-403d-bb4c-e97e95f6cb78.png">

</details>

Hope this helps you. Since this is not a bug with Flutter, I am closing this issue. If you disagree, please comment and we can re-open it.

**Closed by exaby73** 2022-07-29 06:26 UTC
Labels: in triage
