### ISSUE TITLE
Flutter resizeToAvoidBottomInset true not working with Expanded ListView

### ISSUE THREAD

**Issue by saveKenny** [flutter/flutter#96279] opened 2022-01-07 11:31 UTC
I have implemented a chat screen using the above layout:
![Screenshot from 2022-01-07 13-20-55](https://user-images.githubusercontent.com/62389332/148536880-10aeb315-b209-4b20-a16e-4107b197885e.png)

For some reason, the `resizeToAvoidBottomInset: true` doesn't work (the keyboard hides the ListView).
![ezgif com-gif-maker(4)](https://user-images.githubusercontent.com/62389332/148537679-f0ebe519-7e30-4540-982e-2579b00ddecb.gif)

I have also created another application, with a different layout, that it works as expected:
![Screenshot from 2022-01-07 12-44-22](https://user-images.githubusercontent.com/62389332/148537326-1813f6ec-bc26-44ad-b039-aa199e074d45.png)

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on Ubuntu 18.04.6 LTS 5.4.0-91-generic, locale en_IL)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)
```
I have raised the issue in [StackOverflow](https://stackoverflow.com/q/70577942/12695188), there was no solution yet (but seems that people do facing this issue a lot).

What is the problem with my layout? Why `resizeToAvoidBottomInset` is not working?

**Comment by maheshmnj** [comment] 2022-01-07 12:53
Hi @saveKenny, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with output of `flutter doctor -v`.

Thanks

**Comment by saveKenny** [comment] 2022-01-07 13:36
Upgraded to `2.8.1`, still facing the same issue.

Adding the screen source code:
```
import 'package:now_club/utils/globals.dart' as globals;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:now_club/models/message_model.dart';
import 'package:now_club/models/group_model.dart';
import 'package:grouped_list/grouped_list.dart';
import 'package:now_club/network/network.dart';
import 'package:now_club/utils/functions.dart';
import 'package:now_club/utils/widgets.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'dart:ui' as ui;

class GroupScreen extends StatefulWidget {
  final String? friendName;
  final String? friendId;
  final String? availability;
  final String? friendToken;

  const GroupScreen(
      {this.friendName,
      this.friendId,
      this.availability,
      this.friendToken,
      Key? key})
      : super(key: key);

  @override
  _GroupScreen createState() => _GroupScreen();
}

class _GroupScreen extends State<GroupScreen> {
  final ScrollController _scrollController = ScrollController();
  late Function? updateLeaveTime;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() async {
    if (updateLeaveTime != null) updateLeaveTime!();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    String title = widget.friendName! +
        (widget.availability != null ? ' (${widget.availability})' : '');
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: widget.availability != null
            ? getColorByAvailability(widget.availability!)
            : null,
        title: Text(
          title,
          textDirection: Bidi.detectRtlDirectionality(title)
              ? ui.TextDirection.rtl
              : ui.TextDirection.ltr,
        ),
      ),
      body: StreamBuilder(
        stream: FirebaseFirestore.instance
            .collection('groups')
            .where('guests.${globals.user.userId}.guestId',
                isEqualTo: globals.user.userId)
            .where('guests.${widget.friendId!}.guestId',
                isEqualTo: widget.friendId!)
            .limit(1)
            .snapshots(),
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          if (snapshot.hasData) {
            SchedulerBinding.instance!.addPostFrameCallback((_) {
              if (_scrollController.hasClients) {
                _scrollController
                    .jumpTo(_scrollController.position.maxScrollExtent);
              }
            });
            List<DocumentSnapshot<Map<String, dynamic>>> docs =
                snapshot.data!.docs;
            if (docs.isNotEmpty) {
              Group group = Group.fromJson(docs[0].data()!);
              updateLeaveTime = () => updateGroupLeaveTime(docs[0].id, group);
              List<Message> messages = group.messages
                  .map((message) => Message.fromJson(message))
                  .take(100)
                  .toList();
              return Column(
                children: [
                  Expanded(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: GroupedListView<dynamic, String>(
                        controller: _scrollController,
                        keyboardDismissBehavior:
                            ScrollViewKeyboardDismissBehavior.onDrag,
                        physics: const BouncingScrollPhysics(
                            parent: AlwaysScrollableScrollPhysics()),
                        itemBuilder: (context, message) {
                          return ListTile(
                            title: ChatBubble(message),
                          );
                        },
                        elements: messages,
                        groupBy: (message) => DateFormat('MMMM dd,yyyy')
                            .format(message.timestamp.toDate()),
                        groupSeparatorBuilder: (String groupByValue) =>
                            getMiddleChatBubble(context, groupByValue),
                        itemComparator: (item1, item2) =>
                            item1.timestamp.compareTo(item2.timestamp),
                        useStickyGroupSeparators: false,
                        floatingHeader: false,
                        order: GroupedListOrder.ASC,
                      ),
                    ),
                  ),
                  WriteMessageBox(
                      group: group,
                      groupId: docs[0].id,
                      tokens: [widget.friendToken])
                ],
              );
            } else {
              Group group = Group(
                guests: {
                  globals.user.userId: {
                    'guestId': globals.user.userId,
                    'name': globals.user.name,
                  },
                  widget.friendId: {
                    'guestId': widget.friendId!,
                    'name': widget.friendName!,
                  }
                },
                leaveTime: {
                  globals.user.userId: Timestamp.now(),
                  widget.friendId!: Timestamp.now()
                },
                messages: [],
              );
              postGroup(group);
              return const Center(child: Text('Creating new group'));
            }
          } else {
            return const SizedBox();
          }
        },
      ),
    );
  }
}
```
Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 18.04.6 LTS 5.4.0-91-generic, locale en_IL)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)
```

**Comment by saveKenny** [comment] 2022-01-08 18:39
Any news?

**Comment by maheshmnj** [comment] 2022-01-10 06:25
Thanks for the code sample @saveKenny, This is working as intended since you have your ListView in Expanded widget, it will take up all the existing space regardless of value `resizeToAvoidBottomInset: true`.
Closing as this is working as intended.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: true,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: <Widget>[
            SizedBox(
              height: 600,
              child: ListView.builder(
                  itemCount: 100,
                  itemBuilder: (context, index) {
                    return ListTile(
                      title: Text('Item $index'),
                    );
                  }),
            ),
            const Padding(
              padding: EdgeInsets.symmetric(vertical: 16, horizontal: 8.0),
              child: TextField(),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

**Closed by maheshmnj** 2022-01-10 06:25 UTC
Labels: in triage

**Comment by saveKenny** [comment] 2022-01-10 08:39
Thanks @maheshmnj, My issue was solved by using `reverse: true` and `order: GroupedListOrder.DESC` in the `GroupedListView`. I understand why the `resizeToAvoidBottomInset` works as expected, but can you please explain to me why setting the `ListView` to `reverse: true` solved the issue? Who is it different from `reversed: false`?
