### ISSUE TITLE
TextField arrows up & down didn't work when change Align to center or right

### ISSUE THREAD

**Issue by AliWaleed441** [flutter/flutter#154279] opened 2024-08-28 17:52 UTC
### Steps to reproduce

1. Using TextField Widget.
2. Using TextAlign.center Or TextAlign.right.
3. Press on arrows up & down.

### Expected results

Curser must go to begin or end of text

### Actual results

An error has occurred and the message of error  is 

'package:flutter/src/rendering/editable.dart': Failed assertion: line 206 pos 12: 'isValid': is not true.

(elided 2 frames from class _AssertionError)
KeyMessage: KeyMessage([KeyDownEvent#4fac5(physicalKey: PhysicalKeyboardKey#583f3(usbHidUsage: "0x00070052", debugName: "Arrow Up"), logicalKey: LogicalKeyboardKey#88515(keyId: "0x100000304", keyLabel: "Arrow Up", debugName: "Arrow Up"), character: null, timeStamp: 1053:00:12.031630)])

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by services library ======================================================
The following assertion was thrown while processing the key message handler:
'package:flutter/src/rendering/editable.dart': Failed assertion: line 206 pos 12: 'isValid': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      VerticalCaretMovementRun.movePrevious (package:flutter/src/rendering/editable.dart:206:12)
#3      _UpdateTextSelectionVerticallyAction.invoke (package:flutter/src/widgets/editable_text.dart:5557:61)
#4      _OverridableContextAction.invokeDefaultAction (package:flutter/src/widgets/actions.dart:1811:28)
#5      _OverridableActionMixin.invoke (package:flutter/src/widgets/actions.dart:1676:9)
#6      Action._invoke (package:flutter/src/widgets/actions.dart:336:19)
#7      ActionDispatcher.invokeActionIfEnabled (package:flutter/src/widgets/actions.dart:666:28)
#8      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:851:83)
#9      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:1042:20)
#10     _HighlightModeManager.handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1837:32)
#11     KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:996:34)
#12     KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1061:17)
#13     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:223:49)
#14     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#15     _invoke2 (dart:ui/hooks.dart:344:13)
#16     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#17     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#18     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#19     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:722:22)
#20     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)
KeyMessage: KeyMessage([KeyDownEvent#4fac5(physicalKey: PhysicalKeyboardKey#583f3(usbHidUsage: "0x00070052", debugName: "Arrow Up"), logicalKey: LogicalKeyboardKey#88515(keyId: "0x100000304", keyLabel: "Arrow Up", debugName: "Arrow Up"), character: null, timeStamp: 1053:00:12.031630)])
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)                        
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)                  
[√] Chrome - develop for the web                                                
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.2.5)  
[√] Android Studio (version 2023.1)                                             
[√] IntelliJ IDEA Community Edition (version 2022.1)
[√] VS Code (version 1.87.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

```

</details>

**Comment by SuicaLondon** [comment] 2024-08-28 22:03
I have tested it on my iPad in iOS 17.5 and 18.0. Both of them work even in the dev mode. This issue seems to only happen on the Simulator.

**Comment by atkdef** [comment] 2024-08-29 07:00
Probably a duplication of #139201. 

It's been 3 quaters and it seems no one is fixing this.

**Comment by huycozy** [comment] 2024-08-29 07:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139201, please follow it for updates. Thanks!

**Closed by huycozy** 2024-08-29 07:25 UTC
Labels: in triage
