### ISSUE TITLE
[Web] CanvasKit not render circularprogressindicator

### ISSUE THREAD

**Issue by andredealmei** [flutter/flutter#46498] opened 2019-12-08 14:02 UTC
```bash
[√] Flutter (Channel master, v1.13.1-pre.59, on Microsoft Windows [versÃ£o 10.0.17763.864], locale pt-BR)
• Flutter version 1.13.1-pre.59 at C:\flutter
• Framework revision e58dc16 (8 hours ago), 2019-12-06 18:21:52 -0800
• Engine revision e7b69ced2e
• Dart version 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at C:\Users\usuario\AppData\Local\Android\sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-29, build-tools 29.0.2
• Java binary at: C:\android-studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.0)
• Android Studio at C:\android-studio
X Flutter plugin not installed; this adds Flutter specific functionality.
X Dart plugin not installed; this adds Dart specific functionality.
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.40.2)
• VS Code at C:\Users\usuario\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.7.0

[√] Connected device (2 available)
• Chrome • chrome • web-javascript • Google Chrome 78.0.3904.108
• Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment] 2019-12-09 09:39
possible duplicate of https://github.com/flutter/flutter/issues/45955

**Comment by andredealmei** [comment] 2019-12-09 10:19
I don't understand why this is a duplicity

**Comment by yjbanov** [comment] 2019-12-12 23:23
We just fixed an issue in `drawArc`, which might have caused this. Can you please try again on the latest master?

**Comment by andredealmei** [comment] 2019-12-13 11:40
its fixed now, thanks

**Closed** 2019-12-13 11:42 UTC
Labels: a: images, e: web_html, e: web_skia, engine, ☸ platform-web
