### ISSUE TITLE
Issue Running my Already Working Flutter Code

### ISSUE THREAD

**Issue by BillionaireMarumo** [flutter/flutter#87290] opened 2021-07-29 19:18 UTC
I think due to the upgrade, I'm having issues running my code. There's nothing more frustrating then almost releasing the work only to get errors which never occurred before.

Failed to start DevTools: Dart DevTools exited with code 127. env: bash: No such file or directory.

The Dart Analysis Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

This was never an issue and I've already made so much progress. I almost resorted to creating a new flutter project. This is a huge inconvenience to say the least. Please fix it. We have people to report to with our work.

**Comment by BillionaireMarumo** [comment] 2021-07-29 19:19
Please fix it as soon as possible or assist.

**Comment by iapicca** [comment] 2021-07-29 21:04
> I think due to the upgrade, I'm having issues running my code

@BillionaireMarumo 
does the code work on the flutter version you developed the project on? 

`flutter doctor -v`, `flutter run -v` and a code sample would be useful

**Comment by darshankawar** [comment] 2021-07-30 09:49
@BillionaireMarumo 
Please provide above requested details so that we can properly address this issue.
Thanks.

**Comment by BillionaireMarumo** [comment] 2021-07-30 10:51
It used to work until it complained about Dart analysis being an issue. I
get the error each time I try to run my code.

**Comment by darshankawar** [comment] 2021-07-30 11:30
@BillionaireMarumo 
As requested earlier too, we would need your `flutter doctor -v`, a minimal code sample that shows the issue you are describing. Just commenting about the issue won't help to determine the cause.
Thanks.

**Comment by BillionaireMarumo** [comment] 2021-07-30 12:18
Okay, I will do so when I get home.

Thanks

**Comment by BillionaireMarumo** [comment] 2021-08-01 09:27
Hi,

11:21 Dart analysis issue: Bad state: Suspected cycle. [(uri:
dart:nativewrappers, path:
/Users/marumotsesane/Downloads/flutter/bin/cache/pkg/sky_engine/lib/_empty.dart),
(uri: dart:nativewrappers/src/painting/alignment.dart, path:
/Users/marumotsesane/Downloads/flutter/bin/cache/pkg/sky_engine/lib/src/painting/alignment.dart),
(uri: dart:nativewrappers/src/painting/src/painting/alignment.dart, path:
/Users/marumotsesane/Downloads/flutter/bin/cache/pkg/sky_engine/lib/src/painting/src/painting/alignment.dart),
(uri:
dart:nativewrappers/src/painting/src/painting/src/painting/alignment.dart,
path:
/Users/marumotsesane/Downloads/flutter/bin/cache/pkg/sky_engine/lib/src/painting/src/painting/src/painting/alignment.dart),
(uri:
dart:nativewrappers/src/painting/src/painting/src/painting/src/painting/alignment.dart,
path:
/Users/marumotsesane/Downloads/flutter/bin/cache/pkg/sky_engine/lib/src/painting/src/painting/src/painting/src/painting/alignment.dart),
(uri: dart:nativewrappers/src/painting/src/painting/src/painting...

**Comment by BillionaireMarumo** [comment] 2021-08-01 10:11
[12:07:27 PM] [General] [Info] Searching for SDKs...
[12:07:27 PM] [General] [Info] Environment PATH:
[12:07:27 PM] [General] [Info]     /Users/marumotsesane/Downloads/flutter
[12:07:27 PM] [General] [Info] Found Flutter project at
/Users/marumotsesane/the-movers-moving-partner/the_movers_moving_partner:
Mobile? true
Web? false
Create Trigger? false
Flutter Repo? false
[12:07:27 PM] [General] [Info] Searching for flutter
[12:07:27 PM] [General] [Info]     Looking for flutter in:
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/the-movers-moving-partner/the_movers_moving_partner
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/the-movers-moving-partner/the_movers_moving_partner/bin
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/the-movers-moving-partner/the_movers_moving_partner/.flutter
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/the-movers-moving-partner/the_movers_moving_partner/.flutter/bin
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/the-movers-moving-partner/the_movers_moving_partner/vendor/flutter
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/the-movers-moving-partner/the_movers_moving_partner/vendor/flutter/bin
[12:07:27 PM] [General] [Info]         /Users/marumotsesane/flutter-sdk
[12:07:27 PM] [General] [Info]         /Users/marumotsesane/flutter-sdk/bin
[12:07:27 PM] [General] [Info]         /Users/marumotsesane/.flutter-sdk
[12:07:27 PM] [General] [Info]         /Users/marumotsesane/.flutter-sdk/bin
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin
[12:07:27 PM] [General] [Info]     Found at:
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin
[12:07:27 PM] [General] [Info]     Candidate paths to be post-filtered:
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter
[12:07:27 PM] [General] [Info]     Found at
/Users/marumotsesane/Downloads/flutter
[12:07:27 PM] [General] [Info]     Returning SDK path
/Users/marumotsesane/Downloads/flutter for flutter
[12:07:27 PM] [General] [Info] Searching for dart
[12:07:27 PM] [General] [Info]     Looking for dart in:
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk/bin
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk/bin
[12:07:27 PM] [General] [Info]     Found at:
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk/bin
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk/bin
[12:07:27 PM] [General] [Info]     Candidate paths to be post-filtered:
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter
[12:07:27 PM] [General] [Info]
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk
[12:07:27 PM] [General] [Info]     Found at
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk
[12:07:27 PM] [General] [Info]     Returning SDK path
/Users/marumotsesane/Downloads/flutter/bin/cache/dart-sdk for dart
[12:07:27 PM] [General] [Info] Experiment random number is 62 for
experiement 'lsp-default'. Experiment is enabled for <= 75
[12:07:27 PM] [General] [Info] Experiment 'lsp-default' is activating (not
first time)
[12:07:27 PM] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE
INFORMATION BEFORE SHARING !!

**Comment by iapicca** [comment] 2021-08-01 12:18
> `experiement 'lsp-default'. Experiment is enabled for <= 75`

@BillionaireMarumo 
seems that something made neovim upset
rather than a flutter problem

**Comment by BillionaireMarumo** [comment] 2021-08-01 12:43
Okay thank you for the update. How do I fix it?

**Comment by iapicca** [comment] 2021-08-01 16:58
@BillionaireMarumo 
flutter repo is not meant to provide assistance, but to report bugs or propose new features
if you need help try on [reddit](https://www.reddit.com/r/FlutterDev/), [discord](https://discord.gg/N7Yshp4) or [stackoverflow](https://stackoverflow.com/tags/flutter)

 if you think it's a bug please provide [these info](https://github.com/flutter/flutter/issues/87290#issuecomment-889830929)

**Comment by BillionaireMarumo** [comment] 2021-08-01 17:13
Thank you so much for the assistance.

**Comment by darshankawar** [comment] 2021-08-02 05:46
Closing this per above comments as this doesn't seem to be a Flutter issue.

**Closed by darshankawar** 2021-08-02 05:46 UTC
Labels: in triage
