### ISSUE TITLE
Image Picker plugin cannot work in Android Q devices

### ISSUE THREAD

**Issue by buaashuai** [flutter/flutter#31845] opened 2019-04-30 11:41 UTC
As we all known, Google published Android Q beta on May. Recently, we received some emails from some mainstream APP Stores to let our product adapt Android Q. After test, we found that the Image Picker plugin cannot get the correct file path after select images or videos in the Android gallery.

This problem happens because of the Android Q prohibit those Apps who access files out of their sandbox. The actual problem in the source code of the Image Picker plugin located in the FileUtils.java. As shown in the following figure:

![image](https://user-images.githubusercontent.com/11747264/56959398-dc25e380-6b7f-11e9-8e68-4af2bfdcd757.png)

Appreciate flutter team could solve this problem soon.

## Steps to Reproduce

1. I use the Image Picker plugin official demo in my Android Q beta device, the problem can easily appear.

## Logs

```
16:00:42.571 5 info flutter.tools I/flutter (28775): Another exception was thrown: FileSystemException: Cannot open file, path = '/mnt/content/media/external/images/media/1333' (OS Error: No such file or directory, errno = 2)

16:04:23.713 6 info flutter.tools I/flutter (28775): Another exception was thrown: FileSystemException: Cannot open file, path = '/mnt/content/media/external/images/media/4053' (OS Error: No such file or directory, errno = 2)

```

```

[✓] Flutter (Channel dev, v1.4.19, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
    • Flutter version 1.4.19 at /Users/weslywang/project/android/flutter
    • Framework revision 6c7b6833c9 (3 周前), 2019-04-12 10:40:18 -0400
    • Engine revision 9aa7c9a48e
    • Dart version 2.2.1 (build 2.2.1-dev.4.2 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/weslywang/Library/Android/sdk
    • Android NDK at /Users/weslywang/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/weslywang/Library/Android/sdk/platform-tools
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost,.oa.com
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • Pixel 2 • FA7AG1A03615 • android-arm64 • Android Q (API 28)


```

**Comment by KhatibFX** [comment] 2019-10-29 11:09
Any update on this? Thanks in advance.

**Comment by rahuldevgarg** [comment] 2020-01-27 17:28
Any Update?

**Comment by matskosan** [comment] 2020-02-10 20:10
Is there at least a workaround?

**Comment by KhatibFX** [comment] 2020-02-11 02:20
> Is there at least a workaround?

@matskosan in your Android manifest file, add the following line inside <application> tag:android: requestLegacyExternalStorage="true"

For more information, you can refer to this link: https://stackoverflow.com/questions/58379543/cant-create-directory-in-android-10

**Comment by VickySalunkhe** [comment] 2020-03-05 18:24
adding `requestLegacyExternalStorage="true"`
didn't help me resolve the image_picker issue to pick image on Android 10 devices.

What I did is downgraded `targetSdkVersion` and `compileSdkVersion` to 28 from 29
and that worked for me.

Meanwhile please Flutter team have a look at this issue as due to growing Android 10 devices count this issue is getting big day by day.

**Comment by otopba** [comment] 2020-04-09 21:18
Have same problem =/

**Comment by uzumaki258** [comment] 2020-04-16 16:09
I have build targetSdkVersion and compileSdkVersion are 28, but still have an error on some device:
Here is firebase crash log:
almost occur on GalaxyS7,8,9,10, Motorola, But about 1% of all my users.
![image](https://user-images.githubusercontent.com/26773292/79479458-fc6fdc00-8036-11ea-8528-556edd1d5849.png)

**Comment by GaryQian** [comment] 2020-10-19 22:22
It has been a while since the last update, is this still a problem?

**Comment by pedromassangocode** [comment] 2021-02-08 13:12
Hi @buaashuai 
I cannot reproduce this issue on latest stable channel with `image_picker: ^0.6.7+21`.

![gif](https://user-images.githubusercontent.com/67424416/107224201-6a96ec80-6a17-11eb-9dff-9c396cc8b174.gif)

I'm closing this as probably fixed. For anyone facing this same issue, please write in the comments bellow and I will reopen it.
Thank you

<details>
<summary>flutter doctor -v</summary>

```bash
/Users/pedromassango/Code/flutter_stable/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-AO)
    • Flutter version 1.22.6 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Closed by pedromassangocode** 2021-02-08 13:12 UTC
Labels: customer: crowd, e: OS Version specific, p: first party, p: image_picker, platform-android, plugin
