### ISSUE TITLE
Local echo disabled when closing Chrome window.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#105273] opened 2022-06-02 23:44 UTC
My terminal becomes unusable (local echo disabled?) when I close the Chrome instance that was opened by `flutter run -d chrome` on a flutter web app.

### Steps to reproduce:

1. Create a new flutter app
2. `flutter run -d chrome` in said app
3. Close the Chrome window that automatically opens
4. Type something in the terminal window that was used to run `flutter run -d chrome`
5. 💥 no local echo 💥

### Workarounds:

* I can reenable local echo by running `stty echo` in the affected terminal.
* I can close Chrome without triggering this problem by pressing Ctrl+C in the terminal that is running the flutter run.

## Logs

No interesting logs, added flutter doctor just for info, but I started noticing this in `master` today (not sure for how long it's been there)

<details>
<summary>Logs</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1077, on Debian GNU/Linux rodete 5.16.18-1rodete2-amd64, locale en_US.UTF-8)
    • Flutter version 3.1.0-0.0.pre.1077 at ~/github/flutter
    • Upstream repository git@github.com:ditman/flutter.git
    • Framework revision 6bc409af22 (19 minutes ago), 2022-06-02 19:23:08 -0400
    • Engine revision 6734def508
    • Dart version 2.18.0 (build 2.18.0-163.0.dev)
    • DevTools version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /usr/local/google/home/dit/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • Debian clang version 13.0.1-3+build2
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from
      https://cmake.org/download/
    • ninja version 1.8.2
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio-with-blaze-2020.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.67.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 5.16.18-1rodete2-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by ditman** [comment] 2022-06-02 23:47
Happens in `GNOME Terminal 3.44.0 for GNOME 42`

**Comment by christopherfujino** [comment] 2022-06-02 23:50
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/105255. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2022-06-02 23:50 UTC
Labels: tool
