### ISSUE TITLE
image_picker plugin causes Android app to crash

### ISSUE THREAD

**Issue by vikdenic** [flutter/flutter#27830] opened 2019-02-12 08:04 UTC
I installed the image_picker plugin into my project, and it works with iOS, But now the Android build crashes with the error:

FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
```

Any idea why the Android build crashes when using this plugin?

**Comment by zoechi** [comment] 2019-02-12 09:27
Duplicate of #23929

**Closed by zoechi** 2019-02-12 09:27 UTC

**Comment by phodonou** [comment] 2019-03-22 06:24
Using image picker 0.4.6: https://pub.dartlang.org/packages/image_picker/versions/0.4.6#-readme-tab- solves this
