### ISSUE TITLE
Crashlytics: EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000006a8

### ISSUE THREAD

**Issue by desmeit** [flutter/flutter#96768] opened 2022-01-18 10:47 UTC
I get this issue in crashlytics:

```
Crashed: com.apple.main-thread
0  Flutter                        0x3b8404 (Fehlt)
1  Flutter                        0x3e464 (Fehlt)
2  Flutter                        0x3c1f0 (Fehlt)
3  Flutter                        0x3c67ac (Fehlt)
4  Flutter                        0x3c6150 (Fehlt)
5  Flutter                        0x12b2c (Fehlt)
6  Flutter                        0xf1cc (Fehlt)
7  CoreFoundation                 0x2aed8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8  CoreFoundation                 0xc6b8c ___CFXRegistrationPost_block_invoke + 52
9  CoreFoundation                 0x99f44 _CFXRegistrationPost + 456
10 CoreFoundation                 0x40d44 _CFXNotificationPost + 716
11 Foundation                     0x1a628 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
12 UIKitCore                      0xf50e9c -[UIApplication _terminateWithStatus:] + 300
13 UIKitCore                      0x63bd14 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
14 UIKitCore                      0x830c5c -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 224
15 UIKitCore                      0xf4dae4 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
16 FrontBoardServices             0x4fc38 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 80
17 FrontBoardServices             0xa6b4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
18 FrontBoardServices             0x4fbd0 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 132
19 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
20 libdispatch.dylib              0x8118 _dispatch_block_invoke_direct + 264
21 FrontBoardServices             0xbf94 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
22 FrontBoardServices             0xb3d4 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
23 FrontBoardServices             0xf9e4 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
24 CoreFoundation                 0xbb020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
25 CoreFoundation                 0xcbce0 __CFRunLoopDoSource0 + 208
26 CoreFoundation                 0x5fe8 __CFRunLoopDoSources0 + 268
27 CoreFoundation                 0xb7f4 __CFRunLoopRun + 820
28 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
29 GraphicsServices               0x138c GSEventRunModal + 164
30 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
31 UIKitCore                      0x2987f4 UIApplicationMain + 2092
32 Runner                         0x58f4 main + 5 (AppDelegate.swift:5)
33 ???                            0x1004d5a24 (Fehlt)
```

Its since I use Flutter 2.8.1.

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale de-DE)
    • Flutter version 2.8.1 at /Users/XXX/development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

**Comment by mkay-42069** [comment] 2022-01-18 12:58
Is a known and already fixed bug, only needs to be pushed to beta/stable.
https://github.com/flutter/flutter/issues/96424

**Comment by danagbemava-nc** [comment] 2022-01-18 14:06
Hi @desmeit, thanks for reporting this. 

- Can you provide a list of devices that are affected by this? 
- Is it reproducible locally or only in production? 
- Which of the issues linked in https://github.com/flutter/flutter/issues/96768#issuecomment-1015385741 seem similar to yours? 

Thank you

**Comment by desmeit** [comment] 2022-01-18 14:10
Hi @danagbemava-nc 

![Bildschirmfoto 2022-01-18 um 15 08 28](https://user-images.githubusercontent.com/9454529/149952815-e0c87051-1d3a-436d-a46d-bd6e29e7cbfb.png)

I see it only in production (crashlytics).

I get `___CFXRegistrationPost_block_invoke` error.

**Comment by 6N5tr** [comment] 2022-01-18 19:57
> Is a known and already fixed bug, only needs to be pushed to beta/stable. #96424 #95844

How can I do that? Could you give me an example plz. I need to fix this problem as soon as possible.

**Comment by danagbemava-nc** [comment] 2022-01-19 07:24
The logs seem similar to https://github.com/flutter/flutter/issues/95844 which has been fixed and should be available on the latest master channel. There's a cherry-pick request on https://github.com/flutter/flutter/issues/95844 for it to be added into the next beta/stable, but in the meantime @6N5tr, you may switch to the master branch, although, it is not recommended for release builds. 

I would advise anyone facing this issue to wait until it is rolled out into stable/beta. 

Closing from here as duplicate of https://github.com/flutter/flutter/issues/95844. 

Thank you

**Closed by danagbemava-nc** 2022-01-19 07:24 UTC
Labels: in triage
