### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\Users\seyed\.jdks\corretto-17.0.6\bin\bin\java" in the search path. Command: C:\Users\seyed\.jdks\corretto-17.0.6\bin\bin\java, OS error code: 0

### ISSUE THREAD

**Issue by seyed0123** [flutter/flutter#142912] opened 2024-02-05 13:23 UTC
## Command
```
flutter create p
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "C:\Users\seyed\.jdks\corretto-17.0.6\bin\bin\java" in the search path. Command: C:\Users\seyed\.jdks\corretto-17.0.6\bin\bin\java, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:714:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:377:51)
#5      Java.version.<anonymous closure> (package:flutter_tools/src/android/java.dart:139:44)
#6      Java.version (package:flutter_tools/src/android/java.dart:179:5)
#7      Java.version (package:flutter_tools/src/android/java.dart)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:510:41)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.19045.2728], locale en-US)
    [32m•[39m Flutter version 3.16.2 on channel stable at F:\flutter_windows_3.10.1-stable\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 9e1c857886 (10 weeks ago), 2023-11-30 11:51:18 -0600
    [32m•[39m Engine revision cf7a9d0800
    [32m•[39m Dart version 3.2.2
    [32m•[39m DevTools version 2.28.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    [32m•[39m Android SDK at F:\flutter_windows_3.10.1-stable\sdk
    [32m•[39m Platform android-33, build-tools 30.0.2
    [32m•[39m Java binary at: C:\Users\seyed\.jdks\corretto-17.0.6\bin\bin\java
    [31m✗[39m Cannot execute C:\Users\seyed\.jdks\corretto-17.0.6\bin\bin\java to determine the version

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2022.2)
    [32m•[39m IntelliJ at F:\IntelliJ IDEA 2022.2
    [32m•[39m Flutter plugin version 70.0.5
    [32m•[39m Dart plugin version 222.3345.108

[32m[✓][39m VS Code, 64-bit edition (version unknown)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 3.80.0
    [31m✗[39m Unable to determine VS Code version.

[32m[✓][39m Connected device (4 available)
    [32m•[39m 22101320G (mobile) • 6ba59e0c • android-arm64  • Android 13 (API 33)
    [32m•[39m Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    [32m•[39m Chrome (web)       • chrome   • web-javascript • Google Chrome 121.0.6167.140
    [32m•[39m Edge (web)         • edge     • web-javascript • Microsoft Edge 121.0.2277.98

[33m[!][39m Network resources
    [31m✗[39m A cryptographic error occurred while checking "https://github.com/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware
      installed on your computer.

[33m![39m Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by dam-ease** [comment] 2024-02-05 14:09
Hello @seyed0123 
This is a duplicate of https://github.com/flutter/flutter/issues/139180, which was already just fixed in https://github.com/flutter/flutter/pull/139614 and has been nominated for cherrypicking into stable at https://github.com/flutter/flutter/issues/139699.

Kindly upgrade to the latest version of flutter stable (3.16.9).

Closing from here. If you still face this issue after upgrading to the latest version of flutter stable, kindly leave a comment below with the crash log and the updated output of flutter doctor -v and I will reopen this.

Thank you

**Closed by dam-ease** 2024-02-05 14:09 UTC
Labels: in triage
