### ISSUE TITLE
How to provide elevation or shadow to the text or image drawn in the canvas

### ISSUE THREAD

**Issue by DeviArunaMurugan** [flutter/flutter#74808] opened 2021-01-27 13:08 UTC
I want provide shadow or elevation to text and image drawn on the canvas. For path, I have achieved it using the below method,
```dart
canvas.drawShadow(path, Colors.black, 6, true);
```
I have drawn text and an image using the below methods respectively

``` dart
canvas.drawImageNine(image, rect, rect, paint);
```
```dart
TextPainter textPainter = TextPainter(
        text: text,
        textDirection: TextDirection.ltr,
        textAlign: TextAlign.center);
textPainter.paint( canvas, Offset(-10, -10));
````

How to provide elevation support for image and text, while drawn those using the above method?

**Comment by TahaTesser** [comment] 2021-01-27 15:04
Hi @DeviArunaMurugan 
it might be possible but this needs to be explained how it works. 
Duplicate of https://github.com/flutter/flutter/issues/48027
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-27 15:04 UTC
