### ISSUE TITLE
localeListResolutionCallback called with non deterministic parameter value

### ISSUE THREAD

**Issue by marcelderkskarlmax** [flutter/flutter#57513] opened 2020-05-18 18:25 UTC
Device : iPhone 7 
OS: iOS 13.7

There seems to be a race condition at app startup that leads the `locales` parameter in the `localListResolutionCallback` to be sometimes set and sometimes not set.

When opening and closing the app multiple times, at some startups the `locales` parameter has the correct value set and sometimes it is null or empty. This bug only appeared on iOS and only in the Release build of the app. So until now I was not able to track this bug while attached to cable which makes it hard to debug. So I don't know the exact state of that parameter.

The only workaround that I found by now is to run the `MaterialApp` widget with a little delay.

Code snippet:

```
@override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => CalendarNotifier()),
        Provider(create: (_) => TooltipManager()),
      ],
      child: Consumer<CalendarNotifier>(
        builder: (context, counter, _) {
          return MaterialApp(
            title: 'MyApp',
            home: const SplashScreen(selectedBottomBarIndex: BottomBarPage.myTab),
            localizationsDelegates: const [
              MyLocalizationsDelegate(),
              GlobalMaterialLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
            ],
            localeListResolutionCallback: _localeListResolutionCallback,
            routes: {
              SplashScreen.routeName: (_) => const SplashScreen(),
            },
          );
        },
      ),
    );
  }

  Locale _localeListResolutionCallback(List<Locale> locales, Iterable<Locale> supportedLocales) {
   
 // this variable appears to be sometimes set and sometimes not
   if (locales?.isEmpty ?? true) {
      return Locale('en', 'US');
    }

   /// removed code
  }
```

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale de-DE)
    • Flutter version 1.17.0 at /Applications/flutter
    • Framework revision e6b34c2b5c (2 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/marcelderks/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1
```
</details>

**Comment by VladyslavBondarenko** [comment] 2020-06-19 12:31
May be related to https://github.com/flutter/flutter/issues/55642

**Comment by TahaTesser** [comment] 2020-09-01 12:44
Hi @marcelderkskarlmax 
Probably why it's not setting locale is because doesn't return empty locale list but returns `en` locale by default even when the locale is not set in the MaterialApp

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:i18n_example/generated/i18n.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final i18n = I18n.delegate;

    return MaterialApp(
      onGenerateTitle: (context) => I18n.of(context).title,
      theme: ThemeData.dark(),
      home: Home(),
      // locale: Locale('za', 'CH'),
      localizationsDelegates: [
        i18n,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      // supportedLocales: i18n.supportedLocales,

      localeListResolutionCallback: _localeListResolutionCallback,
      // localeResolutionCallback: i18n.resolution(
      //   fallback: Locale('en', 'US'),
      // ),
    );
  }

  Locale _localeListResolutionCallback(
      List<Locale> locales, Iterable<Locale> supportedLocales) {
    // this variable appears to be sometimes set and sometimes not
    print('locales $locales');
    if (locales?.isEmpty ?? true) {
      return Locale('zh', 'CH');
    }

    return null;

    /// removed code
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(I18n.of(context).title),
      ),
      body: Center(
        child: Container(
          child: Text(I18n.of(context).greetTo('World!')),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS
      13.6.1
    • iPhone 11 (mobile)     • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

</details> 


Are you still experiencing this issue? 
If yes, Can you please provide your `flutter doctor -v` with latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using third party packages 
Thank you

**Comment by pedromassangocode** [comment] 2020-09-23 13:32
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-09-23 13:32 UTC
Labels: a: internationalization, f: material design, framework, platform-ios, waiting for customer response
