### ISSUE TITLE
iOS App Submission - Swift folder missing

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#8075] opened 2017-02-11 06:19 UTC
After submitting my app to the Apple App store I get an email that says:

Invalid Swift Support - The SwiftSupport folder is missing
I have not mucked with Swift at all in my Flutter project, only Objective-C, so I don't want Swift.

This overflow says to set "Embedded Content Contains Swift Code" to NO in Build Options. 
http://stackoverflow.com/questions/32559204/invalid-swift-support-the-swiftsupport-folder-is-empty

I haven't found that option yet. I do have one called, "Always Embed Swift Standard Libraries" and that is already set to "NO"... Not sure if that's what is being referred, but atm don't have a way to fix this issue.

I also tried "export for App store", and used Application Loader to upload the file, same error.

## Steps to Reproduce

Submit app to app store.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/joel/dev_3rd/flutter
    • Framework revision 198d293857 (9 hours ago), 
    • Engine revision f306a6f701
    • Tools Dart version 1.22.0-dev.10.6

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/joel/dev_3rd/android-sdk-macosx/
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /Users/joel/dev_3rd/android-sdk-macosx/
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer/
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.0

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin version 163.7743.25
    • Flutter plugin version 0.1.5

[✓] Connected devices

**Comment by jtrunick** [comment] 2017-02-11 21:05
I've also tried setting the "Always Embed Swift Standard Libraries" to NO - ${inherited} w/the same error

**Comment by jtrunick** [comment] 2017-02-14 19:43
any ideas? anything I can try?

**Comment by cbracken** [comment] 2017-02-15 00:58
Question -- are you using any third-party libraries (e.g., via CocoaPods)?

**Comment by jtrunick** [comment] 2017-02-16 04:15
I'm using the Superpowered library : http://superpowered.com/
which has me including these libraries
MediaPlayer.framework
AVFoundation.framework

I didn't seem to have to touch anything to get it to work past adding those... such as the arch list.

**Comment by eseidelGoogle** [comment] 2017-02-16 23:07
I believe @cbracken is on this?

**Comment by jtrunick** [comment] 2017-02-20 19:56
I suppose my next try will be to force Swift to be included, but seems a shame, since afaict there's no Swift anywhere.

**Comment by cbracken** [comment] 2017-03-14 21:17
@jtrunick any luck on this?

**Comment by vlidholt** [comment] 2017-03-17 23:28
I'm having the same issue. The only included pod is the Google sign in pod. This may be a possible solution: http://stackoverflow.com/questions/38981628/invalid-swift-support-the-swiftsupport-folder-is-missing-with-xcode-7-3-1

**Comment by eseidelGoogle** [comment] 2017-03-17 23:43
@vlidholt Fantastic!  I think @cbracken was just looking for someone who could repro to work with.

**Comment by vlidholt** [comment] 2017-03-18 00:23
@eseidelGoogle Happy to help, how do I get in touch with @cbracken?

**Comment by cbracken** [comment] 2017-03-18 04:43
This bug works, or cbracken@google.com :-)

**Comment by vlidholt** [comment] 2017-03-18 19:15
I naturally tried adding Swift support by adding a Swift file, got another error when uploading to the App Store:

__Invalid Swift Support__ - The files libswiftDarwin.dylib, libswiftDispatch.dylib, libswiftCoreGraphics.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftObjectiveC.dylib aren’t at the expected location /Payload/Runner.app/Frameworks. Move the file to the expected location, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

**Comment by vlidholt** [comment] 2017-03-18 19:39
Tested on a clean project, created with `flutter create`, same thing when uploading it to the App Store, so it's not related to any 3rd party libraries.

**Comment by cbracken** [comment] 2017-03-21 20:24
I'm able to repro this with a local app. The underlying issue is likely the [inclusion of app.dylib](//apple_ref/doc/uid/DTS40017543-CH1-TROUBLESHOOTING_BUNDLE_ERRORS-EMBEDDED__DYLIB_FILES) in the app bundle.

**Comment by cbracken** [comment] 2017-03-21 23:13
Update: the inclusion of `app.dylib` was the issue. I was able to cobble together a manual workflow to build the dylib as a framework, and was able to successfully upload to the App Store. I'm working on a patch to our build now.

**Comment by cbracken** [comment] 2017-03-23 00:52
I've landed a patch which eliminates the use of a raw dylib and builds a framework instead. See the steps in #8971 to migrate existing Xcode projects. Once those steps are done, you should be able to do the following steps to push a build to the App Store:
1. On the command line, run `flutter build ios --release`.
1. Close & re-open the Xcode project to pick up the mode change (Xcode 8.3 will eliminate the need to close & re-open when it's out).
1. Select *Runner* > *Generic iOS Device* from the target menu in the toolbar.
1. Ensure you've set an unused Build number in your project settings *General* tab.
1. Select *Archive* from the *Product* menu.
1. The Organizer window will open. Ensure the new build is selected and click the *Validate...* button. Ensure everything looks good.
1. Click *Upload to App Store...*. You should receive an email back within 10-15 minutes with the status of the build.

**Comment by cbracken** [comment] 2017-03-23 16:42
Alright; confirmation from @vlidholt in the Gitter chat today that he was able to upload to the App Store. Marking as fixed. @jtrunick please re-open if you're still hitting this issue after a `flutter update` and following the steps above.

**Closed by cbracken** 2017-03-23 16:42 UTC
Labels: ⌺‬ platform-ios

**Comment by jtrunick** [comment] 2017-03-24 14:23
works!

**Comment by cbracken** [comment] 2017-03-24 17:01
Fantastic! Glad to hear it. Thanks for confirming!

**Comment by SumitDextrous** [comment] 2020-01-16 04:35
hi,
when i submit flutter app on app store, build upload successfully uploaded, but after that apple store given me issue. 
ITMS-90424: Invalid Swift Support - The SwiftSupport folder is empty. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

**Comment by eseidelGoogle** [comment] 2020-01-16 15:15
@SumitDextrous this is a very old issue.  I suspect the cause of this message could be different 3 years later.

Would you be willing to file a new issue with more information (e.g. flutter doctor output)?  We'd love to help.  Thanks.

**Comment by SumitDextrous** [comment] 2020-01-23 05:29
![Screenshot 2020-01-22 at 3 42 22 PM](https://user-images.githubusercontent.com/54306495/72959093-439b5780-3dcf-11ea-8a25-8e36dfd64c3e.png)
 
ITMS-90424: Invalid Swift Support - The SwiftSupport folder is empty. Rebuild your app using the current public (GM) version of Xcode and resubmit it

**Comment by ir2pid** [comment] 2020-04-22 21:17
same for us, any one found a solution?

**Comment by Marek00Malik** [comment] 2020-05-02 10:31
Did anyone manage to fix this not by using the XCode Upload tool?
I'm using code magic and would much appreciate using it in my CI instead of manually doing thing in XCode

**Comment by liudonghua123** [comment] 2020-06-12 03:16
I have the same issue, when I build with fastlane and upload to testflight. I got the following errors in the email.

I can confirm that I did not use these features.

```

Dear Developer,We identified one or more issues with a recent delivery for your app, "colorful-classroom-app" 1.0.0 (1). Please correct the following issues, then upload again.ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSContactsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSAppleMusicUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSMotionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSSpeechRecognitionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).Though you are not required to fix the following issues, we wanted to make you aware of them:ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.ITMS-90191: Missing beta entitlement - Your app does not include the beta-reports-active entitlement. If you intend to distribute this build via TestFlight for beta testing, please re-build this app with an App Store Distribution provisioning profile. Do not use ad-hoc profiles.ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).Best regards,The App Store Team
--



```

**Comment by kyryloz** [comment] 2021-05-31 15:53
I have the same issue with two different applications on two different dev machines. I'm using fastlane tools (`pilot` action) to upload the build to the TestFlight.

```
ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
```

```
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.2.0 at /Users/kzapylaiev/Library/flutter
    • Framework revision b22742018b (2 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/kzapylaiev/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/kzapylaiev/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```
