### ISSUE TITLE
Flutter Material Icons Suddenly Changed (Android)

### ISSUE THREAD

**Issue by brunodmn** [flutter/flutter#83370] opened 2021-05-25 20:13 UTC
HI, recently all my Material Icons changed for other random icons, even the leading of Scaffold Appbar icon (which is implicity in my case), changed for some another random icon. 
I do not now how to reproduce this.
I already tried:
1. `flutter cache repair`
2. `flutter clean` (many times)
3. `flutter channel dev` + `flutter upgrade`
4. uninstall several vscode extensions and downgrade packages

I use Linux Mint (Ubuntu) and VSCode for development.

Bellow my `flutter doctor -v`.

> [✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_US.UTF-8)
>     • Flutter version 2.2.0 at /home/bruno/_development/flutter
>     • Framework revision b22742018b (11 days ago), 2021-05-14 19:12:57 -0700
>     • Engine revision a9d88a4d18
>     • Dart version 2.13.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /home/bruno/Android/Sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at google-chrome
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • clang version 10.0.0-4ubuntu1
>     • cmake version 3.16.3
>     • ninja version 1.10.0
>     • pkg-config version 0.29.1
> 
> [✓] Android Studio
>     • Android Studio at /snap/android-studio/current/android-studio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • android-studio-dir = /snap/android-studio/current/android-studio
>     • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
> 
> [✓] VS Code (version 1.56.2)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.22.0
> 
> [✓] Connected device (3 available)
>     • Mi A2 (mobile)  • 2828ca6d • android-arm64  • Android 10 (API 29)
>     • Linux (desktop) • linux    • linux-x64      • Linux
>     • Chrome (web)    • chrome   • web-javascript • Google Chrome 90.0.4430.212
> 
> • No issues found!

I am not expecting much help, as there is little information on how to reproduce it, but any clues guys? Has happened with someone else?

**Comment by i3games** [comment] 2021-05-25 20:55
This is very likely the same issue as https://github.com/flutter/flutter/issues/83208 

This affects Flutter Android, iOS and Web, including published apps. Maybe someone can upvote these reports.

**Comment by guidezpl** [comment] 2021-05-26 08:19
Please see my [comment](https://github.com/flutter/flutter/issues/83208#issuecomment-848568614)

**Comment by TahaTesser** [comment] 2021-05-26 08:34
@brunodmn 
Closing as duplicate of https://github.com/flutter/flutter/issues/83208
Please follow up there, thank you

**Closed by TahaTesser** 2021-05-26 08:34 UTC
Labels: in triage
