### ISSUE TITLE
please help MainActivity.kt: (3, 19): Unresolved reference: embedding ,MainActivity.kt: (5, 21): Unresolved reference: FlutterActivity

### ISSUE THREAD

**Issue by maxmodlol** [flutter/flutter#81945] opened 2021-05-06 01:42 UTC
![github](https://user-images.githubusercontent.com/83738812/117230258-5b141d80-ae25-11eb-9514-7ef5356e0c15.PNG)
please help i could not find any solution and its my graduation project it happend i think when i did flutter upgrade --force and when i used firebase

**Comment by devmgs** [comment] 2021-05-06 07:44
instead of filling a bug stackoverflow was a better choice.

**Comment by darshankawar** [comment] 2021-05-06 08:14
Closing this as self-duplicate of https://github.com/flutter/flutter/issues/81944

**Closed by darshankawar** 2021-05-06 08:14 UTC
Labels: in triage

**Comment by devmgs** [comment] 2021-05-06 11:25
If this is only a graduation project best bet is create a new project in another folder with same name and copy and paste lib and assets in that folder this way you will get it working in less time without thinking much about what happened behind the scene.
