### ISSUE TITLE
Flutter integration_test produces an error while generating screenshot on web

### ISSUE THREAD

**Issue by sbis04** [flutter/flutter#86985] opened 2021-07-24 14:22 UTC
## Steps to Reproduce

1. Followed the instructions [here](https://github.com/blasten/flutter/blob/754dac8b4b9c8867e9cb6865bced5e1bb014ccf6/packages/integration_test/README.md#screenshots) to write a test for generating screenshots on Web.
2. Ran the chromedriver using:

   ```sh
   ./chromedriver --port=4444
   ```

3. Ran the test using the following command (the app is a default counter app):

   ```sh
   flutter drive \
     --driver=test_driver/integration_test.dart \
     --target=integration_test/screenshot_test.dart \
     -d web-server
   ```

**Actual results:**

It produces some error:

```sh
Running "flutter pub get" in screenshot_integration_demo...        795ms
Launching integration_test/screenshot_test.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         15.0s
integration_test/screenshot_test.dart is being served at http://localhost:55486
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[INFO]: http://localhost:55486/ 58:26 "Installed new service worker."
[WARNING]: http://localhost:55486/dart_sdk.js 48704:16 "registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[WARNING]: http://localhost:55486/dart_sdk.js 48686:16 "postEvent() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[INFO]: http://localhost:55486/dart_sdk.js 27192:14 "00:00 +0: screenshot"
result {"result":"true","failureDetails":[],"data":{"screenshots":[{"bytes":[]}]}}
Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0      integrationDriver (package:integration_test/integration_test_driver_extended.dart:100:60)
<asynchronous suspension>
#1      main (file:///Users/souvikbiswas/Mobile%20Dev/Flutter/screenshot_integration_demo/test_driver/integration_test.dart:5:3)
<asynchronous suspension>
Application finished.
```

But it still generates the screenshot and saves it locally.

<details>
  <summary>Logs</summary>

```
[ +133 ms] executing: sysctl hw.optional.arm64
[  +33 ms] Exit code 0 from: sysctl hw.optional.arm64
[   +4 ms] hw.optional.arm64: 1
[   +7 ms] executing: [/Users/souvikbiswas/fvm/versions/master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 41497f958740fc0aa0371dd5061b088308397d92
[   +1 ms] executing: [/Users/souvikbiswas/fvm/versions/master/] git tag --points-at 41497f958740fc0aa0371dd5061b088308397d92
[  +70 ms] Exit code 0 from: git tag --points-at 41497f958740fc0aa0371dd5061b088308397d92
[   +3 ms] executing: [/Users/souvikbiswas/fvm/versions/master/] git describe --match *.*.* --long --tags 41497f958740fc0aa0371dd5061b088308397d92
[  +90 ms] Exit code 0 from: git describe --match *.*.* --long --tags 41497f958740fc0aa0371dd5061b088308397d92
[        ] 2.4.0-4.0.pre-180-g41497f9587
[  +15 ms] executing: [/Users/souvikbiswas/fvm/versions/master/] git rev-parse --abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/souvikbiswas/fvm/versions/master/] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +155 ms] executing: [/Users/souvikbiswas/fvm/versions/master/] git rev-parse --abbrev-ref HEAD
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +9 ms] executing: sw_vers -productName
[  +20 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +19 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.2.3
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20D91
[  +64 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +68 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] executing: sysctl hw.optional.arm64
[  +13 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -version
[ +709 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun xcodebuild -version
[        ] Xcode 12.5.1
           Build version 12E507
[ +106 ms] Skipping pub get: version match.
[  +60 ms] Found plugin integration_test at /Users/souvikbiswas/fvm/versions/master/packages/integration_test/
[ +109 ms] Found plugin integration_test at /Users/souvikbiswas/fvm/versions/master/packages/integration_test/
[   +7 ms] Generating /Users/souvikbiswas/Mobile Dev/Flutter/screenshot_integration_demo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[+22243 ms] Launching lib/main.dart on Chrome in debug mode...
[ +150 ms] Updating assets
[ +102 ms] Waiting for connection from debug service on Chrome...
[  +17 ms] Found plugin integration_test at /Users/souvikbiswas/fvm/versions/master/packages/integration_test/
[  +14 ms] Found plugin integration_test at /Users/souvikbiswas/fvm/versions/master/packages/integration_test/
[  +37 ms] <- reset
[   +8 ms] /Users/souvikbiswas/fvm/versions/master/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/souvikbiswas/fvm/versions/master/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/souvikbiswas/fvm/versions/master/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/k8/w_zts_vj42918q45xx73vqtr0000gn/T/flutter_tools.8BImJW/flutter_tool.bsBhAq/app.dill --libraries-spec file:///Users/souvikbiswas/fvm/versions/master/bin/cache/flutter_web_sdk/libraries.json --packages
/Users/souvikbiswas/Mobile Dev/Flutter/screenshot_integration_demo/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/var/folders/k8/w_zts_vj42918q45xx73vqtr0000gn/T/flutter_tools.8BImJW/flutter_tools.3yOhIE --filesystem-scheme org-dartlang-app --initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///Users/souvikbiswas/fvm/versions/master/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +43 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+13809 ms] Waiting for connection from debug service on Chrome... (completed in 13.9s)
[  +10 ms] Synced 26.1MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[ +173 ms] Using Google Chrome 91.0.4472.164 

[  +23 ms] executing: sysctl hw.optional.arm64
[  +18 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +43 ms] Found ARM Chrome installation at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome, forcing native launch.
[+3023 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:58982/devtools/browser/d5e0368c-84da-4ed1-b741-0583d7ae3262
[ +959 ms] DwdsInjector: Received request for entrypoint at http://localhost:58944/main_module.bootstrap.js
[   +8 ms] MetadataProvider: Loading debug metadata...
[  +29 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +33 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:58944/main_module.bootstrap.js
[+1471 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[ +160 ms] DevHandler: Debug service listening on ws://127.0.0.1:59055/rgMswcvywcE=/ws

[  +35 ms] This app is linked to the debug service: ws://127.0.0.1:59055/rgMswcvywcE=/ws
[  +10 ms] Debug service listening on ws://127.0.0.1:59055/rgMswcvywcE=/ws
[        ] 💪 Running with sound null safety 💪
[   +6 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:59055/rgMswcvywcE=
[+1198 ms] Activating Dart DevTools...
[+10388 ms] Activating Dart DevTools... (completed in 10.4s)
[ +688 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9104?uri=http://127.0.0.1:59055/rgMswcvywcE=
```

```
Analyzing screenshot_integration_demo...                                
No issues found! (ran in 2.6s)
```

```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.180, on macOS 11.2.3 20D91 darwin-arm, locale en-IN)
    • Flutter version 2.4.0-5.0.pre.180 at /Users/souvikbiswas/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41497f9587 (7 hours ago), 2021-07-24 03:13:03 -0400
    • Engine revision 4a1bc7329e
    • Dart version 2.14.0 (build 2.14.0-349.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/souvikbiswas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

</details>

**Comment by sbis04** [comment] 2021-07-24 15:37
## Update

I tried adding a print statement for `screenshotName` to the `integration_test.dart` file:

```dart
import 'dart:io';
import 'package:integration_test/integration_test_driver_extended.dart';

Future<void> main() async {
  await integrationDriver(
    onScreenshot: (String screenshotName, List<int> screenshotBytes) async {
      print('NAME: $screenshotName'); // this one
      final File image = File('$screenshotName.png');
      image.writeAsBytesSync(screenshotBytes);
      // Return false if the screenshot is invalid.
      return true;
    },
  );
}
```

And made a small change to the `integration_test_driver_extended.dart` file so that Null String is related by an empty String:

```dart
final String screenshotName = (data['screenshotName'] as String?) ?? '';
```

It produces the following logs:

```bash
Running "flutter pub get" in screenshot_integration_demo...        748ms
Launching integration_test/screenshot_test.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         15.4s
integration_test/screenshot_test.dart is being served at http://localhost:52181
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[INFO]: http://localhost:52181/ 58:26 "Installed new service worker."
[WARNING]: http://localhost:52181/dart_sdk.js 48704:16 "registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[WARNING]: http://localhost:52181/dart_sdk.js 48686:16 "postEvent() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[INFO]: http://localhost:52181/dart_sdk.js 27192:14 "00:00 +0: screenshot"
NAME: screenshot-test
result {"result":"true","failureDetails":[],"data":{"screenshots":[{"bytes":[]}]}}
NAME: 
All tests passed.
Application finished.
```

Notice in the above logs, first the name is printed correctly but then it prints the empty String. I also don't understand why is the print statement called twice.

**Comment by darshankawar** [comment] 2021-07-26 10:19
@sbis04 
Thanks for the detailed report. I am getting below compile error while trying to implement your code sample:

<img width="937" alt="Screenshot 2021-07-26 at 3 48 05 PM" src="https://user-images.githubusercontent.com/67046386/126973420-4d8243cf-f595-42b0-9495-a6f3901223a7.png">

If I apply as suggested, it gives me error on `binding.takescreenshot()`.

**Comment by sbis04** [comment] 2021-07-26 10:48
@darshankawar ohh I guess that readme is not updated, try like this:

```dart
final IntegrationTestWidgetsFlutterBinding binding = IntegrationTestWidgetsFlutterBinding();
```

**Comment by darshankawar** [comment] 2021-07-27 06:22
@sbis04 Thanks.
I tried running a sample app with above changes, but observed the app getting stuck on first screen, doesn't throw any error and get below in console if I use `screenshot` related code:

```
void main() {
  final IntegrationTestWidgetsFlutterBinding binding = IntegrationTestWidgetsFlutterBinding();

  testWidgets(
      'Verify login functionality by entering correct email, password and then tapping Login button',
      (WidgetTester tester) async {
    app.main();
    await binding.convertFlutterSurfaceToImage();
    await tester.pumpAndSettle();
    await binding.takeScreenshot('screenshot-1');
```

```
dhs@Dhss-MacBook-Pro int_test_sample % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --no-headless
Running "flutter pub get" in int_test_sample...                    647ms
Launching integration_test/app_test.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         19.1s
integration_test/app_test.dart is being served at http://localhost:50026
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[INFO]: http://localhost:50026/ 58:26 "Installed new service worker."
[WARNING]: http://localhost:50026/dart_sdk.js 48707:16 "registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[WARNING]: http://localhost:50026/dart_sdk.js 48689:16 "postEvent() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[INFO]: http://localhost:50026/dart_sdk.js 27195:14 "00:00 +0: Verify login functionality by entering correct email, password and then tapping Login button"
```

But if I remove `await binding.convertFlutterSurfaceToImage();` and `await binding.takeScreenshot('screenshot-1');` and run using this command `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server`, I get to run the test properly without any issues, as below:

```
dhs@Dhss-MacBook-Pro int_test_sample % flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --no-headless
Running "flutter pub get" in int_test_sample...                    652ms
Launching integration_test/app_test.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         19.4s
integration_test/app_test.dart is being served at http://localhost:49987
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[INFO]: http://localhost:49987/ 58:26 "Installed new service worker."
[WARNING]: http://localhost:49987/dart_sdk.js 48707:16 "registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[WARNING]: http://localhost:49987/dart_sdk.js 48689:16 "postEvent() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[INFO]: http://localhost:49987/dart_sdk.js 27195:14 "00:00 +0: Verify login functionality by entering correct email, password and then tapping Login button"
[INFO]: http://localhost:49987/dart_sdk.js 27195:14 "test@email.com"
[INFO]: http://localhost:49987/dart_sdk.js 27195:14 "demo1234"
All tests passed.
Application finished.

```

I am on latest master. In short, I am unable to replicate the issue you are facing, although for me, the test execution gets stuck and doesn't take a screenshot for me.

<details>
<summary> flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel master, 2.4.0-5.0.pre.202, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.202 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1f1c275d08 (4 hours ago), 2021-07-26 22:33:03 -0400
    • Engine revision 717d55cdd4
    • Dart version 2.14.0 (build 2.14.0-354.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1 18D61
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 92.0.4515.107

• No issues found!





```

</details>

**Comment by sbis04** [comment] 2021-07-27 07:17
@darshankawar `await binding.convertFlutterSurfaceToImage()` is not required for running on web.

I tried again on the latest **master** branch of Flutter but the same issue still exists.

Can you please try once by cloning this repo (I tried with this same code, instructions are there in the readme): https://github.com/sbis04/flutter_screenshot_integration_test.git

**Comment by darshankawar** [comment] 2021-07-27 10:07
Thanks for the repo @sbis04 
I was able to replicate the error using it on latest master, although, on latest stable, the error doesn't occur.

```
Running "flutter pub get" in flutter_screenshot_integration_test...      1,022ms
Launching integration_test/screenshot_test.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         18.8s
integration_test/screenshot_test.dart is being served at http://localhost:53321
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[INFO]: http://localhost:53321/ 58:26 "Installed new service worker."
[WARNING]: http://localhost:53321/dart_sdk.js 48707:16 "registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[WARNING]: http://localhost:53321/dart_sdk.js 48689:16 "postEvent() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[INFO]: http://localhost:53321/dart_sdk.js 27195:14 "00:00 +0: screenshot"
NAME: screenshot-test
result {"result":"true","failureDetails":[],"data":{"screenshots":[{"bytes":[]}]}}
Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0      integrationDriver (package:integration_test/integration_test_driver_extended.dart:100:60)
<asynchronous suspension>
#1      main (file:///Users/dhs/Documents/NCFlutter/flutter_screenshot_integration_test/test_driver/integration_test.dart:5:3)
<asynchronous suspension>
Application finished.
```

Looking at the error log, it seems to be coming from `integration_test_driver_extended.dart`'s following code line:

`final String? screenshotName = response.data!['screenshot_name'] as String?;`

Also, running with `non null safety`, ie, `sdk: ">=2.7.0 <3.0.0"`, doesn't produce the same error and shows below console log:

```
Running "flutter pub get" in flutter_screenshot_integration_test...        694ms
Launching integration_test/screenshot_test.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         18.8s
integration_test/screenshot_test.dart is being served at http://localhost:53542
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[INFO]: http://localhost:53542/ 58:26 "Installed new service worker."
[WARNING]: http://localhost:53542/dart_sdk.js 51506:16 "registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[WARNING]: http://localhost:53542/dart_sdk.js 51485:16 "postEvent() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set."
[INFO]: http://localhost:53542/dart_sdk.js 28578:14 "00:00 +0: screenshot"
NAME: screenshot-test
result {"result":"true","failureDetails":[],"data":{"screenshots":[{"bytes":[]}]}}
NAME: null
All tests passed.
Application finished.
```

<details>
<summary> master flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel master, 2.4.0-5.0.pre.202, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.202 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1f1c275d08 (4 hours ago), 2021-07-26 22:33:03 -0400
    • Engine revision 717d55cdd4
    • Dart version 2.14.0 (build 2.14.0-354.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1 18D61
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 92.0.4515.107

• No issues found!





```

</details>

**Comment by tatumizer** [comment] 2021-12-28 22:55
This issue makes integration test on the web virtually unusable. Can someone at least suggest a workaround?

**Comment by nolandg** [comment] 2022-03-30 05:20
Exact same issue still present today. Flutter web tests work perfectly until you try and take a screenshot.
````
Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0      integrationDriver (package:integration_test/integration_test_driver_extended.dart:103:60)
<asynchronous suspension>
````

**Comment by nolandg** [comment] 2022-04-04 19:40
Workaround fix until I fix my PR:
Update your `pubspec.yaml` to reference the fixed branch of my fork:
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    git:
      url: https://github.com/nolandg/flutter
      path: packages/integration_test
      ref: fix-screenshots
```

Or if you're not using Flutter 2.10.4:
1. Fork and clone repo
2. Checkout the exact tag you're using: `git checkout tags/2.10.4 -b fix-screenshots`
3. Make the fix, commit, and push
4. Update `pubspec.yaml`

**Comment by devyansh** [comment] 2023-03-02 23:22
Has any other fix to this issue been found? I am using flutter 3.0.5 and tried running with and without the flag `--no-sound-null-safety` and still get this error 

`Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast`

![image](https://user-images.githubusercontent.com/37020063/222585562-2547df9d-544a-40ac-9458-67893efafa74.png)

Chaging the integration_test_driver_extended as discussed above fixes the issue or providing a fake string name to screenshotName also fixes the issue. But I dont think this is the most optimal solution. Has any other solution been found to this problem?

**Comment by devyansh** [comment] 2023-03-02 23:23
@nolandg @sbis04

**Comment by mdebbar** [comment] 2023-08-10 18:33
Duplicate of https://github.com/flutter/flutter/issues/118470

**Closed by mdebbar** 2023-08-10 18:33 UTC
Labels: a: tests, platform-web, a: error message, f: integration_test, has reproducible steps, a: null-safety, assigned for triage, found in release: 2.4, team-web
