### ISSUE TITLE
[url_launcher]Does the canLaunch method not support Chinese paths?

### ISSUE THREAD

**Issue by orliu** [flutter/flutter#100344] opened 2022-03-18 02:51 UTC
String urlEn = 'https://xxx.xxx.com/xxx.pdf';
    String urlZh = 'https://xxx.xxx.com/中文.pdf';

    bool canLaunchUrlEn = await canLaunch(urlEn);  // result: true
    bool canLaunchUrlZh = await canLaunch(urlZh); // result: false

I found this problem on iOS platform. (Android is right).

Devce info:
iPhone 11
iOS 14.7.1

flutter doctor -v:

[✓] Flutter (Channel stable, 2.10.3, on macOS 11.5.1 20G80 darwin-x64, locale
    en-AS)
    • Flutter version 2.10.3 at /Users/ubisor/Library/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ubisor/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/ubisor/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8430

[✓] VS Code (version 1.65.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • ubisor’s  iPhone (mobile) • 00008030-000C045A02D3402E • ios            •
      iOS 14.7.1 18G82

**Comment by stuartmorgan** [comment] 2022-03-18 03:06
Duplicate of https://github.com/flutter/flutter/issues/98740

**Closed by stuartmorgan** 2022-03-18 03:06 UTC
