### ISSUE TITLE
Spurious exception in TextStyle for Web platform  

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [flutter/flutter#72633] opened 2020-12-19 00:01 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace main.dart with the file contained in [main.zip](https://github.com/flutter/flutter/files/5718566/main.zip)
3. Run this file in Chrome (web) device
4. Click the Generate image button
5. Exception is thrown

**Expected results:** 
I am expecting a blurred text shown below the button.

**Actual results:** 
Nothing is shown, but there is spurious exception in the log related to this TextStyle:
```dart
var blurredStyle = TextStyle(
    //color: Colors.purple,
    foreground: Paint()
      ..color = Colors.red
      ..style = PaintingStyle.fill
      ..maskFilter = MaskFilter.blur(BlurStyle.normal, 3),
    fontSize: 48);
```
```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text/paragraph.dart:949:13
color == null || foreground == null
"Cannot provide both a color and a foreground\nThe color argument is just a shorthand for \"foreground: new Paint()..color = color\"."
```
However, it works fine in the Android emulator. So I suspect for web there are some additional inherited styles containing color specification, which are merged so both color and foreground appears side by side. But setting color: null doesn't help here.

<details>
  <summary>Logs</summary>

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text/paragraph.dart:949:13
color == null || foreground == null
"Cannot provide both a color and a foreground\nThe color argument is just a shorthand for \"foreground: new Paint()..color = color\"."
    at Object.throw_ [as throw] (http://localhost:52715/dart_sdk.js:4354:11)
    at Object.assertFailed (http://localhost:52715/dart_sdk.js:4297:15)
    at new _engine.EngineTextStyle.only (http://localhost:52715/dart_sdk.js:172525:54)
    at _engine.DomParagraphBuilder.new.[_tryBuildPlainText] (http://localhost:52715/dart_sdk.js:172757:29)
    at _engine.DomParagraphBuilder.new.build (http://localhost:52715/dart_sdk.js:172671:38)
    at text_painter.TextPainter.new.layout (http://localhost:52715/packages/flutter/src/painting/placeholder_span.dart.lib.js:1144:36)
    at main._MyImageState.new.generateImage (http://localhost:52715/packages/horologium/main.dart.lib.js:379:26)
    at generateImage.next (<anonymous>)
    at runBody (http://localhost:52715/dart_sdk.js:38020:34)
    at Object._async [as async] (http://localhost:52715/dart_sdk.js:38051:7)
    at main._MyImageState.new.generateImage (http://localhost:52715/packages/horologium/main.dart.lib.js:368:20)
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:52715/packages/flutter/src/material/icon_button.dart.lib.js:51103:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:52715/packages/flutter/src/gestures/recognizer.dart.lib.js:189:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:52715/packages/flutter/src/gestures/tap.dart.lib.js:395:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:52715/packages/flutter/src/gestures/tap.dart.lib.js:201:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:52715/packages/flutter/src/gestures/tap.dart.lib.js:148:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:52715/packages/flutter/src/gestures/recognizer.dart.lib.js:448:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:52715/packages/flutter/src/gestures/pointer_router.dart.lib.js:86:9)
    at http://localhost:52715/packages/flutter/src/gestures/pointer_router.dart.lib.js:121:26
    at LinkedMap.new.forEach (http://localhost:52715/dart_sdk.js:25125:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:52715/packages/flutter/src/gestures/pointer_router.dart.lib.js:118:29)
    at pointer_router.PointerRouter.new.route (http://localhost:52715/packages/flutter/src/gestures/pointer_router.dart.lib.js:110:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:52715/packages/flutter/src/gestures/binding.dart.lib.js:314:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:52715/packages/flutter/src/gestures/binding.dart.lib.js:297:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:52715/packages/flutter/src/rendering/layer.dart.lib.js:6087:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:52715/packages/flutter/src/gestures/binding.dart.lib.js:268:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:52715/packages/flutter/src/gestures/binding.dart.lib.js:241:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:52715/packages/flutter/src/gestures/binding.dart.lib.js:230:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:52715/packages/flutter/src/gestures/binding.dart.lib.js:220:65)
    at Object.invoke1 (http://localhost:52715/dart_sdk.js:181069:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:52715/dart_sdk.js:163043:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:52715/dart_sdk.js:163678:49)
    at http://localhost:52715/dart_sdk.js:164111:26
    at http://localhost:52715/dart_sdk.js:164070:16
    at http://localhost:52715/dart_sdk.js:163778:11
```

```
No issues found! (ran in 2.5s)
```

```
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.25.0-8.1.pre at C:\flutter-sdk\flutter
    • Framework revision 8f89f6505b (3 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/j.tosovsky/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/j.tosovsky/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\RedHat\java-11-openjdk-11.0.8-2\bin\java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin version 52.0.2
    • Dart plugin version 202.8070

[√] VS Code (version 1.52.0)
    • VS Code at C:\Users\j.tosovsky\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 79.0.309.65

! Doctor found issues in 2 categories.
```

</details>

**Comment by pedromassangocode** [comment] 2020-12-21 09:39
I was able to reproduce this on latest `beta` BUT I cannot reproduce on `master` channel.

Cc @pcsosinski 

![Screen Shot 2020-12-21 at 10 37 42](https://user-images.githubusercontent.com/67424416/102762487-a2b77280-4378-11eb-9ea3-d6ff0f93231a.png)

<details><summary>Logs</summary>

```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:54674/u5E3bO0cWps=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:54674/u5E3bO0cWps=/ws
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text/paragraph.dart:949:13
color == null || foreground == null
"Cannot provide both a color and a foreground\nThe color argument is just a shorthand for \"foreground: new Paint()..color = color\"."
    at Object.throw_ [as throw] (http://localhost:54581/dart_sdk.js:4354:11)
    at Object.assertFailed (http://localhost:54581/dart_sdk.js:4297:15)
    at new _engine.EngineTextStyle.only (http://localhost:54581/dart_sdk.js:172525:54)
    at _engine.DomParagraphBuilder.new.[_tryBuildPlainText] (http://localhost:54581/dart_sdk.js:172757:29)
    at _engine.DomParagraphBuilder.new.build (http://localhost:54581/dart_sdk.js:172671:38)
    at text_painter.TextPainter.new.layout (http://localhost:54581/packages/flutter/src/painting/placeholder_span.dart.lib.js:1144:36)
    at main._MyImageState.new.generateImage (http://localhost:54581/packages/flutter_example/main.dart.lib.js:379:26)
    at generateImage.next (<anonymous>)
    at runBody (http://localhost:54581/dart_sdk.js:38020:34)
    at Object._async [as async] (http://localhost:54581/dart_sdk.js:38051:7)
    at main._MyImageState.new.generateImage (http://localhost:54581/packages/flutter_example/main.dart.lib.js:368:20)
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:54581/packages/flutter/src/material/icon_button.dart.lib.js:51103:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:54581/packages/flutter/src/gestures/recognizer.dart.lib.js:189:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:54581/packages/flutter/src/gestures/tap.dart.lib.js:395:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:54581/packages/flutter/src/gestures/tap.dart.lib.js:201:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:54581/packages/flutter/src/gestures/tap.dart.lib.js:148:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:54581/packages/flutter/src/gestures/recognizer.dart.lib.js:448:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:54581/packages/flutter/src/gestures/pointer_router.dart.lib.js:86:9)
    at http://localhost:54581/packages/flutter/src/gestures/pointer_router.dart.lib.js:121:26
    at LinkedMap.new.forEach (http://localhost:54581/dart_sdk.js:25125:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:54581/packages/flutter/src/gestures/pointer_router.dart.lib.js:118:29)
    at pointer_router.PointerRouter.new.route (http://localhost:54581/packages/flutter/src/gestures/pointer_router.dart.lib.js:110:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:54581/packages/flutter/src/gestures/binding.dart.lib.js:314:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:54581/packages/flutter/src/gestures/binding.dart.lib.js:297:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:54581/packages/flutter/src/rendering/layer.dart.lib.js:6087:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:54581/packages/flutter/src/gestures/binding.dart.lib.js:268:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:54581/packages/flutter/src/gestures/binding.dart.lib.js:241:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:54581/packages/flutter/src/gestures/binding.dart.lib.js:230:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:54581/packages/flutter/src/gestures/binding.dart.lib.js:220:65)
    at Object.invoke1 (http://localhost:54581/dart_sdk.js:181069:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:54581/dart_sdk.js:163043:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:54581/dart_sdk.js:163678:49)
    at http://localhost:54581/dart_sdk.js:164111:26
    at http://localhost:54581/dart_sdk.js:164070:16
    at http://localhost:54581/dart_sdk.js:163778:11
```
</details>

<details><summary>multiple flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.86, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.86 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision b793285329 (3 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 1EEFA5B2-DA95-49CC-AA0B-968BB248B8F3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-8.1.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 8f89f6505b (5 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 1EEFA5B2-DA95-49CC-AA0B-968BB248B8F3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by jan-tosovsky-cz** [comment] 2021-01-07 22:27
I can see blurred text when using `--web-renderer canvaskit`, howevever, in this case the transparent background is converted into the black opaque one.
![image](https://user-images.githubusercontent.com/3907898/103951844-acdebc80-513f-11eb-811a-a3b28b8dcf99.png)

**Comment by yjbanov** [comment] 2021-01-07 22:51
Flutter for mobile also performs this check (https://github.com/flutter/engine/blob/1365c3135199b5e13ddef5a4d41fbeeb86c57882/lib/ui/text.dart#L717). I suspect the issue is on the framework side, not in the web engine.

/cc @goderbauer can you please triage this issue?

**Comment by jan-tosovsky-cz** [comment] 2021-01-11 22:03
I can confirm that exception is not thrown in the master channel (that blurry text is rendered correctly in html renderer). I assume this issue can be closed.
In canvaskit there is still that black background, but this is covered by another issue.

**Comment by mdebbar** [comment] 2021-01-11 22:28
Fixed by https://github.com/flutter/engine/pull/22999

**Closed by mdebbar** 2021-01-11 22:28 UTC
Labels: a: typography, assigned for triage, found in release: 1.25, framework, has reproducible steps, platform-web, severe: crash
