### ISSUE TITLE
FocusTraversalGroup issue: Using up or down keys moves two spaces at a time.

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#100489] opened 2022-03-21 17:14 UTC
Flutter Web:

I've used FocusTraversalGroup to only focus on the TextField. I wanted to use the Up or Down keys to move one space at a time, but it moves two spaces at a time.

I want only the TextField to move the focus.

down key: aaa > bbb > ccc > ddd

up key: ddd > ccc > bbb > aaa

The result for this sample goes from a to c . I want to override the focus of the two icons in front of the textfield.

How to move focus to TextField only?
onKey: focusNode
Can you tell which TextField is focused?

```
class TextBlockSample extends StatefulWidget {
  const TextBlockSample({Key? key}) : super(key: key);

  @override
  State<TextBlockSample> createState() => _TextBlockSampleState();
}

class _TextBlockSampleState extends State<TextBlockSample> {
  late List<TextEditingController> _textControllers;
  late List<FocusNode> _textFocusNodes;
  List<String> users = ['aaa', 'bbb', 'ccc', 'ddd', 'eee'];
  int _currentFieldindex = 0;

  @override
  void initState() {
    _textControllers =
        List.generate(5, (index) => TextEditingController(text: users[index]));
    _textFocusNodes = List.generate(5, (index) => FocusNode());
    super.initState();
  }

  @override
  void dispose() {
    _textControllers.map((e) => e.dispose()).toList();
    _textFocusNodes.map((e) => e.dispose()).toList();
    super.dispose();
  }

  OrderedTraversalPolicy _focusNodeOrder = OrderedTraversalPolicy();

  @override
  Widget build(BuildContext context) {
    return Focus(
      onKey: (FocusNode focusNode, RawKeyEvent event) {
        int _focusIndex =
            _textFocusNodes.indexWhere((element) => element.hasFocus);
     
        print(
            'Current Focus:${focusNode}   ==   indexFocus:${_textFocusNodes[_focusIndex]}');
        if (event.logicalKey == LogicalKeyboardKey.arrowDown) {
       
          _focusNodeOrder.inDirection(
              _textFocusNodes[_focusIndex], TraversalDirection.down);

          return KeyEventResult.handled;
        }
        if (event.logicalKey == LogicalKeyboardKey.arrowUp) {
             _focusNodeOrder.inDirection(
              _textFocusNodes[_focusIndex], TraversalDirection.up);
        }

        return KeyEventResult.ignored;
      },
      child: FocusTraversalGroup(
        policy: _focusNodeOrder,
        child: Container(
          child: Column(
            children:
                users.mapIndexed((index, user) => inputText(index)).toList(),
          ),
        ),
      ),

    );
  }

  Widget inputText(int index) {
    return Container(
      height: 60,
      width: 500,
      child: Row(
        children: [
          FocusTraversalGroup(
            descendantsAreFocusable: false,
            child: IconButton(
              icon: const Icon(Icons.star),
              onPressed: () {},
            ),
          ),
          FocusTraversalGroup(
            descendantsAreFocusable: false,
            child: IconButton(
              icon: const Icon(Icons.label_important_outline),
              onPressed: () {},
            ),
          ),
          Container(
            width: 300,
            height: 50,
            child: FocusTraversalOrder(
              order: NumericFocusOrder(index.toDouble()),
              child: TextFormField(
                autofocus: index == 0 ? true : false,
                controller: _textControllers[index],
                focusNode: _textFocusNodes[index],
                textInputAction: TextInputAction.next,
                onChanged: (v) {
                  print('changed:$v');
                },
                onTap: () {
                  _currentFieldindex = index;
                },
              ),
            ),
          )
        ],
      ),
    );
  }
}

```

[✓] Flutter (Channel stable, 2.10.3, on Mac OS X 10.15.7 19H1615 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
![스크린샷 2022-03-21 오후 10 10 40](https://user-images.githubusercontent.com/49754877/159327870-93eacb06-fc4b-42f3-92e9-864a358cb99f.png)

**Comment by darshankawar** [comment] 2022-03-22 08:04
@Patrick386 
From your code, I am getting compile error `onMapsIndexed`:

<img width="305" alt="Screenshot 2022-03-22 at 1 03 30 PM" src="https://user-images.githubusercontent.com/67046386/159434819-567b569f-97b2-4bfa-9a59-dfc5276a3ba8.png">


> How to move focus to TextField only?

Can you try by using `FocusScope.of(context).nextFocus()` and put it in `onChanged()` of TextField ? and see if it helps ?

**Comment by Patrick386** [comment] 2022-03-22 10:19
> @Patrick386 From your code, I am getting compile error `onMapsIndexed`:
> 
> <img alt="Screenshot 2022-03-22 at 1 03 30 PM" width="305" src="https://user-images.githubusercontent.com/67046386/159434819-567b569f-97b2-4bfa-9a59-dfc5276a3ba8.png">
> 
> > How to move focus to TextField only?
> 
> Can you try by using `FocusScope.of(context).nextFocus()` and put it in `onChanged()` of TextField ? and see if it helps ?

Add a collection package. ( import 'package:collection/collection.dart'; )
FocusScope.of(context).nextFocus() gave the same result.

**Comment by darshankawar** [comment] 2022-03-23 06:49
Thanks for the update. I do see that using code sample provided, using down arrow key, the focus goes from aaa to ccc, while up arrow key takes focus from ccc to aaa although it does go through bbb.

I am going ahead and labeling it for further insights from the team as what should be the correct implementation or expected behavior for below questions asked:



> How to move focus to TextField only? onKey: focusNode Can you tell which TextField is focused?

<details>
<summary> stable, master  flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.13.0-0.0.pre.217, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.217 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e827f0b3e1 (4 hours ago), 2022-03-22 17:31:47 -0700
    • Engine revision 72583b3c71
    • Dart version 2.17.0 (build 2.17.0-228.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by yjbanov** [comment] 2022-03-24 18:17
Removing the web label for now, as this looks like a pure framework issue.

cc @gspencergoog @dkwingsmt

**Comment by Patrick386** [comment] 2022-04-20 12:41
The plotter does not provide a default editor.
If so, developers should be able to create editors.

I want to create an editor for use in my project.
There are several textedit packages, but these are not commonly available editors.(I tested SuperEditor, but it is also unstable and complicated. markdown, super editor ...)

Unfortunately, there seems to be a serious problem with the plotter framework. until now...
Natural scrolling and focus are very difficult.
Also serious is the loss of focus for keyboard control in textfield .
In addition, in order to provide various functions, it is necessary to select a part of the text area,
I need to be able to create a toolbar, but this is also very difficult.

We need a quick feature improvement

**macOs:**
https://user-images.githubusercontent.com/49754877/164231972-7f58b6b9-3c00-4203-90e1-c890cf5fe4a4.mov



**Medium**
https://user-images.githubusercontent.com/49754877/164232312-53593982-0a47-486c-9fd6-0b31f5e7f8f3.mov

.

**Comment by gspencergoog** [comment] 2022-04-20 16:53
Hi @Patrick386, I think the crux of the problem with this code is that you are handling both up and down key events, so pressing a key down will move one field, and then releasing the key moves another field.

Here's a slightly rearranged code example that works for your case:

```dart
import 'package:collection/collection.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MaterialApp(
    home: TextBlockSample(),
  ));
}

class TextBlockSample extends StatefulWidget {
  const TextBlockSample({super.key});

  @override
  State<TextBlockSample> createState() => _TextBlockSampleState();
}

class _TextBlockSampleState extends State<TextBlockSample> {
  late List<TextEditingController> _textControllers;
  late List<FocusNode> _textFocusNodes;
  List<String> users = ['aaa', 'bbb', 'ccc', 'ddd', 'eee'];

  @override
  void initState() {
    _textControllers =
        List<TextEditingController>.generate(5, (int index) => TextEditingController(text: users[index]));
    _textFocusNodes = List<FocusNode>.generate(5, (int index) => FocusNode());
    super.initState();
  }

  @override
  void dispose() {
    _textControllers.map((TextEditingController e) => e.dispose()).toList();
    _textFocusNodes.map((FocusNode e) => e.dispose()).toList();
    super.dispose();
  }

  final OrderedTraversalPolicy _focusNodeOrder = OrderedTraversalPolicy();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Focus(
        onKey: (FocusNode focusNode, RawKeyEvent event) {
          if (event is RawKeyUpEvent) {
            return KeyEventResult.ignored;
          }
          final int focusIndex = _textFocusNodes.indexWhere((FocusNode element) => element.hasPrimaryFocus);
          if (focusIndex > 0 && event.logicalKey == LogicalKeyboardKey.arrowUp) {
            _textFocusNodes[focusIndex - 1].requestFocus();
            return KeyEventResult.handled;
          }
          if (focusIndex < _textFocusNodes.length - 1 && event.logicalKey == LogicalKeyboardKey.arrowDown) {
            _textFocusNodes[focusIndex + 1].requestFocus();
            return KeyEventResult.handled;
          }

          return KeyEventResult.ignored;
        },
        child: FocusTraversalGroup(
          policy: _focusNodeOrder,
          child: Column(
            children: users
                .mapIndexed((int index, String user) =>
                    InputText(index: index, controller: _textControllers[index], focusNode: _textFocusNodes[index]))
                .toList(),
          ),
        ),
      ),
    );
  }
}

class InputText extends StatelessWidget {
  const InputText({
    super.key,
    required this.index,
    required this.controller,
    required this.focusNode,
  });

  final int index;
  final TextEditingController controller;
  final FocusNode focusNode;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 60,
      width: 500,
      child: Row(
        children: <Widget>[
          ExcludeFocus(
            child: IconButton(
              icon: const Icon(Icons.star),
              onPressed: () {},
            ),
          ),
          ExcludeFocus(
            child: IconButton(
              icon: const Icon(Icons.label_important_outline),
              onPressed: () {},
            ),
          ),
          SizedBox(
            width: 300,
            height: 50,
            child: FocusTraversalOrder(
              order: NumericFocusOrder(index.toDouble()),
              child: TextFormField(
                autofocus: index == 0,
                controller: controller,
                focusNode: focusNode,
                textInputAction: TextInputAction.next,
                onChanged: (String v) {
                  print('changed:$v');
                },
                onTap: () {},
              ),
            ),
          )
        ],
      ),
    );
  }
}
```

The key piece of code for fixing your issue is this:

```dart
          if (event is RawKeyUpEvent) {
            return KeyEventResult.ignored;
          }
```

 in the key handler.

Also, I took out all of the calls to the directional focus `inDirection` function, since that will search geometrically for the next field in that direction, and that is overkill here, since you already know which field is above or below. I replaced with with a simple call to `requestFocus` on the appropriate field.

Also, you can use the `ExcludeFocus` widget instead of `FocusTraversalGroup` to exclude focus on a subtree (it's just simpler, but does the same thing).

I'm going to close this issue, as the focus code is working as expected.

**Closed by gspencergoog** 2022-04-20 16:53 UTC
Labels: a: text input, framework, f: material design, f: focus, has reproducible steps, found in release: 2.10, found in release: 2.13

**Comment by Patrick386** [comment] 2022-04-21 04:41
> Hi @Patrick386, I think the crux of the problem with this code is that you are handling both up and down key events, so pressing a key down will move one field, and then releasing the key moves another field.
> 
> Here's a slightly rearranged code example that works for your case:
> 
> ```dart
> import 'package:collection/collection.dart';
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> 
> void main() {
>   runApp(const MaterialApp(
>     home: TextBlockSample(),
>   ));
> }
> 
> class TextBlockSample extends StatefulWidget {
>   const TextBlockSample({super.key});
> 
>   @override
>   State<TextBlockSample> createState() => _TextBlockSampleState();
> }
> 
> class _TextBlockSampleState extends State<TextBlockSample> {
>   late List<TextEditingController> _textControllers;
>   late List<FocusNode> _textFocusNodes;
>   List<String> users = ['aaa', 'bbb', 'ccc', 'ddd', 'eee'];
> 
>   @override
>   void initState() {
>     _textControllers =
>         List<TextEditingController>.generate(5, (int index) => TextEditingController(text: users[index]));
>     _textFocusNodes = List<FocusNode>.generate(5, (int index) => FocusNode());
>     super.initState();
>   }
> 
>   @override
>   void dispose() {
>     _textControllers.map((TextEditingController e) => e.dispose()).toList();
>     _textFocusNodes.map((FocusNode e) => e.dispose()).toList();
>     super.dispose();
>   }
> 
>   final OrderedTraversalPolicy _focusNodeOrder = OrderedTraversalPolicy();
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Focus(
>         onKey: (FocusNode focusNode, RawKeyEvent event) {
>           if (event is RawKeyUpEvent) {
>             return KeyEventResult.ignored;
>           }
>           final int focusIndex = _textFocusNodes.indexWhere((FocusNode element) => element.hasPrimaryFocus);
>           if (focusIndex > 0 && event.logicalKey == LogicalKeyboardKey.arrowUp) {
>             _textFocusNodes[focusIndex - 1].requestFocus();
>             return KeyEventResult.handled;
>           }
>           if (focusIndex < _textFocusNodes.length - 1 && event.logicalKey == LogicalKeyboardKey.arrowDown) {
>             _textFocusNodes[focusIndex + 1].requestFocus();
>             return KeyEventResult.handled;
>           }
> 
>           return KeyEventResult.ignored;
>         },
>         child: FocusTraversalGroup(
>           policy: _focusNodeOrder,
>           child: Column(
>             children: users
>                 .mapIndexed((int index, String user) =>
>                     InputText(index: index, controller: _textControllers[index], focusNode: _textFocusNodes[index]))
>                 .toList(),
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class InputText extends StatelessWidget {
>   const InputText({
>     super.key,
>     required this.index,
>     required this.controller,
>     required this.focusNode,
>   });
> 
>   final int index;
>   final TextEditingController controller;
>   final FocusNode focusNode;
> 
>   @override
>   Widget build(BuildContext context) {
>     return SizedBox(
>       height: 60,
>       width: 500,
>       child: Row(
>         children: <Widget>[
>           ExcludeFocus(
>             child: IconButton(
>               icon: const Icon(Icons.star),
>               onPressed: () {},
>             ),
>           ),
>           ExcludeFocus(
>             child: IconButton(
>               icon: const Icon(Icons.label_important_outline),
>               onPressed: () {},
>             ),
>           ),
>           SizedBox(
>             width: 300,
>             height: 50,
>             child: FocusTraversalOrder(
>               order: NumericFocusOrder(index.toDouble()),
>               child: TextFormField(
>                 autofocus: index == 0,
>                 controller: controller,
>                 focusNode: focusNode,
>                 textInputAction: TextInputAction.next,
>                 onChanged: (String v) {
>                   print('changed:$v');
>                 },
>                 onTap: () {},
>               ),
>             ),
>           )
>         ],
>       ),
>     );
>   }
> }
> ```
> 
> The key piece of code for fixing your issue is this:
> 
> ```dart
>           if (event is RawKeyUpEvent) {
>             return KeyEventResult.ignored;
>           }
> ```
> 
> in the key handler.
> 
> Also, I took out all of the calls to the directional focus `inDirection` function, since that will search geometrically for the next field in that direction, and that is overkill here, since you already know which field is above or below. I replaced with with a simple call to `requestFocus` on the appropriate field.
> 
> Also, you can use the `ExcludeFocus` widget instead of `FocusTraversalGroup` to exclude focus on a subtree (it's just simpler, but does the same thing).
> 
> I'm going to close this issue, as the focus code is working as expected.

**This works perfectly. thank you.**
