### ISSUE TITLE
Bold Text set by android Accessibility setting not working?

### ISSUE THREAD

**Issue by faziltm** [flutter/flutter#114472] opened 2022-11-02 02:35 UTC
When I am enabling bold text option In android accessibility setting. The text is not showing bold. I want to show my text as when enable the bold text in accessibility setting if it disabled the text not want to show as bold. In my code I am using  `MediaQueryData.fromWindow(WidgetsBinding.instance!.window).copyWith(boldText: true)`

And

`useInheritedMediaQuery: true`

Then the text became bold. But when i disabled bold text in accessibility. Then also the text is bold. 

    class MyApp extends StatelessWidget {
      const MyApp({Key? key}) : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return MediaQuery(
            data: MediaQueryData.fromWindow(WidgetsBinding.instance!.window).copyWith(boldText: true),
            child:MaterialApp(
              title: 'Flutter Demo',
              useInheritedMediaQuery: true,
              theme: ThemeData(
                primarySwatch: Colors.blue,
              ),
              home: const MyHomePage(title: 'Flutter Demo Home Page'),
            ));
      }
    }
    
    class MyHomePage extends StatefulWidget {
      const MyHomePage({Key? key, required this.title}) : super(key: key);
      final String title;
    
      @override
      State<MyHomePage> createState() => _MyHomePageState();
    }
    
    class _MyHomePageState extends State<MyHomePage> {
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  'Text Wants to be bold',
                  style: TextStyle(fontSize: 40),
                ),
    
              ],
            ),
          ),
        );
      }
    }
    class MyApp extends StatelessWidget {
      const MyApp({Key? key}) : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return MediaQuery(
            data: MediaQueryData.fromWindow(WidgetsBinding.instance!.window).copyWith(boldText: true),
            child:MaterialApp(
              title: 'Flutter Demo',
              useInheritedMediaQuery: true,
              theme: ThemeData(
                primarySwatch: Colors.blue,
              ),
              home: const MyHomePage(title: 'Flutter Demo Home Page'),
            ));
      }
    }
    
    class MyHomePage extends StatefulWidget {
      const MyHomePage({Key? key, required this.title}) : super(key: key);
      final String title;
    
      @override
      State<MyHomePage> createState() => _MyHomePageState();
    }
    
    class _MyHomePageState extends State<MyHomePage> {
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  'Text Wants to be bold',
                  style: TextStyle(fontSize: 40),
                ),
    
              ],
            ),
          ),
        );
      }
    }

My flutter version details:

    fazil.t.m@FAZIL-T-M-MAC myappnew % flutter doctor
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 2.10.1, on macOS 12.6 21G115 darwin-x64, locale en-GB)
    [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
    Download at: https://developer.apple.com/xcode/download/
    Or install Xcode via the App Store.
    Once installed, run:
    sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
    CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
    Without CocoaPods, plugins will not work on iOS or macOS.
    For more info, see https://flutter.dev/platform-plugins
    To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2021.3)
    [✓] Connected device (1 available)
    [✓] HTTP Host Availability
    
    ! Doctor found issues in 1 category.
    sdsa-fazil.t.m@GMC-FAZIL-T-M-MAC myappnew % flutter doctor
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 2.10.1, on macOS 12.6 21G115 darwin-x64, locale en-GB)
    [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
    Download at: https://developer.apple.com/xcode/download/
    Or install Xcode via the App Store.
    Once installed, run:
    sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
    CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
    Without CocoaPods, plugins will not work on iOS or macOS.
    For more info, see https://flutter.dev/platform-plugins
    To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2021.3)
    [✓] Connected device (1 available)
    [✓] HTTP Host Availability
    
    ! Doctor found issues in 1 category.

![12 2](https://user-images.githubusercontent.com/16598628/199381970-ab4a4832-d9ef-485c-b17e-be6527cc5268.png)
![11](https://user-images.githubusercontent.com/16598628/199382082-865ba443-eb8f-4576-92e8-5c61c4317e10.png)

**Comment by exaby73** [comment] 2022-11-02 10:36
Hello @faziltm. You are overriding the `boldText` param in the `MediaQuery`. This is forcing bold text even when the accessibility setting is turned off. You can remove the override and it works as expected.

<details>
<summary>Updated Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      useInheritedMediaQuery: true,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            Text(
              'Text Wants to be bold',
              style: TextStyle(fontSize: 40),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

Since this is not an issue with Flutter itself and is working as intended, I am closing this issue. If you disagree, please comment and I can reopen it. Thank you

**Closed** 2022-11-02 10:36 UTC
Labels: in triage

**Comment by faziltm** [comment] 2022-11-02 11:31
@exaby73 It is not working. Always showing not bold
My requirement is 
When open settings in android select Accessibility. In option visibility enhancements there is one option Font size and style. There we can select Bold text enable or disable. 
Settings>Accessibility>Visibility Enhancements>Font size and style>Bold text.
So when i am enabling bold text. That time my text wants to shown bold and if I disabled the option Then it should not bold style. This feature is working in whatsapp and other application. But it is not working in my flutter. I want to know whether flutter will support Bold text feature in accessibility.

**Comment by exaby73** [comment] 2022-11-02 11:50
Using the code sample I provided above without the `MediaQuery` widget, I get the following expected behavior:

<details>
<summary>Screen recording</summary>

[RecApp-2022-11-02-17:17:16.webm](https://user-images.githubusercontent.com/50555895/199482774-d7ae64ac-f99c-458d-bed7-eccde29d84a8.webm)

</details>

**Comment by faziltm** [comment] 2022-11-02 12:02
I am not getting the result in my physical device and emulator.
My flutter and versions are 
`Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (9 months ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2`

`Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"`

**Comment by exaby73** [comment] 2022-11-02 13:32
Can you please upgrade to the latest stable and re-confirm this? Unfortunately, we do not consider bugs on older versions valid as those can be already fixed in newer versions
