### ISSUE TITLE
Make onTap not wait for onDoubleTap

### ISSUE THREAD

**Issue by jibbers42** [flutter/flutter#113906] opened 2022-10-23 07:59 UTC
## Use case
Using `onTap` and `onDoubleTap` causes a delay to trigger `onTap` while waiting to see if `onDoubleTap` will trigger. I'd like a way to disable the delay, implying both events may fire. I've developed a couple small apps for Flutter Desktop and in each app, where I've wanted tap and double tap on the same widget, I've not wanted the delay imposed.

This is has been discussed as intended in #22950, but I feel it should be reconsidered, especially with enhanced desktop support Flutter continues to enable. I'm sure it exists, but I can't think of any desktop environment or app where a single click waits to see if it will turn into a double click. Actually, I'm not even sure why this might make sense on mobile, but I'm assuming Flutter's mobile origins influenced this behavior (I haven't developed a native mobile app either, so maybe with experience it would make more sense).

Issue #22950 discusses adjusting `kDoubleTapTimeout` to reduce the delay, but that's not an appropriate solution as it simply makes double clicks harder to achieve and still will have a noticeable delay if configured so that double click is usable.

In one instance I was able to use `SerialTapGestureRecognizer ` (https://discord.com/channels/608014603317936148/1030649689802035251/1031017424935460926), but that isn't always easy or even possible. For example, `DataTable` forces you to pass `DataCell`s, so there is no opportunity to wrap it. Even if you can use it, it would be nicer to use the `onTap` and `onDoubleTap` callbacks that a widget may already provide.

## Proposal
I'd like an option to disable the `onTap` delay when there is also an `onDoubleTap`. I'm not sure the best way of doing this... some kind of global config may work, or maybe instead/also a widget level config that will need to be added to widgets that expose `onTap` and `onDoubleTap`.

I don't know what all implications of this there may be, so it maybe even need be a Flutter v4 thing if breakage is required to do it right, but I do think "fixing" this experience on desktop is important. It simply doesn't work the way users on desktop platforms expect it to.

**Comment by jacobsimionato** [comment] 2024-01-30 02:16
I think this is a duplicate of https://github.com/flutter/flutter/issues/110300

**Closed by jacobsimionato** 2024-01-30 02:16 UTC
Labels: framework, f: gestures, customer: google, c: proposal, P3, team-framework, triaged-framework
