### ISSUE TITLE
Jitters/Frame Drops in iOS Screens after latest Stable release.

### ISSUE THREAD

**Issue by kaumudpa** [flutter/flutter#36064] opened 2019-07-12 12:50 UTC
Since the latest stable release came out v1.7.8-hotfix.3 all the iOS applications are experiencing minor but visible UI Jitters or Frame Drops while scrolling - But the same screen is working perfectly fine in android apps.

This needs urgent attention as this is a major issue and stops the build to be ship-ready.

**Comment by christopherfujino** [comment] 2019-07-12 17:55
What version were you previously on? From looking at [the hotfix PR](https://github.com/flutter/flutter/pull/35777) (and [here](https://github.com/flutter/engine/compare/b1cb0d9..54ad777) is the engine fix) I can't see that breaking iOS performance.

**Comment by kaumudpa** [comment] 2019-07-13 04:33
I upgraded from v1.5.4-hotfix.2 to 1.7.8-hotfix.3

**Comment by aleor** [comment] 2019-07-17 20:00
Having the same issue after upgrade from 1.5.4-hotfix.2 to 1.7.8-hotfix.3.
There are significant jitters on:
- navigating to another screen (both in fullscreen modal and normal modes);
- scrolling the page;
- animation of CupertinoActionSheet (while it's being rolled out from the bottom).

**Comment by kaumudpa** [comment] 2019-07-17 20:07
Exactly!

**Comment by kaumudpa** [comment] 2019-07-19 08:23
@aleor Are you using any image filter?
I have managed to find the problem, My screen uses BAckdrop filter to blur images and that too in list view. This is causing the problem of Jitter/Frame drops in the current stable build of Flutter - 1.7.8-hotfix.3.

This needs urgent attention of the flutter team.

**Comment by aleor** [comment] 2019-07-19 12:26
@kaumudpa Well, I don't use any filters, the only thing I'm using is ClipRRect to circle images. I've read that it can be expensive, but at the same time it didn't cause any issues before (on 1.5.4). Also, I've tested it on a relatively short list (up to 10 items) and still can see jitters.

**Comment by ericmartineau** [comment] 2019-08-01 22:51
Seeing similar in our app.  I'm stuck on `1.5.4-hotfix.2` as well.  I'll double check our usage of BackdropFilter and ClipRRect and report back.

**Comment by ericmartineau** [comment] 2019-08-01 23:20
The flutter sample project `veggieseasons` https://github.com/flutter/samples/tree/master/veggieseasons has the same performance degradation that I'm seeing in my app.

Here's what I did:

- Downloaded the samples project locally: https://github.com/flutter/samples/
- Ran the `veggieseasons` project using the `stable` channel (v1.8.3) in `--profile` mode
  - `flutter run --profile -d xxx`
  - The first page of the app `In Season Today` shows very noticeable stuttering while scrolling
- Ran the `veggieseasons` project using `v1.5.8` in `--profile` mode
  - No visible stuttering, app runs very smoothly

Hopefully this helps track it down

**Comment by ericmartineau** [comment] 2019-08-02 00:52
Video with performance overlay of the two versions:

[Screencast v.1.7.8+hotfix.4 (youtube)](https://youtu.be/ZIsarXWpvcI)
[Screencast v.1.5.8 (youtube)](https://youtu.be/XUD3Skt80t8)

**Comment by ericmartineau** [comment] 2019-08-07 21:37
@christopherfujino - any acknowledgement on this issue?  I'm now bumping up against the problem of not being able to release to the Play store because the apks I'm generating from flutter 1.5.x don't meet the 64-bit compatibility requirement for Play store publishing.  The 1.7.x release fixed this issue, but I can't upgrade due to this performance issue.

**Comment by christopherfujino** [comment] 2019-08-08 17:04
@ericmartineau it is currently being looked at!

**Comment by liyuqian** [comment] 2019-08-10 17:15
Bisected the regression to 71d370fd7bd17305d63a3a305c9b4782e0c0c886 . Will further bisect the engine/skia commits.

**Comment by liyuqian** [comment] 2019-08-12 20:47
I've bisected it down to Skia change: https://skia-review.googlesource.com/c/skia/+/213080

CC @lhkbob, @bsalomon

**Comment by liyuqian** [comment] 2019-08-12 21:06
CC @kf6gpe @csells to put this regression to the release notes.

**Comment by liyuqian** [comment] 2019-08-15 00:43
@lhkbob mentioned that Chromium is also affected by this bug and there's an ETA/deadline of September 5th to land a fix in Skia.

**Comment by liyuqian** [comment] 2019-08-19 23:26
I've reproduced the regression in Skia: https://skia-review.googlesource.com/c/skia/+/234413

Interestingly, the software rendering is always fast. That may give Skia team some information about how to quickly solve this performance regression.

**Comment by lhkbob** [comment] 2019-08-29 20:03
I have landed https://skia-review.googlesource.com/c/skia/+/237904 and it has rolled into the flutter engine. https://perf.skia.org/e/?begin=1567010155&end=1567104574&queries=name%3DGM_savelayer_with_backdrop%26os%3DiOS shows significant improvements in the iOS benchmarks that @liyuqian added to Skia. This can be closed once it's confirmed.

**Comment by aleor** [comment] 2019-08-29 21:22
@lhkbob That's a great news! How could it be tested, please? Should I switch to master branch and rebuild an app?

**Comment by ericmartineau** [comment] 2019-08-30 16:41
Thanks for the work on this - where should we see this fix land in flutter?

**Comment by liyuqian** [comment] 2019-08-30 17:33
I've confirmed that the fix has rolled into flutter since https://github.com/flutter/flutter/commit/14cec30c18b5ada61e5cdb6a8fd3428ccc023e85, and our backdrop ios benchmarks have significantly dropped since then.

@ericmartineau : please use the tip-of-tree master branch of Flutter to see if your problem is fixed.

**Comment by ericmartineau** [comment] 2019-08-30 21:34
@liyuqian the performance issue is fixed for my project in the `master` channel

**Comment by liyuqian** [comment] 2019-08-30 22:24
Glad to hear. Closing the issue.

**Closed by liyuqian** 2019-08-30 22:24 UTC
Labels: customer: crowd, severe: performance, severe: regression, waiting for PR to land (fixed), waiting for customer response, ⌺‬ platform-ios

**Comment by aleor** [comment] 2019-09-11 13:15
Hi @liyuqian , team,
Can't see this fix to be included into recent 1.9.1 release (https://github.com/flutter/flutter/wiki/PRs-merged-between-1.7.8-and-1.9.1), am I missing something or it's not released yet, and some dev branch should be used?

**Comment by christopherfujino** [comment] 2019-09-11 16:56
@aleor it looks like the fix landed in v1.10.0, which is currently on the dev branch.

**Comment by aleor** [comment] 2019-09-11 18:52
@christopherfujino Thanks, but are you sure it's there?.. Looking at https://github.com/flutter/flutter/releases/tag/v1.10.0, but can't see it?

**Comment by christopherfujino** [comment] 2019-09-11 19:27
@aleor 

```bash
~/git/flutter/dev/tools/lib$ git name-rev 14cec30
14cec30 tags/v1.10.0~76
```

which means it landed 76 commits before being published on v1.10.0

**Comment by ericmartineau** [comment] 2019-09-22 08:23
is there any hope for this fix to be backported to 1.9?  I don't love the prospect of releasing our app off the `dev` channel for the next few (?) months.

**Comment by liyuqian** [comment] 2019-09-24 18:23
CC @tvolkert for the hot fix question.

**Comment by tvolkert** [comment] 2019-09-26 16:40
We've decided not to hotfix this to stable (it'll be picked up in the next beta release in early Oct)
