### ISSUE TITLE
Using dart:ui from non-main-thread Isolates crashes

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#10647] opened 2017-06-13 00:39 UTC
Latest update (tl;dr: no current plans): https://github.com/flutter/flutter/issues/10647#issuecomment-1167923640
----

## Steps to Reproduce
In a fresh codebase generated by `flutter create`, I added the following functions and amended the `main()` function. Code taken from [this example](https://github.com/dartlang-italia/dart-libraries-samples/blob/master/isolate/isolates/bin/isolates.dart):

```dart
void echo(SendPort sender) {
  print("echo() the Isolate has been spawned!");
  ReceivePort receivePort = new ReceivePort();
  sender.send(receivePort.sendPort);
  receivePort.listen((data) {
    String msg = data[0];
    SendPort replyTo = data[1];
    print("Isolate received: $msg");
    WidgetsFlutterBinding.ensureInitialized();
    replyTo.send("Greetings from echo() the Isolate!");
  });
}

Future sendReceive(SendPort port, String msg) {
  ReceivePort receivePort = new ReceivePort();
  port.send([msg, receivePort.sendPort]);
  return receivePort.first;
}

void main() {
  ReceivePort receivePort = new ReceivePort();
  Future<Isolate> remote = Isolate.spawn(echo, receivePort.sendPort);
  remote.then((_) => receivePort.first).then((sendPort) {
    sendReceive(sendPort, "message sent from main()").then((msg) {
      print("Main received: $msg");
    });
  });
  runApp(new MyApp());
}
```

When I comment out the `WidgetsFlutterBinding.ensureInitialized();` call, everything runs smoothly. Leaving it in, the app crashes. When I run it in SkyShell with that call left in, I get a seg fault: 

```
echo() the Isolate has been spawned!
Isolate received: message sent from main()
Segmentation fault: 11
```

What is happening here? Should `WidgetsFlutterBinding.ensureInitialized()` be able to be called from a spawned Isolate?

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel alpha)
    • Flutter at /Users/emshack/flutter
    • Framework revision e2f54df5ab (10 days ago), 2017-06-02 10:43:54 -0700
    • Engine revision 1f2aa07571
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.1

[✓] Connected devices
    • iPhone 7 Plus • 09A7F58D-C832-4D91-B681-F67134E64361 • ios • iOS 10.3 (simulator)
```

**Comment by eseidelGoogle** [comment] 2017-06-13 06:28
dart:ui doesn't exist in non-main isolates, so I wouldn't expect much of the Flutter framework to work there.  FYI @Hixie.

We're currently in the process of making some improvements to our engine to allow exposing dart:ui on non-main isolates, but those are not yet complete.

**Comment by emshack** [comment] 2017-06-13 17:59
Ok, please let me know when something like this would be possible!

**Comment by mishadynin** [comment] 2017-06-13 20:54
This will also help another part of our project where we currently spawn another process and communicate via HTTP as a workaround.  So +1 to making this work in an isolate.

**Comment by eseidelGoogle** [comment] 2017-06-14 02:07
@GaryQian is currently working on wiring up libtxt as our new txt backend.  I'm told that's the largest single blocker to being able to use dart:ui off the main thread.  I suspect it may be several months before that's all landed and integrated and off-main-thread dart:ui is support at our current schedules though.  @abarth or @Hixie may correct my estimates however.

**Comment by Hixie** [comment] 2018-05-01 23:42
@chinmaygarde Any idea what the current status of this is?

We will have to come to a decision on what needs to be supported here by 1.0.

**Comment by chinmaygarde** [comment] 2018-05-02 00:46
Launching multiple Flutter views in their own isolates when their own dedicated threads is now supported (and is the default). Having multiple isolates talk to the same view is not currently supported and is not a priority.

We should probably not crash when `WidgetsFlutterBinding.ensureInitialized` is called from a secondary isolate however. Happy to work towards understanding if the current scheme of having multiple Flutter views solves @emshack's use case.

**Comment by paramita** [comment] 2020-04-19 00:04
I need this so much, especially for a heavy things like Path.combine.
I'm having a frame running for 3 seconds because there is no way to isolate native executions on Path.

![Annotation 2020-04-19 014846](https://user-images.githubusercontent.com/856359/79674064-f1a47b00-81df-11ea-9993-00691a7c734b.png)

**Comment by sgehrman** [comment] 2020-06-06 21:30
I have same problem

**Comment by mtiziano** [comment] 2020-07-15 13:49
Same problem

**Comment by ramesh456** [comment] 2020-09-12 09:26
Did you guys find any solution to open UI from isolate ?

**Comment by darshankawar** [comment] 2020-09-29 12:49
Issue replicable on latest beta.

```
I/flutter (16811): echo() the Isolate has been spawned!
I/flutter (16811): Isolate received: message sent from main()
E/flutter (16811): [ERROR:flutter/runtime/dart_isolate.cc(882)] Unhandled exception:
E/flutter (16811): UI actions are only available on root isolate.
```

Although moving `WidgetsFlutterBinding.ensureInitialized();` inside `main()` method doesn't throw the said error.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Mac OS X 10.15.4 19E2269, locale
    en-IN)
    • Flutter version 1.22.0-12.2.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 2bafdc8226 (4 days ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[✓] Connected device (2 available)            
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!

```

</details>

**Comment by ershat-dl** [comment] 2021-02-26 06:20
> Issue replicable on latest beta.
> 
> ```
> I/flutter (16811): echo() the Isolate has been spawned!
> I/flutter (16811): Isolate received: message sent from main()
> E/flutter (16811): [ERROR:flutter/runtime/dart_isolate.cc(882)] Unhandled exception:
> E/flutter (16811): UI actions are only available on root isolate.
> ```
> 
> Although moving `WidgetsFlutterBinding.ensureInitialized();` inside `main()` method doesn't throw the said error.
> 
> flutter doctor -v

could you give a small example , please?  thank you

**Comment by SivaramSS** [comment] 2021-06-09 02:56
Is this still not possible? i'm building 1000's of Paragraph objects and would like to do it in in non-main isolates.. but still getting this crash

**Comment by ruskakimov** [comment] 2021-07-16 06:52
I am using `dart:ui` for image processing. Processing a bunch of images freezes my UI, and I, unfortunately, was unable to get the code running in a isolate.

```
// Some sample code that can't be run in an isolate:
Future<Image> pngRead(File pngFile) async {
  final bytes = await pngFile.readAsBytes();
  final codec = await instantiateImageCodec(bytes);
  final frame = await codec.getNextFrame();
  return frame.image;
}

Future<Image> generateImage(
  CustomPainter? painter,
  int width,
  int height,
) async {
  final recorder = PictureRecorder();
  final canvas = Canvas(recorder);
  painter?.paint(canvas, Size(width.toDouble(), height.toDouble()));
  final picture = recorder.endRecording();
  return picture.toImage(width, height);
}
```

**Comment by VuHongKy** [comment] 2021-09-07 15:18
@Hixie @chinmaygarde Hi bro, I think this is very important thing that flutter should support.
What should I do if I want to change app language via Get.updateLocale()?
App always lag when I call that method on main isolate. That's too sad!
Please support us a solution, thank you!

**Comment by SivaramSS** [comment] 2021-09-19 09:36
Any progress on this? we're stuck to proceed with flutter because of the below issues.

1. We've to use multiple isolates for painting a spreadsheet but dart:ui is not available in non-ui isolates.
2. send the ui:image to the root isolate immediately. currently the decoding of image received at ui isolate takes a lot of ms.

**Comment by maganap** [comment] 2021-10-06 10:12
Similar problem @ruskakimov has. If invoked on an isolate:

`final codec = await ui.instantiateImageCodec(bytes, allowUpscaling: true);`

we're getting an exception:
`Failed to access the internal image decoder registry on this isolate`

UI freezes for several seconds  :-(

**Comment by 7mada123** [comment] 2022-04-11 03:11
Is there a way to overcome this issue?

**Comment by HiCubee** [comment] 2022-05-25 03:19
It has been 5 years, Flutter still not fix this problem, It is very important for us,  I could fix this problem with SurfaceView on Android, how to fix this on Flutter?

**Comment by p4-k4** [comment] 2022-06-04 11:26
Any updates on this?

**Comment by rlueders** [comment] 2022-09-13 03:43
Regarding usecases, I am using dart ui.PictureRecorder to draw a series of PNG images to be used in an overlay that gets merged on top of a user uploaded video. At a frame rate of 30+ frames per second, the app needs to generate thousands of PNGs for a 10 minute video. Of course this doesn't run well on the main isolate and I need to run this work on a pool of isolates. I initially ran in to the same problem that started this thread while attempting to use regular isolates. As such, I switched to use the [Flutter Isolates package.](https://pub.dev/packages/flutter_isolate).  Dart UI works in the Flutter Isolates package, however, I ran into other bugs that have been open for years that render the package unusable for this kind of work. 

Unfortunately this is one of a many dead-ends I have encountered while trying to build my app in flutter. I will be honest, I really don't want to spend my time filling in the gaps of a half-functional framework with patches, PRs, and design doc I have to write myself. I just want to build a beautiful app (like Tim Sneath says all the time at the flutter events. ), but this has proved very difficult with flutter. Using flutter for a real-world project is like  trying to use a kid's plastic toy hammer on a real construction job.

**Comment by matthew-carroll** [comment] 2022-12-07 19:24
@Hixie FYI, I describe a use-case and attempted mitigations related to this constraint in #115257

**Comment by rlueders** [comment] 2022-12-07 22:07
From a Flutter application developer’s perspective, dart:ui is no different from any other general purpose dart library.  For example, an application developer might use dart:math for literally infinite many use cases, some of which might need to run inside an isolate for performance reasons. The developer would be surprised and disappointed to find that after successfully compiling their Flutter application, a call to dart:math breaks when called from an isolate at runtime.  This is exactly what happens with dart:ui as evidenced by the number of issues I have stumbled across that are all asking to use some component of dart:ui in an isolate. Within each of those issues, there are many additional use cases contributed by other users via comments.  Most of these use cases are attempting to use dart:ui as a generic drawing or image  processing tool.
 
I gather that there are some “unsafe” components in dart:ui that should not be called from an isolate that can impact application rendering and frame scheduling.  But, to reiterate, many of these use cases are looking to use the “safe” components of dart:ui  (Canvas, Picture, PictureRecorder, Paint, Path,  Radius, Rect, Offset, Image, Gradient, etc.), using dart:ui as a generic drawing or image manipulation tool.  But then, why are these "safe" generic drawing utilities packaged with “unsafe” Flutter components?  Alternatively,  why are the “safe” generic drawing utilities indiscriminately restricted from isolates along with the “unsafe” Flutter components. To go back to the analogy, would it make sense for the Flutter team to restrict  dart:math from isolates if there was some special Flutter code packaged with dart:math. Of course it doesn't, but it appears that that is exactly what is happening with dart:ui.

**Comment by danagbemava-nc** [comment] 2023-03-17 10:12
Reproduces on the latest versions of flutter. Updating labels. 

<details>
<summary>code sample</summary>

```dart
import 'dart:isolate';

import 'package:flutter/material.dart';

void echo(SendPort sender) {
  print("echo() the Isolate has been spawned!");
  ReceivePort receivePort = ReceivePort();
  sender.send(receivePort.sendPort);
  receivePort.listen((data) {
    String msg = data[0];
    SendPort replyTo = data[1];
    print("Isolate received: $msg");
    WidgetsFlutterBinding.ensureInitialized();
    replyTo.send("Greetings from echo() the Isolate!");
  });
}

Future sendReceive(SendPort port, String msg) {
  ReceivePort receivePort = ReceivePort();
  port.send([msg, receivePort.sendPort]);
  return receivePort.first;
}

void main() {
  ReceivePort receivePort = ReceivePort();
  Future<Isolate> remote = Isolate.spawn(echo, receivePort.sendPort);
  remote.then((_) => receivePort.first).then((sendPort) {
    sendReceive(sendPort, "message sent from main()").then((msg) {
      print("Main received: $msg");
    });
  });
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: const Center(
        child: Text('some text'),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```
</details>

<details>
<summary>logs</summary>

```bash
Launching lib/main.dart on macOS in debug mode...
Building macOS application...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-000329201AD1001E }
{ platform:macOS, arch:x86_64, id:00008103-000329201AD1001E }
Debug service listening on ws://127.0.0.1:51624/HWY-7KvoUsw=/ws
Syncing files to device macOS...
flutter: echo() the Isolate has been spawned!
flutter: Isolate received: message sent from main()
[ERROR:flutter/runtime/dart_isolate.cc(1097)] Unhandled exception:
UI actions are only available on root isolate.
#0      FfiTrampoline____nativeSetNeedsReportTimings$Method$FfiNative$Ptr (dart:ffi)
#1      PlatformDispatcher.__nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:546:24)
#2      PlatformDispatcher._nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:543:52)
#3      PlatformDispatcher.onReportTimings= (dart:ui/platform_dispatcher.dart:535:29)
#4      SchedulerBinding.addTimingsCallback (package:flutter/src/scheduler/binding.dart:308:26)
#5      SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:240:7)
#6      ServicesBinding.initInstances (package:flutter/src/services/binding.dart:37:11)
#7      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:20:11)
#8      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:18:11)
#9      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:30:11)
#10     WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:249:11)
#11     new BindingBase (package:flutter/src/foundation/binding.dart:151:5)
#12     new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
#13     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
#14     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
#15     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
#16     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
#17     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
#18     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
#19     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
#20     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1260:7)
#21     echo.<anonymous closure> (package:ent/main.dart:13:27)
#22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#25     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#26     _StreamController._add (dart:async/stream_controller.dart:648:7)
#27     _StreamController.add (dart:async/stream_controller.dart:596:5)
#28     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
Application finished.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.7.7 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (9 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.9.0-9.0.pre.32, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.9.0-9.0.pre.32 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 53dfd23b04 (4 hours ago), 2023-03-17 01:59:19 -0400
    • Engine revision d9e65441ea
    • Dart version 3.0.0 (build 3.0.0-339.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by ydotmalik** [comment] 2023-03-18 02:50
If Google does not want to fix this issue, can they provide a workaround with a working example?

**Comment by MikeFP** [comment] 2023-04-03 17:06
> From a Flutter application developer’s perspective, dart:ui is no different from any other general purpose dart library. For example, an application developer might use dart:math for literally infinite many use cases, some of which might need to run inside an isolate for performance reasons. The developer would be surprised and disappointed to find that after successfully compiling their Flutter application, a call to dart:math breaks when called from an isolate at runtime. This is exactly what happens with dart:ui as evidenced by the number of issues I have stumbled across that are all asking to use some component of dart:ui in an isolate. Within each of those issues, there are many additional use cases contributed by other users via comments. Most of these use cases are attempting to use dart:ui as a generic drawing or image processing tool.
> 
> I gather that there are some “unsafe” components in dart:ui that should not be called from an isolate that can impact application rendering and frame scheduling. But, to reiterate, many of these use cases are looking to use the “safe” components of dart:ui (Canvas, Picture, PictureRecorder, Paint, Path, Radius, Rect, Offset, Image, Gradient, etc.), using dart:ui as a generic drawing or image manipulation tool. But then, why are these "safe" generic drawing utilities packaged with “unsafe” Flutter components? Alternatively, why are the “safe” generic drawing utilities indiscriminately restricted from isolates along with the “unsafe” Flutter components. To go back to the analogy, would it make sense for the Flutter team to restrict dart:math from isolates if there was some special Flutter code packaged with dart:math. Of course it doesn't, but it appears that that is exactly what is happening with dart:ui.

I second that. In my point of view, there are two main usecases:
- Run intensive rendering-related code in other isolates as to not block main thread.
- Use general classes related to rendering, but not coupled to Flutter, to implement custom render-related code.

The 1st one is harder to implement, since it requires changing the engine, and is related to other limitations of the current state of threading in Dart.

The 2nd one is simpler, and could be easier to implement. I imagine Dart can easily choose to allow importing files from `dart:ui` that do not import from anything related to flutter. I don't know if that's possible, but is sounds more doable than solving the 1st point.

Personally, more than a couple times I had to implement code related to rendering, either as a Dart library or to run in an Isolate, not necessarily on Flutter. Being unable to use `Offset`, `Rect`, `Size`, `Color` etc. is just a weird decision. Why should I manually implement `Rect` if there is a perfect implementation available in core? Instead, devs are expected to make them from scratch (a 3rd party library for those rendering utils would be nice), basically making libraries naturally incompatible with each other, for not adhering to a common interface.

**Comment by Medit8r** [comment] 2023-04-06 21:13
Would one way of potentially working around this be to use Lightweight flutter engines in a pure Flutter app? (ie. notAdd-to-App).  Since instances of the Lightweight flutter engines have their own threads but share some resources they would be fast to start up and perhaps could be used for offscreen rendering?  (Please note: I'm a Flutter newbie, so there could be gaps in my understanding, so pardon if it is a stupid question).  There are so many use cases which require being able to draw to a canvas in an isolate is required to get Flutter to perform any where near native solutions.

**Comment by Somtobro** [comment] 2023-05-11 13:14
This is disappointing
Flutter should take a look at this issue please

**Comment by Medit8r** [comment] 2023-09-03 00:02
By all accounts this has been an issue since 2017, and in the 6 long years since, the issue has never been addressed.  For all the talk of Flutter having a highly performant rendering engine, it does not support any use-cases where complex imagery has to generated.  The only possibility to accomplish this without affecting user interactions is if the rendering of the imagery in background isolates.  With that not being possible, Flutter is orders of magnitude slower than Skia / Xamarin in accomplishing this, so slow as to be unusable.  I guess Flutter is only meant for cartoons, forget use cases like GIS or real time updates ...

**Comment by hahouari** [comment] 2023-09-03 01:46
@Medit8r I hit this issue back in 2021, not sure if I commented here, but seems like this issue is not going to be fixed unless there is a change in the flutter design itself, something I doubt they will pull anytime soon, the project I started back then in flutter I had to rewrite twice to go around this issue with no luck sadly, I went to discover different technologies and as far as I know Xamarin is Xml based, not much what a flutter dev would like to move to, the technology I recommend is Jetpack compose and Compose Multiplatform, developed by JetBrains themselves, I worked with it, they have coroutines where u can pull some ui logic into another thread (if safe to call it a thread), but basically what we exactly want! which is to offload some ui code into another isolate. Kotlin is also super cool as well, so no complains so far, apart from being relatively new, back then I doubted the move from flutter, but looking into 2023, Although flutter is very promising and I like it, I simply don't regret the move I made. So I recommend it to everyone.👌

**Comment by rlueders** [comment] 2023-09-03 11:22
Isolates from the [Flutter Isolates](https://pub.dev/packages/flutter_isolate) package works fine with calls to dart.ui on both IOS and Android. I have been using it to generate lots of images from a pool of Flutter Isolates.

**Comment by chipweinberger** [comment] 2024-01-16 13:54
Just want to add my use case:

I use dart:ui & Canvas to render thousands of video frames.

I'd like to use multiple isolates to increase speed.

**Comment by chipweinberger** [comment] 2024-01-31 08:54
**I released a new plugin that workarounds this issue**.  https://pub.dev/packages/dart_ui_isolate

It is similar to the `flutter_isolate` package, but is specifically aimed at allowing `dart:ui` to run in an isolate.

**Comment by maganap** [comment] 2024-01-31 10:18
@chipweinberger Thank you for that! We dropped a project a couple of years ago because of this issue. We're planning to give it another chance in the next couple of months, so I'll be testing your plugin then.

**Comment by Hellomik2002** [comment] 2024-03-02 10:24
> **I've released a new plugin**. https://pub.dev/packages/dart_ui_isolate
> 
> It is very similar to the `flutter_isolate` package, but is specifically for allowing `dart:ui` to run in an isolate, without the additional complexity of external plugin support.
> 
> Due to that, it supports FlutterEngineGroup which saves 100s of megabytes of memory.

Can you show an example of how to use it with widgets?

**Comment by ignatz** [comment] 2024-03-04 13:04
What I understood from @chipweinberger, ui isolates can be used from Android, iOS and OSX. Are there any plans to support the other platforms?

Independently, even when using this functionality on supported platforms, I'm either holding it wrong or it's pretty clunky. Let's say I rasterize an image with dart:ui on a child ui isolate, I then have to copy the image bytes into the dart isolate to then send it over, to then decode the image which will copy the bytes back to native. Naively, I would have hope to use ImageDescriptor, i.e. just sending a pointer to the image in memory, however ImageDescriptor doesn't seem to be serializable[^1]. With this new functionality, should it be?

> Can you show an example of how to use it with widgets?

Non-authoritatively: I don't think that's an intended use-case

---
[^1]: `Unhandled Exception: Invalid argument: is a regular instance reachable via : Instance of '_NativeImageDescriptor'`

**Comment by jonahwilliams** [comment] 2024-09-18 20:27
deduping into https://github.com/flutter/flutter/issues/13343

**Closed by jonahwilliams** 2024-09-18 20:27 UTC
Labels: c: crash, engine, has reproducible steps, P2, found in release: 3.7, found in release: 3.9, team-engine, triaged-engine
