### ISSUE TITLE
TextField Keyboard option to insert images and GIFs implementation or make an option to disable

### ISSUE THREAD

**Issue by shivamstaq** [flutter/flutter#67857] opened 2020-10-11 09:34 UTC
## Use case
Hello
I am working on a flutter app which requires a chat room feature. I am done with >80% of the app and just now found out that flutter is currently unable to handle the phone's in-built keyboard callbacks like the image insert and GIFs. 
I tried using different `keyboardType` (`TextInputType`) for the `TextField`, but the bar on top of the keyboard still shows up as shown in the picture. 
If any image/GIF is selected from the bar, it gives a message 

> "app doesn't support image insertion here"

I think the reason for that is that Flutter does not handle the `commitContent()` and `InputContentInfo` response from it as mentioned here : https://developer.android.com/guide/topics/text/image-keyboard

![Screenshot_1602407246](https://user-images.githubusercontent.com/61043775/95674850-822ca880-0bd0-11eb-9fa2-bbac95af126b.png)

## Proposal
I went through existing related issues: https://github.com/flutter/flutter/issues/43340 and https://github.com/flutter/flutter/issues/20796 
I could see that this issue has not been resolved in Flutter's master thread and decided to raise a new issue.
The best approach in my view would be to give an option to disable the option for images and GIFs from the keyboard until it can be implemented in production.
As for handling the images from the keyboard, maybe a callback function to receive the url of the selected images so that appropriate response can be implemented. 

I am unaware of any possible workarounds that can be applied here, please don't hesitate to comment a solution that can be a temporary fix since I need to release my app soon.

Thanks

## flutter doctor -v 

![image](https://user-images.githubusercontent.com/61043775/95677195-7a293480-0be1-11eb-8564-e0b046aff7d9.png)

**Comment by tusharsadhwani** [comment] 2020-10-12 09:39
Bump. seems like this is a pretty important feature for a lot of people.

**Comment by TahaTesser** [comment] 2020-10-12 13:22
Hi @skpatrat 
These issues you mentioned are already open to address this issue.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by skpatrat** [comment] 2020-10-12 13:27
> Hi @skpatrat 
> These issues you mentioned are already open to address this issue.
> Please follow up on that issue, I'm closing the current one as a duplicate.
> If you disagree, please write in the comments and I will reopen it.
> Thank you

I raised a new issue because the other one does not mention any option to disable the image/gif bar as shown in the image. 
I believe there should be an option to disable it  within flutter if at all possible. 
Please take that into consideration.

**Comment by TahaTesser** [comment] 2020-10-13 12:11
Hi @skpatrat 
That's fair, you can propose in the existing issues since it's not even implemented yet, how do we propose an option to disable before it's implemented in the first place

**Comment by chrisDK1977** [comment] 2021-03-10 16:21
Is there any option to disable the functions which are not available in Flutter apps like GIF and Sticker? Why is this Issue closed like all other issues adressing this issue?

**Comment by lecicdjuro** [comment] 2021-03-12 08:40
I have the same question? This and all other referenced issues are closed, but the problem is still present.
Please reopen the issue. @TahaTesser

**Comment by TahaTesser** [comment] 2021-03-12 13:16
Looking back I might have misjudged the issue, labelling it as a proposal to disable this

**Comment by aktxyz** [comment] 2021-03-28 16:32
+1

**Comment by duongtruong12** [comment] 2021-04-08 18:45
+1 flutter is working on this requirement?

**Comment by kqureshi14** [comment] 2021-09-22 12:21
any update on this ? how can we give support of GIF in flutter by use the TextField ?

**Comment by foxy17** [comment] 2022-01-04 08:21
All apps which have chat or any other text based interaction will need this feature is the team working on it!

**Comment by Invectys** [comment] 2022-01-31 07:51
i also faced this

**Comment by dooully** [comment] 2022-02-28 04:00
i need same

**Comment by carman247** [comment] 2022-03-25 15:40
Following ... would really like to see the ability to disable certain toolbar options but keep functionality like multiline and suggested words

**Comment by rlee1990** [comment] 2022-04-08 03:33
@TahaTesser any update on this?

**Comment by konoshenko** [comment] 2022-07-15 10:29
Any updates?

**Comment by ash-hashtag** [comment] 2022-11-29 05:26
updates?

**Comment by FlorisDevreese** [comment] 2022-12-04 09:56
for those who are going for a minimal app approach, it is necessary that these options are hidden on the keyboard

**Comment by mrcsh** [comment] 2023-02-28 18:22
While I personally don't care if GIF/sticker support is added, being able to disable functionality in the keyboard in lieu of support is imperative for a good user experience.

**Comment by gnprice** [comment] 2023-03-03 05:02
I believe the main feature request here is the same as #20796, which has been done.

@siddharthadevops It looks like yours is the only comment in this thread that clearly expresses interest in having the ability to disable this feature even though it's now supported. (The original report and a couple of comments are interested in the ability to disable it as a fallback, and several more comments are only interested in the actual feature.) If you or anyone else would still like that feature, I think it would be best to file a fresh issue specifically for that.

**Comment by gnprice** [comment] 2023-03-04 04:48
Closing for the reasons in https://github.com/flutter/flutter/issues/67857#issuecomment-1452977510 , as a duplicate of #20796.

If anyone is still interested in the ability to disable inserting images, now that inserting images is supported, a new issue to express that feature request would be welcome.

**Closed** 2023-03-04 04:52 UTC
Labels: a: text input, framework, a: quality, proposal, passed first triage, P5

**Comment by tneotia** [comment] 2023-03-05 17:02
Just FYI, the existing API that added this feature in is fully disabled by default, to the point where the native system will actually show a toast saying "This app does not support inserting media here" or something to that effect. Thus, any app upgrading their Flutter version to the SDK that supports the feature will need to manually enable users to paste rich content into the text field.

**Comment by gnprice** [comment] 2023-03-07 04:51
> Just FYI, the existing API that added this feature in is fully disabled by default, to the point where the native system will actually show a toast saying "This app does not support inserting media here" or something to that effect.

Ah, thanks for the correction!

In that case, it sounds like everything that was asked for in this thread has been done.
