### ISSUE TITLE
[tool_crash] ProcessException: The paging file is too small for this operation to complete.Working directory: "E:\Programming\Flutter Apps\RAA" (exists)pub env: {  "FLUTTER_ROOT": "F:\flutter",  "PUB_ENVIRONMENT": "flutter_cli:get",} Command: F:\flutter\bin\cache\dart-sdk\bin\dart.EXE, OS error code: 1455

### ISSUE THREAD

**Issue by harrisbasra** [flutter/flutter#136399] opened 2023-10-11 19:35 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The paging file is too small for this operation to complete.

Working directory: "E:\Programming\Flutter Apps\RAA" (exists)
pub env: {
  "FLUTTER_ROOT": "F:\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
}
 Command: F:\flutter\bin\cache\dart-sdk\bin\dart.EXE, OS error code: 1455
```
#0      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:423:9)
<asynchronous suspension>
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:530:5)
<asynchronous suspension>
#2      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:314:7)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
```
[!] Flutter (Channel beta, 3.13.0-0.1.pre, on Microsoft Windows [Version 10.0.22621.2361], locale en-US)
    • Flutter version 3.13.0-0.1.pre on channel beta at F:\flutter
    ! The flutter binary is not on your path. Consider adding F:\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1f6bdb6fa2 (3 months ago), 2023-07-11 14:31:59 -0700
    • Engine revision ae470c12d3
    • Dart version 3.1.0 (build 3.1.0-262.1.beta)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at F:\Androidd
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 20.0.1+9-29)

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33815.320
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2022.3)
    • Android Studio at F:\AndroidAfterMath
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at F:\IntelliJ\IntelliJ IDEA Community Edition 2023.2.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • Infinix X695 (mobile) • 067682514Q109520 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)     • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.2361]
    • Chrome (web)          • chrome           • web-javascript • Google Chrome 117.0.5938.150
    • Edge (web)            • edge             • web-javascript • Microsoft Edge 117.0.2045.60

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 12cb4eb7a009f52b347b62ade7cb4854b926af72
### Plugins
cloud_firestore-4.8.3
cloud_firestore_web-3.6.3
firebase_auth-4.7.0
firebase_auth_web-5.6.0
firebase_core-2.15.0
firebase_core_web-2.6.0
firebase_storage-11.2.5
firebase_storage_web-3.6.5
flutter_email_sender-6.0.2
flutter_native_splash-2.3.3
geolocator-10.1.0
geolocator_android-4.3.1
geolocator_apple-2.3.2
geolocator_web-2.2.0
geolocator_windows-0.2.1
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.4
path_provider_linux-2.1.11
path_provider_windows-2.1.7
url_launcher-6.1.14
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.6
url_launcher_macos-3.0.7
url_launcher_web-2.0.19
url_launcher_windows-3.0.8

**Comment by darshankawar** [comment] 2023-10-12 07:23
Closing this as duplicate of https://github.com/flutter/flutter/issues/96990.

**Closed by darshankawar** 2023-10-12 07:23 UTC
Labels: in triage
