### ISSUE TITLE
[google_maps_flutter] iOS GoogleMap disables gesture events after dragging marker

### ISSUE THREAD

**Issue by Szfymen** [flutter/flutter#53525] opened 2020-03-29 15:59 UTC
# Steps to Reproduce:

- Set onTap closure to add new Marker with the draggable property set to true on each tapped location
- Tap anywhere on the map to add a marker
- Long press on newly added marker to drag it to another location
- Try to drag marker again -> Marker is not reacting now
- Try to drag marker again  -> Marker is now again draggable
- Try to add new marker -> Nothing happens
- Try to add new marker -> Marker is successfully added

## Conclusion:
- Map disables gesture events after dragging the marker on iOS, in order to enable it again you have to press anywhere on the map.
- Android handles it properly

**Comment by iapicca** [comment] 2020-03-30 11:27
Hi @Szfymen 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

possible duplicate of https://github.com/flutter/flutter/issues/53428

**Comment by Szfymen** [comment] 2020-03-30 13:10
Hi @iapicca, here is the simplest code to achieve this issue. 
Just add a marker by tapping on the map, then drag it to another location and try dragging it again -> it won't work.
Basically, after dragging the marker none of the actions on the map works. 
```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class TestMap extends StatefulWidget {
  @override
  _TestMapState createState() => _TestMapState();
}

class _TestMapState extends State<TestMap> {
  Completer<GoogleMapController> _controller = Completer();
  Map<MarkerId, Marker> markers = Map<MarkerId, Marker>();

  @override
  Widget build(BuildContext context) {
    return _buildTestMap();
  }

  Widget _buildTestMap() {
    return GoogleMap(
      onMapCreated: (GoogleMapController controller) {
        _controller.complete(controller);
      },
      initialCameraPosition: CameraPosition(
        target: LatLng(54.0, 20.0),
        zoom: 9.0,
      ),
      markers: markers.values.toSet(),
      onTap: (position) => _addNewMarker(position),
    );
  }

  _addNewMarker(LatLng position) {
    var marker = Marker(
      markerId: MarkerId(
        position.toString(),
      ),
      draggable: true,
      position: position,
    );

    setState(
      () {
        markers[marker.markerId] = marker;
      },
    );
  }
}
```

Here is my `flutter doctor -v`
```
[✓] Flutter (Channel master, v1.16.4-pre.18, on Mac OS X 10.15.1 19B88, locale pl-PL)
    • Flutter version 1.16.4-pre.18 at /Users/mateusztylman/Flutter/SDK/flutter
    • Framework revision c8efcb632b (2 days ago), 2020-03-27 22:31:01 -0700
    • Engine revision 3ee9e3d378
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mateusztylman/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • iPad (Mateusz Tylman) • 00008027-000451E111E8002E • ios • iOS 13.3.1
    • iPhone (Tests XR)     • 00008020-0016251C3CD2002E • ios • iOS 13.3.1

• No issues found!
```

**Comment by iapicca** [comment] 2020-04-03 08:22
Hi @Szfymen 
thank you for your logs 

if the issue is actually related to [53428](https://github.com/flutter/flutter/issues/53525#issuecomment-605943783)
a [fix](https://github.com/flutter/plugins/pull/2629) might be on the way

**Comment by pedromassangoncode** [comment] 2020-07-15 12:37
Hi @Szfymen,
I cannot reproduce this issue on latest `dev` channel.
Can you upgrade to dev and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

<details>
<summary> My flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-AO)
    • Flutter version 1.17.5 at /Users/pedro/dev/SDKs/flutter_stable
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 3754CE41-3077-49D2-A7FB-B6D7558DD7A8 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```
</details>

**Comment by markusaksli-nc** [comment] 2020-08-28 11:22
Closing as probably fixed by https://github.com/flutter/plugins/pull/2629

**Closed by markusaksli-nc** 2020-08-28 11:22 UTC
Labels: f: gestures, framework, p: first party, p: maps, plugin, waiting for customer response
