### ISSUE TITLE
Error: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'

### ISSUE THREAD

**Issue by dhurem** [flutter/flutter#133037] opened 2023-08-22 10:41 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run commands `flutter build ipa` or `flutter build apk`

### Expected results

Android and iOS builds to pass with no issues.

### Actual results

Both Android and iOS builds fail.

### Code sample

No code related to this issue.

### Logs

<details><summary>Android Log</summary>

```console
Error: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'.
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../flutter/packages/flutter/lib/src/rendering/object.dart').
 - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../flutter/packages/flutter/lib/src/foundation/node.dart').
      final AbstractNode? targetParent = renderObject.parent;
                                                      ^
../../.pub-cache/hosted/pub.dev/sliver_tools-0.2.10/lib/src/sliver_stack.dart:283:54: Error: The method 'markNeedsLayout' isn't defined for the class 'AbstractNode?'.
 - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../flutter/packages/flutter/lib/src/foundation/node.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsLayout'.
      if (targetParent is RenderObject) targetParent.markNeedsLayout();
                                                     ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/Users/emirhurem/dev/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/emirhurem/dev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

</details>

<details><summary>iOS Log</summary>

```console
Running Xcode build...                                                  
Xcode archive done.                                         26.1s
Failed to build iOS app
Error (Xcode):
../../.pub-cache/hosted/pub.dev/sliver_tools-0.2.10/lib/src/sliver_stack.dart:28
2:55: Error: A value of type 'RenderObject?' can't be assigned to a variable of
type 'AbstractNode?'.


Encountered error while archiving for device.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4 22F66 darwin-arm64, locale
    en-BA)
    • Flutter version 3.13.0 on channel stable at /Users/emirhurem/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (6 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/emirhurem/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by nicklbaert** [comment] 2023-08-22 10:57
Might be an outdated version of sliver_tools. https://github.com/Kavantix/sliver_tools/issues/83

**Comment by huycozy** [comment] 2023-08-22 11:02
@dhurem The issue is caused by `sliver_tools` package so you should report this for its developer for better support. Taking a quick look at this, you are using an old version `sliver_tools-0.2.10`. It seems to be fixed on a newer version as mentioned on the linked issue given by @nicklbaert.

Closing this as it's not a Flutter framework issue.

**Closed by huycozy** 2023-08-22 11:02 UTC
Labels: in triage

**Comment by dhurem** [comment] 2023-08-22 11:11
Thanks for the insanely fast response! Cheers 🍻
