### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by yikuyiku** [flutter/flutter#87025] opened 2021-07-26 03:52 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:221:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:220:12)
#6      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:137:53)
#7      AndroidPlugin._supportedEmbedings (package:flutter_tools/src/platform_plugins.dart:91:70)
#8      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:83:30)
#9      _extractPlatformMaps (package:flutter_tools/src/plugins.dart:606:40)
#10     _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:622:5)
#11     injectPlugins (package:flutter_tools/src/plugins.dart:1202:11)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:322:5)
<asynchronous suspension>
#13     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:167:5)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.1110], locale zh-CN)
    • Flutter version 2.2.2 at D:\flutter
    • Framework revision d79295af24 (6 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\user\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (3 available)
    • MIX 2S (mobile) • 19aeb9de • android-arm64  • Android 10 (API 29)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)      • edge     • web-javascript • Microsoft Edge 91.0.864.71

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b1395592de68cc8ac4522094ae59956dd21a91db
### Plugins
ali_real_person
amap_flutter_location-2.0.0
connectivity-3.0.6
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
device_info-2.0.2
flutter_image_compress-1.0.0
flutter_inapp_purchase-5.0.1
flutter_keyboard_visibility-5.0.2
flutter_keyboard_visibility_web-2.0.0
flutter_nim
flutter_secure_storage-4.2.0
fluwx-3.4.3
image_crop-0.4.0
package_info-2.0.2
path_provider-2.0.2
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
permission_handler-8.0.1
photo_manager-1.2.2
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
url_launcher-6.0.6
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.1
url_launcher_windows-2.0.0
video_compress-3.0.0
video_player-2.1.5
video_player_web-2.0.1

**Comment by darshankawar** [comment] 2021-07-26 11:26
Closing this as duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by darshankawar** 2021-07-26 11:26 UTC
Labels: in triage
