### ISSUE TITLE
[Impeller] cubic bezier macrobenchmark has rendering artifacts

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#119964] opened 2023-02-03 22:07 UTC
Looks like the ends aren't closed correctly

## Skia

![flutter_03](https://user-images.githubusercontent.com/8975114/216719973-d10db892-ed99-4e38-860e-98fc1ea39774.png)

## Impeller

![flutter_02](https://user-images.githubusercontent.com/8975114/216719981-be41e908-238b-4d39-93ef-dfec9beb6aa1.png)

**Comment by jonahwilliams** [comment] 2023-02-03 22:07
The code in question is https://github.com/flutter/flutter/blob/master/dev/benchmarks/macrobenchmarks/lib/src/cubic_bezier.dart

**Comment by luckysmg** [comment] 2023-03-09 10:51
The cap rendering issue maybe will be fixed by 
 - https://github.com/flutter/engine/pull/40115

Emm But the rendering seems to be strange (This also can be reproduced in stable 3.7.6 and master channel).....**

![normal video](https://user-images.githubusercontent.com/49340347/224000328-0ebce4d2-f035-4dfc-9a94-d9fe646c5db0.gif)

If I remove the rotate call in https://github.com/flutter/flutter/blob/0d413e5d1ad6bf52522ae86a550a20e18fb50387/dev/benchmarks/macrobenchmarks/lib/src/cubic_bezier.dart#L370

Will be:

<img src = "https://user-images.githubusercontent.com/49340347/224001524-66c26285-c73d-469f-87ae-f29784457c36.gif" width=300 />

Seems that rotation results something not correct 🤔

**Comment by chinmaygarde** [comment] 2023-06-27 19:55
Closing this as fixed in https://github.com/flutter/engine/pull/40115.

**Closed by chinmaygarde** 2023-06-27 19:55 UTC
Labels: engine, P4, impeller
