### ISSUE TITLE
Memory keeps increasing leads to crashing in iOS(It would easily happen  in iPhone 6)

### ISSUE THREAD

**Issue by cxq1221** [flutter/flutter#19754] opened 2018-07-25 09:54 UTC
When pushing and popping a complicated page repeatedly, the memory keeps increasing.
The same issue also exists in Flutter Gallery.
As described above:
![20180725173953](https://user-images.githubusercontent.com/13374376/43193763-75ab5946-9033-11e8-91b1-86a6960bafdf.png)

**Comment by cxq1221** [comment] 2018-07-25 10:56
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 0.5.1 at /Users/blockmake/Documents/Test/flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at //Users/blockmake/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = //Users/blockmake/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Mi 4c    • 82cd1714                             • android-arm64 • Android 7.0 (API 24)
    • iPhone X • A2C46D32-7C1A-4F90-A187-44281E51789C • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-0 (simulator)

**Comment by cxq1221** [comment] 2018-07-25 10:59
Reproducing Steps: Push a page with complicated UI and pop, and do it repeatedly , or push diffrent pages repeatedly.

**Comment by ryansong** [comment] 2018-10-16 09:37
I have the same problem, it seems FlutterViewController never be called dealloc to release. Every push will increase about 60+M memory.

**Comment by Natoto** [comment] 2018-12-05 09:11
FlutterViewController can not be release is a big big big big big bug

**Comment by zoechi** [comment] 2019-02-22 10:37
@ryansong @Natoto sounds like #16995

**Comment by ened** [comment] 2019-05-08 05:48
Sounds more like a general performance issue on iPhone 6.

**Comment by joaquinperaza** [comment] 2019-06-07 00:35
Same here, flutter is reducing our possibilities with this. :worried:

**Comment by krishnakirana** [comment] 2019-08-13 04:58
Call flutterEngine?.destroyContext() when you want release flutterViewController

**Comment by ened** [comment] 2019-08-13 07:20
@cxq1221 - can you please provide a simple sample project that shows the problem?

**Comment by maxermakov** [comment] 2019-08-21 11:39
@ened the example provided by topic-starter of this issue https://github.com/flutter/flutter/issues/32143 (don't know why it was closed) is always crashing on ios (testing on iPhone 6 )by the same reason as well as flutter gallery sample with flutter version v1.7.8+hotfix.2 stable channel and v1.9.0 from dev channel.

**Comment by caoyunxiao** [comment] 2019-09-06 09:49
DestroyContext would crash

**Comment by DyaryRaoof** [comment] 2019-10-12 13:48
@cxq1221  did you solve the issue. I have been having this issue for about a month now. no solution really frustrating.

**Comment by caoyunxiao** [comment] 2019-10-14 01:56
This is a big problem that our team has also encountered. We hope the authorities can solve it as soon as possible

**Comment by DyaryRaoof** [comment] 2019-10-14 02:29
Hopefully they will. I have also opened another issue regarding this topic, no answer though.

**Comment by liyuqian** [comment] 2019-11-21 00:57
CC @gaaclarke who has commented on https://github.com/flutter/flutter/issues/44256 . Aaron: can you please try to see if this issue can be reproduced?

**Comment by gaaclarke** [comment] 2019-11-26 00:07
There are a few issues that have addressed this.  It sounds like some of the original comments are talking about a retain cycle with FlutterViewController, which isn't the case today.

Some of the comments talk about releasing resources when FlutterViewController is deleted, that was addressed in: https://github.com/flutter/engine/pull/13396 . It seems like some people may want to look into [FlutterViewController.allowHeadlessExecution](https://github.com/flutter/engine/blob/9f6401362d814eac9b35f88ddcaeac104e68b348/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L220).

One comment talks about the code in https://github.com/flutter/flutter/issues/32143 getting memory booted.  I just ran that on master and it doesn't get memory booted.  You can see when the image cache reaches a certain size it ejects things from memory.

I suggest we put out a call for a reproduction case that results in a memory boot on master.  That will help us definitively say if there is an issue still and what exactly it is since a few different things have been talked about.

**Comment by talisk** [comment] 2019-12-04 08:55
> There are a few issues that have addressed this. It sounds like some of the original comments are talking about a retain cycle with FlutterViewController, which isn't the case today.
> 
> Some of the comments talk about releasing resources when FlutterViewController is deleted, that was addressed in: [flutter/engine#13396](https://github.com/flutter/engine/pull/13396) . It seems like some people may want to look into [FlutterViewController.allowHeadlessExecution](https://github.com/flutter/engine/blob/9f6401362d814eac9b35f88ddcaeac104e68b348/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L220).
> 
> One comment talks about the code in #32143 getting memory booted. I just ran that on master and it doesn't get memory booted. You can see when the image cache reaches a certain size it ejects things from memory.
> 
> I suggest we put out a call for a reproduction case that results in a memory boot on master. That will help us definitively say if there is an issue still and what exactly it is since a few different things have been talked about.

Hi @gaaclarke . Compared to the solution that set allowHeadlessExecution to NO. I prefer to set allowHeadlessExecution to YES. And call destroyContext by a timer when the FlutterViewController dealloc. This should allow some code at the end can be executed.

**Comment by Hixie** [comment] 2020-01-09 01:46
Based on @gaaclarke's comments last year, it sounds like this bug is not really actionable any more, because it covers many topics. I recommend that for each individual thing you would like to see changed, you file a separate bug and describe the use case, the bug, how to reproduce the bug, and so forth. Thanks.

**Closed by Hixie** 2020-01-09 01:46 UTC
Labels: a: quality, customer: crowd, engine, f: routes, framework, severe: performance, team: gallery, waiting for customer response
