### ISSUE TITLE
IntrinsicHeight around Wrap(Text) is incorrect

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#63302] opened 2020-08-08 17:27 UTC
b/163101099

Intrinsic Height calculation for Wrap() widgets with overflowing text is incorrect, causing clipping/renderflex overflows.

This occurs in our app when we have maximum accessibility text size.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  State createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var useIntrinsicHeight = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'IntrinsicHeight',
      theme: ThemeData(primarySwatch: Colors.blue),
      darkTheme: ThemeData(primarySwatch: Colors.blue),
      home: MediaQuery(
        data: MediaQueryData(textScaleFactor: 3.2),
        child: Scaffold(
          appBar: AppBar(title: Text('IntrinsicHeight Test')),
          body: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              _wrapWidget(
                Wrap(
                  children: [
                    Text('Longer text 12345678'),
                    Text('Longer text 12345678'),
                  ],
                ),
              ),
              Center(
                child: RaisedButton(
                  onPressed: () =>
                      setState(() => useIntrinsicHeight = !useIntrinsicHeight),
                  child: Text('Toggle wrapping'),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }

  Widget _wrapWidget(Widget child) {
    if (!useIntrinsicHeight) {
      return Container(
        color: Colors.blue,
        child: child,
      );
    }

    return Container(
      color: Colors.green,
      child: IntrinsicHeight(child: child),
    );
  }
}
```

The expectation is that there should be no difference in height when IntrinsicHeight is toggled on or off.

**Comment by HansMuller** [comment] 2020-08-10 15:21
CC @chunhtai

**Comment by chunhtai** [comment] 2020-08-10 16:30
This looks like a duplicate of https://github.com/flutter/flutter/issues/61204
@Piinks  can you take a look at this?

**Comment by Piinks** [comment] 2020-08-10 16:44
Thanks! It looks like this is all coming from the same root issue. 
#61204 also demonstrates `Wrap` & `Text` issues related to intrinsic height, which is actually rooted in #48679.
cc @goderbauer 

Not sure how to best consolidate these issues, they do appear to be duplicates of the same root cause.

**Comment by chunhtai** [comment] 2020-08-10 21:27
assign my self for now as I am currently investigating a fix

**Comment by dannyvalentesonos** [comment] 2020-08-12 22:34
@goderbauer  Is there any chance this can be cherry picked into the 1.20 stable release?

**Comment by goderbauer** [comment] 2020-08-12 23:00
I don't think that this will qualify for a cherry-pick since it is neither a regression in that version nor a serious bug. 

/cc @pcsosinski

**Comment by chunhtai** [comment] 2020-08-18 16:20
fix is reverted due to internal test failure

**Comment by goderbauer** [comment] 2020-08-19 21:34
@chunhtai has a PR out to fix the internal failure and then we can re-apply the fix.

**Closed** 2020-08-25 17:01 UTC
Labels: P1, a: typography, cp: 1.20, customer: amplify, customer: money (g3), framework

**Comment by pcsosinski** [comment] 2020-08-31 16:16
will not CP for 1.20/1.21
