### ISSUE TITLE
Json Decoder Returning Only Errors

### ISSUE THREAD

**Issue by xeu100** [flutter/flutter#36583] opened 2019-07-20 00:24 UTC
## Steps to Reproduce

1. Use jsonDecoder with List<dynamic>

## Logs

https://paste.xeu100.com/?49310cd9a8bff62f#mUK+5HYLomwYfg4pyQLl3ukmkq8/REXAReAGny8nCVc=

```
Analyzing xid...

   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AccountElement._accountId, AccountElement._email, AccountElement._website - lib\elements\AccountElement.dart:3:7 -
          must_be_immutable
   info - The value of the field '_accountId' isn't used - lib\elements\AccountElement.dart:5:7 - unused_field
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AuthenticatorElement._authenticators, AuthenticatorElement._index - lib\elements\AuthenticatorElement.dart:8:7 -
          must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AuthenticatorList._authenticators - lib\elements\AuthenticatorList.dart:4:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: NavBarElement._currentPage - lib\elements\NavBarElement.dart:3:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: AccountPage._storage, AccountPage._authenticatorsController - lib\pages\AccountPage.dart:8:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: CreateAuthenticatorPage._secret, CreateAuthenticatorPage._nameController, CreateAuthenticatorPage._secretController,
          CreateAuthenticatorPage._digitsController, CreateAuthenticatorPage._periodController - lib\pages\CreateAuthenticatorPage.dart:6:7 - must_be_immutable

7 issues found. (ran in 4.7s)
```

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at D:\ProgramStorage\Applications\Flutter
    • Framework revision b712a172f9 (10 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\liamr\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Users\liamr\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5692245\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\liamr\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5692245
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Users\liamr\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.7479.19
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by stuartmorgan** [comment] 2019-07-20 00:37
From the link, the call that's failing is in:
> package:xid/VerifyData.dart:19

That's not Flutter code. If your code, or third-party code you are using, is passing data of the wrong type somewhere, that's an error that needs to be fixed in that code.

**Comment by xeu100** [comment] 2019-07-20 00:42
The code is correct and I've printed variables, they're all good. It worked then stopped working.

**Comment by stuartmorgan** [comment] 2019-07-20 01:47
You haven't provided the code necessary to reproduce this; from the stack it's not even possible to tell how JSON decoding is involved. It's simply not possible for anyone to investigate with the information you have provided.

If you are confident that this is a Flutter bug you need to file an issue that contains detailed reproduction steps, most importantly the actual code necessary to reproduce it (ideally a reduced test case).

**Comment by stuartmorgan** [comment] 2019-07-20 03:24
Since you seem to be focused on the fact that the bug is closed, rather than my explanation as to why, I'm going to re-open this for now. However, as explained above and in the duplicates, in the current state this can't be investigated.

Please provide the missing information necessary for someone to reproduce this bug: sample code and inputs that will reproduce it.

**Comment by xeu100** [comment] 2019-07-20 03:29
There isn't an amount of code I could give you, all my code and all my projects can't use the function jsonDecode(). No matter what I enter ("[]", "{"blah":"blah"}", for example), it returns a string, not the parsed version.

**Comment by stuartmorgan** [comment] 2019-07-20 03:37
It sounds like you have a minimal test case for this already, which is exactly what we need. So far you haven't provided any code that someone can reproduce this with, just a general description.

**Comment by xeu100** [comment] 2019-07-20 11:41
As I've said, there isn't one specific case where this happens. I restarted my machine and updated Flutter and suddenly all of my code functioned this way.

**Comment by stuartmorgan** [comment] 2019-07-20 12:43
We don't need every case, we just need one. With the actual code, so that someone other than you can run it and see if it's reproducible.

Let's try this another way: if you `flutter create` a new project, and make no changes at all other than adding `print(jsonDecode('[]').runtimeType);` in `main()` and an `import 'dart:convert';`, what is printed when you run it?

**Closed** 2019-07-20 13:09 UTC
Labels: waiting for customer response
