### ISSUE TITLE
Flutter channel master VS code colors not correct

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#75469] opened 2021-02-05 02:22 UTC
After switching out my Flutter install version from master to stable and back, my code color formatting is no longer correct. 

Right after the switching, I've encountered the following issue: https://github.com/microsoft/vscode/issues/115481

Swapping out the version for beta or stable seems to fix the problem. Please note: where the text is blue it's supposed to be white, I no longer see "symbols" such as \n formatted nicely, etc. 

A full reinstall of VS code and it's plugins, and of course multiple changes of the channel did not fix the issue. 

## Logs

<details>
<summary>Logs</summary>

```
Analyzing baby_sleep_scheduler...                                       

   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after
          v1.25.0-8.1.pre. • lib/views/activity/clear_logs/clear_logs_dialog.dart:43:27 • deprecated_member_use
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after
          v1.25.0-8.1.pre. • lib/views/activity/clear_logs/clear_logs_dialog.dart:61:27 • deprecated_member_use
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after
          v1.25.0-8.1.pre. • lib/views/activity/log_entry/delete_log_dialog.dart:35:21 • deprecated_member_use
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after
          v1.25.0-8.1.pre. • lib/views/activity/log_entry/delete_log_dialog.dart:57:21 • deprecated_member_use
   info • The value of the field '_labels' isn't used • lib/views/activity/log_entry/log_entry.dart:64:22 • unused_field
   info • Unused import: 'package:baby_sleep_scheduler/views/help/expandable_info.dart' • lib/views/help/help_view.dart:2:8 • unused_import
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after
          v1.25.0-8.1.pre. • lib/views/trainer/sleep/actions/end_session_dialog.dart:94:17 • deprecated_member_use
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after
          v1.25.0-8.1.pre. • lib/views/trainer/sleep/actions/end_session_dialog.dart:112:17 • deprecated_member_use

8 issues found. (ran in 2.6s)
```

```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.189, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-18.0.pre.189 at /home/user/Development/flutter
    • Framework revision 06e9456a90 (10 hours ago), 2021-02-04 11:51:03 -0500
    • Engine revision 0d6e529c22
    • Dart version 2.12.0 (build 2.12.0-285.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/user/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/user/Documents/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2021-02-05 13:53
Hi @ljmatan 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).

Per https://github.com/microsoft/vscode/issues/115481#issuecomment-770319552 seems that this was caused by a plugin.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-02-05 13:53 UTC
Labels: created via performance template
