### ISSUE TITLE
Will FlutterFire work in Flutter web?

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#32795] opened 2019-05-16 05:24 UTC
>[We intend to completely support all of Flutter's API and functionality across modern browsers.](https://github.com/flutter/flutter_web/blob/master/README.md)

This does not imply that there are plans to add support for Flutter web to all popular plugins, right?

Theoretically, it should not be a problem to add FlutterFire to Flutter web from what I can tell. It would just require another directory in plugins like `web`, which kind of already exists in Flutter web projects. Firebase is also fully supported for web.  
Now, I am just wondering if this is really the plan or not.

**Comment by KirolousNashaat** [comment] 2019-05-16 14:17
https://github.com/flutter/flutter/issues/32637#issuecomment-491947033

**Comment by creativecreatorormaybenot** [comment] 2019-05-16 14:51
@KirolousNashaat Well, it is not a Flutter plugin but rather for Dart for the web. I am not sure if this is the way that Flutter web is planned to make use of packages.

**Comment by kevmoo** [comment] 2019-05-24 18:54
Duplicate of https://github.com/flutter/flutter/issues/32637

**Closed by kevmoo** 2019-05-24 18:54 UTC
Labels: ☸ platform-web
