### ISSUE TITLE
Flutter Fire, Code Sample

### ISSUE THREAD

**Issue by msfasha** [flutter/flutter#90590] opened 2021-09-23 10:34 UTC
I struggled a little bit with the code sample available  [here](https://firebase.flutter.dev/docs/overview#initializing-flutterfire)

The FutureBuilder code sample did not work properly, stuck in the loading screen.
```dart
  if (snapshot.hasError) {
            return SomethingWentWrong();
          }
  
          // Once complete, show your application
          if (snapshot.connectionState == ConnectionState.done) {
            return MyAwesomeApp();
          }
  
          // Otherwise, show something whilst waiting for initialization to complete
          return Loading();
        },

had to use if else statements to activate state-full behavior

```dart
 if (snapshot.hasError) {
          displayWidget = const ErrorScreen();
        }

        // Once complete, show your application
        else if (snapshot.connectionState == ConnectionState.done) {
          displayWidget = const HomeScreen();
        }

        // Otherwise, show something whilst waiting for initialization to complete
        else {
          displayWidget = const Center(
            child: CircularProgressIndicator(),
          );  
        }

I am not sure if there are any differences between the build and the future build to cause such behavior.

**Comment by TahaTesser** [comment] 2021-09-23 10:37
Hi @msfasha 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-23 10:37 UTC
Labels: in triage
