### ISSUE TITLE
Can't retry passing tests

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#81517] opened 2021-04-29 23:16 UTC
Today we had a test suddenly start failing. It would be good to be able to rerun past cases of this test (on older commits) to find out if it was something that started because of a commit or something that was always broken / newly broken independent of the commits. Currently, however, there's no way to rerun a test that's passed. You can click rerun, but it doesn't do anything (though it does tell you it will).

**Comment by godofredoc** [comment] 2021-04-30 04:20
The task should be reporting that it failed to re-try the task that's a bug. Preventing from running a succeeded task was intended but we can enable that again.

**Comment by yusufm** [comment] 2021-05-03 17:24
Historically, we have not supported rerunning previously green tasks because of some unwanted scenarios that can crop up.

For the engine atleast, if retrying tasks that generate artifacts, and a retry is performed on a release commit, it will overwrite the newer artifacts.

Additionally, cocoon does not track task history, only the latest result, so retries on previously green runs could also close the tree.

**Comment by Hixie** [comment] 2021-05-03 19:22
> For the engine atleast, if retrying tasks that generate artifacts, and a retry is performed on a release commit, it will overwrite the newer artifacts.

That does seem like a problem. Is there some way we can flag shards that have side-effects so that they can't be rerun?

> Additionally, cocoon does not track task history, only the latest result, so retries on previously green runs could also close the tree.

That's a feature, not a bug. The way we have it now is sort of backwards. A test that sometimes fails and sometimes passes is a failing test, but we mark it as passing. We really should mark flaky tests as failing, not passing. If anything, we should detect that a test has a history of failing, and retry it automatically several times until it fails.

**Comment by godofredoc** [comment] 2021-05-03 20:11
> > For the engine atleast, if retrying tasks that generate artifacts, and a retry is performed on a release commit, it will overwrite the newer artifacts.
> 
> That does seem like a problem. Is there some way we can flag shards that have side-effects so that they can't be rerun?
> 
One example of this problem is:

A given commit is released(any release channel) and someone accidentally retries that build creating new artifacts. Because the new artifacts never went through the release process they never get signed.

> > Additionally, cocoon does not track task history, only the latest result, so retries on previously green runs could also close the tree.
> 
> That's a feature, not a bug. The way we have it now is sort of backwards. A test that sometimes fails and sometimes passes is a failing test, but we mark it as passing. We really should mark flaky tests as failing, not passing. If anything, we should detect that a test has a history of failing, and retry it automatically several times until it fails.

This sounds like functionality that needs to be implemented as a separate service potentially running overnight to avoid impacting the development workflows.

**Comment by godofredoc** [comment] 2021-05-13 22:28
We are going to implement a tool to run overnight and collect and report flakiness.

**Comment by CaseyHillers** [comment] 2022-03-10 18:23
This was fixed in https://github.com/flutter/flutter/pull/99375

**Comment by CaseyHillers** [comment] 2022-03-10 18:24
Feel free to open another bug if we're still interested in collecting flakiness metrics in off peak hours

**Closed by CaseyHillers** 2022-03-10 18:23 UTC
Labels: passed first triage, team: infra, passed secondary triage, P4
