### ISSUE TITLE
App Store Connect Operation ErrorInvalid Bundle. The bundle Runner.app/Frameworks/App.framework does not support the minimum OS Version specified in the Info.plist.

### ISSUE THREAD

**Issue by youraleangseng** [flutter/flutter#68403] opened 2020-10-17 14:29 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by sidrao2006** [comment] 2020-10-17 15:19
Duplicate of #68404
@youraleangseng , if you have opened this issue by mistake, please close it.
Thanks

**Closed** 2020-10-17 17:28 UTC
