### ISSUE TITLE
macos flutter auth google_sign_in

### ISSUE THREAD

**Issue by omniiidemo** [flutter/flutter#87096] opened 2021-07-27 09:29 UTC
how can support login auth on Mac
inside pod file macOS

pod 'GoogleSignIn'
[!] The platform of the target `Runner` (macOS 10.12) is not compatible with `GoogleSignIn (6.0.1)`, which does not support `macOS`.

also google maps

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment] 2021-07-27 09:35
Duplicate of https://github.com/flutter/flutter/issues/46157

**Closed by stuartmorgan** 2021-07-27 09:35 UTC

**Comment by stuartmorgan** [comment] 2021-07-27 12:39
Since you seem to be confused about the issue I marked this as a duplicate of: the reason the plugin doesn't work for you on macOS is that the plugin doesn't currently support macOS. There isn't a command you can run that will work.
