### ISSUE TITLE
[proposal] Icon rendering should be tested and it's failure should be traceable

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#76442] opened 2021-02-20 08:32 UTC
the latest master does not display [Icons](https://api.flutter.dev/flutter/material/Icons-class.html)
no errors in the logs

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Center(
            child: Icon(Icons.image),
          ),
        ),
      ),
    );

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.27.0-5.0.pre.89, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-5.0.pre.89 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 1b871036f9 (82 minutes ago), 2021-02-20 01:56:02 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.182 snap

! Doctor found issues in 1 category.
```

</details>

<details>
<summary>android screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/108589268-4d8ee180-7366-11eb-9586-951d8da28bb8.png)

</details>

<details>
<summary>web screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/108589291-6d260a00-7366-11eb-93e4-69c8c23b2cb3.png)

</details>

<details>
<summary>linux screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/108589360-9ba3e500-7366-11eb-8ec4-1b01e408202f.png)

</details>

**Comment by darshankawar** [comment] 2021-02-22 08:46
Hi @iapicca 
Seems to be fixed in latest master (`1.27.0-5.0.pre.94`)

Android:

<img width="545" alt="Screenshot 2021-02-22 at 2 08 00 PM" src="https://user-images.githubusercontent.com/67046386/108684082-68a15300-7518-11eb-9967-30f4f4cbe28c.png">


Web:

<img width="663" alt="Screenshot 2021-02-22 at 2 14 42 PM" src="https://user-images.githubusercontent.com/67046386/108684102-6d660700-7518-11eb-86f7-789e96435d6f.png">

Feel free to close once you verify at your end on latest version.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-5.0.pre.94, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-5.0.pre.94 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 5642bed237 (6 hours ago), 2021-02-21 21:41:03 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.182

! Doctor found issues in 1 category.

```

</details>

**Comment by iapicca** [comment] 2021-02-22 09:20
@darshankawar 
I confirm that the issue is solved in the (new) latest master
```
[✓] Flutter (Channel master, 1.27.0-5.0.pre.94, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-5.0.pre.94 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 5642bed237 (6 hours ago), 2021-02-21 21:41:03 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)
```

if you agree I'd redirect the issue to a proposal 

#### expected result:

 - icon failing to render  should throw an `Exception` or at the very least produce some kind of output in the logs
 - a test should verify that the Icon is rendered properly (see also https://github.com/flutter/flutter/issues/62472) preventing regressions

 #### actual result:

- icon render fails silently
- even if short lived, a regression occurred

**Comment by darshankawar** [comment] 2021-02-22 13:38
Agree with you on the proposal front.

**Comment by tbarbette** [comment] 2021-05-29 10:13
Please upscale this. This is very bad for customers and do re-appear from time to time... See https://github.com/flutter/flutter/issues/80646#issuecomment-850808662 .

**Comment by iapicca** [comment] 2021-06-06 15:43
> Please upscale this. This is very bad for customers and do re-appear from time to time... See [#80646 (comment)](https://github.com/flutter/flutter/issues/80646#issuecomment-850808662) .

@tbarbette 
I struggle to understand why something so important isn't part of `goldens` already

**Comment by guidezpl** [comment] 2022-04-26 07:58
Hi, since we have icon golden tests at https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/icons_test.dart#L62-L126, and additionally icon codepoints are now guaranteed to be stable between updates (this was the root cause of the mentioned issues), I'll close this issue. If you believe I've made an error, please reply here with more details that explain the difference and we'll re-open this issue.

**Closed by guidezpl** 2022-04-26 07:58 UTC
Labels: severe: new feature, framework, f: material design, proposal, severe: rendering, a: error message, will affect goldens, passed first triage, P5
