### ISSUE TITLE
After installing flutter snap on Ubuntu 22.04.1, flutter doctor displays error: unsupported value for gpg.format: ssh

### ISSUE THREAD

**Issue by thejacer87** [flutter/flutter#130314] opened 2023-07-11 06:07 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.     Install flutter using sudo snap install flutter --classic
2.     Run flutter doctor -v
3.     .gitconfig uses ssh format for GPG commit signing

### Expected results

flutter should work

### Actual results

because it cant find what version of flutter it is using, i get messages like this for certain packages:

`Because my_app depends on provider >=4.0.0-dev which requires Flutter SDK version >=1.12.1, version solving failed.
exit code 1`

### Code sample

n/a

### Screenshots or Video

n/a

### Logs

n/a

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
Failed to find the latest git commit date: VersionCheckError: Command exited with code
128: git -c log.showSignature=false log HEAD -n 1 --pretty=format:%ad --date=iso
Standard out: 
Standard error: error: unsupported value for gpg.format: ssh
fatal: bad config variable 'gpg.format' in file '/home/jbennest/.gitconfig' at line 15

Returning 1969-12-31 16:00:00.000 instead.
[!] Flutter (Channel stable, 0.0.0-unknown, on Ubuntu 22.04.2 LTS 5.19.0-46-generic,
    locale en_CA.UTF-8)
    ! Flutter version 0.0.0-unknown on channel stable at
      /home/jbennest/snap/flutter/common/flutter
      Cannot resolve current version, possibly due to local changes.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision  (), 1969-12-31 16:00:00.000
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/jbennest/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu122.04.2)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/jbennest/Development/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34)
      (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.2 LTS
      5.19.0-46-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome
      114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by huycozy** [comment] 2023-07-11 08:42
>Standard error: error: unsupported value for gpg.format: ssh

Hi @thejacer87 
It seems the issue is related to Git. Please try updating Git and then retry to see if it works (see this [SO anwser](https://stackoverflow.com/questions/74722894/error-unsupported-value-for-gpg-format-ssh))

**Comment by thejacer87** [comment] 2023-07-11 15:20
> > Standard error: error: unsupported value for gpg.format: ssh
> 
> Hi @thejacer87 It seems the issue is related to Git. Please try updating Git and then retry to see if it works (see this [SO anwser](https://stackoverflow.com/questions/74722894/error-unsupported-value-for-gpg-format-ssh))

```
$ git version
git version 2.34.1
```

forgot to mention that i already have the latest git. but i think the problem is the version of git wrapped in the snap somehow

**Comment by huycozy** [comment] 2023-07-12 03:55
>fatal: bad config variable 'gpg.format' in file '/home/jbennest/.gitconfig' at line 15

Please check `.gitconfig` file at line 15 if there is an issue.

>/home/jbennest/snap/flutter/common/flutter
      Cannot resolve current version, possibly due to local changes.

And make sure there is no local change then retry to see if it works.

Also, can you try installing Flutter manually to see if the issue still persists or not?

**Comment by thejacer87** [comment] 2023-07-12 05:06
line 15 

```
[gpg]
	format = ssh
```

which is a new feature for git 2.34

installing flutter manually did work, but the whole point of the snap is to avoid doing all that extra work

**Comment by huycozy** [comment] 2023-07-12 08:56
Can you try `unset` `gpg.format` to see if it works? (see this [SO](https://stackoverflow.com/a/72950012))

```
git config --global --unset gpg.format
```

**Comment by thejacer87** [comment] 2023-07-12 19:47
while this may work (havent tried yet). another project im working on requires ssh gpg so this isnt a solution

**Comment by huycozy** [comment] 2023-07-13 04:42
For this case, I would recommend you open an issue in [`snap` dedicated repository](https://github.com/canonical/flutter-snap/issues) for better support there. 

Closing as it's not a Flutter issue. If you disagree, please write in the comments with more information and I will reopen this for further investigation. Thanks!

**Closed by huycozy** 2023-07-13 04:42 UTC
Labels: in triage
