### ISSUE TITLE
The method 'setState' isn't defined for the type 'NasabahDataTableSource'.

### ISSUE THREAD

**Issue by azmi1700018002** [flutter/flutter#104223] opened 2022-05-20 03:24 UTC
This is mystatefullwidget.
```
import 'package:flutter/material.dart';
import 'package:flutter_auth/Models/nasabah.dart';
import 'package:flutter_auth/network/nasabah_service.dart';
import 'package:flutter_auth/screens/Menu/DataNasabah/detailnasabah.dart';


import 'package:shared_preferences/shared_preferences.dart';
import 'dart:convert';

class DataNasabah extends StatefulWidget {
  @override
  _DataNasabahState createState() => _DataNasabahState();
}

class _DataNasabahState extends State<DataNasabah> {
  String nama_debitur = '';
  List<Nasabah> _nasabah = [];


  @override
  void initState() {
    super.initState();
    _loadUserData();
    _getNasabah();
  }

  _loadUserData() async {
    SharedPreferences localStorage = await SharedPreferences.getInstance();
    var user = jsonDecode(localStorage.getString('user'));

    if (user != null) {
      setState(() {
        nama_debitur = user['nama_debitur'];
      });
    }
  }

  _getNasabah() {
    NasabahService.getUser().then((nasabah) {
      if (mounted) {
        setState(() {
          _nasabah = nasabah;
        });
      }
    });
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text('Data Nasabah'),
        backgroundColor: Color(0xff151515),
        // automaticallyImplyLeading: false,
      ),
      body: SingleChildScrollView(
        child: PaginatedDataTable(
          rowsPerPage: 10,
          columns: [
            DataColumn(
              label: Expanded(
                  child: Text(
                'ID Nasabah',
                textAlign: TextAlign.center,
              )),
            ),
            DataColumn(
              label: Expanded(
                  child: Text(
                'Nama Nasabah',
                textAlign: TextAlign.center,
              )),
            ),
            DataColumn(
              label: Expanded(
                  child: Text(
                'Aksi',
                textAlign: TextAlign.center,
              )),
            ),
          ],
          source: NasabahDataTableSource(userData: _nasabah, context: context),
        ),
      ),
    );
  }
}
```
I want to use setState method in this class.but cann't use.I
comment setState place
```
class NasabahDataTableSource extends DataTableSource {
  BuildContext context;
  NasabahDataTableSource({this.context, this.userData});
  final List<Nasabah> userData;

  @override
  DataRow getRow(int index) {
    return DataRow.byIndex(
      index: index,
      cells: [
        DataCell(Align(
            alignment: Alignment.center,
            child: Text(
              "${userData[index].id}",
            ))),
        DataCell(Align(
          alignment: Alignment.center,
          child: Text("${userData[index].nama_debitur}"),
        )),
        DataCell(
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              IconButton(
                icon: Icon(Icons.navigate_next),
                color: Colors.blueAccent,
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) =>
                          DetailNasabah(
                            nasabah: userData[index],
                          ),
                    ),
                  );
                },
              ),
              IconButton(
                icon: Icon(Icons.delete),
                color: Colors.red,
                onPressed: () {
                  showDialog(
                    context: context,
                    builder: (context) =>
                        AlertDialog(
                          title: Text('Hapus Data Nasabah'),
                          content: Text(
                              'Apakah anda yakin ingin menghapus data nasabah ini?'),
                          actions: [
                            TextButton(
                                child: Text('Yes'),
                                onPressed: () {
                                  NasabahService.deleteUser(userData[index].id);
                                  setState(() {
                                    //Cann't use
                                  });
                                })
                          ],
                        ),
                  );
                },
              )
            ],
          ),
        ),
      ],
    );
  }
```
i haven't find that solution.
Please help.

**Comment by danagbemava-nc** [comment] 2022-05-20 08:21
Hi @azmi1700018002, this is working as intended. You can only call `setState` from either a `StatefulBuilder` or a `StatefulWidget`. 

What you can do, is find a way to refresh your UI after the deletion is complete. 

You can also just pass in the callbacks from your main UI into your `DataTableSource` class so that it can be handled in the UI. 

Your `NasabahDataTableSource` class could end up looking like the code below. This makes it easier for you to update the actions that you might want to perform after the items have been clicked. 

<details>
<summary>code sample</summary>

```dart
class NasabahDataTableSource extends DataTableSource {
  final VoidCallback onNavigateNextPressed;
  final VoidCallback onDeletePressed;

  NasabahDataTableSource({required this.onDeletePressed, required this.onNavigateNextPressed, this.userData});
  final List<Nasabah> userData;

  @override
  DataRow getRow(int index) {
    return DataRow.byIndex(
      index: index,
      cells: [
        DataCell(Align(
            alignment: Alignment.center,
            child: Text(
              "${userData[index].id}",
            ))),
        DataCell(Align(
          alignment: Alignment.center,
          child: Text("${userData[index].nama_debitur}"),
        )),
        DataCell(
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              IconButton(
                icon: Icon(Icons.navigate_next),
                color: Colors.blueAccent,
                onPressed: onNavigateNextPressed
              ),
              IconButton(
                icon: Icon(Icons.delete),
                color: Colors.red,
                onPressed: onDeletePressed
              )
            ],
          ),
        ),
      ],
    );
  }
}
```
</details>

Closing this as this is working as intended.

**Closed by danagbemava-nc** 2022-05-20 08:21 UTC
Labels: in triage
