### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 6075 pos 12: 'child == _child': is not true.

### ISSUE THREAD

**Issue by Ching0110** [flutter/flutter#90507] opened 2021-09-22 07:56 UTC
```console
Performing hot reload...
Syncing files to device AOSP on IA Emulator...

======== Exception caught by widgets library =======================================================
The following assertion was thrown building UnmanagedRestorationScope:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4633 pos 12: 'child == _child': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/PC/Desktop/flutter_food_delivery/lib/main.dart:13:12
When the exception was thrown, this was the stack: 
#2      ComponentElement.forgetChild (package:flutter/src/widgets/framework.dart:4633:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3563:14)
...     Normal element mounting (36 frames)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
...
====================================================================================================
Reloaded 0 libraries in 229ms.

======== Exception caught by widgets library =======================================================
The following assertion was thrown building AnimatedBuilder(animation: ValueNotifier<bool>#4e0e9(false), state: _AnimatedState#3cb98):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 6075 pos 12: 'child == _child': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/PC/Desktop/flutter_food_delivery/lib/main.dart:13:12
When the exception was thrown, this was the stack: 
#2      SingleChildRenderObjectElement.forgetChild (package:flutter/src/widgets/framework.dart:6075:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3563:14)
...     Normal element mounting (4 frames)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKeys detected in widget tree.

The following GlobalKeys were specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The keys were:
- [GlobalKey#b6147]
  [LabeledGlobalKey<OverlayState>#15c3c]
This was determined by noticing that after widgets with the above global keys were moved out of their respective previous parents, those previous parents never updated during this frame, meaning that they either did not update at all or updated before the widgets were moved, in either case implying that they still think that they should have a child with those global keys.
The specific parents that did not update after having one or more children forcibly removed due to GlobalKey reparenting are:
- IgnorePointer(ignoring: false, renderObject: RenderIgnorePointer#6d36b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE DETACHED)
  UnmanagedRestorationScope
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2900:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2925:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:877:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
...
====================================================================================================
```

When I click on the issue, it redirect to the MaterialApp which is below this code :

```dart
import 'package:flutter/material.dart';
import 'login.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: login(),
    );
  }
}
```

```
C:\Users\PC\Desktop\flutter_food_delivery>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.572], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code (version 1.59.1)
[√] Connected device (3 available)

• No issues found!

```

**Comment by maheshmnj** [comment] 2021-09-22 08:03
Hi @Ching0110, Thanks for filing the issue. Please share the complete reproducible code that should be ready to run with minimal or no code changes, with the exact steps to reproduce the issue. 

Thanks.

**Comment by Ching0110** [comment] 2021-09-22 08:18
This is my code:

class FoodListPage extends StatefulWidget {
  @override
  _FoodListPage createState() => _FoodListPage();
}

class _FoodListPage extends State<FoodListPage> with SingleTickerProviderStateMixin {

  ProductCtg data = new ProductCtg();

  getStringValuesSF() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    //Return String
    setState(() {
      Map json = jsonDecode(prefs.getString('product_list'));
      data = ProductCtg.fromJson(json);
      print('Get product_list: ' + data.toString());
    });
  }

  bool isCollapsed = false;
  AutoScrollController scrollController;
  TabController tabController;

  final double expandedHeight = 500.0;
  final double collapsedHeight = kToolbarHeight;

  final listViewKey = RectGetter.createGlobalKey();
  Map<int, dynamic> itemKeys = {};

  bool pauseRectGetterIndex = false;

  @override
  void initState() {
    getStringValuesSF();
    tabController = TabController(length: data.result.list.length, vsync: this);
    scrollController = AutoScrollController();
    super.initState();
  }

  @override
  void dispose() {
    scrollController.dispose();
    tabController.dispose();
    super.dispose();
  }

  void onCollapsed(bool value) {
    if (this.isCollapsed == value) return;
    setState(() => this.isCollapsed = value);
  }

  void animateAndScrollTo(int index) {
    pauseRectGetterIndex = true; 
    tabController.animateTo(index);
    scrollController
        .scrollToIndex(index, preferPosition: AutoScrollPosition.begin)
        .then((value) => pauseRectGetterIndex = false);
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      //extendBodyBehindAppBar: true,
      //backgroundColor: scheme.background,
      backgroundColor:Colors.white,
      body: RectGetter(
        key: listViewKey,
        child: NotificationListener<ScrollNotification>(
          child: buildSliverScrollView(),
          //onNotification: onScrollNotification,
        ),
      ),
    );
  }

  Widget buildSliverScrollView() {
    return CustomScrollView(
      controller: scrollController,
      slivers: [
        buildAppBar(),
        
    );
  }

  SliverAppBar buildAppBar() {
    return ImageAppBar(
      data: data,
      context: context,
      scrollController: scrollController,
      expandedHeight: expandedHeight,
      collapsedHeight: collapsedHeight,
      isCollapsed: isCollapsed,
      onCollapsed: onCollapsed,
      tabController: tabController,
      onTap: (index) => animateAndScrollTo(index),    );
  }

}

**Comment by Ching0110** [comment] 2021-09-22 08:19
Does anyone know how to solve this kind of problem?

**Comment by shatanikmahanty** [comment] 2021-09-22 08:52
Is RectGetter a custom widget made by you?

**Comment by Ching0110** [comment] 2021-09-22 09:21
no. I am new to Flutter. I would like to do something like when clicking on a category, it should scroll to a position in the vertical list of categories. And when scrolling the vertical list, the active category at the top should also update the currently active category. Both the data of category and vertical list of items are retrieved from JSON.

**Comment by Ching0110** [comment] 2021-09-22 09:23
The example that I see is from here [](https://github.com/theachoem/food_panda_sticky_header)

**Comment by Ching0110** [comment] 2021-09-22 09:24
The example that I refer is from here     [https://github.com/theachoem/food_panda_sticky_header](url)

**Comment by maheshmnj** [comment] 2021-09-22 09:29
@Ching0110  The code sample you provided above contains unknown variables and is not sufficient enough to diagnose the cause of the issue, Also it looks like you are asking for support on your personal code. The issue tracker is to track only the issues in the Flutter framework, If you need further help please try asking such questions on a community forum like StackOverflow and you may get some help. 

Closing this issue as invalid. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-22 09:29 UTC
Labels: in triage
