### ISSUE TITLE
I got this issue when I update to the latest flutter stable version, how can I do to fix this? My screen is always flickering.

### ISSUE THREAD

**Issue by denghejun** [flutter/flutter#127089] opened 2023-05-18 06:18 UTC
Sorry, this is an accidental problem. When trying to reproduce, the bug of the flash screen cannot be reproduced.

_Originally posted by @mazhengshui in https://github.com/flutter/flutter/issues/121583#issuecomment-1452804915_

```
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)
```
```
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.1, on macOS
    12.6.5 21G531 darwin-x64, locale en-CN)
    • Flutter version 3.10.1 on channel stable at
      /Users/me/Code/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (29 hours
      ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • Pub download mirror
      https://pub.flutter-io.cn
    • Flutter download mirror
      https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android
    devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/ja
      va
    • Java version OpenJDK Runtime Environment
      (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at
      /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-fl
      utter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-da
      rt
    • Java version OpenJDK Runtime Environment
      (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version
    2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA
      CE.app
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4345.14

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008101-001814E13A30001E
      • ios            • iOS 16.1.1 20B101
    • macOS (desktop) • macos
      • darwin-x64     • macOS 12.6.5 21G531
      darwin-x64
    • Chrome (web)    • chrome
      • web-javascript • Google Chrome
      113.0.5672.92

[✓] Network resources
    • All expected network resources are
      available.

• No issues found!
```

**Comment by denghejun** [comment] 2023-05-18 06:28
I met this issue today, now I can not move forward on my project. I need to do a release for my app today, how can I do, can I back to old flutter stable version? how should I do?

**Comment by darshankawar** [comment] 2023-05-18 09:59
Closing this as a self-duplicate of https://github.com/flutter/flutter/issues/127084. Please don't open multiple issues for same reason.

**Closed by darshankawar** 2023-05-18 09:59 UTC
Labels: in triage
