### ISSUE TITLE
[google_maps_flutter]: Polyline patterns doesn't work for iOS, but works on android.

### ISSUE THREAD

**Issue by shreymahendru** [flutter/flutter#57523] opened 2020-05-18 20:39 UTC
iOS: 
<img width="466" alt="Screen Shot 2020-05-18 at 4 34 22 PM" src="https://user-images.githubusercontent.com/14631262/82257157-902e1400-9925-11ea-8522-1539473f617a.png">

Android: 
![Screen Shot 2020-05-18 at 4 36 00 PM](https://user-images.githubusercontent.com/14631262/82257259-b5bb1d80-9925-11ea-8b92-b951dcdcdd3b.png)

Relevant Code: 
```
Polyline polyline = Polyline(
      polylineId: PolylineId("poly"),
      color: Color(0xffff6d00),
      points: coords,
      jointType: JointType.round,
      patterns: [PatternItem.dot, PatternItem.gap(10)],
    );
```
Version: 
google_maps_flutter: ^0.5.27+3

**Comment by VladyslavBondarenko** [comment] 2020-05-19 10:46
Complete reproducible code sample

```
import 'dart:async';
import 'package:flutter/material.dart';

import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(Main());

class Main extends StatefulWidget {
  @override
  _MainState createState() => _MainState();
}

class _MainState extends State<Main> {
  Set<Polyline> lines = {};

  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
      target: LatLng(12.988827, 77.472091),
      zoom: 13
  );

  @override
  void initState() {
    super.initState();
    lines.add(
      Polyline(
        points: [
          LatLng(12.988827, 77.472091),
          LatLng(12.980821, 77.470815),
          LatLng(12.969406, 77.471301)
        ],
        endCap: Cap.squareCap,
        geodesic: false,
        polylineId: PolylineId("line_one"),
        patterns: [PatternItem.dot, PatternItem.gap(10)]
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Google Maps Polylines',
      home: Scaffold(
        body: GoogleMap(
          initialCameraPosition: _kGooglePlex,
          onMapCreated: (GoogleMapController controller) {
            _controller.complete(controller);
          },
          polylines: lines,
        ),
      ),
    );
  }
}
```

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision 456d80b9dd (8 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • Redmi Note 7      • 6345c469                             • android-arm64  • Android 9 (API 28)
    • iPhone 11 Pro Max • 5D5365D0-C0F6-4440-B758-FFA83896129E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4
      (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server        • web-server                           • web-javascript • Flutter Tools
    • Chrome            • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-01-14 14:46
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86 • Android 10 (API 29) (emulator)
    • Taha’s iPad (mobile)               • 00008020-000255113EE8402E • ios         • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.337, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.337 at /Users/tahatesser/Code/flutter_master
    • Framework revision 0768daaae3 (4 hours ago), 2021-01-14 05:39:03 -0500
    • Engine revision 1b5e16cda2
    • Dart version 2.12.0 (build 2.12.0-223.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 10 (API 29) (emulator)
    • Taha’s iPad (mobile)               • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)                    • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by vanlooverenkoen** [comment] 2021-02-09 13:30
Duplicate of https://github.com/flutter/flutter/issues/60083

I already added it here: https://github.com/flutter/plugins/pull/3441
pr jobs are failing but no one can tell me why. :(

**Comment by TahaTesser** [comment] 2021-02-10 11:40
closing as a duplicate of https://github.com/flutter/flutter/issues/60083

**Closed by TahaTesser** 2021-02-10 11:40 UTC
Labels: found in release: 1.22, found in release: 1.26, has reproducible steps, p: maps, platform-ios, plugin
