### ISSUE TITLE
Can't find views in a 3-tab page (Possible race condition)

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#4194] opened 2016-05-25 22:45 UTC
## Steps to Reproduce

Test code:

```dart
    test('swipes', () async {
      SerializableFinder body = await find.byValueKey('body');
      await new Future<Null>.delayed(new Duration(milliseconds: 500));
      await findTab1Content();
      await driver.scroll(body, -200.0, 0.0, new Duration(milliseconds: 200));
      await new Future<Null>.delayed(new Duration(milliseconds: 500));
      await findTab2Content();
      await driver.scroll(body, -200.0, 0.0, new Duration(milliseconds: 200));
      await new Future<Null>.delayed(new Duration(milliseconds: 500));
      await findTab3Content();
      await driver.scroll(body, 200.0, 0.0, new Duration(milliseconds: 200));
      await new Future<Null>.delayed(new Duration(milliseconds: 500));
      await findTab2Content();
      await driver.scroll(body, 200.0, 0.0, new Duration(milliseconds: 200));
      await findTab1Content();
    });
```

With the Future<Null>.delayed()... lines, the test runs successfully.  Without those lines, the test fails.  In the emulator running the test, it will swipe right twice to get to tab 3, then swipe left once back to tab 2, wait ~5 seconds, and then fail.  The logs indicate that it fails to find content that lives on tab 3.

## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /usr/local/bin/flutter
    • Framework revision cc93170894 (2 weeks ago), engine revision 98f020ff2d

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at /usr/dir/of/android-sdk-linux
    • Platform android-N, build-tools 24.0.0-preview
    • OpenJDK Runtime Environment

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

## Logs and Crash Reports

Flutter logs:
`
--------- beginning of main
--------- beginning of system
I/flutter : Observatory listening on http://127.0.0.1:36085
I/flutter : Diagnostic server listening on http://127.0.0.1:48470
I/flutter : ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter : The following message was thrown during a service extension callback for "ext.flutter.driver":
I/flutter : Timed out waiting for text "Text from Tab 3"
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      FlutterDriverExtension.waitFor.<waitFor_async_body> (package:flutter_driver/src/extension.dart)
I/flutter : #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
I/flutter : #2      _RootZone.runBinary (dart:async/zone.dart:1210)
I/flutter : #3      _FutureListener.handleError (dart:async/future_impl.dart:146)
I/flutter : #4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:640)
I/flutter : #5      _Future._propagateToListeners (dart:async/future_impl.dart:662)
I/flutter : #6      _Future._completeError (dart:async/future_impl.dart:476)
I/flutter : #7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:528)
I/flutter : #8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
I/flutter : #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
I/flutter : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`
Flutter driver output: go/flutter-crash-djshuckerow-5-25-16

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by abarth** [comment] 2016-05-26 00:53
@yjbanov

**Comment by yjbanov** [comment] 2016-05-26 01:00
For now let's assume this is duplicate of https://github.com/flutter/flutter/issues/4195. If that does fix it, we'll reopen.

**Closed by yjbanov** 2016-05-26 01:00 UTC

**Comment by HansMuller** [comment] 2016-05-26 15:00
The fling gesture `await driver.scroll(body, -200.0, 0.0, new Duration(milliseconds: 200));` triggers an animation that materializes and exposes the newly selected tab. I don't think you want to sample the tab bar's state before the animation has completed, so the 500ms delays make sense.
