### ISSUE TITLE
google_sign_in V 3.0.4 throws PlatformException on very first signin

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#19598] opened 2018-07-20 11:15 UTC
Hi,

I implemented FirebaseAuth together with google_signin V 3.0.4 which most of the time works but: 

If I use a blank emulator where I haven't have logged in into my google account before the App freezes after the browser screen closes and when tapping on the app it throws this platform exception:

![image](https://user-images.githubusercontent.com/16635729/42999377-c61556c6-8c1d-11e8-9e93-beabed4150bb.png)

It happens when `signIn()` in google_signin.dart is called.

You can see it in this screencast https://www.screencast.com/t/gxPujx6sqqvd

I attach a logcat recording of that session
[locat.txt](https://github.com/flutter/flutter/files/2213632/locat.txt)

my current Flutter version:

```
[√] Flutter (Channel master, v0.5.8-pre.37, on Microsoft Windows [Version 10.0.17134.165], locale de-DE)
    • Flutter version 0.5.8-pre.37 at C:\Entwicklung\Flutter
    • Framework revision e22f99743b (8 days ago), 2018-07-12 14:18:29 -0700
    • Engine revision ce06bbac58
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 32-bit edition (version 1.25.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.16.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by escamoteur** [comment] 2018-07-20 15:33
I now debugged the plugin using AS to connect to my App and found out that the Error is already returned from the native GoogleSignIn API.

**Comment by mouadelamrani** [comment] 2018-08-19 23:53
i am having the same problem, and i don't know how to solve it! 
is there a solution or i have to skip/ignore the error?

**Comment by ram231** [comment] 2018-08-21 07:48
I really don't know why this throws an error instead of providing a function "onCancel()" whenever the user taps outside the dialog or the internet connection has been disconnected.

**Comment by jParliaments** [comment] 2018-09-18 13:05
Did you checked for adding fingerprint @firebase ?

**Comment by escamoteur** [comment] 2018-09-18 13:08
sure, it works after the first try

**Comment by knewter** [comment] 2018-10-15 00:39
I ran into the same problem tonight as well.

**Comment by escamoteur** [comment] 2018-10-15 06:59
@eseidel this really should be fixed for a Google product

**Comment by escamoteur** [comment] 2018-10-17 05:57
@timsneath could you set some one on this plase?

**Comment by escamoteur** [comment] 2018-10-17 16:51
@timsneath Sorry, didn't mean it like you should ordering someone . But I think its kind of embarrassing for a Google Product if it crashes if you sign in on a blank phone.

**Comment by cyanglaz** [comment] 2019-04-15 22:46
@escamoteur Do you still experience this issue if you update the google_sign_in to the latest version?
It seems to be working when I tried.

**Comment by escamoteur** [comment] 2019-05-03 09:18
@cyanglaz Hi, I'm sorry but I'm currently no longer on that project so I cannot easily verify.

**Comment by cyanglaz** [comment] 2019-05-03 15:36
Sorry that we have to close this issue because we couldn't gather enough details to proceed. If anyone found the same issue and can provide detailed step to reproduce, please feel empowered to open another issue with details!.

**Closed by cyanglaz** 2019-05-03 15:36 UTC
Labels: p: firebase, p: first party, p: google_sign_in, plugin, severe: crash

**Comment by kroikie** [comment] 2019-10-13 19:01
@escamoteur

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/748. Any further collaboration will be done there.
