### ISSUE TITLE
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: LateInitializationError: Field 'sharedPreferences' has not been initialized.

### ISSUE THREAD

**Issue by kayceetann** [flutter/flutter#106535] opened 2022-06-24 04:11 UTC
App was previously working. After I installed easy_localization, and added some codes to setup the language translation, the app still managed to build but it returned this exception. 

[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: LateInitializationError: Field 'sharedPreferences' has not been initialized.

The issue is I don't even use the field 'sharedPreferences' . I searched for this field in my entire folder and it only appeared in GeratedPluginRegistrant.swift which is a generated file

**Comment by huycozy** [comment] 2022-06-24 12:44
Hi @kayceetann 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/aissat/easy_localization).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.
Thank you!

**Closed by huycozy** 2022-06-24 12:44 UTC
Labels: in triage
