### ISSUE TITLE
Scrollbar cannot be Dragged in Flutter Gallery

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#92319] opened 2021-10-22 11:48 UTC
## Descriptions

I cannot use the main scrollbar (drag using my mouse) in the Flutter Gallery web app.

https://user-images.githubusercontent.com/19204050/138447939-3f99d27a-d384-4a3e-910e-7182896c31cb.mp4

The ones in the nested list views do work, but the main scrollbar does not (and it is clipped at the top, which is also super weird).

### Related issues

This is related to https://github.com/flutter/flutter/issues/83368#issuecomment-940533777. 

@Piinks you stated that:

> This sounds like an issue with your app. You should not need to alter the ScrollBehavior in order to drag a scrollbar, please file an issue. Disabling drag on desktop relates to dragging a Scrollable with a mouse, it does not affect the scrollbar.

When referring to me saying that I saw this issue in our app. Now you have an example of this happening 👍 

### Versions

Reproduced on https://gallery.flutter.dev.  
Using Google Chrome Version 95.0.4638.54 (Official Build) (64-bit) on Windows 10.

**Comment by Piinks** [comment] 2021-12-01 20:18
Thanks for reporting the bug in the gallery! I can't say for sure if this is the same bug you are experiencing in your app, but we can definitely take a look at the Gallery and find out what is missing there.

**Comment by Piinks** [comment] 2021-12-01 20:38
I can reproduce this on https://gallery.flutter.dev/#/ but it is not reproducible when I checked out the latest version of flutter/gallery to investigate. Either this has already been fixed or changed to no longer reflect this behavior. I've reached out to the team to see about updating the version of the gallery that is in production.

When looking at [the existing reproduction](https://gallery.flutter.dev/#/), the console logs errors. Does your app log errors?
If you have a reproduction of what you are experiencing in your app, please provide sample code so we can see what is going on, unfortunately we cannot resolve your issue without more information. Thanks!

**Comment by creativecreatorormaybenot** [comment] 2021-12-03 01:25
@Piinks I suppose we should check the live app again once it has been redeployed (@ gallery.flutter.dev).

**Comment by goderbauer** [comment] 2022-02-16 23:26
Since the issue is fixed on master I am going to close this.

**Closed by goderbauer** 2022-02-16 23:26 UTC
Labels: framework, team: gallery, f: scrolling, passed first triage
