### ISSUE TITLE
Bottom nav item flickering while scrolling on iOS

### ISSUE THREAD

**Issue by mohamoha6200** [flutter/flutter#98281] opened 2022-02-11 19:44 UTC
https://streamable.com/qwlaus

Hi everyone , as shown in the video above , the flickering issue started happening after migrating the flutter SDK from 2.0.5 to 2.10.0 using the 'curved_navigation_bar' on it's latest version , it wise to mention that the issue is only reproduceable on IOS devices , android ones do not have this issue (even if we set scroll physics to bouncing). It's clearly not a package related issue but an SDK one.
Btw issue is still reproduceable on 2.10.1 too.
Any ideas ?

**Comment by darshankawar** [comment] 2022-02-15 12:04
@mohamoha6200 
For some reason, I am unable to access the video link you shared. In order to properly address this issue, please provide your `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Also you can attach a short video here itself instead of a link

**Comment by darshankawar** [comment] 2022-02-16 05:26
@mohamoha6200 
This seems to be an issue related to the third party plugin you are using `curved_navigation_bar`. I see that you have already filed an issue in that repo and replicates using previous and current versions of the plugin, so I suspect it's an issue with the plugin and not framework. Please follow-up in it.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-02-16 05:26 UTC
Labels: in triage

**Comment by mohamoha6200** [comment] 2022-02-16 15:46
@darshankawar,
Thank you for the response, I don't think it's a package related problem since it had been working perfectly fine using the same version of the package , changing the version was just an attempt to fix the problem that came about right when I switched from flutter version 2.0.5 to 2.10.0 besides the dependency is a package that's purely made with dart code and the fact that it's only a new iOS platform only problem makes it more likely to be a Flutter issue more than anything else.

Update : I located the issue : it seems that the Material widget above CurvedNavigationBar is what's causing the problem , you can easily reproduce it and test both scenarios with and without the Material wrapping widget.

Don't you find it odd for such an issue to be reproducible using flutter 2.10.0 and not 2.0.5 and only on iOS ?

**Comment by darshankawar** [comment] 2022-02-17 05:23
Thanks for the feedback.

> it seems that the Material widget above CurvedNavigationBar is what's causing the problem , you can easily reproduce it and test both scenarios with and without the Material wrapping widget.

Can you provide us a minimal code sample so that we can run it and analyse further ?

**Comment by mohamoha6200** [comment] 2022-02-17 16:36
Thank you for the quick response ,
[Reproducible code gist](https://gist.github.com/mohamoha6200/1b0d17b5b33c0a7f40f0fb98d5f3ee3f) here is the gist to reproduce the issue , looking forward to the results.

**Comment by mohamoha6200** [comment] 2022-02-18 11:13
Hey , so to answer your question : you did right by wrapping MainWidget() with MaterialApp but the Material wrapping widget I meant was the one on line 28 which is the parent widget of CurvedNavigationBar , if you remove it the problem will be gone but then we'd lose the elevation of the CurvedNavigationBar. To workaround that I had to remove the Material widget like I said and added it into the package code as the CustomPaint parent as follows : 
// around line 133 package code
Material(
              elevation: 25,
              color: Colors.transparent,
              child: CustomPaint(
                painter: NavCustomPainter(
                    _pos!, _length!, widget.color, Directionality.of(context)),
                child: Container(
                  height: 75.0,
                ),
              ),
            ),
To me this is weird , if anyone will have an explanation for it it would be you guys x)
