### ISSUE TITLE
Flutter Web: TextFormField OR InputDecoration using an RTL language (e.g. Hebrew) is getting stuck after trying to erase after space character, and the cursor is not on the right spot

### ISSUE THREAD

**Issue by Vofchuk** [flutter/flutter#56981] opened 2020-05-12 08:47 UTC
The TextFormField is not working as expected at Flutter web...

The LTR and RTL is not working for me as it should be... I saw on others issues that this problem was fixed, but, at least on flutter web i can't see this working...
So i did a special `Statefull Widget `that detects the language typed and change manually from LTR to RTL.

LIke so im having 2 issues:
1: the cursor on hebrew is not on the correct place.
2: the backspace is not working after erasing one word.

Here is my flutter doctor -v:
```
[√] Flutter (Channel dev, 1.18.0-13.0.pre, on Microsoft Windows [Version 10.0.18362.778], locale en-US)
    • Flutter version 1.18.0-13.0.pre at C:\Program Files\flutter
    • Framework revision 8fbfe1cfbf (5 days ago), 2020-05-06 17:36:01 -0700
    • Engine revision d6aa099de7
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\danie\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\danie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138```

**Comment by TahaTesser** [comment] 2020-05-12 14:42
Hi @Vofchuk 
can you please provide your  and `flutter run -d Chrome --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Vofchuk** [comment] 2020-05-12 15:10
flutter run -d Chrome --verbose:
``flutter run -d Chrome --verbose
[  +11 ms] executing: [C:\Program Files\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +76 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +104 ms] 8fbfe1cfbf6ac5c5c23930556e1019385005bf81
[   +3 ms] executing: [C:\Program Files\flutter/] git tag --contains HEAD
[ +498 ms] Exit code 0 from: git tag --contains HEAD
[  +13 ms] 1.18.0-13.0.pre
[ +246 ms] executing: [C:\Program Files\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +263 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[ +357 ms] origin/dev
[  +54 ms] executing: [C:\Program Files\flutter/] git ls-remote --get-url origin
[ +217 ms] Exit code 0 from: git ls-remote --get-url origin
[ +147 ms] https://github.com/flutter/flutter.git
[ +338 ms] executing: [C:\Program Files\flutter/] git rev-parse --abbrev-ref HEAD
[ +230 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[ +156 ms] dev
[  +57 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +373 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ +337 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ +230 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +231 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +227 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +28 ms] executing: C:\Users\danie\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +258 ms] List of devices attached
                    59d184ad               device product:OnePlus6T model:ONEPLUS_A6010 device:OnePlus6T transport_id:7
[ +205 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +215 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +375 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +399 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +345 ms] Found plugin firebase_auth at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[ +271 ms] Found plugin firebase_auth_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[ +266 ms] Found plugin firebase_core at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[ +345 ms] Found plugin firebase_core_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[ +229 ms] Found plugin location at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[ +491 ms] Found plugin location_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[ +330 ms] Found plugin path_provider at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[ +514 ms] Found plugin firebase_auth at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[  +77 ms] Found plugin firebase_auth_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[ +273 ms] Found plugin firebase_core at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[ +319 ms] Found plugin firebase_core_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +31 ms] Found plugin location at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[ +324 ms] Found plugin location_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[   +6 ms] Found plugin path_provider at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[ +890 ms] Generating S:\Flutter\beezee_stores_dashboard\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +341 ms] Launching lib\main.dart on Chrome in debug mode...
[ +278 ms] Updating assets
[ +783 ms] Syncing files to device Chrome...
[  +18 ms] Found plugin firebase_auth at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[ +277 ms] Found plugin firebase_auth_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +2 ms] Found plugin firebase_core at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +2 ms] Found plugin firebase_core_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +6 ms] Found plugin location at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[ +816 ms] Found plugin location_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[ +939 ms] Found plugin path_provider at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[ +511 ms] Found plugin firebase_auth at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[ +355 ms] Found plugin firebase_auth_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +2 ms] Found plugin firebase_core at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +2 ms] Found plugin firebase_core_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +4 ms] Found plugin location at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[ +328 ms] Found plugin location_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[ +348 ms] Found plugin path_provider at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[  +34 ms] Generating S:\Flutter\beezee_stores_dashboard\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +736 ms] <- reset
[  +46 ms] C:\Program Files\flutter\bin\cache\dart-sdk\bin\dart.exe C:\Program Files\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Program
Files\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\danie\AppData\Local\Temp\flutter_tool.fcea1cc7-945f-11ea-89c0-0c5b8f279a64\app.dill --libraries-spec file:///C:/Program%20Files/flutter/bin/cache/flutter_web_sdk/libraries.json --packages       
.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-root C:\Users\danie\AppData\Local\Temp\flutter_tools.fcea1cc8-945f-11ea-89c0-0c5b8f279a64 --filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill --platform
file:///C:/Program%20Files/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[+1396 ms] <- compile org-dartlang-app:/web_entrypoint.dart``


You can understand better here the problem:
https://gyazo.com/a6dd2dcbe85a80a117355284285d2a29
![a6dd2dcbe85a80a117355284285d2a29](https://user-images.githubusercontent.com/48187154/81709545-9d0cbc80-947a-11ea-8d70-79ac84959932.gif)

the cursor is not on the right spot, and I can't pick a certain letter or area of the text to add something on the middle:
https://gyazo.com/5229786c95909c76346d95c184ca3633
![5229786c95909c76346d95c184ca3633](https://user-images.githubusercontent.com/48187154/81710199-3f2ca480-947b-11ea-9794-d62dcd8e208b.gif)


the code is basically this:
 (on the Text Field)
`TextFormField(
                    textDirection:
                        isHebrew ? TextDirection.rtl : TextDirection.ltr,
`

(isHebrew is a boolean that holds if the text being typed is in Hebrew)
hope that now is more clear!

**Comment by Vofchuk** [comment] 2020-05-12 15:13
flutter run -d Chrome --verbose:
```
[  +11 ms] executing: [C:\Program Files\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +76 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +104 ms] 8fbfe1cfbf6ac5c5c23930556e1019385005bf81
[   +3 ms] executing: [C:\Program Files\flutter/] git tag --contains HEAD
[ +498 ms] Exit code 0 from: git tag --contains HEAD
[  +13 ms] 1.18.0-13.0.pre
[ +246 ms] executing: [C:\Program Files\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +263 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[ +357 ms] origin/dev
[  +54 ms] executing: [C:\Program Files\flutter/] git ls-remote --get-url origin
[ +217 ms] Exit code 0 from: git ls-remote --get-url origin
[ +147 ms] https://github.com/flutter/flutter.git
[ +338 ms] executing: [C:\Program Files\flutter/] git rev-parse --abbrev-ref HEAD
[ +230 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[ +156 ms] dev
[  +57 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +373 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ +337 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ +230 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +231 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +227 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +28 ms] executing: C:\Users\danie\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +258 ms] List of devices attached
                    59d184ad               device product:OnePlus6T model:ONEPLUS_A6010 device:OnePlus6T transport_id:7
[ +205 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +215 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +375 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +399 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +345 ms] Found plugin firebase_auth at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[ +271 ms] Found plugin firebase_auth_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[ +266 ms] Found plugin firebase_core at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[ +345 ms] Found plugin firebase_core_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[ +229 ms] Found plugin location at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[ +491 ms] Found plugin location_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[ +330 ms] Found plugin path_provider at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[ +514 ms] Found plugin firebase_auth at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[  +77 ms] Found plugin firebase_auth_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[ +273 ms] Found plugin firebase_core at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[ +319 ms] Found plugin firebase_core_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +31 ms] Found plugin location at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[ +324 ms] Found plugin location_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[   +6 ms] Found plugin path_provider at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[ +890 ms] Generating S:\Flutter\beezee_stores_dashboard\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +341 ms] Launching lib\main.dart on Chrome in debug mode...
[ +278 ms] Updating assets
[ +783 ms] Syncing files to device Chrome...
[  +18 ms] Found plugin firebase_auth at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[ +277 ms] Found plugin firebase_auth_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +2 ms] Found plugin firebase_core at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +2 ms] Found plugin firebase_core_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +6 ms] Found plugin location at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[ +816 ms] Found plugin location_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[ +939 ms] Found plugin path_provider at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[ +511 ms] Found plugin firebase_auth at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[ +355 ms] Found plugin firebase_auth_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +2 ms] Found plugin firebase_core at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +2 ms] Found plugin firebase_core_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +4 ms] Found plugin location at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[ +328 ms] Found plugin location_web at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[ +348 ms] Found plugin path_provider at C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[  +34 ms] Generating S:\Flutter\beezee_stores_dashboard\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +736 ms] <- reset
[  +46 ms] C:\Program Files\flutter\bin\cache\dart-sdk\bin\dart.exe C:\Program Files\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Program
Files\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\danie\AppData\Local\Temp\flutter_tool.fcea1cc7-945f-11ea-89c0-0c5b8f279a64\app.dill --libraries-spec file:///C:/Program%20Files/flutter/bin/cache/flutter_web_sdk/libraries.json --packages       
.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-root C:\Users\danie\AppData\Local\Temp\flutter_tools.fcea1cc8-945f-11ea-89c0-0c5b8f279a64 --filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill --platform
file:///C:/Program%20Files/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[+1396 ms] <- compile org-dartlang-app:/web_entrypoint.dart```

**Comment by TahaTesser** [comment] 2020-05-13 09:07
Closing as duplicate of [#47745](https://github.com/flutter/flutter/issues/47745)

**Closed by TahaTesser** 2020-05-13 09:07 UTC
Labels: a: internationalization, a: text input, f: material design, framework, in triage, platform-web
