### ISSUE TITLE
 Unable to run "adb"

### ISSUE THREAD

**Issue by JeevaVGeorge** [flutter/flutter#149874] opened 2024-06-07 06:39 UTC
### Steps to reproduce

1.Install Android Studio (latest version)
2. Install flutter
3. Create a flutter project
4. Connect a real(physical) device

### Expected results

Device should be detected instead of flutter daemon termination.

### Actual results

Flutter daemon terminated. And real device is not detecting

### Code sample

Nothing related to code

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
    • Flutter version 3.22.1 on channel stable at /Users/vj10/Documents/jeeva/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (2 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
    • Android SDK at /Users/vj10/Library/Android/sdk
    • Platform android-34, build-tools 35.0.0-rc4
    • ANDROID_HOME = /Users/vj10/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: /Users/vj10/Library/Android/sdk/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:547:36)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
      <asynchronous suspension>
      #4      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:217:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:741:34)
      <asynchronous suspension>
      #6      Future.any.onValue (dart:async/future.dart:618:5)
      <asynchronous suspension>


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
vj10@C001148685 MyEngine % flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: /Users/vj10/Library/Android/sdk/platform-tools/adb
[✓] Network resources

! Doctor found issues in 1 category.

```

**Comment by darshankawar** [comment] 2024-06-07 10:36
@JeevaVGeorge 
Check if https://github.com/flutter/flutter/issues/142996#issuecomment-1932542584 helps in your case or not.

**Comment by JeevaVGeorge** [comment] 2024-06-07 10:44
@darshankawar  I have  checked the versions. My Android Sdk Platform tool version is 35.0.1, and android studio version is Jellyfish 2023.3.1 Patch 1. Seems everything is latest.

**Comment by JeevaVGeorge** [comment] 2024-06-07 11:38
> @JeevaVGeorge Check if [#142996 (comment)](https://github.com/flutter/flutter/issues/142996#issuecomment-1932542584) helps in your case or not.

@darshankawar  I am facing the same issue, but even though i have degraded , my device is not detected by adb , its listing while I troubleshooting, and it says not recognized as android. Downgrading also not helping.

**Comment by darshankawar** [comment] 2024-06-10 05:26
Closing as duplicate of https://github.com/flutter/flutter/issues/72101. Check underlying comments to see if they help in your case or not.

**Closed by darshankawar** 2024-06-10 05:26 UTC
Labels: in triage
