### ISSUE TITLE
flutter build apk/appbundle crash

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#56787] opened 2020-05-09 17:24 UTC
Just upgraded Flutter to latest master, and now `flutter build apk/appbundle` is failing (`run` is working fine):

<details>
  <summary>Logs</summary>

```
flutter build appbundle
Target aot_android_asset_bundle failed: FontSubset error: ConstFinder failure: /C:/flutter/bin/cache/artifacts/engine/windows-x64/const_finder.dart.snapshot: Error: The control character U+0000 can only be used in strings and comments.

build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        15,8s
Gradle task bundleRelease failed with exit code 1
```

With `-v` flag, this is the error:

```
[ +204 ms] [ +128 ms] Skipping target: android_aot_release_android-x64
[   +1 ms] [ +107 ms] Skipping target: android_aot_release_android-arm
[ +185 ms] [ +165 ms] Skipping target: android_aot_release_android-arm64
[+8812 ms] [+8803 ms] Persisting file store
[        ] [  +21 ms] Done persisting file store
[  +94 ms] [  +10 ms] Target aot_android_asset_bundle failed: FontSubset error: ConstFinder failure:
/C:/flutter/bin/cache/artifacts/engine/windows-x64/const_finder.dart.snapshot: Error: The control character U+0000 can
only be used in strings and comments.
[   +1 ms] build failed.
[        ] #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[        ] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:230:7)
[        ] #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] [  +11 ms] "flutter assemble" took 10.747ms.
[        ] #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ] #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ] #10     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[        ] #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ] #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ] #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ] #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] #26     Future.wait.<anonymous closure> (dart:async/future.dart:409:22)
[        ] #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +1 ms] #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ] #35     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ] #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] #42     Future.wait.<anonymous closure> (dart:async/future.dart:409:22)
[        ] #43     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] #44     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #45     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] #46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] #47     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] #48     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] #49     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ] #50     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ] #51     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[        ] #52     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ] #53     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ] #54     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ] #55     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ] #56     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ] #57     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ] #58     Future._completeError (dart:async/future_impl.dart:537:5)
[        ] #59     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ] #60     AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart)
[        ] #61     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ] #62     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ] #63     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ] #64     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ] #65     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ] #66     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ] #67     Future._completeError (dart:async/future_impl.dart:537:5)
[        ] #68     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ] #69     copyAssets (package:flutter_tools/src/build_system/targets/assets.dart)
[        ] #70     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ] #71     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ] #72     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ] #73     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ] #74     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ] #75     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ] #76     Future._completeError (dart:async/future_impl.dart:537:5)
[        ] #77     Future.wait.handleError (dart:async/future.dart:388:18)
[        ] #78     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ] #79     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ] #80     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ] #81     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ] #82     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ] #83     Future._completeError (dart:async/future_impl.dart:537:5)
[        ] #84     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ] #85     copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart)
[        ] #86     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ] #87     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ] #88     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ] #89     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ] #90     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ] #91     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ] #92     Future._completeError (dart:async/future_impl.dart:537:5)
[        ] #93     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ] #94     IconTreeShaker.subsetFont (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart)
[        ] #95     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ] #96     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ] #97     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ] #98     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ] #99     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ] #100    Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ] #101    Future._completeError (dart:async/future_impl.dart:537:5)
[        ] #102    _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ] #103    IconTreeShaker._getIconData (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart)
[        ] #104    _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ] #105    _rootRunBinary (dart:async/zone.dart:1214:47)
[        ] #106    _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ] #107    _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ] #108    Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ] #109    Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ] #110    Future._completeError (dart:async/future_impl.dart:537:5)
[        ] #111    _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ] #112    IconTreeShaker._findConstants (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart)
[        ] #113    _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] #114    _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #115    _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] #116    Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] #117    Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] #118    Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] #119    Future.wait.<anonymous closure> (dart:async/future.dart:409:22)
[        ] #120    _rootRunUnary (dart:async/zone.dart:1198:47)
[        ] #121    _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #122    _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ] #123    Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ] #124    Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ] #125    Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ] #126    Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ] #127    _rootRun (dart:async/zone.dart:1190:13)
[        ] #128    _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #129    _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ] #130    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ] #131    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] #132    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ] #133    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ] #134    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 14s
[        ] > Task :app:compileFlutterBuildRelease FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.4/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 533 actionable tasks: 1 executed, 532 up-to-date
[ +528 ms] Running Gradle task 'bundleRelease'... (completed in 14,8s)
[   +6 ms] "flutter appbundle" took 15.321ms.
Gradle task bundleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:411:7)
#2      _rootRunUnary (dart:async/zone.dart:1198:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
flutter doctor -v
[✓] Flutter (Channel master, 1.19.0-1.0.pre.21, on Microsoft Windows [VersiÃ³n 10.0.19041.208], locale es-ES)
    • Flutter version 1.19.0-1.0.pre.21 at C:\flutter
    • Framework revision f5d2c8c770 (17 hours ago), 2020-05-08 17:35:40 -0700
    • Engine revision 9b905d3f03
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 617bc54b71)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\crist\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

cc/ @jonahwilliams @dnfield since this may be related to `--tree-shake-icons` (`flutter build appbundle --no-tree-shake-icons` works fine).

**Comment by jonahwilliams** [comment] 2020-05-11 19:16
Tentatively tagging as TODAY since we turned this on by default

**Comment by dnfield** [comment] 2020-05-11 19:33
Will take a look

**Comment by dnfield** [comment] 2020-05-11 20:09
@Zazo032  - are you able to consistently reproduce this? Do you have a sample project that reproduces it?

Unfortunately, we're not getting the stack from the relevant program that's crashing. That might be tweakable, but we'd need a good way to repro this.

I'm not sure how a null character would get added there. I'll see if I can just run const_finder on windows to make sure as a sanity check that it works there.

**Comment by Zazo032** [comment] 2020-05-11 20:53
I'm no longer able to repro this issue in our project. Today, I updated some translations and upgraded both Flutter and some plugins, and I'm no longer getting this crash while building.

- Flutter: `1.19.0-1.0.pre.21` => `1.19.0-1.0.pre.28`
- `google_fonts`: `1.0.0` => `1.1.0`
- `provider`: `4.1.0` => `4.1.1`
- `uni_links`: `git://github.com/markathomas/uni_links.git` => `0.4.0`

The only meaningful changes are l10n-related, while moving from a single-language app to an internationalized one, but not sure if this can be related (translations are used like `S.of(context).hello_world`). No icons were changed. Wonder how a `U+0000` char broke this and where it was.

**Comment by Zazo032** [comment] 2020-05-11 21:05
Building the project with the commit of our project where this was happening doesn't trigger the error again, so plugin upgrades don't seem to be culprits. How can I roll my framework version to `1.19.0-1.0.pre.21` so I can check again? If that doesn't trigger the crash again, I'm not really sure what could cause this. Maybe building from a wrong cached copy?

**Comment by dnfield** [comment] 2020-05-11 21:07
You can do a `git checkout f5d2c8c770` from your flutter root directory, re-run `flutter doctor` to make sure everything's ok, and try to build it again.

I strongly suspect some file got corrupted at some point locally for you, and somehow a null byte was read by something that should have really been some other byte.

**Comment by dnfield** [comment] 2020-05-11 21:10
Removing `TODAY` on the assumption that this is either fixed on master or was a flake. If we can we should still try to figure out what's going on and fix it, but right now it's not clear what a next step is or that it's even happening with any consistency.

**Comment by Zazo032** [comment] 2020-05-12 07:44
> You can do a `git checkout f5d2c8c770` from your flutter root directory, re-run `flutter doctor` to make sure everything's ok, and try to build it again.

Can't reproduce it again with this version.

> I strongly suspect some file got corrupted at some point locally for you, and somehow a null byte was read by something that should have really been some other byte.

This makes sense to me, I saw a Windows message while booting my workstation, but didn't manage to read it. Maybe it was fixing some corrupted blocks on my SSD, so this is most likely a flake.

**Comment by jonahwilliams** [comment] 2020-05-26 15:25
If we don't have any more information to go off of I'm going to close this as it is not actionable

**Closed by jonahwilliams** 2020-05-26 15:25 UTC
Labels: severe: crash, tool
