### ISSUE TITLE
VSCode debug mode + save = app crashes

### ISSUE THREAD

**Issue by pdefuns** [flutter/flutter#38706] opened 2019-08-16 18:24 UTC
If I run my application in debug mode (with launch.json), it crashes on save.

```json
{
    "name": "MyApp",
    "request": "launch",
    "type": "dart",
    "program": "lib/main.dart",
    "args": [
        "--flavor", "environment"
    ]
}
```

Only message I see in the debugging console:
```
Lost connection to device.
Exited (sigterm)
```

**VSCode version** `1.37.1`

**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale de-CH)
    • Flutter version 1.7.8+hotfix.4 at /Users/x/Development/Tools/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/x/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/x/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/x/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.0.beta.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone • 00008020-000A615C11E2002E • ios • iOS 12.4

• No issues found!
```

**Comment by YAPPDEF** [comment] 2019-08-16 18:43
**Dart: Capture Logs**:
```
[   +3 ms] Result: {type: Success, view: {type: FlutterView, id: _flutterView/0x104023020, isolate: {type: @Isolate, fixedId: true, id: isolates/921017539, name: main.dart$main-921017539, number: 921017539}}}
[   +2 ms] Sending to VM service: _reloadSources({pause: true, rootLibUri: file:///private/var/mobile/Containers/Data/Application/F967788A-9F4F-4F12-AE2E-471B3CB75BBF/tmp/projectYx43V0/project/lib/sandbox_main.dart.incremental.dill, packagesUri: file:///private/var/mobile/Containers/Data/Application/F967788A-9F4F-4F12-AE2E-471B3CB75BBF/tmp/projectYx43V0/project/.packages, isolateId: isolates/921017539})
[  +82 ms] Result: {type: ReloadReport, success: true, details: {finalLibraryCount: 1137, receivedLibraryCount: 40, receivedLibrariesBytes: 625408, receivedClassesCount: 298, receivedProceduresCount: 16, savedLibraryCount: 1097, loadedLibraryCount: 40, shapeChangeMa...
[   +1 ms] <- accept
[        ] reloaded 40 of 1137 libraries
[        ] Sending reload events to iPhone
[        ] Sending reload event to "main.dart$main-921017539"
[        ] Sending to VM service: getIsolate({isolateId: isolates/921017539})
[  +35 ms] Result: {type: Isolate, id: isolates/921017539, name: main, number: 921017539, _originNumber: 921017539, startTime: 1565980871003, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 23, avgCollectionPeriodMillis: 692.5320434782608,...
[  +23 ms] Sending to VM service: _flutter.listViews({})
[   +2 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x104023020, isolate: {type: @Isolate, fixedId: true, id: isolates/921017539, name: main.dart$main-921017539, number: 921017539}}]}
[        ] Evicting dirty assets
[        ] Reassembling application
[        ] Sending to VM service: ext.flutter.reassemble({isolateId: isolates/921017539})
[  +70 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/F967788A-9F4F-4F12-AE2E-471B3CB75BBF/tmp/projectYx43V0/project/)
[        ] Sending to VM service: _deleteDevFS({fsName: project})
[ +260 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
Exited (sigterm)
```

**Comment by lucasccustodio** [comment] 2019-08-16 19:53
Also happening here with latest master but what's weird is that doing a single Hot restart seems to fix the issue and reloading after no longer crashes, dunno if that's related at all but it's working for me.

**Comment by YAPPDEF** [comment] 2019-08-17 11:39
@lucasccustodio thanks for the workaround. Also working for me - at least I can continue working.. But very annoying issue.

**Comment by jamie1192** [comment] 2019-11-06 11:23
I have this exact same issue. I currently have a few flavors/schemes setup that will build fine, but doing a hot reload will crash the app and VSCode debugger will lose connection to device (both simulator and physical for both Android and iOS).

Weirdly enough, as @lucasccustodio suggested, doing a hot restart and then hot reloading after that retains the connection and allows for reloads to work.

Has anyone managed to find a fix for this?

**Comment by castrors** [comment] 2020-05-06 20:35
Same here! Even if I use the command-line I got the crash on hot restart:

```flutter run -t lib/main_staging.dart --debug --flavor staging```

```
[+6076 ms] Performing hot restart...
[   +2 ms] Refreshing active FlutterViews before restarting.
[        ] Sending to VM service: _flutter.listViews({})
[  +16 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7a14a54620, isolate: {type: @Isolate,
fixedId: true, id: isolates/2921399692494547, name: main.dart$main-2921399692494547, number: 2921399692494547}}]}
[   +8 ms] Scanned through 474 files in 8ms
[        ] Syncing files to device GM1900...
[        ] Scanning asset files
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:flutter_pwm_app/main_staging.dart b6bad17e-58ce-4b18-b99b-e922d6dd65ff
[        ] <- b6bad17e-58ce-4b18-b99b-e922d6dd65ff
[  +49 ms] Updating files
[+1102 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device
(file:///data/user/0/com.avira.passwordmanager.flutter_pwm_app.staging/code_cache/flutter.pwm-appEOEEJR/flutter.pwm-app/)
[        ] Sending to VM service: _deleteDevFS({fsName: flutter.pwm-app})
[  +92 ms] Error writing "lib/main_staging.dart.dill" to DevFS: HttpException: Connection closed before full header was received,
uri = http://127.0.0.1:58641/0rqTHX9yozE=/
[        ] trying again in a few - 9 more attempts left
[ +163 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 25,215ms.
`
``

**Comment by exaby73** [comment] 2022-07-14 10:17
Hello @pdefuns. I cannot reproduce this issue currently. Is this issue still relevant?

**Closed** 2022-08-04 11:17 UTC
Labels: waiting for customer response, tool, dependency: dart

**Comment by exaby73** [comment] 2022-08-04 11:25
Since this issue cannot be reproduced and it's quite an old one, I am keeping it closed. If it still reproduces, please comment with your findings and we can re-open it. Thank you
