### ISSUE TITLE
[camera] Camera crash after denied camera permissions and then allow

### ISSUE THREAD

**Issue by tomk9** [flutter/flutter#41078] opened 2019-09-23 07:15 UTC
Camera Plugin crash after denied camera permissions and then allow.
`camera: ^0.5.4+2`

## Steps to Reproduce

1. Open camera preview
2. Deny camera permission
3. Go back and open camera preview again
4. Allow camera permission
5. Crash:
```
I/CameraManagerGlobal(27679): Connecting to camera service
I/flutter (27679): Camera Controller Error: CameraException(cameraPermission, MediaRecorderCamera permission not granted)
I/flutter (27679): null
I/art     (27679): Do partial code cache collection, code=25KB, data=29KB
I/art     (27679): After code cache collection, code=23KB, data=28KB
I/art     (27679): Increasing code cache capacity to 128KB
I/CameraManager(27679): Using legacy camera HAL.
I/CameraDeviceState(27679): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0(27679): Configure outputs: 2 surfaces configured.
D/Camera  (27679): app passed NULL surface
I/RequestThread-0(27679): configureOutputs - set take picture size to 1920x1088
D/mali_winsys(27679): new_window_surface returns 0x3000
I/CameraDeviceState(27679): Legacy camera service transitioning to state IDLE
D/AndroidRuntime(27679): Shutting down VM
E/AndroidRuntime(27679): FATAL EXCEPTION: main
E/AndroidRuntime(27679): Process: com.example.recording, PID: 27679
E/AndroidRuntime(27679): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(27679): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:151)
E/AndroidRuntime(27679): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(27679): 	at io.flutter.plugins.camera.Camera$3.onOpened(Camera.java:184)
E/AndroidRuntime(27679): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134)
E/AndroidRuntime(27679): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(27679): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(27679): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(27679): 	at android.app.ActivityThread.main(ActivityThread.java:6236)
E/AndroidRuntime(27679): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27679): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
E/AndroidRuntime(27679): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```
Fragment of my code:
```dart
@override
  void initState() {
    super.initState();
    availableCameras().then((cameras) {
      controller = CameraController(
        cameras.first,
        ResolutionPreset.ultraHigh,
        enableAudio: false,
      );
      controller.initialize().then((_) {
        if (!mounted) {
          return;
        }
        setState(() {});
      }).catchError((error) {
        print('Camera Controller Error: $error');
        controller?.dispose();
        Navigator.pop(context);
      });
    }).catchError((error){
      print('Avialable Cameras Error: $error');
      controller?.dispose();
      Navigator.pop(context);
    });
  }
```
## Logs

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale
    en-PL)
    • Flutter version 1.9.1+hotfix.2 at /Users/tomasz/development/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tomasz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/tomasz/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • Lenovo K3 Note               • 7BDAQGLAPJK3PUYD                         •
      android-arm64 • Android 7.1.2 (API 25)
    • Android SDK built for x86 64 • emulator-5554                            •
      android-x64   • Android 10 (API 29) (emulator)
    • iPhone (Tomasz)              • 620db5bbc5a4c108791886c1be1fe7c16ca5028b •
      ios           • iOS 12.4.1

• No issues found!

```

**Comment by escamoteur** [comment] 2019-09-23 09:43
On which platforms does this happen?

**Comment by tomk9** [comment] 2019-09-23 09:53
> On which platforms does this happen?

Android. I tested on Android 7.1.2

**Comment by escamoteur** [comment] 2019-09-23 10:00
Could you please also try on iOS?

**Comment by trantrongkim98** [comment] 2019-09-23 10:40
Hi. This issue is because my function to call permission was 2 times in a raw,
to fix it, you can rewrite it and set the flag to block calls to native 
my code:
```call.method == "requestPermissionCamera" -> {
                    isRequestPermission = false
                    if (!cameraPer) {
                        cameraPer = true
                        permissionListener = object : PermissionListener {
                            override fun hasPermission(bool: Boolean, locked: Boolean) {
                                permissionListener = permissionListenerDefault
                                cameraPer = false
                                runOnUiThread {
                                    result.success(Gson().toJson(PermissionData(bool, locked)))
                                }
                            }
                        }
                        var per = Permission(this@MainActivity).requestPermissionCamera(true)
                        if (per == EnumPermission.GRANTED) {
                            cameraPer = false
                            permissionListener = permissionListenerDefault
                            runOnUiThread {
                                result.success(Gson().toJson(PermissionData(accept = true, locked = false)))
                            }
                        } else if (per == EnumPermission.NEVER) {
                            runOnUiThread {
                                result.success(Gson().toJson(PermissionData(accept = false, locked = true)))
                            }
                        }
                    } else {
                        runOnUiThread {
                            result.success(Gson().toJson(PermissionData(accept = false, locked = false)))
                        }
                    }
                }```

**Comment by tomk9** [comment] 2019-09-23 11:08
> Could you please also try on iOS?

On iOS after the firs denial, next won't appear. When I change camera permission in settings and go back to my app, then my app relaunch. On iOS crash does not occur.

**Comment by escamoteur** [comment] 2019-09-23 12:02
Thanks for trying

**Comment by escamoteur** [comment] 2019-09-23 17:26
I can reproduce this on v1.10.6-pre.19 on my emulator. It happen on the second  `controller.initialize` although the controller was disposed after the first initialize failed.

Here is my code for easy reproduction:

```Dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

class CameraHomeWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return CameraHomeState();
  }
}

class CameraHomeState extends State<CameraHomeWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Column(
        children: <Widget>[Text("text")],
      ),
      floatingActionButton: FloatingActionButton(
          onPressed: () => Navigator.of(context).push(
                MaterialPageRoute(builder: (context) => CameraPage()),
              )),
    );
  }

  @override
  void dispose() {
    super.dispose();
    print("AppHomeWidget dispose");
  }
}

class CameraPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return CameraPageState();
  }
}

class CameraPageState extends State<CameraPage> {
  CameraController controller;

  @override
  void initState() {
    availableCameras().then(
      (cameras) {
        controller = CameraController(
          cameras.first,
          ResolutionPreset.ultraHigh,
          enableAudio: false,
        );
        controller.initialize().then(
          (_) {
            if (!mounted) {
              return;
            }
            setState(() {});
          },
        ).catchError(
          (error) {
            print('Camera Controller Error: $error');
            controller?.dispose();
            Navigator.pop(context);
          },
        );
      },
    ).catchError(
      (error) {
        print('Avialable Cameras Error: $error');
        controller?.dispose();
        Navigator.pop(context);
      },
    );

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: new Text('Camera Page')),
    );
  }

}
```

**Comment by tomk9** [comment] 2019-09-24 06:39
> @tomk9 is this a new error? Meaning did it work with earlier versions?

Let me check:
- `0.5.2` is ok,
- `0.5.2+2` is ok,
- `0.5.3` is this crash.

**Comment by escamoteur** [comment] 2019-09-24 06:54
Thanks a lot, that helps a lot

**Comment by Thetyne** [comment] 2019-11-27 11:36
i had describe the cause of problem inside #43266

**Comment by timsneath** [comment] 2020-01-03 01:50
Duplicate of #26228, I think?

**Closed** 2020-01-03 01:51 UTC
Labels: a: error message, p: camera, plugin, severe: crash, severe: regression, ▣ platform-android

**Comment by ben-xD** [comment] 2020-04-25 11:22
@timsneath The other one was closed because this was a duplicate. So closing this one because the other is a duplicate is probably a mistake?
