### ISSUE TITLE
Unable to step over when using DAP 

### ISSUE THREAD

**Issue by sidlatau** [flutter/flutter#105856] opened 2022-06-12 17:12 UTC
Looks like a problem appears because of an unexpected type of `SteppingGranularity`. According to DAP specification it should be a string: 
https://microsoft.github.io/debug-adapter-protocol/specification#:~:text=number%3B%0A%7D-,SteppingGranularity,-The%20granularity%20of

But flutter debug adapter expects map:
https://github.com/dart-lang/sdk/blob/main/pkg/dds/lib/src/dap/protocol_generated.dart#L3514

For debugging I am using:
https://github.com/akinsho/flutter-tools.nvim
https://github.com/mfussenegger/nvim-dap

Flutter crash report.

## command

flutter debug-adapter

## exception

_CastError: type 'String' is not a subtype of type 'Map<String, Object?>' in type cast

```
#0      new NextArguments.fromMap (package:dds/src/dap/protocol_generated.dart:3514:36)
#1      NextArguments.fromJson (package:dds/src/dap/protocol_generated.dart:3503:21)
#2      BaseDebugAdapter.handle (package:dds/src/dap/base_debug_adapter.dart:112:19)
#3      BaseDebugAdapter._handleIncomingRequest (package:dds/src/dap/base_debug_adapter.dart:324:7)
#4      BaseDebugAdapter._handleIncomingMessage (package:dds/src/dap/base_debug_adapter.dart:273:7)
#5      ByteStreamServerChannel._readMessage (package:dds/src/dap/protocol_stream.dart:82:18)
#6      ByteStreamServerChannel.listen.<anonymous closure> (package:dds/src/dap/protocol_stream.dart:53:24)
#7      _rootRunUnary (dart:async/zone.dart:1434:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#14     _rootRun (dart:async/zone.dart:1418:47)
#15     _CustomZone.run (dart:async/zone.dart:1328:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#18     _rootRun (dart:async/zone.dart:1426:13)
#19     _CustomZone.run (dart:async/zone.dart:1328:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 3.0.1 at /Users/ts/fvm/versions/3.0.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/ts/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 3046710C-B886-4E51-B2FC-A25A956EEDD5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by maheshmnj** [comment] 2022-06-13 10:35
Hi @sidlatau, Thanks for filing the issue. Can you please help me with the reproducible steps to investigate further?

**Comment by sidlatau** [comment] 2022-06-13 11:42
1. Install latest neovim (I am using `brew install neovim --HEAD` in macOS)
2. Add setup from https://github.com/sidlatau/dotfiles/tree/flutter-dap-problem/nvim/.config/nvim
3. Open any flutter project.
4. Add breakpoint (if my setup is using then keys are `<Space><t><d>` or `:lua  require("dap").toggle_breakpoint()`)
5. Start app (`<space><f><f>` in my setup) or `:FlutterRun`
6. Run DAP step over command (<F10> or `:lua  require("dap").step_over()`)

**Comment by maheshmnj** [comment] 2022-06-14 08:43
Thank for the info @sidlatau, I am quite unfamiliar with the tools you are referring too, Would you mind breaking down the steps further?

> Add setup from https://github.com/sidlatau/dotfiles/tree/flutter-dap-problem/nvim/.config/nvim

e.g could you elaborate on what exactly you mean't by this?

**Comment by sidlatau** [comment] 2022-06-14 10:07
You need to install DAP client for neovim, I provided my own configuration, but it can be installed using instructions in https://github.com/mfussenegger/nvim-dap if that is more convenient to you.
Problem is with `granularity` property which is provided by DAP client to DAP server.
In my opinion, DAP client works correctly, the problem looks like is on Dart side  - as you see from error`_CastError: type 'String' is not a subtype of type 'Map<String, Object?>' in type cast` it expects map, but the string is provided. But according to DAP documentation it specified as `String`: 
<img width="723" alt="image" src="https://user-images.githubusercontent.com/4973296/173550833-e420629a-a438-4efb-8099-f9d058e4d44c.png">
About the question is it a Flutter issue - the problem occurs in Flutter, but the tooling is in `https://github.com/dart-lang/sdk` - from the stack trace, the exact line is: https://github.com/dart-lang/sdk/blob/main/pkg/dds/lib/src/dap/protocol_generated.dart#L3514

Should I register issue in that repository too?

**Comment by maheshmnj** [comment] 2022-06-15 11:19
> Should I register issue in that repository too?

yes please file the issue in dart-lang too, I suspect that would be the relevant repo. I am labeling this issue for further insights from the team.

**Comment by DanTup** [comment] 2022-06-16 09:54
Copying my notes [from the Dart issue](https://github.com/dart-lang/sdk/issues/49268#issuecomment-1157462827) for convenience. I'll keep this issue open until the fix has landed in Flutter master (it requires a DDS release to get here).

---

@sidlatau thanks! It looks like the code generation wasn't handling references to simple types correctly. I have a fix for this here:

https://dart-review.googlesource.com/c/sdk/+/248605/

After the fix lands in DDS, it'll need publishing and rolling into Flutter. I'll follow up on the Flutter issue when that happens.

It's worth noting that we don't support this field so any value will be ignored. This is indicated by `supportsSteppingGranularity` not being set to `true` (see https://microsoft.github.io/debug-adapter-protocol/specification#:~:text=number%3B%0A%7D-,SteppingGranularity,-The%20granularity%20of):

```
  /**
   * The debug adapter supports stepping granularities (argument 'granularity')
   * for the stepping requests.
   */
  supportsSteppingGranularity?: boolean;
```

I don't think it's very clear from the spec whether this flag not being sent means "the server will ignore it" or "the server doesn't support you sending it" but it may be worth tweaking your DAP client to check this flag before sending it (this is what VS Code seems to do) which may resolve your issue without needing to wait for a Flutter release that includes the fix.

**Comment by DanTup** [comment] 2022-07-11 11:38
Yep, server responses with `granularity` is present:

```
==> [DAP] {"seq":6,"type":"request","arguments":{"granularity":"statement","threadId":1},"command":"next"}
<== [DAP] {"seq":2070,"type":"response","command":"next","request_seq":6,"success":true}
```

As noted above, the value is ignored because we don't currently support stepping granularity (as indicated by `supportsSteppingGranularity` not being set to `true`), but if a client does send it, we won't crash.

**Closed by DanTup** 2022-07-11 11:38 UTC
Labels: tool, dependency: dart, a: debugging, a: error message
