### ISSUE TITLE
How to ignore updating dependencies on flutter run?

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#56323] opened 2020-05-04 19:33 UTC
in both `flutter run` and `flutter build` commands ...

**Comment by VladyslavBondarenko** [comment] 2020-05-05 10:32
Hi @imeDevelopers 
if you run `flutter run -h` you can see

```
--[no-]pub                                        Whether to run "flutter pub get" before executing this command.
                                                      (defaults to on)
```

```
% flutterd run -d chrome --pub
Running "flutter pub get" in bug...                                 2.6s
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       
71,998ms (!)                                       
^C                       
% flutterd run -d chrome --no-pub
Launching lib/main.dart on Chrome in debug mode...

```


Seems to be working as intended. Tried with `dev v1.18.0-8.0.pre`. Closing.
Comment please how can you see that it's not working and I'll reopen

**Comment by imeDevelopers** [comment] 2020-05-05 13:34
I dont provide the plugin version in my pubspec.yaml file , for example
`plugin: `

It force me to update the plugin before run the app using `flutter run --verbose` command ...

Always tell me that the plugin are up to date , and i wait until  all plugins done with this process..

**Comment by VladyslavBondarenko** [comment] 2020-05-05 14:44
I thy in this way: 
1. Run `flutter pub get`
2. Add some dependency and use it in code

3. If you run with `--no-pub` it will fail with method not defined ...
if you run without `--no-pub` or with `--pub` dependencies will loaded

`(defaults to on)` means default `--pub`

**Comment by imeDevelopers** [comment] 2020-05-05 22:37
I dont understand you .. , please provide some more info

**Comment by imeDevelopers** [comment] 2020-05-05 23:03
I get log line like this:
`[   +99 ms] > Task :image_picker:preBuild UP-TO-DATE `

this means that flutter trying to update my dependencies ...

How can i ignore this step ?

**Comment by imeDevelopers** [comment] 2020-05-05 23:03
@VladyslavBondarenko

**Comment by VladyslavBondarenko** [comment] 2020-05-06 09:20
@imeDevelopers 
I can see `Task :<plugin_name>:preBuild UP-TO-DATE` for any plugins, not only for these with not specified version.
I'm not sure are these tasks related to the `--[no-]pub`, because this flag is responsible only for running `flutter pub get` before the executing of `flutter run`.

**Comment by imeDevelopers** [comment] 2020-05-19 12:51
@VladyslavBondarenko

I tried to launch my app without internet connection ..

But i can't launch it using
`flutter run --verbose` command ..

The command line tool tells me that it `Unable to load Maven meta-data from ...` and gives me a `jcenter.bintray.com` url after this message , this means i can't run my application without internet connection .. , i hope i can ignore it and any other required internet steps using this option `--no-pub` to make fast run without any updates to my files .. , hope you understand , thanks.

**Comment by jonahwilliams** [comment] 2020-07-11 19:53
Without a way to reproduce the issue on our end there is nothing for us to do here. I'm closing the issue for now, but feel free to re-open if you can provide a [minimal reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)

**Closed by jonahwilliams** 2020-07-11 19:53 UTC
Labels: t: gradle, tool

**Comment by Vidtion** [comment] 2021-06-15 02:07
Is there a way to run `flutter debug` in vscode with gradle `offline mode` just like in the Android Studio? It took me 5 mins each time to debug android, while 45s in debug iOS.

**Comment by Vidtion** [comment] 2021-06-15 03:03
This works for me.

`android/gradlew.bat` in line 75 add `--offline`
```
@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %CMD_LINE_ARGS% --offline
```
and `android/gradlew` to end file  add `--offline`
```
exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@" --offline
```
