### ISSUE TITLE
Physical iPhone not detected by flutter doctor. 

### ISSUE THREAD

**Issue by longmengua** [flutter/flutter#41051] opened 2019-09-22 09:17 UTC
I could not detect the device in the flutter, but I can build the app in the Xcode, anyone could help me
![螢幕快照 2019-09-22 下午4 34 10](https://user-images.githubusercontent.com/33407020/65385088-ca2a2480-dd5c-11e9-946b-ee5b8fc061e8.png)
?

**Comment by escamoteur** [comment] 2019-09-22 14:25
Could you please add the output of flutter doctor

**Comment by longmengua** [comment] 2019-09-22 14:30
escamoteur <notifications@github.com> 於 2019年9月22日 週日 下午10:27寫道：

**Comment by longmengua** [comment] 2019-09-22 14:31
![螢幕快照 2019-09-22 下午10 30 04](https://user-images.githubusercontent.com/33407020/65389422-ae3c7800-dd88-11e9-8d8b-d2f2b0429cd6.png)

**Comment by delef** [comment] 2019-09-22 14:32
I have some problem!

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale
    en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[!] Connected device
    ! No devices available

<img width="1145" alt="Screenshot 2019-09-22 at 17 32 06" src="https://user-images.githubusercontent.com/2103263/65389433-ec24a680-dd5e-11e9-8f26-27cb216eef1a.png">

**Comment by longmengua** [comment] 2019-09-22 14:33
currently, even though I make all of the settings to be right, still could not detect the device

**Comment by escamoteur** [comment] 2019-09-22 14:47
Have you updated the Flutter plugins  for your IDE to the latest version?
If yes try to switch to master channel.

**Comment by longmengua** [comment] 2019-09-22 14:51
How to do?

**Comment by escamoteur** [comment] 2019-09-22 14:54
flutter channel master
Then
flutter upgrade

**Comment by longmengua** [comment] 2019-09-22 15:13
![螢幕快照 2019-09-22 下午11 12 41](https://user-images.githubusercontent.com/33407020/65390087-8223f580-dd8e-11e9-80e8-ad45d09f4022.png)
 seem like doesn't work well.

**Comment by escamoteur** [comment] 2019-09-22 15:27
Have you updated the Flutter plugin in IntelliJ or VS code?Have you restarted your computer? Am 22.09.2019 17:15 schrieb 黃鴻文 <notifications@github.com>:

seem like doesn't work well.

**Comment by longmengua** [comment] 2019-09-22 15:39
Currently, it's not about any IDE, I try to run it on the terminal, but as you can see the pic, the terminal could not detect the device well.

**Comment by escamoteur** [comment] 2019-09-22 16:15
Did it work before? Am 22.09.2019 17:41 schrieb 黃鴻文 <notifications@github.com>:Currently, it's not about any IDE, I try to run it on the terminal, but as you can see the pic, the terminal could not detect the device well.

**Comment by longmengua** [comment] 2019-09-22 16:23
Nope, I just reset the Mac and followed the steps from the flutter, after I
done everything, it was not working well, and I google it for a half day,
but no useful information was founded.

**Comment by escamoteur** [comment] 2019-09-22 16:30
So this is the first time you try Flutter and you never saw it working? Am 22.09.2019 18:25 schrieb 黃鴻文 <notifications@github.com>:Nope, I just reset the Mac and followed the steps from the flutter, after I

done everything, it was not working well, and I google it for a half day,

but no useful information was founded.

**Comment by longmengua** [comment] 2019-09-22 16:35
I got something wrong with my computer, but after reset it, and follow the
steps, it was not working on physical devices(only in flutter, Xcode
working find.)

**Comment by escamoteur** [comment] 2019-09-22 16:41
Does it work on the Emulator?
Do you see your phone in xcode?

**Comment by longmengua** [comment] 2019-09-22 16:45
Yeah, it does. Only physical devices couldn’t work.

**Comment by escamoteur** [comment] 2019-09-22 16:57
Do you see your physical device in xcode?Windows->Devices?Am 22.09.2019 18:46 schrieb 黃鴻文 <notifications@github.com>:Yeah, it does. Only physical devices couldn’t work.

**Comment by longmengua** [comment] 2019-09-22 17:02
Yeah, you can see the pic in the previous comment. That’s why I am confused
with the issue.

**Comment by escamoteur** [comment] 2019-09-22 17:10
Uhm I see no picture in your last comment

**Comment by longmengua** [comment] 2019-09-22 17:22
![螢幕快照 2019-09-23 上午1 21 53](https://user-images.githubusercontent.com/33407020/65391863-8ce78600-dda0-11e9-9862-7497a2ea52ef.png)
it's working fine on simulator

**Comment by longmengua** [comment] 2019-09-22 17:24
but as you can see on the Xcode detecting device, waltor, it's my iphone name, but could not be detected in the flutter, and it's not about the IDE, I type flutter doctor -v in terminal, it still not connected.

**Comment by escamoteur** [comment] 2019-09-22 17:47
Yep, you are right, we will have to wait for the Flutter team

**Comment by christopherfujino** [comment] 2019-09-22 18:59
This is a duplicate of [this issue](https://github.com/flutter/flutter/issues/41006). There was briefly an issue with the cached artifacts. The fix is to remove your flutter cache (`rm -rf <flutter_repo_directory>/bin/cache && flutter doctor -v` should delete the cache, and then re-download it). Thanks for reporting this and my apologies for breaking it!

**Closed by christopherfujino** 2019-09-22 18:59 UTC
Labels: a: first hour, severe: regression, t: devtools, t: flutter doctor, t: xcode, ⌘‬ platform-mac, ⌺‬ platform-ios
