### ISSUE TITLE
Two consecutive webview result in no rendering in the first webview after switching app in iPhone X

### ISSUE THREAD

**Issue by Jasphere-Appsploration** [flutter/flutter#36416] opened 2019-07-18 03:22 UTC
I am using webview to render some dynamic contents from our server. We tends to spawn a new screen with another webview instead of using href navigation within the webview in order to preserve the page transition feel and animation. 

This all work fine in Android. However on iOS devices (simulator is working fine as well), in certain condition, the webview will not render itself. This happens in the following order

1. Open a webview
2. Open another webview
3. Switch app (in my case is go to map, call)
4. Switch back to the app
5. Tap back to return to the first webview
6. The webview will not render.

## Steps to Reproduce

1. Run the app code https://gist.github.com/Jasphere-Appsploration/a746b55c848a5ec80c5db8a51bb3bc47
2. When the google page is loaded, tap on the "Image" at the top to open another webview
3. Switch the app to background (not killing the app)
4. Open up the app again
5. Tap on the back 

The result of flutter doctor are 
```
[✓] Flutter (Channel master, v1.8.2-pre.59, on Mac OS X 10.13.6 17G65, locale en-MY)
    • Flutter version 1.8.2-pre.59 at /Users/jaspherelee/Desktop/Application/flutter
    • Framework revision c2d83ccf91 (19 hours ago), 2019-07-17 04:27:27 -0400
    • Engine revision 98241b7b05
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaspherelee/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (4 available)
    • SM G960F • 2208229a21017ece                         • android-arm64  • Android 8.0.0 (API 26)
    • iPhone   • 54450a47f970529a18dbd35d22e5c558f062b51d • ios            • iOS 12.1.4
    • macOS    • macOS                                    • darwin-x64     • Mac OS X 10.13.6 17G65
    • Chrome   • chrome                                   • web-javascript • Google Chrome 75.0.3770.142 


• No issues found!
```

I am using webview version of 0.3.10+3

**Comment by Jasphere-Appsploration** [comment] 2019-07-18 06:11
This is the recording on the steps to reproduce
![ezgif com-optimize](https://user-images.githubusercontent.com/25500437/61433442-e1682280-a965-11e9-924f-612d89843334.gif)

**Comment by BondarenkoStas** [comment] 2019-09-26 15:18
@Jasphere-Appsploration Is it the same while using current flutter stable or master?

**Comment by Jasphere-Appsploration** [comment] 2019-10-07 05:58
> @Jasphere-Appsploration Is it the same while using current flutter stable or master?

I kinda forgot about this, and I tried this again using the latest master channel and it crashed!!

My flutter doctor output as below:
```
[✓] Flutter (Channel master, v1.10.13-pre.12, on Mac OS X 10.14.6 18G103, locale en-MY)
    • Flutter version 1.10.13-pre.12 at /Users/jaspherelee/Desktop/Application/flutter
    • Framework revision 682e6383ac (6 hours ago), 2019-10-06 14:39:16 -0700
    • Engine revision 7d90779bb6
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaspherelee/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • SM G960F • 2208229a21017ece                         • android-arm64 • Android 9 (API 28)
    • iPhone   • 54450a47f970529a18dbd35d22e5c558f062b51d • ios           • iOS 13.1.2

• No issues found!

```

I have updated my iOS to 13.1 and XCode to 11.1 and since then I cannot see any console output in the "Run" tab in Android Studio. 
I tried running using XCode and I still can't get a clue of what happened that cause the crash.

**Comment by Jasphere-Appsploration** [comment] 2019-10-07 07:22
I try switched to Flutter 1.10.7 and there is no such issue.

**Comment by zoeyfan** [comment] 2020-01-03 05:30
Is it just iPhone X or all iOS devices?

**Comment by VladyslavBondarenko** [comment] 2020-03-12 09:36
Hi @Jasphere-Appsploration 
I can't reproduce it with iOS 11.0 or 13.3 simulators, with flutter master v1.15.20 and webview_flutter 0.3.10+3 or 0.3.19+9.
Is it still an issue? if yes, can it be reproduced only on a real device?

**Comment by Jasphere-Appsploration** [comment] 2020-03-12 09:52
It seems the issue does not happen anymore with webview 0.3.19+3

**Comment by VladyslavBondarenko** [comment] 2020-03-12 09:56
@Jasphere-Appsploration
Then I'm closing the issue
If you disagree please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-03-12 09:56 UTC
Labels: p: webview, plugin, ⌺‬ platform-ios
