### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by oculosdanilo** [flutter/flutter#127687] opened 2023-05-26 16:54 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#6      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:210:53)
#7      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:158:49)
#8      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart)
#9      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:152:30)
#10     _extractPlatformMaps (package:flutter_tools/src/flutter_plugins.dart:355:40)
#11     _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:369:53)
#12     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1150:11)
<asynchronous suspension>
#13     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:374:5)
<asynchronous suspension>
#14     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.2, on Microsoft Windows [versÆo 10.0.19045.2673], locale pt-BR)
    [32m•[39m Flutter version 3.10.2 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 9cd3d0d9ff (3 days ago), 2023-05-23 20:57:28 -0700
    [32m•[39m Engine revision 90fa3ae28f
    [32m•[39m Dart version 3.0.2
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    [32m•[39m Android SDK at C:\Users\LAB07\AppData\Local\Android\sdk
    [32m•[39m Platform android-33-ext4, build-tools 33.0.1
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Professional 2019 16.0.22)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    [32m•[39m Visual Studio Professional 2019 version 16.0.28803.916
    [32m•[39m Windows 10 SDK version 10.0.17763.0

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at C:\Users\LAB07\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.64.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    [32m•[39m Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [versÆo 10.0.19045.2673]
    [32m•[39m Chrome (web)                 • chrome        • web-javascript • Google Chrome 111.0.5563.65
    [32m•[39m Edge (web)                   • edge          • web-javascript • Microsoft Edge 109.0.1518.61

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f72efea43c3013323d1b95cff571f3c1caa37583
### Plugins
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
video_player-2.6.1
video_player_android-2.4.8
video_player_avfoundation-2.4.6
video_player_web-2.0.16

**Comment by huycozy** [comment] 2023-05-29 04:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021.

**Closed by huycozy** 2023-05-29 04:59 UTC
Labels: in triage
