### ISSUE TITLE
webview_flutter - WebView.postUrl method

### ISSUE THREAD

**Issue by rlecheta** [flutter/flutter#29930] opened 2019-03-25 18:27 UTC
Hi, I'm migrating an app from Android/iOS to Flutter but I didn't find the WebView.postUrl in the webview_flutter plugin. I need to use this method because I can't change de way the server was written. Can you add this feature to the webview_flutter plugin?

**Comment by June93** [comment] 2019-06-19 10:14
I also encountered the same problem.

**Comment by iapicca** [comment] 2019-11-04 07:54
https://github.com/flutter/flutter/issues/27730

**Comment by stuartmorgan** [comment] 2021-04-05 19:30
Closing as a duplicate of the above.

**Closed by stuartmorgan** 2021-04-05 19:30 UTC
Labels: p: first party, p: webview, plugin, proposal, waiting for PR to land (fixed)
