### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by Oubi256** [flutter/flutter#155643] opened 2024-09-24 23:43 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=00008101-00053982213A001E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2584:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:618:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.22.1, on macOS 15.0 24A335 darwin-arm64, locale ru-UA)
    • Flutter version 3.22.1 on channel stable at /Users/oubi256/Development/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (4 months ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/oubi256/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/oubi256/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone Oubi256 (mobile)         • 00008101-00053982213A001E • ios            • iOS 18.0 22A3354
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.5+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7482962148e8d758338d8a28f589f317e1e42ba4
### Plugins
android_id-0.3.6
appsflyer_sdk-6.14.3
device_info_plus-10.1.0
firebase_analytics-11.2.1
firebase_analytics_web-0.5.9+1
firebase_core-3.3.0
firebase_core_web-2.17.4
firebase_messaging-15.0.4
firebase_messaging_web-3.8.12
flutter_native_splash-2.4.1
flutter_secure_storage-4.2.1
in_app_purchase-3.2.0
in_app_purchase_android-0.3.6+2
in_app_purchase_storekit-0.3.17+2
in_app_review-2.0.9
mixpanel_flutter-2.3.2
package_info_plus-8.0.0
path_provider-2.1.3
path_provider_android-2.2.7
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.7
permission_handler_apple-9.4.5
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
sentry_flutter-8.9.0
shared_preferences-2.3.0
shared_preferences_android-2.3.0
shared_preferences_foundation-2.5.0
shared_preferences_linux-2.4.0
shared_preferences_web-2.4.0
shared_preferences_windows-2.4.0
url_launcher-6.3.0
url_launcher_android-6.3.5
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1
webview_flutter-4.8.0
webview_flutter_android-3.16.4
webview_flutter_wkwebview-3.14.0

**Comment by huycozy** [comment] 2024-09-25 05:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131.

**Closed by huycozy** 2024-09-25 05:14 UTC
Labels: in triage
