### ISSUE TITLE
flutter: No named parameter with the name 'overflow', overflow: Overflow.visible,

### ISSUE THREAD

**Issue by azheennn** [flutter/flutter#66135] opened 2020-09-18 20:23 UTC
i updated my flutter today and now the overflow parameter in stack widget no longer works.

```
Flutter 1.22.0-10.0.pre.252 • channel master • https://github.com/flutter/flutter.git
Framework • revision 78929661fb (5 hours ago) • 2020-09-18 08:08:30 -0700
Engine • revision 2abe69c608
Tools • Dart 2.10.0 (build 2.10.0-136.0.dev)
im using badges and stack widgets everywhere, what do i do?
```
im using badges and stack widgets everywhere, what do i do?

logs:

```
../../.pub-cache/hosted/pub.dartlang.org/badges-1.1.1/lib/src/badge.dart:84:8: Error: No named parameter with the name 'overflow'.
       overflow: Overflow.visible,
       ^^^^^^^^
../../Library/flutter/packages/flutter/lib/src/widgets/basic.dart:3273:3: Context: Found this candidate, but the arguments don't match.
  Stack({
  ^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/admin/Library/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/admin/Library/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 10s
Exception: Gradle task assembleDebug failed with exit code 1
```

flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.252, on Mac OS X 10.15.5 19F101 x86_64, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.0)
[✓] Connected device (3 available)

• No issues found!
admin@Admins-MacBook-Pro-3 ios % 

```

**Comment by hamdikahloun** [comment] 2020-09-18 22:06
Hi @azheennn 
Can you provide minimum simple code please.

**Comment by vickyleu** [comment] 2020-09-19 03:01
master branch remove so many  param,dev branch in function link error, like this  void functionA(int a,{AnyClass clazz});   is link to void functionA(int a,{dynamic AnyClass});

**Comment by azheennn** [comment] 2020-09-19 06:45
> Hi @azheennn
> Can you provide minimum simple code please.

i am using the badges package from pub.dev and it uses stack widget like this

```
  @override
  Widget build(BuildContext context) {
    if (widget.child == null) {
      return _getBadge();
    } else {
      return Stack(
        alignment: widget.alignment,
        overflow: Overflow.visible,
        children: [
          widget.child,
          BadgePositioned(
            position: widget.position,
            child: _getBadge(),
          ),
        ],
      );
    }
  }
```

**Comment by azheennn** [comment] 2020-09-19 06:45
I switched channel to stable and it works fine, on the master it has issues, idk why :/

**Comment by TheBiirb** [comment] 2020-09-19 07:18
Replace `overflow: Overflow.visible` with `clipBehavior: Clip.none`. Check this https://flutter.dev/go/clip-behavior

**Comment by azheennn** [comment] 2020-09-19 07:19
> Replace `overflow: Overflow.visible` with `clipBehavior: Clip.none`. The migration guide -> https://flutter.dev/go/clip-behavior

cant replace it its a package

**Comment by TheBiirb** [comment] 2020-09-19 07:21
You can open a PR on their repo

**Comment by PixelToast** [comment] 2020-09-20 09:03
Closing as duplicate of #66030

**Closed by PixelToast** 2020-09-20 09:03 UTC

**Comment by flutterq** [comment] 2021-01-28 17:22
Already [Solved] Please Look at here for all possible solution [[Solved] Error: No named parameter with the name ‘keyboardDismissBehavior’](https://fluttercorner.com/flutter-run-error-no-named-parameter-with-the-name-keyboarddismissbehavior/)
