### ISSUE TITLE
[image_picker] On iOS,  camera overlay is clickable through, user can interact with widgets behind the overlay 

### ISSUE THREAD

**Issue by suhaotian** [flutter/flutter#39218] opened 2019-08-26 00:23 UTC
## Steps to Reproduce

plugins/image_picker: on iOS when you take a picture from camera, you can click the picture bottom.
if there was a TextField widget in the bottom under the overlay, then you can't do anything more

<img src="https://user-images.githubusercontent.com/6512574/63658087-859d7e80-c7da-11e9-92fd-4c84646ddc46.jpg" width="200" />

**Comment by DylanXing** [comment] 2019-08-26 10:04
+1

**Comment by RemmoYu** [comment] 2019-08-29 08:07
+1

**Comment by TahaTesser** [comment] 2020-09-15 15:50
Hi @suhaotian  @RemmoYu 
Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with the latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by RemmoYu** [comment] 2020-09-25 01:28
I still have this issue, test with flutter stable version 1.20.4

**Comment by TahaTesser** [comment] 2020-09-25 09:23
@RemmoYu 
, Can you please provide your `flutter doctor -v` with the latest stable and`flutter run --verbose` logs, and a minimal complete reproducible code sample
Thank you

**Comment by RemmoYu** [comment] 2020-09-27 10:52
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale
    zh-Hans-CN)
    • Flutter version 1.20.4 at /Users/remmo/flutter
    • Framework revision fba99f6cf9 (13 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/remmo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • 余小雨的iPhone (mobile) • 00008030-001E202C2E11802E • ios • iOS 14.0

• No issues found!

Please refer to the sample code in https://github.com/RemmoYu/image_picker_demo

**Comment by TahaTesser** [comment] 2020-09-29 14:13
### Steps to reproduce
1. launch code sample on iOS
2. Tap on textfield, bring up the keyboard
3. While the keyboard is open, click `take a photo`
4. Take a pic, click use photo and it returns back to the home page 
5. Try clicking on textfield again, the keyboard won'topen  (you can only select or paste text in the textfield) 

### Recording
[recording.MP4.zip](https://github.com/flutter/flutter/files/5299611/recording.MP4.zip)

### Code Sample and doctor -v

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text("DEMO"),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            FlatButton(
              child: Text("take photo"),
              onPressed: _takePhotoAction,
            ),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 15),
              margin: const EdgeInsets.all(20),
              child: TextField(
                maxLines: 20,
                style: TextStyle(
                  color: Color(0xff333333),
                  fontSize: 14,
                ),
                decoration: InputDecoration(
                  border: InputBorder.none,
                  hintText: "Input text",
                ),
              ),
              decoration: BoxDecoration(
                color: Colors.green,
                borderRadius: BorderRadius.circular(6.0),
              ),
            )
          ],
        ),
      ),
    );
  }

  void _takePhotoAction() async {
    final picker = ImagePicker();
    try {
      await picker.getImage(
        source: ImageSource.camera,
      );
    } catch (error) {
      print(error);
    }
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.405, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.405 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 9d7bdb5903 (8 hours ago), 2020-09-28 22:46:21 -0700
    • Engine revision 438685dad0
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.0.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 x86_64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details>

**Comment by RemmoYu** [comment] 2020-09-30 09:00
Hi @TahaTesser  I thank you are describing a different issue from the original one.  the issue we faced is the keyboard covered the picture take from camera.

**Steps to reproduce**

3.  Click "take photo" button
4. Take a picture, ~~click use photo and it returns back to the home page~~, **don't try to click "use photo" or "retake"**,  just try to tap the textfield (yes, it's invisible, but just try that)
5.  The keyboard will bring up and cover the picture, then you can do nothing but close the application.

**Comment by TahaTesser** [comment] 2020-09-30 13:00
Hi  @RemmoYu
That's correct, I encountered another issue, I will investigate that and file a new issue for it

Final steps to reproduce 
1. Launch the app, tap `take a photo`,
2.Take a picture, click use photo and it returns back to the home page, don't try to click "use photo" or "retake", just try to tap the textfield (yes, it's invisible, but just try that)
3. The keyboard will bring up and cover the picture, then you can do nothing but close the application.

Follow your steps, I can reproduce the issue 

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/48603081/94688021-aa9fe180-034a-11eb-9149-ff6e2917fd44.gif)

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text("DEMO"),
      ),
      body: Column(
        children: [
          FlatButton(
            child: Text("take photo"),
            onPressed: _takePhotoAction,
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 15),
            margin: const EdgeInsets.all(20),
            child: TextField(
              maxLines: 20,
              style: TextStyle(
                color: Color(0xff333333),
                fontSize: 14,
              ),
              decoration: InputDecoration(
                border: InputBorder.none,
                hintText: "Input text",
              ),
            ),
            decoration: BoxDecoration(
              color: Colors.green,
              borderRadius: BorderRadius.circular(6.0),
            ),
          )
        ],
      ),
    );
  }

  void _takePhotoAction() async {
    final picker = ImagePicker();
    try {
      await picker.getImage(
        source: ImageSource.camera,
      );
    } catch (error) {
      print(error);
    }
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.428, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.428 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision a06f385145 (11 hours ago), 2020-09-29 21:37:04 -0400
    • Engine revision d18c3ea75c
    • Dart version 2.11.0 (build 2.11.0-178.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.0.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 x86_64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details>

**Comment by paulomunky1** [comment] 2020-11-06 11:56
+1

**Comment by oodavid** [comment] 2020-11-16 11:29
My own investigation into this - see: #69913

## Steps to Reproduce

1. Use `image_picker: ^0.6.7+11` on a real iOS device (you need the camera)
2. Take a photo
3. _Don't_ close the preview screen (where it says Retake / Use Photo)
4. You can now interact with app widgets, even though the preview is visible

## Demo

Below are two recordings demonstrating the issue. It was a customers iPhone 8, we've had similar reports on all iOS devices.

I can't replicate this on the simulator since it requires a camera. Nor do I have access to an iPhone at the moment.

### Video 1 - Typing through the preview

Demonstration of interacting with Widgets below the camera preview.

I manage to fill out a text input while the camera preview is still open.

https://www.youtube.com/watch?v=JddPDSKlEgk

### Video 2 - Two Camera Instances

Here I create *two* camera instances by the same method - interacting with the widgets below the preview.

In this state it's not possible to return to the App as the *first* camera instance cannot be closed.

https://youtu.be/nGTTdfLhhGA

**Comment by jmealo** [comment] 2020-12-30 20:07
Any updates on a fix for this?

**Comment by oodavid** [comment] 2021-01-02 16:49
@jmealo I have a flutter-centric workaround that shoves a dialog between the camera and underlying app to act as a way to capture gestures:

```dart
// In my main function
try {
  openIOSBlockingModal(
    context: context,
    source: source,
  );
  PickedFile pickedFile = await _picker.getImage(source: source);
} catch(e) {
  ...
}

// TODO: Remove this workaround when this issue is resolved:
// https://github.com/flutter/flutter/issues/39218
bool _modalIsOpen = false;
void openIOSBlockingModal({
  BuildContext context,
  ImageSource source,
}) {
  String platform = Platform.operatingSystem;
  if (!_modalIsOpen && source == ImageSource.camera && platform == 'ios') {
    _modalIsOpen = true;
    showGeneralDialog(
      context: context,
      pageBuilder: (
        BuildContext buildContext,
        Animation<double> animation,
        Animation<double> secondaryAnimation,
      ) {
        return Material(
          type: MaterialType.transparency,
          child: Stack(
            children: [
              Align(
                alignment: Alignment.topRight,
                child: Padding(
                  padding: EdgeInsets.all(16),
                  child: IconButton(
                    icon: Icon(
                      Icons.cancel,
                      size: 42,
                      color: Colors.black.withOpacity(0.3),
                    ),
                    onPressed: () {
                      closeIOSBlockingModal(
                        context: context,
                      );
                    },
                  ),
                ),
              ),
              Align(
                alignment: Alignment.center,
                child: Text('Selecting Image'),
              ),
            ],
          ),
        );
      },
      barrierDismissible: false,
      barrierLabel: MaterialLocalizations.of(context).modalBarrierDismissLabel,
      barrierColor: Colors.white.withOpacity(0.7),
      transitionDuration: Duration.zero,
    );
  }
}

void closeIOSBlockingModal({
  BuildContext context,
}) {
  if (_modalIsOpen) {
    Navigator.of(context, rootNavigator: true).pop();
    _modalIsOpen = false;
  }
}
```

**Comment by TahaTesser** [comment] 2021-02-09 11:37
Hi everyone, this problem still exists `0.7.0-nullsafety`

 <details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.4
! Doctor found issues in 3 categories.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.215, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.215 at /Users/tahatesser/Code/flutter_master
    • Framework revision f3c10bd23a (6 hours ago), 2021-02-08 21:52:03 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 88.0.4324.150
! Doctor found issues in 2 categories.
```

</details>

Thank you

**Comment by TahaTesser** [comment] 2021-02-09 12:10
Closing as duplicate of https://github.com/flutter/flutter/issues/28335

**Closed by TahaTesser** 2021-02-09 12:10 UTC
Labels: found in release: 1.22, found in release: 1.26, has reproducible steps, p: first party, p: image_picker, platform-ios, plugin
