### ISSUE TITLE
Printing the help from the terminal of a hot running application gets the terminal stuck on bold

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#59228] opened 2020-06-11 03:44 UTC
Do this:

```
flutter run
h
```

The terminal will get stuck on bold after that. The last line of the help text (which prints the observatory) prints the line in bold without resetting the ANSI escape.

Flutter revision c264b70ec3b0cf9cd568eba5d65d0ce47fe57e1d

**Comment by jonahwilliams** [comment] 2020-06-11 04:04
Duplicate of https://github.com/flutter/flutter/issues/52204

**Closed by jonahwilliams** 2020-06-11 04:04 UTC
Labels: P4, tool
