### ISSUE TITLE
[path_provider] compilation error on flutter 2.10.0

### ISSUE THREAD

**Issue by davsl** [flutter/flutter#97900] opened 2022-02-06 12:03 UTC
```
../../../.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
```

**Comment by ps6067966** [comment] 2022-02-06 12:45
platform: ^3.1.0
Problem solved after placing this in pubspec.yaml file.

**Comment by stuartmorgan** [comment] 2022-02-06 12:48
Per the error message, this error comes from `package`, not `path_provider`. Closing as there is no Flutter bug here.

**Closed by stuartmorgan** 2022-02-06 12:48 UTC

**Comment by stuartmorgan** [comment] 2022-02-06 13:10
(Duplicate of https://github.com/flutter/flutter/issues/96711)
