### ISSUE TITLE
Icons.key does not render on Windows, Android, or Web.  Didnt' test on iOS or macOs

### ISSUE THREAD

**Issue by longtimedeveloper** [flutter/flutter#98947] opened 2022-02-22 21:02 UTC
## Steps to Reproduce

Create a new Flutter app.

Either use this HomePage widget or copy all the code from the below Code Example.

```dart
class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            children: const [
              Icon(Icons.keyboard),
              Icon(Icons.key),
              Icon(Icons.app_registration),
            ],
          ),
        ),
      ),
    );
  }
}
```

Run the app.

**Expected results:** 
Expected to see three icons, including the key.

**Actual results:**
**Windows**
![iconkeydoesnotrenderonwindows](https://user-images.githubusercontent.com/79998776/155218176-a50eefa4-8d03-48a6-80d5-02a5c467cac4.png)

**Web**
![iconkeydoesnotrenderonweb](https://user-images.githubusercontent.com/79998776/155218248-7be7a6c7-4c1f-4e6e-9e04-56649058dec2.png)

**Android**
![iconkeydoesnotrenderonandroid](https://user-images.githubusercontent.com/79998776/155218291-73c9e028-b7c4-42b3-bd69-893c64432eb8.png)

### NOTE
None of the icons that begin with the word key work.  

![keyicons](https://user-images.githubusercontent.com/79998776/155218591-8245282c-3e4d-47c7-8367-cb326b02d7aa.png)

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            children: const [
              Icon(Icons.keyboard),
              Icon(Icons.key),
              Icon(Icons.app_registration),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
>flutter doctor -v
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19043.1526], locale en-US)
    • Flutter version 2.10.1 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (13 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at C:\Users\kdawg\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32126.315
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\kdawg\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by HansMuller** [comment] 2022-02-22 23:37
CC @guidezpl

**Comment by guidezpl** [comment] 2022-02-23 08:19
Duplicate of #97767

**Closed** 2022-02-23 08:18 UTC
Labels: framework, f: material design
