### ISSUE TITLE
Hot Reload Issue when using FlutterEngineGroup in Flutter Android

### ISSUE THREAD

**Issue by abhineetchandan** [flutter/flutter#114221] opened 2022-10-28 10:21 UTC
## Steps to Reproduce
1. When overriding the provideFlutterEngine(context) in MainActivity to provide a flutter engine from FlutterEngineGroup, hot reload of flutter app stops working.
<summary>
Code sample

```
class MainActivity : FlutterActivity(), EventChannel.StreamHandler, MethodCallHandler {
        //Other Codes.........
        override fun provideFlutterEngine(context: Context): FlutterEngine? {
            val appData: MyApp = applicationContext as MyApp
            return appData.engineGroup.createAndRunDefaultEngine(context)
    }
}
```
</summary>

2. The app doesn't hot reload and the app stops.

**Flutter Doctor**
```
C:\>flutter doctor -v
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22621.525], locale en-US)
    • Flutter version 3.3.4 on channel stable at
      C:\Users\myname\AppData\Local\Flutter\flutter_windows_2.10.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (3 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at G:\Android\Sdk\
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = G:\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • ASUS X00TD (mobile) • J7AAGF0408905JK • android-arm64  • Android 9 (API 28)
    • Windows (desktop)   • windows         • windows-x64    • Microsoft Windows [Version 10.0.22621.525]
    • Chrome (web)        • chrome          • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)          • edge            • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by exaby73** [comment] 2022-10-28 12:35
Hello @abhineetchandan. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a public Github repo with all the necessary files.
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by abhineetchandan** [comment] 2022-10-29 15:29
For 1st: Check this repository, but this doesn't work properly when using flutter run -v because of this issue of flutter: https://github.com/flutter/flutter/issues/114011

[Repository](https://github.com/abhineetchandan/hotreload)

For 2nd: Everything works properly, but when modifying any file and then saving the file to trigger hot reload doesn't work, just keeps on showing `Syncing file to device` and then debug stops.

**Comment by abhineetchandan** [comment] 2022-10-31 13:28
@exaby73 oops! sorry, typo, fixed the repository now

**Comment by exaby73** [comment] 2022-10-31 14:31
## Triage report

Running this example, I can see that the app launches and immediately crashes. No error logs are printed even with the verbose flag enabled.

<details>
<summary><code>flutter run -v</code></summary>

```console
# ...
[        ] > Task :app:assembleDebug
[        ] Caching disabled for task ':app:assembleDebug' because:
[        ]   Build cache is disabled
[        ] Task ':app:assembleDebug' is not up-to-date because:
[        ]   Task has not declared any outputs despite executing actions.
[        ] :app:assembleDebug (Thread[Execution worker for ':',5,main]) completed. Took 0.047 secs.
[        ] producer locations for task group 0 (Thread[Execution worker for ':',5,main]) started.
[        ] producer locations for task group 0 (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[        ] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[        ] Please consult deprecation warnings for more details.
[        ] BUILD SUCCESSFUL in 1s
[        ] 35 actionable tasks: 5 executed, 30 up-to-date
[ +333 ms] Running Gradle task 'assembleDebug'... (completed in 1,860ms)
[  +28 ms] calculateSha: LocalDirectory: '/home/nabeelparkar/dev/nevercode/issue_114221/build/app/outputs/flutter-apk'/app.apk
[ +334 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +1 ms] executing: /home/nabeelparkar/Android/Sdk/build-tools/33.0.0/aapt dump xmltree /home/nabeelparkar/dev/nevercode/issue_114221/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +5 ms] Exit code 0 from: /home/nabeelparkar/Android/Sdk/build-tools/33.0.0/aapt dump xmltree /home/nabeelparkar/dev/nevercode/issue_114221/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[        ] Stopping app 'app.apk' on sdk gphone64 x86 64.
[        ] executing: /home/nabeelparkar/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.example.bug
[  +26 ms] executing: /home/nabeelparkar/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.example.bug
[  +21 ms] package:com.example.bug
[        ] executing: /home/nabeelparkar/Android/Sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.bug.sha1
[  +20 ms] cd020b632507017625ed2cb39c4d7e6cb0a52103
[        ] Latest build already installed.
[        ] executing: /home/nabeelparkar/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +24 ms] --------- beginning of main
           10-31 19:57:52.110 D/CarrierSvcBindHelper(  933): No carrier app for: 0
[   +5 ms] executing: /home/nabeelparkar/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.bug/com.example.bug.MainActivity
[  +47 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
```

</details>

**Comment by abhineetchandan** [comment] 2022-11-03 03:46
@exaby73 Sorry for late response. So, actually the error occurring here is due to the casts in `MainActivity.kt` because of flutter issue: #114011. To make it work, you have to temporarily edit your `flutter.gradle` file located in `$SDK_PATH/packages/flutter_tools/gradle/flutter.gradle` as follows:
```
At line 271:
            String baseApplicationName = "android.app.Application"
            if (project.hasProperty("base-application-name")) {
                baseApplicationName = project.property("base-application-name")
//Add this line, as baseApplicationName property doesn't work in flutter builds.
//Remember to remove this after testing, as this project specific.
                baseApplicationName = "com.example.bug"
            }
```

**Comment by exaby73** [comment] 2022-11-03 06:49
Can this issue be summarised as a duplicate of https://github.com/flutter/flutter/issues/114011?

**Comment by abhineetchandan** [comment] 2022-11-03 13:56
No I think not because  if #114011 is resolved, the error which is hot reload doesn't work still exists. Only a reproducible example can be made by using some workarounds to avoid the issue of #114011. I am trying to make another reproducible example, so as to avoid that issue. Will keep you posted.

**Comment by exaby73** [comment] 2022-11-03 14:42
Okay thank you. Do post that example when you can

**Closed** 2022-11-24 16:10 UTC
Labels: waiting for customer response, in triage
