### ISSUE TITLE
RTL WEB SUPPORT

### ISSUE THREAD

**Issue by kfirbracha** [flutter/flutter#70049] opened 2020-11-08 12:04 UTC
hey , please add web support for RTL usin textdield inputs .
web rtl dosent work as it should .

mouse cursor keeps bouncing to the right , no option to mark a single letter or single word to edit.

**Comment by iapicca** [comment] 2020-11-08 17:14
@kfirbracha 
can you provide your `flutter doctor -v` and a minimal reproducible code sample

**Comment by TahaTesser** [comment] 2020-11-09 09:13
Hi @kfirbracha 
It is not fully supported https://github.com/flutter/flutter/issues/47745
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by nizar-khan** [comment] 2020-11-23 13:19
flutter Team Please solve the text field problem that it does not support RTL , Writing pointer is not working properly I am losing clients Because of this problem

**Comment by iapicca** [comment] 2020-11-23 14:10
@nizar-khan 
as for the comment above there's an [issue](https://github.com/flutter/flutter/issues/47745) open addressing this or a similar case,
if you believe that there's some element that said issue is not addressing,
please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample

**Comment by TahaTesser** [comment] 2020-12-11 12:22
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-12-11 12:22 UTC
Labels: in triage, waiting for customer response
