### ISSUE TITLE
[path_provider] example folder include in project

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#134416] opened 2023-09-11 10:08 UTC
Example folder is getting included in projects when downloading the package from pub.dev
This disrupts the development process while searching for files/widgets I am getting this `path_provider` results as well 

As written here https://github.com/dart-lang/pub-dev/issues/5862 you need to manually add `example` folder to `.pubignore`

![image](https://github.com/flutter/flutter/assets/9304740/744bd1a9-eb9c-418c-a7b7-049bab9cf6da)

![image](https://github.com/flutter/flutter/assets/9304740/40d09755-442c-43ea-8847-9ea4e0772120)

**Comment by stuartmorgan** [comment] 2023-09-11 10:52
Please don't file a copy of this issue for every package; we would not handle this differently on a per-package basis in our repository. Closing as a duplicate of https://github.com/flutter/flutter/issues/134413 to consolidate discussion.

**Closed by stuartmorgan** 2023-09-11 10:52 UTC
