### ISSUE TITLE
Error when run my macos flutter app

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#73238] opened 2021-01-03 13:42 UTC
```
embedder.cc (764): 'FlutterEngineInitialize' returned 'kInvalidArguments'. The assets path in the Flutter project arguments was missing.
2021-01-03 00:11:38.096 daybreak_flutter[73281:10722792] Failed to initialize Flutter engine: error 2
embedder.cc (1331): 'FlutterEngineSendPointerEvent' returned 'kInvalidArguments'. Engine handle was invalid.
```

My flutter version is:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.167, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] Connected device (2 available)

```

**Comment by Abhishek01039** [comment] 2021-01-03 18:06
Hello @jinfagang 
can you please provide minimal reproduction code?
Thanks

**Comment by jinfagang** [comment] 2021-01-04 04:47
@Abhishek01039  To be honestly I don't know how to using a minial codes to reproduce because my project is somewhat developed a lot and not sure which part causes the problem. However, it seems simple example can work on macOS desktop with master branch.

I am just post the issue here and I think probabably someone else might occur this issue as well.

Also wish flutter team can debugged a little with the error messages I attach it should have some issue hidden behind.

**Comment by pedromassangocode** [comment] 2021-01-04 10:26
Hi @jinfagang 
I cannot reproduce the issue on latest master channel. Please provide the steps to reproduce the issue and your `flutter doctor -v`.

<details><summary></summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: MyHomePage(),
  ));
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          height: 300,
          child: CupertinoDatePicker(
            mode: CupertinoDatePickerMode.time,
            onDateTimeChanged: (DateTime newDateTime) {},
          ),
        ),
      ),
    );
  }
}
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.168, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.168 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 299e017e41 (23 hours ago), 2021-01-03 06:29:01 -0500
    • Engine revision 121b67fb85
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by stuartmorgan** [comment] 2021-01-04 11:04
Duplicate of https://github.com/flutter/flutter/issues/72608 (which you also filed; please don't file multiple issues for the same error).

**Closed by stuartmorgan** 2021-01-04 11:04 UTC
Labels: in triage, waiting for customer response

**Comment by Zarghamabbas67** [comment] 2021-05-25 19:24
for the android issue you need to install cocoa pods
sudo gem install cocoapod
