### ISSUE TITLE
[iOS] cannot access application specific ClipboardData

### ISSUE THREAD

**Issue by CaptainDario** [flutter/flutter#144872] opened 2024-03-09 10:14 UTC
### Steps to reproduce

I am trying to read data that [ankimobile](https://apps.apple.com/us/app/ankimobile-flashcards/id373493387) added to the clipboard from UIPasteboard.general.data. Its documentation states this

``` swift
let PASTEBOARD_TYPE = "net.ankimobile.json"
if let data = UIPasteboard.general.data(forPasteboardType: PASTEBOARD_TYPE) {
   // clear clipboard
   UIPasteboard.general.setData(Data(), forPasteboardType: PASTEBOARD_TYPE)
   // ... handle json
}
```

Therefore, I am trying to read the data from Flutter's `Clipboard`

``` dart
aunchUrlString(
  "$ankiMobileURLScheme/infoForAdding?x-success=dakanji://",
  mode: LaunchMode.externalApplication
);
await Future.delayed(Duration(seconds: 5));
print(await Clipboard.getData("text/plain"));
print(await Clipboard.getData("net.ankimobile.json"));
```

To verify that the data is actually written to the Clipboard, I tried using the [super_clipboard](https://pub.dev/packages/super_clipboard) package which indeed works.

### Expected results

The Clipboard contains the data from ankimobile.

### Actual results

The Clipboard is null.

### Code sample

<details open><summary>Code sample</summary>

```dart
aunchUrlString(
  "$ankiMobileURLScheme/infoForAdding?x-success=dakanji://",
  mode: LaunchMode.externalApplication
);
await Future.delayed(Duration(seconds: 5));
print(await Clipboard.getData("text/plain"));
print(await Clipboard.getData("net.ankimobile.json"));
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
null
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 13.5.2 22G91 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.87.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2024-03-09 14:57
Closing as a duplicate of https://github.com/flutter/flutter/issues/23603, since this is a subset of general clipboard access.

**Closed by stuartmorgan** 2024-03-09 14:57 UTC
