### ISSUE TITLE
desktopApp font problem

### ISSUE THREAD

**Issue by JonathanGit** [flutter/flutter#114051] opened 2022-10-26 03:21 UTC
I upgraded to 3.3.4, but there is a problem with the desktop font display, I can't solve this problem by replacing the font globally

![image](https://user-images.githubusercontent.com/18020348/197927165-b3fa32c4-bdf2-4af0-8bfb-7522fc60a33e.png)

**Comment by huycozy** [comment] 2022-10-26 10:29
Hi @JonathanGit
Which desktop platform are you testing on?
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by JonathanGit** [comment] 2022-10-27 02:53
Hello, please check the attachment I sent to you, there are different font renderings on windows desktopApp to distinguish different flutter versions
Since I created a new project, it is still relatively large after compression and cannot be uploaded. You just need to create a new project in a different flutter version environment, and then build the code I screenshot.
![image](https://user-images.githubusercontent.com/18020348/198179621-68810f5f-f2f4-4319-aa0b-a82ac3aa2296.png)
I have sent you the attached code as an attachment
[textCode.txt](https://github.com/flutter/flutter/files/9875337/textCode.txt)

Thanks!

**Comment by JonathanGit** [comment] 2022-10-27 03:12
I forgot something just now, make it up now
![font-changed](https://user-images.githubusercontent.com/18020348/198182142-1bb87d4d-a83b-4273-a2e3-a62f070cc6cc.png)
![22b800a1-9029-4ec7-a1d9-03e451dbbcfc](https://user-images.githubusercontent.com/18020348/198182159-28632dd5-d185-4e69-bd4d-0712d7bcfb4c.png)
![16668385875863](https://user-images.githubusercontent.com/18020348/198182189-a8b2bc0a-7e47-431f-96d5-aa721571a581.png)

**Comment by huycozy** [comment] 2022-10-27 04:27
@JonathanGit The text inside your [textCode.txt](https://github.com/flutter/flutter/files/9875337/textCode.txt) seems to be wrong encoding. It's `ÉçÈº·þÎñÊÀ½çÒøÈË`.

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide information in text format for better readability. You may want to take a look at [Quickstart for writing on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/quickstart-for-writing-on-github) as well. Thank you!

**Comment by JonathanGit** [comment] 2022-10-27 08:57
你可以使用 [代码]（https://github.com/JonathanGit/flutter-font/tree/master）在3.3.4和2.10.5的flutter版本上运行windows桌面应用，您会看到字体的不同呈现方式

**Comment by JonathanGit** [comment] 2022-10-27 08:59
你可以使用[code](https://github.com/JonathanGit/flutter-font/tree/master)在3.3.4和2.10.5的flutter版本上运行windows桌面应用，您会看到字体的不同呈现方式

**Comment by JonathanGit** [comment] 2022-10-27 09:00
You can use this [code](https://github.com/JonathanGit/flutter-font/tree/master)  to run windows desktop app on flutter version 3.3.4 and 2.10.5 and you will see different rendering of fonts

**Comment by huycozy** [comment] 2022-10-28 04:12
@JonathanGit Thanks for providing the sample code. But I see there's an open issue addressing the case you described #103811.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2022-10-28 04:12 UTC
Labels: in triage
