### ISSUE TITLE
TextAlign.justify for rtl hebrew not working

### ISSUE THREAD

**Issue by Shmulik-Kravitz** [flutter/flutter#25567] opened 2018-12-19 18:02 UTC
`Hi,`

TextAlign.justify for rtl hebrew not working

snapshot of the issue:
![image](https://user-images.githubusercontent.com/29735690/50238680-c847c500-03c8-11e9-99da-e5ea92f1222e.png)

the code:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static String title = "Flutter Demo";

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: MyApp.title,
      builder: (BuildContext context, Widget child) {
        return new Directionality(
          textDirection: TextDirection.rtl,
          child: new Builder(
            builder: (BuildContext context) {
              return new MediaQuery(
                data: MediaQuery.of(context).copyWith(
                  textScaleFactor: 1.0,
                ),
                child: child,
              );
            },
          ),
        );
      },
      home: MyHomePage(title: MyApp.title),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String engText =
      """A common type of text alignment in print media is "justification", where the spaces between words, and, to a lesser extent, between glyphs or letters, are stretched or compressed to align both the left and right ends of each line of text. When using justification, it is customary to treat the last line of a paragraph separately by simply left or right aligning it, depending on the language direction. Lines in which the spaces have been stretched beyond their normal width are called lines, while those whose spaces have been compressed are called tight lines.""";
  String hebText = """סוג נפוץ של יישור טקסט באמצעי הדפסה הוא "הצדקה", כאשר רווחים בין מילים, ובמידה פחותה בין גליפים או אותיות, נמתחים או דחוסים כדי ליישר את הקצה השמאלי והימני של כל שורת טקסט. כאשר משתמשים בהצדקה, נהוג להתייחס לשורה האחרונה של פסקה בנפרד על ידי פשוט ימינה או שמאלה יישור זה, בהתאם לכיוון השפה. קווים שבהם המרחבים נמתחים מעבר לרוחב הרגיל שלהם נקראים קווים, ואילו אלה שרוחביהם נדחסו נקראים קווים הדוקים.
  """;

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text(widget.title),
        ),
        body: Padding(
            padding: EdgeInsets.all(10.0),
            child: Column(
              children: <Widget>[
                new Text("English Text TextAlign.justify"),
                new Text(engText, textAlign: TextAlign.justify),
                new Divider(height: 20.0),
                new Text("Hebrew Text TextAlign.justify"),
                new Text(hebText, textAlign: TextAlign.justify, textDirection: TextDirection.rtl,),
                new Text("Hebrew Text TextAlign.start"),
                new Text(hebText, textAlign: TextAlign.start),
              ],
            )));
  }
}

```

**Comment by zoechi** [comment] 2018-12-19 18:17
Please add the output of `flutter doctor -v`.

**Comment by Shmulik-Kravitz** [comment] 2018-12-20 05:53
> 
> 
> Please add the output of `flutter doctor -v`.

```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.471], locale he-IL)
    • Flutter version 1.0.0 at D:\flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

```

**Comment by HansMuller** [comment] 2018-12-20 17:40
CC @jason-simmons - problem with libtxt?

**Comment by TarekkMA** [comment] 2019-03-02 18:44
I think the issue is not solved yet.
``flutter doctor -v`` yields the following.
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/tarekkma/Developer/Libs/flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

![screen shot 2019-03-02 at 8 39 45 pm](https://user-images.githubusercontent.com/6633545/53686067-67732c00-3d2b-11e9-8ede-f1de11c6c4d7.png)

Flutter

**Comment by WorthPly** [comment] 2019-05-13 06:19
This issue is not resolved rtl is not working with TextAlign.justify.

here is flutter doctor result

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.5.4-hotfix.1, on Mac OS X 10.13.6 17G65, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by WorthPly** [comment] 2019-06-12 11:43
Any update on this it not working with arabic language.

**Comment by maah75** [comment] 2019-07-11 08:59
still not fixed for rtl lang with the new version  of flutter please fix it

**Comment by HansMuller** [comment] 2019-07-16 17:56
I'm reopening this issue per https://github.com/flutter/flutter/issues/25567#issuecomment-468948323

cc @jason-simmons

**Comment by OsamaAbbas** [comment] 2019-09-01 19:57
Is this issue going to be fixed soon?

**Comment by OsamaAbbas** [comment] 2019-09-04 06:43
This issue should be closed. Refer to: https://github.com/flutter/flutter/issues/28700#issuecomment-527681906

**Comment by HansMuller** [comment] 2019-09-04 16:38
OK, I'm closing this per https://github.com/flutter/flutter/issues/25567#issuecomment-527765881

**Closed by HansMuller** 2019-09-04 16:38 UTC
Labels: a: typography, engine
