### ISSUE TITLE
Need documentation for `flutter driver` when used with apps that include native UI

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#36259] opened 2019-07-16 13:55 UTC
## Use case

Reference to https://github.com/appium/appium/issues/12919, 
Flutter goes with `flutter drive`, the e2e test tool, but it does not work with app that has both flutter view and native view (such as embedding Flutter to existing app), or flutter view with web view (open a webview in Flutter).

Having appium flutter driver in Appium would solve both problems above, similar to http://appium.io/docs/en/writing-running-appium/web/hybrid/

## Proposal

In order to create/contribute to an appium driver, there should be a document of what kind of protocol/communication `flutter drive` is using.

**Comment by longravuth** [comment] 2020-01-08 20:35
Blocker for e2e testing for apps dependent on native components. Hopefully, this is in the work.

**Comment by csells** [comment] 2020-01-13 16:23
@collinjackson for his input

**Comment by shibupanda** [comment] 2020-01-31 16:59
@jmagman Any update here as most of the folks are block due to this. Really appreciate if we can get some status.

**Comment by jmagman** [comment] 2020-01-31 19:30
@shibupanda I have no context for this and am not working on it.  

I'm not sure if this issue is tracking a request for `flutter drive` documentation or for `e2e` working with add-to-app.

\cc @collinjackson @digiter @xster

**Comment by xster** [comment] 2020-03-11 01:09
@RedBrogdon is working on adding such types of examples to https://github.com/flutter/samples/tree/master/add_to_app for Android. 

@collinjackson might be interesting describing the range of valid testing strategies and APIs you've been working on in https://flutter.dev/docs/testing.

**Comment by RedBrogdon** [comment] 2020-03-12 20:21
Relevant PR for integration tests via espresso in add-to-app: https://github.com/flutter/samples/pull/323/files

**Comment by darrinps** [comment] 2020-04-20 15:09
@RedBrogdon Until flutter_driver works with web views, is there a suggested work around for it? A way that Google recommends to get defer out of flutter_driver, login, then get back into it. I was thinking of using flutter_driver with espresso to actually log in, but that doesn't seem to be working right now (I filed this https://github.com/flutter/flutter/issues/54780).

**Comment by RedBrogdon** [comment] 2020-04-23 01:08
@collinjackson would be the expert here as far as the internal details of the espresso plugin, but I did need to play with the versions of some of the gradle artifacts when I was adding espresso tests to the sample apps.

**Comment by cuk2dn95** [comment] 2021-01-29 15:21
bump

**Comment by JulianKeppelerCP** [comment] 2021-10-05 16:02
bump

**Comment by jmagman** [comment] 2021-10-05 16:40
Please don't bump, it adds noise.  If there were updates on this issue someone would comment on it.

**Comment by csells** [comment] 2021-10-05 17:10
cc @dnfield @johnpryan

**Comment by RedBrogdon** [comment] 2021-10-12 00:16
If you haven't already, take a look at the espresso package: https://pub.dev/packages/espresso. It's something that was launched last year to help with Android-to-Flutter-and-back tests.

The documentation for the plugin has some good info, and we added an example test to one of the add-to-app samples: https://github.com/flutter/samples/blob/master/add_to_app/fullscreen/android_fullscreen/app/src/androidTest/java/dev/flutter/example/androidfullscreen/ExampleInstrumentedTest.kt.

**Comment by bartekpacia** [comment] 2022-10-14 11:17
If you want to interact with native views from withing Dart tests run from `flutter test`, take a look at [Patrol](https://github.com/leancodepl/patrol) :)

**Comment by matanlurey** [comment] 2024-10-10 16:32
This is not something we will be doing, folks are able to add their own extensions to driver as necessary (as seen above).

If you want an example of doing something like this with flutter_driver (we won't make this package public, you could take a look at https://github.com/flutter/flutter/tree/master/dev/tools/native_driver), or otherwise I recommend https://pub.dev/packages/patrol.

Duplicate of https://github.com/flutter/flutter/issues/34345.

**Closed by matanlurey** 2024-10-10 16:32 UTC
Labels: a: tests, tool, d: api docs, a: existing-apps, f: integration_test, P3, team-tool, triaged-tool
