### ISSUE TITLE
Please extend the list of supported locales with one more language: Turkmen (TM or TK)

### ISSUE THREAD

**Issue by murat-ti** [flutter/flutter#86466] opened 2021-07-15 07:09 UTC
Add the following locale to material_localizations.dart:
tm - Turkmen (if not possible using tm, you can use tk)

Because my language is not supported yet, I need to write my own class, like:
class _TmMaterialLocalizationsDelegate extends LocalizationsDelegate {
...
}

Or if I use popular libarary like easy_localization, I need to do next trick to support my language:
en_US is supported, so I need to use it like en_TM, otherwise it doesn't work. Because Turkmen is not yet in the list of supported languages of the flutter_localization package, on which Easy_localizations depends.

I want to write my code in right way, so please add Turkmen locale.

Thanks.

**Comment by TahaTesser** [comment] 2021-07-15 07:54
Hi @murat-ti 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/46710
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-15 07:54 UTC
Labels: in triage

**Comment by murat-ti** [comment] 2021-07-15 08:06
Hi,

I agree.

Thank you
