### ISSUE TITLE
statusBarIconBrightness is not working on Xiaomi 11 

### ISSUE THREAD

**Issue by cwf1992** [flutter/flutter#96507] opened 2022-01-12 03:33 UTC
## Steps to Reproduce

when upgrade flutter from 2.2.0 to 2.8.1,
try to set statusBarIconBrightness: Brightness.dark, it works on HUAWEI，Samsung, iOS and other devices, but it doesn't work on XiaoMi 11. but it looks normal on XiaoMi 11 when flutter version is 2.2.0.

**Expected results:** Status bar icon colors must be a dark color

**Actual results:** Status bar icon colors are still white

<details>
<summary>Code sample</summary>

```
AnnotatedRegion<SystemUiOverlayStyle>(
  value: SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.dark,
    statusBarBrightness: Brightness.dark ,
    systemNavigationBarColor: Colors.blue,
    systemNavigationBarDividerColor: Colors.transparent,
    systemNavigationBarIconBrightness: Brightness.dark,
  )
 child : MaterialApp(...)
),
```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.1 20G80 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment] 2022-01-12 08:20
Possiblly related to https://github.com/flutter/flutter/issues/95973

**Comment by maheshmnj** [comment] 2022-01-12 08:21
Possibly related to https://github.com/flutter/flutter/issues/95973

**Comment by darshankawar** [comment] 2022-01-12 08:23
@cwf1992 
Looking at your code sample, it seems to be similar / duplicate of https://github.com/flutter/flutter/issues/95614. Take a look at the underlying comments from that issue which hopefully should resolve your issue.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen.

**Closed by darshankawar** 2022-01-12 08:23 UTC
Labels: in triage
