### ISSUE TITLE
Oops; flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\flutter-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.6\android\src\main\java\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.java'".

### ISSUE THREAD

**Issue by zancheng** [flutter/flutter#106003] opened 2022-06-15 09:01 UTC
## Steps to Reproduce

1. flutter pub add flutter_plugin_android_lifecycle
2. Failed to send crash report due to a network error: SocketException: 信号灯超时时间已到
 (OS Error: 信号灯超时时间已到
, errno = 121), address = clients2.google.com, port = 50102
Oops; flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path =
'D:\flutter-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.6\android\src\main\java\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.java'".

## command

flutter pub add flutter_plugin_android_lifecycle

## exception

FileSystemException: FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\flutter-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-2.0.6\android\src\main\java\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.java'

```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:208:53)
#4      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:155:49)
#5      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart)
#6      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:149:30)
#7      _extractPlatformMaps (package:flutter_tools/src/flutter_plugins.dart:352:40)
#8      _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:367:53)
#9      injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1114:11)
<asynchronous suspension>
#10     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:381:5)
<asynchronous suspension>
#11     PackagesInteractiveGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:357:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.0.2, on Microsoft Windows [版本 10.0.19042.1526], locale zh-CN)
    • Flutter version 3.0.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (7 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\workApps\android-sdk-windows-new
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at E:\workApps\Visual-studio-m
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1)
    • Android Studio at E:\workApps\android studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at E:\workApps\IntelliJ IDEA 2021.1.2
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7798

[✓] VS Code (version 1.67.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • YAL AL10 (mobile) • ERLDU20423010578 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [版本 10.0.19042.1526]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 98.0.1108.56

[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Connection terminated during handshake
    • 

! Doctor found issues in 2 categories.
```

</summary>

I tried the following methods, but none of them worked:

1. delete .flutter-plugins

2. set file read / write permission

3. Flutter SDK on the C disk

I put flutter_ plugin_ android_ Life cycle deletion is normal.

Hope you can give me a clear solution, thank you !

**Comment by exaby73** [comment] 2022-06-15 09:31
Hello. I am unable to reproduce this issue. Have you tried [configuring a mirror][1] with Flutter?

###### Logs

```
flutter pub add flutter_plugin_android_lifecycle
Resolving dependencies...
  async 2.8.2 (2.9.0 available)
  characters 1.2.0 (1.2.1 available)
+ flutter_plugin_android_lifecycle 2.0.6
  material_color_utilities 0.1.4 (0.1.5 available)
  meta 1.7.0 (1.8.0 available)
  path 1.8.1 (1.8.2 available)
  source_span 1.8.2 (1.9.0 available)
  string_scanner 1.1.0 (1.1.1 available)
Changed 1 dependency!
```

[1]: https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site

**Comment by exaby73** [comment] 2022-06-15 11:59
Duplicate of #65021

**Closed by exaby73** 2022-06-15 11:59 UTC
Labels: in triage

**Comment by zancheng** [comment] 2022-06-16 00:23
> #65021的副本[](https://github.com/flutter/flutter/issues/65021)

Modify the under the item .gradle files, or under the plug-in .gradle files?

**Comment by zancheng** [comment] 2022-06-16 01:11
> Duplicate of #65021

Modify the under the item .gradle files, or under the plug-in .gradle files?

**Comment by exaby73** [comment] 2022-06-16 08:20
I don't think you can do much here. You can follow up on the original issue.

**Comment by zancheng** [comment] 2022-06-17 09:29
> I don't think you can do much here. You can follow up on the original issue.

Thank you for your reply.
