### ISSUE TITLE
[iOS][Impeller] BoxShadow fills entire container with shadow color

### ISSUE THREAD

**Issue by TatsuUkraine** [flutter/flutter#139473] opened 2023-12-04 12:17 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create DecoratedBox without child and background color
2. Appy BoxShadow

Could be related to https://github.com/flutter/flutter/issues/139238

### Expected results

color defined in a box shadow applies only to shadow

### Actual results

color defined in box shadow applies to shadow and to container background

### Code sample

<details><summary>Code sample</summary>

```dart
SizedBox(
          height: 100,
          width: 100,
          child: DecoratedBox(
            decoration: BoxDecoration(
              boxShadow: [
                BoxShadow(
                  blurRadius: 4,
                  blurStyle: BlurStyle.outer,
                  color: Colors.blue,
                ),
              ],
            ),
          ),
        )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Android
<img width="156" alt="Android" src="https://github.com/flutter/flutter/assets/621542/9843d4f3-8566-4baa-903e-b3f7f62f3f04">

iOS
<img width="177" alt="iOS" src="https://github.com/flutter/flutter/assets/621542/132e983d-f860-41de-b15f-887ff6ac3cad">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.2, on macOS 13.5.2 22G91 darwin-arm64, locale ru)
    • Flutter version 3.16.2 on channel stable at /Users/tatsu/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (4 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at ....
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = ....
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (4 available)

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by jonahwilliams** [comment] 2023-12-04 18:55
Duplicate of https://github.com/flutter/flutter/issues/134178 . The blur styles are not implemented on impeller.

**Closed by jonahwilliams** 2023-12-04 18:55 UTC
Labels: e: impeller, team-engine

**Comment by TatsuUkraine** [comment] 2023-12-04 18:57
> Duplicate of #134178 . The blur styles are not implemented on impeller.

I think all was working fine in 3.13 🤔
