### ISSUE TITLE
[iOS] Could not build the application for the simulator.

### ISSUE THREAD

**Issue by RenanDelfanti** [flutter/flutter#66546] opened 2020-09-24 11:39 UTC
## Steps to Reproduce

1. clone existing app.
2. flutter run -v

**Expected results:** Apps runing on ios simulator
```
**Actual results:** Error: ```#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)```
```
<details>
  <summary>Logs</summary>

```

```

```
```

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.3 19D76, locale pt-BR)
    • Flutter version 1.20.4 at /Users/delfanti/development/flutter
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • A3C5295A-7C2A-4B7A-81BC-0A1738DAED26 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by RenanDelfanti** [comment] 2020-09-24 11:46
Flutter run -v:
https://www.dropbox.com/s/butdjyhyukrvqsy/flutter%20error.txt?dl=0

**Comment by TahaTesser** [comment] 2020-09-24 14:17
Hi @RenanDelfanti 
Can you please provide  a complete reproducible minimal code sample
Thank you

**Comment by RenanDelfanti** [comment] 2020-09-24 14:23
Hi @TahaTesser 
My code is private, sorry.
However, I found the same problem in this issue #63348.
However the solution presented did not work in my case.
This error started after updating the flutter to version 1.20

**Comment by RenanDelfanti** [comment] 2020-09-24 14:37
I try beta branch, but I got the same error

**Comment by TahaTesser** [comment] 2020-09-25 06:54
Hi @RenanDelfanti 
Please create a new project and try again `flutter create myapp`, if the problem persists, please provide logs running this new project sample 

If the issue doesn't reproduce with a new project, please isolate the code that causes this issue in your project,  create a minimal code sample without privat code and  third  party packages 
Thank you

**Comment by RenanDelfanti** [comment] 2020-09-25 14:18
@TahaTesser 
After several hours of trying to find the cause of the problem, I discovered that the cause was firebase.
To correct my problem I followed the steps of the issue: https://github.com/FirebaseExtended/flutterfire/issues/3272

**Comment by RenanDelfanti** [comment] 2020-09-25 15:30
@TahaTesser 
I am opening to say that this problem only happens in the last stable version, when I did the tests I mentioned above, I did it in version 1.20.1
Now in version 1.20.4 the error recurs

**Comment by TahaTesser** [comment] 2020-09-28 08:20
Hi @RenanDelfanti 
Can you please provide details asked here https://github.com/flutter/flutter/issues/66546#issuecomment-698757534
Thank you

**Comment by Gregga16** [comment] 2020-09-29 21:38
I have the same problem. A few days ago firebase was build successful, but not anymore. Every time the error 
`Could not build module 'firebase_core'` 
Can anyone tell me what the do?

**Comment by RenanDelfanti** [comment] 2020-09-30 01:56
@Gregga16 I still haven't figured out the cause yet, but for now I went back to version 1.20.1 where it builds.

**Comment by RenanDelfanti** [comment] 2020-09-30 01:57
However, I will take some time off and try to study the cause by isolating the plugins from my projects, to see what is causing this problem.

**Comment by Gregga16** [comment] 2020-09-30 06:32
Which version of xcode are you using? I am on Version 12.0.1. 

I will try today on flutter version 1.20.1

**Comment by TahaTesser** [comment] 2020-09-30 07:09
Hi @RenanDelfanti 
When you upgrade again and find the cause, please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
Closing this issue without additional information
Thank you

**Closed by TahaTesser** 2020-09-30 07:09 UTC
Labels: in triage

**Comment by RenanDelfanti** [comment] 2020-09-30 09:30
@Gregga16 I'm on version 11 of xcode
