### ISSUE TITLE
Unexpected null value in BaseTapGestureRecognizer._checkDown

### ISSUE THREAD

**Issue by jhass** [flutter/flutter#82107] opened 2021-05-08 13:03 UTC
I'm seeing the following crash in a Flutter 2.0.6 based app:

```
Null check operator used on a null value

Stack trace:

#0 BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:287)
#1 BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:265)
#2 MultipleTapGestureRecognizer.rejectGesture (package:flutter_html/src/utils.dart:54)
#3 GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:214)
#4 GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53)
#5 OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:260)
#6 BaseTapGestureRecognizer.resolve (package:flutter/src/gestures/tap.dart:253)
#7 PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:472)
#8 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93)
#9 PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138)
#10 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397)
#11 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136)
#12 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122)
#13 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381)
#14 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361)
#15 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278)
#16 GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316)
#17 GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280)
#18 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238)
#19 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221)
#20 _rootRunUnary (dart:async/zone.dart:1370)
#21 _CustomZone.runUnary (dart:async/zone.dart:1265)
#22 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170)
#23 _invoke1 (dart:ui/hooks.dart:180)
#24 PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276)
#25 _dispatchPointerDataPacket (dart:ui/hooks.dart:96)
```

I couldn't find a matching existing report, but it seems quite close to #43310 / #50574.

Unfortunately I have no good way to reproduce this but I'm seeing it while scrolling down a `ListView` of user generated content containing among lots of other things tapable images. So maybe it's related to a large tapable area being used to scroll down something it's contained within.

**Comment by darshankawar** [comment] 2021-05-10 09:27
@jhass 
It'd be great if you could try to find a pattern that shows this crash around below scenario you mentioned, that'll help us to properly address this issue.






> but I'm seeing it while scrolling down a `ListView` of user generated content containing among lots of other things tapable images

**Comment by jhass** [comment] 2021-05-10 12:03
Hi @darshankawar 

as I outlined my app is essentially a ListView of user generated content, in particular markdown transformed to HTML and rendered using the flutter_html. Given this app is also a hobby project I cannot foresee being able to invest the substantial time it will take to find such a minimal reproducing example. Please don't make this a requirement to you fixing crashes in your product.

Do you imagine the fix is substantially different than turning the null assertion into null check?

**Comment by nt4f04uNd** [comment] 2021-05-10 17:04
It looks like you are describing a bug in a third party package, flutter_html is not supported by Flutter team

**Comment by nt4f04uNd** [comment] 2021-05-11 16:45
> Did you take a look at the stack trace? Where does it as much as touch third party code?

Sorry, I'm not quite sure I understood what you are asking.

This line of the stack trace you attached indicates that exception is thrown from `flutter_html` library
`#2 MultipleTapGestureRecognizer.rejectGesture (package:flutter_html/src/utils.dart:54)`

> Do you see any negative consequences from turning that null assertion into a null check?

As far as I can tell, this assertion is there to ensure that gesture recognizer is properly used. Converting it into null check will hide potential errors like this and developers will be left unaware of potential unexpected behaviors

**Comment by nt4f04uNd** [comment] 2021-05-11 18:30
I reproduced it

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  Home({Key key}) : super(key: key);

  final list = List.generate(1000, (index) => index);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: list.length,
        itemBuilder: (BuildContext context, int index) {
          return RawGestureDetector(
            gestures: {
              MultipleTapGestureRecognizer: GestureRecognizerFactoryWithHandlers<MultipleTapGestureRecognizer>(
                () => MultipleTapGestureRecognizer(),
                (MultipleTapGestureRecognizer instance) => instance
                ..onTap = () {
                  print('tap');
                },
              )
            },
            child: const Image(
              image: NetworkImage('https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg'),
            ),
          );
        },
      ),
    );
  }
}

class MultipleTapGestureRecognizer extends TapGestureRecognizer {
  @override
  void rejectGesture(int pointer) {
    acceptGesture(pointer);
  }
}
```
</details>

**Comment by darshankawar** [comment] 2021-05-12 06:18
I see the same behavior as below:

<details>
<summary> console error log </summary>

```
Null check operator used on a null value

Stack trace:

#0 BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:287)
#1 BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:265)
#2 MultipleTapGestureRecognizer.rejectGesture (package:flutter_html/src/utils.dart:54)
#3 GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:214)
#4 GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53)
#5 OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:260)
#6 BaseTapGestureRecognizer.resolve (package:flutter/src/gestures/tap.dart:253)
#7 PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:472)
#8 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93)
#9 PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138)
#10 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397)
#11 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136)
#12 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122)
#13 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381)
#14 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361)
#15 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278)
#16 GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316)
#17 GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280)
#18 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238)
#19 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221)
#20 _rootRunUnary (dart:async/zone.dart:1370)
#21 _CustomZone.runUnary (dart:async/zone.dart:1265)
#22 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170)
#23 _invoke1 (dart:ui/hooks.dart:180)
#24 PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276)
#25 _dispatchPointerDataPacket (dart:ui/hooks.dart:96)



```

</details>

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 2.3.0-2.0.pre.139, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.139 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e621ebfb34 (3 hours ago), 2021-05-11 23:29:03 -0400
    • Engine revision 8e332453b8
    • Dart version 2.14.0 (build
      2.14.0-edge.b99466d472e369990eb22de332cb5b2967b3ea00)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.

```

</details>

**Comment by xu-baolin** [comment] 2021-05-13 03:13
Same issue #71331
There is no reason to override `rejectGesture` with `acceptGesture`, and we can't do this. This will destroy the architectural design of the flutter.
CC @dkwingsmt

**Comment by jhass** [comment] 2021-05-13 08:35
Looks like the initial approach is from https://gist.github.com/Nash0x7E2/08acca529096d93f3df0f60f9c034056

This was introduced to flutter_html to fix another issue: https://github.com/Sub6Resources/flutter_html/pull/631

Your "fix" in flutter_carousel_slider was just removing the workaround, restoring the original issue this wanted to fix. Nobody ever followed up with a proper way to do this: https://github.com/serenader2014/flutter_carousel_slider/blob/master/lib/carousel_slider.dart#L338

What is the proper way to do this? I hope just living with the broken behavior this wants to workaround is not your recommended solution.

**Comment by goderbauer** [comment] 2021-05-19 22:31
As @xu-baolin points out, this code is just not legal:

```dart
class MultipleTapGestureRecognizer extends TapGestureRecognizer {
  @override
  void rejectGesture(int pointer) {
    acceptGesture(pointer);
  }
}
```

Since the `MultipleTapGestureRecognizer` (which is causing this) is not part of the framework, I am going to close this issue here.

**Closed by goderbauer** 2021-05-19 22:31 UTC
Labels: a: error message, f: gestures, f: scrolling, found in release: 2.3, framework, has reproducible steps, severe: crash

**Comment by dkwingsmt** [comment] 2021-05-19 22:52
`TapGestureRecognizer` is not meant to be used as a base class. If it works in this way, it's fine, and if the usage is added it into `flutter/tests`, we'll probably even keep compatibility for it. But if it is extended in an unintended way and caused crashes, that's probably because the extension is incorrect. Providing these methods does not mean using them in any order is legal.

**Please file this bug to the package owner.** (Or not, if you don't mean to file at all.)

We perform assertions against internal states all the time, especially for complex logic as gesture recognizers, and we encourage so. We have done too few assertions, not too many. Assertions ensure that premises are kept throughout the lifecycle of the object. In the situation of this ticket, `_checkDown` means "trigger the tap down callback if non null". It is called whenever the recognizer is confirmed to own this tap, which means this tap must have happened, which of course means there must have been a down event.
