### ISSUE TITLE
firebase_ml_vision supports FirebaseVisionImage.fromBytes() without FirebaseVisionImageMetadata

### ISSUE THREAD

**Issue by thanhbinh84** [flutter/flutter#66967] opened 2020-09-30 10:43 UTC
## Use case

Given an `Uint8List` photo, we have to store to a local file in order to convert `FirebaseVisionImage`

There is a `FirebaseVisionImage.fromBytes()` function, but it perhaps is for `CameraImage` only, with the normal photo such retrieving from the Internet, we have to store to a file and then use `FirebaseVisionImage.fromFile()` that wastes an additional step and space. 

## Proposal
Update this function 
```
FirebaseVisionImage.fromBytes(
    Uint8List bytes
  )
```
With FirebaseVisionImageMetadata is optional

**Comment by TahaTesser** [comment] 2020-09-30 11:20
hI @thanhbinh84 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-30 11:20 UTC
