### ISSUE TITLE
The 'runnable apps' drop down is frequently incomplete

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#2608] opened 2016-03-11 12:13 UTC
I'm having a lot of problems where the runnable list is missing items. 
The most recent case was:

- I had an open project which I had run.
- I added a new project and waited for pub get.
- the new project doesn't appear in the list
- Switch to main.dart on the new project, still no luck
- Close all the existing tabs, open the main.dart of the new project -- now only the new project appears, the original one that is also still in the folder list is not shown.

Perhaps I'm mis-understanding, I would assume that drop down list is supposed to contain 'all of the things that I could run that are in Atom'?

**Comment by eseidelGoogle** [comment] 2016-03-11 16:18
https://github.com/flutter/flutter/issues/2176 and https://github.com/flutter/flutter/issues/2587 are also this issue.  @devoncarew is on the case.  I'm not sure which is a dupe of which, so I'll leave him to sort that out.  This appears to mention more cases.

**Comment by devoncarew** [comment] 2016-03-11 16:29
Closing as a dupe - we do need to re-work the UX for this.

**Closed by devoncarew** 2016-03-11 16:29 UTC
