### ISSUE TITLE
google_sign_in not throwing user cancellation

### ISSUE THREAD

**Issue by livetalabs** [flutter/flutter#57857] opened 2020-05-23 15:16 UTC
google_sign_in package 4.5.1

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.836], locale en-AU)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (11 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Bill\AppData\Local\Android\Sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Bill\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Bill\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\Bill\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Scenario**: User has multiple google accounts on their device. User tries to login with Google via the signIn plugin method and they get a pop-up for the user to choose on of their accounts (see image example).  If the user taps out of the pop-up the API throws an exception.  However this exception (see image) is not thrown back up to the client consumer to handle it.  The exception crawls up to the _callMethod method of the GoogleSignIn class and the trail ends there.  This could be intentional but I would like my app to know if the user has cancelled the login.

Request: Could the dev team please throw the exception up the chain so the client can handle it?

**Comment by livetalabs** [comment] 2020-05-23 15:17
![_callMethod](https://user-images.githubusercontent.com/47648109/82734163-4e093600-9d5c-11ea-9b2f-334fea926e12.jpg)
![exception](https://user-images.githubusercontent.com/47648109/82734165-506b9000-9d5c-11ea-9aa1-047818338781.jpg)
![google choose account](https://user-images.githubusercontent.com/47648109/82734167-52355380-9d5c-11ea-856a-e2b2a1ca3d9c.png)

**Comment by TahaTesser** [comment] 2020-05-25 11:11
duplicate of https://github.com/flutter/flutter/issues/44431

**Closed by TahaTesser** 2020-05-25 11:11 UTC
