### ISSUE TITLE
Add `color` property to `CupertinoScrollbar`

### ISSUE THREAD

**Issue by gintominto5329** [flutter/flutter#116336] opened 2022-12-01 11:52 UTC
Hello,

The `CupertinoActivityIndicator` widget has a `color` property, which is used internally like ```widget.color ?? CupertinoDynamicColor.resolve(_kActiveTickColor, context)```, 

But the `CupertinoScrollbar` widget has its color ~hardcoded(unchangeable by user), used by widget like ```CupertinoDynamicColor.resolve(_kScrollbarColor, context)```,

Currently i have copied the widget from the flutter library sources, and added the color property manually and locally, but would be better if implemented and supported officially,

thanking you

**Comment by exaby73** [comment] 2022-12-01 13:29
Hello @gintominto5329. Thank you for filing this proposal. This looks like a duplicate of https://github.com/flutter/flutter/issues/99013. Please follow up on that issue. Closing this one for the same reason. Thank you

**Closed by exaby73** 2022-12-01 13:29 UTC
Labels: in triage
