### ISSUE TITLE
Image.network() bug. Image.network in debug mode accepts offline asset image and show while in production it dont show. 

### ISSUE THREAD

**Issue by ysumiit005** [flutter/flutter#143919] opened 2024-02-22 06:07 UTC
### What package does this bug report belong to?

Flutter Images the default we get

### What target platforms are you seeing this bug on?

Web

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
bydefault image.network in flutter
```

</details>

### Steps to reproduce

```
Container(
                      // color: Colors.deepOrange,
                      height: double.maxFinite,
                      child: Image.network(
                        "assets/images/contactus_vector.jpg",
                        fit: BoxFit.cover,
                      ),
                    ),  
```
when run in debug mode / in on pc as developer - all fine 
when make build and publish to web - cant see the image

### Expected results

in debug mode i should have got image error. error like - "given image don't exist on internet" 

### Actual results

image.network() shows image from offline asset with no error prompt

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
Container(
                      // color: Colors.deepOrange,
                      height: double.maxFinite,
                      child: Image.network(
                        "assets/images/contactus_vector.jpg",
                        fit: BoxFit.cover,
                      ),
                    ),
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.22621.3155], locale en-IN)
    • Flutter version 3.16.2 on channel stable at C:\Users\Sumit\Documents\Sumit_Workspace\flutter_windows_3.16.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (3 months ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Sumit\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = C:\Users\Sumit\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.86.2)
    • VS Code at C:\Users\Sumit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3155]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.128

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by yjbanov** [comment] 2024-03-14 18:24
Duplicate of https://github.com/flutter/flutter/issues/86833

**Closed by yjbanov** 2024-03-14 18:24 UTC
Labels: platform-web, a: images, a: error message, has reproducible steps, team-web, found in release: 3.19, found in release: 3.20
