### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by Ihfan7477** [flutter/flutter#101801] opened 2022-04-13 03:23 UTC
%23%23 Command
```
flutter run
```

%23%23 Steps to Reproduce
1. ...
2. ...
3. ...

%23%23 Logs
StateError: Bad state: No context with the running Dart application.
```
%230      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
%231      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
%232      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
%233      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
%234      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.379, on Microsoft Windows [Version 10.0.18363.1556], locale
    en-ID)
    • Flutter version 2.13.0-0.0.pre.379 at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bc0ec85717 (8 days ago), 2022-04-04 17:27:18 -0700
    • Engine revision e7e7ca1252
    • Dart version 2.17.0 (build 2.17.0-266.0.dev)
    • DevTools version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\ACER\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.66.1)
    • VS Code at C:\Users\ACER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1556]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.29

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

%23%23 Flutter Application Metadata
**Type**: app
**Version**: 1.0.0 1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6
%23%23%23 Plugins
flutter_midtrans_payment-0.3.0
flutter_plugin_android_lifecycle-2.0.5
fxendit-0.0.3
image_picker-0.8.0 4
image_picker_for_web-2.0.0
midtrans_sdk-0.3.4
onesignal_flutter-3.3.0
path_provider_linux-2.1.5
path_provider_windows-2.0.5
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
url_launcher-5.7.10
url_launcher_linux-0.0.1 4
url_launcher_macos-0.0.1 9
url_launcher_web-0.1.5 3
url_launcher_windows-0.0.1 3

**Comment by danagbemava-nc** [comment] 2022-04-13 07:00
Hi @Ihfan7477 , this is a duplicate of #95916.

If you have any information on how to reproduce or what you were doing when you experienced this issue, kindly provide more details in #95916. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-04-13 07:00 UTC
Labels: in triage
