### ISSUE TITLE
Web pages build with Flutter web hangs

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#47450] opened 2019-12-19 12:35 UTC
My web app on both Android and iOS scroll ok, but after a bit of scrolling the screen just freezes. i doesn't accept any more gestures.

```
Flutter 1.13.3-pre.83 • channel master • https://github.com/flutter/flutter
Framework • revision 78db965642 (2 hours ago) • 2019-12-19 11:23:01 +0100
Engine • revision 0f90e6546b
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.3-pre.83, on Mac OS X 10.15.1 19B88, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] Connected device (4 available)

```
This is Android.
![android](https://user-images.githubusercontent.com/9283414/71174002-c1b68c80-226c-11ea-835f-3a1a684c4bbe.gif)

This is iOS.
![ios](https://user-images.githubusercontent.com/9283414/71173948-af3c5300-226c-11ea-9151-8ec014445e8f.gif)

**Comment by long1eu** [comment] 2019-12-19 12:52
This is what I found in the console. 

```
dart_stack_trace_mapper.js:263 Uncaught Bad state: Source maps are not done loading.
    at Object.a (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:263:3)
    at d1.jd (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:2272:23)
    at Object.ig (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:220:69)
    at iN (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:1979:10)
    at Object.<anonymous> (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:1973:42)
    at dart._StackTrace.new.toString (http://localhost:62022/dart_sdk.js:6087:29)
    at Object._toString [as toString] (http://localhost:62022/dart_sdk.js:4418:26)
    at assertions.FlutterErrorDetails.new.debugFillProperties (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/foundation/debug.dart.js:2931:50)
    at assertions._FlutterErrorDetailsNode.new.get builder (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/foundation/debug.dart.js:2253:34)
    at assertions._FlutterErrorDetailsNode.new.get builder [as builder] (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/foundation/debug.dart.js:3199:27)
    at assertions._FlutterErrorDetailsNode.new.getProperties (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/foundation/debug.dart.js:2265:45)
    at diagnostics$.TextTreeRenderer.new.render (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/foundation/debug.dart.js:1108:37)
    at Function.dumpErrorToConsole (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/foundation/debug.dart.js:3064:142)
    at Function.reportError (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/foundation/debug.dart.js:3127:76)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/scheduler/ticker.dart.js:1160:33)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/scheduler/ticker.dart.js:1128:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:62022/Users/long1eu/IDE/flutter_dev/flutter/packages/flutter/lib/src/scheduler/ticker.dart.js:1085:12)
    at http://localhost:62022/dart_sdk.js:161848:23
```

**Comment by long1eu** [comment] 2019-12-19 13:04
And this is what I get when running on desktop.

![Screenshot 2019-12-19 at 15 03 41](https://user-images.githubusercontent.com/9283414/71175691-d4cb5b80-2270-11ea-9bae-bf91aaa79d03.png)

**Comment by iapicca** [comment] 2019-12-19 15:03
Hi @long1eu 
are you experiencing this in `debug` or `release` ?
can you please provide your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by long1eu** [comment] 2019-12-19 15:04
This is on release.

**Comment by iapicca** [comment] 2019-12-19 16:26
Thanks for the reply @long1eu 
can you please provide your `flutter run --verbose` 
and a minimal code sample to reproduce the problem?
Thank you

**Comment by iapicca** [comment] 2019-12-19 16:28
possibly related to https://github.com/flutter/flutter/issues/47281

**Comment by long1eu** [comment] 2019-12-19 16:32
Sure. here it is. Please keep in mind that I am talking about Flutter _WEB_ this is not realated to a webview.

```
long1eu@Razvans-51-Mac-Pro web % flutterdev run --verbose -d Ch
[  +49 ms] executing: [/Users/long1eu/IDE/flutter_dev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +75 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 78db9656424768d71b363f3365fa5637b3a3fa49
[        ] executing: [/Users/long1eu/IDE/flutter_dev/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +44 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.13.2-83-g78db96564
[  +19 ms] executing: [/Users/long1eu/IDE/flutter_dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/long1eu/IDE/flutter_dev/flutter/] git ls-remote --get-url origin
[  +22 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter
[ +116 ms] executing: [/Users/long1eu/IDE/flutter_dev/flutter/] git rev-parse --abbrev-ref HEAD
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +12 ms] executing: sw_vers -productName
[  +28 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +27 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.1
[        ] executing: sw_vers -buildVersion
[  +27 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19B88
[  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +64 ms] executing: /Users/long1eu/Library/Android/sdk/platform-tools/adb devices -l
[  +12 ms] Exit code 0 from: /Users/long1eu/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +28 ms] executing: /Users/long1eu/IDE/flutter_dev/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +154 ms] executing: /usr/bin/xcode-select --print-path
[  +13 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +2 ms] executing: /usr/bin/xcodebuild -version
[ +211 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3
           Build version 11C29
[   +7 ms] /usr/bin/xcrun simctl list --json devices
[ +274 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +368 ms] Generating /Users/long1eu/IdeaProjects/upcode/web/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +207 ms] Launching lib/main.dart on Chrome in debug mode...
[  +44 ms] Updating assets
[ +502 ms] Syncing files to device Chrome...
[ +391 ms] <- reset
[  +22 ms] /Users/long1eu/IDE/flutter_dev/flutter/bin/cache/dart-sdk/bin/dart /Users/long1eu/IDE/flutter_dev/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/long1eu/IDE/flutter_dev/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc -Ddart.developer.causal_async_stacks=true --output-dill /var/folders/88/djsgz_ds0j3_87639cp05v980000gn/T/flutter_tool.OLeO8f/app.dill --packages /Users/long1eu/IdeaProjects/upcode/web/.packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --platform
file:///Users/long1eu/IDE/flutter_dev/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +20 ms] <- compile package:web/main.dart
[+24474 ms] Syncing files to device Chrome... (completed in 24,887ms, longer than expected)
[   +1 ms] Synced 21.0MB.
[        ] <- accept
[+1601 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[   +4 ms] For a more detailed help message, press "h". To quit, press "q".

```

**Comment by long1eu** [comment] 2019-12-19 17:22
@iapicca Can you please change the label? This As the title suggests this is not related to any plugins. This is a flutter web issue.

**Comment by jonahwilliams** [comment] 2019-12-19 21:37
@long1eu does the devtools console in the browser show any error messages when it stops working?

**Comment by long1eu** [comment] 2019-12-19 22:06
Yes. Here is what i found using the safari web inspector.

![Screenshot 2019-12-20 at 00 05 32](https://user-images.githubusercontent.com/9283414/71213573-89d73580-22bc-11ea-9712-4129774cca23.png)

**Comment by long1eu** [comment] 2019-12-19 22:10
The webpage can be found here: www.upcode.ro

**Comment by long1eu** [comment] 2019-12-19 22:21
Also on Android this is even more visible.

![ezgif-1-441848278e18](https://user-images.githubusercontent.com/9283414/71214740-92c90680-22be-11ea-9221-8b3f0b0360ab.gif)

**Comment by long1eu** [comment] 2019-12-21 08:22
@jonahwilliams @yjbanov is there a way to speed this up? Or at least point me in the right direction so I can make a quickfix?

**Comment by yjbanov** [comment] 2020-01-07 17:06
@long1eu The reason you are seeing continuous network activity is because you have "Disable cache" checked in the dev tools. I think that's unrelated to the Safari issue about canvas memory. We've seen this bug in Safari in the past and fixed it. It seems we somehow unfixed it again recently. We'll need to have a look at what's going on.

One thing you could try is open the canvas debugger in Safari's dev tools and see what part of the UI causes excessive generation of canvases.

BTW, it seems the www.upcode.ro link does not work any more.

**Comment by long1eu** [comment] 2020-01-08 06:58
Sorry I couldn't wait anymore so I moved to a different solution. Thanks

**Comment by ferhatb** [comment] 2020-03-31 22:46
Issue is resolved. There was a leak of canvas(s) that was fixed.

**Closed by ferhatb** 2020-03-31 22:46 UTC
Labels: e: web_html, engine, platform-web, severe: rendering

**Comment by ferhatb** [comment] 2020-04-01 21:47
Fix was in https://github.com/flutter/engine/pull/16721. Master/Dev , soon in beta
