### ISSUE TITLE
Allow `DropDownMenu` occupy available width like `isExpanded`

### ISSUE THREAD

**Issue by muchirajunior** [flutter/flutter#137514] opened 2023-10-30 05:02 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

create a drop down menu in a Sizedbox that occupy the available width or specific width. 

### Expected results

expect the drop menu to occupy available width like when you set isExpanded to true on drop down form filed button 

### Actual results

the drop down menu occupy static width

### Code sample

 Card(
            child: DropdownMenu(
              inputDecorationTheme: InputDecorationTheme(
                border: OutlineInputBorder(
                  gapPadding: 10,
                  borderSide: BorderSide.none,
                ),
              ),
              onSelected: (value) => setState(()=>documentType=value!),
              initialSelection: documentType,
              dropdownMenuEntries: SalesState.documentTypes.map((type) => DropdownMenuEntry(
                value: type,
                label: type.name.toString()
                ) ).toList(),
            ),
          ),

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

N/A

**Comment by abal1000x** [comment] 2023-10-30 07:57
I wonder too, how to make the width expand equal to the parent.

**Comment by abal1000x** [comment] 2023-10-30 08:31
NVM, solve it by adding property
```
            expandedInsets: EdgeInsets.zero,
```
in the main channel.

**Comment by dam-ease** [comment] 2023-10-30 10:43
Hi @muchirajunior. Thanks for filing this. Can you try out https://github.com/flutter/flutter/issues/137514#issuecomment-1784709841 to see if it works in your case? If not, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you

**Comment by muchirajunior** [comment] 2023-10-30 13:36
expandedInsets is not part of the arguments in dropdownmenu

**Comment by dam-ease** [comment] 2023-10-31 10:29
Hi @muchirajunior. If I got you right, you are trying to change the width of the `dropdownMenu`, which can be done by adding the width property. See code sample below to see if it suits your use case.
```dart
DropdownMenu<ColorLabel>(
                        width: 300,
                        initialSelection: ColorLabel.green,
                        controller: colorController,
                        label: const Text('Color'),
                        dropdownMenuEntries: colorEntries,
                        onSelected: (ColorLabel? color) {
                          setState(() {
                            selectedColor = color;
                          });
                        },
                      )
``` 
If this isn't the case you are describing, please provide more information on your use case for using `SizedBox`

**Comment by vnmiso** [comment] 2023-11-02 17:58
@muchirajunior means that there should be an option similar to `isExpanded` for `DropdownButton`, which makes the widget expand to match its parent's width. There doesn't seem to be such an option. With `width` you can only set a fixed size.

**Comment by muchirajunior** [comment] 2023-11-02 20:31
thanks @vnmiso for the illustration, this is what we need

**Comment by CodeDoctorDE** [comment] 2023-11-03 16:41
> expandedInsets is not part of the arguments in dropdownmenu  

You need to be in the beta channel

**Comment by abal1000x** [comment] 2023-11-05 09:22
> @muchirajunior means that there should be an option similar to `isExpanded` for `DropdownButton`, which makes the widget expand to match its parent's width. There doesn't seem to be such an option (where is `expandedInsets`?). With `width` you can only set a fixed size. I tried wrapping a `DropdownMenu` in `Expanded` in a `Row`, and put a `Text` after it; the only effect it had is to push the `Text` to the edge. See screenshot. ![image](https://user-images.githubusercontent.com/142838154/280086985-e82f1ab5-9a9b-4473-8878-d28b191fe0ec.png)

I already said in my comment. In 'MAIN CHANNEL' theres prop expandedInsets which is exactly the thing that you means.

@dam-ease
I don't think its a new feature. Its already implemented, just need to wait until it got to stable channel.

**Comment by dam-ease** [comment] 2023-11-06 08:46
Thanks for pointing this out @abal1000x @CodeDoctorDE. I seem to have missed that.
Hi @muchirajunior, I see this has been implemented on the latest `master` channel. You can check out the docs here https://master-api.flutter.dev/flutter/material/DropdownMenu-class.html. As regards when it will be available on the stable channel, you can read about it here as well: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release (and whole that page for more info).
Closing this since it has been implemented in the latest flutter versions.

**Closed by dam-ease** 2023-11-06 08:46 UTC
Labels: c: new feature, f: material design, c: proposal, team-design
