### ISSUE TITLE
FirebaseDatabase.instance.reference().child("Posts").orderByValue();    this query create proble can anyony help please

### ISSUE THREAD

**Issue by kuldeepsin** [flutter/flutter#44806] opened 2019-11-13 11:23 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment] 2019-11-14 08:53
Hi @kuldeepsin 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).

Opening an issue please try to provide
all or some of the information indicated in the template

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-14 08:53 UTC
