### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by LalitProvis** [flutter/flutter#139720] opened 2023-12-07 04:52 UTC
## Command
```
flutter --no-color run --machine --device-id=c0d5e8cb253d --start-paused --profile --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <57 characters>
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:136:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:55:22)
<asynchronous suspension>
#3      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:297:11)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.16.2, on Ubuntu 20.04.4 LTS 5.15.0-67-generic, locale en_IN)
    • Flutter version 3.16.2 on channel stable at /home/vivek/development/flutter
    ! The flutter binary is not on your path. Consider adding /home/vivek/development/flutter/bin to your path.
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/vivek/development/flutter. Consider adding /home/vivek/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (6 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/vivek/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/vivek/Android/Sdk
    • Java binary at: /snap/android-studio/128/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 76.3.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.68.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Mi A3 (mobile)  • c0d5e8cb253d • android-arm64  • Android 11 (API 30)
    • Linux (desktop) • linux        • linux-x64      • Ubuntu 20.04.4 LTS 5.15.0-67-generic
    • Chrome (web)    • chrome       • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

**Comment by danagbemava-nc** [comment] 2023-12-07 07:23
Closing this as a duplicate of https://github.com/flutter/flutter/issues/118400

**Closed by danagbemava-nc** 2023-12-07 07:23 UTC
Labels: in triage
