### ISSUE TITLE
 Mac_ios flutter_gallery_ios_sksl_warmup__transition_perf flaked on a codesigning error

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#99490] opened 2022-03-03 16:36 UTC
The run here https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_ios%20flutter_gallery_ios_sksl_warmup__transition_perf/1398/overview

Failed on the error `errSecInternalComponent`:
```
/usr/bin/codesign --force --sign AB7DFDD84BF4B572AA92CD5698B8C7648A810ECD --entitlements /Users/swarming/Library/Developer/Xcode/DerivedData/Runner-efincpmorimulycpvscolbitvrwg/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Flutter\ Gallery.app.xcent --timestamp\=none --generate-entitlement-der /opt/s/w/ir/x/w/recipe_cleanup/tmpf9i86t36/flutter\ sdk/dev/integration_tests/flutter_gallery/build/ios/Profile-iphoneos/Flutter\ Gallery.app
[flutter_gallery_ios_sksl_warmup__transition_perf] [STDOUT] run stdout:                /opt/s/w/ir/x/w/recipe_cleanup/tmpf9i86t36/flutter sdk/dev/integration_tests/flutter_gallery/build/ios/Profile-iphoneos/Flutter Gallery.app: errSecInternalComponent
[flutter_gallery_ios_sksl_warmup__transition_perf] [STDOUT] run stdout:                Command CodeSign failed with a nonzero exit code
```

Google searches tell me that this error occurs when there is a problem with either the keychain on the host, or a mismatch of profiles. P3 assuming this is a transient flake, but I'll bump up if it looks like it's happening consistently.

**Comment by zanderso** [comment] 2022-03-04 22:45
Another instance here from prod https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20cubic_bezier_perf_ios_sksl_warmup__timeline_summary/1640/overview

**Comment by keyonghan** [comment] 2022-03-23 19:52
This seems still happening: https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_ios%20flutter_gallery_ios_sksl_warmup__transition_perf/1557/overview (03/22)

> Google searches tell me that this error occurs when there is a problem with either the keychain on the host, or a mismatch of profiles. P3 assuming this is a transient flake, but I'll bump up if it looks like it's happening consistently.

Before running any test, device_doctor will check both [`keychainUnlock`](https://github.com/flutter/cocoon/blob/main/device_doctor/lib/src/ios_device.dart#L58) and [`deviceProvisioningProfile`](https://github.com/flutter/cocoon/blob/main/device_doctor/lib/src/ios_device.dart#L62) to make sure device is in a good state. Otherwise the bot will be quarantined.

Checking if any issues with health check.

**Comment by keyonghan** [comment] 2022-03-23 22:38
Two issues:

- The staging bots (where flakes happened) are not recognizing `idevice_id` (which is installed in /opt/homebrew/bin by default on M1 bots), but the config didn't catch the process exception. This may fail to catch keychain or provision issue. Created https://github.com/flutter/flutter/issues/100654 to track.
- The prod bots are all with intel, and the health check is working correctly. There is confidence that the keychain and provisioning are correct before running tests. If this is due to either case, I would expect the bot consistently failing tests. Based on [history](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-28) on mac28, we can see the issue is not consistent for test `cubic_bezier_perf_ios_sksl_warmup__timeline_summary`. Sounds something else. /cc @zanderso

**Comment by keyonghan** [comment] 2022-03-25 16:48
All these flakes happened when tests execution > 20min, it is possible the keychain unlock timed out.

We should extend the timeout to 30min (the execution timeout threshold). This can be set when creating the keychain by:
```
security set-keychain-settings -l -u -t 1800 login.keychain
```

**Comment by keyonghan** [comment] 2022-03-25 16:49
Promoting to P1 per https://github.com/flutter/flutter/issues/100645.

**Comment by keyonghan** [comment] 2022-03-28 21:01
All bots are updated with new timeout 1800s, and `idevice_id` change also landed.
Will keep monitoring before close.

**Comment by godofredoc** [comment] 2022-03-31 22:07
Monitoring to see if the keychain timeout to 30minutes fixes the problem.

**Comment by keyonghan** [comment] 2022-04-05 17:41
No `errSecInternalComponent` flake hit in recent 50 runs on both `flutter_gallery_ios_sksl_warmup__transition_perf` and `cubic_bezier_perf_ios_sksl_warmup__timeline_summary`. But both hit timeout on `Waiting for observatory url`. 

Filed https://github.com/flutter/flutter/issues/101369 to track.

**Closed by keyonghan** 2022-04-05 17:41 UTC
Labels: team: flakes, team: infra, passed secondary triage, P1, severe: flake
