### ISSUE TITLE
[image_picker] white Sceen on open ImageSource.gallery on iOS

### ISSUE THREAD

**Issue by Rayv1** [flutter/flutter#70786] opened 2020-11-18 20:12 UTC
HI,

iam using the Image_picker Plugin, which is working great on Android. A few days ago i started working iOS and added the following to my info.plist to get the image_picker plugin working:
```
<key>NSCameraUsageDescription</key>
<string>Camera permission is required for barcode scanning and profile image.</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>Photo Library is required for picking profile image and adding recipe images</string>
```
my Code for picking Image:
```
    final picker = ImagePicker();
    final pickedFile = await picker.getImage(
        source: ImageSource.gallery,);
```
when calling the function, sometimes nothing happens and sometimes it appears just a "non-exitable" white Screen. Even if i do a hot restart / hot reload, my app restarts, but the Screen not disappears. I have to fully close it, dot get rid of it. The white Screen seems like just a layer, because when i click on the same location where my button for calling the function is, i got the following 
```
+4435 ms] flutter: <-----↓↓↓↓↓↓↓↓↓↓-----error-----↓↓↓↓↓↓↓↓↓↓----->
[        ] flutter: PlatformException(multiple_request, Cancelled by a second request, null, null)
[        ] flutter: <-----↑↑↑↑↑↑↑↑↑↑-----error-----↑↑↑↑↑↑↑↑↑↑----->
[        ] flutter: <-----↓↓↓↓↓↓↓↓↓↓-----trace-----↓↓↓↓↓↓↓↓↓↓----->
[        ] flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
[   +2 ms] flutter: #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
[   +1 ms] flutter: <asynchronous suspension>
[   +2 ms] flutter: #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[        ] flutter: #3      MethodChannelImagePicker.pickImagePath (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
[        ] flutter: #4      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:25)
[   +2 ms] flutter: #5      ImagePicker.getImage (package:image_picker/image_picker.dart:106:21)
[   +2 ms] flutter: #6      UserService.selectImage (package:fitasy/core/services/user_service.dart:76:37)
[        ] flutter: #7      UserService.uploadPicture (package:fitasy/core/services/user_service.dart:449:11)
[        ] flutter: #8      UserService.setProfileImage (package:fitasy/core/services/user_service.dart:323:19)
[   +1 ms] flutter: #9      UserProfileModel.setProfileImage (package:fitasy/modules/prefs/model/userProfileModel.dart:44:23)
[  +47 ms] flutter: #10     SettingsProfileContainer.build.<anonymous closure>.<anonymous closure> (package:fitasy/modules/prefs/ui/user_prefs.dart:115:40)
[        ] flutter: #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[        ] flutter: #12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
[        ] flutter: #13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
[        ] flutter: #14     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
[        ] flutter: #15     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
[        ] flutter: #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
[   +1 ms] flutter: #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[   +2 ms] flutter: #18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] flutter: #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[        ] flutter: #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] flutter: #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] flutter: #22     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ] flutter: #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] flutter: #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] flutter: #25     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] flutter: #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[        ] flutter:
[        ] flutter: <-----↑↑↑↑↑↑↑↑↑↑-----trace-----↑↑↑↑↑↑↑↑↑↑----->
[   +1 ms] flutter:
```
so it seems its still recognize my input.

Platform:
- iOS 14 (18A372)
- iPhone 11 Pro (A2160)

Flutter doctor:
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.5 19F96 darwin-x64, locale en-DE)
    • Flutter version 1.22.4 at /Users/ray/dev/flutter
    • Framework revision 1aafb3a8b9 (5 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ray/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (1 available)            
    • iPhone 11 Pro (mobile) • D8849935-6AA4-47B3-9869-313E33998901 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```

Searching for Help! 
Cheers,
Ray

**Comment by alexandreducatti** [comment] 2020-11-18 20:25
Same issue here

**Comment by TahaTesser** [comment] 2020-11-19 13:30
Hi @Rayv1 @alexandreducatti 
Unable to reproduce the issue on the latest `Channel stable, 1.22.4` on a physical device
When using gallery as source ` final pickedFile = await picker.getImage(source: ImageSource.gallery);` 


Preview

<details> 
<summary>code sample</summary> 

```dart

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;
  final picker = ImagePicker();

  Future getImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.gallery);

    setState(() {
      if (pickedFile != null) {
        _image = File(pickedFile.path);
      } else {
        print('No image selected.');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null ? Text('No image selected.') : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: Icon(Icons.photo),
      ),
    );
  }
}

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile)                • 00008020-000255113EE8402E
      • ios • iOS 14.2
    • iPhone SE (2nd generation) (mobile) • F0FD09FB-9ABB-402D-9712-7AC7278ED742
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

! Doctor found issues in 1 category.
```

</details>

No white screen on the simulator but if you pick images multiple it will crash on the simulator. https://github.com/flutter/flutter/issues/68283


@Rayv1  @alexandreducatti 
Please provide reproducible steps and device.
Thank you

**Comment by Rayv1** [comment] 2020-11-19 18:36
@TahaTesser 
On a physical device its working, but not the simulator. I tried your Example in a freshly created Flutter app, but same white screen of death appears and sometimes its exiting immediately. Another thing i have noticed is that sometimes it immediately returns: "No image selected." This message only appears, when the white screen is not appearing.

**Comment by TahaTesser** [comment] 2020-11-20 07:26
Hi @Rayv1 
Using offical [example](https://pub.dev/packages/image_picker/example) on the latest `image_picker: ^0.6.7+14` on iOS 14.2 simulator on Xcode 12.2 has no issues

### Preview
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/99771810-bda38680-2b2f-11eb-9c0f-8ff5f109364d.gif)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (7 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64 • Android 10
      (API 29)
    • iPhone 12 (mobile) • 6EDF1AF0-1537-4E53-BE85-928E0CD9785A • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```

</details>


Can you please share the recording the official using official example on your smiluator
Thank you

**Comment by pedromassangocode** [comment] 2020-12-11 09:53
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-11 09:53 UTC
Labels: in triage, waiting for customer response
