### ISSUE TITLE
Flutter get package rxDart 0.24.0 fails

### ISSUE THREAD

**Issue by DavidRuland** [flutter/flutter#67115] opened 2020-10-02 07:34 UTC
Hi, 
I am trying to update to rxDart 0.24.0 with flutter get command and update my dependencies to rxDart 0.24.0. It fails to download and I got error Flutter public service fails to connect. I have tried to remove rxDart 0.24.0 dependencies and it works with Flutter get package. I need rxDart 0.24.0 for audio assets and Google maps. Part of my pubspec.yaml file are below. Do I need to update my dependencies to get rxDart 0.24.0 to work? 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any
  intl: ^0.16.1
  rxDart: ^0.24.0
  percent_indicator: "^1.0.13"
  scoped_model: ^1.0.1
  assets_audio_player: ^1.0.1
  screen: ^0.0.5
  flutter_launcher_icons: "^0.7.0"
  shared_preferences: ^0.5.3+1
  persistent_bottom_nav_bar: any
  custom_navigator: ^0.3.0
  flutter_svg: ^0.18.0
  provider: ^4.3.1
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  google_maps_flutter: ^0.0.3
  flutter_google_places: ^0.1.4
  location: ^1.4.1

**Comment by leanhtuan1994** [comment] 2020-10-02 08:25
Hi, try to rxdart: ^0.24.1

**Comment by TahaTesser** [comment] 2020-10-02 09:56
Hi @DavidRuland 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/ReactiveX/rxdart/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-02 09:56 UTC
