### ISSUE TITLE
Visual Studio is missing necessary components.

### ISSUE THREAD

**Issue by jimbo-jones1313** [flutter/flutter#90117] opened 2021-09-15 10:56 UTC
from Flutter Doctor:

> Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.11.31702.278
>     • Windows 10 SDK version 10.0.20348.0
>     X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
>         MSVC v142 - VS 2019 C++ x64/x86 build tools
>          - If there are multiple build tool versions available, install the latest
>         C++ CMake tools for Windows
>         Windows 10 SDK

"Windows 10 SDK" does not seem to be an option in the list in "Visual Studio Installer."
MSVC is the "latest."
CMake is there.
I started adding SDK versions, hoping one of them might work; none do.

![image](https://user-images.githubusercontent.com/63853386/133421210-25853a10-90ff-474d-8dc7-aaef82691359.png)

**Comment by stuartmorgan** [comment] 2021-09-15 19:09
> "Windows 10 SDK" does not seem to be an option in the list in "Visual Studio Installer."

It's the second blue checkbox item in your screenshot.

Just to be sure, you have performed the installation and restarted since taking that screenshot? Because it's showing that the selection you've show will install 1.32 GB of data, which presumably means that most of it was not installed when you captured that image.

If so, and you're still getting the same message from `flutter doctor`, please run the command listed [in this comment](https://github.com/microsoft/vswhere/issues/199#issuecomment-531875699) and attach the output here.

**Comment by jimbo-jones1313** [comment] 2021-09-16 07:24
Those things were all installed already; I've just been going through, trying different variants on the Windows 10 SDK, hoping Flutter will accept one of them; right now I have 20348 and 19041 installed.

I installed the VSSetup module, but it won't work because I have to run Import-Module VSSetup, but my system won't allow me to run scripts...
So: no input.

I even installed Linux on a VM to try to bypass all this, but installing Android Studio keeps crashing the VM.

**Comment by darshankawar** [comment] 2021-09-16 10:33
@jimbo-jones1313 
The output seems to correctly indicate that you haven't installed all the required components. Are you installing the correct SDK version that `flutter doctor` is indicating ?

**Comment by jimbo-jones1313** [comment] 2021-09-16 10:35
Flutter is indicating "Windows 10 SDK."
I have Win10SDK_10.0.19041 and Win10SDK_10.0.20348 installed, and no option for "Windows 10 SDK."

**Comment by darshankawar** [comment] 2021-09-16 12:46
The screenshot seem to show the `Windows 10 SDK` option:

<img width="178" alt="Screenshot 2021-09-16 at 6 15 34 PM" src="https://user-images.githubusercontent.com/67046386/133614482-6de40777-ea05-4c9e-88a9-c67b9f209f24.png">

**Comment by jimbo-jones1313** [comment] 2021-09-16 12:55
Yes, it does: Win10SDK_10.0.19041 was already installed (which Flutter doctor acknowledges).

As noted: I have Win10SDK_10.0.19041 and Win10SDK_10.0.20348 installed, but no option for "Windows 10 SDK."

**Comment by stuartmorgan** [comment] 2021-09-16 13:59
Based on your output, the problem is that you don't have `Microsoft.VisualStudio.Workload.NativeDesktop`. `flutter doctor` is specifically looking for that workload. It should be one of the large boxes on the left.

**Comment by stuartmorgan** [comment] 2021-09-16 14:01
> Flutter is indicating "Windows 10 SDK."
> I have Win10SDK_10.0.19041 and Win10SDK_10.0.20348 installed, and no option for "Windows 10 SDK."

Requiring a specific version of the SDK was a significant pain point, so we rewrote the check to allow any sufficiently new version. That's why it doesn't give a specific version.

**Comment by jimbo-jones1313** [comment] 2021-09-16 14:16
Installing stuff from ### Microsoft.VisualStudio.Workload.NativeDesktop.
Will let you know.

**Comment by darshankawar** [comment] 2021-09-17 05:10
Closing this as resolved based on above comment.

**Closed by darshankawar** 2021-09-17 05:10 UTC
Labels: in triage
