### ISSUE TITLE
Impeller shader compilation fails on startup with unused uniform

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#155805] opened 2024-09-27 05:20 UTC
### Steps to reproduce

Create a Flutter app with a fragment shader. Have the shader declare a uniform that isn't used. Works fine under Skia, but fails under Impeller.

### Expected results

I expect the same behavior as Skia under Impeller.

### Actual results

Under Impeller, on startup the shader fails to compile. Interestingly, if I start with a shader source that includes usage of all the uniforms, and then delete code from the shader at run time in development mode, the shader compilation succeeds.

### Code sample

<details open><summary>Code sample</summary>

`shaders/simple_shader.frag`:
```glsl
#version 460 core

precision mediump float;

#include <flutter/runtime_effect.glsl>

uniform vec2 uSize;
uniform float uTime;

out vec4 fragColor;

void main()
{
    fragColor = vec4(0.2, 0.4, 0.6,1.0);
}
```

`lib/main.dart`:
```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_shaders/flutter_shaders.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(colorSchemeSeed: Colors.deepPurple),
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Shader Gallery'),
      ),
      body: SimpleShader(),
    );
  }
}

class ShaderPainter extends CustomPainter {
  const ShaderPainter(this.shader, this.time);
  final ui.FragmentShader shader;
  final double time;

  @override
  void paint(ui.Canvas canvas, ui.Size size) {
    shader.setFloatUniforms((uniforms) {
      uniforms.setSize(size);
      uniforms.setFloat(time);
    });
    canvas.drawRect(
        Offset.zero & size,
        Paint()
          ..style = ui.PaintingStyle.fill
          ..shader = shader);
  }

  @override
  bool shouldRepaint(covariant ShaderPainter oldDelegate) => true;
}

class SimpleShader extends StatefulWidget {
  const SimpleShader({super.key});

  @override
  State<SimpleShader> createState() => _SimpleShaderState();
}

class _SimpleShaderState extends State<SimpleShader>
    with SingleTickerProviderStateMixin {
  late Ticker _ticker;
  double _tick = 0;

  @override
  void initState() {
    super.initState();
    _ticker = createTicker((elapsed) {
      setState(() {
        _tick += 0.025;
      });
    });
    _ticker.start();
  }

  @override
  void dispose() {
    _ticker.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ShaderBuilder(
      (context, shader, child) => CustomPaint(
        painter: ShaderPainter(shader, _tick),
        child: child,
      ),
      assetKey: 'shaders/simple_shader.frag',
      child: SizedBox.expand(),
    );
  }
}
```

`pubspec.yaml`:
```yaml
name: shadertoy
description: "Playing with Shaders"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  shaders:
    - shaders/simple_shader.frag
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
════════ Exception caught by rendering library ═════════════════════════════════
RangeError (index): Index out of range: no indices are valid: 0
The relevant error-causing widget was:
    CustomPaint CustomPaint:file:///Users/brettmorgan/Documents/flutter-projects/shadertoy/lib/main.dart:97:35
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#b61ac relayoutBoundary=up1
RenderObject: RenderCustomPaint#b61ac relayoutBoundary=up1
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel master, 3.26.0-1.0.pre.246, on macOS 14.6.1 23G93 darwin-arm64, locale en)
    • Flutter version 3.26.0-1.0.pre.246 on channel master at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 7bb9352911 (4 hours ago), 2024-09-26 21:23:28 -0400
    • Engine revision e57b440ec4
    • Dart version 3.6.0 (build 3.6.0-279.0.dev)
    • DevTools version 2.40.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Community Edition (version 2024.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17890.8

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 129.0.6668.60

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment] 2024-09-27 05:47
See https://github.com/flutter/flutter/issues/116900

**Comment by domesticmouse** [comment] 2024-09-27 20:46
> See https://github.com/flutter/flutter/issues/116900

Should I close as duplicate?

**Comment by jonahwilliams** [comment] 2024-09-27 20:49
Yeah, good call. CLosing as duplicate of https://github.com/flutter/flutter/issues/116900

**Closed by jonahwilliams** 2024-09-27 20:49 UTC
Labels: e: impeller
