### ISSUE TITLE
Changing a SliverList's children's keys each build confuses SliverList

### ISSUE THREAD

**Issue by susch19** [flutter/flutter#10453] opened 2017-06-02 16:37 UTC
This bug appears always, when the ui refreshes and the listview is not scrolled to top, even in the Flutter Gallery App. 

## Steps to Reproduce

[VIDEO](https://www.youtube.com/watch?v=LqD_W6y3Se0)

1. Start the Flutter Gallery App and go into the "Leave-behind list items" demo
2. Scroll to the bottom and delete an item
3. Reset the list (setState won't be called, so you have to delete a second item or undo the deletion)
4. Scroll to top and you won't be able to see all items, even when they are in the list (object) and should be shown

## Flutter Doctor
```
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale de-DE, channel master)
    • Flutter at E:\Flutter\flutter
    • Framework revision e3bab988ce (5 hours ago), 2017-06-02 13:15:49 +0200
    • Engine revision 75c74dc463
    • Tools Dart version 1.24.0-dev.3.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at E:\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = E:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.3
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[√] Connected devices
    • Z2 Pro • 69f89783 • android-arm • Android 6.0.1 (API 23)
```

**Comment by eseidelGoogle** [comment] 2017-06-02 16:54
This sounds very much like https://github.com/flutter/flutter/issues/9665 and possibly https://github.com/flutter/flutter/issues/8090

**Comment by susch19** [comment] 2017-06-02 17:02
#9665 sounds a bit like that, sadly i can't test it on IOS. Something to point out, the whole list blinks on setState, when this bug happends
#8090 seems to be a different issue, because my issue won't be caused when fast scrolled and only, if you call setState at the bottom of the ListView and a change was made previously

**Comment by susch19** [comment] 2017-06-10 15:30
I have tested this issue a little bit more and here is a little workaround for the Gallery App:
```dart
List<LeaveBehindItem> testList=
    new List<LeaveBehindItem>.generate(15, (int index) {
  return new LeaveBehindItem(
      index: index,
      name: 'Item $index Sender',
      subject: 'Subject: $index',
      body: "[$index] first line of the message's body...");
});

void initListItems() {
  leaveBehindItems.clear();
  leaveBehindItems.insertAll(0, testList);
}
```
So what i observed was, creating a new list or modifying "testList" in my example will trigger the wrong behavior, but as long, as you don't change "testList" it will work as expected. 
I tried to implement a similar workaround in my app, but that's not working, because i don't have a non changing list of items.

**Comment by Hixie** [comment] 2017-06-22 05:41
Once you've passed a list to a ListView, you cannot change it again. If you want to change the children, you have to create a new list and pass that in.

I'm not sure how or where to document that.

**Comment by susch19** [comment] 2017-06-22 08:39
@Hixie 
For my understanding i already do that, maybe im missing something, so here is the code, that leads to this misbehavior (on dismiss):
``` dart
Widget buildBody(BuildContext context) {
    User.currentList.shoppingItems?.sort((a, b) => a.id.compareTo(b.id));
    User.currentList.shoppingItems?.sort(
        (a, b) => a.crossedOut.toString().compareTo(b.crossedOut.toString()));

    var mainList = User.currentList.shoppingItems.map((x) {
      var lt = new ListTile(
        title: new Row(children: [
          new Expanded(
              child: new Text(
            x.name,
            maxLines: 2,
            softWrap: true,
            style: new TextStyle(
                decoration: x.crossedOut
                    ? TextDecoration.lineThrough
                    : TextDecoration.none),
          )),
        ]),
        leading: new PopupMenuButton<String>(
          child: new Row(children: [
            new Text(x.amount.toString() + "x"),
            const Icon(Icons.expand_more, size: 16.0),
            new SizedBox(height: 38.0), //for larger clickable size (2 Lines)
          ]),
          initialValue: x.amount.toString(),
          onSelected: (y) => shoppingItemChange(x, int.parse(y) - x.amount),
          itemBuilder: buildChangeMenuItems,
        ),
        onTap: () => crossOutMainListItem(x),
      );

      return new Dismissible(
        key: new ObjectKey(lt),
        child: lt,
        onDismissed: (DismissDirection d) => handleDismissMain(d, x),
        direction: DismissDirection.startToEnd,
        background: new Container(
            decoration:
                new BoxDecoration(color: Theme.of(context).primaryColor),
            child: new ListTile(
                leading: new Icon(Icons.delete,
                    color: Theme.of(context).accentIconTheme.color,
                    size: 36.0))),
      );
    }).toList(growable: true);

    var lv = new ListView.builder(
      itemBuilder: (c, i) => mainList[i],
      itemCount: mainList.length,
      physics: const AlwaysScrollableScrollPhysics(),
    );

    return new RefreshIndicator(
      child: lv,
      onRefresh: _handleMainListRefresh,
    );
  }
```

here is my dismiss method (reduced to the important part, rest is server communication):
``` dart
 void handleDismissMain(DismissDirection dir, ShoppingItem s) {
    var list = User.currentList;
    setState(() => list.shoppingItems.remove(s));
  }
```

**Comment by Hixie** [comment] 2017-06-22 15:48
Weird. Does the same thing happen with ListView (rather than ListView.builder)?

**Comment by Hixie** [comment] 2017-06-22 15:53
By the way, the code above would be more efficient if you didn't create the list each time, but just provided a builder than actually built the children on the fly. If you create the list in advance like in the code above, you might as well use a regular ListView constructor.

**Comment by susch19** [comment] 2017-06-22 16:29
ListView doesn't work either, i have used it before i switched to ListView.builder and i tried it again, same result. 
The code above looked way different before i encountered the bug, but i tried to find a workaround. When i first started to modify this code, i had a list of widgets, where i added and deleted the items, so exactly the thing, you shouldn't do. 

But when you don't find another bug in my code, it seems like it's not just some documentation changes

**Comment by Hixie** [comment] 2017-06-22 16:34
Would you mind creating a one-file flutter project that shows this problem? (i.e. `flutter create repro`, then edit the `main.dart` file to contain whatever is needed to reproduce it)

**Comment by susch19** [comment] 2017-06-22 16:40
I will try to reproduce this issue in one file.
I tried something different (again) and with a CustomScrollView it seems to work as expected, so this is the changed and now working code:
``` dart
    var lv = new CustomScrollView(
      slivers: [
        new SliverFixedExtentList(
            delegate: new SliverChildBuilderDelegate(
                (BuildContext context, int index) {
              return new Container(
                alignment: FractionalOffset.center,
                child: mainList[index],
              );
            }, childCount: mainList.length),
            itemExtent: 50.0)
      ],
      physics: const AlwaysScrollableScrollPhysics(),
    );
```

**Comment by Hixie** [comment] 2017-06-22 18:04
So the problem is basically just the way you set the keys -- you are making each row have a unique key, which changes each time you build the list. (It's unique because it's equal to an object, the ListTile widget, that you just created that very build.) To the underlying code it's as if you were generating an entirely new list each time. For some reason, the code can't handle that. We'll have to fix that.

But in the meantime, doing that is clearly wrong. It's why, for instance, when you dismiss two rows at once, the moment you remove the first item, the other item's dismissal state is lost -- from the framework's perspective, each time you build all the rows change, and so the one that was dismissing is gone and replaced by a new one that isn't.

The fix is simple, change `ObjectKey(lt)` to `ValueKey(x)`.

**Comment by susch19** [comment] 2017-06-22 18:24
Okay that's good to know and that really fixed my problem, thank you very much.
The only question left for me is, why could the CustomScrollView handle that?

**Comment by Hixie** [comment] 2017-06-22 19:17
Yeah I'm not really sure what's going on. The CustomScrollView+SliverList uses the same code as the ListView (ListView really is just a wrapper around the other two). There's definitely a bug here.

**Comment by Hixie** [comment] 2017-06-22 22:09
I think what's going on is that when the key is a UniqueKey, when we rebuild, we add the child but don't remove it straight away, and then we end up deciding that we have too many children so we remove the earlier ones but we don't update the scrolling window or something. Definitely a bug with how SliverMultiBoxAdaptorElement interacts with the underlying render objects.

**Comment by Hixie** [comment] 2017-06-22 22:19
Weird, somehow we end up removing these nodes in the collectGarbage() step.

**Comment by Hixie** [comment] 2017-12-13 00:18
This is not on our short-term priority list. Moving to next milestone.

**Comment by zoechi** [comment] 2019-01-02 10:40
I tried to reproduce with https://github.com/susch19/Flutter-ListView-Bug and couldn't see a bug 
but I'm not sure what the wrong behavior actually looked like.

**Comment by susch19** [comment] 2019-01-02 10:53
In steps to reproduce i linked a video showing the bug with the flutter gallery. 
Maybe it was fixed in the meantime and this issue can be closed. I will look into this in the next days

**Comment by zoechi** [comment] 2019-01-02 13:00
@susch19 the video is quite fast and I don't know what exactly to look for.
Would be great if you could check.

**Comment by zoechi** [comment] 2019-01-28 09:40
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-28 09:40 UTC
Labels: f: scrolling, framework, waiting for customer response
