### ISSUE TITLE
A KeyRepeatEvent is dispatched

### ISSUE THREAD

**Issue by djildo** [flutter/flutter#111393] opened 2022-09-12 14:17 UTC
Another exception was thrown: A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report    
this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: 
KeyRepeatEvent#66f84(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102",  
keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 49:54:41.080787)
Unable to parse JSON message:
The document is empty.

**Comment by exaby73** [comment] 2022-09-12 20:49
Hello @djildo. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`

**Comment by exaby73** [comment] 2022-09-13 11:14
Marking as duplicate of https://github.com/flutter/flutter/issues/108646

**Closed by exaby73** 2022-09-13 11:14 UTC
Labels: waiting for customer response, in triage
