### ISSUE TITLE
[Android] Feature Request: Scroll Capture

### ISSUE THREAD

**Issue by daniloapr** [flutter/flutter#95639] opened 2021-12-21 19:05 UTC
## Use case

The Android OS has a very interesting "Scroll Capture", that allows the user to take screenshots from a whole list, scrolling it, not being restrict in what fits on the screen. However, is doesn't work with Flutter apps, maybe because the `RecyclerView` is missing and the Android OS doesn't recognize the Flutter's `ListView` as a list.

Here are some video with examples in an Android Native (Kotlin) app and a Flutter app running in a Samsung S10 with Android 11.

**Android Native (Kotlin) app** - Working

https://user-images.githubusercontent.com/31525418/146983773-20fbafda-38fb-499b-a392-1bf2850541c0.mp4

**Flutter app** - Not working

https://user-images.githubusercontent.com/31525418/146984122-d43ab676-4243-4ff1-bc1f-69d37eea2546.mp4

## Proposal

Make the "Scroll Capture" work on Flutter apps running in Android OS.

**Comment by nt4f04uNd** [comment] 2021-12-21 19:42
A duplicate of https://github.com/flutter/flutter/issues/85978

**Closed by nt4f04uNd** 2021-12-21 19:42 UTC
