### ISSUE TITLE
Dependency conflict won't resolve

### ISSUE THREAD

**Issue by nathan-kane** [flutter/flutter#83558] opened 2021-05-28 13:11 UTC
## Steps to Reproduce

Here is the contents of my pubspec.yaml file:
name: tonnah

description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.4+1
  firebase_auth_web: ^0.3.2+3
  cloud_firestore: ^0.14.3+1
  modal_progress_hud: ^0.1.3
  uuid: ^2.2.2
  provider: ^4.3.2+3
  flutter_launcher_icons: ^0.8.1
  flutter_keyboard_visibility: ^4.0.2
  firebase_messaging: ^7.0.3
  #table_calendar: ^3.0.0
  intl: ^0.16.1
  #intl: ^0.17.0

dev_dependencies:
  test: ^1.17.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/Appbar_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/tonnah_logo.png"

## Logs

<details>
<summary>
I am having problems when I try to reconcile the dependencies  in the dev_dependencies: section.

Here is the output of "pub get" command inside Android Studio

C:\src\flutter\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in tonnah...                          
Because every version of flutter_test from sdk depends on test_api 0.3.0 and test >=1.17.0 depends on test_api 0.4.0, flutter_test from sdk is incompatible with test >=1.17.0.
So, because tonnah depends on both test ^1.17.5 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because tonnah depends on both test ^1.17.5 and flutter_test any from sdk, version solving failed.)
Process finished with exit code 1</summary>

```
```

C:\src\flutter\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel master, 2.3.0-17.0.pre.34, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
    • Flutter version 2.3.0-17.0.pre.34 at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision de23eb7b29 (4 days ago), 2021-05-24 15:34:02 -0400
    • Engine revision b1385c0df1
    • Dart version 2.14.0 (build 2.14.0-145.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/nkane/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/nkane/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\nkane\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!
Process finished with exit code 0
```

</details>

**Comment by stuartmorgan** [comment] 2021-05-28 13:43
You'll need to use a version of `test` that is compatible with the Flutter SDK version you are using.

Closing as this is not a bug; not every package is compatible with every version of Flutter.

**Closed by stuartmorgan** 2021-05-28 13:43 UTC

**Comment by nathan-kane** [comment] 2021-05-28 14:27
The version of test should work. Here is output of running flutter --version
Flutter 2.3.0-17.0.pre.34 • channel master • https://github.com/flutter/flutter.git
Framework • revision de23eb7b29 (4 days ago) • 2021-05-24 15:34:02 -0400
Engine • revision b1385c0df1
Tools • Dart 2.14.0 (build 2.14.0-145.0.dev)

So, which version of test should I be using?

**Comment by stuartmorgan** [comment] 2021-05-28 15:16
Since you're on master this is a duplicate of https://github.com/flutter/flutter/issues/81294 and you can just get a slightly new version of master.

**Comment by nathan-kane** [comment] 2021-05-28 16:02
Thanks for the response. When I change the .yaml file to
dev_dependencies:
  #test: ^1.17.5
  test_package: any
  flutter_test:
    sdk: flutter

I get this response:
C:\src\flutter\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in tonnah...                          
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 9 in 64 seconds...
Because tonnah depends on test_package any which doesn't exist (could not find package test_package at https://pub.dartlang.org), version solving failed.
pub get failed (server unavailable) -- attempting retry 10 in 64 seconds...


Where do I find test_package and do I even need dev_dependencies in the .yaml? If I remove that section from the .yaml this error goes away.

**Comment by stuartmorgan** [comment] 2021-05-28 16:28
> Thanks for the response. When I change the .yaml file to
> dev_dependencies:
> #test: ^1.17.5
> test_package: any

I'm not sure what you are trying to accomplish here. All you need to do, as I said, is use a newer version of master.



> Where do I find test_package

I have no idea what this is, it why you are trying to use it, so I can't help you with that.

**Comment by stuartmorgan** [comment] 2021-05-28 16:41
https://flutter.dev/docs/development/tools/sdk/upgrading

If you need further assistance, please see flutter.dev/community for resources. The issue tracker is for Flutter bug reports and issue requests.
