### ISSUE TITLE
I can't install package on Flutter project.

### ISSUE THREAD

**Issue by AliHamzaRao** [flutter/flutter#60093] opened 2020-06-23 13:35 UTC
I am trying to install english_words packages in my new flutter project but it keeps saying "**a varialble constraint must be a string**"
![Error](https://user-images.githubusercontent.com/51596406/85410188-3651e700-b580-11ea-812e-c009700ecdee.PNG)

**Comment by VarunSAthreya** [comment] 2020-06-23 19:54
Try keeping the package name and version constraint in the same line.

**Comment by AliHamzaRao** [comment] 2020-06-23 19:58
I've tried it but still doesn't work and even without package installation
of i push save command on my keyboard it still delivers same error

**Comment by iapicca** [comment] 2020-06-24 07:25
Hi @AliHamzaRao 
From what I can see, the issue is related to the 3rd party plugin [english_words](https://pub.dev/packages/english_words) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/filiph/english_words).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-24 07:25 UTC
