### ISSUE TITLE
[iOS Keyboard] All flutter iOS applications crashes when pressing `ESC` key with an external keyboard (cmd+.)

### ISSUE THREAD

**Issue by dupuchba** [flutter/flutter#106407] opened 2022-06-22 12:50 UTC
Reproduce this bug : 
- 1/ download or create any flutter app, i.e. : Google Ad on iOS or an iPad with an external keyboard
- 2/ press cmd+. (esc) on your external keyboard

Error : 
```
*** Assertion failure in uint64_t (anonymous namespace)::GetLogicalKeyForEvent(FlutterUIPressProxy *, uint64_t)(), FlutterEmbedderKeyResponder.mm:173
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unexpected long key label: |UIKeyInputEscape|.'
```

Hypothesis from `src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEmbedderKeyResponder.mm`
For some reason the `ESC` key is not detected as a control character and goes through the NSCAssert with a `keyLabelLength` >=2 throwing an exception.
For some undocumented reason `IsControlCharacter` is false when `length > 1`
I don't have a fix because I could not run my custom engine on my device, I ran into multiple issues for the last 1,5 days...
I cannot run the tests either, I had this error
```
#include "flutter/testing/test_gl_surface.h"
          ^--------------------------------
It is not in any dependency of
  //flutter/shell/common:shell_unittests
The include file is in the target(s):
  //flutter/testing:opengl
which should somehow be reachable.
```

```
static uint64_t GetLogicalKeyForEvent(FlutterUIPressProxy* press, uint64_t physicalKey)
    API_AVAILABLE(ios(13.4)) {
  // Look to see if the keyCode can be mapped from keycode.
  auto fromKeyCode = keyCodeToLogicalKey.find(press.key.keyCode);
  if (fromKeyCode != keyCodeToLogicalKey.end()) {
    return fromKeyCode->second;
  }
  const char* characters =
      getEventCharacters(press.key.charactersIgnoringModifiers, press.key.keyCode);
  NSString* keyLabel =
      characters == nullptr ? nil : [[[NSString alloc] initWithUTF8String:characters] autorelease];
  NSUInteger keyLabelLength = [keyLabel length];
  // If this key is printable, generate the logical key from its Unicode
  // value. Control keys such as ESC, CTRL, and SHIFT are not printable. HOME,
  // DEL, arrow keys, and function keys are considered modifier function keys,
  // which generate invalid Unicode scalar values.
  if (keyLabelLength != 0 && !IsControlCharacter(keyLabelLength, keyLabel) &&
      !IsUnprintableKey(keyLabelLength, keyLabel)) {
    // Given that charactersIgnoringModifiers can contain a string of arbitrary
    // length, limit to a maximum of two Unicode scalar values. It is unlikely
    // that a keyboard would produce a code point bigger than 32 bits, but it is
    // still worth defending against this case.
    NSCAssert((keyLabelLength < 2), @"Unexpected long key label: |%@|.", keyLabel);

    uint64_t codeUnit = (uint64_t)[keyLabel characterAtIndex:0];
    if (keyLabelLength == 2) {
      uint64_t secondCode = (uint64_t)[keyLabel characterAtIndex:1];
      codeUnit = (codeUnit << 16) | secondCode;
    }
    return KeyOfPlane(toLower(codeUnit), kUnicodePlane);
  }

  // This is a non-printable key that is unrecognized, so a new code is minted
  // with the autogenerated bit set.
  return KeyOfPlane(press.key.keyCode, kIosPlane);
}
```

The inconvenience is quite problematic for us as we are trying to port a text editor whose userbase is reliant on cmd+. as a shortcut

**Comment by huycozy** [comment] 2022-06-23 04:51
Hi @dupuchba, thanks for filing the issue. 
This issue is reproducible on the latest `stable` and `master` channels.

On my side, the crash happened with just `Command` + `.` without pressing `Esc` key anymore.
I provide full stack trace below:

<details>
<summary>Stack trace</summary>

```bash
An Observatory debugger and profiler on iPhone is available at: http://127.0.0.1:50515/XFU4t2hLnY4=/
The Flutter DevTools debugger and profiler on iPhone is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:50515/XFU4t2hLnY4=/
*** Assertion failure in uint64_t (anonymous namespace)::GetLogicalKeyForEvent(FlutterUIPressProxy *, uint64_t)(), FlutterEmbedderKeyResponder.mm:173
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unexpected long key label: |UIKeyInputEscape|.'
*** First throw call stack:
(0x180f0fd0c 0x198700ee4 0x1826b5df0 0x106167180 0x106166864 0x1061739c8 0x10618b00c 0x1833966e4 0x18358e0b4 0x183347608 0x1834e8504 0x1dc441f00 0x184056fe0 0x184065a10 0x184065a10 0x184065a10 0x184065a10 0x184065a10 0x184065a10 0x184057080 0x184056f08 0x1dc43bf44 0x18331bae4 0x183311838 0x183316c54 0x180f304ec 0x180f4061c 0x180e82824 0x180e87ef8 0x180e9b240 0x1a1985988 0x18369b41c 0x183434b88 0x1025a58d8 0x1037e83d0)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001bb770bbc libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1bb770bbc <+8>:  b.lo   0x1bb770bd8               ; <+36>
    0x1bb770bc0 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1bb770bc4 <+16>: mov    x29, sp
    0x1bb770bc8 <+20>: bl     0x1bb76c60c               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.2 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1354, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1354 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a30012b275 (3 hours ago), 2022-06-22 17:04:07 -0700
    • Engine revision fc08bf45b0
    • Dart version 2.18.0 (build 2.18.0-216.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by chinmaygarde** [comment] 2022-06-27 17:55
cc @jmagman @dkwingsmt @gspencergoog. Seems like an issue in IME support.

**Comment by dkwingsmt** [comment] 2022-06-30 23:13
I've proposed a PR to fix this: https://github.com/flutter/engine/pull/34413

This problem can be easily reproduced using a simulator. However, you need to enable an option: Top Menu > I/O > Input > Send Keyboard Input to Device. After that, pressing Cmd-. should trigger the crash.

**Comment by dupuchba** [comment] 2022-07-01 06:48
thanks a lot @dkwingsmt , very exciting !
By the way do you have any advice to enhance the feedback loop when working on the iOS engine part of the codebase ?
I also started a PR when I discovered the bug but compiling everything took ~2h on my local (old) MacBook plus I was unable for some reason to launch my app with my custom engine.

Thanks a lot for your time 🥇

**Comment by dkwingsmt** [comment] 2022-07-01 06:53
Thanks for you effort, your investigation and writeup have helped me greatly. Sometimes I miss issues due to having too many in the inbox. You can find us on Discord, which will likely speedup the communication (as long as we put our discussion result back onto Github for tracking.)

Compiling engine is a pain. It also takes half an hour or a full hour for me to compile it from fresh.

**Comment by chinmaygarde** [comment] 2022-07-11 17:37
Fixed by https://github.com/flutter/engine/pull/34413. Not sure why it wasn't cross referenced here by GitHub.

**Closed by chinmaygarde** 2022-07-11 17:37 UTC
Labels: severe: crash, platform-ios, engine, has reproducible steps, P2, found in release: 3.0, found in release: 3.1
