### ISSUE TITLE
Keyboard overlap all widget with nested Scaffold

### ISSUE THREAD

**Issue by splatk** [flutter/flutter#20289] opened 2018-08-07 03:56 UTC
## Steps to Reproduce
flutter 0.5.1
1. a form in AnimatedSize
2. Tap any textfield
3. keyboard show up with a white padding to overlap all widget
similar issue: https://github.com/flutter/flutter/issues/13475

![ezgif-3-ae5a51c278](https://user-images.githubusercontent.com/42162609/43753338-cb36b94c-9a37-11e8-9ca0-5d035c0758ef.gif)
```dart
new AnimatedSize(
vsync: this,
duration: const Duration(milliseconds: 200),
 new Form(
    // some text field
 ))
```
## Logs
No exception.

**Comment by zoechi** [comment] 2018-08-23 17:06
Please add the output of `flutter doctor -v`
and the code for a minimal reproduction.

**Comment by splatk** [comment] 2018-08-24 02:28
```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-HK)
    • Flutter version 0.5.1 at D:\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\kenneth.fu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: D:\kenneth\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at D:\kenneth\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at D:\kenneth\ideaIC-2017.3.1.win
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 2 categories.
```

The actual code is complicated. So I paste a demo.
Demo code to reproduce the problem  : 
```
return new MaterialApp(
      home: new Builder(builder: (context) {
        return  new Scaffold(
            body: new SignUpScreen()
        );
      }),
    );
```
SignUpScreen
```
return new Scaffold(
      appBar: // app bar,
      body: new Stack(children: <Widget>[
        new SingleChildScrollView(
          controller: scrollController,
          padding: new EdgeInsets.fromLTRB(13.7, 0.0, 13.7, 0.0),
          child: new Column(
            children: <Widget>[
              new SignUpForm(),
            ],
          ),
        )
      ])
    );
```

SignUpForm
```
return new AnimatedSize(
      vsync: this,
      duration: kThemeChangeDuration,
      child: new Form(
          key: _formKey,
          autovalidate: _autovalidate,
          child: new Container(
            child: new Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                new RequiredTextInputField(controller: nameController,
                    labelText: 'Your Name *',
                    emptyErrorMessage: "Name is required", isAlphabet: true),
                // other field
```
If I create the SignUpScreen in MaterialApp without the Scaffold(in MaterialApp).
There is no overlap issue.
However, I need to make a common bottomNavigationBar, so I can't remove the Scaffold in MaterialApp.
I use resizeToAvoidBottomPadding: false to solve the problem temporarily.

**Comment by zoechi** [comment] 2018-08-25 16:13
> without focusNode. I need to use default behavior.

What does that mean?

**Comment by nirav4273** [comment] 2018-08-26 04:54
@zoechi 

`import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
      title: "SearchBar",
      theme: ThemeData(
        primaryColor: Colors.amber
      ),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget{
  @override
  createState()=> HomePage();
}

class HomePage extends State<Home>{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new Scaffold(
      appBar: new AppBar(
        title: Text("Form")
      ),
      body:Container(
        child: Column(
          children: <Widget>[
            Expanded(
              child: Container(),
            ),
            Container(
              padding: EdgeInsets.all(10.0),
              child: TextField(
                decoration: InputDecoration(
                    hintText: "Search"
                ),
              ),
            )
          ],
        ),
      )
    );
  }
}
`

At above code set TextField at bottom of page.
For this TextField scroll working fine when keyboard open.
When i used SingleChildScrollView->Columns->TextField.  it's not working.

**Comment by zoechi** [comment] 2018-08-27 07:06
It would be easier if the code were a complete working example in a single `main.dart` file.

**Comment by zoechi** [comment] 2018-08-27 07:15
> Face same issue when i tap on first TextField.
Code as below

What is the expected behavior here? The content is shown.
I tried on `master` channel and can't see what you might want differently.

**Comment by eduardocp** [comment] 2018-08-27 12:50
I think it's the same bug as that #13339

**Comment by zoechi** [comment] 2018-08-27 13:11
#13339 doesn't seem to be a bug. It's also long closed.

**Comment by eduardocp** [comment] 2018-08-27 14:30
@zoechi Not exactly #13339, [from Hixie's comment down](https://github.com/flutter/flutter/issues/13339#issuecomment-385099552), he identifies a possible bug, which already happened to me too, I didn't open a bug because I had seen this request.

**Comment by nirav4273** [comment] 2018-08-27 16:54
@zoechi 
![form_field](https://user-images.githubusercontent.com/22423754/44672369-dfdbf600-aa45-11e8-895e-c7808df7dc0b.gif)


Please see above attached file.
I am working on master branch.
When i am tap on first field it's bounce up & come back.
Tried
resizeToAvoidBottomPadding:false not working so removed from code.
Here is my code.

`
import 'package:flutter/material.dart';
void main() => runApp(new MyApp());

class MyApp extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
      title: "SearchBar",
      theme: ThemeData(
        primaryColor: Colors.amber
      ),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget{
  @override
  createState()=> HomePage();
}

class HomePage extends State<Home>{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new Scaffold(
      appBar: new AppBar(
        title: Text("Form")
      ),
        body: SingleChildScrollView(
          reverse: true,
          child: new Column(
            children: <Widget>[
              new Container(
                // A fixed-height child.
                color: Colors.yellow,
                height: 120.0,
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 1"
                ),
              ),
              new Container(
                // Another fixed-height child.
                color: Colors.green,
                height: 120.0,
              ),
              TextField(
                decoration: InputDecoration(
                  hintText: "Field 2"
                ),
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 3"
                ),
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 4"
                ),
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 5"
                ),
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 6"
                ),
              ),
            ],
          ),
        )
    );
  }
}

`

**Comment by splatk** [comment] 2018-08-28 01:17
Complete example to reproduce my case on flutter 0.5.1, have not tested on master
`
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Scaffold(
        body: new SignUp(),
      ),
    );
  }
}

class SignUp extends StatelessWidget {
  ScrollController scrollController = new ScrollController();

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        body: new Stack(children: <Widget>[
      new SingleChildScrollView(
        controller: scrollController,
        padding: new EdgeInsets.fromLTRB(13.7, 0.0, 13.7, 0.0),
        child: new Column(
          children: <Widget>[
            new SignUpForm(),
          ],
        ),
      )
    ]));
  }
}

class SignUpForm extends StatefulWidget {

  @override
  State createState() => _SignUpFromState();

}

class _SignUpFromState extends State<SignUpForm> with TickerProviderStateMixin {

  final GlobalKey<FormState> _formKey = new GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return new AnimatedSize(
      vsync: this,
      duration: kThemeChangeDuration,
      child: new Form(
          key: _formKey,
          child: new Container(
            child: new Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField(),
                new TextField()
              ],
            ),
          )
      ),
    );
  }

}

`

**Comment by zoechi** [comment] 2018-08-31 18:33
That's because you have nested Scaffolds

**Comment by nirav4273** [comment] 2018-09-01 05:50
@zoechi  Any update about given code ?

**Comment by zoechi** [comment] 2018-09-01 08:01
Nesting Scaffolds is known to cause this behavior. 
I don't know if there are plans to change this.
My suggestion is to just not nest Scaffolds.

You have
```dart
      home: new Scaffold( // <<<===
        body: new SignUp(), // calls code below
      ),
```
an 

```dart
class SignUp extends StatelessWidget {
  ScrollController scrollController = new ScrollController();

  @override
  Widget build(BuildContext context) {
    return new Scaffold( // <===
```
I don't know what your intention is here but you should get rid of one of these two.

**Comment by nirav4273** [comment] 2018-09-01 08:14
@zoechi  https://github.com/flutter/flutter/issues/20289#issuecomment-416292072
About this comment.

**Comment by zoechi** [comment] 2018-09-01 08:30
I don't understand your last comment. 
Why do you think you need nested scaffold to build this?

**Comment by nirav4273** [comment] 2018-09-01 08:40
@zoechi 
this is my code & issue mention in comment https://github.com/flutter/flutter/issues/20289#issuecomment-416292072


`
import 'package:flutter/material.dart';
void main() => runApp(new MyApp());

class MyApp extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
      title: "SearchBar",
      theme: ThemeData(
        primaryColor: Colors.amber
      ),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget{
  @override
  createState()=> HomePage();
}

class HomePage extends State<Home>{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new Scaffold(
      appBar: new AppBar(
        title: Text("Form")
      ),
        body: SingleChildScrollView(
          reverse: true,
          child: new Column(
            children: <Widget>[
              new Container(
                // A fixed-height child.
                color: Colors.yellow,
                height: 120.0,
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 1"
                ),
              ),
              new Container(
                // Another fixed-height child.
                color: Colors.green,
                height: 120.0,
              ),
              TextField(
                decoration: InputDecoration(
                  hintText: "Field 2"
                ),
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 3"
                ),
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 4"
                ),
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 5"
                ),
              ),
              TextField(
                decoration: InputDecoration(
                    hintText: "Field 6"
                ),
              ),
            ],
          ),
        )
    );
  }
}
`

**Comment by splatk** [comment] 2018-09-03 10:07
In my app the appBar may change after push.

e.g.
```
new Scaffold( 
  appBar: new AppBar(),
  body:
),

new Scaffold( 
  appBar: new AppBar1(),
  body:
),
```

**Comment by zoechi** [comment] 2018-09-04 09:02
@splatk Is there still an issue with the latest `beta`?
I don't understand your latest comment.

**Comment by zoechi** [comment] 2018-09-05 07:17
@splatk can you please post minimal but full running example code in one file (main.dart)?

**Comment by splatk** [comment] 2018-09-05 08:00
https://github.com/flutter/flutter/issues/20289#issuecomment-416418909
this example can still reproduce the overlap problem at 0.7.3
the behavior seems different to the old version(0.5.1), the text field will scroll up when keyboard popup.
but text field still overlaps by the white padding.


this code explain why I need nested scaffold only
https://github.com/flutter/flutter/issues/20289#issuecomment-418578066

**Comment by hanxu317317** [comment] 2018-09-28 08:46
> You could try `resizeToAvoidBottomPadding: false` https://docs.flutter.io/flutter/material/Scaffold/Scaffold.html
> Not sure it helps. I just know that nested scaffolds cause that behavior.

from @zoechi

**Comment by splatk** [comment] 2018-09-28 08:53
I am using resizeToAvoidBottomPadding: false for my project now.
But this setting disables the auto scroll to appropriate input field feature.
So, I don't think this is a solution.

**Comment by hanxu317317** [comment] 2018-09-29 09:34
> I am using resizeToAvoidBottomPadding: false for my project now.
> But this setting disables the auto scroll to appropriate input field feature.
> So, I don't think this is a solution.

attep use SingleChildScrollView , maybe useful

**Comment by aderbas** [comment] 2018-10-04 18:07
Works fine with SingleChildScrollView

```
// Main Container app State (layout and user inputs)
class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: SingleChildScrollView(
          reverse: true,
          child: new Container(
            child:  LoginScreen(),
          )
        )
    );
  }
}
```

**Comment by zoechi** [comment] 2018-12-20 15:55
Duplicate of #23106

**Closed by zoechi** 2018-12-20 15:55 UTC
Labels: a: text input, f: material design, framework

**Comment by hatemragab** [comment] 2020-02-24 11:55
> TextField. it's not working.

does the problem solved ?

**Comment by richard457** [comment] 2020-03-06 14:04
@hatemragab  a solution of @aderbas  is a good solution can't call it a work around.!
