### ISSUE TITLE
Admob_firebase: How to prevent banner ad from showing if the view was already disposed

### ISSUE THREAD

**Issue by Areiser** [flutter/flutter#16757] opened 2018-04-19 19:25 UTC
## Steps to Reproduce

I have a view where I want to display a banner ad on the bottom. I added 
```dart
_bannerAd = createBannerAd();
_bannerAd..load().then((loaded) {
    if (loaded && mounted) {
        print("Is this view mounted? : $mounted");
        _bannerAd..show();
    }
 });
```
In my initState() method to load the ad when loading the view. Then after the ad finished loading it is displayed asynchronously. In the dispose method, I added 
```
    _bannerAd?.dispose();
```
to dispose the ad after the view closes. But there is a problem: If the view is closed immediately or the ad takes a while to load, dispose() was called before the ad was actually shown. In that case, the ad will be shown after it finished loading and is "stuck" to the bottom of the screen.
I tried to prevent this by using the "mounted" property to prevent showing the ad when the view was closed as can be seen in the code snippet from initState, but the mounted value is always true, so it doesn't seem to work.

Am I using the banner ad wrong or is it possible to detect that the view was already destroyed? If somebody immediately presses another button or presses the back button, the ad will almost always be stuck on the screen, which is unacceptable in my opinion.

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.8 at /run/media/andreas/Andreas/Programmieren/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/andreas/Android/Sdk
    • Android NDK at /home/andreas/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /usr/share/intellijidea-ce
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] Connected devices (1 available)
    • HUAWEI VNS L31 • FUH7N17220000709 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

**Comment by Lun4rDev** [comment] 2018-12-05 00:02
I am encountering the same issue. The dispose() method comment says :

> Disposing a banner ad that's been shown removes it from the screen

I don't really get why the ad has to be shown to be disposed. It should cancel a loading ad as well.

**Comment by alexcding** [comment] 2019-02-28 02:27
It seems the load() future callback isn't reliable. 

BannerAd(
      adUnitId: _bannerAdId,
      size: AdSize.smartBanner,
      targetingInfo: targetingInfo,
      listener: (MobileAdEvent event) {
        if (event == MobileAdEvent.loaded) {
          // dispose after you received the loaded event seems okay. 
        }
      },

**Comment by kroikie** [comment] 2019-10-13 19:12
@Areiser

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/849. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:32
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment] 2019-10-23 15:08
Hi @Areiser 
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-14 15:14
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  

Thanks for your contribution.Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-14 15:14 UTC
Labels: p: firebase, p: firebase_admob, p: first party, plugin, severe: new feature, transferred, waiting for customer response
