### ISSUE TITLE
trying to upgrade packages to last version exists on pub

### ISSUE THREAD

**Issue by Moatasem159** [flutter/flutter#146717] opened 2024-04-13 12:16 UTC
despite a package version exists on pub the Flutter tools say the version does not exist.

**Because notes depends on go_router ^13.2.4 which doesn't match any versions, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on go_router: flutter pub add go_router:^13.2.3**

**Because notes depends on get_it ^7.6.9 which doesn't match any versions, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on get_it: flutter pub add get_it:^7.6.8**

**Because notes depends on image_picker ^1.0.8 which doesn't match any versions, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on image_picker: flutter pub add image_picker:^1.0.7**

**Because notes depends on path_provider ^2.1.3 which doesn't match any versions, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on path_provider: flutter pub add path_provider:^2.1.2**

notes is my app name 
 
flutter doctor

**Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.19045.4291], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.2)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.87.2)
[√] Connected device (3 available)
[√] Network resources**

**Comment by AbdeMohlbi** [comment] 2024-04-13 15:30
this is the expected behavior because if u have multiple packages they could depend on some packages that have different versions wich creates a conflict , a good solution is to use this command : 
```shell
dart pub outdated
```
also check how to use it [here](https://dart.dev/tools/pub/cmd/pub-outdated)
if this doesn't solve ur issue try to check ur pubspec.yaml file maybee it has some errors
or simply delete ur pubspec.lock file

**Comment by Moatasem159** [comment] 2024-04-13 16:30
This is not the error When package depends on another package with different version. I tried to add the package in new project and get the same error.and I tried delete pubspec.lock and flutter clean but also get the same error

**Comment by AbdeMohlbi** [comment] 2024-04-13 16:39
have u tried dart pub outdated ?

**Comment by Moatasem159** [comment] 2024-04-13 16:47
yes but the packages that i want to upgrade not appear in the list although there are a newer versions in pub dev

**Comment by AbdeMohlbi** [comment] 2024-04-13 16:48
it's simple u have an error in ur pubspec.yaml file : 
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
```
let one space after all the packages versions like i have here

**Comment by AbdeMohlbi** [comment] 2024-04-13 16:49
look very caerfully here : 
ur file should look like that i'm sure
```yaml 
get_it ^7.6.9
path_provider ^2.1.3
image_picker ^1.0.8
```
update ur file to mach my format and it should work

**Comment by Moatasem159** [comment] 2024-04-13 16:55
```
  intl: any
  get_it: ^7.6.8
  image_picker: ^1.0.7
  path_provider: ^2.1.3
```

Resolving dependencies...
Because notes depends on path_provider ^2.1.3 which doesn't match any versions, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on path_provider: flutter pub add path_provider:^2.1.2
Process finished with exit code 1

**Comment by AbdeMohlbi** [comment] 2024-04-13 17:02
have u tried dart pub outdated ?

**Comment by Moatasem159** [comment] 2024-04-13 17:24
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest  

direct dependencies:
intl          *0.18.1  *0.18.1     *0.18.1     0.19.0  

dev_dependencies: all up-to-date.
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
Process finished with exit code 0``

**Comment by stuartmorgan** [comment] 2024-04-13 19:25
@Moatasem159 Have you configured this machine to use a pub mirror? All of the versions in your error output are from within the last couple of days, and mirrors are not always updated immediately.

**Comment by Moatasem159** [comment] 2024-04-14 10:27
@stuartmorgan  i tried to add the last version to new project and the same error happend

`Resolving dependencies...
Because test_pub depends on get_it ^7.6.9 which doesn't match any versions, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on get_it: flutter pub add get_it:^7.6.8
Process finished with exit code 1`


pupspec.yaml file

`name: test_pub
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.9
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by stuartmorgan** [comment] 2024-04-14 12:16
> i tried to add the last version to new project and the same error happend

Using a pub mirror is a machine-level setting, not project-level, so if you are using a mirror it's expected that a new project would behave the same way.

**Comment by huycozy** [comment] 2024-04-15 08:15
@Moatasem159 Could you also share the output of `flutter doctor -v` which may have details of network configuration information? 
This could be filed on [dart-lang/pub](https://github.com/dart-lang/pub) for better insights there.

**Comment by Moatasem159** [comment] 2024-04-15 11:25
@huycozy 
`[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.19045.4291], locale en-US)
    • Flutter version 3.19.5 on channel stable at C:\dev\flutter            
    • Upstream repository https://github.com/flutter/flutter.git            
    • Framework revision 300451adae (3 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498                                            
    • Dart version 3.3.3                                                    
    • DevTools version 2.31.1                                               
    • Pub download mirror https://pub-web.flutter-io.cn/

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\moata\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34622.214
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4291]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.92

[√] Network resources
    • All expected network resources are available.

• No issues found!
`

**Comment by huycozy** [comment] 2024-04-16 04:03
>Pub download mirror https://pub-web.flutter-io.cn/

@Moatasem159 You are using a community-run mirror site. Please check https://docs.flutter.dev/community/china#known-trusted-community-run-mirror-sites for more information and also [send an issue to their repository](https://github.com/cfug/flutter.cn/issues/new/choose) for better support there.

Closing this issue as it doesn't appear to be a Flutter framework bug.

**Closed by huycozy** 2024-04-16 04:03 UTC
Labels: in triage
