### ISSUE TITLE
in_app_purchase: How to validate receipts on iOS?

### ISSUE THREAD

**Issue by ValeriusGC** [flutter/flutter#77232] opened 2021-03-04 09:12 UTC
Hi!
I've made flutter app with auto-renewable subscriptions. It works well on Android, but from Appstore i received this letter:
![photo_2021-03-04_14-11-52](https://user-images.githubusercontent.com/3320861/109940160-985c1200-7cf3-11eb-9bbb-f66c1c30d596.jpg)
Please give me advice, how to deal with it?

**Comment by nt4f04uNd** [comment] 2021-03-04 10:45
duplicate #61339

**Comment by nt4f04uNd** [comment] 2021-03-04 10:47
oh actually i think no. they are similar and can be closed by one PR but not duplicate

**Comment by ValeriusGC** [comment] 2021-03-04 16:31
> duplicate #61339
There is very laconic advice there. I have no idea how to realize this in flutter neither local nor server... (((
Maybe anyone flutter guru can send me steo-by-step lesson or so to deal with this quest?
Actually a lot of `dart pub libraries` (such a **local_auth**, etc) have samples what code one need to write in native - swift or kotlin to achive a result, but not in_app_purchase alas. I really got stucked. Some double-trouble it is.

**Comment by nt4f04uNd** [comment] 2021-03-04 17:00
@ValeriusGC this actually goes beyond what flutter handles, and this is really up to you how you handle purchase validation

here are basic steps to get server validation:

1. get `serverVerificationData` from `in_app_purchase` - on iOS this is base64 encoded string
<details>

```dart
if (purchaseDetails != null) {
  var verificationData = purchaseDetails.verificationData;
  if (Platform.isIOS && verificationData == null) {
    verificationData = await InAppPurchaseConnection.instance.refreshPurchaseVerificationData();
  }
  // call to backend
  final bool subscriptionActive = await firebaseRepository.validatePurchase(
    verificationData.serverVerificationData
  );
// ...
}
```
</details>

2. on server setup such function (i use nodejs firebase cloud functions for example)

<details>

```ts
/**  
*  This function validates the user purchase on iOS.
*  It queries the data from the Apple verifyReceipt method, checks whether subscription is still active
*  and returns a boolean value.
*/
export const validatePurchase = functions.https.onCall(async (data, context) => {
   const { verificationData } = data;
   if (verificationData === undefined) {
      throw new functions.https.HttpsError('invalid-argument', 'Required `verificationData` field is missing');
   }
   const requestData = JSON.stringify({
      'receipt-data': verificationData,
      'password': itunes.password, // this is API key from appstoreconnect
      'exclude-old-transactions': true,
   });
   const headers = {
      'Content-Type': 'application/json',
      'Content-Length': requestData.length,
   };
   let res = await axios.post('https://buy.itunes.apple.com/verifyReceipt', requestData, { headers: headers });
   if (res.data.status === 21007) {
      res = await axios.post('https://sandbox.itunes.apple.com/verifyReceipt', requestData, { headers: headers });
   }
   const latestInfo = res.data?.latest_receipt_info;
   const pendingRenewalInfo = res.data?.pending_renewal_info;
   if (!latestInfo || !pendingRenewalInfo || !latestInfo[0] || !pendingRenewalInfo[0]) {
      functions.logger.log(`{ verificationData: ${verificationData}, status: ${res.data?.status}, false, description: no latest_receipt_info or pending_renewal_info }`);
      return false;
   }
   const graceMs = pendingRenewalInfo[0].grace_period_expires_date_ms;
   const now = Date.now();
   if (graceMs) {
      const value = now < graceMs;
      functions.logger.log(`{ verificationData: ${verificationData}, ${value}, description: grace period }`);
      return value;
   }
   const expiresMs = latestInfo[0].expires_date_ms;
   const value = now < expiresMs;
   functions.logger.log(`{ verificationData: ${verificationData}, ${value}, description: default period (no grace) }`);
   return value;
});
```
</details>

**Comment by nt4f04uNd** [comment] 2021-03-04 17:11
local validation is not reliable, heavy and not implemented in flutter
see https://github.com/flutter/flutter/issues/52522

**Comment by ValeriusGC** [comment] 2021-03-04 17:14
Шt turns out that, that no way to realize it without making my own server?

**Comment by nt4f04uNd** [comment] 2021-03-04 17:15
yes, refer to https://github.com/flutter/flutter/issues/77232#issuecomment-790778672

**Comment by nt4f04uNd** [comment] 2021-03-04 17:18
i reconsidered, it's actually a duplicate of #61339 @TahaTesser

**Comment by ValeriusGC** [comment] 2021-03-04 17:22
> yes, refer to [#77232 (comment)](https://github.com/flutter/flutter/issues/77232#issuecomment-790778672)

I am really shocked! Do thousands of lone programmers build their own servers to get subscriptions? don't make me wrong, please, i can not believe this is really so complex.

**Comment by nt4f04uNd** [comment] 2021-03-04 17:27
i didn't say it's complex. you can always implement it your own by writing some [native code](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html)
i updated my previous comment a bit as well

**Comment by nt4f04uNd** [comment] 2021-03-04 17:42
summarized all from above in https://github.com/flutter/flutter/issues/61339#issuecomment-790791205

**Comment by mvanbeusekom** [comment] 2021-05-20 11:15
Apple and Google both highly recommend handling the verification of receipts on the server-side. Since yesterday a [codelab](https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#0) is available which will take you through the steps on setting up server-side receipt verification using Firebase. Even if you don't want to use Firebase as a backend solution, the codelab might be helpful as it discusses all steps necessary to verify a receipt in detail.

More information can be found in the store specific documentation:
- Apple StoreKit: https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store?language=objc
- Google Billing Client: https://developer.android.com/google/play/billing/security

Local validation is also possible as the in_app_purchase API provides all the data necessary to do so, however since it is not recommended no examples have been worked out. 

I will close this issue as I feel with the codelab there is clear information on how to handle the verification (be it server-side). However please don't hesitate to leave a comment if you have any more specific questions and I would be happy to re-open it.

**Closed by mvanbeusekom** 2021-05-20 11:15 UTC
Labels: P5, documentation, p: first party, p: in_app_purchase, passed first triage, plugin
