### ISSUE TITLE
testWidgets  Shell subprocess crashed with segmentation fault after tests finished

### ISSUE THREAD

**Issue by liruibao** [flutter/flutter#60688] opened 2020-07-01 13:16 UTC
I copied the unit test demo on the official website, but there was an error when running，the error message is as follows
![image](https://user-images.githubusercontent.com/29444771/86248129-0938b080-bbe0-11ea-8c36-6a05c8cf2d92.png)

![image](https://user-images.githubusercontent.com/29444771/86248083-f920d100-bbdf-11ea-9e49-6d198f851578.png)

What is the reason for this?

test code 

![image](https://user-images.githubusercontent.com/29444771/86248574-a8f63e80-bbe0-11ea-8d4d-e44fb669c773.png)

**Comment by VladyslavBondarenko** [comment] 2020-07-01 13:33
Hi @liruibao 
closing as duplicate of https://github.com/flutter/flutter/issues/60519,
please use an older version of the flutter plugin for Android Studio (before v 47) or run tests in debug mode until next version is released

**Closed by VladyslavBondarenko** 2020-07-01 13:33 UTC

**Comment by liruibao** [comment] 2020-07-03 10:49
Okay thank you
