### ISSUE TITLE
[Material] Allow Drawer width to be customized

### ISSUE THREAD

**Issue by TytaniumDev** [flutter/flutter#99776] opened 2022-03-08 20:15 UTC
## Use case

Being able to customize the width of the Material drawer widget. We're building a responsive app and find that we need to increase/decrease drawer width based on screen size.

## Proposal

`Drawer` already has a `width` field internally, it's just always set to a constant value (`_kWidth`). The proposed change is just adding the `width` field to the constructor and having it default to `_kWidth`, so this would be a backwards compatible change.

**Comment by danagbemava-nc** [comment] 2022-03-09 07:53
This appears to be a duplicate of https://github.com/flutter/flutter/issues/19724. 

An alternative is to wrap the `Drawer` with a `SizedBox` and specify the width that way. 

Thanks for the PR, I think it might be best if it references https://github.com/flutter/flutter/issues/19724. 

Closing from here as duplicate. 

Thank you

**Closed** 2022-03-25 20:19 UTC
Labels: framework, f: material design, proposal
