### ISSUE TITLE
[Windows] Right-Shift turns on caps lock and locks in a TextField

### ISSUE THREAD

**Issue by barribarrier** [flutter/flutter#99529] opened 2022-03-04 04:10 UTC
This seems to only happen when you press multiple keys in a quick succession while holding down Right-Shift.
Related: https://github.com/flutter/flutter/issues/75675

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. While pressing Right-Shift, type "ASD" very fast.
3. Let go of the Right-Shift key and type "qwe.".

**Expected results:**
TextField value is "ASDqwe."

**Actual results:**
TextField value is "ASDQWE>"

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).        
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
[!] Android Studio (not installed)
[√] VS Code (version 1.64.2)
[√] Connected device (2 available)
[√] HTTP Host Availability

! Doctor found issues in 3 categories.
```

</details>

**Comment by maheshmnj** [comment] 2022-03-04 10:35
Hi @barribarrier, thanks for filing the issue. I am unable to reproduce the issue with your reproducible steps I see text correctly entered `ASDqwe`, Are there any unusual errors/logs in the console when this error occurs?
Could you please check if this happens with other applications too (Just to ensure if this is not an issue with your system) ?  


<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1526], locale en-US)
    • Flutter version 2.10.3 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (14 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by barribarrier** [comment] 2022-03-04 10:46
I just tested with AuthPass and same happens. It is only happening with Flutter apps.
Two other customer was complaining about not being able to login after signing up. I tracked the cause to this bug.
I contacted with one of the affected customer and we were able to reproduce it on their system too.

I'm gonna test it with master now and report back.
The workaround mentioned in [here](https://github.com/flutter/flutter/issues/75675) works. We're using this in the meantime.

**Comment by barribarrier** [comment] 2022-03-04 11:03
I can confirm this is fixed on master.

**Comment by maheshmnj** [comment] 2022-03-04 12:32
Thanks for the confirmation, The fix should be available on the stable channel in the upcoming stable release.

 Closing based on the above response.

**Closed by maheshmnj** 2022-03-04 12:32 UTC
Labels: in triage
