### ISSUE TITLE
Android keyboard hides bottom bar in scaffold

### ISSUE THREAD

**Issue by NobodyForNothing** [flutter/flutter#140663] opened 2023-12-27 16:24 UTC
### Steps to reproduce

1. create a material app with a `Scaffold`
2. put some bottom app bar as `bottomNavigationBar`
3. open a keyboard by clicking on a TextFormField on the body

### Expected results

<details><summary>The bar gets moved up, like when wrapping the Scaffold in a `Dialoge.fullscreen`.</summary>

![Screenshot_20231227_171349](https://github.com/flutter/flutter/assets/82763757/ca434dd9-f9b2-49c0-836d-d6b08ce6daa8)

</details>

### Actual results

The bottom bar is hidden by the Android keyboard.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        bottomNavigationBar: BottomAppBar(
          child: Text('BAR'),
        ),
        body: TextFormField(),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20231227_171549](https://github.com/flutter/flutter/assets/82763757/c690141d-c960-4ed8-88d3-9f8929a34c69)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output 3.16.3</summary>

```console
[✓] Flutter (Channel stable, 3.16.3, on Garuda Linux 6.6.8-zen1-1-zen, locale en_US.UTF-8)
    • Flutter version 3.16.3 on channel stable at /home/derdilla/bin/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (3 weeks ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/derdilla/Android/Sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • ANDROID_HOME = /home/derdilla/Android/Sdk
    • Java binary at: /home/derdilla/bin/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.28.1
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/derdilla/bin/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/derdilla/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /home/derdilla/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 77.0.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Garuda Linux 6.6.8-zen1-1-zen
    • Chrome (web)                 • chrome        • web-javascript • Chromium 120.0.6099.129 Arch Linux

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

<details open><summary>Doctor output main branch</summary>

```console
✓] Flutter (Channel main, 3.17.0-12.0.pre.12, on Garuda Linux 6.6.8-zen1-1-zen, locale en_US.UTF-8)
    • Flutter version 3.17.0-12.0.pre.12 on channel main at /home/derdilla/bin/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d7608f432 (6 weeks ago), 2023-11-17 20:15:16 -0800
    • Engine revision 53c4fde773
    • Dart version 3.3.0 (build 3.3.0-149.0.dev)
    • DevTools version 2.30.0-dev.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/derdilla/Android/Sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • ANDROID_HOME = /home/derdilla/Android/Sdk
    • Java binary at: /home/derdilla/bin/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.28.1
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/derdilla/bin/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/derdilla/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /home/derdilla/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 77.0.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Garuda Linux 6.6.8-zen1-1-zen
    • Chrome (web)                 • chrome        • web-javascript • Chromium 120.0.6099.129 Arch Linux

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-12-29 09:17
Thanks for filing this @NobodyForNothing.
I see there is an open proposal similar to this https://github.com/flutter/flutter/issues/26499.
Kindly upvote, comment and follow up on this for updates.
Closing this as a duplicate of the already existing issue, if you disagree, please write and I'll reopen this.
Thank you!

**Closed by dam-ease** 2023-12-29 09:17 UTC
Labels: in triage
