### ISSUE TITLE
[Material 3] TextTheme issue

### ISSUE THREAD

**Issue by zs-dima** [flutter/flutter#116066] opened 2022-11-27 10:52 UTC
TextTheme could be assigned in 2 different way in the same time currently.

Is there any way to
1. Pass colors Material3 color transitions to the TextThemes
2. Reduce code boilerplate:
```Dart
appTypography = Typography.material2021(tall: TextTheme(displayLarge: TextStyle(color: m3themeColor, ...
app*TextTheme = const TextTheme(displayLarge: TextStyle(color: m3themeColor, ...

appMaterialLightThemeData = ThemeData(
  useMaterial3: true,
  textTheme: app*TextTheme,
  typography: appTypography,
```

Thanks in advance

**Comment by exaby73** [comment] 2022-11-28 09:22
Hello @zs-dima. I'm sorry but I do not understand the issue here? Could you elaborate on it? What's the issue here with the `TextTheme` or with `Typography`?

**Comment by zs-dima** [comment] 2022-11-28 09:27
@exaby73 thanks for looking into.
It is common Flutter theming issue as it is Font styles could not be applied properly with the current structure as you could see.
For example, what Font color will have priority and be applied to the default Flutter widgets?

**Comment by exaby73** [comment] 2022-11-28 11:44
Could you provide a  [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates this issue?

**Comment by zs-dima** [comment] 2022-11-28 20:25
@exaby73 sure

With this example it will no Material 3 colors transitions when you changing system themeMode for fonts the same as for the other colors with `AppColors lerp()` override and I displayed that current class structure allows to write application font styles in the unpredictable way.

Could I kindly ask you what color will be used for the 'displayLarge' for the current example?

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

final _appTypography = Typography.material2021(tall: TextTheme(displayLarge: TextStyle(color: Colors.green)));
final _appTextTheme = const TextTheme(displayLarge: TextStyle(color: Colors.red));

final _appMaterialLightThemeData = ThemeData(
  useMaterial3: true,
  textTheme: _appTextTheme,
  typography: _appTypography
);

final _appDarkTypography = Typography.material2021(tall: TextTheme(displayLarge: TextStyle(color: Colors.orange)));
final _appTextDarkTheme = const TextTheme(displayLarge: TextStyle(color: Colors.green));

final _appMaterialDarkThemeData = ThemeData(
  useMaterial3: true,
  textTheme: _appTextDarkTheme,
  typography: _appDarkTypography
);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      themeMode: ThemeMode.light,      
      theme: _appMaterialLightThemeData ,
      darkTheme: _appMaterialDarkThemeData,
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Text(widget.title),
    );
  }
}

```

**Comment by exaby73** [comment] 2022-11-29 07:59
I think this is working as expected. The `Typography` class allows you to define `textTheme` for different typographys like cupertino and material. To customize each theme, you should use `textTheme` and not `typography`. It works as expected for me, with red in light theme and green in dark theme.

Since this is working as expected, I am closing this issue. If you disagree with my decision, please comment with your reasoning and I can reopen it. Thank you

**Closed by exaby73** 2022-11-29 07:59 UTC
Labels: in triage
