### ISSUE TITLE
scroll start jump

### ISSUE THREAD

**Issue by tkkcc** [flutter/flutter#19853] opened 2018-07-27 03:41 UTC
Flutter apps jump at slow scroll start, both on real device and emulator, native apps don't jump.
Here is an example of `flutter gallery`
![tim 20180727113801](https://user-images.githubusercontent.com/17373509/43300421-c92fc44e-9191-11e8-91e4-e15ea07b04d5.gif)

**Comment by goderbauer** [comment] 2019-01-03 01:14
Dupe of https://github.com/flutter/flutter/issues/20495.

**Closed by goderbauer** 2019-01-03 01:14 UTC
Labels: f: scrolling, framework, team: gallery
