### ISSUE TITLE
1.22 stable broke input focus in AutofillGroup on iOS

### ISSUE THREAD

**Issue by stx** [flutter/flutter#67180] opened 2020-10-03 00:01 UTC
Focus switching appears to be broken in 1.22 with input fields wrapped in an AutofillGroup on (at least) iOS 14 devices and simulator. Works on Android emulator.

`textInputAction: TextInputAction.next` and  `FocusScope.of(context).requestFocus(...)` both result in the focus switching to the next field, but then instantly jumping back to the previous field.

I'm unable to find the underlying cause or a workaround other than removing AutofillGroup and this is a bad enough UX problem that it's blocking us from shipping 1.22 builds to iOS 14 customers.

```
class TestScreen extends StatefulWidget {
  const TestScreen();

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  FocusNode _passwordFocus = FocusNode();

  void _onEmailSubmitted(String email) {
    FocusScope.of(context).requestFocus(_passwordFocus);
  }

  @override
  Widget build(BuildContext context) {
    // Remove AutofillGroup, works again
    return AutofillGroup(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          TextField(
            keyboardType: TextInputType.emailAddress,
            autofillHints: const <String>[
              AutofillHints.email,
            ],
            // broken: switches to next field and then immediately switches back
            onSubmitted: _onEmailSubmitted,
            // broken: switches to next field and then immediately switches back
            textInputAction: TextInputAction.next,
          ),
          TextField(
            keyboardType: TextInputType.text,
            focusNode: _passwordFocus,
            autofillHints: const <String>[
              AutofillHints.password,
            ],
            textInputAction: TextInputAction.done,
          ),
        ],
      ),
    );
  }
}
```

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0 at /Users/james/Development/flutter
    • Framework revision d408d302e2 (3 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Virgo (mobile) • 00008030-000848D11EF0802E • ios • iOS 14.0

• No issues found!
```

</details>

**Comment by cbenhagen** [comment] 2020-10-03 11:44
Duplicate of https://github.com/flutter/flutter/issues/66144

**Comment by zacherygentry** [comment] 2020-10-03 17:04
Running into the same issue here

**Comment by TahaTesser** [comment] 2020-10-05 10:22
Hi @stx 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/66144
Please follow up on that issue, I'm closing the current one as a duplicate. 
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-05 10:22 UTC
