### ISSUE TITLE
NSM in package:vm_service in web tool tests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#83260] opened 2021-05-24 15:17 UTC
From: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/2108/overview

This appears to be flaky, but even so `package:vm_service` should not NSM.

```
01:35 +0 -1: test\web.shard\debugger_stepping_web_test.dart: Web debugger can step over statements [E]                                                                                                 
  getStack: (-32603) getStack: NoSuchMethodError: The method 'toJson' was called on null.
  Receiver: null
  Tried calling: toJson()
  #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
  #1      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1582:28)
  <asynchronous suspension>
  
  package:vm_service/src/vm_service.dart 1606:45        new _OutstandingRequest
  package:vm_service/src/vm_service.dart 2078:21        VmService._call
  package:vm_service/src/vm_service.dart 1890:61        VmService.getStack
  test\integration.shard\test_driver.dart 334:42        FlutterTestDriver.getTopStackFrame
  ===== asynchronous gap ===========================
  dart:async                                            _Completer.completeError
  package:vm_service/src/vm_service.dart 1613:18        _OutstandingRequest.completeError
  package:vm_service/src/vm_service.dart 2163:15        VmService._processResponse
  package:vm_service/src/vm_service.dart 2152:7         VmService._processMessageStr
  package:vm_service/src/vm_service.dart 2104:7         VmService._processMessage
  ===== asynchronous gap ===========================
  dart:async                                            _StreamImpl.listen
  package:vm_service/src/vm_service.dart 1648:27        new VmService
  package:vm_service/vm_service_io.dart 41:10           vmServiceConnectUri
  ===== asynchronous gap ===========================
  dart:async                                            _asyncThenWrapperHelper
  test\integration.shard\test_driver.dart 139:24        FlutterTestDriver.connectToVmService
  test\integration.shard\test_driver.dart 576:17        FlutterRunTestDriver._setupProcess.<fn>
  ===== asynchronous gap ===========================
  dart:async                                            _asyncThenWrapperHelper
  test\integration.shard\test_driver.dart               FlutterRunTestDriver._setupProcess.<fn>
  test\integration.shard\test_driver.dart 596:6         FlutterRunTestDriver._setupProcess
  ===== asynchronous gap ===========================
  dart:async                                            _asyncThenWrapperHelper
  test\integration.shard\test_driver.dart 471:11        FlutterRunTestDriver.run
  test\web.shard\debugger_stepping_web_test.dart 28:19  main.<fn>
  ===== asynchronous gap ===========================
  dart:async                                            _asyncThenWrapperHelper
  test\web.shard\debugger_stepping_web_test.dart        main.<fn>
  dart:async                                            runZoned
  test\src\common.dart 184:14                           testWithoutContext.<fn>
  test\src\common.dart 183:18                           testWithoutContext.<fn>
  test\src\common.dart 154:18                           test.<fn>
  test\src\common.dart 150:5                            test.<fn>
```

**Comment by jmagman** [comment] 2021-05-24 20:39
Duplicate of https://github.com/flutter/flutter/issues/81592, keeping this one open instead though since @bkonyi is assigned.

**Comment by bkonyi** [comment] 2022-02-16 23:37
Giving this a second look, I don't think this is actually in `package:vm_service` but in `dwds` since the NSM is occurring in the remote target and being reported as an RPC error.

cc @annagrin @elliette

**Comment by annagrin** [comment] 2022-05-13 01:32
@bkonyi I am not really sure what is happening there... Tried a few experiments but I cannot repro the issue, so I suspect something is going on outside of dwds:

my tries: https://github.com/dart-lang/webdev/pull/1614

Some observations:

- the stack is strange: 
```
 package:vm_service/src/vm_service.dart 1606:45        new _OutstandingRequest
  package:vm_service/src/vm_service.dart 2078:21        VmService._call
  package:vm_service/src/vm_service.dart 1890:61        VmService.getStack

>>> Anna: how do we end up here from _Completer.completeError?
  test\integration.shard\test_driver.dart 334:42        FlutterTestDriver.getTopStackFrame
>>>

  ===== asynchronous gap ===========================
  dart:async                                            _Completer.completeError
  package:vm_service/src/vm_service.dart 1613:18        _OutstandingRequest.completeError
  package:vm_service/src/vm_service.dart 2163:15        VmService._processResponse
  package:vm_service/src/vm_service.dart 2152:7         VmService._processMessageStr
  package:vm_service/src/vm_service.dart 2104:7         VmService._processMessage
  ===== asynchronous gap ===========================
  dart:async                                            _StreamImpl.listen
  package:vm_service/src/vm_service.dart 1648:27        new VmService
  package:vm_service/vm_service_io.dart 41:10           vmServiceConnectUri
```

- It looks like the request that is converted to json in `VmServiceDelegate` is `null`, but `ChromeProxyService.getStack` never returns `null`. If I try to manually change it to return `null`, I get a similar trace but not exactly the same:

```
00:16 +0 -1: shared context | callStack | callstack while paused [E]
  getStack: (-32603) getStack: NoSuchMethodError: The method 'toJson' was called on null.
  Receiver: null
  Tried calling: toJson()
  #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
  #1      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1718:28)
  <asynchronous suspension>

  package:vm_service/src/vm_service.dart 1742:45  new _OutstandingRequest
  package:vm_service/src/vm_service.dart 2255:21  VmService._call
  package:vm_service/src/vm_service.dart 2029:61  VmService.getStack
  test/vm_service_test.dart 114:39                main.<fn>.<fn>.<fn>.<fn>
  test/vm_service_test.dart 113:54                main.<fn>.<fn>.<fn>.<fn>
  test/vm_service_test.dart 98:19                 main.<fn>.onBreakPoint
  ===== asynchronous gap ===========================
  test/vm_service_test.dart 113:9                 main.<fn>.<fn>.<fn>
```

**Comment by annagrin** [comment] 2022-05-13 01:34
Assigning to @bkonyi since the error seems to occur in `VmServerConnection` or `VmService`.

**Comment by annagrin** [comment] 2022-05-13 23:24
Actually, I see that the test is no longer disabled, so if we see no new flakes like the one above, we should close the issue.

**Closed** 2022-05-16 17:53 UTC
Labels: a: tests, tool, dependency: dart, team: flakes, platform-web, severe: disabled test
