### ISSUE TITLE
Widgets in AppBar's actions can't get context correctly

### ISSUE THREAD

**Issue by MCredbear** [flutter/flutter#126226] opened 2023-05-07 13:45 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
import 'package:http/http.dart' as http;

import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class ConnectDialog extends StatefulWidget {
  const ConnectDialog({super.key});

  @override
  State<StatefulWidget> createState() => _ConnectDialog();
}

class _ConnectDialog extends State<ConnectDialog> {
  @override
  Widget build(BuildContext context) {
    return const AlertDialog.adaptive(
      title: Text('连接服务器'),
      content: SizedBox(
        width: 200,
        height: 200,
      ),
    );
  }
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  String title = '/';

  Map<String, int> allComicMap = {};
  Map<String, int> showingComicMap = {};

  bool isLoading = true;

  bool showRanked = false;

  @override
  void initState() {
    var url = Uri.parse('http://127.0.0.1:1145/');
    http.get(url).then((value) {
      var tmpList = value.body.split('\n');
      allComicMap = {};
      for (var i = 0; i < tmpList.length - 1; i += 2) {
        allComicMap.putIfAbsent(tmpList[i], () => int.parse(tmpList[i + 1]));
      }
      showingComicMap = allComicMap;
      if (!showRanked) {
        showingComicMap.removeWhere((key, value) => value != -1);
      }
      setState(() {
        isLoading = false;
      });
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: Text(title),
        actions: [
          IconButton(
              onPressed: () {
                showDialog(
                    context: context,
                    builder: (BuildContext context) => ConnectDialog());
              },
              icon: const Icon(Icons.connected_tv)),
          IconButton(
              onPressed: () {
                showRanked = !showRanked;
                showingComicMap = allComicMap;
                if (!showRanked) {
                  showingComicMap.removeWhere((key, value) => value != -1);
                }
                setState(() {});
              },
              icon: Icon(showRanked ? Icons.visibility : Icons.visibility_off)),
          IconButton(
              onPressed: () {
                var url = Uri.parse('http://127.0.0.1:1145/');
                http.get(url).then((value) {
                  var tmpList = value.body.split('\n');
                  allComicMap = {};
                  for (var i = 0; i < tmpList.length - 1; i += 2) {
                    allComicMap.putIfAbsent(
                        tmpList[i], () => int.parse(tmpList[i + 1]));
                  }
                  showingComicMap = allComicMap;
                  if (!showRanked) {
                    showingComicMap.removeWhere((key, value) => value != -1);
                  }
                  setState(() {
                    isLoading = false;
                  });
                });
              },
              icon: const Icon(Icons.refresh))
        ],
      ),
      body: Center(
        child: isLoading
            ? const CircularProgressIndicator.adaptive()
            : ListView.builder(
                itemCount: showingComicMap.length,
                itemBuilder: (BuildContext context, int index) {
                  return ListTile(
                    title: Text(
                        showingComicMap.entries.toList().elementAt(index).key),
                    onTap: () {
                      showDialog(
                          context: context,
                          builder: (BuildContext context) => ConnectDialog());
                    },
                  );
                }),
      ),
    ));
  }
}

```

### Expected results

The `showDialog` at line 75 should work correctly.

### Actual results

In this code, `showDialog` at  line 75 reports
```FlutterError (No MaterialLocalizations found.
MainApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
The material library uses Localizations to generate messages, labels, and abbreviations.
To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
The specific widget that could not find a MaterialLocalizations ancestor was:
  MainApp
The ancestors of this widget were:
  MediaQuery
  _MediaQueryFromView
  _ViewScope
  View-[GlobalObjectKey FlutterView#df0aa]
  [root])
```
But the line 122 one works correctly.

### Code sample

<details><summary>Code sample</summary>

```dart

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on Debian GNU/Linux 12 (bookworm) 6.1.0-7-amd64, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by TahaTesser** [comment] 2023-05-08 07:34
Hi @MCredbear 

This error is thrown when a widget that depends on `MaterialLocalizations` doesn't receive `MaterialLocalizations` from an ancestor widget. This is provided `MaterialApp`
```
MainApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
The material library uses Localizations to generate messages, labels, and abbreviations.
To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
The specific widget that could not find a MaterialLocalizations ancestor was:
  MainApp
The ancestors of this widget were:
  MediaQuery
  _MediaQueryFromView
  _ViewScope
  View-[GlobalObjectKey FlutterView#df0aa]
  [root])
 ```
 
 However, In your code sample, you have provided `MaterialApp` and `showDialog` in the same class, `showDialog` doesn't have an ancestor that can provide `MaterialLocalizations`. You need to either move your `Scaffold` to a separate stateless widget or wrap your Scaffold with a `Builder` widget.  
 
 Here is a code sample to try. 
 
 <details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: Builder(builder: (BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: const Text('Sample'),
            actions: <Widget>[
              IconButton(
                onPressed: () {
                  showDialog(
                    context: context,
                    builder: (BuildContext context) {
                      return const AlertDialog.adaptive(
                        title: Text('Dialog'),
                      );
                    },
                  );
                },
                icon: const Icon(Icons.more_vert_rounded),
              )
            ],
          ),
        );
      }),
    );
  }
}
``` 
	
</details>

Closing, as this is not a bug.

**Closed by TahaTesser** 2023-05-08 07:34 UTC
Labels: in triage
