### ISSUE TITLE
DatePicker Dark Theme cannot function properly because of ColorScheme.onSurface

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#104818] opened 2022-05-27 10:05 UTC
## Steps to Reproduce

The color of a day in the Material Date Picker is taken directly from `ColorScheme.onSurface`, with an opacity of 0.87.
So if I want to have a dark Date Picker with the days being white, I need to specify `ColorScheme.onSurface = Colors.white`. There is no way around this that I know of.
Problem is : with `ColorScheme.brightness = Brightness.dark`, `ColorScheme.onSurface` is also used a the background color for `_DatePickerHeader`. Which means that I cannot have this background be another color.

I'm not sure what's the right way to go about this. I want both the day text and the title text to be white, but this simply doesn't seem possible.
I think the DatePicker widget should take a DatePickerThemeData class, which would allow for overriding any style within it. This would unlock 100% customizability without wrecking any existing code.

Here's the gist : https://dartpad.dev/?id=8f9baaca1f1104152c2d847a07b8bd2b

Relevant lines in Flutter are date_picker.dart:755 (_DatePickerHeader.build) and calendar_date_picker.dart:945 (_DayPickerState.build) as of Flutter 3.

**Comment by TahaTesser** [comment] 2022-05-27 11:31
Hi @TheCarpetMerchant 

Thanks for filing the issue, this looks the same as https://github.com/flutter/flutter/issues/87580 and Theme will added by https://github.com/flutter/flutter/issues/93707 

Closing as duplicate of https://github.com/flutter/flutter/issues/87580

**Closed by TahaTesser** 2022-05-27 11:31 UTC
Labels: in triage
