### ISSUE TITLE
Intellij doctor check crashed

### ISSUE THREAD

**Issue by Lee8888888** [flutter/flutter#98977] opened 2022-02-23 12:30 UTC
Hi, I keep getting this message when trying to run a new flutter project on intellij. I have reached out to intellij but thier support team claims it's a flutter issue. Can somebody please assist me with the issue attached.

![Screenshot (9)](https://user-images.githubusercontent.com/100287208/155319662-085d5134-c71b-4e20-8616-450b53c5a062.png)

**Comment by maheshmnj** [comment] 2022-02-25 07:12
Closing as duplicate of https://github.com/flutter/flutter/issues/94060, This issue is fixed on the master channel and the fix should be available on the stable channel in the upcoming stable release.

**Closed by maheshmnj** 2022-02-25 07:12 UTC
Labels: in triage
