### ISSUE TITLE
Font color glyphs disappears at larger sizes

### ISSUE THREAD

**Issue by andreidiaconu** [flutter/flutter#16386] opened 2018-04-09 23:41 UTC
## Steps to Reproduce

I am trying to use `Icon` and `IconData` to render emoticons. This seems to work for most cases, but in situations where the icon is larger (I've found 85 logical pixels to be the breaking point), certain situations make the icons disappear. I have tried both the iOS simulator and Android emulator and both break, but in different ways. This applies only to color glyphs.
Digging further I understood that this is a manifestation of issues with text rendering. I'll do my best to describe steps to reproduce.

### Android

In order to get it to break, the font needs to be large (over 71), needs to contain a color glyph, like an emoticon (eg. ` "\u{1F600}"`) and the text needs to be rotated (I used 0.1 rad). If any of these conditions are not met, the render is looking good.
Also breaks on my Galaxy S8, not only the emulator.

### iOS

In order to get it to break, the font needs to be large (over 85) and needs to be a color glyph. Rotation does not seem to have an influence.

### Code to reproduce:
Below code breaks on both iOS and Android:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        home: new Scaffold(
            body: new Center(
                child: new Transform.rotate(
                  angle: 0.1, // Rotation breaks Android
                  child: new Text("Hi there! Here is an emoji: \u{1F600}",
                    style: new TextStyle(inherit: true, fontSize: 86.0),), // Size 86 breaks iOS
                )
            )
        )
    );
  }
}
```

## Screenshots

![flutter large glyph bugs](https://user-images.githubusercontent.com/1402046/38528488-a8555afa-3c68-11e8-9606-e6b338763483.png)

## Logs

`flutter run` and `flutter analyze` render nothing interesting. I did try to run the app using `--enable-software-rendering` but the results are the same.

## Flutter Doctor
```
[✓] Flutter (Channel dev, v0.2.10, on Mac OS X 10.13.4 17E199, locale en-RO)
    • Flutter version 0.2.10 at /Users/andrei/Library/Android/flutter
    • Framework revision d6d874474b (3 days ago), 2018-04-06 13:23:16 -0700
    • Engine revision d2b69fec75
    • Dart version 2.0.0-dev.46.0.flutter-09e1766e6c

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    • Android SDK at /Users/andrei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 28.0.0-rc1
    • ANDROID_HOME = /Users/andrei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] Connected devices (2 available)
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 7.0 (API 24) (emulator)
    • iPhone X                     • 7D6D4BE2-0A99-40ED-9ECC-472CE5E212A6 • ios         • iOS 11.3 (simulator)
```

**Comment by jason-simmons** [comment] 2018-04-27 01:03
I can reproduce this on the latest engine.  I did notice that on my setup (Android/Nexus 5X) the text renders properly when `--enable-software-rendering` is active.

So it's apparently related to GPU accelerated text rendering in Skia.  I did notice that when the glyph fails to render Skia goes through the `glyph->fTooLargeForAtlas` code path in `GrAtlasTextBlob::appendGlyph` but then fails to find the path and exits.
    https://github.com/google/skia/blob/master/src/gpu/text/GrAtlasTextBlob.cpp#L93

Filed https://bugs.chromium.org/p/skia/issues/detail?id=7879

**Comment by GaryQian** [comment] 2020-03-26 22:08
It has been a long time since the last update,  and Skia has claimed to have fixed this. Can someone confirm this?

**Comment by iapicca** [comment] 2020-04-22 11:10
Hi @andreidiaconu @GaryQian 
I've tested the code on [dartpad](https://dartpad.dev/67e19f888145d7d7e7a1a812dd1896d0)
[android](https://user-images.githubusercontent.com/45637986/79974504-1e87b500-84a2-11ea-9ac2-15bad5662d67.png) and [ios](https://user-images.githubusercontent.com/45637986/79974986-e2088900-84a2-11ea-92ee-cece30ca8e2f.png)

I'm closing the issue as solved.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-04-22 11:10 UTC
Labels: a: typography, dependency: skia, engine, waiting for customer response
