### ISSUE TITLE
[Enhancement] Ability to trap and handle the OnSaveInstanceState on the Dart side

### ISSUE THREAD

**Issue by NathanaelA** [flutter/flutter#15478] opened 2018-03-13 09:48 UTC
I have developed a plugin in the past for NativeScript that I would like to try and convert to Flutter; this plugin works with small to very extremely large images.   And allows you to make annotations, text, and simple shapes to them.   At this moment the plugin allows you to manually trigger the save, and traps some of the standard android & ios events.  The first one that I can see is a problem is the onSaveInstanceState, which is used to do a final save of all annotations if the image hasn't been saved after the last set of changes yet.

Flutter currently does not support the `onSaveInstanceState` because it has no ability to do Sync messages; a related issue to this is #6827 but the solution to that does not work for this process because of the size of the images.    

- If I am either am saving after each annotation with a really large image it is going to just kill the cpu and battery on the device, and complicate the undo ability as now I have to waste a lot of disk space for each undo; (and then delete them all when a "real" save occurs) where undo in memory is fairly trivial.
- If I am tossing a large image over the pipe/message to the native oem side to hang onto (until a save occurs); I will be wasting a tremendous amount of memory and be likely to cause out of memory issues when they now are dealing with the two times the memory from images from the 12mp cameras...

The best solution to this; is to actually save on demand when the request comes in from the user or the OS.    I can handle the save from the user easily.  ;-)      But I can't handle the standard OS message; that can't be handled in Flutter without the ability to do Sync events like https://github.com/flutter/engine/pull/4358 would fix.

cc: @Hixie

**Comment by lukaspili** [comment] 2018-03-13 20:36
My opinion is biased (cf #6827) but this is an honest question: 

Why did you decide to save/restore the whole annotated images rather than just the annotations data (list of coordinates, shapes, colours, order, etc) and redraw all transformations on original image on restart?
Also I don't see how your undo feature would work after state restoration, if you only save/restore the modified image without the logical data that would allow to only undo the last annotation.

**Comment by NathanaelA** [comment] 2018-03-13 21:39
Good question Lukas,

Because the image is then used in other apps; so the final image needs to end up on disk at the point the app is terminated.    

In the event of a crash/termination; the undo buffer is gone.   I had saved it in the past and replayed it to the point against the original image; but this confused the end users -- so that feature was actually disabled by default in the plugin by request of the client...   I tend to prefer the replay buffer, but the client is always right.  :grinning:

The biggest issue here; is that the only event that work reliably to deal with large amounts of data saving is onSaveInstanceState (even though, technically, I'm not really saving instance state so much as just saving a new image).   OnPause caused too many perf hits to be used reliably.    The `onStop` and `onDestroy` events can also be used; however, they are also is Synchronous events.  So in my opinion using the `onSaveInstanceState` is a best hook to use in this case as it is fired when it knows it is going away and the current instance state needs to be saved.    I'm not opposed to `onStop` being used; but it still needs some sort of proper Sync support to be used properly so that I can save before the app terminates under my feet.

**Comment by lukaspili** [comment] 2018-03-26 22:32
Your use case seems different from #6827. As you said you don't need a mechanism to save/restore the app state using the native mechanics, but rather a reliable way to perform an operation that's guaranteed to complete, when app goes to background or is getting killed. For android for instance, you don't actually need to synchronously manipulate the `bundle` object from `onSaveInstanceState/onRestoreInstante`. 

That being said, it's a valid use case and I don't see any good solution to solve it with the current stack.

**Comment by Hixie** [comment] 2018-11-28 00:51
Dupe of https://github.com/flutter/flutter/issues/6827

**Closed by Hixie** 2018-11-28 00:51 UTC
Labels: customer: crowd, f: routes, framework, severe: customer critical, severe: new feature

**Comment by NathanaelA** [comment] 2018-11-28 04:59
@Hixie - Please re-open -- This is different than #6827 even though it could use the same underlying event as #6827 if it was supported in flutter.   If you solve #6827 internally; it will probably be something tied to the routing and components, not actual sync support; which may or may not work for this.    At the point #6827 is solved then we can see if the solution their will work; otherwise it is a different *related* issue.

This issue needs the ability to handle doing its own work when the app is being stopped.   As I mentioned earlier it technically "abuses" the `onSaveInstanceState` and actually probably is more valid on the `onStop` callback.  However, because it saves I tend to equate it with `onSaveInstanceState` rather than `onStop`.   But if it helps to clarify it for you.  We can pretend I never mentioned `onSaveInstanceState` and this is purely for `onStop` event.   ;-)

**Comment by Hixie** [comment] 2019-01-06 22:36
Please feel free to open a new bug; the original bug as filed, though, is a dupe of #6827, since it's about saving instance state.
