### ISSUE TITLE
Weird bars in Text widget next to 3 dots of TextOverflow.ellipsis

### ISSUE THREAD

**Issue by aytunch** [flutter/flutter#92283] opened 2021-10-21 20:32 UTC
This happens in Web but not in Android (iOS not tested). 

In Android Emulator:
![Screenshot_1634848250](https://user-images.githubusercontent.com/6442915/138352338-666a9db3-4517-4b83-be01-1304f0036a65.png)

In Chrome:
![IMG_0694E9E6FB72-1](https://user-images.githubusercontent.com/6442915/138351835-6b8d0ff3-2f53-4f01-8b3f-6f9b426ec2de.jpeg)
```
            Flexible(
              fit: FlexFit.loose,
              child: Text(
                //this regex trick allows for more text to be seen. Removing this does not solve the problem.
                restName.replaceAll("", "\u{200B}"),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: const TextStyle(
                  color: Color(0xFFFFFFFF),
                  fontFamily: 'SF_Pro_Display',
                  fontSize: 12,
                  fontWeight: FontWeight.w400,
                ),
              ),
            ),
```

**Comment by timovandeput** [comment] 2021-11-16 16:31
Likely a duplicate of https://github.com/flutter/flutter/issues/90135

**Closed** 2021-11-16 17:10 UTC
Labels: waiting for customer response, in triage
