### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Función incorrecta., errno = 1

### ISSUE THREAD

**Issue by MANR01** [flutter/flutter#123546] opened 2023-03-27 16:29 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: Función incorrecta.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1057:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:987:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1089:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:179:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.8, on Microsoft Windows [Versi¢n 10.0.22621.1105], locale es-MX)
    [32m•[39m Flutter version 3.7.8 on channel stable at E:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 90c64ed42b (6 days ago), 2023-03-21 11:27:08 -0500
    [32m•[39m Engine revision 9aa7816315
    [32m•[39m Dart version 2.19.5
    [32m•[39m DevTools version 2.20.1

[31m[✗][39m Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at E:\android-sdk-windows-1.6_r1\android-sdk-windows-1.6_r1
    [32m•[39m Platform android-33, build-tools 33.0.2
    [32m•[39m Java binary at: C:\Program Files\Java\jdk-11.0.17\bin\java
    [32m•[39m Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.4.4)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    [32m•[39m Visual Studio Build Tools 2022 version 17.4.33213.308
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at E:\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[33m[!][39m Android Studio
    [32m•[39m Android Studio at E:\android-sdk-windows-1.6_r1\android-sdk-windows-1.6_r1
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m android-studio-dir = E:\android-sdk-windows-1.6_r1\android-sdk-windows-1.6_r1
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.
    [32m•[39m Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[32m[✓][39m Connected device (4 available)
    [32m•[39m CPH2127 (mobile)  • b3eb9168 • android-arm64  • Android 12 (API 31)
    [32m•[39m Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Versi¢n 10.0.22621.1105]
    [32m•[39m Chrome (web)      • chrome   • web-javascript • Google Chrome 111.0.5563.111
    [32m•[39m Edge (web)        • edge     • web-javascript • Microsoft Edge 111.0.1661.54

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 90c64ed42ba53a52d18f0cb3b17666c8662ed2a0
### Plugins
facebook_auth_desktop-0.0.9
firebase_auth-4.3.0
firebase_auth_web-5.2.10
firebase_core-2.8.0
firebase_core_web-2.2.2
flutter_facebook_auth-5.0.8
flutter_facebook_auth_web-4.1.1
flutter_native_splash-2.2.19
flutter_plugin_android_lifecycle-2.0.9
flutter_secure_storage-8.0.0
flutter_secure_storage_linux-1.1.3
flutter_secure_storage_macos-3.0.0
flutter_secure_storage_web-1.1.1
flutter_secure_storage_windows-2.0.0
google_sign_in-6.0.2
google_sign_in_android-6.1.8
google_sign_in_ios-5.6.1
google_sign_in_web-0.11.0+2
image_cropper-3.0.1
image_cropper_for_web-1.0.3
image_picker-0.8.7
image_picker_android-0.8.6+6
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+1

**Comment by darshankawar** [comment] 2023-03-28 06:05
Closing as duplicate of https://github.com/flutter/flutter/issues/66224

**Closed by darshankawar** 2023-03-28 06:05 UTC
Labels: in triage
