### ISSUE TITLE
Infinite loop in TextFormField with onChanged callback on backspace (iOS)

### ISSUE THREAD

**Issue by WinnLeong** [flutter/flutter#69082] opened 2020-10-27 05:03 UTC
### **Steps to Reproduce**

I implemented the following function to format my TextFormField input. The input field goes into infinite loop when backspace is pressed where it repeatedly removes and adds the last character. This issue only occurs on iOS and works fine on Android. I did not encounter this issue prior to upgrading to the latest flutter version. This issue is similar to [#13961](https://github.com/flutter/flutter/issues/13961) and [#12347](https://github.com/flutter/flutter/issues/12347)

<details>
<summary>complete code sample</summary>

  ```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: InputFormatTest(title: 'Test'),
    );
  }
}

class InputFormatTest extends StatefulWidget {
  InputFormatTest({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _InputFormatTestState createState() => _InputFormatTestState();
}

class _InputFormatTestState extends State<InputFormatTest> {
  final controller = TextEditingController();
  String fieldValue = '';

  @override
  void initState() {
    super.initState();

    controller.addListener(controllerValue);

    setState(() {
      controller.text = '0.00';
    });
  }

  controllerValue() {
    controller.selection = TextSelection.fromPosition(
        TextPosition(offset: controller.text.length));

    setState(() {
      fieldValue = controller.text;
    });
  }

  Future<String> formatInputValue({@required controller}) async {
    final formatter = NumberFormat('#,##0.00');
    List<String> amountList = [];
    String dot = '.';
    String amount = '';

    amountList = List<String>.from(controller.text.split(''));

    amountList.removeWhere((item) => item == dot);

    if (amountList.length > 2) {
      amountList.insert(controller.text.length - 3, dot);
    }
    if (amountList.length == 2) {
      amountList.insert(0, '0');

      amountList.insert(controller.text.length - 2, dot);
    } else if (amountList[0] == '0' && amountList.length > 2) {
      amountList.remove('0');
    }

    amount = amountList.join();
    controller.text =
        formatter.format(double.tryParse(amount.replaceAll(',', '')));

    return controller.text;
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        FocusScopeNode currentFocus = FocusScope.of(context);

        if (!currentFocus.hasPrimaryFocus) {
          currentFocus.unfocus();
        }
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            children: <Widget>[
              Container(
                margin: EdgeInsets.symmetric(horizontal: 10),
                child: TextFormField(
                  cursorWidth: 0,
                  controller: controller,
                  keyboardType: TextInputType.numberWithOptions(decimal: true),
                  onChanged: (value) async {
                    // This will be triggered indefinitely when backspace is pressed
                    if (controller.text.isEmpty) {
                      controller.text = '0.00';
                    } else {
                      var result =
                          await formatInputValue(controller: controller);

                      controller.text = result;
                    }
                  },
                ),
              ),
            ],
          ),
        ), 
      ),
    );
  }
}

```

</details>

### **Flutter Doctor**

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-MY)
    • Flutter version 1.22.2 at /Users/tbsdevp/flutter
    • Framework revision 84f3d28555 (11 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tbsdevp/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 1236BC34-CAAA-4872-9660-D3F25C97B845
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```

**Comment by pedromassangocode** [comment] 2020-10-27 11:26
Hi @WinnLeong 
I need you to provide a minimal complete reproducible code sample that I can just copy/paste to reproduce the issue.
Thank you

**Comment by WinnLeong** [comment] 2020-10-28 00:46
Hi @pedromassango 

Apologies for that. I have modified my code sample, just let me know if there is anything else I can provide.

**Comment by pedromassangocode** [comment] 2020-10-28 09:17
Hi @WinnLeong 
I was not to reproduce the issue.

![gif](https://user-images.githubusercontent.com/67424416/97416283-87932e00-1906-11eb-8730-4a800b940f17.gif)

Can you provide clear steps to reproduce the issue?

**Comment by WinnLeong** [comment] 2020-10-28 09:50
Hi @pedromassangocode 

I'm surprised you didn't get the issue! Using the exact code sample this is what I got.


![loop](https://user-images.githubusercontent.com/38973968/97420021-bb417880-1945-11eb-89bc-6ff05e90c7b1.gif)

**Comment by pedromassangocode** [comment] 2020-10-28 12:33
Hi @WinnLeong 
I just tried to reproduce the same way you did and still can't reproduce.

![gif](https://user-images.githubusercontent.com/67424416/97435718-1d3bb700-1921-11eb-8917-05bc3ada9426.gif)

What device/OS are you using?

**Comment by WinnLeong** [comment] 2020-10-30 00:36
@pedromassangocode

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-30 at 08 32 36](https://user-images.githubusercontent.com/38973968/97646443-a9b5b900-1a8a-11eb-8115-be3b4d997edd.png)

I am using iPhone SE 2nd Generation simulator with iOS 14.0

**Comment by pedromassangocode** [comment] 2020-10-30 10:12
Looks like I was not using the stable channel (1.22.2). 

I can confirm that the issue reproduces on latest `stable` channel however it does not reproduce on latest `beta`, `dev` and `master` channels.

| stable | beta, dev, master|
|------|------|
|<img width="230" height="500" src="https://user-images.githubusercontent.com/67424416/97692861-9ada0100-1aa0-11eb-8eea-944147fb48b1.gif">|<img width="240" height="510" src="https://user-images.githubusercontent.com/67424416/97435718-1d3bb700-1921-11eb-8917-05bc3ada9426.gif">|

**Comment by justinmc** [comment] 2020-10-30 18:24
There has not been a cherry pick discussion for it as far as I'm aware.  I didn't think that it was a regression when I was working on it, are we sure that it is?  I'm on board with cherry picking if it's important enough.

**Comment by LongCatIsLooong** [comment] 2021-03-21 00:34
Closing since this issue seems no longer producible.

**Closed by LongCatIsLooong** 2021-03-21 00:34 UTC
Labels: a: text input, found in release: 1.22, framework, has reproducible steps, platform-ios
