### ISSUE TITLE
tapping on DropDownButton widget makes TextFormField with a focus node gets focused 

### ISSUE THREAD

**Issue by yazanIbrahim** [flutter/flutter#54683] opened 2020-04-13 19:33 UTC
i have a form text field widget with a focus node and a drop down down button inside a form, the problem am facing is when i tap on the drop down button the text field gets focused and the keyboard shows up. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16556544/79153388-7190a680-7dd6-11ea-89b1-6d47d9162be0.gif)

code snippet:
https://gist.github.com/yazanIbrahim/fa36c25bc0f7b415f6b2179007714336?fbclid=IwAR3IaQOSaso73kJjA8ldOfMCVUCcoVDojXjV-kZgwy15ng5ESTiRZm0btWQ

**Comment by imeDevelopers** [comment] 2020-04-13 23:05
i think it is because you are using key: in the Form() widget , try remove it from Form() widget and add it in the SingleChildScrollView() widget ...

or you are just using column inside another column .. and when you press on the drop down menu it simply make setState((){}); on the tree , and when the tree are refreshed .. flutter try to focus on first widget and here its the textfield .. try to put the DropDownFormField() before the textfield() with Positioned() inside Stack() instead of Column() and tell me ..

**Comment by imeDevelopers** [comment] 2020-04-14 16:37
replace InputField() with TextField() ..

remove this line : titleFocusNode.addListener(onTitleFocus);

use `onTap:` inside `TextField()` instead ..

replace `onSaved:` in `InputField()` with `onEditingCompleted:` in `TextField()` ...

and `_book.title = value` in the `onEditingCompleted:` with `_book.title = titleController.text;`

**Comment by yazanIbrahim** [comment] 2020-04-14 17:22
> i think it is because you are using key: in the Form() widget , try remove it from Form() widget and add it in the SingleChildScrollView() widget ...
> 
> or you are just using column inside another column .. and when you press on the drop down menu it simply make setState((){}); on the tree , and when the tree are refreshed .. flutter try to focus on first widget and here its the textfield .. try to put the DropDownFormField() before the textfield() with Positioned() inside Stack() instead of Column() and tell me ..

i have tries this but same results, nothing changed

**Comment by yazanIbrahim** [comment] 2020-04-14 17:24
> replace `InputField()` with `TextField()` ..
> 
> remove this line : `titleFocusNode.addListener(onTitleFocus);`
> 
> use `onTap:` inside `TextField()` instead ..
> 
> replace `onSaved:` in `InputField()` with `onEditingCompleted:` in `TextField()` ...
> 
> and `_book.title = value` in the `onEditingCompleted:` with `_book.title = titleController.text;`

i tried this solution, but the text field still getting focused and when selecting one of the drop down options the textfield is focused again and the keyboard shows up 

here is my code 
https://gist.github.com/yazanIbrahim/c87ac306eb6d4860dc9135d06a583ec9

**Comment by imeDevelopers** [comment] 2020-04-14 19:20
Remove key from Form()..

Return scaffold directly instead of View()...

Remove setstate from onchaged in the drop menu ...

**Comment by imeDevelopers** [comment] 2020-04-14 19:28
Add dropdown() before text field() with positioned() in stack()

**Comment by yazanIbrahim** [comment] 2020-04-14 20:40
> Remove key from Form()..
> 
> Return scaffold directly instead of View()...
> 
> Remove setstate from onchaged in the drop menu ...

i updated my guest and removed all logic from this page, now it's a simple scaffold that has a text field and a drop down button with no state changes , and the problem still exist

**Comment by darshankawar** [comment] 2020-07-08 12:52
Hi @yazanIbrahim,
Can you please confirm if you still experience this issue on latest Flutter channel (eg : dev, master) ? If so, can you provide a minimal complete reproducible code sample ? The gist you shared earlier seem to have lot of other code pieces.

**Comment by TahaTesser** [comment] 2020-08-05 14:36
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-05 14:36 UTC
Labels: f: material design, framework
