### ISSUE TITLE
Flutter test driver break TextField

### ISSUE THREAD

**Issue by polenchheang** [flutter/flutter#17472] opened 2018-05-10 13:45 UTC
## Steps to Reproduce

1. run: `flutter create --with-driver-test my_project`
2. Notice that `enableFlutterDriverExtension();` inside `main.dart` main method
3. Add TextField to your UI
4. Keyboard won't show when you click TextField
5. remove `enableFlutterDriverExtension();` Keyboard show as expected.

## Logs

```
[  +16 ms] [/home/polen/Flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/home/polen/Flutter/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [/home/polen/Flutter/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/home/polen/Flutter/flutter/] git log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 21c2e47f29ec8aaf14f8b137de941bb5aa89d6de
[        ] [/home/polen/Flutter/flutter/] git log -n 1 --pretty=format:%ar
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 31 hours ago
[        ] [/home/polen/Flutter/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +53 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.4.2-16-g21c2e47
[  +60 ms] "flutter run" took 10ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:427)
<asynchronous suspension>
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:251)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:323)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:222)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:42)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:49)
#30     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#31     main (file:///home/polen/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

```
Analyzing /home/polen/workspaces/flutter/test_project...
No issues found!
Ran in 6.2s

```

```
No issues found!
Ran in 6.2s
[polen@polen-dmi test_project]$ flutter doctor -v
[✓] Flutter (Channel master, v0.4.3-pre.16, on Linux, locale en_GB.UTF-8)
    • Flutter version 0.4.3-pre.16 at /home/polen/Flutter/flutter
    • Framework revision 21c2e47f29 (31 hours ago), 2018-05-08 23:23:34 -0700
    • Engine revision 11d6da3cd9
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/polen/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/polen/Android/Sdk
    • Java binary at: /home/polen/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/polen/Android/android-studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.0)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.12.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

• No issues found!

```

**Comment by dbenninger** [comment] 2018-08-06 11:39
Yes, I can confirm this is still an issue with flutter v0.5.1

**Comment by polenchheang** [comment] 2018-08-29 14:57
Hi @zoechi, sorry for late reply. Issue is still happen on `Flutter 0.7.3-pre.26 • channel master` .
Note: that you need to rebuild the App after you add `enableFlutterDriverExtension();` to see the issue.

**Comment by zoechi** [comment] 2018-08-29 15:40
@polenchheang thanks a lot for the update.

**Comment by ROTGP** [comment] 2018-10-07 10:30
I just lost hours on this. It essentially blocks me from implementing integration testing on a package I'm developing.

**Comment by weixfeng** [comment] 2019-01-04 01:48
I also just spent a few hours on this issue.  Hi @zoechi, this is a blocking issue for us.  Do you have any workaround or ETA on the fix?

**Comment by ROTGP** [comment] 2019-02-06 09:22
@zoechi any progress regarding this issue? It's been open for 9 months and seems to be a blocker. Not being able to perform integration testing essentially prevents us from releasing our app. I'm on Flutter v1.0.0 (stable channel) and the issue as described by @polenchheang continues to exist. After enableFlutterDriverExtension() is called, the keyboard refuses to appear and no text can be entered into the textfield.

**Comment by zoechi** [comment] 2019-02-08 11:37
@ROTGP @weixfeng @ shihchanghsiungsonos 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by jonahwilliams** [comment] 2019-03-10 20:11
I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/15415, which has more information.

**Closed by jonahwilliams** 2019-03-10 20:11 UTC
Labels: severe: crash, t: flutter driver, tool
