### ISSUE TITLE
(1-line code sample) TextField caret in wrong place with trailing spaces

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#58366] opened 2020-05-31 12:10 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Project',
        home: Scaffold(
            appBar: AppBar(title: Text('test')),
            body: Container(
                child: TextField(
              controller: TextEditingController(text: 'A\nB'), // can delete this line and enter A\nB manually
              keyboardType: TextInputType.multiline, // can delete this line
              maxLines: null, // or any value
            ))));
  }
}
```
3. First put the caret at the end of the first line (after "A"). Then use keyboard to input a "space" (or many spaces). Then you will see that, the caret is still near the "A" instead of being farther away.

**Expected results:** 

The caret should move right after entering spaces. That is how it behaves normally in Android and iOS system apps.

**Actual results:** 

It does not.

<img width="465" alt="截屏2020-05-31下午8 09 31" src="https://user-images.githubusercontent.com/5236035/83351926-ace13780-a37a-11ea-89f4-deccfd55dbca.png">

<details>
  <summary>Logs</summary>

```
GitHub complains that "Comment is too long (maximum is 65536 characters)"... Thus I cannot paste it here...
```

```
no errors.
```

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.3 19D76, locale
    zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/tom/opt/flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

Checking Android licenses is taking an unexpectedly long time...

[p.s. The environment is ok and I have run many applications successfully :) ]
```

</details>

**Comment by iapicca** [comment] 2020-06-01 13:47
Hi @fzyzcjy 
the behaviour seems to be incorrect also on android ad web
[code sample](https://dartpad.dev/81fb3d76e59adb3587e2f80ad085b5cd)
<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.19.0-2.0.pre.214, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-2.0.pre.214 at /Users/nevercode/development/flutter_master
    • Framework revision 1d395c5e18 (23 hours ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

thank you

**Comment by fzyzcjy** [comment] 2020-06-01 14:07
@iapicca Thanks! By the way, I wonder how much time, as a rough estimation, will the bug be fixed?

**Comment by YeungKC** [comment] 2020-10-20 19:37
I'm using master channel and can't reproduce it on both web mac and Android iOS simulator.

Maybe this has been fixed, please re-test.

cc @iapicca

**Comment by iapicca** [comment] 2020-10-20 20:32
@YeungKC good catch 👍🏻 
even on dartpad seems to be fixed

@TahaTesser please consider closing the issue

**Comment by fzyzcjy** [comment] 2020-10-21 00:49
Sounds great! I have not tested it on my machine yet. So shall I close it or wait for @TahaTesser

**Comment by TahaTesser** [comment] 2020-10-22 11:12
Hi @fzyzcjy 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-10-22 11:12 UTC
Labels: P4, a: text input, f: material design, found in release: 1.19, framework, has reproducible steps
