### ISSUE TITLE
flutter run hangs on project made with flutter create

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#5398] opened 2016-08-15 18:17 UTC
## Steps to Reproduce

On the iOS simulator...

```
flutter create new-project
cd new-project/
flutter run
```

Wait 1 minute and nothing has occurred. The app icon is not present on the simulator.

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision abeb5c7363 (10 minutes ago), engine revision fe509b0d96

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.34
```

## Logs and Crash Reports

```
new-project$ flutter run
Running lib/main.dart on iPhone 5s...
```
No additional output after a minute

**Comment by drewwarren** [comment] 2016-08-15 18:18
flutter run does work fine on flutter/examples/**. Only new projects are hanging for me.

**Comment by sethladd** [comment] 2016-08-15 18:20
Thanks for the report! We'll take a look.

**Comment by Hixie** [comment] 2016-08-16 19:37
This is iOS only. It works fine if you're targetting Android.

**Comment by collinjackson** [comment] 2016-08-16 19:38
Todd can repro this, but it doesn't happen for me.

It works fine if you open the xcworkspace with Xcode and build it. Only flutter run builds seem to be affected.

May have something to do with CocoaPods, I uninstalled my CocoaPods but still can't repro it.

**Comment by collinjackson** [comment] 2016-08-16 19:39
@tvolkert

**Comment by Hixie** [comment] 2016-08-16 19:44
I can confirm that after opening the project in xcode and changing the application name from "com.yourcompany.testapp" to "ch.hixie.testapp" (to match my developer key) it works. I guess that's a dupe of https://github.com/flutter/flutter/issues/5256 ?

**Comment by collinjackson** [comment] 2016-08-16 19:45
@hixie I don't think so... opening up the project with Xcode fixes it, which makes me think it's this:

 http://stackoverflow.com/questions/34123017/xcodebuild-command-line-hangs

**Comment by Hixie** [comment] 2016-08-16 20:01
I see, this is a more specific example (#5256 is just about trying to give guidance when this class of issue occurs).

**Closed** 2016-08-16 21:00 UTC
Labels: ⌺‬ platform-ios, ⚠ bug (regression)
