### ISSUE TITLE
Inconsistent caret position when typing emojis into TextField

### ISSUE THREAD

**Issue by hugocbpassos** [flutter/flutter#31818] opened 2019-04-30 00:35 UTC
Open any `TextField` and type "abc", then type the rainbow flag emoji. The caret will be displayed **before** the emoji. The fields `baseOffset` and `extentOffset` of `TextSelection` hold the correct value, so if you type another letter, it will be correctly displayed at the end of the `TextField`.

This depends on the emoji. If instead of the rainbow flag you were to type the pirate flag, the caret would be displayed at the beginning, before the letter "a".

It seems to me that emojis that are comprised of multiple code points make Flutter confused.

Perhaps these issues are related, but I'm not sure:
https://github.com/dart-lang/language/issues/34
https://github.com/dart-lang/language/issues/49

**Comment by HansMuller** [comment] 2019-04-30 15:58
CC @GaryQian

**Comment by VladyslavBondarenko** [comment] 2020-07-29 08:51
Hi @hugocbpassos,
I can't reproduce this

>Open any TextField and type "abc", then type the rainbow flag emoji. The caret will be displayed before the emoji. The fields baseOffset and extentOffset of TextSelection hold the correct value, so if you type another letter, it will be correctly displayed at the end of the TextField.

With current master `1.21.0-6.0.pre.90` on Android 9 device and iOS 13.6 simulator 

but https://github.com/flutter/flutter/issues/50563 still seems to be actual, please follow up on it, closing current issue

**Closed by VladyslavBondarenko** 2020-07-29 08:51 UTC
Labels: a: text input, framework
