### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by dajyaretakuya** [flutter/flutter#79756] opened 2021-04-05 03:48 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. I am using Flutter 2.0.4 to create a web app.
2. After create the app using the project initial command, I tried to run the app and the chrome is started up with a blank page.
3. About 10 seconds later the app crashed.

## Logs
HttpException
```
Connection closed before full header was received, uri = http://localhost:51958/json
```
```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale
    zh-Hans)
    • Flutter version 2.0.4 at /Volumes/ssd2/builds/flutter
    • Framework revision b1395592de (3 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Volumes/ssd2/applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b1395592de68cc8ac4522094ae59956dd21a91db

**Comment by iapicca** [comment] 2021-04-05 07:35
possible duplicate of https://github.com/flutter/flutter/issues/73743

**Comment by pedromassangocode** [comment] 2021-04-05 09:14
This seems to be a duplicate of https://github.com/flutter/flutter/issues/79748 as well.

**Closed by pedromassangocode** 2021-04-05 09:14 UTC
Labels: passed first triage, severe: crash, tool
