### ISSUE TITLE
RawImage is broken on iOS on Flutter 1.12.2

### ISSUE THREAD

**Issue by jlahd** [flutter/flutter#44988] opened 2019-11-15 14:05 UTC
## Steps to Reproduce

1. Use the RawImage widget on a Flutter application.

RawImage works on Flutter 1.12.1 on all platforms (Android/iOS/Web). On 1.12.2, Android and Web still work, but on iOS the image is not drawn at all.

A minimalistic test program is attached.
[main.zip](https://github.com/flutter/flutter/files/3851763/main.zip)

**Target Platform:** iOS
**Target OS version/browser:** 13.2
**Devices:** iPhone 6s

## Logs

```
[✓] Flutter (Channel master, v1.12.2-pre.52, on Mac OS X 10.15.1 19B88, locale en-FI)
    • Flutter version 1.12.2-pre.52 at /Users/jussi/flutter
    • Framework revision 6deb5b51b9 (4 hours ago), 2019-11-15 05:01:17 -0500
    • Engine revision be139a5b94
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jussi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Jussi Lahdenniemi’s iPad • 76835f818f7383ae846437a59d348dc5baab9b4c • ios • iOS 13.1.3
    • iPhone (Jussi)           • 2785ca011c4fedfd0766146800cee39102b90775 • ios • iOS 13.2

• No issues found!
```

**Comment by jmagman** [comment] 2019-11-19 01:25
This is a duplicate of https://github.com/flutter/flutter/issues/45098.  This was opened first, but that has the TODAY label on it and has already been mentioned in [Bad Builds](https://github.com/flutter/flutter/wiki/Bad-Builds#v1123---present).

**Closed by jmagman** 2019-11-19 01:25 UTC
Labels: a: images, framework, severe: rendering, ⌺‬ platform-ios
