### ISSUE TITLE
on running FirebaseAuth.instance.signOut();   throwing the error "Failed assertion: line 3803 pos 12: '_history.isNotEmpty': is not true."

### ISSUE THREAD

**Issue by useit4me** [flutter/flutter#60176] opened 2020-06-24 06:17 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment] 2020-06-24 08:20
Hi @useit4me 
From the little I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-24 08:20 UTC
