### ISSUE TITLE
flutter_plugin_android_lifecycle : The plugin `flutter_plugin_android_lifecycle` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.

### ISSUE THREAD

**Issue by HappyGhostz** [flutter/flutter#52293] opened 2020-03-10 03:09 UTC
Add Flutter to existing app
I created a flutter module for my Android project and embedded it into an existing Android project according to the official documentation. Everything was ready, but when I added the `flutter_plugin_android_lifecycle: ^ 1.0.6` plugin to the `pubspec.yaml` file, I got A hint
```
Running "flutter pub get" in flutter_lift_test...                   1.7s
The plugin `flutter_plugin_android_lifecycle` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.
Process finished with exit code 0
```

pubspec.yaml set:

```
version: 1.0.1+1 environment: sdk: ">=2.1.0 <3.0.0" flutter: ^1.12.13+hotfix.5
```

flutter doctor -v
```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G3020, locale en)
    • Flutter version 1.12.13+hotfix.5 at /Users/chenping.zhao/flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/chenping.zhao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/chenping.zhao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.1.4
    • Dart plugin version 192.6817.14

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.132
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```
 As long as the flutter project is integrated into the existing Androidx project, then the flutter project depends on flutter_plugin_android_lifecycle, this will happen

**Comment by TahaTesser** [comment] 2020-03-10 09:01
Duplicate of [#47153](https://github.com/flutter/flutter/issues/47153)

**Closed by TahaTesser** 2020-03-10 09:01 UTC
