### ISSUE TITLE
Handle thread merging (platform views) with engines that shared components

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#73620] opened 2021-01-09 00:23 UTC
Thread merging on one engine after it has spawned from another could lead to multiple threads accessing shared resources from different engines.

![image](https://user-images.githubusercontent.com/30870216/104077173-75b6ec80-51cd-11eb-9889-c057898c23c3.png)

Looks like a short term "fix" would be to create a new ExternalViewEmbedder that returns false to "SupportsDynamicThreadMerging" and crashes with an appropriate message.  It looks like the best way to actually solve the issue is to share the RasterThreadMerger between the engines.  The way it is implemented is that the external view embedder asks it if it is merged when a platform view is present, if not it merges it.  So, the first engine that runs into a platform view will just merge it.

We should attempt a full fix if it becomes difficult we can just do the crash/message for now.

**Comment by gaaclarke** [comment] 2021-01-12 00:48
I think this might not be a problem actually.  

If you have 2 different engines and they both have a resource that is meant to be communicated to on the raster thread, if one of the engines communicates with it on the raster thread and another engine communicates to it on the union of the raster thread and the platform thread, it's still safe.

The code would look something like this:
```
dispatch_async(raster_queue, ^{
  dispatch_sync(platform_queue, ^{
    shared_raster_resource->DoSomething();
  });
});
```

If another engine did:
```
dispatch_async(raster_queue, ^{
  shared_raster_resource->DoSomething();
});
```

@iskakaushik can you verify that the raster thread merger behaves as the union of the mutually exclusive regions of the platform and raster thread?  I imagine it has to be implemented that way.

**Comment by iskakaushik** [comment] 2021-01-12 17:59
@gaaclarke in the scenario you've described it wouldn't be a problem because for something that's meant to run on the raster thread if it's run on the platform thread, we should be fine. There could be a problem if one of the engine un-merges the union, which could lead to problems. The API IIRC is something along the lines of `MergeWithLease`, the problem is that if the threads are already merged, we do not seem to extend the lease, if we changed the `RasterThreadMerger` to do that I think we will be good.

Example Scenario:

1. Frame 0 (F0): (Engine-1) E1 merge threads.
2. F0: Threads will stay merged for 5 frames. (F1 to F5 inclusive)
3. F5: E2 merge threads.
4. F5: `RasterThreadMerger::MergeWithLease` notices that threads are already merged and does nothing.
5. F6: Threads are un-merged now. This is a problem as some of E2s tasks that are meant to run on platform thread will now be serviced on the raster thread.

**Comment by gaaclarke** [comment] 2021-01-14 23:19
I was able to verify that platform views don't work with engines with shared components with the following prototype:
![platformview-shared](https://user-images.githubusercontent.com/30870216/104660584-b0ac9a80-567b-11eb-88d4-a09245828e2d.PNG)

Once a platform view is added to one of the engines the other one stops animating and the following error is printed out:
`2021-01-14 15:07:53.671714-0800 LightweightStress[707:178033] [VERBOSE-2:gpu_surface_metal.mm(87)] Canvas not available.`

I'll investigate a fix.

**Comment by gaaclarke** [comment] 2021-01-15 01:54
Beyond the rendering issues after a merge happens I've found that `Rasterizer::Draw` is no longer called on the other engine that wasn't merged.  `Animator::BeginFrame` is continuing to to be called for both engines, so somehow it's not getting sent to the Rasterizer.

Handling rasterizer messages requires reading Dart_CurrentDartIsolate which is effectively a global variable.  It may be that that global variable is mixed up.  I'll spend tomorrow investigating it more, otherwise just crash for now.

**Comment by tylorvan** [comment] 2021-06-07 02:28
> Beyond the rendering issues after a merge happens I've found that `Rasterizer::Draw` is no longer called on the other engine that wasn't merged. `Animator::BeginFrame` is continuing to to be called for both engines, so somehow it's not getting sent to the Rasterizer.
> 
> Handling rasterizer messages requires reading Dart_CurrentDartIsolate which is effectively a global variable. It may be that that global variable is mixed up. I'll spend tomorrow investigating it more, otherwise just crash for now.

How is it going now? When is the problem planned to be fixed？

**Comment by gaaclarke** [comment] 2021-06-07 17:08
@tylorvan can you give me some information on your use case?  Could you not turn the problem inside-out and host multiple flutter instances inside of a host view?  Instead of hosting multiple flutter instances with host views inside of them?

**Comment by tylorvan** [comment] 2021-06-08 04:03
> @tylorvan can you give me some information on your use case? Could you not turn the problem inside-out and host multiple flutter instances inside of a host view? Instead of hosting multiple flutter instances with host views inside of them?

Sometimes, we need use flutter page as drawer, which maybe from bottom、right above a native page. A typical situation, in our player page，the whole page contains a native player on z-Index bottom，above them we use mutli flutter instance as different drawer，which shows just select page, promotion page and so on.

In drawer, we need use platform view show some native component,  in addition sometime flutter widget need cover the platformview widget. Furthermore the component can not change to pure flutter implementaion easily. it depends on many native view, and some native page deps on it too. It will bring too much extra unnessary effort.

**Comment by eggfly** [comment] 2021-07-23 15:26
> @gaaclarke in the scenario you've described it wouldn't be a problem because for something that's meant to run on the raster thread if it's run on the platform thread, we should be fine. There could be a problem if one of the engine un-merges the union, which could lead to problems. The API IIRC is something along the lines of `MergeWithLease`, the problem is that if the threads are already merged, we do not seem to extend the lease, if we changed the `RasterThreadMerger` to do that I think we will be good.
> 
> Example Scenario:
> 
> 1. Frame 0 (F0): (Engine-1) E1 merge threads.
> 2. F0: Threads will stay merged for 5 frames. (F1 to F5 inclusive)
> 3. F5: E2 merge threads.
> 4. F5: `RasterThreadMerger::MergeWithLease` notices that threads are already merged and does nothing.
> 5. F6: Threads are un-merged now. This is a problem as some of E2s tasks that are meant to run on platform thread will now be serviced on the raster thread.

@iskakaushik I can see that the `ExtendLeaseTo()` function will be called in the current master branch code, when rasterizer detected that there're platform layers.

fml/raster_thread_merger.cc 

```c
void RasterThreadMerger::ExtendLeaseTo(size_t lease_term) {
  if (TaskQueuesAreSame()) {
    return;
  }
  std::scoped_lock lock(lease_term_mutex_);
  FML_DCHECK(IsMergedUnSafe()) << "lease_term should be positive.";
  if (lease_term_ != kLeaseNotSet &&
      static_cast<int>(lease_term) > lease_term_) {
    lease_term_ = lease_term;
  }
}
```

So that's ok for this point?
And I take some time trying to make a PR for this: https://github.com/flutter/engine/pull/27662
Happy and waiting for more discussions.

**Comment by eggfly** [comment] 2021-08-07 02:38
This issue should be solved by this PR: https://github.com/flutter/engine/pull/27662

**Closed** 2021-08-09 12:47 UTC
Labels: engine, customer: gold, passed first triage, P5
