### ISSUE TITLE
Floating point issue in PageView extent calculation causes the next page to sometimes build

### ISSUE THREAD

**Issue by miyoyo** [flutter/flutter#63689] opened 2020-08-13 18:47 UTC
## Steps to Reproduce

Using an app with [this code](https://hastebin.com/huqamifocu.dart) and selecting, for example, tile 6, will show that tile 7 also animates it's hero.

A simple, temporary fix is to give a **tiny** bit of overflow to the viewportFraction, such as `1.000001`

**Expected results:** 
Only "Tile 6" animates to take position in the middle of the screen
**Actual results:**
["Tile 7" *also* animates to take place to the left of the screen](https://youtu.be/Bi7cc6dDIcU)

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-BE)
    • Flutter version 1.20.1 at C:\tools\flutter
    • Framework revision 2ae34518b8 (8 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\hidden\AppData\Local\Android\SDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\hidden\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • Redmi 3S (mobile)            • c3fadefd7d33  • android-arm64 • Android 9 (API 28)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by markusaksli-nc** [comment] 2020-08-14 06:34
Reproducible on the latest master `1.21.0-10.0.pre.94`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.94, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.94 at C:\Development\flutter_master
    • Framework revision 58feba8edd (65 minutes ago), 2020-08-13 21:16:04 -0700
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

Need to scroll and try it out a couple of times to find a page that reproduces the issue. Not sure what the root cause is here but no idea how to reduce the sample code to a minimal case.

**Comment by markusaksli-nc** [comment] 2020-08-14 06:36
Also reproducible on 1.17.5 so it's not a regression. Can't find anything issues it could be a duplicate of though.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel unknown, v1.17.5, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.17.5 at C:\Development\flutter_1.17.5
    • Framework revision 8af6b2f038 (6 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows            • Windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Chrome             • chrome             • web-javascript • Google Chrome 84.0.4147.125
    • Web Server         • web-server         • web-javascript • Flutter Tools

• No issues found!
```
</details>

**Comment by chunhtai** [comment] 2020-08-17 21:21
I saw a blank page when i open the link, can you paste the cod here?

**Comment by miyoyo** [comment] 2020-08-17 21:23
```dart
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  timeDilation = 10;
  runApp(
    MaterialApp(
      home: TestPage(),
    ),
  );
}

class ColorHolder {
  final Color color =
      Colors.primaries[Random().nextInt(Colors.primaries.length)];
}

class ColorTile extends StatefulWidget {
  final ColorHolder holder;
  final List<ColorHolder> holders;

  ColorTile(this.holder, this.holders);

  @override
  State<StatefulWidget> createState() {
    return _ColorTile();
  }
}

class _ColorTile extends State<ColorTile> {
  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Positioned.fill(
            child: Hero(
          tag: 'holder_${widget.holders.indexOf(widget.holder)}',
          child: Container(
            color: widget.holder.color,
            child: Center(
              child: Text('Tile ${widget.holders.indexOf(widget.holder) + 1}',
                  style: DefaultTextStyle.of(context).style),
            ),
          ),
        ))
      ],
    );
  }
}

class ColorScreen extends StatefulWidget {
  final List<ColorHolder> posts;
  final int startingIndex;

  const ColorScreen(this.posts, this.startingIndex);

  @override
  State<StatefulWidget> createState() {
    return _ColorScreenState();
  }
}

class _ColorScreenState extends State<ColorScreen> {
  @override
  Widget build(BuildContext context) {
    PageController controller =
        PageController(initialPage: widget.startingIndex, viewportFraction: 1);

    Widget _pageBuilder(BuildContext context, int index) {
      print('opening page ${index + 1}');
      if (index < widget.posts.length) {
        return ColorTile(widget.posts[index], widget.posts);
      } else {
        return null;
      }
    }

    return PageView.builder(
      pageSnapping: true,
      physics: AlwaysScrollableScrollPhysics(),
      controller: controller,
      itemCount: widget.posts.length,
      itemBuilder: _pageBuilder,
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _TestPageState();
  }
}

class _TestPageState extends State<TestPage> {
  List<List<ColorHolder>> _pages = [];

  void _loadNextPage() {
    List<ColorHolder> nextPage = [];
    print('loading page ${_pages.length}');
    for (int i = 0; i < 50; i++) {
      nextPage.add(ColorHolder());
    }

    WidgetsBinding.instance.addPostFrameCallback((_) {
      setState(() {
        _pages.add(nextPage);
      });
    });
  }

  int _itemCount() {
    int i = 0;
    if (_pages.isEmpty) {
      _loadNextPage();
    }
    for (List<ColorHolder> p in _pages) {
      i += p.length;
    }
    return i;
  }

  Widget _itemBuilder(BuildContext context, int item) {
    Widget preview(List<ColorHolder> page, int pageIndex, int listIndex) {
      List<ColorHolder> pages = _pages
          .fold<Iterable<ColorHolder>>(
              Iterable.empty(), (a, b) => a.followedBy(b))
          .toList();
      return Container(
        height: 250,
        child: InkWell(
          child: ColorTile(page[pageIndex], pages),
          onTap: () {
            Navigator.of(context).push(MaterialPageRoute<Null>(
              builder: (context) => Scaffold(
                appBar: AppBar(
                  title: Text('Test'),
                  leading: IconButton(
                    icon: Icon(Icons.arrow_back),
                    onPressed: () => Navigator.pop(context),
                  ),
                ),
                body: ColorScreen(pages, listIndex),
              ),
            ));
          },
        ),
      );
    }

    int posts = 0;

    for (List<ColorHolder> page in _pages) {
      if (page.isEmpty) {
        return null;
      }
      posts += page.length;
      if (item == posts - 1) {
        if (_pages.indexOf(page) == _pages.length - 1) {
          _loadNextPage();
        }
      }

      if (item < posts) {
        return preview(page, item - (posts - page.length), item);
      }
    }

    return null;
  }

  @override
  void didUpdateWidget(Widget oldWidget) {
    super.didUpdateWidget(oldWidget);
    setState(() {
      _pages.clear();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
        leading: IconButton(
          icon: Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: GridView.builder(
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: (MediaQuery.of(context).size.width / 200).round(),
        ),
        itemCount: _itemCount(),
        itemBuilder: _itemBuilder,
        physics: BouncingScrollPhysics(),
      ),
    );
  }
}
```

**Comment by ttencate** [comment] 2020-08-29 11:08
I think I'm seeing something similar on 1.17.1 where the _previous_ page is being built. Unfortunately it's not happening on any device that I have physical access to, so I can't confirm this any further. Just mentioning this in the hope that it'll provide a clue during bug hunting.

Also possibly related (or same issue): https://github.com/flutter/flutter/issues/60295#issuecomment-651040442

**Comment by xster** [comment] 2020-11-09 19:53
This looks like the same issue as https://github.com/flutter/flutter/issues/68182 which was fixed in https://github.com/flutter/flutter/pull/68199. Please feel free to re-open if incorrectly attributed. Otherwise, you can test this issue on master channel.

**Closed by xster** 2020-11-09 19:53 UTC
Labels: a: animation, f: scrolling, found in release: 1.17, found in release: 1.21, framework, has reproducible steps
