### ISSUE TITLE
Bug using toByteData on a PictureRecorder generated image

### ISSUE THREAD

**Issue by DavBfr** [flutter/flutter#23621] opened 2018-10-27 12:51 UTC
Using the Flutter master branch, this code fails to render the image:
```dart
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder, Rect.fromLTWH(0.0, 0.0, 100.0, 100.0));
    final paint = ui.Paint()..color = Colors.red;
    final data = base64.decode('R0lGODdhZABkAIACAAZ/fwzAwCwAAAAAZABkAAACroyPqcvtD6OctNqLs968+w+G4kiW5omm6sq27gvH8kzX9o3n+s73/g8MCofE4g6ATCqXzKbzCY1Kp9Sq9YrNarfcrvcLDovH5LL5jE6r1+y2+w2Py+f0uv2Oz+v3/L7/DxgoOEhYaHiImKi4yNjo+AgZKTlJWWl5iZmpucnZ6fkJGio6SlpqeoqaqrrK2ur6CjtmNEtba3uLm6u7y9vr+wscLDxMXGx8jJysvPxTAAA7');
    final codec = await ui.instantiateImageCodec(data);
    final frame = await codec.getNextFrame();
    canvas.drawImage(frame.image, ui.Offset.zero, paint);
    canvas.drawLine(Offset.zero, Offset(100.0, 100.0), paint);
    final picture = recorder.endRecording();
    final image = picture.toImage(100, 100);
    final imageBytes = await image.toByteData(format:ui.ImageByteFormat.png);
```
the resulting png only contains the line, but not the bitmap image (base64).
using `flutter run --enable-software-rendering` the bitmap image is rendered correctly.

This bug is not present using the Flutter tag v0.5.7, after that it stopped working.
It is related to #17687, and #21618

**Comment by DavBfr** [comment] 2018-10-27 13:33
```
[✓] Flutter (Channel master, v0.10.2-pre.82, on Mac OS X 10.14 18A391, locale en-CA)
    • Flutter version 0.10.2-pre.82 at /Users/me/Documents/Perso/flutter
    • Framework revision 0f34f52620 (9 hours ago), 2018-10-27 00:48:21 -0400
    • Engine revision 6c2a0b3a6d
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Android NDK at /Users/me/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)
```

**Comment by tvolkert** [comment] 2018-11-06 16:28
@DavBfr can you see if this still exists on master if you `flutter upgrade`?

**Comment by DavBfr** [comment] 2018-11-06 23:01
@tvolkert It still exists. I updated the doctor -v

**Comment by tvolkert** [comment] 2018-11-06 23:04
@chinmaygarde another case to look at

**Comment by VolodymyrLykhonis** [comment] 2018-11-23 04:08
Facing same issue. Text and primitives are rendered fine except images. The issue is not present on iOS. I observe the issue only on Android (both emulators and devices).

**Comment by fujingjunben** [comment] 2018-11-25 02:11
Sometimes, devices doesn't display image after picture.toImage.  flutter version: v0.11.9

**Comment by daanvandenhoek** [comment] 2018-11-29 11:17
Is there any update?

**Comment by tvolkert** [comment] 2018-11-29 15:23
@daanvandenhoek not yet. It's still on our radar, but we haven't had bandwidth to look at it yet.

**Comment by VolodymyrLykhonis** [comment] 2018-11-29 15:35
@tvolkert Is there a way for us (community) to upvote to prioritize this?

**Comment by tvolkert** [comment] 2018-11-29 15:40
Upvotes always help provide signal as to what the highest priority issues are, yes.  In this case, we already agree it should be fixed sooner rather than later - we just need to free up on other stuff we're working on 😄

**Comment by VolodymyrLykhonis** [comment] 2018-11-30 21:23
I went trough commits for v0.5.7 starting from [this page](https://github.com/flutter/engine/commits/master?after=7375a0f414bde4bc941e623482221db2fc8c4ab5+804). I did not notice something that would stand out to me as painting related changes for Android platform only. I see a number of skia updates, rest seems unrelated.

Folks familiar with the matter, if you could point where `canvas.drawImageRect` implementation deviates for Android in engine I could try to dig little more.

**Comment by tvolkert** [comment] 2018-11-30 21:33
@VolodymyrLykhonis if you're game, you could [set up the engine for building](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) and [compile it](https://github.com/flutter/flutter/wiki/Compiling-the-engine), then run with [`flutter --local-engine`](https://github.com/flutter/flutter/wiki/The-flutter-tool#using-a-locally-built-engine-with-the-flutter-tool) and bisect the commits to find out where this started happening.

**Comment by VolodymyrLykhonis** [comment] 2018-11-30 21:35
@DavBfr interesting. I do not see the issue with `canvas.drawImageRect` on iOS (both simulator and iPhone 6).

@tvolkert  I had outdated engine fork, will try to dig into this.

**Comment by dkashkin** [comment] 2018-12-07 20:39
I just bumped into the same issue with my app. The problem does not reproduce on iOS devices or simulator - only on Android. Images obtained from ui.instantiateImageCodec refuse to draw on Canvas. One interesting detail - if I load the same source image in any widget and use RenderRepaintBoundary.toImage in order to get the binary data then I am able to draw the image on Android Canvas. I tested this with several JPG and PNG images that had different encoding and none of them worked, so this cannot be blamed on some weird codec.

**Comment by VolodymyrLykhonis** [comment] 2018-12-21 18:02
Any updates on this from Flutter team? This is a launch blocker for the app I am working on for Android.

Last time I had time to look into this I was failing to build engine on OS X. May be able to revisit this in upcoming weeks.

**Comment by dikeboy** [comment] 2018-12-31 10:56
> Any updates on this from Flutter team? This is a launch blocker for the app I am working on for Android.
> 
> Last time I had time to look into this I was failing to build engine on OS X. May be able to revisit this in upcoming weeks.

I  have fixed it  like the  dkashkin 's suggest   ,
you can capture it  and  read the Uint8List
see my link https://github.com/dikeboy/flutter-image-cut

**Comment by VolodymyrLykhonis** [comment] 2019-01-06 19:56
@tvolkert I tried to follow guides to setup and build, but it simply either fails during linking on OS X or fails to launch x84 on Android emulator. x86 seems to be deprecated on OS X that leads to issues linking engine.

Are there any planning for this to be addressed, I don't think it's minor and should remain deprioritized.

**Closed** 2019-01-14 17:39 UTC
Labels: engine, severe: API break

**Comment by AnnatarHe** [comment] 2019-02-16 13:20
Has anyone checked this issue?

I am running on Flutter v1.1.8, it does not fixed.

**Comment by kangwang1988** [comment] 2019-02-16 14:24
@AnnatarHe 
Confirmed this issue is resolved using the latest master.
If you can reproduce it, please file a new issue with details to reproduce it.

**Comment by ZatacaSystems** [comment] 2019-04-26 19:27
Is there a way of saving that base64 string decoded image in a file and open it with the photo viewer of the so?
