### ISSUE TITLE
Out of Memory in process of Android app building

### ISSUE THREAD

**Issue by iBog** [flutter/flutter#66009] opened 2020-09-17 09:28 UTC
Details
Out of Memory bug in process of Android app building on Windows 10 PC

flutter -v doctor
```
[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [Version 10.0.19041.508], locale ru-BY)
    • Flutter version 1.22.0-12.1.pre at D:\Apps\flutter
    • Framework revision 8b3760638a (32 hours ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Apps\android-sdk-windows
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Apps\android-sdk-windows
    • Java binary at: D:\Apps\android-studio4\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Apps\android-studio4
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
```

**Target Platform:**
Windows 10 x64 (build 2004)

**Target OS version/browser:**
Android 10 (fat APK version with all ABI's included)
build.gradle :
  minSdkVersion 17
  targetSdkVersion 30

**Devices:**
Target device: Android Emulator (Android 10, API 29, Pixel 4 virtual device)
Emulator version: 30.0.26-6755297
## Logs

[idea_log.zip](https://github.com/flutter/flutter/files/5237964/idea_log.zip)

```
Running Gradle task 'assembleDebug'...
../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
version=2.10.0-110.3.beta (beta) (Tue Sep 15 14:39:26 2020 +0200) on "windows_x64"
pid=1604, thread=20596, isolate_group=main(000001FB99F231B0), isolate=main(000001FB99ED4940)
isolate_instructions=7ff7202af230, vm_instructions=7ff7202af240
  pc 0x00007ff720440058 fp 0x0000006eb75fcf30 Unknown symbol
-- End of DumpStackTrace
[exit     : sp(0) fp(0x6eb75fdd70) pc(0)]
[stub     : sp(0x6eb75fdd80) fp(0x6eb75fdda0) pc(0x1fb99801094)]
[dart     : sp(0x6eb75fddb0) fp(0x6eb75fddf8) pc(0x1fba278f8e2) dart:core__RegExp@0150898_hasMatch ]
[dart     : sp(0x6eb75fde08) fp(0x6eb75fde58) pc(0x1fba5e3b183) package:flutter_tools/src/android/gradle.dart_::_buildGradleApp__async_op_consumeLog ]
[dart     : sp(0x6eb75fde68) fp(0x6eb75fdea0) pc(0x1fba47191b8) package:flutter_tools/src/base/process.dart__DefaultProcessUtils@75014270_stream__async_op_<anonymous closure> ]
[dart     : sp(0x6eb75fdeb0) fp(0x6eb75fdf20) pc(0x1fba2788dc6) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75fdf30) fp(0x6eb75fdf98) pc(0x1fba2788c50) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75fdfa8) fp(0x6eb75fe040) pc(0x1fba2788766) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x6eb75fe050) fp(0x6eb75fe0d0) pc(0x1fba3e2fc83) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x6eb75fe0e0) fp(0x6eb75fe120) pc(0x1fba4717bf5) *dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x6eb75fe130) fp(0x6eb75fe160) pc(0x1fba3e2f5fd) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x6eb75fe170) fp(0x6eb75fe1a0) pc(0x1fba9b9b8f1) dart:async__ForwardingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x6eb75fe1b0) fp(0x6eb75fe210) pc(0x1fba5e16b38) dart:async__WhereStream@4048458__handleData@4048458 ]
[dart     : sp(0x6eb75fe220) fp(0x6eb75fe258) pc(0x1fba9b9b4a9) dart:async__ForwardingStreamSubscription@4048458__handleData@4048458 ]
[dart     : sp(0x6eb75fe268) fp(0x6eb75fe298) pc(0x1fba9b9b2cb) dart:async__ForwardingStreamSubscription@4048458__handleData@4048458__handleData@4048458 ]
[dart     : sp(0x6eb75fe2a8) fp(0x6eb75fe318) pc(0x1fba2788dc6) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75fe328) fp(0x6eb75fe390) pc(0x1fba2788c50) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75fe3a0) fp(0x6eb75fe438) pc(0x1fba2788766) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x6eb75fe448) fp(0x6eb75fe4c8) pc(0x1fba3e2fc83) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x6eb75fe4d8) fp(0x6eb75fe560) pc(0x1fba3e4efff) *dart:convert__LineSplitterSink@10003594__addLines@10003594 ]
[dart     : sp(0x6eb75fe570) fp(0x6eb75fe5b8) pc(0x1fba8f20057) dart:convert__LineSplitterSink@10003594_addSlice ]
[dart     : sp(0x6eb75fe5c8) fp(0x6eb75fe610) pc(0x1fba8f1fbee) dart:convert_StringConversionSinkMixin_add ]
[dart     : sp(0x6eb75fe620) fp(0x6eb75fe678) pc(0x1fba3e3480f) dart:async__SinkTransformerStreamSubscription@4048458__handleData@4048458 ]
[dart     : sp(0x6eb75fe688) fp(0x6eb75fe6b8) pc(0x1fba3e345fb) dart:async__SinkTransformerStreamSubscription@4048458__handleData@4048458__handleData@4048458 ]
[dart     : sp(0x6eb75fe6c8) fp(0x6eb75fe738) pc(0x1fba2788dc6) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75fe748) fp(0x6eb75fe7b0) pc(0x1fba2788c50) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75fe7c0) fp(0x6eb75fe858) pc(0x1fba2788766) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x6eb75fe868) fp(0x6eb75fe8e8) pc(0x1fba3e2fc83) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x6eb75fe8f8) fp(0x6eb75fe938) pc(0x1fba4717bf5) *dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x6eb75fe948) fp(0x6eb75fe978) pc(0x1fba3e2f5fd) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x6eb75fe988) fp(0x6eb75fe9b8) pc(0x1fba3e352e7) dart:async__SinkTransformerStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x6eb75fe9c8) fp(0x6eb75fe9f8) pc(0x1fba3e34ff6) dart:async__EventSinkWrapper@4048458_add ]
[dart     : sp(0x6eb75fea08) fp(0x6eb75fea38) pc(0x1fba3e4ae92) dart:convert__StringAdapterSink@10003594_add ]
[dart     : sp(0x6eb75fea48) fp(0x6eb75fea80) pc(0x1fba8f1f961) dart:convert__StringAdapterSink@10003594_addSlice ]
[dart     : sp(0x6eb75fea90) fp(0x6eb75feae0) pc(0x1fba8f1d9e9) dart:convert__Utf8ConversionSink@10003594_addSlice ]
[dart     : sp(0x6eb75feaf0) fp(0x6eb75feb38) pc(0x1fba8f1d7ae) dart:convert__Utf8ConversionSink@10003594_add ]
[dart     : sp(0x6eb75feb48) fp(0x6eb75feb78) pc(0x1fba3e34af6) dart:convert__ConverterStreamEventSink@10003594_add ]
[dart     : sp(0x6eb75feb88) fp(0x6eb75febe0) pc(0x1fba3e3480f) dart:async__SinkTransformerStreamSubscription@4048458__handleData@4048458 ]
[dart     : sp(0x6eb75febf0) fp(0x6eb75fec20) pc(0x1fba3e345fb) dart:async__SinkTransformerStreamSubscription@4048458__handleData@4048458__handleData@4048458 ]
[dart     : sp(0x6eb75fec30) fp(0x6eb75feca0) pc(0x1fba2788dc6) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75fecb0) fp(0x6eb75fed18) pc(0x1fba2788c50) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75fed28) fp(0x6eb75fedc0) pc(0x1fba2788766) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x6eb75fedd0) fp(0x6eb75fee50) pc(0x1fba3e2fc83) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x6eb75fee60) fp(0x6eb75feea0) pc(0x1fba4717bf5) *dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x6eb75feeb0) fp(0x6eb75feee0) pc(0x1fba3e2f5fd) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x6eb75feef0) fp(0x6eb75fef20) pc(0x1fba3e2f376) dart:async__SyncStreamController@4048458__sendData@4048458 ]
[dart     : sp(0x6eb75fef30) fp(0x6eb75fef60) pc(0x1fba3e2ceaa) dart:async__StreamController@4048458__add@4048458 ]
[dart     : sp(0x6eb75fef70) fp(0x6eb75fefa0) pc(0x1fba3e2cb3b) dart:async__StreamController@4048458_add ]
[dart     : sp(0x6eb75fefb0) fp(0x6eb75feff0) pc(0x1fba3e30012) dart:io__Socket@15069316__onData@15069316 ]
[dart     : sp(0x6eb75ff000) fp(0x6eb75ff030) pc(0x1fba3e2fe0b) dart:io__Socket@15069316__onData@15069316__onData@15069316 ]
[dart     : sp(0x6eb75ff040) fp(0x6eb75ff0b0) pc(0x1fba2788eef) dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75ff0c0) fp(0x6eb75ff128) pc(0x1fba2788c50) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x6eb75ff138) fp(0x6eb75ff1d0) pc(0x1fba2788766) dart:async__CustomZone@4048458_runUnary ]
[dart     : sp(0x6eb75ff1e0) fp(0x6eb75ff260) pc(0x1fba3e2fc83) dart:async__CustomZone@4048458_runUnaryGuarded ]
[dart     : sp(0x6eb75ff270) fp(0x6eb75ff2b0) pc(0x1fba4717bf5) *dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x6eb75ff2c0) fp(0x6eb75ff2f0) pc(0x1fba3e2f5fd) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x6eb75ff300) fp(0x6eb75ff330) pc(0x1fba3e2f376) dart:async__SyncStreamController@4048458__sendData@4048458 ]
[dart     : sp(0x6eb75ff340) fp(0x6eb75ff370) pc(0x1fba3e2ceaa) dart:async__StreamController@4048458__add@4048458 ]
[dart     : sp(0x6eb75ff380) fp(0x6eb75ff3b0) pc(0x1fba3e2cb3b) dart:async__StreamController@4048458_add ]
[dart     : sp(0x6eb75ff3c0) fp(0x6eb75ff3f0) pc(0x1fba3e2f1b3) dart:io__RawSocket@15069316__RawSocket@15069316._<anonymous closure> ]
[dart     : sp(0x6eb75ff400) fp(0x6eb75ff460) pc(0x1fba27d5fac) dart:core__Closure@0150898_dyn_call ]
[dart     : sp(0x6eb75ff470) fp(0x6eb75ff4b0) pc(0x1fba3e0aa3d) dart:io__NativeSocket@15069316_issueReadEvent_issue ]
[dart     : sp(0x6eb75ff4c0) fp(0x6eb75ff4f8) pc(0x1fba2785e03) dart:async_::__microtaskLoop@4048458 ]
[dart     : sp(0x6eb75ff508) fp(0x6eb75ff538) pc(0x1fba2785a64) dart:async_::__startMicrotaskLoop@4048458 ]
[dart     : sp(0x6eb75ff548) fp(0x6eb75ff568) pc(0x1fba278597b) dart:async_::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]
[dart     : sp(0x6eb75ff578) fp(0x6eb75ff5a8) pc(0x1fba2785833) dart:isolate_::__runPendingImmediateCallback@1026248 ]
[dart     : sp(0x6eb75ff5b8) fp(0x6eb75ff5d0) pc(0x1fb9ccb032d) dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
[entry    : sp(0x6eb75ff5e0) fp(0x6eb75ff6f8) pc(0x1fb99801598)]
```

**Comment by snape-here** [comment] 2020-09-18 16:20
I had the same issue after I updated Flutter to 1.20. But after I restarted my PC, it started working normally again. I feel like the cause might be high RAM usage of my System and therefore leaving no Memory for Dart to compile the app for execution.

**Comment by erickzanardo** [comment] 2020-09-18 21:26
Hi @iBog this happens on a specific application or if you try to compile a recently created app by `flutter create app` the error already happens? Also is this reproducible every time?

Increasing the memory of the gradle daemon could help too, have you tried anything like [this](https://stackoverflow.com/questions/47454257/how-to-increase-maximum-heap-size-for-the-gradle-daemon)?

**Comment by TahaTesser** [comment] 2020-10-14 13:20
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 13:20 UTC
