### ISSUE TITLE
Hero animation jumps when transitioning between Images with different fit

### ISSUE THREAD

**Issue by jrnelson333** [flutter/flutter#20510] opened 2018-08-13 00:00 UTC
Hero animations have a sudden jump when animating an image with two different `fit` values. It is very possible that Hero animations are not intended to work in this scenario. If that is the case, the documentation should clarify this. The example in the documentation says the following about fit. 

> Setting the Image’s fit property to BoxFit.contain, ensures that the image is as large as possible during the transition without changing its aspect ratio

This implies that the `BoxFit` does not have to be the same on each image.

## Steps to Reproduce

Below is an application that demonstrates the issue. This application is a modified version on the application [from the docs](https://flutter.io/animations/hero-animations/). In this application, the animation from screen 1 to screen 2 has a noticeable jump as the fit changes. However, the animation from screen 2 back to screen 1 animates perfectly.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart' show timeDilation;

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(primaryColor: Colors.white),
      home: new HeroAnimation(),
    );
  }
}

class HeroAnimation extends StatelessWidget {
  Widget build(BuildContext context) {
    timeDilation = 4.0;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Screen 1'),
      ),
      body: Container(
        child: PhotoHero(
          photo:
              'https://www.emanprague.com/en/wp-content/uploads/2018/05/flutter_eman_blog.png',
          width: 400.0,
          height: 500.0,
          fit: BoxFit.cover,
          onTap: () {
            Navigator.of(context).push(MaterialPageRoute<Null>(
                builder: (BuildContext context) {
                  return Scaffold(
                      appBar: AppBar(
                        title: const Text('Screen 2'),
                      ),
                      body: Center(
                        child: PhotoHero(
                          photo:
                              'https://www.emanprague.com/en/wp-content/uploads/2018/05/flutter_eman_blog.png',
                          fit: BoxFit.contain,
                          onTap: () {
                            Navigator.of(context).pop();
                          },
                        ),
                      ));
                },
                fullscreenDialog: true));
          },
        ),
      ),
    );
  }
}

class PhotoHero extends StatelessWidget {
  const PhotoHero(
      {Key key, this.photo, this.onTap, this.width, this.height, this.fit})
      : super(key: key);

  final String photo;
  final VoidCallback onTap;
  final double width;
  final double height;
  final BoxFit fit;

  Widget build(BuildContext context) {
    return SizedBox(
      width: width,
      height: height,
      child: Hero(
        tag: photo,
        child: Material(
          color: Colors.transparent,
          child: InkWell(
            onTap: onTap,
            child: Image.network(
              photo,
              fit: fit,
            ),
          ),
        ),
      ),
    );
  }
}
```

GIF:

<img src="https://user-images.githubusercontent.com/20613561/44007746-de559400-9e68-11e8-83ad-88f0fcd72bc3.gif" width="400">

Url to GIF: https://user-images.githubusercontent.com/20613561/44007746-de559400-9e68-11e8-83ad-88f0fcd72bc3.gif

**Comment by erf** [comment] 2019-02-15 14:09
I'm also experience this. Would love to see this fixed.

**Comment by AlexVincent525** [comment] 2019-05-11 08:57
When hero pop from `BoxFit.contain` to `BoxFit.cover` in `PageView`, it will scale to absolutly 100% width and 100% height. See #31543

**Comment by AlexVincent525** [comment] 2019-07-24 05:46
@LongCatIsLooong Any progress about this issue?

**Comment by chunhtai** [comment] 2019-07-31 22:52
This is by design. according to document https://api.flutter.dev/flutter/widgets/Hero-class.html
```
To make the animations look good, it's critical that the widget tree for the hero in both locations be essentially identical. The widget of the target is, by default, used to do the transition: when going from route A to route B, route B's hero's widget is placed over route A's hero's widget. If a flightShuttleBuilder is supplied, its output widget is shown during the flight transition instead.
```
The identical also include the attribute which the box fit. I can update the document if it is confusing.

The hero animation only change the parent box size and offset, it has no idea about how children render inside the box, and that is why we encourage to keep the child the same.

If this is not possible, you should build your own flightShuttleBuilder. For your example
```
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart' show timeDilation;

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(primaryColor: Colors.white),
      home: new HeroAnimation(),
    );
  }
}

class HeroAnimation extends StatelessWidget {
  Widget build(BuildContext context) {
    timeDilation = 4.0;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Screen 1'),
      ),
      body: Container(
        child: PhotoHero(
          photo:
          'https://www.emanprague.com/en/wp-content/uploads/2018/05/flutter_eman_blog.png',
          width: 400.0,
          height: 500.0,
          fit: BoxFit.cover,
          onTap: () {
            Navigator.of(context).push(MaterialPageRoute<Null>(
              builder: (BuildContext context) {
                return Scaffold(
                  appBar: AppBar(
                    title: const Text('Screen 2'),
                  ),
                  body: Center(
                    child: PhotoHero(
                      photo:
                      'https://www.emanprague.com/en/wp-content/uploads/2018/05/flutter_eman_blog.png',
                      fit: BoxFit.contain,
                      onTap: () {
                        Navigator.of(context).pop();
                      },
                    ),
                  ));
              },
              fullscreenDialog: true));
          },
        ),
      ),
    );
  }
}

class PhotoHero extends StatelessWidget {
  const PhotoHero(
    {Key key, this.photo, this.onTap, this.width, this.height, this.fit})
    : super(key: key);

  final String photo;
  final VoidCallback onTap;
  final double width;
  final double height;
  final BoxFit fit;

  Widget build(BuildContext context) {
    return SizedBox(
      width: width,
      height: height,
      child: Hero(
        flightShuttleBuilder: (
            BuildContext flightContext,
            Animation<double> animation,
            HeroFlightDirection flightDirection,
            BuildContext fromHeroContext,
            BuildContext toHeroContext,
          ) {
          final Hero hero = flightDirection == HeroFlightDirection.push ? fromHeroContext.widget : toHeroContext.widget;
          return hero.child;
        },
        tag: photo,
        child: Material(
          color: Colors.transparent,
          child: InkWell(
            onTap: onTap,
            child: Image.network(
              photo,
              fit: fit,
            ),
          ),
        ),
      ),
    );
  }
}
```

There is no plan to change the current behavior. Let me know if there is other use case that cannot be achieve by using flightShuttleBuilder.

**Comment by chunhtai** [comment] 2019-08-12 19:37
I will close this issue for now, feel free to reopen if this is still an issue

**Comment by jrnelson333** [comment] 2019-10-05 16:08
Thanks @chunhtai! I did not know about `flightShuttleBuilder`. This looks like a good solution.

**Closed** 2019-10-05 16:08 UTC
Labels: a: animation, a: quality, f: material design, framework

**Comment by cherrybiu** [comment] 2020-12-22 07:22
The `flightShuttleBuilder` will raise another problem. It will change its shape at the last moment which looks abrupt and strange.

**Comment by chaojian** [comment] 2021-07-27 02:24
> The `flightShuttleBuilder` will raise another problem. It will change its shape at the last moment which looks abrupt and strange.

can you fix this problem?
