### ISSUE TITLE
scroll jank when ListView  is used as ListView horizontal item

### ISSUE THREAD

**Issue by zmtzawqlp** [flutter/flutter#116765] opened 2022-12-09 08:15 UTC
i want to make a list can be scroll in both horizontal and vertical. something like following:

``` dart
ListView.builder(
      scrollDirection: Axis.vertical,
      itemBuilder: (b, index) {
   return ListView.builder(
        itemExtent: 25,
        scrollDirection: Axis.horizontal,
        itemBuilder: (b, index) {
          return SizedBox(
            width: 25,
            child: Text('$index'),
          );
        },
        itemCount: 20,
      );
}
```
but it's jank and only 38 FPS in profile mode.

and if i use singleScrollview, it's better, but it's not support huge items at horizontal.

full code are as following, you can change list1 to list, to see how jank if we use ListView.builder.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: list1,
    );
  }

  Widget get list => getList(SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          children: List<Widget>.generate(
              20,
              (index) => SizedBox(
                    width: 25,
                    child: Text('$index'),
                  )).toList(),
        ),
      ));

  Widget get list1 => getList(ListView.builder(
        itemExtent: 25,
        scrollDirection: Axis.horizontal,
        itemBuilder: (b, index) {
          return SizedBox(
            width: 25,
            child: Text('$index'),
          );
        },
        itemCount: 20,
      ));

  Widget getList(Widget item) {
    return ListView.builder(
      itemBuilder: (b, index) {
        return Container(
          height: 25,
          decoration: BoxDecoration(
              border: Border.all(
            color: Colors.grey,
          )),
          child: Row(
            children: <Widget>[
              Container(
                width: 25,
                color: Colors.blue,
              ),
              Expanded(child: item),
              Container(
                width: 25,
                color: Colors.yellow,
              )
            ],
          ),
        );
      },
      itemCount: 1000,
    );
  }
}

```

FPS use with ListView.builder
<img width="845" alt="截屏2022-12-09 15 44 08" src="https://user-images.githubusercontent.com/16477333/206654937-50a001c0-676b-48c2-b595-b0dc6305a38b.png">

FPS use with SingleScrollview
<img width="722" alt="截屏2022-12-09 15 42 36" src="https://user-images.githubusercontent.com/16477333/206655198-5c7ec88d-fd82-4739-9aa2-cfc6c189091f.png">

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/zmtzawqlp/Documents/flutter/3.3.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zmtzawqlp/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • ANDROID_HOME = /Users/zmtzawqlp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • MI 9 (mobile)   • f65dae09 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment] 2022-12-09 12:27
Thanks for the report. Using the code sample provided, I do see same performance behavior upon scrolling in profile mode. 

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.9 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (12 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-4.0.pre.48, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.7.0-4.0.pre.48 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eefbe85c8b (19 minutes ago), 2022-12-08 22:32:07 -0600
    • Engine revision 8d83b98c55
    • Dart version 3.0.0 (build 3.0.0-0.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>


May be related to:

https://github.com/flutter/flutter/issues/103847
https://github.com/flutter/flutter/issues/75399

**Comment by goderbauer** [comment] 2022-12-13 23:38
@Piinks

**Comment by Piinks** [comment] 2022-12-14 00:30
Hi @zmtzawqlp we are currently working on a native 2D scrolling widget, and tracking it in this project: https://github.com/orgs/flutter/projects/32 I am going to close this as a dupe of https://github.com/flutter/flutter/issues/87370, please follow updates there. Thank you!

**Closed by Piinks** 2022-12-14 00:30 UTC
Labels: framework, severe: performance, f: scrolling, has reproducible steps, found in release: 3.3, found in release: 3.7
