### ISSUE TITLE
[in_app_purchase] Documentation on "buyNonConsumable" out of date

### ISSUE THREAD

**Issue by Ephenodrom** [flutter/flutter#50357] opened 2020-02-07 20:41 UTC
Hello folks,

I am currently writing an app with in app purchases and I am not sure if this is a bug or i made something wrong.

Setup:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.2-pre.39, on Linux, locale de_DE.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.41.1)
[✓] Connected device (3 available)
• No issues found!

I use the following version of the package : 
```
in_app_purchase: ^0.3.0+3
```

Code : 
```dart
  Future<void> initStore() async {
    // Check for connection
    final bool isAvailable = await _connection.isAvailable();
    if (!isAvailable) {
      return;
    }
    // Start listening to incoming purchases
    _listenToPurchases();
    // Fetch PRO product details
    ProductDetailsResponse productDetailResponse =
        await _connection.queryProductDetails(_kProductIds.toSet());
    proProduct = productDetailResponse.productDetails.elementAt(0);
    // Check if PRO product is already purchased
    await _checkPurchased();
  }

  Future<void> _checkPurchased() async {
    bool inAppIsPro = false;

    final QueryPurchaseDetailsResponse purchaseResponse =
        await _connection.queryPastPurchases();
    if (purchaseResponse.error != null) {
      Logger(TAG).info(
          "Fetching past purchases was not succefull, ${purchaseResponse.error}");
      return;
    }
    Logger(TAG).info("Got ${purchaseResponse.pastPurchases.length} purchases");
    for (PurchaseDetails purchase in purchaseResponse.pastPurchases) {
      Logger(TAG).info("Got purchase with productId ${purchase.productID}");
      if (purchase.productID == PRODUCT_ID_PRO_VERSION) {
        inAppIsPro = true;
      }
    }

    // Do something
  }
```

After the first screen is loaded I display a loading animation an call the **initStore()** method. Then I wait until the method is finished before guiding the user to the next screen.

Every code works fine, i can load the product information i can make purchases and get informed via email about the purchase. But the lines
```dart
QueryPurchaseDetailsResponse purchaseResponse =
        await _connection.queryPastPurchases();
```
always return an empty list of past purchases.

What i do : 
1. Start the app
2. Buy the non consumable
3. Close the app
4. Start the app
5. Check for past purchase

Background information : 
- The app runs in debug mode
- The app runs on a normal device 
- I use a real playstore user for the purchase

Any idea whats wrong ?

Regards

**Comment by iapicca** [comment] 2020-02-10 10:57
Hi @Ephenodrom 
can you please provide your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by Ephenodrom** [comment] 2020-02-11 11:58
The bug was on my side. I did not confirm the purchase. That's why I always received an empty list for the past purchases.

**Comment by iapicca** [comment] 2020-02-12 09:31
I'm glad you solved the issue
thanks for letting me know @Ephenodrom

**Comment by Ephenodrom** [comment] 2020-02-12 09:58
It was quite complicate to find the problem, due to the fact that it does not matter if you confirm the purchase or not. In both cases the status of the purchase remains the same in the play console.

**Comment by Ephenodrom** [comment] 2020-02-13 19:54
@iapicca 
I also found out that the code documentation of the buyNonConsumable seems not to be up to date.

There is this line :
On iOS, you also need to call [completePurchase] to finish the purchasing process.

That's why i was not calling **completePurchase**.

**Comment by iapicca** [comment] 2020-02-14 11:50
Hi @Ephenodrom 
I'm going to hijack the issue if you don't mind
thank you for your contribution

**Comment by JayM96** [comment] 2020-05-24 05:59
@iapicca Can you tell me that is it necessary to call completepurchase for ios and consumePurchase for android method to call for completing subscriptions(non-consumable products) ?

**Comment by PramodJoshi** [comment] 2020-06-19 16:46
> @iapicca Can you tell me that is it necessary to call completepurchase for ios and consumePurchase for android method to call for completing subscriptions(non-consumable products) ?

I would really appreciate some clarification on this.

May be i misunderstood but i think In App Purchase README instructions are confusing and contradicting (explanation below).

<img width="928" alt="Screen Shot 2020-06-19 at 11 33 18 AM" src="https://user-images.githubusercontent.com/17320471/85157181-bf83b980-b220-11ea-8373-c1891f61be7c.png">

Screenshot above (of **Loading previous purchases** section) clearly states that **Only App Store requires final confirmation of `completePurchase(purchase)`** . Then again in **Complete a purchase** section states that `completePurchase(purchase)` is also required for Google Play as shown in the screenshot below.

<img width="928" alt="Screen Shot 2020-06-19 at 11 38 09 AM" src="https://user-images.githubusercontent.com/17320471/85157924-bba46700-b221-11ea-9f9f-5f1ee10732e6.png">

However, calling `completePurchase(purchase)` for Android/Google Play returns empty `pastPurchases` result. I was able to get `pastPurchases` result calling `consumePurchase(purchase)` instead of `completePurchase(purchase)` in Android.

Thanks!

**Comment by wetsanddan** [comment] 2020-06-30 03:06
I am glad this plugin exists, but I'm going to second that the docs were confusing whether completePurchase was required for App Store or GooglePlay or both. Also it doesn't help that the best tutorial example is also out of date. 

I would love to see a best practice version of an example for a single-purchase nonConsumable such as a one-time in-app upgrade. I managed to put something together but since it hasn't been 3 days I'm not sure if I did the completePurchase stuff right yet. :)

**Comment by stuartmorgan** [comment] 2021-07-27 17:47
@cyanglaz @mvanbeusekom Was this addressed in the docs updates?

**Comment by mvanbeusekom** [comment] 2021-07-28 08:31
Hi @stuartmorgan, 

In my opinion this is indeed addressed in the docs update. The README.md now mentions:

>**Completing a purchase**
>
>The InAppPurchase.purchaseStream will send purchase updates after you initiate the purchase flow using InAppPurchase.buyConsumable or InAppPurchase.buyNonConsumable. After delivering the content to the user, call InAppPurchase.completePurchase to tell the App Store and Google Play that the purchase has been finished.

Also we created the [code lab](https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases) which is a very detailed tutorial on using the in_app_purchase plugin. Chapter 7 discusses making a purchase and handling the result which also mentions you should always complete the purchase.

**Comment by stuartmorgan** [comment] 2021-07-28 09:33
Great, closing as fixed.

**Closed by stuartmorgan** 2021-07-28 09:33 UTC
Labels: P4, documentation, p: first party, p: in_app_purchase, plugin
