### ISSUE TITLE
[Proposal] Access Primary Scroll Controller in nested Navigator

### ISSUE THREAD

**Issue by SuhwanCha** [flutter/flutter#95836] opened 2021-12-27 03:59 UTC
## Use case

When using nested Router, primary scroll controller is not worked. So, Scrolling Screenshot(Android), Tap to scroll top(iOS) aren't worked.
It's because in nested router, context doesn't point to root context, so `PrimaryScrollController.of(context)` is primary scroll controller for nested router, not whole application.

I.E
- Scaffold
  -  Navigator
     - SingleChildScrollView
        - PrimaryScrollController <-- it point to Navigator's Primary Scroll Controller

So, we have to pass Controller as parameter like https://github.com/flutter/flutter/issues/85603#issuecomment-876798161

## Proposal

Be able to use
```dart
PrimaryScrollController.of(Navigator.of(context, rootNavigator: true).context);
```
or
https://github.com/flutter/flutter/blob/f4a44a9d6867dfefa8adceecafa35694e47f8df1/packages/flutter/lib/src/widgets/primary_scroll_controller.dart#L62

Change this code to PrimaryScrollController always use root's context.

or, add parameter on primary scroll controller
```dart
PrimaryScrollController.of(context, rootNavigator: true);
```
if rootNavigator is true, primary scroll controller use root's context

**Comment by SuhwanCha** [comment] 2021-12-27 08:37
https://medium.com/@suhw4n/flutter-tab-to-scroll-top-on-nested-navigation-b176cc759921
Here's my solution for now..

**Comment by maheshmnj** [comment] 2021-12-27 10:50
Hi @SuhwanCha, I ran the below code sample from the linked issue, I am unable to reproduce the issue. In nested navigation scroll state seems to be maintained.  Let me know if I am missing anything and please share output of `flutter doctor -v` and share a minimal and complete code sample to reproduce the issue.


https://user-images.githubusercontent.com/31410839/147464401-82bd053b-f18b-4b2a-82f0-3eb1e8b258e8.mov


 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MainPage(),
    );
  }
}

class MainPage extends StatefulWidget {
  const MainPage({Key? key}) : super(key: key);

  @override
  _MainPageState createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> {
  final _navigatorKey = GlobalKey<NavigatorState>();
  int currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    // Grab the top most controller
    final ScrollController controller = PrimaryScrollController.of(context)!;

    return Scaffold(
      body: IndexedStack(
        index: currentIndex,
        children: [
          TapBodyWidget(
            listName: 'A',
          ),
          Navigator(
            key: _navigatorKey,
            initialRoute: 'B',
            onGenerateRoute: (settings) => MaterialPageRoute<dynamic>(
              builder: (context) {
                return TapBodyWidget(listName: 'B', controller: controller);
              },
              settings: settings,
            ),
          )
        ],
      ),
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        unselectedItemColor: Colors.black,
        selectedItemColor: Colors.blue,
        selectedLabelStyle: TextStyle(
          color: Colors.blue,
          fontWeight: FontWeight.bold,
        ),
        unselectedLabelStyle: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.bold,
        ),
        currentIndex: currentIndex,
        onTap: (index) => setState(() => currentIndex = index),
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.favorite_border),
            label: 'TAB A',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.bookmark),
            label: 'TAB B',
          ),
        ],
      ),
    );
  }
}

class TapBodyWidget extends StatelessWidget {
  const TapBodyWidget({Key? key, required this.listName, this.controller})
      : super(key: key);
  final String listName;
  final ScrollController? controller;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.separated(
          controller: controller,
          itemBuilder: (context, index) {
            return ListTile(
              tileColor: Colors.red[100 * (index % 9 + 1)],
              title: Text('$listName :  $index'),
              trailing: Icon(Icons.chevron_right),
              onTap: () => Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (context) => TapBodyWidget(
                    listName: '$listName:$index',
                    controller: controller,
                  ),
                ),
              ),
            );
          },
          separatorBuilder: (context, index) => Divider(),
          itemCount: 100),
    );
  }
}


```
</details>
 
 <details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (11 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 45FE8AD8-94DA-4F94-B52B-81102B1B42E7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by SuhwanCha** [comment] 2021-12-28 01:00
Hi, @maheshmnj 

In your code, it works but TapBodyWidget received ScrollController as parameter.
In this solution, passing ScrollController might be cumbersome.
So, I propose there will be option to directly access PrimaryScrollController in nested widget.

For example,
```dart
PrimaryScrollController.of(Navigator.of(context, rootNavigator: true).context);
```

**Comment by maheshmnj** [comment] 2021-12-28 06:56
Ah, I get it now, @SuhwanCha Thanks for the clarification that makes sense.

**Comment by SuhwanCha** [comment] 2021-12-31 06:28
Thank you, @maheshmnj 
Because I’m not familiar with open source contribution, so I just would like to if do I have to wait or can I make PR now.

**Comment by maheshmnj** [comment] 2021-12-31 06:45
@SuhwanCha You are open to submitting a PR and make sure to link this issue in your PR description.

**Comment by mark8044** [comment] 2022-01-02 03:45
This has been a source of immense suffering for the better part of 6 months for me and is holding up my app release in that time.

Heres to hoping a fix is coming 🙏    Not being able to scroll up in a tabbed application doesn't look good right now

**Comment by SuhwanCha** [comment] 2022-01-02 23:31
@maheshmnj 
Hello, I created PR. Can you review it and request reviewing to other org members?
Thanks

**Comment by maheshmnj** [comment] 2022-01-03 04:57
> @maheshmnj
Hello, I created PR. #96012 Can you review it and request reviewing to other org members?

I am not the right person, Please wait until someone reviews it, or you may reach out to team members on discord in Hackers new channel https://github.com/flutter/flutter/wiki/Chat.

**Comment by maheshmnj** [comment] 2022-01-03 05:14
cc: @Piinks

**Comment by Piinks** [comment] 2022-01-04 17:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/85603

**Closed by Piinks** 2022-01-04 17:16 UTC
Labels: severe: new feature, platform-ios, framework, waiting for PR to land (fixed), f: scrolling, f: routes, proposal, passed first triage
