### ISSUE TITLE
flutter add-to-app sample build error

### ISSUE THREAD

**Issue by 4dcity** [flutter/flutter#46884] opened 2019-12-12 15:49 UTC
I open the anroid_fullscreen project in add-to-app sample, at first the build failed with error log below:

```
FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/will/Documents/dev/project/samples/experimental/add_to_app/android_fullscreen/settings.gradle' line: 4

* What went wrong:
A problem occurred evaluating settings 'AndroidFullScreen'.
> /Users/will/Documents/dev/project/samples/experimental/add_to_app/flutter_module/.android/include_flutter.groovy (/Users/will/Documents/dev/project/samples/experimental/add_to_app/flutter_module/.android/include_flutter.groovy)
```

then I add an import statement due to the hint 
`import javax.naming.Binding`
this time the build failed with an different error:
```
FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/will/Documents/dev/project/samples/experimental/add_to_app/android_fullscreen/settings.gradle' line: 5

* What went wrong:
A problem occurred evaluating settings 'AndroidFullScreen'.
> Could not find which method <init>() to invoke from this list:
    public javax.naming.Binding#<init>(java.lang.String, java.lang.String, java.lang.Object, boolean)
    public javax.naming.Binding#<init>(java.lang.String, java.lang.String, java.lang.Object)
    public javax.naming.Binding#<init>(java.lang.String, java.lang.Object, boolean)
    public javax.naming.Binding#<init>(java.lang.String, java.lang.Object)
```
Does anyone knows what's wrong?

below is the flutter doctor info:

[✓] Flutter (Channel master, v1.13.1-pre.99, on Mac OS X 10.15.1 19B2106, locale zh-Hans-CN)
    • Flutter version 1.13.1-pre.99 at /Users/will/Documents/dev/flutter
    • Framework revision 354f80b84a (15 hours ago), 2019-12-11 16:36:03 -0800
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/will/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by xster** [comment] 2019-12-12 22:12
umm we haven't see this one before. I can't repro locally. Perhaps @blasten may have some thoughts

**Comment by blasten** [comment] 2019-12-13 03:17
I’m not sure why it was needed to add an import. It might help if you could share the steps to reproduce this issue starting from `flutter create -t module`. Which file did you modify?

**Comment by blasten** [comment] 2020-01-04 01:12
Duplicate of https://github.com/flutter/flutter/issues/41350

**Closed by blasten** 2020-01-04 01:12 UTC
Labels: a: existing-apps, t: gradle, tool, waiting for customer response, ▣ platform-android
