### ISSUE TITLE
TextPainter behavior no longer matches Text behavior, when useMaterial3 is true

### ISSUE THREAD

**Issue by allenbrunson** [flutter/flutter#141172] opened 2024-01-09 14:44 UTC
### Steps to reproduce

i wrote myself a function, textPainterFromText(), which just copies all the data and parameters from a Text widget, and uses them to create a TextPainter. the purpose is so that i can know ahead of time how large a Text object will be, in pixels, once it is added to a widget tree. this worked fine for many years. but if a Flutter app has a ThemeData with useMaterial3 set to true, then the sizing data reported by TextPainter is no longer correct.

i created a demo app that demonstrates this behavior, and the differences i see, when useMaterial3 is set to true or false. [you can find that demo here](https://github.com/allenbrunson/text_painter_demo). it includes screen-shots and the steps to take to reproduce the behavior i am seeing.

### Expected results

my hope is that the pre-material3 behavior would be restored, and the size reported by TextPainter would once again exactly match the size behavior of Text widgets. if that is not possible, perhaps someone could suggest a workaround.

### Actual results

the size reported by TextPainter objects does not match Text widgets, if useMaterial3 is true.

### Code sample

<details open><summary>Code sample</summary>

```
https://github.com/allenbrunson/text_painter_demo
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    • Flutter version 3.16.5 on channel stable at /Users/allen/local/dart/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/allen/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/allen/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/allen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment] 2024-01-09 15:40
Hello @allenbrunson.
Thanks for filing this. I can reproduce this on the latest `master` and `stable` channels. Not certain if this is the expected behaviour or not though, I'll be labelling this for more insights.

| useMaterial3: true | useMaterial3: false |
|--------|--------|
| <img src="https://github.com/flutter/flutter/assets/53122008/adb4e5e3-b09c-406a-9749-288895c578ae"> | <img src="https://github.com/flutter/flutter/assets/53122008/6251d832-4c5d-4514-903a-21829eafcb14"> | 

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.16.5 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 (mobile)          • F17D2919-6D61-4295-8408-1719692FE958 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 
```
[!] Flutter (Channel master, 3.18.0-19.0.pre.122, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.18.0-19.0.pre.122 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f7f437ce2a (3 hours ago), 2024-01-09 11:05:06 +0200
    • Engine revision 820645dbcc
    • Dart version 3.4.0 (build 3.4.0-4.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Damilola’s iPhone (mobile) • 00008110-001964480AE1801E            • ios            • iOS 17.1.1 21B91
    • iPhone 15 (mobile)         • F17D2919-6D61-4295-8408-1719692FE958 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by jason-simmons** [comment] 2024-01-28 22:14
This app appears to be configuring the `TextPainter` by extracting the `style` attribute from a `Text` widget.

That style may be inheriting properties from the `DefaultTextStyle` that is currently in scope.  The `Text` widget's style will need to be merged with the `DefaultTextStyle` style to create a style that will match the `Text` when used in a `TextPainter`.

Some of the Material 3 theme styles specify properties like `letterSpacing` and `height`.  If these properties are not merged into the style given to the `TextPainter`, then the size computed by the `TextPainter` will differ from the `Text`.

**Comment by allenbrunson** [comment] 2024-01-30 06:32
okay, that points me in the right direction! but i spent several hours trying to implement a change like this, without success.

i see that i can call DefaultTextStyle.of() to get the object that is in scope. but, what do i do with it? am i applying this to the style that i get out of the Text object? i don't see how. i can see a DefaultTextStyle.merge() that i could call, but that returns a Widget, not a new TextStyle.

or am i supposed to apply the DefaultTextStyle to the Text object as i am putting it into the widget tree? based on your description, it sounds like that is already being done automatically. so that doesn't sound right.

so, what next?

**Comment by jason-simmons** [comment] 2024-01-30 16:55
`TextStyle.merge` can be used to combine the default text style and the `Text` widget's style.

See https://api.flutter.dev/flutter/painting/TextStyle/merge.html

**Comment by allenbrunson** [comment] 2024-02-02 17:49
okay, i tried the suggested fix. i would summarize my changes like this:

1) modify textPainterFromText() to take a BuildContext as an input parameter
2) use that BuildContext to get the DefaultTextStyle in scope
3) merge the Text object's TextStyle with DefaultTextStyle.style

alas, it did not work. i tried doing the merge both ways: Text's TextStyle merged with the one from DefaultTextStyle, and vice versa. both ways produced different sets of numbers, and both were wrong. (heh)

but! that got me to thinking. this confirms for me that, as i suspected, Text and TextPainter are now getting their defaults from different places. so, how about this: every TextStyle i create will have enough of their parameters filled in so that the defaults no longer matter.

that, i am happy to say, did work. specifically, any TextStyle without height and letterSpacing parameters will have them set to 1.0 and 0.0, respectively. (other local defaults will likely also work.)

yeah, i might have to update this list in the future, if you guys decide to change the defaults. this feature is important enough to me that i am happy to do so.

i updated my demo app so that it contains both attempted fixes. they are both turned off by default. that link again, in case you forgot: [text_painter_demo](https://github.com/allenbrunson/text_painter_demo)

and i am working on a blog post, attempting to justify why i need this. i will put it here now, in case this issue gets closed to further comments: [Text versus TextPainter](https://allenbrunson.com/posts/text-versus-textpainter/)

i am not going to close this issue, because as far as i am concerned, this is very much a bug. Text and TextPainter used to be equivalent. now they are not. it violates the principle of least surprise. i couldn't find the issue stated exactly this way when i searched the bug database, but i am pretty sure that i am far from the only guy who has been bitten by this.

if it's the maintainers' position that this is not a bug, then i guess you guys should close it, as "won't fix."

**Comment by LongCatIsLooong** [comment] 2024-02-06 21:43
>  the purpose is so that i can know ahead of time how large a Text object will be, in pixels, 

By "ahead of time" do you mean the width/height of the text needs to determined before the `Text` widget's render object (`RenderParagraph`) actually lays out the text? I'm interested in what your use case is. If that is not the case, `RenderParagraph.size` roughly reflects the size of the paragraph.

**Comment by allenbrunson** [comment] 2024-03-04 15:42
whoops, sorry, i missed this somehow.

my use case is using brute-force pixel-counting to do layouts. yes, i know that there are better ways for almost all situations, like putting children into a Row or Column with weighted flex values, and so on. i can't always make that work, for some of my more complicated layouts. in particular, not knowing how tall a multi-line Text object will be is a killer. so i put my Text objects inside TextPainter objects to get their size, so i am better able to make intelligent layout decisions.

**Comment by LongCatIsLooong** [comment] 2024-03-05 01:02
Trying to replicate the Text widget's internal text theming / layout logic is not recommended as that subjects to future changes, and it can get complicated very fast. If you want another widget to be as tall as a Text widget, as you said, generally a multi child container widget would be the preferred solution. What depends on the height of the Text widget in your UI?

**Comment by tony-ditchlabs** [comment] 2024-03-25 16:14
I ran into a related issue this morning with this widget:

```
import 'package:flutter/material.dart';

/// Wraps a [textSpan] in a [Tooltip], but only if the text would overflow.
///
/// Creates a [Text.rich] widget with [textSpan], and passes in the other
/// [Text] arguments as-is. If the [Text.rich] widget cannot be contained in
/// the constraints without overflowing, then it's wrapped in a [Tooltip] with
/// a corresponding [message].
class OverflowTextTooltip extends StatelessWidget {
  /// The styled Text, likely a [TextSpan].
  final InlineSpan textSpan;

  /// The tooltip message to show. The full text of [textSpan].
  final String message;

  final int? maxLines;
  final TextAlign textAlign;
  final TextOverflow? overflow;

  const OverflowTextTooltip({
    super.key,
    required this.textSpan,
    required this.message,
    this.maxLines,
    this.textAlign = TextAlign.start,
    this.overflow,
  });

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final painter = TextPainter(
          text: textSpan,
          textAlign: textAlign,
          maxLines: maxLines,
          textDirection: Directionality.of(context),
          textScaler: MediaQuery.of(context).textScaler,
        )..layout(maxWidth: constraints.maxWidth);

        // TODO: UNRELIABLE
        if (painter.didExceedMaxLines) {
          return Tooltip(
            message: message,
            child: Text.rich(
              textSpan,
              maxLines: maxLines,
              textAlign: textAlign,
              overflow: overflow,
            ),
          );
        } else {
          return Text.rich(
            textSpan,
            maxLines: maxLines,
            textAlign: textAlign,
            overflow: overflow,
          );
        }
      },
    );
  }
}
```

`didExceedMaxLines` turns out to be unreliable - `TextPainter` thinks not everything fits, but when laid out on the screen, it all fits fine. (At least on iOS with the 24 point font we're using). In researching this bug, I would find that `TextPainter` says the text is 355px wide, but it would safely render in a 343px space, so about 12px off (3%).

**Comment by allenbrunson** [comment] 2024-03-27 15:59
yep, pretty sure you are just re-stating the same problem i've got. in case you missed it, the workaround i developed is to always supply enough filled-in fields in my TextStyle objects so that the defaults don't matter anymore.

**Comment by LongCatIsLooong** [comment] 2024-03-28 06:52
I think the `TextPainter` metrics are reliable (the `Text` widget uses it to lay out and paint text), it's just that you're using different input parameters than `Text`. Consider using a multi-child widget / get the text metrics from Text directly, or file a feature request if these two options don't work for you.

**Closed by LongCatIsLooong** 2024-03-28 06:52 UTC
Labels: f: material design, a: typography, has reproducible steps, P2, team-design, triaged-design, found in release: 3.16, found in release: 3.18

**Comment by LongCatIsLooong** [comment] 2024-03-28 07:06
> I ran into a related issue this morning with this widget which we created to add tooltips to text if it overflows, particularly for users with high text scaling:
> 
> ```
> import 'package:flutter/material.dart';
> 
> /// Wraps a [textSpan] in a [Tooltip], but only if the text would overflow.
> ///
> /// Creates a [Text.rich] widget with [textSpan], and passes in the other
> /// [Text] arguments as-is. If the [Text.rich] widget cannot be contained in
> /// the constraints without overflowing, then it's wrapped in a [Tooltip] with
> /// a corresponding [message].
> class OverflowTextTooltip extends StatelessWidget {
>   /// The styled Text, likely a [TextSpan].
>   final InlineSpan textSpan;
> 
>   /// The tooltip message to show. The full text of [textSpan].
>   final String message;
> 
>   final int? maxLines;
>   final TextAlign textAlign;
>   final TextOverflow? overflow;
> 
>   const OverflowTextTooltip({
>     super.key,
>     required this.textSpan,
>     required this.message,
>     this.maxLines,
>     this.textAlign = TextAlign.start,
>     this.overflow,
>   });
> 
>   @override
>   Widget build(BuildContext context) {
>     return LayoutBuilder(
>       builder: (context, constraints) {
>         final painter = TextPainter(
>           text: textSpan,
>           textAlign: textAlign,
>           maxLines: maxLines,
>           textDirection: Directionality.of(context),
>           textScaler: MediaQuery.of(context).textScaler,
>         )..layout(maxWidth: constraints.maxWidth);
> 
>         // TODO: UNRELIABLE
>         if (painter.didExceedMaxLines) {
>           return Tooltip(
>             message: message,
>             child: Text.rich(
>               textSpan,
>               maxLines: maxLines,
>               textAlign: textAlign,
>               overflow: overflow,
>             ),
>           );
>         } else {
>           return Text.rich(
>             textSpan,
>             maxLines: maxLines,
>             textAlign: textAlign,
>             overflow: overflow,
>           );
>         }
>       },
>     );
>   }
> }
> ```
> 
> `didExceedMaxLines` turns out to be unreliable - `TextPainter` thinks not everything fits, but when laid out on the screen, it all fits fine. (At least on iOS with the 24 point font we're using). In researching this bug, I would find that `TextPainter` says the text is 355px wide, but it would safely render in a 343px space, so about 12px off (3%).

I can't think of a good solution other than writing your own `RenderParagraph` which is a lot of work. Could you create a feature request for this?
