### ISSUE TITLE
Container() suddenly requires a positional argument

### ISSUE THREAD

**Issue by bbozo** [flutter/flutter#26275] opened 2019-01-09 08:23 UTC
I'm going through a flutter tutorial, in one moment the parts of my project that haven't been touched (`git status` confirms it) started flashing red in Visual Studio Code because `Container` started to need a positional argument - I thought it might be an IDE error, but `flutter run` from an independent console gave the same results.

The exact moment when it all broke down I was working on the next lecture in which I added this: https://gist.github.com/bbozo/ade0662a222089117754b901a2096f4b - the new code didn't work, but also the old code had errors reported in it too.

I did `git stash` locally to revert the new changes, went through steps to clear cache (went through commands in #17937 and https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#corrupted-cache ) but the `Container()` calls in the old code all now require a positional argument.

* `flutter run` & `flutter doctor` outputs are here: https://gist.github.com/bbozo/54a7d75bb342aeed56bdbce651e262be
* the repo in question is here: https://github.com/bbozo/flutter_tutorial

I'm stuck :-)

**Comment by bbozo** [comment] 2019-01-09 08:31
> Might be https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

Correct! :-D Thank you! This somehow happened:

```
~/opt/flutter (stable) $ git diff
diff --git a/packages/flutter/lib/src/widgets/container.dart b/packages/flutter/lib/src/widgets/container.dart
index 64ce454..ba6d248 100644
--- a/packages/flutter/lib/src/widgets/container.dart
+++ b/packages/flutter/lib/src/widgets/container.dart
@@ -5,6 +5,7 @@
 import 'package:flutter/foundation.dart';
 import 'package:flutter/painting.dart';
 import 'package:flutter/rendering.dart';
+import 'package:flutter/src/material/text_field.dart';
 
 import 'basic.dart';
 import 'framework.dart';
@@ -246,7 +247,7 @@ class Container extends StatelessWidget {
   /// and a `decoration` argument. If you want to have both a `color` and a
   /// `decoration`, you can pass the color as the `color` argument to the
   /// `BoxDecoration`.
-  Container({
+  Container(TextField textField, {
     Key key,
     this.alignment,
     this.padding,
```

**Comment by zoechi** [comment] 2019-01-09 08:38
Perhaps the IDE you are using is not protecting from modifying SDK source.
This happens actually quite frequently.
What IDE are you working with?

**Comment by zoechi** [comment] 2019-01-09 08:39
I'm closing this issue because your problem is solved and there are other issues for related problems.
You can still comment of course.

**Closed by zoechi** 2019-01-09 08:39 UTC

**Comment by bbozo** [comment] 2019-01-09 09:14
> Perhaps the IDE you are using is not protecting from modifying SDK source.
> This happens actually quite frequently.
> What IDE are you working with?

I'm using VisualStudio Code:

```
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.13.0-45-generic
```

it seems this happens often :-)

**Comment by zoechi** [comment] 2019-01-09 09:34
@DanTup can this be caused by accidental modifications from within the IDE?
Does VSCode prevent editing files in the Flutter directory?

**Comment by DanTup** [comment] 2019-01-09 09:54
> can this be caused by accidental modifications from within the IDE?

Yes. Previously this has occurred because the server could generate quick-fixes that modifies the Flutter SDK if you wrote the code incorrectly:

<img width="652" alt="screen shot 2018-12-13 at 1 07 36 pm" src="https://user-images.githubusercontent.com/1078012/49940775-6e329580-fed8-11e8-9232-c917b6ec7c82.png">

This is fixed as part of https://github.com/dart-lang/sdk/issues/35402.

> Does VSCode prevent editing files in the Flutter directory?

We can't prevent them but we do show a warning if you manually modify a file outside of your workspace. It wouldn't have caught this though, as the change was made programatically from the quick-fix. Hopefully once the fix rolls out these sorts of issues will stop (in the meantime, running `git status` in the Flutter SDK folder may be the fastest way to find out if you have dirty files.

**Comment by zoechi** [comment] 2019-01-09 09:56
@DanTup thanks a lot for the update!
