### ISSUE TITLE
When I used cocoapods to import flutter into my old project and build it, the error occurred

### ISSUE THREAD

**Issue by Yewenyu** [flutter/flutter#25613] opened 2018-12-20 09:15 UTC
Hi, when I used cocoapods to import flutter into my old project:
Run Script:
```
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
```
And build it, I get this error:
```
iPhone Developer: Smith Julie (F7RD2Q2RK2): ambiguous (matches "iPhone Developer: Smith Julie (F7RD2Q2RK2)" and "iPhone Developer: Smith Julie (F7RD2Q2RK2)" in /Users/yewenyu/Library/Keychains/login.keychain-db)
iPhone Developer: Smith Julie (F7RD2Q2RK2): ambiguous (matches "iPhone Developer: Smith Julie (F7RD2Q2RK2)" and "iPhone Developer: Smith Julie (F7RD2Q2RK2)" in /Users/yewenyu/Library/Keychains/login.keychain-db)
Command PhaseScriptExecution failed with a nonzero exit code
```
And Then I removed the code:
```
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
```
It build success. However, when I archive the project, I get this error:
```
Could not find an option named "track-widget-creation".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
Failed to build /Users/yewenyu/Desktop/FlutterProject/ProAndFree/my_flutter.
Command PhaseScriptExecution failed with a nonzero exit code
```
Here is my flutter doctor -v:
````
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/yewenyu/Desktop/FlutterProject/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone X • EC5A3E31-E72C-42DB-B23A-C90DC6328597 • ios • iOS 12.0
      (simulator)
```

Can someone help me?

Thanks!

**Comment by kangwang1988** [comment] 2019-01-09 03:33
Nope, it has nothing to do with your code signing.
Check generated.xcconfig and remove "TRACK_WIDGET_CREATION" flag.
@pejalo

**Comment by cikichen** [comment] 2019-01-11 05:51
@kangwang1988 

```
Building cn.codemao.ios.community for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: R5A35URG47
Starting Xcode build...
 ├─Building Dart code...                              0.5s

Xcode build done.                                            1.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Could not find an option named "track-widget-creation".

    Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
    Failed to build /Users/unity_flutter.
    Command /bin/sh failed with exit code 255

Encountered error while building for device.
```
Generated.xcconfig
```
// This is a generated file; do not edit or check into version control.
FLUTTER_ROOT=/Users/xxx/dev/flutter
FLUTTER_APPLICATION_PATH=/Users/xxx/
FLUTTER_TARGET=lib/main.dart
FLUTTER_BUILD_DIR=build
SYMROOT=${SOURCE_ROOT}/../build/ios
FLUTTER_FRAMEWORK_DIR=/Users/xxx/flutter/bin/cache/artifacts/engine/ios-release
FLUTTER_BUILD_NAME=3.1.0
FLUTTER_BUILD_NUMBER=99

```

**Comment by zoechi** [comment] 2019-01-11 05:52
Duplicate of #24239

**Closed by zoechi** 2019-01-11 05:52 UTC
Labels: a: existing-apps, engine, ⌺‬ platform-ios
