### ISSUE TITLE
Flutter 1.12 has broken running apps on Android

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#47189] opened 2019-12-17 03:39 UTC
Here is the error I get when I run flutter run -d all.

<details>
  <summary>error</summary>

 
```bash
Launching lib/main.dart on Android SDK built for x86 in debug mode...

[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
/Users/azamsharp/Downloads/fresh_news 2/android/app/src/debug/AndroidManifest.xml:22:18-91 Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-32:19 to override.
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugManifest'.                  
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:9:5-32:19 to override.
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 33s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        34.9s
AndroidX incompatibilities may have caused this build to fail. Please migrate your app to AndroidX. See https://goo.gl/CP92wY.
Gradle task assembleDebug failed with exit code 1
```

</details>

**Comment by azamsharp** [comment] 2019-12-17 03:39
The link for the help https://goo.gl/CP92wY is also broken.

**Comment by carlosesquivel-katoo** [comment] 2019-12-17 11:01
I have the exact same issue after upgrading. The link works but following the instructions doesn't fix anything

**Comment by iapicca** [comment] 2019-12-17 11:18
Hi @azamsharp 
could you please run 
`flutter clean`
`flutter pub cache repair`

If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by sergicastellsague** [comment] 2019-12-17 11:29
It is generating crashes as well on a very few devices after upgrading to latest stable 1.12.

It crashes so early we don't get Fabric / Firebase reports.

The two examples we're aware of are:
- samsung SM-G531F with android 21
- HUAWEI DUB-LX1 with android 27.

Rolling back to 1.10.7 (the last version we had in prod) works flawlessly.

**Comment by carlosesquivel-katoo** [comment] 2019-12-17 11:52
@iapicca After following your instructions it builds but it's failing because of dependendent plugins, I'll fix those.

Thanks!

**Comment by VladyslavBondarenko** [comment] 2020-01-10 09:55
Given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by 7flash** [comment] 2020-01-16 06:44
Please reopen this issue, it's still not working on devices listed above and also not working on my own device Huawei Y Max

**Comment by 7flash** [comment] 2020-01-16 06:44
```
Flutter 1.12.13+hotfix.5 • channel stable •

flutter create stabletest

cd stabletest

flutter build apk --target-platform android-arm64
```

**Comment by 7flash** [comment] 2020-01-16 06:49
Compiled apk is not working on my device, but it works on most other devices, any ideas?
It works flawless for apps compiled with flutter 1.10.7 but when trying to open application compiled with flutter 1.12 - it does not work on my device

**Comment by sergicastellsague** [comment] 2020-01-16 08:10
@7flash can you please put the crash logs? The issue reported here is happening on compile time. But from your statement, I understand that you managed to compile but crashes on runtime.
So, can we have this runtime crash log, please?

**Comment by 7flash** [comment] 2020-01-16 08:42
I think it's exactly the same issue

**Comment by sergicastellsague** [comment] 2020-01-16 08:58
Is there any chance you can try? I'm planning to re-upgrade to the latest stable flutter version, as it's working on all my test devices (around 15), but I don't have a faulty device like yours to try out... 🙏

**Comment by 7flash** [comment] 2020-01-16 14:55
![stabletest](https://user-images.githubusercontent.com/4569866/72535259-3522dc80-38b3-11ea-814e-f993383442c3.gif)

**Comment by sergicastellsague** [comment] 2020-01-16 15:23
Do you have access to the stacktrace @7flash ?

**Comment by 7flash** [comment] 2020-01-17 03:54
Maybe this is related?
https://github.com/flutter/flutter/issues/49008

**Comment by dkwingsmt** [comment] 2020-01-17 08:04
Probably not #49008. Issue #49008 is only found on the specific version as described in the issue (we’ve kind of pin pointed the culprit), and it literally crashes before any widget is built.

**Comment by rapPayne** [comment] 2020-02-11 15:25
Try this:

1. Edit myProject/android/gradle.properties and add this line:
'android.useAndroidX=true'
2. Run 'flutter clean'
3. Rebuild

It worked for me.

**Comment by darshankawar** [comment] 2020-12-07 13:14
@azamsharp @7flash Is this still a valid issue using latest Flutter version or has this been resolved ?
If issue persists, can we get updated `flutter doctor -v` and reproducible code / steps to replicate ?
Thanks.

**Comment by pedromassangocode** [comment] 2020-12-30 11:02
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 11:02 UTC
Labels: P4, e: device-specific, engine, platform-android, severe: crash, t: gradle, waiting for customer response
