### ISSUE TITLE
FLUTTER - ERROR : 'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 136 pos 15: 'assetName != null': is not true.

### ISSUE THREAD

**Issue by kayisi44** [flutter/flutter#74117] opened 2021-01-16 14:02 UTC
I get an error like this in the code I wrote today. Can you help me?

`'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 136 pos 15: 'assetName != null': is not true.`

I practice a foreign language. There are multiple choice test questions in my application. My questions are random, but I get such an error at once, I will be glad if you can help me with this error. My codes are as follows.

`**MY CODE IS HERE !!**`
**The json file I pulled the questions from
**

<details> 
<summary>json file</summary> 

```json
[
  {
    "1": "images/akraba.jpg",
    "2": "images/hırka.jpg",
    "3": "images/omuz.jpg",
    "4": "images/güzel.jpg",
    "5": "images/doksan.jpg",
    "6": "images/mor.jpg",
    "7": "images/aralık.jpg",
    "8": "images/sürpriz.jpg",
    "9": "images/kıkırdama.jpg",
    "10": "images/şarkı söylemek.jpg",
    "11": "images/vücut geliştirmek.jpg",
    "12": "images/sınıf.jpg",
    "13": "images/yazar.jpg",
    "14": "images/reçel.jpg",
    "15": "images/türkiye.jpg",
    "16": "images/şelale.jpg",
    "17": "images/öksürme.jpg",
    "18": "images/oyuncak robot.jpg",
    "19": "images/ördek.jpg",
    "20": "images/kedi.jpg"
  },
  {
    "1": {
      "a": "Akraba",
      "b": "Reçel",
      "c": "Kurt",
      "d": "Sınıf"
    },
    "2": {
      "a": "Vücut Geliştirmek",
      "b": "Pantolon",
      "c": "Hırka",
      "d": "Oyuncak Robot"
    },
    "3": {
      "a": "Grip",
      "b": "Omuz",
      "c": "Bacak",
      "d": "Parmak"
    },
    "4": {
      "a": "Kısa",
      "b": "Tembel",
      "c": "Uzun",
      "d": "Güzel"
    },
    "5": {
      "a": "Dokuz",
      "b": "Doksan",
      "c": "Yüz",
      "d": "Seksen"
    },
    "6": {
      "a": "Sarı",
      "b": "Mor",
      "c": "Pembe",
      "d": "Turuncu"
    },
    "7": {
      "a": "Ekim",
      "b": "Mayıs",
      "c": "Aralık",
      "d": "Ocak"
    },
    "8": {
      "a": "Tebrik Kartı",
      "b": "Davet",
      "c": "Doğum Günü",
      "d": "Sürpriz"
    },
    "9": {
      "a": "Kıkırdama",
      "b": "Korkmak",
      "c": "Kahkaha Atmak",
      "d": "Hayal Etmek"
    },
    "10": {
      "a": "Dans Etmek",
      "b": "Basketbol Oynamak",
      "c": "Şarkı Söylemek",
      "d": "Vücut Geliştirmek"
    },
    "11": {
      "a": "Yüzmek",
      "b": "Vücut Geliştirmek",
      "c": "Judo",
      "d": "Beyzbol"
    },
    "12": {
      "a": "Cevap",
      "b": "Ders",
      "c": "Sınıf",
      "d": "Bilim İnsanı"
    },
    "13": {
      "a": "Ressam",
      "b": "Doktor",
      "c": "Yazar",
      "d": "Mühendis"
    },
    "14": {
      "a": "Bal",
      "b": "Tost",
      "c": "Pilav",
      "d": "Reçel"
    },
    "15": {
      "a": "Türkiye",
      "b": "Almanya",
      "c": "Bakü",
      "d": "Hollanda"
    },
    "16": {
      "a": "Gökkuşağı",
      "b": "Şelale",
      "c": "Okyanus",
      "d": "Sis"
    },
    "17": {
      "a": "Diş Ağrısı",
      "b": "Şeker",
      "c": "Öksürme",
      "d": "Mide Ağrısı"
    },
    "18": {
      "a": "Oyuncak Araba",
      "b": "Oyuncak Ev",
      "c": "Oyuncak Tabanca",
      "d": "Oyuncak Robot"
    },
    "19": {
      "a": "Ördek",
      "b": "Kurt",
      "c": "Tavşan",
      "d": "Köpek"
    },
    "20": {
      "a": "Tilki",
      "b": "Kedi",
      "c": "Kaplumbağa",
      "d": "Aslan"
    }
  },
  {
    "1": "Akraba",
    "2": "Hırka",
    "3": "Omuz",
    "4": "Güzel",
    "5": "Doksan",
    "6": "Mor",
    "7": "Aralık",
    "8": "Sürpriz",
    "9": "Kıkırdama",
    "10": "Şarkı Söylemek",
    "11": "Vücut Geliştirmek",
    "12": "Sınıf",
    "13": "Yazar",
    "14": "Reçel",
    "15": "Türkiye",
    "16": "Şelale",
    "17": "Öksürme",
    "18": "Oyuncak Robot",
    "19": "Ördek",
    "20": "Kedi"
  }
]
```

</details>

</details>

### DART FILE

<details>
<summary>dart file</summary>

```dart
import 'dart:async';
import 'package:flutter/cupertino.dart';
import 'dart:convert';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:hadibismillah/quiz/test_sorular.dart';
import 'package:hadibismillah/siniflar/test.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'file:///D:/AndroidStudioProjects/hadi_bismillah/lib/test_dogru_yanl%C4%B1%C5%9F_icerik/true_false_sonuc_page.dart';
import 'package:hadibismillah/localization/localization_constants.dart';

class LoadJson extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FutureBuilder(
        future: DefaultAssetBundle.of(context)
            .loadString("lib/quiz/questions.json"),
        builder: (context, snapshot) {
          List mydata = json.decode(snapshot.data.toString());
          if (mydata == null) {
            return Center(
              child: Text("asldöasid"),
            );
          } else {
            return SorularinOlacagiPage(mydata: mydata);
          }
        },
      ),
    );
  }
}

class SorularinOlacagiPage extends StatefulWidget {
  final mydata;

  const SorularinOlacagiPage({Key key, this.mydata}) : super(key: key);

  @override
  _SorularinOlacagiPageState createState() =>
      _SorularinOlacagiPageState(mydata: mydata);
}

class _SorularinOlacagiPageState extends State<SorularinOlacagiPage>
    with SingleTickerProviderStateMixin {
  List<QuestionsModel> _myQuestions = new List<QuestionsModel>();
  List mydata;

  _SorularinOlacagiPageState({this.mydata});

  Color colortoShow = Colors.indigo;
  Color right = Colors.green;
  Color wrong = Colors.red;
  int index = 0;
  int i = 1;
  int marks = 0;
  bool disableAnswer = false;
  int j = 0;
  int timer = 30;
  String showTimer = "30";
  var random_array;
  Animation animation;
  AnimationController animationController;
  double beginAnim = 0.0;
  double endAnim = 1.0;

  Map<String, Color> btnColor = {
    "a": Colors.indigoAccent,
    "b": Colors.indigoAccent,
    "c": Colors.indigoAccent,
    "d": Colors.indigoAccent
  };
  bool cancelTimer = false;

  genrandomarray() {
    var distinctIds = [];
    var rand = new Random();
    for (int i = 0;;) {
      distinctIds.add(rand.nextInt(20));
      random_array = distinctIds.toSet().toList();
      if (random_array.length < 20) {
        continue;
      } else {
        break;
      }
    }
    print(random_array);
  }

  @override
  void initState() {
    startTimer();
    genrandomarray();
    super.initState();
    _myQuestions = getQuestions();
    animationController =
        AnimationController(duration: const Duration(seconds: 8), vsync: this);
    animation =
        Tween(begin: beginAnim, end: endAnim).animate(animationController)
          ..addListener(() {
            setState(() {});
          });
    startAnim();
    animationController.addStatusListener((status) {
      if (status == AnimationStatus.completed) {
        if (index < _myQuestions.length - 1) {
          index++;
          resetAnim();
          startAnim();
        } else {
          Navigator.of(context).pushReplacement(MaterialPageRoute(
              builder: (context) => TrueFalseSSonucSayfasi(marks: marks)));
        }
      }
    });
  }

  startAnim() {
    animationController.forward();
  }

  resetAnim() {
    animationController.reset();
  }

  stopAnim() {
    animationController.stop();
  }

  @override
  void setState(fn) {
    if (mounted) {
      super.setState(fn);
    }
  }

  void startTimer() async {
    const oneSec = Duration(seconds: 1);
    Timer.periodic(oneSec, (Timer t) {
      setState(() {
        if (timer < 1) {
          t.cancel();
          nextQuestions();
        } else if (cancelTimer == true) {
          t.cancel();
        } else {
          timer = timer - 1;
        }
        showTimer = timer.toString();
      });
    });
  }

  void nextQuestions() {
    resetAnim();
    startAnim();
    cancelTimer = false;
    setState(() {
      if (j < 20) {
        i = random_array[j];
        j++;
      } else {}

      btnColor["a"] = Colors.indigoAccent;
      btnColor["b"] = Colors.indigoAccent;
      btnColor["c"] = Colors.indigoAccent;
      btnColor["d"] = Colors.indigoAccent;
      disableAnswer = false;
    });
    //startTimer();
  }

  void checkAnswer(String k) {
    //Sorular -0 şıklar-1 cevaplar -1 =>index numarları
    if (mydata[2][i.toString()] == mydata[1][i.toString()][k]) {
      //answer is correct
      marks = marks + 5;
      colortoShow = right;
    } else {
      //answer is wrong
      colortoShow = wrong;
    }
    setState(() {
      cancelTimer = true;
      btnColor[k] = colortoShow;
      disableAnswer = true;
    });
    Timer(Duration(seconds: 2), nextQuestions);
  }

  Widget choiceButton(String k) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 10, horizontal: 20),
      child: MaterialButton(
        onPressed: () => checkAnswer(k),
        child: Text(
          mydata[1][i.toString()][k],
          style: TextStyle(color: Colors.white, fontSize: 16),
          maxLines: 1,
        ),
        //color: btnColor[k],
        color: btnColor[k],
        splashColor: Colors.indigo.shade700,
        highlightColor: Colors.indigo.shade700,
        minWidth: 200,
        height: 45,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations(
        [DeviceOrientation.portraitDown, DeviceOrientation.portraitUp]);
    return WillPopScope(
      child: Scaffold(
        body: Column(
          children: [
            Container(
              padding: EdgeInsets.only(left: 30, right: 30, top: 20),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  Text(
                    "${j + 1} / ${_myQuestions.length}",
                    style: TextStyle(fontSize: 24, fontWeight: FontWeight.w500),
                  ),
                  Text(
                    getTranslated(context, "ssoru"),
                    style: TextStyle(fontSize: 17, fontWeight: FontWeight.w400),
                  ),
                  Spacer(),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: [
                      Text(
                        "$marks",
                        style: TextStyle(
                            fontSize: 24, fontWeight: FontWeight.w500),
                      ),
                      SizedBox(
                        height: 10,
                      ),
                      Text(
                        getTranslated(context, "puan"),
                        style: TextStyle(
                            fontSize: 17, fontWeight: FontWeight.w400),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            Expanded(
              flex: 1,
              child: Container(
                padding: EdgeInsets.all(15),
                alignment: Alignment.bottomLeft,
                child: Container(
                  child: LinearProgressIndicator(
                    value: animation.value,
                  ),
                ),
              ),
            ),
            Expanded(
              flex: 3,
              child: Image.asset(
                mydata[0][i.toString()],
              ),
            ),
            Expanded(
              flex: 6,
              child: AbsorbPointer(
                absorbing: disableAnswer,
                child: Container(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      choiceButton("a"),
                      choiceButton("b"),
                      choiceButton("c"),
                      choiceButton("d"),
                    ],
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
      onWillPop: () {
        return showDialog(
            context: context,
            builder: (context) => AlertDialog(
                  title: Text("Test"),
                  content: Text("Bu Aşamada Geri Dönemezsin"),
                  actions: [
                    FlatButton(
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                      child: Text("Tamam"),
                    ),
                  ],
                ));
      },
    );
  }
}
```
</details>

**Comment by TahaTesser** [comment] 2021-01-18 08:52
Hi @kayisi44 
This looks like a production app, Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) instead of production code?
Thank you

**Comment by pedromassangocode** [comment] 2021-02-12 10:24
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-12 10:24 UTC
Labels: in triage, waiting for customer response
