### ISSUE TITLE
Container with decoration in a ListView render unexpected border line on real iPhone

### ISSUE THREAD

**Issue by Panl** [flutter/flutter#22068] opened 2018-09-20 05:30 UTC
## Steps to Reproduce

I write a demo to reproduce this issue [flutter_app](https://github.com/Panl/flutter_app)

## ScreenShot
![file](https://user-images.githubusercontent.com/3842675/45797650-33560280-bcd9-11e8-8b90-7e7bb205b5d2.jpg)

## Logs

```
[  +38 ms] executing: [/Users/ray/devenv/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/ray/devenv/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/Users/ray/devenv/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/ray/devenv/flutter/] git log -n 1 --pretty=format:%H
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5ab9e70727d858def3a586db7fb98ee580352957
[        ] executing: [/Users/ray/devenv/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 12 days ago
[        ] executing: [/Users/ray/devenv/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +24 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.8.2-0-g5ab9e7072
[ +296 ms] executing: /Users/ray/Library/Android/SDK/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/ray/Library/Android/SDK/platform-tools/adb devices -l
[        ] List of devices attached
[   +7 ms] executing: idevice_id -h
[  +71 ms] executing: which ideviceinstaller
[   +6 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[   +5 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[  +26 ms] executing: which ideviceinstaller
[   +5 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[   +5 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[  +90 ms] executing: which ideviceinstaller
[   +8 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[   +7 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[ +218 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] Lei.Pan           • d1f228d7daccec070524eb8dfe27bf1f3bc29ce6 • ios • iOS 12.1
[        ] Glow iPhone 6Plus • c9378576b1ae2a6b8b765f94afe2663265b019ba • ios • iOS 11.4.1
[  +18 ms] "flutter run" took 717ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:239:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:350:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:109:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///Users/ray/devenv/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-CN)
    • Flutter version 0.8.2 at /Users/ray/devenv/flutter
    • Framework revision 5ab9e70727 (12 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/ray/Library/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = /Users/ray/Library/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (2 available)
    • Lei.Pan           • d1f228d7daccec070524eb8dfe27bf1f3bc29ce6 • ios • iOS 12.1
    • Glow iPhone 6Plus • c9378576b1ae2a6b8b765f94afe2663265b019ba • ios • iOS 11.4.1

• No issues found!
```

**Comment by zoechi** [comment] 2018-09-24 17:30
Thanks for reporting.
Do you think the log output you added is related? I can#t see the relation.

**Comment by Panl** [comment] 2018-09-25 08:33
I think the log output is not related, I just follow the issue steps to add it here, I guess it may be a skia's render issue on iOS.

**Comment by GaryQian** [comment] 2018-12-06 20:34
I believe this has been fixed with a new Skia change. I don't remember the exact bug/patch but after a certain commit I was unable to reproduce anymore.

**Closed by GaryQian** 2018-12-06 20:34 UTC
Labels: engine, framework, ⌺‬ platform-ios
