### ISSUE TITLE
TextField counts the number of characters incorrectly

### ISSUE THREAD

**Issue by denghewenai** [flutter/flutter#70672] opened 2020-11-17 03:32 UTC
## Steps to Reproduce

1. 
TextField uses maxLength to count the number of characters "(̿▀̿ ̿Ĺ̯̿̿▀̿̿̿)" is 7, but the number of statistics on the original is 15, and the delete button needs to be clicked 15 times when deleting
![tmp](https://user-images.githubusercontent.com/13479936/99343289-867f6c00-28c8-11eb-9ff3-db6fc1022ff2.jpeg)

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H15, locale zh-Hans-CN)
    • Flutter version 1.22.2 at /Users/denghewenhewen/flutter
    • Framework revision 84f3d28555 (4 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/denghewenhewen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/denghewenhewen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • PCT AL10 (mobile) • 5EN0219315004137 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

**Comment by pedromassangocode** [comment] 2020-11-17 06:28
Hi @denghewenai 
Can you please provide a minimal complete reproducible code sample and the steps to reproduce the issue?
Thank you

**Comment by denghewenai** [comment] 2020-11-17 07:55
`

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class InputWidgetWithTitle extends StatelessWidget {
  final _textFieldController = TextEditingController();
  final int maxLength;
  final String titleText;

  InputWidgetWithTitle({
    this.maxLength,
    this.titleText,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 343,
      height: 80,
      alignment: Alignment.center,
      decoration: new BoxDecoration(
          color: Colors.white,
          border: new Border.all(color: Colors.grey, width: 1),
          borderRadius: new BorderRadius.circular(4.0)),
      padding: EdgeInsets.all(12),
      child: TextField(
        controller: _textFieldController,
        maxLength: 120,
        maxLines: 5,
        decoration: InputDecoration(
          border: InputBorder.none,
          focusedBorder: InputBorder.none,
          enabledBorder: InputBorder.none,
          errorBorder: InputBorder.none,
          disabledBorder: InputBorder.none,
          contentPadding: EdgeInsets.zero,
        ),
        keyboardType: TextInputType.text,
        inputFormatters: [LengthLimitingTextInputFormatter(120)],
        style: TextStyle(color: Colors.black, fontSize: 15),
        onChanged: (value) {},
      ),
    );
  }
}
`

Normally limit the maximum number of input characters in the input box, and then enter the string "(̿▀̿ ̿Ĺ̯̿̿▀̿̿̿)"

**Comment by pedromassangocode** [comment] 2020-11-17 09:44
Hi @denghewenai 
Here it counts six digits. I'm still not sure what to expect with the steps you provided above.

![Screen Shot 2020-11-17 at 10 40 10](https://user-images.githubusercontent.com/67424416/99373190-67311080-28c1-11eb-962a-996066e50275.png)

Please make sure you Flutter version is updated.

<details><summary>Flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by denghewenai** [comment] 2020-11-17 10:59
Hello, whether it is 6 or 7 statistical results are not correct, you can click the delete button, you need to click 15 times to delete to complete, so the correct should be 15 characters

**Comment by denghewenai** [comment] 2020-11-17 11:07
![image](https://user-images.githubusercontent.com/13479936/99382691-daf60c00-2907-11eb-84ff-f4aef368a84e.png)

I tried it on an iOS device, and the number of statistical characters is 6, but on an Android device, it is 7. Whether it is 6 or 7 is the wrong statistical result, the correct statistical result should be 15 because it is deleted When you need to click the delete button 15 times

**Comment by HansMuller** [comment] 2020-11-17 17:39
See also: #67898

**Comment by pedromassangocode** [comment] 2020-11-18 07:49
Hi @denghewenai 
On master channel it counts **6** for Android and iOS.

| Android (stable/master) | iOS (stable/master) |
| --- | --- |
![gif](https://user-images.githubusercontent.com/67424416/99499838-c9e5e300-2979-11eb-8a82-44c8db3dd078.gif)|![gif2](https://user-images.githubusercontent.com/67424416/99500365-90fa3e00-297a-11eb-9a65-c679eaa4143b.gif)|

I have been tracking https://github.com/flutter/flutter/issues/67898 and most of the text input issues in Flutter so I'm pretty sure that this was fixed in Flutter `1.22.3`.  As I mentioned in https://github.com/flutter/flutter/issues/70672#issuecomment-728812463, please make sure you update your Flutter sdk.


<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.289, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.289 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision aab9a76ee4 (2 hours ago), 2020-11-17 21:40:28 -0800
    • Engine revision 94e217bcf6
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile)  • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)             • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>

**Comment by denghewenai** [comment] 2020-11-18 10:36
Hello, I upgraded to the latest flutter version, re-verified, and found that the number of characters displayed under the Android statistics is still 7, but it takes 15 to delete. iOS is the same as shown in the gif above

I think it should be caused by the lack of a unified coding method. So I plan to close this issue

![kc5we-j1ac1](https://user-images.githubusercontent.com/13479936/99515360-d09b4700-29c7-11eb-9954-95f4f948b50b.gif)

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/denghewenhewen/flutter
    • Framework revision 1aafb3a8b9 (5 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/denghewenhewen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/denghewenhewen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

 
[✓] Connected device (1 available)            
    • PCT AL10 (mobile) • 5EN0219315004137 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

**Comment by pedromassangocode** [comment] 2020-11-19 08:15
Alright, Let’s have this opened for further investigation.

**Comment by denghewenai** [comment] 2020-11-19 08:41
Mi 10
![Screenshot_2020-11-19-16-37-55-003_com android settings](https://user-images.githubusercontent.com/13479936/99642061-07379700-2a86-11eb-8496-76d565e832e6.jpg)

**Comment by LongCatIsLooong** [comment] 2020-11-20 19:23
I couldn't reproduce this on master. The character count on both platforms is 6 and both take exactly 6 backspaces to delete.

**Comment by HansMuller** [comment] 2020-11-20 22:52
I'm closing this issue because we were unable to reproduce it: https://github.com/flutter/flutter/issues/70672#issuecomment-731362529. If it can be reproduced on master, please explain how and reopen the issue.

**Closed by HansMuller** 2020-11-20 22:52 UTC
Labels: a: text input, f: material design, framework, passed first triage
