### ISSUE TITLE
Fullscreen desktop app

### ISSUE THREAD

**Issue by PiN73** [flutter/flutter#85411] opened 2021-06-27 15:26 UTC
## Use case

I need to make my Flutter Desktop app (on Windows) fullscreen. The window should take all space of the screen. Taskbar and window title should not be visible. Like `WindowState="Maximized"` and `WindowStyle="None"` in WPF.

## What I tried

I tried [desktop_window](https://pub.dev/packages/desktop_window) package but it allows only maximizing window, while taskbar and title remains visible and takes space.

I tried [solution](https://stackoverflow.com/a/63618734/6131611) from stackoverflow. After removing `ShowWindow` call it worked, but there is white margin at right and bottom of the screen. Also it makes impossible to Alt-Tab to another programs.

## Question

Is there any "official" way to make Flutter Desktop app fullscreen?

**Comment by stuartmorgan** [comment] 2021-06-27 21:14
Duplicate of https://github.com/flutter/flutter/issues/67708



> Is there any "official" way to make Flutter Desktop app fullscreen?

This answer is still accurate as to the state of non-third-party options: https://stackoverflow.com/a/57827134

**Closed by stuartmorgan** 2021-06-27 21:14 UTC
