### ISSUE TITLE
[web] zooming and resizing does not redraw Scaffold properly

### ISSUE THREAD

**Issue by peterlauri** [flutter/flutter#80750] opened 2021-04-19 20:36 UTC
See video for details of how to reproduce this issue. Don't forget to turn on the sound :)

https://user-images.githubusercontent.com/3514945/115299736-dc05c080-a167-11eb-9f84-90d7f8ed5051.mp4

Expected behavior: Scaffold should resize properly when zooming in and out.

This problem can also arrive in situations like:

- moving web browser from laptop to external monitor
- resizing window frequently

**Comment by iapicca** [comment] 2021-04-19 21:51
@peterlauri 
can you provide your `flutter doctor -v`

**Comment by peterlauri** [comment] 2021-04-19 23:13
> @peterlauri
> can you provide your `flutter doctor -v`

<details>
<summary>flutter doctor -v</summary>
```
➜  goalplan_next git:(1156-dockerize-tests-and-lint) flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/plauri/apps/flutter
    • Framework revision 4d7946a68d (5 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/plauri/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • BE2013 (mobile) • 2a0d8842 • android-arm64  • Android 10 (API 29)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```
 </details>

**Comment by TahaTesser** [comment] 2021-04-20 08:34
Hi @peterlauri 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/77084
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-20 08:34 UTC
Labels: in triage
