### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY: AnimatedPositioned 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is flutter: not true.

### ISSUE THREAD

**Issue by corymalcolmtaylor** [flutter/flutter#39820] opened 2019-09-04 13:02 UTC
## Steps to Reproduce

1. get the code here https://github.com/corymalcolmtaylor/game_maze.git 
2. get commit with id ==  ```b002138ccee109ee68e93cbcc3e36faefd30b1e2```
3. run the program in iOS sim for iPhone 5s
4. if the errr does not occur try restarting  a game a few times or playing for a while, the error in intermittent

## Logs

```
 
flutter: build in portrait
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building
flutter: AnimatedPositioned-[<'ZaYV7vFn-OfXO5NAlas_sfD8U9e5vahuNlq1rlyAZ0Y='>](duration: 700ms, left: 164.2,
flutter: top: 0.0, height: 30.8, dirty, state: _AnimatedPositionedState#a05a7(ticker active, has left, has
flutter: top, has height)):
flutter: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is
flutter: not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: User-created ancestor of the error-causing widget was:
flutter:   Stack 
lib/main.dart:696
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      Tween.lerp 
package:flutter/…/animation/tween.dart:237
flutter: #3      Tween.transform 
package:flutter/…/animation/tween.dart:260
flutter: #4      Animatable.evaluate 
package:flutter/…/animation/tween.dart:53
flutter: #5      _AnimatedPositionedState.build 
package:flutter/…/widgets/implicit_animations.dart:1002
flutter: #6      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4039
flutter: #7      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3933
flutter: #8      Element.rebuild 
package:flutter/…/widgets/framework.dart:3730
flutter: #9      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2340
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:701
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:285
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1033
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:975
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:891
flutter: #18     _invoke  (dart:ui/hooks.dart:236:10)
flutter: #19     _drawFrame  (dart:ui/hooks.dart:194:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/animation/tween.dart': Failed assertion: line 237 pos 12: 'begin != null': is not true.
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.8.3, on Mac OS X 10.14.6 18G87, locale en-CA)
    • Flutter version 1.8.3 at /Users/corytaylor/dev/flutter
    • Framework revision e4ebcdf6f4 (6 weeks ago), 2019-07-27 11:48:24 -0700
    • Engine revision 38ac5f30a7
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Volumes/macex/androidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone 5s • 00BCA4B2-7B01-4564-8A4A-5E85A6717066 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by BondarenkoStas** [comment] 2019-09-04 13:33
@corymalcolmtaylor Possible the error is with the implementation, not with Flutter itself. In that case I would advise you to open a question on StackOverflow as help may come faster there.

**Comment by goderbauer** [comment] 2019-09-09 23:24
Instead of pointing to your app it would be more helpful for debugging this if you can post a reduced test case that reproduces the error.

**Comment by corymalcolmtaylor** [comment] 2019-09-10 00:31
Yes I suppose it would but like I said the error is intermittent so i don't have such a test case.  I don't seem to be getting this error anymore in that codebase at least so if you want to compare with earlier or later commits that might help but I have moved on.    I posted this bug report because the error message itself contained the request to do so.

**Comment by JRamos29** [comment] 2020-05-24 00:04
@corymalcolmtaylor I can't check if it could be your case (because your link points to the repo and not to the code where you are getting the error) or if this helps. But i was using two animatedPositioned getting the same error in just one of them, pointing to the _right_ property specifically. After some tests, i noticed that i hadn't put key on the widgets. Putting a key in each one solved the problem.

**Comment by hassansaleh31** [comment] 2020-06-23 10:08
I'm having the same error when using `AnimatedPositioned` like so:

```dart
left: percentX <= 0.5
    ? (chartWidth * percentX) - (circleDiameter / 2)
    : null,
right: percentX > 0.5
    ? chartWidth -
        (chartWidth * percentX) -
        (circleDiameter / 2)
    : null,
```

When `percentX` changes from 0.5 to 0.51 left becomes null and right becomes a non-null value.

**Comment by hassansaleh31** [comment] 2020-06-23 10:31
> I'm having the same error when using `AnimatedPositioned` like so:
> 
> ```dart
> left: percentX <= 0.5
>     ? (chartWidth * percentX) - (circleDiameter / 2)
>     : null,
> right: percentX > 0.5
>     ? chartWidth -
>         (chartWidth * percentX) -
>         (circleDiameter / 2)
>     : null,
> ```
> 
> When `percentX` changes from 0.5 to 0.51 left becomes null and right becomes a non-null value.
> 
> If I replace `AnimatedPositioned` with `Positioned`, the code works fine.
> 
> The reason I'm using `Positioned` instead of `Align` is that I need an absolute position on the vertical axis and an alignment on the horizontal axis.

I just fixed this by applying a `maxWidth` and calculating the correct left and right values instead of passing null:

```dart
left: percentX <= 0.5
    ? (chartWidth * percentX) - (circleDiameter / 2)
    : (chartWidth * percentX) -
        (circleDiameter / 2) -
        maxWidth,
right: percentX > 0.5
    ? chartWidth -
        (chartWidth * percentX) -
        (circleDiameter / 2)
    : chartWidth -
        (chartWidth * percentX) -
        (circleDiameter / 2) -
        maxWidth,
```

**Comment by darshankawar** [comment] 2020-08-06 13:48
Hi @corymalcolmtaylor,
Can you please confirm if you still experience this issue on latest Flutter version (eg: dev, master, stable) ?
Thanks.

**Comment by markusaksli-nc** [comment] 2020-08-28 13:09
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

Thanks for your contribution.

**Closed by markusaksli-nc** 2020-08-28 13:09 UTC
Labels: a: animation, framework, waiting for customer response
