### ISSUE TITLE
cupertino_icons, square_pencil issue

### ISSUE THREAD

**Issue by hashirshoaeb** [flutter/flutter#76580] opened 2021-02-23 03:45 UTC
<img width="288" alt="Screenshot 2021-02-23 at 8 42 11 AM" src="https://user-images.githubusercontent.com/35165481/108799779-077a8d80-75b3-11eb-9d4c-dfb6490312c8.png">

`CupertinoIcons.square_pencil` and `CupertinoIcons.square_pencil_fill` are same in [cupertino_icons](https://github.com/flutter/cupertino_icons) v1.0.0. It seems like both icons are overlapping each other.

I believe that, `CupertinoIcons.square_pencil` should look like this: 
<img width="27" alt="Screenshot 2021-02-23 at 8 36 53 AM" src="https://user-images.githubusercontent.com/35165481/108799500-4a883100-75b2-11eb-8724-6f9cec109ac3.png"> 
(i took this screenshot from notes app in iOS for reference) 
And `CupertinoIcons.square_pencil_fill` should be the filled version of it.

**Comment by pedromassangocode** [comment] 2021-02-23 06:59
Duplicate of https://github.com/flutter/flutter/issues/68436. Please follow up on that issue for updates.
Thank you

**Closed by pedromassangocode** 2021-02-23 06:59 UTC

**Comment by hashirshoaeb** [comment] 2021-02-23 07:16
ok, Thanks.
