### ISSUE TITLE
[image_picker] M1 simulator is unable to pick any image.

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#96761] opened 2022-01-18 06:48 UTC
## Steps to Reproduce

Call the following method: 

```dart
 void pickImageFromGallery() async {
  try {
    print('Picking an image');
    await ImagePicker().pickImage(source: ImageSource.gallery);
    print('Image picked');
  } catch (e) {
    print(e);
  }
}
```

1. Pick an image from iOS simulator (any image not just the first one which is of HEIC format as there's a [separate issue](https://github.com/flutter/flutter/issues/82602) created for it)
2. Once the image is picked, the code neither throws any exception nor it prints `Image picked`
3. If you try to select another image now, it throws an error: 
> PlatformException(multiple_request, Cancelled by a second request, null, null)

### Flutter doctor: 
```
[✓] Flutter (Channel dev, 2.9.0-0.1.pre, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
```

### Plugin version: 
`0.8.4+4`

### Platform
- [ ] Android
- [x] iOS

**Comment by maheshmnj** [comment] 2022-01-18 10:43
Hi @dark-chocolate, Thanks for filing the issue. I  ran the [official sample code](https://pub.dev/packages/image_picker/example) and I am not able to reproduce the issue. Neither on stable nor on the master channel.


https://user-images.githubusercontent.com/31410839/149922265-4e4e50fa-22be-4253-bc10-f3317e8bfc18.mov


 Please make sure you have added keys in the `info.plist`

> Add the following keys to your Info.plist file, located in <project root>/ios/Runner/Info.plist:

> NSPhotoLibraryUsageDescription - describe why your app needs permission for the photo library. This is called Privacy - Photo Library Usage Description in the visual editor.
NSCameraUsageDescription - describe why your app needs access to the camera. This is called Privacy - Camera Usage Description in the visual editor.
NSMicrophoneUsageDescription - describe why your app needs access to the microphone, if you intend to record videos. This is called Privacy - Microphone Usage Description in the visual editor.

If the issue persists please share the device/ simulator/ios version name on which you are having the issue.


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.384, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.384 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a3fd36a115 (3 days ago), 2022-01-14 20:40:17 -0500
    • Engine revision 83d99a5809
    • Dart version 2.17.0 (build 2.17.0-16.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android
      11 (API 30)
    • iPhone 12 (mobile)     • A047BAB5-CBE0-4DAF-962E-01A35B593FB5 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS
      12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
Thanks

**Comment by dark-chocolate** [comment] 2022-01-18 12:35
@maheshmnj 

I already have those permissions in `Info.plist` file. If I use previous version of `image_picker: 0.7.4`, the code works fine. So, it's definitely related to the current version.

**Comment by maheshmnj** [comment] 2022-01-18 13:42
Could you please check if this happens on any specific ios version or device? I am not able to reproduce this issue using 
`image_picker: ^0.8.4+4`. Allso, attach the output of `flutter run -v` in a text file

> If the issue persists please share the device/ simulator/ios version name on which you are having the issue.

**Comment by dark-chocolate** [comment] 2022-01-18 20:24
I was only seeing this issue in the Simulator. I updated my Flutter channel after I created this issue, so I can't give you the correct Flutter doctor information, but here it is for the new version: 

```
[✓] Flutter (Channel dev, 2.10.0-0.1.pre, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.10.0-0.1.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 628f0e3f3a (7 days ago), 2022-01-11 19:50:05 -0600
    • Engine revision 63ca99584a
    • Dart version 2.16.0 (build 2.16.0-134.1.beta)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK
    • Platform android-31, build-tools 31.0.0
    • Java binary at: 
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device
    • iPhone 8 (mobile) • 00EE6FDC-5A71-405E-9D9C-CB7472E15BED • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by qdmitry** [comment] 2022-01-19 07:56
M1 Pro, issue PlatformException(multiple_request, Cancelled by a second request, null, null)
First request not complete. And second error. Image not selected. iOS Sim.

**Comment by maheshmnj** [comment] 2022-01-19 08:27
<details>
<summary>flutter doctor -v</summary>

```
```
</details>

**Comment by maheshmnj** [comment] 2022-01-19 08:40
@dark-chocolate, I verified on the latest dev channel I still don't see any exception or error in the console. Please share the output of `flutter run -v`, This issue cannot be actionable without sufficient information.

https://user-images.githubusercontent.com/31410839/150093998-1714eaca-6800-45d2-80bd-e6348408adfc.mov


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 2.10.0-0.1.pre, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-0.1.pre at /Users/mahesh/Documents/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 628f0e3f3a (7 days ago), 2022-01-11 19:50:05 -0600
    • Engine revision 63ca99584a
    • Dart version 2.16.0 (build 2.16.0-134.1.beta)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 19EA5268-C931-4C3A-ACC6-71D3E849C450 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.71
    ! Device 192.168.1.2:5555 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


@qdmitry  can you please share your `flutter doctor -v`, the device on which the exception reproduces and the image picker plugin version ?

Thanks

**Comment by qdmitry** [comment] 2022-01-19 08:54
@maheshmnj 
**flutter doctor -v**
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-arm, locale ru-RU)
    • Flutter version 2.5.3 at /Users/dmitry/Develop/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/dmitry/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/dmitry/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • A5AC7C2B-A86B-4DE4-8A25-B66C88E79AB8 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)

Install -> `image_picker: ^0.8.4+4`

```
selectImage() async {
    print("Request ImagePicker");
    try {
      final file = await ImagePicker().pickImage(source: ImageSource.gallery);
      print("File after await");
      print(file);
    } catch (e) {
      print(e);
    }
  }
```

First request open modal gallery, select image, hide modal, and nothing console log print after await. 

Console log:
```
(2) flutter: Request ImagePicker
flutter: PlatformException(multiple_request, Cancelled by a second request, null, null)
```

**Comment by dark-chocolate** [comment] 2022-01-19 09:34
@maheshmnj 

As there were around 60,000 lines in `flutter run -v` output, I'm sharing the .txt file.


[logs.txt](https://github.com/flutter/flutter/files/7895826/logs.txt)

**Comment by maheshmnj** [comment] 2022-01-19 12:39
Thanks for the info labeling this issue for further investigation, I am unable to reproduce it.

**Comment by qdmitry** [comment] 2022-01-19 16:04
@maheshmnj Maybe it has something to do with get_x plugin?
I'm using it.

**Comment by jmagman** [comment] 2022-01-19 18:29
Because you are using `google_sign_in` (which doesn't support arm simulators) the app is being run with Rosetta on the simulator. 
This is really a Rosetta bug, so either Apple needs to fix it, or keep an eye on getting all your plugins to support the simulator.

Duplicate of https://github.com/flutter/flutter/issues/71943.

**Closed by jmagman** 2022-01-19 18:29 UTC
Labels: platform-ios, plugin, p: first party, p: image_picker, platform-host-arm

**Comment by dark-chocolate** [comment] 2022-01-19 23:50
@jmagman  Thanks so much for the insight 👍

**Comment by qdmitry** [comment] 2022-01-20 05:19
@jmagman @maheshmnj in iOS Sim 12.4 works! Apple crap! :)
