### ISSUE TITLE
 Warning  This release is not compliant with the Google Play 64-bit requirement

### ISSUE THREAD

**Issue by jayateertha043** [flutter/flutter#34986] opened 2019-06-24 11:47 UTC
I manually tried to upload aab file also tried codemagic
Both method fails ,i get 64 bit compliance warning publishing to playstore .

I need to upload to playstore soon kindly resolve this.

**Comment by BondarenkoStas** [comment] 2019-10-03 19:08
Duplicate of #32191

**Closed by BondarenkoStas** 2019-10-03 19:08 UTC
