### ISSUE TITLE
AnimatedContainer requires at least 2ms to change state even when duration is set to 0

### ISSUE THREAD

**Issue by devingryu** [flutter/flutter#86789] opened 2021-07-21 15:57 UTC
## Steps to Reproduce

```dart

class TextAnim extends StatefulWidget {
  const TextAnim({Key? key, required this.text}) : super(key: key);
  final text;

  @override
  _TextAnimState createState() => _TextAnimState();
}

class _TextAnimState extends State<TextAnim> {
  int _duration = 0;
  double _width = 50.0;

  Future<void> startAnim() async {
    setState(() {
      _duration=0;
      _width=0.0;
    });
    //await Future.delayed(Duration(milliseconds: 2));
    setState(() {
      _duration=2000;
      _width=50.0;
    });
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      width: _width,
      duration: Duration(milliseconds: _duration),
      child: Stack(
          clipBehavior: Clip.antiAlias,
          children: [
            Text(
                widget.text,
              maxLines: 1,
              softWrap: false,
              overflow: TextOverflow.clip,
            )
          ]
      ),
    );
  }
}
```
This is simple AnimatedContainer example to reproduce problem.

**Expected results:** 
Text width should change gradually (from 0 to 50) in 2 seconds when `startAnim()` is called.

**Actual results:** 
Nothing happens

Having term of 2ms between two `setState()` solves problem, but I want immediate change.
Is there a workaround for this problem?

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.71], locale ko-KR)
    • Flutter version 2.2.3 at C:\tools\Flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\IBD\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Java\jdk1.8.0_291\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\IBD\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.70

! Doctor found issues in 1 category.
```
</details>

**Comment by maheshmnj** [comment] 2021-07-22 11:56
Hi @devingryu, This is expected behavior and not a bug when you call setState the first time(without delay) the framework schedules a build and by the time it completes the first build you are scheduling another build by calling setState immediately and as a result, the framework is moving immediately to the next build Which is almost same as not calling the first `setState`

```
setState(() {
      _duration=0;
      _width=0.0;
    });
    //await Future.delayed(Duration(milliseconds: 2));
    setState(() {
      _duration=2000;
      _width=50.0;
    });
```
But when you add a slight delay the delay is sufficient enough for the framework to complete the first build and schedule another build. And In both the cases I was able to see a smooth animation for 2 seconds
I believe this is not an issue but an expected behavior you could see this by increasing the delay. 

Here is the complete code 

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: TextAnim(text: 'Hello'));
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  HomePageState createState() => HomePageState();
}

class HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey,
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [TextAnim(text: 'Hello')],
      ),
    );
  }
}

class TextAnim extends StatefulWidget {
  const TextAnim({Key? key, required this.text}) : super(key: key);
  final text;

  @override
  _TextAnimState createState() => _TextAnimState();
}

class _TextAnimState extends State<TextAnim> {
  int _duration = 0;
  double _width = 50.0;

  Future<void> startAnim() async {
    setState(() {
      _duration = 0;
      _width = 0.0;
    });
    // await Future.delayed(Duration(milliseconds: 2000), () {});
    setState(() {
      _duration = 2000;
      _width = 100.0;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          startAnim();
        },
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          AnimatedContainer(
            alignment: Alignment.center,
            width: _width,
            duration: Duration(milliseconds: _duration),
            child: Stack(clipBehavior: Clip.antiAlias, children: [
              Text(
                widget.text,
                maxLines: 1,
                softWrap: false,
                overflow: TextOverflow.clip,
              )
            ]),
          ),
        ],
      ),
    );
  }
}

```
</details>

Closing this issue as invalid, If you disagree feel free to comment and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-07-22 11:56 UTC
Labels: in triage

**Comment by devingryu** [comment] 2021-07-22 17:48
@maheshmnj, thank you for your kind comment.
So you mean there is no way to initialize and start animation without some delay?
Even slight delay is critical for my application(because synchronization breaks when delay is stacked), so code with 2s of delay is actually meaningless for me.
Is there any other workaround for this problem?

**Comment by maheshmnj** [comment] 2021-07-23 06:06
@devingryu, you are using [implicit animated widgets](https://flutter.dev/docs/codelabs/implicit-animations) which basically animates as soon as the property of the widget changes, If you need some delay and want complete control about when the animation starts and ends you should take a look at this [animation tutorial from the docs](https://flutter.dev/docs/development/ui/animations/tutorial), Which basically makes use of a animationController to control the animation.
