### ISSUE TITLE
Overflow error when calling showDatePicker function in flutter entry date mode

### ISSUE THREAD

**Issue by Trung15010802** [flutter/flutter#129506] opened 2023-06-25 09:22 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Call method showDatePicker
2. Change the dialog to input the date
3. Type the wrong format of the date

### Expected results

It must be run smoothly without error bottom overflow

### Actual results

![image](https://github.com/flutter/flutter/assets/90593296/c61751fd-0980-4dc9-807e-0259e03c4275)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```
showDatePicker(
              context: context,
              initialDate: DateTime.now(),
              firstDate: DateTime(2000),
              lastDate: DateTime(
                DateTime.now().year + 1,
              ),
              helpText: 'Select your history todo date!',
            );
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![image](https://github.com/flutter/flutter/assets/90593296/6bc93784-e211-4fd9-8790-208b4640541b)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
    • Flutter version 3.10.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (12 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\TTrung\AppData\Local\Android\sdk
    • Platform android-UpsideDownCake, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at C:\Users\TTrung\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 113.0.5672.129
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 114.0.1823.51

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by Hardenberg** [comment] 2023-06-25 09:57
to reproduce the issue you have to give more information e.g. `flutter doctor -v` or a `full functional example`. Thank u :)  

at first glance I wouldn't bet on a bug, rather on overlapping elements.

**Comment by danagbemava-nc** [comment] 2023-06-26 08:58
Hi @Trung15010802, this was initially reported in https://github.com/flutter/flutter/issues/127861. 

It has been fixed on the master/beta channels and the fix will be available on the stable channel. 

Closing this as a duplicate of the issue linked above.  

Thank you

**Closed by danagbemava-nc** 2023-06-26 08:58 UTC
Labels: in triage
