### ISSUE TITLE
Exception: Build process failed target kernel_snapshot failed : Exception   ubuntu , macOS desktop

### ISSUE THREAD

**Issue by gopiKrishnaPuligundla** [flutter/flutter#126759] opened 2023-05-14 05:53 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

just install flutter and run ur working desktop application either in MacBook or ubuntu .. both fails with above error

### Actual results

Target kernel_snapshot failed : Exception  
Exception: Build process failed 

### Logs

<details>
<summary>Logs</summary>

```console

Launching lib/main.dart on Linux in debug mode...
Building Linux application...
ERROR: ../../.pub-cache/hosted/pub.dev/printing-5.10.3/lib/src/widget_wrapper.dart:178:7: Error: No named parameter with the name 'window'.
ERROR:       window: view,
ERROR:       ^^^^^^
ERROR: ../../snap/flutter/common/flutter/packages/flutter/lib/src/rendering/view.dart:68:3: Context: Found this candidate, but the arguments don't match.
ERROR:   RenderView({
ERROR:   ^^^^^^^^^^
ERROR: Target kernel_snapshot failed: Exception
Exception: Build process failed

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

~$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.0, on Ubuntu 23.04 6.2.0-20-generic, locale
    en_US.UTF-8)
    • Flutter version 3.10.0 on channel stable at
      /home/gpuligun/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (5 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/gpuligun/Android/Sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 72.1.1
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 23.04 6.2.0-20-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-05-15 08:42
Hi @gopiKrishnaPuligundla, your issue is caused by the `printing` package. See https://github.com/DavBfr/dart_pdf/issues/1360

It seems like it has been fixed in the latest version so I would advise you upgrade your version. 

Closing from here as this is not a flutter issue. 

Thank you

**Closed by danagbemava-nc** 2023-05-15 08:42 UTC
Labels: in triage

**Comment by gopiKrishnaPuligundla** [comment] 2023-05-15 12:04
sure , thank you very much danagbemava
