### ISSUE TITLE
Tooltip cancels ink Ripple effect or other effects

### ISSUE THREAD

**Issue by muhammadkamel** [flutter/flutter#113418] opened 2022-10-14 06:15 UTC
Tooltip cancels ink Ripple effect or other effects this issue appears for a long time.

Please check #101958 for more info.

**Comment by huycozy** [comment] 2022-10-14 11:27
@muhammadkamel 
Closing this as a duplicate of #101958. Please do not file multiple issues for the same bug. Thanks!

**Closed by huycozy** 2022-10-14 11:27 UTC
Labels: in triage
