### ISSUE TITLE
Jittering on Flutter Apps (iOS) when switched 

### ISSUE THREAD

**Issue by msw333** [flutter/flutter#28113] opened 2019-02-18 19:00 UTC
**Tested on iPhone X, 12.1.4 - Flutter Stable:**
(see Video)
https://youtu.be/1mdM_Uv574w

When switching between apps (or launching the app), animations are jittering at the beginning - in particular, when scrolling through lists. I didn't test it on other devices. Experienced it both with the inKino app (made by a Googler) and my own app. Same is true on startup. Any idea on that?

**Comment by cybernik** [comment] 2019-02-18 23:03
i have the same problem too on iphone X (12.2)

**Comment by zoechi** [comment] 2019-02-19 07:06
Please add the output of `flutter doctor -v`.

Is this with debug or release builds?

**Comment by zoechi** [comment] 2019-02-19 07:08
Possible duplicate of #813

**Comment by msw333** [comment] 2019-02-19 08:56
release build:

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale de-DE)
    • Flutter version 1.0.0 at /Users/matthiaswolff/Desktop/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/matthiaswolff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • MSW                       • 64b6a2961593dc9e3ca2f157166e12286ecb75a9 • ios         • iOS 12.1.4
    • iPhone XR                 • 53D5005C-5C64-4F4D-9991-80550B214612     • ios         • iOS 12.1 (simulator)

**Comment by zoechi** [comment] 2019-02-19 10:04
Is this with debug or release builds?

**Comment by msw333** [comment] 2019-02-19 10:06
release builds

**Comment by zoechi** [comment] 2019-02-19 10:10
Did you test on a real device or only on the simulator?

**Comment by msw333** [comment] 2019-02-19 10:13
Real device. iPhone X, see video https://youtu.be/1mdM_Uv574w - issue is very noticeable and observable for my app as well as for the app inKino (made by a Googler). So it does not seem to be an issue in my code.

**Comment by zoechi** [comment] 2019-02-19 10:21
Right, I only looked at the `Connected device` list from `flutter doctor -v`.

> So it does not seem to be an issue in my code.

I don't think so. #813 is also still open.

**Comment by msw333** [comment] 2019-02-19 10:26
Ok. Well, it is an issue which makes awesome and butterly smooth Flutter apps not as shiny as they could be. Initial lag is highly observable on first start as well as when switching between apps without 'waiting for 1-2 seconds'. Much worse than shown in the video...

**Comment by frasza** [comment] 2019-03-05 21:15
Also experiencing same issues with iPhone XS.

**Comment by liyuqian** [comment] 2019-03-21 23:23
To allow us to better help you solve this issue, can you please:

1.  Run your app with `flutter run --profile --trace-skia`, save the trace from observatory timeline, and upload it here so we can take a deeper look?
2. Construct a single-file minimal Flutter app that can reproduce the issue. That way, we can test our fixes and maybe add it to our continuous performance benchmarks.

**Comment by liyuqian** [comment] 2019-03-24 18:02
I did reproduce it on iPhone 6S using the code in https://github.com/flutter/flutter/pull/27660#issuecomment-475826733

Below is the trace of the jittering scroll right after switching the app.
[dart-timeline-2019-2-24 (1).json.zip](https://github.com/flutter/flutter/files/3000641/dart-timeline-2019-2-24.1.json.zip)

Around 20s, I found two things:
1. Our in-memory compiled shader is gone after app switches on iOS. I suspect that it's caused by iOS memory management since if don't do a lot of things on the other app, then the compiled shader will still be there.
As a result, in the trace, the first frame right after switch is spending ~30ms on shader compilation. We can also tell that our persistent SKSL shader cache is working as we can see PersistentCacheLoadHit events. Without those, it will be more like 200-300ms shader compilation instead of 30ms shader compilation. Anyway, since this is the first frame, and it's just 30ms, I suspect that it's not the major reason of the jittering.

2. Right after that 30ms first frame, we're waiting for ~300ms before pumping the second frame. I believe this is the major reason of jittering. During that time, all our threads seem to be quite idle. @chinmaygarde : Is this expected on iOS? @bkonyi : I saw some `Engine::DispatchPointerDataPacket`, `Dart_InvokeClosure`, `RuntimeController::DispatchPointerDataPacket` during that 300ms before we issue the next vsync event; is there any suspicious Dart issue you can see from it?

**Comment by liyuqian** [comment] 2019-03-25 23:58
It seems that the 300ms gap could be just waiting for the user input events. So it may not be the issue. I'll reinvestigate the issue.

**Comment by i-schuetz** [comment] 2019-03-26 08:55
Moving the last gallery comments here as it seems more appropriate than in the [PR](https://github.com/flutter/flutter/pull/27660)

Attached the trace from opening the 4 items after closing the app.

Also attached videos, one for directly after launching and another for after closing. As @msw333 says they don't do it justice, but still clearly noticeable. It helps watching at 0.5 or 0.25 speed.

As mentioned before after closing is better, but there's still jank. 

In particular the 3d item it feels like it jumps directly to the open state. 

[trace_after_close.zip](https://github.com/flutter/flutter/files/3007199/trace_after_close.zip)

After launch: https://youtu.be/-gTVXqrJyqo
After close: https://youtu.be/P9CJ3gcyUW0

**Comment by liyuqian** [comment] 2019-03-26 17:51
Thanks @i-schuetz ! Your trace on the 3rd item after closing the app is especially informative.

Just to confirm:
1. your "after launch" means the first launch after an installation (or a clearing the app's data)
2. your "after close" means launch the app again after closing it

Right?

**Comment by i-schuetz** [comment] 2019-03-26 18:15
@liyuqian That's good to read. After launch means the first launch after installation. After close means launching the app after force-close (home button > swipe app out of the screen).

**Comment by msw333** [comment] 2019-04-04 22:42
https://github.com/liyuqian, you have any news for us? Desperately waiting.

**Comment by liyuqian** [comment] 2019-04-05 18:50
@msw333 : Sorry for the waiting. I got distracted by some other issues. Here's what I've found so far:

1. As https://github.com/flutter/flutter/issues/28113#issuecomment-476422065 mentioned, the 300ms gap I found earlier is actually because that I'm not touching the screen. Hence it's not a jank. I mistakenly thought it was a jank because our performance overlay seems to have a one-frame latency (i.e., the last blue bar is actually the second-last frame, not the last frame).

2. I did some tests again on iPhon6S with the performance overlay turned on. However, it seems that most of the times, there's no jank at all after switching: https://photos.app.goo.gl/2KjRRewZsFHYhgzM6

3. Sometimes I do see a big jank (~100ms) but that seems to have nothing to do with switching or starting the app. It usually happens after many scrollings, and it can be reproduced without switching the app. See 
[dart-timeline-2019-3-5.json.zip](https://github.com/flutter/flutter/files/3049199/dart-timeline-2019-3-5.json.zip) at about 309 seconds. I'm not sure if it's the same issue here. Nevertheless it's something that we need to fix (probably by creating a new issue).

As those findings didn't help much in fixing this, can you please help us get a little more information:

1. Run your reproduction app (in https://github.com/flutter/flutter/pull/27660#issuecomment-475826733) using the master branch tip-of-the-tree Flutter in profile mode.
2. Turn on performance overlay (by pressing 'P' on your `flutter run --profile` command line) so we can know exactly which thread is causing the jank.
3. Reproduce the jank after switching, and post the video and the trace here.

I understand your frustration as it's still not fixed. I also desperately want to fix it and I'm frustrated too when I can't reproduce it and find something useful on my iPhone6S. Hopefully that we can learn something useful soon after your new video and trace.

**Comment by i-schuetz** [comment] 2019-04-06 20:22
@liyuqian What about the gallery issues?

**Comment by liyuqian** [comment] 2019-04-06 23:12
@i-schuetz: I just filed https://github.com/flutter/flutter/issues/30625. The issue that you reported seems to be a big one. We're working on it.

**Comment by msw333** [comment] 2019-04-06 23:24
Issue is highly increased when having a more complex logic. In my chat app, which is using Streambuilder, CachedNetworkImage + Firestore etc..., I saw currently no other solution: I am displaying a 3sec ‚loading splashscreen‘ with a timer. After that, it is completely smooth. Issue is highly present on first startup + app switching on my iPhone X. 

App is 50+ dart files, so I cannot easily put a reproducible code together...but I can assure that the reproducible code I was providing only shows a minimal effect. Really hope that and i-schuetz‘s input is helping.

**Comment by liyuqian** [comment] 2019-04-06 23:49
@i-schuetz : ignore https://github.com/flutter/flutter/issues/30625, I forgot `--profile`. Nevertheless, I both your trace and my profile trace show problems in UI thread with frame build time. So I'm going to have a deeper look into that.

**Comment by i-schuetz** [comment] 2019-04-07 18:12
@liyuqian Great! I join @msw333 in hoping that there will be a fix soon. At the moment I'm unable to recommend Flutter to clients, because of this.

**Comment by liyuqian** [comment] 2019-04-07 18:46
I found that the image is only costing less than 5ms so it's not the biggest problem. The font loading is costing more than 50ms:

<img width="1120" alt="Screen Shot 2019-04-07 at 11 37 11 AM" src="https://user-images.githubusercontent.com/22987568/55688090-9f245380-5929-11e9-803f-09a040fde1d2.png">

I'm adding traces for that: https://github.com/flutter/engine/pull/8477 . Once that engine PR is in the framework, you can also test your app to see if font loading is the culprit.

If that's the case, this would be a duplicate of https://github.com/flutter/flutter/issues/19350 .

We'll discuss and figure out a plan to solve it on Monday when the font experts come back.

**Comment by yunyu** [comment] 2019-04-25 18:19
Here is a single file test app which exhibits this issue more clearly: https://github.com/yunyu/flutter_scroll_stutter_test/blob/master/lib/main.dart

**Comment by liyuqian** [comment] 2019-04-29 22:39
@yunyu : Thank you very much for your example app! I did reproduced the stutter on an iPhone X, and it didn't stutter on an iPhone 6S. Given that it only happened on iPhone X, let's continue the discussion in https://github.com/flutter/flutter/issues/31086#issuecomment-487768379

**Comment by luckysmg** [comment] 2019-07-07 02:13
My iPhoneX has the same problem!! It is very apparent when launching the apps or switching apps from background to foreground——the frames drop...

**Comment by liyuqian** [comment] 2019-08-07 17:25
Close this as this issue is a duplicate to
- either https://github.com/flutter/flutter/issues/31086 for the iPhonX/XS only scroll jank
- or https://github.com/flutter/flutter/issues/19350 for the start-up jank

**Closed by liyuqian** 2019-08-07 17:25 UTC
Labels: engine, framework, severe: performance, ⌺‬ platform-ios
