### ISSUE TITLE
didUpdateWidget does not provide oldWidget, but the new widget instead

### ISSUE THREAD

**Issue by GGGuenni** [flutter/flutter#106743] opened 2022-06-28 16:41 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Press the + Button (Nothing happens on screen)
3. Look into the console to see both `oldWidget.colors` and `widget.colors` being the same

**Expected results:** 
`didUpdateWidget(oldWidget)` should provide the old widget, containing only `"Blue"`, `"Orange"` and `"Yellow"`.
The colors lists should be different from each other thus adding "Pink" as a Text Widget.

**Actual results:**
`oldWidget` is the same as `widget`.
Both lists are the same resulting in `"Pink"` not getting added as a Text Widget.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DidUpdateWidget Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'DidUpdateWidget Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<String> _colors = ["Blue", "Orange", "Yellow"];

  void _updateWidget() {
    setState(() {
      _colors.add("Pink");
      _colors.add("Orange");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: SubWidget(colors: _colors)
      ),
      // This button should add pink to the _colors list of SubWidget
      floatingActionButton: FloatingActionButton(
        onPressed: _updateWidget,
        tooltip: 'Add Colors',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class SubWidget extends StatefulWidget {
  const SubWidget({Key? key, required this.colors}) : super(key: key);

  final List<String> colors;

  @override
  State<SubWidget> createState() => _SubWidgetState();
}

class _SubWidgetState extends State<SubWidget> {

  final List<String> _colors = List.empty(growable: true);

  @override
  void initState() {
    super.initState();
    _colors.addAll(widget.colors);
  }

  @override
  void didUpdateWidget(covariant SubWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    // oldWidget.colors and widget.colors are the same
    print("OldWidget color list: ${oldWidget.colors}");
    print("NewWidget color list: ${widget.colors}");

    // We only want to add colors which are not yet added to the list
    for (var color in widget.colors.where((e) => !oldWidget.colors.contains(e))) {
      _colors.add(color);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: _colors.map((e) => Text(e)).toList(),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.19044.1766], locale de-DE)
    • Flutter version 3.0.3 at C:\Programming\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (6 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Programming\Android
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Programming\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.11)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32228.343
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Programming\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.60.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 102.0.1245.44

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by huycozy** [comment] 2022-06-29 05:28
Hi @GGGuenni, thanks for filing the issue. 
This issue is reproducible on the latest `stable` and `master` channels with provided sample code.

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/176358432-76143ca1-3067-4d73-833f-6c97cb7630a7.mp4


</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.3 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (11 hours ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.5 19F77
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1419, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1419 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9c0f239947 (87 minutes ago), 2022-06-28 19:31:27 -0700
    • Engine revision 7635ee96b7
    • Dart version 2.18.0 (build 2.18.0-232.0.dev)
    • DevTools version 2.14.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by bleroux** [comment] 2022-06-29 06:16
Hi! 
This issue is not that oldWidget and new widget are the same, it is related to both widgets sharing the same `List` instance.

Here is the code sample with two additional print statements: 
<details>
<summary>Updated code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DidUpdateWidget Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'DidUpdateWidget Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<String> _colors = ["Blue", "Orange", "Yellow"];

  void _updateWidget() {
    setState(() {
      _colors.add("Pink");
      _colors.add("Orange");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: SubWidget(colors: _colors)
      ),
      // This button should add pink to the _colors list of SubWidget
      floatingActionButton: FloatingActionButton(
        onPressed: _updateWidget,
        tooltip: 'Add Colors',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class SubWidget extends StatefulWidget {
  const SubWidget({Key? key, required this.colors}) : super(key: key);

  final List<String> colors;

  @override
  State<SubWidget> createState() => _SubWidgetState();
}

class _SubWidgetState extends State<SubWidget> {

  final List<String> _colors = List.empty(growable: true);

  @override
  void initState() {
    super.initState();
    _colors.addAll(widget.colors);
  }

  @override
  void didUpdateWidget(covariant SubWidget oldWidget) {
    super.didUpdateWidget(oldWidget);

    print("oldWidget == widget returns ${oldWidget == widget}");
    print("oldWidget.colors == widget.colors returns ${oldWidget.colors == widget.colors}");

    // oldWidget.colors and widget.colors are the same
    print("OldWidget color list: ${oldWidget.colors}");
    print("NewWidget color list: ${widget.colors}");

    // We only want to add colors which are not yet added to the list
    for (var color in widget.colors.where((e) => !oldWidget.colors.contains(e))) {
      _colors.add(color);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: _colors.map((e) => Text(e)).toList(),
    );
  }
}
```
</details>

It will print the following

```
flutter: oldWidget == widget returns false
flutter: oldWidget.colors == widget.colors returns true
flutter: OldWidget color list: [Blue, Orange, Yellow, Pink, Orange]
flutter: NewWidget color list: [Blue, Orange, Yellow, Pink, Orange]
```

One solution is to send a new `List` instance to `SubWidget` :

<details>
<summary>Fixed code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DidUpdateWidget Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'DidUpdateWidget Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<String> _colors = ["Blue", "Orange", "Yellow"];

  void _updateWidget() {
    setState(() {
      _colors.add("Pink");
      _colors.add("Orange");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: SubWidget(colors: List.from(_colors))
      ),
      // This button should add pink to the _colors list of SubWidget
      floatingActionButton: FloatingActionButton(
        onPressed: _updateWidget,
        tooltip: 'Add Colors',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class SubWidget extends StatefulWidget {
  const SubWidget({Key? key, required this.colors}) : super(key: key);

  final List<String> colors;

  @override
  State<SubWidget> createState() => _SubWidgetState();
}

class _SubWidgetState extends State<SubWidget> {

  final List<String> _colors = List.empty(growable: true);

  @override
  void initState() {
    super.initState();
    _colors.addAll(widget.colors);
  }

  @override
  void didUpdateWidget(covariant SubWidget oldWidget) {
    super.didUpdateWidget(oldWidget);

    print("oldWidget == widget returns ${oldWidget == widget}");
    print("oldWidget.colors == widget.colors returns ${oldWidget.colors == widget.colors}");

    // oldWidget.colors and widget.colors are the same
    print("OldWidget color list: ${oldWidget.colors}");
    print("NewWidget color list: ${widget.colors}");

    // We only want to add colors which are not yet added to the list
    for (var color in widget.colors.where((e) => !oldWidget.colors.contains(e))) {
      _colors.add(color);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: _colors.map((e) => Text(e)).toList(),
    );
  }
}
```

</details> 

which prints
```
flutter: oldWidget == widget returns false
flutter: oldWidget.colors == widget.colors returns false
flutter: OldWidget color list: [Blue, Orange, Yellow]
flutter: NewWidget color list: [Blue, Orange, Yellow, Pink, Orange]
```

**Comment by goderbauer** [comment] 2022-06-29 21:56
@bleroux's explanation is correct. Since there is no bug here, I am going to close this.

**Closed by goderbauer** 2022-06-29 21:56 UTC
Labels: waiting for customer response, framework, has reproducible steps, found in release: 3.0, found in release: 3.1
