### ISSUE TITLE
TextField cursor on iOS displayed twice

### ISSUE THREAD

**Issue by ChristianPauly** [flutter/flutter#57787] opened 2020-05-22 07:06 UTC
![IMG_6313](https://user-images.githubusercontent.com/24619905/82640663-45edb100-9c0b-11ea-89a8-0890addb997d.PNG)

## Steps to Reproduce

Unclear... appears randomly.

**Expected results:** Only one cursor

**Actual results:** Two cursors
No errors in the logs :-(

```
```
Analyzing app...                                                        
No issues found! (ran in 33.6s)
```
Flutter Doctor on other machine. Sorry, can't reach my macbook until next week.
```
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.17.1 at /home/krille/Lokal/HADTF/flutter_linux_v1.2.1-stable/flutter
    • Framework revision f7a6a7906b (vor 9 Tagen), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/krille/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/88/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-05-22 09:58
Hi @ChristianPauly 

>Steps to Reproduce
Unclear... appears randomly.

With this the issue is hardly actionable. Could you try to notice some pattern of what and how you are typing/selecting and check if it happens with another locale / another device 

<details>
 <summary>/ with the minimal code sample containing only TextField?</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

</details>

**Comment by TahaTesser** [comment] 2020-06-12 13:07
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-12 13:07 UTC
Labels: in triage, waiting for customer response

**Comment by hr1995** [comment] 2020-06-23 09:43
I also has the same problem, appears randomly too, both in iOS and android devices while developing flutter web.
