### ISSUE TITLE
Add convenience method to pop to root

### ISSUE THREAD

**Issue by bibhas2** [flutter/flutter#15135] opened 2018-03-04 17:20 UTC
## Steps to Reproduce

```
flutter --version
Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (10 days ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```

The ``Navigator`` class needs to provide a way to pop to the root of the stack. The ``popUntil()`` method may not do the job in certain situations where the widget that is in the root also appears in the middle of the stack. For example, let's say that the stack is currently:
```
[HomePage, ProductPage, HomePage, ProductDetailsPage]
```

And we wish to go back to the root of the stack. This is basically what ``UINavigationController. popToRootViewController`` does. It is possible to work around the limitation but it will be very useful to have a ``poptoRoot()`` method in the ``Navigator`` class.

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[!] VS Code (version 1.20.1)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
```

**Comment by CrazyStaff** [comment] 2018-03-05 19:26
I have the same problem.

**Comment by kentcb** [comment] 2018-03-09 05:12
Not to mention `popToRoot` is often what you want and it's much easier to write than using `popUntil`. i.e. make the common things easy.

**Comment by dexcell** [comment] 2018-03-31 19:25
This is very important feature that need to be implemented asap.

**Comment by goderbauer** [comment] 2018-12-28 21:08
Can you just do:

```dart
Navigator.popUntil(context, (Route<dynamic> route) => route.isFirst)
```

Do you need anything else?

See also: https://master-docs.flutter.io/flutter/widgets/Route/isFirst.html

**Comment by amrnt** [comment] 2018-12-28 21:50
@goderbauer `popUntil` will animate all the pops. I don't think this is the expected behavior.

**Comment by bibhas2** [comment] 2018-12-29 14:41
> Can you just do:
> 
> ```dart
> Navigator.popUntil(context, (Route<dynamic> route) => route.isFirst)
> ```
> 
> Do you need anything else?
>

This will probably solve the problem (I haven't had a chance to try this out. But on a matter of principle this seems to work). 

However, the API is somewhat more complex than it has to be. I still vote for a ``popToRoot()`` method that hides the code above.

**Comment by amrnt** [comment] 2019-09-29 01:05
I think for now this is the most efficient:

```
Navigator.pushNamedAndRemoveUntil(context, '/', (_) => false);
```

The tricky part is the animation: looks like a push not a pop or replace.

**Comment by amrnt** [comment] 2019-12-21 14:39
hacky tip: 
If you are using a lib like https://pub.dev/packages/sailor, you can create a trick to get this as expected:

```
                  Routes.sailor.navigate(
                    '/splash',
                    navigationType: NavigationType.pushAndRemoveUntil,
                    removeUntilPredicate: (_) => false,
                    transitions: [
                      SailorTransition.slide_from_left,
                    ],
                  );
```

**Comment by chunhtai** [comment] 2020-05-28 21:43
We are in the middle of implement router widget which can leverage the pages api https://master-api.flutter.dev/flutter/widgets/Navigator/pages.html
We currently don't have plan to extend the imperative api (push/pop/popuntil and friends). Closing this as there will be no further action

**Closed by chunhtai** 2020-05-28 21:43 UTC
Labels: f: routes, framework, severe: new feature
