### ISSUE TITLE
Flutter project to place platform-specific directories in a single root directory

### ISSUE THREAD

**Issue by scopendo** [flutter/flutter#93593] opened 2021-11-13 12:03 UTC
## Use case

As Flutter expands more platforms, the root level of a Flutter project becomes busier, for example, with `android`, `ios`, `macos` and `web` platform-specific directories.

I suggest that it would be easier to quickly parse a Flutter project's in tools such as Android Studio's Project view if these platform-specific directories were contained within a single root directory.

## Proposal

Enhance the tooling so that these platform-specific directories are contained within a `platforms` directory, falling back to the existing structure if a `platforms` directory is not present.

Although it should still be possible to open the platform-specific runner projects as currently, it would also be useful to add menu items for opening these runner projects – for example, in Android Studio, menu items might be added to the Tools | Flutter sub-menu.

**Comment by stuartmorgan** [comment] 2021-11-13 17:26
Duplicate of https://github.com/flutter/flutter/issues/34536

**Closed by stuartmorgan** 2021-11-13 17:26 UTC
