### ISSUE TITLE
Slider, divisions: 175 / 350, the result is not always 0.5. Is that ok by default?

### ISSUE THREAD

**Issue by haizen007** [flutter/flutter#57886] opened 2020-05-24 08:51 UTC
Hey, if I didn't make any mistake the **Slider** when using the **divisions** set to **175 / 350** should have as a result a double increasing or decreasing by **0.5**, right?

```
                              child: Slider(
                                value: weight,
                                min: 25,
                                max: 200,
                                divisions: 350,
                                // activeColor: Color(0xFFEB1555),
                                onChanged: (double newValue) {
                                  setState(() {
                                    weight = newValue;
                                  });
                                },
                              ),
```
![flutter-slider-bug](https://user-images.githubusercontent.com/8696641/82749761-23e36280-9db4-11ea-974b-f54d2deb8566.png)

**Comment by TahaTesser** [comment] 2020-05-25 12:08
Hi @haizen007 

Please try code sample

<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  double weight = 50;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(weight.round().toString()),
            Slider(
              value: weight,
              min: 25,
              max: 200,
              divisions: 350,
              // activeColor: Color(0xFFEB1555),
              onChanged: (double newValue) {
                setState(() {
                  weight = newValue;
                });
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
 
``` 

</details> 

This is probably due to drag precision

Thank you

**Comment by haizen007** [comment] 2020-05-25 12:52
Hey, thanks, I solved using:
`weight.toStringAsFixed(1),`
But my point is, I thought Flutter by default wouldn't need to do that because sometimes was:
**128.0
128.5**
Was ok, but sometimes:
**127.9999999...**
so it's strange behavior.

**Comment by HansMuller** [comment] 2020-05-26 15:54
CC @clocksmith

**Comment by clocksmith** [comment] 2020-11-05 15:34
Duplicate of https://github.com/flutter/flutter/issues/39510

**Comment by TahaTesser** [comment] 2021-01-20 12:56
Closing as duplicate of https://github.com/flutter/flutter/issues/39510

**Closed by TahaTesser** 2021-01-20 12:56 UTC
Labels: f: material design, found in release: 1.19, framework, has reproducible steps
