### ISSUE TITLE
HttpException (HttpException: Failed to parse header value)

### ISSUE THREAD

**Issue by subbbbbaru** [flutter/flutter#115086] opened 2022-11-10 16:22 UTC
Hello! I want to write a mobile application for a keenetic router. But I get an HttpException (HttpException: Failed to parse header value) error when I make a request to the Keenetic router.

 ```
 void httpp() async {
    HttpClient httpClient = new HttpClient();
    HttpClientRequest request =
        await httpClient.get('192.168.1.1', 80, '/auth');
    // it's polite to send the body length to the server

    request.headers.set('Accept-Encoding', '*', preserveHeaderCase: true);
    request.headers.set('Accept', '*/*', preserveHeaderCase: true);
    request.headers
        .set('Transfer-Encoding', 'chunked', preserveHeaderCase: true);
    request.headers.set('Connection', 'keep-alive', preserveHeaderCase: true);
    HttpClientResponse response = await request.close(); // HttpException (HttpException: Failed to parse header value)
    final chunks = await response.transform(utf8.decoder).toList();
    final bbb = chunks.join(',');
    httpClient.close();
    print(bbb);
    print(response);
  }
```

I verified via Wireshark that the request is being processed and I am getting a response headers like this:
`{'Server': 'Web server', 'Date': 'Thu, 29 Sep 2022 22:21:56 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set -Cookie': 'TMAKGAGUCQNB=HHMDXTJAKYRNHCNS; Path=/', 'WWW-Authenticate': 'x-ndw2-interactive realm="Keenetic Air" challenge="MQWUWIVNDDMINFPVMUOBNWFSIRBGPTKI" session_id="HHMDXTJAKYRNHCNS" session_cookie="TMAKGAGUCQNB"', 'X-NDM-Realm': 'Keenetic Air', 'X-NDM-Challenge': 'MQWUWIVNDDMINFPVMUOBNWFSIRBGPTKI'}`

But he still couldn't solve the problem. I will be grateful for help.

[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-arm, locale ru-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_arm64"

**Comment by huycozy** [comment] 2022-11-11 07:56
Hi @subbbbbaru 
From what I can see, the issue is related to `dart` rather than to Flutter framework. It will be better to report to have support there. 
I also see your filed issue https://github.com/dart-lang/sdk/issues/50433 and there is also another issue https://github.com/dart-lang/sdk/issues/46442, so please follow up on it for further updates.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.

**Closed by huycozy** 2022-11-11 07:56 UTC
Labels: in triage
