### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: 目录不是空的。, errno = 145

### ISSUE THREAD

**Issue by lixp185** [flutter/flutter#98855] opened 2022-02-21 07:02 UTC
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: 目录不是空的。
, errno = 145
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:486:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:485:12)
#6      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:82:12)
#7      AndroidProject._regenerateLibrary (package:flutter_tools/src/project.dart:525:29)
#8      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:500:13)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:315:21)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:177:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure

**Comment by darshankawar** [comment] 2022-02-21 11:27
Closing this as duplicate of https://github.com/flutter/flutter/issues/64410

**Comment by lixp185** [comment] 2022-02-21 11:27
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Closed by darshankawar** 2022-02-21 11:27 UTC
Labels: in triage
