### ISSUE TITLE
The text is displayed outside the RenderParagraph 

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#87943] opened 2021-08-09 09:41 UTC
Our customers used some special characters, which caused the text to be displayed outside

The `TextView` of the Android platform does not have this problem, may be related to this line of code https://android.googlesource.com/platform/frameworks/base/+/jb-mr0-release/core/java/android/widget/TextView.java#4852

If you make `_needsClipping` true, the text will also be displayed in the box
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/paragraph.dart#L727
text is 
```
 ๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊h  ๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊e  ๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊l  ๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊l  ๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊o  ๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊
```

<img src="https://user-images.githubusercontent.com/31977171/128686965-822e9f58-4fdb-4205-b511-637908cd74ed.png" height="450" />	

## Steps to Reproduce
https://github.com/ColdPaleLight/flutter_example_87943

**Expected results:** The text is displayed inside the RenderParagrash

**Actual results:** The text is displayed outside the RenderParagrash

<details>
  <summary>Logs</summary>

flutter doctor -v
```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.8, on macOS 11.1 20C69 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.5.0-6.0.pre.8 at /Users/haoan/Develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1922052e90 (4 days ago), 2021-08-05 06:00:03 -0400
    • Engine revision 2c45b6e652
    • Dart version 2.14.0 (build 2.14.0-382.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/haoan/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • ELS AN00 (mobile) • UQG5T20413009690 • android-arm64  • Android 10 (API
      29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      92.0.4515.131

! Doctor found issues in 2 categories.
```

</details>

**Comment by xiaoxiaowesley** [comment] 2021-08-09 13:18
Simplist reproduce code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                ' ๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊๊test',
              ),
            ],
          ),
        ), // This trailing comma makes auto-formatting nicer for build methods.
      ),
    );
  }
}


```

**Comment by TahaTesser** [comment] 2021-08-10 11:49
Hi @ColdPaleLight  @xiaoxiaowesley 
Thanks for filing the issue and code sample

I'm able to reproduce the issue on other platforms other than the web (root cause might be different)


### Android  (`beta` to `master`)
<img src="https://user-images.githubusercontent.com/48603081/128858698-946b58b0-a40b-4d1e-8809-b76574971df8.jpg" height="250" />
![Screenshot_2021-08-10-13-47-19-728_com example triage]()

### Web (canvaskit) on `macOS`, `Linux` and `windows` 
| `stable` | `beta` to `master` on Linux & macOS | `beta` to `master` on Windows | 
| --------------- | --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/128858931-59fb37e1-9314-4870-91a1-138724b86e83.png" height="250" /> | <img src="https://user-images.githubusercontent.com/48603081/128858989-f6184165-0e64-4eda-96c0-c50e1eb0b69f.png" height="250" /> | <img src="https://user-images.githubusercontent.com/48603081/128859457-d4d3708b-4e07-49f2-9544-8bcd847dd59c.png" height="250" />	|
As seen as above, looks like a regression from the `beta` channel in canvaskit.


### Web (HTML) on `macOS` and `windows`  (no issue for HTML renderer on Linux)
| `stable` to `master` on Windows | `stable` to `master` on macOS | 
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/128859829-98f0137b-8684-44e4-8b30-b461012b66bc.png" height="250" /> | <img src="https://user-images.githubusercontent.com/48603081/128859878-b78de753-7b13-413c-ba24-ab55644be503.png" height="250" /> |'


iOS and macOS
| `stable` to `master` on iOS | `stable` to `master` on macOS/iPad | 
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/128861082-7bbbc7ce-25ae-4b11-819a-68aa0b21698b.PNG" height="250" /> | <img src="https://user-images.githubusercontent.com/48603081/128860769-7a77b34b-5717-480d-a112-92ac0fa74215.png" height="250" /> |


|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0
    • iPhone 12 (mobile)     • 3C173470-A5A2-45F2-BF7B-79B8218E717C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.5.0-6.0.pre.40, on macOS 12.0 21A5294g darwin-x64, locale en-GB)
    • Flutter version 2.5.0-6.0.pre.40 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7d76a827c0 (13 hours ago), 2021-08-09 15:21:17 -0700
    • Engine revision 4fef55db10
    • Dart version 2.14.0 (build 2.14.0-385.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5201i
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 15.0 19A5307g
    • iPhone 12 (mobile)     • 3C173470-A5A2-45F2-BF7B-79B8218E717C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```
		
</details>

✅: No Issue ❌: Issue reproduced

**Comment by gspencergoog** [comment] 2021-08-12 18:22
cc @GaryQian Is this Thai vowels acting correctly? In which case, perhaps Linux is the one that is not acting as intended?

**Comment by GaryQian** [comment] 2021-08-12 18:40
This is indeed Thai vowels acting correctly. Unfortunately, Thai is frequently abused to create posts like this.

A simple workaround is to wrap the text with a clipping widget with a small edge inset border. This can prevent extreme overdraws but still allow things like cursive fonts and other various glyphs to show.

**Comment by yjbanov** [comment] 2021-08-12 22:12
Changing this to a framework issue. If we decide there's work to do on the engine side, let's file issues for the specific variants of the engine so the can be fixed independently.

/cc @goderbauer

**Comment by gspencergoog** [comment] 2021-08-12 23:15
I actually think this is "as designed", at least for all the platforms except Linux, which is apparently not handling the Thai vowels properly.

Ironically, the bug is that it's not doing what the OP thought of as the bug.

**Comment by ColdPaleLight** [comment] 2021-08-28 06:00
Our current workaround is to wrap the `Text` with a `ClipRect` as @GaryQian said.

**Comment by goderbauer** [comment] 2022-04-06 22:02
From the discussion above, I am closing this as working-as-intended (and if you want this to work differently, you can apply a manual clip as also discussed above).

**Closed by goderbauer** 2022-04-06 22:02 UTC
Labels: a: text input, framework, customer: alibaba, a: typography, has reproducible steps, found in release: 2.2, found in release: 2.5
