### ISSUE TITLE
DropdownMenu doesn't work

### ISSUE THREAD

**Issue by rohit-00004** [flutter/flutter#135573] opened 2023-09-27 09:48 UTC
### Getting size not defined error on using the new Dropdownmenu

The following assertion was thrown building DropdownMenu<String>(dirty, dependencies: [Directionality, _InheritedTheme, _LocalizationsScope-[GlobalKey#bc5a7]], state: _DropdownMenuState<String>#16b83):
RenderBox was not laid out: RenderMouseRegion#ebc00 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
box.dart:1
Failed assertion: line 1966 pos 12: "hasSize" 

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
DropdownMenu<String>
When the exception was thrown, this was the stack
#2      RenderBox.size
box.dart:1966
#3      _DropdownMenuState.getWidth
dropdown_menu.dart:361
#4      _DropdownMenuState.build
dropdown_menu.dart:513
#5      StatefulElement.build
framework.dart:5198
#6      ComponentElement.performRebuild
framework.dart:5086
#7      StatefulElement.performRebuild
framework.dart:5251
#8      Element.rebuild
framework.dart:4805
#9      BuildOwner.buildScope
framework.dart:2780
#10     WidgetsBinding.drawFrame
binding.dart:903
#11     RendererBinding._handlePersistentFrameCallback
binding.dart:358
#12     SchedulerBinding._invokeFrameCallback
binding.dart:1284
#13     SchedulerBinding.handleDrawFrame
binding.dart:1214
#14     SchedulerBinding._handleDrawFrame
binding.dart:1072
#15     _invoke (dart:ui/hooks.dart:142:13)
#16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#17     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)

**Comment by dam-ease** [comment] 2023-09-27 10:09
Hi @rohit-00004  
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

I am closing this issue since little or no information has been provided. Once you update the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!

**Closed by dam-ease** 2023-09-27 10:09 UTC
Labels: in triage
