### ISSUE TITLE
The RefreshProgressIndicator can not display when put RefreshIndicator under a TabBarView

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15197] opened 2018-03-06 08:46 UTC
I have 3 `ListView`, so I create a page just like the `TabBarView` Demo in Gallery Sample.
But I found there are serveral bugs: 

1. If I set the `unselectedLabelStyle` to `regular` and set `labelStyle` to `medium`, the display is strange, only one `unselectedLabel` updated.

2. if the `ListView` has only few items, can not scroll up and down.

3. The `RefreshProgressIndicator` can not display, if I set `displacement = 80`, then I could see it, but the position is wrong.

**Comment by zoechi** [comment] 2018-03-06 08:52
Can you please provide the code that allows to reproduce?
What Flutter version are you using (`flutter doctor -v` output)

**Comment by realcarlos** [comment] 2018-03-09 03:52
OK

[✓] Flutter (Channel master, v0.0.23-pre.40, on Mac OS X 10.13.2 17C88, locale zh-Hans-CN)
    • Flutter version 0.0.23-pre.40 at /Users/carlos/Documents/GitHub/flutter
    • Framework revision fe9e074581 (4 days ago), 2018-03-02 12:39:29 +0800
    • Engine revision 269bab73b6
    • Dart version 2.0.0-dev.31.0.flutter-1aaebedd70

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/carlos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/carlos/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1


It is easy to reproduce 


@override
  Widget build(BuildContext context) {
    return new DefaultTabController(
      length: _allPages.length,
      child: new Scaffold(
        backgroundColor: Colors.grey,
        drawer: new Drawer(),
        body: new NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              new SliverOverlapAbsorber(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                child: new SliverAppBar(
                  backgroundColor: Colors.white,
                  leading: new Builder(builder: (BuildContext context) {
                    return new IconButton(
                        color: Colors.black,
                        icon: new Icon(Icons.menu),
                        onPressed: () {
                          Scaffold.of(context).openDrawer();
                        });
                  }),
                  iconTheme: Theme.of(context).iconTheme,
                  textTheme: Theme.of(context).textTheme,
                  centerTitle: true,
                  title: const Text('Test'),
                  expandedHeight: 96.0,
                  pinned: true,
                  forceElevated: innerBoxIsScrolled,
                  bottom: new TabBar(
                    unselectedLabelColor: Colors.grey,
                    unselectedLabelStyle: Font.medium(size: 14.0),
                    labelColor: Colors.black,
                    labelStyle: Font.medium(size: 14.0),
                    indicatorColor: Colors.black,
                    tabs: _allPages.keys.map(
                          (_OrderListPage page) => new Tab(text: page.label),
                    ).toList(),
                  ),
                ),
              ),
            ];
          },
          body: new TabBarView(
            children: _allPages.keys.map((_OrderListPage page) {
              return new Builder(
                  builder: (BuildContext context) {
                    return new RefreshIndicator(
                      onRefresh: () {
                        print('onReresh');
                      },
                      child: new CustomScrollView(
                      //physics: myScrollPhysics,
                      key: new PageStorageKey<_OrderListPage>(page),
                      slivers: <Widget>[
                        new SliverOverlapInjector(
                          handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                        ),
                        new SliverPadding(
                          padding: const EdgeInsets.symmetric(
                            vertical: 0.0,
                            horizontal: 0.0,
                          ),
                          sliver: new SliverFixedExtentList(
                            itemExtent: 92.0,
                            delegate: new SliverChildBuilderDelegate(
                                  (BuildContext context, int index) {
                                return new Container(
                                    decoration: new BoxDecoration(
                                        color: Colors.white,
                                        border: new Border(bottom: new BorderSide(color: Colors.grey))
                                      //borderRadius: new BorderRadius.circular(10.0),
                                    ),
                                  child: buildListTile(context, "$index")
                                );
                              },
                              childCount: 200,
                            ),
                          ),
                        ),
                      ],
                    ),
                    );
                  },
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}

**Comment by zoechi** [comment] 2018-03-09 04:46
can you please wrap the code in ``` to make it readable?

**Comment by realcarlos** [comment] 2018-03-14 04:26
yes no problem

**Comment by swipesight** [comment] 2018-09-05 15:38
I found that can use two Transform widgets to workaround the RefreshIndicator displaying problem.
```
var yOffset = NestedScrollView.sliverOverlapAbsorberHandleFor(context).layoutExtent;

...

Transform.translate(
  offset: Offset(0.0, yOffset),
  child: RefreshIndicator(
    onRefresh: () async { ... },
    child: Transform.translate(
      offset: Offset(0.0, -yOffset),
      child: new CustomScrollView( ... ),
    ),
  ),
)

...

```

**Comment by zoechi** [comment] 2019-02-13 18:08
2. needs https://docs.flutter.io/flutter/widgets/AlwaysScrollableScrollPhysics-class.html as far as I know.

**Comment by TahaTesser** [comment] 2020-05-20 14:09
Hi @realcarlos 
I can reproduce the titled issued and using `AlwaysScrollableScrollPhysics` does solve the issue 
regarding other two issues you mentioned which are not related to the title and they are not related to. RefreshProgressIndicator , i suggest to create separate issues

Closing.as duplicate of newer version updated issue https://github.com/flutter/flutter/issues/49169

if you disagree please write in the comments and I will reopen it Thank you

**Closed by TahaTesser** 2020-05-20 14:09 UTC
Labels: f: material design, f: scrolling, framework
