### ISSUE TITLE
Uploading Flutter App to Google Play - Please upgrade to Billing Library version 3 or newer to publish this app. Learn More about Billing Library 3

### ISSUE THREAD

**Issue by jgarrett77** [flutter/flutter#90847] opened 2021-09-28 02:22 UTC
When I uploading Flutter App to Google Play I get the following error "Please upgrade to Billing Library version 3 or newer to publish this app. Learn More about Billing Library 3"

I have updated my app/build.gradle file to use version 4 as below:
```
def billing_version = "4.0.0"
implementation "com.android.billingclient:billing:$billing_version"
```

Also I even tried removing this completely and I still get this error.  I have tried with and without using the:

`  <uses-permission android:name="com.android.vending.BILLING" />`

Permission.

Any help is appreciated!

**Comment by danagbemava-nc** [comment] 2021-09-28 09:03
Hi @jgarrett77 

Can you please provide your `flutter doctor -v` and what version of `in_app_purchases` you're using?

Thank you

**Comment by jgarrett77** [comment] 2021-09-28 12:54
Below is flutter Doctor output:

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/jabari.garrett/Development/Tools/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jabari.garrett/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```

I am using:
`purchases_flutter: ^3.4.5`

Thanks!

**Comment by danagbemava-nc** [comment] 2021-09-28 13:22
Hi @jgarrett77, you appear to be on an older version of `flutter stable`. 

If possible, kindly upgrade to the latest version of stable and try again. 

Also, it appears you're using a third party package. The `purchases_flutter` package is not maintained by the `flutter` team, so if you upgrade and you still run into the issue, I will advise that you file an issue with the `purchases_flutter` repo.


Kindly share your `pubspec.yaml` as well so that we might confirm if the issue is from another package or `purchases_flutter`.

Thank you

**Comment by jgarrett77** [comment] 2021-09-28 13:28
Here are my pubspec.yaml dependencies


```
cupertino_icons: ^1.0.0
  carousel_pro: ^1.0.0
  flutter_swiper : ^1.1.6
  carousel_slider: ^3.0.0
  badges: ^1.1.0
  http: ^0.13.3
  font_awesome_flutter: ^8.5.0
  fluttertoast: ^3.1.3
  custom_radio: ^0.1.2
  flutter_rating_bar: ^3.0.0
  page_transition: "^1.1.5"
  flutter_spinkit: ^3.1.0
  fancy_on_boarding: ^1.8.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  amplify_flutter: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  amplify_api: '<1.0.0'
  amplify_storage_s3: '<1.0.0'
  flutter_multiple_image_picker: ^0.0.1
  dropdown_formfield: ^0.1.3
  flutter_search_bar: ^2.1.0
  image_picker: ^0.8.0+3
  image_cropper: ^1.3.1
  progress_dialog: ^1.2.4
  wechat_assets_picker: ^5.5.4
  xml: ^5.0.0-nullsafety.1
  video_thumbnail: ^0.3.3
  image: ^3.0.2
  mime: ^1.0.0
  path_provider: ^2.0.2
  path: ^1.8.0
  chewie: ^1.0.0
  video_player: ^2.1.6
  flutter_image_compress: ^1.0.0
  flutter_local_notifications: ^8.1.1+1
  rxdart: ^0.27.1
  flutter_native_timezone: ^2.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.7
  dashed_circle: ^0.0.1
  skeleton_loader: ^2.0.0+4
  cached_network_image: ^3.1.0
  package_info_plus: ^1.0.5
  firebase_core: ^1.6.0
  video_compress: ^3.1.0
  youtube_player_flutter: ^8.0.0
  purchases_flutter: ^3.4.5
  url_launcher: ^6.0.10
```

**Comment by danagbemava-nc** [comment] 2021-09-28 13:53
Hi @jgarrett77, I can see that you've filed an issue with `purchases_flutter`, as such I'll be closing this issue for now. 

If they redirect you back here, kindly link the issue and I'll reopen. 

Thank you

**Closed by danagbemava-nc** 2021-09-28 13:53 UTC
Labels: in triage
