### ISSUE TITLE
App crash after scroll of listView with a lot of elements  

### ISSUE THREAD

**Issue by pisa97** [flutter/flutter#29971] opened 2019-03-26 10:03 UTC
Hi, I see that my app crash after I scroll a list with a large amount of cards. This is due to the fact that Flutter does not have a good memory manipulation with item list? I have to manage it by myself? Thanks you in advance!

**Comment by tomalabaster** [comment] 2019-03-26 11:25
Can you provide the minimum code required to repeat the crash, please? Also the output from running `flutter doctor -v`?

**Comment by pisa97** [comment] 2019-03-26 11:31
This is the output of flutter doctor:
`[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G5019, locale it-IT)
    • Flutter version 1.2.1 at /Users/Arcangelo/Desktop/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.32.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone di Denis Bosco • a202d400a7539a02b6f7f9ce1d82c64f633ee838 • ios • iOS 11.3.1`

This is the widget I add into ListView.Builder on flutter:
`return Container(
          child: Column(
              children: <Widget>[
        SizedBox(child: UiKitView(viewType: 'AdView'), width: MediaQuery.of(context).size.width, height: 100,)
      ]`

This is native code of in Swift of a simple WKWebView:
`public class NativeViewForBanner: NSObject, FlutterPlatformViewFactory {
    public func create(withFrame frame: CGRect, viewIdentifier viewId: Int64, arguments args: Any?) -> FlutterPlatformView {
        return AdView(frame, viewId: viewId, args: args)
    }
}

public class AdView : NSObject, FlutterPlatformView, WKNavigationDelegate {
    let frame: CGRect
    let viewId: Int64
       
    init(_ frame: CGRect, viewId: Int64, args: Any?) {
        self.frame = frame
        self.viewId = viewId
    }
    
    public func view() -> UIView {
        
        let finalView: UIView = UIView(frame: frame)
        var webView: WKWebView!

        let webViewConfiguration = WKWebViewConfiguration()
        webView = WKWebView(frame: CGRect(x: finalView.layer.position.x, y: finalView.layer.position.y, width: finalView.frame.width, height: finalView.frame.height), configuration: webViewConfiguration)
        
        webView.translatesAutoresizingMaskIntoConstraints = false
        webView.backgroundColor = UIColor.darkGray
        
        let request = URLRequest(url: URL(string: "www.apple.com")!)
        webView.load(request)
       
        return webView
    }
}
`

**Comment by tomalabaster** [comment] 2019-03-26 11:39
You're using Platform Views which are still in preview. Someone else might know more about Platform Views and their stability for use in ListViews. Someone will probably come along and label this issue appropriately for it to be looked at.

**Comment by pisa97** [comment] 2019-03-28 10:20
Thanks you so much, tom

**Comment by iapicca** [comment] 2020-03-13 11:33
Hi @pisa97 
are you still experiencing the issue with the latest stable version of flutter?
thank you

**Comment by Adrek** [comment] 2020-03-14 21:01
I have a same problem. I made a simple app demo that contains a listview with network images. 
The behavior is correctly if scroll down slow, but if I scroll down fast, many images load until it reaches a point where the screen freezes, the buttons do not work, you cannot go back and the application crashes.

**Comment by iapicca** [comment] 2020-03-15 11:32
Hi @Adrek 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by Piinks** [comment] 2020-04-09 20:56
This may have already been fixed, but not reached stable yet, @dnfield is this another for the deferred loading work you did?

**Comment by dnfield** [comment] 2020-04-09 21:13
@adrek - your problem should be fixed, since image handling is done differently now when scrolling rapidly.

For the original problem in this bug, I'd expect it to still be a problem. The scrolling work I did was not applied to platform views.  /cc @cyanglaz who may have some thoughts on how to handle that.I suspect we may want a similar way of handling this for platform views, e.g. not _actually_ creating and allocating the platform view unless scrolling has slowed down enough.

That said, this use case seems really strange.  Why do you want a long list of webviews?  I suspect there are much better ways of handling this.

**Comment by dnfield** [comment] 2020-04-09 21:50
Re-opening - this has a pretty clear repro case that I think we should address.

**Comment by hasanzia1993** [comment] 2020-04-25 18:56
> I have a same problem. I made a simple app demo that contains a listview with network images.
> The behavior is correctly if scroll down slow, but if I scroll down fast, many images load until it reaches a point where the screen freezes, the buttons do not work, you cannot go back and the application crashes.

I have exactly the same issue

**Comment by AhmedKhattab95** [comment] 2020-08-21 05:21
I have the same issue here any solution found for this?

**Comment by Tharindu-dart** [comment] 2020-09-18 19:03
I have the same issue when i use gridview.builder with keepAlive

**Comment by AhmedKhattab95** [comment] 2020-09-21 16:21
using FadeInImage with ResizeImage will catch the error and will not cause the app to crash
```
FadeInImage(
        fit: BoxFit.cover,
        image: ResizeImage(
          CachedNetworkImageProvider(
            "image_url",
          ),
          width: MediaQuery.of(context).size.width.toInt(),
        ),
        placeholder: AssetImage("image_name.png"),
        // placeholder image until finish loading
        imageErrorBuilder: (context, error, st) {
// handle error and show error image
        });
```
Thanks to https://github.com/mohamed-selim-a

**Comment by TahaTesser** [comment] 2020-09-22 14:07
Hi @pisa97
Are you only experiencing this issue with the platform view? Since a lot of comments on the issue don't mention Platform 
I am unable to reproduce the crash using a lot of  UIKitView in a column in a list 

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('PlatformView WebView'),
      ),
      body: Container(
        child: SingleChildScrollView(
          child: Column(
            children: [
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: 100,
                child: WebView(
                  onWebViewCreated: (controller) {
                    controller.loadUrl('https://flutter.dev/');
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

typedef void WebViewCreatedCallback(WebViewController controller);

class WebView extends StatefulWidget {
  const WebView({
    Key key,
    this.onWebViewCreated,
  }) : super(key: key);

  final WebViewCreatedCallback onWebViewCreated;

  @override
  State<StatefulWidget> createState() => WebViewState();
}

class WebViewState extends State<WebView> {
  @override
  Widget build(BuildContext context) {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return AndroidView(
        viewType: 'webview',
        onPlatformViewCreated: _onPlatformViewCreated,
      );
    } else if (defaultTargetPlatform == TargetPlatform.iOS) {
      return UiKitView(
        viewType: 'webview',
        onPlatformViewCreated: _onPlatformViewCreated,
      );
    }
    // TODO add other platforms
    return Text(
        '$defaultTargetPlatform is not yet supported by the map view plugin');
  }

  void _onPlatformViewCreated(int id) {
    if (widget.onWebViewCreated == null) {
      return;
    }
    widget.onWebViewCreated(new WebViewController(id));
  }
}

class WebViewController {
  WebViewController(int id) {
    this._channel = new MethodChannel('webview$id');
  }

  MethodChannel _channel;

  Future<void> loadUrl(String url) async {
    return _channel.invokeMethod('loadUrl', url);
  }
}

```

</details> 

Everyone who is experiencing this issue 
Can you please provide a complete reproducible minimal code sample in a repository
Thank you

**Comment by AhmedKhattab95** [comment] 2020-09-29 14:10
@TahaTesser it happens with a large number of photos lets say > 20 photos and photos are high quality (2 - 3 Mb)

**Comment by TahaTesser** [comment] 2020-09-30 13:05
Hi @AhmedKhattab95
Thanks for the info, this sounds like a duplicate of a new newer with an updated data https://github.com/flutter/flutter/issues/65834

CC @dnfield 
Can we close this in favor o the new issue?

**Comment by dnfield** [comment] 2020-09-30 15:07
Yes. 

There are actually a number of bugs around lists of images, and it's getting hard to track which ones should even be open anymore, but closing this as a duplicate of #65834 makes sense for this one.

**Closed by dnfield** 2020-09-30 15:07 UTC
Labels: a: platform-views, f: scrolling, framework, platform-ios, severe: crash, waiting for customer response
