### ISSUE TITLE
[Youtube_Videos], no solution means we're robbing creators?

### ISSUE THREAD

**Issue by RaitonGG** [flutter/flutter#60808] opened 2020-07-03 10:28 UTC
I want to play youtube videos on my app, however, every solution I found so far, gets rid of the ads, cards, speed and quality controls, cc, etc... 

How can flutter and youtube both be owned by google and no solution for this exist? I mean, I'll still play the videos but at the expense of the livelihood of the YouTuber, and youtube itself since it takes 45% of the ad revenue...

we NEED a native youtube player on flutter. that we can customize to show what we want (for example show channel cards but not the youtube final card grid...) 

   I Have no idea how to create this or I would myself... but this is a must for yesterday

**Comment by timsneath** [comment] 2020-07-11 22:01
Duplicate of #13756

**Closed by timsneath** 2020-07-11 22:01 UTC
Labels: plugin, severe: new feature
