### ISSUE TITLE
Tap/Click detector is bugged within Stack widget

### ISSUE THREAD

**Issue by shtengel** [flutter/flutter#20798] opened 2018-08-19 16:31 UTC
I Have a problem with the Stack Widget.
I have a Stack that contains two children: an Image wrapped with InkWell and an IconButton.
When i click anywhere on the image, whoever is last on the Stack children list his onTap/onPressed callbacks is executed. even if i click the image and not the iconbutton, the iconbutton's onPressed is called.
how can i correct this?
My goal is to have an Image with an 'X' icon button on the right corner.

```dart
Stack(
                fit: StackFit.expand,
                children: <Widget>[
                  InkWell (
                    onTap: () {
                      setState(() {
                        // Not Called
                      });
                    }, child :new Image(
                    height: 60.0,
                    width: 60.0,
                    image: new NetworkImage("SomeImageURL"),
                    fit: BoxFit.fill,
                  )),
                  IconButton(
                    color: Theme.of(context).accentColor,
                    alignment: Alignment.topRight,
                    icon: Icon(Icons.cancel),
                    onPressed: () {
                      setState(() {
                        // Called even if i click the image and not the tiny IconButton which is on top
                      });
                    },
                  )
                ],
              )
```

**Comment by zoechi** [comment] 2018-08-19 17:29
Did you experiment with the https://docs.flutter.io/flutter/widgets/GestureDetector/behavior.html property of `GestureDetector`? Does it make a difference to pass different values?

**Comment by shtengel** [comment] 2018-08-19 20:40
@zoechi 
Output of "doctor -v":

[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale he-IL)
    • Flutter version 0.5.1 at D:\env\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\MLClient\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: D:\Android Studio 1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[!] Android Studio (version 2.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.1)
    • Android Studio at D:\Android Studio 1
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.

**Comment by shtengel** [comment] 2018-08-19 21:15
@zoechi 
Couldn't make it work by wrapping IconButton with GestureDetector :(

**Comment by shtengel** [comment] 2018-08-19 21:34
@zoechi 
Fixed. 
By removing the IconButton and using Icon wrapped with GestrueDetector

**Comment by davystrong** [comment] 2019-09-15 01:30
I'm running into this problem too

**Comment by davystrong** [comment] 2019-09-16 01:04
Actually, this was my mistake. I had confused the order of the stack!

**Comment by nvalakunde** [comment] 2019-10-10 12:59
because you are moving the clickable area outside your Stack so you can't hit on those positions.
If you wrap stack with container() and set height your are able to click the button

**Comment by jiaqidegege** [comment] 2019-11-08 09:18
@nvalakunde  It doesn't work for me

**Comment by HartP97** [comment] 2020-04-03 20:07
It won't work for me either, I tried all the mentioned workarounds.
I have a Stack-widget which has multiple children, onPressed/Tap works just fine in the most top widget, everything below the most top-widget is ignoring onPressed/Tap. It's like there is a transparent "wall" created around the most top-widget that fills the rest of the screen and that won't allow any touch-events below it.

**Comment by iapicca** [comment] 2020-04-09 11:30
Hi @shtengel 
as @nvalakunde  correctly stated 
it's necessary to make sure the clickable area is inside the stack
and this behaviour is [intended](https://github.com/flutter/flutter/issues/19445#issuecomment-452017412)

from the initial code just wrap the icon in a `Center` (or `Align`, or `Positioned` ...)

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const String _url = 'https://flutter.dev/assets/flutter-lockup-c13da9c9303e26b8d5fc208d2a1fa20c1ef47eb021ecadf27046dea04c0cebf6.png';

  void _snack(BuildContext context, String message) =>
      Scaffold.of(context).showSnackBar(
        SnackBar(
          content: Text(message),
        ),
      );

  @override
  Widget build(BuildContext context) => Scaffold(
    body: Builder(
      builder: (context) => Center(
          child: Stack(
        fit: StackFit.expand,
        children: <Widget>[
          InkWell(
              onTap: () => _snack(context,'inkwell'),
              child: Image(
                height: 60.0,
                width: 60.0,
                image:  NetworkImage(_url),
                fit: BoxFit.fill,
              )),

          Center( child: // <== need to be wrapped in a center / positioned / align ....
           
            IconButton(
              color: Theme.of(context).accentColor,
              alignment: Alignment.topRight,
              icon: Icon(Icons.cancel),
              onPressed: () => _snack(context,'icon button'),
            ),

          ),

        ],
      )),
    ),
  );
}
```
I'm closing this issue
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by HartP97** [comment] 2020-04-10 20:32
My Layout is still blocking the button that is not in the most top Stack-item, I have the following structure (simplified):

```
Stack(
   fit: StackFit.expand,
   children: <Widget>[
      .....
      Positioned(
         child: Container(
            child: Column(
               children: <Widget>[
                  .....
                  RaisedButton("This one doesn't work!")
      Positioned(
         child: Container(
            child: Column(
               children: <Widget>[
                  .....
                  RaisedButton("This one works!")
      .....

```

The two containers have a specific size and the top one is overlapping the other (just in one corner). Even though the top one is overlapping the other, it has plenty of distance to the button that was placed inside the bottom container. @iapicca do you have any idea why this could be?

**Comment by iapicca** [comment] 2020-04-17 10:23
Hi @HartP97 
can you please provide your `flutter doctor -v` , 
and a reproducible minimal code sample.
Thank you

**Comment by HartP97** [comment] 2020-04-18 23:09
Hi @iapicca , sorry for the inconvenience, I just found the problem when producing the minimal code sample. There was a vector graphic overlapping the button that was causing the problem (didn't realize it before as the graphic was transparent in this region).

**Comment by iapicca** [comment] 2020-04-20 13:27
Hi @HartP97 
I'm glad you solved the issue
thank you for letting me know

**Closed by iapicca** 2020-04-20 13:27 UTC
Labels: in triage, waiting for customer response
