### ISSUE TITLE
[web] release build strange behaviour

### ISSUE THREAD

**Issue by tapeo** [flutter/flutter#52669] opened 2020-03-16 15:39 UTC
Running `flutter run -d web-server` it works. When I create the build on the server with `flutter build web` it shows a grey background with the following error on console:

`Another exception was thrown: Instance of 'minified:at<void>'
QG — main.dart.js:2808:82`

Small project with that bug attached to reproduce it.

```
matteo@MacBook-Pro-di-Matteo ~/f/b/b/web> flutter doctor -v
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale it-IT)
    • Flutter version 1.14.6 at /Users/matteo/development/flutter
    • Framework revision fabeb2a16f (7 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/matteo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```
[bug.zip](https://github.com/flutter/flutter/files/4338966/bug.zip)

**Comment by TahaTesser** [comment] 2020-03-16 16:01
Hi @tapeo 
Could you please provide `flutter build web --verbose`?
Thank you

**Comment by tapeo** [comment] 2020-03-16 16:05
```
matteo@MacBook-Pro-di-Matteo ~/f/b/b/web> flutter build web --verbose
[  +18 ms] executing: [/Users/matteo/development/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +88 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/Users/matteo/development/flutter/] git describe --match
v*.*.* --first-parent --long --tags
[  +97 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +1 ms] v1.14.6-0-gfabeb2a16
[  +14 ms] executing: [/Users/matteo/development/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/matteo/development/flutter/] git ls-remote
--get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +110 ms] executing: [/Users/matteo/development/flutter/] git rev-parse
--abbrev-ref HEAD
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +12 ms] executing: sw_vers -productName
[  +37 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[   +1 ms] executing: sw_vers -productVersion
[  +20 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +24 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +47 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[  +29 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +17 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +20 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[   +8 ms] Changing current working directory to: /Users/matteo/flutter/bug
[ +293 ms] Generating
/Users/matteo/flutter/bug/android/app/src/main/java/io/flutter/plugins/Generated
PluginRegistrant.java
[ +142 ms] Generating
/Users/matteo/flutter/bug/android/app/src/main/java/io/flutter/plugins/Generated
PluginRegistrant.java
[   +9 ms] Compiling lib/main.dart for the Web...
[  +16 ms] Initializing file store
[  +24 ms] Done initializing file store
[ +117 ms] invalidated build due to missing files:
/Users/matteo/flutter/bug/packages/flutter_tools/lib/src/build_system/targets/we
b.dart
[  +20 ms] web_entrypoint: Starting due to {InvalidatedReason.inputMissing}
[   +3 ms] web_entrypoint: Complete
[+3600 ms] Skipping target: dart2js
[  +54 ms] Skipping target: web_release_bundle
[  +32 ms] Skipping target: web_service_worker
[   +1 ms] Persisting file store
[  +19 ms] Done persisting file store
[  +20 ms] Compiling lib/main.dart for the Web... (completed in 3,9s)
[   +2 ms] "flutter web" took 4.641ms.
```

**Comment by VladyslavBondarenko** [comment] 2020-03-16 16:26
I couldn't reproduce with `beta v1.14.6`

**Comment by VladyslavBondarenko** [comment] 2020-03-16 16:29
I couldn't reproduce with `beta v1.14.6`

**Comment by TahaTesser** [comment] 2020-03-17 08:56
Hi @tapeo 
Could you please switch dev channel and try agian? [reference](https://github.com/flutter/flutter/issues/50704#issuecomment-588967975)
Thank you

**Comment by tapeo** [comment] 2020-03-17 10:06
In `dev` channel same issue. Try reproduce it in this way:

1. use the new attached .zip (I think the problem is using `Wrap` widget.
2. run `flutter run -d web-server --release`

It shows to me a grey screen. If you change `Wrap` to `Row` all works.

**Comment by TahaTesser** [comment] 2020-03-17 10:20
Hi @tapeo 
That doesn't sound like release issue
Could you please provide a minimal reproducible sample?
Thank you

**Comment by tapeo** [comment] 2020-03-17 10:24
I attached the file `bug.zip` in the latest response. Do you need something else?

For me with that .zip:
with `flutter run -d web-server` it works.
using `flutter run -d web-server --release` doesn't works.

**Comment by TahaTesser** [comment] 2020-03-17 11:18
Hi @tapeo 
I just tested your code 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Test App",
      debugShowCheckedModeBanner: false,
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          Text("Test1",
              style: TextStyle(
                  color: Colors.black,
                  fontSize: 17,
                  fontWeight: FontWeight.bold)),
          Wrap(
            children: <Widget>[
              IconButton(
                icon: Container(
                  height: 24,
                  child: Icon(Icons.info_outline),
                ),
                onPressed: () {},
              ),
            ],
          ),
        ],
      ),
    ));
  }
}
```

You're just using `Wrap` wrong 
Please follow article to learn [Flutter Widget Guide — Wrap Widget in 5 mins or less.](https://medium.com/flutter-community/flutter-widget-guide-wrap-widget-in-5-mins-or-less-f77ad249c176)


Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-03-17 11:18 UTC
Labels: a: release, ☸ platform-web

**Comment by tapeo** [comment] 2020-03-17 12:10
Yes, was an issue with `Expanded` that in debug environment doesn't show up. Can close this issue, if this behavior with debug mode is normal.
