### ISSUE TITLE
[Android] Flutter 3.0 : RuntimeError: java.lang.IllegalStateException: Can't change activity type once set: ActivityRecord{51a07cc u0 com.android.settings/.homepage.SettingsHomepageActivity t165} activityType=undefined

### ISSUE THREAD

**Issue by whateverfast** [flutter/flutter#104083] opened 2022-05-18 14:26 UTC
Hi everyone,

I updated to Flutter 3.0,  clean, built it, and then ran my application again and it now produces this fatal exception which I couldn't find a solution to yet.

Any ideas?
```
E/AndroidRuntime(10445): FATAL EXCEPTION: main
E/AndroidRuntime(10445): Process: com.android.settings, PID: 10445
E/AndroidRuntime(10445): java.lang.IllegalStateException: Can't change activity type once set: ActivityRecord{51a07cc u0 com.android.settings/.homepage.SettingsHomepageActivity t165} activityType=undefined
E/AndroidRuntime(10445): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
E/AndroidRuntime(10445): 	at android.os.Parcel.createException(Parcel.java:2409)
E/AndroidRuntime(10445): 	at android.os.Parcel.readException(Parcel.java:2392)
E/AndroidRuntime(10445): 	at android.os.Parcel.readException(Parcel.java:2334)
E/AndroidRuntime(10445): 	at android.window.IWindowOrganizerController$Stub$Proxy.applyTransaction(IWindowOrganizerController.java:377)
E/AndroidRuntime(10445): 	at android.window.WindowOrganizer.applyTransaction(WindowOrganizer.java:53)
E/AndroidRuntime(10445): 	at android.window.TaskFragmentOrganizer.applyTransaction(TaskFragmentOrganizer.java:157)
E/AndroidRuntime(10445): 	at androidx.window.extensions.embedding.SplitPresenter.createNewSplitWithEmptySideContainer(SplitPresenter.java:120)
E/AndroidRuntime(10445): 	at androidx.window.extensions.embedding.SplitController$ActivityStartMonitor.setLaunchingToSideContainer(SplitController.java:807)
E/AndroidRuntime(10445): 	at androidx.window.extensions.embedding.SplitController$ActivityStartMonitor.onStartActivity(SplitController.java:775)
E/AndroidRuntime(10445): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1740)
E/AndroidRuntime(10445): 	at android.app.Activity.startActivityForResult(Activity.java:5407)
E/AndroidRuntime(10445): 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:584)
E/AndroidRuntime(10445): 	at android.app.Activity.startActivityForResult(Activity.java:5365)
E/AndroidRuntime(10445): 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:570)
E/AndroidRuntime(10445): 	at android.app.Activity.startActivity(Activity.java:5751)
E/AndroidRuntime(10445): 	at android.app.Activity.startActivity(Activity.java:5704)
E/AndroidRuntime(10445): 	at com.android.settings.core.SubSettingLauncher.launch(SubSettingLauncher.java:179)
E/AndroidRuntime(10445): 	at com.android.settings.core.SubSettingLauncher.launch(SubSettingLauncher.java:145)
E/AndroidRuntime(10445): 	at com.android.settings.homepage.TopLevelSettings.onPreferenceStartFragment(TopLevelSettings.java:123)
E/AndroidRuntime(10445): 	at androidx.preference.PreferenceFragmentCompat.onPreferenceTreeClick(PreferenceFragmentCompat.java:404)
E/AndroidRuntime(10445): 	at com.android.settings.core.InstrumentedPreferenceFragment.onPreferenceTreeClick(InstrumentedPreferenceFragment.java:115)
E/AndroidRuntime(10445): 	at com.android.settings.dashboard.DashboardFragment.onPreferenceTreeClick(DashboardFragment.java:237)
E/AndroidRuntime(10445): 	at com.android.settings.homepage.TopLevelSettings.onPreferenceTreeClick(TopLevelSettings.java:111)
E/AndroidRuntime(10445): 	at androidx.preference.Preference.performClick(Preference.java:1194)
E/AndroidRuntime(10445): 	at androidx.preference.Preference.performClick(Preference.java:1168)
E/AndroidRuntime(10445): 	at androidx.preference.Preference$1.onClick(Preference.java:181)
E/AndroidRuntime(10445): 	at android.view.View.performClick(View.java:7455)
E/AndroidRuntime(10445): 	at android.view.View.performClickInternal(View.java:7432)
E/AndroidRuntime(10445): 	at android.view.View.access$3700(View.java:835)
E/AndroidRuntime(10445): 	at android.view.View$PerformClick.run(View.java:28810)
E/AndroidRuntime(10445): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(10445): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10445): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(10445): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(10445): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(10445): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10445): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(10445): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(10445): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(10445): 	at com.android.server.wm.ConfigurationContainer.setActivityType(ConfigurationContainer.java:532)
E/AndroidRuntime(10445): 	at com.android.server.wm.Task.onDescendantActivityAdded(Task.java:1476)
E/AndroidRuntime(10445): 	at com.android.server.wm.TaskFragment.addChild(TaskFragment.java:1683)
E/AndroidRuntime(10445): 	at com.android.server.wm.WindowContainer.reparent(WindowContainer.java:367)
E/AndroidRuntime(10445): 	at com.android.server.wm.WindowOrganizerController.applyHierarchyOp(WindowOrganizerController.java:651)
E/AndroidRuntime(10445):
```
```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /Users/concordiahs/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (9 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/concordiahs/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by maheshmnj** [comment] 2022-05-19 07:19
Hi @whateverfast, Thanks for filing the issue. Please share the output of `flutter run -v ` in a text file (as the output will be long)?  Also, do you see this exception with a newly created project too?

**Comment by whateverfast** [comment] 2022-05-19 07:44
I just noticed that the error went away when I connected to a stronger WiFi network. Should this exception appear even when the app does not have access to the internet? [newbie question]

**Comment by maheshmnj** [comment] 2022-05-19 12:19
Thanks for the update @whateverfast, The error in the original post doesn't seem to indicate that the exception was due to the network connectivity. 

> Should this exception appear even when the app does not have access to the internet? [newbie question]

I don't think so, You should be able to build your flutter app even when offline provided that all the dependencies required to build the app are downloaded locally.

I am going to close the issue since you are no longer able to reproduce it. If you encounter this issue again feel free to file a new issue or comment on this issue and we will reopen it.

**Closed by maheshmnj** 2022-05-19 12:19 UTC
Labels: in triage
