### ISSUE TITLE
[macOS] TextField crashes app on macOS Sonoma

### ISSUE THREAD

**Issue by MegatronKing** [flutter/flutter#137049] opened 2023-10-23 05:02 UTC
### Steps to reproduce

This issue is a user feedback, see here: https://github.com/reqable/reqable-app/issues/278
1. Run app on maOS Sonoma
2. Tap a TextField
3. App will crash

### Expected results

TextField grants the focus.

### Actual results

App crashes.

### Logs

https://github.com/reqable/reqable-app/issues/278#issuecomment-1774430907

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.10.4, on macOS 13.5.1 22G90 darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.10.4 on channel unknown at /Users/megatronking/Workspace/Flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Warning: `flutter` on your path resolves to /Users/megatronking/Workspace/flutter/bin/flutter, which is not inside your current
      Flutter SDK checkout at /Users/megatronking/Workspace/Flutter. Consider adding /Users/megatronking/Workspace/Flutter/bin to the
      front of your path.
    ! Warning: `dart` on your path resolves to /Users/megatronking/Workspace/flutter/bin/dart, which is not inside your current Flutter
      SDK checkout at /Users/megatronking/Workspace/Flutter. Consider adding /Users/megatronking/Workspace/Flutter/bin to the front of
      your path.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 682aa387cf (5 months ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update
      checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/megatronking/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/megatronking/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.88
```

</details>

**Comment by dam-ease** [comment] 2023-10-23 11:47
Hi @MegatronKing. Thanks for filing this. I see you are on an older version of Flutter, can you please upgrade to the latest versions to see if this issue still persists? I it does, kindly share the full output of your `flutter run -v`.
Thank you!

**Comment by MegatronKing** [comment] 2023-10-24 11:39
@dam-ease I can't upgrade my app to the latest flutter version in a short time, there are some additional incompatibility issues. And I don't have a Sonoma machine, this bug was reported form my user.

**Comment by dam-ease** [comment] 2023-10-25 07:56
Thanks for your response @MegatronKing. I created a sample project with a `TextField` and ran it on macOS with 14 Sonoma on the latest `master` and `stable` channels and can't reproduce this issue.
For the issue to be workable, it needs to be reproducible with a minimal complete code sample that doesn’t include 3rd party plugins complex production code or full output of `flutter run -v`. Please provide such a sample.
Thank you

**Comment by MegatronKing** [comment] 2023-11-02 07:40
@dam-ease Seems that the crash caused by `Actions`, try this code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Actions(
          actions: {
            PasteTextIntent: InterceptIntentAction<PasteTextIntent>(
              onHit: (intent) {
                return null;
              }
            ),
            CopySelectionTextIntent: InterceptIntentAction<CopySelectionTextIntent>(
              onHit: (intent) {
                return null;
              }
            ),
          },
          child: const TextField(),
        )
      ),
    );
  }
}

class InterceptIntentAction<T extends Intent> extends Action<T> {

  final OnInvokeCallback<T> onHit;

  InterceptIntentAction({
    required this.onHit
  });

  @override
  Object? invoke(T intent) async {
    return onHit(intent) ?? callingAction?.invoke(intent);
  }

  @override
  bool get isActionEnabled => callingAction?.isActionEnabled ?? false;

  @override
  bool consumesKey(T intent) => callingAction?.consumesKey(intent) ?? false;

 }

```

**Comment by dam-ease** [comment] 2023-11-02 08:19
Thanks for your response and the sample. Running this on my end, I still can't reproduce this. Can you share the full output of your `flutter run -v`?
Also, I see you are on an older version of Flutter, kindly upgrade to the latest versions first to confirm this issue persists.

<img width="500" alt="Screenshot 2023-11-02 at 09 14 11" src="https://github.com/flutter/flutter/assets/53122008/64672b54-1437-4ca1-9774-4aa5f8653624">

<details><summary>Details</summary>
<p>

```
[!] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.9 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (8 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E • ios            •
      iOS 17.0.2 21A351
    • macOS (desktop)             • macos                     • darwin-arm64   •
      macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 118.0.5993.117

[!] Network resources
    ✗ A network error occurred while checking "https://github.com/": Operation
      timed out

! Doctor found issues in 3 categories
``` 

</p>
</details>

**Comment by MegatronKing** [comment] 2023-11-02 08:24
@dam-ease I don't have a 14 Sonoma machine. My user tells me  that the app without `Actions` works.

**Comment by dam-ease** [comment] 2023-11-02 15:14
Thanks for your response. I tried running the sample you shared earlier but couldn't reproduce the crash at any point (Tested on macOS Sonoma as well). I'll be labelling based on the crash report shared here https://github.com/reqable/reqable-app/issues/278#issuecomment-1774430907 for more insights from the team.
Thank you!

**Comment by gspencergoog** [comment] 2023-11-09 19:06
Unfortunately, we're going to close this as not reproducible in the latest version of Flutter.  If you upgrade your application to the latest version of Flutter and still have this issue, please comment here or open a new issue. (Desktop Triage)

**Closed by gspencergoog** 2023-11-09 19:06 UTC
Labels: a: text input, engine, platform-mac, e: OS-version specific, team-desktop
