### ISSUE TITLE
ButtonTheme removes Paste button

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#68153] opened 2020-10-14 23:22 UTC
This `buttonTheme` removes the Paste button:

```dart
 class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        buttonTheme: ButtonTheme.of(context).copyWith(
          buttonColor: Colors.blue,
          disabledColor: Colors.black38,
          textTheme: ButtonTextTheme.accent,
          colorScheme: Theme.of(context).colorScheme.copyWith(
                primary: Colors.blue,
                secondary: Theme.of(context).colorScheme.onPrimary,
              ),
          shape: StadiumBorder(),
        ),
      ),
      home: Scaffold(
        body: Center(
          child: TextFormField(),
        ),
      ),
    );
  }
}
```

![image](https://user-images.githubusercontent.com/8120472/96055523-b7e4c200-0e5a-11eb-996e-3f0f7ae4867e.png)

It was supposed to look like this:

![image](https://user-images.githubusercontent.com/8120472/96055598-de0a6200-0e5a-11eb-98c7-25e1d3fce7bb.png)

I use this `buttonTheme` as it's the only way I can set the text color for all my buttons.

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.508], locale pt-BR)
    • Flutter version 1.22.1 at C:\Programming\Flutter\sdk\flutter
    • Framework revision f30b7f4db9 (6 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Michel\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.2
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.31

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\Michel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
``` 
</details>

**Comment by TahaTesser** [comment] 2020-10-15 13:44
Hi @feinstein 
Thanks for filing the issue the regression issue
| (Channel stable, 1.22.1 &  Channel beta, 1.22.  | Channel dev, 1.23.0-18.0.pr & Channel master, 1.23.0-19.0.pre.48 |
| --------------- | --------------- |
![flutter_01](https://user-images.githubusercontent.com/48603081/96137678-8cc1a780-0f1a-11eb-9dfa-ff2e0a51a1e5.png) | ![flutter_01](https://user-images.githubusercontent.com/48603081/96137722-99460000-0f1a-11eb-9b77-100fb0bc1205.png)
 

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        buttonTheme: ButtonTheme.of(context).copyWith(
          buttonColor: Colors.blue,
          disabledColor: Colors.black38,
          textTheme: ButtonTextTheme.accent,
          colorScheme: Theme.of(context).colorScheme.copyWith(
                primary: Colors.blue,
                secondary: Theme.of(context).colorScheme.onPrimary,
              ),
          shape: StadiumBorder(),
        ),
      ),
      home: Scaffold(
        body: Center(
          child: TextFormField(),
        ),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f30b7f4db9 (7 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/tahatesser/Code/flutter_beta
    • Framework revision f30b7f4db9 (7 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (1 available)            
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.23.0-18.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 37ebe3d82a (2 days ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (4 available)            
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 86.0.4240.80

• No issues found!
tahatesser@Tahas-MacB
```

</details> 
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-19.0.pre.48, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-GB)
    • Flutter version 1.23.0-19.0.pre.48 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1133c2e85c (8 hours ago), 2020-10-15 01:57:04 -0400
    • Engine revision d2ea378be4
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.7 19H2
      darwin-x64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 86.0.4240.80

• No issues found!

```

</details>

**Comment by HansMuller** [comment] 2020-10-15 16:27
As of https://github.com/flutter/flutter/pull/66597 the text selection menu no longer depends on FlatButton or ButtonTheme.
So, as @TahaTesser pointed out, this isn't an issue anymore.

**Comment by feinstein** [comment] 2020-10-15 16:34
@HansMuller perfect.

I just got a question then (I am not familiar yet with the new buttons): If we set a theme for `TextButton`, will it propagate to the copy/paste selection menus? If yes, this might be a problem when we expect something closer to the styling given by the platform.

**Comment by HansMuller** [comment] 2020-10-15 16:40
That's a good point however, the TextSelection menu does override the default appearance of its TextButtons. See:

https://github.com/HansMuller/flutter/blob/9e45b78687843702f2e5c7b24d252df539691362/packages/flutter/lib/src/material/text_selection.dart#L93

**Comment by feinstein** [comment] 2020-10-15 16:41
Perfect!

**Comment by TahaTesser** [comment] 2020-10-15 17:44
Hi @HansMuller 
Can we close this if it isn't significant for CP?
Thank you

**Comment by HansMuller** [comment] 2020-10-15 22:06
I'm going to close this issue because the problem only exists with FlatButton/ButtonTheme. Those classes are obsolete, they're no longer used in the text selection menu, and will be deprecated fairly soon.

**Closed by HansMuller** 2020-10-15 22:06 UTC
Labels: f: material design, found in release: 1.22, framework, has reproducible steps

**Comment by feinstein** [comment] 2020-10-15 22:08
(@TahaTesser what does CP stands for?)
