### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: google-chrome, OS error code: 2

### ISSUE THREAD

**Issue by codexsourav** [flutter/flutter#118141] opened 2023-01-07 15:08 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: google-chrome, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._lau

**Comment by darshankawar** [comment] 2023-01-09 07:05
Closing as duplicate of https://github.com/flutter/flutter/issues/95142. Please upvote the original issue for team's attention.

**Closed by darshankawar** 2023-01-09 07:05 UTC
Labels: in triage
