### ISSUE TITLE
[url_launcher] NPE in WebViewActivity.extractHeaders

### ISSUE THREAD

**Issue by bakua** [flutter/flutter#81532] opened 2021-04-30 07:25 UTC
Hello, I got this NPE in url_launcher 6.0.3 on Flutter 2.0.5. 

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.os.Bundle.keySet()' on a null object reference
       at io.flutter.plugins.urllauncher.WebViewActivity.extractHeaders(WebViewActivity.java:147)
       at io.flutter.plugins.urllauncher.WebViewActivity.onCreate(WebViewActivity.java:128)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by pedromassangocode** [comment] 2021-04-30 10:02
Hi @bakua 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), your `flutter doctor -v`, and `flutter run --verbose`?
Thank you

**Comment by pedromassangocode** [comment] 2021-05-21 08:19
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-21 08:19 UTC
Labels: in triage, waiting for customer response

**Comment by stuartmorgan** [comment] 2021-11-11 21:55
For posterity, this is a duplicate of https://github.com/flutter/flutter/issues/72863
