### ISSUE TITLE
TextTheme docs should link to material.io

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#18580] opened 2018-06-18 19:50 UTC
The material.io web site has a good description of the various text theme values.  We should link to it from the TextTheme docs:

https://material.io/design/typography/the-type-system.html

**Comment by zoechi** [comment] 2019-01-28 14:55
Duplicate of #19060 

PR #26807 to fix it waiting to be merged.

**Comment by johnsonmh** [comment] 2019-04-18 04:35
Looks like this was fixed in https://github.com/flutter/flutter/pull/26807, `text_theme.dart` now links to [material.io/design/typography](http://material.io/design/typography).

**Closed by johnsonmh** 2019-04-18 04:35 UTC
Labels: d: api docs, f: material design, framework
