### ISSUE TITLE
integration testing issues

### ISSUE THREAD

**Issue by kimsean** [flutter/flutter#119219] opened 2023-01-26 05:49 UTC
HI. I followed these intructions

https://github.com/flutter/flutter/tree/master/packages/integration_test#android-device-testing

but when i build it, i get these errors.
`
error: cannot find symbol
 public ActivityTestRule<MainActivity> rule = new ActivityTestRule<>(MainActivity.class, true, false);
`
Currently using flutter 3.3.10

**Comment by darshankawar** [comment] 2023-01-26 11:45
Closing this as duplicate of https://github.com/flutter/flutter/issues/62237. Please upvote original issue for team's attention.

**Closed by darshankawar** 2023-01-26 11:45 UTC
Labels: in triage
