### ISSUE TITLE
Field Input focus bug

### ISSUE THREAD

**Issue by jascodes** [flutter/flutter#72918] opened 2020-12-24 07:32 UTC
https://user-images.githubusercontent.com/1231593/103070600-d77d3100-45e7-11eb-8d8c-4a8e19ca675e.MP4

The issue is with curor focus. When I do nextFocus `FocusScope.of(context).nextFocus();`. The cursor start blinking at start of text but when you type it moves to end of text field. Is there setting I am missing or is this an bug?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.52.1)
```

**Comment by anirudh-jwala** [comment] 2020-12-24 10:31
Similar/duplicate of [#Issue 72818](https://github.com/flutter/flutter/issues/72818)

**Comment by jascodes** [comment] 2020-12-24 11:33
@anirudh-jwala Not even close...

**Comment by darshankawar** [comment] 2020-12-28 08:20
@jascodes 
Can you provide a minimal complete reproducible code sample ?
Thanks.

**Comment by jascodes** [comment] 2020-12-28 08:37
@darshankawar little busy for few days but will post back.. with sample project

**Comment by pedromassangocode** [comment] 2021-01-20 11:03
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-01-20 11:03 UTC
Labels: a: text input, framework, in triage, waiting for customer response
