### ISSUE TITLE
Make debugCheckedModeBanner touchable

### ISSUE THREAD

**Issue by clintwan** [flutter/flutter#47999] opened 2019-12-31 00:26 UTC
## Use case

```
Widget build(BuildContext context) {
  return MaterialApp(
    title: 'myapp',
    initialRoute: Constants.ROUTE_INIT,
    onGenerateRoute: Router.generateRoute,
    checkedModeBannerOnPressed:()=> Navigator.push(DebugView),
    checkedModeBannerHandler: MyBannerHandler(
      onPressed:()=> Navigator.push(DebugView),
    ),
    checkedModeBanner: MyBanner(),
  );
}
```
## Proposal

```
class DebugView extends StatelessWidget {  
  @override
  Widget build(BuildContext context) {
    return some view show app status;
  }
}
```

**Comment by goderbauer** [comment] 2020-01-06 21:24
Duplicate of https://github.com/flutter/flutter/issues/9324.

**Closed by goderbauer** 2020-01-06 21:24 UTC
Labels: framework, proposal
