### ISSUE TITLE
Linux Desktop cannot hot restart when paused at a breakpoint

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#51779] opened 2020-03-02 17:16 UTC
Repro steps:
`git clone https://github.com/google/flutter-desktop-embedding`
Pause at a breakpoint and edit some Flutter code.
Attempt to hot restart. 
The app will never resume if you later also try to click resume.
On MacOs Desktop and mobile, hot restart after being paused at a breakpoint works fine.

**Comment by jacob314** [comment] 2020-03-02 17:16
Fyi @jonahwilliams

**Comment by jonahwilliams** [comment] 2020-03-02 22:15
No idea about this, might be an issue with the engine. FYI @stuartmorgan

**Comment by stuartmorgan** [comment] 2020-03-03 05:51
I wonder if it's an issue with the runloop implementation? That's entirely speculation at this point but it's definitely very different between macOS and Linux so is probably a good place for us to start looking.

**Comment by TahaTesser** [comment] 2021-10-01 13:18
Hi @jacob314 
I've attempted to reproduce this issue on the latest `stable` channel on Zorin OS (based on Ubuntu 20.04 LTS), hot restarts work fine when paused at a breakpoint and after hot restarts, break gets hit and resume works fine too

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.2, on Zorin OS 16 5.11.0-37-generic, locale en_US.UTF-8)
    • Flutter version 2.5.2 at /home/taha/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (17 hours ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/taha/Code/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/taha/Code/android-sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29.1
[✓] Android Studio (version 2020.3)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.26.0
[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Zorin OS 16 5.11.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.61
• No issues found!
```
	 
</details>


Since Fluter tooling probably changed a lot since the time when this issue was filed, would you mind trying the latest Flutter stable?
Thank you

**Comment by danagbemava-nc** [comment] 2021-11-17 12:27
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-11-17 12:27 UTC
Labels: waiting for customer response, platform-linux, a: desktop, P4
