### ISSUE TITLE
Linux: GDK-Critical error on startup: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

### ISSUE THREAD

**Issue by dannyglover** [flutter/flutter#137262] opened 2023-10-25 16:34 UTC
### Steps to reproduce

1) Open the example app in VSCode.
2) Press F5 to build and run
3) Observe the output stated in the console output 

### Expected results

There should be no GDK errors on startup.

### Actual results

GDK throws the following error on startup:

```
(myapp:62126): Gdk-CRITICAL **: 17:24:24.008: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
```

### Logs

<details><summary>Logs</summary>

```console
(myapp:62126): Gdk-CRITICAL **: 17:24:24.008: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
✓] Flutter (Channel stable, 3.13.6, on Fedora Linux 38 (Workstation Edition) 6.5.6-200.fc38.x86_64,
    locale en_GB.UTF-8)
    • Flutter version 3.13.6 on channel stable at /home/danny/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (4 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/danny/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at:
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio/jbr/bi
      n/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[!] Android Studio (version unknown)
    • Android Studio at
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • android-studio-dir =
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 38 (Workstation Edition)
      6.5.6-200.fc38.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment] 2023-10-26 07:36
Thanks for filing the issue. I can reproduce this on the latest Flutter stable and master channels.

I see the same issue has been fixed at https://github.com/flutter/flutter/issues/130514. This could be a regression.

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.9, on Ubuntu 22.04.3 LTS 6.2.0-34-generic, locale en_US.UTF-8)
    • Flutter version 3.13.9 on channel stable at /home/huynq/Documents/Working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (11 hours ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.83.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-34-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.16.0-17.0.pre.42, on Ubuntu 22.04.3 LTS 6.2.0-34-generic, locale en_US.UTF-8)
    • Flutter version 3.16.0-17.0.pre.42 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/huynq/Documents/Working/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0ce766dfd6 (9 minutes ago), 2023-10-26 03:19:05 -0400
    • Engine revision 2a01fae53d
    • Dart version 3.3.0 (build 3.3.0-56.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.83.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-34-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by jwinarske** [comment] 2023-10-26 12:44
I also have a repro.  It's not fatal.  You can't query the window state before the window exists.  I suspect you don't see the error with a restart, as the window already exists. So it needs conditional logic to determine if the window already exists.

https://github.com/flutter/engine/blob/23649a0529e53b99e9b35345f7c092b68b839cf2/shell/platform/linux/fl_view.cc#L251

**Comment by dannyglover** [comment] 2023-10-26 14:17
> I also have a repro. It's not fatal. You can't query the window state before the window exists. I suspect you don't see the error with a restart, as the window already exists. So it needs conditional logic to determine if the window already exists.
> 
> https://github.com/flutter/engine/blob/23649a0529e53b99e9b35345f7c092b68b839cf2/shell/platform/linux/fl_view.cc#L251

Yep, it isn't fatal and the app still runs. However, I haven't tested on a variety of Linux flavours and this _could_ potentially cause issues on other distributions.

It doesn't happen with a hot restart either, correct.

It'd be nice to have this fixed either way, as it's not a good look to have this message outputted in a released app.

**Comment by guobihai** [comment] 2023-10-27 05:50
<img width="568" alt="image" src="https://github.com/flutter/flutter/assets/4987622/97d30f18-9398-4aaf-896e-6dd338932934">

**Comment by dannyglover** [comment] 2023-10-27 08:52
> <img alt="image" width="568" src="https://user-images.githubusercontent.com/4987622/278548005-97d30f18-9398-4aaf-896e-6dd338932934.png">

This isn't a solution. Disabling Wayland to sidestep an error that shouldn't be occurring is frankly a ludicrous suggestion.

**Comment by gdelgado11** [comment] 2023-10-30 18:51
I´m have the same problem.

**Comment by gspencergoog** [comment] 2023-11-02 18:06
cc @robert-ancell

**Comment by robert-ancell** [comment] 2023-11-03 08:10
Looks like one of yours @gspencergoog - https://github.com/flutter/engine/commit/81839ac81a644b58c598cbf3560eb9e76aafceeb

Without testing I would think the correct way to keep the window state is:
```
diff --git a/shell/platform/linux/fl_view.cc b/shell/platform/linux/fl_view.cc
index e41bbebdab..4f258cd006 100644
--- a/shell/platform/linux/fl_view.cc
+++ b/shell/platform/linux/fl_view.cc
@@ -247,8 +247,6 @@ static void on_pre_engine_restart_cb(FlEngine* engine, gpointer user_data) {
   g_clear_object(&self->scrolling_manager);
   init_keyboard(self);
   init_scrolling(self);
-  self->window_state =
-      gdk_window_get_state(gtk_widget_get_window(GTK_WIDGET(self)));
 }
 
 // Implements FlPluginRegistry::get_registrar_for_plugin.
@@ -556,6 +554,7 @@ static void realize_cb(GtkWidget* widget) {
   self->window_state_cb_id =
       g_signal_connect(toplevel_window, "window-state-event",
                        G_CALLBACK(window_state_event_cb), self);
+  self->window_state = gdk_window_get_state(toplevel_window);
 
   g_signal_connect(toplevel_window, "delete-event",
                    G_CALLBACK(window_delete_event_cb), self);
@@ -760,8 +759,6 @@ static void fl_view_class_init(FlViewClass* klass) {
 
 static void fl_view_init(FlView* self) {
   gtk_widget_set_can_focus(GTK_WIDGET(self), TRUE);
-  self->window_state = gdk_window_get_state(
-      gtk_widget_get_window(gtk_widget_get_toplevel(GTK_WIDGET(self))));
 }
 
 G_MODULE_EXPORT FlView* fl_view_new(FlDartProject* project) {
```

i.e. you get it when the widget is realized and keep track of changes. There should be no need to re-query it during an engine restart or any other event as if the state changed it would have been updated anyway in `window_state_event_cb`.

**Comment by gspencergoog** [comment] 2023-11-09 00:24
Fixed by https://github.com/flutter/engine/pull/47713

**Closed by gspencergoog** 2023-11-09 00:24 UTC
Labels: platform-linux, a: desktop, has reproducible steps, P2, team-desktop, triaged-desktop, found in release: 3.13, found in release: 3.16
