### ISSUE TITLE
Path_provider can't working on Android platform

### ISSUE THREAD

**Issue by vadimlukutin** [flutter/flutter#95741] opened 2021-12-23 19:01 UTC
E/flutter (23905): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

**Comment by stuartmorgan** [comment] 2021-12-23 19:26
Duplicate of https://github.com/flutter/flutter/issues/95706

**Closed by stuartmorgan** 2021-12-23 19:26 UTC
