### ISSUE TITLE
Gallery, Pesto: missing frames when quickly scrolling list of recipes

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5044] opened 2016-07-26 18:29 UTC
Tested on a Nexus 5X, built with profile mode.

Open Gallery, then tap pesto. Then, scroll up and down quickly.

Here's a performance overlay after a fast scroll:

![screen shot 2016-07-26 at 11 26 08 am](https://cloud.githubusercontent.com/assets/5479/17150303/c1061bdc-5323-11e6-964e-018e53d5cbfa.png)

Here's a trace:

![screen shot 2016-07-26 at 11 28 46 am](https://cloud.githubusercontent.com/assets/5479/17150393/1da99490-5324-11e6-96b8-717370e7b837.png)

Here's a zip of the trace file:

[pesto-fast-fling.json.zip](https://github.com/flutter/flutter/files/384505/pesto-fast-fling.json.zip)

**Comment by abarth** [comment] 2016-07-26 19:09
This is very likely to be image uploading (i.e., a dupe of #3805).  Assigning to @chinmaygarde because he's working on image uploading.

**Comment by abarth** [comment] 2016-08-02 21:58
This is now fixed with async image uploading.

**Closed by abarth** 2016-08-02 21:58 UTC
Labels: customer: gallery, ⚠ astounding performance
