### ISSUE TITLE
Overscroll on iOS is too "loose"

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10972] opened 2017-06-26 17:17 UTC
The following video was recorded by running [the scroll overlay app](https://github.com/flutter/scroll_overlay) on iOS:

[![Click to play video](https://img.youtube.com/vi/5YQ5tKCAcKc/0.jpg)](https://youtu.be/5YQ5tKCAcKc)

It shows that Flutter's overscroll on iOS allows the user to drag the content too far / too easily.

**Comment by tvolkert** [comment] 2017-06-26 17:23
FYI @chinmaygarde @cbracken @HansMuller

**Comment by eseidelGoogle** [comment] 2017-06-26 17:49
I suspect @xster may be the right person to fix this.

**Comment by Hixie** [comment] 2017-06-27 20:47
Related: https://github.com/flutter/flutter/issues/10977 https://github.com/flutter/flutter/issues/10976 https://github.com/flutter/flutter/issues/10972

**Comment by xster** [comment] 2017-06-30 23:41
Seems like we're only applying a linear friction to the overscroll. The original behaviour is likely higher order.

**Comment by xster** [comment] 2017-07-01 00:59
Another bug is that we're only applying the drag in one direction into the overscroll but the overscroll easing should have a drag as well.

**Comment by xster** [comment] 2017-07-06 01:40
More testing
![easing](https://user-images.githubusercontent.com/156888/27891892-51169836-61b1-11e7-9e7c-a1542abd7a94.gif)
![repeated](https://user-images.githubusercontent.com/156888/27891888-4e2c2bd6-61b1-11e7-966e-ccf176cebd72.gif)

**Comment by tvolkert** [comment] 2017-07-06 05:56
Awesome! 🥂

**Comment by tvolkert** [comment] 2017-07-18 15:44
Per @harveynick, the new overscroll behavior is actually worse.  Nick, can you provide details here?

**Comment by xster** [comment] 2017-07-18 16:48
One thing I can think of is there is a bug for lists smaller than the viewport size fixed in https://github.com/flutter/flutter/commit/5756d6293188ebcb0f7a8143829613557fafbe9b. @harveynick, is the issue on head?

**Comment by harveynick** [comment] 2017-07-23 10:14
No, this is with a list bigger than the viewport. The overscroll is now too tight and quite glitchy. It seems to get better or worse depending on the contents of the list. I can't easily post an example here, but I'll see if I can reproduce it in the gallery app.

**Comment by xster** [comment] 2017-07-31 20:38
@harveynick sure, anything works. Screen cap videos, sample apps, stuff in gallery.

**Comment by Hixie** [comment] 2017-08-15 18:14
I'm taking this off the customer critical list because we're not sure what needs to happen.

**Comment by xster** [comment] 2017-08-15 18:17
I'll actually close this for now. @harveynick feel free to reopen if it's still noticeable. Though I strongly suspect given your description that it was temporary while https://github.com/flutter/flutter/commit/5756d6293188ebcb0f7a8143829613557fafbe9b was not rolled into g3

**Closed by xster** 2017-08-15 18:17 UTC
Labels: customer: six (g3), prod: scrolling, waiting for customer response, ⌺‬ platform-ios
