### ISSUE TITLE
Illegal use of properties in engine.py recipe

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#84225] opened 2021-06-08 22:35 UTC
When using properties in recipes, we seem to use `api.properties.get` in the `RunSteps` branch of the code, this is deprecated, and isn't working well in our tests, see: https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/engine.py#1675.

This boils down to the fact the protobuf3 doesn't support wrapped primitive values and results in problems where

`api.properties.get('some_property_key', True)` to always return true even when `some_property_key` is explicitly set to `false`. This causes our `GenTests` code to generate code ignoring the branches that evaluate to `False`.

**Comment by iskakaushik** [comment] 2021-06-08 22:35
cc: @christopherfujino , @godofredoc FYI

**Comment by christopherfujino** [comment] 2021-06-08 22:49
thanks for root causing this @iskakaushik

**Comment by christopherfujino** [comment] 2021-06-09 00:04
> When using properties in recipes, we seem to use `api.properties.get` in the `RunSteps` branch of the code, **this is deprecated**

Is this deprecation documented? Or more importantly, what should we be doing instead?

**Comment by godofredoc** [comment] 2021-06-09 00:32
Yes properties have been un-officially deprecated for a few years in favor of protos but migrating to protos with the current recipe is not trivial.

I'd recommend to to wait until we split the recipes so we can get rid of all the properties used to create different version of a build before moving to protos.

**Comment by dnfield** [comment] 2021-06-29 03:18
This is blocking efforts where I'm trying to refactor how we check for build upload files for https://github.com/flutter/flutter/issues/85271 - basically, the tests don't do what they think they're doing, and as things are shifting it makes everything blow up.

@godofredoc - do you have information about what makes this difficult? I had started trying to use protos instead of properties a while back, but maybe I lost track of something.

**Comment by dnfield** [comment] 2021-06-29 19:07
The problem is that api.properties('foo', True) would force the property to always be true, since the default value is False instead of unset in the proto3 world. https://flutter-review.googlesource.com/c/recipes/+/15020 fixes this.

**Comment by dnfield** [comment] 2021-06-29 22:47
Fixed in https://flutter-review.googlesource.com/c/recipes/+/15021 instead, which passes JSON arguments more similarly to how the builders get them passed in.

**Closed by dnfield** 2021-06-29 22:47 UTC
Labels: P4, passed secondary triage, team: infra, tech-debt

**Comment by dnfield** [comment] 2021-06-29 22:48
To be clear: the real problem was the way the test generation code was passing in the properties, which involved using JSONPB and encoded "false" and empty/None the same.
