### ISSUE TITLE
Looks like a regression issue in Flutter Web (1.10.6-pre.27)

### ISSUE THREAD

**Issue by ptyagicodecamp** [flutter/flutter#41008] opened 2019-09-20 23:22 UTC
Getting following error in Chrome (console) and white page, when running Flutter Web app using `flutter run -d Chrome`.
Flutter installation info:
```
Flutter 1.10.6-pre.27 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8e23179627 (3 hours ago) • 2019-09-20 13:37:10 -0700
Engine • revision 99092a0436
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)

```

Error:
```
Uncaught (in promise) TypeError: Cannot read property 'hash' of undefined
    at HashLocationStrategy.get path [as path] (browser
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by CorbanR** [comment] 2019-09-21 01:51
I am also getting the same error 

```
Flutter 1.10.6-pre.29 • channel master • https://github.com/flutter/flutter.git
Framework • revision 919cc97f6a (4 hours ago) • 2019-09-20 14:57:05 -0700
Engine • revision 99092a0436
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)
```
Following directions from https://flutter.dev/docs/get-started/web on creating a new app.

**Comment by jonahwilliams** [comment] 2019-09-21 05:16
duplicate of https://github.com/flutter/flutter/issues/40876

**Closed by jonahwilliams** 2019-09-21 05:16 UTC
