### ISSUE TITLE
flutter doctor faild 

### ISSUE THREAD

**Issue by ahmedkhafagy800** [flutter/flutter#134078] opened 2023-09-04 00:37 UTC
![Screenshot (4)](https://github.com/flutter/devtools/assets/98766643/70697347-0765-4a52-b0f4-1dd3dddda494)

**Comment by huycozy** [comment] 2023-09-06 04:22
@ahmedkhafagy800 This is a Flutter tool issue and seems to be caused by wrong value of `--android-studio-dir`. You can try setting its value with the correct path, see [this](https://github.com/flutter/flutter/issues/99954#issuecomment-1641878300). 

Despite that, this is similar to a known issue at https://github.com/flutter/flutter/issues/99954. Closing as a duplicate.

**Closed by huycozy** 2023-09-06 04:22 UTC
Labels: in triage

**Comment by ahmedkhafagy800** [comment] 2023-09-07 12:16
> Yes please Upload it asap
now  i uploaded it

**Comment by TSxSAHIL** [comment] 2023-09-07 12:43
@ahmedkhafagy800 I have opened a pull request you can check and merge it accordingly

**Comment by ahmedkhafagy800** [comment] 2023-09-07 12:55
> @ahmedkhafagy800 I have opened a pull request you can check and merge it accordingly

![IMG-20230907-WA0028.jpg](https://github.com/flutter/flutter/assets/98766643/83fbd734-c7b2-4737-9d77-6bb23413a7f8)

**Comment by ahmedkhafagy800** [comment] 2023-09-07 12:57
i have errors in android studio, can you help me?

**Comment by TSxSAHIL** [comment] 2023-09-07 12:59
Yes

**Comment by TSxSAHIL** [comment] 2023-09-07 13:00
But please merge the pull request
