### ISSUE TITLE
Android dependency 'com.google.android.gms:play-services-basement' has different version for the compile (16.0.1) and runtime (17.0.0) classpath. 

### ISSUE THREAD

**Issue by a7me63azzab** [flutter/flutter#39686] opened 2019-09-02 12:49 UTC
## Error
```
  Execution failed for task ':app:preDebugBuild'.    > Android dependency 'com.google.android.gms:play-services-basement' has different version for the compile (16.0.1) and runtime (17.0.0) classpath. You should manually set the same version via DependencyResolution
```

## pubspec.yaml

``` cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.3+4
  flutter_launcher_icons: ^0.7.2+1
  auto_size_text: ^2.0.2+1
  image_picker: ^0.6.1
  dotted_border: ^1.0.2
  pinch_zoom_image: ^0.2.5
  flutter_swiper: ^1.1.6
  flutter_html: ^0.10.4
  google_maps_flutter: ^0.5.21
  geolocator: ^5.1.3
  location: ^2.3.5
  location_permissions: ^2.0.2
```

## Flutter doctor -v
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-EG)
    • Flutter version 1.7.8+hotfix.4 at /Users/apple/development/flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • D2302 • ZH8002SYU4 • android-arm • Android 5.1.1 (API 22)

• No issues found!``

**Comment by BondarenkoStas** [comment] 2019-09-02 13:02
Duplicate of #39561

**Comment by BondarenkoStas** [comment] 2019-09-02 13:16
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but with your gradle configuration.
But it occurs not at the first time, so I think it worth to keep it open here as well.

**Comment by a7me63azzab** [comment] 2019-09-02 13:21
Someone post the same error on stackoverflow 9 days ago and no answerhttps://stackoverflow.com/questions/57632026/android-dependency-com-google-android-gmsplay-services-tasks-has-different-ve

**Comment by githumbi** [comment] 2019-12-24 06:41
Still getting errors after upgrading to the latest SDK version.
Can someone explain how you make the current project compatible with version 1.12.13+hotfix.6 • channel beta

**Comment by TahaTesser** [comment] 2020-03-10 15:34
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

Thank you

**Closed by TahaTesser** 2020-03-10 15:34 UTC
Labels: d: stackoverflow, plugin, ▣ platform-android
