### ISSUE TITLE
video_player: Please add support for Windows

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#147518] opened 2024-04-29 13:26 UTC
### Use case

I actually only need there lines to work not the full package
```
    VideoPlayerController controller = VideoPlayerController.file(file);
    await controller.initialize();
    var height = controller.value.size.height;
    var width = controller.value.size.width;
```

### Proposal

can you implement a really basic version for Windows?

**Comment by danagbemava-nc** [comment] 2024-04-29 13:29
Closing this as a duplicate of https://github.com/flutter/flutter/issues/37673

**Closed by danagbemava-nc** 2024-04-29 13:29 UTC
Labels: in triage
