### ISSUE TITLE
macOS KeyUpEvent + Chinese PinYin exception

### ISSUE THREAD

**Issue by PassionPenguin** [flutter/flutter#130651] opened 2023-07-15 05:39 UTC
### Code

the exception was caught when debugging my application and use it myself when suddenly keyboard events are not accepted by the application. Found the exception in console output, I reproduced it with `flutter create` and modify the home-body with TextField only:

```sh
flutter create tmp
cd tmp
vi lib/main.dart
```

Replace `main.dart` with the following content:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(body: TextField()), // the only line changed. Nothing else is needed.
    );
  }
}
```

Run the application in macOS environment:

```sh
flutter run -d macos
```

### system settings pre-requirement

1. Enable Chinese Simplified or Chinese Traditional with PinYin.
2. Enable `Use the Caps Lock key to switch to and from ABC` (the second setting tile in the screenshot below)

<img width="827" alt="Screenshot 2023-07-15 at 1 34 10 PM" src="https://github.com/flutter/flutter/assets/41184947/00056a39-c02a-4098-9d7a-26a1dcb2eb74">

### reproducing the exception

1. toggle the input method to PinYin
<img width="428" alt="Screenshot 2023-07-15 at 1 35 58 PM" src="https://github.com/flutter/flutter/assets/41184947/5fb9503f-0aec-40c4-9cc9-431ff6f4ae0b">

2. typing in characters and clicking caps-lock at the same time(you may click as fast as you can)

## Exception

```log
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following assertion was thrown during a platform message callback:
                    A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different
                    logical key. If this occurs in real application, please report this bug to Flutter. If this occurs
                    in unit tests, please ensure that simulated events follow Flutter's event model as documented in
                    `HardwareKeyboard`. This was the event: KeyUpEvent#122fd(physicalKey:
                    PhysicalKeyboardKey#8f27a(usbHidUsage: "0x0007000b", debugName: "Key H"), logicalKey:
                    LogicalKeyboardKey#b782e(keyId: "0x140007000b", keyLabel: "", debugName: "Key with ID
                    0x0140007000b"), character: null, timeStamp: 22:15:31.751770) and the recorded logical key
                    LogicalKeyboardKey#268e8(keyId: "0x00000068", keyLabel: "H", debugName: "Key H")
                    'package:flutter/src/services/hardware_keyboard.dart':
                    Failed assertion: line 437 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'
                    
                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md
                    
                    When the exception was thrown, this was the stack:
                    #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:437:16)
                    #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:445:6)
                    #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:537:5)
                    #5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:956:37)
                    #6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
                    #7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:35)
                    #8      _invoke2 (dart:ui/hooks.dart:174:13)
                    #9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
                    #10     _Channel.push (dart:ui/channel_buffers.dart:130:31)
                    #11     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
                    #12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:686:22)
                    #13     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
                    (elided 2 frames from class _AssertionError)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════


 Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this
occurs in
                    unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#122fd(physicalKey: PhysicalKeyboardKey#8f27a(usbHidUsage:
"0x0007000b", debugName:
                    "Key H"), logicalKey: LogicalKeyboardKey#b782e(keyId: "0x140007000b", keyLabel: "", debugName: "Key with ID 0x0140007000b"), character: null, timeStamp: 22:15:31.751770) and the recorded logical key
                    LogicalKeyboardKey#268e8(keyId: "0x00000068", keyLabel: "H", debugName: "Key H")
```

Notice that in the second exception the key which sent `KeyUpEvent` is random refering to the key you before which you press `caps lock` key. The exception was reproduced for 5 times both in my production-app and the minimal-code-app.

**Comment by PassionPenguin** [comment] 2023-07-15 06:13
Maybe a way-more-easier method to reproduce the exception:

Given the exception was thrown due to inadequate time for flutter to handle key events, pressing Caps-Lock and any other 26keys when input method is PinYin and Caps-Lock-Toggle is on is also possible to reproduce the exception.

1. Config as above(Pinyin, Caps-Lock-Toggle)
2. `flutter run -d macos`
3. toggle the input to PinYin
4. pressing any 26-keys(`h` for example here) and Caps-Lock key at the same time.

```log
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different
logical key. If this occurs in real application, please report this bug to Flutter. If this occurs
in unit tests, please ensure that simulated events follow Flutter's event model as documented in
`HardwareKeyboard`. This was the event: KeyUpEvent#19c61(physicalKey:
PhysicalKeyboardKey#8f27a(usbHidUsage: "0x0007000b", debugName: "Key H"), logicalKey:
LogicalKeyboardKey#b782e(keyId: "0x140007000b", keyLabel: "", debugName: "Key with ID
0x0140007000b"), character: null, timeStamp: 22:57:48.754899) and the recorded logical key
LogicalKeyboardKey#268e8(keyId: "0x00000068", keyLabel: "H", debugName: "Key H")
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 437 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:437:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:445:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:537:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:956:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:35)
#8      _invoke2 (dart:ui/hooks.dart:174:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:686:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in
unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#19c61(physicalKey: PhysicalKeyboardKey#8f27a(usbHidUsage: "0x0007000b", debugName:
"Key H"), logicalKey: LogicalKeyboardKey#b782e(keyId: "0x140007000b", keyLabel: "", debugName: "Key with ID 0x0140007000b"), character: null, timeStamp: 22:57:48.754899) and the recorded logical key
LogicalKeyboardKey#268e8(keyId: "0x00000068", keyLabel: "H", debugName: "Key H")
```

**Comment by PassionPenguin** [comment] 2023-07-15 06:14
Flutter + System config:

```sh
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-x64, locale en-US)
    • Flutter version 3.10.3 on channel stable at /usr/local/Caskroom/flutter/3.10.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (6 weeks ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/hoarfroster/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary

[!] Android Studio
    • Android Studio at /Users/hoarfroster/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/231.8109.175.2311.10205233/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.81.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.68.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost,127.0.0.0,127.0.1.1,local.home,::1,
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4 22F66 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5889.0 canary

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by huycozy** [comment] 2023-07-17 09:40
Thanks for your report. Reproduced the issue on the latest Flutter stable and master channels. This issue occurs on macOS and Web platforms with stack traces as below. 


<details>
<summary>Output stack trace - macos</summary>

```console
2023-07-17 16:30:41.751 reproduce_issues_2[53386:9402242] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different
flutter: logical key. If this occurs in real application, please report this bug to Flutter. If this occurs
flutter: in unit tests, please ensure that simulated events follow Flutter's event model as documented in
flutter: `HardwareKeyboard`. This was the event: KeyUpEvent#bcffd(physicalKey:
flutter: PhysicalKeyboardKey#ae4f7(usbHidUsage: "0x00070016", debugName: "Key S"), logicalKey:
flutter: LogicalKeyboardKey#96ea3(keyId: "0x1400070016", keyLabel: "", debugName: "Key with ID
flutter: 0x01400070016"), character: null, timeStamp: 174:57:19.121910) and the recorded logical key
flutter: LogicalKeyboardKey#45b63(keyId: "0x00000073", keyLabel: "S", debugName: "Key S")
flutter: 'package:flutter/src/services/hardware_keyboard.dart':
flutter: Failed assertion: line 474 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey'
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:474:16)
flutter: #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:482:6)
flutter: #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:601:5)
flutter: #5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1021:37)
flutter: #6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
flutter: #7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
flutter: #8      _invoke2 (dart:ui/hooks.dart:202:13)
flutter: #9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
flutter: #10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
flutter: #11     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
flutter: #12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:745:22)
flutter: #13     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
16
flutter: Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#bcffd(physicalKey: PhysicalKeyboardKey#ae4f7(usbHidUsage: "0x00070016", debugName: "Key S"), logicalKey: LogicalKeyboardKey#96ea3(keyId: "0x1400070016", keyLabel: "", debugName: "Key with ID 0x01400070016"), character: null, timeStamp: 174:57:19.121910) and the recorded logical key LogicalKeyboardKey#45b63(keyId: "0x00000073", keyLabel: "S", debugName: "Key S")

```
</details>

<details>
<summary>Output stack trace - web</summary>

```console
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
Error: Assertion failed: file:///Users/huynq/Documents/GitHub/flutter_master/packages/flutter/lib/src/services/hardware_keyboard.dart:474:16
_pressedKeys[event.physicalKey] == event.logicalKey
"A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#2b45b(physicalKey: PhysicalKeyboardKey#70016(usbHidUsage: \"0x00070016\", debugName: \"Key S\"), logicalKey: LogicalKeyboardKey#00073(keyId: \"0x00000073\", keyLabel: \"S\", debugName: \"Key S\"), character: null, timeStamp: 0:00:36.711899, synthesized) and the recorded logical key LogicalKeyboardKey#ae73a(keyId: \"0x100000001\", keyLabel: \"Unidentified\", debugName: \"Unidentified\")"
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
packages/flutter/src/services/hardware_keyboard.dart 474:56                       <fn>
packages/flutter/src/services/hardware_keyboard.dart 481:14                       [_assertEventIsRegular]
packages/flutter/src/services/hardware_keyboard.dart 601:5                        handleKeyEvent
packages/flutter/src/services/hardware_keyboard.dart 948:29                       handleKeyData
lib/_engine/engine/platform_dispatcher.dart 332:33                                <fn>
lib/_engine/engine/platform_dispatcher.dart 1304:13                               invoke
lib/_engine/engine/platform_dispatcher.dart 331:7                                 invokeOnKeyData
lib/_engine/engine/keyboard_binding.dart 161:39                                   [_onKeyData]
lib/_engine/engine/keyboard_binding.dart 579:36                                   <fn>
lib/_engine/engine/keyboard_binding.dart 457:11                                   [_handleEvent]
lib/_engine/engine/keyboard_binding.dart 582:7                                    handleEvent
lib/_engine/engine/keyboard_binding.dart 98:18                                    <fn>
lib/_engine/engine/keyboard_binding.dart 140:16                                   loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 hours ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.13.0-3.0.pre.91, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.13.0-3.0.pre.91 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5a866a031f (3 hours ago), 2023-07-16 17:36:30 -0700
    • Engine revision 683087731f
    • Dart version 3.1.0 (build 3.1.0-315.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by htoor3** [comment] 2023-07-20 17:38
I'm going to mark this as a duplicate of https://github.com/flutter/flutter/issues/126247 - the `HardwareKeyboard` error seems to be occurring for languages that require IME (Chinese PinYin, Korean, Japanese, etc).  I believe these are related - will try to prioritize a fix.

**Comment by htoor3** [comment] 2023-07-20 17:38
I'm going to mark this as a duplicate of https://github.com/flutter/flutter/issues/126247 - the HardwareKeyboard error seems to be occurring for languages that require IME (Chinese PinYin, Korean, Japanese, etc). I believe these are related - will try to prioritize a fix.

**Closed by htoor3** 2023-07-20 17:38 UTC
Labels: a: text input, c: crash, framework, engine, platform-mac, platform-web, a: desktop, has reproducible steps, found in release: 3.10, team-desktop, found in release: 3.13
