### ISSUE TITLE
visited platform views list not cleared

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#109783] opened 2022-08-18 17:05 UTC
https://github.com/flutter/engine/pull/34355 adds a feature that platform view ids are pushed to a visited_platform_views list. However, the list is not cleared after each frame.

The list needs to be cleared at the start of each frame.

**Comment by zanderso** [comment] 2022-08-19 16:16
This rolled into the framework in https://github.com/flutter/flutter/commit/5e6adcb493374c9a790a8d48605440c606a2d877 on August 10th. We need to notify the internal rollers team of this regression so that customer teams don't cut releases based on the bad commit range. cc @itsjustkevin @khyati82

**Comment by zanderso** [comment] 2022-08-19 16:17
Marking P0 for bookkeeping purposes, but this will be addressed by the revert in https://github.com/flutter/engine/pull/35543

**Comment by zanderso** [comment] 2022-08-19 17:01
The revert has landed. Leaving this open until it rolls into the framework.

**Comment by xster** [comment] 2022-08-20 00:05
It's not clear what the symptoms/impact could be. To make things easier for announcements etc, could you elaborate a bit @cyanglaz?

**Comment by cyanglaz** [comment] 2022-08-20 16:57
> It's not clear what the symptoms/impact could be. To make things easier for announcements etc, could you elaborate a bit @cyanglaz?

A list of visitedPlatformView is created in the reverted PR. When a platform_view_layer is visited, the platform view id is pushed to the list. The list is supposed to be cleared at the beginning of each frame, but it never was. So it makes the list forever increasing, which impacts the performance after the App runs for a while with PlatformViews on the screen.

**Comment by zanderso** [comment] 2022-08-21 18:45
The revert rolled into the framework in https://github.com/flutter/flutter/commit/a9750d6a2ef9b8a18678f96fcc7345e425e3c857.

@xster In particular, the performance of `BackdropFilter` will get severely slower and slower each time a new platform view is displayed.

**Comment by chinmaygarde** [comment] 2022-08-22 17:34
This issue is open because the notification of the bad builds needs to be propagated right?

**Comment by xster** [comment] 2022-08-22 17:43
@jiahaog ok, I think the description is clearer and the issue is severe. We should make an announcement

**Comment by zanderso** [comment] 2022-08-22 17:43
I think the right folks have been notified, so I'm going to close this.

**Closed by zanderso** 2022-08-22 17:43 UTC
Labels: engine, P0

**Comment by xster** [comment] 2022-08-22 19:44
@khyati82 we should get started on the post-mortem on this one too

**Comment by xster** [comment] 2022-08-23 00:04
@zanderso I think you mentioned iOS but this affects all platforms? Or am I misreading?

**Comment by cyanglaz** [comment] 2022-08-23 00:38
> @zanderso I think you mentioned iOS but this affects all platforms? Or am I misreading?

This is iOS only. Add the iOS label to the issue.
