### ISSUE TITLE
Gallery, Data tables: missed CPU frames when opening/closing the Data table demo

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5010] opened 2016-07-22 19:56 UTC
On my iPod Touch:
- Open gallery
- Tap Data tables

Notice in the screenshot below the spikes in the CPU chart. Those spikes are from opening/closing (displaying/hiding) the data tables.

![img_0011](https://cloud.githubusercontent.com/assets/5479/17069454/9032a39c-500b-11e6-819b-b7b52e08982b.PNG)

**Comment by sethladd** [comment] 2016-07-22 19:56
cc @Hixie

**Comment by Hixie** [comment] 2016-07-22 21:54
Yeah. These tables are very expensive to lay out.

**Comment by sethladd** [comment] 2016-07-22 23:19
Is this a good test case for Dart's compiler infrastructure, something that can be optimized at that layer?

**Comment by Hixie** [comment] 2016-07-23 00:24
It's just a bunch of expensive algorithms. To lay the table out, every cell of every row has to be visited twice, once to determine the column widths, and once to lay everything out. Plus some more complicated things around baselines and so forth.

I probably need to make another pass and clean things up and optimise what it's doing.

**Comment by darshankawar** [comment] 2020-09-04 08:29
Since I don't have ipod touch, so can't replicate it. 
@sethladd Can you please confim if this is still a valid issue ?
Thanks.

**Comment by guidezpl** [comment] 2022-04-13 12:18
Closing as not reproducible. If you disagree, please file an issue at https://github.com/flutter/gallery.

**Closed by guidezpl** 2022-04-13 12:18 UTC
Labels: team, framework, severe: performance, team: gallery, passed first triage, P4
