### ISSUE TITLE
Floating point math issue in sliver app bars

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#8180] opened 2017-02-15 17:40 UTC
The app below is just a CustomScrollView with three slivers:
1 - A pinned fixed height header defined with  _SliverStatusBarPaddingDelegate
2 - A pinned header defined with _SliverAppBarDelegate. Turns red when overlapsContent=true
3 - A SliverToBoxAdapter that contains a fixed height=1200 sized box.

During scrolling I expected sliver 2 to only be red when the sliver 3 scrolled behind it. It's always red because overlapsContent is almost always true. But it shouldn't be? The parameter isn't documented so I'm just guessing its meaning based on the way it's used by AppBar.

During scrolling the following exception appears intermittently. I'm afraid it can be difficult to reproduce.

```
I/flutter (31217): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (31217): The following assertion was thrown during performLayout():
I/flutter (31217): SliverGeometry has a layoutExtent that exceeds its paintExtent.
I/flutter (31217): The paintExtent is 530.4498268371303, but the layoutExtent is 530.4498268371304. Maybe you have
I/flutter (31217): fallen prey to floating point rounding errors, and should explicitly apply the min() or max()
I/flutter (31217): functions, or the clamp() method, to the layoutExtent?
I/flutter (31217): When the exception was thrown, this was the stack:
I/flutter (31217): #0      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:461:9)
I/flutter (31217): #2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:459:12)
I/flutter (31217): #3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:693:21)
I/flutter (31217): #4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1750:19)
I/flutter (31217): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1750:14)
I/flutter (31217): #7      RenderViewportBase2.layoutOneSide (package:flutter/src/rendering/sliver.dart:1223:13)
I/flutter (31217): #8      RenderViewport2._attemptLayout (package:flutter/src/rendering/sliver.dart:1712:12)
I/flutter (31217): #9      RenderViewport2.performLayout (package:flutter/src/rendering/sliver.dart:1641:20)
I/flutter (31217): #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1624:7)
I/flutter (31217): #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:953:18)
I/flutter (31217): #12     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:223:19)
I/flutter (31217): #13     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:333:23)
I/flutter (31217): #14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:168:5)
I/flutter (31217): #15     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:676:15)
I/flutter (31217): #16     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:611:9)
I/flutter (31217): #17     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (31217): (elided 2 frames from class _AssertionError)
I/flutter (31217): The following RenderObject was being processed when the exception was fired:
I/flutter (31217):   _RenderSliverPinnedPersistentHeaderForWidgets relayoutBoundary=up1
I/flutter (31217):   creator: _SliverPinnedPersistentHeader ← SliverPersistentHeader ← Viewport2 ←
I/flutter (31217):   IgnorePointer-[GlobalKey 703668342] ← Listener ← _GestureSemantics ←
I/flutter (31217):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState> 323752371] ← RepaintBoundary ←
I/flutter (31217):   CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification2> ←
I/flutter (31217):   GlowingOverscrollIndicator ← ⋯
I/flutter (31217):   parentData: paintOffset=Offset(0.0, 0.0)
I/flutter (31217):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward,
I/flutter (31217):   ScrollDirection.reverse, scrollOffset: 36.6, remainingPaintExtent: 592.0, overlap: 25.0,
I/flutter (31217):   crossAxisExtent: 360.0viewportMainAxisExtent: 592.0)
I/flutter (31217):   geometry: SliverGeometry(scrollExtent: 567.0, paintExtent: 530.4, layoutExtent: 530.4,
I/flutter (31217):   maxPaintExtent: 592.0, hasVisualOverflow: true, scrollOffsetCorrection: 0.0)
I/flutter (31217):   maxExtent: 567.0
I/flutter (31217):   child position: 25.0
I/flutter (31217): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (31217):   RenderConstrainedBox relayoutBoundary=up2
I/flutter (31217):     RenderDecoratedBox
I/flutter (31217):       RenderPadding
I/flutter (31217):         RenderCustomPaint
I/flutter (31217): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (31217): Another exception was thrown: SliverGeometry has a layoutExtent that exceeds its paintExtent.
I/flutter (31217): Another exception was thrown: SliverGeometry has a layoutExtent that exceeds its paintExtent.
I/flutter (31217): Another exception was thrown: SliverGeometry has a layoutExtent that exceeds its paintExtent.
```

```dart
import 'dart:math' as math;

import 'package:flutter/material.dart';

class PlaceholderPainter extends CustomPainter {
  void paint(Canvas canvas, Size size) {
    Paint paint = new Paint()
      ..color = Colors.white
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1.0;
    canvas.drawLine(Point.origin, new Point(size.width, size.height), paint);
    canvas.drawLine(new Point(size.width, 0.0), new Point(0.0, size.height), paint);
  }

  bool shouldRepaint(_) => false;
}

// Renders a colored bordered box with an X that extends to the corners.
class Placeholder extends StatelessWidget {
  Placeholder({ @required this.colors }) {
    assert(colors != null);
  }

  final Map<int, Color> colors;

  @override
  Widget build(BuildContext context) {
    return new Container (
      decoration: new BoxDecoration(
        backgroundColor: colors[400],
        border: new Border.all(color: colors[200], width: 3.0),
      ),
      child: new CustomPaint(painter: new PlaceholderPainter()),
    );
  }
}

class _SliverStatusBarPaddingDelegate extends SliverPersistentHeaderDelegate {
  _SliverStatusBarPaddingDelegate({ @required this.height });

  final double height;

  @override double get minExtent => height;
  @override double get maxExtent => height;

  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {
    return new SizedBox.expand(
      child: new Placeholder(colors: Colors.orange),
    );
  }

  @override
  bool shouldRebuild(@checked _SliverStatusBarPaddingDelegate oldDelegate) {
    return height != oldDelegate.height;
  }
}

class _SliverAppBarDelegate extends SliverPersistentHeaderDelegate {
  _SliverAppBarDelegate({
    @required this.collapsedHeight,
    @required this.expandedHeight,
  });

  final double expandedHeight;
  final double collapsedHeight;

  @override double get minExtent => collapsedHeight;
  @override double get maxExtent => math.max(expandedHeight, minExtent);

  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {
    return new SizedBox.expand(
      child: new Placeholder(colors: overlapsContent ? Colors.red : Colors.teal),
    );
  }

  @override
  bool shouldRebuild(@checked _SliverAppBarDelegate oldDelegate) {
    return expandedHeight != oldDelegate.expandedHeight
        || collapsedHeight != oldDelegate.collapsedHeight;
  }
}

class SliverIssue extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final MediaQueryData mediaQueryData = MediaQuery.of(context);
    final double statusBarHeight = mediaQueryData.padding.top;
    final double screenHeight = mediaQueryData.size.height;

    return new CustomScrollView(
      slivers: <Widget>[
        new SliverPersistentHeader(
          pinned: true,
          delegate: new _SliverStatusBarPaddingDelegate(
            height: statusBarHeight,
          ),
        ),
        new SliverPersistentHeader(
          pinned: true,
          delegate: new _SliverAppBarDelegate(
            expandedHeight: screenHeight - statusBarHeight,
            collapsedHeight: 200.0,
          ),
        ),
        new SliverToBoxAdapter(
          child: new SizedBox(
            height: 1200.0,
            child: new Placeholder(colors: Colors.blue),
          ),
        ),
      ],
    );
  }
}

void main() {
  runApp(new MaterialApp(home: new SliverIssue()));
}
```

**Comment by Hixie** [comment] 2017-02-15 19:07
I recommend trying to make a unit test that reproduces the error reliably, and then reducing it until it's got the fewest slivers needed for reproduction.

**Comment by Hixie** [comment] 2017-11-29 00:43
Moving this out to beyond m3 since it doesn't currently fit our priorities, but it is something we will fix in due course. Please let us know if this is a priority for you and you can't work around it.

**Comment by chunhtai** [comment] 2020-04-09 16:55
I cannot reproduce, it is probably fixed

**Closed by chunhtai** 2020-04-09 16:55 UTC
Labels: f: scrolling, framework, severe: crash
