### ISSUE TITLE
The height of Tab can not be set.

### ISSUE THREAD

**Issue by Hanggi** [flutter/flutter#24228] opened 2018-11-11 18:46 UTC
There is a SizedBox in Tab class, the height of SizedBox cannot be modified.

I need a less height of Tabbar tab.

same as #13322
Thank you.

**Comment by zoechi** [comment] 2019-02-21 09:22
Duplicate of #13322

**Closed by zoechi** 2019-02-21 09:22 UTC
Labels: f: material design, framework, severe: new feature

**Comment by zoechi** [comment] 2019-02-21 12:52
Closing as duplicate of #13322
