### ISSUE TITLE
[webview_flutter] Add support for all platforms

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#138378] opened 2023-11-13 23:48 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

`webview_flutter` is the official package for managing web views, yet, it lacks support for all platforms that flutter supports, only supporting `ios` and `android` for now.

### Proposal

`webview_flutter` should support `windows`, `macos`, `linux` and `web`, so we can seamlessly port our apps to new platforms.

**Comment by stuartmorgan** [comment] 2023-11-14 00:41
> `webview_flutter` should support `windows`, `macos`, `linux`

Closing as a duplicate of https://github.com/flutter/flutter/issues/37597, https://github.com/flutter/flutter/issues/41725, and https://github.com/flutter/flutter/issues/41726.

> and `web`

See https://pub.dev/packages/webview_flutter_web. Please feel free to file specific feature requests for functionality. However:

> so we can seamlessly port our apps to new platforms.

any application with complex usage of `webview_flutter` cannot be seamlessly ported to web, because the web platform simply does not allow sub-hosting arbitrary pages within arbitrary other pages with full control over them; doing so is fundamentally incompatible with fundamental security principles of the web.

**Closed by stuartmorgan** 2023-11-14 00:41 UTC

**Comment by feinstein** [comment] 2023-11-14 00:49
@stuartmorgan thanks, I didn't find these duplicate issues, github search isn't helping much. Maybe we should create a parent issue to track all platform implementations?

**Comment by feinstein** [comment] 2023-11-14 01:01
@stuartmorgan just to confirm from your explanation, there's no way to make a mechanism where my flutter code can send a command, or receive back a message, from the embedded website, right?

I wanted to play/pause a 3D animation that was made as a website and we own all the web source code.

**Comment by stuartmorgan** [comment] 2023-11-14 01:05
It sounds like you want https://github.com/flutter/flutter/issues/101758; you can follow that for updates.

> @stuartmorgan thanks, I didn't find these duplicate issues, github search isn't helping much. Maybe we should create a parent issue to track all platform implementations?

If searches aren't turning up the three existing issues, it seems unlikely that adding a fourth would help.

**Comment by feinstein** [comment] 2023-11-14 01:20
Yeah, but many issues that fragment into multiple ones have a parent issue, so it could help us track down how is the current compatibility across all platforms, like [this](https://github.com/flutter/flutter/issues/60113) umbrella issue you created for Apple Silicon.
