### ISSUE TITLE
Add other programming languages compatible with Flutter

### ISSUE THREAD

**Issue by yhojann-cl** [flutter/flutter#145295] opened 2024-03-17 19:40 UTC
### Use case

> Please tell us the problem you are running into that led to you wanting a new feature.

The problem is that I do not have a comfortable and flexible language to develop in Flutter, the only option is the Dart language which has several deficiencies.

My original goal is to be able to create applications for Android and Linux Desktop from a single project, for this I have chosen Flutter (since there is no other with good support and linux app is not supported by react native and react native skia embed the js source code on compiled app, is not realy a compiled code), I would like to be able to develop directly with languages that already exist, that are already tested, have long acceptance time and they have a considerable number of users, it is safe and so on, for example, java, python, nodejs and rust.

Why use Dart instead of Golang which is another language abandoned by Google? I don't know, no one knows, what I do know is that Oracle wants to bite Google with Java, the same could happen with C#, but not so with python, rust or nodejs.

For example, the same thing that you can do in Kotlin in 30 lines, in Nodejs you can do it in 2 with simple streams, the same thing happens with Python, each language could include its own libraries from pip or npm instead of trying to reinvent the wheel with dart.

An example of the impracticality of dart is the handling of anti-intuitive asynchronous processes that depend on double declarations on the left and right as a functional patch inherited from old versions of javascript (ES6) where you could not execute an await if the function It was not asynchronous.

Related posts:
- https://www.reddit.com/r/FlutterDev/comments/17j3zzt/java_instead_of_dart/
- https://stackoverflow.com/questions/78176323/how-to-make-a-concatenated-async-function-in-flutter

> Describe the alternative solutions you've considered. Is there a package on pub.dev/flutter that already solves this?

Yes: https://docs.flutter.dev/platform-integration/platform-channels but only works with the native code (a diferent code for each platform).

### Proposal

When creating the project there should be some option to indicate which base language to use, something like in Android projects where you can choose Java, Kotlin or C++. Like as NodeJS and ReactJS:

```
const { flutter, FlutterApp, Component } = require('flutter');
const { Scaffold, ElevatedButton } = require('flutter/material');

class App extends Component {
    
    constructor() {
        super();
        this.state = {
            val: 0
        };
    }

    render() {
        return new FlutterApp({
            title: `Pressed ${this.state.val} times`,
            home: new Scaffold({
              body: new ElevatedButton({
                  onPressed: () => this.setState({ val: this.state.val++ })
              })
            })
        });
    }
}

flutter.render(new App());
```

It is much easier for people who know javascript to develop for Flutter than for people to learn a new language with similarities to other languages, adding a new language to learn.

When a developer studies to work in the future, he does so by learning languages where he can be productive at work. Very few companies request developers in Dart. However, most companies in the world request developers with knowledge of Java or Nodejs, especially for applications. serverside and clientside web.

Why add a barrier in making cross-platform applications if you can make everything easier using popular languages like golang, python, nodejs, java (maybe), c# (maybe) and rust?

**Comment by darshankawar** [comment] 2024-03-18 11:05
Closing as duplicate of https://github.com/flutter/flutter/issues/109522

**Closed by darshankawar** 2024-03-18 11:05 UTC
Labels: in triage
