### ISSUE TITLE
Add more granularity when using the InteractiveViewer zoom

### ISSUE THREAD

**Issue by Guthers** [flutter/flutter#76765] opened 2021-02-25 06:02 UTC
Hello, I am using the package graphview. And I have run into a bit of an issue with the InteractiveViewer. Particularity when zooming in and out on web, it is too "fast"?. In the InteractiveViewer file it has the following comment.

```
// In the Flutter engine, the mousewheel scrollDelta is hardcoded to 20 per scroll, while a trackpad scroll can be any amount.
// The calculation for scaleChange here was arbitrarily chosen to feel natural for both trackpads and mousewheels on all platforms.
final double scaleChange = math.exp(-event.scrollDelta.dy / 200);
```

I would suggest the easiest way to fix this would be to make the 200 a variable you can pass to the class so that you can change the rate of scroll.

Thanks,
Harry

**Comment by pedromassangocode** [comment] 2021-02-25 09:19
Hi @Guthers 
I believe this is somehow a duplicate of https://github.com/flutter/flutter/issues/71676 as it seems to mention your proposal there.

**Comment by HansMuller** [comment] 2021-02-25 17:22
CC @justinmc

**Comment by Guthers** [comment] 2021-02-26 00:12
I think there is some overlap true, but my proposal might be an easy step towards that? Just allowing for a linear change to scroll speed would improve the experience where it is really required (for example trying to zoom in and out on a diagram and going too far out or in, in any step), and would likely be a much simpler fix. Although something like proposed in #71676 would eventually be the best solution

**Comment by Guthers** [comment] 2021-02-26 00:13
Also, as a side note, as I am not sure if it is possible (if not I will likely make another issue) but is it possible to have a range slider linked to the scale of the interactive viewer? Potentially be default, if not through listeners?

**Comment by justinmc** [comment] 2021-02-26 01:02
I agree that this issue should stay open for now.  Currently the speed of the zoom is not related to the physics, though maybe it should be in the long term.

The PR https://github.com/flutter/flutter/pull/71266 adjusted the speed of zooming and added the quoted lines above.  It made it much better on most platforms, but I guess still not ideal for everywhere.  Maybe the best way is just to accept a parameter for that "200" value as `scrollDeltaScale`.

And yes it is possible to tie a slider to the scale through listeners, but not by default.  You can update the [TransformationController](https://master-api.flutter.dev/flutter/widgets/TransformationController-class.html) in `setState` when the slider changes.

**Comment by Guthers** [comment] 2021-02-26 04:48
Thanks for getting back to me @justinmc, I did have a look at that, I suppose my issue is, as far as I could tell I couldn't provide a number between my min and max scale easily, it looked like I had to pass a matrix, which all of the functions relating that scale to the matrix are private inside of the InteractiveViewer (sorry if this is off topic to the above, happy to continue the discussion elsewhere?)

**Comment by RomanJos** [comment] 2021-03-17 20:13
This value has been set subjectively, I first thought to modify this value based on the viewport size but Google maps seems to have a fixed value.
So for me adding a `scrollDeltaScale` parameter would solve the issue

**Comment by longtimedeveloper** [comment] 2021-11-29 16:35
@justinmc can you have a look at this issue. I've copied my proposal here.

I'm kind of new to Flutter, this issue has been open a long time.

Is there any possible workaround for Flutter Web apps?  I'm writing a game and really need this capability.  Thank you!!

**Proposal from my closed issue**  https://github.com/flutter/flutter/issues/94315

To the InteractiveViewer widget, add a user-settable double property `mouseWheelSensitivity `that either increases or decreases the effective delta changes between mouse wheel movements.

`mouseWheelSensitivity `should default to 1.0 so that this enhancement would not break any applications.

When testing, I recommend using a large image 2570 x 1926. The below link is to a game board that I'm using in a game I'm writing. After downloading this image, open it in your favorite editor and save it as a JPG image as the PNG is 12 MB. The JPG comes in a 2.8 MB.

I recommend testing using different screen resolutions so you can see the user experience when scrolling the mouse wheel with various screen resolutions and `mouseWheelSensitivity `settings.

https://github.com/tim-koehler/ScotlandYard/blob/master/resources/map.png

**Comment by justinmc** [comment] 2021-11-30 18:55
@longtimedeveloper Thanks for getting in touch about this.  It would be pretty easy to add a new parameter like mouseWheelSensitivity, but I want to make sure that's the best solution for as many situations as possible.

For example, it sounds like mouseWheelSensitivity might need to change depending on the platform and maybe even also depending on the screen resolution, etc.  If it existed, how would you use it?  Would you have a `switch` statement for the platform and set it to a different value for each platform?

Here's the code where the change in scale is calculated for the record:

https://github.com/flutter/flutter/blob/361d416e6abb66bf601c5a6600fbc37706bb6c14/packages/flutter/lib/src/widgets/interactive_viewer.dart#L885-L889

**Comment by longtimedeveloper** [comment] 2021-11-30 19:21
@justinmc In my game, I'll provide a slider for users to make the adjustment to the mouse sensitivity at runtime.  This greatly simplifies my code and provides the very best user experience.  Once they have set it, I can save the value in preferences.

My code would not have to fuss with the platform, screen size, etc. They would just set the value that works best for their user experience.  Remember that Windows and macOS allow the user to set their desired scrolling speed (mouse wheel sensitivity).  So different users would have different values.  Default is 3.  I normally set mine to 6.  By providing a runtime settable slider, users can very easily adjust the zoom of the game board using the slider and without my code trying to do any magic.

I would strongly recommend adding `mouseWheelSensitivity ` so that the mouse scroll wheel can have separate settings from the trackpad.  These are two very different input devices and should be independently adjustable at runtime.  This would make it much easier for the framework code also and would also remove hardcoded values used for calculations.

Can your code determine if the input is a Trackpad or Mouse Wheel?  If so, this should be super easy and open the door to having a `trackpadSensitivity` setting as well.  If not, then a single property would do.

I'm sure that touch-enabled devices may have this type of setting as well, not sure.

Given the wide variety of devices, screen sizes, resolutions, mouse wheel speeds, etc., exposing public user-settable properties would make this widget very developer and user friendly.

Thank you for your time and consideration!  Best regards, Karl

**Comment by justinmc** [comment] 2021-11-30 19:59
Got it, that sounds reasonable.  It doesn't look like you can easily distinguish between trackpad and mouse events in [PointerSignalEvent](https://master-api.flutter.dev/flutter/gestures/PointerSignalEvent-class.html), but maybe there is a way, I'll double check.

You might be able to achieve what you want currently by listening to scale events via [onInteractionUpdate](https://master-api.flutter.dev/flutter/widgets/InteractiveViewer/onInteractionUpdate.html) and handling them however you want.  You may want to set [scaleEnabled](https://master-api.flutter.dev/flutter/widgets/InteractiveViewer/scaleEnabled.html) to false too.

**Comment by longtimedeveloper** [comment] 2021-11-30 20:27
Looks like `PointerDeviceKind ` may be what we are looking for.  [https://master-api.flutter.dev/flutter/dart-ui/PointerDeviceKind.html](https://master-api.flutter.dev/flutter/dart-ui/PointerDeviceKind.html) to assist in determining the type of device.

I tried using `onInteractionUpdate `but it does not allow me to set the scale, only read it.

If I set `scaleEnabled `to false then the user can't zoom the image, but they need to be able to zoom.

Thank you for all your assistance!

**Comment by justinmc** [comment] 2021-11-30 22:49
Try setting the scale by using [transformationController](https://master-api.flutter.dev/flutter/widgets/InteractiveViewer/transformationController.html).

I tried running a Mac app and logging PointerDeviceKind with a Magic Mouse, the built-in trackpad, and a Logitech mouse with a physical scrollwheel, but they all reported the same value.  I also tried logging just about every other relevant value on PointerSignalEvent and everything was identical as well.  Are you able to see a difference?

**Comment by longtimedeveloper** [comment] 2021-11-30 23:48
I tried working with the `transformationController` but am not able to figure out how to work with it.  I can get it to make changes but they are not very small incremental changes that we would get using the below math.

I don't have a trackpad.  Sorry, this suggestion didn't work.  Seems like it should.  Maybe there is an issue with the listener not correctly reporting the kind of device.

Maybe adding line 900:  `scaleChange = scaleChange  * mouseWheelSensitivity ;` would meet the requirements and not break any existing code.

**Comment by longtimedeveloper** [comment] 2021-12-01 00:02
@justinmc had another idea.  Add a callback on line 900 that would allow the developer to modify the value of `scaleChange`.  You might also want to pass the value of `PointerDeviceKind `as well so that in the future when the Listener starts setting the correct device value, the developer can use this value to determine how to scale.

Essentially, this solution provides an optional way for the developer to inject their logic for determining how little or much the viewer scales on each invokation.

**Comment by justinmc** [comment] 2021-12-06 20:27
Here's a quick naive implementation of manually handling scaling: https://dartpad.dartlang.org/?id=c3689c4a0de844aaa2c8a81e1d776f99

Can you modify that onInteractionUpdate callback to get the behavior that you want?

**Comment by longtimedeveloper** [comment] 2021-12-06 22:26
@justinmc thank you for the information.  Unfortunately, doing this bypasses the below functionality in the InteractiveViewer.  I got bizarre results in both the dartpad example and my app.

1. min and max scaling ability 
2. zooming in or out at the mouse pointer

Honestly, the very best fix for everyone is to either add a public property that your calculation uses or put the calculation in an overridable function that we can do the math and return the delta value that works best for the application.

Thank you very much for your time and consideration, Karl

**Comment by longtimedeveloper** [comment] 2021-12-06 23:04
Hi Justin,

Thank you for the information. Unfortunately, doing this bypasses the below
functionality in the InteractiveViewer. I got bizarre results in both the
dartpad example and my app.

   1. min and max scaling ability
   2. zooming in or out at the mouse pointer

Honestly, the very best fix for everyone is to either add a public property
that your calculation uses or put the calculation in an overridable
function that we can do the math and return the delta value that works best
for the application.

Thank you very much for your time and consideration, Karl

**Comment by justinmc** [comment] 2021-12-07 19:01
Yeah I didn't implement those two features in this example for brevity.

I'm usually hesitant to add any parameters to a widget to avoid making the widget more complex, so I want to make sure we've got the best solution before making a change.

If you could change that scale value, do you plan to just make a `switch` on the platform and return a value that feels best to you on each?  I wonder if there are some values that feel native on each platform, maybe InteractiveViewer should just do this `switch` statement internally rather than requiring each developer to figure out the correct values on their own.

If it is necessary for developers to be able to customize this scale value, it seems to already be possible by using onInteractionUpdate, as shown in my example.  Maybe I could expose how InteractiveViewer does scaling so that it's easier to get the ability to do min/max and centering on the cursor.

**Comment by longtimedeveloper** [comment] 2021-12-07 19:55
@justinmc understand taking your time making a decision.

If given the requested property, in my app I'll provide a slider in the UI for the user to be able to adjust the value, essentially giving them the ability to scale the sensitivity of their mouse wheel changes.  This provides the very best user experience for the user based on their settings.  Remember each user can have their computer mouse vertical scroll settings different.  This is vertical scroll speed setting on **their** system GREATLY impacts the interactive viewer mouse wheel scrolling user experience.

If this property is added with the default value of 1, it will not impact any current for future developers.  This seems like a very simple, non-breaking change with a massive ROI for you, the developers, and the users of our applications.  As I suggested above, adding line 900 `scaleChange = scaleChange * mouseWheelSensitivity ;`  Where `mouseWheelSensitivity` is a double that defaults to 1.

I need to provide a smooth mouse wheel zooming-in and out experience for my users.

The option for developers to obtain this capability by having to re-implement core logic using the `onInteractionUpdate` seems like a lot of extra work and if you made internal changes that could impact developers' custom implementation.  A single optional property is much simpler and much easier for all to maintain over time.

Thank you for your time and consideration!  Best regards, Karl

**Comment by longtimedeveloper** [comment] 2021-12-12 12:59
@justinmc any decision on the request?  Thank you.

**Comment by justinmc** [comment] 2021-12-14 19:19
Sorry, I forgot you mentioned the slider above.

I think I'm on board.  This seems like it will be a common situation for users on desktop, and using onInteractionUpdate is powerful enough but very complicated.

I've written a draft PR, let me know what you think: https://github.com/flutter/flutter/pull/95224

**Comment by longtimedeveloper** [comment] 2021-12-14 22:36
@justinmc  your fix is outstanding!!  Thank you!!!  So looking forward to using this in my game!!  Merry Christmas and a Happy New Year!!

**Closed** 2022-01-07 18:40 UTC
Labels: framework, f: material design, proposal, passed first triage

**Comment by Guthers** [comment] 2022-01-08 04:18
Awesome! Thanks so much completing this!
