### ISSUE TITLE
Website has no max-width

### ISSUE THREAD

**Issue by b-strauss** [flutter/flutter#10084] opened 2017-05-15 09:42 UTC
This is a minor point, but the website has no max-width. On high resolution displays this leads to very long paragraphs.

![page-width](https://cloud.githubusercontent.com/assets/6588177/26051744/660ec7ca-3963-11e7-8a7c-a66ab1c8aebe.jpg)

> Too wide – if a line of text is too long the reader’s eyes will have a hard time focusing on the text. This is because the line length makes it difficult to gauge where the line starts and ends. Furthermore it can be difficult to continue onto the correct line in large blocks of text.

https://baymard.com/blog/line-length-readability

**Comment by sethladd** [comment] 2017-05-15 17:48
Dupe of https://github.com/flutter/flutter/issues/9671 , I believe.

Thanks for the feedback! Let me know if this issue is something different.

**Closed by sethladd** 2017-05-15 17:48 UTC

**Comment by b-strauss** [comment] 2017-05-15 19:03
Yes that's correct, thx!
