### ISSUE TITLE
Can't click through `CarouselView` widget.

### ISSUE THREAD

**Issue by mhmzdev** [flutter/flutter#155199] opened 2024-09-14 08:45 UTC
### Steps to reproduce

1. Create a simple UI with `CarouselView`
2. In `children` widget make sure you have some clickable widget i.e. button or gesture detector
3. Try to tap on the `children` widget, the `onTap` of `CarouselView` will override it and it won't let you make action.

### Expected results

If `onTap` property is not given, it should not effect or override the children's `onTap`

### Actual results

1. `CarouselView` is not letting me tap the children's `onTap`
2. Plus, if I import the `Carousel_Slider` package from `pub.dev` it simply throws error due to duplicate import of widget and doesn't even build the app.

### Code sample

<details open><summary>CarouselView code with a `EventCard`</summary>

```dart
      return CarouselView(
        itemExtent: AppMedia.height,
        controller: appState.carouselController,
        scrollDirection: Axis.vertical,
        itemSnapping: true,
        padding: Space.z,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(0),
        ),
        children: nearbyEvents
            .map(
              (event) => EventCard(
                event: event,
                type: EventCardType.reelView,
              ),
            )
            .toList(),
      );
```

</details>

<details open><summary>`EventCard` has a button with below code</summary>

```dart
               Center(
                    child: AppButton(
                      height: 50,
                      width: 250,
                      radius: AppButtonRadius.capsule,
                      iconToEnd: true,
                      icon: Iconsax.arrow_right_1,
                      label: 'Details',
                      onPressed: () => AppRoutes.eventDetail.push(
                        context,
                        arguments: {'event': event},
                      ),
                    ),
                  ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/e78eee17-4d19-43bf-8d0f-0904a23be2d1

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-PK)
    • Flutter version 3.24.0 on channel stable at /Users/hamza/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (7 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/hamza/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/hamza/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/hamza/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)            
    • iPhone 15 Pro (mobile)          • 2DFED524-E171-445E-B631-828D239B1B43 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by SuicaLondon** [comment] 2024-09-15 00:53
I can reproduce this issue on version 3.24.0
![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-14 at 23 42 44](https://github.com/user-attachments/assets/94372461-5922-485a-89bb-f65db6c2d10a)

That was caused by the the `onTap` method is always set whatever the `widget.onTap ` exists or not. And all children will be covered by `InkWell` widget and it is totally not clickable.
<img width="613" alt="Screenshot 2024-09-14 at 11 43 36 PM" src="https://github.com/user-attachments/assets/a609782a-aa68-4b4c-8707-a9b3818566ca">

It could be fixed by add a new parameter and a guard statement on the InkWell widget. I am a bit not sure if this is the normal behavior of the carousel.
<img width="453" alt="Screenshot 2024-09-15 at 1 07 12 AM" src="https://github.com/user-attachments/assets/278ed8d2-9138-4f28-8155-31dec97d2732">

I suggest to add a new parameter `disabledChildrenInteraction` to provide an optional for developer to customize the clickable area.

```Dart
/// Whether the children tap is disabled.
/// Noted that this will disable the tap event for all children by covering InkWell.
/// Defaults to true.
final bool disabledChildrenInteraction;
```


I have created a [PR](https://github.com/flutter/flutter/pull/155214) for it.

**Comment by mhmzdev** [comment] 2024-09-15 04:37
@SuicaLondon I don't think we need an extra parameter for this, it should work in a way that if `widget.onTap` is given, it should work otherwise shouldn't override any other children's onTap.

**Comment by SuicaLondon** [comment] 2024-09-15 10:10
@mhmzdev You can checked my first commit, I was using onTap at first, but it will break some test case. If we update it with that, it will be a breaking change for everyone. For that reason, it will be better to have another parameter to control its behavior.

**Comment by darshankawar** [comment] 2024-09-16 07:57
@mhmzdev 
I believe this is similar / duplicate of https://github.com/flutter/flutter/issues/154701 which already has an active PR to fix the behavior. Please follow-up in it for further updates.
Closing this in favor of it. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2024-09-16 07:57 UTC
Labels: in triage

**Comment by mhmzdev** [comment] 2024-09-16 08:02
@SuicaLondon you can check the duplicate PR has similar approach.
@darshankawar sure thanks! closing my duplicate PR as well #155218
