### ISSUE TITLE
[Windows] Release version of the app do not work correctly with a powershell "Send-OSNotification" command.

### ISSUE THREAD

**Issue by MaximRyabovol** [flutter/flutter#70926] opened 2020-11-20 08:35 UTC
Simplified example (a default app as a start point):

1. Install a module for powershell by a "powershell Install-Module -Name PoshNotify -Scope CurrentUser -Force" command in terminal.
2. Add the plugin [process_run](https://pub.dev/packages/process_run) in a project.
3. The _incrementCounter method of the deffault app replace to:
```
void _incrementCounter() async {
    var shell = Shell(runInShell: false);
    shell.run('''
powershell Send-OSNotification -Body 'Hello' -Title 'Title'
''');
  }
```
4. build realise version of the app by "flutter build windows"

I created [a ready project](https://github.com/MaximRyabovol/powernotife) for your convenience there everything done already. Just don't forget install the module for powershell to which I have referred.

**Expected results:**
Notifications pushed every time then floating action button was pressed.

**Actual results:**
The app running **in debug mode**: woking as expected.
A **release version** of the app: after FAB was pressed a terminal showing for a moment, a notification shows, but subsequent pressing don't push a notification again.

Additionaly I have some logs from windows event viewer:
**from application:**
_Error:_
Faulting application name: powernotif.exe, version: 1.0.0.0, time stamp: 0x5fb7588f
Faulting module name: flutter_windows.dll, version: 0.0.0.0, time stamp: 0x5fa9c2e5
Exception code: 0xc0000005
Fault offset: 0x000000000000705e
Faulting process id: 0x3170
Faulting application start time: 0x01d6bf0d53e0e488
Faulting application path: C:\somefolder1\somefolder2\powernotif\build\windows\runner\Release\powernotif.exe
Faulting module path: C:\somefolder1\somefolder2\powernotif\build\windows\runner\Release\flutter_windows.dll
Report Id: 97ed5942-b79f-4134-96bd-67eb63b4a7a6
Faulting package full name: 
Faulting package-relative application ID: 

_Information:_
Fault bucket 1758431171041770082, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: powernotif.exe
P2: 1.0.0.0
P3: 5fb7588f
P4: flutter_windows.dll
P5: 0.0.0.0
P6: 5fa9c2e5
P7: c0000005
P8: 000000000000705e
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6DDF.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6E4E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6E6E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6E6C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6E9C.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_powernotif.exe_54587ab5fec0c6a1f4f8c2e1b7ed40cb74c0ed4e_61912671_081af18a-b89c-4681-bc72-b234739779e0

Analysis symbol: 
Rechecking for solution: 0
Report Id: 97ed5942-b79f-4134-96bd-67eb63b4a7a6
Report Status: 268435456
Hashed bucket: b71047776d5c5436b86733d55feb3a62
Cab Guid: 0

**from system:**
(I don't know why there not english text)
The для конкретного приложения permission settings do not grant Локально Активация permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user user\username SID (some_sid) from address LocalHost (с использованием LRPC) running in the application container Недоступно SID (Недоступно). This security permission can be modified using the Component Services administrative tool.

I tried to build the app by MS visual studio and MS visual studio code. The result the same.

I think it is something to do with APPID. I packed the app in installer, but it did not bring any results. Maybe there is some additional opportunity to add APPID to the system?

**Comment by sidrao2006** [comment] 2020-11-20 10:25
Hey @MaximRyabovol ,
This issue tracker is used for tracking bugs and feature requests for the flutter framework, engine and the flutter tool.
Since this is an error/bug with a 3rd party package, please close this issue

Thanks

**Comment by pedromassangocode** [comment] 2020-11-20 10:35
Hi @MaximRyabovol 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/tekartik/process_run.dart).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-20 10:35 UTC
