### ISSUE TITLE
Memory leak when using Navigator pages api

### ISSUE THREAD

**Issue by tamas-p** [flutter/flutter#126995] opened 2023-05-17 08:34 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Execute widget test provided in the code sample section.

While I was working on a layer on top of Navigator 2.0 I created a stress test (in the form of a widget test) for my new router delegate class. It showed serious memory leak since Flutter version `3.7.0`. Last OK version was `3.3.10`.
The provided widget test in this report is the smallest possible version of such stress test I could come up with.

### Expected results

Test passes (RSS increase - over the 100 iterations in the test -  is less than 100 MB).

Side note: Even when using 3.3.10 and test passes, there is continuous a RSS usage increase (but two magnitude smaller than with Flutter versions >= 3.7.0). 

### Actual results

Since Flutter version 3.7.0 test fails (RSS increase is > `3 GB`).

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class TestApp extends StatelessWidget {
  const TestApp({required this.routerDelegate, super.key});
  final TestRouterDelegate routerDelegate;
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(routerDelegate: routerDelegate);
  }
}

class TestRouterDelegate extends RouterDelegate<bool> with ChangeNotifier {
  bool ui = true;
  final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    ui = !ui;
    return Navigator(
      key: _navigatorKey,
      pages: [MaterialPage<void>(child: Text('$ui'), key: ValueKey(ui))],
      onPopPage: (route, dynamic result) => true,
    );
  }

  @override
  Future<void> setNewRoutePath(bool _) => throw UnimplementedError();
  @override
  Future<bool> popRoute() => throw UnimplementedError();
}

void main() {
  testWidgets('Navigator memory leak test.', (WidgetTester tester) async {
    final routerDelegate = TestRouterDelegate();
    await tester.pumpWidget(TestApp(routerDelegate: routerDelegate));

    final beforeRSS = ProcessInfo.currentRss;
    for (var i = 0; i < 100; i++) {
      routerDelegate.notifyListeners();
      await tester.pumpAndSettle();
    }
    final afterRSS = ProcessInfo.currentRss;
    expect(afterRSS - beforeRSS, lessThan(100 * 1024 * 1024));
  });
}

```

</details>

### Logs

<details><summary>Logs</summary>

```console
Resolving dependencies...
> async 2.11.0 (was 2.9.0)
> boolean_selector 2.1.1 (was 2.1.0)
> characters 1.3.0 (was 1.2.1)
> collection 1.17.1 (was 1.16.0) (1.17.2 available)
+ js 0.6.7
  lints 2.0.1 (2.1.0 available)
> matcher 0.12.15 (was 0.12.12) (0.12.16 available)
> material_color_utilities 0.2.0 (was 0.1.5) (0.5.0 available)
> meta 1.9.1 (was 1.8.0)
> path 1.8.3 (was 1.8.2)
> source_span 1.9.1 (was 1.9.0) (1.10.0 available)
> stack_trace 1.11.0 (was 1.10.0)
> stream_channel 2.1.1 (was 2.1.0)
> string_scanner 1.2.0 (was 1.1.1)
> test_api 0.5.1 (was 0.4.12) (0.6.0 available)
> vector_math 2.1.4 (was 2.1.2)
Changed 15 dependencies!
00:00 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:01 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:02 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:03 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:04 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:05 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:06 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:07 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:08 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:09 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:10 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:10 +0: Navigator memory leak test.                                                                    00:11 +0: Navigator memory leak test.                                                                    00:12 +0: Navigator memory leak test.                                                                    00:13 +0: Navigator memory leak test.                                                                    00:13 +0: Navigator memory leak test.                                                                                                                                                                  
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: a value less than <104857600>
  Actual: <3473719296>
   Which: is not a value less than <104857600>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart:46:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart line 46
The test description was:
  Navigator memory leak test.
════════════════════════════════════════════════════════════════════════════════════════════════════
00:13 +0 -1: Navigator memory leak test. [E]                                                                                                                                                           
  Test failed. See exception logs above.
  The test description was: Navigator memory leak test.
  

To run this test again: /home/tamas/fvm/versions/3.10.0/bin/cache/dart-sdk/bin/dart test /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart -p vm --plain-name 'Navigator memory leak test.'
00:13 +0 -1: Some tests failed.         
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on Ubuntu 22.04.2 LTS 5.19.0-41-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] Android Studio
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```
```console
$ fvm use 3.3.10 --force
Project now uses Flutter [3.3.10]
$ f doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.04.2 LTS 5.19.0-41-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] Android Studio
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```
</details>

**Comment by huycozy** [comment] 2023-05-17 11:46
Hi @tamas-p 
Thanks for the report, but this issue seems to be fixed on the master channel since I see the test is passed there (whilst it's failed on stable channel).

Please retry on master and confirm this:

```
flutter channel master
flutter upgrade
```

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (35 hours ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-6.0.pre.85, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-6.0.pre.85 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2919572fb3 (71 minutes ago), 2023-05-15 19:01:28 -0700
    • Engine revision c4d4b40c65
    • Dart version 3.1.0 (build 3.1.0-113.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by tamas-p** [comment] 2023-05-17 18:03
> Thanks for the report, but this issue seems to be fixed on the master channel since I see the test is passed there (whilst it's failed on stable channel).

Great news. Look forward to seeing the fix in the stable channel. I am ok to close as the main problem (3 GB RSS increase over 100 iterations in the widget test) is fixed on the master.

However, there are two things to consider investigating:
- There is still a constant RSS increase and it is larger for master:
  - master: `147 MB` RSS increase during test run
  - 3.3.10: 88 MB RSS increase during test run
- The test runs significantly slower on the master compared to 3.3.10: 
  - master:  `162 seconds`
  - 3.3.10: 36 seconds

Numbers above are from test run where I set `10K` iterations to see the differences more clearly.

**Comment by huycozy** [comment] 2023-05-18 04:23
Thanks for the update. Can you please provide sample code for those cases above?

**Comment by tamas-p** [comment] 2023-05-18 07:07
Sure,

This test (1K iterations) passes on 3.3.10 and fails on master:

<details><summary>Code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class TestApp extends StatelessWidget {
  const TestApp({required this.routerDelegate, super.key});
  final TestRouterDelegate routerDelegate;
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(routerDelegate: routerDelegate);
  }
}

class TestRouterDelegate extends RouterDelegate<bool> with ChangeNotifier {
  bool ui = true;
  final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    ui = !ui;
    return Navigator(
      key: _navigatorKey,
      pages: [MaterialPage<void>(child: Text('$ui'), key: ValueKey(ui))],
      onPopPage: (route, dynamic result) => true,
    );
  }

  @override
  Future<void> setNewRoutePath(bool _) => throw UnimplementedError();
  @override
  Future<bool> popRoute() => throw UnimplementedError();
}

void main() {
  testWidgets('Navigator memory leak test.', (WidgetTester tester) async {
    final routerDelegate = TestRouterDelegate();
    await tester.pumpWidget(TestApp(routerDelegate: routerDelegate));

    final beforeRSS = ProcessInfo.currentRss;
    final startTime = DateTime.now().millisecondsSinceEpoch;
    for (var i = 0; i < 1000; i++) {
      // print('$i - mem: ${ProcessInfo.currentRss / 1024 / 1024} MB');
      routerDelegate.notifyListeners();
      await tester.pumpAndSettle();
    }
    final finishTime = DateTime.now().millisecondsSinceEpoch;
    final afterRSS = ProcessInfo.currentRss;

    final testDuration = (finishTime - startTime) / 1000;
    final testRssIncrease = (afterRSS - beforeRSS) / 1024 / 1024;

    print('Duration: ${testDuration.toStringAsFixed(2)} sec, '
        'RSS increase: ${testRssIncrease.toStringAsFixed(2)} MB');

    expect(testDuration, lessThan(10));
    expect(testRssIncrease, lessThan(50 * 1024 * 1024));
  });
}

```

</details>

`3.3.10 results:` Duration: 5.28 sec, RSS increase: 32.33 MB

<details><summary>3.3.10 logs</summary>

```console
$ f --version
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (5 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
$ f test test/navigator_memory_leak_test.dart 
00:00 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:01 +0: loading /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart       00:01 +0: Navigator memory leak test.
00:02 +0: Navigator memory leak test.
00:03 +0: Navigator memory leak test.
00:04 +0: Navigator memory leak test.
00:05 +0: Navigator memory leak test.
00:06 +0: Navigator memory leak test.
00:07 +0: Navigator memory leak test.
00:07 +0: Navigator memory leak test.                                                                                                                                                                 
Duration: 5.28 sec, RSS increase: 32.33 MB
00:07 +1: Navigator memory leak test.
00:07 +1: All tests passed! 
```
</details>

`master results:` Duration: 19.45 sec, RSS increase: 56.62 MB

<details><summary>master logs</summary>

```console
$ flutter --version
Flutter 3.11.0-6.0.pre.134 • channel master • https://github.com/flutter/flutter.git
Framework • revision f31dae2a80 (7 hours ago) • 2023-05-17 17:18:51 -0700
Engine • revision d970370779
Tools • Dart 3.1.0 (build 3.1.0-118.0.dev) • DevTools 2.23.1
$ flutter test test/navigator_memory_leak_test.dart 
00:21 +0: Navigator memory leak test.                                                                   
Duration: 19.45 sec, RSS increase: 56.62 MB
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: a value less than <10>
  Actual: <19.454>
   Which: is not a value less than <10>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart:56:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart line 56
The test description was:
  Navigator memory leak test.
════════════════════════════════════════════════════════════════════════════════════════════════════
00:21 +0 -1: Navigator memory leak test. [E]                                                            
  Test failed. See exception logs above.
  The test description was: Navigator memory leak test.
  

To run this test again: /home/tamas/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart test /home/tamas/projects/flutter/navigator_leak/test/navigator_memory_leak_test.dart -p vm --plain-name 'Navigator memory leak test.'
00:21 +0 -1: Some tests failed.  
```
</details>

**Comment by huycozy** [comment] 2023-05-18 07:37
Thanks! I add test results from my end as below:

- `master` result: Duration: 21.50 sec, RSS increase: 89.83 MB (Test Failed ❌)
- `stable` result: Duration: 37.72 sec, RSS increase: 4198.52 MB (Test Failed ❌)
- `3.7.12` result: Duration: 43.26 sec, RSS increase: 4410.01 MB (Test Failed ❌)
- `3.3.10` result: Duration: 9.29 sec, RSS increase: 46.96 MB (Test passed ✅)

✅: No Issue ❌: Issue reproduced

Labeling the issue for further investigation.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (26 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-6.0.pre.134, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-6.0.pre.134 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f31dae2a80 (3 hours ago), 2023-05-17 17:18:51 -0700
    • Engine revision d970370779
    • Dart version 3.1.0 (build 3.1.0-118.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by goderbauer** [comment] 2023-05-30 22:29
cc @chunhtai

**Comment by chunhtai** [comment] 2023-06-06 20:56
I can't really find any leak in the navigator code. I have been using Object creation tracking with the leak_tracker package. This is the code I am using.

<details>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:leak_tracker/leak_tracker.dart';

class TestApp extends StatelessWidget {
  const TestApp({required this.routerDelegate, super.key});
  final TestRouterDelegate routerDelegate;
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(routerDelegate: routerDelegate);
  }
}

class TestRouterDelegate extends RouterDelegate<bool> with ChangeNotifier {
  bool ui = true;
  final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    ui = !ui;
    return Navigator(
      key: _navigatorKey,
      pages: [MaterialPage<void>(child: Text('$ui'), key: ValueKey(ui))],
      onPopPage: (route, dynamic result) => true,
    );
  }

  @override
  Future<void> setNewRoutePath(bool _) => throw UnimplementedError();
  @override
  Future<bool> popRoute() => throw UnimplementedError();
}
void flutterEventToLeakTracker(ObjectEvent event) {
  return dispatchObjectEvent(event.toMap());
}
void main() {
  testWidgets('Navigator memory leak test.', (WidgetTester tester) async {
    final routerDelegate = TestRouterDelegate();
    await tester.pumpWidget(TestApp(routerDelegate: routerDelegate));

    Future<void> asyncCodeRunner(DartAsyncCallback action) async => tester.runAsync(action);
    MemoryAllocations.instance.addListener(flutterEventToLeakTracker);
    Leaks leaks = await withLeakTracking(
      () async {
        for (var i = 0; i < 1000; i++) {
          // print('$i - mem: ${ProcessInfo.currentRss / 1024 / 1024} MB');
          routerDelegate.notifyListeners();
          await tester.pumpAndSettle();
        }
      },
      asyncCodeRunner: asyncCodeRunner,
      stackTraceCollectionConfig: const LeakTrackingTestConfig().stackTraceCollectionConfig,
      shouldThrowOnLeaks: false,
    );
    MemoryAllocations.instance.removeListener(flutterEventToLeakTracker);
    print('leaks ${leaks.toJson()}');

  });
}
```

</details>

I also need to raise _maxAllowedNotRegisterdObjects up so that it can work with existing running app

It doesn't record any not disposed item. Only 3 not GC item.
```
{
  notDisposed: [
    
  ],
  notGCed: [
    {
      type: ValueNotifier<_OverlayEntryWidgetState?>,
      context: null,
      code: 14471490,
      tracked: package: flutter/foundation.dart/ValueNotifier<dynamic>
    },
    {
      type: ValueNotifier<_OverlayEntryWidgetState?>,
      context: null,
      code: 271186787,
      tracked: package: flutter/foundation.dart/ValueNotifier<dynamic>
    },
    {
      type: ValueNotifier<String?>,
      context: null,
      code: 44316636,
      tracked: package: flutter/foundation.dart/ValueNotifier<dynamic>
    }
  ],
  gcedLate: [
    
  ]
}
```

@polina-c since you may be more familiar with this, I think this should be normal?

The increase in memory usage may coming from some other places

**Comment by chunhtai** [comment] 2023-06-06 21:17
ah nvm it looks like the leak tracking is not comprehensive, and is not a accurate representation of the actual memory usage.

**Comment by chunhtai** [comment] 2023-06-06 22:26
After some more test, I don't think there is any memory leak, the increase in RSS is probably memory waiting to be GC.

I have been running the code in a real app and use devtool to profile the memory usage.

this is the code I am using
<details>

```dart
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
void main() => runApp(TestApp(routerDelegate: TestRouterDelegate()));

class TestApp extends StatelessWidget {
  const TestApp({required this.routerDelegate, super.key});
  final TestRouterDelegate routerDelegate;
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(routerDelegate: routerDelegate);
  }
}

class TestRouterDelegate extends RouterDelegate<bool> with ChangeNotifier {
  bool ui = true;
  final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();
  @override
  Widget build(BuildContext context) {
    ui = !ui;
    return Navigator(
      key: _navigatorKey,
      pages: [MaterialPage<void>(child: ElevatedButton(child: Text('$ui'), onPressed: (){
        int count = 100;
        Timer.periodic(Duration(milliseconds: 50), (timer) {
          count -= 1;
          if (count == 0) {
            timer.cancel();
          }
          notifyListeners();
        });
      }), key: ValueKey(ui))],
      onPopPage: (route, dynamic result) => true,
    );
  }

  @override
  Future<void> setNewRoutePath(bool _) => throw UnimplementedError();
  @override
  Future<bool> popRoute() => throw UnimplementedError();
}
```

</details>

I am running on mac and the initial memory is about 55MB. When I click the button(update 100 times) the memory would increase to ~98mb and will drop back to ~69mb after force GC. I then keep trying click the button multiple times, and the memory always drop back to ~69mb after force GC.

I think everything is normal here. I am closing this issue, feel free to reopen if you are still seeing memory leak

**Closed by chunhtai** 2023-06-06 22:26 UTC
Labels: severe: regression, framework, f: routes, perf: memory, has reproducible steps, P4, found in release: 3.10, found in release: 3.11

**Comment by tamas-p** [comment] 2023-06-08 10:29
>the increase in RSS is probably memory waiting to be GC.

Thanks @chunhtai, I agree with your statement - but I had to learn a bit about flutter/dart garbage collector, why the garbage collection effect was not visible during my stress tests:

First I run the test to 1M iterations as I never seen the sawtooth graph of RSS during the tests I ran. This is what I got:

![1M](https://github.com/flutter/flutter/assets/10595775/9cfbec8a-95ad-4d3d-97a6-44dceeed0d3b)

and indeed, as I saw before, there is no gc cleaning ups (no sawtooth pattern in how RSS changes) during the test. Then I went searching for some flutter/dart material on gc for a novice on the subject. I read Matt Sullivan's article [Flutter: Don’t Fear the Garbage Collector](https://medium.com/flutter/flutter-dont-fear-the-garbage-collector-d69b3ff1ca30) and it says:

*"To minimize the effects of garbage collection on app and UI performance, the garbage collector provides hooks to the Flutter engine that alerts it when the engine detects that the app is idle and there’s no user interaction. This gives the garbage collector windows of opportunity to run its collection phases without impacting performance."*

There we go... My stress test was stressing so much dart had no time to cleanup. 

I modified the test to add 1 sec rest at every 10K iterations:

```dart
 if (i != 0 && i % 10000 == 0) {
    print('Have some rest...');
    await tester.runAsync(() async {
      await Future<void>.delayed(const Duration(seconds: 1));
    });
    print('Continue.');
}
```

> **_NOTE:_**  When running the test from command line I had to use the "--timeout none" argument to avoid test timing out.

With these rests this is the graphs I got:

![1M_with_rests](https://github.com/flutter/flutter/assets/10595775/5b494ace-292f-4620-8791-9edf94b9913e)

much better. The sawtooths are there, gc is effective. All good about the RSS part of the story (for backend dart work I need to still learn more on dart gc, if and how dart can be used to long running algorithmic processing - when there's no rest).

However there is one thing that I still bothering: As you can see on the graphs, 3.3.10 (purple) is much faster done with the test of 1M iterations than the master (green) version: 3816.57 vs 18774.67 seconds. It seems the old 3.3.10 is able to do the same job `~5 times faster`.

**Comment by chunhtai** [comment] 2023-06-08 16:12
I can't tell what may have caused the difference between the gc frequency. I am also not sure if this is actually an issue or not. Since this is not related to navigator leak any more, can you file a new issue for this?

**Comment by tamas-p** [comment] 2023-06-08 16:42
gc happens at every 10K iterations in the test, so the gc frequency is higher for 3.3.10 only because 10K iterations takes ~5 times smaller amount of time compared to master. I will do a profiling to see where time spent and might file a new issue as you recommended.

**Comment by polina-c** [comment] 2023-06-09 00:51
Leak tracker reports notGCed leak if an object is disposed and then is not GCed after full GC cycle.
Starting version 7.0.2, if configured in LeakDiagnosticConfig, leak tracker can give you retaining path that holds the object from garbage collection.

Let me know if it helps.
