### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by MaxAndroid33** [flutter/flutter#108180] opened 2022-07-22 18:27 UTC
## Co

**Comment by darshankawar** [comment] 2022-07-25 05:31
Closing this as self-duplicate of https://github.com/flutter/flutter/issues/108181.
Please don't create multiple issues for same reason.

**Closed by darshankawar** 2022-07-25 05:31 UTC
Labels: in triage
