### ISSUE TITLE
pigeon: implement primitive enum return values and arguments

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#87307] opened 2021-07-29 23:14 UTC
example:
```dart
enum Foo {
  one,
  two,
}

@HostApi
abstract class Api {
  Foo lookup(int identifier);
  void set(int identifier, Foo foo);
}
```

**Comment by bparrishMines** [comment] 2021-12-28 22:26
For Dart and Android, support for this feature is pretty straightforward. It can be solved by just updating the codec with enum indexes:

**Dart:**
```dart
enum Fruit {
  apple,
  banana,
}

class ACodec extends StandardMessageCodec {
  const ACodec();
  
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Fruit) {
      buffer.putUint8(128);
      writeValue(buffer, value.index);
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return Fruit.values[readValue(buffer)! as int];
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}
```

**Java:**
```java
public enum Fruit {
  apple(0),
  banana(1);

  private int index;
  Fruit(final int index) {
    this.index = index;
  }
}

private static class ACodec extends StandardMessageCodec {
  public static final ACodec INSTANCE = new ACodec();
  private ACodec() {}
  @Override
  protected Object readValueOfType(byte type, ByteBuffer buffer) {
    switch (type) {
      case (byte)128:
        return Fruit.values()[(int) readValue(buffer)];
      default:        
        return super.readValueOfType(type, buffer);
      
    }
  }
  @Override
  protected void writeValue(ByteArrayOutputStream stream, Object value)     {
    if (value instanceof Fruit) {
      stream.write(128);
      writeValue(stream, ((Fruit) value).index);
    } else {
      super.writeValue(stream, value);
    }
  }
}
```

But, the codec for *Objective-C* doesn't handle *Objective-C* type enums well. e.g:

```objc
typedef NS_ENUM(NSUInteger, Fruit) {
  FruitApple = 0,
  FruitBanana = 1,
};
```

`FlutterStandardReader.readValueOfType` and `FlutterStandardWriter.writeValue` require an object, not a primitive, to be returned or passed respectively. So, the solution won't be as straightforward as other languages. A couple of solutions I came up with are:

1. The Objective-C generation could create Enum like classes with static variables. e.g.

```objc
@interface Fruit : NSObject
@property(readonly) NSUInteger index;
- (instancetype)init NS_UNAVAILABLE;
+ (Fruit *)apple;
+ (Fruit *)banana;
@end
```

2. Methods for `HostApi`s/`FlutterApi`s could take and/or return enum wrappers. e.g.

```objc
typedef NS_ENUM(NSUInteger, Fruit) {
  FruitApple = 0,
  FruitBanana = 1,
};

@interface FruitEnum : NSObject
@property(readonly) Fruit value;
- (instancetype)initWithValue:(Fruit)value;
@end

@protocol AClass
- (void)aMethod:(NSArray<FruitEnum *> *)fruits error:(FlutterError *_Nullable *_Nonnull)error;
@end
```

**Comment by TheBuggedYRN** [comment] 2022-10-11 17:28
After merging flutter/packages#1871:
1. `Enum` argument works ✅:

    ```dart
    void bar(Foo foo);
    ```
1. `List<Enum>` argument does not work ❌:

    ```dart
    void bar(List<Foo> foo);
    ```
    
 @gaaclarke is this intended?

**Comment by hawkkiller** [comment] 2022-12-26 21:41
Any updates about @FlutterApi ?

**Comment by mchouchane-enedis** [comment] 2023-04-11 06:56
Any update for about this?

**Comment by timukasr** [comment] 2023-07-06 12:40
Confused how #130064 is duplicate of this. From my (user) point of view, #87307 is already implemented, but it is not working correctly.

If this feature is not supported, then pigeon generator should give error and not generate code that crashes in production.

**Closed** 2023-08-28 14:25 UTC
Labels: package, c: proposal, team-ecosystem, p: pigeon, P1, triaged-ecosystem
