### ISSUE TITLE
admob banner issue

### ISSUE THREAD

**Issue by superciccio** [flutter/flutter#21907] opened 2018-09-15 12:50 UTC
## Steps to Reproduce

Implemented an adbanner following the example from the plugin firebase_admob.

I placed the banner in the home and is showing but I when go to screen (trough another route) then banner is still there the dispose is not called...

If I  call the dispose of the banner by myself then the banned will not be recreated (it disappear from the home )

see the screenshot attached
![screenshot_1537014855](https://user-images.githubusercontent.com/4390182/45586343-6cfbc780-b8ed-11e8-9936-52e1f8b6fc5e.png)
![screenshot_1537014918](https://user-images.githubusercontent.com/4390182/45586344-6cfbc780-b8ed-11e8-9e25-1eeb4048c95c.png)

## Logs

```
+1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:56022/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+7081 ms] W/DynamiteModule(31028): Local module descriptor class for com.google.firebase.auth not found.
[        ] W/BiChannelGoogleApi(31028): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@61e63bb
[        ] W/DynamiteModule(31028): Local module descriptor class for com.google.firebase.auth not found.
[  +99 ms] D/        (31028): HostConnection::get() New Host Connection established 0x9e018b80, tid 31065
[   +9 ms] D/EGL_emulation(31028): eglMakeCurrent: 0x9c641a20: ver 3 0 (tinfo 0x9e003b70)
[  +22 ms] I/FirebaseAuth(31028): [FirebaseAuth:] Loading module via FirebaseOptions.
[        ] I/FirebaseAuth(31028): [FirebaseAuth:] Preparing to create service connection to gms implementation
[ +607 ms] W/Firestore(31028): (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
[        ] W/Firestore(31028): To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
[        ] W/Firestore(31028): 
[        ] W/Firestore(31028): FirebaseFirestore firestore = FirebaseFirestore.getInstance();
[        ] W/Firestore(31028): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
[        ] W/Firestore(31028):     .setTimestampsInSnapshotsEnabled(true)
[        ] W/Firestore(31028):     .build();
[        ] W/Firestore(31028): firestore.setFirestoreSettings(settings);
[        ] W/Firestore(31028): 
[        ] W/Firestore(31028): With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
[        ] W/Firestore(31028): 
[        ] W/Firestore(31028): // Old:
[        ] W/Firestore(31028): java.util.Date date = snapshot.getDate("created_at");
[        ] W/Firestore(31028): // New:
[        ] W/Firestore(31028): Timestamp timestamp = snapshot.getTimestamp("created_at");
[        ] W/Firestore(31028): java.util.Date date = timestamp.toDate();
[        ] W/Firestore(31028): 
[        ] W/Firestore(31028): Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
[  +32 ms] D/DynamitePackage(31028): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
[  +16 ms] D/DynamitePackage(31028): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
[  +38 ms] V/NativeCrypto(31028): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
[  +17 ms] I/flutter (31028): initial link: /home
[  +30 ms] I/Ads     (31028): Starting ad request.
[        ] I/Ads     (31028): SDK version: afma-sdk-a-v13280022.12451000.1
[        ] I/Ads     (31028): This request is sent from a test device.
[  +48 ms] I/WebViewFactory(31028): Loading com.android.chrome version 69.0.3497.91 (code 349709112)
[ +614 ms] I/zygote  (31028): Do partial code cache collection, code=60KB, data=44KB
[  +11 ms] I/flutter (31028): null
[        ] I/flutter (31028): Push Messaging token: dv09GhZosM0:APA91bGXWonCG-nwe1z_rWyT3dripCoGx739INHQ77WGzVrghQ7x5vE8DtYCF8Ef3Yay2zkHiKvFVhixXkplFFqpHuyl9Qs3-4Qe-xa4qa3ICWeEKP4ZnrGr31suokvEEpKeLaoVjZP_
[  +29 ms] I/zygote  (31028): After code cache collection, code=60KB, data=44KB
[        ] I/zygote  (31028): Increasing code cache capacity to 256KB
[ +128 ms] I/ProviderInstaller(31028): Installed default security provider GmsCore_OpenSSL
[ +202 ms] I/zygote  (31028): Rejecting re-init on previously-failed class java.lang.Class<uJ>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/TracingController;
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:128)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:402)
[        ] I/zygote  (31028):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
[        ] I/zygote  (31028):   at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
[        ] I/zygote  (31028):   at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.a(android.content.Context) (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):5)
[        ] I/zygote  (31028):   at java.lang.Object com.google.android.gms.ads.internal.f.call() (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):3)
[        ] I/zygote  (31028):   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
[        ] I/zygote  (31028):   at void java.lang.Thread.run() (Thread.java:764)
[        ] I/zygote  (31028): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.TracingController" on path: DexPathList[[zip file "/data/app/com.android.chrome-Sg1gEdb0IQnjRdom89kZaw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-Sg1gEdb0IQnjRdom89kZaw==/lib/x86, /data/app/com.android.chrome-Sg1gEdb0IQnjRdom89kZaw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
[        ] I/zygote  (31028):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:128)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:402)
[        ] I/zygote  (31028):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
[        ] I/zygote  (31028):   at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
[        ] I/zygote  (31028):   at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.a(android.content.Context) (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):5)
[        ] I/zygote  (31028):   at java.lang.Object com.google.android.gms.ads.internal.f.call() (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):3)
[        ] I/zygote  (31028):   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
[        ] I/zygote  (31028):   at void java.lang.Thread.run() (Thread.java:764)
[        ] I/zygote  (31028): 
[        ] I/zygote  (31028): Rejecting re-init on previously-failed class java.lang.Class<uJ>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/TracingController;
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:128)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:402)
[        ] I/zygote  (31028):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
[        ] I/zygote  (31028):   at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
[        ] I/zygote  (31028):   at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.a(android.content.Context) (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):5)
[        ] I/zygote  (31028):   at java.lang.Object com.google.android.gms.ads.internal.f.call() (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):3)
[        ] I/zygote  (31028):   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
[        ] I/zygote  (31028):   at void java.lang.Thread.run() (Thread.java:764)
[        ] I/zygote  (31028): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.TracingController" on path: DexPathList[[zip file "/data/app/com.android.chrome-Sg1gEdb0IQnjRdom89kZaw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-Sg1gEdb0IQnjRdom89kZaw==/lib/x86, /data/app/com.android.chrome-Sg1gEdb0IQnjRdom89kZaw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
[        ] I/zygote  (31028):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:128)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:402)
[        ] I/zygote  (31028):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
[        ] I/zygote  (31028):   at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
[        ] I/zygote  (31028):   at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.a(android.content.Context) (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):5)
[        ] I/zygote  (31028):   at java.lang.Object com.google.android.gms.ads.internal.f.call() (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):3)
[        ] I/zygote  (31028):   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
[        ] I/zygote  (31028):   at void java.lang.Thread.run() (Thread.java:764)
[        ] I/zygote  (31028): 
[        ] I/zygote  (31028): Rejecting re-init on previously-failed class java.lang.Class<uJ>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/TracingController;
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:128)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:402)
[        ] I/zygote  (31028):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
[        ] I/zygote  (31028):   at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
[        ] I/zygote  (31028):   at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.a(android.content.Context) (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):5)
[        ] I/zygote  (31028):   at java.lang.Object com.google.android.gms.ads.internal.f.call() (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):3)
[        ] I/zygote  (31028):   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
[        ] I/zygote  (31028):   at void java.lang.Thread.run() (Thread.java:764)
[        ] I/zygote  (31028): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.TracingController" on path: DexPathList[[zip file "/data/app/com.android.chrome-Sg1gEdb0IQnjRdom89kZaw==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-Sg1gEdb0IQnjRdom89kZaw==/lib/x86, /data/app/com.android.chrome-Sg1gEdb0IQnjRdom89kZaw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
[        ] I/zygote  (31028):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
[        ] I/zygote  (31028):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:128)
[        ] I/zygote  (31028):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:402)
[        ] I/zygote  (31028):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
[        ] I/zygote  (31028):   at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
[        ] I/zygote  (31028):   at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.a(android.content.Context) (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):5)
[        ] I/zygote  (31028):   at java.lang.Object com.google.android.gms.ads.internal.f.call() (:com.google.android.gms.dynamite_adsdynamite@13280052@13.2.80 (040700-211705629):3)
[        ] I/zygote  (31028):   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
[        ] I/zygote  (31028):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
[        ] I/zygote  (31028):   at void java.lang.Thread.run() (Thread.java:764)
[        ] I/zygote  (31028): 
[ +113 ms] I/cr_LibraryLoader(31028): Time to load native libraries: 64 ms (timestamps 4666-4730)
[  +52 ms] I/chromium(31028): [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
[        ] I/cr_LibraryLoader(31028): Expected native library version number "69.0.3497.91", actual native library version number "69.0.3497.91"
[  +21 ms] E/cr_VariationsUtils(31028): Failed reading seed file "/data/user/0/as.ab.myphysio/app_webview/variations_seed_new": /data/user/0/as.ab.myphysio/app_webview/variations_seed_new (No such file or directory)
[ +226 ms] D/FirebaseAuth(31028): Notifying id token listeners about user ( ihZA6pkMUSOoOVk0hb3B65CI2yC2 ).
[        ] D/FirebaseApp(31028): Notifying auth state listeners.
[        ] D/FirebaseApp(31028): Notified 1 auth state listeners.
[ +204 ms] I/zygote  (31028): Background concurrent copying GC freed 43189(2MB) AllocSpace objects, 17(528KB) LOS objects, 49% free, 2MB/5MB, paused 686us total 104.893ms
[ +234 ms] W/cr_ChildProcLH(31028): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
[   +9 ms] I/cr_BrowserStartup(31028): Initializing chromium process, singleProcess=false
[   +4 ms] W/ResourceType(31028): Failure getting entry for 0x7f1204b0 (t=17 e=1200) (error -2147483647)
[  +30 ms] I/chromium(31028): [INFO:aw_field_trial_creator.cc(54)] First-WebView-Experiment not found
[ +319 ms] W/cr_media(31028): Requires BLUETOOTH permission
[        ] D/        (31028): HostConnection::get() New Host Connection established 0x6efd6c80, tid 31183
[        ] D/EGL_emulation(31028): eglCreateContext: 0x6efd2420: maj 3 min 0 rcv 3
[        ] D/EGL_emulation(31028): eglMakeCurrent: 0x6efd2420: ver 3 0 (tinfo 0x6efb7dc0)
[        ] W/cr_CrashFileManager(31028): /data/user/0/as.ab.myphysio/cache/WebView/Crash Reports does not exist or is not a directory
[  +43 ms] I/VideoCapabilities(31028): Unsupported profile 4 for video/mp4v-es
[   +5 ms] W/cr_MediaCodecUtil(31028): HW encoder for video/avc is not available on this device.
[   +6 ms] D/EGL_emulation(31028): eglCreateContext: 0x6fd10040: maj 3 min 0 rcv 3
[   +1 ms] D/EGL_emulation(31028): eglMakeCurrent: 0x6fd10040: ver 3 0 (tinfo 0x6efb7dc0)
[ +415 ms] I/Ads     (31028): Scheduling ad refresh 70000 milliseconds from now.
[  +21 ms] I/DynamiteModule(31028): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:310
[        ] I/DynamiteModule(31028): Selected remote version of com.google.android.gms.ads.dynamite, version >= 310
[  +92 ms] I/flutter (31028): BannerAd event MobileAdEvent.loaded
[ +203 ms] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5
[ +110 ms] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5
[ +254 ms] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5
[  +72 ms] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5
[        ] I/chromium(31028): [INFO:CONSOLE(0)] "Document was loaded from Application Cache with manifest https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.appcache", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
[        ] I/chromium(31028): [INFO:CONSOLE(0)] "Application Cache Checking event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
[  +55 ms] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5
[  +50 ms] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5
[        ] I/zygote  (31028): Do full code cache collection, code=122KB, data=93KB
[        ] I/zygote  (31028): After code cache collection, code=114KB, data=66KB
[  +60 ms] I/chromium(31028): [INFO:CONSOLE(0)] "Application Cache NoUpdate event", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40-loader.html (0)
[  +34 ms] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5
[+5203 ms] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5
[ +120 ms] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5
[+2378 ms] I/chatty  (31028): uid=10080(as.ab.myphysio) RenderThread identical 2 lines
[        ] E/eglCodecCommon(31028): glUtilsParamSize: unknow param 0x000085b5


```

```

flutter analyze
Analyzing flutter_physio...                                      

   info • Unused import: 'package:flutter_physio/model/exerciselist.dart' • lib/DB.dart:7:8 • unused_import
   info • TODO in hold for now • lib/config/routes.dart:32:7 • todo
   info • Unused import: 'package:firebase_admob/firebase_admob.dart' • lib/main.dart:2:8 • unused_import
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/ui/archive/exercise/detailexercisearchive.dart:11:7 • must_be_immutable
   info • Unused import: 'package:flutter_physio/ui/ImageCarousel.dart' • lib/ui/archive/workout/detailworkoutarchive.dart:12:8 • unused_import
   info • Unused import: 'package:fluro/fluro.dart' • lib/ui/auth/auth.dart:2:8 • unused_import
   info • Unused import: '../../config/application.dart' • lib/ui/auth/auth.dart:7:8 • unused_import
   info • The top level variable '_auth' isn't used • lib/ui/auth/auth.dart:9:20 • unused_element
   info • The top level variable '_googleSignIn' isn't used • lib/ui/auth/auth.dart:10:20 • unused_element
   info • Unused import: 'package:cached_network_image/cached_network_image.dart' • lib/ui/contacts/list.dart:1:8 • unused_import
   info • TODO: position doesn't seem to notify listeners when metrics change, • lib/ui/createexercise.dart:261:8 • todo
   info • The value of the field '_latestLink' isn't used • lib/ui/home/home.dart:31:10 • unused_field
   info • The value of the field '_latestUri' isn't used • lib/ui/home/home.dart:32:7 • unused_field
   info • The value of the field '_banner' isn't used • lib/ui/home/homerow.dart:14:18 • unused_field
   info • Unused import: 'package:flutter_physio/model/sectionmodel.dart' • lib/ui/util/section.dart:3:8 • unused_import
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/ui/workout/myworkout.dart:13:7 • must_be_immutable

16 issues found. (ran in 2.2s)


```

```

flutter doctor -v
[✓] Flutter (Channel master, v0.8.3-pre.60, on Mac OS X 10.13.6 17G65, locale en-GB)
    • Flutter version 0.8.3-pre.60 at /Users/andrea/flutter
    • Framework revision b5afdca20e (23 hours ago), 2018-09-14 10:04:32 -0400
    • Engine revision ade2d1d04c
    • Dart version 2.1.0-dev.4.0.flutter-c28db2d6e1

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/andrea/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/andrea/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.

```

**Comment by superciccio** [comment] 2018-09-18 08:54
I was able to make it wrok... I just needed to dispose the banner when navigating to the second screen and recreate the banner once in the home screen.

There is another another issue that I found which is the banner overlapping the Navigation drawer when open.

The fact that the Banner is not use placeable also is not very good at the moment. :/

**Comment by zoechi** [comment] 2018-09-25 09:54
I think #19030 allows to fix that.

**Comment by superciccio** [comment] 2018-09-29 17:26
By the way another wired behaviour is that the banner overlaps the navigation drawer :/

**Comment by gcshri** [comment] 2018-12-02 03:52
@superciccio @zoechi seems like there is conflicting information here.

> Unfortunately #19030 doesn't help with that.

https://github.com/flutter/flutter/issues/17452#issuecomment-415128984

**Comment by zoechi** [comment] 2018-12-27 09:50
Duplicate of #17452

**Closed by zoechi** 2018-12-27 09:50 UTC
Labels: p: firebase, p: first party, plugin

**Comment by kroikie** [comment] 2019-10-13 18:51
@superciccio

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/662. Any further collaboration will be done there.
