### ISSUE TITLE
webview_flutter 0.3.15+1 is showing scrollbar in middle of the iPhone X device.

### ISSUE THREAD

**Issue by dhanrajvermaRepo** [flutter/flutter#44174] opened 2019-11-05 10:58 UTC
I am using webview_flutter 0.3.15+1. This webview is working fine in andoid devices but in iPhone X iOS 13.1.3 it shows scrollbar some time extreme right of the screen and some times in middle of the screen.

Please provide any solution as soon as possible.

**Comment by iapicca** [comment] 2019-11-05 11:53
Hi @dhanrajvermaRepo 
can you please provide your updated  `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by yendangn** [comment] 2019-11-06 04:31
I got the same issue

**Comment by deckerst** [comment] 2019-11-06 05:29
Sounds like a duplicate of https://github.com/flutter/flutter/issues/41592

**Comment by dhanrajvermaRepo** [comment] 2019-11-06 09:49
Hi @deckerst, my issue is same as #41592

**Comment by iapicca** [comment] 2019-11-06 09:57
Hi @dhanrajvermaRepo 
Please follow up on the issue linked above,
(thank you @deckerst for noticing it)
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2019-11-06 09:57 UTC

**Comment by dhanrajvermaRepo** [comment] 2019-11-11 07:55
Hi @iapicca, ok I'll follow the issue there.
Thank you.
