### ISSUE TITLE
[release] [android] didChangeMetrics(), sometimes MediaQueryData size = Size.zero

### ISSUE THREAD

**Issue by peterweb2005** [flutter/flutter#151516] opened 2024-07-10 04:53 UTC
### Steps to reproduce

just happens sometimes
"crash record" (actually not crash, just record) the MediaQueryData if size = Size.zero

### Expected results

as https://github.com/flutter/flutter/issues/140569

should resolved

### crash log

FlutterError: Exception: MediaQueryData size zero
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:119)
       at FirebaseCrashlytics.recordFlutterError(firebase_crashlytics.dart:145)
       at ThemeState.update(theme_provider.dart:37)
       at _State.build.<fn>(app.dart:123)
       at _MediaQueryDataHookState.didChangeMetrics(metrics.dart:47)
       at WidgetsBinding.handleMetricsChanged(binding.dart:728)

### Code sample

<details open><summary>Code sample</summary>

```dart
  @override
  void didChangeMetrics() {
    final MediaQueryData data = MediaQuery.of(context);
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] IntelliJ IDEA Community Edition (version 2024.1)
[√] VS Code, 64-bit edition (version 1.90.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category
```

</details>

**Comment by huycozy** [comment] 2024-07-10 09:28
Hi @peterweb2005 
Could you provide a complete and minimal sample code to reproduce this error? And please share the entire error stack trace if any. Thanks!

**Comment by peterweb2005** [comment] 2024-07-10 18:03
just follow this example:
https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeMetrics.html

1. with WidgetsBindingObserver 
2. register observer
```dart
@override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }
@override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
```
3. get the media query data
```dart  @override
  void didChangeMetrics() {
    final MediaQueryData data = MediaQuery.of(context);
  }
```

## note
this only happen in release mode, android

**Comment by maRci002** [comment] 2024-07-10 19:03
This is the expected behavior; see the [document](https://api.flutter.dev/flutter/widgets/MediaQueryData/size.html).

> For instance, during startup, especially in release mode, the first returned size might be [Size.zero](https://api.flutter.dev/flutter/dart-ui/Size/zero-constant.html).

**Comment by huycozy** [comment] 2024-07-11 07:31
@peterweb2005 I still can't reproduce the error with sample code below:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  Size _lastSize = Size.zero;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeMetrics() {
    final MediaQueryData data = MediaQuery.of(context);
    print('MediaQueryData: ${data.size.width} x ${data.size.height}');
    setState(() {
      _lastSize = data.size;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text('Current size: $_lastSize'),
      ),
    );
  }
}

```
</details>

Do you see the crash on app startup? Please check @maRci002's comment above with the link he shared.

**Comment by peterweb2005** [comment] 2024-07-11 17:26
just publish a release to see if there is another event on didChangeMetrics() and that the data size is not zero

**Comment by peterweb2005** [comment] 2024-07-11 17:27
@huycozy yes, maybe less than 1/1000 possibilties

**Comment by huycozy** [comment] 2024-07-12 06:07
@peterweb2005 Does that mean the crash only occurs in production that you get from user via Crashlytics as reported? Or can you also reproduce it locally in release mode? 

I tried this with release mode in local as well (a few times) but can't reproduce it (yes, it could be due to probability as you stated)

Can you also confirm that your implementation is similar to my sample code above? (just by calling size from MediaQueryData inside didChangeMetrics) How do you use the size afterward? Please check [Troubleshooting](https://api.flutter.dev/flutter/widgets/MediaQueryData/size.html#:~:text=have%20different%20sizes.-,Troubleshooting,-It%20is%20considered) part: 

> It is considered bad practice to cache and later use the size returned by MediaQuery.sizeOf(context). It will make the application non-responsive and might lead to unexpected behaviors.

> For instance, during startup, especially in release mode, the first returned size might be [Size.zero](https://api.flutter.dev/flutter/dart-ui/Size/zero-constant.html). The size will be updated when the native platform reports the actual resolution. Using [MediaQuery.sizeOf](https://api.flutter.dev/flutter/widgets/MediaQuery/sizeOf.html) will ensure that when the size changes, any widgets depending on the size are automatically rebuilt.

**Comment by peterweb2005** [comment] 2024-07-23 11:18
now, only have 1 event, 
100% can be resumed from size zero, ie: after didChangeMetrics() event then get media query return size zero, will have next didChangeMetrics() event that get media query return size not zero

**Comment by peterweb2005** [comment] 2024-07-23 11:20
is that related? because only happens in android, which seems due to the flutter platform in android too fast
https://github.com/googleads/googleads-mobile-flutter/issues/906

**Comment by darshankawar** [comment] 2024-07-24 06:45
@peterweb2005 
See below issues for reference out of which one was filed by you:

https://github.com/flutter/flutter/issues/25827
https://github.com/flutter/flutter/issues/140569

Getting size zero is expected and I don't think it is actionable from flutter side to make any changes.
Closing for now. If you disagree, write in comments and I'll reopen it.

**Comment by peterweb2005** [comment] 2024-07-30 17:23
@darshankawar @huycozy 
i found that still some logs which cases is not resume, ie: stuck in size zero

and identify pattern:

```dart
       at _State.build.<fn>(app.dart:115)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1392)
       at SchedulerBinding.handleDrawFrame(binding.dart:1326)
       at SchedulerBinding._handleDrawFrame(binding.dart:1171)
```
```dart
       at _State.build.<fn>(app.dart:115)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1392)
       at SchedulerBinding.handleDrawFrame(binding.dart:1326)
       at SchedulerBinding.scheduleWarmUpFrame.<fn>(binding.dart:1035)
       at PlatformDispatcher.scheduleWarmUpFrame.<fn>(dart:ui)
       at TickerFuture.whenCompleteOrCancel.thunk(ticker.dart:435)
```

, the second block, keywords "scheduleWarmUpFrame" will not have the didChangeMetrics() event, which my application will request 

```dart
MediaQueryData data = MediaQuery.of(context);
```

and then the data size always not size zero, and then my applcation can resume

also, i think that it may not be device problem, same model can have the above 2 block of logs, and then sometimes can resume (have the didChangeMetrics() event) and sometimes not

thanks

**Comment by huycozy** [comment] 2024-08-01 04:42
@peterweb2005 Can you share the complete crash log if any? 

>i found that still some logs which cases is not resume, ie: stuck in size zero

>the second block, keywords "scheduleWarmUpFrame" will not have the didChangeMetrics() event LATER in same second, which inside didChangeMetrics() my application will request

Looks like you have an implementation that blocks your app to be resumed. Please try to provide a complete (and minimal) example that will help us investigate this further. Thank you!

**Comment by peterweb2005** [comment] 2024-08-01 06:21
@huycozy i see, the "block" cases may only be an issue in production environment, depends on how users use,
actually after i handled using loop retries when size zero or listen to didChangeMetrics(), i never experienced in this half year in my side

but really afriad it happen when user using my app, can't prove that it won't happen

**Comment by huycozy** [comment] 2024-08-02 04:24
It looks like this depends on the implementation code, so I will close the issue again. Once you can reproduce this with a specific case with a minimal sample code and clear steps, please write in comments.

**Closed by huycozy** 2024-08-02 04:24 UTC
Labels: in triage
