### ISSUE TITLE
Use wrong exitCode in gradle task

### ISSUE THREAD

**Issue by voiddog** [flutter/flutter#74479] opened 2021-01-22 09:47 UTC
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle.dart#L680

```groovy
 if (result.exitCode != 0) {
    globals.printStatus(result.stdout, wrap: false);
    globals.printError(result.stderr, wrap: false);
    throwToolExit(
      'Gradle task $aarTask failed with exit code $exitCode.',
      exitCode: exitCode,
    );
  }
```
The `exitCode` here should use `result.exitCode` otherwise will occur `Gradle task assembleAarDebug failed with exit code 0.`（The script will judge it as successful）

**Comment by darshankawar** [comment] 2021-01-22 10:17
@voiddog 
Do you have a use case wherein the above will result in `Gradle task assembleAarDebug failed with exit code 0` ?
Can you provide steps to replicate that will throw this error ?

**Comment by voiddog** [comment] 2021-01-22 10:21
Yes, I can create a reproducible demo
Wait a while... I will @ you after I'm done

**Comment by MrBirb** [comment] 2021-01-22 13:36
@pedromassango Duplicate of [#71484](https://github.com/flutter/flutter/issues/71484)

**Comment by pedromassango** [comment] 2021-01-22 15:18
They are similar,seems that someone found it in this PR https://github.com/flutter/flutter/pull/71582#issuecomment-737393869. This will be fixed by https://github.com/flutter/flutter/pull/71582 as well.

**Closed** 2021-02-11 22:11 UTC
Labels: in triage, waiting for customer response
