### ISSUE TITLE
Unable to run hello world app in Linux device

### ISSUE THREAD

**Issue by abhilashraju** [flutter/flutter#87446] opened 2021-08-02 04:32 UTC
## Steps to Reproduce
When I run the flutter demo app after selecting a device as Linux  I am getting the following error.
I am using Ubuntu 16.04.7 LTS
## Logs
```
CMake Error at /snap/flutter/91/usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/snap/flutter/current/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /sirius/work/rabhil/hello_flutter/build/linux/x64/debug/CMakeFiles/CMakeTmp

    Run Build Command:"/snap/flutter/current/usr/bin/ninja" "cmTC_c6f8a"
    [1/2] Building CXX object CMakeFiles/cmTC_c6f8a.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_c6f8a
    FAILED: cmTC_c6f8a 
    : && /snap/flutter/current/usr/bin/clang++    -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -L/snap/flutter/current/usr/lib/ CMakeFiles/cmTC_c6f8a.dir/testCXXCompiler.cxx.o  -o cmTC_c6f8a   && :
    /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpgrt_get_syscall_clamp@GPG_ERROR_1.0'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
<details>
<summary>Logs</summary>
```

```
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

</details>

**Comment by hndrbrm** [comment] 2021-08-02 04:47
Same with [#81882](https://github.com/flutter/flutter/issues/81882).

Solve in [here](https://github.com/flutter/flutter/issues/81882#issuecomment-832584620)

**Comment by TahaTesser** [comment] 2021-08-02 08:56
HI @abhilashraju 
This is a duplicate of https://github.com/flutter/flutter/issues/81882, please follow the comment link above 
Closing as duplicate of https://github.com/flutter/flutter/issues/81882

**Closed by TahaTesser** 2021-08-02 08:56 UTC
Labels: in triage
