### ISSUE TITLE
iOS shell code needs to reflect engine changes

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#18187] opened 2018-06-04 23:37 UTC
@chinmaygarde has done a lot of extensive engine updates in the past weeks ([Google-internal doc](https://docs.google.com/document/d/1n7xgoIpgxMmbVqrkbhYQUHTg0br-By1RSv1psXDIMow)). We might need to update the iOS shell code to reflect this new world. 

It is unclear to me how much iOS code needs to change for this. @mravn-google @sigurdm who have done extensive changes for add-to-app use cases.

**Comment by xster** [comment] 2019-05-22 07:55
@dnfield is there still any work left to do here? I took a quick look at Chinmay's doc and to a layman like me, it appears as if we're already compatible with what's listed.

**Comment by matthew-carroll** [comment] 2019-06-06 00:09
@mehmetf @dnfield @chinmaygarde Does anyone know if we can close this ticket?

**Comment by matthew-carroll** [comment] 2019-06-14 07:37
I'm going to close this because the ticket is old, most likely completed, and relevant parties have not chimed in on the status. Please re-open if the issue is still legitimate.

**Closed by matthew-carroll** 2019-06-14 07:37 UTC
Labels: engine, ⌺‬ platform-ios
