### ISSUE TITLE
Flutter 2.10.1 showing incorrect icons / missing icons.

### ISSUE THREAD

**Issue by m-j-g** [flutter/flutter#98344] opened 2022-02-12 22:45 UTC
There are some icons that are missing and show as other icons.   I noticed when looking at icons.dart that there are a number of icons that aren't showing a preview and don't display the correct icon.  

Here is scoreboard_outlined
<img width="88" alt="Screen Shot 2022-02-12 at 4 42 28 PM" src="https://user-images.githubusercontent.com/10711395/153731069-0eb9a025-017d-4852-ad33-e329eda521ad.png">

<img width="826" alt="Screen Shot 2022-02-12 at 4 37 58 PM" src="https://user-images.githubusercontent.com/10711395/153730891-ac573c44-7161-457a-92cd-3a0037ce4c5b.png">

[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale en-US)
    • Flutter version 2.10.1 at /Users/l/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24

    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/l/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/l/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by yoniker** [comment] 2022-02-13 00:15
Possible duplicate of https://github.com/flutter/flutter/issues/98334

**Comment by danagbemava-nc** [comment] 2022-02-14 08:30
Duplicate of #97767

**Closed by danagbemava-nc** 2022-02-14 08:30 UTC
Labels: in triage
