### ISSUE TITLE
Material 3 Demo App is Crashing on some iOS devices

### ISSUE THREAD

**Issue by QuncCccccc** [flutter/flutter#117164] opened 2022-12-15 20:15 UTC
The app link: https://flutter-experimental-m3-demo.web.app/#/

When the app is running on iOS safari/chrome, scrolling the first two pages will cause crashing and show a message: "A problem repeatedly occurred". But for other platforms, it works fine. 

https://user-images.githubusercontent.com/36861262/207957403-c939926e-50ef-419c-89ea-c99cf4f5feef.mp4

The source code is a PR under review: https://github.com/flutter/samples/pull/1530/files

**Comment by darshankawar** [comment] 2022-12-16 07:42
Thanks for the report @QuncCccccc 
I am unable to replicate the behavior after accessing the link on iOS safari in physical device (iPhone 6s, OS 15.3.1) and also using iOS simulator (iPhone 13 pro max, OS 15.2).


https://user-images.githubusercontent.com/67046386/208048165-94c25e3b-2641-4727-99a2-33fc43ae20e8.MP4

Can you provide the device details on which this behavior occurs ? Also, does the crash occur consistently everytime you scroll ?

**Comment by aguilaair** [comment] 2022-12-18 17:48
https://photos.app.goo.gl/srx1fjQMwdTR9cb37

I can reproduce the issue on my iPhone 14 Pro Max, happens on an app I am developing too so it's not unique to this specific app

**Comment by QuncCccccc** [comment] 2022-12-20 17:40
> Thanks for the report @QuncCccccc I am unable to replicate the behavior after accessing the link on iOS safari in physical device (iPhone 6s, OS 15.3.1) and also using iOS simulator (iPhone 13 pro max, OS 15.2).
> 
>  RPReplay-Final1671176345.MP4 
> Can you provide the device details on which this behavior occurs ? Also, does the crash occur consistently everytime you scroll ?

Yes, all iOS simulators work fine for me, and the app also works okay on iPhone 8(iOS 14.0.1) and iPad(iOS 14.4). But it crashes on iPhone 6(iOS 12.5.6), iPhone 12(iOS 16.1.1), iPhone 13(iOS 15.6.1), and iPhone 14(iOS 16.0.1), and the crashes occur consistently everytime. Both of the first two pages will cause a crash when start scrolling. Based on my experiments, I think the app just crashes on most of the iOS web.

**Comment by darrenaustin** [comment] 2022-12-21 00:06
I was able reproduce this locally with the iOS simulator by forcing the rendered to html:

- Clone the repo: https://github.com/flutter/samples
- `cd samples/experimental/material_3_demo`
- `flutter run --release -d chrome --web-renderer=html`
- Open the same URL from Chrome in the Safari browser in an iOS simulator
- Scroll the main screen and it should crash

@yjbanov can someone from your team take a look at this? This is kinda blocking showing our demo app, as most people will probably see this as a web app and this causes it to crash immediately on iOS. Thx.

**Comment by darrenaustin** [comment] 2022-12-21 00:11
Ok, I may have spoken too soon. It doesn't reliably crash when scrolling, but I have been able to get it to crash a couple of times by just playing around with it (switching back an forth between M2/M3 and a lot of scrolling). It does appear to be intermittent in the simulator.

**Comment by darrenaustin** [comment] 2022-12-21 00:29
Turning on Safari debug I was able to see this in the log when I got it to crash:

```
[Warning] Total canvas memory use exceeds the maximum limit (224 MB). (main.dart.js, line 6711)
[Warning] Total canvas memory use exceeds the maximum limit (224 MB). (main.dart.js, line 6711)
[Warning] Total canvas memory use exceeds the maximum limit (224 MB). (main.dart.js, line 6711)
[Warning] Total canvas memory use exceeds the maximum limit (224 MB). (main.dart.js, line 6711)
[Warning] Total canvas memory use exceeds the maximum limit (224 MB). (main.dart.js, line 6711)
[Log] NoSuchMethodError: method not found: 'toString' on null (main.dart.js, line 24163)
```

And a bunch of exceptions after that.

**Comment by darshankawar** [comment] 2022-12-21 05:28
I trie the steps to replicate as mentioned [above](https://github.com/flutter/flutter/issues/117164#issuecomment-1360529179) and ran on iPhone 6s (OS 15.2.1) but was unable to replicate the issue.


https://user-images.githubusercontent.com/67046386/208828456-d9a9823a-faf0-4387-ba42-c482a75ef69d.MP4

**Comment by eyebrowsoffire** [comment] 2022-12-22 23:09
I also am able to consistently reproduce this with my personal iPhone 13 Pro Max, it seems to crash the webkit process on scroll. I tried attaching devtools, but it was basically useless and immediately just says "webpage crashed" with no useful information in the console logs. I tried looking through my logs for a crash report for the webkit process, but I couldn't seem to find one. Hmm.

**Comment by eyebrowsoffire** [comment] 2022-12-22 23:19
CanvasKit renderer works fine, slight jank on scrolling but no crashes.

**Comment by QuncCccccc** [comment] 2023-01-09 20:10
Just tried to deploy the app again, but the crash seems still happen on my device.

**Comment by darrenaustin** [comment] 2023-01-12 08:33
@mdebbar thanks so much for tackling this issue. We will definitely look into integrating your PR that adds repaint boundaries. Is there any guidance here as to where they needed to be added? (I.e. large groups of widgets? or stuff that takes up a lot of screen real estate?)

I haven't had a chance to run the demo with the suggested changes, I will play with tomorrow.

Should we go ahead and try to cherry pick https://github.com/flutter/engine/pull/38640? 

It sounds like https://github.com/flutter/engine/pull/38602 is promising, but not ready for production yet.

**Comment by mdebbar** [comment] 2023-01-12 19:35
> @mdebbar thanks so much for tackling this issue. We will definitely look into integrating your PR that adds repaint boundaries. Is there any guidance here as to where they needed to be added? (I.e. large groups of widgets? or stuff that takes up a lot of screen real estate?)

I'm not sure if there's general guidance on adding repaint boundaries. It's on a case by case basis. For example, when I open the material 3 demo in Safari (desktop), I looked at the allocated canvases (in devtools, in the Graphics tab):
![image](https://user-images.githubusercontent.com/1278212/212162701-5c676e76-0517-41fb-9811-730a83709253.png)
When I hover over any of these canvases, it highlights this area:
![image](https://user-images.githubusercontent.com/1278212/212162863-ec9bd7f4-9410-4616-b89f-2347115e48a2.png)

So that tells me we are allocating a large canvas to render a single button in it. By adding a repaint boundary around each Card, we are restricting the size of canvas allocation to that Card's size.

### After adding repaint boundaries:

Still not ideal, but the canvases are much smaller:
![image](https://user-images.githubusercontent.com/1278212/212163347-a642a92d-f89f-4ef8-9d4e-5b4027b0ce21.png)

And each canvas only covers a single Card:

![image](https://user-images.githubusercontent.com/1278212/212163478-55ea823b-ef9f-4f27-ab3d-0df1c041803c.png)


> I haven't had a chance to run the demo with the suggested changes, I will play with tomorrow.

Please let me know if it makes things better.

> Should we go ahead and try to cherry pick [flutter/engine#38640](https://github.com/flutter/engine/pull/38640)?

Sure. Did you mean cherry-picking for beta or stable?

**Comment by darrenaustin** [comment] 2023-01-12 21:44
@mdebbar thanks so much for the info. That makes a lot of sense. Both Qun and I have tried this and it appears to fix the problem for us. Given that she wasn't seeing it using only the beta branch (which I assume doesn't have https://github.com/flutter/engine/pull/38640) perhaps we don't need it to be cherry picked. If the web team deems it important enough to push for, please go ahead and start the cherry pick process for it, but if we are running the demo fine with just the repaint boundaries added, that works for us right now. Thx.

**Comment by mdebbar** [comment] 2023-01-13 20:13
Since the crash is fixed, I'm going to close this issue.

I captured the things that we still need to improve in this issue: https://github.com/flutter/flutter/issues/118471

**Closed by mdebbar** 2023-01-13 20:13 UTC
Labels: severe: crash, e: device-specific, framework, f: material design, platform-web, e: OS Version specific, e: web_html, P2, browser: safari-ios
