### ISSUE TITLE
There is some bugs when I set the property of maxLength for TextFormField.

### ISSUE THREAD

**Issue by FallInLoveMyGod** [flutter/flutter#58157] opened 2020-05-28 10:01 UTC
When the length of the word I have write is length than the maxLength ,  I continue tap in the keyboard quickly or I delete the word,  the app shut down.

The output of logs: 
*********
2020-05-28 17:37:03.276263+0800 Runner[5229:1261969] flutter: Another exception was thrown: NoSuchMethodError: The method 'findRenderObject' was called on null.
2020-05-28 17:37:04.268141+0800 Runner[5229:1261702] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString substringWithRange:]: Range {28, 2} out of bounds; string length 29'
*** First throw call stack:
*********

**Comment by TahaTesser** [comment] 2020-05-28 12:52
Hi @FallInLoveMyGod 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by yangyxd** [comment] 2020-06-09 02:59
I have the same problem.

> 2020-06-09 10:45:47.533399+0800 Runner[9795:2015137] [general] Connection to daemon was invalidated
2020-06-09 10:46:27.028370+0800 Runner[9795:2014994] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString substringWithRange:]: Range {0, 8} out of bounds; string length 7'
*** First throw call stack:
(0x18d2155f0 0x18cf37bcc 0x18d26b0cc 0x18d26b1bc 0x18d0fa934 0x1910dd820 0x1910f286c 0x1910f2d48 0x1910f2e7c 0x1910f18a8 0x1910f1a5c 0x1910ebe50 0x1910f7950 0x19110fb50 0x19111008c 0x19110eac0 0x19110fa70 0x18d21b760 0x18d0ecb40 0x19162b130 0x18d192fb8 0x18d18deac 0x18d18e328 0x18d18dc34 0x1972d738c 0x1912c022c 0x1002843a0 0x18d015800)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by yangyxd** [comment] 2020-06-09 03:01
My way of reproduction is:
Limit the textfield's MaxLength = 8. Keep inputting, deleting, inputting, deleting, inputting, and holding the delete key of the soft keyboard, it will flash back soon.

**Comment by TahaTesser** [comment] 2020-06-19 15:22
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2020-06-19 15:22 UTC
Labels: in triage, waiting for customer response
