### ISSUE TITLE
Linux Unopt passed on release branch presubmit but fails license check on CI

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#107761] opened 2022-07-15 23:49 UTC
https://github.com/flutter/engine/pull/34699

**Comment by godofredoc** [comment] 2022-07-27 01:29
Do you have the link for the failed build?

**Comment by godofredoc** [comment] 2022-07-27 01:29
@CaseyHillers for the question above

**Comment by CaseyHillers** [comment] 2022-07-27 01:37
Presubmit (passing): https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Unopt/15398/overview
Postsubmit (failing): https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Unopt/6492/overview

**Comment by godofredoc** [comment] 2022-07-27 02:03
The failing task is running the licenses check and the passing one is not.

Failing:
![image](https://user-images.githubusercontent.com/54371434/181144336-37582b62-995a-4083-a288-a2cb37460fc4.png)

Passing:
![image](https://user-images.githubusercontent.com/54371434/181144476-6ac3b18f-bf72-49cc-821a-fd3807ccb324.png)

**Comment by godofredoc** [comment] 2022-07-27 02:07
Presubmit ran with the main version of the recipes while post-submit ran with `refs/heads/fuchsia_r49`

**Comment by godofredoc** [comment] 2022-07-27 02:15
The problem is the presubmit logic only uses release branch recipes if the branch starts with `flutter-` and in this case the branch name is `fuchsia_`.

@CaseyHillers Do we want to fix the logic or should we close it as working as intended?

**Comment by godofredoc** [comment] 2022-07-27 02:16
This is the link to the logic collecting the branches:

https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/service/luci_build_service.dart;l=220?q=exe_cipd_version&ss=flutter%2Fcocoon

**Comment by CaseyHillers** [comment] 2022-07-27 04:33
Removing this sounds good to me. For the time being, Fuchsia is the only customer using this, but I assume other's will want to take advantage of their own releases.

**Closed** 2022-08-18 00:27 UTC
Labels: team: infra, team: release
