### ISSUE TITLE
Cut/Copy/Paste translation CRASH

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#19120] opened 2018-07-06 18:42 UTC
Open any TextField and select some text. Works ok as long as the language is English. When testing in Portuguese (pt_br), it crashes:

    ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞══
    I/flutter (22994): The following NoSuchMethodError was thrown building _TextSelectionToolbar(dirty):
    I/flutter (22994): The getter 'cutButtonLabel' was called on null.
    I/flutter (22994): Receiver: null
    I/flutter (22994): Tried calling: cutButtonLabel
    I/flutter (22994): 
    I/flutter (22994): When the exception was thrown, this was the stack:
    I/flutter (22994): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
    I/flutter (22994): #1      _TextSelectionToolbar.build (package:flutter/src/material/text_selection.dart:41:62)

That's the offending code:

    final MaterialLocalizations localizations = MaterialLocalizations.of(context);
    if (handleCut != null)
      items.add(new FlatButton(child: new Text(localizations.cutButtonLabel), onPressed: handleCut));

**Comment by zoechi** [comment] 2018-07-06 20:28
Please add the output of `flutter doctor`

**Comment by marcglasberg** [comment] 2018-07-06 21:05
[√] Flutter (Channel dev, v0.5.5, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    X Android license status unknown.
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[!] VS Code, 64-bit edition (version 1.21.1)
[√] Connected devices (1 available)

**Comment by marcglasberg** [comment] 2018-07-06 22:08
[√] Flutter (Channel dev, v0.5.6, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    X Android license status unknown.
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[!] VS Code, 64-bit edition (version 1.21.1)
[√] Connected devices (1 available)

**Comment by marcglasberg** [comment] 2018-08-17 17:25
I would like to add some more info to this. This is solved if you add `GlobalMaterialLocalizations.delegate` and `GlobalWidgetsLocalizations.delegate` to the localization delegates.

However, suppose you don't want to add any translations to your app. Then your app, which is English only, crashes when someone with a phone configured to a language different than English tries to copy/paste some text. This forces you to add the localization delegates even if you don't want any translations.

But even if you do add the localization delegates above, your app will still crash if the phone is in some language different from the ones already provided by Flutter!

To solve this, stock Flutter widgets cannot crash if they don't find the localizations. Instead, they must simply fall back to English.

This issue is not only for copy/paste, but for all widgets with internal localizations.

**Comment by aidandavis** [comment] 2018-10-15 05:44
I'm having this same error. I'm building an app for my company, which is a utility, and we don't intend to develop for languages other than English.
Is there some fix for this issue, or is this something that needs to be fixed in Flutter?

**Comment by HansMuller** [comment] 2018-10-27 00:53
If the value of a `MaterialApp`'s `supportedLocales` is `[Locale('en', 'US')]` - the default - then the english translations will be used, no matter what the device's locale is. In other words for an app that's only going to use english translations, nothing needs to be done or configured.

Which is to say, I don't understand the failure mode reported here. 

If the app specifies one or more `supportedLocales` from the list in [GlobalMaterialLocalizations](https://docs.flutter.io/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html) then `localizationsDelegates: GlobalMaterialLocalizations.delegates,` must also be specified per the documentation.  In that case, if the device is configured to a locale that matches one of the `supportedLocales`, then flutter will use the appropriate translations. If the device is configured for a locale that doesn't match a supported locale, then the first element of `supportedLocales` is used.  So to have an internationalized app fallback to english for unsupported locales, make `Locale('en', 'US')]` the first entry in `supportedLocales`.

If you believe that a problem still exists, please provide a test case that shows how MaterialApp is configured.

**Comment by aidandavis** [comment] 2018-10-29 04:54
Hi,
We've deescalated the bug on our side because it was only happening on one user's phone. It happens consistently when the text field is long pressed. It happens on any text input field. The phone is an iphone 8, running ios 11.4.1. There was no special locality set on the phone, and we haven't done anything for the locales in Flutter. English in app and English (Australia) in the phone.

It may not be the same error, but the result is the same. This is the closest issue I could find.

**Comment by HansMuller** [comment] 2018-10-29 17:09
@marcglasberg - if you have a test case that demonstrates this bug per https://github.com/flutter/flutter/issues/19120#issuecomment-433577785, please post it here.

**Comment by HansMuller** [comment] 2018-10-29 17:12
@aidandavis - thanks for narrowing down the scope of the problem your user ran into. Will see if we can reproduce the problem with iPhone 8, iOS 11.4.1.

**Comment by chunlea** [comment] 2018-12-10 11:55
It seems to https://github.com/flutter/flutter/issues/22624, and due to https://github.com/flutter/flutter/issues/13452, we need to waiting Cupertino Translation added. But we can use https://github.com/flutter/flutter/issues/22624#issuecomment-445524102 to force to use the Android style text selection bar.

I think this issue can be closed.

**Comment by pakivika** [comment] 2019-01-28 18:11
> It seems to #22624, and due to #13452, we need to waiting Cupertino Translation added. But we can use [#22624 (comment)](https://github.com/flutter/flutter/issues/22624#issuecomment-445524102) to force to use the Android style text selection bar.
> 
> I think this issue can be closed.

Workaround presented in #22624 is only last resort and it causes other problems. For instance I won't be able to select platform specific translation strings any longer.

If I set the following

```
if (Platform.operatingSystem == 'android') {...}
```

Then selecting platform specific strings won't work in iOS because I always get the string meant for Android.

```
Theme.of(context).platform == TargetPlatform.iOS ?
   MyAppLocalizations.of(context).appStoreUrlIOS() :
   MyAppLocalizations.of(context).appStoreUrlAndroid());
```

I have translations in intl_en.arb defined as follows

```
  "appStoreUrlIOS": "itms://itunes.apple.com/us/app/peflog/id1212024484?mt=8",
  "@appStoreUrlIOS": {
    "description": "Url to the appstore",
    "type": "text",
    "placeholders": {}
  },
  "appStoreUrlAndroid": "https://play.google.com/store/apps/details?id=fi.haliops.peflog",
  "@appStoreUrlAndroid": {
    "description": "Url to the playstore",
    "type": "text",
    "placeholders": {}
  },
```

**Comment by pakivika** [comment] 2019-02-14 19:21
And just to update, the problem is still present in 
`Flutter 1.1.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 985ccb6d14 (5 weeks ago) • 2019-01-08 13:45:55 -0800
Engine • revision 7112b72cc2
Tools • Dart 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)`

**Comment by kangwang1988** [comment] 2019-02-15 05:33
@pakivika 
Can you paste a minimal main.dart(pubspec.yaml) which can reproduce this issue?

**Comment by zoechi** [comment] 2019-02-15 07:18
@pakivika iOS, Android, or both?

**Comment by xiewu** [comment] 2019-02-16 03:13
Hi, @kangwang1988 , this config may cause the issue. Original project: https://github.com/CarGuo/GSYGithubAppFlutter

pubspec.yaml

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2
  fluttertoast: 2.0.9
  json_annotation: ^1.1.0
  flutter_redux: ^0.5.2
  device_info: ^0.2.1
  connectivity: ^0.3.1
  url_launcher: ^3.0.3
  flutter_markdown: ^0.2.0
  share: ^0.5.3
  flutter_spinkit: ^2.0.1
  flutter_webview_plugin: ^0.2.1+2
  sqflite: ^0.12.2+1
  pub_semver: ^1.4.2
  flutter_statusbar: ^0.0.1
  flutter_svg: 0.5.4
  photo_view: ^0.0.7
  flutter_slidable: ^0.4.3
  dio: ^1.0.1
  flutter_localizations:
    sdk: flutter
  event_bus:  ^1.0.1
  flutter_cache_manager: ^0.1.2
  path_provider: ^0.4.1
  permission_handler: 2.0.0
  scoped_model: ^0.3.0
  package_info: ^0.3.2

dev_dependencies:
  build_runner: ^0.10.1+1
  json_serializable: ^1.1.0


main.dart

import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:event_bus/event_bus.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:my_app_flutter/common/event/HttpErrorEvent.dart';
import 'package:my_app_flutter/common/localization/MyLocalizationsDelegate.dart';
import 'package:my_app_flutter/common/redux/MyState.dart';
import 'package:my_app_flutter/common/model/User.dart';
import 'package:my_app_flutter/common/style/MyStyle.dart';
import 'package:my_app_flutter/common/utils/CommonUtils.dart';
import 'package:my_app_flutter/page/HomePage.dart';
import 'package:my_app_flutter/page/LoginPage.dart';
import 'package:my_app_flutter/page/WelcomePage.dart';
import 'package:flutter_redux/flutter_redux.dart';
import 'package:redux/redux.dart';
import 'package:my_app_flutter/common/net/Code.dart';

class FlutterReduxApp extends StatelessWidget {
  final store = new Store<MyState>(
    appReducer,

    initialState: new MyState(
        userInfo: User.empty(),
        eventList: new List(),
        trendList: new List(),
        themeData: new ThemeData(
          primarySwatch: MyColors.primarySwatch,
          platform: TargetPlatform.iOS
        ),
        locale: Locale('zh', 'CH')),
  );

  FlutterReduxApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return new StoreProvider(
      store: store,
      child: new StoreBuilder<MyState>(builder: (context, store) {
        return new MaterialApp(
            localizationsDelegates: [
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              MyLocalizationsDelegate.delegate,
            ],
            locale: store.state.locale,
            supportedLocales: [store.state.locale],
            theme: store.state.themeData,
            routes: {
              WelcomePage.sName: (context) {
                store.state.platformLocale = Localizations.localeOf(context);
                return WelcomePage();
              },
              HomePage.sName: (context) {
                return new MyLocalizations(
                  child: new HomePage(),
                );
              },
              LoginPage.sName: (context) {
                return new MyLocalizations(
                  child: new LoginPage(),
                );
              },
            });
      }),
    );
  }
}

class MyLocalizations extends StatefulWidget {
  final Widget child;

  MyLocalizations({Key key, this.child}) : super(key: key);

  @override
  State<MyLocalizations> createState() {
    return new _MyLocalizations();
  }
}

**Comment by xiewu** [comment] 2019-02-16 03:17
```
flutter doctor -v
[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17134.590], locale zh-CN)
    • Flutter version 1.2.0 at E:\flutter
    • Framework revision 06b979c4d5 (3 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\xw\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\xw\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by xiewu** [comment] 2019-02-16 03:28
Original project need change `lib/widget/webview/WebView.dart` line:31 `this.gestureRecognizers = const <OneSequenceGestureRecognizer>[],` to `this.gestureRecognizers,`(may cause issue),line:48 `final List<OneSequenceGestureRecognizer> gestureRecognizers;` to `final Set<Factory<OneSequenceGestureRecognizer>> gestureRecognizers;`

**Comment by kangwang1988** [comment] 2019-02-16 13:08
@xiewu 
I think it's a bad idea if I have to create a github client_id & client_secret if I want to use it.
It should be a minimal project which can reproduce this issue without knowing too much irrelevant things.

**Comment by xiewu** [comment] 2019-02-16 17:16
@kangwang1988 
It is very easy to request a github oauth access client,just  create a github Oauth App. Settings/Developer Settings/OAuth Apps/New OAuth App

**Comment by zoechi** [comment] 2019-02-17 12:39
@xiewu 
> It is very easy to request a github oauth access client,just create a github Oauth App.

How is the oauth access client related to the the reported issue?

How can a minimal reproduction about copy-paste depend on such a long list of imports?
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:event_bus/event_bus.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:my_app_flutter/common/event/HttpErrorEvent.dart';
import 'package:my_app_flutter/common/localization/MyLocalizationsDelegate.dart';
import 'package:my_app_flutter/common/redux/MyState.dart';
import 'package:my_app_flutter/common/model/User.dart';
import 'package:my_app_flutter/common/style/MyStyle.dart';
import 'package:my_app_flutter/common/utils/CommonUtils.dart';
import 'package:my_app_flutter/page/HomePage.dart';
import 'package:my_app_flutter/page/LoginPage.dart';
import 'package:my_app_flutter/page/WelcomePage.dart';
import 'package:flutter_redux/flutter_redux.dart';
import 'package:redux/redux.dart';
import 'package:my_app_flutter/common/net/Code.dart';
```

Please see https://stackoverflow.com/help/mcve about what a minimal reproduction is.

**Comment by xiewu** [comment] 2019-02-17 14:18
@kangwang1988  @zoechi  ,sorry, i am a beginner. The project is a demo,and I use it to test the flutter environment, I have no ability to change dart code. This issue seems is caused by localization. So I pasted it.

**Comment by xiewu** [comment] 2019-02-17 14:22
I upgrade dart to v 2.1.2 and flutter 1.2.1, this issue seems has gone.

**Comment by kangwang1988** [comment] 2019-02-17 14:57
Close #19120
Feel free to comment below if any one can reproduce this issue using the latest master branch.

**Closed by kangwang1988** 2019-02-17 14:57 UTC
Labels: a: internationalization, a: text input, framework, severe: crash, waiting for customer response

**Comment by Katekko** [comment] 2019-02-26 12:16
still crashing when I try copy/paste/cut @kangwang1988 
Am i doing something wrong?

![image](https://user-images.githubusercontent.com/13632735/53411789-39e25780-39a6-11e9-9ef8-eba80652d0cb.png)

![image](https://user-images.githubusercontent.com/13632735/53411986-d60c5e80-39a6-11e9-9229-4f3b39e6a1bd.png)

![image](https://user-images.githubusercontent.com/13632735/53412084-21bf0800-39a7-11e9-9b12-3c9514948c11.png)

**Comment by RaimundWege** [comment] 2019-03-08 09:53
Also crashing for german language:

![simulator screen shot - iphone 8 - 2019-03-08 at 10 49 24](https://user-images.githubusercontent.com/1120142/54021381-53e31d80-4190-11e9-9c56-0c2a6f5a40c4.png)

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G65, locale de-DE)
    • Flutter version 1.2.1 at /Users/raimundwege/Development/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/raimundwege/Library/android/sdk
    • Android NDK at /Users/raimundwege/Library/android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/raimundwege/Library/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Ray      • xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx • ios • iOS 12.1.2
    • iPhone 8 • 37A1A9B5-BDD2-4D03-9A0F-BFD6BF140D21     • ios • iOS 12.1 (simulator)
```

**Comment by HansMuller** [comment] 2019-03-08 15:45
@RaimundWege - please open a new issue with a small test case that demonstrates the problem. This issue is closed and will not get as much attention as an open issue.

**Comment by caroline171** [comment] 2019-06-03 11:38
Still found for Arabic on IOS

**Comment by HansMuller** [comment] 2019-06-03 17:08
@caroline171 - please open a new issue with a small test case that demonstrates the problem. This issue is closed and will not get as much attention as an open issue.

**Comment by AgiliApps** [comment] 2019-07-30 11:38
To fix this problem, just add **GlobalCupertinoLocalizations.delegate**
to **localizationsDelegates:**

e.g.
```
localizationsDelegates: [
    GlobalCupertinoLocalizations.delegate,
    AppLocalizations.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
]
```

**Comment by MatthiasGehrmann** [comment] 2019-10-12 12:56
worked for me !
thank you so much :)

> 
> To fix this problem, just add **GlobalCupertinoLocalizations.delegate**
> to **localizationsDelegates:**
> 
> e.g.
> 
> ```
> localizationsDelegates: [
>     GlobalCupertinoLocalizations.delegate,
>     AppLocalizations.delegate,
>     GlobalMaterialLocalizations.delegate,
>     GlobalWidgetsLocalizations.delegate,
> ]
> ```
