### ISSUE TITLE
crash report during flutter upgrade

### ISSUE THREAD

**Issue by chinabosh** [flutter/flutter#50901] opened 2020-02-17 01:58 UTC
[flutter_03.log](https://github.com/flutter/flutter/files/4211482/flutter_03.log)

**Comment by jonahwilliams** [comment] 2020-02-17 02:17
Duplicate of #50902

If you have more context for this error message, or want to leave a 👍 to indicate that it is still affecting you please comment on the meta issue #50902

**Closed by jonahwilliams** 2020-02-17 02:17 UTC
