### ISSUE TITLE
[Windows Desktop] Backspace stops working after Pressing Shift + three Keys 

### ISSUE THREAD

**Issue by luciano-cervantes** [flutter/flutter#95479] opened 2021-12-17 20:28 UTC
When pressing the right shift key and pressing three more keys at the same time, the backspace key stops working and the other keys are inverted, to return to work just click the left shift key, but this is a bug. The similar thing happened [here ](https://github.com/flutter/flutter/issues/75675)

**Comment by maheshmnj** [comment] 2021-12-20 07:05
HI @luciano-cervantes, Thanks for filing the issue. Please share your output of `flutter doctor -v` This is likely a duplicate of https://github.com/flutter/flutter/issues/95502.

**Comment by luciano-cervantes** [comment] 2021-12-20 16:37
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [versÃ£o 10.0.19041.1415], locale pt-BR)
    • Flutter version 2.8.0 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (12 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.1)
    • VS Code at C:\Users\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.19041.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.57

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment] 2021-12-21 06:17
Thanks for the info @luciano-cervantes, when the keys stops working Are there any error logs in the console? Also Does this happen after pressing any specific keys or shift + any three keys?

**Comment by luciano-cervantes** [comment] 2021-12-21 11:26
Hi, nothing appears in the error log. and this happens after pressing Shift + any three keys. It is important to note that it is just a right shift. and to get back to work, just press the left shift

**Comment by maheshmnj** [comment] 2021-12-21 12:07
Thanks for the info. I verified on `stable 2.8.0`. I am unable to reproduce the issue. Can you share what platform are you compiling for?

https://user-images.githubusercontent.com/31410839/146927090-8501ca46-9917-4967-9b23-f9398fc2a16e.mp4

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.8.0 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (12 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)  
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.53

• No issues found!
```
</details>

**Comment by luciano-cervantes** [comment] 2021-12-21 13:26
I'm compiling on windows 10, but the error also happens on windows 11. It was tested in debug and release version

https://user-images.githubusercontent.com/72446530/146937359-16357b13-900a-4bff-b2f6-b5f6d49cfe87.mp4

**Comment by maheshmnj** [comment] 2021-12-22 05:15
Thanks for the info @luciano-cervantes,  You might possibly be hitting this issue https://github.com/flutter/flutter/issues/94880 which was fixed recently. Can you please try upgrading to latest master channel by running 
```
flutter channel master
flutter upgrade
```
and see if this fixes the issue.

**Comment by luciano-cervantes** [comment] 2021-12-22 13:50
I updated the flutter for the master channel and the problem when pressing three keys at the same time was fixed, now I can delete using backspace. But now the keys are getting inverted when you click right shift + three keys, this means that if the capslock is on the characters are lowercase if the capslock is off the characters are uppercase. 
Here is the flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.9.0-1.0.pre.159, on Microsoft Windows [versÃ£o 10.0.19041.1415], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by luciano-cervantes** [comment] 2021-12-22 14:07
When starting the video the capslock was turned off.
https://user-images.githubusercontent.com/72446530/147105162-c1c5de84-408e-4637-8b93-fcd06e538ba3.mp4

**Comment by maheshmnj** [comment] 2021-12-23 07:18
Thanks for the info @luciano-cervantes, I am unable to reproduce this neither on stable nor on master. Leaving this open for further investigation.

**Comment by luciano-cervantes** [comment] 2021-12-23 11:36
OK, this is a mistake that I think is hard to make in production. But it would be great to have it corrected. I'll leave a Widget that can be useful for someone who doesn't want to have problems with it.

`class ShiftRightFixer extends StatefulWidget {
  ShiftRightFixer({this.child});
  final Widget child;
  @override
  State<StatefulWidget> createState() => _ShiftRightFixerState();
}

class _ShiftRightFixerState extends State<ShiftRightFixer> {
  final FocusNode focus = FocusNode(skipTraversal: true, canRequestFocus: false);
  @override
  Widget build(BuildContext context) {
    return Focus(
      focusNode: focus,
      onKey: (_, RawKeyEvent event) {
        return event.physicalKey == PhysicalKeyboardKey.shiftRight ?
          KeyEventResult.handled : KeyEventResult.ignored;
      },
      child: widget.child,
    );
  }
}`
This code snippet was taken from [here](https://github.com/flutter/flutter/issues/75675#issuecomment-831581709). Thanks @maheshmnj

**Comment by dkwingsmt** [comment] 2022-02-02 21:50
This is likely a duplicate of https://github.com/flutter/flutter/issues/91482 and will be fixed soon.

**Closed** 2022-02-02 23:30 UTC
Labels: a: text input, engine, platform-windows, a: desktop, passed first triage, P4
