### ISSUE TITLE
Simplified vs Traditional Chinese locales do not display properly on iOS

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#22642] opened 2018-10-03 23:36 UTC
In Mulligan's bug report, the user's device locale was detected by the Feedback library as "zh-TW", which would indicate Traditional Chinese.

Their feedback screenshot showed the screen title as ( 选择帐号 ), which is apparently Simplified Chinese. Traditional Chinese translation should be ( 選取帳戶 ) which the TC correctly shows.

I confirmed this by switching my physical device's language setting to Traditional Chinese, and the app rendered using Simplified Chinese strings.

**Comment by mehmetf** [comment] 2018-10-03 23:37
It is worth noting that the locale works properly on Android.

**Comment by jamesderlin** [comment] 2018-10-03 23:43
There's more information in the internal bug report.

Possibly we're getting something like zh-Hant where we expect something like zh-TW.

**Comment by mehmetf** [comment] 2018-10-04 00:09
Thanks @jamesderlin I would like Flutter team to look at this with a fresh pair of eyes. The internal bug is b/116636856 for reference. @xster Xiao, could you please bring this to the attention of the appropriate owner given that it is customer critical? Thanks!

**Comment by xster** [comment] 2018-10-04 19:33
@GaryQian this was the bug we were just chatting about.

**Comment by GaryQian** [comment] 2018-10-08 19:53
Encountered https://github.com/flutter/flutter/issues/17933 when trying to replicate. This may be a more general bug relating to iOS localization.

**Comment by GaryQian** [comment] 2018-10-08 21:11
After experimentation, I think I can better define the behavior (still investigating the cause):

We currently do not seem to distinguish/pass the correct country code on. Flutter is treating all zh_** languages as the same, and will render any text in the **first** zh_ language listed under `supportedLocales: [...],`

If the first zh_ (also applies to other languages with country identifiers) is simplified (`'zh'`) then it will render as simplified. If the first happens to be `'zh_TW'` then it will render traditional.

**Comment by GaryQian** [comment] 2018-10-10 18:31
I have identified the cause for this.

https://github.com/flutter/engine/pull/6483 is a temporary hack to work around this bug for Chinese due to its potential to affect large numbers of users.

On iOS, the way the locale selection works allows for strange locales such as "zh_US" to be selected. In addition, we do not pass on the scriptcode (eg, 'Hant' for traditional Chinese and 'Hans' for simplified).

Whenever we are unable to match on both the language code and country code, we default to selecting the first language specified, without regard to script code. In cases where simplified is listed first (as is most common), then users with locale 'zh_Hant_US' will render simplified text. The opposite (simplified locale rendering traditional) is also possible, but less likely due to developers not tending to list traditional first. This bug affects all languages with multiple scripts.

The full fix involves properly supporting scriptcodes as well as other BCP47 properties such as variants. Due to the potential severity of the bug and the API breaking nature of the full fix, the patch mentioned above can be landed to help reduce the impact of the bug until it is properly fixed.

**Comment by GaryQian** [comment] 2018-10-26 18:10
https://github.com/flutter/flutter/pull/23583 Should provide a new locale resolution system that will fix this.

**Comment by GaryQian** [comment] 2018-11-06 19:35
After a thorough yak-shave, The following PRs should resolve this:
https://github.com/flutter/flutter/pull/23583
https://github.com/flutter/engine/pull/6711
https://github.com/flutter/flutter/pull/23853

Will land them as they are approved/safe

**Comment by GaryQian** [comment] 2018-11-09 22:48
The changes necessary to distinguish simplified vs traditional has been landed. To properly support scriptCodes, the following changes should be made (copied from the dartdocs in https://github.com/flutter/flutter/pull/24184):

When supporting languages with more than one script, it is recommended to specify the scriptCode explicitly. Locales may also be defined without countryCode to specify a generic fallback for a particular script. Not specifying scriptCode where it is needed (such as Chinese) may lead to improperly resolved locales. This may be achieved with the [Locale.fromSubtags] constructor:

```dart
// Full Chinese support for CN, TW, and HK
supportedLocales: [
  const Locale.fromSubtags(languageCode: 'zh'), // generic Chinese
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'), // generic simplified Chinese
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'), // generic traditional Chinese
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans', countryCode: 'CN'),
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant', countryCode: 'TW'),
  const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant', countryCode: 'HK'),
],
```

**Closed by GaryQian** 2018-11-09 22:48 UTC
Labels: a: internationalization, customer: mulligan (g3), severe: customer critical, ⌺‬ platform-ios

**Comment by w4mxl** [comment] 2019-01-24 10:56
> The changes necessary to distinguish simplified vs traditional has been landed. To properly support scriptCodes, the following changes should be made (copied from the dartdocs in #24184):
> 
> When supporting languages with more than one script, it is recommended to specify the scriptCode explicitly. Locales may also be defined without countryCode to specify a generic fallback for a particular script. Not specifying scriptCode where it is needed (such as Chinese) may lead to improperly resolved locales. This may be achieved with the [Locale.fromSubtags] constructor:
> 
> ```dart
> // Full Chinese support for CN, TW, and HK
> supportedLocales: [
>   const Locale.fromSubtags(languageCode: 'zh'), // generic Chinese
>   const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'), // generic simplified Chinese
>   const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'), // generic traditional Chinese
>   const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans', countryCode: 'CN'),
>   const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant', countryCode: 'TW'),
>   const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant', countryCode: 'HK'),
> ],
> ```

@GaryQian  您好，当我按照上面所示去做的时候，我发现：
假设在 Android 和 iOS 上都首选 繁体中文(香港)，
是在 Android Localizations.localeOf(context).toString()  return ‘zh_Hant_HK’，
而在 iPhone 上 return  ‘zh_Hant’。通过查看源码的逻辑我能理解为什么这么返回，但是这样的结果是不是有失合理呢？

![users mu desktop screenshot_1548327085](https://user-images.githubusercontent.com/3645496/51673680-92ba7b00-2009-11e9-96da-dfb09118173a.jpg)
![users mu desktop simulator screen shot - iphone xr - 2019-01-24 at 18 51 20](https://user-images.githubusercontent.com/3645496/51673686-98b05c00-2009-11e9-9bd7-143d92a56526.jpg)

**Comment by GaryQian** [comment] 2019-01-24 22:48
@w4mxl Android and iOS use different systems to select language/script/country.

Android:
Select language. Select country. Script is assumed.

iOS:
Select language AND script as one option. Select country.

This may be causing the platform to be sending incomplete or differing data for the `zh_Hant_HK` locale.  I can check internally to see what locale we are getting directly from the platform, as the logic should select the same locale for both in this case. If an exact match is found (which should be the case here) then the localeResolution should return the exact match always,

**Comment by w4mxl** [comment] 2019-01-25 04:02
> This may be causing the platform to be sending incomplete or differing data for the zh_Hant_HK locale. I can check internally to see what locale we are getting directly from the platform,

@GaryQian 
Yes, that's it. I also want to know which fields obtained by flutter from the iOS and Android platforms are assembled as the system language obtained by the flutter app.

 And I guess flutter on iOS is by splicing language(or language AND script) and country as a locale string return back , just guessing. 

Look forward to your reply. Thank you!

**Comment by GaryQian** [comment] 2019-01-29 20:44
I have found the problem. I don't think there is actually anything Flutter can do about it though.

When the locale is set to Traditional Chinese HK on Android, the way it is set is through a language+script selection, and then a required country selection immediately after. This ensures the country always corresponds to the language and script.

However, on iOS, the language and script selection is separate from the country selection. In your case, your language and script is set to Traditional Chinese (HK), which iOS interprets as zh_Hant. iOS does not make a distinction at the supported languages level between TW, HK, or other forms of Traditional Chinese. Instead, the "HK" portion of the selection is passed separately as the second preferred locale as 'zh_HK'. The first preferred locale instead uses the country set by the separate country setting. In your case, it is set to China (PRC).

Your list of preferred locales looks like:

1. zh_Hant_CN
2. zh_HK
3. zh_Hans_CN
4. ...

Thus, iOS does not correctly include the 'HK' part of the language in a way we can process it. Instead, we are led to try to resolve zh_Hant_CN.

**Comment by w4mxl** [comment] 2019-02-11 07:19
@GaryQian 

First of all, thank you for your detailed reply.

A few days ago I also looked at Internation­alizing on iOS. Did some testing.

``` ObjectiveC
NSString *udfLanguageCode = [[NSUserDefaults standardUserDefaults] objectForKey:@"AppleLanguages"][0];
NSString *pfLanguageCode = [NSLocale preferredLanguages][0];

NSLog(@"%@", [[NSUserDefaults standardUserDefaults] objectForKey:@"AppleLanguages"]);
NSLog(@"%@", udfLanguageCode);
    
NSLog(@"%@",[NSLocale preferredLanguages]);
NSLog(@"%@", pfLanguageCode);
```
<image src="https://ws3.sinaimg.cn/large/006tNc79gy1fzivqut9zsj30n01dsadz.jpg" width="300"/>

I get the following output information：

```
2019-01-25 15:44:23.640613+0800 TestLanguage[30886:254351] (
    "zh-Hant-HK",
    "zh-Hant-TW",
    "zh-Hans-CN",
    "ja-CN",
    "en-CN"
)
2019-01-25 15:44:23.640701+0800 TestLanguage[30886:254351] zh-Hant-HK
2019-01-25 15:44:23.640848+0800 TestLanguage[30886:254351] (
    "zh-Hant-HK",
    "zh-Hant-TW",
    "zh-Hans-CN",
    "ja-CN",
    "en-CN"
)
2019-01-25 15:44:23.640921+0800 TestLanguage[30886:254351] zh-Hant-HK
```

So, can flutter consider using one of the above iOS APIs to get locales? The locales information obtained in this way seems to be consistent with Android.

**Comment by GaryQian** [comment] 2019-02-11 07:28
Thanks for looking at that, I can do some experimentation and see if we might be able to use that API instead and what the difference is from what we are doing now.
