### ISSUE TITLE
Flutter Android TV app is rejected because "crashes after launch" but it works correctly on the emulator and Android TV.

### ISSUE THREAD

**Issue by bhoominn** [flutter/flutter#96575] opened 2022-01-13 06:47 UTC
I have developed Flutter App for Android TV. basically, it is a Video Streaming app like Netflix and is meant to be used for Android TV only.

The app is working very fine in the TV emulator but when I am uploading in the Play Store Console, they are approving but getting continuous rejection for Android TV Release Type. See the below picture.

![Screenshot from 2022-01-13 12-07-46](https://user-images.githubusercontent.com/10153710/149278490-b4311c55-b06d-4fe5-82aa-c072546077a8.png)

![Screenshot from 2022-01-13 12-09-15](https://user-images.githubusercontent.com/10153710/149278647-a8e28486-20e5-47ae-a49e-00c60f7d2bbe.png)

I have followed the Android TV Guideline from the above picture.
**_TV Activity documentation_** - [https://developer.android.com/training/tv/start/start.html#tv-activity](https://developer.android.com/training/tv/start/start.html#tv-activity)

Please help anyone in approving the TV app in Play Store.

**Comment by maheshmnj** [comment] 2022-01-13 08:21
Hi @bhoominn, Thanks for filing the issue.
Please share the output of `flutter doctor -v`, and are there any crash logs for us to have a look?

Thanks

**Comment by bhoominn** [comment] 2022-01-13 08:31
The issue is there are no any crashes.

**Comment by maheshmnj** [comment] 2022-01-13 09:24
@bhoominn, Without any logs or reproducible steps this issue wouldn't be actionable. Probably you can try using crashlytics or sentry and see if you get any crash logs along with your output of `flutter doctor -v` and `flutter run -v`.

**Comment by bhoominn** [comment] 2022-01-13 09:55
Here is the screenshot of the crash.

![crash](https://user-images.githubusercontent.com/10153710/149307722-2e81635a-7e12-4976-9185-ad2357d1d433.png)

**Comment by maheshmnj** [comment] 2022-01-13 10:20
@bhoominn  It would be great if you can share the complete logs in a text file, rather than showing a screenshot of a partial error log, And please do share the complete output of `flutter doctor -v` as requested above.

**Comment by bhoominn** [comment] 2022-01-13 12:42
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yacourb.AstreamTv/MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by maheshmnj** [comment] 2022-01-13 13:20
> please do share the complete output of flutter doctor -v as requested above.

**Comment by bhoominn** [comment] 2022-02-01 07:51
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1466], locale en-US)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Redmi Y2 (mobile) • 33003235 • android-arm    • Android 9 (API 28)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 97.0.1072.69

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment] 2022-02-01 07:59
> java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found

Thanks for the info, Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/57237

**Closed by maheshmnj** 2022-02-01 07:59 UTC
Labels: in triage
