### ISSUE TITLE
Dash Docset Icon for Flutter is not specified.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#25104] opened 2018-12-07 22:21 UTC
The icon for Flutter related APIs in Dash (and probably Zeal) is unspecified. This makes it hard to distinguish Flutter APIs from others. It would be great if the Flutter logo was added in place of the generic library icon. The icon can be specified during docset generation [as described in the section on icon specification](https://kapeli.com/docsets#addingicon) in the Docset Generation Guide.

<img width="394" alt="screen shot 2018-12-07 at 2 16 25 pm" src="https://user-images.githubusercontent.com/44085/49675619-51efae00-fa2b-11e8-878c-520e2fb310e2.png">

**Comment by chinmaygarde** [comment] 2018-12-07 22:33
Thanks for the pointer. I will patch it.

**Comment by gspencergoog** [comment] 2018-12-07 23:49
It might be a different path... I tried that, and 

`"icon32x32": "flutter.docset/flutter/static-assets/favicon.png",`

and it didn't work.  Maybe it needs to be called "icon.png"?

**Comment by gspencergoog** [comment] 2018-12-10 19:33
Actually, I think it should be what I had here:

`"icon32x32": "flutter.docset/flutter/static-assets/favicon.png",`

But I didn't see it because when I loaded up the local feed, it was pointing at the one from the website.

**Comment by xster** [comment] 2019-02-07 21:17
I think this was fixed and the PR wasn't attached at some point. 

Tentatively closing. (Though there's another regression recently #27654)

**Closed by xster** 2019-02-07 21:17 UTC
Labels: d: api docs, team
