### ISSUE TITLE
Google_maps_flutter_web marker is too big in debug

### ISSUE THREAD

**Issue by abigotado** [flutter/flutter#131869] opened 2023-08-03 17:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am facing quite the same bug as in this closed (and resolved) issue: #73789 - custom markers are too big on web.

With some remarks: in release builds markers has a proper size, everything is OK, in debug builds marker are twice bigger than estimated (and than in release).

You can use any example from this issue #73789 to reproduce.

This [answer](https://github.com/flutter/flutter/issues/73789#issuecomment-1205921567) solves the problem. But I think it should be fixed nevertheless.

### Expected results

Custom markers of the same size in release and debug builds

### Actual results

In release builds markers has a proper size, everything is OK, in debug builds marker are twice bigger than estimated (and than in release).

### Code sample

You can use any example from this issue #73789 to reproduce.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-08-04 10:03
Hi @abigotado 
I used the sample code at https://github.com/flutter/flutter/issues/73789#issuecomment-760272853, but I notice the issue appears in both debug and release mode, the marker is big.

<details>
<summary>Demo big marker</summary>

![Screenshot 2023-08-04 at 16 32 31](https://github.com/flutter/flutter/assets/104349824/0ba9f2c4-e6e4-45ab-81a6-f96e720eb1e4)


</details>

Meanwhile, the issue doesn't appear if I load the marker as following example:

<details>
<summary>Sample code of loading marker as usual</summary>

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs
// ignore_for_file: unawaited_futures

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MaterialApp(home: MarkerIconsBody()));
}

class MarkerIconsBody extends StatefulWidget {
  const MarkerIconsBody({super.key});

  @override
  State<StatefulWidget> createState() => MarkerIconsBodyState();
}

const LatLng _kMapCenter = LatLng(52.4478, -3.5402);

class MarkerIconsBodyState extends State<MarkerIconsBody> {
  GoogleMapController? controller;
  BitmapDescriptor? _markerIcon;

  @override
  Widget build(BuildContext context) {
    _createMarkerImageFromAsset(context);
    return Scaffold(
      body: GoogleMap(
        initialCameraPosition: const CameraPosition(
          target: _kMapCenter,
          zoom: 7.0,
        ),
        markers: <Marker>{_createMarker()},
        onMapCreated: _onMapCreated,
      ),
    );
  }

  Marker _createMarker() {
    if (_markerIcon != null) {
      return Marker(
        markerId: const MarkerId('marker_1'),
        position: _kMapCenter,
        icon: _markerIcon!,
      );
    } else {
      return const Marker(
        markerId: MarkerId('marker_1'),
        position: _kMapCenter,
      );
    }
  }

  Future<void> _createMarkerImageFromAsset(BuildContext context) async {
    if (_markerIcon == null) {
      final ImageConfiguration imageConfiguration = createLocalImageConfiguration(context, size: const Size.square(48));
      BitmapDescriptor.fromAssetImage(imageConfiguration, 'assets/marker.png').then(_updateBitmap);
    }
  }

  void _updateBitmap(BitmapDescriptor bitmap) {
    setState(() {
      _markerIcon = bitmap;
    });
  }

  void _onMapCreated(GoogleMapController controllerParam) {
    setState(() {
      controller = controllerParam;
    });
  }
}
```
</details>

<details>
<summary>Demo normal marker</summary>

![Screenshot 2023-08-04 at 16 19 13](https://github.com/flutter/flutter/assets/104349824/0e783629-1d3e-4982-9870-72f0476ae15b)

</details>

Are you building web in canvaskit renderer?

**Comment by abigotado** [comment] 2023-08-04 11:43
Hi @huycozy Thank you for your answer!

Yes, I am building web with canvaskit renderer.

In my case icon takes normal size in release build after deploying it to the server. If I test it locally - yes, it'll be too big in both debug and release.

And I am creating BitmapDescriptor from svg asset.

Here is SVG converter:
```dart
 import 'dart:math';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

/// Utility for converting SVG.
class SvgConverter {
  /// Converts SVG to [BitmapDescriptor].
  static Future<BitmapDescriptor> getBitmapDescriptorFromSvgAsset(
    final BuildContext context,
    final String assetName, {
    final Size size = const Size.square(64),
    final ColorMapper? colorMapper,
  }) async {
    final ui.FlutterView view = View.of(context);
    final PictureInfo pictureInfo = await vg.loadPicture(
      SvgAssetLoader(assetName, colorMapper: colorMapper),
      context,
    );

    final double devicePixelRatio = view.devicePixelRatio;
    final int width = (size.width * devicePixelRatio).toInt();
    final int height = (size.height * devicePixelRatio).toInt();

    final double scaleFactor = min(
      width / pictureInfo.size.width,
      height / pictureInfo.size.height,
    );

    final ui.PictureRecorder recorder = ui.PictureRecorder();

    ui.Canvas(recorder)
      ..scale(scaleFactor)
      ..drawPicture(pictureInfo.picture);

    final ui.Picture rasterPicture = recorder.endRecording();

    final ui.Image image = rasterPicture.toImageSync(width, height);
    final ByteData bytes =
        (await image.toByteData(format: ui.ImageByteFormat.png))!;

    return BitmapDescriptor.fromBytes(bytes.buffer.asUint8List());
  }
}
```

icon itself:
```dart
  /// Volleyball icon.
  static Future<BitmapDescriptor> volleyball(
    final BuildContext context, {
    final bool isDark = false,
  }) async =>
      SvgConverter.getBitmapDescriptorFromSvgAsset(
        context,
        'assets/icons/map_icons/volleyball.svg',
        colorMapper: isDark ? defaultColorMapper : null,
      );
```
and method for adding it:

```dart
  Future<void> _setMarkers() async {
        final BitmapDescriptor icon = await MapBitmapIcons.volleyball(
          context,
        );

          final Marker marker = Marker(
            markerId: MarkerId('marker_1'),
            position: _kMapCenter,
            icon: icon,
          );

          _markers.add(marker);
       
    if (mounted) setState(() {});
  }
```

**Comment by huycozy** [comment] 2023-08-07 04:11
Thanks for the update. But I have checked this with below updated sample code with svg file and can't see the issue. The svg file size is the same in both released/deployed web and local web. 

| release | local |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/5248ee77-57f3-4f4d-8f1f-45b874fcabd6"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/3e6b66aa-5741-4adc-a865-76aa97054296">


[volleyball.svg.zip](https://github.com/flutter/flutter/files/12271949/volleyball.svg.zip)

<details>
<summary>Complete sample code</summary>

```dart
import 'dart:math';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(
    MapsPage(),
  );
}

class MapsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MapsHome(),
    );
  }
}

class MapsHome extends StatefulWidget {
  @override
  _MapsHomeState createState() {
    return _MapsHomeState();
  }
}

class _MapsHomeState extends State<MapsHome> {
  final LatLng _kMapCenter = const LatLng(52.4478, -3.5402);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _setMarkers(),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        if (snapshot.hasData) {
          return GoogleMap(
            initialCameraPosition: CameraPosition(
              target: _kMapCenter,
              zoom: 18.0,
            ),
            markers: <Marker>{snapshot.data},
          );
        } else {
          return const Center(
            child: CircularProgressIndicator(),
          );
        }
      },
    );
  }

  Future<Marker> _setMarkers() async {
    final BitmapDescriptor icon = await volleyball(
      context,
    );
    return Marker(
      markerId: const MarkerId('marker_1'),
      position: _kMapCenter,
      icon: icon,
    );
  }

  /// Volleyball icon.
  static Future<BitmapDescriptor> volleyball(final BuildContext context) async {
    return SvgConverter.getBitmapDescriptorFromSvgAsset(
      context,
      'assets/volleyball.svg',
    );
  }
}

/// Utility for converting SVG.
class SvgConverter {
  /// Converts SVG to [BitmapDescriptor].
  static Future<BitmapDescriptor> getBitmapDescriptorFromSvgAsset(
    final BuildContext context,
    final String assetName, {
    final Size size = const Size.square(64),
    final ColorMapper? colorMapper,
  }) async {
    final ui.FlutterView view = View.of(context);
    final PictureInfo pictureInfo = await vg.loadPicture(
      SvgAssetLoader(assetName, colorMapper: colorMapper),
      context,
    );

    final double devicePixelRatio = view.devicePixelRatio;
    final int width = (size.width * devicePixelRatio).toInt();
    final int height = (size.height * devicePixelRatio).toInt();

    final double scaleFactor = min(
      width / pictureInfo.size.width,
      height / pictureInfo.size.height,
    );

    final ui.PictureRecorder recorder = ui.PictureRecorder();

    ui.Canvas(recorder)
      ..scale(scaleFactor)
      ..drawPicture(pictureInfo.picture);

    final ui.Picture rasterPicture = recorder.endRecording();

    final ui.Image image = rasterPicture.toImageSync(width, height);
    final ByteData bytes = (await image.toByteData(format: ui.ImageByteFormat.png))!;

    return BitmapDescriptor.fromBytes(bytes.buffer.asUint8List());
  }
}

```
</details>


Can you please check this sample code with my svg file? If the issue is also not reproduced, please provide your svg and complete sample code along with demo?

**Comment by abigotado** [comment] 2023-08-22 19:44
@huycozy tried your code with my svg - and it looks huge again

<img width="1325" alt="Снимок экрана 2023-08-22 в 16 34 42" src="https://github.com/flutter/flutter/assets/82471392/542b4c4d-94a3-4a9d-9d45-050935c77c06">

Here is zoom:
https://github.com/flutter/flutter/assets/82471392/172bd63d-35a1-44b3-99a3-474964dc8484

My svg:
![volleyball](https://github.com/flutter/flutter/assets/82471392/1e644cee-ccd5-46e7-ae44-73de0502bcce)

**Comment by huycozy** [comment] 2023-08-23 03:38
Thanks for the update. I check the issue with that svg file but it displays the same size (and smaller than yours) in debug/release/deployed mode. 

<details>
<summary>Demo</summary>

| debug | release | deployed |
| --------------- | --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/2bff07d5-76bd-43e3-97ef-cd0797c4d2ec"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/0dc88919-7de5-49f0-9f70-110e1f82ca6e"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/f4d10ba8-64e6-4e41-bf65-75c1802cf86a">
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (25 hours ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-9.0.pre.49, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-9.0.pre.49 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d8470f713c (62 minutes ago), 2023-08-22 19:18:00 -0700
    • Engine revision b190f90150
    • Dart version 3.2.0 (build 3.2.0-96.0.dev)
    • DevTools version 2.26.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

I'm on the latest stable 3.13.0. Can you retry and confirm on this channel as well?

**Comment by abigotado** [comment] 2023-08-24 15:52
@huycozy Thanks for your answer! Wow, that's strange, I can't understand why it is happening. I have retried - the same result 😞 . And I am on stable channel too. Here is Flutter doctor output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4.1 22F82 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Comment by huycozy** [comment] 2023-08-25 04:34
Hi, have you checked this on a newly created Flutter project? (Just to make sure there is no modification in `web` module).

If the issue still persists, can you share that project here (via GitHub or zip file) so that I can check it on my end?

**Comment by abigotado** [comment] 2023-08-30 15:26
@huycozy Hi! I tried it now on a newly created Flutter project. And it has normal size on this new project. But I wonder what could cause this on other (old) projects.

**Comment by darshankawar** [comment] 2023-09-01 06:28
Thanks for the update @abigotado and good to know it works as well at your end using new Flutter project. 


> I wonder what could cause this on other (old) projects

This would be a bit tough to pinpoint exactly as why you are seeing this on old project. Can you provide on what flutter version is your old project created ? That way we can check through release notes if we could find anything related.

**Comment by abigotado** [comment] 2023-09-01 15:09
@darshankawar Thank you for your answer! Where can I look up the info with which version the project was created? As for now, it uses the latest stable version. But I have no idea, how to find out the creation version.

**Comment by darshankawar** [comment] 2023-09-04 06:13
I don't think there's a way to check the project version, but if your project has `pubspec.lock`, then you could use it to check  the version of every package including flutter in it.
If your project is already published, then `pubspec.yaml` version could also help.

**Comment by abigotado** [comment] 2023-09-04 16:18
@darshankawar That's weird^ but I have this in `pubspec.lock`: 

```
flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
```

**Comment by huycozy** [comment] 2023-09-05 03:58
@abigotado I have the same `flutter` part info in my `pubspec.lock` file so I think it could not be related. Instead, can you back up your `web` directory (compress it or save it somewhere) then try re-generating `web` module again? (the command is: `flutter create . --platforms=web`)

It could be also appreciated if you could try with `png` marker to see if the issue is caused by `svg` format only or not.

**Comment by abigotado** [comment] 2023-09-07 21:31
@huycozy I have tested it with `png` marker and it looks ok and has correct size. So the problem occurs only with `svg`.

Here's screen with `png`:
<img width="1327" alt="Снимок экрана 2023-09-07 в 18 23 40" src="https://github.com/flutter/flutter/assets/82471392/c651f1dd-8ae5-434d-a9b6-541387a5a2fe">

I have tried to re-generate `web` directory with `flutter create . --platforms=web`. The problem persists - the marker is huge.

**Comment by huycozy** [comment] 2023-09-08 04:01
One possible clue is the difference in package/plugin version of `flutter_svg` or `google_maps_flutter`. Can you check the versions being used between the current and new project on `pubspec.lock` file?

**Comment by abigotado** [comment] 2023-09-08 22:29
`flutter_svg` new:

```
  flutter_svg:
    dependency: "direct main"
    description:
      name: flutter_svg
      sha256: "8c5d68a82add3ca76d792f058b186a0599414f279f00ece4830b9b231b570338"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.7"
```

`flutter_svg` old:

```
  flutter_svg:
    dependency: "direct main"
    description:
      name: flutter_svg
      sha256: "8c5d68a82add3ca76d792f058b186a0599414f279f00ece4830b9b231b570338"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.7"
```

`google_maps_flutter` new:

```  google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      sha256: "71b26389e86b17e2e8a8403318c92f316655f089580236892969c230013c6e38"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.1"
```

`google_maps_flutter` old:

```
  google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      sha256: c290921cd1750b5ede99c82dcaa84740da86278e6ed0f83ad29752b29a8552c6
      url: "https://pub.dev"
    source: hosted
    version: "2.4.0"
```

**Comment by huycozy** [comment] 2023-09-11 12:22
I can see `flutter_svg` versions are the same. 

`google_maps_flutter` versions are different but changes between the two versions seem unlikely to create this issue, see [changelog](https://pub.dev/packages/google_maps_flutter/changelog). 
I also think about `google_maps_flutter_web`, I used an old version. After upgrading it to the latest version, the issue is not reproducible as well. But it's worth checking this  as well on your end.

Would you mind sharing your old project code here? (Please remove unrelated packages/plugins/widgets/code... for privacy)

**Comment by abigotado** [comment] 2023-09-13 09:59
@huycozy I have updated  `google_maps_flutter_web`, as well as `google_maps_flutter`, but unfortunately I'm still facing the issue. 

Well, yes, I have specially created old testing project, which faces the problem consistently, it is minimal and I can share it: 
[untitled1.zip](https://github.com/flutter/flutter/files/12596058/untitled1.zip)

**Comment by huycozy** [comment] 2023-09-14 04:25
Strange, the issue doesn't reproduce with your sample code above. 

| My code | Your code |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/824912a7-ae73-4295-ba31-5aea172c700a"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/4f2fa66d-7a98-4219-ab56-b0c95218ebda">

I will label this issue for other's opinions. Meanwhile, can you please check plugin versions in `.pub-cache` as well?

<details>
<summary>Check plugin version in pub-cache</summary>

```console
➜  ~ cd ~/.pub-cache/hosted/pub.dev/                      
➜  pub.dev ll | grep svg
drwx------@ 15 huynq  staff   480B Aug 17 14:58 flutter_svg-1.1.6
drwx------@ 14 huynq  staff   448B Aug 11 12:28 flutter_svg-2.0.1
drwx------  14 huynq  staff   448B Aug 14 15:36 flutter_svg-2.0.5
drwx------@ 11 huynq  staff   352B Aug  8 14:37 flutter_svg-2.0.7

➜  pub.dev ll | grep maps_flutter_web
drwx------@ 10 huynq  staff   320B Aug 11 12:28 google_maps_flutter_web-0.4.0+5
drwx------@ 10 huynq  staff   320B Aug  8 14:37 google_maps_flutter_web-0.5.3
drwx------@ 10 huynq  staff   320B Sep 11 19:16 google_maps_flutter_web-0.5.4+2
```
</details>

**Comment by ditman** [comment] 2023-09-14 19:20
Sizes of the icons are sensitive to the DPR of the screen, in fact in the [svg converter](https://github.com/flutter/flutter/issues/131869#issuecomment-1665475835), the DPR is used to make the icon bigger:

```dart
    final double devicePixelRatio = view.devicePixelRatio;
    final int width = (size.width * devicePixelRatio).toInt();
    final int height = (size.height * devicePixelRatio).toInt();
```

Then when creating the bitmap descriptor, you usually needed to specify the actual physical size of the image (which the current SVG converter seems to not be doing?)

```dart
    return BitmapDescriptor.fromBytes(bytes.buffer.asUint8List());
```

Which maybe should be:

```dart
    return BitmapDescriptor.fromBytes(bytes.buffer.asUint8List(), size: size);
```

In any case, we needed this to help google maps tell apart "big markers" from "big markers that need to be rendered smaller so they look sharp on a high DPI screen".

---

The difference on sizes of the icon might be explained by:

* Different monitors (different DPIs) used when looking at debug vs prod?
* Different zoom level in the browser? (That affects DPI as well)

As for the sudden fix:

* Maybe google maps web SDK has started to default "large images" as "high DPI images"? I'm not aware of any change on their end, though :S

**Comment by abigotado** [comment] 2023-09-16 02:01
@ditman Thank you for explanation!

**Comment by ditman** [comment] 2023-09-18 23:19
@abigotado do you think we can close this issue, or is there anything that you'd have liked to find about this earlier (docs, or anything else?)

**Comment by abigotado** [comment] 2023-09-18 23:34
@ditman Yes, you could close it! Thank you very much for help!

**Comment by huycozy** [comment] 2023-09-19 01:35
Closing the issue as above comments.

**Closed by huycozy** 2023-09-19 01:35 UTC
Labels: p: maps, platform-web, package, needs repro info, team-web
