### ISSUE TITLE
Google maps permissions Android Bug

### ISSUE THREAD

**Issue by oscarshaitan** [flutter/flutter#64841] opened 2020-08-28 23:34 UTC
## Steps to Reproduce

Using the google flutter maps plugin, I'm trying to fetch my pos.
on **iOs** show the permission request just fine, but on **Android** the maps load without asking for the permission and correctly hide the my pos button.
To handle this I use `Permission_handler `plugin but this brings another issue on ios because 2 permissions request ocur at the same time.
so right now I have a `Platform.isAndroid` to request the permissions 

```
[√] Flutter (Channel dev, 1.21.0-9.0.pre, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.21.0-9.0.pre at D:\flutter
    • Framework revision 7c6f9dd239 (3 weeks ago), 2020-08-09 10:31:03 -0400
    • Engine revision 6d86e67f04
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Shaitan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    X Android SDK file not found: C:\Users\Shaitan\AppData\Local\Android\sdk\platforms\android-30\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
```

**Comment by darshankawar** [comment] 2020-08-31 06:29
Hi @oscarshaitan,
Please provide a minimal complete reproducible code sample.
Thanks.

**Comment by mihirduttaa** [comment] 2020-09-16 08:21
Permission_handler is having some issues. Google maps cannot be displayed on android platform due to this issue.

**Comment by TahaTesser** [comment] 2020-10-14 14:49
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 14:49 UTC
Labels: in triage
