### ISSUE TITLE
The size of the iOS long image is different from the actual size

### ISSUE THREAD

**Issue by wahkim** [flutter/flutter#158232] opened 2024-11-06 03:58 UTC
### Steps to reproduce

A long graph with a width of 1563 and a height of 20802 is obtained with a width of 1563 and a height of 16384.

### Expected results

Same size as the picture

### Actual results

Does not match the size of the picture

### Code sample

<details open><summary>Code sample</summary>

```dart
    Image image = Image.file(orgFile!);
    ImageStream stream = image.image.resolve(ImageConfiguration());
    stream.addListener(new ImageStreamListener((ImageInfo info, bool synchronousCall) {
      int height = info.image.height;
      int width = info.image.width;
      debugPrint('imageInfo width=$width, height=$height, synchronousCall=$synchronousCall');
    }));
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.22.2, on macOS 15.0.1 24A348 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.22.2 on channel stable at /Users/xxx/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

</details>

**Comment by huycozy** [comment] 2024-11-06 09:08
Hi @wahkim 
For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. 

Also, please share the device info (OS, model name) you are testing on. There was a similar issue that occurred on iOS 13-15 at https://github.com/flutter/flutter/issues/91685 that you can check to see if it's the same case (that issue has been responded at https://github.com/flutter/flutter/issues/91685#issuecomment-951184905)

**Comment by wahkim** [comment] 2024-11-06 09:33
1. Code examples are provided above
2. device:
    iphone 8plus, system version 14.6
    iphone 13 , system version 18.0
3. It should be the same problem as #91685, but I don't see a solution

**Comment by jonahwilliams** [comment] 2024-11-06 15:37
20802 is larger than that devices maximum texture size, so flutter is unable to create a texture bigger than that.

**Comment by wahkim** [comment] 2024-11-07 01:37
> 20802 is larger than that devices maximum texture size, so flutter is unable to create a texture bigger than that.

I see that the height of the picture taken on Android is also 16384, but the width is 1231, why on iOS only changed the height and width did not change, why not do the same for Android?

**Comment by huycozy** [comment] 2024-11-07 07:47
>iphone 8plus, system version 14.6
iphone 13 , system version 18.0

Per https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf:

- iPhone 8 Plus: Chip A11 Bionic > Apple4 GPU family, Maximum 2D texture width and height: 16,384 px
- iPhone 13: Chip A15 Bionic > Apple8 GPU family, Maximum 2D texture width and height: 16,384 px

>I see that the height of the picture taken on Android is also 16384, but the width is 1231, why on iOS only changed the height and width did not change, why not do the same for Android?

Per https://github.com/flutter/flutter/issues/91685 conclusion, it's working as intended so I am going to close the issue as a duplicate. If you disagree, please write in the comments and I will reopen it.

**Closed by huycozy** 2024-11-07 07:47 UTC
Labels: in triage

**Comment by wahkim** [comment] 2024-11-07 08:08
> > iphone 8plus, system version 14.6
> > iphone 13 , system version 18.0
> 
> Per https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf:
> 
> * iPhone 8 Plus: Chip A11 Bionic > Apple4 GPU family, Maximum 2D texture width and height: 16,384 px
> * iPhone 13: Chip A15 Bionic > Apple8 GPU family, Maximum 2D texture width and height: 16,384 px
> 
> > I see that the height of the picture taken on Android is also 16384, but the width is 1231, why on iOS only changed the height and width did not change, why not do the same for Android?
> 
> Per #91685 conclusion, it's working as intended so I am going to close the issue as a duplicate. If you disagree, please write in the comments and I will reopen it.

Can you do the same thing with Android?

**Comment by huycozy** [comment] 2024-11-08 03:57
No unfortunately, please check https://github.com/flutter/flutter/issues/91685#issuecomment-951184905 again: "_...This probably deserves a more detailed API design._"
