### ISSUE TITLE
[Camera] One back camera received instead of 3 with availableCameras() and iPhone 11

### ISSUE THREAD

**Issue by gyihasz** [flutter/flutter#96589] opened 2022-01-13 12:44 UTC
An [issue opened by iNima](https://github.com/flutter/flutter/issues/59964) 1.5 years ago describes it all.
The getAvailableCameras only returns 2 cameras in the case of an iPhone 11, which has 3 cameras. One on the back and one on the front.

For me it looks like iNima also found the root of the problem, however, the issue still persists so I'm not sure why it got closed.

The original issue opened is #59964

Sorry for the duplicate, but I think the issue still persists and I believe it was closed by accident.

It would be really nice to use the Telephoto, Wide, and Ultra Wide cameras as well.

Camera version: 0.9.4+5

**Comment by darshankawar** [comment] 2022-01-13 13:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/80865

**Closed by darshankawar** 2022-01-13 13:19 UTC
Labels: in triage
