### ISSUE TITLE
ImageFilter.compose crashes the app

### ISSUE THREAD

**Issue by X-Wei** [flutter/flutter#105461] opened 2022-06-06 19:25 UTC
## Steps to Reproduce

https://dartpad.dev/?id=a39eeefa873b62f63e4f3516c2d04b09

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ImageFiltered(
      // ❌️❌️ blur then rotate - CRASH?? (console says "script error") ❌️❌️
      imageFilter: ImageFilter.compose(
        outer: ImageFilter.matrix(Matrix4.rotationZ(0.1).storage),
        inner: ImageFilter.blur(sigmaX: 2, sigmaY: 3),
      ),
      // ✅️ only rotation - OK
      // imageFilter: ImageFilter.matrix(Matrix4.rotationZ(0.1).storage),
      // ✅️ only blur - OK
      // imageFilter: ImageFilter.blur(sigmaX: 2, sigmaY: 3),
      child:Text(
      'Hello, World!',
      style: Theme.of(context).textTheme.headline4,
    ),);
  }
}
```

</details>

<details>
  <summary>Logs</summary>

I don't see any logs in the console, the app crashes directly, I only see "Lost connection to device.".
 
On dartpad, the console prints "script error" and nothing more.

```
```

```
```

</details>

(First reported in https://github.com/X-Wei/flutter_catalog/issues/131)

**Comment by sanjidbillah** [comment] 2022-06-07 05:48
What is your flutter version?
I have no issue with this code .
I use flutter 3.0.1

**Comment by exaby73** [comment] 2022-06-07 07:25
Hi @X-Wei. `Image.compose` is not implemented for web. If you run the code example you provided on your local environment on chrome, you will get the following logs:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnimplementedError was thrown building MyWidget(dirty):
ImageFilter.compose not implemented for web platform.
```

If you want to request for this to be implemented, please file another issue as a feature request. I'm closing this since this is not a bug in Flutter.

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.1 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1139, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1139 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ab56de808 (66 minutes ago), 2022-06-07 02:18:05 -0400
    • Engine revision 5797ecf2fb
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Closed by exaby73** 2022-06-07 07:25 UTC
Labels: in triage
