### ISSUE TITLE
WASM support for Flutter for dart2js

### ISSUE THREAD

**Issue by imdigitalashish** [flutter/flutter#69292] opened 2020-10-29 10:09 UTC
Hey there are many articles saying that wasm is faster than anything on the web

What if Flutter dart compile to wasm ( web assembly ) instead of Dart2js.. Because if it does... Then the flutter website will be faster than react vue or any other javascript framework

PLEASE REPLY IF THERE IS ANY ISSUE WITH WASM

**Comment by darshankawar** [comment] 2020-10-29 10:19
Closing this as duplicate of [41062](https://github.com/flutter/flutter/issues/41062)

**Closed by darshankawar** 2020-10-29 10:19 UTC

**Comment by iapicca** [comment] 2021-04-01 06:40
see also 
possibly a duplicate of  https://github.com/flutter/flutter/issues/41062
