### ISSUE TITLE
Module 'flutter_native_splash' not found

### ISSUE THREAD

**Issue by zeeshan-rsys** [flutter/flutter#114020] opened 2022-10-25 15:14 UTC
<img width="800" alt="Screenshot 2022-10-25 at 8 39 37 PM" src="https://user-images.githubusercontent.com/101088061/197812829-57299c3c-624e-45b8-865b-67a3011c5065.png">

<details>
  <summary>Logs</summary>

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.5 21G72 darwin-arm, locale en-IN)
    • Flutter version 3.3.5 on channel stable at /Users/radiansys/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (6 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/radiansys/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Users/radiansys/Downloads/Xcode.app/Contents/Developer
    • Build 13F17a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 3D524B95-EE05-45B1-8269-9C87F3A95CD9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5 21G72
      darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2022-10-26 09:24
@zeeshan-rsys 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/jonbhanson/flutter_native_splash/issues).
Closing, as this isn't an issue with Flutter itself.  

If you disagree, please write in the comments, providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not use 3rd party plugins and I will reopen it.

Thank you!

**Closed by huycozy** 2022-10-26 09:24 UTC
Labels: in triage
