### ISSUE TITLE
ElevatedButton looks bad on the Web.

### ISSUE THREAD

**Issue by GrzegorzDyrda** [flutter/flutter#98083] opened 2022-02-09 01:10 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample (see "Code sample" section below).

**Expected results:**

Mobile and Web versions should look the same.

**Actual results:**

Web version looks wrong. Both internal and external paddings are incorrect. The font also seems to be too large?

<details>
<summary>Code sample</summary>

```dart
void main() {
  runApp(
    MaterialApp(
      home: SafeArea(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () {},
              child: const Text('LOREM IPSUM'),
            ),
            ElevatedButton(
              onPressed: () {},
              child: const Text('DOLOR SIT'),
            ),
          ],
        ),
      ),
    ),
  );
}
```

</details>

<details>
  <summary>Logs</summary>

```
$ flutter --version
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (8 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

</details>

Attached screenshots (dark background is Android, white is the Web version).

![Screenshot_1644367304](https://user-images.githubusercontent.com/13047856/153101985-7173da73-baff-4c40-9eaa-501544d0fe66.png)

![localhost_49294_(Pixel 5)](https://user-images.githubusercontent.com/13047856/153101998-c703db9f-62d5-4528-aeec-449ec4af43e5.png)

**Comment by GrzegorzDyrda** [comment] 2022-02-09 01:27
I just upgraded to Flutter 2.10.0. The bug still exists.

**Comment by bernaferrari** [comment] 2022-02-09 01:46
Duplicated of https://github.com/flutter/flutter/issues/85729 https://github.com/flutter/flutter/issues/87780 https://github.com/flutter/flutter/issues/96995

It is correct, you are using it wrong. You should change `visualDensity: VisualDensity.standard` or materialTapTarget.

**Comment by danagbemava-nc** [comment] 2022-02-09 09:50
Closing as duplicate of https://github.com/flutter/flutter/issues/85729. Kindly see https://github.com/flutter/flutter/issues/85729#issuecomment-878640953 for more information.

**Closed by danagbemava-nc** 2022-02-09 09:50 UTC
Labels: in triage
