### ISSUE TITLE
[Windows] After FlutterWnd is hidden and reshown, the FlutterViewController becomes 'blank'

### ISSUE THREAD

**Issue by Taijuk** [flutter/flutter#101339] opened 2022-04-05 07:56 UTC
Using Flutter on Windows Devices, if the FlutterWnd is hidden and then reshown, the FlutterViewController will be blank. The Widgets won't be drawn until we trigger the update manually.
The bug as shown in the video:

https://user-images.githubusercontent.com/3714809/161705869-82da5cd4-6faa-40e6-a2fe-8194f08ec411.mp4

-----

## Steps to Reproduce

1. Create a Windows demo
2. Copy and paste 'Code Sample' into main.cpp
3. flutter run
4. The  window will be displayed after the Demo started, and it will hidden after 13 seconds.
5. At then it will be reshown agin, but the FlutterViewController will be 'blank'.

**Expected results:** 
The FlutterViewController should draw the Widgets.

**Actual results:**
Only blank page.

<details>
<summary>Code sample</summary>

```
#include <flutter/dart_project.h>
#include <flutter/flutter_view_controller.h>
#include <windows.h>

#include "flutter_window.h"
#include "utils.h"

#include <Windows.h>
#include <iostream>

static HWND sFlutterWnd = nullptr;
static void CALLBACK HideTimerProc(HWND hwnd, UINT nMsg, UINT_PTR nTimerId, DWORD dwTime)
{
    std::cout << "HideTimeProc fired" << std::endl;
    ::ShowWindow(sFlutterWnd, SW_HIDE);
    ::KillTimer(sFlutterWnd, 1);
}
static void CALLBACK ShowTimerProc(HWND hwnd, UINT nMsg, UINT_PTR nTimerId, DWORD dwTime)
{
    std::cout << "ShowTimeProc fired" << std::endl;
    ::ShowWindow(sFlutterWnd, SW_SHOWNORMAL);
    ::KillTimer(sFlutterWnd, 2);
}


int APIENTRY wWinMain(_In_ HINSTANCE instance, _In_opt_ HINSTANCE prev,
                      _In_ wchar_t *command_line, _In_ int show_command) {
    // Attach to console when present (e.g., 'flutter run') or create a
    // new console when running with a debugger.
    if (!::AttachConsole(ATTACH_PARENT_PROCESS) && ::IsDebuggerPresent()) {
        CreateAndAttachConsole();
    }
    
    // Initialize COM, so that it is available for use in the library and/or
    // plugins.
    ::CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
    
    flutter::DartProject project(L"data");
    
    std::vector<std::string> command_line_arguments =
        GetCommandLineArguments();
    
    project.set_dart_entrypoint_arguments(std::move(command_line_arguments));
    
    FlutterWindow window(project);
    Win32Window::Point origin(10, 10);
    Win32Window::Size size(1280, 720);
    if (!window.CreateAndShow(L"example", origin, size)) {
        return EXIT_FAILURE;
    }
    window.SetQuitOnClose(true);
    
    sFlutterWnd = window.GetHandle();
    // hide
    SetTimer(sFlutterWnd, 1, 13 * 1000, HideTimerProc);
    // show
    SetTimer(sFlutterWnd, 2, 15 * 1000, ShowTimerProc);
    
    ::MSG msg;
    while (::GetMessage(&msg, nullptr, 0, 0)) {
        ::TranslateMessage(&msg);
        ::DispatchMessage(&msg);
    }
    
    ::CoUninitialize();
    return EXIT_SUCCESS;
}
```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.4-0.0.pre.1, on Microsoft Windows [Version 10.0.19042.1586], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)[√] Android Studio (version 2020.3)
[√] VS Code (version 1.66.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

```

</details>

**Comment by maheshmnj** [comment] 2022-04-05 12:23
Hi @Taijuk, thanks for filing the issue. Can you please recheck the code sample in the `main.cpp`? The editor seems to complain

```
argument of type "void (__stdcall *)(HWND hwnd, UINT nMsg, UINT nTimerId, DWORD dwTime)" is incompatible with parameter of type "TIMERPROC"C/C++(
```

and the build fails with error 

```error
Launching lib\main.dart on Windows in debug mode...
C:\Users\mahesh\Downloads\crash_repro\windows\runner\main.cpp(55,54): error C2664: 'UINT_PTR SetTimer(HWND,UINT_PTR,UINT,TIMERPROC)': cannot convert argument 4 from 'void (__cdecl *)(HWND,UINT,UINT,DWORD)' to 'TIMERPROC' [C:\Users\mahesh\Downloads\crash_repro\build\windows\runner\crash_repro.vcxproj]
C:\Users\mahesh\Downloads\crash_repro\windows\runner\main.cpp(57,54): error C2664: 'UINT_PTR SetTimer(HWND,UINT_PTR,UINT,TIMERPROC)': cannot convert argument 4 from 'void (__cdecl *)(HWND,UINT,UINT,DWORD)' to 'TIMERPROC' [C:\Users\mahesh\Downloads\crash_repro\build\windows\runner\crash_repro.vcxproj]
Exception: Build process failed.
Exited (sigterm)

```  

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586],
    locale en-US)
    • Flutter version 2.10.4 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.82      
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.30     

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Taijuk** [comment] 2022-04-06 01:08
> Hi @Taijuk, thanks for filing the issue. Can you please recheck the code sample in the `main.cpp`? The editor seems to complain
> 
> ```
> argument of type "void (__stdcall *)(HWND hwnd, UINT nMsg, UINT nTimerId, DWORD dwTime)" is incompatible with parameter of type "TIMERPROC"C/C++(
> ```
> 
> and the build fails with error
> 
> ```
> Launching lib\main.dart on Windows in debug mode...
> C:\Users\mahesh\Downloads\crash_repro\windows\runner\main.cpp(55,54): error C2664: 'UINT_PTR SetTimer(HWND,UINT_PTR,UINT,TIMERPROC)': cannot convert argument 4 from 'void (__cdecl *)(HWND,UINT,UINT,DWORD)' to 'TIMERPROC' [C:\Users\mahesh\Downloads\crash_repro\build\windows\runner\crash_repro.vcxproj]
> C:\Users\mahesh\Downloads\crash_repro\windows\runner\main.cpp(57,54): error C2664: 'UINT_PTR SetTimer(HWND,UINT_PTR,UINT,TIMERPROC)': cannot convert argument 4 from 'void (__cdecl *)(HWND,UINT,UINT,DWORD)' to 'TIMERPROC' [C:\Users\mahesh\Downloads\crash_repro\build\windows\runner\crash_repro.vcxproj]
> Exception: Build process failed.
> Exited (sigterm)
> ```
> 
> flutter doctor -v (windows)

@maheshmnj  Sorry my bad. I have updated the 'main.cpp', please try again.

**Comment by maheshmnj** [comment] 2022-04-06 05:23
Thanks for the update @Taijuk, I tried your reproducible steps with the updated code sample, But I was not able to reproduce the issue on the latest stable version of flutter `2.10.4`. The app worked normally when the window was hidden and shown.

https://user-images.githubusercontent.com/31410839/161901310-994ff2ff-8c36-403d-a7c5-02cfe0426b34.mp4

Also looking at your flutter doctor `Channel stable, 2.10.4-0.0.pre.1` this doesn't seem to be the official flutter version.

Can you please share the complete output of `flutter doctor -v`?

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586],
    locale en-US)
    • Flutter version 2.10.4 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.82      
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.30     

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Taijuk** [comment] 2022-04-08 07:42
> Thanks for the update @Taijuk, I tried your reproducible steps with the updated code sample, But I was not able to reproduce the issue on the latest stable version of flutter `2.10.4`. The app worked normally when the window was hidden and shown.
> 
>  2022-04-06.05-13-48_Trim.mp4 
> Also looking at your flutter doctor `Channel stable, 2.10.4-0.0.pre.1` this doesn't seem to be the official flutter version.
> 
> Can you please share the complete output of `flutter doctor -v`?
> 
> flutter doctor -v (windows)

Hi @maheshmnj, I have recheck my flutter version, it seems like I have a locally compiled version. But after switch to Channel stable, the issue still exists.

https://user-images.githubusercontent.com/3714809/162387202-01e0ad62-7f6f-4350-8ef0-086d0675ebad.mp4

My flutter doctor -v

`
[√] Flutter (Channel github/stable, 2.10.4, on Microsoft Windows [Version 10.0.19042.1586], locale zh-CN)
    • Flutter version 2.10.4 at D:\work\flutter\flutter
    • Upstream repository remotes
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\nuliang\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32126.315
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.66.0)
    • VS Code at C:\Users\nuliang\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.29

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
`

The reason why you can not reproduce this issue, I think it may have somethin to do with the state of Flutter widgets. Would you try keep the 'demo' and 'mouse cursor' stable during the test, it may help reproduce the issue.

**Comment by maheshmnj** [comment] 2022-04-08 10:15
Thanks for the update @Taijuk, I tried not to move the mouse or press any keys and I am still not able to reproduce it. Can you try running flutter counter app instead and see if it makes any difference (It shouldn;t though).


https://user-images.githubusercontent.com/31410839/162415865-6cba2434-72a2-451a-9656-32d5176a1e8b.mp4

 
<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586],
    locale en-US)
    • Flutter version 2.10.4 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.82      
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.30     

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Taijuk** [comment] 2022-04-10 07:19
> Thanks for the update @Taijuk, I tried not to move the mouse or press any keys and I am still not able to reproduce it. Can you try running flutter counter app instead and see if it makes any difference (It shouldn;t though).
> 
>  2022-04-08.10-09-19_Trim.mp4 
> Also are you seeing this issue in any specific mode (debug/profile/release) or all modes?
> 
> flutter doctor -v (windows)

Hi @maheshmnj ,thiks for the reminding. It's true that I can't reproduce this issue either with `Counter App`. 
But if I remove the `_MyHomePageState`'s `floatingActionButton`(comment out lines 110 to 114), the  bug reshown again. I don't known why😂

**Comment by maheshmnj** [comment] 2022-04-11 06:02
@Taijuk  that's strange :), Can you please share the reproducible dart code?

**Comment by Taijuk** [comment] 2022-04-11 07:49
> @Taijuk that's strange :), Can you please share the reproducible dart code?

@maheshmnj OK, please replace the `main.dart` with this one:
[main.zip](https://github.com/flutter/flutter/files/8462042/main.zip)

**Comment by maheshmnj** [comment] 2022-04-11 13:41
Thanks for the reproducible code @Taijuk, I am able to reproduce the issue on stable and the master channel.  The app goes blank when the window is hidden and reshown. Strangely the issue doesn't reproduce if the floating action button is present in the below code sample, same can be seen in the  [above output](https://github.com/flutter/flutter/issues/101339#issuecomment-1092705036)

https://user-images.githubusercontent.com/31410839/162751811-8061f0ed-3634-4eb7-ad99-7c65bd0ff603.mp4

### Steps to reproduce 
- Replace the code sample in `main.dart` and `main.cpp` with the below code sample
- Run the app

<details>
<summary>code sample</summary>

`windows/runner/main.cpp`
```cpp
#include <flutter/dart_project.h>
#include <flutter/flutter_view_controller.h>
#include <windows.h>

#include "flutter_window.h"
#include "utils.h"

#include <Windows.h>
#include <iostream>

static HWND sFlutterWnd = nullptr;
static void CALLBACK HideTimerProc(HWND hwnd, UINT nMsg, UINT_PTR nTimerId, DWORD dwTime)
{
    std::cout << "HideTimeProc fired" << std::endl;
    ::ShowWindow(sFlutterWnd, SW_HIDE);
    ::KillTimer(sFlutterWnd, 1);
}
static void CALLBACK ShowTimerProc(HWND hwnd, UINT nMsg, UINT_PTR nTimerId, DWORD dwTime)
{
    std::cout << "ShowTimeProc fired" << std::endl;
    ::ShowWindow(sFlutterWnd, SW_SHOWNORMAL);
    ::KillTimer(sFlutterWnd, 2);
}


int APIENTRY wWinMain(_In_ HINSTANCE instance, _In_opt_ HINSTANCE prev,
                      _In_ wchar_t *command_line, _In_ int show_command) {
    // Attach to console when present (e.g., 'flutter run') or create a
    // new console when running with a debugger.
    if (!::AttachConsole(ATTACH_PARENT_PROCESS) && ::IsDebuggerPresent()) {
        CreateAndAttachConsole();
    }
    
    // Initialize COM, so that it is available for use in the library and/or
    // plugins.
    ::CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
    
    flutter::DartProject project(L"data");
    
    std::vector<std::string> command_line_arguments =
        GetCommandLineArguments();
    
    project.set_dart_entrypoint_arguments(std::move(command_line_arguments));
    
    FlutterWindow window(project);
    Win32Window::Point origin(10, 10);
    Win32Window::Size size(1280, 720);
    if (!window.CreateAndShow(L"example", origin, size)) {
        return EXIT_FAILURE;
    }
    window.SetQuitOnClose(true);
    
    sFlutterWnd = window.GetHandle();
    // hide
    SetTimer(sFlutterWnd, 1, 13 * 1000, HideTimerProc);
    // show
    SetTimer(sFlutterWnd, 2, 15 * 1000, ShowTimerProc);
    
    ::MSG msg;
    while (::GetMessage(&msg, nullptr, 0, 0)) {
        ::TranslateMessage(&msg);
        ::DispatchMessage(&msg);
    }
    
    ::CoUninitialize();
    return EXIT_SUCCESS;
}
```

`main.dart`
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    //return Container(color: Colors.red,);
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      // floatingActionButton: FloatingActionButton(
      //   onPressed: _incrementCounter,
      //   tooltip: 'Increment',
      //   child: const Icon(Icons.add),
      // ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```
</details>


### logs

```
Launching lib\main.dart on Windows in debug mode...
Connecting to VM Service at ws://127.0.0.1:52102/OhMwrAuhEV0=/ws
HideTimeProc fired
ShowTimeProc fired
Lost connection to device.
Exited (sigterm)
```

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586],
    locale en-US)
    • Flutter version 2.10.4 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.82      
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.30     

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[√] Flutter (Channel master, 2.13.0-0.0.pre.391, on Microsoft Windows [Version
    10.0.19044.1586], locale en-US)
    • Flutter version 2.13.0-0.0.pre.391 at C:\flutter_sdk\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 08c46bcb58 (5 days ago), 2022-04-05 22:24:05 -0400   
    • Engine revision 45bedbe841
    • Dart version 2.17.0 (build 2.17.0-266.0.dev)
    • DevTools version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code    
    • Flutter extension version 3.38.1

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows
      [Version 10.0.19044.1586]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome    
      100.0.4896.75
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge
      99.0.1150.30

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by gspencergoog** [comment] 2022-04-14 18:14
I think adding the FAB helps because it has an animation associated with it.

Probably we're missing a place where we pump a frame when the window is shown.

**Comment by FusoraTech** [comment] 2022-04-18 15:54
Seems like a full repaint is missing when a window comes from some hidden state to a shown state.

**Comment by sevenstars** [comment] 2022-06-26 17:00
> 

I found that when the content is static, both the framework and engine will not trigger a new frame in these user cases, e.g., hide/show the app window.
I have created a PR, maybe you can take a look and see if it's the right approach to fix this.

**Comment by sevenstars** [comment] 2022-06-26 17:11
This PR https://github.com/flutter/engine/pull/34306 will also fix a similar issue on Windows 7   https://github.com/flutter/flutter/issues/102030
cc @maheshmnj

**Comment by loic-sharma** [comment] 2022-07-13 18:29
This should be addressed in the next Flutter release by https://github.com/flutter/engine/pull/34306

**Closed by loic-sharma** 2022-07-13 18:29 UTC
Labels: engine, platform-windows, a: desktop, has reproducible steps, P4, found in release: 2.10, found in release: 2.13
