### ISSUE TITLE
Error trying to accept licenses on jdk 15

### ISSUE THREAD

**Issue by BrayanBertan** [flutter/flutter#77019] opened 2021-03-01 23:27 UTC
I was using jdk 15 without any problems but after installing docker and run a flutter application inside a container using adb i start getting errors first all the code of the application i ran on container is red and the flutter doctor shows a warning asking to accept licenses again but if i try do that with jdk 15 i get the error in the screenshot below, but if i change to jdk 8 i can  accept the licenses without any problem.

https://user-images.githubusercontent.com/25934199/109572341-cf4fdf00-7acb-11eb-9f94-6010ed92df43.jpeg

**Comment by darshankawar** [comment] 2021-03-02 08:20
@BrayanBertan 
Check out [this](https://github.com/flutter/flutter/issues/56778) similar issue and underlying comments and see if any of the workarounds help.
Closing this as duplicate of https://github.com/flutter/flutter/issues/56778

**Closed by darshankawar** 2021-03-02 08:20 UTC
Labels: in triage
