### ISSUE TITLE
Navigation 2.0 RouterDelegate Build method called twice at the start of the app

### ISSUE THREAD

**Issue by franarolas** [flutter/flutter#71272] opened 2020-11-26 12:04 UTC
I implemented the Navigation 2.0 which works fine, but the Build method of the RouterDelegate class is called twice, which makes the app to have an unexpected behaviour because all the initial operations of the pages are called twice.

Tested in Android and Flutter Web, same result.

## Steps to Reproduce

1. Create a Flutter project with the complete example code: [Example](https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade), or clone the following github repository: [Github example](https://github.com/franarolas/navigation20_test)(Code imported from the given example at [Flutter docs](https://flutter.dev/docs/development/ui/navigation))
2. Add debugPrints at the lines 26(Inside AppState build method) and 99(Inside RouterDelegate build method).
3. Run the app

**Expected results:** The debug prints should be wrote once each.

**Actual results:** The debug print at line 99 is printed twice.

<details>
  <summary>Flutter doctor</summary>
```

[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [VersiÃ³n 10.0.19042.630], locale es-ES)
    • Flutter version 1.24.0-10.2.pre at C:\flutter
    • Framework revision 022b333a08 (8 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\F-Laptop\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[√] VS Code, 64-bit edition (version 1.42.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.56

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2020-11-26 12:21
Hi @franarolas 
Can you please provide a minimal complete reproducible code sample that reproduces the problem? The link above points to a blog post not to a sample code.
Thank you

**Comment by franarolas** [comment] 2020-11-26 12:40
> 
> 
> Hi @franarolas
> Can you please provide a minimal complete reproducible code sample that reproduces the problem? The link above points to a blog post not to a sample code.
> Thank you

Edited.

**Comment by pedromassangocode** [comment] 2020-11-26 13:51
```
Running "flutter pub get" in flutter_example...
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
I/flutter_exampl( 4966): Not late-enabling -Xcheck:jni (already on)
I/flutter_exampl( 4966): Unquickening 12 vdex files!
W/flutter_exampl( 4966): Unexpected CPU variant for X86 using defaults: x86
W/flutter_exampl( 4966): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/flutter_exampl( 4966): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_exampl( 4966): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/flutter_exampl( 4966): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
Waiting for sdk gphone x86 arm to report its views...
Debug service listening on ws://127.0.0.1:51528/0-B5HKZqiZA=/ws
Syncing files to device sdk gphone x86 arm...
I/flutter ( 4966): Called app state build method
I/flutter ( 4966): Called router delegate build method
I/flutter ( 4966): Called router delegate build method
```

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-10.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 022b333a08 (8 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!

```
</details>

**Comment by franarolas** [comment] 2020-11-28 14:08
If anyone else is encountering this issue, you can make a workaround just adding this inside the build method:
`
    if(lastPathBuilt == currentPath && lastLanguageBuilt == Localizations.localeOf(context).languageCode)
      currentPath.loadInitialValues = false;
    else {
      currentPath.loadInitialValues = true;
      lastLanguageBuilt = Localizations.localeOf(context).languageCode;
      lastPathBuilt = currentPath;
    }`

And then check the boolean variable inside your initial page.
Everything is still builded twice but you can check if you need to get the initial values or not.
I hope it helps someone.

**Comment by chunhtai** [comment] 2020-11-30 18:45
We should looking into it, but the build method should not have any side effect. We do not guarantee the build method will only be called once per rebuild.

**Comment by franarolas** [comment] 2020-12-02 10:54
> 
> 
> We should looking into it, but the build method should not have any side effect. We do not guarantee the build method will only be called once per rebuild.

Well, in that case, how should we load the initial values? Imagine that I request some data to my api at the first load of home page and different data at the products page, I can't find a proper way to not be sending petitions to api multiple times.

**Comment by pedromassangocode** [comment] 2020-12-02 11:27
> Well, in that case, how should we load the initial values?

You may want to invoke your API in the `initState()` of your page instead of `build()` method.

**Comment by chunhtai** [comment] 2020-12-02 17:04
@franarolas RouterDelegate.setNewRoutePath is expecting a future, you can load the initial data in that method before returning the future.

**Comment by franarolas** [comment] 2020-12-03 00:50
@chunhtai 
setNewRoutePath is only called the first time that you enter the app, so it would only work if I want to load all the initial values of all pages at once which I don't think is the right method, anyways could be an option.

@pedromassangocode 
That is the first thing I thought(and I ended up doing), but it is not that easy as it creates other problems, let me explain myself...

I had all my initial pages Stateless and being controlled by blocs so I turned all of them to stateful, initialized the blocs at the state constructor and loaded the initial values at the initState.
That created another problem, the language of the app, my app currently supports 4 languages and you can switch between them in realtime.
I was changing it with a Global bloc which was rebuilding the MaterialApp when the language was changed, so even the material and cupertino widgets were changing the language, but now it was not loading the initial values of the new language, because the initState method is only called once.
After thinking a bit about it, I tought that the only solution here is to navigate to a new page when the language is changed(Like a normal website) with the new navigation, it works like a charm.
After some modifications in the RouterDelegate extension class I can now navigate to mywebsite.com/#/en/xxx or mywebsite.com/#/es/xxx and it perfectly recognizes the language and the desired path.

I hope I explained myself and maybe my workaround can help someone.
Thank you for your help.

**Comment by chunhtai** [comment] 2020-12-03 01:00
There is a didChangeDependencies you can use if your page depends on inherited widget. I assume the bloc uses inherited widget underneath, the didChangeDependencies will be called when the inherited widget has changed.

**Comment by franarolas** [comment] 2020-12-03 19:37
> 
> 
> There is a didChangeDependencies you can use if your page depends on inherited widget. I assume the bloc uses inherited widget underneath, the didChangeDependencies will be called when the inherited widget has changed.

When is didChangeDependencies exactly called?

**Comment by chunhtai** [comment] 2020-12-03 21:06
this should be a flutter bloc question.

I took a quick peek at their code, it looks like BlocProvider uses Provider which underneath uses inheritedwidget. I think didChangeDependencies should be called on widget first build and when the bloc has need update.

**Comment by chunhtai** [comment] 2020-12-30 22:38
The double builds are expected if the parseRouteInformation and setNewRoutePath return non synchronousFuture. The first build is called before the future resolve and the second build is called after the future is resolved. Closing this issue as WAI

**Closed by chunhtai** 2020-12-30 22:38 UTC
Labels: f: routes, found in release: 1.22, found in release: 1.23, found in release: 1.24, framework, has reproducible steps
