### ISSUE TITLE
Flutter web DatePicker error previous/next button with semantics 

### ISSUE THREAD

**Issue by k-bello** [flutter/flutter#158669] opened 2024-11-13 15:46 UTC
### Steps to reproduce

1. add SemanticsBinding.instance.ensureSemantics();
2. with showDatePicker open the date picker dialog
3. click sometimes on previous button to switch month 
4. move between previous and next month button and click on next month

### Expected results

I expect the button with the focus to be clicked

### Actual results

several times also if focus is on next button, the click started from the previous button , if I delete   SemanticsBinding.instance.ensureSemantics();
everything works 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SemanticsBinding.instance.ensureSemantics();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: false,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    showDatePicker(
        initialEntryMode: DatePickerEntryMode.calendarOnly,
        context: context,
        barrierDismissible: false,
        firstDate: DateTime(1990),
        lastDate: DateTime.now(),
        initialDate: DateTime.now());
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/166a8d6b-a5b2-4f7c-b88c-facfdd310ed1

</details>

### Logs

<details open><summary>Logs</summary>

```console
meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">
flutter_bootstrap.js:3 Installing/Activating first service worker.
flutter_bootstrap.js:3 Activated new service worker.
flutter_bootstrap.js:1 Injecting <script> tag. Using callback.
 This app is linked to the debug service: ws://127.0.0.1:57965/xLfannPZoMM=/ws
5[Violation] 'requestAnimationFrame' handler took <N>ms
js_allow_interop_patch.dart:81 [Violation] 'requestAnimationFrame' handler took 50ms
js_allow_interop_patch.dart:81 [Violation] 'requestAnimationFrame' handler took 51ms
js_allow_interop_patch.dart:81 [Violation] 'requestAnimationFrame' handler took 55ms
js_allow_interop_patch.dart:81 [Violation] 'requestAnimationFrame' handler took 54ms
js_allow_interop_patch.dart:81 [Violation] 'requestAnimationFrame' handler took 51ms
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale it-IT)
    • Flutter version 3.24.4 on channel stable at /Users/kris/Desktop/Projects/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (3 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

```

</details>

**Comment by danagbemava-nc** [comment] 2024-11-14 07:52
Hi @k-bello, it seems like this might have been fixed on the master channel (or the rate of reproduction has reduced). Can you check on the master channel to see if you still experience this issue? 

https://github.com/user-attachments/assets/939bdae2-c7eb-46f4-91c7-b3de5f3007ec

**Comment by k-bello** [comment] 2024-11-14 08:33
I've just tryed and I confirm that in master it works 

When it will release in the stable channel ? 

 Flutter (Channel master, 3.27.0-1.0.pre.492, on macOS 15.1 24B83 darwin-arm64, locale it-IT)
    • Flutter version 3.27.0-1.0.pre.492 on channel master at /Users/kris/Desktop/Projects/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c1ee381b18 (9 minutes ago), 2024-11-14 16:14:17 +0800
    • Engine revision 619804c0fb
    • Dart version 3.7.0 (build 3.7.0-140.0.dev)
    • DevTools version 2.41.0-dev.2

https://github.com/user-attachments/assets/5c9ab833-2dd5-4b9e-8055-e35f0dc1c079

**Comment by danagbemava-nc** [comment] 2024-11-15 06:14
Hi @k-bello, I just checked the latest beta (3.27.0-0.2.pre) and the fix is in there, so this should be available whenever the next stable version is released. 

Per our triage policy, I'll be closing this since it has already been fixed on the newer channels. 

Thank you

**Closed by danagbemava-nc** 2024-11-15 06:14 UTC
Labels: in triage
