### ISSUE TITLE
Android image upload through WebView (`flutter_webview_plugin`)

### ISSUE THREAD

**Issue by vascoV** [flutter/flutter#17567] opened 2018-05-14 12:26 UTC
I have a backend which is loaded on the mobile as full-screen WebView. On the webview I am able to upload a photo either from the gallery or capturing a photo now, however, I am getting an issue on the android devices I can upload either from gallery or take a photo.

+ I tried adding the permissions and ask for them before launching the webview but still got the same issue, on IOS is working fine. 

+ For permission I am using the `simple_permissions: "^0.1.4"

+ For the we view plugin I am using ` flutter_webview_plugin: ^0.1.5

Here is my Flutter doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.3.5, on Mac OS X 10.13.4 17E202, locale en-CY)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.21.1)
[!] VS Code (version 1.23.1)
[✓] Connected devices (3 available)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment] 2018-05-14 12:50
> I am getting an issue

Is there any additional information about your issue? I wasn't able to derive more from above post.
What is the problem? Do you get an error message? How to reproduce?

**Comment by vascoV** [comment] 2018-05-14 13:12
@zoechi The problem is that I can upload photos from a webview for some weird reason!

On the webview when I click add a photo (see the uploaded image) I am getting this log :
`W/zygote  ( 4158): Attempt to remove non-JNI local reference, dumping thread` nothing much

![flutter_01](https://user-images.githubusercontent.com/15817701/39999315-7ad4dc60-5791-11e8-9deb-b4de1e28802d.png)

**Comment by zoechi** [comment] 2018-07-27 15:29
Can you please report this in the plugin repo. I don't think there is anything the Flutter team can do.

**Comment by zoechi** [comment] 2018-08-31 20:32
Closing because this is about a 3rd-party plugin.

**Closed by zoechi** 2018-08-31 20:32 UTC
