### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by moun2001** [flutter/flutter#154802] opened 2024-09-08 20:46 UTC
== Building for iOS ==

> flutter build ios --debug --no-codesign
Resolving dependencies...
Downloading packages...
  _flutterfire_internals 1.3.16 (1.3.41 available)
  collection 1.18.0 (1.19.0 available)
  firebase_core 2.24.2 (3.4.0 available)
  firebase_core_web 2.10.0 (2.17.5 available)
  firebase_messaging 14.7.10 (15.1.0 available)
  firebase_messaging_platform_interface 4.5.18 (4.5.43 available)
  firebase_messaging_web 3.5.18 (3.8.13 available)
  http_parser 4.0.2 (4.1.0 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.5 (10.0.7 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.8 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  syncfusion_flutter_calendar 26.2.11+1 (26.2.13 available)
  syncfusion_flutter_core 26.2.11 (26.2.13 available)
  syncfusion_flutter_datepicker 26.2.11 (26.2.13 available)
  test_api 0.7.2 (0.7.3 available)
Got dependencies!
17 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.foodishtaridz for device (ios)...

Oops; flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path = '/Users/builder/clone/ios/Podfile'".
A crash report has been written to /Users/builder/clone/flutter_01.log
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Failed+to+decode+data+using+encoding+%27utf-8%27%2C+path+%3D+%27%2FUsers%2Fbuilder%2Fclone%2Fios%2FPodfile%27

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/to/report-bugs

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Failed+to+decode+data+using+encoding+%27utf-8%27%2C+null&body=%23%23+Command%0A%60%60%60sh%0Aflutter+build+ios+--debug+--no-codesign%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Failed+to+decode+data+using+encoding+%27utf-8%27%2C+null%0A%60%60%60console%0A%230++++++_File._tryDecode+%28dart%3Aio%2Ffile_impl.dart%3A615%3A7%29%0A%231++++++_File.readAsStringSync+%28dart%3Aio%2Ffile_impl.dart%3A624%3A7%29%0A%232++++++_File.readAsLinesSync+%28dart%3Aio%2Ffile_impl.dart%3A630%3A36%29%0A%233++++++ForwardingFile.readAsLinesSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file.dart%3A107%3A16%29%0A%234++++++ForwardingFile.readAsLinesSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file.dart%3A107%3A16%29%0A%235++++++ProjectMigrator.processFileLines+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fproject_migrator.dart%3A40%3A37%29%0A%236++++++IOSDeploymentTargetMigration.migrate+%28package%3Aflutter_tools%2Fsrc%2Fios%2Fmigrations%2Fios_deployment_target_migration.dart%3A37%3A7%29%0A%237++++++ProjectMigration.run+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fproject_migrator.dart%3A84%3A22%29%0A%3Casynchronous+suspension%3E%0A%238++++++buildXcodeProject+%28package%3Aflutter_tools%2Fsrc%2Fios%2Fmac.dart%3A182%3A3%29%0A%3Casynchronous+suspension%3E%0A%239++++++_BuildIOSSubCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fbuild_ios.dart%3A696%3A37%29%0A%3Casynchronous+suspension%3E%0A%2310+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1408%3A27%29%0A%3Casynchronous+suspension%3E%0A%2311+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A153%3A19%29%0A%3Casynchronous+suspension%3E%0A%2312+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A212%3A13%29%0A%3Casynchronous+suspension%3E%0A%2313+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A420%3A9%29%0A%3Casynchronous+suspension%3E%0A%2314+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A153%3A19%29%0A%3Casynchronous+suspension%3E%0A%2315+++++FlutterCommandRunner.runCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A364%3A5%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60console%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+3.24.2%2C+on+macOS+14.4.1+23E224+darwin-arm64%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+3.24.2+on+channel+stable+at+%2FUsers%2Fbuilder%2Fprograms%2Fflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+4cf269e36d+%285+days+ago%29%2C+2024-09-03+14%3A30%3A00+-0700%0A++++%E2%80%A2+Engine+revision+a6bd3f1de1%0A++++%E2%80%A2+Dart+version+3.5.2%0A++++%E2%80%A2+DevTools+version+2.37.2%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.0%29%0A++++%E2%80%A2+Android+SDK+at+%2Fusr%2Flocal%2Fshare%2Fandroid-sdk%0A++++%E2%80%A2+Platform+android-33%2C+build-tools+33.0.0%0A++++%E2%80%A2+ANDROID_HOME+%3D+%2Fusr%2Flocal%2Fshare%2Fandroid-sdk%0A++++%E2%80%A2+ANDROID_SDK_ROOT+%3D+%2Fusr%2Flocal%2Fshare%2Fandroid-sdk%0A++++%E2%80%A2+Java+binary+at%3A+%2FApplications%2FAndroid+Studio.app%2FContents%2Fjre%2FContents%2FHome%2Fbin%2Fjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Xcode+-+develop+for+iOS+and+macOS+%28Xcode+15.4%29%0A++++%E2%80%A2+Xcode+at+%2FApplications%2FXcode-15.4.app%2FContents%2FDeveloper%0A++++%E2%80%A2+Build+15F31d%0A++++%E2%80%A2+CocoaPods+version+1.15.2%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+%2FApplications%2FGoogle+Chrome.app%2FContents%2FMacOS%2FGoogle+Chrome%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2021.3%29%0A++++%E2%80%A2+Android+Studio+at+%2FApplications%2FAndroid+Studio.app%2FContents%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0A%0A%5B%E2%9C%93%5D+Connected+device+%283+available%29%0A++++%E2%80%A2+macOS+%28desktop%29+++++++++++++++++%E2%80%A2+macos+++++++++++++++++%E2%80%A2+darwin-arm64+++%E2%80%A2+macOS+14.4.1+23E224+darwin-arm64%0A++++%E2%80%A2+Mac+Designed+for+iPad+%28desktop%29+%E2%80%A2+mac-designed-for-ipad+%E2%80%A2+darwin+++++++++%E2%80%A2+macOS+14.4.1+23E224+darwin-arm64%0A++++%E2%80%A2+Chrome+%28web%29++++++++++++++++++++%E2%80%A2+chrome++++++++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+124.0.6367.119%0A%0A%5B%E2%9C%93%5D+Network+resources%0A++++%E2%80%A2+All+expected+network+resources+are+available.%0A%0A%E2%80%A2+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+80c2e84975bbd28ecf5f8d4bd4ca5a2490bfc819%0A%23%23%23+Plugins%0Adevice_info_plus-10.1.2%0Afile_selector_linux-0.9.2%2B1%0Afile_selector_macos-0.9.4%0Afile_selector_windows-0.9.3%2B2%0Afirebase_core-2.24.2%0Afirebase_core_web-2.10.0%0Afirebase_messaging-14.7.10%0Afirebase_messaging_web-3.5.18%0Aflutter_local_notifications-17.2.2%0Aflutter_local_notifications_linux-4.0.1%0Aflutter_plugin_android_lifecycle-2.0.22%0Aflutter_stripe-11.0.0%0Aimage_picker-1.1.2%0Aimage_picker_android-0.8.12%2B13%0Aimage_picker_for_web-3.0.5%0Aimage_picker_ios-0.8.12%0Aimage_picker_linux-0.2.1%2B1%0Aimage_picker_macos-0.2.1%2B1%0Aimage_picker_windows-0.2.1%2B1%0Apath_provider-2.1.4%0Apath_provider_android-2.2.10%0Apath_provider_foundation-2.4.0%0Apath_provider_linux-2.2.1%0Apath_provider_windows-2.3.0%0Astripe_android-11.0.0%0Astripe_ios-11.0.0%0A%0A&labels=tool%2Csevere%3A+crash

Build failed :|
Failed to build for iOS

**Comment by huycozy** [comment] 2024-09-09 10:25
## Command
```sh
flutter build ios --debug --no-codesign
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```console
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#5      ProjectMigrator.processFileLines (package:flutter_tools/src/base/project_migrator.dart:40:37)
#6      IOSDeploymentTargetMigration.migrate (package:flutter_tools/src/ios/migrations/ios_deployment_target_migration.dart:37:7)
#7      ProjectMigration.run (package:flutter_tools/src/base/project_migrator.dart:84:22)
<asynchronous suspension>
#8      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:182:3)
<asynchronous suspension>
#9      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:696:37)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    • Flutter version 3.24.2 on channel stable at /Users/builder/programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (5 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode-15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 124.0.6367.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 80c2e84975bbd28ecf5f8d4bd4ca5a2490bfc819
### Plugins
device_info_plus-10.1.2
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_core-2.24.2
firebase_core_web-2.10.0
firebase_messaging-14.7.10
firebase_messaging_web-3.5.18
flutter_local_notifications-17.2.2
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.22
flutter_stripe-11.0.0
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
stripe_android-11.0.0
stripe_ios-11.0.0

**Comment by huycozy** [comment] 2024-09-09 10:29
(The decoded info after clicking on the URL is above)

Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by huycozy** 2024-09-09 10:29 UTC
Labels: in triage
